TranslatorCzech Class Reference
#include <translator_cz.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
virtual QCString trDesignUnitHierarchy ()
virtual QCString trDesignUnitList ()
virtual QCString trDesignUnitMembers ()
virtual QCString trDesignUnitListDescription ()
virtual QCString trDesignUnitIndex ()
virtual QCString trDesignUnits ()
virtual QCString trFunctionAndProc ()
virtual QCString trVhdlType (uint64 type, bool single)
virtual QCString trCustomReference (const QCString &name)
virtual QCString trConstants ()
virtual QCString trConstantDocumentation ()
virtual QCString trSequences ()
virtual QCString trSequenceDocumentation ()
virtual QCString trDictionaries ()
virtual QCString trDictionaryDocumentation ()
virtual QCString trSliceInterfaces ()
virtual QCString trInterfaceIndex ()
virtual QCString trInterfaceList ()
virtual QCString trInterfaceListDescription ()
virtual QCString trInterfaceHierarchy ()
virtual QCString trInterfaceHierarchyDescription ()
virtual QCString trInterfaceDocumentation ()
virtual QCString trStructs ()
virtual QCString trStructIndex ()
virtual QCString trStructList ()
virtual QCString trStructListDescription ()
virtual QCString trStructDocumentation ()
virtual QCString trExceptionIndex ()
virtual QCString trExceptionList ()
virtual QCString trExceptionListDescription ()
virtual QCString trExceptionHierarchy ()
virtual QCString trExceptionHierarchyDescription ()
virtual QCString trExceptionDocumentation ()
virtual QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal)
virtual QCString trOperations ()
virtual QCString trOperationDocumentation ()
virtual QCString trDataMembers ()
virtual QCString trDataMemberDocumentation ()
virtual QCString trDesignUnitDocumentation ()
virtual QCString trConcept (bool first_capital, bool singular)
virtual QCString trConceptReference (const QCString &conceptName)
virtual QCString trConceptList ()
virtual QCString trConceptIndex ()
virtual QCString trConceptDocumentation ()
virtual QCString trConceptListDescription (bool extractAll)
virtual QCString trConceptDefinition ()
virtual QCString trPackageList ()
virtual QCString trFlowchart ()
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
virtual QCString trDesignUnitHierarchy ()
virtual QCString trDesignUnitList ()
virtual QCString trDesignUnitMembers ()
virtual QCString trDesignUnitListDescription ()
virtual QCString trDesignUnitIndex ()
virtual QCString trDesignUnits ()
virtual QCString trFunctionAndProc ()
virtual QCString trVhdlType (uint64 type, bool single)
virtual QCString trCustomReference (const QCString &name)
virtual QCString trConstants ()
virtual QCString trConstantDocumentation ()
virtual QCString trSequences ()
virtual QCString trSequenceDocumentation ()
virtual QCString trDictionaries ()
virtual QCString trDictionaryDocumentation ()
virtual QCString trSliceInterfaces ()
virtual QCString trInterfaceIndex ()
virtual QCString trInterfaceList ()
virtual QCString trInterfaceListDescription ()
virtual QCString trInterfaceHierarchy ()
virtual QCString trInterfaceHierarchyDescription ()
virtual QCString trInterfaceDocumentation ()
virtual QCString trStructs ()
virtual QCString trStructIndex ()
virtual QCString trStructList ()
virtual QCString trStructListDescription ()
virtual QCString trStructDocumentation ()
virtual QCString trExceptionIndex ()
virtual QCString trExceptionList ()
virtual QCString trExceptionListDescription ()
virtual QCString trExceptionHierarchy ()
virtual QCString trExceptionHierarchyDescription ()
virtual QCString trExceptionDocumentation ()
virtual QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal)
virtual QCString trOperations ()
virtual QCString trOperationDocumentation ()
virtual QCString trDataMembers ()
virtual QCString trDataMemberDocumentation ()
virtual QCString trDesignUnitDocumentation ()
virtual QCString trConcept (bool first_capital, bool singular)
virtual QCString trConceptReference (const QCString &conceptName)
virtual QCString trConceptList ()
virtual QCString trConceptIndex ()
virtual QCString trConceptDocumentation ()
virtual QCString trConceptListDescription (bool extractAll)
virtual QCString trConceptDefinition ()
virtual QCString trPackageList ()
virtual QCString trFlowchart ()
Detailed Description
When defining a translator class for the new language, follow the description in the documentation. One of the steps says that you should copy the translator_en.h (this) file to your translator_xx.h new file. Your new language should use the Translator class as the base class. This means that you need to implement exactly the same (pure virtual) methods as the TranslatorEnglish does. Because of this, it is a good idea to start with the copy of TranslatorEnglish and replace the strings one by one.
It is not necessary to include `translator.h` or `translator_adapter.h` here. The files are included in the language.cpp correctly. Not including any of the mentioned files frees the maintainer from thinking about whether the first, the second, or both files should be included or not, and why. This holds namely for localized translators because their base class is changed occasionally to adapter classes when the Translator class changes the interface, or back to the Translator class (by the local maintainer) when the localized translator is made up-to-date again.
Definition at line 132 of file translator_cz.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorCzech::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 178 of file translator_cz.h.
    {
      return "0x405 Czech";
    }
getLanguageString() [2/2]
virtual QCString TranslatorCzech::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 178 of file translator_cz.h.
    {
      return "0x405 Czech";
    }
idLanguage() [1/2]
virtual QCString TranslatorCzech::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 144 of file translator_cz.h.
    { return "czech"; }
idLanguage() [2/2]
virtual QCString TranslatorCzech::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 144 of file translator_cz.h.
    { return "czech"; }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorCzech::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 161 of file translator_cz.h.
    {
      return "\\usepackage[T2A]{fontenc}\n"
             "\\usepackage[czech]{babel}\n"
             "\\usepackage{regexpatch}\n"
             "\\makeatletter\n"
             "% Change the `-` delimiter to an active character\n"
             "\\xpatchparametertext\\@@@cmidrule{-}{\\cA-}{}{}\n"
             "\\xpatchparametertext\\@cline{-}{\\cA-}{}{}\n"
             "\\makeatother\n";
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorCzech::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 161 of file translator_cz.h.
    {
      return "\\usepackage[T2A]{fontenc}\n"
             "\\usepackage[czech]{babel}\n"
             "\\usepackage{regexpatch}\n"
             "\\makeatletter\n"
             "% Change the `-` delimiter to an active character\n"
             "\\xpatchparametertext\\@@@cmidrule{-}{\\cA-}{}{}\n"
             "\\xpatchparametertext\\@cline{-}{\\cA-}{}{}\n"
             "\\makeatother\n";
    }
trAdditionalInheritedMembers() [1/2]
virtual QCString TranslatorCzech::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 2048 of file translator_cz.h.
    { return "Dal zddn leny"; }
trAdditionalInheritedMembers() [2/2]
virtual QCString TranslatorCzech::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 2048 of file translator_cz.h.
    { return "Dal zddn leny"; }
trAll() [1/2]
virtual QCString TranslatorCzech::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1554 of file translator_cz.h.
    {
      return "Ve";
    }
trAll() [2/2]
virtual QCString TranslatorCzech::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1554 of file translator_cz.h.
    {
      return "Ve";
    }
trAndMore() [1/2]
virtual QCString TranslatorCzech::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 2024 of file translator_cz.h.
    { return "a "+number+" dal(ch)..."; }
trAndMore() [2/2]
virtual QCString TranslatorCzech::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 2024 of file translator_cz.h.
    { return "a "+number+" dal(ch)..."; }
trAttention() [1/2]
virtual QCString TranslatorCzech::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 1100 of file translator_cz.h.
    {
      return "Upozornn"; // ??? not checked in a context
    }
trAttention() [2/2]
virtual QCString TranslatorCzech::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 1100 of file translator_cz.h.
    {
      return "Upozornn"; // ??? not checked in a context
    }
trAuthor() [1/2]
virtual QCString TranslatorCzech::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1425 of file translator_cz.h.
    {
      QCString result((first_capital ? "Auto" : "auto"));
      result += (singular) ? "r" : "i";
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorCzech::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1425 of file translator_cz.h.
    {
      QCString result((first_capital ? "Auto" : "auto"));
      result += (singular) ? "r" : "i";
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorCzech::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1280 of file translator_cz.h.
    {
      return "Chyba";
    }
trBug() [2/2]
virtual QCString TranslatorCzech::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1280 of file translator_cz.h.
    {
      return "Chyba";
    }
trBugList() [1/2]
virtual QCString TranslatorCzech::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1285 of file translator_cz.h.
    {
      return "Seznam chyb";
    }
trBugList() [2/2]
virtual QCString TranslatorCzech::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1285 of file translator_cz.h.
    {
      return "Seznam chyb";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorCzech::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1676 of file translator_cz.h.
    {
      return "Tuto funkci volaj...";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorCzech::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1676 of file translator_cz.h.
    {
      return "Tuto funkci volaj...";
    }
trCallGraph() [1/2]
virtual QCString TranslatorCzech::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1559 of file translator_cz.h.
    {
      return "Tato funkce vol...";
    }
trCallGraph() [2/2]
virtual QCString TranslatorCzech::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1559 of file translator_cz.h.
    {
      return "Tato funkce vol...";
    }
trCiteReferences() [1/2]
virtual QCString TranslatorCzech::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 2000 of file translator_cz.h.
    { return "Odkazy na literaturu"; }
trCiteReferences() [2/2]
virtual QCString TranslatorCzech::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 2000 of file translator_cz.h.
    { return "Odkazy na literaturu"; }
trClass() [1/2]
virtual QCString TranslatorCzech::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1343 of file translator_cz.h.
    {
      QCString result((first_capital ? "Td" : "td"));
      result += singular ? "a" : "y";
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorCzech::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1343 of file translator_cz.h.
    {
      QCString result((first_capital ? "Td" : "td"));
      result += singular ? "a" : "y";
      return result;
    }
trClassDiagram() [1/2]
virtual QCString TranslatorCzech::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 638 of file translator_cz.h.
    {
      return "Diagram ddinosti pro tdu "+clName+":";
    }
trClassDiagram() [2/2]
virtual QCString TranslatorCzech::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 638 of file translator_cz.h.
    {
      return "Diagram ddinosti pro tdu "+clName+":";
    }
trClassDocumentation() [1/2]
virtual QCString TranslatorCzech::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 513 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentace datovch struktur";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Dokumentace td";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorCzech::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 513 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentace datovch struktur";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Dokumentace td";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorCzech::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1243 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datov struktury";
      }
      else
      {
        return "Tdy";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorCzech::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1243 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datov struktury";
      }
      else
      {
        return "Tdy";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorCzech::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 282 of file translator_cz.h.
    { return "Hierarchie td"; }
trClassHierarchy() [2/2]
virtual QCString TranslatorCzech::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 282 of file translator_cz.h.
    { return "Hierarchie td"; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorCzech::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 341 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return "Zde je hierarchick seznam vech entit:";
      }
      else
      {
        return "Zde naleznete seznam, vyjadujc vztah ddinosti td. "
               "Je seazen piblin (ale ne pln) podle abecedy:";
      }
    }
References Config_getBool.
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorCzech::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 341 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return "Zde je hierarchick seznam vech entit:";
      }
      else
      {
        return "Zde naleznete seznam, vyjadujc vztah ddinosti td. "
               "Je seazen piblin (ale ne pln) podle abecedy:";
      }
    }
References Config_getBool.
trClassMethods() [1/2]
virtual QCString TranslatorCzech::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 2086 of file translator_cz.h.
    {
      return "Metody tdy";
    }
trClassMethods() [2/2]
virtual QCString TranslatorCzech::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 2086 of file translator_cz.h.
    {
      return "Metody tdy";
    }
trCode() [1/2]
virtual QCString TranslatorCzech::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 1000 of file translator_cz.h.
    {
      return "zdrojov text";
    }
trCode() [2/2]
virtual QCString TranslatorCzech::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 1000 of file translator_cz.h.
    {
      return "zdrojov text";
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorCzech::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 953 of file translator_cz.h.
    {
      return "Diagram pro "+clName+":";
    }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorCzech::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 953 of file translator_cz.h.
    {
      return "Diagram pro "+clName+":";
    }
trCompoundIndex() [1/2]
virtual QCString TranslatorCzech::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 486 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Rejstk datovch struktur";
      }
      else
      {
        return "Rejstk td";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorCzech::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 486 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Rejstk datovch struktur";
      }
      else
      {
        return "Rejstk td";
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorCzech::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1731 of file translator_cz.h.
    { return "Rejstk datovch typ"; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorCzech::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1731 of file translator_cz.h.
    { return "Rejstk datovch typ"; }
trCompoundList() [1/2]
virtual QCString TranslatorCzech::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 286 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datov struktury";
      }
      else
      {
        return "Seznam td";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorCzech::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 286 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datov struktury";
      }
      else
      {
        return "Seznam td";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorCzech::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 364 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Nsledujc seznam obsahuje identifikace datovch "
               "struktur a jejich strun popisy:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Nsledujc seznam obsahuje identifikace td. "
               "V seznamu jsou uvedeny jejich strun popisy:";
      }
      else
      {
        return "Nsledujc seznam obsahuje pedevm identifikace "
               "td, ale nachzej se zde i dal netriviln prvky, "
               "jako jsou struktury (struct), unie (union) a rozhran "
               "(interface). V seznamu jsou uvedeny jejich strun "
               "popisy:";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorCzech::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 364 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Nsledujc seznam obsahuje identifikace datovch "
               "struktur a jejich strun popisy:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Nsledujc seznam obsahuje identifikace td. "
               "V seznamu jsou uvedeny jejich strun popisy:";
      }
      else
      {
        return "Nsledujc seznam obsahuje pedevm identifikace "
               "td, ale nachzej se zde i dal netriviln prvky, "
               "jako jsou struktury (struct), unie (union) a rozhran "
               "(interface). V seznamu jsou uvedeny jejich strun "
               "popisy:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorCzech::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1704 of file translator_cz.h.
    { return "Datov typy se strunmi popisy:"; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorCzech::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1704 of file translator_cz.h.
    { return "Datov typy se strunmi popisy:"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorCzech::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1696 of file translator_cz.h.
    { return "Seznam datovch typ"; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorCzech::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1696 of file translator_cz.h.
    { return "Seznam datovch typ"; }
trCompoundMembers() [1/2]
virtual QCString TranslatorCzech::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 303 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datov poloky";
      }
      else
      {
        return "Seznam len td";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorCzech::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 303 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datov poloky";
      }
      else
      {
        return "Seznam len td";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorCzech::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 388 of file translator_cz.h.
    {
      QCString result="Zde naleznete seznam vech ";
      if (!extractAll)
      {
        result+="dokumentovanch ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="poloek struktur (struct) a uni (union)";
      }
      else
      {
        result+="len td";
      }
      result+=" s odkazy na ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="struktury/unie, ke kterm psluej:";
        }
        else
        {
          result+="tdy, ke kterm psluej:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="dokumentaci struktur/uni, ke kterm psluej:";
        }
        else
        {
          result+="dokumentaci td, ke kterm psluej:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorCzech::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 388 of file translator_cz.h.
    {
      QCString result="Zde naleznete seznam vech ";
      if (!extractAll)
      {
        result+="dokumentovanch ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="poloek struktur (struct) a uni (union)";
      }
      else
      {
        result+="len td";
      }
      result+=" s odkazy na ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="struktury/unie, ke kterm psluej:";
        }
        else
        {
          result+="tdy, ke kterm psluej:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="dokumentaci struktur/uni, ke kterm psluej:";
        }
        else
        {
          result+="dokumentaci td, ke kterm psluej:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorCzech::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1708 of file translator_cz.h.
    {
      QCString result="Nsleduje seznam vech ";
      if (!extractAll)
      {
        result+="dokumentovanch ";
      }
      result+="sloek datovch typ";
      result+=" s odkazy na ";
      if (!extractAll)
      {
         result+="dokumentaci datov struktury pro kadou sloku:";
      }
      else
      {
         result+="pslun datov typy:";
      }
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorCzech::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1708 of file translator_cz.h.
    {
      QCString result="Nsleduje seznam vech ";
      if (!extractAll)
      {
        result+="dokumentovanch ";
      }
      result+="sloek datovch typ";
      result+=" s odkazy na ";
      if (!extractAll)
      {
         result+="dokumentaci datov struktury pro kadou sloku:";
      }
      else
      {
         result+="pslun datov typy:";
      }
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorCzech::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1700 of file translator_cz.h.
    { return "Datov poloky"; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorCzech::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1700 of file translator_cz.h.
    { return "Datov poloky"; }
trCompoundReference() [1/2]
virtual QCString TranslatorCzech::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 713 of file translator_cz.h.
    {
      QCString result="Dokumentace ";
      if (isTemplate) result += "ablony ";
      switch(compType)
      {
        case ClassDef::Class: result+="tdy "; break;
        case ClassDef::Struct: result+="struktury "; break;
        case ClassDef::Union: result+="unie "; break;
        case ClassDef::Interface: result+="rozhran "; break;
        case ClassDef::Protocol: result+="protokolu "; break;
        case ClassDef::Category: result+="kategorie "; break;
        case ClassDef::Exception: result+="vjimky "; break;
        default: break;
      }
      result += clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorCzech::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 713 of file translator_cz.h.
    {
      QCString result="Dokumentace ";
      if (isTemplate) result += "ablony ";
      switch(compType)
      {
        case ClassDef::Class: result+="tdy "; break;
        case ClassDef::Struct: result+="struktury "; break;
        case ClassDef::Union: result+="unie "; break;
        case ClassDef::Interface: result+="rozhran "; break;
        case ClassDef::Protocol: result+="protokolu "; break;
        case ClassDef::Category: result+="kategorie "; break;
        case ClassDef::Exception: result+="vjimky "; break;
        default: break;
      }
      result += clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorCzech::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1772 of file translator_cz.h.
    {
      QCString result="Dokumentace ";
      if (isTemplate) result += "ablony ";
      switch(compType)
      {
        case ClassDef::Class: result+="modulu "; break;
        case ClassDef::Struct: result+="typu "; break;
        case ClassDef::Union: result+="unie "; break;
        case ClassDef::Interface: result+="rozhran "; break;
        case ClassDef::Protocol: result+="protokolu "; break;
        case ClassDef::Category: result+="kategorie "; break;
        case ClassDef::Exception: result+="vjimky "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorCzech::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1772 of file translator_cz.h.
    {
      QCString result="Dokumentace ";
      if (isTemplate) result += "ablony ";
      switch(compType)
      {
        case ClassDef::Class: result+="modulu "; break;
        case ClassDef::Struct: result+="typu "; break;
        case ClassDef::Union: result+="unie "; break;
        case ClassDef::Interface: result+="rozhran "; break;
        case ClassDef::Protocol: result+="protokolu "; break;
        case ClassDef::Category: result+="kategorie "; break;
        case ClassDef::Exception: result+="vjimky "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice() [1/2]
virtual QCString TranslatorCzech::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) [inline], [virtual]
Implements Translator.
Definition at line 2376 of file translator_cz.h.
    {
      QCString result="Dokumentace";
      if (isLocal) result+=" lokln";
      switch(compType)
      {
        case ClassDef::Class: result+=" tdy "; break;
        case ClassDef::Struct: result+=" struktury "; break;
        case ClassDef::Union: result+=" unie "; break;
        case ClassDef::Interface:
                                   if (isLocal) result+="ho";
                                   result+=" rozhran "; break;
        case ClassDef::Protocol:
                                   if (isLocal) result+="ho";
                                   result+=" protokolu "; break;
        case ClassDef::Category: result+=" kategorie "; break;
        case ClassDef::Exception: result+=" vyjmky "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice() [2/2]
virtual QCString TranslatorCzech::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) [inline], [virtual]
Implements Translator.
Definition at line 2376 of file translator_cz.h.
    {
      QCString result="Dokumentace";
      if (isLocal) result+=" lokln";
      switch(compType)
      {
        case ClassDef::Class: result+=" tdy "; break;
        case ClassDef::Struct: result+=" struktury "; break;
        case ClassDef::Union: result+=" unie "; break;
        case ClassDef::Interface:
                                   if (isLocal) result+="ho";
                                   result+=" rozhran "; break;
        case ClassDef::Protocol:
                                   if (isLocal) result+="ho";
                                   result+=" protokolu "; break;
        case ClassDef::Category: result+=" kategorie "; break;
        case ClassDef::Exception: result+=" vyjmky "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorCzech::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 614 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datov struktury";
      }
      else
      {
        return "Tdy";
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorCzech::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 614 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datov struktury";
      }
      else
      {
        return "Tdy";
      }
    }
References Config_getBool.
trConcept() [1/2]
virtual QCString TranslatorCzech::trConcept (bool first_capital, bool singular) [inline], [virtual]
C++20 concept
Implements Translator.
Definition at line 2428 of file translator_cz.h.
    {
      QCString result((first_capital ? "Koncept" : "koncept"));
      if (!singular) result+="y";
      return result;
    }
trConcept() [2/2]
virtual QCString TranslatorCzech::trConcept (bool first_capital, bool singular) [inline], [virtual]
C++20 concept
Implements Translator.
Definition at line 2428 of file translator_cz.h.
    {
      QCString result((first_capital ? "Koncept" : "koncept"));
      if (!singular) result+="y";
      return result;
    }
trConceptDefinition() [1/2]
virtual QCString TranslatorCzech::trConceptDefinition () [inline], [virtual]
used to introduce the definition of the C++20 concept
Implements Translator.
Definition at line 2464 of file translator_cz.h.
    {
      return "Definice koncept";
    }
trConceptDefinition() [2/2]
virtual QCString TranslatorCzech::trConceptDefinition () [inline], [virtual]
used to introduce the definition of the C++20 concept
Implements Translator.
Definition at line 2464 of file translator_cz.h.
    {
      return "Definice koncept";
    }
trConceptDocumentation() [1/2]
virtual QCString TranslatorCzech::trConceptDocumentation () [inline], [virtual]
used as the title of chapter containing all information about concepts.
Implements Translator.
Definition at line 2451 of file translator_cz.h.
    { return "Dokumentace koncept"; }
trConceptDocumentation() [2/2]
virtual QCString TranslatorCzech::trConceptDocumentation () [inline], [virtual]
used as the title of chapter containing all information about concepts.
Implements Translator.
Definition at line 2451 of file translator_cz.h.
    { return "Dokumentace koncept"; }
trConceptIndex() [1/2]
virtual QCString TranslatorCzech::trConceptIndex () [inline], [virtual]
used as the title of chapter containing the index listing all concepts.
Implements Translator.
Definition at line 2447 of file translator_cz.h.
    { return "Rejstk koncept"; }
trConceptIndex() [2/2]
virtual QCString TranslatorCzech::trConceptIndex () [inline], [virtual]
used as the title of chapter containing the index listing all concepts.
Implements Translator.
Definition at line 2447 of file translator_cz.h.
    { return "Rejstk koncept"; }
trConceptList() [1/2]
virtual QCString TranslatorCzech::trConceptList () [inline], [virtual]
used as the title of page containing all the index of all concepts.
Implements Translator.
Definition at line 2443 of file translator_cz.h.
    { return "Seznam koncept"; }
trConceptList() [2/2]
virtual QCString TranslatorCzech::trConceptList () [inline], [virtual]
used as the title of page containing all the index of all concepts.
Implements Translator.
Definition at line 2443 of file translator_cz.h.
    { return "Seznam koncept"; }
trConceptListDescription() [1/2]
virtual QCString TranslatorCzech::trConceptListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the concept list
Implements Translator.
Definition at line 2455 of file translator_cz.h.
    {
      QCString result="Nsleduje seznam vech ";
      if (!extractAll) result+="dokumentovanch ";
      result+="koncept se strunmi popisy:";
      return result;
    }
trConceptListDescription() [2/2]
virtual QCString TranslatorCzech::trConceptListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the concept list
Implements Translator.
Definition at line 2455 of file translator_cz.h.
    {
      QCString result="Nsleduje seznam vech ";
      if (!extractAll) result+="dokumentovanch ";
      result+="koncept se strunmi popisy:";
      return result;
    }
trConceptReference() [1/2]
virtual QCString TranslatorCzech::trConceptReference (const QCString & conceptName) [inline], [virtual]
used as the title of the HTML page of a C++20 concept page
Implements Translator.
Definition at line 2435 of file translator_cz.h.
    {
      QCString result="Dokumentace konceptu ";
      result+=conceptName;
      return result;
    }
trConceptReference() [2/2]
virtual QCString TranslatorCzech::trConceptReference (const QCString & conceptName) [inline], [virtual]
used as the title of the HTML page of a C++20 concept page
Implements Translator.
Definition at line 2435 of file translator_cz.h.
    {
      QCString result="Dokumentace konceptu ";
      result+=conceptName;
      return result;
    }
trConstantDocumentation() [1/2]
virtual QCString TranslatorCzech::trConstantDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2284 of file translator_cz.h.
    {
        return "Dokumentace konstant";
    }
trConstantDocumentation() [2/2]
virtual QCString TranslatorCzech::trConstantDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2284 of file translator_cz.h.
    {
        return "Dokumentace konstant";
    }
trConstantGroupReference() [1/2]
virtual QCString TranslatorCzech::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 2123 of file translator_cz.h.
    {
      QCString result="Konstantn skupiny z ";
      result+=namespaceName;
      return result;
    }
trConstantGroupReference() [2/2]
virtual QCString TranslatorCzech::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 2123 of file translator_cz.h.
    {
      QCString result="Konstantn skupiny z ";
      result+=namespaceName;
      return result;
    }
trConstantGroups() [1/2]
virtual QCString TranslatorCzech::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 2119 of file translator_cz.h.
    { return "Konstantn skupiny"; }
trConstantGroups() [2/2]
virtual QCString TranslatorCzech::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 2119 of file translator_cz.h.
    { return "Konstantn skupiny"; }
trConstants() [1/2]
virtual QCString TranslatorCzech::trConstants () [inline], [virtual]
Implements Translator.
Definition at line 2280 of file translator_cz.h.
    {
        return "Konstanty";
    }
trConstants() [2/2]
virtual QCString TranslatorCzech::trConstants () [inline], [virtual]
Implements Translator.
Definition at line 2280 of file translator_cz.h.
    {
        return "Konstanty";
    }
trConstructorDocumentation() [1/2]
virtual QCString TranslatorCzech::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 963 of file translator_cz.h.
    {
      return "Dokumentace konstruktoru a destruktoru";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorCzech::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 963 of file translator_cz.h.
    {
      return "Dokumentace konstruktoru a destruktoru";
    }
trCopyright() [1/2]
virtual QCString TranslatorCzech::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 2004 of file translator_cz.h.
    { return "Copyright"; }
trCopyright() [2/2]
virtual QCString TranslatorCzech::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 2004 of file translator_cz.h.
    { return "Copyright"; }
trCustomReference() [1/2]
virtual QCString TranslatorCzech::trCustomReference (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 2276 of file translator_cz.h.
    { return "Dokumentace pro "+name; }
References setup::name.
trCustomReference() [2/2]
virtual QCString TranslatorCzech::trCustomReference (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 2276 of file translator_cz.h.
    { return "Dokumentace pro "+name; }
References setup::name.
trDataMemberDocumentation() [1/2]
virtual QCString TranslatorCzech::trDataMemberDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2410 of file translator_cz.h.
    {
        return "Dokumentace datovch len";
    }
trDataMemberDocumentation() [2/2]
virtual QCString TranslatorCzech::trDataMemberDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2410 of file translator_cz.h.
    {
        return "Dokumentace datovch len";
    }
trDataMembers() [1/2]
virtual QCString TranslatorCzech::trDataMembers () [inline], [virtual]
Implements Translator.
Definition at line 2406 of file translator_cz.h.
    {
        return "Datov leny";
    }
trDataMembers() [2/2]
virtual QCString TranslatorCzech::trDataMembers () [inline], [virtual]
Implements Translator.
Definition at line 2406 of file translator_cz.h.
    {
        return "Datov leny";
    }
trDataTypes() [1/2]
virtual QCString TranslatorCzech::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1755 of file translator_cz.h.
    { return "Datov typy"; }
trDataTypes() [2/2]
virtual QCString TranslatorCzech::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1755 of file translator_cz.h.
    { return "Datov typy"; }
trDate() [1/2]
virtual QCString TranslatorCzech::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 652 of file translator_cz.h.
    { return "Datum"; }
trDate() [2/2]
virtual QCString TranslatorCzech::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 652 of file translator_cz.h.
    { return "Datum"; }
trDateTime() [1/2]
virtual QCString TranslatorCzech::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1957 of file translator_cz.h.
    {
      static const char *days[] = { "po","t","st","t","p","so","ne" };
      static const char *months[] = { "led","no","be","dub","kv","er","ec","srp","z","j","lis","pro" };
      QCString sdate;
      sdate.sprintf("%s %d. %s %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d.%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDateTime() [2/2]
virtual QCString TranslatorCzech::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1957 of file translator_cz.h.
    {
      static const char *days[] = { "po","t","st","t","p","so","ne" };
      static const char *months[] = { "led","no","be","dub","kv","er","ec","srp","z","j","lis","pro" };
      QCString sdate;
      sdate.sprintf("%s %d. %s %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d.%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDayOfWeek() [1/2]
virtual QCString TranslatorCzech::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1973 of file translator_cz.h.
    {
      static const char *days_short[] = { "po", "t", "st", "t", "p", "so", "ne" };
      static const char *days_full[] = { "pondl", "ter", "steda", "tvrtek", "ptek", "sobota", "nedle" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayOfWeek() [2/2]
virtual QCString TranslatorCzech::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1973 of file translator_cz.h.
    {
      static const char *days_short[] = { "po", "t", "st", "t", "p", "so", "ne" };
      static const char *days_full[] = { "pondl", "ter", "steda", "tvrtek", "ptek", "sobota", "nedle" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod() [1/2]
virtual QCString TranslatorCzech::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1989 of file translator_cz.h.
    {
      static const char *dayPeriod[] = { "dop.", "odp." };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorCzech::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1989 of file translator_cz.h.
    {
      static const char *dayPeriod[] = { "dop.", "odp." };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorCzech::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 930 of file translator_cz.h.
    {
      return "Definice je uvedena na dku @0 v souboru @1.";
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorCzech::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 930 of file translator_cz.h.
    {
      return "Definice je uvedena na dku @0 v souboru @1.";
    }
trDefinedIn() [1/2]
virtual QCString TranslatorCzech::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 270 of file translator_cz.h.
    { return "definovn v"; }
trDefinedIn() [2/2]
virtual QCString TranslatorCzech::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 270 of file translator_cz.h.
    { return "definovn v"; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorCzech::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 934 of file translator_cz.h.
    {
      return "Definice v souboru @0.";
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorCzech::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 934 of file translator_cz.h.
    {
      return "Definice v souboru @0.";
    }
trDefineDocumentation() [1/2]
virtual QCString TranslatorCzech::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 584 of file translator_cz.h.
    { return "Dokumentace definic maker"; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorCzech::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 584 of file translator_cz.h.
    { return "Dokumentace definic maker"; }
trDefines() [1/2]
virtual QCString TranslatorCzech::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 548 of file translator_cz.h.
    { return "Definice maker"; }
trDefines() [2/2]
virtual QCString TranslatorCzech::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 548 of file translator_cz.h.
    { return "Definice maker"; }
trDefineValue() [1/2]
virtual QCString TranslatorCzech::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1270 of file translator_cz.h.
    {
      return "Hodnota:";
    }
trDefineValue() [2/2]
virtual QCString TranslatorCzech::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1270 of file translator_cz.h.
    {
      return "Hodnota:";
    }
trDeprecated() [1/2]
virtual QCString TranslatorCzech::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 943 of file translator_cz.h.
    {
      return "Zastaral";
    }
trDeprecated() [2/2]
virtual QCString TranslatorCzech::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 943 of file translator_cz.h.
    {
      return "Zastaral";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorCzech::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1482 of file translator_cz.h.
    {
      return "Seznam zastaralch prvk";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorCzech::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1482 of file translator_cz.h.
    {
      return "Seznam zastaralch prvk";
    }
trDesignUnitDocumentation() [1/2]
virtual QCString TranslatorCzech::trDesignUnitDocumentation () [inline], [virtual]
VHDL design unit documentation
Implements Translator.
Definition at line 2420 of file translator_cz.h.
    { return "Dokumentace nvrhov jednotky"; }
Referenced by trClassDocumentation().
trDesignUnitDocumentation() [2/2]
virtual QCString TranslatorCzech::trDesignUnitDocumentation () [inline], [virtual]
VHDL design unit documentation
Implements Translator.
Definition at line 2420 of file translator_cz.h.
    { return "Dokumentace nvrhov jednotky"; }
trDesignUnitHierarchy() [1/2]
virtual QCString TranslatorCzech::trDesignUnitHierarchy () [inline], [virtual]
VHDL design unit hierarchy
Implements Translator.
Definition at line 2167 of file translator_cz.h.
    { return "Hierarchie nvrhovch jednotek"; }
trDesignUnitHierarchy() [2/2]
virtual QCString TranslatorCzech::trDesignUnitHierarchy () [inline], [virtual]
VHDL design unit hierarchy
Implements Translator.
Definition at line 2167 of file translator_cz.h.
    { return "Hierarchie nvrhovch jednotek"; }
trDesignUnitIndex() [1/2]
virtual QCString TranslatorCzech::trDesignUnitIndex () [inline], [virtual]
VHDL design unit index
Implements Translator.
Definition at line 2182 of file translator_cz.h.
    { return "Rejstk nvrhovch jednotek"; }
trDesignUnitIndex() [2/2]
virtual QCString TranslatorCzech::trDesignUnitIndex () [inline], [virtual]
VHDL design unit index
Implements Translator.
Definition at line 2182 of file translator_cz.h.
    { return "Rejstk nvrhovch jednotek"; }
trDesignUnitList() [1/2]
virtual QCString TranslatorCzech::trDesignUnitList () [inline], [virtual]
VHDL design unit list
Implements Translator.
Definition at line 2170 of file translator_cz.h.
    { return "Seznam nvrhovch jednotek"; }
trDesignUnitList() [2/2]
virtual QCString TranslatorCzech::trDesignUnitList () [inline], [virtual]
VHDL design unit list
Implements Translator.
Definition at line 2170 of file translator_cz.h.
    { return "Seznam nvrhovch jednotek"; }
trDesignUnitListDescription() [1/2]
virtual QCString TranslatorCzech::trDesignUnitListDescription () [inline], [virtual]
VHDL design unit list description
Implements Translator.
Definition at line 2176 of file translator_cz.h.
    {
        return "Zde naleznete seznam vech len nvrhov jednotky s odkazy na "
            "entity, ke kterm psluej:";
    }
trDesignUnitListDescription() [2/2]
virtual QCString TranslatorCzech::trDesignUnitListDescription () [inline], [virtual]
VHDL design unit list description
Implements Translator.
Definition at line 2176 of file translator_cz.h.
    {
        return "Zde naleznete seznam vech len nvrhov jednotky s odkazy na "
            "entity, ke kterm psluej:";
    }
trDesignUnitMembers() [1/2]
virtual QCString TranslatorCzech::trDesignUnitMembers () [inline], [virtual]
VHDL design unit members
Implements Translator.
Definition at line 2173 of file translator_cz.h.
    { return "Seznam len nvrhovch jednotek"; }
trDesignUnitMembers() [2/2]
virtual QCString TranslatorCzech::trDesignUnitMembers () [inline], [virtual]
VHDL design unit members
Implements Translator.
Definition at line 2173 of file translator_cz.h.
    { return "Seznam len nvrhovch jednotek"; }
trDesignUnits() [1/2]
virtual QCString TranslatorCzech::trDesignUnits () [inline], [virtual]
VHDL design units
Implements Translator.
Definition at line 2185 of file translator_cz.h.
    { return "Nvrhov jednotky"; }
trDesignUnits() [2/2]
virtual QCString TranslatorCzech::trDesignUnits () [inline], [virtual]
VHDL design units
Implements Translator.
Definition at line 2185 of file translator_cz.h.
    { return "Nvrhov jednotky"; }
trDetailedDescription() [1/2]
virtual QCString TranslatorCzech::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 193 of file translator_cz.h.
    { return "Detailn popis"; }
trDetailedDescription() [2/2]
virtual QCString TranslatorCzech::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 193 of file translator_cz.h.
    { return "Detailn popis"; }
trDetailLevel() [1/2]
virtual QCString TranslatorCzech::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 2016 of file translator_cz.h.
    { return "rove detail"; }
trDetailLevel() [2/2]
virtual QCString TranslatorCzech::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 2016 of file translator_cz.h.
    { return "rove detail"; }
trDictionaries() [1/2]
virtual QCString TranslatorCzech::trDictionaries () [inline], [virtual]
Implements Translator.
Definition at line 2296 of file translator_cz.h.
    {
        return "Slovnky";
    }
trDictionaries() [2/2]
virtual QCString TranslatorCzech::trDictionaries () [inline], [virtual]
Implements Translator.
Definition at line 2296 of file translator_cz.h.
    {
        return "Slovnky";
    }
trDictionaryDocumentation() [1/2]
virtual QCString TranslatorCzech::trDictionaryDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2300 of file translator_cz.h.
    {
        return "Dokumentace slovnku";
    }
trDictionaryDocumentation() [2/2]
virtual QCString TranslatorCzech::trDictionaryDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2300 of file translator_cz.h.
    {
        return "Dokumentace slovnku";
    }
trDir() [1/2]
virtual QCString TranslatorCzech::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in singular or plural form (singular).
Implements Translator.
Definition at line 1650 of file translator_cz.h.
    {
      QCString result((first_capital ? "Adres" : "adres"));
      if (!singular) result+="e";
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorCzech::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in singular or plural form (singular).
Implements Translator.
Definition at line 1650 of file translator_cz.h.
    {
      QCString result((first_capital ? "Adres" : "adres"));
      if (!singular) result+="e";
      return result;
    }
trDirDepGraph() [1/2]
virtual QCString TranslatorCzech::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 2008 of file translator_cz.h.
    { return "Graf zvislosti na adresch pro "+name+":"; } // ??? not checked in a context
References setup::name.
trDirDepGraph() [2/2]
virtual QCString TranslatorCzech::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 2008 of file translator_cz.h.
    { return "Graf zvislosti na adresch pro "+name+":"; } // ??? not checked in a context
References setup::name.
trDirDocumentation() [1/2]
virtual QCString TranslatorCzech::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1632 of file translator_cz.h.
    { return "Dokumentace adres"; }
trDirDocumentation() [2/2]
virtual QCString TranslatorCzech::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1632 of file translator_cz.h.
    { return "Dokumentace adres"; }
trDirectories() [1/2]
virtual QCString TranslatorCzech::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1638 of file translator_cz.h.
    { return "Adrese"; }
trDirectories() [2/2]
virtual QCString TranslatorCzech::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1638 of file translator_cz.h.
    { return "Adrese"; }
trDirIndex() [1/2]
virtual QCString TranslatorCzech::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1626 of file translator_cz.h.
    { return "Hierarchie adres"; }
trDirIndex() [2/2]
virtual QCString TranslatorCzech::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1626 of file translator_cz.h.
    { return "Hierarchie adres"; }
trDirReference() [1/2]
virtual QCString TranslatorCzech::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1644 of file translator_cz.h.
    { QCString result="Reference k adresi "; result+=dirName; return result; }
trDirReference() [2/2]
virtual QCString TranslatorCzech::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1644 of file translator_cz.h.
    { QCString result="Reference k adresi "; result+=dirName; return result; }
trDirRelation() [1/2]
virtual QCString TranslatorCzech::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1896 of file translator_cz.h.
    {
      return "Relace "+name; // ??? not checked in a context
    }
References setup::name.
trDirRelation() [2/2]
virtual QCString TranslatorCzech::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1896 of file translator_cz.h.
    {
      return "Relace "+name; // ??? not checked in a context
    }
References setup::name.
trDocumentation() [1/2]
virtual QCString TranslatorCzech::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 468 of file translator_cz.h.
    { return "Dokumentace"; }
trDocumentation() [2/2]
virtual QCString TranslatorCzech::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 468 of file translator_cz.h.
    { return "Dokumentace"; }
trEnumerations() [1/2]
virtual QCString TranslatorCzech::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 560 of file translator_cz.h.
    { return "Vty"; }
trEnumerations() [2/2]
virtual QCString TranslatorCzech::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 560 of file translator_cz.h.
    { return "Vty"; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorCzech::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 596 of file translator_cz.h.
    { return "Dokumentace vtovch typ"; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorCzech::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 596 of file translator_cz.h.
    { return "Dokumentace vtovch typ"; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorCzech::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1684 of file translator_cz.h.
    { return "Dokumentace vtovch hodnot"; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorCzech::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1684 of file translator_cz.h.
    { return "Dokumentace vtovch hodnot"; }
trEnumerationValues() [1/2]
virtual QCString TranslatorCzech::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 578 of file translator_cz.h.
    { return "Hodnoty vtu"; }
trEnumerationValues() [2/2]
virtual QCString TranslatorCzech::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 578 of file translator_cz.h.
    { return "Hodnoty vtu"; }
trEnumGeneratedFromFiles() [1/2]
virtual QCString TranslatorCzech::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 2028 of file translator_cz.h.
    { QCString result = "Dokumentace pro tento vet byla vygenerovna z nsledujc";
      if (single)
          result += "ho souboru:";
      else
          result += "ch soubor:";
      return result;
    }
trEnumGeneratedFromFiles() [2/2]
virtual QCString TranslatorCzech::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 2028 of file translator_cz.h.
    { QCString result = "Dokumentace pro tento vet byla vygenerovna z nsledujc";
      if (single)
          result += "ho souboru:";
      else
          result += "ch soubor:";
      return result;
    }
trEnumName() [1/2]
virtual QCString TranslatorCzech::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 262 of file translator_cz.h.
    { return "jmno vtu"; }
trEnumName() [2/2]
virtual QCString TranslatorCzech::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 262 of file translator_cz.h.
    { return "jmno vtu"; }
trEnumReference() [1/2]
virtual QCString TranslatorCzech::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 2038 of file translator_cz.h.
    { return "Reference k vtu "+name; }
References setup::name.
trEnumReference() [2/2]
virtual QCString TranslatorCzech::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 2038 of file translator_cz.h.
    { return "Reference k vtu "+name; }
References setup::name.
trEnumValue() [1/2]
virtual QCString TranslatorCzech::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 266 of file translator_cz.h.
    { return "hodnota vtu"; }
trEnumValue() [2/2]
virtual QCString TranslatorCzech::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 266 of file translator_cz.h.
    { return "hodnota vtu"; }
trEventDocumentation() [1/2]
virtual QCString TranslatorCzech::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1499 of file translator_cz.h.
    {
      return "Dokumentace udlost";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorCzech::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1499 of file translator_cz.h.
    {
      return "Dokumentace udlost";
    }
trEvents() [1/2]
virtual QCString TranslatorCzech::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1494 of file translator_cz.h.
    {
      return "Udlosti";
    }
trEvents() [2/2]
virtual QCString TranslatorCzech::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1494 of file translator_cz.h.
    {
      return "Udlosti";
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorCzech::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 538 of file translator_cz.h.
    { return "Dokumentace pklad"; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorCzech::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 538 of file translator_cz.h.
    { return "Dokumentace pklad"; }
trExamples() [1/2]
virtual QCString TranslatorCzech::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 333 of file translator_cz.h.
    { return "Pklady"; }
trExamples() [2/2]
virtual QCString TranslatorCzech::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 333 of file translator_cz.h.
    { return "Pklady"; }
trExamplesDescription() [1/2]
virtual QCString TranslatorCzech::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 454 of file translator_cz.h.
    { return "Zde naleznete seznam vech pklad:"; }
trExamplesDescription() [2/2]
virtual QCString TranslatorCzech::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 454 of file translator_cz.h.
    { return "Zde naleznete seznam vech pklad:"; }
trExceptionDocumentation() [1/2]
virtual QCString TranslatorCzech::trExceptionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2372 of file translator_cz.h.
    {
        return "Dokumentace vyjmek";
    }
trExceptionDocumentation() [2/2]
virtual QCString TranslatorCzech::trExceptionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2372 of file translator_cz.h.
    {
        return "Dokumentace vyjmek";
    }
trExceptionHierarchy() [1/2]
virtual QCString TranslatorCzech::trExceptionHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2364 of file translator_cz.h.
    {
        return "Hierarchie vyjmek";
    }
trExceptionHierarchy() [2/2]
virtual QCString TranslatorCzech::trExceptionHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2364 of file translator_cz.h.
    {
        return "Hierarchie vyjmek";
    }
trExceptionHierarchyDescription() [1/2]
virtual QCString TranslatorCzech::trExceptionHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2368 of file translator_cz.h.
    {
        return "Zde naleznete seznam, vyjadujc vztah ddinosti vyjmek. Je seazen piblin (ale ne pln) podle abecedy:";
    }
trExceptionHierarchyDescription() [2/2]
virtual QCString TranslatorCzech::trExceptionHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2368 of file translator_cz.h.
    {
        return "Zde naleznete seznam, vyjadujc vztah ddinosti vyjmek. Je seazen piblin (ale ne pln) podle abecedy:";
    }
trExceptionIndex() [1/2]
virtual QCString TranslatorCzech::trExceptionIndex () [inline], [virtual]
Implements Translator.
Definition at line 2352 of file translator_cz.h.
    {
        return "Rejstk vyjmek";
    }
trExceptionIndex() [2/2]
virtual QCString TranslatorCzech::trExceptionIndex () [inline], [virtual]
Implements Translator.
Definition at line 2352 of file translator_cz.h.
    {
        return "Rejstk vyjmek";
    }
trExceptionList() [1/2]
virtual QCString TranslatorCzech::trExceptionList () [inline], [virtual]
Implements Translator.
Definition at line 2356 of file translator_cz.h.
    {
        return "Seznam vyjmek";
    }
trExceptionList() [2/2]
virtual QCString TranslatorCzech::trExceptionList () [inline], [virtual]
Implements Translator.
Definition at line 2356 of file translator_cz.h.
    {
        return "Seznam vyjmek";
    }
trExceptionListDescription() [1/2]
virtual QCString TranslatorCzech::trExceptionListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2360 of file translator_cz.h.
    {
        return "Nsledujc seznam obsahuje jmna vjmek a jejich strun popisy:";
    }
trExceptionListDescription() [2/2]
virtual QCString TranslatorCzech::trExceptionListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2360 of file translator_cz.h.
    {
        return "Nsledujc seznam obsahuje jmna vjmek a jejich strun popisy:";
    }
trExceptions() [1/2]
virtual QCString TranslatorCzech::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 668 of file translator_cz.h.
    { return "Vjimky"; }
trExceptions() [2/2]
virtual QCString TranslatorCzech::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 668 of file translator_cz.h.
    { return "Vjimky"; }
trExtendsClass() [1/2]
virtual QCString TranslatorCzech::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 2078 of file translator_cz.h.
    {
      return "Roziuje tdu @0.";
    }
trExtendsClass() [2/2]
virtual QCString TranslatorCzech::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 2078 of file translator_cz.h.
    {
      return "Roziuje tdu @0.";
    }
trFile() [1/2]
virtual QCString TranslatorCzech::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1354 of file translator_cz.h.
    {
      QCString result((first_capital ? "Soubor" : "soubor"));
      if (!singular) result+="y";
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorCzech::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1354 of file translator_cz.h.
    {
      QCString result((first_capital ? "Soubor" : "soubor"));
      if (!singular) result+="y";
      return result;
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorCzech::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 532 of file translator_cz.h.
    { return "Dokumentace soubor"; }
trFileDocumentation() [2/2]
virtual QCString TranslatorCzech::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 532 of file translator_cz.h.
    { return "Dokumentace soubor"; }
trFileIn() [1/2]
virtual QCString TranslatorCzech::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1933 of file translator_cz.h.
    {
      return "Soubor v "+name;
    }
References setup::name.
trFileIn() [2/2]
virtual QCString TranslatorCzech::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1933 of file translator_cz.h.
    {
      return "Soubor v "+name;
    }
References setup::name.
trFileIndex() [1/2]
virtual QCString TranslatorCzech::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 501 of file translator_cz.h.
    { return "Rejstk soubor"; }
trFileIndex() [2/2]
virtual QCString TranslatorCzech::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 501 of file translator_cz.h.
    { return "Rejstk soubor"; }
trFileList() [1/2]
virtual QCString TranslatorCzech::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 299 of file translator_cz.h.
    { return "Seznam soubor"; }
trFileList() [2/2]
virtual QCString TranslatorCzech::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 299 of file translator_cz.h.
    { return "Seznam soubor"; }
trFileListDescription() [1/2]
virtual QCString TranslatorCzech::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 355 of file translator_cz.h.
    {
      QCString result="Zde naleznete seznam vech ";
      if (!extractAll) result+="dokumentovanch ";
      result+="soubor se strunmi popisy:";
      return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorCzech::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 355 of file translator_cz.h.
    {
      QCString result="Zde naleznete seznam vech ";
      if (!extractAll) result+="dokumentovanch ";
      result+="soubor se strunmi popisy:";
      return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorCzech::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 316 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globln symboly";
      }
      else
      {
        return "Symboly v souborech";
      }
    }
References Config_getBool.
trFileMembers() [2/2]
virtual QCString TranslatorCzech::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 316 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globln symboly";
      }
      else
      {
        return "Symboly v souborech";
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
virtual QCString TranslatorCzech::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 430 of file translator_cz.h.
    {
      QCString result="Zde naleznete seznam vech ";
      if (!extractAll) result+="dokumentovanch ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funkc, promnnch, maker, vt a definic typ (typedef) "
                "s odkazy";
      }
      else
      {
        result+="symbol, kter jsou definovny na rovni svch soubor. "
                "Pro kad symbol je uveden odkaz";
      }
      result+=" na ";
      if (extractAll)
        result+="soubory, ke kterm psluej:";
      else
        result+="dokumentaci:";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorCzech::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 430 of file translator_cz.h.
    {
      QCString result="Zde naleznete seznam vech ";
      if (!extractAll) result+="dokumentovanch ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funkc, promnnch, maker, vt a definic typ (typedef) "
                "s odkazy";
      }
      else
      {
        result+="symbol, kter jsou definovny na rovni svch soubor. "
                "Pro kad symbol je uveden odkaz";
      }
      result+=" na ";
      if (extractAll)
        result+="soubory, ke kterm psluej:";
      else
        result+="dokumentaci:";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorCzech::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 735 of file translator_cz.h.
    {
      QCString result="Dokumentace souboru ";
      result+=fileName;
      return result;
    }
trFileReference() [2/2]
virtual QCString TranslatorCzech::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 735 of file translator_cz.h.
    {
      QCString result="Dokumentace souboru ";
      result+=fileName;
      return result;
    }
trFlowchart() [1/2]
virtual QCString TranslatorCzech::trFlowchart () [inline], [virtual]
This is used for translation of the word that will be followed by a single name of the VHDL process flowchart.
Implements Translator.
Definition at line 2483 of file translator_cz.h.
    { return "Vvojov diagram: "; }
trFlowchart() [2/2]
virtual QCString TranslatorCzech::trFlowchart () [inline], [virtual]
This is used for translation of the word that will be followed by a single name of the VHDL process flowchart.
Implements Translator.
Definition at line 2483 of file translator_cz.h.
    { return "Vvojov diagram: "; }
trFriends() [1/2]
virtual QCString TranslatorCzech::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 695 of file translator_cz.h.
    { return "Ptel tdy"; }
trFriends() [2/2]
virtual QCString TranslatorCzech::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 695 of file translator_cz.h.
    { return "Ptel tdy"; }
trFunctionAndProc() [1/2]
virtual QCString TranslatorCzech::trFunctionAndProc () [inline], [virtual]
VHDL functions/procedures/processes
Implements Translator.
Definition at line 2188 of file translator_cz.h.
    { return "Funkce/Procedury/Procesy"; }
trFunctionAndProc() [2/2]
virtual QCString TranslatorCzech::trFunctionAndProc () [inline], [virtual]
VHDL functions/procedures/processes
Implements Translator.
Definition at line 2188 of file translator_cz.h.
    { return "Funkce/Procedury/Procesy"; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorCzech::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 602 of file translator_cz.h.
    { return "Dokumentace funkc"; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorCzech::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 602 of file translator_cz.h.
    { return "Dokumentace funkc"; }
trFunctions() [1/2]
virtual QCString TranslatorCzech::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 566 of file translator_cz.h.
    { return "Funkce"; }
trFunctions() [2/2]
virtual QCString TranslatorCzech::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 566 of file translator_cz.h.
    { return "Funkce"; }
trGeneratedAt() [1/2]
virtual QCString TranslatorCzech::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 629 of file translator_cz.h.
    {
      QCString result="Vygenerovno dne: "+date;
      if (!projName.isEmpty()) result +=", pro projekt: "+projName;
      result+=", programem";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorCzech::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 629 of file translator_cz.h.
    {
      QCString result="Vygenerovno dne: "+date;
      if (!projName.isEmpty()) result +=", pro projekt: "+projName;
      result+=", programem";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorCzech::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 253 of file translator_cz.h.
    { QCString result="Vygenerovno automaticky programem Doxygen "
                      "ze zdrojovch text";
      if (!s.isEmpty()) result+=" projektu "+s;
      result+=".";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorCzech::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 253 of file translator_cz.h.
    { QCString result="Vygenerovno automaticky programem Doxygen "
                      "ze zdrojovch text";
      if (!s.isEmpty()) result+=" projektu "+s;
      result+=".";
      return result;
    }
References s.
trGeneratedBy() [1/2]
virtual QCString TranslatorCzech::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 672 of file translator_cz.h.
    { return "Vygenerovno programem"; }
trGeneratedBy() [2/2]
virtual QCString TranslatorCzech::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 672 of file translator_cz.h.
    { return "Vygenerovno programem"; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorCzech::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 885 of file translator_cz.h.
    { // single is true implies a single file
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      QCString result="Dokumentace pro ";
      switch(compType)
      {
        case ClassDef::Class: result+=vhdlOpt?"tuto nvrhovou jednotku":"tuto tdu"; break;
        case ClassDef::Struct: result+="tuto strukturu"; break;
        case ClassDef::Union: result+="tuto unii"; break;
        case ClassDef::Interface: result+="toto rozhran"; break;
        case ClassDef::Protocol: result+="tento protokol"; break;
        case ClassDef::Category: result+="tuto kategorii"; break;
        case ClassDef::Exception: result+="tuto vjimku"; break;
        default: break;
      }
      result+=" byla vygenerovna z nsledujc";
      if (single) result+="ho souboru:";
      else result+="ch soubor:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, Config_getBool, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorCzech::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 885 of file translator_cz.h.
    { // single is true implies a single file
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      QCString result="Dokumentace pro ";
      switch(compType)
      {
        case ClassDef::Class: result+=vhdlOpt?"tuto nvrhovou jednotku":"tuto tdu"; break;
        case ClassDef::Struct: result+="tuto strukturu"; break;
        case ClassDef::Union: result+="tuto unii"; break;
        case ClassDef::Interface: result+="toto rozhran"; break;
        case ClassDef::Protocol: result+="tento protokol"; break;
        case ClassDef::Category: result+="tuto kategorii"; break;
        case ClassDef::Exception: result+="tuto vjimku"; break;
        default: break;
      }
      result+=" byla vygenerovna z nsledujc";
      if (single) result+="ho souboru:";
      else result+="ch soubor:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, Config_getBool, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorCzech::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1841 of file translator_cz.h.
    {
      // single is true implies a single file
      QCString result="Dokumentace pro ";
      switch(compType)
      {
        case ClassDef::Class: result+="tento modul"; break;
        case ClassDef::Struct: result+="tento typ"; break;
        case ClassDef::Union: result+="tuto unii"; break;
        case ClassDef::Interface: result+="toto rozhran"; break;
        case ClassDef::Protocol: result+="tento protokol"; break;
        case ClassDef::Category: result+="tuto kategorii"; break;
        case ClassDef::Exception: result+="tuto vjimku"; break;
        default: break;
      }
      result+=" byla vygenerovna z nsledujc";
      if (single) result+="ho souboru:";
      else result+="ch soubor:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorCzech::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1841 of file translator_cz.h.
    {
      // single is true implies a single file
      QCString result="Dokumentace pro ";
      switch(compType)
      {
        case ClassDef::Class: result+="tento modul"; break;
        case ClassDef::Struct: result+="tento typ"; break;
        case ClassDef::Union: result+="tuto unii"; break;
        case ClassDef::Interface: result+="toto rozhran"; break;
        case ClassDef::Protocol: result+="tento protokol"; break;
        case ClassDef::Category: result+="tuto kategorii"; break;
        case ClassDef::Exception: result+="tuto vjimku"; break;
        default: break;
      }
      result+=" byla vygenerovna z nsledujc";
      if (single) result+="ho souboru:";
      else result+="ch soubor:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorCzech::trGlobal (bool first_capital, bool singular) [inline], [virtual]
??? Jak to prelozit? Bylo by dobre, kdyby se ozval nekdo, kdo to pouziva.
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1412 of file translator_cz.h.
    {
      QCString result((first_capital ? "Global" : "global"));
      if (!singular) result+="s";
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorCzech::trGlobal (bool first_capital, bool singular) [inline], [virtual]
??? Jak to prelozit? Bylo by dobre, kdyby se ozval nekdo, kdo to pouziva.
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1412 of file translator_cz.h.
    {
      QCString result((first_capital ? "Global" : "global"));
      if (!singular) result+="s";
      return result;
    }
trGlobalNamespace() [1/2]
virtual QCString TranslatorCzech::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1908 of file translator_cz.h.
    {
      return "Globln jmenn prostor";
    }
trGlobalNamespace() [2/2]
virtual QCString TranslatorCzech::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1908 of file translator_cz.h.
    {
      return "Globln jmenn prostor";
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorCzech::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 973 of file translator_cz.h.
    {
      return "Zobrazit dokumentaci tohoto souboru.";
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorCzech::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 973 of file translator_cz.h.
    {
      return "Zobrazit dokumentaci tohoto souboru.";
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorCzech::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 1008 of file translator_cz.h.
    {
      return "Zobrazit grafickou podobu hierarchie";
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorCzech::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 1008 of file translator_cz.h.
    {
      return "Zobrazit grafickou podobu hierarchie";
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorCzech::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 968 of file translator_cz.h.
    {
      return "Zobrazit zdrojov text tohoto souboru.";
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorCzech::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 968 of file translator_cz.h.
    {
      return "Zobrazit zdrojov text tohoto souboru.";
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorCzech::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 1012 of file translator_cz.h.
    {
      return "Zobrazit textovou podobu hierarchie";
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorCzech::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 1012 of file translator_cz.h.
    {
      return "Zobrazit textovou podobu hierarchie";
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorCzech::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 1004 of file translator_cz.h.
    {
      return "Grafick zobrazen hierarchie td";
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorCzech::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 1004 of file translator_cz.h.
    {
      return "Grafick zobrazen hierarchie td";
    }
trGroup() [1/2]
virtual QCString TranslatorCzech::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1378 of file translator_cz.h.
    {
      QCString result((first_capital ? "Skupin" : "skupin"));
      result += singular ? "a" : "y";
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorCzech::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1378 of file translator_cz.h.
    {
      QCString result((first_capital ? "Skupin" : "skupin"));
      result += singular ? "a" : "y";
      return result;
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorCzech::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 480 of file translator_cz.h.
    { return "Rejstk hierarchie"; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorCzech::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 480 of file translator_cz.h.
    { return "Rejstk hierarchie"; }
trImplementedFromList() [1/2]
virtual QCString TranslatorCzech::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1450 of file translator_cz.h.
    {
      return "Implementuje "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorCzech::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1450 of file translator_cz.h.
    {
      return "Implementuje "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorCzech::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1458 of file translator_cz.h.
    {
      return "Implementovno v "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorCzech::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1458 of file translator_cz.h.
    {
      return "Implementovno v "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorCzech::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 1104 of file translator_cz.h.
    {
      return "Nsledujc graf ukazuje, kter soubory pmo nebo "
             "nepmo vkldaj tento soubor:";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorCzech::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 1104 of file translator_cz.h.
    {
      return "Nsledujc graf ukazuje, kter soubory pmo nebo "
             "nepmo vkldaj tento soubor:";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorCzech::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 958 of file translator_cz.h.
    {
      return "Graf zvislost na vkldanch souborech pro "+fName+":";
    }
trInclDepGraph() [2/2]
virtual QCString TranslatorCzech::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 958 of file translator_cz.h.
    {
      return "Graf zvislost na vkldanch souborech pro "+fName+":";
    }
trIncludesFileIn() [1/2]
virtual QCString TranslatorCzech::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1942 of file translator_cz.h.
    {
      return "Vkld (include) soubor z "+name;
    }
References setup::name.
trIncludesFileIn() [2/2]
virtual QCString TranslatorCzech::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1942 of file translator_cz.h.
    {
      return "Vkld (include) soubor z "+name;
    }
References setup::name.
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorCzech::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 247 of file translator_cz.h.
    { return ", vetn vech zddnch len."; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorCzech::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 247 of file translator_cz.h.
    { return ", vetn vech zddnch len."; }
trInheritedByList() [1/2]
virtual QCString TranslatorCzech::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 813 of file translator_cz.h.
    {
      QCString result="Zddna ";
      result += (numEntries == 1) ? "tdou " : "tdami ";
      result += trWriteList(numEntries) + ".";
      return result;
    }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorCzech::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 813 of file translator_cz.h.
    {
      QCString result="Zddna ";
      result += (numEntries == 1) ? "tdou " : "tdami ";
      result += trWriteList(numEntries) + ".";
      return result;
    }
References trWriteList().
trInheritedFrom() [1/2]
virtual QCString TranslatorCzech::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 2042 of file translator_cz.h.
    { return members+" dd se z "+what; }
trInheritedFrom() [2/2]
virtual QCString TranslatorCzech::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 2042 of file translator_cz.h.
    { return members+" dd se z "+what; }
trInheritsList() [1/2]
virtual QCString TranslatorCzech::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 802 of file translator_cz.h.
    {
      QCString result="Dd z ";
      result += (numEntries == 1) ? "bzov tdy " : "bzovch td ";
      result += trWriteList(numEntries) + ".";
      return result;
    }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorCzech::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 802 of file translator_cz.h.
    {
      QCString result="Dd z ";
      result += (numEntries == 1) ? "bzov tdy " : "bzovch td ";
      result += trWriteList(numEntries) + ".";
      return result;
    }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorCzech::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 995 of file translator_cz.h.
    {
      return "Inicializan hodnota:";
    }
trInitialValue() [2/2]
virtual QCString TranslatorCzech::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 995 of file translator_cz.h.
    {
      return "Inicializan hodnota:";
    }
trInstanceMethods() [1/2]
virtual QCString TranslatorCzech::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 2094 of file translator_cz.h.
    {
      return "Metody instance";
    }
trInstanceMethods() [2/2]
virtual QCString TranslatorCzech::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 2094 of file translator_cz.h.
    {
      return "Metody instance";
    }
trInterfaceDocumentation() [1/2]
virtual QCString TranslatorCzech::trInterfaceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2328 of file translator_cz.h.
    {
        return "Dokumentace rozhran";
    }
trInterfaceDocumentation() [2/2]
virtual QCString TranslatorCzech::trInterfaceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2328 of file translator_cz.h.
    {
        return "Dokumentace rozhran";
    }
trInterfaceHierarchy() [1/2]
virtual QCString TranslatorCzech::trInterfaceHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2320 of file translator_cz.h.
    {
        return "Hierarchie rozhran";
    }
trInterfaceHierarchy() [2/2]
virtual QCString TranslatorCzech::trInterfaceHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2320 of file translator_cz.h.
    {
        return "Hierarchie rozhran";
    }
trInterfaceHierarchyDescription() [1/2]
virtual QCString TranslatorCzech::trInterfaceHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2324 of file translator_cz.h.
    {
        return "Zde naleznete seznam, vyjadujc vztah ddinosti rozhran. Je seazen piblin (ale ne pln) podle abecedy:";
    }
trInterfaceHierarchyDescription() [2/2]
virtual QCString TranslatorCzech::trInterfaceHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2324 of file translator_cz.h.
    {
        return "Zde naleznete seznam, vyjadujc vztah ddinosti rozhran. Je seazen piblin (ale ne pln) podle abecedy:";
    }
trInterfaceIndex() [1/2]
virtual QCString TranslatorCzech::trInterfaceIndex () [inline], [virtual]
Implements Translator.
Definition at line 2308 of file translator_cz.h.
    {
        return "Rejstk rozhran";
    }
trInterfaceIndex() [2/2]
virtual QCString TranslatorCzech::trInterfaceIndex () [inline], [virtual]
Implements Translator.
Definition at line 2308 of file translator_cz.h.
    {
        return "Rejstk rozhran";
    }
trInterfaceList() [1/2]
virtual QCString TranslatorCzech::trInterfaceList () [inline], [virtual]
Implements Translator.
Definition at line 2312 of file translator_cz.h.
    {
        return "Seznam rozhran";
    }
trInterfaceList() [2/2]
virtual QCString TranslatorCzech::trInterfaceList () [inline], [virtual]
Implements Translator.
Definition at line 2312 of file translator_cz.h.
    {
        return "Seznam rozhran";
    }
trInterfaceListDescription() [1/2]
virtual QCString TranslatorCzech::trInterfaceListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2316 of file translator_cz.h.
    {
        return "Nsledujc seznam obsahuje jmna rozhran a jejich strun popisy:";
    }
trInterfaceListDescription() [2/2]
virtual QCString TranslatorCzech::trInterfaceListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2316 of file translator_cz.h.
    {
        return "Nsledujc seznam obsahuje jmna rozhran a jejich strun popisy:";
    }
trInterfaces() [1/2]
virtual QCString TranslatorCzech::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 2111 of file translator_cz.h.
    { return "Exportovan rozhran"; }
trInterfaces() [2/2]
virtual QCString TranslatorCzech::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 2111 of file translator_cz.h.
    { return "Exportovan rozhran"; }
trInvariant() [1/2]
virtual QCString TranslatorCzech::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 990 of file translator_cz.h.
    {
      return "Invariant"; // ???
    }
trInvariant() [2/2]
virtual QCString TranslatorCzech::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 990 of file translator_cz.h.
    {
      return "Invariant"; // ???
    }
trISOLang() [1/2]
virtual QCString TranslatorCzech::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 173 of file translator_cz.h.
    {
      return "cs";
    }
trISOLang() [2/2]
virtual QCString TranslatorCzech::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 173 of file translator_cz.h.
    {
      return "cs";
    }
trLegend() [1/2]
virtual QCString TranslatorCzech::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1204 of file translator_cz.h.
    {
      return "vysvtlivky";
    }
trLegend() [2/2]
virtual QCString TranslatorCzech::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1204 of file translator_cz.h.
    {
      return "vysvtlivky";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorCzech::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 1126 of file translator_cz.h.
    {
      return
        "Zde naleznete vysvtlen, jak maj bt interpretovny grafy, "
        "kter byly vygenerovny programem doxygen.<p>\n"
        "Uvaujte nsledujc pklad:\n"
        "\\code\n"
        "/*! Neviditeln tda, kter se v grafu nezobrazuje, protoe "
        "dolo k oezn grafu. */\n"
        "class Invisible { };\n\n"
        "/*! Tda, u kter dolo k oezn grafu. Vztah ddinosti "
        "je skryt. */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Tda, kter nen dokumentovna komenti programu doxygen. */\n"
        "class Undocumented { };\n\n"
        "/*! Bzov tda ddn veejn (public inheritance). */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! ablona tdy. */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Bzov tda, pouit pro chrnn ddn "
        "(protected inheritance). */\n"
        "class ProtectedBase { };\n\n"
        "/*! Bzov tda, vyuit pro privtn ddn "
        "(private inheritance). */\n"
        "class PrivateBase { };\n\n"
        "/*! Tda, kter je vyuvna tdou Inherited. */\n"
        "class Used { };\n\n"
        "/*! Odvozen tda, kter dd z vce td. */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "K ve uvedenmu bude vygenerovn nsledujc graf:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        "Bloky (tj. uzly) v uvedenm grafu maj nsledujc vznam:\n"
        "</p>\n"
        "<ul>\n"
        "<li>ed vyplnn obdlnk reprezentuje strukturu nebo tdu, "
            "pro kterou byl graf vygenerovn.</li>\n"
        "<li>Obdlnk s ernm obrysem oznauje dokumentovanou "
            "strukturu nebo tdu.</li>\n"
        "<li>Obdlnk s edm obrysem oznauje nedokumentovanou "
            "strukturu nebo tdu.</li>\n"
        "<li>Obdlnk s ervenm obrysem oznauje dokumentovanou "
            "strukturu nebo tdu, pro kterou\n"
            "nejsou zobrazeny vechny vztahy ddinosti nebo obsaen. "
            "Graf je oezn v ppad, kdy jej\n"
            "nen mon umstit do vymezenho prostoru.</li>\n"
        "</ul>\n"
        "<p>\n"
        "ipky (tj. hrany grafu) maj nsledujc vznam:\n"
        "</p>\n"
        "<ul>\n"
        "<li>Modr ipka se pouv pro oznaen vztahu veejn "
            "ddinosti (public) mezi dvma tdami.</li>\n"
        "<li>Tmav zelen ipka oznauje vztah chrnn ddinosti "
            "(protected).</li>\n"
        "<li>Tmav erven ipka oznauje vztah privtn ddinosti "
            "(private).</li>\n"
        "<li>Purpurov ipka kreslen rkovan se pouv v ppad, "
            "kdy je tda obsaena v jin td,\n"
            "nebo kdy je pouvna jinou tdou. ipka je oznaena "
            "identifiktorem jedn nebo vce promnnch, pes kter\n"
            "je tda nebo struktura zpstupnna.</li>\n"
        "<li>lut ipka kreslen rkovan vyjaduje vztah mezi instanc ablony "
            "a ablonou tdy, na zklad kter byla\n"
            "instance ablony vytvoena. V popisu ipky jsou uvedeny pslun "
            "parametry ablony.</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorCzech::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 1126 of file translator_cz.h.
    {
      return
        "Zde naleznete vysvtlen, jak maj bt interpretovny grafy, "
        "kter byly vygenerovny programem doxygen.<p>\n"
        "Uvaujte nsledujc pklad:\n"
        "\\code\n"
        "/*! Neviditeln tda, kter se v grafu nezobrazuje, protoe "
        "dolo k oezn grafu. */\n"
        "class Invisible { };\n\n"
        "/*! Tda, u kter dolo k oezn grafu. Vztah ddinosti "
        "je skryt. */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Tda, kter nen dokumentovna komenti programu doxygen. */\n"
        "class Undocumented { };\n\n"
        "/*! Bzov tda ddn veejn (public inheritance). */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! ablona tdy. */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Bzov tda, pouit pro chrnn ddn "
        "(protected inheritance). */\n"
        "class ProtectedBase { };\n\n"
        "/*! Bzov tda, vyuit pro privtn ddn "
        "(private inheritance). */\n"
        "class PrivateBase { };\n\n"
        "/*! Tda, kter je vyuvna tdou Inherited. */\n"
        "class Used { };\n\n"
        "/*! Odvozen tda, kter dd z vce td. */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "K ve uvedenmu bude vygenerovn nsledujc graf:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        "Bloky (tj. uzly) v uvedenm grafu maj nsledujc vznam:\n"
        "</p>\n"
        "<ul>\n"
        "<li>ed vyplnn obdlnk reprezentuje strukturu nebo tdu, "
            "pro kterou byl graf vygenerovn.</li>\n"
        "<li>Obdlnk s ernm obrysem oznauje dokumentovanou "
            "strukturu nebo tdu.</li>\n"
        "<li>Obdlnk s edm obrysem oznauje nedokumentovanou "
            "strukturu nebo tdu.</li>\n"
        "<li>Obdlnk s ervenm obrysem oznauje dokumentovanou "
            "strukturu nebo tdu, pro kterou\n"
            "nejsou zobrazeny vechny vztahy ddinosti nebo obsaen. "
            "Graf je oezn v ppad, kdy jej\n"
            "nen mon umstit do vymezenho prostoru.</li>\n"
        "</ul>\n"
        "<p>\n"
        "ipky (tj. hrany grafu) maj nsledujc vznam:\n"
        "</p>\n"
        "<ul>\n"
        "<li>Modr ipka se pouv pro oznaen vztahu veejn "
            "ddinosti (public) mezi dvma tdami.</li>\n"
        "<li>Tmav zelen ipka oznauje vztah chrnn ddinosti "
            "(protected).</li>\n"
        "<li>Tmav erven ipka oznauje vztah privtn ddinosti "
            "(private).</li>\n"
        "<li>Purpurov ipka kreslen rkovan se pouv v ppad, "
            "kdy je tda obsaena v jin td,\n"
            "nebo kdy je pouvna jinou tdou. ipka je oznaena "
            "identifiktorem jedn nebo vce promnnch, pes kter\n"
            "je tda nebo struktura zpstupnna.</li>\n"
        "<li>lut ipka kreslen rkovan vyjaduje vztah mezi instanc ablony "
            "a ablonou tdy, na zklad kter byla\n"
            "instance ablony vytvoena. V popisu ipky jsou uvedeny pslun "
            "parametry ablony.</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorCzech::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 1119 of file translator_cz.h.
    {
      return "Vysvtlivky ke grafu";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorCzech::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 1119 of file translator_cz.h.
    {
      return "Vysvtlivky ke grafu";
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorCzech::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 235 of file translator_cz.h.
    { return "Seznam vech len"; }
trListOfAllMembers() [2/2]
virtual QCString TranslatorCzech::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 235 of file translator_cz.h.
    { return "Seznam vech len"; }
trLoading() [1/2]
virtual QCString TranslatorCzech::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1902 of file translator_cz.h.
    {
      return "Natm...";
    }
trLoading() [2/2]
virtual QCString TranslatorCzech::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1902 of file translator_cz.h.
    {
      return "Natm...";
    }
trMainPage() [1/2]
virtual QCString TranslatorCzech::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 917 of file translator_cz.h.
    { return "Hlavn strnka"; }
trMainPage() [2/2]
virtual QCString TranslatorCzech::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 917 of file translator_cz.h.
    { return "Hlavn strnka"; }
trMember() [1/2]
virtual QCString TranslatorCzech::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1400 of file translator_cz.h.
    {
      QCString result((first_capital ? "len" : "len"));
      if (!singular) result += "y";
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorCzech::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1400 of file translator_cz.h.
    {
      QCString result((first_capital ? "len" : "len"));
      if (!singular) result += "y";
      return result;
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorCzech::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 218 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentace poloek";
      }
      else
      {
        return "Dokumentace datovch len";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorCzech::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 218 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentace poloek";
      }
      else
      {
        return "Dokumentace datovch len";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorCzech::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 201 of file translator_cz.h.
    { return "Dokumentace lenskch vt"; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorCzech::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 201 of file translator_cz.h.
    { return "Dokumentace lenskch vt"; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorCzech::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 205 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return "Dokumentace lenskch funkc/procedur/proces";
      }
      else
      {
        return "Dokumentace lenskch funkc";
      }
    }
References Config_getBool.
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorCzech::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 205 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return "Dokumentace lenskch funkc/procedur/proces";
      }
      else
      {
        return "Dokumentace lenskch funkc";
      }
    }
References Config_getBool.
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorCzech::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1692 of file translator_cz.h.
    { return "Dokumentace lenskch funkc/podprogram"; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorCzech::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1692 of file translator_cz.h.
    { return "Dokumentace lenskch funkc/podprogram"; }
trMemberList() [1/2]
virtual QCString TranslatorCzech::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 239 of file translator_cz.h.
    { return "Seznam len tdy"; }
trMemberList() [2/2]
virtual QCString TranslatorCzech::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 239 of file translator_cz.h.
    { return "Seznam len tdy"; }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorCzech::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 197 of file translator_cz.h.
    { return "Dokumentace lenskch typ"; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorCzech::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 197 of file translator_cz.h.
    { return "Dokumentace lenskch typ"; }
trMethodDocumentation() [1/2]
virtual QCString TranslatorCzech::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 2101 of file translator_cz.h.
    {
      return "Dokumentace metody";
    }
trMethodDocumentation() [2/2]
virtual QCString TranslatorCzech::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 2101 of file translator_cz.h.
    {
      return "Dokumentace metody";
    }
trModule() [1/2]
virtual QCString TranslatorCzech::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1831 of file translator_cz.h.
    {
      QCString result((first_capital ? "Modul" : "modul"));
      if (!singular) result+="y";
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorCzech::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1831 of file translator_cz.h.
    {
      QCString result((first_capital ? "Modul" : "modul"));
      if (!singular) result+="y";
      return result;
    }
trModuleDocumentation() [1/2]
virtual QCString TranslatorCzech::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 507 of file translator_cz.h.
    { return "Dokumentace modul"; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorCzech::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 507 of file translator_cz.h.
    { return "Dokumentace modul"; }
trModuleIndex() [1/2]
virtual QCString TranslatorCzech::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 474 of file translator_cz.h.
    { return "Rejstk modul"; }
trModuleIndex() [2/2]
virtual QCString TranslatorCzech::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 474 of file translator_cz.h.
    { return "Rejstk modul"; }
trModuleReference() [1/2]
virtual QCString TranslatorCzech::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1793 of file translator_cz.h.
    {
      QCString result="Dokumentace modulu ";
      result += namespaceName;
      return result;
    }
trModuleReference() [2/2]
virtual QCString TranslatorCzech::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1793 of file translator_cz.h.
    {
      QCString result="Dokumentace modulu ";
      result += namespaceName;
      return result;
    }
trModules() [1/2]
virtual QCString TranslatorCzech::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 278 of file translator_cz.h.
    { return "Moduly"; }
trModules() [2/2]
virtual QCString TranslatorCzech::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 278 of file translator_cz.h.
    { return "Moduly"; }
trModulesDescription() [1/2]
virtual QCString TranslatorCzech::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 462 of file translator_cz.h.
    { return "Zde naleznete seznam vech modul:"; }
trModulesDescription() [2/2]
virtual QCString TranslatorCzech::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 462 of file translator_cz.h.
    { return "Zde naleznete seznam vech modul:"; }
trModulesIndex() [1/2]
virtual QCString TranslatorCzech::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1824 of file translator_cz.h.
    { return "Rejstk modul"; }
trModulesIndex() [2/2]
virtual QCString TranslatorCzech::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1824 of file translator_cz.h.
    { return "Rejstk modul"; }
trModulesList() [1/2]
virtual QCString TranslatorCzech::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1759 of file translator_cz.h.
    { return "Seznam modul"; }
trModulesList() [2/2]
virtual QCString TranslatorCzech::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1759 of file translator_cz.h.
    { return "Seznam modul"; }
trModulesListDescription() [1/2]
virtual QCString TranslatorCzech::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1763 of file translator_cz.h.
    {
      QCString result="Nsleduje seznam vech ";
      if (!extractAll) result+="dokumentovanch ";
      result+="modul se strunmi popisy:";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorCzech::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1763 of file translator_cz.h.
    {
      QCString result="Nsleduje seznam vech ";
      if (!extractAll) result+="dokumentovanch ";
      result+="modul se strunmi popisy:";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorCzech::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1805 of file translator_cz.h.
    {
      QCString result="Nsleduje seznam vech ";
      if (!extractAll) result+="dokumentovanch ";
      result+="st modul s odkazy ";
      if (extractAll)
      {
        result+="na dokumentaci modulu pro danou st:";
      }
      else
      {
        result+="na moduly, ke kterm st pat:";
      }
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorCzech::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1805 of file translator_cz.h.
    {
      QCString result="Nsleduje seznam vech ";
      if (!extractAll) result+="dokumentovanch ";
      result+="st modul s odkazy ";
      if (extractAll)
      {
        result+="na dokumentaci modulu pro danou st:";
      }
      else
      {
        result+="na moduly, ke kterm st pat:";
      }
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorCzech::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1801 of file translator_cz.h.
    { return "sti modulu"; }
trModulesMembers() [2/2]
virtual QCString TranslatorCzech::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1801 of file translator_cz.h.
    { return "sti modulu"; }
trMonth() [1/2]
virtual QCString TranslatorCzech::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1981 of file translator_cz.h.
    {
      static const char *months_short[] = { "led", "no", "be", "dub", "kv", "vn", "vc", "srp", "z", "j", "lis", "pro" };
      static const char *months_full[] = { "leden", "nor", "bezen", "duben", "kvten", "erven", "ervenec", "srpen", "z", "jen", "listopad", "prosinec" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMonth() [2/2]
virtual QCString TranslatorCzech::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1981 of file translator_cz.h.
    {
      static const char *months_short[] = { "led", "no", "be", "dub", "kv", "vn", "vc", "srp", "z", "j", "lis", "pro" };
      static const char *months_full[] = { "leden", "nor", "bezen", "duben", "kvten", "erven", "ervenec", "srpen", "z", "jen", "listopad", "prosinec" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore() [1/2]
virtual QCString TranslatorCzech::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 231 of file translator_cz.h.
    { return "..."; }
trMore() [2/2]
virtual QCString TranslatorCzech::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 231 of file translator_cz.h.
    { return "..."; }
trNamespace() [1/2]
virtual QCString TranslatorCzech::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1365 of file translator_cz.h.
    {
      QCString result((first_capital ? "Jmenn" : "jmenn"));
      result += singular ? "" : "";
      result+=" prostor";
      if (!singular) result+="y";
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorCzech::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1365 of file translator_cz.h.
    {
      QCString result((first_capital ? "Jmenn" : "jmenn"));
      result += singular ? "" : "";
      result+=" prostor";
      if (!singular) result+="y";
      return result;
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorCzech::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 865 of file translator_cz.h.
    { return "Dokumentace jmennch prostor"; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorCzech::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 865 of file translator_cz.h.
    { return "Dokumentace jmennch prostor"; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorCzech::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 859 of file translator_cz.h.
    { return "Rejstk jmennch prostor"; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorCzech::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 859 of file translator_cz.h.
    { return "Rejstk jmennch prostor"; }
trNamespaceList() [1/2]
virtual QCString TranslatorCzech::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 680 of file translator_cz.h.
    { return "Seznam jmennch prostor"; }
trNamespaceList() [2/2]
virtual QCString TranslatorCzech::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 680 of file translator_cz.h.
    { return "Seznam jmennch prostor"; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorCzech::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 684 of file translator_cz.h.
    {
      QCString result="Zde naleznete seznam vech ";
      if (!extractAll) result+="dokumentovanch ";
      result+="jmennch prostor se strunm popisem:";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorCzech::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 684 of file translator_cz.h.
    {
      QCString result="Zde naleznete seznam vech ";
      if (!extractAll) result+="dokumentovanch ";
      result+="jmennch prostor se strunm popisem:";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorCzech::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 844 of file translator_cz.h.
    {
      QCString result="Zde naleznete seznam vech ";
      if (!extractAll) result+="dokumentovanch ";
      result+="symbol, kter jsou definovny ve svch jmennch prostorech. "
              "U kadho je uveden odkaz na ";
      if (extractAll)
        result+="dokumentaci pslunho jmennho prostoru:";
      else
        result+="pslun jmenn prostor:";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorCzech::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 844 of file translator_cz.h.
    {
      QCString result="Zde naleznete seznam vech ";
      if (!extractAll) result+="dokumentovanch ";
      result+="symbol, kter jsou definovny ve svch jmennch prostorech. "
              "U kadho je uveden odkaz na ";
      if (extractAll)
        result+="dokumentaci pslunho jmennho prostoru:";
      else
        result+="pslun jmenn prostor:";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorCzech::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 840 of file translator_cz.h.
    { return "Symboly ve jmennm prostoru"; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorCzech::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 840 of file translator_cz.h.
    { return "Symboly ve jmennm prostoru"; }
trNamespaceReference() [1/2]
virtual QCString TranslatorCzech::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 743 of file translator_cz.h.
    {
      QCString result="Dokumentace jmennho prostoru ";
      result+=namespaceName;
      return result;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorCzech::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 743 of file translator_cz.h.
    {
      QCString result="Dokumentace jmennho prostoru ";
      result+=namespaceName;
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorCzech::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 875 of file translator_cz.h.
    { return "Jmenn prostory"; }
trNamespaces() [2/2]
virtual QCString TranslatorCzech::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 875 of file translator_cz.h.
    { return "Jmenn prostory"; }
trNoMatches() [1/2]
virtual QCString TranslatorCzech::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1920 of file translator_cz.h.
    {
      return "Nebylo nic nalezeno";
    }
trNoMatches() [2/2]
virtual QCString TranslatorCzech::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1920 of file translator_cz.h.
    {
      return "Nebylo nic nalezeno";
    }
trNote() [1/2]
virtual QCString TranslatorCzech::trNote () [inline], [virtual]
Implements Translator.
Definition at line 1025 of file translator_cz.h.
    {
      return "Poznmka";
    }
trNote() [2/2]
virtual QCString TranslatorCzech::trNote () [inline], [virtual]
Implements Translator.
Definition at line 1025 of file translator_cz.h.
    {
      return "Poznmka";
    }
trOperationDocumentation() [1/2]
virtual QCString TranslatorCzech::trOperationDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2402 of file translator_cz.h.
    {
        return "Dokumentace operace";
    }
trOperationDocumentation() [2/2]
virtual QCString TranslatorCzech::trOperationDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2402 of file translator_cz.h.
    {
        return "Dokumentace operace";
    }
trOperations() [1/2]
virtual QCString TranslatorCzech::trOperations () [inline], [virtual]
Implements Translator.
Definition at line 2398 of file translator_cz.h.
    {
        return "Operace";
    }
trOperations() [2/2]
virtual QCString TranslatorCzech::trOperations () [inline], [virtual]
Implements Translator.
Definition at line 2398 of file translator_cz.h.
    {
        return "Operace";
    }
trOverloadText() [1/2]
virtual QCString TranslatorCzech::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1664 of file translator_cz.h.
    {
       return "Jde o petenou (overloaded) metodu, "
              "kter m usnadnit pouvn. Od ve uveden metody se li "
              "pouze jinak zadvanmi argumenty.";
    }
trOverloadText() [2/2]
virtual QCString TranslatorCzech::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1664 of file translator_cz.h.
    {
       return "Jde o petenou (overloaded) metodu, "
              "kter m usnadnit pouvn. Od ve uveden metody se li "
              "pouze jinak zadvanmi argumenty.";
    }
trPackage() [1/2]
virtual QCString TranslatorCzech::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1255 of file translator_cz.h.
    {
      return "Balk "+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorCzech::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1255 of file translator_cz.h.
    {
      return "Balk "+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorCzech::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1535 of file translator_cz.h.
    {
      return "Atributy v balku"; // ??? not checked in a context
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorCzech::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1535 of file translator_cz.h.
    {
      return "Atributy v balku"; // ??? not checked in a context
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorCzech::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1517 of file translator_cz.h.
    {
      return "Funkce v balku";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorCzech::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1517 of file translator_cz.h.
    {
      return "Funkce v balku";
    }
trPackageList() [1/2]
virtual QCString TranslatorCzech::trPackageList () [inline], [virtual]
Implements Translator.
Definition at line 2473 of file translator_cz.h.
    { return "Seznam balk"; }
trPackageList() [2/2]
virtual QCString TranslatorCzech::trPackageList () [inline], [virtual]
Implements Translator.
Definition at line 2473 of file translator_cz.h.
    { return "Seznam balk"; }
trPackageListDescription() [1/2]
virtual QCString TranslatorCzech::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1260 of file translator_cz.h.
    {
      return "Zde naleznete seznam balk se strunm popisem (pokud byl uveden):";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorCzech::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1260 of file translator_cz.h.
    {
      return "Zde naleznete seznam balk se strunm popisem (pokud byl uveden):";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorCzech::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1521 of file translator_cz.h.
    {
      return "leny v balku"; // ??? not checked in a context
    }
trPackageMembers() [2/2]
virtual QCString TranslatorCzech::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1521 of file translator_cz.h.
    {
      return "leny v balku"; // ??? not checked in a context
    }
trPackages() [1/2]
virtual QCString TranslatorCzech::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1265 of file translator_cz.h.
    {
      return "Balky";
    }
trPackages() [2/2]
virtual QCString TranslatorCzech::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1265 of file translator_cz.h.
    {
      return "Balky";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorCzech::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1510 of file translator_cz.h.
    {
      return "Typy v balku";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorCzech::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1510 of file translator_cz.h.
    {
      return "Typy v balku";
    }
trPage() [1/2]
virtual QCString TranslatorCzech::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1389 of file translator_cz.h.
    {
      QCString result((first_capital ? "Strnk" : "strnk"));
      result += singular ? "a" : "y";
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorCzech::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1389 of file translator_cz.h.
    {
      QCString result((first_capital ? "Strnk" : "strnk"));
      result += singular ? "a" : "y";
      return result;
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorCzech::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 923 of file translator_cz.h.
    { return "s."; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorCzech::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 923 of file translator_cz.h.
    { return "s."; }
trPageIndex() [1/2]
virtual QCString TranslatorCzech::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 1016 of file translator_cz.h.
    {
      return "Rejstk strnek";
    }
trPageIndex() [2/2]
virtual QCString TranslatorCzech::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 1016 of file translator_cz.h.
    {
      return "Rejstk strnek";
    }
trPanelSynchronisationTooltip() [1/2]
virtual QCString TranslatorCzech::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 2059 of file translator_cz.h.
    {
      QCString opt = enable ? "povolit" : "zakzat";
      return opt + " synchronizaci panel";
    }
trPanelSynchronisationTooltip() [2/2]
virtual QCString TranslatorCzech::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 2059 of file translator_cz.h.
    {
      QCString opt = enable ? "povolit" : "zakzat";
      return opt + " synchronizaci panel";
    }
trParameters() [1/2]
virtual QCString TranslatorCzech::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 664 of file translator_cz.h.
    { return "Parametry"; }
trParameters() [2/2]
virtual QCString TranslatorCzech::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 664 of file translator_cz.h.
    { return "Parametry"; }
trPostcondition() [1/2]
virtual QCString TranslatorCzech::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 985 of file translator_cz.h.
    {
      return "Postcondition"; // ???
    }
trPostcondition() [2/2]
virtual QCString TranslatorCzech::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 985 of file translator_cz.h.
    {
      return "Postcondition"; // ???
    }
trPrecondition() [1/2]
virtual QCString TranslatorCzech::trPrecondition () [inline], [virtual]
??? Jak to prelozit? Bylo by dobre, kdyby se ozval nekdo, kdo to pouziva.
Text for the \pre command
Implements Translator.
Definition at line 980 of file translator_cz.h.
    {
      return "Precondition"; // ???
    }
trPrecondition() [2/2]
virtual QCString TranslatorCzech::trPrecondition () [inline], [virtual]
??? Jak to prelozit? Bylo by dobre, kdyby se ozval nekdo, kdo to pouziva.
Text for the \pre command
Implements Translator.
Definition at line 980 of file translator_cz.h.
    {
      return "Precondition"; // ???
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorCzech::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1064 of file translator_cz.h.
    {
      return "Privtn atributy";
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorCzech::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1064 of file translator_cz.h.
    {
      return "Privtn atributy";
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorCzech::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 767 of file translator_cz.h.
    { return "Privtn metody"; }
trPrivateMembers() [2/2]
virtual QCString TranslatorCzech::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 767 of file translator_cz.h.
    { return "Privtn metody"; }
trPrivateSlots() [1/2]
virtual QCString TranslatorCzech::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 769 of file translator_cz.h.
    { return "Privtn sloty"; }
trPrivateSlots() [2/2]
virtual QCString TranslatorCzech::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 769 of file translator_cz.h.
    { return "Privtn sloty"; }
trPrivateTypes() [1/2]
virtual QCString TranslatorCzech::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 1060 of file translator_cz.h.
    {
      return "Privtn typy";
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorCzech::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 1060 of file translator_cz.h.
    {
      return "Privtn typy";
    }
trProperties() [1/2]
virtual QCString TranslatorCzech::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1229 of file translator_cz.h.
    {
      return "Vlastnosti";
    }
trProperties() [2/2]
virtual QCString TranslatorCzech::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1229 of file translator_cz.h.
    {
      return "Vlastnosti";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorCzech::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1234 of file translator_cz.h.
    {
      return "Dokumentace vlastnost";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorCzech::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1234 of file translator_cz.h.
    {
      return "Dokumentace vlastnost";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorCzech::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1052 of file translator_cz.h.
    {
      return "Chrnn atributy";
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorCzech::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1052 of file translator_cz.h.
    {
      return "Chrnn atributy";
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorCzech::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 761 of file translator_cz.h.
    { return "Chrnn metody"; }
trProtectedMembers() [2/2]
virtual QCString TranslatorCzech::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 761 of file translator_cz.h.
    { return "Chrnn metody"; }
trProtectedSlots() [1/2]
virtual QCString TranslatorCzech::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 763 of file translator_cz.h.
    { return "Chrnn sloty"; }
trProtectedSlots() [2/2]
virtual QCString TranslatorCzech::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 763 of file translator_cz.h.
    { return "Chrnn sloty"; }
trProtectedTypes() [1/2]
virtual QCString TranslatorCzech::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 1048 of file translator_cz.h.
    {
      return "Chrnn typy";
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorCzech::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 1048 of file translator_cz.h.
    {
      return "Chrnn typy";
    }
trProvidedByCategory() [1/2]
virtual QCString TranslatorCzech::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 2069 of file translator_cz.h.
    {
      return "Deklarovno v kategorii @0.";
    }
trProvidedByCategory() [2/2]
virtual QCString TranslatorCzech::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 2069 of file translator_cz.h.
    {
      return "Deklarovno v kategorii @0.";
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorCzech::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1033 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datov poloky";
      }
      else
      {
        return "Veejn atributy";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorCzech::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1033 of file translator_cz.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datov poloky";
      }
      else
      {
        return "Veejn atributy";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorCzech::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 753 of file translator_cz.h.
    { return "Veejn metody"; }
trPublicMembers() [2/2]
virtual QCString TranslatorCzech::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 753 of file translator_cz.h.
    { return "Veejn metody"; }
trPublicSlots() [1/2]
virtual QCString TranslatorCzech::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 755 of file translator_cz.h.
    { return "Veejn sloty"; }
trPublicSlots() [2/2]
virtual QCString TranslatorCzech::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 755 of file translator_cz.h.
    { return "Veejn sloty"; }
trPublicTypes() [1/2]
virtual QCString TranslatorCzech::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 1029 of file translator_cz.h.
    {
      return "Veejn typy";
    }
trPublicTypes() [2/2]
virtual QCString TranslatorCzech::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 1029 of file translator_cz.h.
    {
      return "Veejn typy";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorCzech::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 1092 of file translator_cz.h.
    {
      return "Pouv se v";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorCzech::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 1092 of file translator_cz.h.
    {
      return "Pouv se v";
    }
trReferenceManual() [1/2]
virtual QCString TranslatorCzech::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 542 of file translator_cz.h.
    { return "Referenn pruka"; }
trReferenceManual() [2/2]
virtual QCString TranslatorCzech::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 542 of file translator_cz.h.
    { return "Referenn pruka"; }
trReferences() [1/2]
virtual QCString TranslatorCzech::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1438 of file translator_cz.h.
    {
      return "Odkazuje se na";
    }
trReferences() [2/2]
virtual QCString TranslatorCzech::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1438 of file translator_cz.h.
    {
      return "Odkazuje se na";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorCzech::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 824 of file translator_cz.h.
    {
      QCString result="Reimplementuje stejnojmenn prvek z ";
      result += trWriteList(numEntries) + ".";
      return result;
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorCzech::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 824 of file translator_cz.h.
    {
      QCString result="Reimplementuje stejnojmenn prvek z ";
      result += trWriteList(numEntries) + ".";
      return result;
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorCzech::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 834 of file translator_cz.h.
    {
      return "Reimplementovno v "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorCzech::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 834 of file translator_cz.h.
    {
      return "Reimplementovno v "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorCzech::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 705 of file translator_cz.h.
    { return "Dokumentace ptel a souvisejcch funkc tdy"; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorCzech::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 705 of file translator_cz.h.
    { return "Dokumentace ptel a souvisejcch funkc tdy"; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorCzech::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 185 of file translator_cz.h.
    { return "Souvisejc funkce"; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorCzech::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 185 of file translator_cz.h.
    { return "Souvisejc funkce"; }
trRelatedPages() [1/2]
virtual QCString TranslatorCzech::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 329 of file translator_cz.h.
    { return "Ostatn strnky"; }
trRelatedPages() [2/2]
virtual QCString TranslatorCzech::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 329 of file translator_cz.h.
    { return "Ostatn strnky"; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorCzech::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 458 of file translator_cz.h.
    { return "Nsledujc seznam odkazuje na dal strnky projektu:"; }
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorCzech::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 458 of file translator_cz.h.
    { return "Nsledujc seznam odkazuje na dal strnky projektu:"; }
trRelatedSubscript() [1/2]
virtual QCString TranslatorCzech::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 189 of file translator_cz.h.
    { return "(Uveden funkce nejsou lenskmi funkcemi.)"; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorCzech::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 189 of file translator_cz.h.
    { return "(Uveden funkce nejsou lenskmi funkcemi.)"; }
trRemarks() [1/2]
virtual QCString TranslatorCzech::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 1096 of file translator_cz.h.
    {
      return "Poznmky"; // ??? not checked in a context
    }
trRemarks() [2/2]
virtual QCString TranslatorCzech::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 1096 of file translator_cz.h.
    {
      return "Poznmky"; // ??? not checked in a context
    }
trReturns() [1/2]
virtual QCString TranslatorCzech::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 656 of file translator_cz.h.
    { return "Nvratov hodnota"; }
trReturns() [2/2]
virtual QCString TranslatorCzech::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 656 of file translator_cz.h.
    { return "Nvratov hodnota"; }
trReturnValues() [1/2]
virtual QCString TranslatorCzech::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 912 of file translator_cz.h.
    { return "Vracen hodnoty"; }
trReturnValues() [2/2]
virtual QCString TranslatorCzech::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 912 of file translator_cz.h.
    { return "Vracen hodnoty"; }
trRTFansicp() [1/2]
virtual QCString TranslatorCzech::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1319 of file translator_cz.h.
    {
      return "1250";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorCzech::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1319 of file translator_cz.h.
    {
      return "1250";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorCzech::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1328 of file translator_cz.h.
    {
      return "238";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorCzech::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1328 of file translator_cz.h.
    {
      return "238";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorCzech::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1334 of file translator_cz.h.
    {
      return "Rejstk";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorCzech::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1334 of file translator_cz.h.
    {
      return "Rejstk";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorCzech::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1470 of file translator_cz.h.
    {
      return "Obsah";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorCzech::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1470 of file translator_cz.h.
    {
      return "Obsah";
    }
trSearch() [1/2]
virtual QCString TranslatorCzech::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 337 of file translator_cz.h.
    { return "Hledat"; }
trSearch() [2/2]
virtual QCString TranslatorCzech::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 337 of file translator_cz.h.
    { return "Hledat"; }
trSearching() [1/2]
virtual QCString TranslatorCzech::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1914 of file translator_cz.h.
    {
      return "Vyhledvm...";
    }
trSearching() [2/2]
virtual QCString TranslatorCzech::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1914 of file translator_cz.h.
    {
      return "Vyhledvm...";
    }
trSearchMatches() [1/2]
virtual QCString TranslatorCzech::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1603 of file translator_cz.h.
    {
      return "Nalezen slova:";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorCzech::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1603 of file translator_cz.h.
    {
      return "Nalezen slova:";
    }
trSearchResults() [1/2]
virtual QCString TranslatorCzech::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1583 of file translator_cz.h.
    {
      if (numDocuments==0)
      {
        return "Lituji. Vaemu dotazu neodpovd dn dokument.";
      }
      else if (numDocuments==1)
      {
        return "Nalezen jeden dokument, kter vyhovuje vaemu dotazu.";
      }
      else
      {
        return "Nalezeno <b>$num</b> dokument, kter vyhovuj vaemu "
                      "dotazu. Nejlpe odpovdajc dokumenty jsou zobrazeny "
                      "jako prvn.";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorCzech::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1583 of file translator_cz.h.
    {
      if (numDocuments==0)
      {
        return "Lituji. Vaemu dotazu neodpovd dn dokument.";
      }
      else if (numDocuments==1)
      {
        return "Nalezen jeden dokument, kter vyhovuje vaemu dotazu.";
      }
      else
      {
        return "Nalezeno <b>$num</b> dokument, kter vyhovuj vaemu "
                      "dotazu. Nejlpe odpovdajc dokumenty jsou zobrazeny "
                      "jako prvn.";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorCzech::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1571 of file translator_cz.h.
    {
      return "Vsledky vyhledvn";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorCzech::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1571 of file translator_cz.h.
    {
      return "Vsledky vyhledvn";
    }
trSeeAlso() [1/2]
virtual QCString TranslatorCzech::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 660 of file translator_cz.h.
    { return "Viz tak"; }
trSeeAlso() [2/2]
virtual QCString TranslatorCzech::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 660 of file translator_cz.h.
    { return "Viz tak"; }
trSequenceDocumentation() [1/2]
virtual QCString TranslatorCzech::trSequenceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2292 of file translator_cz.h.
    {
        return "Dokumentace sekvence";
    }
trSequenceDocumentation() [2/2]
virtual QCString TranslatorCzech::trSequenceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2292 of file translator_cz.h.
    {
        return "Dokumentace sekvence";
    }
trSequences() [1/2]
virtual QCString TranslatorCzech::trSequences () [inline], [virtual]
Implements Translator.
Definition at line 2288 of file translator_cz.h.
    {
        return "Sekvence";
    }
trSequences() [2/2]
virtual QCString TranslatorCzech::trSequences () [inline], [virtual]
Implements Translator.
Definition at line 2288 of file translator_cz.h.
    {
        return "Sekvence";
    }
trServiceGeneratedFromFiles() [1/2]
virtual QCString TranslatorCzech::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 2144 of file translator_cz.h.
    {
      // single is true implies a single file
      QCString result="Dokumentace k tto slub byla vygenerovna z nsledujc";
      if (single) result+="ho souboru:";
      else result+="ch soubor:";
      return result;
    }
trServiceGeneratedFromFiles() [2/2]
virtual QCString TranslatorCzech::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 2144 of file translator_cz.h.
    {
      // single is true implies a single file
      QCString result="Dokumentace k tto slub byla vygenerovna z nsledujc";
      if (single) result+="ho souboru:";
      else result+="ch soubor:";
      return result;
    }
trServiceReference() [1/2]
virtual QCString TranslatorCzech::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 2130 of file translator_cz.h.
    {
      QCString result="Popis sluby ";
      result+=sName;
      return result;
    }
trServiceReference() [2/2]
virtual QCString TranslatorCzech::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 2130 of file translator_cz.h.
    {
      QCString result="Popis sluby ";
      result+=sName;
      return result;
    }
trServices() [1/2]
virtual QCString TranslatorCzech::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 2115 of file translator_cz.h.
    { return "Zalenn sluby"; }
trServices() [2/2]
virtual QCString TranslatorCzech::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 2115 of file translator_cz.h.
    { return "Zalenn sluby"; }
trSignals() [1/2]
virtual QCString TranslatorCzech::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 757 of file translator_cz.h.
    { return "Signly"; }
trSignals() [2/2]
virtual QCString TranslatorCzech::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 757 of file translator_cz.h.
    { return "Signly"; }
trSince() [1/2]
virtual QCString TranslatorCzech::trSince () [inline], [virtual]
Implements Translator.
Definition at line 1109 of file translator_cz.h.
    {
      return "Od"; // ??? not checked in a context
    }
trSince() [2/2]
virtual QCString TranslatorCzech::trSince () [inline], [virtual]
Implements Translator.
Definition at line 1109 of file translator_cz.h.
    {
      return "Od"; // ??? not checked in a context
    }
trSingletonGeneratedFromFiles() [1/2]
virtual QCString TranslatorCzech::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 2153 of file translator_cz.h.
    {
      // single is true implies a single file
      QCString result="Dokumentace k tomuto singletonu byla vygenerovna z nsledujc";
      if (single) result+="ho souboru:";
      else result+="ch soubor:";
      return result;
    }
trSingletonGeneratedFromFiles() [2/2]
virtual QCString TranslatorCzech::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 2153 of file translator_cz.h.
    {
      // single is true implies a single file
      QCString result="Dokumentace k tomuto singletonu byla vygenerovna z nsledujc";
      if (single) result+="ho souboru:";
      else result+="ch soubor:";
      return result;
    }
trSingletonReference() [1/2]
virtual QCString TranslatorCzech::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 2137 of file translator_cz.h.
    {
      QCString result="Popis singletonu ";
      result+=sName;
      return result;
    }
trSingletonReference() [2/2]
virtual QCString TranslatorCzech::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 2137 of file translator_cz.h.
    {
      QCString result="Popis singletonu ";
      result+=sName;
      return result;
    }
trSliceInterfaces() [1/2]
virtual QCString TranslatorCzech::trSliceInterfaces () [inline], [virtual]
Implements Translator.
Definition at line 2304 of file translator_cz.h.
    {
        return "Rozhran";
    }
trSliceInterfaces() [2/2]
virtual QCString TranslatorCzech::trSliceInterfaces () [inline], [virtual]
Implements Translator.
Definition at line 2304 of file translator_cz.h.
    {
        return "Rozhran";
    }
trSourceFile() [1/2]
virtual QCString TranslatorCzech::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1614 of file translator_cz.h.
    {
      return "Zdrojov soubor " + filename;
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorCzech::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1614 of file translator_cz.h.
    {
      return "Zdrojov soubor " + filename;
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorCzech::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1542 of file translator_cz.h.
    {
      return "Statick atributy v balku"; // ??? not checked in a context
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorCzech::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1542 of file translator_cz.h.
    {
      return "Statick atributy v balku"; // ??? not checked in a context
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorCzech::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1528 of file translator_cz.h.
    {
      return "Statick funkce v balku";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorCzech::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1528 of file translator_cz.h.
    {
      return "Statick funkce v balku";
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorCzech::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1068 of file translator_cz.h.
    {
      return "Statick privtn atributy";
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorCzech::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1068 of file translator_cz.h.
    {
      return "Statick privtn atributy";
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorCzech::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 771 of file translator_cz.h.
    { return "Statick privtn metody"; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorCzech::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 771 of file translator_cz.h.
    { return "Statick privtn metody"; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorCzech::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1056 of file translator_cz.h.
    {
      return "Statick chrnn atributy";
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorCzech::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1056 of file translator_cz.h.
    {
      return "Statick chrnn atributy";
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorCzech::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 765 of file translator_cz.h.
    { return "Statick chrnn metody"; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorCzech::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 765 of file translator_cz.h.
    { return "Statick chrnn metody"; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorCzech::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1044 of file translator_cz.h.
    {
      return "Statick veejn atributy";
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorCzech::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1044 of file translator_cz.h.
    {
      return "Statick veejn atributy";
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorCzech::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 759 of file translator_cz.h.
    { return "Statick veejn metody"; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorCzech::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 759 of file translator_cz.h.
    { return "Statick veejn metody"; }
trStructDocumentation() [1/2]
virtual QCString TranslatorCzech::trStructDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2348 of file translator_cz.h.
    {
        return "Dokumentace struktur";
    }
trStructDocumentation() [2/2]
virtual QCString TranslatorCzech::trStructDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2348 of file translator_cz.h.
    {
        return "Dokumentace struktur";
    }
trStructIndex() [1/2]
virtual QCString TranslatorCzech::trStructIndex () [inline], [virtual]
Implements Translator.
Definition at line 2336 of file translator_cz.h.
    {
        return "Rejstk struktur";
    }
trStructIndex() [2/2]
virtual QCString TranslatorCzech::trStructIndex () [inline], [virtual]
Implements Translator.
Definition at line 2336 of file translator_cz.h.
    {
        return "Rejstk struktur";
    }
trStructList() [1/2]
virtual QCString TranslatorCzech::trStructList () [inline], [virtual]
Implements Translator.
Definition at line 2340 of file translator_cz.h.
    {
        return "Seznam struktur";
    }
trStructList() [2/2]
virtual QCString TranslatorCzech::trStructList () [inline], [virtual]
Implements Translator.
Definition at line 2340 of file translator_cz.h.
    {
        return "Seznam struktur";
    }
trStructListDescription() [1/2]
virtual QCString TranslatorCzech::trStructListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2344 of file translator_cz.h.
    {
        return "Nsledujc seznam obsahuje jmna struktur a jejich strun popisy:";
    }
trStructListDescription() [2/2]
virtual QCString TranslatorCzech::trStructListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2344 of file translator_cz.h.
    {
        return "Nsledujc seznam obsahuje jmna struktur a jejich strun popisy:";
    }
trStructs() [1/2]
virtual QCString TranslatorCzech::trStructs () [inline], [virtual]
Implements Translator.
Definition at line 2332 of file translator_cz.h.
    {
        return "Struktury";
    }
trStructs() [2/2]
virtual QCString TranslatorCzech::trStructs () [inline], [virtual]
Implements Translator.
Definition at line 2332 of file translator_cz.h.
    {
        return "Struktury";
    }
trSubprogram() [1/2]
virtual QCString TranslatorCzech::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1878 of file translator_cz.h.
    {
      QCString result((first_capital ? "Podprogram" : "podprogram"));
      if (!singular) result+="y";
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorCzech::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1878 of file translator_cz.h.
    {
      QCString result((first_capital ? "Podprogram" : "podprogram"));
      if (!singular) result+="y";
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorCzech::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1749 of file translator_cz.h.
    { return "Dokumentace funkce/podprogramu"; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorCzech::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1749 of file translator_cz.h.
    { return "Dokumentace funkce/podprogramu"; }
trSubprograms() [1/2]
virtual QCString TranslatorCzech::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1743 of file translator_cz.h.
    { return "Funkce/podprogramy"; }
trSubprograms() [2/2]
virtual QCString TranslatorCzech::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1743 of file translator_cz.h.
    { return "Funkce/podprogramy"; }
trTemplateParameters() [1/2]
virtual QCString TranslatorCzech::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 2020 of file translator_cz.h.
    { return "Parametry ablony"; }
trTemplateParameters() [2/2]
virtual QCString TranslatorCzech::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 2020 of file translator_cz.h.
    { return "Parametry ablony"; }
trTest() [1/2]
virtual QCString TranslatorCzech::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1214 of file translator_cz.h.
    {
      return "Test";
    }
trTest() [2/2]
virtual QCString TranslatorCzech::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1214 of file translator_cz.h.
    {
      return "Test";
    }
trTestList() [1/2]
virtual QCString TranslatorCzech::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1219 of file translator_cz.h.
    {
      return "Seznam test";
    }
trTestList() [2/2]
virtual QCString TranslatorCzech::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1219 of file translator_cz.h.
    {
      return "Seznam test";
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorCzech::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 243 of file translator_cz.h.
    { return "Zde naleznete pln seznam len tdy "; }
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorCzech::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 243 of file translator_cz.h.
    { return "Zde naleznete pln seznam len tdy "; }
trTodo() [1/2]
virtual QCString TranslatorCzech::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 1078 of file translator_cz.h.
    {
      return "Plnovan pravy";
    }
trTodo() [2/2]
virtual QCString TranslatorCzech::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 1078 of file translator_cz.h.
    {
      return "Plnovan pravy";
    }
trTodoList() [1/2]
virtual QCString TranslatorCzech::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 1083 of file translator_cz.h.
    {
      return "Seznam plnovanch prav";
    }
trTodoList() [2/2]
virtual QCString TranslatorCzech::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 1083 of file translator_cz.h.
    {
      return "Seznam plnovanch prav";
    }
trType() [1/2]
virtual QCString TranslatorCzech::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1867 of file translator_cz.h.
    {
      QCString result((first_capital ? "Typ" : "typ"));
      if (!singular) result+="y";
      return result;
    }
trType() [2/2]
virtual QCString TranslatorCzech::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1867 of file translator_cz.h.
    {
      QCString result((first_capital ? "Typ" : "typ"));
      if (!singular) result+="y";
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorCzech::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1886 of file translator_cz.h.
    {
      return "Omezen typ (Type Constraints)";
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorCzech::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1886 of file translator_cz.h.
    {
      return "Omezen typ (Type Constraints)";
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorCzech::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 590 of file translator_cz.h.
    { return "Dokumentace definic typ"; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorCzech::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 590 of file translator_cz.h.
    { return "Dokumentace definic typ"; }
trTypedefs() [1/2]
virtual QCString TranslatorCzech::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 554 of file translator_cz.h.
    { return "Definice typ"; }
trTypedefs() [2/2]
virtual QCString TranslatorCzech::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 554 of file translator_cz.h.
    { return "Definice typ"; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorCzech::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1737 of file translator_cz.h.
    { return "Dokumentace datovch typ"; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorCzech::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1737 of file translator_cz.h.
    { return "Dokumentace datovch typ"; }
trVariableDocumentation() [1/2]
virtual QCString TranslatorCzech::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 608 of file translator_cz.h.
    { return "Dokumentace promnnch"; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorCzech::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 608 of file translator_cz.h.
    { return "Dokumentace promnnch"; }
trVariables() [1/2]
virtual QCString TranslatorCzech::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 572 of file translator_cz.h.
    { return "Promnn"; }
trVariables() [2/2]
virtual QCString TranslatorCzech::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 572 of file translator_cz.h.
    { return "Promnn"; }
trVersion() [1/2]
virtual QCString TranslatorCzech::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 648 of file translator_cz.h.
    { return "Verze"; }
trVersion() [2/2]
virtual QCString TranslatorCzech::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 648 of file translator_cz.h.
    { return "Verze"; }
trVhdlType() [1/2]
virtual QCString TranslatorCzech::trVhdlType (uint64 type, bool single) [inline], [virtual]
VHDL type
Implements Translator.
Definition at line 2191 of file translator_cz.h.
    {
      switch(type)
      {
        case VhdlDocGen::LIBRARY:
          if (single) return "Knihovna";
          else return "Knihovny";
        case VhdlDocGen::PACKAGE:
          if (single) return "Balk";
          else return "Balky";
        case VhdlDocGen::SIGNAL:
          if (single) return "Signl";
          else return "Signly";
        case VhdlDocGen::COMPONENT:
          if (single) return "Komponenta";
          else return "Komponenty";
        case VhdlDocGen::CONSTANT:
          if (single) return "Konstanta";
          else return "Konstanty";
        case VhdlDocGen::ENTITY:
          if (single) return "Entita";
          else return "Entity";
        case VhdlDocGen::TYPE:
          if (single) return "Typ";
          else return "Typy";
        case VhdlDocGen::SUBTYPE:
          if (single) return "Subtyp";
          else return "Subtypy";
        case VhdlDocGen::FUNCTION:
          if (single) return "Funkce";
          else return "Funkce";
        case VhdlDocGen::RECORD:
          if (single) return "Zznam";
          else return "Zznamy";
        case VhdlDocGen::PROCEDURE:
          if (single) return "Procedura";
          else return "Procedury";
        case VhdlDocGen::ARCHITECTURE:
          if (single) return "Architektura";
          else return "Architektury";
        case VhdlDocGen::ATTRIBUTE:
          if (single) return "Atribut";
          else return "Atributy";
        case VhdlDocGen::PROCESS:
          if (single) return "Proces";
          else return "Procesy";
        case VhdlDocGen::PORT:
          if (single) return "Brna";
          else return "Brny";
        case VhdlDocGen::USE:
          if (single) return "Klauzule use";
          else return "Klauzule use";
        case VhdlDocGen::GENERIC:
          if (single) return "Generick parametr";
          else return "Generick parametry";
        case VhdlDocGen::PACKAGE_BODY:
          return "Tlo balku";
        case VhdlDocGen::UNITS:
          return "Fyzikln jednotky";
        case VhdlDocGen::SHAREDVARIABLE:
          if (single) return "Sdlen promnn";
          else return "Sdlen promnn";
        case VhdlDocGen::VFILE:
          if (single) return "Soubor";
          else return "Soubory";
        case VhdlDocGen::GROUP:
          if (single) return "Skupina";
          else return "Skupiny";
        case VhdlDocGen::INSTANTIATION:
          if (single) return "Vloen instance";
          else return "Vloen instance";
        case VhdlDocGen::ALIAS:
          if (single) return "Alias";
          else return "Aliasy";
        case VhdlDocGen::CONFIG:
          if (single) return "Konfigurace";
          else return "Konfigurace";
        case VhdlDocGen::MISCELLANEOUS:
          return "Ostatn";
        case VhdlDocGen::UCF_CONST:
          return "Omezen (constraints)";
        default:
          return "Tda";
      }
    }
References VhdlDocGen::ALIAS, VhdlDocGen::ARCHITECTURE, VhdlDocGen::ATTRIBUTE, VhdlDocGen::COMPONENT, VhdlDocGen::CONFIG, VhdlDocGen::CONSTANT, VhdlDocGen::ENTITY, VhdlDocGen::FUNCTION, VhdlDocGen::GENERIC, VhdlDocGen::GROUP, VhdlDocGen::INSTANTIATION, VhdlDocGen::LIBRARY, VhdlDocGen::MISCELLANEOUS, VhdlDocGen::PACKAGE, VhdlDocGen::PACKAGE_BODY, VhdlDocGen::PORT, VhdlDocGen::PROCEDURE, VhdlDocGen::PROCESS, VhdlDocGen::RECORD, VhdlDocGen::SHAREDVARIABLE, VhdlDocGen::SIGNAL, VhdlDocGen::SUBTYPE, VhdlDocGen::TYPE, VhdlDocGen::UCF_CONST, VhdlDocGen::UNITS, VhdlDocGen::USE, and VhdlDocGen::VFILE.
trVhdlType() [2/2]
virtual QCString TranslatorCzech::trVhdlType (uint64 type, bool single) [inline], [virtual]
VHDL type
Implements Translator.
Definition at line 2191 of file translator_cz.h.
    {
      switch(type)
      {
        case VhdlDocGen::LIBRARY:
          if (single) return "Knihovna";
          else return "Knihovny";
        case VhdlDocGen::PACKAGE:
          if (single) return "Balk";
          else return "Balky";
        case VhdlDocGen::SIGNAL:
          if (single) return "Signl";
          else return "Signly";
        case VhdlDocGen::COMPONENT:
          if (single) return "Komponenta";
          else return "Komponenty";
        case VhdlDocGen::CONSTANT:
          if (single) return "Konstanta";
          else return "Konstanty";
        case VhdlDocGen::ENTITY:
          if (single) return "Entita";
          else return "Entity";
        case VhdlDocGen::TYPE:
          if (single) return "Typ";
          else return "Typy";
        case VhdlDocGen::SUBTYPE:
          if (single) return "Subtyp";
          else return "Subtypy";
        case VhdlDocGen::FUNCTION:
          if (single) return "Funkce";
          else return "Funkce";
        case VhdlDocGen::RECORD:
          if (single) return "Zznam";
          else return "Zznamy";
        case VhdlDocGen::PROCEDURE:
          if (single) return "Procedura";
          else return "Procedury";
        case VhdlDocGen::ARCHITECTURE:
          if (single) return "Architektura";
          else return "Architektury";
        case VhdlDocGen::ATTRIBUTE:
          if (single) return "Atribut";
          else return "Atributy";
        case VhdlDocGen::PROCESS:
          if (single) return "Proces";
          else return "Procesy";
        case VhdlDocGen::PORT:
          if (single) return "Brna";
          else return "Brny";
        case VhdlDocGen::USE:
          if (single) return "Klauzule use";
          else return "Klauzule use";
        case VhdlDocGen::GENERIC:
          if (single) return "Generick parametr";
          else return "Generick parametry";
        case VhdlDocGen::PACKAGE_BODY:
          return "Tlo balku";
        case VhdlDocGen::UNITS:
          return "Fyzikln jednotky";
        case VhdlDocGen::SHAREDVARIABLE:
          if (single) return "Sdlen promnn";
          else return "Sdlen promnn";
        case VhdlDocGen::VFILE:
          if (single) return "Soubor";
          else return "Soubory";
        case VhdlDocGen::GROUP:
          if (single) return "Skupina";
          else return "Skupiny";
        case VhdlDocGen::INSTANTIATION:
          if (single) return "Vloen instance";
          else return "Vloen instance";
        case VhdlDocGen::ALIAS:
          if (single) return "Alias";
          else return "Aliasy";
        case VhdlDocGen::CONFIG:
          if (single) return "Konfigurace";
          else return "Konfigurace";
        case VhdlDocGen::MISCELLANEOUS:
          return "Ostatn";
        case VhdlDocGen::UCF_CONST:
          return "Omezen (constraints)";
        default:
          return "Tda";
      }
    }
References VhdlDocGen::ALIAS, VhdlDocGen::ARCHITECTURE, VhdlDocGen::ATTRIBUTE, VhdlDocGen::COMPONENT, VhdlDocGen::CONFIG, VhdlDocGen::CONSTANT, VhdlDocGen::ENTITY, VhdlDocGen::FUNCTION, VhdlDocGen::GENERIC, VhdlDocGen::GROUP, VhdlDocGen::INSTANTIATION, VhdlDocGen::LIBRARY, VhdlDocGen::MISCELLANEOUS, VhdlDocGen::PACKAGE, VhdlDocGen::PACKAGE_BODY, VhdlDocGen::PORT, VhdlDocGen::PROCEDURE, VhdlDocGen::PROCESS, VhdlDocGen::RECORD, VhdlDocGen::SHAREDVARIABLE, VhdlDocGen::SIGNAL, VhdlDocGen::SUBTYPE, VhdlDocGen::TYPE, VhdlDocGen::UCF_CONST, VhdlDocGen::UNITS, VhdlDocGen::USE, and VhdlDocGen::VFILE.
trWarning() [1/2]
virtual QCString TranslatorCzech::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 644 of file translator_cz.h.
    { return "Pozor"; }
trWarning() [2/2]
virtual QCString TranslatorCzech::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 644 of file translator_cz.h.
    { return "Pozor"; }
trWriteList() [1/2]
virtual QCString TranslatorCzech::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 777 of file translator_cz.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" a ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorCzech::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 777 of file translator_cz.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" a ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_cz.h
doxygen/src/translator_cz.h