TranslatorTurkish Class Reference
#include <translator_tr.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
Additional Inherited Members
Detailed Description
When defining a translator class for the new language, follow the description in the documentation. One of the steps says that you should copy the translator_en.h (this) file to your translator_xx.h new file. Your new language should use the Translator class as the base class. This means that you need to implement exactly the same (pure virtual) methods as the TranslatorEnglish does. Because of this, it is a good idea to start with the copy of TranslatorEnglish and replace the strings one by one.
It is not necessary to include `translator.h` or `translator_adapter.h` here. The files are included in the language.cpp correctly. Not including any of the mentioned files frees the maintainer from thinking about whether the first, the second, or both files should be included or not, and why. This holds namely for localized translators because their base class is changed occasionally to adapter classes when the Translator class changes the interface, or back to the Translator class (by the local maintainer) when the localized translator is made up-to-date again.
Definition at line 43 of file translator_tr.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorTurkish::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 80 of file translator_tr.h.
    {
      return "0x41F Turkey";
    }
getLanguageString() [2/2]
virtual QCString TranslatorTurkish::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 80 of file translator_tr.h.
    {
      return "0x41F Turkey";
    }
idLanguage() [1/2]
virtual QCString TranslatorTurkish::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 55 of file translator_tr.h.
    { return "turkish"; }
idLanguage() [2/2]
virtual QCString TranslatorTurkish::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 55 of file translator_tr.h.
    { return "turkish"; }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorTurkish::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 72 of file translator_tr.h.
    {
      return "\\usepackage[turkish]{babel}\n";
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorTurkish::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 72 of file translator_tr.h.
    {
      return "\\usepackage[turkish]{babel}\n";
    }
trAll() [1/2]
virtual QCString TranslatorTurkish::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1396 of file translator_tr.h.
    {
      return "Tm";
    }
trAll() [2/2]
virtual QCString TranslatorTurkish::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1396 of file translator_tr.h.
    {
      return "Tm";
    }
trAttention() [1/2]
virtual QCString TranslatorTurkish::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 960 of file translator_tr.h.
    {
      return "Dikkat";
    }
trAttention() [2/2]
virtual QCString TranslatorTurkish::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 960 of file translator_tr.h.
    {
      return "Dikkat";
    }
trAuthor() [1/2]
virtual QCString TranslatorTurkish::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1267 of file translator_tr.h.
    {
      QCString result((first_capital ? "Yazar" : "yazar"));
      if (!singular) result+="lar";
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorTurkish::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1267 of file translator_tr.h.
    {
      QCString result((first_capital ? "Yazar" : "yazar"));
      if (!singular) result+="lar";
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorTurkish::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1125 of file translator_tr.h.
    {
      return "Hata";
    }
trBug() [2/2]
virtual QCString TranslatorTurkish::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1125 of file translator_tr.h.
    {
      return "Hata";
    }
trBugList() [1/2]
virtual QCString TranslatorTurkish::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1130 of file translator_tr.h.
    {
      return "Hata Listesi";
    }
trBugList() [2/2]
virtual QCString TranslatorTurkish::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1130 of file translator_tr.h.
    {
      return "Hata Listesi";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorTurkish::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1517 of file translator_tr.h.
    {
      return "Bu fonksiyon iin arlma emas:";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorTurkish::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1517 of file translator_tr.h.
    {
      return "Bu fonksiyon iin arlma emas:";
    }
trCallGraph() [1/2]
virtual QCString TranslatorTurkish::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1401 of file translator_tr.h.
    {
      return "Bu fonksiyon iin arlma emas:";
    }
trCallGraph() [2/2]
virtual QCString TranslatorTurkish::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1401 of file translator_tr.h.
    {
      return "Bu fonksiyon iin arlma emas:";
    }
trClass() [1/2]
virtual QCString TranslatorTurkish::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1188 of file translator_tr.h.
    {
      QCString result((first_capital ? "Snf" : "snf"));
      if (!singular) result+="lar";
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorTurkish::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1188 of file translator_tr.h.
    {
      QCString result((first_capital ? "Snf" : "snf"));
      if (!singular) result+="lar";
      return result;
    }
trClassDiagram() [1/2]
virtual QCString TranslatorTurkish::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 512 of file translator_tr.h.
    {
      return clName+" iin kaltm emas:";
    }
trClassDiagram() [2/2]
virtual QCString TranslatorTurkish::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 512 of file translator_tr.h.
    {
      return clName+" iin kaltm emas:";
    }
trClassDocumentation() [1/2]
virtual QCString TranslatorTurkish::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 387 of file translator_tr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Veri Yaplar Dokmantasyonu";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Snf Dokmantasyonu";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorTurkish::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 387 of file translator_tr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Veri Yaplar Dokmantasyonu";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Snf Dokmantasyonu";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorTurkish::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1088 of file translator_tr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Veri Yaplar";
      }
      else
      {
        return "Snflar";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorTurkish::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1088 of file translator_tr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Veri Yaplar";
      }
      else
      {
        return "Snflar";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorTurkish::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 175 of file translator_tr.h.
    { return "Snf Hiyerarisi"; }
trClassHierarchy() [2/2]
virtual QCString TranslatorTurkish::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 175 of file translator_tr.h.
    { return "Snf Hiyerarisi"; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorTurkish::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 234 of file translator_tr.h.
    { return "Bu kaltm listesi tamamen olmasa da yaklak "
             "olarak alfabetik sraya konulmutur:";
    }
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorTurkish::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 234 of file translator_tr.h.
    { return "Bu kaltm listesi tamamen olmasa da yaklak "
             "olarak alfabetik sraya konulmutur:";
    }
trCode() [1/2]
virtual QCString TranslatorTurkish::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 860 of file translator_tr.h.
    {
      return "kod";
    }
trCode() [2/2]
virtual QCString TranslatorTurkish::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 860 of file translator_tr.h.
    {
      return "kod";
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorTurkish::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 815 of file translator_tr.h.
    {
      return clName+" iin ibirlii (collaboration) emas:";
    }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorTurkish::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 815 of file translator_tr.h.
    {
      return clName+" iin ibirlii (collaboration) emas:";
    }
trCompoundIndex() [1/2]
virtual QCString TranslatorTurkish::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 360 of file translator_tr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Veri Yaplar ndeksi";
      }
      else
      {
        return "Snf ndeksi";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorTurkish::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 360 of file translator_tr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Veri Yaplar ndeksi";
      }
      else
      {
        return "Snf ndeksi";
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorTurkish::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1571 of file translator_tr.h.
    { return "Veri Tipi ndeksi"; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorTurkish::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1571 of file translator_tr.h.
    { return "Veri Tipi ndeksi"; }
trCompoundList() [1/2]
virtual QCString TranslatorTurkish::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 179 of file translator_tr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Veri Yaplar";
      }
      else
      {
        return "Snf Listesi";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorTurkish::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 179 of file translator_tr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Veri Yaplar";
      }
      else
      {
        return "Snf Listesi";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorTurkish::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 249 of file translator_tr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Ksa tanmlaryla birlikte veri yaplar:";
      }
      else
      {
        return "Ksa tanmlaryla snflar, yaplar (struct), "
               "birleimler(union) ve arayzler:";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorTurkish::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 249 of file translator_tr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Ksa tanmlaryla birlikte veri yaplar:";
      }
      else
      {
        return "Ksa tanmlaryla snflar, yaplar (struct), "
               "birleimler(union) ve arayzler:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorTurkish::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1545 of file translator_tr.h.
    { return "Ksa tanmlaryla veri tipleri:"; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorTurkish::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1545 of file translator_tr.h.
    { return "Ksa tanmlaryla veri tipleri:"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorTurkish::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1537 of file translator_tr.h.
    { return "Veri Tipleri Listesi"; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorTurkish::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1537 of file translator_tr.h.
    { return "Veri Tipleri Listesi"; }
trCompoundMembers() [1/2]
virtual QCString TranslatorTurkish::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 196 of file translator_tr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Veri Alanlar";
      }
      else
      {
        return "Snf yeleri";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorTurkish::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 196 of file translator_tr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Veri Alanlar";
      }
      else
      {
        return "Snf yeleri";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorTurkish::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 264 of file translator_tr.h.
    {
      QCString result="Bu liste tm ";
      if (!extractAll)
      {
        result+="dokmante edilmi ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="yap(struct) ve birleim(union) yaplarn ierir";
      }
      else
      {
        result+="snf yelerini ierir";
      }
      result+=" ve ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="her alan yap(struct)/birleim(union) dokmantasyonuna balar:";
        }
        else
        {
          result+="her ye iin snf dokmantasyonuna balar:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="ait olduu yap(struct)/birleime(union) balar:";
        }
        else
        {
          result+="ait olduu snfa balar:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorTurkish::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 264 of file translator_tr.h.
    {
      QCString result="Bu liste tm ";
      if (!extractAll)
      {
        result+="dokmante edilmi ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="yap(struct) ve birleim(union) yaplarn ierir";
      }
      else
      {
        result+="snf yelerini ierir";
      }
      result+=" ve ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="her alan yap(struct)/birleim(union) dokmantasyonuna balar:";
        }
        else
        {
          result+="her ye iin snf dokmantasyonuna balar:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="ait olduu yap(struct)/birleime(union) balar:";
        }
        else
        {
          result+="ait olduu snfa balar:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorTurkish::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1549 of file translator_tr.h.
    {
      QCString result="Bu liste tm ";
      if (!extractAll)
      {
        result+="dokmante edilmi ";
      }
      result+="veri tiplerini ierir ve ";
      if (!extractAll)
      {
         result+="her yeyi veri yaps dokmantasyonuna balar:";
      }
      else
      {
         result+="ait olduklar veri tiplerine balar:";
      }
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorTurkish::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1549 of file translator_tr.h.
    {
      QCString result="Bu liste tm ";
      if (!extractAll)
      {
        result+="dokmante edilmi ";
      }
      result+="veri tiplerini ierir ve ";
      if (!extractAll)
      {
         result+="her yeyi veri yaps dokmantasyonuna balar:";
      }
      else
      {
         result+="ait olduklar veri tiplerine balar:";
      }
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorTurkish::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1541 of file translator_tr.h.
    { return "Veri Alanlar"; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorTurkish::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1541 of file translator_tr.h.
    { return "Veri Alanlar"; }
trCompoundReference() [1/2]
virtual QCString TranslatorTurkish::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 587 of file translator_tr.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" Snf"; break;
        case ClassDef::Struct: result+=" Yap(Struct)"; break;
        case ClassDef::Union: result+=" Birleim(Union)"; break;
        case ClassDef::Interface: result+=" Arayz(Interface)"; break;
        case ClassDef::Protocol: result+=" Protokol"; break;
        case ClassDef::Category: result+=" Kategori"; break;
        case ClassDef::Exception: result+=" stisna"; break;
        default: break;
      }
      if (isTemplate) result+=" ablon";
      result+=" Referans";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorTurkish::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 587 of file translator_tr.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" Snf"; break;
        case ClassDef::Struct: result+=" Yap(Struct)"; break;
        case ClassDef::Union: result+=" Birleim(Union)"; break;
        case ClassDef::Interface: result+=" Arayz(Interface)"; break;
        case ClassDef::Protocol: result+=" Protokol"; break;
        case ClassDef::Category: result+=" Kategori"; break;
        case ClassDef::Exception: result+=" stisna"; break;
        default: break;
      }
      if (isTemplate) result+=" ablon";
      result+=" Referans";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorTurkish::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1612 of file translator_tr.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" Modl"; break;
        case ClassDef::Struct: result+=" Tip"; break;
        case ClassDef::Union: result+=" Birleim(Union)"; break;
        case ClassDef::Interface: result+=" Arayz"; break;
        case ClassDef::Protocol: result+=" Protokol"; break;
        case ClassDef::Category: result+=" Kategori"; break;
        case ClassDef::Exception: result+=" stisna"; break;
        default: break;
      }
      if (isTemplate) result+=" ablon";
      result+=" Referans";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorTurkish::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1612 of file translator_tr.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" Modl"; break;
        case ClassDef::Struct: result+=" Tip"; break;
        case ClassDef::Union: result+=" Birleim(Union)"; break;
        case ClassDef::Interface: result+=" Arayz"; break;
        case ClassDef::Protocol: result+=" Protokol"; break;
        case ClassDef::Category: result+=" Kategori"; break;
        case ClassDef::Exception: result+=" stisna"; break;
        default: break;
      }
      if (isTemplate) result+=" ablon";
      result+=" Referans";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorTurkish::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 488 of file translator_tr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Veri Yaplar";
      }
      else
      {
        return "Snflar";
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorTurkish::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 488 of file translator_tr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Veri Yaplar";
      }
      else
      {
        return "Snflar";
      }
    }
References Config_getBool.
trConstructorDocumentation() [1/2]
virtual QCString TranslatorTurkish::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 825 of file translator_tr.h.
    {
      return "Constructor & Destructor Dokmantasyonu";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorTurkish::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 825 of file translator_tr.h.
    {
      return "Constructor & Destructor Dokmantasyonu";
    }
trDataTypes() [1/2]
virtual QCString TranslatorTurkish::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1595 of file translator_tr.h.
    { return "Veri Tipleri"; }
trDataTypes() [2/2]
virtual QCString TranslatorTurkish::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1595 of file translator_tr.h.
    { return "Veri Tipleri"; }
trDate() [1/2]
virtual QCString TranslatorTurkish::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 526 of file translator_tr.h.
    { return "Tarih"; }
trDate() [2/2]
virtual QCString TranslatorTurkish::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 526 of file translator_tr.h.
    { return "Tarih"; }
trDateTime() [1/2]
virtual QCString TranslatorTurkish::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1795 of file translator_tr.h.
    {
    static const char *days[] = { "Pzt","Sal","ar","Per","Cma","Cmt","Pzr" };
    static const char *months[] = { "Oca","ub","Mar","Nis","May","Haz","Tem","Au","Eyl","Ekm","Kas","Ara" };
    QCString sdate;
    sdate.sprintf("%s %s %d %d",days[dayOfWeek-1],months[month-1],day,year);
    if (includeTime)
    {
      QCString stime;
      stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
      sdate+=stime;
    }
    return sdate;
    }
References QCString::sprintf().
trDateTime() [2/2]
virtual QCString TranslatorTurkish::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1795 of file translator_tr.h.
    {
    static const char *days[] = { "Pzt","Sal","ar","Per","Cma","Cmt","Pzr" };
    static const char *months[] = { "Oca","ub","Mar","Nis","May","Haz","Tem","Au","Eyl","Ekm","Kas","Ara" };
    QCString sdate;
    sdate.sprintf("%s %s %d %d",days[dayOfWeek-1],months[month-1],day,year);
    if (includeTime)
    {
      QCString stime;
      stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
      sdate+=stime;
    }
    return sdate;
    }
References QCString::sprintf().
trDayOfWeek() [1/2]
virtual QCString TranslatorTurkish::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1811 of file translator_tr.h.
    {
      static const char *days_short[] = { "Pzt", "Sal", "ar", "Per", "Cum", "Cmt", "Paz" };
      static const char *days_full[] = { "Pazartesi", "Sal", "aramba", "Perembe", "Cuma", "Cumartesi", "Pazar" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      return text;
    }
trDayOfWeek() [2/2]
virtual QCString TranslatorTurkish::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1811 of file translator_tr.h.
    {
      static const char *days_short[] = { "Pzt", "Sal", "ar", "Per", "Cum", "Cmt", "Paz" };
      static const char *days_full[] = { "Pazartesi", "Sal", "aramba", "Perembe", "Cuma", "Cumartesi", "Pazar" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      return text;
    }
trDayPeriod() [1/2]
virtual QCString TranslatorTurkish::trDayPeriod (int period) [inline], [virtual]
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1825 of file translator_tr.h.
    {
      static const char *dayPeriod[] = { "", "S" };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorTurkish::trDayPeriod (int period) [inline], [virtual]
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1825 of file translator_tr.h.
    {
      static const char *dayPeriod[] = { "", "S" };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorTurkish::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 792 of file translator_tr.h.
    {
      return "@1 dosyasnn @0 numaral satrnda tanmlanmtr.";
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorTurkish::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 792 of file translator_tr.h.
    {
      return "@1 dosyasnn @0 numaral satrnda tanmlanmtr.";
    }
trDefinedIn() [1/2]
virtual QCString TranslatorTurkish::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 163 of file translator_tr.h.
    { return "tanmland yer"; }
trDefinedIn() [2/2]
virtual QCString TranslatorTurkish::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 163 of file translator_tr.h.
    { return "tanmland yer"; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorTurkish::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 796 of file translator_tr.h.
    {
      return "@0 dosyasnda tanmlanmtr.";
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorTurkish::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 796 of file translator_tr.h.
    {
      return "@0 dosyasnda tanmlanmtr.";
    }
trDefineDocumentation() [1/2]
virtual QCString TranslatorTurkish::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 458 of file translator_tr.h.
    { return "Makro Dokmantasyonu"; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorTurkish::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 458 of file translator_tr.h.
    { return "Makro Dokmantasyonu"; }
trDefines() [1/2]
virtual QCString TranslatorTurkish::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 422 of file translator_tr.h.
    { return "Makrolar"; }
trDefines() [2/2]
virtual QCString TranslatorTurkish::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 422 of file translator_tr.h.
    { return "Makrolar"; }
trDefineValue() [1/2]
virtual QCString TranslatorTurkish::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1115 of file translator_tr.h.
    {
      return "Deer:";
    }
trDefineValue() [2/2]
virtual QCString TranslatorTurkish::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1115 of file translator_tr.h.
    {
      return "Deer:";
    }
trDeprecated() [1/2]
virtual QCString TranslatorTurkish::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 805 of file translator_tr.h.
    {
      return "Kullanmdan kalkmtr";
    }
trDeprecated() [2/2]
virtual QCString TranslatorTurkish::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 805 of file translator_tr.h.
    {
      return "Kullanmdan kalkmtr";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorTurkish::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1324 of file translator_tr.h.
    {
      return "Kullanmdan Kalkanlar Listesl";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorTurkish::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1324 of file translator_tr.h.
    {
      return "Kullanmdan Kalkanlar Listesl";
    }
trDetailedDescription() [1/2]
virtual QCString TranslatorTurkish::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 96 of file translator_tr.h.
    { return "Ayrntl tanmlama"; }
trDetailedDescription() [2/2]
virtual QCString TranslatorTurkish::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 96 of file translator_tr.h.
    { return "Ayrntl tanmlama"; }
trDir() [1/2]
virtual QCString TranslatorTurkish::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1491 of file translator_tr.h.
    {
      QCString result((first_capital ? "Dizin" : "dizin"));
      if (!singular) result+="ler";
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorTurkish::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1491 of file translator_tr.h.
    {
      QCString result((first_capital ? "Dizin" : "dizin"));
      if (!singular) result+="ler";
      return result;
    }
trDirDocumentation() [1/2]
virtual QCString TranslatorTurkish::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1473 of file translator_tr.h.
    { return "Dizin Dokmantasyonu"; }
trDirDocumentation() [2/2]
virtual QCString TranslatorTurkish::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1473 of file translator_tr.h.
    { return "Dizin Dokmantasyonu"; }
trDirectories() [1/2]
virtual QCString TranslatorTurkish::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1479 of file translator_tr.h.
    { return "Dizinler"; }
trDirectories() [2/2]
virtual QCString TranslatorTurkish::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1479 of file translator_tr.h.
    { return "Dizinler"; }
trDirIndex() [1/2]
virtual QCString TranslatorTurkish::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1467 of file translator_tr.h.
    { return "Dizin Hiyerarisi"; }
trDirIndex() [2/2]
virtual QCString TranslatorTurkish::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1467 of file translator_tr.h.
    { return "Dizin Hiyerarisi"; }
trDirReference() [1/2]
virtual QCString TranslatorTurkish::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1485 of file translator_tr.h.
    { QCString result=dirName; result+=" Dizin Referans"; return result; }
trDirReference() [2/2]
virtual QCString TranslatorTurkish::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1485 of file translator_tr.h.
    { QCString result=dirName; result+=" Dizin Referans"; return result; }
trDirRelation() [1/2]
virtual QCString TranslatorTurkish::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1734 of file translator_tr.h.
    {
    return QCString(name)+" likisi";
    }
References setup::name.
trDirRelation() [2/2]
virtual QCString TranslatorTurkish::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1734 of file translator_tr.h.
    {
    return QCString(name)+" likisi";
    }
References setup::name.
trDocumentation() [1/2]
virtual QCString TranslatorTurkish::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 342 of file translator_tr.h.
    { return "Dokmantasyonu"; }
trDocumentation() [2/2]
virtual QCString TranslatorTurkish::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 342 of file translator_tr.h.
    { return "Dokmantasyonu"; }
trEnumerations() [1/2]
virtual QCString TranslatorTurkish::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 434 of file translator_tr.h.
    { return "Enmerasyonlar"; }
trEnumerations() [2/2]
virtual QCString TranslatorTurkish::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 434 of file translator_tr.h.
    { return "Enmerasyonlar"; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorTurkish::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 470 of file translator_tr.h.
    { return "Enmerasyon Tipi Dokmantasyonu"; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorTurkish::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 470 of file translator_tr.h.
    { return "Enmerasyon Tipi Dokmantasyonu"; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorTurkish::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1525 of file translator_tr.h.
    { return "Enmerasyon Dokmantasyonu"; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorTurkish::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1525 of file translator_tr.h.
    { return "Enmerasyon Dokmantasyonu"; }
trEnumerationValues() [1/2]
virtual QCString TranslatorTurkish::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 452 of file translator_tr.h.
    { return "Enmeratr"; }
trEnumerationValues() [2/2]
virtual QCString TranslatorTurkish::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 452 of file translator_tr.h.
    { return "Enmeratr"; }
trEnumName() [1/2]
virtual QCString TranslatorTurkish::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 155 of file translator_tr.h.
    { return "enum ad"; }
trEnumName() [2/2]
virtual QCString TranslatorTurkish::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 155 of file translator_tr.h.
    { return "enum ad"; }
trEnumValue() [1/2]
virtual QCString TranslatorTurkish::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 159 of file translator_tr.h.
    { return "enum deeri"; }
trEnumValue() [2/2]
virtual QCString TranslatorTurkish::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 159 of file translator_tr.h.
    { return "enum deeri"; }
trEventDocumentation() [1/2]
virtual QCString TranslatorTurkish::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1341 of file translator_tr.h.
    {
      return "Olay Dokmantasyonu";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorTurkish::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1341 of file translator_tr.h.
    {
      return "Olay Dokmantasyonu";
    }
trEvents() [1/2]
virtual QCString TranslatorTurkish::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1336 of file translator_tr.h.
    {
      return "Olaylar";
    }
trEvents() [2/2]
virtual QCString TranslatorTurkish::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1336 of file translator_tr.h.
    {
      return "Olaylar";
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorTurkish::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 412 of file translator_tr.h.
    { return "rnek Dokmantasyonu"; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorTurkish::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 412 of file translator_tr.h.
    { return "rnek Dokmantasyonu"; }
trExamples() [1/2]
virtual QCString TranslatorTurkish::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 226 of file translator_tr.h.
    { return "rnekler"; }
trExamples() [2/2]
virtual QCString TranslatorTurkish::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 226 of file translator_tr.h.
    { return "rnekler"; }
trExamplesDescription() [1/2]
virtual QCString TranslatorTurkish::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 328 of file translator_tr.h.
    { return "Tm rneklerin listesi aadadr:"; }
trExamplesDescription() [2/2]
virtual QCString TranslatorTurkish::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 328 of file translator_tr.h.
    { return "Tm rneklerin listesi aadadr:"; }
trExceptions() [1/2]
virtual QCString TranslatorTurkish::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 542 of file translator_tr.h.
    { return "stisnalar"; }
trExceptions() [2/2]
virtual QCString TranslatorTurkish::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 542 of file translator_tr.h.
    { return "stisnalar"; }
trFile() [1/2]
virtual QCString TranslatorTurkish::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1199 of file translator_tr.h.
    {
      QCString result((first_capital ? "Dosya" : "dosya"));
      if (!singular) result+="lar";
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorTurkish::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1199 of file translator_tr.h.
    {
      QCString result((first_capital ? "Dosya" : "dosya"));
      if (!singular) result+="lar";
      return result;
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorTurkish::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 406 of file translator_tr.h.
    { return "Dosya Dokmantasyonu"; }
trFileDocumentation() [2/2]
virtual QCString TranslatorTurkish::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 406 of file translator_tr.h.
    { return "Dosya Dokmantasyonu"; }
trFileIn() [1/2]
virtual QCString TranslatorTurkish::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1771 of file translator_tr.h.
    {
    return name+" dizinindeki dosya";
    }
References setup::name.
trFileIn() [2/2]
virtual QCString TranslatorTurkish::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1771 of file translator_tr.h.
    {
    return name+" dizinindeki dosya";
    }
References setup::name.
trFileIndex() [1/2]
virtual QCString TranslatorTurkish::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 375 of file translator_tr.h.
    { return "Dosya ndeksi"; }
trFileIndex() [2/2]
virtual QCString TranslatorTurkish::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 375 of file translator_tr.h.
    { return "Dosya ndeksi"; }
trFileList() [1/2]
virtual QCString TranslatorTurkish::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 192 of file translator_tr.h.
    { return "Dosya Listesi"; }
trFileList() [2/2]
virtual QCString TranslatorTurkish::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 192 of file translator_tr.h.
    { return "Dosya Listesi"; }
trFileListDescription() [1/2]
virtual QCString TranslatorTurkish::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 240 of file translator_tr.h.
    {
      QCString result="Bu liste tm ";
      if (!extractAll) result+="dokmante edilmi ";
      result+="dosyalar ksa aklamalaryla gstermektedir:";
      return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorTurkish::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 240 of file translator_tr.h.
    {
      QCString result="Bu liste tm ";
      if (!extractAll) result+="dokmante edilmi ";
      result+="dosyalar ksa aklamalaryla gstermektedir:";
      return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorTurkish::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 209 of file translator_tr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globaller";
      }
      else
      {
        return "Dosya yeleri";
      }
    }
References Config_getBool.
trFileMembers() [2/2]
virtual QCString TranslatorTurkish::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 209 of file translator_tr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globaller";
      }
      else
      {
        return "Dosya yeleri";
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
virtual QCString TranslatorTurkish::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 306 of file translator_tr.h.
    {
      QCString result="Bu liste tm ";
      if (!extractAll) result+="dokmante edilmi ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="fonksiyonlar, deikenleri, makrolar, enmerasyonlar ve typedef\'leri ierir";
      }
      else
      {
        result+="dosya yelerini ierir";
      }
      result+=" ve ";
      if (extractAll)
        result+="ait olduu dosyalar balar:";
      else
        result+="dokmantasyona balar:";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorTurkish::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 306 of file translator_tr.h.
    {
      QCString result="Bu liste tm ";
      if (!extractAll) result+="dokmante edilmi ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="fonksiyonlar, deikenleri, makrolar, enmerasyonlar ve typedef\'leri ierir";
      }
      else
      {
        result+="dosya yelerini ierir";
      }
      result+=" ve ";
      if (extractAll)
        result+="ait olduu dosyalar balar:";
      else
        result+="dokmantasyona balar:";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorTurkish::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 609 of file translator_tr.h.
    {
      QCString result=fileName;
      result+=" Dosya Referans";
      return result;
    }
trFileReference() [2/2]
virtual QCString TranslatorTurkish::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 609 of file translator_tr.h.
    {
      QCString result=fileName;
      result+=" Dosya Referans";
      return result;
    }
trFriends() [1/2]
virtual QCString TranslatorTurkish::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 569 of file translator_tr.h.
    { return "Arkadalar"; }
trFriends() [2/2]
virtual QCString TranslatorTurkish::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 569 of file translator_tr.h.
    { return "Arkadalar"; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorTurkish::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 476 of file translator_tr.h.
    { return "Fonksiyon Dokmantasyonu"; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorTurkish::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 476 of file translator_tr.h.
    { return "Fonksiyon Dokmantasyonu"; }
trFunctions() [1/2]
virtual QCString TranslatorTurkish::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 440 of file translator_tr.h.
    { return "Fonksiyonlar"; }
trFunctions() [2/2]
virtual QCString TranslatorTurkish::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 440 of file translator_tr.h.
    { return "Fonksiyonlar"; }
trGeneratedAt() [1/2]
virtual QCString TranslatorTurkish::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 503 of file translator_tr.h.
    {
      QCString result=projName+" iin "+date;
      if (!projName.isEmpty()) result+=" tarihinde ";
      result+=" reten: ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorTurkish::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 503 of file translator_tr.h.
    {
      QCString result=projName+" iin "+date;
      if (!projName.isEmpty()) result+=" tarihinde ";
      result+=" reten: ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorTurkish::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 147 of file translator_tr.h.
    { QCString result="Doxygen tarafndan";
      if (!s.isEmpty()) result+=s+" iin ";
      result+=" kaynak koddan otomatik retilmitir.";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorTurkish::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 147 of file translator_tr.h.
    { QCString result="Doxygen tarafndan";
      if (!s.isEmpty()) result+=s+" iin ";
      result+=" kaynak koddan otomatik retilmitir.";
      return result;
    }
References s.
trGeneratedBy() [1/2]
virtual QCString TranslatorTurkish::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 546 of file translator_tr.h.
    { return "Oluturan"; }
trGeneratedBy() [2/2]
virtual QCString TranslatorTurkish::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 546 of file translator_tr.h.
    { return "Oluturan"; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorTurkish::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 747 of file translator_tr.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Bu ";
      switch(compType)
      {
        case ClassDef::Class: result+="snf"; break;
        case ClassDef::Struct: result+="yap(struct)"; break;
        case ClassDef::Union: result+="birleim(union)"; break;
        case ClassDef::Interface: result+="arayz(interface)"; break;
        case ClassDef::Protocol: result+="protokol"; break;
        case ClassDef::Category: result+="kategori"; break;
        case ClassDef::Exception: result+="istisna"; break;
        default: break;
      }
      result+=" iin dokmantasyon aadaki dosya";
      if (single) result+=""; else result+="lar";
      result+="dan retilmitir:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorTurkish::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 747 of file translator_tr.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Bu ";
      switch(compType)
      {
        case ClassDef::Class: result+="snf"; break;
        case ClassDef::Struct: result+="yap(struct)"; break;
        case ClassDef::Union: result+="birleim(union)"; break;
        case ClassDef::Interface: result+="arayz(interface)"; break;
        case ClassDef::Protocol: result+="protokol"; break;
        case ClassDef::Category: result+="kategori"; break;
        case ClassDef::Exception: result+="istisna"; break;
        default: break;
      }
      result+=" iin dokmantasyon aadaki dosya";
      if (single) result+=""; else result+="lar";
      result+="dan retilmitir:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorTurkish::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1680 of file translator_tr.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Bu ";
      switch(compType)
      {
        case ClassDef::Class: result+="modl"; break;
        case ClassDef::Struct: result+="tip"; break;
        case ClassDef::Union: result+="birleim(union)"; break;
        case ClassDef::Interface: result+="arayz"; break;
        case ClassDef::Protocol: result+="protokol"; break;
        case ClassDef::Category: result+="kategori"; break;
        case ClassDef::Exception: result+="istisna"; break;
        default: break;
      }
      result+=" iin dokmantasyon aadaki dosya";
      if (single) result+=":"; else result+="lar";
      result="dan retilmitir:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorTurkish::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1680 of file translator_tr.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Bu ";
      switch(compType)
      {
        case ClassDef::Class: result+="modl"; break;
        case ClassDef::Struct: result+="tip"; break;
        case ClassDef::Union: result+="birleim(union)"; break;
        case ClassDef::Interface: result+="arayz"; break;
        case ClassDef::Protocol: result+="protokol"; break;
        case ClassDef::Category: result+="kategori"; break;
        case ClassDef::Exception: result+="istisna"; break;
        default: break;
      }
      result+=" iin dokmantasyon aadaki dosya";
      if (single) result+=":"; else result+="lar";
      result="dan retilmitir:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorTurkish::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1254 of file translator_tr.h.
    {
      QCString result((first_capital ? "Global deiken" : "global deiken"));
      if (!singular) result+="ler";
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorTurkish::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1254 of file translator_tr.h.
    {
      QCString result((first_capital ? "Global deiken" : "global deiken"));
      if (!singular) result+="ler";
      return result;
    }
trGlobalNamespace() [1/2]
virtual QCString TranslatorTurkish::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1746 of file translator_tr.h.
    {
    return "En st Seviye";
    }
trGlobalNamespace() [2/2]
virtual QCString TranslatorTurkish::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1746 of file translator_tr.h.
    {
    return "En st Seviye";
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorTurkish::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 835 of file translator_tr.h.
    {
      return "Bu dosyann dokmantasyonuna git.";
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorTurkish::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 835 of file translator_tr.h.
    {
      return "Bu dosyann dokmantasyonuna git.";
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorTurkish::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 868 of file translator_tr.h.
    {
      return "Grafiksel snf hiyerarisine git";
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorTurkish::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 868 of file translator_tr.h.
    {
      return "Grafiksel snf hiyerarisine git";
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorTurkish::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 830 of file translator_tr.h.
    {
      return "Bu dosyann kaynak koduna git.";
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorTurkish::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 830 of file translator_tr.h.
    {
      return "Bu dosyann kaynak koduna git.";
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorTurkish::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 872 of file translator_tr.h.
    {
      return "Metinsel snf hiyerarisine git";
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorTurkish::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 872 of file translator_tr.h.
    {
      return "Metinsel snf hiyerarisine git";
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorTurkish::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 864 of file translator_tr.h.
    {
      return "Grafiksel Snf Hiyerarisi";
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorTurkish::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 864 of file translator_tr.h.
    {
      return "Grafiksel Snf Hiyerarisi";
    }
trGroup() [1/2]
virtual QCString TranslatorTurkish::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1221 of file translator_tr.h.
    {
      QCString result((first_capital ? "Grup" : "grup"));
      if (!singular) result+="lar";
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorTurkish::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1221 of file translator_tr.h.
    {
      QCString result((first_capital ? "Grup" : "grup"));
      if (!singular) result+="lar";
      return result;
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorTurkish::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 354 of file translator_tr.h.
    { return "Hiyerarik ndeksi"; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorTurkish::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 354 of file translator_tr.h.
    { return "Hiyerarik ndeksi"; }
trImplementedFromList() [1/2]
virtual QCString TranslatorTurkish::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1292 of file translator_tr.h.
    {
      return "u yeleri gerekler: "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorTurkish::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1292 of file translator_tr.h.
    {
      return "u yeleri gerekler: "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorTurkish::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1300 of file translator_tr.h.
    {
      return "u yelerce gereklenir: "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorTurkish::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1300 of file translator_tr.h.
    {
      return "u yelerce gereklenir: "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorTurkish::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 964 of file translator_tr.h.
    {
      return "Bu ekil hangi dosyalarn dorudan ya da "
             "dolayl olarak bu dosyay ierdiini gsterir:";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorTurkish::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 964 of file translator_tr.h.
    {
      return "Bu ekil hangi dosyalarn dorudan ya da "
             "dolayl olarak bu dosyay ierdiini gsterir:";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorTurkish::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 820 of file translator_tr.h.
    {
      return fName+" iin ierme bamllk grafii:";
    }
trInclDepGraph() [2/2]
virtual QCString TranslatorTurkish::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 820 of file translator_tr.h.
    {
      return fName+" iin ierme bamllk grafii:";
    }
trIncludesFileIn() [1/2]
virtual QCString TranslatorTurkish::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1780 of file translator_tr.h.
    {
    return name + " dizinindeki dosyay kapsyor";
    }
References setup::name.
trIncludesFileIn() [2/2]
virtual QCString TranslatorTurkish::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1780 of file translator_tr.h.
    {
    return name + " dizinindeki dosyay kapsyor";
    }
References setup::name.
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorTurkish::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 141 of file translator_tr.h.
    { return " (kaltmla gelen yeleri de ierir)."; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorTurkish::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 141 of file translator_tr.h.
    { return " (kaltmla gelen yeleri de ierir)."; }
trInheritedByList() [1/2]
virtual QCString TranslatorTurkish::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 681 of file translator_tr.h.
    {
      return "u snflarn atasdr : "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorTurkish::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 681 of file translator_tr.h.
    {
      return "u snflarn atasdr : "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [1/2]
virtual QCString TranslatorTurkish::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 673 of file translator_tr.h.
    {
      return "u snflardan tremitir : "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorTurkish::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 673 of file translator_tr.h.
    {
      return "u snflardan tremitir : "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorTurkish::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 855 of file translator_tr.h.
    {
      return "lk deer:";
    }
trInitialValue() [2/2]
virtual QCString TranslatorTurkish::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 855 of file translator_tr.h.
    {
      return "lk deer:";
    }
trInvariant() [1/2]
virtual QCString TranslatorTurkish::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 850 of file translator_tr.h.
    {
      return "Deimez(Invariant)";
    }
trInvariant() [2/2]
virtual QCString TranslatorTurkish::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 850 of file translator_tr.h.
    {
      return "Deimez(Invariant)";
    }
trISOLang() [1/2]
virtual QCString TranslatorTurkish::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 76 of file translator_tr.h.
    {
      return "tr";
    }
trISOLang() [2/2]
virtual QCString TranslatorTurkish::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 76 of file translator_tr.h.
    {
      return "tr";
    }
trLegend() [1/2]
virtual QCString TranslatorTurkish::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1048 of file translator_tr.h.
    {
      return "lejant";
    }
trLegend() [2/2]
virtual QCString TranslatorTurkish::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1048 of file translator_tr.h.
    {
      return "lejant";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorTurkish::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 986 of file translator_tr.h.
    {
      return
        "Bu dosya doxygen tarafndan retilen grafiklerin nasl anlalacan "
        "aklar.<p>\n"
        "Aadaki rnee bakalm:\n"
        "\\code\n"
        "/*! Sadeleme yznden grnmeyen snf */\n"
        "class Invisible { };\n\n"
        "/*! Sadelemi snf, kaltm ilikisi gizli */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Doxygen yorumlaryla dokmante edilmemi snf */\n"
        "class Undocumented { };\n\n"
        "/*! Public kaltmla tretilen snf */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! Bir ablon snf */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Korumal kaltmla tretilen snf */\n"
        "class ProtectedBase { };\n\n"
        "/*! zel kaltmla tretilen snf */\n"
        "class PrivateBase { };\n\n"
        "/*! Tretilen snf tarafndan kullanlan snf */\n"
        "class Used { };\n\n"
        "/*! Pekok snftan treyen bir snf */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Bu kod aadaki emay oluturur:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "Yukardaki emadaki kutular aada aklanmtr:\n"
        "<ul>\n"
        "<li>Dolu gri kutu emann ait olduu yap(struct) ya da snf "
        "gsterir.\n"
        "<li>Siyah ereveli bir kutu dokmante edilmi bir yap(struct) ya da snf gsterir.\n"
        "<li>Gri ereveli bir kutu dokmante edilmemi bir yap(struct) ya da snf gsterir.\n"
        "<li>Krmz ereveli bir kutu tm kaltm/ierme ilikileri gsterilmemi ve dokmante "
        "edilmi bir yap(struct) ya da snf gsterir. %A ema belirlenen snrlara "
        "smyorsa sadeletirilir.\n"
        "</ul>\n"
        "Oklarn anlam aadaki gibidir:\n"
        "<ul>\n"
        "<li>Koyu mavi ok iki snf arasndaki public kaltm ilikisini "
        "gstermekte kullanlr.\n"
        "<li>Koyu yeil ok korumal kaltm gsterir.\n"
        "<li>Koyu krmz ok zel kaltm gsterir.\n"
        "<li>Mor kesikli izgi bir snfn dieri tarafndan ieriliyor ya da kullanlyor "
        "olduunu gsterir. Ok iaret edilen snfn hangi deiken(ler) tarafndan eriildiini "
        "gsteren etiketle iaretlenitir.\n"
        "<li>Sar kesikli izgi ablondan retilen bir snf ve ilgili ablon snf "
        "arasndaki ilikiyi gsterir. Ok treyen snfn ablon parametreleriyle "
        "etiketlenmitir.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorTurkish::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 986 of file translator_tr.h.
    {
      return
        "Bu dosya doxygen tarafndan retilen grafiklerin nasl anlalacan "
        "aklar.<p>\n"
        "Aadaki rnee bakalm:\n"
        "\\code\n"
        "/*! Sadeleme yznden grnmeyen snf */\n"
        "class Invisible { };\n\n"
        "/*! Sadelemi snf, kaltm ilikisi gizli */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Doxygen yorumlaryla dokmante edilmemi snf */\n"
        "class Undocumented { };\n\n"
        "/*! Public kaltmla tretilen snf */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! Bir ablon snf */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Korumal kaltmla tretilen snf */\n"
        "class ProtectedBase { };\n\n"
        "/*! zel kaltmla tretilen snf */\n"
        "class PrivateBase { };\n\n"
        "/*! Tretilen snf tarafndan kullanlan snf */\n"
        "class Used { };\n\n"
        "/*! Pekok snftan treyen bir snf */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Bu kod aadaki emay oluturur:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "Yukardaki emadaki kutular aada aklanmtr:\n"
        "<ul>\n"
        "<li>Dolu gri kutu emann ait olduu yap(struct) ya da snf "
        "gsterir.\n"
        "<li>Siyah ereveli bir kutu dokmante edilmi bir yap(struct) ya da snf gsterir.\n"
        "<li>Gri ereveli bir kutu dokmante edilmemi bir yap(struct) ya da snf gsterir.\n"
        "<li>Krmz ereveli bir kutu tm kaltm/ierme ilikileri gsterilmemi ve dokmante "
        "edilmi bir yap(struct) ya da snf gsterir. %A ema belirlenen snrlara "
        "smyorsa sadeletirilir.\n"
        "</ul>\n"
        "Oklarn anlam aadaki gibidir:\n"
        "<ul>\n"
        "<li>Koyu mavi ok iki snf arasndaki public kaltm ilikisini "
        "gstermekte kullanlr.\n"
        "<li>Koyu yeil ok korumal kaltm gsterir.\n"
        "<li>Koyu krmz ok zel kaltm gsterir.\n"
        "<li>Mor kesikli izgi bir snfn dieri tarafndan ieriliyor ya da kullanlyor "
        "olduunu gsterir. Ok iaret edilen snfn hangi deiken(ler) tarafndan eriildiini "
        "gsteren etiketle iaretlenitir.\n"
        "<li>Sar kesikli izgi ablondan retilen bir snf ve ilgili ablon snf "
        "arasndaki ilikiyi gsterir. Ok treyen snfn ablon parametreleriyle "
        "etiketlenmitir.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorTurkish::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 979 of file translator_tr.h.
    {
      return "ekil Lejant";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorTurkish::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 979 of file translator_tr.h.
    {
      return "ekil Lejant";
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorTurkish::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 129 of file translator_tr.h.
    { return "Tm yelerin listesi"; }
trListOfAllMembers() [2/2]
virtual QCString TranslatorTurkish::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 129 of file translator_tr.h.
    { return "Tm yelerin listesi"; }
trLoading() [1/2]
virtual QCString TranslatorTurkish::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1740 of file translator_tr.h.
    {
    return "Yklyor...";
    }
trLoading() [2/2]
virtual QCString TranslatorTurkish::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1740 of file translator_tr.h.
    {
    return "Yklyor...";
    }
trMainPage() [1/2]
virtual QCString TranslatorTurkish::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 779 of file translator_tr.h.
    { return "Ana Sayfa"; }
trMainPage() [2/2]
virtual QCString TranslatorTurkish::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 779 of file translator_tr.h.
    { return "Ana Sayfa"; }
trMember() [1/2]
virtual QCString TranslatorTurkish::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1243 of file translator_tr.h.
    {
      QCString result((first_capital ? "ye" : "ye"));
      if (!singular) result+="ler";
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorTurkish::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1243 of file translator_tr.h.
    {
      QCString result((first_capital ? "ye" : "ye"));
      if (!singular) result+="ler";
      return result;
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorTurkish::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 112 of file translator_tr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Alan Dokmantasyonu";
      }
      else
      {
        return "ye Veri Dokmantasyonu";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorTurkish::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 112 of file translator_tr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Alan Dokmantasyonu";
      }
      else
      {
        return "ye Veri Dokmantasyonu";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorTurkish::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 104 of file translator_tr.h.
    { return "ye Enmerasyon Dokmantasyonu"; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorTurkish::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 104 of file translator_tr.h.
    { return "ye Enmerasyon Dokmantasyonu"; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorTurkish::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member fonksiyonlar.
Implements Translator.
Definition at line 108 of file translator_tr.h.
    { return "ye Fonksiyon Dokmantasyonu"; }
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorTurkish::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member fonksiyonlar.
Implements Translator.
Definition at line 108 of file translator_tr.h.
    { return "ye Fonksiyon Dokmantasyonu"; }
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorTurkish::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1533 of file translator_tr.h.
    { return "ye Fonksiyon/Subroutine Dokmantasyonu"; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorTurkish::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1533 of file translator_tr.h.
    { return "ye Fonksiyon/Subroutine Dokmantasyonu"; }
trMemberList() [1/2]
virtual QCString TranslatorTurkish::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 133 of file translator_tr.h.
    { return "ye Listesi"; }
trMemberList() [2/2]
virtual QCString TranslatorTurkish::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 133 of file translator_tr.h.
    { return "ye Listesi"; }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorTurkish::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 100 of file translator_tr.h.
    { return "ye Typedef Dokmantasyonu"; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorTurkish::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 100 of file translator_tr.h.
    { return "ye Typedef Dokmantasyonu"; }
trModule() [1/2]
virtual QCString TranslatorTurkish::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1671 of file translator_tr.h.
    {
      QCString result((first_capital ? "Modl" : "modl"));
      if (!singular) result+="ler";
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorTurkish::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1671 of file translator_tr.h.
    {
      QCString result((first_capital ? "Modl" : "modl"));
      if (!singular) result+="ler";
      return result;
    }
trModuleDocumentation() [1/2]
virtual QCString TranslatorTurkish::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 381 of file translator_tr.h.
    { return "Modl Dokmantasyonu"; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorTurkish::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 381 of file translator_tr.h.
    { return "Modl Dokmantasyonu"; }
trModuleIndex() [1/2]
virtual QCString TranslatorTurkish::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 348 of file translator_tr.h.
    { return "Modl ndeksi"; }
trModuleIndex() [2/2]
virtual QCString TranslatorTurkish::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 348 of file translator_tr.h.
    { return "Modl ndeksi"; }
trModuleReference() [1/2]
virtual QCString TranslatorTurkish::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1633 of file translator_tr.h.
    {
      QCString result=namespaceName;
      result+=" Modl Referans";
      return result;
    }
trModuleReference() [2/2]
virtual QCString TranslatorTurkish::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1633 of file translator_tr.h.
    {
      QCString result=namespaceName;
      result+=" Modl Referans";
      return result;
    }
trModules() [1/2]
virtual QCString TranslatorTurkish::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 171 of file translator_tr.h.
    { return "Modller"; }
trModules() [2/2]
virtual QCString TranslatorTurkish::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 171 of file translator_tr.h.
    { return "Modller"; }
trModulesDescription() [1/2]
virtual QCString TranslatorTurkish::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 336 of file translator_tr.h.
    { return "Tm modllerin listesi aadadr:"; }
trModulesDescription() [2/2]
virtual QCString TranslatorTurkish::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 336 of file translator_tr.h.
    { return "Tm modllerin listesi aadadr:"; }
trModulesIndex() [1/2]
virtual QCString TranslatorTurkish::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1664 of file translator_tr.h.
    { return "Modller Indeksi"; }
trModulesIndex() [2/2]
virtual QCString TranslatorTurkish::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1664 of file translator_tr.h.
    { return "Modller Indeksi"; }
trModulesList() [1/2]
virtual QCString TranslatorTurkish::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1599 of file translator_tr.h.
    { return "Modller Listesi"; }
trModulesList() [2/2]
virtual QCString TranslatorTurkish::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1599 of file translator_tr.h.
    { return "Modller Listesi"; }
trModulesListDescription() [1/2]
virtual QCString TranslatorTurkish::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1603 of file translator_tr.h.
    {
      QCString result="Bu liste tm ";
      if (!extractAll) result+="dokmante edilmi ";
      result+="modlleri ksa tanmlarya ierir:";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorTurkish::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1603 of file translator_tr.h.
    {
      QCString result="Bu liste tm ";
      if (!extractAll) result+="dokmante edilmi ";
      result+="modlleri ksa tanmlarya ierir:";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorTurkish::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1645 of file translator_tr.h.
    {
      QCString result="Bu liste tm ";
      if (!extractAll) result+="dokmante edilmi ";
      result+="modl yelerini ierir ve ";
      if (extractAll)
      {
        result+="her yeyi modl dokmantasyonuna balar:";
      }
      else
      {
        result+="ait olduklar modllere balar:";
      }
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorTurkish::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1645 of file translator_tr.h.
    {
      QCString result="Bu liste tm ";
      if (!extractAll) result+="dokmante edilmi ";
      result+="modl yelerini ierir ve ";
      if (extractAll)
      {
        result+="her yeyi modl dokmantasyonuna balar:";
      }
      else
      {
        result+="ait olduklar modllere balar:";
      }
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorTurkish::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1641 of file translator_tr.h.
    { return "Modl yeleri"; }
trModulesMembers() [2/2]
virtual QCString TranslatorTurkish::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1641 of file translator_tr.h.
    { return "Modl yeleri"; }
trMonth() [1/2]
virtual QCString TranslatorTurkish::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1818 of file translator_tr.h.
    {
      static const char *months_short[] = { "Oca", "ub", "Mar", "Nis", "May", "Haz", "Tem", "Au", "Eyl", "Eki", "Kas", "Ara" };
      static const char *months_full[] = { "Ocak", "ubat", "Mart", "Nisan", "Mays", "Haziran", "Temmuz", "Austos", "Eyll", "Ekim", "Kasm", "Aralk" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      return text;
    }
trMonth() [2/2]
virtual QCString TranslatorTurkish::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1818 of file translator_tr.h.
    {
      static const char *months_short[] = { "Oca", "ub", "Mar", "Nis", "May", "Haz", "Tem", "Au", "Eyl", "Eki", "Kas", "Ara" };
      static const char *months_full[] = { "Ocak", "ubat", "Mart", "Nisan", "Mays", "Haziran", "Temmuz", "Austos", "Eyll", "Ekim", "Kasm", "Aralk" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      return text;
    }
trMore() [1/2]
virtual QCString TranslatorTurkish::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 125 of file translator_tr.h.
    { return "Ayrntlar..."; }
trMore() [2/2]
virtual QCString TranslatorTurkish::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 125 of file translator_tr.h.
    { return "Ayrntlar..."; }
trNamespace() [1/2]
virtual QCString TranslatorTurkish::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1210 of file translator_tr.h.
    {
      QCString result((first_capital ? "Namespace" : "namespace"));
      if (!singular) result+="\'ler";
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorTurkish::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1210 of file translator_tr.h.
    {
      QCString result((first_capital ? "Namespace" : "namespace"));
      if (!singular) result+="\'ler";
      return result;
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorTurkish::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 727 of file translator_tr.h.
    { return "Namespace Dokmantasyonu"; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorTurkish::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 727 of file translator_tr.h.
    { return "Namespace Dokmantasyonu"; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorTurkish::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 721 of file translator_tr.h.
    { return "Namespace ndeksi"; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorTurkish::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 721 of file translator_tr.h.
    { return "Namespace ndeksi"; }
trNamespaceList() [1/2]
virtual QCString TranslatorTurkish::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 554 of file translator_tr.h.
    { return "Namespace Listesi"; }
trNamespaceList() [2/2]
virtual QCString TranslatorTurkish::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 554 of file translator_tr.h.
    { return "Namespace Listesi"; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorTurkish::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 558 of file translator_tr.h.
    {
      QCString result="Tm ";
      if (!extractAll) result+="dokmante edilmi ";
      result+="namespace\'lerin ksa tanmlaryla listesi aadadr:";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorTurkish::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 558 of file translator_tr.h.
    {
      QCString result="Tm ";
      if (!extractAll) result+="dokmante edilmi ";
      result+="namespace\'lerin ksa tanmlaryla listesi aadadr:";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorTurkish::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 707 of file translator_tr.h.
    {
      QCString result="Bu liste tm ";
      if (!extractAll) result+="dokmante edilmi ";
      result+="namespace yelerini listeler ve ";
      if (extractAll)
        result+="her ye iin ye dokmantasyonuna balar:";
      else
        result+="ait olduu namespace\'lere balar:";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorTurkish::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 707 of file translator_tr.h.
    {
      QCString result="Bu liste tm ";
      if (!extractAll) result+="dokmante edilmi ";
      result+="namespace yelerini listeler ve ";
      if (extractAll)
        result+="her ye iin ye dokmantasyonuna balar:";
      else
        result+="ait olduu namespace\'lere balar:";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorTurkish::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 703 of file translator_tr.h.
    { return "Namespace yeleri"; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorTurkish::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 703 of file translator_tr.h.
    { return "Namespace yeleri"; }
trNamespaceReference() [1/2]
virtual QCString TranslatorTurkish::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 617 of file translator_tr.h.
    {
      QCString result=namespaceName;
      result+=" Namespace Referans";
      return result;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorTurkish::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 617 of file translator_tr.h.
    {
      QCString result=namespaceName;
      result+=" Namespace Referans";
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorTurkish::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 737 of file translator_tr.h.
    { return "Namespace\'ler"; }
trNamespaces() [2/2]
virtual QCString TranslatorTurkish::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 737 of file translator_tr.h.
    { return "Namespace\'ler"; }
trNoMatches() [1/2]
virtual QCString TranslatorTurkish::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1758 of file translator_tr.h.
    {
    return "Eleme Yok";
    }
trNoMatches() [2/2]
virtual QCString TranslatorTurkish::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1758 of file translator_tr.h.
    {
    return "Eleme Yok";
    }
trNote() [1/2]
virtual QCString TranslatorTurkish::trNote () [inline], [virtual]
Implements Translator.
Definition at line 885 of file translator_tr.h.
    {
      return "Not";
    }
trNote() [2/2]
virtual QCString TranslatorTurkish::trNote () [inline], [virtual]
Implements Translator.
Definition at line 885 of file translator_tr.h.
    {
      return "Not";
    }
trOverloadText() [1/2]
virtual QCString TranslatorTurkish::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1505 of file translator_tr.h.
    {
       return "Bu ok anlaml (overloaded) bir ye fonksiyondur, "
              "tamamlk asndan burada verilmektedir. Yukardaki fonksiyondan "
              "sadece ald argman(lar) asndan farkldr.";
    }
trOverloadText() [2/2]
virtual QCString TranslatorTurkish::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1505 of file translator_tr.h.
    {
       return "Bu ok anlaml (overloaded) bir ye fonksiyondur, "
              "tamamlk asndan burada verilmektedir. Yukardaki fonksiyondan "
              "sadece ald argman(lar) asndan farkldr.";
    }
trPackage() [1/2]
virtual QCString TranslatorTurkish::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1100 of file translator_tr.h.
    {
      return "Paket "+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorTurkish::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1100 of file translator_tr.h.
    {
      return "Paket "+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorTurkish::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1377 of file translator_tr.h.
    {
      return "Packet zellikleri(attribute)";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorTurkish::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1377 of file translator_tr.h.
    {
      return "Packet zellikleri(attribute)";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorTurkish::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class fonksiyonlar with package scope.
Implements Translator.
Definition at line 1359 of file translator_tr.h.
    {
      return "Paket Fonksiyonlar";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorTurkish::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class fonksiyonlar with package scope.
Implements Translator.
Definition at line 1359 of file translator_tr.h.
    {
      return "Paket Fonksiyonlar";
    }
trPackageListDescription() [1/2]
virtual QCString TranslatorTurkish::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1105 of file translator_tr.h.
    {
      return "Paketler ve ksa tanmlar (var ise):";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorTurkish::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1105 of file translator_tr.h.
    {
      return "Paketler ve ksa tanmlar (var ise):";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorTurkish::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1363 of file translator_tr.h.
    {
      return "Paket yeler";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorTurkish::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1363 of file translator_tr.h.
    {
      return "Paket yeler";
    }
trPackages() [1/2]
virtual QCString TranslatorTurkish::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1110 of file translator_tr.h.
    {
      return "Paketler";
    }
trPackages() [2/2]
virtual QCString TranslatorTurkish::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1110 of file translator_tr.h.
    {
      return "Paketler";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorTurkish::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1352 of file translator_tr.h.
    {
      return "Paket Tipleri";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorTurkish::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1352 of file translator_tr.h.
    {
      return "Paket Tipleri";
    }
trPage() [1/2]
virtual QCString TranslatorTurkish::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1232 of file translator_tr.h.
    {
      QCString result((first_capital ? "Sayfa" : "sayfa"));
      if (!singular) result+="lar";
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorTurkish::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1232 of file translator_tr.h.
    {
      QCString result((first_capital ? "Sayfa" : "sayfa"));
      if (!singular) result+="lar";
      return result;
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorTurkish::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 785 of file translator_tr.h.
    { return "sf."; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorTurkish::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 785 of file translator_tr.h.
    { return "sf."; }
trPageIndex() [1/2]
virtual QCString TranslatorTurkish::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 876 of file translator_tr.h.
    {
      return "Sayfa ndeksi";
    }
trPageIndex() [2/2]
virtual QCString TranslatorTurkish::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 876 of file translator_tr.h.
    {
      return "Sayfa ndeksi";
    }
trParameters() [1/2]
virtual QCString TranslatorTurkish::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 538 of file translator_tr.h.
    { return "Parametreler"; }
trParameters() [2/2]
virtual QCString TranslatorTurkish::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 538 of file translator_tr.h.
    { return "Parametreler"; }
trPostcondition() [1/2]
virtual QCString TranslatorTurkish::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 845 of file translator_tr.h.
    {
      return "Son art (Postcondition)";
    }
trPostcondition() [2/2]
virtual QCString TranslatorTurkish::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 845 of file translator_tr.h.
    {
      return "Son art (Postcondition)";
    }
trPrecondition() [1/2]
virtual QCString TranslatorTurkish::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 840 of file translator_tr.h.
    {
      return "n art";
    }
trPrecondition() [2/2]
virtual QCString TranslatorTurkish::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 840 of file translator_tr.h.
    {
      return "n art";
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorTurkish::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 924 of file translator_tr.h.
    {
      return "zel zellikler(attribute)";
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorTurkish::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 924 of file translator_tr.h.
    {
      return "zel zellikler(attribute)";
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorTurkish::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 638 of file translator_tr.h.
    { return "zel ye Fonksiyonlar"; }
trPrivateMembers() [2/2]
virtual QCString TranslatorTurkish::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 638 of file translator_tr.h.
    { return "zel ye Fonksiyonlar"; }
trPrivateSlots() [1/2]
virtual QCString TranslatorTurkish::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 640 of file translator_tr.h.
    { return "zel Slotlar"; }
trPrivateSlots() [2/2]
virtual QCString TranslatorTurkish::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 640 of file translator_tr.h.
    { return "zel Slotlar"; }
trPrivateTypes() [1/2]
virtual QCString TranslatorTurkish::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 920 of file translator_tr.h.
    {
      return "zel Tipler";
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorTurkish::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 920 of file translator_tr.h.
    {
      return "zel Tipler";
    }
trProperties() [1/2]
virtual QCString TranslatorTurkish::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1073 of file translator_tr.h.
    {
      return "zellikler";
    }
trProperties() [2/2]
virtual QCString TranslatorTurkish::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1073 of file translator_tr.h.
    {
      return "zellikler";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorTurkish::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1078 of file translator_tr.h.
    {
      return "zellik Dokmantasyonu";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorTurkish::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1078 of file translator_tr.h.
    {
      return "zellik Dokmantasyonu";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorTurkish::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 912 of file translator_tr.h.
    {
      return "Korumal zellikler(attribute)";
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorTurkish::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 912 of file translator_tr.h.
    {
      return "Korumal zellikler(attribute)";
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorTurkish::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 632 of file translator_tr.h.
    { return "Korumal ye Fonksiyonlar"; }
trProtectedMembers() [2/2]
virtual QCString TranslatorTurkish::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 632 of file translator_tr.h.
    { return "Korumal ye Fonksiyonlar"; }
trProtectedSlots() [1/2]
virtual QCString TranslatorTurkish::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 634 of file translator_tr.h.
    { return "Korumal Slotlar"; }
trProtectedSlots() [2/2]
virtual QCString TranslatorTurkish::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 634 of file translator_tr.h.
    { return "Korumal Slotlar"; }
trProtectedTypes() [1/2]
virtual QCString TranslatorTurkish::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 908 of file translator_tr.h.
    {
      return "Korumal Tipler";
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorTurkish::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 908 of file translator_tr.h.
    {
      return "Korumal Tipler";
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorTurkish::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 893 of file translator_tr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Veri Alanlar";
      }
      else
      {
        return "Public zellikler(attribute)";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorTurkish::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 893 of file translator_tr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Veri Alanlar";
      }
      else
      {
        return "Public zellikler(attribute)";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorTurkish::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 624 of file translator_tr.h.
    { return "Public ye Fonksiyonlar"; }
trPublicMembers() [2/2]
virtual QCString TranslatorTurkish::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 624 of file translator_tr.h.
    { return "Public ye Fonksiyonlar"; }
trPublicSlots() [1/2]
virtual QCString TranslatorTurkish::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 626 of file translator_tr.h.
    { return "Public Slotlar"; }
trPublicSlots() [2/2]
virtual QCString TranslatorTurkish::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 626 of file translator_tr.h.
    { return "Public Slotlar"; }
trPublicTypes() [1/2]
virtual QCString TranslatorTurkish::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 889 of file translator_tr.h.
    {
      return "Public Tipler";
    }
trPublicTypes() [2/2]
virtual QCString TranslatorTurkish::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 889 of file translator_tr.h.
    {
      return "Public Tipler";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorTurkish::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 952 of file translator_tr.h.
    {
      return "Referans veren";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorTurkish::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 952 of file translator_tr.h.
    {
      return "Referans veren";
    }
trReferenceManual() [1/2]
virtual QCString TranslatorTurkish::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 416 of file translator_tr.h.
    { return "Referans Kitab"; }
trReferenceManual() [2/2]
virtual QCString TranslatorTurkish::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 416 of file translator_tr.h.
    { return "Referans Kitab"; }
trReferences() [1/2]
virtual QCString TranslatorTurkish::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1280 of file translator_tr.h.
    {
      return "Referanslar";
    }
trReferences() [2/2]
virtual QCString TranslatorTurkish::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1280 of file translator_tr.h.
    {
      return "Referanslar";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorTurkish::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 689 of file translator_tr.h.
    {
      return "u yeleri yeniden tanmlar : "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorTurkish::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 689 of file translator_tr.h.
    {
      return "u yeleri yeniden tanmlar : "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorTurkish::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 697 of file translator_tr.h.
    {
      return "u yeler tarafndan yeniden tanmlanmtr : "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorTurkish::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 697 of file translator_tr.h.
    {
      return "u yeler tarafndan yeniden tanmlanmtr : "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorTurkish::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 579 of file translator_tr.h.
    { return "Arkada Ve lgili Fonksiyon Dokmantasyonu"; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorTurkish::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 579 of file translator_tr.h.
    { return "Arkada Ve lgili Fonksiyon Dokmantasyonu"; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorTurkish::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related fonksiyonlar.
Implements Translator.
Definition at line 88 of file translator_tr.h.
    { return "lgili Fonksiyonlar"; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorTurkish::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related fonksiyonlar.
Implements Translator.
Definition at line 88 of file translator_tr.h.
    { return "lgili Fonksiyonlar"; }
trRelatedPages() [1/2]
virtual QCString TranslatorTurkish::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 222 of file translator_tr.h.
    { return "lgili Sayfalar"; }
trRelatedPages() [2/2]
virtual QCString TranslatorTurkish::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 222 of file translator_tr.h.
    { return "lgili Sayfalar"; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorTurkish::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 332 of file translator_tr.h.
    { return "lgili tm dokmantasyon sayfalarnn listesi aadadr:"; }
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorTurkish::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 332 of file translator_tr.h.
    { return "lgili tm dokmantasyon sayfalarnn listesi aadadr:"; }
trRelatedSubscript() [1/2]
virtual QCString TranslatorTurkish::trRelatedSubscript () [inline], [virtual]
subscript for the related fonksiyonlar.
Implements Translator.
Definition at line 92 of file translator_tr.h.
    { return "(Not: Bu fonksiyonlar ye fonksiyon deildir.)"; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorTurkish::trRelatedSubscript () [inline], [virtual]
subscript for the related fonksiyonlar.
Implements Translator.
Definition at line 92 of file translator_tr.h.
    { return "(Not: Bu fonksiyonlar ye fonksiyon deildir.)"; }
trRemarks() [1/2]
virtual QCString TranslatorTurkish::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 956 of file translator_tr.h.
    {
      return "Dipnotlar";
    }
trRemarks() [2/2]
virtual QCString TranslatorTurkish::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 956 of file translator_tr.h.
    {
      return "Dipnotlar";
    }
trReturns() [1/2]
virtual QCString TranslatorTurkish::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 530 of file translator_tr.h.
    { return "Dndrd deer"; }
trReturns() [2/2]
virtual QCString TranslatorTurkish::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 530 of file translator_tr.h.
    { return "Dndrd deer"; }
trReturnValues() [1/2]
virtual QCString TranslatorTurkish::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 774 of file translator_tr.h.
    { return "Dndrd deerler"; }
trReturnValues() [2/2]
virtual QCString TranslatorTurkish::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 774 of file translator_tr.h.
    { return "Dndrd deerler"; }
trRTFansicp() [1/2]
virtual QCString TranslatorTurkish::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1164 of file translator_tr.h.
    {
      return "1254";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorTurkish::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1164 of file translator_tr.h.
    {
      return "1254";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorTurkish::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1173 of file translator_tr.h.
    {
      return "162";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorTurkish::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1173 of file translator_tr.h.
    {
      return "162";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorTurkish::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1179 of file translator_tr.h.
    {
      return "ndeks";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorTurkish::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1179 of file translator_tr.h.
    {
      return "ndeks";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorTurkish::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1312 of file translator_tr.h.
    {
      return "indekiler";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorTurkish::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1312 of file translator_tr.h.
    {
      return "indekiler";
    }
trSearch() [1/2]
virtual QCString TranslatorTurkish::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 230 of file translator_tr.h.
    { return "Ara"; }
trSearch() [2/2]
virtual QCString TranslatorTurkish::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 230 of file translator_tr.h.
    { return "Ara"; }
trSearching() [1/2]
virtual QCString TranslatorTurkish::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1752 of file translator_tr.h.
    {
    return "Aryor...";
    }
trSearching() [2/2]
virtual QCString TranslatorTurkish::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1752 of file translator_tr.h.
    {
    return "Aryor...";
    }
trSearchMatches() [1/2]
virtual QCString TranslatorTurkish::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1444 of file translator_tr.h.
    {
      return "Eleme:";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorTurkish::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1444 of file translator_tr.h.
    {
      return "Eleme:";
    }
trSearchResults() [1/2]
virtual QCString TranslatorTurkish::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1425 of file translator_tr.h.
    {
      if (numDocuments==0)
      {
        return "zgnm, sorgunuzla eleen dokman bulunamad.";
      }
      else if (numDocuments==1)
      {
        return "Sorgunuzla eleen <b>1</b> dokman bulundu.";
      }
      else
      {
        return "Sorgunuzla eleen <b>$num</b> dokman bulundu. "
               "nce en iyi elemeler gsteriliyor.";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorTurkish::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1425 of file translator_tr.h.
    {
      if (numDocuments==0)
      {
        return "zgnm, sorgunuzla eleen dokman bulunamad.";
      }
      else if (numDocuments==1)
      {
        return "Sorgunuzla eleen <b>1</b> dokman bulundu.";
      }
      else
      {
        return "Sorgunuzla eleen <b>$num</b> dokman bulundu. "
               "nce en iyi elemeler gsteriliyor.";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorTurkish::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1413 of file translator_tr.h.
    {
      return "Arama sonular";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorTurkish::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1413 of file translator_tr.h.
    {
      return "Arama sonular";
    }
trSeeAlso() [1/2]
virtual QCString TranslatorTurkish::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 534 of file translator_tr.h.
    { return "Ayrca Baknz"; }
trSeeAlso() [2/2]
virtual QCString TranslatorTurkish::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 534 of file translator_tr.h.
    { return "Ayrca Baknz"; }
trSignals() [1/2]
virtual QCString TranslatorTurkish::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 628 of file translator_tr.h.
    { return "Sinyaller"; }
trSignals() [2/2]
virtual QCString TranslatorTurkish::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 628 of file translator_tr.h.
    { return "Sinyaller"; }
trSince() [1/2]
virtual QCString TranslatorTurkish::trSince () [inline], [virtual]
Implements Translator.
Definition at line 969 of file translator_tr.h.
    {
      return "u zamandan beri";
    }
trSince() [2/2]
virtual QCString TranslatorTurkish::trSince () [inline], [virtual]
Implements Translator.
Definition at line 969 of file translator_tr.h.
    {
      return "u zamandan beri";
    }
trSourceFile() [1/2]
virtual QCString TranslatorTurkish::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1455 of file translator_tr.h.
    {
      return filename + " Kaynak Dosyas";
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorTurkish::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1455 of file translator_tr.h.
    {
      return filename + " Kaynak Dosyas";
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorTurkish::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1384 of file translator_tr.h.
    {
      return "Statik Packet zellikleri(attribute)";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorTurkish::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1384 of file translator_tr.h.
    {
      return "Statik Packet zellikleri(attribute)";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorTurkish::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class fonksiyonlar with package scope.
Implements Translator.
Definition at line 1370 of file translator_tr.h.
    {
      return "Static Pakat Fonksiyonlar";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorTurkish::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class fonksiyonlar with package scope.
Implements Translator.
Definition at line 1370 of file translator_tr.h.
    {
      return "Static Pakat Fonksiyonlar";
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorTurkish::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 928 of file translator_tr.h.
    {
      return "Statik zel zellikler(attribute)";
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorTurkish::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 928 of file translator_tr.h.
    {
      return "Statik zel zellikler(attribute)";
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorTurkish::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 642 of file translator_tr.h.
    { return "Statik zel ye Fonksiyonlar"; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorTurkish::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 642 of file translator_tr.h.
    { return "Statik zel ye Fonksiyonlar"; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorTurkish::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 916 of file translator_tr.h.
    {
      return "Statik Korumal Attributes";
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorTurkish::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 916 of file translator_tr.h.
    {
      return "Statik Korumal Attributes";
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorTurkish::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 636 of file translator_tr.h.
    { return "Statik Korumal ye Fonksiyonlar"; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorTurkish::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 636 of file translator_tr.h.
    { return "Statik Korumal ye Fonksiyonlar"; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorTurkish::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 904 of file translator_tr.h.
    {
      return "Statik Public zellikler(attribute)";
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorTurkish::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 904 of file translator_tr.h.
    {
      return "Statik Public zellikler(attribute)";
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorTurkish::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 630 of file translator_tr.h.
    { return "Statik Public ye Fonksiyonlar"; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorTurkish::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 630 of file translator_tr.h.
    { return "Statik Public ye Fonksiyonlar"; }
trSubprogram() [1/2]
virtual QCString TranslatorTurkish::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1715 of file translator_tr.h.
    {
      QCString result((first_capital ? "Alt program" : "alt program"));
      if (!singular) result+="lar";
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorTurkish::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1715 of file translator_tr.h.
    {
      QCString result((first_capital ? "Alt program" : "alt program"));
      if (!singular) result+="lar";
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorTurkish::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1589 of file translator_tr.h.
    { return "Fonksiyon/Subroutine Dokmantasyonu"; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorTurkish::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1589 of file translator_tr.h.
    { return "Fonksiyon/Subroutine Dokmantasyonu"; }
trSubprograms() [1/2]
virtual QCString TranslatorTurkish::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1583 of file translator_tr.h.
    { return "Fonksiyonlar/Subroutine\'ler"; }
trSubprograms() [2/2]
virtual QCString TranslatorTurkish::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1583 of file translator_tr.h.
    { return "Fonksiyonlar/Subroutine\'ler"; }
trTest() [1/2]
virtual QCString TranslatorTurkish::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1058 of file translator_tr.h.
    {
      return "Test";
    }
trTest() [2/2]
virtual QCString TranslatorTurkish::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1058 of file translator_tr.h.
    {
      return "Test";
    }
trTestList() [1/2]
virtual QCString TranslatorTurkish::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1063 of file translator_tr.h.
    {
      return "Test Listesi";
    }
trTestList() [2/2]
virtual QCString TranslatorTurkish::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1063 of file translator_tr.h.
    {
      return "Test Listesi";
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorTurkish::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 137 of file translator_tr.h.
    { return "u snfn tm yelerinin listesidir: "; }
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorTurkish::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 137 of file translator_tr.h.
    { return "u snfn tm yelerinin listesidir: "; }
trTodo() [1/2]
virtual QCString TranslatorTurkish::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 938 of file translator_tr.h.
    {
      return "Yaplacak";
    }
trTodo() [2/2]
virtual QCString TranslatorTurkish::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 938 of file translator_tr.h.
    {
      return "Yaplacak";
    }
trTodoList() [1/2]
virtual QCString TranslatorTurkish::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 943 of file translator_tr.h.
    {
      return "Yaplacaklar Listesi";
    }
trTodoList() [2/2]
virtual QCString TranslatorTurkish::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 943 of file translator_tr.h.
    {
      return "Yaplacaklar Listesi";
    }
trType() [1/2]
virtual QCString TranslatorTurkish::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1705 of file translator_tr.h.
    {
      QCString result((first_capital ? "Tip" : "tip"));
      if (!singular) result+="ler";
      return result;
    }
trType() [2/2]
virtual QCString TranslatorTurkish::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1705 of file translator_tr.h.
    {
      QCString result((first_capital ? "Tip" : "tip"));
      if (!singular) result+="ler";
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorTurkish::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1723 of file translator_tr.h.
    {
      return "Tip Snrlamalar";
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorTurkish::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1723 of file translator_tr.h.
    {
      return "Tip Snrlamalar";
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorTurkish::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 464 of file translator_tr.h.
    { return "Typedef Dokmantasyonu"; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorTurkish::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 464 of file translator_tr.h.
    { return "Typedef Dokmantasyonu"; }
trTypedefs() [1/2]
virtual QCString TranslatorTurkish::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 428 of file translator_tr.h.
    { return "Typedef\'ler"; }
trTypedefs() [2/2]
virtual QCString TranslatorTurkish::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 428 of file translator_tr.h.
    { return "Typedef\'ler"; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorTurkish::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1577 of file translator_tr.h.
    { return "Veri Tipi Dokmantasyonu"; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorTurkish::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1577 of file translator_tr.h.
    { return "Veri Tipi Dokmantasyonu"; }
trVariableDocumentation() [1/2]
virtual QCString TranslatorTurkish::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 482 of file translator_tr.h.
    { return "Deiken Dokmantasyonu"; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorTurkish::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 482 of file translator_tr.h.
    { return "Deiken Dokmantasyonu"; }
trVariables() [1/2]
virtual QCString TranslatorTurkish::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 446 of file translator_tr.h.
    { return "Deikenler"; }
trVariables() [2/2]
virtual QCString TranslatorTurkish::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 446 of file translator_tr.h.
    { return "Deikenler"; }
trVersion() [1/2]
virtual QCString TranslatorTurkish::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 522 of file translator_tr.h.
    { return "Srm"; }
trVersion() [2/2]
virtual QCString TranslatorTurkish::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 522 of file translator_tr.h.
    { return "Srm"; }
trWarning() [1/2]
virtual QCString TranslatorTurkish::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 518 of file translator_tr.h.
    { return "Uyar"; }
trWarning() [2/2]
virtual QCString TranslatorTurkish::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 518 of file translator_tr.h.
    { return "Uyar"; }
trWriteList() [1/2]
virtual QCString TranslatorTurkish::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 648 of file translator_tr.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" ve ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorTurkish::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 648 of file translator_tr.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" ve ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_tr.h
doxygen/src/translator_tr.h