DirRelation Class Reference
#include <dirdef.h>
Public Member Functions
DirRelation (const QCString &name, const DirDef *src, UsedDir *dst)
const DirDef * source () const
UsedDir * destination () const
void writeDocumentation (OutputList &ol)
QCString getOutputFileBase () const
DirRelation (const QCString &name, const DirDef *src, UsedDir *dst)
const DirDef * source () const
UsedDir * destination () const
void writeDocumentation (OutputList &ol)
QCString getOutputFileBase () const
Private Attributes
QCString m_name
const DirDef * m_src
UsedDir * m_dst
Detailed Description
A usage relation between two directories.
Definition at line 157 of file dirdef.h.
Constructor & Destructor Documentation
DirRelation() [1/2]
DirRelation::DirRelation (const QCString & name, const DirDef * src, UsedDir * dst) [inline]
Definition at line 160 of file dirdef.h.
      : m_name(name), m_src(src), m_dst(dst) {}
DirRelation() [2/2]
DirRelation::DirRelation (const QCString & name, const DirDef * src, UsedDir * dst) [inline]
Definition at line 160 of file dirdef.h.
      : m_name(name), m_src(src), m_dst(dst) {}
Member Function Documentation
destination() [1/2]
UsedDir * DirRelation::destination () const [inline]
Definition at line 163 of file dirdef.h.
{ return m_dst; }
References m_dst.
destination() [2/2]
UsedDir * DirRelation::destination () const [inline]
Definition at line 163 of file dirdef.h.
{ return m_dst; }
References m_dst.
getOutputFileBase() [1/2]
QCString DirRelation::getOutputFileBase () const [inline]
Definition at line 165 of file dirdef.h.
{ return m_name; }
References m_name.
Referenced by writeDocumentation().
getOutputFileBase() [2/2]
QCString DirRelation::getOutputFileBase () const [inline]
Definition at line 165 of file dirdef.h.
{ return m_name; }
References m_name.
source() [1/2]
const DirDef * DirRelation::source () const [inline]
Definition at line 162 of file dirdef.h.
{ return m_src; }
References m_src.
source() [2/2]
const DirDef * DirRelation::source () const [inline]
Definition at line 162 of file dirdef.h.
{ return m_src; }
References m_src.
writeDocumentation() [1/2]
void DirRelation::writeDocumentation (OutputList & ol)
Definition at line 882 of file dirdef.cpp.
{
  bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
  ol.pushGeneratorState();
  ol.disableAllBut(OutputGenerator::Html);
  QCString shortTitle=theTranslator->trDirRelation(
                      (m_src->shortName()+" &rarr; "+m_dst->dir()->shortName()));
  QCString title=theTranslator->trDirRelation(
                 (m_src->displayName()+" -> "+m_dst->dir()->shortName()));
  startFile(ol,getOutputFileBase(),getOutputFileBase(),
            title,HLI_None,!generateTreeView,m_src->getOutputFileBase());
  if (!generateTreeView)
  {
    // write navigation path
    m_src->writeNavigationPath(ol);
    ol.endQuickIndices();
  }
  ol.startContents();
  ol.writeString("<h3>"+shortTitle+"</h3>");
  ol.writeString("<table class=\"dirtab\">");
  ol.writeString("<tr class=\"dirtab\">");
  ol.writeString("<th class=\"dirtab\">");
  ol.parseText(theTranslator->trFileIn(m_src->pathFragment()));
  ol.writeString("</th>");
  ol.writeString("<th class=\"dirtab\">");
  ol.parseText(theTranslator->trIncludesFileIn(m_dst->dir()->pathFragment()));
  ol.writeString("</th>");
  ol.writeString("</tr>");
  for (const auto &fp : m_dst->filePairs())
  {
    ol.writeString("<tr class=\"dirtab\">");
    ol.writeString("<td class=\"dirtab\">");
    writePartialFilePath(ol,m_src,fp->source());
    ol.writeString("</td>");
    ol.writeString("<td class=\"dirtab\">");
    writePartialFilePath(ol,m_dst->dir(),fp->destination());
    ol.writeString("</td>");
    ol.writeString("</tr>");
  }
  ol.writeString("</table>");
  ol.endContents();
  endFileWithNavPath(m_src,ol);
  ol.popGeneratorState();
}
References Config_getBool, UsedDir::dir(), OutputList::disableAllBut(), DirDef::displayName(), OutputList::endContents(), endFileWithNavPath(), OutputList::endQuickIndices(), UsedDir::filePairs(), getOutputFileBase(), DirDef::getOutputFileBase(), HLI_None, OutputGenerator::Html, m_dst, m_src, OutputList::parseText(), Definition::pathFragment(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), DirDef::shortName(), OutputList::startContents(), startFile(), theTranslator, Translator::trDirRelation(), Translator::trFileIn(), Translator::trIncludesFileIn(), DefinitionMutable::writeNavigationPath(), writePartialFilePath(), and OutputList::writeString().
writeDocumentation() [2/2]
void DirRelation::writeDocumentation (OutputList & ol)
Member Data Documentation
m_dst
UsedDir * DirRelation::m_dst [private]
Definition at line 170 of file dirdef.h.
Referenced by destination(), and writeDocumentation().
m_name
QCString DirRelation::m_name [private]
Definition at line 168 of file dirdef.h.
Referenced by getOutputFileBase().
m_src
const DirDef * DirRelation::m_src [private]
Definition at line 169 of file dirdef.h.
Referenced by source(), and writeDocumentation().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/dirdef.h
doxygen/src/dirdef.h
doxygen/build/doxygen/src/dirdef.cpp
doxygen/src/dirdef.cpp