TemplateEscapeIntf Class Reference
Interface used to escape characters in a string.
#include <template.h>
Public Member Functions
virtual ~TemplateEscapeIntf ()=default
virtual std::unique_ptr< TemplateEscapeIntf > clone ()=0
virtual QCString escape (const QCString &input)=0
virtual void enableTabbing (bool b)=0
virtual ~TemplateEscapeIntf ()=default
virtual std::unique_ptr< TemplateEscapeIntf > clone ()=0
virtual QCString escape (const QCString &input)=0
virtual void enableTabbing (bool b)=0
Detailed Description
Interface used to escape characters in a string.
Definition at line 396 of file template.h.
Constructor & Destructor Documentation
 TemplateEscapeIntf() [1/2]
virtual TemplateEscapeIntf::~TemplateEscapeIntf () [virtual], [default]
 TemplateEscapeIntf() [2/2]
virtual TemplateEscapeIntf::~TemplateEscapeIntf () [virtual], [default]
Member Function Documentation
clone() [1/2]
virtual std::unique_ptr< TemplateEscapeIntf > TemplateEscapeIntf::clone () [pure virtual]
Create a copy of the escape filter
Implemented in HtmlEscaper, LatexEscaper, HtmlEscaper, and LatexEscaper.
clone() [2/2]
virtual std::unique_ptr< TemplateEscapeIntf > TemplateEscapeIntf::clone () [pure virtual]
Create a copy of the escape filter
Implemented in HtmlEscaper, LatexEscaper, HtmlEscaper, and LatexEscaper.
enableTabbing() [1/2]
virtual void TemplateEscapeIntf::enableTabbing (bool b) [pure virtual]
Setting tabbing mode on or off (for LaTeX)
Implemented in LatexEscaper, LatexEscaper, HtmlEscaper, and HtmlEscaper.
Referenced by TemplateContextImpl::enableTabbing().
enableTabbing() [2/2]
virtual void TemplateEscapeIntf::enableTabbing (bool b) [pure virtual]
Setting tabbing mode on or off (for LaTeX)
Implemented in LatexEscaper, LatexEscaper, HtmlEscaper, and HtmlEscaper.
escape() [1/2]
virtual QCString TemplateEscapeIntf::escape (const QCString & input) [pure virtual]
Returns the input after escaping certain characters
Implemented in HtmlEscaper, LatexEscaper, HtmlEscaper, and LatexEscaper.
Referenced by TemplateNodeVariable::render(), and TemplateNodeCycle::render().
escape() [2/2]
virtual QCString TemplateEscapeIntf::escape (const QCString & input) [pure virtual]
Returns the input after escaping certain characters
Implemented in HtmlEscaper, LatexEscaper, HtmlEscaper, and LatexEscaper.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.h
doxygen/src/template.h