MarkdownOutlineParser Class Reference
#include <markdown.h>
Classes
struct Private
Public Member Functions
MarkdownOutlineParser ()
virtual ~MarkdownOutlineParser ()
void parseInput (const QCString &fileName, const char *fileBuf, const std::shared_ptr< Entry > &root, ClangTUParser *clangParser)
bool needsPreprocessing (const QCString &) const
void parsePrototype (const QCString &text)
MarkdownOutlineParser ()
virtual ~MarkdownOutlineParser ()
void parseInput (const QCString &fileName, const char *fileBuf, const std::shared_ptr< Entry > &root, ClangTUParser *clangParser)
bool needsPreprocessing (const QCString &) const
void parsePrototype (const QCString &text)
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Definition at line 93 of file markdown.h.
Constructor & Destructor Documentation
MarkdownOutlineParser() [1/2]
MarkdownOutlineParser::MarkdownOutlineParser ()
Definition at line 3489 of file markdown.cpp.
                                             : p(std::make_unique<Private>())
{
}
 MarkdownOutlineParser() [1/2]
MarkdownOutlineParser::~MarkdownOutlineParser () [virtual]
Definition at line 3493 of file markdown.cpp.
{
}
MarkdownOutlineParser() [2/2]
MarkdownOutlineParser::MarkdownOutlineParser ()
 MarkdownOutlineParser() [2/2]
virtual MarkdownOutlineParser::~MarkdownOutlineParser () [virtual]
Member Function Documentation
needsPreprocessing() [1/2]
bool MarkdownOutlineParser::needsPreprocessing (const QCString & extension) const [inline], [virtual]
Returns TRUE if the language identified by extension needs the C preprocessor to be run before feed the result to the input parser.
See also
parseInput()
Implements OutlineParserInterface.
Definition at line 102 of file markdown.h.
{ return FALSE; }
References FALSE.
needsPreprocessing() [2/2]
bool MarkdownOutlineParser::needsPreprocessing (const QCString & extension) const [inline], [virtual]
Returns TRUE if the language identified by extension needs the C preprocessor to be run before feed the result to the input parser.
See also
parseInput()
Implements OutlineParserInterface.
Definition at line 102 of file markdown.h.
{ return FALSE; }
References FALSE.
parseInput() [1/2]
void MarkdownOutlineParser::parseInput (const QCString & fileName, const char * fileBuf, const std::shared_ptr< Entry > & root, ClangTUParser * clangParser) [virtual]
Parses a single input file with the goal to build an Entry tree.
Parameters
 in fileName The full name of the file.
 in fileBuf The contents of the file (zero terminated).
 in,out root The root of the tree of Entry *nodes representing the information extracted from the file.
 in clangParser The clang translation unit parser object or nullptr if disabled.
Implements OutlineParserInterface.
Definition at line 3497 of file markdown.cpp.
{
  std::shared_ptr<Entry> current = std::make_shared<Entry>();
  int prepend = 0; // number of empty lines in front
  current->lang = SrcLangExt_Markdown;
  current->fileName = fileName;
  current->docFile = fileName;
  current->docLine = 1;
  QCString docs = fileBuf;
  Debug::print(Debug::Markdown,0,"======== Markdown =========\n---- input ------- \n%s\n",qPrint(fileBuf));
  QCString id;
  Markdown markdown(fileName,1,0);
  QCString title=markdown.extractPageTitle(docs,id,prepend).stripWhiteSpace();
  if (id.startsWith("autotoc_md")) id = "";
  int indentLevel=title.isEmpty() ? 0 : -1;
  markdown.setIndentLevel(indentLevel);
  QCString fn = FileInfo(fileName.str()).fileName();
  QCString titleFn = stripExtensionGeneral(fn,getFileNameExtension(fn));
  QCString mdfileAsMainPage = Config_getString(USE_MDFILE_AS_MAINPAGE);
  bool wasEmpty = id.isEmpty();
  if (wasEmpty) id = markdownFileNameToId(fileName);
  switch (isExplicitPage(docs))
  {
    case ExplicitPageResult::notExplicit:
      if (!mdfileAsMainPage.isEmpty() &&
          (fn==mdfileAsMainPage || // name reference
           FileInfo(fileName.str()).absFilePath()==
           FileInfo(mdfileAsMainPage.str()).absFilePath()) // file reference with path
         )
      {
        docs.prepend("@anchor " + id + "\\ilinebr ");
        docs.prepend("@mainpage "+title+"\\ilinebr ");
      }
      else if (id=="mainpage" || id=="index")
      {
        if (title.isEmpty()) title = titleFn;
        docs.prepend("@anchor " + id + "\\ilinebr ");
        docs.prepend("@mainpage "+title+"\\ilinebr ");
      }
      else
      {
        if (title.isEmpty()) {title = titleFn;prepend=0;}
        if (!wasEmpty) docs.prepend("@anchor " + markdownFileNameToId(fileName) + "\\ilinebr ");
        docs.prepend("@page "+id+" "+title+"\\ilinebr ");
      }
      for (int i = 0; i < prepend; i++) docs.prepend("\n");
      break;
    case ExplicitPageResult::explicitPage:
      {
        // look for `@page label My Title\n` and capture `label` (match[1]) and ` My Title` (match[2])
        static const reg::Ex re(R"([\\@]page\s+(\a[\w-]*)(\s*[^\n]*)\n)");
        reg::Match match;
        std::string s = docs.str();
        if (reg::search(s,match,re))
        {
          QCString orgLabel = match[1].str();
          QCString newLabel = markdownFileNameToId(fileName);
          docs = docs.left(match[1].position())+ // part before label
                 newLabel+ // new label
                 match[2].str()+ // part between orgLabel and \n
                 "\\ilinebr @anchor "+orgLabel+"\n"+ // add original anchor plus \n of above
                 docs.right(docs.length()-match.length()); // add remainder of docs
        }
      }
      break;
    case ExplicitPageResult::explicitMainPage:
      break;
  }
  int lineNr=1;
  p->commentScanner.enterFile(fileName,lineNr);
  Protection prot=Public;
  bool needsEntry = FALSE;
  int position=0;
  QCString processedDocs = markdown.process(docs,lineNr,true);
  while (p->commentScanner.parseCommentBlock(
        this,
        current.get(),
        processedDocs,
        fileName,
        lineNr,
        FALSE, // isBrief
        FALSE, // javadoc autobrief
        FALSE, // inBodyDocs
        prot, // protection
        position,
        needsEntry,
        true))
  {
    if (needsEntry)
    {
      QCString docFile = current->docFile;
      root->moveToSubEntryAndRefresh(current);
      current->lang = SrcLangExt_Markdown;
      current->docFile = docFile;
      current->docLine = lineNr;
    }
  }
  if (needsEntry)
  {
    root->moveToSubEntryAndKeep(current);
  }
  p->commentScanner.leaveFile(fileName,lineNr);
}
References FileInfo::absFilePath(), Config_getString, explicitMainPage, explicitPage, Markdown::extractPageTitle(), FALSE, FileInfo::fileName(), getFileNameExtension(), id, QCString::isEmpty(), isExplicitPage(), QCString::left(), QCString::length(), Debug::Markdown, markdownFileNameToId(), reg::match(), notExplicit, p, QCString::prepend(), Debug::print(), Markdown::process(), Public, qPrint(), QCString::right(), s, reg::search(), Markdown::setIndentLevel(), SrcLangExt_Markdown, ghc::filesystem::detail::startsWith(), QCString::str(), string, stripExtensionGeneral(), and QCString::stripWhiteSpace().
parseInput() [2/2]
void MarkdownOutlineParser::parseInput (const QCString & fileName, const char * fileBuf, const std::shared_ptr< Entry > & root, ClangTUParser * clangParser) [virtual]
Parses a single input file with the goal to build an Entry tree.
Parameters
 in fileName The full name of the file.
 in fileBuf The contents of the file (zero terminated).
 in,out root The root of the tree of Entry *nodes representing the information extracted from the file.
 in clangParser The clang translation unit parser object or nullptr if disabled.
Implements OutlineParserInterface.
parsePrototype() [1/2]
void MarkdownOutlineParser::parsePrototype (const QCString & text) [virtual]
Callback function called by the comment block scanner. It provides a string text containing the prototype of a function or variable. The parser should parse this and store the information in the Entry node that corresponds with the node for which the comment block parser was invoked.
Implements OutlineParserInterface.
Definition at line 3605 of file markdown.cpp.
{
  Doxygen::parserManager->getOutlineParser("*.cpp")->parsePrototype(text);
}
References ParserManager::getOutlineParser(), and Doxygen::parserManager.
parsePrototype() [2/2]
void MarkdownOutlineParser::parsePrototype (const QCString & text) [virtual]
Callback function called by the comment block scanner. It provides a string text containing the prototype of a function or variable. The parser should parse this and store the information in the Entry node that corresponds with the node for which the comment block parser was invoked.
Implements OutlineParserInterface.
Member Data Documentation
p
std::unique_ptr< Private > MarkdownOutlineParser::p [private]
Definition at line 106 of file markdown.h.
Referenced by parseInput().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/markdown.h
doxygen/src/markdown.h
doxygen/build/doxygen/src/markdown.cpp
doxygen/src/markdown.cpp