MemberList Class Reference
#include <memberlist.h>
Public Member Functions
MemberList (MemberListType lt, MemberListContainer container)
~MemberList ()
MemberListType listType () const
MemberListContainer container () const
int numDecMembers () const
int numDecEnumValues () const
int numDocMembers () const
int numDocEnumValues () const
bool needsSorting () const
void countDecMembers ()
void countDocMembers ()
int countInheritableMembers (const ClassDef *inheritedFrom) const
void writePlainDeclarations (OutputList &ol, bool inGroup, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd, int indentLevel, const ClassDef *inheritedFrom, const QCString &inheritId) const
void writeDeclarations (OutputList &ol, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd, const QCString &title, const QCString &subtitle, bool showEnumValues=FALSE, bool showInline=FALSE, const ClassDef *inheritedFrom=0, MemberListType lt=MemberListType_pubMethods) const
void writeDocumentation (OutputList &ol, const QCString &scopeName, const Definition *container, const QCString &title, bool showEnumValues=FALSE, bool showInline=FALSE) const
void writeSimpleDocumentation (OutputList &ol, const Definition *container) const
void writeDocumentationPage (OutputList &ol, const QCString &scopeName, const DefinitionMutable *container) const
void writeTagFile (TextStream &, bool useQualifiedName=false)
bool declVisible () const
void addMemberGroup (MemberGroup *mg)
void addListReferences (Definition *def)
void findSectionsInDocumentation (const Definition *d)
void setNeedsSorting (bool b)
const MemberGroupRefList & getMemberGroupList () const
void setAnonymousEnumType ()
void setAnchors ()
MemberList (MemberListType lt, MemberListContainer container)
~MemberList ()
MemberListType listType () const
MemberListContainer container () const
int numDecMembers () const
int numDecEnumValues () const
int numDocMembers () const
int numDocEnumValues () const
bool needsSorting () const
void countDecMembers ()
void countDocMembers ()
int countInheritableMembers (const ClassDef *inheritedFrom) const
void writePlainDeclarations (OutputList &ol, bool inGroup, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd, int indentLevel, const ClassDef *inheritedFrom, const QCString &inheritId) const
void writeDeclarations (OutputList &ol, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd, const QCString &title, const QCString &subtitle, bool showEnumValues=FALSE, bool showInline=FALSE, const ClassDef *inheritedFrom=0, MemberListType lt=MemberListType_pubMethods) const
void writeDocumentation (OutputList &ol, const QCString &scopeName, const Definition *container, const QCString &title, bool showEnumValues=FALSE, bool showInline=FALSE) const
void writeSimpleDocumentation (OutputList &ol, const Definition *container) const
void writeDocumentationPage (OutputList &ol, const QCString &scopeName, const DefinitionMutable *container) const
void writeTagFile (TextStream &, bool useQualifiedName=false)
bool declVisible () const
void addMemberGroup (MemberGroup *mg)
void addListReferences (Definition *def)
void findSectionsInDocumentation (const Definition *d)
void setNeedsSorting (bool b)
const MemberGroupRefList & getMemberGroupList () const
void setAnonymousEnumType ()
void setAnchors ()
Static Public Member Functions
static QCString listTypeAsString (MemberListType type)
static QCString listTypeAsString (MemberListType type)
Private Member Functions
int countEnumValues (const MemberDef *md) const
int countEnumValues (const MemberDef *md) const
Private Attributes
int m_numDecMembers
int m_numDecEnumValues
int m_numDocMembers
int m_numDocEnumValues
MemberGroupRefList m_memberGroupRefList
MemberListContainer m_container
MemberListType m_listType
bool m_needsSorting
Additional Inherited Members
Detailed Description
A list of MemberDef objects as shown in documentation sections.
Definition at line 81 of file memberlist.h.
Constructor & Destructor Documentation
MemberList() [1/2]
MemberList::MemberList (MemberListType lt, MemberListContainer container)
Definition at line 33 of file memberlist.cpp.
                                                                : m_container(con), m_listType(lt)
{
  //printf("%p: MemberList::MemberList(%d)\n",this,lt);
  m_numDecMembers=-1; // special value indicating that value needs to be computed
  m_numDecEnumValues=0;
  m_numDocMembers=-1; // special value indicating that value needs to be computed
  m_numDocEnumValues=0;
  m_needsSorting=FALSE;
}
References FALSE, m_needsSorting, m_numDecEnumValues, m_numDecMembers, m_numDocEnumValues, and m_numDocMembers.
 MemberList() [1/2]
MemberList::~MemberList ()
Definition at line 43 of file memberlist.cpp.
{
}
MemberList() [2/2]
MemberList::MemberList (MemberListType lt, MemberListContainer container)
 MemberList() [2/2]
MemberList::~MemberList ()
Member Function Documentation
addListReferences() [1/2]
void MemberList::addListReferences (Definition * def)
Definition at line 831 of file memberlist.cpp.
{
  for (const auto &imd : m_members)
  {
    MemberDefMutable *md = toMemberDefMutable(imd);
    if (md && !md->isAlias() && (md->getGroupDef()==0 || def->definitionType()==Definition::TypeGroup))
    {
      md->addListReference(def);
      const MemberVector &enumFields = md->enumFieldList();
      if (md->memberType()==MemberType_Enumeration && !enumFields.empty())
      {
        //printf(" Adding enum values!\n");
        for (const auto &vmd : enumFields)
        {
          MemberDefMutable *vmdm = toMemberDefMutable(vmd);
          if (vmdm)
          {
            //printf(" adding %s\n",qPrint(vmd->name()));
            vmdm->addListReference(def);
          }
        }
      }
    }
  }
  for (const auto &mg : m_memberGroupRefList)
  {
    mg->addListReferences(def);
  }
}
References MemberDefMutable::addListReference(), Definition::definitionType(), MemberVector::empty(), MemberDef::enumFieldList(), MemberDef::getGroupDef(), Definition::isAlias(), m_memberGroupRefList, MemberVector::m_members, MemberDef::memberType(), MemberType_Enumeration, toMemberDefMutable(), and Definition::TypeGroup.
addListReferences() [2/2]
void MemberList::addListReferences (Definition * def)
addMemberGroup() [1/2]
void MemberList::addMemberGroup (MemberGroup * mg)
Definition at line 826 of file memberlist.cpp.
{
  m_memberGroupRefList.push_back(mg);
}
References m_memberGroupRefList.
Referenced by MemberGroup::addToDeclarationSection().
addMemberGroup() [2/2]
void MemberList::addMemberGroup (MemberGroup * mg)
container() [1/2]
MemberListContainer MemberList::container () const [inline]
Definition at line 88 of file memberlist.h.
{ return m_container; }
References m_container.
Referenced by doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), addMembersToMemberGroup(), writeDocumentation(), writeDocumentationPage(), and writeSimpleDocumentation().
container() [2/2]
MemberListContainer MemberList::container () const [inline]
Definition at line 88 of file memberlist.h.
{ return m_container; }
References m_container.
Referenced by doxmlparser.compound.MemberSpec_::__init__(), and doxmlparser.index.MemberSpec_::__init__().
countDecMembers() [1/2]
void MemberList::countDecMembers ()
Count the number of members in this list that are visible in the declaration part of a compound's documentation page.
Definition at line 116 of file memberlist.cpp.
{
  if (m_numDecMembers!=-1) return;
  //printf("----- countDecMembers count=%d ----\n",count());
  /*
  m_varCnt=m_funcCnt=m_enumCnt=m_enumValCnt=0;
  m_typeCnt=m_seqCnt=m_dictCnt=m_protoCnt=m_defCnt=m_friendCnt=0;
  */
  m_numDecMembers=0;
  for (const auto &md : m_members)
  {
    //printf("MemberList::countDecMembers(md=%s,%d)\n",qPrint(md->name()),md->isBriefSectionVisible());
    if (md->isBriefSectionVisible())
    {
      switch(md->memberType())
      {
        case MemberType_Variable: // fall through
        case MemberType_Event: // fall through
        case MemberType_Property: /*m_varCnt++,*/
                                     m_numDecMembers++;
                                     break;
// apparently necessary to get this to show up in declarations section?
        case MemberType_Interface: // fall through
        case MemberType_Service: // fall through
        case MemberType_Function: // fall through
        case MemberType_Signal: // fall through
        case MemberType_DCOP: // fall through
        case MemberType_Slot: if (!md->isRelated() || md->getClassDef())
                                       /*m_funcCnt++,*/
                                       m_numDecMembers++;
                                     break;
        case MemberType_Enumeration: /*m_enumCnt++,*/
                                     m_numDecMembers++;
                                     break;
        case MemberType_EnumValue: m_numDecEnumValues++;
                                     m_numDecMembers++;
                                     break;
        case MemberType_Typedef: /*m_typeCnt++,*/
                                     m_numDecMembers++;
                                     break;
        case MemberType_Sequence: /*m_seqCnt++,*/
                                     m_numDecMembers++;
                                     break;
        case MemberType_Dictionary: /*m_dictCnt++,*/
                                     m_numDecMembers++;
                                     break;
        //case MemberType_Prototype: m_protoCnt++,m_numDecMembers++; break;
        case MemberType_Define: if (Config_getBool(EXTRACT_ALL) ||
                                         !md->argsString().isEmpty() ||
                                         !md->initializer().isEmpty() ||
                                         md->hasDocumentation()
                                        ) /*m_defCnt++,*/ m_numDecMembers++;
                                     break;
        case MemberType_Friend: /*m_friendCnt++,*/
                                     m_numDecMembers++;
                                     break;
        default:
          err("Unknown member type found for member '%s'\n!",qPrint(md->name()));
      }
    }
  }
  for (const auto &mg : m_memberGroupRefList)
  {
    mg->countDecMembers();
    /*
    m_varCnt+=mg->varCount();
    m_funcCnt+=mg->funcCount();
    m_enumCnt+=mg->enumCount();
    m_enumValCnt+=mg->enumValueCount();
    m_typeCnt+=mg->typedefCount();
    m_seqCnt+=mg->sequenceCount();
    m_dictCnt+=mg->dictionaryCount();
    m_protoCnt+=mg->protoCount();
    m_defCnt+=mg->defineCount();
    m_friendCnt+=mg->friendCount();
    */
    m_numDecMembers+=mg->numDecMembers();
    m_numDecEnumValues+=mg->numDecEnumValues();
  }
  //printf("----- end countDecMembers ----\n");
  //printf("MemberList::countDecMembers()=%d\n",m_numDecMembers);
}
References Config_getBool, err(), m_memberGroupRefList, MemberVector::m_members, m_numDecEnumValues, m_numDecMembers, MemberType_DCOP, MemberType_Define, MemberType_Dictionary, MemberType_Enumeration, MemberType_EnumValue, MemberType_Event, MemberType_Friend, MemberType_Function, MemberType_Interface, MemberType_Property, MemberType_Sequence, MemberType_Service, MemberType_Signal, MemberType_Slot, MemberType_Typedef, MemberType_Variable, and qPrint().
Referenced by MemberGroup::addGroupedInheritedMembers().
countDecMembers() [2/2]
void MemberList::countDecMembers ()
countDocMembers() [1/2]
void MemberList::countDocMembers ()
Definition at line 201 of file memberlist.cpp.
{
  if (m_numDocMembers!=-1) return; // used cached value
  m_numDocMembers=0;
  for (const auto &md : m_members)
  {
    if (md->isDetailedSectionVisible(m_container) && !md->isAlias())
    {
      // do not count enum values, since they do not produce entries of their own
      if (md->memberType()==MemberType_EnumValue)
      {
        m_numDocEnumValues++;
      }
      m_numDocMembers++;
    }
  }
  for (const auto &mg : m_memberGroupRefList)
  {
    mg->countDocMembers();
    m_numDocMembers+=mg->numDocMembers();
    m_numDocEnumValues+=mg->numDocEnumValues();
  }
  //printf("MemberList::countDocMembers()=%d memberGroupList=%p\n",m_numDocMembers,memberGroupList);
}
References m_container, m_memberGroupRefList, MemberVector::m_members, m_numDocEnumValues, m_numDocMembers, and MemberType_EnumValue.
countDocMembers() [2/2]
void MemberList::countDocMembers ()
countEnumValues() [1/2]
int MemberList::countEnumValues (const MemberDef * md) const [private]
Definition at line 259 of file memberlist.cpp.
{
  int numEnumValues=0;
  QCString name(md->name());
  int i=name.findRev("::");
  if (i!=-1) name=name.right(name.length()-i-2);
  if (name[0]=='@')
  {
    for (const auto &vmd : m_members)
    {
      QCString vtype=vmd->typeString();
      if ((vtype.find(name))!=-1)
      {
        numEnumValues++;
      }
    }
  }
  return numEnumValues;
}
References QCString::find(), MemberVector::m_members, setup::name, and Definition::name().
Referenced by declVisible(), and writePlainDeclarations().
countEnumValues() [2/2]
int MemberList::countEnumValues (const MemberDef * md) const [private]
countInheritableMembers() [1/2]
int MemberList::countInheritableMembers (const ClassDef * inheritedFrom) const
Definition at line 79 of file memberlist.cpp.
{
  int count=0;
  for (const auto &md : m_members)
  {
    if (md->isBriefSectionVisible())
    {
      if (md->memberType()!=MemberType_Friend &&
          md->memberType()!=MemberType_EnumValue)
      {
        //printf("member %s: isReimplementedBy(%s)=%d\n",qPrint(md->name()),
        // qPrint(inheritedFrom->name()),
        // md->isReimplementedBy(inheritedFrom));
        if (md->memberType()==MemberType_Function)
        {
          if (!md->isReimplementedBy(inheritedFrom)) count++;
        }
        else
        {
          count++;
        }
      }
    }
  }
  for (const auto &mg : m_memberGroupRefList)
  {
    count+=mg->countInheritableMembers(inheritedFrom);
  }
  //printf("%s::countInheritableMembers(%s)=%d\n",
  // qPrint(listTypeAsString()),
  // qPrint(inheritedFrom->name()),count);
  return count;
}
References m_memberGroupRefList, MemberVector::m_members, MemberType_EnumValue, MemberType_Friend, and MemberType_Function.
Referenced by ClassDefImpl::countMembersIncludingGrouped().
countInheritableMembers() [2/2]
int MemberList::countInheritableMembers (const ClassDef * inheritedFrom) const
declVisible() [1/2]
bool MemberList::declVisible () const
Definition at line 279 of file memberlist.cpp.
{
  for (const auto &md : m_members)
  {
    if (md->isBriefSectionVisible())
    {
      switch (md->memberType())
      {
        case MemberType_Define: // fall through
        case MemberType_Typedef: // fall through
        case MemberType_Variable: // fall through
        case MemberType_Function: // fall through
        case MemberType_Signal: // fall through
        case MemberType_Slot: // fall through
        case MemberType_DCOP: // fall through
        case MemberType_Property: // fall through
        case MemberType_Interface: // fall through
        case MemberType_Service: // fall through
        case MemberType_Sequence: // fall through
        case MemberType_Dictionary: // fall through
        case MemberType_Event:
          return TRUE;
        case MemberType_Enumeration:
          {
            // if this is an anonymous enum and there are variables of this
            // enum type (i.e. enumVars>0), then we do not show the enum here.
            if (countEnumValues(md)==0) // show enum here
            {
              return TRUE;
            }
          }
          break;
        case MemberType_Friend:
          return TRUE;
        case MemberType_EnumValue:
          {
            if (m_container==MemberListContainer::Group)
            {
              return TRUE;
            }
          }
          break;
      }
    }
  }
  return FALSE;
}
References countEnumValues(), FALSE, Group, m_container, MemberVector::m_members, MemberType_DCOP, MemberType_Define, MemberType_Dictionary, MemberType_Enumeration, MemberType_EnumValue, MemberType_Event, MemberType_Friend, MemberType_Function, MemberType_Interface, MemberType_Property, MemberType_Sequence, MemberType_Service, MemberType_Signal, MemberType_Slot, MemberType_Typedef, MemberType_Variable, and TRUE.
Referenced by ClassDefImpl::writeSummaryLinks(), FileDefImpl::writeSummaryLinks(), GroupDefImpl::writeSummaryLinks(), and NamespaceDefImpl::writeSummaryLinks().
declVisible() [2/2]
bool MemberList::declVisible () const
findSectionsInDocumentation() [1/2]
void MemberList::findSectionsInDocumentation (const Definition * d)
Definition at line 861 of file memberlist.cpp.
{
  for (const auto &imd : m_members)
  {
    MemberDefMutable *md = toMemberDefMutable(imd);
    if (md)
    {
      md->findSectionsInDocumentation();
    }
  }
  for (const auto &mg : m_memberGroupRefList)
  {
    mg->findSectionsInDocumentation(d);
  }
}
References MemberDefMutable::findSectionsInDocumentation(), m_memberGroupRefList, MemberVector::m_members, and toMemberDefMutable().
findSectionsInDocumentation() [2/2]
void MemberList::findSectionsInDocumentation (const Definition * d)
getMemberGroupList() [1/2]
const MemberGroupRefList & MemberList::getMemberGroupList () const [inline]
Definition at line 118 of file memberlist.h.
{ return m_memberGroupRefList; }
References m_memberGroupRefList.
Referenced by InheritedMemberInfoListContext::Private::addMemberListIncludingGrouped(), MemberListInfoContext::Private::createMemberGroups(), membersHaveSpecificType(), and VhdlDocGen::writeVHDLDeclarations().
getMemberGroupList() [2/2]
const MemberGroupRefList & MemberList::getMemberGroupList () const [inline]
Definition at line 118 of file memberlist.h.
{ return m_memberGroupRefList; }
References m_memberGroupRefList.
listType() [1/2]
MemberListType MemberList::listType () const [inline]
Definition at line 86 of file memberlist.h.
{ return m_listType; }
References m_listType.
Referenced by MemberGroup::addGroupedInheritedMembers(), MemberListInfoContext::Private::anchor(), MemberGroup::countGroupedInheritedMembers(), MemberListInfoContext::Private::createInherited(), generateXMLForClass(), generateXMLForFile(), generateXMLForGroup(), generateXMLForNamespace(), MemberListContext::MemberListContext(), ClassDefImpl::writeSummaryLinks(), FileDefImpl::writeSummaryLinks(), GroupDefImpl::writeSummaryLinks(), and NamespaceDefImpl::writeSummaryLinks().
listType() [2/2]
MemberListType MemberList::listType () const [inline]
Definition at line 86 of file memberlist.h.
{ return m_listType; }
References m_listType.
listTypeAsString() [1/2]
QCString MemberList::listTypeAsString (MemberListType type) [static]
Definition at line 882 of file memberlist.cpp.
{
  switch(type)
  {
    case MemberListType_pubMethods: return "pub-methods";
    case MemberListType_proMethods: return "pro-methods";
    case MemberListType_pacMethods: return "pac-methods";
    case MemberListType_priMethods: return "pri-methods";
    case MemberListType_pubStaticMethods: return "pub-static-methods";
    case MemberListType_proStaticMethods: return "pro-static-methods";
    case MemberListType_pacStaticMethods: return "pac-static-methods";
    case MemberListType_priStaticMethods: return "pri-static-methods";
    case MemberListType_pubSlots: return "pub-slots";
    case MemberListType_proSlots: return "pro-slots";
    case MemberListType_priSlots: return "pri-slots";
    case MemberListType_pubAttribs: return "pub-attribs";
    case MemberListType_proAttribs: return "pro-attribs";
    case MemberListType_pacAttribs: return "pac-attribs";
    case MemberListType_priAttribs: return "pri-attribs";
    case MemberListType_pubStaticAttribs: return "pub-static-attribs";
    case MemberListType_proStaticAttribs: return "pro-static-attribs";
    case MemberListType_pacStaticAttribs: return "pac-static-attribs";
    case MemberListType_priStaticAttribs: return "pri-static-attribs";
    case MemberListType_pubTypes: return "pub-types";
    case MemberListType_proTypes: return "pro-types";
    case MemberListType_pacTypes: return "pac-types";
    case MemberListType_priTypes: return "pri-types";
    case MemberListType_related: return "related";
    case MemberListType_signals: return "signals";
    case MemberListType_friends: return "friends";
    case MemberListType_dcopMethods: return "dcop-methods";
    case MemberListType_properties: return "properties";
    case MemberListType_events: return "events";
    case MemberListType_interfaces: return "interfaces";
    case MemberListType_services: return "services";
    case MemberListType_decDefineMembers: return "define-members";
    case MemberListType_decProtoMembers: return "proto-members";
    case MemberListType_decTypedefMembers: return "typedef-members";
    case MemberListType_decSequenceMembers: return "sequence-members";
    case MemberListType_decDictionaryMembers: return "dictionary-members";
    case MemberListType_decEnumMembers: return "enum-members";
    case MemberListType_decFuncMembers: return "func-members";
    case MemberListType_decVarMembers: return "var-members";
    case MemberListType_decEnumValMembers: return "enumval-members";
    case MemberListType_decPubSlotMembers: return "pub-slot-members";
    case MemberListType_decProSlotMembers: return "pro-slot-members";
    case MemberListType_decPriSlotMembers: return "pri-slot-members";
    case MemberListType_decSignalMembers: return "signal-members";
    case MemberListType_decEventMembers: return "event-members";
    case MemberListType_decFriendMembers: return "friend-members";
    case MemberListType_decPropMembers: return "prop-members";
    case MemberListType_enumFields: return "enum-fields";
    case MemberListType_memberGroup: break;
    default: break;
  }
  return "";
}
References MemberListType_dcopMethods, MemberListType_decDefineMembers, MemberListType_decDictionaryMembers, MemberListType_decEnumMembers, MemberListType_decEnumValMembers, MemberListType_decEventMembers, MemberListType_decFriendMembers, MemberListType_decFuncMembers, MemberListType_decPriSlotMembers, MemberListType_decPropMembers, MemberListType_decProSlotMembers, MemberListType_decProtoMembers, MemberListType_decPubSlotMembers, MemberListType_decSequenceMembers, MemberListType_decSignalMembers, MemberListType_decTypedefMembers, MemberListType_decVarMembers, MemberListType_enumFields, MemberListType_events, MemberListType_friends, MemberListType_interfaces, MemberListType_memberGroup, MemberListType_pacAttribs, MemberListType_pacMethods, MemberListType_pacStaticAttribs, MemberListType_pacStaticMethods, MemberListType_pacTypes, MemberListType_priAttribs, MemberListType_priMethods, MemberListType_priSlots, MemberListType_priStaticAttribs, MemberListType_priStaticMethods, MemberListType_priTypes, MemberListType_proAttribs, MemberListType_proMethods, MemberListType_properties, MemberListType_proSlots, MemberListType_proStaticAttribs, MemberListType_proStaticMethods, MemberListType_proTypes, MemberListType_pubAttribs, MemberListType_pubMethods, MemberListType_pubSlots, MemberListType_pubStaticAttribs, MemberListType_pubStaticMethods, MemberListType_pubTypes, MemberListType_related, MemberListType_services, and MemberListType_signals.
Referenced by MemberListInfoContext::Private::anchor(), InheritedMemberInfoContext::Private::id(), writeDeclarations(), ClassDefImpl::writeSummaryLinks(), FileDefImpl::writeSummaryLinks(), GroupDefImpl::writeSummaryLinks(), and NamespaceDefImpl::writeSummaryLinks().
listTypeAsString() [2/2]
static QCString MemberList::listTypeAsString (MemberListType type) [static]
needsSorting() [1/2]
bool MemberList::needsSorting () const [inline]
Definition at line 94 of file memberlist.h.
{ return m_needsSorting; }
References m_needsSorting.
Referenced by FileDefImpl::sortMemberLists().
needsSorting() [2/2]
bool MemberList::needsSorting () const [inline]
Definition at line 94 of file memberlist.h.
{ return m_needsSorting; }
References m_needsSorting.
numDecEnumValues() [1/2]
int MemberList::numDecEnumValues () const [inline]
Definition at line 91 of file memberlist.h.
{ return m_numDecEnumValues; }
References m_numDecEnumValues.
Referenced by writeDeclarations(), and writePlainDeclarations().
numDecEnumValues() [2/2]
int MemberList::numDecEnumValues () const [inline]
Definition at line 91 of file memberlist.h.
{ return m_numDecEnumValues; }
References m_numDecEnumValues.
numDecMembers() [1/2]
int MemberList::numDecMembers () const [inline]
Definition at line 90 of file memberlist.h.
{ ASSERT(m_numDecMembers!=-1); return m_numDecMembers; }
References ASSERT, and m_numDecMembers.
Referenced by ClassDefImpl::countMemberDeclarations(), FileDefImpl::numDecMembers(), writeDeclarations(), and writePlainDeclarations().
numDecMembers() [2/2]
int MemberList::numDecMembers () const [inline]
Definition at line 90 of file memberlist.h.
{ ASSERT(m_numDecMembers!=-1); return m_numDecMembers; }
References ASSERT, and m_numDecMembers.
numDocEnumValues() [1/2]
int MemberList::numDocEnumValues () const [inline]
Definition at line 93 of file memberlist.h.
{ return m_numDocEnumValues; }
References m_numDocEnumValues.
Referenced by writeDocumentation(), and writeSimpleDocumentation().
numDocEnumValues() [2/2]
int MemberList::numDocEnumValues () const [inline]
Definition at line 93 of file memberlist.h.
{ return m_numDocEnumValues; }
References m_numDocEnumValues.
numDocMembers() [1/2]
int MemberList::numDocMembers () const [inline]
Definition at line 92 of file memberlist.h.
{ ASSERT(m_numDocMembers!=-1); return m_numDocMembers; }
References ASSERT, and m_numDocMembers.
Referenced by FileDefImpl::numDocMembers(), NamespaceDefImpl::numDocMembers(), writeDocumentation(), and writeSimpleDocumentation().
numDocMembers() [2/2]
int MemberList::numDocMembers () const [inline]
Definition at line 92 of file memberlist.h.
{ ASSERT(m_numDocMembers!=-1); return m_numDocMembers; }
References ASSERT, and m_numDocMembers.
setAnchors() [1/2]
void MemberList::setAnchors ()
Definition at line 975 of file memberlist.cpp.
{
  //int count=0;
  for (const auto &md : m_members)
  {
    MemberDefMutable *mdm = toMemberDefMutable(md);
    if (mdm && !md->isReference())
    {
      mdm->setAnchor();
    }
  }
}
References MemberDef::isReference(), MemberVector::m_members, MemberDefMutable::setAnchor(), and toMemberDefMutable().
Referenced by FileDefImpl::computeAnchors(), GroupDefImpl::computeAnchors(), and NamespaceDefImpl::computeAnchors().
setAnchors() [2/2]
void MemberList::setAnchors ()
setAnonymousEnumType() [1/2]
void MemberList::setAnonymousEnumType ()
Definition at line 226 of file memberlist.cpp.
{
  //printf("MemberList(%p)::setAnonymousEnumType()\n",this);
  for (const auto &md : m_members)
  {
    if (md->isBriefSectionVisible())
    {
      QCString name(md->name());
      int i=name.findRev("::");
      if (i!=-1) name=name.right(name.length()-i-2);
      if (md->memberType()==MemberType_Enumeration && name[0]=='@')
      {
        for (const auto &vmd : md->enumFieldList())
        {
          MemberDefMutable *vmdm = toMemberDefMutable(vmd);
          if (vmdm)
          {
            QCString vtype=vmd->typeString();
            if ((vtype.find(name))!=-1)
            {
              vmdm->setAnonymousEnumType(md);
            }
          }
        }
      }
    }
  }
  for (const auto &mg : m_memberGroupRefList)
  {
    mg->setAnonymousEnumType();
  }
}
References QCString::find(), m_memberGroupRefList, MemberVector::m_members, MemberType_Enumeration, setup::name, MemberDefMutable::setAnonymousEnumType(), and toMemberDefMutable().
Referenced by ClassDefImpl::setAnonymousEnumType().
setAnonymousEnumType() [2/2]
void MemberList::setAnonymousEnumType ()
setNeedsSorting() [1/2]
void MemberList::setNeedsSorting (bool b)
Definition at line 877 of file memberlist.cpp.
{
  m_needsSorting = b;
}
References b, and m_needsSorting.
Referenced by FileDefImpl::sortMemberLists().
setNeedsSorting() [2/2]
void MemberList::setNeedsSorting (bool b)
writeDeclarations() [1/2]
void MemberList::writeDeclarations (OutputList & ol, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd, const QCString & title, const QCString & subtitle, bool showEnumValues = FALSE, bool showInline = FALSE, const ClassDef * inheritedFrom = 0, MemberListType lt = MemberListType_pubMethods) const
Writes the list of members to the output.
Parameters
ol Output list to write to
cd non-null if this list is part of class documentation.
nd non-null if this list is part of namespace documentation.
fd non-null if this list is part of file documentation.
gd non-null if this list is part of group documentation.
title Title to use for the member list.
subtitle Sub title to use for the member list.
showEnumValues Obsolete, always set to FALSE.
showInline if set to TRUE if title is rendered differently
inheritedFrom if not 0, the list is shown inside the given class as inherited members, parameter cd points to the class containing the members.
lt Type of list that is inherited from.
Definition at line 526 of file memberlist.cpp.
{
  (void)showEnumValues; // unused
  //printf("----- writeDeclaration() this=%p ---- inheritedFrom=%p\n",this,inheritedFrom);
  bool optimizeVhdl = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
  QCString inheritId;
  const Definition *ctx = cd;
  if (ctx==0 && nd) ctx = nd;
  if (ctx==0 && gd) ctx = gd;
  if (ctx==0 && fd) ctx = fd;
  //printf("%p: MemberList::writeDeclaration(title='%s',subtitle='%s')=%d inheritedFrom=%p\n",
  // this,title,subtitle,numDecMembers(),inheritedFrom);
  int num = numDecMembers();
  int numEnumValues = numDecEnumValues();
  if (inheritedFrom)
  {
    //if (cd && !optimizeVhdl && countInheritableMembers(inheritedFrom)>0)
    if (cd && !optimizeVhdl && cd->countMembersIncludingGrouped(
                                      m_listType,inheritedFrom,TRUE)>0)
    {
      ol.pushGeneratorState();
      ol.disableAllBut(OutputGenerator::Html);
      inheritId = substitute(listTypeAsString(lt),"-","_")+"_"+
                  stripPath(cd->getOutputFileBase());
      if (!title.isEmpty())
      {
        ol.writeInheritedSectionTitle(inheritId,cd->getReference(),
                                      cd->getOutputFileBase(),
                                      cd->anchor(),title,cd->displayName());
      }
      ol.popGeneratorState();
    }
  }
  else if (num>numEnumValues)
  {
    if (!title.isEmpty())
    {
      if (showInline)
      {
        ol.startInlineHeader();
      }
      else
      {
        ol.startMemberHeader(listTypeAsString(m_listType));
      }
      ol.parseText(title);
      if (showInline)
      {
        ol.endInlineHeader();
      }
      else
      {
        ol.endMemberHeader();
      }
    }
    if (!subtitle.stripWhiteSpace().isEmpty())
    {
      ol.startMemberSubtitle();
      ol.generateDoc("[generated]",-1,ctx,0,subtitle,FALSE,FALSE,
                     QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
      ol.endMemberSubtitle();
    }
  }
  if (num>numEnumValues)
  {
     bool inGroup = m_container==MemberListContainer::Group;
    // TODO: Two things need to be worked out for proper VHDL output:
    // 1. Signals and types under the group need to be
    // formatted to associate them with the group somehow
    // indentation, or at the very least, extra space after
    // the group is done
    // 2. This might need to be repeated below for memberGroupLists
    if (optimizeVhdl) // use specific declarations function
    {
      VhdlDocGen::writeVhdlDeclarations(this,ol,0,cd,0,0);
    }
    else
    {
      writePlainDeclarations(ol,inGroup,cd,nd,fd,gd,0,0,inheritId);
    }
    //printf("memberGroupList=%p\n",memberGroupList);
    for (const auto &mg : m_memberGroupRefList)
    {
      bool hasHeader=!mg->header().isEmpty();
      if (inheritId.isEmpty())
      {
        //printf("mg->header=%s hasHeader=%d\n",qPrint(mg->header()),hasHeader);
        ol.startMemberGroupHeader(hasHeader);
        if (hasHeader)
        {
          ol.parseText(mg->header());
        }
        ol.endMemberGroupHeader();
        if (!mg->documentation().isEmpty())
        {
          //printf("Member group has docs!\n");
          ol.startMemberGroupDocs();
          ol.generateDoc(mg->docFile(),mg->docLine(),mg->memberContainer(),0,mg->documentation()+"\n",FALSE,FALSE,
              QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
          ol.endMemberGroupDocs();
        }
        ol.startMemberGroup();
      }
      //printf("--- mg->writePlainDeclarations ---\n");
      mg->writePlainDeclarations(ol,inGroup,cd,nd,fd,gd,0,inheritedFrom,inheritId);
      if (inheritId.isEmpty())
      {
        ol.endMemberGroup(hasHeader);
      }
    }
  }
  if (inheritedFrom && cd)
  {
    const ClassDefMutable *cdm = toClassDefMutable(cd);
    if (cdm)
    {
      // also add members that of this list type, that are grouped together
      // in a separate list in class 'inheritedFrom'
      cdm->addGroupedInheritedMembers(ol,m_listType,inheritedFrom,inheritId);
    }
  }
  //printf("----- end writeDeclaration() ----\n");
}
References ClassDefMutable::addGroupedInheritedMembers(), ClassDef::anchor(), Config_getBool, ClassDef::countMembersIncludingGrouped(), OutputList::disableAllBut(), ClassDef::displayName(), OutputList::endInlineHeader(), OutputList::endMemberGroup(), OutputList::endMemberGroupDocs(), OutputList::endMemberGroupHeader(), OutputList::endMemberHeader(), OutputList::endMemberSubtitle(), FALSE, OutputList::generateDoc(), ClassDef::getOutputFileBase(), ClassDef::getReference(), Group, OutputGenerator::Html, QCString::isEmpty(), listTypeAsString(), m_container, m_listType, m_memberGroupRefList, numDecEnumValues(), numDecMembers(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startInlineHeader(), OutputList::startMemberGroup(), OutputList::startMemberGroupDocs(), OutputList::startMemberGroupHeader(), OutputList::startMemberHeader(), OutputList::startMemberSubtitle(), stripPath(), QCString::stripWhiteSpace(), substitute(), toClassDefMutable(), TRUE, OutputList::writeInheritedSectionTitle(), writePlainDeclarations(), and VhdlDocGen::writeVhdlDeclarations().
Referenced by ClassDefImpl::writeMemberDeclarations(), FileDefImpl::writeMemberDeclarations(), GroupDefImpl::writeMemberDeclarations(), and NamespaceDefImpl::writeMemberDeclarations().
writeDeclarations() [2/2]
void MemberList::writeDeclarations (OutputList & ol, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd, const QCString & title, const QCString & subtitle, bool showEnumValues = FALSE, bool showInline = FALSE, const ClassDef * inheritedFrom = 0, MemberListType lt = MemberListType_pubMethods) const
writeDocumentation() [1/2]
void MemberList::writeDocumentation (OutputList & ol, const QCString & scopeName, const Definition * container, const QCString & title, bool showEnumValues = FALSE, bool showInline = FALSE) const
Definition at line 658 of file memberlist.cpp.
{
  if (numDocMembers()==-1)
  {
    err("MemberList::numDocMembers()==-1, so the members of this list have not been counted. Please report as a bug.\n");
    abort();
  }
  if (numDocMembers()==0) return;
  if (!showEnumValues && numDocMembers()<=numDocEnumValues()) return;
  if (!title.isEmpty())
  {
    ol.pushGeneratorState();
      ol.disable(OutputGenerator::Html);
      ol.writeRuler();
    ol.popGeneratorState();
    ol.startGroupHeader(showInline ? 2 : 0);
    ol.parseText(title);
    ol.endGroupHeader(showInline ? 2 : 0);
  }
  ol.startMemberDocList();
  struct OverloadInfo
  {
    uint count = 1;
    uint total = 0;
  };
  std::unordered_map<std::string,OverloadInfo> overloadInfo;
  // count the number of overloaded members
  for (const auto &md : m_members)
  {
    if (md->isDetailedSectionVisible(m_container) &&
        !(md->isEnumValue() && !showInline))
    {
      auto it = overloadInfo.insert(std::make_pair(md->name().str(),OverloadInfo())).first;
      it->second.total++;
    }
  }
  for (const auto &md : m_members)
  {
    if (md->isDetailedSectionVisible(m_container) &&
        !(md->isEnumValue() && !showInline))
    {
      auto it = overloadInfo.find(md->name().str());
      uint overloadCount = it->second.total;
      uint &count = it->second.count;
      MemberDefMutable *mdm = toMemberDefMutable(md);
      if (mdm)
      {
        mdm->writeDocumentation(this,count++,overloadCount,ol,scopeName,container,
            m_container==MemberListContainer::Group,showEnumValues,showInline);
      }
    }
  }
  //printf("MemberList::writeDocumentation() -- member groups %d\n",memberGroupList->count());
  for (const auto &mg : m_memberGroupRefList)
  {
    mg->writeDocumentation(ol,scopeName,container,showEnumValues,showInline);
  }
  ol.endMemberDocList();
}
References container(), OutputList::disable(), OutputList::endGroupHeader(), OutputList::endMemberDocList(), err(), Group, OutputGenerator::Html, QCString::isEmpty(), m_container, m_memberGroupRefList, MemberVector::m_members, numDocEnumValues(), numDocMembers(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startGroupHeader(), OutputList::startMemberDocList(), toMemberDefMutable(), MemberDefMutable::writeDocumentation(), and OutputList::writeRuler().
Referenced by FileDefImpl::writeMemberDocumentation(), GroupDefImpl::writeMemberDocumentation(), NamespaceDefImpl::writeMemberDocumentation(), and ClassDefImpl::writeMemberDocumentation().
writeDocumentation() [2/2]
void MemberList::writeDocumentation (OutputList & ol, const QCString & scopeName, const Definition * container, const QCString & title, bool showEnumValues = FALSE, bool showInline = FALSE) const
writeDocumentationPage() [1/2]
void MemberList::writeDocumentationPage (OutputList & ol, const QCString & scopeName, const DefinitionMutable * container) const
Definition at line 749 of file memberlist.cpp.
{
  bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
  struct OverloadInfo
  {
    uint count = 1;
    uint total = 0;
  };
  std::unordered_map<std::string,OverloadInfo> overloadInfo;
  // count the number of overloaded members
  for (const auto &imd : m_members)
  {
    MemberDefMutable *md = toMemberDefMutable(imd);
    if (md && md->hasDetailedDescription())
    {
      auto it = overloadInfo.insert(std::make_pair(md->name().str(),OverloadInfo())).first;
      it->second.total++;
    }
  }
  for (const auto &imd : m_members)
  {
    Definition *container_d = toDefinition(const_cast<DefinitionMutable*>(container));
    MemberDefMutable *md = toMemberDefMutable(imd);
    if (md && md->hasDetailedDescription())
    {
      auto it = overloadInfo.find(md->name().str());
      uint overloadCount = it->second.total;
      uint &count = it->second.count;
      QCString diskName=md->getOutputFileBase();
      QCString title=md->qualifiedName();
      startFile(ol,diskName,md->name(),title,HLI_None,!generateTreeView,diskName);
      if (!generateTreeView)
      {
        container->writeNavigationPath(ol);
        ol.endQuickIndices();
      }
      ol.startContents();
      if (generateTreeView)
      {
        md->writeDocumentation(this,count++,overloadCount,ol,scopeName,container_d,m_container==MemberListContainer::Group);
        ol.endContents();
        endFileWithNavPath(container_d,ol);
      }
      else
      {
        ol.writeString("<table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\n"
            " <tr>\n"
            " <td valign=\"top\">\n");
        container->writeQuickMemberLinks(ol,md);
        ol.writeString(" </td>\n");
        ol.writeString(" <td valign=\"top\" class=\"mempage\">\n");
        md->writeDocumentation(this,count++,overloadCount,ol,scopeName,container_d,m_container==MemberListContainer::Group);
        ol.writeString(" </td>\n");
        ol.writeString(" </tr>\n");
        ol.writeString("</table>\n");
        endFile(ol);
      }
    }
  }
  for (const auto &mg : m_memberGroupRefList)
  {
    mg->writeDocumentationPage(ol,scopeName,container);
  }
}
References Config_getBool, container(), OutputList::endContents(), endFile(), endFileWithNavPath(), OutputList::endQuickIndices(), MemberDef::getOutputFileBase(), Group, MemberDef::hasDetailedDescription(), HLI_None, m_container, m_memberGroupRefList, MemberVector::m_members, Definition::name(), MemberDef::qualifiedName(), OutputList::startContents(), startFile(), QCString::str(), toDefinition(), toMemberDefMutable(), MemberDefMutable::writeDocumentation(), and OutputList::writeString().
writeDocumentationPage() [2/2]
void MemberList::writeDocumentationPage (OutputList & ol, const QCString & scopeName, const DefinitionMutable * container) const
writePlainDeclarations() [1/2]
void MemberList::writePlainDeclarations (OutputList & ol, bool inGroup, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd, int indentLevel, const ClassDef * inheritedFrom, const QCString & inheritId) const
Definition at line 327 of file memberlist.cpp.
{
  //printf("----- writePlainDeclaration() ----\n");
  if (numDecMembers()==-1)
  {
    err("MemberList::numDecMembers()==-1, so the members of this list have not been counted. Please report as a bug.\n");
    abort();
  }
  if (numDecMembers()<=numDecEnumValues())
  {
    //printf(" --> no members!\n");
    return; // no members in this list
  }
  //printf(" --> writePlainDeclaration() numDecMembers()=%d\n",
  // numDecMembers());
  ol.pushGeneratorState();
  bool first=TRUE;
  for (const auto &md : m_members)
  {
    //printf(">>> Member '%s' type=%d visible=%d\n",
    // qPrint(md->name()),md->memberType(),md->isBriefSectionVisible());
    if ((inheritedFrom==0 || !md->isReimplementedBy(inheritedFrom)) &&
        md->isBriefSectionVisible())
    {
      //printf(">>> rendering\n");
      switch(md->memberType())
      {
        case MemberType_Define: // fall through
        //case MemberType_Prototype: // fall through
        case MemberType_Typedef: // fall through
        case MemberType_Variable: // fall through
        case MemberType_Function: // fall through
        case MemberType_Signal: // fall through
        case MemberType_Slot: // fall through
        case MemberType_DCOP: // fall through
        case MemberType_Property: // fall through
        case MemberType_Interface: // fall through
        case MemberType_Service: // fall through
        case MemberType_Sequence: // fall through
        case MemberType_Dictionary: // fall through
        case MemberType_Event:
          {
            if (first) ol.startMemberList(),first=FALSE;
            md->writeDeclaration(ol,cd,nd,fd,gd,inGroup,indentLevel,inheritedFrom,inheritId);
            break;
          }
        case MemberType_Enumeration:
          {
            // if this is an anonymous enum and there are variables of this
            // enum type (i.e. enumVars>0), then we do not show the enum here.
            if (countEnumValues(md)==0) // show enum here
            {
              //printf("Enum!!\n");
              if (first)
              {
                ol.startMemberList();
                first=FALSE;
              }
              ol.startMemberDeclaration();
              ol.startMemberItem(md->anchor(),0,inheritId);
              bool detailsLinkable = md->hasDetailedDescription();
              if (!detailsLinkable)
              {
                ol.startDoxyAnchor(md->getOutputFileBase(),QCString(),md->anchor(),md->name(),QCString());
              }
              if (md->isSliceLocal())
              {
                ol.writeString("local ");
              }
              ol.writeString("enum ");
              if (md->getLanguage()==SrcLangExt_Cpp && md->isStrong())
              {
                if (md->isEnumStruct())
                {
                  ol.writeString("struct ");
                }
                else
                {
                  ol.writeString("class ");
                }
              }
              ol.insertMemberAlign();
              md->writeEnumDeclaration(ol,cd,nd,fd,gd);
              if (!detailsLinkable)
              {
                ol.endDoxyAnchor(md->getOutputFileBase(),md->anchor());
              }
              ol.endMemberItem();
              if (!md->briefDescription().isEmpty() && Config_getBool(BRIEF_MEMBER_DESC))
              {
                auto parser { createDocParser() };
                auto ast { validatingParseDoc(*parser.get(),
                                                 md->briefFile(),md->briefLine(),
                                                 cd,md,
                                                 md->briefDescription(),
                                                 TRUE,FALSE,
                                                 QCString(),TRUE,FALSE,
                                                 Config_getBool(MARKDOWN_SUPPORT)) };
                if (!ast->isEmpty())
                {
                  ol.startMemberDescription(md->anchor());
                  ol.writeDoc(ast.get(),cd,md);
                  if (md->hasDetailedDescription())
                  {
                    ol.disableAllBut(OutputGenerator::Html);
                    ol.docify(" ");
                    ol.startTextLink(md->getOutputFileBase(),
                        md->anchor());
                    ol.parseText(theTranslator->trMore());
                    ol.endTextLink();
                    ol.enableAll();
                  }
                  ol.endMemberDescription();
                }
              }
              ol.endMemberDeclaration(md->anchor(),inheritId);
            }
            md->warnIfUndocumented();
            break;
          }
        case MemberType_Friend:
          if (inheritedFrom==0)
          {
            if (first)
            {
              ol.startMemberList();
              first=FALSE;
            }
            md->writeDeclaration(ol,cd,nd,fd,gd,inGroup,indentLevel,inheritedFrom,inheritId);
            break;
          }
        case MemberType_EnumValue:
          {
            if (inGroup)
            {
              //printf("EnumValue!\n");
              if (first) ol.startMemberList(),first=FALSE;
              md->writeDeclaration(ol,cd,nd,fd,gd,true,indentLevel,inheritedFrom,inheritId);
            }
          }
          break;
      }
    }
  }
  // handle members that are inside anonymous compounds and for which
  // no variables of the anonymous compound type exist.
  if (cd)
  {
    for (const auto &md : m_members)
    {
      if (md->fromAnonymousScope() && !md->anonymousDeclShown())
      {
        MemberDefMutable *mdm = toMemberDefMutable(md);
        if (mdm) mdm->setFromAnonymousScope(FALSE);
        //printf("anonymous compound members\n");
        if (md->isBriefSectionVisible())
        {
          if (first)
          {
            ol.startMemberList();
            first=FALSE;
          }
          md->writeDeclaration(ol,cd,nd,fd,gd,inGroup,indentLevel);
        }
        if (mdm) mdm->setFromAnonymousScope(TRUE);
      }
    }
  }
  if (!first)
  {
    ol.endMemberList();
  }
  ol.popGeneratorState();
  //printf("----- end writePlainDeclaration() ----\n");
}
References Definition::briefDescription(), Config_getBool, countEnumValues(), createDocParser(), OutputList::disableAllBut(), OutputList::docify(), OutputList::enableAll(), OutputList::endDoxyAnchor(), OutputList::endMemberDeclaration(), OutputList::endMemberDescription(), OutputList::endMemberItem(), OutputList::endMemberList(), OutputList::endTextLink(), err(), FALSE, OutputGenerator::Html, OutputList::insertMemberAlign(), MemberVector::m_members, MemberType_DCOP, MemberType_Define, MemberType_Dictionary, MemberType_Enumeration, MemberType_EnumValue, MemberType_Event, MemberType_Friend, MemberType_Function, MemberType_Interface, MemberType_Property, MemberType_Sequence, MemberType_Service, MemberType_Signal, MemberType_Slot, MemberType_Typedef, MemberType_Variable, numDecEnumValues(), numDecMembers(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), MemberDefMutable::setFromAnonymousScope(), SrcLangExt_Cpp, OutputList::startDoxyAnchor(), OutputList::startMemberDeclaration(), OutputList::startMemberDescription(), OutputList::startMemberItem(), OutputList::startMemberList(), OutputList::startTextLink(), theTranslator, toMemberDefMutable(), Translator::trMore(), TRUE, validatingParseDoc(), OutputList::writeDoc(), and OutputList::writeString().
Referenced by MemberGroup::addGroupedInheritedMembers(), writeDeclarations(), and ClassDefImpl::writePlainMemberDeclaration().
writePlainDeclarations() [2/2]
void MemberList::writePlainDeclarations (OutputList & ol, bool inGroup, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd, int indentLevel, const ClassDef * inheritedFrom, const QCString & inheritId) const
writeSimpleDocumentation() [1/2]
void MemberList::writeSimpleDocumentation (OutputList & ol, const Definition * container) const
Definition at line 725 of file memberlist.cpp.
{
  //printf("MemberList count=%d enumValues=%d\n",numDocMembers(),numDocEnumValues());
  if (numDocMembers()<=numDocEnumValues()) return; // only enum values and they should be excluded
  const ClassDef *cd = 0;
  if (container && container->definitionType()==Definition::TypeClass)
  {
    cd = toClassDef(container);
  }
  ol.startMemberDocSimple(cd && cd->isJavaEnum());
  for (const auto &md : m_members)
  {
    MemberDefMutable *mdm = toMemberDefMutable(md);
    if (mdm)
    {
      mdm->writeMemberDocSimple(ol,container);
    }
  }
  ol.endMemberDocSimple(cd && cd->isJavaEnum());
}
References container(), OutputList::endMemberDocSimple(), ClassDef::isJavaEnum(), MemberVector::m_members, numDocEnumValues(), numDocMembers(), OutputList::startMemberDocSimple(), toClassDef(), toMemberDefMutable(), Definition::TypeClass, and MemberDefMutable::writeMemberDocSimple().
Referenced by ClassDefImpl::writeSimpleMemberDocumentation().
writeSimpleDocumentation() [2/2]
void MemberList::writeSimpleDocumentation (OutputList & ol, const Definition * container) const
writeTagFile() [1/2]
void MemberList::writeTagFile (TextStream & tagFile, bool useQualifiedName = false)
Definition at line 940 of file memberlist.cpp.
{
  for (const auto &imd : m_members)
  {
    MemberDefMutable *md = toMemberDefMutable(imd);
    if (md)
    {
      if (md->getLanguage()!=SrcLangExt_VHDL)
      {
        md->writeTagFile(tagFile,useQualifiedName);
        if (md->memberType()==MemberType_Enumeration && !md->isStrong())
        {
          for (const auto &ivmd : md->enumFieldList())
          {
            MemberDefMutable *vmd = toMemberDefMutable(ivmd);
            if (vmd)
            {
              vmd->writeTagFile(tagFile,useQualifiedName);
            }
          }
        }
      }
      else
      {
        VhdlDocGen::writeTagFile(md,tagFile);
      }
    }
  }
  for (const auto &mg : m_memberGroupRefList)
  {
    mg->writeTagFile(tagFile,useQualifiedName);
  }
}
References MemberDef::enumFieldList(), Definition::getLanguage(), MemberDef::isStrong(), m_memberGroupRefList, MemberVector::m_members, MemberDef::memberType(), MemberType_Enumeration, SrcLangExt_VHDL, toMemberDefMutable(), VhdlDocGen::writeTagFile(), and MemberDefMutable::writeTagFile().
Referenced by ClassDefImpl::writeTagFile(), GroupDefImpl::writeTagFile(), NamespaceDefImpl::writeTagFile(), and FileDefImpl::writeTagFile().
writeTagFile() [2/2]
void MemberList::writeTagFile (TextStream & , bool useQualifiedName = false)
Member Data Documentation
m_container
MemberListContainer MemberList::m_container [private]
Definition at line 129 of file memberlist.h.
Referenced by container(), countDocMembers(), declVisible(), writeDeclarations(), writeDocumentation(), and writeDocumentationPage().
m_listType
MemberListType MemberList::m_listType [private]
Definition at line 130 of file memberlist.h.
Referenced by listType(), and writeDeclarations().
m_memberGroupRefList
MemberGroupRefList MemberList::m_memberGroupRefList [private]
Definition at line 128 of file memberlist.h.
Referenced by addListReferences(), addMemberGroup(), countDecMembers(), countDocMembers(), countInheritableMembers(), findSectionsInDocumentation(), getMemberGroupList(), setAnonymousEnumType(), writeDeclarations(), writeDocumentation(), writeDocumentationPage(), and writeTagFile().
m_needsSorting
bool MemberList::m_needsSorting [private]
Definition at line 131 of file memberlist.h.
Referenced by MemberList(), needsSorting(), and setNeedsSorting().
m_numDecEnumValues
int MemberList::m_numDecEnumValues [private]
Definition at line 125 of file memberlist.h.
Referenced by countDecMembers(), MemberList(), and numDecEnumValues().
m_numDecMembers
int MemberList::m_numDecMembers [private]
Definition at line 124 of file memberlist.h.
Referenced by countDecMembers(), MemberList(), and numDecMembers().
m_numDocEnumValues
int MemberList::m_numDocEnumValues [private]
Definition at line 127 of file memberlist.h.
Referenced by countDocMembers(), MemberList(), and numDocEnumValues().
m_numDocMembers
int MemberList::m_numDocMembers [private]
Definition at line 126 of file memberlist.h.
Referenced by countDocMembers(), MemberList(), and numDocMembers().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/memberlist.h
doxygen/src/memberlist.h
doxygen/build/doxygen/src/memberlist.cpp
doxygen/src/memberlist.cpp