FileCodeParser Class Reference
Generic code parser.
#include <fileparser.h>
Public Member Functions
void parseCode (CodeOutputInterface &codeOutIntf, const QCString &scopeName, const QCString &input, SrcLangExt lang, bool isExampleBlock, const QCString &exampleName=QCString(), const FileDef *fileDef=0, int startLine=-1, int endLine=-1, bool inlineFragment=FALSE, const MemberDef *memberDef=0, bool showLineNumbers=TRUE, const Definition *searchCtx=0, bool collectXRefs=TRUE)
void resetCodeParserState ()
void parseCode (CodeOutputInterface &codeOutIntf, const QCString &scopeName, const QCString &input, SrcLangExt lang, bool isExampleBlock, const QCString &exampleName=QCString(), const FileDef *fileDef=0, int startLine=-1, int endLine=-1, bool inlineFragment=FALSE, const MemberDef *memberDef=0, bool showLineNumbers=TRUE, const Definition *searchCtx=0, bool collectXRefs=TRUE)
void resetCodeParserState ()
Detailed Description
Generic code parser.
Definition at line 22 of file fileparser.h.
Member Function Documentation
parseCode() [1/2]
void FileCodeParser::parseCode (CodeOutputInterface & codeOutIntf, const QCString & scopeName, const QCString & input, SrcLangExt lang, bool isExampleBlock, const QCString & exampleName = QCString(), const FileDef * fileDef = 0, int startLine = -1, int endLine = -1, bool inlineFragment = FALSE, const MemberDef * memberDef = 0, bool showLineNumbers = TRUE, const Definition * searchCtx = 0, bool collectXRefs = TRUE) [virtual]
Parses a source file or fragment with the goal to produce highlighted and cross-referenced output.
Parameters
 in codeOutIntf Abstract interface for writing the result.
 in scopeName Name of scope to which the code belongs.
 in input Actual code in the form of a string
 in lang The programming language of the code fragment.
 in isExampleBlock TRUE iff the code is part of an example.
 in exampleName Name of the example.
 in fileDef File definition to which the code is associated.
 in startLine Starting line in case of a code fragment.
 in endLine Ending line of the code fragment.
 in inlineFragment Code fragment that is to be shown inline as part of the documentation.
 in memberDef Member definition to which the code is associated (non null in case of an inline fragment for a member).
 in showLineNumbers if set to TRUE and also fileDef is not 0, line numbers will be added to the source fragment
 in searchCtx context under which search data has to be stored.
 in collectXRefs collect cross-reference relations.
Implements CodeParserInterface.
Definition at line 19 of file fileparser.cpp.
{
  int lineNr = startLine!=-1 ? startLine : 1;
  int length = input.length();
  int i=0;
  while (i<length && (endLine==-1 || lineNr<=endLine))
  {
    int j=i;
    while (j<length && input[j]!='\n') j++;
    QCString lineStr = input.mid(i,j-i);
    codeOutIntf.startCodeLine(fileDef != 0 && showLineNumbers);
    if (fileDef != 0 && showLineNumbers)
    {
      codeOutIntf.writeLineNumber(QCString(),QCString(),QCString(),lineNr,!inlineFragment);
    }
    if (!lineStr.isEmpty()) codeOutIntf.codify(lineStr.data());
    codeOutIntf.endCodeLine();
    lineNr++;
    i=j+1;
  }
}
References CodeOutputInterface::codify(), QCString::data(), CodeOutputInterface::endCodeLine(), QCString::isEmpty(), QCString::length(), QCString::mid(), CodeOutputInterface::startCodeLine(), and CodeOutputInterface::writeLineNumber().
parseCode() [2/2]
void FileCodeParser::parseCode (CodeOutputInterface & codeOutIntf, const QCString & scopeName, const QCString & input, SrcLangExt lang, bool isExampleBlock, const QCString & exampleName = QCString(), const FileDef * fileDef = 0, int startLine = -1, int endLine = -1, bool inlineFragment = FALSE, const MemberDef * memberDef = 0, bool showLineNumbers = TRUE, const Definition * searchCtx = 0, bool collectXRefs = TRUE) [virtual]
Parses a source file or fragment with the goal to produce highlighted and cross-referenced output.
Parameters
 in codeOutIntf Abstract interface for writing the result.
 in scopeName Name of scope to which the code belongs.
 in input Actual code in the form of a string
 in lang The programming language of the code fragment.
 in isExampleBlock TRUE iff the code is part of an example.
 in exampleName Name of the example.
 in fileDef File definition to which the code is associated.
 in startLine Starting line in case of a code fragment.
 in endLine Ending line of the code fragment.
 in inlineFragment Code fragment that is to be shown inline as part of the documentation.
 in memberDef Member definition to which the code is associated (non null in case of an inline fragment for a member).
 in showLineNumbers if set to TRUE and also fileDef is not 0, line numbers will be added to the source fragment
 in searchCtx context under which search data has to be stored.
 in collectXRefs collect cross-reference relations.
Implements CodeParserInterface.
resetCodeParserState() [1/2]
void FileCodeParser::resetCodeParserState () [inline], [virtual]
Resets the state of the code parser. Since multiple code fragments can together form a single example, an explicit function is used to reset the code parser state.
See also
parseCode()
Implements CodeParserInterface.
Definition at line 40 of file fileparser.h.
{}
resetCodeParserState() [2/2]
void FileCodeParser::resetCodeParserState () [inline], [virtual]
Resets the state of the code parser. Since multiple code fragments can together form a single example, an explicit function is used to reset the code parser state.
See also
parseCode()
Implements CodeParserInterface.
Definition at line 40 of file fileparser.h.
{}
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/fileparser.h
doxygen/src/fileparser.h
doxygen/build/doxygen/src/fileparser.cpp
doxygen/src/fileparser.cpp