RefListManager Class Reference
#include <reflist.h>
Static Public Member Functions
static RefListManager & instance ()
static RefListManager & instance ()
Private Member Functions
RefListManager ()
RefListManager (const RefListManager &other)=delete
RefListManager & operator= (const RefListManager &other)=delete
RefListManager ()
RefListManager (const RefListManager &other)=delete
RefListManager & operator= (const RefListManager &other)=delete
Additional Inherited Members
Detailed Description
Definition at line 117 of file reflist.h.
Constructor & Destructor Documentation
RefListManager() [1/4]
RefListManager::RefListManager () [inline], [private]
Definition at line 127 of file reflist.h.
{}
RefListManager() [2/4]
RefListManager::RefListManager (const RefListManager & other) [private], [delete]
RefListManager() [3/4]
RefListManager::RefListManager () [inline], [private]
Definition at line 127 of file reflist.h.
{}
RefListManager() [4/4]
RefListManager::RefListManager (const RefListManager & other) [private], [delete]
Member Function Documentation
instance() [1/2]
static RefListManager & RefListManager::instance () [inline], [static]
Definition at line 120 of file reflist.h.
    {
      static RefListManager rlm;
      return rlm;
    }
Referenced by addXRefItem(), generateXRefPages(), DocXRefItem::parse(), resolveUserReferences(), and PageDefImpl::writeTagFile().
instance() [2/2]
static RefListManager & RefListManager::instance () [inline], [static]
Definition at line 120 of file reflist.h.
    {
      static RefListManager rlm;
      return rlm;
    }
operator=() [1/2]
RefListManager & RefListManager::operator= (const RefListManager & other) [private], [delete]
operator=() [2/2]
RefListManager & RefListManager::operator= (const RefListManager & other) [private], [delete]
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/reflist.h
doxygen/src/reflist.h