ConceptDef Class Reference
#include <conceptdef.h>
Public Member Functions
virtual DefType definitionType () const =0
virtual QCString getOutputFileBase () const =0
virtual bool hasDetailedDescription () const =0
virtual QCString displayName (bool includeScope=true) const =0
virtual const IncludeInfo * includeInfo () const =0
virtual ArgumentList getTemplateParameterList () const =0
virtual QCString anchor () const =0
virtual bool isLinkableInProject () const =0
virtual bool isLinkable () const =0
virtual QCString initializer () const =0
virtual void writeDeclarationLink (OutputList &ol, bool &found, const QCString &header, bool localNames) const =0
virtual const NamespaceDef * getNamespaceDef () const =0
virtual const FileDef * getFileDef () const =0
virtual QCString title () const =0
virtual int groupId () const =0
virtual DefType definitionType () const =0
virtual QCString getOutputFileBase () const =0
virtual bool hasDetailedDescription () const =0
virtual QCString displayName (bool includeScope=true) const =0
virtual const IncludeInfo * includeInfo () const =0
virtual ArgumentList getTemplateParameterList () const =0
virtual QCString anchor () const =0
virtual bool isLinkableInProject () const =0
virtual bool isLinkable () const =0
virtual QCString initializer () const =0
virtual void writeDeclarationLink (OutputList &ol, bool &found, const QCString &header, bool localNames) const =0
virtual const NamespaceDef * getNamespaceDef () const =0
virtual const FileDef * getFileDef () const =0
virtual QCString title () const =0
virtual int groupId () const =0
Additional Inherited Members
Detailed Description
Definition at line 22 of file conceptdef.h.
Member Function Documentation
anchor() [1/2]
virtual QCString ConceptDef::anchor () const [pure virtual]
Returns the anchor within a page where this item can be found
Implements Definition.
Implemented in ConceptDefImpl, ConceptDefAliasImpl, ConceptDefImpl, and ConceptDefAliasImpl.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), ConceptDefAliasImpl::anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), if(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), resolveLink(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
anchor() [2/2]
virtual QCString ConceptDef::anchor () const [pure virtual]
Returns the anchor within a page where this item can be found
Implements Definition.
Implemented in ConceptDefImpl, ConceptDefAliasImpl, ConceptDefImpl, and ConceptDefAliasImpl.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
definitionType() [1/2]
virtual DefType ConceptDef::definitionType () const [pure virtual]
Use this for dynamic inspection of the type of the derived class
Implements Definition.
Implemented in ConceptDefImpl, ConceptDefAliasImpl, ConceptDefImpl, and ConceptDefAliasImpl.
definitionType() [2/2]
virtual DefType ConceptDef::definitionType () const [pure virtual]
Use this for dynamic inspection of the type of the derived class
Implements Definition.
Implemented in ConceptDefImpl, ConceptDefAliasImpl, ConceptDefImpl, and ConceptDefAliasImpl.
displayName() [1/2]
virtual QCString ConceptDef::displayName (bool includeScope = true) const [pure virtual]
Returns the name of the definition as it appears in the output
Implements Definition.
Implemented in ConceptDefImpl, ConceptDefAliasImpl, ConceptDefImpl, and ConceptDefAliasImpl.
Referenced by ConceptDefAliasImpl::displayName().
displayName() [2/2]
virtual QCString ConceptDef::displayName (bool includeScope = true) const [pure virtual]
Returns the name of the definition as it appears in the output
Implements Definition.
Implemented in ConceptDefImpl, ConceptDefAliasImpl, ConceptDefImpl, and ConceptDefAliasImpl.
getFileDef() [1/2]
virtual const FileDef * ConceptDef::getFileDef () const [pure virtual]
Implemented in ConceptDefImpl, ConceptDefAliasImpl, ConceptDefImpl, and ConceptDefAliasImpl.
Referenced by generateXMLForConcept(), ConceptDefAliasImpl::getFileDef(), and writeTemplateList().
getFileDef() [2/2]
virtual const FileDef * ConceptDef::getFileDef () const [pure virtual]
Implemented in ConceptDefImpl, ConceptDefAliasImpl, ConceptDefImpl, and ConceptDefAliasImpl.
getNamespaceDef() [1/2]
virtual const NamespaceDef * ConceptDef::getNamespaceDef () const [pure virtual]
Implemented in ConceptDefImpl, ConceptDefAliasImpl, ConceptDefImpl, and ConceptDefAliasImpl.
Referenced by ConceptDefAliasImpl::getNamespaceDef().
getNamespaceDef() [2/2]
virtual const NamespaceDef * ConceptDef::getNamespaceDef () const [pure virtual]
Implemented in ConceptDefImpl, ConceptDefAliasImpl, ConceptDefImpl, and ConceptDefAliasImpl.
getOutputFileBase() [1/2]
virtual QCString ConceptDef::getOutputFileBase () const [pure virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements Definition.
Implemented in ConceptDefImpl, ConceptDefAliasImpl, ConceptDefImpl, and ConceptDefAliasImpl.
Referenced by generateXMLForConcept(), ConceptDefAliasImpl::getOutputFileBase(), and if().
getOutputFileBase() [2/2]
virtual QCString ConceptDef::getOutputFileBase () const [pure virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements Definition.
Implemented in ConceptDefImpl, ConceptDefAliasImpl, ConceptDefImpl, and ConceptDefAliasImpl.
getTemplateParameterList() [1/2]
virtual ArgumentList ConceptDef::getTemplateParameterList () const [pure virtual]
Implemented in ConceptDefImpl, ConceptDefAliasImpl, ConceptDefImpl, and ConceptDefAliasImpl.
Referenced by addTemplateList(), ConceptContext::Private::createTemplateDecls(), ConceptDefAliasImpl::getTemplateParameterList(), and writeTemplateList().
getTemplateParameterList() [2/2]
virtual ArgumentList ConceptDef::getTemplateParameterList () const [pure virtual]
Implemented in ConceptDefImpl, ConceptDefAliasImpl, ConceptDefImpl, and ConceptDefAliasImpl.
groupId() [1/2]
virtual int ConceptDef::groupId () const [pure virtual]
Implemented in ConceptDefImpl, ConceptDefAliasImpl, ConceptDefImpl, and ConceptDefAliasImpl.
Referenced by ConceptDefAliasImpl::groupId().
groupId() [2/2]
virtual int ConceptDef::groupId () const [pure virtual]
Implemented in ConceptDefImpl, ConceptDefAliasImpl, ConceptDefImpl, and ConceptDefAliasImpl.
hasDetailedDescription() [1/2]
virtual bool ConceptDef::hasDetailedDescription () const [pure virtual]
Implemented in ConceptDefImpl, ConceptDefAliasImpl, ConceptDefImpl, and ConceptDefAliasImpl.
Referenced by ConceptDefAliasImpl::hasDetailedDescription(), and ConceptContext::Private::hasDetails().
hasDetailedDescription() [2/2]
virtual bool ConceptDef::hasDetailedDescription () const [pure virtual]
Implemented in ConceptDefImpl, ConceptDefAliasImpl, ConceptDefImpl, and ConceptDefAliasImpl.
includeInfo() [1/2]
virtual const IncludeInfo * ConceptDef::includeInfo () const [pure virtual]
Implemented in ConceptDefImpl, ConceptDefAliasImpl, ConceptDefImpl, and ConceptDefAliasImpl.
Referenced by ConceptContext::Private::createIncludeInfo(), PerlModGenerator::generatePerlModForConcept(), generateXMLForConcept(), and ConceptDefAliasImpl::includeInfo().
includeInfo() [2/2]
virtual const IncludeInfo * ConceptDef::includeInfo () const [pure virtual]
Implemented in ConceptDefImpl, ConceptDefAliasImpl, ConceptDefImpl, and ConceptDefAliasImpl.
initializer() [1/2]
virtual QCString ConceptDef::initializer () const [pure virtual]
Implemented in ConceptDefImpl, ConceptDefAliasImpl, ConceptDefImpl, and ConceptDefAliasImpl.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), ConceptContext::Private::createInitializer(), ConceptContext::Private::createInitializerAsCode(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), PerlModGenerator::generatePerlModForConcept(), generateXMLForConcept(), doxmlparser.compound.compounddefType::get_initializer(), doxmlparser.compound.memberdefType::get_initializer(), doxmlparser.compound.enumvalueType::get_initializer(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), ConceptDefAliasImpl::initializer(), doxmlparser.compound.compounddefType::set_initializer(), doxmlparser.compound.memberdefType::set_initializer(), and doxmlparser.compound.enumvalueType::set_initializer().
initializer() [2/2]
virtual QCString ConceptDef::initializer () const [pure virtual]
Implemented in ConceptDefImpl, ConceptDefAliasImpl, ConceptDefImpl, and ConceptDefAliasImpl.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.compounddefType::get_initializer(), doxmlparser.compound.memberdefType::get_initializer(), doxmlparser.compound.enumvalueType::get_initializer(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.compounddefType::set_initializer(), doxmlparser.compound.memberdefType::set_initializer(), and doxmlparser.compound.enumvalueType::set_initializer().
isLinkable() [1/2]
virtual bool ConceptDef::isLinkable () const [pure virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements Definition.
Implemented in ConceptDefImpl, ConceptDefAliasImpl, ConceptDefImpl, and ConceptDefAliasImpl.
Referenced by NestingContext::Private::addConcept(), generateClassOrGlobalLink(), if(), and ConceptDefAliasImpl::isLinkable().
isLinkable() [2/2]
virtual bool ConceptDef::isLinkable () const [pure virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements Definition.
Implemented in ConceptDefImpl, ConceptDefAliasImpl, ConceptDefImpl, and ConceptDefAliasImpl.
isLinkableInProject() [1/2]
virtual bool ConceptDef::isLinkableInProject () const [pure virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements Definition.
Implemented in ConceptDefImpl, ConceptDefAliasImpl, ConceptDefImpl, and ConceptDefAliasImpl.
Referenced by generateConceptDocs(), if(), ConceptDefAliasImpl::isLinkableInProject(), and writeTagFile().
isLinkableInProject() [2/2]
virtual bool ConceptDef::isLinkableInProject () const [pure virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements Definition.
Implemented in ConceptDefImpl, ConceptDefAliasImpl, ConceptDefImpl, and ConceptDefAliasImpl.
title() [1/2]
virtual QCString ConceptDef::title () const [pure virtual]
Implemented in ConceptDefImpl, ConceptDefAliasImpl, ConceptDefImpl, and ConceptDefAliasImpl.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), doxmlparser.compound.docSimpleSectType::set_title(), ConceptDefAliasImpl::title(), and ConceptContext::Private::title().
title() [2/2]
virtual QCString ConceptDef::title () const [pure virtual]
Implemented in ConceptDefImpl, ConceptDefAliasImpl, ConceptDefImpl, and ConceptDefAliasImpl.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
writeDeclarationLink() [1/2]
virtual void ConceptDef::writeDeclarationLink (OutputList & ol, bool & found, const QCString & header, bool localNames) const [pure virtual]
Implemented in ConceptDefImpl, ConceptDefAliasImpl, ConceptDefImpl, and ConceptDefAliasImpl.
Referenced by ConceptDefAliasImpl::writeDeclarationLink().
writeDeclarationLink() [2/2]
virtual void ConceptDef::writeDeclarationLink (OutputList & ol, bool & found, const QCString & header, bool localNames) const [pure virtual]
Implemented in ConceptDefImpl, ConceptDefAliasImpl, ConceptDefImpl, and ConceptDefAliasImpl.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/conceptdef.h
doxygen/src/conceptdef.h