MemberInfoContext::Private Class Reference
Public Member Functions
Private (const MemberInfo *mi)
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private (const MemberInfo *mi)
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private Member Functions
TemplateVariant protection () const
TemplateVariant virtualness () const
TemplateVariant ambiguityScope () const
TemplateVariant member () const
TemplateVariant createMember () const
TemplateVariant protection () const
TemplateVariant virtualness () const
TemplateVariant ambiguityScope () const
TemplateVariant member () const
TemplateVariant createMember () const
Private Attributes
const MemberInfo * m_memberInfo
CachedItem< TemplateVariant, Private, &Private::createMember > m_member
Static Private Attributes
static const PropertyMap< MemberInfoContext::Private > s_inst
Detailed Description
Definition at line 7631 of file context.cpp.
Constructor & Destructor Documentation
Private() [1/2]
MemberInfoContext::Private::Private (const MemberInfo * mi) [inline]
Definition at line 7634 of file context.cpp.
: m_memberInfo(mi) {}
Private() [2/2]
MemberInfoContext::Private::Private (const MemberInfo * mi) [inline]
Definition at line 7634 of file context.cpp.
: m_memberInfo(mi) {}
Member Function Documentation
ambiguityScope() [1/2]
TemplateVariant MemberInfoContext::Private::ambiguityScope () const [inline], [private]
Definition at line 7663 of file context.cpp.
    {
      return m_memberInfo->ambiguityResolutionScope();
    }
References MemberInfo::ambiguityResolutionScope(), and m_memberInfo.
ambiguityScope() [2/2]
TemplateVariant MemberInfoContext::Private::ambiguityScope () const [inline], [private]
Definition at line 7663 of file context.cpp.
    {
      return m_memberInfo->ambiguityResolutionScope();
    }
createMember() [1/2]
TemplateVariant MemberInfoContext::Private::createMember () const [inline], [private]
Definition at line 7673 of file context.cpp.
    {
      return m_memberInfo->memberDef() ?
        TemplateVariant(MemberContext::alloc(m_memberInfo->memberDef())) :
        TemplateVariant(false);
    }
References MemberContext::alloc(), m_memberInfo, and MemberInfo::memberDef().
createMember() [2/2]
TemplateVariant MemberInfoContext::Private::createMember () const [inline], [private]
Definition at line 7673 of file context.cpp.
    {
      return m_memberInfo->memberDef() ?
        TemplateVariant(MemberContext::alloc(m_memberInfo->memberDef())) :
        TemplateVariant(false);
    }
References MemberContext::alloc().
fields() [1/2]
StringVector MemberInfoContext::Private::fields () const [inline]
Definition at line 7638 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
fields() [2/2]
StringVector MemberInfoContext::Private::fields () const [inline]
Definition at line 7638 of file context.cpp.
{ return s_inst.fields(); }
get() [1/2]
TemplateVariant MemberInfoContext::Private::get (const QCString & n) const [inline]
Definition at line 7637 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), n, and s_inst.
get() [2/2]
TemplateVariant MemberInfoContext::Private::get (const QCString & n) const [inline]
Definition at line 7637 of file context.cpp.
{ return s_inst.get(this,n); }
References n.
member() [1/2]
TemplateVariant MemberInfoContext::Private::member () const [inline], [private]
Definition at line 7667 of file context.cpp.
    {
      return m_member.get(this);
    }
References m_member.
Referenced by doxmlparser.compound.listofallmembersType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.listofallmembersType::add_member(), doxmlparser.index.CompoundType::add_member(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.listofallmembersType::get_member(), doxmlparser.index.CompoundType::get_member(), doxmlparser.compound.listofallmembersType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.compound.listofallmembersType::insert_member_at(), doxmlparser.index.CompoundType::insert_member_at(), doxmlparser.compound.listofallmembersType::replace_member_at(), doxmlparser.index.CompoundType::replace_member_at(), doxmlparser.compound.listofallmembersType::set_member(), and doxmlparser.index.CompoundType::set_member().
member() [2/2]
TemplateVariant MemberInfoContext::Private::member () const [inline], [private]
Definition at line 7667 of file context.cpp.
    {
      return m_member.get(this);
    }
Referenced by doxmlparser.compound.listofallmembersType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.listofallmembersType::add_member(), doxmlparser.index.CompoundType::add_member(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.listofallmembersType::get_member(), doxmlparser.index.CompoundType::get_member(), doxmlparser.compound.listofallmembersType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.compound.listofallmembersType::insert_member_at(), doxmlparser.index.CompoundType::insert_member_at(), doxmlparser.compound.listofallmembersType::replace_member_at(), doxmlparser.index.CompoundType::replace_member_at(), doxmlparser.compound.listofallmembersType::set_member(), and doxmlparser.index.CompoundType::set_member().
protection() [1/2]
TemplateVariant MemberInfoContext::Private::protection () const [inline], [private]
Definition at line 7642 of file context.cpp.
    {
      switch (m_memberInfo->prot())
      {
        case ::Public: return "public";
        case ::Protected: return "protected";
        case ::Private: return "private";
        case ::Package: return "package";
      }
      return "";
    }
References m_memberInfo, Package, Private, MemberInfo::prot(), Protected, and Public.
protection() [2/2]
TemplateVariant MemberInfoContext::Private::protection () const [inline], [private]
Definition at line 7642 of file context.cpp.
    {
      switch (m_memberInfo->prot())
      {
        case ::Public: return "public";
        case ::Protected: return "protected";
        case ::Private: return "private";
        case ::Package: return "package";
      }
      return "";
    }
References Package, Private, Protected, and Public.
virtualness() [1/2]
TemplateVariant MemberInfoContext::Private::virtualness () const [inline], [private]
Definition at line 7653 of file context.cpp.
    {
      switch (m_memberInfo->virt())
      {
        case ::Normal: return "normal";
        case ::Virtual: return "virtual";
        case ::Pure: return "pure";
      }
      return "";
    }
References m_memberInfo, Normal, Pure, MemberInfo::virt(), and Virtual.
virtualness() [2/2]
TemplateVariant MemberInfoContext::Private::virtualness () const [inline], [private]
Definition at line 7653 of file context.cpp.
    {
      switch (m_memberInfo->virt())
      {
        case ::Normal: return "normal";
        case ::Virtual: return "virtual";
        case ::Pure: return "pure";
      }
      return "";
    }
References Normal, Pure, and Virtual.
Member Data Documentation
m_member
CachedItem< TemplateVariant, Private, &Private::createMember > MemberInfoContext::Private::m_member [private]
Definition at line 7680 of file context.cpp.
Referenced by member().
m_memberInfo
const MemberInfo * MemberInfoContext::Private::m_memberInfo [private]
Definition at line 7679 of file context.cpp.
Referenced by ambiguityScope(), createMember(), protection(), and virtualness().
s_inst
const PropertyMap< MemberInfoContext::Private > MemberInfoContext::Private::s_inst [static], [private]
Initial value:
{
  
  { "protection", &Private::protection },
  
  { "virtualness", &Private::virtualness },
  
  { "ambiguityScope",&Private::ambiguityScope },
  
  { "member", &Private::member }
}
Definition at line 7681 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp