ConceptListContext::Private Class Reference
Public Member Functions
void addConcepts (const ConceptLinkedMap &nsLinkedMap)
void addConcepts (const ConceptLinkedMap &nsLinkedMap)
Additional Inherited Members
Detailed Description
Definition at line 6169 of file context.cpp.
Member Function Documentation
addConcepts() [1/2]
void ConceptListContext::Private::addConcepts (const ConceptLinkedMap & nsLinkedMap) [inline]
Definition at line 6172 of file context.cpp.
    {
      for (const auto &cd : nsLinkedMap)
      {
        if (cd->isLinkableInProject())
        {
          append(ConceptContext::alloc(cd.get()));
        }
      }
    }
References ConceptContext::alloc(), and GenericNodeListContext::append().
addConcepts() [2/2]
void ConceptListContext::Private::addConcepts (const ConceptLinkedMap & nsLinkedMap) [inline]
Definition at line 6172 of file context.cpp.
    {
      for (const auto &cd : nsLinkedMap)
      {
        if (cd->isLinkableInProject())
        {
          append(ConceptContext::alloc(cd.get()));
        }
      }
    }
References ConceptContext::alloc().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp