ConfigString Class Reference
#include <configimpl.h>
Public Types
enum WidgetType {
String
, File
, Dir
, Image
,
FileAndDir
, String
, File
, Dir
,
Image
, FileAndDir
 }
enum WidgetType {
String
, File
, Dir
, Image
,
FileAndDir
, String
, File
, Dir
,
Image
, FileAndDir
 }
Public Member Functions
ConfigString (const char *name, const char *doc)
~ConfigString ()
void setWidgetType (WidgetType w)
WidgetType widgetType () const
void setDefaultValue (const char *v)
QCString * valueRef ()
void writeTemplate (TextStream &t, bool sl, bool)
void compareDoxyfile (TextStream &t, Config::CompareMode compareMode)
void writeXMLDoxyfile (TextStream &t)
void substEnvVars ()
void init ()
void emptyValueToDefault ()
bool isDefault ()
ConfigString (const char *name, const char *doc)
~ConfigString ()
void setWidgetType (WidgetType w)
WidgetType widgetType () const
void setDefaultValue (const char *v)
QCString * valueRef ()
void writeTemplate (TextStream &t, bool sl, bool)
void compareDoxyfile (TextStream &t, Config::CompareMode compareMode)
void writeXMLDoxyfile (TextStream &t)
void substEnvVars ()
void init ()
void emptyValueToDefault ()
bool isDefault ()
Private Attributes
QCString m_value
QCString m_defValue
WidgetType m_widgetType
Additional Inherited Members
Detailed Description
Class representing a string type option.
Definition at line 183 of file configimpl.h.
Member Enumeration Documentation
WidgetType [1/2]
enum ConfigString::WidgetType
Enumerator
String
File
Dir
Image
FileAndDir
String
File
Dir
Image
FileAndDir
Definition at line 186 of file configimpl.h.
{ String, File, Dir, Image, FileAndDir };
WidgetType [2/2]
enum ConfigString::WidgetType
Enumerator
String
File
Dir
Image
FileAndDir
String
File
Dir
Image
FileAndDir
Definition at line 186 of file configimpl.h.
{ String, File, Dir, Image, FileAndDir };
Constructor & Destructor Documentation
ConfigString() [1/2]
ConfigString::ConfigString (const char * name, const char * doc) [inline]
Definition at line 187 of file configimpl.h.
      : ConfigOption(O_String)
    {
      m_name = name;
      m_doc = doc;
      m_widgetType = String;
    }
References ConfigOption::m_doc, ConfigOption::m_name, m_widgetType, ConfigOption::name(), and String.
 ConfigString() [1/2]
ConfigString::~ConfigString () [inline]
Definition at line 194 of file configimpl.h.
    {
    }
ConfigString() [2/2]
ConfigString::ConfigString (const char * name, const char * doc) [inline]
Definition at line 187 of file configimpl.h.
      : ConfigOption(O_String)
    {
      m_name = name;
      m_doc = doc;
      m_widgetType = String;
    }
References ConfigOption::m_doc, ConfigOption::m_name, m_widgetType, ConfigOption::name(), and String.
 ConfigString() [2/2]
ConfigString::~ConfigString () [inline]
Definition at line 194 of file configimpl.h.
    {
    }
Member Function Documentation
compareDoxyfile() [1/2]
void ConfigString::compareDoxyfile (TextStream & t, Config::CompareMode compareMode) [virtual]
Implements ConfigOption.
Definition at line 504 of file configimpl.l.
{
  if (!isDefault()) writeTemplate(t,TRUE,TRUE);
}
References isDefault(), TRUE, and writeTemplate().
compareDoxyfile() [2/2]
void ConfigString::compareDoxyfile (TextStream & t, Config::CompareMode compareMode) [virtual]
Implements ConfigOption.
emptyValueToDefault() [1/2]
void ConfigString::emptyValueToDefault () [inline], [virtual]
Reimplemented from ConfigOption.
Definition at line 206 of file configimpl.h.
{ if (m_value.isEmpty()) m_value=m_defValue; };
References QCString::isEmpty(), m_defValue, and m_value.
emptyValueToDefault() [2/2]
void ConfigString::emptyValueToDefault () [inline], [virtual]
Reimplemented from ConfigOption.
Definition at line 206 of file configimpl.h.
{ if (m_value.isEmpty()) m_value=m_defValue; };
References QCString::isEmpty(), m_defValue, and m_value.
init() [1/2]
void ConfigString::init () [inline], [virtual]
Reimplemented from ConfigOption.
Definition at line 205 of file configimpl.h.
{ m_value = m_defValue; }
References m_defValue, and m_value.
Referenced by Config::parse().
init() [2/2]
void ConfigString::init () [inline], [virtual]
Reimplemented from ConfigOption.
Definition at line 205 of file configimpl.h.
{ m_value = m_defValue; }
References m_defValue, and m_value.
isDefault() [1/2]
bool ConfigString::isDefault () [inline], [virtual]
Reimplemented from ConfigOption.
Definition at line 207 of file configimpl.h.
{ return m_value.stripWhiteSpace() == m_defValue.stripWhiteSpace(); }
References m_defValue, m_value, and QCString::stripWhiteSpace().
Referenced by compareDoxyfile(), and writeXMLDoxyfile().
isDefault() [2/2]
bool ConfigString::isDefault () [inline], [virtual]
Reimplemented from ConfigOption.
Definition at line 207 of file configimpl.h.
{ return m_value.stripWhiteSpace() == m_defValue.stripWhiteSpace(); }
References m_defValue, m_value, and QCString::stripWhiteSpace().
setDefaultValue() [1/2]
void ConfigString::setDefaultValue (const char * v) [inline]
Definition at line 199 of file configimpl.h.
{ m_defValue = v; }
References m_defValue.
setDefaultValue() [2/2]
void ConfigString::setDefaultValue (const char * v) [inline]
Definition at line 199 of file configimpl.h.
{ m_defValue = v; }
References m_defValue.
setWidgetType() [1/2]
void ConfigString::setWidgetType (WidgetType w) [inline]
Definition at line 197 of file configimpl.h.
{ m_widgetType = w; }
References m_widgetType, and w.
setWidgetType() [2/2]
void ConfigString::setWidgetType (WidgetType w) [inline]
Definition at line 197 of file configimpl.h.
{ m_widgetType = w; }
References m_widgetType, and w.
substEnvVars() [1/2]
void ConfigString::substEnvVars () [virtual]
Implements ConfigOption.
Definition at line 1474 of file configimpl.l.
{
  substEnvVarsInString(m_value);
}
References m_value, and substEnvVarsInString().
substEnvVars() [2/2]
void ConfigString::substEnvVars () [virtual]
Implements ConfigOption.
valueRef() [1/2]
QCString * ConfigString::valueRef () [inline]
Definition at line 200 of file configimpl.h.
{ return &m_value; }
References m_value.
Referenced by checkEncoding().
valueRef() [2/2]
QCString * ConfigString::valueRef () [inline]
Definition at line 200 of file configimpl.h.
{ return &m_value; }
References m_value.
widgetType() [1/2]
WidgetType ConfigString::widgetType () const [inline]
Definition at line 198 of file configimpl.h.
{ return m_widgetType; }
References m_widgetType.
widgetType() [2/2]
WidgetType ConfigString::widgetType () const [inline]
Definition at line 198 of file configimpl.h.
{ return m_widgetType; }
References m_widgetType.
writeTemplate() [1/2]
void ConfigString::writeTemplate (TextStream & t, bool sl, bool) [virtual]
Implements ConfigOption.
Definition at line 487 of file configimpl.l.
{
  if (!sl)
  {
    t << "\n";
    t << convertToComment(m_doc, m_userComment);
    t << "\n";
  }
  else if (!m_userComment.isEmpty())
  {
    t << convertToComment("", m_userComment);
  }
  t << m_name << m_spaces.left(MAX_OPTION_LENGTH-m_name.length()) << "=";
  writeStringValue(t,m_value);
  t << "\n";
}
References convertToComment(), QCString::isEmpty(), QCString::left(), QCString::length(), ConfigOption::m_doc, ConfigOption::m_name, ConfigOption::m_spaces, ConfigOption::m_userComment, m_value, ConfigOption::MAX_OPTION_LENGTH, caseconvert::sl, and ConfigOption::writeStringValue().
Referenced by compareDoxyfile().
writeTemplate() [2/2]
void ConfigString::writeTemplate (TextStream & t, bool sl, bool) [virtual]
Implements ConfigOption.
writeXMLDoxyfile() [1/2]
void ConfigString::writeXMLDoxyfile (TextStream & t) [virtual]
Implements ConfigOption.
Definition at line 509 of file configimpl.l.
{
  t << " <option id='" << m_name << "'";
  t << " default='" << (isDefault() ? "yes" : "no") << "'";
  t << " type='string'";
  t << ">";
  t << "<value>";
  t << "<![CDATA[";
  writeStringValue(t,m_value,false);
  t << "]]>";
  t << "</value>";
  t << "</option>\n";
}
References isDefault(), ConfigOption::m_name, m_value, and ConfigOption::writeStringValue().
writeXMLDoxyfile() [2/2]
void ConfigString::writeXMLDoxyfile (TextStream & t) [virtual]
Implements ConfigOption.
Member Data Documentation
m_defValue
QCString ConfigString::m_defValue [private]
Definition at line 211 of file configimpl.h.
Referenced by emptyValueToDefault(), init(), isDefault(), and setDefaultValue().
m_value
QCString ConfigString::m_value [private]
Definition at line 210 of file configimpl.h.
Referenced by emptyValueToDefault(), init(), isDefault(), substEnvVars(), valueRef(), writeTemplate(), and writeXMLDoxyfile().
m_widgetType
WidgetType ConfigString::m_widgetType [private]
Definition at line 212 of file configimpl.h.
Referenced by ConfigString(), setWidgetType(), and widgetType().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/configimpl.h
doxygen/src/configimpl.h
doxygen/build/doxygen/src/configimpl.l
doxygen/src/configimpl.l