VhdlDocGen Class Reference
#include <vhdldocgen.h>
Public Types
enum VhdlClasses {
ENTITYCLASS
, PACKBODYCLASS
, ARCHITECTURECLASS
, PACKAGECLASS
,
ENTITYCLASS
, PACKBODYCLASS
, ARCHITECTURECLASS
, PACKAGECLASS
 }
enum VhdlKeyWords {
LIBRARY =1
, ENTITY
, PACKAGE_BODY
, ARCHITECTURE
,
PACKAGE
, ATTRIBUTE
, SIGNAL
, COMPONENT
,
CONSTANT
, TYPE
, SUBTYPE
, FUNCTION
,
RECORD
, PROCEDURE
, USE
, PROCESS
,
PORT
, UNITS
, GENERIC
, INSTANTIATION
,
GROUP
, VFILE
, SHAREDVARIABLE
, CONFIG
,
ALIAS
, MISCELLANEOUS
, UCF_CONST
, LIBRARY =1
,
ENTITY
, PACKAGE_BODY
, ARCHITECTURE
, PACKAGE
,
ATTRIBUTE
, SIGNAL
, COMPONENT
, CONSTANT
,
TYPE
, SUBTYPE
, FUNCTION
, RECORD
,
PROCEDURE
, USE
, PROCESS
, PORT
,
UNITS
, GENERIC
, INSTANTIATION
, GROUP
,
VFILE
, SHAREDVARIABLE
, CONFIG
, ALIAS
,
MISCELLANEOUS
, UCF_CONST
 }
enum VhdlClasses {
ENTITYCLASS
, PACKBODYCLASS
, ARCHITECTURECLASS
, PACKAGECLASS
,
ENTITYCLASS
, PACKBODYCLASS
, ARCHITECTURECLASS
, PACKAGECLASS
 }
enum VhdlKeyWords {
LIBRARY =1
, ENTITY
, PACKAGE_BODY
, ARCHITECTURE
,
PACKAGE
, ATTRIBUTE
, SIGNAL
, COMPONENT
,
CONSTANT
, TYPE
, SUBTYPE
, FUNCTION
,
RECORD
, PROCEDURE
, USE
, PROCESS
,
PORT
, UNITS
, GENERIC
, INSTANTIATION
,
GROUP
, VFILE
, SHAREDVARIABLE
, CONFIG
,
ALIAS
, MISCELLANEOUS
, UCF_CONST
, LIBRARY =1
,
ENTITY
, PACKAGE_BODY
, ARCHITECTURE
, PACKAGE
,
ATTRIBUTE
, SIGNAL
, COMPONENT
, CONSTANT
,
TYPE
, SUBTYPE
, FUNCTION
, RECORD
,
PROCEDURE
, USE
, PROCESS
, PORT
,
UNITS
, GENERIC
, INSTANTIATION
, GROUP
,
VFILE
, SHAREDVARIABLE
, CONFIG
, ALIAS
,
MISCELLANEOUS
, UCF_CONST
 }
Public Member Functions
VhdlDocGen ()
virtual ~VhdlDocGen ()
VhdlDocGen ()
virtual ~VhdlDocGen ()
Static Public Member Functions
static VhdlClasses convert (Protection prot)
static void init ()
static QCString convertFileNameToClassName (QCString name)
static bool isSubClass (ClassDef *cd, ClassDef *scd, bool followInstances, int level)
static QCString getIndexWord (const QCString &, int index)
static bool deleteCharRev (QCString &s, char c)
static void deleteAllChars (QCString &s, char c)
static void parseFuncProto (const QCString &text, QCString &name, QCString &ret, bool doc=false)
static void computeVhdlComponentRelations ()
static const char * findKeyWord (const QCString &word)
static ClassDef * getPackageName (const QCString &name)
static const MemberDef * findMember (const QCString &className, const QCString &memName)
static void findAllPackages (ClassDef *)
static const MemberDef * findMemberDef (ClassDef *cd, const QCString &key, MemberListType type)
static ClassDef * getClass (const QCString &name)
static const MemberDef * findFunction (const QCString &name, const QCString &package)
static QCString getClassTitle (const ClassDef *)
static void writeInlineClassLink (const ClassDef *, OutputList &ol)
static void writeTagFile (MemberDefMutable *mdef, TextStream &tagFile)
static bool isConstraint (const MemberDef *mdef)
static bool isConfig (const MemberDef *mdef)
static bool isAlias (const MemberDef *mdef)
static bool isLibrary (const MemberDef *mdef)
static bool isGeneric (const MemberDef *mdef)
static bool isPort (const MemberDef *mdef)
static bool isComponent (const MemberDef *mdef)
static bool isPackage (const MemberDef *mdef)
static bool isEntity (const MemberDef *mdef)
static bool isConstant (const MemberDef *mdef)
static bool isVType (const MemberDef *mdef)
static bool isSubType (const MemberDef *mdef)
static bool isVhdlFunction (const MemberDef *mdef)
static bool isProcess (const MemberDef *mdef)
static bool isSignal (const MemberDef *mdef)
static bool isAttribute (const MemberDef *mdef)
static bool isSignals (const MemberDef *mdef)
static bool isProcedure (const MemberDef *mdef)
static bool isRecord (const MemberDef *mdef)
static bool isArchitecture (const MemberDef *mdef)
static bool isUnit (const MemberDef *mdef)
static bool isPackageBody (const MemberDef *mdef)
static bool isVariable (const MemberDef *mdef)
static bool isFile (const MemberDef *mdef)
static bool isGroup (const MemberDef *mdef)
static bool isCompInst (const MemberDef *mdef)
static bool isMisc (const MemberDef *mdef)
static void prepareComment (QCString &)
static void formatString (const QCString &, OutputList &ol, const MemberDef *)
static void writeFormatString (const QCString &, OutputList &ol, const MemberDef *)
static void writeFunctionProto (OutputList &ol, const ArgumentList &al, const MemberDef *)
static void writeProcessProto (OutputList &ol, const ArgumentList &al, const MemberDef *)
static void writeProcedureProto (OutputList &ol, const ArgumentList &al, const MemberDef *)
static bool writeFuncProcDocu (const MemberDef *mdef, OutputList &ol, const ArgumentList &al, bool type=false)
static void writeRecordProto (const MemberDef *mdef, OutputList &ol, const ArgumentList &al)
static bool writeVHDLTypeDocumentation (const MemberDef *mdef, const Definition *d, OutputList &ol)
static void writeVhdlDeclarations (const MemberList *, OutputList &, const GroupDef *, const ClassDef *, const FileDef *, const NamespaceDef *)
static void writeVHDLDeclaration (const MemberDefMutable *mdef, OutputList &ol, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd, bool inGroup)
static void writePlainVHDLDeclarations (const MemberList *ml, OutputList &ol, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd, uint64_t specifier)
static void writeVHDLDeclarations (const MemberList *ml, OutputList &ol, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd, const QCString &title, const QCString &subtitle, bool showEnumValues, int type)
static bool writeClassType (const ClassDef *, OutputList &ol, QCString &cname)
static QCString convertArgumentListToString (const ArgumentList &al, bool f)
static QCString getProcessNumber ()
static QCString getRecordNumber ()
static QCString getClassName (const ClassDef *)
static bool isNumber (const std::string &s)
static QCString getProtectionName (int prot)
static void parseUCF (const char *input, Entry *entity, const QCString &f, bool vendor)
static const ClassDef * findArchitecture (const ClassDef *cd)
static void correctMemberProperties (MemberDefMutable *md)
static void writeSource (const MemberDefMutable *mdef, OutputList &ol, const QCString &cname)
static QCString parseForConfig (QCString &entity, QCString &arch)
static QCString parseForBinding (QCString &entity, QCString &arch)
static void addBaseClass (ClassDef *cd, ClassDef *ent)
static ClassDef * findVhdlClass (const QCString &className)
static void writeOverview (OutputList &ol)
static void writeOverview ()
static void createFlowChart (const MemberDef *)
static void setFlowMember (const MemberDef *flowMember)
static const MemberDef * getFlowMember ()
static bool isVhdlClass (const Entry *cu)
static void resetCodeVhdlParserState ()
static VhdlClasses convert (Protection prot)
static void init ()
static QCString convertFileNameToClassName (QCString name)
static bool isSubClass (ClassDef *cd, ClassDef *scd, bool followInstances, int level)
static QCString getIndexWord (const QCString &, int index)
static bool deleteCharRev (QCString &s, char c)
static void deleteAllChars (QCString &s, char c)
static void parseFuncProto (const QCString &text, QCString &name, QCString &ret, bool doc=false)
static void computeVhdlComponentRelations ()
static const char * findKeyWord (const QCString &word)
static ClassDef * getPackageName (const QCString &name)
static const MemberDef * findMember (const QCString &className, const QCString &memName)
static void findAllPackages (ClassDef *)
static const MemberDef * findMemberDef (ClassDef *cd, const QCString &key, MemberListType type)
static ClassDef * getClass (const QCString &name)
static const MemberDef * findFunction (const QCString &name, const QCString &package)
static QCString getClassTitle (const ClassDef *)
static void writeInlineClassLink (const ClassDef *, OutputList &ol)
static void writeTagFile (MemberDefMutable *mdef, TextStream &tagFile)
static bool isConstraint (const MemberDef *mdef)
static bool isConfig (const MemberDef *mdef)
static bool isAlias (const MemberDef *mdef)
static bool isLibrary (const MemberDef *mdef)
static bool isGeneric (const MemberDef *mdef)
static bool isPort (const MemberDef *mdef)
static bool isComponent (const MemberDef *mdef)
static bool isPackage (const MemberDef *mdef)
static bool isEntity (const MemberDef *mdef)
static bool isConstant (const MemberDef *mdef)
static bool isVType (const MemberDef *mdef)
static bool isSubType (const MemberDef *mdef)
static bool isVhdlFunction (const MemberDef *mdef)
static bool isProcess (const MemberDef *mdef)
static bool isSignal (const MemberDef *mdef)
static bool isAttribute (const MemberDef *mdef)
static bool isSignals (const MemberDef *mdef)
static bool isProcedure (const MemberDef *mdef)
static bool isRecord (const MemberDef *mdef)
static bool isArchitecture (const MemberDef *mdef)
static bool isUnit (const MemberDef *mdef)
static bool isPackageBody (const MemberDef *mdef)
static bool isVariable (const MemberDef *mdef)
static bool isFile (const MemberDef *mdef)
static bool isGroup (const MemberDef *mdef)
static bool isCompInst (const MemberDef *mdef)
static bool isMisc (const MemberDef *mdef)
static void prepareComment (QCString &)
static void formatString (const QCString &, OutputList &ol, const MemberDef *)
static void writeFormatString (const QCString &, OutputList &ol, const MemberDef *)
static void writeFunctionProto (OutputList &ol, const ArgumentList &al, const MemberDef *)
static void writeProcessProto (OutputList &ol, const ArgumentList &al, const MemberDef *)
static void writeProcedureProto (OutputList &ol, const ArgumentList &al, const MemberDef *)
static bool writeFuncProcDocu (const MemberDef *mdef, OutputList &ol, const ArgumentList &al, bool type=false)
static void writeRecordProto (const MemberDef *mdef, OutputList &ol, const ArgumentList &al)
static bool writeVHDLTypeDocumentation (const MemberDef *mdef, const Definition *d, OutputList &ol)
static void writeVhdlDeclarations (const MemberList *, OutputList &, const GroupDef *, const ClassDef *, const FileDef *, const NamespaceDef *)
static void writeVHDLDeclaration (const MemberDefMutable *mdef, OutputList &ol, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd, bool inGroup)
static void writePlainVHDLDeclarations (const MemberList *ml, OutputList &ol, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd, uint64_t specifier)
static void writeVHDLDeclarations (const MemberList *ml, OutputList &ol, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd, const QCString &title, const QCString &subtitle, bool showEnumValues, int type)
static bool writeClassType (const ClassDef *, OutputList &ol, QCString &cname)
static QCString convertArgumentListToString (const ArgumentList &al, bool f)
static QCString getProcessNumber ()
static QCString getRecordNumber ()
static QCString getClassName (const ClassDef *)
static bool isNumber (const std::string &s)
static QCString getProtectionName (int prot)
static void parseUCF (const char *input, Entry *entity, const QCString &f, bool vendor)
static const ClassDef * findArchitecture (const ClassDef *cd)
static void correctMemberProperties (MemberDefMutable *md)
static void writeSource (const MemberDefMutable *mdef, OutputList &ol, const QCString &cname)
static QCString parseForConfig (QCString &entity, QCString &arch)
static QCString parseForBinding (QCString &entity, QCString &arch)
static void addBaseClass (ClassDef *cd, ClassDef *ent)
static ClassDef * findVhdlClass (const QCString &className)
static void writeOverview (OutputList &ol)
static void writeOverview ()
static void createFlowChart (const MemberDef *)
static void setFlowMember (const MemberDef *flowMember)
static const MemberDef * getFlowMember ()
static bool isVhdlClass (const Entry *cu)
static void resetCodeVhdlParserState ()
Static Private Member Functions
static void findAllArchitectures (std::vector< QCString > &ql, const ClassDef *cd)
static bool compareArgList (const ArgumentList &, const ArgumentList &)
static void writeVhdlLink (const ClassDef *cdd, OutputList &ol, QCString &type, QCString &name, QCString &beh)
static void writeStringLink (const MemberDef *mdef, QCString mem, OutputList &ol)
static void writeRecUnitDocu (const MemberDef *md, OutputList &ol, QCString largs)
static void writeRecordUnit (QCString &largs, QCString &ltype, OutputList &ol, const MemberDefMutable *mdef)
static void findAllArchitectures (std::vector< QCString > &ql, const ClassDef *cd)
static bool compareArgList (const ArgumentList &, const ArgumentList &)
static void writeVhdlLink (const ClassDef *cdd, OutputList &ol, QCString &type, QCString &name, QCString &beh)
static void writeStringLink (const MemberDef *mdef, QCString mem, OutputList &ol)
static void writeRecUnitDocu (const MemberDef *md, OutputList &ol, QCString largs)
static void writeRecordUnit (QCString &largs, QCString &ltype, OutputList &ol, const MemberDefMutable *mdef)
Detailed Description
Class for generating documentation specific for VHDL
Definition at line 68 of file vhdldocgen.h.
Member Enumeration Documentation
VhdlClasses [1/2]
enum VhdlDocGen::VhdlClasses
Enumerator
ENTITYCLASS
PACKBODYCLASS
ARCHITECTURECLASS
PACKAGECLASS
ENTITYCLASS
PACKBODYCLASS
ARCHITECTURECLASS
PACKAGECLASS
Definition at line 72 of file vhdldocgen.h.
    {
      ENTITYCLASS, // Overlays: Public
      PACKBODYCLASS, // Overlays: Protected
      ARCHITECTURECLASS, // Overlays: Private
      PACKAGECLASS // Overlays: Package
    };
VhdlClasses [2/2]
enum VhdlDocGen::VhdlClasses
Enumerator
ENTITYCLASS
PACKBODYCLASS
ARCHITECTURECLASS
PACKAGECLASS
ENTITYCLASS
PACKBODYCLASS
ARCHITECTURECLASS
PACKAGECLASS
Definition at line 72 of file vhdldocgen.h.
    {
      ENTITYCLASS, // Overlays: Public
      PACKBODYCLASS, // Overlays: Protected
      ARCHITECTURECLASS, // Overlays: Private
      PACKAGECLASS // Overlays: Package
    };
VhdlKeyWords [1/2]
enum VhdlDocGen::VhdlKeyWords
Enumerator
LIBRARY
ENTITY
PACKAGE_BODY
ARCHITECTURE
PACKAGE
ATTRIBUTE
SIGNAL
COMPONENT
CONSTANT
TYPE
SUBTYPE
FUNCTION
RECORD
PROCEDURE
USE
PROCESS
PORT
UNITS
GENERIC
INSTANTIATION
GROUP
VFILE
SHAREDVARIABLE
CONFIG
ALIAS
MISCELLANEOUS
UCF_CONST
LIBRARY
ENTITY
PACKAGE_BODY
ARCHITECTURE
PACKAGE
ATTRIBUTE
SIGNAL
COMPONENT
CONSTANT
TYPE
SUBTYPE
FUNCTION
RECORD
PROCEDURE
USE
PROCESS
PORT
UNITS
GENERIC
INSTANTIATION
GROUP
VFILE
SHAREDVARIABLE
CONFIG
ALIAS
MISCELLANEOUS
UCF_CONST
Definition at line 91 of file vhdldocgen.h.
    {
      LIBRARY=1,
      ENTITY,
      PACKAGE_BODY,
      ARCHITECTURE,
      PACKAGE,
      ATTRIBUTE,
      SIGNAL,
      COMPONENT,
      CONSTANT,
      TYPE,
      SUBTYPE,
      FUNCTION,
      RECORD,
      PROCEDURE,
      USE,
      PROCESS,
      PORT,
      UNITS,
      GENERIC,
      INSTANTIATION,
      GROUP,
      VFILE,
      SHAREDVARIABLE,
      CONFIG,
      ALIAS,
      MISCELLANEOUS,
      UCF_CONST
    };
VhdlKeyWords [2/2]
enum VhdlDocGen::VhdlKeyWords
Enumerator
LIBRARY
ENTITY
PACKAGE_BODY
ARCHITECTURE
PACKAGE
ATTRIBUTE
SIGNAL
COMPONENT
CONSTANT
TYPE
SUBTYPE
FUNCTION
RECORD
PROCEDURE
USE
PROCESS
PORT
UNITS
GENERIC
INSTANTIATION
GROUP
VFILE
SHAREDVARIABLE
CONFIG
ALIAS
MISCELLANEOUS
UCF_CONST
LIBRARY
ENTITY
PACKAGE_BODY
ARCHITECTURE
PACKAGE
ATTRIBUTE
SIGNAL
COMPONENT
CONSTANT
TYPE
SUBTYPE
FUNCTION
RECORD
PROCEDURE
USE
PROCESS
PORT
UNITS
GENERIC
INSTANTIATION
GROUP
VFILE
SHAREDVARIABLE
CONFIG
ALIAS
MISCELLANEOUS
UCF_CONST
Definition at line 91 of file vhdldocgen.h.
    {
      LIBRARY=1,
      ENTITY,
      PACKAGE_BODY,
      ARCHITECTURE,
      PACKAGE,
      ATTRIBUTE,
      SIGNAL,
      COMPONENT,
      CONSTANT,
      TYPE,
      SUBTYPE,
      FUNCTION,
      RECORD,
      PROCEDURE,
      USE,
      PROCESS,
      PORT,
      UNITS,
      GENERIC,
      INSTANTIATION,
      GROUP,
      VFILE,
      SHAREDVARIABLE,
      CONFIG,
      ALIAS,
      MISCELLANEOUS,
      UCF_CONST
    };
Constructor & Destructor Documentation
VhdlDocGen() [1/2]
VhdlDocGen::VhdlDocGen ()
Definition at line 497 of file vhdldocgen.cpp.
{
}
 VhdlDocGen() [1/2]
VhdlDocGen::~VhdlDocGen () [virtual]
Definition at line 501 of file vhdldocgen.cpp.
{
}
VhdlDocGen() [2/2]
VhdlDocGen::VhdlDocGen ()
 VhdlDocGen() [2/2]
virtual VhdlDocGen::~VhdlDocGen () [virtual]
Member Function Documentation
addBaseClass() [1/2]
void VhdlDocGen::addBaseClass (ClassDef * cd, ClassDef * ent) [static]
Definition at line 2698 of file vhdldocgen.cpp.
{
  BaseClassList bcl = cd->baseClasses();
  for (auto &bcd : bcl)
  {
    ClassDef *ccd = bcd.classDef;
    if (ccd==ent)
    {
      QCString n = bcd.usedName;
      int i = n.find('(');
      if(i<0)
      {
        bcd.usedName.append("(2)");
        return;
      }
      static const reg::Ex reg(R"(\d+)");
      QCString s=n.left(i);
      QCString r=n.right(n.length()-i);
      std::string t=r.str();
      VhdlDocGen::deleteAllChars(r,')');
      VhdlDocGen::deleteAllChars(r,'(');
      r.setNum(r.toInt()+1);
      reg::replace(t, reg, r.str());
      s.append(t.c_str());
      bcd.usedName=s;
      bcd.templSpecifiers=t;
    }
  }
  cd->updateBaseClasses(bcl);
}
References ClassDef::baseClasses(), deleteAllChars(), n, r, reg::replace(), s, string, and ClassDef::updateBaseClasses().
Referenced by addInstance().
addBaseClass() [2/2]
static void VhdlDocGen::addBaseClass (ClassDef * cd, ClassDef * ent) [static]
compareArgList() [1/2]
static bool VhdlDocGen::compareArgList (const ArgumentList & , const ArgumentList &) [static], [private]
compareArgList() [2/2]
static bool VhdlDocGen::compareArgList (const ArgumentList & , const ArgumentList &) [static], [private]
computeVhdlComponentRelations() [1/2]
void VhdlDocGen::computeVhdlComponentRelations () [static]
Definition at line 2500 of file vhdldocgen.cpp.
{
  QCString entity,arch,inst;
  for (const auto &cur : getVhdlInstList())
  {
    if (cur->stat) // was bind
    {
      continue;
    }
    if (cur->includeName=="entity" || cur->includeName=="component")
    {
      entity=cur->includeName+" "+cur->type;
      QCString rr=VhdlDocGen::parseForBinding(entity,arch);
    }
    else if (cur->includeName.isEmpty())
    {
      entity=cur->type;
    }
    ClassDefMutable *classEntity= toClassDefMutable(VhdlDocGen::findVhdlClass(entity));
    inst=VhdlDocGen::getIndexWord(cur->args,0);
    ClassDefMutable *cd=toClassDefMutable(Doxygen::classLinkedMap->find(inst));
    ClassDefMutable *ar=toClassDefMutable(Doxygen::classLinkedMap->find(cur->args));
    if (cd==0)
    {
      continue;
    }
    // if (classEntity==0)
    // err("%s:%d:Entity:%s%s",qPrint(cur->fileName),cur->startLine,qPrint(entity)," could not be found");
    addInstance(classEntity,ar,cd,cur);
  }
}
References addInstance(), Doxygen::classLinkedMap, findVhdlClass(), getIndexWord(), getVhdlInstList(), parseForBinding(), and toClassDefMutable().
Referenced by parseInput().
computeVhdlComponentRelations() [2/2]
static void VhdlDocGen::computeVhdlComponentRelations () [static]
convert() [1/2]
static VhdlClasses VhdlDocGen::convert (Protection prot) [inline], [static]
Definition at line 79 of file vhdldocgen.h.
    {
      switch (prot)
      {
        case Public: return ENTITYCLASS;
        case Protected: return PACKBODYCLASS;
        case Private: return ARCHITECTURECLASS;
        case Package: return PACKAGECLASS;
      }
      return ENTITYCLASS;
    }
References ARCHITECTURECLASS, ENTITYCLASS, Package, PACKAGECLASS, PACKBODYCLASS, Private, Protected, and Public.
Referenced by NestingContext::Private::addClass(), ClassListContext::Private::addClasses(), NestingContext::Private::addClassHierarchy(), DotGfxHierarchyTable::addClassList(), NestingContext::Private::addDerivedClasses(), ClassIndexContext::Private::createClasses(), findMember(), getClassName(), writeAlphabeticalClassList(), writeAnnotatedClassList(), writeClassTree(), writeClassTreeForList(), writeClassTreeToOutput(), ClassDefImpl::writeDeclarationLink(), writeInlineClassLink(), writeOverview(), and writeVHDLDeclaration().
convert() [2/2]
static VhdlClasses VhdlDocGen::convert (Protection prot) [inline], [static]
Definition at line 79 of file vhdldocgen.h.
    {
      switch (prot)
      {
        case Public: return ENTITYCLASS;
        case Protected: return PACKBODYCLASS;
        case Private: return ARCHITECTURECLASS;
        case Package: return PACKAGECLASS;
      }
      return ENTITYCLASS;
    }
References ARCHITECTURECLASS, ENTITYCLASS, Package, PACKAGECLASS, PACKBODYCLASS, Private, Protected, and Public.
convertArgumentListToString() [1/2]
QCString VhdlDocGen::convertArgumentListToString (const ArgumentList & al, bool f) [static]
Definition at line 1511 of file vhdldocgen.cpp.
{
  QCString argString;
  bool sem=FALSE;
  for (const Argument &arg : al)
  {
    if (sem) argString.append(", ");
    if (func)
    {
      argString+=arg.name;
      argString+=":";
      argString+=arg.type;
    }
    else
    {
      argString+=arg.defval+" ";
      argString+=arg.name+" :";
      argString+=arg.attrib+" ";
      argString+=arg.type;
    }
    sem=TRUE;
  }
  return argString;
}
References QCString::append(), FALSE, docstring::func(), and TRUE.
Referenced by writeTagFile().
convertArgumentListToString() [2/2]
static QCString VhdlDocGen::convertArgumentListToString (const ArgumentList & al, bool f) [static]
convertFileNameToClassName() [1/2]
QCString VhdlDocGen::convertFileNameToClassName (QCString name) [static]
Definition at line 2244 of file vhdldocgen.cpp.
{
  QCString n=name;
  n=n.remove(0,6);
  int i=0;
  while((i=n.find("__"))>0)
  {
    n=n.remove(i,1);
  }
  while((i=n.find("_1"))>0)
  {
    n=n.replace(i,2,":");
  }
  return n;
}
References n, and setup::name.
convertFileNameToClassName() [2/2]
static QCString VhdlDocGen::convertFileNameToClassName (QCString name) [static]
correctMemberProperties() [1/2]
void VhdlDocGen::correctMemberProperties (MemberDefMutable * md) [static]
Definition at line 1569 of file vhdldocgen.cpp.
{
  if (md->argsString()=="package")
  {
    md->setMemberSpecifiers(VhdlDocGen::INSTANTIATION);
  }
  else if (md->argsString()=="configuration")
  {
    md->setMemberSpecifiers(VhdlDocGen::CONFIG);
  }
  else if (md->typeString()=="library")
  {
    md->setMemberSpecifiers(VhdlDocGen::LIBRARY);
  }
  else if (md->typeString()=="use")
  {
    md->setMemberSpecifiers(VhdlDocGen::USE);
  }
  else if (md->typeString().lower()=="misc")
  {
    md->setMemberSpecifiers(VhdlDocGen::MISCELLANEOUS);
  }
  else if (md->typeString().lower()=="ucf_const")
  {
    md->setMemberSpecifiers(VhdlDocGen::UCF_CONST);
  }
  if (md->getMemberSpecifiers()==VhdlDocGen::UCF_CONST)
  {
    int mm=md->name().findRev('_');
    if (mm>0)
    {
      md->setName(md->name().left(mm));
    }
  }
  else if (md->getMemberSpecifiers()==VhdlDocGen::TYPE)
  {
    QCString largs=md->argsString();
    bool bRec=largs.stripPrefix("record") ;
    bool bUnit=largs.stripPrefix("units") ;
    if (bRec || bUnit)
    {
      md->setType("");
    }
  }
}
References MemberDef::argsString(), CONFIG, QCString::findRev(), MemberDef::getMemberSpecifiers(), INSTANTIATION, QCString::left(), LIBRARY, QCString::lower(), MISCELLANEOUS, Definition::name(), MemberDefMutable::setMemberSpecifiers(), DefinitionMutable::setName(), MemberDefMutable::setType(), QCString::stripPrefix(), TYPE, MemberDef::typeString(), UCF_CONST, and USE.
Referenced by vhdlCorrectMemberProperties().
correctMemberProperties() [2/2]
static void VhdlDocGen::correctMemberProperties (MemberDefMutable * md) [static]
createFlowChart() [1/2]
void VhdlDocGen::createFlowChart (const MemberDef * mdef) [static]
Definition at line 2744 of file vhdldocgen.cpp.
{
  if (mdef==0) return;
  QCString codeFragment;
  const MemberDef* mm=0;
  if ((mm=findMemFlow(mdef))!=0)
  {
    // don't create the same flowchart twice
    VhdlDocGen::setFlowMember(mm);
    return;
  }
  else
  {
    mdList.push_back(mdef);
  }
  //fprintf(stderr,"\n create flow mem %s %p\n",qPrint(mdef->name()),mdef);
  int actualStart= mdef->getStartBodyLine();
  int actualEnd=mdef->getEndBodyLine();
  const FileDef* fd=mdef->getFileDef();
  bool b=readCodeFragment(fd->absFilePath(), actualStart,actualEnd,codeFragment);
  if (!b) return;
  auto parser { Doxygen::parserManager->getOutlineParser(".vhd") };
  VhdlDocGen::setFlowMember(mdef);
  std::shared_ptr<Entry> root = std::make_shared<Entry>();
  StringVector filesInSameTu;
  parser->parseInput("",codeFragment.data(),root,nullptr);
}
References FileDef::absFilePath(), b, QCString::data(), findMemFlow(), Definition::getEndBodyLine(), MemberDef::getFileDef(), ParserManager::getOutlineParser(), Definition::getStartBodyLine(), mdList, Doxygen::parserManager, readCodeFragment(), and setFlowMember().
Referenced by DocVhdlFlow::parse().
createFlowChart() [2/2]
static void VhdlDocGen::createFlowChart (const MemberDef *) [static]
deleteAllChars() [1/2]
void VhdlDocGen::deleteAllChars (QCString & s, char c) [static]
Definition at line 1084 of file vhdldocgen.cpp.
{
  int index=s.findRev(c,-1,FALSE);
  while (index > -1)
  {
    QCString qcs=s.remove(index,1);
    s=qcs;
    index=s.findRev(c,-1,FALSE);
  }
}
References c, FALSE, and s.
Referenced by addBaseClass(), VHDLOutlineParser::createFunction(), vhdl::parser::VhdlParser::full_type_declaration(), and initUCF().
deleteAllChars() [2/2]
static void VhdlDocGen::deleteAllChars (QCString & s, char c) [static]
deleteCharRev() [1/2]
bool VhdlDocGen::deleteCharRev (QCString & s, char c) [static]
deletes a char backwards in a string
Definition at line 1072 of file vhdldocgen.cpp.
{
  int index=s.findRev(c,-1,FALSE);
  if (index > -1)
  {
    QCString qcs=s.remove(index,1);
    s=qcs;
    return TRUE;
  }
  return FALSE;
}
References c, FALSE, s, and TRUE.
Referenced by parseFuncProto().
deleteCharRev() [2/2]
static bool VhdlDocGen::deleteCharRev (QCString & s, char c) [static]
findAllArchitectures() [1/2]
void VhdlDocGen::findAllArchitectures (std::vector< QCString > & ql, const ClassDef * cd) [static], [private]
Definition at line 905 of file vhdldocgen.cpp.
{
  for (const auto &citer : *Doxygen::classLinkedMap)
  {
    QCString className=citer->className();
    int pos;
    if (cd != citer.get() && (pos=className.find('-'))!=-1)
    {
      QCString postfix=className.mid(pos+1);
      if (qstricmp(cd->className(),postfix)==0)
      {
        qll.push_back(className);
      }
    }
  }// for
}//findAllArchitectures
References Doxygen::classLinkedMap, ClassDef::className(), QCString::find(), QCString::mid(), and qstricmp().
Referenced by writeInlineClassLink().
findAllArchitectures() [2/2]
static void VhdlDocGen::findAllArchitectures (std::vector< QCString > & ql, const ClassDef * cd) [static], [private]
findAllPackages() [1/2]
void VhdlDocGen::findAllPackages (ClassDef * cdef) [static]
finds all included packages of an Entity or Package
Definition at line 740 of file vhdldocgen.cpp.
{
  if (g_packages.find(cdef)!=g_packages.end()) return;
  std::vector<ClassDef*> cList;
  MemberList *mem=cdef->getMemberList(MemberListType_variableMembers);
  if (mem)
  {
    for (const auto &md : *mem)
    {
      if (VhdlDocGen::isPackage(md))
      {
        ClassDef* cd=VhdlDocGen::getPackageName(md->name());
        if (cd)
        {
          cList.push_back(cd);
          VhdlDocGen::findAllPackages(cd);
          g_packages.insert({cdef,cList});
        }
      }
    }//for
  }
}// findAllPackages
References findAllPackages(), g_packages, ClassDef::getMemberList(), getPackageName(), isPackage(), and MemberListType_variableMembers.
Referenced by findAllPackages(), and findMember().
findAllPackages() [2/2]
static void VhdlDocGen::findAllPackages (ClassDef *) [static]
findArchitecture() [1/2]
const ClassDef * VhdlDocGen::findArchitecture (const ClassDef * cd) [static]
Definition at line 922 of file vhdldocgen.cpp.
{
  QCString nn=cd->name();
  for (const auto &citer : *Doxygen::classLinkedMap)
  {
    QCString jj=citer->name();
    StringVector ql=split(jj.str(),":");
    if (ql.size()>1)
    {
      if (QCString(ql[0])==nn)
      {
        return citer.get();
      }
    }
  }
  return 0;
}
References Doxygen::classLinkedMap, Definition::name(), split(), and QCString::str().
findArchitecture() [2/2]
static const ClassDef * VhdlDocGen::findArchitecture (const ClassDef * cd) [static]
findFunction() [1/2]
const MemberDef * VhdlDocGen::findFunction (const QCString & funcname, const QCString & package) [static]
returns the function with the matching argument list is called in vhdlcode.l
Definition at line 769 of file vhdldocgen.cpp.
{
  ClassDef *cdef=getClass(package);
  if (cdef==0) return 0;
  MemberList *mem=cdef->getMemberList(MemberListType_pubMethods);
  if (mem)
  {
    for (const auto &mdef : *mem)
    {
      QCString mname=mdef->name();
      if ((VhdlDocGen::isProcedure(mdef) || VhdlDocGen::isVhdlFunction(mdef)) && (compareString(funcname,mname)==0))
      {
        return mdef;
      }//if
    }//for
  }//if
  return 0;
} //findFunction
References compareString(), getClass(), ClassDef::getMemberList(), isProcedure(), isVhdlFunction(), and MemberListType_pubMethods.
Referenced by writeFuncProto().
findFunction() [2/2]
static const MemberDef * VhdlDocGen::findFunction (const QCString & name, const QCString & package) [static]
findKeyWord() [1/2]
const char * VhdlDocGen::findKeyWord (const QCString & kw) [static]
returns the color of a keyword
Definition at line 561 of file vhdldocgen.cpp.
{
  std::string word=kw.lower().str();
  if (word.empty()) return 0;
  if (g_vhdlKeyWordSet0.find(word)!=g_vhdlKeyWordSet0.end())
    return "keywordflow";
  if (g_vhdlKeyWordSet1.find(word)!=g_vhdlKeyWordSet1.end())
    return "keywordtype";
  if (g_vhdlKeyWordSet2.find(word)!=g_vhdlKeyWordSet2.end())
    return "vhdllogic";
  if (g_vhdlKeyWordSet3.find(word)!=g_vhdlKeyWordSet3.end())
    return "vhdlkeyword";
  return 0;
}
References g_vhdlKeyWordSet0, g_vhdlKeyWordSet1, g_vhdlKeyWordSet2, g_vhdlKeyWordSet3, QCString::lower(), QCString::str(), string, and word.
Referenced by writeColoredWord(), writeFormatString(), writeFunctionProto(), and writeProcedureProto().
findKeyWord() [2/2]
static const char * VhdlDocGen::findKeyWord (const QCString & word) [static]
findMember() [1/2]
const MemberDef * VhdlDocGen::findMember (const QCString & className, const QCString & memName) [static]
Definition at line 597 of file vhdldocgen.cpp.
{
  ClassDef* cd,*ecd=0;
  const MemberDef *mdef=0;
  cd=getClass(className);
  //printf("VhdlDocGen::findMember(%s,%s)=%p\n",qPrint(className),qPrint(memName),cd);
  if (cd==0) return 0;
  mdef=VhdlDocGen::findMemberDef(cd,memName,MemberListType_variableMembers);
  if (mdef) return mdef;
  mdef=VhdlDocGen::findMemberDef(cd,memName,MemberListType_pubMethods);
  if (mdef) return mdef;
  // nothing found so far
  // if we are an architecture or package body search in entity
  if (VhdlDocGen::convert(cd->protection())==VhdlDocGen::ARCHITECTURECLASS ||
      VhdlDocGen::convert(cd->protection())==VhdlDocGen::PACKBODYCLASS)
  {
    Definition *d = cd->getOuterScope();
    // searching upper/lower case names
    QCString tt=d->name();
    ecd =getClass(tt);
    if (!ecd)
    {
      tt=tt.upper();
      ecd =getClass(tt);
    }
    if (!ecd)
    {
      tt=tt.lower();
      ecd =getClass(tt);
    }
    if (ecd) //d && d->definitionType()==Definition::TypeClass)
    {
      //ClassDef *ecd = (ClassDef*)d;
      mdef=VhdlDocGen::findMemberDef(ecd,memName,MemberListType_variableMembers);
      if (mdef) return mdef;
      mdef=VhdlDocGen::findMemberDef(cd,memName,MemberListType_pubMethods);
      if (mdef) return mdef;
    }
   }
  if (VhdlDocGen::convert(cd->protection())==VhdlDocGen::ARCHITECTURECLASS ||
      VhdlDocGen::convert(cd->protection())==VhdlDocGen::PACKBODYCLASS)
  {
    Definition *d = cd->getOuterScope();
    QCString tt=d->name();
    ClassDef *acd =getClass(tt);
    if (!acd)
    {
      tt=tt.upper();
      acd =getClass(tt);
    }
    if (!acd)
    {
      tt=tt.lower();
      acd =getClass(tt);
    }
    if (acd) //d && d->definitionType()==Definition::TypeClass)
    {
      if(g_packages.find(acd)==g_packages.end())
      {
        VhdlDocGen::findAllPackages(acd);
      }
    }
  }
  else
  {
    ecd=cd;
    if (g_packages.find(ecd)==g_packages.end()) VhdlDocGen::findAllPackages(ecd);
  }
  if (ecd)
  {
    auto cList_it = g_packages.find(ecd);
    if (cList_it!=g_packages.end())
    {
      for (const auto &cdp : cList_it->second)
      {
        mdef=VhdlDocGen::findMemberDef(cdp,memName,MemberListType_variableMembers);
        if (mdef) return mdef;
        mdef=VhdlDocGen::findMemberDef(cdp,memName,MemberListType_pubMethods);
        if (mdef) return mdef;
      }
    }
  }
  return 0;
}//findMember
References ARCHITECTURECLASS, convert(), findAllPackages(), findMemberDef(), g_packages, getClass(), Definition::getOuterScope(), QCString::lower(), MemberListType_pubMethods, MemberListType_variableMembers, Definition::name(), PACKBODYCLASS, ClassDef::protection(), and QCString::upper().
Referenced by generateMemLink(), startCodeLine(), writeStringLink(), and writeVHDLTypeDocumentation().
findMember() [2/2]
static const MemberDef * VhdlDocGen::findMember (const QCString & className, const QCString & memName) [static]
findMemberDef() [1/2]
const MemberDef * VhdlDocGen::findMemberDef (ClassDef * cd, const QCString & key, MemberListType type) [static]
This function returns the entity|package in which the key (type) is found
Definition at line 697 of file vhdldocgen.cpp.
{
  QCString keyType=cd->symbolName()+"@"+key;
  //printf("\n %s | %s | %s",qPrint(cd->symbolName()),key.data(,),qPrint(keyType));
  auto it = g_varMap.find(keyType.str());
  if (it!=g_varMap.end())
  {
    return it->second;
  }
  if (std::find(g_classList.begin(),g_classList.end(),cd)!=g_classList.end())
  {
    return 0;
  }
  const MemberList *ml=cd->getMemberList(type);
  g_classList.push_back(cd);
  if (!ml)
  {
    return 0;
  }
  //int l=ml->count();
  // fprintf(stderr,"\n loading entity %s %s: %d",qPrint(cd->symbolName()),qPrint(keyType),l);
  for (const auto &md : *ml)
  {
    QCString tkey=cd->symbolName()+"@"+md->name();
    if (g_varMap.find(tkey.str())==g_varMap.end())
    {
      g_varMap.insert({tkey.str(),md});
    }
  }
  it=g_varMap.find(keyType.str());
  if (it!=g_varMap.end())
  {
    return it->second;
  }
  return 0;
}//findMemberDef
References g_classList, g_varMap, ClassDef::getMemberList(), QCString::str(), and Definition::symbolName().
Referenced by findMember().
findMemberDef() [2/2]
static const MemberDef * VhdlDocGen::findMemberDef (ClassDef * cd, const QCString & key, MemberListType type) [static]
findVhdlClass() [1/2]
ClassDef * VhdlDocGen::findVhdlClass (const QCString & className) [static]
Definition at line 2474 of file vhdldocgen.cpp.
{
 for (const auto &cd : *Doxygen::classLinkedMap)
 {
   if (qstricmp(className.data(),qPrint(cd->name()))==0)
   {
     return cd.get();
   }
 }
 return 0;
}
References Doxygen::classLinkedMap, QCString::data(), qPrint(), and qstricmp().
Referenced by computeVhdlComponentRelations().
findVhdlClass() [2/2]
static ClassDef * VhdlDocGen::findVhdlClass (const QCString & className) [static]
formatString() [1/2]
void VhdlDocGen::formatString (const QCString & s, OutputList & ol, const MemberDef * mdef) [static]
inserts white spaces for better readings and writes a colored string to the output
Definition at line 1209 of file vhdldocgen.cpp.
{
  QCString qcs = s;
  QCString temp;
  qcs.stripPrefix(":");
  qcs.stripPrefix("is");
  qcs.stripPrefix("IS");
  qcs.stripPrefix("of");
  qcs.stripPrefix("OF");
  // VhdlDocGen::deleteCharRev(qcs,';');
  //char white='\t';
  int len = qcs.length();
  unsigned int index=1;//temp.length();
  for (int j=0;j<len;j++)
  {
    char c=qcs[j];
    char b=c;
    if (j>0) b=qcs[j-1];
    if (c=='"' || c==',' || c=='\''|| c=='(' || c==')' || c==':' || c=='[' || c==']') // || (c==':' && b!='=')) // || (c=='=' && b!='>'))
    {
      if (temp.length()>=index && temp.at(index-1) != ' ')
      {
        temp+=" ";
      }
      temp+=c;
      temp+=" ";
    }
    else if (c=='=')
    {
      if (b==':') // := operator
      {
        temp.replace(index-1,1,"=");
        temp+=" ";
      }
      else // = operator
      {
        temp+=" ";
        temp+=c;
        temp+=" ";
      }
    }
    else
    {
      temp+=c;
    }
    index=temp.length();
  }// for
  temp=temp.stripWhiteSpace();
  // printf("\n [%s]",qPrint(qcs));
  VhdlDocGen::writeFormatString(temp,ol,mdef);
}
References QCString::at(), b, c, len, QCString::length(), QCString::replace(), s, QCString::stripPrefix(), QCString::stripWhiteSpace(), and writeFormatString().
Referenced by writeFunctionProto(), writeProcedureProto(), writeRecordUnit(), writeRecUnitDocu(), writeUCFLink(), writeVHDLDeclaration(), and writeVHDLTypeDocumentation().
formatString() [2/2]
static void VhdlDocGen::formatString (const QCString & , OutputList & ol, const MemberDef *) [static]
getClass() [1/2]
ClassDef * VhdlDocGen::getClass (const QCString & name) [static]
Definition at line 582 of file vhdldocgen.cpp.
{
  if (name.isEmpty()) return 0;
  return Doxygen::classLinkedMap->find(QCString(name).stripWhiteSpace());
}
References Doxygen::classLinkedMap, LinkedMap< T, Hash, KeyEqual, Map >::find(), and setup::name.
Referenced by findFunction(), findMember(), generateMemLink(), getPackageName(), writeInlineClassLink(), and writeVHDLDeclaration().
getClass() [2/2]
static ClassDef * VhdlDocGen::getClass (const QCString & name) [static]
getClassName() [1/2]
QCString VhdlDocGen::getClassName (const ClassDef * cd) [static]
Definition at line 809 of file vhdldocgen.cpp.
{
  QCString temp;
  if (cd==0) return "";
  if (VhdlDocGen::convert(cd->protection())==VhdlDocGen::PACKBODYCLASS)
  {
    temp=cd->name();
    temp.stripPrefix("_");
    return temp;
  }
  return substitute(cd->className(),"::",".");
}
References ClassDef::className(), convert(), Definition::name(), PACKBODYCLASS, ClassDef::protection(), QCString::stripPrefix(), and substitute().
Referenced by getClassTitle(), makeDisplayName(), and writeClassType().
getClassName() [2/2]
static QCString VhdlDocGen::getClassName (const ClassDef *) [static]
getClassTitle() [1/2]
QCString VhdlDocGen::getClassTitle (const ClassDef * cd) [static]
returns the class title+ref
Definition at line 796 of file vhdldocgen.cpp.
{
  QCString pageTitle;
  if (cd==0) return "";
  pageTitle=VhdlDocGen::getClassName(cd);
  int ii=cd->protection();
  pageTitle+=" ";
  pageTitle+=theTranslator_vhdlType(ii+2,TRUE);
  return pageTitle;
} // getClassTitle
References getClassName(), ClassDef::protection(), theTranslator_vhdlType, and TRUE.
Referenced by ClassDefImpl::title().
getClassTitle() [2/2]
static QCString VhdlDocGen::getClassTitle (const ClassDef *) [static]
getFlowMember() [1/2]
const MemberDef * VhdlDocGen::getFlowMember () [static]
Definition at line 91 of file vhdldocgen.cpp.
{
  return flowMember;
}
References flowMember.
Referenced by FlowChart::addFlowChart(), VHDLOutlineParser::addVhdlType(), FlowChart::alignFuncProc(), FlowChart::convertNameToFileName(), VHDLOutlineParser::createFlow(), VHDLOutlineParser::handleFlowComment(), FlowChart::moveToPrevLevel(), and HtmlDocVisitor::operator()().
getFlowMember() [2/2]
static const MemberDef * VhdlDocGen::getFlowMember () [static]
getIndexWord() [1/2]
QCString VhdlDocGen::getIndexWord (const QCString & c, int index) [static]
Definition at line 1040 of file vhdldocgen.cpp.
{
  static const reg::Ex reg(R"([\s:|])");
  auto ql=split(c.str(),reg);
  if (index < static_cast<int>(ql.size()))
  {
    return QCString(ql[index]);
  }
  return "";
}
References c, and split().
Referenced by vhdl::parser::VhdlParser::component_instantiation_statement(), computeVhdlComponentRelations(), and parseFuncProto().
getIndexWord() [2/2]
static QCString VhdlDocGen::getIndexWord (const QCString & , int index) [static]
getPackageName() [1/2]
ClassDef * VhdlDocGen::getPackageName (const QCString & name) [static]
Definition at line 588 of file vhdldocgen.cpp.
{
  return getClass(name);
}
References getClass(), and setup::name.
Referenced by findAllPackages().
getPackageName() [2/2]
static ClassDef * VhdlDocGen::getPackageName (const QCString & name) [static]
getProcessNumber() [1/2]
QCString VhdlDocGen::getProcessNumber () [static]
returns the next number of an anonymous process
Definition at line 1114 of file vhdldocgen.cpp.
{
  static int stringCounter;
  char buf[8];
  QCString qcs("PROCESS_");
  sprintf(buf,"%d",stringCounter++);
  qcs.append(&buf[0]);
  return qcs;
}
References QCString::append().
Referenced by vhdl::parser::VhdlParser::process_statement().
getProcessNumber() [2/2]
static QCString VhdlDocGen::getProcessNumber () [static]
getProtectionName() [1/2]
QCString VhdlDocGen::getProtectionName (int prot) [static]
Definition at line 1054 of file vhdldocgen.cpp.
{
  if (prot==VhdlDocGen::ENTITYCLASS)
    return "entity";
  else if (prot==VhdlDocGen::ARCHITECTURECLASS)
    return "architecture";
  else if (prot==VhdlDocGen::PACKAGECLASS)
    return "package";
  else if (prot==VhdlDocGen::PACKBODYCLASS)
    return "package body";
  return "";
}
References ARCHITECTURECLASS, ENTITYCLASS, PACKAGECLASS, and PACKBODYCLASS.
Referenced by writeAnnotatedClassList(), and ClassDefImpl::writeDeclarationLink().
getProtectionName() [2/2]
static QCString VhdlDocGen::getProtectionName (int prot) [static]
getRecordNumber() [1/2]
QCString VhdlDocGen::getRecordNumber () [static]
returns the next number of a record|unit member
Definition at line 1102 of file vhdldocgen.cpp.
{
  char buf[12];
  sprintf(buf,"%d",recordCounter++);
  QCString qcs(&buf[0]);
  return qcs;
}
References recordCounter.
Referenced by VHDLOutlineParser::checkInlineCode(), initUCF(), and writeVhdlEntityToolTip().
getRecordNumber() [2/2]
static QCString VhdlDocGen::getRecordNumber () [static]
init() [1/2]
void VhdlDocGen::init () [static]
Definition at line 554 of file vhdldocgen.cpp.
{
}
Referenced by VHDLCodeParser::parseCode().
init() [2/2]
static void VhdlDocGen::init () [static]
isAlias() [1/2]
bool VhdlDocGen::isAlias (const MemberDef * mdef) [static]
Definition at line 2787 of file vhdldocgen.cpp.
{ return mdef->getMemberSpecifiers()==VhdlDocGen::ALIAS; }
References ALIAS, and MemberDef::getMemberSpecifiers().
Referenced by writeTagFile().
isAlias() [2/2]
static bool VhdlDocGen::isAlias (const MemberDef * mdef) [static]
isArchitecture() [1/2]
bool VhdlDocGen::isArchitecture (const MemberDef * mdef) [static]
Definition at line 2821 of file vhdldocgen.cpp.
{ return mdef->getMemberSpecifiers()==VhdlDocGen::ARCHITECTURE; }
References ARCHITECTURE, and MemberDef::getMemberSpecifiers().
isArchitecture() [2/2]
static bool VhdlDocGen::isArchitecture (const MemberDef * mdef) [static]
isAttribute() [1/2]
bool VhdlDocGen::isAttribute (const MemberDef * mdef) [static]
Definition at line 2813 of file vhdldocgen.cpp.
{ return mdef->getMemberSpecifiers()==VhdlDocGen::ATTRIBUTE; }
References ATTRIBUTE, and MemberDef::getMemberSpecifiers().
Referenced by writeTagFile().
isAttribute() [2/2]
static bool VhdlDocGen::isAttribute (const MemberDef * mdef) [static]
isCompInst() [1/2]
bool VhdlDocGen::isCompInst (const MemberDef * mdef) [static]
Definition at line 2833 of file vhdldocgen.cpp.
{ return mdef->getMemberSpecifiers()==VhdlDocGen::INSTANTIATION; }
References MemberDef::getMemberSpecifiers(), and INSTANTIATION.
Referenced by writeTagFile(), and writeVHDLDeclaration().
isCompInst() [2/2]
static bool VhdlDocGen::isCompInst (const MemberDef * mdef) [static]
isComponent() [1/2]
bool VhdlDocGen::isComponent (const MemberDef * mdef) [static]
Definition at line 2795 of file vhdldocgen.cpp.
{ return mdef->getMemberSpecifiers()==VhdlDocGen::COMPONENT; }
References COMPONENT, and MemberDef::getMemberSpecifiers().
Referenced by writeTagFile(), and writeVHDLDeclaration().
isComponent() [2/2]
static bool VhdlDocGen::isComponent (const MemberDef * mdef) [static]
isConfig() [1/2]
bool VhdlDocGen::isConfig (const MemberDef * mdef) [static]
Definition at line 2785 of file vhdldocgen.cpp.
{ return mdef->getMemberSpecifiers()==VhdlDocGen::CONFIG; }
References CONFIG, and MemberDef::getMemberSpecifiers().
Referenced by writeVHDLDeclaration().
isConfig() [2/2]
static bool VhdlDocGen::isConfig (const MemberDef * mdef) [static]
isConstant() [1/2]
bool VhdlDocGen::isConstant (const MemberDef * mdef) [static]
Definition at line 2801 of file vhdldocgen.cpp.
{ return mdef->getMemberSpecifiers()==VhdlDocGen::CONSTANT; }
References CONSTANT, and MemberDef::getMemberSpecifiers().
Referenced by writeTagFile().
isConstant() [2/2]
static bool VhdlDocGen::isConstant (const MemberDef * mdef) [static]
isConstraint() [1/2]
bool VhdlDocGen::isConstraint (const MemberDef * mdef) [static]
Definition at line 2783 of file vhdldocgen.cpp.
{ return mdef->getMemberSpecifiers()==VhdlDocGen::UCF_CONST; }
References MemberDef::getMemberSpecifiers(), and UCF_CONST.
Referenced by writeVHDLTypeDocumentation().
isConstraint() [2/2]
static bool VhdlDocGen::isConstraint (const MemberDef * mdef) [static]
isEntity() [1/2]
bool VhdlDocGen::isEntity (const MemberDef * mdef) [static]
Definition at line 2799 of file vhdldocgen.cpp.
{ return mdef->getMemberSpecifiers()==VhdlDocGen::ENTITY; }
References ENTITY, and MemberDef::getMemberSpecifiers().
Referenced by writeTagFile().
isEntity() [2/2]
static bool VhdlDocGen::isEntity (const MemberDef * mdef) [static]
isFile() [1/2]
bool VhdlDocGen::isFile (const MemberDef * mdef) [static]
Definition at line 2829 of file vhdldocgen.cpp.
{ return mdef->getMemberSpecifiers()==VhdlDocGen::VFILE; }
References MemberDef::getMemberSpecifiers(), and VFILE.
Referenced by writeTagFile().
isFile() [2/2]
static bool VhdlDocGen::isFile (const MemberDef * mdef) [static]
isGeneric() [1/2]
bool VhdlDocGen::isGeneric (const MemberDef * mdef) [static]
Definition at line 2791 of file vhdldocgen.cpp.
{ return mdef->getMemberSpecifiers()==VhdlDocGen::GENERIC; }
References GENERIC, and MemberDef::getMemberSpecifiers().
Referenced by writeTagFile(), and writeVHDLTypeDocumentation().
isGeneric() [2/2]
static bool VhdlDocGen::isGeneric (const MemberDef * mdef) [static]
isGroup() [1/2]
bool VhdlDocGen::isGroup (const MemberDef * mdef) [static]
Definition at line 2831 of file vhdldocgen.cpp.
{ return mdef->getMemberSpecifiers()==VhdlDocGen::GROUP; }
References MemberDef::getMemberSpecifiers(), and GROUP.
Referenced by writeTagFile().
isGroup() [2/2]
static bool VhdlDocGen::isGroup (const MemberDef * mdef) [static]
isLibrary() [1/2]
bool VhdlDocGen::isLibrary (const MemberDef * mdef) [static]
Definition at line 2789 of file vhdldocgen.cpp.
{ return mdef->getMemberSpecifiers()==VhdlDocGen::LIBRARY; }
References MemberDef::getMemberSpecifiers(), and LIBRARY.
Referenced by writeTagFile(), and writeVHDLTypeDocumentation().
isLibrary() [2/2]
static bool VhdlDocGen::isLibrary (const MemberDef * mdef) [static]
isMisc() [1/2]
bool VhdlDocGen::isMisc (const MemberDef * mdef) [static]
Definition at line 2835 of file vhdldocgen.cpp.
{ return mdef->getMemberSpecifiers()==VhdlDocGen::MISCELLANEOUS; }
References MemberDef::getMemberSpecifiers(), and MISCELLANEOUS.
Referenced by MemberDefImpl::writeDocumentation().
isMisc() [2/2]
static bool VhdlDocGen::isMisc (const MemberDef * mdef) [static]
isNumber() [1/2]
bool VhdlDocGen::isNumber (const std::string & s) [static]
returns TRUE if this string is a number
Definition at line 1197 of file vhdldocgen.cpp.
{
  static const reg::Ex regg(R"([0-9][0-9eEfFbBcCdDaA_.#+?xXzZ-]*)");
  return reg::match(s,regg);
}// isNumber
References reg::match(), and s.
Referenced by checkVhdlString(), writeFormatString(), and writeWord().
isNumber() [2/2]
static bool VhdlDocGen::isNumber (const std::string & s) [static]
isPackage() [1/2]
bool VhdlDocGen::isPackage (const MemberDef * mdef) [static]
Definition at line 2797 of file vhdldocgen.cpp.
{ return mdef->getMemberSpecifiers()==VhdlDocGen::USE; }
References MemberDef::getMemberSpecifiers(), and USE.
Referenced by findAllPackages(), writeTagFile(), and writeVHDLTypeDocumentation().
isPackage() [2/2]
static bool VhdlDocGen::isPackage (const MemberDef * mdef) [static]
isPackageBody() [1/2]
bool VhdlDocGen::isPackageBody (const MemberDef * mdef) [static]
Definition at line 2825 of file vhdldocgen.cpp.
{ return mdef->getMemberSpecifiers()==VhdlDocGen::PACKAGE_BODY; }
References MemberDef::getMemberSpecifiers(), and PACKAGE_BODY.
isPackageBody() [2/2]
static bool VhdlDocGen::isPackageBody (const MemberDef * mdef) [static]
isPort() [1/2]
bool VhdlDocGen::isPort (const MemberDef * mdef) [static]
Definition at line 2793 of file vhdldocgen.cpp.
{ return mdef->getMemberSpecifiers()==VhdlDocGen::PORT; }
References MemberDef::getMemberSpecifiers(), and PORT.
Referenced by writeTagFile(), and writeVHDLTypeDocumentation().
isPort() [2/2]
static bool VhdlDocGen::isPort (const MemberDef * mdef) [static]
isProcedure() [1/2]
bool VhdlDocGen::isProcedure (const MemberDef * mdef) [static]
Definition at line 2817 of file vhdldocgen.cpp.
{ return mdef->getMemberSpecifiers()==VhdlDocGen::PROCEDURE; }
References MemberDef::getMemberSpecifiers(), and PROCEDURE.
Referenced by findFunction(), writeFuncProcDocu(), writeTagFile(), and writeVHDLTypeDocumentation().
isProcedure() [2/2]
static bool VhdlDocGen::isProcedure (const MemberDef * mdef) [static]
isProcess() [1/2]
bool VhdlDocGen::isProcess (const MemberDef * mdef) [static]
Definition at line 2809 of file vhdldocgen.cpp.
{ return mdef->getMemberSpecifiers()==VhdlDocGen::PROCESS; }
References MemberDef::getMemberSpecifiers(), and PROCESS.
Referenced by writeFuncProcDocu(), writeTagFile(), and writeVHDLTypeDocumentation().
isProcess() [2/2]
static bool VhdlDocGen::isProcess (const MemberDef * mdef) [static]
isRecord() [1/2]
bool VhdlDocGen::isRecord (const MemberDef * mdef) [static]
Definition at line 2819 of file vhdldocgen.cpp.
{ return mdef->getMemberSpecifiers()==VhdlDocGen::RECORD; }
References MemberDef::getMemberSpecifiers(), and RECORD.
Referenced by writeTagFile().
isRecord() [2/2]
static bool VhdlDocGen::isRecord (const MemberDef * mdef) [static]
isSignal() [1/2]
bool VhdlDocGen::isSignal (const MemberDef * mdef) [static]
Definition at line 2811 of file vhdldocgen.cpp.
{ return mdef->getMemberSpecifiers()==VhdlDocGen::SIGNAL; }
References MemberDef::getMemberSpecifiers(), and SIGNAL.
isSignal() [2/2]
static bool VhdlDocGen::isSignal (const MemberDef * mdef) [static]
isSignals() [1/2]
bool VhdlDocGen::isSignals (const MemberDef * mdef) [static]
Definition at line 2815 of file vhdldocgen.cpp.
{ return mdef->getMemberSpecifiers()==VhdlDocGen::SIGNAL; }
References MemberDef::getMemberSpecifiers(), and SIGNAL.
Referenced by writeTagFile().
isSignals() [2/2]
static bool VhdlDocGen::isSignals (const MemberDef * mdef) [static]
isSubClass() [1/2]
bool VhdlDocGen::isSubClass (ClassDef * cd, ClassDef * scd, bool followInstances, int level) [static]
Definition at line 2664 of file vhdldocgen.cpp.
{
  bool found=FALSE;
  //printf("isBaseClass(cd=%s) looking for %s\n",qPrint(name()),qPrint(bcd->name()));
  if (level>255)
  {
    err("Possible recursive class relation while inside %s and looking for %s\n",qPrint(cd->name()),qPrint(scd->name()));
    abort();
  }
  for (const auto &bcd :cd->subClasses())
  {
    const ClassDef *ccd=bcd.classDef;
    if (!followInstances && ccd->templateMaster()) ccd=ccd->templateMaster();
    //printf("isSubClass() subclass %s\n",qPrint(ccd->name()));
    if (ccd==scd)
    {
      found=true;
    }
    else
    {
      if (level <256)
      {
        level = ccd->isBaseClass(scd,followInstances);
        if (level>0)
        {
          found=true;
        }
      }
    }
  }
  return found;
}
References err(), FALSE, found, ClassDef::isBaseClass(), level, Definition::name(), qPrint(), ClassDef::subClasses(), and ClassDef::templateMaster().
Referenced by addInstance().
isSubClass() [2/2]
static bool VhdlDocGen::isSubClass (ClassDef * cd, ClassDef * scd, bool followInstances, int level) [static]
isSubType() [1/2]
bool VhdlDocGen::isSubType (const MemberDef * mdef) [static]
Definition at line 2805 of file vhdldocgen.cpp.
{ return mdef->getMemberSpecifiers()==VhdlDocGen::SUBTYPE; }
References MemberDef::getMemberSpecifiers(), and SUBTYPE.
Referenced by writeTagFile().
isSubType() [2/2]
static bool VhdlDocGen::isSubType (const MemberDef * mdef) [static]
isUnit() [1/2]
bool VhdlDocGen::isUnit (const MemberDef * mdef) [static]
Definition at line 2823 of file vhdldocgen.cpp.
{ return mdef->getMemberSpecifiers()==VhdlDocGen::UNITS; }
References MemberDef::getMemberSpecifiers(), and UNITS.
isUnit() [2/2]
static bool VhdlDocGen::isUnit (const MemberDef * mdef) [static]
isVariable() [1/2]
bool VhdlDocGen::isVariable (const MemberDef * mdef) [static]
Definition at line 2827 of file vhdldocgen.cpp.
{ return mdef->getMemberSpecifiers()==VhdlDocGen::SHAREDVARIABLE; }
References MemberDef::getMemberSpecifiers(), and SHAREDVARIABLE.
Referenced by writeTagFile().
isVariable() [2/2]
static bool VhdlDocGen::isVariable (const MemberDef * mdef) [static]
isVhdlClass() [1/2]
static bool VhdlDocGen::isVhdlClass (const Entry * cu) [inline], [static]
Definition at line 247 of file vhdldocgen.h.
    {
      return cu->spec==VhdlDocGen::ENTITY ||
             cu->spec==VhdlDocGen::PACKAGE ||
             cu->spec==VhdlDocGen::ARCHITECTURE ||
             cu->spec==VhdlDocGen::PACKAGE_BODY;
    }
References ARCHITECTURE, ENTITY, PACKAGE, PACKAGE_BODY, and Entry::spec.
Referenced by VHDLOutlineParser::mapLibPackage().
isVhdlClass() [2/2]
static bool VhdlDocGen::isVhdlClass (const Entry * cu) [inline], [static]
Definition at line 247 of file vhdldocgen.h.
    {
      return cu->spec==VhdlDocGen::ENTITY ||
             cu->spec==VhdlDocGen::PACKAGE ||
             cu->spec==VhdlDocGen::ARCHITECTURE ||
             cu->spec==VhdlDocGen::PACKAGE_BODY;
    }
References ARCHITECTURE, ENTITY, PACKAGE, PACKAGE_BODY, and Entry::spec.
isVhdlFunction() [1/2]
bool VhdlDocGen::isVhdlFunction (const MemberDef * mdef) [static]
Definition at line 2807 of file vhdldocgen.cpp.
{ return mdef->getMemberSpecifiers()==VhdlDocGen::FUNCTION; }
References FUNCTION, and MemberDef::getMemberSpecifiers().
Referenced by findFunction(), writeFuncProcDocu(), writeTagFile(), and writeVHDLTypeDocumentation().
isVhdlFunction() [2/2]
static bool VhdlDocGen::isVhdlFunction (const MemberDef * mdef) [static]
isVType() [1/2]
bool VhdlDocGen::isVType (const MemberDef * mdef) [static]
Definition at line 2803 of file vhdldocgen.cpp.
{ return mdef->getMemberSpecifiers()==VhdlDocGen::TYPE; }
References MemberDef::getMemberSpecifiers(), and TYPE.
Referenced by writeTagFile().
isVType() [2/2]
static bool VhdlDocGen::isVType (const MemberDef * mdef) [static]
parseForBinding() [1/2]
QCString VhdlDocGen::parseForBinding (QCString & entity, QCString & arch) [static]
Definition at line 2440 of file vhdldocgen.cpp.
{
  static const reg::Ex exp(R"([()\s])");
  auto ql = split(entity.str(),exp);
  if (findIndex(ql,"open")!=-1)
  {
    return "open";
  }
  if (ql.size()<2)
  {
    return "";
  }
  std::string label=ql[0];
  entity = ql[1];
  int index;
  if ((index=entity.findRev("."))>=0)
  {
    entity.remove(0,index+1);
  }
  if (ql.size()==3)
  {
    arch=ql[2];
  }
  return QCString(label);
}
References findIndex(), QCString::findRev(), QCString::remove(), split(), QCString::str(), and string.
Referenced by computeVhdlComponentRelations().
parseForBinding() [2/2]
static QCString VhdlDocGen::parseForBinding (QCString & entity, QCString & arch) [static]
parseForConfig() [1/2]
QCString VhdlDocGen::parseForConfig (QCString & entity, QCString & arch) [static]
Definition at line 2407 of file vhdldocgen.cpp.
{
  QCString label;
  if (!entity.contains(":")) return "";
  static const reg::Ex exp(R"([:()\s])");
  auto ql=split(entity.str(),exp);
  if (ql.size()<2)
  {
    return "";
  }
  label = ql[0];
  entity = ql[1];
  int index;
  if ((index=entity.findRev("."))>=0)
  {
    entity.remove(0,index+1);
  }
  if (ql.size()==3)
  {
    arch = ql[2];
    ql=split(arch.str(),exp);
    if (ql.size()>1) // expression
    {
      arch="";
    }
  }
  return label; // label
}
References QCString::contains(), QCString::findRev(), QCString::remove(), split(), and QCString::str().
parseForConfig() [2/2]
static QCString VhdlDocGen::parseForConfig (QCString & entity, QCString & arch) [static]
parseFuncProto() [1/2]
void VhdlDocGen::parseFuncProto (const QCString & text, QCString & name, QCString & ret, bool doc = false) [static]
parses a function proto
Parameters
text function string
name points to the function name
ret Stores the return type
doc ???
Definition at line 989 of file vhdldocgen.cpp.
{
  int index,end;
  QCString s1(text);
  QCString temp;
  index=s1.find("(");
  if (index<0) index=0;
  end=s1.findRev(")");
  if ((end-index)>0)
  {
    temp=s1.mid(index+1,(end-index-1));
    //getFuncParams(qlist,temp);
  }
  if (doc)
  {
    name=s1.left(index);
    name=name.stripWhiteSpace();
    if ((end-index)>0)
    {
      ret="function";
    }
    return;
  }
  else
  {
    s1=s1.stripWhiteSpace();
    int i=s1.find('(');
    int s=s1.find(' ');
    if (s==-1) s=s1.find('\t');
    if (i==-1 || i<s)
      s1=VhdlDocGen::getIndexWord(s1,1);
    else // s<i, s=start of name, i=end of name
      s1=s1.mid(s,(i-s));
    name=s1.stripWhiteSpace();
  }
  index=s1.findRev("return",-1,FALSE);
  if (index !=-1)
  {
    ret=s1.mid(index+6,s1.length());
    ret=ret.stripWhiteSpace();
    VhdlDocGen::deleteCharRev(ret,';');
  }
}
References deleteCharRev(), ghc::filesystem::end(), FALSE, QCString::find(), QCString::findRev(), getIndexWord(), QCString::left(), QCString::length(), QCString::mid(), setup::name, s, and QCString::stripWhiteSpace().
Referenced by writeFuncProto().
parseFuncProto() [2/2]
static void VhdlDocGen::parseFuncProto (const QCString & text, QCString & name, QCString & ret, bool doc = false) [static]
parseUCF() [1/2]
void VhdlDocGen::parseUCF (const char * input, Entry * entity, const QCString & f, bool vendor) [static]
Definition at line 2265 of file vhdldocgen.cpp.
{
  QCString ucFile(input);
  int lineNo=0;
  QCString comment("#!");
  QCString brief;
  while (!ucFile.isEmpty())
  {
    int i=ucFile.find("\n");
    if (i<0) break;
    lineNo++;
    QCString temp=ucFile.left(i);
    temp=temp.stripWhiteSpace();
    bool bb=temp.stripPrefix("//");
    if (!temp.isEmpty())
    {
      if (temp.stripPrefix(comment))
      {
        brief+=temp;
        brief.append("\\n");
      }
      else if (!temp.stripPrefix("#") && !bb)
      {
        if (altera)
        {
          int in=temp.find("-name");
          if (in>0)
          {
            temp=temp.remove(0,in+5);
          }
          temp.stripPrefix("set_location_assignment");
          initUCF(entity,QCString(),temp,lineNo,fileName,brief);
        }
        else
        {
          static const reg::Ex ee(R"([\s=])");
          int in=findIndex(temp.str(),ee);
          if (in<0) in=0;
          QCString ff=temp.left(in);
          temp.stripPrefix(ff);
          ff.append("#");
          if (!temp.isEmpty())
          {
            initUCF(entity,ff,temp,lineNo,fileName,brief);
          }
        }
      }
    }//temp
    ucFile=ucFile.remove(0,i+1);
  }// while
}
References QCString::append(), comment, QCString::find(), findIndex(), initUCF(), QCString::isEmpty(), QCString::left(), QCString::remove(), QCString::str(), QCString::stripPrefix(), and QCString::stripWhiteSpace().
Referenced by VHDLOutlineParser::parseInput().
parseUCF() [2/2]
static void VhdlDocGen::parseUCF (const char * input, Entry * entity, const QCString & f, bool vendor) [static]
prepareComment() [1/2]
void VhdlDocGen::prepareComment (QCString & qcs) [static]
strips the `--` prefixes of vhdl comments
Definition at line 967 of file vhdldocgen.cpp.
{
  const char* s="--!";
  int index=0;
  while (TRUE)
  {
    index=qcs.find(s,0,TRUE);
    if (index<0) break;
    qcs=qcs.remove(index,qstrlen(s));
  }
  qcs=qcs.stripWhiteSpace();
}
References QCString::find(), qstrlen(), QCString::remove(), s, QCString::stripWhiteSpace(), and TRUE.
Referenced by VHDLOutlineParser::checkInlineCode(), VHDLOutlineParser::checkMultiComment(), and VHDLOutlineParser::handleCommentBlock().
prepareComment() [2/2]
static void VhdlDocGen::prepareComment (QCString &) [static]
resetCodeVhdlParserState() [1/2]
void VhdlDocGen::resetCodeVhdlParserState () [static]
Definition at line 2776 of file vhdldocgen.cpp.
{
  g_varMap.clear();
  g_classList.clear();
  g_packages.clear();
}
References g_classList, g_packages, and g_varMap.
resetCodeVhdlParserState() [2/2]
static void VhdlDocGen::resetCodeVhdlParserState () [static]
setFlowMember() [1/2]
void VhdlDocGen::setFlowMember (const MemberDef * flowMember) [static]
Definition at line 86 of file vhdldocgen.cpp.
{
  flowMember=mem;
}
References flowMember.
Referenced by createFlowChart().
setFlowMember() [2/2]
static void VhdlDocGen::setFlowMember (const MemberDef * flowMember) [static]
writeClassType() [1/2]
bool VhdlDocGen::writeClassType (const ClassDef * cd, OutputList & ol, QCString & cname) [static]
Definition at line 2149 of file vhdldocgen.cpp.
{
  int id=cd->protection();
  QCString qcs = theTranslator->trVhdlType(id+2,TRUE);
  cname=VhdlDocGen::getClassName(cd);
  ol.startBold();
  ol.writeString(qcs);
  ol.writeString(" ");
  ol.endBold();
  //ol.insertMemberAlign();
  return FALSE;
}// writeClassLink
References OutputList::endBold(), FALSE, getClassName(), ClassDef::protection(), OutputList::startBold(), theTranslator, TRUE, Translator::trVhdlType(), and OutputList::writeString().
writeClassType() [2/2]
static bool VhdlDocGen::writeClassType (const ClassDef * , OutputList & ol, QCString & cname) [static]
writeFormatString() [1/2]
void VhdlDocGen::writeFormatString (const QCString & s, OutputList & ol, const MemberDef * mdef) [static]
writes a colored and formatted string
Definition at line 1128 of file vhdldocgen.cpp.
{
  static const reg::Ex reg(R"([\[\]./<>:\s,;'+*|&=()\"-])");
  QCString qcs = s;
  qcs+=QCString(" ");// parsing the last sign
  QCString find=qcs;
  QCString temp=qcs;
  char buf[2];
  buf[1]='\0';
  int j = findIndex(temp.str(),reg);
  ol.startBold();
  if (j>=0)
  {
    while (j>=0)
    {
      find=find.left(j);
      buf[0]=temp[j];
      const char *ss=VhdlDocGen::findKeyWord(find);
      bool k=isNumber(find.str()); // is this a number
      if (k)
      {
        ol.docify(" ");
        startFonts(find,"vhdldigit",ol);
        ol.docify(" ");
      }
      else if (j != 0 && ss)
      {
        startFonts(find,ss,ol);
      }
      else
      {
        if (j>0)
        {
          VhdlDocGen::writeStringLink(mdef,find,ol);
        }
      }
      startFonts(&buf[0],"vhdlchar",ol);
      QCString st=temp.remove(0,j+1);
      find=st;
      if (!find.isEmpty() && find.at(0)=='"')
      {
        int ii=find.find('"',2);
        if (ii>1)
        {
          QCString com=find.left(ii+1);
          startFonts(com,"keyword",ol);
          temp=find.remove(0,ii+1);
        }
      }
      else
      {
        temp=st;
      }
      j = findIndex(temp.str(),reg);
    }//while
  }//if
  else
  {
    startFonts(find,"vhdlchar",ol);
  }
  ol.endBold();
}// writeFormatString
References QCString::at(), OutputList::docify(), OutputList::endBold(), QCString::find(), findIndex(), findKeyWord(), QCString::isEmpty(), isNumber(), QCString::left(), QCString::remove(), s, OutputList::startBold(), startFonts(), QCString::str(), and writeStringLink().
Referenced by formatString(), writeFuncProcDocu(), and writeProcessProto().
writeFormatString() [2/2]
static void VhdlDocGen::writeFormatString (const QCString & , OutputList & ol, const MemberDef *) [static]
writeFuncProcDocu() [1/2]
bool VhdlDocGen::writeFuncProcDocu (const MemberDef * md, OutputList & ol, const ArgumentList & al, bool type = false) [static]
writes a function|procedure documentation to the output
Definition at line 1427 of file vhdldocgen.cpp.
{
  //bool sem=FALSE;
  ol.enableAll();
  size_t index=al.size();
  if (index==0)
  {
    ol.docify(" () ");
    return FALSE;
  }
  ol.endMemberDocName();
  ol.startParameterList(TRUE);
  //ol.startParameterName(FALSE);
  bool first=TRUE;
  for (const Argument &arg : al)
  {
    ol.startParameterType(first,"");
    // if (first) ol.writeChar('(');
    QCString attl=arg.defval;
    bool bGen=attl.stripPrefix("gen!");
    if (bGen)
      VhdlDocGen::writeFormatString(QCString("generic "),ol,md);
    if (VhdlDocGen::isProcedure(md))
    {
      startFonts(arg.defval,"keywordtype",ol);
      ol.docify(" ");
    }
    ol.endParameterType();
    ol.startParameterName(TRUE);
    VhdlDocGen::writeFormatString(arg.name,ol,md);
    if (VhdlDocGen::isProcedure(md))
    {
      startFonts(arg.attrib,"stringliteral",ol);
    }
    else if (VhdlDocGen::isVhdlFunction(md))
    {
      startFonts(QCString("in"),"stringliteral",ol);
    }
    ol.docify(" ");
    ol.disable(OutputGenerator::Man);
    ol.startEmphasis();
    ol.enable(OutputGenerator::Man);
    if (!VhdlDocGen::isProcess(md))
    {
     // startFonts(arg.type,"vhdlkeyword",ol);
        VhdlDocGen::writeFormatString(arg.type,ol,md);
    }
    ol.disable(OutputGenerator::Man);
    ol.endEmphasis();
    ol.enable(OutputGenerator::Man);
    if (--index)
    {
      ol.docify(" , ");
    }
    else
    {
      // ol.docify(") ");
      ol.endParameterName(TRUE,FALSE,TRUE);
      break;
    }
    ol.endParameterName(FALSE,FALSE,FALSE);
    //sem=TRUE;
    first=FALSE;
  }
  //ol.endParameterList();
  return TRUE;
} // writeDocFunProc
References OutputList::disable(), OutputList::docify(), OutputList::enable(), OutputList::enableAll(), OutputList::endEmphasis(), OutputList::endMemberDocName(), OutputList::endParameterName(), OutputList::endParameterType(), FALSE, isProcedure(), isProcess(), isVhdlFunction(), OutputGenerator::Man, ArgumentList::size(), OutputList::startEmphasis(), startFonts(), OutputList::startParameterList(), OutputList::startParameterName(), OutputList::startParameterType(), QCString::stripPrefix(), TRUE, and writeFormatString().
Referenced by writeVHDLTypeDocumentation().
writeFuncProcDocu() [2/2]
static bool VhdlDocGen::writeFuncProcDocu (const MemberDef * mdef, OutputList & ol, const ArgumentList & al, bool type = false) [static]
writeFunctionProto() [1/2]
void VhdlDocGen::writeFunctionProto (OutputList & ol, const ArgumentList & al, const MemberDef * mdef) [static]
writes a function prototype to the output
Definition at line 1323 of file vhdldocgen.cpp.
{
  if (!al.hasParameters()) return;
  bool sem=FALSE;
  size_t len=al.size();
  ol.startBold();
  ol.docify(" (");
  ol.endBold();
  if (len>2)
  {
    ol.lineBreak();
  }
  for (const Argument &arg : al)
  {
    ol.startBold();
    QCString att=arg.defval;
    bool bGen=att.stripPrefix("gen!");
    if (sem && len < 3)
    {
      ol.docify(" , ");
    }
    if (bGen)
    {
      VhdlDocGen::formatString(QCString("generic "),ol,mdef);
    }
    if (!att.isEmpty())
    {
      const char *str=VhdlDocGen::findKeyWord(att);
      att+=" ";
      if (str)
        VhdlDocGen::formatString(att,ol,mdef);
      else
        startFonts(att,"vhdlchar",ol);
    }
    QCString nn=arg.name;
    nn+=": ";
    QCString ss=arg.type.stripWhiteSpace(); //.lower();
    QCString w=ss.stripWhiteSpace();//.upper();
    startFonts(nn,"vhdlchar",ol);
    startFonts("in ","stringliteral",ol);
    const char *str=VhdlDocGen::findKeyWord(ss);
    if (str)
      VhdlDocGen::formatString(w,ol,mdef);
    else
      startFonts(w,"vhdlchar",ol);
    if (!arg.attrib.isEmpty())
      startFonts(arg.attrib,"vhdlchar",ol);
    sem=TRUE;
    ol.endBold();
    if (len > 2)
    {
      ol.lineBreak();
    }
  }
  ol.startBold();
  ol.docify(")");
  QCString exp=mdef->excpString();
  if (!exp.isEmpty())
  {
    ol.insertMemberAlign();
    ol.startBold();
    ol.docify("[ ");
    ol.docify(exp);
    ol.docify(" ]");
    ol.endBold();
  }
  ol.endBold();
}
References OutputList::docify(), OutputList::endBold(), MemberDef::excpString(), FALSE, findKeyWord(), formatString(), ArgumentList::hasParameters(), OutputList::insertMemberAlign(), QCString::isEmpty(), len, OutputList::lineBreak(), ArgumentList::size(), OutputList::startBold(), startFonts(), QCString::stripPrefix(), QCString::stripWhiteSpace(), TRUE, and w.
Referenced by writeVHDLDeclaration().
writeFunctionProto() [2/2]
static void VhdlDocGen::writeFunctionProto (OutputList & ol, const ArgumentList & al, const MemberDef *) [static]
writeInlineClassLink() [1/2]
void VhdlDocGen::writeInlineClassLink (const ClassDef * cd, OutputList & ol) [static]
writes an inline link form entity|package to architecture|package body and vice verca
Definition at line 828 of file vhdldocgen.cpp.
{
  std::vector<QCString> ql;
  QCString nn=cd->className();
  VhdlClasses ii=convert(cd->protection());
  QCString type;
  if (ii==VhdlDocGen::ENTITYCLASS)
    type+=theTranslator_vhdlType(VhdlDocGen::ENTITY,TRUE);
  else if (ii==VhdlDocGen::ARCHITECTURECLASS)
    type+=theTranslator_vhdlType(VhdlDocGen::ARCHITECTURE,TRUE);
  else if (ii==VhdlDocGen::PACKBODYCLASS)
    type+=theTranslator_vhdlType(VhdlDocGen::PACKAGE_BODY,TRUE);
  else if (ii==VhdlDocGen::PACKAGECLASS)
    type+=theTranslator_vhdlType(VhdlDocGen::PACKAGE,TRUE);
  else
    type+="";
  //type=type.lower();
  type+=" >> ";
  ol.disable(OutputGenerator::RTF);
  ol.disable(OutputGenerator::Man);
  if (ii==VhdlDocGen::PACKBODYCLASS)
  {
    nn.stripPrefix("_");
    cd=getClass(nn);
  }
  else if (ii==VhdlDocGen::PACKAGECLASS)
  {
    nn.prepend("_");
    cd=getClass(nn);
  }
  else if (ii==VhdlDocGen::ARCHITECTURECLASS)
  {
    StringVector qlist=split(nn.str(),"-");
    if (qlist.size()>1)
    {
      nn=qlist[1];
      cd=VhdlDocGen::getClass(nn);
    }
  }
  QCString opp;
  if (ii==VhdlDocGen::ENTITYCLASS)
  {
    VhdlDocGen::findAllArchitectures(ql,cd);
    for (const auto &s : ql)
    {
      StringVector qlist=split(s.str(),"-");
      if (qlist.size()>2)
      {
        QCString s1(qlist[0]);
        QCString s2(qlist[1]);
        s1.stripPrefix("_");
        if (ql.size()==1) s1.resize(0);
        ClassDef *cc = getClass(s);
        if (cc)
        {
          VhdlDocGen::writeVhdlLink(cc,ol,type,s2,s1);
        }
      }
    }
  }
  else
  {
    VhdlDocGen::writeVhdlLink(cd,ol,type,nn,opp);
  }
  ol.enable(OutputGenerator::Man);
  ol.enable(OutputGenerator::RTF);
}// write
References ARCHITECTURE, ARCHITECTURECLASS, ClassDef::className(), convert(), OutputList::disable(), OutputList::enable(), ENTITY, ENTITYCLASS, findAllArchitectures(), getClass(), OutputGenerator::Man, PACKAGE, PACKAGE_BODY, PACKAGECLASS, PACKBODYCLASS, QCString::prepend(), ClassDef::protection(), QCString::resize(), OutputGenerator::RTF, s, split(), QCString::str(), QCString::stripPrefix(), theTranslator_vhdlType, TRUE, and writeVhdlLink().
Referenced by ClassDefImpl::writeMemberDeclarations().
writeInlineClassLink() [2/2]
static void VhdlDocGen::writeInlineClassLink (const ClassDef * , OutputList & ol) [static]
writeOverview() [1/4]
void VhdlDocGen::writeOverview () [static]
Definition at line 175 of file vhdldocgen.cpp.
{
  bool found=FALSE;
  for (const auto &cd : *Doxygen::classLinkedMap)
  {
    if (VhdlDocGen::convert(cd->protection())==VhdlDocGen::ENTITYCLASS)
    {
      found=TRUE;
      break;
    }
  }
  if (!found) return;
  QCString ov =Config_getString(HTML_OUTPUT);
  QCString fileName=ov+"/vhdl_design.dot";
  std::ofstream f(fileName.str(),std::ofstream::out | std::ofstream::binary);
  if (!f.is_open())
  {
    err("Warning: Cannot open file %s for writing\n",qPrint(fileName));
    return;
  }
  TextStream t(&f);
  startDot(t);
  for (const auto &cd : *Doxygen::classLinkedMap)
  {
    if (VhdlDocGen::convert(cd->protection())!=VhdlDocGen::ENTITYCLASS)
    {
      continue;
    }
    std::vector<const MemberDef *> ports = getPorts(cd.get());
    if (ports.empty())
    {
      continue;
    }
    startTable(t,cd->name());
    writeClassToDot(t,cd.get());
    writeTable(ports,t);
    endTable(t);
    writeVhdlEntityToolTip(t,cd.get());
    for (const auto &bcd : cd->baseClasses())
    {
      ClassDef *bClass=bcd.classDef;
      QCString dotn=cd->name()+":";
      dotn+=cd->name();
      QCString csc=bClass->name()+":";
      csc+=bClass->name();
      // fprintf(stderr,"\n <%s| %s>",qPrint(dotn),qPrint(csc));
      writeVhdlDotLink(t,dotn,csc,QCString());
    }
  }// for
  endDot(t);
  // writePortLinks(t);
  t.flush();
  f.close();
  createSVG();
}
References Doxygen::classLinkedMap, Config_getString, convert(), createSVG(), endDot(), endTable(), ENTITYCLASS, err(), f, FALSE, TextStream::flush(), found, getPorts(), Definition::name(), out, qPrint(), startDot(), startTable(), QCString::str(), TRUE, writeClassToDot(), writeTable(), writeVhdlDotLink(), and writeVhdlEntityToolTip().
writeOverview() [2/4]
static void VhdlDocGen::writeOverview () [static]
writeOverview() [3/4]
static void VhdlDocGen::writeOverview (OutputList & ol) [static]
writeOverview() [4/4]
static void VhdlDocGen::writeOverview (OutputList & ol) [static]
writePlainVHDLDeclarations() [1/2]
void VhdlDocGen::writePlainVHDLDeclarations (const MemberList * ml, OutputList & ol, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd, uint64_t specifier) [static]
Definition at line 2044 of file vhdldocgen.cpp.
{
  StringSet pack;
  bool first=TRUE;
  for (const auto &imd : *mlist)
  {
    MemberDefMutable *md = toMemberDefMutable(imd);
    if (md)
    {
      uint64_t mems=md->getMemberSpecifiers();
      if (md->isBriefSectionVisible() && (mems==specifier) && (mems!=VhdlDocGen::LIBRARY))
      {
        if (first) { ol.startMemberList();first=FALSE; }
        VhdlDocGen::writeVHDLDeclaration(md,ol,cd,nd,fd,gd,FALSE);
      } //if
      else if (md->isBriefSectionVisible() && (mems==specifier))
      {
        if (pack.find(md->name().str())==pack.end())
        {
          if (first) ol.startMemberList(),first=FALSE;
          VhdlDocGen::writeVHDLDeclaration(md,ol,cd,nd,fd,gd,FALSE);
          pack.insert(md->name().str());
        }
      } //if
    } //if
  } //for
  if (!first) ol.endMemberList();
}//plainDeclaration
References OutputList::endMemberList(), FALSE, MemberDef::getMemberSpecifiers(), MemberDef::isBriefSectionVisible(), LIBRARY, Definition::name(), OutputList::startMemberList(), QCString::str(), toMemberDefMutable(), TRUE, and writeVHDLDeclaration().
Referenced by writeVHDLDeclarations().
writePlainVHDLDeclarations() [2/2]
static void VhdlDocGen::writePlainVHDLDeclarations (const MemberList * ml, OutputList & ol, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd, uint64_t specifier) [static]
writeProcedureProto() [1/2]
void VhdlDocGen::writeProcedureProto (OutputList & ol, const ArgumentList & al, const MemberDef * mdef) [static]
writes a procedure prototype to the output
Definition at line 1268 of file vhdldocgen.cpp.
{
  bool sem=FALSE;
  size_t len=al.size();
  ol.docify("(");
  if (len > 2)
  {
    ol.lineBreak();
  }
  for (const Argument &arg : al)
  {
    ol.startBold();
    if (sem && len <3)
      ol.writeChar(',');
    QCString nn=arg.name;
    nn+=": ";
    QCString defval = arg.defval;
    const char *str=VhdlDocGen::findKeyWord(defval);
    defval+=" ";
    if (str)
    {
      startFonts(defval,str,ol);
    }
    else
    {
      startFonts(defval,"vhdlchar",ol); // write type (variable,constant etc.)
    }
    startFonts(nn,"vhdlchar",ol); // write name
    if (qstricmp(arg.attrib,arg.type) != 0)
    {
      startFonts(arg.attrib.lower(),"stringliteral",ol); // write in|out
    }
    ol.docify(" ");
    VhdlDocGen::formatString(arg.type,ol,mdef);
    sem=TRUE;
    ol.endBold();
    if (len > 2)
    {
      ol.lineBreak();
      ol.docify(" ");
    }
  }//for
  ol.docify(")");
}
References OutputList::docify(), OutputList::endBold(), FALSE, findKeyWord(), formatString(), len, OutputList::lineBreak(), qstricmp(), ArgumentList::size(), OutputList::startBold(), startFonts(), TRUE, and OutputList::writeChar().
Referenced by writeVHDLDeclaration().
writeProcedureProto() [2/2]
static void VhdlDocGen::writeProcedureProto (OutputList & ol, const ArgumentList & al, const MemberDef *) [static]
writeProcessProto() [1/2]
void VhdlDocGen::writeProcessProto (OutputList & ol, const ArgumentList & al, const MemberDef * mdef) [static]
writes a process prototype to the output
Definition at line 1401 of file vhdldocgen.cpp.
{
  if (!al.hasParameters()) return;
  bool sem=FALSE;
  ol.startBold();
  ol.docify(" (");
  for (const Argument &arg : al)
  {
    if (sem)
    {
      ol.docify(" , ");
    }
    QCString nn=arg.name;
    // startFonts(nn,"vhdlchar",ol);
    VhdlDocGen::writeFormatString(nn,ol,mdef);
    sem=TRUE;
  }
  ol.docify(")");
  ol.endBold();
}
References OutputList::docify(), OutputList::endBold(), FALSE, ArgumentList::hasParameters(), OutputList::startBold(), TRUE, and writeFormatString().
Referenced by writeVHDLDeclaration().
writeProcessProto() [2/2]
static void VhdlDocGen::writeProcessProto (OutputList & ol, const ArgumentList & al, const MemberDef *) [static]
writeRecordProto() [1/2]
static void VhdlDocGen::writeRecordProto (const MemberDef * mdef, OutputList & ol, const ArgumentList & al) [static]
writeRecordProto() [2/2]
static void VhdlDocGen::writeRecordProto (const MemberDef * mdef, OutputList & ol, const ArgumentList & al) [static]
writeRecordUnit() [1/2]
void VhdlDocGen::writeRecordUnit (QCString & largs, QCString & ltype, OutputList & ol, const MemberDefMutable * mdef) [static], [private]
Definition at line 2611 of file vhdldocgen.cpp.
{
  int i=mdef->name().find('~');
  if (i>0)
  {
    //sets the real record member name
    const_cast<MemberDefMutable*>(mdef)->setName(mdef->name().left(i));
  }
  writeLink(mdef,ol);
  ol.startBold();
  ol.insertMemberAlign();
  if (!ltype.isEmpty()){
    VhdlDocGen::formatString(ltype,ol,mdef);
  }
  ol.endBold();
}
References OutputList::endBold(), QCString::find(), formatString(), OutputList::insertMemberAlign(), QCString::isEmpty(), QCString::left(), Definition::name(), OutputList::startBold(), and writeLink().
Referenced by writeVHDLDeclaration().
writeRecordUnit() [2/2]
static void VhdlDocGen::writeRecordUnit (QCString & largs, QCString & ltype, OutputList & ol, const MemberDefMutable * mdef) [static], [private]
writeRecUnitDocu() [1/2]
void VhdlDocGen::writeRecUnitDocu (const MemberDef * md, OutputList & ol, QCString largs) [static], [private]
Definition at line 2630 of file vhdldocgen.cpp.
{
  StringVector ql=split(largs.str(),"#");
  size_t len=ql.size();
  ol.startParameterList(TRUE);
  bool first=TRUE;
  for(size_t i=0;i<len;i++)
  {
    QCString n=QCString(ql[i]);
    ol.startParameterType(first,"");
    ol.endParameterType();
    ol.startParameterName(TRUE);
    VhdlDocGen::formatString(n,ol,md);
    if ((len-i)>1)
    {
      ol.endParameterName(FALSE,FALSE,FALSE);
    }
    else
    {
      ol.endParameterName(TRUE,FALSE,TRUE);
    }
    first=FALSE;
  }
}//#
References OutputList::endParameterName(), OutputList::endParameterType(), FALSE, formatString(), len, n, split(), OutputList::startParameterList(), OutputList::startParameterName(), OutputList::startParameterType(), QCString::str(), and TRUE.
Referenced by writeVHDLTypeDocumentation().
writeRecUnitDocu() [2/2]
static void VhdlDocGen::writeRecUnitDocu (const MemberDef * md, OutputList & ol, QCString largs) [static], [private]
writeSource() [1/2]
void VhdlDocGen::writeSource (const MemberDefMutable * mdef, OutputList & ol, const QCString & cname) [static]
Definition at line 2190 of file vhdldocgen.cpp.
{
  auto intf = Doxygen::parserManager->getCodeParser(".vhd");
 // pIntf->resetCodeParserState();
  QCString codeFragment=mdef->documentation();
  if (cname.isEmpty())
  {
    writeLink(mdef,ol);
    int fi=0;
    int j=0;
    do
    {
     fi=codeFragment.find("\n",++fi);
    } while(fi>=0 && j++ <3);
    // show only the first four lines
    if (j==4)
    {
      codeFragment=codeFragment.left(fi);
      codeFragment.append("\n .... ");
    }
  }
  codeFragment.prepend("\n");
  ol.pushGeneratorState();
  ol.startCodeFragment("DoxyCode");
  intf->parseCode(ol, // codeOutIntf
                       QCString(), // scope
                       codeFragment, // input
                       SrcLangExt_VHDL, // lang
                       FALSE, // isExample
                       QCString(), // exampleName
                       const_cast<FileDef*>(mdef->getFileDef()), // fileDef
                       mdef->getStartBodyLine(), // startLine
                       mdef->getEndBodyLine(), // endLine
                       TRUE, // inlineFragment
                       mdef, // memberDef
                       TRUE // show line numbers
                      );
  ol.endCodeFragment("DoxyCode");
  ol.popGeneratorState();
  if (cname.isEmpty()) return;
  mdef->writeSourceDef(ol,cname);
  if (mdef->hasReferencesRelation()) mdef->writeSourceRefs(ol,cname);
  if (mdef->hasReferencedByRelation()) mdef->writeSourceReffedBy(ol,cname);
}
References QCString::append(), MemberDef::documentation(), OutputList::endCodeFragment(), FALSE, QCString::find(), ParserManager::getCodeParser(), Definition::getEndBodyLine(), MemberDef::getFileDef(), Definition::getStartBodyLine(), MemberDef::hasReferencedByRelation(), MemberDef::hasReferencesRelation(), QCString::isEmpty(), QCString::left(), Doxygen::parserManager, OutputList::popGeneratorState(), QCString::prepend(), OutputList::pushGeneratorState(), SrcLangExt_VHDL, OutputList::startCodeFragment(), TRUE, writeLink(), DefinitionMutable::writeSourceDef(), DefinitionMutable::writeSourceReffedBy(), and DefinitionMutable::writeSourceRefs().
Referenced by MemberDefImpl::writeDocumentation(), and writeVHDLDeclaration().
writeSource() [2/2]
static void VhdlDocGen::writeSource (const MemberDefMutable * mdef, OutputList & ol, const QCString & cname) [static]
writeStringLink() [1/2]
void VhdlDocGen::writeStringLink (const MemberDef * mdef, QCString mem, OutputList & ol) [static], [private]
writes a link if the string is linkable else a formatted string
Definition at line 2166 of file vhdldocgen.cpp.
{
  if (mdef)
  {
    const ClassDef *cd=mdef->getClassDef();
    if (cd)
    {
      QCString n=cd->name();
      const MemberDef* memdef=VhdlDocGen::findMember(n,mem);
      if (memdef && memdef->isLinkable())
      {
        ol.startBold();
        writeLink(memdef,ol);
        ol.endBold();
        ol.docify(" ");
        return;
      }
    }
  }
  startFonts(mem,"vhdlchar",ol);
}// found component
References OutputList::docify(), OutputList::endBold(), findMember(), MemberDef::getClassDef(), MemberDef::isLinkable(), n, Definition::name(), OutputList::startBold(), startFonts(), and writeLink().
Referenced by writeFormatString().
writeStringLink() [2/2]
static void VhdlDocGen::writeStringLink (const MemberDef * mdef, QCString mem, OutputList & ol) [static], [private]
writeTagFile() [1/2]
void VhdlDocGen::writeTagFile (MemberDefMutable * mdef, TextStream & tagFile) [static]
Definition at line 1701 of file vhdldocgen.cpp.
{
  tagFile << " <member kind=\"";
  if (VhdlDocGen::isGeneric(mdef)) tagFile << "generic";
  if (VhdlDocGen::isPort(mdef)) tagFile << "port";
  if (VhdlDocGen::isEntity(mdef)) tagFile << "entity";
  if (VhdlDocGen::isComponent(mdef)) tagFile << "component";
  if (VhdlDocGen::isVType(mdef)) tagFile << "type";
  if (VhdlDocGen::isConstant(mdef)) tagFile << "constant";
  if (VhdlDocGen::isSubType(mdef)) tagFile << "subtype";
  if (VhdlDocGen::isVhdlFunction(mdef)) tagFile << "function";
  if (VhdlDocGen::isProcedure(mdef)) tagFile << "procedure";
  if (VhdlDocGen::isProcess(mdef)) tagFile << "process";
  if (VhdlDocGen::isSignals(mdef)) tagFile << "signal";
  if (VhdlDocGen::isAttribute(mdef)) tagFile << "attribute";
  if (VhdlDocGen::isRecord(mdef)) tagFile << "record";
  if (VhdlDocGen::isLibrary(mdef)) tagFile << "library";
  if (VhdlDocGen::isPackage(mdef)) tagFile << "package";
  if (VhdlDocGen::isVariable(mdef)) tagFile << "shared variable";
  if (VhdlDocGen::isFile(mdef)) tagFile << "file";
  if (VhdlDocGen::isGroup(mdef)) tagFile << "group";
  if (VhdlDocGen::isCompInst(mdef)) tagFile << "instantiation";
  if (VhdlDocGen::isAlias(mdef)) tagFile << "alias";
  if (VhdlDocGen::isCompInst(mdef)) tagFile << "configuration";
  tagFile << "\">\n";
  tagFile << " <type>" << convertToXML(mdef->typeString()) << "</type>\n";
  tagFile << " <name>" << convertToXML(mdef->name()) << "</name>\n";
  tagFile << " <anchorfile>" << convertToXML(addHtmlExtensionIfMissing(mdef->getOutputFileBase())) << "</anchorfile>\n";
  tagFile << " <anchor>" << convertToXML(mdef->anchor()) << "</anchor>\n";
  if (VhdlDocGen::isVhdlFunction(mdef))
    tagFile << " <arglist>" << convertToXML(VhdlDocGen::convertArgumentListToString(mdef->argumentList(),TRUE)) << "</arglist>\n";
  else if (VhdlDocGen::isProcedure(mdef))
    tagFile << " <arglist>" << convertToXML(VhdlDocGen::convertArgumentListToString(mdef->argumentList(),FALSE)) << "</arglist>\n";
  else
    tagFile << " <arglist>" << convertToXML(mdef->argsString()) << "</arglist>\n";
  mdef->writeDocAnchorsToTagFile(tagFile);
  tagFile << " </member>\n";
}
References addHtmlExtensionIfMissing(), MemberDef::anchor(), MemberDef::argsString(), MemberDef::argumentList(), convertArgumentListToString(), convertToXML(), FALSE, MemberDef::getOutputFileBase(), isAlias(), isAttribute(), isCompInst(), isComponent(), isConstant(), isEntity(), isFile(), isGeneric(), isGroup(), isLibrary(), isPackage(), isPort(), isProcedure(), isProcess(), isRecord(), isSignals(), isSubType(), isVariable(), isVhdlFunction(), isVType(), Definition::name(), TRUE, MemberDef::typeString(), and DefinitionMutable::writeDocAnchorsToTagFile().
Referenced by MemberList::writeTagFile().
writeTagFile() [2/2]
static void VhdlDocGen::writeTagFile (MemberDefMutable * mdef, TextStream & tagFile) [static]
writeVHDLDeclaration() [1/2]
void VhdlDocGen::writeVHDLDeclaration (const MemberDefMutable * mdef, OutputList & ol, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd, bool inGroup) [static]
printf(`startMemberItem for %s\n`,qPrint(name()));
Definition at line 1745 of file vhdldocgen.cpp.
{
  const Definition *d=0;
  ASSERT(cd!=0 || nd!=0 || fd!=0 || gd!=0 ||
      mdef->getMemberSpecifiers()==VhdlDocGen::LIBRARY ||
      mdef->getMemberSpecifiers()==VhdlDocGen::USE
      ); // member should belong to something
  if (cd) d=cd;
  else if (nd) d=nd;
  else if (fd) d=fd;
  else if (gd) d=gd;
  else d=mdef;
  // write search index info
  if (Doxygen::searchIndex)
  {
    Doxygen::searchIndex->setCurrentDoc(mdef,mdef->anchor(),FALSE);
    Doxygen::searchIndex->addWord(mdef->localName(),TRUE);
    Doxygen::searchIndex->addWord(mdef->qualifiedName(),FALSE);
  }
  QCString cname = d->name();
  QCString cfname = d->getOutputFileBase();
  //HtmlHelp *htmlHelp=0;
  // bool hasHtmlHelp = Config_getBool(GENERATE_HTML) && Config_getBool(GENERATE_HTMLHELP);
  // if (hasHtmlHelp) htmlHelp = HtmlHelp::getInstance();
  // search for the last anonymous scope in the member type
  ClassDef *annoClassDef=mdef->getClassDefOfAnonymousType();
  // start a new member declaration
  uint isAnonymous = annoClassDef!=0; // || m_impl->annMemb || m_impl->annEnumType;
  uint64_t mm=mdef->getMemberSpecifiers();
  if (mm==VhdlDocGen::MISCELLANEOUS)
      isAnonymous=3;
   ol.startMemberItem(mdef->anchor(), isAnonymous); //? 1 : m_impl->tArgList ? 3 : 0);
  // If there is no detailed description we need to write the anchor here.
  bool detailsVisible = mdef->hasDetailedDescription();
  if (!detailsVisible) // && !m_impl->annMemb)
  {
    QCString doxyName=mdef->name();
    if (!cname.isEmpty()) doxyName.prepend(cname+"::");
    QCString doxyArgs=mdef->argsString();
    ol.startDoxyAnchor(cfname,cname,mdef->anchor(),doxyName,doxyArgs);
    ol.pushGeneratorState();
    ol.disable(OutputGenerator::Man);
    ol.disable(OutputGenerator::Latex);
    ol.docify("\n");
    ol.popGeneratorState();
  }
  // *** write type
  /*VHDL CHANGE */
  QCString ltype(mdef->typeString());
  QCString largs(mdef->argsString());
  ClassDef *kl=0;
  const ArgumentList &al = mdef->argumentList();
  QCString nn;
  //VhdlDocGen::adjustRecordMember(mdef);
  if (gd) gd=0;
  switch (mm)
  {
    case VhdlDocGen::MISCELLANEOUS:
      VhdlDocGen::writeSource(mdef,ol,nn);
      break;
    case VhdlDocGen::PROCEDURE:
    case VhdlDocGen::FUNCTION:
      ol.startBold();
      VhdlDocGen::formatString(ltype,ol,mdef);
      ol.endBold();
      ol.insertMemberAlign();
      ol.docify(" ");
      writeLink(mdef,ol);
      if (al.hasParameters() && mm==VhdlDocGen::FUNCTION)
        VhdlDocGen::writeFunctionProto(ol,al,mdef);
      if (al.hasParameters() && mm==VhdlDocGen::PROCEDURE)
        VhdlDocGen::writeProcedureProto(ol,al,mdef);
      break;
    case VhdlDocGen::USE:
      kl=VhdlDocGen::getClass(mdef->name());
      if (kl && (VhdlDocGen::convert(kl->protection())==VhdlDocGen::ENTITYCLASS)) break;
      writeLink(mdef,ol);
      ol.insertMemberAlign();
      ol.docify(" ");
      if (kl)
      {
        nn=kl->getOutputFileBase();
        ol.pushGeneratorState();
        ol.disableAllBut(OutputGenerator::Html);
        ol.docify(" ");
        QCString name=theTranslator_vhdlType(VhdlDocGen::PACKAGE,TRUE);
        ol.startBold();
        ol.docify(name);
        name.resize(0);
        ol.endBold();
        name+=" <"+mdef->name()+">";
        ol.startEmphasis();
        ol.writeObjectLink(kl->getReference(),kl->getOutputFileBase(),QCString(),name);
        ol.popGeneratorState();
      }
      break;
    case VhdlDocGen::LIBRARY:
      writeLink(mdef,ol);
      ol.insertMemberAlign();
      if (largs=="context")
      {
        VhdlDocGen::writeRecordUnit(ltype,largs,ol,mdef);
      }
      break;
    case VhdlDocGen::GENERIC:
    case VhdlDocGen::PORT:
    case VhdlDocGen::ALIAS:
      writeLink(mdef,ol);
      ol.docify(" ");
      if (mm==VhdlDocGen::GENERIC)
      {
        ol.insertMemberAlign();
        ol.startBold();
        VhdlDocGen::formatString(largs,ol,mdef);
        ol.endBold();
      }
      else
      {
        ol.insertMemberAlignLeft(isAnonymous, false);
        ol.docify(" ");
        ol.startBold();
        VhdlDocGen::formatString(ltype,ol,mdef);
        ol.endBold();
        ol.insertMemberAlign();
        ol.docify(" ");
        VhdlDocGen::formatString(largs,ol,mdef);
      }
      break;
    case VhdlDocGen::PROCESS:
      writeLink(mdef,ol);
      ol.insertMemberAlign();
      VhdlDocGen::writeProcessProto(ol,al,mdef);
      break;
    case VhdlDocGen::PACKAGE:
    case VhdlDocGen::ENTITY:
    case VhdlDocGen::COMPONENT:
    case VhdlDocGen::INSTANTIATION:
    case VhdlDocGen::CONFIG:
      if (VhdlDocGen::isCompInst(mdef))
      {
        nn=largs;
        if(nn.stripPrefix("function") || nn.stripPrefix("package"))
        {
          VhdlDocGen::formatString(largs,ol,mdef);
          ol.insertMemberAlign();
          writeLink(mdef,ol);
          ol.docify(" ");
          VhdlDocGen::formatString(ltype,ol,mdef);
          break;
        }
        largs.prepend("::");
        largs.prepend(mdef->name());
        ol.writeObjectLink(mdef->getReference(),
            cfname,
            mdef->anchor(),
            mdef->name());
      }
      else
        writeLink(mdef,ol);
      ol.insertMemberAlign();
      ol.docify(" ");
      ol.startBold();
      ol.docify(ltype);
      ol.endBold();
      ol.docify(" ");
      if (VhdlDocGen::isComponent(mdef) ||
          VhdlDocGen::isConfig(mdef) ||
          VhdlDocGen::isCompInst(mdef))
      {
        if (VhdlDocGen::isConfig(mdef) || VhdlDocGen::isCompInst(mdef))
        {
          nn=ltype;
        }
        else
        {
          nn=mdef->name();
        }
        kl=getClass(nn);
        if (kl)
        {
          nn=kl->getOutputFileBase();
          ol.pushGeneratorState();
          ol.disableAllBut(OutputGenerator::Html);
          ol.startEmphasis();
          QCString name("<Entity ");
          if (VhdlDocGen::isConfig(mdef) || VhdlDocGen::isCompInst(mdef))
          {
            name+=ltype+">";
          }
          else
          {
            name+=mdef->name()+"> ";
          }
          ol.writeObjectLink(kl->getReference(),kl->getOutputFileBase(),QCString(),name);
          ol.endEmphasis();
          ol.popGeneratorState();
        }
      }
      break;
    case VhdlDocGen::UCF_CONST:
      writeUCFLink(mdef,ol);
      break;
    case VhdlDocGen::SIGNAL:
    case VhdlDocGen::ATTRIBUTE:
    case VhdlDocGen::SUBTYPE:
    case VhdlDocGen::CONSTANT:
    case VhdlDocGen::SHAREDVARIABLE:
    case VhdlDocGen::VFILE:
    case VhdlDocGen::GROUP:
    case VhdlDocGen::TYPE:
      writeLink(mdef,ol);
      ol.docify(" ");
      ol.insertMemberAlign();
      VhdlDocGen::formatString(ltype,ol,mdef);
      break;
    case VhdlDocGen::RECORD:
    case VhdlDocGen::UNITS:
     writeRecordUnit(largs,ltype,ol,mdef);
      break;
    default: break;
  }
  bool htmlOn = ol.isEnabled(OutputGenerator::Html);
  if (htmlOn && /*Config_getBool(HTML_ALIGN_MEMBERS) &&*/ !ltype.isEmpty())
  {
    ol.disable(OutputGenerator::Html);
  }
  if (!ltype.isEmpty()) ol.docify(" ");
  if (htmlOn)
  {
    ol.enable(OutputGenerator::Html);
  }
  if (!detailsVisible)// && !m_impl->annMemb)
  {
    ol.endDoxyAnchor(cfname,mdef->anchor());
  }
  ol.endMemberItem();
  if (!mdef->briefDescription().isEmpty() && Config_getBool(BRIEF_MEMBER_DESC) /* && !annMemb */)
  {
    QCString s=mdef->briefDescription();
    ol.startMemberDescription(mdef->anchor(), QCString(), mm == VhdlDocGen::PORT);
    ol.generateDoc(mdef->briefFile(),mdef->briefLine(),
                   mdef->getOuterScope()?mdef->getOuterScope():d,
                   mdef,s,TRUE,FALSE,
                   QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    if (detailsVisible)
    {
      ol.pushGeneratorState();
      ol.disableAllBut(OutputGenerator::Html);
      //ol.endEmphasis();
      ol.docify(" ");
      if (mdef->getGroupDef()!=0 && gd==0) // forward link to the group
      {
        ol.startTextLink(mdef->getOutputFileBase(),mdef->anchor());
      }
      else // local link
      {
        ol.startTextLink(QCString(),mdef->anchor());
      }
      ol.endTextLink();
      //ol.startEmphasis();
      ol.popGeneratorState();
    }
    //ol.newParagraph();
    ol.endMemberDescription();
  }
  mdef->warnIfUndocumented();
}// end writeVhdlDeclaration
References SearchIndexIntf::addWord(), ALIAS, MemberDef::anchor(), MemberDef::argsString(), MemberDef::argumentList(), ASSERT, ATTRIBUTE, MemberDef::briefDescription(), Definition::briefFile(), Definition::briefLine(), COMPONENT, CONFIG, Config_getBool, CONSTANT, convert(), OutputList::disable(), OutputList::disableAllBut(), OutputList::docify(), OutputList::enable(), OutputList::endBold(), OutputList::endDoxyAnchor(), OutputList::endEmphasis(), OutputList::endMemberDescription(), OutputList::endMemberItem(), OutputList::endTextLink(), ENTITY, ENTITYCLASS, FALSE, formatString(), FUNCTION, OutputList::generateDoc(), GENERIC, getClass(), MemberDef::getClassDefOfAnonymousType(), MemberDef::getGroupDef(), MemberDef::getMemberSpecifiers(), Definition::getOuterScope(), ClassDef::getOutputFileBase(), Definition::getOutputFileBase(), MemberDef::getOutputFileBase(), ClassDef::getReference(), MemberDef::getReference(), GROUP, MemberDef::hasDetailedDescription(), ArgumentList::hasParameters(), OutputGenerator::Html, OutputList::insertMemberAlign(), OutputList::insertMemberAlignLeft(), INSTANTIATION, isCompInst(), isComponent(), isConfig(), QCString::isEmpty(), OutputList::isEnabled(), OutputGenerator::Latex, LIBRARY, Definition::localName(), OutputGenerator::Man, MISCELLANEOUS, setup::name, Definition::name(), PACKAGE, OutputList::popGeneratorState(), PORT, QCString::prepend(), PROCEDURE, PROCESS, ClassDef::protection(), OutputList::pushGeneratorState(), MemberDef::qualifiedName(), RECORD, s, Doxygen::searchIndex, SearchIndexIntf::setCurrentDoc(), SHAREDVARIABLE, SIGNAL, OutputList::startBold(), OutputList::startDoxyAnchor(), OutputList::startEmphasis(), OutputList::startMemberDescription(), OutputList::startMemberItem(), OutputList::startTextLink(), QCString::stripPrefix(), SUBTYPE, theTranslator_vhdlType, TRUE, TYPE, MemberDef::typeString(), UCF_CONST, UNITS, USE, VFILE, MemberDef::warnIfUndocumented(), writeFunctionProto(), writeLink(), OutputList::writeObjectLink(), writeProcedureProto(), writeProcessProto(), writeRecordUnit(), writeSource(), and writeUCFLink().
Referenced by writePlainVHDLDeclarations().
writeVHDLDeclaration() [2/2]
static void VhdlDocGen::writeVHDLDeclaration (const MemberDefMutable * mdef, OutputList & ol, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd, bool inGroup) [static]
writeVhdlDeclarations() [1/2]
void VhdlDocGen::writeVhdlDeclarations (const MemberList * ml, OutputList & ol, const GroupDef * gd, const ClassDef * cd, const FileDef * fd, const NamespaceDef * nd) [static]
Definition at line 1538 of file vhdldocgen.cpp.
{
  VhdlDocGen::writeVHDLDeclarations(ml,ol,cd,nd,fd,gd,theTranslator_vhdlType(VhdlDocGen::LIBRARY,FALSE),QCString(),FALSE,VhdlDocGen::LIBRARY);
  VhdlDocGen::writeVHDLDeclarations(ml,ol,cd,nd,fd,gd,theTranslator_vhdlType(VhdlDocGen::USE,FALSE),QCString(),FALSE,VhdlDocGen::USE);
  VhdlDocGen::writeVHDLDeclarations(ml,ol,cd,nd,fd,gd,theTranslator_vhdlType(VhdlDocGen::FUNCTION,FALSE),QCString(),FALSE,VhdlDocGen::FUNCTION);
  VhdlDocGen::writeVHDLDeclarations(ml,ol,cd,nd,fd,gd,theTranslator_vhdlType(VhdlDocGen::COMPONENT,FALSE),QCString(),FALSE,VhdlDocGen::COMPONENT);
  VhdlDocGen::writeVHDLDeclarations(ml,ol,cd,nd,fd,gd,theTranslator_vhdlType(VhdlDocGen::CONSTANT,FALSE),QCString(),FALSE,VhdlDocGen::CONSTANT);
  VhdlDocGen::writeVHDLDeclarations(ml,ol,cd,nd,fd,gd,theTranslator_vhdlType(VhdlDocGen::TYPE,FALSE),QCString(),FALSE,VhdlDocGen::TYPE);
  VhdlDocGen::writeVHDLDeclarations(ml,ol,cd,nd,fd,gd,theTranslator_vhdlType(VhdlDocGen::SUBTYPE,FALSE),QCString(),FALSE,VhdlDocGen::SUBTYPE);
  VhdlDocGen::writeVHDLDeclarations(ml,ol,cd,nd,fd,gd,theTranslator_vhdlType(VhdlDocGen::GENERIC,FALSE),QCString(),FALSE,VhdlDocGen::GENERIC);
  VhdlDocGen::writeVHDLDeclarations(ml,ol,cd,nd,fd,gd,theTranslator_vhdlType(VhdlDocGen::PORT,FALSE),QCString(),FALSE,VhdlDocGen::PORT);
  VhdlDocGen::writeVHDLDeclarations(ml,ol,cd,nd,fd,gd,theTranslator_vhdlType(VhdlDocGen::PROCESS,FALSE),QCString(),FALSE,VhdlDocGen::PROCESS);
  VhdlDocGen::writeVHDLDeclarations(ml,ol,cd,nd,fd,gd,theTranslator_vhdlType(VhdlDocGen::SIGNAL,FALSE),QCString(),FALSE,VhdlDocGen::SIGNAL);
  VhdlDocGen::writeVHDLDeclarations(ml,ol,cd,nd,fd,gd,theTranslator_vhdlType(VhdlDocGen::ATTRIBUTE,FALSE),QCString(),FALSE,VhdlDocGen::ATTRIBUTE);
  VhdlDocGen::writeVHDLDeclarations(ml,ol,cd,nd,fd,gd,theTranslator_vhdlType(VhdlDocGen::PROCEDURE,FALSE),QCString(),FALSE,VhdlDocGen::PROCEDURE);
  VhdlDocGen::writeVHDLDeclarations(ml,ol,cd,nd,fd,gd,theTranslator_vhdlType(VhdlDocGen::RECORD,FALSE),QCString(),FALSE,VhdlDocGen::RECORD);
  VhdlDocGen::writeVHDLDeclarations(ml,ol,cd,nd,fd,gd,theTranslator_vhdlType(VhdlDocGen::UNITS,FALSE),QCString(),FALSE,VhdlDocGen::UNITS);
  VhdlDocGen::writeVHDLDeclarations(ml,ol,cd,nd,fd,gd,theTranslator_vhdlType(VhdlDocGen::SHAREDVARIABLE,FALSE),QCString(),FALSE,VhdlDocGen::SHAREDVARIABLE);
  VhdlDocGen::writeVHDLDeclarations(ml,ol,cd,nd,fd,gd,theTranslator_vhdlType(VhdlDocGen::VFILE,FALSE),QCString(),FALSE,VhdlDocGen::VFILE);
  VhdlDocGen::writeVHDLDeclarations(ml,ol,cd,nd,fd,gd,theTranslator_vhdlType(VhdlDocGen::GROUP,FALSE),QCString(),FALSE,VhdlDocGen::GROUP);
  VhdlDocGen::writeVHDLDeclarations(ml,ol,cd,nd,fd,gd,theTranslator_vhdlType(VhdlDocGen::INSTANTIATION,FALSE),QCString(),FALSE,VhdlDocGen::INSTANTIATION);
  VhdlDocGen::writeVHDLDeclarations(ml,ol,cd,nd,fd,gd,theTranslator_vhdlType(VhdlDocGen::ALIAS,FALSE),QCString(),FALSE,VhdlDocGen::ALIAS);
  VhdlDocGen::writeVHDLDeclarations(ml,ol,cd,nd,fd,gd,theTranslator_vhdlType(VhdlDocGen::MISCELLANEOUS,TRUE),QCString(),FALSE,VhdlDocGen::MISCELLANEOUS);
  // configurations must be added to global file definitions.
  VhdlDocGen::writeVHDLDeclarations(ml,ol,cd,nd,fd,gd,theTranslator_vhdlType(VhdlDocGen::CONFIG,FALSE),QCString(),FALSE,VhdlDocGen::CONFIG);
  VhdlDocGen::writeVHDLDeclarations(ml,ol,cd,nd,fd,gd,theTranslator_vhdlType(VhdlDocGen::UCF_CONST,FALSE),QCString(),FALSE,VhdlDocGen::UCF_CONST);
}
References ALIAS, ATTRIBUTE, COMPONENT, CONFIG, CONSTANT, FALSE, FUNCTION, GENERIC, GROUP, INSTANTIATION, LIBRARY, MISCELLANEOUS, PORT, PROCEDURE, PROCESS, RECORD, SHAREDVARIABLE, SIGNAL, SUBTYPE, theTranslator_vhdlType, TRUE, TYPE, UCF_CONST, UNITS, USE, VFILE, and writeVHDLDeclarations().
Referenced by MemberList::writeDeclarations(), ClassDefImpl::writeMemberDeclarations(), FileDefImpl::writeMemberDeclarations(), and GroupDefImpl::writeMemberDeclarations().
writeVhdlDeclarations() [2/2]
static void VhdlDocGen::writeVhdlDeclarations (const MemberList * , OutputList & , const GroupDef * , const ClassDef * , const FileDef * , const NamespaceDef *) [static]
writeVHDLDeclarations() [1/2]
void VhdlDocGen::writeVHDLDeclarations (const MemberList * ml, OutputList & ol, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd, const QCString & title, const QCString & subtitle, bool showEnumValues, int type) [static]
Definition at line 2097 of file vhdldocgen.cpp.
{
  if (!membersHaveSpecificType(ml,type)) return;
  if (!title.isEmpty())
  {
    ol.startMemberHeader(convertToId(title),type == VhdlDocGen::PORT ? 3 : 2);
    ol.parseText(title);
    ol.endMemberHeader();
    ol.docify(" ");
  }
  if (!subtitle.isEmpty())
  {
    ol.startMemberSubtitle();
    ol.generateDoc("[generated]",-1,0,0,subtitle,FALSE,FALSE,
                   QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    ol.endMemberSubtitle();
  } //printf("memberGroupList=%p\n",memberGroupList);
  VhdlDocGen::writePlainVHDLDeclarations(ml,ol,cd,nd,fd,gd,type);
  for (const auto &mg : ml->getMemberGroupList())
  {
    if (membersHaveSpecificType(&mg->members(),type))
    {
      //printf("mg->header=%s\n",qPrint(mg->header()));
      bool hasHeader=!mg->header().isEmpty();
      ol.startMemberGroupHeader(hasHeader);
      if (hasHeader)
      {
        ol.parseText(mg->header());
      }
      ol.endMemberGroupHeader();
      if (!mg->documentation().isEmpty())
      {
        //printf("Member group has docs!\n");
        ol.startMemberGroupDocs();
        ol.generateDoc("[generated]",-1,0,0,mg->documentation()+"\n",FALSE,FALSE,
            QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
        ol.endMemberGroupDocs();
      }
      ol.startMemberGroup();
      //printf("--- mg->writePlainDeclarations ---\n");
      VhdlDocGen::writePlainVHDLDeclarations(&mg->members(),ol,cd,nd,fd,gd,type);
      ol.endMemberGroup(hasHeader);
    }
  }
}// writeVHDLDeclarations
References Config_getBool, convertToId(), OutputList::docify(), OutputList::endMemberGroup(), OutputList::endMemberGroupDocs(), OutputList::endMemberGroupHeader(), OutputList::endMemberHeader(), OutputList::endMemberSubtitle(), FALSE, OutputList::generateDoc(), MemberList::getMemberGroupList(), QCString::isEmpty(), membersHaveSpecificType(), OutputList::parseText(), PORT, OutputList::startMemberGroup(), OutputList::startMemberGroupDocs(), OutputList::startMemberGroupHeader(), OutputList::startMemberHeader(), OutputList::startMemberSubtitle(), TRUE, and writePlainVHDLDeclarations().
Referenced by writeVhdlDeclarations().
writeVHDLDeclarations() [2/2]
static void VhdlDocGen::writeVHDLDeclarations (const MemberList * ml, OutputList & ol, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd, const QCString & title, const QCString & subtitle, bool showEnumValues, int type) [static]
writeVhdlLink() [1/2]
void VhdlDocGen::writeVhdlLink (const ClassDef * cdd, OutputList & ol, QCString & type, QCString & name, QCString & beh) [static], [private]
Definition at line 943 of file vhdldocgen.cpp.
{
  if (ccd==0) return;
  ol.startBold();
  ol.docify(type);
  ol.endBold();
  nn.stripPrefix("_");
  ol.writeObjectLink(ccd->getReference(),ccd->getOutputFileBase(),QCString(),nn);
  if (!behav.isEmpty())
  {
    behav.prepend(" ");
    ol.startBold();
    ol.docify(behav);
    ol.endBold();
  }
  ol.lineBreak();
}
References OutputList::docify(), OutputList::endBold(), ClassDef::getOutputFileBase(), ClassDef::getReference(), QCString::isEmpty(), OutputList::lineBreak(), QCString::prepend(), OutputList::startBold(), QCString::stripPrefix(), and OutputList::writeObjectLink().
Referenced by writeInlineClassLink().
writeVhdlLink() [2/2]
static void VhdlDocGen::writeVhdlLink (const ClassDef * cdd, OutputList & ol, QCString & type, QCString & name, QCString & beh) [static], [private]
writeVHDLTypeDocumentation() [1/2]
bool VhdlDocGen::writeVHDLTypeDocumentation (const MemberDef * mdef, const Definition * d, OutputList & ol) [static]
Definition at line 1617 of file vhdldocgen.cpp.
{
  const ClassDef *cd=toClassDef(d);
  bool hasParams = FALSE;
  if (cd==0) return hasParams;
  QCString ttype=mdef->typeString();
  QCString largs=mdef->argsString();
  if ((VhdlDocGen::isVhdlFunction(mdef) || VhdlDocGen::isProcedure(mdef) || VhdlDocGen::isProcess(mdef)))
  {
    QCString nn=mdef->typeString();
    nn=nn.stripWhiteSpace();
    QCString na=cd->name();
    const MemberDef* memdef=VhdlDocGen::findMember(na,nn);
    if (memdef && memdef->isLinkable())
    {
      ol.docify(" ");
      ol.startBold();
      writeLink(memdef,ol);
      ol.endBold();
      ol.docify(" ");
    }
    else
    {
      ol.docify(" ");
      VhdlDocGen::formatString(ttype,ol,mdef);
      ol.docify(" ");
    }
    ol.docify(mdef->name());
    hasParams = VhdlDocGen::writeFuncProcDocu(mdef,ol, mdef->argumentList());
  }
  if (mdef->isVariable())
  {
    if (VhdlDocGen::isConstraint(mdef))
    {
      writeLink(mdef,ol);
      ol.docify(" ");
      largs=substitute(largs,"#"," ");
      VhdlDocGen::formatString(largs,ol,mdef);
      return hasParams;
    }
    else
    {
      writeLink(mdef,ol);
      if (VhdlDocGen::isLibrary(mdef) || VhdlDocGen::isPackage(mdef))
      {
        return hasParams;
      }
      ol.docify(" ");
    }
    // QCString largs=mdef->argsString();
    bool c=largs=="context";
    bool brec=largs.stripPrefix("record") ;
    if (!brec && !c)
      VhdlDocGen::formatString(ttype,ol,mdef);
    if (c || brec || largs.stripPrefix("units"))
    {
      if (c)
      largs=ttype;
      VhdlDocGen::writeRecUnitDocu(mdef,ol,largs);
      return hasParams;
    }
    ol.docify(" ");
    if (VhdlDocGen::isPort(mdef) || VhdlDocGen::isGeneric(mdef))
    {
      // QCString largs=mdef->argsString();
      VhdlDocGen::formatString(largs,ol,mdef);
      ol.docify(" ");
    }
  }
  return hasParams;
}
References MemberDef::argsString(), MemberDef::argumentList(), c, OutputList::docify(), OutputList::endBold(), FALSE, findMember(), formatString(), isConstraint(), isGeneric(), isLibrary(), MemberDef::isLinkable(), isPackage(), isPort(), isProcedure(), isProcess(), MemberDef::isVariable(), isVhdlFunction(), Definition::name(), OutputList::startBold(), QCString::stripPrefix(), QCString::stripWhiteSpace(), substitute(), toClassDef(), MemberDef::typeString(), writeFuncProcDocu(), writeLink(), and writeRecUnitDocu().
Referenced by MemberDefImpl::writeDocumentation().
writeVHDLTypeDocumentation() [2/2]
static bool VhdlDocGen::writeVHDLTypeDocumentation (const MemberDef * mdef, const Definition * d, OutputList & ol) [static]
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/vhdldocgen.h
doxygen/src/vhdldocgen.h
doxygen/build/doxygen/src/vhdldocgen.cpp
doxygen/src/vhdldocgen.cpp