ClangTUParser Class Reference
Clang parser object for a single translation unit, which consists of a source file and the directly or indirectly included headers.
#include <clangparser.h>
Classes
class Private
Public Member Functions
ClangTUParser (const ClangParser &parser, const FileDef *fd)
virtual ~ClangTUParser ()
void parse ()
void switchToFile (const FileDef *fd)
StringVector filesInSameTU () const
std::string lookup (uint line, const char *symbol)
void writeSources (CodeOutputInterface &ol, const FileDef *fd)
ClangTUParser (const ClangParser &parser, const FileDef *fd)
virtual ~ClangTUParser ()
void parse ()
void switchToFile (const FileDef *fd)
StringVector filesInSameTU () const
std::string lookup (uint line, const char *symbol)
void writeSources (CodeOutputInterface &ol, const FileDef *fd)
Private Member Functions
void detectFunctionBody (const char *s)
void writeLineNumber (CodeOutputInterface &ol, const FileDef *fd, uint line, bool writeLineAnchor)
void codifyLines (CodeOutputInterface &ol, const FileDef *fd, const char *text, uint &line, uint &column, const char *fontClass=0)
void writeMultiLineCodeLink (CodeOutputInterface &ol, const FileDef *fd, uint &line, uint &column, const Definition *d, const char *text)
void linkIdentifier (CodeOutputInterface &ol, const FileDef *fd, uint &line, uint &column, const char *text, int tokenIndex)
void linkMacro (CodeOutputInterface &ol, const FileDef *fd, uint &line, uint &column, const char *text)
void linkInclude (CodeOutputInterface &ol, const FileDef *fd, uint &line, uint &column, const char *text)
ClangTUParser (const ClangTUParser &)=delete
ClangTUParser & operator= (const ClangTUParser &)=delete
void detectFunctionBody (const char *s)
void writeLineNumber (CodeOutputInterface &ol, const FileDef *fd, uint line, bool writeLineAnchor)
void codifyLines (CodeOutputInterface &ol, const FileDef *fd, const char *text, uint &line, uint &column, const char *fontClass=0)
void writeMultiLineCodeLink (CodeOutputInterface &ol, const FileDef *fd, uint &line, uint &column, const Definition *d, const char *text)
void linkIdentifier (CodeOutputInterface &ol, const FileDef *fd, uint &line, uint &column, const char *text, int tokenIndex)
void linkMacro (CodeOutputInterface &ol, const FileDef *fd, uint &line, uint &column, const char *text)
void linkInclude (CodeOutputInterface &ol, const FileDef *fd, uint &line, uint &column, const char *text)
ClangTUParser (const ClangTUParser &)=delete
ClangTUParser & operator= (const ClangTUParser &)=delete
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Clang parser object for a single translation unit, which consists of a source file and the directly or indirectly included headers.
Definition at line 21 of file clangparser.h.
Constructor & Destructor Documentation
ClangTUParser() [1/4]
ClangTUParser::ClangTUParser (const ClangParser & parser, const FileDef * fd)
Definition at line 923 of file clangparser.cpp.
                                                                : p(std::make_unique<Private>())
{
}
 ClangTUParser() [1/2]
ClangTUParser::~ClangTUParser () [virtual]
Definition at line 927 of file clangparser.cpp.
{
}
ClangTUParser() [2/4]
ClangTUParser::ClangTUParser (const ClangTUParser &) [private], [delete]
ClangTUParser() [3/4]
ClangTUParser::ClangTUParser (const ClangParser & parser, const FileDef * fd)
 ClangTUParser() [2/2]
virtual ClangTUParser::~ClangTUParser () [virtual]
ClangTUParser() [4/4]
ClangTUParser::ClangTUParser (const ClangTUParser &) [private], [delete]
Member Function Documentation
codifyLines() [1/2]
void ClangTUParser::codifyLines (CodeOutputInterface & ol, const FileDef * fd, const char * text, uint & line, uint & column, const char * fontClass = 0) [private]
codifyLines() [2/2]
void ClangTUParser::codifyLines (CodeOutputInterface & ol, const FileDef * fd, const char * text, uint & line, uint & column, const char * fontClass = 0) [private]
detectFunctionBody() [1/2]
void ClangTUParser::detectFunctionBody (const char * s) [private]
detectFunctionBody() [2/2]
void ClangTUParser::detectFunctionBody (const char * s) [private]
filesInSameTU() [1/2]
StringVector ClangTUParser::filesInSameTU () const
Returns the list of files for this translation unit
filesInSameTU() [2/2]
StringVector ClangTUParser::filesInSameTU () const
Returns the list of files for this translation unit
linkIdentifier() [1/2]
void ClangTUParser::linkIdentifier (CodeOutputInterface & ol, const FileDef * fd, uint & line, uint & column, const char * text, int tokenIndex) [private]
linkIdentifier() [2/2]
void ClangTUParser::linkIdentifier (CodeOutputInterface & ol, const FileDef * fd, uint & line, uint & column, const char * text, int tokenIndex) [private]
linkInclude() [1/2]
void ClangTUParser::linkInclude (CodeOutputInterface & ol, const FileDef * fd, uint & line, uint & column, const char * text) [private]
linkInclude() [2/2]
void ClangTUParser::linkInclude (CodeOutputInterface & ol, const FileDef * fd, uint & line, uint & column, const char * text) [private]
linkMacro() [1/2]
void ClangTUParser::linkMacro (CodeOutputInterface & ol, const FileDef * fd, uint & line, uint & column, const char * text) [private]
linkMacro() [2/2]
void ClangTUParser::linkMacro (CodeOutputInterface & ol, const FileDef * fd, uint & line, uint & column, const char * text) [private]
lookup() [1/2]
std::string ClangTUParser::lookup (uint line, const char * symbol)
Looks for symbol which should be found at line. returns a clang unique reference to the symbol.
Definition at line 931 of file clangparser.cpp.
{
  return std::string();
}
References string.
lookup() [2/2]
std::string ClangTUParser::lookup (uint line, const char * symbol)
Looks for symbol which should be found at line. returns a clang unique reference to the symbol.
operator=() [1/2]
ClangTUParser & ClangTUParser::operator= (const ClangTUParser &) [private], [delete]
operator=() [2/2]
ClangTUParser & ClangTUParser::operator= (const ClangTUParser &) [private], [delete]
parse() [1/2]
void ClangTUParser::parse ()
Parse the file given at construction time as a translation unit This file should already be preprocessed by doxygen preprocessor at the time of calling.
Definition at line 919 of file clangparser.cpp.
{
}
Referenced by parseFile().
parse() [2/2]
void ClangTUParser::parse ()
Parse the file given at construction time as a translation unit This file should already be preprocessed by doxygen preprocessor at the time of calling.
switchToFile() [1/2]
void ClangTUParser::switchToFile (const FileDef * fd)
Switches to another file within the translation unit started with start().
Parameters
 in fd The file definition with the name of the file to switch to.
Definition at line 915 of file clangparser.cpp.
{
}
Referenced by parseFile(), FileDefImpl::parseSource(), and FileDefImpl::writeSourceBody().
switchToFile() [2/2]
void ClangTUParser::switchToFile (const FileDef * fd)
Switches to another file within the translation unit started with start().
Parameters
 in fd The file definition with the name of the file to switch to.
writeLineNumber() [1/2]
void ClangTUParser::writeLineNumber (CodeOutputInterface & ol, const FileDef * fd, uint line, bool writeLineAnchor) [private]
writeLineNumber() [2/2]
void ClangTUParser::writeLineNumber (CodeOutputInterface & ol, const FileDef * fd, uint line, bool writeLineAnchor) [private]
writeMultiLineCodeLink() [1/2]
void ClangTUParser::writeMultiLineCodeLink (CodeOutputInterface & ol, const FileDef * fd, uint & line, uint & column, const Definition * d, const char * text) [private]
writeMultiLineCodeLink() [2/2]
void ClangTUParser::writeMultiLineCodeLink (CodeOutputInterface & ol, const FileDef * fd, uint & line, uint & column, const Definition * d, const char * text) [private]
writeSources() [1/2]
void ClangTUParser::writeSources (CodeOutputInterface & ol, const FileDef * fd)
writes the syntax highlighted source code for a file
Parameters
 out ol The output generator list to write to.
 in fd The file to write sources for.
Referenced by FileDefImpl::parseSource(), and FileDefImpl::writeSourceBody().
writeSources() [2/2]
void ClangTUParser::writeSources (CodeOutputInterface & ol, const FileDef * fd)
writes the syntax highlighted source code for a file
Parameters
 out ol The output generator list to write to.
 in fd The file to write sources for.
Member Data Documentation
p
std::unique_ptr< Private > ClangTUParser::p [private]
Definition at line 71 of file clangparser.h.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/clangparser.h
doxygen/src/clangparser.h
doxygen/build/doxygen/src/clangparser.cpp
doxygen/src/clangparser.cpp