MemberListInfoContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const QCString &name) const
virtual StringVector fields () const
MemberListInfoContext (const Definition *def, const QCString &relPath, const MemberList *ml, const QCString &title, const QCString &subtitle=QCString())
virtual ~MemberListInfoContext ()
virtual TemplateVariant get (const QCString &name) const
virtual StringVector fields () const
MemberListInfoContext (const Definition *def, const QCString &relPath, const MemberList *ml, const QCString &title, const QCString &subtitle=QCString())
virtual ~MemberListInfoContext ()
Static Public Member Functions
static TemplateStructIntfPtr alloc (const Definition *def, const QCString &relPath, const MemberList *ml, const QCString &title, const QCString &subtitle=QCString())
static TemplateStructIntfPtr alloc (const Definition *def, const QCString &relPath, const MemberList *ml, const QCString &title, const QCString &subtitle=QCString())
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Definition at line 1076 of file context.h.
Constructor & Destructor Documentation
MemberListInfoContext() [1/2]
MemberListInfoContext::MemberListInfoContext (const Definition * def, const QCString & relPath, const MemberList * ml, const QCString & title, const QCString & subtitle = QCString())
Definition at line 7974 of file context.cpp.
                                                           : p(std::make_unique<Private>(def,relPath,ml,title,subtitle))
{
}
 MemberListInfoContext() [1/2]
MemberListInfoContext::~MemberListInfoContext () [virtual]
Definition at line 7980 of file context.cpp.
{
}
MemberListInfoContext() [2/2]
MemberListInfoContext::MemberListInfoContext (const Definition * def, const QCString & relPath, const MemberList * ml, const QCString & title, const QCString & subtitle = QCString())
 MemberListInfoContext() [2/2]
virtual MemberListInfoContext::~MemberListInfoContext () [virtual]
Member Function Documentation
alloc() [1/2]
static TemplateStructIntfPtr MemberListInfoContext::alloc (const Definition * def, const QCString & relPath, const MemberList * ml, const QCString & title, const QCString & subtitle = QCString()) [inline], [static]
Definition at line 1079 of file context.h.
    { return std::static_pointer_cast<TemplateStructIntf>(std::make_shared<MemberListInfoContext>(def,relPath,ml,title,subtitle)); }
Referenced by ClassContext::Private::createMemberList(), NamespaceContext::Private::createMemberList(), FileContext::Private::createMemberList(), and ModuleContext::Private::createMemberList().
alloc() [2/2]
static TemplateStructIntfPtr MemberListInfoContext::alloc (const Definition * def, const QCString & relPath, const MemberList * ml, const QCString & title, const QCString & subtitle = QCString()) [inline], [static]
Definition at line 1079 of file context.h.
    { return std::static_pointer_cast<TemplateStructIntf>(std::make_shared<MemberListInfoContext>(def,relPath,ml,title,subtitle)); }
fields() [1/2]
StringVector MemberListInfoContext::fields () const [virtual]
Return the list of fields.
Implements TemplateStructIntf.
Definition at line 7989 of file context.cpp.
{
  return p->fields();
}
References p.
fields() [2/2]
virtual StringVector MemberListInfoContext::fields () const [virtual]
Return the list of fields.
Implements TemplateStructIntf.
get() [1/2]
TemplateVariant MemberListInfoContext::get (const QCString & name) const [virtual]
Gets the value for a field name.
Parameters
 in name The name of the field.
Implements TemplateStructIntf.
Definition at line 7984 of file context.cpp.
{
  return p->get(name);
}
References setup::name, and p.
get() [2/2]
virtual TemplateVariant MemberListInfoContext::get (const QCString & name) const [virtual]
Gets the value for a field name.
Parameters
 in name The name of the field.
Implements TemplateStructIntf.
Member Data Documentation
p
std::unique_ptr< Private > MemberListInfoContext::p [private]
Definition at line 1095 of file context.h.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.h
doxygen/src/context.h
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp