EmojiEntityMapper Class Reference
Singleton helper class to map emoji entities to other formats.
#include <emoji.h>
Public Member Functions
const char * name (int index) const
Access routine to the name of the Emoji entity.
const char * unicode (int index) const
Access routine to the unicode sequence for the Emoji entity.
void writeEmojiFile (TextStream &t)
Writes the list of supported emojis to the given file.
int symbol2index (const std::string &symName) const
Returns a code for the requested Emoji entity name.
const char * name (int index) const
const char * unicode (int index) const
void writeEmojiFile (TextStream &t)
int symbol2index (const std::string &symName) const
Static Public Member Functions
static EmojiEntityMapper * instance ()
static void deleteInstance ()
static EmojiEntityMapper * instance ()
static void deleteInstance ()
Private Member Functions
EmojiEntityMapper ()
~EmojiEntityMapper ()
EmojiEntityMapper ()
~EmojiEntityMapper ()
Private Attributes
std::map< std::string, int > m_name2symGh
Static Private Attributes
static EmojiEntityMapper * s_instance = 0
Detailed Description
Singleton helper class to map emoji entities to other formats.
Definition at line 24 of file emoji.h.
Constructor & Destructor Documentation
EmojiEntityMapper() [1/2]
EmojiEntityMapper::EmojiEntityMapper () [private]
Definition at line 1902 of file emoji.cpp.
{
  for (size_t i = 0; i < g_numEmojiEntities; i++)
  {
    m_name2symGh.insert(std::make_pair(g_emojiEntities[i].name, static_cast<int>(i)));
  }
  for (size_t i = 0; i < g_numEmojiCompatibilityEntities; i++)
  {
    int ii = symbol2index(g_emojiCompatibilityEntities[i].newName);
    if (ii != -1) m_name2symGh.insert(std::make_pair(g_emojiCompatibilityEntities[i].oldName, ii));
  }
}
References g_emojiCompatibilityEntities, g_emojiEntities, g_numEmojiCompatibilityEntities, g_numEmojiEntities, m_name2symGh, name(), and symbol2index().
Referenced by instance().
 EmojiEntityMapper() [1/2]
EmojiEntityMapper::~EmojiEntityMapper () [private]
Definition at line 1915 of file emoji.cpp.
{
}
EmojiEntityMapper() [2/2]
EmojiEntityMapper::EmojiEntityMapper () [private]
 EmojiEntityMapper() [2/2]
EmojiEntityMapper::~EmojiEntityMapper () [private]
Member Function Documentation
deleteInstance() [1/2]
void EmojiEntityMapper::deleteInstance () [static]
Deletes the one and only instance of the Emoji entity mapper
Definition at line 1930 of file emoji.cpp.
{
  delete s_instance;
  s_instance=0;
}
References s_instance.
deleteInstance() [2/2]
static void EmojiEntityMapper::deleteInstance () [static]
instance() [1/2]
EmojiEntityMapper * EmojiEntityMapper::instance () [static]
Returns the one and only instance of the Emoji entity mapper
Definition at line 1920 of file emoji.cpp.
{
  if (s_instance==0)
  {
    s_instance = new EmojiEntityMapper;
  }
  return s_instance;
}
References EmojiEntityMapper(), and s_instance.
Referenced by DocEmoji::DocEmoji(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), PerlModDocVisitor::operator()(), RTFDocVisitor::operator()(), TextDocVisitor::operator()(), XmlDocVisitor::operator()(), PrintDocVisitor::operator()(), and readConfiguration().
instance() [2/2]
static EmojiEntityMapper * EmojiEntityMapper::instance () [static]
name() [1/2]
const char * EmojiEntityMapper::name (int index) const
Access routine to the name of the Emoji entity.
Parameters
index code of the requested Emoji entity returned by symbol2index()
Returns
the name of the Emoji entity in GitHub format (i.e. :smile:)
Definition at line 1978 of file emoji.cpp.
{
  return index>=0 && static_cast<size_t>(index)<g_numEmojiEntities ? g_emojiEntities[index].name : 0;
}
References g_emojiEntities, g_numEmojiEntities, and name().
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), EmojiEntityMapper(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), name(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), PerlModDocVisitor::operator()(), TextDocVisitor::operator()(), XmlDocVisitor::operator()(), PrintDocVisitor::operator()(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
name() [2/2]
const char * EmojiEntityMapper::name (int index) const
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
symbol2index() [1/2]
int EmojiEntityMapper::symbol2index (const std::string & symName) const
Returns a code for the requested Emoji entity name.
Parameters
symName Emoji entity name
Returns
the code for the requested Emoji entity name, in case the requested Emoji item does not exist -1 is returned.
Definition at line 1942 of file emoji.cpp.
{
  auto it = m_name2symGh.find(symName);
  return it!=m_name2symGh.end() ? it->second : -1;
}
References m_name2symGh.
Referenced by DocEmoji::DocEmoji(), and EmojiEntityMapper().
symbol2index() [2/2]
int EmojiEntityMapper::symbol2index (const std::string & symName) const
unicode() [1/2]
const char * EmojiEntityMapper::unicode (int index) const
Access routine to the unicode sequence for the Emoji entity.
Parameters
index code of the requested Emoji entity returned by symbol2index()
Returns
the unicode sequence of the Emoji entity,
Definition at line 1968 of file emoji.cpp.
{
  return index>=0 && static_cast<size_t>(index)<g_numEmojiEntities ? g_emojiEntities[index].unicode : 0;
}
References g_emojiEntities, g_numEmojiEntities, and unicode().
Referenced by doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docEmojiType::get_unicode(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), RTFDocVisitor::operator()(), doxmlparser.compound.docEmojiType::set_unicode(), and unicode().
unicode() [2/2]
const char * EmojiEntityMapper::unicode (int index) const
Referenced by doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docEmojiType::get_unicode(), and doxmlparser.compound.docEmojiType::set_unicode().
writeEmojiFile() [1/2]
void EmojiEntityMapper::writeEmojiFile (TextStream & t)
Writes the list of supported emojis to the given file.
Definition at line 1951 of file emoji.cpp.
{
  for (size_t i = 0; i < g_numEmojiEntities; i++)
  {
    t << g_emojiEntities[i].name << "\n";
  }
  for (size_t i = 0; i < g_numEmojiCompatibilityEntities; i++)
  {
    t << g_emojiCompatibilityEntities[i].oldName << "\n";
  }
}
References g_emojiCompatibilityEntities, g_emojiEntities, g_numEmojiCompatibilityEntities, g_numEmojiEntities, emojiEntityInfo::name, and emojiEntityCompatibility::oldName.
Referenced by readConfiguration().
writeEmojiFile() [2/2]
void EmojiEntityMapper::writeEmojiFile (TextStream & t)
Member Data Documentation
m_name2symGh
std::map< std::string, int > EmojiEntityMapper::m_name2symGh [private]
Definition at line 38 of file emoji.h.
Referenced by EmojiEntityMapper(), and symbol2index().
s_instance
static EmojiEntityMapper * EmojiEntityMapper::s_instance = 0 [static], [private]
Definition at line 37 of file emoji.h.
Referenced by deleteInstance(), and instance().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/emoji.h
doxygen/src/emoji.h
doxygen/build/doxygen/src/emoji.cpp
doxygen/src/emoji.cpp