TranslatorCroatian Class Reference
#include <translator_hr.h>
Public Member Functions
QCString idLanguage ()
QCString latexLanguageSupportCommand ()
QCString trISOLang ()
virtual QCString getLanguageString ()
QCString trRelatedFunctions ()
QCString trRelatedSubscript ()
QCString trDetailedDescription ()
QCString trMemberTypedefDocumentation ()
QCString trMemberEnumerationDocumentation ()
QCString trMemberFunctionDocumentation ()
QCString trMemberDataDocumentation ()
QCString trMore ()
QCString trListOfAllMembers ()
QCString trMemberList ()
QCString trThisIsTheListOfAllMembers ()
QCString trIncludingInheritedMembers ()
QCString trGeneratedAutomatically (const QCString &s)
QCString trEnumName ()
QCString trEnumValue ()
QCString trDefinedIn ()
QCString trModules ()
QCString trClassHierarchy ()
QCString trCompoundList ()
QCString trFileList ()
QCString trCompoundMembers ()
QCString trFileMembers ()
QCString trRelatedPages ()
QCString trExamples ()
QCString trSearch ()
QCString trClassHierarchyDescription ()
QCString trFileListDescription (bool extractAll)
QCString trCompoundListDescription ()
QCString trCompoundMembersDescription (bool extractAll)
QCString trFileMembersDescription (bool extractAll)
QCString trExamplesDescription ()
QCString trRelatedPagesDescription ()
QCString trModulesDescription ()
QCString trDocumentation ()
QCString trModuleIndex ()
QCString trHierarchicalIndex ()
QCString trCompoundIndex ()
QCString trFileIndex ()
QCString trModuleDocumentation ()
QCString trClassDocumentation ()
QCString trFileDocumentation ()
QCString trExampleDocumentation ()
QCString trReferenceManual ()
QCString trDefines ()
QCString trTypedefs ()
QCString trEnumerations ()
QCString trFunctions ()
QCString trVariables ()
QCString trEnumerationValues ()
QCString trDefineDocumentation ()
QCString trTypedefDocumentation ()
QCString trEnumerationTypeDocumentation ()
QCString trFunctionDocumentation ()
QCString trVariableDocumentation ()
QCString trCompounds ()
QCString trGeneratedAt (const QCString &date, const QCString &projName)
QCString trClassDiagram (const QCString &clName)
QCString trWarning ()
QCString trVersion ()
QCString trDate ()
QCString trReturns ()
QCString trSeeAlso ()
QCString trParameters ()
QCString trExceptions ()
QCString trGeneratedBy ()
QCString trNamespaceList ()
QCString trNamespaceListDescription (bool extractAll)
QCString trFriends ()
QCString trRelatedFunctionDocumentation ()
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool)
QCString trFileReference (const QCString &fileName)
QCString trNamespaceReference (const QCString &namespaceName)
QCString trPublicMembers ()
QCString trPublicSlots ()
QCString trSignals ()
QCString trStaticPublicMembers ()
QCString trProtectedMembers ()
QCString trProtectedSlots ()
QCString trStaticProtectedMembers ()
QCString trPrivateMembers ()
QCString trPrivateSlots ()
QCString trStaticPrivateMembers ()
QCString trWriteList (int numEntries)
QCString trInheritsList (int numEntries)
QCString trInheritedByList (int numEntries)
QCString trReimplementedFromList (int numEntries)
QCString trReimplementedInList (int numEntries)
QCString trNamespaceMembers ()
QCString trNamespaceMemberDescription (bool extractAll)
QCString trNamespaceIndex ()
QCString trNamespaceDocumentation ()
QCString trNamespaces ()
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
QCString trReturnValues ()
QCString trMainPage ()
QCString trPageAbbreviation ()
QCString trDefinedAtLineInSourceFile ()
QCString trDefinedInSourceFile ()
QCString trDeprecated ()
QCString trCollaborationDiagram (const QCString &clName)
QCString trInclDepGraph (const QCString &fName)
QCString trConstructorDocumentation ()
QCString trGotoSourceCode ()
QCString trGotoDocumentation ()
QCString trPrecondition ()
QCString trPostcondition ()
QCString trInvariant ()
QCString trInitialValue ()
QCString trCode ()
QCString trGraphicalHierarchy ()
QCString trGotoGraphicalHierarchy ()
QCString trGotoTextualHierarchy ()
QCString trPageIndex ()
QCString trNote ()
QCString trPublicTypes ()
QCString trPublicAttribs ()
QCString trStaticPublicAttribs ()
QCString trProtectedTypes ()
QCString trProtectedAttribs ()
QCString trStaticProtectedAttribs ()
QCString trPrivateTypes ()
QCString trPrivateAttribs ()
QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
QCString idLanguage ()
QCString latexLanguageSupportCommand ()
QCString trISOLang ()
virtual QCString getLanguageString ()
QCString trRelatedFunctions ()
QCString trRelatedSubscript ()
QCString trDetailedDescription ()
QCString trMemberTypedefDocumentation ()
QCString trMemberEnumerationDocumentation ()
QCString trMemberFunctionDocumentation ()
QCString trMemberDataDocumentation ()
QCString trMore ()
QCString trListOfAllMembers ()
QCString trMemberList ()
QCString trThisIsTheListOfAllMembers ()
QCString trIncludingInheritedMembers ()
QCString trGeneratedAutomatically (const QCString &s)
QCString trEnumName ()
QCString trEnumValue ()
QCString trDefinedIn ()
QCString trModules ()
QCString trClassHierarchy ()
QCString trCompoundList ()
QCString trFileList ()
QCString trCompoundMembers ()
QCString trFileMembers ()
QCString trRelatedPages ()
QCString trExamples ()
QCString trSearch ()
QCString trClassHierarchyDescription ()
QCString trFileListDescription (bool extractAll)
QCString trCompoundListDescription ()
QCString trCompoundMembersDescription (bool extractAll)
QCString trFileMembersDescription (bool extractAll)
QCString trExamplesDescription ()
QCString trRelatedPagesDescription ()
QCString trModulesDescription ()
QCString trDocumentation ()
QCString trModuleIndex ()
QCString trHierarchicalIndex ()
QCString trCompoundIndex ()
QCString trFileIndex ()
QCString trModuleDocumentation ()
QCString trClassDocumentation ()
QCString trFileDocumentation ()
QCString trExampleDocumentation ()
QCString trReferenceManual ()
QCString trDefines ()
QCString trTypedefs ()
QCString trEnumerations ()
QCString trFunctions ()
QCString trVariables ()
QCString trEnumerationValues ()
QCString trDefineDocumentation ()
QCString trTypedefDocumentation ()
QCString trEnumerationTypeDocumentation ()
QCString trFunctionDocumentation ()
QCString trVariableDocumentation ()
QCString trCompounds ()
QCString trGeneratedAt (const QCString &date, const QCString &projName)
QCString trClassDiagram (const QCString &clName)
QCString trWarning ()
QCString trVersion ()
QCString trDate ()
QCString trReturns ()
QCString trSeeAlso ()
QCString trParameters ()
QCString trExceptions ()
QCString trGeneratedBy ()
QCString trNamespaceList ()
QCString trNamespaceListDescription (bool extractAll)
QCString trFriends ()
QCString trRelatedFunctionDocumentation ()
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool)
QCString trFileReference (const QCString &fileName)
QCString trNamespaceReference (const QCString &namespaceName)
QCString trPublicMembers ()
QCString trPublicSlots ()
QCString trSignals ()
QCString trStaticPublicMembers ()
QCString trProtectedMembers ()
QCString trProtectedSlots ()
QCString trStaticProtectedMembers ()
QCString trPrivateMembers ()
QCString trPrivateSlots ()
QCString trStaticPrivateMembers ()
QCString trWriteList (int numEntries)
QCString trInheritsList (int numEntries)
QCString trInheritedByList (int numEntries)
QCString trReimplementedFromList (int numEntries)
QCString trReimplementedInList (int numEntries)
QCString trNamespaceMembers ()
QCString trNamespaceMemberDescription (bool extractAll)
QCString trNamespaceIndex ()
QCString trNamespaceDocumentation ()
QCString trNamespaces ()
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
QCString trReturnValues ()
QCString trMainPage ()
QCString trPageAbbreviation ()
QCString trDefinedAtLineInSourceFile ()
QCString trDefinedInSourceFile ()
QCString trDeprecated ()
QCString trCollaborationDiagram (const QCString &clName)
QCString trInclDepGraph (const QCString &fName)
QCString trConstructorDocumentation ()
QCString trGotoSourceCode ()
QCString trGotoDocumentation ()
QCString trPrecondition ()
QCString trPostcondition ()
QCString trInvariant ()
QCString trInitialValue ()
QCString trCode ()
QCString trGraphicalHierarchy ()
QCString trGotoGraphicalHierarchy ()
QCString trGotoTextualHierarchy ()
QCString trPageIndex ()
QCString trNote ()
QCString trPublicTypes ()
QCString trPublicAttribs ()
QCString trStaticPublicAttribs ()
QCString trProtectedTypes ()
QCString trProtectedAttribs ()
QCString trStaticProtectedAttribs ()
QCString trPrivateTypes ()
QCString trPrivateAttribs ()
QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
Additional Inherited Members
Detailed Description
Definition at line 86 of file translator_hr.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorCroatian::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 97 of file translator_hr.h.
    {
      return "0x41A Croatian";
    }
getLanguageString() [2/2]
virtual QCString TranslatorCroatian::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 97 of file translator_hr.h.
    {
      return "0x41A Croatian";
    }
idLanguage() [1/2]
QCString TranslatorCroatian::idLanguage () [inline], [virtual]
Implements Translator.
Definition at line 91 of file translator_hr.h.
    { return "croatian"; }
idLanguage() [2/2]
QCString TranslatorCroatian::idLanguage () [inline], [virtual]
Implements Translator.
Definition at line 91 of file translator_hr.h.
    { return "croatian"; }
latexLanguageSupportCommand() [1/2]
QCString TranslatorCroatian::latexLanguageSupportCommand () [inline], [virtual]
Implements Translator.
Definition at line 93 of file translator_hr.h.
    { return "\\usepackage[croatian]{babel}\n"; }
latexLanguageSupportCommand() [2/2]
QCString TranslatorCroatian::latexLanguageSupportCommand () [inline], [virtual]
Implements Translator.
Definition at line 93 of file translator_hr.h.
    { return "\\usepackage[croatian]{babel}\n"; }
trAdditionalInheritedMembers() [1/2]
virtual QCString TranslatorCroatian::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1587 of file translator_hr.h.
    { return "Dodatni naslijeeni lanovi"; }
trAdditionalInheritedMembers() [2/2]
virtual QCString TranslatorCroatian::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1587 of file translator_hr.h.
    { return "Dodatni naslijeeni lanovi"; }
trAll() [1/2]
virtual QCString TranslatorCroatian::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1098 of file translator_hr.h.
    {
        return "Sve";
    }
trAll() [2/2]
virtual QCString TranslatorCroatian::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1098 of file translator_hr.h.
    {
        return "Sve";
    }
trAndMore() [1/2]
virtual QCString TranslatorCroatian::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1565 of file translator_hr.h.
    { return "i jo "+number+" ..."; }
trAndMore() [2/2]
virtual QCString TranslatorCroatian::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1565 of file translator_hr.h.
    { return "i jo "+number+" ..."; }
trAttention() [1/2]
virtual QCString TranslatorCroatian::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 703 of file translator_hr.h.
    {
        return "Panja";
    }
trAttention() [2/2]
virtual QCString TranslatorCroatian::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 703 of file translator_hr.h.
    {
        return "Panja";
    }
trAuthor() [1/2]
virtual QCString TranslatorCroatian::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 975 of file translator_hr.h.
    {
      QCString result((first_capital ? "Autor" : "autor"));
      if (!singular) result+="i";
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorCroatian::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 975 of file translator_hr.h.
    {
      QCString result((first_capital ? "Autor" : "autor"));
      if (!singular) result+="i";
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorCroatian::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 856 of file translator_hr.h.
    {
      return "Greka";
    }
trBug() [2/2]
virtual QCString TranslatorCroatian::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 856 of file translator_hr.h.
    {
      return "Greka";
    }
trBugList() [1/2]
virtual QCString TranslatorCroatian::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 861 of file translator_hr.h.
    {
      return "Popis greaka";
    }
trBugList() [2/2]
virtual QCString TranslatorCroatian::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 861 of file translator_hr.h.
    {
      return "Popis greaka";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorCroatian::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1225 of file translator_hr.h.
    {
      return "Ovo je graf funkcija koje pozivaju ovu funkciju:";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorCroatian::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1225 of file translator_hr.h.
    {
      return "Ovo je graf funkcija koje pozivaju ovu funkciju:";
    }
trCallGraph() [1/2]
virtual QCString TranslatorCroatian::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1103 of file translator_hr.h.
    {
        return "Ovo je dijagram poziva za ovu funkciju:";
    }
trCallGraph() [2/2]
virtual QCString TranslatorCroatian::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1103 of file translator_hr.h.
    {
        return "Ovo je dijagram poziva za ovu funkciju:";
    }
trCiteReferences() [1/2]
virtual QCString TranslatorCroatian::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1541 of file translator_hr.h.
    { return "Bibliografija"; }
trCiteReferences() [2/2]
virtual QCString TranslatorCroatian::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1541 of file translator_hr.h.
    { return "Bibliografija"; }
trClass() [1/2]
virtual QCString TranslatorCroatian::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 889 of file translator_hr.h.
    {
      QCString result((first_capital ? "Klas" : "klas"));
      result+= (singular ? "a" : "e");
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorCroatian::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 889 of file translator_hr.h.
    {
      QCString result((first_capital ? "Klas" : "klas"));
      result+= (singular ? "a" : "e");
      return result;
    }
trClassDiagram() [1/2]
QCString TranslatorCroatian::trClassDiagram (const QCString & clName) [inline], [virtual]
Implements Translator.
Definition at line 301 of file translator_hr.h.
    {
      return QCString("Dijagram klasa za ")+clName;
    }
trClassDiagram() [2/2]
QCString TranslatorCroatian::trClassDiagram (const QCString & clName) [inline], [virtual]
Implements Translator.
Definition at line 301 of file translator_hr.h.
    {
      return QCString("Dijagram klasa za ")+clName;
    }
trClassDocumentation() [1/2]
QCString TranslatorCroatian::trClassDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 248 of file translator_hr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentacija struktura podataka";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return trDesignUnitDocumentation();
      }
      else
      {
        return "Dokumentacija klasa";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClassDocumentation() [2/2]
QCString TranslatorCroatian::trClassDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 248 of file translator_hr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentacija struktura podataka";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return trDesignUnitDocumentation();
      }
      else
      {
        return "Dokumentacija klasa";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorCroatian::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 826 of file translator_hr.h.
    {
      return "Klase";
    }
trClasses() [2/2]
virtual QCString TranslatorCroatian::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 826 of file translator_hr.h.
    {
      return "Klase";
    }
trClassHierarchy() [1/2]
QCString TranslatorCroatian::trClassHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 139 of file translator_hr.h.
    { return "Stablo klasa"; }
trClassHierarchy() [2/2]
QCString TranslatorCroatian::trClassHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 139 of file translator_hr.h.
    { return "Stablo klasa"; }
trClassHierarchyDescription() [1/2]
QCString TranslatorCroatian::trClassHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 169 of file translator_hr.h.
    { return "Stablo naslijeivanja je sloeno "
             "priblino po abecedi:";
    }
trClassHierarchyDescription() [2/2]
QCString TranslatorCroatian::trClassHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 169 of file translator_hr.h.
    { return "Stablo naslijeivanja je sloeno "
             "priblino po abecedi:";
    }
trCode() [1/2]
QCString TranslatorCroatian::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 611 of file translator_hr.h.
    {
      return "kod";
    }
trCode() [2/2]
QCString TranslatorCroatian::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 611 of file translator_hr.h.
    {
      return "kod";
    }
trCollaborationDiagram() [1/2]
QCString TranslatorCroatian::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 566 of file translator_hr.h.
    {
      return "Kolaboracijski dijagram za "+clName+ ":";
    }
trCollaborationDiagram() [2/2]
QCString TranslatorCroatian::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 566 of file translator_hr.h.
    {
      return "Kolaboracijski dijagram za "+clName+ ":";
    }
trCompoundIndex() [1/2]
QCString TranslatorCroatian::trCompoundIndex () [inline], [virtual]
Implements Translator.
Definition at line 233 of file translator_hr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Kazalo struktura podataka";
      }
      else
      {
    return "Skupno kazalo ";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
QCString TranslatorCroatian::trCompoundIndex () [inline], [virtual]
Implements Translator.
Definition at line 233 of file translator_hr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Kazalo struktura podataka";
      }
      else
      {
    return "Skupno kazalo ";
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorCroatian::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1279 of file translator_hr.h.
    { return "Kazalo data tipova"; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorCroatian::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1279 of file translator_hr.h.
    { return "Kazalo data tipova"; }
trCompoundList() [1/2]
QCString TranslatorCroatian::trCompoundList () [inline], [virtual]
Implements Translator.
Definition at line 141 of file translator_hr.h.
    {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
            return "Sve strukture";
        }
        else
        {
            return "Sve klase";
        }
    }
References Config_getBool.
trCompoundList() [2/2]
QCString TranslatorCroatian::trCompoundList () [inline], [virtual]
Implements Translator.
Definition at line 141 of file translator_hr.h.
    {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
            return "Sve strukture";
        }
        else
        {
            return "Sve klase";
        }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
QCString TranslatorCroatian::trCompoundListDescription () [inline], [virtual]
Implements Translator.
Definition at line 180 of file translator_hr.h.
    { return "Popis svih klasa, unija i struktura "
          "s kratkim opisom :";
    }
trCompoundListDescription() [2/2]
QCString TranslatorCroatian::trCompoundListDescription () [inline], [virtual]
Implements Translator.
Definition at line 180 of file translator_hr.h.
    { return "Popis svih klasa, unija i struktura "
          "s kratkim opisom :";
    }
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorCroatian::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1252 of file translator_hr.h.
    { return "Tipovi podataka s kratkim opisom:"; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorCroatian::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1252 of file translator_hr.h.
    { return "Tipovi podataka s kratkim opisom:"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorCroatian::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1244 of file translator_hr.h.
    { return "Lista tipova podataka"; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorCroatian::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1244 of file translator_hr.h.
    { return "Lista tipova podataka"; }
trCompoundMembers() [1/2]
QCString TranslatorCroatian::trCompoundMembers () [inline], [virtual]
Implements Translator.
Definition at line 154 of file translator_hr.h.
    {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
            return "Svi lanovi struktura";
        else
            return "Svi lanovi klasa";
    }
References Config_getBool.
trCompoundMembers() [2/2]
QCString TranslatorCroatian::trCompoundMembers () [inline], [virtual]
Implements Translator.
Definition at line 154 of file translator_hr.h.
    {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
            return "Svi lanovi struktura";
        else
            return "Svi lanovi klasa";
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
QCString TranslatorCroatian::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 184 of file translator_hr.h.
    {
      QCString result="Popis svih ";
      if (!extractAll)
          result+="dokumentiranih ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
          result+="lanova klasa s linkovima na ";
      else
          result+="lanova struktura s linkovima na ";
      if (!extractAll)
      {
          result+="dokumentaciju svakog lana:";
      }
      else
      {
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
              result+="dokumentaciju klase :";
          else
              result +="dokumentaciju strukture";
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
QCString TranslatorCroatian::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 184 of file translator_hr.h.
    {
      QCString result="Popis svih ";
      if (!extractAll)
          result+="dokumentiranih ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
          result+="lanova klasa s linkovima na ";
      else
          result+="lanova struktura s linkovima na ";
      if (!extractAll)
      {
          result+="dokumentaciju svakog lana:";
      }
      else
      {
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
              result+="dokumentaciju klase :";
          else
              result +="dokumentaciju strukture";
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorCroatian::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1256 of file translator_hr.h.
    {
      QCString result="Lista svih ";
      if (!extractAll)
      {
        result+="dokumentiranih ";
      }
      result+="polja";
      result+=" s linkovima na ";
      if (!extractAll)
      {
        result+="dokumentaciju struktura podataka za svako polje";
      }
      else
      {
        result+="strukture kojima pripadaju:";
      }
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorCroatian::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1256 of file translator_hr.h.
    {
      QCString result="Lista svih ";
      if (!extractAll)
      {
        result+="dokumentiranih ";
      }
      result+="polja";
      result+=" s linkovima na ";
      if (!extractAll)
      {
        result+="dokumentaciju struktura podataka za svako polje";
      }
      else
      {
        result+="strukture kojima pripadaju:";
      }
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorCroatian::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1248 of file translator_hr.h.
    { return "Polja"; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorCroatian::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1248 of file translator_hr.h.
    { return "Polja"; }
trCompoundReference() [1/2]
QCString TranslatorCroatian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool) [inline], [virtual]
Implements Translator.
Definition at line 349 of file translator_hr.h.
    {
      QCString result="Opis ";
      switch(compType)
      {
        case ClassDef::Class: result+=" klase "; break;
        case ClassDef::Struct: result+=" strukture "; break;
        case ClassDef::Union: result+=" unije "; break;
        case ClassDef::Interface: result+=" suelja (interface) "; break;
        case ClassDef::Protocol: result+=" protokola "; break;
        case ClassDef::Category: result+=" kategorije "; break;
        case ClassDef::Exception: result+=" iznimke (exception) "; break;
        default: break;
      }
      result += clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
QCString TranslatorCroatian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool) [inline], [virtual]
Implements Translator.
Definition at line 349 of file translator_hr.h.
    {
      QCString result="Opis ";
      switch(compType)
      {
        case ClassDef::Class: result+=" klase "; break;
        case ClassDef::Struct: result+=" strukture "; break;
        case ClassDef::Union: result+=" unije "; break;
        case ClassDef::Interface: result+=" suelja (interface) "; break;
        case ClassDef::Protocol: result+=" protokola "; break;
        case ClassDef::Category: result+=" kategorije "; break;
        case ClassDef::Exception: result+=" iznimke (exception) "; break;
        default: break;
      }
      result += clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorCroatian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1320 of file translator_hr.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" Modul"; break;
        case ClassDef::Struct: result+=" Tip"; break;
        case ClassDef::Union: result+=" Unija"; break;
        case ClassDef::Interface: result+=" Suelje"; break;
        case ClassDef::Protocol: result+=" Protokol"; break;
        case ClassDef::Category: result+=" Kategorija"; break;
        case ClassDef::Exception: result+=" Iznimka"; break;
        default: break;
      }
      if (isTemplate) result+=" Predloak";
      result+=" Referenca";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorCroatian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1320 of file translator_hr.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" Modul"; break;
        case ClassDef::Struct: result+=" Tip"; break;
        case ClassDef::Union: result+=" Unija"; break;
        case ClassDef::Interface: result+=" Suelje"; break;
        case ClassDef::Protocol: result+=" Protokol"; break;
        case ClassDef::Category: result+=" Kategorija"; break;
        case ClassDef::Exception: result+=" Iznimka"; break;
        default: break;
      }
      if (isTemplate) result+=" Predloak";
      result+=" Referenca";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
QCString TranslatorCroatian::trCompounds () [inline], [virtual]
Implements Translator.
Definition at line 292 of file translator_hr.h.
    { return "Strukture"; }
trCompounds() [2/2]
QCString TranslatorCroatian::trCompounds () [inline], [virtual]
Implements Translator.
Definition at line 292 of file translator_hr.h.
    { return "Strukture"; }
trConstructorDocumentation() [1/2]
QCString TranslatorCroatian::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 576 of file translator_hr.h.
    {
      return "Dokumentacija konstruktora i destruktora ";
    }
trConstructorDocumentation() [2/2]
QCString TranslatorCroatian::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 576 of file translator_hr.h.
    {
      return "Dokumentacija konstruktora i destruktora ";
    }
trCopyright() [1/2]
virtual QCString TranslatorCroatian::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1545 of file translator_hr.h.
    { return "Copyright"; }
trCopyright() [2/2]
virtual QCString TranslatorCroatian::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1545 of file translator_hr.h.
    { return "Copyright"; }
trDataTypes() [1/2]
virtual QCString TranslatorCroatian::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1303 of file translator_hr.h.
    { return "Tipovi podataka"; }
trDataTypes() [2/2]
virtual QCString TranslatorCroatian::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1303 of file translator_hr.h.
    { return "Tipovi podataka"; }
trDate() [1/2]
QCString TranslatorCroatian::trDate () [inline], [virtual]
Implements Translator.
Definition at line 309 of file translator_hr.h.
    { return "Datum"; }
trDate() [2/2]
QCString TranslatorCroatian::trDate () [inline], [virtual]
Implements Translator.
Definition at line 309 of file translator_hr.h.
    { return "Datum"; }
trDateTime() [1/2]
virtual QCString TranslatorCroatian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1499 of file translator_hr.h.
    {
      static const char *days[] = { "Pon","Uto","Sri","et","Pet","Sub","Ned" };
      static const char *months[] = { "Sje","Velj","Ou","Tra","Svi","Lip","Srp","Kol","Ruj","Lis","Stu","Pro" };
      QCString sdate;
      sdate.sprintf("%s %s %d %d",days[dayOfWeek-1],months[month-1],day,year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDateTime() [2/2]
virtual QCString TranslatorCroatian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1499 of file translator_hr.h.
    {
      static const char *days[] = { "Pon","Uto","Sri","et","Pet","Sub","Ned" };
      static const char *months[] = { "Sje","Velj","Ou","Tra","Svi","Lip","Srp","Kol","Ruj","Lis","Stu","Pro" };
      QCString sdate;
      sdate.sprintf("%s %s %d %d",days[dayOfWeek-1],months[month-1],day,year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDayOfWeek() [1/2]
virtual QCString TranslatorCroatian::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1515 of file translator_hr.h.
    {
      static const char *days_short[] = { "pon", "uto", "sri", "et", "pet", "sub", "ned" };
      static const char *days_full[] = { "ponedjeljak", "utorak", "srijeda", "etvrtak", "petak", "subota", "nedjelja" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      return text;
    }
trDayOfWeek() [2/2]
virtual QCString TranslatorCroatian::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1515 of file translator_hr.h.
    {
      static const char *days_short[] = { "pon", "uto", "sri", "et", "pet", "sub", "ned" };
      static const char *days_full[] = { "ponedjeljak", "utorak", "srijeda", "etvrtak", "petak", "subota", "nedjelja" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      return text;
    }
trDayPeriod() [1/2]
virtual QCString TranslatorCroatian::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1529 of file translator_hr.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorCroatian::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1529 of file translator_hr.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
QCString TranslatorCroatian::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 543 of file translator_hr.h.
    {
      return "Definirano u liniji @0 datoteke @1.";
    }
trDefinedAtLineInSourceFile() [2/2]
QCString TranslatorCroatian::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 543 of file translator_hr.h.
    {
      return "Definirano u liniji @0 datoteke @1.";
    }
trDefinedIn() [1/2]
QCString TranslatorCroatian::trDefinedIn () [inline], [virtual]
Implements Translator.
Definition at line 135 of file translator_hr.h.
    { return "definirano u"; }
trDefinedIn() [2/2]
QCString TranslatorCroatian::trDefinedIn () [inline], [virtual]
Implements Translator.
Definition at line 135 of file translator_hr.h.
    { return "definirano u"; }
trDefinedInSourceFile() [1/2]
QCString TranslatorCroatian::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 547 of file translator_hr.h.
    {
      return "Definirano u datoteci @0.";
    }
trDefinedInSourceFile() [2/2]
QCString TranslatorCroatian::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 547 of file translator_hr.h.
    {
      return "Definirano u datoteci @0.";
    }
trDefineDocumentation() [1/2]
QCString TranslatorCroatian::trDefineDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 282 of file translator_hr.h.
    { return "Dokumentacija definicija"; }
trDefineDocumentation() [2/2]
QCString TranslatorCroatian::trDefineDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 282 of file translator_hr.h.
    { return "Dokumentacija definicija"; }
trDefines() [1/2]
QCString TranslatorCroatian::trDefines () [inline], [virtual]
Implements Translator.
Definition at line 270 of file translator_hr.h.
    { return "Definicije"; }
trDefines() [2/2]
QCString TranslatorCroatian::trDefines () [inline], [virtual]
Implements Translator.
Definition at line 270 of file translator_hr.h.
    { return "Definicije"; }
trDefineValue() [1/2]
virtual QCString TranslatorCroatian::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 846 of file translator_hr.h.
    {
      return "Vrijednost:";
    }
trDefineValue() [2/2]
virtual QCString TranslatorCroatian::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 846 of file translator_hr.h.
    {
      return "Vrijednost:";
    }
trDeprecated() [1/2]
QCString TranslatorCroatian::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 556 of file translator_hr.h.
    {
      return "Zastarjelo";
    }
trDeprecated() [2/2]
QCString TranslatorCroatian::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 556 of file translator_hr.h.
    {
      return "Zastarjelo";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorCroatian::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1029 of file translator_hr.h.
    {
      return "Popis zastarjelih metoda";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorCroatian::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1029 of file translator_hr.h.
    {
      return "Popis zastarjelih metoda";
    }
trDetailedDescription() [1/2]
QCString TranslatorCroatian::trDetailedDescription () [inline], [virtual]
Implements Translator.
Definition at line 105 of file translator_hr.h.
    { return "Detaljno objanjenje"; }
trDetailedDescription() [2/2]
QCString TranslatorCroatian::trDetailedDescription () [inline], [virtual]
Implements Translator.
Definition at line 105 of file translator_hr.h.
    { return "Detaljno objanjenje"; }
trDetailLevel() [1/2]
virtual QCString TranslatorCroatian::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1557 of file translator_hr.h.
    { return "razina detalja"; }
trDetailLevel() [2/2]
virtual QCString TranslatorCroatian::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1557 of file translator_hr.h.
    { return "razina detalja"; }
trDir() [1/2]
virtual QCString TranslatorCroatian::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1200 of file translator_hr.h.
    {
      QCString result((first_capital ? "Direktorij" : "direktorij"));
      if (!singular) result+="i";
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorCroatian::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1200 of file translator_hr.h.
    {
      QCString result((first_capital ? "Direktorij" : "direktorij"));
      if (!singular) result+="i";
      return result;
    }
trDirDepGraph() [1/2]
virtual QCString TranslatorCroatian::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1549 of file translator_hr.h.
    { return QCString("Direktoriji o kojima ovisi ")+name+":"; }
References setup::name.
trDirDepGraph() [2/2]
virtual QCString TranslatorCroatian::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1549 of file translator_hr.h.
    { return QCString("Direktoriji o kojima ovisi ")+name+":"; }
References setup::name.
trDirDocumentation() [1/2]
virtual QCString TranslatorCroatian::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1182 of file translator_hr.h.
    { return "Dokumentacija direktorija"; }
trDirDocumentation() [2/2]
virtual QCString TranslatorCroatian::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1182 of file translator_hr.h.
    { return "Dokumentacija direktorija"; }
trDirectories() [1/2]
virtual QCString TranslatorCroatian::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1188 of file translator_hr.h.
    { return "Direktoriji"; }
trDirectories() [2/2]
virtual QCString TranslatorCroatian::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1188 of file translator_hr.h.
    { return "Direktoriji"; }
trDirIndex() [1/2]
virtual QCString TranslatorCroatian::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1176 of file translator_hr.h.
    { return "Stablo direktorija"; }
trDirIndex() [2/2]
virtual QCString TranslatorCroatian::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1176 of file translator_hr.h.
    { return "Stablo direktorija"; }
trDirReference() [1/2]
virtual QCString TranslatorCroatian::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1194 of file translator_hr.h.
    { QCString result= "Opis direktorija "; result += dirName; return result; }
trDirReference() [2/2]
virtual QCString TranslatorCroatian::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1194 of file translator_hr.h.
    { QCString result= "Opis direktorija "; result += dirName; return result; }
trDirRelation() [1/2]
virtual QCString TranslatorCroatian::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1438 of file translator_hr.h.
    {
        return QCString("Relacije ") + QCString(name);
    }
References setup::name.
trDirRelation() [2/2]
virtual QCString TranslatorCroatian::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1438 of file translator_hr.h.
    {
        return QCString("Relacije ") + QCString(name);
    }
References setup::name.
trDocumentation() [1/2]
QCString TranslatorCroatian::trDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 227 of file translator_hr.h.
    { return "Dokumentacija"; }
trDocumentation() [2/2]
QCString TranslatorCroatian::trDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 227 of file translator_hr.h.
    { return "Dokumentacija"; }
trEnumerations() [1/2]
QCString TranslatorCroatian::trEnumerations () [inline], [virtual]
Implements Translator.
Definition at line 274 of file translator_hr.h.
    { return "Enumeracije"; }
trEnumerations() [2/2]
QCString TranslatorCroatian::trEnumerations () [inline], [virtual]
Implements Translator.
Definition at line 274 of file translator_hr.h.
    { return "Enumeracije"; }
trEnumerationTypeDocumentation() [1/2]
QCString TranslatorCroatian::trEnumerationTypeDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 286 of file translator_hr.h.
    { return "Dokumentacija enumeracijskog tipa"; }
trEnumerationTypeDocumentation() [2/2]
QCString TranslatorCroatian::trEnumerationTypeDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 286 of file translator_hr.h.
    { return "Dokumentacija enumeracijskog tipa"; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorCroatian::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1233 of file translator_hr.h.
    { return "Dokumentacija enumeracija"; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorCroatian::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1233 of file translator_hr.h.
    { return "Dokumentacija enumeracija"; }
trEnumerationValues() [1/2]
QCString TranslatorCroatian::trEnumerationValues () [inline], [virtual]
Implements Translator.
Definition at line 280 of file translator_hr.h.
    { return "Vrijednosti enumeracija"; }
trEnumerationValues() [2/2]
QCString TranslatorCroatian::trEnumerationValues () [inline], [virtual]
Implements Translator.
Definition at line 280 of file translator_hr.h.
    { return "Vrijednosti enumeracija"; }
trEnumGeneratedFromFiles() [1/2]
virtual QCString TranslatorCroatian::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1569 of file translator_hr.h.
    { QCString result = "Dokumatacija za ovu enumeraciju je generirana iz ";
      if (!single) result += "datoteka:";
      else result += "datoteke:";
      return result;
    }
trEnumGeneratedFromFiles() [2/2]
virtual QCString TranslatorCroatian::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1569 of file translator_hr.h.
    { QCString result = "Dokumatacija za ovu enumeraciju je generirana iz ";
      if (!single) result += "datoteka:";
      else result += "datoteke:";
      return result;
    }
trEnumName() [1/2]
QCString TranslatorCroatian::trEnumName () [inline], [virtual]
Implements Translator.
Definition at line 131 of file translator_hr.h.
    { return "enum ime"; }
trEnumName() [2/2]
QCString TranslatorCroatian::trEnumName () [inline], [virtual]
Implements Translator.
Definition at line 131 of file translator_hr.h.
    { return "enum ime"; }
trEnumReference() [1/2]
virtual QCString TranslatorCroatian::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1577 of file translator_hr.h.
    { return "Opis enumeracije " + QCString(name); }
References setup::name.
trEnumReference() [2/2]
virtual QCString TranslatorCroatian::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1577 of file translator_hr.h.
    { return "Opis enumeracije " + QCString(name); }
References setup::name.
trEnumValue() [1/2]
QCString TranslatorCroatian::trEnumValue () [inline], [virtual]
Implements Translator.
Definition at line 133 of file translator_hr.h.
    { return "enum vrijednost"; }
trEnumValue() [2/2]
QCString TranslatorCroatian::trEnumValue () [inline], [virtual]
Implements Translator.
Definition at line 133 of file translator_hr.h.
    { return "enum vrijednost"; }
trEventDocumentation() [1/2]
virtual QCString TranslatorCroatian::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1045 of file translator_hr.h.
    {
      return "Dokumentacija dogaaja";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorCroatian::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1045 of file translator_hr.h.
    {
      return "Dokumentacija dogaaja";
    }
trEvents() [1/2]
virtual QCString TranslatorCroatian::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1040 of file translator_hr.h.
    {
      return "Dogaaji";
    }
trEvents() [2/2]
virtual QCString TranslatorCroatian::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1040 of file translator_hr.h.
    {
      return "Dogaaji";
    }
trExampleDocumentation() [1/2]
QCString TranslatorCroatian::trExampleDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 265 of file translator_hr.h.
    { return "Dokumentacija primjera"; }
trExampleDocumentation() [2/2]
QCString TranslatorCroatian::trExampleDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 265 of file translator_hr.h.
    { return "Dokumentacija primjera"; }
trExamples() [1/2]
QCString TranslatorCroatian::trExamples () [inline], [virtual]
Implements Translator.
Definition at line 165 of file translator_hr.h.
    { return "Primjeri"; }
trExamples() [2/2]
QCString TranslatorCroatian::trExamples () [inline], [virtual]
Implements Translator.
Definition at line 165 of file translator_hr.h.
    { return "Primjeri"; }
trExamplesDescription() [1/2]
QCString TranslatorCroatian::trExamplesDescription () [inline], [virtual]
Implements Translator.
Definition at line 220 of file translator_hr.h.
    { return "Popis primjera :"; }
trExamplesDescription() [2/2]
QCString TranslatorCroatian::trExamplesDescription () [inline], [virtual]
Implements Translator.
Definition at line 220 of file translator_hr.h.
    { return "Popis primjera :"; }
trExceptions() [1/2]
QCString TranslatorCroatian::trExceptions () [inline], [virtual]
Implements Translator.
Definition at line 317 of file translator_hr.h.
    { return "Iznimke"; }
trExceptions() [2/2]
QCString TranslatorCroatian::trExceptions () [inline], [virtual]
Implements Translator.
Definition at line 317 of file translator_hr.h.
    { return "Iznimke"; }
trFile() [1/2]
virtual QCString TranslatorCroatian::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 900 of file translator_hr.h.
    {
      QCString result((first_capital ? "Datotek" : "datotek"));
      result+= (singular ? "a" : "e");
      return result;
    }
Referenced by trGeneratedFromFiles().
trFile() [2/2]
virtual QCString TranslatorCroatian::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 900 of file translator_hr.h.
    {
      QCString result((first_capital ? "Datotek" : "datotek"));
      result+= (singular ? "a" : "e");
      return result;
    }
trFileDocumentation() [1/2]
QCString TranslatorCroatian::trFileDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 263 of file translator_hr.h.
    { return "Dokumentacija datoteka"; }
trFileDocumentation() [2/2]
QCString TranslatorCroatian::trFileDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 263 of file translator_hr.h.
    { return "Dokumentacija datoteka"; }
trFileIn() [1/2]
virtual QCString TranslatorCroatian::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1475 of file translator_hr.h.
    {
      return "Datoteka u "+name;
    }
References setup::name.
trFileIn() [2/2]
virtual QCString TranslatorCroatian::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1475 of file translator_hr.h.
    {
      return "Datoteka u "+name;
    }
References setup::name.
trFileIndex() [1/2]
QCString TranslatorCroatian::trFileIndex () [inline], [virtual]
Implements Translator.
Definition at line 244 of file translator_hr.h.
    { return "Kazalo datoteka"; }
trFileIndex() [2/2]
QCString TranslatorCroatian::trFileIndex () [inline], [virtual]
Implements Translator.
Definition at line 244 of file translator_hr.h.
    { return "Kazalo datoteka"; }
trFileList() [1/2]
QCString TranslatorCroatian::trFileList () [inline], [virtual]
Implements Translator.
Definition at line 152 of file translator_hr.h.
    { return "Popis datoteka"; }
trFileList() [2/2]
QCString TranslatorCroatian::trFileList () [inline], [virtual]
Implements Translator.
Definition at line 152 of file translator_hr.h.
    { return "Popis datoteka"; }
trFileListDescription() [1/2]
QCString TranslatorCroatian::trFileListDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 173 of file translator_hr.h.
    {
      QCString result="Popis svih ";
      if (!extractAll) result+="dokumentiranih ";
      result+="datoteka, s kratkim opisom:";
      return result;
    }
trFileListDescription() [2/2]
QCString TranslatorCroatian::trFileListDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 173 of file translator_hr.h.
    {
      QCString result="Popis svih ";
      if (!extractAll) result+="dokumentiranih ";
      result+="datoteka, s kratkim opisom:";
      return result;
    }
trFileMembers() [1/2]
QCString TranslatorCroatian::trFileMembers () [inline], [virtual]
Implements Translator.
Definition at line 161 of file translator_hr.h.
    { return "lanovi klasa u datoteci"; }
trFileMembers() [2/2]
QCString TranslatorCroatian::trFileMembers () [inline], [virtual]
Implements Translator.
Definition at line 161 of file translator_hr.h.
    { return "lanovi klasa u datoteci"; }
trFileMembersDescription() [1/2]
QCString TranslatorCroatian::trFileMembersDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 208 of file translator_hr.h.
    {
      QCString result="Popis svih ";
      if (!extractAll)
          result+="dokumentiranih ";
      result+="lanova s linkovima na ";
      if (extractAll)
          result+="dokumentaciju datoteke u kojima se nalaze:";
      else
          result+="datoteke u kojima se nalaze:";
      return result;
    }
trFileMembersDescription() [2/2]
QCString TranslatorCroatian::trFileMembersDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 208 of file translator_hr.h.
    {
      QCString result="Popis svih ";
      if (!extractAll)
          result+="dokumentiranih ";
      result+="lanova s linkovima na ";
      if (extractAll)
          result+="dokumentaciju datoteke u kojima se nalaze:";
      else
          result+="datoteke u kojima se nalaze:";
      return result;
    }
trFileReference() [1/2]
QCString TranslatorCroatian::trFileReference (const QCString & fileName) [inline], [virtual]
Implements Translator.
Definition at line 369 of file translator_hr.h.
    {
      QCString result="Opis datoteke ";
          result+=fileName;
          return result;
    }
trFileReference() [2/2]
QCString TranslatorCroatian::trFileReference (const QCString & fileName) [inline], [virtual]
Implements Translator.
Definition at line 369 of file translator_hr.h.
    {
      QCString result="Opis datoteke ";
          result+=fileName;
          return result;
    }
trFriends() [1/2]
QCString TranslatorCroatian::trFriends () [inline], [virtual]
Implements Translator.
Definition at line 335 of file translator_hr.h.
    { return "Friend-ovi "; }
trFriends() [2/2]
QCString TranslatorCroatian::trFriends () [inline], [virtual]
Implements Translator.
Definition at line 335 of file translator_hr.h.
    { return "Friend-ovi "; }
trFunctionDocumentation() [1/2]
QCString TranslatorCroatian::trFunctionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 288 of file translator_hr.h.
    { return "Dokumentacije funkcija"; }
trFunctionDocumentation() [2/2]
QCString TranslatorCroatian::trFunctionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 288 of file translator_hr.h.
    { return "Dokumentacije funkcija"; }
trFunctions() [1/2]
QCString TranslatorCroatian::trFunctions () [inline], [virtual]
Implements Translator.
Definition at line 276 of file translator_hr.h.
    { return "Funkcije"; }
trFunctions() [2/2]
QCString TranslatorCroatian::trFunctions () [inline], [virtual]
Implements Translator.
Definition at line 276 of file translator_hr.h.
    { return "Funkcije"; }
trGeneratedAt() [1/2]
QCString TranslatorCroatian::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
Implements Translator.
Definition at line 294 of file translator_hr.h.
    {
      QCString result="Napravljeno "+date;
      if (!projName.isEmpty()) result+=" projekt: "+projName;
      result+=" generator: ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
QCString TranslatorCroatian::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
Implements Translator.
Definition at line 294 of file translator_hr.h.
    {
      QCString result="Napravljeno "+date;
      if (!projName.isEmpty()) result+=" projekt: "+projName;
      result+=" generator: ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
QCString TranslatorCroatian::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
Implements Translator.
Definition at line 125 of file translator_hr.h.
    { QCString result="napravljeno automatski Doxygen-om";
      if (!s.isEmpty()) result+=" za "+s;
      result+=" iz programskog koda.";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
QCString TranslatorCroatian::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
Implements Translator.
Definition at line 125 of file translator_hr.h.
    { QCString result="napravljeno automatski Doxygen-om";
      if (!s.isEmpty()) result+=" za "+s;
      result+=" iz programskog koda.";
      return result;
    }
References s.
trGeneratedBy() [1/2]
QCString TranslatorCroatian::trGeneratedBy () [inline], [virtual]
Implements Translator.
Definition at line 319 of file translator_hr.h.
    { return "Generirao"; }
trGeneratedBy() [2/2]
QCString TranslatorCroatian::trGeneratedBy () [inline], [virtual]
Implements Translator.
Definition at line 319 of file translator_hr.h.
    { return "Generirao"; }
trGeneratedFromFiles() [1/2]
QCString TranslatorCroatian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 500 of file translator_hr.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentacija ";
      switch(compType)
      {
        case ClassDef::Class: result+="klase"; break;
        case ClassDef::Struct: result+="strukture"; break;
        case ClassDef::Union: result+="unije"; break;
        case ClassDef::Interface: result+="suelja (interface)"; break;
        case ClassDef::Protocol: result+="protokola"; break;
        case ClassDef::Category: result+="kategorije"; break;
        case ClassDef::Exception: result+="iznimke (exception)"; break;
        default: break;
      }
      result+=" je napravljena iz " + trFile(FALSE, single) + ": ";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, FALSE, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, trFile(), and ClassDef::Union.
trGeneratedFromFiles() [2/2]
QCString TranslatorCroatian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 500 of file translator_hr.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentacija ";
      switch(compType)
      {
        case ClassDef::Class: result+="klase"; break;
        case ClassDef::Struct: result+="strukture"; break;
        case ClassDef::Union: result+="unije"; break;
        case ClassDef::Interface: result+="suelja (interface)"; break;
        case ClassDef::Protocol: result+="protokola"; break;
        case ClassDef::Category: result+="kategorije"; break;
        case ClassDef::Exception: result+="iznimke (exception)"; break;
        default: break;
      }
      result+=" je napravljena iz " + trFile(FALSE, single) + ": ";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, FALSE, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, trFile(), and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorCroatian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1388 of file translator_hr.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentacija ovog ";
      switch(compType)
      {
        case ClassDef::Class: result+="modula"; break;
        case ClassDef::Struct: result+="tipa"; break;
        case ClassDef::Union: result+="unije"; break;
        case ClassDef::Interface: result+="suelja"; break;
        case ClassDef::Protocol: result+="protokola"; break;
        case ClassDef::Category: result+="kategorije"; break;
        case ClassDef::Exception: result+="iznimke"; break;
        default: break;
      }
      result+=" je napravljena iz :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorCroatian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1388 of file translator_hr.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentacija ovog ";
      switch(compType)
      {
        case ClassDef::Class: result+="modula"; break;
        case ClassDef::Struct: result+="tipa"; break;
        case ClassDef::Union: result+="unije"; break;
        case ClassDef::Interface: result+="suelja"; break;
        case ClassDef::Protocol: result+="protokola"; break;
        case ClassDef::Category: result+="kategorije"; break;
        case ClassDef::Exception: result+="iznimke"; break;
        default: break;
      }
      result+=" je napravljena iz :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorCroatian::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 958 of file translator_hr.h.
    {
      QCString result((first_capital ? "G" : "g"));
      if(singular)
          result += "lobalna varijabla";
      else
          result += "lobalne varijable";
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorCroatian::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 958 of file translator_hr.h.
    {
      QCString result((first_capital ? "G" : "g"));
      if(singular)
          result += "lobalna varijabla";
      else
          result += "lobalne varijable";
      return result;
    }
trGlobalNamespace() [1/2]
virtual QCString TranslatorCroatian::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1450 of file translator_hr.h.
    {
        return "Globalni namespace";
    }
trGlobalNamespace() [2/2]
virtual QCString TranslatorCroatian::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1450 of file translator_hr.h.
    {
        return "Globalni namespace";
    }
trGotoDocumentation() [1/2]
QCString TranslatorCroatian::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 586 of file translator_hr.h.
    {
      return "Dokumenacija za ovu datoteku.";
    }
trGotoDocumentation() [2/2]
QCString TranslatorCroatian::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 586 of file translator_hr.h.
    {
      return "Dokumenacija za ovu datoteku.";
    }
trGotoGraphicalHierarchy() [1/2]
QCString TranslatorCroatian::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 619 of file translator_hr.h.
    {
      return "Grafiko stablo klasa";
    }
trGotoGraphicalHierarchy() [2/2]
QCString TranslatorCroatian::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 619 of file translator_hr.h.
    {
      return "Grafiko stablo klasa";
    }
trGotoSourceCode() [1/2]
QCString TranslatorCroatian::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 581 of file translator_hr.h.
    {
      return "Izvorni kod";
    }
trGotoSourceCode() [2/2]
QCString TranslatorCroatian::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 581 of file translator_hr.h.
    {
      return "Izvorni kod";
    }
trGotoTextualHierarchy() [1/2]
QCString TranslatorCroatian::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 623 of file translator_hr.h.
    {
      return "Tekstualno stablo klasa";
    }
trGotoTextualHierarchy() [2/2]
QCString TranslatorCroatian::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 623 of file translator_hr.h.
    {
      return "Tekstualno stablo klasa";
    }
trGraphicalHierarchy() [1/2]
QCString TranslatorCroatian::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 615 of file translator_hr.h.
    {
      return "Grafiko stablo klasa";
    }
trGraphicalHierarchy() [2/2]
QCString TranslatorCroatian::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 615 of file translator_hr.h.
    {
      return "Grafiko stablo klasa";
    }
trGroup() [1/2]
virtual QCString TranslatorCroatian::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 925 of file translator_hr.h.
    {
      QCString result((first_capital ? "Grup" : "grup"));
      result+= (singular ? "a" : "e");
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorCroatian::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 925 of file translator_hr.h.
    {
      QCString result((first_capital ? "Grup" : "grup"));
      result+= (singular ? "a" : "e");
      return result;
    }
trHierarchicalIndex() [1/2]
QCString TranslatorCroatian::trHierarchicalIndex () [inline], [virtual]
Implements Translator.
Definition at line 231 of file translator_hr.h.
    { return "Hijerarhijsko kazalo"; }
trHierarchicalIndex() [2/2]
QCString TranslatorCroatian::trHierarchicalIndex () [inline], [virtual]
Implements Translator.
Definition at line 231 of file translator_hr.h.
    { return "Hijerarhijsko kazalo"; }
trImplementedFromList() [1/2]
virtual QCString TranslatorCroatian::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 999 of file translator_hr.h.
    {
      return "Implementira "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorCroatian::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 999 of file translator_hr.h.
    {
      return "Implementira "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorCroatian::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implementation this member.
Implements Translator.
Definition at line 1007 of file translator_hr.h.
    {
      return "Implementirano u "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorCroatian::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implementation this member.
Implements Translator.
Definition at line 1007 of file translator_hr.h.
    {
      return "Implementirano u "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorCroatian::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 707 of file translator_hr.h.
    {
      return "Ovaj graf pokazuje koje datoteke izravno "
             "ili neizravno ukljuuju ovu datoteku:";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorCroatian::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 707 of file translator_hr.h.
    {
      return "Ovaj graf pokazuje koje datoteke izravno "
             "ili neizravno ukljuuju ovu datoteku:";
    }
trInclDepGraph() [1/2]
QCString TranslatorCroatian::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 571 of file translator_hr.h.
    {
      return "Graf include meuovisnosti za "+fName+":";
    }
trInclDepGraph() [2/2]
QCString TranslatorCroatian::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 571 of file translator_hr.h.
    {
      return "Graf include meuovisnosti za "+fName+":";
    }
trIncludesFileIn() [1/2]
virtual QCString TranslatorCroatian::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1484 of file translator_hr.h.
    {
      return "Ukljuuje datotake u "+name;
    }
References setup::name.
trIncludesFileIn() [2/2]
virtual QCString TranslatorCroatian::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1484 of file translator_hr.h.
    {
      return "Ukljuuje datotake u "+name;
    }
References setup::name.
trIncludingInheritedMembers() [1/2]
QCString TranslatorCroatian::trIncludingInheritedMembers () [inline], [virtual]
Implements Translator.
Definition at line 123 of file translator_hr.h.
    { return ", ukljuujui naslijeene lanove."; }
trIncludingInheritedMembers() [2/2]
QCString TranslatorCroatian::trIncludingInheritedMembers () [inline], [virtual]
Implements Translator.
Definition at line 123 of file translator_hr.h.
    { return ", ukljuujui naslijeene lanove."; }
trInheritedByList() [1/2]
QCString TranslatorCroatian::trInheritedByList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 438 of file translator_hr.h.
    {
      return "Naslijeena u "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedByList() [2/2]
QCString TranslatorCroatian::trInheritedByList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 438 of file translator_hr.h.
    {
      return "Naslijeena u "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom() [1/2]
virtual QCString TranslatorCroatian::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1581 of file translator_hr.h.
    { return QCString(members)+" naslijeeni od "+what; }
trInheritedFrom() [2/2]
virtual QCString TranslatorCroatian::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1581 of file translator_hr.h.
    { return QCString(members)+" naslijeeni od "+what; }
trInheritsList() [1/2]
QCString TranslatorCroatian::trInheritsList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 432 of file translator_hr.h.
    {
      return "Naslijeuje od "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [2/2]
QCString TranslatorCroatian::trInheritsList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 432 of file translator_hr.h.
    {
      return "Naslijeuje od "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue() [1/2]
QCString TranslatorCroatian::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 606 of file translator_hr.h.
    {
      return "Poetna vrijednost:";
    }
trInitialValue() [2/2]
QCString TranslatorCroatian::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 606 of file translator_hr.h.
    {
      return "Poetna vrijednost:";
    }
trInvariant() [1/2]
QCString TranslatorCroatian::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 601 of file translator_hr.h.
    {
      return "Invarijanta";
    }
trInvariant() [2/2]
QCString TranslatorCroatian::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 601 of file translator_hr.h.
    {
      return "Invarijanta";
    }
trISOLang() [1/2]
QCString TranslatorCroatian::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 95 of file translator_hr.h.
    { return "hr"; }
trISOLang() [2/2]
QCString TranslatorCroatian::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 95 of file translator_hr.h.
    { return "hr"; }
trLegend() [1/2]
virtual QCString TranslatorCroatian::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 787 of file translator_hr.h.
    {
      return "legenda";
    }
trLegend() [2/2]
virtual QCString TranslatorCroatian::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 787 of file translator_hr.h.
    {
      return "legenda";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorCroatian::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 727 of file translator_hr.h.
    {
      return
        "Ova stranica objanjava kako interpretirati grafikone koje je generirao "
        "doxygen.<p>\n"
        "Na primjer:\n"
        "\\code\n"
        "/*! Nevidljiva klasa (nee stati na graf date visine) */\n"
        "class Invisible { };\n\n"
        "/*! Odrezana klasa, inheritance je skriven (klase se vidi na grafu, ali ne i sve bazne klase) */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Nedokumentirana klasa */\n"
        "class Undocumented { };\n\n"
        "/*! Klasa koja je naslijeena public */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Klasa koje je naslijeena protected */\n"
        "class ProtectedBase { };\n\n"
        "/*! Klasa koje je naslijeena private */\n"
        "class PrivateBase { };\n\n"
        "/*! Klasa koja se koristi agregacijom */\n"
        "class Used { };\n\n"
        "/*! Super klasa koja naslijeuje/koristi ostale */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "To e rezultirati grafikonom:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "Pravokutnici imaju slijedee znaenje:\n"
        "<ul>\n"
        "<li>Puni crni predstavlja klasu za koji je napravljen graf.\n"
        "<li>Pravokutnik s crnim rubom predstavlja dokumentiranu klasu.\n"
        "<li>Pravokutnik s sivim rubom predstavlja nedokumentiranu klasu.\n"
        "<li>Pravokutnik s crvenim rubom predstavlja dokumentiranu klasu\n"
        "Za koju nije prikazan graf naslijeivanja. Graf je odrezan "
        "ako ne stane unutar odreenih granica."
        "</ul>\n"
        "Strelice imaju slijedee znaenje:\n"
        "<ul>\n"
        "<li>Tamnoplava strelica oznaava public naslijeivanje.\n"
        "<li>Tamnozelena strelica oznaava protected naslijeivanje.\n"
        "<li>Tamnocrvena strelica oznaava private naslijeivanje.\n"
        "<li>Ljubiasta isprekidana strelica se koristi ako je klasa dio "
        "druge klase ili ako se klasa koristi u drugoj klasi. Natpis na "
        "strelici je ime varijable u drugoj klasi\n"
        "Strelica je oznaena imenom varijable.\n"
        "<li>uta isprekidana strelica oznaava relaciju izmeu template instance "
        "i template klase. Oznaena je imenom template parametra\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorCroatian::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 727 of file translator_hr.h.
    {
      return
        "Ova stranica objanjava kako interpretirati grafikone koje je generirao "
        "doxygen.<p>\n"
        "Na primjer:\n"
        "\\code\n"
        "/*! Nevidljiva klasa (nee stati na graf date visine) */\n"
        "class Invisible { };\n\n"
        "/*! Odrezana klasa, inheritance je skriven (klase se vidi na grafu, ali ne i sve bazne klase) */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Nedokumentirana klasa */\n"
        "class Undocumented { };\n\n"
        "/*! Klasa koja je naslijeena public */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Klasa koje je naslijeena protected */\n"
        "class ProtectedBase { };\n\n"
        "/*! Klasa koje je naslijeena private */\n"
        "class PrivateBase { };\n\n"
        "/*! Klasa koja se koristi agregacijom */\n"
        "class Used { };\n\n"
        "/*! Super klasa koja naslijeuje/koristi ostale */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "To e rezultirati grafikonom:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "Pravokutnici imaju slijedee znaenje:\n"
        "<ul>\n"
        "<li>Puni crni predstavlja klasu za koji je napravljen graf.\n"
        "<li>Pravokutnik s crnim rubom predstavlja dokumentiranu klasu.\n"
        "<li>Pravokutnik s sivim rubom predstavlja nedokumentiranu klasu.\n"
        "<li>Pravokutnik s crvenim rubom predstavlja dokumentiranu klasu\n"
        "Za koju nije prikazan graf naslijeivanja. Graf je odrezan "
        "ako ne stane unutar odreenih granica."
        "</ul>\n"
        "Strelice imaju slijedee znaenje:\n"
        "<ul>\n"
        "<li>Tamnoplava strelica oznaava public naslijeivanje.\n"
        "<li>Tamnozelena strelica oznaava protected naslijeivanje.\n"
        "<li>Tamnocrvena strelica oznaava private naslijeivanje.\n"
        "<li>Ljubiasta isprekidana strelica se koristi ako je klasa dio "
        "druge klase ili ako se klasa koristi u drugoj klasi. Natpis na "
        "strelici je ime varijable u drugoj klasi\n"
        "Strelica je oznaena imenom varijable.\n"
        "<li>uta isprekidana strelica oznaava relaciju izmeu template instance "
        "i template klase. Oznaena je imenom template parametra\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorCroatian::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 722 of file translator_hr.h.
    {
      return "Legenda";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorCroatian::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 722 of file translator_hr.h.
    {
      return "Legenda";
    }
trListOfAllMembers() [1/2]
QCString TranslatorCroatian::trListOfAllMembers () [inline], [virtual]
Implements Translator.
Definition at line 117 of file translator_hr.h.
    { return "Popis svih lanova"; }
trListOfAllMembers() [2/2]
QCString TranslatorCroatian::trListOfAllMembers () [inline], [virtual]
Implements Translator.
Definition at line 117 of file translator_hr.h.
    { return "Popis svih lanova"; }
trLoading() [1/2]
virtual QCString TranslatorCroatian::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1444 of file translator_hr.h.
    {
        return "Uitavam...";
    }
trLoading() [2/2]
virtual QCString TranslatorCroatian::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1444 of file translator_hr.h.
    {
        return "Uitavam...";
    }
trMainPage() [1/2]
QCString TranslatorCroatian::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 530 of file translator_hr.h.
    { return "Glavna stranica"; }
trMainPage() [2/2]
QCString TranslatorCroatian::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 530 of file translator_hr.h.
    { return "Glavna stranica"; }
trMember() [1/2]
virtual QCString TranslatorCroatian::trMember (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 947 of file translator_hr.h.
    {
      QCString result("lan");
      if (!singular) result+="ovi";
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorCroatian::trMember (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 947 of file translator_hr.h.
    {
      QCString result("lan");
      if (!singular) result+="ovi";
      return result;
    }
trMemberDataDocumentation() [1/2]
QCString TranslatorCroatian::trMemberDataDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 113 of file translator_hr.h.
    { return "Documentacija varijabli"; }
trMemberDataDocumentation() [2/2]
QCString TranslatorCroatian::trMemberDataDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 113 of file translator_hr.h.
    { return "Documentacija varijabli"; }
trMemberEnumerationDocumentation() [1/2]
QCString TranslatorCroatian::trMemberEnumerationDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 109 of file translator_hr.h.
    { return "Dokumentacija enumeracijskih lanova"; }
trMemberEnumerationDocumentation() [2/2]
QCString TranslatorCroatian::trMemberEnumerationDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 109 of file translator_hr.h.
    { return "Dokumentacija enumeracijskih lanova"; }
trMemberFunctionDocumentation() [1/2]
QCString TranslatorCroatian::trMemberFunctionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 111 of file translator_hr.h.
    { return "Dokumentacija funkcija"; }
trMemberFunctionDocumentation() [2/2]
QCString TranslatorCroatian::trMemberFunctionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 111 of file translator_hr.h.
    { return "Dokumentacija funkcija"; }
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorCroatian::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1240 of file translator_hr.h.
    { return "Dokumentacija member funkcija/subrutina"; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorCroatian::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1240 of file translator_hr.h.
    { return "Dokumentacija member funkcija/subrutina"; }
trMemberList() [1/2]
QCString TranslatorCroatian::trMemberList () [inline], [virtual]
Implements Translator.
Definition at line 119 of file translator_hr.h.
    { return "Popis lanova."; }
trMemberList() [2/2]
QCString TranslatorCroatian::trMemberList () [inline], [virtual]
Implements Translator.
Definition at line 119 of file translator_hr.h.
    { return "Popis lanova."; }
trMemberTypedefDocumentation() [1/2]
QCString TranslatorCroatian::trMemberTypedefDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 107 of file translator_hr.h.
    { return "Dokumentacija typedef lanova"; }
trMemberTypedefDocumentation() [2/2]
QCString TranslatorCroatian::trMemberTypedefDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 107 of file translator_hr.h.
    { return "Dokumentacija typedef lanova"; }
trModule() [1/2]
virtual QCString TranslatorCroatian::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1379 of file translator_hr.h.
    {
      QCString result((first_capital ? "Modul" : "modul"));
      if (!singular) result+="i";
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorCroatian::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1379 of file translator_hr.h.
    {
      QCString result((first_capital ? "Modul" : "modul"));
      if (!singular) result+="i";
      return result;
    }
trModuleDocumentation() [1/2]
QCString TranslatorCroatian::trModuleDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 246 of file translator_hr.h.
    { return "Dokumentacija modula"; }
trModuleDocumentation() [2/2]
QCString TranslatorCroatian::trModuleDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 246 of file translator_hr.h.
    { return "Dokumentacija modula"; }
trModuleIndex() [1/2]
QCString TranslatorCroatian::trModuleIndex () [inline], [virtual]
Implements Translator.
Definition at line 229 of file translator_hr.h.
    { return "Kazalo modula"; }
trModuleIndex() [2/2]
QCString TranslatorCroatian::trModuleIndex () [inline], [virtual]
Implements Translator.
Definition at line 229 of file translator_hr.h.
    { return "Kazalo modula"; }
trModuleReference() [1/2]
virtual QCString TranslatorCroatian::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1341 of file translator_hr.h.
    {
      QCString result=namespaceName;
      result+=" - Sadraj modula";
      return result;
    }
trModuleReference() [2/2]
virtual QCString TranslatorCroatian::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1341 of file translator_hr.h.
    {
      QCString result=namespaceName;
      result+=" - Sadraj modula";
      return result;
    }
trModules() [1/2]
QCString TranslatorCroatian::trModules () [inline], [virtual]
Implements Translator.
Definition at line 137 of file translator_hr.h.
    { return "Moduli"; }
trModules() [2/2]
QCString TranslatorCroatian::trModules () [inline], [virtual]
Implements Translator.
Definition at line 137 of file translator_hr.h.
    { return "Moduli"; }
trModulesDescription() [1/2]
QCString TranslatorCroatian::trModulesDescription () [inline], [virtual]
Implements Translator.
Definition at line 224 of file translator_hr.h.
    { return "Popis svih modula:"; }
trModulesDescription() [2/2]
QCString TranslatorCroatian::trModulesDescription () [inline], [virtual]
Implements Translator.
Definition at line 224 of file translator_hr.h.
    { return "Popis svih modula:"; }
trModulesIndex() [1/2]
virtual QCString TranslatorCroatian::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1372 of file translator_hr.h.
    { return "Kazalo modula"; }
trModulesIndex() [2/2]
virtual QCString TranslatorCroatian::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1372 of file translator_hr.h.
    { return "Kazalo modula"; }
trModulesList() [1/2]
virtual QCString TranslatorCroatian::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1307 of file translator_hr.h.
    { return "Popis modula"; }
trModulesList() [2/2]
virtual QCString TranslatorCroatian::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1307 of file translator_hr.h.
    { return "Popis modula"; }
trModulesListDescription() [1/2]
virtual QCString TranslatorCroatian::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1311 of file translator_hr.h.
    {
      QCString result="Lista svih ";
      if (!extractAll) result+="dokumentiranih ";
      result+="modula s kratkim opisom:";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorCroatian::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1311 of file translator_hr.h.
    {
      QCString result="Lista svih ";
      if (!extractAll) result+="dokumentiranih ";
      result+="modula s kratkim opisom:";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorCroatian::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1353 of file translator_hr.h.
    {
      QCString result="Lista svih ";
      if (!extractAll) result+="dokumentiranih ";
      result+="lanova modula s linkovima na ";
      if (extractAll)
      {
        result+="dokumentaciju modula za svaki lan:";
      }
      else
      {
        result+="modul kojem pripadaju:";
      }
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorCroatian::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1353 of file translator_hr.h.
    {
      QCString result="Lista svih ";
      if (!extractAll) result+="dokumentiranih ";
      result+="lanova modula s linkovima na ";
      if (extractAll)
      {
        result+="dokumentaciju modula za svaki lan:";
      }
      else
      {
        result+="modul kojem pripadaju:";
      }
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorCroatian::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1349 of file translator_hr.h.
    { return "lanovi modula"; }
trModulesMembers() [2/2]
virtual QCString TranslatorCroatian::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1349 of file translator_hr.h.
    { return "lanovi modula"; }
trMonth() [1/2]
virtual QCString TranslatorCroatian::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1522 of file translator_hr.h.
    {
      static const char *months_short[] = { "sij", "vlj", "ou", "tra", "svi", "lip", "srp", "kol", "ruj", "lis", "stu", "pro" };
      static const char *months_full[] = { "sijeanj", "veljaa", "oujak", "travanj", "svibanj", "lipanj", "srpanj", "kolovoz", "rujan", "listopad", "studeni", "prosinac" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      return text;
    }
trMonth() [2/2]
virtual QCString TranslatorCroatian::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1522 of file translator_hr.h.
    {
      static const char *months_short[] = { "sij", "vlj", "ou", "tra", "svi", "lip", "srp", "kol", "ruj", "lis", "stu", "pro" };
      static const char *months_full[] = { "sijeanj", "veljaa", "oujak", "travanj", "svibanj", "lipanj", "srpanj", "kolovoz", "rujan", "listopad", "studeni", "prosinac" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      return text;
    }
trMore() [1/2]
QCString TranslatorCroatian::trMore () [inline], [virtual]
Implements Translator.
Definition at line 115 of file translator_hr.h.
    { return "Opirnije..."; }
trMore() [2/2]
QCString TranslatorCroatian::trMore () [inline], [virtual]
Implements Translator.
Definition at line 115 of file translator_hr.h.
    { return "Opirnije..."; }
trNamespace() [1/2]
virtual QCString TranslatorCroatian::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 911 of file translator_hr.h.
    {
        QCString result;
        if (singular)
            result = ((first_capital ? "Imenik" : "imenik"));
        else
            result = ((first_capital ? "Imenici" : "imenici"));
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorCroatian::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 911 of file translator_hr.h.
    {
        QCString result;
        if (singular)
            result = ((first_capital ? "Imenik" : "imenik"));
        else
            result = ((first_capital ? "Imenici" : "imenici"));
      return result;
    }
trNamespaceDocumentation() [1/2]
QCString TranslatorCroatian::trNamespaceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 476 of file translator_hr.h.
    { return "Dokumentacija namespace-a"; }
trNamespaceDocumentation() [2/2]
QCString TranslatorCroatian::trNamespaceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 476 of file translator_hr.h.
    { return "Dokumentacija namespace-a"; }
trNamespaceIndex() [1/2]
QCString TranslatorCroatian::trNamespaceIndex () [inline], [virtual]
Implements Translator.
Definition at line 472 of file translator_hr.h.
    { return "Kazalo imenika"; }
trNamespaceIndex() [2/2]
QCString TranslatorCroatian::trNamespaceIndex () [inline], [virtual]
Implements Translator.
Definition at line 472 of file translator_hr.h.
    { return "Kazalo imenika"; }
trNamespaceList() [1/2]
QCString TranslatorCroatian::trNamespaceList () [inline], [virtual]
Implements Translator.
Definition at line 326 of file translator_hr.h.
    { return "Popis imenika"; }
trNamespaceList() [2/2]
QCString TranslatorCroatian::trNamespaceList () [inline], [virtual]
Implements Translator.
Definition at line 326 of file translator_hr.h.
    { return "Popis imenika"; }
trNamespaceListDescription() [1/2]
QCString TranslatorCroatian::trNamespaceListDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 328 of file translator_hr.h.
    {
      QCString result="Popis svih ";
      if (!extractAll) result+="dokumentiranih ";
      result+="imenika s kratkim opisom:";
      return result;
    }
trNamespaceListDescription() [2/2]
QCString TranslatorCroatian::trNamespaceListDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 328 of file translator_hr.h.
    {
      QCString result="Popis svih ";
      if (!extractAll) result+="dokumentiranih ";
      result+="imenika s kratkim opisom:";
      return result;
    }
trNamespaceMemberDescription() [1/2]
QCString TranslatorCroatian::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 460 of file translator_hr.h.
    {
      QCString result="Lista svih ";
      if (!extractAll) result+="dokumentiranih ";
      result+="lanova imenika s linkovima na ";
      if (extractAll)
        result+="imeniku dokumentaciju svakog lana:";
      else
        result+="imenike kojima pripadaju:";
      return result;
    }
trNamespaceMemberDescription() [2/2]
QCString TranslatorCroatian::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 460 of file translator_hr.h.
    {
      QCString result="Lista svih ";
      if (!extractAll) result+="dokumentiranih ";
      result+="lanova imenika s linkovima na ";
      if (extractAll)
        result+="imeniku dokumentaciju svakog lana:";
      else
        result+="imenike kojima pripadaju:";
      return result;
    }
trNamespaceMembers() [1/2]
QCString TranslatorCroatian::trNamespaceMembers () [inline], [virtual]
Implements Translator.
Definition at line 457 of file translator_hr.h.
    { return "lanovi imenika"; }
trNamespaceMembers() [2/2]
QCString TranslatorCroatian::trNamespaceMembers () [inline], [virtual]
Implements Translator.
Definition at line 457 of file translator_hr.h.
    { return "lanovi imenika"; }
trNamespaceReference() [1/2]
QCString TranslatorCroatian::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
Implements Translator.
Definition at line 376 of file translator_hr.h.
    {
      QCString result ="Opis imenika ";
          result+=namespaceName;
      return result;
    }
trNamespaceReference() [2/2]
QCString TranslatorCroatian::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
Implements Translator.
Definition at line 376 of file translator_hr.h.
    {
      QCString result ="Opis imenika ";
          result+=namespaceName;
      return result;
    }
trNamespaces() [1/2]
QCString TranslatorCroatian::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 488 of file translator_hr.h.
    {
      return "Imenici";
    }
trNamespaces() [2/2]
QCString TranslatorCroatian::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 488 of file translator_hr.h.
    {
      return "Imenici";
    }
trNoMatches() [1/2]
virtual QCString TranslatorCroatian::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1462 of file translator_hr.h.
    {
        return "Nema traenih podataka";
    }
trNoMatches() [2/2]
virtual QCString TranslatorCroatian::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1462 of file translator_hr.h.
    {
        return "Nema traenih podataka";
    }
trNote() [1/2]
QCString TranslatorCroatian::trNote () [inline], [virtual]
Implements Translator.
Definition at line 636 of file translator_hr.h.
    {
      return "Primjedba";
    }
trNote() [2/2]
QCString TranslatorCroatian::trNote () [inline], [virtual]
Implements Translator.
Definition at line 636 of file translator_hr.h.
    {
      return "Primjedba";
    }
trOverloadText() [1/2]
virtual QCString TranslatorCroatian::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1213 of file translator_hr.h.
    {
       return "Ovo je preoptereena funkcija (overload). "
              "Razlikuje se od navedene metode "
              "samo po vrsti argumenata koje prihvaa.";
    }
trOverloadText() [2/2]
virtual QCString TranslatorCroatian::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1213 of file translator_hr.h.
    {
       return "Ovo je preoptereena funkcija (overload). "
              "Razlikuje se od navedene metode "
              "samo po vrsti argumenata koje prihvaa.";
    }
trPackage() [1/2]
virtual QCString TranslatorCroatian::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 831 of file translator_hr.h.
    {
      return "Paket "+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorCroatian::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 831 of file translator_hr.h.
    {
      return "Paket "+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorCroatian::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1080 of file translator_hr.h.
    {
      return "Atributi u paketu";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorCroatian::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1080 of file translator_hr.h.
    {
      return "Atributi u paketu";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorCroatian::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1062 of file translator_hr.h.
    {
      return "Funkcije u paketu";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorCroatian::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1062 of file translator_hr.h.
    {
      return "Funkcije u paketu";
    }
trPackageListDescription() [1/2]
virtual QCString TranslatorCroatian::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 836 of file translator_hr.h.
    {
      return "Paketi s kratkim opisom (ukoliko postoji):";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorCroatian::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 836 of file translator_hr.h.
    {
      return "Paketi s kratkim opisom (ukoliko postoji):";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorCroatian::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1066 of file translator_hr.h.
    {
      return "lanovi u paketu";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorCroatian::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1066 of file translator_hr.h.
    {
      return "lanovi u paketu";
    }
trPackages() [1/2]
virtual QCString TranslatorCroatian::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 841 of file translator_hr.h.
    {
      return "Paketi";
    }
trPackages() [2/2]
virtual QCString TranslatorCroatian::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 841 of file translator_hr.h.
    {
      return "Paketi";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorCroatian::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1055 of file translator_hr.h.
    {
      return "Tipovi u paketu";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorCroatian::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1055 of file translator_hr.h.
    {
      return "Tipovi u paketu";
    }
trPage() [1/2]
virtual QCString TranslatorCroatian::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 936 of file translator_hr.h.
    {
      QCString result((first_capital ? "Stranic" : "stranic"));
      result+= (singular ? "a" : "e");
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorCroatian::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 936 of file translator_hr.h.
    {
      QCString result((first_capital ? "Stranic" : "stranic"));
      result+= (singular ? "a" : "e");
      return result;
    }
trPageAbbreviation() [1/2]
QCString TranslatorCroatian::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 536 of file translator_hr.h.
    { return "str."; }
trPageAbbreviation() [2/2]
QCString TranslatorCroatian::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 536 of file translator_hr.h.
    { return "str."; }
trPageIndex() [1/2]
QCString TranslatorCroatian::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 627 of file translator_hr.h.
    {
      return "Indeks stranice";
    }
trPageIndex() [2/2]
QCString TranslatorCroatian::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 627 of file translator_hr.h.
    {
      return "Indeks stranice";
    }
trParameters() [1/2]
QCString TranslatorCroatian::trParameters () [inline], [virtual]
Implements Translator.
Definition at line 315 of file translator_hr.h.
    { return "Parametri"; }
trParameters() [2/2]
QCString TranslatorCroatian::trParameters () [inline], [virtual]
Implements Translator.
Definition at line 315 of file translator_hr.h.
    { return "Parametri"; }
trPostcondition() [1/2]
QCString TranslatorCroatian::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 596 of file translator_hr.h.
    {
      return "Postuvjeti";
    }
trPostcondition() [2/2]
QCString TranslatorCroatian::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 596 of file translator_hr.h.
    {
      return "Postuvjeti";
    }
trPrecondition() [1/2]
QCString TranslatorCroatian::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 591 of file translator_hr.h.
    {
      return "Preduvjeti";
    }
trPrecondition() [2/2]
QCString TranslatorCroatian::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 591 of file translator_hr.h.
    {
      return "Preduvjeti";
    }
trPrivateAttribs() [1/2]
QCString TranslatorCroatian::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 668 of file translator_hr.h.
    {
      return "Private atributi";
    }
trPrivateAttribs() [2/2]
QCString TranslatorCroatian::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 668 of file translator_hr.h.
    {
      return "Private atributi";
    }
trPrivateMembers() [1/2]
QCString TranslatorCroatian::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 400 of file translator_hr.h.
    { return "Privatni lanovi"; }
trPrivateMembers() [2/2]
QCString TranslatorCroatian::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 400 of file translator_hr.h.
    { return "Privatni lanovi"; }
trPrivateSlots() [1/2]
QCString TranslatorCroatian::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 402 of file translator_hr.h.
    { return "Privatni slotovi"; }
trPrivateSlots() [2/2]
QCString TranslatorCroatian::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 402 of file translator_hr.h.
    { return "Privatni slotovi"; }
trPrivateTypes() [1/2]
QCString TranslatorCroatian::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 664 of file translator_hr.h.
    {
      return "Private tipovi";
    }
trPrivateTypes() [2/2]
QCString TranslatorCroatian::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 664 of file translator_hr.h.
    {
      return "Private tipovi";
    }
trProperties() [1/2]
virtual QCString TranslatorCroatian::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 811 of file translator_hr.h.
    {
      return "Svojstva (property)";
    }
trProperties() [2/2]
virtual QCString TranslatorCroatian::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 811 of file translator_hr.h.
    {
      return "Svojstva (property)";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorCroatian::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 816 of file translator_hr.h.
    {
      return "Dokumentacija svojstava";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorCroatian::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 816 of file translator_hr.h.
    {
      return "Dokumentacija svojstava";
    }
trProtectedAttribs() [1/2]
QCString TranslatorCroatian::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 656 of file translator_hr.h.
    {
      return "Protected atributi";
    }
trProtectedAttribs() [2/2]
QCString TranslatorCroatian::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 656 of file translator_hr.h.
    {
      return "Protected atributi";
    }
trProtectedMembers() [1/2]
QCString TranslatorCroatian::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 394 of file translator_hr.h.
    { return "Protected lanovi"; }
trProtectedMembers() [2/2]
QCString TranslatorCroatian::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 394 of file translator_hr.h.
    { return "Protected lanovi"; }
trProtectedSlots() [1/2]
QCString TranslatorCroatian::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 396 of file translator_hr.h.
    { return "Protected slotovi"; }
trProtectedSlots() [2/2]
QCString TranslatorCroatian::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 396 of file translator_hr.h.
    { return "Protected slotovi"; }
trProtectedTypes() [1/2]
QCString TranslatorCroatian::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 652 of file translator_hr.h.
    {
      return "Protected tipovi";
    }
trProtectedTypes() [2/2]
QCString TranslatorCroatian::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 652 of file translator_hr.h.
    {
      return "Protected tipovi";
    }
trPublicAttribs() [1/2]
QCString TranslatorCroatian::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 644 of file translator_hr.h.
    {
      return "Public atributi";
    }
trPublicAttribs() [2/2]
QCString TranslatorCroatian::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 644 of file translator_hr.h.
    {
      return "Public atributi";
    }
trPublicMembers() [1/2]
QCString TranslatorCroatian::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 386 of file translator_hr.h.
    { return "Public lanovi"; }
trPublicMembers() [2/2]
QCString TranslatorCroatian::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 386 of file translator_hr.h.
    { return "Public lanovi"; }
trPublicSlots() [1/2]
QCString TranslatorCroatian::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 388 of file translator_hr.h.
    { return "Public slotovi"; }
trPublicSlots() [2/2]
QCString TranslatorCroatian::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 388 of file translator_hr.h.
    { return "Public slotovi"; }
trPublicTypes() [1/2]
QCString TranslatorCroatian::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 640 of file translator_hr.h.
    {
      return "Public tipovi";
    }
trPublicTypes() [2/2]
QCString TranslatorCroatian::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 640 of file translator_hr.h.
    {
      return "Public tipovi";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorCroatian::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 695 of file translator_hr.h.
    {
      return "Referencirano od";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorCroatian::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 695 of file translator_hr.h.
    {
      return "Referencirano od";
    }
trReferenceManual() [1/2]
QCString TranslatorCroatian::trReferenceManual () [inline], [virtual]
Implements Translator.
Definition at line 267 of file translator_hr.h.
    { return "Prirunik"; }
trReferenceManual() [2/2]
QCString TranslatorCroatian::trReferenceManual () [inline], [virtual]
Implements Translator.
Definition at line 267 of file translator_hr.h.
    { return "Prirunik"; }
trReferences() [1/2]
virtual QCString TranslatorCroatian::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 988 of file translator_hr.h.
    {
      return "Reference";
    }
trReferences() [2/2]
virtual QCString TranslatorCroatian::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 988 of file translator_hr.h.
    {
      return "Reference";
    }
trReimplementedFromList() [1/2]
QCString TranslatorCroatian::trReimplementedFromList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 444 of file translator_hr.h.
    {
      return "Reimplementirano od "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedFromList() [2/2]
QCString TranslatorCroatian::trReimplementedFromList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 444 of file translator_hr.h.
    {
      return "Reimplementirano od "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [1/2]
QCString TranslatorCroatian::trReimplementedInList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 450 of file translator_hr.h.
    {
      // used in member documentation blocks to produce a list of
      // all member that overwrite the implementation of this member.
      return "Reimplementacija u "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [2/2]
QCString TranslatorCroatian::trReimplementedInList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 450 of file translator_hr.h.
    {
      // used in member documentation blocks to produce a list of
      // all member that overwrite the implementation of this member.
      return "Reimplementacija u "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
QCString TranslatorCroatian::trRelatedFunctionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 342 of file translator_hr.h.
    { return "Dokumentacija povezanih funkcija"; }
trRelatedFunctionDocumentation() [2/2]
QCString TranslatorCroatian::trRelatedFunctionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 342 of file translator_hr.h.
    { return "Dokumentacija povezanih funkcija"; }
trRelatedFunctions() [1/2]
QCString TranslatorCroatian::trRelatedFunctions () [inline], [virtual]
Implements Translator.
Definition at line 101 of file translator_hr.h.
    { return "Povezane funkcije"; }
trRelatedFunctions() [2/2]
QCString TranslatorCroatian::trRelatedFunctions () [inline], [virtual]
Implements Translator.
Definition at line 101 of file translator_hr.h.
    { return "Povezane funkcije"; }
trRelatedPages() [1/2]
QCString TranslatorCroatian::trRelatedPages () [inline], [virtual]
Implements Translator.
Definition at line 163 of file translator_hr.h.
    { return "Stranice povezane s ovom"; }
trRelatedPages() [2/2]
QCString TranslatorCroatian::trRelatedPages () [inline], [virtual]
Implements Translator.
Definition at line 163 of file translator_hr.h.
    { return "Stranice povezane s ovom"; }
trRelatedPagesDescription() [1/2]
QCString TranslatorCroatian::trRelatedPagesDescription () [inline], [virtual]
Implements Translator.
Definition at line 222 of file translator_hr.h.
    { return "Popis povezanih stranica:"; }
trRelatedPagesDescription() [2/2]
QCString TranslatorCroatian::trRelatedPagesDescription () [inline], [virtual]
Implements Translator.
Definition at line 222 of file translator_hr.h.
    { return "Popis povezanih stranica:"; }
trRelatedSubscript() [1/2]
QCString TranslatorCroatian::trRelatedSubscript () [inline], [virtual]
Implements Translator.
Definition at line 103 of file translator_hr.h.
    { return "(To nisu member funkcije.)"; }
trRelatedSubscript() [2/2]
QCString TranslatorCroatian::trRelatedSubscript () [inline], [virtual]
Implements Translator.
Definition at line 103 of file translator_hr.h.
    { return "(To nisu member funkcije.)"; }
trRemarks() [1/2]
virtual QCString TranslatorCroatian::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 699 of file translator_hr.h.
    {
      return "Napomene";
    }
trRemarks() [2/2]
virtual QCString TranslatorCroatian::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 699 of file translator_hr.h.
    {
      return "Napomene";
    }
trReturns() [1/2]
QCString TranslatorCroatian::trReturns () [inline], [virtual]
Implements Translator.
Definition at line 311 of file translator_hr.h.
    { return "Povratne vrijednosti"; }
trReturns() [2/2]
QCString TranslatorCroatian::trReturns () [inline], [virtual]
Implements Translator.
Definition at line 311 of file translator_hr.h.
    { return "Povratne vrijednosti"; }
trReturnValues() [1/2]
QCString TranslatorCroatian::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 525 of file translator_hr.h.
    { return "Povratna vrijednost"; }
trReturnValues() [2/2]
QCString TranslatorCroatian::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 525 of file translator_hr.h.
    { return "Povratna vrijednost"; }
trRTFansicp() [1/2]
virtual QCString TranslatorCroatian::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
Implements Translator.
Definition at line 870 of file translator_hr.h.
    {
      return "1252";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorCroatian::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
Implements Translator.
Definition at line 870 of file translator_hr.h.
    {
      return "1252";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorCroatian::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
Implements Translator.
Definition at line 875 of file translator_hr.h.
    {
      return "238";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorCroatian::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
Implements Translator.
Definition at line 875 of file translator_hr.h.
    {
      return "238";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorCroatian::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 880 of file translator_hr.h.
    {
      return "Sadraj";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorCroatian::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 880 of file translator_hr.h.
    {
      return "Sadraj";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorCroatian::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1018 of file translator_hr.h.
    {
      return "Sadraj";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorCroatian::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1018 of file translator_hr.h.
    {
      return "Sadraj";
    }
trSearch() [1/2]
QCString TranslatorCroatian::trSearch () [inline], [virtual]
Implements Translator.
Definition at line 167 of file translator_hr.h.
    { return "Trai"; }
trSearch() [2/2]
QCString TranslatorCroatian::trSearch () [inline], [virtual]
Implements Translator.
Definition at line 167 of file translator_hr.h.
    { return "Trai"; }
trSearching() [1/2]
virtual QCString TranslatorCroatian::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1456 of file translator_hr.h.
    {
        return "Traim...";
    }
trSearching() [2/2]
virtual QCString TranslatorCroatian::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1456 of file translator_hr.h.
    {
        return "Traim...";
    }
trSearchMatches() [1/2]
virtual QCString TranslatorCroatian::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1153 of file translator_hr.h.
    {
        return "Pronaeno:";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorCroatian::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1153 of file translator_hr.h.
    {
        return "Pronaeno:";
    }
trSearchResults() [1/2]
virtual QCString TranslatorCroatian::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1127 of file translator_hr.h.
    {
        if (numDocuments==0)
        {
            return "Nema dokumenta koji odgovaraju vaem upitu";
        }
        else if (numDocuments==1)
        {
            return "Naen <b>1</b> dokument koji odgovara vaem upitu.";
        }
        else if (numDocuments<5)
        {
            // Croatian (AFAIK all Slavic languages except Macedonian and Bulgarian)
            // have different plural form for 2,3,4.
            return "Naena <b>$num</b> dokumenta koji odgovaraju vaem upitu."
                "Najbolji su prikazani prvi.";
        }
        else
        {
            return "Naeno <b>$num</b> dokumenata koji odgovaraju vaem upitu."
                "Najbolji su prikazani prvi.";
        }
    }
trSearchResults() [2/2]
virtual QCString TranslatorCroatian::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1127 of file translator_hr.h.
    {
        if (numDocuments==0)
        {
            return "Nema dokumenta koji odgovaraju vaem upitu";
        }
        else if (numDocuments==1)
        {
            return "Naen <b>1</b> dokument koji odgovara vaem upitu.";
        }
        else if (numDocuments<5)
        {
            // Croatian (AFAIK all Slavic languages except Macedonian and Bulgarian)
            // have different plural form for 2,3,4.
            return "Naena <b>$num</b> dokumenta koji odgovaraju vaem upitu."
                "Najbolji su prikazani prvi.";
        }
        else
        {
            return "Naeno <b>$num</b> dokumenata koji odgovaraju vaem upitu."
                "Najbolji su prikazani prvi.";
        }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorCroatian::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1115 of file translator_hr.h.
    {
        return "Rezultati pretrage";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorCroatian::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1115 of file translator_hr.h.
    {
        return "Rezultati pretrage";
    }
trSeeAlso() [1/2]
QCString TranslatorCroatian::trSeeAlso () [inline], [virtual]
Implements Translator.
Definition at line 313 of file translator_hr.h.
    { return "Vidi takoer"; }
trSeeAlso() [2/2]
QCString TranslatorCroatian::trSeeAlso () [inline], [virtual]
Implements Translator.
Definition at line 313 of file translator_hr.h.
    { return "Vidi takoer"; }
trSignals() [1/2]
QCString TranslatorCroatian::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 390 of file translator_hr.h.
    { return "Signali"; }
trSignals() [2/2]
QCString TranslatorCroatian::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 390 of file translator_hr.h.
    { return "Signali"; }
trSince() [1/2]
virtual QCString TranslatorCroatian::trSince () [inline], [virtual]
Implements Translator.
Definition at line 712 of file translator_hr.h.
    {
      return "Od";
    }
trSince() [2/2]
virtual QCString TranslatorCroatian::trSince () [inline], [virtual]
Implements Translator.
Definition at line 712 of file translator_hr.h.
    {
      return "Od";
    }
trSourceFile() [1/2]
virtual QCString TranslatorCroatian::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1164 of file translator_hr.h.
    {
      return "Izvorni kod datoteke " + filename;
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorCroatian::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1164 of file translator_hr.h.
    {
      return "Izvorni kod datoteke " + filename;
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorCroatian::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1087 of file translator_hr.h.
    {
      return "Statiki atributi u paketu";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorCroatian::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1087 of file translator_hr.h.
    {
      return "Statiki atributi u paketu";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorCroatian::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1073 of file translator_hr.h.
    {
      return "Statike funkcije u paketu";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorCroatian::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1073 of file translator_hr.h.
    {
      return "Statike funkcije u paketu";
    }
trStaticPrivateAttribs() [1/2]
QCString TranslatorCroatian::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 672 of file translator_hr.h.
    {
      return "Static private atributi";
    }
trStaticPrivateAttribs() [2/2]
QCString TranslatorCroatian::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 672 of file translator_hr.h.
    {
      return "Static private atributi";
    }
trStaticPrivateMembers() [1/2]
QCString TranslatorCroatian::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 404 of file translator_hr.h.
    { return "Statini privatni lanovi"; }
trStaticPrivateMembers() [2/2]
QCString TranslatorCroatian::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 404 of file translator_hr.h.
    { return "Statini privatni lanovi"; }
trStaticProtectedAttribs() [1/2]
QCString TranslatorCroatian::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 660 of file translator_hr.h.
    {
      return "Static protected atributi";
    }
trStaticProtectedAttribs() [2/2]
QCString TranslatorCroatian::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 660 of file translator_hr.h.
    {
      return "Static protected atributi";
    }
trStaticProtectedMembers() [1/2]
QCString TranslatorCroatian::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 398 of file translator_hr.h.
    { return "Static protected lanovi"; }
trStaticProtectedMembers() [2/2]
QCString TranslatorCroatian::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 398 of file translator_hr.h.
    { return "Static protected lanovi"; }
trStaticPublicAttribs() [1/2]
QCString TranslatorCroatian::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 648 of file translator_hr.h.
    {
      return "Static public atributi";
    }
trStaticPublicAttribs() [2/2]
QCString TranslatorCroatian::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 648 of file translator_hr.h.
    {
      return "Static public atributi";
    }
trStaticPublicMembers() [1/2]
QCString TranslatorCroatian::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 392 of file translator_hr.h.
    { return "Static public lanovi"; }
trStaticPublicMembers() [2/2]
QCString TranslatorCroatian::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 392 of file translator_hr.h.
    { return "Static public lanovi"; }
trSubprogram() [1/2]
virtual QCString TranslatorCroatian::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1421 of file translator_hr.h.
    {
      QCString result((first_capital ? "Subprogram" : "subprogram"));
      if (!singular) result+="i";
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorCroatian::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1421 of file translator_hr.h.
    {
      QCString result((first_capital ? "Subprogram" : "subprogram"));
      if (!singular) result+="i";
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorCroatian::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1297 of file translator_hr.h.
    { return "Documentacija funkcija/subrutina"; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorCroatian::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1297 of file translator_hr.h.
    { return "Documentacija funkcija/subrutina"; }
trSubprograms() [1/2]
virtual QCString TranslatorCroatian::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1291 of file translator_hr.h.
    { return "Funkcije/Subrutine"; }
trSubprograms() [2/2]
virtual QCString TranslatorCroatian::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1291 of file translator_hr.h.
    { return "Funkcije/Subrutine"; }
trTemplateParameters() [1/2]
virtual QCString TranslatorCroatian::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1561 of file translator_hr.h.
    { return "Parametri predloka"; }
trTemplateParameters() [2/2]
virtual QCString TranslatorCroatian::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1561 of file translator_hr.h.
    { return "Parametri predloka"; }
trTest() [1/2]
virtual QCString TranslatorCroatian::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 796 of file translator_hr.h.
    {
      return "Test";
    }
trTest() [2/2]
virtual QCString TranslatorCroatian::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 796 of file translator_hr.h.
    {
      return "Test";
    }
trTestList() [1/2]
virtual QCString TranslatorCroatian::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 801 of file translator_hr.h.
    {
      return "Test lista";
    }
trTestList() [2/2]
virtual QCString TranslatorCroatian::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 801 of file translator_hr.h.
    {
      return "Test lista";
    }
trThisIsTheListOfAllMembers() [1/2]
QCString TranslatorCroatian::trThisIsTheListOfAllMembers () [inline], [virtual]
Implements Translator.
Definition at line 121 of file translator_hr.h.
    { return "Ovo je popis svih lanova"; }
trThisIsTheListOfAllMembers() [2/2]
QCString TranslatorCroatian::trThisIsTheListOfAllMembers () [inline], [virtual]
Implements Translator.
Definition at line 121 of file translator_hr.h.
    { return "Ovo je popis svih lanova"; }
trTodo() [1/2]
virtual QCString TranslatorCroatian::trTodo () [inline], [virtual]
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 681 of file translator_hr.h.
    {
      return "Za uraditi";
    }
trTodo() [2/2]
virtual QCString TranslatorCroatian::trTodo () [inline], [virtual]
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 681 of file translator_hr.h.
    {
      return "Za uraditi";
    }
trTodoList() [1/2]
virtual QCString TranslatorCroatian::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 686 of file translator_hr.h.
    {
      return "Ostalo za uraditi";
    }
trTodoList() [2/2]
virtual QCString TranslatorCroatian::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 686 of file translator_hr.h.
    {
      return "Ostalo za uraditi";
    }
trType() [1/2]
virtual QCString TranslatorCroatian::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1411 of file translator_hr.h.
    {
      QCString result((first_capital ? "Tip" : "tip"));
      if (!singular) result+="ovi";
      return result;
    }
trType() [2/2]
virtual QCString TranslatorCroatian::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1411 of file translator_hr.h.
    {
      QCString result((first_capital ? "Tip" : "tip"));
      if (!singular) result+="ovi";
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorCroatian::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1429 of file translator_hr.h.
    {
      return "Ogranienja tipova (Type Constraints)";
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorCroatian::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1429 of file translator_hr.h.
    {
      return "Ogranienja tipova (Type Constraints)";
    }
trTypedefDocumentation() [1/2]
QCString TranslatorCroatian::trTypedefDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 284 of file translator_hr.h.
    { return "Dokumentacija typedef-a"; }
trTypedefDocumentation() [2/2]
QCString TranslatorCroatian::trTypedefDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 284 of file translator_hr.h.
    { return "Dokumentacija typedef-a"; }
trTypedefs() [1/2]
QCString TranslatorCroatian::trTypedefs () [inline], [virtual]
Implements Translator.
Definition at line 272 of file translator_hr.h.
    { return "Typedef-ovi"; }
trTypedefs() [2/2]
QCString TranslatorCroatian::trTypedefs () [inline], [virtual]
Implements Translator.
Definition at line 272 of file translator_hr.h.
    { return "Typedef-ovi"; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorCroatian::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1285 of file translator_hr.h.
    { return "Dokumentacija tipova podataka"; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorCroatian::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1285 of file translator_hr.h.
    { return "Dokumentacija tipova podataka"; }
trVariableDocumentation() [1/2]
QCString TranslatorCroatian::trVariableDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 290 of file translator_hr.h.
    { return "Dokumentacija varijable"; }
trVariableDocumentation() [2/2]
QCString TranslatorCroatian::trVariableDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 290 of file translator_hr.h.
    { return "Dokumentacija varijable"; }
trVariables() [1/2]
QCString TranslatorCroatian::trVariables () [inline], [virtual]
Implements Translator.
Definition at line 278 of file translator_hr.h.
    { return "Varijable"; }
trVariables() [2/2]
QCString TranslatorCroatian::trVariables () [inline], [virtual]
Implements Translator.
Definition at line 278 of file translator_hr.h.
    { return "Varijable"; }
trVersion() [1/2]
QCString TranslatorCroatian::trVersion () [inline], [virtual]
Implements Translator.
Definition at line 307 of file translator_hr.h.
    { return "Verzija"; }
trVersion() [2/2]
QCString TranslatorCroatian::trVersion () [inline], [virtual]
Implements Translator.
Definition at line 307 of file translator_hr.h.
    { return "Verzija"; }
trWarning() [1/2]
QCString TranslatorCroatian::trWarning () [inline], [virtual]
Implements Translator.
Definition at line 305 of file translator_hr.h.
    { return "Upozorenje"; }
trWarning() [2/2]
QCString TranslatorCroatian::trWarning () [inline], [virtual]
Implements Translator.
Definition at line 305 of file translator_hr.h.
    { return "Upozorenje"; }
trWriteList() [1/2]
QCString TranslatorCroatian::trWriteList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 408 of file translator_hr.h.
    {
      // this function is used to produce a comma-separated list of items.
      // use generateMarker(i) to indicate where item i should be put.
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+="";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
QCString TranslatorCroatian::trWriteList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 408 of file translator_hr.h.
    {
      // this function is used to produce a comma-separated list of items.
      // use generateMarker(i) to indicate where item i should be put.
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+="";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_hr.h
doxygen/src/translator_hr.h