ModuleListContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
void addModules (const GroupLinkedMap &)
void addModules (const GroupList &)
ModuleListContext ()
virtual ~ModuleListContext ()
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
void addModules (const GroupLinkedMap &)
void addModules (const GroupList &)
ModuleListContext ()
virtual ~ModuleListContext ()
Static Public Member Functions
static TemplateListIntfPtr alloc ()
static TemplateListIntfPtr alloc ()
Private Attributes
std::unique_ptr< Private > p
Additional Inherited Members
Detailed Description
Definition at line 773 of file context.h.
Constructor & Destructor Documentation
ModuleListContext() [1/2]
ModuleListContext::ModuleListContext ()
Definition at line 6735 of file context.cpp.
                                     : p(std::make_unique<Private>())
{
  p->addModules();
}
References p.
 ModuleListContext() [1/2]
ModuleListContext::~ModuleListContext () [virtual]
Definition at line 6740 of file context.cpp.
{
}
ModuleListContext() [2/2]
ModuleListContext::ModuleListContext ()
 ModuleListContext() [2/2]
virtual ModuleListContext::~ModuleListContext () [virtual]
Member Function Documentation
addModules() [1/4]
void ModuleListContext::addModules (const GroupLinkedMap &)
addModules() [2/4]
void ModuleListContext::addModules (const GroupLinkedMap &)
addModules() [3/4]
void ModuleListContext::addModules (const GroupList &)
addModules() [4/4]
void ModuleListContext::addModules (const GroupList &)
alloc() [1/2]
static TemplateListIntfPtr ModuleListContext::alloc () [inline], [static]
Definition at line 776 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<ModuleListContext>()); }
Referenced by generateOutputViaTemplate().
alloc() [2/2]
static TemplateListIntfPtr ModuleListContext::alloc () [inline], [static]
Definition at line 776 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<ModuleListContext>()); }
at() [1/2]
TemplateVariant ModuleListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 6750 of file context.cpp.
{
  return p->at(index);
}
References p.
at() [2/2]
virtual TemplateVariant ModuleListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
count() [1/2]
size_t ModuleListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Definition at line 6745 of file context.cpp.
{
  return p->count();
}
References p.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
count() [2/2]
virtual size_t ModuleListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
createIterator() [1/2]
TemplateListIntf::ConstIteratorPtr ModuleListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 6755 of file context.cpp.
{
  return p->createIterator();
}
References p.
createIterator() [2/2]
virtual TemplateListIntf::ConstIteratorPtr ModuleListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Member Data Documentation
p
std::unique_ptr< Private > ModuleListContext::p [private]
Definition at line 792 of file context.h.
Referenced by at(), count(), createIterator(), and ModuleListContext().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.h
doxygen/src/context.h
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp