InputString Class Reference
#include <inputstring.h>
Public Types
enum StringMode {
StringFree =0
, StringFile =1
, StringDir =2
, StringFixed =3
,
StringImage =4
, StringFileDir =5
, StringFree =0
, StringFile =1
,
StringDir =2
, StringFixed =3
, StringImage =4
, StringFileDir =5
 }
enum StringMode {
StringFree =0
, StringFile =1
, StringDir =2
, StringFixed =3
,
StringImage =4
, StringFileDir =5
, StringFree =0
, StringFile =1
,
StringDir =2
, StringFixed =3
, StringImage =4
, StringFileDir =5
 }
Public Slots
void reset ()
void setValue (const QString &)
void reset ()
void setValue (const QString &)
Signals
void changed ()
void showHelp (Input *)
void changed ()
void showHelp (Input *)
Public Member Functions
InputString (QGridLayout *layout, int &row, const QString &id, const QString &s, StringMode m, const QString &docs, const QString &absPath=QString())
~InputString ()
void addValue (QString s)
void setDefault ()
QVariant & value ()
void update ()
Kind kind () const
StringMode stringMode () const
QString docs () const
QString id () const
QString templateDocs () const
void addDependency (Input *)
void setEnabled (bool)
void updateDependencies ()
bool isDefault ()
void writeValue (QTextStream &t, TextCodecAdapter *codec)
void setTemplateDocs (const QString &docs)
bool isEmpty ()
QString checkEnumVal (const QString &value)
InputString (QGridLayout *layout, int &row, const QString &id, const QString &s, StringMode m, const QString &docs, const QString &absPath=QString())
~InputString ()
void addValue (QString s)
void setDefault ()
QVariant & value ()
void update ()
Kind kind () const
StringMode stringMode () const
QString docs () const
QString id () const
QString templateDocs () const
void addDependency (Input *)
void setEnabled (bool)
void updateDependencies ()
bool isDefault ()
void writeValue (QTextStream &t, TextCodecAdapter *codec)
void setTemplateDocs (const QString &docs)
bool isEmpty ()
QString checkEnumVal (const QString &value)
Private Slots
void browseFile ()
void browseDir ()
void clear ()
void help ()
void browseFile ()
void browseDir ()
void clear ()
void help ()
Private Member Functions
void updateDefault ()
void updateDefault ()
Private Attributes
QLabel * m_lab
QLineEdit * m_le
QLabel * m_im
QToolBar * m_br
QAction * m_brFile
QAction * m_brDir
QComboBox * m_com
QString m_str
QString m_default
StringMode m_sm
QStringList m_values
int m_index
QVariant m_value
QString m_docs
QString m_id
bool m_absPath
QString m_tdocs
Detailed Description
Definition at line 29 of file inputstring.h.
Member Enumeration Documentation
StringMode [1/2]
enum InputString::StringMode
Enumerator
StringFree
StringFile
StringDir
StringFixed
StringImage
StringFileDir
StringFree
StringFile
StringDir
StringFixed
StringImage
StringFileDir
Definition at line 34 of file inputstring.h.
                    { StringFree=0,
                      StringFile=1,
                      StringDir=2,
                      StringFixed=3,
                      StringImage=4,
                      StringFileDir=5
                    };
StringMode [2/2]
enum InputString::StringMode
Enumerator
StringFree
StringFile
StringDir
StringFixed
StringImage
StringFileDir
StringFree
StringFile
StringDir
StringFixed
StringImage
StringFileDir
Definition at line 34 of file inputstring.h.
                    { StringFree=0,
                      StringFile=1,
                      StringDir=2,
                      StringFixed=3,
                      StringImage=4,
                      StringFileDir=5
                    };
Constructor & Destructor Documentation
InputString() [1/2]
InputString::InputString (QGridLayout * layout, int & row, const QString & id, const QString & s, StringMode m, const QString & docs, const QString & absPath = QString())
Definition at line 37 of file inputstring.cpp.
  : m_default(s), m_sm(m), m_index(0), m_docs(docs), m_id(id),
    m_absPath(absPath==QString::fromLatin1("1"))
{
  m_lab = new HelpLabel(id);
  m_brFile = 0;
  m_brDir = 0;
  if (m==StringFixed)
  {
    layout->addWidget(m_lab, row, 0);
    m_com = new NoWheelComboBox;
    layout->addWidget(m_com, row, 1, 1, 3, Qt::AlignLeft);
    m_le=0;
    m_br=0;
    m_im=0;
    row++;
  }
  else
  {
    layout->addWidget(m_lab, row, 0);
    m_le = new QLineEdit;
    m_le->setText(s);
    m_im = 0;
    //layout->setColumnMinimumWidth(2,150);
    if (m==StringFile || m==StringDir || m==StringImage || m==StringFileDir)
    {
      QHBoxLayout *rowLayout = new QHBoxLayout;
      rowLayout->addWidget(m_le);
      m_br = new QToolBar;
      m_br->setIconSize(QSize(24,24));
      if (m==StringFile || m==StringImage || m==StringFileDir)
      {
        m_brFile = m_br->addAction(QIcon(QString::fromLatin1(":/images/file.png")),QString(),this,SLOT(browseFile()));
        m_brFile->setToolTip(tr("Browse to a file"));
        if (m==StringImage)
        {
          m_im = new QLabel;
          m_im->setMinimumSize(1,55);
          m_im->setAlignment(Qt::AlignLeft|Qt::AlignTop);
          row++;
          layout->addWidget(m_im,row,1);
        }
      }
      if (m==StringDir || m==StringFileDir)
      {
        m_brDir = m_br->addAction(QIcon(QString::fromLatin1(":/images/folder.png")),QString(),this,SLOT(browseDir()));
        m_brDir->setToolTip(tr("Browse to a folder"));
      }
      rowLayout->addWidget(m_br);
      layout->addLayout(rowLayout, m==StringImage?row-1:row, 1, 1, 2);
    }
    else
    {
      layout->addWidget(m_le, row, 1, 1, 2);
      m_br=0;
      m_im=0;
    }
    m_com=0;
    row++;
  }
  if (m_le) connect(m_le, SIGNAL(textChanged(const QString&)),
                      this, SLOT(setValue(const QString&)));
  if (m_com) connect(m_com, SIGNAL(textActivated(const QString &)),
                      this, SLOT(setValue(const QString &)));
  m_str = s+QChar::fromLatin1('!'); // force update
  setValue(s);
  connect(m_lab, SIGNAL(enter()), SLOT(help()));
  connect(m_lab, SIGNAL(reset()), SLOT(reset()));
}
References AlignLeft, browseDir(), browseFile(), help(), m_br, m_brDir, m_brFile, m_com, m_im, m_lab, m_le, m_str, reset(), s, setValue(), StringDir, StringFile, StringFileDir, StringFixed, and StringImage.
 InputString() [1/2]
InputString::~InputString ()
Definition at line 117 of file inputstring.cpp.
{
}
InputString() [2/2]
InputString::InputString (QGridLayout * layout, int & row, const QString & id, const QString & s, StringMode m, const QString & docs, const QString & absPath = QString())
 InputString() [2/2]
InputString::~InputString ()
Member Function Documentation
addDependency() [1/2]
void InputString::addDependency (Input *) [inline], [virtual]
Implements Input.
Definition at line 59 of file inputstring.h.
{ Q_ASSERT(false); }
addDependency() [2/2]
void InputString::addDependency (Input *) [inline], [virtual]
Implements Input.
Definition at line 59 of file inputstring.h.
{ Q_ASSERT(false); }
addValue() [1/2]
void InputString::addValue (QString s)
Definition at line 224 of file inputstring.cpp.
{
  if (m_sm==StringFixed)
  {
    m_values.append(s);
    m_com->addItem(s);
  }
}
References m_com, m_sm, m_values, s, and StringFixed.
Referenced by Expert::createTopicWidget().
addValue() [2/2]
void InputString::addValue (QString s)
browseDir [1/2]
void InputString::browseDir () [private], [slot]
Definition at line 201 of file inputstring.cpp.
{
  QString path = QFileInfo(MainWindow::instance().configFileName()).path();
  {
    QString dirName = QFileDialog::getExistingDirectory(&MainWindow::instance(),
        tr("Select directory"),path);
    if (!dirName.isNull())
    {
      QDir dir(path);
      if (!MainWindow::instance().configFileName().isEmpty() && dir.exists())
      {
        dirName = m_absPath ? dirName : dir.relativeFilePath(dirName);
      }
      setValue(dirName);
    }
  }
}
References MainWindow::instance(), isEmpty(), m_absPath, and setValue().
Referenced by InputString().
browseDir [2/2]
void InputString::browseDir () [private], [slot]
browseFile [1/2]
void InputString::browseFile () [private], [slot]
Definition at line 186 of file inputstring.cpp.
{
  QString path = QFileInfo(MainWindow::instance().configFileName()).path();
  QString fileName = QFileDialog::getOpenFileName(&MainWindow::instance(),
      tr("Select file"),path);
  if (!fileName.isNull())
  {
    QDir dir(path);
    if (!MainWindow::instance().configFileName().isEmpty() && dir.exists())
    {
      fileName = m_absPath ? fileName : dir.relativeFilePath(fileName);
    }
    setValue(fileName);
  }
}
References MainWindow::instance(), isEmpty(), m_absPath, and setValue().
Referenced by InputString().
browseFile [2/2]
void InputString::browseFile () [private], [slot]
changed [1/2]
void InputString::changed () [signal]
Referenced by updateDefault().
changed [2/2]
void InputString::changed () [signal]
checkEnumVal() [1/2]
QString InputString::checkEnumVal (const QString & value)
Definition at line 266 of file inputstring.cpp.
{
  QString val = value.trimmed().toLower();
  QStringList::Iterator it;
  for (it= m_values.begin(); it != m_values.end(); ++it)
  {
    QString enumVal = *it;
    if (enumVal.toLower() == val) return enumVal;
  }
  config_warn("argument '%s' for option %s is not a valid enum value."
              " Using the default: %s!",qPrintable(value),qPrintable(m_id),qPrintable(m_default));
  return m_default;
}
References config_warn(), m_default, m_id, m_values, testsqlite3::val, and value().
Referenced by processString().
checkEnumVal() [2/2]
QString InputString::checkEnumVal (const QString & value)
clear [1/2]
void InputString::clear () [private], [slot]
Definition at line 219 of file inputstring.cpp.
{
  setValue(QString());
}
References setValue().
clear [2/2]
void InputString::clear () [private], [slot]
docs() [1/2]
QString InputString::docs () const [inline], [virtual]
Implements Input.
Definition at line 56 of file inputstring.h.
{ return m_docs; }
References m_docs.
Referenced by setTemplateDocs().
docs() [2/2]
QString InputString::docs () const [inline], [virtual]
Implements Input.
Definition at line 56 of file inputstring.h.
{ return m_docs; }
References m_docs.
help [1/2]
void InputString::help () [private], [slot]
Definition at line 111 of file inputstring.cpp.
{
  showHelp(this);
}
References showHelp().
Referenced by InputString().
help [2/2]
void InputString::help () [private], [slot]
id() [1/2]
QString InputString::id () const [inline], [virtual]
Implements Input.
Definition at line 57 of file inputstring.h.
{ return m_id; }
References m_id.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), and doxmlparser.compound.docXRefSectType::set_id().
id() [2/2]
QString InputString::id () const [inline], [virtual]
Implements Input.
Definition at line 57 of file inputstring.h.
{ return m_id; }
References m_id.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), and doxmlparser.compound.docXRefSectType::set_id().
isDefault() [1/2]
bool InputString::isDefault () [virtual]
Implements Input.
Definition at line 261 of file inputstring.cpp.
{
  return m_str == m_default;
}
References m_default, and m_str.
isDefault() [2/2]
bool InputString::isDefault () [virtual]
Implements Input.
isEmpty() [1/2]
bool InputString::isEmpty () [inline], [virtual]
Reimplemented from Input.
Definition at line 65 of file inputstring.h.
{ return m_str.isEmpty(); }
References m_str.
Referenced by browseDir(), and browseFile().
isEmpty() [2/2]
bool InputString::isEmpty () [inline], [virtual]
Reimplemented from Input.
Definition at line 65 of file inputstring.h.
{ return m_str.isEmpty(); }
References m_str.
kind() [1/2]
Kind InputString::kind () const [inline], [virtual]
Implements Input.
Definition at line 54 of file inputstring.h.
{ return String; }
References Input::String.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.sectiondefType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.docParamListType::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.sectiondefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.docSimpleSectType::buildAttributes(), doxmlparser.compound.docParamListType::buildAttributes(), doxmlparser.index.CompoundType::buildAttributes(), doxmlparser.index.MemberType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.index.CompoundType::exportAttributes(), doxmlparser.compound.docParamListType::exportAttributes(), doxmlparser.compound.docSimpleSectType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.index.MemberType::exportAttributes(), doxmlparser.compound.sectiondefType::exportAttributes(), doxmlparser.compound.compounddefType::get_kind(), doxmlparser.compound.sectiondefType::get_kind(), doxmlparser.compound.memberdefType::get_kind(), doxmlparser.compound.docSimpleSectType::get_kind(), doxmlparser.compound.docParamListType::get_kind(), doxmlparser.index.CompoundType::get_kind(), doxmlparser.index.MemberType::get_kind(), doxmlparser.compound.compounddefType::set_kind(), doxmlparser.compound.sectiondefType::set_kind(), doxmlparser.compound.memberdefType::set_kind(), doxmlparser.compound.docSimpleSectType::set_kind(), doxmlparser.compound.docParamListType::set_kind(), doxmlparser.index.CompoundType::set_kind(), and doxmlparser.index.MemberType::set_kind().
kind() [2/2]
Kind InputString::kind () const [inline], [virtual]
Implements Input.
Definition at line 54 of file inputstring.h.
{ return String; }
References Input::String.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.sectiondefType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.docParamListType::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.sectiondefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.docSimpleSectType::buildAttributes(), doxmlparser.compound.docParamListType::buildAttributes(), doxmlparser.index.CompoundType::buildAttributes(), doxmlparser.index.MemberType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.index.CompoundType::exportAttributes(), doxmlparser.compound.docParamListType::exportAttributes(), doxmlparser.compound.docSimpleSectType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.index.MemberType::exportAttributes(), doxmlparser.compound.sectiondefType::exportAttributes(), doxmlparser.compound.compounddefType::get_kind(), doxmlparser.compound.sectiondefType::get_kind(), doxmlparser.compound.memberdefType::get_kind(), doxmlparser.compound.docSimpleSectType::get_kind(), doxmlparser.compound.docParamListType::get_kind(), doxmlparser.index.CompoundType::get_kind(), doxmlparser.index.MemberType::get_kind(), doxmlparser.compound.compounddefType::set_kind(), doxmlparser.compound.sectiondefType::set_kind(), doxmlparser.compound.memberdefType::set_kind(), doxmlparser.compound.docSimpleSectType::set_kind(), doxmlparser.compound.docParamListType::set_kind(), doxmlparser.index.CompoundType::set_kind(), and doxmlparser.index.MemberType::set_kind().
reset [1/2]
void InputString::reset () [slot]
Definition at line 250 of file inputstring.cpp.
{
  setValue(m_default);
  setDefault();
}
References m_default, setDefault(), and setValue().
Referenced by InputString().
reset [2/2]
void InputString::reset () [slot]
setDefault() [1/2]
void InputString::setDefault ()
Definition at line 233 of file inputstring.cpp.
{
  int index = m_values.indexOf(m_str);
  if (index!=-1 && m_com) m_com->setCurrentIndex(index);
}
References m_com, m_str, and m_values.
Referenced by Expert::createTopicWidget(), reset(), and update().
setDefault() [2/2]
void InputString::setDefault ()
setEnabled() [1/2]
void InputString::setEnabled (bool state) [virtual]
Implements Input.
Definition at line 174 of file inputstring.cpp.
{
  m_lab->setEnabled(state);
  if (m_le) m_le->setEnabled(state);
  if (m_im) m_im->setEnabled(state);
  if (m_br) m_br->setEnabled(state);
  if (m_brFile) m_brFile->setEnabled(state);
  if (m_brDir) m_brDir->setEnabled(state);
  if (m_com) m_com->setEnabled(state);
  updateDefault();
}
References m_br, m_brDir, m_brFile, m_com, m_im, m_lab, m_le, and updateDefault().
setEnabled() [2/2]
void InputString::setEnabled (bool) [virtual]
Implements Input.
setTemplateDocs() [1/2]
void InputString::setTemplateDocs (const QString & docs) [inline], [virtual]
Implements Input.
Definition at line 64 of file inputstring.h.
{ m_tdocs = docs; }
References docs(), and m_tdocs.
setTemplateDocs() [2/2]
void InputString::setTemplateDocs (const QString & docs) [inline], [virtual]
Implements Input.
Definition at line 64 of file inputstring.h.
{ m_tdocs = docs; }
References docs(), and m_tdocs.
setValue [1/2]
void InputString::setValue (const QString & s) [slot]
Definition at line 122 of file inputstring.cpp.
{
  if (m_str!=s)
  {
    m_str = s;
    m_value = m_str;
    updateDefault();
  }
}
References m_str, m_value, s, and updateDefault().
Referenced by browseDir(), browseFile(), clear(), InputString(), reset(), update(), and upgradeConfig().
setValue [2/2]
void InputString::setValue (const QString &) [slot]
showHelp [1/2]
void InputString::showHelp (Input *) [signal]
Referenced by help().
showHelp [2/2]
void InputString::showHelp (Input *) [signal]
stringMode() [1/2]
StringMode InputString::stringMode () const [inline]
Definition at line 55 of file inputstring.h.
{ return m_sm; }
References m_sm.
stringMode() [2/2]
StringMode InputString::stringMode () const [inline]
Definition at line 55 of file inputstring.h.
{ return m_sm; }
References m_sm.
templateDocs() [1/2]
QString InputString::templateDocs () const [inline], [virtual]
Implements Input.
Definition at line 58 of file inputstring.h.
{ return m_tdocs; }
References m_tdocs.
templateDocs() [2/2]
QString InputString::templateDocs () const [inline], [virtual]
Implements Input.
Definition at line 58 of file inputstring.h.
{ return m_tdocs; }
References m_tdocs.
update() [1/2]
void InputString::update () [virtual]
Implements Input.
Definition at line 244 of file inputstring.cpp.
{
  setValue(m_value.toString().trimmed());
  setDefault();
}
References m_value, setDefault(), and setValue().
Referenced by runtests.Tester::__init__(), and runtests.Tester::run().
update() [2/2]
void InputString::update () [virtual]
Implements Input.
Referenced by runtests.Tester::__init__(), and runtests.Tester::run().
updateDefault() [1/2]
void InputString::updateDefault () [private]
Definition at line 131 of file inputstring.cpp.
{
  {
    if (m_str==m_default || !m_lab->isEnabled())
    {
      m_lab->setText(QString::fromLatin1("<qt>")+m_id+QString::fromLatin1("</qt>"));
    }
    else
    {
      m_lab->setText(QString::fromLatin1("<qt><font color='red'>")+m_id+QString::fromLatin1("</font></qt>"));
    }
    if (m_im)
    {
      if (m_str.isEmpty())
      {
        m_im->setText(tr("No Project logo selected."));
      }
      else
      {
        QFile Fout(m_str);
        if(!Fout.exists())
        {
          m_im->setText(tr("Sorry, cannot find file(")+m_str+QString::fromLatin1(");"));
        }
        else
        {
          QPixmap pm(m_str);
          if (!pm.isNull())
          {
            m_im->setPixmap(pm.scaledToHeight(55,Qt::SmoothTransformation));
          }
          else
          {
            m_im->setText(tr("Sorry, no preview available (")+m_str+QString::fromLatin1(");"));
          }
        }
      }
    }
    if (m_le && m_le->text()!=m_str) m_le->setText(m_str);
    emit changed();
  }
}
References changed(), m_default, m_id, m_im, m_lab, m_le, and m_str.
Referenced by setEnabled(), and setValue().
updateDefault() [2/2]
void InputString::updateDefault () [private]
updateDependencies() [1/2]
void InputString::updateDependencies () [inline], [virtual]
Implements Input.
Definition at line 61 of file inputstring.h.
{}
updateDependencies() [2/2]
void InputString::updateDependencies () [inline], [virtual]
Implements Input.
Definition at line 61 of file inputstring.h.
{}
value() [1/2]
QVariant & InputString::value () [virtual]
Implements Input.
Definition at line 239 of file inputstring.cpp.
{
  return m_value;
}
References m_value.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), doxmlparser.compound.docListItemType::__init__(), doxmlparser.compound.spType::__init__(), doxmlparser.compound.spType::buildAttributes(), doxmlparser.compound.docListItemType::buildAttributes(), checkEnumVal(), doxmlparser.compound.MixedContainer::export(), doxmlparser.index.MixedContainer::export(), doxmlparser.compound.docListItemType::exportAttributes(), doxmlparser.compound.spType::exportAttributes(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), doxmlparser.compound.spType::get_value(), doxmlparser.compound.docListItemType::get_value(), doxmlparser.compound.MixedContainer::getValue(), doxmlparser.index.MixedContainer::getValue(), doxmlparser.compound.spType::set_value(), doxmlparser.compound.docListItemType::set_value(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), doxmlparser.compound.MixedContainer::to_etree_simple(), doxmlparser.index.MixedContainer::to_etree_simple(), and upgradeConfig().
value() [2/2]
QVariant & InputString::value () [virtual]
Implements Input.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), doxmlparser.compound.docListItemType::__init__(), doxmlparser.compound.spType::__init__(), doxmlparser.compound.spType::buildAttributes(), doxmlparser.compound.docListItemType::buildAttributes(), doxmlparser.compound.MixedContainer::export(), doxmlparser.index.MixedContainer::export(), doxmlparser.compound.docListItemType::exportAttributes(), doxmlparser.compound.spType::exportAttributes(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), doxmlparser.compound.spType::get_value(), doxmlparser.compound.docListItemType::get_value(), doxmlparser.compound.MixedContainer::getValue(), doxmlparser.index.MixedContainer::getValue(), doxmlparser.compound.spType::set_value(), doxmlparser.compound.docListItemType::set_value(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), doxmlparser.compound.MixedContainer::to_etree_simple(), and doxmlparser.index.MixedContainer::to_etree_simple().
writeValue() [1/2]
void InputString::writeValue (QTextStream & t, TextCodecAdapter * codec) [virtual]
Implements Input.
Definition at line 256 of file inputstring.cpp.
{
  writeStringValue(t,codec,m_str);
}
References m_str, and writeStringValue().
writeValue() [2/2]
void InputString::writeValue (QTextStream & t, TextCodecAdapter * codec) [virtual]
Implements Input.
Member Data Documentation
m_absPath
bool InputString::m_absPath [private]
Definition at line 99 of file inputstring.h.
Referenced by browseDir(), and browseFile().
m_br
QToolBar * InputString::m_br [private]
Definition at line 87 of file inputstring.h.
Referenced by InputString(), and setEnabled().
m_brDir
QAction * InputString::m_brDir [private]
Definition at line 89 of file inputstring.h.
Referenced by InputString(), and setEnabled().
m_brFile
QAction * InputString::m_brFile [private]
Definition at line 88 of file inputstring.h.
Referenced by InputString(), and setEnabled().
m_com
QComboBox * InputString::m_com [private]
Definition at line 90 of file inputstring.h.
Referenced by addValue(), InputString(), setDefault(), and setEnabled().
m_default
QString InputString::m_default [private]
Definition at line 92 of file inputstring.h.
Referenced by checkEnumVal(), isDefault(), reset(), and updateDefault().
m_docs
QString InputString::m_docs [private]
Definition at line 97 of file inputstring.h.
Referenced by docs().
m_id
QString InputString::m_id [private]
Definition at line 98 of file inputstring.h.
Referenced by checkEnumVal(), id(), and updateDefault().
m_im
QLabel * InputString::m_im [private]
Definition at line 86 of file inputstring.h.
Referenced by InputString(), setEnabled(), and updateDefault().
m_index
int InputString::m_index [private]
Definition at line 95 of file inputstring.h.
m_lab
QLabel * InputString::m_lab [private]
Definition at line 84 of file inputstring.h.
Referenced by InputString(), setEnabled(), and updateDefault().
m_le
QLineEdit * InputString::m_le [private]
Definition at line 85 of file inputstring.h.
Referenced by InputString(), setEnabled(), and updateDefault().
m_sm
StringMode InputString::m_sm [private]
Definition at line 93 of file inputstring.h.
Referenced by addValue(), and stringMode().
m_str
QString InputString::m_str [private]
Definition at line 91 of file inputstring.h.
Referenced by InputString(), isDefault(), isEmpty(), setDefault(), setValue(), updateDefault(), and writeValue().
m_tdocs
QString InputString::m_tdocs [private]
Definition at line 100 of file inputstring.h.
Referenced by setTemplateDocs(), and templateDocs().
m_value
QVariant InputString::m_value [private]
Definition at line 96 of file inputstring.h.
Referenced by setValue(), update(), and value().
m_values
QStringList InputString::m_values [private]
Definition at line 94 of file inputstring.h.
Referenced by addValue(), checkEnumVal(), and setDefault().
The documentation for this class was generated from the following files:
doxygen/addon/doxywizard/inputstring.h
doxygen/build/doxygen/addon/doxywizard/inputstring.h
doxygen/addon/doxywizard/inputstring.cpp
doxygen/build/doxygen/addon/doxywizard/inputstring.cpp