TranslatorAdapter_1_9_2 Class Reference
#include <translator_adapter.h>
Public Member Functions
virtual QCString updateNeededMessage ()
virtual QCString trConcept (bool first_capital, bool singular)
virtual QCString trConceptReference (const QCString &conceptName)
virtual QCString trConceptList ()
virtual QCString trConceptIndex ()
virtual QCString trConceptDocumentation ()
virtual QCString trConceptListDescription (bool extractAll)
virtual QCString trConceptDefinition ()
virtual QCString updateNeededMessage ()
virtual QCString trConcept (bool first_capital, bool singular)
virtual QCString trConceptReference (const QCString &conceptName)
virtual QCString trConceptList ()
virtual QCString trConceptIndex ()
virtual QCString trConceptDocumentation ()
virtual QCString trConceptListDescription (bool extractAll)
virtual QCString trConceptDefinition ()
Additional Inherited Members
Detailed Description
Definition at line 63 of file translator_adapter.h.
Member Function Documentation
trConcept() [1/2]
virtual QCString TranslatorAdapter_1_9_2::trConcept (bool first_capital, bool singular) [inline], [virtual]
Implements Translator.
Definition at line 69 of file translator_adapter.h.
    { return english.trConcept(first_capital,singular); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trConcept().
trConcept() [2/2]
virtual QCString TranslatorAdapter_1_9_2::trConcept (bool first_capital, bool singular) [inline], [virtual]
Implements Translator.
Definition at line 69 of file translator_adapter.h.
    { return english.trConcept(first_capital,singular); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trConcept().
trConceptDefinition() [1/2]
virtual QCString TranslatorAdapter_1_9_2::trConceptDefinition () [inline], [virtual]
Implements Translator.
Definition at line 87 of file translator_adapter.h.
    { return english.trConceptDefinition(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trConceptDefinition().
trConceptDefinition() [2/2]
virtual QCString TranslatorAdapter_1_9_2::trConceptDefinition () [inline], [virtual]
Implements Translator.
Definition at line 87 of file translator_adapter.h.
    { return english.trConceptDefinition(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trConceptDefinition().
trConceptDocumentation() [1/2]
virtual QCString TranslatorAdapter_1_9_2::trConceptDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 81 of file translator_adapter.h.
    { return english.trConceptDocumentation(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trConceptDocumentation().
trConceptDocumentation() [2/2]
virtual QCString TranslatorAdapter_1_9_2::trConceptDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 81 of file translator_adapter.h.
    { return english.trConceptDocumentation(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trConceptDocumentation().
trConceptIndex() [1/2]
virtual QCString TranslatorAdapter_1_9_2::trConceptIndex () [inline], [virtual]
Implements Translator.
Definition at line 78 of file translator_adapter.h.
    { return english.trConceptIndex(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trConceptIndex().
trConceptIndex() [2/2]
virtual QCString TranslatorAdapter_1_9_2::trConceptIndex () [inline], [virtual]
Implements Translator.
Definition at line 78 of file translator_adapter.h.
    { return english.trConceptIndex(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trConceptIndex().
trConceptList() [1/2]
virtual QCString TranslatorAdapter_1_9_2::trConceptList () [inline], [virtual]
Implements Translator.
Definition at line 75 of file translator_adapter.h.
    { return english.trConceptList(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trConceptList().
trConceptList() [2/2]
virtual QCString TranslatorAdapter_1_9_2::trConceptList () [inline], [virtual]
Implements Translator.
Definition at line 75 of file translator_adapter.h.
    { return english.trConceptList(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trConceptList().
trConceptListDescription() [1/2]
virtual QCString TranslatorAdapter_1_9_2::trConceptListDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 84 of file translator_adapter.h.
    { return english.trConceptListDescription(extractAll); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trConceptListDescription().
trConceptListDescription() [2/2]
virtual QCString TranslatorAdapter_1_9_2::trConceptListDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 84 of file translator_adapter.h.
    { return english.trConceptListDescription(extractAll); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trConceptListDescription().
trConceptReference() [1/2]
virtual QCString TranslatorAdapter_1_9_2::trConceptReference (const QCString & conceptName) [inline], [virtual]
Implements Translator.
Definition at line 72 of file translator_adapter.h.
    { return english.trConceptReference(conceptName); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trConceptReference().
trConceptReference() [2/2]
virtual QCString TranslatorAdapter_1_9_2::trConceptReference (const QCString & conceptName) [inline], [virtual]
Implements Translator.
Definition at line 72 of file translator_adapter.h.
    { return english.trConceptReference(conceptName); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trConceptReference().
updateNeededMessage() [1/2]
virtual QCString TranslatorAdapter_1_9_2::updateNeededMessage () [inline], [virtual]
This method is used to generate a warning message to signal the user that the translation of his/her language of choice needs updating. It must be implemented by the translator adapter class (pure virtual).
See also
createUpdateNeededMessage()
Reimplemented from TranslatorAdapter_1_9_4.
Reimplemented in TranslatorAdapter_1_8_19, TranslatorAdapter_1_8_15, TranslatorAdapter_1_8_4, TranslatorAdapter_1_8_2, TranslatorAdapter_1_8_0, TranslatorAdapter_1_7_5, TranslatorAdapter_1_6_0, TranslatorAdapter_1_4_6, TranslatorAdapter_1_8_19, TranslatorAdapter_1_8_15, TranslatorAdapter_1_8_4, TranslatorAdapter_1_8_2, TranslatorAdapter_1_8_0, TranslatorAdapter_1_7_5, TranslatorAdapter_1_6_0, and TranslatorAdapter_1_4_6.
Definition at line 66 of file translator_adapter.h.
    { return createUpdateNeededMessage(idLanguage(),"release 1.9.2"); }
References TranslatorAdapterBase::createUpdateNeededMessage(), and Translator::idLanguage().
updateNeededMessage() [2/2]
virtual QCString TranslatorAdapter_1_9_2::updateNeededMessage () [inline], [virtual]
This method is used to generate a warning message to signal the user that the translation of his/her language of choice needs updating. It must be implemented by the translator adapter class (pure virtual).
See also
createUpdateNeededMessage()
Reimplemented from TranslatorAdapter_1_9_4.
Reimplemented in TranslatorAdapter_1_8_19, TranslatorAdapter_1_8_15, TranslatorAdapter_1_8_4, TranslatorAdapter_1_8_2, TranslatorAdapter_1_8_0, TranslatorAdapter_1_7_5, TranslatorAdapter_1_6_0, TranslatorAdapter_1_4_6, TranslatorAdapter_1_8_19, TranslatorAdapter_1_8_15, TranslatorAdapter_1_8_4, TranslatorAdapter_1_8_2, TranslatorAdapter_1_8_0, TranslatorAdapter_1_7_5, TranslatorAdapter_1_6_0, and TranslatorAdapter_1_4_6.
Definition at line 66 of file translator_adapter.h.
    { return createUpdateNeededMessage(idLanguage(),"release 1.9.2"); }
References TranslatorAdapterBase::createUpdateNeededMessage(), and Translator::idLanguage().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_adapter.h
doxygen/src/translator_adapter.h