LatexGenerator Class Reference
#include <latexgen.h>
Public Member Functions
LatexGenerator ()
LatexGenerator (const LatexGenerator &)
LatexGenerator & operator= (const LatexGenerator &)
virtual ~LatexGenerator ()
virtual std::unique_ptr< OutputGenerator > clone () const
void cleanup ()
virtual OutputType type () const
void codify (const QCString &text)
void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip)
void writeLineNumber (const QCString &ref, const QCString &file, const QCString &anchor, int lineNumber, bool writeLineAnchor)
void writeTooltip (const QCString &id, const DocLinkInfo &docInfo, const QCString &decl, const QCString &desc, const SourceLinkInfo &defInfo, const SourceLinkInfo &declInfo)
void startCodeLine (bool hasLineNumbers)
void endCodeLine ()
void startFontClass (const QCString &s)
void endFontClass ()
void writeCodeAnchor (const QCString &anchor)
void startCodeFragment (const QCString &style)
void endCodeFragment (const QCString &style)
void writeDoc (const IDocNodeAST *node, const Definition *ctx, const MemberDef *, int id)
void startFile (const QCString &name, const QCString &manName, const QCString &title, int id)
void writeSearchInfo ()
void writeFooter (const QCString &)
void endFile ()
void clearBuffer ()
void startIndexSection (IndexSections)
void endIndexSection (IndexSections)
void writePageLink (const QCString &, bool)
void startProjectNumber ()
void endProjectNumber ()
void writeStyleInfo (int part)
void startTitleHead (const QCString &)
void startTitle ()
void endTitleHead (const QCString &, const QCString &name)
void endTitle ()
void newParagraph ()
void startParagraph (const QCString &classDef)
void endParagraph ()
void writeString (const QCString &text)
void startIndexListItem ()
void endIndexListItem ()
void startIndexList ()
void endIndexList ()
void startIndexKey ()
void endIndexKey ()
void startIndexValue (bool)
void endIndexValue (const QCString &, bool)
void startItemList ()
void endItemList ()
void startIndexItem (const QCString &ref, const QCString &file)
void endIndexItem (const QCString &ref, const QCString &file)
void docify (const QCString &text)
void writeObjectLink (const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name)
void startTextLink (const QCString &, const QCString &)
void endTextLink ()
void startHtmlLink (const QCString &url)
void endHtmlLink ()
void startTypewriter ()
void endTypewriter ()
void startGroupHeader (int)
void endGroupHeader (int)
void startItemListItem ()
void endItemListItem ()
void startMemberSections ()
void endMemberSections ()
void startHeaderSection ()
void endHeaderSection ()
void startMemberHeader (const QCString &, int)
void endMemberHeader ()
void startMemberSubtitle ()
void endMemberSubtitle ()
void startMemberDocList ()
void endMemberDocList ()
void startMemberList ()
void endMemberList ()
void startInlineHeader ()
void endInlineHeader ()
void startAnonTypeScope (int)
void endAnonTypeScope (int)
void startMemberItem (const QCString &, int, const QCString &)
void endMemberItem ()
void startMemberTemplateParams ()
void endMemberTemplateParams (const QCString &, const QCString &)
void startCompoundTemplateParams ()
void endCompoundTemplateParams ()
void startMemberGroupHeader (bool)
void endMemberGroupHeader ()
void startMemberGroupDocs ()
void endMemberGroupDocs ()
void startMemberGroup ()
void endMemberGroup (bool)
void insertMemberAlign (bool)
void insertMemberAlignLeft (int, bool)
void writeRuler ()
void writeAnchor (const QCString &fileName, const QCString &name)
void startEmphasis ()
void endEmphasis ()
void startBold ()
void endBold ()
void startDescription ()
void endDescription ()
void startDescItem ()
void endDescItem ()
void lineBreak (const QCString &style=QCString())
void startMemberDoc (const QCString &, const QCString &, const QCString &, const QCString &, int, int, bool)
void endMemberDoc (bool)
void startDoxyAnchor (const QCString &, const QCString &, const QCString &, const QCString &, const QCString &)
void endDoxyAnchor (const QCString &, const QCString &)
void writeChar (char c)
void writeLatexSpacing ()
void writeStartAnnoItem (const QCString &type, const QCString &file, const QCString &path, const QCString &name)
void writeEndAnnoItem (const QCString &name)
void startSubsection ()
void endSubsection ()
void startSubsubsection ()
void endSubsubsection ()
void startCenter ()
void endCenter ()
void startSmall ()
void endSmall ()
void startMemberDescription (const QCString &, const QCString &, bool)
void endMemberDescription ()
void startMemberDeclaration ()
void endMemberDeclaration (const QCString &, const QCString &)
void writeInheritedSectionTitle (const QCString &, const QCString &, const QCString &, const QCString &, const QCString &, const QCString &)
void startDescList (SectionTypes)
void endDescList ()
void startExamples ()
void endExamples ()
void startParamList (ParamListTypes, const QCString &title)
void endParamList ()
void startDescForItem ()
void endDescForItem ()
void startSection (const QCString &, const QCString &, SectionType)
void endSection (const QCString &, SectionType)
void addIndexItem (const QCString &, const QCString &)
void startIndent ()
void endIndent ()
void writeSynopsis ()
void startClassDiagram ()
void endClassDiagram (const ClassDiagram &, const QCString &, const QCString &)
void startPageRef ()
void endPageRef (const QCString &, const QCString &)
void startQuickIndices ()
void endQuickIndices ()
void writeSplitBar (const QCString &)
void writeNavigationPath (const QCString &)
void writeLogo ()
void writeQuickLinks (bool, HighlightedItem, const QCString &)
void writeSummaryLink (const QCString &, const QCString &, const QCString &, bool)
void startContents ()
void endContents ()
void writeNonBreakableSpace (int)
void startDescTable (const QCString &title)
void endDescTable ()
void startDescTableRow ()
void endDescTableRow ()
void startDescTableTitle ()
void endDescTableTitle ()
void startDescTableData ()
void endDescTableData ()
void lastIndexPage ()
void startDotGraph ()
void endDotGraph (DotClassGraph &)
void startInclDepGraph ()
void endInclDepGraph (DotInclDepGraph &)
void startCallGraph ()
void startGroupCollaboration ()
void endGroupCollaboration (DotGroupCollaboration &g)
void endCallGraph (DotCallGraph &)
void startDirDepGraph ()
void endDirDepGraph (DotDirDeps &g)
void writeGraphicalHierarchy (DotGfxHierarchyTable &)
void startTextBlock (bool)
void endTextBlock (bool)
void startMemberDocPrefixItem ()
void endMemberDocPrefixItem ()
void startMemberDocName (bool)
void endMemberDocName ()
void startParameterType (bool, const QCString &)
void endParameterType ()
void startParameterName (bool)
void endParameterName (bool, bool, bool)
void startParameterList (bool)
void endParameterList ()
void exceptionEntry (const QCString &, bool)
void startConstraintList (const QCString &)
void startConstraintParam ()
void endConstraintParam ()
void startConstraintType ()
void endConstraintType ()
void startConstraintDocs ()
void endConstraintDocs ()
void endConstraintList ()
void startMemberDocSimple (bool)
void endMemberDocSimple (bool)
void startInlineMemberType ()
void endInlineMemberType ()
void startInlineMemberName ()
void endInlineMemberName ()
void startInlineMemberDoc ()
void endInlineMemberDoc ()
void startLabels ()
void writeLabel (const QCString &l, bool isLast)
void endLabels ()
void setCurrentDoc (const Definition *, const QCString &, bool)
void addWord (const QCString &, bool)
LatexGenerator ()
LatexGenerator (const LatexGenerator &)
LatexGenerator & operator= (const LatexGenerator &)
virtual ~LatexGenerator ()
virtual std::unique_ptr< OutputGenerator > clone () const
void cleanup ()
virtual OutputType type () const
void codify (const QCString &text)
void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip)
void writeLineNumber (const QCString &ref, const QCString &file, const QCString &anchor, int lineNumber, bool writeLineAnchor)
void writeTooltip (const QCString &id, const DocLinkInfo &docInfo, const QCString &decl, const QCString &desc, const SourceLinkInfo &defInfo, const SourceLinkInfo &declInfo)
void startCodeLine (bool hasLineNumbers)
void endCodeLine ()
void startFontClass (const QCString &s)
void endFontClass ()
void writeCodeAnchor (const QCString &anchor)
void startCodeFragment (const QCString &style)
void endCodeFragment (const QCString &style)
void writeDoc (const IDocNodeAST *node, const Definition *ctx, const MemberDef *, int id)
void startFile (const QCString &name, const QCString &manName, const QCString &title, int id)
void writeSearchInfo ()
void writeFooter (const QCString &)
void endFile ()
void clearBuffer ()
void startIndexSection (IndexSections)
void endIndexSection (IndexSections)
void writePageLink (const QCString &, bool)
void startProjectNumber ()
void endProjectNumber ()
void writeStyleInfo (int part)
void startTitleHead (const QCString &)
void startTitle ()
void endTitleHead (const QCString &, const QCString &name)
void endTitle ()
void newParagraph ()
void startParagraph (const QCString &classDef)
void endParagraph ()
void writeString (const QCString &text)
void startIndexListItem ()
void endIndexListItem ()
void startIndexList ()
void endIndexList ()
void startIndexKey ()
void endIndexKey ()
void startIndexValue (bool)
void endIndexValue (const QCString &, bool)
void startItemList ()
void endItemList ()
void startIndexItem (const QCString &ref, const QCString &file)
void endIndexItem (const QCString &ref, const QCString &file)
void docify (const QCString &text)
void writeObjectLink (const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name)
void startTextLink (const QCString &, const QCString &)
void endTextLink ()
void startHtmlLink (const QCString &url)
void endHtmlLink ()
void startTypewriter ()
void endTypewriter ()
void startGroupHeader (int)
void endGroupHeader (int)
void startItemListItem ()
void endItemListItem ()
void startMemberSections ()
void endMemberSections ()
void startHeaderSection ()
void endHeaderSection ()
void startMemberHeader (const QCString &, int)
void endMemberHeader ()
void startMemberSubtitle ()
void endMemberSubtitle ()
void startMemberDocList ()
void endMemberDocList ()
void startMemberList ()
void endMemberList ()
void startInlineHeader ()
void endInlineHeader ()
void startAnonTypeScope (int)
void endAnonTypeScope (int)
void startMemberItem (const QCString &, int, const QCString &)
void endMemberItem ()
void startMemberTemplateParams ()
void endMemberTemplateParams (const QCString &, const QCString &)
void startCompoundTemplateParams ()
void endCompoundTemplateParams ()
void startMemberGroupHeader (bool)
void endMemberGroupHeader ()
void startMemberGroupDocs ()
void endMemberGroupDocs ()
void startMemberGroup ()
void endMemberGroup (bool)
void insertMemberAlign (bool)
void insertMemberAlignLeft (int, bool)
void writeRuler ()
void writeAnchor (const QCString &fileName, const QCString &name)
void startEmphasis ()
void endEmphasis ()
void startBold ()
void endBold ()
void startDescription ()
void endDescription ()
void startDescItem ()
void endDescItem ()
void lineBreak (const QCString &style=QCString())
void startMemberDoc (const QCString &, const QCString &, const QCString &, const QCString &, int, int, bool)
void endMemberDoc (bool)
void startDoxyAnchor (const QCString &, const QCString &, const QCString &, const QCString &, const QCString &)
void endDoxyAnchor (const QCString &, const QCString &)
void writeChar (char c)
void writeLatexSpacing ()
void writeStartAnnoItem (const QCString &type, const QCString &file, const QCString &path, const QCString &name)
void writeEndAnnoItem (const QCString &name)
void startSubsection ()
void endSubsection ()
void startSubsubsection ()
void endSubsubsection ()
void startCenter ()
void endCenter ()
void startSmall ()
void endSmall ()
void startMemberDescription (const QCString &, const QCString &, bool)
void endMemberDescription ()
void startMemberDeclaration ()
void endMemberDeclaration (const QCString &, const QCString &)
void writeInheritedSectionTitle (const QCString &, const QCString &, const QCString &, const QCString &, const QCString &, const QCString &)
void startDescList (SectionTypes)
void endDescList ()
void startExamples ()
void endExamples ()
void startParamList (ParamListTypes, const QCString &title)
void endParamList ()
void startDescForItem ()
void endDescForItem ()
void startSection (const QCString &, const QCString &, SectionType)
void endSection (const QCString &, SectionType)
void addIndexItem (const QCString &, const QCString &)
void startIndent ()
void endIndent ()
void writeSynopsis ()
void startClassDiagram ()
void endClassDiagram (const ClassDiagram &, const QCString &, const QCString &)
void startPageRef ()
void endPageRef (const QCString &, const QCString &)
void startQuickIndices ()
void endQuickIndices ()
void writeSplitBar (const QCString &)
void writeNavigationPath (const QCString &)
void writeLogo ()
void writeQuickLinks (bool, HighlightedItem, const QCString &)
void writeSummaryLink (const QCString &, const QCString &, const QCString &, bool)
void startContents ()
void endContents ()
void writeNonBreakableSpace (int)
void startDescTable (const QCString &title)
void endDescTable ()
void startDescTableRow ()
void endDescTableRow ()
void startDescTableTitle ()
void endDescTableTitle ()
void startDescTableData ()
void endDescTableData ()
void lastIndexPage ()
void startDotGraph ()
void endDotGraph (DotClassGraph &)
void startInclDepGraph ()
void endInclDepGraph (DotInclDepGraph &)
void startCallGraph ()
void startGroupCollaboration ()
void endGroupCollaboration (DotGroupCollaboration &g)
void endCallGraph (DotCallGraph &)
void startDirDepGraph ()
void endDirDepGraph (DotDirDeps &g)
void writeGraphicalHierarchy (DotGfxHierarchyTable &)
void startTextBlock (bool)
void endTextBlock (bool)
void startMemberDocPrefixItem ()
void endMemberDocPrefixItem ()
void startMemberDocName (bool)
void endMemberDocName ()
void startParameterType (bool, const QCString &)
void endParameterType ()
void startParameterName (bool)
void endParameterName (bool, bool, bool)
void startParameterList (bool)
void endParameterList ()
void exceptionEntry (const QCString &, bool)
void startConstraintList (const QCString &)
void startConstraintParam ()
void endConstraintParam ()
void startConstraintType ()
void endConstraintType ()
void startConstraintDocs ()
void endConstraintDocs ()
void endConstraintList ()
void startMemberDocSimple (bool)
void endMemberDocSimple (bool)
void startInlineMemberType ()
void endInlineMemberType ()
void startInlineMemberName ()
void endInlineMemberName ()
void startInlineMemberDoc ()
void endInlineMemberDoc ()
void startLabels ()
void writeLabel (const QCString &l, bool isLast)
void endLabels ()
void setCurrentDoc (const Definition *, const QCString &, bool)
void addWord (const QCString &, bool)
Static Public Member Functions
static void init ()
static void writeStyleSheetFile (TextStream &t)
static void writeHeaderFile (TextStream &t)
static void writeFooterFile (TextStream &t)
static void init ()
static void writeStyleSheetFile (TextStream &t)
static void writeHeaderFile (TextStream &t)
static void writeFooterFile (TextStream &t)
Private Attributes
bool m_insideTabbing = false
bool m_firstDescItem = true
bool m_disableLinks = false
QCString m_relPath
int m_indent = 0
bool templateMemberItem = false
LatexCodeGenerator m_codeGen
Additional Inherited Members
Detailed Description
Generator for LaTeX output.
Definition at line 77 of file latexgen.h.
Constructor & Destructor Documentation
LatexGenerator() [1/4]
LatexGenerator::LatexGenerator ()
Definition at line 262 of file latexgen.cpp.
                               : OutputGenerator(Config_getString(LATEX_OUTPUT)), m_codeGen(m_t)
{
  //printf("LatexGenerator::LatexGenerator() m_insideTabbing=FALSE\n");
}
LatexGenerator() [2/4]
LatexGenerator::LatexGenerator (const LatexGenerator & og)
Definition at line 267 of file latexgen.cpp.
                                                       : OutputGenerator(og), m_codeGen(m_t)
{
}
 LatexGenerator() [1/2]
LatexGenerator::~LatexGenerator () [virtual]
Definition at line 282 of file latexgen.cpp.
{
}
LatexGenerator() [3/4]
LatexGenerator::LatexGenerator ()
LatexGenerator() [4/4]
LatexGenerator::LatexGenerator (const LatexGenerator &)
 LatexGenerator() [2/2]
virtual LatexGenerator::~LatexGenerator () [virtual]
Member Function Documentation
addIndexItem() [1/2]
void LatexGenerator::addIndexItem (const QCString & s1, const QCString & s2) [virtual]
Implements BaseOutputDocInterface.
Definition at line 1513 of file latexgen.cpp.
{
  if (!s1.isEmpty())
  {
    m_t << "\\index{";
    m_t << latexEscapeLabelName(s1);
    m_t << "@{";
    m_t << latexEscapeIndexChars(s1);
    m_t << "}";
    if (!s2.isEmpty())
    {
      m_t << "!";
      m_t << latexEscapeLabelName(s2);
      m_t << "@{";
      m_t << latexEscapeIndexChars(s2);
      m_t << "}";
    }
    m_t << "}";
  }
}
References QCString::isEmpty(), latexEscapeIndexChars(), latexEscapeLabelName(), and OutputGenerator::m_t.
addIndexItem() [2/2]
void LatexGenerator::addIndexItem (const QCString & , const QCString &) [virtual]
Implements BaseOutputDocInterface.
addWord() [1/2]
void LatexGenerator::addWord (const QCString & , bool) [inline], [virtual]
Reimplemented from CodeOutputInterface.
Definition at line 331 of file latexgen.h.
{}
addWord() [2/2]
void LatexGenerator::addWord (const QCString & , bool) [inline], [virtual]
Reimplemented from CodeOutputInterface.
Definition at line 331 of file latexgen.h.
{}
cleanup() [1/2]
void LatexGenerator::cleanup () [virtual]
Implements OutputGenerator.
Definition at line 531 of file latexgen.cpp.
{
  QCString dname = Config_getString(LATEX_OUTPUT);
  Dir d(dname.str());
  clearSubDirs(d);
}
References clearSubDirs(), Config_getString, and QCString::str().
cleanup() [2/2]
void LatexGenerator::cleanup () [virtual]
Implements OutputGenerator.
clearBuffer() [1/2]
void LatexGenerator::clearBuffer ()
clearBuffer() [2/2]
void LatexGenerator::clearBuffer ()
clone() [1/2]
std::unique_ptr< OutputGenerator > LatexGenerator::clone () const [virtual]
Implements OutputGenerator.
Definition at line 277 of file latexgen.cpp.
{
  return std::make_unique<LatexGenerator>(*this);
}
clone() [2/2]
virtual std::unique_ptr< OutputGenerator > LatexGenerator::clone () const [virtual]
Implements OutputGenerator.
codify() [1/2]
void LatexGenerator::codify (const QCString & s) [inline], [virtual]
Writes an code fragment to the output. This function should keep spaces visible, should break lines at a newline and should convert tabs to the right number of spaces.
Implements CodeOutputInterface.
Definition at line 95 of file latexgen.h.
    { m_codeGen.codify(text); }
References LatexCodeGenerator::codify(), and m_codeGen.
codify() [2/2]
void LatexGenerator::codify (const QCString & s) [inline], [virtual]
Writes an code fragment to the output. This function should keep spaces visible, should break lines at a newline and should convert tabs to the right number of spaces.
Implements CodeOutputInterface.
Definition at line 95 of file latexgen.h.
    { m_codeGen.codify(text); }
References LatexCodeGenerator::codify(), and m_codeGen.
docify() [1/2]
void LatexGenerator::docify (const QCString & s) [virtual]
Writes an ASCII string to the output. Converts characters that have A special meaning, like & in html.
Implements BaseOutputDocInterface.
Definition at line 1578 of file latexgen.cpp.
{
  filterLatexString(m_t,str,
                    m_insideTabbing, // insideTabbing
                    false, // insidePre
                    false, // insideItem
                    m_codeGen.usedTableLevel()>0, // insideTable
                    false // keepSpaces
                   );
}
References filterLatexString(), m_codeGen, m_insideTabbing, OutputGenerator::m_t, and LatexCodeGenerator::usedTableLevel().
Referenced by startConstraintList(), startExamples(), startMemberDocSimple(), startParameterType(), startParamList(), writeChar(), writeObjectLink(), and writeStartAnnoItem().
docify() [2/2]
void LatexGenerator::docify (const QCString & s) [virtual]
Writes an ASCII string to the output. Converts characters that have A special meaning, like & in html.
Implements BaseOutputDocInterface.
endAnonTypeScope() [1/2]
void LatexGenerator::endAnonTypeScope (int indent) [virtual]
Implements OutputGenerator.
Definition at line 1621 of file latexgen.cpp.
{
  if (indent==0)
  {
    m_t << "\n" << "\\end{tabbing}";
    m_insideTabbing=FALSE;
  }
  m_indent=indent;
}
References FALSE, m_indent, m_insideTabbing, and OutputGenerator::m_t.
endAnonTypeScope() [2/2]
void LatexGenerator::endAnonTypeScope (int) [virtual]
Implements OutputGenerator.
endBold() [1/2]
void LatexGenerator::endBold () [inline], [virtual]
End a section of text displayed in bold face.
Implements BaseOutputDocInterface.
Definition at line 213 of file latexgen.h.
{ m_t << "}"; }
References OutputGenerator::m_t.
endBold() [2/2]
void LatexGenerator::endBold () [inline], [virtual]
End a section of text displayed in bold face.
Implements BaseOutputDocInterface.
Definition at line 213 of file latexgen.h.
{ m_t << "}"; }
References OutputGenerator::m_t.
endCallGraph() [1/2]
void LatexGenerator::endCallGraph (DotCallGraph & g) [virtual]
Implements OutputGenerator.
Definition at line 1860 of file latexgen.cpp.
{
  g.writeGraph(m_t,GOF_EPS,EOF_LaTeX,dir(),fileName(),m_relPath);
}
References OutputGenerator::dir(), EOF_LaTeX, OutputGenerator::fileName(), g, GOF_EPS, m_relPath, and OutputGenerator::m_t.
endCallGraph() [2/2]
void LatexGenerator::endCallGraph (DotCallGraph &) [virtual]
Implements OutputGenerator.
endCenter() [1/2]
void LatexGenerator::endCenter () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 233 of file latexgen.h.
{ m_t << "\\end{center}\n"; }
References OutputGenerator::m_t.
endCenter() [2/2]
void LatexGenerator::endCenter () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 233 of file latexgen.h.
{ m_t << "\\end{center}\n"; }
References OutputGenerator::m_t.
endClassDiagram() [1/2]
void LatexGenerator::endClassDiagram (const ClassDiagram & d, const QCString & fileName, const QCString &) [virtual]
Implements OutputGenerator.
Definition at line 1603 of file latexgen.cpp.
{
  d.writeFigure(m_t,dir(),fileName);
}
References OutputGenerator::dir(), OutputGenerator::fileName(), OutputGenerator::m_t, and ClassDiagram::writeFigure().
endClassDiagram() [2/2]
void LatexGenerator::endClassDiagram (const ClassDiagram & , const QCString & , const QCString &) [virtual]
Implements OutputGenerator.
endCodeFragment() [1/2]
void LatexGenerator::endCodeFragment (const QCString & style) [inline], [virtual]
Ends a block of code
Implements CodeOutputInterface.
Definition at line 120 of file latexgen.h.
    { m_codeGen.endCodeFragment(style); }
References LatexCodeGenerator::endCodeFragment(), m_codeGen, and style.
endCodeFragment() [2/2]
void LatexGenerator::endCodeFragment (const QCString & style) [inline], [virtual]
Ends a block of code
Implements CodeOutputInterface.
Definition at line 120 of file latexgen.h.
    { m_codeGen.endCodeFragment(style); }
References LatexCodeGenerator::endCodeFragment(), m_codeGen, and style.
endCodeLine() [1/2]
void LatexGenerator::endCodeLine () [inline], [virtual]
Ends a line of code started with startCodeLine()
Implements CodeOutputInterface.
Definition at line 110 of file latexgen.h.
    { m_codeGen.endCodeLine(); }
References LatexCodeGenerator::endCodeLine(), and m_codeGen.
endCodeLine() [2/2]
void LatexGenerator::endCodeLine () [inline], [virtual]
Ends a line of code started with startCodeLine()
Implements CodeOutputInterface.
Definition at line 110 of file latexgen.h.
    { m_codeGen.endCodeLine(); }
References LatexCodeGenerator::endCodeLine(), and m_codeGen.
endCompoundTemplateParams() [1/2]
void LatexGenerator::endCompoundTemplateParams () [inline], [virtual]
Implements OutputGenerator.
Definition at line 196 of file latexgen.h.
{ endSubsubsection(); }
References endSubsubsection().
endCompoundTemplateParams() [2/2]
void LatexGenerator::endCompoundTemplateParams () [inline], [virtual]
Implements OutputGenerator.
Definition at line 196 of file latexgen.h.
{ endSubsubsection(); }
References endSubsubsection().
endConstraintDocs() [1/2]
void LatexGenerator::endConstraintDocs () [virtual]
Implements OutputGenerator.
Definition at line 2021 of file latexgen.cpp.
{
}
endConstraintDocs() [2/2]
void LatexGenerator::endConstraintDocs () [virtual]
Implements OutputGenerator.
endConstraintList() [1/2]
void LatexGenerator::endConstraintList () [virtual]
Implements OutputGenerator.
Definition at line 2025 of file latexgen.cpp.
{
  m_t << "\\end{description}\n";
  m_t << "\\end{Desc}\n";
}
References OutputGenerator::m_t.
endConstraintList() [2/2]
void LatexGenerator::endConstraintList () [virtual]
Implements OutputGenerator.
endConstraintParam() [1/2]
void LatexGenerator::endConstraintParam () [virtual]
Implements OutputGenerator.
Definition at line 2003 of file latexgen.cpp.
{
}
endConstraintParam() [2/2]
void LatexGenerator::endConstraintParam () [virtual]
Implements OutputGenerator.
endConstraintType() [1/2]
void LatexGenerator::endConstraintType () [virtual]
Implements OutputGenerator.
Definition at line 2012 of file latexgen.cpp.
{
  m_t << "}]";
}
References OutputGenerator::m_t.
endConstraintType() [2/2]
void LatexGenerator::endConstraintType () [virtual]
Implements OutputGenerator.
endContents() [1/2]
void LatexGenerator::endContents () [inline], [virtual]
Implements OutputGenerator.
Definition at line 268 of file latexgen.h.
{}
endContents() [2/2]
void LatexGenerator::endContents () [inline], [virtual]
Implements OutputGenerator.
Definition at line 268 of file latexgen.h.
{}
endDescForItem() [1/2]
void LatexGenerator::endDescForItem () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 249 of file latexgen.h.
{}
endDescForItem() [2/2]
void LatexGenerator::endDescForItem () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 249 of file latexgen.h.
{}
endDescItem() [1/2]
void LatexGenerator::endDescItem () [virtual]
Ends an item of a description list and starts the description itself: e.g. </dt> in HTML.
Implements BaseOutputDocInterface.
Definition at line 1891 of file latexgen.cpp.
{
  if (m_firstDescItem)
  {
    m_t << "]\n";
    m_firstDescItem=FALSE;
  }
  else
  {
    lineBreak();
  }
}
References FALSE, lineBreak(), m_firstDescItem, and OutputGenerator::m_t.
endDescItem() [2/2]
void LatexGenerator::endDescItem () [virtual]
Ends an item of a description list and starts the description itself: e.g. </dt> in HTML.
Implements BaseOutputDocInterface.
endDescList() [1/2]
void LatexGenerator::endDescList () [inline]
Definition at line 243 of file latexgen.h.
{ m_t << "\\end{Desc}\n"; }
References OutputGenerator::m_t.
endDescList() [2/2]
void LatexGenerator::endDescList () [inline]
Definition at line 243 of file latexgen.h.
{ m_t << "\\end{Desc}\n"; }
References OutputGenerator::m_t.
endDescription() [1/2]
void LatexGenerator::endDescription () [virtual]
Ends a description list: e.g. </dl> in HTML
Implements BaseOutputDocInterface.
Definition at line 1879 of file latexgen.cpp.
{
  m_t << "\\end{description}\n";
  m_firstDescItem=TRUE;
}
References m_firstDescItem, OutputGenerator::m_t, and TRUE.
endDescription() [2/2]
void LatexGenerator::endDescription () [virtual]
Ends a description list: e.g. </dl> in HTML
Implements BaseOutputDocInterface.
endDescTable() [1/2]
void LatexGenerator::endDescTable () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1727 of file latexgen.cpp.
{
  m_codeGen.decUsedTableLevel();
  m_t << "\\end{DoxyEnumFields}\n";
}
References LatexCodeGenerator::decUsedTableLevel(), m_codeGen, and OutputGenerator::m_t.
endDescTable() [2/2]
void LatexGenerator::endDescTable () [virtual]
Implements BaseOutputDocInterface.
endDescTableData() [1/2]
void LatexGenerator::endDescTableData () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1758 of file latexgen.cpp.
{
  m_t << "\\\\\n\\hline\n\n";
}
References OutputGenerator::m_t.
endDescTableData() [2/2]
void LatexGenerator::endDescTableData () [virtual]
Implements BaseOutputDocInterface.
endDescTableRow() [1/2]
void LatexGenerator::endDescTableRow () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1740 of file latexgen.cpp.
{
}
endDescTableRow() [2/2]
void LatexGenerator::endDescTableRow () [virtual]
Implements BaseOutputDocInterface.
endDescTableTitle() [1/2]
void LatexGenerator::endDescTableTitle () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1749 of file latexgen.cpp.
{
}
endDescTableTitle() [2/2]
void LatexGenerator::endDescTableTitle () [virtual]
Implements BaseOutputDocInterface.
endDirDepGraph() [1/2]
void LatexGenerator::endDirDepGraph (DotDirDeps & g) [virtual]
Implements OutputGenerator.
Definition at line 1869 of file latexgen.cpp.
{
  g.writeGraph(m_t,GOF_EPS,EOF_LaTeX,dir(),fileName(),m_relPath);
}
References OutputGenerator::dir(), EOF_LaTeX, OutputGenerator::fileName(), g, GOF_EPS, m_relPath, and OutputGenerator::m_t.
endDirDepGraph() [2/2]
void LatexGenerator::endDirDepGraph (DotDirDeps & g) [virtual]
Implements OutputGenerator.
endDotGraph() [1/2]
void LatexGenerator::endDotGraph (DotClassGraph & g) [virtual]
Implements OutputGenerator.
Definition at line 1833 of file latexgen.cpp.
{
  g.writeGraph(m_t,GOF_EPS,EOF_LaTeX,dir(),fileName(),m_relPath);
}
References OutputGenerator::dir(), EOF_LaTeX, OutputGenerator::fileName(), g, GOF_EPS, m_relPath, and OutputGenerator::m_t.
endDotGraph() [2/2]
void LatexGenerator::endDotGraph (DotClassGraph &) [virtual]
Implements OutputGenerator.
endDoxyAnchor() [1/2]
void LatexGenerator::endDoxyAnchor (const QCString & fName, const QCString & anchor) [virtual]
Implements OutputGenerator.
Definition at line 1484 of file latexgen.cpp.
{
}
endDoxyAnchor() [2/2]
void LatexGenerator::endDoxyAnchor (const QCString & , const QCString &) [virtual]
Implements OutputGenerator.
endEmphasis() [1/2]
void LatexGenerator::endEmphasis () [inline], [virtual]
Ends a section of text displayed in italic.
Implements BaseOutputDocInterface.
Definition at line 211 of file latexgen.h.
{ m_t << "}"; }
References OutputGenerator::m_t.
endEmphasis() [2/2]
void LatexGenerator::endEmphasis () [inline], [virtual]
Ends a section of text displayed in italic.
Implements BaseOutputDocInterface.
Definition at line 211 of file latexgen.h.
{ m_t << "}"; }
References OutputGenerator::m_t.
endExamples() [1/2]
void LatexGenerator::endExamples () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1911 of file latexgen.cpp.
{
  m_t << "\\end{Desc}\n";
}
References OutputGenerator::m_t.
endExamples() [2/2]
void LatexGenerator::endExamples () [virtual]
Implements BaseOutputDocInterface.
endFile() [1/2]
void LatexGenerator::endFile () [virtual]
Implements OutputGenerator.
Definition at line 574 of file latexgen.cpp.
{
  endPlainFile();
  m_codeGen.setSourceFileName("");
}
References OutputGenerator::endPlainFile(), m_codeGen, and LatexCodeGenerator::setSourceFileName().
endFile() [2/2]
void LatexGenerator::endFile () [virtual]
Implements OutputGenerator.
endFontClass() [1/2]
void LatexGenerator::endFontClass () [inline], [virtual]
Ends a block started with startFontClass()
Implements CodeOutputInterface.
Definition at line 114 of file latexgen.h.
    { m_codeGen.endFontClass(); }
References LatexCodeGenerator::endFontClass(), and m_codeGen.
endFontClass() [2/2]
void LatexGenerator::endFontClass () [inline], [virtual]
Ends a block started with startFontClass()
Implements CodeOutputInterface.
Definition at line 114 of file latexgen.h.
    { m_codeGen.endFontClass(); }
References LatexCodeGenerator::endFontClass(), and m_codeGen.
endGroupCollaboration() [1/2]
void LatexGenerator::endGroupCollaboration (DotGroupCollaboration & g) [virtual]
Implements OutputGenerator.
Definition at line 1851 of file latexgen.cpp.
{
  g.writeGraph(m_t,GOF_EPS,EOF_LaTeX,dir(),fileName(),m_relPath);
}
References OutputGenerator::dir(), EOF_LaTeX, OutputGenerator::fileName(), g, GOF_EPS, m_relPath, and OutputGenerator::m_t.
endGroupCollaboration() [2/2]
void LatexGenerator::endGroupCollaboration (DotGroupCollaboration & g) [virtual]
Implements OutputGenerator.
endGroupHeader() [1/2]
void LatexGenerator::endGroupHeader (int) [virtual]
Implements OutputGenerator.
Definition at line 1367 of file latexgen.cpp.
{
  m_disableLinks=FALSE;
  m_t << "}\n";
}
References FALSE, m_disableLinks, and OutputGenerator::m_t.
endGroupHeader() [2/2]
void LatexGenerator::endGroupHeader (int) [virtual]
Implements OutputGenerator.
endHeaderSection() [1/2]
void LatexGenerator::endHeaderSection () [inline], [virtual]
Implements OutputGenerator.
Definition at line 178 of file latexgen.h.
{}
endHeaderSection() [2/2]
void LatexGenerator::endHeaderSection () [inline], [virtual]
Implements OutputGenerator.
Definition at line 178 of file latexgen.h.
{}
endHtmlLink() [1/2]
void LatexGenerator::endHtmlLink () [virtual]
Ends a link started by startHtmlLink().
Implements BaseOutputDocInterface.
Definition at line 1175 of file latexgen.cpp.
{
  m_t << "}}";
}
References OutputGenerator::m_t.
endHtmlLink() [2/2]
void LatexGenerator::endHtmlLink () [virtual]
Ends a link started by startHtmlLink().
Implements BaseOutputDocInterface.
endInclDepGraph() [1/2]
void LatexGenerator::endInclDepGraph (DotInclDepGraph & g) [virtual]
Implements OutputGenerator.
Definition at line 1842 of file latexgen.cpp.
{
  g.writeGraph(m_t,GOF_EPS,EOF_LaTeX,dir(),fileName(),m_relPath);
}
References OutputGenerator::dir(), EOF_LaTeX, OutputGenerator::fileName(), g, GOF_EPS, m_relPath, and OutputGenerator::m_t.
endInclDepGraph() [2/2]
void LatexGenerator::endInclDepGraph (DotInclDepGraph &) [virtual]
Implements OutputGenerator.
endIndent() [1/2]
void LatexGenerator::endIndent () [inline], [virtual]
Implements OutputGenerator.
Definition at line 254 of file latexgen.h.
{}
endIndent() [2/2]
void LatexGenerator::endIndent () [inline], [virtual]
Implements OutputGenerator.
Definition at line 254 of file latexgen.h.
{}
endIndexItem() [1/2]
void LatexGenerator::endIndexItem (const QCString & ref, const QCString & file) [virtual]
Implements OutputGenerator.
Definition at line 1148 of file latexgen.cpp.
{
  if (ref.isEmpty() && !fn.isEmpty())
  {
    m_t << "}{\\pageref{" << stripPath(fn) << "}}{}\n";
  }
}
References QCString::isEmpty(), OutputGenerator::m_t, and stripPath().
endIndexItem() [2/2]
void LatexGenerator::endIndexItem (const QCString & ref, const QCString & file) [virtual]
Implements OutputGenerator.
endIndexKey() [1/2]
void LatexGenerator::endIndexKey () [virtual]
Implements OutputGenerator.
Definition at line 1212 of file latexgen.cpp.
{
}
endIndexKey() [2/2]
void LatexGenerator::endIndexKey () [virtual]
Implements OutputGenerator.
endIndexList() [1/2]
void LatexGenerator::endIndexList () [inline], [virtual]
Implements OutputGenerator.
Definition at line 151 of file latexgen.h.
{ m_t << "\\end{DoxyCompactList}\n"; }
References OutputGenerator::m_t.
endIndexList() [2/2]
void LatexGenerator::endIndexList () [inline], [virtual]
Implements OutputGenerator.
Definition at line 151 of file latexgen.h.
{ m_t << "\\end{DoxyCompactList}\n"; }
References OutputGenerator::m_t.
endIndexListItem() [1/2]
void LatexGenerator::endIndexListItem () [inline], [virtual]
Implements OutputGenerator.
Definition at line 149 of file latexgen.h.
{}
endIndexListItem() [2/2]
void LatexGenerator::endIndexListItem () [inline], [virtual]
Implements OutputGenerator.
Definition at line 149 of file latexgen.h.
{}
endIndexSection() [1/2]
void LatexGenerator::endIndexSection (IndexSections is) [virtual]
Implements OutputGenerator.
Definition at line 893 of file latexgen.cpp.
{
  switch (is)
  {
    case isTitlePageStart:
      break;
    case isTitlePageAuthor:
      break;
    case isMainPage:
      {
        //QCString indexName=Config_getBool(GENERATE_TREEVIEW)?"main":"index";
        QCString indexName="index";
        m_t << "}\n\\label{index}";
        if (Config_getBool(PDF_HYPERLINKS)) m_t << "\\hypertarget{index}{}";
        m_t << "\\input{" << indexName << "}\n";
      }
      break;
    case isModuleIndex:
      m_t << "}\n\\input{modules}\n";
      break;
    case isDirIndex:
      m_t << "}\n\\input{dirs}\n";
      break;
    case isNamespaceIndex:
      m_t << "}\n\\input{namespaces}\n";
      break;
    case isConceptIndex:
      m_t << "}\n\\input{concepts}\n";
      break;
    case isClassHierarchyIndex:
      m_t << "}\n\\input{hierarchy}\n";
      break;
    case isCompoundIndex:
      m_t << "}\n\\input{annotated}\n";
      break;
    case isFileIndex:
      m_t << "}\n\\input{files}\n";
      break;
    case isPageIndex:
      m_t << "}\n\\input{pages}\n";
      break;
    case isModuleDocumentation:
      {
        bool found=FALSE;
        for (const auto &gd : *Doxygen::groupLinkedMap)
        {
          if (!gd->isReference())
          {
            if (!found)
            {
              m_t << "}\n";
              found=TRUE;
            }
            m_t << "\\input{" << gd->getOutputFileBase() << "}\n";
          }
        }
      }
      break;
    case isDirDocumentation:
      {
        bool found=FALSE;
        for (const auto &dd : *Doxygen::dirLinkedMap)
        {
          if (dd->isLinkableInProject())
          {
            if (!found)
            {
              m_t << "}\n";
              found = TRUE;
            }
            m_t << "\\input{" << dd->getOutputFileBase() << "}\n";
          }
        }
      }
      break;
    case isNamespaceDocumentation:
      {
        bool found=FALSE;
        for (const auto &nd : *Doxygen::namespaceLinkedMap)
        {
          if (nd->isLinkableInProject() && !nd->isAlias())
          {
            if (!found)
            {
              m_t << "}\n";
              found=true;
            }
            m_t << "\\input{" << nd->getOutputFileBase() << "}\n";
          }
        }
      }
      break;
    case isConceptDocumentation:
      {
        bool found=FALSE;
        for (const auto &cd : *Doxygen::conceptLinkedMap)
        {
          if (cd->isLinkableInProject() && !cd->isAlias())
          {
            if (!found)
            {
              m_t << "}\n";
              found=true;
            }
            m_t << "\\input{" << cd->getOutputFileBase() << "}\n";
          }
        }
      }
      break;
    case isClassDocumentation:
      {
        bool found=FALSE;
        for (const auto &cd : *Doxygen::classLinkedMap)
        {
          if (cd->isLinkableInProject() &&
              cd->templateMaster()==0 &&
             !cd->isEmbeddedInOuterScope() &&
             !cd->isAlias()
             )
          {
            if (!found)
            {
              m_t << "}\n"; // end doxysection or chapter title
              found=TRUE;
            }
            m_t << "\\input{" << cd->getOutputFileBase() << "}\n";
          }
        }
      }
      break;
    case isFileDocumentation:
      {
        bool isFirst=TRUE;
        for (const auto &fn : *Doxygen::inputNameLinkedMap)
        {
          for (const auto &fd : *fn)
          {
            if (fd->isLinkableInProject())
            {
              if (isFirst)
              {
                m_t << "}\n"; // end doxysection or chapter title
              }
              isFirst=FALSE;
              m_t << "\\input{" << fd->getOutputFileBase() << "}\n";
            }
            if (fd->generateSourceFile())
            {
              if (isFirst)
              {
                m_t << "}\n"; // end doxysection or chapter title
              }
              isFirst=FALSE;
              m_t << "\\input{" << fd->getSourceFileBase() << "}\n";
            }
          }
        }
      }
      break;
    case isExampleDocumentation:
      {
        m_t << "}\n";
        for (const auto &pd : *Doxygen::exampleLinkedMap)
        {
          m_t << "\\input{" << pd->getOutputFileBase() << "}\n";
        }
      }
      break;
    case isPageDocumentation:
      {
        m_t << "}\n";
#if 0
        bool first=TRUE;
        for (const auto *pd : Doxygen::pageLinkedMap)
        {
          if (!pd->getGroupDef() && !pd->isReference())
          {
             if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
             m_t << "{" << pd->title();
             m_t << "}\n";
            if (compactLatex || first) m_t << "\\input" ; else m_t << "\\include";
            m_t << "{" << pd->getOutputFileBase() << "}\n";
            first=FALSE;
          }
        }
#endif
      }
      break;
    case isPageDocumentation2:
      break;
    case isEndIndex:
      m_t << substituteLatexKeywords(g_footer,convertToLaTeX(Config_getString(PROJECT_NAME)));
      break;
  }
}
References Doxygen::classLinkedMap, Doxygen::conceptLinkedMap, Config_getBool, Config_getString, convertToLaTeX(), Doxygen::dirLinkedMap, Doxygen::exampleLinkedMap, FALSE, found, g_footer, Doxygen::groupLinkedMap, Doxygen::inputNameLinkedMap, isClassDocumentation, isClassHierarchyIndex, isCompoundIndex, isConceptDocumentation, isConceptIndex, isDirDocumentation, isDirIndex, isEndIndex, isExampleDocumentation, isFileDocumentation, isFileIndex, isMainPage, isModuleDocumentation, isModuleIndex, isNamespaceDocumentation, isNamespaceIndex, isPageDocumentation, isPageDocumentation2, isPageIndex, isTitlePageAuthor, isTitlePageStart, OutputGenerator::m_t, Doxygen::namespaceLinkedMap, Doxygen::pageLinkedMap, substituteLatexKeywords(), and TRUE.
endIndexSection() [2/2]
void LatexGenerator::endIndexSection (IndexSections) [virtual]
Implements OutputGenerator.
endIndexValue() [1/2]
void LatexGenerator::endIndexValue (const QCString & name, bool) [virtual]
Implements OutputGenerator.
Definition at line 1222 of file latexgen.cpp.
{
  //if (hasBrief) m_t << ")";
  m_t << "}{\\pageref{" << stripPath(name) << "}}{}\n";
}
References OutputGenerator::m_t, setup::name, and stripPath().
endIndexValue() [2/2]
void LatexGenerator::endIndexValue (const QCString & , bool) [virtual]
Implements OutputGenerator.
endInlineHeader() [1/2]
void LatexGenerator::endInlineHeader () [virtual]
Implements OutputGenerator.
Definition at line 2043 of file latexgen.cpp.
{
  m_t << "}\n";
}
References OutputGenerator::m_t.
endInlineHeader() [2/2]
void LatexGenerator::endInlineHeader () [virtual]
Implements OutputGenerator.
endInlineMemberDoc() [1/2]
void LatexGenerator::endInlineMemberDoc () [virtual]
Implements OutputGenerator.
Definition at line 2115 of file latexgen.cpp.
{
  m_t << "\\\\\n\\hline\n\n";
}
References OutputGenerator::m_t.
endInlineMemberDoc() [2/2]
void LatexGenerator::endInlineMemberDoc () [virtual]
Implements OutputGenerator.
endInlineMemberName() [1/2]
void LatexGenerator::endInlineMemberName () [virtual]
Implements OutputGenerator.
Definition at line 2105 of file latexgen.cpp.
{
  m_t << "&\n";
  m_insideTabbing = FALSE;
}
References FALSE, m_insideTabbing, and OutputGenerator::m_t.
endInlineMemberName() [2/2]
void LatexGenerator::endInlineMemberName () [virtual]
Implements OutputGenerator.
endInlineMemberType() [1/2]
void LatexGenerator::endInlineMemberType () [virtual]
Implements OutputGenerator.
Definition at line 2094 of file latexgen.cpp.
{
  m_t << "&\n";
  m_insideTabbing = FALSE;
}
References FALSE, m_insideTabbing, and OutputGenerator::m_t.
endInlineMemberType() [2/2]
void LatexGenerator::endInlineMemberType () [virtual]
Implements OutputGenerator.
endItemList() [1/2]
void LatexGenerator::endItemList () [inline], [virtual]
Ends a bullet list: e.g. </ul> in html
Implements BaseOutputDocInterface.
Definition at line 157 of file latexgen.h.
{ m_t << "\\end{DoxyCompactItemize}\n"; }
References OutputGenerator::m_t.
endItemList() [2/2]
void LatexGenerator::endItemList () [inline], [virtual]
Ends a bullet list: e.g. </ul> in html
Implements BaseOutputDocInterface.
Definition at line 157 of file latexgen.h.
{ m_t << "\\end{DoxyCompactItemize}\n"; }
References OutputGenerator::m_t.
endItemListItem() [1/2]
void LatexGenerator::endItemListItem () [inline], [virtual]
Writes a list item for a bullet or enumerated list: e.g. </li> in html
Implements BaseOutputDocInterface.
Definition at line 173 of file latexgen.h.
{}
endItemListItem() [2/2]
void LatexGenerator::endItemListItem () [inline], [virtual]
Writes a list item for a bullet or enumerated list: e.g. </li> in html
Implements BaseOutputDocInterface.
Definition at line 173 of file latexgen.h.
{}
endLabels() [1/2]
void LatexGenerator::endLabels () [virtual]
Implements OutputGenerator.
Definition at line 2131 of file latexgen.cpp.
{
}
endLabels() [2/2]
void LatexGenerator::endLabels () [virtual]
Implements OutputGenerator.
endMemberDeclaration() [1/2]
void LatexGenerator::endMemberDeclaration (const QCString & , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 239 of file latexgen.h.
{}
endMemberDeclaration() [2/2]
void LatexGenerator::endMemberDeclaration (const QCString & , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 239 of file latexgen.h.
{}
endMemberDescription() [1/2]
void LatexGenerator::endMemberDescription () [virtual]
Implements OutputGenerator.
Definition at line 1680 of file latexgen.cpp.
{
  if (!m_insideTabbing)
  {
    //m_t << "\\item\\end{DoxyCompactList}";
    m_t << "\\end{DoxyCompactList}";
  }
  else
  {
    m_t << "}\\\\\n";
  }
}
References m_insideTabbing, and OutputGenerator::m_t.
endMemberDescription() [2/2]
void LatexGenerator::endMemberDescription () [virtual]
Implements OutputGenerator.
endMemberDoc() [1/2]
void LatexGenerator::endMemberDoc (bool) [virtual]
Implements OutputGenerator.
Definition at line 1457 of file latexgen.cpp.
{
  m_disableLinks=FALSE;
  m_t << "}\n\n";
  //if (Config_getBool(COMPACT_LATEX)) m_t << "\\hfill";
}
References FALSE, m_disableLinks, and OutputGenerator::m_t.
endMemberDoc() [2/2]
void LatexGenerator::endMemberDoc (bool) [virtual]
Implements OutputGenerator.
endMemberDocList() [1/2]
void LatexGenerator::endMemberDocList () [inline], [virtual]
Implements OutputGenerator.
Definition at line 184 of file latexgen.h.
{}
endMemberDocList() [2/2]
void LatexGenerator::endMemberDocList () [inline], [virtual]
Implements OutputGenerator.
Definition at line 184 of file latexgen.h.
{}
endMemberDocName() [1/2]
void LatexGenerator::endMemberDocName () [inline], [virtual]
Implements OutputGenerator.
Definition at line 299 of file latexgen.h.
{}
endMemberDocName() [2/2]
void LatexGenerator::endMemberDocName () [inline], [virtual]
Implements OutputGenerator.
Definition at line 299 of file latexgen.h.
{}
endMemberDocPrefixItem() [1/2]
void LatexGenerator::endMemberDocPrefixItem () [inline], [virtual]
Implements OutputGenerator.
Definition at line 297 of file latexgen.h.
{ m_t << "\\\\\n"; }
References OutputGenerator::m_t.
endMemberDocPrefixItem() [2/2]
void LatexGenerator::endMemberDocPrefixItem () [inline], [virtual]
Implements OutputGenerator.
Definition at line 297 of file latexgen.h.
{ m_t << "\\\\\n"; }
References OutputGenerator::m_t.
endMemberDocSimple() [1/2]
void LatexGenerator::endMemberDocSimple (bool isEnum) [virtual]
Implements OutputGenerator.
Definition at line 2076 of file latexgen.cpp.
{
  m_codeGen.decUsedTableLevel();
  if (isEnum)
  {
    m_t << "\\end{DoxyEnumFields}\n";
  }
  else
  {
    m_t << "\\end{DoxyFields}\n";
  }
}
References LatexCodeGenerator::decUsedTableLevel(), m_codeGen, and OutputGenerator::m_t.
endMemberDocSimple() [2/2]
void LatexGenerator::endMemberDocSimple (bool) [virtual]
Implements OutputGenerator.
endMemberGroup() [1/2]
void LatexGenerator::endMemberGroup (bool hasHeader) [virtual]
Implements OutputGenerator.
Definition at line 1822 of file latexgen.cpp.
{
  if (hasHeader)m_t << "\\end{Indent}";
  m_t << "\n";
}
References OutputGenerator::m_t.
endMemberGroup() [2/2]
void LatexGenerator::endMemberGroup (bool) [virtual]
Implements OutputGenerator.
endMemberGroupDocs() [1/2]
void LatexGenerator::endMemberGroupDocs () [virtual]
Implements OutputGenerator.
Definition at line 1813 of file latexgen.cpp.
{
  m_t << "}";
}
References OutputGenerator::m_t.
endMemberGroupDocs() [2/2]
void LatexGenerator::endMemberGroupDocs () [virtual]
Implements OutputGenerator.
endMemberGroupHeader() [1/2]
void LatexGenerator::endMemberGroupHeader () [virtual]
Implements OutputGenerator.
Definition at line 1801 of file latexgen.cpp.
{
  // changed back to rev 756 due to bug 660501
  m_t << "}\\par\n";
  //m_t << "}\n";
}
References OutputGenerator::m_t.
endMemberGroupHeader() [2/2]
void LatexGenerator::endMemberGroupHeader () [virtual]
Implements OutputGenerator.
endMemberHeader() [1/2]
void LatexGenerator::endMemberHeader () [virtual]
Implements OutputGenerator.
Definition at line 1386 of file latexgen.cpp.
{
  m_disableLinks=FALSE;
  m_t << "}\n";
}
References FALSE, m_disableLinks, and OutputGenerator::m_t.
endMemberHeader() [2/2]
void LatexGenerator::endMemberHeader () [virtual]
Implements OutputGenerator.
endMemberItem() [1/2]
void LatexGenerator::endMemberItem () [virtual]
Implements OutputGenerator.
Definition at line 1657 of file latexgen.cpp.
{
  if (m_insideTabbing)
  {
    m_t << "\\\\";
  }
  templateMemberItem = FALSE;
  m_t << "\n";
}
References FALSE, m_insideTabbing, OutputGenerator::m_t, and templateMemberItem.
endMemberItem() [2/2]
void LatexGenerator::endMemberItem () [virtual]
Implements OutputGenerator.
endMemberList() [1/2]
void LatexGenerator::endMemberList () [virtual]
Implements OutputGenerator.
Definition at line 1776 of file latexgen.cpp.
{
  //printf("LatexGenerator::endMemberList(%d)\n",m_insideTabbing);
  if (!m_insideTabbing)
  {
    m_t << "\\end{DoxyCompactItemize}\n";
  }
}
References m_insideTabbing, and OutputGenerator::m_t.
endMemberList() [2/2]
void LatexGenerator::endMemberList () [virtual]
Implements OutputGenerator.
endMemberSections() [1/2]
void LatexGenerator::endMemberSections () [inline], [virtual]
Implements OutputGenerator.
Definition at line 176 of file latexgen.h.
{}
endMemberSections() [2/2]
void LatexGenerator::endMemberSections () [inline], [virtual]
Implements OutputGenerator.
Definition at line 176 of file latexgen.h.
{}
endMemberSubtitle() [1/2]
void LatexGenerator::endMemberSubtitle () [inline], [virtual]
Implements OutputGenerator.
Definition at line 182 of file latexgen.h.
{}
endMemberSubtitle() [2/2]
void LatexGenerator::endMemberSubtitle () [inline], [virtual]
Implements OutputGenerator.
Definition at line 182 of file latexgen.h.
{}
endMemberTemplateParams() [1/2]
void LatexGenerator::endMemberTemplateParams (const QCString & , const QCString &) [virtual]
Implements OutputGenerator.
Definition at line 1639 of file latexgen.cpp.
{
  if (templateMemberItem)
  {
    m_t << "}\\\\";
  }
}
References OutputGenerator::m_t, and templateMemberItem.
endMemberTemplateParams() [2/2]
void LatexGenerator::endMemberTemplateParams (const QCString & , const QCString &) [virtual]
Implements OutputGenerator.
endPageRef() [1/2]
void LatexGenerator::endPageRef (const QCString & clname, const QCString & anchor) [virtual]
Implements BaseOutputDocInterface.
Definition at line 1289 of file latexgen.cpp.
{
  m_t << "}{";
  if (!clname.isEmpty()) m_t << clname;
  if (!anchor.isEmpty()) m_t << "_" << anchor;
  m_t << "}";
}
References QCString::isEmpty(), and OutputGenerator::m_t.
endPageRef() [2/2]
void LatexGenerator::endPageRef (const QCString & , const QCString &) [virtual]
Implements BaseOutputDocInterface.
endParagraph() [1/2]
void LatexGenerator::endParagraph () [virtual]
Ends a paragraph
Implements BaseOutputDocInterface.
Definition at line 1129 of file latexgen.cpp.
{
  m_t << "\n" << "\n";
}
References OutputGenerator::m_t.
endParagraph() [2/2]
void LatexGenerator::endParagraph () [virtual]
Ends a paragraph
Implements BaseOutputDocInterface.
endParameterList() [1/2]
void LatexGenerator::endParameterList () [virtual]
Implements OutputGenerator.
Definition at line 1935 of file latexgen.cpp.
{
}
endParameterList() [2/2]
void LatexGenerator::endParameterList () [virtual]
Implements OutputGenerator.
endParameterName() [1/2]
void LatexGenerator::endParameterName (bool last, bool , bool closeBracket) [virtual]
Implements OutputGenerator.
Definition at line 1955 of file latexgen.cpp.
{
  m_t << " }";
  if (last)
  {
    m_t << "\\end{DoxyParamCaption}";
    if (closeBracket) m_t << ")";
  }
}
References OutputGenerator::m_t.
endParameterName() [2/2]
void LatexGenerator::endParameterName (bool , bool , bool) [virtual]
Implements OutputGenerator.
endParameterType() [1/2]
void LatexGenerator::endParameterType () [virtual]
Implements OutputGenerator.
Definition at line 1945 of file latexgen.cpp.
{
  m_t << "}]";
}
References OutputGenerator::m_t.
endParameterType() [2/2]
void LatexGenerator::endParameterType () [virtual]
Implements OutputGenerator.
endParamList() [1/2]
void LatexGenerator::endParamList () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1923 of file latexgen.cpp.
{
  m_t << "\\end{Desc}\n";
}
References OutputGenerator::m_t.
endParamList() [2/2]
void LatexGenerator::endParamList () [virtual]
Implements BaseOutputDocInterface.
endProjectNumber() [1/2]
void LatexGenerator::endProjectNumber () [inline], [virtual]
Implements OutputGenerator.
Definition at line 137 of file latexgen.h.
{}
endProjectNumber() [2/2]
void LatexGenerator::endProjectNumber () [inline], [virtual]
Implements OutputGenerator.
Definition at line 137 of file latexgen.h.
{}
endQuickIndices() [1/2]
void LatexGenerator::endQuickIndices () [inline], [virtual]
Implements OutputGenerator.
Definition at line 261 of file latexgen.h.
{}
endQuickIndices() [2/2]
void LatexGenerator::endQuickIndices () [inline], [virtual]
Implements OutputGenerator.
Definition at line 261 of file latexgen.h.
{}
endSection() [1/2]
void LatexGenerator::endSection (const QCString & lab, SectionType) [virtual]
Implements BaseOutputDocInterface.
Definition at line 1572 of file latexgen.cpp.
{
  m_t << "}\\label{" << lab << "}\n";
}
References OutputGenerator::m_t.
endSection() [2/2]
void LatexGenerator::endSection (const QCString & , SectionType) [virtual]
Implements BaseOutputDocInterface.
endSmall() [1/2]
void LatexGenerator::endSmall () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 235 of file latexgen.h.
{ m_t << "\\normalsize "; }
References OutputGenerator::m_t.
endSmall() [2/2]
void LatexGenerator::endSmall () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 235 of file latexgen.h.
{ m_t << "\\normalsize "; }
References OutputGenerator::m_t.
endSubsection() [1/2]
void LatexGenerator::endSubsection () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 229 of file latexgen.h.
{ m_t << "}\n"; }
References OutputGenerator::m_t.
endSubsection() [2/2]
void LatexGenerator::endSubsection () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 229 of file latexgen.h.
{ m_t << "}\n"; }
References OutputGenerator::m_t.
endSubsubsection() [1/2]
void LatexGenerator::endSubsubsection () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 231 of file latexgen.h.
{ m_t << "}\n"; }
References OutputGenerator::m_t.
Referenced by endCompoundTemplateParams().
endSubsubsection() [2/2]
void LatexGenerator::endSubsubsection () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 231 of file latexgen.h.
{ m_t << "}\n"; }
References OutputGenerator::m_t.
endTextBlock() [1/2]
void LatexGenerator::endTextBlock (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 294 of file latexgen.h.
{}
endTextBlock() [2/2]
void LatexGenerator::endTextBlock (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 294 of file latexgen.h.
{}
endTextLink() [1/2]
void LatexGenerator::endTextLink () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1252 of file latexgen.cpp.
{
  bool pdfHyperlinks = Config_getBool(PDF_HYPERLINKS);
  if (!m_disableLinks && pdfHyperlinks)
  {
    m_t << "}";
  }
  m_t << "}";
}
References Config_getBool, m_disableLinks, and OutputGenerator::m_t.
endTextLink() [2/2]
void LatexGenerator::endTextLink () [virtual]
Implements BaseOutputDocInterface.
endTitle() [1/2]
void LatexGenerator::endTitle () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 142 of file latexgen.h.
{ m_t << "}"; }
References OutputGenerator::m_t.
endTitle() [2/2]
void LatexGenerator::endTitle () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 142 of file latexgen.h.
{ m_t << "}"; }
References OutputGenerator::m_t.
endTitleHead() [1/2]
void LatexGenerator::endTitleHead (const QCString & fileName, const QCString & name) [virtual]
Implements OutputGenerator.
Definition at line 1316 of file latexgen.cpp.
{
  m_t << "}\n";
  if (!name.isEmpty())
  {
    m_t << "\\label{" << stripPath(fileName) << "}\\index{";
    m_t << latexEscapeLabelName(name);
    m_t << "@{";
    m_t << latexEscapeIndexChars(name);
    m_t << "}}\n";
  }
}
References OutputGenerator::fileName(), latexEscapeIndexChars(), latexEscapeLabelName(), OutputGenerator::m_t, setup::name, and stripPath().
endTitleHead() [2/2]
void LatexGenerator::endTitleHead (const QCString & , const QCString & name) [virtual]
Implements OutputGenerator.
endTypewriter() [1/2]
void LatexGenerator::endTypewriter () [inline], [virtual]
End a section of text displayed in typewriter style.
Implements BaseOutputDocInterface.
Definition at line 169 of file latexgen.h.
{ m_t << "}"; }
References OutputGenerator::m_t.
endTypewriter() [2/2]
void LatexGenerator::endTypewriter () [inline], [virtual]
End a section of text displayed in typewriter style.
Implements BaseOutputDocInterface.
Definition at line 169 of file latexgen.h.
{ m_t << "}"; }
References OutputGenerator::m_t.
exceptionEntry() [1/2]
void LatexGenerator::exceptionEntry (const QCString & prefix, bool closeBracket) [virtual]
Implements OutputGenerator.
Definition at line 1965 of file latexgen.cpp.
{
  if (!prefix.isEmpty())
  {
    m_t << " " << prefix << "(";
  }
  else if (closeBracket)
  {
    m_t << ")";
  }
  m_t << " ";
}
References QCString::isEmpty(), and OutputGenerator::m_t.
exceptionEntry() [2/2]
void LatexGenerator::exceptionEntry (const QCString & , bool) [virtual]
Implements OutputGenerator.
init() [1/2]
void LatexGenerator::init () [static]
Definition at line 497 of file latexgen.cpp.
{
  QCString dname = Config_getString(LATEX_OUTPUT);
  Dir d(dname.str());
  if (!d.exists() && !d.mkdir(dname.str()))
  {
    term("Could not create output directory %s\n",qPrint(dname));
  }
  if (!Config_getString(LATEX_HEADER).isEmpty())
  {
    g_header=fileToString(Config_getString(LATEX_HEADER));
    //printf("g_header='%s'\n",qPrint(g_header));
  }
  else
  {
    g_header = ResourceMgr::instance().getAsString("header.tex");
  }
  if (!Config_getString(LATEX_FOOTER).isEmpty())
  {
    g_footer=fileToString(Config_getString(LATEX_FOOTER));
    //printf("g_footer='%s'\n",qPrint(g_footer));
  }
  else
  {
    g_footer = ResourceMgr::instance().getAsString("footer.tex");
  }
  writeLatexMakefile();
  writeMakeBat();
  createSubDirs(d);
}
References Config_getString, createSubDirs(), Dir::exists(), fileToString(), g_footer, g_header, ResourceMgr::getAsString(), ResourceMgr::instance(), Dir::mkdir(), qPrint(), QCString::str(), term(), writeLatexMakefile(), and writeMakeBat().
Referenced by generateOutput().
init() [2/2]
static void LatexGenerator::init () [static]
insertMemberAlign() [1/2]
void LatexGenerator::insertMemberAlign (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 205 of file latexgen.h.
{}
insertMemberAlign() [2/2]
void LatexGenerator::insertMemberAlign (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 205 of file latexgen.h.
{}
insertMemberAlignLeft() [1/2]
void LatexGenerator::insertMemberAlignLeft (int , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 206 of file latexgen.h.
{}
insertMemberAlignLeft() [2/2]
void LatexGenerator::insertMemberAlignLeft (int , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 206 of file latexgen.h.
{}
lastIndexPage() [1/2]
void LatexGenerator::lastIndexPage () [virtual]
Implements OutputGenerator.
Definition at line 1763 of file latexgen.cpp.
{
}
lastIndexPage() [2/2]
void LatexGenerator::lastIndexPage () [virtual]
Implements OutputGenerator.
lineBreak() [1/2]
void LatexGenerator::lineBreak (const QCString & style = QCString()) [virtual]
Implements BaseOutputDocInterface.
Definition at line 2048 of file latexgen.cpp.
{
  if (m_insideTabbing)
  {
    m_t << "\\\\\n";
  }
  else
  {
    m_t << "\\newline\n";
  }
}
References m_insideTabbing, and OutputGenerator::m_t.
Referenced by endDescItem().
lineBreak() [2/2]
void LatexGenerator::lineBreak (const QCString & style = QCString()) [virtual]
Implements BaseOutputDocInterface.
newParagraph() [1/2]
void LatexGenerator::newParagraph ()
Definition at line 1119 of file latexgen.cpp.
{
  m_t << "\n" << "\n";
}
References OutputGenerator::m_t.
Referenced by startDotGraph().
newParagraph() [2/2]
void LatexGenerator::newParagraph ()
operator=() [1/2]
LatexGenerator & LatexGenerator::operator= (const LatexGenerator & og)
Definition at line 271 of file latexgen.cpp.
{
  OutputGenerator::operator=(og);
  return *this;
}
References OutputGenerator::operator=().
operator=() [2/2]
LatexGenerator & LatexGenerator::operator= (const LatexGenerator &)
setCurrentDoc() [1/2]
void LatexGenerator::setCurrentDoc (const Definition * , const QCString & , bool) [inline], [virtual]
Reimplemented from CodeOutputInterface.
Definition at line 330 of file latexgen.h.
{}
setCurrentDoc() [2/2]
void LatexGenerator::setCurrentDoc (const Definition * , const QCString & , bool) [inline], [virtual]
Reimplemented from CodeOutputInterface.
Definition at line 330 of file latexgen.h.
{}
startAnonTypeScope() [1/2]
void LatexGenerator::startAnonTypeScope (int indent) [virtual]
Implements OutputGenerator.
Definition at line 1610 of file latexgen.cpp.
{
  if (indent==0)
  {
    m_t << "\\begin{tabbing}\n";
    m_t << "xx\\=xx\\=xx\\=xx\\=xx\\=xx\\=xx\\=xx\\=xx\\=\\kill\n";
    m_insideTabbing=TRUE;
  }
  m_indent=indent;
}
References m_indent, m_insideTabbing, OutputGenerator::m_t, and TRUE.
startAnonTypeScope() [2/2]
void LatexGenerator::startAnonTypeScope (int) [virtual]
Implements OutputGenerator.
startBold() [1/2]
void LatexGenerator::startBold () [inline], [virtual]
Changes the text font to bold face. The bold section ends with endBold()
Implements BaseOutputDocInterface.
Definition at line 212 of file latexgen.h.
{ m_t << "{\\bfseries "; }
References OutputGenerator::m_t.
startBold() [2/2]
void LatexGenerator::startBold () [inline], [virtual]
Changes the text font to bold face. The bold section ends with endBold()
Implements BaseOutputDocInterface.
Definition at line 212 of file latexgen.h.
{ m_t << "{\\bfseries "; }
References OutputGenerator::m_t.
startCallGraph() [1/2]
void LatexGenerator::startCallGraph () [virtual]
Implements OutputGenerator.
Definition at line 1856 of file latexgen.cpp.
{
}
startCallGraph() [2/2]
void LatexGenerator::startCallGraph () [virtual]
Implements OutputGenerator.
startCenter() [1/2]
void LatexGenerator::startCenter () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 232 of file latexgen.h.
{ m_t << "\\begin{center}\n"; }
References OutputGenerator::m_t.
startCenter() [2/2]
void LatexGenerator::startCenter () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 232 of file latexgen.h.
{ m_t << "\\begin{center}\n"; }
References OutputGenerator::m_t.
startClassDiagram() [1/2]
void LatexGenerator::startClassDiagram () [virtual]
Implements OutputGenerator.
Definition at line 1597 of file latexgen.cpp.
{
  //if (Config_getBool(COMPACT_LATEX)) m_t << "\\doxysubsubsection"; else m_t << "\\doxysubsection";
  //m_t << "{";
}
startClassDiagram() [2/2]
void LatexGenerator::startClassDiagram () [virtual]
Implements OutputGenerator.
startCodeFragment() [1/2]
void LatexGenerator::startCodeFragment (const QCString & style) [inline], [virtual]
Starts a source code fragment. The fragment will be fed to the code parser (see code.h) for syntax highlighting and cross-referencing. The fragment ends by a call to endCodeFragment()
Parameters
style The kind of code fragment.
Implements CodeOutputInterface.
Definition at line 118 of file latexgen.h.
    { m_codeGen.startCodeFragment(style); }
References m_codeGen, LatexCodeGenerator::startCodeFragment(), and style.
startCodeFragment() [2/2]
void LatexGenerator::startCodeFragment (const QCString & style) [inline], [virtual]
Starts a source code fragment. The fragment will be fed to the code parser (see code.h) for syntax highlighting and cross-referencing. The fragment ends by a call to endCodeFragment()
Parameters
style The kind of code fragment.
Implements CodeOutputInterface.
Definition at line 118 of file latexgen.h.
    { m_codeGen.startCodeFragment(style); }
References m_codeGen, LatexCodeGenerator::startCodeFragment(), and style.
startCodeLine() [1/2]
void LatexGenerator::startCodeLine (bool hasLineNumbers) [inline], [virtual]
Implements CodeOutputInterface.
Definition at line 108 of file latexgen.h.
    { m_codeGen.startCodeLine(hasLineNumbers); }
References m_codeGen, and LatexCodeGenerator::startCodeLine().
startCodeLine() [2/2]
void LatexGenerator::startCodeLine (bool hasLineNumbers) [inline], [virtual]
Implements CodeOutputInterface.
Definition at line 108 of file latexgen.h.
    { m_codeGen.startCodeLine(hasLineNumbers); }
References m_codeGen, and LatexCodeGenerator::startCodeLine().
startCompoundTemplateParams() [1/2]
void LatexGenerator::startCompoundTemplateParams () [inline], [virtual]
Implements OutputGenerator.
Definition at line 195 of file latexgen.h.
{ startSubsubsection(); }
References startSubsubsection().
startCompoundTemplateParams() [2/2]
void LatexGenerator::startCompoundTemplateParams () [inline], [virtual]
Implements OutputGenerator.
Definition at line 195 of file latexgen.h.
{ startSubsubsection(); }
References startSubsubsection().
startConstraintDocs() [1/2]
void LatexGenerator::startConstraintDocs () [virtual]
Implements OutputGenerator.
Definition at line 2017 of file latexgen.cpp.
{
}
startConstraintDocs() [2/2]
void LatexGenerator::startConstraintDocs () [virtual]
Implements OutputGenerator.
startConstraintList() [1/2]
void LatexGenerator::startConstraintList (const QCString & header) [virtual]
Implements OutputGenerator.
Definition at line 1990 of file latexgen.cpp.
{
  m_t << "\\begin{Desc}\n\\item[";
  docify(header);
  m_t << "]";
  m_t << "\\begin{description}\n";
}
References docify(), and OutputGenerator::m_t.
startConstraintList() [2/2]
void LatexGenerator::startConstraintList (const QCString &) [virtual]
Implements OutputGenerator.
startConstraintParam() [1/2]
void LatexGenerator::startConstraintParam () [virtual]
Implements OutputGenerator.
Definition at line 1998 of file latexgen.cpp.
{
  m_t << "\\item[{\\em ";
}
References OutputGenerator::m_t.
startConstraintParam() [2/2]
void LatexGenerator::startConstraintParam () [virtual]
Implements OutputGenerator.
startConstraintType() [1/2]
void LatexGenerator::startConstraintType () [virtual]
Implements OutputGenerator.
Definition at line 2007 of file latexgen.cpp.
{
  m_t << "} : {\\em ";
}
References OutputGenerator::m_t.
startConstraintType() [2/2]
void LatexGenerator::startConstraintType () [virtual]
Implements OutputGenerator.
startContents() [1/2]
void LatexGenerator::startContents () [inline], [virtual]
Implements OutputGenerator.
Definition at line 267 of file latexgen.h.
{}
startContents() [2/2]
void LatexGenerator::startContents () [inline], [virtual]
Implements OutputGenerator.
Definition at line 267 of file latexgen.h.
{}
startDescForItem() [1/2]
void LatexGenerator::startDescForItem () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 248 of file latexgen.h.
{ m_t << "\\par\n"; }
References OutputGenerator::m_t.
startDescForItem() [2/2]
void LatexGenerator::startDescForItem () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 248 of file latexgen.h.
{ m_t << "\\par\n"; }
References OutputGenerator::m_t.
startDescItem() [1/2]
void LatexGenerator::startDescItem () [virtual]
Starts an item of a description list: e.g. <dt> in HTML.
Implements BaseOutputDocInterface.
Definition at line 1885 of file latexgen.cpp.
{
  m_firstDescItem=TRUE;
  m_t << "\\item[";
}
References m_firstDescItem, OutputGenerator::m_t, and TRUE.
startDescItem() [2/2]
void LatexGenerator::startDescItem () [virtual]
Starts an item of a description list: e.g. <dt> in HTML.
Implements BaseOutputDocInterface.
startDescList() [1/2]
void LatexGenerator::startDescList (SectionTypes) [inline]
Definition at line 242 of file latexgen.h.
{ m_t << "\\begin{Desc}\n\\item["; }
References OutputGenerator::m_t.
startDescList() [2/2]
void LatexGenerator::startDescList (SectionTypes) [inline]
Definition at line 242 of file latexgen.h.
{ m_t << "\\begin{Desc}\n\\item["; }
References OutputGenerator::m_t.
startDescription() [1/2]
void LatexGenerator::startDescription () [virtual]
Starts a description list: e.g. <dl> in HTML Items are surrounded by startDescItem() and endDescItem()
Implements BaseOutputDocInterface.
Definition at line 1874 of file latexgen.cpp.
{
  m_t << "\\begin{description}\n";
}
References OutputGenerator::m_t.
startDescription() [2/2]
void LatexGenerator::startDescription () [virtual]
Starts a description list: e.g. <dl> in HTML Items are surrounded by startDescItem() and endDescItem()
Implements BaseOutputDocInterface.
startDescTable() [1/2]
void LatexGenerator::startDescTable (const QCString & title) [virtual]
Implements BaseOutputDocInterface.
Definition at line 1721 of file latexgen.cpp.
{
  m_codeGen.incUsedTableLevel();
  m_t << "\\begin{DoxyEnumFields}{" << title << "}\n";
}
References LatexCodeGenerator::incUsedTableLevel(), m_codeGen, and OutputGenerator::m_t.
startDescTable() [2/2]
void LatexGenerator::startDescTable (const QCString & title) [virtual]
Implements BaseOutputDocInterface.
startDescTableData() [1/2]
void LatexGenerator::startDescTableData () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1753 of file latexgen.cpp.
{
  m_t << "&";
}
References OutputGenerator::m_t.
startDescTableData() [2/2]
void LatexGenerator::startDescTableData () [virtual]
Implements BaseOutputDocInterface.
startDescTableRow() [1/2]
void LatexGenerator::startDescTableRow () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1733 of file latexgen.cpp.
{
  // this is needed to prevent the \hypertarget, \label, and \index commands from messing up
  // the row height (based on http://tex.stackexchange.com/a/186102)
  m_t << "\\raisebox{\\heightof{T}}[0pt][0pt]{";
}
References OutputGenerator::m_t.
startDescTableRow() [2/2]
void LatexGenerator::startDescTableRow () [virtual]
Implements BaseOutputDocInterface.
startDescTableTitle() [1/2]
void LatexGenerator::startDescTableTitle () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1744 of file latexgen.cpp.
{
  m_t << "}";
}
References OutputGenerator::m_t.
startDescTableTitle() [2/2]
void LatexGenerator::startDescTableTitle () [virtual]
Implements BaseOutputDocInterface.
startDirDepGraph() [1/2]
void LatexGenerator::startDirDepGraph () [virtual]
Implements OutputGenerator.
Definition at line 1865 of file latexgen.cpp.
{
}
startDirDepGraph() [2/2]
void LatexGenerator::startDirDepGraph () [virtual]
Implements OutputGenerator.
startDotGraph() [1/2]
void LatexGenerator::startDotGraph () [virtual]
Implements OutputGenerator.
Definition at line 1828 of file latexgen.cpp.
{
  newParagraph();
}
References newParagraph().
startDotGraph() [2/2]
void LatexGenerator::startDotGraph () [virtual]
Implements OutputGenerator.
startDoxyAnchor() [1/2]
void LatexGenerator::startDoxyAnchor (const QCString & fName, const QCString & , const QCString & anchor, const QCString & , const QCString &) [virtual]
Implements OutputGenerator.
Definition at line 1464 of file latexgen.cpp.
{
  bool pdfHyperlinks = Config_getBool(PDF_HYPERLINKS);
  bool usePDFLatex = Config_getBool(USE_PDFLATEX);
  m_t << "\\mbox{";
  if (usePDFLatex && pdfHyperlinks)
  {
    m_t << "\\Hypertarget{";
    if (!fName.isEmpty()) m_t << stripPath(fName);
    if (!anchor.isEmpty()) m_t << "_" << anchor;
    m_t << "}";
  }
  m_t << "\\label{";
  if (!fName.isEmpty()) m_t << stripPath(fName);
  if (!anchor.isEmpty()) m_t << "_" << anchor;
  m_t << "}} \n";
}
References Config_getBool, QCString::isEmpty(), OutputGenerator::m_t, and stripPath().
startDoxyAnchor() [2/2]
void LatexGenerator::startDoxyAnchor (const QCString & , const QCString & , const QCString & , const QCString & , const QCString &) [virtual]
Implements OutputGenerator.
startEmphasis() [1/2]
void LatexGenerator::startEmphasis () [inline], [virtual]
Changes the text font to italic. The italic section ends with endEmphasis()
Implements BaseOutputDocInterface.
Definition at line 210 of file latexgen.h.
{ m_t << "{\\em "; }
References OutputGenerator::m_t.
startEmphasis() [2/2]
void LatexGenerator::startEmphasis () [inline], [virtual]
Changes the text font to italic. The italic section ends with endEmphasis()
Implements BaseOutputDocInterface.
Definition at line 210 of file latexgen.h.
{ m_t << "{\\em "; }
References OutputGenerator::m_t.
startExamples() [1/2]
void LatexGenerator::startExamples () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1904 of file latexgen.cpp.
{
  m_t << "\\begin{Desc}\n\\item[";
  docify(theTranslator->trExamples());
  m_t << "]";
}
References docify(), OutputGenerator::m_t, theTranslator, and Translator::trExamples().
startExamples() [2/2]
void LatexGenerator::startExamples () [virtual]
Implements BaseOutputDocInterface.
startFile() [1/2]
void LatexGenerator::startFile (const QCString & name, const QCString & manName, const QCString & title, int id) [virtual]
Implements OutputGenerator.
Definition at line 561 of file latexgen.cpp.
{
#if 0
  setEncoding(Config_getString(LATEX_OUTPUT_ENCODING));
#endif
  QCString fileName=name;
  m_relPath = relativePathToRoot(fileName);
  if (!fileName.endsWith(".tex") && !fileName.endsWith(".sty")) fileName+=".tex";
  startPlainFile(fileName);
  m_codeGen.setRelativePath(m_relPath);
  m_codeGen.setSourceFileName(stripPath(fileName));
}
References Config_getString, QCString::endsWith(), OutputGenerator::fileName(), m_codeGen, m_relPath, setup::name, relativePathToRoot(), LatexCodeGenerator::setRelativePath(), LatexCodeGenerator::setSourceFileName(), OutputGenerator::startPlainFile(), and stripPath().
startFile() [2/2]
void LatexGenerator::startFile (const QCString & name, const QCString & manName, const QCString & title, int id) [virtual]
Implements OutputGenerator.
startFontClass() [1/2]
void LatexGenerator::startFontClass (const QCString & clsName) [inline], [virtual]
Starts a block with a certain meaning. Used for syntax highlighting, which elements of the same type are rendered using the same 'font class'.
Parameters
clsName The category name.
Implements CodeOutputInterface.
Definition at line 112 of file latexgen.h.
    { m_codeGen.startFontClass(s); }
References m_codeGen, s, and LatexCodeGenerator::startFontClass().
startFontClass() [2/2]
void LatexGenerator::startFontClass (const QCString & clsName) [inline], [virtual]
Starts a block with a certain meaning. Used for syntax highlighting, which elements of the same type are rendered using the same 'font class'.
Parameters
clsName The category name.
Implements CodeOutputInterface.
Definition at line 112 of file latexgen.h.
    { m_codeGen.startFontClass(s); }
References m_codeGen, s, and LatexCodeGenerator::startFontClass().
startGroupCollaboration() [1/2]
void LatexGenerator::startGroupCollaboration () [virtual]
Implements OutputGenerator.
Definition at line 1847 of file latexgen.cpp.
{
}
startGroupCollaboration() [2/2]
void LatexGenerator::startGroupCollaboration () [virtual]
Implements OutputGenerator.
startGroupHeader() [1/2]
void LatexGenerator::startGroupHeader (int extraIndentLevel) [virtual]
Implements OutputGenerator.
Definition at line 1341 of file latexgen.cpp.
{
  if (Config_getBool(COMPACT_LATEX))
  {
    extraIndentLevel++;
  }
  if (extraIndentLevel==3)
  {
    m_t << "\\doxysubparagraph*{";
  }
  else if (extraIndentLevel==2)
  {
    m_t << "\\doxyparagraph{";
  }
  else if (extraIndentLevel==1)
  {
    m_t << "\\doxysubsubsection{";
  }
  else // extraIndentLevel==0
  {
    m_t << "\\doxysubsection{";
  }
  m_disableLinks=TRUE;
}
References Config_getBool, m_disableLinks, OutputGenerator::m_t, and TRUE.
startGroupHeader() [2/2]
void LatexGenerator::startGroupHeader (int) [virtual]
Implements OutputGenerator.
startHeaderSection() [1/2]
void LatexGenerator::startHeaderSection () [inline], [virtual]
Implements OutputGenerator.
Definition at line 177 of file latexgen.h.
{}
startHeaderSection() [2/2]
void LatexGenerator::startHeaderSection () [inline], [virtual]
Implements OutputGenerator.
Definition at line 177 of file latexgen.h.
{}
startHtmlLink() [1/2]
void LatexGenerator::startHtmlLink (const QCString & url) [virtual]
Starts a (link to an) URL found in the documentation.
Parameters
url The URL to link to.
Implements BaseOutputDocInterface.
Definition at line 1164 of file latexgen.cpp.
{
  if (Config_getBool(PDF_HYPERLINKS))
  {
    m_t << "\\href{";
    m_t << latexFilterURL(url);
    m_t << "}";
  }
  m_t << "{\\texttt{ ";
}
References Config_getBool, latexFilterURL(), OutputGenerator::m_t, and setup::url.
startHtmlLink() [2/2]
void LatexGenerator::startHtmlLink (const QCString & url) [virtual]
Starts a (link to an) URL found in the documentation.
Parameters
url The URL to link to.
Implements BaseOutputDocInterface.
startInclDepGraph() [1/2]
void LatexGenerator::startInclDepGraph () [virtual]
Implements OutputGenerator.
Definition at line 1838 of file latexgen.cpp.
{
}
startInclDepGraph() [2/2]
void LatexGenerator::startInclDepGraph () [virtual]
Implements OutputGenerator.
startIndent() [1/2]
void LatexGenerator::startIndent () [inline], [virtual]
Implements OutputGenerator.
Definition at line 253 of file latexgen.h.
{}
startIndent() [2/2]
void LatexGenerator::startIndent () [inline], [virtual]
Implements OutputGenerator.
Definition at line 253 of file latexgen.h.
{}
startIndexItem() [1/2]
void LatexGenerator::startIndexItem (const QCString & ref, const QCString & file) [virtual]
Implements OutputGenerator.
Definition at line 1139 of file latexgen.cpp.
{
  m_t << "\\item ";
  if (ref.isEmpty() && !fn.isEmpty())
  {
    m_t << "\\contentsline{section}{";
  }
}
References QCString::isEmpty(), and OutputGenerator::m_t.
startIndexItem() [2/2]
void LatexGenerator::startIndexItem (const QCString & ref, const QCString & file) [virtual]
Implements OutputGenerator.
startIndexKey() [1/2]
void LatexGenerator::startIndexKey () [virtual]
Implements OutputGenerator.
Definition at line 1207 of file latexgen.cpp.
{
  m_t << "\\item\\contentsline{section}{";
}
References OutputGenerator::m_t.
startIndexKey() [2/2]
void LatexGenerator::startIndexKey () [virtual]
Implements OutputGenerator.
startIndexList() [1/2]
void LatexGenerator::startIndexList () [inline], [virtual]
Implements OutputGenerator.
Definition at line 150 of file latexgen.h.
{ m_t << "\\begin{DoxyCompactList}\n"; }
References OutputGenerator::m_t.
startIndexList() [2/2]
void LatexGenerator::startIndexList () [inline], [virtual]
Implements OutputGenerator.
Definition at line 150 of file latexgen.h.
{ m_t << "\\begin{DoxyCompactList}\n"; }
References OutputGenerator::m_t.
startIndexListItem() [1/2]
void LatexGenerator::startIndexListItem () [inline], [virtual]
Implements OutputGenerator.
Definition at line 148 of file latexgen.h.
{}
startIndexListItem() [2/2]
void LatexGenerator::startIndexListItem () [inline], [virtual]
Implements OutputGenerator.
Definition at line 148 of file latexgen.h.
{}
startIndexSection() [1/2]
void LatexGenerator::startIndexSection (IndexSections is) [virtual]
Implements OutputGenerator.
Definition at line 738 of file latexgen.cpp.
{
  bool compactLatex = Config_getBool(COMPACT_LATEX);
  switch (is)
  {
    case isTitlePageStart:
      m_t << substituteLatexKeywords(g_header,convertToLaTeX(Config_getString(PROJECT_NAME)));
      break;
    case isTitlePageAuthor:
      break;
    case isMainPage:
      if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
      m_t << "{"; //Introduction}\n"
      break;
    case isModuleIndex:
      if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
      m_t << "{"; //Module Index}\n"
      break;
    case isDirIndex:
      if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
      m_t << "{"; //Directory Index}\n"
      break;
    case isNamespaceIndex:
      if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
      m_t << "{"; //Namespace Index}\n"
      break;
    case isConceptIndex:
      if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
      m_t << "{"; //Concept Index}\n"
      break;
    case isClassHierarchyIndex:
      if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
      m_t << "{"; //Hierarchical Index}\n"
      break;
    case isCompoundIndex:
      if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
      m_t << "{"; //Annotated Compound Index}\n"
      break;
    case isFileIndex:
      if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
      m_t << "{"; //Annotated File Index}\n"
      break;
    case isPageIndex:
      if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
      m_t << "{"; //Annotated Page Index}\n"
      break;
    case isModuleDocumentation:
      {
        for (const auto &gd : *Doxygen::groupLinkedMap)
        {
          if (!gd->isReference())
          {
            if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
            m_t << "{"; //Module Documentation}\n";
            break;
          }
        }
      }
      break;
    case isDirDocumentation:
      {
        for (const auto &dd : *Doxygen::dirLinkedMap)
        {
          if (dd->isLinkableInProject())
          {
            if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
            m_t << "{"; //Module Documentation}\n";
            break;
          }
        }
      }
      break;
    case isNamespaceDocumentation:
      {
        for (const auto &nd : *Doxygen::namespaceLinkedMap)
        {
          if (nd->isLinkableInProject() && !nd->isAlias())
          {
            if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
            m_t << "{"; // Namespace Documentation}\n":
            break;
          }
        }
      }
      break;
    case isConceptDocumentation:
      {
        for (const auto &cd : *Doxygen::conceptLinkedMap)
        {
          if (cd->isLinkableInProject() && !cd->isAlias())
          {
            if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
            m_t << "{"; // Concept Documentation}\n":
            break;
          }
        }
      }
      break;
    case isClassDocumentation:
      {
        for (const auto &cd : *Doxygen::classLinkedMap)
        {
          if (cd->isLinkableInProject() &&
              cd->templateMaster()==0 &&
              !cd->isEmbeddedInOuterScope() &&
              !cd->isAlias()
             )
          {
            if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
            m_t << "{"; //Compound Documentation}\n";
            break;
          }
        }
      }
      break;
    case isFileDocumentation:
      {
        bool isFirst=TRUE;
        for (const auto &fn : *Doxygen::inputNameLinkedMap)
        {
          for (const auto &fd : *fn)
          {
            if (fd->isLinkableInProject() || fd->generateSourceFile())
            {
              if (isFirst)
              {
                if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
                m_t << "{"; //File Documentation}\n";
                isFirst=FALSE;
                break;
              }
            }
          }
        }
      }
      break;
    case isExampleDocumentation:
      {
        if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
        m_t << "{"; //Example Documentation}\n";
      }
      break;
    case isPageDocumentation:
      {
        if (compactLatex) m_t << "\\doxysection"; else m_t << "\\chapter";
        m_t << "{"; //Page Documentation}\n";
      }
      break;
    case isPageDocumentation2:
      break;
    case isEndIndex:
      break;
  }
}
References Doxygen::classLinkedMap, Doxygen::conceptLinkedMap, Config_getBool, Config_getString, convertToLaTeX(), Doxygen::dirLinkedMap, FALSE, g_header, Doxygen::groupLinkedMap, Doxygen::inputNameLinkedMap, isClassDocumentation, isClassHierarchyIndex, isCompoundIndex, isConceptDocumentation, isConceptIndex, isDirDocumentation, isDirIndex, isEndIndex, isExampleDocumentation, isFileDocumentation, isFileIndex, isMainPage, isModuleDocumentation, isModuleIndex, isNamespaceDocumentation, isNamespaceIndex, isPageDocumentation, isPageDocumentation2, isPageIndex, isTitlePageAuthor, isTitlePageStart, OutputGenerator::m_t, Doxygen::namespaceLinkedMap, substituteLatexKeywords(), and TRUE.
startIndexSection() [2/2]
void LatexGenerator::startIndexSection (IndexSections) [virtual]
Implements OutputGenerator.
startIndexValue() [1/2]
void LatexGenerator::startIndexValue (bool hasBrief) [virtual]
Implements OutputGenerator.
Definition at line 1216 of file latexgen.cpp.
{
  m_t << " ";
  if (hasBrief) m_t << "\\\\*";
}
References OutputGenerator::m_t.
startIndexValue() [2/2]
void LatexGenerator::startIndexValue (bool) [virtual]
Implements OutputGenerator.
startInlineHeader() [1/2]
void LatexGenerator::startInlineHeader () [virtual]
Implements OutputGenerator.
Definition at line 2031 of file latexgen.cpp.
{
  if (Config_getBool(COMPACT_LATEX))
  {
    m_t << "\\doxyparagraph*{";
  }
  else
  {
    m_t << "\\doxysubsubsection*{";
  }
}
References Config_getBool, and OutputGenerator::m_t.
startInlineHeader() [2/2]
void LatexGenerator::startInlineHeader () [virtual]
Implements OutputGenerator.
startInlineMemberDoc() [1/2]
void LatexGenerator::startInlineMemberDoc () [virtual]
Implements OutputGenerator.
Definition at line 2111 of file latexgen.cpp.
{
}
startInlineMemberDoc() [2/2]
void LatexGenerator::startInlineMemberDoc () [virtual]
Implements OutputGenerator.
startInlineMemberName() [1/2]
void LatexGenerator::startInlineMemberName () [virtual]
Implements OutputGenerator.
Definition at line 2100 of file latexgen.cpp.
{
  m_insideTabbing = TRUE; // to prevent \+ from causing unwanted breaks
}
References m_insideTabbing, and TRUE.
startInlineMemberName() [2/2]
void LatexGenerator::startInlineMemberName () [virtual]
Implements OutputGenerator.
startInlineMemberType() [1/2]
void LatexGenerator::startInlineMemberType () [virtual]
Implements OutputGenerator.
Definition at line 2089 of file latexgen.cpp.
{
  m_insideTabbing = TRUE; // to prevent \+ from causing unwanted breaks
}
References m_insideTabbing, and TRUE.
startInlineMemberType() [2/2]
void LatexGenerator::startInlineMemberType () [virtual]
Implements OutputGenerator.
startItemList() [1/2]
void LatexGenerator::startItemList () [inline], [virtual]
Start of a bullet list: e.g. <ul> in html. startItemListItem() is Used for the bullet items.
Implements BaseOutputDocInterface.
Definition at line 156 of file latexgen.h.
{ m_t << "\\begin{DoxyCompactItemize}\n"; }
References OutputGenerator::m_t.
startItemList() [2/2]
void LatexGenerator::startItemList () [inline], [virtual]
Start of a bullet list: e.g. <ul> in html. startItemListItem() is Used for the bullet items.
Implements BaseOutputDocInterface.
Definition at line 156 of file latexgen.h.
{ m_t << "\\begin{DoxyCompactItemize}\n"; }
References OutputGenerator::m_t.
startItemListItem() [1/2]
void LatexGenerator::startItemListItem () [inline], [virtual]
Writes a list item for a bullet or enumerated list: e.g. <li> in html
Implements BaseOutputDocInterface.
Definition at line 172 of file latexgen.h.
{ m_t << "\\item \n"; }
References OutputGenerator::m_t.
startItemListItem() [2/2]
void LatexGenerator::startItemListItem () [inline], [virtual]
Writes a list item for a bullet or enumerated list: e.g. <li> in html
Implements BaseOutputDocInterface.
Definition at line 172 of file latexgen.h.
{ m_t << "\\item \n"; }
References OutputGenerator::m_t.
startLabels() [1/2]
void LatexGenerator::startLabels () [virtual]
Implements OutputGenerator.
Definition at line 2120 of file latexgen.cpp.
{
  m_t << "\\hspace{0.3cm}";
}
References OutputGenerator::m_t.
startLabels() [2/2]
void LatexGenerator::startLabels () [virtual]
Implements OutputGenerator.
startMemberDeclaration() [1/2]
void LatexGenerator::startMemberDeclaration () [inline], [virtual]
Implements OutputGenerator.
Definition at line 238 of file latexgen.h.
{}
startMemberDeclaration() [2/2]
void LatexGenerator::startMemberDeclaration () [inline], [virtual]
Implements OutputGenerator.
Definition at line 238 of file latexgen.h.
{}
startMemberDescription() [1/2]
void LatexGenerator::startMemberDescription (const QCString & , const QCString & , bool) [virtual]
Implements OutputGenerator.
Definition at line 1667 of file latexgen.cpp.
{
  if (!m_insideTabbing)
  {
    m_t << "\\begin{DoxyCompactList}\\small\\item\\em ";
  }
  else
  {
    for (int i=0;i<m_indent+2;i++) m_t << "\\>";
    m_t << "{\\em ";
  }
}
References m_indent, m_insideTabbing, and OutputGenerator::m_t.
startMemberDescription() [2/2]
void LatexGenerator::startMemberDescription (const QCString & , const QCString & , bool) [virtual]
Implements OutputGenerator.
startMemberDoc() [1/2]
void LatexGenerator::startMemberDoc (const QCString & clname, const QCString & memname, const QCString & , const QCString & title, int memCount, int memTotal, bool showInline) [virtual]
Implements OutputGenerator.
Definition at line 1392 of file latexgen.cpp.
{
  if (!memname.isEmpty() && memname[0]!='@')
  {
    m_t << "\\index{";
    if (!clname.isEmpty())
    {
      m_t << latexEscapeLabelName(clname);
      m_t << "@{";
      m_t << latexEscapeIndexChars(clname);
      m_t << "}!";
    }
    m_t << latexEscapeLabelName(memname);
    m_t << "@{";
    m_t << latexEscapeIndexChars(memname);
    m_t << "}}\n";
    m_t << "\\index{";
    m_t << latexEscapeLabelName(memname);
    m_t << "@{";
    m_t << latexEscapeIndexChars(memname);
    m_t << "}";
    if (!clname.isEmpty())
    {
      m_t << "!";
      m_t << latexEscapeLabelName(clname);
      m_t << "@{";
      m_t << latexEscapeIndexChars(clname);
      m_t << "}";
    }
    m_t << "}\n";
  }
  static const char *levelLab[] = { "doxysubsubsection","doxyparagraph","doxysubparagraph", "doxysubparagraph" };
  bool compactLatex = Config_getBool(COMPACT_LATEX);
  bool pdfHyperlinks = Config_getBool(PDF_HYPERLINKS);
  int level=0;
  if (showInline) level+=2;
  if (compactLatex) level++;
  m_t << "\\" << levelLab[level];
  m_t << "{";
  if (pdfHyperlinks)
  {
    m_t << "\\texorpdfstring{";
  }
  m_t << latexEscapeIndexChars(title);
  if (pdfHyperlinks)
  {
    m_t << "}{" << latexEscapePDFString(title) << "}";
  }
  if (memTotal>1)
  {
    m_t << "\\hspace{0.1cm}{\\footnotesize\\ttfamily [" << memCount << "/" << memTotal << "]}";
  }
  m_t << "}";
  m_t << "\n{\\footnotesize\\ttfamily ";
  //m_disableLinks=TRUE;
}
References Config_getBool, QCString::isEmpty(), latexEscapeIndexChars(), latexEscapeLabelName(), latexEscapePDFString(), level, and OutputGenerator::m_t.
startMemberDoc() [2/2]
void LatexGenerator::startMemberDoc (const QCString & , const QCString & , const QCString & , const QCString & , int , int , bool) [virtual]
Implements OutputGenerator.
startMemberDocList() [1/2]
void LatexGenerator::startMemberDocList () [inline], [virtual]
Implements OutputGenerator.
Definition at line 183 of file latexgen.h.
{}
startMemberDocList() [2/2]
void LatexGenerator::startMemberDocList () [inline], [virtual]
Implements OutputGenerator.
Definition at line 183 of file latexgen.h.
{}
startMemberDocName() [1/2]
void LatexGenerator::startMemberDocName (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 298 of file latexgen.h.
{}
startMemberDocName() [2/2]
void LatexGenerator::startMemberDocName (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 298 of file latexgen.h.
{}
startMemberDocPrefixItem() [1/2]
void LatexGenerator::startMemberDocPrefixItem () [inline], [virtual]
Implements OutputGenerator.
Definition at line 296 of file latexgen.h.
{}
startMemberDocPrefixItem() [2/2]
void LatexGenerator::startMemberDocPrefixItem () [inline], [virtual]
Implements OutputGenerator.
Definition at line 296 of file latexgen.h.
{}
startMemberDocSimple() [1/2]
void LatexGenerator::startMemberDocSimple (bool isEnum) [virtual]
Implements OutputGenerator.
Definition at line 2060 of file latexgen.cpp.
{
  m_codeGen.incUsedTableLevel();
  if (isEnum)
  {
    m_t << "\\begin{DoxyEnumFields}{";
    docify(theTranslator->trEnumerationValues());
  }
  else
  {
    m_t << "\\begin{DoxyFields}{";
    docify(theTranslator->trCompoundMembers());
  }
  m_t << "}\n";
}
References docify(), LatexCodeGenerator::incUsedTableLevel(), m_codeGen, OutputGenerator::m_t, theTranslator, Translator::trCompoundMembers(), and Translator::trEnumerationValues().
startMemberDocSimple() [2/2]
void LatexGenerator::startMemberDocSimple (bool) [virtual]
Implements OutputGenerator.
startMemberGroup() [1/2]
void LatexGenerator::startMemberGroup () [virtual]
Implements OutputGenerator.
Definition at line 1818 of file latexgen.cpp.
{
}
startMemberGroup() [2/2]
void LatexGenerator::startMemberGroup () [virtual]
Implements OutputGenerator.
startMemberGroupDocs() [1/2]
void LatexGenerator::startMemberGroupDocs () [virtual]
Implements OutputGenerator.
Definition at line 1808 of file latexgen.cpp.
{
  m_t << "{\\em ";
}
References OutputGenerator::m_t.
startMemberGroupDocs() [2/2]
void LatexGenerator::startMemberGroupDocs () [virtual]
Implements OutputGenerator.
startMemberGroupHeader() [1/2]
void LatexGenerator::startMemberGroupHeader (bool hasHeader) [virtual]
Implements OutputGenerator.
Definition at line 1786 of file latexgen.cpp.
{
  if (hasHeader) m_t << "\\begin{Indent}";
  m_t << "\\textbf{ ";
  // changed back to rev 756 due to bug 660501
  //if (Config_getBool(COMPACT_LATEX))
  //{
  // m_t << "\\doxysubparagraph*{";
  //}
  //else
  //{
  // m_t << "\\doxyparagraph*{";
  //}
}
References OutputGenerator::m_t.
startMemberGroupHeader() [2/2]
void LatexGenerator::startMemberGroupHeader (bool) [virtual]
Implements OutputGenerator.
startMemberHeader() [1/2]
void LatexGenerator::startMemberHeader (const QCString & , int) [virtual]
Implements OutputGenerator.
Definition at line 1373 of file latexgen.cpp.
{
  if (Config_getBool(COMPACT_LATEX))
  {
    m_t << "\\doxysubsubsection*{";
  }
  else
  {
    m_t << "\\doxysubsection*{";
  }
  m_disableLinks=TRUE;
}
References Config_getBool, m_disableLinks, OutputGenerator::m_t, and TRUE.
startMemberHeader() [2/2]
void LatexGenerator::startMemberHeader (const QCString & , int) [virtual]
Implements OutputGenerator.
startMemberItem() [1/2]
void LatexGenerator::startMemberItem (const QCString & , int annoType, const QCString &) [virtual]
Implements OutputGenerator.
Definition at line 1647 of file latexgen.cpp.
{
  //printf("LatexGenerator::startMemberItem(%d)\n",annType);
  if (!m_insideTabbing)
  {
    m_t << "\\item \n";
    templateMemberItem = (annoType == 3);
  }
}
References m_insideTabbing, OutputGenerator::m_t, and templateMemberItem.
startMemberItem() [2/2]
void LatexGenerator::startMemberItem (const QCString & , int , const QCString &) [virtual]
Implements OutputGenerator.
startMemberList() [1/2]
void LatexGenerator::startMemberList () [virtual]
Implements OutputGenerator.
Definition at line 1768 of file latexgen.cpp.
{
  if (!m_insideTabbing)
  {
    m_t << "\\begin{DoxyCompactItemize}\n";
  }
}
References m_insideTabbing, and OutputGenerator::m_t.
startMemberList() [2/2]
void LatexGenerator::startMemberList () [virtual]
Implements OutputGenerator.
startMemberSections() [1/2]
void LatexGenerator::startMemberSections () [inline], [virtual]
Implements OutputGenerator.
Definition at line 175 of file latexgen.h.
{}
startMemberSections() [2/2]
void LatexGenerator::startMemberSections () [inline], [virtual]
Implements OutputGenerator.
Definition at line 175 of file latexgen.h.
{}
startMemberSubtitle() [1/2]
void LatexGenerator::startMemberSubtitle () [inline], [virtual]
Implements OutputGenerator.
Definition at line 181 of file latexgen.h.
{}
startMemberSubtitle() [2/2]
void LatexGenerator::startMemberSubtitle () [inline], [virtual]
Implements OutputGenerator.
Definition at line 181 of file latexgen.h.
{}
startMemberTemplateParams() [1/2]
void LatexGenerator::startMemberTemplateParams () [virtual]
Implements OutputGenerator.
Definition at line 1631 of file latexgen.cpp.
{
  if (templateMemberItem)
  {
    m_t << "{\\footnotesize ";
  }
}
References OutputGenerator::m_t, and templateMemberItem.
startMemberTemplateParams() [2/2]
void LatexGenerator::startMemberTemplateParams () [virtual]
Implements OutputGenerator.
startPageRef() [1/2]
void LatexGenerator::startPageRef () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1284 of file latexgen.cpp.
{
  m_t << " \\doxyref{}{";
}
References OutputGenerator::m_t.
startPageRef() [2/2]
void LatexGenerator::startPageRef () [virtual]
Implements BaseOutputDocInterface.
startParagraph() [1/2]
void LatexGenerator::startParagraph (const QCString & classDef) [virtual]
Starts a new paragraph
Starts a new paragraph
Implements BaseOutputDocInterface.
Definition at line 1124 of file latexgen.cpp.
{
  m_t << "\n" << "\n";
}
References OutputGenerator::m_t.
startParagraph() [2/2]
void LatexGenerator::startParagraph (const QCString & classDef) [virtual]
Starts a new paragraph
Starts a new paragraph
Implements BaseOutputDocInterface.
startParameterList() [1/2]
void LatexGenerator::startParameterList (bool openBracket) [virtual]
Implements OutputGenerator.
Definition at line 1928 of file latexgen.cpp.
{
  /* start of ParameterType ParameterName list */
  if (openBracket) m_t << "(";
  m_t << "\\begin{DoxyParamCaption}";
}
References OutputGenerator::m_t.
startParameterList() [2/2]
void LatexGenerator::startParameterList (bool) [virtual]
Implements OutputGenerator.
startParameterName() [1/2]
void LatexGenerator::startParameterName (bool) [virtual]
Implements OutputGenerator.
Definition at line 1950 of file latexgen.cpp.
{
  m_t << "{";
}
References OutputGenerator::m_t.
startParameterName() [2/2]
void LatexGenerator::startParameterName (bool) [virtual]
Implements OutputGenerator.
startParameterType() [1/2]
void LatexGenerator::startParameterType (bool first, const QCString & key) [virtual]
Implements OutputGenerator.
Definition at line 1939 of file latexgen.cpp.
{
  m_t << "\\item[{";
  if (!first && !key.isEmpty()) docify(key);
}
References docify(), QCString::isEmpty(), and OutputGenerator::m_t.
startParameterType() [2/2]
void LatexGenerator::startParameterType (bool , const QCString &) [virtual]
Implements OutputGenerator.
startParamList() [1/2]
void LatexGenerator::startParamList (ParamListTypes , const QCString & title) [virtual]
Implements BaseOutputDocInterface.
Definition at line 1916 of file latexgen.cpp.
{
  m_t << "\\begin{Desc}\n\\item[";
  docify(title);
  m_t << "]";
}
References docify(), and OutputGenerator::m_t.
startParamList() [2/2]
void LatexGenerator::startParamList (ParamListTypes , const QCString & title) [virtual]
Implements BaseOutputDocInterface.
startProjectNumber() [1/2]
void LatexGenerator::startProjectNumber () [virtual]
Implements OutputGenerator.
Definition at line 585 of file latexgen.cpp.
{
  m_t << "\\\\[1ex]\\large ";
}
References OutputGenerator::m_t.
startProjectNumber() [2/2]
void LatexGenerator::startProjectNumber () [virtual]
Implements OutputGenerator.
startQuickIndices() [1/2]
void LatexGenerator::startQuickIndices () [inline], [virtual]
Implements OutputGenerator.
Definition at line 260 of file latexgen.h.
{}
startQuickIndices() [2/2]
void LatexGenerator::startQuickIndices () [inline], [virtual]
Implements OutputGenerator.
Definition at line 260 of file latexgen.h.
{}
startSection() [1/2]
void LatexGenerator::startSection (const QCString & lab, const QCString & , SectionType type) [virtual]
Implements BaseOutputDocInterface.
Definition at line 1535 of file latexgen.cpp.
{
  bool pdfHyperlinks = Config_getBool(PDF_HYPERLINKS);
  bool usePDFLatex = Config_getBool(USE_PDFLATEX);
  if (usePDFLatex && pdfHyperlinks)
  {
    m_t << "\\hypertarget{" << stripPath(lab) << "}{}";
  }
  m_t << "\\";
  if (Config_getBool(COMPACT_LATEX))
  {
    switch(type)
    {
      case SectionType::Page: m_t << "doxysubsection"; break;
      case SectionType::Section: m_t << "doxysubsubsection"; break;
      case SectionType::Subsection: m_t << "doxyparagraph"; break;
      case SectionType::Subsubsection: m_t << "doxysubparagraph"; break;
      case SectionType::Paragraph: m_t << "doxysubparagraph"; break;
      default: ASSERT(0); break;
    }
    m_t << "{";
  }
  else
  {
    switch(type)
    {
      case SectionType::Page: m_t << "doxysection"; break;
      case SectionType::Section: m_t << "doxysubsection"; break;
      case SectionType::Subsection: m_t << "doxysubsubsection"; break;
      case SectionType::Subsubsection: m_t << "doxyparagraph"; break;
      case SectionType::Paragraph: m_t << "doxysubparagraph"; break;
      default: ASSERT(0); break;
    }
    m_t << "{";
  }
}
References ASSERT, Config_getBool, OutputGenerator::m_t, Page, Paragraph, Section, stripPath(), Subsection, Subsubsection, and type().
startSection() [2/2]
void LatexGenerator::startSection (const QCString & , const QCString & , SectionType) [virtual]
Implements BaseOutputDocInterface.
startSmall() [1/2]
void LatexGenerator::startSmall () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 234 of file latexgen.h.
{ m_t << "\\footnotesize "; }
References OutputGenerator::m_t.
startSmall() [2/2]
void LatexGenerator::startSmall () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 234 of file latexgen.h.
{ m_t << "\\footnotesize "; }
References OutputGenerator::m_t.
startSubsection() [1/2]
void LatexGenerator::startSubsection () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 228 of file latexgen.h.
{ m_t << "\\subsection*{"; }
References OutputGenerator::m_t.
startSubsection() [2/2]
void LatexGenerator::startSubsection () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 228 of file latexgen.h.
{ m_t << "\\subsection*{"; }
References OutputGenerator::m_t.
startSubsubsection() [1/2]
void LatexGenerator::startSubsubsection () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 230 of file latexgen.h.
{ m_t << "\\subsubsection*{"; }
References OutputGenerator::m_t.
Referenced by startCompoundTemplateParams().
startSubsubsection() [2/2]
void LatexGenerator::startSubsubsection () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 230 of file latexgen.h.
{ m_t << "\\subsubsection*{"; }
References OutputGenerator::m_t.
startTextBlock() [1/2]
void LatexGenerator::startTextBlock (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 293 of file latexgen.h.
{}
startTextBlock() [2/2]
void LatexGenerator::startTextBlock (bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 293 of file latexgen.h.
{}
startTextLink() [1/2]
void LatexGenerator::startTextLink (const QCString & f, const QCString & anchor) [virtual]
Implements BaseOutputDocInterface.
Definition at line 1236 of file latexgen.cpp.
{
  bool pdfHyperlinks = Config_getBool(PDF_HYPERLINKS);
  if (!m_disableLinks && pdfHyperlinks)
  {
    m_t << "\\mbox{\\hyperlink{";
    if (!f.isEmpty()) m_t << stripPath(f);
    if (!anchor.isEmpty()) m_t << "_" << anchor;
    m_t << "}{";
  }
  else
  {
    m_t << "\\textbf{ ";
  }
}
References Config_getBool, f, QCString::isEmpty(), m_disableLinks, OutputGenerator::m_t, and stripPath().
startTextLink() [2/2]
void LatexGenerator::startTextLink (const QCString & , const QCString &) [virtual]
Implements BaseOutputDocInterface.
startTitle() [1/2]
void LatexGenerator::startTitle () [virtual]
Implements BaseOutputDocInterface.
Definition at line 1329 of file latexgen.cpp.
{
  if (Config_getBool(COMPACT_LATEX))
  {
    m_t << "\\doxysubsection{";
  }
  else
  {
    m_t << "\\doxysection{";
  }
}
References Config_getBool, and OutputGenerator::m_t.
startTitle() [2/2]
void LatexGenerator::startTitle () [virtual]
Implements BaseOutputDocInterface.
startTitleHead() [1/2]
void LatexGenerator::startTitleHead (const QCString & fileName) [virtual]
Implements OutputGenerator.
Definition at line 1298 of file latexgen.cpp.
{
  bool pdfHyperlinks = Config_getBool(PDF_HYPERLINKS);
  bool usePDFLatex = Config_getBool(USE_PDFLATEX);
  if (usePDFLatex && pdfHyperlinks && !fileName.isEmpty())
  {
    m_t << "\\hypertarget{" << stripPath(fileName) << "}{}";
  }
  if (Config_getBool(COMPACT_LATEX))
  {
    m_t << "\\doxysubsection{";
  }
  else
  {
    m_t << "\\doxysection{";
  }
}
References Config_getBool, OutputGenerator::fileName(), QCString::isEmpty(), OutputGenerator::m_t, and stripPath().
startTitleHead() [2/2]
void LatexGenerator::startTitleHead (const QCString &) [virtual]
Implements OutputGenerator.
startTypewriter() [1/2]
void LatexGenerator::startTypewriter () [inline], [virtual]
Changes the text font to fixed size. The section ends with endTypewriter()
Implements BaseOutputDocInterface.
Definition at line 168 of file latexgen.h.
{ m_t << "{\\ttfamily "; }
References OutputGenerator::m_t.
startTypewriter() [2/2]
void LatexGenerator::startTypewriter () [inline], [virtual]
Changes the text font to fixed size. The section ends with endTypewriter()
Implements BaseOutputDocInterface.
Definition at line 168 of file latexgen.h.
{ m_t << "{\\ttfamily "; }
References OutputGenerator::m_t.
type() [1/2]
virtual OutputType LatexGenerator::type () const [inline], [virtual]
Implements OutputGenerator.
Definition at line 92 of file latexgen.h.
{ return Latex; }
References OutputGenerator::Latex.
Referenced by startSection(), and writeCodeLink().
type() [2/2]
virtual OutputType LatexGenerator::type () const [inline], [virtual]
Implements OutputGenerator.
Definition at line 92 of file latexgen.h.
{ return Latex; }
References OutputGenerator::Latex.
writeAnchor() [1/2]
void LatexGenerator::writeAnchor (const QCString & fileName, const QCString & name) [virtual]
Implements BaseOutputDocInterface.
Definition at line 1488 of file latexgen.cpp.
{
  //printf("LatexGenerator::writeAnchor(%s,%s)\n",fName,name);
  m_t << "\\label{" << stripPath(name) << "}\n";
  bool pdfHyperlinks = Config_getBool(PDF_HYPERLINKS);
  bool usePDFLatex = Config_getBool(USE_PDFLATEX);
  if (usePDFLatex && pdfHyperlinks)
  {
    if (!fName.isEmpty())
    {
      m_t << "\\Hypertarget{" << stripPath(fName) << "_" << stripPath(name) << "}\n";
    }
    else
    {
      m_t << "\\Hypertarget{" << stripPath(name) << "}\n";
    }
  }
}
References Config_getBool, QCString::isEmpty(), OutputGenerator::m_t, setup::name, and stripPath().
writeAnchor() [2/2]
void LatexGenerator::writeAnchor (const QCString & fileName, const QCString & name) [virtual]
Implements BaseOutputDocInterface.
writeChar() [1/2]
void LatexGenerator::writeChar (char c) [virtual]
Writes a single ASCII character to the output. Converts characters that have a special meaning.
Implements BaseOutputDocInterface.
Definition at line 1589 of file latexgen.cpp.
{
  char cs[2];
  cs[0]=c;
  cs[1]=0;
  docify(cs);
}
References c, cs, and docify().
writeChar() [2/2]
void LatexGenerator::writeChar (char c) [virtual]
Writes a single ASCII character to the output. Converts characters that have a special meaning.
Implements BaseOutputDocInterface.
writeCodeAnchor() [1/2]
void LatexGenerator::writeCodeAnchor (const QCString & name) [inline], [virtual]
Write an anchor to a source listing.
Parameters
name The name of the anchor.
Implements CodeOutputInterface.
Definition at line 116 of file latexgen.h.
    { m_codeGen.writeCodeAnchor(anchor); }
References m_codeGen, and LatexCodeGenerator::writeCodeAnchor().
writeCodeAnchor() [2/2]
void LatexGenerator::writeCodeAnchor (const QCString & name) [inline], [virtual]
Write an anchor to a source listing.
Parameters
name The name of the anchor.
Implements CodeOutputInterface.
Definition at line 116 of file latexgen.h.
    { m_codeGen.writeCodeAnchor(anchor); }
References m_codeGen, and LatexCodeGenerator::writeCodeAnchor().
writeCodeLink() [1/2]
void LatexGenerator::writeCodeLink (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) [inline], [virtual]
Writes a link to an object in a code fragment.
Parameters
type The type of symbol, used for semantic syntax highlighting, may be Default is no info is available.
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
tooltip The tooltip to display when the mouse is on the link.
Implements CodeOutputInterface.
Definition at line 97 of file latexgen.h.
    { m_codeGen.writeCodeLink(type,ref,file,anchor,name,tooltip); }
References caseconvert::file, m_codeGen, setup::name, type(), and LatexCodeGenerator::writeCodeLink().
writeCodeLink() [2/2]
void LatexGenerator::writeCodeLink (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) [inline], [virtual]
Writes a link to an object in a code fragment.
Parameters
type The type of symbol, used for semantic syntax highlighting, may be Default is no info is available.
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
tooltip The tooltip to display when the mouse is on the link.
Implements CodeOutputInterface.
Definition at line 97 of file latexgen.h.
    { m_codeGen.writeCodeLink(type,ref,file,anchor,name,tooltip); }
References caseconvert::file, m_codeGen, setup::name, type(), and LatexCodeGenerator::writeCodeLink().
writeDoc() [1/2]
void LatexGenerator::writeDoc (const IDocNodeAST * node, const Definition * ctx, const MemberDef * , int id) [virtual]
Implements OutputGenerator.
Definition at line 1978 of file latexgen.cpp.
{
  const DocNodeAST *astImpl = dynamic_cast<const DocNodeAST*>(ast);
  if (astImpl)
  {
    LatexDocVisitor visitor(m_t,m_codeGen,
                            ctx?ctx->getDefFileExtension():QCString(""),
                            m_insideTabbing);
    std::visit(visitor,astImpl->root);
  }
}
References Definition::getDefFileExtension(), m_codeGen, m_insideTabbing, OutputGenerator::m_t, and DocNodeAST::root.
writeDoc() [2/2]
void LatexGenerator::writeDoc (const IDocNodeAST * node, const Definition * ctx, const MemberDef * , int id) [virtual]
Implements OutputGenerator.
writeEndAnnoItem() [1/2]
void LatexGenerator::writeEndAnnoItem (const QCString & name) [virtual]
Implements OutputGenerator.
Definition at line 1202 of file latexgen.cpp.
{
  m_t << "}{\\pageref{" << stripPath(name) << "}}{}\n";
}
References OutputGenerator::m_t, setup::name, and stripPath().
writeEndAnnoItem() [2/2]
void LatexGenerator::writeEndAnnoItem (const QCString & name) [virtual]
Implements OutputGenerator.
writeFooter() [1/2]
void LatexGenerator::writeFooter (const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 129 of file latexgen.h.
{}
writeFooter() [2/2]
void LatexGenerator::writeFooter (const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 129 of file latexgen.h.
{}
writeFooterFile() [1/2]
void LatexGenerator::writeFooterFile (TextStream & t) [static]
Definition at line 549 of file latexgen.cpp.
{
  t << "% Latex footer for doxygen " << getDoxygenVersion() << "\n";
  t << ResourceMgr::instance().getAsString("footer.tex");
}
References ResourceMgr::getAsString(), getDoxygenVersion(), and ResourceMgr::instance().
Referenced by readConfiguration().
writeFooterFile() [2/2]
static void LatexGenerator::writeFooterFile (TextStream & t) [static]
writeGraphicalHierarchy() [1/2]
void LatexGenerator::writeGraphicalHierarchy (DotGfxHierarchyTable &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 291 of file latexgen.h.
{}
writeGraphicalHierarchy() [2/2]
void LatexGenerator::writeGraphicalHierarchy (DotGfxHierarchyTable &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 291 of file latexgen.h.
{}
writeHeaderFile() [1/2]
void LatexGenerator::writeHeaderFile (TextStream & t) [static]
Definition at line 543 of file latexgen.cpp.
{
  t << "% Latex header for doxygen " << getDoxygenVersion() << "\n";
  t << ResourceMgr::instance().getAsString("header.tex");
}
References ResourceMgr::getAsString(), getDoxygenVersion(), and ResourceMgr::instance().
Referenced by readConfiguration().
writeHeaderFile() [2/2]
static void LatexGenerator::writeHeaderFile (TextStream & t) [static]
writeInheritedSectionTitle() [1/2]
void LatexGenerator::writeInheritedSectionTitle (const QCString & , const QCString & , const QCString & , const QCString & , const QCString & , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 240 of file latexgen.h.
                                                                          {}
writeInheritedSectionTitle() [2/2]
void LatexGenerator::writeInheritedSectionTitle (const QCString & , const QCString & , const QCString & , const QCString & , const QCString & , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 240 of file latexgen.h.
                                                                          {}
writeLabel() [1/2]
void LatexGenerator::writeLabel (const QCString & l, bool isLast) [virtual]
Implements OutputGenerator.
Definition at line 2125 of file latexgen.cpp.
{
  m_t << "{\\ttfamily [" << l << "]}";
  if (!isLast) m_t << ", ";
}
References OutputGenerator::m_t.
writeLabel() [2/2]
void LatexGenerator::writeLabel (const QCString & l, bool isLast) [virtual]
Implements OutputGenerator.
writeLatexSpacing() [1/2]
void LatexGenerator::writeLatexSpacing () [inline], [virtual]
Implements OutputGenerator.
Definition at line 224 of file latexgen.h.
{ m_t << "\\hspace{0.3cm}"; }
References OutputGenerator::m_t.
writeLatexSpacing() [2/2]
void LatexGenerator::writeLatexSpacing () [inline], [virtual]
Implements OutputGenerator.
Definition at line 224 of file latexgen.h.
{ m_t << "\\hspace{0.3cm}"; }
References OutputGenerator::m_t.
writeLineNumber() [1/2]
void LatexGenerator::writeLineNumber (const QCString & ref, const QCString & file, const QCString & anchor, int lineNumber, bool writeLineAnchor) [inline], [virtual]
Writes the line number of a source listing
Parameters
ref External reference (when imported from a tag file)
file The file part of the URL pointing to the docs.
anchor The anchor part of the URL pointing to the docs.
lineNumber The line number to write
writeLineAnchor Indicates if an anchor for the line number needs to be written
Implements CodeOutputInterface.
Definition at line 102 of file latexgen.h.
    { m_codeGen.writeLineNumber(ref,file,anchor,lineNumber,writeLineAnchor); }
References caseconvert::file, m_codeGen, and LatexCodeGenerator::writeLineNumber().
writeLineNumber() [2/2]
void LatexGenerator::writeLineNumber (const QCString & ref, const QCString & file, const QCString & anchor, int lineNumber, bool writeLineAnchor) [inline], [virtual]
Writes the line number of a source listing
Parameters
ref External reference (when imported from a tag file)
file The file part of the URL pointing to the docs.
anchor The anchor part of the URL pointing to the docs.
lineNumber The line number to write
writeLineAnchor Indicates if an anchor for the line number needs to be written
Implements CodeOutputInterface.
Definition at line 102 of file latexgen.h.
    { m_codeGen.writeLineNumber(ref,file,anchor,lineNumber,writeLineAnchor); }
References caseconvert::file, m_codeGen, and LatexCodeGenerator::writeLineNumber().
writeLogo() [1/2]
void LatexGenerator::writeLogo () [inline], [virtual]
Implements OutputGenerator.
Definition at line 264 of file latexgen.h.
{}
writeLogo() [2/2]
void LatexGenerator::writeLogo () [inline], [virtual]
Implements OutputGenerator.
Definition at line 264 of file latexgen.h.
{}
writeNavigationPath() [1/2]
void LatexGenerator::writeNavigationPath (const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 263 of file latexgen.h.
{}
writeNavigationPath() [2/2]
void LatexGenerator::writeNavigationPath (const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 263 of file latexgen.h.
{}
writeNonBreakableSpace() [1/2]
void LatexGenerator::writeNonBreakableSpace (int) [virtual]
Implements BaseOutputDocInterface.
Definition at line 1694 of file latexgen.cpp.
{
  //printf("writeNonBreakableSpace()\n");
  if (m_insideTabbing)
  {
    m_t << "\\>";
  }
  else
  {
    m_t << "~";
  }
}
References m_insideTabbing, and OutputGenerator::m_t.
writeNonBreakableSpace() [2/2]
void LatexGenerator::writeNonBreakableSpace (int) [virtual]
Implements BaseOutputDocInterface.
writeObjectLink() [1/2]
void LatexGenerator::writeObjectLink (const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name) [virtual]
Writes a link to an object in the documentation.
Parameters
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
Implements BaseOutputDocInterface.
Definition at line 1262 of file latexgen.cpp.
{
  bool pdfHyperlinks = Config_getBool(PDF_HYPERLINKS);
  if (!m_disableLinks && ref.isEmpty() && pdfHyperlinks)
  {
    m_t << "\\mbox{\\hyperlink{";
    if (!f.isEmpty()) m_t << stripPath(f);
    if (!f.isEmpty() && !anchor.isEmpty()) m_t << "_";
    if (!anchor.isEmpty()) m_t << anchor;
    m_t << "}{";
    docify(text);
    m_t << "}}";
  }
  else
  {
    m_t << "\\textbf{ ";
    docify(text);
    m_t << "}";
  }
}
References Config_getBool, docify(), f, QCString::isEmpty(), m_disableLinks, OutputGenerator::m_t, and stripPath().
writeObjectLink() [2/2]
void LatexGenerator::writeObjectLink (const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name) [virtual]
Writes a link to an object in the documentation.
Parameters
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
Implements BaseOutputDocInterface.
writePageLink() [1/2]
void LatexGenerator::writePageLink (const QCString & name, bool) [virtual]
Implements OutputGenerator.
Definition at line 1090 of file latexgen.cpp.
{
  //bool &compactLatex = Config_getBool(COMPACT_LATEX);
  // next is remove for bug615957
  //if (compactLatex || first) m_t << "\\input" ; else m_t << "\\include";
  m_t << "\\input" ;
  m_t << "{" << name << "}\n";
}
References OutputGenerator::m_t, and setup::name.
writePageLink() [2/2]
void LatexGenerator::writePageLink (const QCString & , bool) [virtual]
Implements OutputGenerator.
writeQuickLinks() [1/2]
void LatexGenerator::writeQuickLinks (bool , HighlightedItem , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 265 of file latexgen.h.
{}
writeQuickLinks() [2/2]
void LatexGenerator::writeQuickLinks (bool , HighlightedItem , const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 265 of file latexgen.h.
{}
writeRuler() [1/2]
void LatexGenerator::writeRuler () [inline], [virtual]
Writes a horizontal ruler to the output
Implements BaseOutputDocInterface.
Definition at line 208 of file latexgen.h.
{ m_t << "\n\n"; }
References OutputGenerator::m_t.
writeRuler() [2/2]
void LatexGenerator::writeRuler () [inline], [virtual]
Writes a horizontal ruler to the output
Implements BaseOutputDocInterface.
Definition at line 208 of file latexgen.h.
{ m_t << "\n\n"; }
References OutputGenerator::m_t.
writeSearchInfo() [1/2]
void LatexGenerator::writeSearchInfo () [inline], [virtual]
Implements OutputGenerator.
Definition at line 128 of file latexgen.h.
{}
writeSearchInfo() [2/2]
void LatexGenerator::writeSearchInfo () [inline], [virtual]
Implements OutputGenerator.
Definition at line 128 of file latexgen.h.
{}
writeSplitBar() [1/2]
void LatexGenerator::writeSplitBar (const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 262 of file latexgen.h.
{}
writeSplitBar() [2/2]
void LatexGenerator::writeSplitBar (const QCString &) [inline], [virtual]
Implements OutputGenerator.
Definition at line 262 of file latexgen.h.
{}
writeStartAnnoItem() [1/2]
void LatexGenerator::writeStartAnnoItem (const QCString & type, const QCString & file, const QCString & path, const QCString & name) [virtual]
Implements OutputGenerator.
Definition at line 1193 of file latexgen.cpp.
{
  m_t << "\\item\\contentsline{section}\\textbf{ ";
  if (!path.isEmpty()) docify(path);
  docify(name);
  m_t << "} ";
}
References docify(), QCString::isEmpty(), OutputGenerator::m_t, and setup::name.
writeStartAnnoItem() [2/2]
void LatexGenerator::writeStartAnnoItem (const QCString & type, const QCString & file, const QCString & path, const QCString & name) [virtual]
Implements OutputGenerator.
writeString() [1/2]
void LatexGenerator::writeString (const QCString & text) [virtual]
Writes an ASCII string to the output, without converting special characters.
Implements BaseOutputDocInterface.
Definition at line 1134 of file latexgen.cpp.
{
  m_t << text;
}
References OutputGenerator::m_t.
writeString() [2/2]
void LatexGenerator::writeString (const QCString & text) [virtual]
Writes an ASCII string to the output, without converting special characters.
Implements BaseOutputDocInterface.
writeStyleInfo() [1/2]
void LatexGenerator::writeStyleInfo (int part) [virtual]
Implements OutputGenerator.
Definition at line 1100 of file latexgen.cpp.
{
  if (part > 0)
    return;
  startPlainFile("doxygen.sty");
  writeDefaultStyleSheet(m_t);
  endPlainFile();
  // workaround for the problem caused by change in LaTeX in version 2019
  // in the unmaintained tabu package
  startPlainFile("tabu_doxygen.sty");
  m_t << ResourceMgr::instance().getAsString("tabu_doxygen.sty");
  endPlainFile();
  startPlainFile("longtable_doxygen.sty");
  m_t << ResourceMgr::instance().getAsString("longtable_doxygen.sty");
  endPlainFile();
}
References OutputGenerator::endPlainFile(), ResourceMgr::getAsString(), ResourceMgr::instance(), OutputGenerator::m_t, OutputGenerator::startPlainFile(), and writeDefaultStyleSheet().
writeStyleInfo() [2/2]
void LatexGenerator::writeStyleInfo (int part) [virtual]
Implements OutputGenerator.
writeStyleSheetFile() [1/2]
void LatexGenerator::writeStyleSheetFile (TextStream & t) [static]
Definition at line 555 of file latexgen.cpp.
{
  t << "% stylesheet for doxygen " << getDoxygenVersion() << "\n";
  writeDefaultStyleSheet(t);
}
References getDoxygenVersion(), and writeDefaultStyleSheet().
Referenced by readConfiguration().
writeStyleSheetFile() [2/2]
static void LatexGenerator::writeStyleSheetFile (TextStream & t) [static]
writeSummaryLink() [1/2]
void LatexGenerator::writeSummaryLink (const QCString & , const QCString & , const QCString & , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 266 of file latexgen.h.
{}
writeSummaryLink() [2/2]
void LatexGenerator::writeSummaryLink (const QCString & , const QCString & , const QCString & , bool) [inline], [virtual]
Implements OutputGenerator.
Definition at line 266 of file latexgen.h.
{}
writeSynopsis() [1/2]
void LatexGenerator::writeSynopsis () [inline], [virtual]
Implements OutputGenerator.
Definition at line 255 of file latexgen.h.
{}
writeSynopsis() [2/2]
void LatexGenerator::writeSynopsis () [inline], [virtual]
Implements OutputGenerator.
Definition at line 255 of file latexgen.h.
{}
writeTooltip() [1/2]
void LatexGenerator::writeTooltip (const QCString & id, const DocLinkInfo & docInfo, const QCString & decl, const QCString & desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) [inline], [virtual]
Writes a tool tip definition
Parameters
id unique identifier for the tooltip
docInfo Info about the symbol's documentation.
decl full declaration of the symbol (for functions)
desc brief description for the symbol
defInfo Info about the symbol's definition in the source code
declInfo Info about the symbol's declaration in the source code
Implements CodeOutputInterface.
Definition at line 104 of file latexgen.h.
    { m_codeGen.writeTooltip(id,docInfo,decl,desc,defInfo,declInfo); }
References m_codeGen, and LatexCodeGenerator::writeTooltip().
writeTooltip() [2/2]
void LatexGenerator::writeTooltip (const QCString & id, const DocLinkInfo & docInfo, const QCString & decl, const QCString & desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) [inline], [virtual]
Writes a tool tip definition
Parameters
id unique identifier for the tooltip
docInfo Info about the symbol's documentation.
decl full declaration of the symbol (for functions)
desc brief description for the symbol
defInfo Info about the symbol's definition in the source code
declInfo Info about the symbol's declaration in the source code
Implements CodeOutputInterface.
Definition at line 104 of file latexgen.h.
    { m_codeGen.writeTooltip(id,docInfo,decl,desc,defInfo,declInfo); }
References m_codeGen, and LatexCodeGenerator::writeTooltip().
Member Data Documentation
m_codeGen
LatexCodeGenerator LatexGenerator::m_codeGen [private]
Definition at line 341 of file latexgen.h.
Referenced by codify(), docify(), endCodeFragment(), endCodeLine(), endDescTable(), endFile(), endFontClass(), endMemberDocSimple(), startCodeFragment(), startCodeLine(), startDescTable(), startFile(), startFontClass(), startMemberDocSimple(), writeCodeAnchor(), writeCodeLink(), writeDoc(), writeLineNumber(), and writeTooltip().
m_disableLinks
bool LatexGenerator::m_disableLinks = false [private]
Definition at line 337 of file latexgen.h.
Referenced by endGroupHeader(), endMemberDoc(), endMemberHeader(), endTextLink(), startGroupHeader(), startMemberHeader(), startTextLink(), and writeObjectLink().
m_firstDescItem
bool LatexGenerator::m_firstDescItem = true [private]
Definition at line 336 of file latexgen.h.
Referenced by endDescItem(), endDescription(), and startDescItem().
m_indent
int LatexGenerator::m_indent = 0 [private]
Definition at line 339 of file latexgen.h.
Referenced by endAnonTypeScope(), startAnonTypeScope(), and startMemberDescription().
m_insideTabbing
bool LatexGenerator::m_insideTabbing = false [private]
Definition at line 335 of file latexgen.h.
Referenced by docify(), endAnonTypeScope(), endInlineMemberName(), endInlineMemberType(), endMemberDescription(), endMemberItem(), endMemberList(), lineBreak(), startAnonTypeScope(), startInlineMemberName(), startInlineMemberType(), startMemberDescription(), startMemberItem(), startMemberList(), writeDoc(), and writeNonBreakableSpace().
m_relPath
QCString LatexGenerator::m_relPath [private]
Definition at line 338 of file latexgen.h.
Referenced by endCallGraph(), endDirDepGraph(), endDotGraph(), endGroupCollaboration(), endInclDepGraph(), and startFile().
templateMemberItem
bool LatexGenerator::templateMemberItem = false [private]
Definition at line 340 of file latexgen.h.
Referenced by endMemberItem(), endMemberTemplateParams(), startMemberItem(), and startMemberTemplateParams().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/latexgen.h
doxygen/src/latexgen.h
doxygen/build/doxygen/src/latexgen.cpp
doxygen/src/latexgen.cpp