FileListContext::Private Class Reference
Public Member Functions
void addFiles (const FileNameLinkedMap &fnMap)
void addFiles (const FileNameLinkedMap &fnMap)
Additional Inherited Members
Detailed Description
Definition at line 6338 of file context.cpp.
Member Function Documentation
addFiles() [1/2]
void FileListContext::Private::addFiles (const FileNameLinkedMap & fnMap) [inline]
Definition at line 6341 of file context.cpp.
    {
      // TODO: if FULL_PATH_NAMES is enabled, the ordering should be dir+file
      for (const auto &fn : fnMap)
      {
        for (const auto &fd : *fn)
        {
          bool doc = fd->isLinkableInProject();
          bool src = fd->generateSourceFile();
          bool nameOk = !fd->isDocumentationFile();
          if (nameOk && (doc || src) && !fd->isReference())
          {
            append(FileContext::alloc(fd.get()));
          }
        }
      }
    }
References FileContext::alloc(), GenericNodeListContext::append(), and src.
addFiles() [2/2]
void FileListContext::Private::addFiles (const FileNameLinkedMap & fnMap) [inline]
Definition at line 6341 of file context.cpp.
    {
      // TODO: if FULL_PATH_NAMES is enabled, the ordering should be dir+file
      for (const auto &fn : fnMap)
      {
        for (const auto &fd : *fn)
        {
          bool doc = fd->isLinkableInProject();
          bool src = fd->generateSourceFile();
          bool nameOk = !fd->isDocumentationFile();
          if (nameOk && (doc || src) && !fd->isReference())
          {
            append(FileContext::alloc(fd.get()));
          }
        }
      }
    }
References FileContext::alloc(), and src.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp