COutlineParser Class Reference
C-like language parser using state-based lexical scanning.
#include <scanner.h>
Classes
struct Private
Public Member Functions
COutlineParser ()
virtual ~COutlineParser ()
void parseInput (const QCString &fileName, const char *fileBuf, const std::shared_ptr< Entry > &root, ClangTUParser *clangParser)
bool needsPreprocessing (const QCString &extension) const
void parsePrototype (const QCString &text)
COutlineParser ()
virtual ~COutlineParser ()
void parseInput (const QCString &fileName, const char *fileBuf, const std::shared_ptr< Entry > &root, ClangTUParser *clangParser)
bool needsPreprocessing (const QCString &extension) const
void parsePrototype (const QCString &text)
Private Attributes
std::unique_ptr< Private > p
Detailed Description
C-like language parser using state-based lexical scanning.
This is the language parser for doxygen. It is somewhat fuzzy and supports C++ and various languages that are closely related to C++, such as C, C#, Objective-C, Java, PHP, and IDL.
Definition at line 29 of file scanner.h.
Constructor & Destructor Documentation
COutlineParser() [1/2]
COutlineParser::COutlineParser ()
Definition at line 7878 of file scanner.l.
                               : p(std::make_unique<COutlineParser::Private>())
{
  scannerYYlex_init_extra(&p->state,&p->yyscanner);
#ifdef FLEX_DEBUG
  scannerYYset_debug(1,p->yyscanner);
#endif
}
References p.
 COutlineParser() [1/2]
COutlineParser::~COutlineParser () [virtual]
Definition at line 7886 of file scanner.l.
{
  scannerYYlex_destroy(p->yyscanner);
}
References p.
COutlineParser() [2/2]
COutlineParser::COutlineParser ()
 COutlineParser() [2/2]
virtual COutlineParser::~COutlineParser () [virtual]
Member Function Documentation
needsPreprocessing() [1/2]
bool COutlineParser::needsPreprocessing (const QCString & extension) const [virtual]
Returns TRUE if the language identified by extension needs the C preprocessor to be run before feed the result to the input parser.
See also
parseInput()
Implements OutlineParserInterface.
Definition at line 7907 of file scanner.l.
{
  QCString fe=extension.lower();
  SrcLangExt lang = getLanguageFromFileName(extension);
  return (SrcLangExt_Cpp == lang) || (SrcLangExt_Lex == lang) ||
   !(fe==".java" || fe==".as" || fe==".d" || fe==".php" ||
      fe==".php4" || fe==".inc" || fe==".phtml"|| fe==".php5"
    );
}
References getLanguageFromFileName(), QCString::lower(), SrcLangExt_Cpp, and SrcLangExt_Lex.
needsPreprocessing() [2/2]
bool COutlineParser::needsPreprocessing (const QCString & extension) const [virtual]
Returns TRUE if the language identified by extension needs the C preprocessor to be run before feed the result to the input parser.
See also
parseInput()
Implements OutlineParserInterface.
parseInput() [1/2]
void COutlineParser::parseInput (const QCString & fileName, const char * fileBuf, const std::shared_ptr< Entry > & root, ClangTUParser * clangParser) [virtual]
Parses a single input file with the goal to build an Entry tree.
Parameters
 in fileName The full name of the file.
 in fileBuf The contents of the file (zero terminated).
 in,out root The root of the tree of Entry *nodes representing the information extracted from the file.
 in clangParser The clang translation unit parser object or nullptr if disabled.
Implements OutlineParserInterface.
Definition at line 7891 of file scanner.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)p->yyscanner;
  yyextra->thisParser = this;
  printlex(yy_flex_debug, TRUE, __FILE__, qPrint(fileName));
  ::parseMain(p->yyscanner,fileName,fileBuf,root,clangParser);
  printlex(yy_flex_debug, FALSE, __FILE__, qPrint(fileName));
}
References FALSE, p, parseMain(), printlex(), qPrint(), and TRUE.
parseInput() [2/2]
void COutlineParser::parseInput (const QCString & fileName, const char * fileBuf, const std::shared_ptr< Entry > & root, ClangTUParser * clangParser) [virtual]
Parses a single input file with the goal to build an Entry tree.
Parameters
 in fileName The full name of the file.
 in fileBuf The contents of the file (zero terminated).
 in,out root The root of the tree of Entry *nodes representing the information extracted from the file.
 in clangParser The clang translation unit parser object or nullptr if disabled.
Implements OutlineParserInterface.
parsePrototype() [1/2]
void COutlineParser::parsePrototype (const QCString & text) [virtual]
Callback function called by the comment block scanner. It provides a string text containing the prototype of a function or variable. The parser should parse this and store the information in the Entry node that corresponds with the node for which the comment block parser was invoked.
Implements OutlineParserInterface.
Definition at line 7917 of file scanner.l.
{
  ::parsePrototype(p->yyscanner,text);
}
References p, and parsePrototype().
Referenced by parsePrototype().
parsePrototype() [2/2]
void COutlineParser::parsePrototype (const QCString & text) [virtual]
Callback function called by the comment block scanner. It provides a string text containing the prototype of a function or variable. The parser should parse this and store the information in the Entry node that corresponds with the node for which the comment block parser was invoked.
Implements OutlineParserInterface.
Member Data Documentation
p
std::unique_ptr< Private > COutlineParser::p [private]
Definition at line 42 of file scanner.h.
Referenced by COutlineParser(), parseInput(), parsePrototype(), and ~COutlineParser().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/scanner.h
doxygen/src/scanner.h
doxygen/build/doxygen/src/scanner.l
doxygen/src/scanner.l