FilterAlphaIndex Class Reference
The implementation of the `alphaIndex` filter.
Classes
struct ListElem
Static Public Member Functions
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &args)
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &args)
Static Private Member Functions
static QCString keyToLabel (const char *startLetter)
static std::string determineSortKey (const TemplateStructIntfPtr s, const QCString &attribName)
static QCString keyToLabel (const char *startLetter)
static std::string determineSortKey (const TemplateStructIntfPtr s, const QCString &attribName)
Detailed Description
The implementation of the `alphaIndex` filter.
Definition at line 1280 of file template.cpp.
Member Function Documentation
apply() [1/2]
static TemplateVariant FilterAlphaIndex::apply (const TemplateVariant & v, const TemplateVariant & args) [inline], [static]
Definition at line 1320 of file template.cpp.
    {
      if (v.isList() && args.isString())
      {
        TemplateListIntfPtr list = v.toList();
        if (list)
        {
          //printf("FilterListSort::apply: v=%s args=%s\n",qPrint(v.toString()),qPrint(args.toString()));
          TemplateListIntf::ConstIteratorPtr it = list->createIterator();
          TemplateVariant item;
          TemplateListPtr result = TemplateList::alloc();
          // create list of items based on v using the data in args as a sort key
          using SortList = std::vector<ListElem>;
          SortList sortList;
          sortList.reserve(v.toList()->count());
          for (it->toFirst();(it->current(item));it->toNext())
          {
            TemplateStructIntfPtr s = item.toStruct();
            if (s)
            {
              std::string sortKey = determineSortKey(s,args.toString());
              sortList.emplace_back(sortKey,item);
              //printf("sortKey=%s\n",qPrint(sortKey));
            }
          }
          // sort the list
          std::sort(sortList.begin(),
              sortList.end(),
              [](const auto &lhs,const auto &rhs) { return lhs.key < rhs.key; });
          // create an index from the sorted list
          std::string letter;
          TemplateStructPtr indexNode;
          TemplateListPtr indexList;
          for (const auto &elem : sortList)
          {
            if (letter!=elem.key || indexNode==0)
            {
              // create new indexNode
              indexNode = TemplateStruct::alloc();
              indexList = TemplateList::alloc();
              indexNode->set("letter", elem.key);
              indexNode->set("label", keyToLabel(elem.key.c_str()));
              indexNode->set("items",std::static_pointer_cast<TemplateListIntf>(indexList));
              result->append(std::static_pointer_cast<TemplateStructIntf>(indexNode));
              letter=elem.key;
            }
            indexList->append(elem.value);
          }
          return TemplateVariant(std::static_pointer_cast<TemplateListIntf>(result));
        }
      }
      return v;
    }
References TemplateStruct::alloc(), TemplateList::alloc(), determineSortKey(), TemplateVariant::isList(), TemplateVariant::isString(), keyToLabel(), s, string, TemplateVariant::toList(), TemplateVariant::toString(), and TemplateVariant::toStruct().
apply() [2/2]
static TemplateVariant FilterAlphaIndex::apply (const TemplateVariant & v, const TemplateVariant & args) [inline], [static]
Definition at line 1320 of file template.cpp.
    {
      if (v.isList() && args.isString())
      {
        TemplateListIntfPtr list = v.toList();
        if (list)
        {
          //printf("FilterListSort::apply: v=%s args=%s\n",qPrint(v.toString()),qPrint(args.toString()));
          TemplateListIntf::ConstIteratorPtr it = list->createIterator();
          TemplateVariant item;
          TemplateListPtr result = TemplateList::alloc();
          // create list of items based on v using the data in args as a sort key
          using SortList = std::vector<ListElem>;
          SortList sortList;
          sortList.reserve(v.toList()->count());
          for (it->toFirst();(it->current(item));it->toNext())
          {
            TemplateStructIntfPtr s = item.toStruct();
            if (s)
            {
              std::string sortKey = determineSortKey(s,args.toString());
              sortList.emplace_back(sortKey,item);
              //printf("sortKey=%s\n",qPrint(sortKey));
            }
          }
          // sort the list
          std::sort(sortList.begin(),
              sortList.end(),
              [](const auto &lhs,const auto &rhs) { return lhs.key < rhs.key; });
          // create an index from the sorted list
          std::string letter;
          TemplateStructPtr indexNode;
          TemplateListPtr indexList;
          for (const auto &elem : sortList)
          {
            if (letter!=elem.key || indexNode==0)
            {
              // create new indexNode
              indexNode = TemplateStruct::alloc();
              indexList = TemplateList::alloc();
              indexNode->set("letter", elem.key);
              indexNode->set("label", keyToLabel(elem.key.c_str()));
              indexNode->set("items",std::static_pointer_cast<TemplateListIntf>(indexList));
              result->append(std::static_pointer_cast<TemplateStructIntf>(indexNode));
              letter=elem.key;
            }
            indexList->append(elem.value);
          }
          return TemplateVariant(std::static_pointer_cast<TemplateListIntf>(result));
        }
      }
      return v;
    }
References TemplateStruct::alloc(), TemplateList::alloc(), TemplateVariant::isList(), TemplateVariant::isString(), s, string, TemplateVariant::toList(), TemplateVariant::toString(), and TemplateVariant::toStruct().
determineSortKey() [1/2]
static std::string FilterAlphaIndex::determineSortKey (const TemplateStructIntfPtr s, const QCString & attribName) [inline], [static], [private]
Definition at line 1312 of file template.cpp.
    {
       TemplateVariant v = s->get(attribName);
       int index = getPrefixIndex(v.toString());
       return convertUTF8ToUpper(getUTF8CharAt(v.toString().str(),index));
    }
References convertUTF8ToUpper(), getPrefixIndex(), getUTF8CharAt(), s, QCString::str(), and TemplateVariant::toString().
Referenced by apply().
determineSortKey() [2/2]
static std::string FilterAlphaIndex::determineSortKey (const TemplateStructIntfPtr s, const QCString & attribName) [inline], [static], [private]
Definition at line 1312 of file template.cpp.
    {
       TemplateVariant v = s->get(attribName);
       int index = getPrefixIndex(v.toString());
       return convertUTF8ToUpper(getUTF8CharAt(v.toString().str(),index));
    }
References convertUTF8ToUpper(), getPrefixIndex(), getUTF8CharAt(), s, QCString::str(), and TemplateVariant::toString().
keyToLabel() [1/2]
static QCString FilterAlphaIndex::keyToLabel (const char * startLetter) [inline], [static], [private]
Definition at line 1289 of file template.cpp.
    {
      //printf(">keyToLabel(%s)\n",qPrint(startLetter));
      const char *p = startLetter;
      char c = *p;
      QCString result;
      if (c<127 && c>31) // printable ASCII character
      {
        result+=c;
      }
      else
      {
        result="0x";
        const char hex[]="0123456789abcdef";
        while ((c=*p++))
        {
          result+=hex[static_cast<unsigned char>(c)>>4];
          result+=hex[static_cast<unsigned char>(c)&0xf];
        }
      }
      //printf("<keyToLabel(%s)\n",qPrint(result));
      return result;
    }
References c, hex, and p.
Referenced by apply().
keyToLabel() [2/2]
static QCString FilterAlphaIndex::keyToLabel (const char * startLetter) [inline], [static], [private]
Definition at line 1289 of file template.cpp.
    {
      //printf(">keyToLabel(%s)\n",qPrint(startLetter));
      const char *p = startLetter;
      char c = *p;
      QCString result;
      if (c<127 && c>31) // printable ASCII character
      {
        result+=c;
      }
      else
      {
        result="0x";
        const char hex[]="0123456789abcdef";
        while ((c=*p++))
        {
          result+=hex[static_cast<unsigned char>(c)>>4];
          result+=hex[static_cast<unsigned char>(c)&0xf];
        }
      }
      //printf("<keyToLabel(%s)\n",qPrint(result));
      return result;
    }
References c, hex, and TemplateImmutableList::p.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp