FilterList Class Reference
The implementation of the `list` filter.
Static Public Member Functions
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &)
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &)
Detailed Description
The implementation of the `list` filter.
Definition at line 861 of file template.cpp.
Member Function Documentation
apply() [1/2]
static TemplateVariant FilterList::apply (const TemplateVariant & v, const TemplateVariant &) [inline], [static]
Definition at line 864 of file template.cpp.
    {
      if (v.isValid())
      {
        if (v.isList()) // input is already a list
        {
          return v;
        }
        // create a list with v as the only element
        TemplateListPtr list = TemplateList::alloc();
        list->append(v);
        return TemplateVariant(std::static_pointer_cast<TemplateListIntf>(list));
      }
      else
      {
        return v;
      }
    }
References TemplateList::alloc(), TemplateVariant::isList(), and TemplateVariant::isValid().
apply() [2/2]
static TemplateVariant FilterList::apply (const TemplateVariant & v, const TemplateVariant &) [inline], [static]
Definition at line 864 of file template.cpp.
    {
      if (v.isValid())
      {
        if (v.isList()) // input is already a list
        {
          return v;
        }
        // create a list with v as the only element
        TemplateListPtr list = TemplateList::alloc();
        list->append(v);
        return TemplateVariant(std::static_pointer_cast<TemplateListIntf>(list));
      }
      else
      {
        return v;
      }
    }
References TemplateList::alloc(), TemplateVariant::isList(), and TemplateVariant::isValid().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp