Cache< K, V > Class Template Reference
#include <cache.h>
Public Types
using kv_pair = std::pair< K, V >
using iterator = typename std::list< kv_pair >::iterator
using const_iterator = typename std::list< kv_pair >::const_iterator
using kv_pair = std::pair< K, V >
using iterator = typename std::list< kv_pair >::iterator
using const_iterator = typename std::list< kv_pair >::const_iterator
Public Member Functions
Cache (size_t capacity)
creates a cache that can hold capacity elements
V * insert (const K &key, V &&value)
Inserts value under key in the cache.
V * insert (const K &key, const V &value)
Inserts value under key in the cache.
void remove (const K &key)
V * find (const K &key)
size_t size () const
Returns the number of values stored in the cache.
size_t capacity () const
Returns the maximum number of values that can be stored in the cache.
uint64_t hits () const
Returns how many of the find() calls did find a value in the cache.
uint64_t misses () const
Returns how many of the find() calls did not found a value in the cache.
void clear ()
Clears all values in the cache.
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
Cache (size_t capacity)
creates a cache that can hold capacity elements
V * insert (const K &key, V &&value)
Inserts value under key in the cache.
V * insert (const K &key, const V &value)
Inserts value under key in the cache.
void remove (const K &key)
V * find (const K &key)
size_t size () const
Returns the number of values stored in the cache.
size_t capacity () const
Returns the maximum number of values that can be stored in the cache.
uint64_t hits () const
Returns how many of the find() calls did find a value in the cache.
uint64_t misses () const
Returns how many of the find() calls did not found a value in the cache.
void clear ()
Clears all values in the cache.
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
Private Member Functions
void resize ()
void resize ()
Private Attributes
size_t m_capacity
std::list< kv_pair > m_cacheItemList
std::unordered_map< K, iterator > m_cacheItemMap
uint64_t m_hits =0
uint64_t m_misses =0
Detailed Description
template<typename K, typename V>
class Cache< K, V >
Fixed size cache for value type V using keys of type K.
When the maximum capacity has reached, the least recently used value is removed from the cache (LRU strategy).
Definition at line 31 of file cache.h.
Member Typedef Documentation
const_iterator [1/2]
template<typename K , typename V >
using Cache< K, V >::const_iterator = typename std::list<kv_pair>::const_iterator
Definition at line 36 of file cache.h.
const_iterator [2/2]
template<typename K , typename V >
using Cache< K, V >::const_iterator = typename std::list<kv_pair>::const_iterator
Definition at line 36 of file cache.h.
iterator [1/2]
template<typename K , typename V >
using Cache< K, V >::iterator = typename std::list<kv_pair>::iterator
Definition at line 35 of file cache.h.
iterator [2/2]
template<typename K , typename V >
using Cache< K, V >::iterator = typename std::list<kv_pair>::iterator
Definition at line 35 of file cache.h.
kv_pair [1/2]
template<typename K , typename V >
using Cache< K, V >::kv_pair = std::pair<K,V>
Definition at line 34 of file cache.h.
kv_pair [2/2]
template<typename K , typename V >
using Cache< K, V >::kv_pair = std::pair<K,V>
Definition at line 34 of file cache.h.
Constructor & Destructor Documentation
Cache() [1/2]
template<typename K , typename V >
Cache< K, V >::Cache (size_t capacity) [inline]
creates a cache that can hold capacity elements
Definition at line 39 of file cache.h.
                           : m_capacity(capacity)
    {
    }
Cache() [2/2]
template<typename K , typename V >
Cache< K, V >::Cache (size_t capacity) [inline]
creates a cache that can hold capacity elements
Definition at line 39 of file cache.h.
                           : m_capacity(capacity)
    {
    }
Member Function Documentation
begin() [1/4]
template<typename K , typename V >
iterator Cache< K, V >::begin () [inline]
Definition at line 156 of file cache.h.
{ return m_cacheItemList.begin(); }
References Cache< K, V >::m_cacheItemList.
begin() [2/4]
template<typename K , typename V >
iterator Cache< K, V >::begin () [inline]
Definition at line 156 of file cache.h.
{ return m_cacheItemList.begin(); }
References Cache< K, V >::m_cacheItemList.
begin() [3/4]
template<typename K , typename V >
const_iterator Cache< K, V >::begin () const [inline]
Definition at line 158 of file cache.h.
{ return m_cacheItemList.cbegin(); }
References Cache< K, V >::m_cacheItemList.
begin() [4/4]
template<typename K , typename V >
const_iterator Cache< K, V >::begin () const [inline]
Definition at line 158 of file cache.h.
{ return m_cacheItemList.cbegin(); }
References Cache< K, V >::m_cacheItemList.
capacity() [1/2]
template<typename K , typename V >
size_t Cache< K, V >::capacity () const [inline]
Returns the maximum number of values that can be stored in the cache.
Definition at line 132 of file cache.h.
    {
      return m_capacity;
    }
References Cache< K, V >::m_capacity.
capacity() [2/2]
template<typename K , typename V >
size_t Cache< K, V >::capacity () const [inline]
Returns the maximum number of values that can be stored in the cache.
Definition at line 132 of file cache.h.
    {
      return m_capacity;
    }
References Cache< K, V >::m_capacity.
clear() [1/2]
template<typename K , typename V >
void Cache< K, V >::clear () [inline]
Clears all values in the cache.
Definition at line 150 of file cache.h.
    {
      m_cacheItemMap.clear();
      m_cacheItemList.clear();
    }
References Cache< K, V >::m_cacheItemList, and Cache< K, V >::m_cacheItemMap.
Referenced by parseInput().
clear() [2/2]
template<typename K , typename V >
void Cache< K, V >::clear () [inline]
Clears all values in the cache.
Definition at line 150 of file cache.h.
    {
      m_cacheItemMap.clear();
      m_cacheItemList.clear();
    }
References Cache< K, V >::m_cacheItemList, and Cache< K, V >::m_cacheItemMap.
end() [1/4]
template<typename K , typename V >
iterator Cache< K, V >::end () [inline]
Definition at line 157 of file cache.h.
{ return m_cacheItemList.end(); }
References Cache< K, V >::m_cacheItemList.
end() [2/4]
template<typename K , typename V >
iterator Cache< K, V >::end () [inline]
Definition at line 157 of file cache.h.
{ return m_cacheItemList.end(); }
References Cache< K, V >::m_cacheItemList.
end() [3/4]
template<typename K , typename V >
const_iterator Cache< K, V >::end () const [inline]
Definition at line 159 of file cache.h.
{ return m_cacheItemList.cend(); }
References Cache< K, V >::m_cacheItemList.
end() [4/4]
template<typename K , typename V >
const_iterator Cache< K, V >::end () const [inline]
Definition at line 159 of file cache.h.
{ return m_cacheItemList.cend(); }
References Cache< K, V >::m_cacheItemList.
find() [1/2]
template<typename K , typename V >
V * Cache< K, V >::find (const K & key) [inline]
Finds a value in the cache given the corresponding key.
Returns
a pointer to the value or nullptr if the key is not found in the cache
Note
The hit and miss counters are updated, see hits() and misses().
Definition at line 105 of file cache.h.
    {
      auto it = m_cacheItemMap.find(key);
      if (it != m_cacheItemMap.end())
      {
        // move the item to the front of the list
        m_cacheItemList.splice(m_cacheItemList.begin(),
                               m_cacheItemList,
                               it->second);
        m_hits++;
        // return the value
        return &it->second->second;
      }
      else
      {
        m_misses++;
      }
      return nullptr;
    }
References Cache< K, V >::m_cacheItemList, Cache< K, V >::m_cacheItemMap, Cache< K, V >::m_hits, and Cache< K, V >::m_misses.
Referenced by SymbolResolver::Private::getResolvedSymbolRec(), and SymbolResolver::Private::getResolvedTypeRec().
find() [2/2]
template<typename K , typename V >
V * Cache< K, V >::find (const K & key) [inline]
Finds a value in the cache given the corresponding key.
Returns
a pointer to the value or nullptr if the key is not found in the cache
Note
The hit and miss counters are updated, see hits() and misses().
Definition at line 105 of file cache.h.
    {
      auto it = m_cacheItemMap.find(key);
      if (it != m_cacheItemMap.end())
      {
        // move the item to the front of the list
        m_cacheItemList.splice(m_cacheItemList.begin(),
                               m_cacheItemList,
                               it->second);
        m_hits++;
        // return the value
        return &it->second->second;
      }
      else
      {
        m_misses++;
      }
      return nullptr;
    }
References Cache< K, V >::m_cacheItemList, Cache< K, V >::m_cacheItemMap, Cache< K, V >::m_hits, and Cache< K, V >::m_misses.
hits() [1/2]
template<typename K , typename V >
uint64_t Cache< K, V >::hits () const [inline]
Returns how many of the find() calls did find a value in the cache.
Definition at line 138 of file cache.h.
    {
      return m_hits;
    }
References Cache< K, V >::m_hits.
hits() [2/2]
template<typename K , typename V >
uint64_t Cache< K, V >::hits () const [inline]
Returns how many of the find() calls did find a value in the cache.
Definition at line 138 of file cache.h.
    {
      return m_hits;
    }
References Cache< K, V >::m_hits.
insert() [1/4]
template<typename K , typename V >
V * Cache< K, V >::insert (const K & key, const V & value) [inline]
Inserts value under key in the cache.
Definition at line 67 of file cache.h.
    {
      // reuse item if it already exists
      auto it = m_cacheItemMap.find(key);
      if (it != m_cacheItemMap.end())
      {
        // move the item to the front of the list
        m_cacheItemList.splice(m_cacheItemList.begin(),
                               m_cacheItemList,
                               it->second);
        it->second->second = value;
        return &it->second->second;
      }
      // store new item
      m_cacheItemList.push_front(kv_pair(key,value));
      V *result = &m_cacheItemList.front().second;
      m_cacheItemMap[key] = m_cacheItemList.begin();
      // remove least recently used item if cache is full
      resize();
      return result;
    }
References Cache< K, V >::m_cacheItemList, Cache< K, V >::m_cacheItemMap, and Cache< K, V >::resize().
insert() [2/4]
template<typename K , typename V >
V * Cache< K, V >::insert (const K & key, const V & value) [inline]
Inserts value under key in the cache.
Definition at line 67 of file cache.h.
    {
      // reuse item if it already exists
      auto it = m_cacheItemMap.find(key);
      if (it != m_cacheItemMap.end())
      {
        // move the item to the front of the list
        m_cacheItemList.splice(m_cacheItemList.begin(),
                               m_cacheItemList,
                               it->second);
        it->second->second = value;
        return &it->second->second;
      }
      // store new item
      m_cacheItemList.push_front(kv_pair(key,value));
      V *result = &m_cacheItemList.front().second;
      m_cacheItemMap[key] = m_cacheItemList.begin();
      // remove least recently used item if cache is full
      resize();
      return result;
    }
References Cache< K, V >::m_cacheItemList, Cache< K, V >::m_cacheItemMap, and Cache< K, V >::resize().
insert() [3/4]
template<typename K , typename V >
V * Cache< K, V >::insert (const K & key, V && value) [inline]
Inserts value under key in the cache.
Definition at line 44 of file cache.h.
    {
      // reuse item if it already exists
      auto it = m_cacheItemMap.find(key);
      if (it != m_cacheItemMap.end())
      {
        // move the item to the front of the list
        m_cacheItemList.splice(m_cacheItemList.begin(),
                               m_cacheItemList,
                               it->second);
        std::exchange(it->second->second,value);
        return &it->second->second;
      }
      // create new item
      m_cacheItemList.push_front(kv_pair(key,std::move(value)));
      V *result = &m_cacheItemList.front().second;
      m_cacheItemMap[key] = m_cacheItemList.begin();
      // remove least recently used item if cache is full
      resize();
      return result;
    }
References Cache< K, V >::m_cacheItemList, Cache< K, V >::m_cacheItemMap, and Cache< K, V >::resize().
Referenced by SymbolResolver::Private::getResolvedSymbolRec(), and SymbolResolver::Private::getResolvedTypeRec().
insert() [4/4]
template<typename K , typename V >
V * Cache< K, V >::insert (const K & key, V && value) [inline]
Inserts value under key in the cache.
Definition at line 44 of file cache.h.
    {
      // reuse item if it already exists
      auto it = m_cacheItemMap.find(key);
      if (it != m_cacheItemMap.end())
      {
        // move the item to the front of the list
        m_cacheItemList.splice(m_cacheItemList.begin(),
                               m_cacheItemList,
                               it->second);
        std::exchange(it->second->second,value);
        return &it->second->second;
      }
      // create new item
      m_cacheItemList.push_front(kv_pair(key,std::move(value)));
      V *result = &m_cacheItemList.front().second;
      m_cacheItemMap[key] = m_cacheItemList.begin();
      // remove least recently used item if cache is full
      resize();
      return result;
    }
References Cache< K, V >::m_cacheItemList, Cache< K, V >::m_cacheItemMap, and Cache< K, V >::resize().
misses() [1/2]
template<typename K , typename V >
uint64_t Cache< K, V >::misses () const [inline]
Returns how many of the find() calls did not found a value in the cache.
Definition at line 144 of file cache.h.
    {
      return m_misses;
    }
References Cache< K, V >::m_misses.
misses() [2/2]
template<typename K , typename V >
uint64_t Cache< K, V >::misses () const [inline]
Returns how many of the find() calls did not found a value in the cache.
Definition at line 144 of file cache.h.
    {
      return m_misses;
    }
References Cache< K, V >::m_misses.
remove() [1/2]
template<typename K , typename V >
void Cache< K, V >::remove (const K & key) [inline]
Removes entry key from the cache.
Note
this invalidates any iterators
Definition at line 91 of file cache.h.
    {
      // remove item if it already exists
      auto it = m_cacheItemMap.find(key);
      if (it != m_cacheItemMap.end())
      {
        m_cacheItemList.erase(it->second);
        m_cacheItemMap.erase(it);
      }
    }
References Cache< K, V >::m_cacheItemList, and Cache< K, V >::m_cacheItemMap.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), flushCachedTemplateRelations(), flushUnresolvedRelations(), doxmlparser.compound.memberdefType::get_remove(), and doxmlparser.compound.memberdefType::set_remove().
remove() [2/2]
template<typename K , typename V >
void Cache< K, V >::remove (const K & key) [inline]
Removes entry key from the cache.
Note
this invalidates any iterators
Definition at line 91 of file cache.h.
    {
      // remove item if it already exists
      auto it = m_cacheItemMap.find(key);
      if (it != m_cacheItemMap.end())
      {
        m_cacheItemList.erase(it->second);
        m_cacheItemMap.erase(it);
      }
    }
References Cache< K, V >::m_cacheItemList, and Cache< K, V >::m_cacheItemMap.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_remove(), and doxmlparser.compound.memberdefType::set_remove().
resize() [1/2]
template<typename K , typename V >
void Cache< K, V >::resize () [inline], [private]
Definition at line 163 of file cache.h.
    {
      if (m_cacheItemMap.size() > m_capacity)
      {
        auto last_it = m_cacheItemList.end();
        --last_it;
        m_cacheItemMap.erase(last_it->first);
        m_cacheItemList.pop_back();
      }
    }
References Cache< K, V >::m_cacheItemList, Cache< K, V >::m_cacheItemMap, and Cache< K, V >::m_capacity.
Referenced by Cache< K, V >::insert().
resize() [2/2]
template<typename K , typename V >
void Cache< K, V >::resize () [inline], [private]
Definition at line 163 of file cache.h.
    {
      if (m_cacheItemMap.size() > m_capacity)
      {
        auto last_it = m_cacheItemList.end();
        --last_it;
        m_cacheItemMap.erase(last_it->first);
        m_cacheItemList.pop_back();
      }
    }
References Cache< K, V >::m_cacheItemList, Cache< K, V >::m_cacheItemMap, and Cache< K, V >::m_capacity.
size() [1/2]
template<typename K , typename V >
size_t Cache< K, V >::size () const [inline]
Returns the number of values stored in the cache.
Definition at line 126 of file cache.h.
    {
      return m_cacheItemMap.size();
    }
References Cache< K, V >::m_cacheItemMap.
size() [2/2]
template<typename K , typename V >
size_t Cache< K, V >::size () const [inline]
Returns the number of values stored in the cache.
Definition at line 126 of file cache.h.
    {
      return m_cacheItemMap.size();
    }
References Cache< K, V >::m_cacheItemMap.
Member Data Documentation
m_cacheItemList
template<typename K , typename V >
std::list< kv_pair > Cache< K, V >::m_cacheItemList [private]
Definition at line 176 of file cache.h.
Referenced by Cache< K, V >::begin(), Cache< K, V >::clear(), Cache< K, V >::end(), Cache< K, V >::find(), Cache< K, V >::insert(), Cache< K, V >::remove(), and Cache< K, V >::resize().
m_cacheItemMap
template<typename K , typename V >
std::unordered_map< K, iterator > Cache< K, V >::m_cacheItemMap [private]
Definition at line 178 of file cache.h.
Referenced by Cache< K, V >::clear(), Cache< K, V >::find(), Cache< K, V >::insert(), Cache< K, V >::remove(), Cache< K, V >::resize(), and Cache< K, V >::size().
m_capacity
template<typename K , typename V >
size_t Cache< K, V >::m_capacity [private]
Definition at line 174 of file cache.h.
Referenced by Cache< K, V >::capacity(), and Cache< K, V >::resize().
m_hits
template<typename K , typename V >
uint64_t Cache< K, V >::m_hits =0 [private]
Definition at line 179 of file cache.h.
Referenced by Cache< K, V >::find(), and Cache< K, V >::hits().
m_misses
template<typename K , typename V >
uint64_t Cache< K, V >::m_misses =0 [private]
Definition at line 180 of file cache.h.
Referenced by Cache< K, V >::find(), and Cache< K, V >::misses().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/cache.h
doxygen/src/cache.h