TranslatorRomanian Class Reference
#include <translator_ro.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
Additional Inherited Members
Detailed Description
Definition at line 45 of file translator_ro.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorRomanian::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 81 of file translator_ro.h.
    {
      return "0x418 Romanian";
    }
getLanguageString() [2/2]
virtual QCString TranslatorRomanian::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 81 of file translator_ro.h.
    {
      return "0x418 Romanian";
    }
idLanguage() [1/2]
virtual QCString TranslatorRomanian::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 57 of file translator_ro.h.
    { return "romanian"; }
idLanguage() [2/2]
virtual QCString TranslatorRomanian::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 57 of file translator_ro.h.
    { return "romanian"; }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorRomanian::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 73 of file translator_ro.h.
    {
      return "\\usepackage[romanian]{babel}\n";
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorRomanian::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 73 of file translator_ro.h.
    {
      return "\\usepackage[romanian]{babel}\n";
    }
trAdditionalInheritedMembers() [1/2]
virtual QCString TranslatorRomanian::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1906 of file translator_ro.h.
    { return "Membri Motenii Adiionali"; }
trAdditionalInheritedMembers() [2/2]
virtual QCString TranslatorRomanian::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1906 of file translator_ro.h.
    { return "Membri Motenii Adiionali"; }
trAll() [1/2]
virtual QCString TranslatorRomanian::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1412 of file translator_ro.h.
    {
      return "Toate";
    }
trAll() [2/2]
virtual QCString TranslatorRomanian::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1412 of file translator_ro.h.
    {
      return "Toate";
    }
trAndMore() [1/2]
virtual QCString TranslatorRomanian::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1882 of file translator_ro.h.
    { return "i nc " + number; }
trAndMore() [2/2]
virtual QCString TranslatorRomanian::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1882 of file translator_ro.h.
    { return "i nc " + number; }
trAttention() [1/2]
virtual QCString TranslatorRomanian::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 980 of file translator_ro.h.
    {
      return "Atenie";
    }
trAttention() [2/2]
virtual QCString TranslatorRomanian::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 980 of file translator_ro.h.
    {
      return "Atenie";
    }
trAuthor() [1/2]
virtual QCString TranslatorRomanian::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1283 of file translator_ro.h.
    {
      QCString result((first_capital ? "Autor" : "autor"));
    result+= singular ? "ul":"ii";
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorRomanian::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1283 of file translator_ro.h.
    {
      QCString result((first_capital ? "Autor" : "autor"));
    result+= singular ? "ul":"ii";
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorRomanian::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1141 of file translator_ro.h.
    {
      return "Problema (Bug)";
    }
trBug() [2/2]
virtual QCString TranslatorRomanian::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1141 of file translator_ro.h.
    {
      return "Problema (Bug)";
    }
trBugList() [1/2]
virtual QCString TranslatorRomanian::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1146 of file translator_ro.h.
    {
      return "Lista de Probleme (Bugs)";
    }
trBugList() [2/2]
virtual QCString TranslatorRomanian::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1146 of file translator_ro.h.
    {
      return "Lista de Probleme (Bugs)";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorRomanian::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1536 of file translator_ro.h.
    {
      return "Graful de apeluri pentru aceast funcie:";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorRomanian::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1536 of file translator_ro.h.
    {
      return "Graful de apeluri pentru aceast funcie:";
    }
trCallGraph() [1/2]
virtual QCString TranslatorRomanian::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1417 of file translator_ro.h.
    {
      return "Graful de apel al acestei funcii:";
    }
trCallGraph() [2/2]
virtual QCString TranslatorRomanian::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1417 of file translator_ro.h.
    {
      return "Graful de apel al acestei funcii:";
    }
trCiteReferences() [1/2]
virtual QCString TranslatorRomanian::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1858 of file translator_ro.h.
    { return "Referine Bibliografice"; }
trCiteReferences() [2/2]
virtual QCString TranslatorRomanian::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1858 of file translator_ro.h.
    { return "Referine Bibliografice"; }
trClass() [1/2]
virtual QCString TranslatorRomanian::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1204 of file translator_ro.h.
    {
      QCString result((first_capital ? "Clas" : "clas"));
    result+= singular ? "a":"ele";
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorRomanian::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1204 of file translator_ro.h.
    {
      QCString result((first_capital ? "Clas" : "clas"));
    result+= singular ? "a":"ele";
      return result;
    }
trClassDiagram() [1/2]
virtual QCString TranslatorRomanian::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 530 of file translator_ro.h.
    {
      return "Diagrama de relaii pentru "+clName;
    }
trClassDiagram() [2/2]
virtual QCString TranslatorRomanian::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 530 of file translator_ro.h.
    {
      return "Diagrama de relaii pentru "+clName;
    }
trClassDocumentation() [1/2]
virtual QCString TranslatorRomanian::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 403 of file translator_ro.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentaia Structurilor de Date";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Documentaia Claselor";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorRomanian::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 403 of file translator_ro.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentaia Structurilor de Date";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Documentaia Claselor";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorRomanian::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1104 of file translator_ro.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Structuri de Date";
      }
      else
      {
        return "Clase";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorRomanian::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1104 of file translator_ro.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Structuri de Date";
      }
      else
      {
        return "Clase";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorRomanian::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 177 of file translator_ro.h.
    { return "Ierarhia Claselor"; }
trClassHierarchy() [2/2]
virtual QCString TranslatorRomanian::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 177 of file translator_ro.h.
    { return "Ierarhia Claselor"; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorRomanian::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 239 of file translator_ro.h.
    { return "Aceast list de moteniri este sortat n general, "
             "dar nu complet, n ordine alfabetic:";
    }
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorRomanian::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 239 of file translator_ro.h.
    { return "Aceast list de moteniri este sortat n general, "
             "dar nu complet, n ordine alfabetic:";
    }
trClassMethods() [1/2]
virtual QCString TranslatorRomanian::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1944 of file translator_ro.h.
    {
      return "Metodele Clasei";
    }
trClassMethods() [2/2]
virtual QCString TranslatorRomanian::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1944 of file translator_ro.h.
    {
      return "Metodele Clasei";
    }
trCode() [1/2]
virtual QCString TranslatorRomanian::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 879 of file translator_ro.h.
    {
      return "cod";
    }
trCode() [2/2]
virtual QCString TranslatorRomanian::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 879 of file translator_ro.h.
    {
      return "cod";
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorRomanian::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 834 of file translator_ro.h.
    {
      return "Diagrama de relaii pentru "+clName+":";
    }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorRomanian::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 834 of file translator_ro.h.
    {
      return "Diagrama de relaii pentru "+clName+":";
    }
trCompoundIndex() [1/2]
virtual QCString TranslatorRomanian::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 375 of file translator_ro.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Indexul Structurilor de Date";
      }
      else
      {
        return "Indexul Claselor";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorRomanian::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 375 of file translator_ro.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Indexul Structurilor de Date";
      }
      else
      {
        return "Indexul Claselor";
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorRomanian::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1590 of file translator_ro.h.
    { return "Indexul Tipurilor de Date"; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorRomanian::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1590 of file translator_ro.h.
    { return "Indexul Tipurilor de Date"; }
trCompoundList() [1/2]
virtual QCString TranslatorRomanian::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 181 of file translator_ro.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Structuri de Date";
      }
      else
      {
        return "Lista Claselor";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorRomanian::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 181 of file translator_ro.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Structuri de Date";
      }
      else
      {
        return "Lista Claselor";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorRomanian::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 255 of file translator_ro.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Lista structurilor de date, cu scurte descrieri:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Lista claselor, cu scurte descrieri:";
      }
      else
      {
        return "Lista claselor, structurilor, uniunilor i interfeelor"
        ", cu scurte descrieri:";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorRomanian::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 255 of file translator_ro.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Lista structurilor de date, cu scurte descrieri:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Lista claselor, cu scurte descrieri:";
      }
      else
      {
        return "Lista claselor, structurilor, uniunilor i interfeelor"
        ", cu scurte descrieri:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorRomanian::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1564 of file translator_ro.h.
    { return "Tipurile de date, cu scurte descrieri:"; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorRomanian::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1564 of file translator_ro.h.
    { return "Tipurile de date, cu scurte descrieri:"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorRomanian::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1556 of file translator_ro.h.
    { return "Lista Tipurilor de Date"; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorRomanian::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1556 of file translator_ro.h.
    { return "Lista Tipurilor de Date"; }
trCompoundMembers() [1/2]
virtual QCString TranslatorRomanian::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 199 of file translator_ro.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Cmpurile de Date";
      }
      else
      {
        return "Membrii Componeni"; //cu articol hotarat
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorRomanian::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 199 of file translator_ro.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Cmpurile de Date";
      }
      else
      {
        return "Membrii Componeni"; //cu articol hotarat
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorRomanian::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 274 of file translator_ro.h.
    {
      QCString result="Lista tuturor ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="cmpurilor ";
        if (!extractAll) result+=" documentate ";
        result+="din structuri si uniuni ";
      }
      else
      {
        result+="membrilor ";
      if (!extractAll) result+="documentai ";
        result+="din toate clasele ";
      }
      result+=", cu legturi ctre ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="documentaia structurii/uniunii pentru fiecare cmp n parte:";
        }
        else
        {
          result+="documentaia clasei pentru fiecare membru n parte:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="structurile/uniunile de care aparin:";
        }
        else
        {
          result+="clasele de care aparin:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorRomanian::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 274 of file translator_ro.h.
    {
      QCString result="Lista tuturor ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="cmpurilor ";
        if (!extractAll) result+=" documentate ";
        result+="din structuri si uniuni ";
      }
      else
      {
        result+="membrilor ";
      if (!extractAll) result+="documentai ";
        result+="din toate clasele ";
      }
      result+=", cu legturi ctre ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="documentaia structurii/uniunii pentru fiecare cmp n parte:";
        }
        else
        {
          result+="documentaia clasei pentru fiecare membru n parte:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="structurile/uniunile de care aparin:";
        }
        else
        {
          result+="clasele de care aparin:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorRomanian::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1568 of file translator_ro.h.
    {
      QCString result="Lista tuturor tipurilor de date ";
      if (!extractAll)
      {
        result+="documentate ";
      }
      result+=" cu legturi ctre ";
      if (!extractAll)
      {
         result+="documentaia structurii de date pentru fiecare membru";
      }
      else
      {
         result+="tipurile de date de care aparin:";
      }
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorRomanian::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1568 of file translator_ro.h.
    {
      QCString result="Lista tuturor tipurilor de date ";
      if (!extractAll)
      {
        result+="documentate ";
      }
      result+=" cu legturi ctre ";
      if (!extractAll)
      {
         result+="documentaia structurii de date pentru fiecare membru";
      }
      else
      {
         result+="tipurile de date de care aparin:";
      }
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorRomanian::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1560 of file translator_ro.h.
    { return "Cmpuri de date"; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorRomanian::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1560 of file translator_ro.h.
    { return "Cmpuri de date"; }
trCompoundReference() [1/2]
virtual QCString TranslatorRomanian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 604 of file translator_ro.h.
    {
      QCString result="Referin la ";
      switch(compType)
      {
        case ClassDef::Class: result+="clasa "; break;
        case ClassDef::Struct: result+="structura "; break;
        case ClassDef::Union: result+="uniunea "; break;
        case ClassDef::Interface: result+="interfaa "; break;
        case ClassDef::Protocol: result+="protocolul "; break;
        case ClassDef::Category: result+="categoria "; break;
        case ClassDef::Exception: result+="excepia "; break;
        default: break;
      }
      if (isTemplate) result+=" (Template) ";
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorRomanian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 604 of file translator_ro.h.
    {
      QCString result="Referin la ";
      switch(compType)
      {
        case ClassDef::Class: result+="clasa "; break;
        case ClassDef::Struct: result+="structura "; break;
        case ClassDef::Union: result+="uniunea "; break;
        case ClassDef::Interface: result+="interfaa "; break;
        case ClassDef::Protocol: result+="protocolul "; break;
        case ClassDef::Category: result+="categoria "; break;
        case ClassDef::Exception: result+="excepia "; break;
        default: break;
      }
      if (isTemplate) result+=" (Template) ";
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorRomanian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1631 of file translator_ro.h.
    {
      QCString result="Referin la ";
      switch(compType)
      {
        case ClassDef::Class: result+="Modulul "; break;
        case ClassDef::Struct: result+="Tipul "; break;
        case ClassDef::Union: result+="Uniunea "; break;
        case ClassDef::Interface: result+="Interfaa "; break;
        case ClassDef::Protocol: result+="Protocolul "; break;
        case ClassDef::Category: result+="Categoria "; break;
        case ClassDef::Exception: result+="Excepia "; break;
        default: break;
      }
      if (isTemplate) result+="(Template) ";
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorRomanian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1631 of file translator_ro.h.
    {
      QCString result="Referin la ";
      switch(compType)
      {
        case ClassDef::Class: result+="Modulul "; break;
        case ClassDef::Struct: result+="Tipul "; break;
        case ClassDef::Union: result+="Uniunea "; break;
        case ClassDef::Interface: result+="Interfaa "; break;
        case ClassDef::Protocol: result+="Protocolul "; break;
        case ClassDef::Category: result+="Categoria "; break;
        case ClassDef::Exception: result+="Excepia "; break;
        default: break;
      }
      if (isTemplate) result+="(Template) ";
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorRomanian::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 505 of file translator_ro.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Structuri de Date";
      }
      else
      {
        return "Membri";
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorRomanian::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 505 of file translator_ro.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Structuri de Date";
      }
      else
      {
        return "Membri";
      }
    }
References Config_getBool.
trConstantGroupReference() [1/2]
virtual QCString TranslatorRomanian::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1981 of file translator_ro.h.
    {
      QCString result=namespaceName;
      result+=" Referin Grup Constant";
      return result;
    }
trConstantGroupReference() [2/2]
virtual QCString TranslatorRomanian::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1981 of file translator_ro.h.
    {
      QCString result=namespaceName;
      result+=" Referin Grup Constant";
      return result;
    }
trConstantGroups() [1/2]
virtual QCString TranslatorRomanian::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1977 of file translator_ro.h.
    { return "Grupuri Constante"; }
trConstantGroups() [2/2]
virtual QCString TranslatorRomanian::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1977 of file translator_ro.h.
    { return "Grupuri Constante"; }
trConstructorDocumentation() [1/2]
virtual QCString TranslatorRomanian::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 844 of file translator_ro.h.
    {
      return "Documentaia pentru Constructori i Destructori";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorRomanian::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 844 of file translator_ro.h.
    {
      return "Documentaia pentru Constructori i Destructori";
    }
trCopyright() [1/2]
virtual QCString TranslatorRomanian::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1862 of file translator_ro.h.
    { return "Copyright"; }
trCopyright() [2/2]
virtual QCString TranslatorRomanian::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1862 of file translator_ro.h.
    { return "Copyright"; }
trDataTypes() [1/2]
virtual QCString TranslatorRomanian::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1614 of file translator_ro.h.
    { return "Tipuri de Date"; }
trDataTypes() [2/2]
virtual QCString TranslatorRomanian::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1614 of file translator_ro.h.
    { return "Tipuri de Date"; }
trDate() [1/2]
virtual QCString TranslatorRomanian::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 544 of file translator_ro.h.
    { return "Data"; }
trDate() [2/2]
virtual QCString TranslatorRomanian::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 544 of file translator_ro.h.
    { return "Data"; }
trDateTime() [1/2]
virtual QCString TranslatorRomanian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1815 of file translator_ro.h.
    {
      static const char *days[] = { "Luni","Mari","Miercuri","Joi","Vineri","Smbt","Duminic" };
      static const char *months[] = { "Ian","Feb","Mar","Apr","Mai","Iun","Iul","Aug","Sep","Oct","Noi","Dec" };
      QCString sdate;
      sdate.sprintf("%s %s %d %d",days[dayOfWeek-1],months[month-1],day,year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDateTime() [2/2]
virtual QCString TranslatorRomanian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1815 of file translator_ro.h.
    {
      static const char *days[] = { "Luni","Mari","Miercuri","Joi","Vineri","Smbt","Duminic" };
      static const char *months[] = { "Ian","Feb","Mar","Apr","Mai","Iun","Iul","Aug","Sep","Oct","Noi","Dec" };
      QCString sdate;
      sdate.sprintf("%s %s %d %d",days[dayOfWeek-1],months[month-1],day,year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDayOfWeek() [1/2]
virtual QCString TranslatorRomanian::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1831 of file translator_ro.h.
    {
      static const char *days_short[] = { "lun.", "mar.", "mie.", "joi", "vin.", "sm.", "dum." };
      static const char *days_full[] = { "luni", "mar?i", "miercuri", "joi", "vineri", "smbt", "duminic" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayOfWeek() [2/2]
virtual QCString TranslatorRomanian::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1831 of file translator_ro.h.
    {
      static const char *days_short[] = { "lun.", "mar.", "mie.", "joi", "vin.", "sm.", "dum." };
      static const char *days_full[] = { "luni", "mar?i", "miercuri", "joi", "vineri", "smbt", "duminic" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod() [1/2]
virtual QCString TranslatorRomanian::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1847 of file translator_ro.h.
    {
      static const char *dayPeriod[] = { "a.m.", "p.m." };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorRomanian::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1847 of file translator_ro.h.
    {
      static const char *dayPeriod[] = { "a.m.", "p.m." };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorRomanian::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 811 of file translator_ro.h.
    {
      return "Definiia n linia @0 a fiierului @1.";
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorRomanian::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 811 of file translator_ro.h.
    {
      return "Definiia n linia @0 a fiierului @1.";
    }
trDefinedIn() [1/2]
virtual QCString TranslatorRomanian::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 165 of file translator_ro.h.
    { return "definit n"; }
trDefinedIn() [2/2]
virtual QCString TranslatorRomanian::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 165 of file translator_ro.h.
    { return "definit n"; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorRomanian::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 815 of file translator_ro.h.
    {
      return "Definiia n fiierul @0.";
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorRomanian::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 815 of file translator_ro.h.
    {
      return "Definiia n fiierul @0.";
    }
trDefineDocumentation() [1/2]
virtual QCString TranslatorRomanian::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 475 of file translator_ro.h.
    { return "Documentaia definiiilor"; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorRomanian::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 475 of file translator_ro.h.
    { return "Documentaia definiiilor"; }
trDefines() [1/2]
virtual QCString TranslatorRomanian::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 439 of file translator_ro.h.
    { return "Definiii"; }
trDefines() [2/2]
virtual QCString TranslatorRomanian::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 439 of file translator_ro.h.
    { return "Definiii"; }
trDefineValue() [1/2]
virtual QCString TranslatorRomanian::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1131 of file translator_ro.h.
    {
      return "Valoare:";
    }
trDefineValue() [2/2]
virtual QCString TranslatorRomanian::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1131 of file translator_ro.h.
    {
      return "Valoare:";
    }
trDeprecated() [1/2]
virtual QCString TranslatorRomanian::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 824 of file translator_ro.h.
    {
      return "nvechit(Deprecated)";
    }
trDeprecated() [2/2]
virtual QCString TranslatorRomanian::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 824 of file translator_ro.h.
    {
      return "nvechit(Deprecated)";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorRomanian::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1340 of file translator_ro.h.
    {
      return "Lista elementelor nvechite (deprecated)";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorRomanian::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1340 of file translator_ro.h.
    {
      return "Lista elementelor nvechite (deprecated)";
    }
trDetailedDescription() [1/2]
virtual QCString TranslatorRomanian::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 97 of file translator_ro.h.
    { return "Descriere Detaliat"; }
trDetailedDescription() [2/2]
virtual QCString TranslatorRomanian::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 97 of file translator_ro.h.
    { return "Descriere Detaliat"; }
trDetailLevel() [1/2]
virtual QCString TranslatorRomanian::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1874 of file translator_ro.h.
    { return "nivel de detaliu"; }
trDetailLevel() [2/2]
virtual QCString TranslatorRomanian::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1874 of file translator_ro.h.
    { return "nivel de detaliu"; }
trDir() [1/2]
virtual QCString TranslatorRomanian::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1510 of file translator_ro.h.
     {
       QCString result((first_capital ? "Directo" : "directo"));
       if (singular) result+="r"; else result="are";
       return result;
     }
trDir() [2/2]
virtual QCString TranslatorRomanian::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1510 of file translator_ro.h.
     {
       QCString result((first_capital ? "Directo" : "directo"));
       if (singular) result+="r"; else result="are";
       return result;
     }
trDirDepGraph() [1/2]
virtual QCString TranslatorRomanian::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1866 of file translator_ro.h.
    { return QCString("Grafic de dependen a directoarelor pentru ")+name+":"; }
References setup::name.
trDirDepGraph() [2/2]
virtual QCString TranslatorRomanian::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1866 of file translator_ro.h.
    { return QCString("Grafic de dependen a directoarelor pentru ")+name+":"; }
References setup::name.
trDirDocumentation() [1/2]
virtual QCString TranslatorRomanian::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1489 of file translator_ro.h.
     { return "Documentaia directoarelor"; }
trDirDocumentation() [2/2]
virtual QCString TranslatorRomanian::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1489 of file translator_ro.h.
     { return "Documentaia directoarelor"; }
trDirectories() [1/2]
virtual QCString TranslatorRomanian::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1495 of file translator_ro.h.
     { return "Directoare"; }
trDirectories() [2/2]
virtual QCString TranslatorRomanian::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1495 of file translator_ro.h.
     { return "Directoare"; }
trDirIndex() [1/2]
virtual QCString TranslatorRomanian::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1483 of file translator_ro.h.
     { return "Ierarhia directoarelor"; }
trDirIndex() [2/2]
virtual QCString TranslatorRomanian::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1483 of file translator_ro.h.
     { return "Ierarhia directoarelor"; }
trDirReference() [1/2]
virtual QCString TranslatorRomanian::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1501 of file translator_ro.h.
     {
       QCString result="Director-referin "; result+=dirName;
       return result;
     }
trDirReference() [2/2]
virtual QCString TranslatorRomanian::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1501 of file translator_ro.h.
     {
       QCString result="Director-referin "; result+=dirName;
       return result;
     }
trDirRelation() [1/2]
virtual QCString TranslatorRomanian::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1754 of file translator_ro.h.
    {
      return QCString(name)+" Relaie";
    }
References setup::name.
trDirRelation() [2/2]
virtual QCString TranslatorRomanian::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1754 of file translator_ro.h.
    {
      return QCString(name)+" Relaie";
    }
References setup::name.
trDocumentation() [1/2]
virtual QCString TranslatorRomanian::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 357 of file translator_ro.h.
    { return "Documentaie"; }
trDocumentation() [2/2]
virtual QCString TranslatorRomanian::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 357 of file translator_ro.h.
    { return "Documentaie"; }
trEnumerations() [1/2]
virtual QCString TranslatorRomanian::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 451 of file translator_ro.h.
    { return "Enumerri"; }
trEnumerations() [2/2]
virtual QCString TranslatorRomanian::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 451 of file translator_ro.h.
    { return "Enumerri"; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorRomanian::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 487 of file translator_ro.h.
    { return "Documentaia enumerrilor"; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorRomanian::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 487 of file translator_ro.h.
    { return "Documentaia enumerrilor"; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorRomanian::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1544 of file translator_ro.h.
    { return "Documentaia Enumeratorilor"; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorRomanian::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1544 of file translator_ro.h.
    { return "Documentaia Enumeratorilor"; }
trEnumerationValues() [1/2]
virtual QCString TranslatorRomanian::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 469 of file translator_ro.h.
    { return "Valori de enumerri"; }
trEnumerationValues() [2/2]
virtual QCString TranslatorRomanian::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 469 of file translator_ro.h.
    { return "Valori de enumerri"; }
trEnumGeneratedFromFiles() [1/2]
virtual QCString TranslatorRomanian::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1886 of file translator_ro.h.
    { QCString result = "Documentaia pentru acest enum a fost generat din ";
      if (single)
        result += "urmtorul fiier:";
      else
        result += "urmtoarele fiiere:";
      return result;
    }
trEnumGeneratedFromFiles() [2/2]
virtual QCString TranslatorRomanian::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1886 of file translator_ro.h.
    { QCString result = "Documentaia pentru acest enum a fost generat din ";
      if (single)
        result += "urmtorul fiier:";
      else
        result += "urmtoarele fiiere:";
      return result;
    }
trEnumName() [1/2]
virtual QCString TranslatorRomanian::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 157 of file translator_ro.h.
    { return "nume enumerare"; }
trEnumName() [2/2]
virtual QCString TranslatorRomanian::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 157 of file translator_ro.h.
    { return "nume enumerare"; }
trEnumReference() [1/2]
virtual QCString TranslatorRomanian::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1896 of file translator_ro.h.
    { return QCString(name)+" Referin Enum"; }
References setup::name.
trEnumReference() [2/2]
virtual QCString TranslatorRomanian::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1896 of file translator_ro.h.
    { return QCString(name)+" Referin Enum"; }
References setup::name.
trEnumValue() [1/2]
virtual QCString TranslatorRomanian::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 161 of file translator_ro.h.
    { return "valoare enumerare"; }
trEnumValue() [2/2]
virtual QCString TranslatorRomanian::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 161 of file translator_ro.h.
    { return "valoare enumerare"; }
trEventDocumentation() [1/2]
virtual QCString TranslatorRomanian::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1357 of file translator_ro.h.
    {
      return "Documentaia aferent evenimentelor";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorRomanian::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1357 of file translator_ro.h.
    {
      return "Documentaia aferent evenimentelor";
    }
trEvents() [1/2]
virtual QCString TranslatorRomanian::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1352 of file translator_ro.h.
    {
      return "Evenimente";
    }
trEvents() [2/2]
virtual QCString TranslatorRomanian::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1352 of file translator_ro.h.
    {
      return "Evenimente";
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorRomanian::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 429 of file translator_ro.h.
    { return "Documentaia Exemplelor"; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorRomanian::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 429 of file translator_ro.h.
    { return "Documentaia Exemplelor"; }
trExamples() [1/2]
virtual QCString TranslatorRomanian::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 231 of file translator_ro.h.
    { return "Exemple"; }
trExamples() [2/2]
virtual QCString TranslatorRomanian::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 231 of file translator_ro.h.
    { return "Exemple"; }
trExamplesDescription() [1/2]
virtual QCString TranslatorRomanian::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 342 of file translator_ro.h.
    { return "Lista tuturor exemplelor:"; }
trExamplesDescription() [2/2]
virtual QCString TranslatorRomanian::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 342 of file translator_ro.h.
    { return "Lista tuturor exemplelor:"; }
trExceptions() [1/2]
virtual QCString TranslatorRomanian::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 560 of file translator_ro.h.
    { return "Excepii"; }
trExceptions() [2/2]
virtual QCString TranslatorRomanian::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 560 of file translator_ro.h.
    { return "Excepii"; }
trExtendsClass() [1/2]
virtual QCString TranslatorRomanian::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1936 of file translator_ro.h.
    {
      return "Extinde clasa @0.";
    }
trExtendsClass() [2/2]
virtual QCString TranslatorRomanian::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1936 of file translator_ro.h.
    {
      return "Extinde clasa @0.";
    }
trFile() [1/2]
virtual QCString TranslatorRomanian::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1215 of file translator_ro.h.
    {
      QCString result((first_capital ? "Fiier" : "fiier"));
    result+= singular ? "ul":"ele";
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorRomanian::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1215 of file translator_ro.h.
    {
      QCString result((first_capital ? "Fiier" : "fiier"));
    result+= singular ? "ul":"ele";
      return result;
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorRomanian::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 423 of file translator_ro.h.
    { return "Documentaia Fiierelor"; }
trFileDocumentation() [2/2]
virtual QCString TranslatorRomanian::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 423 of file translator_ro.h.
    { return "Documentaia Fiierelor"; }
trFileIn() [1/2]
virtual QCString TranslatorRomanian::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1791 of file translator_ro.h.
    {
      return "Fiierul din "+name;
    }
References setup::name.
trFileIn() [2/2]
virtual QCString TranslatorRomanian::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1791 of file translator_ro.h.
    {
      return "Fiierul din "+name;
    }
References setup::name.
trFileIndex() [1/2]
virtual QCString TranslatorRomanian::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 391 of file translator_ro.h.
    { return "Indexul Fiierelor"; }
trFileIndex() [2/2]
virtual QCString TranslatorRomanian::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 391 of file translator_ro.h.
    { return "Indexul Fiierelor"; }
trFileList() [1/2]
virtual QCString TranslatorRomanian::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 195 of file translator_ro.h.
    { return "Lista fiierelor"; }
trFileList() [2/2]
virtual QCString TranslatorRomanian::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 195 of file translator_ro.h.
    { return "Lista fiierelor"; }
trFileListDescription() [1/2]
virtual QCString TranslatorRomanian::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 245 of file translator_ro.h.
    {
      QCString result="Lista tuturor ";
      result+="fiierelor";
      if (!extractAll) result+=" documentate";
      result+=", cu scurte descrieri:";
      return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorRomanian::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 245 of file translator_ro.h.
    {
      QCString result="Lista tuturor ";
      result+="fiierelor";
      if (!extractAll) result+=" documentate";
      result+=", cu scurte descrieri:";
      return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorRomanian::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 213 of file translator_ro.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globale";
      }
      else
      {
        return "Membrii din Fiier"; //cu articol hotarat
      }
    }
References Config_getBool.
trFileMembers() [2/2]
virtual QCString TranslatorRomanian::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 213 of file translator_ro.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globale";
      }
      else
      {
        return "Membrii din Fiier"; //cu articol hotarat
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
virtual QCString TranslatorRomanian::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 318 of file translator_ro.h.
    {
      QCString result="Lista tuturor ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funciilor, variabilelor, definiiilor, enumerrilor i definiiilor de tip";
      if (!extractAll) result+=" documentate";
      }
      else
      {
        result+="membrilor ";
      if (!extractAll) result+="documentai ";
      result+="din toate fiierele";
      }
      result+=", cu legturi ctre ";
      if (extractAll)
        result+="fiierele de care aparin:";
      else
        result+="documentaia aferent:";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorRomanian::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 318 of file translator_ro.h.
    {
      QCString result="Lista tuturor ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funciilor, variabilelor, definiiilor, enumerrilor i definiiilor de tip";
      if (!extractAll) result+=" documentate";
      }
      else
      {
        result+="membrilor ";
      if (!extractAll) result+="documentai ";
      result+="din toate fiierele";
      }
      result+=", cu legturi ctre ";
      if (extractAll)
        result+="fiierele de care aparin:";
      else
        result+="documentaia aferent:";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorRomanian::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 627 of file translator_ro.h.
    {
      QCString result="Referin la fiierul ";
      result+=fileName;
      return result;
    }
trFileReference() [2/2]
virtual QCString TranslatorRomanian::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 627 of file translator_ro.h.
    {
      QCString result="Referin la fiierul ";
      result+=fileName;
      return result;
    }
trFriends() [1/2]
virtual QCString TranslatorRomanian::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 586 of file translator_ro.h.
    { return "Prieteni"; }
trFriends() [2/2]
virtual QCString TranslatorRomanian::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 586 of file translator_ro.h.
    { return "Prieteni"; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorRomanian::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 493 of file translator_ro.h.
    { return "Documentaia funciilor"; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorRomanian::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 493 of file translator_ro.h.
    { return "Documentaia funciilor"; }
trFunctions() [1/2]
virtual QCString TranslatorRomanian::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 457 of file translator_ro.h.
    { return "Funcii"; }
trFunctions() [2/2]
virtual QCString TranslatorRomanian::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 457 of file translator_ro.h.
    { return "Funcii"; }
trGeneratedAt() [1/2]
virtual QCString TranslatorRomanian::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 521 of file translator_ro.h.
    {
      QCString result="Generat "+date;
      if (!projName.isEmpty()) result+=" pentru "+projName;
      result+=" de ctre";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorRomanian::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 521 of file translator_ro.h.
    {
      QCString result="Generat "+date;
      if (!projName.isEmpty()) result+=" pentru "+projName;
      result+=" de ctre";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorRomanian::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 149 of file translator_ro.h.
    { QCString result="Generat automat de Doxygen";
      if (!s.isEmpty()) result+=" pentru "+s;
      result+=" din codul surs.";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorRomanian::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 149 of file translator_ro.h.
    { QCString result="Generat automat de Doxygen";
      if (!s.isEmpty()) result+=" pentru "+s;
      result+=" din codul surs.";
      return result;
    }
References s.
trGeneratedBy() [1/2]
virtual QCString TranslatorRomanian::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 564 of file translator_ro.h.
    { return "Generat de"; }
trGeneratedBy() [2/2]
virtual QCString TranslatorRomanian::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 564 of file translator_ro.h.
    { return "Generat de"; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorRomanian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 767 of file translator_ro.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Documentaia pentru aceast ";
      switch(compType)
      {
        case ClassDef::Class: result+="clas"; break;
        case ClassDef::Struct: result+="structur"; break;
        case ClassDef::Union: result+="uniune"; break;
        case ClassDef::Interface: result+="interfa"; break;
        case ClassDef::Protocol: result+="protocol"; break;
        case ClassDef::Category: result+="categorie"; break;
        case ClassDef::Exception: result+="excepie"; break;
        default: break;
      }
      result+=" a fost generat din fiier";
      if (single) result+="ul:"; else result+="ele:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorRomanian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 767 of file translator_ro.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Documentaia pentru aceast ";
      switch(compType)
      {
        case ClassDef::Class: result+="clas"; break;
        case ClassDef::Struct: result+="structur"; break;
        case ClassDef::Union: result+="uniune"; break;
        case ClassDef::Interface: result+="interfa"; break;
        case ClassDef::Protocol: result+="protocol"; break;
        case ClassDef::Category: result+="categorie"; break;
        case ClassDef::Exception: result+="excepie"; break;
        default: break;
      }
      result+=" a fost generat din fiier";
      if (single) result+="ul:"; else result+="ele:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorRomanian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1700 of file translator_ro.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Documentaia ";
      switch(compType)
      {
        case ClassDef::Class: result+="modulului"; break;
        case ClassDef::Struct: result+="tipului"; break;
        case ClassDef::Union: result+="uniunii"; break;
        case ClassDef::Interface: result+="interfeei"; break;
        case ClassDef::Protocol: result+="protocolului"; break;
        case ClassDef::Category: result+="categoriei"; break;
        case ClassDef::Exception: result+="excepiei"; break;
        default: break;
      }
      result+=" a fost generat din urmto";
      if (single) result+="rul fiier:"; else result+="arele fiiere:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorRomanian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1700 of file translator_ro.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Documentaia ";
      switch(compType)
      {
        case ClassDef::Class: result+="modulului"; break;
        case ClassDef::Struct: result+="tipului"; break;
        case ClassDef::Union: result+="uniunii"; break;
        case ClassDef::Interface: result+="interfeei"; break;
        case ClassDef::Protocol: result+="protocolului"; break;
        case ClassDef::Category: result+="categoriei"; break;
        case ClassDef::Exception: result+="excepiei"; break;
        default: break;
      }
      result+=" a fost generat din urmto";
      if (single) result+="rul fiier:"; else result+="arele fiiere:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorRomanian::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1270 of file translator_ro.h.
    {
      QCString result((first_capital ? "Global" : "global"));
      if (!singular) result+="e";
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorRomanian::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1270 of file translator_ro.h.
    {
      QCString result((first_capital ? "Global" : "global"));
      if (!singular) result+="e";
      return result;
    }
trGlobalNamespace() [1/2]
virtual QCString TranslatorRomanian::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1766 of file translator_ro.h.
    {
      return "Namespace Global";
    }
trGlobalNamespace() [2/2]
virtual QCString TranslatorRomanian::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1766 of file translator_ro.h.
    {
      return "Namespace Global";
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorRomanian::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 854 of file translator_ro.h.
    {
      return "Vezi documentaia.";
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorRomanian::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 854 of file translator_ro.h.
    {
      return "Vezi documentaia.";
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorRomanian::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 887 of file translator_ro.h.
    {
      return "Vezi ierarhia claselor n mod grafic";
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorRomanian::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 887 of file translator_ro.h.
    {
      return "Vezi ierarhia claselor n mod grafic";
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorRomanian::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 849 of file translator_ro.h.
    {
      return "Vezi sursele.";
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorRomanian::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 849 of file translator_ro.h.
    {
      return "Vezi sursele.";
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorRomanian::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 891 of file translator_ro.h.
    {
      return "Vezi ierarhia claselor n mod text";
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorRomanian::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 891 of file translator_ro.h.
    {
      return "Vezi ierarhia claselor n mod text";
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorRomanian::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 883 of file translator_ro.h.
    {
      return "Ierarhia Claselor n mod grafic";
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorRomanian::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 883 of file translator_ro.h.
    {
      return "Ierarhia Claselor n mod grafic";
    }
trGroup() [1/2]
virtual QCString TranslatorRomanian::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1237 of file translator_ro.h.
    {
      QCString result((first_capital ? "Grupu" : "grupu"));
    result+= singular ? "l":"rile";
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorRomanian::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1237 of file translator_ro.h.
    {
      QCString result((first_capital ? "Grupu" : "grupu"));
    result+= singular ? "l":"rile";
      return result;
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorRomanian::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 369 of file translator_ro.h.
    { return "Index Ierarhic"; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorRomanian::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 369 of file translator_ro.h.
    { return "Index Ierarhic"; }
trImplementedFromList() [1/2]
virtual QCString TranslatorRomanian::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1308 of file translator_ro.h.
    {
      return "Implementeaz "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorRomanian::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1308 of file translator_ro.h.
    {
      return "Implementeaz "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorRomanian::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1316 of file translator_ro.h.
    {
      return "Implementat n "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorRomanian::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1316 of file translator_ro.h.
    {
      return "Implementat n "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorRomanian::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 984 of file translator_ro.h.
    {
      return "Acest graf arat care fiiere includ, "
          "direct sau indirect, acest fiier:";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorRomanian::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 984 of file translator_ro.h.
    {
      return "Acest graf arat care fiiere includ, "
          "direct sau indirect, acest fiier:";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorRomanian::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 839 of file translator_ro.h.
    {
      return "Graful dependenelor prin incluziune pentru "+fName+":";
    }
trInclDepGraph() [2/2]
virtual QCString TranslatorRomanian::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 839 of file translator_ro.h.
    {
      return "Graful dependenelor prin incluziune pentru "+fName+":";
    }
trIncludesFileIn() [1/2]
virtual QCString TranslatorRomanian::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1800 of file translator_ro.h.
    {
      return "Include fiierul din "+name;
    }
References setup::name.
trIncludesFileIn() [2/2]
virtual QCString TranslatorRomanian::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1800 of file translator_ro.h.
    {
      return "Include fiierul din "+name;
    }
References setup::name.
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorRomanian::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 143 of file translator_ro.h.
    { return ", inclusiv a tuturor membrilor motenii."; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorRomanian::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 143 of file translator_ro.h.
    { return ", inclusiv a tuturor membrilor motenii."; }
trInheritedByList() [1/2]
virtual QCString TranslatorRomanian::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 700 of file translator_ro.h.
    {
      return "Motenit de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorRomanian::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 700 of file translator_ro.h.
    {
      return "Motenit de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom() [1/2]
virtual QCString TranslatorRomanian::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1900 of file translator_ro.h.
    { return QCString(members)+" motenit(e) din "+what; }
trInheritedFrom() [2/2]
virtual QCString TranslatorRomanian::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1900 of file translator_ro.h.
    { return QCString(members)+" motenit(e) din "+what; }
trInheritsList() [1/2]
virtual QCString TranslatorRomanian::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 692 of file translator_ro.h.
    {
      return "Motenete "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorRomanian::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 692 of file translator_ro.h.
    {
      return "Motenete "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorRomanian::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 874 of file translator_ro.h.
    {
      return "Valoarea iniial:";
    }
trInitialValue() [2/2]
virtual QCString TranslatorRomanian::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 874 of file translator_ro.h.
    {
      return "Valoarea iniial:";
    }
trInstanceMethods() [1/2]
virtual QCString TranslatorRomanian::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1952 of file translator_ro.h.
    {
      return "Metodele Instanei";
    }
trInstanceMethods() [2/2]
virtual QCString TranslatorRomanian::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1952 of file translator_ro.h.
    {
      return "Metodele Instanei";
    }
trInterfaces() [1/2]
virtual QCString TranslatorRomanian::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1969 of file translator_ro.h.
    { return "Interfee exportate"; }
trInterfaces() [2/2]
virtual QCString TranslatorRomanian::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1969 of file translator_ro.h.
    { return "Interfee exportate"; }
trInvariant() [1/2]
virtual QCString TranslatorRomanian::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 869 of file translator_ro.h.
    {
      return "Invariant";
    }
trInvariant() [2/2]
virtual QCString TranslatorRomanian::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 869 of file translator_ro.h.
    {
      return "Invariant";
    }
trISOLang() [1/2]
virtual QCString TranslatorRomanian::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 77 of file translator_ro.h.
    {
      return "ro";
    }
trISOLang() [2/2]
virtual QCString TranslatorRomanian::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 77 of file translator_ro.h.
    {
      return "ro";
    }
trLegend() [1/2]
virtual QCString TranslatorRomanian::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1064 of file translator_ro.h.
    {
      return "legenda";
    }
trLegend() [2/2]
virtual QCString TranslatorRomanian::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1064 of file translator_ro.h.
    {
      return "legenda";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorRomanian::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 1004 of file translator_ro.h.
    {
      return
        "Aceast pagin arat modul n care trebuie s interpretai "
        "grafurile generate de doxygen.<p>\n"
        "Considerai urmtorul exemplu:\n"
        "\\code\n"
        "/*! Clas invizibil, tiat din cauza depirii spaiului */\n"
        "class Invisible { };\n\n"
        "/*! Alt clas tiat, relaia de motenire este ascuns */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Clas necomentat n stil doxygen */\n"
        "class Undocumented { };\n\n"
        "/*! Clas care este motenit n mod public */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! Clas template */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Clas care este motenit n mod protejat */\n"
        "class ProtectedBase { };\n\n"
        "/*! Clas care este motenit n mod privat */\n"
        "class PrivateBase { };\n\n"
        "/*! Clas care este folosit de clasa Inherited */\n"
        "class Used { };\n\n"
        "/*! Superclas care motenete un numr de alte clase */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Dac tagul \\c MAX_DOT_GRAPH_HEIGHT din fiierul de configurare "
        "este setat la 200, acesta este graful rezultat:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "Csuele din partea de sus au urmtoarea semnificaie:\n"
        "<ul>\n"
        "<li>O csu neagr reprezint structura sau clasa pentru care "
        "graful este generat.\n"
        "<li>O csu cu marginea neagr reprezint o structur sau o clas documentate.\n"
        "<li>O csu cu marginea gri reprezint o structur sau o clas nedocumentate.\n"
        "<li>O csu cu marginea roie reprezint o structur sau o clas documentate, pentru\n"
        "care nu toate relaiile de motenire/incluziune sunt artate. Un graf este "
        "tiat dac nu ncape n marginile specificate."
        "</ul>\n"
        "Sgeile au urmtoarea semnificaie:\n"
        "<ul>\n"
        "<li>O sgeat de un albastru nchis este folosit cnd avem o relaie de "
        "motenire public ntre dou clase.\n"
        "<li>O sgeat de un verde nchis este folosit cnd avem o motenire protejat.\n"
        "<li>O sgeat de un rou nchis este folosit cnd avem o motenire privat.\n"
        "<li>O sgeat violet punctat este folosit pentru o clas coninut sau folosit "
        "de o alt clas. Sgeata este marcat cu variabila(e) "
        "prin care este accesibil clasa sau structura spre care este ndreptat. \n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorRomanian::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 1004 of file translator_ro.h.
    {
      return
        "Aceast pagin arat modul n care trebuie s interpretai "
        "grafurile generate de doxygen.<p>\n"
        "Considerai urmtorul exemplu:\n"
        "\\code\n"
        "/*! Clas invizibil, tiat din cauza depirii spaiului */\n"
        "class Invisible { };\n\n"
        "/*! Alt clas tiat, relaia de motenire este ascuns */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Clas necomentat n stil doxygen */\n"
        "class Undocumented { };\n\n"
        "/*! Clas care este motenit n mod public */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! Clas template */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Clas care este motenit n mod protejat */\n"
        "class ProtectedBase { };\n\n"
        "/*! Clas care este motenit n mod privat */\n"
        "class PrivateBase { };\n\n"
        "/*! Clas care este folosit de clasa Inherited */\n"
        "class Used { };\n\n"
        "/*! Superclas care motenete un numr de alte clase */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Dac tagul \\c MAX_DOT_GRAPH_HEIGHT din fiierul de configurare "
        "este setat la 200, acesta este graful rezultat:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "Csuele din partea de sus au urmtoarea semnificaie:\n"
        "<ul>\n"
        "<li>O csu neagr reprezint structura sau clasa pentru care "
        "graful este generat.\n"
        "<li>O csu cu marginea neagr reprezint o structur sau o clas documentate.\n"
        "<li>O csu cu marginea gri reprezint o structur sau o clas nedocumentate.\n"
        "<li>O csu cu marginea roie reprezint o structur sau o clas documentate, pentru\n"
        "care nu toate relaiile de motenire/incluziune sunt artate. Un graf este "
        "tiat dac nu ncape n marginile specificate."
        "</ul>\n"
        "Sgeile au urmtoarea semnificaie:\n"
        "<ul>\n"
        "<li>O sgeat de un albastru nchis este folosit cnd avem o relaie de "
        "motenire public ntre dou clase.\n"
        "<li>O sgeat de un verde nchis este folosit cnd avem o motenire protejat.\n"
        "<li>O sgeat de un rou nchis este folosit cnd avem o motenire privat.\n"
        "<li>O sgeat violet punctat este folosit pentru o clas coninut sau folosit "
        "de o alt clas. Sgeata este marcat cu variabila(e) "
        "prin care este accesibil clasa sau structura spre care este ndreptat. \n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorRomanian::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 999 of file translator_ro.h.
    {
      return "Legenda grafului";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorRomanian::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 999 of file translator_ro.h.
    {
      return "Legenda grafului";
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorRomanian::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 131 of file translator_ro.h.
    { return "Lista tuturor membrilor"; }
trListOfAllMembers() [2/2]
virtual QCString TranslatorRomanian::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 131 of file translator_ro.h.
    { return "Lista tuturor membrilor"; }
trLoading() [1/2]
virtual QCString TranslatorRomanian::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1760 of file translator_ro.h.
    {
      return "Se ncarc...";
    }
trLoading() [2/2]
virtual QCString TranslatorRomanian::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1760 of file translator_ro.h.
    {
      return "Se ncarc...";
    }
trMainPage() [1/2]
virtual QCString TranslatorRomanian::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 798 of file translator_ro.h.
    { return "Pagina principal"; }
trMainPage() [2/2]
virtual QCString TranslatorRomanian::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 798 of file translator_ro.h.
    { return "Pagina principal"; }
trMember() [1/2]
virtual QCString TranslatorRomanian::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1259 of file translator_ro.h.
    {
      QCString result((first_capital ? "Membr" : "membr"));
    result+= singular ? "ul":"ii";
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorRomanian::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1259 of file translator_ro.h.
    {
      QCString result((first_capital ? "Membr" : "membr"));
    result+= singular ? "ul":"ii";
      return result;
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorRomanian::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 113 of file translator_ro.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentaia Cmpurilor";
      }
      else
      {
        return "Documentaia Datelor Membre";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorRomanian::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 113 of file translator_ro.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentaia Cmpurilor";
      }
      else
      {
        return "Documentaia Datelor Membre";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorRomanian::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 105 of file translator_ro.h.
    { return "Documentaia Enumerrilor Membre"; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorRomanian::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 105 of file translator_ro.h.
    { return "Documentaia Enumerrilor Membre"; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorRomanian::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 109 of file translator_ro.h.
    { return "Documentaia Funciilor Membre"; }
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorRomanian::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 109 of file translator_ro.h.
    { return "Documentaia Funciilor Membre"; }
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorRomanian::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1552 of file translator_ro.h.
    { return "Documentaia Funciei Membre/Subrutinei"; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorRomanian::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1552 of file translator_ro.h.
    { return "Documentaia Funciei Membre/Subrutinei"; }
trMemberList() [1/2]
virtual QCString TranslatorRomanian::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 135 of file translator_ro.h.
    { return "Lista Membrilor"; }
trMemberList() [2/2]
virtual QCString TranslatorRomanian::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 135 of file translator_ro.h.
    { return "Lista Membrilor"; }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorRomanian::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 101 of file translator_ro.h.
    { return "Documentaia Definiiilor de Tipuri (typedef) Membre"; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorRomanian::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 101 of file translator_ro.h.
    { return "Documentaia Definiiilor de Tipuri (typedef) Membre"; }
trMethodDocumentation() [1/2]
virtual QCString TranslatorRomanian::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1959 of file translator_ro.h.
    {
      return "Documentaia Metodelor";
    }
trMethodDocumentation() [2/2]
virtual QCString TranslatorRomanian::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1959 of file translator_ro.h.
    {
      return "Documentaia Metodelor";
    }
trModule() [1/2]
virtual QCString TranslatorRomanian::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1690 of file translator_ro.h.
    {
      QCString result((first_capital ? "Modul" : "modul"));
      if (singular) result+="ul";
      else result += "ele";
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorRomanian::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1690 of file translator_ro.h.
    {
      QCString result((first_capital ? "Modul" : "modul"));
      if (singular) result+="ul";
      else result += "ele";
      return result;
    }
trModuleDocumentation() [1/2]
virtual QCString TranslatorRomanian::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 397 of file translator_ro.h.
    { return "Documentaia Modulelor"; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorRomanian::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 397 of file translator_ro.h.
    { return "Documentaia Modulelor"; }
trModuleIndex() [1/2]
virtual QCString TranslatorRomanian::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 363 of file translator_ro.h.
    { return "Indexul Modulelor"; }
trModuleIndex() [2/2]
virtual QCString TranslatorRomanian::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 363 of file translator_ro.h.
    { return "Indexul Modulelor"; }
trModuleReference() [1/2]
virtual QCString TranslatorRomanian::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1652 of file translator_ro.h.
    {
      QCString result="Referin la Modulul ";
      result += namespaceName;
      return result;
    }
trModuleReference() [2/2]
virtual QCString TranslatorRomanian::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1652 of file translator_ro.h.
    {
      QCString result="Referin la Modulul ";
      result += namespaceName;
      return result;
    }
trModules() [1/2]
virtual QCString TranslatorRomanian::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 173 of file translator_ro.h.
    { return "Module"; }
trModules() [2/2]
virtual QCString TranslatorRomanian::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 173 of file translator_ro.h.
    { return "Module"; }
trModulesDescription() [1/2]
virtual QCString TranslatorRomanian::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 350 of file translator_ro.h.
    { return "Lista tuturor modulelor:"; }
trModulesDescription() [2/2]
virtual QCString TranslatorRomanian::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 350 of file translator_ro.h.
    { return "Lista tuturor modulelor:"; }
trModulesIndex() [1/2]
virtual QCString TranslatorRomanian::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1683 of file translator_ro.h.
    { return "Indexul Modulelor"; }
trModulesIndex() [2/2]
virtual QCString TranslatorRomanian::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1683 of file translator_ro.h.
    { return "Indexul Modulelor"; }
trModulesList() [1/2]
virtual QCString TranslatorRomanian::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1618 of file translator_ro.h.
    { return "Lista Modulelor"; }
trModulesList() [2/2]
virtual QCString TranslatorRomanian::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1618 of file translator_ro.h.
    { return "Lista Modulelor"; }
trModulesListDescription() [1/2]
virtual QCString TranslatorRomanian::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1622 of file translator_ro.h.
    {
      QCString result="Lista tuturor modulelor ";
      if (!extractAll) result+="documentate ";
      result+="cu scurte descrieri:";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorRomanian::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1622 of file translator_ro.h.
    {
      QCString result="Lista tuturor modulelor ";
      if (!extractAll) result+="documentate ";
      result+="cu scurte descrieri:";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorRomanian::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1664 of file translator_ro.h.
    {
      QCString result="Lista tuturor membrilor ";
      if (!extractAll) result+="documentai ai ";
      result+="modulului cu legturi ctre ";
      if (extractAll)
      {
        result+="documentaia modulului pentru fiecare membru:";
      }
      else
      {
        result+="modulele de care aparin:";
      }
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorRomanian::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1664 of file translator_ro.h.
    {
      QCString result="Lista tuturor membrilor ";
      if (!extractAll) result+="documentai ai ";
      result+="modulului cu legturi ctre ";
      if (extractAll)
      {
        result+="documentaia modulului pentru fiecare membru:";
      }
      else
      {
        result+="modulele de care aparin:";
      }
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorRomanian::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1660 of file translator_ro.h.
    { return "Membrii Modulului"; }
trModulesMembers() [2/2]
virtual QCString TranslatorRomanian::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1660 of file translator_ro.h.
    { return "Membrii Modulului"; }
trMonth() [1/2]
virtual QCString TranslatorRomanian::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1839 of file translator_ro.h.
    {
      static const char *months_short[] = { "ian.", "feb.", "mar.", "apr.", "mai", "iun.", "iul.", "aug.", "sept.", "oct.", "nov.", "dec." };
      static const char *months_full[] = { "ianuarie", "februarie", "martie", "aprilie", "mai", "iunie", "iulie", "august", "septembrie", "octombrie", "noiembrie", "decembrie" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMonth() [2/2]
virtual QCString TranslatorRomanian::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1839 of file translator_ro.h.
    {
      static const char *months_short[] = { "ian.", "feb.", "mar.", "apr.", "mai", "iun.", "iul.", "aug.", "sept.", "oct.", "nov.", "dec." };
      static const char *months_full[] = { "ianuarie", "februarie", "martie", "aprilie", "mai", "iunie", "iulie", "august", "septembrie", "octombrie", "noiembrie", "decembrie" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore() [1/2]
virtual QCString TranslatorRomanian::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 127 of file translator_ro.h.
    { return "Mai mult..."; }
trMore() [2/2]
virtual QCString TranslatorRomanian::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 127 of file translator_ro.h.
    { return "Mai mult..."; }
trNamespace() [1/2]
virtual QCString TranslatorRomanian::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1226 of file translator_ro.h.
    {
      QCString result((first_capital ? "Namespace" : "namespace"));
    result+= singular ? "-ul":"-urile";
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorRomanian::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1226 of file translator_ro.h.
    {
      QCString result((first_capital ? "Namespace" : "namespace"));
    result+= singular ? "-ul":"-urile";
      return result;
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorRomanian::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 747 of file translator_ro.h.
    { return "Documentaia Namespace-ului"; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorRomanian::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 747 of file translator_ro.h.
    { return "Documentaia Namespace-ului"; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorRomanian::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 741 of file translator_ro.h.
    { return "Indexul Namespace-ului"; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorRomanian::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 741 of file translator_ro.h.
    { return "Indexul Namespace-ului"; }
trNamespaceList() [1/2]
virtual QCString TranslatorRomanian::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 570 of file translator_ro.h.
    { return "Lista de Namespace-uri"; }
trNamespaceList() [2/2]
virtual QCString TranslatorRomanian::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 570 of file translator_ro.h.
    { return "Lista de Namespace-uri"; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorRomanian::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 574 of file translator_ro.h.
    {
      QCString result="Lista tuturor ";
      result+="namespace-urilor ";
      if (!extractAll) result+="documentate ";
      result+=", cu scurte descrieri:";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorRomanian::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 574 of file translator_ro.h.
    {
      QCString result="Lista tuturor ";
      result+="namespace-urilor ";
      if (!extractAll) result+="documentate ";
      result+=", cu scurte descrieri:";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorRomanian::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 726 of file translator_ro.h.
    {
      QCString result="Lista tuturor membrilor ";
      if (!extractAll) result+="documentai ";
      result+="din toate namespace-urile, cu legturi ctre ";
      if (extractAll)
        result+="documentaia namespace-ului pentru fiecare membru n parte:";
      else
        result+="namespace-urile de care aparin:";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorRomanian::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 726 of file translator_ro.h.
    {
      QCString result="Lista tuturor membrilor ";
      if (!extractAll) result+="documentai ";
      result+="din toate namespace-urile, cu legturi ctre ";
      if (extractAll)
        result+="documentaia namespace-ului pentru fiecare membru n parte:";
      else
        result+="namespace-urile de care aparin:";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorRomanian::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 722 of file translator_ro.h.
    { return "Membrii Namespace-ului"; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorRomanian::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 722 of file translator_ro.h.
    { return "Membrii Namespace-ului"; }
trNamespaceReference() [1/2]
virtual QCString TranslatorRomanian::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 635 of file translator_ro.h.
    {
      QCString result="Referin la Namespace-ul ";
      result+=namespaceName;
      return result;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorRomanian::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 635 of file translator_ro.h.
    {
      QCString result="Referin la Namespace-ul ";
      result+=namespaceName;
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorRomanian::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 757 of file translator_ro.h.
    { return "Namespace-uri"; }
trNamespaces() [2/2]
virtual QCString TranslatorRomanian::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 757 of file translator_ro.h.
    { return "Namespace-uri"; }
trNoMatches() [1/2]
virtual QCString TranslatorRomanian::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1778 of file translator_ro.h.
    {
      return "Niciun rezultat";
    }
trNoMatches() [2/2]
virtual QCString TranslatorRomanian::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1778 of file translator_ro.h.
    {
      return "Niciun rezultat";
    }
trNote() [1/2]
virtual QCString TranslatorRomanian::trNote () [inline], [virtual]
Implements Translator.
Definition at line 904 of file translator_ro.h.
    {
      return "Not";
    }
trNote() [2/2]
virtual QCString TranslatorRomanian::trNote () [inline], [virtual]
Implements Translator.
Definition at line 904 of file translator_ro.h.
    {
      return "Not";
    }
trOverloadText() [1/2]
virtual QCString TranslatorRomanian::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1524 of file translator_ro.h.
    {
       return "Aceasta este o funcie membr suprascris. "
              "Difer de funcia de mai sus "
              "doar prin argumentele acceptate.";
    }
trOverloadText() [2/2]
virtual QCString TranslatorRomanian::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1524 of file translator_ro.h.
    {
       return "Aceasta este o funcie membr suprascris. "
              "Difer de funcia de mai sus "
              "doar prin argumentele acceptate.";
    }
trPackage() [1/2]
virtual QCString TranslatorRomanian::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1116 of file translator_ro.h.
    {
      return "Pachet "+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorRomanian::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1116 of file translator_ro.h.
    {
      return "Pachet "+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorRomanian::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1393 of file translator_ro.h.
    {
      return "Atribute n pachet";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorRomanian::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1393 of file translator_ro.h.
    {
      return "Atribute n pachet";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorRomanian::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1375 of file translator_ro.h.
    {
      return "Funcii n pachet";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorRomanian::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1375 of file translator_ro.h.
    {
      return "Funcii n pachet";
    }
trPackageListDescription() [1/2]
virtual QCString TranslatorRomanian::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1121 of file translator_ro.h.
    {
      return "Lista pachetelor, nsoit de scurte explicaii, acolo unde acestea exist:";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorRomanian::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1121 of file translator_ro.h.
    {
      return "Lista pachetelor, nsoit de scurte explicaii, acolo unde acestea exist:";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorRomanian::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1379 of file translator_ro.h.
    {
      return "Membrii n pachet";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorRomanian::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1379 of file translator_ro.h.
    {
      return "Membrii n pachet";
    }
trPackages() [1/2]
virtual QCString TranslatorRomanian::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1126 of file translator_ro.h.
    {
      return "Pachete";
    }
trPackages() [2/2]
virtual QCString TranslatorRomanian::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1126 of file translator_ro.h.
    {
      return "Pachete";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorRomanian::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1368 of file translator_ro.h.
    {
      return "Tipuri n pachet";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorRomanian::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1368 of file translator_ro.h.
    {
      return "Tipuri n pachet";
    }
trPage() [1/2]
virtual QCString TranslatorRomanian::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1248 of file translator_ro.h.
    {
      QCString result((first_capital ? "Pagin" : "pagin"));
    result+= singular ? "a":"ile";
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorRomanian::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1248 of file translator_ro.h.
    {
      QCString result((first_capital ? "Pagin" : "pagin"));
    result+= singular ? "a":"ile";
      return result;
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorRomanian::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 804 of file translator_ro.h.
    { return "pg."; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorRomanian::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 804 of file translator_ro.h.
    { return "pg."; }
trPageIndex() [1/2]
virtual QCString TranslatorRomanian::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 895 of file translator_ro.h.
    {
      return "Indexul Paginilor";
    }
trPageIndex() [2/2]
virtual QCString TranslatorRomanian::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 895 of file translator_ro.h.
    {
      return "Indexul Paginilor";
    }
trPanelSynchronisationTooltip() [1/2]
virtual QCString TranslatorRomanian::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1917 of file translator_ro.h.
    {
      QCString opt = enable ? "activa" : "dezactiva";
      return "apas click pentru a "+opt+" sincronizarea panourilor";
    }
trPanelSynchronisationTooltip() [2/2]
virtual QCString TranslatorRomanian::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1917 of file translator_ro.h.
    {
      QCString opt = enable ? "activa" : "dezactiva";
      return "apas click pentru a "+opt+" sincronizarea panourilor";
    }
trParameters() [1/2]
virtual QCString TranslatorRomanian::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 556 of file translator_ro.h.
    { return "Parametri"; }
trParameters() [2/2]
virtual QCString TranslatorRomanian::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 556 of file translator_ro.h.
    { return "Parametri"; }
trPostcondition() [1/2]
virtual QCString TranslatorRomanian::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 864 of file translator_ro.h.
    {
      return "Postcondiie";
    }
trPostcondition() [2/2]
virtual QCString TranslatorRomanian::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 864 of file translator_ro.h.
    {
      return "Postcondiie";
    }
trPrecondition() [1/2]
virtual QCString TranslatorRomanian::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 859 of file translator_ro.h.
    {
      return "Precondiie";
    }
trPrecondition() [2/2]
virtual QCString TranslatorRomanian::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 859 of file translator_ro.h.
    {
      return "Precondiie";
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorRomanian::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 944 of file translator_ro.h.
    {
      return "Atribute Private";
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorRomanian::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 944 of file translator_ro.h.
    {
      return "Atribute Private";
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorRomanian::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 657 of file translator_ro.h.
    { return "Metode Private"; }
trPrivateMembers() [2/2]
virtual QCString TranslatorRomanian::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 657 of file translator_ro.h.
    { return "Metode Private"; }
trPrivateSlots() [1/2]
virtual QCString TranslatorRomanian::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 659 of file translator_ro.h.
    { return "Conectori (slots) Privai"; }
trPrivateSlots() [2/2]
virtual QCString TranslatorRomanian::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 659 of file translator_ro.h.
    { return "Conectori (slots) Privai"; }
trPrivateTypes() [1/2]
virtual QCString TranslatorRomanian::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 940 of file translator_ro.h.
    {
      return "Tipuri Private";
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorRomanian::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 940 of file translator_ro.h.
    {
      return "Tipuri Private";
    }
trProperties() [1/2]
virtual QCString TranslatorRomanian::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1089 of file translator_ro.h.
    {
      return "Proprieti";
    }
trProperties() [2/2]
virtual QCString TranslatorRomanian::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1089 of file translator_ro.h.
    {
      return "Proprieti";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorRomanian::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1094 of file translator_ro.h.
    {
      return "Documentaia Proprietilor";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorRomanian::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1094 of file translator_ro.h.
    {
      return "Documentaia Proprietilor";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorRomanian::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 932 of file translator_ro.h.
    {
      return "Atribute Protejate";
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorRomanian::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 932 of file translator_ro.h.
    {
      return "Atribute Protejate";
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorRomanian::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 651 of file translator_ro.h.
    { return "Metode Protejate"; }
trProtectedMembers() [2/2]
virtual QCString TranslatorRomanian::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 651 of file translator_ro.h.
    { return "Metode Protejate"; }
trProtectedSlots() [1/2]
virtual QCString TranslatorRomanian::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 653 of file translator_ro.h.
    { return "Conectori (slots) Protejai"; }
trProtectedSlots() [2/2]
virtual QCString TranslatorRomanian::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 653 of file translator_ro.h.
    { return "Conectori (slots) Protejai"; }
trProtectedTypes() [1/2]
virtual QCString TranslatorRomanian::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 928 of file translator_ro.h.
    {
      return "Tipuri Protejate";
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorRomanian::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 928 of file translator_ro.h.
    {
      return "Tipuri Protejate";
    }
trProvidedByCategory() [1/2]
virtual QCString TranslatorRomanian::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1927 of file translator_ro.h.
    {
      return "Furnizat de categoria @0.";
    }
trProvidedByCategory() [2/2]
virtual QCString TranslatorRomanian::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1927 of file translator_ro.h.
    {
      return "Furnizat de categoria @0.";
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorRomanian::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 912 of file translator_ro.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Cmpuri de Date";
      }
      else
      {
        return "Atribute Publice";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorRomanian::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 912 of file translator_ro.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Cmpuri de Date";
      }
      else
      {
        return "Atribute Publice";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorRomanian::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 643 of file translator_ro.h.
    { return "Metode Publice"; }
trPublicMembers() [2/2]
virtual QCString TranslatorRomanian::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 643 of file translator_ro.h.
    { return "Metode Publice"; }
trPublicSlots() [1/2]
virtual QCString TranslatorRomanian::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 645 of file translator_ro.h.
    { return "Conectori (slots) Publici"; }
trPublicSlots() [2/2]
virtual QCString TranslatorRomanian::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 645 of file translator_ro.h.
    { return "Conectori (slots) Publici"; }
trPublicTypes() [1/2]
virtual QCString TranslatorRomanian::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 908 of file translator_ro.h.
    {
      return "Tipuri Publice";
    }
trPublicTypes() [2/2]
virtual QCString TranslatorRomanian::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 908 of file translator_ro.h.
    {
      return "Tipuri Publice";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorRomanian::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 972 of file translator_ro.h.
    {
      return "Semnalat de";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorRomanian::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 972 of file translator_ro.h.
    {
      return "Semnalat de";
    }
trReferenceManual() [1/2]
virtual QCString TranslatorRomanian::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 433 of file translator_ro.h.
    { return "Manual de utilizare"; }
trReferenceManual() [2/2]
virtual QCString TranslatorRomanian::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 433 of file translator_ro.h.
    { return "Manual de utilizare"; }
trReferences() [1/2]
virtual QCString TranslatorRomanian::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1296 of file translator_ro.h.
    {
      return "Referine";
    }
trReferences() [2/2]
virtual QCString TranslatorRomanian::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1296 of file translator_ro.h.
    {
      return "Referine";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorRomanian::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 708 of file translator_ro.h.
    {
      return "Reimplementat din "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorRomanian::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 708 of file translator_ro.h.
    {
      return "Reimplementat din "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorRomanian::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 716 of file translator_ro.h.
    {
      return "Reimplementat n "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorRomanian::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 716 of file translator_ro.h.
    {
      return "Reimplementat n "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorRomanian::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 596 of file translator_ro.h.
    { return "Documentaia funciilor prietene sau nrudite"; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorRomanian::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 596 of file translator_ro.h.
    { return "Documentaia funciilor prietene sau nrudite"; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorRomanian::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 89 of file translator_ro.h.
    { return "Funcii nrudite"; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorRomanian::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 89 of file translator_ro.h.
    { return "Funcii nrudite"; }
trRelatedPages() [1/2]
virtual QCString TranslatorRomanian::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 227 of file translator_ro.h.
    { return "Pagini nrudite"; }
trRelatedPages() [2/2]
virtual QCString TranslatorRomanian::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 227 of file translator_ro.h.
    { return "Pagini nrudite"; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorRomanian::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 346 of file translator_ro.h.
    { return "Lista tuturor documentaiilor nrudite:"; }
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorRomanian::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 346 of file translator_ro.h.
    { return "Lista tuturor documentaiilor nrudite:"; }
trRelatedSubscript() [1/2]
virtual QCString TranslatorRomanian::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 93 of file translator_ro.h.
    { return "(Atenie: acestea nu sunt funcii membre.)"; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorRomanian::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 93 of file translator_ro.h.
    { return "(Atenie: acestea nu sunt funcii membre.)"; }
trRemarks() [1/2]
virtual QCString TranslatorRomanian::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 976 of file translator_ro.h.
    {
      return "Observaii";
    }
trRemarks() [2/2]
virtual QCString TranslatorRomanian::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 976 of file translator_ro.h.
    {
      return "Observaii";
    }
trReturns() [1/2]
virtual QCString TranslatorRomanian::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 548 of file translator_ro.h.
    { return "ntoarce"; }
trReturns() [2/2]
virtual QCString TranslatorRomanian::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 548 of file translator_ro.h.
    { return "ntoarce"; }
trReturnValues() [1/2]
virtual QCString TranslatorRomanian::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 793 of file translator_ro.h.
    { return "Valori returnate"; }
trReturnValues() [2/2]
virtual QCString TranslatorRomanian::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 793 of file translator_ro.h.
    { return "Valori returnate"; }
trRTFansicp() [1/2]
virtual QCString TranslatorRomanian::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1180 of file translator_ro.h.
    {
      return "1250"; //EASTEUROPE_CHARSET
    }
trRTFansicp() [2/2]
virtual QCString TranslatorRomanian::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1180 of file translator_ro.h.
    {
      return "1250"; //EASTEUROPE_CHARSET
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorRomanian::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1189 of file translator_ro.h.
    {
      return "238";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorRomanian::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1189 of file translator_ro.h.
    {
      return "238";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorRomanian::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1195 of file translator_ro.h.
    {
      return "Index";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorRomanian::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1195 of file translator_ro.h.
    {
      return "Index";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorRomanian::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1328 of file translator_ro.h.
    {
      return "Cuprins";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorRomanian::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1328 of file translator_ro.h.
    {
      return "Cuprins";
    }
trSearch() [1/2]
virtual QCString TranslatorRomanian::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 235 of file translator_ro.h.
    { return "Caut"; }
trSearch() [2/2]
virtual QCString TranslatorRomanian::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 235 of file translator_ro.h.
    { return "Caut"; }
trSearching() [1/2]
virtual QCString TranslatorRomanian::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1772 of file translator_ro.h.
    {
      return "Cutare...";
    }
trSearching() [2/2]
virtual QCString TranslatorRomanian::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1772 of file translator_ro.h.
    {
      return "Cutare...";
    }
trSearchMatches() [1/2]
virtual QCString TranslatorRomanian::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1460 of file translator_ro.h.
    {
      return "Gsite:";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorRomanian::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1460 of file translator_ro.h.
    {
      return "Gsite:";
    }
trSearchResults() [1/2]
virtual QCString TranslatorRomanian::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1441 of file translator_ro.h.
    {
      if (numDocuments==0)
      {
        return "Din pcate nu am gsit nici un document care s corespund cererii.";
      }
      else if (numDocuments==1)
      {
        return "Am gsit <b>1</b> document corespunznd cererii.";
      }
      else
      {
        return "Am gsit <b>$num</b> documente corespunznd cererii. "
               "Lista documentelor gsite, sortate dup relevan.";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorRomanian::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1441 of file translator_ro.h.
    {
      if (numDocuments==0)
      {
        return "Din pcate nu am gsit nici un document care s corespund cererii.";
      }
      else if (numDocuments==1)
      {
        return "Am gsit <b>1</b> document corespunznd cererii.";
      }
      else
      {
        return "Am gsit <b>$num</b> documente corespunznd cererii. "
               "Lista documentelor gsite, sortate dup relevan.";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorRomanian::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1429 of file translator_ro.h.
    {
      return "Rezultatele cutarii";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorRomanian::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1429 of file translator_ro.h.
    {
      return "Rezultatele cutarii";
    }
trSeeAlso() [1/2]
virtual QCString TranslatorRomanian::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 552 of file translator_ro.h.
    { return "Vezi i"; }
trSeeAlso() [2/2]
virtual QCString TranslatorRomanian::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 552 of file translator_ro.h.
    { return "Vezi i"; }
trServiceGeneratedFromFiles() [1/2]
virtual QCString TranslatorRomanian::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 2002 of file translator_ro.h.
    {
      // single is true implies a single file
      QCString result="Documentaia pentru acest serviciu "
                                "a fost generat din ";
      if (single)
        result += "urmtorul fiier:";
      else
        result += "urmtoarele fiiere:";
      return result;
    }
trServiceGeneratedFromFiles() [2/2]
virtual QCString TranslatorRomanian::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 2002 of file translator_ro.h.
    {
      // single is true implies a single file
      QCString result="Documentaia pentru acest serviciu "
                                "a fost generat din ";
      if (single)
        result += "urmtorul fiier:";
      else
        result += "urmtoarele fiiere:";
      return result;
    }
trServiceReference() [1/2]
virtual QCString TranslatorRomanian::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 1988 of file translator_ro.h.
    {
      QCString result=sName;
      result+=" Referin Serviciu";
      return result;
    }
trServiceReference() [2/2]
virtual QCString TranslatorRomanian::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 1988 of file translator_ro.h.
    {
      QCString result=sName;
      result+=" Referin Serviciu";
      return result;
    }
trServices() [1/2]
virtual QCString TranslatorRomanian::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1973 of file translator_ro.h.
    { return "Servicii Incluse"; }
trServices() [2/2]
virtual QCString TranslatorRomanian::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1973 of file translator_ro.h.
    { return "Servicii Incluse"; }
trSignals() [1/2]
virtual QCString TranslatorRomanian::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 647 of file translator_ro.h.
    { return "Semnale"; }
trSignals() [2/2]
virtual QCString TranslatorRomanian::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 647 of file translator_ro.h.
    { return "Semnale"; }
trSince() [1/2]
virtual QCString TranslatorRomanian::trSince () [inline], [virtual]
Implements Translator.
Definition at line 989 of file translator_ro.h.
    {
      return "Din";
    }
trSince() [2/2]
virtual QCString TranslatorRomanian::trSince () [inline], [virtual]
Implements Translator.
Definition at line 989 of file translator_ro.h.
    {
      return "Din";
    }
trSingletonGeneratedFromFiles() [1/2]
virtual QCString TranslatorRomanian::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 2014 of file translator_ro.h.
    {
      // single is true implies a single file
      QCString result="Documentaia pentru acest singleton "
                                "a fost generat din ";
      if (single)
        result += "urmtorul fiier:";
      else
        result += "urmtoarele fiiere:";
      return result;
    }
trSingletonGeneratedFromFiles() [2/2]
virtual QCString TranslatorRomanian::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 2014 of file translator_ro.h.
    {
      // single is true implies a single file
      QCString result="Documentaia pentru acest singleton "
                                "a fost generat din ";
      if (single)
        result += "urmtorul fiier:";
      else
        result += "urmtoarele fiiere:";
      return result;
    }
trSingletonReference() [1/2]
virtual QCString TranslatorRomanian::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 1995 of file translator_ro.h.
    {
      QCString result=sName;
      result+=" Referin Singleton";
      return result;
    }
trSingletonReference() [2/2]
virtual QCString TranslatorRomanian::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 1995 of file translator_ro.h.
    {
      QCString result=sName;
      result+=" Referin Singleton";
      return result;
    }
trSourceFile() [1/2]
virtual QCString TranslatorRomanian::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1471 of file translator_ro.h.
     {
       return " Fiierul surs " + filename;
     }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorRomanian::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1471 of file translator_ro.h.
     {
       return " Fiierul surs " + filename;
     }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorRomanian::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1400 of file translator_ro.h.
    {
      return "Atribute statice n pachet";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorRomanian::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1400 of file translator_ro.h.
    {
      return "Atribute statice n pachet";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorRomanian::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1386 of file translator_ro.h.
    {
      return "Funcii statice n pachet";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorRomanian::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1386 of file translator_ro.h.
    {
      return "Funcii statice n pachet";
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorRomanian::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 948 of file translator_ro.h.
    {
      return "Atribute Statice Private";
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorRomanian::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 948 of file translator_ro.h.
    {
      return "Atribute Statice Private";
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorRomanian::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 661 of file translator_ro.h.
    { return "Metode Statice Private"; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorRomanian::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 661 of file translator_ro.h.
    { return "Metode Statice Private"; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorRomanian::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 936 of file translator_ro.h.
    {
      return "Atribute Statice Protejate";
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorRomanian::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 936 of file translator_ro.h.
    {
      return "Atribute Statice Protejate";
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorRomanian::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 655 of file translator_ro.h.
    { return "Metode Statice Protejate"; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorRomanian::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 655 of file translator_ro.h.
    { return "Metode Statice Protejate"; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorRomanian::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 924 of file translator_ro.h.
    {
      return "Atribute Statice Publice";
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorRomanian::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 924 of file translator_ro.h.
    {
      return "Atribute Statice Publice";
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorRomanian::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 649 of file translator_ro.h.
    { return "Metode Statice Publice"; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorRomanian::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 649 of file translator_ro.h.
    { return "Metode Statice Publice"; }
trSubprogram() [1/2]
virtual QCString TranslatorRomanian::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1735 of file translator_ro.h.
    {
      QCString result((first_capital ? "Subprogram" : "subprogram"));
      if (singular) result+="ul";
      else result += "ele";
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorRomanian::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1735 of file translator_ro.h.
    {
      QCString result((first_capital ? "Subprogram" : "subprogram"));
      if (singular) result+="ul";
      else result += "ele";
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorRomanian::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1608 of file translator_ro.h.
    { return "Documentaia Funciilor/Subrutinelor"; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorRomanian::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1608 of file translator_ro.h.
    { return "Documentaia Funciilor/Subrutinelor"; }
trSubprograms() [1/2]
virtual QCString TranslatorRomanian::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1602 of file translator_ro.h.
    { return "Funcii/Subrutine"; }
trSubprograms() [2/2]
virtual QCString TranslatorRomanian::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1602 of file translator_ro.h.
    { return "Funcii/Subrutine"; }
trTemplateParameters() [1/2]
virtual QCString TranslatorRomanian::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1878 of file translator_ro.h.
    { return "Parametri Template"; }
trTemplateParameters() [2/2]
virtual QCString TranslatorRomanian::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1878 of file translator_ro.h.
    { return "Parametri Template"; }
trTest() [1/2]
virtual QCString TranslatorRomanian::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1074 of file translator_ro.h.
    {
      return "Test";
    }
trTest() [2/2]
virtual QCString TranslatorRomanian::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1074 of file translator_ro.h.
    {
      return "Test";
    }
trTestList() [1/2]
virtual QCString TranslatorRomanian::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1079 of file translator_ro.h.
    {
      return "List de teste";
    }
trTestList() [2/2]
virtual QCString TranslatorRomanian::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1079 of file translator_ro.h.
    {
      return "List de teste";
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorRomanian::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 139 of file translator_ro.h.
    { return "Lista complet a membrilor din "; }
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorRomanian::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 139 of file translator_ro.h.
    { return "Lista complet a membrilor din "; }
trTodo() [1/2]
virtual QCString TranslatorRomanian::trTodo () [inline], [virtual]
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 958 of file translator_ro.h.
    {
      return "De fcut";
    }
trTodo() [2/2]
virtual QCString TranslatorRomanian::trTodo () [inline], [virtual]
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 958 of file translator_ro.h.
    {
      return "De fcut";
    }
trTodoList() [1/2]
virtual QCString TranslatorRomanian::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 963 of file translator_ro.h.
    {
      return "Lista lucrurilor de fcut";
    }
trTodoList() [2/2]
virtual QCString TranslatorRomanian::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 963 of file translator_ro.h.
    {
      return "Lista lucrurilor de fcut";
    }
trType() [1/2]
virtual QCString TranslatorRomanian::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1724 of file translator_ro.h.
    {
      QCString result((first_capital ? "Tip" : "tip"));
      if (singular) result+="ul";
      else result += "urile";
      return result;
    }
trType() [2/2]
virtual QCString TranslatorRomanian::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1724 of file translator_ro.h.
    {
      QCString result((first_capital ? "Tip" : "tip"));
      if (singular) result+="ul";
      else result += "urile";
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorRomanian::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1744 of file translator_ro.h.
    {
      return "Constrngerile de Tip";
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorRomanian::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1744 of file translator_ro.h.
    {
      return "Constrngerile de Tip";
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorRomanian::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 481 of file translator_ro.h.
    { return "Documentaia definiiilor de tipuri"; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorRomanian::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 481 of file translator_ro.h.
    { return "Documentaia definiiilor de tipuri"; }
trTypedefs() [1/2]
virtual QCString TranslatorRomanian::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 445 of file translator_ro.h.
    { return "Definiii de tipuri"; }
trTypedefs() [2/2]
virtual QCString TranslatorRomanian::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 445 of file translator_ro.h.
    { return "Definiii de tipuri"; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorRomanian::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1596 of file translator_ro.h.
    { return "Documentaia Tipurilor de Date"; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorRomanian::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1596 of file translator_ro.h.
    { return "Documentaia Tipurilor de Date"; }
trVariableDocumentation() [1/2]
virtual QCString TranslatorRomanian::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 499 of file translator_ro.h.
    { return "Documentaia variabilelor"; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorRomanian::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 499 of file translator_ro.h.
    { return "Documentaia variabilelor"; }
trVariables() [1/2]
virtual QCString TranslatorRomanian::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 463 of file translator_ro.h.
    { return "Variabile"; }
trVariables() [2/2]
virtual QCString TranslatorRomanian::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 463 of file translator_ro.h.
    { return "Variabile"; }
trVersion() [1/2]
virtual QCString TranslatorRomanian::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 540 of file translator_ro.h.
    { return "Versiunea"; }
trVersion() [2/2]
virtual QCString TranslatorRomanian::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 540 of file translator_ro.h.
    { return "Versiunea"; }
trWarning() [1/2]
virtual QCString TranslatorRomanian::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 536 of file translator_ro.h.
    { return "Atenie"; }
trWarning() [2/2]
virtual QCString TranslatorRomanian::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 536 of file translator_ro.h.
    { return "Atenie"; }
trWriteList() [1/2]
virtual QCString TranslatorRomanian::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 667 of file translator_ro.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" i ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorRomanian::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 667 of file translator_ro.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" i ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_ro.h
doxygen/src/translator_ro.h