TooltipManager Class Reference
Class that manages the tooltips for a source file.
#include <tooltip.h>
Classes
class Private
Public Member Functions
TooltipManager ()
~TooltipManager ()
void addTooltip (CodeOutputInterface &ol, const Definition *d)
void writeTooltips (CodeOutputInterface &ol)
TooltipManager ()
~TooltipManager ()
void addTooltip (CodeOutputInterface &ol, const Definition *d)
void writeTooltips (CodeOutputInterface &ol)
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Class that manages the tooltips for a source file.
Definition at line 24 of file tooltip.h.
Constructor & Destructor Documentation
TooltipManager() [1/2]
TooltipManager::TooltipManager ()
Definition at line 39 of file tooltip.cpp.
                               : p(std::make_unique<Private>())
{
}
 TooltipManager() [1/2]
TooltipManager::~TooltipManager ()
Definition at line 43 of file tooltip.cpp.
{
}
TooltipManager() [2/2]
TooltipManager::TooltipManager ()
 TooltipManager() [2/2]
TooltipManager::~TooltipManager ()
Member Function Documentation
addTooltip() [1/2]
void TooltipManager::addTooltip (CodeOutputInterface & ol, const Definition * d)
add a tooltip for a given symbol definition
Definition at line 54 of file tooltip.cpp.
{
  bool sourceTooltips = Config_getBool(SOURCE_TOOLTIPS);
  if (!sourceTooltips) return;
  QCString id = d->getOutputFileBase();
  int i=id.findRev('/');
  if (i!=-1)
  {
    id = id.right(id.length()-i-1); // strip path (for CREATE_SUBDIRS=YES)
  }
  // In case an extension is present translate this extension to something understood by the tooltip handler
  // otherwise extend t with a translated htmlFileExtension.
  QCString currentExtension = getFileNameExtension(id);
  if (currentExtension.isEmpty())
  {
    id += escapeId(Doxygen::htmlFileExtension);
  }
  else
  {
    id = stripExtensionGeneral(id,currentExtension) + escapeId(currentExtension);
  }
  QCString anc = d->anchor();
  if (!anc.isEmpty())
  {
    id+="_"+anc;
  }
  id = "a" + id;
  p->tooltipInfo.insert(std::make_pair(id.str(),d));
  //printf("%p: addTooltip(%s) ol=%d\n",this,id.data(),ol.id());
}
References Definition::anchor(), Config_getBool, escapeId(), QCString::findRev(), getFileNameExtension(), Definition::getOutputFileBase(), Doxygen::htmlFileExtension, id, QCString::isEmpty(), p, and stripExtensionGeneral().
addTooltip() [2/2]
void TooltipManager::addTooltip (CodeOutputInterface & ol, const Definition * d)
add a tooltip for a given symbol definition
writeTooltips() [1/2]
void TooltipManager::writeTooltips (CodeOutputInterface & ol)
write the list of all collected tooltip to the given outputs
Definition at line 87 of file tooltip.cpp.
{
  int id = ol.id();
  std::unordered_map<int, std::set<std::string> >::iterator it;
  // critical section
  {
    std::lock_guard<std::mutex> lock(g_tooltipsMutex);
    it = g_tooltipsWrittenPerFile.find(id);
    if (it==g_tooltipsWrittenPerFile.end()) // new file
    {
      it = g_tooltipsWrittenPerFile.insert(std::make_pair(id,std::set<std::string>())).first;
    }
  }
  for (const auto &kv : p->tooltipInfo)
  {
    bool written = it->second.find(kv.first)!=it->second.end();
    if (!written) // only write tooltips once
    {
      //printf("%p: writeTooltips(%s) ol=%d\n",this,kv.first.c_str(),ol.id());
      const Definition *d = kv.second;
      DocLinkInfo docInfo;
      docInfo.name = d->qualifiedName();
      docInfo.ref = d->getReference();
      docInfo.url = d->getOutputFileBase();
      docInfo.anchor = d->anchor();
      SourceLinkInfo defInfo;
      if (d->getBodyDef() && d->getStartBodyLine()!=-1)
      {
        defInfo.file = d->getBodyDef()->name();
        defInfo.line = d->getStartBodyLine();
        defInfo.url = d->getSourceFileBase();
        defInfo.anchor = d->getSourceAnchor();
      }
      SourceLinkInfo declInfo; // TODO: fill in...
      QCString decl;
      if (d->definitionType()==Definition::TypeMember)
      {
        const MemberDef *md = toMemberDef(d);
        if (!md->isAnonymous())
        {
          decl = md->declaration();
        }
      }
      ol.writeTooltip(kv.first.c_str(), // id
          docInfo, // symName
          decl, // decl
          d->briefDescriptionAsTooltip(), // desc
          defInfo,
          declInfo
          );
      it->second.insert(kv.first); // remember we wrote this tooltip for the given file id
    }
  }
}
References Definition::anchor(), DocLinkInfo::anchor, SourceLinkInfo::anchor, Definition::briefDescriptionAsTooltip(), MemberDef::declaration(), Definition::definitionType(), SourceLinkInfo::file, g_tooltipsMutex, g_tooltipsWrittenPerFile, Definition::getBodyDef(), Definition::getOutputFileBase(), Definition::getReference(), Definition::getSourceAnchor(), Definition::getSourceFileBase(), Definition::getStartBodyLine(), CodeOutputInterface::id(), Definition::isAnonymous(), SourceLinkInfo::line, FileDef::name(), DocLinkInfo::name, p, Definition::qualifiedName(), DocLinkInfo::ref, toMemberDef(), Definition::TypeMember, DocLinkInfo::url, SourceLinkInfo::url, and CodeOutputInterface::writeTooltip().
writeTooltips() [2/2]
void TooltipManager::writeTooltips (CodeOutputInterface & ol)
write the list of all collected tooltip to the given outputs
Member Data Documentation
p
std::unique_ptr< Private > TooltipManager::p [private]
Definition at line 38 of file tooltip.h.
Referenced by addTooltip(), and writeTooltips().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/tooltip.h
doxygen/src/tooltip.h
doxygen/build/doxygen/src/tooltip.cpp
doxygen/src/tooltip.cpp