TranslatorKorean Class Reference
#include <translator_kr.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString latexCommandName ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual bool needsPunctuation ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool, bool singular)
virtual QCString trFile (bool, bool singular)
virtual QCString trNamespace (bool, bool singular)
virtual QCString trGroup (bool, bool singular)
virtual QCString trPage (bool, bool singular)
virtual QCString trMember (bool, bool singular)
virtual QCString trGlobal (bool, bool singular)
virtual QCString trAuthor (bool, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool, bool singular)
virtual QCString trSubprogram (bool, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString latexCommandName ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual bool needsPunctuation ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool, bool singular)
virtual QCString trFile (bool, bool singular)
virtual QCString trNamespace (bool, bool singular)
virtual QCString trGroup (bool, bool singular)
virtual QCString trPage (bool, bool singular)
virtual QCString trMember (bool, bool singular)
virtual QCString trGlobal (bool, bool singular)
virtual QCString trAuthor (bool, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool, bool singular)
virtual QCString trSubprogram (bool, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
Additional Inherited Members
Detailed Description
When defining a translator class for the new language, follow the description in the documentation. One of the steps says that you should copy the translator_en.h (this) file to your translator_xx.h new file. Your new language should use the Translator class as the base class. This means that you need to implement exactly the same (pure virtual) methods as the TranslatorEnglish does. Because of this, it is a good idea to start with the copy of TranslatorEnglish and replace the strings one by one.
It is not necessary to include `translator.h` or `translator_adapter.h` here. The files are included in the language.cpp correctly. Not including any of the mentioned files frees the maintainer from thinking about whether the first, the second, or both files should be included or not, and why. This holds namely for localized translators because their base class is changed occasionally to adapter classes when the Translator class changes the interface, or back to the Translator class (by the local maintainer) when the localized translator is made up-to-date again.
Definition at line 51 of file translator_kr.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorKorean::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 101 of file translator_kr.h.
    {
      return "0x412 Korean";
    }
getLanguageString() [2/2]
virtual QCString TranslatorKorean::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 101 of file translator_kr.h.
    {
      return "0x412 Korean";
    }
idLanguage() [1/2]
virtual QCString TranslatorKorean::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 63 of file translator_kr.h.
    { return "korean"; }
idLanguage() [2/2]
virtual QCString TranslatorKorean::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 63 of file translator_kr.h.
    { return "korean"; }
latexCommandName() [1/2]
virtual QCString TranslatorKorean::latexCommandName () [inline], [virtual]
Set the name to be used as latex command.
Reimplemented from Translator.
Definition at line 87 of file translator_kr.h.
    {
      QCString latex_command = Config_getString(LATEX_CMD_NAME);
      if (latex_command.isEmpty()) latex_command = "latex";
      if (Config_getBool(USE_PDFLATEX))
      {
        if (latex_command == "latex") latex_command = "xelatex";
      }
      return latex_command;
    }
References Config_getBool, Config_getString, and QCString::isEmpty().
latexCommandName() [2/2]
virtual QCString TranslatorKorean::latexCommandName () [inline], [virtual]
Set the name to be used as latex command.
Reimplemented from Translator.
Definition at line 87 of file translator_kr.h.
    {
      QCString latex_command = Config_getString(LATEX_CMD_NAME);
      if (latex_command.isEmpty()) latex_command = "latex";
      if (Config_getBool(USE_PDFLATEX))
      {
        if (latex_command == "latex") latex_command = "xelatex";
      }
      return latex_command;
    }
References Config_getBool, Config_getString, and QCString::isEmpty().
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorKorean::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 80 of file translator_kr.h.
    {
      // I'm not sure what this should be.
      // When I figure it out, I'll update this.
      // see http://www.ktug.or.kr/jsboard/read.php?table=operate&no=4422&page=1
      return "\\usepackage{kotex}\n";
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorKorean::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 80 of file translator_kr.h.
    {
      // I'm not sure what this should be.
      // When I figure it out, I'll update this.
      // see http://www.ktug.or.kr/jsboard/read.php?table=operate&no=4422&page=1
      return "\\usepackage{kotex}\n";
    }
needsPunctuation() [1/2]
virtual bool TranslatorKorean::needsPunctuation () [inline], [virtual]
add punctuation at the end of a brief description when needed and supported by the language
Reimplemented from Translator.
Definition at line 105 of file translator_kr.h.
    {
      return false;
    }
needsPunctuation() [2/2]
virtual bool TranslatorKorean::needsPunctuation () [inline], [virtual]
add punctuation at the end of a brief description when needed and supported by the language
Reimplemented from Translator.
Definition at line 105 of file translator_kr.h.
    {
      return false;
    }
trAdditionalInheritedMembers() [1/2]
virtual QCString TranslatorKorean::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1905 of file translator_kr.h.
    { return " "; }
trAdditionalInheritedMembers() [2/2]
virtual QCString TranslatorKorean::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1905 of file translator_kr.h.
    { return " "; }
trAll() [1/2]
virtual QCString TranslatorKorean::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1420 of file translator_kr.h.
    {
      return "";
    }
trAll() [2/2]
virtual QCString TranslatorKorean::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1420 of file translator_kr.h.
    {
      return "";
    }
trAndMore() [1/2]
virtual QCString TranslatorKorean::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1885 of file translator_kr.h.
    { return QCString(" ")+number+" ..."; }
trAndMore() [2/2]
virtual QCString TranslatorKorean::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1885 of file translator_kr.h.
    { return QCString(" ")+number+" ..."; }
trAttention() [1/2]
virtual QCString TranslatorKorean::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 990 of file translator_kr.h.
    {
        return "";
    }
trAttention() [2/2]
virtual QCString TranslatorKorean::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 990 of file translator_kr.h.
    {
        return "";
    }
trAuthor() [1/2]
virtual QCString TranslatorKorean::trAuthor (bool , bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1291 of file translator_kr.h.
    {
      QCString result("");
      if (!singular) result+="";
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorKorean::trAuthor (bool , bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1291 of file translator_kr.h.
    {
      QCString result("");
      if (!singular) result+="";
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorKorean::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1149 of file translator_kr.h.
    {
      return "";
    }
trBug() [2/2]
virtual QCString TranslatorKorean::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1149 of file translator_kr.h.
    {
      return "";
    }
trBugList() [1/2]
virtual QCString TranslatorKorean::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1154 of file translator_kr.h.
    {
      return " ";
    }
trBugList() [2/2]
virtual QCString TranslatorKorean::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1154 of file translator_kr.h.
    {
      return " ";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorKorean::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1540 of file translator_kr.h.
    {
      return " .:";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorKorean::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1540 of file translator_kr.h.
    {
      return " .:";
    }
trCallGraph() [1/2]
virtual QCString TranslatorKorean::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1425 of file translator_kr.h.
    {
      return " .:";
    }
trCallGraph() [2/2]
virtual QCString TranslatorKorean::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1425 of file translator_kr.h.
    {
      return " .:";
    }
trCiteReferences() [1/2]
virtual QCString TranslatorKorean::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1861 of file translator_kr.h.
    { return " "; }
trCiteReferences() [2/2]
virtual QCString TranslatorKorean::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1861 of file translator_kr.h.
    { return " "; }
trClass() [1/2]
virtual QCString TranslatorKorean::trClass (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1212 of file translator_kr.h.
    {
      QCString result("");
      if (!singular) result+="";
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorKorean::trClass (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1212 of file translator_kr.h.
    {
      QCString result("");
      if (!singular) result+="";
      return result;
    }
trClassDiagram() [1/2]
virtual QCString TranslatorKorean::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 542 of file translator_kr.h.
    {
      return clName+" : ";
    }
trClassDiagram() [2/2]
virtual QCString TranslatorKorean::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 542 of file translator_kr.h.
    {
      return clName+" : ";
    }
trClassDocumentation() [1/2]
virtual QCString TranslatorKorean::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 417 of file translator_kr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return " ";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorKorean::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 417 of file translator_kr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return " ";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorKorean::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1112 of file translator_kr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorKorean::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1112 of file translator_kr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorKorean::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 199 of file translator_kr.h.
    { return " "; }
trClassHierarchy() [2/2]
virtual QCString TranslatorKorean::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 199 of file translator_kr.h.
    { return " "; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorKorean::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 258 of file translator_kr.h.
    { return " .:";
    }
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorKorean::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 258 of file translator_kr.h.
    { return " .:";
    }
trClassMethods() [1/2]
virtual QCString TranslatorKorean::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1943 of file translator_kr.h.
    {
      return " ";
    }
trClassMethods() [2/2]
virtual QCString TranslatorKorean::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1943 of file translator_kr.h.
    {
      return " ";
    }
trCode() [1/2]
virtual QCString TranslatorKorean::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 890 of file translator_kr.h.
    {
      return "";
    }
trCode() [2/2]
virtual QCString TranslatorKorean::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 890 of file translator_kr.h.
    {
      return "";
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorKorean::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 845 of file translator_kr.h.
    {
      return clName+" :";
    }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorKorean::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 845 of file translator_kr.h.
    {
      return clName+" :";
    }
trCompoundIndex() [1/2]
virtual QCString TranslatorKorean::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 390 of file translator_kr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorKorean::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 390 of file translator_kr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorKorean::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1596 of file translator_kr.h.
    { return " "; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorKorean::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1596 of file translator_kr.h.
    { return " "; }
trCompoundList() [1/2]
virtual QCString TranslatorKorean::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 203 of file translator_kr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorKorean::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 203 of file translator_kr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorKorean::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 272 of file translator_kr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " . () :";
      }
      else
      {
        return " , , . "
               "() :";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorKorean::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 272 of file translator_kr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " . () :";
      }
      else
      {
        return " , , . "
               "() :";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorKorean::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1568 of file translator_kr.h.
    { return " .:"; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorKorean::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1568 of file translator_kr.h.
    { return " .:"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorKorean::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1560 of file translator_kr.h.
    { return " "; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorKorean::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1560 of file translator_kr.h.
    { return " "; }
trCompoundMembers() [1/2]
virtual QCString TranslatorKorean::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 220 of file translator_kr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorKorean::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 220 of file translator_kr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorKorean::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 287 of file translator_kr.h.
    {
      QCString result=" ";
      if (!extractAll)
      {
        result+=" ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+=" ";
      }
      else
      {
        result+=" ";
      }
      result+=" . ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+=" "
          " . :";
        }
        else
        {
          result+=" "
          " . :";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+=" "
          " . :";
        }
        else
        {
          result+=" "
          " . :";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorKorean::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 287 of file translator_kr.h.
    {
      QCString result=" ";
      if (!extractAll)
      {
        result+=" ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+=" ";
      }
      else
      {
        result+=" ";
      }
      result+=" . ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+=" "
          " . :";
        }
        else
        {
          result+=" "
          " . :";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+=" "
          " . :";
        }
        else
        {
          result+=" "
          " . :";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorKorean::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1572 of file translator_kr.h.
    {
      QCString result=" ";
      if (!extractAll)
      {
        result+=" ";
      }
      result+=" . ";
      result+=" ";
      if (!extractAll)
      {
         result+=" .";
      }
      else
      {
         result+=" . :";
      }
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorKorean::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1572 of file translator_kr.h.
    {
      QCString result=" ";
      if (!extractAll)
      {
        result+=" ";
      }
      result+=" . ";
      result+=" ";
      if (!extractAll)
      {
         result+=" .";
      }
      else
      {
         result+=" . :";
      }
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorKorean::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1564 of file translator_kr.h.
    { return " "; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorKorean::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1564 of file translator_kr.h.
    { return " "; }
trCompoundReference() [1/2]
virtual QCString TranslatorKorean::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 617 of file translator_kr.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      if (isTemplate) result+=" ";
      result+=" ";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorKorean::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 617 of file translator_kr.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      if (isTemplate) result+=" ";
      result+=" ";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorKorean::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1637 of file translator_kr.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      if (isTemplate) result+=" ";
      result+=" ";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorKorean::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1637 of file translator_kr.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      if (isTemplate) result+=" ";
      result+=" ";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorKorean::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 518 of file translator_kr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorKorean::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 518 of file translator_kr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trConstantGroupReference() [1/2]
virtual QCString TranslatorKorean::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1980 of file translator_kr.h.
    {
      QCString result=namespaceName;
      result+=" ";
      return result;
    }
trConstantGroupReference() [2/2]
virtual QCString TranslatorKorean::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1980 of file translator_kr.h.
    {
      QCString result=namespaceName;
      result+=" ";
      return result;
    }
trConstantGroups() [1/2]
virtual QCString TranslatorKorean::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1976 of file translator_kr.h.
    { return " "; }
trConstantGroups() [2/2]
virtual QCString TranslatorKorean::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1976 of file translator_kr.h.
    { return " "; }
trConstructorDocumentation() [1/2]
virtual QCString TranslatorKorean::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 855 of file translator_kr.h.
    {
      return " & ";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorKorean::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 855 of file translator_kr.h.
    {
      return " & ";
    }
trCopyright() [1/2]
virtual QCString TranslatorKorean::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1865 of file translator_kr.h.
    { return "Copyright"; }
trCopyright() [2/2]
virtual QCString TranslatorKorean::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1865 of file translator_kr.h.
    { return "Copyright"; }
trDataTypes() [1/2]
virtual QCString TranslatorKorean::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1620 of file translator_kr.h.
    { return " "; }
trDataTypes() [2/2]
virtual QCString TranslatorKorean::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1620 of file translator_kr.h.
    { return " "; }
trDate() [1/2]
virtual QCString TranslatorKorean::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 556 of file translator_kr.h.
    { return ""; }
trDate() [2/2]
virtual QCString TranslatorKorean::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 556 of file translator_kr.h.
    { return ""; }
trDateTime() [1/2]
virtual QCString TranslatorKorean::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1820 of file translator_kr.h.
    {
      static const char *days[] = { "","","","","","","" };
      static const char *months[] = { "1","2","3","4","5","6","7","8","9","10","11","12" };
      QCString sdate;
      sdate.sprintf("%s %s %d %d",days[dayOfWeek-1],months[month-1],day,year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDateTime() [2/2]
virtual QCString TranslatorKorean::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1820 of file translator_kr.h.
    {
      static const char *days[] = { "","","","","","","" };
      static const char *months[] = { "1","2","3","4","5","6","7","8","9","10","11","12" };
      QCString sdate;
      sdate.sprintf("%s %s %d %d",days[dayOfWeek-1],months[month-1],day,year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDayOfWeek() [1/2]
virtual QCString TranslatorKorean::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1836 of file translator_kr.h.
    {
      static const char *days_short[] = { "", "", "", "", "", "", "" };
      static const char *days_full[] = { "", "", "", "", "", "", "" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      return text;
    }
trDayOfWeek() [2/2]
virtual QCString TranslatorKorean::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1836 of file translator_kr.h.
    {
      static const char *days_short[] = { "", "", "", "", "", "", "" };
      static const char *days_full[] = { "", "", "", "", "", "", "" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      return text;
    }
trDayPeriod() [1/2]
virtual QCString TranslatorKorean::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1850 of file translator_kr.h.
    {
      static const char *dayPeriod[] = { "", "" };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorKorean::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1850 of file translator_kr.h.
    {
      static const char *dayPeriod[] = { "", "" };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorKorean::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 822 of file translator_kr.h.
    {
      return "@1 @0 .";
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorKorean::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 822 of file translator_kr.h.
    {
      return "@1 @0 .";
    }
trDefinedIn() [1/2]
virtual QCString TranslatorKorean::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 187 of file translator_kr.h.
    { return " :"; }
trDefinedIn() [2/2]
virtual QCString TranslatorKorean::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 187 of file translator_kr.h.
    { return " :"; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorKorean::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 826 of file translator_kr.h.
    {
      return "@0 .";
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorKorean::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 826 of file translator_kr.h.
    {
      return "@0 .";
    }
trDefineDocumentation() [1/2]
virtual QCString TranslatorKorean::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 488 of file translator_kr.h.
    { return " "; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorKorean::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 488 of file translator_kr.h.
    { return " "; }
trDefines() [1/2]
virtual QCString TranslatorKorean::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 452 of file translator_kr.h.
    { return ""; }
trDefines() [2/2]
virtual QCString TranslatorKorean::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 452 of file translator_kr.h.
    { return ""; }
trDefineValue() [1/2]
virtual QCString TranslatorKorean::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1139 of file translator_kr.h.
    {
      return ":";
    }
trDefineValue() [2/2]
virtual QCString TranslatorKorean::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1139 of file translator_kr.h.
    {
      return ":";
    }
trDeprecated() [1/2]
virtual QCString TranslatorKorean::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 835 of file translator_kr.h.
    {
      return " ";
    }
trDeprecated() [2/2]
virtual QCString TranslatorKorean::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 835 of file translator_kr.h.
    {
      return " ";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorKorean::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1348 of file translator_kr.h.
    {
      return " ";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorKorean::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1348 of file translator_kr.h.
    {
      return " ";
    }
trDetailedDescription() [1/2]
virtual QCString TranslatorKorean::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 120 of file translator_kr.h.
    { return " "; }
trDetailedDescription() [2/2]
virtual QCString TranslatorKorean::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 120 of file translator_kr.h.
    { return " "; }
trDetailLevel() [1/2]
virtual QCString TranslatorKorean::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1877 of file translator_kr.h.
    { return " "; }
trDetailLevel() [2/2]
virtual QCString TranslatorKorean::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1877 of file translator_kr.h.
    { return " "; }
trDir() [1/2]
virtual QCString TranslatorKorean::trDir (bool , bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1515 of file translator_kr.h.
    {
      QCString result("");
      if (singular) result+=""; else result+="";
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorKorean::trDir (bool , bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1515 of file translator_kr.h.
    {
      QCString result("");
      if (singular) result+=""; else result+="";
      return result;
    }
trDirDepGraph() [1/2]
virtual QCString TranslatorKorean::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1869 of file translator_kr.h.
    { return QCString(name) + QCString(" :"); }
References setup::name.
trDirDepGraph() [2/2]
virtual QCString TranslatorKorean::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1869 of file translator_kr.h.
    { return QCString(name) + QCString(" :"); }
References setup::name.
trDirDocumentation() [1/2]
virtual QCString TranslatorKorean::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1497 of file translator_kr.h.
    { return " "; }
trDirDocumentation() [2/2]
virtual QCString TranslatorKorean::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1497 of file translator_kr.h.
    { return " "; }
trDirectories() [1/2]
virtual QCString TranslatorKorean::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1503 of file translator_kr.h.
    { return ""; }
trDirectories() [2/2]
virtual QCString TranslatorKorean::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1503 of file translator_kr.h.
    { return ""; }
trDirIndex() [1/2]
virtual QCString TranslatorKorean::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1491 of file translator_kr.h.
    { return " "; }
trDirIndex() [2/2]
virtual QCString TranslatorKorean::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1491 of file translator_kr.h.
    { return " "; }
trDirReference() [1/2]
virtual QCString TranslatorKorean::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1509 of file translator_kr.h.
    { QCString result=dirName; result+=" "; return result; }
trDirReference() [2/2]
virtual QCString TranslatorKorean::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1509 of file translator_kr.h.
    { QCString result=dirName; result+=" "; return result; }
trDirRelation() [1/2]
virtual QCString TranslatorKorean::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1759 of file translator_kr.h.
    {
      return QCString(name)+" ";
    }
References setup::name.
trDirRelation() [2/2]
virtual QCString TranslatorKorean::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1759 of file translator_kr.h.
    {
      return QCString(name)+" ";
    }
References setup::name.
trDocumentation() [1/2]
virtual QCString TranslatorKorean::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 372 of file translator_kr.h.
    { return ""; }
trDocumentation() [2/2]
virtual QCString TranslatorKorean::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 372 of file translator_kr.h.
    { return ""; }
trEnumerations() [1/2]
virtual QCString TranslatorKorean::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 464 of file translator_kr.h.
    { return " "; }
trEnumerations() [2/2]
virtual QCString TranslatorKorean::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 464 of file translator_kr.h.
    { return " "; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorKorean::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 500 of file translator_kr.h.
    { return " "; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorKorean::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 500 of file translator_kr.h.
    { return " "; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorKorean::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1548 of file translator_kr.h.
    { return " "; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorKorean::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1548 of file translator_kr.h.
    { return " "; }
trEnumerationValues() [1/2]
virtual QCString TranslatorKorean::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 482 of file translator_kr.h.
    { return " "; }
trEnumerationValues() [2/2]
virtual QCString TranslatorKorean::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 482 of file translator_kr.h.
    { return " "; }
trEnumGeneratedFromFiles() [1/2]
virtual QCString TranslatorKorean::trEnumGeneratedFromFiles (bool) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1889 of file translator_kr.h.
    { QCString result = " () .:";
      return result;
    }
trEnumGeneratedFromFiles() [2/2]
virtual QCString TranslatorKorean::trEnumGeneratedFromFiles (bool) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1889 of file translator_kr.h.
    { QCString result = " () .:";
      return result;
    }
trEnumName() [1/2]
virtual QCString TranslatorKorean::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 179 of file translator_kr.h.
    { return " "; }
trEnumName() [2/2]
virtual QCString TranslatorKorean::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 179 of file translator_kr.h.
    { return " "; }
trEnumReference() [1/2]
virtual QCString TranslatorKorean::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1895 of file translator_kr.h.
    { return QCString(name)+" Enum Reference"; }
References setup::name.
trEnumReference() [2/2]
virtual QCString TranslatorKorean::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1895 of file translator_kr.h.
    { return QCString(name)+" Enum Reference"; }
References setup::name.
trEnumValue() [1/2]
virtual QCString TranslatorKorean::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 183 of file translator_kr.h.
    { return " "; }
trEnumValue() [2/2]
virtual QCString TranslatorKorean::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 183 of file translator_kr.h.
    { return " "; }
trEventDocumentation() [1/2]
virtual QCString TranslatorKorean::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1365 of file translator_kr.h.
    {
      return " ";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorKorean::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1365 of file translator_kr.h.
    {
      return " ";
    }
trEvents() [1/2]
virtual QCString TranslatorKorean::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1360 of file translator_kr.h.
    {
      return "";
    }
trEvents() [2/2]
virtual QCString TranslatorKorean::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1360 of file translator_kr.h.
    {
      return "";
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorKorean::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 442 of file translator_kr.h.
    { return " "; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorKorean::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 442 of file translator_kr.h.
    { return " "; }
trExamples() [1/2]
virtual QCString TranslatorKorean::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 250 of file translator_kr.h.
    { return ""; }
trExamples() [2/2]
virtual QCString TranslatorKorean::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 250 of file translator_kr.h.
    { return ""; }
trExamplesDescription() [1/2]
virtual QCString TranslatorKorean::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 358 of file translator_kr.h.
    { return " .:"; }
trExamplesDescription() [2/2]
virtual QCString TranslatorKorean::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 358 of file translator_kr.h.
    { return " .:"; }
trExceptions() [1/2]
virtual QCString TranslatorKorean::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 572 of file translator_kr.h.
    { return ""; }
trExceptions() [2/2]
virtual QCString TranslatorKorean::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 572 of file translator_kr.h.
    { return ""; }
trExtendsClass() [1/2]
virtual QCString TranslatorKorean::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1935 of file translator_kr.h.
    {
      return " @0 .";
    }
trExtendsClass() [2/2]
virtual QCString TranslatorKorean::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1935 of file translator_kr.h.
    {
      return " @0 .";
    }
trFile() [1/2]
virtual QCString TranslatorKorean::trFile (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1223 of file translator_kr.h.
    {
      QCString result("");
      if (!singular) result+="";
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorKorean::trFile (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1223 of file translator_kr.h.
    {
      QCString result("");
      if (!singular) result+="";
      return result;
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorKorean::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 436 of file translator_kr.h.
    { return " "; }
trFileDocumentation() [2/2]
virtual QCString TranslatorKorean::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 436 of file translator_kr.h.
    { return " "; }
trFileIn() [1/2]
virtual QCString TranslatorKorean::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1796 of file translator_kr.h.
    {
      return QCString(name) + " ";
    }
References setup::name.
trFileIn() [2/2]
virtual QCString TranslatorKorean::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1796 of file translator_kr.h.
    {
      return QCString(name) + " ";
    }
References setup::name.
trFileIndex() [1/2]
virtual QCString TranslatorKorean::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 405 of file translator_kr.h.
    { return " "; }
trFileIndex() [2/2]
virtual QCString TranslatorKorean::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 405 of file translator_kr.h.
    { return " "; }
trFileList() [1/2]
virtual QCString TranslatorKorean::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 216 of file translator_kr.h.
    { return " "; }
trFileList() [2/2]
virtual QCString TranslatorKorean::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 216 of file translator_kr.h.
    { return " "; }
trFileListDescription() [1/2]
virtual QCString TranslatorKorean::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 263 of file translator_kr.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" . () :";
      return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorKorean::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 263 of file translator_kr.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" . () :";
      return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorKorean::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 233 of file translator_kr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trFileMembers() [2/2]
virtual QCString TranslatorKorean::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 233 of file translator_kr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return " ";
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
virtual QCString TranslatorKorean::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 334 of file translator_kr.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+=" , , , , ";
      }
      else
      {
        result+=" ";
      }
      result+=" . ";
      result+=" ";
      if (extractAll)
        result+=" . :";
      else
        result+=" . :";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorKorean::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 334 of file translator_kr.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+=" , , , , ";
      }
      else
      {
        result+=" ";
      }
      result+=" . ";
      result+=" ";
      if (extractAll)
        result+=" . :";
      else
        result+=" . :";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorKorean::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 639 of file translator_kr.h.
    {
      QCString result=fileName;
      result+=" ";
      return result;
    }
trFileReference() [2/2]
virtual QCString TranslatorKorean::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 639 of file translator_kr.h.
    {
      QCString result=fileName;
      result+=" ";
      return result;
    }
trFriends() [1/2]
virtual QCString TranslatorKorean::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 599 of file translator_kr.h.
    { return "Friends"; }
trFriends() [2/2]
virtual QCString TranslatorKorean::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 599 of file translator_kr.h.
    { return "Friends"; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorKorean::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 506 of file translator_kr.h.
    { return " "; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorKorean::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 506 of file translator_kr.h.
    { return " "; }
trFunctions() [1/2]
virtual QCString TranslatorKorean::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 470 of file translator_kr.h.
    { return ""; }
trFunctions() [2/2]
virtual QCString TranslatorKorean::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 470 of file translator_kr.h.
    { return ""; }
trGeneratedAt() [1/2]
virtual QCString TranslatorKorean::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 533 of file translator_kr.h.
    {
      QCString result=" : "+date;
      if (!projName.isEmpty()) result+=", : "+projName;
      result+=", : ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorKorean::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 533 of file translator_kr.h.
    {
      QCString result=" : "+date;
      if (!projName.isEmpty()) result+=", : "+projName;
      result+=", : ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorKorean::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 171 of file translator_kr.h.
    { QCString result=" ";
      if (!s.isEmpty()) result+=s+" ";
      result+="Doxygen .";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorKorean::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 171 of file translator_kr.h.
    { QCString result=" ";
      if (!s.isEmpty()) result+=s+" ";
      result+="Doxygen .";
      return result;
    }
References s.
trGeneratedBy() [1/2]
virtual QCString TranslatorKorean::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 576 of file translator_kr.h.
    { return " : "; }
trGeneratedBy() [2/2]
virtual QCString TranslatorKorean::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 576 of file translator_kr.h.
    { return " : "; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorKorean::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 777 of file translator_kr.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result=" ";
      switch(compType)
      {
        case ClassDef::Class: result+=""; break;
        case ClassDef::Struct: result+=""; break;
        case ClassDef::Union: result+=""; break;
        case ClassDef::Interface: result+=""; break;
        case ClassDef::Protocol: result+=""; break;
        case ClassDef::Category: result+=""; break;
        case ClassDef::Exception: result+=""; break;
        default: break;
      }
      result+=" ";
      if (!single) result+="";
      result+=" .:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorKorean::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 777 of file translator_kr.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result=" ";
      switch(compType)
      {
        case ClassDef::Class: result+=""; break;
        case ClassDef::Struct: result+=""; break;
        case ClassDef::Union: result+=""; break;
        case ClassDef::Interface: result+=""; break;
        case ClassDef::Protocol: result+=""; break;
        case ClassDef::Category: result+=""; break;
        case ClassDef::Exception: result+=""; break;
        default: break;
      }
      result+=" ";
      if (!single) result+="";
      result+=" .:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorKorean::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1705 of file translator_kr.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result=" ";
      if (single) result+=""; else result+="";
      result+=" ";
      result+=" ";
      switch(compType)
      {
        case ClassDef::Class: result+=""; break;
        case ClassDef::Struct: result+=""; break;
        case ClassDef::Union: result+=""; break;
        case ClassDef::Interface: result+=""; break;
        case ClassDef::Protocol: result+=""; break;
        case ClassDef::Category: result+=""; break;
        case ClassDef::Exception: result+=""; break;
        default: break;
      }
      result+=" :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorKorean::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1705 of file translator_kr.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result=" ";
      if (single) result+=""; else result+="";
      result+=" ";
      result+=" ";
      switch(compType)
      {
        case ClassDef::Class: result+=""; break;
        case ClassDef::Struct: result+=""; break;
        case ClassDef::Union: result+=""; break;
        case ClassDef::Interface: result+=""; break;
        case ClassDef::Protocol: result+=""; break;
        case ClassDef::Category: result+=""; break;
        case ClassDef::Exception: result+=""; break;
        default: break;
      }
      result+=" :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorKorean::trGlobal (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1278 of file translator_kr.h.
    {
      QCString result("");
      if (!singular) result+="";
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorKorean::trGlobal (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1278 of file translator_kr.h.
    {
      QCString result("");
      if (!singular) result+="";
      return result;
    }
trGlobalNamespace() [1/2]
virtual QCString TranslatorKorean::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1771 of file translator_kr.h.
    {
      return " ";
    }
trGlobalNamespace() [2/2]
virtual QCString TranslatorKorean::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1771 of file translator_kr.h.
    {
      return " ";
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorKorean::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 865 of file translator_kr.h.
    {
      return " ";
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorKorean::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 865 of file translator_kr.h.
    {
      return " ";
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorKorean::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 898 of file translator_kr.h.
    {
      return " ";
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorKorean::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 898 of file translator_kr.h.
    {
      return " ";
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorKorean::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 860 of file translator_kr.h.
    {
      return " ";
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorKorean::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 860 of file translator_kr.h.
    {
      return " ";
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorKorean::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 902 of file translator_kr.h.
    {
      return " ";
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorKorean::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 902 of file translator_kr.h.
    {
      return " ";
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorKorean::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 894 of file translator_kr.h.
    {
      return " ";
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorKorean::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 894 of file translator_kr.h.
    {
      return " ";
    }
trGroup() [1/2]
virtual QCString TranslatorKorean::trGroup (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1245 of file translator_kr.h.
    {
      QCString result("");
      if (!singular) result+="";
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorKorean::trGroup (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1245 of file translator_kr.h.
    {
      QCString result("");
      if (!singular) result+="";
      return result;
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorKorean::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 384 of file translator_kr.h.
    { return " "; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorKorean::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 384 of file translator_kr.h.
    { return " "; }
trImplementedFromList() [1/2]
virtual QCString TranslatorKorean::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1316 of file translator_kr.h.
    {
      return trWriteList(numEntries)+" .";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorKorean::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1316 of file translator_kr.h.
    {
      return trWriteList(numEntries)+" .";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorKorean::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1324 of file translator_kr.h.
    {
      return trWriteList(numEntries)+" .";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorKorean::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1324 of file translator_kr.h.
    {
      return trWriteList(numEntries)+" .";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorKorean::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 994 of file translator_kr.h.
    {
      return " / include .:";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorKorean::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 994 of file translator_kr.h.
    {
      return " / include .:";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorKorean::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 850 of file translator_kr.h.
    {
      return fName+" include ";
    }
trInclDepGraph() [2/2]
virtual QCString TranslatorKorean::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 850 of file translator_kr.h.
    {
      return fName+" include ";
    }
trIncludesFileIn() [1/2]
virtual QCString TranslatorKorean::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1805 of file translator_kr.h.
    {
      return QCString(name) + " ";
    }
References setup::name.
trIncludesFileIn() [2/2]
virtual QCString TranslatorKorean::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1805 of file translator_kr.h.
    {
      return QCString(name) + " ";
    }
References setup::name.
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorKorean::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 165 of file translator_kr.h.
    { return " (.)"; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorKorean::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 165 of file translator_kr.h.
    { return " (.)"; }
trInheritedByList() [1/2]
virtual QCString TranslatorKorean::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 711 of file translator_kr.h.
    {
      return trWriteList(numEntries)+" .";
    }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorKorean::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 711 of file translator_kr.h.
    {
      return trWriteList(numEntries)+" .";
    }
References trWriteList().
trInheritedFrom() [1/2]
virtual QCString TranslatorKorean::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1899 of file translator_kr.h.
    { return QCString(what) + QCString("() ") + QCString(members); }
trInheritedFrom() [2/2]
virtual QCString TranslatorKorean::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1899 of file translator_kr.h.
    { return QCString(what) + QCString("() ") + QCString(members); }
trInheritsList() [1/2]
virtual QCString TranslatorKorean::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 703 of file translator_kr.h.
    {
      return trWriteList(numEntries)+"() .";
    }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorKorean::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 703 of file translator_kr.h.
    {
      return trWriteList(numEntries)+"() .";
    }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorKorean::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 885 of file translator_kr.h.
    {
      return ":";
    }
trInitialValue() [2/2]
virtual QCString TranslatorKorean::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 885 of file translator_kr.h.
    {
      return ":";
    }
trInstanceMethods() [1/2]
virtual QCString TranslatorKorean::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1951 of file translator_kr.h.
    {
      return " ";
    }
trInstanceMethods() [2/2]
virtual QCString TranslatorKorean::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1951 of file translator_kr.h.
    {
      return " ";
    }
trInterfaces() [1/2]
virtual QCString TranslatorKorean::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1968 of file translator_kr.h.
    { return " "; }
trInterfaces() [2/2]
virtual QCString TranslatorKorean::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1968 of file translator_kr.h.
    { return " "; }
trInvariant() [1/2]
virtual QCString TranslatorKorean::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 880 of file translator_kr.h.
    {
      return " ";
    }
trInvariant() [2/2]
virtual QCString TranslatorKorean::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 880 of file translator_kr.h.
    {
      return " ";
    }
trISOLang() [1/2]
virtual QCString TranslatorKorean::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 97 of file translator_kr.h.
    {
      return "ko";
    }
trISOLang() [2/2]
virtual QCString TranslatorKorean::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 97 of file translator_kr.h.
    {
      return "ko";
    }
trLegend() [1/2]
virtual QCString TranslatorKorean::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1072 of file translator_kr.h.
    {
      return "";
    }
trLegend() [2/2]
virtual QCString TranslatorKorean::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1072 of file translator_kr.h.
    {
      return "";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorKorean::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 1015 of file translator_kr.h.
    {
      return
        " doxygen .<p>\n"
        " .:\n"
        "\\code\n"
        "/*! */\n"
        "class Invisible { };\n\n"
        "/*! Truncated , */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* doxygen */\n"
        "class Undocumented { };\n\n"
        "/*! public */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! */\n"
        "template<class T> class Templ { };\n\n"
        "/*! protected */\n"
        "class ProtectedBase { };\n\n"
        "/*! private */\n"
        "class PrivateBase { };\n\n"
        "/*! () */\n"
        "class Used { };\n\n"
        "/*! */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        " . :"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        " . :\n"
        "<ul>\n"
        "<li>%A .\n"
        "<li>%A .\n"
        "<li>%A .\n"
        "<li>%A "
    " ."
        "%A , .\n"
        "</ul>\n"
        " . :\n"
        "<ul>\n"
        "<li>%A public .\n"
        "<li>%A protected .\n"
        "<li>%A private .\n"
        "<li>%A . "
    " () .\n"
        "<li>%A . "
    " .\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorKorean::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 1015 of file translator_kr.h.
    {
      return
        " doxygen .<p>\n"
        " .:\n"
        "\\code\n"
        "/*! */\n"
        "class Invisible { };\n\n"
        "/*! Truncated , */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* doxygen */\n"
        "class Undocumented { };\n\n"
        "/*! public */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! */\n"
        "template<class T> class Templ { };\n\n"
        "/*! protected */\n"
        "class ProtectedBase { };\n\n"
        "/*! private */\n"
        "class PrivateBase { };\n\n"
        "/*! () */\n"
        "class Used { };\n\n"
        "/*! */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        " . :"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        " . :\n"
        "<ul>\n"
        "<li>%A .\n"
        "<li>%A .\n"
        "<li>%A .\n"
        "<li>%A "
    " ."
        "%A , .\n"
        "</ul>\n"
        " . :\n"
        "<ul>\n"
        "<li>%A public .\n"
        "<li>%A protected .\n"
        "<li>%A private .\n"
        "<li>%A . "
    " () .\n"
        "<li>%A . "
    " .\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorKorean::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 1008 of file translator_kr.h.
    {
      return " ";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorKorean::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 1008 of file translator_kr.h.
    {
      return " ";
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorKorean::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 153 of file translator_kr.h.
    { return " "; }
trListOfAllMembers() [2/2]
virtual QCString TranslatorKorean::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 153 of file translator_kr.h.
    { return " "; }
trLoading() [1/2]
virtual QCString TranslatorKorean::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1765 of file translator_kr.h.
    {
      return "...";
    }
trLoading() [2/2]
virtual QCString TranslatorKorean::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1765 of file translator_kr.h.
    {
      return "...";
    }
trMainPage() [1/2]
virtual QCString TranslatorKorean::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 809 of file translator_kr.h.
    { return " "; }
trMainPage() [2/2]
virtual QCString TranslatorKorean::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 809 of file translator_kr.h.
    { return " "; }
trMember() [1/2]
virtual QCString TranslatorKorean::trMember (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1267 of file translator_kr.h.
    {
      QCString result("");
      if (!singular) result+="";
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorKorean::trMember (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1267 of file translator_kr.h.
    {
      QCString result("");
      if (!singular) result+="";
      return result;
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorKorean::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 136 of file translator_kr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
          return " ";
      }
      else
      {
          return " ";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorKorean::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 136 of file translator_kr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
          return " ";
      }
      else
      {
          return " ";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorKorean::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 128 of file translator_kr.h.
    { return " "; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorKorean::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 128 of file translator_kr.h.
    { return " "; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorKorean::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 132 of file translator_kr.h.
    { return " "; }
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorKorean::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 132 of file translator_kr.h.
    { return " "; }
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorKorean::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1556 of file translator_kr.h.
    { return " / "; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorKorean::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1556 of file translator_kr.h.
    { return " / "; }
trMemberList() [1/2]
virtual QCString TranslatorKorean::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 157 of file translator_kr.h.
    { return " "; }
trMemberList() [2/2]
virtual QCString TranslatorKorean::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 157 of file translator_kr.h.
    { return " "; }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorKorean::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 124 of file translator_kr.h.
    { return " "; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorKorean::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 124 of file translator_kr.h.
    { return " "; }
trMethodDocumentation() [1/2]
virtual QCString TranslatorKorean::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1958 of file translator_kr.h.
    {
      return " ";
    }
trMethodDocumentation() [2/2]
virtual QCString TranslatorKorean::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1958 of file translator_kr.h.
    {
      return " ";
    }
trModule() [1/2]
virtual QCString TranslatorKorean::trModule (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1696 of file translator_kr.h.
    {
      QCString result("");
      if (!singular) result+="";
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorKorean::trModule (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1696 of file translator_kr.h.
    {
      QCString result("");
      if (!singular) result+="";
      return result;
    }
trModuleDocumentation() [1/2]
virtual QCString TranslatorKorean::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 411 of file translator_kr.h.
    { return " "; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorKorean::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 411 of file translator_kr.h.
    { return " "; }
trModuleIndex() [1/2]
virtual QCString TranslatorKorean::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 378 of file translator_kr.h.
    { return " "; }
trModuleIndex() [2/2]
virtual QCString TranslatorKorean::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 378 of file translator_kr.h.
    { return " "; }
trModuleReference() [1/2]
virtual QCString TranslatorKorean::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1658 of file translator_kr.h.
    {
      QCString result=namespaceName;
      result+=" ";
      return result;
    }
trModuleReference() [2/2]
virtual QCString TranslatorKorean::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1658 of file translator_kr.h.
    {
      QCString result=namespaceName;
      result+=" ";
      return result;
    }
trModules() [1/2]
virtual QCString TranslatorKorean::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 195 of file translator_kr.h.
    { return ""; }
trModules() [2/2]
virtual QCString TranslatorKorean::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 195 of file translator_kr.h.
    { return ""; }
trModulesDescription() [1/2]
virtual QCString TranslatorKorean::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 366 of file translator_kr.h.
    { return " .:"; }
trModulesDescription() [2/2]
virtual QCString TranslatorKorean::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 366 of file translator_kr.h.
    { return " .:"; }
trModulesIndex() [1/2]
virtual QCString TranslatorKorean::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1689 of file translator_kr.h.
    { return " "; }
trModulesIndex() [2/2]
virtual QCString TranslatorKorean::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1689 of file translator_kr.h.
    { return " "; }
trModulesList() [1/2]
virtual QCString TranslatorKorean::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1624 of file translator_kr.h.
    { return " "; }
trModulesList() [2/2]
virtual QCString TranslatorKorean::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1624 of file translator_kr.h.
    { return " "; }
trModulesListDescription() [1/2]
virtual QCString TranslatorKorean::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1628 of file translator_kr.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" . () :";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorKorean::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1628 of file translator_kr.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" . () :";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorKorean::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1670 of file translator_kr.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" . ";
      if (extractAll)
      {
        result+=" . :";
      }
      else
      {
        result+=" . :";
      }
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorKorean::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1670 of file translator_kr.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" . ";
      if (extractAll)
      {
        result+=" . :";
      }
      else
      {
        result+=" . :";
      }
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorKorean::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1666 of file translator_kr.h.
    { return " "; }
trModulesMembers() [2/2]
virtual QCString TranslatorKorean::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1666 of file translator_kr.h.
    { return " "; }
trMonth() [1/2]
virtual QCString TranslatorKorean::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1843 of file translator_kr.h.
    {
      static const char *months_short[] = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" };
      static const char *months_full[] = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      return text;
    }
trMonth() [2/2]
virtual QCString TranslatorKorean::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1843 of file translator_kr.h.
    {
      static const char *months_short[] = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" };
      static const char *months_full[] = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      return text;
    }
trMore() [1/2]
virtual QCString TranslatorKorean::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 149 of file translator_kr.h.
    { return " ..."; }
trMore() [2/2]
virtual QCString TranslatorKorean::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 149 of file translator_kr.h.
    { return " ..."; }
trNamespace() [1/2]
virtual QCString TranslatorKorean::trNamespace (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1234 of file translator_kr.h.
    {
      QCString result("");
      if (!singular) result+="";
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorKorean::trNamespace (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1234 of file translator_kr.h.
    {
      QCString result("");
      if (!singular) result+="";
      return result;
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorKorean::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 757 of file translator_kr.h.
    { return " "; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorKorean::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 757 of file translator_kr.h.
    { return " "; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorKorean::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 751 of file translator_kr.h.
    { return " "; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorKorean::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 751 of file translator_kr.h.
    { return " "; }
trNamespaceList() [1/2]
virtual QCString TranslatorKorean::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 584 of file translator_kr.h.
    { return " "; }
trNamespaceList() [2/2]
virtual QCString TranslatorKorean::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 584 of file translator_kr.h.
    { return " "; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorKorean::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 588 of file translator_kr.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" . () :";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorKorean::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 588 of file translator_kr.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" . () :";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorKorean::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 737 of file translator_kr.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" . ";
      if (extractAll)
        result+=" . :";
      else
        result+=" . :";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorKorean::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 737 of file translator_kr.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" . ";
      if (extractAll)
        result+=" . :";
      else
        result+=" . :";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorKorean::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 733 of file translator_kr.h.
    { return " "; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorKorean::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 733 of file translator_kr.h.
    { return " "; }
trNamespaceReference() [1/2]
virtual QCString TranslatorKorean::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 647 of file translator_kr.h.
    {
      QCString result=namespaceName;
      result+=" ";
      return result;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorKorean::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 647 of file translator_kr.h.
    {
      QCString result=namespaceName;
      result+=" ";
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorKorean::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 767 of file translator_kr.h.
    { return ""; }
trNamespaces() [2/2]
virtual QCString TranslatorKorean::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 767 of file translator_kr.h.
    { return ""; }
trNoMatches() [1/2]
virtual QCString TranslatorKorean::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1783 of file translator_kr.h.
    {
      return " ";
    }
trNoMatches() [2/2]
virtual QCString TranslatorKorean::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1783 of file translator_kr.h.
    {
      return " ";
    }
trNote() [1/2]
virtual QCString TranslatorKorean::trNote () [inline], [virtual]
Implements Translator.
Definition at line 915 of file translator_kr.h.
    {
      return "";
    }
trNote() [2/2]
virtual QCString TranslatorKorean::trNote () [inline], [virtual]
Implements Translator.
Definition at line 915 of file translator_kr.h.
    {
      return "";
    }
trOverloadText() [1/2]
virtual QCString TranslatorKorean::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1529 of file translator_kr.h.
    {
       return " . "
              " (argument) .";
    }
trOverloadText() [2/2]
virtual QCString TranslatorKorean::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1529 of file translator_kr.h.
    {
       return " . "
              " (argument) .";
    }
trPackage() [1/2]
virtual QCString TranslatorKorean::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1124 of file translator_kr.h.
    {
      return name+" ";
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorKorean::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1124 of file translator_kr.h.
    {
      return name+" ";
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorKorean::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1401 of file translator_kr.h.
    {
      return " ";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorKorean::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1401 of file translator_kr.h.
    {
      return " ";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorKorean::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1383 of file translator_kr.h.
    {
      return " ";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorKorean::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1383 of file translator_kr.h.
    {
      return " ";
    }
trPackageListDescription() [1/2]
virtual QCString TranslatorKorean::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1129 of file translator_kr.h.
    {
      return " . () :";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorKorean::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1129 of file translator_kr.h.
    {
      return " . () :";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorKorean::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1387 of file translator_kr.h.
    {
      return " ";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorKorean::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1387 of file translator_kr.h.
    {
      return " ";
    }
trPackages() [1/2]
virtual QCString TranslatorKorean::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1134 of file translator_kr.h.
    {
      return "";
    }
trPackages() [2/2]
virtual QCString TranslatorKorean::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1134 of file translator_kr.h.
    {
      return "";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorKorean::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1376 of file translator_kr.h.
    {
      return " ";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorKorean::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1376 of file translator_kr.h.
    {
      return " ";
    }
trPage() [1/2]
virtual QCString TranslatorKorean::trPage (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1256 of file translator_kr.h.
    {
      QCString result("");
      if (!singular) result+="";
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorKorean::trPage (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1256 of file translator_kr.h.
    {
      QCString result("");
      if (!singular) result+="";
      return result;
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorKorean::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 815 of file translator_kr.h.
    { return ""; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorKorean::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 815 of file translator_kr.h.
    { return ""; }
trPageIndex() [1/2]
virtual QCString TranslatorKorean::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 906 of file translator_kr.h.
    {
      return " ";
    }
trPageIndex() [2/2]
virtual QCString TranslatorKorean::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 906 of file translator_kr.h.
    {
      return " ";
    }
trPanelSynchronisationTooltip() [1/2]
virtual QCString TranslatorKorean::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1916 of file translator_kr.h.
    {
      QCString opt = enable ? "" : "";
      return " "+opt+" ";
    }
trPanelSynchronisationTooltip() [2/2]
virtual QCString TranslatorKorean::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1916 of file translator_kr.h.
    {
      QCString opt = enable ? "" : "";
      return " "+opt+" ";
    }
trParameters() [1/2]
virtual QCString TranslatorKorean::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 568 of file translator_kr.h.
    { return ""; }
trParameters() [2/2]
virtual QCString TranslatorKorean::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 568 of file translator_kr.h.
    { return ""; }
trPostcondition() [1/2]
virtual QCString TranslatorKorean::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 875 of file translator_kr.h.
    {
      return "";
    }
trPostcondition() [2/2]
virtual QCString TranslatorKorean::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 875 of file translator_kr.h.
    {
      return "";
    }
trPrecondition() [1/2]
virtual QCString TranslatorKorean::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 870 of file translator_kr.h.
    {
      return "";
    }
trPrecondition() [2/2]
virtual QCString TranslatorKorean::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 870 of file translator_kr.h.
    {
      return "";
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorKorean::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 954 of file translator_kr.h.
    {
      return "Private ";
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorKorean::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 954 of file translator_kr.h.
    {
      return "Private ";
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorKorean::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 668 of file translator_kr.h.
    { return "Private "; }
trPrivateMembers() [2/2]
virtual QCString TranslatorKorean::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 668 of file translator_kr.h.
    { return "Private "; }
trPrivateSlots() [1/2]
virtual QCString TranslatorKorean::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 670 of file translator_kr.h.
    { return "Private Slots"; }
trPrivateSlots() [2/2]
virtual QCString TranslatorKorean::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 670 of file translator_kr.h.
    { return "Private Slots"; }
trPrivateTypes() [1/2]
virtual QCString TranslatorKorean::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 950 of file translator_kr.h.
    {
      return "Private ";
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorKorean::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 950 of file translator_kr.h.
    {
      return "Private ";
    }
trProperties() [1/2]
virtual QCString TranslatorKorean::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1097 of file translator_kr.h.
    {
      return "";
    }
trProperties() [2/2]
virtual QCString TranslatorKorean::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1097 of file translator_kr.h.
    {
      return "";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorKorean::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1102 of file translator_kr.h.
    {
      return " ";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorKorean::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1102 of file translator_kr.h.
    {
      return " ";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorKorean::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 942 of file translator_kr.h.
    {
      return "Protected ";
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorKorean::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 942 of file translator_kr.h.
    {
      return "Protected ";
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorKorean::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 662 of file translator_kr.h.
    { return "Protected "; }
trProtectedMembers() [2/2]
virtual QCString TranslatorKorean::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 662 of file translator_kr.h.
    { return "Protected "; }
trProtectedSlots() [1/2]
virtual QCString TranslatorKorean::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 664 of file translator_kr.h.
    { return "Protected Slots"; }
trProtectedSlots() [2/2]
virtual QCString TranslatorKorean::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 664 of file translator_kr.h.
    { return "Protected Slots"; }
trProtectedTypes() [1/2]
virtual QCString TranslatorKorean::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 938 of file translator_kr.h.
    {
      return "Protected ";
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorKorean::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 938 of file translator_kr.h.
    {
      return "Protected ";
    }
trProvidedByCategory() [1/2]
virtual QCString TranslatorKorean::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1926 of file translator_kr.h.
    {
      return " @0 .";
    }
trProvidedByCategory() [2/2]
virtual QCString TranslatorKorean::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1926 of file translator_kr.h.
    {
      return " @0 .";
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorKorean::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 923 of file translator_kr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return "Public ";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorKorean::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 923 of file translator_kr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ";
      }
      else
      {
        return "Public ";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorKorean::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 654 of file translator_kr.h.
    { return "Public "; }
trPublicMembers() [2/2]
virtual QCString TranslatorKorean::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 654 of file translator_kr.h.
    { return "Public "; }
trPublicSlots() [1/2]
virtual QCString TranslatorKorean::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 656 of file translator_kr.h.
    { return "Public Slots"; }
trPublicSlots() [2/2]
virtual QCString TranslatorKorean::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 656 of file translator_kr.h.
    { return "Public Slots"; }
trPublicTypes() [1/2]
virtual QCString TranslatorKorean::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 919 of file translator_kr.h.
    {
      return "Public ";
    }
trPublicTypes() [2/2]
virtual QCString TranslatorKorean::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 919 of file translator_kr.h.
    {
      return "Public ";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorKorean::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 982 of file translator_kr.h.
    {
      return " : ";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorKorean::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 982 of file translator_kr.h.
    {
      return " : ";
    }
trReferenceManual() [1/2]
virtual QCString TranslatorKorean::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 446 of file translator_kr.h.
    { return " "; }
trReferenceManual() [2/2]
virtual QCString TranslatorKorean::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 446 of file translator_kr.h.
    { return " "; }
trReferences() [1/2]
virtual QCString TranslatorKorean::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1304 of file translator_kr.h.
    {
      return " : ";
    }
trReferences() [2/2]
virtual QCString TranslatorKorean::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1304 of file translator_kr.h.
    {
      return " : ";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorKorean::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 719 of file translator_kr.h.
    {
      return trWriteList(numEntries)+"() .";
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorKorean::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 719 of file translator_kr.h.
    {
      return trWriteList(numEntries)+"() .";
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorKorean::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 727 of file translator_kr.h.
    {
      return trWriteList(numEntries)+" .";
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorKorean::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 727 of file translator_kr.h.
    {
      return trWriteList(numEntries)+" .";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorKorean::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 609 of file translator_kr.h.
    { return "Friend, "; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorKorean::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 609 of file translator_kr.h.
    { return "Friend, "; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorKorean::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 112 of file translator_kr.h.
    { return " "; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorKorean::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 112 of file translator_kr.h.
    { return " "; }
trRelatedPages() [1/2]
virtual QCString TranslatorKorean::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 246 of file translator_kr.h.
    { return " "; }
trRelatedPages() [2/2]
virtual QCString TranslatorKorean::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 246 of file translator_kr.h.
    { return " "; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorKorean::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 362 of file translator_kr.h.
    { return " .:"; }
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorKorean::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 362 of file translator_kr.h.
    { return " .:"; }
trRelatedSubscript() [1/2]
virtual QCString TranslatorKorean::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 116 of file translator_kr.h.
    { return "(. .)"; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorKorean::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 116 of file translator_kr.h.
    { return "(. .)"; }
trRemarks() [1/2]
virtual QCString TranslatorKorean::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 986 of file translator_kr.h.
    {
      return "Remarks";
    }
trRemarks() [2/2]
virtual QCString TranslatorKorean::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 986 of file translator_kr.h.
    {
      return "Remarks";
    }
trReturns() [1/2]
virtual QCString TranslatorKorean::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 560 of file translator_kr.h.
    { return ""; }
trReturns() [2/2]
virtual QCString TranslatorKorean::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 560 of file translator_kr.h.
    { return ""; }
trReturnValues() [1/2]
virtual QCString TranslatorKorean::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 804 of file translator_kr.h.
    { return ""; }
trReturnValues() [2/2]
virtual QCString TranslatorKorean::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 804 of file translator_kr.h.
    { return ""; }
trRTFansicp() [1/2]
virtual QCString TranslatorKorean::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1188 of file translator_kr.h.
    {
      return "949";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorKorean::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1188 of file translator_kr.h.
    {
      return "949";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorKorean::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1197 of file translator_kr.h.
    {
      return "129";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorKorean::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1197 of file translator_kr.h.
    {
      return "129";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorKorean::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1203 of file translator_kr.h.
    {
      return "";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorKorean::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1203 of file translator_kr.h.
    {
      return "";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorKorean::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1336 of file translator_kr.h.
    {
      return "";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorKorean::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1336 of file translator_kr.h.
    {
      return "";
    }
trSearch() [1/2]
virtual QCString TranslatorKorean::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 254 of file translator_kr.h.
    { return ""; }
trSearch() [2/2]
virtual QCString TranslatorKorean::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 254 of file translator_kr.h.
    { return ""; }
trSearching() [1/2]
virtual QCString TranslatorKorean::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1777 of file translator_kr.h.
    {
      return "...";
    }
trSearching() [2/2]
virtual QCString TranslatorKorean::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1777 of file translator_kr.h.
    {
      return "...";
    }
trSearchMatches() [1/2]
virtual QCString TranslatorKorean::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1468 of file translator_kr.h.
    {
      return ":";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorKorean::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1468 of file translator_kr.h.
    {
      return ":";
    }
trSearchResults() [1/2]
virtual QCString TranslatorKorean::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1449 of file translator_kr.h.
    {
      if (numDocuments==0)
      {
        return ". .";
      }
      else if (numDocuments==1)
      {
        return " <b>1</b> .";
      }
      else
      {
        return " <b>$num</b> . "
               " .";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorKorean::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1449 of file translator_kr.h.
    {
      if (numDocuments==0)
      {
        return ". .";
      }
      else if (numDocuments==1)
      {
        return " <b>1</b> .";
      }
      else
      {
        return " <b>$num</b> . "
               " .";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorKorean::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1437 of file translator_kr.h.
    {
      return " ";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorKorean::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1437 of file translator_kr.h.
    {
      return " ";
    }
trSeeAlso() [1/2]
virtual QCString TranslatorKorean::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 564 of file translator_kr.h.
    { return ""; }
trSeeAlso() [2/2]
virtual QCString TranslatorKorean::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 564 of file translator_kr.h.
    { return ""; }
trServiceGeneratedFromFiles() [1/2]
virtual QCString TranslatorKorean::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 2001 of file translator_kr.h.
    {
      // single is true implies a single file
      QCString result=" ";
      if (!single) result+="";
      result+=" .:";
      return result;
    }
trServiceGeneratedFromFiles() [2/2]
virtual QCString TranslatorKorean::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 2001 of file translator_kr.h.
    {
      // single is true implies a single file
      QCString result=" ";
      if (!single) result+="";
      result+=" .:";
      return result;
    }
trServiceReference() [1/2]
virtual QCString TranslatorKorean::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 1987 of file translator_kr.h.
    {
      QCString result=sName;
      result+=" ";
      return result;
    }
trServiceReference() [2/2]
virtual QCString TranslatorKorean::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 1987 of file translator_kr.h.
    {
      QCString result=sName;
      result+=" ";
      return result;
    }
trServices() [1/2]
virtual QCString TranslatorKorean::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1972 of file translator_kr.h.
    { return " "; }
trServices() [2/2]
virtual QCString TranslatorKorean::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1972 of file translator_kr.h.
    { return " "; }
trSignals() [1/2]
virtual QCString TranslatorKorean::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 658 of file translator_kr.h.
    { return "Signals"; }
trSignals() [2/2]
virtual QCString TranslatorKorean::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 658 of file translator_kr.h.
    { return "Signals"; }
trSince() [1/2]
virtual QCString TranslatorKorean::trSince () [inline], [virtual]
Implements Translator.
Definition at line 998 of file translator_kr.h.
    {
      return "Since";
    }
trSince() [2/2]
virtual QCString TranslatorKorean::trSince () [inline], [virtual]
Implements Translator.
Definition at line 998 of file translator_kr.h.
    {
      return "Since";
    }
trSingletonGeneratedFromFiles() [1/2]
virtual QCString TranslatorKorean::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 2010 of file translator_kr.h.
    {
      // single is true implies a single file
      QCString result=" ";
      if (!single) result+="";
      result+=" .:";
      return result;
    }
trSingletonGeneratedFromFiles() [2/2]
virtual QCString TranslatorKorean::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 2010 of file translator_kr.h.
    {
      // single is true implies a single file
      QCString result=" ";
      if (!single) result+="";
      result+=" .:";
      return result;
    }
trSingletonReference() [1/2]
virtual QCString TranslatorKorean::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 1994 of file translator_kr.h.
    {
      QCString result=sName;
      result+=" ";
      return result;
    }
trSingletonReference() [2/2]
virtual QCString TranslatorKorean::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 1994 of file translator_kr.h.
    {
      QCString result=sName;
      result+=" ";
      return result;
    }
trSourceFile() [1/2]
virtual QCString TranslatorKorean::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1479 of file translator_kr.h.
    {
      return filename + " ";
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorKorean::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1479 of file translator_kr.h.
    {
      return filename + " ";
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorKorean::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1408 of file translator_kr.h.
    {
      return " ";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorKorean::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1408 of file translator_kr.h.
    {
      return " ";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorKorean::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1394 of file translator_kr.h.
    {
      return " ";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorKorean::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1394 of file translator_kr.h.
    {
      return " ";
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorKorean::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 958 of file translator_kr.h.
    {
      return " Private ";
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorKorean::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 958 of file translator_kr.h.
    {
      return " Private ";
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorKorean::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 672 of file translator_kr.h.
    { return " Private "; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorKorean::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 672 of file translator_kr.h.
    { return " Private "; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorKorean::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 946 of file translator_kr.h.
    {
      return " Protected ";
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorKorean::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 946 of file translator_kr.h.
    {
      return " Protected ";
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorKorean::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 666 of file translator_kr.h.
    { return " Protected "; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorKorean::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 666 of file translator_kr.h.
    { return " Protected "; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorKorean::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 934 of file translator_kr.h.
    {
      return " Public ";
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorKorean::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 934 of file translator_kr.h.
    {
      return " Public ";
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorKorean::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 660 of file translator_kr.h.
    { return " Public "; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorKorean::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 660 of file translator_kr.h.
    { return " Public "; }
trSubprogram() [1/2]
virtual QCString TranslatorKorean::trSubprogram (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1741 of file translator_kr.h.
    {
      QCString result("");
      if (!singular) result+="";
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorKorean::trSubprogram (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1741 of file translator_kr.h.
    {
      QCString result("");
      if (!singular) result+="";
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorKorean::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1614 of file translator_kr.h.
    { return "/ "; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorKorean::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1614 of file translator_kr.h.
    { return "/ "; }
trSubprograms() [1/2]
virtual QCString TranslatorKorean::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1608 of file translator_kr.h.
    { return "/"; }
trSubprograms() [2/2]
virtual QCString TranslatorKorean::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1608 of file translator_kr.h.
    { return "/"; }
trTemplateParameters() [1/2]
virtual QCString TranslatorKorean::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1881 of file translator_kr.h.
    { return " "; }
trTemplateParameters() [2/2]
virtual QCString TranslatorKorean::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1881 of file translator_kr.h.
    { return " "; }
trTest() [1/2]
virtual QCString TranslatorKorean::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1082 of file translator_kr.h.
    {
      return "";
    }
trTest() [2/2]
virtual QCString TranslatorKorean::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1082 of file translator_kr.h.
    {
      return "";
    }
trTestList() [1/2]
virtual QCString TranslatorKorean::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1087 of file translator_kr.h.
    {
      return " ";
    }
trTestList() [2/2]
virtual QCString TranslatorKorean::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1087 of file translator_kr.h.
    {
      return " ";
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorKorean::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 161 of file translator_kr.h.
    { return " : "; }
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorKorean::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 161 of file translator_kr.h.
    { return " : "; }
trTodo() [1/2]
virtual QCString TranslatorKorean::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 968 of file translator_kr.h.
    {
      return "";
    }
trTodo() [2/2]
virtual QCString TranslatorKorean::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 968 of file translator_kr.h.
    {
      return "";
    }
trTodoList() [1/2]
virtual QCString TranslatorKorean::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 973 of file translator_kr.h.
    {
      return " ";
    }
trTodoList() [2/2]
virtual QCString TranslatorKorean::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 973 of file translator_kr.h.
    {
      return " ";
    }
trType() [1/2]
virtual QCString TranslatorKorean::trType (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1731 of file translator_kr.h.
    {
      QCString result("");
      if (!singular) result+="";
      return result;
    }
trType() [2/2]
virtual QCString TranslatorKorean::trType (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1731 of file translator_kr.h.
    {
      QCString result("");
      if (!singular) result+="";
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorKorean::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1749 of file translator_kr.h.
    {
      return " ";
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorKorean::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1749 of file translator_kr.h.
    {
      return " ";
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorKorean::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 494 of file translator_kr.h.
    { return " "; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorKorean::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 494 of file translator_kr.h.
    { return " "; }
trTypedefs() [1/2]
virtual QCString TranslatorKorean::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 458 of file translator_kr.h.
    { return ""; }
trTypedefs() [2/2]
virtual QCString TranslatorKorean::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 458 of file translator_kr.h.
    { return ""; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorKorean::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1602 of file translator_kr.h.
    { return " "; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorKorean::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1602 of file translator_kr.h.
    { return " "; }
trVariableDocumentation() [1/2]
virtual QCString TranslatorKorean::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 512 of file translator_kr.h.
    { return " "; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorKorean::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 512 of file translator_kr.h.
    { return " "; }
trVariables() [1/2]
virtual QCString TranslatorKorean::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 476 of file translator_kr.h.
    { return ""; }
trVariables() [2/2]
virtual QCString TranslatorKorean::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 476 of file translator_kr.h.
    { return ""; }
trVersion() [1/2]
virtual QCString TranslatorKorean::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 552 of file translator_kr.h.
    { return ""; }
trVersion() [2/2]
virtual QCString TranslatorKorean::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 552 of file translator_kr.h.
    { return ""; }
trWarning() [1/2]
virtual QCString TranslatorKorean::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 548 of file translator_kr.h.
    { return ""; }
trWarning() [2/2]
virtual QCString TranslatorKorean::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 548 of file translator_kr.h.
    { return ""; }
trWriteList() [1/2]
virtual QCString TranslatorKorean::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 678 of file translator_kr.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          //if (i<numEntries-2) // not the fore last entry
            result+=", ";
          //else // the fore last entry
          // result+=", "; // TODO: does the 'and' need to be translated here?
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorKorean::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 678 of file translator_kr.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          //if (i<numEntries-2) // not the fore last entry
            result+=", ";
          //else // the fore last entry
          // result+=", "; // TODO: does the 'and' need to be translated here?
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_kr.h
doxygen/src/translator_kr.h