TranslatorPolish Class Reference
#include <translator_pl.h>
Public Member Functions
QCString idLanguage ()
QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
QCString trRelatedFunctions ()
QCString trRelatedSubscript ()
QCString trDetailedDescription ()
QCString trMemberTypedefDocumentation ()
QCString trMemberEnumerationDocumentation ()
QCString trMemberFunctionDocumentation ()
QCString trMemberDataDocumentation ()
QCString trMore ()
QCString trListOfAllMembers ()
QCString trMemberList ()
QCString trThisIsTheListOfAllMembers ()
QCString trIncludingInheritedMembers ()
QCString trGeneratedAutomatically (const QCString &s)
QCString trEnumName ()
QCString trEnumValue ()
QCString trDefinedIn ()
QCString trModules ()
QCString trClassHierarchy ()
QCString trCompoundList ()
QCString trFileList ()
QCString trCompoundMembers ()
QCString trFileMembers ()
QCString trRelatedPages ()
QCString trExamples ()
QCString trSearch ()
QCString trClassHierarchyDescription ()
QCString trFileListDescription (bool extractAll)
QCString trCompoundListDescription ()
QCString trCompoundMembersDescription (bool extractAll)
QCString trFileMembersDescription (bool extractAll)
QCString trExamplesDescription ()
QCString trRelatedPagesDescription ()
QCString trModulesDescription ()
QCString trDocumentation ()
QCString trModuleIndex ()
QCString trHierarchicalIndex ()
QCString trCompoundIndex ()
QCString trFileIndex ()
QCString trModuleDocumentation ()
QCString trClassDocumentation ()
QCString trFileDocumentation ()
QCString trExampleDocumentation ()
QCString trReferenceManual ()
QCString trDefines ()
QCString trTypedefs ()
QCString trEnumerations ()
QCString trFunctions ()
QCString trVariables ()
QCString trEnumerationValues ()
QCString trDefineDocumentation ()
QCString trTypedefDocumentation ()
QCString trEnumerationTypeDocumentation ()
QCString trFunctionDocumentation ()
QCString trVariableDocumentation ()
QCString trCompounds ()
QCString trGeneratedAt (const QCString &date, const QCString &projName)
QCString trClassDiagram (const QCString &clName)
QCString trWarning ()
QCString trVersion ()
QCString trDate ()
QCString trReturns ()
QCString trSeeAlso ()
QCString trParameters ()
QCString trExceptions ()
QCString trGeneratedBy ()
QCString trNamespaceList ()
QCString trNamespaceListDescription (bool extractAll)
QCString trFriends ()
QCString trRelatedFunctionDocumentation ()
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
QCString trFileReference (const QCString &fileName)
QCString trNamespaceReference (const QCString &namespaceName)
QCString trPublicMembers ()
QCString trPublicSlots ()
QCString trSignals ()
QCString trStaticPublicMembers ()
QCString trProtectedMembers ()
QCString trProtectedSlots ()
QCString trStaticProtectedMembers ()
QCString trPrivateMembers ()
QCString trPrivateSlots ()
QCString trStaticPrivateMembers ()
QCString trWriteList (int numEntries)
QCString trInheritsList (int numEntries)
QCString trInheritedByList (int numEntries)
QCString trReimplementedFromList (int numEntries)
QCString trReimplementedInList (int numEntries)
QCString trNamespaceMembers ()
QCString trNamespaceMemberDescription (bool extractAll)
QCString trNamespaceIndex ()
QCString trNamespaceDocumentation ()
QCString trNamespaces ()
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
QCString trReturnValues ()
QCString trMainPage ()
QCString trPageAbbreviation ()
QCString trDefinedAtLineInSourceFile ()
QCString trDefinedInSourceFile ()
QCString trDeprecated ()
QCString trCollaborationDiagram (const QCString &clName)
QCString trInclDepGraph (const QCString &fName)
QCString trConstructorDocumentation ()
QCString trGotoSourceCode ()
QCString trGotoDocumentation ()
QCString trPrecondition ()
QCString trPostcondition ()
QCString trInvariant ()
QCString trInitialValue ()
QCString trCode ()
QCString trGraphicalHierarchy ()
QCString trGotoGraphicalHierarchy ()
QCString trGotoTextualHierarchy ()
QCString trPageIndex ()
QCString trNote ()
QCString trPublicTypes ()
QCString trPublicAttribs ()
QCString trStaticPublicAttribs ()
QCString trProtectedTypes ()
QCString trProtectedAttribs ()
QCString trStaticProtectedAttribs ()
QCString trPrivateTypes ()
QCString trPrivateAttribs ()
QCString trStaticPrivateAttribs ()
QCString trTodo ()
QCString trTodoList ()
QCString trReferencedBy ()
QCString trRemarks ()
QCString trAttention ()
QCString trInclByDepGraph ()
QCString trSince ()
QCString trLegendTitle ()
QCString trLegendDocs ()
QCString trLegend ()
QCString trTest ()
QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
QCString idLanguage ()
QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
QCString trRelatedFunctions ()
QCString trRelatedSubscript ()
QCString trDetailedDescription ()
QCString trMemberTypedefDocumentation ()
QCString trMemberEnumerationDocumentation ()
QCString trMemberFunctionDocumentation ()
QCString trMemberDataDocumentation ()
QCString trMore ()
QCString trListOfAllMembers ()
QCString trMemberList ()
QCString trThisIsTheListOfAllMembers ()
QCString trIncludingInheritedMembers ()
QCString trGeneratedAutomatically (const QCString &s)
QCString trEnumName ()
QCString trEnumValue ()
QCString trDefinedIn ()
QCString trModules ()
QCString trClassHierarchy ()
QCString trCompoundList ()
QCString trFileList ()
QCString trCompoundMembers ()
QCString trFileMembers ()
QCString trRelatedPages ()
QCString trExamples ()
QCString trSearch ()
QCString trClassHierarchyDescription ()
QCString trFileListDescription (bool extractAll)
QCString trCompoundListDescription ()
QCString trCompoundMembersDescription (bool extractAll)
QCString trFileMembersDescription (bool extractAll)
QCString trExamplesDescription ()
QCString trRelatedPagesDescription ()
QCString trModulesDescription ()
QCString trDocumentation ()
QCString trModuleIndex ()
QCString trHierarchicalIndex ()
QCString trCompoundIndex ()
QCString trFileIndex ()
QCString trModuleDocumentation ()
QCString trClassDocumentation ()
QCString trFileDocumentation ()
QCString trExampleDocumentation ()
QCString trReferenceManual ()
QCString trDefines ()
QCString trTypedefs ()
QCString trEnumerations ()
QCString trFunctions ()
QCString trVariables ()
QCString trEnumerationValues ()
QCString trDefineDocumentation ()
QCString trTypedefDocumentation ()
QCString trEnumerationTypeDocumentation ()
QCString trFunctionDocumentation ()
QCString trVariableDocumentation ()
QCString trCompounds ()
QCString trGeneratedAt (const QCString &date, const QCString &projName)
QCString trClassDiagram (const QCString &clName)
QCString trWarning ()
QCString trVersion ()
QCString trDate ()
QCString trReturns ()
QCString trSeeAlso ()
QCString trParameters ()
QCString trExceptions ()
QCString trGeneratedBy ()
QCString trNamespaceList ()
QCString trNamespaceListDescription (bool extractAll)
QCString trFriends ()
QCString trRelatedFunctionDocumentation ()
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
QCString trFileReference (const QCString &fileName)
QCString trNamespaceReference (const QCString &namespaceName)
QCString trPublicMembers ()
QCString trPublicSlots ()
QCString trSignals ()
QCString trStaticPublicMembers ()
QCString trProtectedMembers ()
QCString trProtectedSlots ()
QCString trStaticProtectedMembers ()
QCString trPrivateMembers ()
QCString trPrivateSlots ()
QCString trStaticPrivateMembers ()
QCString trWriteList (int numEntries)
QCString trInheritsList (int numEntries)
QCString trInheritedByList (int numEntries)
QCString trReimplementedFromList (int numEntries)
QCString trReimplementedInList (int numEntries)
QCString trNamespaceMembers ()
QCString trNamespaceMemberDescription (bool extractAll)
QCString trNamespaceIndex ()
QCString trNamespaceDocumentation ()
QCString trNamespaces ()
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
QCString trReturnValues ()
QCString trMainPage ()
QCString trPageAbbreviation ()
QCString trDefinedAtLineInSourceFile ()
QCString trDefinedInSourceFile ()
QCString trDeprecated ()
QCString trCollaborationDiagram (const QCString &clName)
QCString trInclDepGraph (const QCString &fName)
QCString trConstructorDocumentation ()
QCString trGotoSourceCode ()
QCString trGotoDocumentation ()
QCString trPrecondition ()
QCString trPostcondition ()
QCString trInvariant ()
QCString trInitialValue ()
QCString trCode ()
QCString trGraphicalHierarchy ()
QCString trGotoGraphicalHierarchy ()
QCString trGotoTextualHierarchy ()
QCString trPageIndex ()
QCString trNote ()
QCString trPublicTypes ()
QCString trPublicAttribs ()
QCString trStaticPublicAttribs ()
QCString trProtectedTypes ()
QCString trProtectedAttribs ()
QCString trStaticProtectedAttribs ()
QCString trPrivateTypes ()
QCString trPrivateAttribs ()
QCString trStaticPrivateAttribs ()
QCString trTodo ()
QCString trTodoList ()
QCString trReferencedBy ()
QCString trRemarks ()
QCString trAttention ()
QCString trInclByDepGraph ()
QCString trSince ()
QCString trLegendTitle ()
QCString trLegendDocs ()
QCString trLegend ()
QCString trTest ()
QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
Additional Inherited Members
Detailed Description
Definition at line 25 of file translator_pl.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorPolish::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 61 of file translator_pl.h.
    {
      return "0x415 Polish";
    }
getLanguageString() [2/2]
virtual QCString TranslatorPolish::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 61 of file translator_pl.h.
    {
      return "0x415 Polish";
    }
idLanguage() [1/2]
QCString TranslatorPolish::idLanguage () [inline], [virtual]
Used for identification of the language. May resemble the string returned by latexBabelPackage(), but it is not used for the same purpose. The identification should not be translated. It should be replaced by the name of the language in English (e.g. Czech, Japanese, Russian, etc.). It should be equal to the identification in language.h.
Implements Translator.
Definition at line 38 of file translator_pl.h.
    { return "polish"; }
idLanguage() [2/2]
QCString TranslatorPolish::idLanguage () [inline], [virtual]
Used for identification of the language. May resemble the string returned by latexBabelPackage(), but it is not used for the same purpose. The identification should not be translated. It should be replaced by the name of the language in English (e.g. Czech, Japanese, Russian, etc.). It should be equal to the identification in language.h.
Implements Translator.
Definition at line 38 of file translator_pl.h.
    { return "polish"; }
latexLanguageSupportCommand() [1/2]
QCString TranslatorPolish::latexLanguageSupportCommand () [inline], [virtual]
Used to get the command(s) for the language support. This method was designed for languages which do not prefer babel package. If this methods returns empty string, then the latexBabelPackage() method is used to generate the command for using the babel package.
Implements Translator.
Definition at line 45 of file translator_pl.h.
    {
      return "\\usepackage[polish]{babel}\n"
             "\\let\\lll\\undefined\n"; /* to overcome problems with the <<<
                                           symbol as defined in the amssymb
                                           package, and the Polish symbol
                                           "Latin Small Letter L With Stroke"
                                           &lstrok; or &#322; or &#x0142;
                                           We take the amssymb symbol as leading.
                                         */
    }
latexLanguageSupportCommand() [2/2]
QCString TranslatorPolish::latexLanguageSupportCommand () [inline], [virtual]
Used to get the command(s) for the language support. This method was designed for languages which do not prefer babel package. If this methods returns empty string, then the latexBabelPackage() method is used to generate the command for using the babel package.
Implements Translator.
Definition at line 45 of file translator_pl.h.
    {
      return "\\usepackage[polish]{babel}\n"
             "\\let\\lll\\undefined\n"; /* to overcome problems with the <<<
                                           symbol as defined in the amssymb
                                           package, and the Polish symbol
                                           "Latin Small Letter L With Stroke"
                                           &lstrok; or &#322; or &#x0142;
                                           We take the amssymb symbol as leading.
                                         */
    }
trAdditionalInheritedMembers() [1/2]
virtual QCString TranslatorPolish::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1843 of file translator_pl.h.
    { return "Dodatkowe Dziedziczone Skadowe"; }
trAdditionalInheritedMembers() [2/2]
virtual QCString TranslatorPolish::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1843 of file translator_pl.h.
    { return "Dodatkowe Dziedziczone Skadowe"; }
trAll() [1/2]
virtual QCString TranslatorPolish::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1351 of file translator_pl.h.
    {
      return "Wszystko";
    }
trAll() [2/2]
virtual QCString TranslatorPolish::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1351 of file translator_pl.h.
    {
      return "Wszystko";
    }
trAndMore() [1/2]
virtual QCString TranslatorPolish::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1822 of file translator_pl.h.
    { return "i "+number+" wicej..."; }
trAndMore() [2/2]
virtual QCString TranslatorPolish::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1822 of file translator_pl.h.
    { return "i "+number+" wicej..."; }
trAttention() [1/2]
QCString TranslatorPolish::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 943 of file translator_pl.h.
    {
      return "Uwaga";
    }
trAttention() [2/2]
QCString TranslatorPolish::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 943 of file translator_pl.h.
    {
      return "Uwaga";
    }
trAuthor() [1/2]
virtual QCString TranslatorPolish::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1226 of file translator_pl.h.
    {
      QCString result((first_capital ? "Auto" : "auto"));
      result += (singular) ? "r" : "rzy";
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorPolish::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1226 of file translator_pl.h.
    {
      QCString result((first_capital ? "Auto" : "auto"));
      result += (singular) ? "r" : "rzy";
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorPolish::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1110 of file translator_pl.h.
    {
      return "Bd";
    }
trBug() [2/2]
virtual QCString TranslatorPolish::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1110 of file translator_pl.h.
    {
      return "Bd";
    }
trBugList() [1/2]
virtual QCString TranslatorPolish::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1115 of file translator_pl.h.
    {
      return "Lista bdw";
    }
trBugList() [2/2]
virtual QCString TranslatorPolish::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1115 of file translator_pl.h.
    {
      return "Lista bdw";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorPolish::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1478 of file translator_pl.h.
    {
      return "Oto graf wywoywa tej funkcji:";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorPolish::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1478 of file translator_pl.h.
    {
      return "Oto graf wywoywa tej funkcji:";
    }
trCallGraph() [1/2]
virtual QCString TranslatorPolish::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1356 of file translator_pl.h.
    {
      return "Oto graf wywoa dla tej funkcji:";
    }
trCallGraph() [2/2]
virtual QCString TranslatorPolish::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1356 of file translator_pl.h.
    {
      return "Oto graf wywoa dla tej funkcji:";
    }
trCiteReferences() [1/2]
virtual QCString TranslatorPolish::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1798 of file translator_pl.h.
    { return "Odwoania do literatury"; }
trCiteReferences() [2/2]
virtual QCString TranslatorPolish::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1798 of file translator_pl.h.
    { return "Odwoania do literatury"; }
trClass() [1/2]
virtual QCString TranslatorPolish::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1146 of file translator_pl.h.
    {
      QCString result((first_capital ? "Klas" : "klas"));
      result+=(singular ? "a" : "y");
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorPolish::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1146 of file translator_pl.h.
    {
      QCString result((first_capital ? "Klas" : "klas"));
      result+=(singular ? "a" : "y");
      return result;
    }
trClassDiagram() [1/2]
QCString TranslatorPolish::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 497 of file translator_pl.h.
    {
      return "Diagram dziedziczenia dla "+clName;
    }
trClassDiagram() [2/2]
QCString TranslatorPolish::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 497 of file translator_pl.h.
    {
      return "Diagram dziedziczenia dla "+clName;
    }
trClassDocumentation() [1/2]
QCString TranslatorPolish::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 372 of file translator_pl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentacja struktur danych";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Dokumentacja klas";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClassDocumentation() [2/2]
QCString TranslatorPolish::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 372 of file translator_pl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentacja struktur danych";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Dokumentacja klas";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorPolish::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1073 of file translator_pl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Struktury Danych";
      }
      else
      {
        return "Klasy";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorPolish::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1073 of file translator_pl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Struktury Danych";
      }
      else
      {
        return "Klasy";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
QCString TranslatorPolish::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 156 of file translator_pl.h.
    { return "Hierarchia klas"; }
trClassHierarchy() [2/2]
QCString TranslatorPolish::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 156 of file translator_pl.h.
    { return "Hierarchia klas"; }
trClassHierarchyDescription() [1/2]
QCString TranslatorPolish::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 215 of file translator_pl.h.
    { return "Ta lista dziedziczenia posortowana jest z grubsza, "
             "cho nie cakowicie, alfabetycznie:";
    }
trClassHierarchyDescription() [2/2]
QCString TranslatorPolish::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 215 of file translator_pl.h.
    { return "Ta lista dziedziczenia posortowana jest z grubsza, "
             "cho nie cakowicie, alfabetycznie:";
    }
trCode() [1/2]
QCString TranslatorPolish::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 843 of file translator_pl.h.
    {
      return "kod rdowy";
    }
trCode() [2/2]
QCString TranslatorPolish::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 843 of file translator_pl.h.
    {
      return "kod rdowy";
    }
trCollaborationDiagram() [1/2]
QCString TranslatorPolish::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 798 of file translator_pl.h.
    {
      return "Diagram wsppracy dla "+clName+":";
    }
trCollaborationDiagram() [2/2]
QCString TranslatorPolish::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 798 of file translator_pl.h.
    {
      return "Diagram wsppracy dla "+clName+":";
    }
trCompoundIndex() [1/2]
QCString TranslatorPolish::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 345 of file translator_pl.h.
    {
     if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Indeks struktur danych";
      }
      else
      {
        return "Indeks klas";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
QCString TranslatorPolish::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 345 of file translator_pl.h.
    {
     if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Indeks struktur danych";
      }
      else
      {
        return "Indeks klas";
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorPolish::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1533 of file translator_pl.h.
    { return "Indeks typw danych"; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorPolish::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1533 of file translator_pl.h.
    { return "Indeks typw danych"; }
trCompoundList() [1/2]
QCString TranslatorPolish::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 160 of file translator_pl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Struktury danych";
      }
      else
      {
        return "Lista klas";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
QCString TranslatorPolish::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 160 of file translator_pl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Struktury danych";
      }
      else
      {
        return "Lista klas";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
QCString TranslatorPolish::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 230 of file translator_pl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Tutaj znajduj si struktury danych wraz z ich krtkimi opisami:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Tutaj znajduj si klasy wraz z ich krtkimi opisami:";
      }
      else
      {
        return "Tutaj znajduj si klasy, struktury, "
             "unie i interfejsy wraz z ich krtkimi opisami:";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
QCString TranslatorPolish::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 230 of file translator_pl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Tutaj znajduj si struktury danych wraz z ich krtkimi opisami:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Tutaj znajduj si klasy wraz z ich krtkimi opisami:";
      }
      else
      {
        return "Tutaj znajduj si klasy, struktury, "
             "unie i interfejsy wraz z ich krtkimi opisami:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorPolish::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1506 of file translator_pl.h.
    { return "Tutaj znajduj si typy danych z ich krtkimi opisami:"; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorPolish::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1506 of file translator_pl.h.
    { return "Tutaj znajduj si typy danych z ich krtkimi opisami:"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorPolish::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1498 of file translator_pl.h.
    { return "Lista typw danych"; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorPolish::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1498 of file translator_pl.h.
    { return "Lista typw danych"; }
trCompoundMembers() [1/2]
QCString TranslatorPolish::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 177 of file translator_pl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Pola danych";
      }
      else
      {
        return "Skadowe klas";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
QCString TranslatorPolish::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 177 of file translator_pl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Pola danych";
      }
      else
      {
        return "Skadowe klas";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
QCString TranslatorPolish::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 249 of file translator_pl.h.
    {
      QCString result="Tutaj znajduje si lista wszystkich ";
      if (!extractAll)
      {
        result+="udokumentowanych ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="pl struktur i unii";
      }
      else
      {
        result+="skadowych";
      }
      result+=" wraz z odnonikami do ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="dokumentacji struktur/unii dla kadego pola:";
        }
        else
        {
          result+="dokumentacji klas dla kadej skadowej:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="struktur/unii, do ktrych dane pole naley:";
        }
        else
        {
          result+="klas, do ktrych dana skadowa naley:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
QCString TranslatorPolish::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 249 of file translator_pl.h.
    {
      QCString result="Tutaj znajduje si lista wszystkich ";
      if (!extractAll)
      {
        result+="udokumentowanych ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="pl struktur i unii";
      }
      else
      {
        result+="skadowych";
      }
      result+=" wraz z odnonikami do ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="dokumentacji struktur/unii dla kadego pola:";
        }
        else
        {
          result+="dokumentacji klas dla kadej skadowej:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="struktur/unii, do ktrych dane pole naley:";
        }
        else
        {
          result+="klas, do ktrych dana skadowa naley:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorPolish::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1510 of file translator_pl.h.
    {
      QCString result="Tutaj znajduje si lista wszystkich ";
      if (!extractAll)
      {
        result+="udokumentowanych ";
      }
      result+="skadowych typw danych";
      result+=" wraz z odnonikami do ";
      if (!extractAll)
      {
         result+="dokumentacji struktury danych dla kadej skadowej";
      }
      else
      {
         result+="typw danych, do ktrych dana skadowa naley:";
      }
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorPolish::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1510 of file translator_pl.h.
    {
      QCString result="Tutaj znajduje si lista wszystkich ";
      if (!extractAll)
      {
        result+="udokumentowanych ";
      }
      result+="skadowych typw danych";
      result+=" wraz z odnonikami do ";
      if (!extractAll)
      {
         result+="dokumentacji struktury danych dla kadej skadowej";
      }
      else
      {
         result+="typw danych, do ktrych dana skadowa naley:";
      }
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorPolish::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1502 of file translator_pl.h.
    { return "Pola danych"; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorPolish::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1502 of file translator_pl.h.
    { return "Pola danych"; }
trCompoundReference() [1/2]
QCString TranslatorPolish::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 570 of file translator_pl.h.
    {
      QCString result="Dokumentacja";
      if (isTemplate) result+=" szablonu";
      switch(compType)
      {
        case ClassDef::Class: result+=" klasy "; break;
        case ClassDef::Struct: result+=" struktury "; break;
        case ClassDef::Union: result+=" unii "; break;
        case ClassDef::Interface: result+=" interfejsu "; break;
        case ClassDef::Protocol: result+=" protokou "; break;
        case ClassDef::Category: result+=" kategorii "; break;
        case ClassDef::Exception: result+=" wyjtku "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
QCString TranslatorPolish::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 570 of file translator_pl.h.
    {
      QCString result="Dokumentacja";
      if (isTemplate) result+=" szablonu";
      switch(compType)
      {
        case ClassDef::Class: result+=" klasy "; break;
        case ClassDef::Struct: result+=" struktury "; break;
        case ClassDef::Union: result+=" unii "; break;
        case ClassDef::Interface: result+=" interfejsu "; break;
        case ClassDef::Protocol: result+=" protokou "; break;
        case ClassDef::Category: result+=" kategorii "; break;
        case ClassDef::Exception: result+=" wyjtku "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorPolish::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1574 of file translator_pl.h.
    {
      QCString result="Dokumentacja";
      if (isTemplate) result+=" szablonu";
      switch(compType)
      {
        case ClassDef::Class: result+=" moduu "; break;
        case ClassDef::Struct: result+=" typu "; break;
        case ClassDef::Union: result+=" unii "; break;
        case ClassDef::Interface: result+=" interfejsu "; break;
        case ClassDef::Protocol: result+=" protokou "; break;
        case ClassDef::Category: result+=" kategorii "; break;
        case ClassDef::Exception: result+=" wyjtku "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorPolish::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1574 of file translator_pl.h.
    {
      QCString result="Dokumentacja";
      if (isTemplate) result+=" szablonu";
      switch(compType)
      {
        case ClassDef::Class: result+=" moduu "; break;
        case ClassDef::Struct: result+=" typu "; break;
        case ClassDef::Union: result+=" unii "; break;
        case ClassDef::Interface: result+=" interfejsu "; break;
        case ClassDef::Protocol: result+=" protokou "; break;
        case ClassDef::Category: result+=" kategorii "; break;
        case ClassDef::Exception: result+=" wyjtku "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
QCString TranslatorPolish::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 473 of file translator_pl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Struktury danych";
      }
      else
      {
        return "Komponenty";
      }
    }
References Config_getBool.
trCompounds() [2/2]
QCString TranslatorPolish::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 473 of file translator_pl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Struktury danych";
      }
      else
      {
        return "Komponenty";
      }
    }
References Config_getBool.
trConstructorDocumentation() [1/2]
QCString TranslatorPolish::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 808 of file translator_pl.h.
    {
      return "Dokumentacja konstruktora i destruktora";
    }
trConstructorDocumentation() [2/2]
QCString TranslatorPolish::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 808 of file translator_pl.h.
    {
      return "Dokumentacja konstruktora i destruktora";
    }
trCopyright() [1/2]
virtual QCString TranslatorPolish::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1802 of file translator_pl.h.
    { return "Copyright"; }
trCopyright() [2/2]
virtual QCString TranslatorPolish::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1802 of file translator_pl.h.
    { return "Copyright"; }
trDataTypes() [1/2]
virtual QCString TranslatorPolish::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1557 of file translator_pl.h.
    { return "Typy danych"; }
trDataTypes() [2/2]
virtual QCString TranslatorPolish::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1557 of file translator_pl.h.
    { return "Typy danych"; }
trDate() [1/2]
QCString TranslatorPolish::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 511 of file translator_pl.h.
    { return "Data"; }
trDate() [2/2]
QCString TranslatorPolish::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 511 of file translator_pl.h.
    { return "Data"; }
trDateTime() [1/2]
virtual QCString TranslatorPolish::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1755 of file translator_pl.h.
    {
      static const char *days[] = { "Pn","Wt","r","Cz","Pt","So","N" };
      static const char *months[] = { "sty","lut","mar","kwi","maj","cze","lip","sie","wrz","pa","lis","gru" };
      QCString sdate;
      sdate.sprintf("%s, %d %s %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDateTime() [2/2]
virtual QCString TranslatorPolish::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1755 of file translator_pl.h.
    {
      static const char *days[] = { "Pn","Wt","r","Cz","Pt","So","N" };
      static const char *months[] = { "sty","lut","mar","kwi","maj","cze","lip","sie","wrz","pa","lis","gru" };
      QCString sdate;
      sdate.sprintf("%s, %d %s %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDayOfWeek() [1/2]
virtual QCString TranslatorPolish::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1771 of file translator_pl.h.
    {
      static const char *days_short[] = { "pon.", "wt.", "r.", "czw.", "pt.", "sob.", "niedz." };
      static const char *days_full[] = { "poniedziaek", "wtorek", "roda", "czwartek", "pitek", "sobota", "niedziela" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayOfWeek() [2/2]
virtual QCString TranslatorPolish::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1771 of file translator_pl.h.
    {
      static const char *days_short[] = { "pon.", "wt.", "r.", "czw.", "pt.", "sob.", "niedz." };
      static const char *days_full[] = { "poniedziaek", "wtorek", "roda", "czwartek", "pitek", "sobota", "niedziela" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod() [1/2]
virtual QCString TranslatorPolish::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1787 of file translator_pl.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorPolish::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1787 of file translator_pl.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
QCString TranslatorPolish::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 775 of file translator_pl.h.
    {
      return "Definicja w linii @0 pliku @1.";
    }
trDefinedAtLineInSourceFile() [2/2]
QCString TranslatorPolish::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 775 of file translator_pl.h.
    {
      return "Definicja w linii @0 pliku @1.";
    }
trDefinedIn() [1/2]
QCString TranslatorPolish::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 144 of file translator_pl.h.
    { return "zdefiniowana w"; }
trDefinedIn() [2/2]
QCString TranslatorPolish::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 144 of file translator_pl.h.
    { return "zdefiniowana w"; }
trDefinedInSourceFile() [1/2]
QCString TranslatorPolish::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 779 of file translator_pl.h.
    {
      return "Definicja w pliku @0.";
    }
trDefinedInSourceFile() [2/2]
QCString TranslatorPolish::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 779 of file translator_pl.h.
    {
      return "Definicja w pliku @0.";
    }
trDefineDocumentation() [1/2]
QCString TranslatorPolish::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 443 of file translator_pl.h.
    { return "Dokumentacja definicji"; }
trDefineDocumentation() [2/2]
QCString TranslatorPolish::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 443 of file translator_pl.h.
    { return "Dokumentacja definicji"; }
trDefines() [1/2]
QCString TranslatorPolish::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 407 of file translator_pl.h.
    { return "Definicje"; }
trDefines() [2/2]
QCString TranslatorPolish::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 407 of file translator_pl.h.
    { return "Definicje"; }
trDefineValue() [1/2]
virtual QCString TranslatorPolish::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1100 of file translator_pl.h.
    {
      return "Warto:";
    }
trDefineValue() [2/2]
virtual QCString TranslatorPolish::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1100 of file translator_pl.h.
    {
      return "Warto:";
    }
trDeprecated() [1/2]
QCString TranslatorPolish::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 788 of file translator_pl.h.
    {
      return "Do wycofania";
    }
trDeprecated() [2/2]
QCString TranslatorPolish::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 788 of file translator_pl.h.
    {
      return "Do wycofania";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorPolish::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1279 of file translator_pl.h.
    {
      return "Lista elementw do wycofania";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorPolish::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1279 of file translator_pl.h.
    {
      return "Lista elementw do wycofania";
    }
trDetailedDescription() [1/2]
QCString TranslatorPolish::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 77 of file translator_pl.h.
    { return "Opis szczegowy"; }
trDetailedDescription() [2/2]
QCString TranslatorPolish::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 77 of file translator_pl.h.
    { return "Opis szczegowy"; }
trDetailLevel() [1/2]
virtual QCString TranslatorPolish::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1814 of file translator_pl.h.
    { return "poziom szczegw"; }
trDetailLevel() [2/2]
virtual QCString TranslatorPolish::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1814 of file translator_pl.h.
    { return "poziom szczegw"; }
trDir() [1/2]
virtual QCString TranslatorPolish::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1453 of file translator_pl.h.
    {
      QCString result((first_capital ? "Katalog" : "katalog"));
      if (! singular) result+="i";
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorPolish::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1453 of file translator_pl.h.
    {
      QCString result((first_capital ? "Katalog" : "katalog"));
      if (! singular) result+="i";
      return result;
    }
trDirDepGraph() [1/2]
virtual QCString TranslatorPolish::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1806 of file translator_pl.h.
    { return QCString("Wykres zalenoci katalogu dla ")+name+":"; }
References setup::name.
trDirDepGraph() [2/2]
virtual QCString TranslatorPolish::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1806 of file translator_pl.h.
    { return QCString("Wykres zalenoci katalogu dla ")+name+":"; }
References setup::name.
trDirDocumentation() [1/2]
virtual QCString TranslatorPolish::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1434 of file translator_pl.h.
    { return "Dokumentacja katalogw"; }
trDirDocumentation() [2/2]
virtual QCString TranslatorPolish::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1434 of file translator_pl.h.
    { return "Dokumentacja katalogw"; }
trDirectories() [1/2]
virtual QCString TranslatorPolish::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1440 of file translator_pl.h.
    { return "Katalogi"; }
trDirectories() [2/2]
virtual QCString TranslatorPolish::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1440 of file translator_pl.h.
    { return "Katalogi"; }
trDirIndex() [1/2]
virtual QCString TranslatorPolish::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1428 of file translator_pl.h.
    { return "Struktura katalogw"; }
trDirIndex() [2/2]
virtual QCString TranslatorPolish::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1428 of file translator_pl.h.
    { return "Struktura katalogw"; }
trDirReference() [1/2]
virtual QCString TranslatorPolish::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1447 of file translator_pl.h.
    { QCString result="Dokumentacja katalogu "; result+=dirName; return result; }
trDirReference() [2/2]
virtual QCString TranslatorPolish::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1447 of file translator_pl.h.
    { QCString result="Dokumentacja katalogu "; result+=dirName; return result; }
trDirRelation() [1/2]
virtual QCString TranslatorPolish::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1694 of file translator_pl.h.
    {
      return "Relacja "+ QCString(name);
    }
References setup::name.
trDirRelation() [2/2]
virtual QCString TranslatorPolish::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1694 of file translator_pl.h.
    {
      return "Relacja "+ QCString(name);
    }
References setup::name.
trDocumentation() [1/2]
QCString TranslatorPolish::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 327 of file translator_pl.h.
    { return "Dokumentacja"; }
trDocumentation() [2/2]
QCString TranslatorPolish::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 327 of file translator_pl.h.
    { return "Dokumentacja"; }
trEnumerations() [1/2]
QCString TranslatorPolish::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 419 of file translator_pl.h.
    { return "Wyliczenia"; }
trEnumerations() [2/2]
QCString TranslatorPolish::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 419 of file translator_pl.h.
    { return "Wyliczenia"; }
trEnumerationTypeDocumentation() [1/2]
QCString TranslatorPolish::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 455 of file translator_pl.h.
    { return "Dokumentacja typw wyliczanych"; }
trEnumerationTypeDocumentation() [2/2]
QCString TranslatorPolish::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 455 of file translator_pl.h.
    { return "Dokumentacja typw wyliczanych"; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorPolish::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1486 of file translator_pl.h.
    { return "Dokumentacja wylicze"; } //TODO check if it is correct translation
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorPolish::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1486 of file translator_pl.h.
    { return "Dokumentacja wylicze"; } //TODO check if it is correct translation
trEnumerationValues() [1/2]
QCString TranslatorPolish::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 437 of file translator_pl.h.
    { return "Wartoci wylicze"; }
trEnumerationValues() [2/2]
QCString TranslatorPolish::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 437 of file translator_pl.h.
    { return "Wartoci wylicze"; }
trEnumGeneratedFromFiles() [1/2]
virtual QCString TranslatorPolish::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1826 of file translator_pl.h.
    { QCString result = "Dokumentacja dla tego wyliczenia zostaa wygenerowana z plik";
      if (single) result+="u:"; else result+="w:";
      return result;
    }
trEnumGeneratedFromFiles() [2/2]
virtual QCString TranslatorPolish::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1826 of file translator_pl.h.
    { QCString result = "Dokumentacja dla tego wyliczenia zostaa wygenerowana z plik";
      if (single) result+="u:"; else result+="w:";
      return result;
    }
trEnumName() [1/2]
QCString TranslatorPolish::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 136 of file translator_pl.h.
    { return "nazwa wyliczenia"; }
trEnumName() [2/2]
QCString TranslatorPolish::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 136 of file translator_pl.h.
    { return "nazwa wyliczenia"; }
trEnumReference() [1/2]
virtual QCString TranslatorPolish::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1833 of file translator_pl.h.
    { QCString result="Dokumentacja wyliczenia "; result+=name; return result; }
References setup::name.
trEnumReference() [2/2]
virtual QCString TranslatorPolish::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1833 of file translator_pl.h.
    { QCString result="Dokumentacja wyliczenia "; result+=name; return result; }
References setup::name.
trEnumValue() [1/2]
QCString TranslatorPolish::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 140 of file translator_pl.h.
    { return "warto wyliczenia"; }
trEnumValue() [2/2]
QCString TranslatorPolish::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 140 of file translator_pl.h.
    { return "warto wyliczenia"; }
trEventDocumentation() [1/2]
virtual QCString TranslatorPolish::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1296 of file translator_pl.h.
    {
      return "Dokumentacja zdarze";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorPolish::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1296 of file translator_pl.h.
    {
      return "Dokumentacja zdarze";
    }
trEvents() [1/2]
virtual QCString TranslatorPolish::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1291 of file translator_pl.h.
    {
      return "Zdarzenia";
    }
trEvents() [2/2]
virtual QCString TranslatorPolish::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1291 of file translator_pl.h.
    {
      return "Zdarzenia";
    }
trExampleDocumentation() [1/2]
QCString TranslatorPolish::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 397 of file translator_pl.h.
    { return "Dokumentacja przykadw"; }
trExampleDocumentation() [2/2]
QCString TranslatorPolish::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 397 of file translator_pl.h.
    { return "Dokumentacja przykadw"; }
trExamples() [1/2]
QCString TranslatorPolish::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 207 of file translator_pl.h.
    { return "Przykady"; }
trExamples() [2/2]
QCString TranslatorPolish::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 207 of file translator_pl.h.
    { return "Przykady"; }
trExamplesDescription() [1/2]
QCString TranslatorPolish::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 312 of file translator_pl.h.
    { return "Tutaj znajduje si lista wszystkich przykadw:"; }
trExamplesDescription() [2/2]
QCString TranslatorPolish::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 312 of file translator_pl.h.
    { return "Tutaj znajduje si lista wszystkich przykadw:"; }
trExceptions() [1/2]
QCString TranslatorPolish::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 527 of file translator_pl.h.
    { return "Wyjtki"; }
trExceptions() [2/2]
QCString TranslatorPolish::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 527 of file translator_pl.h.
    { return "Wyjtki"; }
trFile() [1/2]
virtual QCString TranslatorPolish::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1157 of file translator_pl.h.
    {
      QCString result((first_capital ? "Plik" : "plik"));
      if (!singular) result+="i";
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorPolish::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1157 of file translator_pl.h.
    {
      QCString result((first_capital ? "Plik" : "plik"));
      if (!singular) result+="i";
      return result;
    }
trFileDocumentation() [1/2]
QCString TranslatorPolish::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 391 of file translator_pl.h.
    { return "Dokumentacja plikw"; }
trFileDocumentation() [2/2]
QCString TranslatorPolish::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 391 of file translator_pl.h.
    { return "Dokumentacja plikw"; }
trFileIn() [1/2]
virtual QCString TranslatorPolish::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1731 of file translator_pl.h.
    {
      return "Plik w "+name;
    }
References setup::name.
trFileIn() [2/2]
virtual QCString TranslatorPolish::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1731 of file translator_pl.h.
    {
      return "Plik w "+name;
    }
References setup::name.
trFileIndex() [1/2]
QCString TranslatorPolish::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 360 of file translator_pl.h.
    { return "Indeks plikw"; }
trFileIndex() [2/2]
QCString TranslatorPolish::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 360 of file translator_pl.h.
    { return "Indeks plikw"; }
trFileList() [1/2]
QCString TranslatorPolish::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 173 of file translator_pl.h.
    { return "Lista plikw"; }
trFileList() [2/2]
QCString TranslatorPolish::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 173 of file translator_pl.h.
    { return "Lista plikw"; }
trFileListDescription() [1/2]
QCString TranslatorPolish::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 221 of file translator_pl.h.
    {
      QCString result="Tutaj znajduje si lista wszystkich ";
      if (!extractAll) result+="udokumentowanych ";
      result+="plikw z ich krtkimi opisami:";
      return result;
    }
trFileListDescription() [2/2]
QCString TranslatorPolish::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 221 of file translator_pl.h.
    {
      QCString result="Tutaj znajduje si lista wszystkich ";
      if (!extractAll) result+="udokumentowanych ";
      result+="plikw z ich krtkimi opisami:";
      return result;
    }
trFileMembers() [1/2]
QCString TranslatorPolish::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 190 of file translator_pl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globalne";
      }
      else
      {
        return "Skadowe plikw";
      }
    }
References Config_getBool.
trFileMembers() [2/2]
QCString TranslatorPolish::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 190 of file translator_pl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globalne";
      }
      else
      {
        return "Skadowe plikw";
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
QCString TranslatorPolish::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 291 of file translator_pl.h.
    {
      QCString result="Tutaj znajduje si lista wszystkich ";
      if (!extractAll) result+="udokumentowanych ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funkcji, zmiennych, makr, wylicze i definicji typw";
      }
      else
      {
        result+="skadowych plikw";
      }
      result+=" wraz z odnonikami do ";
      if (extractAll)
        result+="plikw, do ktrych one nale:";
      else
        result+="dokumentacji:";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
QCString TranslatorPolish::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 291 of file translator_pl.h.
    {
      QCString result="Tutaj znajduje si lista wszystkich ";
      if (!extractAll) result+="udokumentowanych ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funkcji, zmiennych, makr, wylicze i definicji typw";
      }
      else
      {
        result+="skadowych plikw";
      }
      result+=" wraz z odnonikami do ";
      if (extractAll)
        result+="plikw, do ktrych one nale:";
      else
        result+="dokumentacji:";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
QCString TranslatorPolish::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 592 of file translator_pl.h.
    {
      QCString result="Dokumentacja pliku ";
      result+=fileName;
      return result;
    }
trFileReference() [2/2]
QCString TranslatorPolish::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 592 of file translator_pl.h.
    {
      QCString result="Dokumentacja pliku ";
      result+=fileName;
      return result;
    }
trFriends() [1/2]
QCString TranslatorPolish::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 552 of file translator_pl.h.
    { return "Przyjaciele"; }
trFriends() [2/2]
QCString TranslatorPolish::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 552 of file translator_pl.h.
    { return "Przyjaciele"; }
trFunctionDocumentation() [1/2]
QCString TranslatorPolish::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 461 of file translator_pl.h.
    { return "Dokumentacja funkcji"; }
trFunctionDocumentation() [2/2]
QCString TranslatorPolish::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 461 of file translator_pl.h.
    { return "Dokumentacja funkcji"; }
trFunctions() [1/2]
QCString TranslatorPolish::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 425 of file translator_pl.h.
    { return "Funkcje"; }
trFunctions() [2/2]
QCString TranslatorPolish::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 425 of file translator_pl.h.
    { return "Funkcje"; }
trGeneratedAt() [1/2]
QCString TranslatorPolish::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 488 of file translator_pl.h.
    {
      QCString result="Wygenerowano "+date;
      if (!projName.isEmpty()) result+=" dla "+projName;
      result+=" programem";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
QCString TranslatorPolish::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 488 of file translator_pl.h.
    {
      QCString result="Wygenerowano "+date;
      if (!projName.isEmpty()) result+=" dla "+projName;
      result+=" programem";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
QCString TranslatorPolish::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 128 of file translator_pl.h.
    { QCString result="Wygenerowano automatycznie z kodu rdowego programem Doxygen";
      if (!s.isEmpty()) result+=" dla "+s;
      result+=".";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
QCString TranslatorPolish::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 128 of file translator_pl.h.
    { QCString result="Wygenerowano automatycznie z kodu rdowego programem Doxygen";
      if (!s.isEmpty()) result+=" dla "+s;
      result+=".";
      return result;
    }
References s.
trGeneratedBy() [1/2]
QCString TranslatorPolish::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 531 of file translator_pl.h.
    { return "Wygenerowano przez"; }
trGeneratedBy() [2/2]
QCString TranslatorPolish::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 531 of file translator_pl.h.
    { return "Wygenerowano przez"; }
trGeneratedFromFiles() [1/2]
QCString TranslatorPolish::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 731 of file translator_pl.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentacja dla te";
      switch(compType)
      {
        case ClassDef::Class: result+="j klasy"; break;
        case ClassDef::Struct: result+="j struktury"; break;
        case ClassDef::Union: result+="j unii"; break;
        case ClassDef::Interface: result+="go interfejsu"; break;
        case ClassDef::Protocol: result+="go protokou"; break;
        case ClassDef::Category: result+="j kategorii"; break;
        case ClassDef::Exception: result+="go wyjtku"; break;
        default: break;
      }
      result+=" zostaa wygenerowana z plik";
      if (single) result+="u:"; else result+="w:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
QCString TranslatorPolish::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 731 of file translator_pl.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentacja dla te";
      switch(compType)
      {
        case ClassDef::Class: result+="j klasy"; break;
        case ClassDef::Struct: result+="j struktury"; break;
        case ClassDef::Union: result+="j unii"; break;
        case ClassDef::Interface: result+="go interfejsu"; break;
        case ClassDef::Protocol: result+="go protokou"; break;
        case ClassDef::Category: result+="j kategorii"; break;
        case ClassDef::Exception: result+="go wyjtku"; break;
        default: break;
      }
      result+=" zostaa wygenerowana z plik";
      if (single) result+="u:"; else result+="w:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorPolish::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1642 of file translator_pl.h.
    {
      // single is true implies a single file
      QCString result="Dokumentacja dla te";
      switch(compType)
      {
        case ClassDef::Class: result+="go moduu"; break;
        case ClassDef::Struct: result+="go typu"; break;
        case ClassDef::Union: result+="j unii"; break;
        case ClassDef::Interface: result+="go interfejsu"; break;
        case ClassDef::Protocol: result+="go protokou"; break;
        case ClassDef::Category: result+="j kategorii"; break;
        case ClassDef::Exception: result+="go wyjtku"; break;
        default: break;
      }
      result+=" zostaa wygenerowana z plik";
      if (single) result+="u:"; else result+="w:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorPolish::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1642 of file translator_pl.h.
    {
      // single is true implies a single file
      QCString result="Dokumentacja dla te";
      switch(compType)
      {
        case ClassDef::Class: result+="go moduu"; break;
        case ClassDef::Struct: result+="go typu"; break;
        case ClassDef::Union: result+="j unii"; break;
        case ClassDef::Interface: result+="go interfejsu"; break;
        case ClassDef::Protocol: result+="go protokou"; break;
        case ClassDef::Category: result+="j kategorii"; break;
        case ClassDef::Exception: result+="go wyjtku"; break;
        default: break;
      }
      result+=" zostaa wygenerowana z plik";
      if (single) result+="u:"; else result+="w:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorPolish::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1213 of file translator_pl.h.
    {
      QCString result((first_capital ? "Global" : "global"));
      result+=(singular ? "ny" : "ne");
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorPolish::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1213 of file translator_pl.h.
    {
      QCString result((first_capital ? "Global" : "global"));
      result+=(singular ? "ny" : "ne");
      return result;
    }
trGlobalNamespace() [1/2]
virtual QCString TranslatorPolish::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1706 of file translator_pl.h.
    {
      return "Globalna przestrze nazw";
    }
trGlobalNamespace() [2/2]
virtual QCString TranslatorPolish::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1706 of file translator_pl.h.
    {
      return "Globalna przestrze nazw";
    }
trGotoDocumentation() [1/2]
QCString TranslatorPolish::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 818 of file translator_pl.h.
    {
      return "Id do dokumentacji tego pliku.";
    }
trGotoDocumentation() [2/2]
QCString TranslatorPolish::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 818 of file translator_pl.h.
    {
      return "Id do dokumentacji tego pliku.";
    }
trGotoGraphicalHierarchy() [1/2]
QCString TranslatorPolish::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 851 of file translator_pl.h.
    {
      return "Id do graficznej hierarchii klas";
    }
trGotoGraphicalHierarchy() [2/2]
QCString TranslatorPolish::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 851 of file translator_pl.h.
    {
      return "Id do graficznej hierarchii klas";
    }
trGotoSourceCode() [1/2]
QCString TranslatorPolish::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 813 of file translator_pl.h.
    {
      return "Id do kodu rdowego tego pliku.";
    }
trGotoSourceCode() [2/2]
QCString TranslatorPolish::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 813 of file translator_pl.h.
    {
      return "Id do kodu rdowego tego pliku.";
    }
trGotoTextualHierarchy() [1/2]
QCString TranslatorPolish::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 855 of file translator_pl.h.
    {
      return "Id do tekstowej hierarchii klas";
    }
trGotoTextualHierarchy() [2/2]
QCString TranslatorPolish::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 855 of file translator_pl.h.
    {
      return "Id do tekstowej hierarchii klas";
    }
trGraphicalHierarchy() [1/2]
QCString TranslatorPolish::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 847 of file translator_pl.h.
    {
      return "Graficzna hierarchia klas";
    }
trGraphicalHierarchy() [2/2]
QCString TranslatorPolish::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 847 of file translator_pl.h.
    {
      return "Graficzna hierarchia klas";
    }
trGroup() [1/2]
virtual QCString TranslatorPolish::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1180 of file translator_pl.h.
    {
      QCString result((first_capital ? "Grupa" : "grupa"));
      result+=(singular ? "a" : "y");
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorPolish::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1180 of file translator_pl.h.
    {
      QCString result((first_capital ? "Grupa" : "grupa"));
      result+=(singular ? "a" : "y");
      return result;
    }
trHierarchicalIndex() [1/2]
QCString TranslatorPolish::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 339 of file translator_pl.h.
    { return "Indeks hierarchiczny"; }
trHierarchicalIndex() [2/2]
QCString TranslatorPolish::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 339 of file translator_pl.h.
    { return "Indeks hierarchiczny"; }
trImplementedFromList() [1/2]
virtual QCString TranslatorPolish::trImplementedFromList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 1250 of file translator_pl.h.
    {
      return "Implementuje "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorPolish::trImplementedFromList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 1250 of file translator_pl.h.
    {
      return "Implementuje "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorPolish::trImplementedInList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 1255 of file translator_pl.h.
    {
      return "Implementowany w "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorPolish::trImplementedInList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 1255 of file translator_pl.h.
    {
      return "Implementowany w "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph() [1/2]
QCString TranslatorPolish::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 947 of file translator_pl.h.
    {
      return "Ten wykres pokazuje, ktre pliki bezporednio lub "
             "porednio zaczaj ten plik:";
    }
trInclByDepGraph() [2/2]
QCString TranslatorPolish::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 947 of file translator_pl.h.
    {
      return "Ten wykres pokazuje, ktre pliki bezporednio lub "
             "porednio zaczaj ten plik:";
    }
trInclDepGraph() [1/2]
QCString TranslatorPolish::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 803 of file translator_pl.h.
    {
      return "Wykres zalenoci zaczania dla "+fName+":";
    }
trInclDepGraph() [2/2]
QCString TranslatorPolish::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 803 of file translator_pl.h.
    {
      return "Wykres zalenoci zaczania dla "+fName+":";
    }
trIncludesFileIn() [1/2]
virtual QCString TranslatorPolish::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1740 of file translator_pl.h.
    {
      return "Zawiera plik w "+name;
    }
References setup::name.
trIncludesFileIn() [2/2]
virtual QCString TranslatorPolish::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1740 of file translator_pl.h.
    {
      return "Zawiera plik w "+name;
    }
References setup::name.
trIncludingInheritedMembers() [1/2]
QCString TranslatorPolish::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 122 of file translator_pl.h.
    { return ", uwzgldniajca wszystkie dziedziczone skadowe."; }
trIncludingInheritedMembers() [2/2]
QCString TranslatorPolish::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 122 of file translator_pl.h.
    { return ", uwzgldniajca wszystkie dziedziczone skadowe."; }
trInheritedByList() [1/2]
QCString TranslatorPolish::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 665 of file translator_pl.h.
    {
      return "Dziedziczona przez "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedByList() [2/2]
QCString TranslatorPolish::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 665 of file translator_pl.h.
    {
      return "Dziedziczona przez "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom() [1/2]
virtual QCString TranslatorPolish::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1837 of file translator_pl.h.
    { return QCString(members)+" dziedziczone z "+what; }
trInheritedFrom() [2/2]
virtual QCString TranslatorPolish::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1837 of file translator_pl.h.
    { return QCString(members)+" dziedziczone z "+what; }
trInheritsList() [1/2]
QCString TranslatorPolish::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 657 of file translator_pl.h.
    {
      return "Dziedziczy "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [2/2]
QCString TranslatorPolish::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 657 of file translator_pl.h.
    {
      return "Dziedziczy "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue() [1/2]
QCString TranslatorPolish::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 838 of file translator_pl.h.
    {
      return "Warto pocztkowa:";
    }
trInitialValue() [2/2]
QCString TranslatorPolish::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 838 of file translator_pl.h.
    {
      return "Warto pocztkowa:";
    }
trInterfaces() [1/2]
virtual QCString TranslatorPolish::trInterfaces () [inline], [virtual]
Used for Java interfaces in the summary section of Java packages
Reimplemented from TranslatorAdapter_1_8_4.
Definition at line 1068 of file translator_pl.h.
    {
      return "Interfejsy";
    }
trInterfaces() [2/2]
virtual QCString TranslatorPolish::trInterfaces () [inline], [virtual]
Used for Java interfaces in the summary section of Java packages
Reimplemented from TranslatorAdapter_1_8_4.
Definition at line 1068 of file translator_pl.h.
    {
      return "Interfejsy";
    }
trInvariant() [1/2]
QCString TranslatorPolish::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 833 of file translator_pl.h.
    {
      return "Niezmiennik";
    }
trInvariant() [2/2]
QCString TranslatorPolish::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 833 of file translator_pl.h.
    {
      return "Niezmiennik";
    }
trISOLang() [1/2]
virtual QCString TranslatorPolish::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 57 of file translator_pl.h.
    {
      return "pl";
    }
trISOLang() [2/2]
virtual QCString TranslatorPolish::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 57 of file translator_pl.h.
    {
      return "pl";
    }
trLegend() [1/2]
QCString TranslatorPolish::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1029 of file translator_pl.h.
    {
      return "legenda";
    }
trLegend() [2/2]
QCString TranslatorPolish::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1029 of file translator_pl.h.
    {
      return "legenda";
    }
trLegendDocs() [1/2]
QCString TranslatorPolish::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 967 of file translator_pl.h.
    {
      return
        "Ta strona wyjania jak interpretowa wykresy, ktre s wygenerowane "
        "przez doxygen.<p>\n"
        "Rozwa nastpujcy przykad:\n"
        "\\code\n"
        "/*! Klasa Niewidzialna z powodu okrojenia */\n"
        "class Niewidzialna { };\n\n"
        "/*! Klasa Okrojona, relacja dziedziczenia jest ukryta */\n"
        "class Okrojona : public Niewidzialna { };\n\n"
        "/* Klasa nie udokumentowana komentarzami doxygen */\n"
        "class Nieudokumentowana { };\n\n"
        "/*! Klasa, ktra jest dziedziczona publicznie */\n"
        "class PublicznaBaza : public Okrojona { };\n\n"
        "/*! Szablon klasy */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Klasa, ktra jest dziedziczona przy uyciu dziedziczenia chronionego */\n"
        "class ChronionaBaza { };\n\n"
        "/*! Klasa, ktra jest dziedziczona prywatnie */\n"
        "class PrywatnaBaza { };\n\n"
        "/*! Klasa, ktra jest uyta przez klas Dziedziczona */\n"
        "class Uzyta { };\n\n"
        "/*! Superklasa, ktra dziedziczy kilka innych klas */\n"
        "class Dziedziczona : public PublicznaBaza,\n"
        " protected ChronionaBaza,\n"
        " private PrywatnaBaza,\n"
        " public Nieudokumentowana,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Uzyta *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Rezultat na nastpujcym wykresie:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        "Prostokty w powyszym wykresie maj nastpujce znaczenie:\n"
        "</p>\n"
        "<ul>\n"
        "<li>Wypeniony czarny prostokt reprezentuje struktur lub klas dla "
        "ktrej zosta wygenerowany wykres.</li>\n"
        "<li>Prostokt z czarn obwolut oznacza udokumentowan struktur lub klas.</li>\n"
        "<li>Prostokt z szar obwolut oznacza nieudokumentowan struktur lub klas.</li>\n"
        "<li>Prostokt z czerwon obwolut oznacza udokumentowan struktur lub klas dla\n"
        "ktrej nie s pokazane wszystkie relacje dziedziczenia/zawierania. Wykres jest "
        "okrojony, jeli nie mieci si w okrelonych brzegach.</li>\n"
        "</ul>\n"
        "<p>\n"
        "Strzaki maj nastpujce znaczenie:\n"
        "<p>\n"
        "<ul>\n"
        "<li>Ciemno niebieska strzaka jest uywana do wizualizacji relacji "
        "dziedziczenia publicznego pomidzy dwiema klasami.</li>\n"
        "<li>Ciemno zielona strzaka jest uywana dla dziedziczenia chronionego.</li>\n"
        "<li>Ciemno czerwona strzaka jest uywana dla dziedziczenia prywatnego.</li>\n"
        "<li>Fioletowa przerywana strzaka jest uywana jeli klasa jest zawarta "
        "lub uyta przez inn klas. Strzaka jest podpisana zmienn(ymi) "
        "przez ktre wskazywana klasa lub struktura jest dostpna. </li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
QCString TranslatorPolish::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 967 of file translator_pl.h.
    {
      return
        "Ta strona wyjania jak interpretowa wykresy, ktre s wygenerowane "
        "przez doxygen.<p>\n"
        "Rozwa nastpujcy przykad:\n"
        "\\code\n"
        "/*! Klasa Niewidzialna z powodu okrojenia */\n"
        "class Niewidzialna { };\n\n"
        "/*! Klasa Okrojona, relacja dziedziczenia jest ukryta */\n"
        "class Okrojona : public Niewidzialna { };\n\n"
        "/* Klasa nie udokumentowana komentarzami doxygen */\n"
        "class Nieudokumentowana { };\n\n"
        "/*! Klasa, ktra jest dziedziczona publicznie */\n"
        "class PublicznaBaza : public Okrojona { };\n\n"
        "/*! Szablon klasy */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Klasa, ktra jest dziedziczona przy uyciu dziedziczenia chronionego */\n"
        "class ChronionaBaza { };\n\n"
        "/*! Klasa, ktra jest dziedziczona prywatnie */\n"
        "class PrywatnaBaza { };\n\n"
        "/*! Klasa, ktra jest uyta przez klas Dziedziczona */\n"
        "class Uzyta { };\n\n"
        "/*! Superklasa, ktra dziedziczy kilka innych klas */\n"
        "class Dziedziczona : public PublicznaBaza,\n"
        " protected ChronionaBaza,\n"
        " private PrywatnaBaza,\n"
        " public Nieudokumentowana,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Uzyta *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Rezultat na nastpujcym wykresie:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        "Prostokty w powyszym wykresie maj nastpujce znaczenie:\n"
        "</p>\n"
        "<ul>\n"
        "<li>Wypeniony czarny prostokt reprezentuje struktur lub klas dla "
        "ktrej zosta wygenerowany wykres.</li>\n"
        "<li>Prostokt z czarn obwolut oznacza udokumentowan struktur lub klas.</li>\n"
        "<li>Prostokt z szar obwolut oznacza nieudokumentowan struktur lub klas.</li>\n"
        "<li>Prostokt z czerwon obwolut oznacza udokumentowan struktur lub klas dla\n"
        "ktrej nie s pokazane wszystkie relacje dziedziczenia/zawierania. Wykres jest "
        "okrojony, jeli nie mieci si w okrelonych brzegach.</li>\n"
        "</ul>\n"
        "<p>\n"
        "Strzaki maj nastpujce znaczenie:\n"
        "<p>\n"
        "<ul>\n"
        "<li>Ciemno niebieska strzaka jest uywana do wizualizacji relacji "
        "dziedziczenia publicznego pomidzy dwiema klasami.</li>\n"
        "<li>Ciemno zielona strzaka jest uywana dla dziedziczenia chronionego.</li>\n"
        "<li>Ciemno czerwona strzaka jest uywana dla dziedziczenia prywatnego.</li>\n"
        "<li>Fioletowa przerywana strzaka jest uywana jeli klasa jest zawarta "
        "lub uyta przez inn klas. Strzaka jest podpisana zmienn(ymi) "
        "przez ktre wskazywana klasa lub struktura jest dostpna. </li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
QCString TranslatorPolish::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 962 of file translator_pl.h.
    {
      return "Legenda wykresu";
    }
trLegendTitle() [2/2]
QCString TranslatorPolish::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 962 of file translator_pl.h.
    {
      return "Legenda wykresu";
    }
trListOfAllMembers() [1/2]
QCString TranslatorPolish::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 110 of file translator_pl.h.
    { return "Lista wszystkich skadowych"; }
trListOfAllMembers() [2/2]
QCString TranslatorPolish::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 110 of file translator_pl.h.
    { return "Lista wszystkich skadowych"; }
trLoading() [1/2]
virtual QCString TranslatorPolish::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1700 of file translator_pl.h.
    {
      return "Wczytywanie...";
    }
trLoading() [2/2]
virtual QCString TranslatorPolish::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1700 of file translator_pl.h.
    {
      return "Wczytywanie...";
    }
trMainPage() [1/2]
QCString TranslatorPolish::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 762 of file translator_pl.h.
    { return "Strona gwna"; }
trMainPage() [2/2]
QCString TranslatorPolish::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 762 of file translator_pl.h.
    { return "Strona gwna"; }
trMember() [1/2]
virtual QCString TranslatorPolish::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1202 of file translator_pl.h.
    {
      QCString result((first_capital ? "Skadow" : "skadow"));
      result+=(singular ? "a" : "e");
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorPolish::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1202 of file translator_pl.h.
    {
      QCString result((first_capital ? "Skadow" : "skadow"));
      result+=(singular ? "a" : "e");
      return result;
    }
trMemberDataDocumentation() [1/2]
QCString TranslatorPolish::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 93 of file translator_pl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentacja pl";
      }
      else
      {
        return "Dokumentacja atrybutw skadowych";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
QCString TranslatorPolish::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 93 of file translator_pl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentacja pl";
      }
      else
      {
        return "Dokumentacja atrybutw skadowych";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
QCString TranslatorPolish::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 85 of file translator_pl.h.
    { return "Dokumentacja skadowych wyliczanych"; }
trMemberEnumerationDocumentation() [2/2]
QCString TranslatorPolish::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 85 of file translator_pl.h.
    { return "Dokumentacja skadowych wyliczanych"; }
trMemberFunctionDocumentation() [1/2]
QCString TranslatorPolish::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 89 of file translator_pl.h.
    { return "Dokumentacja funkcji skadowych"; }
trMemberFunctionDocumentation() [2/2]
QCString TranslatorPolish::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 89 of file translator_pl.h.
    { return "Dokumentacja funkcji skadowych"; }
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorPolish::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1494 of file translator_pl.h.
    { return "Dokumentacja skadowej funkcji/podprogramu"; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorPolish::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1494 of file translator_pl.h.
    { return "Dokumentacja skadowej funkcji/podprogramu"; }
trMemberList() [1/2]
QCString TranslatorPolish::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 114 of file translator_pl.h.
    { return "Lista skadowych"; }
trMemberList() [2/2]
QCString TranslatorPolish::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 114 of file translator_pl.h.
    { return "Lista skadowych"; }
trMemberTypedefDocumentation() [1/2]
QCString TranslatorPolish::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 81 of file translator_pl.h.
    { return "Dokumentacja skadowych definicji typu"; }
trMemberTypedefDocumentation() [2/2]
QCString TranslatorPolish::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 81 of file translator_pl.h.
    { return "Dokumentacja skadowych definicji typu"; }
trModule() [1/2]
virtual QCString TranslatorPolish::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1633 of file translator_pl.h.
    {
      QCString result((first_capital ? "Modu" : "modu"));
      if (!singular) result+="y";
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorPolish::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1633 of file translator_pl.h.
    {
      QCString result((first_capital ? "Modu" : "modu"));
      if (!singular) result+="y";
      return result;
    }
trModuleDocumentation() [1/2]
QCString TranslatorPolish::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 366 of file translator_pl.h.
    { return "Dokumentacja grup"; }
trModuleDocumentation() [2/2]
QCString TranslatorPolish::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 366 of file translator_pl.h.
    { return "Dokumentacja grup"; }
trModuleIndex() [1/2]
QCString TranslatorPolish::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 333 of file translator_pl.h.
    { return "Indeks grup"; }
trModuleIndex() [2/2]
QCString TranslatorPolish::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 333 of file translator_pl.h.
    { return "Indeks grup"; }
trModuleReference() [1/2]
virtual QCString TranslatorPolish::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1595 of file translator_pl.h.
    {
      QCString result="Dokumentacja moduu ";
      result+=namespaceName;
      return result;
    }
trModuleReference() [2/2]
virtual QCString TranslatorPolish::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1595 of file translator_pl.h.
    {
      QCString result="Dokumentacja moduu ";
      result+=namespaceName;
      return result;
    }
trModules() [1/2]
QCString TranslatorPolish::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 152 of file translator_pl.h.
    { return "Moduy"; }
trModules() [2/2]
QCString TranslatorPolish::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 152 of file translator_pl.h.
    { return "Moduy"; }
trModulesDescription() [1/2]
QCString TranslatorPolish::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 320 of file translator_pl.h.
    { return "Tutaj znajduje si lista wszystkich grup:"; }
trModulesDescription() [2/2]
QCString TranslatorPolish::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 320 of file translator_pl.h.
    { return "Tutaj znajduje si lista wszystkich grup:"; }
trModulesIndex() [1/2]
virtual QCString TranslatorPolish::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1626 of file translator_pl.h.
    { return "Indeks moduu"; }
trModulesIndex() [2/2]
virtual QCString TranslatorPolish::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1626 of file translator_pl.h.
    { return "Indeks moduu"; }
trModulesList() [1/2]
virtual QCString TranslatorPolish::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1561 of file translator_pl.h.
    { return "Lista moduw"; }
trModulesList() [2/2]
virtual QCString TranslatorPolish::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1561 of file translator_pl.h.
    { return "Lista moduw"; }
trModulesListDescription() [1/2]
virtual QCString TranslatorPolish::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1565 of file translator_pl.h.
    {
      QCString result="Tutaj znajduje si lista wszystkich ";
      if (!extractAll) result+="udokumentowanych ";
      result+="moduw z ich krtkimi opisami:";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorPolish::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1565 of file translator_pl.h.
    {
      QCString result="Tutaj znajduje si lista wszystkich ";
      if (!extractAll) result+="udokumentowanych ";
      result+="moduw z ich krtkimi opisami:";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorPolish::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1607 of file translator_pl.h.
    {
      QCString result="Tutaj znajduje si lista wszystkich ";
      if (!extractAll) result+="udokumentowanych ";
      result+="skadowych moduw wraz z odnonikami do ";
      if (extractAll)
      {
        result+="dokumentacji moduu dla kadej skadowej:";
      }
      else
      {
        result+="moduw, do ktrych skadowe te nale:";
      }
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorPolish::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1607 of file translator_pl.h.
    {
      QCString result="Tutaj znajduje si lista wszystkich ";
      if (!extractAll) result+="udokumentowanych ";
      result+="skadowych moduw wraz z odnonikami do ";
      if (extractAll)
      {
        result+="dokumentacji moduu dla kadej skadowej:";
      }
      else
      {
        result+="moduw, do ktrych skadowe te nale:";
      }
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorPolish::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1603 of file translator_pl.h.
    { return "Skadowe moduu"; }
trModulesMembers() [2/2]
virtual QCString TranslatorPolish::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1603 of file translator_pl.h.
    { return "Skadowe moduu"; }
trMonth() [1/2]
virtual QCString TranslatorPolish::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1779 of file translator_pl.h.
    {
      static const char *months_short[] = { "sty", "lut", "mar", "kwi", "maj", "cze", "lip", "sie", "wrz", "pa", "lis", "gru" };
      static const char *months_full[] = { "stycze", "luty", "marzec", "kwiecie", "maj", "czerwiec", "lipiec", "sierpie", "wrzesie", "padziernik", "listopad", "grudzie" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMonth() [2/2]
virtual QCString TranslatorPolish::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1779 of file translator_pl.h.
    {
      static const char *months_short[] = { "sty", "lut", "mar", "kwi", "maj", "cze", "lip", "sie", "wrz", "pa", "lis", "gru" };
      static const char *months_full[] = { "stycze", "luty", "marzec", "kwiecie", "maj", "czerwiec", "lipiec", "sierpie", "wrzesie", "padziernik", "listopad", "grudzie" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore() [1/2]
QCString TranslatorPolish::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 106 of file translator_pl.h.
    { return "Wicej..."; }
trMore() [2/2]
QCString TranslatorPolish::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 106 of file translator_pl.h.
    { return "Wicej..."; }
trNamespace() [1/2]
virtual QCString TranslatorPolish::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1168 of file translator_pl.h.
    {
      QCString result((first_capital ? "Przestrze" : "przestrze"));
      result+=(singular ? "" : "nie");
      result+=" nazw";
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorPolish::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1168 of file translator_pl.h.
    {
      QCString result((first_capital ? "Przestrze" : "przestrze"));
      result+=(singular ? "" : "nie");
      result+=" nazw";
      return result;
    }
trNamespaceDocumentation() [1/2]
QCString TranslatorPolish::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 711 of file translator_pl.h.
    { return "Dokumentacja przestrzeni nazw"; }
trNamespaceDocumentation() [2/2]
QCString TranslatorPolish::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 711 of file translator_pl.h.
    { return "Dokumentacja przestrzeni nazw"; }
trNamespaceIndex() [1/2]
QCString TranslatorPolish::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 705 of file translator_pl.h.
    { return "Indeks przestrzeni nazw"; }
trNamespaceIndex() [2/2]
QCString TranslatorPolish::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 705 of file translator_pl.h.
    { return "Indeks przestrzeni nazw"; }
trNamespaceList() [1/2]
QCString TranslatorPolish::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 537 of file translator_pl.h.
    { return "Lista przestrzeni nazw"; }
trNamespaceList() [2/2]
QCString TranslatorPolish::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 537 of file translator_pl.h.
    { return "Lista przestrzeni nazw"; }
trNamespaceListDescription() [1/2]
QCString TranslatorPolish::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 541 of file translator_pl.h.
    {
      QCString result="Tutaj znajduj si wszystkie ";
      if (!extractAll) result+="udokumentowane ";
      result+="przestrzenie nazw wraz z ich krtkimi opisami:";
      return result;
    }
trNamespaceListDescription() [2/2]
QCString TranslatorPolish::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 541 of file translator_pl.h.
    {
      QCString result="Tutaj znajduj si wszystkie ";
      if (!extractAll) result+="udokumentowane ";
      result+="przestrzenie nazw wraz z ich krtkimi opisami:";
      return result;
    }
trNamespaceMemberDescription() [1/2]
QCString TranslatorPolish::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 691 of file translator_pl.h.
    {
      QCString result="Tutaj znajduje si lista wszystkich ";
      if (!extractAll) result+="udokumentowanych ";
      result+="skadowych wraz z odnonikami do ";
      if (extractAll)
        result+="dokumentacji przestrzeni nazw dla kadej skadowej:";
      else
        result+="przestrzeni nazw do ktrych skadowe te nale:";
      return result;
    }
trNamespaceMemberDescription() [2/2]
QCString TranslatorPolish::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 691 of file translator_pl.h.
    {
      QCString result="Tutaj znajduje si lista wszystkich ";
      if (!extractAll) result+="udokumentowanych ";
      result+="skadowych wraz z odnonikami do ";
      if (extractAll)
        result+="dokumentacji przestrzeni nazw dla kadej skadowej:";
      else
        result+="przestrzeni nazw do ktrych skadowe te nale:";
      return result;
    }
trNamespaceMembers() [1/2]
QCString TranslatorPolish::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 687 of file translator_pl.h.
    { return "Skadowe przestrzeni nazw"; }
trNamespaceMembers() [2/2]
QCString TranslatorPolish::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 687 of file translator_pl.h.
    { return "Skadowe przestrzeni nazw"; }
trNamespaceReference() [1/2]
QCString TranslatorPolish::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 600 of file translator_pl.h.
    {
      QCString result="Dokumentacja przestrzeni nazw ";
      result+=namespaceName;
      return result;
    }
trNamespaceReference() [2/2]
QCString TranslatorPolish::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 600 of file translator_pl.h.
    {
      QCString result="Dokumentacja przestrzeni nazw ";
      result+=namespaceName;
      return result;
    }
trNamespaces() [1/2]
QCString TranslatorPolish::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 721 of file translator_pl.h.
    { return "Przestrzenie nazw"; }
trNamespaces() [2/2]
QCString TranslatorPolish::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 721 of file translator_pl.h.
    { return "Przestrzenie nazw"; }
trNoMatches() [1/2]
virtual QCString TranslatorPolish::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1718 of file translator_pl.h.
    {
      return "Brak dopasowa";
    }
trNoMatches() [2/2]
virtual QCString TranslatorPolish::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1718 of file translator_pl.h.
    {
      return "Brak dopasowa";
    }
trNote() [1/2]
QCString TranslatorPolish::trNote () [inline], [virtual]
Implements Translator.
Definition at line 868 of file translator_pl.h.
    {
      return "Nota";
    }
trNote() [2/2]
QCString TranslatorPolish::trNote () [inline], [virtual]
Implements Translator.
Definition at line 868 of file translator_pl.h.
    {
      return "Nota";
    }
trOverloadText() [1/2]
virtual QCString TranslatorPolish::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1467 of file translator_pl.h.
    {
      return "To jest metoda przeciona, udostpniona dla wygody. "
             "Rni si od powyszej metody tylko zestawem akceptowanych argumentw.";
    }
trOverloadText() [2/2]
virtual QCString TranslatorPolish::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1467 of file translator_pl.h.
    {
      return "To jest metoda przeciona, udostpniona dla wygody. "
             "Rni si od powyszej metody tylko zestawem akceptowanych argumentw.";
    }
trPackage() [1/2]
virtual QCString TranslatorPolish::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1085 of file translator_pl.h.
    {
      return "Pakiet "+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorPolish::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1085 of file translator_pl.h.
    {
      return "Pakiet "+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorPolish::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1332 of file translator_pl.h.
    {
      return "Atrybuty pakietu";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorPolish::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1332 of file translator_pl.h.
    {
      return "Atrybuty pakietu";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorPolish::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1314 of file translator_pl.h.
    {
      return "Funkcje pakietu";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorPolish::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1314 of file translator_pl.h.
    {
      return "Funkcje pakietu";
    }
trPackageListDescription() [1/2]
virtual QCString TranslatorPolish::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1090 of file translator_pl.h.
    {
      return "Oto lista pakietw wraz z krtkim opisem (o ile jest dostpny):";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorPolish::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1090 of file translator_pl.h.
    {
      return "Oto lista pakietw wraz z krtkim opisem (o ile jest dostpny):";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorPolish::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1318 of file translator_pl.h.
    {
      return "Skadowe pakietu";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorPolish::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1318 of file translator_pl.h.
    {
      return "Skadowe pakietu";
    }
trPackages() [1/2]
virtual QCString TranslatorPolish::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1095 of file translator_pl.h.
    {
      return "Pakiety";
    }
trPackages() [2/2]
virtual QCString TranslatorPolish::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1095 of file translator_pl.h.
    {
      return "Pakiety";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorPolish::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1307 of file translator_pl.h.
    {
      return "Typy pakietu";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorPolish::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1307 of file translator_pl.h.
    {
      return "Typy pakietu";
    }
trPage() [1/2]
virtual QCString TranslatorPolish::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1191 of file translator_pl.h.
    {
      QCString result((first_capital ? "Stron" : "stron"));
      result+=(singular ? "a" : "y");
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorPolish::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1191 of file translator_pl.h.
    {
      QCString result((first_capital ? "Stron" : "stron"));
      result+=(singular ? "a" : "y");
      return result;
    }
trPageAbbreviation() [1/2]
QCString TranslatorPolish::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 768 of file translator_pl.h.
    { return "str."; }
trPageAbbreviation() [2/2]
QCString TranslatorPolish::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 768 of file translator_pl.h.
    { return "str."; }
trPageIndex() [1/2]
QCString TranslatorPolish::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 859 of file translator_pl.h.
    {
      return "Indeks stron";
    }
trPageIndex() [2/2]
QCString TranslatorPolish::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 859 of file translator_pl.h.
    {
      return "Indeks stron";
    }
trParameters() [1/2]
QCString TranslatorPolish::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 523 of file translator_pl.h.
    { return "Parametry"; }
trParameters() [2/2]
QCString TranslatorPolish::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 523 of file translator_pl.h.
    { return "Parametry"; }
trPostcondition() [1/2]
QCString TranslatorPolish::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 828 of file translator_pl.h.
    {
      return "Warunek kocowy";
    }
trPostcondition() [2/2]
QCString TranslatorPolish::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 828 of file translator_pl.h.
    {
      return "Warunek kocowy";
    }
trPrecondition() [1/2]
QCString TranslatorPolish::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 823 of file translator_pl.h.
    {
      return "Warunek wstpny";
    }
trPrecondition() [2/2]
QCString TranslatorPolish::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 823 of file translator_pl.h.
    {
      return "Warunek wstpny";
    }
trPrivateAttribs() [1/2]
QCString TranslatorPolish::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 907 of file translator_pl.h.
    {
      return "Atrybuty prywatne";
    }
trPrivateAttribs() [2/2]
QCString TranslatorPolish::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 907 of file translator_pl.h.
    {
      return "Atrybuty prywatne";
    }
trPrivateMembers() [1/2]
QCString TranslatorPolish::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 622 of file translator_pl.h.
    { return "Metody prywatne"; }
trPrivateMembers() [2/2]
QCString TranslatorPolish::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 622 of file translator_pl.h.
    { return "Metody prywatne"; }
trPrivateSlots() [1/2]
QCString TranslatorPolish::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 624 of file translator_pl.h.
    { return "Sloty prywatne"; }
trPrivateSlots() [2/2]
QCString TranslatorPolish::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 624 of file translator_pl.h.
    { return "Sloty prywatne"; }
trPrivateTypes() [1/2]
QCString TranslatorPolish::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 903 of file translator_pl.h.
    {
      return "Typy prywatne";
    }
trPrivateTypes() [2/2]
QCString TranslatorPolish::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 903 of file translator_pl.h.
    {
      return "Typy prywatne";
    }
trProperties() [1/2]
virtual QCString TranslatorPolish::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1054 of file translator_pl.h.
    {
      return "Waciwoci";
    }
trProperties() [2/2]
virtual QCString TranslatorPolish::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1054 of file translator_pl.h.
    {
      return "Waciwoci";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorPolish::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1059 of file translator_pl.h.
    {
      return "Dokumentacja waciwoci";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorPolish::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1059 of file translator_pl.h.
    {
      return "Dokumentacja waciwoci";
    }
trProtectedAttribs() [1/2]
QCString TranslatorPolish::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 895 of file translator_pl.h.
    {
      return "Atrybuty chronione";
    }
trProtectedAttribs() [2/2]
QCString TranslatorPolish::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 895 of file translator_pl.h.
    {
      return "Atrybuty chronione";
    }
trProtectedMembers() [1/2]
QCString TranslatorPolish::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 616 of file translator_pl.h.
    { return "Metody chronione"; }
trProtectedMembers() [2/2]
QCString TranslatorPolish::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 616 of file translator_pl.h.
    { return "Metody chronione"; }
trProtectedSlots() [1/2]
QCString TranslatorPolish::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 618 of file translator_pl.h.
    { return "Sloty chronione"; }
trProtectedSlots() [2/2]
QCString TranslatorPolish::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 618 of file translator_pl.h.
    { return "Sloty chronione"; }
trProtectedTypes() [1/2]
QCString TranslatorPolish::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 891 of file translator_pl.h.
    {
      return "Typy chronione";
    }
trProtectedTypes() [2/2]
QCString TranslatorPolish::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 891 of file translator_pl.h.
    {
      return "Typy chronione";
    }
trPublicAttribs() [1/2]
QCString TranslatorPolish::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 876 of file translator_pl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Pola danych";
      }
      else
      {
        return "Atrybuty publiczne";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
QCString TranslatorPolish::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 876 of file translator_pl.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Pola danych";
      }
      else
      {
        return "Atrybuty publiczne";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
QCString TranslatorPolish::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 608 of file translator_pl.h.
    { return "Metody publiczne"; }
trPublicMembers() [2/2]
QCString TranslatorPolish::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 608 of file translator_pl.h.
    { return "Metody publiczne"; }
trPublicSlots() [1/2]
QCString TranslatorPolish::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 610 of file translator_pl.h.
    { return "Sloty publiczne"; }
trPublicSlots() [2/2]
QCString TranslatorPolish::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 610 of file translator_pl.h.
    { return "Sloty publiczne"; }
trPublicTypes() [1/2]
QCString TranslatorPolish::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 872 of file translator_pl.h.
    {
      return "Typy publiczne";
    }
trPublicTypes() [2/2]
QCString TranslatorPolish::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 872 of file translator_pl.h.
    {
      return "Typy publiczne";
    }
trReferencedBy() [1/2]
QCString TranslatorPolish::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 935 of file translator_pl.h.
    {
      return "Odwoania w";
    }
trReferencedBy() [2/2]
QCString TranslatorPolish::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 935 of file translator_pl.h.
    {
      return "Odwoania w";
    }
trReferenceManual() [1/2]
QCString TranslatorPolish::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 401 of file translator_pl.h.
    { return "Podrcznik"; }
trReferenceManual() [2/2]
QCString TranslatorPolish::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 401 of file translator_pl.h.
    { return "Podrcznik"; }
trReferences() [1/2]
virtual QCString TranslatorPolish::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1239 of file translator_pl.h.
    {
      return "Odwouje si do";
    }
trReferences() [2/2]
virtual QCString TranslatorPolish::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1239 of file translator_pl.h.
    {
      return "Odwouje si do";
    }
trReimplementedFromList() [1/2]
QCString TranslatorPolish::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 673 of file translator_pl.h.
    {
      return "Reimplementowana z "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedFromList() [2/2]
QCString TranslatorPolish::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 673 of file translator_pl.h.
    {
      return "Reimplementowana z "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [1/2]
QCString TranslatorPolish::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 681 of file translator_pl.h.
    {
      return "Reimplementowana w "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [2/2]
QCString TranslatorPolish::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 681 of file translator_pl.h.
    {
      return "Reimplementowana w "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
QCString TranslatorPolish::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 562 of file translator_pl.h.
    { return "Dokumentacja przyjaci i funkcji zwizanych"; }
trRelatedFunctionDocumentation() [2/2]
QCString TranslatorPolish::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 562 of file translator_pl.h.
    { return "Dokumentacja przyjaci i funkcji zwizanych"; }
trRelatedFunctions() [1/2]
QCString TranslatorPolish::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 69 of file translator_pl.h.
    { return "Funkcje powizane"; }
trRelatedFunctions() [2/2]
QCString TranslatorPolish::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 69 of file translator_pl.h.
    { return "Funkcje powizane"; }
trRelatedPages() [1/2]
QCString TranslatorPolish::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 203 of file translator_pl.h.
    { return "Dodatkowe strony"; }
trRelatedPages() [2/2]
QCString TranslatorPolish::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 203 of file translator_pl.h.
    { return "Dodatkowe strony"; }
trRelatedPagesDescription() [1/2]
QCString TranslatorPolish::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 316 of file translator_pl.h.
    { return "Tutaj znajduje si lista wszystkich stron dokumentacji:"; }
trRelatedPagesDescription() [2/2]
QCString TranslatorPolish::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 316 of file translator_pl.h.
    { return "Tutaj znajduje si lista wszystkich stron dokumentacji:"; }
trRelatedSubscript() [1/2]
QCString TranslatorPolish::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 73 of file translator_pl.h.
    { return "(Zauwa, e to nie s metody klas.)"; }
trRelatedSubscript() [2/2]
QCString TranslatorPolish::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 73 of file translator_pl.h.
    { return "(Zauwa, e to nie s metody klas.)"; }
trRemarks() [1/2]
QCString TranslatorPolish::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 939 of file translator_pl.h.
    {
      return "Spostrzeenia";
    }
trRemarks() [2/2]
QCString TranslatorPolish::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 939 of file translator_pl.h.
    {
      return "Spostrzeenia";
    }
trReturns() [1/2]
QCString TranslatorPolish::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 515 of file translator_pl.h.
    { return "Zwraca"; }
trReturns() [2/2]
QCString TranslatorPolish::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 515 of file translator_pl.h.
    { return "Zwraca"; }
trReturnValues() [1/2]
QCString TranslatorPolish::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 757 of file translator_pl.h.
    { return "Zwracane wartoci"; }
trReturnValues() [2/2]
QCString TranslatorPolish::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 757 of file translator_pl.h.
    { return "Zwracane wartoci"; }
trRTFansicp() [1/2]
virtual QCString TranslatorPolish::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
Implements Translator.
Definition at line 1125 of file translator_pl.h.
    {
      return "1250";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorPolish::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
Implements Translator.
Definition at line 1125 of file translator_pl.h.
    {
      return "1250";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorPolish::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
Implements Translator.
Definition at line 1131 of file translator_pl.h.
    {
      return "238";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorPolish::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
Implements Translator.
Definition at line 1131 of file translator_pl.h.
    {
      return "238";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorPolish::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1137 of file translator_pl.h.
    {
      return "Indeks";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorPolish::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1137 of file translator_pl.h.
    {
      return "Indeks";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorPolish::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1267 of file translator_pl.h.
    {
      return "Spis treci";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorPolish::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1267 of file translator_pl.h.
    {
      return "Spis treci";
    }
trSearch() [1/2]
QCString TranslatorPolish::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 211 of file translator_pl.h.
    { return "Szukaj"; }
trSearch() [2/2]
QCString TranslatorPolish::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 211 of file translator_pl.h.
    { return "Szukaj"; }
trSearching() [1/2]
virtual QCString TranslatorPolish::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1712 of file translator_pl.h.
    {
      return "Szukanie...";
    }
trSearching() [2/2]
virtual QCString TranslatorPolish::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1712 of file translator_pl.h.
    {
      return "Szukanie...";
    }
trSearchMatches() [1/2]
virtual QCString TranslatorPolish::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1405 of file translator_pl.h.
    {
      return "Pasujce sowa:";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorPolish::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1405 of file translator_pl.h.
    {
      return "Pasujce sowa:";
    }
trSearchResults() [1/2]
virtual QCString TranslatorPolish::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1380 of file translator_pl.h.
    {
      if (numDocuments==0)
      {
        return "Niestety aden dokument nie pasuje do twojego zapytania.";
      }
      else if (numDocuments==1)
      {
        return "Znaleziono <b>1</b> dokument pasujcy do twojego zapytania.";
      }
      int count = numDocuments % 10;
      if ((count>=2) && (count<=4))
      {
        return "Znaleziono <b>$num</b> dokumenty pasujce do twojego zapytania. "
               "Najlepiej pasujce dokumenty wywietlane s na pocztku listy.";
      }
      else
      {
        return "Znaleziono <b>$num</b> dokumentw pasujcych do twojego zapytania. "
               "Najlepiej pasujce dokumenty wywietlane s na pocztku listy.";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorPolish::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1380 of file translator_pl.h.
    {
      if (numDocuments==0)
      {
        return "Niestety aden dokument nie pasuje do twojego zapytania.";
      }
      else if (numDocuments==1)
      {
        return "Znaleziono <b>1</b> dokument pasujcy do twojego zapytania.";
      }
      int count = numDocuments % 10;
      if ((count>=2) && (count<=4))
      {
        return "Znaleziono <b>$num</b> dokumenty pasujce do twojego zapytania. "
               "Najlepiej pasujce dokumenty wywietlane s na pocztku listy.";
      }
      else
      {
        return "Znaleziono <b>$num</b> dokumentw pasujcych do twojego zapytania. "
               "Najlepiej pasujce dokumenty wywietlane s na pocztku listy.";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorPolish::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1368 of file translator_pl.h.
    {
      return "Wyniki szukania";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorPolish::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1368 of file translator_pl.h.
    {
      return "Wyniki szukania";
    }
trSeeAlso() [1/2]
QCString TranslatorPolish::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 519 of file translator_pl.h.
    { return "Zobacz rwnie"; }
trSeeAlso() [2/2]
QCString TranslatorPolish::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 519 of file translator_pl.h.
    { return "Zobacz rwnie"; }
trSignals() [1/2]
QCString TranslatorPolish::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 612 of file translator_pl.h.
    { return "Sygnay"; }
trSignals() [2/2]
QCString TranslatorPolish::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 612 of file translator_pl.h.
    { return "Sygnay"; }
trSince() [1/2]
QCString TranslatorPolish::trSince () [inline], [virtual]
Implements Translator.
Definition at line 952 of file translator_pl.h.
    {
      return "Od";
    }
trSince() [2/2]
QCString TranslatorPolish::trSince () [inline], [virtual]
Implements Translator.
Definition at line 952 of file translator_pl.h.
    {
      return "Od";
    }
trSourceFile() [1/2]
virtual QCString TranslatorPolish::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1416 of file translator_pl.h.
    {
      return "Plik rdowy " + filename;
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorPolish::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1416 of file translator_pl.h.
    {
      return "Plik rdowy " + filename;
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorPolish::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1339 of file translator_pl.h.
    {
      return "Statyczne atrybuty pakietu";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorPolish::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1339 of file translator_pl.h.
    {
      return "Statyczne atrybuty pakietu";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorPolish::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1325 of file translator_pl.h.
    {
      return "Statyczne funkcje pakietu";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorPolish::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1325 of file translator_pl.h.
    {
      return "Statyczne funkcje pakietu";
    }
trStaticPrivateAttribs() [1/2]
QCString TranslatorPolish::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 911 of file translator_pl.h.
    {
      return "Statyczne atrybuty prywatne";
    }
trStaticPrivateAttribs() [2/2]
QCString TranslatorPolish::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 911 of file translator_pl.h.
    {
      return "Statyczne atrybuty prywatne";
    }
trStaticPrivateMembers() [1/2]
QCString TranslatorPolish::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 626 of file translator_pl.h.
    { return "Statyczne metody prywatne"; }
trStaticPrivateMembers() [2/2]
QCString TranslatorPolish::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 626 of file translator_pl.h.
    { return "Statyczne metody prywatne"; }
trStaticProtectedAttribs() [1/2]
QCString TranslatorPolish::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 899 of file translator_pl.h.
    {
      return "Statyczne atrybuty chronione";
    }
trStaticProtectedAttribs() [2/2]
QCString TranslatorPolish::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 899 of file translator_pl.h.
    {
      return "Statyczne atrybuty chronione";
    }
trStaticProtectedMembers() [1/2]
QCString TranslatorPolish::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 620 of file translator_pl.h.
    { return "Statyczne metody chronione"; }
trStaticProtectedMembers() [2/2]
QCString TranslatorPolish::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 620 of file translator_pl.h.
    { return "Statyczne metody chronione"; }
trStaticPublicAttribs() [1/2]
QCString TranslatorPolish::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 887 of file translator_pl.h.
    {
      return "Statyczne atrybuty publiczne";
    }
trStaticPublicAttribs() [2/2]
QCString TranslatorPolish::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 887 of file translator_pl.h.
    {
      return "Statyczne atrybuty publiczne";
    }
trStaticPublicMembers() [1/2]
QCString TranslatorPolish::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 614 of file translator_pl.h.
    { return "Statyczne metody publiczne"; }
trStaticPublicMembers() [2/2]
QCString TranslatorPolish::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 614 of file translator_pl.h.
    { return "Statyczne metody publiczne"; }
trSubprogram() [1/2]
virtual QCString TranslatorPolish::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1676 of file translator_pl.h.
    {
      QCString result((first_capital ? "Podprogram" : "podprogram"));
      if (!singular) result+="y";
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorPolish::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1676 of file translator_pl.h.
    {
      QCString result((first_capital ? "Podprogram" : "podprogram"));
      if (!singular) result+="y";
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorPolish::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1551 of file translator_pl.h.
    { return "Dokumentacja funkcji/podprogramu"; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorPolish::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1551 of file translator_pl.h.
    { return "Dokumentacja funkcji/podprogramu"; }
trSubprograms() [1/2]
virtual QCString TranslatorPolish::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1545 of file translator_pl.h.
    { return "Funkcje/podprogramy"; }
trSubprograms() [2/2]
virtual QCString TranslatorPolish::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1545 of file translator_pl.h.
    { return "Funkcje/podprogramy"; }
trTemplateParameters() [1/2]
virtual QCString TranslatorPolish::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1818 of file translator_pl.h.
    { return "Parametry Szablonu"; }
trTemplateParameters() [2/2]
virtual QCString TranslatorPolish::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1818 of file translator_pl.h.
    { return "Parametry Szablonu"; }
trTest() [1/2]
QCString TranslatorPolish::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1039 of file translator_pl.h.
    {
      return "Test";
    }
trTest() [2/2]
QCString TranslatorPolish::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1039 of file translator_pl.h.
    {
      return "Test";
    }
trTestList() [1/2]
QCString TranslatorPolish::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1044 of file translator_pl.h.
    {
      return "Lista testu";
    }
trTestList() [2/2]
QCString TranslatorPolish::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1044 of file translator_pl.h.
    {
      return "Lista testu";
    }
trThisIsTheListOfAllMembers() [1/2]
QCString TranslatorPolish::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 118 of file translator_pl.h.
    { return "To jest kompletna lista skadowych dla "; }
trThisIsTheListOfAllMembers() [2/2]
QCString TranslatorPolish::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 118 of file translator_pl.h.
    { return "To jest kompletna lista skadowych dla "; }
trTodo() [1/2]
QCString TranslatorPolish::trTodo () [inline], [virtual]
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 921 of file translator_pl.h.
    {
      return "Do zrobienia";
    }
trTodo() [2/2]
QCString TranslatorPolish::trTodo () [inline], [virtual]
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 921 of file translator_pl.h.
    {
      return "Do zrobienia";
    }
trTodoList() [1/2]
QCString TranslatorPolish::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 926 of file translator_pl.h.
    {
      return "Lista rzeczy do zrobienia";
    }
trTodoList() [2/2]
QCString TranslatorPolish::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 926 of file translator_pl.h.
    {
      return "Lista rzeczy do zrobienia";
    }
trType() [1/2]
virtual QCString TranslatorPolish::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1666 of file translator_pl.h.
    {
      QCString result((first_capital ? "Typ" : "typ"));
      if (!singular) result+="y";
      return result;
    }
trType() [2/2]
virtual QCString TranslatorPolish::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1666 of file translator_pl.h.
    {
      QCString result((first_capital ? "Typ" : "typ"));
      if (!singular) result+="y";
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorPolish::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1684 of file translator_pl.h.
    {
      return "Wizy typw"; //TODO check if it is correct translation
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorPolish::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1684 of file translator_pl.h.
    {
      return "Wizy typw"; //TODO check if it is correct translation
    }
trTypedefDocumentation() [1/2]
QCString TranslatorPolish::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 449 of file translator_pl.h.
    { return "Dokumentacja definicji typw"; }
trTypedefDocumentation() [2/2]
QCString TranslatorPolish::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 449 of file translator_pl.h.
    { return "Dokumentacja definicji typw"; }
trTypedefs() [1/2]
QCString TranslatorPolish::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 413 of file translator_pl.h.
    { return "Definicje typw"; }
trTypedefs() [2/2]
QCString TranslatorPolish::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 413 of file translator_pl.h.
    { return "Definicje typw"; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorPolish::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1539 of file translator_pl.h.
    { return "Dokumentacja typw danych"; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorPolish::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1539 of file translator_pl.h.
    { return "Dokumentacja typw danych"; }
trVariableDocumentation() [1/2]
QCString TranslatorPolish::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 467 of file translator_pl.h.
    { return "Dokumentacja zmiennych"; }
trVariableDocumentation() [2/2]
QCString TranslatorPolish::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 467 of file translator_pl.h.
    { return "Dokumentacja zmiennych"; }
trVariables() [1/2]
QCString TranslatorPolish::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 431 of file translator_pl.h.
    { return "Zmienne"; }
trVariables() [2/2]
QCString TranslatorPolish::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 431 of file translator_pl.h.
    { return "Zmienne"; }
trVersion() [1/2]
QCString TranslatorPolish::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 507 of file translator_pl.h.
    { return "Wersja"; }
trVersion() [2/2]
QCString TranslatorPolish::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 507 of file translator_pl.h.
    { return "Wersja"; }
trWarning() [1/2]
QCString TranslatorPolish::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 503 of file translator_pl.h.
    { return "Ostrzeenie"; }
trWarning() [2/2]
QCString TranslatorPolish::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 503 of file translator_pl.h.
    { return "Ostrzeenie"; }
trWriteList() [1/2]
QCString TranslatorPolish::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 632 of file translator_pl.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" i ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
QCString TranslatorPolish::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 632 of file translator_pl.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" i ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_pl.h
doxygen/src/translator_pl.h