TranslatorLithuanian Class Reference
#include <translator_lt.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
Additional Inherited Members
Detailed Description
Definition at line 33 of file translator_lt.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorLithuanian::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 72 of file translator_lt.h.
    {
      return "0x427 Lithuanian";
    }
getLanguageString() [2/2]
virtual QCString TranslatorLithuanian::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 72 of file translator_lt.h.
    {
      return "0x427 Lithuanian";
    }
idLanguage() [1/2]
virtual QCString TranslatorLithuanian::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 45 of file translator_lt.h.
    { return "lithuanian"; }
idLanguage() [2/2]
virtual QCString TranslatorLithuanian::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 45 of file translator_lt.h.
    { return "lithuanian"; }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorLithuanian::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 62 of file translator_lt.h.
    {
      return "\\usepackage[T2A]{fontenc}\n"
             "\\usepackage[lithuanian]{babel}\n";
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorLithuanian::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 62 of file translator_lt.h.
    {
      return "\\usepackage[T2A]{fontenc}\n"
             "\\usepackage[lithuanian]{babel}\n";
    }
trAll() [1/2]
virtual QCString TranslatorLithuanian::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1397 of file translator_lt.h.
    {
      return "Visi";
    }
trAll() [2/2]
virtual QCString TranslatorLithuanian::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1397 of file translator_lt.h.
    {
      return "Visi";
    }
trAttention() [1/2]
virtual QCString TranslatorLithuanian::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 954 of file translator_lt.h.
    {
      return "Attention";
    }
trAttention() [2/2]
virtual QCString TranslatorLithuanian::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 954 of file translator_lt.h.
    {
      return "Attention";
    }
trAuthor() [1/2]
virtual QCString TranslatorLithuanian::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1267 of file translator_lt.h.
    {
      QCString result((first_capital ? "Autori" : "autori"));
      if (!singular) result+="ai";
      else result+="us";
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorLithuanian::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1267 of file translator_lt.h.
    {
      QCString result((first_capital ? "Autori" : "autori"));
      if (!singular) result+="ai";
      else result+="us";
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorLithuanian::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1120 of file translator_lt.h.
    {
      return "Klaida";
    }
trBug() [2/2]
virtual QCString TranslatorLithuanian::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1120 of file translator_lt.h.
    {
      return "Klaida";
    }
trBugList() [1/2]
virtual QCString TranslatorLithuanian::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1125 of file translator_lt.h.
    {
      return "Klaid Sraas";
    }
trBugList() [2/2]
virtual QCString TranslatorLithuanian::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1125 of file translator_lt.h.
    {
      return "Klaid Sraas";
    }
trCallGraph() [1/2]
virtual QCString TranslatorLithuanian::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1402 of file translator_lt.h.
    {
      return "Funkcijos kvietimo grafas:";
    }
trCallGraph() [2/2]
virtual QCString TranslatorLithuanian::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1402 of file translator_lt.h.
    {
      return "Funkcijos kvietimo grafas:";
    }
trClass() [1/2]
virtual QCString TranslatorLithuanian::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1183 of file translator_lt.h.
    {
      QCString result((first_capital ? "Klas" : "klas"));
      if (!singular) result+="s";
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorLithuanian::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1183 of file translator_lt.h.
    {
      QCString result((first_capital ? "Klas" : "klas"));
      if (!singular) result+="s";
      return result;
    }
trClassDiagram() [1/2]
virtual QCString TranslatorLithuanian::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 508 of file translator_lt.h.
    {
      return "Paveldimumo diagrama "+clName+":"; /*FIXME*/
    }
trClassDiagram() [2/2]
virtual QCString TranslatorLithuanian::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 508 of file translator_lt.h.
    {
      return "Paveldimumo diagrama "+clName+":"; /*FIXME*/
    }
trClassDocumentation() [1/2]
virtual QCString TranslatorLithuanian::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 383 of file translator_lt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Duomen Struktros Dokumentacija";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Klass Dokumentacija";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorLithuanian::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 383 of file translator_lt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Duomen Struktros Dokumentacija";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Klass Dokumentacija";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorLithuanian::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1083 of file translator_lt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Duomen Struktros";
      }
      else
      {
        return "Klass";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorLithuanian::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1083 of file translator_lt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Duomen Struktros";
      }
      else
      {
        return "Klass";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorLithuanian::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 167 of file translator_lt.h.
    { return "Klasi hierarchija"; }
trClassHierarchy() [2/2]
virtual QCString TranslatorLithuanian::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 167 of file translator_lt.h.
    { return "Klasi hierarchija"; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorLithuanian::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 226 of file translator_lt.h.
    { return "is paveldjimo sraas yra beveik surikiuotas "
             "abcls tvarka:";
    }
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorLithuanian::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 226 of file translator_lt.h.
    { return "is paveldjimo sraas yra beveik surikiuotas "
             "abcls tvarka:";
    }
trCode() [1/2]
virtual QCString TranslatorLithuanian::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 854 of file translator_lt.h.
    {
      return "tekstas";/*FIXME*/
    }
trCode() [2/2]
virtual QCString TranslatorLithuanian::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 854 of file translator_lt.h.
    {
      return "tekstas";/*FIXME*/
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorLithuanian::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 809 of file translator_lt.h.
    {
      return "Bendradarbiavimo diagrama "+clName+":";/*FIXME*/
    }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorLithuanian::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 809 of file translator_lt.h.
    {
      return "Bendradarbiavimo diagrama "+clName+":";/*FIXME*/
    }
trCompoundIndex() [1/2]
virtual QCString TranslatorLithuanian::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 356 of file translator_lt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Duomen Struktros Indeksas";
      }
      else
      {
        return "Klass Indeksas";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorLithuanian::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 356 of file translator_lt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Duomen Struktros Indeksas";
      }
      else
      {
        return "Klass Indeksas";
      }
    }
References Config_getBool.
trCompoundList() [1/2]
virtual QCString TranslatorLithuanian::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 171 of file translator_lt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Duomen Struktros";
      }
      else
      {
        return "Klass";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorLithuanian::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 171 of file translator_lt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Duomen Struktros";
      }
      else
      {
        return "Klass";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorLithuanian::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 241 of file translator_lt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Duomen struktros su trumpais apraymais:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Klass su trumpais apraymais:";
      }
      else
      {
        return "Klass, struktros, "
               "sjungos ir ssajos su trumpais apraymais:";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorLithuanian::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 241 of file translator_lt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Duomen struktros su trumpais apraymais:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Klass su trumpais apraymais:";
      }
      else
      {
        return "Klass, struktros, "
               "sjungos ir ssajos su trumpais apraymais:";
      }
    }
References Config_getBool.
trCompoundMembers() [1/2]
virtual QCString TranslatorLithuanian::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 188 of file translator_lt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Duomen Laukai";
      }
      else
      {
        return "Klasi Nariai";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorLithuanian::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 188 of file translator_lt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Duomen Laukai";
      }
      else
      {
        return "Klasi Nariai";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorLithuanian::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 260 of file translator_lt.h.
    {
      QCString result="Vis ";
      if (!extractAll)
      {
        result+="dokumentuot ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="struktr ir sjung lauk sraas";
      }
      else
      {
        result+="klasi nariai";
      }
      result+=" su ryiais ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="struktr/sjung kiekvieno lauko dokumentacij:";
        }
        else
        {
          result+="klass dokumentacija kiekvienam nariui:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="struktros/sjungos, kurios priklauso:";
        }
        else
        {
          result+="klass, kurios priklauso:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorLithuanian::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 260 of file translator_lt.h.
    {
      QCString result="Vis ";
      if (!extractAll)
      {
        result+="dokumentuot ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="struktr ir sjung lauk sraas";
      }
      else
      {
        result+="klasi nariai";
      }
      result+=" su ryiais ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="struktr/sjung kiekvieno lauko dokumentacij:";
        }
        else
        {
          result+="klass dokumentacija kiekvienam nariui:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="struktros/sjungos, kurios priklauso:";
        }
        else
        {
          result+="klass, kurios priklauso:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundReference() [1/2]
virtual QCString TranslatorLithuanian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 583 of file translator_lt.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" Klas"; break;
        case ClassDef::Struct: result+=" Struktra"; break;
        case ClassDef::Union: result+=" Sjunga"; break;
        case ClassDef::Interface: result+=" Ssaja"; break;
        case ClassDef::Protocol: result+=" Protokolas"; break;
        case ClassDef::Category: result+=" Kategorija"; break;
        case ClassDef::Exception: result+=" Iimtis"; break;
        default: break;
      }
      if (isTemplate) result+=" ablonas";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorLithuanian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 583 of file translator_lt.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" Klas"; break;
        case ClassDef::Struct: result+=" Struktra"; break;
        case ClassDef::Union: result+=" Sjunga"; break;
        case ClassDef::Interface: result+=" Ssaja"; break;
        case ClassDef::Protocol: result+=" Protokolas"; break;
        case ClassDef::Category: result+=" Kategorija"; break;
        case ClassDef::Exception: result+=" Iimtis"; break;
        default: break;
      }
      if (isTemplate) result+=" ablonas";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorLithuanian::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 484 of file translator_lt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Duomen struktros";
      }
      else
      {
        return "Klass";
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorLithuanian::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 484 of file translator_lt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Duomen struktros";
      }
      else
      {
        return "Klass";
      }
    }
References Config_getBool.
trConstructorDocumentation() [1/2]
virtual QCString TranslatorLithuanian::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 819 of file translator_lt.h.
    {
      return "Konstruktoriaus ir Destruktoriaus Dokumentacija";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorLithuanian::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 819 of file translator_lt.h.
    {
      return "Konstruktoriaus ir Destruktoriaus Dokumentacija";
    }
trDate() [1/2]
virtual QCString TranslatorLithuanian::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 522 of file translator_lt.h.
    { return "Data"; }
trDate() [2/2]
virtual QCString TranslatorLithuanian::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 522 of file translator_lt.h.
    { return "Data"; }
trDayOfWeek() [1/2]
virtual QCString TranslatorLithuanian::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1512 of file translator_lt.h.
    {
      static const char *days_short[] = { "pr", "an", "tr", "kt", "pn", "t", "sk" };
      static const char *days_full[] = { "pirmadienis", "antradienis", "treiadienis", "ketvirtadienis", "penktadienis", "etadienis", "sekmadienis" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayOfWeek() [2/2]
virtual QCString TranslatorLithuanian::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1512 of file translator_lt.h.
    {
      static const char *days_short[] = { "pr", "an", "tr", "kt", "pn", "t", "sk" };
      static const char *days_full[] = { "pirmadienis", "antradienis", "treiadienis", "ketvirtadienis", "penktadienis", "etadienis", "sekmadienis" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod() [1/2]
virtual QCString TranslatorLithuanian::trDayPeriod (int period) [inline], [virtual]
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1528 of file translator_lt.h.
    {
      static const char *dayPeriod[] = { "priepiet", "popiet" };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorLithuanian::trDayPeriod (int period) [inline], [virtual]
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1528 of file translator_lt.h.
    {
      static const char *dayPeriod[] = { "priepiet", "popiet" };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorLithuanian::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 786 of file translator_lt.h.
    {
      return "Apibrimas failo @1 eilutje @0.";
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorLithuanian::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 786 of file translator_lt.h.
    {
      return "Apibrimas failo @1 eilutje @0.";
    }
trDefinedIn() [1/2]
virtual QCString TranslatorLithuanian::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 155 of file translator_lt.h.
    { return "apibrta"; }
trDefinedIn() [2/2]
virtual QCString TranslatorLithuanian::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 155 of file translator_lt.h.
    { return "apibrta"; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorLithuanian::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 790 of file translator_lt.h.
    {
      return "Apibrimas faile @0.";
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorLithuanian::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 790 of file translator_lt.h.
    {
      return "Apibrimas faile @0.";
    }
trDefineDocumentation() [1/2]
virtual QCString TranslatorLithuanian::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 454 of file translator_lt.h.
    { return "Apibrim Dokumentacija"; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorLithuanian::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 454 of file translator_lt.h.
    { return "Apibrim Dokumentacija"; }
trDefines() [1/2]
virtual QCString TranslatorLithuanian::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 418 of file translator_lt.h.
    { return "Apibrimai"; }
trDefines() [2/2]
virtual QCString TranslatorLithuanian::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 418 of file translator_lt.h.
    { return "Apibrimai"; }
trDefineValue() [1/2]
virtual QCString TranslatorLithuanian::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1110 of file translator_lt.h.
    {
      return "Reikm:";
    }
trDefineValue() [2/2]
virtual QCString TranslatorLithuanian::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1110 of file translator_lt.h.
    {
      return "Reikm:";
    }
trDeprecated() [1/2]
virtual QCString TranslatorLithuanian::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 799 of file translator_lt.h.
    {
      return "Smerktina";
    }
trDeprecated() [2/2]
virtual QCString TranslatorLithuanian::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 799 of file translator_lt.h.
    {
      return "Smerktina";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorLithuanian::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1325 of file translator_lt.h.
    {
      return "Smerktinum Sraas";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorLithuanian::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1325 of file translator_lt.h.
    {
      return "Smerktinum Sraas";
    }
trDetailedDescription() [1/2]
virtual QCString TranslatorLithuanian::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 88 of file translator_lt.h.
    { return "Smulkus apraymas"; }
trDetailedDescription() [2/2]
virtual QCString TranslatorLithuanian::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 88 of file translator_lt.h.
    { return "Smulkus apraymas"; }
trDir() [1/2]
virtual QCString TranslatorLithuanian::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1491 of file translator_lt.h.
    {
      QCString result((first_capital ? "Direktorij" : "direktorij"));
      if (singular) result+="a"; else result+="os";
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorLithuanian::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1491 of file translator_lt.h.
    {
      QCString result((first_capital ? "Direktorij" : "direktorij"));
      if (singular) result+="a"; else result+="os";
      return result;
    }
trDirDocumentation() [1/2]
virtual QCString TranslatorLithuanian::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1473 of file translator_lt.h.
    { return "Direktorij dokumentacija"; }
trDirDocumentation() [2/2]
virtual QCString TranslatorLithuanian::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1473 of file translator_lt.h.
    { return "Direktorij dokumentacija"; }
trDirectories() [1/2]
virtual QCString TranslatorLithuanian::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1479 of file translator_lt.h.
    { return "Direktorijos"; }
trDirectories() [2/2]
virtual QCString TranslatorLithuanian::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1479 of file translator_lt.h.
    { return "Direktorijos"; }
trDirIndex() [1/2]
virtual QCString TranslatorLithuanian::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1467 of file translator_lt.h.
    { return "Direktorij hierarchija"; }
trDirIndex() [2/2]
virtual QCString TranslatorLithuanian::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1467 of file translator_lt.h.
    { return "Direktorij hierarchija"; }
trDirReference() [1/2]
virtual QCString TranslatorLithuanian::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1485 of file translator_lt.h.
    { QCString result=dirName; result+=" Directorijos apraas"; return result; }
trDirReference() [2/2]
virtual QCString TranslatorLithuanian::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1485 of file translator_lt.h.
    { QCString result=dirName; result+=" Directorijos apraas"; return result; }
trDocumentation() [1/2]
virtual QCString TranslatorLithuanian::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 338 of file translator_lt.h.
    { return "Dokumentacija"; }
trDocumentation() [2/2]
virtual QCString TranslatorLithuanian::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 338 of file translator_lt.h.
    { return "Dokumentacija"; }
trEnumerations() [1/2]
virtual QCString TranslatorLithuanian::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 430 of file translator_lt.h.
    { return "Ivardinimai"; }
trEnumerations() [2/2]
virtual QCString TranslatorLithuanian::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 430 of file translator_lt.h.
    { return "Ivardinimai"; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorLithuanian::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 466 of file translator_lt.h.
    { return "Ivardinimo Tipo Dokumentacija"; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorLithuanian::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 466 of file translator_lt.h.
    { return "Ivardinimo Tipo Dokumentacija"; }
trEnumerationValues() [1/2]
virtual QCString TranslatorLithuanian::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 448 of file translator_lt.h.
    { return "Ivardinim reikms"; }
trEnumerationValues() [2/2]
virtual QCString TranslatorLithuanian::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 448 of file translator_lt.h.
    { return "Ivardinim reikms"; }
trEnumName() [1/2]
virtual QCString TranslatorLithuanian::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 147 of file translator_lt.h.
    { return "ivardinimo vardas"; }
trEnumName() [2/2]
virtual QCString TranslatorLithuanian::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 147 of file translator_lt.h.
    { return "ivardinimo vardas"; }
trEnumValue() [1/2]
virtual QCString TranslatorLithuanian::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 151 of file translator_lt.h.
    { return "ivardinimo reikm"; }
trEnumValue() [2/2]
virtual QCString TranslatorLithuanian::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 151 of file translator_lt.h.
    { return "ivardinimo reikm"; }
trEventDocumentation() [1/2]
virtual QCString TranslatorLithuanian::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1342 of file translator_lt.h.
    {
      return "vykio Dokumentacija";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorLithuanian::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1342 of file translator_lt.h.
    {
      return "vykio Dokumentacija";
    }
trEvents() [1/2]
virtual QCString TranslatorLithuanian::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1337 of file translator_lt.h.
    {
      return "vykiai";
    }
trEvents() [2/2]
virtual QCString TranslatorLithuanian::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1337 of file translator_lt.h.
    {
      return "vykiai";
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorLithuanian::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 408 of file translator_lt.h.
    { return "Pavyzdio Dokumentacija"; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorLithuanian::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 408 of file translator_lt.h.
    { return "Pavyzdio Dokumentacija"; }
trExamples() [1/2]
virtual QCString TranslatorLithuanian::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 218 of file translator_lt.h.
    { return "Pavyzdiai"; }
trExamples() [2/2]
virtual QCString TranslatorLithuanian::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 218 of file translator_lt.h.
    { return "Pavyzdiai"; }
trExamplesDescription() [1/2]
virtual QCString TranslatorLithuanian::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 324 of file translator_lt.h.
    { return "Vis pavyzdi sraas:"; }
trExamplesDescription() [2/2]
virtual QCString TranslatorLithuanian::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 324 of file translator_lt.h.
    { return "Vis pavyzdi sraas:"; }
trExceptions() [1/2]
virtual QCString TranslatorLithuanian::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 538 of file translator_lt.h.
    { return "Iimtys"; }
trExceptions() [2/2]
virtual QCString TranslatorLithuanian::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 538 of file translator_lt.h.
    { return "Iimtys"; }
trFile() [1/2]
virtual QCString TranslatorLithuanian::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1194 of file translator_lt.h.
    {
      QCString result((first_capital ? "Faila" : "faila"));
      if (!singular) result+="i";
      else result+="s";
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorLithuanian::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1194 of file translator_lt.h.
    {
      QCString result((first_capital ? "Faila" : "faila"));
      if (!singular) result+="i";
      else result+="s";
      return result;
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorLithuanian::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 402 of file translator_lt.h.
    { return "Failo Dokumentacija"; }
trFileDocumentation() [2/2]
virtual QCString TranslatorLithuanian::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 402 of file translator_lt.h.
    { return "Failo Dokumentacija"; }
trFileIndex() [1/2]
virtual QCString TranslatorLithuanian::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 371 of file translator_lt.h.
    { return "Failo Indeksas"; }
trFileIndex() [2/2]
virtual QCString TranslatorLithuanian::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 371 of file translator_lt.h.
    { return "Failo Indeksas"; }
trFileList() [1/2]
virtual QCString TranslatorLithuanian::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 184 of file translator_lt.h.
    { return "Failai"; }
trFileList() [2/2]
virtual QCString TranslatorLithuanian::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 184 of file translator_lt.h.
    { return "Failai"; }
trFileListDescription() [1/2]
virtual QCString TranslatorLithuanian::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 232 of file translator_lt.h.
    {
      QCString result="Vis ";
      if (!extractAll) result+="dokumentuot ";
      result+="fail sraas su trumpais apraymais:";
      return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorLithuanian::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 232 of file translator_lt.h.
    {
      QCString result="Vis ";
      if (!extractAll) result+="dokumentuot ";
      result+="fail sraas su trumpais apraymais:";
      return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorLithuanian::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 201 of file translator_lt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globals Nariai";
      }
      else
      {
        return "Fail Nariai";
      }
    }
References Config_getBool.
trFileMembers() [2/2]
virtual QCString TranslatorLithuanian::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 201 of file translator_lt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globals Nariai";
      }
      else
      {
        return "Fail Nariai";
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
virtual QCString TranslatorLithuanian::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 302 of file translator_lt.h.
    {
      QCString result="Sraas vis ";
      if (!extractAll) result+="dokumentuot ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funkcij, kintamj, apibrim, ivardinim, ir tip apibrim";
      }
      else
      {
        result+="globali nari";
      }
      result+=" su ryiais ";
      if (extractAll)
        result+="failus, kuriems jie priklauso:";
      else
        result+="dokumentacija:";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorLithuanian::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 302 of file translator_lt.h.
    {
      QCString result="Sraas vis ";
      if (!extractAll) result+="dokumentuot ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funkcij, kintamj, apibrim, ivardinim, ir tip apibrim";
      }
      else
      {
        result+="globali nari";
      }
      result+=" su ryiais ";
      if (extractAll)
        result+="failus, kuriems jie priklauso:";
      else
        result+="dokumentacija:";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorLithuanian::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 604 of file translator_lt.h.
    {
      QCString result=fileName;
      result+=" Failo Nuoroda";
      return result;
    }
trFileReference() [2/2]
virtual QCString TranslatorLithuanian::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 604 of file translator_lt.h.
    {
      QCString result=fileName;
      result+=" Failo Nuoroda";
      return result;
    }
trFriends() [1/2]
virtual QCString TranslatorLithuanian::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 565 of file translator_lt.h.
    { return "Draugai"; }
trFriends() [2/2]
virtual QCString TranslatorLithuanian::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 565 of file translator_lt.h.
    { return "Draugai"; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorLithuanian::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 472 of file translator_lt.h.
    { return "Funkcijos Dokumentacija"; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorLithuanian::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 472 of file translator_lt.h.
    { return "Funkcijos Dokumentacija"; }
trFunctions() [1/2]
virtual QCString TranslatorLithuanian::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 436 of file translator_lt.h.
    { return "Funkcijos"; }
trFunctions() [2/2]
virtual QCString TranslatorLithuanian::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 436 of file translator_lt.h.
    { return "Funkcijos"; }
trGeneratedAt() [1/2]
virtual QCString TranslatorLithuanian::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 499 of file translator_lt.h.
    {
      QCString result="Sugeneruota "+date;/*FIXME*/
      if (!projName.isEmpty()) result+=" "+projName;/*FIXME*/
      result+=" ";/*FIXME*/
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorLithuanian::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 499 of file translator_lt.h.
    {
      QCString result="Sugeneruota "+date;/*FIXME*/
      if (!projName.isEmpty()) result+=" "+projName;/*FIXME*/
      result+=" ";/*FIXME*/
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorLithuanian::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 139 of file translator_lt.h.
    { QCString result="Automatikai sugeneruota Doxygen rankiu";
      if (!s.isEmpty()) result+=" "+s;
      result+=" i programos kodo.";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorLithuanian::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 139 of file translator_lt.h.
    { QCString result="Automatikai sugeneruota Doxygen rankiu";
      if (!s.isEmpty()) result+=" "+s;
      result+=" i programos kodo.";
      return result;
    }
References s.
trGeneratedBy() [1/2]
virtual QCString TranslatorLithuanian::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 542 of file translator_lt.h.
    { return "Sugeneruota"; }
trGeneratedBy() [2/2]
virtual QCString TranslatorLithuanian::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 542 of file translator_lt.h.
    { return "Sugeneruota"; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorLithuanian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 742 of file translator_lt.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentacija ";
      switch(compType)
      {
        case ClassDef::Class: result+="iai klasei"; break;
        case ClassDef::Struct: result+="iai struktrai"; break;
        case ClassDef::Union: result+="iai sjungai"; break;
        case ClassDef::Interface: result+="iai ssajai"; break;
        case ClassDef::Protocol: result+="iam protocolui"; break;
        case ClassDef::Category: result+="iai kategorijai"; break;
        case ClassDef::Exception: result+="iai iimiai"; break;
        default: break;
      }
      result+=" sugeneruota i ";
      if (single) result+="io failo:"; else result+="i fail:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorLithuanian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 742 of file translator_lt.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentacija ";
      switch(compType)
      {
        case ClassDef::Class: result+="iai klasei"; break;
        case ClassDef::Struct: result+="iai struktrai"; break;
        case ClassDef::Union: result+="iai sjungai"; break;
        case ClassDef::Interface: result+="iai ssajai"; break;
        case ClassDef::Protocol: result+="iam protocolui"; break;
        case ClassDef::Category: result+="iai kategorijai"; break;
        case ClassDef::Exception: result+="iai iimiai"; break;
        default: break;
      }
      result+=" sugeneruota i ";
      if (single) result+="io failo:"; else result+="i fail:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorLithuanian::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1253 of file translator_lt.h.
    {
      QCString result((first_capital ? "Global" : "global"));
      if (!singular) result+="s";
      else result+="us";
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorLithuanian::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1253 of file translator_lt.h.
    {
      QCString result((first_capital ? "Global" : "global"));
      if (!singular) result+="s";
      else result+="us";
      return result;
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorLithuanian::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 829 of file translator_lt.h.
    {
      return "Eiti io failo dokumentacij.";
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorLithuanian::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 829 of file translator_lt.h.
    {
      return "Eiti io failo dokumentacij.";
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorLithuanian::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 862 of file translator_lt.h.
    {
      return "Eiti grafin klass hierarchij";
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorLithuanian::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 862 of file translator_lt.h.
    {
      return "Eiti grafin klass hierarchij";
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorLithuanian::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 824 of file translator_lt.h.
    {
      return "Eiti io failo programos kod.";
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorLithuanian::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 824 of file translator_lt.h.
    {
      return "Eiti io failo programos kod.";
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorLithuanian::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 866 of file translator_lt.h.
    {
      return "Eiti tekstin klass hierarchij";
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorLithuanian::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 866 of file translator_lt.h.
    {
      return "Eiti tekstin klass hierarchij";
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorLithuanian::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 858 of file translator_lt.h.
    {
      return "Grafin Klass Hierarchija";
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorLithuanian::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 858 of file translator_lt.h.
    {
      return "Grafin Klass Hierarchija";
    }
trGroup() [1/2]
virtual QCString TranslatorLithuanian::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1218 of file translator_lt.h.
    {
      QCString result((first_capital ? "Grup" : "grup"));
      if (!singular) result+="s";
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorLithuanian::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1218 of file translator_lt.h.
    {
      QCString result((first_capital ? "Grup" : "grup"));
      if (!singular) result+="s";
      return result;
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorLithuanian::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 350 of file translator_lt.h.
    { return "Hierarchijos Indeksas"; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorLithuanian::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 350 of file translator_lt.h.
    { return "Hierarchijos Indeksas"; }
trImplementedFromList() [1/2]
virtual QCString TranslatorLithuanian::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1293 of file translator_lt.h.
    {
      return "Realizuoja "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorLithuanian::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1293 of file translator_lt.h.
    {
      return "Realizuoja "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorLithuanian::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1301 of file translator_lt.h.
    {
      return "Realizuota "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorLithuanian::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1301 of file translator_lt.h.
    {
      return "Realizuota "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorLithuanian::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 958 of file translator_lt.h.
    {
      return "is grafas rodo, kuris failas tiesiogiai ar "
             "netiesiogiai traukia fail:";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorLithuanian::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 958 of file translator_lt.h.
    {
      return "is grafas rodo, kuris failas tiesiogiai ar "
             "netiesiogiai traukia fail:";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorLithuanian::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 814 of file translator_lt.h.
    {
      return "traukimo priklausomybi diagrama "+fName+":";/*FIXME*/
    }
trInclDepGraph() [2/2]
virtual QCString TranslatorLithuanian::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 814 of file translator_lt.h.
    {
      return "traukimo priklausomybi diagrama "+fName+":";/*FIXME*/
    }
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorLithuanian::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 133 of file translator_lt.h.
    { return ", traukiant visus paveldtus narius."; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorLithuanian::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 133 of file translator_lt.h.
    { return ", traukiant visus paveldtus narius."; }
trInheritedByList() [1/2]
virtual QCString TranslatorLithuanian::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 676 of file translator_lt.h.
    {
      return "Paveldta "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorLithuanian::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 676 of file translator_lt.h.
    {
      return "Paveldta "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [1/2]
virtual QCString TranslatorLithuanian::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 668 of file translator_lt.h.
    {
      return "Paveldi "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorLithuanian::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 668 of file translator_lt.h.
    {
      return "Paveldi "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorLithuanian::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 849 of file translator_lt.h.
    {
      return "Pradin reikm:";
    }
trInitialValue() [2/2]
virtual QCString TranslatorLithuanian::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 849 of file translator_lt.h.
    {
      return "Pradin reikm:";
    }
trInvariant() [1/2]
virtual QCString TranslatorLithuanian::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 844 of file translator_lt.h.
    {
      return "Pastovus";
    }
trInvariant() [2/2]
virtual QCString TranslatorLithuanian::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 844 of file translator_lt.h.
    {
      return "Pastovus";
    }
trISOLang() [1/2]
virtual QCString TranslatorLithuanian::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 68 of file translator_lt.h.
    {
      return "lt";
    }
trISOLang() [2/2]
virtual QCString TranslatorLithuanian::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 68 of file translator_lt.h.
    {
      return "lt";
    }
trLegend() [1/2]
virtual QCString TranslatorLithuanian::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1043 of file translator_lt.h.
    {
      return "legenda";
    }
trLegend() [2/2]
virtual QCString TranslatorLithuanian::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1043 of file translator_lt.h.
    {
      return "legenda";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorLithuanian::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 980 of file translator_lt.h.
    {
      return
        "is puslapis paaikina, kaip interpretuoti sugeneruotus grafus "
        "su Doxygen rankiu.<p>\n"
        "Panagrinkite pavyzd:\n"
        "\\kodo pradia\n"
        "/*! Invisible class because of truncation */\n"
        "class Invisible { };\n\n"
        "/*! Truncated class, inheritance relation is hidden */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Class not documented with doxygen comments */\n"
        "class Undocumented { };\n\n"
        "/*! Class that is inherited using public inheritance */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Class that is inherited using protected inheritance */\n"
        "class ProtectedBase { };\n\n"
        "/*! Class that is inherited using private inheritance */\n"
        "class PrivateBase { };\n\n"
        "/*! Class that is used by the Inherited class */\n"
        "class Used { };\n\n"
        "/*! Super class that inherits a number of other classes */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "If the \\c MAX_DOT_GRAPH_HEIGHT tag in the configuration file "
        "is set to 240 this will result in the following graph:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "The boxes in the above graph have the following meaning:\n"
        "<ul>\n"
        "<li>%A filled black box represents the struct or class for which the "
        "graph is generated.\n"
        "<li>%A box with a black border denotes a documented struct or class.\n"
        "<li>%A box with a gray border denotes an undocumented struct or class.\n"
        "<li>%A box with a red border denotes a documented struct or class for"
        "which not all inheritance/containment relations are shown. %A graph is "
        "truncated if it does not fit within the specified boundaries.\n"
        "</ul>\n"
        "The arrows have the following meaning:\n"
        "<ul>\n"
        "<li>%A dark blue arrow is used to visualize a public inheritance "
        "relation between two classes.\n"
        "<li>%A dark green arrow is used for protected inheritance.\n"
        "<li>%A dark red arrow is used for private inheritance.\n"
        "<li>%A purple dashed arrow is used if a class is contained or used "
        "by another class. The arrow is labeled with the variable(s) "
        "through which the pointed class or struct is accessible.\n"
        "<li>%A yellow dashed arrow denotes a relation between a template instance and "
        "the template class it was instantiated from. The arrow is labeled with "
        "the template parameters of the instance.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorLithuanian::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 980 of file translator_lt.h.
    {
      return
        "is puslapis paaikina, kaip interpretuoti sugeneruotus grafus "
        "su Doxygen rankiu.<p>\n"
        "Panagrinkite pavyzd:\n"
        "\\kodo pradia\n"
        "/*! Invisible class because of truncation */\n"
        "class Invisible { };\n\n"
        "/*! Truncated class, inheritance relation is hidden */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Class not documented with doxygen comments */\n"
        "class Undocumented { };\n\n"
        "/*! Class that is inherited using public inheritance */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Class that is inherited using protected inheritance */\n"
        "class ProtectedBase { };\n\n"
        "/*! Class that is inherited using private inheritance */\n"
        "class PrivateBase { };\n\n"
        "/*! Class that is used by the Inherited class */\n"
        "class Used { };\n\n"
        "/*! Super class that inherits a number of other classes */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "If the \\c MAX_DOT_GRAPH_HEIGHT tag in the configuration file "
        "is set to 240 this will result in the following graph:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "The boxes in the above graph have the following meaning:\n"
        "<ul>\n"
        "<li>%A filled black box represents the struct or class for which the "
        "graph is generated.\n"
        "<li>%A box with a black border denotes a documented struct or class.\n"
        "<li>%A box with a gray border denotes an undocumented struct or class.\n"
        "<li>%A box with a red border denotes a documented struct or class for"
        "which not all inheritance/containment relations are shown. %A graph is "
        "truncated if it does not fit within the specified boundaries.\n"
        "</ul>\n"
        "The arrows have the following meaning:\n"
        "<ul>\n"
        "<li>%A dark blue arrow is used to visualize a public inheritance "
        "relation between two classes.\n"
        "<li>%A dark green arrow is used for protected inheritance.\n"
        "<li>%A dark red arrow is used for private inheritance.\n"
        "<li>%A purple dashed arrow is used if a class is contained or used "
        "by another class. The arrow is labeled with the variable(s) "
        "through which the pointed class or struct is accessible.\n"
        "<li>%A yellow dashed arrow denotes a relation between a template instance and "
        "the template class it was instantiated from. The arrow is labeled with "
        "the template parameters of the instance.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorLithuanian::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 973 of file translator_lt.h.
    {
      return "Grafo Legenda";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorLithuanian::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 973 of file translator_lt.h.
    {
      return "Grafo Legenda";
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorLithuanian::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 121 of file translator_lt.h.
    { return "Vis nari sraas"; }
trListOfAllMembers() [2/2]
virtual QCString TranslatorLithuanian::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 121 of file translator_lt.h.
    { return "Vis nari sraas"; }
trMainPage() [1/2]
virtual QCString TranslatorLithuanian::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 773 of file translator_lt.h.
    { return "Pagrindinis Puslapis"; }
trMainPage() [2/2]
virtual QCString TranslatorLithuanian::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 773 of file translator_lt.h.
    { return "Pagrindinis Puslapis"; }
trMember() [1/2]
virtual QCString TranslatorLithuanian::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1241 of file translator_lt.h.
    {
      QCString result((first_capital ? "Nar" : "nar"));
      if (!singular) result+="iai";
      else result+="ys";
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorLithuanian::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1241 of file translator_lt.h.
    {
      QCString result((first_capital ? "Nar" : "nar"));
      if (!singular) result+="iai";
      else result+="ys";
      return result;
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorLithuanian::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 104 of file translator_lt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Lauko apraymas";
      }
      else
      {
        return "Atribut Dokumentacija";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorLithuanian::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 104 of file translator_lt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Lauko apraymas";
      }
      else
      {
        return "Atribut Dokumentacija";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorLithuanian::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 96 of file translator_lt.h.
    { return "Ivardinimo Dokumentacija"; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorLithuanian::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 96 of file translator_lt.h.
    { return "Ivardinimo Dokumentacija"; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorLithuanian::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 100 of file translator_lt.h.
    { return "Metod Dokumentacija"; }
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorLithuanian::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 100 of file translator_lt.h.
    { return "Metod Dokumentacija"; }
trMemberList() [1/2]
virtual QCString TranslatorLithuanian::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 125 of file translator_lt.h.
    { return "Nari sraas"; }
trMemberList() [2/2]
virtual QCString TranslatorLithuanian::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 125 of file translator_lt.h.
    { return "Nari sraas"; }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorLithuanian::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 92 of file translator_lt.h.
    { return "Tipo Apraymo Dokumentacija"; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorLithuanian::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 92 of file translator_lt.h.
    { return "Tipo Apraymo Dokumentacija"; }
trModuleDocumentation() [1/2]
virtual QCString TranslatorLithuanian::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 377 of file translator_lt.h.
    { return "Modulio Dokumentacija"; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorLithuanian::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 377 of file translator_lt.h.
    { return "Modulio Dokumentacija"; }
trModuleIndex() [1/2]
virtual QCString TranslatorLithuanian::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 344 of file translator_lt.h.
    { return "Modulio Indeksas"; }
trModuleIndex() [2/2]
virtual QCString TranslatorLithuanian::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 344 of file translator_lt.h.
    { return "Modulio Indeksas"; }
trModules() [1/2]
virtual QCString TranslatorLithuanian::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 163 of file translator_lt.h.
    { return "Moduliai"; }
trModules() [2/2]
virtual QCString TranslatorLithuanian::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 163 of file translator_lt.h.
    { return "Moduliai"; }
trModulesDescription() [1/2]
virtual QCString TranslatorLithuanian::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 332 of file translator_lt.h.
    { return "Vis moduli sraas:"; }
trModulesDescription() [2/2]
virtual QCString TranslatorLithuanian::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 332 of file translator_lt.h.
    { return "Vis moduli sraas:"; }
trMonth() [1/2]
virtual QCString TranslatorLithuanian::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1520 of file translator_lt.h.
    {
      static const char *months_short[] = { "saus.", "vas.", "kov.", "bal.", "geg.", "bir.", "liep.", "rugp.", "rugs.", "spal.", "lapkr.", "gruod." };
      static const char *months_full[] = { "sausis", "vasaris", "kovas", "balandis", "gegu", "birelis", "liepa", "rugpjtis", "rugsjis", "spalis", "lapkritis", "gruodis" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMonth() [2/2]
virtual QCString TranslatorLithuanian::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1520 of file translator_lt.h.
    {
      static const char *months_short[] = { "saus.", "vas.", "kov.", "bal.", "geg.", "bir.", "liep.", "rugp.", "rugs.", "spal.", "lapkr.", "gruod." };
      static const char *months_full[] = { "sausis", "vasaris", "kovas", "balandis", "gegu", "birelis", "liepa", "rugpjtis", "rugsjis", "spalis", "lapkritis", "gruodis" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore() [1/2]
virtual QCString TranslatorLithuanian::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 117 of file translator_lt.h.
    { return "Daugiau..."; }
trMore() [2/2]
virtual QCString TranslatorLithuanian::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 117 of file translator_lt.h.
    { return "Daugiau..."; }
trNamespace() [1/2]
virtual QCString TranslatorLithuanian::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1206 of file translator_lt.h.
    {
      QCString result((first_capital ? "Vard srit" : "vard srit"));
      if (!singular) result+="ys";
      else result+="is";
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorLithuanian::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1206 of file translator_lt.h.
    {
      QCString result((first_capital ? "Vard srit" : "vard srit"));
      if (!singular) result+="ys";
      else result+="is";
      return result;
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorLithuanian::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 722 of file translator_lt.h.
    { return "Vard Srities Dokumentacija"; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorLithuanian::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 722 of file translator_lt.h.
    { return "Vard Srities Dokumentacija"; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorLithuanian::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 716 of file translator_lt.h.
    { return "Vard Srities Indeksas"; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorLithuanian::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 716 of file translator_lt.h.
    { return "Vard Srities Indeksas"; }
trNamespaceList() [1/2]
virtual QCString TranslatorLithuanian::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 550 of file translator_lt.h.
    { return "Var Srities Sraas"; }
trNamespaceList() [2/2]
virtual QCString TranslatorLithuanian::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 550 of file translator_lt.h.
    { return "Var Srities Sraas"; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorLithuanian::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 554 of file translator_lt.h.
    {
      QCString result="Sraas vis ";
      if (!extractAll) result+="dokumentuot ";
      result+="vard srii su trumpais apraymais:";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorLithuanian::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 554 of file translator_lt.h.
    {
      QCString result="Sraas vis ";
      if (!extractAll) result+="dokumentuot ";
      result+="vard srii su trumpais apraymais:";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorLithuanian::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 702 of file translator_lt.h.
    {
      QCString result="Sraas vis ";
      if (!extractAll) result+="dokumentuot ";
      result+="vard srities nari su nuorodomis ";
      if (extractAll)
        result+="vard srities dokumentacij kiekvienam nariui:";
      else
        result+="vard sritis, kurioms jos priklauso:";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorLithuanian::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 702 of file translator_lt.h.
    {
      QCString result="Sraas vis ";
      if (!extractAll) result+="dokumentuot ";
      result+="vard srities nari su nuorodomis ";
      if (extractAll)
        result+="vard srities dokumentacij kiekvienam nariui:";
      else
        result+="vard sritis, kurioms jos priklauso:";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorLithuanian::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 698 of file translator_lt.h.
    { return "Vard Srities Nariai"; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorLithuanian::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 698 of file translator_lt.h.
    { return "Vard Srities Nariai"; }
trNamespaceReference() [1/2]
virtual QCString TranslatorLithuanian::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 612 of file translator_lt.h.
    {
      QCString result=namespaceName;
      result+=" Vard Srities Nuoroda";
      return result;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorLithuanian::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 612 of file translator_lt.h.
    {
      QCString result=namespaceName;
      result+=" Vard Srities Nuoroda";
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorLithuanian::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 732 of file translator_lt.h.
    { return "Vard Sritys"; }
trNamespaces() [2/2]
virtual QCString TranslatorLithuanian::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 732 of file translator_lt.h.
    { return "Vard Sritys"; }
trNote() [1/2]
virtual QCString TranslatorLithuanian::trNote () [inline], [virtual]
Implements Translator.
Definition at line 879 of file translator_lt.h.
    {
      return "Pastaba";
    }
trNote() [2/2]
virtual QCString TranslatorLithuanian::trNote () [inline], [virtual]
Implements Translator.
Definition at line 879 of file translator_lt.h.
    {
      return "Pastaba";
    }
trOverloadText() [1/2]
virtual QCString TranslatorLithuanian::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1505 of file translator_lt.h.
    {
       return "Perkraunamas metodas sukurtas patogumui. "
              "Jis skiriasi nuo aukiau minto tik argumetais.";
    }
trOverloadText() [2/2]
virtual QCString TranslatorLithuanian::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1505 of file translator_lt.h.
    {
       return "Perkraunamas metodas sukurtas patogumui. "
              "Jis skiriasi nuo aukiau minto tik argumetais.";
    }
trPackage() [1/2]
virtual QCString TranslatorLithuanian::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1095 of file translator_lt.h.
    {
      return "Paketas "+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorLithuanian::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1095 of file translator_lt.h.
    {
      return "Paketas "+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorLithuanian::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1378 of file translator_lt.h.
    {
      return "Paketo Atributai";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorLithuanian::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1378 of file translator_lt.h.
    {
      return "Paketo Atributai";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorLithuanian::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1360 of file translator_lt.h.
    {
      return "Paketo Funkcijos";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorLithuanian::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1360 of file translator_lt.h.
    {
      return "Paketo Funkcijos";
    }
trPackageListDescription() [1/2]
virtual QCString TranslatorLithuanian::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1100 of file translator_lt.h.
    {
      return "Paketai su trumpu apraymu:";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorLithuanian::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1100 of file translator_lt.h.
    {
      return "Paketai su trumpu apraymu:";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorLithuanian::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1364 of file translator_lt.h.
    {
      return "Paketo Nariai";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorLithuanian::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1364 of file translator_lt.h.
    {
      return "Paketo Nariai";
    }
trPackages() [1/2]
virtual QCString TranslatorLithuanian::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1105 of file translator_lt.h.
    {
      return "Paketai";
    }
trPackages() [2/2]
virtual QCString TranslatorLithuanian::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1105 of file translator_lt.h.
    {
      return "Paketai";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorLithuanian::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1353 of file translator_lt.h.
    {
      return "Paketo Tipai";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorLithuanian::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1353 of file translator_lt.h.
    {
      return "Paketo Tipai";
    }
trPage() [1/2]
virtual QCString TranslatorLithuanian::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1229 of file translator_lt.h.
    {
      QCString result((first_capital ? "Puslapi" : "puslapi"));
      if (!singular) result+="ai";
      else result+="s";
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorLithuanian::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1229 of file translator_lt.h.
    {
      QCString result((first_capital ? "Puslapi" : "puslapi"));
      if (!singular) result+="ai";
      else result+="s";
      return result;
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorLithuanian::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 779 of file translator_lt.h.
    { return "psl."; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorLithuanian::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 779 of file translator_lt.h.
    { return "psl."; }
trPageIndex() [1/2]
virtual QCString TranslatorLithuanian::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 870 of file translator_lt.h.
    {
      return "Puslapio Indeksas";
    }
trPageIndex() [2/2]
virtual QCString TranslatorLithuanian::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 870 of file translator_lt.h.
    {
      return "Puslapio Indeksas";
    }
trParameters() [1/2]
virtual QCString TranslatorLithuanian::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 534 of file translator_lt.h.
    { return "Parametrai"; }
trParameters() [2/2]
virtual QCString TranslatorLithuanian::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 534 of file translator_lt.h.
    { return "Parametrai"; }
trPostcondition() [1/2]
virtual QCString TranslatorLithuanian::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 839 of file translator_lt.h.
    {
      return "Postcondition";/*FIXME*/
    }
trPostcondition() [2/2]
virtual QCString TranslatorLithuanian::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 839 of file translator_lt.h.
    {
      return "Postcondition";/*FIXME*/
    }
trPrecondition() [1/2]
virtual QCString TranslatorLithuanian::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 834 of file translator_lt.h.
    {
      return "Iakstin slyga";
    }
trPrecondition() [2/2]
virtual QCString TranslatorLithuanian::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 834 of file translator_lt.h.
    {
      return "Iakstin slyga";
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorLithuanian::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 918 of file translator_lt.h.
    {
      return "Privats Atributai";
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorLithuanian::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 918 of file translator_lt.h.
    {
      return "Privats Atributai";
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorLithuanian::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 633 of file translator_lt.h.
    { return "Privatats Metodai"; }
trPrivateMembers() [2/2]
virtual QCString TranslatorLithuanian::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 633 of file translator_lt.h.
    { return "Privatats Metodai"; }
trPrivateSlots() [1/2]
virtual QCString TranslatorLithuanian::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 635 of file translator_lt.h.
    { return "Privats Slotai"; }/*FIXME*/
trPrivateSlots() [2/2]
virtual QCString TranslatorLithuanian::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 635 of file translator_lt.h.
    { return "Privats Slotai"; }/*FIXME*/
trPrivateTypes() [1/2]
virtual QCString TranslatorLithuanian::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 914 of file translator_lt.h.
    {
      return "Privats Tipai";
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorLithuanian::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 914 of file translator_lt.h.
    {
      return "Privats Tipai";
    }
trProperties() [1/2]
virtual QCString TranslatorLithuanian::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1068 of file translator_lt.h.
    {
      return "Savybs";
    }
trProperties() [2/2]
virtual QCString TranslatorLithuanian::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1068 of file translator_lt.h.
    {
      return "Savybs";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorLithuanian::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1073 of file translator_lt.h.
    {
      return "Savybs Dokumentacija";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorLithuanian::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1073 of file translator_lt.h.
    {
      return "Savybs Dokumentacija";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorLithuanian::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 906 of file translator_lt.h.
    {
      return "Apsaugoti Atributai";
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorLithuanian::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 906 of file translator_lt.h.
    {
      return "Apsaugoti Atributai";
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorLithuanian::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 627 of file translator_lt.h.
    { return "Apsaugoti Metodai"; }
trProtectedMembers() [2/2]
virtual QCString TranslatorLithuanian::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 627 of file translator_lt.h.
    { return "Apsaugoti Metodai"; }
trProtectedSlots() [1/2]
virtual QCString TranslatorLithuanian::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 629 of file translator_lt.h.
    { return "Apsaugoti Slotai"; }/*FIXME*/
trProtectedSlots() [2/2]
virtual QCString TranslatorLithuanian::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 629 of file translator_lt.h.
    { return "Apsaugoti Slotai"; }/*FIXME*/
trProtectedTypes() [1/2]
virtual QCString TranslatorLithuanian::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 902 of file translator_lt.h.
    {
      return "Apsaugoti Tipai";
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorLithuanian::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 902 of file translator_lt.h.
    {
      return "Apsaugoti Tipai";
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorLithuanian::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 887 of file translator_lt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Duomen Laukai";
      }
      else
      {
        return "Viei Atributai";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorLithuanian::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 887 of file translator_lt.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Duomen Laukai";
      }
      else
      {
        return "Viei Atributai";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorLithuanian::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 619 of file translator_lt.h.
    { return "Viei Metodai"; }
trPublicMembers() [2/2]
virtual QCString TranslatorLithuanian::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 619 of file translator_lt.h.
    { return "Viei Metodai"; }
trPublicSlots() [1/2]
virtual QCString TranslatorLithuanian::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 621 of file translator_lt.h.
    { return "Viei Slotai"; } /*FIXME*/
trPublicSlots() [2/2]
virtual QCString TranslatorLithuanian::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 621 of file translator_lt.h.
    { return "Viei Slotai"; } /*FIXME*/
trPublicTypes() [1/2]
virtual QCString TranslatorLithuanian::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 883 of file translator_lt.h.
    {
      return "Viei Tipai";
    }
trPublicTypes() [2/2]
virtual QCString TranslatorLithuanian::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 883 of file translator_lt.h.
    {
      return "Viei Tipai";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorLithuanian::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 946 of file translator_lt.h.
    {
      return "Naudojamas";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorLithuanian::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 946 of file translator_lt.h.
    {
      return "Naudojamas";
    }
trReferenceManual() [1/2]
virtual QCString TranslatorLithuanian::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 412 of file translator_lt.h.
    { return "Informacinis Vadovas"; }
trReferenceManual() [2/2]
virtual QCString TranslatorLithuanian::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 412 of file translator_lt.h.
    { return "Informacinis Vadovas"; }
trReferences() [1/2]
virtual QCString TranslatorLithuanian::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1281 of file translator_lt.h.
    {
      return "Ryiai";
    }
trReferences() [2/2]
virtual QCString TranslatorLithuanian::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1281 of file translator_lt.h.
    {
      return "Ryiai";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorLithuanian::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 684 of file translator_lt.h.
    {
      return "Perkrauna metod i "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorLithuanian::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 684 of file translator_lt.h.
    {
      return "Perkrauna metod i "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorLithuanian::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 692 of file translator_lt.h.
    {
      return "Metodas perkraunamas "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorLithuanian::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 692 of file translator_lt.h.
    {
      return "Metodas perkraunamas "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorLithuanian::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 575 of file translator_lt.h.
    { return "Draugik Ir Susijusi Funkcij Dokumentacija"; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorLithuanian::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 575 of file translator_lt.h.
    { return "Draugik Ir Susijusi Funkcij Dokumentacija"; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorLithuanian::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 80 of file translator_lt.h.
    { return "Susij Funkcijos"; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorLithuanian::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 80 of file translator_lt.h.
    { return "Susij Funkcijos"; }
trRelatedPages() [1/2]
virtual QCString TranslatorLithuanian::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 214 of file translator_lt.h.
    { return "Susij Puslapiai"; }
trRelatedPages() [2/2]
virtual QCString TranslatorLithuanian::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 214 of file translator_lt.h.
    { return "Susij Puslapiai"; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorLithuanian::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 328 of file translator_lt.h.
    { return "Vis susijusi dokumentacijos puslapi sraas:"; }
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorLithuanian::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 328 of file translator_lt.h.
    { return "Vis susijusi dokumentacijos puslapi sraas:"; }
trRelatedSubscript() [1/2]
virtual QCString TranslatorLithuanian::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 84 of file translator_lt.h.
    { return "Atkreipkite dmes, i ne metodai"; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorLithuanian::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 84 of file translator_lt.h.
    { return "Atkreipkite dmes, i ne metodai"; }
trRemarks() [1/2]
virtual QCString TranslatorLithuanian::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 950 of file translator_lt.h.
    {
      return "Pastabos";
    }
trRemarks() [2/2]
virtual QCString TranslatorLithuanian::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 950 of file translator_lt.h.
    {
      return "Pastabos";
    }
trReturns() [1/2]
virtual QCString TranslatorLithuanian::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 526 of file translator_lt.h.
    { return "Graina"; }
trReturns() [2/2]
virtual QCString TranslatorLithuanian::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 526 of file translator_lt.h.
    { return "Graina"; }
trReturnValues() [1/2]
virtual QCString TranslatorLithuanian::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 768 of file translator_lt.h.
    { return "Grainamos reikms"; }
trReturnValues() [2/2]
virtual QCString TranslatorLithuanian::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 768 of file translator_lt.h.
    { return "Grainamos reikms"; }
trRTFansicp() [1/2]
virtual QCString TranslatorLithuanian::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1159 of file translator_lt.h.
    {
      return "1257";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorLithuanian::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1159 of file translator_lt.h.
    {
      return "1257";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorLithuanian::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1168 of file translator_lt.h.
    {
      return "186";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorLithuanian::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1168 of file translator_lt.h.
    {
      return "186";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorLithuanian::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1174 of file translator_lt.h.
    {
      return "Indeksas";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorLithuanian::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1174 of file translator_lt.h.
    {
      return "Indeksas";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorLithuanian::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1313 of file translator_lt.h.
    {
      return "Turinys";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorLithuanian::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1313 of file translator_lt.h.
    {
      return "Turinys";
    }
trSearch() [1/2]
virtual QCString TranslatorLithuanian::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 222 of file translator_lt.h.
    { return "Paieka"; }
trSearch() [2/2]
virtual QCString TranslatorLithuanian::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 222 of file translator_lt.h.
    { return "Paieka"; }
trSearchMatches() [1/2]
virtual QCString TranslatorLithuanian::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1445 of file translator_lt.h.
    {
      return "Atitikmenys:";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorLithuanian::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1445 of file translator_lt.h.
    {
      return "Atitikmenys:";
    }
trSearchResults() [1/2]
virtual QCString TranslatorLithuanian::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1426 of file translator_lt.h.
    {
      if (numDocuments==0)
      {
        return "Atsipraome, joki dokument nerasta pagal Js uklaus.";
      }
      else if (numDocuments==1)
      {
        return "Surasta <b>1</b> dokumentas, atitinkantis Js uklaus.";
      }
      else
      {
        return "Surasta <b>$num</b> dokument, atitinkani Js uklaus. "
               "Pirmiausiai rodomi labiausiai tenkinantys uklaus.";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorLithuanian::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1426 of file translator_lt.h.
    {
      if (numDocuments==0)
      {
        return "Atsipraome, joki dokument nerasta pagal Js uklaus.";
      }
      else if (numDocuments==1)
      {
        return "Surasta <b>1</b> dokumentas, atitinkantis Js uklaus.";
      }
      else
      {
        return "Surasta <b>$num</b> dokument, atitinkani Js uklaus. "
               "Pirmiausiai rodomi labiausiai tenkinantys uklaus.";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorLithuanian::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1414 of file translator_lt.h.
    {
      return "Paiekos Rezultatai";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorLithuanian::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1414 of file translator_lt.h.
    {
      return "Paiekos Rezultatai";
    }
trSeeAlso() [1/2]
virtual QCString TranslatorLithuanian::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 530 of file translator_lt.h.
    { return "Taip pat irti"; }
trSeeAlso() [2/2]
virtual QCString TranslatorLithuanian::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 530 of file translator_lt.h.
    { return "Taip pat irti"; }
trSignals() [1/2]
virtual QCString TranslatorLithuanian::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 623 of file translator_lt.h.
    { return "Signalai"; }
trSignals() [2/2]
virtual QCString TranslatorLithuanian::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 623 of file translator_lt.h.
    { return "Signalai"; }
trSince() [1/2]
virtual QCString TranslatorLithuanian::trSince () [inline], [virtual]
Implements Translator.
Definition at line 963 of file translator_lt.h.
    {
      return "Nuo";
    }
trSince() [2/2]
virtual QCString TranslatorLithuanian::trSince () [inline], [virtual]
Implements Translator.
Definition at line 963 of file translator_lt.h.
    {
      return "Nuo";
    }
trSourceFile() [1/2]
virtual QCString TranslatorLithuanian::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1455 of file translator_lt.h.
    {
      return filename + " ieities tekstas";
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorLithuanian::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1455 of file translator_lt.h.
    {
      return filename + " ieities tekstas";
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorLithuanian::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1385 of file translator_lt.h.
    {
      return "Statiniai Paketo Atributai";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorLithuanian::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1385 of file translator_lt.h.
    {
      return "Statiniai Paketo Atributai";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorLithuanian::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1371 of file translator_lt.h.
    {
      return "Statins Paketo Funkcijos";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorLithuanian::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1371 of file translator_lt.h.
    {
      return "Statins Paketo Funkcijos";
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorLithuanian::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 922 of file translator_lt.h.
    {
      return "Statiniai Privats Atributai";
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorLithuanian::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 922 of file translator_lt.h.
    {
      return "Statiniai Privats Atributai";
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorLithuanian::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 637 of file translator_lt.h.
    { return "Statiniai Privats Metodai"; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorLithuanian::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 637 of file translator_lt.h.
    { return "Statiniai Privats Metodai"; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorLithuanian::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 910 of file translator_lt.h.
    {
      return "Statiniai Apsaugoti Atributai";
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorLithuanian::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 910 of file translator_lt.h.
    {
      return "Statiniai Apsaugoti Atributai";
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorLithuanian::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 631 of file translator_lt.h.
    { return "Statiniai Apsaugoti Metodai"; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorLithuanian::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 631 of file translator_lt.h.
    { return "Statiniai Apsaugoti Metodai"; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorLithuanian::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 898 of file translator_lt.h.
    {
      return "Statiniai Viei Atributai";
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorLithuanian::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 898 of file translator_lt.h.
    {
      return "Statiniai Viei Atributai";
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorLithuanian::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 625 of file translator_lt.h.
    { return "Statiniai Viei Metodai"; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorLithuanian::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 625 of file translator_lt.h.
    { return "Statiniai Viei Metodai"; }
trTest() [1/2]
virtual QCString TranslatorLithuanian::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1053 of file translator_lt.h.
    {
      return "Testas";
    }
trTest() [2/2]
virtual QCString TranslatorLithuanian::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1053 of file translator_lt.h.
    {
      return "Testas";
    }
trTestList() [1/2]
virtual QCString TranslatorLithuanian::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1058 of file translator_lt.h.
    {
      return "Testo Sraas";
    }
trTestList() [2/2]
virtual QCString TranslatorLithuanian::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1058 of file translator_lt.h.
    {
      return "Testo Sraas";
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorLithuanian::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 129 of file translator_lt.h.
    { return "Tai galutinis nari sraas "; }
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorLithuanian::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 129 of file translator_lt.h.
    { return "Tai galutinis nari sraas "; }
trTodo() [1/2]
virtual QCString TranslatorLithuanian::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 932 of file translator_lt.h.
    {
      return "Daryti";
    }
trTodo() [2/2]
virtual QCString TranslatorLithuanian::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 932 of file translator_lt.h.
    {
      return "Daryti";
    }
trTodoList() [1/2]
virtual QCString TranslatorLithuanian::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 937 of file translator_lt.h.
    {
      return "Tolimesni Darbai";
    }
trTodoList() [2/2]
virtual QCString TranslatorLithuanian::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 937 of file translator_lt.h.
    {
      return "Tolimesni Darbai";
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorLithuanian::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 460 of file translator_lt.h.
    { return "Tip apibrim Dokumentacija"; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorLithuanian::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 460 of file translator_lt.h.
    { return "Tip apibrim Dokumentacija"; }
trTypedefs() [1/2]
virtual QCString TranslatorLithuanian::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 424 of file translator_lt.h.
    { return "Tip apibrimai"; }
trTypedefs() [2/2]
virtual QCString TranslatorLithuanian::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 424 of file translator_lt.h.
    { return "Tip apibrimai"; }
trVariableDocumentation() [1/2]
virtual QCString TranslatorLithuanian::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 478 of file translator_lt.h.
    { return "Kintamojo Dokumentacija"; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorLithuanian::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 478 of file translator_lt.h.
    { return "Kintamojo Dokumentacija"; }
trVariables() [1/2]
virtual QCString TranslatorLithuanian::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 442 of file translator_lt.h.
    { return "Kintamieji"; }
trVariables() [2/2]
virtual QCString TranslatorLithuanian::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 442 of file translator_lt.h.
    { return "Kintamieji"; }
trVersion() [1/2]
virtual QCString TranslatorLithuanian::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 518 of file translator_lt.h.
    { return "Versija"; }
trVersion() [2/2]
virtual QCString TranslatorLithuanian::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 518 of file translator_lt.h.
    { return "Versija"; }
trWarning() [1/2]
virtual QCString TranslatorLithuanian::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 514 of file translator_lt.h.
    { return "spjimas"; }
trWarning() [2/2]
virtual QCString TranslatorLithuanian::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 514 of file translator_lt.h.
    { return "spjimas"; }
trWriteList() [1/2]
virtual QCString TranslatorLithuanian::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 643 of file translator_lt.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=", ir ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorLithuanian::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 643 of file translator_lt.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=", ir ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_lt.h
doxygen/src/translator_lt.h