vhdl::parser::VhdlTokenManagerErrorHandler Class Reference
#include <VhdlParserErrorHandler.hpp>
Public Member Functions
VhdlTokenManagerErrorHandler (const char *fileName)
virtual void lexicalError (bool EOFSeen, int lexState, int errorLine, int errorColumn, const JJString &errorAfter, JJChar curChar, VhdlParserTokenManager *token_manager)
virtual void lexicalError (const JJString &errorMessage, VhdlParserTokenManager *token_manager)
VhdlTokenManagerErrorHandler (const char *fileName)
virtual void lexicalError (bool EOFSeen, int lexState, int errorLine, int errorColumn, const JJString &errorAfter, JJChar curChar, VhdlParserTokenManager *token_manager)
virtual void lexicalError (const JJString &errorMessage, VhdlParserTokenManager *token_manager)
Private Attributes
QCString m_fileName
Additional Inherited Members
Detailed Description
Definition at line 46 of file VhdlParserErrorHandler.hpp.
Constructor & Destructor Documentation
VhdlTokenManagerErrorHandler() [1/2]
vhdl::parser::VhdlTokenManagerErrorHandler::VhdlTokenManagerErrorHandler (const char * fileName) [inline]
Definition at line 49 of file VhdlParserErrorHandler.hpp.
: m_fileName(fileName) {}
VhdlTokenManagerErrorHandler() [2/2]
vhdl::parser::VhdlTokenManagerErrorHandler::VhdlTokenManagerErrorHandler (const char * fileName) [inline]
Definition at line 49 of file VhdlParserErrorHandler.hpp.
: m_fileName(fileName) {}
Member Function Documentation
lexicalError() [1/4]
virtual void vhdl::parser::VhdlTokenManagerErrorHandler::lexicalError (bool EOFSeen, int lexState, int errorLine, int errorColumn, const JJString & errorAfter, JJChar curChar, VhdlParserTokenManager * token_manager) [inline], [virtual]
Reimplemented from vhdl::parser::TokenManagerErrorHandler.
Definition at line 51 of file VhdlParserErrorHandler.hpp.
    {
      warn(m_fileName,errorLine,"Lexical error, Encountered: '%c' after: '%s'",curChar, (EOFSeen? "EOF" : (const char*)errorAfter.c_str()));
    }
References m_fileName, and warn().
lexicalError() [2/4]
virtual void vhdl::parser::VhdlTokenManagerErrorHandler::lexicalError (bool EOFSeen, int lexState, int errorLine, int errorColumn, const JJString & errorAfter, JJChar curChar, VhdlParserTokenManager * token_manager) [inline], [virtual]
Reimplemented from vhdl::parser::TokenManagerErrorHandler.
Definition at line 51 of file VhdlParserErrorHandler.hpp.
    {
      warn(m_fileName,errorLine,"Lexical error, Encountered: '%c' after: '%s'",curChar, (EOFSeen? "EOF" : (const char*)errorAfter.c_str()));
    }
References m_fileName, and warn().
lexicalError() [3/4]
virtual void vhdl::parser::VhdlTokenManagerErrorHandler::lexicalError (const JJString & errorMessage, VhdlParserTokenManager * token_manager) [inline], [virtual]
Reimplemented from vhdl::parser::TokenManagerErrorHandler.
Definition at line 56 of file VhdlParserErrorHandler.hpp.
    {
      warn(m_fileName,-1,"Unknown error: '%s'", (char*)errorMessage.c_str());
    }
References m_fileName, and warn().
lexicalError() [4/4]
virtual void vhdl::parser::VhdlTokenManagerErrorHandler::lexicalError (const JJString & errorMessage, VhdlParserTokenManager * token_manager) [inline], [virtual]
Reimplemented from vhdl::parser::TokenManagerErrorHandler.
Definition at line 56 of file VhdlParserErrorHandler.hpp.
    {
      warn(m_fileName,-1,"Unknown error: '%s'", (char*)errorMessage.c_str());
    }
References m_fileName, and warn().
Member Data Documentation
m_fileName
QCString vhdl::parser::VhdlTokenManagerErrorHandler::m_fileName [private]
Definition at line 62 of file VhdlParserErrorHandler.hpp.
Referenced by lexicalError().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/vhdlparser/VhdlParserErrorHandler.hpp
doxygen/vhdlparser/VhdlParserErrorHandler.hpp