ghc::filesystem::directory_iterator::impl Class Reference
#include <filesystem.hpp>
Public Member Functions
impl (const path &path, directory_options options)
impl (const impl &other)=delete
~impl ()
void increment (std::error_code &ec)
void copyToDirEntry ()
impl (const path &path, directory_options options)
impl (const impl &other)=delete
~impl ()
void increment (std::error_code &ec)
void copyToDirEntry ()
Public Attributes
path _base
directory_options _options
DIR * _dir
struct::dirent * _entry
directory_entry _dir_entry
std::error_code _ec
Detailed Description
Definition at line 5545 of file filesystem.hpp.
Constructor & Destructor Documentation
impl() [1/4]
ghc::filesystem::directory_iterator::impl::impl (const path & path, directory_options options) [inline]
Definition at line 5548 of file filesystem.hpp.
        : _base(path)
        , _options(options)
        , _dir(nullptr)
        , _entry(nullptr)
    {
        if (!path.empty()) {
            _dir = ::opendir(path.native().c_str());
            if (!_dir) {
                auto error = errno;
                _base = filesystem::path();
                if ((error != EACCES && error != EPERM) || (options & directory_options::skip_permission_denied) == directory_options::none) {
                    _ec = detail::make_system_error();
                }
            }
            else {
                increment(_ec);
            }
        }
    }
References _base, _dir, _ec, ghc::filesystem::path::empty(), errno, increment(), ghc::filesystem::detail::make_system_error(), ghc::filesystem::path::native(), ghc::filesystem::none, and ghc::filesystem::skip_permission_denied.
impl() [2/4]
ghc::filesystem::directory_iterator::impl::impl (const impl & other) [delete]
 impl() [1/2]
ghc::filesystem::directory_iterator::impl::~impl () [inline]
Definition at line 5569 of file filesystem.hpp.
    {
        if (_dir) {
            ::closedir(_dir);
        }
    }
References _dir.
impl() [3/4]
ghc::filesystem::directory_iterator::impl::impl (const path & path, directory_options options) [inline]
Definition at line 5548 of file filesystem.hpp.
        : _base(path)
        , _options(options)
        , _dir(nullptr)
        , _entry(nullptr)
    {
        if (!path.empty()) {
            _dir = ::opendir(path.native().c_str());
            if (!_dir) {
                auto error = errno;
                _base = filesystem::path();
                if ((error != EACCES && error != EPERM) || (options & directory_options::skip_permission_denied) == directory_options::none) {
                    _ec = detail::make_system_error();
                }
            }
            else {
                increment(_ec);
            }
        }
    }
References _base, _dir, _ec, ghc::filesystem::path::empty(), errno, increment(), ghc::filesystem::detail::make_system_error(), ghc::filesystem::path::native(), ghc::filesystem::none, and ghc::filesystem::skip_permission_denied.
impl() [4/4]
ghc::filesystem::directory_iterator::impl::impl (const impl & other) [delete]
 impl() [2/2]
ghc::filesystem::directory_iterator::impl::~impl () [inline]
Definition at line 5569 of file filesystem.hpp.
    {
        if (_dir) {
            ::closedir(_dir);
        }
    }
References _dir.
Member Function Documentation
copyToDirEntry() [1/2]
void ghc::filesystem::directory_iterator::impl::copyToDirEntry () [inline]
Definition at line 5605 of file filesystem.hpp.
    {
#ifdef GHC_NO_DIRENT_D_TYPE
        _dir_entry._symlink_status = file_status();
        _dir_entry._status = file_status();
#else
        _dir_entry._symlink_status.permissions(perms::unknown);
        switch(_entry->d_type) {
            case DT_BLK: _dir_entry._symlink_status.type(file_type::block); break;
            case DT_CHR: _dir_entry._symlink_status.type(file_type::character); break;
            case DT_DIR: _dir_entry._symlink_status.type(file_type::directory); break;
            case DT_FIFO: _dir_entry._symlink_status.type(file_type::fifo); break;
            case DT_LNK: _dir_entry._symlink_status.type(file_type::symlink); break;
            case DT_REG: _dir_entry._symlink_status.type(file_type::regular); break;
            case DT_SOCK: _dir_entry._symlink_status.type(file_type::socket); break;
            case DT_UNKNOWN: _dir_entry._symlink_status.type(file_type::none); break;
            default: _dir_entry._symlink_status.type(file_type::unknown); break;
        }
        if (_entry->d_type != DT_LNK) {
            _dir_entry._status = _dir_entry._symlink_status;
        }
        else {
            _dir_entry._status.type(file_type::none);
            _dir_entry._status.permissions(perms::unknown);
        }
#endif
        _dir_entry._file_size = static_cast<uintmax_t>(-1);
        _dir_entry._hard_link_count = static_cast<uintmax_t>(-1);
        _dir_entry._last_write_time = 0;
    }
References _dir_entry, _entry, ghc::filesystem::directory_entry::_file_size, ghc::filesystem::directory_entry::_hard_link_count, ghc::filesystem::directory_entry::_last_write_time, ghc::filesystem::directory_entry::_status, ghc::filesystem::directory_entry::_symlink_status, ghc::filesystem::block, ghc::filesystem::character, ghc::filesystem::directory, ghc::filesystem::fifo, ghc::filesystem::none, ghc::filesystem::file_status::permissions(), ghc::filesystem::regular, ghc::filesystem::socket, ghc::filesystem::symlink, ghc::filesystem::file_status::type(), and ghc::filesystem::unknown.
Referenced by increment().
copyToDirEntry() [2/2]
void ghc::filesystem::directory_iterator::impl::copyToDirEntry () [inline]
Definition at line 5605 of file filesystem.hpp.
    {
#ifdef GHC_NO_DIRENT_D_TYPE
        _dir_entry._symlink_status = file_status();
        _dir_entry._status = file_status();
#else
        _dir_entry._symlink_status.permissions(perms::unknown);
        switch(_entry->d_type) {
            case DT_BLK: _dir_entry._symlink_status.type(file_type::block); break;
            case DT_CHR: _dir_entry._symlink_status.type(file_type::character); break;
            case DT_DIR: _dir_entry._symlink_status.type(file_type::directory); break;
            case DT_FIFO: _dir_entry._symlink_status.type(file_type::fifo); break;
            case DT_LNK: _dir_entry._symlink_status.type(file_type::symlink); break;
            case DT_REG: _dir_entry._symlink_status.type(file_type::regular); break;
            case DT_SOCK: _dir_entry._symlink_status.type(file_type::socket); break;
            case DT_UNKNOWN: _dir_entry._symlink_status.type(file_type::none); break;
            default: _dir_entry._symlink_status.type(file_type::unknown); break;
        }
        if (_entry->d_type != DT_LNK) {
            _dir_entry._status = _dir_entry._symlink_status;
        }
        else {
            _dir_entry._status.type(file_type::none);
            _dir_entry._status.permissions(perms::unknown);
        }
#endif
        _dir_entry._file_size = static_cast<uintmax_t>(-1);
        _dir_entry._hard_link_count = static_cast<uintmax_t>(-1);
        _dir_entry._last_write_time = 0;
    }
References _dir_entry, _entry, ghc::filesystem::directory_entry::_file_size, ghc::filesystem::directory_entry::_hard_link_count, ghc::filesystem::directory_entry::_last_write_time, ghc::filesystem::directory_entry::_status, ghc::filesystem::directory_entry::_symlink_status, ghc::filesystem::block, ghc::filesystem::character, ghc::filesystem::directory, ghc::filesystem::fifo, ghc::filesystem::none, ghc::filesystem::file_status::permissions(), ghc::filesystem::regular, ghc::filesystem::socket, ghc::filesystem::symlink, ghc::filesystem::file_status::type(), and ghc::filesystem::unknown.
increment() [1/2]
void ghc::filesystem::directory_iterator::impl::increment (std::error_code & ec) [inline]
Definition at line 5575 of file filesystem.hpp.
    {
        if (_dir) {
            bool skip;
            do {
                skip = false;
                errno = 0;
                _entry = ::readdir(_dir);
                if (_entry) {
                    _dir_entry._path = _base;
                    _dir_entry._path.append_name(_entry->d_name);
                    copyToDirEntry();
                    if (ec && (ec.value() == EACCES || ec.value() == EPERM) && (_options & directory_options::skip_permission_denied) == directory_options::skip_permission_denied) {
                        ec.clear();
                        skip = true;
                    }
                }
                else {
                    ::closedir(_dir);
                    _dir = nullptr;
                    _dir_entry._path.clear();
                    if (errno) {
                        ec = detail::make_system_error();
                    }
                    break;
                }
            } while (skip || std::strcmp(_entry->d_name, ".") == 0 || std::strcmp(_entry->d_name, "..") == 0);
        }
    }
References _base, _dir, _dir_entry, _entry, _options, ghc::filesystem::directory_entry::_path, ghc::filesystem::path::append_name(), ghc::filesystem::path::clear(), copyToDirEntry(), errno, ghc::filesystem::detail::make_system_error(), ghc::filesystem::skip_permission_denied, and strcmp().
Referenced by impl().
increment() [2/2]
void ghc::filesystem::directory_iterator::impl::increment (std::error_code & ec) [inline]
Definition at line 5575 of file filesystem.hpp.
    {
        if (_dir) {
            bool skip;
            do {
                skip = false;
                errno = 0;
                _entry = ::readdir(_dir);
                if (_entry) {
                    _dir_entry._path = _base;
                    _dir_entry._path.append_name(_entry->d_name);
                    copyToDirEntry();
                    if (ec && (ec.value() == EACCES || ec.value() == EPERM) && (_options & directory_options::skip_permission_denied) == directory_options::skip_permission_denied) {
                        ec.clear();
                        skip = true;
                    }
                }
                else {
                    ::closedir(_dir);
                    _dir = nullptr;
                    _dir_entry._path.clear();
                    if (errno) {
                        ec = detail::make_system_error();
                    }
                    break;
                }
            } while (skip || std::strcmp(_entry->d_name, ".") == 0 || std::strcmp(_entry->d_name, "..") == 0);
        }
    }
References _base, _dir, _dir_entry, _entry, _options, ghc::filesystem::directory_entry::_path, ghc::filesystem::path::append_name(), ghc::filesystem::path::clear(), copyToDirEntry(), errno, ghc::filesystem::detail::make_system_error(), ghc::filesystem::skip_permission_denied, and strcmp().
Member Data Documentation
_base
path ghc::filesystem::directory_iterator::impl::_base
Definition at line 5635 of file filesystem.hpp.
Referenced by impl(), and increment().
_dir
DIR * ghc::filesystem::directory_iterator::impl::_dir
Definition at line 5637 of file filesystem.hpp.
Referenced by impl(), increment(), and ~impl().
_dir_entry
directory_entry ghc::filesystem::directory_iterator::impl::_dir_entry
Definition at line 5639 of file filesystem.hpp.
Referenced by copyToDirEntry(), and increment().
_ec
std::error_code ghc::filesystem::directory_iterator::impl::_ec
Definition at line 5640 of file filesystem.hpp.
Referenced by impl().
_entry
struct::dirent * ghc::filesystem::directory_iterator::impl::_entry
Definition at line 5638 of file filesystem.hpp.
Referenced by copyToDirEntry(), and increment().
_options
directory_options ghc::filesystem::directory_iterator::impl::_options
Definition at line 5636 of file filesystem.hpp.
Referenced by increment().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/filesystem/filesystem.hpp
doxygen/filesystem/filesystem.hpp