DocHtmlHeader Class Reference
#include <docnode.h>
Public Member Functions
DocHtmlHeader (DocParser *parser, DocNodeVariant *parent, const HtmlAttribList &attribs, int level)
int level () const
const HtmlAttribList & attribs () const
int parse (DocNodeVariant *)
DocHtmlHeader (DocParser *parser, DocNodeVariant *parent, const HtmlAttribList &attribs, int level)
int level () const
const HtmlAttribList & attribs () const
int parse (DocNodeVariant *)
Private Attributes
int m_level = 0
HtmlAttribList m_attribs
Additional Inherited Members
Detailed Description
Node Html heading
Definition at line 825 of file docnode.h.
Constructor & Destructor Documentation
DocHtmlHeader() [1/2]
DocHtmlHeader::DocHtmlHeader (DocParser * parser, DocNodeVariant * parent, const HtmlAttribList & attribs, int level) [inline]
Definition at line 828 of file docnode.h.
                                                                                                    :
       DocCompoundNode(parser,parent), m_level(level), m_attribs(attribs) {}
DocHtmlHeader() [2/2]
DocHtmlHeader::DocHtmlHeader (DocParser * parser, DocNodeVariant * parent, const HtmlAttribList & attribs, int level) [inline]
Definition at line 828 of file docnode.h.
                                                                                                    :
       DocCompoundNode(parser,parent), m_level(level), m_attribs(attribs) {}
Member Function Documentation
attribs() [1/2]
const HtmlAttribList & DocHtmlHeader::attribs () const [inline]
Definition at line 831 of file docnode.h.
{ return m_attribs; }
References m_attribs.
Referenced by HtmlDocVisitor::operator()().
attribs() [2/2]
const HtmlAttribList & DocHtmlHeader::attribs () const [inline]
Definition at line 831 of file docnode.h.
{ return m_attribs; }
References m_attribs.
level() [1/2]
int DocHtmlHeader::level () const [inline]
Definition at line 830 of file docnode.h.
{ return m_level; }
References m_level.
Referenced by doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docHeadingType::buildAttributes(), doxmlparser.compound.docHeadingType::exportAttributes(), doxmlparser.compound.docHeadingType::get_level(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), PerlModDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), PrintDocVisitor::operator()(), and doxmlparser.compound.docHeadingType::set_level().
level() [2/2]
int DocHtmlHeader::level () const [inline]
Definition at line 830 of file docnode.h.
{ return m_level; }
References m_level.
Referenced by doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docHeadingType::buildAttributes(), doxmlparser.compound.docHeadingType::exportAttributes(), doxmlparser.compound.docHeadingType::get_level(), and doxmlparser.compound.docHeadingType::set_level().
parse() [1/2]
int DocHtmlHeader::parse (DocNodeVariant * thisVariant)
Definition at line 1181 of file docnode.cpp.
{
  int retval=RetVal_OK;
  auto ns = AutoNodeStack(parser(),thisVariant);
  DBG(("DocHtmlHeader::parse() start\n"));
  int tok;
  while ((tok=parser()->tokenizer.lex()))
  {
    if (!parser()->defaultHandleToken(thisVariant,tok,children()))
    {
      switch (tok)
      {
        case TK_HTMLTAG:
          {
            int tagId=Mappers::htmlTagMapper->map(parser()->context.token->name);
            if (tagId==HTML_H1 && parser()->context.token->endTag) // found </h1> tag
            {
              if (m_level!=1)
              {
                warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"<h%d> ended with </h1>",
                    m_level);
              }
              goto endheader;
            }
            else if (tagId==HTML_H2 && parser()->context.token->endTag) // found </h2> tag
            {
              if (m_level!=2)
              {
                warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"<h%d> ended with </h2>",
                    m_level);
              }
              goto endheader;
            }
            else if (tagId==HTML_H3 && parser()->context.token->endTag) // found </h3> tag
            {
              if (m_level!=3)
              {
                warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"<h%d> ended with </h3>",
                    m_level);
              }
              goto endheader;
            }
            else if (tagId==HTML_H4 && parser()->context.token->endTag) // found </h4> tag
            {
              if (m_level!=4)
              {
                warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"<h%d> ended with </h4>",
                    m_level);
              }
              goto endheader;
            }
            else if (tagId==HTML_H5 && parser()->context.token->endTag) // found </h5> tag
            {
              if (m_level!=5)
              {
                warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"<h%d> ended with </h5>",
                    m_level);
              }
              goto endheader;
            }
            else if (tagId==HTML_H6 && parser()->context.token->endTag) // found </h6> tag
            {
              if (m_level!=6)
              {
                warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"<h%d> ended with </h6>",
                    m_level);
              }
              goto endheader;
            }
            else if (tagId==HTML_A)
            {
              if (!parser()->context.token->endTag)
              {
                parser()->handleAHref(thisVariant,children(),parser()->context.token->attribs);
              }
            }
            else if (tagId==HTML_BR)
            {
              children().append<DocLineBreak>(parser(),thisVariant,parser()->context.token->attribs);
            }
            else
            {
              warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"Unexpected html tag <%s%s> found within <h%d> context",
                  parser()->context.token->endTag?"/":"",qPrint(parser()->context.token->name),m_level);
            }
          }
          break;
        default:
      char tmp[20];
      sprintf(tmp,"<h%d>tag",m_level);
          parser()->errorHandleDefaultToken(thisVariant,tok,children(),tmp);
      }
    }
  }
  if (tok==0)
  {
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"Unexpected end of comment while inside"
           " <h%d> tag\n",m_level);
  }
endheader:
  parser()->handlePendingStyleCommands(thisVariant,children());
  DBG(("DocHtmlHeader::parse() end\n"));
  return retval;
}
References DocNodeList::append(), TokenInfo::attribs, DocCompoundNode::children(), DocParser::context, DBG, DocParser::errorHandleDefaultToken(), DocParser::handleAHref(), DocParser::handlePendingStyleCommands(), HTML_A, HTML_BR, HTML_H1, HTML_H2, HTML_H3, HTML_H4, HTML_H5, HTML_H6, Mappers::htmlTagMapper, m_level, Mapper::map(), DocNode::parser(), qPrint(), RetVal_OK, TK_HTMLTAG, DocParserContext::token, and warn_doc_error().
parse() [2/2]
int DocHtmlHeader::parse (DocNodeVariant *)
Member Data Documentation
m_attribs
HtmlAttribList DocHtmlHeader::m_attribs [private]
Definition at line 836 of file docnode.h.
Referenced by attribs().
m_level
int DocHtmlHeader::m_level = 0 [private]
Definition at line 835 of file docnode.h.
Referenced by level(), and parse().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docnode.h
doxygen/src/docnode.h
doxygen/build/doxygen/src/docnode.cpp
doxygen/src/docnode.cpp