InheritedMemberInfoListContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
void addMemberList (const ClassDef *cd, MemberListType lt, const QCString &title, bool additionalList=TRUE)
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
InheritedMemberInfoListContext ()
virtual ~InheritedMemberInfoListContext ()
void addMemberList (const ClassDef *cd, MemberListType lt, const QCString &title, bool additionalList=TRUE)
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
InheritedMemberInfoListContext ()
virtual ~InheritedMemberInfoListContext ()
Static Public Member Functions
static TemplateListIntfPtr alloc ()
static TemplateListIntfPtr alloc ()
Private Attributes
std::unique_ptr< Private > p
Additional Inherited Members
Detailed Description
Definition at line 1140 of file context.h.
Constructor & Destructor Documentation
InheritedMemberInfoListContext() [1/2]
InheritedMemberInfoListContext::InheritedMemberInfoListContext ()
Definition at line 8167 of file context.cpp.
                                                               : p(std::make_unique<Private>())
{
}
 InheritedMemberInfoListContext() [1/2]
InheritedMemberInfoListContext::~InheritedMemberInfoListContext () [virtual]
Definition at line 8185 of file context.cpp.
{
}
InheritedMemberInfoListContext() [2/2]
InheritedMemberInfoListContext::InheritedMemberInfoListContext ()
 InheritedMemberInfoListContext() [2/2]
virtual InheritedMemberInfoListContext::~InheritedMemberInfoListContext () [virtual]
Member Function Documentation
addMemberList() [1/2]
void InheritedMemberInfoListContext::addMemberList (const ClassDef * cd, MemberListType lt, const QCString & title, bool additionalList = TRUE)
Definition at line 8171 of file context.cpp.
{
  ClassDefSet visited;
  bool memberInSection = cd->countMembersIncludingGrouped(lt,cd,FALSE)>0;
  bool show = (additionalList && !memberInSection) || // inherited member to show in the additional inherited members list
              (!additionalList && memberInSection); // inherited member to show in a member list of the class
  //printf("%s:%s show=%d\n",qPrint(cd->name()),qPrint(MemberList::listTypeAsString(lt)),show);
  if (show)
  {
    p->findInheritedMembers(cd,cd,lt,-1,title,additionalList,visited);
  }
}
References ClassDef::countMembersIncludingGrouped(), FALSE, and p.
addMemberList() [2/2]
void InheritedMemberInfoListContext::addMemberList (const ClassDef * cd, MemberListType lt, const QCString & title, bool additionalList = TRUE)
alloc() [1/2]
static TemplateListIntfPtr InheritedMemberInfoListContext::alloc () [inline], [static]
Definition at line 1143 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<InheritedMemberInfoListContext>()); }
Referenced by ClassContext::Private::createAdditionalInheritedMembers(), and MemberListInfoContext::Private::createInherited().
alloc() [2/2]
static TemplateListIntfPtr InheritedMemberInfoListContext::alloc () [inline], [static]
Definition at line 1143 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<InheritedMemberInfoListContext>()); }
at() [1/2]
TemplateVariant InheritedMemberInfoListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 8195 of file context.cpp.
{
  return p->at(index);
}
References p.
at() [2/2]
virtual TemplateVariant InheritedMemberInfoListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
count() [1/2]
size_t InheritedMemberInfoListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Definition at line 8190 of file context.cpp.
{
  return p->count();
}
References p.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
count() [2/2]
virtual size_t InheritedMemberInfoListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
createIterator() [1/2]
TemplateListIntf::ConstIteratorPtr InheritedMemberInfoListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 8200 of file context.cpp.
{
  return p->createIterator();
}
References p.
createIterator() [2/2]
virtual TemplateListIntf::ConstIteratorPtr InheritedMemberInfoListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Member Data Documentation
p
std::unique_ptr< Private > InheritedMemberInfoListContext::p [private]
Definition at line 1157 of file context.h.
Referenced by addMemberList(), at(), count(), and createIterator().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.h
doxygen/src/context.h
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp