TranslatorSwedish Class Reference
#include <translator_sv.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
virtual QCString trDesignUnitHierarchy ()
virtual QCString trDesignUnitList ()
virtual QCString trDesignUnitMembers ()
virtual QCString trDesignUnitListDescription ()
virtual QCString trDesignUnitIndex ()
virtual QCString trDesignUnits ()
virtual QCString trFunctionAndProc ()
virtual QCString trVhdlType (uint64 type, bool single)
virtual QCString trCustomReference (const QCString &name)
virtual QCString trConstants ()
virtual QCString trConstantDocumentation ()
virtual QCString trSequences ()
virtual QCString trSequenceDocumentation ()
virtual QCString trDictionaries ()
virtual QCString trDictionaryDocumentation ()
virtual QCString trSliceInterfaces ()
virtual QCString trInterfaceIndex ()
virtual QCString trInterfaceList ()
virtual QCString trInterfaceListDescription ()
virtual QCString trInterfaceHierarchy ()
virtual QCString trInterfaceHierarchyDescription ()
virtual QCString trInterfaceDocumentation ()
virtual QCString trStructs ()
virtual QCString trStructIndex ()
virtual QCString trStructList ()
virtual QCString trStructListDescription ()
virtual QCString trStructDocumentation ()
virtual QCString trExceptionIndex ()
virtual QCString trExceptionList ()
virtual QCString trExceptionListDescription ()
virtual QCString trExceptionHierarchy ()
virtual QCString trExceptionHierarchyDescription ()
virtual QCString trExceptionDocumentation ()
virtual QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal)
virtual QCString trOperations ()
virtual QCString trOperationDocumentation ()
virtual QCString trDataMembers ()
virtual QCString trDataMemberDocumentation ()
virtual QCString trDesignUnitDocumentation ()
virtual QCString trConcept (bool first_capital, bool singular)
virtual QCString trConceptReference (const QCString &conceptName)
virtual QCString trConceptList ()
virtual QCString trConceptIndex ()
virtual QCString trConceptDocumentation ()
virtual QCString trConceptListDescription (bool extractAll)
virtual QCString trConceptDefinition ()
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
virtual QCString trDesignUnitHierarchy ()
virtual QCString trDesignUnitList ()
virtual QCString trDesignUnitMembers ()
virtual QCString trDesignUnitListDescription ()
virtual QCString trDesignUnitIndex ()
virtual QCString trDesignUnits ()
virtual QCString trFunctionAndProc ()
virtual QCString trVhdlType (uint64 type, bool single)
virtual QCString trCustomReference (const QCString &name)
virtual QCString trConstants ()
virtual QCString trConstantDocumentation ()
virtual QCString trSequences ()
virtual QCString trSequenceDocumentation ()
virtual QCString trDictionaries ()
virtual QCString trDictionaryDocumentation ()
virtual QCString trSliceInterfaces ()
virtual QCString trInterfaceIndex ()
virtual QCString trInterfaceList ()
virtual QCString trInterfaceListDescription ()
virtual QCString trInterfaceHierarchy ()
virtual QCString trInterfaceHierarchyDescription ()
virtual QCString trInterfaceDocumentation ()
virtual QCString trStructs ()
virtual QCString trStructIndex ()
virtual QCString trStructList ()
virtual QCString trStructListDescription ()
virtual QCString trStructDocumentation ()
virtual QCString trExceptionIndex ()
virtual QCString trExceptionList ()
virtual QCString trExceptionListDescription ()
virtual QCString trExceptionHierarchy ()
virtual QCString trExceptionHierarchyDescription ()
virtual QCString trExceptionDocumentation ()
virtual QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal)
virtual QCString trOperations ()
virtual QCString trOperationDocumentation ()
virtual QCString trDataMembers ()
virtual QCString trDataMemberDocumentation ()
virtual QCString trDesignUnitDocumentation ()
virtual QCString trConcept (bool first_capital, bool singular)
virtual QCString trConceptReference (const QCString &conceptName)
virtual QCString trConceptList ()
virtual QCString trConceptIndex ()
virtual QCString trConceptDocumentation ()
virtual QCString trConceptListDescription (bool extractAll)
virtual QCString trConceptDefinition ()
Additional Inherited Members
Detailed Description
Definition at line 159 of file translator_sv.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorSwedish::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 189 of file translator_sv.h.
    {
      return "0x41D Swedish";
    }
getLanguageString() [2/2]
virtual QCString TranslatorSwedish::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 189 of file translator_sv.h.
    {
      return "0x41D Swedish";
    }
idLanguage() [1/2]
virtual QCString TranslatorSwedish::idLanguage () [inline], [virtual]
Implements Translator.
Definition at line 163 of file translator_sv.h.
    { return "swedish"; }
idLanguage() [2/2]
virtual QCString TranslatorSwedish::idLanguage () [inline], [virtual]
Implements Translator.
Definition at line 163 of file translator_sv.h.
    { return "swedish"; }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorSwedish::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 180 of file translator_sv.h.
    {
      return "\\usepackage[swedish]{babel}\n";
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorSwedish::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 180 of file translator_sv.h.
    {
      return "\\usepackage[swedish]{babel}\n";
    }
trAdditionalInheritedMembers() [1/2]
virtual QCString TranslatorSwedish::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1998 of file translator_sv.h.
    { return "Ytterliga rvda medlemmar"; }
trAdditionalInheritedMembers() [2/2]
virtual QCString TranslatorSwedish::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1998 of file translator_sv.h.
    { return "Ytterliga rvda medlemmar"; }
trAll() [1/2]
virtual QCString TranslatorSwedish::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1508 of file translator_sv.h.
    {
      return "Alla";
    }
trAll() [2/2]
virtual QCString TranslatorSwedish::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1508 of file translator_sv.h.
    {
      return "Alla";
    }
trAndMore() [1/2]
virtual QCString TranslatorSwedish::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1976 of file translator_sv.h.
    { return "och "+number+" flera..."; }
trAndMore() [2/2]
virtual QCString TranslatorSwedish::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1976 of file translator_sv.h.
    { return "och "+number+" flera..."; }
trAttention() [1/2]
virtual QCString TranslatorSwedish::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 1081 of file translator_sv.h.
    {
      return "Observera";
    }
trAttention() [2/2]
virtual QCString TranslatorSwedish::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 1081 of file translator_sv.h.
    {
      return "Observera";
    }
trAuthor() [1/2]
virtual QCString TranslatorSwedish::trAuthor (bool first_capital, bool) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1380 of file translator_sv.h.
    {
      QCString result((first_capital ? "Frfattare" : "frfattare"));
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorSwedish::trAuthor (bool first_capital, bool) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1380 of file translator_sv.h.
    {
      QCString result((first_capital ? "Frfattare" : "frfattare"));
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorSwedish::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1250 of file translator_sv.h.
    {
      return "Bugg";
    }
trBug() [2/2]
virtual QCString TranslatorSwedish::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1250 of file translator_sv.h.
    {
      return "Bugg";
    }
trBugList() [1/2]
virtual QCString TranslatorSwedish::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1255 of file translator_sv.h.
    {
      return "Bugglista";
    }
trBugList() [2/2]
virtual QCString TranslatorSwedish::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1255 of file translator_sv.h.
    {
      return "Bugglista";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorSwedish::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1630 of file translator_sv.h.
    {
      return "Hr r anropsgrafen fr denna funktion:";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorSwedish::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1630 of file translator_sv.h.
    {
      return "Hr r anropsgrafen fr denna funktion:";
    }
trCallGraph() [1/2]
virtual QCString TranslatorSwedish::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1513 of file translator_sv.h.
    {
      return "Hr r anropsdiagrammet fr den hr funktionen:";
    }
trCallGraph() [2/2]
virtual QCString TranslatorSwedish::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1513 of file translator_sv.h.
    {
      return "Hr r anropsdiagrammet fr den hr funktionen:";
    }
trCiteReferences() [1/2]
virtual QCString TranslatorSwedish::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1952 of file translator_sv.h.
    { return "Bibliografiska Referenser"; }
trCiteReferences() [2/2]
virtual QCString TranslatorSwedish::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1952 of file translator_sv.h.
    { return "Bibliografiska Referenser"; }
trClass() [1/2]
virtual QCString TranslatorSwedish::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1298 of file translator_sv.h.
    {
      QCString result((first_capital ? "Klass" : "klass"));
      if (!singular) result+="er";
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorSwedish::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1298 of file translator_sv.h.
    {
      QCString result((first_capital ? "Klass" : "klass"));
      if (!singular) result+="er";
      return result;
    }
trClassDiagram() [1/2]
virtual QCString TranslatorSwedish::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 626 of file translator_sv.h.
    {
      return "Klassdiagram fr "+clName;
    }
trClassDiagram() [2/2]
virtual QCString TranslatorSwedish::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 626 of file translator_sv.h.
    {
      return "Klassdiagram fr "+clName;
    }
trClassDocumentation() [1/2]
virtual QCString TranslatorSwedish::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 501 of file translator_sv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentation ver datastrukturer";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Klassdokumentation";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorSwedish::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 501 of file translator_sv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentation ver datastrukturer";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Klassdokumentation";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorSwedish::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1212 of file translator_sv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datastrukturer";
      }
      else
      {
        return "Klasser";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorSwedish::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1212 of file translator_sv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datastrukturer";
      }
      else
      {
        return "Klasser";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorSwedish::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 284 of file translator_sv.h.
    { return "Klasshierarki"; }
trClassHierarchy() [2/2]
virtual QCString TranslatorSwedish::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 284 of file translator_sv.h.
    { return "Klasshierarki"; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorSwedish::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 343 of file translator_sv.h.
    { return "Denna lista ver arv r grovt, men inte helt, "
             "sorterad i alfabetisk ordning:";
    }
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorSwedish::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 343 of file translator_sv.h.
    { return "Denna lista ver arv r grovt, men inte helt, "
             "sorterad i alfabetisk ordning:";
    }
trClassMethods() [1/2]
virtual QCString TranslatorSwedish::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 2036 of file translator_sv.h.
    {
      return "Klassmetoder";
    }
trClassMethods() [2/2]
virtual QCString TranslatorSwedish::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 2036 of file translator_sv.h.
    {
      return "Klassmetoder";
    }
trCode() [1/2]
virtual QCString TranslatorSwedish::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 981 of file translator_sv.h.
    {
      return "kllkod";
    }
trCode() [2/2]
virtual QCString TranslatorSwedish::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 981 of file translator_sv.h.
    {
      return "kllkod";
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorSwedish::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 936 of file translator_sv.h.
    {
      return "Samarbetsdiagram fr "+clName+":";
    }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorSwedish::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 936 of file translator_sv.h.
    {
      return "Samarbetsdiagram fr "+clName+":";
    }
trCompoundIndex() [1/2]
virtual QCString TranslatorSwedish::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 474 of file translator_sv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Index ver datastrukturer";
      }
      else
      {
        return "Klassindex";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorSwedish::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 474 of file translator_sv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Index ver datastrukturer";
      }
      else
      {
        return "Klassindex";
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorSwedish::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1685 of file translator_sv.h.
    { return "Datatypsindex"; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorSwedish::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1685 of file translator_sv.h.
    { return "Datatypsindex"; }
trCompoundList() [1/2]
virtual QCString TranslatorSwedish::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 288 of file translator_sv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datastrukturer";
      }
      else
      {
        return "Klasslista";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorSwedish::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 288 of file translator_sv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datastrukturer";
      }
      else
      {
        return "Klasslista";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorSwedish::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 358 of file translator_sv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Hr fljer datastrukturerna med korta beskrivningar:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Hr fljer klasserna med korta beskrivningar:";
      }
      else
      {
        return "Hr fljer klasserna, strukterna, unionerna och "
               "grnssnitten med korta beskrivningar:";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorSwedish::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 358 of file translator_sv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Hr fljer datastrukturerna med korta beskrivningar:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Hr fljer klasserna med korta beskrivningar:";
      }
      else
      {
        return "Hr fljer klasserna, strukterna, unionerna och "
               "grnssnitten med korta beskrivningar:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorSwedish::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1658 of file translator_sv.h.
    { return "Hr r datatyperna med en kort beskrivning:"; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorSwedish::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1658 of file translator_sv.h.
    { return "Hr r datatyperna med en kort beskrivning:"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorSwedish::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1650 of file translator_sv.h.
    { return "Datatyplista"; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorSwedish::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1650 of file translator_sv.h.
    { return "Datatyplista"; }
trCompoundMembers() [1/2]
virtual QCString TranslatorSwedish::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 305 of file translator_sv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dataflt";
      }
      else
      {
        return "Klassmedlemmar";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorSwedish::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 305 of file translator_sv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dataflt";
      }
      else
      {
        return "Klassmedlemmar";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorSwedish::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 377 of file translator_sv.h.
    {
      QCString result="Hr r en lista ver alla ";
      if (!extractAll)
      {
        result+="dokumenterade ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="struktur- och unions-flt";
      }
      else
      {
        result+="klassmedlemmar";
      }
      result+=" med lnkar till ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="struktur/union-dokumentationen fr varje flt:";
        }
        else
        {
          result+="klassdokumentationen fr varje medlem:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+=" strukturerna/unionerna de tillhr:";
        }
        else
        {
          result+="klasserna de tillhr:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorSwedish::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 377 of file translator_sv.h.
    {
      QCString result="Hr r en lista ver alla ";
      if (!extractAll)
      {
        result+="dokumenterade ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="struktur- och unions-flt";
      }
      else
      {
        result+="klassmedlemmar";
      }
      result+=" med lnkar till ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="struktur/union-dokumentationen fr varje flt:";
        }
        else
        {
          result+="klassdokumentationen fr varje medlem:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+=" strukturerna/unionerna de tillhr:";
        }
        else
        {
          result+="klasserna de tillhr:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorSwedish::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1662 of file translator_sv.h.
    {
      QCString result="Hr r en lista ver alla ";
      if (!extractAll)
      {
        result+="dokumenterade ";
      }
      result+="datatypsmedlemmar";
      result+=" med lnkar till ";
      if (!extractAll)
      {
         result+="dokumentation fr varje medlem";
      }
      else
      {
         result+="klasserna de hr till:";
      }
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorSwedish::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1662 of file translator_sv.h.
    {
      QCString result="Hr r en lista ver alla ";
      if (!extractAll)
      {
        result+="dokumenterade ";
      }
      result+="datatypsmedlemmar";
      result+=" med lnkar till ";
      if (!extractAll)
      {
         result+="dokumentation fr varje medlem";
      }
      else
      {
         result+="klasserna de hr till:";
      }
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorSwedish::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1654 of file translator_sv.h.
    { return "Dataflt"; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorSwedish::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1654 of file translator_sv.h.
    { return "Dataflt"; }
trCompoundReference() [1/2]
virtual QCString TranslatorSwedish::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 698 of file translator_sv.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" klass"; break;
        case ClassDef::Struct: result+=" strukt"; break;
        case ClassDef::Union: result+=" union"; break;
        case ClassDef::Interface: result+=" grnssnitt"; break;
        case ClassDef::Protocol: result+=" protokoll"; break;
        case ClassDef::Category: result+=" kategori"; break;
        case ClassDef::Exception: result+=" undantag"; break;
        default: break;
      }
      if (isTemplate) result+="-mall";
      result+=" referens";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorSwedish::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 698 of file translator_sv.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" klass"; break;
        case ClassDef::Struct: result+=" strukt"; break;
        case ClassDef::Union: result+=" union"; break;
        case ClassDef::Interface: result+=" grnssnitt"; break;
        case ClassDef::Protocol: result+=" protokoll"; break;
        case ClassDef::Category: result+=" kategori"; break;
        case ClassDef::Exception: result+=" undantag"; break;
        default: break;
      }
      if (isTemplate) result+="-mall";
      result+=" referens";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorSwedish::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1726 of file translator_sv.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" Modul"; break;
        case ClassDef::Struct: result+=" Typ"; break;
        case ClassDef::Union: result+=" Union"; break;
        case ClassDef::Interface: result+=" Grnssnitt"; break;
        case ClassDef::Protocol: result+=" Protokoll"; break;
        case ClassDef::Category: result+=" Kategori"; break;
        case ClassDef::Exception: result+=" Undantag"; break;
        default: break;
      }
      if (isTemplate) result+="-mall";
      result+=" referens";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorSwedish::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1726 of file translator_sv.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" Modul"; break;
        case ClassDef::Struct: result+=" Typ"; break;
        case ClassDef::Union: result+=" Union"; break;
        case ClassDef::Interface: result+=" Grnssnitt"; break;
        case ClassDef::Protocol: result+=" Protokoll"; break;
        case ClassDef::Category: result+=" Kategori"; break;
        case ClassDef::Exception: result+=" Undantag"; break;
        default: break;
      }
      if (isTemplate) result+="-mall";
      result+=" referens";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice() [1/2]
virtual QCString TranslatorSwedish::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) [inline], [virtual]
Implements Translator.
Definition at line 2330 of file translator_sv.h.
    {
      QCString result=clName;
      if (isLocal) result+=" Lokal";
      switch(compType)
      {
        case ClassDef::Class: result+=" Klass"; break;
        case ClassDef::Struct: result+=" Struktur"; break;
        case ClassDef::Union: result+=" Unions"; break;
        case ClassDef::Interface: result+=" Grnssnitts"; break;
        case ClassDef::Protocol: result+=" Protokoll"; break;
        case ClassDef::Category: result+=" Kategori"; break;
        case ClassDef::Exception: result+=" Undantags"; break;
        default: break;
      }
      result+="referens";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice() [2/2]
virtual QCString TranslatorSwedish::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) [inline], [virtual]
Implements Translator.
Definition at line 2330 of file translator_sv.h.
    {
      QCString result=clName;
      if (isLocal) result+=" Lokal";
      switch(compType)
      {
        case ClassDef::Class: result+=" Klass"; break;
        case ClassDef::Struct: result+=" Struktur"; break;
        case ClassDef::Union: result+=" Unions"; break;
        case ClassDef::Interface: result+=" Grnssnitts"; break;
        case ClassDef::Protocol: result+=" Protokoll"; break;
        case ClassDef::Category: result+=" Kategori"; break;
        case ClassDef::Exception: result+=" Undantags"; break;
        default: break;
      }
      result+="referens";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorSwedish::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 602 of file translator_sv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datastrukturer";
      }
      else
      {
        return "Klasser";
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorSwedish::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 602 of file translator_sv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datastrukturer";
      }
      else
      {
        return "Klasser";
      }
    }
References Config_getBool.
trConcept() [1/2]
virtual QCString TranslatorSwedish::trConcept (bool first_capital, bool singular) [inline], [virtual]
C++20 concept
Implements Translator.
Definition at line 2378 of file translator_sv.h.
    {
      QCString result((first_capital ? "Koncept" : "koncept"));
      return result;
    }
trConcept() [2/2]
virtual QCString TranslatorSwedish::trConcept (bool first_capital, bool singular) [inline], [virtual]
C++20 concept
Implements Translator.
Definition at line 2378 of file translator_sv.h.
    {
      QCString result((first_capital ? "Koncept" : "koncept"));
      return result;
    }
trConceptDefinition() [1/2]
virtual QCString TranslatorSwedish::trConceptDefinition () [inline], [virtual]
used to introduce the definition of the C++20 concept
Implements Translator.
Definition at line 2413 of file translator_sv.h.
    {
      return "Konceptdefinition";
    }
trConceptDefinition() [2/2]
virtual QCString TranslatorSwedish::trConceptDefinition () [inline], [virtual]
used to introduce the definition of the C++20 concept
Implements Translator.
Definition at line 2413 of file translator_sv.h.
    {
      return "Konceptdefinition";
    }
trConceptDocumentation() [1/2]
virtual QCString TranslatorSwedish::trConceptDocumentation () [inline], [virtual]
used as the title of chapter containing all information about concepts.
Implements Translator.
Definition at line 2400 of file translator_sv.h.
    { return "Konceptdokumentation"; }
trConceptDocumentation() [2/2]
virtual QCString TranslatorSwedish::trConceptDocumentation () [inline], [virtual]
used as the title of chapter containing all information about concepts.
Implements Translator.
Definition at line 2400 of file translator_sv.h.
    { return "Konceptdokumentation"; }
trConceptIndex() [1/2]
virtual QCString TranslatorSwedish::trConceptIndex () [inline], [virtual]
used as the title of chapter containing the index listing all concepts.
Implements Translator.
Definition at line 2396 of file translator_sv.h.
    { return "Konceptindex"; }
trConceptIndex() [2/2]
virtual QCString TranslatorSwedish::trConceptIndex () [inline], [virtual]
used as the title of chapter containing the index listing all concepts.
Implements Translator.
Definition at line 2396 of file translator_sv.h.
    { return "Konceptindex"; }
trConceptList() [1/2]
virtual QCString TranslatorSwedish::trConceptList () [inline], [virtual]
used as the title of page containing all the index of all concepts.
Implements Translator.
Definition at line 2392 of file translator_sv.h.
    { return "Konceptlista"; }
trConceptList() [2/2]
virtual QCString TranslatorSwedish::trConceptList () [inline], [virtual]
used as the title of page containing all the index of all concepts.
Implements Translator.
Definition at line 2392 of file translator_sv.h.
    { return "Konceptlista"; }
trConceptListDescription() [1/2]
virtual QCString TranslatorSwedish::trConceptListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the concept list
Implements Translator.
Definition at line 2404 of file translator_sv.h.
    {
      QCString result="Hr r listan ver alla ";
      if (!extractAll) result+="dokumenterade ";
      result+="koncept med en kort beskrivning:";
      return result;
    }
trConceptListDescription() [2/2]
virtual QCString TranslatorSwedish::trConceptListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the concept list
Implements Translator.
Definition at line 2404 of file translator_sv.h.
    {
      QCString result="Hr r listan ver alla ";
      if (!extractAll) result+="dokumenterade ";
      result+="koncept med en kort beskrivning:";
      return result;
    }
trConceptReference() [1/2]
virtual QCString TranslatorSwedish::trConceptReference (const QCString & conceptName) [inline], [virtual]
used as the title of the HTML page of a C++20 concept page
Implements Translator.
Definition at line 2384 of file translator_sv.h.
    {
      QCString result=conceptName;
      result+=" Konceptreferens";
      return result;
    }
trConceptReference() [2/2]
virtual QCString TranslatorSwedish::trConceptReference (const QCString & conceptName) [inline], [virtual]
used as the title of the HTML page of a C++20 concept page
Implements Translator.
Definition at line 2384 of file translator_sv.h.
    {
      QCString result=conceptName;
      result+=" Konceptreferens";
      return result;
    }
trConstantDocumentation() [1/2]
virtual QCString TranslatorSwedish::trConstantDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2233 of file translator_sv.h.
    {
        return "Konstantdokumentation";
    }
trConstantDocumentation() [2/2]
virtual QCString TranslatorSwedish::trConstantDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2233 of file translator_sv.h.
    {
        return "Konstantdokumentation";
    }
trConstantGroupReference() [1/2]
virtual QCString TranslatorSwedish::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 2073 of file translator_sv.h.
    {
      QCString result=namespaceName;
      result+=" Referens till konstantgrupp";
      return result;
    }
trConstantGroupReference() [2/2]
virtual QCString TranslatorSwedish::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 2073 of file translator_sv.h.
    {
      QCString result=namespaceName;
      result+=" Referens till konstantgrupp";
      return result;
    }
trConstantGroups() [1/2]
virtual QCString TranslatorSwedish::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 2069 of file translator_sv.h.
    { return "Konstantgrupper"; }
trConstantGroups() [2/2]
virtual QCString TranslatorSwedish::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 2069 of file translator_sv.h.
    { return "Konstantgrupper"; }
trConstants() [1/2]
virtual QCString TranslatorSwedish::trConstants () [inline], [virtual]
Implements Translator.
Definition at line 2229 of file translator_sv.h.
    {
        return "Konstanter";
    }
trConstants() [2/2]
virtual QCString TranslatorSwedish::trConstants () [inline], [virtual]
Implements Translator.
Definition at line 2229 of file translator_sv.h.
    {
        return "Konstanter";
    }
trConstructorDocumentation() [1/2]
virtual QCString TranslatorSwedish::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 946 of file translator_sv.h.
    {
      return "Dokumentation av konstruktorer och destruktorer";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorSwedish::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 946 of file translator_sv.h.
    {
      return "Dokumentation av konstruktorer och destruktorer";
    }
trCopyright() [1/2]
virtual QCString TranslatorSwedish::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1956 of file translator_sv.h.
    { return "Copyright"; }
trCopyright() [2/2]
virtual QCString TranslatorSwedish::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1956 of file translator_sv.h.
    { return "Copyright"; }
trCustomReference() [1/2]
virtual QCString TranslatorSwedish::trCustomReference (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 2225 of file translator_sv.h.
    { return QCString(name)+"referens"; }
References setup::name.
trCustomReference() [2/2]
virtual QCString TranslatorSwedish::trCustomReference (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 2225 of file translator_sv.h.
    { return QCString(name)+"referens"; }
References setup::name.
trDataMemberDocumentation() [1/2]
virtual QCString TranslatorSwedish::trDataMemberDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2360 of file translator_sv.h.
    {
        return "Datamedlemsdokumentation";
    }
trDataMemberDocumentation() [2/2]
virtual QCString TranslatorSwedish::trDataMemberDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2360 of file translator_sv.h.
    {
        return "Datamedlemsdokumentation";
    }
trDataMembers() [1/2]
virtual QCString TranslatorSwedish::trDataMembers () [inline], [virtual]
Implements Translator.
Definition at line 2356 of file translator_sv.h.
    {
        return "Datamedlemmar";
    }
trDataMembers() [2/2]
virtual QCString TranslatorSwedish::trDataMembers () [inline], [virtual]
Implements Translator.
Definition at line 2356 of file translator_sv.h.
    {
        return "Datamedlemmar";
    }
trDataTypes() [1/2]
virtual QCString TranslatorSwedish::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1709 of file translator_sv.h.
    { return "Datatyper"; }
trDataTypes() [2/2]
virtual QCString TranslatorSwedish::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1709 of file translator_sv.h.
    { return "Datatyper"; }
trDate() [1/2]
virtual QCString TranslatorSwedish::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 640 of file translator_sv.h.
    { return "Datum"; }
trDate() [2/2]
virtual QCString TranslatorSwedish::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 640 of file translator_sv.h.
    { return "Datum"; }
trDateTime() [1/2]
virtual QCString TranslatorSwedish::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1909 of file translator_sv.h.
    {
      static const char *days[] = { "Mn","Tis","Ons","Tor","Fre","Lr","Sn" };
      static const char *months[] = { "Jan","Feb","Mar","Apr","Maj","Jun","Jul","Aug","Sep","Okt","Nov","Dec" };
      QCString sdate;
      sdate.sprintf("%s %d %s %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDateTime() [2/2]
virtual QCString TranslatorSwedish::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1909 of file translator_sv.h.
    {
      static const char *days[] = { "Mn","Tis","Ons","Tor","Fre","Lr","Sn" };
      static const char *months[] = { "Jan","Feb","Mar","Apr","Maj","Jun","Jul","Aug","Sep","Okt","Nov","Dec" };
      QCString sdate;
      sdate.sprintf("%s %d %s %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDayOfWeek() [1/2]
virtual QCString TranslatorSwedish::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1925 of file translator_sv.h.
    {
      static const char *days_short[] = { "mn", "tis", "ons", "tor", "fre", "lr", "sn" };
      static const char *days_full[] = { "mndag", "tisdag", "onsdag", "torsdag", "fredag", "lrdag", "sndag" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayOfWeek() [2/2]
virtual QCString TranslatorSwedish::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1925 of file translator_sv.h.
    {
      static const char *days_short[] = { "mn", "tis", "ons", "tor", "fre", "lr", "sn" };
      static const char *days_full[] = { "mndag", "tisdag", "onsdag", "torsdag", "fredag", "lrdag", "sndag" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod() [1/2]
virtual QCString TranslatorSwedish::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1941 of file translator_sv.h.
    {
      static const char *dayPeriod[] = { "fm", "em" };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorSwedish::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1941 of file translator_sv.h.
    {
      static const char *dayPeriod[] = { "fm", "em" };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorSwedish::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 913 of file translator_sv.h.
    {
      return "Definition p rad @0 i filen @1.";
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorSwedish::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 913 of file translator_sv.h.
    {
      return "Definition p rad @0 i filen @1.";
    }
trDefinedIn() [1/2]
virtual QCString TranslatorSwedish::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 272 of file translator_sv.h.
    { return "definierad i"; }
trDefinedIn() [2/2]
virtual QCString TranslatorSwedish::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 272 of file translator_sv.h.
    { return "definierad i"; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorSwedish::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 917 of file translator_sv.h.
    {
      return "Definition i filen @0.";
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorSwedish::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 917 of file translator_sv.h.
    {
      return "Definition i filen @0.";
    }
trDefineDocumentation() [1/2]
virtual QCString TranslatorSwedish::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 572 of file translator_sv.h.
    { return "Dokumentation ver makrodefinitioner"; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorSwedish::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 572 of file translator_sv.h.
    { return "Dokumentation ver makrodefinitioner"; }
trDefines() [1/2]
virtual QCString TranslatorSwedish::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 536 of file translator_sv.h.
    { return "Makron"; }
trDefines() [2/2]
virtual QCString TranslatorSwedish::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 536 of file translator_sv.h.
    { return "Makron"; }
trDefineValue() [1/2]
virtual QCString TranslatorSwedish::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1240 of file translator_sv.h.
    {
      return "Vrde:";
    }
trDefineValue() [2/2]
virtual QCString TranslatorSwedish::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1240 of file translator_sv.h.
    {
      return "Vrde:";
    }
trDeprecated() [1/2]
virtual QCString TranslatorSwedish::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 926 of file translator_sv.h.
    {
      return "Obsolet";
    }
trDeprecated() [2/2]
virtual QCString TranslatorSwedish::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 926 of file translator_sv.h.
    {
      return "Obsolet";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorSwedish::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1436 of file translator_sv.h.
    {
      return "Lista ver frldrade";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorSwedish::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1436 of file translator_sv.h.
    {
      return "Lista ver frldrade";
    }
trDesignUnitDocumentation() [1/2]
virtual QCString TranslatorSwedish::trDesignUnitDocumentation () [inline], [virtual]
VHDL design unit documentation
Implements Translator.
Definition at line 2370 of file translator_sv.h.
    { return "Designenhetsdokumentation"; }
Referenced by trClassDocumentation().
trDesignUnitDocumentation() [2/2]
virtual QCString TranslatorSwedish::trDesignUnitDocumentation () [inline], [virtual]
VHDL design unit documentation
Implements Translator.
Definition at line 2370 of file translator_sv.h.
    { return "Designenhetsdokumentation"; }
trDesignUnitHierarchy() [1/2]
virtual QCString TranslatorSwedish::trDesignUnitHierarchy () [inline], [virtual]
VHDL design unit hierarchy
Implements Translator.
Definition at line 2117 of file translator_sv.h.
    { return "Designenhetshirarki"; }
trDesignUnitHierarchy() [2/2]
virtual QCString TranslatorSwedish::trDesignUnitHierarchy () [inline], [virtual]
VHDL design unit hierarchy
Implements Translator.
Definition at line 2117 of file translator_sv.h.
    { return "Designenhetshirarki"; }
trDesignUnitIndex() [1/2]
virtual QCString TranslatorSwedish::trDesignUnitIndex () [inline], [virtual]
VHDL design unit index
Implements Translator.
Definition at line 2135 of file translator_sv.h.
    { return "Designenhetsindex"; }
trDesignUnitIndex() [2/2]
virtual QCString TranslatorSwedish::trDesignUnitIndex () [inline], [virtual]
VHDL design unit index
Implements Translator.
Definition at line 2135 of file translator_sv.h.
    { return "Designenhetsindex"; }
trDesignUnitList() [1/2]
virtual QCString TranslatorSwedish::trDesignUnitList () [inline], [virtual]
VHDL design unit list
Implements Translator.
Definition at line 2120 of file translator_sv.h.
    { return "Designenhetslista"; }
trDesignUnitList() [2/2]
virtual QCString TranslatorSwedish::trDesignUnitList () [inline], [virtual]
VHDL design unit list
Implements Translator.
Definition at line 2120 of file translator_sv.h.
    { return "Designenhetslista"; }
trDesignUnitListDescription() [1/2]
virtual QCString TranslatorSwedish::trDesignUnitListDescription () [inline], [virtual]
VHDL design unit list description Orginal: Here is a list of all design unit members with links to the Entities they belong to:
Implements Translator.
Definition at line 2129 of file translator_sv.h.
    {
        return "Hr r en lista av alla designenhetsmedlemmar med lnkar till "
               "entiteterna som de hr till:";
    }
trDesignUnitListDescription() [2/2]
virtual QCString TranslatorSwedish::trDesignUnitListDescription () [inline], [virtual]
VHDL design unit list description Orginal: Here is a list of all design unit members with links to the Entities they belong to:
Implements Translator.
Definition at line 2129 of file translator_sv.h.
    {
        return "Hr r en lista av alla designenhetsmedlemmar med lnkar till "
               "entiteterna som de hr till:";
    }
trDesignUnitMembers() [1/2]
virtual QCString TranslatorSwedish::trDesignUnitMembers () [inline], [virtual]
VHDL design unit members
Implements Translator.
Definition at line 2123 of file translator_sv.h.
    { return "Designenhetsmedlemmar"; }
trDesignUnitMembers() [2/2]
virtual QCString TranslatorSwedish::trDesignUnitMembers () [inline], [virtual]
VHDL design unit members
Implements Translator.
Definition at line 2123 of file translator_sv.h.
    { return "Designenhetsmedlemmar"; }
trDesignUnits() [1/2]
virtual QCString TranslatorSwedish::trDesignUnits () [inline], [virtual]
VHDL design units
Implements Translator.
Definition at line 2138 of file translator_sv.h.
    { return "Designenheter"; }
trDesignUnits() [2/2]
virtual QCString TranslatorSwedish::trDesignUnits () [inline], [virtual]
VHDL design units
Implements Translator.
Definition at line 2138 of file translator_sv.h.
    { return "Designenheter"; }
trDetailedDescription() [1/2]
virtual QCString TranslatorSwedish::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 205 of file translator_sv.h.
    { return "Detaljerad beskrivning"; }
trDetailedDescription() [2/2]
virtual QCString TranslatorSwedish::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 205 of file translator_sv.h.
    { return "Detaljerad beskrivning"; }
trDetailLevel() [1/2]
virtual QCString TranslatorSwedish::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1968 of file translator_sv.h.
    { return "detaljniv"; }
trDetailLevel() [2/2]
virtual QCString TranslatorSwedish::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1968 of file translator_sv.h.
    { return "detaljniv"; }
trDictionaries() [1/2]
virtual QCString TranslatorSwedish::trDictionaries () [inline], [virtual]
Implements Translator.
Definition at line 2245 of file translator_sv.h.
    {
        return "Uppslagsverk";
    }
trDictionaries() [2/2]
virtual QCString TranslatorSwedish::trDictionaries () [inline], [virtual]
Implements Translator.
Definition at line 2245 of file translator_sv.h.
    {
        return "Uppslagsverk";
    }
trDictionaryDocumentation() [1/2]
virtual QCString TranslatorSwedish::trDictionaryDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2249 of file translator_sv.h.
    {
        return "Uppslagsverksdokumentation";
    }
trDictionaryDocumentation() [2/2]
virtual QCString TranslatorSwedish::trDictionaryDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2249 of file translator_sv.h.
    {
        return "Uppslagsverksdokumentation";
    }
trDir() [1/2]
virtual QCString TranslatorSwedish::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in singular or plural form (singular).
Implements Translator.
Definition at line 1603 of file translator_sv.h.
    {
      QCString result((first_capital ? "Katalog" : "katalog"));
      if (!singular) result+="er";
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorSwedish::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in singular or plural form (singular).
Implements Translator.
Definition at line 1603 of file translator_sv.h.
    {
      QCString result((first_capital ? "Katalog" : "katalog"));
      if (!singular) result+="er";
      return result;
    }
trDirDepGraph() [1/2]
virtual QCString TranslatorSwedish::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1960 of file translator_sv.h.
    { return QCString("Katalogberoendegraf fr ")+name+":"; }
References setup::name.
trDirDepGraph() [2/2]
virtual QCString TranslatorSwedish::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1960 of file translator_sv.h.
    { return QCString("Katalogberoendegraf fr ")+name+":"; }
References setup::name.
trDirDocumentation() [1/2]
virtual QCString TranslatorSwedish::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1585 of file translator_sv.h.
    { return "Katalogdokumentation"; }
trDirDocumentation() [2/2]
virtual QCString TranslatorSwedish::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1585 of file translator_sv.h.
    { return "Katalogdokumentation"; }
trDirectories() [1/2]
virtual QCString TranslatorSwedish::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1591 of file translator_sv.h.
    { return "Kataloger"; }
trDirectories() [2/2]
virtual QCString TranslatorSwedish::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1591 of file translator_sv.h.
    { return "Kataloger"; }
trDirIndex() [1/2]
virtual QCString TranslatorSwedish::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1579 of file translator_sv.h.
    { return "Katalogstruktur"; }
trDirIndex() [2/2]
virtual QCString TranslatorSwedish::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1579 of file translator_sv.h.
    { return "Katalogstruktur"; }
trDirReference() [1/2]
virtual QCString TranslatorSwedish::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1597 of file translator_sv.h.
    { QCString result=dirName; result+=" Katalogreferens"; return result; }
trDirReference() [2/2]
virtual QCString TranslatorSwedish::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1597 of file translator_sv.h.
    { QCString result=dirName; result+=" Katalogreferens"; return result; }
trDirRelation() [1/2]
virtual QCString TranslatorSwedish::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1848 of file translator_sv.h.
    {
      return QCString(name)+" Relation";
    }
References setup::name.
trDirRelation() [2/2]
virtual QCString TranslatorSwedish::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1848 of file translator_sv.h.
    {
      return QCString(name)+" Relation";
    }
References setup::name.
trDocumentation() [1/2]
virtual QCString TranslatorSwedish::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 456 of file translator_sv.h.
    { return "Dokumentation"; }
trDocumentation() [2/2]
virtual QCString TranslatorSwedish::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 456 of file translator_sv.h.
    { return "Dokumentation"; }
trEnumerations() [1/2]
virtual QCString TranslatorSwedish::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 548 of file translator_sv.h.
    { return "Egenupprknande typer"; }
trEnumerations() [2/2]
virtual QCString TranslatorSwedish::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 548 of file translator_sv.h.
    { return "Egenupprknande typer"; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorSwedish::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 584 of file translator_sv.h.
    { return "Dokumentation ver egenupprknande typer"; ; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorSwedish::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 584 of file translator_sv.h.
    { return "Dokumentation ver egenupprknande typer"; ; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorSwedish::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1638 of file translator_sv.h.
    { return "Upprknings-dokumentation"; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorSwedish::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1638 of file translator_sv.h.
    { return "Upprknings-dokumentation"; }
trEnumerationValues() [1/2]
virtual QCString TranslatorSwedish::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 566 of file translator_sv.h.
    { return "Egenupprknade typers vrden"; }
trEnumerationValues() [2/2]
virtual QCString TranslatorSwedish::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 566 of file translator_sv.h.
    { return "Egenupprknade typers vrden"; }
trEnumGeneratedFromFiles() [1/2]
virtual QCString TranslatorSwedish::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1980 of file translator_sv.h.
    { QCString result = "Dokumentationen fr denna enum var genererad frn fjlande fil";
      if (!single) result += "er";
      result+=":";
      return result;
    }
trEnumGeneratedFromFiles() [2/2]
virtual QCString TranslatorSwedish::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1980 of file translator_sv.h.
    { QCString result = "Dokumentationen fr denna enum var genererad frn fjlande fil";
      if (!single) result += "er";
      result+=":";
      return result;
    }
trEnumName() [1/2]
virtual QCString TranslatorSwedish::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 264 of file translator_sv.h.
    { return "enum-namn"; }
trEnumName() [2/2]
virtual QCString TranslatorSwedish::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 264 of file translator_sv.h.
    { return "enum-namn"; }
trEnumReference() [1/2]
virtual QCString TranslatorSwedish::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1988 of file translator_sv.h.
    { return QCString(name)+" Enum-referens"; }
References setup::name.
trEnumReference() [2/2]
virtual QCString TranslatorSwedish::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1988 of file translator_sv.h.
    { return QCString(name)+" Enum-referens"; }
References setup::name.
trEnumValue() [1/2]
virtual QCString TranslatorSwedish::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 268 of file translator_sv.h.
    { return "enum-vrde"; }
trEnumValue() [2/2]
virtual QCString TranslatorSwedish::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 268 of file translator_sv.h.
    { return "enum-vrde"; }
trEventDocumentation() [1/2]
virtual QCString TranslatorSwedish::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1453 of file translator_sv.h.
    {
      return "Hndelsedokumentation";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorSwedish::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1453 of file translator_sv.h.
    {
      return "Hndelsedokumentation";
    }
trEvents() [1/2]
virtual QCString TranslatorSwedish::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1448 of file translator_sv.h.
    {
      return "Hndelser";
    }
trEvents() [2/2]
virtual QCString TranslatorSwedish::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1448 of file translator_sv.h.
    {
      return "Hndelser";
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorSwedish::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 526 of file translator_sv.h.
    { return "Exempeldokumentation"; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorSwedish::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 526 of file translator_sv.h.
    { return "Exempeldokumentation"; }
trExamples() [1/2]
virtual QCString TranslatorSwedish::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 335 of file translator_sv.h.
    { return "Exempel"; }
trExamples() [2/2]
virtual QCString TranslatorSwedish::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 335 of file translator_sv.h.
    { return "Exempel"; }
trExamplesDescription() [1/2]
virtual QCString TranslatorSwedish::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 442 of file translator_sv.h.
    { return "Hr fljer en lista med alla exempel:"; }
trExamplesDescription() [2/2]
virtual QCString TranslatorSwedish::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 442 of file translator_sv.h.
    { return "Hr fljer en lista med alla exempel:"; }
trExceptionDocumentation() [1/2]
virtual QCString TranslatorSwedish::trExceptionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2326 of file translator_sv.h.
    {
        return "Undantagsdokumentation";
    }
trExceptionDocumentation() [2/2]
virtual QCString TranslatorSwedish::trExceptionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2326 of file translator_sv.h.
    {
        return "Undantagsdokumentation";
    }
trExceptionHierarchy() [1/2]
virtual QCString TranslatorSwedish::trExceptionHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2317 of file translator_sv.h.
    {
        return "Undantagshirarki";
    }
trExceptionHierarchy() [2/2]
virtual QCString TranslatorSwedish::trExceptionHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2317 of file translator_sv.h.
    {
        return "Undantagshirarki";
    }
trExceptionHierarchyDescription() [1/2]
virtual QCString TranslatorSwedish::trExceptionHierarchyDescription () [inline], [virtual]
Orginal: This inheritance list is sorted roughly, but not completely, alphabetically:
Implements Translator.
Definition at line 2322 of file translator_sv.h.
    {
        return "Denna arvslista r grovt sorterad, men inte helt, i alfabetisk ordning:";
    }
trExceptionHierarchyDescription() [2/2]
virtual QCString TranslatorSwedish::trExceptionHierarchyDescription () [inline], [virtual]
Orginal: This inheritance list is sorted roughly, but not completely, alphabetically:
Implements Translator.
Definition at line 2322 of file translator_sv.h.
    {
        return "Denna arvslista r grovt sorterad, men inte helt, i alfabetisk ordning:";
    }
trExceptionIndex() [1/2]
virtual QCString TranslatorSwedish::trExceptionIndex () [inline], [virtual]
Implements Translator.
Definition at line 2304 of file translator_sv.h.
    {
        return "Undantagsindex";
    }
trExceptionIndex() [2/2]
virtual QCString TranslatorSwedish::trExceptionIndex () [inline], [virtual]
Implements Translator.
Definition at line 2304 of file translator_sv.h.
    {
        return "Undantagsindex";
    }
trExceptionList() [1/2]
virtual QCString TranslatorSwedish::trExceptionList () [inline], [virtual]
Implements Translator.
Definition at line 2308 of file translator_sv.h.
    {
        return "Undantagslista";
    }
trExceptionList() [2/2]
virtual QCString TranslatorSwedish::trExceptionList () [inline], [virtual]
Implements Translator.
Definition at line 2308 of file translator_sv.h.
    {
        return "Undantagslista";
    }
trExceptionListDescription() [1/2]
virtual QCString TranslatorSwedish::trExceptionListDescription () [inline], [virtual]
Orginal: Here are the exceptions with brief descriptions:
Implements Translator.
Definition at line 2313 of file translator_sv.h.
    {
        return "Hr r undantagen med en kort beskrivning:";
    }
trExceptionListDescription() [2/2]
virtual QCString TranslatorSwedish::trExceptionListDescription () [inline], [virtual]
Orginal: Here are the exceptions with brief descriptions:
Implements Translator.
Definition at line 2313 of file translator_sv.h.
    {
        return "Hr r undantagen med en kort beskrivning:";
    }
trExceptions() [1/2]
virtual QCString TranslatorSwedish::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 656 of file translator_sv.h.
    { return "Undantag"; }
trExceptions() [2/2]
virtual QCString TranslatorSwedish::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 656 of file translator_sv.h.
    { return "Undantag"; }
trExtendsClass() [1/2]
virtual QCString TranslatorSwedish::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 2028 of file translator_sv.h.
    {
      return "Utkar klass @0.";
    }
trExtendsClass() [2/2]
virtual QCString TranslatorSwedish::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 2028 of file translator_sv.h.
    {
      return "Utkar klass @0.";
    }
trFile() [1/2]
virtual QCString TranslatorSwedish::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1309 of file translator_sv.h.
    {
      QCString result((first_capital ? "Fil" : "fil"));
      if (!singular) result+="er";
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorSwedish::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1309 of file translator_sv.h.
    {
      QCString result((first_capital ? "Fil" : "fil"));
      if (!singular) result+="er";
      return result;
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorSwedish::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 520 of file translator_sv.h.
    { return "Fildokumentation"; }
trFileDocumentation() [2/2]
virtual QCString TranslatorSwedish::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 520 of file translator_sv.h.
    { return "Fildokumentation"; }
trFileIn() [1/2]
virtual QCString TranslatorSwedish::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1885 of file translator_sv.h.
    {
      return "Fil i "+name;
    }
References setup::name.
trFileIn() [2/2]
virtual QCString TranslatorSwedish::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1885 of file translator_sv.h.
    {
      return "Fil i "+name;
    }
References setup::name.
trFileIndex() [1/2]
virtual QCString TranslatorSwedish::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 489 of file translator_sv.h.
    { return "Filindex"; }
trFileIndex() [2/2]
virtual QCString TranslatorSwedish::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 489 of file translator_sv.h.
    { return "Filindex"; }
trFileList() [1/2]
virtual QCString TranslatorSwedish::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 301 of file translator_sv.h.
    { return "Fillista"; }
trFileList() [2/2]
virtual QCString TranslatorSwedish::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 301 of file translator_sv.h.
    { return "Fillista"; }
trFileListDescription() [1/2]
virtual QCString TranslatorSwedish::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 349 of file translator_sv.h.
    {
      QCString result="Hr fljer en lista ver alla ";
      if (!extractAll) result+="dokumenterade ";
      result+="filer, med en kort beskrivning:";
      return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorSwedish::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 349 of file translator_sv.h.
    {
      QCString result="Hr fljer en lista ver alla ";
      if (!extractAll) result+="dokumenterade ";
      result+="filer, med en kort beskrivning:";
      return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorSwedish::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 318 of file translator_sv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globala symboler";
      }
      else
      {
        return "Filmedlemmar";
      }
    }
References Config_getBool.
trFileMembers() [2/2]
virtual QCString TranslatorSwedish::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 318 of file translator_sv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globala symboler";
      }
      else
      {
        return "Filmedlemmar";
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
virtual QCString TranslatorSwedish::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 419 of file translator_sv.h.
    {
      QCString result="Hr fljer en lista ver alla ";
      if (!extractAll) result+="dokumenterade ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funktioner, variabler, definitioner, enumerationer "
                "och typdefinitioner";
      }
      else
      {
        result+= "filmedlemmar";
      }
      result+= " med lnkar till ";
      if (extractAll)
        result+= "filerna de tillhr:";
      else
        result+= "dokumentationen:";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorSwedish::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 419 of file translator_sv.h.
    {
      QCString result="Hr fljer en lista ver alla ";
      if (!extractAll) result+="dokumenterade ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funktioner, variabler, definitioner, enumerationer "
                "och typdefinitioner";
      }
      else
      {
        result+= "filmedlemmar";
      }
      result+= " med lnkar till ";
      if (extractAll)
        result+= "filerna de tillhr:";
      else
        result+= "dokumentationen:";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorSwedish::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 720 of file translator_sv.h.
    {
      QCString result=fileName;
      result+=" filreferens";
      return result;
    }
trFileReference() [2/2]
virtual QCString TranslatorSwedish::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 720 of file translator_sv.h.
    {
      QCString result=fileName;
      result+=" filreferens";
      return result;
    }
trFriends() [1/2]
virtual QCString TranslatorSwedish::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 683 of file translator_sv.h.
    { return "Vnner"; }
trFriends() [2/2]
virtual QCString TranslatorSwedish::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 683 of file translator_sv.h.
    { return "Vnner"; }
trFunctionAndProc() [1/2]
virtual QCString TranslatorSwedish::trFunctionAndProc () [inline], [virtual]
VHDL functions/procedures/processes
Implements Translator.
Definition at line 2141 of file translator_sv.h.
    { return "Funktioner/Procedurer/Processer"; }
trFunctionAndProc() [2/2]
virtual QCString TranslatorSwedish::trFunctionAndProc () [inline], [virtual]
VHDL functions/procedures/processes
Implements Translator.
Definition at line 2141 of file translator_sv.h.
    { return "Funktioner/Procedurer/Processer"; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorSwedish::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 590 of file translator_sv.h.
    { return "Dokumentation ver funktioner"; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorSwedish::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 590 of file translator_sv.h.
    { return "Dokumentation ver funktioner"; }
trFunctions() [1/2]
virtual QCString TranslatorSwedish::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 554 of file translator_sv.h.
    { return "Funktioner"; }
trFunctions() [2/2]
virtual QCString TranslatorSwedish::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 554 of file translator_sv.h.
    { return "Funktioner"; }
trGeneratedAt() [1/2]
virtual QCString TranslatorSwedish::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 617 of file translator_sv.h.
    {
      QCString result="Skapad "+date;
      if (!projName.isEmpty()) result+=" fr "+projName;
      result+=" av";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorSwedish::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 617 of file translator_sv.h.
    {
      QCString result="Skapad "+date;
      if (!projName.isEmpty()) result+=" fr "+projName;
      result+=" av";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorSwedish::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 256 of file translator_sv.h.
    { QCString result="Automatiskt skapad av Doxygen";
      if (!s.isEmpty()) result+=" fr "+s;
      result+=" frn kllkoden.";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorSwedish::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 256 of file translator_sv.h.
    { QCString result="Automatiskt skapad av Doxygen";
      if (!s.isEmpty()) result+=" fr "+s;
      result+=" frn kllkoden.";
      return result;
    }
References s.
trGeneratedBy() [1/2]
virtual QCString TranslatorSwedish::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 660 of file translator_sv.h.
    { return "Skapad av"; }
trGeneratedBy() [2/2]
virtual QCString TranslatorSwedish::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 660 of file translator_sv.h.
    { return "Skapad av"; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorSwedish::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 868 of file translator_sv.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      QCString result="Dokumentationen fr ";
      switch(compType)
      {
        case ClassDef::Class: result+=vhdlOpt? "denna designenhets":"denna klass"; break;
        case ClassDef::Struct: result+="denna strukt"; break;
        case ClassDef::Union: result+="denna union"; break;
        case ClassDef::Interface: result+="detta grnssnitt"; break;
        case ClassDef::Protocol: result+="detta protokoll"; break;
        case ClassDef::Category: result+="denna kategori"; break;
        case ClassDef::Exception: result+="detta undantag"; break;
        default: break;
      }
      result+=" var genererad frn fljande fil";
      if (single) result+=":"; else result+="er:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, Config_getBool, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorSwedish::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 868 of file translator_sv.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      QCString result="Dokumentationen fr ";
      switch(compType)
      {
        case ClassDef::Class: result+=vhdlOpt? "denna designenhets":"denna klass"; break;
        case ClassDef::Struct: result+="denna strukt"; break;
        case ClassDef::Union: result+="denna union"; break;
        case ClassDef::Interface: result+="detta grnssnitt"; break;
        case ClassDef::Protocol: result+="detta protokoll"; break;
        case ClassDef::Category: result+="denna kategori"; break;
        case ClassDef::Exception: result+="detta undantag"; break;
        default: break;
      }
      result+=" var genererad frn fljande fil";
      if (single) result+=":"; else result+="er:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, Config_getBool, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorSwedish::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1795 of file translator_sv.h.
    {
      // single is true implies a single file
      QCString result="Dokumentationen fr ";
      switch(compType)
      {
        case ClassDef::Class: result+="denna modul"; break;
        case ClassDef::Struct: result+="denna typ"; break;
        case ClassDef::Union: result+="denna union"; break;
        case ClassDef::Interface: result+="detta grnssnitt"; break;
        case ClassDef::Protocol: result+="detta protokoll"; break;
        case ClassDef::Category: result+="denna kategori"; break;
        case ClassDef::Exception: result+="detta undantag"; break;
        default: break;
      }
      result+=" genererades frn fljade fil";
      if (single) result+=":"; else result+="er:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorSwedish::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1795 of file translator_sv.h.
    {
      // single is true implies a single file
      QCString result="Dokumentationen fr ";
      switch(compType)
      {
        case ClassDef::Class: result+="denna modul"; break;
        case ClassDef::Struct: result+="denna typ"; break;
        case ClassDef::Union: result+="denna union"; break;
        case ClassDef::Interface: result+="detta grnssnitt"; break;
        case ClassDef::Protocol: result+="detta protokoll"; break;
        case ClassDef::Category: result+="denna kategori"; break;
        case ClassDef::Exception: result+="detta undantag"; break;
        default: break;
      }
      result+=" genererades frn fljade fil";
      if (single) result+=":"; else result+="er:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorSwedish::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1367 of file translator_sv.h.
    {
      QCString result((first_capital ? "Global" : "global"));
      if (!singular) result+="er";
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorSwedish::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1367 of file translator_sv.h.
    {
      QCString result((first_capital ? "Global" : "global"));
      if (!singular) result+="er";
      return result;
    }
trGlobalNamespace() [1/2]
virtual QCString TranslatorSwedish::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1860 of file translator_sv.h.
    {
      return "Global namnrymd";
    }
trGlobalNamespace() [2/2]
virtual QCString TranslatorSwedish::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1860 of file translator_sv.h.
    {
      return "Global namnrymd";
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorSwedish::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 956 of file translator_sv.h.
    {
      return "G till denna fils dokumentation.";
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorSwedish::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 956 of file translator_sv.h.
    {
      return "G till denna fils dokumentation.";
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorSwedish::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 989 of file translator_sv.h.
    {
      return "G till den grafiska klasshierarkin";
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorSwedish::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 989 of file translator_sv.h.
    {
      return "G till den grafiska klasshierarkin";
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorSwedish::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 951 of file translator_sv.h.
    {
      return "G till denna fils kllkod.";
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorSwedish::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 951 of file translator_sv.h.
    {
      return "G till denna fils kllkod.";
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorSwedish::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 993 of file translator_sv.h.
    {
      return "G till den textbaserade klasshierarkin";
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorSwedish::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 993 of file translator_sv.h.
    {
      return "G till den textbaserade klasshierarkin";
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorSwedish::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 985 of file translator_sv.h.
    {
      return "Grafisk klasshierarki";
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorSwedish::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 985 of file translator_sv.h.
    {
      return "Grafisk klasshierarki";
    }
trGroup() [1/2]
virtual QCString TranslatorSwedish::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1331 of file translator_sv.h.
    {
      QCString result((first_capital ? "Modul" : "modul"));
      if (!singular) result+="er";
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorSwedish::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1331 of file translator_sv.h.
    {
      QCString result((first_capital ? "Modul" : "modul"));
      if (!singular) result+="er";
      return result;
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorSwedish::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 468 of file translator_sv.h.
    { return "Hierarkiskt index"; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorSwedish::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 468 of file translator_sv.h.
    { return "Hierarkiskt index"; }
trImplementedFromList() [1/2]
virtual QCString TranslatorSwedish::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1404 of file translator_sv.h.
    {
      return "Implementerar "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorSwedish::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1404 of file translator_sv.h.
    {
      return "Implementerar "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorSwedish::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1412 of file translator_sv.h.
    {
      return "Implementerad i "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorSwedish::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1412 of file translator_sv.h.
    {
      return "Implementerad i "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorSwedish::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 1085 of file translator_sv.h.
    {
      return "Den hr grafen visar vilka filer som direkt eller "
             "indirekt inkluderar denna filen:";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorSwedish::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 1085 of file translator_sv.h.
    {
      return "Den hr grafen visar vilka filer som direkt eller "
             "indirekt inkluderar denna filen:";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorSwedish::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 941 of file translator_sv.h.
    {
      return "Include-beroendediagram fr "+fName+":";
    }
trInclDepGraph() [2/2]
virtual QCString TranslatorSwedish::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 941 of file translator_sv.h.
    {
      return "Include-beroendediagram fr "+fName+":";
    }
trIncludesFileIn() [1/2]
virtual QCString TranslatorSwedish::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1894 of file translator_sv.h.
    {
      return "Inkluderar fil i "+name;
    }
References setup::name.
trIncludesFileIn() [2/2]
virtual QCString TranslatorSwedish::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1894 of file translator_sv.h.
    {
      return "Inkluderar fil i "+name;
    }
References setup::name.
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorSwedish::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 250 of file translator_sv.h.
    { return " med alla rvda medlemmar."; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorSwedish::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 250 of file translator_sv.h.
    { return " med alla rvda medlemmar."; }
trInheritedByList() [1/2]
virtual QCString TranslatorSwedish::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 796 of file translator_sv.h.
    {
      return "rvd av "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorSwedish::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 796 of file translator_sv.h.
    {
      return "rvd av "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom() [1/2]
virtual QCString TranslatorSwedish::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1992 of file translator_sv.h.
    { return QCString(members)+" rvd ifrn "+what; }
trInheritedFrom() [2/2]
virtual QCString TranslatorSwedish::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1992 of file translator_sv.h.
    { return QCString(members)+" rvd ifrn "+what; }
trInheritsList() [1/2]
virtual QCString TranslatorSwedish::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 786 of file translator_sv.h.
    {
      return "rver "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorSwedish::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 786 of file translator_sv.h.
    {
      return "rver "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorSwedish::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 976 of file translator_sv.h.
    {
      return "Begynnelsevrde:";
    }
trInitialValue() [2/2]
virtual QCString TranslatorSwedish::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 976 of file translator_sv.h.
    {
      return "Begynnelsevrde:";
    }
trInstanceMethods() [1/2]
virtual QCString TranslatorSwedish::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 2044 of file translator_sv.h.
    {
      return "Instansmetoder";
    }
trInstanceMethods() [2/2]
virtual QCString TranslatorSwedish::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 2044 of file translator_sv.h.
    {
      return "Instansmetoder";
    }
trInterfaceDocumentation() [1/2]
virtual QCString TranslatorSwedish::trInterfaceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2279 of file translator_sv.h.
    {
        return "Grnssnittsdokumentation";
    }
trInterfaceDocumentation() [2/2]
virtual QCString TranslatorSwedish::trInterfaceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2279 of file translator_sv.h.
    {
        return "Grnssnittsdokumentation";
    }
trInterfaceHierarchy() [1/2]
virtual QCString TranslatorSwedish::trInterfaceHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2270 of file translator_sv.h.
    {
        return "Grnssnittshirarkin";
    }
trInterfaceHierarchy() [2/2]
virtual QCString TranslatorSwedish::trInterfaceHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2270 of file translator_sv.h.
    {
        return "Grnssnittshirarkin";
    }
trInterfaceHierarchyDescription() [1/2]
virtual QCString TranslatorSwedish::trInterfaceHierarchyDescription () [inline], [virtual]
Orginal: This inheritance list is sorted roughly, but not completely, alphabetically:
Implements Translator.
Definition at line 2275 of file translator_sv.h.
    {
        return "Denna arvslista r grovt sorterad, men inte helt, i alfabetisk ordning:";
    }
trInterfaceHierarchyDescription() [2/2]
virtual QCString TranslatorSwedish::trInterfaceHierarchyDescription () [inline], [virtual]
Orginal: This inheritance list is sorted roughly, but not completely, alphabetically:
Implements Translator.
Definition at line 2275 of file translator_sv.h.
    {
        return "Denna arvslista r grovt sorterad, men inte helt, i alfabetisk ordning:";
    }
trInterfaceIndex() [1/2]
virtual QCString TranslatorSwedish::trInterfaceIndex () [inline], [virtual]
Implements Translator.
Definition at line 2257 of file translator_sv.h.
    {
        return "Grnssnittsindex";
    }
trInterfaceIndex() [2/2]
virtual QCString TranslatorSwedish::trInterfaceIndex () [inline], [virtual]
Implements Translator.
Definition at line 2257 of file translator_sv.h.
    {
        return "Grnssnittsindex";
    }
trInterfaceList() [1/2]
virtual QCString TranslatorSwedish::trInterfaceList () [inline], [virtual]
Implements Translator.
Definition at line 2261 of file translator_sv.h.
    {
        return "Grnssnittslist";
    }
trInterfaceList() [2/2]
virtual QCString TranslatorSwedish::trInterfaceList () [inline], [virtual]
Implements Translator.
Definition at line 2261 of file translator_sv.h.
    {
        return "Grnssnittslist";
    }
trInterfaceListDescription() [1/2]
virtual QCString TranslatorSwedish::trInterfaceListDescription () [inline], [virtual]
Orginal: Here are the interfaces with brief descriptions:
Implements Translator.
Definition at line 2266 of file translator_sv.h.
    {
        return "Hr r grnssnitten med en kort beskrivning";
    }
trInterfaceListDescription() [2/2]
virtual QCString TranslatorSwedish::trInterfaceListDescription () [inline], [virtual]
Orginal: Here are the interfaces with brief descriptions:
Implements Translator.
Definition at line 2266 of file translator_sv.h.
    {
        return "Hr r grnssnitten med en kort beskrivning";
    }
trInterfaces() [1/2]
virtual QCString TranslatorSwedish::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 2061 of file translator_sv.h.
    { return "Exporterade interface"; }
trInterfaces() [2/2]
virtual QCString TranslatorSwedish::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 2061 of file translator_sv.h.
    { return "Exporterade interface"; }
trInvariant() [1/2]
virtual QCString TranslatorSwedish::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 971 of file translator_sv.h.
    {
      return "Invariant";
    }
trInvariant() [2/2]
virtual QCString TranslatorSwedish::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 971 of file translator_sv.h.
    {
      return "Invariant";
    }
trISOLang() [1/2]
virtual QCString TranslatorSwedish::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 185 of file translator_sv.h.
    {
      return "sv";
    }
trISOLang() [2/2]
virtual QCString TranslatorSwedish::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 185 of file translator_sv.h.
    {
      return "sv";
    }
trLegend() [1/2]
virtual QCString TranslatorSwedish::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1172 of file translator_sv.h.
    {
      return "frklaring";
    }
trLegend() [2/2]
virtual QCString TranslatorSwedish::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1172 of file translator_sv.h.
    {
      return "frklaring";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorSwedish::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 1107 of file translator_sv.h.
    {
      return
        "Den hr sidan frklarar hur man ska tolka de grafer som doxygen "
        "genererar.<p>\n"
        "vervg fljande exempel:\n"
        "\\code\n"
        "/*! Osynlig klass p grund av trunkering */\n"
        "class Invisible { };\n\n"
        "/*! Trunkerad klass, rvningsrelationen r dold */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Klass utan doxygen-kommentarer */\n"
        "class Undocumented { };\n\n"
        "/*! Klass som rvs med publikt arv */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! En template-klass */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Klass som rvs med skyddat arv */\n"
        "class ProtectedBase { };\n\n"
        "/*! Klass som rvs med privat arv */\n"
        "class PrivateBase { };\n\n"
        "/*! Klass som anvnds av den rvda klassen */\n"
        "class Used { };\n\n"
        "/*! Super-klass som rver ett antal andra klasser */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Detta resulterar i att fljande graf genereras:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        "Rektanglarna i den ovanstende grafen har fljande betydelser:\n"
        "</p>\n"
        "<ul>\n"
        "<li>%En fylld gr rektangel representerar den strukt eller klass "
        "som har genererat grafen.</li>\n"
        "<li>%En rektangel med svart kant symboliserar en dokumenterad strukt eller klass.</li>\n"
        "<li>%En rektangel med gr kant symboliserar en odokumenterad strukt eller klass.</li>\n"
        "<li>%En klass med rd kant symboliserar en strukt eller klass dr "
        "alla dess relationer inte visas. %En graf trunkeras om den inte fr "
        "plats inom de givna grnserna.</li>\n"
        "</ul>\n"
        "<p>\n"
        "Pilarna har fljande betydelser:\n"
        "</p>\n"
        "<ul>\n"
        "<li>%En mrkbl pil anvnds fr att visualisera en publik arvrelation "
        "mellan tv klasser.</li>\n"
        "<li>%En mrkgrn pil anvnds fr en skyddad arvsrelation.</li>\n"
        "<li>%En mrkrd pil anvnds fr en privat arvsrelation.\n</li>"
        "<li>%En strckad lila pil anvnds om en klass r innesluten eller "
        "anvnd av en annan klass. Vid pilen str namnet p den eller de "
        "variabler som klassen pilen pekar p kommer t.</li>\n"
        "<li>%En strckad gul pil symboliserar frhllandet mellan en "
        "template-instans och template-klassen, som den instantierades frn.\n"
        "Vid pilen str instansens template-parametrar.</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorSwedish::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 1107 of file translator_sv.h.
    {
      return
        "Den hr sidan frklarar hur man ska tolka de grafer som doxygen "
        "genererar.<p>\n"
        "vervg fljande exempel:\n"
        "\\code\n"
        "/*! Osynlig klass p grund av trunkering */\n"
        "class Invisible { };\n\n"
        "/*! Trunkerad klass, rvningsrelationen r dold */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Klass utan doxygen-kommentarer */\n"
        "class Undocumented { };\n\n"
        "/*! Klass som rvs med publikt arv */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! En template-klass */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Klass som rvs med skyddat arv */\n"
        "class ProtectedBase { };\n\n"
        "/*! Klass som rvs med privat arv */\n"
        "class PrivateBase { };\n\n"
        "/*! Klass som anvnds av den rvda klassen */\n"
        "class Used { };\n\n"
        "/*! Super-klass som rver ett antal andra klasser */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Detta resulterar i att fljande graf genereras:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        "Rektanglarna i den ovanstende grafen har fljande betydelser:\n"
        "</p>\n"
        "<ul>\n"
        "<li>%En fylld gr rektangel representerar den strukt eller klass "
        "som har genererat grafen.</li>\n"
        "<li>%En rektangel med svart kant symboliserar en dokumenterad strukt eller klass.</li>\n"
        "<li>%En rektangel med gr kant symboliserar en odokumenterad strukt eller klass.</li>\n"
        "<li>%En klass med rd kant symboliserar en strukt eller klass dr "
        "alla dess relationer inte visas. %En graf trunkeras om den inte fr "
        "plats inom de givna grnserna.</li>\n"
        "</ul>\n"
        "<p>\n"
        "Pilarna har fljande betydelser:\n"
        "</p>\n"
        "<ul>\n"
        "<li>%En mrkbl pil anvnds fr att visualisera en publik arvrelation "
        "mellan tv klasser.</li>\n"
        "<li>%En mrkgrn pil anvnds fr en skyddad arvsrelation.</li>\n"
        "<li>%En mrkrd pil anvnds fr en privat arvsrelation.\n</li>"
        "<li>%En strckad lila pil anvnds om en klass r innesluten eller "
        "anvnd av en annan klass. Vid pilen str namnet p den eller de "
        "variabler som klassen pilen pekar p kommer t.</li>\n"
        "<li>%En strckad gul pil symboliserar frhllandet mellan en "
        "template-instans och template-klassen, som den instantierades frn.\n"
        "Vid pilen str instansens template-parametrar.</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorSwedish::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 1100 of file translator_sv.h.
    {
      return "Graffrklaring";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorSwedish::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 1100 of file translator_sv.h.
    {
      return "Graffrklaring";
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorSwedish::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 238 of file translator_sv.h.
    { return "Lista ver alla medlemmar"; }
trListOfAllMembers() [2/2]
virtual QCString TranslatorSwedish::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 238 of file translator_sv.h.
    { return "Lista ver alla medlemmar"; }
trLoading() [1/2]
virtual QCString TranslatorSwedish::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1854 of file translator_sv.h.
    {
      return "Laddar...";
    }
trLoading() [2/2]
virtual QCString TranslatorSwedish::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1854 of file translator_sv.h.
    {
      return "Laddar...";
    }
trMainPage() [1/2]
virtual QCString TranslatorSwedish::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 900 of file translator_sv.h.
    { return "Huvudsida"; }
trMainPage() [2/2]
virtual QCString TranslatorSwedish::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 900 of file translator_sv.h.
    { return "Huvudsida"; }
trMember() [1/2]
virtual QCString TranslatorSwedish::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1356 of file translator_sv.h.
    {
      QCString result((first_capital ? "Medlem" : "medlem"));
      if (!singular) result+="mar";
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorSwedish::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1356 of file translator_sv.h.
    {
      QCString result((first_capital ? "Medlem" : "medlem"));
      if (!singular) result+="mar";
      return result;
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorSwedish::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 221 of file translator_sv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentation av flt";
      }
      else
      {
        return "Dokumentation av datamedlemmar";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorSwedish::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 221 of file translator_sv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentation av flt";
      }
      else
      {
        return "Dokumentation av datamedlemmar";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorSwedish::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 213 of file translator_sv.h.
    { return "Dokumentation av egenupprknande medlemmar"; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorSwedish::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 213 of file translator_sv.h.
    { return "Dokumentation av egenupprknande medlemmar"; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorSwedish::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 217 of file translator_sv.h.
    { return "Dokumentation av medlemsfunktioner"; }
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorSwedish::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 217 of file translator_sv.h.
    { return "Dokumentation av medlemsfunktioner"; }
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorSwedish::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1646 of file translator_sv.h.
    { return "Dokumentation fr memlemsfunktion/subrutin"; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorSwedish::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1646 of file translator_sv.h.
    { return "Dokumentation fr memlemsfunktion/subrutin"; }
trMemberList() [1/2]
virtual QCString TranslatorSwedish::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 242 of file translator_sv.h.
    { return "Medlemslista"; }
trMemberList() [2/2]
virtual QCString TranslatorSwedish::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 242 of file translator_sv.h.
    { return "Medlemslista"; }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorSwedish::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 209 of file translator_sv.h.
    { return "Dokumentation av typdefinierade medlemmar"; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorSwedish::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 209 of file translator_sv.h.
    { return "Dokumentation av typdefinierade medlemmar"; }
trMethodDocumentation() [1/2]
virtual QCString TranslatorSwedish::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 2051 of file translator_sv.h.
    {
      return "Metoddokumentation";
    }
trMethodDocumentation() [2/2]
virtual QCString TranslatorSwedish::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 2051 of file translator_sv.h.
    {
      return "Metoddokumentation";
    }
trModule() [1/2]
virtual QCString TranslatorSwedish::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1785 of file translator_sv.h.
    {
     QCString result((first_capital ? "Modul" : "modul"));
      if (!singular) result+="er";
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorSwedish::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1785 of file translator_sv.h.
    {
     QCString result((first_capital ? "Modul" : "modul"));
      if (!singular) result+="er";
      return result;
    }
trModuleDocumentation() [1/2]
virtual QCString TranslatorSwedish::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 495 of file translator_sv.h.
    { return "Moduldokumentation"; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorSwedish::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 495 of file translator_sv.h.
    { return "Moduldokumentation"; }
trModuleIndex() [1/2]
virtual QCString TranslatorSwedish::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 462 of file translator_sv.h.
    { return "Modulindex"; }
trModuleIndex() [2/2]
virtual QCString TranslatorSwedish::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 462 of file translator_sv.h.
    { return "Modulindex"; }
trModuleReference() [1/2]
virtual QCString TranslatorSwedish::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1747 of file translator_sv.h.
    {
      QCString result=namespaceName;
      result+=" Modulreferens";
      return result;
    }
trModuleReference() [2/2]
virtual QCString TranslatorSwedish::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1747 of file translator_sv.h.
    {
      QCString result=namespaceName;
      result+=" Modulreferens";
      return result;
    }
trModules() [1/2]
virtual QCString TranslatorSwedish::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 280 of file translator_sv.h.
    { return "Moduler"; }
trModules() [2/2]
virtual QCString TranslatorSwedish::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 280 of file translator_sv.h.
    { return "Moduler"; }
trModulesDescription() [1/2]
virtual QCString TranslatorSwedish::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 450 of file translator_sv.h.
    { return "Hr fljer en lista ver alla moduler:"; }
trModulesDescription() [2/2]
virtual QCString TranslatorSwedish::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 450 of file translator_sv.h.
    { return "Hr fljer en lista ver alla moduler:"; }
trModulesIndex() [1/2]
virtual QCString TranslatorSwedish::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1778 of file translator_sv.h.
    { return "Modulindex"; }
trModulesIndex() [2/2]
virtual QCString TranslatorSwedish::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1778 of file translator_sv.h.
    { return "Modulindex"; }
trModulesList() [1/2]
virtual QCString TranslatorSwedish::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1713 of file translator_sv.h.
    { return "Modullista"; }
trModulesList() [2/2]
virtual QCString TranslatorSwedish::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1713 of file translator_sv.h.
    { return "Modullista"; }
trModulesListDescription() [1/2]
virtual QCString TranslatorSwedish::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1717 of file translator_sv.h.
    {
      QCString result="Hr r en lista ver alla ";
      if (!extractAll) result+="dokumenterade ";
      result+="moduler med en kort beskrivning:";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorSwedish::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1717 of file translator_sv.h.
    {
      QCString result="Hr r en lista ver alla ";
      if (!extractAll) result+="dokumenterade ";
      result+="moduler med en kort beskrivning:";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorSwedish::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1759 of file translator_sv.h.
    {
      QCString result="Hr r en lista ver alla ";
      if (!extractAll) result+="documented ";
      result+="modulmedlemmar med lnkar till ";
      if (extractAll)
      {
        result+="moduldokumentationen fr varje medlem:";
      }
      else
      {
        result+="modulerna de hr till:";
      }
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorSwedish::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1759 of file translator_sv.h.
    {
      QCString result="Hr r en lista ver alla ";
      if (!extractAll) result+="documented ";
      result+="modulmedlemmar med lnkar till ";
      if (extractAll)
      {
        result+="moduldokumentationen fr varje medlem:";
      }
      else
      {
        result+="modulerna de hr till:";
      }
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorSwedish::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1755 of file translator_sv.h.
    { return "Modulmedlemmar"; }
trModulesMembers() [2/2]
virtual QCString TranslatorSwedish::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1755 of file translator_sv.h.
    { return "Modulmedlemmar"; }
trMonth() [1/2]
virtual QCString TranslatorSwedish::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1933 of file translator_sv.h.
    {
      static const char *months_short[] = { "jan", "feb", "mar", "apr", "maj", "jun", "jul", "aug", "sep", "okt", "nov", "dec" };
      static const char *months_full[] = { "januari", "februari", "mars", "april", "maj", "juni", "juli", "augusti", "september", "oktober", "november", "december" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMonth() [2/2]
virtual QCString TranslatorSwedish::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1933 of file translator_sv.h.
    {
      static const char *months_short[] = { "jan", "feb", "mar", "apr", "maj", "jun", "jul", "aug", "sep", "okt", "nov", "dec" };
      static const char *months_full[] = { "januari", "februari", "mars", "april", "maj", "juni", "juli", "augusti", "september", "oktober", "november", "december" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore() [1/2]
virtual QCString TranslatorSwedish::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 234 of file translator_sv.h.
    { return "Mer..."; }
trMore() [2/2]
virtual QCString TranslatorSwedish::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 234 of file translator_sv.h.
    { return "Mer..."; }
trNamespace() [1/2]
virtual QCString TranslatorSwedish::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1320 of file translator_sv.h.
    {
      QCString result((first_capital ? "Namnrymd" : "namnrymd"));
      if (!singular) result+="er";
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorSwedish::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1320 of file translator_sv.h.
    {
      QCString result((first_capital ? "Namnrymd" : "namnrymd"));
      if (!singular) result+="er";
      return result;
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorSwedish::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 848 of file translator_sv.h.
      { return "Namnrymd-dokumentation"; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorSwedish::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 848 of file translator_sv.h.
      { return "Namnrymd-dokumentation"; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorSwedish::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 842 of file translator_sv.h.
    { return "Namnrymdsindex"; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorSwedish::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 842 of file translator_sv.h.
    { return "Namnrymdsindex"; }
trNamespaceList() [1/2]
virtual QCString TranslatorSwedish::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 668 of file translator_sv.h.
    { return "Namnrymdslista"; }
trNamespaceList() [2/2]
virtual QCString TranslatorSwedish::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 668 of file translator_sv.h.
    { return "Namnrymdslista"; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorSwedish::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 672 of file translator_sv.h.
    {
      QCString result="Hr r en lista ver alla ";
      if (!extractAll) result+="dokumenterade ";
      result+="namnrymder med en kort beskrivning:";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorSwedish::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 672 of file translator_sv.h.
    {
      QCString result="Hr r en lista ver alla ";
      if (!extractAll) result+="dokumenterade ";
      result+="namnrymder med en kort beskrivning:";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorSwedish::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 828 of file translator_sv.h.
    {
      QCString result="Hr r en lista ver alla ";
      if (!extractAll) result+="dokumenterade ";
      result+="namnrymdsmedlemmar med lnkar till ";
      if (extractAll)
        result+=" namnrymd-dokumentationen fr varje medlem:";
      else
        result+="de namnrymder de tillhr:";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorSwedish::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 828 of file translator_sv.h.
    {
      QCString result="Hr r en lista ver alla ";
      if (!extractAll) result+="dokumenterade ";
      result+="namnrymdsmedlemmar med lnkar till ";
      if (extractAll)
        result+=" namnrymd-dokumentationen fr varje medlem:";
      else
        result+="de namnrymder de tillhr:";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorSwedish::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 824 of file translator_sv.h.
    { return "Namnrymdsmedlemmar"; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorSwedish::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 824 of file translator_sv.h.
    { return "Namnrymdsmedlemmar"; }
trNamespaceReference() [1/2]
virtual QCString TranslatorSwedish::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 728 of file translator_sv.h.
    {
      QCString result=namespaceName;
      result+=" namnrymdreferens";
      return result;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorSwedish::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 728 of file translator_sv.h.
    {
      QCString result=namespaceName;
      result+=" namnrymdreferens";
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorSwedish::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 858 of file translator_sv.h.
    { return "Namnrymder"; }
trNamespaces() [2/2]
virtual QCString TranslatorSwedish::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 858 of file translator_sv.h.
    { return "Namnrymder"; }
trNoMatches() [1/2]
virtual QCString TranslatorSwedish::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1872 of file translator_sv.h.
    {
      return "Inga trffar";
    }
trNoMatches() [2/2]
virtual QCString TranslatorSwedish::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1872 of file translator_sv.h.
    {
      return "Inga trffar";
    }
trNote() [1/2]
virtual QCString TranslatorSwedish::trNote () [inline], [virtual]
Implements Translator.
Definition at line 1006 of file translator_sv.h.
    {
      return "Notera";
    }
trNote() [2/2]
virtual QCString TranslatorSwedish::trNote () [inline], [virtual]
Implements Translator.
Definition at line 1006 of file translator_sv.h.
    {
      return "Notera";
    }
trOperationDocumentation() [1/2]
virtual QCString TranslatorSwedish::trOperationDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2352 of file translator_sv.h.
    {
        return "Operationsdokumentation";
    }
trOperationDocumentation() [2/2]
virtual QCString TranslatorSwedish::trOperationDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2352 of file translator_sv.h.
    {
        return "Operationsdokumentation";
    }
trOperations() [1/2]
virtual QCString TranslatorSwedish::trOperations () [inline], [virtual]
Implements Translator.
Definition at line 2348 of file translator_sv.h.
    {
        return "Operationer";
    }
trOperations() [2/2]
virtual QCString TranslatorSwedish::trOperations () [inline], [virtual]
Implements Translator.
Definition at line 2348 of file translator_sv.h.
    {
        return "Operationer";
    }
trOverloadText() [1/2]
virtual QCString TranslatorSwedish::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1617 of file translator_sv.h.
    {
      return "Det hr r en verlagrad medlemsfunktion "
             "tillhandahllen fr bekvmlighet. Den enda som "
             "skiljer sig frn ovanstende funktion r vilka "
             "argument den tar emot.";
    }
trOverloadText() [2/2]
virtual QCString TranslatorSwedish::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1617 of file translator_sv.h.
    {
      return "Det hr r en verlagrad medlemsfunktion "
             "tillhandahllen fr bekvmlighet. Den enda som "
             "skiljer sig frn ovanstende funktion r vilka "
             "argument den tar emot.";
    }
trPackage() [1/2]
virtual QCString TranslatorSwedish::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1224 of file translator_sv.h.
    {
      return "Paket "+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorSwedish::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1224 of file translator_sv.h.
    {
      return "Paket "+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorSwedish::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1489 of file translator_sv.h.
    {
      return "Paketattribut";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorSwedish::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1489 of file translator_sv.h.
    {
      return "Paketattribut";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorSwedish::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1471 of file translator_sv.h.
    {
      return "Paketfunktioner";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorSwedish::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1471 of file translator_sv.h.
    {
      return "Paketfunktioner";
    }
trPackageListDescription() [1/2]
virtual QCString TranslatorSwedish::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1229 of file translator_sv.h.
    {
      return "Hr r en lista ver paketen med en kort beskrivning "
             "(om sdan finns):";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorSwedish::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1229 of file translator_sv.h.
    {
      return "Hr r en lista ver paketen med en kort beskrivning "
             "(om sdan finns):";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorSwedish::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1475 of file translator_sv.h.
    {
      return "Paketmedlemmar";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorSwedish::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1475 of file translator_sv.h.
    {
      return "Paketmedlemmar";
    }
trPackages() [1/2]
virtual QCString TranslatorSwedish::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1235 of file translator_sv.h.
    {
      return "Paket";
    }
trPackages() [2/2]
virtual QCString TranslatorSwedish::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1235 of file translator_sv.h.
    {
      return "Paket";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorSwedish::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1464 of file translator_sv.h.
    {
      return "Pakettyper";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorSwedish::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1464 of file translator_sv.h.
    {
      return "Pakettyper";
    }
trPage() [1/2]
virtual QCString TranslatorSwedish::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1342 of file translator_sv.h.
    {
      QCString result((first_capital ? "Sid" : "sid"));
      if (singular)
         result+="a";
      else
         result+="or";
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorSwedish::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1342 of file translator_sv.h.
    {
      QCString result((first_capital ? "Sid" : "sid"));
      if (singular)
         result+="a";
      else
         result+="or";
      return result;
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorSwedish::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 906 of file translator_sv.h.
    { return "s."; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorSwedish::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 906 of file translator_sv.h.
    { return "s."; }
trPageIndex() [1/2]
virtual QCString TranslatorSwedish::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 997 of file translator_sv.h.
    {
      return "Sidindex";
    }
trPageIndex() [2/2]
virtual QCString TranslatorSwedish::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 997 of file translator_sv.h.
    {
      return "Sidindex";
    }
trPanelSynchronisationTooltip() [1/2]
virtual QCString TranslatorSwedish::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 2009 of file translator_sv.h.
    {
      QCString opt = enable ? "aktivera" : "inaktivera";
      return "klicka fr att "+opt+" panelsynkronisering";
    }
trPanelSynchronisationTooltip() [2/2]
virtual QCString TranslatorSwedish::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 2009 of file translator_sv.h.
    {
      QCString opt = enable ? "aktivera" : "inaktivera";
      return "klicka fr att "+opt+" panelsynkronisering";
    }
trParameters() [1/2]
virtual QCString TranslatorSwedish::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 652 of file translator_sv.h.
    { return "Parametrar"; }
trParameters() [2/2]
virtual QCString TranslatorSwedish::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 652 of file translator_sv.h.
    { return "Parametrar"; }
trPostcondition() [1/2]
virtual QCString TranslatorSwedish::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 966 of file translator_sv.h.
    {
      return "Postcondition";
    }
trPostcondition() [2/2]
virtual QCString TranslatorSwedish::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 966 of file translator_sv.h.
    {
      return "Postcondition";
    }
trPrecondition() [1/2]
virtual QCString TranslatorSwedish::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 961 of file translator_sv.h.
    {
      return "Precondition";
    }
trPrecondition() [2/2]
virtual QCString TranslatorSwedish::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 961 of file translator_sv.h.
    {
      return "Precondition";
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorSwedish::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1045 of file translator_sv.h.
    {
      return "Privata attribut";
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorSwedish::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1045 of file translator_sv.h.
    {
      return "Privata attribut";
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorSwedish::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 749 of file translator_sv.h.
    { return "Privata medlemmsfunktioner"; }
trPrivateMembers() [2/2]
virtual QCString TranslatorSwedish::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 749 of file translator_sv.h.
    { return "Privata medlemmsfunktioner"; }
trPrivateSlots() [1/2]
virtual QCString TranslatorSwedish::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 751 of file translator_sv.h.
    { return "Privata slots"; }
trPrivateSlots() [2/2]
virtual QCString TranslatorSwedish::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 751 of file translator_sv.h.
    { return "Privata slots"; }
trPrivateTypes() [1/2]
virtual QCString TranslatorSwedish::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 1041 of file translator_sv.h.
    {
      return "Privata typer";
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorSwedish::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 1041 of file translator_sv.h.
    {
      return "Privata typer";
    }
trProperties() [1/2]
virtual QCString TranslatorSwedish::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1197 of file translator_sv.h.
    {
      return "Egenskaper";
    }
trProperties() [2/2]
virtual QCString TranslatorSwedish::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1197 of file translator_sv.h.
    {
      return "Egenskaper";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorSwedish::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1202 of file translator_sv.h.
    {
      return "Egenskapsdokumentation";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorSwedish::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1202 of file translator_sv.h.
    {
      return "Egenskapsdokumentation";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorSwedish::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1033 of file translator_sv.h.
    {
      return "Skyddade attribut";
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorSwedish::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1033 of file translator_sv.h.
    {
      return "Skyddade attribut";
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorSwedish::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 743 of file translator_sv.h.
    { return "Skyddade medlemmsfunktioner"; }
trProtectedMembers() [2/2]
virtual QCString TranslatorSwedish::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 743 of file translator_sv.h.
    { return "Skyddade medlemmsfunktioner"; }
trProtectedSlots() [1/2]
virtual QCString TranslatorSwedish::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 745 of file translator_sv.h.
    { return "Skyddade slots"; }
trProtectedSlots() [2/2]
virtual QCString TranslatorSwedish::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 745 of file translator_sv.h.
    { return "Skyddade slots"; }
trProtectedTypes() [1/2]
virtual QCString TranslatorSwedish::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 1029 of file translator_sv.h.
    {
      return "Skyddade typer";
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorSwedish::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 1029 of file translator_sv.h.
    {
      return "Skyddade typer";
    }
trProvidedByCategory() [1/2]
virtual QCString TranslatorSwedish::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 2019 of file translator_sv.h.
    {
      return "Tillhandahlls av kategori @0.";
    }
trProvidedByCategory() [2/2]
virtual QCString TranslatorSwedish::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 2019 of file translator_sv.h.
    {
      return "Tillhandahlls av kategori @0.";
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorSwedish::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1014 of file translator_sv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dataflt";
      }
      else
      {
        return "Publika attribut";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorSwedish::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1014 of file translator_sv.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dataflt";
      }
      else
      {
        return "Publika attribut";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorSwedish::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 735 of file translator_sv.h.
    { return "Publika medlemsfunktioner"; }
trPublicMembers() [2/2]
virtual QCString TranslatorSwedish::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 735 of file translator_sv.h.
    { return "Publika medlemsfunktioner"; }
trPublicSlots() [1/2]
virtual QCString TranslatorSwedish::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 737 of file translator_sv.h.
    { return "Publika slots"; }
trPublicSlots() [2/2]
virtual QCString TranslatorSwedish::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 737 of file translator_sv.h.
    { return "Publika slots"; }
trPublicTypes() [1/2]
virtual QCString TranslatorSwedish::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 1010 of file translator_sv.h.
    {
      return "Publika typer";
    }
trPublicTypes() [2/2]
virtual QCString TranslatorSwedish::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 1010 of file translator_sv.h.
    {
      return "Publika typer";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorSwedish::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 1073 of file translator_sv.h.
    {
      return "Refererad av";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorSwedish::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 1073 of file translator_sv.h.
    {
      return "Refererad av";
    }
trReferenceManual() [1/2]
virtual QCString TranslatorSwedish::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 530 of file translator_sv.h.
    { return "Referensmanual"; }
trReferenceManual() [2/2]
virtual QCString TranslatorSwedish::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 530 of file translator_sv.h.
    { return "Referensmanual"; }
trReferences() [1/2]
virtual QCString TranslatorSwedish::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1392 of file translator_sv.h.
    {
      return "Referenser";
    }
trReferences() [2/2]
virtual QCString TranslatorSwedish::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1392 of file translator_sv.h.
    {
      return "Referenser";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorSwedish::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 806 of file translator_sv.h.
    {
      return "terskapad frn "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorSwedish::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 806 of file translator_sv.h.
    {
      return "terskapad frn "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorSwedish::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 816 of file translator_sv.h.
    {
      // used in member documentation blocks to produce a list of
      // all member that overwrite the implementation of this member.
      return "terskapad i "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorSwedish::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 816 of file translator_sv.h.
    {
      // used in member documentation blocks to produce a list of
      // all member that overwrite the implementation of this member.
      return "terskapad i "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorSwedish::trRelatedFunctionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 690 of file translator_sv.h.
    { return "Dokumenation av vnners och relaterade funktioner"; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorSwedish::trRelatedFunctionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 690 of file translator_sv.h.
    { return "Dokumenation av vnners och relaterade funktioner"; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorSwedish::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 197 of file translator_sv.h.
    { return "Beslktade funktioner"; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorSwedish::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 197 of file translator_sv.h.
    { return "Beslktade funktioner"; }
trRelatedPages() [1/2]
virtual QCString TranslatorSwedish::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 331 of file translator_sv.h.
    { return "Relaterade sidor"; }
trRelatedPages() [2/2]
virtual QCString TranslatorSwedish::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 331 of file translator_sv.h.
    { return "Relaterade sidor"; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorSwedish::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 446 of file translator_sv.h.
    { return "Hr fljer en lista ver alla relaterade dokumentationssidor:";}
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorSwedish::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 446 of file translator_sv.h.
    { return "Hr fljer en lista ver alla relaterade dokumentationssidor:";}
trRelatedSubscript() [1/2]
virtual QCString TranslatorSwedish::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 201 of file translator_sv.h.
    { return "(Observera att dessa inte r medlemsfunktioner)"; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorSwedish::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 201 of file translator_sv.h.
    { return "(Observera att dessa inte r medlemsfunktioner)"; }
trRemarks() [1/2]
virtual QCString TranslatorSwedish::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 1077 of file translator_sv.h.
    {
      return "Lgg mrke till";
    }
trRemarks() [2/2]
virtual QCString TranslatorSwedish::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 1077 of file translator_sv.h.
    {
      return "Lgg mrke till";
    }
trReturns() [1/2]
virtual QCString TranslatorSwedish::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 644 of file translator_sv.h.
    { return "Returnerar"; }
trReturns() [2/2]
virtual QCString TranslatorSwedish::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 644 of file translator_sv.h.
    { return "Returnerar"; }
trReturnValues() [1/2]
virtual QCString TranslatorSwedish::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 895 of file translator_sv.h.
    { return "Returvrden"; }
trReturnValues() [2/2]
virtual QCString TranslatorSwedish::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 895 of file translator_sv.h.
    { return "Returvrden"; }
trRTFansicp() [1/2]
virtual QCString TranslatorSwedish::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
ANSI_CHARSET 0 (x00) 1252
Implements Translator.
Definition at line 1274 of file translator_sv.h.
    {
      return "1252";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorSwedish::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
ANSI_CHARSET 0 (x00) 1252
Implements Translator.
Definition at line 1274 of file translator_sv.h.
    {
      return "1252";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorSwedish::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1283 of file translator_sv.h.
    {
      return "0";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorSwedish::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1283 of file translator_sv.h.
    {
      return "0";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorSwedish::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1289 of file translator_sv.h.
    {
      return "Index";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorSwedish::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1289 of file translator_sv.h.
    {
      return "Index";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorSwedish::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1424 of file translator_sv.h.
    {
      return "Innehllsfrteckning";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorSwedish::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1424 of file translator_sv.h.
    {
      return "Innehllsfrteckning";
    }
trSearch() [1/2]
virtual QCString TranslatorSwedish::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 339 of file translator_sv.h.
    { return "Sk"; }
trSearch() [2/2]
virtual QCString TranslatorSwedish::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 339 of file translator_sv.h.
    { return "Sk"; }
trSearching() [1/2]
virtual QCString TranslatorSwedish::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1866 of file translator_sv.h.
    {
      return "Sker...";
    }
trSearching() [2/2]
virtual QCString TranslatorSwedish::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1866 of file translator_sv.h.
    {
      return "Sker...";
    }
trSearchMatches() [1/2]
virtual QCString TranslatorSwedish::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1556 of file translator_sv.h.
    {
      return "Trffar:";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorSwedish::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1556 of file translator_sv.h.
    {
      return "Trffar:";
    }
trSearchResults() [1/2]
virtual QCString TranslatorSwedish::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1537 of file translator_sv.h.
    {
      if (numDocuments==0)
      {
        return "Tyvrr finns det inga dokument som matchar din skning.";
      }
      else if (numDocuments==1)
      {
        return "Hittade <b>1</b> dokument som matchar din skning.";
      }
      else
      {
        return "Hittade <b>$num</b> dokument som matchar din skning. "
               "Visar de bsta trffarna frst.";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorSwedish::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1537 of file translator_sv.h.
    {
      if (numDocuments==0)
      {
        return "Tyvrr finns det inga dokument som matchar din skning.";
      }
      else if (numDocuments==1)
      {
        return "Hittade <b>1</b> dokument som matchar din skning.";
      }
      else
      {
        return "Hittade <b>$num</b> dokument som matchar din skning. "
               "Visar de bsta trffarna frst.";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorSwedish::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1525 of file translator_sv.h.
    {
      return "Skresultat";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorSwedish::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1525 of file translator_sv.h.
    {
      return "Skresultat";
    }
trSeeAlso() [1/2]
virtual QCString TranslatorSwedish::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 648 of file translator_sv.h.
    { return "Se ven"; }
trSeeAlso() [2/2]
virtual QCString TranslatorSwedish::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 648 of file translator_sv.h.
    { return "Se ven"; }
trSequenceDocumentation() [1/2]
virtual QCString TranslatorSwedish::trSequenceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2241 of file translator_sv.h.
    {
        return "Sekvensdokumentation";
    }
trSequenceDocumentation() [2/2]
virtual QCString TranslatorSwedish::trSequenceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2241 of file translator_sv.h.
    {
        return "Sekvensdokumentation";
    }
trSequences() [1/2]
virtual QCString TranslatorSwedish::trSequences () [inline], [virtual]
Implements Translator.
Definition at line 2237 of file translator_sv.h.
    {
        return "Sekvenser";
    }
trSequences() [2/2]
virtual QCString TranslatorSwedish::trSequences () [inline], [virtual]
Implements Translator.
Definition at line 2237 of file translator_sv.h.
    {
        return "Sekvenser";
    }
trServiceGeneratedFromFiles() [1/2]
virtual QCString TranslatorSwedish::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 2094 of file translator_sv.h.
    {
      // single is true implies a single file
      QCString result="Dokumentationen fr denna tjnst "
                                "genererades frn fljande fil";
      if (single) result+=":"; else result+="er:";
      return result;
    }
trServiceGeneratedFromFiles() [2/2]
virtual QCString TranslatorSwedish::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 2094 of file translator_sv.h.
    {
      // single is true implies a single file
      QCString result="Dokumentationen fr denna tjnst "
                                "genererades frn fljande fil";
      if (single) result+=":"; else result+="er:";
      return result;
    }
trServiceReference() [1/2]
virtual QCString TranslatorSwedish::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 2080 of file translator_sv.h.
    {
      QCString result=sName;
      result+=" Tjnstereferens";
      return result;
    }
trServiceReference() [2/2]
virtual QCString TranslatorSwedish::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 2080 of file translator_sv.h.
    {
      QCString result=sName;
      result+=" Tjnstereferens";
      return result;
    }
trServices() [1/2]
virtual QCString TranslatorSwedish::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 2065 of file translator_sv.h.
    { return "Inkuderade tjnster"; }
trServices() [2/2]
virtual QCString TranslatorSwedish::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 2065 of file translator_sv.h.
    { return "Inkuderade tjnster"; }
trSignals() [1/2]
virtual QCString TranslatorSwedish::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 739 of file translator_sv.h.
    { return "Signaler"; }
trSignals() [2/2]
virtual QCString TranslatorSwedish::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 739 of file translator_sv.h.
    { return "Signaler"; }
trSince() [1/2]
virtual QCString TranslatorSwedish::trSince () [inline], [virtual]
Implements Translator.
Definition at line 1090 of file translator_sv.h.
    {
      return "Sedan";
    }
trSince() [2/2]
virtual QCString TranslatorSwedish::trSince () [inline], [virtual]
Implements Translator.
Definition at line 1090 of file translator_sv.h.
    {
      return "Sedan";
    }
trSingletonGeneratedFromFiles() [1/2]
virtual QCString TranslatorSwedish::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 2103 of file translator_sv.h.
    {
      // single is true implies a single file
      QCString result="Dokumentationen fr denna singleton "
                                "genererades frn fljande fil";
      if (single) result+=":"; else result+="er:";
      return result;
    }
trSingletonGeneratedFromFiles() [2/2]
virtual QCString TranslatorSwedish::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 2103 of file translator_sv.h.
    {
      // single is true implies a single file
      QCString result="Dokumentationen fr denna singleton "
                                "genererades frn fljande fil";
      if (single) result+=":"; else result+="er:";
      return result;
    }
trSingletonReference() [1/2]
virtual QCString TranslatorSwedish::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 2087 of file translator_sv.h.
    {
      QCString result=sName;
      result+=" Singleton-referens";
      return result;
    }
trSingletonReference() [2/2]
virtual QCString TranslatorSwedish::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 2087 of file translator_sv.h.
    {
      QCString result=sName;
      result+=" Singleton-referens";
      return result;
    }
trSliceInterfaces() [1/2]
virtual QCString TranslatorSwedish::trSliceInterfaces () [inline], [virtual]
Implements Translator.
Definition at line 2253 of file translator_sv.h.
    {
        return "Grnssnitt";
    }
trSliceInterfaces() [2/2]
virtual QCString TranslatorSwedish::trSliceInterfaces () [inline], [virtual]
Implements Translator.
Definition at line 2253 of file translator_sv.h.
    {
        return "Grnssnitt";
    }
trSourceFile() [1/2]
virtual QCString TranslatorSwedish::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1567 of file translator_sv.h.
    {
      return "Kllkodsfilen " + filename;
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorSwedish::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1567 of file translator_sv.h.
    {
      return "Kllkodsfilen " + filename;
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorSwedish::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1496 of file translator_sv.h.
    {
      return "Statiska paketattribut";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorSwedish::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1496 of file translator_sv.h.
    {
      return "Statiska paketattribut";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorSwedish::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1482 of file translator_sv.h.
    {
      return "Statiska paketfunktioner";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorSwedish::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1482 of file translator_sv.h.
    {
      return "Statiska paketfunktioner";
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorSwedish::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1049 of file translator_sv.h.
    {
      return "Statiska privata attribut";
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorSwedish::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1049 of file translator_sv.h.
    {
      return "Statiska privata attribut";
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorSwedish::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 753 of file translator_sv.h.
    { return "Statiska privata medlemmsfunktioner"; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorSwedish::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 753 of file translator_sv.h.
    { return "Statiska privata medlemmsfunktioner"; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorSwedish::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1037 of file translator_sv.h.
    {
      return "Statiska skyddade attribut";
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorSwedish::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1037 of file translator_sv.h.
    {
      return "Statiska skyddade attribut";
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorSwedish::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 747 of file translator_sv.h.
    { return "Statiska skyddade medlemmsfunktioner"; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorSwedish::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 747 of file translator_sv.h.
    { return "Statiska skyddade medlemmsfunktioner"; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorSwedish::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1025 of file translator_sv.h.
    {
      return "Statiska publika attribut";
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorSwedish::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1025 of file translator_sv.h.
    {
      return "Statiska publika attribut";
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorSwedish::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 741 of file translator_sv.h.
    { return "Statiska publika medlemmsfunktioner"; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorSwedish::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 741 of file translator_sv.h.
    { return "Statiska publika medlemmsfunktioner"; }
trStructDocumentation() [1/2]
virtual QCString TranslatorSwedish::trStructDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2300 of file translator_sv.h.
    {
        return "Strukturdokumentation";
    }
trStructDocumentation() [2/2]
virtual QCString TranslatorSwedish::trStructDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2300 of file translator_sv.h.
    {
        return "Strukturdokumentation";
    }
trStructIndex() [1/2]
virtual QCString TranslatorSwedish::trStructIndex () [inline], [virtual]
Implements Translator.
Definition at line 2287 of file translator_sv.h.
    {
        return "Strukturindex";
    }
trStructIndex() [2/2]
virtual QCString TranslatorSwedish::trStructIndex () [inline], [virtual]
Implements Translator.
Definition at line 2287 of file translator_sv.h.
    {
        return "Strukturindex";
    }
trStructList() [1/2]
virtual QCString TranslatorSwedish::trStructList () [inline], [virtual]
Implements Translator.
Definition at line 2291 of file translator_sv.h.
    {
        return "Strukturlist";
    }
trStructList() [2/2]
virtual QCString TranslatorSwedish::trStructList () [inline], [virtual]
Implements Translator.
Definition at line 2291 of file translator_sv.h.
    {
        return "Strukturlist";
    }
trStructListDescription() [1/2]
virtual QCString TranslatorSwedish::trStructListDescription () [inline], [virtual]
Orginal: Here are the structs with brief descriptions:
Implements Translator.
Definition at line 2296 of file translator_sv.h.
    {
        return "Hr r strukturerna med en kort beskrivning:";
    }
trStructListDescription() [2/2]
virtual QCString TranslatorSwedish::trStructListDescription () [inline], [virtual]
Orginal: Here are the structs with brief descriptions:
Implements Translator.
Definition at line 2296 of file translator_sv.h.
    {
        return "Hr r strukturerna med en kort beskrivning:";
    }
trStructs() [1/2]
virtual QCString TranslatorSwedish::trStructs () [inline], [virtual]
Implements Translator.
Definition at line 2283 of file translator_sv.h.
    {
        return "Strukturer";
    }
trStructs() [2/2]
virtual QCString TranslatorSwedish::trStructs () [inline], [virtual]
Implements Translator.
Definition at line 2283 of file translator_sv.h.
    {
        return "Strukturer";
    }
trSubprogram() [1/2]
virtual QCString TranslatorSwedish::trSubprogram (bool first_capital, bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1831 of file translator_sv.h.
    {
      QCString result((first_capital ? "Underprogram" : "underprogram"));
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorSwedish::trSubprogram (bool first_capital, bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1831 of file translator_sv.h.
    {
      QCString result((first_capital ? "Underprogram" : "underprogram"));
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorSwedish::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1703 of file translator_sv.h.
    { return "Dokumentation fr funktion/subrutin"; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorSwedish::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1703 of file translator_sv.h.
    { return "Dokumentation fr funktion/subrutin"; }
trSubprograms() [1/2]
virtual QCString TranslatorSwedish::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1697 of file translator_sv.h.
    { return "Funktioner/subrutiner"; }
trSubprograms() [2/2]
virtual QCString TranslatorSwedish::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1697 of file translator_sv.h.
    { return "Funktioner/subrutiner"; }
trTemplateParameters() [1/2]
virtual QCString TranslatorSwedish::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1972 of file translator_sv.h.
    { return "Mall-parametrar"; }
trTemplateParameters() [2/2]
virtual QCString TranslatorSwedish::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1972 of file translator_sv.h.
    { return "Mall-parametrar"; }
trTest() [1/2]
virtual QCString TranslatorSwedish::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1182 of file translator_sv.h.
    {
      return "Test";
    }
trTest() [2/2]
virtual QCString TranslatorSwedish::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1182 of file translator_sv.h.
    {
      return "Test";
    }
trTestList() [1/2]
virtual QCString TranslatorSwedish::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1187 of file translator_sv.h.
    {
      return "Testlista";
    }
trTestList() [2/2]
virtual QCString TranslatorSwedish::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1187 of file translator_sv.h.
    {
      return "Testlista";
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorSwedish::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 246 of file translator_sv.h.
    { return "Det hr r en fullstndig lista ver medlemmar fr "; }
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorSwedish::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 246 of file translator_sv.h.
    { return "Det hr r en fullstndig lista ver medlemmar fr "; }
trTodo() [1/2]
virtual QCString TranslatorSwedish::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 1059 of file translator_sv.h.
    {
      return "Att-gra";
    }
trTodo() [2/2]
virtual QCString TranslatorSwedish::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 1059 of file translator_sv.h.
    {
      return "Att-gra";
    }
trTodoList() [1/2]
virtual QCString TranslatorSwedish::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 1064 of file translator_sv.h.
    {
      return "Att gra-lista";
    }
trTodoList() [2/2]
virtual QCString TranslatorSwedish::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 1064 of file translator_sv.h.
    {
      return "Att gra-lista";
    }
trType() [1/2]
virtual QCString TranslatorSwedish::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1820 of file translator_sv.h.
    {
      QCString result((first_capital ? "Typ" : "typ"));
      if (!singular) result+="er";
      return result;
    }
trType() [2/2]
virtual QCString TranslatorSwedish::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1820 of file translator_sv.h.
    {
      QCString result((first_capital ? "Typ" : "typ"));
      if (!singular) result+="er";
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorSwedish::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1838 of file translator_sv.h.
    {
      return "Typbegrnsningar";
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorSwedish::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1838 of file translator_sv.h.
    {
      return "Typbegrnsningar";
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorSwedish::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 578 of file translator_sv.h.
    { return "Dokumentation ver typdefinitioner"; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorSwedish::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 578 of file translator_sv.h.
    { return "Dokumentation ver typdefinitioner"; }
trTypedefs() [1/2]
virtual QCString TranslatorSwedish::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 542 of file translator_sv.h.
    { return "Typdefinitioner"; }
trTypedefs() [2/2]
virtual QCString TranslatorSwedish::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 542 of file translator_sv.h.
    { return "Typdefinitioner"; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorSwedish::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1691 of file translator_sv.h.
    { return "Datatypsdokumentation"; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorSwedish::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1691 of file translator_sv.h.
    { return "Datatypsdokumentation"; }
trVariableDocumentation() [1/2]
virtual QCString TranslatorSwedish::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 596 of file translator_sv.h.
    { return "Dokumentation ver variabler"; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorSwedish::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 596 of file translator_sv.h.
    { return "Dokumentation ver variabler"; }
trVariables() [1/2]
virtual QCString TranslatorSwedish::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 560 of file translator_sv.h.
    { return "Variabler"; }
trVariables() [2/2]
virtual QCString TranslatorSwedish::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 560 of file translator_sv.h.
    { return "Variabler"; }
trVersion() [1/2]
virtual QCString TranslatorSwedish::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 636 of file translator_sv.h.
    { return "Version"; }
trVersion() [2/2]
virtual QCString TranslatorSwedish::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 636 of file translator_sv.h.
    { return "Version"; }
trVhdlType() [1/2]
virtual QCString TranslatorSwedish::trVhdlType (uint64 type, bool single) [inline], [virtual]
VHDL type
Implements Translator.
Definition at line 2144 of file translator_sv.h.
    {
      switch(type)
      {
        case VhdlDocGen::LIBRARY:
          return "Biblotek";
        case VhdlDocGen::PACKAGE:
          return "Paket";
        case VhdlDocGen::SIGNAL:
          if (single) return "Signal";
          else return "Signaler";
        case VhdlDocGen::COMPONENT:
          if (single) return "Komponent";
          else return "Komponenter";
        case VhdlDocGen::CONSTANT:
          if (single) return "Konstant";
          else return "Konstanter";
        case VhdlDocGen::ENTITY:
          if (single) return "Entitet";
          else return "Entiteter";
        case VhdlDocGen::TYPE:
          if (single) return "Typ";
          else return "Typer";
        case VhdlDocGen::SUBTYPE:
          if (single) return "Undertyp";
          else return "Undertyper";
        case VhdlDocGen::FUNCTION:
          if (single) return "Funktion";
          else return "Funktioner";
        case VhdlDocGen::RECORD:
          if (single) return "Post";
          else return "Poster";
        case VhdlDocGen::PROCEDURE:
          if (single) return "Procedur";
          else return "Procedurer";
        case VhdlDocGen::ARCHITECTURE:
          if (single) return "Arkitektur";
          else return "Arkitekturer";
        case VhdlDocGen::ATTRIBUTE:
          return "Attribut";
        case VhdlDocGen::PROCESS:
          if (single) return "Process";
          else return "Processer";
        case VhdlDocGen::PORT:
          if (single) return "Port";
          else return "Portar";
        case VhdlDocGen::USE:
          if (single) return "use clause";
          else return "Use Clauses";
        case VhdlDocGen::GENERIC:
          if (single) return "Generisk";
          else return "Generiska";
        case VhdlDocGen::PACKAGE_BODY:
          return "Paketinehll";
        case VhdlDocGen::UNITS:
          return "Enheter";
        case VhdlDocGen::SHAREDVARIABLE:
          if (single) return "Delad Variabel";
          else return "Delade Variabler";
        case VhdlDocGen::VFILE:
          if (single) return "Fil";
          else return "Filer";
        case VhdlDocGen::GROUP:
          if (single) return "Grupp";
          else return "Grupper";
        case VhdlDocGen::INSTANTIATION:
          if (single) return "Instantiation";
          else return "Instantiations";
        case VhdlDocGen::ALIAS:
          return "Alias";
        case VhdlDocGen::CONFIG:
          if (single) return "Konfiguration";
          else return "Konfigurationer";
        case VhdlDocGen::MISCELLANEOUS:
          return "Diverse";
        case VhdlDocGen::UCF_CONST:
          return "Begrnsningar";
        default:
          return "Klass";
      }
    }
References VhdlDocGen::ALIAS, VhdlDocGen::ARCHITECTURE, VhdlDocGen::ATTRIBUTE, VhdlDocGen::COMPONENT, VhdlDocGen::CONFIG, VhdlDocGen::CONSTANT, VhdlDocGen::ENTITY, VhdlDocGen::FUNCTION, VhdlDocGen::GENERIC, VhdlDocGen::GROUP, VhdlDocGen::INSTANTIATION, VhdlDocGen::LIBRARY, VhdlDocGen::MISCELLANEOUS, VhdlDocGen::PACKAGE, VhdlDocGen::PACKAGE_BODY, VhdlDocGen::PORT, VhdlDocGen::PROCEDURE, VhdlDocGen::PROCESS, VhdlDocGen::RECORD, VhdlDocGen::SHAREDVARIABLE, VhdlDocGen::SIGNAL, VhdlDocGen::SUBTYPE, VhdlDocGen::TYPE, VhdlDocGen::UCF_CONST, VhdlDocGen::UNITS, VhdlDocGen::USE, and VhdlDocGen::VFILE.
trVhdlType() [2/2]
virtual QCString TranslatorSwedish::trVhdlType (uint64 type, bool single) [inline], [virtual]
VHDL type
Implements Translator.
Definition at line 2144 of file translator_sv.h.
    {
      switch(type)
      {
        case VhdlDocGen::LIBRARY:
          return "Biblotek";
        case VhdlDocGen::PACKAGE:
          return "Paket";
        case VhdlDocGen::SIGNAL:
          if (single) return "Signal";
          else return "Signaler";
        case VhdlDocGen::COMPONENT:
          if (single) return "Komponent";
          else return "Komponenter";
        case VhdlDocGen::CONSTANT:
          if (single) return "Konstant";
          else return "Konstanter";
        case VhdlDocGen::ENTITY:
          if (single) return "Entitet";
          else return "Entiteter";
        case VhdlDocGen::TYPE:
          if (single) return "Typ";
          else return "Typer";
        case VhdlDocGen::SUBTYPE:
          if (single) return "Undertyp";
          else return "Undertyper";
        case VhdlDocGen::FUNCTION:
          if (single) return "Funktion";
          else return "Funktioner";
        case VhdlDocGen::RECORD:
          if (single) return "Post";
          else return "Poster";
        case VhdlDocGen::PROCEDURE:
          if (single) return "Procedur";
          else return "Procedurer";
        case VhdlDocGen::ARCHITECTURE:
          if (single) return "Arkitektur";
          else return "Arkitekturer";
        case VhdlDocGen::ATTRIBUTE:
          return "Attribut";
        case VhdlDocGen::PROCESS:
          if (single) return "Process";
          else return "Processer";
        case VhdlDocGen::PORT:
          if (single) return "Port";
          else return "Portar";
        case VhdlDocGen::USE:
          if (single) return "use clause";
          else return "Use Clauses";
        case VhdlDocGen::GENERIC:
          if (single) return "Generisk";
          else return "Generiska";
        case VhdlDocGen::PACKAGE_BODY:
          return "Paketinehll";
        case VhdlDocGen::UNITS:
          return "Enheter";
        case VhdlDocGen::SHAREDVARIABLE:
          if (single) return "Delad Variabel";
          else return "Delade Variabler";
        case VhdlDocGen::VFILE:
          if (single) return "Fil";
          else return "Filer";
        case VhdlDocGen::GROUP:
          if (single) return "Grupp";
          else return "Grupper";
        case VhdlDocGen::INSTANTIATION:
          if (single) return "Instantiation";
          else return "Instantiations";
        case VhdlDocGen::ALIAS:
          return "Alias";
        case VhdlDocGen::CONFIG:
          if (single) return "Konfiguration";
          else return "Konfigurationer";
        case VhdlDocGen::MISCELLANEOUS:
          return "Diverse";
        case VhdlDocGen::UCF_CONST:
          return "Begrnsningar";
        default:
          return "Klass";
      }
    }
References VhdlDocGen::ALIAS, VhdlDocGen::ARCHITECTURE, VhdlDocGen::ATTRIBUTE, VhdlDocGen::COMPONENT, VhdlDocGen::CONFIG, VhdlDocGen::CONSTANT, VhdlDocGen::ENTITY, VhdlDocGen::FUNCTION, VhdlDocGen::GENERIC, VhdlDocGen::GROUP, VhdlDocGen::INSTANTIATION, VhdlDocGen::LIBRARY, VhdlDocGen::MISCELLANEOUS, VhdlDocGen::PACKAGE, VhdlDocGen::PACKAGE_BODY, VhdlDocGen::PORT, VhdlDocGen::PROCEDURE, VhdlDocGen::PROCESS, VhdlDocGen::RECORD, VhdlDocGen::SHAREDVARIABLE, VhdlDocGen::SIGNAL, VhdlDocGen::SUBTYPE, VhdlDocGen::TYPE, VhdlDocGen::UCF_CONST, VhdlDocGen::UNITS, VhdlDocGen::USE, and VhdlDocGen::VFILE.
trWarning() [1/2]
virtual QCString TranslatorSwedish::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 632 of file translator_sv.h.
    { return "Varning"; }
trWarning() [2/2]
virtual QCString TranslatorSwedish::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 632 of file translator_sv.h.
    { return "Varning"; }
trWriteList() [1/2]
virtual QCString TranslatorSwedish::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 759 of file translator_sv.h.
    {
      // this function is used to produce a comma-separated list of items.
      // use generateMarker(i) to indicate where item i should be put.
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=", och ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorSwedish::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 759 of file translator_sv.h.
    {
      // this function is used to produce a comma-separated list of items.
      // use generateMarker(i) to indicate where item i should be put.
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=", och ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_sv.h
doxygen/src/translator_sv.h