PageContext::Private Class Reference
Classes
struct Cachable
Public Member Functions
Private (const PageDef *pd, bool isMainPage, bool isExample)
TemplateVariant get (const QCString &n) const
StringVector fields () const
TemplateVariant title () const
TemplateVariant relPath () const
TemplateVariant highlight () const
TemplateVariant subHighlight () const
TemplateVariant example () const
Private (const PageDef *pd, bool isMainPage, bool isExample)
TemplateVariant get (const QCString &n) const
StringVector fields () const
TemplateVariant title () const
TemplateVariant relPath () const
TemplateVariant highlight () const
TemplateVariant subHighlight () const
TemplateVariant example () const
Private Member Functions
TemplateVariant createExample () const
TemplateVariant createExample () const
Private Attributes
const PageDef * m_pageDef
Cachable m_cachable
bool m_isMainPage
bool m_isExample
Static Private Attributes
static const PropertyMap< PageContext::Private > s_inst
Additional Inherited Members
Detailed Description
Definition at line 3268 of file context.cpp.
Constructor & Destructor Documentation
Private() [1/2]
PageContext::Private::Private (const PageDef * pd, bool isMainPage, bool isExample) [inline]
Definition at line 3271 of file context.cpp.
      : DefinitionContext<PageContext::Private>(pd) , m_pageDef(pd), m_isMainPage(isMainPage),
        m_isExample(isExample)
    {
    }
Private() [2/2]
PageContext::Private::Private (const PageDef * pd, bool isMainPage, bool isExample) [inline]
Definition at line 3271 of file context.cpp.
      : DefinitionContext<PageContext::Private>(pd) , m_pageDef(pd), m_isMainPage(isMainPage),
        m_isExample(isExample)
    {
    }
Member Function Documentation
createExample() [1/2]
TemplateVariant PageContext::Private::createExample () const [inline], [private]
Definition at line 3341 of file context.cpp.
    {
      return m_isExample ?
          TemplateVariant(parseDoc(m_pageDef,m_pageDef->docFile(),m_pageDef->docLine(),
                  relPathAsString(),"\\include "+m_pageDef->name(),FALSE)) :
          TemplateVariant("");
    }
References Definition::docFile(), Definition::docLine(), FALSE, m_isExample, m_pageDef, Definition::name(), parseDoc(), and DefinitionContext< PageContext::Private >::relPathAsString().
createExample() [2/2]
TemplateVariant PageContext::Private::createExample () const [inline], [private]
Definition at line 3341 of file context.cpp.
    {
      return m_isExample ?
          TemplateVariant(parseDoc(m_pageDef,m_pageDef->docFile(),m_pageDef->docLine(),
                  relPathAsString(),"\\include "+m_pageDef->name(),FALSE)) :
          TemplateVariant("");
    }
References FALSE, and parseDoc().
example() [1/2]
TemplateVariant PageContext::Private::example () const [inline]
Definition at line 3336 of file context.cpp.
    {
      return m_cachable.example.get(this);
    }
References PageContext::Private::Cachable::example, and m_cachable.
example() [2/2]
TemplateVariant PageContext::Private::example () const [inline]
Definition at line 3336 of file context.cpp.
    {
      return m_cachable.example.get(this);
    }
fields() [1/2]
StringVector PageContext::Private::fields () const [inline]
Definition at line 3279 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
fields() [2/2]
StringVector PageContext::Private::fields () const [inline]
Definition at line 3279 of file context.cpp.
{ return s_inst.fields(); }
get() [1/2]
TemplateVariant PageContext::Private::get (const QCString & n) const [inline]
Definition at line 3278 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), n, and s_inst.
get() [2/2]
TemplateVariant PageContext::Private::get (const QCString & n) const [inline]
Definition at line 3278 of file context.cpp.
{ return s_inst.get(this,n); }
References n.
highlight() [1/2]
TemplateVariant PageContext::Private::highlight () const [inline]
Definition at line 3321 of file context.cpp.
    {
      if (m_isMainPage)
      {
        return "main";
      }
      else
      {
        return "pages";
      }
    }
References m_isMainPage.
Referenced by doxmlparser.compound.codelineType::__init__(), doxmlparser.compound.codelineType::add_highlight(), doxmlparser.compound.codelineType::buildChildren(), doxmlparser.compound.codelineType::exportChildren(), doxmlparser.compound.codelineType::get_highlight(), doxmlparser.compound.codelineType::hasContent_(), doxmlparser.compound.codelineType::insert_highlight_at(), doxmlparser.compound.codelineType::replace_highlight_at(), and doxmlparser.compound.codelineType::set_highlight().
highlight() [2/2]
TemplateVariant PageContext::Private::highlight () const [inline]
Definition at line 3321 of file context.cpp.
    {
      if (m_isMainPage)
      {
        return "main";
      }
      else
      {
        return "pages";
      }
    }
Referenced by doxmlparser.compound.codelineType::__init__(), doxmlparser.compound.codelineType::add_highlight(), doxmlparser.compound.codelineType::buildChildren(), doxmlparser.compound.codelineType::exportChildren(), doxmlparser.compound.codelineType::get_highlight(), doxmlparser.compound.codelineType::hasContent_(), doxmlparser.compound.codelineType::insert_highlight_at(), doxmlparser.compound.codelineType::replace_highlight_at(), and doxmlparser.compound.codelineType::set_highlight().
relPath() [1/2]
TemplateVariant PageContext::Private::relPath () const [inline], [virtual]
Reimplemented from DefinitionContext< PageContext::Private >.
Definition at line 3316 of file context.cpp.
    {
      return m_isMainPage ? TemplateVariant("") :
                            TemplateVariant(DefinitionContext<PageContext::Private>::relPath());
    }
References m_isMainPage.
relPath() [2/2]
TemplateVariant PageContext::Private::relPath () const [inline], [virtual]
Reimplemented from DefinitionContext< PageContext::Private >.
Definition at line 3316 of file context.cpp.
    {
      return m_isMainPage ? TemplateVariant("") :
                            TemplateVariant(DefinitionContext<PageContext::Private>::relPath());
    }
subHighlight() [1/2]
TemplateVariant PageContext::Private::subHighlight () const [inline]
Definition at line 3332 of file context.cpp.
    {
      return "";
    }
subHighlight() [2/2]
TemplateVariant PageContext::Private::subHighlight () const [inline]
Definition at line 3332 of file context.cpp.
    {
      return "";
    }
title() [1/2]
TemplateVariant PageContext::Private::title () const [inline]
Definition at line 3282 of file context.cpp.
    {
      if (m_isMainPage)
      {
        QCString projectName = Config_getString(PROJECT_NAME);
        if (Doxygen::mainPage && !Doxygen::mainPage->title().isEmpty())
        {
          if (Doxygen::mainPage->title().lower()!="notitle")
          {
            return m_pageDef->title();
          }
          else
          {
            return "";
          }
        }
        else if (!projectName.isEmpty())
        {
          return projectName+" "+theTranslator->trDocumentation();
        }
        else
        {
          return theTranslator->trMainPage();
        }
      }
      else if (m_isExample)
      {
        return m_pageDef->name();
      }
      else
      {
        return m_pageDef->title();
      }
    }
References Config_getString, QCString::isEmpty(), m_isExample, m_isMainPage, m_pageDef, Doxygen::mainPage, Definition::name(), theTranslator, title(), PageDef::title(), Translator::trDocumentation(), and Translator::trMainPage().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), doxmlparser.compound.docSimpleSectType::set_title(), and title().
title() [2/2]
TemplateVariant PageContext::Private::title () const [inline]
Definition at line 3282 of file context.cpp.
    {
      if (m_isMainPage)
      {
        QCString projectName = Config_getString(PROJECT_NAME);
        if (Doxygen::mainPage && !Doxygen::mainPage->title().isEmpty())
        {
          if (Doxygen::mainPage->title().lower()!="notitle")
          {
            return m_pageDef->title();
          }
          else
          {
            return "";
          }
        }
        else if (!projectName.isEmpty())
        {
          return projectName+" "+theTranslator->trDocumentation();
        }
        else
        {
          return theTranslator->trMainPage();
        }
      }
      else if (m_isExample)
      {
        return m_pageDef->name();
      }
      else
      {
        return m_pageDef->title();
      }
    }
References Config_getString, QCString::isEmpty(), Doxygen::mainPage, theTranslator, Translator::trDocumentation(), and Translator::trMainPage().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
Member Data Documentation
m_cachable
Cachable PageContext::Private::m_cachable [private]
Definition at line 3354 of file context.cpp.
Referenced by example().
m_isExample
bool PageContext::Private::m_isExample [private]
Definition at line 3356 of file context.cpp.
Referenced by createExample(), and title().
m_isMainPage
bool PageContext::Private::m_isMainPage [private]
Definition at line 3355 of file context.cpp.
Referenced by highlight(), relPath(), and title().
m_pageDef
const PageDef * PageContext::Private::m_pageDef [private]
Definition at line 3349 of file context.cpp.
Referenced by createExample(), and title().
s_inst
const PropertyMap< PageContext::Private > PageContext::Private::s_inst [static], [private]
Initial value:
{
  BASE_PROPERTIES,
  { "title", &Private::title },
  { "highlight", &Private::highlight },
  { "subhighlight",&Private::subHighlight },
  { "example", &Private::example }
}
Definition at line 3357 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp