SymbolListContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
SymbolListContext (const SearchIndexList::const_iterator &start, const SearchIndexList::const_iterator &end)
virtual ~SymbolListContext ()
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
SymbolListContext (const SearchIndexList::const_iterator &start, const SearchIndexList::const_iterator &end)
virtual ~SymbolListContext ()
Static Public Member Functions
static TemplateListIntfPtr alloc (const SearchIndexList::const_iterator &start, const SearchIndexList::const_iterator &end)
static TemplateListIntfPtr alloc (const SearchIndexList::const_iterator &start, const SearchIndexList::const_iterator &end)
Private Attributes
std::unique_ptr< Private > p
Additional Inherited Members
Detailed Description
Definition at line 1247 of file context.h.
Constructor & Destructor Documentation
SymbolListContext() [1/2]
SymbolListContext::SymbolListContext (const SearchIndexList::const_iterator & start, const SearchIndexList::const_iterator & end)
Definition at line 8518 of file context.cpp.
                                                                               : p(std::make_unique<Private>(start,end))
{
}
 SymbolListContext() [1/2]
SymbolListContext::~SymbolListContext () [virtual]
Definition at line 8523 of file context.cpp.
{
}
SymbolListContext() [2/2]
SymbolListContext::SymbolListContext (const SearchIndexList::const_iterator & start, const SearchIndexList::const_iterator & end)
 SymbolListContext() [2/2]
virtual SymbolListContext::~SymbolListContext () [virtual]
Member Function Documentation
alloc() [1/2]
static TemplateListIntfPtr SymbolListContext::alloc (const SearchIndexList::const_iterator & start, const SearchIndexList::const_iterator & end) [inline], [static]
Definition at line 1250 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<SymbolListContext>(start,end)); }
References ghc::filesystem::end().
Referenced by SymbolGroupContext::Private::createSymbolList().
alloc() [2/2]
static TemplateListIntfPtr SymbolListContext::alloc (const SearchIndexList::const_iterator & start, const SearchIndexList::const_iterator & end) [inline], [static]
Definition at line 1250 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<SymbolListContext>(start,end)); }
References ghc::filesystem::end().
at() [1/2]
TemplateVariant SymbolListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 8533 of file context.cpp.
{
  return p->at(index);
}
References p.
at() [2/2]
virtual TemplateVariant SymbolListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
count() [1/2]
size_t SymbolListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Definition at line 8528 of file context.cpp.
{
  return p->count();
}
References p.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
count() [2/2]
virtual size_t SymbolListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
createIterator() [1/2]
TemplateListIntf::ConstIteratorPtr SymbolListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 8538 of file context.cpp.
{
  return p->createIterator();
}
References p.
createIterator() [2/2]
virtual TemplateListIntf::ConstIteratorPtr SymbolListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Member Data Documentation
p
std::unique_ptr< Private > SymbolListContext::p [private]
Definition at line 1265 of file context.h.
Referenced by at(), count(), and createIterator().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.h
doxygen/src/context.h
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp