InputStrList Class Reference
#include <inputstrlist.h>
Public Types
enum ListMode {
ListString = 0
, ListFile = 1
, ListDir = 2
, ListFileDir = ListFile | ListDir
,
ListString = 0
, ListFile = 1
, ListDir = 2
, ListFileDir = ListFile | ListDir
 }
enum ListMode {
ListString = 0
, ListFile = 1
, ListDir = 2
, ListFileDir = ListFile | ListDir
,
ListString = 0
, ListFile = 1
, ListDir = 2
, ListFileDir = ListFile | ListDir
 }
Public Slots
void reset ()
void reset ()
Signals
void changed ()
void showHelp (Input *)
void changed ()
void showHelp (Input *)
Public Member Functions
InputStrList (QGridLayout *layout, int &row, const QString &id, const QStringList &sl, ListMode v, const QString &docs)
void setValue (const QStringList &sl)
QVariant & value ()
void update ()
Kind kind () const
QString docs () const
QString id () const
QString templateDocs () const
void addDependency (Input *)
void setEnabled (bool)
void updateDependencies ()
bool isDefault ()
void writeValue (QTextStream &t, TextCodecAdapter *codec)
void setTemplateDocs (const QString &docs)
bool isEmpty ()
InputStrList (QGridLayout *layout, int &row, const QString &id, const QStringList &sl, ListMode v, const QString &docs)
void setValue (const QStringList &sl)
QVariant & value ()
void update ()
Kind kind () const
QString docs () const
QString id () const
QString templateDocs () const
void addDependency (Input *)
void setEnabled (bool)
void updateDependencies ()
bool isDefault ()
void writeValue (QTextStream &t, TextCodecAdapter *codec)
void setTemplateDocs (const QString &docs)
bool isEmpty ()
Private Slots
void addString ()
void delString ()
void updateString ()
void selectText (const QString &s)
void browseFiles ()
void browseDir ()
void help ()
void addString ()
void delString ()
void updateString ()
void selectText (const QString &s)
void browseFiles ()
void browseDir ()
void help ()
Private Member Functions
void updateDefault ()
void updateDefault ()
Private Attributes
QLabel * m_lab
QLineEdit * m_le
QAction * m_add
QAction * m_del
QAction * m_upd
QAction * m_brFile
QAction * m_brDir
QListWidget * m_lb
QStringList m_default
QStringList m_strList
QVariant m_value
QString m_docs
QString m_id
QString m_tdocs
Detailed Description
Definition at line 28 of file inputstrlist.h.
Member Enumeration Documentation
ListMode [1/2]
enum InputStrList::ListMode
Enumerator
ListString
ListFile
ListDir
ListFileDir
ListString
ListFile
ListDir
ListFileDir
Definition at line 33 of file inputstrlist.h.
                  { ListString = 0,
                    ListFile = 1,
                    ListDir = 2,
                    ListFileDir = ListFile | ListDir
                  };
ListMode [2/2]
enum InputStrList::ListMode
Enumerator
ListString
ListFile
ListDir
ListFileDir
ListString
ListFile
ListDir
ListFileDir
Definition at line 33 of file inputstrlist.h.
                  { ListString = 0,
                    ListFile = 1,
                    ListDir = 2,
                    ListFileDir = ListFile | ListDir
                  };
Constructor & Destructor Documentation
InputStrList() [1/2]
InputStrList::InputStrList (QGridLayout * layout, int & row, const QString & id, const QStringList & sl, ListMode v, const QString & docs)
Definition at line 26 of file inputstrlist.cpp.
  : m_default(sl), m_strList(sl), m_docs(docs), m_id(id)
{
  m_lab = new HelpLabel(id);
  m_le = new QLineEdit;
  m_le->clear();
  QToolBar *toolBar = new QToolBar;
  toolBar->setIconSize(QSize(24,24));
  m_add = toolBar->addAction(QIcon(QString::fromLatin1(":/images/add.png")),QString(),
                             this,SLOT(addString()));
  m_add->setToolTip(tr("Add item"));
  m_del = toolBar->addAction(QIcon(QString::fromLatin1(":/images/del.png")),QString(),
                             this,SLOT(delString()));
  m_del->setToolTip(tr("Delete selected item"));
  m_upd = toolBar->addAction(QIcon(QString::fromLatin1(":/images/refresh.png")),QString(),
                             this,SLOT(updateString()));
  m_upd->setToolTip(tr("Update selected item"));
  m_lb = new QListWidget;
  //m_lb->setMinimumSize(400,100);
  foreach (QString s, m_strList) m_lb->addItem(s);
  m_brFile=0;
  m_brDir=0;
  if (lm!=ListString)
  {
    if (lm&ListFile)
    {
      m_brFile = toolBar->addAction(QIcon(QString::fromLatin1(":/images/file.png")),QString(),
                                    this,SLOT(browseFiles()));
      m_brFile->setToolTip(tr("Browse to a file"));
    }
    if (lm&ListDir)
    {
      m_brDir = toolBar->addAction(QIcon(QString::fromLatin1(":/images/folder.png")),QString(),
                                   this,SLOT(browseDir()));
      m_brDir->setToolTip(tr("Browse to a folder"));
    }
  }
  QHBoxLayout *rowLayout = new QHBoxLayout;
  rowLayout->addWidget(m_le);
  rowLayout->addWidget(toolBar);
  layout->addWidget(m_lab, row,0);
  layout->addLayout(rowLayout, row,1,1,2);
  layout->addWidget(m_lb, row+1,1,1,2);
  row+=2;
  m_value = m_strList;
  connect(m_le, SIGNAL(returnPressed()),
          this, SLOT(addString()));
  connect(m_lb, SIGNAL(currentTextChanged(const QString &)),
          this, SLOT(selectText(const QString &)));
  connect(m_lab, SIGNAL(enter()), SLOT(help()));
  connect(m_lab, SIGNAL(reset()), SLOT(reset()));
}
References addString(), browseDir(), browseFiles(), delString(), help(), ListDir, ListFile, ListString, m_add, m_brDir, m_brFile, m_del, m_lab, m_lb, m_le, m_strList, m_upd, m_value, reset(), s, selectText(), and updateString().
InputStrList() [2/2]
InputStrList::InputStrList (QGridLayout * layout, int & row, const QString & id, const QStringList & sl, ListMode v, const QString & docs)
Member Function Documentation
addDependency() [1/2]
void InputStrList::addDependency (Input *) [inline], [virtual]
Implements Input.
Definition at line 50 of file inputstrlist.h.
{ Q_ASSERT(false); }
addDependency() [2/2]
void InputStrList::addDependency (Input *) [inline], [virtual]
Implements Input.
Definition at line 50 of file inputstrlist.h.
{ Q_ASSERT(false); }
addString [1/2]
void InputStrList::addString () [private], [slot]
Definition at line 94 of file inputstrlist.cpp.
{
  if (!m_le->text().isEmpty())
  {
    m_lb->addItem(m_le->text());
    m_strList.append(m_le->text());
    m_value = m_strList;
    updateDefault();
    emit changed();
    m_le->clear();
  }
}
References changed(), m_lb, m_le, m_strList, m_value, and updateDefault().
Referenced by InputStrList().
addString [2/2]
void InputStrList::addString () [private], [slot]
browseDir [1/2]
void InputStrList::browseDir () [private], [slot]
Definition at line 181 of file inputstrlist.cpp.
{
  QString path = QFileInfo(MainWindow::instance().configFileName()).path();
  QString dirName = QFileDialog::getExistingDirectory();
  if (!dirName.isNull())
  {
    QDir dir(path);
    if (!MainWindow::instance().configFileName().isEmpty() && dir.exists())
    {
      dirName = dir.relativeFilePath(dirName);
    }
    if (dirName.isEmpty())
    {
      dirName=QString::fromLatin1(".");
    }
    m_lb->addItem(dirName);
    m_strList.append(dirName);
    m_value = m_strList;
    updateDefault();
    emit changed();
    m_le->setText(dirName);
  }
}
References changed(), MainWindow::instance(), isEmpty(), m_lb, m_le, m_strList, m_value, and updateDefault().
Referenced by InputStrList().
browseDir [2/2]
void InputStrList::browseDir () [private], [slot]
browseFiles [1/2]
void InputStrList::browseFiles () [private], [slot]
Definition at line 151 of file inputstrlist.cpp.
{
  QString path = QFileInfo(MainWindow::instance().configFileName()).path();
  QStringList fileNames = QFileDialog::getOpenFileNames();
  if (!fileNames.isEmpty())
  {
    QStringList::Iterator it;
    for (it= fileNames.begin(); it != fileNames.end(); ++it)
    {
      QString fileName;
      QDir dir(path);
      if (!MainWindow::instance().configFileName().isEmpty() && dir.exists())
      {
        fileName = dir.relativeFilePath(*it);
      }
      if (fileName.isEmpty())
      {
        fileName = *it;
      }
      m_lb->addItem(fileName);
      m_strList.append(fileName);
      m_value = m_strList;
      updateDefault();
      emit changed();
    }
    m_le->setText(m_strList[0]);
  }
}
References changed(), MainWindow::instance(), isEmpty(), m_lb, m_le, m_strList, m_value, and updateDefault().
Referenced by InputStrList().
browseFiles [2/2]
void InputStrList::browseFiles () [private], [slot]
changed [1/2]
void InputStrList::changed () [signal]
Referenced by addString(), browseDir(), browseFiles(), delString(), and updateString().
changed [2/2]
void InputStrList::changed () [signal]
delString [1/2]
void InputStrList::delString () [private], [slot]
Definition at line 107 of file inputstrlist.cpp.
{
  if (m_lb->currentRow()!=-1)
  {
    int itemIndex = m_lb->currentRow();
    delete m_lb->currentItem();
    m_strList.removeAt(itemIndex);
    m_value = m_strList;
    updateDefault();
    emit changed();
  }
}
References changed(), m_lb, m_strList, m_value, and updateDefault().
Referenced by InputStrList().
delString [2/2]
void InputStrList::delString () [private], [slot]
docs() [1/2]
QString InputStrList::docs () const [inline], [virtual]
Implements Input.
Definition at line 47 of file inputstrlist.h.
{ return m_docs; }
References m_docs.
Referenced by setTemplateDocs().
docs() [2/2]
QString InputStrList::docs () const [inline], [virtual]
Implements Input.
Definition at line 47 of file inputstrlist.h.
{ return m_docs; }
References m_docs.
help [1/2]
void InputStrList::help () [private], [slot]
Definition at line 88 of file inputstrlist.cpp.
{
  showHelp(this);
}
References showHelp().
Referenced by InputStrList().
help [2/2]
void InputStrList::help () [private], [slot]
id() [1/2]
QString InputStrList::id () const [inline], [virtual]
Implements Input.
Definition at line 48 of file inputstrlist.h.
{ return m_id; }
References m_id.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), and doxmlparser.compound.docXRefSectType::set_id().
id() [2/2]
QString InputStrList::id () const [inline], [virtual]
Implements Input.
Definition at line 48 of file inputstrlist.h.
{ return m_id; }
References m_id.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), and doxmlparser.compound.docXRefSectType::set_id().
isDefault() [1/2]
bool InputStrList::isDefault () [virtual]
Implements Input.
Definition at line 260 of file inputstrlist.cpp.
{
  if (m_strList==m_default) return true;
  auto it1 = m_strList.begin();
  auto it2 = m_default.begin();
  while (it1!=m_strList.end() && (*it1).isEmpty())
  {
    ++it1;
  }
  while (it2!=m_default.end() && (*it2).isEmpty())
  {
    ++it2;
  }
  // both lists are empty
  if (it1==m_strList.end() && it2==m_default.end()) return true;
  // one list is empty but the other is not
  if (it1==m_strList.end()) return false;
  if (it2==m_default.end()) return false;
  it1 = m_strList.begin();
  it2 = m_default.begin();
  while (it1!=m_strList.end() && it2!=m_default.end())
  {
    // skip over empty values
    while (it1!=m_strList.end() && (*it1).isEmpty())
    {
      ++it1;
    }
    while (it2!=m_default.end() && (*it2).isEmpty())
    {
      ++it2;
    }
    if ((it1!=m_strList.end()) && (it2!=m_default.end()))
    {
      if ((*it1).trimmed()!= (*it2).trimmed()) // difference so not the default
      {
        return false;
      }
      ++it1;
      ++it2;
    }
    else if ((it1!=m_strList.end()) || (it2!=m_default.end()))
    {
      // one list empty so cannot be the default
      return false;
    }
  }
  return true;
}
References m_default, and m_strList.
Referenced by updateDefault().
isDefault() [2/2]
bool InputStrList::isDefault () [virtual]
Implements Input.
isEmpty() [1/2]
bool InputStrList::isEmpty () [virtual]
Reimplemented from Input.
Definition at line 313 of file inputstrlist.cpp.
{
  foreach (QString s, m_strList)
  {
    if (!s.isEmpty()) return false;
  }
  return true;
}
References m_strList, and s.
Referenced by browseDir(), and browseFiles().
isEmpty() [2/2]
bool InputStrList::isEmpty () [virtual]
Reimplemented from Input.
kind() [1/2]
Kind InputStrList::kind () const [inline], [virtual]
Implements Input.
Definition at line 46 of file inputstrlist.h.
{ return StrList; }
References Input::StrList.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.sectiondefType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.docParamListType::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.sectiondefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.docSimpleSectType::buildAttributes(), doxmlparser.compound.docParamListType::buildAttributes(), doxmlparser.index.CompoundType::buildAttributes(), doxmlparser.index.MemberType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.index.CompoundType::exportAttributes(), doxmlparser.compound.docParamListType::exportAttributes(), doxmlparser.compound.docSimpleSectType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.index.MemberType::exportAttributes(), doxmlparser.compound.sectiondefType::exportAttributes(), doxmlparser.compound.compounddefType::get_kind(), doxmlparser.compound.sectiondefType::get_kind(), doxmlparser.compound.memberdefType::get_kind(), doxmlparser.compound.docSimpleSectType::get_kind(), doxmlparser.compound.docParamListType::get_kind(), doxmlparser.index.CompoundType::get_kind(), doxmlparser.index.MemberType::get_kind(), doxmlparser.compound.compounddefType::set_kind(), doxmlparser.compound.sectiondefType::set_kind(), doxmlparser.compound.memberdefType::set_kind(), doxmlparser.compound.docSimpleSectType::set_kind(), doxmlparser.compound.docParamListType::set_kind(), doxmlparser.index.CompoundType::set_kind(), and doxmlparser.index.MemberType::set_kind().
kind() [2/2]
Kind InputStrList::kind () const [inline], [virtual]
Implements Input.
Definition at line 46 of file inputstrlist.h.
{ return StrList; }
References Input::StrList.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.sectiondefType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.docParamListType::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.sectiondefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.docSimpleSectType::buildAttributes(), doxmlparser.compound.docParamListType::buildAttributes(), doxmlparser.index.CompoundType::buildAttributes(), doxmlparser.index.MemberType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.index.CompoundType::exportAttributes(), doxmlparser.compound.docParamListType::exportAttributes(), doxmlparser.compound.docSimpleSectType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.index.MemberType::exportAttributes(), doxmlparser.compound.sectiondefType::exportAttributes(), doxmlparser.compound.compounddefType::get_kind(), doxmlparser.compound.sectiondefType::get_kind(), doxmlparser.compound.memberdefType::get_kind(), doxmlparser.compound.docSimpleSectType::get_kind(), doxmlparser.compound.docParamListType::get_kind(), doxmlparser.index.CompoundType::get_kind(), doxmlparser.index.MemberType::get_kind(), doxmlparser.compound.compounddefType::set_kind(), doxmlparser.compound.sectiondefType::set_kind(), doxmlparser.compound.memberdefType::set_kind(), doxmlparser.compound.docSimpleSectType::set_kind(), doxmlparser.compound.docParamListType::set_kind(), doxmlparser.index.CompoundType::set_kind(), and doxmlparser.index.MemberType::set_kind().
reset [1/2]
void InputStrList::reset () [slot]
Definition at line 240 of file inputstrlist.cpp.
{
  setValue(m_default);
}
References m_default, and setValue().
Referenced by InputStrList().
reset [2/2]
void InputStrList::reset () [slot]
selectText [1/2]
void InputStrList::selectText (const QString & s) [private], [slot]
Definition at line 133 of file inputstrlist.cpp.
{
  m_le->setText(s);
}
References m_le, and s.
Referenced by InputStrList().
selectText [2/2]
void InputStrList::selectText (const QString & s) [private], [slot]
setEnabled() [1/2]
void InputStrList::setEnabled (bool state) [virtual]
Implements Input.
Definition at line 138 of file inputstrlist.cpp.
{
  m_lab->setEnabled(state);
  m_le->setEnabled(state);
  m_add->setEnabled(state);
  m_del->setEnabled(state);
  m_upd->setEnabled(state);
  m_lb->setEnabled(state);
  if (m_brFile) m_brFile->setEnabled(state);
  if (m_brDir) m_brDir->setEnabled(state);
  updateDefault();
}
References m_add, m_brDir, m_brFile, m_del, m_lab, m_lb, m_le, m_upd, and updateDefault().
setEnabled() [2/2]
void InputStrList::setEnabled (bool) [virtual]
Implements Input.
setTemplateDocs() [1/2]
void InputStrList::setTemplateDocs (const QString & docs) [inline], [virtual]
Implements Input.
Definition at line 55 of file inputstrlist.h.
{ m_tdocs = docs; }
References docs(), and m_tdocs.
setTemplateDocs() [2/2]
void InputStrList::setTemplateDocs (const QString & docs) [inline], [virtual]
Implements Input.
Definition at line 55 of file inputstrlist.h.
{ m_tdocs = docs; }
References docs(), and m_tdocs.
setValue() [1/2]
void InputStrList::setValue (const QStringList & sl)
Definition at line 206 of file inputstrlist.cpp.
{
  m_le->clear();
  m_lb->clear();
  m_strList = sl;
  for (int i=0;i<m_strList.size();i++)
  {
    m_lb->addItem(m_strList[i].trimmed());
  }
  updateDefault();
}
References m_lb, m_le, m_strList, caseconvert::sl, and updateDefault().
Referenced by reset(), and update().
setValue() [2/2]
void InputStrList::setValue (const QStringList & sl)
showHelp [1/2]
void InputStrList::showHelp (Input *) [signal]
Referenced by help().
showHelp [2/2]
void InputStrList::showHelp (Input *) [signal]
templateDocs() [1/2]
QString InputStrList::templateDocs () const [inline], [virtual]
Implements Input.
Definition at line 49 of file inputstrlist.h.
{ return m_tdocs; }
References m_tdocs.
templateDocs() [2/2]
QString InputStrList::templateDocs () const [inline], [virtual]
Implements Input.
Definition at line 49 of file inputstrlist.h.
{ return m_tdocs; }
References m_tdocs.
update() [1/2]
void InputStrList::update () [virtual]
Implements Input.
Definition at line 223 of file inputstrlist.cpp.
{
  setValue(m_value.toStringList());
}
References m_value, and setValue().
Referenced by runtests.Tester::__init__(), and runtests.Tester::run().
update() [2/2]
void InputStrList::update () [virtual]
Implements Input.
Referenced by runtests.Tester::__init__(), and runtests.Tester::run().
updateDefault() [1/2]
void InputStrList::updateDefault () [private]
Definition at line 228 of file inputstrlist.cpp.
{
  if (isDefault() || !m_lab->isEnabled())
  {
    m_lab->setText(QString::fromLatin1("<qt>")+m_id+QString::fromLatin1("</qt>"));
  }
  else
  {
    m_lab->setText(QString::fromLatin1("<qt><font color='red'>")+m_id+QString::fromLatin1("</font></qt>"));
  }
}
References isDefault(), m_id, and m_lab.
Referenced by addString(), browseDir(), browseFiles(), delString(), setEnabled(), setValue(), and updateString().
updateDefault() [2/2]
void InputStrList::updateDefault () [private]
updateDependencies() [1/2]
void InputStrList::updateDependencies () [inline], [virtual]
Implements Input.
Definition at line 52 of file inputstrlist.h.
{}
updateDependencies() [2/2]
void InputStrList::updateDependencies () [inline], [virtual]
Implements Input.
Definition at line 52 of file inputstrlist.h.
{}
updateString [1/2]
void InputStrList::updateString () [private], [slot]
Definition at line 120 of file inputstrlist.cpp.
{
  if (m_lb->currentRow()!=-1 && !m_le->text().isEmpty())
  {
    m_lb->currentItem()->setText(m_le->text());
    m_strList.insert(m_lb->currentRow(),m_le->text());
    m_strList.removeAt(m_lb->currentRow()+1);
    m_value = m_strList;
    updateDefault();
    emit changed();
  }
}
References changed(), m_lb, m_le, m_strList, m_value, and updateDefault().
Referenced by InputStrList().
updateString [2/2]
void InputStrList::updateString () [private], [slot]
value() [1/2]
QVariant & InputStrList::value () [virtual]
Implements Input.
Definition at line 218 of file inputstrlist.cpp.
{
  return m_value;
}
References m_value.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), doxmlparser.compound.docListItemType::__init__(), doxmlparser.compound.spType::__init__(), doxmlparser.compound.spType::buildAttributes(), doxmlparser.compound.docListItemType::buildAttributes(), doxmlparser.compound.MixedContainer::export(), doxmlparser.index.MixedContainer::export(), doxmlparser.compound.docListItemType::exportAttributes(), doxmlparser.compound.spType::exportAttributes(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), doxmlparser.compound.spType::get_value(), doxmlparser.compound.docListItemType::get_value(), doxmlparser.compound.MixedContainer::getValue(), doxmlparser.index.MixedContainer::getValue(), doxmlparser.compound.spType::set_value(), doxmlparser.compound.docListItemType::set_value(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), doxmlparser.compound.MixedContainer::to_etree_simple(), and doxmlparser.index.MixedContainer::to_etree_simple().
value() [2/2]
QVariant & InputStrList::value () [virtual]
Implements Input.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), doxmlparser.compound.docListItemType::__init__(), doxmlparser.compound.spType::__init__(), doxmlparser.compound.spType::buildAttributes(), doxmlparser.compound.docListItemType::buildAttributes(), doxmlparser.compound.MixedContainer::export(), doxmlparser.index.MixedContainer::export(), doxmlparser.compound.docListItemType::exportAttributes(), doxmlparser.compound.spType::exportAttributes(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), doxmlparser.compound.spType::get_value(), doxmlparser.compound.docListItemType::get_value(), doxmlparser.compound.MixedContainer::getValue(), doxmlparser.index.MixedContainer::getValue(), doxmlparser.compound.spType::set_value(), doxmlparser.compound.docListItemType::set_value(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), doxmlparser.compound.MixedContainer::to_etree_simple(), and doxmlparser.index.MixedContainer::to_etree_simple().
writeValue() [1/2]
void InputStrList::writeValue (QTextStream & t, TextCodecAdapter * codec) [virtual]
Implements Input.
Definition at line 245 of file inputstrlist.cpp.
{
  bool first=true;
  foreach (QString s, m_strList)
  {
    if (!first)
    {
      t << " \\\n";
      t << " ";
    }
    first=false;
    writeStringValue(t,codec,s);
  }
}
References m_strList, s, and writeStringValue().
writeValue() [2/2]
void InputStrList::writeValue (QTextStream & t, TextCodecAdapter * codec) [virtual]
Implements Input.
Member Data Documentation
m_add
QAction * InputStrList::m_add [private]
Definition at line 78 of file inputstrlist.h.
Referenced by InputStrList(), and setEnabled().
m_brDir
QAction * InputStrList::m_brDir [private]
Definition at line 82 of file inputstrlist.h.
Referenced by InputStrList(), and setEnabled().
m_brFile
QAction * InputStrList::m_brFile [private]
Definition at line 81 of file inputstrlist.h.
Referenced by InputStrList(), and setEnabled().
m_default
QStringList InputStrList::m_default [private]
Definition at line 84 of file inputstrlist.h.
Referenced by isDefault(), and reset().
m_del
QAction * InputStrList::m_del [private]
Definition at line 79 of file inputstrlist.h.
Referenced by InputStrList(), and setEnabled().
m_docs
QString InputStrList::m_docs [private]
Definition at line 87 of file inputstrlist.h.
Referenced by docs().
m_id
QString InputStrList::m_id [private]
Definition at line 88 of file inputstrlist.h.
Referenced by id(), and updateDefault().
m_lab
QLabel * InputStrList::m_lab [private]
Definition at line 76 of file inputstrlist.h.
Referenced by InputStrList(), setEnabled(), and updateDefault().
m_lb
QListWidget * InputStrList::m_lb [private]
Definition at line 83 of file inputstrlist.h.
Referenced by addString(), browseDir(), browseFiles(), delString(), InputStrList(), setEnabled(), setValue(), and updateString().
m_le
QLineEdit * InputStrList::m_le [private]
Definition at line 77 of file inputstrlist.h.
Referenced by addString(), browseDir(), browseFiles(), InputStrList(), selectText(), setEnabled(), setValue(), and updateString().
m_strList
QStringList InputStrList::m_strList [private]
Definition at line 85 of file inputstrlist.h.
Referenced by addString(), browseDir(), browseFiles(), delString(), InputStrList(), isDefault(), isEmpty(), setValue(), updateString(), and writeValue().
m_tdocs
QString InputStrList::m_tdocs [private]
Definition at line 89 of file inputstrlist.h.
Referenced by setTemplateDocs(), and templateDocs().
m_upd
QAction * InputStrList::m_upd [private]
Definition at line 80 of file inputstrlist.h.
Referenced by InputStrList(), and setEnabled().
m_value
QVariant InputStrList::m_value [private]
Definition at line 86 of file inputstrlist.h.
Referenced by addString(), browseDir(), browseFiles(), delString(), InputStrList(), update(), updateString(), and value().
The documentation for this class was generated from the following files:
doxygen/addon/doxywizard/inputstrlist.h
doxygen/build/doxygen/addon/doxywizard/inputstrlist.h
doxygen/addon/doxywizard/inputstrlist.cpp
doxygen/build/doxygen/addon/doxywizard/inputstrlist.cpp