UCTurma Class Reference
Classe UCTurma.
#include <UCTurma.h>
Public Member Functions
UCTurma (string codTurma, string codUC)
Constructor da classe `UCTurma`.
UCTurma ()
Default constructor da classe `UCTurma`.
bool operator< (const UCTurma &s) const
Overloader do operator `<`.
void addAula (Aula aula)
Modifier do atributo `timetable`.
const string & getCodUc () const
Accessor do atributo `codUC`.
const string & getCodTurma () const
Accessor do atributo `codTurma`.
const list< Aula > & getTimetable () const
Accessor do atributo `timetable`.
Private Attributes
string codUC
string codTurma
list< Aula > timetable
Detailed Description
Classe UCTurma.
A turma de uma UC (Unidade Curricular) é definida pelo código da UC, pelo código da turma e pelo horário.
Definition at line 15 of file UCTurma.h.
Constructor & Destructor Documentation
UCTurma() [1/2]
UCTurma::UCTurma (string codTurma, string codUC)
Constructor da classe `UCTurma`.
Complexidade O(1).
Parameters
codTurma Código da turma.
codUC Código da UC.
Definition at line 3 of file UCTurma.cpp.
: codTurma(codTurma), codUC(codUC) {}
UCTurma() [2/2]
UCTurma::UCTurma ()
Default constructor da classe `UCTurma`.
Complexidade O(1).
Definition at line 15 of file UCTurma.cpp.
{}
Member Function Documentation
addAula()
void UCTurma::addAula (Aula aula)
Modifier do atributo `timetable`.
Complexidade O(1).
Parameters
aula Aula a adicionar ao horário.
Definition at line 17 of file UCTurma.cpp.
                               {
    timetable.push_back(aula);
}
References timetable.
Referenced by GestaoHor::addStudentUCClass(), and GestaoHor::getDataAula().
getCodTurma()
const string & UCTurma::getCodTurma () const
Accessor do atributo `codTurma`.
Complexidade O(1).
Returns
Código da turma.
Definition at line 21 of file UCTurma.cpp.
                                         {
    return codTurma;
}
References codTurma.
Referenced by Estudante::removeTurma().
getCodUc()
const string & UCTurma::getCodUc () const
Accessor do atributo `codUC`.
Complexidade O(1).
Returns
Código da UC.
Definition at line 11 of file UCTurma.cpp.
                                      {
    return codUC;
}
References codUC.
Referenced by Estudante::removeTurma().
getTimetable()
const list< Aula > & UCTurma::getTimetable () const
Accessor do atributo `timetable`.
Complexidade O(1).
Returns
Horário.
Definition at line 25 of file UCTurma.cpp.
                                              {
    return timetable;
}
References timetable.
Referenced by GestaoHor::classConflict().
operator<()
bool UCTurma::operator< (const UCTurma & s) const
Overloader do operator `<`.
Retorna `true` se o código da UC da primeira turma for menor que o da segunda, se forem iguais, retorna `true` se o código da turma da primeira turma for menor do que o da segunda, em qualquer outra situação retorna `false`. Complexidade O(1).
Parameters
s Segunda turma.
Returns
Definition at line 5 of file UCTurma.cpp.
                                              {
    if (this->codUC == s.codUC)
        return this->codTurma < s.codTurma;
    return this->codUC < s.codUC;
}
References codTurma, and codUC.
Member Data Documentation
codTurma
string UCTurma::codTurma [private]
Definition at line 81 of file UCTurma.h.
Referenced by getCodTurma(), and operator<().
codUC
string UCTurma::codUC [private]
Definition at line 80 of file UCTurma.h.
Referenced by getCodUc(), and operator<().
timetable
list<Aula> UCTurma::timetable [private]
Definition at line 82 of file UCTurma.h.
Referenced by addAula(), and getTimetable().
The documentation for this class was generated from the following files:
UCTurma.h
UCTurma.cpp