TemplateImmutableList Class Reference
Default implementation of a immutable context value of type list.
#include <template.h>
Classes
class Private
Private data of a template immutable list object.
Public Member Functions
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
TemplateImmutableList (std::initializer_list< TemplateVariant > elements)
TemplateImmutableList (const std::vector< TemplateVariant > &elements)
virtual ~TemplateImmutableList ()
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
TemplateImmutableList (std::initializer_list< TemplateVariant > elements)
TemplateImmutableList (const std::vector< TemplateVariant > &elements)
virtual ~TemplateImmutableList ()
Static Public Member Functions
static TemplateListIntfPtr alloc (std::initializer_list< TemplateVariant > elements)
static TemplateListIntfPtr alloc (const std::vector< TemplateVariant > &elements)
static TemplateListIntfPtr alloc (std::initializer_list< TemplateVariant > elements)
static TemplateListIntfPtr alloc (const std::vector< TemplateVariant > &elements)
Private Attributes
std::unique_ptr< Private > p
Additional Inherited Members
Detailed Description
Default implementation of a immutable context value of type list.
Definition at line 323 of file template.h.
Constructor & Destructor Documentation
TemplateImmutableList() [1/4]
TemplateImmutableList::TemplateImmutableList (std::initializer_list< TemplateVariant > elements)
Creates a list
Definition at line 513 of file template.cpp.
  : p(std::make_unique<Private>(elements))
{
}
TemplateImmutableList() [2/4]
TemplateImmutableList::TemplateImmutableList (const std::vector< TemplateVariant > & elements)
Definition at line 518 of file template.cpp.
  : p(std::make_unique<Private>(elements))
{
}
 TemplateImmutableList() [1/2]
TemplateImmutableList::~TemplateImmutableList () [virtual]
Destroys the list
Definition at line 523 of file template.cpp.
{
}
TemplateImmutableList() [3/4]
TemplateImmutableList::TemplateImmutableList (std::initializer_list< TemplateVariant > elements)
Creates a list
TemplateImmutableList() [4/4]
TemplateImmutableList::TemplateImmutableList (const std::vector< TemplateVariant > & elements)
 TemplateImmutableList() [2/2]
virtual TemplateImmutableList::~TemplateImmutableList () [virtual]
Destroys the list
Member Function Documentation
alloc() [1/4]
TemplateListIntfPtr TemplateImmutableList::alloc (const std::vector< TemplateVariant > & elements) [static]
Definition at line 547 of file template.cpp.
{
  return std::make_shared<TemplateImmutableList>(elements);
}
alloc() [2/4]
static TemplateListIntfPtr TemplateImmutableList::alloc (const std::vector< TemplateVariant > & elements) [static]
alloc() [3/4]
TemplateListIntfPtr TemplateImmutableList::alloc (std::initializer_list< TemplateVariant > elements) [static]
Creates an instance and returns a shared pointer to it
Definition at line 542 of file template.cpp.
{
  return std::make_shared<TemplateImmutableList>(elements);
}
Referenced by ClassContext::Private::createClasses(), NamespaceContext::Private::createClasses(), FileContext::Private::createClasses(), ModuleContext::Private::createClasses(), ClassIndexContext::Private::createClasses(), ConfigContext::Private::createConfigData(), NamespaceContext::Private::createConstantgroups(), FileContext::Private::createConstantgroups(), ModuleContext::Private::createConstantgroups(), ClassHierarchyContext::Private::createDiagrams(), DirContext::Private::createDirs(), ModuleContext::Private::createDirs(), MemberContext::Private::createEventAttrs(), ClassContext::Private::createExamples(), MemberContext::Private::createExamples(), ModuleContext::Private::createExamples(), DirContext::Private::createFiles(), ModuleContext::Private::createFiles(), MemberContext::Private::createImplementedBy(), MemberContext::Private::createImplements(), InheritedMemberInfoContext::Private::createInheritedFrom(), NamespaceContext::Private::createInlineClasses(), FileContext::Private::createInlineClasses(), ModuleContext::Private::createInlineClasses(), ClassContext::Private::createInnerClasses(), MemberContext::Private::createLabels(), GlobalsIndexContext::Private::createMembersFiltered(), ClassMembersIndexContext::Private::createMembersFiltered(), NamespaceMembersIndexContext::Private::createMembersFiltered(), ModuleContext::Private::createModules(), NamespaceContext::Private::createNamespaces(), FileContext::Private::createNamespaces(), ModuleContext::Private::createNamespaces(), DefinitionContext< T >::createNavigationPath(), ModuleContext::Private::createPages(), DefinitionContext< T >::createPartOfGroups(), MemberContext::Private::createPropertyAttrs(), MemberContext::Private::createReimplementedBy(), MemberContext::Private::createReimplements(), ClassContext::Private::createTemplateDecls(), MemberContext::Private::createTemplateDecls(), ConceptContext::Private::createTemplateDecls(), and DefinitionContext< T >::DefinitionContext().
alloc() [4/4]
static TemplateListIntfPtr TemplateImmutableList::alloc (std::initializer_list< TemplateVariant > elements) [static]
Creates an instance and returns a shared pointer to it
at() [1/2]
TemplateVariant TemplateImmutableList::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 537 of file template.cpp.
{
  return index<p->elems.size() ? p->elems[static_cast<int>(index)] : TemplateVariant();
}
References p.
at() [2/2]
virtual TemplateVariant TemplateImmutableList::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
count() [1/2]
size_t TemplateImmutableList::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Definition at line 527 of file template.cpp.
{
  return p->elems.size();
}
References p.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
count() [2/2]
virtual size_t TemplateImmutableList::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
createIterator() [1/2]
TemplateListIntf::ConstIteratorPtr TemplateImmutableList::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 532 of file template.cpp.
{
  return std::make_unique< TemplateListGenericConstIterator<TemplateImmutableList> >(*this);
}
createIterator() [2/2]
virtual TemplateListIntf::ConstIteratorPtr TemplateImmutableList::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Member Data Documentation
p
std::unique_ptr< Private > TemplateImmutableList::p [private]
Definition at line 343 of file template.h.
Referenced by at(), count(), FilterListSort::determineSortKey(), ExpressionParser::getNextToken(), and FilterAlphaIndex::keyToLabel().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.h
doxygen/src/template.h
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp