MemberListContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
MemberListContext ()
MemberListContext (const MemberList *ml)
MemberListContext (const MemberVector &ml)
virtual ~MemberListContext ()
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
MemberListContext ()
MemberListContext (const MemberList *ml)
MemberListContext (const MemberVector &ml)
virtual ~MemberListContext ()
Static Public Member Functions
static TemplateListIntfPtr alloc ()
static TemplateListIntfPtr alloc (const MemberList *ml)
static TemplateListIntfPtr alloc (const MemberVector &ml)
static TemplateListIntfPtr alloc ()
static TemplateListIntfPtr alloc (const MemberList *ml)
static TemplateListIntfPtr alloc (const MemberVector &ml)
Private Attributes
std::unique_ptr< Private > p
Additional Inherited Members
Detailed Description
Definition at line 1001 of file context.h.
Constructor & Destructor Documentation
MemberListContext() [1/6]
MemberListContext::MemberListContext ()
Definition at line 7580 of file context.cpp.
                                     : p(std::make_unique<Private>())
{
}
MemberListContext() [2/6]
MemberListContext::MemberListContext (const MemberList * ml)
Definition at line 7584 of file context.cpp.
                                                           : p(std::make_unique<Private>())
{
  if (list)
  {
    bool details = list->listType()&MemberListType_detailedLists;
    for (const auto &md : *list)
    {
      if ((md->isBriefSectionVisible() && !details) ||
          (md->hasDetailedDescription() && details)
         )
      {
        p->addMember(md);
      }
    }
  }
}
References MemberList::listType(), MemberListType_detailedLists, and p.
MemberListContext() [3/6]
MemberListContext::MemberListContext (const MemberVector & ml)
Definition at line 7601 of file context.cpp.
                                                           : p(std::make_unique<Private>())
{
  for (const auto &md : ml)
  {
    p->addMember(md);
  }
}
References p.
 MemberListContext() [1/2]
MemberListContext::~MemberListContext () [virtual]
Definition at line 7609 of file context.cpp.
{
}
MemberListContext() [4/6]
MemberListContext::MemberListContext ()
MemberListContext() [5/6]
MemberListContext::MemberListContext (const MemberList * ml)
MemberListContext() [6/6]
MemberListContext::MemberListContext (const MemberVector & ml)
 MemberListContext() [2/2]
virtual MemberListContext::~MemberListContext () [virtual]
Member Function Documentation
alloc() [1/6]
static TemplateListIntfPtr MemberListContext::alloc () [inline], [static]
Definition at line 1004 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<MemberListContext>()); }
Referenced by MemberContext::Private::createEnumValues(), MemberListInfoContext::Private::createMemberList(), InheritedMemberInfoContext::Private::createMemberList(), ClassContext::Private::createMembers(), MemberGroupInfoContext::Private::createMembers(), MemberContext::Private::createSourceRefBys(), and MemberContext::Private::createSourceRefs().
alloc() [2/6]
static TemplateListIntfPtr MemberListContext::alloc () [inline], [static]
Definition at line 1004 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<MemberListContext>()); }
alloc() [3/6]
static TemplateListIntfPtr MemberListContext::alloc (const MemberList * ml) [inline], [static]
Definition at line 1006 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<MemberListContext>(ml)); }
alloc() [4/6]
static TemplateListIntfPtr MemberListContext::alloc (const MemberList * ml) [inline], [static]
Definition at line 1006 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<MemberListContext>(ml)); }
alloc() [5/6]
static TemplateListIntfPtr MemberListContext::alloc (const MemberVector & ml) [inline], [static]
Definition at line 1008 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<MemberListContext>(ml)); }
alloc() [6/6]
static TemplateListIntfPtr MemberListContext::alloc (const MemberVector & ml) [inline], [static]
Definition at line 1008 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<MemberListContext>(ml)); }
at() [1/2]
TemplateVariant MemberListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 7619 of file context.cpp.
{
  return p->at(index);
}
References p.
at() [2/2]
virtual TemplateVariant MemberListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
count() [1/2]
size_t MemberListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Definition at line 7614 of file context.cpp.
{
  return p->count();
}
References p.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
count() [2/2]
virtual size_t MemberListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
createIterator() [1/2]
TemplateListIntf::ConstIteratorPtr MemberListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 7624 of file context.cpp.
{
  return p->createIterator();
}
References p.
createIterator() [2/2]
virtual TemplateListIntf::ConstIteratorPtr MemberListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Member Data Documentation
p
std::unique_ptr< Private > MemberListContext::p [private]
Definition at line 1023 of file context.h.
Referenced by at(), count(), createIterator(), and MemberListContext().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.h
doxygen/src/context.h
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp