FilterAdd Class Reference
The implementation of the `add` filter.
Static Public Member Functions
static int variantIntValue (const TemplateVariant &v, bool &isInt)
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &arg)
static int variantIntValue (const TemplateVariant &v, bool &isInt)
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &arg)
Detailed Description
The implementation of the `add` filter.
Definition at line 729 of file template.cpp.
Member Function Documentation
apply() [1/2]
static TemplateVariant FilterAdd::apply (const TemplateVariant & v, const TemplateVariant & arg) [inline], [static]
Definition at line 740 of file template.cpp.
    {
      if (!v.isValid())
      {
        return arg;
      }
      bool lhsIsInt = false;
      int lhsValue = variantIntValue(v,lhsIsInt);
      bool rhsIsInt = false;
      int rhsValue = variantIntValue(arg,rhsIsInt);
      if (lhsIsInt && rhsIsInt)
      {
        return lhsValue+rhsValue;
      }
      else if (v.isString() && arg.isString())
      {
        return TemplateVariant(v.toString() + arg.toString());
      }
      else
      {
        return v;
      }
    }
References TemplateVariant::isString(), TemplateVariant::isValid(), TemplateVariant::toString(), and variantIntValue().
apply() [2/2]
static TemplateVariant FilterAdd::apply (const TemplateVariant & v, const TemplateVariant & arg) [inline], [static]
Definition at line 740 of file template.cpp.
    {
      if (!v.isValid())
      {
        return arg;
      }
      bool lhsIsInt = false;
      int lhsValue = variantIntValue(v,lhsIsInt);
      bool rhsIsInt = false;
      int rhsValue = variantIntValue(arg,rhsIsInt);
      if (lhsIsInt && rhsIsInt)
      {
        return lhsValue+rhsValue;
      }
      else if (v.isString() && arg.isString())
      {
        return TemplateVariant(v.toString() + arg.toString());
      }
      else
      {
        return v;
      }
    }
References TemplateVariant::isString(), TemplateVariant::isValid(), and TemplateVariant::toString().
variantIntValue() [1/2]
static int FilterAdd::variantIntValue (const TemplateVariant & v, bool & isInt) [inline], [static]
Definition at line 732 of file template.cpp.
    {
      if (!v.isInt() && v.isString())
      {
        return v.toString().toInt(&isInt);
      }
      return v.isInt() ? v.toInt() : 0;
    }
References TemplateVariant::isInt(), TemplateVariant::isString(), TemplateVariant::toInt(), QCString::toInt(), and TemplateVariant::toString().
Referenced by apply().
variantIntValue() [2/2]
static int FilterAdd::variantIntValue (const TemplateVariant & v, bool & isInt) [inline], [static]
Definition at line 732 of file template.cpp.
    {
      if (!v.isInt() && v.isString())
      {
        return v.toString().toInt(&isInt);
      }
      return v.isInt() ? v.toInt() : 0;
    }
References TemplateVariant::isInt(), TemplateVariant::isString(), TemplateVariant::toInt(), QCString::toInt(), and TemplateVariant::toString().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp