PageContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const QCString &name) const
virtual StringVector fields () const
PageContext (const PageDef *, bool isMainPage, bool isExample)
virtual ~PageContext ()
virtual TemplateVariant get (const QCString &name) const
virtual StringVector fields () const
PageContext (const PageDef *, bool isMainPage, bool isExample)
virtual ~PageContext ()
Static Public Member Functions
static TemplateStructIntfPtr alloc (const PageDef *pd, bool isMainPage, bool isExample)
static TemplateStructIntfPtr alloc (const PageDef *pd, bool isMainPage, bool isExample)
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Definition at line 297 of file context.h.
Constructor & Destructor Documentation
PageContext() [1/2]
PageContext::PageContext (const PageDef * pd, bool isMainPage, bool isExample)
Definition at line 3371 of file context.cpp.
                                                                         : p(std::make_unique<Private>(pd,isMainPage,isExample))
{
}
 PageContext() [1/2]
PageContext::~PageContext () [virtual]
Definition at line 3375 of file context.cpp.
{
}
PageContext() [2/2]
PageContext::PageContext (const PageDef * , bool isMainPage, bool isExample)
 PageContext() [2/2]
virtual PageContext::~PageContext () [virtual]
Member Function Documentation
alloc() [1/2]
static TemplateStructIntfPtr PageContext::alloc (const PageDef * pd, bool isMainPage, bool isExample) [inline], [static]
Definition at line 300 of file context.h.
    { return std::static_pointer_cast<TemplateStructIntf>(std::make_shared<PageContext>(pd,isMainPage,isExample)); }
References isMainPage.
Referenced by PageListContext::Private::addPages(), ModuleContext::Private::createExamples(), NestingNodeContext::Private::createPage(), ModuleContext::Private::createPages(), generateOutputViaTemplate(), and ExampleListContext::Private::Private().
alloc() [2/2]
static TemplateStructIntfPtr PageContext::alloc (const PageDef * pd, bool isMainPage, bool isExample) [inline], [static]
Definition at line 300 of file context.h.
    { return std::static_pointer_cast<TemplateStructIntf>(std::make_shared<PageContext>(pd,isMainPage,isExample)); }
References isMainPage.
fields() [1/2]
StringVector PageContext::fields () const [virtual]
Return the list of fields.
Implements TemplateStructIntf.
Definition at line 3384 of file context.cpp.
{
  return p->fields();
}
References p.
fields() [2/2]
virtual StringVector PageContext::fields () const [virtual]
Return the list of fields.
Implements TemplateStructIntf.
get() [1/2]
TemplateVariant PageContext::get (const QCString & name) const [virtual]
Gets the value for a field name.
Parameters
 in name The name of the field.
Implements TemplateStructIntf.
Definition at line 3379 of file context.cpp.
{
  return p->get(n);
}
References n, and p.
get() [2/2]
virtual TemplateVariant PageContext::get (const QCString & name) const [virtual]
Gets the value for a field name.
Parameters
 in name The name of the field.
Implements TemplateStructIntf.
Member Data Documentation
p
std::unique_ptr< Private > PageContext::p [private]
Definition at line 312 of file context.h.
Referenced by fields(), get(), and TextGeneratorHtml::writeString().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.h
doxygen/src/context.h
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp