MemberInfo Class Reference
#include <membername.h>
Public Member Functions
MemberInfo (const MemberDef *md, Protection p, Specifier v, bool inh)
~MemberInfo ()=default
const MemberDef * memberDef ()
const MemberDef * memberDef () const
Protection prot () const
Specifier virt () const
bool inherited () const
QCString scopePath () const
QCString ambiguityResolutionScope () const
const ClassDef * ambigClass () const
void setAmbiguityResolutionScope (const QCString &s)
void setScopePath (const QCString &s)
void setAmbigClass (const ClassDef *cd)
MemberInfo (const MemberDef *md, Protection p, Specifier v, bool inh)
~MemberInfo ()=default
const MemberDef * memberDef ()
const MemberDef * memberDef () const
Protection prot () const
Specifier virt () const
bool inherited () const
QCString scopePath () const
QCString ambiguityResolutionScope () const
const ClassDef * ambigClass () const
void setAmbiguityResolutionScope (const QCString &s)
void setScopePath (const QCString &s)
void setAmbigClass (const ClassDef *cd)
Private Attributes
const MemberDef * m_memberDef
Protection m_prot
Specifier m_virt
bool m_inherited
QCString m_scopePath
QCString m_ambiguityResolutionScope
const ClassDef * m_ambigClass = 0
Detailed Description
Data associated with a MemberDef in an inheritance relation.
Definition at line 66 of file membername.h.
Constructor & Destructor Documentation
MemberInfo() [1/2]
MemberInfo::MemberInfo (const MemberDef * md, Protection p, Specifier v, bool inh) [inline]
Definition at line 69 of file membername.h.
                                                                      :
          m_memberDef(md), m_prot(p), m_virt(v), m_inherited(inh) {}
 MemberInfo() [1/2]
MemberInfo::~MemberInfo () [default]
MemberInfo() [2/2]
MemberInfo::MemberInfo (const MemberDef * md, Protection p, Specifier v, bool inh) [inline]
Definition at line 69 of file membername.h.
                                                                      :
          m_memberDef(md), m_prot(p), m_virt(v), m_inherited(inh) {}
 MemberInfo() [2/2]
MemberInfo::~MemberInfo () [default]
Member Function Documentation
ambigClass() [1/2]
const ClassDef * MemberInfo::ambigClass () const [inline]
Definition at line 81 of file membername.h.
{ return m_ambigClass; }
References m_ambigClass.
ambigClass() [2/2]
const ClassDef * MemberInfo::ambigClass () const [inline]
Definition at line 81 of file membername.h.
{ return m_ambigClass; }
References m_ambigClass.
ambiguityResolutionScope() [1/2]
QCString MemberInfo::ambiguityResolutionScope () const [inline]
Definition at line 80 of file membername.h.
{ return m_ambiguityResolutionScope; }
References m_ambiguityResolutionScope.
Referenced by MemberInfoContext::Private::ambiguityScope().
ambiguityResolutionScope() [2/2]
QCString MemberInfo::ambiguityResolutionScope () const [inline]
Definition at line 80 of file membername.h.
{ return m_ambiguityResolutionScope; }
References m_ambiguityResolutionScope.
inherited() [1/2]
bool MemberInfo::inherited () const [inline]
Definition at line 78 of file membername.h.
{ return m_inherited; }
References m_inherited.
inherited() [2/2]
bool MemberInfo::inherited () const [inline]
Definition at line 78 of file membername.h.
{ return m_inherited; }
References m_inherited.
memberDef() [1/4]
const MemberDef * MemberInfo::memberDef () [inline]
Definition at line 74 of file membername.h.
{ return m_memberDef; }
References m_memberDef.
Referenced by MemberInfoContext::Private::createMember().
memberDef() [2/4]
const MemberDef * MemberInfo::memberDef () [inline]
Definition at line 74 of file membername.h.
{ return m_memberDef; }
References m_memberDef.
memberDef() [3/4]
const MemberDef * MemberInfo::memberDef () const [inline]
Definition at line 75 of file membername.h.
{ return m_memberDef; }
References m_memberDef.
memberDef() [4/4]
const MemberDef * MemberInfo::memberDef () const [inline]
Definition at line 75 of file membername.h.
{ return m_memberDef; }
References m_memberDef.
prot() [1/2]
Protection MemberInfo::prot () const [inline]
Definition at line 76 of file membername.h.
{ return m_prot; }
References m_prot.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.refType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.compoundRefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberRefType::buildAttributes(), doxmlparser.compound.compoundRefType::buildAttributes(), doxmlparser.compound.refType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.compoundRefType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberRefType::exportAttributes(), doxmlparser.compound.refType::exportAttributes(), doxmlparser.compound.compounddefType::get_prot(), doxmlparser.compound.memberRefType::get_prot(), doxmlparser.compound.compoundRefType::get_prot(), doxmlparser.compound.refType::get_prot(), doxmlparser.compound.memberdefType::get_prot(), doxmlparser.compound.enumvalueType::get_prot(), MemberInfoContext::Private::protection(), doxmlparser.compound.compounddefType::set_prot(), doxmlparser.compound.memberRefType::set_prot(), doxmlparser.compound.compoundRefType::set_prot(), doxmlparser.compound.refType::set_prot(), doxmlparser.compound.memberdefType::set_prot(), and doxmlparser.compound.enumvalueType::set_prot().
prot() [2/2]
Protection MemberInfo::prot () const [inline]
Definition at line 76 of file membername.h.
{ return m_prot; }
References m_prot.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.refType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.compoundRefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberRefType::buildAttributes(), doxmlparser.compound.compoundRefType::buildAttributes(), doxmlparser.compound.refType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.compoundRefType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberRefType::exportAttributes(), doxmlparser.compound.refType::exportAttributes(), doxmlparser.compound.compounddefType::get_prot(), doxmlparser.compound.memberRefType::get_prot(), doxmlparser.compound.compoundRefType::get_prot(), doxmlparser.compound.refType::get_prot(), doxmlparser.compound.memberdefType::get_prot(), doxmlparser.compound.enumvalueType::get_prot(), doxmlparser.compound.compounddefType::set_prot(), doxmlparser.compound.memberRefType::set_prot(), doxmlparser.compound.compoundRefType::set_prot(), doxmlparser.compound.refType::set_prot(), doxmlparser.compound.memberdefType::set_prot(), and doxmlparser.compound.enumvalueType::set_prot().
scopePath() [1/2]
QCString MemberInfo::scopePath () const [inline]
Definition at line 79 of file membername.h.
{ return m_scopePath; }
References m_scopePath.
scopePath() [2/2]
QCString MemberInfo::scopePath () const [inline]
Definition at line 79 of file membername.h.
{ return m_scopePath; }
References m_scopePath.
setAmbigClass() [1/2]
void MemberInfo::setAmbigClass (const ClassDef * cd) [inline]
Definition at line 86 of file membername.h.
{ m_ambigClass = cd; }
References m_ambigClass.
setAmbigClass() [2/2]
void MemberInfo::setAmbigClass (const ClassDef * cd) [inline]
Definition at line 86 of file membername.h.
{ m_ambigClass = cd; }
References m_ambigClass.
setAmbiguityResolutionScope() [1/2]
void MemberInfo::setAmbiguityResolutionScope (const QCString & s) [inline]
Definition at line 84 of file membername.h.
{ m_ambiguityResolutionScope = s; }
References m_ambiguityResolutionScope, and s.
setAmbiguityResolutionScope() [2/2]
void MemberInfo::setAmbiguityResolutionScope (const QCString & s) [inline]
Definition at line 84 of file membername.h.
{ m_ambiguityResolutionScope = s; }
References m_ambiguityResolutionScope, and s.
setScopePath() [1/2]
void MemberInfo::setScopePath (const QCString & s) [inline]
Definition at line 85 of file membername.h.
{ m_scopePath = s; }
References m_scopePath, and s.
setScopePath() [2/2]
void MemberInfo::setScopePath (const QCString & s) [inline]
Definition at line 85 of file membername.h.
{ m_scopePath = s; }
References m_scopePath, and s.
virt() [1/2]
Specifier MemberInfo::virt () const [inline]
Definition at line 77 of file membername.h.
{ return m_virt; }
References m_virt.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.compoundRefType::__init__(), doxmlparser.compound.memberRefType::buildAttributes(), doxmlparser.compound.compoundRefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.compoundRefType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberRefType::exportAttributes(), doxmlparser.compound.memberRefType::get_virt(), doxmlparser.compound.compoundRefType::get_virt(), doxmlparser.compound.memberdefType::get_virt(), doxmlparser.compound.memberRefType::set_virt(), doxmlparser.compound.compoundRefType::set_virt(), doxmlparser.compound.memberdefType::set_virt(), and MemberInfoContext::Private::virtualness().
virt() [2/2]
Specifier MemberInfo::virt () const [inline]
Definition at line 77 of file membername.h.
{ return m_virt; }
References m_virt.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.compoundRefType::__init__(), doxmlparser.compound.memberRefType::buildAttributes(), doxmlparser.compound.compoundRefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.compoundRefType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberRefType::exportAttributes(), doxmlparser.compound.memberRefType::get_virt(), doxmlparser.compound.compoundRefType::get_virt(), doxmlparser.compound.memberdefType::get_virt(), doxmlparser.compound.memberRefType::set_virt(), doxmlparser.compound.compoundRefType::set_virt(), and doxmlparser.compound.memberdefType::set_virt().
Member Data Documentation
m_ambigClass
const ClassDef * MemberInfo::m_ambigClass = 0 [private]
Definition at line 95 of file membername.h.
Referenced by ambigClass(), and setAmbigClass().
m_ambiguityResolutionScope
QCString MemberInfo::m_ambiguityResolutionScope [private]
Definition at line 94 of file membername.h.
Referenced by ambiguityResolutionScope(), and setAmbiguityResolutionScope().
m_inherited
bool MemberInfo::m_inherited [private]
Definition at line 92 of file membername.h.
Referenced by inherited().
m_memberDef
const MemberDef * MemberInfo::m_memberDef [private]
Definition at line 89 of file membername.h.
Referenced by memberDef().
m_prot
Protection MemberInfo::m_prot [private]
Definition at line 90 of file membername.h.
Referenced by prot().
m_scopePath
QCString MemberInfo::m_scopePath [private]
Definition at line 93 of file membername.h.
Referenced by scopePath(), and setScopePath().
m_virt
Specifier MemberInfo::m_virt [private]
Definition at line 91 of file membername.h.
Referenced by virt().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/membername.h
doxygen/src/membername.h