TemplateNodeSet Class Reference
Class representing an 'set' tag in a template.
Classes
struct Mapping
Public Member Functions
TemplateNodeSet (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
~TemplateNodeSet ()
void render (TextStream &, TemplateContext *c)
TemplateNodeSet (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
~TemplateNodeSet ()
void render (TextStream &, TemplateContext *c)
Private Attributes
std::unique_ptr< Mapping > m_mapping
Additional Inherited Members
Detailed Description
Class representing an 'set' tag in a template.
Definition at line 4321 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeSet() [1/2]
TemplateNodeSet::TemplateNodeSet (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 4330 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeSet>(parser,parent,line)
    {
      TRACE(("{TemplateNodeSet(%s)\n",qPrint(data)));
      ExpressionParser expParser(parser,line);
      // data format: name=expression
      int j=data.find('=');
      ExprAstPtr expr = 0;
      if (j>0 && (expr = expParser.parse(data.mid(j+1))))
      {
        m_mapping = std::make_unique<Mapping>(data.left(j),std::move(expr));
      }
      TRACE(("}TemplateNodeSet(%s)\n",qPrint(data)));
    }
References data, m_mapping, ExpressionParser::parse(), qPrint(), and TRACE.
 TemplateNodeSet() [1/2]
TemplateNodeSet::~TemplateNodeSet () [inline]
Definition at line 4344 of file template.cpp.
    {
    }
TemplateNodeSet() [2/2]
TemplateNodeSet::TemplateNodeSet (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 4330 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeSet>(parser,parent,line)
    {
      TRACE(("{TemplateNodeSet(%s)\n",qPrint(data)));
      ExpressionParser expParser(parser,line);
      // data format: name=expression
      int j=data.find('=');
      ExprAstPtr expr = 0;
      if (j>0 && (expr = expParser.parse(data.mid(j+1))))
      {
        m_mapping = std::make_unique<Mapping>(data.left(j),std::move(expr));
      }
      TRACE(("}TemplateNodeSet(%s)\n",qPrint(data)));
    }
References data, m_mapping, ExpressionParser::parse(), qPrint(), and TRACE.
 TemplateNodeSet() [2/2]
TemplateNodeSet::~TemplateNodeSet () [inline]
Definition at line 4344 of file template.cpp.
    {
    }
Member Function Documentation
render() [1/2]
void TemplateNodeSet::render (TextStream & , TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 4347 of file template.cpp.
    {
      TemplateContextImpl *ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      if (m_mapping)
      {
        TemplateVariant value = m_mapping->value->resolve(c);
        ci->set(m_mapping->name,value);
      }
    }
References c, TemplateNodeCreator< TemplateNodeSet >::m_line, m_mapping, TemplateNodeCreator< TemplateNodeSet >::m_templateName, TemplateContextImpl::set(), and TemplateContextImpl::setLocation().
render() [2/2]
void TemplateNodeSet::render (TextStream & , TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 4347 of file template.cpp.
    {
      TemplateContextImpl *ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      if (m_mapping)
      {
        TemplateVariant value = m_mapping->value->resolve(c);
        ci->set(m_mapping->name,value);
      }
    }
References c, TemplateNodeCreator< TemplateNodeSet >::m_line, m_mapping, TemplateNodeCreator< TemplateNodeSet >::m_templateName, TemplateContextImpl::set(), and TemplateContextImpl::setLocation().
Member Data Documentation
m_mapping
std::unique_ptr< Mapping > TemplateNodeSet::m_mapping [private]
Definition at line 4359 of file template.cpp.
Referenced by render(), and TemplateNodeSet().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp