DefinitionMixin< Base > Class Template Reference
#include <definitionimpl.h>
Public Member Functions
DefinitionMixin (const QCString &defFileName, int defLine, int defColumn, const QCString &name, const char *b=0, const char *d=0, bool isSymbol=TRUE)
virtual ~DefinitionMixin ()=default
virtual bool isAlias () const
virtual QCString name () const
virtual bool isAnonymous () const
virtual QCString localName () const
virtual QCString qualifiedName () const
virtual QCString symbolName () const
virtual QCString getSourceFileBase () const
virtual QCString getSourceAnchor () const
virtual QCString documentation () const
virtual int docLine () const
virtual QCString docFile () const
virtual QCString briefDescription (bool abbreviate=FALSE) const
virtual QCString briefDescriptionAsTooltip () const
virtual int briefLine () const
virtual QCString inbodyDocumentation () const
virtual QCString inbodyFile () const
virtual int inbodyLine () const
virtual QCString briefFile () const
virtual QCString getDefFileName () const
virtual QCString getDefFileExtension () const
virtual int getDefLine () const
virtual int getDefColumn () const
virtual bool hasDocumentation () const
virtual bool hasUserDocumentation () const
virtual bool isVisibleInProject () const
virtual bool isVisible () const
virtual bool isHidden () const
virtual bool isArtificial () const
virtual QCString getReference () const
virtual bool isReference () const
virtual QCString externalReference (const QCString &relPath) const
virtual int getStartDefLine () const
virtual int getStartBodyLine () const
virtual int getEndBodyLine () const
virtual const FileDef * getBodyDef () const
virtual SrcLangExt getLanguage () const
virtual const GroupList & partOfGroups () const
virtual bool isLinkableViaGroup () const
virtual const RefItemVector & xrefListItems () const
virtual const Definition * findInnerCompound (const QCString &name) const
virtual Definition * getOuterScope () const
virtual const MemberVector & getReferencesMembers () const
virtual const MemberVector & getReferencedByMembers () const
virtual bool hasSections () const
virtual bool hasSources () const
virtual bool hasBriefDescription () const
virtual QCString id () const
virtual const SectionRefs & getSectionRefs () const
virtual void setName (const QCString &name)
virtual void setId (const QCString &name)
virtual void setDefFile (const QCString &df, int defLine, int defColumn)
virtual void setDocumentation (const QCString &doc, const QCString &docFile, int docLine, bool stripWhiteSpace=TRUE)
virtual void setBriefDescription (const QCString &brief, const QCString &briefFile, int briefLine)
virtual void setInbodyDocumentation (const QCString &doc, const QCString &docFile, int docLine)
virtual void setReference (const QCString &r)
virtual void addSectionsToDefinition (const std::vector< const SectionInfo * > &anchorList)
virtual void setBodySegment (int defLine, int bls, int ble)
virtual void setBodyDef (const FileDef *fd)
virtual void addSourceReferencedBy (const MemberDef *md)
virtual void addSourceReferences (const MemberDef *md)
virtual void setRefItems (const RefItemVector &sli)
virtual void mergeRefItems (Definition *def)
virtual void mergeReferences (const Definition *other)
virtual void mergeReferencedBy (const Definition *other)
virtual void addInnerCompound (const Definition *def)
virtual void setOuterScope (Definition *def)
virtual void setHidden (bool b)
virtual void setArtificial (bool b)
virtual void setLanguage (SrcLangExt lang)
virtual void writeSourceDef (OutputList &ol, const QCString &scopeName) const
virtual void writeInlineCode (OutputList &ol, const QCString &scopeName) const
virtual bool hasSourceRefs () const
virtual bool hasSourceReffedBy () const
virtual void writeSourceRefs (OutputList &ol, const QCString &scopeName) const
virtual void writeSourceReffedBy (OutputList &ol, const QCString &scopeName) const
virtual void makePartOfGroup (const GroupDef *gd)
virtual void writeNavigationPath (OutputList &ol) const
virtual QCString navigationPathAsString () const
virtual void writeQuickMemberLinks (OutputList &ol, const MemberDef *md) const
virtual void writeSummaryLinks (OutputList &ol) const
virtual QCString pathFragment () const
virtual void writeDocAnchorsToTagFile (TextStream &fs) const
virtual void setLocalName (const QCString &name)
virtual void addSectionsToIndex ()
virtual void writeToc (OutputList &ol, const LocalToc &lt) const
virtual void computeTooltip ()
virtual void _setSymbolName (const QCString &name)
virtual QCString _symbolName () const
DefinitionMixin (const QCString &defFileName, int defLine, int defColumn, const QCString &name, const char *b=0, const char *d=0, bool isSymbol=TRUE)
virtual ~DefinitionMixin ()=default
virtual bool isAlias () const
virtual QCString name () const
virtual bool isAnonymous () const
virtual QCString localName () const
virtual QCString qualifiedName () const
virtual QCString symbolName () const
virtual QCString getSourceFileBase () const
virtual QCString getSourceAnchor () const
virtual QCString documentation () const
virtual int docLine () const
virtual QCString docFile () const
virtual QCString briefDescription (bool abbreviate=FALSE) const
virtual QCString briefDescriptionAsTooltip () const
virtual int briefLine () const
virtual QCString inbodyDocumentation () const
virtual QCString inbodyFile () const
virtual int inbodyLine () const
virtual QCString briefFile () const
virtual QCString getDefFileName () const
virtual QCString getDefFileExtension () const
virtual int getDefLine () const
virtual int getDefColumn () const
virtual bool hasDocumentation () const
virtual bool hasUserDocumentation () const
virtual bool isVisibleInProject () const
virtual bool isVisible () const
virtual bool isHidden () const
virtual bool isArtificial () const
virtual QCString getReference () const
virtual bool isReference () const
virtual QCString externalReference (const QCString &relPath) const
virtual int getStartDefLine () const
virtual int getStartBodyLine () const
virtual int getEndBodyLine () const
virtual const FileDef * getBodyDef () const
virtual SrcLangExt getLanguage () const
virtual const GroupList & partOfGroups () const
virtual bool isLinkableViaGroup () const
virtual const RefItemVector & xrefListItems () const
virtual const Definition * findInnerCompound (const QCString &name) const
virtual Definition * getOuterScope () const
virtual const MemberVector & getReferencesMembers () const
virtual const MemberVector & getReferencedByMembers () const
virtual bool hasSections () const
virtual bool hasSources () const
virtual bool hasBriefDescription () const
virtual QCString id () const
virtual const SectionRefs & getSectionRefs () const
virtual void setName (const QCString &name)
virtual void setId (const QCString &name)
virtual void setDefFile (const QCString &df, int defLine, int defColumn)
virtual void setDocumentation (const QCString &doc, const QCString &docFile, int docLine, bool stripWhiteSpace=TRUE)
virtual void setBriefDescription (const QCString &brief, const QCString &briefFile, int briefLine)
virtual void setInbodyDocumentation (const QCString &doc, const QCString &docFile, int docLine)
virtual void setReference (const QCString &r)
virtual void addSectionsToDefinition (const std::vector< const SectionInfo * > &anchorList)
virtual void setBodySegment (int defLine, int bls, int ble)
virtual void setBodyDef (const FileDef *fd)
virtual void addSourceReferencedBy (const MemberDef *md)
virtual void addSourceReferences (const MemberDef *md)
virtual void setRefItems (const RefItemVector &sli)
virtual void mergeRefItems (Definition *def)
virtual void mergeReferences (const Definition *other)
virtual void mergeReferencedBy (const Definition *other)
virtual void addInnerCompound (const Definition *def)
virtual void setOuterScope (Definition *def)
virtual void setHidden (bool b)
virtual void setArtificial (bool b)
virtual void setLanguage (SrcLangExt lang)
virtual void writeSourceDef (OutputList &ol, const QCString &scopeName) const
virtual void writeInlineCode (OutputList &ol, const QCString &scopeName) const
virtual bool hasSourceRefs () const
virtual bool hasSourceReffedBy () const
virtual void writeSourceRefs (OutputList &ol, const QCString &scopeName) const
virtual void writeSourceReffedBy (OutputList &ol, const QCString &scopeName) const
virtual void makePartOfGroup (const GroupDef *gd)
virtual void writeNavigationPath (OutputList &ol) const
virtual QCString navigationPathAsString () const
virtual void writeQuickMemberLinks (OutputList &ol, const MemberDef *md) const
virtual void writeSummaryLinks (OutputList &ol) const
virtual QCString pathFragment () const
virtual void writeDocAnchorsToTagFile (TextStream &fs) const
virtual void setLocalName (const QCString &name)
virtual void addSectionsToIndex ()
virtual void writeToc (OutputList &ol, const LocalToc &lt) const
virtual void computeTooltip ()
virtual void _setSymbolName (const QCString &name)
virtual QCString _symbolName () const
Protected Member Functions
DefinitionMixin (const DefinitionMixin &def)=default
DefinitionMixin (const DefinitionMixin &def)=default
Private Member Functions
virtual Definition * toDefinition_ ()
virtual DefinitionMutable * toDefinitionMutable_ ()
virtual const DefinitionImpl * toDefinitionImpl_ () const
virtual Definition * toDefinition_ ()
virtual DefinitionMutable * toDefinitionMutable_ ()
virtual const DefinitionImpl * toDefinitionImpl_ () const
Private Attributes
DefinitionImpl m_impl
Detailed Description
template<class Base>
class DefinitionMixin< Base >
Definition at line 142 of file definitionimpl.h.
Constructor & Destructor Documentation
DefinitionMixin() [1/4]
template<class Base >
DefinitionMixin< Base >::DefinitionMixin (const QCString & defFileName, int defLine, int defColumn, const QCString & name, const char * b = 0, const char * d = 0, bool isSymbol = TRUE) [inline]
Create a new definition
Definition at line 146 of file definitionimpl.h.
                            : m_impl(this,defFileName,defLine,defColumn,name,b,d,isSymbol) {}
 DefinitionMixin() [1/2]
template<class Base >
virtual DefinitionMixin< Base >::~DefinitionMixin () [virtual], [default]
DefinitionMixin() [2/4]
template<class Base >
DefinitionMixin< Base >::DefinitionMixin (const DefinitionMixin< Base > & def) [protected], [default]
DefinitionMixin() [3/4]
template<class Base >
DefinitionMixin< Base >::DefinitionMixin (const QCString & defFileName, int defLine, int defColumn, const QCString & name, const char * b = 0, const char * d = 0, bool isSymbol = TRUE) [inline]
Create a new definition
Definition at line 146 of file definitionimpl.h.
                            : m_impl(this,defFileName,defLine,defColumn,name,b,d,isSymbol) {}
 DefinitionMixin() [2/2]
template<class Base >
virtual DefinitionMixin< Base >::~DefinitionMixin () [virtual], [default]
DefinitionMixin() [4/4]
template<class Base >
DefinitionMixin< Base >::DefinitionMixin (const DefinitionMixin< Base > & def) [protected], [default]
Member Function Documentation
_setSymbolName() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::_setSymbolName (const QCString & name) [inline], [virtual]
Definition at line 278 of file definitionimpl.h.
    { m_impl._setSymbolName(name); }
References DefinitionImpl::_setSymbolName(), DefinitionMixin< Base >::m_impl, and DefinitionMixin< Base >::name().
_setSymbolName() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::_setSymbolName (const QCString & name) [inline], [virtual]
Definition at line 278 of file definitionimpl.h.
    { m_impl._setSymbolName(name); }
References DefinitionImpl::_setSymbolName(), DefinitionMixin< Base >::m_impl, and DefinitionMixin< Base >::name().
_symbolName() [1/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::_symbolName () const [inline], [virtual]
Definition at line 280 of file definitionimpl.h.
    { return m_impl._symbolName(); }
References DefinitionImpl::_symbolName(), and DefinitionMixin< Base >::m_impl.
_symbolName() [2/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::_symbolName () const [inline], [virtual]
Definition at line 280 of file definitionimpl.h.
    { return m_impl._symbolName(); }
References DefinitionImpl::_symbolName(), and DefinitionMixin< Base >::m_impl.
addInnerCompound() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::addInnerCompound (const Definition * def) [inline], [virtual]
Reimplemented in ClassDefImpl, NamespaceDefImpl, PageDefImpl, ClassDefImpl, NamespaceDefImpl, and PageDefImpl.
Definition at line 234 of file definitionimpl.h.
    { m_impl.addInnerCompound(def); }
References DefinitionImpl::addInnerCompound(), and DefinitionMixin< Base >::m_impl.
addInnerCompound() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::addInnerCompound (const Definition * def) [inline], [virtual]
Reimplemented in ClassDefImpl, NamespaceDefImpl, PageDefImpl, ClassDefImpl, NamespaceDefImpl, and PageDefImpl.
Definition at line 234 of file definitionimpl.h.
    { m_impl.addInnerCompound(def); }
References DefinitionImpl::addInnerCompound(), and DefinitionMixin< Base >::m_impl.
addSectionsToDefinition() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::addSectionsToDefinition (const std::vector< const SectionInfo * > & anchorList) [inline], [virtual]
Definition at line 216 of file definitionimpl.h.
    { m_impl.addSectionsToDefinition(anchorList); }
References DefinitionImpl::addSectionsToDefinition(), and DefinitionMixin< Base >::m_impl.
addSectionsToDefinition() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::addSectionsToDefinition (const std::vector< const SectionInfo * > & anchorList) [inline], [virtual]
Definition at line 216 of file definitionimpl.h.
    { m_impl.addSectionsToDefinition(anchorList); }
References DefinitionImpl::addSectionsToDefinition(), and DefinitionMixin< Base >::m_impl.
addSectionsToIndex() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::addSectionsToIndex () [inline], [virtual]
Definition at line 272 of file definitionimpl.h.
    { m_impl.addSectionsToIndex(); }
References DefinitionImpl::addSectionsToIndex(), and DefinitionMixin< Base >::m_impl.
addSectionsToIndex() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::addSectionsToIndex () [inline], [virtual]
Definition at line 272 of file definitionimpl.h.
    { m_impl.addSectionsToIndex(); }
References DefinitionImpl::addSectionsToIndex(), and DefinitionMixin< Base >::m_impl.
addSourceReferencedBy() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::addSourceReferencedBy (const MemberDef * md) [inline], [virtual]
Definition at line 222 of file definitionimpl.h.
    { m_impl.addSourceReferencedBy(md); }
References DefinitionImpl::addSourceReferencedBy(), and DefinitionMixin< Base >::m_impl.
addSourceReferencedBy() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::addSourceReferencedBy (const MemberDef * md) [inline], [virtual]
Definition at line 222 of file definitionimpl.h.
    { m_impl.addSourceReferencedBy(md); }
References DefinitionImpl::addSourceReferencedBy(), and DefinitionMixin< Base >::m_impl.
addSourceReferences() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::addSourceReferences (const MemberDef * md) [inline], [virtual]
Definition at line 224 of file definitionimpl.h.
    { m_impl.addSourceReferences(md); }
References DefinitionImpl::addSourceReferences(), and DefinitionMixin< Base >::m_impl.
addSourceReferences() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::addSourceReferences (const MemberDef * md) [inline], [virtual]
Definition at line 224 of file definitionimpl.h.
    { m_impl.addSourceReferences(md); }
References DefinitionImpl::addSourceReferences(), and DefinitionMixin< Base >::m_impl.
briefDescription() [1/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::briefDescription (bool abbreviate = FALSE) const [inline], [virtual]
Reimplemented in MemberDefImpl, and MemberDefImpl.
Definition at line 165 of file definitionimpl.h.
{ return m_impl.briefDescription(abbreviate); }
References abbreviate(), DefinitionImpl::briefDescription(), and DefinitionMixin< Base >::m_impl.
Referenced by MemberDefImpl::briefDescription().
briefDescription() [2/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::briefDescription (bool abbreviate = FALSE) const [inline], [virtual]
Reimplemented in MemberDefImpl, and MemberDefImpl.
Definition at line 165 of file definitionimpl.h.
{ return m_impl.briefDescription(abbreviate); }
References abbreviate(), DefinitionImpl::briefDescription(), and DefinitionMixin< Base >::m_impl.
briefDescriptionAsTooltip() [1/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::briefDescriptionAsTooltip () const [inline], [virtual]
Definition at line 166 of file definitionimpl.h.
{ return m_impl.briefDescriptionAsTooltip(); }
References DefinitionImpl::briefDescriptionAsTooltip(), and DefinitionMixin< Base >::m_impl.
briefDescriptionAsTooltip() [2/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::briefDescriptionAsTooltip () const [inline], [virtual]
Definition at line 166 of file definitionimpl.h.
{ return m_impl.briefDescriptionAsTooltip(); }
References DefinitionImpl::briefDescriptionAsTooltip(), and DefinitionMixin< Base >::m_impl.
briefFile() [1/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::briefFile () const [inline], [virtual]
Definition at line 171 of file definitionimpl.h.
{ return m_impl.briefFile(); }
References DefinitionImpl::briefFile(), and DefinitionMixin< Base >::m_impl.
Referenced by DefinitionMixin< Base >::setBriefDescription().
briefFile() [2/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::briefFile () const [inline], [virtual]
Definition at line 171 of file definitionimpl.h.
{ return m_impl.briefFile(); }
References DefinitionImpl::briefFile(), and DefinitionMixin< Base >::m_impl.
briefLine() [1/2]
template<class Base >
virtual int DefinitionMixin< Base >::briefLine () const [inline], [virtual]
Definition at line 167 of file definitionimpl.h.
{ return m_impl.briefLine(); }
References DefinitionImpl::briefLine(), and DefinitionMixin< Base >::m_impl.
Referenced by DefinitionMixin< Base >::setBriefDescription().
briefLine() [2/2]
template<class Base >
virtual int DefinitionMixin< Base >::briefLine () const [inline], [virtual]
Definition at line 167 of file definitionimpl.h.
{ return m_impl.briefLine(); }
References DefinitionImpl::briefLine(), and DefinitionMixin< Base >::m_impl.
computeTooltip() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::computeTooltip () [inline], [virtual]
Definition at line 276 of file definitionimpl.h.
    { m_impl.computeTooltip(); }
References DefinitionImpl::computeTooltip(), and DefinitionMixin< Base >::m_impl.
computeTooltip() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::computeTooltip () [inline], [virtual]
Definition at line 276 of file definitionimpl.h.
    { m_impl.computeTooltip(); }
References DefinitionImpl::computeTooltip(), and DefinitionMixin< Base >::m_impl.
docFile() [1/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::docFile () const [inline], [virtual]
Definition at line 164 of file definitionimpl.h.
{ return m_impl.docFile(); }
References DefinitionImpl::docFile(), and DefinitionMixin< Base >::m_impl.
Referenced by DefinitionMixin< Base >::setDocumentation(), and DefinitionMixin< Base >::setInbodyDocumentation().
docFile() [2/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::docFile () const [inline], [virtual]
Definition at line 164 of file definitionimpl.h.
{ return m_impl.docFile(); }
References DefinitionImpl::docFile(), and DefinitionMixin< Base >::m_impl.
docLine() [1/2]
template<class Base >
virtual int DefinitionMixin< Base >::docLine () const [inline], [virtual]
Definition at line 163 of file definitionimpl.h.
{ return m_impl.docLine(); }
References DefinitionImpl::docLine(), and DefinitionMixin< Base >::m_impl.
Referenced by DefinitionMixin< Base >::setDocumentation(), and DefinitionMixin< Base >::setInbodyDocumentation().
docLine() [2/2]
template<class Base >
virtual int DefinitionMixin< Base >::docLine () const [inline], [virtual]
Definition at line 163 of file definitionimpl.h.
{ return m_impl.docLine(); }
References DefinitionImpl::docLine(), and DefinitionMixin< Base >::m_impl.
documentation() [1/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::documentation () const [inline], [virtual]
Reimplemented in MemberDefImpl, and MemberDefImpl.
Definition at line 162 of file definitionimpl.h.
{ return m_impl.documentation(); }
References DefinitionImpl::documentation(), and DefinitionMixin< Base >::m_impl.
Referenced by MemberDefImpl::documentation().
documentation() [2/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::documentation () const [inline], [virtual]
Reimplemented in MemberDefImpl, and MemberDefImpl.
Definition at line 162 of file definitionimpl.h.
{ return m_impl.documentation(); }
References DefinitionImpl::documentation(), and DefinitionMixin< Base >::m_impl.
externalReference() [1/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::externalReference (const QCString & relPath) const [inline], [virtual]
Definition at line 184 of file definitionimpl.h.
{ return m_impl.externalReference(relPath); }
References DefinitionImpl::externalReference(), and DefinitionMixin< Base >::m_impl.
externalReference() [2/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::externalReference (const QCString & relPath) const [inline], [virtual]
Definition at line 184 of file definitionimpl.h.
{ return m_impl.externalReference(relPath); }
References DefinitionImpl::externalReference(), and DefinitionMixin< Base >::m_impl.
findInnerCompound() [1/2]
template<class Base >
virtual const Definition * DefinitionMixin< Base >::findInnerCompound (const QCString & name) const [inline], [virtual]
Reimplemented in ClassDefImpl, NamespaceDefImpl, ClassDefImpl, and NamespaceDefImpl.
Definition at line 193 of file definitionimpl.h.
{ return m_impl.findInnerCompound(name); }
References DefinitionImpl::findInnerCompound(), DefinitionMixin< Base >::m_impl, and DefinitionMixin< Base >::name().
findInnerCompound() [2/2]
template<class Base >
virtual const Definition * DefinitionMixin< Base >::findInnerCompound (const QCString & name) const [inline], [virtual]
Reimplemented in ClassDefImpl, NamespaceDefImpl, ClassDefImpl, and NamespaceDefImpl.
Definition at line 193 of file definitionimpl.h.
{ return m_impl.findInnerCompound(name); }
References DefinitionImpl::findInnerCompound(), DefinitionMixin< Base >::m_impl, and DefinitionMixin< Base >::name().
getBodyDef() [1/2]
template<class Base >
virtual const FileDef * DefinitionMixin< Base >::getBodyDef () const [inline], [virtual]
Definition at line 188 of file definitionimpl.h.
{ return m_impl.getBodyDef(); }
References DefinitionImpl::getBodyDef(), and DefinitionMixin< Base >::m_impl.
getBodyDef() [2/2]
template<class Base >
virtual const FileDef * DefinitionMixin< Base >::getBodyDef () const [inline], [virtual]
Definition at line 188 of file definitionimpl.h.
{ return m_impl.getBodyDef(); }
References DefinitionImpl::getBodyDef(), and DefinitionMixin< Base >::m_impl.
getDefColumn() [1/2]
template<class Base >
virtual int DefinitionMixin< Base >::getDefColumn () const [inline], [virtual]
Definition at line 175 of file definitionimpl.h.
{ return m_impl.getDefColumn(); }
References DefinitionImpl::getDefColumn(), and DefinitionMixin< Base >::m_impl.
getDefColumn() [2/2]
template<class Base >
virtual int DefinitionMixin< Base >::getDefColumn () const [inline], [virtual]
Definition at line 175 of file definitionimpl.h.
{ return m_impl.getDefColumn(); }
References DefinitionImpl::getDefColumn(), and DefinitionMixin< Base >::m_impl.
getDefFileExtension() [1/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::getDefFileExtension () const [inline], [virtual]
Definition at line 173 of file definitionimpl.h.
{ return m_impl.getDefFileExtension(); }
References DefinitionImpl::getDefFileExtension(), and DefinitionMixin< Base >::m_impl.
getDefFileExtension() [2/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::getDefFileExtension () const [inline], [virtual]
Definition at line 173 of file definitionimpl.h.
{ return m_impl.getDefFileExtension(); }
References DefinitionImpl::getDefFileExtension(), and DefinitionMixin< Base >::m_impl.
getDefFileName() [1/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::getDefFileName () const [inline], [virtual]
Definition at line 172 of file definitionimpl.h.
{ return m_impl.getDefFileName(); }
References DefinitionImpl::getDefFileName(), and DefinitionMixin< Base >::m_impl.
getDefFileName() [2/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::getDefFileName () const [inline], [virtual]
Definition at line 172 of file definitionimpl.h.
{ return m_impl.getDefFileName(); }
References DefinitionImpl::getDefFileName(), and DefinitionMixin< Base >::m_impl.
getDefLine() [1/2]
template<class Base >
virtual int DefinitionMixin< Base >::getDefLine () const [inline], [virtual]
Definition at line 174 of file definitionimpl.h.
{ return m_impl.getDefLine(); }
References DefinitionImpl::getDefLine(), and DefinitionMixin< Base >::m_impl.
getDefLine() [2/2]
template<class Base >
virtual int DefinitionMixin< Base >::getDefLine () const [inline], [virtual]
Definition at line 174 of file definitionimpl.h.
{ return m_impl.getDefLine(); }
References DefinitionImpl::getDefLine(), and DefinitionMixin< Base >::m_impl.
getEndBodyLine() [1/2]
template<class Base >
virtual int DefinitionMixin< Base >::getEndBodyLine () const [inline], [virtual]
Definition at line 187 of file definitionimpl.h.
{ return m_impl.getEndBodyLine(); }
References DefinitionImpl::getEndBodyLine(), and DefinitionMixin< Base >::m_impl.
getEndBodyLine() [2/2]
template<class Base >
virtual int DefinitionMixin< Base >::getEndBodyLine () const [inline], [virtual]
Definition at line 187 of file definitionimpl.h.
{ return m_impl.getEndBodyLine(); }
References DefinitionImpl::getEndBodyLine(), and DefinitionMixin< Base >::m_impl.
getLanguage() [1/2]
template<class Base >
virtual SrcLangExt DefinitionMixin< Base >::getLanguage () const [inline], [virtual]
Definition at line 189 of file definitionimpl.h.
{ return m_impl.getLanguage(); }
References DefinitionImpl::getLanguage(), and DefinitionMixin< Base >::m_impl.
getLanguage() [2/2]
template<class Base >
virtual SrcLangExt DefinitionMixin< Base >::getLanguage () const [inline], [virtual]
Definition at line 189 of file definitionimpl.h.
{ return m_impl.getLanguage(); }
References DefinitionImpl::getLanguage(), and DefinitionMixin< Base >::m_impl.
getOuterScope() [1/2]
template<class Base >
virtual Definition * DefinitionMixin< Base >::getOuterScope () const [inline], [virtual]
Definition at line 194 of file definitionimpl.h.
{ return m_impl.getOuterScope(); }
References DefinitionImpl::getOuterScope(), and DefinitionMixin< Base >::m_impl.
getOuterScope() [2/2]
template<class Base >
virtual Definition * DefinitionMixin< Base >::getOuterScope () const [inline], [virtual]
Definition at line 194 of file definitionimpl.h.
{ return m_impl.getOuterScope(); }
References DefinitionImpl::getOuterScope(), and DefinitionMixin< Base >::m_impl.
getReference() [1/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::getReference () const [inline], [virtual]
Reimplemented in ClassDefImpl, MemberDefImpl, ClassDefImpl, and MemberDefImpl.
Definition at line 182 of file definitionimpl.h.
{ return m_impl.getReference(); }
References DefinitionImpl::getReference(), and DefinitionMixin< Base >::m_impl.
Referenced by ClassDefImpl::getReference(), and MemberDefImpl::getReference().
getReference() [2/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::getReference () const [inline], [virtual]
Reimplemented in ClassDefImpl, MemberDefImpl, ClassDefImpl, and MemberDefImpl.
Definition at line 182 of file definitionimpl.h.
{ return m_impl.getReference(); }
References DefinitionImpl::getReference(), and DefinitionMixin< Base >::m_impl.
getReferencedByMembers() [1/2]
template<class Base >
virtual const MemberVector & DefinitionMixin< Base >::getReferencedByMembers () const [inline], [virtual]
Definition at line 196 of file definitionimpl.h.
{ return m_impl.getReferencedByMembers(); }
References DefinitionImpl::getReferencedByMembers(), and DefinitionMixin< Base >::m_impl.
getReferencedByMembers() [2/2]
template<class Base >
virtual const MemberVector & DefinitionMixin< Base >::getReferencedByMembers () const [inline], [virtual]
Definition at line 196 of file definitionimpl.h.
{ return m_impl.getReferencedByMembers(); }
References DefinitionImpl::getReferencedByMembers(), and DefinitionMixin< Base >::m_impl.
getReferencesMembers() [1/2]
template<class Base >
virtual const MemberVector & DefinitionMixin< Base >::getReferencesMembers () const [inline], [virtual]
Definition at line 195 of file definitionimpl.h.
{ return m_impl.getReferencesMembers(); }
References DefinitionImpl::getReferencesMembers(), and DefinitionMixin< Base >::m_impl.
getReferencesMembers() [2/2]
template<class Base >
virtual const MemberVector & DefinitionMixin< Base >::getReferencesMembers () const [inline], [virtual]
Definition at line 195 of file definitionimpl.h.
{ return m_impl.getReferencesMembers(); }
References DefinitionImpl::getReferencesMembers(), and DefinitionMixin< Base >::m_impl.
getSectionRefs() [1/2]
template<class Base >
virtual const SectionRefs & DefinitionMixin< Base >::getSectionRefs () const [inline], [virtual]
Definition at line 201 of file definitionimpl.h.
{ return m_impl.getSectionRefs(); }
References DefinitionImpl::getSectionRefs(), and DefinitionMixin< Base >::m_impl.
getSectionRefs() [2/2]
template<class Base >
virtual const SectionRefs & DefinitionMixin< Base >::getSectionRefs () const [inline], [virtual]
Definition at line 201 of file definitionimpl.h.
{ return m_impl.getSectionRefs(); }
References DefinitionImpl::getSectionRefs(), and DefinitionMixin< Base >::m_impl.
getSourceAnchor() [1/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::getSourceAnchor () const [inline], [virtual]
Definition at line 161 of file definitionimpl.h.
{ return m_impl.getSourceAnchor(); }
References DefinitionImpl::getSourceAnchor(), and DefinitionMixin< Base >::m_impl.
getSourceAnchor() [2/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::getSourceAnchor () const [inline], [virtual]
Definition at line 161 of file definitionimpl.h.
{ return m_impl.getSourceAnchor(); }
References DefinitionImpl::getSourceAnchor(), and DefinitionMixin< Base >::m_impl.
getSourceFileBase() [1/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::getSourceFileBase () const [inline], [virtual]
Reimplemented in ClassDefImpl, FileDefImpl, ClassDefImpl, and FileDefImpl.
Definition at line 160 of file definitionimpl.h.
{ return m_impl.getSourceFileBase(); }
References DefinitionImpl::getSourceFileBase(), and DefinitionMixin< Base >::m_impl.
Referenced by ClassDefImpl::getSourceFileBase().
getSourceFileBase() [2/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::getSourceFileBase () const [inline], [virtual]
Reimplemented in ClassDefImpl, FileDefImpl, ClassDefImpl, and FileDefImpl.
Definition at line 160 of file definitionimpl.h.
{ return m_impl.getSourceFileBase(); }
References DefinitionImpl::getSourceFileBase(), and DefinitionMixin< Base >::m_impl.
getStartBodyLine() [1/2]
template<class Base >
virtual int DefinitionMixin< Base >::getStartBodyLine () const [inline], [virtual]
Definition at line 186 of file definitionimpl.h.
{ return m_impl.getStartBodyLine(); }
References DefinitionImpl::getStartBodyLine(), and DefinitionMixin< Base >::m_impl.
getStartBodyLine() [2/2]
template<class Base >
virtual int DefinitionMixin< Base >::getStartBodyLine () const [inline], [virtual]
Definition at line 186 of file definitionimpl.h.
{ return m_impl.getStartBodyLine(); }
References DefinitionImpl::getStartBodyLine(), and DefinitionMixin< Base >::m_impl.
getStartDefLine() [1/2]
template<class Base >
virtual int DefinitionMixin< Base >::getStartDefLine () const [inline], [virtual]
Definition at line 185 of file definitionimpl.h.
{ return m_impl.getStartDefLine(); }
References DefinitionImpl::getStartDefLine(), and DefinitionMixin< Base >::m_impl.
getStartDefLine() [2/2]
template<class Base >
virtual int DefinitionMixin< Base >::getStartDefLine () const [inline], [virtual]
Definition at line 185 of file definitionimpl.h.
{ return m_impl.getStartDefLine(); }
References DefinitionImpl::getStartDefLine(), and DefinitionMixin< Base >::m_impl.
hasBriefDescription() [1/2]
template<class Base >
virtual bool DefinitionMixin< Base >::hasBriefDescription () const [inline], [virtual]
Definition at line 199 of file definitionimpl.h.
{ return m_impl.hasBriefDescription(); }
References DefinitionImpl::hasBriefDescription(), and DefinitionMixin< Base >::m_impl.
hasBriefDescription() [2/2]
template<class Base >
virtual bool DefinitionMixin< Base >::hasBriefDescription () const [inline], [virtual]
Definition at line 199 of file definitionimpl.h.
{ return m_impl.hasBriefDescription(); }
References DefinitionImpl::hasBriefDescription(), and DefinitionMixin< Base >::m_impl.
hasDocumentation() [1/2]
template<class Base >
virtual bool DefinitionMixin< Base >::hasDocumentation () const [inline], [virtual]
Reimplemented in ClassDefImpl, MemberDefImpl, ClassDefImpl, and MemberDefImpl.
Definition at line 176 of file definitionimpl.h.
{ return m_impl.hasDocumentation(); }
References DefinitionImpl::hasDocumentation(), and DefinitionMixin< Base >::m_impl.
Referenced by ClassDefImpl::hasDocumentation(), and MemberDefImpl::hasDocumentation().
hasDocumentation() [2/2]
template<class Base >
virtual bool DefinitionMixin< Base >::hasDocumentation () const [inline], [virtual]
Reimplemented in ClassDefImpl, MemberDefImpl, ClassDefImpl, and MemberDefImpl.
Definition at line 176 of file definitionimpl.h.
{ return m_impl.hasDocumentation(); }
References DefinitionImpl::hasDocumentation(), and DefinitionMixin< Base >::m_impl.
hasSections() [1/2]
template<class Base >
virtual bool DefinitionMixin< Base >::hasSections () const [inline], [virtual]
Definition at line 197 of file definitionimpl.h.
{ return m_impl.hasSections(); }
References DefinitionImpl::hasSections(), and DefinitionMixin< Base >::m_impl.
hasSections() [2/2]
template<class Base >
virtual bool DefinitionMixin< Base >::hasSections () const [inline], [virtual]
Definition at line 197 of file definitionimpl.h.
{ return m_impl.hasSections(); }
References DefinitionImpl::hasSections(), and DefinitionMixin< Base >::m_impl.
hasSourceReffedBy() [1/2]
template<class Base >
virtual bool DefinitionMixin< Base >::hasSourceReffedBy () const [inline], [virtual]
Definition at line 250 of file definitionimpl.h.
    { return m_impl.hasSourceReffedBy(); }
References DefinitionImpl::hasSourceReffedBy(), and DefinitionMixin< Base >::m_impl.
hasSourceReffedBy() [2/2]
template<class Base >
virtual bool DefinitionMixin< Base >::hasSourceReffedBy () const [inline], [virtual]
Definition at line 250 of file definitionimpl.h.
    { return m_impl.hasSourceReffedBy(); }
References DefinitionImpl::hasSourceReffedBy(), and DefinitionMixin< Base >::m_impl.
hasSourceRefs() [1/2]
template<class Base >
virtual bool DefinitionMixin< Base >::hasSourceRefs () const [inline], [virtual]
Definition at line 248 of file definitionimpl.h.
    { return m_impl.hasSourceRefs(); }
References DefinitionImpl::hasSourceRefs(), and DefinitionMixin< Base >::m_impl.
hasSourceRefs() [2/2]
template<class Base >
virtual bool DefinitionMixin< Base >::hasSourceRefs () const [inline], [virtual]
Definition at line 248 of file definitionimpl.h.
    { return m_impl.hasSourceRefs(); }
References DefinitionImpl::hasSourceRefs(), and DefinitionMixin< Base >::m_impl.
hasSources() [1/2]
template<class Base >
virtual bool DefinitionMixin< Base >::hasSources () const [inline], [virtual]
Definition at line 198 of file definitionimpl.h.
{ return m_impl.hasSources(); }
References DefinitionImpl::hasSources(), and DefinitionMixin< Base >::m_impl.
hasSources() [2/2]
template<class Base >
virtual bool DefinitionMixin< Base >::hasSources () const [inline], [virtual]
Definition at line 198 of file definitionimpl.h.
{ return m_impl.hasSources(); }
References DefinitionImpl::hasSources(), and DefinitionMixin< Base >::m_impl.
hasUserDocumentation() [1/2]
template<class Base >
virtual bool DefinitionMixin< Base >::hasUserDocumentation () const [inline], [virtual]
Definition at line 177 of file definitionimpl.h.
{ return m_impl.hasUserDocumentation(); }
References DefinitionImpl::hasUserDocumentation(), and DefinitionMixin< Base >::m_impl.
hasUserDocumentation() [2/2]
template<class Base >
virtual bool DefinitionMixin< Base >::hasUserDocumentation () const [inline], [virtual]
Definition at line 177 of file definitionimpl.h.
{ return m_impl.hasUserDocumentation(); }
References DefinitionImpl::hasUserDocumentation(), and DefinitionMixin< Base >::m_impl.
id() [1/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::id () const [inline], [virtual]
Definition at line 200 of file definitionimpl.h.
{ return m_impl.id(); }
References DefinitionImpl::id(), and DefinitionMixin< Base >::m_impl.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), and doxmlparser.compound.docXRefSectType::set_id().
id() [2/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::id () const [inline], [virtual]
Definition at line 200 of file definitionimpl.h.
{ return m_impl.id(); }
References DefinitionImpl::id(), and DefinitionMixin< Base >::m_impl.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), and doxmlparser.compound.docXRefSectType::set_id().
inbodyDocumentation() [1/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::inbodyDocumentation () const [inline], [virtual]
Definition at line 168 of file definitionimpl.h.
{ return m_impl.inbodyDocumentation(); }
References DefinitionImpl::inbodyDocumentation(), and DefinitionMixin< Base >::m_impl.
inbodyDocumentation() [2/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::inbodyDocumentation () const [inline], [virtual]
Definition at line 168 of file definitionimpl.h.
{ return m_impl.inbodyDocumentation(); }
References DefinitionImpl::inbodyDocumentation(), and DefinitionMixin< Base >::m_impl.
inbodyFile() [1/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::inbodyFile () const [inline], [virtual]
Definition at line 169 of file definitionimpl.h.
{ return m_impl.inbodyFile(); }
References DefinitionImpl::inbodyFile(), and DefinitionMixin< Base >::m_impl.
inbodyFile() [2/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::inbodyFile () const [inline], [virtual]
Definition at line 169 of file definitionimpl.h.
{ return m_impl.inbodyFile(); }
References DefinitionImpl::inbodyFile(), and DefinitionMixin< Base >::m_impl.
inbodyLine() [1/2]
template<class Base >
virtual int DefinitionMixin< Base >::inbodyLine () const [inline], [virtual]
Definition at line 170 of file definitionimpl.h.
{ return m_impl.inbodyLine(); }
References DefinitionImpl::inbodyLine(), and DefinitionMixin< Base >::m_impl.
inbodyLine() [2/2]
template<class Base >
virtual int DefinitionMixin< Base >::inbodyLine () const [inline], [virtual]
Definition at line 170 of file definitionimpl.h.
{ return m_impl.inbodyLine(); }
References DefinitionImpl::inbodyLine(), and DefinitionMixin< Base >::m_impl.
isAlias() [1/2]
template<class Base >
virtual bool DefinitionMixin< Base >::isAlias () const [inline], [virtual]
Definition at line 152 of file definitionimpl.h.
{ return FALSE; }
References FALSE.
isAlias() [2/2]
template<class Base >
virtual bool DefinitionMixin< Base >::isAlias () const [inline], [virtual]
Definition at line 152 of file definitionimpl.h.
{ return FALSE; }
References FALSE.
isAnonymous() [1/2]
template<class Base >
virtual bool DefinitionMixin< Base >::isAnonymous () const [inline], [virtual]
Definition at line 156 of file definitionimpl.h.
{ return m_impl.isAnonymous(); }
References DefinitionImpl::isAnonymous(), and DefinitionMixin< Base >::m_impl.
isAnonymous() [2/2]
template<class Base >
virtual bool DefinitionMixin< Base >::isAnonymous () const [inline], [virtual]
Definition at line 156 of file definitionimpl.h.
{ return m_impl.isAnonymous(); }
References DefinitionImpl::isAnonymous(), and DefinitionMixin< Base >::m_impl.
isArtificial() [1/2]
template<class Base >
virtual bool DefinitionMixin< Base >::isArtificial () const [inline], [virtual]
Definition at line 181 of file definitionimpl.h.
{ return m_impl.isArtificial(); }
References DefinitionImpl::isArtificial(), and DefinitionMixin< Base >::m_impl.
isArtificial() [2/2]
template<class Base >
virtual bool DefinitionMixin< Base >::isArtificial () const [inline], [virtual]
Definition at line 181 of file definitionimpl.h.
{ return m_impl.isArtificial(); }
References DefinitionImpl::isArtificial(), and DefinitionMixin< Base >::m_impl.
isHidden() [1/2]
template<class Base >
virtual bool DefinitionMixin< Base >::isHidden () const [inline], [virtual]
Definition at line 180 of file definitionimpl.h.
{ return m_impl.isHidden(); }
References DefinitionImpl::isHidden(), and DefinitionMixin< Base >::m_impl.
isHidden() [2/2]
template<class Base >
virtual bool DefinitionMixin< Base >::isHidden () const [inline], [virtual]
Definition at line 180 of file definitionimpl.h.
{ return m_impl.isHidden(); }
References DefinitionImpl::isHidden(), and DefinitionMixin< Base >::m_impl.
isLinkableViaGroup() [1/2]
template<class Base >
virtual bool DefinitionMixin< Base >::isLinkableViaGroup () const [inline], [virtual]
Definition at line 191 of file definitionimpl.h.
{ return m_impl.isLinkableViaGroup(); }
References DefinitionImpl::isLinkableViaGroup(), and DefinitionMixin< Base >::m_impl.
isLinkableViaGroup() [2/2]
template<class Base >
virtual bool DefinitionMixin< Base >::isLinkableViaGroup () const [inline], [virtual]
Definition at line 191 of file definitionimpl.h.
{ return m_impl.isLinkableViaGroup(); }
References DefinitionImpl::isLinkableViaGroup(), and DefinitionMixin< Base >::m_impl.
isReference() [1/2]
template<class Base >
virtual bool DefinitionMixin< Base >::isReference () const [inline], [virtual]
Reimplemented in ClassDefImpl, MemberDefImpl, ClassDefImpl, and MemberDefImpl.
Definition at line 183 of file definitionimpl.h.
{ return m_impl.isReference(); }
References DefinitionImpl::isReference(), and DefinitionMixin< Base >::m_impl.
Referenced by ClassDefImpl::isReference(), and MemberDefImpl::isReference().
isReference() [2/2]
template<class Base >
virtual bool DefinitionMixin< Base >::isReference () const [inline], [virtual]
Reimplemented in ClassDefImpl, MemberDefImpl, ClassDefImpl, and MemberDefImpl.
Definition at line 183 of file definitionimpl.h.
{ return m_impl.isReference(); }
References DefinitionImpl::isReference(), and DefinitionMixin< Base >::m_impl.
isVisible() [1/2]
template<class Base >
virtual bool DefinitionMixin< Base >::isVisible () const [inline], [virtual]
Definition at line 179 of file definitionimpl.h.
{ return m_impl.isVisible(); }
References DefinitionImpl::isVisible(), and DefinitionMixin< Base >::m_impl.
isVisible() [2/2]
template<class Base >
virtual bool DefinitionMixin< Base >::isVisible () const [inline], [virtual]
Definition at line 179 of file definitionimpl.h.
{ return m_impl.isVisible(); }
References DefinitionImpl::isVisible(), and DefinitionMixin< Base >::m_impl.
isVisibleInProject() [1/2]
template<class Base >
virtual bool DefinitionMixin< Base >::isVisibleInProject () const [inline], [virtual]
Definition at line 178 of file definitionimpl.h.
{ return m_impl.isVisibleInProject(); }
References DefinitionImpl::isVisibleInProject(), and DefinitionMixin< Base >::m_impl.
isVisibleInProject() [2/2]
template<class Base >
virtual bool DefinitionMixin< Base >::isVisibleInProject () const [inline], [virtual]
Definition at line 178 of file definitionimpl.h.
{ return m_impl.isVisibleInProject(); }
References DefinitionImpl::isVisibleInProject(), and DefinitionMixin< Base >::m_impl.
localName() [1/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::localName () const [inline], [virtual]
Reimplemented in NamespaceDefImpl, and NamespaceDefImpl.
Definition at line 157 of file definitionimpl.h.
{ return m_impl.localName(); }
References DefinitionImpl::localName(), and DefinitionMixin< Base >::m_impl.
localName() [2/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::localName () const [inline], [virtual]
Reimplemented in NamespaceDefImpl, and NamespaceDefImpl.
Definition at line 157 of file definitionimpl.h.
{ return m_impl.localName(); }
References DefinitionImpl::localName(), and DefinitionMixin< Base >::m_impl.
makePartOfGroup() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::makePartOfGroup (const GroupDef * gd) [inline], [virtual]
Definition at line 256 of file definitionimpl.h.
    { m_impl.makePartOfGroup(gd); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::makePartOfGroup().
makePartOfGroup() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::makePartOfGroup (const GroupDef * gd) [inline], [virtual]
Definition at line 256 of file definitionimpl.h.
    { m_impl.makePartOfGroup(gd); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::makePartOfGroup().
mergeReferencedBy() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::mergeReferencedBy (const Definition * other) [inline], [virtual]
Definition at line 232 of file definitionimpl.h.
    { m_impl.mergeReferencedBy(other); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::mergeReferencedBy().
mergeReferencedBy() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::mergeReferencedBy (const Definition * other) [inline], [virtual]
Definition at line 232 of file definitionimpl.h.
    { m_impl.mergeReferencedBy(other); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::mergeReferencedBy().
mergeReferences() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::mergeReferences (const Definition * other) [inline], [virtual]
Definition at line 230 of file definitionimpl.h.
    { m_impl.mergeReferences(other); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::mergeReferences().
mergeReferences() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::mergeReferences (const Definition * other) [inline], [virtual]
Definition at line 230 of file definitionimpl.h.
    { m_impl.mergeReferences(other); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::mergeReferences().
mergeRefItems() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::mergeRefItems (Definition * def) [inline], [virtual]
Definition at line 228 of file definitionimpl.h.
    { m_impl.mergeRefItems(def); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::mergeRefItems().
mergeRefItems() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::mergeRefItems (Definition * def) [inline], [virtual]
Definition at line 228 of file definitionimpl.h.
    { m_impl.mergeRefItems(def); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::mergeRefItems().
name() [1/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::name () const [inline], [virtual]
Reimplemented in FileDefImpl, and FileDefImpl.
Definition at line 155 of file definitionimpl.h.
{ return m_impl.name(); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::name().
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), DefinitionMixin< Base >::_setSymbolName(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), GroupDefImpl::displayName(), MemberDefImpl::displayName(), PageDefImpl::displayName(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), DefinitionMixin< Base >::findInnerCompound(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), FileDefImpl::name(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), DefinitionMixin< Base >::setId(), DefinitionMixin< Base >::setLocalName(), DefinitionMixin< Base >::setName(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
name() [2/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::name () const [inline], [virtual]
Reimplemented in FileDefImpl, and FileDefImpl.
Definition at line 155 of file definitionimpl.h.
{ return m_impl.name(); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::name().
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
navigationPathAsString() [1/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::navigationPathAsString () const [inline], [virtual]
Definition at line 260 of file definitionimpl.h.
    { return m_impl.navigationPathAsString(); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::navigationPathAsString().
navigationPathAsString() [2/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::navigationPathAsString () const [inline], [virtual]
Definition at line 260 of file definitionimpl.h.
    { return m_impl.navigationPathAsString(); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::navigationPathAsString().
partOfGroups() [1/2]
template<class Base >
virtual const GroupList & DefinitionMixin< Base >::partOfGroups () const [inline], [virtual]
Definition at line 190 of file definitionimpl.h.
{ return m_impl.partOfGroups(); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::partOfGroups().
partOfGroups() [2/2]
template<class Base >
virtual const GroupList & DefinitionMixin< Base >::partOfGroups () const [inline], [virtual]
Definition at line 190 of file definitionimpl.h.
{ return m_impl.partOfGroups(); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::partOfGroups().
pathFragment() [1/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::pathFragment () const [inline], [virtual]
Definition at line 266 of file definitionimpl.h.
    { return m_impl.pathFragment(); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::pathFragment().
pathFragment() [2/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::pathFragment () const [inline], [virtual]
Definition at line 266 of file definitionimpl.h.
    { return m_impl.pathFragment(); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::pathFragment().
qualifiedName() [1/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::qualifiedName () const [inline], [virtual]
Reimplemented in MemberDefImpl, and MemberDefImpl.
Definition at line 158 of file definitionimpl.h.
{ return m_impl.qualifiedName(); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::qualifiedName().
Referenced by MemberDefImpl::qualifiedName().
qualifiedName() [2/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::qualifiedName () const [inline], [virtual]
Reimplemented in MemberDefImpl, and MemberDefImpl.
Definition at line 158 of file definitionimpl.h.
{ return m_impl.qualifiedName(); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::qualifiedName().
setArtificial() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::setArtificial (bool b) [inline], [virtual]
Definition at line 240 of file definitionimpl.h.
    { m_impl.setArtificial(b); }
References b, DefinitionMixin< Base >::m_impl, and DefinitionImpl::setArtificial().
setArtificial() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::setArtificial (bool b) [inline], [virtual]
Definition at line 240 of file definitionimpl.h.
    { m_impl.setArtificial(b); }
References b, DefinitionMixin< Base >::m_impl, and DefinitionImpl::setArtificial().
setBodyDef() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::setBodyDef (const FileDef * fd) [inline], [virtual]
Definition at line 220 of file definitionimpl.h.
    { m_impl.setBodyDef(fd); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::setBodyDef().
setBodyDef() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::setBodyDef (const FileDef * fd) [inline], [virtual]
Definition at line 220 of file definitionimpl.h.
    { m_impl.setBodyDef(fd); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::setBodyDef().
setBodySegment() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::setBodySegment (int defLine, int bls, int ble) [inline], [virtual]
Definition at line 218 of file definitionimpl.h.
    { m_impl.setBodySegment(defLine,bls,ble); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::setBodySegment().
setBodySegment() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::setBodySegment (int defLine, int bls, int ble) [inline], [virtual]
Definition at line 218 of file definitionimpl.h.
    { m_impl.setBodySegment(defLine,bls,ble); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::setBodySegment().
setBriefDescription() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::setBriefDescription (const QCString & brief, const QCString & briefFile, int briefLine) [inline], [virtual]
Reimplemented in MemberDefImpl, and MemberDefImpl.
Definition at line 210 of file definitionimpl.h.
    { m_impl.setBriefDescription(brief,briefFile,briefLine); }
References DefinitionMixin< Base >::briefFile(), DefinitionMixin< Base >::briefLine(), DefinitionMixin< Base >::m_impl, and DefinitionImpl::setBriefDescription().
Referenced by MemberDefImpl::setBriefDescription().
setBriefDescription() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::setBriefDescription (const QCString & brief, const QCString & briefFile, int briefLine) [inline], [virtual]
Reimplemented in MemberDefImpl, and MemberDefImpl.
Definition at line 210 of file definitionimpl.h.
    { m_impl.setBriefDescription(brief,briefFile,briefLine); }
References DefinitionMixin< Base >::briefFile(), DefinitionMixin< Base >::briefLine(), DefinitionMixin< Base >::m_impl, and DefinitionImpl::setBriefDescription().
setDefFile() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::setDefFile (const QCString & df, int defLine, int defColumn) [inline], [virtual]
Definition at line 206 of file definitionimpl.h.
    { m_impl.setDefFile(df,defLine,defColumn); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::setDefFile().
setDefFile() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::setDefFile (const QCString & df, int defLine, int defColumn) [inline], [virtual]
Definition at line 206 of file definitionimpl.h.
    { m_impl.setDefFile(df,defLine,defColumn); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::setDefFile().
setDocumentation() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::setDocumentation (const QCString & doc, const QCString & docFile, int docLine, bool stripWhiteSpace = TRUE) [inline], [virtual]
Reimplemented in MemberDefImpl, and MemberDefImpl.
Definition at line 208 of file definitionimpl.h.
    { m_impl.setDocumentation(doc,docFile,docLine,stripWhiteSpace); }
References DefinitionMixin< Base >::docFile(), DefinitionMixin< Base >::docLine(), DefinitionMixin< Base >::m_impl, and DefinitionImpl::setDocumentation().
Referenced by MemberDefImpl::setDocumentation().
setDocumentation() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::setDocumentation (const QCString & doc, const QCString & docFile, int docLine, bool stripWhiteSpace = TRUE) [inline], [virtual]
Reimplemented in MemberDefImpl, and MemberDefImpl.
Definition at line 208 of file definitionimpl.h.
    { m_impl.setDocumentation(doc,docFile,docLine,stripWhiteSpace); }
References DefinitionMixin< Base >::docFile(), DefinitionMixin< Base >::docLine(), DefinitionMixin< Base >::m_impl, and DefinitionImpl::setDocumentation().
setHidden() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::setHidden (bool b) [inline], [virtual]
Reimplemented in MemberDefImpl, and MemberDefImpl.
Definition at line 238 of file definitionimpl.h.
    { m_impl.setHidden(b); }
References b, DefinitionMixin< Base >::m_impl, and DefinitionImpl::setHidden().
Referenced by MemberDefImpl::setHidden().
setHidden() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::setHidden (bool b) [inline], [virtual]
Reimplemented in MemberDefImpl, and MemberDefImpl.
Definition at line 238 of file definitionimpl.h.
    { m_impl.setHidden(b); }
References b, DefinitionMixin< Base >::m_impl, and DefinitionImpl::setHidden().
setId() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::setId (const QCString & name) [inline], [virtual]
Definition at line 205 of file definitionimpl.h.
{ m_impl.setId(name); }
References DefinitionMixin< Base >::m_impl, DefinitionMixin< Base >::name(), and DefinitionImpl::setId().
setId() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::setId (const QCString & name) [inline], [virtual]
Definition at line 205 of file definitionimpl.h.
{ m_impl.setId(name); }
References DefinitionMixin< Base >::m_impl, DefinitionMixin< Base >::name(), and DefinitionImpl::setId().
setInbodyDocumentation() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::setInbodyDocumentation (const QCString & doc, const QCString & docFile, int docLine) [inline], [virtual]
Reimplemented in MemberDefImpl, and MemberDefImpl.
Definition at line 212 of file definitionimpl.h.
    { m_impl.setInbodyDocumentation(doc,docFile,docLine); }
References DefinitionMixin< Base >::docFile(), DefinitionMixin< Base >::docLine(), DefinitionMixin< Base >::m_impl, and DefinitionImpl::setInbodyDocumentation().
Referenced by MemberDefImpl::setInbodyDocumentation().
setInbodyDocumentation() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::setInbodyDocumentation (const QCString & doc, const QCString & docFile, int docLine) [inline], [virtual]
Reimplemented in MemberDefImpl, and MemberDefImpl.
Definition at line 212 of file definitionimpl.h.
    { m_impl.setInbodyDocumentation(doc,docFile,docLine); }
References DefinitionMixin< Base >::docFile(), DefinitionMixin< Base >::docLine(), DefinitionMixin< Base >::m_impl, and DefinitionImpl::setInbodyDocumentation().
setLanguage() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::setLanguage (SrcLangExt lang) [inline], [virtual]
Definition at line 242 of file definitionimpl.h.
    { m_impl.setLanguage(lang); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::setLanguage().
setLanguage() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::setLanguage (SrcLangExt lang) [inline], [virtual]
Definition at line 242 of file definitionimpl.h.
    { m_impl.setLanguage(lang); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::setLanguage().
setLocalName() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::setLocalName (const QCString & name) [inline], [virtual]
Definition at line 270 of file definitionimpl.h.
    { m_impl.setLocalName(name); }
References DefinitionMixin< Base >::m_impl, DefinitionMixin< Base >::name(), and DefinitionImpl::setLocalName().
setLocalName() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::setLocalName (const QCString & name) [inline], [virtual]
Definition at line 270 of file definitionimpl.h.
    { m_impl.setLocalName(name); }
References DefinitionMixin< Base >::m_impl, DefinitionMixin< Base >::name(), and DefinitionImpl::setLocalName().
setName() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::setName (const QCString & name) [inline], [virtual]
Reimplemented in ClassDefImpl, and ClassDefImpl.
Definition at line 204 of file definitionimpl.h.
{ m_impl.setName(name); }
References DefinitionMixin< Base >::m_impl, DefinitionMixin< Base >::name(), and DefinitionImpl::setName().
Referenced by ClassDefImpl::setName().
setName() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::setName (const QCString & name) [inline], [virtual]
Reimplemented in ClassDefImpl, and ClassDefImpl.
Definition at line 204 of file definitionimpl.h.
{ m_impl.setName(name); }
References DefinitionMixin< Base >::m_impl, DefinitionMixin< Base >::name(), and DefinitionImpl::setName().
setOuterScope() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::setOuterScope (Definition * def) [inline], [virtual]
Definition at line 236 of file definitionimpl.h.
    { m_impl.setOuterScope(def); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::setOuterScope().
setOuterScope() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::setOuterScope (Definition * def) [inline], [virtual]
Definition at line 236 of file definitionimpl.h.
    { m_impl.setOuterScope(def); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::setOuterScope().
setReference() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::setReference (const QCString & r) [inline], [virtual]
Definition at line 214 of file definitionimpl.h.
    { m_impl.setReference(r); }
References DefinitionMixin< Base >::m_impl, r, and DefinitionImpl::setReference().
setReference() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::setReference (const QCString & r) [inline], [virtual]
Definition at line 214 of file definitionimpl.h.
    { m_impl.setReference(r); }
References DefinitionMixin< Base >::m_impl, r, and DefinitionImpl::setReference().
setRefItems() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::setRefItems (const RefItemVector & sli) [inline], [virtual]
Definition at line 226 of file definitionimpl.h.
    { m_impl.setRefItems(sli); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::setRefItems().
setRefItems() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::setRefItems (const RefItemVector & sli) [inline], [virtual]
Definition at line 226 of file definitionimpl.h.
    { m_impl.setRefItems(sli); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::setRefItems().
symbolName() [1/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::symbolName () const [inline], [virtual]
Definition at line 159 of file definitionimpl.h.
{ return m_impl.symbolName(); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::symbolName().
symbolName() [2/2]
template<class Base >
virtual QCString DefinitionMixin< Base >::symbolName () const [inline], [virtual]
Definition at line 159 of file definitionimpl.h.
{ return m_impl.symbolName(); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::symbolName().
toDefinition_() [1/2]
template<class Base >
virtual Definition * DefinitionMixin< Base >::toDefinition_ () [inline], [private], [virtual]
Definition at line 288 of file definitionimpl.h.
{ return this; }
toDefinition_() [2/2]
template<class Base >
virtual Definition * DefinitionMixin< Base >::toDefinition_ () [inline], [private], [virtual]
Definition at line 288 of file definitionimpl.h.
{ return this; }
toDefinitionImpl_() [1/2]
template<class Base >
virtual const DefinitionImpl * DefinitionMixin< Base >::toDefinitionImpl_ () const [inline], [private], [virtual]
Definition at line 290 of file definitionimpl.h.
{ return &m_impl; }
References DefinitionMixin< Base >::m_impl.
toDefinitionImpl_() [2/2]
template<class Base >
virtual const DefinitionImpl * DefinitionMixin< Base >::toDefinitionImpl_ () const [inline], [private], [virtual]
Definition at line 290 of file definitionimpl.h.
{ return &m_impl; }
References DefinitionMixin< Base >::m_impl.
toDefinitionMutable_() [1/2]
template<class Base >
virtual DefinitionMutable * DefinitionMixin< Base >::toDefinitionMutable_ () [inline], [private], [virtual]
Definition at line 289 of file definitionimpl.h.
{ return this; }
toDefinitionMutable_() [2/2]
template<class Base >
virtual DefinitionMutable * DefinitionMixin< Base >::toDefinitionMutable_ () [inline], [private], [virtual]
Definition at line 289 of file definitionimpl.h.
{ return this; }
writeDocAnchorsToTagFile() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::writeDocAnchorsToTagFile (TextStream & fs) const [inline], [virtual]
Definition at line 268 of file definitionimpl.h.
    { m_impl.writeDocAnchorsToTagFile(fs); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::writeDocAnchorsToTagFile().
writeDocAnchorsToTagFile() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::writeDocAnchorsToTagFile (TextStream & fs) const [inline], [virtual]
Definition at line 268 of file definitionimpl.h.
    { m_impl.writeDocAnchorsToTagFile(fs); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::writeDocAnchorsToTagFile().
writeInlineCode() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::writeInlineCode (OutputList & ol, const QCString & scopeName) const [inline], [virtual]
Definition at line 246 of file definitionimpl.h.
    { m_impl.writeInlineCode(ol,scopeName); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::writeInlineCode().
writeInlineCode() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::writeInlineCode (OutputList & ol, const QCString & scopeName) const [inline], [virtual]
Definition at line 246 of file definitionimpl.h.
    { m_impl.writeInlineCode(ol,scopeName); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::writeInlineCode().
writeNavigationPath() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::writeNavigationPath (OutputList & ol) const [inline], [virtual]
Definition at line 258 of file definitionimpl.h.
    { m_impl.writeNavigationPath(ol); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::writeNavigationPath().
writeNavigationPath() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::writeNavigationPath (OutputList & ol) const [inline], [virtual]
Definition at line 258 of file definitionimpl.h.
    { m_impl.writeNavigationPath(ol); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::writeNavigationPath().
writeQuickMemberLinks() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::writeQuickMemberLinks (OutputList & ol, const MemberDef * md) const [inline], [virtual]
Reimplemented in FileDefImpl, GroupDefImpl, NamespaceDefImpl, FileDefImpl, GroupDefImpl, NamespaceDefImpl, ClassDefImpl, and ClassDefImpl.
Definition at line 262 of file definitionimpl.h.
    { m_impl.writeQuickMemberLinks(ol,md); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::writeQuickMemberLinks().
writeQuickMemberLinks() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::writeQuickMemberLinks (OutputList & ol, const MemberDef * md) const [inline], [virtual]
Reimplemented in FileDefImpl, GroupDefImpl, NamespaceDefImpl, FileDefImpl, GroupDefImpl, NamespaceDefImpl, ClassDefImpl, and ClassDefImpl.
Definition at line 262 of file definitionimpl.h.
    { m_impl.writeQuickMemberLinks(ol,md); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::writeQuickMemberLinks().
writeSourceDef() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::writeSourceDef (OutputList & ol, const QCString & scopeName) const [inline], [virtual]
Definition at line 244 of file definitionimpl.h.
    { m_impl.writeSourceDef(ol,scopeName); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::writeSourceDef().
writeSourceDef() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::writeSourceDef (OutputList & ol, const QCString & scopeName) const [inline], [virtual]
Definition at line 244 of file definitionimpl.h.
    { m_impl.writeSourceDef(ol,scopeName); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::writeSourceDef().
writeSourceReffedBy() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::writeSourceReffedBy (OutputList & ol, const QCString & scopeName) const [inline], [virtual]
Definition at line 254 of file definitionimpl.h.
    { m_impl.writeSourceReffedBy(ol,scopeName); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::writeSourceReffedBy().
writeSourceReffedBy() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::writeSourceReffedBy (OutputList & ol, const QCString & scopeName) const [inline], [virtual]
Definition at line 254 of file definitionimpl.h.
    { m_impl.writeSourceReffedBy(ol,scopeName); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::writeSourceReffedBy().
writeSourceRefs() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::writeSourceRefs (OutputList & ol, const QCString & scopeName) const [inline], [virtual]
Definition at line 252 of file definitionimpl.h.
    { m_impl.writeSourceRefs(ol,scopeName); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::writeSourceRefs().
writeSourceRefs() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::writeSourceRefs (OutputList & ol, const QCString & scopeName) const [inline], [virtual]
Definition at line 252 of file definitionimpl.h.
    { m_impl.writeSourceRefs(ol,scopeName); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::writeSourceRefs().
writeSummaryLinks() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::writeSummaryLinks (OutputList & ol) const [inline], [virtual]
Reimplemented in ClassDefImpl, FileDefImpl, GroupDefImpl, NamespaceDefImpl, ClassDefImpl, FileDefImpl, GroupDefImpl, and NamespaceDefImpl.
Definition at line 264 of file definitionimpl.h.
    { m_impl.writeSummaryLinks(ol); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::writeSummaryLinks().
writeSummaryLinks() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::writeSummaryLinks (OutputList & ol) const [inline], [virtual]
Reimplemented in ClassDefImpl, FileDefImpl, GroupDefImpl, NamespaceDefImpl, ClassDefImpl, FileDefImpl, GroupDefImpl, and NamespaceDefImpl.
Definition at line 264 of file definitionimpl.h.
    { m_impl.writeSummaryLinks(ol); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::writeSummaryLinks().
writeToc() [1/2]
template<class Base >
virtual void DefinitionMixin< Base >::writeToc (OutputList & ol, const LocalToc & lt) const [inline], [virtual]
Definition at line 274 of file definitionimpl.h.
    { m_impl.writeToc(ol,lt); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::writeToc().
writeToc() [2/2]
template<class Base >
virtual void DefinitionMixin< Base >::writeToc (OutputList & ol, const LocalToc & lt) const [inline], [virtual]
Definition at line 274 of file definitionimpl.h.
    { m_impl.writeToc(ol,lt); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::writeToc().
xrefListItems() [1/2]
template<class Base >
virtual const RefItemVector & DefinitionMixin< Base >::xrefListItems () const [inline], [virtual]
Definition at line 192 of file definitionimpl.h.
{ return m_impl.xrefListItems(); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::xrefListItems().
xrefListItems() [2/2]
template<class Base >
virtual const RefItemVector & DefinitionMixin< Base >::xrefListItems () const [inline], [virtual]
Definition at line 192 of file definitionimpl.h.
{ return m_impl.xrefListItems(); }
References DefinitionMixin< Base >::m_impl, and DefinitionImpl::xrefListItems().
Member Data Documentation
m_impl
template<class Base >
DefinitionImpl DefinitionMixin< Base >::m_impl [private]
Definition at line 292 of file definitionimpl.h.
Referenced by DefinitionMixin< Base >::_setSymbolName(), DefinitionMixin< Base >::_symbolName(), DefinitionMixin< Base >::addInnerCompound(), DefinitionMixin< Base >::addSectionsToDefinition(), DefinitionMixin< Base >::addSectionsToIndex(), DefinitionMixin< Base >::addSourceReferencedBy(), DefinitionMixin< Base >::addSourceReferences(), DefinitionMixin< Base >::briefDescription(), DefinitionMixin< Base >::briefDescriptionAsTooltip(), DefinitionMixin< Base >::briefFile(), DefinitionMixin< Base >::briefLine(), DefinitionMixin< Base >::computeTooltip(), DefinitionMixin< Base >::docFile(), DefinitionMixin< Base >::docLine(), DefinitionMixin< Base >::documentation(), DefinitionMixin< Base >::externalReference(), DefinitionMixin< Base >::findInnerCompound(), DefinitionMixin< Base >::getBodyDef(), DefinitionMixin< Base >::getDefColumn(), DefinitionMixin< Base >::getDefFileExtension(), DefinitionMixin< Base >::getDefFileName(), DefinitionMixin< Base >::getDefLine(), DefinitionMixin< Base >::getEndBodyLine(), DefinitionMixin< Base >::getLanguage(), DefinitionMixin< Base >::getOuterScope(), DefinitionMixin< Base >::getReference(), DefinitionMixin< Base >::getReferencedByMembers(), DefinitionMixin< Base >::getReferencesMembers(), DefinitionMixin< Base >::getSectionRefs(), DefinitionMixin< Base >::getSourceAnchor(), DefinitionMixin< Base >::getSourceFileBase(), DefinitionMixin< Base >::getStartBodyLine(), DefinitionMixin< Base >::getStartDefLine(), DefinitionMixin< Base >::hasBriefDescription(), DefinitionMixin< Base >::hasDocumentation(), DefinitionMixin< Base >::hasSections(), DefinitionMixin< Base >::hasSourceReffedBy(), DefinitionMixin< Base >::hasSourceRefs(), DefinitionMixin< Base >::hasSources(), DefinitionMixin< Base >::hasUserDocumentation(), DefinitionMixin< Base >::id(), DefinitionMixin< Base >::inbodyDocumentation(), DefinitionMixin< Base >::inbodyFile(), DefinitionMixin< Base >::inbodyLine(), DefinitionMixin< Base >::isAnonymous(), DefinitionMixin< Base >::isArtificial(), DefinitionMixin< Base >::isHidden(), DefinitionMixin< Base >::isLinkableViaGroup(), DefinitionMixin< Base >::isReference(), DefinitionMixin< Base >::isVisible(), DefinitionMixin< Base >::isVisibleInProject(), DefinitionMixin< Base >::localName(), DefinitionMixin< Base >::makePartOfGroup(), DefinitionMixin< Base >::mergeReferencedBy(), DefinitionMixin< Base >::mergeReferences(), DefinitionMixin< Base >::mergeRefItems(), DefinitionMixin< Base >::name(), DefinitionMixin< Base >::navigationPathAsString(), DefinitionMixin< Base >::partOfGroups(), DefinitionMixin< Base >::pathFragment(), DefinitionMixin< Base >::qualifiedName(), DefinitionMixin< Base >::setArtificial(), DefinitionMixin< Base >::setBodyDef(), DefinitionMixin< Base >::setBodySegment(), DefinitionMixin< Base >::setBriefDescription(), DefinitionMixin< Base >::setDefFile(), DefinitionMixin< Base >::setDocumentation(), DefinitionMixin< Base >::setHidden(), DefinitionMixin< Base >::setId(), DefinitionMixin< Base >::setInbodyDocumentation(), DefinitionMixin< Base >::setLanguage(), DefinitionMixin< Base >::setLocalName(), DefinitionMixin< Base >::setName(), DefinitionMixin< Base >::setOuterScope(), DefinitionMixin< Base >::setReference(), DefinitionMixin< Base >::setRefItems(), DefinitionMixin< Base >::symbolName(), DefinitionMixin< Base >::toDefinitionImpl_(), DefinitionMixin< Base >::writeDocAnchorsToTagFile(), DefinitionMixin< Base >::writeInlineCode(), DefinitionMixin< Base >::writeNavigationPath(), DefinitionMixin< Base >::writeQuickMemberLinks(), DefinitionMixin< Base >::writeSourceDef(), DefinitionMixin< Base >::writeSourceReffedBy(), DefinitionMixin< Base >::writeSourceRefs(), DefinitionMixin< Base >::writeSummaryLinks(), DefinitionMixin< Base >::writeToc(), and DefinitionMixin< Base >::xrefListItems().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/definitionimpl.h
doxygen/src/definitionimpl.h