TranslatorSpanish Class Reference
#include <translator_es.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
virtual QCString trDesignUnitHierarchy ()
virtual QCString trDesignUnitList ()
virtual QCString trDesignUnitMembers ()
virtual QCString trDesignUnitListDescription ()
virtual QCString trDesignUnitIndex ()
virtual QCString trDesignUnits ()
virtual QCString trFunctionAndProc ()
virtual QCString trVhdlType (uint64 type, bool single)
virtual QCString trCustomReference (const QCString &name)
virtual QCString trConstants ()
virtual QCString trConstantDocumentation ()
virtual QCString trSequences ()
virtual QCString trSequenceDocumentation ()
virtual QCString trDictionaries ()
virtual QCString trDictionaryDocumentation ()
virtual QCString trSliceInterfaces ()
virtual QCString trInterfaceIndex ()
virtual QCString trInterfaceList ()
virtual QCString trInterfaceListDescription ()
virtual QCString trInterfaceHierarchy ()
virtual QCString trInterfaceHierarchyDescription ()
virtual QCString trInterfaceDocumentation ()
virtual QCString trStructs ()
virtual QCString trStructIndex ()
virtual QCString trStructList ()
virtual QCString trStructListDescription ()
virtual QCString trStructDocumentation ()
virtual QCString trExceptionIndex ()
virtual QCString trExceptionList ()
virtual QCString trExceptionListDescription ()
virtual QCString trExceptionHierarchy ()
virtual QCString trExceptionHierarchyDescription ()
virtual QCString trExceptionDocumentation ()
virtual QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal)
virtual QCString trOperations ()
virtual QCString trOperationDocumentation ()
virtual QCString trDataMembers ()
virtual QCString trDataMemberDocumentation ()
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
virtual QCString trDesignUnitHierarchy ()
virtual QCString trDesignUnitList ()
virtual QCString trDesignUnitMembers ()
virtual QCString trDesignUnitListDescription ()
virtual QCString trDesignUnitIndex ()
virtual QCString trDesignUnits ()
virtual QCString trFunctionAndProc ()
virtual QCString trVhdlType (uint64 type, bool single)
virtual QCString trCustomReference (const QCString &name)
virtual QCString trConstants ()
virtual QCString trConstantDocumentation ()
virtual QCString trSequences ()
virtual QCString trSequenceDocumentation ()
virtual QCString trDictionaries ()
virtual QCString trDictionaryDocumentation ()
virtual QCString trSliceInterfaces ()
virtual QCString trInterfaceIndex ()
virtual QCString trInterfaceList ()
virtual QCString trInterfaceListDescription ()
virtual QCString trInterfaceHierarchy ()
virtual QCString trInterfaceHierarchyDescription ()
virtual QCString trInterfaceDocumentation ()
virtual QCString trStructs ()
virtual QCString trStructIndex ()
virtual QCString trStructList ()
virtual QCString trStructListDescription ()
virtual QCString trStructDocumentation ()
virtual QCString trExceptionIndex ()
virtual QCString trExceptionList ()
virtual QCString trExceptionListDescription ()
virtual QCString trExceptionHierarchy ()
virtual QCString trExceptionHierarchyDescription ()
virtual QCString trExceptionDocumentation ()
virtual QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal)
virtual QCString trOperations ()
virtual QCString trOperationDocumentation ()
virtual QCString trDataMembers ()
virtual QCString trDataMemberDocumentation ()
Additional Inherited Members
Detailed Description
translator_es.h modified by Lucas Cruz (7-julio-2000) Some notes:
It's posible that some sentences haven't got meaning because some words haven't got translate in spanish. Updated from 1.3.8 to 1.4.6 by Guillermo Ballester Valor (May-05-2006) Updated to 1.5.1 by Bartomeu Creus Navarro (22-enero-2007) Updated to 1.5.5 by Bartomeu Creus Navarro (5-febrero-2008) Updated to 1.5.8 by Bartomeu Creus Navarro (10-abril-2009) Updated to 1.6.3 by Bartomeu Creus Navarro (3-marzo-2010) Updated to 1.6.4 by Bartomeu Creus Navarro (26-mayo-2010) [(16-jun-2010) grabado en UTF-8] Updated to 1.8.0 by Bartomeu Creus Navarro (11-abril-2012) Updated to 1.8.2 by Bartomeu Creus Navarro (01-julio-2012) Updated to 1.8.4 by Bartomeu Creus Navarro (17-julio-2013)
Definition at line 37 of file translator_es.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorSpanish::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 75 of file translator_es.h.
    {
      return "0x40A Spanish(Traditional Sort)";
    }
getLanguageString() [2/2]
virtual QCString TranslatorSpanish::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 75 of file translator_es.h.
    {
      return "0x40A Spanish(Traditional Sort)";
    }
idLanguage() [1/2]
virtual QCString TranslatorSpanish::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 49 of file translator_es.h.
    { return "spanish"; }
idLanguage() [2/2]
virtual QCString TranslatorSpanish::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 49 of file translator_es.h.
    { return "spanish"; }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorSpanish::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 66 of file translator_es.h.
    {
      return "\\usepackage[spanish]{babel}";
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorSpanish::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 66 of file translator_es.h.
    {
      return "\\usepackage[spanish]{babel}";
    }
trAdditionalInheritedMembers() [1/2]
virtual QCString TranslatorSpanish::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1957 of file translator_es.h.
    { return "Otros miembros heredados"; }
trAdditionalInheritedMembers() [2/2]
virtual QCString TranslatorSpanish::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1957 of file translator_es.h.
    { return "Otros miembros heredados"; }
trAll() [1/2]
virtual QCString TranslatorSpanish::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1447 of file translator_es.h.
    {
      return "Todo";
    }
trAll() [2/2]
virtual QCString TranslatorSpanish::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1447 of file translator_es.h.
    {
      return "Todo";
    }
trAndMore() [1/2]
virtual QCString TranslatorSpanish::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1933 of file translator_es.h.
    { return "y "+number+" ms..."; }
trAndMore() [2/2]
virtual QCString TranslatorSpanish::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1933 of file translator_es.h.
    { return "y "+number+" ms..."; }
trAttention() [1/2]
virtual QCString TranslatorSpanish::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 992 of file translator_es.h.
    {
      return "Atencin";
    }
trAttention() [2/2]
virtual QCString TranslatorSpanish::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 992 of file translator_es.h.
    {
      return "Atencin";
    }
trAuthor() [1/2]
virtual QCString TranslatorSpanish::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1313 of file translator_es.h.
    {
      QCString result((first_capital ? "Autor" : "autor"));
      if (!singular) result+="es";
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorSpanish::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1313 of file translator_es.h.
    {
      QCString result((first_capital ? "Autor" : "autor"));
      if (!singular) result+="es";
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorSpanish::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1170 of file translator_es.h.
    {
      return "Bug";
    }
trBug() [2/2]
virtual QCString TranslatorSpanish::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1170 of file translator_es.h.
    {
      return "Bug";
    }
trBugList() [1/2]
virtual QCString TranslatorSpanish::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1176 of file translator_es.h.
    {
      return "Lista de bugs";
    }
trBugList() [2/2]
virtual QCString TranslatorSpanish::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1176 of file translator_es.h.
    {
      return "Lista de bugs";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorSpanish::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1575 of file translator_es.h.
    {
      return "Grfico de llamadas a esta funcin:";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorSpanish::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1575 of file translator_es.h.
    {
      return "Grfico de llamadas a esta funcin:";
    }
trCallGraph() [1/2]
virtual QCString TranslatorSpanish::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1453 of file translator_es.h.
    {
      return "Grfico de llamadas para esta funcin:";
    }
trCallGraph() [2/2]
virtual QCString TranslatorSpanish::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1453 of file translator_es.h.
    {
      return "Grfico de llamadas para esta funcin:";
    }
trCiteReferences() [1/2]
virtual QCString TranslatorSpanish::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1909 of file translator_es.h.
    { return "Referencias bibliogrficas"; }
trCiteReferences() [2/2]
virtual QCString TranslatorSpanish::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1909 of file translator_es.h.
    { return "Referencias bibliogrficas"; }
trClass() [1/2]
virtual QCString TranslatorSpanish::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1234 of file translator_es.h.
    {
      QCString result((first_capital ? "Clase" : "clase"));
      if (!singular) result+="s";
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorSpanish::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1234 of file translator_es.h.
    {
      QCString result((first_capital ? "Clase" : "clase"));
      if (!singular) result+="s";
      return result;
    }
trClassDiagram() [1/2]
virtual QCString TranslatorSpanish::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 509 of file translator_es.h.
    {
      return "Diagrama de herencias de "+clName;
    }
trClassDiagram() [2/2]
virtual QCString TranslatorSpanish::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 509 of file translator_es.h.
    {
      return "Diagrama de herencias de "+clName;
    }
trClassDocumentation() [1/2]
virtual QCString TranslatorSpanish::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 384 of file translator_es.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentacin de las estructuras de datos";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Documentacin de las clases";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorSpanish::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 384 of file translator_es.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentacin de las estructuras de datos";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Documentacin de las clases";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorSpanish::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1128 of file translator_es.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estructuras de Datos";
      }
      else
      {
        return "Clases";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorSpanish::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1128 of file translator_es.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estructuras de Datos";
      }
      else
      {
        return "Clases";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorSpanish::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 170 of file translator_es.h.
    { return "Jerarqua de la clase"; }
trClassHierarchy() [2/2]
virtual QCString TranslatorSpanish::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 170 of file translator_es.h.
    { return "Jerarqua de la clase"; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorSpanish::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 229 of file translator_es.h.
    { return "Esta lista de herencias esta ordenada "
              "aproximadamente por orden alfabtico:";
    }
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorSpanish::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 229 of file translator_es.h.
    { return "Esta lista de herencias esta ordenada "
              "aproximadamente por orden alfabtico:";
    }
trClassMethods() [1/2]
virtual QCString TranslatorSpanish::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1995 of file translator_es.h.
    {
      return "Mtodos de la clase";
    }
trClassMethods() [2/2]
virtual QCString TranslatorSpanish::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1995 of file translator_es.h.
    {
      return "Mtodos de la clase";
    }
trCode() [1/2]
virtual QCString TranslatorSpanish::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 876 of file translator_es.h.
    {
      return "cdigo";
    }
trCode() [2/2]
virtual QCString TranslatorSpanish::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 876 of file translator_es.h.
    {
      return "cdigo";
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorSpanish::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 822 of file translator_es.h.
    {
      return "Diagrama de colaboracin para "+clName+":";
    }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorSpanish::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 822 of file translator_es.h.
    {
      return "Diagrama de colaboracin para "+clName+":";
    }
trCompoundIndex() [1/2]
virtual QCString TranslatorSpanish::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 357 of file translator_es.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "ndice de estructura de datos";
      }
      else
      {
        return "ndice de clases";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorSpanish::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 357 of file translator_es.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "ndice de estructura de datos";
      }
      else
      {
        return "ndice de clases";
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorSpanish::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1636 of file translator_es.h.
    { return "ndice de tipos de datos"; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorSpanish::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1636 of file translator_es.h.
    { return "ndice de tipos de datos"; }
trCompoundList() [1/2]
virtual QCString TranslatorSpanish::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 174 of file translator_es.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estructura de datos";
      }
      else
      {
        return "Lista de clases";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorSpanish::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 174 of file translator_es.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estructura de datos";
      }
      else
      {
        return "Lista de clases";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorSpanish::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 244 of file translator_es.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Lista de estructuras con una breve descripcin:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Lista de las clases con una breve descripcin:";
      }
      else
      {
       return "Lista de las clases, estructuras, "
             "uniones e interfaces con una breve descripcin:";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorSpanish::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 244 of file translator_es.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Lista de estructuras con una breve descripcin:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Lista de las clases con una breve descripcin:";
      }
      else
      {
       return "Lista de las clases, estructuras, "
             "uniones e interfaces con una breve descripcin:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorSpanish::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1609 of file translator_es.h.
    { return "Aqu estn los tipos de datos con una breve descripcin:"; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorSpanish::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1609 of file translator_es.h.
    { return "Aqu estn los tipos de datos con una breve descripcin:"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorSpanish::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1601 of file translator_es.h.
    { return "Lista de tipos de datos"; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorSpanish::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1601 of file translator_es.h.
    { return "Lista de tipos de datos"; }
trCompoundMembers() [1/2]
virtual QCString TranslatorSpanish::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 191 of file translator_es.h.
    {
    if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Campos de datos";
      }
      else
      {
        return "Miembros de las clases";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorSpanish::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 191 of file translator_es.h.
    {
    if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Campos de datos";
      }
      else
      {
        return "Miembros de las clases";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorSpanish::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 262 of file translator_es.h.
    {
      QCString result="Lista de todos los ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="campos de estructuras y uniones";
      }
      else
      {
        result+="campos de clases";
      }
      if (!extractAll)
      {
        result+=" documentados";
      }
      result+=" con enlaces a ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="la documentacin de la estructura/unin para cada campo:";
        }
        else
        {
          result+="la documentacin de la clase para cada miembro:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="las estructuras/uniones a que pertenecen:";
        }
        else
        {
          result+="las classes a que pertenecen:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorSpanish::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 262 of file translator_es.h.
    {
      QCString result="Lista de todos los ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="campos de estructuras y uniones";
      }
      else
      {
        result+="campos de clases";
      }
      if (!extractAll)
      {
        result+=" documentados";
      }
      result+=" con enlaces a ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="la documentacin de la estructura/unin para cada campo:";
        }
        else
        {
          result+="la documentacin de la clase para cada miembro:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="las estructuras/uniones a que pertenecen:";
        }
        else
        {
          result+="las classes a que pertenecen:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorSpanish::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1613 of file translator_es.h.
    {
      QCString result="Aqu est una lista de todos ";
      result+="los miembros de los tipos de datos ";
      if (!extractAll)
      {
        result+="documentados ";
      }
      result+="con enlaces a ";
      if (!extractAll)
      {
         result+="la documentacin de la estructura de datos para cada miembro";
      }
      else
      {
         result+="los tipos de dato a que pertenece:";
      }
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorSpanish::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1613 of file translator_es.h.
    {
      QCString result="Aqu est una lista de todos ";
      result+="los miembros de los tipos de datos ";
      if (!extractAll)
      {
        result+="documentados ";
      }
      result+="con enlaces a ";
      if (!extractAll)
      {
         result+="la documentacin de la estructura de datos para cada miembro";
      }
      else
      {
         result+="los tipos de dato a que pertenece:";
      }
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorSpanish::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1605 of file translator_es.h.
    { return "Etiquetas de datos"; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorSpanish::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1605 of file translator_es.h.
    { return "Etiquetas de datos"; }
trCompoundReference() [1/2]
virtual QCString TranslatorSpanish::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 584 of file translator_es.h.
    {
      QCString result="Referencia de";
      if (isTemplate) result+=" la plantilla de";
      switch(compType)
      {
        case ClassDef::Class: result+=" la Clase "; break;
        case ClassDef::Struct: result+=" la Estructura "; break;
        case ClassDef::Union: result+=" la Unin "; break;
        case ClassDef::Interface: result+=" la Interfaz "; break;
        case ClassDef::Protocol: result+="l Protocolo "; break;
        case ClassDef::Category: result+=" la Categoria "; break;
        case ClassDef::Exception: result+=" la Excepcin "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorSpanish::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 584 of file translator_es.h.
    {
      QCString result="Referencia de";
      if (isTemplate) result+=" la plantilla de";
      switch(compType)
      {
        case ClassDef::Class: result+=" la Clase "; break;
        case ClassDef::Struct: result+=" la Estructura "; break;
        case ClassDef::Union: result+=" la Unin "; break;
        case ClassDef::Interface: result+=" la Interfaz "; break;
        case ClassDef::Protocol: result+="l Protocolo "; break;
        case ClassDef::Category: result+=" la Categoria "; break;
        case ClassDef::Exception: result+=" la Excepcin "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorSpanish::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1677 of file translator_es.h.
    {
      QCString result="Referencia de";
      if (isTemplate) result+=" la plantilla de";
      switch(compType)
      {
        case ClassDef::Class: result+="l mdulo"; break;
        case ClassDef::Struct: result+="l tipo"; break;
        case ClassDef::Union: result+=" la unin"; break;
        case ClassDef::Interface: result+=" la interfaz"; break;
        case ClassDef::Protocol: result+="l protocolo"; break;
        case ClassDef::Category: result+=" la categora"; break;
        case ClassDef::Exception: result+=" la excepcin"; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorSpanish::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1677 of file translator_es.h.
    {
      QCString result="Referencia de";
      if (isTemplate) result+=" la plantilla de";
      switch(compType)
      {
        case ClassDef::Class: result+="l mdulo"; break;
        case ClassDef::Struct: result+="l tipo"; break;
        case ClassDef::Union: result+=" la unin"; break;
        case ClassDef::Interface: result+=" la interfaz"; break;
        case ClassDef::Protocol: result+="l protocolo"; break;
        case ClassDef::Category: result+=" la categora"; break;
        case ClassDef::Exception: result+=" la excepcin"; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice() [1/2]
virtual QCString TranslatorSpanish::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) [inline], [virtual]
Implements Translator.
Definition at line 2284 of file translator_es.h.
    {
      QCString result="Referencia de";
      switch(compType)
      {
        case ClassDef::Class: result+=" la Clase"; break;
        case ClassDef::Struct: result+=" la Estructura"; break;
        case ClassDef::Union: result+=" la Unin"; break;
        case ClassDef::Interface: result+=" la Interfaz"; break;
        case ClassDef::Protocol: result+="l Protocolo"; break;
        case ClassDef::Category: result+=" la Categora"; break;
        case ClassDef::Exception: result+=" la Excepcin"; break;
        default: break;
      }
      if (isLocal) result+=" Local";
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice() [2/2]
virtual QCString TranslatorSpanish::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) [inline], [virtual]
Implements Translator.
Definition at line 2284 of file translator_es.h.
    {
      QCString result="Referencia de";
      switch(compType)
      {
        case ClassDef::Class: result+=" la Clase"; break;
        case ClassDef::Struct: result+=" la Estructura"; break;
        case ClassDef::Union: result+=" la Unin"; break;
        case ClassDef::Interface: result+=" la Interfaz"; break;
        case ClassDef::Protocol: result+="l Protocolo"; break;
        case ClassDef::Category: result+=" la Categora"; break;
        case ClassDef::Exception: result+=" la Excepcin"; break;
        default: break;
      }
      if (isLocal) result+=" Local";
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorSpanish::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 485 of file translator_es.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estructuras de datos";
      }
      else
      {
        return "Clases";
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorSpanish::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 485 of file translator_es.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estructuras de datos";
      }
      else
      {
        return "Clases";
      }
    }
References Config_getBool.
trConstantDocumentation() [1/2]
virtual QCString TranslatorSpanish::trConstantDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2192 of file translator_es.h.
    {
        return "Documentacin de constante";
    }
trConstantDocumentation() [2/2]
virtual QCString TranslatorSpanish::trConstantDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2192 of file translator_es.h.
    {
        return "Documentacin de constante";
    }
trConstantGroupReference() [1/2]
virtual QCString TranslatorSpanish::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 2032 of file translator_es.h.
    {
      QCString result=namespaceName;
      result+=" referencia de grupos constantes";
      return result;
    }
trConstantGroupReference() [2/2]
virtual QCString TranslatorSpanish::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 2032 of file translator_es.h.
    {
      QCString result=namespaceName;
      result+=" referencia de grupos constantes";
      return result;
    }
trConstantGroups() [1/2]
virtual QCString TranslatorSpanish::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 2028 of file translator_es.h.
    { return "Grupos constantes"; }
trConstantGroups() [2/2]
virtual QCString TranslatorSpanish::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 2028 of file translator_es.h.
    { return "Grupos constantes"; }
trConstants() [1/2]
virtual QCString TranslatorSpanish::trConstants () [inline], [virtual]
Implements Translator.
Definition at line 2188 of file translator_es.h.
    {
        return "Constantes";
    }
trConstants() [2/2]
virtual QCString TranslatorSpanish::trConstants () [inline], [virtual]
Implements Translator.
Definition at line 2188 of file translator_es.h.
    {
        return "Constantes";
    }
trConstructorDocumentation() [1/2]
virtual QCString TranslatorSpanish::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 834 of file translator_es.h.
    {
      return "Documentacin del constructor y destructor";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorSpanish::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 834 of file translator_es.h.
    {
      return "Documentacin del constructor y destructor";
    }
trCopyright() [1/2]
virtual QCString TranslatorSpanish::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1913 of file translator_es.h.
    { return "Copyright"; }
trCopyright() [2/2]
virtual QCString TranslatorSpanish::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1913 of file translator_es.h.
    { return "Copyright"; }
trCustomReference() [1/2]
virtual QCString TranslatorSpanish::trCustomReference (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 2185 of file translator_es.h.
    { return "Referencia"+QCString(name); }
References setup::name.
trCustomReference() [2/2]
virtual QCString TranslatorSpanish::trCustomReference (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 2185 of file translator_es.h.
    { return "Referencia"+QCString(name); }
References setup::name.
trDataMemberDocumentation() [1/2]
virtual QCString TranslatorSpanish::trDataMemberDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2314 of file translator_es.h.
    {
        return "Documentacin miembro de datos";
    }
trDataMemberDocumentation() [2/2]
virtual QCString TranslatorSpanish::trDataMemberDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2314 of file translator_es.h.
    {
        return "Documentacin miembro de datos";
    }
trDataMembers() [1/2]
virtual QCString TranslatorSpanish::trDataMembers () [inline], [virtual]
Implements Translator.
Definition at line 2310 of file translator_es.h.
    {
        return "Miembros de datos";
    }
trDataMembers() [2/2]
virtual QCString TranslatorSpanish::trDataMembers () [inline], [virtual]
Implements Translator.
Definition at line 2310 of file translator_es.h.
    {
        return "Miembros de datos";
    }
trDataTypes() [1/2]
virtual QCString TranslatorSpanish::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1660 of file translator_es.h.
    { return "Tipos de datos"; }
trDataTypes() [2/2]
virtual QCString TranslatorSpanish::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1660 of file translator_es.h.
    { return "Tipos de datos"; }
trDate() [1/2]
virtual QCString TranslatorSpanish::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 523 of file translator_es.h.
    { return "Fecha"; }
trDate() [2/2]
virtual QCString TranslatorSpanish::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 523 of file translator_es.h.
    { return "Fecha"; }
trDateTime() [1/2]
virtual QCString TranslatorSpanish::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1863 of file translator_es.h.
    {
      static const char *days[] = { "Lunes","Martes","Mircoles","Jueves",
                                      "Viernes","Sbado","Domingo" };
      static const char *months[] = { "Enero","Febrero","Marzo","Abril",
                                      "Mayo","Junio","Julio","Agosto",
                                      "Septiembre","Octubre","Noviembre","Diciembre" };
      QCString sdate;
      sdate.sprintf("%s, %d de %s de %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDateTime() [2/2]
virtual QCString TranslatorSpanish::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1863 of file translator_es.h.
    {
      static const char *days[] = { "Lunes","Martes","Mircoles","Jueves",
                                      "Viernes","Sbado","Domingo" };
      static const char *months[] = { "Enero","Febrero","Marzo","Abril",
                                      "Mayo","Junio","Julio","Agosto",
                                      "Septiembre","Octubre","Noviembre","Diciembre" };
      QCString sdate;
      sdate.sprintf("%s, %d de %s de %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDayOfWeek() [1/2]
virtual QCString TranslatorSpanish::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1882 of file translator_es.h.
    {
      static const char *days_short[] = { "lu.", "ma.", "mi.", "ju.", "vi.", "s.", "do." };
      static const char *days_full[] = { "lunes", "martes", "mircoles", "jueves", "viernes", "sbado", "domingo" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayOfWeek() [2/2]
virtual QCString TranslatorSpanish::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1882 of file translator_es.h.
    {
      static const char *days_short[] = { "lu.", "ma.", "mi.", "ju.", "vi.", "s.", "do." };
      static const char *days_full[] = { "lunes", "martes", "mircoles", "jueves", "viernes", "sbado", "domingo" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod() [1/2]
virtual QCString TranslatorSpanish::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1898 of file translator_es.h.
    {
      static const char *dayPeriod[] = { "a. m.", "p. m." };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorSpanish::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1898 of file translator_es.h.
    {
      static const char *dayPeriod[] = { "a. m.", "p. m." };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorSpanish::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 799 of file translator_es.h.
    {
      return "Definicin en la lnea @0 del archivo @1.";
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorSpanish::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 799 of file translator_es.h.
    {
      return "Definicin en la lnea @0 del archivo @1.";
    }
trDefinedIn() [1/2]
virtual QCString TranslatorSpanish::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 158 of file translator_es.h.
    { return "definido en"; }
trDefinedIn() [2/2]
virtual QCString TranslatorSpanish::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 158 of file translator_es.h.
    { return "definido en"; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorSpanish::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 803 of file translator_es.h.
    {
      return "Definicin en el archivo @0.";
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorSpanish::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 803 of file translator_es.h.
    {
      return "Definicin en el archivo @0.";
    }
trDefineDocumentation() [1/2]
virtual QCString TranslatorSpanish::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 455 of file translator_es.h.
    { return "Documentacin de los 'defines'"; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorSpanish::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 455 of file translator_es.h.
    { return "Documentacin de los 'defines'"; }
trDefines() [1/2]
virtual QCString TranslatorSpanish::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 419 of file translator_es.h.
    { return "defines"; }
trDefines() [2/2]
virtual QCString TranslatorSpanish::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 419 of file translator_es.h.
    { return "defines"; }
trDefineValue() [1/2]
virtual QCString TranslatorSpanish::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1160 of file translator_es.h.
    {
      return "Valor:";
    }
trDefineValue() [2/2]
virtual QCString TranslatorSpanish::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1160 of file translator_es.h.
    {
      return "Valor:";
    }
trDeprecated() [1/2]
virtual QCString TranslatorSpanish::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 812 of file translator_es.h.
    {
    return "Obsoleto";
    }
trDeprecated() [2/2]
virtual QCString TranslatorSpanish::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 812 of file translator_es.h.
    {
    return "Obsoleto";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorSpanish::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1370 of file translator_es.h.
    {
      return "Lista de obsoletos";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorSpanish::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1370 of file translator_es.h.
    {
      return "Lista de obsoletos";
    }
trDesignUnitHierarchy() [1/2]
virtual QCString TranslatorSpanish::trDesignUnitHierarchy () [inline], [virtual]
VHDL design unit hierarchy
Implements Translator.
Definition at line 2076 of file translator_es.h.
    { return "Jerarqua de unidades de diseo"; }
trDesignUnitHierarchy() [2/2]
virtual QCString TranslatorSpanish::trDesignUnitHierarchy () [inline], [virtual]
VHDL design unit hierarchy
Implements Translator.
Definition at line 2076 of file translator_es.h.
    { return "Jerarqua de unidades de diseo"; }
trDesignUnitIndex() [1/2]
virtual QCString TranslatorSpanish::trDesignUnitIndex () [inline], [virtual]
VHDL design unit index
Implements Translator.
Definition at line 2091 of file translator_es.h.
    { return "Indice de unidades de diseo"; }
trDesignUnitIndex() [2/2]
virtual QCString TranslatorSpanish::trDesignUnitIndex () [inline], [virtual]
VHDL design unit index
Implements Translator.
Definition at line 2091 of file translator_es.h.
    { return "Indice de unidades de diseo"; }
trDesignUnitList() [1/2]
virtual QCString TranslatorSpanish::trDesignUnitList () [inline], [virtual]
VHDL design unit list
Implements Translator.
Definition at line 2079 of file translator_es.h.
    { return "Lista de unidades de diseo"; }
trDesignUnitList() [2/2]
virtual QCString TranslatorSpanish::trDesignUnitList () [inline], [virtual]
VHDL design unit list
Implements Translator.
Definition at line 2079 of file translator_es.h.
    { return "Lista de unidades de diseo"; }
trDesignUnitListDescription() [1/2]
virtual QCString TranslatorSpanish::trDesignUnitListDescription () [inline], [virtual]
VHDL design unit list description
Implements Translator.
Definition at line 2085 of file translator_es.h.
    {
        return "Aqu hay una lista de todos los miembros de la unidad de diseo con "
            "enlaces a las entidades a las que pertenecen:";
    }
trDesignUnitListDescription() [2/2]
virtual QCString TranslatorSpanish::trDesignUnitListDescription () [inline], [virtual]
VHDL design unit list description
Implements Translator.
Definition at line 2085 of file translator_es.h.
    {
        return "Aqu hay una lista de todos los miembros de la unidad de diseo con "
            "enlaces a las entidades a las que pertenecen:";
    }
trDesignUnitMembers() [1/2]
virtual QCString TranslatorSpanish::trDesignUnitMembers () [inline], [virtual]
VHDL design unit members
Implements Translator.
Definition at line 2082 of file translator_es.h.
    { return "Miembros de las unidades de diseo"; }
trDesignUnitMembers() [2/2]
virtual QCString TranslatorSpanish::trDesignUnitMembers () [inline], [virtual]
VHDL design unit members
Implements Translator.
Definition at line 2082 of file translator_es.h.
    { return "Miembros de las unidades de diseo"; }
trDesignUnits() [1/2]
virtual QCString TranslatorSpanish::trDesignUnits () [inline], [virtual]
VHDL design units
Implements Translator.
Definition at line 2094 of file translator_es.h.
    { return "Unidades de Diseo"; }
trDesignUnits() [2/2]
virtual QCString TranslatorSpanish::trDesignUnits () [inline], [virtual]
VHDL design units
Implements Translator.
Definition at line 2094 of file translator_es.h.
    { return "Unidades de Diseo"; }
trDetailedDescription() [1/2]
virtual QCString TranslatorSpanish::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 91 of file translator_es.h.
    { return "Descripcin detallada"; }
trDetailedDescription() [2/2]
virtual QCString TranslatorSpanish::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 91 of file translator_es.h.
    { return "Descripcin detallada"; }
trDetailLevel() [1/2]
virtual QCString TranslatorSpanish::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1925 of file translator_es.h.
    { return "detalle nivel"; }
trDetailLevel() [2/2]
virtual QCString TranslatorSpanish::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1925 of file translator_es.h.
    { return "detalle nivel"; }
trDictionaries() [1/2]
virtual QCString TranslatorSpanish::trDictionaries () [inline], [virtual]
Implements Translator.
Definition at line 2204 of file translator_es.h.
    {
        return "Diccionarios";
    }
trDictionaries() [2/2]
virtual QCString TranslatorSpanish::trDictionaries () [inline], [virtual]
Implements Translator.
Definition at line 2204 of file translator_es.h.
    {
        return "Diccionarios";
    }
trDictionaryDocumentation() [1/2]
virtual QCString TranslatorSpanish::trDictionaryDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2208 of file translator_es.h.
    {
        return "Documentacin de diccionario";
    }
trDictionaryDocumentation() [2/2]
virtual QCString TranslatorSpanish::trDictionaryDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2208 of file translator_es.h.
    {
        return "Documentacin de diccionario";
    }
trDir() [1/2]
virtual QCString TranslatorSpanish::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1549 of file translator_es.h.
    {
      QCString result((first_capital ? "Directorio" : "directorio"));
      if (!singular) result+="s";
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorSpanish::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1549 of file translator_es.h.
    {
      QCString result((first_capital ? "Directorio" : "directorio"));
      if (!singular) result+="s";
      return result;
    }
trDirDepGraph() [1/2]
virtual QCString TranslatorSpanish::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1917 of file translator_es.h.
    { return QCString("Grfico de dependencias de directorios para ")+name+":"; }
References setup::name.
trDirDepGraph() [2/2]
virtual QCString TranslatorSpanish::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1917 of file translator_es.h.
    { return QCString("Grfico de dependencias de directorios para ")+name+":"; }
References setup::name.
trDirDocumentation() [1/2]
virtual QCString TranslatorSpanish::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1527 of file translator_es.h.
    { return "Documentacin de directorios"; }
trDirDocumentation() [2/2]
virtual QCString TranslatorSpanish::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1527 of file translator_es.h.
    { return "Documentacin de directorios"; }
trDirectories() [1/2]
virtual QCString TranslatorSpanish::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1533 of file translator_es.h.
    { return "Directorios"; }
trDirectories() [2/2]
virtual QCString TranslatorSpanish::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1533 of file translator_es.h.
    { return "Directorios"; }
trDirIndex() [1/2]
virtual QCString TranslatorSpanish::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1521 of file translator_es.h.
    { return "Jerarqua de directorios"; }
trDirIndex() [2/2]
virtual QCString TranslatorSpanish::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1521 of file translator_es.h.
    { return "Jerarqua de directorios"; }
trDirReference() [1/2]
virtual QCString TranslatorSpanish::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1539 of file translator_es.h.
    {
      QCString result="Referencia del directorio ";
      result+=dirName;
      return result;
    }
trDirReference() [2/2]
virtual QCString TranslatorSpanish::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1539 of file translator_es.h.
    {
      QCString result="Referencia del directorio ";
      result+=dirName;
      return result;
    }
trDirRelation() [1/2]
virtual QCString TranslatorSpanish::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1802 of file translator_es.h.
    {
      return QCString(name)+" relacin";
    }
References setup::name.
trDirRelation() [2/2]
virtual QCString TranslatorSpanish::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1802 of file translator_es.h.
    {
      return QCString(name)+" relacin";
    }
References setup::name.
trDocumentation() [1/2]
virtual QCString TranslatorSpanish::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 339 of file translator_es.h.
    { return "Documentacin"; }
trDocumentation() [2/2]
virtual QCString TranslatorSpanish::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 339 of file translator_es.h.
    { return "Documentacin"; }
trEnumerations() [1/2]
virtual QCString TranslatorSpanish::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 431 of file translator_es.h.
    { return "Enumeraciones"; }
trEnumerations() [2/2]
virtual QCString TranslatorSpanish::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 431 of file translator_es.h.
    { return "Enumeraciones"; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorSpanish::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 467 of file translator_es.h.
    { return "Documentacin de las enumeraciones"; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorSpanish::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 467 of file translator_es.h.
    { return "Documentacin de las enumeraciones"; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorSpanish::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1583 of file translator_es.h.
    { return "Documentacin de los valores de la enumeracin"; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorSpanish::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1583 of file translator_es.h.
    { return "Documentacin de los valores de la enumeracin"; }
trEnumerationValues() [1/2]
virtual QCString TranslatorSpanish::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 449 of file translator_es.h.
    { return "Valores de enumeraciones"; }
trEnumerationValues() [2/2]
virtual QCString TranslatorSpanish::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 449 of file translator_es.h.
    { return "Valores de enumeraciones"; }
trEnumGeneratedFromFiles() [1/2]
virtual QCString TranslatorSpanish::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1937 of file translator_es.h.
    { QCString result = "La documentacin para este enum ha sido generada a partir de";
      if (single)
          result += "l siguiente fichero:";
      else
          result += " los siguientes ficheros:";
      return result;
    }
trEnumGeneratedFromFiles() [2/2]
virtual QCString TranslatorSpanish::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1937 of file translator_es.h.
    { QCString result = "La documentacin para este enum ha sido generada a partir de";
      if (single)
          result += "l siguiente fichero:";
      else
          result += " los siguientes ficheros:";
      return result;
    }
trEnumName() [1/2]
virtual QCString TranslatorSpanish::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 150 of file translator_es.h.
    { return "nombre de la enumeracin"; }
trEnumName() [2/2]
virtual QCString TranslatorSpanish::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 150 of file translator_es.h.
    { return "nombre de la enumeracin"; }
trEnumReference() [1/2]
virtual QCString TranslatorSpanish::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1947 of file translator_es.h.
    { return QCString("Referencia del enum ") + QCString(name); }
References setup::name.
trEnumReference() [2/2]
virtual QCString TranslatorSpanish::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1947 of file translator_es.h.
    { return QCString("Referencia del enum ") + QCString(name); }
References setup::name.
trEnumValue() [1/2]
virtual QCString TranslatorSpanish::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 154 of file translator_es.h.
    { return "valor enumerado"; }
trEnumValue() [2/2]
virtual QCString TranslatorSpanish::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 154 of file translator_es.h.
    { return "valor enumerado"; }
trEventDocumentation() [1/2]
virtual QCString TranslatorSpanish::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1388 of file translator_es.h.
    {
      return "Documentacin de los eventos";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorSpanish::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1388 of file translator_es.h.
    {
      return "Documentacin de los eventos";
    }
trEvents() [1/2]
virtual QCString TranslatorSpanish::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1382 of file translator_es.h.
    {
      return "Eventos";
    }
trEvents() [2/2]
virtual QCString TranslatorSpanish::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1382 of file translator_es.h.
    {
      return "Eventos";
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorSpanish::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 409 of file translator_es.h.
    { return "Documentacin de ejemplos"; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorSpanish::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 409 of file translator_es.h.
    { return "Documentacin de ejemplos"; }
trExamples() [1/2]
virtual QCString TranslatorSpanish::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 221 of file translator_es.h.
    { return "Ejemplos"; }
trExamples() [2/2]
virtual QCString TranslatorSpanish::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 221 of file translator_es.h.
    { return "Ejemplos"; }
trExamplesDescription() [1/2]
virtual QCString TranslatorSpanish::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 325 of file translator_es.h.
    { return "Lista de todos los ejemplos:"; }
trExamplesDescription() [2/2]
virtual QCString TranslatorSpanish::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 325 of file translator_es.h.
    { return "Lista de todos los ejemplos:"; }
trExceptionDocumentation() [1/2]
virtual QCString TranslatorSpanish::trExceptionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2280 of file translator_es.h.
    {
        return "Documentacin de excepcin";
    }
trExceptionDocumentation() [2/2]
virtual QCString TranslatorSpanish::trExceptionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2280 of file translator_es.h.
    {
        return "Documentacin de excepcin";
    }
trExceptionHierarchy() [1/2]
virtual QCString TranslatorSpanish::trExceptionHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2272 of file translator_es.h.
    {
        return "Jerarqua de excepciones";
    }
trExceptionHierarchy() [2/2]
virtual QCString TranslatorSpanish::trExceptionHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2272 of file translator_es.h.
    {
        return "Jerarqua de excepciones";
    }
trExceptionHierarchyDescription() [1/2]
virtual QCString TranslatorSpanish::trExceptionHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2276 of file translator_es.h.
    {
        return "Este listado de herencia est ordenado de forma aproximada, pero no completamente en orden alfabtico:";
    }
trExceptionHierarchyDescription() [2/2]
virtual QCString TranslatorSpanish::trExceptionHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2276 of file translator_es.h.
    {
        return "Este listado de herencia est ordenado de forma aproximada, pero no completamente en orden alfabtico:";
    }
trExceptionIndex() [1/2]
virtual QCString TranslatorSpanish::trExceptionIndex () [inline], [virtual]
Implements Translator.
Definition at line 2260 of file translator_es.h.
    {
        return "Indice de excepciones";
    }
trExceptionIndex() [2/2]
virtual QCString TranslatorSpanish::trExceptionIndex () [inline], [virtual]
Implements Translator.
Definition at line 2260 of file translator_es.h.
    {
        return "Indice de excepciones";
    }
trExceptionList() [1/2]
virtual QCString TranslatorSpanish::trExceptionList () [inline], [virtual]
Implements Translator.
Definition at line 2264 of file translator_es.h.
    {
        return "Lista de excepciones";
    }
trExceptionList() [2/2]
virtual QCString TranslatorSpanish::trExceptionList () [inline], [virtual]
Implements Translator.
Definition at line 2264 of file translator_es.h.
    {
        return "Lista de excepciones";
    }
trExceptionListDescription() [1/2]
virtual QCString TranslatorSpanish::trExceptionListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2268 of file translator_es.h.
    {
        return "Aqu estn las excepciones con una breve descripcin:";
    }
trExceptionListDescription() [2/2]
virtual QCString TranslatorSpanish::trExceptionListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2268 of file translator_es.h.
    {
        return "Aqu estn las excepciones con una breve descripcin:";
    }
trExceptions() [1/2]
virtual QCString TranslatorSpanish::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 539 of file translator_es.h.
    { return "Excepciones"; }
trExceptions() [2/2]
virtual QCString TranslatorSpanish::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 539 of file translator_es.h.
    { return "Excepciones"; }
trExtendsClass() [1/2]
virtual QCString TranslatorSpanish::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1987 of file translator_es.h.
    {
      return "Extiende la clase @0.";
    }
trExtendsClass() [2/2]
virtual QCString TranslatorSpanish::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1987 of file translator_es.h.
    {
      return "Extiende la clase @0.";
    }
trFile() [1/2]
virtual QCString TranslatorSpanish::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1245 of file translator_es.h.
    {
      QCString result((first_capital ? "Archivo" : "archivo"));
      if (!singular) result+="s";
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorSpanish::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1245 of file translator_es.h.
    {
      QCString result((first_capital ? "Archivo" : "archivo"));
      if (!singular) result+="s";
      return result;
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorSpanish::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 403 of file translator_es.h.
    { return "Documentacin de archivos"; }
trFileDocumentation() [2/2]
virtual QCString TranslatorSpanish::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 403 of file translator_es.h.
    { return "Documentacin de archivos"; }
trFileIn() [1/2]
virtual QCString TranslatorSpanish::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1839 of file translator_es.h.
    {
      return "Fichero en "+name;
    }
References setup::name.
trFileIn() [2/2]
virtual QCString TranslatorSpanish::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1839 of file translator_es.h.
    {
      return "Fichero en "+name;
    }
References setup::name.
trFileIndex() [1/2]
virtual QCString TranslatorSpanish::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 372 of file translator_es.h.
    { return "Indice de archivos"; }
trFileIndex() [2/2]
virtual QCString TranslatorSpanish::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 372 of file translator_es.h.
    { return "Indice de archivos"; }
trFileList() [1/2]
virtual QCString TranslatorSpanish::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 187 of file translator_es.h.
    { return "Lista de archivos"; }
trFileList() [2/2]
virtual QCString TranslatorSpanish::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 187 of file translator_es.h.
    { return "Lista de archivos"; }
trFileListDescription() [1/2]
virtual QCString TranslatorSpanish::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 235 of file translator_es.h.
    {
      QCString result="Lista de todos los archivos ";
      if (!extractAll) result+="documentados y ";
      result+="con descripciones breves:";
      return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorSpanish::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 235 of file translator_es.h.
    {
      QCString result="Lista de todos los archivos ";
      if (!extractAll) result+="documentados y ";
      result+="con descripciones breves:";
      return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorSpanish::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 204 of file translator_es.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globales";
      }
      else
      {
        return "Miembros de los ficheros";
      }
    }
References Config_getBool.
trFileMembers() [2/2]
virtual QCString TranslatorSpanish::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 204 of file translator_es.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globales";
      }
      else
      {
        return "Miembros de los ficheros";
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
virtual QCString TranslatorSpanish::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 304 of file translator_es.h.
    {
      QCString result="Lista de ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="todas las funciones, variables, 'defines', enumeraciones y 'typedefs'";
      }
      else
      {
        result+="todos los mienbros de los ficheros";
      }
      if (!extractAll) result+=" documentados";
      result+=" con enlaces ";
      if (extractAll)
        result+="a los ficheros a los que corresponden:";
      else
        result+="a la documentacin:";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorSpanish::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 304 of file translator_es.h.
    {
      QCString result="Lista de ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="todas las funciones, variables, 'defines', enumeraciones y 'typedefs'";
      }
      else
      {
        result+="todos los mienbros de los ficheros";
      }
      if (!extractAll) result+=" documentados";
      result+=" con enlaces ";
      if (extractAll)
        result+="a los ficheros a los que corresponden:";
      else
        result+="a la documentacin:";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorSpanish::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 606 of file translator_es.h.
    {
      QCString result="Referencia del Archivo ";
      result+=fileName;
      return result;
    }
trFileReference() [2/2]
virtual QCString TranslatorSpanish::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 606 of file translator_es.h.
    {
      QCString result="Referencia del Archivo ";
      result+=fileName;
      return result;
    }
trFriends() [1/2]
virtual QCString TranslatorSpanish::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 566 of file translator_es.h.
    { return "Amigas"; }
trFriends() [2/2]
virtual QCString TranslatorSpanish::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 566 of file translator_es.h.
    { return "Amigas"; }
trFunctionAndProc() [1/2]
virtual QCString TranslatorSpanish::trFunctionAndProc () [inline], [virtual]
VHDL functions/procedures/processes
Implements Translator.
Definition at line 2097 of file translator_es.h.
    { return "Funciones/Procedimientos/Procesos"; }
trFunctionAndProc() [2/2]
virtual QCString TranslatorSpanish::trFunctionAndProc () [inline], [virtual]
VHDL functions/procedures/processes
Implements Translator.
Definition at line 2097 of file translator_es.h.
    { return "Funciones/Procedimientos/Procesos"; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorSpanish::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 473 of file translator_es.h.
    { return "Documentacin de las funciones"; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorSpanish::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 473 of file translator_es.h.
    { return "Documentacin de las funciones"; }
trFunctions() [1/2]
virtual QCString TranslatorSpanish::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 437 of file translator_es.h.
    { return "Funciones"; }
trFunctions() [2/2]
virtual QCString TranslatorSpanish::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 437 of file translator_es.h.
    { return "Funciones"; }
trGeneratedAt() [1/2]
virtual QCString TranslatorSpanish::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 500 of file translator_es.h.
    {
      QCString result="Generado el "+date;
      if (!projName.isEmpty()) result+=" para "+projName;
      result+=" por";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorSpanish::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 500 of file translator_es.h.
    {
      QCString result="Generado el "+date;
      if (!projName.isEmpty()) result+=" para "+projName;
      result+=" por";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorSpanish::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 142 of file translator_es.h.
    { QCString result="Generado automticamente por Doxygen";
      if (!s.isEmpty()) result+=" para "+s;
      result+=" del cdigo fuente.";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorSpanish::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 142 of file translator_es.h.
    { QCString result="Generado automticamente por Doxygen";
      if (!s.isEmpty()) result+=" para "+s;
      result+=" del cdigo fuente.";
      return result;
    }
References s.
trGeneratedBy() [1/2]
virtual QCString TranslatorSpanish::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 543 of file translator_es.h.
    { return "Generado por"; }
trGeneratedBy() [2/2]
virtual QCString TranslatorSpanish::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 543 of file translator_es.h.
    { return "Generado por"; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorSpanish::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 753 of file translator_es.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      QCString result="La documentacin para est";
      switch(compType)
      {
        case ClassDef::Class: result+=vhdlOpt? "a unidades de diseo":"a clase"; break;
        case ClassDef::Struct: result+="a estructura"; break;
        case ClassDef::Union: result+="a unin"; break;
        case ClassDef::Interface: result+="e interfaz"; break;
        case ClassDef::Protocol: result+="e protocolo"; break;
        case ClassDef::Category: result+="a categora"; break;
        case ClassDef::Exception: result+="a excepcin"; break;
        default: break;
      }
      result+=" fue generada a partir de";
      if (single) result+="l siguiente fichero:";
      else result+=" los siguientes ficheros:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, Config_getBool, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorSpanish::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 753 of file translator_es.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      QCString result="La documentacin para est";
      switch(compType)
      {
        case ClassDef::Class: result+=vhdlOpt? "a unidades de diseo":"a clase"; break;
        case ClassDef::Struct: result+="a estructura"; break;
        case ClassDef::Union: result+="a unin"; break;
        case ClassDef::Interface: result+="e interfaz"; break;
        case ClassDef::Protocol: result+="e protocolo"; break;
        case ClassDef::Category: result+="a categora"; break;
        case ClassDef::Exception: result+="a excepcin"; break;
        default: break;
      }
      result+=" fue generada a partir de";
      if (single) result+="l siguiente fichero:";
      else result+=" los siguientes ficheros:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, Config_getBool, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorSpanish::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1747 of file translator_es.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="La documentacin para est";
      switch(compType)
      {
        case ClassDef::Class: result+="e mdulo"; break;
        case ClassDef::Struct: result+="e tipo"; break;
        case ClassDef::Union: result+="a unin"; break;
        case ClassDef::Interface: result+="e interfaz"; break;
        case ClassDef::Protocol: result+="e protocolo"; break;
        case ClassDef::Category: result+="a categora"; break;
        case ClassDef::Exception: result+="a excepcin"; break;
        default: break;
      }
      result+=" fue generada de";
      if (single) result+="l siguiente fichero:";
      else result+=" los siguientes ficheros:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorSpanish::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1747 of file translator_es.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="La documentacin para est";
      switch(compType)
      {
        case ClassDef::Class: result+="e mdulo"; break;
        case ClassDef::Struct: result+="e tipo"; break;
        case ClassDef::Union: result+="a unin"; break;
        case ClassDef::Interface: result+="e interfaz"; break;
        case ClassDef::Protocol: result+="e protocolo"; break;
        case ClassDef::Category: result+="a categora"; break;
        case ClassDef::Exception: result+="a excepcin"; break;
        default: break;
      }
      result+=" fue generada de";
      if (single) result+="l siguiente fichero:";
      else result+=" los siguientes ficheros:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorSpanish::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1300 of file translator_es.h.
    {
      QCString result((first_capital ? "Global" : "global"));
      if (!singular) result+="es";
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorSpanish::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1300 of file translator_es.h.
    {
      QCString result((first_capital ? "Global" : "global"));
      if (!singular) result+="es";
      return result;
    }
trGlobalNamespace() [1/2]
virtual QCString TranslatorSpanish::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1814 of file translator_es.h.
    {
      return "Namespace global";
    }
trGlobalNamespace() [2/2]
virtual QCString TranslatorSpanish::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1814 of file translator_es.h.
    {
      return "Namespace global";
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorSpanish::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 846 of file translator_es.h.
    {
      return "Ir a la documentacin de este archivo.";
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorSpanish::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 846 of file translator_es.h.
    {
      return "Ir a la documentacin de este archivo.";
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorSpanish::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 886 of file translator_es.h.
    {
      return "Ir a la representacin grfica de la jerarqua de la clase";
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorSpanish::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 886 of file translator_es.h.
    {
      return "Ir a la representacin grfica de la jerarqua de la clase";
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorSpanish::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 840 of file translator_es.h.
    {
      return "Ir al cdigo fuente de este archivo.";
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorSpanish::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 840 of file translator_es.h.
    {
      return "Ir al cdigo fuente de este archivo.";
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorSpanish::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 891 of file translator_es.h.
    {
      return "Ir a la jerarqua textual de la clase";
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorSpanish::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 891 of file translator_es.h.
    {
      return "Ir a la jerarqua textual de la clase";
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorSpanish::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 881 of file translator_es.h.
    {
      return "Representacin grfica de la clase";
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorSpanish::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 881 of file translator_es.h.
    {
      return "Representacin grfica de la clase";
    }
trGroup() [1/2]
virtual QCString TranslatorSpanish::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1267 of file translator_es.h.
    {
      QCString result((first_capital ? "Grupo" : "grupo"));
      if (!singular) result+="s";
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorSpanish::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1267 of file translator_es.h.
    {
      QCString result((first_capital ? "Grupo" : "grupo"));
      if (!singular) result+="s";
      return result;
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorSpanish::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 351 of file translator_es.h.
    { return "Indice jerrquico"; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorSpanish::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 351 of file translator_es.h.
    { return "Indice jerrquico"; }
trImplementedFromList() [1/2]
virtual QCString TranslatorSpanish::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1338 of file translator_es.h.
    {
      return "Implementa "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorSpanish::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1338 of file translator_es.h.
    {
      return "Implementa "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorSpanish::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1346 of file translator_es.h.
    {
      return "Implementado en "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorSpanish::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1346 of file translator_es.h.
    {
      return "Implementado en "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorSpanish::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 997 of file translator_es.h.
    {
      return "Grfico de los archivos que directa o "
              "indirectamente incluyen a este archivo:";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorSpanish::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 997 of file translator_es.h.
    {
      return "Grfico de los archivos que directa o "
              "indirectamente incluyen a este archivo:";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorSpanish::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 828 of file translator_es.h.
    {
      return "Dependencia grfica adjunta para "+fName+":";
    }
trInclDepGraph() [2/2]
virtual QCString TranslatorSpanish::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 828 of file translator_es.h.
    {
      return "Dependencia grfica adjunta para "+fName+":";
    }
trIncludesFileIn() [1/2]
virtual QCString TranslatorSpanish::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1848 of file translator_es.h.
    {
      return "Incluye ficheros en "+name;
    }
References setup::name.
trIncludesFileIn() [2/2]
virtual QCString TranslatorSpanish::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1848 of file translator_es.h.
    {
      return "Incluye ficheros en "+name;
    }
References setup::name.
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorSpanish::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 136 of file translator_es.h.
    { return ", incluyendo todos los heredados:"; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorSpanish::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 136 of file translator_es.h.
    { return ", incluyendo todos los heredados:"; }
trInheritedByList() [1/2]
virtual QCString TranslatorSpanish::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 687 of file translator_es.h.
    {
      return "Heredado por "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorSpanish::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 687 of file translator_es.h.
    {
      return "Heredado por "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom() [1/2]
virtual QCString TranslatorSpanish::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1951 of file translator_es.h.
    { return QCString(members)+" heredados desde "+what; }
trInheritedFrom() [2/2]
virtual QCString TranslatorSpanish::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1951 of file translator_es.h.
    { return QCString(members)+" heredados desde "+what; }
trInheritsList() [1/2]
virtual QCString TranslatorSpanish::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 679 of file translator_es.h.
    {
      return "Herencias "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorSpanish::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 679 of file translator_es.h.
    {
      return "Herencias "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorSpanish::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 870 of file translator_es.h.
    {
      return "Valor inicial:";
    }
trInitialValue() [2/2]
virtual QCString TranslatorSpanish::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 870 of file translator_es.h.
    {
      return "Valor inicial:";
    }
trInstanceMethods() [1/2]
virtual QCString TranslatorSpanish::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 2003 of file translator_es.h.
    {
      return "Mtodos de instancia";
    }
trInstanceMethods() [2/2]
virtual QCString TranslatorSpanish::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 2003 of file translator_es.h.
    {
      return "Mtodos de instancia";
    }
trInterfaceDocumentation() [1/2]
virtual QCString TranslatorSpanish::trInterfaceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2236 of file translator_es.h.
    {
        return "Documentacin de interfaz";
    }
trInterfaceDocumentation() [2/2]
virtual QCString TranslatorSpanish::trInterfaceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2236 of file translator_es.h.
    {
        return "Documentacin de interfaz";
    }
trInterfaceHierarchy() [1/2]
virtual QCString TranslatorSpanish::trInterfaceHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2228 of file translator_es.h.
    {
        return "Jerarqua de interfaces";
    }
trInterfaceHierarchy() [2/2]
virtual QCString TranslatorSpanish::trInterfaceHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2228 of file translator_es.h.
    {
        return "Jerarqua de interfaces";
    }
trInterfaceHierarchyDescription() [1/2]
virtual QCString TranslatorSpanish::trInterfaceHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2232 of file translator_es.h.
    {
        return "Este listado de herencia est ordenado de forma aproximada, pero no completamente en orden alfabtico:";
    }
trInterfaceHierarchyDescription() [2/2]
virtual QCString TranslatorSpanish::trInterfaceHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2232 of file translator_es.h.
    {
        return "Este listado de herencia est ordenado de forma aproximada, pero no completamente en orden alfabtico:";
    }
trInterfaceIndex() [1/2]
virtual QCString TranslatorSpanish::trInterfaceIndex () [inline], [virtual]
Implements Translator.
Definition at line 2216 of file translator_es.h.
    {
        return "Indice de interfaces";
    }
trInterfaceIndex() [2/2]
virtual QCString TranslatorSpanish::trInterfaceIndex () [inline], [virtual]
Implements Translator.
Definition at line 2216 of file translator_es.h.
    {
        return "Indice de interfaces";
    }
trInterfaceList() [1/2]
virtual QCString TranslatorSpanish::trInterfaceList () [inline], [virtual]
Implements Translator.
Definition at line 2220 of file translator_es.h.
    {
        return "Lista de interfaces";
    }
trInterfaceList() [2/2]
virtual QCString TranslatorSpanish::trInterfaceList () [inline], [virtual]
Implements Translator.
Definition at line 2220 of file translator_es.h.
    {
        return "Lista de interfaces";
    }
trInterfaceListDescription() [1/2]
virtual QCString TranslatorSpanish::trInterfaceListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2224 of file translator_es.h.
    {
        return "Aqu estn las interfaces con una breve descripcin:";
    }
trInterfaceListDescription() [2/2]
virtual QCString TranslatorSpanish::trInterfaceListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2224 of file translator_es.h.
    {
        return "Aqu estn las interfaces con una breve descripcin:";
    }
trInterfaces() [1/2]
virtual QCString TranslatorSpanish::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 2020 of file translator_es.h.
    { return "Interface exportada"; }
trInterfaces() [2/2]
virtual QCString TranslatorSpanish::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 2020 of file translator_es.h.
    { return "Interface exportada"; }
trInvariant() [1/2]
virtual QCString TranslatorSpanish::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 864 of file translator_es.h.
    {
      return "Invariante";
    }
trInvariant() [2/2]
virtual QCString TranslatorSpanish::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 864 of file translator_es.h.
    {
      return "Invariante";
    }
trISOLang() [1/2]
virtual QCString TranslatorSpanish::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 71 of file translator_es.h.
    {
      return "es";
    }
trISOLang() [2/2]
virtual QCString TranslatorSpanish::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 71 of file translator_es.h.
    {
      return "es";
    }
trLegend() [1/2]
virtual QCString TranslatorSpanish::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1086 of file translator_es.h.
    {
      return "significado de colores y flechas";
    }
trLegend() [2/2]
virtual QCString TranslatorSpanish::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1086 of file translator_es.h.
    {
      return "significado de colores y flechas";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorSpanish::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 1021 of file translator_es.h.
    {
      return
        "Esta pgina explica como interpretar los grficos que son generados "
        "por doxygen.<p>\n"
        "Considere el siguiente ejemplo:\n"
        "\\code\n"
        "/*! Clase invisible por truncamiento */\n"
        "class Invisible { };\n\n"
        "/*! Clase truncada, relacin de herencia escondida */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Clase no documentada con comentarios de doxygen */\n"
        "class Undocumented { };\n\n"
        "/*! Clase que es heredera usando herencia publica */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! Clase plantilla */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Clase que es heredera usando herencia protegida */\n"
        "class ProtectedBase { };\n\n"
        "/*! Clase que es heredera usando herencia privada */\n"
        "class PrivateBase { };\n\n"
        "/*! Clase que es usada por la clase heredada */\n"
        "class Used { };\n\n"
        "/*! Super-Clase que hereda de varias otras clases */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Dar como resultado el siguiente grfico:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        "Las cajas en el grfico arriba tienen el siguiente significado:\n"
        "</p>\n"
        "<ul>\n"
        "<li>Una caja llena gris representa la estructura o clase para la cul"
        "se gener el grfico.\n"
        "<li>Una caja con borde negro seala una estructura o clase documentada.\n"
        "<li>Una caja con borde griz seala una estructura o clase no documentada.\n"
        "<li>una caja con borde rojo seala una estructura o clase documentada"
        " de la cul no toda las relaciones de jerarqua/contenido son "
        "mostradas. El grfico sera truncado si este no calza dentro de los "
        "lmites especificados."
        "</ul>\n"
        "<p>\n"
        "Las flechas tienen el siguiente significado:\n"
        "</p>\n"
        "<ul>\n"
        "<li>Una azul oscuro es usada para visualizar una relacin herencia publica entre dos clases.\n"
        "<li>Una flecha verde oscuro es usada para herencia protegida.\n"
        "<li>Una flecha rojo oscuro es usada para herencia privada.\n"
        "<li>Una flecha segmentada prpura se usa si la clase es contenida o "
        "usada por otra clase. La flecha est etiquetada por la variable "
        "con que se accede a la clase o estructura apuntada. \n"
        "<li>Una flecha segmentada amarilla indica la relacin entre una instancia template y la clase template de la que se ha instanciado."
        " La flecha se etiqueta con los parmetros con que se llama al template.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorSpanish::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 1021 of file translator_es.h.
    {
      return
        "Esta pgina explica como interpretar los grficos que son generados "
        "por doxygen.<p>\n"
        "Considere el siguiente ejemplo:\n"
        "\\code\n"
        "/*! Clase invisible por truncamiento */\n"
        "class Invisible { };\n\n"
        "/*! Clase truncada, relacin de herencia escondida */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Clase no documentada con comentarios de doxygen */\n"
        "class Undocumented { };\n\n"
        "/*! Clase que es heredera usando herencia publica */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! Clase plantilla */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Clase que es heredera usando herencia protegida */\n"
        "class ProtectedBase { };\n\n"
        "/*! Clase que es heredera usando herencia privada */\n"
        "class PrivateBase { };\n\n"
        "/*! Clase que es usada por la clase heredada */\n"
        "class Used { };\n\n"
        "/*! Super-Clase que hereda de varias otras clases */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Dar como resultado el siguiente grfico:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        "Las cajas en el grfico arriba tienen el siguiente significado:\n"
        "</p>\n"
        "<ul>\n"
        "<li>Una caja llena gris representa la estructura o clase para la cul"
        "se gener el grfico.\n"
        "<li>Una caja con borde negro seala una estructura o clase documentada.\n"
        "<li>Una caja con borde griz seala una estructura o clase no documentada.\n"
        "<li>una caja con borde rojo seala una estructura o clase documentada"
        " de la cul no toda las relaciones de jerarqua/contenido son "
        "mostradas. El grfico sera truncado si este no calza dentro de los "
        "lmites especificados."
        "</ul>\n"
        "<p>\n"
        "Las flechas tienen el siguiente significado:\n"
        "</p>\n"
        "<ul>\n"
        "<li>Una azul oscuro es usada para visualizar una relacin herencia publica entre dos clases.\n"
        "<li>Una flecha verde oscuro es usada para herencia protegida.\n"
        "<li>Una flecha rojo oscuro es usada para herencia privada.\n"
        "<li>Una flecha segmentada prpura se usa si la clase es contenida o "
        "usada por otra clase. La flecha est etiquetada por la variable "
        "con que se accede a la clase o estructura apuntada. \n"
        "<li>Una flecha segmentada amarilla indica la relacin entre una instancia template y la clase template de la que se ha instanciado."
        " La flecha se etiqueta con los parmetros con que se llama al template.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
QCString TranslatorSpanish::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 1013 of file translator_es.h.
    {
      return "Colores y flechas del Grfico";
    }
trLegendTitle() [2/2]
QCString TranslatorSpanish::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 1013 of file translator_es.h.
    {
      return "Colores y flechas del Grfico";
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorSpanish::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 124 of file translator_es.h.
    { return "Lista de todos los miembros"; }
trListOfAllMembers() [2/2]
virtual QCString TranslatorSpanish::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 124 of file translator_es.h.
    { return "Lista de todos los miembros"; }
trLoading() [1/2]
virtual QCString TranslatorSpanish::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1808 of file translator_es.h.
    {
      return "Cargando...";
    }
trLoading() [2/2]
virtual QCString TranslatorSpanish::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1808 of file translator_es.h.
    {
      return "Cargando...";
    }
trMainPage() [1/2]
virtual QCString TranslatorSpanish::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 786 of file translator_es.h.
    { return "Pgina principal"; }
trMainPage() [2/2]
virtual QCString TranslatorSpanish::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 786 of file translator_es.h.
    { return "Pgina principal"; }
trMember() [1/2]
virtual QCString TranslatorSpanish::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1289 of file translator_es.h.
    {
      QCString result((first_capital ? "Miembro" : "miembro"));
      if (!singular) result+="s";
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorSpanish::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1289 of file translator_es.h.
    {
      QCString result((first_capital ? "Miembro" : "miembro"));
      if (!singular) result+="s";
      return result;
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorSpanish::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 107 of file translator_es.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentacin de los campos";
      }
      else
      {
        return "Documentacin de los datos miembro";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorSpanish::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 107 of file translator_es.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentacin de los campos";
      }
      else
      {
        return "Documentacin de los datos miembro";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorSpanish::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 99 of file translator_es.h.
    { return "Documentacin de las enumeraciones miembro de la clase"; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorSpanish::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 99 of file translator_es.h.
    { return "Documentacin de las enumeraciones miembro de la clase"; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorSpanish::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 103 of file translator_es.h.
    { return "Documentacin de las funciones miembro"; }
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorSpanish::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 103 of file translator_es.h.
    { return "Documentacin de las funciones miembro"; }
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorSpanish::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1597 of file translator_es.h.
    { return "Documetacin de miembros Function/Subroutine"; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorSpanish::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1597 of file translator_es.h.
    { return "Documetacin de miembros Function/Subroutine"; }
trMemberList() [1/2]
virtual QCString TranslatorSpanish::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 128 of file translator_es.h.
    { return "Lista de los miembros"; }
trMemberList() [2/2]
virtual QCString TranslatorSpanish::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 128 of file translator_es.h.
    { return "Lista de los miembros"; }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorSpanish::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 95 of file translator_es.h.
    { return "Documentacin de los 'Typedef' miembros de la clase"; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorSpanish::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 95 of file translator_es.h.
    { return "Documentacin de los 'Typedef' miembros de la clase"; }
trMethodDocumentation() [1/2]
virtual QCString TranslatorSpanish::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 2010 of file translator_es.h.
    {
      return "Mtodo de documentacin";
    }
trMethodDocumentation() [2/2]
virtual QCString TranslatorSpanish::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 2010 of file translator_es.h.
    {
      return "Mtodo de documentacin";
    }
trModule() [1/2]
virtual QCString TranslatorSpanish::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1737 of file translator_es.h.
    {
      QCString result((first_capital ? "Mdulo" : "mdulo"));
      if (!singular) result+="s";
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorSpanish::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1737 of file translator_es.h.
    {
      QCString result((first_capital ? "Mdulo" : "mdulo"));
      if (!singular) result+="s";
      return result;
    }
trModuleDocumentation() [1/2]
virtual QCString TranslatorSpanish::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 378 of file translator_es.h.
    { return "Documentacin de mdulos"; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorSpanish::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 378 of file translator_es.h.
    { return "Documentacin de mdulos"; }
trModuleIndex() [1/2]
virtual QCString TranslatorSpanish::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 345 of file translator_es.h.
    { return "Indice de mdulos"; }
trModuleIndex() [2/2]
virtual QCString TranslatorSpanish::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 345 of file translator_es.h.
    { return "Indice de mdulos"; }
trModuleReference() [1/2]
virtual QCString TranslatorSpanish::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1699 of file translator_es.h.
    {
      QCString result="Referencia mdulo ";
      result+=namespaceName;
      return result;
    }
trModuleReference() [2/2]
virtual QCString TranslatorSpanish::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1699 of file translator_es.h.
    {
      QCString result="Referencia mdulo ";
      result+=namespaceName;
      return result;
    }
trModules() [1/2]
virtual QCString TranslatorSpanish::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 166 of file translator_es.h.
    { return "Mdulos"; }
trModules() [2/2]
virtual QCString TranslatorSpanish::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 166 of file translator_es.h.
    { return "Mdulos"; }
trModulesDescription() [1/2]
virtual QCString TranslatorSpanish::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 333 of file translator_es.h.
    { return "Lista de todos los mdulos:"; }
trModulesDescription() [2/2]
virtual QCString TranslatorSpanish::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 333 of file translator_es.h.
    { return "Lista de todos los mdulos:"; }
trModulesIndex() [1/2]
virtual QCString TranslatorSpanish::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1730 of file translator_es.h.
    { return "ndice de mdulos"; }
trModulesIndex() [2/2]
virtual QCString TranslatorSpanish::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1730 of file translator_es.h.
    { return "ndice de mdulos"; }
trModulesList() [1/2]
virtual QCString TranslatorSpanish::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1664 of file translator_es.h.
    { return "Lista de mdulos"; }
trModulesList() [2/2]
virtual QCString TranslatorSpanish::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1664 of file translator_es.h.
    { return "Lista de mdulos"; }
trModulesListDescription() [1/2]
virtual QCString TranslatorSpanish::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1668 of file translator_es.h.
    {
      QCString result="Lista de todos los mdulos ";
      if (!extractAll) result+="documentados ";
      result+="con una breve descripcin:";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorSpanish::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1668 of file translator_es.h.
    {
      QCString result="Lista de todos los mdulos ";
      if (!extractAll) result+="documentados ";
      result+="con una breve descripcin:";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorSpanish::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1711 of file translator_es.h.
    {
      QCString result="Lista de todos los miembros del mdulo ";
      if (!extractAll) result+="documentados ";
      result+="con enlaces ";
      if (extractAll)
      {
        result+="a la documentacin del mdulo para cada uno:";
      }
      else
      {
        result+="al mdulo al que pertenecen:";
      }
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorSpanish::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1711 of file translator_es.h.
    {
      QCString result="Lista de todos los miembros del mdulo ";
      if (!extractAll) result+="documentados ";
      result+="con enlaces ";
      if (extractAll)
      {
        result+="a la documentacin del mdulo para cada uno:";
      }
      else
      {
        result+="al mdulo al que pertenecen:";
      }
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorSpanish::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1707 of file translator_es.h.
    { return "Miembros mdulo"; }
trModulesMembers() [2/2]
virtual QCString TranslatorSpanish::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1707 of file translator_es.h.
    { return "Miembros mdulo"; }
trMonth() [1/2]
virtual QCString TranslatorSpanish::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1890 of file translator_es.h.
    {
      static const char *months_short[] = { "ene.", "feb.", "mar.", "abr.", "may.", "jun.", "jul.", "ago.", "sep.", "oct.", "nov.", "dic." };
      static const char *months_full[] = { "enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMonth() [2/2]
virtual QCString TranslatorSpanish::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1890 of file translator_es.h.
    {
      static const char *months_short[] = { "ene.", "feb.", "mar.", "abr.", "may.", "jun.", "jul.", "ago.", "sep.", "oct.", "nov.", "dic." };
      static const char *months_full[] = { "enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore() [1/2]
virtual QCString TranslatorSpanish::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 120 of file translator_es.h.
    { return "Ms..."; }
trMore() [2/2]
virtual QCString TranslatorSpanish::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 120 of file translator_es.h.
    { return "Ms..."; }
trNamespace() [1/2]
virtual QCString TranslatorSpanish::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1256 of file translator_es.h.
    {
      QCString result((first_capital ? "Namespace" : "namespace"));
      if (!singular) result+="s";
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorSpanish::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1256 of file translator_es.h.
    {
      QCString result((first_capital ? "Namespace" : "namespace"));
      if (!singular) result+="s";
      return result;
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorSpanish::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 733 of file translator_es.h.
    { return "Documentacin de namespaces"; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorSpanish::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 733 of file translator_es.h.
    { return "Documentacin de namespaces"; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorSpanish::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 727 of file translator_es.h.
    { return "Indice de namespaces"; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorSpanish::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 727 of file translator_es.h.
    { return "Indice de namespaces"; }
trNamespaceList() [1/2]
virtual QCString TranslatorSpanish::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 551 of file translator_es.h.
    { return "Lista de 'namespaces'"; }
trNamespaceList() [2/2]
virtual QCString TranslatorSpanish::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 551 of file translator_es.h.
    { return "Lista de 'namespaces'"; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorSpanish::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 555 of file translator_es.h.
    {
      QCString result="Lista de ";
      if (!extractAll) result+="toda la documentacin de ";
      result+="los 'namespaces', con una breve descripcin:";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorSpanish::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 555 of file translator_es.h.
    {
      QCString result="Lista de ";
      if (!extractAll) result+="toda la documentacin de ";
      result+="los 'namespaces', con una breve descripcin:";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorSpanish::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 713 of file translator_es.h.
    {
      QCString result="Lista de ";
      if (!extractAll) result+="toda la documentacin de ";
      result+="los miembros del namespace con enlace a ";
      if (extractAll)
        result+="los namespace de cada miembro:";
      else
        result+="la documentacin de los namespaces pertenecientes a:";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorSpanish::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 713 of file translator_es.h.
    {
      QCString result="Lista de ";
      if (!extractAll) result+="toda la documentacin de ";
      result+="los miembros del namespace con enlace a ";
      if (extractAll)
        result+="los namespace de cada miembro:";
      else
        result+="la documentacin de los namespaces pertenecientes a:";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorSpanish::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 709 of file translator_es.h.
    { return "Miembros del Namespace "; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorSpanish::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 709 of file translator_es.h.
    { return "Miembros del Namespace "; }
trNamespaceReference() [1/2]
virtual QCString TranslatorSpanish::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 614 of file translator_es.h.
    {
      QCString result="Referencia del Namespace ";
      result+=namespaceName;
      return result;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorSpanish::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 614 of file translator_es.h.
    {
      QCString result="Referencia del Namespace ";
      result+=namespaceName;
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorSpanish::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 743 of file translator_es.h.
    { return "Namespaces"; }
trNamespaces() [2/2]
virtual QCString TranslatorSpanish::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 743 of file translator_es.h.
    { return "Namespaces"; }
trNoMatches() [1/2]
virtual QCString TranslatorSpanish::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1826 of file translator_es.h.
    {
      return "Nada coincide";
    }
trNoMatches() [2/2]
virtual QCString TranslatorSpanish::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1826 of file translator_es.h.
    {
      return "Nada coincide";
    }
trNote() [1/2]
virtual QCString TranslatorSpanish::trNote () [inline], [virtual]
Implements Translator.
Definition at line 905 of file translator_es.h.
    {
      return "Nota";
    }
trNote() [2/2]
virtual QCString TranslatorSpanish::trNote () [inline], [virtual]
Implements Translator.
Definition at line 905 of file translator_es.h.
    {
      return "Nota";
    }
trOperationDocumentation() [1/2]
virtual QCString TranslatorSpanish::trOperationDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2306 of file translator_es.h.
    {
        return "Documentacin de operacin";
    }
trOperationDocumentation() [2/2]
virtual QCString TranslatorSpanish::trOperationDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2306 of file translator_es.h.
    {
        return "Documentacin de operacin";
    }
trOperations() [1/2]
virtual QCString TranslatorSpanish::trOperations () [inline], [virtual]
Implements Translator.
Definition at line 2302 of file translator_es.h.
    {
        return "Operaciones";
    }
trOperations() [2/2]
virtual QCString TranslatorSpanish::trOperations () [inline], [virtual]
Implements Translator.
Definition at line 2302 of file translator_es.h.
    {
        return "Operaciones";
    }
trOverloadText() [1/2]
virtual QCString TranslatorSpanish::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1563 of file translator_es.h.
    {
       return "Esta es una funcin miembro sobrecargada que se "
               "suministra por conveniencia. Difiere de la anterior "
               "funcin solamente en los argumentos que acepta.";
    }
trOverloadText() [2/2]
virtual QCString TranslatorSpanish::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1563 of file translator_es.h.
    {
       return "Esta es una funcin miembro sobrecargada que se "
               "suministra por conveniencia. Difiere de la anterior "
               "funcin solamente en los argumentos que acepta.";
    }
trPackage() [1/2]
virtual QCString TranslatorSpanish::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1141 of file translator_es.h.
    {
      return "Paquetes "+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorSpanish::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1141 of file translator_es.h.
    {
      return "Paquetes "+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorSpanish::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1427 of file translator_es.h.
    {
      return "Atributos del 'package'";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorSpanish::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1427 of file translator_es.h.
    {
      return "Atributos del 'package'";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorSpanish::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1407 of file translator_es.h.
    {
      return "Funciones del 'package'";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorSpanish::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1407 of file translator_es.h.
    {
      return "Funciones del 'package'";
    }
trPackageListDescription() [1/2]
virtual QCString TranslatorSpanish::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1148 of file translator_es.h.
    {
      return "Aqu van los paquetes con una breve descripcin (si et disponible):";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorSpanish::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1148 of file translator_es.h.
    {
      return "Aqu van los paquetes con una breve descripcin (si et disponible):";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorSpanish::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1411 of file translator_es.h.
    {
      return "Miembros del 'package'";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorSpanish::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1411 of file translator_es.h.
    {
      return "Miembros del 'package'";
    }
trPackages() [1/2]
virtual QCString TranslatorSpanish::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1154 of file translator_es.h.
    {
      return "Paquetes";
    }
trPackages() [2/2]
virtual QCString TranslatorSpanish::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1154 of file translator_es.h.
    {
      return "Paquetes";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorSpanish::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1399 of file translator_es.h.
    {
      return "Tipos del 'package'";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorSpanish::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1399 of file translator_es.h.
    {
      return "Tipos del 'package'";
    }
trPage() [1/2]
virtual QCString TranslatorSpanish::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1278 of file translator_es.h.
    {
      QCString result((first_capital ? "Pgina" : "pgina"));
      if (!singular) result+="s";
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorSpanish::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1278 of file translator_es.h.
    {
      QCString result((first_capital ? "Pgina" : "pgina"));
      if (!singular) result+="s";
      return result;
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorSpanish::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 792 of file translator_es.h.
    { return "p."; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorSpanish::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 792 of file translator_es.h.
    { return "p."; }
trPageIndex() [1/2]
virtual QCString TranslatorSpanish::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 896 of file translator_es.h.
    {
      return "Pgina indice";
    }
trPageIndex() [2/2]
virtual QCString TranslatorSpanish::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 896 of file translator_es.h.
    {
      return "Pgina indice";
    }
trPanelSynchronisationTooltip() [1/2]
virtual QCString TranslatorSpanish::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1968 of file translator_es.h.
    {
      QCString opt = enable ? "habilitar" : "deshabilitar";
      return "click en "+opt+" sincronizacin";
    }
trPanelSynchronisationTooltip() [2/2]
virtual QCString TranslatorSpanish::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1968 of file translator_es.h.
    {
      QCString opt = enable ? "habilitar" : "deshabilitar";
      return "click en "+opt+" sincronizacin";
    }
trParameters() [1/2]
virtual QCString TranslatorSpanish::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 535 of file translator_es.h.
    { return "Parmetros"; }
trParameters() [2/2]
virtual QCString TranslatorSpanish::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 535 of file translator_es.h.
    { return "Parmetros"; }
trPostcondition() [1/2]
virtual QCString TranslatorSpanish::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 858 of file translator_es.h.
    {
      return "Postcondicin";
    }
trPostcondition() [2/2]
virtual QCString TranslatorSpanish::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 858 of file translator_es.h.
    {
      return "Postcondicin";
    }
trPrecondition() [1/2]
virtual QCString TranslatorSpanish::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 852 of file translator_es.h.
    {
      return "Precondicin";
    }
trPrecondition() [2/2]
virtual QCString TranslatorSpanish::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 852 of file translator_es.h.
    {
      return "Precondicin";
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorSpanish::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 952 of file translator_es.h.
    {
      return "Atributos privados";
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorSpanish::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 952 of file translator_es.h.
    {
      return "Atributos privados";
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorSpanish::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 642 of file translator_es.h.
    { return "Mtodos privados"; }
trPrivateMembers() [2/2]
virtual QCString TranslatorSpanish::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 642 of file translator_es.h.
    { return "Mtodos privados"; }
trPrivateSlots() [1/2]
virtual QCString TranslatorSpanish::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 645 of file translator_es.h.
    { return "Slots privados"; }
trPrivateSlots() [2/2]
virtual QCString TranslatorSpanish::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 645 of file translator_es.h.
    { return "Slots privados"; }
trPrivateTypes() [1/2]
virtual QCString TranslatorSpanish::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 947 of file translator_es.h.
    {
      return "Tipos privados";
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorSpanish::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 947 of file translator_es.h.
    {
      return "Tipos privados";
    }
trProperties() [1/2]
virtual QCString TranslatorSpanish::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1112 of file translator_es.h.
    {
      return "Propiedades";
    }
trProperties() [2/2]
virtual QCString TranslatorSpanish::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1112 of file translator_es.h.
    {
      return "Propiedades";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorSpanish::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1118 of file translator_es.h.
    {
      return "Documentacin de propiedades";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorSpanish::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1118 of file translator_es.h.
    {
      return "Documentacin de propiedades";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorSpanish::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 937 of file translator_es.h.
    {
      return "Atributos protegidos";
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorSpanish::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 937 of file translator_es.h.
    {
      return "Atributos protegidos";
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorSpanish::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 633 of file translator_es.h.
    { return "Mtodos protegidos"; }
trProtectedMembers() [2/2]
virtual QCString TranslatorSpanish::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 633 of file translator_es.h.
    { return "Mtodos protegidos"; }
trProtectedSlots() [1/2]
virtual QCString TranslatorSpanish::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 636 of file translator_es.h.
    { return "Slots protegidos"; }
trProtectedSlots() [2/2]
virtual QCString TranslatorSpanish::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 636 of file translator_es.h.
    { return "Slots protegidos"; }
trProtectedTypes() [1/2]
virtual QCString TranslatorSpanish::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 932 of file translator_es.h.
    {
      return "Tipos protegidos";
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorSpanish::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 932 of file translator_es.h.
    {
      return "Tipos protegidos";
    }
trProvidedByCategory() [1/2]
virtual QCString TranslatorSpanish::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1978 of file translator_es.h.
    {
      return "Proporcionado por categora @0.";
    }
trProvidedByCategory() [2/2]
virtual QCString TranslatorSpanish::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1978 of file translator_es.h.
    {
      return "Proporcionado por categora @0.";
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorSpanish::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 915 of file translator_es.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Campos de datos";
      }
      else
      {
        return "Atributos pblicos";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorSpanish::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 915 of file translator_es.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Campos de datos";
      }
      else
      {
        return "Atributos pblicos";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorSpanish::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 621 of file translator_es.h.
    { return "Mtodos pblicos"; }
trPublicMembers() [2/2]
virtual QCString TranslatorSpanish::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 621 of file translator_es.h.
    { return "Mtodos pblicos"; }
trPublicSlots() [1/2]
virtual QCString TranslatorSpanish::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 624 of file translator_es.h.
    { return "Slots pblicos"; }
trPublicSlots() [2/2]
virtual QCString TranslatorSpanish::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 624 of file translator_es.h.
    { return "Slots pblicos"; }
trPublicTypes() [1/2]
virtual QCString TranslatorSpanish::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 910 of file translator_es.h.
    {
      return "Tipos pblicos";
    }
trPublicTypes() [2/2]
virtual QCString TranslatorSpanish::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 910 of file translator_es.h.
    {
      return "Tipos pblicos";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorSpanish::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 982 of file translator_es.h.
    {
      return "Referenciado por";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorSpanish::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 982 of file translator_es.h.
    {
      return "Referenciado por";
    }
trReferenceManual() [1/2]
virtual QCString TranslatorSpanish::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 413 of file translator_es.h.
    { return "Manual de referencia"; }
trReferenceManual() [2/2]
virtual QCString TranslatorSpanish::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 413 of file translator_es.h.
    { return "Manual de referencia"; }
trReferences() [1/2]
virtual QCString TranslatorSpanish::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1326 of file translator_es.h.
    {
      return "Hace referencia a";
    }
trReferences() [2/2]
virtual QCString TranslatorSpanish::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1326 of file translator_es.h.
    {
      return "Hace referencia a";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorSpanish::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 695 of file translator_es.h.
    {
      return "Reimplementado de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorSpanish::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 695 of file translator_es.h.
    {
      return "Reimplementado de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorSpanish::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 703 of file translator_es.h.
    {
      return "Reimplementado en "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorSpanish::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 703 of file translator_es.h.
    {
      return "Reimplementado en "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorSpanish::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 576 of file translator_es.h.
    { return "Documentacin de las funciones relacionadas y clases amigas"; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorSpanish::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 576 of file translator_es.h.
    { return "Documentacin de las funciones relacionadas y clases amigas"; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorSpanish::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 83 of file translator_es.h.
    { return "Funciones relacionadas"; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorSpanish::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 83 of file translator_es.h.
    { return "Funciones relacionadas"; }
trRelatedPages() [1/2]
virtual QCString TranslatorSpanish::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 217 of file translator_es.h.
    { return "Pginas relacionadas"; }
trRelatedPages() [2/2]
virtual QCString TranslatorSpanish::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 217 of file translator_es.h.
    { return "Pginas relacionadas"; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorSpanish::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 329 of file translator_es.h.
    { return "Lista de toda la documentacin relacionada:"; }
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorSpanish::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 329 of file translator_es.h.
    { return "Lista de toda la documentacin relacionada:"; }
trRelatedSubscript() [1/2]
virtual QCString TranslatorSpanish::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 87 of file translator_es.h.
    { return "(Observar que estas no son funciones miembro.)"; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorSpanish::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 87 of file translator_es.h.
    { return "(Observar que estas no son funciones miembro.)"; }
trRemarks() [1/2]
virtual QCString TranslatorSpanish::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 987 of file translator_es.h.
    {
      return "Comentarios";
    }
trRemarks() [2/2]
virtual QCString TranslatorSpanish::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 987 of file translator_es.h.
    {
      return "Comentarios";
    }
trReturns() [1/2]
virtual QCString TranslatorSpanish::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 527 of file translator_es.h.
    { return "Devuelve"; }
trReturns() [2/2]
virtual QCString TranslatorSpanish::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 527 of file translator_es.h.
    { return "Devuelve"; }
trReturnValues() [1/2]
virtual QCString TranslatorSpanish::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 781 of file translator_es.h.
    { return "Valores devueltos"; }
trReturnValues() [2/2]
virtual QCString TranslatorSpanish::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 781 of file translator_es.h.
    { return "Valores devueltos"; }
trRTFansicp() [1/2]
virtual QCString TranslatorSpanish::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1210 of file translator_es.h.
    {
      return "1252";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorSpanish::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1210 of file translator_es.h.
    {
      return "1252";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorSpanish::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1219 of file translator_es.h.
    {
      return "0";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorSpanish::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1219 of file translator_es.h.
    {
      return "0";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorSpanish::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1225 of file translator_es.h.
    {
      return "ndice";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorSpanish::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1225 of file translator_es.h.
    {
      return "ndice";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorSpanish::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1358 of file translator_es.h.
    {
      return "Tabla de contenidos";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorSpanish::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1358 of file translator_es.h.
    {
      return "Tabla de contenidos";
    }
trSearch() [1/2]
virtual QCString TranslatorSpanish::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 225 of file translator_es.h.
    { return "Buscar"; }
trSearch() [2/2]
virtual QCString TranslatorSpanish::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 225 of file translator_es.h.
    { return "Buscar"; }
trSearching() [1/2]
virtual QCString TranslatorSpanish::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1820 of file translator_es.h.
    {
      return "Buscando...";
    }
trSearching() [2/2]
virtual QCString TranslatorSpanish::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1820 of file translator_es.h.
    {
      return "Buscando...";
    }
trSearchMatches() [1/2]
virtual QCString TranslatorSpanish::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1498 of file translator_es.h.
    {
      return "Coincidencias:";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorSpanish::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1498 of file translator_es.h.
    {
      return "Coincidencias:";
    }
trSearchResults() [1/2]
virtual QCString TranslatorSpanish::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1478 of file translator_es.h.
    {
      if (numDocuments==0)
      {
        return "Disculpe, no se encontraron documentos que coincidan con su bsqueda.";
      }
      else if (numDocuments==1)
      {
        return "Se encontr <b>1</b> documento que coincide con su bsqueda.";
      }
      else
      {
        return "Se encontraron <b>$num</b> documentos que coinciden con su bsqueda. "
                "Se muestran los mejores resultados primero.";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorSpanish::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1478 of file translator_es.h.
    {
      if (numDocuments==0)
      {
        return "Disculpe, no se encontraron documentos que coincidan con su bsqueda.";
      }
      else if (numDocuments==1)
      {
        return "Se encontr <b>1</b> documento que coincide con su bsqueda.";
      }
      else
      {
        return "Se encontraron <b>$num</b> documentos que coinciden con su bsqueda. "
                "Se muestran los mejores resultados primero.";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorSpanish::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1465 of file translator_es.h.
    {
      return "Resultados de la Bsqueda";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorSpanish::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1465 of file translator_es.h.
    {
      return "Resultados de la Bsqueda";
    }
trSeeAlso() [1/2]
virtual QCString TranslatorSpanish::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 531 of file translator_es.h.
    { return "Ver tambin"; }
trSeeAlso() [2/2]
virtual QCString TranslatorSpanish::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 531 of file translator_es.h.
    { return "Ver tambin"; }
trSequenceDocumentation() [1/2]
virtual QCString TranslatorSpanish::trSequenceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2200 of file translator_es.h.
    {
        return "Documentacin de secuencia";
    }
trSequenceDocumentation() [2/2]
virtual QCString TranslatorSpanish::trSequenceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2200 of file translator_es.h.
    {
        return "Documentacin de secuencia";
    }
trSequences() [1/2]
virtual QCString TranslatorSpanish::trSequences () [inline], [virtual]
Implements Translator.
Definition at line 2196 of file translator_es.h.
    {
        return "Secuencias";
    }
trSequences() [2/2]
virtual QCString TranslatorSpanish::trSequences () [inline], [virtual]
Implements Translator.
Definition at line 2196 of file translator_es.h.
    {
        return "Secuencias";
    }
trServiceGeneratedFromFiles() [1/2]
virtual QCString TranslatorSpanish::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 2053 of file translator_es.h.
    {
      // single is true implies a single file
      QCString result="La documentacion para este servicio "
                                "se ha generado desde ";
      if (single) result+="el siguiente fichero:"; else result+="los siguientes ficheros:";
      return result;
    }
trServiceGeneratedFromFiles() [2/2]
virtual QCString TranslatorSpanish::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 2053 of file translator_es.h.
    {
      // single is true implies a single file
      QCString result="La documentacion para este servicio "
                                "se ha generado desde ";
      if (single) result+="el siguiente fichero:"; else result+="los siguientes ficheros:";
      return result;
    }
trServiceReference() [1/2]
virtual QCString TranslatorSpanish::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 2039 of file translator_es.h.
    {
      QCString result=sName;
      result+=" Referencia servicio";
      return result;
    }
trServiceReference() [2/2]
virtual QCString TranslatorSpanish::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 2039 of file translator_es.h.
    {
      QCString result=sName;
      result+=" Referencia servicio";
      return result;
    }
trServices() [1/2]
virtual QCString TranslatorSpanish::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 2024 of file translator_es.h.
    { return "Servicios incluidos"; }
trServices() [2/2]
virtual QCString TranslatorSpanish::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 2024 of file translator_es.h.
    { return "Servicios incluidos"; }
trSignals() [1/2]
virtual QCString TranslatorSpanish::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 627 of file translator_es.h.
    { return "Seales"; }
trSignals() [2/2]
virtual QCString TranslatorSpanish::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 627 of file translator_es.h.
    { return "Seales"; }
trSince() [1/2]
virtual QCString TranslatorSpanish::trSince () [inline], [virtual]
Implements Translator.
Definition at line 1003 of file translator_es.h.
    {
      return "Desde";
    }
trSince() [2/2]
virtual QCString TranslatorSpanish::trSince () [inline], [virtual]
Implements Translator.
Definition at line 1003 of file translator_es.h.
    {
      return "Desde";
    }
trSingletonGeneratedFromFiles() [1/2]
virtual QCString TranslatorSpanish::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 2062 of file translator_es.h.
    {
      // single is true implies a single file
      QCString result="La documentacin para este singleton "
                                "se ha generado desde ";
      if (single) result+="el siguiente fichero:"; else result+="los siguientes ficheros:";
      return result;
    }
trSingletonGeneratedFromFiles() [2/2]
virtual QCString TranslatorSpanish::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 2062 of file translator_es.h.
    {
      // single is true implies a single file
      QCString result="La documentacin para este singleton "
                                "se ha generado desde ";
      if (single) result+="el siguiente fichero:"; else result+="los siguientes ficheros:";
      return result;
    }
trSingletonReference() [1/2]
virtual QCString TranslatorSpanish::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 2046 of file translator_es.h.
    {
      QCString result=sName;
      result+=" referencia Singleton";
      return result;
    }
trSingletonReference() [2/2]
virtual QCString TranslatorSpanish::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 2046 of file translator_es.h.
    {
      QCString result=sName;
      result+=" referencia Singleton";
      return result;
    }
trSliceInterfaces() [1/2]
virtual QCString TranslatorSpanish::trSliceInterfaces () [inline], [virtual]
Implements Translator.
Definition at line 2212 of file translator_es.h.
    {
        return "Interfaces";
    }
trSliceInterfaces() [2/2]
virtual QCString TranslatorSpanish::trSliceInterfaces () [inline], [virtual]
Implements Translator.
Definition at line 2212 of file translator_es.h.
    {
        return "Interfaces";
    }
trSourceFile() [1/2]
virtual QCString TranslatorSpanish::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1509 of file translator_es.h.
    {
      return "Fichero Fuente " + filename;
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorSpanish::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1509 of file translator_es.h.
    {
      return "Fichero Fuente " + filename;
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorSpanish::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1435 of file translator_es.h.
    {
      return "Atributos Estticos del 'package'";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorSpanish::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1435 of file translator_es.h.
    {
      return "Atributos Estticos del 'package'";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorSpanish::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1419 of file translator_es.h.
    {
      return "Funciones estticas del 'package'";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorSpanish::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1419 of file translator_es.h.
    {
      return "Funciones estticas del 'package'";
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorSpanish::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 957 of file translator_es.h.
    {
      return "Atributos privados estticos";
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorSpanish::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 957 of file translator_es.h.
    {
      return "Atributos privados estticos";
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorSpanish::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 648 of file translator_es.h.
    { return "Mtodos privados estticos"; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorSpanish::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 648 of file translator_es.h.
    { return "Mtodos privados estticos"; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorSpanish::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 942 of file translator_es.h.
    {
      return "Atributos protegidos estticos";
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorSpanish::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 942 of file translator_es.h.
    {
      return "Atributos protegidos estticos";
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorSpanish::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 639 of file translator_es.h.
    { return "Mtodos protegidos estticos"; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorSpanish::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 639 of file translator_es.h.
    { return "Mtodos protegidos estticos"; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorSpanish::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 927 of file translator_es.h.
    {
      return "Atributos pblicos estticos";
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorSpanish::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 927 of file translator_es.h.
    {
      return "Atributos pblicos estticos";
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorSpanish::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 630 of file translator_es.h.
    { return "Mtodos pblicos estticos"; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorSpanish::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 630 of file translator_es.h.
    { return "Mtodos pblicos estticos"; }
trStructDocumentation() [1/2]
virtual QCString TranslatorSpanish::trStructDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2256 of file translator_es.h.
    {
        return "Documentacin estructura";
    }
trStructDocumentation() [2/2]
virtual QCString TranslatorSpanish::trStructDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2256 of file translator_es.h.
    {
        return "Documentacin estructura";
    }
trStructIndex() [1/2]
virtual QCString TranslatorSpanish::trStructIndex () [inline], [virtual]
Implements Translator.
Definition at line 2244 of file translator_es.h.
    {
        return "Indice de estructuras";
    }
trStructIndex() [2/2]
virtual QCString TranslatorSpanish::trStructIndex () [inline], [virtual]
Implements Translator.
Definition at line 2244 of file translator_es.h.
    {
        return "Indice de estructuras";
    }
trStructList() [1/2]
virtual QCString TranslatorSpanish::trStructList () [inline], [virtual]
Implements Translator.
Definition at line 2248 of file translator_es.h.
    {
        return "Lista de estructuras";
    }
trStructList() [2/2]
virtual QCString TranslatorSpanish::trStructList () [inline], [virtual]
Implements Translator.
Definition at line 2248 of file translator_es.h.
    {
        return "Lista de estructuras";
    }
trStructListDescription() [1/2]
virtual QCString TranslatorSpanish::trStructListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2252 of file translator_es.h.
    {
        return "Aqu estn las estructuras de datos con una breve descripcin:";
    }
trStructListDescription() [2/2]
virtual QCString TranslatorSpanish::trStructListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2252 of file translator_es.h.
    {
        return "Aqu estn las estructuras de datos con una breve descripcin:";
    }
trStructs() [1/2]
virtual QCString TranslatorSpanish::trStructs () [inline], [virtual]
Implements Translator.
Definition at line 2240 of file translator_es.h.
    {
        return "Estructuras";
    }
trStructs() [2/2]
virtual QCString TranslatorSpanish::trStructs () [inline], [virtual]
Implements Translator.
Definition at line 2240 of file translator_es.h.
    {
        return "Estructuras";
    }
trSubprogram() [1/2]
virtual QCString TranslatorSpanish::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1784 of file translator_es.h.
    {
      QCString result((first_capital ? "Subprograma" : "subprograma"));
      if (!singular) result+="s";
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorSpanish::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1784 of file translator_es.h.
    {
      QCString result((first_capital ? "Subprograma" : "subprograma"));
      if (!singular) result+="s";
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorSpanish::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1654 of file translator_es.h.
    { return "Documentacin de Funciones/Subprogramas"; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorSpanish::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1654 of file translator_es.h.
    { return "Documentacin de Funciones/Subprogramas"; }
trSubprograms() [1/2]
virtual QCString TranslatorSpanish::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1648 of file translator_es.h.
    { return "Funciones/Subprogramas"; }
trSubprograms() [2/2]
virtual QCString TranslatorSpanish::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1648 of file translator_es.h.
    { return "Funciones/Subprogramas"; }
trTemplateParameters() [1/2]
virtual QCString TranslatorSpanish::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1929 of file translator_es.h.
    { return "Parmetros del template"; }
trTemplateParameters() [2/2]
virtual QCString TranslatorSpanish::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1929 of file translator_es.h.
    { return "Parmetros del template"; }
trTest() [1/2]
virtual QCString TranslatorSpanish::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1096 of file translator_es.h.
    {
      return "Prueba";
    }
trTest() [2/2]
virtual QCString TranslatorSpanish::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1096 of file translator_es.h.
    {
      return "Prueba";
    }
trTestList() [1/2]
virtual QCString TranslatorSpanish::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1102 of file translator_es.h.
    {
      return "Lista de pruebas";
    }
trTestList() [2/2]
virtual QCString TranslatorSpanish::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1102 of file translator_es.h.
    {
      return "Lista de pruebas";
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorSpanish::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 132 of file translator_es.h.
    { return "Lista completa de los miembros de "; }
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorSpanish::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 132 of file translator_es.h.
    { return "Lista completa de los miembros de "; }
trTodo() [1/2]
virtual QCString TranslatorSpanish::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 967 of file translator_es.h.
    {
      return "Tareas pendientes";
    }
trTodo() [2/2]
virtual QCString TranslatorSpanish::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 967 of file translator_es.h.
    {
      return "Tareas pendientes";
    }
trTodoList() [1/2]
virtual QCString TranslatorSpanish::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 973 of file translator_es.h.
    {
      return "Lista de tareas pendientes";
    }
trTodoList() [2/2]
virtual QCString TranslatorSpanish::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 973 of file translator_es.h.
    {
      return "Lista de tareas pendientes";
    }
trType() [1/2]
virtual QCString TranslatorSpanish::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1773 of file translator_es.h.
    {
      QCString result((first_capital ? "Tipo" : "tipo"));
      if (!singular) result+="s";
      return result;
    }
trType() [2/2]
virtual QCString TranslatorSpanish::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1773 of file translator_es.h.
    {
      QCString result((first_capital ? "Tipo" : "tipo"));
      if (!singular) result+="s";
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorSpanish::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1792 of file translator_es.h.
    {
      return "Restriciones de tipo";
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorSpanish::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1792 of file translator_es.h.
    {
      return "Restriciones de tipo";
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorSpanish::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 461 of file translator_es.h.
    { return "Documentacin de los 'typedefs'"; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorSpanish::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 461 of file translator_es.h.
    { return "Documentacin de los 'typedefs'"; }
trTypedefs() [1/2]
virtual QCString TranslatorSpanish::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 425 of file translator_es.h.
    { return "typedefs"; }
trTypedefs() [2/2]
virtual QCString TranslatorSpanish::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 425 of file translator_es.h.
    { return "typedefs"; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorSpanish::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1642 of file translator_es.h.
    { return "Documentacin de tipos de datos"; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorSpanish::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1642 of file translator_es.h.
    { return "Documentacin de tipos de datos"; }
trVariableDocumentation() [1/2]
virtual QCString TranslatorSpanish::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 479 of file translator_es.h.
    { return "Documentacin de las variables"; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorSpanish::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 479 of file translator_es.h.
    { return "Documentacin de las variables"; }
trVariables() [1/2]
virtual QCString TranslatorSpanish::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 443 of file translator_es.h.
    { return "Variables"; }
trVariables() [2/2]
virtual QCString TranslatorSpanish::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 443 of file translator_es.h.
    { return "Variables"; }
trVersion() [1/2]
virtual QCString TranslatorSpanish::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 519 of file translator_es.h.
    { return "Versin"; }
trVersion() [2/2]
virtual QCString TranslatorSpanish::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 519 of file translator_es.h.
    { return "Versin"; }
trVhdlType() [1/2]
virtual QCString TranslatorSpanish::trVhdlType (uint64 type, bool single) [inline], [virtual]
VHDL type
Implements Translator.
Definition at line 2100 of file translator_es.h.
    {
      switch(type)
      {
        case VhdlDocGen::LIBRARY:
          if (single) return "Libreria";
          else return "Librerias";
        case VhdlDocGen::PACKAGE:
          if (single) return "Paquete";
          else return "Paquetes";
        case VhdlDocGen::SIGNAL:
          if (single) return "Seal";
          else return "Seales";
        case VhdlDocGen::COMPONENT:
          if (single) return "Componente";
          else return "Componentes";
        case VhdlDocGen::CONSTANT:
          if (single) return "Constante";
          else return "Constantes";
        case VhdlDocGen::ENTITY:
          if (single) return "Entidad";
          else return "Entidades";
        case VhdlDocGen::TYPE:
          if (single) return "Tipo";
          else return "Tipos";
        case VhdlDocGen::SUBTYPE:
          if (single) return "Subtipo";
          else return "Subtipos";
        case VhdlDocGen::FUNCTION:
          if (single) return "Funcin";
          else return "Funciones";
        case VhdlDocGen::RECORD:
          if (single) return "Registro";
          else return "Registros";
        case VhdlDocGen::PROCEDURE:
          if (single) return "Procedimiento";
          else return "Procedimientos";
        case VhdlDocGen::ARCHITECTURE:
          if (single) return "Arquitectura";
          else return "Arquitecturas";
        case VhdlDocGen::ATTRIBUTE:
          if (single) return "Atributo";
          else return "Atributos";
        case VhdlDocGen::PROCESS:
          if (single) return "Proceso";
          else return "Procesos";
        case VhdlDocGen::PORT:
          if (single) return "Puerto";
          else return "Puertos";
        case VhdlDocGen::USE:
          if (single) return "clusula de uso";
          else return "Clusulas de uso";
        case VhdlDocGen::GENERIC:
          if (single) return "Genrico";
          else return "Genricos";
        case VhdlDocGen::PACKAGE_BODY:
          return "Cuerpo del paquete";
        case VhdlDocGen::UNITS:
          return "Unidades";
        case VhdlDocGen::SHAREDVARIABLE:
          if (single) return "Variable Compartida";
          else return "Variable Compartidas";
        case VhdlDocGen::VFILE:
          if (single) return "Fichero";
          else return "Ficheros";
        case VhdlDocGen::GROUP:
          if (single) return "Grupo";
          else return "Grupos";
        case VhdlDocGen::INSTANTIATION:
          if (single) return "Instanciacin";
          else return "Instanciaciones";
        case VhdlDocGen::ALIAS:
          if (single) return "Alias";
          else return "Aliases";
        case VhdlDocGen::CONFIG:
          if (single) return "Configuracin";
          else return "Configuraciones";
        case VhdlDocGen::MISCELLANEOUS:
          return "Varios";
        case VhdlDocGen::UCF_CONST:
          return "Restricciones";
        default:
          return "Clase";
      }
    }
References VhdlDocGen::ALIAS, VhdlDocGen::ARCHITECTURE, VhdlDocGen::ATTRIBUTE, VhdlDocGen::COMPONENT, VhdlDocGen::CONFIG, VhdlDocGen::CONSTANT, VhdlDocGen::ENTITY, VhdlDocGen::FUNCTION, VhdlDocGen::GENERIC, VhdlDocGen::GROUP, VhdlDocGen::INSTANTIATION, VhdlDocGen::LIBRARY, VhdlDocGen::MISCELLANEOUS, VhdlDocGen::PACKAGE, VhdlDocGen::PACKAGE_BODY, VhdlDocGen::PORT, VhdlDocGen::PROCEDURE, VhdlDocGen::PROCESS, VhdlDocGen::RECORD, VhdlDocGen::SHAREDVARIABLE, VhdlDocGen::SIGNAL, VhdlDocGen::SUBTYPE, VhdlDocGen::TYPE, VhdlDocGen::UCF_CONST, VhdlDocGen::UNITS, VhdlDocGen::USE, and VhdlDocGen::VFILE.
trVhdlType() [2/2]
virtual QCString TranslatorSpanish::trVhdlType (uint64 type, bool single) [inline], [virtual]
VHDL type
Implements Translator.
Definition at line 2100 of file translator_es.h.
    {
      switch(type)
      {
        case VhdlDocGen::LIBRARY:
          if (single) return "Libreria";
          else return "Librerias";
        case VhdlDocGen::PACKAGE:
          if (single) return "Paquete";
          else return "Paquetes";
        case VhdlDocGen::SIGNAL:
          if (single) return "Seal";
          else return "Seales";
        case VhdlDocGen::COMPONENT:
          if (single) return "Componente";
          else return "Componentes";
        case VhdlDocGen::CONSTANT:
          if (single) return "Constante";
          else return "Constantes";
        case VhdlDocGen::ENTITY:
          if (single) return "Entidad";
          else return "Entidades";
        case VhdlDocGen::TYPE:
          if (single) return "Tipo";
          else return "Tipos";
        case VhdlDocGen::SUBTYPE:
          if (single) return "Subtipo";
          else return "Subtipos";
        case VhdlDocGen::FUNCTION:
          if (single) return "Funcin";
          else return "Funciones";
        case VhdlDocGen::RECORD:
          if (single) return "Registro";
          else return "Registros";
        case VhdlDocGen::PROCEDURE:
          if (single) return "Procedimiento";
          else return "Procedimientos";
        case VhdlDocGen::ARCHITECTURE:
          if (single) return "Arquitectura";
          else return "Arquitecturas";
        case VhdlDocGen::ATTRIBUTE:
          if (single) return "Atributo";
          else return "Atributos";
        case VhdlDocGen::PROCESS:
          if (single) return "Proceso";
          else return "Procesos";
        case VhdlDocGen::PORT:
          if (single) return "Puerto";
          else return "Puertos";
        case VhdlDocGen::USE:
          if (single) return "clusula de uso";
          else return "Clusulas de uso";
        case VhdlDocGen::GENERIC:
          if (single) return "Genrico";
          else return "Genricos";
        case VhdlDocGen::PACKAGE_BODY:
          return "Cuerpo del paquete";
        case VhdlDocGen::UNITS:
          return "Unidades";
        case VhdlDocGen::SHAREDVARIABLE:
          if (single) return "Variable Compartida";
          else return "Variable Compartidas";
        case VhdlDocGen::VFILE:
          if (single) return "Fichero";
          else return "Ficheros";
        case VhdlDocGen::GROUP:
          if (single) return "Grupo";
          else return "Grupos";
        case VhdlDocGen::INSTANTIATION:
          if (single) return "Instanciacin";
          else return "Instanciaciones";
        case VhdlDocGen::ALIAS:
          if (single) return "Alias";
          else return "Aliases";
        case VhdlDocGen::CONFIG:
          if (single) return "Configuracin";
          else return "Configuraciones";
        case VhdlDocGen::MISCELLANEOUS:
          return "Varios";
        case VhdlDocGen::UCF_CONST:
          return "Restricciones";
        default:
          return "Clase";
      }
    }
References VhdlDocGen::ALIAS, VhdlDocGen::ARCHITECTURE, VhdlDocGen::ATTRIBUTE, VhdlDocGen::COMPONENT, VhdlDocGen::CONFIG, VhdlDocGen::CONSTANT, VhdlDocGen::ENTITY, VhdlDocGen::FUNCTION, VhdlDocGen::GENERIC, VhdlDocGen::GROUP, VhdlDocGen::INSTANTIATION, VhdlDocGen::LIBRARY, VhdlDocGen::MISCELLANEOUS, VhdlDocGen::PACKAGE, VhdlDocGen::PACKAGE_BODY, VhdlDocGen::PORT, VhdlDocGen::PROCEDURE, VhdlDocGen::PROCESS, VhdlDocGen::RECORD, VhdlDocGen::SHAREDVARIABLE, VhdlDocGen::SIGNAL, VhdlDocGen::SUBTYPE, VhdlDocGen::TYPE, VhdlDocGen::UCF_CONST, VhdlDocGen::UNITS, VhdlDocGen::USE, and VhdlDocGen::VFILE.
trWarning() [1/2]
virtual QCString TranslatorSpanish::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 515 of file translator_es.h.
    { return "Atencin"; }
trWarning() [2/2]
virtual QCString TranslatorSpanish::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 515 of file translator_es.h.
    { return "Atencin"; }
trWriteList() [1/2]
virtual QCString TranslatorSpanish::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 654 of file translator_es.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" y ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorSpanish::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 654 of file translator_es.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" y ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_es.h
doxygen/src/translator_es.h