DocDotFile Class Reference
#include <docnode.h>
Public Member Functions
DocDotFile (DocParser *parser, DocNodeVariant *parent, const QCString &name, const QCString &context, const QCString &srcFile, int srcLine)
bool parse (DocNodeVariant *)
DocDotFile (DocParser *parser, DocNodeVariant *parent, const QCString &name, const QCString &context, const QCString &srcFile, int srcLine)
bool parse (DocNodeVariant *)
Additional Inherited Members
Detailed Description
Node representing a dot file
Definition at line 676 of file docnode.h.
Constructor & Destructor Documentation
DocDotFile() [1/2]
DocDotFile::DocDotFile (DocParser * parser, DocNodeVariant * parent, const QCString & name, const QCString & context, const QCString & srcFile, int srcLine)
Definition at line 1010 of file docnode.cpp.
                                                            :
  DocDiagramFileBase(parser,parent,name,context,srcFile,srcLine)
{
  p->relPath = parser->context.relPath;
}
References DocParser::context, DocDiagramFileBase::p, DocNode::parser(), and DocParserContext::relPath.
DocDotFile() [2/2]
DocDotFile::DocDotFile (DocParser * parser, DocNodeVariant * parent, const QCString & name, const QCString & context, const QCString & srcFile, int srcLine)
Member Function Documentation
parse() [1/2]
bool DocDotFile::parse (DocNodeVariant * thisVariant)
Definition at line 1017 of file docnode.cpp.
{
  bool ok = false;
  parser()->defaultHandleTitleAndSize(CMD_DOTFILE,thisVariant,children(),p->width,p->height);
  bool ambig;
  FileDef *fd = findFileDef(Doxygen::dotFileNameLinkedMap,p->name,ambig);
  if (fd==0 && !p->name.endsWith(".dot")) // try with .dot extension as well
  {
    fd = findFileDef(Doxygen::dotFileNameLinkedMap,p->name+".dot",ambig);
  }
  if (fd)
  {
    p->file = fd->absFilePath();
    ok = true;
    if (ambig)
    {
      warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"included dot file name %s is ambiguous.\n"
           "Possible candidates:\n%s",qPrint(p->name),
           qPrint(showFileDefMatches(Doxygen::dotFileNameLinkedMap,p->name))
          );
    }
  }
  else
  {
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"included dot file %s is not found "
           "in any of the paths specified via DOTFILE_DIRS!",qPrint(p->name));
  }
  return ok;
}
References FileDef::absFilePath(), DocCompoundNode::children(), CMD_DOTFILE, DocDiagramFileBase::context(), DocParser::defaultHandleTitleAndSize(), Doxygen::dotFileNameLinkedMap, findFileDef(), DocDiagramFileBase::p, DocNode::parser(), qPrint(), showFileDefMatches(), and warn_doc_error().
parse() [2/2]
bool DocDotFile::parse (DocNodeVariant *)
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docnode.h
doxygen/src/docnode.h
doxygen/build/doxygen/src/docnode.cpp
doxygen/src/docnode.cpp