ExpressionParser Class Reference
Recursive decent parser for Django style template expressions.
Classes
class ExprToken
Class representing a token within an expression.
Public Member Functions
ExpressionParser (const TemplateParser *parser, int line)
virtual ~ExpressionParser ()
ExprAstPtr parse (const QCString &expr)
ExpressionParser (const TemplateParser *parser, int line)
virtual ~ExpressionParser ()
ExprAstPtr parse (const QCString &expr)
Private Member Functions
ExprAstPtr parseExpression ()
ExprAstPtr parseOrExpression ()
ExprAstPtr parseAndExpression ()
ExprAstPtr parseNotExpression ()
ExprAstPtr parseCompareExpression ()
ExprAstPtr parseAdditiveExpression ()
ExprAstPtr parseMultiplicativeExpression ()
ExprAstPtr parseUnaryExpression ()
ExprAstPtr parsePrimaryExpression ()
ExprAstPtr parseNumber ()
ExprAstPtr parseIdentifier ()
ExprAstPtr parseLiteral ()
ExprAstPtr parseIdentifierOptionalArgs ()
ExprAstPtr parseFilteredVariable ()
ExprAstFilterPtr parseFilter ()
bool getNextToken ()
ExprAstPtr parseExpression ()
ExprAstPtr parseOrExpression ()
ExprAstPtr parseAndExpression ()
ExprAstPtr parseNotExpression ()
ExprAstPtr parseCompareExpression ()
ExprAstPtr parseAdditiveExpression ()
ExprAstPtr parseMultiplicativeExpression ()
ExprAstPtr parseUnaryExpression ()
ExprAstPtr parsePrimaryExpression ()
ExprAstPtr parseNumber ()
ExprAstPtr parseIdentifier ()
ExprAstPtr parseLiteral ()
ExprAstPtr parseIdentifierOptionalArgs ()
ExprAstPtr parseFilteredVariable ()
ExprAstFilterPtr parseFilter ()
bool getNextToken ()
Private Attributes
const TemplateParser * m_parser = 0
ExprToken m_curToken
int m_line = 0
const char * m_tokenStream
Detailed Description
Recursive decent parser for Django style template expressions.
Definition at line 2009 of file template.cpp.
Constructor & Destructor Documentation
ExpressionParser() [1/2]
ExpressionParser::ExpressionParser (const TemplateParser * parser, int line) [inline]
Definition at line 2012 of file template.cpp.
      : m_parser(parser), m_line(line), m_tokenStream(0)
    {
    }
 ExpressionParser() [1/2]
virtual ExpressionParser::~ExpressionParser () [inline], [virtual]
Definition at line 2016 of file template.cpp.
    {
    }
ExpressionParser() [2/2]
ExpressionParser::ExpressionParser (const TemplateParser * parser, int line) [inline]
Definition at line 2012 of file template.cpp.
      : m_parser(parser), m_line(line), m_tokenStream(0)
    {
    }
 ExpressionParser() [2/2]
virtual ExpressionParser::~ExpressionParser () [inline], [virtual]
Definition at line 2016 of file template.cpp.
    {
    }
Member Function Documentation
getNextToken() [1/2]
bool ExpressionParser::getNextToken () [inline], [private]
Definition at line 2343 of file template.cpp.
    {
      const char *p = m_tokenStream;
      char s[2];
      s[1]=0;
      if (p==0 || *p=='\0') return FALSE;
      while (*p==' ') p++; // skip over spaces
      char c=*p;
      if (*p=='\0') // only spaces...
      {
        m_tokenStream = p;
        return FALSE;
      }
      const char *q = p;
      switch (c)
      {
        case '=':
          if (c=='=' && *(p+1)=='=') // equal
          {
            m_curToken.op = Operator::Equal;
            p+=2;
          }
          break;
        case '!':
          if (c=='!' && *(p+1)=='=') // not equal
          {
            m_curToken.op = Operator::NotEqual;
            p+=2;
          }
          break;
        case '<':
          if (c=='<' && *(p+1)=='=') // less or equal
          {
            m_curToken.op = Operator::LessEqual;
            p+=2;
          }
          else // less
          {
            m_curToken.op = Operator::Less;
            p++;
          }
          break;
        case '>':
          if (c=='>' && *(p+1)=='=') // greater or equal
          {
            m_curToken.op = Operator::GreaterEqual;
            p+=2;
          }
          else // greater
          {
            m_curToken.op = Operator::Greater;
            p++;
          }
          break;
        case '(':
          m_curToken.op = Operator::LeftParen;
          p++;
          break;
        case ')':
          m_curToken.op = Operator::RightParen;
          p++;
          break;
        case '|':
          m_curToken.op = Operator::Filter;
          p++;
          break;
        case '+':
          m_curToken.op = Operator::Plus;
          p++;
          break;
        case '-':
          m_curToken.op = Operator::Minus;
          p++;
          break;
        case '*':
          m_curToken.op = Operator::Multiply;
          p++;
          break;
        case '/':
          m_curToken.op = Operator::Divide;
          p++;
          break;
        case '%':
          m_curToken.op = Operator::Modulo;
          p++;
          break;
        case ':':
          m_curToken.op = Operator::Colon;
          p++;
          break;
        case ',':
          m_curToken.op = Operator::Comma;
          p++;
          break;
        case 'n':
          if (strncmp(p,"not ",4)==0)
          {
            m_curToken.op = Operator::Not;
            p+=4;
          }
          break;
        case 'a':
          if (strncmp(p,"and ",4)==0)
          {
            m_curToken.op = Operator::And;
            p+=4;
          }
          break;
        case 'o':
          if (strncmp(p,"or ",3)==0)
          {
            m_curToken.op = Operator::Or;
            p+=3;
          }
          break;
        default:
          break;
      }
      if (p!=q) // found an operator
      {
        m_curToken.type = ExprToken::Operator;
      }
      else // no token found yet
      {
        if (c>='0' && c<='9') // number?
        {
          m_curToken.type = ExprToken::Number;
          const char *np = p;
          m_curToken.num = 0;
          while (*np>='0' && *np<='9')
          {
            m_curToken.num*=10;
            m_curToken.num+=*np-'0';
            np++;
          }
          p=np;
        }
        else if (c=='_' || (c>='a' && c<='z') || (c>='A' && c<='Z')) // identifier?
        {
          m_curToken.type = ExprToken::Identifier;
          s[0]=c;
          m_curToken.id = s;
          p++;
          while ((c=*p) &&
              (c=='_' || c=='.' ||
               (c>='a' && c<='z') ||
               (c>='A' && c<='Z') ||
               (c>='0' && c<='9'))
              )
          {
            s[0]=c;
            m_curToken.id+=s;
            p++;
          }
          if (m_curToken.id=="True") // treat true literal as numerical 1
          {
            m_curToken.type = ExprToken::Number;
            m_curToken.num = 1;
          }
          else if (m_curToken.id=="False") // treat false literal as numerical 0
          {
            m_curToken.type = ExprToken::Number;
            m_curToken.num = 0;
          }
        }
        else if (c=='"' || c=='\'') // string literal
        {
          m_curToken.type = ExprToken::Literal;
          m_curToken.id.resize(0);
          p++;
          char tokenChar = c;
          char cp=0;
          while ((c=*p) && (c!=tokenChar || (c==tokenChar && cp=='\\')))
          {
            s[0]=c;
            if (c!='\\' || cp=='\\') // don't add escapes
            {
              m_curToken.id+=s;
            }
            cp=c;
            p++;
          }
          if (*p==tokenChar) p++;
        }
      }
      if (p==q) // still no valid token found -> error
      {
        m_curToken.type = ExprToken::Unknown;
        s[0]=c;
        s[1]=0;
        warn(m_parser->templateName(),m_line,"Found unknown token '%s' (%d) while parsing %s",s,c,m_tokenStream);
        m_curToken.id = s;
        p++;
      }
      TRACE(("token type=%d op=%d num=%d id=%s\n",
          m_curToken.type,m_curToken.op,m_curToken.num,qPrint(m_curToken.id)));
      m_tokenStream = p;
      return TRUE;
    }
References Operator::And, c, Operator::Colon, Operator::Comma, Operator::Divide, Operator::Equal, FALSE, Operator::Filter, Operator::Greater, Operator::GreaterEqual, ExpressionParser::ExprToken::id, ExpressionParser::ExprToken::Identifier, Operator::LeftParen, Operator::Less, Operator::LessEqual, ExpressionParser::ExprToken::Literal, m_curToken, m_line, m_parser, m_tokenStream, Operator::Minus, Operator::Modulo, Operator::Multiply, Operator::Not, Operator::NotEqual, ExpressionParser::ExprToken::num, ExpressionParser::ExprToken::Number, ExpressionParser::ExprToken::op, ExpressionParser::ExprToken::Operator, Operator::Or, p, Operator::Plus, qPrint(), QCString::resize(), Operator::RightParen, s, TemplateParser::templateName(), TRACE, TRUE, ExpressionParser::ExprToken::type, ExpressionParser::ExprToken::Unknown, and warn().
Referenced by parse(), parseAdditiveExpression(), parseAndExpression(), parseCompareExpression(), parseFilter(), parseFilteredVariable(), parseIdentifier(), parseIdentifierOptionalArgs(), parseLiteral(), parseMultiplicativeExpression(), parseNotExpression(), parseNumber(), parseOrExpression(), parsePrimaryExpression(), and parseUnaryExpression().
getNextToken() [2/2]
bool ExpressionParser::getNextToken () [inline], [private]
Definition at line 2343 of file template.cpp.
    {
      const char *p = m_tokenStream;
      char s[2];
      s[1]=0;
      if (p==0 || *p=='\0') return FALSE;
      while (*p==' ') p++; // skip over spaces
      char c=*p;
      if (*p=='\0') // only spaces...
      {
        m_tokenStream = p;
        return FALSE;
      }
      const char *q = p;
      switch (c)
      {
        case '=':
          if (c=='=' && *(p+1)=='=') // equal
          {
            m_curToken.op = Operator::Equal;
            p+=2;
          }
          break;
        case '!':
          if (c=='!' && *(p+1)=='=') // not equal
          {
            m_curToken.op = Operator::NotEqual;
            p+=2;
          }
          break;
        case '<':
          if (c=='<' && *(p+1)=='=') // less or equal
          {
            m_curToken.op = Operator::LessEqual;
            p+=2;
          }
          else // less
          {
            m_curToken.op = Operator::Less;
            p++;
          }
          break;
        case '>':
          if (c=='>' && *(p+1)=='=') // greater or equal
          {
            m_curToken.op = Operator::GreaterEqual;
            p+=2;
          }
          else // greater
          {
            m_curToken.op = Operator::Greater;
            p++;
          }
          break;
        case '(':
          m_curToken.op = Operator::LeftParen;
          p++;
          break;
        case ')':
          m_curToken.op = Operator::RightParen;
          p++;
          break;
        case '|':
          m_curToken.op = Operator::Filter;
          p++;
          break;
        case '+':
          m_curToken.op = Operator::Plus;
          p++;
          break;
        case '-':
          m_curToken.op = Operator::Minus;
          p++;
          break;
        case '*':
          m_curToken.op = Operator::Multiply;
          p++;
          break;
        case '/':
          m_curToken.op = Operator::Divide;
          p++;
          break;
        case '%':
          m_curToken.op = Operator::Modulo;
          p++;
          break;
        case ':':
          m_curToken.op = Operator::Colon;
          p++;
          break;
        case ',':
          m_curToken.op = Operator::Comma;
          p++;
          break;
        case 'n':
          if (strncmp(p,"not ",4)==0)
          {
            m_curToken.op = Operator::Not;
            p+=4;
          }
          break;
        case 'a':
          if (strncmp(p,"and ",4)==0)
          {
            m_curToken.op = Operator::And;
            p+=4;
          }
          break;
        case 'o':
          if (strncmp(p,"or ",3)==0)
          {
            m_curToken.op = Operator::Or;
            p+=3;
          }
          break;
        default:
          break;
      }
      if (p!=q) // found an operator
      {
        m_curToken.type = ExprToken::Operator;
      }
      else // no token found yet
      {
        if (c>='0' && c<='9') // number?
        {
          m_curToken.type = ExprToken::Number;
          const char *np = p;
          m_curToken.num = 0;
          while (*np>='0' && *np<='9')
          {
            m_curToken.num*=10;
            m_curToken.num+=*np-'0';
            np++;
          }
          p=np;
        }
        else if (c=='_' || (c>='a' && c<='z') || (c>='A' && c<='Z')) // identifier?
        {
          m_curToken.type = ExprToken::Identifier;
          s[0]=c;
          m_curToken.id = s;
          p++;
          while ((c=*p) &&
              (c=='_' || c=='.' ||
               (c>='a' && c<='z') ||
               (c>='A' && c<='Z') ||
               (c>='0' && c<='9'))
              )
          {
            s[0]=c;
            m_curToken.id+=s;
            p++;
          }
          if (m_curToken.id=="True") // treat true literal as numerical 1
          {
            m_curToken.type = ExprToken::Number;
            m_curToken.num = 1;
          }
          else if (m_curToken.id=="False") // treat false literal as numerical 0
          {
            m_curToken.type = ExprToken::Number;
            m_curToken.num = 0;
          }
        }
        else if (c=='"' || c=='\'') // string literal
        {
          m_curToken.type = ExprToken::Literal;
          m_curToken.id.resize(0);
          p++;
          char tokenChar = c;
          char cp=0;
          while ((c=*p) && (c!=tokenChar || (c==tokenChar && cp=='\\')))
          {
            s[0]=c;
            if (c!='\\' || cp=='\\') // don't add escapes
            {
              m_curToken.id+=s;
            }
            cp=c;
            p++;
          }
          if (*p==tokenChar) p++;
        }
      }
      if (p==q) // still no valid token found -> error
      {
        m_curToken.type = ExprToken::Unknown;
        s[0]=c;
        s[1]=0;
        warn(m_parser->templateName(),m_line,"Found unknown token '%s' (%d) while parsing %s",s,c,m_tokenStream);
        m_curToken.id = s;
        p++;
      }
      TRACE(("token type=%d op=%d num=%d id=%s\n",
          m_curToken.type,m_curToken.op,m_curToken.num,qPrint(m_curToken.id)));
      m_tokenStream = p;
      return TRUE;
    }
References Operator::And, c, Operator::Colon, Operator::Comma, Operator::Divide, Operator::Equal, FALSE, Operator::Filter, Operator::Greater, Operator::GreaterEqual, Operator::LeftParen, Operator::Less, Operator::LessEqual, Operator::Minus, Operator::Modulo, Operator::Multiply, Operator::Not, Operator::NotEqual, Operator::Or, TemplateImmutableList::p, Operator::Plus, qPrint(), Operator::RightParen, s, TRACE, TRUE, and warn().
parse() [1/2]
ExprAstPtr ExpressionParser::parse (const QCString & expr) [inline]
Definition at line 2020 of file template.cpp.
    {
      if (expr.isEmpty()) return 0;
      m_tokenStream = expr.data();
      getNextToken();
      return parseExpression();
    }
References QCString::data(), getNextToken(), QCString::isEmpty(), m_tokenStream, and parseExpression().
Referenced by TemplateNodeCreate::TemplateNodeCreate(), TemplateNodeCycle::TemplateNodeCycle(), TemplateNodeEncoding::TemplateNodeEncoding(), TemplateNodeExtend::TemplateNodeExtend(), TemplateNodeFor::TemplateNodeFor(), TemplateNodeIf::TemplateNodeIf(), TemplateNodeInclude::TemplateNodeInclude(), TemplateNodeIndexEntry::TemplateNodeIndexEntry(), TemplateNodeMarkers::TemplateNodeMarkers(), TemplateNodeRange::TemplateNodeRange(), TemplateNodeRepeat::TemplateNodeRepeat(), TemplateNodeResource::TemplateNodeResource(), TemplateNodeSet::TemplateNodeSet(), TemplateNodeTree::TemplateNodeTree(), TemplateNodeVariable::TemplateNodeVariable(), and TemplateNodeWith::TemplateNodeWith().
parse() [2/2]
ExprAstPtr ExpressionParser::parse (const QCString & expr) [inline]
Definition at line 2020 of file template.cpp.
    {
      if (expr.isEmpty()) return 0;
      m_tokenStream = expr.data();
      getNextToken();
      return parseExpression();
    }
References QCString::data(), and QCString::isEmpty().
parseAdditiveExpression() [1/2]
ExprAstPtr ExpressionParser::parseAdditiveExpression () [inline], [private]
Definition at line 2142 of file template.cpp.
    {
      TRACE(("{parseAdditiveExpression(%s)\n",m_tokenStream));
      ExprAstPtr lhs { parseMultiplicativeExpression() };
      if (lhs)
      {
        while (m_curToken.type==ExprToken::Operator &&
               (m_curToken.op==Operator::Plus || m_curToken.op==Operator::Minus))
        {
          Operator::Type op = m_curToken.op;
          getNextToken();
          ExprAstPtr rhs { parseMultiplicativeExpression() };
          lhs = std::make_unique<ExprAstBinary>(op,std::move(lhs),std::move(rhs));
        }
      }
      TRACE(("}parseAdditiveExpression(%s)\n",m_tokenStream));
      return lhs;
    }
References getNextToken(), m_curToken, m_tokenStream, Operator::Minus, ExpressionParser::ExprToken::op, ExpressionParser::ExprToken::Operator, parseMultiplicativeExpression(), Operator::Plus, TRACE, and ExpressionParser::ExprToken::type.
Referenced by parseCompareExpression().
parseAdditiveExpression() [2/2]
ExprAstPtr ExpressionParser::parseAdditiveExpression () [inline], [private]
Definition at line 2142 of file template.cpp.
    {
      TRACE(("{parseAdditiveExpression(%s)\n",m_tokenStream));
      ExprAstPtr lhs { parseMultiplicativeExpression() };
      if (lhs)
      {
        while (m_curToken.type==ExprToken::Operator &&
               (m_curToken.op==Operator::Plus || m_curToken.op==Operator::Minus))
        {
          Operator::Type op = m_curToken.op;
          getNextToken();
          ExprAstPtr rhs { parseMultiplicativeExpression() };
          lhs = std::make_unique<ExprAstBinary>(op,std::move(lhs),std::move(rhs));
        }
      }
      TRACE(("}parseAdditiveExpression(%s)\n",m_tokenStream));
      return lhs;
    }
References Operator::Minus, Operator::Plus, and TRACE.
parseAndExpression() [1/2]
ExprAstPtr ExpressionParser::parseAndExpression () [inline], [private]
Definition at line 2074 of file template.cpp.
    {
      TRACE(("{parseAndExpression(%s)\n",m_tokenStream));
      ExprAstPtr lhs { parseNotExpression() };
      if (lhs)
      {
        while (m_curToken.type==ExprToken::Operator &&
               m_curToken.op==Operator::And)
        {
          getNextToken();
          ExprAstPtr rhs { parseNotExpression() };
          lhs = std::make_unique<ExprAstBinary>(Operator::And,std::move(lhs),std::move(rhs));
        }
      }
      TRACE(("}parseAndExpression(%s)\n",m_tokenStream));
      return lhs;
    }
References Operator::And, getNextToken(), m_curToken, m_tokenStream, ExpressionParser::ExprToken::op, ExpressionParser::ExprToken::Operator, parseNotExpression(), TRACE, and ExpressionParser::ExprToken::type.
Referenced by parseOrExpression().
parseAndExpression() [2/2]
ExprAstPtr ExpressionParser::parseAndExpression () [inline], [private]
Definition at line 2074 of file template.cpp.
    {
      TRACE(("{parseAndExpression(%s)\n",m_tokenStream));
      ExprAstPtr lhs { parseNotExpression() };
      if (lhs)
      {
        while (m_curToken.type==ExprToken::Operator &&
               m_curToken.op==Operator::And)
        {
          getNextToken();
          ExprAstPtr rhs { parseNotExpression() };
          lhs = std::make_unique<ExprAstBinary>(Operator::And,std::move(lhs),std::move(rhs));
        }
      }
      TRACE(("}parseAndExpression(%s)\n",m_tokenStream));
      return lhs;
    }
References Operator::And, and TRACE.
parseCompareExpression() [1/2]
ExprAstPtr ExpressionParser::parseCompareExpression () [inline], [private]
Definition at line 2116 of file template.cpp.
    {
      TRACE(("{parseCompareExpression(%s)\n",m_tokenStream));
      ExprAstPtr lhs { parseAdditiveExpression() };
      if (lhs)
      {
        Operator::Type op = m_curToken.op;
        if (m_curToken.type==ExprToken::Operator &&
            (op==Operator::Less ||
             op==Operator::Greater ||
             op==Operator::Equal ||
             op==Operator::NotEqual ||
             op==Operator::LessEqual ||
             op==Operator::GreaterEqual
            )
           )
        {
          getNextToken();
          ExprAstPtr rhs { parseNotExpression() };
          lhs = std::make_unique<ExprAstBinary>(op,std::move(lhs),std::move(rhs));
        }
      }
      TRACE(("}parseCompareExpression(%s)\n",m_tokenStream));
      return lhs;
    }
References Operator::Equal, getNextToken(), Operator::Greater, Operator::GreaterEqual, Operator::Less, Operator::LessEqual, m_curToken, m_tokenStream, Operator::NotEqual, ExpressionParser::ExprToken::op, ExpressionParser::ExprToken::Operator, parseAdditiveExpression(), parseNotExpression(), TRACE, and ExpressionParser::ExprToken::type.
Referenced by parseNotExpression().
parseCompareExpression() [2/2]
ExprAstPtr ExpressionParser::parseCompareExpression () [inline], [private]
Definition at line 2116 of file template.cpp.
    {
      TRACE(("{parseCompareExpression(%s)\n",m_tokenStream));
      ExprAstPtr lhs { parseAdditiveExpression() };
      if (lhs)
      {
        Operator::Type op = m_curToken.op;
        if (m_curToken.type==ExprToken::Operator &&
            (op==Operator::Less ||
             op==Operator::Greater ||
             op==Operator::Equal ||
             op==Operator::NotEqual ||
             op==Operator::LessEqual ||
             op==Operator::GreaterEqual
            )
           )
        {
          getNextToken();
          ExprAstPtr rhs { parseNotExpression() };
          lhs = std::make_unique<ExprAstBinary>(op,std::move(lhs),std::move(rhs));
        }
      }
      TRACE(("}parseCompareExpression(%s)\n",m_tokenStream));
      return lhs;
    }
References Operator::Equal, Operator::Greater, Operator::GreaterEqual, Operator::Less, Operator::LessEqual, Operator::NotEqual, and TRACE.
parseExpression() [1/2]
ExprAstPtr ExpressionParser::parseExpression () [inline], [private]
Definition at line 2048 of file template.cpp.
    {
      TRACE(("{parseExpression(%s)\n",m_tokenStream));
      ExprAstPtr result { parseOrExpression() };
      TRACE(("}parseExpression(%s)\n",m_tokenStream));
      return result;
    }
References m_tokenStream, parseOrExpression(), and TRACE.
Referenced by parse(), and parsePrimaryExpression().
parseExpression() [2/2]
ExprAstPtr ExpressionParser::parseExpression () [inline], [private]
Definition at line 2048 of file template.cpp.
    {
      TRACE(("{parseExpression(%s)\n",m_tokenStream));
      ExprAstPtr result { parseOrExpression() };
      TRACE(("}parseExpression(%s)\n",m_tokenStream));
      return result;
    }
References TRACE.
parseFilter() [1/2]
ExprAstFilterPtr ExpressionParser::parseFilter () [inline], [private]
Definition at line 2325 of file template.cpp.
    {
      TRACE(("{parseFilter(%s)\n",qPrint(m_curToken.id)));
      QCString filterName = m_curToken.id;
      getNextToken();
      ExprAstPtr argExpr;
      if (m_curToken.type==ExprToken::Operator &&
          m_curToken.op==Operator::Colon)
      {
        getNextToken();
        argExpr = parsePrimaryExpression();
      }
      ExprAstFilterPtr filter = std::make_unique<ExprAstFilter>(filterName,std::move(argExpr));
      TRACE(("}parseFilter()\n"));
      return filter;
    }
References Operator::Colon, filter, getNextToken(), ExpressionParser::ExprToken::id, m_curToken, ExpressionParser::ExprToken::op, ExpressionParser::ExprToken::Operator, parsePrimaryExpression(), qPrint(), TRACE, and ExpressionParser::ExprToken::type.
Referenced by parseFilteredVariable().
parseFilter() [2/2]
ExprAstFilterPtr ExpressionParser::parseFilter () [inline], [private]
Definition at line 2325 of file template.cpp.
    {
      TRACE(("{parseFilter(%s)\n",qPrint(m_curToken.id)));
      QCString filterName = m_curToken.id;
      getNextToken();
      ExprAstPtr argExpr;
      if (m_curToken.type==ExprToken::Operator &&
          m_curToken.op==Operator::Colon)
      {
        getNextToken();
        argExpr = parsePrimaryExpression();
      }
      ExprAstFilterPtr filter = std::make_unique<ExprAstFilter>(filterName,std::move(argExpr));
      TRACE(("}parseFilter()\n"));
      return filter;
    }
References Operator::Colon, filter, qPrint(), and TRACE.
parseFilteredVariable() [1/2]
ExprAstPtr ExpressionParser::parseFilteredVariable () [inline], [private]
Definition at line 2306 of file template.cpp.
    {
      TRACE(("{parseFilteredVariable()\n"));
      ExprAstPtr expr = parseIdentifierOptionalArgs();
      if (expr)
      {
        while (m_curToken.type==ExprToken::Operator &&
               m_curToken.op==Operator::Filter)
        {
          getNextToken();
          ExprAstFilterPtr filter = parseFilter();
          if (!filter) break;
          expr = std::make_unique<ExprAstFilterAppl>(std::move(expr),std::move(filter));
        }
      }
      TRACE(("}parseFilteredVariable()\n"));
      return expr;
    }
References filter, Operator::Filter, getNextToken(), m_curToken, ExpressionParser::ExprToken::op, ExpressionParser::ExprToken::Operator, parseFilter(), parseIdentifierOptionalArgs(), TRACE, and ExpressionParser::ExprToken::type.
Referenced by parsePrimaryExpression().
parseFilteredVariable() [2/2]
ExprAstPtr ExpressionParser::parseFilteredVariable () [inline], [private]
Definition at line 2306 of file template.cpp.
    {
      TRACE(("{parseFilteredVariable()\n"));
      ExprAstPtr expr = parseIdentifierOptionalArgs();
      if (expr)
      {
        while (m_curToken.type==ExprToken::Operator &&
               m_curToken.op==Operator::Filter)
        {
          getNextToken();
          ExprAstFilterPtr filter = parseFilter();
          if (!filter) break;
          expr = std::make_unique<ExprAstFilterAppl>(std::move(expr),std::move(filter));
        }
      }
      TRACE(("}parseFilteredVariable()\n"));
      return expr;
    }
References filter, Operator::Filter, and TRACE.
parseIdentifier() [1/2]
ExprAstPtr ExpressionParser::parseIdentifier () [inline], [private]
Definition at line 2263 of file template.cpp.
    {
      TRACE(("{parseIdentifier(%s)\n",qPrint(m_curToken.id)));
      ExprAstPtr id = std::make_unique<ExprAstVariable>(m_curToken.id);
      getNextToken();
      TRACE(("}parseIdentifier()\n"));
      return id;
    }
References getNextToken(), id, ExpressionParser::ExprToken::id, m_curToken, qPrint(), and TRACE.
Referenced by parseIdentifierOptionalArgs().
parseIdentifier() [2/2]
ExprAstPtr ExpressionParser::parseIdentifier () [inline], [private]
Definition at line 2263 of file template.cpp.
    {
      TRACE(("{parseIdentifier(%s)\n",qPrint(m_curToken.id)));
      ExprAstPtr id = std::make_unique<ExprAstVariable>(m_curToken.id);
      getNextToken();
      TRACE(("}parseIdentifier()\n"));
      return id;
    }
References id, qPrint(), and TRACE.
parseIdentifierOptionalArgs() [1/2]
ExprAstPtr ExpressionParser::parseIdentifierOptionalArgs () [inline], [private]
Definition at line 2281 of file template.cpp.
    {
      TRACE(("{parseIdentifierOptionalArgs(%s)\n",qPrint(m_curToken.id)));
      ExprAstPtr expr { parseIdentifier() };
      if (expr)
      {
        if (m_curToken.type==ExprToken::Operator &&
            m_curToken.op==Operator::Colon)
        {
          getNextToken();
          ExprAstList args;
          args.push_back(std::unique_ptr<ExprAst>(parsePrimaryExpression()));
          while (m_curToken.type==ExprToken::Operator &&
                 m_curToken.op==Operator::Comma)
          {
            getNextToken();
            args.push_back(std::unique_ptr<ExprAst>(parsePrimaryExpression()));
          }
          expr = std::make_unique<ExprAstFunctionVariable>(std::move(expr),std::move(args));
        }
      }
      TRACE(("}parseIdentifierOptionalArgs()\n"));
      return expr;
    }
References Operator::Colon, Operator::Comma, getNextToken(), ExpressionParser::ExprToken::id, m_curToken, ExpressionParser::ExprToken::op, ExpressionParser::ExprToken::Operator, parseIdentifier(), parsePrimaryExpression(), qPrint(), TRACE, and ExpressionParser::ExprToken::type.
Referenced by parseFilteredVariable().
parseIdentifierOptionalArgs() [2/2]
ExprAstPtr ExpressionParser::parseIdentifierOptionalArgs () [inline], [private]
Definition at line 2281 of file template.cpp.
    {
      TRACE(("{parseIdentifierOptionalArgs(%s)\n",qPrint(m_curToken.id)));
      ExprAstPtr expr { parseIdentifier() };
      if (expr)
      {
        if (m_curToken.type==ExprToken::Operator &&
            m_curToken.op==Operator::Colon)
        {
          getNextToken();
          ExprAstList args;
          args.push_back(std::unique_ptr<ExprAst>(parsePrimaryExpression()));
          while (m_curToken.type==ExprToken::Operator &&
                 m_curToken.op==Operator::Comma)
          {
            getNextToken();
            args.push_back(std::unique_ptr<ExprAst>(parsePrimaryExpression()));
          }
          expr = std::make_unique<ExprAstFunctionVariable>(std::move(expr),std::move(args));
        }
      }
      TRACE(("}parseIdentifierOptionalArgs()\n"));
      return expr;
    }
References Operator::Colon, Operator::Comma, qPrint(), and TRACE.
parseLiteral() [1/2]
ExprAstPtr ExpressionParser::parseLiteral () [inline], [private]
Definition at line 2272 of file template.cpp.
    {
      TRACE(("{parseLiteral(%s)\n",qPrint(m_curToken.id)));
      ExprAstPtr expr = std::make_unique<ExprAstLiteral>(m_curToken.id);
      getNextToken();
      TRACE(("}parseLiteral()\n"));
      return expr;
    }
References getNextToken(), ExpressionParser::ExprToken::id, m_curToken, qPrint(), and TRACE.
Referenced by parsePrimaryExpression().
parseLiteral() [2/2]
ExprAstPtr ExpressionParser::parseLiteral () [inline], [private]
Definition at line 2272 of file template.cpp.
    {
      TRACE(("{parseLiteral(%s)\n",qPrint(m_curToken.id)));
      ExprAstPtr expr = std::make_unique<ExprAstLiteral>(m_curToken.id);
      getNextToken();
      TRACE(("}parseLiteral()\n"));
      return expr;
    }
References qPrint(), and TRACE.
parseMultiplicativeExpression() [1/2]
ExprAstPtr ExpressionParser::parseMultiplicativeExpression () [inline], [private]
Definition at line 2161 of file template.cpp.
    {
      TRACE(("{parseMultiplicativeExpression(%s)\n",m_tokenStream));
      ExprAstPtr lhs = parseUnaryExpression();
      if (lhs)
      {
        while (m_curToken.type==ExprToken::Operator &&
               (m_curToken.op==Operator::Multiply || m_curToken.op==Operator::Divide || m_curToken.op==Operator::Modulo))
        {
          Operator::Type op = m_curToken.op;
          getNextToken();
          ExprAstPtr rhs = parseUnaryExpression();
          lhs = std::make_unique<ExprAstBinary>(op,std::move(lhs),std::move(rhs));
        }
      }
      TRACE(("}parseMultiplicativeExpression(%s)\n",m_tokenStream));
      return lhs;
    }
References Operator::Divide, getNextToken(), m_curToken, m_tokenStream, Operator::Modulo, Operator::Multiply, ExpressionParser::ExprToken::op, ExpressionParser::ExprToken::Operator, parseUnaryExpression(), TRACE, and ExpressionParser::ExprToken::type.
Referenced by parseAdditiveExpression().
parseMultiplicativeExpression() [2/2]
ExprAstPtr ExpressionParser::parseMultiplicativeExpression () [inline], [private]
Definition at line 2161 of file template.cpp.
    {
      TRACE(("{parseMultiplicativeExpression(%s)\n",m_tokenStream));
      ExprAstPtr lhs = parseUnaryExpression();
      if (lhs)
      {
        while (m_curToken.type==ExprToken::Operator &&
               (m_curToken.op==Operator::Multiply || m_curToken.op==Operator::Divide || m_curToken.op==Operator::Modulo))
        {
          Operator::Type op = m_curToken.op;
          getNextToken();
          ExprAstPtr rhs = parseUnaryExpression();
          lhs = std::make_unique<ExprAstBinary>(op,std::move(lhs),std::move(rhs));
        }
      }
      TRACE(("}parseMultiplicativeExpression(%s)\n",m_tokenStream));
      return lhs;
    }
References Operator::Divide, Operator::Modulo, Operator::Multiply, and TRACE.
parseNotExpression() [1/2]
ExprAstPtr ExpressionParser::parseNotExpression () [inline], [private]
Definition at line 2092 of file template.cpp.
    {
      TRACE(("{parseNotExpression(%s)\n",m_tokenStream));
      ExprAstPtr result;
      if (m_curToken.type==ExprToken::Operator &&
          m_curToken.op==Operator::Not)
      {
        getNextToken();
        ExprAstPtr expr = parseCompareExpression();
        if (expr==0)
        {
          warn(m_parser->templateName(),m_line,"argument missing for not operator");
          return 0;
        }
        result = std::make_unique<ExprAstNegate>(std::move(expr));
      }
      else
      {
        result = parseCompareExpression();
      }
      TRACE(("}parseNotExpression(%s)\n",m_tokenStream));
      return result;
    }
References getNextToken(), m_curToken, m_line, m_parser, m_tokenStream, Operator::Not, ExpressionParser::ExprToken::op, ExpressionParser::ExprToken::Operator, parseCompareExpression(), TemplateParser::templateName(), TRACE, ExpressionParser::ExprToken::type, and warn().
Referenced by parseAndExpression(), and parseCompareExpression().
parseNotExpression() [2/2]
ExprAstPtr ExpressionParser::parseNotExpression () [inline], [private]
Definition at line 2092 of file template.cpp.
    {
      TRACE(("{parseNotExpression(%s)\n",m_tokenStream));
      ExprAstPtr result;
      if (m_curToken.type==ExprToken::Operator &&
          m_curToken.op==Operator::Not)
      {
        getNextToken();
        ExprAstPtr expr = parseCompareExpression();
        if (expr==0)
        {
          warn(m_parser->templateName(),m_line,"argument missing for not operator");
          return 0;
        }
        result = std::make_unique<ExprAstNegate>(std::move(expr));
      }
      else
      {
        result = parseCompareExpression();
      }
      TRACE(("}parseNotExpression(%s)\n",m_tokenStream));
      return result;
    }
References Operator::Not, TRACE, and warn().
parseNumber() [1/2]
ExprAstPtr ExpressionParser::parseNumber () [inline], [private]
Definition at line 2254 of file template.cpp.
    {
      TRACE(("{parseNumber(%d)\n",m_curToken.num));
      ExprAstPtr num = std::make_unique<ExprAstNumber>(m_curToken.num);
      getNextToken();
      TRACE(("}parseNumber()\n"));
      return num;
    }
References getNextToken(), m_curToken, ExpressionParser::ExprToken::num, and TRACE.
Referenced by parsePrimaryExpression().
parseNumber() [2/2]
ExprAstPtr ExpressionParser::parseNumber () [inline], [private]
Definition at line 2254 of file template.cpp.
    {
      TRACE(("{parseNumber(%d)\n",m_curToken.num));
      ExprAstPtr num = std::make_unique<ExprAstNumber>(m_curToken.num);
      getNextToken();
      TRACE(("}parseNumber()\n"));
      return num;
    }
References TRACE.
parseOrExpression() [1/2]
ExprAstPtr ExpressionParser::parseOrExpression () [inline], [private]
Definition at line 2056 of file template.cpp.
    {
      TRACE(("{parseOrExpression(%s)\n",m_tokenStream));
      ExprAstPtr lhs { parseAndExpression() };
      if (lhs)
      {
        while (m_curToken.type==ExprToken::Operator &&
            m_curToken.op==Operator::Or)
        {
          getNextToken();
          ExprAstPtr rhs { parseAndExpression() };
          lhs = std::make_unique<ExprAstBinary>(Operator::Or,std::move(lhs),std::move(rhs));
        }
      }
      TRACE(("}parseOrExpression(%s)\n",m_tokenStream));
      return lhs;
    }
References getNextToken(), m_curToken, m_tokenStream, ExpressionParser::ExprToken::op, ExpressionParser::ExprToken::Operator, Operator::Or, parseAndExpression(), TRACE, and ExpressionParser::ExprToken::type.
Referenced by parseExpression().
parseOrExpression() [2/2]
ExprAstPtr ExpressionParser::parseOrExpression () [inline], [private]
Definition at line 2056 of file template.cpp.
    {
      TRACE(("{parseOrExpression(%s)\n",m_tokenStream));
      ExprAstPtr lhs { parseAndExpression() };
      if (lhs)
      {
        while (m_curToken.type==ExprToken::Operator &&
            m_curToken.op==Operator::Or)
        {
          getNextToken();
          ExprAstPtr rhs { parseAndExpression() };
          lhs = std::make_unique<ExprAstBinary>(Operator::Or,std::move(lhs),std::move(rhs));
        }
      }
      TRACE(("}parseOrExpression(%s)\n",m_tokenStream));
      return lhs;
    }
References Operator::Or, and TRACE.
parsePrimaryExpression() [1/2]
ExprAstPtr ExpressionParser::parsePrimaryExpression () [inline], [private]
Definition at line 2210 of file template.cpp.
    {
      TRACE(("{parsePrimary(%s)\n",m_tokenStream));
      ExprAstPtr result;
      switch (m_curToken.type)
      {
        case ExprToken::Number:
          result = parseNumber();
          break;
        case ExprToken::Identifier:
          result = parseFilteredVariable();
          break;
        case ExprToken::Literal:
          result = parseLiteral();
          break;
        case ExprToken::Operator:
          if (m_curToken.op==Operator::LeftParen)
          {
            getNextToken(); // skip over opening bracket
            result = parseExpression();
            if (m_curToken.type!=ExprToken::Operator ||
                m_curToken.op!=Operator::RightParen)
            {
              warn(m_parser->templateName(),m_line,"missing closing parenthesis");
            }
            else
            {
              getNextToken(); // skip over closing bracket
            }
          }
          else
          {
            warn(m_parser->templateName(),m_line,"unexpected operator '%s' in expression",
                Operator::toString(m_curToken.op));
            abort();
          }
          break;
        default:
          warn(m_parser->templateName(),m_line,"unexpected token in expression");
      }
      TRACE(("}parsePrimary(%s)\n",m_tokenStream));
      return result;
    }
References getNextToken(), ExpressionParser::ExprToken::Identifier, Operator::LeftParen, ExpressionParser::ExprToken::Literal, m_curToken, m_line, m_parser, m_tokenStream, ExpressionParser::ExprToken::Number, ExpressionParser::ExprToken::op, ExpressionParser::ExprToken::Operator, parseExpression(), parseFilteredVariable(), parseLiteral(), parseNumber(), Operator::RightParen, TemplateParser::templateName(), Operator::toString(), TRACE, ExpressionParser::ExprToken::type, and warn().
Referenced by parseFilter(), parseIdentifierOptionalArgs(), and parseUnaryExpression().
parsePrimaryExpression() [2/2]
ExprAstPtr ExpressionParser::parsePrimaryExpression () [inline], [private]
Definition at line 2210 of file template.cpp.
    {
      TRACE(("{parsePrimary(%s)\n",m_tokenStream));
      ExprAstPtr result;
      switch (m_curToken.type)
      {
        case ExprToken::Number:
          result = parseNumber();
          break;
        case ExprToken::Identifier:
          result = parseFilteredVariable();
          break;
        case ExprToken::Literal:
          result = parseLiteral();
          break;
        case ExprToken::Operator:
          if (m_curToken.op==Operator::LeftParen)
          {
            getNextToken(); // skip over opening bracket
            result = parseExpression();
            if (m_curToken.type!=ExprToken::Operator ||
                m_curToken.op!=Operator::RightParen)
            {
              warn(m_parser->templateName(),m_line,"missing closing parenthesis");
            }
            else
            {
              getNextToken(); // skip over closing bracket
            }
          }
          else
          {
            warn(m_parser->templateName(),m_line,"unexpected operator '%s' in expression",
                Operator::toString(m_curToken.op));
            abort();
          }
          break;
        default:
          warn(m_parser->templateName(),m_line,"unexpected token in expression");
      }
      TRACE(("}parsePrimary(%s)\n",m_tokenStream));
      return result;
    }
References Operator::LeftParen, doxmlparser.compound::parseLiteral(), Operator::RightParen, Operator::toString(), TRACE, and warn().
parseUnaryExpression() [1/2]
ExprAstPtr ExpressionParser::parseUnaryExpression () [inline], [private]
Definition at line 2180 of file template.cpp.
    {
      TRACE(("{parseUnaryExpression(%s)\n",m_tokenStream));
      ExprAstPtr result;
      if (m_curToken.type==ExprToken::Operator)
      {
        if (m_curToken.op==Operator::Plus)
        {
          getNextToken();
          result = parsePrimaryExpression();
        }
        else if (m_curToken.op==Operator::Minus)
        {
          getNextToken();
          ExprAstPtr rhs { parsePrimaryExpression() };
          result = std::make_unique<ExprAstUnary>(m_curToken.op,std::move(rhs));
        }
        else
        {
          result = parsePrimaryExpression();
        }
      }
      else
      {
        result = parsePrimaryExpression();
      }
      TRACE(("}parseUnaryExpression(%s)\n",m_tokenStream));
      return result;
    }
References getNextToken(), m_curToken, m_tokenStream, Operator::Minus, ExpressionParser::ExprToken::op, ExpressionParser::ExprToken::Operator, parsePrimaryExpression(), Operator::Plus, TRACE, and ExpressionParser::ExprToken::type.
Referenced by parseMultiplicativeExpression().
parseUnaryExpression() [2/2]
ExprAstPtr ExpressionParser::parseUnaryExpression () [inline], [private]
Definition at line 2180 of file template.cpp.
    {
      TRACE(("{parseUnaryExpression(%s)\n",m_tokenStream));
      ExprAstPtr result;
      if (m_curToken.type==ExprToken::Operator)
      {
        if (m_curToken.op==Operator::Plus)
        {
          getNextToken();
          result = parsePrimaryExpression();
        }
        else if (m_curToken.op==Operator::Minus)
        {
          getNextToken();
          ExprAstPtr rhs { parsePrimaryExpression() };
          result = std::make_unique<ExprAstUnary>(m_curToken.op,std::move(rhs));
        }
        else
        {
          result = parsePrimaryExpression();
        }
      }
      else
      {
        result = parsePrimaryExpression();
      }
      TRACE(("}parseUnaryExpression(%s)\n",m_tokenStream));
      return result;
    }
References Operator::Minus, Operator::Plus, and TRACE.
Member Data Documentation
m_curToken
ExprToken ExpressionParser::m_curToken [private]
Definition at line 2545 of file template.cpp.
Referenced by getNextToken(), parseAdditiveExpression(), parseAndExpression(), parseCompareExpression(), parseFilter(), parseFilteredVariable(), parseIdentifier(), parseIdentifierOptionalArgs(), parseLiteral(), parseMultiplicativeExpression(), parseNotExpression(), parseNumber(), parseOrExpression(), parsePrimaryExpression(), and parseUnaryExpression().
m_line
int ExpressionParser::m_line = 0 [private]
Definition at line 2546 of file template.cpp.
Referenced by getNextToken(), parseNotExpression(), and parsePrimaryExpression().
m_parser
const TemplateParser * ExpressionParser::m_parser = 0 [private]
Definition at line 2544 of file template.cpp.
Referenced by getNextToken(), parseNotExpression(), and parsePrimaryExpression().
m_tokenStream
const char * ExpressionParser::m_tokenStream [private]
Definition at line 2547 of file template.cpp.
Referenced by getNextToken(), parse(), parseAdditiveExpression(), parseAndExpression(), parseCompareExpression(), parseExpression(), parseMultiplicativeExpression(), parseNotExpression(), parseOrExpression(), parsePrimaryExpression(), and parseUnaryExpression().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp