MemberGroupListContext::Private Class Reference
Public Member Functions
void addMemberGroup (const Definition *def, const QCString &relPath, const MemberGroup *mg)
void addMemberGroup (const Definition *def, const QCString &relPath, const MemberGroup *mg)
Additional Inherited Members
Detailed Description
Definition at line 7852 of file context.cpp.
Member Function Documentation
addMemberGroup() [1/2]
void MemberGroupListContext::Private::addMemberGroup (const Definition * def, const QCString & relPath, const MemberGroup * mg) [inline]
Definition at line 7855 of file context.cpp.
    {
      append(MemberGroupInfoContext::alloc(def,relPath,mg));
    }
References MemberGroupInfoContext::alloc(), and GenericNodeListContext::append().
addMemberGroup() [2/2]
void MemberGroupListContext::Private::addMemberGroup (const Definition * def, const QCString & relPath, const MemberGroup * mg) [inline]
Definition at line 7855 of file context.cpp.
    {
      append(MemberGroupInfoContext::alloc(def,relPath,mg));
    }
References MemberGroupInfoContext::alloc().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp