DotAttributes Class Reference
Class representing an attribute list of a dot graph object.
#include <dotattributes.h>
Public Member Functions
DotAttributes (const QCString &input)
Creates an instance of a DotAttribute list given its initial string representation.
QCString str () const
Return the string representation of the attribute list.
void updateValue (const QCString &key, const QCString &value)
DotAttributes (const QCString &input)
Creates an instance of a DotAttribute list given its initial string representation.
QCString str () const
Return the string representation of the attribute list.
void updateValue (const QCString &key, const QCString &value)
Private Attributes
QCString m_input
Detailed Description
Class representing an attribute list of a dot graph object.
Definition at line 26 of file dotattributes.h.
Constructor & Destructor Documentation
DotAttributes() [1/2]
DotAttributes::DotAttributes (const QCString & input) [inline]
Creates an instance of a DotAttribute list given its initial string representation.
Definition at line 30 of file dotattributes.h.
: m_input(input) {}
DotAttributes() [2/2]
DotAttributes::DotAttributes (const QCString & input) [inline]
Creates an instance of a DotAttribute list given its initial string representation.
Definition at line 30 of file dotattributes.h.
: m_input(input) {}
Member Function Documentation
str() [1/2]
QCString DotAttributes::str () const [inline]
Return the string representation of the attribute list.
Definition at line 33 of file dotattributes.h.
{ return m_input; }
References m_input.
Referenced by Config::updateObsolete().
str() [2/2]
QCString DotAttributes::str () const [inline]
Return the string representation of the attribute list.
Definition at line 33 of file dotattributes.h.
{ return m_input; }
References m_input.
updateValue() [1/2]
void DotAttributes::updateValue (const QCString & key, const QCString & value) [inline]
update a given attribute with a new value. If the attribute is not found a new attribute will be appended.
Definition at line 37 of file dotattributes.h.
    {
      // look for key\s*=
      const reg::Ex re = key.str()+R"(\s*=)";
      reg::Match match;
      std::string s = m_input.str();
      if (reg::search(s,match,re)) // replace existing attribute
      {
        size_t len = s.length();
        size_t startPos = match.position()+match.length(); // position after =
        size_t pos = startPos;
        while (pos<len && qisspace(s[pos])) pos++;
        if (pos<len && s[pos]=='"') // quoted value, search for end quote, ignoring escaped quotes
        {
          char pc=s[pos];
          pos++; // skip over start quote
          while (pos<len && (s[pos]!='"' || (s[pos]=='"' && pc=='\\'))) pc=s[pos++];
          if (pos<len) pos++; // skip over end quote
        }
        else // unquoted value, search for attribute separator (space,comma, or semicolon)
        {
          while (pos<len && s[pos]!=',' && s[pos]!=';' && !qisspace(s[pos])) pos++;
        }
        // pos is now the position after the value, so replace the part between [start..pos) with the new value
        m_input=m_input.left(startPos)+value.quoted()+m_input.mid(pos);
      }
      else // append new attribute
      {
        if (!m_input.isEmpty()) m_input+=",";
        m_input+=key+"="+value.quoted();
      }
    }
References QCString::isEmpty(), QCString::left(), len, m_input, reg::match(), QCString::mid(), qisspace(), QCString::quoted(), s, reg::search(), QCString::str(), and string.
Referenced by updateAttribute().
updateValue() [2/2]
void DotAttributes::updateValue (const QCString & key, const QCString & value) [inline]
update a given attribute with a new value. If the attribute is not found a new attribute will be appended.
Definition at line 37 of file dotattributes.h.
    {
      // look for key\s*=
      const reg::Ex re = key.str()+R"(\s*=)";
      reg::Match match;
      std::string s = m_input.str();
      if (reg::search(s,match,re)) // replace existing attribute
      {
        size_t len = s.length();
        size_t startPos = match.position()+match.length(); // position after =
        size_t pos = startPos;
        while (pos<len && qisspace(s[pos])) pos++;
        if (pos<len && s[pos]=='"') // quoted value, search for end quote, ignoring escaped quotes
        {
          char pc=s[pos];
          pos++; // skip over start quote
          while (pos<len && (s[pos]!='"' || (s[pos]=='"' && pc=='\\'))) pc=s[pos++];
          if (pos<len) pos++; // skip over end quote
        }
        else // unquoted value, search for attribute separator (space,comma, or semicolon)
        {
          while (pos<len && s[pos]!=',' && s[pos]!=';' && !qisspace(s[pos])) pos++;
        }
        // pos is now the position after the value, so replace the part between [start..pos) with the new value
        m_input=m_input.left(startPos)+value.quoted()+m_input.mid(pos);
      }
      else // append new attribute
      {
        if (!m_input.isEmpty()) m_input+=",";
        m_input+=key+"="+value.quoted();
      }
    }
References QCString::isEmpty(), QCString::left(), len, m_input, reg::match(), QCString::mid(), qisspace(), QCString::quoted(), s, reg::search(), QCString::str(), and string.
Member Data Documentation
m_input
QCString DotAttributes::m_input [private]
Definition at line 71 of file dotattributes.h.
Referenced by str(), and updateValue().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/dotattributes.h
doxygen/src/dotattributes.h