TemplateNodeIf Class Reference
Class representing an 'if' tag in a template.
Classes
struct GuardedNodes
Public Member Functions
TemplateNodeIf (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
~TemplateNodeIf ()
void render (TextStream &ts, TemplateContext *c)
TemplateNodeIf (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
~TemplateNodeIf ()
void render (TextStream &ts, TemplateContext *c)
Private Attributes
std::vector< std::unique_ptr< GuardedNodes > > m_ifGuardedNodes
TemplateNodeList m_falseNodes
Additional Inherited Members
Detailed Description
Class representing an 'if' tag in a template.
Definition at line 3101 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeIf() [1/2]
TemplateNodeIf::TemplateNodeIf (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 3104 of file template.cpp.
                                                                                              :
      TemplateNodeCreator<TemplateNodeIf>(parser,parent,line)
    {
      TRACE(("{TemplateNodeIf(%s)\n",qPrint(data)));
      if (data.isEmpty())
      {
        parser->warn(m_templateName,line,"missing argument for if tag");
      }
      StringVector stopAt = { "endif", "elif", "else" };
      // if 'nodes'
      {
        m_ifGuardedNodes.push_back(std::make_unique<GuardedNodes>());
        auto &guardedNodes = m_ifGuardedNodes.back();
        ExpressionParser ex(parser,line);
        guardedNodes->line = line;
        guardedNodes->guardAst = ex.parse(data);
        parser->parse(this,line,stopAt,guardedNodes->trueNodes);
      }
      auto tok = parser->takeNextToken();
      // elif 'nodes'
      while (tok && tok->data.startsWith("elif "))
      {
        m_ifGuardedNodes.push_back(std::make_unique<GuardedNodes>());
        auto &guardedNodes = m_ifGuardedNodes.back();
        ExpressionParser ex(parser,line);
        guardedNodes->line = tok->line;
        guardedNodes->guardAst = ex.parse(tok->data.mid(5));
        parser->parse(this,tok->line,stopAt,guardedNodes->trueNodes);
        // proceed to the next token
        tok = parser->takeNextToken();
      }
      // else 'nodes'
      if (tok && tok->data=="else")
      {
        stopAt.pop_back(); // remove "else"
        stopAt.pop_back(); // remove "elif"
        parser->parse(this,line,stopAt,m_falseNodes);
        parser->removeNextToken(); // skip over endif
      }
      TRACE(("}TemplateNodeIf(%s)\n",qPrint(data)));
    }
References data, m_falseNodes, m_ifGuardedNodes, TemplateNodeCreator< TemplateNodeIf >::m_templateName, ExpressionParser::parse(), TemplateParser::parse(), qPrint(), TemplateParser::removeNextToken(), TemplateParser::takeNextToken(), TRACE, and TemplateParser::warn().
 TemplateNodeIf() [1/2]
TemplateNodeIf::~TemplateNodeIf () [inline]
Definition at line 3148 of file template.cpp.
    {
    }
TemplateNodeIf() [2/2]
TemplateNodeIf::TemplateNodeIf (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 3104 of file template.cpp.
                                                                                              :
      TemplateNodeCreator<TemplateNodeIf>(parser,parent,line)
    {
      TRACE(("{TemplateNodeIf(%s)\n",qPrint(data)));
      if (data.isEmpty())
      {
        parser->warn(m_templateName,line,"missing argument for if tag");
      }
      StringVector stopAt = { "endif", "elif", "else" };
      // if 'nodes'
      {
        m_ifGuardedNodes.push_back(std::make_unique<GuardedNodes>());
        auto &guardedNodes = m_ifGuardedNodes.back();
        ExpressionParser ex(parser,line);
        guardedNodes->line = line;
        guardedNodes->guardAst = ex.parse(data);
        parser->parse(this,line,stopAt,guardedNodes->trueNodes);
      }
      auto tok = parser->takeNextToken();
      // elif 'nodes'
      while (tok && tok->data.startsWith("elif "))
      {
        m_ifGuardedNodes.push_back(std::make_unique<GuardedNodes>());
        auto &guardedNodes = m_ifGuardedNodes.back();
        ExpressionParser ex(parser,line);
        guardedNodes->line = tok->line;
        guardedNodes->guardAst = ex.parse(tok->data.mid(5));
        parser->parse(this,tok->line,stopAt,guardedNodes->trueNodes);
        // proceed to the next token
        tok = parser->takeNextToken();
      }
      // else 'nodes'
      if (tok && tok->data=="else")
      {
        stopAt.pop_back(); // remove "else"
        stopAt.pop_back(); // remove "elif"
        parser->parse(this,line,stopAt,m_falseNodes);
        parser->removeNextToken(); // skip over endif
      }
      TRACE(("}TemplateNodeIf(%s)\n",qPrint(data)));
    }
References data, m_falseNodes, m_ifGuardedNodes, TemplateNodeCreator< TemplateNodeIf >::m_templateName, ExpressionParser::parse(), TemplateParser::parse(), qPrint(), TemplateParser::removeNextToken(), TemplateParser::takeNextToken(), TRACE, and TemplateParser::warn().
 TemplateNodeIf() [2/2]
TemplateNodeIf::~TemplateNodeIf () [inline]
Definition at line 3148 of file template.cpp.
    {
    }
Member Function Documentation
render() [1/2]
void TemplateNodeIf::render (TextStream & ts, TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 3152 of file template.cpp.
    {
      TemplateContextImpl* ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      //printf("TemplateNodeIf::render #trueNodes=%d #falseNodes=%d\n",m_trueNodes.count(),m_falseNodes.count());
      bool processed=FALSE;
      for (auto &nodes : m_ifGuardedNodes)
      {
        if (nodes->guardAst)
        {
          TemplateVariant guardValue = nodes->guardAst->resolve(c);
          if (guardValue.toBool()) // render nodes for the first guard that evaluated to 'true'
          {
            nodes->trueNodes.render(ts,c);
            processed=TRUE;
            break;
          }
        }
        else
        {
          ci->warn(m_templateName,nodes->line,"invalid expression for if/elif");
        }
      }
      if (!processed)
      {
        // all guards are false, render 'else' nodes
        m_falseNodes.render(ts,c);
      }
    }
References c, FALSE, m_falseNodes, m_ifGuardedNodes, TemplateNodeCreator< TemplateNodeIf >::m_line, TemplateNodeCreator< TemplateNodeIf >::m_templateName, TemplateNodeList::render(), TemplateContextImpl::setLocation(), TemplateVariant::toBool(), TRUE, and TemplateContextImpl::warn().
render() [2/2]
void TemplateNodeIf::render (TextStream & ts, TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 3152 of file template.cpp.
    {
      TemplateContextImpl* ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      //printf("TemplateNodeIf::render #trueNodes=%d #falseNodes=%d\n",m_trueNodes.count(),m_falseNodes.count());
      bool processed=FALSE;
      for (auto &nodes : m_ifGuardedNodes)
      {
        if (nodes->guardAst)
        {
          TemplateVariant guardValue = nodes->guardAst->resolve(c);
          if (guardValue.toBool()) // render nodes for the first guard that evaluated to 'true'
          {
            nodes->trueNodes.render(ts,c);
            processed=TRUE;
            break;
          }
        }
        else
        {
          ci->warn(m_templateName,nodes->line,"invalid expression for if/elif");
        }
      }
      if (!processed)
      {
        // all guards are false, render 'else' nodes
        m_falseNodes.render(ts,c);
      }
    }
References c, FALSE, m_falseNodes, m_ifGuardedNodes, TemplateNodeCreator< TemplateNodeIf >::m_line, TemplateNodeCreator< TemplateNodeIf >::m_templateName, TemplateNodeList::render(), TemplateContextImpl::setLocation(), TemplateVariant::toBool(), TRUE, and TemplateContextImpl::warn().
Member Data Documentation
m_falseNodes
TemplateNodeList TemplateNodeIf::m_falseNodes [private]
Definition at line 3190 of file template.cpp.
Referenced by render(), and TemplateNodeIf().
m_ifGuardedNodes
std::vector< std::unique_ptr< GuardedNodes > > TemplateNodeIf::m_ifGuardedNodes [private]
Definition at line 3189 of file template.cpp.
Referenced by render(), and TemplateNodeIf().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp