ConfigImpl Class Reference
#include <configimpl.h>
Public Member Functions
void writeTemplate (TextStream &t, bool shortIndex, bool updateOnly)
void compareDoxyfile (TextStream &t, Config::CompareMode compareMode)
void writeXMLDoxyfile (TextStream &t)
void setHeader (const char *header)
void convertStrToVal (Config::CompareMode compareMode)
void emptyValueToDefault ()
void substituteEnvironmentVars ()
void init ()
bool parseString (const QCString &fn, const QCString &str, bool upd=FALSE)
bool parse (const QCString &fn, bool upd=FALSE)
void create ()
void appendStartComment (const QCString &u)
void appendUserComment (const QCString &u)
void appendStoreRepl (const QCString &u)
QCString takeStartComment ()
QCString takeUserComment ()
QCString takeStoreRepl ()
void writeTemplate (TextStream &t, bool shortIndex, bool updateOnly)
void compareDoxyfile (TextStream &t, Config::CompareMode compareMode)
void writeXMLDoxyfile (TextStream &t)
void setHeader (const char *header)
void convertStrToVal (Config::CompareMode compareMode)
void emptyValueToDefault ()
void substituteEnvironmentVars ()
void init ()
bool parseString (const QCString &fn, const QCString &str, bool upd=FALSE)
bool parse (const QCString &fn, bool upd=FALSE)
void create ()
void appendStartComment (const QCString &u)
void appendUserComment (const QCString &u)
void appendStoreRepl (const QCString &u)
QCString takeStartComment ()
QCString takeUserComment ()
QCString takeStoreRepl ()
 Getting configuration values.
QCString & getString (const char *fileName, int num, const char *name) const
StringVector & getList (const char *fileName, int num, const char *name) const
QCString & getEnum (const char *fileName, int num, const char *name) const
int & getInt (const char *fileName, int num, const char *name) const
bool & getBool (const char *fileName, int num, const char *name) const
ConfigOption * get (const QCString &name) const
QCString & getString (const char *fileName, int num, const char *name) const
StringVector & getList (const char *fileName, int num, const char *name) const
QCString & getEnum (const char *fileName, int num, const char *name) const
int & getInt (const char *fileName, int num, const char *name) const
bool & getBool (const char *fileName, int num, const char *name) const
ConfigOption * get (const QCString &name) const
 Adding configuration options.
ConfigInfo * addInfo (const char *name, const char *doc)
ConfigString * addString (const char *name, const char *doc)
ConfigEnum * addEnum (const char *name, const char *doc, const char *defVal)
ConfigList * addList (const char *name, const char *doc)
ConfigInt * addInt (const char *name, const char *doc, int minVal, int maxVal, int defVal)
ConfigBool * addBool (const char *name, const char *doc, bool defVal)
ConfigOption * addObsolete (const char *name, ConfigOption::OptionType orgType)
ConfigOption * addDisabled (const char *name)
ConfigInfo * addInfo (const char *name, const char *doc)
ConfigString * addString (const char *name, const char *doc)
ConfigEnum * addEnum (const char *name, const char *doc, const char *defVal)
ConfigList * addList (const char *name, const char *doc)
ConfigInt * addInt (const char *name, const char *doc, int minVal, int maxVal, int defVal)
ConfigBool * addBool (const char *name, const char *doc, bool defVal)
ConfigOption * addObsolete (const char *name, ConfigOption::OptionType orgType)
ConfigOption * addDisabled (const char *name)
Static Public Member Functions
static ConfigImpl * instance ()
static void deleteInstance ()
static ConfigImpl * instance ()
static void deleteInstance ()
Protected Member Functions
ConfigImpl ()
~ConfigImpl ()
ConfigImpl ()
~ConfigImpl ()
Private Attributes
ConfigOptionList m_options
ConfigOptionList m_obsolete
ConfigOptionList m_disabled
ConfigOptionMap m_dict
QCString m_startComment
QCString m_userComment
QCString m_storeRepl
bool m_initialized
QCString m_header
Static Private Attributes
static ConfigImpl * m_instance = 0
Detailed Description
Singleton for configuration variables.
This object holds the global static variables read from a user-supplied configuration file. The static member instance() can be used to get a pointer to the one and only instance.
Set all variables to their default values by calling Config::instance()->init()
Definition at line 336 of file configimpl.h.
Constructor & Destructor Documentation
ConfigImpl() [1/2]
ConfigImpl::ConfigImpl () [inline], [protected]
Definition at line 604 of file configimpl.h.
    {
      m_initialized = FALSE;
      create();
    }
References create(), FALSE, and m_initialized.
Referenced by instance().
 ConfigImpl() [1/2]
ConfigImpl::~ConfigImpl () [inline], [protected]
Definition at line 609 of file configimpl.h.
    {
    }
ConfigImpl() [2/2]
ConfigImpl::ConfigImpl () [inline], [protected]
Definition at line 604 of file configimpl.h.
    {
      m_initialized = FALSE;
      create();
    }
References create(), FALSE, and m_initialized.
 ConfigImpl() [2/2]
ConfigImpl::~ConfigImpl () [inline], [protected]
Definition at line 609 of file configimpl.h.
    {
    }
Member Function Documentation
addBool() [1/2]
ConfigBool * ConfigImpl::addBool (const char * name, const char * doc, bool defVal) [inline]
Adds a new boolean option with name and documentation doc. The boolean has a default value of defVal.
Returns
An object representing the option.
Definition at line 473 of file configimpl.h.
    {
      ConfigBool *result = new ConfigBool(name,doc,defVal);
      m_options.push_back(std::unique_ptr<ConfigOption>(result));
      m_dict.insert(std::make_pair(name,result));
      return result;
    }
References m_dict, m_options, and setup::name.
addBool() [2/2]
ConfigBool * ConfigImpl::addBool (const char * name, const char * doc, bool defVal) [inline]
Adds a new boolean option with name and documentation doc. The boolean has a default value of defVal.
Returns
An object representing the option.
Definition at line 473 of file configimpl.h.
    {
      ConfigBool *result = new ConfigBool(name,doc,defVal);
      m_options.push_back(std::unique_ptr<ConfigOption>(result));
      m_dict.insert(std::make_pair(name,result));
      return result;
    }
References m_dict, m_options, and setup::name.
addDisabled() [1/2]
ConfigOption * ConfigImpl::addDisabled (const char * name) [inline]
Adds an option that has been disabled at compile time.
Definition at line 491 of file configimpl.h.
    {
      ConfigDisabled *result = new ConfigDisabled(name);
      m_disabled.push_back(std::unique_ptr<ConfigOption>(result));
      m_dict.insert(std::make_pair(name,result));
      return result;
    }
References m_dict, m_disabled, and setup::name.
addDisabled() [2/2]
ConfigOption * ConfigImpl::addDisabled (const char * name) [inline]
Adds an option that has been disabled at compile time.
Definition at line 491 of file configimpl.h.
    {
      ConfigDisabled *result = new ConfigDisabled(name);
      m_disabled.push_back(std::unique_ptr<ConfigOption>(result));
      m_dict.insert(std::make_pair(name,result));
      return result;
    }
References m_dict, m_disabled, and setup::name.
addEnum() [1/2]
ConfigEnum * ConfigImpl::addEnum (const char * name, const char * doc, const char * defVal) [inline]
Adds a new enumeration option with name and documentation doc and initial value defVal.
Returns
An object representing the option.
Definition at line 432 of file configimpl.h.
    {
      ConfigEnum *result = new ConfigEnum(name,doc,defVal);
      m_options.push_back(std::unique_ptr<ConfigOption>(result));
      m_dict.insert(std::make_pair(name,result));
      return result;
    }
References m_dict, m_options, and setup::name.
addEnum() [2/2]
ConfigEnum * ConfigImpl::addEnum (const char * name, const char * doc, const char * defVal) [inline]
Adds a new enumeration option with name and documentation doc and initial value defVal.
Returns
An object representing the option.
Definition at line 432 of file configimpl.h.
    {
      ConfigEnum *result = new ConfigEnum(name,doc,defVal);
      m_options.push_back(std::unique_ptr<ConfigOption>(result));
      m_dict.insert(std::make_pair(name,result));
      return result;
    }
References m_dict, m_options, and setup::name.
addInfo() [1/2]
ConfigInfo * ConfigImpl::addInfo (const char * name, const char * doc) [inline]
Starts a new configuration section with name and description doc.
Returns
An object representing the option.
Definition at line 409 of file configimpl.h.
    {
      ConfigInfo *result = new ConfigInfo(name,doc);
      m_options.push_back(std::unique_ptr<ConfigOption>(result));
      return result;
    }
References m_options, and setup::name.
addInfo() [2/2]
ConfigInfo * ConfigImpl::addInfo (const char * name, const char * doc) [inline]
Starts a new configuration section with name and description doc.
Returns
An object representing the option.
Definition at line 409 of file configimpl.h.
    {
      ConfigInfo *result = new ConfigInfo(name,doc);
      m_options.push_back(std::unique_ptr<ConfigOption>(result));
      return result;
    }
References m_options, and setup::name.
addInt() [1/2]
ConfigInt * ConfigImpl::addInt (const char * name, const char * doc, int minVal, int maxVal, int defVal) [inline]
Adds a new integer option with name and documentation doc. The integer has a range between minVal and maxVal and a default value of defVal.
Returns
An object representing the option.
Definition at line 459 of file configimpl.h.
    {
      ConfigInt *result = new ConfigInt(name,doc,minVal,maxVal,defVal);
      m_options.push_back(std::unique_ptr<ConfigOption>(result));
      m_dict.insert(std::make_pair(name,result));
      return result;
    }
References m_dict, m_options, and setup::name.
addInt() [2/2]
ConfigInt * ConfigImpl::addInt (const char * name, const char * doc, int minVal, int maxVal, int defVal) [inline]
Adds a new integer option with name and documentation doc. The integer has a range between minVal and maxVal and a default value of defVal.
Returns
An object representing the option.
Definition at line 459 of file configimpl.h.
    {
      ConfigInt *result = new ConfigInt(name,doc,minVal,maxVal,defVal);
      m_options.push_back(std::unique_ptr<ConfigOption>(result));
      m_dict.insert(std::make_pair(name,result));
      return result;
    }
References m_dict, m_options, and setup::name.
addList() [1/2]
ConfigList * ConfigImpl::addList (const char * name, const char * doc) [inline]
Adds a new string option with name and documentation doc.
Returns
An object representing the option.
Definition at line 445 of file configimpl.h.
    {
      ConfigList *result = new ConfigList(name,doc);
      m_options.push_back(std::unique_ptr<ConfigOption>(result));
      m_dict.insert(std::make_pair(name,result));
      return result;
    }
References m_dict, m_options, and setup::name.
addList() [2/2]
ConfigList * ConfigImpl::addList (const char * name, const char * doc) [inline]
Adds a new string option with name and documentation doc.
Returns
An object representing the option.
Definition at line 445 of file configimpl.h.
    {
      ConfigList *result = new ConfigList(name,doc);
      m_options.push_back(std::unique_ptr<ConfigOption>(result));
      m_dict.insert(std::make_pair(name,result));
      return result;
    }
References m_dict, m_options, and setup::name.
addObsolete() [1/2]
ConfigOption * ConfigImpl::addObsolete (const char * name, ConfigOption::OptionType orgType) [inline]
Adds an option that has become obsolete.
Definition at line 483 of file configimpl.h.
    {
      ConfigObsolete *result = new ConfigObsolete(name,orgType);
      m_obsolete.push_back(std::unique_ptr<ConfigOption>(result));
      m_dict.insert(std::make_pair(name,result));
      return result;
    }
References m_dict, m_obsolete, and setup::name.
addObsolete() [2/2]
ConfigOption * ConfigImpl::addObsolete (const char * name, ConfigOption::OptionType orgType) [inline]
Adds an option that has become obsolete.
Definition at line 483 of file configimpl.h.
    {
      ConfigObsolete *result = new ConfigObsolete(name,orgType);
      m_obsolete.push_back(std::unique_ptr<ConfigOption>(result));
      m_dict.insert(std::make_pair(name,result));
      return result;
    }
References m_dict, m_obsolete, and setup::name.
addString() [1/2]
ConfigString * ConfigImpl::addString (const char * name, const char * doc) [inline]
Adds a new string option with name and documentation doc.
Returns
An object representing the option.
Definition at line 419 of file configimpl.h.
    {
      ConfigString *result = new ConfigString(name,doc);
      m_options.push_back(std::unique_ptr<ConfigOption>(result));
      m_dict.insert(std::make_pair(name,result));
      return result;
    }
References m_dict, m_options, and setup::name.
addString() [2/2]
ConfigString * ConfigImpl::addString (const char * name, const char * doc) [inline]
Adds a new string option with name and documentation doc.
Returns
An object representing the option.
Definition at line 419 of file configimpl.h.
    {
      ConfigString *result = new ConfigString(name,doc);
      m_options.push_back(std::unique_ptr<ConfigOption>(result));
      m_dict.insert(std::make_pair(name,result));
      return result;
    }
References m_dict, m_options, and setup::name.
appendStartComment() [1/2]
void ConfigImpl::appendStartComment (const QCString & u) [inline]
Append user start comment
Definition at line 558 of file configimpl.h.
    {
      m_startComment += u;
    }
References m_startComment.
appendStartComment() [2/2]
void ConfigImpl::appendStartComment (const QCString & u) [inline]
Append user start comment
Definition at line 558 of file configimpl.h.
    {
      m_startComment += u;
    }
References m_startComment.
appendStoreRepl() [1/2]
void ConfigImpl::appendStoreRepl (const QCString & u) [inline]
Append replacement string
Definition at line 570 of file configimpl.h.
    {
      m_storeRepl += u;
    }
References m_storeRepl.
appendStoreRepl() [2/2]
void ConfigImpl::appendStoreRepl (const QCString & u) [inline]
Append replacement string
Definition at line 570 of file configimpl.h.
    {
      m_storeRepl += u;
    }
References m_storeRepl.
appendUserComment() [1/2]
void ConfigImpl::appendUserComment (const QCString & u) [inline]
Append user comment
Definition at line 564 of file configimpl.h.
    {
      m_userComment += u;
    }
References m_userComment.
Referenced by stripComment().
appendUserComment() [2/2]
void ConfigImpl::appendUserComment (const QCString & u) [inline]
Append user comment
Definition at line 564 of file configimpl.h.
    {
      m_userComment += u;
    }
References m_userComment.
compareDoxyfile() [1/2]
void ConfigImpl::compareDoxyfile (TextStream & t, Config::CompareMode compareMode)
Writes a the differences between the current configuration and the template configuration to stream t.
Definition at line 1315 of file configimpl.l.
{
  t << "# Difference with default Doxyfile " << getFullVersion();
  t << "\n";
  for (const auto &option : m_options)
  {
    option->m_userComment = "";
    option->compareDoxyfile(t,compareMode);
  }
  if (!m_storeRepl.isEmpty())
  {
    t << "\n";
    t << takeStoreRepl() << "\n";
  }
}
References ConfigOption::compareDoxyfile(), getFullVersion(), QCString::isEmpty(), m_options, m_storeRepl, ConfigOption::m_userComment, and takeStoreRepl().
Referenced by Config::compareDoxyfile().
compareDoxyfile() [2/2]
void ConfigImpl::compareDoxyfile (TextStream & t, Config::CompareMode compareMode)
Writes a the differences between the current configuration and the template configuration to stream t.
convertStrToVal() [1/2]
void ConfigImpl::convertStrToVal (Config::CompareMode compareMode)
Converts the string values read from the configuration file to real values for non-string type options (like int, and bools)
Definition at line 1342 of file configimpl.l.
{
  for (const auto &option : m_options)
  {
    option->convertStrToVal(compareMode);
  }
}
References ConfigOption::convertStrToVal(), and m_options.
convertStrToVal() [2/2]
void ConfigImpl::convertStrToVal (Config::CompareMode compareMode)
Converts the string values read from the configuration file to real values for non-string type options (like int, and bools)
create() [1/2]
void ConfigImpl::create ()
Called from the constructor, will add doxygen's default options to the configuration object
Definition at line 1532 of file configimpl.l.
{
  if (m_initialized) return;
  m_initialized = TRUE;
  addConfigOptions(this);
}
References addConfigOptions(), m_initialized, and TRUE.
Referenced by ConfigImpl().
create() [2/2]
void ConfigImpl::create ()
Called from the constructor, will add doxygen's default options to the configuration object
deleteInstance() [1/2]
static void ConfigImpl::deleteInstance () [inline], [static]
Delete the instance
Definition at line 350 of file configimpl.h.
    {
      delete m_instance;
      m_instance=0;
    }
References m_instance.
Referenced by Config::deinit().
deleteInstance() [2/2]
static void ConfigImpl::deleteInstance () [inline], [static]
Delete the instance
Definition at line 350 of file configimpl.h.
    {
      delete m_instance;
      m_instance=0;
    }
References m_instance.
emptyValueToDefault() [1/2]
void ConfigImpl::emptyValueToDefault ()
Sets default value in case value is empty
Definition at line 1349 of file configimpl.l.
{
  for (const auto &option : m_options)
  {
    option->emptyValueToDefault();
  }
}
References ConfigOption::emptyValueToDefault(), and m_options.
emptyValueToDefault() [2/2]
void ConfigImpl::emptyValueToDefault ()
Sets default value in case value is empty
get() [1/2]
ConfigOption * ConfigImpl::get (const QCString & name) const [inline]
Returns the ConfigOption corresponding with name or 0 if the option is not supported.
Definition at line 394 of file configimpl.h.
    {
      auto it = m_dict.find(name.str());
      return it!=m_dict.end() ? it->second : nullptr;
    }
References m_dict, and setup::name.
Referenced by checkEncoding(), init(), Config::parse(), and Config::updateObsolete().
get() [2/2]
ConfigOption * ConfigImpl::get (const QCString & name) const [inline]
Returns the ConfigOption corresponding with name or 0 if the option is not supported.
Definition at line 394 of file configimpl.h.
    {
      auto it = m_dict.find(name.str());
      return it!=m_dict.end() ? it->second : nullptr;
    }
References m_dict, and setup::name.
getBool() [1/2]
bool & ConfigImpl::getBool (const char * fileName, int num, const char * name) const
Returns the value of the boolean option with name fileName. The arguments num and name are for debugging purposes only. There is a convenience function Config_getBool() for this.
Definition at line 353 of file configimpl.l.
{
  auto it = m_dict.find(name);
  if (it==m_dict.end())
  {
    config_term("%s<%d>: Internal error: Requested unknown option %s!\n",fileName,num,name);
  }
  else if (it->second->kind()!=ConfigOption::O_Bool)
  {
    config_term("%s<%d>: Internal error: Requested option %s not of boolean type!\n",fileName,num,name);
  }
  return *(dynamic_cast<ConfigBool *>(it->second))->valueRef();
}
References config_term(), m_dict, setup::name, and ConfigOption::O_Bool.
getBool() [2/2]
bool & ConfigImpl::getBool (const char * fileName, int num, const char * name) const
Returns the value of the boolean option with name fileName. The arguments num and name are for debugging purposes only. There is a convenience function Config_getBool() for this.
getEnum() [1/2]
QCString & ConfigImpl::getEnum (const char * fileName, int num, const char * name) const
Returns the value of the enum option with name fileName. The arguments num and name are for debugging purposes only. There is a convenience function Config_getEnum() for this.
Definition at line 325 of file configimpl.l.
{
  auto it = m_dict.find(name);
  if (it==m_dict.end())
  {
    config_term("%s<%d>: Internal error: Requested unknown option %s!\n",fileName,num,name);
  }
  else if (it->second->kind()!=ConfigOption::O_Enum)
  {
    config_term("%s<%d>: Internal error: Requested option %s not of enum type!\n",fileName,num,name);
  }
  return *(dynamic_cast<ConfigEnum *>(it->second))->valueRef();
}
References config_term(), m_dict, setup::name, and ConfigOption::O_Enum.
getEnum() [2/2]
QCString & ConfigImpl::getEnum (const char * fileName, int num, const char * name) const
Returns the value of the enum option with name fileName. The arguments num and name are for debugging purposes only. There is a convenience function Config_getEnum() for this.
getInt() [1/2]
int & ConfigImpl::getInt (const char * fileName, int num, const char * name) const
Returns the value of the integer option with name fileName. The arguments num and name are for debugging purposes only. There is a convenience function Config_getInt() for this.
Definition at line 339 of file configimpl.l.
{
  auto it = m_dict.find(name);
  if (it==m_dict.end())
  {
    config_term("%s<%d>: Internal error: Requested unknown option %s!\n",fileName,num,name);
  }
  else if (it->second->kind()!=ConfigOption::O_Int)
  {
    config_term("%s<%d>: Internal error: Requested option %s not of integer type!\n",fileName,num,name);
  }
  return *(dynamic_cast<ConfigInt *>(it->second))->valueRef();
}
References config_term(), m_dict, setup::name, and ConfigOption::O_Int.
getInt() [2/2]
int & ConfigImpl::getInt (const char * fileName, int num, const char * name) const
Returns the value of the integer option with name fileName. The arguments num and name are for debugging purposes only. There is a convenience function Config_getInt() for this.
getList() [1/2]
StringVector & ConfigImpl::getList (const char * fileName, int num, const char * name) const
Returns the value of the list option with name fileName. The arguments num and name are for debugging purposes only. There is a convenience function Config_getList() for this.
Definition at line 311 of file configimpl.l.
{
  auto it = m_dict.find(name);
  if (it==m_dict.end())
  {
    config_term("%s<%d>: Internal error: Requested unknown option %s!\n",fileName,num,name);
  }
  else if (it->second->kind()!=ConfigOption::O_List)
  {
    config_term("%s<%d>: Internal error: Requested option %s not of list type!\n",fileName,num,name);
  }
  return *(dynamic_cast<ConfigList *>(it->second))->valueRef();
}
References config_term(), m_dict, setup::name, and ConfigOption::O_List.
getList() [2/2]
StringVector & ConfigImpl::getList (const char * fileName, int num, const char * name) const
Returns the value of the list option with name fileName. The arguments num and name are for debugging purposes only. There is a convenience function Config_getList() for this.
getString() [1/2]
QCString & ConfigImpl::getString (const char * fileName, int num, const char * name) const
Returns the value of the string option with name fileName. The arguments num and name are for debugging purposes only. There is a convenience function Config_getString() for this.
Definition at line 297 of file configimpl.l.
{
  auto it = m_dict.find(name);
  if (it==m_dict.end())
  {
    config_term("%s<%d>: Internal error: Requested unknown option %s!\n",fileName,num,name);
  }
  else if (it->second->kind()!=ConfigOption::O_String)
  {
    config_term("%s<%d>: Internal error: Requested option %s not of string type!\n",fileName,num,name);
  }
  return *(dynamic_cast<ConfigString *>(it->second))->valueRef();
}
References config_term(), m_dict, setup::name, and ConfigOption::O_String.
getString() [2/2]
QCString & ConfigImpl::getString (const char * fileName, int num, const char * name) const
Returns the value of the string option with name fileName. The arguments num and name are for debugging purposes only. There is a convenience function Config_getString() for this.
init() [1/2]
void ConfigImpl::init ()
Initialize config variables to their default value
Definition at line 1509 of file configimpl.l.
{
  for (const auto &option : m_options)
  {
    option->init();
  }
  // sanity check if all depends relations are valid
  for (const auto &option : m_options)
  {
    QCString depName = option->dependsOn();
    if (!depName.isEmpty())
    {
      ConfigOption * opt = ConfigImpl::instance()->get(depName);
      if (opt==0)
      {
        config_term("Config option '%s' has invalid depends relation on unknown option '%s'\n",
            qPrint(option->name()),qPrint(depName));
      }
    }
  }
}
References config_term(), ConfigOption::dependsOn(), get(), ConfigOption::init(), instance(), QCString::isEmpty(), m_options, ConfigOption::name(), and qPrint().
Referenced by Config::init().
init() [2/2]
void ConfigImpl::init ()
Initialize config variables to their default value
instance() [1/2]
static ConfigImpl * ConfigImpl::instance () [inline], [static]
Returns the one and only instance of this class
Definition at line 344 of file configimpl.h.
    {
      if (m_instance==0) m_instance = new ConfigImpl;
      return m_instance;
    }
References ConfigImpl(), and m_instance.
Referenced by Config::compareDoxyfile(), Config::deinit(), Config::init(), init(), Config::parse(), parseString(), Config::postProcess(), Config::updateObsolete(), Config::writeTemplate(), and Config::writeXMLDoxyfile().
instance() [2/2]
static ConfigImpl * ConfigImpl::instance () [inline], [static]
Returns the one and only instance of this class
Definition at line 344 of file configimpl.h.
    {
      if (m_instance==0) m_instance = new ConfigImpl;
      return m_instance;
    }
References ConfigImpl(), and m_instance.
parse() [1/2]
bool ConfigImpl::parse (const QCString & fn, bool upd = FALSE)
Parse a configuration file with name fn.
Returns
TRUE if successful, FALSE if the file could not be opened or read.
Definition at line 1587 of file configimpl.l.
{
  int retval;
  g_encoding = "UTF-8";
  printlex(yy_flex_debug, TRUE, __FILE__, qPrint(fn));
  retval = parseString(fn,configFileToString(fn), update);
  printlex(yy_flex_debug, FALSE, __FILE__, qPrint(fn));
  return retval;
}
References configFileToString(), FALSE, g_encoding, parseString(), printlex(), qPrint(), and TRUE.
Referenced by Config::parse().
parse() [2/2]
bool ConfigImpl::parse (const QCString & fn, bool upd = FALSE)
Parse a configuration file with name fn.
Returns
TRUE if successful, FALSE if the file could not be opened or read.
parseString() [1/2]
bool ConfigImpl::parseString (const QCString & fn, const QCString & str, bool upd = FALSE)
Parse a configuration data in string str.
Returns
TRUE if successful, or FALSE if the string could not be parsed.
Definition at line 1570 of file configimpl.l.
{
  g_config = ConfigImpl::instance();
  g_inputString = str.data();
  g_inputPosition = 0;
  g_yyFileName = fn;
  g_yyLineNr = 1;
  g_includeStack.clear();
  configimplYYrestart(configimplYYin);
  BEGIN(Start);
  g_configUpdate = update;
  configimplYYlex();
  g_configUpdate = FALSE;
  g_inputString = 0;
  return TRUE;
}
References QCString::data(), FALSE, g_config, g_configUpdate, g_includeStack, g_inputPosition, g_inputString, g_yyFileName, g_yyLineNr, instance(), and TRUE.
Referenced by parse().
parseString() [2/2]
bool ConfigImpl::parseString (const QCString & fn, const QCString & str, bool upd = FALSE)
Parse a configuration data in string str.
Returns
TRUE if successful, or FALSE if the string could not be parsed.
setHeader() [1/2]
void ConfigImpl::setHeader (const char * header) [inline]
Definition at line 516 of file configimpl.h.
{ m_header = header; }
References m_header.
setHeader() [2/2]
void ConfigImpl::setHeader (const char * header) [inline]
Definition at line 516 of file configimpl.h.
{ m_header = header; }
References m_header.
substituteEnvironmentVars() [1/2]
void ConfigImpl::substituteEnvironmentVars ()
Replaces references to environment variable by the actual value of the environment variable.
Definition at line 1501 of file configimpl.l.
{
  for (const auto &option : m_options)
  {
    option->substEnvVars();
  }
}
References m_options, and ConfigOption::substEnvVars().
substituteEnvironmentVars() [2/2]
void ConfigImpl::substituteEnvironmentVars ()
Replaces references to environment variable by the actual value of the environment variable.
takeStartComment() [1/2]
QCString ConfigImpl::takeStartComment () [inline]
Take the user start comment and reset it internally
Returns
user start comment
Definition at line 577 of file configimpl.h.
    {
      QCString result=m_startComment;
      m_startComment.resize(0);
      return substitute(result,"\r","");
    }
References m_startComment, QCString::resize(), and substitute().
Referenced by writeTemplate().
takeStartComment() [2/2]
QCString ConfigImpl::takeStartComment () [inline]
Take the user start comment and reset it internally
Returns
user start comment
Definition at line 577 of file configimpl.h.
    {
      QCString result=m_startComment;
      m_startComment.resize(0);
      return substitute(result,"\r","");
    }
References m_startComment, QCString::resize(), and substitute().
takeStoreRepl() [1/2]
QCString ConfigImpl::takeStoreRepl () [inline]
Take the replacement string
Returns
the replacement string
Definition at line 595 of file configimpl.h.
    {
      QCString result=m_storeRepl;
      m_storeRepl.resize(0);
      return substitute(result,"\r","");
    }
References m_storeRepl, QCString::resize(), and substitute().
Referenced by compareDoxyfile().
takeStoreRepl() [2/2]
QCString ConfigImpl::takeStoreRepl () [inline]
Take the replacement string
Returns
the replacement string
Definition at line 595 of file configimpl.h.
    {
      QCString result=m_storeRepl;
      m_storeRepl.resize(0);
      return substitute(result,"\r","");
    }
References m_storeRepl, QCString::resize(), and substitute().
takeUserComment() [1/2]
QCString ConfigImpl::takeUserComment () [inline]
Take the user comment and reset it internally
Returns
user comment
Definition at line 586 of file configimpl.h.
    {
      QCString result=m_userComment;
      m_userComment.resize(0);
      return substitute(result,"\r","");
    }
References m_userComment, QCString::resize(), and substitute().
Referenced by writeTemplate().
takeUserComment() [2/2]
QCString ConfigImpl::takeUserComment () [inline]
Take the user comment and reset it internally
Returns
user comment
Definition at line 586 of file configimpl.h.
    {
      QCString result=m_userComment;
      m_userComment.resize(0);
      return substitute(result,"\r","");
    }
References m_userComment, QCString::resize(), and substitute().
writeTemplate() [1/2]
void ConfigImpl::writeTemplate (TextStream & t, bool shortIndex, bool updateOnly)
Writes a template configuration to stream t. If shortIndex is TRUE the description of each configuration option will be omitted.
Definition at line 1291 of file configimpl.l.
{
  /* print first lines of user comment that were at the beginning of the file, might have special meaning for editors */
  if (!m_startComment.isEmpty())
  {
    t << takeStartComment() << "\n";
  }
  t << "# Doxyfile " << getDoxygenVersion() << "\n\n";
  if (!sl)
  {
    t << convertToComment(m_header,"");
  }
  for (const auto &option : m_options)
  {
    option->writeTemplate(t,sl,upd);
  }
  /* print last lines of user comment that were at the end of the file */
  if (!m_userComment.isEmpty())
  {
    t << "\n";
    t << takeUserComment();
  }
}
References convertToComment(), getDoxygenVersion(), QCString::isEmpty(), m_header, m_options, m_startComment, m_userComment, caseconvert::sl, takeStartComment(), takeUserComment(), and ConfigOption::writeTemplate().
Referenced by Config::writeTemplate().
writeTemplate() [2/2]
void ConfigImpl::writeTemplate (TextStream & t, bool shortIndex, bool updateOnly)
Writes a template configuration to stream t. If shortIndex is TRUE the description of each configuration option will be omitted.
writeXMLDoxyfile() [1/2]
void ConfigImpl::writeXMLDoxyfile (TextStream & t)
Writes a the used settings of the current configuration as XML format to stream t.
Definition at line 1331 of file configimpl.l.
{
  t << "<?xml version='1.0' encoding='UTF-8' standalone='no'?>\n";
  t << "<doxyfile xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:noNamespaceSchemaLocation=\"doxyfile.xsd\" version=\"" << getDoxygenVersion() << "\" xml:lang=\"" << theTranslator->trISOLang() << "\">\n";
  for (const auto &option : m_options)
  {
    option->writeXMLDoxyfile(t);
  }
  t << "</doxyfile>\n";
}
References getDoxygenVersion(), m_options, theTranslator, Translator::trISOLang(), and ConfigOption::writeXMLDoxyfile().
Referenced by Config::writeXMLDoxyfile().
writeXMLDoxyfile() [2/2]
void ConfigImpl::writeXMLDoxyfile (TextStream & t)
Writes a the used settings of the current configuration as XML format to stream t.
Member Data Documentation
m_dict
ConfigOptionMap ConfigImpl::m_dict [private]
Definition at line 617 of file configimpl.h.
Referenced by addBool(), addDisabled(), addEnum(), addInt(), addList(), addObsolete(), addString(), get(), getBool(), getEnum(), getInt(), getList(), and getString().
m_disabled
ConfigOptionList ConfigImpl::m_disabled [private]
Definition at line 616 of file configimpl.h.
Referenced by addDisabled().
m_header
QCString ConfigImpl::m_header [private]
Definition at line 623 of file configimpl.h.
Referenced by setHeader(), and writeTemplate().
m_initialized
bool ConfigImpl::m_initialized [private]
Definition at line 622 of file configimpl.h.
Referenced by ConfigImpl(), and create().
m_instance
ConfigImpl * ConfigImpl::m_instance = 0 [static], [private]
Definition at line 618 of file configimpl.h.
Referenced by deleteInstance(), and instance().
m_obsolete
ConfigOptionList ConfigImpl::m_obsolete [private]
Definition at line 615 of file configimpl.h.
Referenced by addObsolete().
m_options
ConfigOptionList ConfigImpl::m_options [private]
Definition at line 614 of file configimpl.h.
Referenced by addBool(), addEnum(), addInfo(), addInt(), addList(), addString(), compareDoxyfile(), convertStrToVal(), emptyValueToDefault(), init(), substituteEnvironmentVars(), writeTemplate(), and writeXMLDoxyfile().
m_startComment
QCString ConfigImpl::m_startComment [private]
Definition at line 619 of file configimpl.h.
Referenced by appendStartComment(), takeStartComment(), and writeTemplate().
m_storeRepl
QCString ConfigImpl::m_storeRepl [private]
Definition at line 621 of file configimpl.h.
Referenced by appendStoreRepl(), compareDoxyfile(), and takeStoreRepl().
m_userComment
QCString ConfigImpl::m_userComment [private]
Definition at line 620 of file configimpl.h.
Referenced by appendUserComment(), takeUserComment(), and writeTemplate().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/configimpl.h
doxygen/src/configimpl.h
doxygen/build/doxygen/src/configimpl.l
doxygen/src/configimpl.l