TranslatorSerbian Class Reference
#include <translator_sr.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
Ovo je u skladu sa `unutrašnja klasa` što se može videti u knjizi.
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int)
virtual QCString trInheritedByList (int)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int)
virtual QCString trImplementedInList (int)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trInterfaces ()
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
Ovo je u skladu sa `unutrašnja klasa` što se može videti u knjizi.
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int)
virtual QCString trInheritedByList (int)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int)
virtual QCString trImplementedInList (int)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trInterfaces ()
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
Additional Inherited Members
Detailed Description
Definition at line 27 of file translator_sr.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorSerbian::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 65 of file translator_sr.h.
    {
      return "0x81A Serbian (Serbia, Latin)";
    }
getLanguageString() [2/2]
virtual QCString TranslatorSerbian::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 65 of file translator_sr.h.
    {
      return "0x81A Serbian (Serbia, Latin)";
    }
idLanguage() [1/2]
virtual QCString TranslatorSerbian::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 39 of file translator_sr.h.
    { return "serbian"; }
idLanguage() [2/2]
virtual QCString TranslatorSerbian::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 39 of file translator_sr.h.
    { return "serbian"; }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorSerbian::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 56 of file translator_sr.h.
    {
      QCString result="\\usepackage[serbian]{babel}\n";
      return result;
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorSerbian::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 56 of file translator_sr.h.
    {
      QCString result="\\usepackage[serbian]{babel}\n";
      return result;
    }
trAll() [1/2]
virtual QCString TranslatorSerbian::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1385 of file translator_sr.h.
    {
      return "Sve";
    }
trAll() [2/2]
virtual QCString TranslatorSerbian::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1385 of file translator_sr.h.
    {
      return "Sve";
    }
trAttention() [1/2]
virtual QCString TranslatorSerbian::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 948 of file translator_sr.h.
    {
      return "Pažnja";
    }
trAttention() [2/2]
virtual QCString TranslatorSerbian::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 948 of file translator_sr.h.
    {
      return "Pažnja";
    }
trAuthor() [1/2]
virtual QCString TranslatorSerbian::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1256 of file translator_sr.h.
    {
      QCString result((first_capital ? "Autor" : "autor"));
      result+= (singular ? "" : "i");
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorSerbian::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1256 of file translator_sr.h.
    {
      QCString result((first_capital ? "Autor" : "autor"));
      result+= (singular ? "" : "i");
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorSerbian::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1113 of file translator_sr.h.
    {
      return "Greška";
    }
trBug() [2/2]
virtual QCString TranslatorSerbian::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1113 of file translator_sr.h.
    {
      return "Greška";
    }
trBugList() [1/2]
virtual QCString TranslatorSerbian::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1118 of file translator_sr.h.
    {
      return "Spisak grešaka";
    }
trBugList() [2/2]
virtual QCString TranslatorSerbian::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1118 of file translator_sr.h.
    {
      return "Spisak grešaka";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorSerbian::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph Možda je bolje `Graf pozivalaca ove funkcije`
Implements Translator.
Definition at line 1505 of file translator_sr.h.
    {
      return "Graf funkcija koje pozivaju ovu funkciju:";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorSerbian::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph Možda je bolje `Graf pozivalaca ove funkcije`
Implements Translator.
Definition at line 1505 of file translator_sr.h.
    {
      return "Graf funkcija koje pozivaju ovu funkciju:";
    }
trCallGraph() [1/2]
virtual QCString TranslatorSerbian::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1390 of file translator_sr.h.
    {
      return "Graf poziva iz ove funkcije:";
    }
trCallGraph() [2/2]
virtual QCString TranslatorSerbian::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1390 of file translator_sr.h.
    {
      return "Graf poziva iz ove funkcije:";
    }
trClass() [1/2]
virtual QCString TranslatorSerbian::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1176 of file translator_sr.h.
    {
      QCString result((first_capital ? "Klas" : "klas"));
      result+= (singular ? "a" : "e");
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorSerbian::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1176 of file translator_sr.h.
    {
      QCString result((first_capital ? "Klas" : "klas"));
      result+= (singular ? "a" : "e");
      return result;
    }
trClassDiagram() [1/2]
virtual QCString TranslatorSerbian::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 501 of file translator_sr.h.
    {
      return QCString("Dijagram nasleđivanja za klasu ") + clName + ":";
    }
trClassDiagram() [2/2]
virtual QCString TranslatorSerbian::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 501 of file translator_sr.h.
    {
      return QCString("Dijagram nasleđivanja za klasu ") + clName + ":";
    }
trClassDocumentation() [1/2]
virtual QCString TranslatorSerbian::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 376 of file translator_sr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentacija stuktura/unija";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Dokumentacija klasa";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorSerbian::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 376 of file translator_sr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentacija stuktura/unija";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Dokumentacija klasa";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorSerbian::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1076 of file translator_sr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Strukture i unije";
      }
      else
      {
        return "Klase";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorSerbian::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1076 of file translator_sr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Strukture i unije";
      }
      else
      {
        return "Klase";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorSerbian::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 163 of file translator_sr.h.
    { return "Hijerarhija klasa"; }
trClassHierarchy() [2/2]
virtual QCString TranslatorSerbian::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 163 of file translator_sr.h.
    { return "Hijerarhija klasa"; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorSerbian::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 222 of file translator_sr.h.
    { return "Hijerahija klasa uređena približno po abecedi:"; }
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorSerbian::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 222 of file translator_sr.h.
    { return "Hijerahija klasa uređena približno po abecedi:"; }
trCode() [1/2]
virtual QCString TranslatorSerbian::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 848 of file translator_sr.h.
    {
      return "programski kod";
    }
trCode() [2/2]
virtual QCString TranslatorSerbian::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 848 of file translator_sr.h.
    {
      return "programski kod";
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorSerbian::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 803 of file translator_sr.h.
    {
      return "Klasni dijagram za "+clName+":";
    }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorSerbian::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 803 of file translator_sr.h.
    {
      return "Klasni dijagram za "+clName+":";
    }
trCompoundIndex() [1/2]
virtual QCString TranslatorSerbian::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 349 of file translator_sr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Spisak struktura/unija";
      }
      else
      {
        return "Spisak klasa";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorSerbian::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 349 of file translator_sr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Spisak struktura/unija";
      }
      else
      {
        return "Spisak klasa";
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorSerbian::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1561 of file translator_sr.h.
    { return "Sadržaj složenog tipa podataka"; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorSerbian::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1561 of file translator_sr.h.
    { return "Sadržaj složenog tipa podataka"; }
trCompoundList() [1/2]
virtual QCString TranslatorSerbian::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 167 of file translator_sr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Spisak struktura";
      }
      else
      {
        return "Spisak klasa";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorSerbian::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 167 of file translator_sr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Spisak struktura";
      }
      else
      {
        return "Spisak klasa";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorSerbian::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 235 of file translator_sr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Spisak struktura sa kratkim opisima:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Spisak klasa sa kratkim opisima:";
      }
      else
      {
        return "Spisak klasa, struktura, unija i interfejsa sa kratkim opisima:";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorSerbian::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 235 of file translator_sr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Spisak struktura sa kratkim opisima:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Spisak klasa sa kratkim opisima:";
      }
      else
      {
        return "Spisak klasa, struktura, unija i interfejsa sa kratkim opisima:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorSerbian::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1534 of file translator_sr.h.
    { return "Spisak složenih tipova podataka sa kratkim opisima:"; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorSerbian::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1534 of file translator_sr.h.
    { return "Spisak složenih tipova podataka sa kratkim opisima:"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorSerbian::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1526 of file translator_sr.h.
    { return "Složeni tipovi podataka"; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorSerbian::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1526 of file translator_sr.h.
    { return "Složeni tipovi podataka"; }
trCompoundMembers() [1/2]
virtual QCString TranslatorSerbian::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 184 of file translator_sr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Sva polja struktura";
      }
      else
      {
        return "Svi članovi klasa";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorSerbian::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 184 of file translator_sr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Sva polja struktura";
      }
      else
      {
        return "Svi članovi klasa";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorSerbian::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 253 of file translator_sr.h.
    {
      QCString result="Spisak svih ";
      if (!extractAll)
      {
        result+="dokumentovanih ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="članova struktura/unija";
      }
      else
      {
        result+="članova klasa";
      }
      result+=" sa vezama ka ";
      if (extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="dokumentaciji svakog polja strukture/unije:";
        }
        else
        {
          result+="dokumentaciji svakog člana klase:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="strukturama/unijama kojima pripadaju:";
        }
        else
        {
          result+="klasama kojima pripadaju:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorSerbian::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 253 of file translator_sr.h.
    {
      QCString result="Spisak svih ";
      if (!extractAll)
      {
        result+="dokumentovanih ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="članova struktura/unija";
      }
      else
      {
        result+="članova klasa";
      }
      result+=" sa vezama ka ";
      if (extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="dokumentaciji svakog polja strukture/unije:";
        }
        else
        {
          result+="dokumentaciji svakog člana klase:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="strukturama/unijama kojima pripadaju:";
        }
        else
        {
          result+="klasama kojima pripadaju:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorSerbian::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1538 of file translator_sr.h.
    {
      QCString result=" Spisak svih ";
      if (!extractAll)
      {
        result+="dokumentovanih ";
      }
      result+="polja složenih tipova podataka";
      result+=" sa vezama ka ";
      if (!extractAll)
      {
         result+="dokumentaciji strukture podataka za svakog člana";
      }
      else
      {
         result+="složenim tipovima podataka kojima pripadaju:";
      }
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorSerbian::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1538 of file translator_sr.h.
    {
      QCString result=" Spisak svih ";
      if (!extractAll)
      {
        result+="dokumentovanih ";
      }
      result+="polja složenih tipova podataka";
      result+=" sa vezama ka ";
      if (!extractAll)
      {
         result+="dokumentaciji strukture podataka za svakog člana";
      }
      else
      {
         result+="složenim tipovima podataka kojima pripadaju:";
      }
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorSerbian::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1530 of file translator_sr.h.
    { return "Polja u složenim tipovima podataka"; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorSerbian::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1530 of file translator_sr.h.
    { return "Polja u složenim tipovima podataka"; }
trCompoundReference() [1/2]
virtual QCString TranslatorSerbian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 576 of file translator_sr.h.
    {
      QCString result("Dokumentacija ");
      switch(compType)
      {
        case ClassDef::Class: result+="klase "; break;
        case ClassDef::Struct: result+="strukture "; break;
        case ClassDef::Union: result+="unije "; break;
        case ClassDef::Interface: result+="interfejsa "; break;
        case ClassDef::Protocol: result+="protokola "; break;
        case ClassDef::Category: result+="kategorije "; break;
        case ClassDef::Exception: result+="izuzetka "; break;
        default: break;
      }
      if (isTemplate) result += "šablona ";
      result += clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorSerbian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 576 of file translator_sr.h.
    {
      QCString result("Dokumentacija ");
      switch(compType)
      {
        case ClassDef::Class: result+="klase "; break;
        case ClassDef::Struct: result+="strukture "; break;
        case ClassDef::Union: result+="unije "; break;
        case ClassDef::Interface: result+="interfejsa "; break;
        case ClassDef::Protocol: result+="protokola "; break;
        case ClassDef::Category: result+="kategorije "; break;
        case ClassDef::Exception: result+="izuzetka "; break;
        default: break;
      }
      if (isTemplate) result += "šablona ";
      result += clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorSerbian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1602 of file translator_sr.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" Modul"; break;
        case ClassDef::Struct: result+=" Tip"; break;
        case ClassDef::Union: result+=" Unija"; break;
        case ClassDef::Interface: result+=" Interfejs"; break;
        case ClassDef::Protocol: result+=" Protokol"; break;
        case ClassDef::Category: result+=" Kategorija"; break;
        case ClassDef::Exception: result+=" Izuzetak"; break;
        default: break;
      }
      result+=" - sažet pregled";
      if (isTemplate) result+=" šablona";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorSerbian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1602 of file translator_sr.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" Modul"; break;
        case ClassDef::Struct: result+=" Tip"; break;
        case ClassDef::Union: result+=" Unija"; break;
        case ClassDef::Interface: result+=" Interfejs"; break;
        case ClassDef::Protocol: result+=" Protokol"; break;
        case ClassDef::Category: result+=" Kategorija"; break;
        case ClassDef::Exception: result+=" Izuzetak"; break;
        default: break;
      }
      result+=" - sažet pregled";
      if (isTemplate) result+=" šablona";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorSerbian::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 477 of file translator_sr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Strukture i unije";
      }
      else
      {
        return "Klase, strukture i unije";
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorSerbian::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 477 of file translator_sr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Strukture i unije";
      }
      else
      {
        return "Klase, strukture i unije";
      }
    }
References Config_getBool.
trConstructorDocumentation() [1/2]
virtual QCString TranslatorSerbian::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 813 of file translator_sr.h.
    {
      return "Dokumentacija konstruktora i destruktora";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorSerbian::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 813 of file translator_sr.h.
    {
      return "Dokumentacija konstruktora i destruktora";
    }
trDataTypes() [1/2]
virtual QCString TranslatorSerbian::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1585 of file translator_sr.h.
    { return "Složeni tipovi podataka"; }
trDataTypes() [2/2]
virtual QCString TranslatorSerbian::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1585 of file translator_sr.h.
    { return "Složeni tipovi podataka"; }
trDate() [1/2]
virtual QCString TranslatorSerbian::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 515 of file translator_sr.h.
    { return "Datum"; }
trDate() [2/2]
virtual QCString TranslatorSerbian::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 515 of file translator_sr.h.
    { return "Datum"; }
trDayOfWeek() [1/2]
virtual QCString TranslatorSerbian::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1723 of file translator_sr.h.
    {
      static const char *days_short[] = { "pon", "uto", "sre", "čet", "pet", "sub", "ned" };
      static const char *days_full[] = { "ponedeljak", "utorak", "sreda", "četvrtak", "petak", "subota", "nedelja" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayOfWeek() [2/2]
virtual QCString TranslatorSerbian::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1723 of file translator_sr.h.
    {
      static const char *days_short[] = { "pon", "uto", "sre", "čet", "pet", "sub", "ned" };
      static const char *days_full[] = { "ponedeljak", "utorak", "sreda", "četvrtak", "petak", "subota", "nedelja" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod() [1/2]
virtual QCString TranslatorSerbian::trDayPeriod (int period) [inline], [virtual]
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1739 of file translator_sr.h.
    {
      static const char *dayPeriod[] = { "pre podne", "po podne" };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorSerbian::trDayPeriod (int period) [inline], [virtual]
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1739 of file translator_sr.h.
    {
      static const char *dayPeriod[] = { "pre podne", "po podne" };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorSerbian::trDefinedAtLineInSourceFile () [inline], [virtual]
Izbacujemo rod
Implements Translator.
Definition at line 780 of file translator_sr.h.
    {
      return "Definicija je u redu @0 datoteke @1.";
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorSerbian::trDefinedAtLineInSourceFile () [inline], [virtual]
Izbacujemo rod
Implements Translator.
Definition at line 780 of file translator_sr.h.
    {
      return "Definicija je u redu @0 datoteke @1.";
    }
trDefinedIn() [1/2]
virtual QCString TranslatorSerbian::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 151 of file translator_sr.h.
    { return "definicija u"; }
trDefinedIn() [2/2]
virtual QCString TranslatorSerbian::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 151 of file translator_sr.h.
    { return "definicija u"; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorSerbian::trDefinedInSourceFile () [inline], [virtual]
Izbacujemo rod
Implements Translator.
Definition at line 784 of file translator_sr.h.
    {
      return "Definicija je u datoteci @0.";
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorSerbian::trDefinedInSourceFile () [inline], [virtual]
Izbacujemo rod
Implements Translator.
Definition at line 784 of file translator_sr.h.
    {
      return "Definicija je u datoteci @0.";
    }
trDefineDocumentation() [1/2]
virtual QCString TranslatorSerbian::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 447 of file translator_sr.h.
    { return "Dokumentacija makro zamene"; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorSerbian::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 447 of file translator_sr.h.
    { return "Dokumentacija makro zamene"; }
trDefines() [1/2]
virtual QCString TranslatorSerbian::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 411 of file translator_sr.h.
    { return "Makro zamene"; }
trDefines() [2/2]
virtual QCString TranslatorSerbian::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 411 of file translator_sr.h.
    { return "Makro zamene"; }
trDefineValue() [1/2]
virtual QCString TranslatorSerbian::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1103 of file translator_sr.h.
    {
      return "Vrednost:";
    }
trDefineValue() [2/2]
virtual QCString TranslatorSerbian::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1103 of file translator_sr.h.
    {
      return "Vrednost:";
    }
trDeprecated() [1/2]
virtual QCString TranslatorSerbian::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 793 of file translator_sr.h.
    {
      return "Zastarelo";
    }
trDeprecated() [2/2]
virtual QCString TranslatorSerbian::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 793 of file translator_sr.h.
    {
      return "Zastarelo";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorSerbian::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1313 of file translator_sr.h.
    {
      return "Spisak zastarelih stvari";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorSerbian::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1313 of file translator_sr.h.
    {
      return "Spisak zastarelih stvari";
    }
trDetailedDescription() [1/2]
virtual QCString TranslatorSerbian::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 83 of file translator_sr.h.
    { return "Opširniji opis"; }
trDetailedDescription() [2/2]
virtual QCString TranslatorSerbian::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 83 of file translator_sr.h.
    { return "Opširniji opis"; }
trDir() [1/2]
virtual QCString TranslatorSerbian::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1480 of file translator_sr.h.
    {
      QCString result((first_capital ? "Direktorijum" : "direktorijum"));
      if (!singular) result+="i";
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorSerbian::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1480 of file translator_sr.h.
    {
      QCString result((first_capital ? "Direktorijum" : "direktorijum"));
      if (!singular) result+="i";
      return result;
    }
trDirDocumentation() [1/2]
virtual QCString TranslatorSerbian::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1462 of file translator_sr.h.
    { return "Dokumentacija direktorijuma"; }
trDirDocumentation() [2/2]
virtual QCString TranslatorSerbian::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1462 of file translator_sr.h.
    { return "Dokumentacija direktorijuma"; }
trDirectories() [1/2]
virtual QCString TranslatorSerbian::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1468 of file translator_sr.h.
    { return "Direktorijumi"; }
trDirectories() [2/2]
virtual QCString TranslatorSerbian::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1468 of file translator_sr.h.
    { return "Direktorijumi"; }
trDirIndex() [1/2]
virtual QCString TranslatorSerbian::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1456 of file translator_sr.h.
    { return "Hijerarhija direktorijuma"; }
trDirIndex() [2/2]
virtual QCString TranslatorSerbian::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1456 of file translator_sr.h.
    { return "Hijerarhija direktorijuma"; }
trDirReference() [1/2]
virtual QCString TranslatorSerbian::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1474 of file translator_sr.h.
    { QCString result=dirName; result+="Opis direktorijuma"; return result; }
trDirReference() [2/2]
virtual QCString TranslatorSerbian::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1474 of file translator_sr.h.
    { QCString result=dirName; result+="Opis direktorijuma"; return result; }
trDocumentation() [1/2]
virtual QCString TranslatorSerbian::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 331 of file translator_sr.h.
    { return "Dokumentacija"; }
trDocumentation() [2/2]
virtual QCString TranslatorSerbian::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 331 of file translator_sr.h.
    { return "Dokumentacija"; }
trEnumerations() [1/2]
virtual QCString TranslatorSerbian::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 423 of file translator_sr.h.
    { return "Nabrajanja"; }
trEnumerations() [2/2]
virtual QCString TranslatorSerbian::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 423 of file translator_sr.h.
    { return "Nabrajanja"; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorSerbian::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 459 of file translator_sr.h.
    { return "Dokumentacija nabrajanja"; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorSerbian::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 459 of file translator_sr.h.
    { return "Dokumentacija nabrajanja"; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorSerbian::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1513 of file translator_sr.h.
    { return "Dokumentacija enum vrednosti"; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorSerbian::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1513 of file translator_sr.h.
    { return "Dokumentacija enum vrednosti"; }
trEnumerationValues() [1/2]
virtual QCString TranslatorSerbian::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 441 of file translator_sr.h.
    { return "Vrednosti nabrojanih konstanti"; }
trEnumerationValues() [2/2]
virtual QCString TranslatorSerbian::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 441 of file translator_sr.h.
    { return "Vrednosti nabrojanih konstanti"; }
trEnumName() [1/2]
virtual QCString TranslatorSerbian::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 143 of file translator_sr.h.
    { return "ime nabrajanja "; }
trEnumName() [2/2]
virtual QCString TranslatorSerbian::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 143 of file translator_sr.h.
    { return "ime nabrajanja "; }
trEnumValue() [1/2]
virtual QCString TranslatorSerbian::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 147 of file translator_sr.h.
    { return "vrednost nabrojane konstante"; }
trEnumValue() [2/2]
virtual QCString TranslatorSerbian::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 147 of file translator_sr.h.
    { return "vrednost nabrojane konstante"; }
trEventDocumentation() [1/2]
virtual QCString TranslatorSerbian::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1330 of file translator_sr.h.
    {
      return "Dokumentacija događaja";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorSerbian::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1330 of file translator_sr.h.
    {
      return "Dokumentacija događaja";
    }
trEvents() [1/2]
virtual QCString TranslatorSerbian::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1325 of file translator_sr.h.
    {
      return "Događaji";
    }
trEvents() [2/2]
virtual QCString TranslatorSerbian::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1325 of file translator_sr.h.
    {
      return "Događaji";
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorSerbian::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 401 of file translator_sr.h.
    { return "Dokumentacija primera"; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorSerbian::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 401 of file translator_sr.h.
    { return "Dokumentacija primera"; }
trExamples() [1/2]
virtual QCString TranslatorSerbian::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 214 of file translator_sr.h.
    { return "Primeri"; }
trExamples() [2/2]
virtual QCString TranslatorSerbian::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 214 of file translator_sr.h.
    { return "Primeri"; }
trExamplesDescription() [1/2]
virtual QCString TranslatorSerbian::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 317 of file translator_sr.h.
    { return "Spisak svih primera:"; }
trExamplesDescription() [2/2]
virtual QCString TranslatorSerbian::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 317 of file translator_sr.h.
    { return "Spisak svih primera:"; }
trExceptions() [1/2]
virtual QCString TranslatorSerbian::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 531 of file translator_sr.h.
    { return "Izuzeci"; }
trExceptions() [2/2]
virtual QCString TranslatorSerbian::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 531 of file translator_sr.h.
    { return "Izuzeci"; }
trFile() [1/2]
virtual QCString TranslatorSerbian::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1187 of file translator_sr.h.
    {
      QCString result((first_capital ? "Datotek" : "datotek"));
      result+= (singular ? "a" : "e");
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorSerbian::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1187 of file translator_sr.h.
    {
      QCString result((first_capital ? "Datotek" : "datotek"));
      result+= (singular ? "a" : "e");
      return result;
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorSerbian::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 395 of file translator_sr.h.
    { return "Dokumentacija datoteke"; }
trFileDocumentation() [2/2]
virtual QCString TranslatorSerbian::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 395 of file translator_sr.h.
    { return "Dokumentacija datoteke"; }
trFileIndex() [1/2]
virtual QCString TranslatorSerbian::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 364 of file translator_sr.h.
    { return "Indeks datoteka"; }
trFileIndex() [2/2]
virtual QCString TranslatorSerbian::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 364 of file translator_sr.h.
    { return "Indeks datoteka"; }
trFileList() [1/2]
virtual QCString TranslatorSerbian::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 180 of file translator_sr.h.
    { return "Spisak datoteka"; }
trFileList() [2/2]
virtual QCString TranslatorSerbian::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 180 of file translator_sr.h.
    { return "Spisak datoteka"; }
trFileListDescription() [1/2]
virtual QCString TranslatorSerbian::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 226 of file translator_sr.h.
    {
      QCString result="Spisak svih ";
      if (!extractAll) result+="dokumentovanih ";
      result+="datoteka, sa kratkim opisima:";
      return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorSerbian::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 226 of file translator_sr.h.
    {
      QCString result="Spisak svih ";
      if (!extractAll) result+="dokumentovanih ";
      result+="datoteka, sa kratkim opisima:";
      return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorSerbian::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 197 of file translator_sr.h.
    {
      //if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      //{
      // return "Članovi datoteke"; // TODO: translate me
      //}
      //else
      //{
      return "Članovi datoteke";
      //}
    }
trFileMembers() [2/2]
virtual QCString TranslatorSerbian::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 197 of file translator_sr.h.
    {
      //if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      //{
      // return "Članovi datoteke"; // TODO: translate me
      //}
      //else
      //{
      return "Članovi datoteke";
      //}
    }
trFileMembersDescription() [1/2]
virtual QCString TranslatorSerbian::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 295 of file translator_sr.h.
    {
      QCString result="Spisak svih ";
      if (!extractAll) result+="dokumentovanih ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funkcija, promenljivih, makro zamena, nabrajanja i definicija tipa";
      }
      else
      {
        result+="članova";
      }
      result+=" sa vezama ka ";
      if (extractAll)
        result+="datotekama u kojima se nalaze:";
      else
        result+="dokumentaciji:";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorSerbian::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 295 of file translator_sr.h.
    {
      QCString result="Spisak svih ";
      if (!extractAll) result+="dokumentovanih ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funkcija, promenljivih, makro zamena, nabrajanja i definicija tipa";
      }
      else
      {
        result+="članova";
      }
      result+=" sa vezama ka ";
      if (extractAll)
        result+="datotekama u kojima se nalaze:";
      else
        result+="dokumentaciji:";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorSerbian::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 598 of file translator_sr.h.
    {
      QCString result = "Opis datoteke ";
      result += fileName;
      return result;
    }
trFileReference() [2/2]
virtual QCString TranslatorSerbian::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 598 of file translator_sr.h.
    {
      QCString result = "Opis datoteke ";
      result += fileName;
      return result;
    }
trFriends() [1/2]
virtual QCString TranslatorSerbian::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 558 of file translator_sr.h.
    { return "Prijatelji"; }
trFriends() [2/2]
virtual QCString TranslatorSerbian::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 558 of file translator_sr.h.
    { return "Prijatelji"; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorSerbian::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 465 of file translator_sr.h.
    { return "Dokumentacija funkcije"; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorSerbian::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 465 of file translator_sr.h.
    { return "Dokumentacija funkcije"; }
trFunctions() [1/2]
virtual QCString TranslatorSerbian::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 429 of file translator_sr.h.
    { return "Funkcije"; }
trFunctions() [2/2]
virtual QCString TranslatorSerbian::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 429 of file translator_sr.h.
    { return "Funkcije"; }
trGeneratedAt() [1/2]
virtual QCString TranslatorSerbian::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 492 of file translator_sr.h.
    {
      QCString result="[" + date + "] Napravljeno automatski ";
      if (!projName.isEmpty()) result+=" za projekat " + projName;
      result+=" upotrebom ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorSerbian::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 492 of file translator_sr.h.
    {
      QCString result="[" + date + "] Napravljeno automatski ";
      if (!projName.isEmpty()) result+=" za projekat " + projName;
      result+=" upotrebom ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorSerbian::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 135 of file translator_sr.h.
    { QCString result="Napravljeno automatski korišćenjem alata Doxygen";
      if (!s.isEmpty()) result+=" za projekat " + s;
      result+=" od izvornog koda.";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorSerbian::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 135 of file translator_sr.h.
    { QCString result="Napravljeno automatski korišćenjem alata Doxygen";
      if (!s.isEmpty()) result+=" za projekat " + s;
      result+=" od izvornog koda.";
      return result;
    }
References s.
trGeneratedBy() [1/2]
virtual QCString TranslatorSerbian::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 535 of file translator_sr.h.
    { return "Napravio"; }
trGeneratedBy() [2/2]
virtual QCString TranslatorSerbian::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 535 of file translator_sr.h.
    { return "Napravio"; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorSerbian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 736 of file translator_sr.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentacija ";
      switch(compType)
      {
        case ClassDef::Class: result+="ove klase"; break;
        case ClassDef::Struct: result+="ove strukture"; break;
        case ClassDef::Union: result+="ove unije"; break;
        case ClassDef::Interface: result+="ovog interfejsa"; break;
        case ClassDef::Protocol: result+="ovog protokola"; break;
        case ClassDef::Category: result+="ove kategorije"; break;
        case ClassDef::Exception: result+="ovog izuzetka"; break;
        default: break;
      }
      result+=" je napravljena na osnovu ";
      if (single) result+="datoteke "; else result+="sledećih datoteka:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorSerbian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 736 of file translator_sr.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentacija ";
      switch(compType)
      {
        case ClassDef::Class: result+="ove klase"; break;
        case ClassDef::Struct: result+="ove strukture"; break;
        case ClassDef::Union: result+="ove unije"; break;
        case ClassDef::Interface: result+="ovog interfejsa"; break;
        case ClassDef::Protocol: result+="ovog protokola"; break;
        case ClassDef::Category: result+="ove kategorije"; break;
        case ClassDef::Exception: result+="ovog izuzetka"; break;
        default: break;
      }
      result+=" je napravljena na osnovu ";
      if (single) result+="datoteke "; else result+="sledećih datoteka:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorSerbian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1670 of file translator_sr.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentacija za ovaj ";
      switch(compType)
      {
        case ClassDef::Class: result+="modul"; break;
        case ClassDef::Struct: result+="tip"; break;
        case ClassDef::Union: result+="uniju"; break;
        case ClassDef::Interface: result+="interfejs"; break;
        case ClassDef::Protocol: result+="protokol"; break;
        case ClassDef::Category: result+="kategoriju"; break;
        case ClassDef::Exception: result+="izuzetak"; break;
        default: break;
      }
      result+=" napravljena je automatski od sledeć";
      if (single) result+="e datoteke:"; else result+="ih datoteka:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorSerbian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1670 of file translator_sr.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentacija za ovaj ";
      switch(compType)
      {
        case ClassDef::Class: result+="modul"; break;
        case ClassDef::Struct: result+="tip"; break;
        case ClassDef::Union: result+="uniju"; break;
        case ClassDef::Interface: result+="interfejs"; break;
        case ClassDef::Protocol: result+="protokol"; break;
        case ClassDef::Category: result+="kategoriju"; break;
        case ClassDef::Exception: result+="izuzetak"; break;
        default: break;
      }
      result+=" napravljena je automatski od sledeć";
      if (single) result+="e datoteke:"; else result+="ih datoteka:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorSerbian::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1243 of file translator_sr.h.
    {
      QCString result((first_capital ? "Globalni " : "globalni "));
      result+= (singular ? "podatak" : "podaci");
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorSerbian::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1243 of file translator_sr.h.
    {
      QCString result((first_capital ? "Globalni " : "globalni "));
      result+= (singular ? "podatak" : "podaci");
      return result;
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorSerbian::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 823 of file translator_sr.h.
    {
      return "Dokumentacija.";
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorSerbian::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 823 of file translator_sr.h.
    {
      return "Dokumentacija.";
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorSerbian::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 856 of file translator_sr.h.
    {
      return "Prikaz hijerarhije klasa u obliku grafa";
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorSerbian::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 856 of file translator_sr.h.
    {
      return "Prikaz hijerarhije klasa u obliku grafa";
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorSerbian::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 818 of file translator_sr.h.
    {
      return "Izvorni kod.";
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorSerbian::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 818 of file translator_sr.h.
    {
      return "Izvorni kod.";
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorSerbian::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 860 of file translator_sr.h.
    {
      return "Prikaz hijerarhije klasa u obliku nazubljenog teksta";
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorSerbian::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 860 of file translator_sr.h.
    {
      return "Prikaz hijerarhije klasa u obliku nazubljenog teksta";
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorSerbian::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 852 of file translator_sr.h.
    {
      return "Hijerarhija klasa u obliku grafa";
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorSerbian::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 852 of file translator_sr.h.
    {
      return "Hijerarhija klasa u obliku grafa";
    }
trGroup() [1/2]
virtual QCString TranslatorSerbian::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1210 of file translator_sr.h.
    {
      QCString result((first_capital ? "Grup" : "grup"));
      result+= (singular ? "a" : "e");
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorSerbian::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1210 of file translator_sr.h.
    {
      QCString result((first_capital ? "Grup" : "grup"));
      result+= (singular ? "a" : "e");
      return result;
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorSerbian::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 343 of file translator_sr.h.
    { return "Hijerarhijski sadržaj"; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorSerbian::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 343 of file translator_sr.h.
    { return "Hijerarhijski sadržaj"; }
trImplementedFromList() [1/2]
virtual QCString TranslatorSerbian::trImplementedFromList (int) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one. `Definiše` je previše kratko, ispada sa de definišu same apstraktne klase
Implements Translator.
Definition at line 1281 of file translator_sr.h.
    {
      return "Definiše apstraktnu funkciju deklarisanu u ";
    }
trImplementedFromList() [2/2]
virtual QCString TranslatorSerbian::trImplementedFromList (int) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one. `Definiše` je previše kratko, ispada sa de definišu same apstraktne klase
Implements Translator.
Definition at line 1281 of file translator_sr.h.
    {
      return "Definiše apstraktnu funkciju deklarisanu u ";
    }
trImplementedInList() [1/2]
virtual QCString TranslatorSerbian::trImplementedInList (int) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member. Izbegavanje roda
Implements Translator.
Definition at line 1289 of file translator_sr.h.
    {
      return "Definicija u ";
    }
trImplementedInList() [2/2]
virtual QCString TranslatorSerbian::trImplementedInList (int) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member. Izbegavanje roda
Implements Translator.
Definition at line 1289 of file translator_sr.h.
    {
      return "Definicija u ";
    }
trInclByDepGraph() [1/2]
virtual QCString TranslatorSerbian::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 952 of file translator_sr.h.
    {
      return "Ovaj graf pokazuje koje datoteke direktno "
             "ili indirektno uključuju ovu datoteku: ";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorSerbian::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 952 of file translator_sr.h.
    {
      return "Ovaj graf pokazuje koje datoteke direktno "
             "ili indirektno uključuju ovu datoteku: ";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorSerbian::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 808 of file translator_sr.h.
    {
      return "Graf zavisnosti datoteka za "+fName+":";
    }
trInclDepGraph() [2/2]
virtual QCString TranslatorSerbian::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 808 of file translator_sr.h.
    {
      return "Graf zavisnosti datoteka za "+fName+":";
    }
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorSerbian::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 129 of file translator_sr.h.
    { return ", uključujući nasleđene članove."; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorSerbian::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 129 of file translator_sr.h.
    { return ", uključujući nasleđene članove."; }
trInheritedByList() [1/2]
virtual QCString TranslatorSerbian::trInheritedByList (int) [inline], [virtual]
used in class documentation to produce a list of derived classes, if class diagrams are disabled.
Implements Translator.
Definition at line 670 of file translator_sr.h.
    {
      return "Spisak izvedenih klasa: ";
    }
trInheritedByList() [2/2]
virtual QCString TranslatorSerbian::trInheritedByList (int) [inline], [virtual]
used in class documentation to produce a list of derived classes, if class diagrams are disabled.
Implements Translator.
Definition at line 670 of file translator_sr.h.
    {
      return "Spisak izvedenih klasa: ";
    }
trInheritsList() [1/2]
virtual QCString TranslatorSerbian::trInheritsList (int) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 662 of file translator_sr.h.
    {
      return "Spisak osnovnih klasa: ";
    }
trInheritsList() [2/2]
virtual QCString TranslatorSerbian::trInheritsList (int) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 662 of file translator_sr.h.
    {
      return "Spisak osnovnih klasa: ";
    }
trInitialValue() [1/2]
virtual QCString TranslatorSerbian::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 843 of file translator_sr.h.
    {
      return "Početna vrednost:";
    }
trInitialValue() [2/2]
virtual QCString TranslatorSerbian::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 843 of file translator_sr.h.
    {
      return "Početna vrednost:";
    }
trInterfaces() [1/2]
virtual QCString TranslatorSerbian::trInterfaces () [inline], [virtual]
Used for Java interfaces in the summary section of Java packages < Radna okruzenja. Ali to je dve reci.
Reimplemented from TranslatorAdapter_1_8_4.
Definition at line 1718 of file translator_sr.h.
    {
      return "Interfejsi";
    }
trInterfaces() [2/2]
virtual QCString TranslatorSerbian::trInterfaces () [inline], [virtual]
Used for Java interfaces in the summary section of Java packages < Radna okruzenja. Ali to je dve reci.
Reimplemented from TranslatorAdapter_1_8_4.
Definition at line 1718 of file translator_sr.h.
    {
      return "Interfejsi";
    }
trInvariant() [1/2]
virtual QCString TranslatorSerbian::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 838 of file translator_sr.h.
    {
      return "Invarijanta";
    }
trInvariant() [2/2]
virtual QCString TranslatorSerbian::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 838 of file translator_sr.h.
    {
      return "Invarijanta";
    }
trISOLang() [1/2]
virtual QCString TranslatorSerbian::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 61 of file translator_sr.h.
    {
      return "sr-Latn";
    }
trISOLang() [2/2]
virtual QCString TranslatorSerbian::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 61 of file translator_sr.h.
    {
      return "sr-Latn";
    }
trLegend() [1/2]
virtual QCString TranslatorSerbian::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1036 of file translator_sr.h.
    {
      return "Objašnjenje korišćenih simbola";
    }
trLegend() [2/2]
virtual QCString TranslatorSerbian::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1036 of file translator_sr.h.
    {
      return "Objašnjenje korišćenih simbola";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorSerbian::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 974 of file translator_sr.h.
    {
      return
        "Ova stranica objašnjava kako tumačiti grafikone koje je napravio "
        "doxygen.<p>\n"
        "Na primer:\n"
        "\\code\n"
        "/*! Klasa nevidljiva zbog trenutnih ograničenja */\n"
        "class Invisible { };\n\n"
        "/*! Klasa kojoj se ne vidi način izvođenja */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Klasa bez doxygen komentara */\n"
        "class Undocumented { };\n\n"
        "/*! Klasa izvedena iz osnovne klase javnim izvođenjem */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! Šablonska klasa */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Klasa izvedena iz osnovne klase zaštićenim izvođenjem */\n"
        "class ProtectedBase { };\n\n"
        "/*! Klasa izvedena iz osnovne klase privatnim izvođenjem */\n"
        "class PrivateBase { };\n\n"
        "/*! Klasa korišćena u nekoj/nekim od drugih klasa */\n"
        "class Used { };\n\n"
        "/*! Klasa izvedena iz više osnovnih klasa */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Ako je \\c MAX_DOT_GRAPH_HEIGHT tag u konfiguracionoj datoteci "
        "postavljen na \\c 200 graf izvođenja će izgledati ovako:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "Graf će biti odsečen ako ne stane unutar zadatih granica.\n"
        "<p>\n"
        "Pravougaonici imaju sledeća značenja:\n"
        "<ul>\n"
         "<li>Puni sivi predstavlja strukturu ili klasu za koju je graf napravljen.\n"
         "<li>Sa crnom ivicom predstavlja dokumentovanu strukturu ili klasu.\n"
         "<li>Sa sivom ivicom predstavlja strukturu ili klasu bez doxygen komentara.\n"
         "<li>Sa crvenom ivicom predstavlja dokumentovanu strukturu ili klasu\n"
         "za koju nisu prikazani svi relevantni grafovi.\n"
         "</ul>"
        "Strelice imaju sledeća značenja:\n"
        "<ul>\n"
         "<li>Tamnoplava strelica označava javno izvođenje.\n"
         "<li>Tamnozelena strelica označava zaštićeno izvođenje.\n"
         "<li>Tamnocrvena strelica označava privatno izvođenje.\n"
         "<li>Ljubičasta isprekidana strelica označava da je klasa sadržana "
          "ili korišćena u drugoj klasi. Strelica je označena imenom atributa "
          "preko koga se pristupa klasi/strukturi na koju pokazuje.\n"
         "<li>Žuta isprekidana strelica označava vezu između primerka šablona i"
          " šablona klase od kojeg je primerak napravljen. "
          "Strelica je označena stvarnim argumentima šablona.\n"
        "</ul>\n"
        ;
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorSerbian::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 974 of file translator_sr.h.
    {
      return
        "Ova stranica objašnjava kako tumačiti grafikone koje je napravio "
        "doxygen.<p>\n"
        "Na primer:\n"
        "\\code\n"
        "/*! Klasa nevidljiva zbog trenutnih ograničenja */\n"
        "class Invisible { };\n\n"
        "/*! Klasa kojoj se ne vidi način izvođenja */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Klasa bez doxygen komentara */\n"
        "class Undocumented { };\n\n"
        "/*! Klasa izvedena iz osnovne klase javnim izvođenjem */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! Šablonska klasa */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Klasa izvedena iz osnovne klase zaštićenim izvođenjem */\n"
        "class ProtectedBase { };\n\n"
        "/*! Klasa izvedena iz osnovne klase privatnim izvođenjem */\n"
        "class PrivateBase { };\n\n"
        "/*! Klasa korišćena u nekoj/nekim od drugih klasa */\n"
        "class Used { };\n\n"
        "/*! Klasa izvedena iz više osnovnih klasa */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Ako je \\c MAX_DOT_GRAPH_HEIGHT tag u konfiguracionoj datoteci "
        "postavljen na \\c 200 graf izvođenja će izgledati ovako:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "Graf će biti odsečen ako ne stane unutar zadatih granica.\n"
        "<p>\n"
        "Pravougaonici imaju sledeća značenja:\n"
        "<ul>\n"
         "<li>Puni sivi predstavlja strukturu ili klasu za koju je graf napravljen.\n"
         "<li>Sa crnom ivicom predstavlja dokumentovanu strukturu ili klasu.\n"
         "<li>Sa sivom ivicom predstavlja strukturu ili klasu bez doxygen komentara.\n"
         "<li>Sa crvenom ivicom predstavlja dokumentovanu strukturu ili klasu\n"
         "za koju nisu prikazani svi relevantni grafovi.\n"
         "</ul>"
        "Strelice imaju sledeća značenja:\n"
        "<ul>\n"
         "<li>Tamnoplava strelica označava javno izvođenje.\n"
         "<li>Tamnozelena strelica označava zaštićeno izvođenje.\n"
         "<li>Tamnocrvena strelica označava privatno izvođenje.\n"
         "<li>Ljubičasta isprekidana strelica označava da je klasa sadržana "
          "ili korišćena u drugoj klasi. Strelica je označena imenom atributa "
          "preko koga se pristupa klasi/strukturi na koju pokazuje.\n"
         "<li>Žuta isprekidana strelica označava vezu između primerka šablona i"
          " šablona klase od kojeg je primerak napravljen. "
          "Strelica je označena stvarnim argumentima šablona.\n"
        "</ul>\n"
        ;
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorSerbian::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 967 of file translator_sr.h.
    {
      return "Objašnjenje korišćenih simbola";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorSerbian::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 967 of file translator_sr.h.
    {
      return "Objašnjenje korišćenih simbola";
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorSerbian::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 117 of file translator_sr.h.
    { return "Spisak svih članova"; }
trListOfAllMembers() [2/2]
virtual QCString TranslatorSerbian::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 117 of file translator_sr.h.
    { return "Spisak svih članova"; }
trMainPage() [1/2]
virtual QCString TranslatorSerbian::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 767 of file translator_sr.h.
    { return "Glavna strana"; }
trMainPage() [2/2]
virtual QCString TranslatorSerbian::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 767 of file translator_sr.h.
    { return "Glavna strana"; }
trMember() [1/2]
virtual QCString TranslatorSerbian::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1232 of file translator_sr.h.
    {
      QCString result((first_capital ? "Član" : "član"));
      result+= (singular ? "" : "ovi");
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorSerbian::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1232 of file translator_sr.h.
    {
      QCString result((first_capital ? "Član" : "član"));
      result+= (singular ? "" : "ovi");
      return result;
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorSerbian::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 100 of file translator_sr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentacija polja";
      }
      else
      {
        return "Dokumentacija atributa";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorSerbian::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 100 of file translator_sr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentacija polja";
      }
      else
      {
        return "Dokumentacija atributa";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorSerbian::trMemberEnumerationDocumentation () [inline], [virtual]
Ovo je u skladu sa `unutrašnja klasa` što se može videti u knjizi.
header that is put before the list of enumerations.
Implements Translator.
Definition at line 91 of file translator_sr.h.
    { return "Dokumentacija unutrašnjih nabrajanja"; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorSerbian::trMemberEnumerationDocumentation () [inline], [virtual]
Ovo je u skladu sa `unutrašnja klasa` što se može videti u knjizi.
header that is put before the list of enumerations.
Implements Translator.
Definition at line 91 of file translator_sr.h.
    { return "Dokumentacija unutrašnjih nabrajanja"; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorSerbian::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 96 of file translator_sr.h.
    { return "Dokumentacija funkcija članica"; }
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorSerbian::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 96 of file translator_sr.h.
    { return "Dokumentacija funkcija članica"; }
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorSerbian::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1521 of file translator_sr.h.
    { return "Dokumentacija funkcija i procedura"; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorSerbian::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1521 of file translator_sr.h.
    { return "Dokumentacija funkcija i procedura"; }
trMemberList() [1/2]
virtual QCString TranslatorSerbian::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 121 of file translator_sr.h.
    { return "Spisak članova"; }
trMemberList() [2/2]
virtual QCString TranslatorSerbian::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 121 of file translator_sr.h.
    { return "Spisak članova"; }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorSerbian::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 87 of file translator_sr.h.
    { return "Dokumentacija unutrašnjih definicija tipa"; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorSerbian::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 87 of file translator_sr.h.
    { return "Dokumentacija unutrašnjih definicija tipa"; }
trModule() [1/2]
virtual QCString TranslatorSerbian::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1661 of file translator_sr.h.
    {
      QCString result((first_capital ? "Modul" : "modul"));
      if (!singular) result+="i";
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorSerbian::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1661 of file translator_sr.h.
    {
      QCString result((first_capital ? "Modul" : "modul"));
      if (!singular) result+="i";
      return result;
    }
trModuleDocumentation() [1/2]
virtual QCString TranslatorSerbian::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 370 of file translator_sr.h.
    { return "Dokumentacija modula"; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorSerbian::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 370 of file translator_sr.h.
    { return "Dokumentacija modula"; }
trModuleIndex() [1/2]
virtual QCString TranslatorSerbian::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 337 of file translator_sr.h.
    { return "Indeks modula"; }
trModuleIndex() [2/2]
virtual QCString TranslatorSerbian::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 337 of file translator_sr.h.
    { return "Indeks modula"; }
trModuleReference() [1/2]
virtual QCString TranslatorSerbian::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1623 of file translator_sr.h.
    {
      QCString result=namespaceName;
      result+=" - sažet pregled modula";
      return result;
    }
trModuleReference() [2/2]
virtual QCString TranslatorSerbian::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1623 of file translator_sr.h.
    {
      QCString result=namespaceName;
      result+=" - sažet pregled modula";
      return result;
    }
trModules() [1/2]
virtual QCString TranslatorSerbian::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 159 of file translator_sr.h.
    { return "Moduli"; }
trModules() [2/2]
virtual QCString TranslatorSerbian::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 159 of file translator_sr.h.
    { return "Moduli"; }
trModulesDescription() [1/2]
virtual QCString TranslatorSerbian::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 325 of file translator_sr.h.
    { return "Spisak svih modula:"; }
trModulesDescription() [2/2]
virtual QCString TranslatorSerbian::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 325 of file translator_sr.h.
    { return "Spisak svih modula:"; }
trModulesIndex() [1/2]
virtual QCString TranslatorSerbian::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1654 of file translator_sr.h.
    { return "Spisak modula"; }
trModulesIndex() [2/2]
virtual QCString TranslatorSerbian::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1654 of file translator_sr.h.
    { return "Spisak modula"; }
trModulesList() [1/2]
virtual QCString TranslatorSerbian::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1589 of file translator_sr.h.
    { return "Spisak modula"; }
trModulesList() [2/2]
virtual QCString TranslatorSerbian::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1589 of file translator_sr.h.
    { return "Spisak modula"; }
trModulesListDescription() [1/2]
virtual QCString TranslatorSerbian::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1593 of file translator_sr.h.
    {
      QCString result="Spisak svih ";
      if (!extractAll) result+="dokumentovanih ";
      result+="modula sa kratkim opisima:";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorSerbian::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1593 of file translator_sr.h.
    {
      QCString result="Spisak svih ";
      if (!extractAll) result+="dokumentovanih ";
      result+="modula sa kratkim opisima:";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorSerbian::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1635 of file translator_sr.h.
    {
      QCString result="Spisak svih ";
      if (!extractAll) result+="dokumentovanih ";
      result+="članova modula sa vezama ka ";
      if (extractAll)
      {
        result+="dokumentaciji za svakog člana modula:";
      }
      else
      {
        result+="modulima kojima pripadaju:";
      }
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorSerbian::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1635 of file translator_sr.h.
    {
      QCString result="Spisak svih ";
      if (!extractAll) result+="dokumentovanih ";
      result+="članova modula sa vezama ka ";
      if (extractAll)
      {
        result+="dokumentaciji za svakog člana modula:";
      }
      else
      {
        result+="modulima kojima pripadaju:";
      }
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorSerbian::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1631 of file translator_sr.h.
    { return "Članovi modula"; }
trModulesMembers() [2/2]
virtual QCString TranslatorSerbian::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1631 of file translator_sr.h.
    { return "Članovi modula"; }
trMonth() [1/2]
virtual QCString TranslatorSerbian::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1731 of file translator_sr.h.
    {
      static const char *months_short[] = { "jan", "feb", "mar", "apr", "maj", "jun", "jul", "avg", "sep", "okt", "nov", "dec" };
      static const char *months_full[] = { "januar", "februar", "mart", "april", "maj", "jun", "jul", "avgust", "septembar", "oktobar", "novembar", "decembar" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMonth() [2/2]
virtual QCString TranslatorSerbian::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1731 of file translator_sr.h.
    {
      static const char *months_short[] = { "jan", "feb", "mar", "apr", "maj", "jun", "jul", "avg", "sep", "okt", "nov", "dec" };
      static const char *months_full[] = { "januar", "februar", "mart", "april", "maj", "jun", "jul", "avgust", "septembar", "oktobar", "novembar", "decembar" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore() [1/2]
virtual QCString TranslatorSerbian::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 113 of file translator_sr.h.
    { return "Još..."; }
trMore() [2/2]
virtual QCString TranslatorSerbian::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 113 of file translator_sr.h.
    { return "Još..."; }
trNamespace() [1/2]
virtual QCString TranslatorSerbian::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1198 of file translator_sr.h.
    {
      QCString result((first_capital ? "Prostor" : "prostor"));
      result += (singular ? "" : "i");
      result += " imena";
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorSerbian::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1198 of file translator_sr.h.
    {
      QCString result((first_capital ? "Prostor" : "prostor"));
      result += (singular ? "" : "i");
      result += " imena";
      return result;
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorSerbian::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 716 of file translator_sr.h.
    { return "Dokumentacija prostora imena"; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorSerbian::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 716 of file translator_sr.h.
    { return "Dokumentacija prostora imena"; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorSerbian::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 710 of file translator_sr.h.
    { return "Indeks prostora imena"; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorSerbian::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 710 of file translator_sr.h.
    { return "Indeks prostora imena"; }
trNamespaceList() [1/2]
virtual QCString TranslatorSerbian::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 543 of file translator_sr.h.
    { return "Spisak prostora imena"; }
trNamespaceList() [2/2]
virtual QCString TranslatorSerbian::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 543 of file translator_sr.h.
    { return "Spisak prostora imena"; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorSerbian::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 547 of file translator_sr.h.
    {
      QCString result="Spisak svih ";
      if (!extractAll) result+="dokumentovanih ";
      result+="prostora imena sa kratkim opisom:";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorSerbian::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 547 of file translator_sr.h.
    {
      QCString result="Spisak svih ";
      if (!extractAll) result+="dokumentovanih ";
      result+="prostora imena sa kratkim opisom:";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorSerbian::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 696 of file translator_sr.h.
    {
      QCString result="Spisak svih ";
      if (!extractAll) result+="dokumentovanih ";
      result+="članova prostora imena sa vezama prema ";
      if (extractAll)
        result+="dokumentaciji svakog člana prostora imena: ";
      else
        result+="prostorima imena kojima pripadaju: ";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorSerbian::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 696 of file translator_sr.h.
    {
      QCString result="Spisak svih ";
      if (!extractAll) result+="dokumentovanih ";
      result+="članova prostora imena sa vezama prema ";
      if (extractAll)
        result+="dokumentaciji svakog člana prostora imena: ";
      else
        result+="prostorima imena kojima pripadaju: ";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorSerbian::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 692 of file translator_sr.h.
    { return "Članovi prostora imena"; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorSerbian::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 692 of file translator_sr.h.
    { return "Članovi prostora imena"; }
trNamespaceReference() [1/2]
virtual QCString TranslatorSerbian::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 606 of file translator_sr.h.
    {
      QCString result="Opis prostora imena ";
      result += namespaceName;
      return result;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorSerbian::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 606 of file translator_sr.h.
    {
      QCString result="Opis prostora imena ";
      result += namespaceName;
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorSerbian::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 726 of file translator_sr.h.
    { return "Prostori imena"; }
trNamespaces() [2/2]
virtual QCString TranslatorSerbian::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 726 of file translator_sr.h.
    { return "Prostori imena"; }
trNote() [1/2]
virtual QCString TranslatorSerbian::trNote () [inline], [virtual]
Implements Translator.
Definition at line 873 of file translator_sr.h.
    {
      return "Beleška";
    }
trNote() [2/2]
virtual QCString TranslatorSerbian::trNote () [inline], [virtual]
Implements Translator.
Definition at line 873 of file translator_sr.h.
    {
      return "Beleška";
    }
trOverloadText() [1/2]
virtual QCString TranslatorSerbian::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1494 of file translator_sr.h.
    {
       return "Ovo je funkcija prekopljenog imena, razlikuje se "
              "od gore navedene samo po argumentima koje prihvata.";
    }
trOverloadText() [2/2]
virtual QCString TranslatorSerbian::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1494 of file translator_sr.h.
    {
       return "Ovo je funkcija prekopljenog imena, razlikuje se "
              "od gore navedene samo po argumentima koje prihvata.";
    }
trPackage() [1/2]
virtual QCString TranslatorSerbian::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1088 of file translator_sr.h.
    {
      return "Paket "+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorSerbian::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1088 of file translator_sr.h.
    {
      return "Paket "+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorSerbian::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1366 of file translator_sr.h.
    {
      return "Atributi u paketu"; // Clanovi u paketu
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorSerbian::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1366 of file translator_sr.h.
    {
      return "Atributi u paketu"; // Clanovi u paketu
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorSerbian::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1348 of file translator_sr.h.
    {
      return "Funkcije u paketu";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorSerbian::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1348 of file translator_sr.h.
    {
      return "Funkcije u paketu";
    }
trPackageListDescription() [1/2]
virtual QCString TranslatorSerbian::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1093 of file translator_sr.h.
    {
      return "Paketi s kratkim opisom (ukoliko postoji):";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorSerbian::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1093 of file translator_sr.h.
    {
      return "Paketi s kratkim opisom (ukoliko postoji):";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorSerbian::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1352 of file translator_sr.h.
    {
      return "Članovi u paketu";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorSerbian::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1352 of file translator_sr.h.
    {
      return "Članovi u paketu";
    }
trPackages() [1/2]
virtual QCString TranslatorSerbian::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1098 of file translator_sr.h.
    {
      return "Paketi";
    }
trPackages() [2/2]
virtual QCString TranslatorSerbian::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1098 of file translator_sr.h.
    {
      return "Paketi";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorSerbian::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1341 of file translator_sr.h.
    {
      return "Tipovi u paketu";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorSerbian::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1341 of file translator_sr.h.
    {
      return "Tipovi u paketu";
    }
trPage() [1/2]
virtual QCString TranslatorSerbian::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1221 of file translator_sr.h.
    {
      QCString result((first_capital ? "Stran" : "stran"));
      result+= (singular ? "a" : "e");
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorSerbian::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1221 of file translator_sr.h.
    {
      QCString result((first_capital ? "Stran" : "stran"));
      result+= (singular ? "a" : "e");
      return result;
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorSerbian::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 773 of file translator_sr.h.
    { return "str."; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorSerbian::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 773 of file translator_sr.h.
    { return "str."; }
trPageIndex() [1/2]
virtual QCString TranslatorSerbian::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 864 of file translator_sr.h.
    {
      return "Indeks stranice";
    }
trPageIndex() [2/2]
virtual QCString TranslatorSerbian::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 864 of file translator_sr.h.
    {
      return "Indeks stranice";
    }
trParameters() [1/2]
virtual QCString TranslatorSerbian::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 527 of file translator_sr.h.
    { return "Parametri"; }
trParameters() [2/2]
virtual QCString TranslatorSerbian::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 527 of file translator_sr.h.
    { return "Parametri"; }
trPostcondition() [1/2]
virtual QCString TranslatorSerbian::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 833 of file translator_sr.h.
    {
      return "Stanje po izvršenju";
    }
trPostcondition() [2/2]
virtual QCString TranslatorSerbian::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 833 of file translator_sr.h.
    {
      return "Stanje po izvršenju";
    }
trPrecondition() [1/2]
virtual QCString TranslatorSerbian::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 828 of file translator_sr.h.
    {
      return "Preduslovi";
    }
trPrecondition() [2/2]
virtual QCString TranslatorSerbian::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 828 of file translator_sr.h.
    {
      return "Preduslovi";
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorSerbian::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 912 of file translator_sr.h.
    {
      return "Privatni članovi";
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorSerbian::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 912 of file translator_sr.h.
    {
      return "Privatni članovi";
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorSerbian::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 627 of file translator_sr.h.
    { return "Privatni članovi"; }
trPrivateMembers() [2/2]
virtual QCString TranslatorSerbian::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 627 of file translator_sr.h.
    { return "Privatni članovi"; }
trPrivateSlots() [1/2]
virtual QCString TranslatorSerbian::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 629 of file translator_sr.h.
    { return "Privatni slotovi"; }
trPrivateSlots() [2/2]
virtual QCString TranslatorSerbian::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 629 of file translator_sr.h.
    { return "Privatni slotovi"; }
trPrivateTypes() [1/2]
virtual QCString TranslatorSerbian::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 908 of file translator_sr.h.
    {
      return "Privatni tipovi";
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorSerbian::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 908 of file translator_sr.h.
    {
      return "Privatni tipovi";
    }
trProperties() [1/2]
virtual QCString TranslatorSerbian::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1061 of file translator_sr.h.
    {
      return "Osobine";
    }
trProperties() [2/2]
virtual QCString TranslatorSerbian::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1061 of file translator_sr.h.
    {
      return "Osobine";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorSerbian::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1066 of file translator_sr.h.
    {
      return "Dokumentacija osobina";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorSerbian::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1066 of file translator_sr.h.
    {
      return "Dokumentacija osobina";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorSerbian::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 900 of file translator_sr.h.
    {
      return "Zaštićeni članovi";
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorSerbian::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 900 of file translator_sr.h.
    {
      return "Zaštićeni članovi";
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorSerbian::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 621 of file translator_sr.h.
    { return "Zaštićeni članovi"; }
trProtectedMembers() [2/2]
virtual QCString TranslatorSerbian::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 621 of file translator_sr.h.
    { return "Zaštićeni članovi"; }
trProtectedSlots() [1/2]
virtual QCString TranslatorSerbian::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 623 of file translator_sr.h.
    { return "Zaštićeni slotovi"; }
trProtectedSlots() [2/2]
virtual QCString TranslatorSerbian::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 623 of file translator_sr.h.
    { return "Zaštićeni slotovi"; }
trProtectedTypes() [1/2]
virtual QCString TranslatorSerbian::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 896 of file translator_sr.h.
    {
      return "Zaštićeni tipovi";
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorSerbian::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 896 of file translator_sr.h.
    {
      return "Zaštićeni tipovi";
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorSerbian::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 881 of file translator_sr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Polja";
      }
      else
      {
        return "Javni članovi";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorSerbian::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 881 of file translator_sr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Polja";
      }
      else
      {
        return "Javni članovi";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorSerbian::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 613 of file translator_sr.h.
    { return "Javni članovi"; }
trPublicMembers() [2/2]
virtual QCString TranslatorSerbian::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 613 of file translator_sr.h.
    { return "Javni članovi"; }
trPublicSlots() [1/2]
virtual QCString TranslatorSerbian::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 615 of file translator_sr.h.
    { return "Javni slotovi"; }
trPublicSlots() [2/2]
virtual QCString TranslatorSerbian::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 615 of file translator_sr.h.
    { return "Javni slotovi"; }
trPublicTypes() [1/2]
virtual QCString TranslatorSerbian::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 877 of file translator_sr.h.
    {
      return "Javni tipovi";
    }
trPublicTypes() [2/2]
virtual QCString TranslatorSerbian::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 877 of file translator_sr.h.
    {
      return "Javni tipovi";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorSerbian::trReferencedBy () [inline], [virtual]
Izbegavanje roda. Uskladjivanje sa trReferences
Implements Translator.
Definition at line 940 of file translator_sr.h.
    {
      return "Korisnici: ";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorSerbian::trReferencedBy () [inline], [virtual]
Izbegavanje roda. Uskladjivanje sa trReferences
Implements Translator.
Definition at line 940 of file translator_sr.h.
    {
      return "Korisnici: ";
    }
trReferenceManual() [1/2]
virtual QCString TranslatorSerbian::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 405 of file translator_sr.h.
    { return "Priručnik"; }
trReferenceManual() [2/2]
virtual QCString TranslatorSerbian::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 405 of file translator_sr.h.
    { return "Priručnik"; }
trReferences() [1/2]
virtual QCString TranslatorSerbian::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1269 of file translator_sr.h.
    {
      return "Koristi";
    }
trReferences() [2/2]
virtual QCString TranslatorSerbian::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1269 of file translator_sr.h.
    {
      return "Koristi";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorSerbian::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 678 of file translator_sr.h.
    {
      return "Menja definiciju iz "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorSerbian::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 678 of file translator_sr.h.
    {
      return "Menja definiciju iz "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorSerbian::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member. Ako već ne možemo jednu reč (redefinicija), da uskladimo sa prethodnim i izbacimo upotrebu roda
Implements Translator.
Definition at line 686 of file translator_sr.h.
    {
      return "Definicija je izmenjena u "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorSerbian::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member. Ako već ne možemo jednu reč (redefinicija), da uskladimo sa prethodnim i izbacimo upotrebu roda
Implements Translator.
Definition at line 686 of file translator_sr.h.
    {
      return "Definicija je izmenjena u "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorSerbian::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 568 of file translator_sr.h.
    { return "Dokumentacija prijatelja i relevantnih funkcija"; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorSerbian::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 568 of file translator_sr.h.
    { return "Dokumentacija prijatelja i relevantnih funkcija"; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorSerbian::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions. Čini se da je ovako manje loše nego `Povezane funkcije`, što uopšte ne izgleda dobro jer ta kartica sadrži prijatelje i globalne funkcije
Implements Translator.
Definition at line 73 of file translator_sr.h.
    { return "Relevantne funkcije"; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorSerbian::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions. Čini se da je ovako manje loše nego `Povezane funkcije`, što uopšte ne izgleda dobro jer ta kartica sadrži prijatelje i globalne funkcije
Implements Translator.
Definition at line 73 of file translator_sr.h.
    { return "Relevantne funkcije"; }
trRelatedPages() [1/2]
virtual QCString TranslatorSerbian::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 210 of file translator_sr.h.
    { return "Stranice koje imaju veze sa ovom stranicom"; }
trRelatedPages() [2/2]
virtual QCString TranslatorSerbian::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 210 of file translator_sr.h.
    { return "Stranice koje imaju veze sa ovom stranicom"; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorSerbian::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 321 of file translator_sr.h.
    { return "Spisak stranica koje imaju veze sa ovom stranicom:"; }
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorSerbian::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 321 of file translator_sr.h.
    { return "Spisak stranica koje imaju veze sa ovom stranicom:"; }
trRelatedSubscript() [1/2]
virtual QCString TranslatorSerbian::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 79 of file translator_sr.h.
    { return "(To nisu funkcije članice.)"; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorSerbian::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 79 of file translator_sr.h.
    { return "(To nisu funkcije članice.)"; }
trRemarks() [1/2]
virtual QCString TranslatorSerbian::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 944 of file translator_sr.h.
    {
      return "Napomene";
    }
trRemarks() [2/2]
virtual QCString TranslatorSerbian::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 944 of file translator_sr.h.
    {
      return "Napomene";
    }
trReturns() [1/2]
virtual QCString TranslatorSerbian::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 519 of file translator_sr.h.
    { return "Vrednost funkcije"; }
trReturns() [2/2]
virtual QCString TranslatorSerbian::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 519 of file translator_sr.h.
    { return "Vrednost funkcije"; }
trReturnValues() [1/2]
virtual QCString TranslatorSerbian::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 762 of file translator_sr.h.
    { return "Karakteristične vrednosti funkcije"; }
trReturnValues() [2/2]
virtual QCString TranslatorSerbian::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 762 of file translator_sr.h.
    { return "Karakteristične vrednosti funkcije"; }
trRTFansicp() [1/2]
virtual QCString TranslatorSerbian::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1152 of file translator_sr.h.
    {
      return "1252";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorSerbian::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1152 of file translator_sr.h.
    {
      return "1252";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorSerbian::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1161 of file translator_sr.h.
    {
      return "238";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorSerbian::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1161 of file translator_sr.h.
    {
      return "238";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorSerbian::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1167 of file translator_sr.h.
    {
      return "Sadržaj";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorSerbian::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1167 of file translator_sr.h.
    {
      return "Sadržaj";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorSerbian::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1301 of file translator_sr.h.
     {
      return "Sadržaj";
     }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorSerbian::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1301 of file translator_sr.h.
     {
      return "Sadržaj";
     }
trSearch() [1/2]
virtual QCString TranslatorSerbian::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 218 of file translator_sr.h.
    { return "Traži"; }
trSearch() [2/2]
virtual QCString TranslatorSerbian::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 218 of file translator_sr.h.
    { return "Traži"; }
trSearchMatches() [1/2]
virtual QCString TranslatorSerbian::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1433 of file translator_sr.h.
    {
      return "Pronađeno:";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorSerbian::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1433 of file translator_sr.h.
    {
      return "Pronađeno:";
    }
trSearchResults() [1/2]
virtual QCString TranslatorSerbian::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1414 of file translator_sr.h.
    {
      if (numDocuments==0)
      {
        return "Nema dokumenata koji odgovaraju Vašem upitu.";
      }
      else if (numDocuments==1)
      { return "Nađen je <b>1</b> dokument koji odgovara vašem upitu."; }
      else if (numDocuments<5)
      { return "Nađena su <b>$num</b> dokumenta koji odgovaraju vašem upitu."
               " Najbolji su prikazani prvi."; }
      else
      { return "Nađeno je <b>$num</b> dokumenata koji odgovaraju vašem upitu."
               " Najbolji su prikazani prvi.";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorSerbian::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1414 of file translator_sr.h.
    {
      if (numDocuments==0)
      {
        return "Nema dokumenata koji odgovaraju Vašem upitu.";
      }
      else if (numDocuments==1)
      { return "Nađen je <b>1</b> dokument koji odgovara vašem upitu."; }
      else if (numDocuments<5)
      { return "Nađena su <b>$num</b> dokumenta koji odgovaraju vašem upitu."
               " Najbolji su prikazani prvi."; }
      else
      { return "Nađeno je <b>$num</b> dokumenata koji odgovaraju vašem upitu."
               " Najbolji su prikazani prvi.";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorSerbian::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1402 of file translator_sr.h.
    {
      return "Rezultati pretraživanja";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorSerbian::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1402 of file translator_sr.h.
    {
      return "Rezultati pretraživanja";
    }
trSeeAlso() [1/2]
virtual QCString TranslatorSerbian::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 523 of file translator_sr.h.
    { return "Takođe pogledati"; }
trSeeAlso() [2/2]
virtual QCString TranslatorSerbian::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 523 of file translator_sr.h.
    { return "Takođe pogledati"; }
trSignals() [1/2]
virtual QCString TranslatorSerbian::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 617 of file translator_sr.h.
    { return "Signali"; }
trSignals() [2/2]
virtual QCString TranslatorSerbian::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 617 of file translator_sr.h.
    { return "Signali"; }
trSince() [1/2]
virtual QCString TranslatorSerbian::trSince () [inline], [virtual]
Implements Translator.
Definition at line 957 of file translator_sr.h.
    {
      return "Od";
    }
trSince() [2/2]
virtual QCString TranslatorSerbian::trSince () [inline], [virtual]
Implements Translator.
Definition at line 957 of file translator_sr.h.
    {
      return "Od";
    }
trSourceFile() [1/2]
virtual QCString TranslatorSerbian::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1444 of file translator_sr.h.
    {
      return "Izvorni kod datoteke " + filename;
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorSerbian::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1444 of file translator_sr.h.
    {
      return "Izvorni kod datoteke " + filename;
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorSerbian::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1373 of file translator_sr.h.
    {
      return "Statički atributi u paketu"; // Zajednicki clanovi u paketu
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorSerbian::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1373 of file translator_sr.h.
    {
      return "Statički atributi u paketu"; // Zajednicki clanovi u paketu
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorSerbian::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1359 of file translator_sr.h.
    {
      return "Statičke funkcije u paketu"; // Zajednicke funkcije u paketu
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorSerbian::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1359 of file translator_sr.h.
    {
      return "Statičke funkcije u paketu"; // Zajednicke funkcije u paketu
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorSerbian::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 916 of file translator_sr.h.
    {
      return "Zajednički privatni članovi";
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorSerbian::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 916 of file translator_sr.h.
    {
      return "Zajednički privatni članovi";
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorSerbian::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 631 of file translator_sr.h.
    { return "Zajednički privatni članovi"; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorSerbian::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 631 of file translator_sr.h.
    { return "Zajednički privatni članovi"; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorSerbian::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 904 of file translator_sr.h.
    {
      return "Zajednički zaštićeni članovi";
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorSerbian::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 904 of file translator_sr.h.
    {
      return "Zajednički zaštićeni članovi";
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorSerbian::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 625 of file translator_sr.h.
    { return "Zajednički zaštićeni članovi"; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorSerbian::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 625 of file translator_sr.h.
    { return "Zajednički zaštićeni članovi"; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorSerbian::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 892 of file translator_sr.h.
    {
      return "Zajednički javni članovi";
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorSerbian::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 892 of file translator_sr.h.
    {
      return "Zajednički javni članovi";
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorSerbian::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 619 of file translator_sr.h.
    { return "Zajednički javni članovi"; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorSerbian::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 619 of file translator_sr.h.
    { return "Zajednički javni članovi"; }
trSubprogram() [1/2]
virtual QCString TranslatorSerbian::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1704 of file translator_sr.h.
    {
      QCString result((first_capital ? "Procedura" : "procedura"));
      if (!singular) result = (first_capital ? "Procedure" : "procedure");
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorSerbian::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1704 of file translator_sr.h.
    {
      QCString result((first_capital ? "Procedura" : "procedura"));
      if (!singular) result = (first_capital ? "Procedure" : "procedure");
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorSerbian::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1579 of file translator_sr.h.
    { return "Dokumentacija funkcija i procedura"; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorSerbian::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1579 of file translator_sr.h.
    { return "Dokumentacija funkcija i procedura"; }
trSubprograms() [1/2]
virtual QCString TranslatorSerbian::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1573 of file translator_sr.h.
    { return "Funkcije i procedure"; }
trSubprograms() [2/2]
virtual QCString TranslatorSerbian::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1573 of file translator_sr.h.
    { return "Funkcije i procedure"; }
trTest() [1/2]
virtual QCString TranslatorSerbian::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1046 of file translator_sr.h.
    {
      return "Test";
    }
trTest() [2/2]
virtual QCString TranslatorSerbian::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1046 of file translator_sr.h.
    {
      return "Test";
    }
trTestList() [1/2]
virtual QCString TranslatorSerbian::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1051 of file translator_sr.h.
    {
      return "Spisak testova";
    }
trTestList() [2/2]
virtual QCString TranslatorSerbian::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1051 of file translator_sr.h.
    {
      return "Spisak testova";
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorSerbian::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 125 of file translator_sr.h.
    { return "Ovo je spisak svih članova "; }
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorSerbian::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 125 of file translator_sr.h.
    { return "Ovo je spisak svih članova "; }
trTodo() [1/2]
virtual QCString TranslatorSerbian::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 926 of file translator_sr.h.
    {
      return "Uraditi";
    }
trTodo() [2/2]
virtual QCString TranslatorSerbian::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 926 of file translator_sr.h.
    {
      return "Uraditi";
    }
trTodoList() [1/2]
virtual QCString TranslatorSerbian::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 931 of file translator_sr.h.
    {
      return "Spisak stvari koje treba uraditi";
    }
trTodoList() [2/2]
virtual QCString TranslatorSerbian::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 931 of file translator_sr.h.
    {
      return "Spisak stvari koje treba uraditi";
    }
trType() [1/2]
virtual QCString TranslatorSerbian::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1694 of file translator_sr.h.
    {
      QCString result((first_capital ? "Tip" : "tip"));
      if (!singular) result+="ovi";
      return result;
    }
trType() [2/2]
virtual QCString TranslatorSerbian::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1694 of file translator_sr.h.
    {
      QCString result((first_capital ? "Tip" : "tip"));
      if (!singular) result+="ovi";
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorSerbian::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1712 of file translator_sr.h.
    {
      return "Ograničenja tipova";
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorSerbian::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1712 of file translator_sr.h.
    {
      return "Ograničenja tipova";
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorSerbian::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 453 of file translator_sr.h.
    { return "Dokumentacija definicije tipa"; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorSerbian::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 453 of file translator_sr.h.
    { return "Dokumentacija definicije tipa"; }
trTypedefs() [1/2]
virtual QCString TranslatorSerbian::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 417 of file translator_sr.h.
    { return "Definicije tipa"; }
trTypedefs() [2/2]
virtual QCString TranslatorSerbian::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 417 of file translator_sr.h.
    { return "Definicije tipa"; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorSerbian::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1567 of file translator_sr.h.
    { return "Dokumentacija tipova podataka"; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorSerbian::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1567 of file translator_sr.h.
    { return "Dokumentacija tipova podataka"; }
trVariableDocumentation() [1/2]
virtual QCString TranslatorSerbian::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 471 of file translator_sr.h.
    { return "Dokumentacija promenljive"; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorSerbian::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 471 of file translator_sr.h.
    { return "Dokumentacija promenljive"; }
trVariables() [1/2]
virtual QCString TranslatorSerbian::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 435 of file translator_sr.h.
    { return "Promenljive"; }
trVariables() [2/2]
virtual QCString TranslatorSerbian::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 435 of file translator_sr.h.
    { return "Promenljive"; }
trVersion() [1/2]
virtual QCString TranslatorSerbian::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 511 of file translator_sr.h.
    { return "Verzija"; }
trVersion() [2/2]
virtual QCString TranslatorSerbian::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 511 of file translator_sr.h.
    { return "Verzija"; }
trWarning() [1/2]
virtual QCString TranslatorSerbian::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 507 of file translator_sr.h.
    { return "Upozorenje"; }
trWarning() [2/2]
virtual QCString TranslatorSerbian::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 507 of file translator_sr.h.
    { return "Upozorenje"; }
trWriteList() [1/2]
virtual QCString TranslatorSerbian::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 637 of file translator_sr.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" i ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorSerbian::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 637 of file translator_sr.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" i ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_sr.h
doxygen/src/translator_sr.h