TranslatorUkrainian Class Reference
#include <translator_ua.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
Additional Inherited Members
Detailed Description
Definition at line 22 of file translator_ua.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorUkrainian::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 38 of file translator_ua.h.
    {
      return "0x422 Ukrainian";
    }
getLanguageString() [2/2]
virtual QCString TranslatorUkrainian::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 38 of file translator_ua.h.
    {
      return "0x422 Ukrainian";
    }
idLanguage() [1/2]
virtual QCString TranslatorUkrainian::idLanguage () [inline], [virtual]
Used for identification of the language.
Implements Translator.
Definition at line 26 of file translator_ua.h.
    { return "ukrainian"; }
idLanguage() [2/2]
virtual QCString TranslatorUkrainian::idLanguage () [inline], [virtual]
Used for identification of the language.
Implements Translator.
Definition at line 26 of file translator_ua.h.
    { return "ukrainian"; }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorUkrainian::latexLanguageSupportCommand () [inline], [virtual]
Implements Translator.
Definition at line 30 of file translator_ua.h.
    {
      return "\\usepackage[T2A]{fontenc}\n\\usepackage[ukrainian]{babel}\n";
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorUkrainian::latexLanguageSupportCommand () [inline], [virtual]
Implements Translator.
Definition at line 30 of file translator_ua.h.
    {
      return "\\usepackage[T2A]{fontenc}\n\\usepackage[ukrainian]{babel}\n";
    }
trAdditionalInheritedMembers() [1/2]
virtual QCString TranslatorUkrainian::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1862 of file translator_ua.h.
    { return " "; }
trAdditionalInheritedMembers() [2/2]
virtual QCString TranslatorUkrainian::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1862 of file translator_ua.h.
    { return " "; }
trAll() [1/2]
virtual QCString TranslatorUkrainian::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1358 of file translator_ua.h.
    {
      return "";
    }
trAll() [2/2]
virtual QCString TranslatorUkrainian::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1358 of file translator_ua.h.
    {
      return "";
    }
trAndMore() [1/2]
virtual QCString TranslatorUkrainian::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1840 of file translator_ua.h.
    { return " "+number+"..."; }
trAndMore() [2/2]
virtual QCString TranslatorUkrainian::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1840 of file translator_ua.h.
    { return " "+number+"..."; }
trAttention() [1/2]
virtual QCString TranslatorUkrainian::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 944 of file translator_ua.h.
    {
      return "";
    }
trAttention() [2/2]
virtual QCString TranslatorUkrainian::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 944 of file translator_ua.h.
    {
      return "";
    }
trAuthor() [1/2]
virtual QCString TranslatorUkrainian::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1224 of file translator_ua.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorUkrainian::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1224 of file translator_ua.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorUkrainian::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1104 of file translator_ua.h.
    {
      return "";
    }
trBug() [2/2]
virtual QCString TranslatorUkrainian::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1104 of file translator_ua.h.
    {
      return "";
    }
trBugList() [1/2]
virtual QCString TranslatorUkrainian::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1109 of file translator_ua.h.
    {
      return " ";
    }
trBugList() [2/2]
virtual QCString TranslatorUkrainian::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1109 of file translator_ua.h.
    {
      return " ";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorUkrainian::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1479 of file translator_ua.h.
    {
      return " :";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorUkrainian::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1479 of file translator_ua.h.
    {
      return " :";
    }
trCallGraph() [1/2]
virtual QCString TranslatorUkrainian::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1363 of file translator_ua.h.
    {
      return " :";
    }
trCallGraph() [2/2]
virtual QCString TranslatorUkrainian::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1363 of file translator_ua.h.
    {
      return " :";
    }
trCiteReferences() [1/2]
virtual QCString TranslatorUkrainian::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1816 of file translator_ua.h.
    { return " "; }
trCiteReferences() [2/2]
virtual QCString TranslatorUkrainian::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1816 of file translator_ua.h.
    { return " "; }
trClass() [1/2]
virtual QCString TranslatorUkrainian::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1137 of file translator_ua.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        QCString result((first_capital ? " " : " "));
        return result;
      }
      else
      {
        QCString result((first_capital ? "" : ""));
        if(!singular) result+="";
        return result;
      }
    }
References Config_getBool.
trClass() [2/2]
virtual QCString TranslatorUkrainian::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1137 of file translator_ua.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        QCString result((first_capital ? " " : " "));
        return result;
      }
      else
      {
        QCString result((first_capital ? "" : ""));
        if(!singular) result+="";
        return result;
      }
    }
References Config_getBool.
trClassDiagram() [1/2]
virtual QCString TranslatorUkrainian::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 465 of file translator_ua.h.
    {
      return QCString(" ")+clName;
    }
trClassDiagram() [2/2]
virtual QCString TranslatorUkrainian::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 465 of file translator_ua.h.
    {
      return QCString(" ")+clName;
    }
trClassDocumentation() [1/2]
virtual QCString TranslatorUkrainian::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 335 of file translator_ua.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " " ;
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "" ;
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorUkrainian::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 335 of file translator_ua.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " " ;
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "" ;
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorUkrainian::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1067 of file translator_ua.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " " ;
      }
      else
      {
        return "" ;
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorUkrainian::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1067 of file translator_ua.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " " ;
      }
      else
      {
        return "" ;
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorUkrainian::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 141 of file translator_ua.h.
    { return " "; }
trClassHierarchy() [2/2]
virtual QCString TranslatorUkrainian::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 141 of file translator_ua.h.
    { return " "; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorUkrainian::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 196 of file translator_ua.h.
    { return " "; }
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorUkrainian::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 196 of file translator_ua.h.
    { return " "; }
trClassMethods() [1/2]
virtual QCString TranslatorUkrainian::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1900 of file translator_ua.h.
    {
      return " ";
    }
trClassMethods() [2/2]
virtual QCString TranslatorUkrainian::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1900 of file translator_ua.h.
    {
      return " ";
    }
trCode() [1/2]
virtual QCString TranslatorUkrainian::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 841 of file translator_ua.h.
    {
      return " ";
    }
trCode() [2/2]
virtual QCString TranslatorUkrainian::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 841 of file translator_ua.h.
    {
      return " ";
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorUkrainian::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 796 of file translator_ua.h.
    {
      return " ' "+clName+":";
    }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorUkrainian::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 796 of file translator_ua.h.
    {
      return " ' "+clName+":";
    }
trCompoundIndex() [1/2]
virtual QCString TranslatorUkrainian::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 308 of file translator_ua.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " " ;
      }
      else
      {
        return " " ;
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorUkrainian::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 308 of file translator_ua.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " " ;
      }
      else
      {
        return " " ;
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorUkrainian::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1534 of file translator_ua.h.
    { return " "; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorUkrainian::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1534 of file translator_ua.h.
    { return " "; }
trCompoundList() [1/2]
virtual QCString TranslatorUkrainian::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 145 of file translator_ua.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " " ;
      }
      else
      {
        return "" ;
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorUkrainian::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 145 of file translator_ua.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " " ;
      }
      else
      {
        return "" ;
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorUkrainian::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 209 of file translator_ua.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ." ;
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return " ." ;
      }
      else
      {
        return ", , ' ." ;
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorUkrainian::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 209 of file translator_ua.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " ." ;
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return " ." ;
      }
      else
      {
        return ", , ' ." ;
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorUkrainian::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1507 of file translator_ua.h.
    { return " :"; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorUkrainian::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1507 of file translator_ua.h.
    { return " :"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorUkrainian::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1499 of file translator_ua.h.
    { return " "; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorUkrainian::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1499 of file translator_ua.h.
    { return " "; }
trCompoundMembers() [1/2]
virtual QCString TranslatorUkrainian::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 162 of file translator_ua.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " " ;
      }
      else
      {
        return " " ;
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorUkrainian::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 162 of file translator_ua.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " " ;
      }
      else
      {
        return " " ;
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorUkrainian::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 226 of file translator_ua.h.
    {
        QCString result=" ";
        if(!extractAll) result+=" ";
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
          result+=" ";
        else
          result+=" ";
        if(extractAll)
        {
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
            result+=" /' .";
          else
            result+=" .";
        }
        else
        {
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
            result += " ";
          else
            result += " ";
          result+=", .";
        }
        return result ;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorUkrainian::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 226 of file translator_ua.h.
    {
        QCString result=" ";
        if(!extractAll) result+=" ";
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
          result+=" ";
        else
          result+=" ";
        if(extractAll)
        {
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
            result+=" /' .";
          else
            result+=" .";
        }
        else
        {
          if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
            result += " ";
          else
            result += " ";
          result+=", .";
        }
        return result ;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorUkrainian::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1511 of file translator_ua.h.
    {
      QCString result=" ";
      if (!extractAll)
      {
        result+=" ";
      }
      result+=" ";
      result+=" ";
      if (!extractAll)
      {
         result+=" ";
      }
      else
      {
         result+=" , :";
      }
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorUkrainian::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1511 of file translator_ua.h.
    {
      QCString result=" ";
      if (!extractAll)
      {
        result+=" ";
      }
      result+=" ";
      result+=" ";
      if (!extractAll)
      {
         result+=" ";
      }
      else
      {
         result+=" , :";
      }
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorUkrainian::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1503 of file translator_ua.h.
    { return " "; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorUkrainian::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1503 of file translator_ua.h.
    { return " "; }
trCompoundReference() [1/2]
virtual QCString TranslatorUkrainian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 540 of file translator_ua.h.
    {
      QCString result;
      if (isTemplate)
      {
        result=" ";
        switch(compType)
        {
          case ClassDef::Class: result+=""; break;
          case ClassDef::Struct: result+=""; break;
          case ClassDef::Union: result+="'"; break;
          case ClassDef::Interface: result+=""; break;
          case ClassDef::Protocol: result+=""; break;
          case ClassDef::Category: result+=""; break;
          case ClassDef::Exception: result+=""; break;
          default: break;
        }
      }
      else
      {
        switch(compType)
        {
          case ClassDef::Class: result+=""; break;
          case ClassDef::Struct: result+=""; break;
          case ClassDef::Union: result+="'"; break;
          case ClassDef::Interface: result+=""; break;
          case ClassDef::Protocol: result+=""; break;
          case ClassDef::Category: result+=""; break;
          case ClassDef::Exception: result+=""; break;
          default: break;
        }
      }
      result+=" ";
      return result+clName;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorUkrainian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 540 of file translator_ua.h.
    {
      QCString result;
      if (isTemplate)
      {
        result=" ";
        switch(compType)
        {
          case ClassDef::Class: result+=""; break;
          case ClassDef::Struct: result+=""; break;
          case ClassDef::Union: result+="'"; break;
          case ClassDef::Interface: result+=""; break;
          case ClassDef::Protocol: result+=""; break;
          case ClassDef::Category: result+=""; break;
          case ClassDef::Exception: result+=""; break;
          default: break;
        }
      }
      else
      {
        switch(compType)
        {
          case ClassDef::Class: result+=""; break;
          case ClassDef::Struct: result+=""; break;
          case ClassDef::Union: result+="'"; break;
          case ClassDef::Interface: result+=""; break;
          case ClassDef::Protocol: result+=""; break;
          case ClassDef::Category: result+=""; break;
          case ClassDef::Exception: result+=""; break;
          default: break;
        }
      }
      result+=" ";
      return result+clName;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorUkrainian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1575 of file translator_ua.h.
    {
      QCString result=clName;
      if (isTemplate)
      {
    switch(compType)
    {
      case ClassDef::Class: result+=" "; break;
      case ClassDef::Struct: result+=" "; break;
      case ClassDef::Union: result+=" '"; break;
      case ClassDef::Interface: result+=" "; break;
      case ClassDef::Protocol: result+=" "; break;
      case ClassDef::Category: result+=" "; break;
      case ClassDef::Exception: result+=" "; break;
          default: break;
    }
      }
      else
      {
    result+=" ";
    switch(compType)
    {
      case ClassDef::Class: result+=""; break;
      case ClassDef::Struct: result+=""; break;
      case ClassDef::Union: result+="'"; break;
      case ClassDef::Interface: result+=""; break;
      case ClassDef::Protocol: result+=""; break;
      case ClassDef::Category: result+=""; break;
      case ClassDef::Exception: result+=""; break;
          default: break;
    }
      }
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorUkrainian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1575 of file translator_ua.h.
    {
      QCString result=clName;
      if (isTemplate)
      {
    switch(compType)
    {
      case ClassDef::Class: result+=" "; break;
      case ClassDef::Struct: result+=" "; break;
      case ClassDef::Union: result+=" '"; break;
      case ClassDef::Interface: result+=" "; break;
      case ClassDef::Protocol: result+=" "; break;
      case ClassDef::Category: result+=" "; break;
      case ClassDef::Exception: result+=" "; break;
          default: break;
    }
      }
      else
      {
    result+=" ";
    switch(compType)
    {
      case ClassDef::Class: result+=""; break;
      case ClassDef::Struct: result+=""; break;
      case ClassDef::Union: result+="'"; break;
      case ClassDef::Interface: result+=""; break;
      case ClassDef::Protocol: result+=""; break;
      case ClassDef::Category: result+=""; break;
      case ClassDef::Exception: result+=""; break;
          default: break;
    }
      }
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorUkrainian::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 436 of file translator_ua.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " " ;
      }
      else
      {
        return "" ;
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorUkrainian::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 436 of file translator_ua.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " " ;
      }
      else
      {
        return "" ;
      }
    }
References Config_getBool.
trConstructorDocumentation() [1/2]
virtual QCString TranslatorUkrainian::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 806 of file translator_ua.h.
    {
      return "()";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorUkrainian::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 806 of file translator_ua.h.
    {
      return "()";
    }
trCopyright() [1/2]
virtual QCString TranslatorUkrainian::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1820 of file translator_ua.h.
    { return ""; }
trCopyright() [2/2]
virtual QCString TranslatorUkrainian::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1820 of file translator_ua.h.
    { return ""; }
trDataTypes() [1/2]
virtual QCString TranslatorUkrainian::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1558 of file translator_ua.h.
    { return " "; }
trDataTypes() [2/2]
virtual QCString TranslatorUkrainian::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1558 of file translator_ua.h.
    { return " "; }
trDate() [1/2]
virtual QCString TranslatorUkrainian::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 479 of file translator_ua.h.
    { return ""; }
trDate() [2/2]
virtual QCString TranslatorUkrainian::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 479 of file translator_ua.h.
    { return ""; }
trDateTime() [1/2]
virtual QCString TranslatorUkrainian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1775 of file translator_ua.h.
    {
      static const char *days[] = { "","","","","'","","" };
      static const char *months[] = { "","","","","","","","","","","","" };
      QCString sdate;
      sdate.sprintf("%s, %d %s %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDateTime() [2/2]
virtual QCString TranslatorUkrainian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1775 of file translator_ua.h.
    {
      static const char *days[] = { "","","","","'","","" };
      static const char *months[] = { "","","","","","","","","","","","" };
      QCString sdate;
      sdate.sprintf("%s, %d %s %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDayOfWeek() [1/2]
virtual QCString TranslatorUkrainian::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1791 of file translator_ua.h.
    {
      static const char *days_short[] = { "", "", "", "", "", "", "" };
      static const char *days_full[] = { "", "", "", "", "'", "", "" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      return text;
    }
trDayOfWeek() [2/2]
virtual QCString TranslatorUkrainian::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1791 of file translator_ua.h.
    {
      static const char *days_short[] = { "", "", "", "", "", "", "" };
      static const char *days_full[] = { "", "", "", "", "'", "", "" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      return text;
    }
trDayPeriod() [1/2]
virtual QCString TranslatorUkrainian::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1805 of file translator_ua.h.
    {
      static const char *dayPeriod[] = { "", "" };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorUkrainian::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1805 of file translator_ua.h.
    {
      static const char *dayPeriod[] = { "", "" };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorUkrainian::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 773 of file translator_ua.h.
    {
      return ". @1, @0";
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorUkrainian::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 773 of file translator_ua.h.
    {
      return ". @1, @0";
    }
trDefinedIn() [1/2]
virtual QCString TranslatorUkrainian::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 129 of file translator_ua.h.
    { return " "; }
trDefinedIn() [2/2]
virtual QCString TranslatorUkrainian::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 129 of file translator_ua.h.
    { return " "; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorUkrainian::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 777 of file translator_ua.h.
    {
      return ". @0";
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorUkrainian::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 777 of file translator_ua.h.
    {
      return ". @0";
    }
trDefineDocumentation() [1/2]
virtual QCString TranslatorUkrainian::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 406 of file translator_ua.h.
    { return " "; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorUkrainian::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 406 of file translator_ua.h.
    { return " "; }
trDefines() [1/2]
virtual QCString TranslatorUkrainian::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 370 of file translator_ua.h.
    { return ""; }
trDefines() [2/2]
virtual QCString TranslatorUkrainian::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 370 of file translator_ua.h.
    { return ""; }
trDefineValue() [1/2]
virtual QCString TranslatorUkrainian::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1094 of file translator_ua.h.
    {
      return ":";
    }
trDefineValue() [2/2]
virtual QCString TranslatorUkrainian::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1094 of file translator_ua.h.
    {
      return ":";
    }
trDeprecated() [1/2]
virtual QCString TranslatorUkrainian::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 786 of file translator_ua.h.
    {
      return " ";
    }
trDeprecated() [2/2]
virtual QCString TranslatorUkrainian::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 786 of file translator_ua.h.
    {
      return " ";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorUkrainian::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1281 of file translator_ua.h.
    {
      return " ";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorUkrainian::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1281 of file translator_ua.h.
    {
      return " ";
    }
trDetailedDescription() [1/2]
virtual QCString TranslatorUkrainian::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 54 of file translator_ua.h.
    { return " "; }
trDetailedDescription() [2/2]
virtual QCString TranslatorUkrainian::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 54 of file translator_ua.h.
    { return " "; }
trDetailLevel() [1/2]
virtual QCString TranslatorUkrainian::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1832 of file translator_ua.h.
    { return " "; }
trDetailLevel() [2/2]
virtual QCString TranslatorUkrainian::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1832 of file translator_ua.h.
    { return " "; }
trDir() [1/2]
virtual QCString TranslatorUkrainian::trDir (bool , bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1453 of file translator_ua.h.
    {
      QCString result("");
      if (!singular) result+="";
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorUkrainian::trDir (bool , bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1453 of file translator_ua.h.
    {
      QCString result("");
      if (!singular) result+="";
      return result;
    }
trDirDepGraph() [1/2]
virtual QCString TranslatorUkrainian::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1824 of file translator_ua.h.
    { return QCString(" ")+name+":"; }
References setup::name.
trDirDepGraph() [2/2]
virtual QCString TranslatorUkrainian::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1824 of file translator_ua.h.
    { return QCString(" ")+name+":"; }
References setup::name.
trDirDocumentation() [1/2]
virtual QCString TranslatorUkrainian::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1435 of file translator_ua.h.
    { return " "; }
trDirDocumentation() [2/2]
virtual QCString TranslatorUkrainian::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1435 of file translator_ua.h.
    { return " "; }
trDirectories() [1/2]
virtual QCString TranslatorUkrainian::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1441 of file translator_ua.h.
    { return ""; }
trDirectories() [2/2]
virtual QCString TranslatorUkrainian::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1441 of file translator_ua.h.
    { return ""; }
trDirIndex() [1/2]
virtual QCString TranslatorUkrainian::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1429 of file translator_ua.h.
    { return " "; }
trDirIndex() [2/2]
virtual QCString TranslatorUkrainian::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1429 of file translator_ua.h.
    { return " "; }
trDirReference() [1/2]
virtual QCString TranslatorUkrainian::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1447 of file translator_ua.h.
    { QCString result=" "; result+=dirName; return result; }
trDirReference() [2/2]
virtual QCString TranslatorUkrainian::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1447 of file translator_ua.h.
    { QCString result=" "; result+=dirName; return result; }
trDirRelation() [1/2]
virtual QCString TranslatorUkrainian::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1714 of file translator_ua.h.
    {
      return "' "+QCString(name);
    }
References setup::name.
trDirRelation() [2/2]
virtual QCString TranslatorUkrainian::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1714 of file translator_ua.h.
    {
      return "' "+QCString(name);
    }
References setup::name.
trDocumentation() [1/2]
virtual QCString TranslatorUkrainian::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 290 of file translator_ua.h.
    { return ""; }
trDocumentation() [2/2]
virtual QCString TranslatorUkrainian::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 290 of file translator_ua.h.
    { return ""; }
trEnumerations() [1/2]
virtual QCString TranslatorUkrainian::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 382 of file translator_ua.h.
    { return ""; }
trEnumerations() [2/2]
virtual QCString TranslatorUkrainian::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 382 of file translator_ua.h.
    { return ""; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorUkrainian::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 418 of file translator_ua.h.
    { return " "; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorUkrainian::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 418 of file translator_ua.h.
    { return " "; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorUkrainian::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1487 of file translator_ua.h.
    { return " "; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorUkrainian::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1487 of file translator_ua.h.
    { return " "; }
trEnumerationValues() [1/2]
virtual QCString TranslatorUkrainian::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 400 of file translator_ua.h.
    { return " "; }
trEnumerationValues() [2/2]
virtual QCString TranslatorUkrainian::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 400 of file translator_ua.h.
    { return " "; }
trEnumGeneratedFromFiles() [1/2]
virtual QCString TranslatorUkrainian::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1844 of file translator_ua.h.
    { QCString result = " ";
            result += (single? " ": " ");
      result+=":";
      return result;
    }
trEnumGeneratedFromFiles() [2/2]
virtual QCString TranslatorUkrainian::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1844 of file translator_ua.h.
    { QCString result = " ";
            result += (single? " ": " ");
      result+=":";
      return result;
    }
trEnumName() [1/2]
virtual QCString TranslatorUkrainian::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 121 of file translator_ua.h.
    { return ""; }
trEnumName() [2/2]
virtual QCString TranslatorUkrainian::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 121 of file translator_ua.h.
    { return ""; }
trEnumReference() [1/2]
virtual QCString TranslatorUkrainian::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1852 of file translator_ua.h.
    { return QCString(name)+" "; }
References setup::name.
trEnumReference() [2/2]
virtual QCString TranslatorUkrainian::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1852 of file translator_ua.h.
    { return QCString(name)+" "; }
References setup::name.
trEnumValue() [1/2]
virtual QCString TranslatorUkrainian::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 125 of file translator_ua.h.
    { return " "; }
trEnumValue() [2/2]
virtual QCString TranslatorUkrainian::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 125 of file translator_ua.h.
    { return " "; }
trEventDocumentation() [1/2]
virtual QCString TranslatorUkrainian::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1299 of file translator_ua.h.
    {
      return " ";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorUkrainian::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1299 of file translator_ua.h.
    {
      return " ";
    }
trEvents() [1/2]
virtual QCString TranslatorUkrainian::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1293 of file translator_ua.h.
    {
      return "";
    }
trEvents() [2/2]
virtual QCString TranslatorUkrainian::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1293 of file translator_ua.h.
    {
      return "";
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorUkrainian::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 360 of file translator_ua.h.
    { return ""; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorUkrainian::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 360 of file translator_ua.h.
    { return ""; }
trExamples() [1/2]
virtual QCString TranslatorUkrainian::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 188 of file translator_ua.h.
    { return ""; }
trExamples() [2/2]
virtual QCString TranslatorUkrainian::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 188 of file translator_ua.h.
    { return ""; }
trExamplesDescription() [1/2]
virtual QCString TranslatorUkrainian::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 276 of file translator_ua.h.
    { return " ."; }
trExamplesDescription() [2/2]
virtual QCString TranslatorUkrainian::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 276 of file translator_ua.h.
    { return " ."; }
trExceptions() [1/2]
virtual QCString TranslatorUkrainian::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 495 of file translator_ua.h.
    { return " "; }
trExceptions() [2/2]
virtual QCString TranslatorUkrainian::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 495 of file translator_ua.h.
    { return " "; }
trExtendsClass() [1/2]
virtual QCString TranslatorUkrainian::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1892 of file translator_ua.h.
    {
      return " @0.";
    }
trExtendsClass() [2/2]
virtual QCString TranslatorUkrainian::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1892 of file translator_ua.h.
    {
      return " @0.";
    }
trFile() [1/2]
virtual QCString TranslatorUkrainian::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1156 of file translator_ua.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorUkrainian::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1156 of file translator_ua.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorUkrainian::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 354 of file translator_ua.h.
    { return ""; }
trFileDocumentation() [2/2]
virtual QCString TranslatorUkrainian::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 354 of file translator_ua.h.
    { return ""; }
trFileIn() [1/2]
virtual QCString TranslatorUkrainian::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1751 of file translator_ua.h.
    {
      return " "+name;
    }
References setup::name.
trFileIn() [2/2]
virtual QCString TranslatorUkrainian::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1751 of file translator_ua.h.
    {
      return " "+name;
    }
References setup::name.
trFileIndex() [1/2]
virtual QCString TranslatorUkrainian::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 323 of file translator_ua.h.
    { return " " ; }
trFileIndex() [2/2]
virtual QCString TranslatorUkrainian::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 323 of file translator_ua.h.
    { return " " ; }
trFileList() [1/2]
virtual QCString TranslatorUkrainian::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 158 of file translator_ua.h.
    { return ""; }
trFileList() [2/2]
virtual QCString TranslatorUkrainian::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 158 of file translator_ua.h.
    { return ""; }
trFileListDescription() [1/2]
virtual QCString TranslatorUkrainian::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 200 of file translator_ua.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=".";
      return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorUkrainian::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 200 of file translator_ua.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=".";
      return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorUkrainian::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 176 of file translator_ua.h.
    {
      return " " ;
    }
trFileMembers() [2/2]
virtual QCString TranslatorUkrainian::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 176 of file translator_ua.h.
    {
      return " " ;
    }
trFileMembersDescription() [1/2]
virtual QCString TranslatorUkrainian::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 253 of file translator_ua.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+=", , , "
                " ";
      }
      else
      {
        result+=" ";
      }
      result+=" ";
      if (extractAll)
        result+=", .";
      else
        result+=".";
      return result ;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorUkrainian::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 253 of file translator_ua.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+=", , , "
                " ";
      }
      else
      {
        result+=" ";
      }
      result+=" ";
      if (extractAll)
        result+=", .";
      else
        result+=".";
      return result ;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorUkrainian::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 579 of file translator_ua.h.
    {
      return QCString(" ")+fileName;
    }
trFileReference() [2/2]
virtual QCString TranslatorUkrainian::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 579 of file translator_ua.h.
    {
      return QCString(" ")+fileName;
    }
trFriends() [1/2]
virtual QCString TranslatorUkrainian::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 522 of file translator_ua.h.
    { return " "; }
trFriends() [2/2]
virtual QCString TranslatorUkrainian::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 522 of file translator_ua.h.
    { return " "; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorUkrainian::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 424 of file translator_ua.h.
    { return " "; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorUkrainian::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 424 of file translator_ua.h.
    { return " "; }
trFunctions() [1/2]
virtual QCString TranslatorUkrainian::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 388 of file translator_ua.h.
    { return ""; }
trFunctions() [2/2]
virtual QCString TranslatorUkrainian::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 388 of file translator_ua.h.
    { return ""; }
trGeneratedAt() [1/2]
virtual QCString TranslatorUkrainian::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the documentation of a group before the list of links to documented files
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 455 of file translator_ua.h.
    {
      QCString result=" ";
      if (!projName.isEmpty()) result+=QCString(" ")+projName;
      result+=QCString(" ")+date;
      result+=" ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorUkrainian::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the documentation of a group before the list of links to documented files
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 455 of file translator_ua.h.
    {
      QCString result=" ";
      if (!projName.isEmpty()) result+=QCString(" ")+projName;
      result+=QCString(" ")+date;
      result+=" ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorUkrainian::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 113 of file translator_ua.h.
    { QCString result=" Doxygen";
      if (!s.isEmpty()) result+=QCString(" ")+s;
      result+=" .";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorUkrainian::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 113 of file translator_ua.h.
    { QCString result=" Doxygen";
      if (!s.isEmpty()) result+=QCString(" ")+s;
      result+=" .";
      return result;
    }
References s.
trGeneratedBy() [1/2]
virtual QCString TranslatorUkrainian::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 499 of file translator_ua.h.
    { return " "; }
trGeneratedBy() [2/2]
virtual QCString TranslatorUkrainian::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 499 of file translator_ua.h.
    { return " "; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorUkrainian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 714 of file translator_ua.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result=" ";
      switch(compType)
      {
        case ClassDef::Class:
          if (single) result+=" "; else result+=" ";
          break;
        case ClassDef::Struct:
          if (single) result+=" "; else result+=" ";
          break;
        case ClassDef::Union:
          if (single) result+=" '"; else result+=" '";
          break;
        case ClassDef::Interface:
          if (single) result+=" "; else result+=" ";
          break;
        case ClassDef::Protocol:
          if (single) result+=" "; else result+=" ";
          break;
        case ClassDef::Category:
          if (single) result+=" "; else result+=" ";
          break;
        case ClassDef::Exception:
          if (single) result+=" "; else result+=" ";
          break;
        default:
          break;
      }
      result+=" ";
      if (single) result+=":"; else result+=":";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorUkrainian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 714 of file translator_ua.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result=" ";
      switch(compType)
      {
        case ClassDef::Class:
          if (single) result+=" "; else result+=" ";
          break;
        case ClassDef::Struct:
          if (single) result+=" "; else result+=" ";
          break;
        case ClassDef::Union:
          if (single) result+=" '"; else result+=" '";
          break;
        case ClassDef::Interface:
          if (single) result+=" "; else result+=" ";
          break;
        case ClassDef::Protocol:
          if (single) result+=" "; else result+=" ";
          break;
        case ClassDef::Category:
          if (single) result+=" "; else result+=" ";
          break;
        case ClassDef::Exception:
          if (single) result+=" "; else result+=" ";
          break;
        default:
          break;
      }
      result+=" ";
      if (single) result+=":"; else result+=":";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorUkrainian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1660 of file translator_ua.h.
    {
      // single is true implies a single file
      QCString result=" ";
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" '"; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      result+=" ";
      if (single) result+=" :"; else result+=" :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorUkrainian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1660 of file translator_ua.h.
    {
      // single is true implies a single file
      QCString result=" ";
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" '"; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      result+=" ";
      if (single) result+=" :"; else result+=" :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorUkrainian::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1211 of file translator_ua.h.
    {
      QCString result((first_capital ? "" : ""));
      result+=(singular ? "" : "");
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorUkrainian::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1211 of file translator_ua.h.
    {
      QCString result((first_capital ? "" : ""));
      result+=(singular ? "" : "");
      return result;
    }
trGlobalNamespace() [1/2]
virtual QCString TranslatorUkrainian::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1726 of file translator_ua.h.
    {
      return " ";
    }
trGlobalNamespace() [2/2]
virtual QCString TranslatorUkrainian::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1726 of file translator_ua.h.
    {
      return " ";
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorUkrainian::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 816 of file translator_ua.h.
    {
      return ". .";
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorUkrainian::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 816 of file translator_ua.h.
    {
      return ". .";
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorUkrainian::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 849 of file translator_ua.h.
    {
      return ". ";
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorUkrainian::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 849 of file translator_ua.h.
    {
      return ". ";
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorUkrainian::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 811 of file translator_ua.h.
    {
      return ". .";
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorUkrainian::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 811 of file translator_ua.h.
    {
      return ". .";
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorUkrainian::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 853 of file translator_ua.h.
    {
      return ". ";
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorUkrainian::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 853 of file translator_ua.h.
    {
      return ". ";
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorUkrainian::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 845 of file translator_ua.h.
    {
      return " ";
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorUkrainian::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 845 of file translator_ua.h.
    {
      return " ";
    }
trGroup() [1/2]
virtual QCString TranslatorUkrainian::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1178 of file translator_ua.h.
    {
      QCString result((first_capital ? "" : ""));
      result+=(singular ? "" : "");
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorUkrainian::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1178 of file translator_ua.h.
    {
      QCString result((first_capital ? "" : ""));
      result+=(singular ? "" : "");
      return result;
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorUkrainian::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 302 of file translator_ua.h.
    { return " "; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorUkrainian::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 302 of file translator_ua.h.
    { return " "; }
trImplementedFromList() [1/2]
virtual QCString TranslatorUkrainian::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1249 of file translator_ua.h.
    {
      return " " + trWriteList(numEntries) + ".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorUkrainian::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1249 of file translator_ua.h.
    {
      return " " + trWriteList(numEntries) + ".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorUkrainian::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1257 of file translator_ua.h.
    {
      return " " + trWriteList(numEntries) + ".";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorUkrainian::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1257 of file translator_ua.h.
    {
      return " " + trWriteList(numEntries) + ".";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorUkrainian::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 948 of file translator_ua.h.
    {
      return " , :";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorUkrainian::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 948 of file translator_ua.h.
    {
      return " , :";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorUkrainian::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 801 of file translator_ua.h.
    {
      return QCString(" ")+fName+":";
    }
trInclDepGraph() [2/2]
virtual QCString TranslatorUkrainian::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 801 of file translator_ua.h.
    {
      return QCString(" ")+fName+":";
    }
trIncludesFileIn() [1/2]
virtual QCString TranslatorUkrainian::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1760 of file translator_ua.h.
    {
      return " "+name;
    }
References setup::name.
trIncludesFileIn() [2/2]
virtual QCString TranslatorUkrainian::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1760 of file translator_ua.h.
    {
      return " "+name;
    }
References setup::name.
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorUkrainian::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 107 of file translator_ua.h.
    { return ", "; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorUkrainian::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 107 of file translator_ua.h.
    { return ", "; }
trInheritedByList() [1/2]
virtual QCString TranslatorUkrainian::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 647 of file translator_ua.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorUkrainian::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 647 of file translator_ua.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom() [1/2]
virtual QCString TranslatorUkrainian::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1856 of file translator_ua.h.
    { return QCString(members)+" "+what; }
trInheritedFrom() [2/2]
virtual QCString TranslatorUkrainian::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1856 of file translator_ua.h.
    { return QCString(members)+" "+what; }
trInheritsList() [1/2]
virtual QCString TranslatorUkrainian::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 639 of file translator_ua.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorUkrainian::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 639 of file translator_ua.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorUkrainian::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 836 of file translator_ua.h.
    {
      return " ";
    }
trInitialValue() [2/2]
virtual QCString TranslatorUkrainian::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 836 of file translator_ua.h.
    {
      return " ";
    }
trInstanceMethods() [1/2]
virtual QCString TranslatorUkrainian::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1908 of file translator_ua.h.
    {
      return " '";
    }
trInstanceMethods() [2/2]
virtual QCString TranslatorUkrainian::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1908 of file translator_ua.h.
    {
      return " '";
    }
trInvariant() [1/2]
virtual QCString TranslatorUkrainian::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 831 of file translator_ua.h.
    {
      return "";
    }
trInvariant() [2/2]
virtual QCString TranslatorUkrainian::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 831 of file translator_ua.h.
    {
      return "";
    }
trISOLang() [1/2]
virtual QCString TranslatorUkrainian::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 34 of file translator_ua.h.
    {
      return "uk";
    }
trISOLang() [2/2]
virtual QCString TranslatorUkrainian::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 34 of file translator_ua.h.
    {
      return "uk";
    }
trLegend() [1/2]
virtual QCString TranslatorUkrainian::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1027 of file translator_ua.h.
    {
      return ". ";
    }
trLegend() [2/2]
virtual QCString TranslatorUkrainian::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1027 of file translator_ua.h.
    {
      return ". ";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorUkrainian::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 968 of file translator_ua.h.
    {
      return
        ", .<p>\n"
        " :\n"
        "\\code\n"
        "/*! */\n"
        "class Invisible { };\n\n"
        "/*! , */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* */\n"
        "class Undocumented { };\n\n"
        "/*! */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! */\n"
        "class ProtectedBase { };\n\n"
        "/*! */\n"
        "class PrivateBase { };\n\n"
        "/*! , Inherited */\n"
        "class Used { };\n\n"
        "/*! , */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        " , :"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        " :\n"
        "<ul>\n"
        "<li> , "
        " .\n"
        "<li> .\n"
        "<li> .\n"
        "<li> , \n"
        " / . , "
        " ."
        "</ul>\n"
        " :\n"
        "<ul>\n"
        "<li> "
        " .\n"
        "<li> .\n"
        "<li> .\n"
        "<li> , "
        " ."
        " , "
        " . \n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorUkrainian::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 968 of file translator_ua.h.
    {
      return
        ", .<p>\n"
        " :\n"
        "\\code\n"
        "/*! */\n"
        "class Invisible { };\n\n"
        "/*! , */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* */\n"
        "class Undocumented { };\n\n"
        "/*! */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! */\n"
        "class ProtectedBase { };\n\n"
        "/*! */\n"
        "class PrivateBase { };\n\n"
        "/*! , Inherited */\n"
        "class Used { };\n\n"
        "/*! , */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        " , :"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        " :\n"
        "<ul>\n"
        "<li> , "
        " .\n"
        "<li> .\n"
        "<li> .\n"
        "<li> , \n"
        " / . , "
        " ."
        "</ul>\n"
        " :\n"
        "<ul>\n"
        "<li> "
        " .\n"
        "<li> .\n"
        "<li> .\n"
        "<li> , "
        " ."
        " , "
        " . \n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorUkrainian::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 963 of file translator_ua.h.
    {
      return "";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorUkrainian::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 963 of file translator_ua.h.
    {
      return "";
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorUkrainian::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 88 of file translator_ua.h.
    {
      return " " ;
    }
trListOfAllMembers() [2/2]
virtual QCString TranslatorUkrainian::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 88 of file translator_ua.h.
    {
      return " " ;
    }
trLoading() [1/2]
virtual QCString TranslatorUkrainian::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1720 of file translator_ua.h.
    {
      return "...";
    }
trLoading() [2/2]
virtual QCString TranslatorUkrainian::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1720 of file translator_ua.h.
    {
      return "...";
    }
trMainPage() [1/2]
virtual QCString TranslatorUkrainian::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 760 of file translator_ua.h.
    { return " "; }
trMainPage() [2/2]
virtual QCString TranslatorUkrainian::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 760 of file translator_ua.h.
    { return " "; }
trMember() [1/2]
virtual QCString TranslatorUkrainian::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1200 of file translator_ua.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorUkrainian::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1200 of file translator_ua.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorUkrainian::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 70 of file translator_ua.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "" ;
      }
      else
      {
        return " " ;
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorUkrainian::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 70 of file translator_ua.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "" ;
      }
      else
      {
        return " " ;
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorUkrainian::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 62 of file translator_ua.h.
    { return " "; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorUkrainian::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 62 of file translator_ua.h.
    { return " "; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorUkrainian::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 66 of file translator_ua.h.
    { return " "; }
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorUkrainian::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 66 of file translator_ua.h.
    { return " "; }
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorUkrainian::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1495 of file translator_ua.h.
    { return " /"; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorUkrainian::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1495 of file translator_ua.h.
    { return " /"; }
trMemberList() [1/2]
virtual QCString TranslatorUkrainian::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 95 of file translator_ua.h.
    {
      return "C " ;
    }
trMemberList() [2/2]
virtual QCString TranslatorUkrainian::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 95 of file translator_ua.h.
    {
      return "C " ;
    }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorUkrainian::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 58 of file translator_ua.h.
    { return " "; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorUkrainian::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 58 of file translator_ua.h.
    { return " "; }
trMethodDocumentation() [1/2]
virtual QCString TranslatorUkrainian::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1915 of file translator_ua.h.
    {
      return " ";
    }
trMethodDocumentation() [2/2]
virtual QCString TranslatorUkrainian::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1915 of file translator_ua.h.
    {
      return " ";
    }
trModule() [1/2]
virtual QCString TranslatorUkrainian::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1650 of file translator_ua.h.
    {
            QCString result((first_capital ? "" : ""));
            result+=(singular? "": "");
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorUkrainian::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1650 of file translator_ua.h.
    {
            QCString result((first_capital ? "" : ""));
            result+=(singular? "": "");
      return result;
    }
trModuleDocumentation() [1/2]
virtual QCString TranslatorUkrainian::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 329 of file translator_ua.h.
    { return " "; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorUkrainian::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 329 of file translator_ua.h.
    { return " "; }
trModuleIndex() [1/2]
virtual QCString TranslatorUkrainian::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 296 of file translator_ua.h.
    { return " "; }
trModuleIndex() [2/2]
virtual QCString TranslatorUkrainian::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 296 of file translator_ua.h.
    { return " "; }
trModuleReference() [1/2]
virtual QCString TranslatorUkrainian::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1612 of file translator_ua.h.
    {
      QCString result=namespaceName;
      result+=" ";
      return result;
    }
trModuleReference() [2/2]
virtual QCString TranslatorUkrainian::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1612 of file translator_ua.h.
    {
      QCString result=namespaceName;
      result+=" ";
      return result;
    }
trModules() [1/2]
virtual QCString TranslatorUkrainian::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 137 of file translator_ua.h.
    { return " "; }
trModules() [2/2]
virtual QCString TranslatorUkrainian::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 137 of file translator_ua.h.
    { return " "; }
trModulesDescription() [1/2]
virtual QCString TranslatorUkrainian::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 284 of file translator_ua.h.
    { return " ."; }
trModulesDescription() [2/2]
virtual QCString TranslatorUkrainian::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 284 of file translator_ua.h.
    { return " ."; }
trModulesIndex() [1/2]
virtual QCString TranslatorUkrainian::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1643 of file translator_ua.h.
    { return " "; }
trModulesIndex() [2/2]
virtual QCString TranslatorUkrainian::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1643 of file translator_ua.h.
    { return " "; }
trModulesList() [1/2]
virtual QCString TranslatorUkrainian::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1562 of file translator_ua.h.
    { return " "; }
trModulesList() [2/2]
virtual QCString TranslatorUkrainian::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1562 of file translator_ua.h.
    { return " "; }
trModulesListDescription() [1/2]
virtual QCString TranslatorUkrainian::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1566 of file translator_ua.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" :";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorUkrainian::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1566 of file translator_ua.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" :";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorUkrainian::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1624 of file translator_ua.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" ";
      if (extractAll)
      {
        result+=" :";
      }
      else
      {
        result+=", :";
      }
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorUkrainian::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1624 of file translator_ua.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" ";
      if (extractAll)
      {
        result+=" :";
      }
      else
      {
        result+=", :";
      }
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorUkrainian::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1620 of file translator_ua.h.
    { return " "; }
trModulesMembers() [2/2]
virtual QCString TranslatorUkrainian::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1620 of file translator_ua.h.
    { return " "; }
trMonth() [1/2]
virtual QCString TranslatorUkrainian::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1798 of file translator_ua.h.
    {
      static const char *months_short[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      static const char *months_full[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      return text;
    }
trMonth() [2/2]
virtual QCString TranslatorUkrainian::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1798 of file translator_ua.h.
    {
      static const char *months_short[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      static const char *months_full[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      return text;
    }
trMore() [1/2]
virtual QCString TranslatorUkrainian::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 83 of file translator_ua.h.
    { return "..."; }
trMore() [2/2]
virtual QCString TranslatorUkrainian::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 83 of file translator_ua.h.
    { return "..."; }
trNamespace() [1/2]
virtual QCString TranslatorUkrainian::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1167 of file translator_ua.h.
    {
      QCString result((first_capital ? "" : ""));
      result+=(singular?" ":" ");
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorUkrainian::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1167 of file translator_ua.h.
    {
      QCString result((first_capital ? "" : ""));
      result+=(singular?" ":" ");
      return result;
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorUkrainian::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 694 of file translator_ua.h.
    { return " "; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorUkrainian::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 694 of file translator_ua.h.
    { return " "; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorUkrainian::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 688 of file translator_ua.h.
    { return " "; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorUkrainian::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 688 of file translator_ua.h.
    { return " "; }
trNamespaceList() [1/2]
virtual QCString TranslatorUkrainian::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 507 of file translator_ua.h.
    { return " "; }
trNamespaceList() [2/2]
virtual QCString TranslatorUkrainian::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 507 of file translator_ua.h.
    { return " "; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorUkrainian::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 511 of file translator_ua.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" .";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorUkrainian::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 511 of file translator_ua.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" .";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorUkrainian::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 673 of file translator_ua.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" ";
      if (extractAll)
        result+=" :";
      else
        result+=" :";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorUkrainian::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 673 of file translator_ua.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+=" ";
      if (extractAll)
        result+=" :";
      else
        result+=" :";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorUkrainian::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 669 of file translator_ua.h.
    { return " "; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorUkrainian::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 669 of file translator_ua.h.
    { return " "; }
trNamespaceReference() [1/2]
virtual QCString TranslatorUkrainian::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 585 of file translator_ua.h.
    {
      return QCString(" ")+namespaceName;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorUkrainian::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 585 of file translator_ua.h.
    {
      return QCString(" ")+namespaceName;
    }
trNamespaces() [1/2]
virtual QCString TranslatorUkrainian::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 704 of file translator_ua.h.
    { return " " ; }
trNamespaces() [2/2]
virtual QCString TranslatorUkrainian::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 704 of file translator_ua.h.
    { return " " ; }
trNoMatches() [1/2]
virtual QCString TranslatorUkrainian::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1738 of file translator_ua.h.
    {
      return " ";
    }
trNoMatches() [2/2]
virtual QCString TranslatorUkrainian::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1738 of file translator_ua.h.
    {
      return " ";
    }
trNote() [1/2]
virtual QCString TranslatorUkrainian::trNote () [inline], [virtual]
Implements Translator.
Definition at line 866 of file translator_ua.h.
    {
      return "";
    }
trNote() [2/2]
virtual QCString TranslatorUkrainian::trNote () [inline], [virtual]
Implements Translator.
Definition at line 866 of file translator_ua.h.
    {
      return "";
    }
trOverloadText() [1/2]
virtual QCString TranslatorUkrainian::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1467 of file translator_ua.h.
    {
       return " , "
              " . "
              " .";
    }
trOverloadText() [2/2]
virtual QCString TranslatorUkrainian::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1467 of file translator_ua.h.
    {
       return " , "
              " . "
              " .";
    }
trPackage() [1/2]
virtual QCString TranslatorUkrainian::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1079 of file translator_ua.h.
    {
      return QCString(" ")+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorUkrainian::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1079 of file translator_ua.h.
    {
      return QCString(" ")+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorUkrainian::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1338 of file translator_ua.h.
    {
      return " ";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorUkrainian::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1338 of file translator_ua.h.
    {
      return " ";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorUkrainian::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1318 of file translator_ua.h.
    {
      return " ";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorUkrainian::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1318 of file translator_ua.h.
    {
      return " ";
    }
trPackageListDescription() [1/2]
virtual QCString TranslatorUkrainian::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1084 of file translator_ua.h.
    {
      return " .";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorUkrainian::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1084 of file translator_ua.h.
    {
      return " .";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorUkrainian::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1322 of file translator_ua.h.
    {
      return " ";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorUkrainian::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1322 of file translator_ua.h.
    {
      return " ";
    }
trPackages() [1/2]
virtual QCString TranslatorUkrainian::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1089 of file translator_ua.h.
    {
      return "";
    }
trPackages() [2/2]
virtual QCString TranslatorUkrainian::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1089 of file translator_ua.h.
    {
      return "";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorUkrainian::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1310 of file translator_ua.h.
    {
      return " ";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorUkrainian::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1310 of file translator_ua.h.
    {
      return " ";
    }
trPage() [1/2]
virtual QCString TranslatorUkrainian::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1189 of file translator_ua.h.
    {
      QCString result((first_capital ? "" : ""));
      result+=(singular ? "" : "");
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorUkrainian::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1189 of file translator_ua.h.
    {
      QCString result((first_capital ? "" : ""));
      result+=(singular ? "" : "");
      return result;
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorUkrainian::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 766 of file translator_ua.h.
    { return "."; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorUkrainian::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 766 of file translator_ua.h.
    { return "."; }
trPageIndex() [1/2]
virtual QCString TranslatorUkrainian::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 857 of file translator_ua.h.
    {
      return " ";
    }
trPageIndex() [2/2]
virtual QCString TranslatorUkrainian::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 857 of file translator_ua.h.
    {
      return " ";
    }
trPanelSynchronisationTooltip() [1/2]
virtual QCString TranslatorUkrainian::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1873 of file translator_ua.h.
    {
      QCString opt = enable ? "" : "";
      return " , "+opt+" ";
    }
trPanelSynchronisationTooltip() [2/2]
virtual QCString TranslatorUkrainian::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1873 of file translator_ua.h.
    {
      QCString opt = enable ? "" : "";
      return " , "+opt+" ";
    }
trParameters() [1/2]
virtual QCString TranslatorUkrainian::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 491 of file translator_ua.h.
    { return ""; }
trParameters() [2/2]
virtual QCString TranslatorUkrainian::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 491 of file translator_ua.h.
    { return ""; }
trPostcondition() [1/2]
virtual QCString TranslatorUkrainian::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 826 of file translator_ua.h.
    {
      return "";
    }
trPostcondition() [2/2]
virtual QCString TranslatorUkrainian::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 826 of file translator_ua.h.
    {
      return "";
    }
trPrecondition() [1/2]
virtual QCString TranslatorUkrainian::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 821 of file translator_ua.h.
    {
      return "";
    }
trPrecondition() [2/2]
virtual QCString TranslatorUkrainian::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 821 of file translator_ua.h.
    {
      return "";
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorUkrainian::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 905 of file translator_ua.h.
    {
      return " ";
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorUkrainian::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 905 of file translator_ua.h.
    {
      return " ";
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorUkrainian::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 604 of file translator_ua.h.
    { return " "; }
trPrivateMembers() [2/2]
virtual QCString TranslatorUkrainian::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 604 of file translator_ua.h.
    { return " "; }
trPrivateSlots() [1/2]
virtual QCString TranslatorUkrainian::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 606 of file translator_ua.h.
    { return " "; }
trPrivateSlots() [2/2]
virtual QCString TranslatorUkrainian::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 606 of file translator_ua.h.
    { return " "; }
trPrivateTypes() [1/2]
virtual QCString TranslatorUkrainian::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 901 of file translator_ua.h.
    {
      return " ";
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorUkrainian::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 901 of file translator_ua.h.
    {
      return " ";
    }
trProperties() [1/2]
virtual QCString TranslatorUkrainian::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1052 of file translator_ua.h.
    {
      return "";
    }
trProperties() [2/2]
virtual QCString TranslatorUkrainian::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1052 of file translator_ua.h.
    {
      return "";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorUkrainian::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1057 of file translator_ua.h.
    {
      return " ";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorUkrainian::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1057 of file translator_ua.h.
    {
      return " ";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorUkrainian::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 893 of file translator_ua.h.
    {
      return " ";
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorUkrainian::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 893 of file translator_ua.h.
    {
      return " ";
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorUkrainian::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 598 of file translator_ua.h.
    { return " "; }
trProtectedMembers() [2/2]
virtual QCString TranslatorUkrainian::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 598 of file translator_ua.h.
    { return " "; }
trProtectedSlots() [1/2]
virtual QCString TranslatorUkrainian::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 600 of file translator_ua.h.
    { return " "; }
trProtectedSlots() [2/2]
virtual QCString TranslatorUkrainian::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 600 of file translator_ua.h.
    { return " "; }
trProtectedTypes() [1/2]
virtual QCString TranslatorUkrainian::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 889 of file translator_ua.h.
    {
      return " ";
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorUkrainian::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 889 of file translator_ua.h.
    {
      return " ";
    }
trProvidedByCategory() [1/2]
virtual QCString TranslatorUkrainian::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1883 of file translator_ua.h.
    {
      return " @0.";
    }
trProvidedByCategory() [2/2]
virtual QCString TranslatorUkrainian::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1883 of file translator_ua.h.
    {
      return " @0.";
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorUkrainian::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 874 of file translator_ua.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " " ;
      }
      else
      {
        return " " ;
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorUkrainian::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 874 of file translator_ua.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " " ;
      }
      else
      {
        return " " ;
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorUkrainian::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 590 of file translator_ua.h.
    { return " "; }
trPublicMembers() [2/2]
virtual QCString TranslatorUkrainian::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 590 of file translator_ua.h.
    { return " "; }
trPublicSlots() [1/2]
virtual QCString TranslatorUkrainian::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 592 of file translator_ua.h.
    { return " "; }
trPublicSlots() [2/2]
virtual QCString TranslatorUkrainian::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 592 of file translator_ua.h.
    { return " "; }
trPublicTypes() [1/2]
virtual QCString TranslatorUkrainian::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 870 of file translator_ua.h.
    {
      return " ";
    }
trPublicTypes() [2/2]
virtual QCString TranslatorUkrainian::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 870 of file translator_ua.h.
    {
      return " ";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorUkrainian::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 936 of file translator_ua.h.
    {
      return " ";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorUkrainian::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 936 of file translator_ua.h.
    {
      return " ";
    }
trReferenceManual() [1/2]
virtual QCString TranslatorUkrainian::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 364 of file translator_ua.h.
    { return " "; }
trReferenceManual() [2/2]
virtual QCString TranslatorUkrainian::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 364 of file translator_ua.h.
    { return " "; }
trReferences() [1/2]
virtual QCString TranslatorUkrainian::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1237 of file translator_ua.h.
    {
      return "";
    }
trReferences() [2/2]
virtual QCString TranslatorUkrainian::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1237 of file translator_ua.h.
    {
      return "";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorUkrainian::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 655 of file translator_ua.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorUkrainian::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 655 of file translator_ua.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorUkrainian::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 663 of file translator_ua.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorUkrainian::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 663 of file translator_ua.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorUkrainian::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 532 of file translator_ua.h.
      { return " "; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorUkrainian::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 532 of file translator_ua.h.
      { return " "; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorUkrainian::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 46 of file translator_ua.h.
    { return " "; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorUkrainian::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 46 of file translator_ua.h.
    { return " "; }
trRelatedPages() [1/2]
virtual QCString TranslatorUkrainian::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 182 of file translator_ua.h.
    { return " "; }
trRelatedPages() [2/2]
virtual QCString TranslatorUkrainian::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 182 of file translator_ua.h.
    { return " "; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorUkrainian::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 280 of file translator_ua.h.
    { return " ."; }
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorUkrainian::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 280 of file translator_ua.h.
    { return " ."; }
trRelatedSubscript() [1/2]
virtual QCString TranslatorUkrainian::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 50 of file translator_ua.h.
    { return "()"; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorUkrainian::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 50 of file translator_ua.h.
    { return "()"; }
trRemarks() [1/2]
virtual QCString TranslatorUkrainian::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 940 of file translator_ua.h.
    {
      return ".";
    }
trRemarks() [2/2]
virtual QCString TranslatorUkrainian::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 940 of file translator_ua.h.
    {
      return ".";
    }
trReturns() [1/2]
virtual QCString TranslatorUkrainian::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 483 of file translator_ua.h.
    { return ""; }
trReturns() [2/2]
virtual QCString TranslatorUkrainian::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 483 of file translator_ua.h.
    { return ""; }
trReturnValues() [1/2]
virtual QCString TranslatorUkrainian::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 755 of file translator_ua.h.
    { return ", "; }
trReturnValues() [2/2]
virtual QCString TranslatorUkrainian::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 755 of file translator_ua.h.
    { return ", "; }
trRTFansicp() [1/2]
virtual QCString TranslatorUkrainian::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
Implements Translator.
Definition at line 1118 of file translator_ua.h.
    {
      return "1251";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorUkrainian::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
Implements Translator.
Definition at line 1118 of file translator_ua.h.
    {
      return "1251";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorUkrainian::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
Implements Translator.
Definition at line 1123 of file translator_ua.h.
    {
      return "204";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorUkrainian::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
Implements Translator.
Definition at line 1123 of file translator_ua.h.
    {
      return "204";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorUkrainian::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1128 of file translator_ua.h.
    {
      return " ";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorUkrainian::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1128 of file translator_ua.h.
    {
      return " ";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorUkrainian::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1269 of file translator_ua.h.
    {
      return "";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorUkrainian::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1269 of file translator_ua.h.
    {
      return "";
    }
trSearch() [1/2]
virtual QCString TranslatorUkrainian::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 192 of file translator_ua.h.
    { return ""; }
trSearch() [2/2]
virtual QCString TranslatorUkrainian::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 192 of file translator_ua.h.
    { return ""; }
trSearching() [1/2]
virtual QCString TranslatorUkrainian::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1732 of file translator_ua.h.
    {
      return "...";
    }
trSearching() [2/2]
virtual QCString TranslatorUkrainian::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1732 of file translator_ua.h.
    {
      return "...";
    }
trSearchMatches() [1/2]
virtual QCString TranslatorUkrainian::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1406 of file translator_ua.h.
    {
      return ":";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorUkrainian::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1406 of file translator_ua.h.
    {
      return ":";
    }
trSearchResults() [1/2]
virtual QCString TranslatorUkrainian::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1387 of file translator_ua.h.
    {
      if (numDocuments==0)
      {
        return " .";
      }
      else if (numDocuments==1)
      {
        return " <b>1</b> .";
      }
      else
      {
        return " <b>$num</b> . "
           " .";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorUkrainian::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1387 of file translator_ua.h.
    {
      if (numDocuments==0)
      {
        return " .";
      }
      else if (numDocuments==1)
      {
        return " <b>1</b> .";
      }
      else
      {
        return " <b>$num</b> . "
           " .";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorUkrainian::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1375 of file translator_ua.h.
    {
      return " ";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorUkrainian::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1375 of file translator_ua.h.
    {
      return " ";
    }
trSeeAlso() [1/2]
virtual QCString TranslatorUkrainian::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 487 of file translator_ua.h.
    { return ". "; }
trSeeAlso() [2/2]
virtual QCString TranslatorUkrainian::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 487 of file translator_ua.h.
    { return ". "; }
trSignals() [1/2]
virtual QCString TranslatorUkrainian::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 594 of file translator_ua.h.
    { return ""; }
trSignals() [2/2]
virtual QCString TranslatorUkrainian::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 594 of file translator_ua.h.
    { return ""; }
trSince() [1/2]
virtual QCString TranslatorUkrainian::trSince () [inline], [virtual]
Implements Translator.
Definition at line 952 of file translator_ua.h.
    {
      return " ";
    }
trSince() [2/2]
virtual QCString TranslatorUkrainian::trSince () [inline], [virtual]
Implements Translator.
Definition at line 952 of file translator_ua.h.
    {
      return " ";
    }
trSourceFile() [1/2]
virtual QCString TranslatorUkrainian::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1417 of file translator_ua.h.
    {
      return " "+filename;
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorUkrainian::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1417 of file translator_ua.h.
    {
      return " "+filename;
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorUkrainian::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1346 of file translator_ua.h.
    {
      return " ";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorUkrainian::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1346 of file translator_ua.h.
    {
      return " ";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorUkrainian::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1330 of file translator_ua.h.
    {
      return " ";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorUkrainian::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1330 of file translator_ua.h.
    {
      return " ";
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorUkrainian::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 909 of file translator_ua.h.
    {
      return " ";
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorUkrainian::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 909 of file translator_ua.h.
    {
      return " ";
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorUkrainian::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 608 of file translator_ua.h.
    { return " "; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorUkrainian::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 608 of file translator_ua.h.
    { return " "; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorUkrainian::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 897 of file translator_ua.h.
    {
      return " ";
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorUkrainian::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 897 of file translator_ua.h.
    {
      return " ";
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorUkrainian::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 602 of file translator_ua.h.
    { return " "; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorUkrainian::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 602 of file translator_ua.h.
    { return " "; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorUkrainian::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 885 of file translator_ua.h.
    {
      return " ";
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorUkrainian::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 885 of file translator_ua.h.
    {
      return " ";
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorUkrainian::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 596 of file translator_ua.h.
    { return " "; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorUkrainian::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 596 of file translator_ua.h.
    { return " "; }
trSubprogram() [1/2]
virtual QCString TranslatorUkrainian::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1696 of file translator_ua.h.
    {
      QCString result((first_capital ? "" : ""));
      result+= (singular? "": "");
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorUkrainian::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1696 of file translator_ua.h.
    {
      QCString result((first_capital ? "" : ""));
      result+= (singular? "": "");
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorUkrainian::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1552 of file translator_ua.h.
    { return " /"; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorUkrainian::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1552 of file translator_ua.h.
    { return " /"; }
trSubprograms() [1/2]
virtual QCString TranslatorUkrainian::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1546 of file translator_ua.h.
    { return "/"; }
trSubprograms() [2/2]
virtual QCString TranslatorUkrainian::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1546 of file translator_ua.h.
    { return "/"; }
trTemplateParameters() [1/2]
virtual QCString TranslatorUkrainian::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1836 of file translator_ua.h.
    { return " "; }
trTemplateParameters() [2/2]
virtual QCString TranslatorUkrainian::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1836 of file translator_ua.h.
    { return " "; }
trTest() [1/2]
virtual QCString TranslatorUkrainian::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1037 of file translator_ua.h.
    {
      return "";
    }
trTest() [2/2]
virtual QCString TranslatorUkrainian::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1037 of file translator_ua.h.
    {
      return "";
    }
trTestList() [1/2]
virtual QCString TranslatorUkrainian::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1042 of file translator_ua.h.
    {
      return " ";
    }
trTestList() [2/2]
virtual QCString TranslatorUkrainian::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1042 of file translator_ua.h.
    {
      return " ";
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorUkrainian::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 102 of file translator_ua.h.
    { return " "; }
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorUkrainian::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 102 of file translator_ua.h.
    { return " "; }
trTodo() [1/2]
virtual QCString TranslatorUkrainian::trTodo () [inline], [virtual]
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 920 of file translator_ua.h.
    {
      return " ";
    }
trTodo() [2/2]
virtual QCString TranslatorUkrainian::trTodo () [inline], [virtual]
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 920 of file translator_ua.h.
    {
      return " ";
    }
trTodoList() [1/2]
virtual QCString TranslatorUkrainian::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 926 of file translator_ua.h.
    {
      return " ";
    }
trTodoList() [2/2]
virtual QCString TranslatorUkrainian::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 926 of file translator_ua.h.
    {
      return " ";
    }
trType() [1/2]
virtual QCString TranslatorUkrainian::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1685 of file translator_ua.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trType() [2/2]
virtual QCString TranslatorUkrainian::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1685 of file translator_ua.h.
    {
      QCString result((first_capital ? "" : ""));
      if (!singular) result+="";
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorUkrainian::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1704 of file translator_ua.h.
    {
      return " ";
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorUkrainian::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1704 of file translator_ua.h.
    {
      return " ";
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorUkrainian::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 412 of file translator_ua.h.
    { return " "; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorUkrainian::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 412 of file translator_ua.h.
    { return " "; }
trTypedefs() [1/2]
virtual QCString TranslatorUkrainian::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 376 of file translator_ua.h.
    { return " "; }
trTypedefs() [2/2]
virtual QCString TranslatorUkrainian::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 376 of file translator_ua.h.
    { return " "; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorUkrainian::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1540 of file translator_ua.h.
    { return " "; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorUkrainian::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1540 of file translator_ua.h.
    { return " "; }
trVariableDocumentation() [1/2]
virtual QCString TranslatorUkrainian::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 430 of file translator_ua.h.
    { return " "; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorUkrainian::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 430 of file translator_ua.h.
    { return " "; }
trVariables() [1/2]
virtual QCString TranslatorUkrainian::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 394 of file translator_ua.h.
    { return ""; }
trVariables() [2/2]
virtual QCString TranslatorUkrainian::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 394 of file translator_ua.h.
    { return ""; }
trVersion() [1/2]
virtual QCString TranslatorUkrainian::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 475 of file translator_ua.h.
    { return ""; }
trVersion() [2/2]
virtual QCString TranslatorUkrainian::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 475 of file translator_ua.h.
    { return ""; }
trWarning() [1/2]
virtual QCString TranslatorUkrainian::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 471 of file translator_ua.h.
    { return ""; }
trWarning() [2/2]
virtual QCString TranslatorUkrainian::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 471 of file translator_ua.h.
    { return ""; }
trWriteList() [1/2]
virtual QCString TranslatorUkrainian::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 614 of file translator_ua.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+= " " ;
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorUkrainian::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 614 of file translator_ua.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+= " " ;
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_ua.h
doxygen/src/translator_ua.h