LinkedMap< T, Hash, KeyEqual, Map > Class Template Reference
Container class representing a vector of objects with keys.
#include <linkedmap.h>
Public Types
using Ptr = std::unique_ptr< T >
using Vec = std::vector< Ptr >
using iterator = typename Vec::iterator
using const_iterator = typename Vec::const_iterator
using reverse_iterator = typename Vec::reverse_iterator
using const_reverse_iterator = typename Vec::const_reverse_iterator
using Ptr = std::unique_ptr< T >
using Vec = std::vector< Ptr >
using iterator = typename Vec::iterator
using const_iterator = typename Vec::const_iterator
using reverse_iterator = typename Vec::reverse_iterator
using const_reverse_iterator = typename Vec::const_reverse_iterator
Public Member Functions
const T * find (const std::string &key) const
const T * find (const QCString &key) const
const T * find (const char *key) const
T * find (const char *key)
A non-const wrapper for find() const.
T * find (const QCString &key)
A non-const wrapper for find() const.
T * find (const std::string &key)
A non-const wrapper for find() const.
template<class... Args>
T * add (const char *k, Args &&... args)
template<class... Args>
T * add (const QCString &k, Args &&... args)
T * add (const char *k, Ptr &&ptr)
T * add (const QCString &k, Ptr &&ptr)
template<class... Args>
T * prepend (const char *k, Args &&... args)
template<class... Args>
T * prepend (const QCString &key, Args &&... args)
bool del (const QCString &key)
Ptr & operator[] (size_t pos)
const Ptr & operator[] (size_t pos) const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
bool empty () const
size_t size () const
void clear ()
const T * find (const std::string &key) const
const T * find (const QCString &key) const
const T * find (const char *key) const
T * find (const char *key)
A non-const wrapper for find() const.
T * find (const QCString &key)
A non-const wrapper for find() const.
T * find (const std::string &key)
A non-const wrapper for find() const.
template<class... Args>
T * add (const char *k, Args &&... args)
template<class... Args>
T * add (const QCString &k, Args &&... args)
T * add (const char *k, Ptr &&ptr)
T * add (const QCString &k, Ptr &&ptr)
template<class... Args>
T * prepend (const char *k, Args &&... args)
template<class... Args>
T * prepend (const QCString &key, Args &&... args)
bool del (const QCString &key)
Ptr & operator[] (size_t pos)
const Ptr & operator[] (size_t pos) const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
bool empty () const
size_t size () const
void clear ()
Private Attributes
Map m_lookup
Vec m_entries
Detailed Description
template<class T, class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
class LinkedMap< T, Hash, KeyEqual, Map >
Container class representing a vector of objects with keys.
Objects can efficiently be looked up given the key. Objects are owned by the container. When adding objects the order of addition is kept, and used while iterating.
Definition at line 35 of file linkedmap.h.
Member Typedef Documentation
const_iterator [1/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
using LinkedMap< T, Hash, KeyEqual, Map >::const_iterator = typename Vec::const_iterator
Definition at line 41 of file linkedmap.h.
const_iterator [2/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
using LinkedMap< T, Hash, KeyEqual, Map >::const_iterator = typename Vec::const_iterator
Definition at line 41 of file linkedmap.h.
const_reverse_iterator [1/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
using LinkedMap< T, Hash, KeyEqual, Map >::const_reverse_iterator = typename Vec::const_reverse_iterator
Definition at line 43 of file linkedmap.h.
const_reverse_iterator [2/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
using LinkedMap< T, Hash, KeyEqual, Map >::const_reverse_iterator = typename Vec::const_reverse_iterator
Definition at line 43 of file linkedmap.h.
iterator [1/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
using LinkedMap< T, Hash, KeyEqual, Map >::iterator = typename Vec::iterator
Definition at line 40 of file linkedmap.h.
iterator [2/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
using LinkedMap< T, Hash, KeyEqual, Map >::iterator = typename Vec::iterator
Definition at line 40 of file linkedmap.h.
Ptr [1/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
using LinkedMap< T, Hash, KeyEqual, Map >::Ptr = std::unique_ptr<T>
Definition at line 38 of file linkedmap.h.
Ptr [2/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
using LinkedMap< T, Hash, KeyEqual, Map >::Ptr = std::unique_ptr<T>
Definition at line 38 of file linkedmap.h.
reverse_iterator [1/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
using LinkedMap< T, Hash, KeyEqual, Map >::reverse_iterator = typename Vec::reverse_iterator
Definition at line 42 of file linkedmap.h.
reverse_iterator [2/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
using LinkedMap< T, Hash, KeyEqual, Map >::reverse_iterator = typename Vec::reverse_iterator
Definition at line 42 of file linkedmap.h.
Vec [1/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
using LinkedMap< T, Hash, KeyEqual, Map >::Vec = std::vector<Ptr>
Definition at line 39 of file linkedmap.h.
Vec [2/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
using LinkedMap< T, Hash, KeyEqual, Map >::Vec = std::vector<Ptr>
Definition at line 39 of file linkedmap.h.
Member Function Documentation
add() [1/8]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
template<class... Args>
T * LinkedMap< T, Hash, KeyEqual, Map >::add (const char * k, Args &&... args) [inline]
Adds a new object to the ordered vector if it was not added already. Return a non-owning pointer to the newly added object, or to the existing object if it was already inserted before under the given key.
Definition at line 90 of file linkedmap.h.
    {
      T *result = find(k);
      if (result==nullptr)
      {
        std::string key(k ? k : "");
        Ptr ptr = std::make_unique<T>(QCString(k),std::forward<Args>(args)...);
        result = ptr.get();
        m_lookup.insert({key,result});
        m_entries.push_back(std::move(ptr));
      }
      return result;
    }
References LinkedMap< T, Hash, KeyEqual, Map >::find(), LinkedMap< T, Hash, KeyEqual, Map >::m_entries, LinkedMap< T, Hash, KeyEqual, Map >::m_lookup, and string.
Referenced by doxmlparser.compound.memberdefType::__init__(), SectionManager::add(), addEnumValuesToEnums(), UsedDir::addFileDep(), addInstance(), HtmlHelpIndex::addItem(), addLocalObjCMethod(), ClassDefImpl::addMembersToTemplateInstance(), addRelatedPage(), DirDefImpl::addUsesDependency(), addVariableToClass(), addVariableToFile(), addXRefItem(), doxmlparser.compound.memberdefType::buildAttributes(), buildDefineList(), buildExampleList(), buildGroupListFiltered(), buildNamespaceList(), DirDefImpl::createNewDir(), doxmlparser.compound.memberdefType::exportAttributes(), findDefineDocumentation(), findEnums(), findMember(), findUsingDeclImports(), doxmlparser.compound.memberdefType::get_add(), GroupDefImpl::insertMember(), NamespaceDefImpl::insertMember(), ClassDefImpl::internalInsertMember(), ClassDefImpl::mergeCategory(), ClassDefImpl::mergeMembers(), readDir(), readFileOrDirectory(), SectionManager::replace(), resolveClassNestingRelations(), and doxmlparser.compound.memberdefType::set_add().
add() [2/8]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
template<class... Args>
T * LinkedMap< T, Hash, KeyEqual, Map >::add (const char * k, Args &&... args) [inline]
Adds a new object to the ordered vector if it was not added already. Return a non-owning pointer to the newly added object, or to the existing object if it was already inserted before under the given key.
Definition at line 90 of file linkedmap.h.
    {
      T *result = find(k);
      if (result==nullptr)
      {
        std::string key(k ? k : "");
        Ptr ptr = std::make_unique<T>(QCString(k),std::forward<Args>(args)...);
        result = ptr.get();
        m_lookup.insert({key,result});
        m_entries.push_back(std::move(ptr));
      }
      return result;
    }
References LinkedMap< T, Hash, KeyEqual, Map >::find(), LinkedMap< T, Hash, KeyEqual, Map >::m_entries, LinkedMap< T, Hash, KeyEqual, Map >::m_lookup, and string.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
add() [3/8]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
T * LinkedMap< T, Hash, KeyEqual, Map >::add (const char * k, Ptr && ptr) [inline]
Adds an existing object to the ordered vector (unless another object was already added under the same key). Ownership is transferred. Return a non-owning pointer to the newly added object, or to the existing object if it was already inserted before under the given key.
Definition at line 123 of file linkedmap.h.
    {
      T *result = find(k);
      if (result==nullptr)
      {
        std::string key(k ? k : "");
        result = ptr.get();
        m_lookup.insert({key,result});
        m_entries.push_back(std::move(ptr));
      }
      return result;
    }
References LinkedMap< T, Hash, KeyEqual, Map >::find(), LinkedMap< T, Hash, KeyEqual, Map >::m_entries, LinkedMap< T, Hash, KeyEqual, Map >::m_lookup, and string.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
add() [4/8]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
T * LinkedMap< T, Hash, KeyEqual, Map >::add (const char * k, Ptr && ptr) [inline]
Adds an existing object to the ordered vector (unless another object was already added under the same key). Ownership is transferred. Return a non-owning pointer to the newly added object, or to the existing object if it was already inserted before under the given key.
Definition at line 123 of file linkedmap.h.
    {
      T *result = find(k);
      if (result==nullptr)
      {
        std::string key(k ? k : "");
        result = ptr.get();
        m_lookup.insert({key,result});
        m_entries.push_back(std::move(ptr));
      }
      return result;
    }
References LinkedMap< T, Hash, KeyEqual, Map >::find(), LinkedMap< T, Hash, KeyEqual, Map >::m_entries, LinkedMap< T, Hash, KeyEqual, Map >::m_lookup, and string.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
add() [5/8]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
template<class... Args>
T * LinkedMap< T, Hash, KeyEqual, Map >::add (const QCString & k, Args &&... args) [inline]
Definition at line 105 of file linkedmap.h.
    {
      std::string key = k.str();
      T *result = find(key);
      if (result==nullptr)
      {
        Ptr ptr = std::make_unique<T>(k,std::forward<Args>(args)...);
        result = ptr.get();
        m_lookup.insert({key,result});
        m_entries.push_back(std::move(ptr));
      }
      return result;
    }
References LinkedMap< T, Hash, KeyEqual, Map >::find(), LinkedMap< T, Hash, KeyEqual, Map >::m_entries, LinkedMap< T, Hash, KeyEqual, Map >::m_lookup, QCString::str(), and string.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
add() [6/8]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
template<class... Args>
T * LinkedMap< T, Hash, KeyEqual, Map >::add (const QCString & k, Args &&... args) [inline]
Definition at line 105 of file linkedmap.h.
    {
      std::string key = k.str();
      T *result = find(key);
      if (result==nullptr)
      {
        Ptr ptr = std::make_unique<T>(k,std::forward<Args>(args)...);
        result = ptr.get();
        m_lookup.insert({key,result});
        m_entries.push_back(std::move(ptr));
      }
      return result;
    }
References LinkedMap< T, Hash, KeyEqual, Map >::find(), LinkedMap< T, Hash, KeyEqual, Map >::m_entries, LinkedMap< T, Hash, KeyEqual, Map >::m_lookup, QCString::str(), and string.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
add() [7/8]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
T * LinkedMap< T, Hash, KeyEqual, Map >::add (const QCString & k, Ptr && ptr) [inline]
Definition at line 136 of file linkedmap.h.
    {
      std::string key = k.str();
      T *result = find(key);
      if (result==nullptr)
      {
        result = ptr.get();
        m_lookup.insert({key,result});
        m_entries.push_back(std::move(ptr));
      }
      return result;
    }
References LinkedMap< T, Hash, KeyEqual, Map >::find(), LinkedMap< T, Hash, KeyEqual, Map >::m_entries, LinkedMap< T, Hash, KeyEqual, Map >::m_lookup, QCString::str(), and string.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
add() [8/8]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
T * LinkedMap< T, Hash, KeyEqual, Map >::add (const QCString & k, Ptr && ptr) [inline]
Definition at line 136 of file linkedmap.h.
    {
      std::string key = k.str();
      T *result = find(key);
      if (result==nullptr)
      {
        result = ptr.get();
        m_lookup.insert({key,result});
        m_entries.push_back(std::move(ptr));
      }
      return result;
    }
References LinkedMap< T, Hash, KeyEqual, Map >::find(), LinkedMap< T, Hash, KeyEqual, Map >::m_entries, LinkedMap< T, Hash, KeyEqual, Map >::m_lookup, QCString::str(), and string.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
begin() [1/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
iterator LinkedMap< T, Hash, KeyEqual, Map >::begin () [inline]
Definition at line 201 of file linkedmap.h.
{ return m_entries.begin(); }
References LinkedMap< T, Hash, KeyEqual, Map >::m_entries.
Referenced by computeCommonDirPrefix(), DirDefImpl::computeDependencies(), UsedDir::sort(), and ClassDefImpl::sortAllMembersList().
begin() [2/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
iterator LinkedMap< T, Hash, KeyEqual, Map >::begin () [inline]
Definition at line 201 of file linkedmap.h.
{ return m_entries.begin(); }
References LinkedMap< T, Hash, KeyEqual, Map >::m_entries.
begin() [3/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
const_iterator LinkedMap< T, Hash, KeyEqual, Map >::begin () const [inline]
Definition at line 203 of file linkedmap.h.
{ return m_entries.cbegin(); }
References LinkedMap< T, Hash, KeyEqual, Map >::m_entries.
begin() [4/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
const_iterator LinkedMap< T, Hash, KeyEqual, Map >::begin () const [inline]
Definition at line 203 of file linkedmap.h.
{ return m_entries.cbegin(); }
References LinkedMap< T, Hash, KeyEqual, Map >::m_entries.
clear() [1/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
void LinkedMap< T, Hash, KeyEqual, Map >::clear () [inline]
Definition at line 212 of file linkedmap.h.
    {
      m_entries.clear();
      m_lookup.clear();
    }
References LinkedMap< T, Hash, KeyEqual, Map >::m_entries, and LinkedMap< T, Hash, KeyEqual, Map >::m_lookup.
Referenced by cleanUpDoxygen(), and clearAll().
clear() [2/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
void LinkedMap< T, Hash, KeyEqual, Map >::clear () [inline]
Definition at line 212 of file linkedmap.h.
    {
      m_entries.clear();
      m_lookup.clear();
    }
References LinkedMap< T, Hash, KeyEqual, Map >::m_entries, and LinkedMap< T, Hash, KeyEqual, Map >::m_lookup.
del() [1/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
bool LinkedMap< T, Hash, KeyEqual, Map >::del (const QCString & key) [inline]
Removes an object from the container and deletes it. Returns true if the object was deleted or false it is was not found.
Definition at line 183 of file linkedmap.h.
    {
      auto it = m_lookup.find(key.str());
      if (it!=m_lookup.end())
      {
        auto vecit = std::find_if(m_entries.begin(),m_entries.end(),[obj=it->second](auto &el) { return el.get()==obj; });
        if (vecit!=m_entries.end()) // should always be true
        {
          m_entries.erase(vecit);
          m_lookup.erase(it);
          return true;
        }
      }
      return false;
    }
References LinkedMap< T, Hash, KeyEqual, Map >::m_entries, LinkedMap< T, Hash, KeyEqual, Map >::m_lookup, and QCString::str().
Referenced by GroupDefImpl::removeMember().
del() [2/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
bool LinkedMap< T, Hash, KeyEqual, Map >::del (const QCString & key) [inline]
Removes an object from the container and deletes it. Returns true if the object was deleted or false it is was not found.
Definition at line 183 of file linkedmap.h.
    {
      auto it = m_lookup.find(key.str());
      if (it!=m_lookup.end())
      {
        auto vecit = std::find_if(m_entries.begin(),m_entries.end(),[obj=it->second](auto &el) { return el.get()==obj; });
        if (vecit!=m_entries.end()) // should always be true
        {
          m_entries.erase(vecit);
          m_lookup.erase(it);
          return true;
        }
      }
      return false;
    }
References LinkedMap< T, Hash, KeyEqual, Map >::m_entries, LinkedMap< T, Hash, KeyEqual, Map >::m_lookup, and QCString::str().
empty() [1/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
bool LinkedMap< T, Hash, KeyEqual, Map >::empty () const [inline]
Definition at line 209 of file linkedmap.h.
{ return m_entries.empty(); }
References LinkedMap< T, Hash, KeyEqual, Map >::m_entries.
Referenced by DirDefImpl::depGraphIsTrivial(), quickLinkVisible(), ClassDefImpl::writeMemberList(), and ClassDefImpl::writeSummaryLinks().
empty() [2/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
bool LinkedMap< T, Hash, KeyEqual, Map >::empty () const [inline]
Definition at line 209 of file linkedmap.h.
{ return m_entries.empty(); }
References LinkedMap< T, Hash, KeyEqual, Map >::m_entries.
end() [1/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
iterator LinkedMap< T, Hash, KeyEqual, Map >::end () [inline]
Definition at line 202 of file linkedmap.h.
{ return m_entries.end(); }
References LinkedMap< T, Hash, KeyEqual, Map >::m_entries.
Referenced by DirDefImpl::computeDependencies(), UsedDir::sort(), and ClassDefImpl::sortAllMembersList().
end() [2/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
iterator LinkedMap< T, Hash, KeyEqual, Map >::end () [inline]
Definition at line 202 of file linkedmap.h.
{ return m_entries.end(); }
References LinkedMap< T, Hash, KeyEqual, Map >::m_entries.
end() [3/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
const_iterator LinkedMap< T, Hash, KeyEqual, Map >::end () const [inline]
Definition at line 204 of file linkedmap.h.
{ return m_entries.cend(); }
References LinkedMap< T, Hash, KeyEqual, Map >::m_entries.
end() [4/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
const_iterator LinkedMap< T, Hash, KeyEqual, Map >::end () const [inline]
Definition at line 204 of file linkedmap.h.
{ return m_entries.cend(); }
References LinkedMap< T, Hash, KeyEqual, Map >::m_entries.
find() [1/12]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
T * LinkedMap< T, Hash, KeyEqual, Map >::find (const char * key) [inline]
A non-const wrapper for find() const.
Definition at line 69 of file linkedmap.h.
    {
      return const_cast<T*>(static_cast<const LinkedMap&>(*this).find(key));
    }
References LinkedMap< T, Hash, KeyEqual, Map >::find().
find() [2/12]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
T * LinkedMap< T, Hash, KeyEqual, Map >::find (const char * key) [inline]
A non-const wrapper for find() const.
Definition at line 69 of file linkedmap.h.
    {
      return const_cast<T*>(static_cast<const LinkedMap&>(*this).find(key));
    }
References LinkedMap< T, Hash, KeyEqual, Map >::find().
find() [3/12]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
const T * LinkedMap< T, Hash, KeyEqual, Map >::find (const char * key) const [inline]
Find an object given the key. Returns a pointer to the element if found or nullptr if it is not found.
Definition at line 63 of file linkedmap.h.
    {
      return find(std::string(key ? key : ""));
    }
References LinkedMap< T, Hash, KeyEqual, Map >::find(), and string.
find() [4/12]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
const T * LinkedMap< T, Hash, KeyEqual, Map >::find (const char * key) const [inline]
Find an object given the key. Returns a pointer to the element if found or nullptr if it is not found.
Definition at line 63 of file linkedmap.h.
    {
      return find(std::string(key ? key : ""));
    }
References LinkedMap< T, Hash, KeyEqual, Map >::find(), and string.
find() [5/12]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
T * LinkedMap< T, Hash, KeyEqual, Map >::find (const QCString & key) [inline]
A non-const wrapper for find() const.
Definition at line 75 of file linkedmap.h.
    {
      return const_cast<T*>(static_cast<const LinkedMap&>(*this).find(key));
    }
References LinkedMap< T, Hash, KeyEqual, Map >::find().
find() [6/12]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
T * LinkedMap< T, Hash, KeyEqual, Map >::find (const QCString & key) [inline]
A non-const wrapper for find() const.
Definition at line 75 of file linkedmap.h.
    {
      return const_cast<T*>(static_cast<const LinkedMap&>(*this).find(key));
    }
References LinkedMap< T, Hash, KeyEqual, Map >::find().
find() [7/12]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
const T * LinkedMap< T, Hash, KeyEqual, Map >::find (const QCString & key) const [inline]
Find an object given the key. Returns a pointer to the element if found or nullptr if it is not found.
Definition at line 55 of file linkedmap.h.
    {
      auto it = m_lookup.find(key.str());
      return it!=m_lookup.end() ? it->second : nullptr;
    }
References LinkedMap< T, Hash, KeyEqual, Map >::m_lookup, and QCString::str().
find() [8/12]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
const T * LinkedMap< T, Hash, KeyEqual, Map >::find (const QCString & key) const [inline]
Find an object given the key. Returns a pointer to the element if found or nullptr if it is not found.
Definition at line 55 of file linkedmap.h.
    {
      auto it = m_lookup.find(key.str());
      return it!=m_lookup.end() ? it->second : nullptr;
    }
References LinkedMap< T, Hash, KeyEqual, Map >::m_lookup, and QCString::str().
find() [9/12]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
T * LinkedMap< T, Hash, KeyEqual, Map >::find (const std::string & key) [inline]
A non-const wrapper for find() const.
Definition at line 81 of file linkedmap.h.
    {
      return const_cast<T*>(static_cast<const LinkedMap&>(*this).find(key));
    }
References LinkedMap< T, Hash, KeyEqual, Map >::find().
find() [10/12]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
T * LinkedMap< T, Hash, KeyEqual, Map >::find (const std::string & key) [inline]
A non-const wrapper for find() const.
Definition at line 81 of file linkedmap.h.
    {
      return const_cast<T*>(static_cast<const LinkedMap&>(*this).find(key));
    }
References LinkedMap< T, Hash, KeyEqual, Map >::find().
find() [11/12]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
const T * LinkedMap< T, Hash, KeyEqual, Map >::find (const std::string & key) const [inline]
Find an object given the key. Returns a pointer to the element if found or nullptr if it is not found.
Definition at line 47 of file linkedmap.h.
    {
      auto it = m_lookup.find(key);
      return it!=m_lookup.end() ? it->second : nullptr;
    }
References LinkedMap< T, Hash, KeyEqual, Map >::m_lookup.
Referenced by LinkedMap< T, Hash, KeyEqual, Map >::add(), addAnchor(), addClassToGroups(), addConceptToGroups(), addDirToGroups(), addEnumValuesToEnums(), addExampleToGroups(), addGroupToGroups(), anonymous_namespace{tagreader.cpp}::TagFileParser::addIncludes(), addMemberFunction(), addMemberToGroups(), addNamespaceToGroups(), addRelatedPage(), addSection(), DefinitionImpl::addSectionsToDefinition(), DirDefImpl::addUsesDependency(), addUsingDirective(), addVariableToClass(), addVariableToFile(), addXRefItem(), buildDirectories(), buildFileList(), buildGroupListFiltered(), buildNamespaceList(), buildScopeFromQualifiedName(), computePageRelations(), DirDefImpl::createNewDir(), DocAnchor::DocAnchor(), DocHtmlCaption::DocHtmlCaption(), DocRef::DocRef(), LinkedMap< T, Hash, KeyEqual, Map >::find(), findDefineDocumentation(), DocParser::findDocsForMemberOrCompound(), findEnumDocumentation(), findFileDef(), UsedDir::findFilePair(), findGlobalMember(), findMainPage(), findMember(), findUsedClassesForClass(), findUsingDeclImports(), findUsingDirectives(), generateMemberLink(), PerlModGenerator::generatePerlModForPage(), generateXMLForPage(), getClass(), VhdlDocGen::getClass(), getConcept(), getDefsOld(), getFortranDefs(), getFortranTypeDefs(), ClassDefImpl::getMemberByName(), getResolvedNamespace(), getTemplateArgumentsFromName(), ClassDefImpl::insertTemplateInstance(), isVarWithConstructor(), ClassDefImpl::mergeCategory(), ClassDefImpl::mergeMembers(), DocXRefItem::parse(), DocSection::parse(), DocSecRefItem::parse(), DocRoot::parse(), LinkedMap< T, Hash, KeyEqual, Map >::prepend(), processSection(), GroupDefImpl::removeMember(), SectionManager::replace(), resolveLink(), resolveRef(), resolveTypeDef(), resolveUserReferences(), showFileDefMatches(), PageDefImpl::writeDocumentation(), writeGroupTreeNode(), writeObjCMethodCall(), and GroupDefImpl::writePageDocumentation().
find() [12/12]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
const T * LinkedMap< T, Hash, KeyEqual, Map >::find (const std::string & key) const [inline]
Find an object given the key. Returns a pointer to the element if found or nullptr if it is not found.
Definition at line 47 of file linkedmap.h.
    {
      auto it = m_lookup.find(key);
      return it!=m_lookup.end() ? it->second : nullptr;
    }
References LinkedMap< T, Hash, KeyEqual, Map >::m_lookup.
operator[]() [1/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
Ptr & LinkedMap< T, Hash, KeyEqual, Map >::operator[] (size_t pos) [inline]
Definition at line 199 of file linkedmap.h.
{ return m_entries[pos]; }
References LinkedMap< T, Hash, KeyEqual, Map >::m_entries.
operator[]() [2/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
Ptr & LinkedMap< T, Hash, KeyEqual, Map >::operator[] (size_t pos) [inline]
Definition at line 199 of file linkedmap.h.
{ return m_entries[pos]; }
References LinkedMap< T, Hash, KeyEqual, Map >::m_entries.
operator[]() [3/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
const Ptr & LinkedMap< T, Hash, KeyEqual, Map >::operator[] (size_t pos) const [inline]
Definition at line 200 of file linkedmap.h.
{ return m_entries[pos]; }
References LinkedMap< T, Hash, KeyEqual, Map >::m_entries.
operator[]() [4/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
const Ptr & LinkedMap< T, Hash, KeyEqual, Map >::operator[] (size_t pos) const [inline]
Definition at line 200 of file linkedmap.h.
{ return m_entries[pos]; }
References LinkedMap< T, Hash, KeyEqual, Map >::m_entries.
prepend() [1/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
template<class... Args>
T * LinkedMap< T, Hash, KeyEqual, Map >::prepend (const char * k, Args &&... args) [inline]
Prepends a new object to the ordered vector if it was not added already. Return a non-owning pointer to the newly added object, or to the existing object if it was already inserted before under the given key.
Definition at line 153 of file linkedmap.h.
    {
      T *result = find(k);
      if (result==nullptr)
      {
        std::string key(k ? k : "");
        Ptr ptr = std::make_unique<T>(key.c_str(),std::forward<Args>(args)...);
        result = ptr.get();
        m_lookup.insert({key,result});
        m_entries.push_front(std::move(ptr));
      }
      return result;
    }
References LinkedMap< T, Hash, KeyEqual, Map >::find(), LinkedMap< T, Hash, KeyEqual, Map >::m_entries, LinkedMap< T, Hash, KeyEqual, Map >::m_lookup, and string.
prepend() [2/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
template<class... Args>
T * LinkedMap< T, Hash, KeyEqual, Map >::prepend (const char * k, Args &&... args) [inline]
Prepends a new object to the ordered vector if it was not added already. Return a non-owning pointer to the newly added object, or to the existing object if it was already inserted before under the given key.
Definition at line 153 of file linkedmap.h.
    {
      T *result = find(k);
      if (result==nullptr)
      {
        std::string key(k ? k : "");
        Ptr ptr = std::make_unique<T>(key.c_str(),std::forward<Args>(args)...);
        result = ptr.get();
        m_lookup.insert({key,result});
        m_entries.push_front(std::move(ptr));
      }
      return result;
    }
References LinkedMap< T, Hash, KeyEqual, Map >::find(), LinkedMap< T, Hash, KeyEqual, Map >::m_entries, LinkedMap< T, Hash, KeyEqual, Map >::m_lookup, and string.
prepend() [3/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
template<class... Args>
T * LinkedMap< T, Hash, KeyEqual, Map >::prepend (const QCString & key, Args &&... args) [inline]
Definition at line 168 of file linkedmap.h.
    {
      T *result = find(key);
      if (result==nullptr)
      {
        Ptr ptr = std::make_unique<T>(key,std::forward<Args>(args)...);
        result = ptr.get();
        m_lookup.insert({key.str(),result});
        m_entries.push_front(std::move(ptr));
      }
      return result;
    }
References LinkedMap< T, Hash, KeyEqual, Map >::find(), LinkedMap< T, Hash, KeyEqual, Map >::m_entries, LinkedMap< T, Hash, KeyEqual, Map >::m_lookup, and QCString::str().
prepend() [4/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
template<class... Args>
T * LinkedMap< T, Hash, KeyEqual, Map >::prepend (const QCString & key, Args &&... args) [inline]
Definition at line 168 of file linkedmap.h.
    {
      T *result = find(key);
      if (result==nullptr)
      {
        Ptr ptr = std::make_unique<T>(key,std::forward<Args>(args)...);
        result = ptr.get();
        m_lookup.insert({key.str(),result});
        m_entries.push_front(std::move(ptr));
      }
      return result;
    }
References LinkedMap< T, Hash, KeyEqual, Map >::find(), LinkedMap< T, Hash, KeyEqual, Map >::m_entries, LinkedMap< T, Hash, KeyEqual, Map >::m_lookup, and QCString::str().
rbegin() [1/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
reverse_iterator LinkedMap< T, Hash, KeyEqual, Map >::rbegin () [inline]
Definition at line 205 of file linkedmap.h.
{ return m_entries.rbegin(); }
References LinkedMap< T, Hash, KeyEqual, Map >::m_entries.
rbegin() [2/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
reverse_iterator LinkedMap< T, Hash, KeyEqual, Map >::rbegin () [inline]
Definition at line 205 of file linkedmap.h.
{ return m_entries.rbegin(); }
References LinkedMap< T, Hash, KeyEqual, Map >::m_entries.
rbegin() [3/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
const_reverse_iterator LinkedMap< T, Hash, KeyEqual, Map >::rbegin () const [inline]
Definition at line 207 of file linkedmap.h.
{ return m_entries.crbegin(); }
References LinkedMap< T, Hash, KeyEqual, Map >::m_entries.
rbegin() [4/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
const_reverse_iterator LinkedMap< T, Hash, KeyEqual, Map >::rbegin () const [inline]
Definition at line 207 of file linkedmap.h.
{ return m_entries.crbegin(); }
References LinkedMap< T, Hash, KeyEqual, Map >::m_entries.
rend() [1/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
reverse_iterator LinkedMap< T, Hash, KeyEqual, Map >::rend () [inline]
Definition at line 206 of file linkedmap.h.
{ return m_entries.rend(); }
References LinkedMap< T, Hash, KeyEqual, Map >::m_entries.
rend() [2/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
reverse_iterator LinkedMap< T, Hash, KeyEqual, Map >::rend () [inline]
Definition at line 206 of file linkedmap.h.
{ return m_entries.rend(); }
References LinkedMap< T, Hash, KeyEqual, Map >::m_entries.
rend() [3/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
const_reverse_iterator LinkedMap< T, Hash, KeyEqual, Map >::rend () const [inline]
Definition at line 208 of file linkedmap.h.
{ return m_entries.crend(); }
References LinkedMap< T, Hash, KeyEqual, Map >::m_entries.
rend() [4/4]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
const_reverse_iterator LinkedMap< T, Hash, KeyEqual, Map >::rend () const [inline]
Definition at line 208 of file linkedmap.h.
{ return m_entries.crend(); }
References LinkedMap< T, Hash, KeyEqual, Map >::m_entries.
size() [1/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
size_t LinkedMap< T, Hash, KeyEqual, Map >::size () const [inline]
Definition at line 210 of file linkedmap.h.
{ return m_entries.size(); }
References LinkedMap< T, Hash, KeyEqual, Map >::m_entries.
Referenced by computeClassRelations(), and HtmlHelpIndex::size().
size() [2/2]
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
size_t LinkedMap< T, Hash, KeyEqual, Map >::size () const [inline]
Definition at line 210 of file linkedmap.h.
{ return m_entries.size(); }
References LinkedMap< T, Hash, KeyEqual, Map >::m_entries.
Member Data Documentation
m_entries
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
Vec LinkedMap< T, Hash, KeyEqual, Map >::m_entries [private]
Definition at line 221 of file linkedmap.h.
Referenced by LinkedMap< T, Hash, KeyEqual, Map >::add(), LinkedMap< T, Hash, KeyEqual, Map >::begin(), LinkedMap< T, Hash, KeyEqual, Map >::clear(), LinkedMap< T, Hash, KeyEqual, Map >::del(), LinkedMap< T, Hash, KeyEqual, Map >::empty(), LinkedMap< T, Hash, KeyEqual, Map >::end(), LinkedMap< T, Hash, KeyEqual, Map >::operator[](), LinkedMap< T, Hash, KeyEqual, Map >::prepend(), LinkedMap< T, Hash, KeyEqual, Map >::rbegin(), LinkedMap< T, Hash, KeyEqual, Map >::rend(), and LinkedMap< T, Hash, KeyEqual, Map >::size().
m_lookup
template<class T , class Hash = std::hash<std::string>, class KeyEqual = std::equal_to<std::string>, class Map = std::unordered_map<std::string,T*,Hash,KeyEqual >>
Map LinkedMap< T, Hash, KeyEqual, Map >::m_lookup [private]
Definition at line 220 of file linkedmap.h.
Referenced by LinkedMap< T, Hash, KeyEqual, Map >::add(), LinkedMap< T, Hash, KeyEqual, Map >::clear(), LinkedMap< T, Hash, KeyEqual, Map >::del(), LinkedMap< T, Hash, KeyEqual, Map >::find(), and LinkedMap< T, Hash, KeyEqual, Map >::prepend().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/linkedmap.h
doxygen/src/linkedmap.h