DocSimpleList Class Reference
#include <docnode.h>
Public Member Functions
DocSimpleList (DocParser *parser, DocNodeVariant *parent)
int parse (DocNodeVariant *)
DocSimpleList (DocParser *parser, DocNodeVariant *parent)
int parse (DocNodeVariant *)
Additional Inherited Members
Detailed Description
Node representing a simple list
Definition at line 942 of file docnode.h.
Constructor & Destructor Documentation
DocSimpleList() [1/2]
DocSimpleList::DocSimpleList (DocParser * parser, DocNodeVariant * parent) [inline]
Definition at line 945 of file docnode.h.
: DocCompoundNode(parser,parent) {}
DocSimpleList() [2/2]
DocSimpleList::DocSimpleList (DocParser * parser, DocNodeVariant * parent) [inline]
Definition at line 945 of file docnode.h.
: DocCompoundNode(parser,parent) {}
Member Function Documentation
parse() [1/2]
int DocSimpleList::parse (DocNodeVariant * thisVariant)
Definition at line 2635 of file docnode.cpp.
{
  auto ns = AutoNodeStack(parser(),thisVariant);
  int rv;
  do
  {
    auto vDocSimpleListItem = children().append<DocSimpleListItem>(parser(),thisVariant);
    DocSimpleListItem *li = children().get_last<DocSimpleListItem>();
    rv=li->parse(vDocSimpleListItem);
  } while (rv==RetVal_ListItem);
  return (rv!=TK_NEWPARA) ? rv : RetVal_OK;
}
References DocNodeList::append(), DocCompoundNode::children(), DocNodeList::get_last(), DocSimpleListItem::parse(), DocNode::parser(), RetVal_ListItem, RetVal_OK, and TK_NEWPARA.
parse() [2/2]
int DocSimpleList::parse (DocNodeVariant *)
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docnode.h
doxygen/src/docnode.h
doxygen/build/doxygen/src/docnode.cpp
doxygen/src/docnode.cpp