IncludeInfoContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const QCString &name) const
virtual StringVector fields () const
IncludeInfoContext (const IncludeInfo *, SrcLangExt lang)
virtual ~IncludeInfoContext ()
virtual TemplateVariant get (const QCString &name) const
virtual StringVector fields () const
IncludeInfoContext (const IncludeInfo *, SrcLangExt lang)
virtual ~IncludeInfoContext ()
Static Public Member Functions
static TemplateStructIntfPtr alloc (const IncludeInfo *info, SrcLangExt lang)
static TemplateStructIntfPtr alloc (const IncludeInfo *info, SrcLangExt lang)
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Definition at line 155 of file context.h.
Constructor & Destructor Documentation
IncludeInfoContext() [1/2]
IncludeInfoContext::IncludeInfoContext (const IncludeInfo * info, SrcLangExt lang)
Definition at line 1653 of file context.cpp.
                                                                              : p(std::make_unique<Private>(info,lang))
{
}
 IncludeInfoContext() [1/2]
IncludeInfoContext::~IncludeInfoContext () [virtual]
Definition at line 1657 of file context.cpp.
{
}
IncludeInfoContext() [2/2]
IncludeInfoContext::IncludeInfoContext (const IncludeInfo * , SrcLangExt lang)
 IncludeInfoContext() [2/2]
virtual IncludeInfoContext::~IncludeInfoContext () [virtual]
Member Function Documentation
alloc() [1/2]
static TemplateStructIntfPtr IncludeInfoContext::alloc (const IncludeInfo * info, SrcLangExt lang) [inline], [static]
Definition at line 158 of file context.h.
    { return std::static_pointer_cast<TemplateStructIntf>(std::make_shared<IncludeInfoContext>(info,lang)); }
Referenced by ClassContext::Private::createIncludeInfo(), ConceptContext::Private::createIncludeInfo(), and IncludeInfoListContext::Private::Private().
alloc() [2/2]
static TemplateStructIntfPtr IncludeInfoContext::alloc (const IncludeInfo * info, SrcLangExt lang) [inline], [static]
Definition at line 158 of file context.h.
    { return std::static_pointer_cast<TemplateStructIntf>(std::make_shared<IncludeInfoContext>(info,lang)); }
fields() [1/2]
StringVector IncludeInfoContext::fields () const [virtual]
Return the list of fields.
Implements TemplateStructIntf.
Definition at line 1666 of file context.cpp.
{
  return p->fields();
}
References p.
fields() [2/2]
virtual StringVector IncludeInfoContext::fields () const [virtual]
Return the list of fields.
Implements TemplateStructIntf.
get() [1/2]
TemplateVariant IncludeInfoContext::get (const QCString & name) const [virtual]
Gets the value for a field name.
Parameters
 in name The name of the field.
Implements TemplateStructIntf.
Definition at line 1661 of file context.cpp.
{
  return p->get(n);
}
References n, and p.
get() [2/2]
virtual TemplateVariant IncludeInfoContext::get (const QCString & name) const [virtual]
Gets the value for a field name.
Parameters
 in name The name of the field.
Implements TemplateStructIntf.
Member Data Documentation
p
std::unique_ptr< Private > IncludeInfoContext::p [private]
Definition at line 170 of file context.h.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.h
doxygen/src/context.h
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp