TemplateNodeIndexEntry Class Reference
Class representing an 'indexentry' tag in a template.
Classes
struct Mapping
Public Member Functions
TemplateNodeIndexEntry (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void render (TextStream &, TemplateContext *c)
TemplateNodeIndexEntry (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void render (TextStream &, TemplateContext *c)
Private Attributes
QCString m_name
std::vector< Mapping > m_args
Additional Inherited Members
Detailed Description
Class representing an 'indexentry' tag in a template.
Definition at line 4040 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeIndexEntry() [1/2]
TemplateNodeIndexEntry::TemplateNodeIndexEntry (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 4049 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeIndexEntry>(parser,parent,line)
    {
      TRACE(("{TemplateNodeIndexEntry(%s)\n",qPrint(data)));
      ExpressionParser expParser(parser,line);
      std::vector<QCString> args = split(data," ");
      auto it = args.begin();
      if (it==args.end() || (*it).find('=')!=-1)
      {
        parser->warn(parser->templateName(),line,"Missing name for indexentry tag");
      }
      else
      {
        m_name = *it;
        ++it;
        while (it!=args.end())
        {
          QCString arg = *it;
          int j=arg.find('=');
          if (j>0)
          {
            ExprAstPtr expr = expParser.parse(arg.mid(j+1));
            if (expr)
            {
              m_args.emplace_back(arg.left(j),std::move(expr));
            }
          }
          else
          {
            parser->warn(parser->templateName(),line,"invalid argument '%s' for indexentry tag",qPrint(arg));
          }
          ++it;
        }
      }
      TRACE(("}TemplateNodeIndexEntry(%s)\n",qPrint(data)));
    }
References data, QCString::find(), QCString::left(), m_args, m_name, QCString::mid(), ExpressionParser::parse(), qPrint(), split(), TemplateParser::templateName(), TRACE, and TemplateParser::warn().
TemplateNodeIndexEntry() [2/2]
TemplateNodeIndexEntry::TemplateNodeIndexEntry (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 4049 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeIndexEntry>(parser,parent,line)
    {
      TRACE(("{TemplateNodeIndexEntry(%s)\n",qPrint(data)));
      ExpressionParser expParser(parser,line);
      std::vector<QCString> args = split(data," ");
      auto it = args.begin();
      if (it==args.end() || (*it).find('=')!=-1)
      {
        parser->warn(parser->templateName(),line,"Missing name for indexentry tag");
      }
      else
      {
        m_name = *it;
        ++it;
        while (it!=args.end())
        {
          QCString arg = *it;
          int j=arg.find('=');
          if (j>0)
          {
            ExprAstPtr expr = expParser.parse(arg.mid(j+1));
            if (expr)
            {
              m_args.emplace_back(arg.left(j),std::move(expr));
            }
          }
          else
          {
            parser->warn(parser->templateName(),line,"invalid argument '%s' for indexentry tag",qPrint(arg));
          }
          ++it;
        }
      }
      TRACE(("}TemplateNodeIndexEntry(%s)\n",qPrint(data)));
    }
References data, QCString::find(), QCString::left(), m_args, m_name, QCString::mid(), ExpressionParser::parse(), qPrint(), split(), TemplateParser::templateName(), TRACE, and TemplateParser::warn().
Member Function Documentation
render() [1/2]
void TemplateNodeIndexEntry::render (TextStream & , TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 4085 of file template.cpp.
    {
      TemplateContextImpl *ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      if (!m_name.isEmpty())
      {
        ci->setLocation(m_templateName,m_line);
        std::vector<TemplateKeyValue> list;
        for (const auto &mapping : m_args)
        {
          list.emplace_back(mapping.name,mapping.value->resolve(c));
        }
        ci->addIndexEntry(m_name,list);
      }
    }
References TemplateContextImpl::addIndexEntry(), c, QCString::isEmpty(), m_args, TemplateNodeCreator< TemplateNodeIndexEntry >::m_line, m_name, TemplateNodeCreator< TemplateNodeIndexEntry >::m_templateName, and TemplateContextImpl::setLocation().
render() [2/2]
void TemplateNodeIndexEntry::render (TextStream & , TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 4085 of file template.cpp.
    {
      TemplateContextImpl *ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      if (!m_name.isEmpty())
      {
        ci->setLocation(m_templateName,m_line);
        std::vector<TemplateKeyValue> list;
        for (const auto &mapping : m_args)
        {
          list.emplace_back(mapping.name,mapping.value->resolve(c));
        }
        ci->addIndexEntry(m_name,list);
      }
    }
References TemplateContextImpl::addIndexEntry(), c, QCString::isEmpty(), m_args, TemplateNodeCreator< TemplateNodeIndexEntry >::m_line, m_name, TemplateNodeCreator< TemplateNodeIndexEntry >::m_templateName, and TemplateContextImpl::setLocation().
Member Data Documentation
m_args
std::vector< Mapping > TemplateNodeIndexEntry::m_args [private]
Definition at line 4102 of file template.cpp.
Referenced by render(), and TemplateNodeIndexEntry().
m_name
QCString TemplateNodeIndexEntry::m_name [private]
Definition at line 4101 of file template.cpp.
Referenced by render(), and TemplateNodeIndexEntry().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp