DocDiaFile Class Reference
#include <docnode.h>
Public Member Functions
DocDiaFile (DocParser *parser, DocNodeVariant *parent, const QCString &name, const QCString &context, const QCString &srcFile, int srcLine)
bool parse (DocNodeVariant *)
DocDiaFile (DocParser *parser, DocNodeVariant *parent, const QCString &name, const QCString &context, const QCString &srcFile, int srcLine)
bool parse (DocNodeVariant *)
Additional Inherited Members
Detailed Description
Node representing a dia file
Definition at line 694 of file docnode.h.
Constructor & Destructor Documentation
DocDiaFile() [1/2]
DocDiaFile::DocDiaFile (DocParser * parser, DocNodeVariant * parent, const QCString & name, const QCString & context, const QCString & srcFile, int srcLine)
Definition at line 1088 of file docnode.cpp.
                                                            :
  DocDiagramFileBase(parser,parent,name,context,srcFile,srcLine)
{
  p->relPath = parser->context.relPath;
}
References DocParser::context, DocDiagramFileBase::p, DocNode::parser(), and DocParserContext::relPath.
DocDiaFile() [2/2]
DocDiaFile::DocDiaFile (DocParser * parser, DocNodeVariant * parent, const QCString & name, const QCString & context, const QCString & srcFile, int srcLine)
Member Function Documentation
parse() [1/2]
bool DocDiaFile::parse (DocNodeVariant * thisVariant)
Definition at line 1095 of file docnode.cpp.
{
  bool ok = false;
  parser()->defaultHandleTitleAndSize(CMD_DIAFILE,thisVariant,children(),p->width,p->height);
  bool ambig;
  FileDef *fd = findFileDef(Doxygen::diaFileNameLinkedMap,p->name,ambig);
  if (fd==0 && !p->name.endsWith(".dia")) // try with .dia extension as well
  {
    fd = findFileDef(Doxygen::diaFileNameLinkedMap,p->name+".dia",ambig);
  }
  if (fd)
  {
    p->file = fd->absFilePath();
    ok = true;
    if (ambig)
    {
      warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"included dia file name %s is ambiguous.\n"
           "Possible candidates:\n%s",qPrint(p->name),
           qPrint(showFileDefMatches(Doxygen::diaFileNameLinkedMap,p->name))
          );
    }
  }
  else
  {
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"included dia file %s is not found "
           "in any of the paths specified via DIAFILE_DIRS!",qPrint(p->name));
  }
  return ok;
}
References FileDef::absFilePath(), DocCompoundNode::children(), CMD_DIAFILE, DocDiagramFileBase::context(), DocParser::defaultHandleTitleAndSize(), Doxygen::diaFileNameLinkedMap, findFileDef(), DocDiagramFileBase::p, DocNode::parser(), qPrint(), showFileDefMatches(), and warn_doc_error().
parse() [2/2]
bool DocDiaFile::parse (DocNodeVariant *)
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docnode.h
doxygen/src/docnode.h
doxygen/build/doxygen/src/docnode.cpp
doxygen/src/docnode.cpp