TemplateNodeOpenSubIndex Class Reference
Class representing an 'opensubindex' tag in a template.
Public Member Functions
TemplateNodeOpenSubIndex (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void render (TextStream &, TemplateContext *c)
TemplateNodeOpenSubIndex (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void render (TextStream &, TemplateContext *c)
Private Attributes
QCString m_name
Additional Inherited Members
Detailed Description
Class representing an 'opensubindex' tag in a template.
Definition at line 4108 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeOpenSubIndex() [1/2]
TemplateNodeOpenSubIndex::TemplateNodeOpenSubIndex (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 4111 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeOpenSubIndex>(parser,parent,line)
    {
      TRACE(("{TemplateNodeOpenSubIndex(%s)\n",qPrint(data)));
      m_name = data.stripWhiteSpace();
      if (m_name.isEmpty())
      {
        parser->warn(parser->templateName(),line,"Missing argument for opensubindex tag");
      }
      else if (m_name.find(' ')!=-1)
      {
        parser->warn(parser->templateName(),line,"Expected single argument for opensubindex tag got '%s'",qPrint(data));
        m_name="";
      }
      TRACE(("}TemplateNodeOpenSubIndex(%s)\n",qPrint(data)));
    }
References data, QCString::find(), QCString::isEmpty(), m_name, qPrint(), TemplateParser::templateName(), TRACE, and TemplateParser::warn().
TemplateNodeOpenSubIndex() [2/2]
TemplateNodeOpenSubIndex::TemplateNodeOpenSubIndex (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 4111 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeOpenSubIndex>(parser,parent,line)
    {
      TRACE(("{TemplateNodeOpenSubIndex(%s)\n",qPrint(data)));
      m_name = data.stripWhiteSpace();
      if (m_name.isEmpty())
      {
        parser->warn(parser->templateName(),line,"Missing argument for opensubindex tag");
      }
      else if (m_name.find(' ')!=-1)
      {
        parser->warn(parser->templateName(),line,"Expected single argument for opensubindex tag got '%s'",qPrint(data));
        m_name="";
      }
      TRACE(("}TemplateNodeOpenSubIndex(%s)\n",qPrint(data)));
    }
References data, QCString::find(), QCString::isEmpty(), m_name, qPrint(), TemplateParser::templateName(), TRACE, and TemplateParser::warn().
Member Function Documentation
render() [1/2]
void TemplateNodeOpenSubIndex::render (TextStream & , TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 4127 of file template.cpp.
    {
      TemplateContextImpl *ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      if (!m_name.isEmpty())
      {
        ci->setLocation(m_templateName,m_line);
        ci->openSubIndex(m_name);
      }
    }
References c, QCString::isEmpty(), TemplateNodeCreator< TemplateNodeOpenSubIndex >::m_line, m_name, TemplateNodeCreator< TemplateNodeOpenSubIndex >::m_templateName, TemplateContextImpl::openSubIndex(), and TemplateContextImpl::setLocation().
render() [2/2]
void TemplateNodeOpenSubIndex::render (TextStream & , TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 4127 of file template.cpp.
    {
      TemplateContextImpl *ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      if (!m_name.isEmpty())
      {
        ci->setLocation(m_templateName,m_line);
        ci->openSubIndex(m_name);
      }
    }
References c, QCString::isEmpty(), TemplateNodeCreator< TemplateNodeOpenSubIndex >::m_line, m_name, TemplateNodeCreator< TemplateNodeOpenSubIndex >::m_templateName, TemplateContextImpl::openSubIndex(), and TemplateContextImpl::setLocation().
Member Data Documentation
m_name
QCString TemplateNodeOpenSubIndex::m_name [private]
Definition at line 4138 of file template.cpp.
Referenced by render(), and TemplateNodeOpenSubIndex().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp