ReaderStream Class Reference
#include <JavaCC.h>
Public Member Functions
virtual size_t read (JAVACC_CHAR_TYPE *buffer, int offset, size_t len)
virtual bool endOfInput ()
virtual ~ReaderStream ()
virtual size_t read (JAVACC_CHAR_TYPE *buffer, int offset, size_t len)
virtual bool endOfInput ()
virtual ~ReaderStream ()
Detailed Description
Definition at line 27 of file JavaCC.h.
Constructor & Destructor Documentation
 ReaderStream() [1/2]
virtual ReaderStream::~ReaderStream () [inline], [virtual]
Definition at line 32 of file JavaCC.h.
{}
 ReaderStream() [2/2]
virtual ReaderStream::~ReaderStream () [inline], [virtual]
Definition at line 32 of file JavaCC.h.
{}
Member Function Documentation
endOfInput() [1/2]
virtual bool ReaderStream::endOfInput () [inline], [virtual]
Reimplemented in anonymous_namespace{CharStream.cc}::StringReaderStream, and anonymous_namespace{CharStream.cc}::StringReaderStream.
Definition at line 31 of file JavaCC.h.
{ return true; }
Referenced by vhdl::parser::CharStream::endOfInput().
endOfInput() [2/2]
virtual bool ReaderStream::endOfInput () [inline], [virtual]
Reimplemented in anonymous_namespace{CharStream.cc}::StringReaderStream, and anonymous_namespace{CharStream.cc}::StringReaderStream.
Definition at line 31 of file JavaCC.h.
{ return true; }
read() [1/2]
virtual size_t ReaderStream::read (JAVACC_CHAR_TYPE * buffer, int offset, size_t len) [inline], [virtual]
Reimplemented in anonymous_namespace{CharStream.cc}::StringReaderStream, and anonymous_namespace{CharStream.cc}::StringReaderStream.
Definition at line 30 of file JavaCC.h.
{ return 0; }
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), vhdl::parser::CharStream::FillBuff(), doxmlparser.compound.memberdefType::get_read(), doxmlparser.compound.memberdefType::hasContent_(), and doxmlparser.compound.memberdefType::set_read().
read() [2/2]
virtual size_t ReaderStream::read (JAVACC_CHAR_TYPE * buffer, int offset, size_t len) [inline], [virtual]
Reimplemented in anonymous_namespace{CharStream.cc}::StringReaderStream, and anonymous_namespace{CharStream.cc}::StringReaderStream.
Definition at line 30 of file JavaCC.h.
{ return 0; }
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_read(), doxmlparser.compound.memberdefType::hasContent_(), and doxmlparser.compound.memberdefType::set_read().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/vhdlparser/JavaCC.h
doxygen/vhdlparser/JavaCC.h