FilterHex Class Reference
The implementation of the `upper` filter.
Static Public Member Functions
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &)
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &)
Detailed Description
The implementation of the `upper` filter.
Definition at line 1523 of file template.cpp.
Member Function Documentation
apply() [1/2]
static TemplateVariant FilterHex::apply (const TemplateVariant & v, const TemplateVariant &) [inline], [static]
Definition at line 1526 of file template.cpp.
    {
      if (v.isValid())
      {
        return QCString().sprintf("%x",v.toInt());
      }
      return v;
    }
References TemplateVariant::isValid(), QCString::sprintf(), and TemplateVariant::toInt().
apply() [2/2]
static TemplateVariant FilterHex::apply (const TemplateVariant & v, const TemplateVariant &) [inline], [static]
Definition at line 1526 of file template.cpp.
    {
      if (v.isValid())
      {
        return QCString().sprintf("%x",v.toInt());
      }
      return v;
    }
References TemplateVariant::isValid(), QCString::sprintf(), and TemplateVariant::toInt().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp