TemplateNodeInclude Class Reference
Class representing an 'include' tag in a template.
Public Member Functions
TemplateNodeInclude (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void render (TextStream &ts, TemplateContext *c)
TemplateNodeInclude (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void render (TextStream &ts, TemplateContext *c)
Private Attributes
ExprAstPtr m_includeExpr
Additional Inherited Members
Detailed Description
Class representing an 'include' tag in a template.
Definition at line 3753 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeInclude() [1/2]
TemplateNodeInclude::TemplateNodeInclude (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 3756 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeInclude>(parser,parent,line)
    {
      TRACE(("TemplateNodeInclude(%s)\n",qPrint(data)));
      ExpressionParser ep(parser,line);
      if (data.isEmpty())
      {
        parser->warn(m_templateName,line,"include tag is missing template file argument");
      }
      m_includeExpr = ep.parse(data);
    }
References data, m_includeExpr, TemplateNodeCreator< TemplateNodeInclude >::m_templateName, ExpressionParser::parse(), qPrint(), TRACE, and TemplateParser::warn().
TemplateNodeInclude() [2/2]
TemplateNodeInclude::TemplateNodeInclude (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 3756 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeInclude>(parser,parent,line)
    {
      TRACE(("TemplateNodeInclude(%s)\n",qPrint(data)));
      ExpressionParser ep(parser,line);
      if (data.isEmpty())
      {
        parser->warn(m_templateName,line,"include tag is missing template file argument");
      }
      m_includeExpr = ep.parse(data);
    }
References data, m_includeExpr, TemplateNodeCreator< TemplateNodeInclude >::m_templateName, ExpressionParser::parse(), qPrint(), TRACE, and TemplateParser::warn().
Member Function Documentation
render() [1/2]
void TemplateNodeInclude::render (TextStream & ts, TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 3767 of file template.cpp.
    {
      TemplateContextImpl* ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      if (m_includeExpr)
      {
        QCString includeFile = m_includeExpr->resolve(c).toString();
        if (includeFile.isEmpty())
        {
          ci->warn(m_templateName,m_line,"invalid parameter for include command\n");
        }
        else
        {
          TemplateImpl *t = getTemplate();
          if (t)
          {
            Template *it = t->engine()->loadByName(includeFile,m_line);
            TemplateImpl *incTemplate = it ? dynamic_cast<TemplateImpl*>(it) : 0;
            if (incTemplate)
            {
              incTemplate->render(ts,c);
            }
            else
            {
              ci->warn(m_templateName,m_line,"failed to load template '%s' for include",qPrint(includeFile));
            }
            t->engine()->unload(it);
          }
        }
      }
    }
References c, TemplateImpl::engine(), TemplateNodeCreator< TemplateNodeInclude >::getTemplate(), QCString::isEmpty(), TemplateEngine::loadByName(), m_includeExpr, TemplateNodeCreator< TemplateNodeInclude >::m_line, TemplateNodeCreator< TemplateNodeInclude >::m_templateName, qPrint(), TemplateImpl::render(), TemplateContextImpl::setLocation(), TemplateEngine::unload(), and TemplateContextImpl::warn().
render() [2/2]
void TemplateNodeInclude::render (TextStream & ts, TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 3767 of file template.cpp.
    {
      TemplateContextImpl* ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      if (m_includeExpr)
      {
        QCString includeFile = m_includeExpr->resolve(c).toString();
        if (includeFile.isEmpty())
        {
          ci->warn(m_templateName,m_line,"invalid parameter for include command\n");
        }
        else
        {
          TemplateImpl *t = getTemplate();
          if (t)
          {
            Template *it = t->engine()->loadByName(includeFile,m_line);
            TemplateImpl *incTemplate = it ? dynamic_cast<TemplateImpl*>(it) : 0;
            if (incTemplate)
            {
              incTemplate->render(ts,c);
            }
            else
            {
              ci->warn(m_templateName,m_line,"failed to load template '%s' for include",qPrint(includeFile));
            }
            t->engine()->unload(it);
          }
        }
      }
    }
References c, TemplateImpl::engine(), TemplateNodeCreator< TemplateNodeInclude >::getTemplate(), QCString::isEmpty(), TemplateEngine::loadByName(), m_includeExpr, TemplateNodeCreator< TemplateNodeInclude >::m_line, TemplateNodeCreator< TemplateNodeInclude >::m_templateName, qPrint(), TemplateImpl::render(), TemplateContextImpl::setLocation(), TemplateEngine::unload(), and TemplateContextImpl::warn().
Member Data Documentation
m_includeExpr
ExprAstPtr TemplateNodeInclude::m_includeExpr [private]
Definition at line 3801 of file template.cpp.
Referenced by render(), and TemplateNodeInclude().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp