SearchIndicesContext::Private Class Reference
Public Member Functions
Private ()
Private ()
Additional Inherited Members
Detailed Description
Definition at line 8814 of file context.cpp.
Constructor & Destructor Documentation
Private() [1/2]
SearchIndicesContext::Private::Private () [inline]
Definition at line 8817 of file context.cpp.
    {
      for (const auto &si : getSearchIndices())
      {
        append(SearchIndexContext::alloc(si));
      }
    }
References SearchIndexContext::alloc(), GenericNodeListContext::append(), and getSearchIndices().
Private() [2/2]
SearchIndicesContext::Private::Private () [inline]
Definition at line 8817 of file context.cpp.
    {
      for (const auto &si : getSearchIndices())
      {
        append(SearchIndexContext::alloc(si));
      }
    }
References SearchIndexContext::alloc(), and getSearchIndices().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp