DirContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const QCString &name) const
virtual StringVector fields () const
DirContext (const DirDef *)
virtual ~DirContext ()
virtual TemplateVariant get (const QCString &name) const
virtual StringVector fields () const
DirContext (const DirDef *)
virtual ~DirContext ()
Static Public Member Functions
static TemplateStructIntfPtr alloc (const DirDef *dd)
static TemplateStructIntfPtr alloc (const DirDef *dd)
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Definition at line 276 of file context.h.
Constructor & Destructor Documentation
DirContext() [1/2]
DirContext::DirContext (const DirDef * fd)
Definition at line 3248 of file context.cpp.
                                       : p(std::make_unique<Private>(fd))
{
}
 DirContext() [1/2]
DirContext::~DirContext () [virtual]
Definition at line 3252 of file context.cpp.
{
}
DirContext() [2/2]
DirContext::DirContext (const DirDef *)
 DirContext() [2/2]
virtual DirContext::~DirContext () [virtual]
Member Function Documentation
alloc() [1/2]
static TemplateStructIntfPtr DirContext::alloc (const DirDef * dd) [inline], [static]
Definition at line 279 of file context.h.
    { return std::static_pointer_cast<TemplateStructIntf>(std::make_shared<DirContext>(dd)); }
Referenced by NestingNodeContext::Private::createDir(), DirContext::Private::createDirs(), ModuleContext::Private::createDirs(), and DirListContext::Private::Private().
alloc() [2/2]
static TemplateStructIntfPtr DirContext::alloc (const DirDef * dd) [inline], [static]
Definition at line 279 of file context.h.
    { return std::static_pointer_cast<TemplateStructIntf>(std::make_shared<DirContext>(dd)); }
fields() [1/2]
StringVector DirContext::fields () const [virtual]
Return the list of fields.
Implements TemplateStructIntf.
Definition at line 3261 of file context.cpp.
{
  return p->fields();
}
References p.
fields() [2/2]
virtual StringVector DirContext::fields () const [virtual]
Return the list of fields.
Implements TemplateStructIntf.
get() [1/2]
TemplateVariant DirContext::get (const QCString & name) const [virtual]
Gets the value for a field name.
Parameters
 in name The name of the field.
Implements TemplateStructIntf.
Definition at line 3256 of file context.cpp.
{
  return p->get(n);
}
References n, and p.
get() [2/2]
virtual TemplateVariant DirContext::get (const QCString & name) const [virtual]
Gets the value for a field name.
Parameters
 in name The name of the field.
Implements TemplateStructIntf.
Member Data Documentation
p
std::unique_ptr< Private > DirContext::p [private]
Definition at line 291 of file context.h.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.h
doxygen/src/context.h
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp