DocSecRefList Class Reference
#include <docnode.h>
Public Member Functions
DocSecRefList (DocParser *parser, DocNodeVariant *parent)
void parse (DocNodeVariant *)
DocSecRefList (DocParser *parser, DocNodeVariant *parent)
void parse (DocNodeVariant *)
Additional Inherited Members
Detailed Description
Node representing a list of section references
Definition at line 911 of file docnode.h.
Constructor & Destructor Documentation
DocSecRefList() [1/2]
DocSecRefList::DocSecRefList (DocParser * parser, DocNodeVariant * parent) [inline]
Definition at line 914 of file docnode.h.
: DocCompoundNode(parser,parent) {}
DocSecRefList() [2/2]
DocSecRefList::DocSecRefList (DocParser * parser, DocNodeVariant * parent) [inline]
Definition at line 914 of file docnode.h.
: DocCompoundNode(parser,parent) {}
Member Function Documentation
parse() [1/2]
void DocSecRefList::parse (DocNodeVariant * thisVariant)
Definition at line 597 of file docnode.cpp.
{
  DBG(("DocSecRefList::parse() start\n"));
  auto ns = AutoNodeStack(parser(),thisVariant);
  int tok=parser()->tokenizer.lex();
  // skip white space
  while (tok==TK_WHITESPACE || tok==TK_NEWPARA) tok=parser()->tokenizer.lex();
  // handle items
  while (tok)
  {
    if (tok==TK_COMMAND_AT || tok == TK_COMMAND_BS)
    {
      const char *cmd_start = (tok==TK_COMMAND_AT ? "@" : "\\");
      switch (Mappers::cmdMapper->map(parser()->context.token->name))
      {
        case CMD_SECREFITEM:
          {
            tok=parser()->tokenizer.lex();
            if (tok!=TK_WHITESPACE)
            {
              warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"expected whitespace after \\refitem command");
              break;
            }
            tok=parser()->tokenizer.lex();
            if (tok!=TK_WORD && tok!=TK_LNKWORD)
            {
              warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"unexpected token %s as the argument of \\refitem",
                  DocTokenizer::tokToString(tok));
              break;
            }
            auto vDocSecRefItem = children().append<DocSecRefItem>(parser(),thisVariant,parser()->context.token->name);
            children().get_last<DocSecRefItem>()->parse(vDocSecRefItem);
          }
          break;
        case CMD_ENDSECREFLIST:
          goto endsecreflist;
        default:
          warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"Illegal command %s as part of a \\secreflist",
              qPrint(cmd_start + parser()->context.token->name));
          goto endsecreflist;
      }
    }
    else if (tok==TK_WHITESPACE)
    {
      // ignore whitespace
    }
    else
    {
      warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"Unexpected token %s inside section reference list",
          DocTokenizer::tokToString(tok));
      goto endsecreflist;
    }
    tok=parser()->tokenizer.lex();
  }
endsecreflist:
  DBG(("DocSecRefList::parse() end\n"));
}
References DocNodeList::append(), DocCompoundNode::children(), CMD_ENDSECREFLIST, CMD_SECREFITEM, Mappers::cmdMapper, DocParser::context, DBG, DocNodeList::get_last(), DocTokenizer::lex(), TokenInfo::name, parse(), DocNode::parser(), qPrint(), TK_COMMAND_AT, TK_COMMAND_BS, TK_LNKWORD, TK_NEWPARA, TK_WHITESPACE, TK_WORD, DocParserContext::token, DocParser::tokenizer, DocTokenizer::tokToString(), and warn_doc_error().
Referenced by parse().
parse() [2/2]
void DocSecRefList::parse (DocNodeVariant *)
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docnode.h
doxygen/src/docnode.h
doxygen/build/doxygen/src/docnode.cpp
doxygen/src/docnode.cpp