FilterLength Class Reference
The implementation of the `length` filter.
Static Public Member Functions
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &)
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &)
Detailed Description
The implementation of the `length` filter.
Definition at line 964 of file template.cpp.
Member Function Documentation
apply() [1/2]
static TemplateVariant FilterLength::apply (const TemplateVariant & v, const TemplateVariant &) [inline], [static]
Definition at line 967 of file template.cpp.
    {
      if (!v.isValid())
      {
        return TemplateVariant();
      }
      if (v.isList())
      {
        return TemplateVariant(v.toList()->count());
      }
      else if (v.isString())
      {
        return TemplateVariant(v.toString().length());
      }
      else
      {
        return TemplateVariant();
      }
    }
References TemplateVariant::isList(), TemplateVariant::isString(), TemplateVariant::isValid(), QCString::length(), TemplateVariant::toList(), and TemplateVariant::toString().
apply() [2/2]
static TemplateVariant FilterLength::apply (const TemplateVariant & v, const TemplateVariant &) [inline], [static]
Definition at line 967 of file template.cpp.
    {
      if (!v.isValid())
      {
        return TemplateVariant();
      }
      if (v.isList())
      {
        return TemplateVariant(v.toList()->count());
      }
      else if (v.isString())
      {
        return TemplateVariant(v.toString().length());
      }
      else
      {
        return TemplateVariant();
      }
    }
References TemplateVariant::isList(), TemplateVariant::isString(), TemplateVariant::isValid(), QCString::length(), TemplateVariant::toList(), and TemplateVariant::toString().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp