TranslatorJapanese Class Reference
#include <translator_jp.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString latexFontenc ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual bool needsPunctuation ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool, bool)
virtual QCString trFile (bool, bool)
virtual QCString trNamespace (bool, bool)
virtual QCString trGroup (bool, bool)
virtual QCString trPage (bool, bool)
virtual QCString trMember (bool, bool)
virtual QCString trGlobal (bool, bool)
virtual QCString trAuthor (bool, bool)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool, bool)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool, bool)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool)
virtual QCString trType (bool, bool)
virtual QCString trSubprogram (bool, bool)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool)
virtual QCString trSingletonGeneratedFromFiles (bool)
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString latexFontenc ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual bool needsPunctuation ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool, bool)
virtual QCString trFile (bool, bool)
virtual QCString trNamespace (bool, bool)
virtual QCString trGroup (bool, bool)
virtual QCString trPage (bool, bool)
virtual QCString trMember (bool, bool)
virtual QCString trGlobal (bool, bool)
virtual QCString trAuthor (bool, bool)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool, bool)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool, bool)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool)
virtual QCString trType (bool, bool)
virtual QCString trSubprogram (bool, bool)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool)
virtual QCString trSingletonGeneratedFromFiles (bool)
Additional Inherited Members
Detailed Description
Definition at line 72 of file translator_jp.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorJapanese::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 86 of file translator_jp.h.
    {
      return "0x411 Japanese";
    }
getLanguageString() [2/2]
virtual QCString TranslatorJapanese::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 86 of file translator_jp.h.
    {
      return "0x411 Japanese";
    }
idLanguage() [1/2]
virtual QCString TranslatorJapanese::idLanguage () [inline], [virtual]
Implements Translator.
Definition at line 75 of file translator_jp.h.
    { return "japanese"; }
idLanguage() [2/2]
virtual QCString TranslatorJapanese::idLanguage () [inline], [virtual]
Implements Translator.
Definition at line 75 of file translator_jp.h.
    { return "japanese"; }
latexDocumentPost() [1/2]
virtual QCString TranslatorJapanese::latexDocumentPost () [inline], [virtual]
Sets the commands to be inserted directly before the \\end{document} in the LaTeX document.
Reimplemented from Translator.
Definition at line 98 of file translator_jp.h.
    {
      return "\\end{CJK}\n";
    }
latexDocumentPost() [2/2]
virtual QCString TranslatorJapanese::latexDocumentPost () [inline], [virtual]
Sets the commands to be inserted directly before the \\end{document} in the LaTeX document.
Reimplemented from Translator.
Definition at line 98 of file translator_jp.h.
    {
      return "\\end{CJK}\n";
    }
latexDocumentPre() [1/2]
virtual QCString TranslatorJapanese::latexDocumentPre () [inline], [virtual]
Sets the commands to be inserted directly after the \\begin{document} in the LaTeX document.
Reimplemented from Translator.
Definition at line 94 of file translator_jp.h.
    {
      return "\\begin{CJK}{UTF8}{min}\n";
    }
latexDocumentPre() [2/2]
virtual QCString TranslatorJapanese::latexDocumentPre () [inline], [virtual]
Sets the commands to be inserted directly after the \\begin{document} in the LaTeX document.
Reimplemented from Translator.
Definition at line 94 of file translator_jp.h.
    {
      return "\\begin{CJK}{UTF8}{min}\n";
    }
latexFontenc() [1/2]
virtual QCString TranslatorJapanese::latexFontenc () [inline], [virtual]
Sets the LaTeX font encoding to be used. The default is set to T1, in case another font encoding has to be used this can be specified with this routine. In case no font encoding is required the empty string can be returned.
Reimplemented from Translator.
Definition at line 90 of file translator_jp.h.
    {
      return "";
    }
latexFontenc() [2/2]
virtual QCString TranslatorJapanese::latexFontenc () [inline], [virtual]
Sets the LaTeX font encoding to be used. The default is set to T1, in case another font encoding has to be used this can be specified with this routine. In case no font encoding is required the empty string can be returned.
Reimplemented from Translator.
Definition at line 90 of file translator_jp.h.
    {
      return "";
    }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorJapanese::latexLanguageSupportCommand () [inline], [virtual]
Implements Translator.
Definition at line 78 of file translator_jp.h.
    {
      return "\\usepackage{CJKutf8}\n";
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorJapanese::latexLanguageSupportCommand () [inline], [virtual]
Implements Translator.
Definition at line 78 of file translator_jp.h.
    {
      return "\\usepackage{CJKutf8}\n";
    }
needsPunctuation() [1/2]
virtual bool TranslatorJapanese::needsPunctuation () [inline], [virtual]
add punctuation at the end of a brief description when needed and supported by the language
Reimplemented from Translator.
Definition at line 102 of file translator_jp.h.
    {
      return false;
    }
needsPunctuation() [2/2]
virtual bool TranslatorJapanese::needsPunctuation () [inline], [virtual]
add punctuation at the end of a brief description when needed and supported by the language
Reimplemented from Translator.
Definition at line 102 of file translator_jp.h.
    {
      return false;
    }
trAdditionalInheritedMembers() [1/2]
virtual QCString TranslatorJapanese::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1886 of file translator_jp.h.
    { return ""; }
trAdditionalInheritedMembers() [2/2]
virtual QCString TranslatorJapanese::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1886 of file translator_jp.h.
    { return ""; }
trAll() [1/2]
virtual QCString TranslatorJapanese::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1415 of file translator_jp.h.
    {
      return "";
    }
trAll() [2/2]
virtual QCString TranslatorJapanese::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1415 of file translator_jp.h.
    {
      return "";
    }
trAndMore() [1/2]
virtual QCString TranslatorJapanese::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1866 of file translator_jp.h.
    { return " "+number+" "; }
trAndMore() [2/2]
virtual QCString TranslatorJapanese::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1866 of file translator_jp.h.
    { return " "+number+" "; }
trAttention() [1/2]
virtual QCString TranslatorJapanese::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 999 of file translator_jp.h.
    {
      return "";
    }
trAttention() [2/2]
virtual QCString TranslatorJapanese::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 999 of file translator_jp.h.
    {
      return "";
    }
trAuthor() [1/2]
virtual QCString TranslatorJapanese::trAuthor (bool , bool) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1288 of file translator_jp.h.
    {
      return "";
    }
trAuthor() [2/2]
virtual QCString TranslatorJapanese::trAuthor (bool , bool) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1288 of file translator_jp.h.
    {
      return "";
    }
trBug() [1/2]
virtual QCString TranslatorJapanese::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1160 of file translator_jp.h.
    {
      return "";
    }
trBug() [2/2]
virtual QCString TranslatorJapanese::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1160 of file translator_jp.h.
    {
      return "";
    }
trBugList() [1/2]
virtual QCString TranslatorJapanese::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1165 of file translator_jp.h.
    {
      return "";
    }
trBugList() [2/2]
virtual QCString TranslatorJapanese::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1165 of file translator_jp.h.
    {
      return "";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorJapanese::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1534 of file translator_jp.h.
    {
      return ":";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorJapanese::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1534 of file translator_jp.h.
    {
      return ":";
    }
trCallGraph() [1/2]
virtual QCString TranslatorJapanese::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1420 of file translator_jp.h.
    {
      return ":";
    }
trCallGraph() [2/2]
virtual QCString TranslatorJapanese::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1420 of file translator_jp.h.
    {
      return ":";
    }
trCiteReferences() [1/2]
virtual QCString TranslatorJapanese::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1842 of file translator_jp.h.
    { return ""; }
trCiteReferences() [2/2]
virtual QCString TranslatorJapanese::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1842 of file translator_jp.h.
    { return ""; }
trClass() [1/2]
virtual QCString TranslatorJapanese::trClass (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1223 of file translator_jp.h.
    {
      return "";
    }
trClass() [2/2]
virtual QCString TranslatorJapanese::trClass (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1223 of file translator_jp.h.
    {
      return "";
    }
trClassDiagram() [1/2]
virtual QCString TranslatorJapanese::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 552 of file translator_jp.h.
    {
      return clName+" ";
    }
trClassDiagram() [2/2]
virtual QCString TranslatorJapanese::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 552 of file translator_jp.h.
    {
      return clName+" ";
    }
trClassDocumentation() [1/2]
virtual QCString TranslatorJapanese::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 429 of file translator_jp.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorJapanese::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 429 of file translator_jp.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorJapanese::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1121 of file translator_jp.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
    {
      return "";
    }
      else
    {
      return "";
    }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorJapanese::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1121 of file translator_jp.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
    {
      return "";
    }
      else
    {
      return "";
    }
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorJapanese::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 206 of file translator_jp.h.
    { return ""; }
trClassHierarchy() [2/2]
virtual QCString TranslatorJapanese::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 206 of file translator_jp.h.
    { return ""; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorJapanese::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 264 of file translator_jp.h.
    {
      return "";
    }
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorJapanese::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 264 of file translator_jp.h.
    {
      return "";
    }
trClassMethods() [1/2]
virtual QCString TranslatorJapanese::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1925 of file translator_jp.h.
    {
      return "";
    }
trClassMethods() [2/2]
virtual QCString TranslatorJapanese::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1925 of file translator_jp.h.
    {
      return "";
    }
trCode() [1/2]
virtual QCString TranslatorJapanese::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 900 of file translator_jp.h.
    {
      return "";
    }
trCode() [2/2]
virtual QCString TranslatorJapanese::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 900 of file translator_jp.h.
    {
      return "";
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorJapanese::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 855 of file translator_jp.h.
    {
      return clName+" ";
    }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorJapanese::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 855 of file translator_jp.h.
    {
      return clName+" ";
    }
trCompoundIndex() [1/2]
virtual QCString TranslatorJapanese::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 402 of file translator_jp.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorJapanese::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 402 of file translator_jp.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorJapanese::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1582 of file translator_jp.h.
    { return ""; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorJapanese::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1582 of file translator_jp.h.
    { return ""; }
trCompoundList() [1/2]
virtual QCString TranslatorJapanese::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 210 of file translator_jp.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorJapanese::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 210 of file translator_jp.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorJapanese::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 286 of file translator_jp.h.
    {
      /* */
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorJapanese::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 286 of file translator_jp.h.
    {
      /* */
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorJapanese::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1563 of file translator_jp.h.
    { return ":"; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorJapanese::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1563 of file translator_jp.h.
    { return ":"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorJapanese::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1555 of file translator_jp.h.
    { return ""; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorJapanese::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1555 of file translator_jp.h.
    { return ""; }
trCompoundMembers() [1/2]
virtual QCString TranslatorJapanese::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 227 of file translator_jp.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorJapanese::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 227 of file translator_jp.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorJapanese::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 300 of file translator_jp.h.
    {
      const bool forC = Config_getBool(OPTIMIZE_OUTPUT_FOR_C);
      QCString result;
      if (forC)
      {
        result = "";
      }
      if (extractAll)
      {
        result += "";
      }
      else
      {
        result += "";
      }
      if (forC)
      {
        result += "";
      }
      else
      {
        result += "";
      }
      if (!extractAll && !forC)
      {
        result += "";
      }
      result += "";
      if (!extractAll)
      {
        if (forC)
        {
          result+="";
        }
        else
        {
          result+="";
        }
      }
      else
      {
        if (forC)
        {
          result+="";
        }
        else
        {
          result+="";
        }
      }
      result += "";
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorJapanese::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 300 of file translator_jp.h.
    {
      const bool forC = Config_getBool(OPTIMIZE_OUTPUT_FOR_C);
      QCString result;
      if (forC)
      {
        result = "";
      }
      if (extractAll)
      {
        result += "";
      }
      else
      {
        result += "";
      }
      if (forC)
      {
        result += "";
      }
      else
      {
        result += "";
      }
      if (!extractAll && !forC)
      {
        result += "";
      }
      result += "";
      if (!extractAll)
      {
        if (forC)
        {
          result+="";
        }
        else
        {
          result+="";
        }
      }
      else
      {
        if (forC)
        {
          result+="";
        }
        else
        {
          result+="";
        }
      }
      result += "";
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorJapanese::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1567 of file translator_jp.h.
    {
      QCString result="";
      result+="";
      if (extractAll)
      {
          result+="";
      }
      result+="";
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorJapanese::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1567 of file translator_jp.h.
    {
      QCString result="";
      result+="";
      if (extractAll)
      {
          result+="";
      }
      result+="";
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorJapanese::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1559 of file translator_jp.h.
    { return ""; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorJapanese::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1559 of file translator_jp.h.
    { return ""; }
trCompoundReference() [1/2]
virtual QCString TranslatorJapanese::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 628 of file translator_jp.h.
    {
      QCString result=clName+" ";
      switch(compType)
      {
        case ClassDef::Class: result+=""; break;
        case ClassDef::Struct: result+=""; break;
        case ClassDef::Union: result+=""; break;
        case ClassDef::Interface: result+=""; break;
        case ClassDef::Protocol: result+=""; break;
        case ClassDef::Category: result+=""; break;
        case ClassDef::Exception: result+=""; break;
        default: break;
      }
      if (isTemplate) result+="";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorJapanese::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 628 of file translator_jp.h.
    {
      QCString result=clName+" ";
      switch(compType)
      {
        case ClassDef::Class: result+=""; break;
        case ClassDef::Struct: result+=""; break;
        case ClassDef::Union: result+=""; break;
        case ClassDef::Interface: result+=""; break;
        case ClassDef::Protocol: result+=""; break;
        case ClassDef::Category: result+=""; break;
        case ClassDef::Exception: result+=""; break;
        default: break;
      }
      if (isTemplate) result+="";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorJapanese::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1631 of file translator_jp.h.
    {
      QCString result="";
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+="TYPE "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      if (isTemplate) result += " ";
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorJapanese::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1631 of file translator_jp.h.
    {
      QCString result="";
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+="TYPE "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      if (isTemplate) result += " ";
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorJapanese::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 529 of file translator_jp.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorJapanese::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 529 of file translator_jp.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trConstantGroupReference() [1/2]
virtual QCString TranslatorJapanese::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1962 of file translator_jp.h.
    {
      QCString result=namespaceName;
      result+=" ";
      return result;
    }
trConstantGroupReference() [2/2]
virtual QCString TranslatorJapanese::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1962 of file translator_jp.h.
    {
      QCString result=namespaceName;
      result+=" ";
      return result;
    }
trConstantGroups() [1/2]
virtual QCString TranslatorJapanese::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1958 of file translator_jp.h.
    { return ""; }
trConstantGroups() [2/2]
virtual QCString TranslatorJapanese::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1958 of file translator_jp.h.
    { return ""; }
trConstructorDocumentation() [1/2]
virtual QCString TranslatorJapanese::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 865 of file translator_jp.h.
    {
      return "";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorJapanese::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 865 of file translator_jp.h.
    {
      return "";
    }
trCopyright() [1/2]
virtual QCString TranslatorJapanese::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1846 of file translator_jp.h.
    { return ""; }
trCopyright() [2/2]
virtual QCString TranslatorJapanese::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1846 of file translator_jp.h.
    { return ""; }
trDataTypes() [1/2]
virtual QCString TranslatorJapanese::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1607 of file translator_jp.h.
    { return ""; }
trDataTypes() [2/2]
virtual QCString TranslatorJapanese::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1607 of file translator_jp.h.
    { return ""; }
trDate() [1/2]
virtual QCString TranslatorJapanese::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 566 of file translator_jp.h.
    { return ""; }
trDate() [2/2]
virtual QCString TranslatorJapanese::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 566 of file translator_jp.h.
    { return ""; }
trDateTime() [1/2]
virtual QCString TranslatorJapanese::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1802 of file translator_jp.h.
    {
      static const char *days[] = { "", "", "", "", "", "", "" };
      QCString sdate;
      sdate.sprintf("%.4d%.2d%.2d(%s)",year,month,day,days[dayOfWeek-1]);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d%.2d%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDateTime() [2/2]
virtual QCString TranslatorJapanese::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1802 of file translator_jp.h.
    {
      static const char *days[] = { "", "", "", "", "", "", "" };
      QCString sdate;
      sdate.sprintf("%.4d%.2d%.2d(%s)",year,month,day,days[dayOfWeek-1]);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d%.2d%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDayOfWeek() [1/2]
virtual QCString TranslatorJapanese::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1817 of file translator_jp.h.
    {
      static const char *days_short[] = { "", "", "", "", "", "", "" };
      static const char *days_full[] = { "", "", "", "", "", "", "" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      return text;
    }
trDayOfWeek() [2/2]
virtual QCString TranslatorJapanese::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1817 of file translator_jp.h.
    {
      static const char *days_short[] = { "", "", "", "", "", "", "" };
      static const char *days_full[] = { "", "", "", "", "", "", "" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      return text;
    }
trDayPeriod() [1/2]
virtual QCString TranslatorJapanese::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1831 of file translator_jp.h.
    {
      static const char *dayPeriod[] = { "", "" };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorJapanese::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1831 of file translator_jp.h.
    {
      static const char *dayPeriod[] = { "", "" };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorJapanese::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 836 of file translator_jp.h.
    {
      return " @1 @0 ";
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorJapanese::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 836 of file translator_jp.h.
    {
      return " @1 @0 ";
    }
trDefinedIn() [1/2]
virtual QCString TranslatorJapanese::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 194 of file translator_jp.h.
    { return ": "; }
trDefinedIn() [2/2]
virtual QCString TranslatorJapanese::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 194 of file translator_jp.h.
    { return ": "; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorJapanese::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 840 of file translator_jp.h.
    {
      return " @0 ";
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorJapanese::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 840 of file translator_jp.h.
    {
      return " @0 ";
    }
trDefineDocumentation() [1/2]
virtual QCString TranslatorJapanese::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 499 of file translator_jp.h.
    { return ""; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorJapanese::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 499 of file translator_jp.h.
    { return ""; }
trDefines() [1/2]
virtual QCString TranslatorJapanese::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 464 of file translator_jp.h.
    { return ""; }
trDefines() [2/2]
virtual QCString TranslatorJapanese::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 464 of file translator_jp.h.
    { return ""; }
trDefineValue() [1/2]
virtual QCString TranslatorJapanese::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1149 of file translator_jp.h.
    {
      return ":";
    }
trDefineValue() [2/2]
virtual QCString TranslatorJapanese::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1149 of file translator_jp.h.
    {
      return ":";
    }
trDeprecated() [1/2]
virtual QCString TranslatorJapanese::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 849 of file translator_jp.h.
    {
      return "";
    }
trDeprecated() [2/2]
virtual QCString TranslatorJapanese::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 849 of file translator_jp.h.
    {
      return "";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorJapanese::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1342 of file translator_jp.h.
    {
      return "";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorJapanese::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1342 of file translator_jp.h.
    {
      return "";
    }
trDetailedDescription() [1/2]
virtual QCString TranslatorJapanese::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 116 of file translator_jp.h.
    { return ""; }
trDetailedDescription() [2/2]
virtual QCString TranslatorJapanese::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 116 of file translator_jp.h.
    { return ""; }
trDetailLevel() [1/2]
virtual QCString TranslatorJapanese::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1858 of file translator_jp.h.
    { return ""; }
trDetailLevel() [2/2]
virtual QCString TranslatorJapanese::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1858 of file translator_jp.h.
    { return ""; }
trDir() [1/2]
virtual QCString TranslatorJapanese::trDir (bool , bool) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1510 of file translator_jp.h.
    {
      return "";
    }
trDir() [2/2]
virtual QCString TranslatorJapanese::trDir (bool , bool) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1510 of file translator_jp.h.
    {
      return "";
    }
trDirDepGraph() [1/2]
virtual QCString TranslatorJapanese::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1850 of file translator_jp.h.
    { return QCString(name)+" "; }
References setup::name.
trDirDepGraph() [2/2]
virtual QCString TranslatorJapanese::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1850 of file translator_jp.h.
    { return QCString(name)+" "; }
References setup::name.
trDirDocumentation() [1/2]
virtual QCString TranslatorJapanese::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1492 of file translator_jp.h.
    { return ""; }
trDirDocumentation() [2/2]
virtual QCString TranslatorJapanese::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1492 of file translator_jp.h.
    { return ""; }
trDirectories() [1/2]
virtual QCString TranslatorJapanese::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1498 of file translator_jp.h.
    { return ""; }
trDirectories() [2/2]
virtual QCString TranslatorJapanese::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1498 of file translator_jp.h.
    { return ""; }
trDirIndex() [1/2]
virtual QCString TranslatorJapanese::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1486 of file translator_jp.h.
    { return ""; }
trDirIndex() [2/2]
virtual QCString TranslatorJapanese::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1486 of file translator_jp.h.
    { return ""; }
trDirReference() [1/2]
virtual QCString TranslatorJapanese::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1504 of file translator_jp.h.
    { QCString result=dirName; result+=" "; return result; }
trDirReference() [2/2]
virtual QCString TranslatorJapanese::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1504 of file translator_jp.h.
    { QCString result=dirName; result+=" "; return result; }
trDirRelation() [1/2]
virtual QCString TranslatorJapanese::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1741 of file translator_jp.h.
    {
      return QCString(name)+" ";
    }
References setup::name.
trDirRelation() [2/2]
virtual QCString TranslatorJapanese::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1741 of file translator_jp.h.
    {
      return QCString(name)+" ";
    }
References setup::name.
trDocumentation() [1/2]
virtual QCString TranslatorJapanese::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 384 of file translator_jp.h.
    { return ""; }
trDocumentation() [2/2]
virtual QCString TranslatorJapanese::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 384 of file translator_jp.h.
    { return ""; }
trEnumerations() [1/2]
virtual QCString TranslatorJapanese::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 476 of file translator_jp.h.
    { return ""; }
trEnumerations() [2/2]
virtual QCString TranslatorJapanese::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 476 of file translator_jp.h.
    { return ""; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorJapanese::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 511 of file translator_jp.h.
    { return ""; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorJapanese::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 511 of file translator_jp.h.
    { return ""; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorJapanese::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1542 of file translator_jp.h.
    { return ""; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorJapanese::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1542 of file translator_jp.h.
    { return ""; }
trEnumerationValues() [1/2]
virtual QCString TranslatorJapanese::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 494 of file translator_jp.h.
    { return ""; }
trEnumerationValues() [2/2]
virtual QCString TranslatorJapanese::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 494 of file translator_jp.h.
    { return ""; }
trEnumGeneratedFromFiles() [1/2]
virtual QCString TranslatorJapanese::trEnumGeneratedFromFiles (bool) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1870 of file translator_jp.h.
    {
      return ":";
    }
trEnumGeneratedFromFiles() [2/2]
virtual QCString TranslatorJapanese::trEnumGeneratedFromFiles (bool) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1870 of file translator_jp.h.
    {
      return ":";
    }
trEnumName() [1/2]
virtual QCString TranslatorJapanese::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 186 of file translator_jp.h.
    { return ""; }
trEnumName() [2/2]
virtual QCString TranslatorJapanese::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 186 of file translator_jp.h.
    { return ""; }
trEnumReference() [1/2]
virtual QCString TranslatorJapanese::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1876 of file translator_jp.h.
    { return QCString(" ")+name+" "; }
References setup::name.
trEnumReference() [2/2]
virtual QCString TranslatorJapanese::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1876 of file translator_jp.h.
    { return QCString(" ")+name+" "; }
References setup::name.
trEnumValue() [1/2]
virtual QCString TranslatorJapanese::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 190 of file translator_jp.h.
    { return ""; }
trEnumValue() [2/2]
virtual QCString TranslatorJapanese::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 190 of file translator_jp.h.
    { return ""; }
trEventDocumentation() [1/2]
virtual QCString TranslatorJapanese::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1359 of file translator_jp.h.
    {
      return "";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorJapanese::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1359 of file translator_jp.h.
    {
      return "";
    }
trEvents() [1/2]
virtual QCString TranslatorJapanese::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1354 of file translator_jp.h.
    {
      return "";
    }
trEvents() [2/2]
virtual QCString TranslatorJapanese::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1354 of file translator_jp.h.
    {
      return "";
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorJapanese::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 454 of file translator_jp.h.
    { return ""; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorJapanese::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 454 of file translator_jp.h.
    { return ""; }
trExamples() [1/2]
virtual QCString TranslatorJapanese::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 256 of file translator_jp.h.
    { return ""; }
trExamples() [2/2]
virtual QCString TranslatorJapanese::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 256 of file translator_jp.h.
    { return ""; }
trExamplesDescription() [1/2]
virtual QCString TranslatorJapanese::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 372 of file translator_jp.h.
    { return ""; }
trExamplesDescription() [2/2]
virtual QCString TranslatorJapanese::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 372 of file translator_jp.h.
    { return ""; }
trExceptions() [1/2]
virtual QCString TranslatorJapanese::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 582 of file translator_jp.h.
    { return ""; }
trExceptions() [2/2]
virtual QCString TranslatorJapanese::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 582 of file translator_jp.h.
    { return ""; }
trExtendsClass() [1/2]
virtual QCString TranslatorJapanese::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1917 of file translator_jp.h.
    {
      return "@0 ";
    }
trExtendsClass() [2/2]
virtual QCString TranslatorJapanese::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1917 of file translator_jp.h.
    {
      return "@0 ";
    }
trFile() [1/2]
virtual QCString TranslatorJapanese::trFile (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1232 of file translator_jp.h.
    {
      return "";
    }
trFile() [2/2]
virtual QCString TranslatorJapanese::trFile (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1232 of file translator_jp.h.
    {
      return "";
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorJapanese::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 448 of file translator_jp.h.
    { return ""; }
trFileDocumentation() [2/2]
virtual QCString TranslatorJapanese::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 448 of file translator_jp.h.
    { return ""; }
trFileIn() [1/2]
virtual QCString TranslatorJapanese::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1778 of file translator_jp.h.
    {
      return name+"";
    }
References setup::name.
trFileIn() [2/2]
virtual QCString TranslatorJapanese::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1778 of file translator_jp.h.
    {
      return name+"";
    }
References setup::name.
trFileIndex() [1/2]
virtual QCString TranslatorJapanese::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 417 of file translator_jp.h.
    { return ""; }
trFileIndex() [2/2]
virtual QCString TranslatorJapanese::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 417 of file translator_jp.h.
    { return ""; }
trFileList() [1/2]
virtual QCString TranslatorJapanese::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 223 of file translator_jp.h.
    { return ""; }
trFileList() [2/2]
virtual QCString TranslatorJapanese::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 223 of file translator_jp.h.
    { return ""; }
trFileListDescription() [1/2]
virtual QCString TranslatorJapanese::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 270 of file translator_jp.h.
    {
      /* */
      /* extractAll EXTRACT_ALL
         
         
      */
      if (extractAll)
      {
        return "";
      }
      return "";
    }
trFileListDescription() [2/2]
virtual QCString TranslatorJapanese::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 270 of file translator_jp.h.
    {
      /* */
      /* extractAll EXTRACT_ALL
         
         
      */
      if (extractAll)
      {
        return "";
      }
      return "";
    }
trFileMembers() [1/2]
virtual QCString TranslatorJapanese::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 240 of file translator_jp.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trFileMembers() [2/2]
virtual QCString TranslatorJapanese::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 240 of file translator_jp.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
virtual QCString TranslatorJapanese::trFileMembersDescription (bool) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 356 of file translator_jp.h.
    {
      QCString result;
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="";
      }
      else
      {
        result+="";
      }
      result+="";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorJapanese::trFileMembersDescription (bool) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 356 of file translator_jp.h.
    {
      QCString result;
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="";
      }
      else
      {
        result+="";
      }
      result+="";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorJapanese::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 649 of file translator_jp.h.
    {
      QCString result=fileName+" ";
      return result;
    }
trFileReference() [2/2]
virtual QCString TranslatorJapanese::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 649 of file translator_jp.h.
    {
      QCString result=fileName+" ";
      return result;
    }
trFriends() [1/2]
virtual QCString TranslatorJapanese::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 610 of file translator_jp.h.
    { return ""; }
trFriends() [2/2]
virtual QCString TranslatorJapanese::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 610 of file translator_jp.h.
    { return ""; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorJapanese::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 517 of file translator_jp.h.
    { return ""; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorJapanese::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 517 of file translator_jp.h.
    { return ""; }
trFunctions() [1/2]
virtual QCString TranslatorJapanese::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 482 of file translator_jp.h.
    { return ""; }
trFunctions() [2/2]
virtual QCString TranslatorJapanese::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 482 of file translator_jp.h.
    { return ""; }
trGeneratedAt() [1/2]
virtual QCString TranslatorJapanese::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 543 of file translator_jp.h.
    {
      QCString result = date+"";
      if (!projName.isEmpty()) result+=" - " + projName;
      result+=" / : ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorJapanese::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 543 of file translator_jp.h.
    {
      QCString result = date+"";
      if (!projName.isEmpty()) result+=" - " + projName;
      result+=" / : ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorJapanese::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 178 of file translator_jp.h.
    { QCString result = "Doxygen ";
      if (!s.isEmpty()) result=" "+s+"";
      result+="";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorJapanese::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 178 of file translator_jp.h.
    { QCString result = "Doxygen ";
      if (!s.isEmpty()) result=" "+s+"";
      result+="";
      return result;
    }
References s.
trGeneratedBy() [1/2]
virtual QCString TranslatorJapanese::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 586 of file translator_jp.h.
    { return ":"; }
trGeneratedBy() [2/2]
virtual QCString TranslatorJapanese::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 586 of file translator_jp.h.
    { return ":"; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorJapanese::trGeneratedFromFiles (ClassDef::CompoundType compType, bool) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 793 of file translator_jp.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="";
      switch(compType)
      {
        case ClassDef::Class: result+=""; break;
        case ClassDef::Struct: result+=""; break;
        case ClassDef::Union: result+=""; break;
        case ClassDef::Interface: result+=""; break;
        case ClassDef::Protocol: result+=""; break;
        case ClassDef::Category: result+=""; break;
        case ClassDef::Exception: result+=""; break;
        default: break;
      }
      result+=":";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorJapanese::trGeneratedFromFiles (ClassDef::CompoundType compType, bool) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 793 of file translator_jp.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="";
      switch(compType)
      {
        case ClassDef::Class: result+=""; break;
        case ClassDef::Struct: result+=""; break;
        case ClassDef::Union: result+=""; break;
        case ClassDef::Interface: result+=""; break;
        case ClassDef::Protocol: result+=""; break;
        case ClassDef::Category: result+=""; break;
        case ClassDef::Exception: result+=""; break;
        default: break;
      }
      result+=":";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorJapanese::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1692 of file translator_jp.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="";
      switch(compType)
      {
        case ClassDef::Class: result+=""; break;
        case ClassDef::Struct: result+=""; break;
        case ClassDef::Union: result+=""; break;
        case ClassDef::Interface: result+=""; break;
        case ClassDef::Protocol: result+=""; break;
        case ClassDef::Category: result+=""; break;
        case ClassDef::Exception: result+=""; break;
        default: break;
      }
      result+=":";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorJapanese::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1692 of file translator_jp.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="";
      switch(compType)
      {
        case ClassDef::Class: result+=""; break;
        case ClassDef::Struct: result+=""; break;
        case ClassDef::Union: result+=""; break;
        case ClassDef::Interface: result+=""; break;
        case ClassDef::Protocol: result+=""; break;
        case ClassDef::Category: result+=""; break;
        case ClassDef::Exception: result+=""; break;
        default: break;
      }
      result+=":";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorJapanese::trGlobal (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1277 of file translator_jp.h.
    {
      return "";
    }
trGlobal() [2/2]
virtual QCString TranslatorJapanese::trGlobal (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1277 of file translator_jp.h.
    {
      return "";
    }
trGlobalNamespace() [1/2]
virtual QCString TranslatorJapanese::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1753 of file translator_jp.h.
    {
      return "";
    }
trGlobalNamespace() [2/2]
virtual QCString TranslatorJapanese::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1753 of file translator_jp.h.
    {
      return "";
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorJapanese::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 875 of file translator_jp.h.
    {
      return "[]";
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorJapanese::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 875 of file translator_jp.h.
    {
      return "[]";
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorJapanese::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 908 of file translator_jp.h.
    {
      return "[]";
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorJapanese::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 908 of file translator_jp.h.
    {
      return "[]";
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorJapanese::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 870 of file translator_jp.h.
    {
      return "[]";
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorJapanese::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 870 of file translator_jp.h.
    {
      return "[]";
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorJapanese::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 912 of file translator_jp.h.
    {
      return "[]";
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorJapanese::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 912 of file translator_jp.h.
    {
      return "[]";
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorJapanese::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 904 of file translator_jp.h.
    {
      return "";
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorJapanese::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 904 of file translator_jp.h.
    {
      return "";
    }
trGroup() [1/2]
virtual QCString TranslatorJapanese::trGroup (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1250 of file translator_jp.h.
    {
      return "";
    }
trGroup() [2/2]
virtual QCString TranslatorJapanese::trGroup (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1250 of file translator_jp.h.
    {
      return "";
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorJapanese::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 396 of file translator_jp.h.
    { return ""; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorJapanese::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 396 of file translator_jp.h.
    { return ""; }
trImplementedFromList() [1/2]
virtual QCString TranslatorJapanese::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1311 of file translator_jp.h.
    {
      return trWriteList(numEntries)+"";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorJapanese::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1311 of file translator_jp.h.
    {
      return trWriteList(numEntries)+"";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorJapanese::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1319 of file translator_jp.h.
    {
      return trWriteList(numEntries)+"";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorJapanese::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1319 of file translator_jp.h.
    {
      return trWriteList(numEntries)+"";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorJapanese::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 1003 of file translator_jp.h.
    {
      return ":";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorJapanese::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 1003 of file translator_jp.h.
    {
      return ":";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorJapanese::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 860 of file translator_jp.h.
    {
    return fName+" :";
    }
trInclDepGraph() [2/2]
virtual QCString TranslatorJapanese::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 860 of file translator_jp.h.
    {
    return fName+" :";
    }
trIncludesFileIn() [1/2]
virtual QCString TranslatorJapanese::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1787 of file translator_jp.h.
    {
      return name+" include ";
    }
References setup::name.
trIncludesFileIn() [2/2]
virtual QCString TranslatorJapanese::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1787 of file translator_jp.h.
    {
      return name+" include ";
    }
References setup::name.
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorJapanese::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 171 of file translator_jp.h.
    { return " "; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorJapanese::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 171 of file translator_jp.h.
    { return " "; }
trInheritedByList() [1/2]
virtual QCString TranslatorJapanese::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 723 of file translator_jp.h.
    {
      return trWriteList(numEntries)+"";
    }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorJapanese::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 723 of file translator_jp.h.
    {
      return trWriteList(numEntries)+"";
    }
References trWriteList().
trInheritedFrom() [1/2]
virtual QCString TranslatorJapanese::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1880 of file translator_jp.h.
    { return QCString(" ")+what+" "+members; }
trInheritedFrom() [2/2]
virtual QCString TranslatorJapanese::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1880 of file translator_jp.h.
    { return QCString(" ")+what+" "+members; }
trInheritsList() [1/2]
virtual QCString TranslatorJapanese::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 715 of file translator_jp.h.
    {
      return trWriteList(numEntries)+"";
    }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorJapanese::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 715 of file translator_jp.h.
    {
      return trWriteList(numEntries)+"";
    }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorJapanese::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 895 of file translator_jp.h.
    {
      return ":";
    }
trInitialValue() [2/2]
virtual QCString TranslatorJapanese::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 895 of file translator_jp.h.
    {
      return ":";
    }
trInstanceMethods() [1/2]
virtual QCString TranslatorJapanese::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1933 of file translator_jp.h.
    {
      return "";
    }
trInstanceMethods() [2/2]
virtual QCString TranslatorJapanese::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1933 of file translator_jp.h.
    {
      return "";
    }
trInterfaces() [1/2]
virtual QCString TranslatorJapanese::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1950 of file translator_jp.h.
    { return ""; }
trInterfaces() [2/2]
virtual QCString TranslatorJapanese::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1950 of file translator_jp.h.
    { return ""; }
trInvariant() [1/2]
virtual QCString TranslatorJapanese::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 890 of file translator_jp.h.
    {
      return "";
    }
trInvariant() [2/2]
virtual QCString TranslatorJapanese::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 890 of file translator_jp.h.
    {
      return "";
    }
trISOLang() [1/2]
virtual QCString TranslatorJapanese::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 82 of file translator_jp.h.
    {
      return "ja";
    }
trISOLang() [2/2]
virtual QCString TranslatorJapanese::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 82 of file translator_jp.h.
    {
      return "ja";
    }
trLegend() [1/2]
virtual QCString TranslatorJapanese::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1080 of file translator_jp.h.
    {
      return "";
    }
trLegend() [2/2]
virtual QCString TranslatorJapanese::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1080 of file translator_jp.h.
    {
      return "";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorJapanese::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 1022 of file translator_jp.h.
    {
      return
        "Doxygen <p>\n"
        "\n"
        "\\code\n"
        "/*! */\n"
        "class Invisible { };\n\n"
        "/*! (Invisible) */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Doxygen */\n"
        "class Undocumented { };\n\n"
        "/*! */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! */\n"
        "class ProtectedBase { };\n\n"
        "/*! */\n"
        "class PrivateBase { };\n\n"
        "/*! Inherited */\n"
        "class Used { };\n\n"
        "/*! */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "\\c MAX_DOT_GRAPH_" /* doc/translator.py */
        "HEIGHT 200 "
        ""
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "\n"
        "<ul>\n"
        "<li></li>\n"
        "<li></li>\n"
        "<li></li>\n"
        "<li>"
        ""
        "</li>\n"
        "</ul>\n"
        "<p></p>\n"
        "<ul>\n"
        "<li></li>\n"
        "<li></li>\n"
        "<li></li>\n"
        "<li>"
      ""
      "</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorJapanese::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 1022 of file translator_jp.h.
    {
      return
        "Doxygen <p>\n"
        "\n"
        "\\code\n"
        "/*! */\n"
        "class Invisible { };\n\n"
        "/*! (Invisible) */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Doxygen */\n"
        "class Undocumented { };\n\n"
        "/*! */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! A template class */\n"
        "template<class T> class Templ { };\n\n"
        "/*! */\n"
        "class ProtectedBase { };\n\n"
        "/*! */\n"
        "class PrivateBase { };\n\n"
        "/*! Inherited */\n"
        "class Used { };\n\n"
        "/*! */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "\\c MAX_DOT_GRAPH_" /* doc/translator.py */
        "HEIGHT 200 "
        ""
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "\n"
        "<ul>\n"
        "<li></li>\n"
        "<li></li>\n"
        "<li></li>\n"
        "<li>"
        ""
        "</li>\n"
        "</ul>\n"
        "<p></p>\n"
        "<ul>\n"
        "<li></li>\n"
        "<li></li>\n"
        "<li></li>\n"
        "<li>"
      ""
      "</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorJapanese::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 1017 of file translator_jp.h.
    {
      return "";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorJapanese::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 1017 of file translator_jp.h.
    {
      return "";
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorJapanese::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 158 of file translator_jp.h.
    { return ""; }
trListOfAllMembers() [2/2]
virtual QCString TranslatorJapanese::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 158 of file translator_jp.h.
    { return ""; }
trLoading() [1/2]
virtual QCString TranslatorJapanese::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1747 of file translator_jp.h.
    {
      return "";
    }
trLoading() [2/2]
virtual QCString TranslatorJapanese::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1747 of file translator_jp.h.
    {
      return "";
    }
trMainPage() [1/2]
virtual QCString TranslatorJapanese::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 823 of file translator_jp.h.
    { return ""; }
trMainPage() [2/2]
virtual QCString TranslatorJapanese::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 823 of file translator_jp.h.
    { return ""; }
trMember() [1/2]
virtual QCString TranslatorJapanese::trMember (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1268 of file translator_jp.h.
    {
      return "";
    }
trMember() [2/2]
virtual QCString TranslatorJapanese::trMember (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1268 of file translator_jp.h.
    {
      return "";
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorJapanese::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 141 of file translator_jp.h.
    {
      if(Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorJapanese::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 141 of file translator_jp.h.
    {
      if(Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorJapanese::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 124 of file translator_jp.h.
    { return ""; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorJapanese::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 124 of file translator_jp.h.
    { return ""; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorJapanese::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 128 of file translator_jp.h.
    {
      if(Config_getBool(OPTIMIZE_OUTPUT_JAVA))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorJapanese::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 128 of file translator_jp.h.
    {
      if(Config_getBool(OPTIMIZE_OUTPUT_JAVA))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorJapanese::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1551 of file translator_jp.h.
    { return "/"; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorJapanese::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1551 of file translator_jp.h.
    { return "/"; }
trMemberList() [1/2]
virtual QCString TranslatorJapanese::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 162 of file translator_jp.h.
    { return ""; }
trMemberList() [2/2]
virtual QCString TranslatorJapanese::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 162 of file translator_jp.h.
    { return ""; }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorJapanese::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 120 of file translator_jp.h.
    { return ""; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorJapanese::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 120 of file translator_jp.h.
    { return ""; }
trMethodDocumentation() [1/2]
virtual QCString TranslatorJapanese::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1940 of file translator_jp.h.
    {
      return "";
    }
trMethodDocumentation() [2/2]
virtual QCString TranslatorJapanese::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1940 of file translator_jp.h.
    {
      return "";
    }
trModule() [1/2]
virtual QCString TranslatorJapanese::trModule (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1685 of file translator_jp.h.
    {
      return "";
    }
trModule() [2/2]
virtual QCString TranslatorJapanese::trModule (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1685 of file translator_jp.h.
    {
      return "";
    }
trModuleDocumentation() [1/2]
virtual QCString TranslatorJapanese::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 423 of file translator_jp.h.
    { return ""; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorJapanese::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 423 of file translator_jp.h.
    { return ""; }
trModuleIndex() [1/2]
virtual QCString TranslatorJapanese::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 390 of file translator_jp.h.
    { return ""; }
trModuleIndex() [2/2]
virtual QCString TranslatorJapanese::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 390 of file translator_jp.h.
    { return ""; }
trModuleReference() [1/2]
virtual QCString TranslatorJapanese::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1652 of file translator_jp.h.
    {
      QCString result=namespaceName;
      result+="";
      return result;
    }
trModuleReference() [2/2]
virtual QCString TranslatorJapanese::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1652 of file translator_jp.h.
    {
      QCString result=namespaceName;
      result+="";
      return result;
    }
trModules() [1/2]
virtual QCString TranslatorJapanese::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 202 of file translator_jp.h.
    { return ""; }
trModules() [2/2]
virtual QCString TranslatorJapanese::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 202 of file translator_jp.h.
    { return ""; }
trModulesDescription() [1/2]
virtual QCString TranslatorJapanese::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 380 of file translator_jp.h.
    { return ""; }
trModulesDescription() [2/2]
virtual QCString TranslatorJapanese::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 380 of file translator_jp.h.
    { return ""; }
trModulesIndex() [1/2]
virtual QCString TranslatorJapanese::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1678 of file translator_jp.h.
    { return ""; }
trModulesIndex() [2/2]
virtual QCString TranslatorJapanese::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1678 of file translator_jp.h.
    { return ""; }
trModulesList() [1/2]
virtual QCString TranslatorJapanese::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1611 of file translator_jp.h.
    { return ""; }
trModulesList() [2/2]
virtual QCString TranslatorJapanese::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1611 of file translator_jp.h.
    { return ""; }
trModulesListDescription() [1/2]
virtual QCString TranslatorJapanese::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1615 of file translator_jp.h.
    {
      QCString result;
      if (!extractAll)
      {
        result+="";
      }
      else
      {
        result+="";
      }
      result+="";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorJapanese::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1615 of file translator_jp.h.
    {
      QCString result;
      if (!extractAll)
      {
        result+="";
      }
      else
      {
        result+="";
      }
      result+="";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorJapanese::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1664 of file translator_jp.h.
    {
      QCString result=" ";
      if (extractAll)
      {
        result+="";
      }
      result+="";
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorJapanese::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1664 of file translator_jp.h.
    {
      QCString result=" ";
      if (extractAll)
      {
        result+="";
      }
      result+="";
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorJapanese::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1660 of file translator_jp.h.
    { return ""; }
trModulesMembers() [2/2]
virtual QCString TranslatorJapanese::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1660 of file translator_jp.h.
    { return ""; }
trMonth() [1/2]
virtual QCString TranslatorJapanese::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1824 of file translator_jp.h.
    {
      static const char *months_short[] = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" };
      static const char *months_full[] = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      return text;
    }
trMonth() [2/2]
virtual QCString TranslatorJapanese::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1824 of file translator_jp.h.
    {
      static const char *months_short[] = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" };
      static const char *months_full[] = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      return text;
    }
trMore() [1/2]
virtual QCString TranslatorJapanese::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 154 of file translator_jp.h.
    { return "[]"; }
trMore() [2/2]
virtual QCString TranslatorJapanese::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 154 of file translator_jp.h.
    { return "[]"; }
trNamespace() [1/2]
virtual QCString TranslatorJapanese::trNamespace (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1241 of file translator_jp.h.
    {
      return "";
    }
trNamespace() [2/2]
virtual QCString TranslatorJapanese::trNamespace (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1241 of file translator_jp.h.
    {
      return "";
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorJapanese::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 773 of file translator_jp.h.
    { return ""; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorJapanese::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 773 of file translator_jp.h.
    { return ""; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorJapanese::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 767 of file translator_jp.h.
    { return ""; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorJapanese::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 767 of file translator_jp.h.
    { return ""; }
trNamespaceList() [1/2]
virtual QCString TranslatorJapanese::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 594 of file translator_jp.h.
    { return ""; }
trNamespaceList() [2/2]
virtual QCString TranslatorJapanese::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 594 of file translator_jp.h.
    { return ""; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorJapanese::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 598 of file translator_jp.h.
    {
      if (extractAll)
      {
        return "";
      }
      return "";
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorJapanese::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 598 of file translator_jp.h.
    {
      if (extractAll)
      {
        return "";
      }
      return "";
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorJapanese::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 749 of file translator_jp.h.
    {
      QCString result="";
      result+="";
      if (extractAll)
      {
        result+="";
      }
      else
      {
        result+="";
      }
      result+="";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorJapanese::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 749 of file translator_jp.h.
    {
      QCString result="";
      result+="";
      if (extractAll)
      {
        result+="";
      }
      else
      {
        result+="";
      }
      result+="";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorJapanese::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 745 of file translator_jp.h.
    { return ""; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorJapanese::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 745 of file translator_jp.h.
    { return ""; }
trNamespaceReference() [1/2]
virtual QCString TranslatorJapanese::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 656 of file translator_jp.h.
    {
      QCString result=namespaceName+" ";
      return result;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorJapanese::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 656 of file translator_jp.h.
    {
      QCString result=namespaceName+" ";
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorJapanese::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 783 of file translator_jp.h.
    { return ""; }
trNamespaces() [2/2]
virtual QCString TranslatorJapanese::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 783 of file translator_jp.h.
    { return ""; }
trNoMatches() [1/2]
virtual QCString TranslatorJapanese::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1765 of file translator_jp.h.
    {
      return "";
    }
trNoMatches() [2/2]
virtual QCString TranslatorJapanese::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1765 of file translator_jp.h.
    {
      return "";
    }
trNote() [1/2]
virtual QCString TranslatorJapanese::trNote () [inline], [virtual]
Implements Translator.
Definition at line 924 of file translator_jp.h.
    {
      return "";
    }
trNote() [2/2]
virtual QCString TranslatorJapanese::trNote () [inline], [virtual]
Implements Translator.
Definition at line 924 of file translator_jp.h.
    {
      return "";
    }
trOverloadText() [1/2]
virtual QCString TranslatorJapanese::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1522 of file translator_jp.h.
    {
       return ""
              ""
              "";
    }
trOverloadText() [2/2]
virtual QCString TranslatorJapanese::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1522 of file translator_jp.h.
    {
       return ""
              ""
              "";
    }
trPackage() [1/2]
virtual QCString TranslatorJapanese::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1133 of file translator_jp.h.
    {
      return name+" ";
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorJapanese::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1133 of file translator_jp.h.
    {
      return name+" ";
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorJapanese::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1396 of file translator_jp.h.
    {
      return "";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorJapanese::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1396 of file translator_jp.h.
    {
      return "";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorJapanese::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1377 of file translator_jp.h.
    {
      return "";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorJapanese::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1377 of file translator_jp.h.
    {
      return "";
    }
trPackageListDescription() [1/2]
virtual QCString TranslatorJapanese::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1138 of file translator_jp.h.
    {
      return "";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorJapanese::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1138 of file translator_jp.h.
    {
      return "";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorJapanese::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1381 of file translator_jp.h.
    {
      return "";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorJapanese::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1381 of file translator_jp.h.
    {
      return "";
    }
trPackages() [1/2]
virtual QCString TranslatorJapanese::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1143 of file translator_jp.h.
    {
      return "";
    }
trPackages() [2/2]
virtual QCString TranslatorJapanese::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1143 of file translator_jp.h.
    {
      return "";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorJapanese::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1370 of file translator_jp.h.
    {
      return "";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorJapanese::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1370 of file translator_jp.h.
    {
      return "";
    }
trPage() [1/2]
virtual QCString TranslatorJapanese::trPage (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1259 of file translator_jp.h.
    {
      return "";
    }
trPage() [2/2]
virtual QCString TranslatorJapanese::trPage (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1259 of file translator_jp.h.
    {
      return "";
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorJapanese::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 829 of file translator_jp.h.
    { return "p."; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorJapanese::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 829 of file translator_jp.h.
    { return "p."; }
trPageIndex() [1/2]
virtual QCString TranslatorJapanese::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 916 of file translator_jp.h.
    {
      return "";
    }
trPageIndex() [2/2]
virtual QCString TranslatorJapanese::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 916 of file translator_jp.h.
    {
      return "";
    }
trPanelSynchronisationTooltip() [1/2]
virtual QCString TranslatorJapanese::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1897 of file translator_jp.h.
    {
      QCString opt = enable ? "" : "";
      return ""+opt+"";
    }
trPanelSynchronisationTooltip() [2/2]
virtual QCString TranslatorJapanese::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1897 of file translator_jp.h.
    {
      QCString opt = enable ? "" : "";
      return ""+opt+"";
    }
trParameters() [1/2]
virtual QCString TranslatorJapanese::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 578 of file translator_jp.h.
    { return ""; }
trParameters() [2/2]
virtual QCString TranslatorJapanese::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 578 of file translator_jp.h.
    { return ""; }
trPostcondition() [1/2]
virtual QCString TranslatorJapanese::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 885 of file translator_jp.h.
    {
      return "";
    }
trPostcondition() [2/2]
virtual QCString TranslatorJapanese::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 885 of file translator_jp.h.
    {
      return "";
    }
trPrecondition() [1/2]
virtual QCString TranslatorJapanese::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 880 of file translator_jp.h.
    {
      return "";
    }
trPrecondition() [2/2]
virtual QCString TranslatorJapanese::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 880 of file translator_jp.h.
    {
      return "";
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorJapanese::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 963 of file translator_jp.h.
    {
      return "";
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorJapanese::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 963 of file translator_jp.h.
    {
      return "";
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorJapanese::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 677 of file translator_jp.h.
    { return ""; }
trPrivateMembers() [2/2]
virtual QCString TranslatorJapanese::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 677 of file translator_jp.h.
    { return ""; }
trPrivateSlots() [1/2]
virtual QCString TranslatorJapanese::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 679 of file translator_jp.h.
    { return ""; }
trPrivateSlots() [2/2]
virtual QCString TranslatorJapanese::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 679 of file translator_jp.h.
    { return ""; }
trPrivateTypes() [1/2]
virtual QCString TranslatorJapanese::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 959 of file translator_jp.h.
    {
      return "";
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorJapanese::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 959 of file translator_jp.h.
    {
      return "";
    }
trProperties() [1/2]
virtual QCString TranslatorJapanese::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1105 of file translator_jp.h.
    {
      return "";
    }
trProperties() [2/2]
virtual QCString TranslatorJapanese::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1105 of file translator_jp.h.
    {
      return "";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorJapanese::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1110 of file translator_jp.h.
    {
      return "";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorJapanese::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1110 of file translator_jp.h.
    {
      return "";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorJapanese::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 951 of file translator_jp.h.
    {
      return "";
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorJapanese::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 951 of file translator_jp.h.
    {
      return "";
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorJapanese::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 671 of file translator_jp.h.
    { return ""; }
trProtectedMembers() [2/2]
virtual QCString TranslatorJapanese::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 671 of file translator_jp.h.
    { return ""; }
trProtectedSlots() [1/2]
virtual QCString TranslatorJapanese::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 673 of file translator_jp.h.
    { return ""; }
trProtectedSlots() [2/2]
virtual QCString TranslatorJapanese::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 673 of file translator_jp.h.
    { return ""; }
trProtectedTypes() [1/2]
virtual QCString TranslatorJapanese::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 947 of file translator_jp.h.
    {
      return "";
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorJapanese::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 947 of file translator_jp.h.
    {
      return "";
    }
trProvidedByCategory() [1/2]
virtual QCString TranslatorJapanese::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1908 of file translator_jp.h.
    {
      return "@0 ";
    }
trProvidedByCategory() [2/2]
virtual QCString TranslatorJapanese::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1908 of file translator_jp.h.
    {
      return "@0 ";
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorJapanese::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 932 of file translator_jp.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorJapanese::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 932 of file translator_jp.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorJapanese::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 663 of file translator_jp.h.
    { return ""; }
trPublicMembers() [2/2]
virtual QCString TranslatorJapanese::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 663 of file translator_jp.h.
    { return ""; }
trPublicSlots() [1/2]
virtual QCString TranslatorJapanese::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 665 of file translator_jp.h.
    { return ""; }
trPublicSlots() [2/2]
virtual QCString TranslatorJapanese::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 665 of file translator_jp.h.
    { return ""; }
trPublicTypes() [1/2]
virtual QCString TranslatorJapanese::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 928 of file translator_jp.h.
    {
      return "";
    }
trPublicTypes() [2/2]
virtual QCString TranslatorJapanese::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 928 of file translator_jp.h.
    {
      return "";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorJapanese::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 991 of file translator_jp.h.
    {
      return "";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorJapanese::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 991 of file translator_jp.h.
    {
      return "";
    }
trReferenceManual() [1/2]
virtual QCString TranslatorJapanese::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 458 of file translator_jp.h.
    { return ""; }
trReferenceManual() [2/2]
virtual QCString TranslatorJapanese::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 458 of file translator_jp.h.
    { return ""; }
trReferences() [1/2]
virtual QCString TranslatorJapanese::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1299 of file translator_jp.h.
    {
      return "";
    }
trReferences() [2/2]
virtual QCString TranslatorJapanese::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1299 of file translator_jp.h.
    {
      return "";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorJapanese::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 731 of file translator_jp.h.
    {
      return trWriteList(numEntries)+"";
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorJapanese::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 731 of file translator_jp.h.
    {
      return trWriteList(numEntries)+"";
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorJapanese::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 739 of file translator_jp.h.
    {
      return trWriteList(numEntries)+"";
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorJapanese::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 739 of file translator_jp.h.
    {
      return trWriteList(numEntries)+"";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorJapanese::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 620 of file translator_jp.h.
    { return ""; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorJapanese::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 620 of file translator_jp.h.
    { return ""; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorJapanese::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 108 of file translator_jp.h.
    { return ""; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorJapanese::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 108 of file translator_jp.h.
    { return ""; }
trRelatedPages() [1/2]
virtual QCString TranslatorJapanese::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 252 of file translator_jp.h.
    { return ""; }
trRelatedPages() [2/2]
virtual QCString TranslatorJapanese::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 252 of file translator_jp.h.
    { return ""; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorJapanese::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 376 of file translator_jp.h.
    { return ""; }
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorJapanese::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 376 of file translator_jp.h.
    { return ""; }
trRelatedSubscript() [1/2]
virtual QCString TranslatorJapanese::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 112 of file translator_jp.h.
    { return ""; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorJapanese::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 112 of file translator_jp.h.
    { return ""; }
trRemarks() [1/2]
virtual QCString TranslatorJapanese::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 995 of file translator_jp.h.
    {
      return "";
    }
trRemarks() [2/2]
virtual QCString TranslatorJapanese::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 995 of file translator_jp.h.
    {
      return "";
    }
trReturns() [1/2]
virtual QCString TranslatorJapanese::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 570 of file translator_jp.h.
    { return ""; }
trReturns() [2/2]
virtual QCString TranslatorJapanese::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 570 of file translator_jp.h.
    { return ""; }
trReturnValues() [1/2]
virtual QCString TranslatorJapanese::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 818 of file translator_jp.h.
    { return ""; }
trReturnValues() [2/2]
virtual QCString TranslatorJapanese::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 818 of file translator_jp.h.
    { return ""; }
trRTFansicp() [1/2]
virtual QCString TranslatorJapanese::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1199 of file translator_jp.h.
    {
      return "932";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorJapanese::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1199 of file translator_jp.h.
    {
      return "932";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorJapanese::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1208 of file translator_jp.h.
    {
      return "128";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorJapanese::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1208 of file translator_jp.h.
    {
      return "128";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorJapanese::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1214 of file translator_jp.h.
    {
      return "";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorJapanese::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1214 of file translator_jp.h.
    {
      return "";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorJapanese::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1330 of file translator_jp.h.
    {
      return "";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorJapanese::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1330 of file translator_jp.h.
    {
      return "";
    }
trSearch() [1/2]
virtual QCString TranslatorJapanese::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 260 of file translator_jp.h.
    { return ""; }
trSearch() [2/2]
virtual QCString TranslatorJapanese::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 260 of file translator_jp.h.
    { return ""; }
trSearching() [1/2]
virtual QCString TranslatorJapanese::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1759 of file translator_jp.h.
    {
      return "";
    }
trSearching() [2/2]
virtual QCString TranslatorJapanese::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1759 of file translator_jp.h.
    {
      return "";
    }
trSearchMatches() [1/2]
virtual QCString TranslatorJapanese::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1463 of file translator_jp.h.
    {
      return ":";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorJapanese::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1463 of file translator_jp.h.
    {
      return ":";
    }
trSearchResults() [1/2]
virtual QCString TranslatorJapanese::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1444 of file translator_jp.h.
    {
      if (numDocuments==0)
      {
        return "";
      }
      else if (numDocuments==1)
      {
        return " <b>1</b> .";
      }
      else
      {
        return " <b>$num</b> . "
               ".";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorJapanese::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1444 of file translator_jp.h.
    {
      if (numDocuments==0)
      {
        return "";
      }
      else if (numDocuments==1)
      {
        return " <b>1</b> .";
      }
      else
      {
        return " <b>$num</b> . "
               ".";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorJapanese::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1432 of file translator_jp.h.
    {
      return "";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorJapanese::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1432 of file translator_jp.h.
    {
      return "";
    }
trSeeAlso() [1/2]
virtual QCString TranslatorJapanese::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 574 of file translator_jp.h.
    { return ""; }
trSeeAlso() [2/2]
virtual QCString TranslatorJapanese::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 574 of file translator_jp.h.
    { return ""; }
trServiceGeneratedFromFiles() [1/2]
virtual QCString TranslatorJapanese::trServiceGeneratedFromFiles (bool) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 1983 of file translator_jp.h.
    {
      // single is true implies a single file
      return ""
             ":";
    }
trServiceGeneratedFromFiles() [2/2]
virtual QCString TranslatorJapanese::trServiceGeneratedFromFiles (bool) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 1983 of file translator_jp.h.
    {
      // single is true implies a single file
      return ""
             ":";
    }
trServiceReference() [1/2]
virtual QCString TranslatorJapanese::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 1969 of file translator_jp.h.
    {
      QCString result=sName;
      result+=" ";
      return result;
    }
trServiceReference() [2/2]
virtual QCString TranslatorJapanese::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 1969 of file translator_jp.h.
    {
      QCString result=sName;
      result+=" ";
      return result;
    }
trServices() [1/2]
virtual QCString TranslatorJapanese::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1954 of file translator_jp.h.
    { return ""; }
trServices() [2/2]
virtual QCString TranslatorJapanese::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1954 of file translator_jp.h.
    { return ""; }
trSignals() [1/2]
virtual QCString TranslatorJapanese::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 667 of file translator_jp.h.
    { return ""; }
trSignals() [2/2]
virtual QCString TranslatorJapanese::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 667 of file translator_jp.h.
    { return ""; }
trSince() [1/2]
virtual QCString TranslatorJapanese::trSince () [inline], [virtual]
Implements Translator.
Definition at line 1007 of file translator_jp.h.
    {
      return "";
    }
trSince() [2/2]
virtual QCString TranslatorJapanese::trSince () [inline], [virtual]
Implements Translator.
Definition at line 1007 of file translator_jp.h.
    {
      return "";
    }
trSingletonGeneratedFromFiles() [1/2]
virtual QCString TranslatorJapanese::trSingletonGeneratedFromFiles (bool) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 1990 of file translator_jp.h.
    {
      // single is true implies a single file
      return " Singleton "
             ":";
    }
trSingletonGeneratedFromFiles() [2/2]
virtual QCString TranslatorJapanese::trSingletonGeneratedFromFiles (bool) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 1990 of file translator_jp.h.
    {
      // single is true implies a single file
      return " Singleton "
             ":";
    }
trSingletonReference() [1/2]
virtual QCString TranslatorJapanese::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 1976 of file translator_jp.h.
    {
      QCString result=sName;
      result+=" Singleton ";
      return result;
    }
trSingletonReference() [2/2]
virtual QCString TranslatorJapanese::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 1976 of file translator_jp.h.
    {
      QCString result=sName;
      result+=" Singleton ";
      return result;
    }
trSourceFile() [1/2]
virtual QCString TranslatorJapanese::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1474 of file translator_jp.h.
    {
      return filename + " ";
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorJapanese::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1474 of file translator_jp.h.
    {
      return filename + " ";
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorJapanese::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1403 of file translator_jp.h.
    {
      return "";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorJapanese::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1403 of file translator_jp.h.
    {
      return "";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorJapanese::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1389 of file translator_jp.h.
    {
      return "";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorJapanese::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1389 of file translator_jp.h.
    {
      return "";
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorJapanese::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 967 of file translator_jp.h.
    {
      return "";
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorJapanese::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 967 of file translator_jp.h.
    {
      return "";
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorJapanese::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 681 of file translator_jp.h.
    { return ""; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorJapanese::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 681 of file translator_jp.h.
    { return ""; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorJapanese::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 955 of file translator_jp.h.
    {
      return "";
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorJapanese::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 955 of file translator_jp.h.
    {
      return "";
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorJapanese::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 675 of file translator_jp.h.
    { return ""; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorJapanese::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 675 of file translator_jp.h.
    { return ""; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorJapanese::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 943 of file translator_jp.h.
    {
      return "";
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorJapanese::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 943 of file translator_jp.h.
    {
      return "";
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorJapanese::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 669 of file translator_jp.h.
    { return ""; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorJapanese::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 669 of file translator_jp.h.
    { return ""; }
trSubprogram() [1/2]
virtual QCString TranslatorJapanese::trSubprogram (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1724 of file translator_jp.h.
    {
      QCString result = "";
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorJapanese::trSubprogram (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1724 of file translator_jp.h.
    {
      QCString result = "";
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorJapanese::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1601 of file translator_jp.h.
    { return "/"; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorJapanese::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1601 of file translator_jp.h.
    { return "/"; }
trSubprograms() [1/2]
virtual QCString TranslatorJapanese::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1594 of file translator_jp.h.
    { return "/"; }
trSubprograms() [2/2]
virtual QCString TranslatorJapanese::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1594 of file translator_jp.h.
    { return "/"; }
trTemplateParameters() [1/2]
virtual QCString TranslatorJapanese::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1862 of file translator_jp.h.
    { return ""; }
trTemplateParameters() [2/2]
virtual QCString TranslatorJapanese::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1862 of file translator_jp.h.
    { return ""; }
trTest() [1/2]
virtual QCString TranslatorJapanese::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1090 of file translator_jp.h.
    {
      return "";
    }
trTest() [2/2]
virtual QCString TranslatorJapanese::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1090 of file translator_jp.h.
    {
      return "";
    }
trTestList() [1/2]
virtual QCString TranslatorJapanese::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1095 of file translator_jp.h.
    {
      return "";
    }
trTestList() [2/2]
virtual QCString TranslatorJapanese::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1095 of file translator_jp.h.
    {
      return "";
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorJapanese::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 166 of file translator_jp.h.
    { return " "; }
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorJapanese::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 166 of file translator_jp.h.
    { return " "; }
trTodo() [1/2]
virtual QCString TranslatorJapanese::trTodo () [inline], [virtual]
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 977 of file translator_jp.h.
    {
      return "todo";
    }
trTodo() [2/2]
virtual QCString TranslatorJapanese::trTodo () [inline], [virtual]
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 977 of file translator_jp.h.
    {
      return "todo";
    }
trTodoList() [1/2]
virtual QCString TranslatorJapanese::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 982 of file translator_jp.h.
    {
      return "todo";
    }
trTodoList() [2/2]
virtual QCString TranslatorJapanese::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 982 of file translator_jp.h.
    {
      return "todo";
    }
trType() [1/2]
virtual QCString TranslatorJapanese::trType (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1715 of file translator_jp.h.
    {
      QCString result = "";
      return result;
    }
trType() [2/2]
virtual QCString TranslatorJapanese::trType (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1715 of file translator_jp.h.
    {
      QCString result = "";
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorJapanese::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1731 of file translator_jp.h.
    {
      return "";
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorJapanese::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1731 of file translator_jp.h.
    {
      return "";
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorJapanese::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 505 of file translator_jp.h.
    { return ""; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorJapanese::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 505 of file translator_jp.h.
    { return ""; }
trTypedefs() [1/2]
virtual QCString TranslatorJapanese::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 470 of file translator_jp.h.
    { return ""; }
trTypedefs() [2/2]
virtual QCString TranslatorJapanese::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 470 of file translator_jp.h.
    { return ""; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorJapanese::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1588 of file translator_jp.h.
    { return ""; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorJapanese::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1588 of file translator_jp.h.
    { return ""; }
trVariableDocumentation() [1/2]
virtual QCString TranslatorJapanese::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 523 of file translator_jp.h.
    { return ""; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorJapanese::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 523 of file translator_jp.h.
    { return ""; }
trVariables() [1/2]
virtual QCString TranslatorJapanese::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 488 of file translator_jp.h.
    { return ""; }
trVariables() [2/2]
virtual QCString TranslatorJapanese::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 488 of file translator_jp.h.
    { return ""; }
trVersion() [1/2]
virtual QCString TranslatorJapanese::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 562 of file translator_jp.h.
    { return ""; }
trVersion() [2/2]
virtual QCString TranslatorJapanese::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 562 of file translator_jp.h.
    { return ""; }
trWarning() [1/2]
virtual QCString TranslatorJapanese::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 558 of file translator_jp.h.
    { return ""; }
trWarning() [2/2]
virtual QCString TranslatorJapanese::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 558 of file translator_jp.h.
    { return ""; }
trWriteList() [1/2]
virtual QCString TranslatorJapanese::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 687 of file translator_jp.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          result+=", ";
        }
      }
      if (result.length() > 60)
      {
        QCString countStr;
        countStr.sprintf(" (%d)", numEntries);
        result += countStr;
      }
      return result;
    }
References generateMarker(), QCString::length(), and QCString::sprintf().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorJapanese::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 687 of file translator_jp.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          result+=", ";
        }
      }
      if (result.length() > 60)
      {
        QCString countStr;
        countStr.sprintf(" (%d)", numEntries);
        result += countStr;
      }
      return result;
    }
References generateMarker(), QCString::length(), and QCString::sprintf().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_jp.h
doxygen/src/translator_jp.h