KeywordHash Class Reference
Static Public Member Functions
static const char * find (const char *str, unsigned int len)
static const char * find (const char *str, unsigned int len)
Static Private Member Functions
static unsigned int hash (const char *str, unsigned int len)
static unsigned int hash (const char *str, unsigned int len)
Detailed Description
Definition at line 685 of file defargs.l.
Member Function Documentation
find() [1/2]
const char * KeywordHash::find (const char * str, unsigned int len) [static]
Definition at line 742 of file defargs.l.
{
  static const char * const wordlist[] =
  {
    "", "", "",
    "int",
    "bool",
    "float",
    "signed",
    "",
    "volatile",
    "char",
    "short",
    "double",
    "wchar_t",
    "uint16_t",
    "long",
    "const",
    "int8_t",
    "uint8_t",
    "char16_t",
    "void",
    "", "",
    "char8_t",
    "intptr_t",
    "uintptr_t",
    "", "", "",
    "intmax_t",
    "uintmax_t",
    "", "",
    "int64_t",
    "uint64_t",
    "", "", "",
    "int16_t",
    "uint32_t",
    "", "", "",
    "int32_t",
    "char32_t",
    "", "", "", "",
    "unsigned"
  };
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
  {
    unsigned int key = hash (str, len);
    if (key <= MAX_HASH_VALUE)
    {
      const char *s = wordlist[key];
      if (*str == *s && !qstrcmp (str + 1, s + 1))
        return s;
    }
  }
  return 0;
}
References hash(), len, MAX_HASH_VALUE, MIN_WORD_LENGTH, qstrcmp(), and s.
Referenced by nameIsActuallyPartOfType().
find() [2/2]
static const char * KeywordHash::find (const char * str, unsigned int len) [static]
hash() [1/2]
unsigned int KeywordHash::hash (const char * str, unsigned int len) [inline], [static], [private]
Definition at line 694 of file defargs.l.
{
  static const unsigned char asso_values[] =
  {
    49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
    49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
    49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
    49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
    49, 49, 49, 49, 49, 49, 49, 49, 49, 5,
     5, 30, 0, 49, 25, 49, 10, 49, 49, 49,
    49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
    49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
    49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
    49, 49, 49, 49, 49, 0, 49, 0, 5, 49,
    15, 0, 49, 10, 49, 30, 49, 49, 0, 20,
     0, 49, 15, 49, 5, 10, 0, 49, 49, 49,
    49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
    49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
    49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
    49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
    49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
    49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
    49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
    49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
    49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
    49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
    49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
    49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
    49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
    49, 49, 49, 49, 49, 49
  };
  unsigned int hval = len;
  switch (hval)
  {
    default:
      hval += asso_values[static_cast<unsigned char>(str[4])];
      /*FALLTHROUGH*/
    case 4:
      hval += asso_values[static_cast<unsigned char>(str[3])];
      /*FALLTHROUGH*/
    case 3:
      break;
  }
  return hval;
}
References len.
Referenced by find().
hash() [2/2]
static unsigned int KeywordHash::hash (const char * str, unsigned int len) [inline], [static], [private]
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/defargs.l
doxygen/src/defargs.l