ClassDiagram Class Reference
#include <diagram.h>
Classes
struct Private
Public Member Functions
ClassDiagram (const ClassDef *root)
~ClassDiagram ()
void writeFigure (TextStream &t, const QCString &path, const QCString &file) const
void writeImage (TextStream &t, const QCString &path, const QCString &relPath, const QCString &file, bool generateMap=true) const
ClassDiagram (const ClassDef *root)
~ClassDiagram ()
void writeFigure (TextStream &t, const QCString &path, const QCString &file) const
void writeImage (TextStream &t, const QCString &path, const QCString &relPath, const QCString &file, bool generateMap=true) const
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Class representing a built-in class diagram.
Definition at line 29 of file diagram.h.
Constructor & Destructor Documentation
ClassDiagram() [1/2]
ClassDiagram::ClassDiagram (const ClassDef * root)
Definition at line 1031 of file diagram.cpp.
                                               : p(std::make_unique<Private>(root))
{
  p->base.computeLayout();
  p->super.computeLayout();
  DiagramItem *baseItem = p->base.row(0)->item(0);
  DiagramItem *superItem = p->super.row(0)->item(0);
  uint xbase = baseItem->xPos();
  uint xsuper = superItem->xPos();
  if (xbase>xsuper)
  {
    int dist=static_cast<int>(xbase-xsuper);
    superItem->move(dist,0);
    p->super.moveChildren(superItem,dist);
  }
  else if (xbase<xsuper)
  {
    int dist=static_cast<int>(xsuper-xbase);
    baseItem->move(dist,0);
    p->base.moveChildren(baseItem,dist);
  }
}
References DiagramItem::move(), p, and DiagramItem::xPos().
 ClassDiagram() [1/2]
ClassDiagram::~ClassDiagram ()
Definition at line 1053 of file diagram.cpp.
{
}
ClassDiagram() [2/2]
ClassDiagram::ClassDiagram (const ClassDef * root)
 ClassDiagram() [2/2]
ClassDiagram::~ClassDiagram ()
Member Function Documentation
writeFigure() [1/2]
void ClassDiagram::writeFigure (TextStream & t, const QCString & path, const QCString & file) const
Definition at line 1057 of file diagram.cpp.
{
  uint baseRows=p->base.computeRows();
  uint superRows=p->super.computeRows();
  uint baseMaxX, baseMaxLabelWidth, superMaxX, superMaxLabelWidth;
  p->base.computeExtremes(&baseMaxLabelWidth,&baseMaxX);
  p->super.computeExtremes(&superMaxLabelWidth,&superMaxX);
  uint rows=std::max(1u,baseRows+superRows-1);
  uint cols=(std::max(baseMaxX,superMaxX)+gridWidth*2-1)/gridWidth;
  // Estimate the image aspect width and height in pixels.
  float estHeight = static_cast<float>(rows)*40.0f;
  float estWidth = static_cast<float>(cols)*(20+static_cast<float>(std::max(baseMaxLabelWidth,superMaxLabelWidth)));
  //printf("Estimated size %d x %d\n",estWidth,estHeight);
  const float pageWidth = 14.0f; // estimated page width in cm.
                                 // Somewhat lower to deal with estimation
                                 // errors.
  // compute the image height in centimeters based on the estimates
  float realHeight = static_cast<float>(std::min(rows,12u)); // real height in cm
  float realWidth = realHeight * estWidth/estHeight;
  if (realWidth>pageWidth) // assume that the page width is about 15 cm
  {
    realHeight*=pageWidth/realWidth;
  }
  //output << "}\n";
  output << "\\begin{figure}[H]\n"
            "\\begin{center}\n"
            "\\leavevmode\n";
  output << "\\includegraphics[height=" << realHeight << "cm]{"
                                        << fileName << "}\n";
  output << "\\end{center}\n"
            "\\end{figure}\n";
  //printf("writeFigure rows=%d cols=%d\n",rows,cols);
  QCString epsBaseName=QCString(path)+"/"+fileName;
  QCString epsName=epsBaseName+".eps";
  std::ofstream f(epsName.str(),std::ofstream::out | std::ofstream::binary);
  if (!f.is_open())
  {
    term("Could not open file %s for writing\n",qPrint(epsName));
  }
  else
  {
    TextStream t(&f);
    //printf("writeEPS() rows=%d cols=%d\n",rows,cols);
    // generate EPS header and postscript variables and procedures
    t << "%!PS-Adobe-2.0 EPSF-2.0\n";
    t << "%%Title: ClassName\n";
    t << "%%Creator: Doxygen\n";
    t << "%%CreationDate: Time\n";
    t << "%%For: \n";
    t << "%Magnification: 1.00\n";
    t << "%%Orientation: Portrait\n";
    t << "%%BoundingBox: 0 0 500 " << estHeight*500.0f/estWidth << "\n";
    t << "%%Pages: 0\n";
    t << "%%BeginSetup\n";
    t << "%%EndSetup\n";
    t << "%%EndComments\n";
    t << "\n";
    t << "% ----- variables -----\n";
    t << "\n";
    t << "/boxwidth 0 def\n";
    t << "/boxheight 40 def\n";
    t << "/fontheight 24 def\n";
    t << "/marginwidth 10 def\n";
    t << "/distx 20 def\n";
    t << "/disty 40 def\n";
    t << "/boundaspect " << estWidth/estHeight << " def % aspect ratio of the BoundingBox (width/height)\n";
    t << "/boundx 500 def\n";
    t << "/boundy boundx boundaspect div def\n";
    t << "/xspacing 0 def\n";
    t << "/yspacing 0 def\n";
    t << "/rows " << rows << " def\n";
    t << "/cols " << cols << " def\n";
    t << "/scalefactor 0 def\n";
    t << "/boxfont /Times-Roman findfont fontheight scalefont def\n";
    t << "\n";
    t << "% ----- procedures -----\n";
    t << "\n";
    t << "/dotted { [1 4] 0 setdash } def\n";
    t << "/dashed { [5] 0 setdash } def\n";
    t << "/solid { [] 0 setdash } def\n";
    t << "\n";
    t << "/max % result = MAX(arg1,arg2)\n";
    t << "{\n";
    t << " /a exch def\n";
    t << " /b exch def\n";
    t << " a b gt {a} {b} ifelse\n";
    t << "} def\n";
    t << "\n";
    t << "/xoffset % result = MAX(0,(scalefactor-(boxwidth*cols+distx*(cols-1)))/2)\n";
    t << "{\n";
    t << " 0 scalefactor boxwidth cols mul distx cols 1 sub mul add sub 2 div max\n";
    t << "} def\n";
    t << "\n";
    t << "/cw % boxwidth = MAX(boxwidth, stringwidth(arg1))\n";
    t << "{\n";
    t << " /str exch def\n";
    t << " /boxwidth boxwidth str stringwidth pop max def\n";
    t << "} def\n";
    t << "\n";
    t << "/box % draws a box with text 'arg1' at grid pos (arg2,arg3)\n";
    t << "{ gsave\n";
    t << " 2 setlinewidth\n";
    t << " newpath\n";
    t << " exch xspacing mul xoffset add\n";
    t << " exch yspacing mul\n";
    t << " moveto\n";
    t << " boxwidth 0 rlineto \n";
    t << " 0 boxheight rlineto \n";
    t << " boxwidth neg 0 rlineto \n";
    t << " 0 boxheight neg rlineto \n";
    t << " closepath\n";
    t << " dup stringwidth pop neg boxwidth add 2 div\n";
    t << " boxheight fontheight 2 div sub 2 div\n";
    t << " rmoveto show stroke\n";
    t << " grestore\n";
    t << "} def \n";
    t << "\n";
    t << "/mark\n";
    t << "{ newpath\n";
    t << " exch xspacing mul xoffset add boxwidth add\n";
    t << " exch yspacing mul\n";
    t << " moveto\n";
    t << " 0 boxheight 4 div rlineto\n";
    t << " boxheight neg 4 div boxheight neg 4 div rlineto\n";
    t << " closepath\n";
    t << " eofill\n";
    t << " stroke\n";
    t << "} def\n";
    t << "\n";
    t << "/arrow\n";
    t << "{ newpath\n";
    t << " moveto\n";
    t << " 3 -8 rlineto\n";
    t << " -6 0 rlineto\n";
    t << " 3 8 rlineto\n";
    t << " closepath\n";
    t << " eofill\n";
    t << " stroke\n";
    t << "} def\n";
    t << "\n";
    t << "/out % draws an output connector for the block at (arg1,arg2)\n";
    t << "{\n";
    t << " newpath\n";
    t << " exch xspacing mul xoffset add boxwidth 2 div add\n";
    t << " exch yspacing mul boxheight add\n";
    t << " /y exch def\n";
    t << " /x exch def\n";
    t << " x y moveto\n";
    t << " 0 disty 2 div rlineto \n";
    t << " stroke\n";
    t << " 1 eq { x y disty 2 div add arrow } if\n";
    t << "} def\n";
    t << "\n";
    t << "/in % draws an input connector for the block at (arg1,arg2)\n";
    t << "{\n";
    t << " newpath\n";
    t << " exch xspacing mul xoffset add boxwidth 2 div add\n";
    t << " exch yspacing mul disty 2 div sub\n";
    t << " /y exch def\n";
    t << " /x exch def\n";
    t << " x y moveto\n";
    t << " 0 disty 2 div rlineto\n";
    t << " stroke\n";
    t << " 1 eq { x y disty 2 div add arrow } if\n";
    t << "} def\n";
    t << "\n";
    t << "/hedge\n";
    t << "{\n";
    t << " exch xspacing mul xoffset add boxwidth 2 div add\n";
    t << " exch yspacing mul boxheight 2 div sub\n";
    t << " /y exch def\n";
    t << " /x exch def\n";
    t << " newpath\n";
    t << " x y moveto\n";
    t << " boxwidth 2 div distx add 0 rlineto\n";
    t << " stroke\n";
    t << " 1 eq\n";
    t << " { newpath x boxwidth 2 div distx add add y moveto\n";
    t << " -8 3 rlineto\n";
    t << " 0 -6 rlineto\n";
    t << " 8 3 rlineto\n";
    t << " closepath\n";
    t << " eofill\n";
    t << " stroke\n";
    t << " } if\n";
    t << "} def\n";
    t << "\n";
    t << "/vedge\n";
    t << "{\n";
    t << " /ye exch def\n";
    t << " /ys exch def\n";
    t << " /xs exch def\n";
    t << " newpath\n";
    t << " xs xspacing mul xoffset add boxwidth 2 div add dup\n";
    t << " ys yspacing mul boxheight 2 div sub\n";
    t << " moveto\n";
    t << " ye yspacing mul boxheight 2 div sub\n";
    t << " lineto\n";
    t << " stroke\n";
    t << "} def\n";
    t << "\n";
    t << "/conn % connections the blocks from col 'arg1' to 'arg2' of row 'arg3'\n";
    t << "{\n";
    t << " /ys exch def\n";
    t << " /xe exch def\n";
    t << " /xs exch def\n";
    t << " newpath\n";
    t << " xs xspacing mul xoffset add boxwidth 2 div add\n";
    t << " ys yspacing mul disty 2 div sub\n";
    t << " moveto\n";
    t << " xspacing xe xs sub mul 0\n";
    t << " rlineto\n";
    t << " stroke\n";
    t << "} def\n";
    t << "\n";
    t << "% ----- main ------\n";
    t << "\n";
    t << "boxfont setfont\n";
    t << "1 boundaspect scale\n";
    for (const auto &dr : p->base)
    {
      bool done=FALSE;
      for (const auto &di : *dr)
      {
        done=di->isInList();
        t << "(" << convertToPSString(di->label()) << ") cw\n";
      }
      if (done) break;
    }
    auto it = p->super.begin();
    if (it!=p->super.end()) ++it;
    for (;it!=p->super.end();++it)
    {
      const auto &dr = *it;
      bool done=FALSE;
      for (const auto &di : *dr)
      {
        done=di->isInList();
        t << "(" << convertToPSString(di->label()) << ") cw\n";
      }
      if (done) break;
    }
    t << "/boxwidth boxwidth marginwidth 2 mul add def\n"
      << "/xspacing boxwidth distx add def\n"
      << "/yspacing boxheight disty add def\n"
      << "/scalefactor \n"
      << " boxwidth cols mul distx cols 1 sub mul add\n"
      << " boxheight rows mul disty rows 1 sub mul add boundaspect mul \n"
      << " max def\n"
      << "boundx scalefactor div boundy scalefactor div scale\n";
    t << "\n% ----- classes -----\n\n";
    p->base.drawBoxes(t,0,TRUE,FALSE,baseRows,superRows,0,0);
    p->super.drawBoxes(t,0,FALSE,FALSE,baseRows,superRows,0,0);
    t << "\n% ----- relations -----\n\n";
    p->base.drawConnectors(t,0,TRUE,FALSE,baseRows,superRows,0,0);
    p->super.drawConnectors(t,0,FALSE,FALSE,baseRows,superRows,0,0);
  }
  f.close();
  if (Config_getBool(USE_PDFLATEX))
  {
    QCString epstopdfArgs(4096);
    epstopdfArgs.sprintf("\"%s.eps\" --outfile=\"%s.pdf\"",
                   qPrint(epsBaseName),qPrint(epsBaseName));
    //printf("Converting eps using '%s'\n",qPrint(epstopdfArgs));
    Portable::sysTimerStart();
    if (Portable::system("epstopdf",epstopdfArgs)!=0)
    {
       err("Problems running epstopdf. Check your TeX installation!\n");
       Portable::sysTimerStop();
       return;
    }
    Portable::sysTimerStop();
  }
}
References Config_getBool, convertToPSString(), err(), f, FALSE, gridWidth, out, p, qPrint(), QCString::sprintf(), QCString::str(), Portable::system(), Portable::sysTimerStart(), Portable::sysTimerStop(), term(), and TRUE.
Referenced by LatexGenerator::endClassDiagram(), and ClassContext::Private::inheritanceDiagram().
writeFigure() [2/2]
void ClassDiagram::writeFigure (TextStream & t, const QCString & path, const QCString & file) const
writeImage() [1/2]
void ClassDiagram::writeImage (TextStream & t, const QCString & path, const QCString & relPath, const QCString & file, bool generateMap = true) const
Definition at line 1352 of file diagram.cpp.
{
  uint baseRows=p->base.computeRows();
  uint superRows=p->super.computeRows();
  uint rows=baseRows+superRows-1;
  uint lb,ls,xb,xs;
  p->base.computeExtremes(&lb,&xb);
  p->super.computeExtremes(&ls,&xs);
  uint cellWidth = std::max(lb,ls)+labelHorMargin*2;
  uint maxXPos = std::max(xb,xs);
  uint labelVertMargin = 6; //std::max(6,(cellWidth-fontHeight)/6); // aspect at least 1:3
  uint cellHeight = labelVertMargin*2+fontHeight;
  uint imageWidth = (maxXPos+gridWidth)*cellWidth/gridWidth+
                    (maxXPos*labelHorSpacing)/gridWidth;
  uint imageHeight = rows*cellHeight+(rows-1)*labelVertSpacing;
  Image image(imageWidth,imageHeight);
  p->base.drawBoxes(t,&image,TRUE,TRUE,baseRows,superRows,cellWidth,cellHeight,relPath,generateMap);
  p->super.drawBoxes(t,&image,FALSE,TRUE,baseRows,superRows,cellWidth,cellHeight,relPath,generateMap);
  p->base.drawConnectors(t,&image,TRUE,TRUE,baseRows,superRows,cellWidth,cellHeight);
  p->super.drawConnectors(t,&image,FALSE,TRUE,baseRows,superRows,cellWidth,cellHeight);
#define IMAGE_EXT ".png"
  image.save(QCString(path)+"/"+fileName+IMAGE_EXT);
  Doxygen::indexList->addImageFile(QCString(fileName)+IMAGE_EXT);
}
References IndexList::addImageFile(), FALSE, fontHeight, gridWidth, IMAGE_EXT, Doxygen::indexList, labelHorMargin, labelHorSpacing, labelVertSpacing, p, and TRUE.
Referenced by DocbookGenerator::endClassDiagram(), HtmlGenerator::endClassDiagram(), RTFGenerator::endClassDiagram(), and ClassContext::Private::inheritanceDiagram().
writeImage() [2/2]
void ClassDiagram::writeImage (TextStream & t, const QCString & path, const QCString & relPath, const QCString & file, bool generateMap = true) const
Member Data Documentation
p
std::unique_ptr< Private > ClassDiagram::p [private]
Definition at line 40 of file diagram.h.
Referenced by ClassDiagram(), writeFigure(), and writeImage().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/diagram.h
doxygen/src/diagram.h
doxygen/build/doxygen/src/diagram.cpp
doxygen/src/diagram.cpp