ExampleListContext::Private Class Reference
Public Member Functions
Private ()
Private ()
Additional Inherited Members
Detailed Description
Definition at line 6678 of file context.cpp.
Constructor & Destructor Documentation
Private() [1/2]
ExampleListContext::Private::Private () [inline]
Definition at line 6681 of file context.cpp.
    {
      for (const auto &pd : *Doxygen::exampleLinkedMap)
      {
        if (!pd->getGroupDef() && !pd->isReference())
        {
          append(PageContext::alloc(pd.get(),FALSE,TRUE));
        }
      }
    }
References PageContext::alloc(), GenericNodeListContext::append(), Doxygen::exampleLinkedMap, FALSE, and TRUE.
Private() [2/2]
ExampleListContext::Private::Private () [inline]
Definition at line 6681 of file context.cpp.
    {
      for (const auto &pd : *Doxygen::exampleLinkedMap)
      {
        if (!pd->getGroupDef() && !pd->isReference())
        {
          append(PageContext::alloc(pd.get(),FALSE,TRUE));
        }
      }
    }
References PageContext::alloc(), Doxygen::exampleLinkedMap, FALSE, and TRUE.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp