InheritanceListContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
InheritanceListContext (const BaseClassList &list, bool baseClasses)
virtual ~InheritanceListContext ()
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
InheritanceListContext (const BaseClassList &list, bool baseClasses)
virtual ~InheritanceListContext ()
Static Public Member Functions
static TemplateListIntfPtr alloc (const BaseClassList &list, bool baseClasses)
static TemplateListIntfPtr alloc (const BaseClassList &list, bool baseClasses)
Private Attributes
std::unique_ptr< Private > p
Additional Inherited Members
Detailed Description
Definition at line 980 of file context.h.
Constructor & Destructor Documentation
InheritanceListContext() [1/2]
InheritanceListContext::InheritanceListContext (const BaseClassList & list, bool baseClasses)
Definition at line 7528 of file context.cpp.
                                                                                          : p(std::make_unique<Private>())
{
  for (const auto &bcd : list)
  {
    const ClassDef *cd=bcd.classDef;
    QCString name;
    if (baseClasses)
    {
      name = insertTemplateSpecifierInScope(
          cd->displayName(),bcd.templSpecifiers);
    }
    else
    {
      name = cd->displayName();
    }
    //printf("InheritanceListContext: adding %s baseClass=%d\n",qPrint(name),baseClasses);
    p->addClass(cd,name);
  }
}
References ClassDef::displayName(), insertTemplateSpecifierInScope(), setup::name, and p.
 InheritanceListContext() [1/2]
InheritanceListContext::~InheritanceListContext () [virtual]
Definition at line 7548 of file context.cpp.
{
}
InheritanceListContext() [2/2]
InheritanceListContext::InheritanceListContext (const BaseClassList & list, bool baseClasses)
 InheritanceListContext() [2/2]
virtual InheritanceListContext::~InheritanceListContext () [virtual]
Member Function Documentation
alloc() [1/2]
static TemplateListIntfPtr InheritanceListContext::alloc (const BaseClassList & list, bool baseClasses) [inline], [static]
Definition at line 983 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<InheritanceListContext>(list,baseClasses)); }
Referenced by ClassContext::Private::createInheritedByList(), and ClassContext::Private::createInheritsList().
alloc() [2/2]
static TemplateListIntfPtr InheritanceListContext::alloc (const BaseClassList & list, bool baseClasses) [inline], [static]
Definition at line 983 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<InheritanceListContext>(list,baseClasses)); }
at() [1/2]
TemplateVariant InheritanceListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 7558 of file context.cpp.
{
  return p->at(index);
}
References p.
at() [2/2]
virtual TemplateVariant InheritanceListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
count() [1/2]
size_t InheritanceListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Definition at line 7553 of file context.cpp.
{
  return p->count();
}
References p.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
count() [2/2]
virtual size_t InheritanceListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
createIterator() [1/2]
TemplateListIntf::ConstIteratorPtr InheritanceListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 7563 of file context.cpp.
{
  return p->createIterator();
}
References p.
createIterator() [2/2]
virtual TemplateListIntf::ConstIteratorPtr InheritanceListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Member Data Documentation
p
std::unique_ptr< Private > InheritanceListContext::p [private]
Definition at line 996 of file context.h.
Referenced by at(), count(), createIterator(), and InheritanceListContext().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.h
doxygen/src/context.h
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp