TemplateImpl Class Reference
Internal class representing the implementation of a template.
Public Member Functions
TemplateImpl (TemplateEngine *e, const QCString &name, const QCString &data, const QCString &extension)
~TemplateImpl ()
void render (TextStream &ts, TemplateContext *c)
TemplateEngine * engine () const
TemplateBlockContext * blockContext ()
TemplateImpl (TemplateEngine *e, const QCString &name, const QCString &data, const QCString &extension)
~TemplateImpl ()
void render (TextStream &ts, TemplateContext *c)
TemplateEngine * engine () const
TemplateBlockContext * blockContext ()
Private Attributes
TemplateEngine * m_engine = 0
QCString m_name
TemplateNodeList m_nodes
TemplateBlockContext m_blockContext
Detailed Description
Internal class representing the implementation of a template.
Definition at line 2553 of file template.cpp.
Constructor & Destructor Documentation
TemplateImpl() [1/2]
TemplateImpl::TemplateImpl (TemplateEngine * e, const QCString & name, const QCString & data, const QCString & extension)
Definition at line 5176 of file template.cpp.
  : TemplateNode(0)
{
  //printf("%p:TemplateImpl::TemplateImpl(%s)\n",(void*)this,qPrint(name));
  m_name = name;
  m_engine = engine;
  TemplateLexer lexer(engine,name,data);
  if (extension=="tex")
  {
    lexer.setOpenCloseCharacters('<','>');
  }
  TemplateTokenStream tokens;
  lexer.tokenize(tokens);
  TemplateParser parser(engine,name,tokens);
  parser.parse(this,1,StringVector(),m_nodes);
}
References data, engine(), m_engine, m_name, m_nodes, setup::name, TemplateParser::parse(), TemplateLexer::setOpenCloseCharacters(), and TemplateLexer::tokenize().
 TemplateImpl() [1/2]
TemplateImpl::~TemplateImpl ()
Definition at line 5194 of file template.cpp.
{
  //printf("%p:TemplateImpl::~TemplateImpl(%s)\n",(void*)this,qPrint(m_name));
}
TemplateImpl() [2/2]
TemplateImpl::TemplateImpl (TemplateEngine * e, const QCString & name, const QCString & data, const QCString & extension)
 TemplateImpl() [2/2]
TemplateImpl::~TemplateImpl ()
Member Function Documentation
blockContext() [1/2]
TemplateBlockContext * TemplateImpl::blockContext () [inline]
Definition at line 2562 of file template.cpp.
{ return &m_blockContext; }
References m_blockContext.
blockContext() [2/2]
TemplateBlockContext * TemplateImpl::blockContext () [inline]
Definition at line 2562 of file template.cpp.
{ return &m_blockContext; }
engine() [1/2]
TemplateEngine * TemplateImpl::engine () const [inline]
Definition at line 2561 of file template.cpp.
{ return m_engine; }
References m_engine.
Referenced by doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.compound.docPlantumlType::get_engine(), TemplateNodeCreate::render(), TemplateNodeBlock::render(), TemplateNodeExtend::render(), TemplateNodeInclude::render(), doxmlparser.compound.docPlantumlType::set_engine(), and TemplateImpl().
engine() [2/2]
TemplateEngine * TemplateImpl::engine () const [inline]
Definition at line 2561 of file template.cpp.
{ return m_engine; }
Referenced by doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.compound.docPlantumlType::get_engine(), and doxmlparser.compound.docPlantumlType::set_engine().
render() [1/2]
void TemplateImpl::render (TextStream & ts, TemplateContext * c) [virtual]
Implements TemplateNode.
Definition at line 5199 of file template.cpp.
{
  TemplateContextImpl *ci = dynamic_cast<TemplateContextImpl*>(c);
  if (ci==0) return; // should not happen
  if (!m_nodes.empty())
  {
    TemplateNodeExtend *ne = dynamic_cast<TemplateNodeExtend*>(m_nodes.front().get());
    if (ne==0) // normal template, add blocks to block context
    {
      TemplateBlockContext *bc = ci->blockContext();
      for (const auto &n : m_nodes)
      {
        TemplateNodeBlock *nb = dynamic_cast<TemplateNodeBlock*>(n.get());
        if (nb)
        {
          bc->add(nb);
        }
      }
    }
    m_nodes.render(ts,c);
  }
}
References TemplateBlockContext::add(), TemplateContextImpl::blockContext(), c, m_nodes, n, and TemplateNodeList::render().
Referenced by TemplateNodeCreate::render(), TemplateNodeExtend::render(), and TemplateNodeInclude::render().
render() [2/2]
void TemplateImpl::render (TextStream & ts, TemplateContext * c) [virtual]
Implements TemplateNode.
Member Data Documentation
m_blockContext
TemplateBlockContext TemplateImpl::m_blockContext [private]
Definition at line 2568 of file template.cpp.
Referenced by blockContext().
m_engine
TemplateEngine * TemplateImpl::m_engine = 0 [private]
Definition at line 2565 of file template.cpp.
Referenced by engine(), and TemplateImpl().
m_name
QCString TemplateImpl::m_name [private]
Definition at line 2566 of file template.cpp.
Referenced by TemplateImpl().
m_nodes
TemplateNodeList TemplateImpl::m_nodes [private]
Definition at line 2567 of file template.cpp.
Referenced by render(), and TemplateImpl().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp