DefineManager::DefinesPerFile Class Reference
Public Member Functions
DefinesPerFile (DefineManager *parent)
void addInclude (std::string fileName)
void store (const DefineMap &fromMap)
void retrieve (DefineMap &toMap)
void retrieveRec (DefineMap &toMap, StringSet &includeStack)
bool stored () const
DefinesPerFile (DefineManager *parent)
void addInclude (std::string fileName)
void store (const DefineMap &fromMap)
void retrieve (DefineMap &toMap)
void retrieveRec (DefineMap &toMap, StringSet &includeStack)
bool stored () const
Private Attributes
DefineManager * m_parent
DefineMap m_defines
StringSet m_includedFiles
bool m_stored = false
Detailed Description
Local class used to hold the defines for a single file
Definition at line 125 of file pre.l.
Constructor & Destructor Documentation
DefinesPerFile() [1/2]
DefineManager::DefinesPerFile::DefinesPerFile (DefineManager * parent) [inline]
Creates an empty container for defines
Definition at line 129 of file pre.l.
          : m_parent(parent)
        {
        }
DefinesPerFile() [2/2]
DefineManager::DefinesPerFile::DefinesPerFile (DefineManager * parent) [inline]
Creates an empty container for defines
Definition at line 129 of file pre.l.
          : m_parent(parent)
        {
        }
Member Function Documentation
addInclude() [1/2]
void DefineManager::DefinesPerFile::addInclude (std::string fileName) [inline]
Definition at line 133 of file pre.l.
        {
          m_includedFiles.insert(fileName);
        }
References m_includedFiles.
addInclude() [2/2]
void DefineManager::DefinesPerFile::addInclude (std::string fileName) [inline]
Definition at line 133 of file pre.l.
        {
          m_includedFiles.insert(fileName);
        }
References m_includedFiles.
retrieve() [1/2]
void DefineManager::DefinesPerFile::retrieve (DefineMap & toMap) [inline]
Definition at line 146 of file pre.l.
        {
          StringSet includeStack;
          retrieveRec(toMap,includeStack);
        }
References retrieveRec().
retrieve() [2/2]
void DefineManager::DefinesPerFile::retrieve (DefineMap & toMap) [inline]
Definition at line 146 of file pre.l.
        {
          StringSet includeStack;
          retrieveRec(toMap,includeStack);
        }
References retrieveRec().
retrieveRec() [1/2]
void DefineManager::DefinesPerFile::retrieveRec (DefineMap & toMap, StringSet & includeStack) [inline]
Definition at line 151 of file pre.l.
        {
          //printf(" retrieveRec #includedFiles=%zu\n",m_includedFiles.size());
          for (auto incFile : m_includedFiles)
          {
            DefinesPerFile *dpf = m_parent->find(incFile);
            if (dpf && includeStack.find(incFile)==includeStack.end())
            {
              includeStack.insert(incFile);
              dpf->retrieveRec(toMap,includeStack);
              //printf(" retrieveRec: processing include %s: #toMap=%zu\n",qPrint(incFile),toMap.size());
            }
          }
          for (auto &kv : m_defines)
          {
            toMap.emplace(kv.first,kv.second);
          }
        }
References DefineManager::find(), m_defines, m_includedFiles, m_parent, and retrieveRec().
Referenced by retrieve(), and retrieveRec().
retrieveRec() [2/2]
void DefineManager::DefinesPerFile::retrieveRec (DefineMap & toMap, StringSet & includeStack) [inline]
Definition at line 151 of file pre.l.
        {
          //printf(" retrieveRec #includedFiles=%zu\n",m_includedFiles.size());
          for (auto incFile : m_includedFiles)
          {
            DefinesPerFile *dpf = m_parent->find(incFile);
            if (dpf && includeStack.find(incFile)==includeStack.end())
            {
              includeStack.insert(incFile);
              dpf->retrieveRec(toMap,includeStack);
              //printf(" retrieveRec: processing include %s: #toMap=%zu\n",qPrint(incFile),toMap.size());
            }
          }
          for (auto &kv : m_defines)
          {
            toMap.emplace(kv.first,kv.second);
          }
        }
References DefineManager::find(), m_defines, m_includedFiles, and m_parent.
store() [1/2]
void DefineManager::DefinesPerFile::store (const DefineMap & fromMap) [inline]
Definition at line 137 of file pre.l.
        {
          for (auto &kv : fromMap)
          {
            m_defines.emplace(kv.first,kv.second);
          }
          //printf(" m_defines.size()=%zu\n",m_defines.size());
          m_stored=true;
        }
References m_defines, and m_stored.
store() [2/2]
void DefineManager::DefinesPerFile::store (const DefineMap & fromMap) [inline]
Definition at line 137 of file pre.l.
        {
          for (auto &kv : fromMap)
          {
            m_defines.emplace(kv.first,kv.second);
          }
          //printf(" m_defines.size()=%zu\n",m_defines.size());
          m_stored=true;
        }
References m_defines, and m_stored.
stored() [1/2]
bool DefineManager::DefinesPerFile::stored () const [inline]
Definition at line 169 of file pre.l.
{ return m_stored; }
References m_stored.
stored() [2/2]
bool DefineManager::DefinesPerFile::stored () const [inline]
Definition at line 169 of file pre.l.
{ return m_stored; }
References m_stored.
Member Data Documentation
m_defines
DefineMap DefineManager::DefinesPerFile::m_defines [private]
Definition at line 172 of file pre.l.
Referenced by retrieveRec(), and store().
m_includedFiles
StringSet DefineManager::DefinesPerFile::m_includedFiles [private]
Definition at line 173 of file pre.l.
Referenced by addInclude(), and retrieveRec().
m_parent
DefineManager * DefineManager::DefinesPerFile::m_parent [private]
Definition at line 171 of file pre.l.
Referenced by retrieveRec().
m_stored
bool DefineManager::DefinesPerFile::m_stored = false [private]
Definition at line 174 of file pre.l.
Referenced by store(), and stored().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/pre.l
doxygen/src/pre.l