SymbolIndexContext::Private Class Reference
Public Member Functions
Private (const std::string &letter, const SearchIndexList &sl, const QCString &name)
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private (const std::string &letter, const SearchIndexList &sl, const QCString &name)
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private Member Functions
TemplateVariant name () const
TemplateVariant letter () const
TemplateVariant symbolGroups () const
TemplateVariant createSymbolGroups () const
TemplateVariant name () const
TemplateVariant letter () const
TemplateVariant symbolGroups () const
TemplateVariant createSymbolGroups () const
Private Attributes
QCString m_letter
const SearchIndexList & m_searchList
QCString m_name
CachedItem< TemplateVariant, Private,&Private::createSymbolGroups > m_symbolGroups
Static Private Attributes
static const PropertyMap< SymbolIndexContext::Private > s_inst
Detailed Description
Definition at line 8660 of file context.cpp.
Constructor & Destructor Documentation
Private() [1/2]
SymbolIndexContext::Private::Private (const std::string & letter, const SearchIndexList & sl, const QCString & name) [inline]
Definition at line 8663 of file context.cpp.
      : m_letter(letter), m_searchList(sl), m_name(name) {}
Private() [2/2]
SymbolIndexContext::Private::Private (const std::string & letter, const SearchIndexList & sl, const QCString & name) [inline]
Definition at line 8663 of file context.cpp.
      : m_letter(letter), m_searchList(sl), m_name(name) {}
Member Function Documentation
createSymbolGroups() [1/2]
TemplateVariant SymbolIndexContext::Private::createSymbolGroups () const [inline], [private]
Definition at line 8677 of file context.cpp.
    {
      return SymbolGroupListContext::alloc(m_searchList);
    }
References SymbolGroupListContext::alloc(), and m_searchList.
createSymbolGroups() [2/2]
TemplateVariant SymbolIndexContext::Private::createSymbolGroups () const [inline], [private]
Definition at line 8677 of file context.cpp.
    {
      return SymbolGroupListContext::alloc(m_searchList);
    }
References SymbolGroupListContext::alloc().
fields() [1/2]
StringVector SymbolIndexContext::Private::fields () const [inline]
Definition at line 8667 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
fields() [2/2]
StringVector SymbolIndexContext::Private::fields () const [inline]
Definition at line 8667 of file context.cpp.
{ return s_inst.fields(); }
get() [1/2]
TemplateVariant SymbolIndexContext::Private::get (const QCString & n) const [inline]
Definition at line 8666 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), n, and s_inst.
get() [2/2]
TemplateVariant SymbolIndexContext::Private::get (const QCString & n) const [inline]
Definition at line 8666 of file context.cpp.
{ return s_inst.get(this,n); }
References n.
letter() [1/2]
TemplateVariant SymbolIndexContext::Private::letter () const [inline], [private]
Definition at line 8672 of file context.cpp.
{ return m_letter; }
References m_letter.
letter() [2/2]
TemplateVariant SymbolIndexContext::Private::letter () const [inline], [private]
Definition at line 8672 of file context.cpp.
{ return m_letter; }
name() [1/2]
TemplateVariant SymbolIndexContext::Private::name () const [inline], [private]
Definition at line 8671 of file context.cpp.
{ return m_name; }
References m_name.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
name() [2/2]
TemplateVariant SymbolIndexContext::Private::name () const [inline], [private]
Definition at line 8671 of file context.cpp.
{ return m_name; }
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
symbolGroups() [1/2]
TemplateVariant SymbolIndexContext::Private::symbolGroups () const [inline], [private]
Definition at line 8673 of file context.cpp.
{ return m_symbolGroups.get(this); }
References m_symbolGroups.
symbolGroups() [2/2]
TemplateVariant SymbolIndexContext::Private::symbolGroups () const [inline], [private]
Definition at line 8673 of file context.cpp.
{ return m_symbolGroups.get(this); }
Member Data Documentation
m_letter
QCString SymbolIndexContext::Private::m_letter [private]
Definition at line 8681 of file context.cpp.
Referenced by letter().
m_name
QCString SymbolIndexContext::Private::m_name [private]
Definition at line 8683 of file context.cpp.
Referenced by name().
m_searchList
const SearchIndexList & SymbolIndexContext::Private::m_searchList [private]
Definition at line 8682 of file context.cpp.
Referenced by createSymbolGroups().
m_symbolGroups
CachedItem< TemplateVariant, Private,&Private::createSymbolGroups > SymbolIndexContext::Private::m_symbolGroups [private]
Definition at line 8684 of file context.cpp.
Referenced by symbolGroups().
s_inst
const PropertyMap< SymbolIndexContext::Private > SymbolIndexContext::Private::s_inst [static], [private]
Initial value:
{
  { "name", &Private::name },
  { "letter", &Private::letter },
  { "symbolGroups",&Private::symbolGroups },
}
Definition at line 8685 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp