VHDLCodeParser Class Reference
#include <vhdlcode.h>
Classes
struct Private
Public Member Functions
VHDLCodeParser ()
virtual ~VHDLCodeParser ()
void parseCode (CodeOutputInterface &codeOutIntf, const QCString &scopeName, const QCString &input, SrcLangExt lang, bool isExampleBlock, const QCString &exampleName=QCString(), const FileDef *fileDef=0, int startLine=-1, int endLine=-1, bool inlineFragment=FALSE, const MemberDef *memberDef=0, bool showLineNumbers=TRUE, const Definition *searchCtx=0, bool collectXRefs=TRUE)
void resetCodeParserState ()
VHDLCodeParser ()
virtual ~VHDLCodeParser ()
void parseCode (CodeOutputInterface &codeOutIntf, const QCString &scopeName, const QCString &input, SrcLangExt lang, bool isExampleBlock, const QCString &exampleName=QCString(), const FileDef *fileDef=0, int startLine=-1, int endLine=-1, bool inlineFragment=FALSE, const MemberDef *memberDef=0, bool showLineNumbers=TRUE, const Definition *searchCtx=0, bool collectXRefs=TRUE)
void resetCodeParserState ()
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Definition at line 26 of file vhdlcode.h.
Constructor & Destructor Documentation
VHDLCodeParser() [1/2]
VHDLCodeParser::VHDLCodeParser ()
Definition at line 1565 of file vhdlcode.l.
                               : p(std::make_unique<Private>())
{
  vhdlcodeYYlex_init_extra(&p->state,&p->yyscanner);
#ifdef FLEX_DEBUG
  vhdlcodeYYset_debug(1,p->yyscanner);
#endif
  resetCodeParserState();
}
References p, and resetCodeParserState().
 VHDLCodeParser() [1/2]
VHDLCodeParser::~VHDLCodeParser () [virtual]
Definition at line 1574 of file vhdlcode.l.
{
  vhdlcodeYYlex_destroy(p->yyscanner);
}
References p.
VHDLCodeParser() [2/2]
VHDLCodeParser::VHDLCodeParser ()
 VHDLCodeParser() [2/2]
virtual VHDLCodeParser::~VHDLCodeParser () [virtual]
Member Function Documentation
parseCode() [1/2]
void VHDLCodeParser::parseCode (CodeOutputInterface & codeOutIntf, const QCString & scopeName, const QCString & input, SrcLangExt lang, bool isExampleBlock, const QCString & exampleName = QCString(), const FileDef * fileDef = 0, int startLine = -1, int endLine = -1, bool inlineFragment = FALSE, const MemberDef * memberDef = 0, bool showLineNumbers = TRUE, const Definition * searchCtx = 0, bool collectXRefs = TRUE) [virtual]
Parses a source file or fragment with the goal to produce highlighted and cross-referenced output.
Parameters
 in codeOutIntf Abstract interface for writing the result.
 in scopeName Name of scope to which the code belongs.
 in input Actual code in the form of a string
 in lang The programming language of the code fragment.
 in isExampleBlock TRUE iff the code is part of an example.
 in exampleName Name of the example.
 in fileDef File definition to which the code is associated.
 in startLine Starting line in case of a code fragment.
 in endLine Ending line of the code fragment.
 in inlineFragment Code fragment that is to be shown inline as part of the documentation.
 in memberDef Member definition to which the code is associated (non null in case of an inline fragment for a member).
 in showLineNumbers if set to TRUE and also fileDef is not 0, line numbers will be added to the source fragment
 in searchCtx context under which search data has to be stored.
 in collectXRefs collect cross-reference relations.
Implements CodeParserInterface.
Definition at line 1584 of file vhdlcode.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  //printf("***parseCode() exBlock=%d exName=%s fd=%p\n",exBlock,exName,fd);
  if (s.isEmpty()) return;
  printlex(yy_flex_debug, true, __FILE__, fd ? qPrint(fd->fileName()): NULL);
  yyextra->fileName = fd ? fd->fileName():"";
  if (memberDef)
  {
    const ClassDef *dd=memberDef->getClassDef();
    if (dd) yyextra->currClass=dd->name();
  }
  resetCodeParserState();
  yyextra->code = &od;
  yyextra->inputString = s.data();
  yyextra->inputPosition = 0;
  yyextra->currentFontClass = 0;
  yyextra->insideCodeLine = false;
  yyextra->searchCtx = searchCtx;
  if (startLine!=-1)
    yyextra->yyLineNr = startLine;
  else
    yyextra->yyLineNr = 1;
  if (endLine!=-1)
    yyextra->inputLines = endLine+1;
  else
    yyextra->inputLines = yyextra->yyLineNr + countLines(yyscanner) - 1;
  // yyextra->theCallContext.clear();
  yyextra->exampleBlock = exBlock;
  yyextra->exampleName = exName;
  yyextra->sourceFileDef = fd;
  bool cleanupSourceDef = false;
  if (exBlock && fd==0)
  {
    // create a dummy filedef for the example
    yyextra->sourceFileDef = createFileDef("",exName);
    cleanupSourceDef = true;
  }
  if (yyextra->sourceFileDef)
  {
    setCurrentDoc(yyscanner,"l00001");
  }
  yyextra->currentDefinition = 0;
  yyextra->currentMemberDef = 0;
  yyextra->vhdlMember=0;
  if (!yyextra->exampleName.isEmpty())
  {
    yyextra->exampleFile = convertNameToFile(yyextra->exampleName+"-example");
  }
  yyextra->includeCodeFragment = inlineFragment;
  startCodeLine(yyscanner);
  if (!yyextra->lexInit)
  {
    VhdlDocGen::init();
    yyextra->lexInit=true;
  }
  vhdlcodeYYrestart(0, yyscanner);
  BEGIN(Bases);
  vhdlcodeYYlex(yyscanner);
  if (yyextra->insideCodeLine)
  {
    endCodeLine(yyscanner);
  }
  if (cleanupSourceDef)
  {
    // delete the temporary file definition used for this example
    delete yyextra->sourceFileDef;
    yyextra->sourceFileDef=0;
  }
  // write the tooltips
  yyextra->tooltipManager.writeTooltips(od);
  printlex(yy_flex_debug, false, __FILE__, fd ? qPrint(fd->fileName()): NULL);
}
References convertNameToFile(), countLines(), createFileDef(), gdFont::data, endCodeLine(), FileDef::fileName(), MemberDef::getClassDef(), VhdlDocGen::init(), Definition::name(), p, printlex(), qPrint(), resetCodeParserState(), s, setCurrentDoc(), and startCodeLine().
parseCode() [2/2]
void VHDLCodeParser::parseCode (CodeOutputInterface & codeOutIntf, const QCString & scopeName, const QCString & input, SrcLangExt lang, bool isExampleBlock, const QCString & exampleName = QCString(), const FileDef * fileDef = 0, int startLine = -1, int endLine = -1, bool inlineFragment = FALSE, const MemberDef * memberDef = 0, bool showLineNumbers = TRUE, const Definition * searchCtx = 0, bool collectXRefs = TRUE) [virtual]
Parses a source file or fragment with the goal to produce highlighted and cross-referenced output.
Parameters
 in codeOutIntf Abstract interface for writing the result.
 in scopeName Name of scope to which the code belongs.
 in input Actual code in the form of a string
 in lang The programming language of the code fragment.
 in isExampleBlock TRUE iff the code is part of an example.
 in exampleName Name of the example.
 in fileDef File definition to which the code is associated.
 in startLine Starting line in case of a code fragment.
 in endLine Ending line of the code fragment.
 in inlineFragment Code fragment that is to be shown inline as part of the documentation.
 in memberDef Member definition to which the code is associated (non null in case of an inline fragment for a member).
 in showLineNumbers if set to TRUE and also fileDef is not 0, line numbers will be added to the source fragment
 in searchCtx context under which search data has to be stored.
 in collectXRefs collect cross-reference relations.
Implements CodeParserInterface.
resetCodeParserState() [1/2]
void VHDLCodeParser::resetCodeParserState () [virtual]
Resets the state of the code parser. Since multiple code fragments can together form a single example, an explicit function is used to reset the code parser state.
See also
parseCode()
Implements CodeParserInterface.
Definition at line 1579 of file vhdlcode.l.
{
  p->state.vhdlKeyDict.clear();
}
References p.
Referenced by parseCode(), and VHDLCodeParser().
resetCodeParserState() [2/2]
void VHDLCodeParser::resetCodeParserState () [virtual]
Resets the state of the code parser. Since multiple code fragments can together form a single example, an explicit function is used to reset the code parser state.
See also
parseCode()
Implements CodeParserInterface.
Member Data Documentation
p
std::unique_ptr< Private > VHDLCodeParser::p [private]
Definition at line 49 of file vhdlcode.h.
Referenced by parseCode(), resetCodeParserState(), VHDLCodeParser(), and ~VHDLCodeParser().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/vhdlcode.h
doxygen/src/vhdlcode.h
doxygen/build/doxygen/src/vhdlcode.l
doxygen/src/vhdlcode.l