DocLink Class Reference
#include <docnode.h>
Public Member Functions
DocLink (DocParser *parser, DocNodeVariant *parent, const QCString &target)
QCString parse (DocNodeVariant *, bool, bool isXmlLink=FALSE)
QCString file () const
QCString relPath () const
QCString ref () const
QCString anchor () const
DocLink (DocParser *parser, DocNodeVariant *parent, const QCString &target)
QCString parse (DocNodeVariant *, bool, bool isXmlLink=FALSE)
QCString file () const
QCString relPath () const
QCString ref () const
QCString anchor () const
Private Attributes
QCString m_file
QCString m_relPath
QCString m_ref
QCString m_anchor
QCString m_refText
Additional Inherited Members
Detailed Description
Node representing a link to some item
Definition at line 713 of file docnode.h.
Constructor & Destructor Documentation
DocLink() [1/2]
DocLink::DocLink (DocParser * parser, DocNodeVariant * parent, const QCString & target)
Definition at line 882 of file docnode.cpp.
                                                                                : DocCompoundNode(parser,parent)
{
  const Definition *compound = 0;
  QCString anchor;
  m_refText = target;
  m_relPath = parser->context.relPath;
  if (!m_refText.isEmpty() && m_refText.at(0)=='#')
  {
    m_refText = m_refText.right(m_refText.length()-1);
  }
  if (resolveLink(parser->context.context,stripKnownExtensions(target),parser->context.inSeeBlock,&compound,anchor))
  {
    m_anchor = anchor;
    if (compound && compound->isLinkable())
    {
      m_file = compound->getOutputFileBase();
      m_ref = compound->getReference();
    }
    else if (compound && compound->definitionType()==Definition::TypeFile &&
             (toFileDef(compound))->generateSourceFile()
            ) // undocumented file that has source code we can link to
    {
      m_file = compound->getSourceFileBase();
      m_ref = compound->getReference();
    }
    return;
  }
  // bogus link target
  warn_doc_error(parser->context.fileName,parser->tokenizer.getLineNr(),"unable to resolve link to '%s' for \\link command",
         qPrint(target));
}
References anchor(), QCString::at(), DocParserContext::context, DocParser::context, Definition::definitionType(), DocParserContext::fileName, DocTokenizer::getLineNr(), Definition::getOutputFileBase(), Definition::getReference(), Definition::getSourceFileBase(), DocParserContext::inSeeBlock, QCString::isEmpty(), Definition::isLinkable(), QCString::length(), m_anchor, m_file, m_ref, m_refText, m_relPath, DocNode::parser(), qPrint(), DocParserContext::relPath, resolveLink(), QCString::right(), stripKnownExtensions(), toFileDef(), DocParser::tokenizer, Definition::TypeFile, and warn_doc_error().
DocLink() [2/2]
DocLink::DocLink (DocParser * parser, DocNodeVariant * parent, const QCString & target)
Member Function Documentation
anchor() [1/2]
QCString DocLink::anchor () const [inline]
Definition at line 721 of file docnode.h.
{ return m_anchor; }
References m_anchor.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), DocLink(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), PerlModDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), LatexDocVisitor::operator()(), PrintDocVisitor::operator()(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
anchor() [2/2]
QCString DocLink::anchor () const [inline]
Definition at line 721 of file docnode.h.
{ return m_anchor; }
References m_anchor.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
file() [1/2]
QCString DocLink::file () const [inline]
Definition at line 718 of file docnode.h.
{ return m_file; }
References m_file.
Referenced by doxmlparser.compound.locationType::__init__(), doxmlparser.compound.locationType::buildAttributes(), doxmlparser.compound.locationType::exportAttributes(), doxmlparser.compound.locationType::get_file(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), PerlModDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), LatexDocVisitor::operator()(), PrintDocVisitor::operator()(), and doxmlparser.compound.locationType::set_file().
file() [2/2]
QCString DocLink::file () const [inline]
Definition at line 718 of file docnode.h.
{ return m_file; }
References m_file.
Referenced by doxmlparser.compound.locationType::__init__(), doxmlparser.compound.locationType::buildAttributes(), doxmlparser.compound.locationType::exportAttributes(), doxmlparser.compound.locationType::get_file(), and doxmlparser.compound.locationType::set_file().
parse() [1/2]
QCString DocLink::parse (DocNodeVariant * thisVariant, bool isJavaLink, bool isXmlLink = FALSE)
Definition at line 916 of file docnode.cpp.
{
  QCString result;
  auto ns = AutoNodeStack(parser(),thisVariant);
  DBG(("DocLink::parse() start\n"));
  int tok;
  while ((tok=parser()->tokenizer.lex()))
  {
    if (!parser()->defaultHandleToken(thisVariant,tok,children(),FALSE))
    {
      const char *cmd_start = "\\";
      switch (tok)
      {
        case TK_COMMAND_AT:
          cmd_start = "@";
        // fall through
        case TK_COMMAND_BS:
          switch (Mappers::cmdMapper->map(parser()->context.token->name))
          {
            case CMD_ENDLINK:
              if (isJavaLink)
              {
                warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"{@link.. ended with @endlink command");
              }
              goto endlink;
            default:
              warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"Illegal command %s as part of a \\link",
                  qPrint(cmd_start + parser()->context.token->name));
              break;
          }
          break;
        case TK_SYMBOL:
          warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"Unsupported symbol %s found as part of a \\link",
              qPrint(parser()->context.token->name));
          break;
        case TK_HTMLTAG:
          if (parser()->context.token->name!="see" || !isXmlLink)
          {
            warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"Unexpected xml/html command %s found as part of a \\link",
                qPrint(parser()->context.token->name));
          }
          goto endlink;
        case TK_LNKWORD:
        case TK_WORD:
          if (isJavaLink) // special case to detect closing }
          {
            QCString w = parser()->context.token->name;
            int p;
            if (w=="}")
            {
              goto endlink;
            }
            else if ((p=w.find('}'))!=-1)
            {
              uint l=w.length();
              children().append<DocWord>(parser(),thisVariant,w.left(p));
              if (static_cast<uint>(p)<l-1) // something left after the } (for instance a .)
              {
                result=w.right(static_cast<int>(l)-p-1);
              }
              goto endlink;
            }
          }
          children().append<DocWord>(parser(),thisVariant,parser()->context.token->name);
          break;
        default:
          warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"Unexpected token %s",
             DocTokenizer::tokToString(tok));
        break;
      }
    }
  }
  if (tok==0)
  {
    warn_doc_error(parser()->context.fileName,
                   parser()->tokenizer.getLineNr(),
                   "Unexpected end of comment while inside link command\n");
  }
endlink:
  if (children().empty()) // no link text
  {
    children().append<DocWord>(parser(),thisVariant,m_refText);
  }
  parser()->handlePendingStyleCommands(thisVariant,children());
  DBG(("DocLink::parse() end\n"));
  return result;
}
References DocNodeList::append(), DocCompoundNode::children(), CMD_ENDLINK, Mappers::cmdMapper, DocParser::context, DBG, FALSE, DocParser::handlePendingStyleCommands(), m_refText, TokenInfo::name, p, DocNode::parser(), qPrint(), TK_COMMAND_AT, TK_COMMAND_BS, TK_HTMLTAG, TK_LNKWORD, TK_SYMBOL, TK_WORD, DocParserContext::token, DocTokenizer::tokToString(), w, and warn_doc_error().
parse() [2/2]
QCString DocLink::parse (DocNodeVariant * , bool , bool isXmlLink = FALSE)
ref() [1/2]
QCString DocLink::ref () const [inline]
Definition at line 720 of file docnode.h.
{ return m_ref; }
References m_ref.
Referenced by doxmlparser.compound.highlightType::__init__(), doxmlparser.compound.docParamName::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.linkedTextType::__init__(), doxmlparser.compound.docParamType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.linkedTextType::add_ref(), doxmlparser.compound.highlightType::add_ref(), doxmlparser.compound.docTitleType::add_ref(), doxmlparser.compound.docSummaryType::add_ref(), doxmlparser.compound.docParaType::add_ref(), doxmlparser.compound.docMarkupType::add_ref(), doxmlparser.compound.docURLLink::add_ref(), doxmlparser.compound.docRefTextType::add_ref(), doxmlparser.compound.docCaptionType::add_ref(), doxmlparser.compound.docHeadingType::add_ref(), doxmlparser.compound.docImageType::add_ref(), doxmlparser.compound.docDotMscType::add_ref(), doxmlparser.compound.docImageFileType::add_ref(), doxmlparser.compound.docPlantumlType::add_ref(), doxmlparser.compound.docTocItemType::add_ref(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docParamName::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.highlightType::exportChildren(), doxmlparser.compound.linkedTextType::get_ref(), doxmlparser.compound.highlightType::get_ref(), doxmlparser.compound.docTitleType::get_ref(), doxmlparser.compound.docSummaryType::get_ref(), doxmlparser.compound.docParaType::get_ref(), doxmlparser.compound.docMarkupType::get_ref(), doxmlparser.compound.docURLLink::get_ref(), doxmlparser.compound.docRefTextType::get_ref(), doxmlparser.compound.docCaptionType::get_ref(), doxmlparser.compound.docHeadingType::get_ref(), doxmlparser.compound.docImageType::get_ref(), doxmlparser.compound.docDotMscType::get_ref(), doxmlparser.compound.docImageFileType::get_ref(), doxmlparser.compound.docPlantumlType::get_ref(), doxmlparser.compound.docTocItemType::get_ref(), doxmlparser.compound.docParamType::get_ref(), doxmlparser.compound.docParamName::get_ref(), doxmlparser.compound.linkedTextType::hasContent_(), doxmlparser.compound.highlightType::hasContent_(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docParamType::hasContent_(), doxmlparser.compound.docParamName::hasContent_(), doxmlparser.compound.linkedTextType::insert_ref_at(), doxmlparser.compound.highlightType::insert_ref_at(), doxmlparser.compound.docTitleType::insert_ref_at(), doxmlparser.compound.docSummaryType::insert_ref_at(), doxmlparser.compound.docParaType::insert_ref_at(), doxmlparser.compound.docMarkupType::insert_ref_at(), doxmlparser.compound.docURLLink::insert_ref_at(), doxmlparser.compound.docRefTextType::insert_ref_at(), doxmlparser.compound.docCaptionType::insert_ref_at(), doxmlparser.compound.docHeadingType::insert_ref_at(), doxmlparser.compound.docImageType::insert_ref_at(), doxmlparser.compound.docDotMscType::insert_ref_at(), doxmlparser.compound.docImageFileType::insert_ref_at(), doxmlparser.compound.docPlantumlType::insert_ref_at(), doxmlparser.compound.docTocItemType::insert_ref_at(), HtmlDocVisitor::operator()(), PerlModDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), LatexDocVisitor::operator()(), PrintDocVisitor::operator()(), doxmlparser.compound.linkedTextType::replace_ref_at(), doxmlparser.compound.highlightType::replace_ref_at(), doxmlparser.compound.docTitleType::replace_ref_at(), doxmlparser.compound.docSummaryType::replace_ref_at(), doxmlparser.compound.docParaType::replace_ref_at(), doxmlparser.compound.docMarkupType::replace_ref_at(), doxmlparser.compound.docURLLink::replace_ref_at(), doxmlparser.compound.docRefTextType::replace_ref_at(), doxmlparser.compound.docCaptionType::replace_ref_at(), doxmlparser.compound.docHeadingType::replace_ref_at(), doxmlparser.compound.docImageType::replace_ref_at(), doxmlparser.compound.docDotMscType::replace_ref_at(), doxmlparser.compound.docImageFileType::replace_ref_at(), doxmlparser.compound.docPlantumlType::replace_ref_at(), doxmlparser.compound.docTocItemType::replace_ref_at(), doxmlparser.compound.linkedTextType::set_ref(), doxmlparser.compound.highlightType::set_ref(), doxmlparser.compound.docTitleType::set_ref(), doxmlparser.compound.docSummaryType::set_ref(), doxmlparser.compound.docParaType::set_ref(), doxmlparser.compound.docMarkupType::set_ref(), doxmlparser.compound.docURLLink::set_ref(), doxmlparser.compound.docRefTextType::set_ref(), doxmlparser.compound.docCaptionType::set_ref(), doxmlparser.compound.docHeadingType::set_ref(), doxmlparser.compound.docImageType::set_ref(), doxmlparser.compound.docDotMscType::set_ref(), doxmlparser.compound.docImageFileType::set_ref(), doxmlparser.compound.docPlantumlType::set_ref(), doxmlparser.compound.docTocItemType::set_ref(), doxmlparser.compound.docParamType::set_ref(), and doxmlparser.compound.docParamName::set_ref().
ref() [2/2]
QCString DocLink::ref () const [inline]
Definition at line 720 of file docnode.h.
{ return m_ref; }
References m_ref.
Referenced by doxmlparser.compound.highlightType::__init__(), doxmlparser.compound.docParamName::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.linkedTextType::__init__(), doxmlparser.compound.docParamType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.linkedTextType::add_ref(), doxmlparser.compound.highlightType::add_ref(), doxmlparser.compound.docTitleType::add_ref(), doxmlparser.compound.docSummaryType::add_ref(), doxmlparser.compound.docParaType::add_ref(), doxmlparser.compound.docMarkupType::add_ref(), doxmlparser.compound.docURLLink::add_ref(), doxmlparser.compound.docRefTextType::add_ref(), doxmlparser.compound.docCaptionType::add_ref(), doxmlparser.compound.docHeadingType::add_ref(), doxmlparser.compound.docImageType::add_ref(), doxmlparser.compound.docDotMscType::add_ref(), doxmlparser.compound.docImageFileType::add_ref(), doxmlparser.compound.docPlantumlType::add_ref(), doxmlparser.compound.docTocItemType::add_ref(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docParamName::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.highlightType::exportChildren(), doxmlparser.compound.linkedTextType::get_ref(), doxmlparser.compound.highlightType::get_ref(), doxmlparser.compound.docTitleType::get_ref(), doxmlparser.compound.docSummaryType::get_ref(), doxmlparser.compound.docParaType::get_ref(), doxmlparser.compound.docMarkupType::get_ref(), doxmlparser.compound.docURLLink::get_ref(), doxmlparser.compound.docRefTextType::get_ref(), doxmlparser.compound.docCaptionType::get_ref(), doxmlparser.compound.docHeadingType::get_ref(), doxmlparser.compound.docImageType::get_ref(), doxmlparser.compound.docDotMscType::get_ref(), doxmlparser.compound.docImageFileType::get_ref(), doxmlparser.compound.docPlantumlType::get_ref(), doxmlparser.compound.docTocItemType::get_ref(), doxmlparser.compound.docParamType::get_ref(), doxmlparser.compound.docParamName::get_ref(), doxmlparser.compound.linkedTextType::hasContent_(), doxmlparser.compound.highlightType::hasContent_(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docParamType::hasContent_(), doxmlparser.compound.docParamName::hasContent_(), doxmlparser.compound.linkedTextType::insert_ref_at(), doxmlparser.compound.highlightType::insert_ref_at(), doxmlparser.compound.docTitleType::insert_ref_at(), doxmlparser.compound.docSummaryType::insert_ref_at(), doxmlparser.compound.docParaType::insert_ref_at(), doxmlparser.compound.docMarkupType::insert_ref_at(), doxmlparser.compound.docURLLink::insert_ref_at(), doxmlparser.compound.docRefTextType::insert_ref_at(), doxmlparser.compound.docCaptionType::insert_ref_at(), doxmlparser.compound.docHeadingType::insert_ref_at(), doxmlparser.compound.docImageType::insert_ref_at(), doxmlparser.compound.docDotMscType::insert_ref_at(), doxmlparser.compound.docImageFileType::insert_ref_at(), doxmlparser.compound.docPlantumlType::insert_ref_at(), doxmlparser.compound.docTocItemType::insert_ref_at(), doxmlparser.compound.linkedTextType::replace_ref_at(), doxmlparser.compound.highlightType::replace_ref_at(), doxmlparser.compound.docTitleType::replace_ref_at(), doxmlparser.compound.docSummaryType::replace_ref_at(), doxmlparser.compound.docParaType::replace_ref_at(), doxmlparser.compound.docMarkupType::replace_ref_at(), doxmlparser.compound.docURLLink::replace_ref_at(), doxmlparser.compound.docRefTextType::replace_ref_at(), doxmlparser.compound.docCaptionType::replace_ref_at(), doxmlparser.compound.docHeadingType::replace_ref_at(), doxmlparser.compound.docImageType::replace_ref_at(), doxmlparser.compound.docDotMscType::replace_ref_at(), doxmlparser.compound.docImageFileType::replace_ref_at(), doxmlparser.compound.docPlantumlType::replace_ref_at(), doxmlparser.compound.docTocItemType::replace_ref_at(), doxmlparser.compound.linkedTextType::set_ref(), doxmlparser.compound.highlightType::set_ref(), doxmlparser.compound.docTitleType::set_ref(), doxmlparser.compound.docSummaryType::set_ref(), doxmlparser.compound.docParaType::set_ref(), doxmlparser.compound.docMarkupType::set_ref(), doxmlparser.compound.docURLLink::set_ref(), doxmlparser.compound.docRefTextType::set_ref(), doxmlparser.compound.docCaptionType::set_ref(), doxmlparser.compound.docHeadingType::set_ref(), doxmlparser.compound.docImageType::set_ref(), doxmlparser.compound.docDotMscType::set_ref(), doxmlparser.compound.docImageFileType::set_ref(), doxmlparser.compound.docPlantumlType::set_ref(), doxmlparser.compound.docTocItemType::set_ref(), doxmlparser.compound.docParamType::set_ref(), and doxmlparser.compound.docParamName::set_ref().
relPath() [1/2]
QCString DocLink::relPath () const [inline]
Definition at line 719 of file docnode.h.
{ return m_relPath; }
References m_relPath.
Referenced by HtmlDocVisitor::operator()().
relPath() [2/2]
QCString DocLink::relPath () const [inline]
Definition at line 719 of file docnode.h.
{ return m_relPath; }
References m_relPath.
Member Data Documentation
m_anchor
QCString DocLink::m_anchor [private]
Definition at line 727 of file docnode.h.
Referenced by anchor(), and DocLink().
m_file
QCString DocLink::m_file [private]
Definition at line 724 of file docnode.h.
Referenced by DocLink(), and file().
m_ref
QCString DocLink::m_ref [private]
Definition at line 726 of file docnode.h.
Referenced by DocLink(), and ref().
m_refText
QCString DocLink::m_refText [private]
Definition at line 728 of file docnode.h.
Referenced by DocLink(), and parse().
m_relPath
QCString DocLink::m_relPath [private]
Definition at line 725 of file docnode.h.
Referenced by DocLink(), and relPath().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docnode.h
doxygen/src/docnode.h
doxygen/build/doxygen/src/docnode.cpp
doxygen/src/docnode.cpp