TextDocVisitor Class Reference
Concrete visitor implementation for TEXT output.
#include <textdocvisitor.h>
Public Member Functions
TextDocVisitor (TextStream &t)
void operator() (const DocWord &w)
void operator() (const DocLinkedWord &w)
void operator() (const DocWhiteSpace &)
void operator() (const DocSymbol &)
void operator() (const DocEmoji &)
void operator() (const DocURL &u)
void operator() (const DocLineBreak &)
void operator() (const DocHorRuler &)
void operator() (const DocStyleChange &)
void operator() (const DocVerbatim &s)
void operator() (const DocAnchor &)
void operator() (const DocInclude &)
void operator() (const DocIncOperator &)
void operator() (const DocFormula &)
void operator() (const DocIndexEntry &)
void operator() (const DocSimpleSectSep &)
void operator() (const DocCite &)
void operator() (const DocSeparator &)
template<class T >
void visitChildren (const T &t)
void operator() (const DocAutoList &l)
void operator() (const DocAutoListItem &li)
void operator() (const DocPara &p)
void operator() (const DocRoot &r)
void operator() (const DocSimpleSect &s)
void operator() (const DocTitle &t)
void operator() (const DocSimpleList &l)
void operator() (const DocSimpleListItem &)
void operator() (const DocSection &s)
void operator() (const DocHtmlList &l)
void operator() (const DocHtmlListItem &li)
void operator() (const DocHtmlDescList &dl)
void operator() (const DocHtmlDescTitle &dt)
void operator() (const DocHtmlDescData &dd)
void operator() (const DocHtmlTable &t)
void operator() (const DocHtmlRow &r)
void operator() (const DocHtmlCell &c)
void operator() (const DocHtmlCaption &c)
void operator() (const DocInternal &i)
void operator() (const DocHRef &h)
void operator() (const DocHtmlSummary &s)
void operator() (const DocHtmlDetails &d)
void operator() (const DocHtmlHeader &h)
void operator() (const DocImage &i)
void operator() (const DocDotFile &df)
void operator() (const DocMscFile &df)
void operator() (const DocDiaFile &df)
void operator() (const DocLink &l)
void operator() (const DocRef &r)
void operator() (const DocSecRefItem &s)
void operator() (const DocSecRefList &l)
void operator() (const DocParamSect &s)
void operator() (const DocParamList &)
void operator() (const DocXRefItem &x)
void operator() (const DocInternalRef &r)
void operator() (const DocText &t)
void operator() (const DocHtmlBlockQuote &q)
void operator() (const DocVhdlFlow &)
void operator() (const DocParBlock &pb)
TextDocVisitor (TextStream &t)
void operator() (const DocWord &w)
void operator() (const DocLinkedWord &w)
void operator() (const DocWhiteSpace &)
void operator() (const DocSymbol &)
void operator() (const DocEmoji &)
void operator() (const DocURL &u)
void operator() (const DocLineBreak &)
void operator() (const DocHorRuler &)
void operator() (const DocStyleChange &)
void operator() (const DocVerbatim &s)
void operator() (const DocAnchor &)
void operator() (const DocInclude &)
void operator() (const DocIncOperator &)
void operator() (const DocFormula &)
void operator() (const DocIndexEntry &)
void operator() (const DocSimpleSectSep &)
void operator() (const DocCite &)
void operator() (const DocSeparator &)
template<class T >
void visitChildren (const T &t)
void operator() (const DocAutoList &l)
void operator() (const DocAutoListItem &li)
void operator() (const DocPara &p)
void operator() (const DocRoot &r)
void operator() (const DocSimpleSect &s)
void operator() (const DocTitle &t)
void operator() (const DocSimpleList &l)
void operator() (const DocSimpleListItem &)
void operator() (const DocSection &s)
void operator() (const DocHtmlList &l)
void operator() (const DocHtmlListItem &li)
void operator() (const DocHtmlDescList &dl)
void operator() (const DocHtmlDescTitle &dt)
void operator() (const DocHtmlDescData &dd)
void operator() (const DocHtmlTable &t)
void operator() (const DocHtmlRow &r)
void operator() (const DocHtmlCell &c)
void operator() (const DocHtmlCaption &c)
void operator() (const DocInternal &i)
void operator() (const DocHRef &h)
void operator() (const DocHtmlSummary &s)
void operator() (const DocHtmlDetails &d)
void operator() (const DocHtmlHeader &h)
void operator() (const DocImage &i)
void operator() (const DocDotFile &df)
void operator() (const DocMscFile &df)
void operator() (const DocDiaFile &df)
void operator() (const DocLink &l)
void operator() (const DocRef &r)
void operator() (const DocSecRefItem &s)
void operator() (const DocSecRefList &l)
void operator() (const DocParamSect &s)
void operator() (const DocParamList &)
void operator() (const DocXRefItem &x)
void operator() (const DocInternalRef &r)
void operator() (const DocText &t)
void operator() (const DocHtmlBlockQuote &q)
void operator() (const DocVhdlFlow &)
void operator() (const DocParBlock &pb)
Private Member Functions
void filter (const QCString &str)
void filter (const QCString &str)
Private Attributes
TextStream & m_t
Detailed Description
Concrete visitor implementation for TEXT output.
Definition at line 28 of file textdocvisitor.h.
Constructor & Destructor Documentation
TextDocVisitor() [1/2]
TextDocVisitor::TextDocVisitor (TextStream & t) [inline]
Definition at line 31 of file textdocvisitor.h.
: m_t(t) {}
TextDocVisitor() [2/2]
TextDocVisitor::TextDocVisitor (TextStream & t) [inline]
Definition at line 31 of file textdocvisitor.h.
: m_t(t) {}
Member Function Documentation
filter() [1/2]
void TextDocVisitor::filter (const QCString & str) [private]
Definition at line 53 of file textdocvisitor.cpp.
{
  if (str.isEmpty()) return;
  //printf("TextDocVisitor::filter(%s)\n",str);
  const char *p=str.data();
  char c;
  while (*p)
  {
    c=*p++;
    switch(c)
    {
      case '\n': m_t << " "; break;
      default: m_t << c;
    }
  }
}
References c, QCString::data(), QCString::isEmpty(), m_t, and p.
Referenced by operator()().
filter() [2/2]
void TextDocVisitor::filter (const QCString & str) [private]
operator()() [1/114]
void TextDocVisitor::operator() (const DocAnchor &) [inline]
Definition at line 47 of file textdocvisitor.h.
{}
operator()() [2/114]
void TextDocVisitor::operator() (const DocAnchor &) [inline]
Definition at line 47 of file textdocvisitor.h.
{}
operator()() [3/114]
void TextDocVisitor::operator() (const DocAutoList & l) [inline]
Definition at line 68 of file textdocvisitor.h.
{ visitChildren(l); }
References visitChildren().
operator()() [4/114]
void TextDocVisitor::operator() (const DocAutoList & l) [inline]
Definition at line 68 of file textdocvisitor.h.
{ visitChildren(l); }
References visitChildren().
operator()() [5/114]
void TextDocVisitor::operator() (const DocAutoListItem & li) [inline]
Definition at line 69 of file textdocvisitor.h.
{ visitChildren(li); }
References visitChildren().
operator()() [6/114]
void TextDocVisitor::operator() (const DocAutoListItem & li) [inline]
Definition at line 69 of file textdocvisitor.h.
{ visitChildren(li); }
References visitChildren().
operator()() [7/114]
void TextDocVisitor::operator() (const DocCite &) [inline]
Definition at line 53 of file textdocvisitor.h.
{}
operator()() [8/114]
void TextDocVisitor::operator() (const DocCite &) [inline]
Definition at line 53 of file textdocvisitor.h.
{}
operator()() [9/114]
void TextDocVisitor::operator() (const DocDiaFile & df) [inline]
Definition at line 94 of file textdocvisitor.h.
{ visitChildren(df); }
References visitChildren().
operator()() [10/114]
void TextDocVisitor::operator() (const DocDiaFile & df) [inline]
Definition at line 94 of file textdocvisitor.h.
{ visitChildren(df); }
References visitChildren().
operator()() [11/114]
void TextDocVisitor::operator() (const DocDotFile & df) [inline]
Definition at line 92 of file textdocvisitor.h.
{ visitChildren(df); }
References visitChildren().
operator()() [12/114]
void TextDocVisitor::operator() (const DocDotFile & df) [inline]
Definition at line 92 of file textdocvisitor.h.
{ visitChildren(df); }
References visitChildren().
operator()() [13/114]
void TextDocVisitor::operator() (const DocEmoji & s)
Definition at line 40 of file textdocvisitor.cpp.
{
  const char *res = EmojiEntityMapper::instance()->name(s.index());
  if (res)
  {
    filter(res);
  }
  else
  {
    filter(s.name());
  }
}
References filter(), EmojiEntityMapper::instance(), EmojiEntityMapper::name(), and s.
operator()() [14/114]
void TextDocVisitor::operator() (const DocEmoji &)
operator()() [15/114]
void TextDocVisitor::operator() (const DocFormula &) [inline]
Definition at line 50 of file textdocvisitor.h.
{}
operator()() [16/114]
void TextDocVisitor::operator() (const DocFormula &) [inline]
Definition at line 50 of file textdocvisitor.h.
{}
operator()() [17/114]
void TextDocVisitor::operator() (const DocHorRuler &) [inline]
Definition at line 44 of file textdocvisitor.h.
{}
operator()() [18/114]
void TextDocVisitor::operator() (const DocHorRuler &) [inline]
Definition at line 44 of file textdocvisitor.h.
{}
operator()() [19/114]
void TextDocVisitor::operator() (const DocHRef & h) [inline]
Definition at line 87 of file textdocvisitor.h.
{ visitChildren(h); }
References h, and visitChildren().
operator()() [20/114]
void TextDocVisitor::operator() (const DocHRef & h) [inline]
Definition at line 87 of file textdocvisitor.h.
{ visitChildren(h); }
References h, and visitChildren().
operator()() [21/114]
void TextDocVisitor::operator() (const DocHtmlBlockQuote & q) [inline]
Definition at line 104 of file textdocvisitor.h.
{ visitChildren(q); }
References visitChildren().
operator()() [22/114]
void TextDocVisitor::operator() (const DocHtmlBlockQuote & q) [inline]
Definition at line 104 of file textdocvisitor.h.
{ visitChildren(q); }
References visitChildren().
operator()() [23/114]
void TextDocVisitor::operator() (const DocHtmlCaption & c) [inline]
Definition at line 85 of file textdocvisitor.h.
{ visitChildren(c); }
References c, and visitChildren().
operator()() [24/114]
void TextDocVisitor::operator() (const DocHtmlCaption & c) [inline]
Definition at line 85 of file textdocvisitor.h.
{ visitChildren(c); }
References c, and visitChildren().
operator()() [25/114]
void TextDocVisitor::operator() (const DocHtmlCell & c) [inline]
Definition at line 84 of file textdocvisitor.h.
{ visitChildren(c); }
References c, and visitChildren().
operator()() [26/114]
void TextDocVisitor::operator() (const DocHtmlCell & c) [inline]
Definition at line 84 of file textdocvisitor.h.
{ visitChildren(c); }
References c, and visitChildren().
operator()() [27/114]
void TextDocVisitor::operator() (const DocHtmlDescData & dd) [inline]
Definition at line 81 of file textdocvisitor.h.
{ visitChildren(dd); }
References visitChildren().
operator()() [28/114]
void TextDocVisitor::operator() (const DocHtmlDescData & dd) [inline]
Definition at line 81 of file textdocvisitor.h.
{ visitChildren(dd); }
References visitChildren().
operator()() [29/114]
void TextDocVisitor::operator() (const DocHtmlDescList & dl) [inline]
Definition at line 79 of file textdocvisitor.h.
{ visitChildren(dl); }
References visitChildren().
operator()() [30/114]
void TextDocVisitor::operator() (const DocHtmlDescList & dl) [inline]
Definition at line 79 of file textdocvisitor.h.
{ visitChildren(dl); }
References visitChildren().
operator()() [31/114]
void TextDocVisitor::operator() (const DocHtmlDescTitle & dt) [inline]
Definition at line 80 of file textdocvisitor.h.
{ visitChildren(dt); }
References visitChildren().
operator()() [32/114]
void TextDocVisitor::operator() (const DocHtmlDescTitle & dt) [inline]
Definition at line 80 of file textdocvisitor.h.
{ visitChildren(dt); }
References visitChildren().
operator()() [33/114]
void TextDocVisitor::operator() (const DocHtmlDetails & d) [inline]
Definition at line 89 of file textdocvisitor.h.
{ visitChildren(d); }
References visitChildren().
operator()() [34/114]
void TextDocVisitor::operator() (const DocHtmlDetails & d) [inline]
Definition at line 89 of file textdocvisitor.h.
{ visitChildren(d); }
References visitChildren().
operator()() [35/114]
void TextDocVisitor::operator() (const DocHtmlHeader & h) [inline]
Definition at line 90 of file textdocvisitor.h.
{ visitChildren(h); }
References h, and visitChildren().
operator()() [36/114]
void TextDocVisitor::operator() (const DocHtmlHeader & h) [inline]
Definition at line 90 of file textdocvisitor.h.
{ visitChildren(h); }
References h, and visitChildren().
operator()() [37/114]
void TextDocVisitor::operator() (const DocHtmlList & l) [inline]
Definition at line 77 of file textdocvisitor.h.
{ visitChildren(l); }
References visitChildren().
operator()() [38/114]
void TextDocVisitor::operator() (const DocHtmlList & l) [inline]
Definition at line 77 of file textdocvisitor.h.
{ visitChildren(l); }
References visitChildren().
operator()() [39/114]
void TextDocVisitor::operator() (const DocHtmlListItem & li) [inline]
Definition at line 78 of file textdocvisitor.h.
{ visitChildren(li); }
References visitChildren().
operator()() [40/114]
void TextDocVisitor::operator() (const DocHtmlListItem & li) [inline]
Definition at line 78 of file textdocvisitor.h.
{ visitChildren(li); }
References visitChildren().
operator()() [41/114]
void TextDocVisitor::operator() (const DocHtmlRow & r) [inline]
Definition at line 83 of file textdocvisitor.h.
{ visitChildren(r); }
References r, and visitChildren().
operator()() [42/114]
void TextDocVisitor::operator() (const DocHtmlRow & r) [inline]
Definition at line 83 of file textdocvisitor.h.
{ visitChildren(r); }
References r, and visitChildren().
operator()() [43/114]
void TextDocVisitor::operator() (const DocHtmlSummary & s) [inline]
Definition at line 88 of file textdocvisitor.h.
{ visitChildren(s); }
References s, and visitChildren().
operator()() [44/114]
void TextDocVisitor::operator() (const DocHtmlSummary & s) [inline]
Definition at line 88 of file textdocvisitor.h.
{ visitChildren(s); }
References s, and visitChildren().
operator()() [45/114]
void TextDocVisitor::operator() (const DocHtmlTable & t) [inline]
Definition at line 82 of file textdocvisitor.h.
{ visitChildren(t); }
References visitChildren().
operator()() [46/114]
void TextDocVisitor::operator() (const DocHtmlTable & t) [inline]
Definition at line 82 of file textdocvisitor.h.
{ visitChildren(t); }
References visitChildren().
operator()() [47/114]
void TextDocVisitor::operator() (const DocImage & i) [inline]
Definition at line 91 of file textdocvisitor.h.
{ visitChildren(i); }
References visitChildren().
operator()() [48/114]
void TextDocVisitor::operator() (const DocImage & i) [inline]
Definition at line 91 of file textdocvisitor.h.
{ visitChildren(i); }
References visitChildren().
operator()() [49/114]
void TextDocVisitor::operator() (const DocInclude &) [inline]
Definition at line 48 of file textdocvisitor.h.
{}
operator()() [50/114]
void TextDocVisitor::operator() (const DocInclude &) [inline]
Definition at line 48 of file textdocvisitor.h.
{}
operator()() [51/114]
void TextDocVisitor::operator() (const DocIncOperator &) [inline]
Definition at line 49 of file textdocvisitor.h.
{}
operator()() [52/114]
void TextDocVisitor::operator() (const DocIncOperator &) [inline]
Definition at line 49 of file textdocvisitor.h.
{}
operator()() [53/114]
void TextDocVisitor::operator() (const DocIndexEntry &) [inline]
Definition at line 51 of file textdocvisitor.h.
{}
operator()() [54/114]
void TextDocVisitor::operator() (const DocIndexEntry &) [inline]
Definition at line 51 of file textdocvisitor.h.
{}
operator()() [55/114]
void TextDocVisitor::operator() (const DocInternal & i) [inline]
Definition at line 86 of file textdocvisitor.h.
{ visitChildren(i); }
References visitChildren().
operator()() [56/114]
void TextDocVisitor::operator() (const DocInternal & i) [inline]
Definition at line 86 of file textdocvisitor.h.
{ visitChildren(i); }
References visitChildren().
operator()() [57/114]
void TextDocVisitor::operator() (const DocInternalRef & r) [inline]
Definition at line 102 of file textdocvisitor.h.
{ visitChildren(r); }
References r, and visitChildren().
operator()() [58/114]
void TextDocVisitor::operator() (const DocInternalRef & r) [inline]
Definition at line 102 of file textdocvisitor.h.
{ visitChildren(r); }
References r, and visitChildren().
operator()() [59/114]
void TextDocVisitor::operator() (const DocLineBreak &) [inline]
Definition at line 43 of file textdocvisitor.h.
{ m_t << " "; }
References m_t.
operator()() [60/114]
void TextDocVisitor::operator() (const DocLineBreak &) [inline]
Definition at line 43 of file textdocvisitor.h.
{ m_t << " "; }
References m_t.
operator()() [61/114]
void TextDocVisitor::operator() (const DocLink & l) [inline]
Definition at line 95 of file textdocvisitor.h.
{ visitChildren(l); }
References visitChildren().
operator()() [62/114]
void TextDocVisitor::operator() (const DocLink & l) [inline]
Definition at line 95 of file textdocvisitor.h.
{ visitChildren(l); }
References visitChildren().
operator()() [63/114]
void TextDocVisitor::operator() (const DocLinkedWord & w) [inline]
Definition at line 38 of file textdocvisitor.h.
{ filter(w.word()); }
References filter(), and w.
operator()() [64/114]
void TextDocVisitor::operator() (const DocLinkedWord & w) [inline]
Definition at line 38 of file textdocvisitor.h.
{ filter(w.word()); }
References filter(), and w.
operator()() [65/114]
void TextDocVisitor::operator() (const DocMscFile & df) [inline]
Definition at line 93 of file textdocvisitor.h.
{ visitChildren(df); }
References visitChildren().
operator()() [66/114]
void TextDocVisitor::operator() (const DocMscFile & df) [inline]
Definition at line 93 of file textdocvisitor.h.
{ visitChildren(df); }
References visitChildren().
operator()() [67/114]
void TextDocVisitor::operator() (const DocPara & p) [inline]
Definition at line 70 of file textdocvisitor.h.
{ visitChildren(p); }
References p, and visitChildren().
operator()() [68/114]
void TextDocVisitor::operator() (const DocPara & p) [inline]
Definition at line 70 of file textdocvisitor.h.
{ visitChildren(p); }
References p, and visitChildren().
operator()() [69/114]
void TextDocVisitor::operator() (const DocParamList &) [inline]
Definition at line 100 of file textdocvisitor.h.
{ }
operator()() [70/114]
void TextDocVisitor::operator() (const DocParamList &) [inline]
Definition at line 100 of file textdocvisitor.h.
{ }
operator()() [71/114]
void TextDocVisitor::operator() (const DocParamSect & s) [inline]
Definition at line 99 of file textdocvisitor.h.
{ visitChildren(s); }
References s, and visitChildren().
operator()() [72/114]
void TextDocVisitor::operator() (const DocParamSect & s) [inline]
Definition at line 99 of file textdocvisitor.h.
{ visitChildren(s); }
References s, and visitChildren().
operator()() [73/114]
void TextDocVisitor::operator() (const DocParBlock & pb) [inline]
Definition at line 106 of file textdocvisitor.h.
{ visitChildren(pb); }
References visitChildren().
operator()() [74/114]
void TextDocVisitor::operator() (const DocParBlock & pb) [inline]
Definition at line 106 of file textdocvisitor.h.
{ visitChildren(pb); }
References visitChildren().
operator()() [75/114]
void TextDocVisitor::operator() (const DocRef & r) [inline]
Definition at line 96 of file textdocvisitor.h.
{ visitChildren(r); }
References r, and visitChildren().
operator()() [76/114]
void TextDocVisitor::operator() (const DocRef & r) [inline]
Definition at line 96 of file textdocvisitor.h.
{ visitChildren(r); }
References r, and visitChildren().
operator()() [77/114]
void TextDocVisitor::operator() (const DocRoot & r) [inline]
Definition at line 71 of file textdocvisitor.h.
{ visitChildren(r); }
References r, and visitChildren().
operator()() [78/114]
void TextDocVisitor::operator() (const DocRoot & r) [inline]
Definition at line 71 of file textdocvisitor.h.
{ visitChildren(r); }
References r, and visitChildren().
operator()() [79/114]
void TextDocVisitor::operator() (const DocSecRefItem & s) [inline]
Definition at line 97 of file textdocvisitor.h.
{ visitChildren(s); }
References s, and visitChildren().
operator()() [80/114]
void TextDocVisitor::operator() (const DocSecRefItem & s) [inline]
Definition at line 97 of file textdocvisitor.h.
{ visitChildren(s); }
References s, and visitChildren().
operator()() [81/114]
void TextDocVisitor::operator() (const DocSecRefList & l) [inline]
Definition at line 98 of file textdocvisitor.h.
{ visitChildren(l); }
References visitChildren().
operator()() [82/114]
void TextDocVisitor::operator() (const DocSecRefList & l) [inline]
Definition at line 98 of file textdocvisitor.h.
{ visitChildren(l); }
References visitChildren().
operator()() [83/114]
void TextDocVisitor::operator() (const DocSection & s) [inline]
Definition at line 76 of file textdocvisitor.h.
{ visitChildren(s); }
References s, and visitChildren().
operator()() [84/114]
void TextDocVisitor::operator() (const DocSection & s) [inline]
Definition at line 76 of file textdocvisitor.h.
{ visitChildren(s); }
References s, and visitChildren().
operator()() [85/114]
void TextDocVisitor::operator() (const DocSeparator &) [inline]
Definition at line 54 of file textdocvisitor.h.
{ m_t << " "; }
References m_t.
operator()() [86/114]
void TextDocVisitor::operator() (const DocSeparator &) [inline]
Definition at line 54 of file textdocvisitor.h.
{ m_t << " "; }
References m_t.
operator()() [87/114]
void TextDocVisitor::operator() (const DocSimpleList & l) [inline]
Definition at line 74 of file textdocvisitor.h.
{ visitChildren(l); }
References visitChildren().
operator()() [88/114]
void TextDocVisitor::operator() (const DocSimpleList & l) [inline]
Definition at line 74 of file textdocvisitor.h.
{ visitChildren(l); }
References visitChildren().
operator()() [89/114]
void TextDocVisitor::operator() (const DocSimpleListItem &) [inline]
Definition at line 75 of file textdocvisitor.h.
{ }
operator()() [90/114]
void TextDocVisitor::operator() (const DocSimpleListItem &) [inline]
Definition at line 75 of file textdocvisitor.h.
{ }
operator()() [91/114]
void TextDocVisitor::operator() (const DocSimpleSect & s) [inline]
Definition at line 72 of file textdocvisitor.h.
{ visitChildren(s); }
References s, and visitChildren().
operator()() [92/114]
void TextDocVisitor::operator() (const DocSimpleSect & s) [inline]
Definition at line 72 of file textdocvisitor.h.
{ visitChildren(s); }
References s, and visitChildren().
operator()() [93/114]
void TextDocVisitor::operator() (const DocSimpleSectSep &) [inline]
Definition at line 52 of file textdocvisitor.h.
{}
operator()() [94/114]
void TextDocVisitor::operator() (const DocSimpleSectSep &) [inline]
Definition at line 52 of file textdocvisitor.h.
{}
operator()() [95/114]
void TextDocVisitor::operator() (const DocStyleChange &) [inline]
Definition at line 45 of file textdocvisitor.h.
{}
operator()() [96/114]
void TextDocVisitor::operator() (const DocStyleChange &) [inline]
Definition at line 45 of file textdocvisitor.h.
{}
operator()() [97/114]
void TextDocVisitor::operator() (const DocSymbol & s)
Definition at line 27 of file textdocvisitor.cpp.
{
  const char *res = HtmlEntityMapper::instance()->html(s.symbol());
  if (res)
  {
    m_t << res;
  }
  else
  {
    err("text: non supported HTML-entity found: %s\n",HtmlEntityMapper::instance()->html(s.symbol(),TRUE));
  }
}
References err(), HtmlEntityMapper::html(), HtmlEntityMapper::instance(), m_t, s, and TRUE.
operator()() [98/114]
void TextDocVisitor::operator() (const DocSymbol &)
operator()() [99/114]
void TextDocVisitor::operator() (const DocText & t) [inline]
Definition at line 103 of file textdocvisitor.h.
{ visitChildren(t); }
References visitChildren().
operator()() [100/114]
void TextDocVisitor::operator() (const DocText & t) [inline]
Definition at line 103 of file textdocvisitor.h.
{ visitChildren(t); }
References visitChildren().
operator()() [101/114]
void TextDocVisitor::operator() (const DocTitle & t) [inline]
Definition at line 73 of file textdocvisitor.h.
{ visitChildren(t); }
References visitChildren().
operator()() [102/114]
void TextDocVisitor::operator() (const DocTitle & t) [inline]
Definition at line 73 of file textdocvisitor.h.
{ visitChildren(t); }
References visitChildren().
operator()() [103/114]
void TextDocVisitor::operator() (const DocURL & u) [inline]
Definition at line 42 of file textdocvisitor.h.
{ filter(u.url()); }
References filter(), and DocURL::url().
operator()() [104/114]
void TextDocVisitor::operator() (const DocURL & u) [inline]
Definition at line 42 of file textdocvisitor.h.
{ filter(u.url()); }
References filter(), and DocURL::url().
operator()() [105/114]
void TextDocVisitor::operator() (const DocVerbatim & s) [inline]
Definition at line 46 of file textdocvisitor.h.
{ filter(s.text()); }
References filter(), and s.
operator()() [106/114]
void TextDocVisitor::operator() (const DocVerbatim & s) [inline]
Definition at line 46 of file textdocvisitor.h.
{ filter(s.text()); }
References filter(), and s.
operator()() [107/114]
void TextDocVisitor::operator() (const DocVhdlFlow &) [inline]
Definition at line 105 of file textdocvisitor.h.
{ }
operator()() [108/114]
void TextDocVisitor::operator() (const DocVhdlFlow &) [inline]
Definition at line 105 of file textdocvisitor.h.
{ }
operator()() [109/114]
void TextDocVisitor::operator() (const DocWhiteSpace &) [inline]
Definition at line 39 of file textdocvisitor.h.
{ m_t << " "; }
References m_t.
operator()() [110/114]
void TextDocVisitor::operator() (const DocWhiteSpace &) [inline]
Definition at line 39 of file textdocvisitor.h.
{ m_t << " "; }
References m_t.
operator()() [111/114]
void TextDocVisitor::operator() (const DocWord & w) [inline]
Definition at line 37 of file textdocvisitor.h.
{ filter(w.word()); }
References filter(), and w.
operator()() [112/114]
void TextDocVisitor::operator() (const DocWord & w) [inline]
Definition at line 37 of file textdocvisitor.h.
{ filter(w.word()); }
References filter(), and w.
operator()() [113/114]
void TextDocVisitor::operator() (const DocXRefItem & x) [inline]
Definition at line 101 of file textdocvisitor.h.
{ visitChildren(x); }
References visitChildren(), and x.
operator()() [114/114]
void TextDocVisitor::operator() (const DocXRefItem & x) [inline]
Definition at line 101 of file textdocvisitor.h.
{ visitChildren(x); }
References visitChildren(), and x.
visitChildren() [1/2]
template<class T >
void TextDocVisitor::visitChildren (const T & t) [inline]
Definition at line 61 of file textdocvisitor.h.
    {
      for (const auto &child : t.children())
      {
        std::visit(*this, child);
      }
    }
Referenced by operator()().
visitChildren() [2/2]
template<class T >
void TextDocVisitor::visitChildren (const T & t) [inline]
Definition at line 61 of file textdocvisitor.h.
    {
      for (const auto &child : t.children())
      {
        std::visit(*this, child);
      }
    }
Member Data Documentation
m_t
TextStream & TextDocVisitor::m_t [private]
Definition at line 112 of file textdocvisitor.h.
Referenced by filter(), and operator()().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/textdocvisitor.h
doxygen/src/textdocvisitor.h
doxygen/build/doxygen/src/textdocvisitor.cpp
doxygen/src/textdocvisitor.cpp