reg::Match Class Reference
#include <regex.h>
Public Member Functions
Match ()
size_t position () const
size_t length () const
std::string str () const
SubMatch prefix () const
SubMatch suffix () const
size_t size () const
const SubMatch & operator[] (size_t index) const
Match ()
size_t position () const
size_t length () const
std::string str () const
SubMatch prefix () const
SubMatch suffix () const
size_t size () const
const SubMatch & operator[] (size_t index) const
Private Member Functions
void init (const std::string *str)
void startCapture (size_t index)
void endCapture (size_t index)
void setMatch (size_t pos, size_t len)
void init (const std::string *str)
void startCapture (size_t index)
void endCapture (size_t index)
void setMatch (size_t pos, size_t len)
Private Attributes
std::vector< SubMatch > m_subMatches
size_t m_captureIndex =0
const std::string * m_str = nullptr
bool m_insideCapture =false
Friends
class Ex
Detailed Description
Object representing the matching results. It consists of an array of SubMatch objects. The first entry of the array represents the whole match, any next elements represent each of the capture ranges.
For example string @42 and expression @(\\d+) will have two Submatches, match[0] will point to the input string as a whole, and match[1] will point to the number 42 only.
Definition at line 150 of file regex.h.
Constructor & Destructor Documentation
Match() [1/2]
reg::Match::Match () [inline]
Creates an empty match object
Definition at line 154 of file regex.h.
{}
Match() [2/2]
reg::Match::Match () [inline]
Creates an empty match object
Definition at line 154 of file regex.h.
{}
Member Function Documentation
endCapture() [1/2]
void reg::Match::endCapture (size_t index) [inline], [private]
Definition at line 207 of file regex.h.
    {
      if (index>m_subMatches.back().position())
      {
        m_captureIndex=0;
        m_subMatches.back().setEnd(index);
        m_insideCapture = false;
      }
    }
References m_captureIndex, m_insideCapture, and m_subMatches.
endCapture() [2/2]
void reg::Match::endCapture (size_t index) [inline], [private]
Definition at line 207 of file regex.h.
    {
      if (index>m_subMatches.back().position())
      {
        m_captureIndex=0;
        m_subMatches.back().setEnd(index);
        m_insideCapture = false;
      }
    }
References m_captureIndex, m_insideCapture, and m_subMatches.
init() [1/2]
void reg::Match::init (const std::string * str) [inline], [private]
Definition at line 190 of file regex.h.
    {
      m_subMatches.clear();
      m_subMatches.emplace_back(str);
      m_str = str;
    }
References m_str, m_subMatches, and str().
Referenced by reg::Ex::Private::matchAt().
init() [2/2]
void reg::Match::init (const std::string * str) [inline], [private]
Definition at line 190 of file regex.h.
    {
      m_subMatches.clear();
      m_subMatches.emplace_back(str);
      m_str = str;
    }
References m_str, m_subMatches, and str().
length() [1/2]
size_t reg::Match::length () const [inline]
Returns the position of the match or std::string::npos if no length is set.
Definition at line 160 of file regex.h.
{ return m_subMatches[0].length(); }
References m_subMatches.
Referenced by reg::Iterator::findNext(), reg::Ex::Private::matchAt(), replaceNamespaceAliases(), and suffix().
length() [2/2]
size_t reg::Match::length () const [inline]
Returns the position of the match or std::string::npos if no length is set.
Definition at line 160 of file regex.h.
{ return m_subMatches[0].length(); }
References m_subMatches.
operator[]() [1/2]
const SubMatch & reg::Match::operator[] (size_t index) const [inline]
Returns the n-th SubMatch object. Note that there is always 1 SubMatch object representing the whole match.
Definition at line 186 of file regex.h.
{ return m_subMatches[index]; }
References m_subMatches.
operator[]() [2/2]
const SubMatch & reg::Match::operator[] (size_t index) const [inline]
Returns the n-th SubMatch object. Note that there is always 1 SubMatch object representing the whole match.
Definition at line 186 of file regex.h.
{ return m_subMatches[index]; }
References m_subMatches.
position() [1/2]
size_t reg::Match::position () const [inline]
Returns the position of the match or std::string::npos if no position is set.
Definition at line 157 of file regex.h.
{ return m_subMatches[0].position(); }
References m_subMatches.
Referenced by reg::Iterator::findNext(), prefix(), and suffix().
position() [2/2]
size_t reg::Match::position () const [inline]
Returns the position of the match or std::string::npos if no position is set.
Definition at line 157 of file regex.h.
{ return m_subMatches[0].position(); }
References m_subMatches.
prefix() [1/2]
SubMatch reg::Match::prefix () const [inline]
Return the part of the string before the match
Definition at line 166 of file regex.h.
{ SubMatch m(m_str); m.setMatch(0,position()); return m; }
References m_str, position(), and reg::SubMatch::setMatch().
prefix() [2/2]
SubMatch reg::Match::prefix () const [inline]
Return the part of the string before the match
Definition at line 166 of file regex.h.
{ SubMatch m(m_str); m.setMatch(0,position()); return m; }
References m_str, position(), and reg::SubMatch::setMatch().
setMatch() [1/2]
void reg::Match::setMatch (size_t pos, size_t len) [inline], [private]
Definition at line 216 of file regex.h.
    {
      m_subMatches[m_captureIndex].setMatch(pos,len);
    }
References len, m_captureIndex, and m_subMatches.
setMatch() [2/2]
void reg::Match::setMatch (size_t pos, size_t len) [inline], [private]
Definition at line 216 of file regex.h.
    {
      m_subMatches[m_captureIndex].setMatch(pos,len);
    }
References len, m_captureIndex, and m_subMatches.
size() [1/2]
size_t reg::Match::size () const [inline]
Returns the number of sub matches available in this match.
Definition at line 181 of file regex.h.
{ return m_subMatches.size(); }
References m_subMatches.
size() [2/2]
size_t reg::Match::size () const [inline]
Returns the number of sub matches available in this match.
Definition at line 181 of file regex.h.
{ return m_subMatches.size(); }
References m_subMatches.
startCapture() [1/2]
void reg::Match::startCapture (size_t index) [inline], [private]
Definition at line 196 of file regex.h.
    {
      if (!m_insideCapture) // when backtracking we can re-entry the capture multiple times
                            // only update the index, example `\s*(x)`
      {
        m_captureIndex = m_subMatches.size();
        m_subMatches.emplace_back(m_str);
        m_insideCapture = true;
      }
      m_subMatches.back().setStart(index);
    }
References m_captureIndex, m_insideCapture, m_str, and m_subMatches.
startCapture() [2/2]
void reg::Match::startCapture (size_t index) [inline], [private]
Definition at line 196 of file regex.h.
    {
      if (!m_insideCapture) // when backtracking we can re-entry the capture multiple times
                            // only update the index, example `\s*(x)`
      {
        m_captureIndex = m_subMatches.size();
        m_subMatches.emplace_back(m_str);
        m_insideCapture = true;
      }
      m_subMatches.back().setStart(index);
    }
References m_captureIndex, m_insideCapture, m_str, and m_subMatches.
str() [1/2]
std::string reg::Match::str () const [inline]
Return a string representing the matching part.
Definition at line 163 of file regex.h.
{ return m_subMatches[0].str(); }
References m_subMatches.
Referenced by containsWord(), init(), and initPredefined().
str() [2/2]
std::string reg::Match::str () const [inline]
Return a string representing the matching part.
Definition at line 163 of file regex.h.
{ return m_subMatches[0].str(); }
References m_subMatches.
suffix() [1/2]
SubMatch reg::Match::suffix () const [inline]
Return the part of the string after the match
Definition at line 169 of file regex.h.
    {
      SubMatch m(m_str);
      if (m_str)
      {
        size_t e = position()+length();
        m.setMatch(e,m_str->length()-e);
      }
      return m;
    }
References e, length(), m_str, position(), and reg::SubMatch::setMatch().
suffix() [2/2]
SubMatch reg::Match::suffix () const [inline]
Return the part of the string after the match
Definition at line 169 of file regex.h.
    {
      SubMatch m(m_str);
      if (m_str)
      {
        size_t e = position()+length();
        m.setMatch(e,m_str->length()-e);
      }
      return m;
    }
References e, length(), m_str, position(), and reg::SubMatch::setMatch().
Friends And Related Function Documentation
Ex
Ex [friend]
Definition at line 189 of file regex.h.
Member Data Documentation
m_captureIndex
size_t reg::Match::m_captureIndex =0 [private]
Definition at line 222 of file regex.h.
Referenced by endCapture(), setMatch(), and startCapture().
m_insideCapture
bool reg::Match::m_insideCapture =false [private]
Definition at line 224 of file regex.h.
Referenced by endCapture(), and startCapture().
m_str
const std::string * reg::Match::m_str = nullptr [private]
Definition at line 223 of file regex.h.
Referenced by init(), prefix(), startCapture(), and suffix().
m_subMatches
std::vector< SubMatch > reg::Match::m_subMatches [private]
Definition at line 221 of file regex.h.
Referenced by endCapture(), init(), length(), operator[](), position(), setMatch(), size(), startCapture(), and str().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/regex.h
doxygen/src/regex.h