TemplateNodeExtend Class Reference
Class representing a 'extend' tag in a template.
Public Member Functions
TemplateNodeExtend (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void render (TextStream &ts, TemplateContext *c)
TemplateNodeExtend (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void render (TextStream &ts, TemplateContext *c)
Private Attributes
ExprAstPtr m_extendExpr
TemplateNodeList m_nodes
Additional Inherited Members
Detailed Description
Class representing a 'extend' tag in a template.
Definition at line 3676 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeExtend() [1/2]
TemplateNodeExtend::TemplateNodeExtend (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 3679 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeExtend>(parser,parent,line)
    {
      TRACE(("{TemplateNodeExtend(%s)\n",qPrint(data)));
      ExpressionParser ep(parser,line);
      if (data.isEmpty())
      {
        parser->warn(m_templateName,line,"extend tag is missing template file argument");
      }
      m_extendExpr = ep.parse(data);
      StringVector stopAt;
      parser->parse(this,line,stopAt,m_nodes);
      TRACE(("}TemplateNodeExtend(%s)\n",qPrint(data)));
    }
References data, m_extendExpr, m_nodes, TemplateNodeCreator< TemplateNodeExtend >::m_templateName, ExpressionParser::parse(), TemplateParser::parse(), qPrint(), TRACE, and TemplateParser::warn().
TemplateNodeExtend() [2/2]
TemplateNodeExtend::TemplateNodeExtend (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 3679 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeExtend>(parser,parent,line)
    {
      TRACE(("{TemplateNodeExtend(%s)\n",qPrint(data)));
      ExpressionParser ep(parser,line);
      if (data.isEmpty())
      {
        parser->warn(m_templateName,line,"extend tag is missing template file argument");
      }
      m_extendExpr = ep.parse(data);
      StringVector stopAt;
      parser->parse(this,line,stopAt,m_nodes);
      TRACE(("}TemplateNodeExtend(%s)\n",qPrint(data)));
    }
References data, m_extendExpr, m_nodes, TemplateNodeCreator< TemplateNodeExtend >::m_templateName, ExpressionParser::parse(), TemplateParser::parse(), qPrint(), TRACE, and TemplateParser::warn().
Member Function Documentation
render() [1/2]
void TemplateNodeExtend::render (TextStream & ts, TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 3694 of file template.cpp.
    {
      TemplateContextImpl* ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      if (m_extendExpr==0) return;
      QCString extendFile = m_extendExpr->resolve(c).toString();
      if (extendFile.isEmpty())
      {
        ci->warn(m_templateName,m_line,"invalid parameter for extend command");
      }
      // goto root of tree (template node)
      TemplateImpl *t = getTemplate();
      if (t)
      {
        Template *bt = t->engine()->loadByName(extendFile,m_line);
        TemplateImpl *baseTemplate = bt ? dynamic_cast<TemplateImpl*>(bt) : 0;
        if (baseTemplate)
        {
          // fill block context
          TemplateBlockContext *bc = ci->blockContext();
          // add overruling blocks to the context
          for (const auto &n : m_nodes)
          {
            TemplateNodeBlock *nb = dynamic_cast<TemplateNodeBlock*>(n.get());
            if (nb)
            {
              bc->add(nb);
            }
            TemplateNodeMsg *msg = dynamic_cast<TemplateNodeMsg*>(n.get());
            if (msg)
            {
              msg->render(ts,c);
            }
          }
          // render the base template with the given context
          baseTemplate->render(ts,c);
          // clean up
          bc->clear();
        }
        else
        {
          ci->warn(m_templateName,m_line,"failed to load template %s for extend",qPrint(extendFile));
        }
        t->engine()->unload(bt);
      }
    }
References TemplateBlockContext::add(), TemplateContextImpl::blockContext(), c, TemplateBlockContext::clear(), TemplateImpl::engine(), TemplateNodeCreator< TemplateNodeExtend >::getTemplate(), QCString::isEmpty(), TemplateEngine::loadByName(), m_extendExpr, TemplateNodeCreator< TemplateNodeExtend >::m_line, m_nodes, TemplateNodeCreator< TemplateNodeExtend >::m_templateName, msg(), n, qPrint(), TemplateImpl::render(), TemplateContextImpl::setLocation(), TemplateEngine::unload(), and TemplateContextImpl::warn().
render() [2/2]
void TemplateNodeExtend::render (TextStream & ts, TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 3694 of file template.cpp.
    {
      TemplateContextImpl* ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      if (m_extendExpr==0) return;
      QCString extendFile = m_extendExpr->resolve(c).toString();
      if (extendFile.isEmpty())
      {
        ci->warn(m_templateName,m_line,"invalid parameter for extend command");
      }
      // goto root of tree (template node)
      TemplateImpl *t = getTemplate();
      if (t)
      {
        Template *bt = t->engine()->loadByName(extendFile,m_line);
        TemplateImpl *baseTemplate = bt ? dynamic_cast<TemplateImpl*>(bt) : 0;
        if (baseTemplate)
        {
          // fill block context
          TemplateBlockContext *bc = ci->blockContext();
          // add overruling blocks to the context
          for (const auto &n : m_nodes)
          {
            TemplateNodeBlock *nb = dynamic_cast<TemplateNodeBlock*>(n.get());
            if (nb)
            {
              bc->add(nb);
            }
            TemplateNodeMsg *msg = dynamic_cast<TemplateNodeMsg*>(n.get());
            if (msg)
            {
              msg->render(ts,c);
            }
          }
          // render the base template with the given context
          baseTemplate->render(ts,c);
          // clean up
          bc->clear();
        }
        else
        {
          ci->warn(m_templateName,m_line,"failed to load template %s for extend",qPrint(extendFile));
        }
        t->engine()->unload(bt);
      }
    }
References TemplateBlockContext::add(), TemplateContextImpl::blockContext(), c, TemplateBlockContext::clear(), TemplateImpl::engine(), TemplateNodeCreator< TemplateNodeExtend >::getTemplate(), QCString::isEmpty(), TemplateEngine::loadByName(), m_extendExpr, TemplateNodeCreator< TemplateNodeExtend >::m_line, m_nodes, TemplateNodeCreator< TemplateNodeExtend >::m_templateName, msg(), n, qPrint(), TemplateImpl::render(), TemplateContextImpl::setLocation(), TemplateEngine::unload(), and TemplateContextImpl::warn().
Member Data Documentation
m_extendExpr
ExprAstPtr TemplateNodeExtend::m_extendExpr [private]
Definition at line 3748 of file template.cpp.
Referenced by render(), and TemplateNodeExtend().
m_nodes
TemplateNodeList TemplateNodeExtend::m_nodes [private]
Definition at line 3749 of file template.cpp.
Referenced by render(), and TemplateNodeExtend().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp