DocImage Class Reference
#include <docnode.h>
Classes
struct Private
Public Types
enum Type {
Html
, Latex
, Rtf
, DocBook
,
Xml
, Html
, Latex
, Rtf
,
DocBook
, Xml
 }
enum Type {
Html
, Latex
, Rtf
, DocBook
,
Xml
, Html
, Latex
, Rtf
,
DocBook
, Xml
 }
Public Member Functions
DocImage (DocParser *parser, DocNodeVariant *parent, const HtmlAttribList &attribs, const QCString &name, Type t, const QCString &url=QCString(), bool inlineImage=TRUE)
Type type () const
QCString name () const
bool hasCaption () const
QCString width () const
QCString height () const
QCString relPath () const
QCString url () const
bool isInlineImage () const
bool isSVG () const
const HtmlAttribList & attribs () const
void parse (DocNodeVariant *)
DocImage (DocParser *parser, DocNodeVariant *parent, const HtmlAttribList &attribs, const QCString &name, Type t, const QCString &url=QCString(), bool inlineImage=TRUE)
Type type () const
QCString name () const
bool hasCaption () const
QCString width () const
QCString height () const
QCString relPath () const
QCString url () const
bool isInlineImage () const
bool isSVG () const
const HtmlAttribList & attribs () const
void parse (DocNodeVariant *)
Private Attributes
std::unique_ptr< Private > p
Additional Inherited Members
Detailed Description
Node representing an image
Definition at line 605 of file docnode.h.
Member Enumeration Documentation
Type [1/2]
enum DocImage::Type
Enumerator
Html
Latex
Rtf
DocBook
Xml
Html
Latex
Rtf
DocBook
Xml
Definition at line 608 of file docnode.h.
{ Html, Latex, Rtf, DocBook, Xml };
Type [2/2]
enum DocImage::Type
Enumerator
Html
Latex
Rtf
DocBook
Xml
Html
Latex
Rtf
DocBook
Xml
Definition at line 608 of file docnode.h.
{ Html, Latex, Rtf, DocBook, Xml };
Constructor & Destructor Documentation
DocImage() [1/2]
DocImage::DocImage (DocParser * parser, DocNodeVariant * parent, const HtmlAttribList & attribs, const QCString & name, Type t, const QCString & url = QCString(), bool inlineImage = TRUE)
Definition at line 1158 of file docnode.cpp.
                                                                 :
      DocCompoundNode(parser,parent), p(std::make_unique<Private>(attribs, name, t, parser->context.relPath, url, inlineImage))
{
}
DocImage() [2/2]
DocImage::DocImage (DocParser * parser, DocNodeVariant * parent, const HtmlAttribList & attribs, const QCString & name, Type t, const QCString & url = QCString(), bool inlineImage = TRUE)
Member Function Documentation
attribs() [1/2]
const HtmlAttribList & DocImage::attribs () const [inline]
Definition at line 620 of file docnode.h.
{ return p->attribs; }
References p.
Referenced by HtmlDocVisitor::operator()(), and XmlDocVisitor::operator()().
attribs() [2/2]
const HtmlAttribList & DocImage::attribs () const [inline]
Definition at line 620 of file docnode.h.
{ return p->attribs; }
References p.
hasCaption() [1/2]
bool DocImage::hasCaption () const [inline]
Definition at line 613 of file docnode.h.
{ return !children().empty(); }
References DocCompoundNode::children(), and GrowVector< T >::empty().
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), and RTFDocVisitor::operator()().
hasCaption() [2/2]
bool DocImage::hasCaption () const [inline]
Definition at line 613 of file docnode.h.
{ return !children().empty(); }
References DocCompoundNode::children(), and GrowVector< T >::empty().
height() [1/2]
QCString DocImage::height () const [inline]
Definition at line 615 of file docnode.h.
{ return p->height; }
References p.
Referenced by doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.compound.docImageType::get_height(), doxmlparser.compound.docDotMscType::get_height(), doxmlparser.compound.docImageFileType::get_height(), doxmlparser.compound.docPlantumlType::get_height(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), PerlModDocVisitor::operator()(), XmlDocVisitor::operator()(), PrintDocVisitor::operator()(), doxmlparser.compound.docImageType::set_height(), doxmlparser.compound.docDotMscType::set_height(), doxmlparser.compound.docImageFileType::set_height(), and doxmlparser.compound.docPlantumlType::set_height().
height() [2/2]
QCString DocImage::height () const [inline]
Definition at line 615 of file docnode.h.
{ return p->height; }
References p.
Referenced by doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.compound.docImageType::get_height(), doxmlparser.compound.docDotMscType::get_height(), doxmlparser.compound.docImageFileType::get_height(), doxmlparser.compound.docPlantumlType::get_height(), doxmlparser.compound.docImageType::set_height(), doxmlparser.compound.docDotMscType::set_height(), doxmlparser.compound.docImageFileType::set_height(), and doxmlparser.compound.docPlantumlType::set_height().
isInlineImage() [1/2]
bool DocImage::isInlineImage () const [inline]
Definition at line 618 of file docnode.h.
{ return p->inlineImage; }
References p.
Referenced by mustBeOutsideParagraph(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), and PrintDocVisitor::operator()().
isInlineImage() [2/2]
bool DocImage::isInlineImage () const [inline]
Definition at line 618 of file docnode.h.
{ return p->inlineImage; }
References p.
isSVG() [1/2]
bool DocImage::isSVG () const
Definition at line 1164 of file docnode.cpp.
{
  QCString locName = p->url.isEmpty() ? p->name : p->url;
  int len = static_cast<int>(locName.length());
  int fnd = locName.find('?'); // ignore part from ? until end
  if (fnd==-1) fnd=len;
  return fnd>=4 && locName.mid(fnd-4,4)==".svg";
}
References QCString::find(), len, QCString::length(), QCString::mid(), and p.
Referenced by HtmlDocVisitor::operator()().
isSVG() [2/2]
bool DocImage::isSVG () const
name() [1/2]
QCString DocImage::name () const [inline]
Definition at line 612 of file docnode.h.
{ return p->name; }
References p.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), PerlModDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), PrintDocVisitor::operator()(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
name() [2/2]
QCString DocImage::name () const [inline]
Definition at line 612 of file docnode.h.
{ return p->name; }
References p.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
parse() [1/2]
void DocImage::parse (DocNodeVariant * thisVariant)
Definition at line 1173 of file docnode.cpp.
{
  parser()->defaultHandleTitleAndSize(CMD_IMAGE,thisVariant,children(),p->width,p->height);
}
References DocCompoundNode::children(), CMD_IMAGE, DocParser::defaultHandleTitleAndSize(), p, and DocNode::parser().
parse() [2/2]
void DocImage::parse (DocNodeVariant *)
relPath() [1/2]
QCString DocImage::relPath () const [inline]
Definition at line 616 of file docnode.h.
{ return p->relPath; }
References p.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), and XmlDocVisitor::operator()().
relPath() [2/2]
QCString DocImage::relPath () const [inline]
Definition at line 616 of file docnode.h.
{ return p->relPath; }
References p.
type() [1/2]
Type DocImage::type () const [inline]
Definition at line 611 of file docnode.h.
{ return p->type; }
References p.
Referenced by isInvisibleNode(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), PerlModDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), and PrintDocVisitor::operator()().
type() [2/2]
Type DocImage::type () const [inline]
Definition at line 611 of file docnode.h.
{ return p->type; }
References p.
url() [1/2]
QCString DocImage::url () const [inline]
Definition at line 617 of file docnode.h.
{ return p->url; }
References p.
Referenced by doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docURLLink::buildAttributes(), doxmlparser.compound.docURLLink::exportAttributes(), doxmlparser.compound.docURLLink::get_url(), HtmlDocVisitor::operator()(), XmlDocVisitor::operator()(), and doxmlparser.compound.docURLLink::set_url().
url() [2/2]
QCString DocImage::url () const [inline]
Definition at line 617 of file docnode.h.
{ return p->url; }
References p.
Referenced by doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docURLLink::buildAttributes(), doxmlparser.compound.docURLLink::exportAttributes(), doxmlparser.compound.docURLLink::get_url(), and doxmlparser.compound.docURLLink::set_url().
width() [1/2]
QCString DocImage::width () const [inline]
Definition at line 614 of file docnode.h.
{ return p->width; }
References p.
Referenced by doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docTableType::__init__(), doxmlparser.compound.docEntryType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docTableType::buildAttributes(), doxmlparser.compound.docEntryType::buildAttributes(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEntryType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.compound.docTableType::exportAttributes(), doxmlparser.compound.docTableType::get_width(), doxmlparser.compound.docEntryType::get_width(), doxmlparser.compound.docImageType::get_width(), doxmlparser.compound.docDotMscType::get_width(), doxmlparser.compound.docImageFileType::get_width(), doxmlparser.compound.docPlantumlType::get_width(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), PerlModDocVisitor::operator()(), XmlDocVisitor::operator()(), PrintDocVisitor::operator()(), doxmlparser.compound.docTableType::set_width(), doxmlparser.compound.docEntryType::set_width(), doxmlparser.compound.docImageType::set_width(), doxmlparser.compound.docDotMscType::set_width(), doxmlparser.compound.docImageFileType::set_width(), and doxmlparser.compound.docPlantumlType::set_width().
width() [2/2]
QCString DocImage::width () const [inline]
Definition at line 614 of file docnode.h.
{ return p->width; }
References p.
Referenced by doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docTableType::__init__(), doxmlparser.compound.docEntryType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docTableType::buildAttributes(), doxmlparser.compound.docEntryType::buildAttributes(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEntryType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.compound.docTableType::exportAttributes(), doxmlparser.compound.docTableType::get_width(), doxmlparser.compound.docEntryType::get_width(), doxmlparser.compound.docImageType::get_width(), doxmlparser.compound.docDotMscType::get_width(), doxmlparser.compound.docImageFileType::get_width(), doxmlparser.compound.docPlantumlType::get_width(), doxmlparser.compound.docTableType::set_width(), doxmlparser.compound.docEntryType::set_width(), doxmlparser.compound.docImageType::set_width(), doxmlparser.compound.docDotMscType::set_width(), doxmlparser.compound.docImageFileType::set_width(), and doxmlparser.compound.docPlantumlType::set_width().
Member Data Documentation
p
std::unique_ptr< Private > DocImage::p [private]
Definition at line 639 of file docnode.h.
Referenced by attribs(), height(), isInlineImage(), isSVG(), name(), parse(), relPath(), type(), url(), and width().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docnode.h
doxygen/src/docnode.h
doxygen/build/doxygen/src/docnode.cpp
doxygen/src/docnode.cpp