TemplateNodeSpaceless Class Reference
Class representing an 'spaceless' tag in a template.
Public Member Functions
TemplateNodeSpaceless (TemplateParser *parser, TemplateNode *parent, int line, const QCString &)
void render (TextStream &ts, TemplateContext *c)
TemplateNodeSpaceless (TemplateParser *parser, TemplateNode *parent, int line, const QCString &)
void render (TextStream &ts, TemplateContext *c)
Private Attributes
TemplateNodeList m_nodes
Additional Inherited Members
Detailed Description
Class representing an 'spaceless' tag in a template.
Definition at line 4365 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeSpaceless() [1/2]
TemplateNodeSpaceless::TemplateNodeSpaceless (TemplateParser * parser, TemplateNode * parent, int line, const QCString &) [inline]
Definition at line 4368 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeSpaceless>(parser,parent,line)
    {
      TRACE(("{TemplateNodeSpaceless()\n"));
      StringVector stopAt = { "endspaceless" };
      parser->parse(this,line,stopAt,m_nodes);
      parser->removeNextToken(); // skip over endwith
      TRACE(("}TemplateNodeSpaceless()\n"));
    }
References m_nodes, TemplateParser::parse(), TemplateParser::removeNextToken(), and TRACE.
TemplateNodeSpaceless() [2/2]
TemplateNodeSpaceless::TemplateNodeSpaceless (TemplateParser * parser, TemplateNode * parent, int line, const QCString &) [inline]
Definition at line 4368 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeSpaceless>(parser,parent,line)
    {
      TRACE(("{TemplateNodeSpaceless()\n"));
      StringVector stopAt = { "endspaceless" };
      parser->parse(this,line,stopAt,m_nodes);
      parser->removeNextToken(); // skip over endwith
      TRACE(("}TemplateNodeSpaceless()\n"));
    }
References m_nodes, TemplateParser::parse(), TemplateParser::removeNextToken(), and TRACE.
Member Function Documentation
render() [1/2]
void TemplateNodeSpaceless::render (TextStream & ts, TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 4377 of file template.cpp.
    {
      TemplateContextImpl *ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      bool wasSpaceless = ci->spacelessEnabled();
      ci->enableSpaceless(TRUE);
      m_nodes.render(ts,c);
      ci->enableSpaceless(wasSpaceless);
    }
References c, TemplateContextImpl::enableSpaceless(), TemplateNodeCreator< TemplateNodeSpaceless >::m_line, m_nodes, TemplateNodeCreator< TemplateNodeSpaceless >::m_templateName, TemplateNodeList::render(), TemplateContextImpl::setLocation(), TemplateContextImpl::spacelessEnabled(), and TRUE.
render() [2/2]
void TemplateNodeSpaceless::render (TextStream & ts, TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 4377 of file template.cpp.
    {
      TemplateContextImpl *ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      bool wasSpaceless = ci->spacelessEnabled();
      ci->enableSpaceless(TRUE);
      m_nodes.render(ts,c);
      ci->enableSpaceless(wasSpaceless);
    }
References c, TemplateContextImpl::enableSpaceless(), TemplateNodeCreator< TemplateNodeSpaceless >::m_line, m_nodes, TemplateNodeCreator< TemplateNodeSpaceless >::m_templateName, TemplateNodeList::render(), TemplateContextImpl::setLocation(), TemplateContextImpl::spacelessEnabled(), and TRUE.
Member Data Documentation
m_nodes
TemplateNodeList TemplateNodeSpaceless::m_nodes [private]
Definition at line 4388 of file template.cpp.
Referenced by render(), and TemplateNodeSpaceless().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp