InheritanceListContext::Private Class Reference
Public Member Functions
void addClass (const ClassDef *cd, const QCString &name)
void addClass (const ClassDef *cd, const QCString &name)
Additional Inherited Members
Detailed Description
Definition at line 7519 of file context.cpp.
Member Function Documentation
addClass() [1/2]
void InheritanceListContext::Private::addClass (const ClassDef * cd, const QCString & name) [inline]
Definition at line 7522 of file context.cpp.
    {
      append(InheritanceNodeContext::alloc(cd,name));
    }
References InheritanceNodeContext::alloc(), GenericNodeListContext::append(), and setup::name.
addClass() [2/2]
void InheritanceListContext::Private::addClass (const ClassDef * cd, const QCString & name) [inline]
Definition at line 7522 of file context.cpp.
    {
      append(InheritanceNodeContext::alloc(cd,name));
    }
References InheritanceNodeContext::alloc(), and setup::name.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp