EclipseHelp Class Reference
#include <eclipsehelp.h>
Classes
struct Private
Public Member Functions
EclipseHelp ()
virtual ~EclipseHelp ()
EclipseHelp (EclipseHelp &&)
virtual void initialize ()
Initialize the Eclipse generator.
virtual void finalize ()
Finish generation of the Eclipse specific help files.
virtual void incContentsDepth ()
Increase the level of content hierarchy.
virtual void decContentsDepth ()
Decrease the level of content hierarchy.
virtual void addContentsItem (bool isDir, const QCString &name, const QCString &ref, const QCString &file, const QCString &anchor, bool separateIndex, bool addToNavIndex, const Definition *def)
Add an item to the content.
virtual void addIndexItem (const Definition *context, const MemberDef *md, const QCString &sectionAnchor, const QCString &title)
virtual void addIndexFile (const QCString &name)
virtual void addImageFile (const QCString &name)
virtual void addStyleSheetFile (const QCString &name)
EclipseHelp ()
virtual ~EclipseHelp ()
EclipseHelp (EclipseHelp &&)
virtual void initialize ()
virtual void finalize ()
virtual void incContentsDepth ()
virtual void decContentsDepth ()
virtual void addContentsItem (bool isDir, const QCString &name, const QCString &ref, const QCString &file, const QCString &anchor, bool separateIndex, bool addToNavIndex, const Definition *def)
virtual void addIndexItem (const Definition *context, const MemberDef *md, const QCString &sectionAnchor, const QCString &title)
virtual void addIndexFile (const QCString &name)
virtual void addImageFile (const QCString &name)
virtual void addStyleSheetFile (const QCString &name)
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Generator for Eclipse help files.
This class generates the Eclipse specific help files. These files can be used to generate a help plugin readable by the Eclipse IDE.
Definition at line 41 of file eclipsehelp.h.
Constructor & Destructor Documentation
EclipseHelp() [1/4]
EclipseHelp::EclipseHelp ()
Definition at line 60 of file eclipsehelp.cpp.
: p(std::make_unique<Private>()) {}
 EclipseHelp() [1/2]
EclipseHelp::~EclipseHelp () [virtual], [default]
EclipseHelp() [2/4]
EclipseHelp::EclipseHelp (EclipseHelp &&) [default]
EclipseHelp() [3/4]
EclipseHelp::EclipseHelp ()
 EclipseHelp() [2/2]
virtual EclipseHelp::~EclipseHelp () [virtual]
EclipseHelp() [4/4]
EclipseHelp::EclipseHelp (EclipseHelp &&)
Member Function Documentation
addContentsItem() [1/2]
void EclipseHelp::addContentsItem (bool isDir, const QCString & name, const QCString & ref, const QCString & file, const QCString & anchor, bool separateIndex, bool addToNavIndex, const Definition * def) [virtual]
Add an item to the content.
Parameters
isDir Flag whether the argument file is a directory or a file entry
name Name of the item
ref URL of the item
file Name of a file which the item is defined in (without extension)
anchor Name of an anchor of the item.
separateIndex not used.
addToNavIndex not used.
def not used.
Definition at line 163 of file eclipsehelp.cpp.
{
  // -- write the topic tag
  p->closedTag();
  if (!file.isEmpty())
  {
    switch (file[0]) // check for special markers (user defined URLs)
    {
      case '^':
        // URL not supported by eclipse toc.xml
    break;
      case '!':
        p->indent();
        p->tocstream << "<topic label=\"" << convertToXML(name) << "\"";
        p->tocstream << " href=\"" << convertToXML(p->pathprefix) << &file[1] << "\"";
        p->endtag = TRUE;
    break;
      default:
        p->indent();
        p->tocstream << "<topic label=\"" << convertToXML(name) << "\"";
        p->tocstream << " href=\"" << convertToXML(p->pathprefix)
                    << addHtmlExtensionIfMissing(file);
        if (!anchor.isEmpty())
        {
          p->tocstream << "#" << anchor;
        }
        p->tocstream << "\"";
        p->endtag = TRUE;
    break;
    }
  }
  else
  {
    p->indent();
    p->tocstream << "<topic label=\"" << convertToXML(name) << "\"";
    p->endtag = TRUE;
  }
}
References addHtmlExtensionIfMissing(), convertToXML(), caseconvert::file, QCString::isEmpty(), setup::name, p, and TRUE.
addContentsItem() [2/2]
virtual void EclipseHelp::addContentsItem (bool isDir, const QCString & name, const QCString & ref, const QCString & file, const QCString & anchor, bool separateIndex, bool addToNavIndex, const Definition * def) [virtual]
addImageFile() [1/2]
void EclipseHelp::addImageFile (const QCString & name) [virtual]
Definition at line 224 of file eclipsehelp.cpp.
{
}
addImageFile() [2/2]
virtual void EclipseHelp::addImageFile (const QCString & name) [virtual]
addIndexFile() [1/2]
void EclipseHelp::addIndexFile (const QCString & name) [virtual]
Definition at line 220 of file eclipsehelp.cpp.
{
}
addIndexFile() [2/2]
virtual void EclipseHelp::addIndexFile (const QCString & name) [virtual]
addIndexItem() [1/2]
void EclipseHelp::addIndexItem (const Definition * context, const MemberDef * md, const QCString & sectionAnchor, const QCString & title) [virtual]
Definition at line 212 of file eclipsehelp.cpp.
{
}
addIndexItem() [2/2]
virtual void EclipseHelp::addIndexItem (const Definition * context, const MemberDef * md, const QCString & sectionAnchor, const QCString & title) [virtual]
addStyleSheetFile() [1/2]
void EclipseHelp::addStyleSheetFile (const QCString & name) [virtual]
Definition at line 228 of file eclipsehelp.cpp.
{
}
addStyleSheetFile() [2/2]
virtual void EclipseHelp::addStyleSheetFile (const QCString & name) [virtual]
decContentsDepth() [1/2]
void EclipseHelp::decContentsDepth () [virtual]
Decrease the level of content hierarchy.
It closes currently opened topic tag.
Definition at line 137 of file eclipsehelp.cpp.
{
  // -- end of the opened topic
  p->closedTag();
  --p->depth;
  if (p->openTags==p->depth)
  {
    --p->openTags;
    p->indent();
    p->tocstream << "</topic>\n";
  }
}
References p.
decContentsDepth() [2/2]
virtual void EclipseHelp::decContentsDepth () [virtual]
finalize() [1/2]
void EclipseHelp::finalize () [virtual]
Finish generation of the Eclipse specific help files.
This method writes footers of the files and closes them.
See also
initialize()
Definition at line 98 of file eclipsehelp.cpp.
{
  p->closedTag(); // -- close previous tag
  // -- write ending tag
  --p->depth;
  p->tocstream << "</toc>\n";
  // -- close the content file
  p->tocstream.close();
  QCString name = Config_getString(HTML_OUTPUT) + "/plugin.xml";
  std::ofstream t(name.str(),std::ofstream::out | std::ofstream::binary);
  if (t.is_open())
  {
    QCString docId = Config_getString(ECLIPSE_DOC_ID);
    t << "<plugin name=\"" << docId << "\" id=\"" << docId << "\"\n";
    t << " version=\"1.0.0\" provider-name=\"Doxygen\">\n";
    t << " <extension point=\"org.eclipse.help.toc\">\n";
    t << " <toc file=\"toc.xml\" primary=\"true\" />\n";
    t << " </extension>\n";
    t << "</plugin>\n";
  }
}
References Config_getString, setup::name, out, and p.
finalize() [2/2]
virtual void EclipseHelp::finalize () [virtual]
incContentsDepth() [1/2]
void EclipseHelp::incContentsDepth () [virtual]
Increase the level of content hierarchy.
Definition at line 126 of file eclipsehelp.cpp.
{
  p->openedTag();
  ++p->depth;
}
References p.
incContentsDepth() [2/2]
virtual void EclipseHelp::incContentsDepth () [virtual]
initialize() [1/2]
void EclipseHelp::initialize () [virtual]
Initialize the Eclipse generator.
This method opens the XML TOC file and writes headers of the files.
See also
finalize()
Definition at line 70 of file eclipsehelp.cpp.
{
  // -- open the contents file
  QCString name = Config_getString(HTML_OUTPUT) + "/toc.xml";
  p->tocstream.open(name.str(), std::ofstream::out | std::ofstream::binary);
  if (!p->tocstream.is_open())
  {
    term("Could not open file %s for writing\n", qPrint(name));
  }
  // -- write the opening tag
  QCString title = Config_getString(PROJECT_NAME);
  if (title.isEmpty())
  {
    title = "Doxygen generated documentation";
  }
  p->tocstream << "<toc label=\"" << convertToXML(title)
              << "\" topic=\"" << convertToXML(p->pathprefix)
              << "index" << Doxygen::htmlFileExtension << "\">\n";
  ++ p->depth;
}
References Config_getString, convertToXML(), Doxygen::htmlFileExtension, QCString::isEmpty(), setup::name, out, p, qPrint(), and term().
initialize() [2/2]
virtual void EclipseHelp::initialize () [virtual]
Member Data Documentation
p
std::unique_ptr< Private > EclipseHelp::p [private]
Definition at line 64 of file eclipsehelp.h.
Referenced by addContentsItem(), decContentsDepth(), finalize(), incContentsDepth(), and initialize().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/eclipsehelp.h
doxygen/src/eclipsehelp.h
doxygen/build/doxygen/src/eclipsehelp.cpp
doxygen/src/eclipsehelp.cpp