TranslatorItalian Class Reference
#include <translator_it.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
QCString trRelatedFunctions ()
QCString trRelatedSubscript ()
QCString trDetailedDescription ()
QCString trMemberTypedefDocumentation ()
QCString trMemberEnumerationDocumentation ()
QCString trMemberFunctionDocumentation ()
QCString trMemberDataDocumentation ()
QCString trMore ()
QCString trListOfAllMembers ()
QCString trMemberList ()
QCString trThisIsTheListOfAllMembers ()
QCString trIncludingInheritedMembers ()
QCString trGeneratedAutomatically (const QCString &s)
QCString trEnumName ()
QCString trEnumValue ()
QCString trDefinedIn ()
QCString trModules ()
QCString trClassHierarchy ()
QCString trCompoundList ()
QCString trFileList ()
QCString trCompoundMembers ()
QCString trFileMembers ()
QCString trRelatedPages ()
QCString trExamples ()
QCString trSearch ()
QCString trClassHierarchyDescription ()
QCString trFileListDescription (bool extractAll)
QCString trCompoundListDescription ()
QCString trCompoundMembersDescription (bool extractAll)
QCString trFileMembersDescription (bool extractAll)
QCString trExamplesDescription ()
QCString trRelatedPagesDescription ()
QCString trModulesDescription ()
QCString trDocumentation ()
QCString trModuleIndex ()
QCString trHierarchicalIndex ()
QCString trCompoundIndex ()
QCString trFileIndex ()
QCString trModuleDocumentation ()
QCString trClassDocumentation ()
QCString trFileDocumentation ()
QCString trExampleDocumentation ()
QCString trReferenceManual ()
QCString trDefines ()
QCString trTypedefs ()
QCString trEnumerations ()
QCString trFunctions ()
QCString trVariables ()
QCString trEnumerationValues ()
QCString trDefineDocumentation ()
QCString trTypedefDocumentation ()
QCString trEnumerationTypeDocumentation ()
QCString trFunctionDocumentation ()
QCString trVariableDocumentation ()
QCString trCompounds ()
QCString trGeneratedAt (const QCString &date, const QCString &projName)
QCString trClassDiagram (const QCString &clName)
QCString trWarning ()
QCString trVersion ()
QCString trDate ()
QCString trReturns ()
QCString trSeeAlso ()
QCString trParameters ()
QCString trExceptions ()
QCString trGeneratedBy ()
QCString trNamespaceList ()
QCString trNamespaceListDescription (bool extractAll)
QCString trFriends ()
QCString trRelatedFunctionDocumentation ()
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
QCString trFileReference (const QCString &fileName)
QCString trNamespaceReference (const QCString &namespaceName)
QCString trPublicMembers ()
QCString trPublicSlots ()
QCString trSignals ()
QCString trStaticPublicMembers ()
QCString trProtectedMembers ()
QCString trProtectedSlots ()
QCString trStaticProtectedMembers ()
QCString trPrivateMembers ()
QCString trPrivateSlots ()
QCString trStaticPrivateMembers ()
QCString trWriteList (int numEntries)
QCString trInheritsList (int numEntries)
QCString trInheritedByList (int numEntries)
QCString trReimplementedFromList (int numEntries)
QCString trReimplementedInList (int numEntries)
QCString trNamespaceMembers ()
QCString trNamespaceMemberDescription (bool extractAll)
QCString trNamespaceIndex ()
QCString trNamespaceDocumentation ()
QCString trNamespaces ()
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
QCString trReturnValues ()
QCString trMainPage ()
QCString trPageAbbreviation ()
QCString trDefinedAtLineInSourceFile ()
QCString trDefinedInSourceFile ()
QCString trDeprecated ()
QCString trCollaborationDiagram (const QCString &clName)
QCString trInclDepGraph (const QCString &fName)
QCString trConstructorDocumentation ()
QCString trGotoSourceCode ()
QCString trGotoDocumentation ()
QCString trPrecondition ()
QCString trPostcondition ()
QCString trInvariant ()
QCString trInitialValue ()
QCString trCode ()
QCString trGraphicalHierarchy ()
QCString trGotoGraphicalHierarchy ()
QCString trGotoTextualHierarchy ()
QCString trPageIndex ()
QCString trNote ()
QCString trPublicTypes ()
QCString trPublicAttribs ()
QCString trStaticPublicAttribs ()
QCString trProtectedTypes ()
QCString trProtectedAttribs ()
QCString trStaticProtectedAttribs ()
QCString trPrivateTypes ()
QCString trPrivateAttribs ()
QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool)
virtual QCString trNamespace (bool first_capital, bool)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
QCString trRelatedFunctions ()
QCString trRelatedSubscript ()
QCString trDetailedDescription ()
QCString trMemberTypedefDocumentation ()
QCString trMemberEnumerationDocumentation ()
QCString trMemberFunctionDocumentation ()
QCString trMemberDataDocumentation ()
QCString trMore ()
QCString trListOfAllMembers ()
QCString trMemberList ()
QCString trThisIsTheListOfAllMembers ()
QCString trIncludingInheritedMembers ()
QCString trGeneratedAutomatically (const QCString &s)
QCString trEnumName ()
QCString trEnumValue ()
QCString trDefinedIn ()
QCString trModules ()
QCString trClassHierarchy ()
QCString trCompoundList ()
QCString trFileList ()
QCString trCompoundMembers ()
QCString trFileMembers ()
QCString trRelatedPages ()
QCString trExamples ()
QCString trSearch ()
QCString trClassHierarchyDescription ()
QCString trFileListDescription (bool extractAll)
QCString trCompoundListDescription ()
QCString trCompoundMembersDescription (bool extractAll)
QCString trFileMembersDescription (bool extractAll)
QCString trExamplesDescription ()
QCString trRelatedPagesDescription ()
QCString trModulesDescription ()
QCString trDocumentation ()
QCString trModuleIndex ()
QCString trHierarchicalIndex ()
QCString trCompoundIndex ()
QCString trFileIndex ()
QCString trModuleDocumentation ()
QCString trClassDocumentation ()
QCString trFileDocumentation ()
QCString trExampleDocumentation ()
QCString trReferenceManual ()
QCString trDefines ()
QCString trTypedefs ()
QCString trEnumerations ()
QCString trFunctions ()
QCString trVariables ()
QCString trEnumerationValues ()
QCString trDefineDocumentation ()
QCString trTypedefDocumentation ()
QCString trEnumerationTypeDocumentation ()
QCString trFunctionDocumentation ()
QCString trVariableDocumentation ()
QCString trCompounds ()
QCString trGeneratedAt (const QCString &date, const QCString &projName)
QCString trClassDiagram (const QCString &clName)
QCString trWarning ()
QCString trVersion ()
QCString trDate ()
QCString trReturns ()
QCString trSeeAlso ()
QCString trParameters ()
QCString trExceptions ()
QCString trGeneratedBy ()
QCString trNamespaceList ()
QCString trNamespaceListDescription (bool extractAll)
QCString trFriends ()
QCString trRelatedFunctionDocumentation ()
QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
QCString trFileReference (const QCString &fileName)
QCString trNamespaceReference (const QCString &namespaceName)
QCString trPublicMembers ()
QCString trPublicSlots ()
QCString trSignals ()
QCString trStaticPublicMembers ()
QCString trProtectedMembers ()
QCString trProtectedSlots ()
QCString trStaticProtectedMembers ()
QCString trPrivateMembers ()
QCString trPrivateSlots ()
QCString trStaticPrivateMembers ()
QCString trWriteList (int numEntries)
QCString trInheritsList (int numEntries)
QCString trInheritedByList (int numEntries)
QCString trReimplementedFromList (int numEntries)
QCString trReimplementedInList (int numEntries)
QCString trNamespaceMembers ()
QCString trNamespaceMemberDescription (bool extractAll)
QCString trNamespaceIndex ()
QCString trNamespaceDocumentation ()
QCString trNamespaces ()
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
QCString trReturnValues ()
QCString trMainPage ()
QCString trPageAbbreviation ()
QCString trDefinedAtLineInSourceFile ()
QCString trDefinedInSourceFile ()
QCString trDeprecated ()
QCString trCollaborationDiagram (const QCString &clName)
QCString trInclDepGraph (const QCString &fName)
QCString trConstructorDocumentation ()
QCString trGotoSourceCode ()
QCString trGotoDocumentation ()
QCString trPrecondition ()
QCString trPostcondition ()
QCString trInvariant ()
QCString trInitialValue ()
QCString trCode ()
QCString trGraphicalHierarchy ()
QCString trGotoGraphicalHierarchy ()
QCString trGotoTextualHierarchy ()
QCString trPageIndex ()
QCString trNote ()
QCString trPublicTypes ()
QCString trPublicAttribs ()
QCString trStaticPublicAttribs ()
QCString trProtectedTypes ()
QCString trProtectedAttribs ()
QCString trStaticProtectedAttribs ()
QCString trPrivateTypes ()
QCString trPrivateAttribs ()
QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool)
virtual QCString trNamespace (bool first_capital, bool)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
Additional Inherited Members
Detailed Description
Definition at line 92 of file translator_it.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorItalian::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 119 of file translator_it.h.
    {
      return "0x410 Italian";
    }
getLanguageString() [2/2]
virtual QCString TranslatorItalian::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 119 of file translator_it.h.
    {
      return "0x410 Italian";
    }
idLanguage() [1/2]
virtual QCString TranslatorItalian::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 104 of file translator_it.h.
    { return "italian"; }
idLanguage() [2/2]
virtual QCString TranslatorItalian::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 104 of file translator_it.h.
    { return "italian"; }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorItalian::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method was designed for languages which do wish to use a babel package.
Implements Translator.
Definition at line 110 of file translator_it.h.
    {
      return "\\usepackage[italian]{babel}\n";
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorItalian::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method was designed for languages which do wish to use a babel package.
Implements Translator.
Definition at line 110 of file translator_it.h.
    {
      return "\\usepackage[italian]{babel}\n";
    }
trAdditionalInheritedMembers() [1/2]
virtual QCString TranslatorItalian::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1872 of file translator_it.h.
    { return "Altri membri ereditati"; }
trAdditionalInheritedMembers() [2/2]
virtual QCString TranslatorItalian::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1872 of file translator_it.h.
    { return "Altri membri ereditati"; }
trAll() [1/2]
virtual QCString TranslatorItalian::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1382 of file translator_it.h.
    {
      return "Tutto";
    }
trAll() [2/2]
virtual QCString TranslatorItalian::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1382 of file translator_it.h.
    {
      return "Tutto";
    }
trAndMore() [1/2]
virtual QCString TranslatorItalian::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1849 of file translator_it.h.
    { return "e altri "+number+" ..."; }
trAndMore() [2/2]
virtual QCString TranslatorItalian::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1849 of file translator_it.h.
    { return "e altri "+number+" ..."; }
trAttention() [1/2]
virtual QCString TranslatorItalian::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 981 of file translator_it.h.
    {
      return "Attenzione";
    }
trAttention() [2/2]
virtual QCString TranslatorItalian::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 981 of file translator_it.h.
    {
      return "Attenzione";
    }
trAuthor() [1/2]
virtual QCString TranslatorItalian::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1252 of file translator_it.h.
    {
      QCString result((first_capital ? "Autor" : "autor"));
      result+=(singular ? "e" : "i");
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorItalian::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1252 of file translator_it.h.
    {
      QCString result((first_capital ? "Autor" : "autor"));
      result+=(singular ? "e" : "i");
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorItalian::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1139 of file translator_it.h.
    {
      return "Bug";
    }
trBug() [2/2]
virtual QCString TranslatorItalian::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1139 of file translator_it.h.
    {
      return "Bug";
    }
trBugList() [1/2]
virtual QCString TranslatorItalian::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1144 of file translator_it.h.
    {
      return "Lista dei bug";
    }
trBugList() [2/2]
virtual QCString TranslatorItalian::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1144 of file translator_it.h.
    {
      return "Lista dei bug";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorItalian::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1502 of file translator_it.h.
    {
      return "Questo il grafo dei chiamanti di questa funzione:";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorItalian::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1502 of file translator_it.h.
    {
      return "Questo il grafo dei chiamanti di questa funzione:";
    }
trCallGraph() [1/2]
virtual QCString TranslatorItalian::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1387 of file translator_it.h.
    {
      return "Questo il grafo delle chiamate per questa funzione:";
    }
trCallGraph() [2/2]
virtual QCString TranslatorItalian::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1387 of file translator_it.h.
    {
      return "Questo il grafo delle chiamate per questa funzione:";
    }
trCiteReferences() [1/2]
virtual QCString TranslatorItalian::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1825 of file translator_it.h.
    { return "Riferimenti bibliografici"; }
trCiteReferences() [2/2]
virtual QCString TranslatorItalian::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1825 of file translator_it.h.
    { return "Riferimenti bibliografici"; }
trClass() [1/2]
virtual QCString TranslatorItalian::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1175 of file translator_it.h.
    {
      QCString result((first_capital ? "Class" : "class"));
      result+=(singular ? "e" : "i");
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorItalian::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1175 of file translator_it.h.
    {
      QCString result((first_capital ? "Class" : "class"));
      result+=(singular ? "e" : "i");
      return result;
    }
trClassDiagram() [1/2]
QCString TranslatorItalian::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 528 of file translator_it.h.
    {
      return "Diagramma delle classi per "+clName;
    }
trClassDiagram() [2/2]
QCString TranslatorItalian::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 528 of file translator_it.h.
    {
      return "Diagramma delle classi per "+clName;
    }
trClassDocumentation() [1/2]
QCString TranslatorItalian::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 416 of file translator_it.h.
    { return "Documentazione delle classi"; }
trClassDocumentation() [2/2]
QCString TranslatorItalian::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 416 of file translator_it.h.
    { return "Documentazione delle classi"; }
trClasses() [1/2]
virtual QCString TranslatorItalian::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1102 of file translator_it.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Strutture dati";
      }
      else
      {
          return "Classi";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorItalian::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1102 of file translator_it.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Strutture dati";
      }
      else
      {
          return "Classi";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
QCString TranslatorItalian::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 215 of file translator_it.h.
    { return "Gerarchia delle classi"; }
trClassHierarchy() [2/2]
QCString TranslatorItalian::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 215 of file translator_it.h.
    { return "Gerarchia delle classi"; }
trClassHierarchyDescription() [1/2]
QCString TranslatorItalian::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 274 of file translator_it.h.
    {
        return "Questo elenco di ereditariet ordinato "
        "approssimativamente, ma non completamente, in ordine alfabetico:";
    }
trClassHierarchyDescription() [2/2]
QCString TranslatorItalian::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 274 of file translator_it.h.
    {
        return "Questo elenco di ereditariet ordinato "
        "approssimativamente, ma non completamente, in ordine alfabetico:";
    }
trClassMethods() [1/2]
virtual QCString TranslatorItalian::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1910 of file translator_it.h.
    {
      return "Metodi della classe";
    }
trClassMethods() [2/2]
virtual QCString TranslatorItalian::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1910 of file translator_it.h.
    {
      return "Metodi della classe";
    }
trCode() [1/2]
QCString TranslatorItalian::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 880 of file translator_it.h.
    {
      return "codice";
    }
trCode() [2/2]
QCString TranslatorItalian::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 880 of file translator_it.h.
    {
      return "codice";
    }
trCollaborationDiagram() [1/2]
QCString TranslatorItalian::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 835 of file translator_it.h.
    {
      return "Diagramma di collaborazione per "+clName+":";
    }
trCollaborationDiagram() [2/2]
QCString TranslatorItalian::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 835 of file translator_it.h.
    {
      return "Diagramma di collaborazione per "+clName+":";
    }
trCompoundIndex() [1/2]
QCString TranslatorItalian::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 389 of file translator_it.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Indice delle strutture dati";
      }
      else
      {
        return "Indice dei tipi composti";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
QCString TranslatorItalian::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 389 of file translator_it.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Indice delle strutture dati";
      }
      else
      {
        return "Indice dei tipi composti";
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorItalian::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1556 of file translator_it.h.
    { return "Indice dei tipi dati"; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorItalian::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1556 of file translator_it.h.
    { return "Indice dei tipi dati"; }
trCompoundList() [1/2]
QCString TranslatorItalian::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 219 of file translator_it.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Strutture dati";
      }
      else
      {
        return "Elenco dei tipi composti";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
QCString TranslatorItalian::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 219 of file translator_it.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Strutture dati";
      }
      else
      {
        return "Elenco dei tipi composti";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
QCString TranslatorItalian::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 291 of file translator_it.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Queste sono le strutture dati con una loro breve descrizione:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Queste sono le classi con una loro breve descrizione:";
      }
      else
      {
        return "Queste sono le classi, le struct, le union e le interfacce con una loro breve descrizione:";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
QCString TranslatorItalian::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 291 of file translator_it.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Queste sono le strutture dati con una loro breve descrizione:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Queste sono le classi con una loro breve descrizione:";
      }
      else
      {
        return "Queste sono le classi, le struct, le union e le interfacce con una loro breve descrizione:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorItalian::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1530 of file translator_it.h.
    { return "Questi sono i tipi dato con una loro breve descrizione:"; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorItalian::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1530 of file translator_it.h.
    { return "Questi sono i tipi dato con una loro breve descrizione:"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorItalian::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1522 of file translator_it.h.
    { return "Elenco dei tipi di dato"; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorItalian::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1522 of file translator_it.h.
    { return "Elenco dei tipi di dato"; }
trCompoundMembers() [1/2]
QCString TranslatorItalian::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 236 of file translator_it.h.
     {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Campi dei dati";
      }
      else
      {
        return "Membri dei composti";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
QCString TranslatorItalian::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 236 of file translator_it.h.
     {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Campi dei dati";
      }
      else
      {
        return "Membri dei composti";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
QCString TranslatorItalian::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 309 of file translator_it.h.
    {
      QCString result="Questo un elenco ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        if (!extractAll) result+="delle struct e delle union documentate ";
        else result+="di tutte le struct e le union ";
      }
      else
      {
        if (!extractAll) result+="dei membri documentati ";
        else result+="di tutti i membri ";
      }
      result+="con collegamenti alla documentazione ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
          if (extractAll) result+="della struct/union per ciascun campo:";
          else result+="delle struct/union a cui appartengono:";
      }
      else
      {
          if (extractAll) result+="della classe a cui appartengono:";
          else result+="delle classi a cui appartengono:";
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
QCString TranslatorItalian::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 309 of file translator_it.h.
    {
      QCString result="Questo un elenco ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        if (!extractAll) result+="delle struct e delle union documentate ";
        else result+="di tutte le struct e le union ";
      }
      else
      {
        if (!extractAll) result+="dei membri documentati ";
        else result+="di tutti i membri ";
      }
      result+="con collegamenti alla documentazione ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
          if (extractAll) result+="della struct/union per ciascun campo:";
          else result+="delle struct/union a cui appartengono:";
      }
      else
      {
          if (extractAll) result+="della classe a cui appartengono:";
          else result+="delle classi a cui appartengono:";
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorItalian::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1534 of file translator_it.h.
    {
      QCString result="Questa una lista di tutti i membri ";
      if (!extractAll)
      {
        result+="documentati ";
      }
      result+="dei tipi di dato con collegamenti ";
      if (!extractAll)
      {
         result+="alla documentazione della struttura dati per ciascun membro:";
      }
      else
      {
         result+="ai tipi dato a cui appartengono:";
      }
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorItalian::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1534 of file translator_it.h.
    {
      QCString result="Questa una lista di tutti i membri ";
      if (!extractAll)
      {
        result+="documentati ";
      }
      result+="dei tipi di dato con collegamenti ";
      if (!extractAll)
      {
         result+="alla documentazione della struttura dati per ciascun membro:";
      }
      else
      {
         result+="ai tipi dato a cui appartengono:";
      }
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorItalian::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1526 of file translator_it.h.
    { return "Membri dei tipi di dato"; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorItalian::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1526 of file translator_it.h.
    { return "Membri dei tipi di dato"; }
trCompoundReference() [1/2]
QCString TranslatorItalian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 604 of file translator_it.h.
    {
      QCString result="Riferimenti per ";
      if (isTemplate) result="Template per ";
      switch(compType)
      {
        case ClassDef::Class: result+="la classe "; break;
        case ClassDef::Struct: result+="la struct "; break;
        case ClassDef::Union: result+="la union "; break;
        case ClassDef::Interface: result+="l'interfaccia "; break;
        case ClassDef::Protocol: result+="il protocollo "; break;
        case ClassDef::Category: result+="la categoria "; break;
        case ClassDef::Exception: result+="l'eccezione "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
QCString TranslatorItalian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 604 of file translator_it.h.
    {
      QCString result="Riferimenti per ";
      if (isTemplate) result="Template per ";
      switch(compType)
      {
        case ClassDef::Class: result+="la classe "; break;
        case ClassDef::Struct: result+="la struct "; break;
        case ClassDef::Union: result+="la union "; break;
        case ClassDef::Interface: result+="l'interfaccia "; break;
        case ClassDef::Protocol: result+="il protocollo "; break;
        case ClassDef::Category: result+="la categoria "; break;
        case ClassDef::Exception: result+="l'eccezione "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorItalian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1597 of file translator_it.h.
    {
      QCString result="Riferimenti per ";
      if (isTemplate) result="Template per ";
      switch(compType)
      {
        case ClassDef::Class: result+=" il modulo"; break;
        case ClassDef::Struct: result+=" il tipo dato"; break;
        case ClassDef::Union: result+=" l'union"; break;
        case ClassDef::Interface: result+=" l'nterfaccia"; break;
        case ClassDef::Protocol: result+=" il protocollo"; break;
        case ClassDef::Category: result+=" la categoria"; break;
        case ClassDef::Exception: result+=" l'eccezione"; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorItalian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1597 of file translator_it.h.
    {
      QCString result="Riferimenti per ";
      if (isTemplate) result="Template per ";
      switch(compType)
      {
        case ClassDef::Class: result+=" il modulo"; break;
        case ClassDef::Struct: result+=" il tipo dato"; break;
        case ClassDef::Union: result+=" l'union"; break;
        case ClassDef::Interface: result+=" l'nterfaccia"; break;
        case ClassDef::Protocol: result+=" il protocollo"; break;
        case ClassDef::Category: result+=" la categoria"; break;
        case ClassDef::Exception: result+=" l'eccezione"; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
QCString TranslatorItalian::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 504 of file translator_it.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Strutture dati";
      }
      else
      {
        return "Composti";
      }
    }
References Config_getBool.
trCompounds() [2/2]
QCString TranslatorItalian::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 504 of file translator_it.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Strutture dati";
      }
      else
      {
        return "Composti";
      }
    }
References Config_getBool.
trConstantGroupReference() [1/2]
virtual QCString TranslatorItalian::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1947 of file translator_it.h.
    {
      QCString result="Riferimenti per il gruppo di costanti ";
      result+=namespaceName;
      return result;
    }
trConstantGroupReference() [2/2]
virtual QCString TranslatorItalian::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1947 of file translator_it.h.
    {
      QCString result="Riferimenti per il gruppo di costanti ";
      result+=namespaceName;
      return result;
    }
trConstantGroups() [1/2]
virtual QCString TranslatorItalian::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1943 of file translator_it.h.
    { return "Gruppi di costanti"; }
trConstantGroups() [2/2]
virtual QCString TranslatorItalian::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1943 of file translator_it.h.
    { return "Gruppi di costanti"; }
trConstructorDocumentation() [1/2]
QCString TranslatorItalian::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 845 of file translator_it.h.
    {
      return "Documentazione dei costruttori e dei distruttori";
    }
trConstructorDocumentation() [2/2]
QCString TranslatorItalian::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 845 of file translator_it.h.
    {
      return "Documentazione dei costruttori e dei distruttori";
    }
trCopyright() [1/2]
virtual QCString TranslatorItalian::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1829 of file translator_it.h.
    { return "Copyright"; }
trCopyright() [2/2]
virtual QCString TranslatorItalian::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1829 of file translator_it.h.
    { return "Copyright"; }
trDataTypes() [1/2]
virtual QCString TranslatorItalian::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1580 of file translator_it.h.
    { return "Tipi di dato"; }
trDataTypes() [2/2]
virtual QCString TranslatorItalian::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1580 of file translator_it.h.
    { return "Tipi di dato"; }
trDate() [1/2]
QCString TranslatorItalian::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 542 of file translator_it.h.
    { return "Data"; }
trDate() [2/2]
QCString TranslatorItalian::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 542 of file translator_it.h.
    { return "Data"; }
trDateTime() [1/2]
virtual QCString TranslatorItalian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1782 of file translator_it.h.
    {
      static const char *days[] = { "Lun","Mar","Mer","Gio","Ven","Sab","Dom" };
      static const char *months[] = { "Gen","Feb","Mar","Apr","Mag","Giu","Lug","Ago","Set","Ott","Nov","Dic" };
      QCString sdate;
      sdate.sprintf("%s %d %s %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDateTime() [2/2]
virtual QCString TranslatorItalian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1782 of file translator_it.h.
    {
      static const char *days[] = { "Lun","Mar","Mer","Gio","Ven","Sab","Dom" };
      static const char *months[] = { "Gen","Feb","Mar","Apr","Mag","Giu","Lug","Ago","Set","Ott","Nov","Dic" };
      QCString sdate;
      sdate.sprintf("%s %d %s %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDayOfWeek() [1/2]
virtual QCString TranslatorItalian::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1798 of file translator_it.h.
    {
      static const char *days_short[] = { "lun", "mar", "mer", "gio", "ven", "sab", "dom" };
      static const char *days_full[] = { "luned", "marted", "mercoled", "gioved", "venerd", "sabato", "domenica" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayOfWeek() [2/2]
virtual QCString TranslatorItalian::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1798 of file translator_it.h.
    {
      static const char *days_short[] = { "lun", "mar", "mer", "gio", "ven", "sab", "dom" };
      static const char *days_full[] = { "luned", "marted", "mercoled", "gioved", "venerd", "sabato", "domenica" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod() [1/2]
virtual QCString TranslatorItalian::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1814 of file translator_it.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorItalian::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1814 of file translator_it.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
QCString TranslatorItalian::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 812 of file translator_it.h.
    {
      return "Definizione alla linea @0 del file @1.";
    }
trDefinedAtLineInSourceFile() [2/2]
QCString TranslatorItalian::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 812 of file translator_it.h.
    {
      return "Definizione alla linea @0 del file @1.";
    }
trDefinedIn() [1/2]
QCString TranslatorItalian::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 203 of file translator_it.h.
    { return "definito in"; }
trDefinedIn() [2/2]
QCString TranslatorItalian::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 203 of file translator_it.h.
    { return "definito in"; }
trDefinedInSourceFile() [1/2]
QCString TranslatorItalian::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 816 of file translator_it.h.
    {
      return "Definizione nel file @0.";
    }
trDefinedInSourceFile() [2/2]
QCString TranslatorItalian::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 816 of file translator_it.h.
    {
      return "Definizione nel file @0.";
    }
trDefineDocumentation() [1/2]
QCString TranslatorItalian::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 474 of file translator_it.h.
    { return "Documentazione delle definizioni"; }
trDefineDocumentation() [2/2]
QCString TranslatorItalian::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 474 of file translator_it.h.
    { return "Documentazione delle definizioni"; }
trDefines() [1/2]
QCString TranslatorItalian::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 438 of file translator_it.h.
    { return "Definizioni"; }
trDefines() [2/2]
QCString TranslatorItalian::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 438 of file translator_it.h.
    { return "Definizioni"; }
trDefineValue() [1/2]
virtual QCString TranslatorItalian::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1129 of file translator_it.h.
    {
      return "Valore:";
    }
trDefineValue() [2/2]
virtual QCString TranslatorItalian::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1129 of file translator_it.h.
    {
      return "Valore:";
    }
trDeprecated() [1/2]
QCString TranslatorItalian::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 825 of file translator_it.h.
    {
      return "Deprecato";
    }
trDeprecated() [2/2]
QCString TranslatorItalian::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 825 of file translator_it.h.
    {
      return "Deprecato";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorItalian::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1309 of file translator_it.h.
    {
      return "Lista degli elementi deprecati";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorItalian::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1309 of file translator_it.h.
    {
      return "Lista degli elementi deprecati";
    }
trDetailedDescription() [1/2]
QCString TranslatorItalian::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 135 of file translator_it.h.
    { return "Descrizione dettagliata"; }
trDetailedDescription() [2/2]
QCString TranslatorItalian::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 135 of file translator_it.h.
    { return "Descrizione dettagliata"; }
trDetailLevel() [1/2]
virtual QCString TranslatorItalian::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1841 of file translator_it.h.
    { return "livello di dettaglio"; }
trDetailLevel() [2/2]
virtual QCString TranslatorItalian::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1841 of file translator_it.h.
    { return "livello di dettaglio"; }
trDir() [1/2]
virtual QCString TranslatorItalian::trDir (bool first_capital, bool) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1477 of file translator_it.h.
    {
      QCString result((first_capital ? "Directory" : "directory"));
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorItalian::trDir (bool first_capital, bool) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1477 of file translator_it.h.
    {
      QCString result((first_capital ? "Directory" : "directory"));
      return result;
    }
trDirDepGraph() [1/2]
virtual QCString TranslatorItalian::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1833 of file translator_it.h.
    { return QCString("Grafo di dipendenza delle directory per ")+name+":"; }
References setup::name.
trDirDepGraph() [2/2]
virtual QCString TranslatorItalian::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1833 of file translator_it.h.
    { return QCString("Grafo di dipendenza delle directory per ")+name+":"; }
References setup::name.
trDirDocumentation() [1/2]
virtual QCString TranslatorItalian::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1459 of file translator_it.h.
    { return "Documentazione delle directory"; }
trDirDocumentation() [2/2]
virtual QCString TranslatorItalian::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1459 of file translator_it.h.
    { return "Documentazione delle directory"; }
trDirectories() [1/2]
virtual QCString TranslatorItalian::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1465 of file translator_it.h.
    { return "Directory"; }
trDirectories() [2/2]
virtual QCString TranslatorItalian::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1465 of file translator_it.h.
    { return "Directory"; }
trDirIndex() [1/2]
virtual QCString TranslatorItalian::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1453 of file translator_it.h.
    { return "Gerarchia delle directory"; }
trDirIndex() [2/2]
virtual QCString TranslatorItalian::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1453 of file translator_it.h.
    { return "Gerarchia delle directory"; }
trDirReference() [1/2]
virtual QCString TranslatorItalian::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1471 of file translator_it.h.
    { QCString result="Riferimenti per la directory "; result+=dirName; return result; }
trDirReference() [2/2]
virtual QCString TranslatorItalian::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1471 of file translator_it.h.
    { QCString result="Riferimenti per la directory "; result+=dirName; return result; }
trDirRelation() [1/2]
virtual QCString TranslatorItalian::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1721 of file translator_it.h.
    {
      return "Relazione per "+QCString(name);
    }
References setup::name.
trDirRelation() [2/2]
virtual QCString TranslatorItalian::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1721 of file translator_it.h.
    {
      return "Relazione per "+QCString(name);
    }
References setup::name.
trDocumentation() [1/2]
QCString TranslatorItalian::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 371 of file translator_it.h.
    { return "Documentazione"; }
trDocumentation() [2/2]
QCString TranslatorItalian::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 371 of file translator_it.h.
    { return "Documentazione"; }
trEnumerations() [1/2]
QCString TranslatorItalian::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 450 of file translator_it.h.
    { return "Tipi enumerati (enum)"; }
trEnumerations() [2/2]
QCString TranslatorItalian::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 450 of file translator_it.h.
    { return "Tipi enumerati (enum)"; }
trEnumerationTypeDocumentation() [1/2]
QCString TranslatorItalian::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 486 of file translator_it.h.
    { return "Documentazione dei tipi enumerati"; }
trEnumerationTypeDocumentation() [2/2]
QCString TranslatorItalian::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 486 of file translator_it.h.
    { return "Documentazione dei tipi enumerati"; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorItalian::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1510 of file translator_it.h.
    { return "Documentazione dei tipi enumerati"; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorItalian::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1510 of file translator_it.h.
    { return "Documentazione dei tipi enumerati"; }
trEnumerationValues() [1/2]
QCString TranslatorItalian::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 468 of file translator_it.h.
    { return "Valori del tipo enumerato"; }
trEnumerationValues() [2/2]
QCString TranslatorItalian::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 468 of file translator_it.h.
    { return "Valori del tipo enumerato"; }
trEnumGeneratedFromFiles() [1/2]
virtual QCString TranslatorItalian::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1853 of file translator_it.h.
    { QCString result = "La documentazione per questo tipo enumerato stata generata a partire";
      if (!single) result += " dai seguenti";
      else result += " dal seguente";
      result+=" file:";
      return result;
    }
trEnumGeneratedFromFiles() [2/2]
virtual QCString TranslatorItalian::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1853 of file translator_it.h.
    { QCString result = "La documentazione per questo tipo enumerato stata generata a partire";
      if (!single) result += " dai seguenti";
      else result += " dal seguente";
      result+=" file:";
      return result;
    }
trEnumName() [1/2]
QCString TranslatorItalian::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 195 of file translator_it.h.
    { return "nome di tipo enumerato"; }
trEnumName() [2/2]
QCString TranslatorItalian::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 195 of file translator_it.h.
    { return "nome di tipo enumerato"; }
trEnumReference() [1/2]
virtual QCString TranslatorItalian::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1862 of file translator_it.h.
    { return QCString("Riferimenti per il tipo enumerato ") + QCString(name); }
References setup::name.
trEnumReference() [2/2]
virtual QCString TranslatorItalian::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1862 of file translator_it.h.
    { return QCString("Riferimenti per il tipo enumerato ") + QCString(name); }
References setup::name.
trEnumValue() [1/2]
QCString TranslatorItalian::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 199 of file translator_it.h.
    { return "valore di tipo enumerato"; }
trEnumValue() [2/2]
QCString TranslatorItalian::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 199 of file translator_it.h.
    { return "valore di tipo enumerato"; }
trEventDocumentation() [1/2]
virtual QCString TranslatorItalian::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1326 of file translator_it.h.
    {
      return "Documentazione degli eventi";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorItalian::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1326 of file translator_it.h.
    {
      return "Documentazione degli eventi";
    }
trEvents() [1/2]
virtual QCString TranslatorItalian::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1321 of file translator_it.h.
    {
      return "Eventi";
    }
trEvents() [2/2]
virtual QCString TranslatorItalian::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1321 of file translator_it.h.
    {
      return "Eventi";
    }
trExampleDocumentation() [1/2]
QCString TranslatorItalian::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 428 of file translator_it.h.
    { return "Documentazione degli esempi"; }
trExampleDocumentation() [2/2]
QCString TranslatorItalian::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 428 of file translator_it.h.
    { return "Documentazione degli esempi"; }
trExamples() [1/2]
QCString TranslatorItalian::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 266 of file translator_it.h.
    { return "Esempi"; }
trExamples() [2/2]
QCString TranslatorItalian::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 266 of file translator_it.h.
    { return "Esempi"; }
trExamplesDescription() [1/2]
QCString TranslatorItalian::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 357 of file translator_it.h.
    { return "Questo l'elenco di tutti gli esempi:"; }
trExamplesDescription() [2/2]
QCString TranslatorItalian::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 357 of file translator_it.h.
    { return "Questo l'elenco di tutti gli esempi:"; }
trExceptions() [1/2]
QCString TranslatorItalian::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 558 of file translator_it.h.
    { return "Eccezioni"; }
trExceptions() [2/2]
QCString TranslatorItalian::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 558 of file translator_it.h.
    { return "Eccezioni"; }
trExtendsClass() [1/2]
virtual QCString TranslatorItalian::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1902 of file translator_it.h.
    {
      return "Estende la classe @0.";
    }
trExtendsClass() [2/2]
virtual QCString TranslatorItalian::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1902 of file translator_it.h.
    {
      return "Estende la classe @0.";
    }
trFile() [1/2]
virtual QCString TranslatorItalian::trFile (bool first_capital, bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1186 of file translator_it.h.
    {
      QCString result((first_capital ? "File" : "file"));
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorItalian::trFile (bool first_capital, bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1186 of file translator_it.h.
    {
      QCString result((first_capital ? "File" : "file"));
      return result;
    }
trFileDocumentation() [1/2]
QCString TranslatorItalian::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 422 of file translator_it.h.
    { return "Documentazione dei file"; }
trFileDocumentation() [2/2]
QCString TranslatorItalian::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 422 of file translator_it.h.
    { return "Documentazione dei file"; }
trFileIn() [1/2]
virtual QCString TranslatorItalian::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1758 of file translator_it.h.
    {
      return "File in "+name;
    }
References setup::name.
trFileIn() [2/2]
virtual QCString TranslatorItalian::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1758 of file translator_it.h.
    {
      return "File in "+name;
    }
References setup::name.
trFileIndex() [1/2]
QCString TranslatorItalian::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 404 of file translator_it.h.
    { return "Indice dei file"; }
trFileIndex() [2/2]
QCString TranslatorItalian::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 404 of file translator_it.h.
    { return "Indice dei file"; }
trFileList() [1/2]
QCString TranslatorItalian::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 232 of file translator_it.h.
    { return "Elenco dei file"; }
trFileList() [2/2]
QCString TranslatorItalian::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 232 of file translator_it.h.
    { return "Elenco dei file"; }
trFileListDescription() [1/2]
QCString TranslatorItalian::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 281 of file translator_it.h.
    {
      QCString result="Questo un elenco ";
      if (!extractAll) result+="dei file documentati ";
      else result+="di tutti i file ";
      result+="con una loro breve descrizione:";
      return result;
    }
trFileListDescription() [2/2]
QCString TranslatorItalian::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 281 of file translator_it.h.
    {
      QCString result="Questo un elenco ";
      if (!extractAll) result+="dei file documentati ";
      else result+="di tutti i file ";
      result+="con una loro breve descrizione:";
      return result;
    }
trFileMembers() [1/2]
QCString TranslatorItalian::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 249 of file translator_it.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Elementi globali";
      }
      else
      {
        return "Elementi dei file";
      }
    }
References Config_getBool.
trFileMembers() [2/2]
QCString TranslatorItalian::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 249 of file translator_it.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Elementi globali";
      }
      else
      {
        return "Elementi dei file";
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
QCString TranslatorItalian::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 337 of file translator_it.h.
    {
      QCString result="Questo un elenco ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
          if (!extractAll) result+="delle funzioni, delle variabili, delle define, dei tipi enumerati e delle ridefinizioni dei tipi (typedef) documentate ";
          else result+="di tutte le funzioni, variabili, define, tipi enumerati, e ridefinizioni dei tipi (typedef) ";
      }
      else
      {
          if (!extractAll) result+="degli elementi documentati dei file ";
          else result+="di tutti gli elementi dei file ";
      }
      result+="con collegamenti alla documentazione";
      if (extractAll) result+=" del file a cui appartengono:";
      else result+=":";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
QCString TranslatorItalian::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 337 of file translator_it.h.
    {
      QCString result="Questo un elenco ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
          if (!extractAll) result+="delle funzioni, delle variabili, delle define, dei tipi enumerati e delle ridefinizioni dei tipi (typedef) documentate ";
          else result+="di tutte le funzioni, variabili, define, tipi enumerati, e ridefinizioni dei tipi (typedef) ";
      }
      else
      {
          if (!extractAll) result+="degli elementi documentati dei file ";
          else result+="di tutti gli elementi dei file ";
      }
      result+="con collegamenti alla documentazione";
      if (extractAll) result+=" del file a cui appartengono:";
      else result+=":";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
QCString TranslatorItalian::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 627 of file translator_it.h.
    {
      QCString result="Riferimenti per il file ";
      result+=fileName;
      return result;
    }
trFileReference() [2/2]
QCString TranslatorItalian::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 627 of file translator_it.h.
    {
      QCString result="Riferimenti per il file ";
      result+=fileName;
      return result;
    }
trFriends() [1/2]
QCString TranslatorItalian::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 586 of file translator_it.h.
    { return "Friend"; }
trFriends() [2/2]
QCString TranslatorItalian::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 586 of file translator_it.h.
    { return "Friend"; }
trFunctionDocumentation() [1/2]
QCString TranslatorItalian::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 492 of file translator_it.h.
    { return "Documentazione delle funzioni"; }
trFunctionDocumentation() [2/2]
QCString TranslatorItalian::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 492 of file translator_it.h.
    { return "Documentazione delle funzioni"; }
trFunctions() [1/2]
QCString TranslatorItalian::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 456 of file translator_it.h.
    { return "Funzioni"; }
trFunctions() [2/2]
QCString TranslatorItalian::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 456 of file translator_it.h.
    { return "Funzioni"; }
trGeneratedAt() [1/2]
QCString TranslatorItalian::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 519 of file translator_it.h.
    {
      QCString result="Generato "+date;
      if (!projName.isEmpty()) result+=" per "+projName;
      result+=" da";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
QCString TranslatorItalian::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 519 of file translator_it.h.
    {
      QCString result="Generato "+date;
      if (!projName.isEmpty()) result+=" per "+projName;
      result+=" da";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
QCString TranslatorItalian::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 186 of file translator_it.h.
    {
      QCString result="Generato automaticamente da Doxygen";
      if (!s.isEmpty()) result+=" per "+s;
      result+=" a partire dal codice sorgente.";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
QCString TranslatorItalian::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 186 of file translator_it.h.
    {
      QCString result="Generato automaticamente da Doxygen";
      if (!s.isEmpty()) result+=" per "+s;
      result+=" a partire dal codice sorgente.";
      return result;
    }
References s.
trGeneratedBy() [1/2]
QCString TranslatorItalian::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 562 of file translator_it.h.
    { return "Generato da"; }
trGeneratedBy() [2/2]
QCString TranslatorItalian::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 562 of file translator_it.h.
    { return "Generato da"; }
trGeneratedFromFiles() [1/2]
QCString TranslatorItalian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 767 of file translator_it.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="La documentazione per quest";
      switch(compType)
      {
        case ClassDef::Class: result+="a classe"; break;
        case ClassDef::Struct: result+="a struct"; break;
        case ClassDef::Union: result+="a union"; break;
        case ClassDef::Interface: result+="a interfaccia"; break;
        case ClassDef::Protocol: result+="o protocollo"; break;
        case ClassDef::Category: result+="a categoria"; break;
        case ClassDef::Exception: result+="a eccezione"; break;
        default: break;
      }
      result+=" stata generata a partire ";
      if (single) result+="dal seguente file:";
      else result+="dai seguenti file:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
QCString TranslatorItalian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 767 of file translator_it.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="La documentazione per quest";
      switch(compType)
      {
        case ClassDef::Class: result+="a classe"; break;
        case ClassDef::Struct: result+="a struct"; break;
        case ClassDef::Union: result+="a union"; break;
        case ClassDef::Interface: result+="a interfaccia"; break;
        case ClassDef::Protocol: result+="o protocollo"; break;
        case ClassDef::Category: result+="a categoria"; break;
        case ClassDef::Exception: result+="a eccezione"; break;
        default: break;
      }
      result+=" stata generata a partire ";
      if (single) result+="dal seguente file:";
      else result+="dai seguenti file:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorItalian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1667 of file translator_it.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="La documentazione per quest";
      switch(compType)
      {
        case ClassDef::Class: result+="o modulo"; break;
        case ClassDef::Struct: result+="o tipo"; break;
        case ClassDef::Union: result+="a union"; break;
        case ClassDef::Interface: result+="a interfaccia"; break;
        case ClassDef::Protocol: result+="o protocollo"; break;
        case ClassDef::Category: result+="a categoria"; break;
        case ClassDef::Exception: result+="a eccezione"; break;
        default: break;
      }
      result+=" stata generata a partire ";
      if (single) result+="dal seguente file:"; else result+="dai seguenti file:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorItalian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1667 of file translator_it.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="La documentazione per quest";
      switch(compType)
      {
        case ClassDef::Class: result+="o modulo"; break;
        case ClassDef::Struct: result+="o tipo"; break;
        case ClassDef::Union: result+="a union"; break;
        case ClassDef::Interface: result+="a interfaccia"; break;
        case ClassDef::Protocol: result+="o protocollo"; break;
        case ClassDef::Category: result+="a categoria"; break;
        case ClassDef::Exception: result+="a eccezione"; break;
        default: break;
      }
      result+=" stata generata a partire ";
      if (single) result+="dal seguente file:"; else result+="dai seguenti file:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorItalian::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1239 of file translator_it.h.
    {
      QCString result((first_capital ? "Global" : "global"));
      result+=(singular ? "e" : "i");
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorItalian::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1239 of file translator_it.h.
    {
      QCString result((first_capital ? "Global" : "global"));
      result+=(singular ? "e" : "i");
      return result;
    }
trGlobalNamespace() [1/2]
virtual QCString TranslatorItalian::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1733 of file translator_it.h.
    {
      return "Namespace globale";
    }
trGlobalNamespace() [2/2]
virtual QCString TranslatorItalian::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1733 of file translator_it.h.
    {
      return "Namespace globale";
    }
trGotoDocumentation() [1/2]
QCString TranslatorItalian::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 855 of file translator_it.h.
    {
      return "Vai alla documentazione di questo file.";
    }
trGotoDocumentation() [2/2]
QCString TranslatorItalian::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 855 of file translator_it.h.
    {
      return "Vai alla documentazione di questo file.";
    }
trGotoGraphicalHierarchy() [1/2]
QCString TranslatorItalian::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 888 of file translator_it.h.
    {
      return "Vai al grafico della gerarchia delle classi";
    }
trGotoGraphicalHierarchy() [2/2]
QCString TranslatorItalian::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 888 of file translator_it.h.
    {
      return "Vai al grafico della gerarchia delle classi";
    }
trGotoSourceCode() [1/2]
QCString TranslatorItalian::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 850 of file translator_it.h.
    {
      return "Vai al codice sorgente di questo file.";
    }
trGotoSourceCode() [2/2]
QCString TranslatorItalian::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 850 of file translator_it.h.
    {
      return "Vai al codice sorgente di questo file.";
    }
trGotoTextualHierarchy() [1/2]
QCString TranslatorItalian::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 892 of file translator_it.h.
    {
      return "Vai alla gerarchia delle classi (testuale)";
    }
trGotoTextualHierarchy() [2/2]
QCString TranslatorItalian::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 892 of file translator_it.h.
    {
      return "Vai alla gerarchia delle classi (testuale)";
    }
trGraphicalHierarchy() [1/2]
QCString TranslatorItalian::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 884 of file translator_it.h.
    {
      return "Grafico della gerarchia delle classi";
    }
trGraphicalHierarchy() [2/2]
QCString TranslatorItalian::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 884 of file translator_it.h.
    {
      return "Grafico della gerarchia delle classi";
    }
trGroup() [1/2]
virtual QCString TranslatorItalian::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1206 of file translator_it.h.
    {
      QCString result((first_capital ? "Grupp" : "grupp"));
      result+=(singular ? "o" : "i");
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorItalian::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1206 of file translator_it.h.
    {
      QCString result((first_capital ? "Grupp" : "grupp"));
      result+=(singular ? "o" : "i");
      return result;
    }
trHierarchicalIndex() [1/2]
QCString TranslatorItalian::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 383 of file translator_it.h.
    { return "Indice della gerarchia"; }
trHierarchicalIndex() [2/2]
QCString TranslatorItalian::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 383 of file translator_it.h.
    { return "Indice della gerarchia"; }
trImplementedFromList() [1/2]
virtual QCString TranslatorItalian::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1277 of file translator_it.h.
    {
      return "Implementa "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorItalian::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1277 of file translator_it.h.
    {
      return "Implementa "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorItalian::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implementation this member.
Implements Translator.
Definition at line 1285 of file translator_it.h.
    {
      return "Implementato in "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorItalian::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implementation this member.
Implements Translator.
Definition at line 1285 of file translator_it.h.
    {
      return "Implementato in "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorItalian::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 985 of file translator_it.h.
    {
      return "Questo grafo mostra quali altri file includono direttamente o indirettamente questo file:";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorItalian::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 985 of file translator_it.h.
    {
      return "Questo grafo mostra quali altri file includono direttamente o indirettamente questo file:";
    }
trInclDepGraph() [1/2]
QCString TranslatorItalian::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 840 of file translator_it.h.
    {
      return "Grafo delle dipendenze di inclusione per "+fName+":";
    }
trInclDepGraph() [2/2]
QCString TranslatorItalian::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 840 of file translator_it.h.
    {
      return "Grafo delle dipendenze di inclusione per "+fName+":";
    }
trIncludesFileIn() [1/2]
virtual QCString TranslatorItalian::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1767 of file translator_it.h.
    {
      return "Include il file in "+name;
    }
References setup::name.
trIncludesFileIn() [2/2]
virtual QCString TranslatorItalian::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1767 of file translator_it.h.
    {
      return "Include il file in "+name;
    }
References setup::name.
trIncludingInheritedMembers() [1/2]
QCString TranslatorItalian::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 180 of file translator_it.h.
    { return ", inclusi tutti i membri ereditati."; }
trIncludingInheritedMembers() [2/2]
QCString TranslatorItalian::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 180 of file translator_it.h.
    { return ", inclusi tutti i membri ereditati."; }
trInheritedByList() [1/2]
QCString TranslatorItalian::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 700 of file translator_it.h.
    {
      return "Base per "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedByList() [2/2]
QCString TranslatorItalian::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 700 of file translator_it.h.
    {
      return "Base per "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom() [1/2]
virtual QCString TranslatorItalian::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1866 of file translator_it.h.
    { return QCString(members)+" ereditati da "+what; }
trInheritedFrom() [2/2]
virtual QCString TranslatorItalian::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1866 of file translator_it.h.
    { return QCString(members)+" ereditati da "+what; }
trInheritsList() [1/2]
QCString TranslatorItalian::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 692 of file translator_it.h.
    {
      return "Eredita da "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [2/2]
QCString TranslatorItalian::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 692 of file translator_it.h.
    {
      return "Eredita da "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue() [1/2]
QCString TranslatorItalian::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 875 of file translator_it.h.
    {
      return "Valore iniziale:";
    }
trInitialValue() [2/2]
QCString TranslatorItalian::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 875 of file translator_it.h.
    {
      return "Valore iniziale:";
    }
trInstanceMethods() [1/2]
virtual QCString TranslatorItalian::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1918 of file translator_it.h.
    {
      return "Metodi di instanza";
    }
trInstanceMethods() [2/2]
virtual QCString TranslatorItalian::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1918 of file translator_it.h.
    {
      return "Metodi di instanza";
    }
trInterfaces() [1/2]
virtual QCString TranslatorItalian::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1935 of file translator_it.h.
    { return "Interfacce esportate"; }
trInterfaces() [2/2]
virtual QCString TranslatorItalian::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1935 of file translator_it.h.
    { return "Interfacce esportate"; }
trInvariant() [1/2]
QCString TranslatorItalian::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 870 of file translator_it.h.
    {
      return "Invariante";
    }
trInvariant() [2/2]
QCString TranslatorItalian::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 870 of file translator_it.h.
    {
      return "Invariante";
    }
trISOLang() [1/2]
virtual QCString TranslatorItalian::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 115 of file translator_it.h.
    {
      return "it";
    }
trISOLang() [2/2]
virtual QCString TranslatorItalian::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 115 of file translator_it.h.
    {
      return "it";
    }
trLegend() [1/2]
virtual QCString TranslatorItalian::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1062 of file translator_it.h.
    {
      return "legenda";
    }
trLegend() [2/2]
virtual QCString TranslatorItalian::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1062 of file translator_it.h.
    {
      return "legenda";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorItalian::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 1004 of file translator_it.h.
    {
      return
        "Questa pagina spiega come interpretare i grafi generati da doxygen.<p>\n"
        "Si consideri l'esempio seguente:\n"
        "\\code\n"
        "/*! Classe invisibile per troncamento */\n"
        "class Invisible { };\n\n"
        "/*! Classe tronca, la relazione di ereditariet nascosta */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Classe non documentata con i commenti speciali di doxygen*/\n"
        "class Undocumented { };\n\n"
        "/*! Classe estesa mediante ereditariet pubblica */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! Classe templatizzata */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Classe estesa mediante ereditariet protetta*/\n"
        "class ProtectedBase { };\n\n"
        "/*! Classe estesa mediante ereditariet privata*/\n"
        "class PrivateBase { };\n\n"
        "/*! Classe utilizzata dalla classe Inherited */\n"
        "class Used { };\n\n"
        "/*! Classe che eredita da varie classi*/\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Verr prodotto il grafo seguente:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        "I riquadri nel grafo qui sopra hanno il seguente significato:\n"
        "</p>\n"
        "<ul>\n"
        "<li>Il riquadro grigio pieno rappresenta la struct o la classe per la quale il grafo stato generato.</li>\n"
        "<li>Un riquadro con un bordo nero denota una struct o una classe documentata.</li>\n"
        "<li>Un riquadro con un bordo grigio indica una struct o una classe non documentata.</li>\n"
        "<li>Un riquadro con un bordo rosso indica una struct o una classe per la quale non sono mostrate tutte le relazioni di ereditariet/contenimento (un grafo viene troncato se non rientra nei limiti prestabiliti).</li>\n"
        "</ul>\n"
        "<p>\n"
        "Le frecce hanno il seguente significato:\n"
        "</p>\n"
        "<ul>\n"
        "<li>Una freccia blu scuro indica una relazione di ereditariet pubblica tra due classi.</li>\n"
        "<li>Una freccia verde indica un'ereditariet protetta.</li>\n"
        "<li>Una freccia rossa indica un'ereditariet privata.</li>\n"
        "<li>Una freccia viola tratteggiata indica che una classe contenuta o usata da un'altra classe."
        " La freccia viene etichettata con la o le variabili attraverso cui la struct o la classe puntata dalla freccia accessibile.</li>\n"
        "<li>Una freccia gialla tratteggiata indica la relazione tra una istanza di un template e la classe templatizzata da cui stata istanziata."
        " La freccia viene etichettata con i parametri di template dell'istanza.</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorItalian::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 1004 of file translator_it.h.
    {
      return
        "Questa pagina spiega come interpretare i grafi generati da doxygen.<p>\n"
        "Si consideri l'esempio seguente:\n"
        "\\code\n"
        "/*! Classe invisibile per troncamento */\n"
        "class Invisible { };\n\n"
        "/*! Classe tronca, la relazione di ereditariet nascosta */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Classe non documentata con i commenti speciali di doxygen*/\n"
        "class Undocumented { };\n\n"
        "/*! Classe estesa mediante ereditariet pubblica */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! Classe templatizzata */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Classe estesa mediante ereditariet protetta*/\n"
        "class ProtectedBase { };\n\n"
        "/*! Classe estesa mediante ereditariet privata*/\n"
        "class PrivateBase { };\n\n"
        "/*! Classe utilizzata dalla classe Inherited */\n"
        "class Used { };\n\n"
        "/*! Classe che eredita da varie classi*/\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Verr prodotto il grafo seguente:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        "I riquadri nel grafo qui sopra hanno il seguente significato:\n"
        "</p>\n"
        "<ul>\n"
        "<li>Il riquadro grigio pieno rappresenta la struct o la classe per la quale il grafo stato generato.</li>\n"
        "<li>Un riquadro con un bordo nero denota una struct o una classe documentata.</li>\n"
        "<li>Un riquadro con un bordo grigio indica una struct o una classe non documentata.</li>\n"
        "<li>Un riquadro con un bordo rosso indica una struct o una classe per la quale non sono mostrate tutte le relazioni di ereditariet/contenimento (un grafo viene troncato se non rientra nei limiti prestabiliti).</li>\n"
        "</ul>\n"
        "<p>\n"
        "Le frecce hanno il seguente significato:\n"
        "</p>\n"
        "<ul>\n"
        "<li>Una freccia blu scuro indica una relazione di ereditariet pubblica tra due classi.</li>\n"
        "<li>Una freccia verde indica un'ereditariet protetta.</li>\n"
        "<li>Una freccia rossa indica un'ereditariet privata.</li>\n"
        "<li>Una freccia viola tratteggiata indica che una classe contenuta o usata da un'altra classe."
        " La freccia viene etichettata con la o le variabili attraverso cui la struct o la classe puntata dalla freccia accessibile.</li>\n"
        "<li>Una freccia gialla tratteggiata indica la relazione tra una istanza di un template e la classe templatizzata da cui stata istanziata."
        " La freccia viene etichettata con i parametri di template dell'istanza.</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorItalian::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 999 of file translator_it.h.
    {
      return "Legenda del grafo";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorItalian::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 999 of file translator_it.h.
    {
      return "Legenda del grafo";
    }
trListOfAllMembers() [1/2]
QCString TranslatorItalian::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 168 of file translator_it.h.
    { return "Elenco di tutti i membri"; }
trListOfAllMembers() [2/2]
QCString TranslatorItalian::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 168 of file translator_it.h.
    { return "Elenco di tutti i membri"; }
trLoading() [1/2]
virtual QCString TranslatorItalian::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1727 of file translator_it.h.
    {
      return "Caricamento in corso...";
    }
trLoading() [2/2]
virtual QCString TranslatorItalian::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1727 of file translator_it.h.
    {
      return "Caricamento in corso...";
    }
trMainPage() [1/2]
QCString TranslatorItalian::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 799 of file translator_it.h.
    { return "Pagina Principale"; }
trMainPage() [2/2]
QCString TranslatorItalian::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 799 of file translator_it.h.
    { return "Pagina Principale"; }
trMember() [1/2]
virtual QCString TranslatorItalian::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1228 of file translator_it.h.
    {
      QCString result((first_capital ? "Membr" : "membr"));
      result+=(singular ? "o" : "i");
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorItalian::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1228 of file translator_it.h.
    {
      QCString result((first_capital ? "Membr" : "membr"));
      result+=(singular ? "o" : "i");
      return result;
    }
trMemberDataDocumentation() [1/2]
QCString TranslatorItalian::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 151 of file translator_it.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentazione dei campi";
      }
      else
      {
        return "Documentazione dei membri dato";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
QCString TranslatorItalian::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 151 of file translator_it.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentazione dei campi";
      }
      else
      {
        return "Documentazione dei membri dato";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
QCString TranslatorItalian::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 143 of file translator_it.h.
    { return "Documentazione dei tipi enumerati (enum)"; }
trMemberEnumerationDocumentation() [2/2]
QCString TranslatorItalian::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 143 of file translator_it.h.
    { return "Documentazione dei tipi enumerati (enum)"; }
trMemberFunctionDocumentation() [1/2]
QCString TranslatorItalian::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 147 of file translator_it.h.
    { return "Documentazione delle funzioni membro"; }
trMemberFunctionDocumentation() [2/2]
QCString TranslatorItalian::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 147 of file translator_it.h.
    { return "Documentazione delle funzioni membro"; }
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorItalian::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1518 of file translator_it.h.
    { return "Documentazione delle funzioni membro/subroutine"; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorItalian::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1518 of file translator_it.h.
    { return "Documentazione delle funzioni membro/subroutine"; }
trMemberList() [1/2]
QCString TranslatorItalian::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 172 of file translator_it.h.
    { return "Elenco dei membri"; }
trMemberList() [2/2]
QCString TranslatorItalian::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 172 of file translator_it.h.
    { return "Elenco dei membri"; }
trMemberTypedefDocumentation() [1/2]
QCString TranslatorItalian::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 139 of file translator_it.h.
    { return "Documentazione delle ridefinizioni dei tipi (typedef)"; }
trMemberTypedefDocumentation() [2/2]
QCString TranslatorItalian::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 139 of file translator_it.h.
    { return "Documentazione delle ridefinizioni dei tipi (typedef)"; }
trMethodDocumentation() [1/2]
virtual QCString TranslatorItalian::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1925 of file translator_it.h.
    {
      return "Documentazione dei metodi";
    }
trMethodDocumentation() [2/2]
virtual QCString TranslatorItalian::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1925 of file translator_it.h.
    {
      return "Documentazione dei metodi";
    }
trModule() [1/2]
virtual QCString TranslatorItalian::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1657 of file translator_it.h.
    {
      QCString result((first_capital ? "Modul" : "modul"));
      if (singular) result+="o";
      else result+="i";
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorItalian::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1657 of file translator_it.h.
    {
      QCString result((first_capital ? "Modul" : "modul"));
      if (singular) result+="o";
      else result+="i";
      return result;
    }
trModuleDocumentation() [1/2]
QCString TranslatorItalian::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 410 of file translator_it.h.
    { return "Documentazione dei moduli"; }
trModuleDocumentation() [2/2]
QCString TranslatorItalian::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 410 of file translator_it.h.
    { return "Documentazione dei moduli"; }
trModuleIndex() [1/2]
QCString TranslatorItalian::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 377 of file translator_it.h.
    { return "Indice dei moduli"; }
trModuleIndex() [2/2]
QCString TranslatorItalian::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 377 of file translator_it.h.
    { return "Indice dei moduli"; }
trModuleReference() [1/2]
virtual QCString TranslatorItalian::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1619 of file translator_it.h.
    {
      QCString result="Riferimenti per il modulo ";
      result+=namespaceName;
      return result;
    }
trModuleReference() [2/2]
virtual QCString TranslatorItalian::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1619 of file translator_it.h.
    {
      QCString result="Riferimenti per il modulo ";
      result+=namespaceName;
      return result;
    }
trModules() [1/2]
QCString TranslatorItalian::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 211 of file translator_it.h.
    { return "Moduli"; }
trModules() [2/2]
QCString TranslatorItalian::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 211 of file translator_it.h.
    { return "Moduli"; }
trModulesDescription() [1/2]
QCString TranslatorItalian::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 365 of file translator_it.h.
    { return "Questo l'elenco di tutti i moduli:"; }
trModulesDescription() [2/2]
QCString TranslatorItalian::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 365 of file translator_it.h.
    { return "Questo l'elenco di tutti i moduli:"; }
trModulesIndex() [1/2]
virtual QCString TranslatorItalian::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1650 of file translator_it.h.
    { return "Indice dei moduli"; }
trModulesIndex() [2/2]
virtual QCString TranslatorItalian::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1650 of file translator_it.h.
    { return "Indice dei moduli"; }
trModulesList() [1/2]
virtual QCString TranslatorItalian::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1584 of file translator_it.h.
    { return "Elenco dei moduli"; }
trModulesList() [2/2]
virtual QCString TranslatorItalian::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1584 of file translator_it.h.
    { return "Elenco dei moduli"; }
trModulesListDescription() [1/2]
virtual QCString TranslatorItalian::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1588 of file translator_it.h.
    {
      QCString result="Questa una lista di tutti i moduli ";
      if (!extractAll) result+="documentati ";
      result+="con una loro breve descrizione:";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorItalian::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1588 of file translator_it.h.
    {
      QCString result="Questa una lista di tutti i moduli ";
      if (!extractAll) result+="documentati ";
      result+="con una loro breve descrizione:";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorItalian::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1631 of file translator_it.h.
    {
      QCString result="Questo un elenco di tutti i membri dei moduli ";
      if (!extractAll) result+="documentati ";
      result+="con collegamenti ";
      if (extractAll)
      {
        result+="alla documentazione del modulo per ciascun membro:";
      }
      else
      {
        result+="al modulo a cui appartengono:";
      }
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorItalian::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1631 of file translator_it.h.
    {
      QCString result="Questo un elenco di tutti i membri dei moduli ";
      if (!extractAll) result+="documentati ";
      result+="con collegamenti ";
      if (extractAll)
      {
        result+="alla documentazione del modulo per ciascun membro:";
      }
      else
      {
        result+="al modulo a cui appartengono:";
      }
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorItalian::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1627 of file translator_it.h.
    { return "Membri del modulo"; }
trModulesMembers() [2/2]
virtual QCString TranslatorItalian::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1627 of file translator_it.h.
    { return "Membri del modulo"; }
trMonth() [1/2]
virtual QCString TranslatorItalian::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1806 of file translator_it.h.
    {
      static const char *months_short[] = { "gen", "feb", "mar", "apr", "mag", "giu", "lug", "ago", "set", "ott", "nov", "dic" };
      static const char *months_full[] = { "gennaio", "febbraio", "marzo", "aprile", "maggio", "giugno", "luglio", "agosto", "settembre", "ottobre", "novembre", "dicembre" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMonth() [2/2]
virtual QCString TranslatorItalian::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1806 of file translator_it.h.
    {
      static const char *months_short[] = { "gen", "feb", "mar", "apr", "mag", "giu", "lug", "ago", "set", "ott", "nov", "dic" };
      static const char *months_full[] = { "gennaio", "febbraio", "marzo", "aprile", "maggio", "giugno", "luglio", "agosto", "settembre", "ottobre", "novembre", "dicembre" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore() [1/2]
QCString TranslatorItalian::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 164 of file translator_it.h.
    { return "Continua..."; }
trMore() [2/2]
QCString TranslatorItalian::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 164 of file translator_it.h.
    { return "Continua..."; }
trNamespace() [1/2]
virtual QCString TranslatorItalian::trNamespace (bool first_capital, bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1196 of file translator_it.h.
    {
      QCString result((first_capital ? "Namespace" : "namespace"));
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorItalian::trNamespace (bool first_capital, bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1196 of file translator_it.h.
    {
      QCString result((first_capital ? "Namespace" : "namespace"));
      return result;
    }
trNamespaceDocumentation() [1/2]
QCString TranslatorItalian::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 747 of file translator_it.h.
    { return "Documentazione dei namespace"; }
trNamespaceDocumentation() [2/2]
QCString TranslatorItalian::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 747 of file translator_it.h.
    { return "Documentazione dei namespace"; }
trNamespaceIndex() [1/2]
QCString TranslatorItalian::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 741 of file translator_it.h.
    { return "Indice dei namespace"; }
trNamespaceIndex() [2/2]
QCString TranslatorItalian::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 741 of file translator_it.h.
    { return "Indice dei namespace"; }
trNamespaceList() [1/2]
QCString TranslatorItalian::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 570 of file translator_it.h.
    { return "Lista dei namespace"; }
trNamespaceList() [2/2]
QCString TranslatorItalian::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 570 of file translator_it.h.
    { return "Lista dei namespace"; }
trNamespaceListDescription() [1/2]
QCString TranslatorItalian::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 574 of file translator_it.h.
    {
      QCString result="Questa l'elenco ";
      if (!extractAll) result+="dei namespace documentati, ";
      else result+="di tutti i namespace ";
      result+="con una loro breve descrizione:";
      return result;
    }
trNamespaceListDescription() [2/2]
QCString TranslatorItalian::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 574 of file translator_it.h.
    {
      QCString result="Questa l'elenco ";
      if (!extractAll) result+="dei namespace documentati, ";
      else result+="di tutti i namespace ";
      result+="con una loro breve descrizione:";
      return result;
    }
trNamespaceMemberDescription() [1/2]
QCString TranslatorItalian::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 726 of file translator_it.h.
    {
      QCString result="Questa la lista ";
      if (!extractAll) result+="dei membri documentati del namespace, ";
       else result+="di tutti i membri del namespace ";
      result+="con collegamenti ";
      if (extractAll)
        result+="alla documentazione del namespace per ciascun membro:";
      else
        result+="ai namespace a cui appartengono:";
      return result;
    }
trNamespaceMemberDescription() [2/2]
QCString TranslatorItalian::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 726 of file translator_it.h.
    {
      QCString result="Questa la lista ";
      if (!extractAll) result+="dei membri documentati del namespace, ";
       else result+="di tutti i membri del namespace ";
      result+="con collegamenti ";
      if (extractAll)
        result+="alla documentazione del namespace per ciascun membro:";
      else
        result+="ai namespace a cui appartengono:";
      return result;
    }
trNamespaceMembers() [1/2]
QCString TranslatorItalian::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 722 of file translator_it.h.
    { return "Membri dei namespace"; }
trNamespaceMembers() [2/2]
QCString TranslatorItalian::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 722 of file translator_it.h.
    { return "Membri dei namespace"; }
trNamespaceReference() [1/2]
QCString TranslatorItalian::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 635 of file translator_it.h.
    {
      QCString result="Riferimenti per il namespace ";
      result+=namespaceName;
      return result;
    }
trNamespaceReference() [2/2]
QCString TranslatorItalian::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 635 of file translator_it.h.
    {
      QCString result="Riferimenti per il namespace ";
      result+=namespaceName;
      return result;
    }
trNamespaces() [1/2]
QCString TranslatorItalian::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 757 of file translator_it.h.
    { return "Namespace"; }
trNamespaces() [2/2]
QCString TranslatorItalian::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 757 of file translator_it.h.
    { return "Namespace"; }
trNoMatches() [1/2]
virtual QCString TranslatorItalian::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1745 of file translator_it.h.
    {
      return "Nessun risultato";
    }
trNoMatches() [2/2]
virtual QCString TranslatorItalian::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1745 of file translator_it.h.
    {
      return "Nessun risultato";
    }
trNote() [1/2]
QCString TranslatorItalian::trNote () [inline], [virtual]
Implements Translator.
Definition at line 905 of file translator_it.h.
    {
      return "Nota";
    }
trNote() [2/2]
QCString TranslatorItalian::trNote () [inline], [virtual]
Implements Translator.
Definition at line 905 of file translator_it.h.
    {
      return "Nota";
    }
trOverloadText() [1/2]
virtual QCString TranslatorItalian::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1490 of file translator_it.h.
    {
       return "Questa una funzione membro sovraccaricata (overloaded), "
              "fornita per comodit. Differisce dalla funzione di cui sopra "
              "unicamente per gli argomenti passati.";
    }
trOverloadText() [2/2]
virtual QCString TranslatorItalian::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1490 of file translator_it.h.
    {
       return "Questa una funzione membro sovraccaricata (overloaded), "
              "fornita per comodit. Differisce dalla funzione di cui sopra "
              "unicamente per gli argomenti passati.";
    }
trPackage() [1/2]
virtual QCString TranslatorItalian::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1114 of file translator_it.h.
    {
      return "Package "+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorItalian::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1114 of file translator_it.h.
    {
      return "Package "+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorItalian::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1363 of file translator_it.h.
    {
      return "Attributi con visibilit di package";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorItalian::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1363 of file translator_it.h.
    {
      return "Attributi con visibilit di package";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorItalian::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1345 of file translator_it.h.
    {
      return "Funzioni con visibilit di package";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorItalian::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1345 of file translator_it.h.
    {
      return "Funzioni con visibilit di package";
    }
trPackageListDescription() [1/2]
virtual QCString TranslatorItalian::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1119 of file translator_it.h.
    {
      return "Questi sono i package e una loro breve descrizione (se disponibile):";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorItalian::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1119 of file translator_it.h.
    {
      return "Questi sono i package e una loro breve descrizione (se disponibile):";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorItalian::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1349 of file translator_it.h.
    {
      return "Membri con visibilit di package";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorItalian::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1349 of file translator_it.h.
    {
      return "Membri con visibilit di package";
    }
trPackages() [1/2]
virtual QCString TranslatorItalian::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1124 of file translator_it.h.
    {
      return "Package";
    }
trPackages() [2/2]
virtual QCString TranslatorItalian::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1124 of file translator_it.h.
    {
      return "Package";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorItalian::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1338 of file translator_it.h.
    {
      return "Tipi con visibilit di package";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorItalian::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1338 of file translator_it.h.
    {
      return "Tipi con visibilit di package";
    }
trPage() [1/2]
virtual QCString TranslatorItalian::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1217 of file translator_it.h.
    {
      QCString result((first_capital ? "Pagin" : "pagin"));
      result+=(singular ? "a" : "e");
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorItalian::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1217 of file translator_it.h.
    {
      QCString result((first_capital ? "Pagin" : "pagin"));
      result+=(singular ? "a" : "e");
      return result;
    }
trPageAbbreviation() [1/2]
QCString TranslatorItalian::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 805 of file translator_it.h.
    { return "pag."; }
trPageAbbreviation() [2/2]
QCString TranslatorItalian::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 805 of file translator_it.h.
    { return "pag."; }
trPageIndex() [1/2]
QCString TranslatorItalian::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 896 of file translator_it.h.
    {
      return "Indice delle pagine";
    }
trPageIndex() [2/2]
QCString TranslatorItalian::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 896 of file translator_it.h.
    {
      return "Indice delle pagine";
    }
trPanelSynchronisationTooltip() [1/2]
virtual QCString TranslatorItalian::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1883 of file translator_it.h.
    {
      QCString opt = enable ? "abilitare" : "disabilitare";
      return "cliccare per "+opt+" la sincronizzazione del pannello";
    }
trPanelSynchronisationTooltip() [2/2]
virtual QCString TranslatorItalian::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1883 of file translator_it.h.
    {
      QCString opt = enable ? "abilitare" : "disabilitare";
      return "cliccare per "+opt+" la sincronizzazione del pannello";
    }
trParameters() [1/2]
QCString TranslatorItalian::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 554 of file translator_it.h.
    { return "Parametri"; }
trParameters() [2/2]
QCString TranslatorItalian::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 554 of file translator_it.h.
    { return "Parametri"; }
trPostcondition() [1/2]
QCString TranslatorItalian::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 865 of file translator_it.h.
    {
      return "Postcondizione";
    }
trPostcondition() [2/2]
QCString TranslatorItalian::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 865 of file translator_it.h.
    {
      return "Postcondizione";
    }
trPrecondition() [1/2]
QCString TranslatorItalian::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 860 of file translator_it.h.
    {
      return "Precondizione";
    }
trPrecondition() [2/2]
QCString TranslatorItalian::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 860 of file translator_it.h.
    {
      return "Precondizione";
    }
trPrivateAttribs() [1/2]
QCString TranslatorItalian::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 945 of file translator_it.h.
    {
      return "Attributi privati";
    }
trPrivateAttribs() [2/2]
QCString TranslatorItalian::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 945 of file translator_it.h.
    {
      return "Attributi privati";
    }
trPrivateMembers() [1/2]
QCString TranslatorItalian::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 657 of file translator_it.h.
    { return "Membri privati"; }
trPrivateMembers() [2/2]
QCString TranslatorItalian::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 657 of file translator_it.h.
    { return "Membri privati"; }
trPrivateSlots() [1/2]
QCString TranslatorItalian::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 659 of file translator_it.h.
    { return "Slot privati"; }
trPrivateSlots() [2/2]
QCString TranslatorItalian::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 659 of file translator_it.h.
    { return "Slot privati"; }
trPrivateTypes() [1/2]
QCString TranslatorItalian::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 941 of file translator_it.h.
    {
      return "Tipi privati";
    }
trPrivateTypes() [2/2]
QCString TranslatorItalian::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 941 of file translator_it.h.
    {
      return "Tipi privati";
    }
trProperties() [1/2]
virtual QCString TranslatorItalian::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1087 of file translator_it.h.
    {
      return "Propriet";
    }
trProperties() [2/2]
virtual QCString TranslatorItalian::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1087 of file translator_it.h.
    {
      return "Propriet";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorItalian::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1092 of file translator_it.h.
    {
      return "Documentazione delle propriet";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorItalian::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1092 of file translator_it.h.
    {
      return "Documentazione delle propriet";
    }
trProtectedAttribs() [1/2]
QCString TranslatorItalian::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 933 of file translator_it.h.
    {
      return "Attributi protetti";
    }
trProtectedAttribs() [2/2]
QCString TranslatorItalian::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 933 of file translator_it.h.
    {
      return "Attributi protetti";
    }
trProtectedMembers() [1/2]
QCString TranslatorItalian::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 651 of file translator_it.h.
    { return "Membri protetti"; }
trProtectedMembers() [2/2]
QCString TranslatorItalian::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 651 of file translator_it.h.
    { return "Membri protetti"; }
trProtectedSlots() [1/2]
QCString TranslatorItalian::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 653 of file translator_it.h.
    { return "Slot protetti"; }
trProtectedSlots() [2/2]
QCString TranslatorItalian::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 653 of file translator_it.h.
    { return "Slot protetti"; }
trProtectedTypes() [1/2]
QCString TranslatorItalian::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 929 of file translator_it.h.
    {
      return "Tipi protetti";
    }
trProtectedTypes() [2/2]
QCString TranslatorItalian::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 929 of file translator_it.h.
    {
      return "Tipi protetti";
    }
trProvidedByCategory() [1/2]
virtual QCString TranslatorItalian::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1893 of file translator_it.h.
    {
      return "Fornito dalla categoria @0.";
    }
trProvidedByCategory() [2/2]
virtual QCString TranslatorItalian::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1893 of file translator_it.h.
    {
      return "Fornito dalla categoria @0.";
    }
trPublicAttribs() [1/2]
QCString TranslatorItalian::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 913 of file translator_it.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Campi";
      }
      else
      {
      return "Attributi pubblici";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
QCString TranslatorItalian::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 913 of file translator_it.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Campi";
      }
      else
      {
      return "Attributi pubblici";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
QCString TranslatorItalian::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 643 of file translator_it.h.
    { return "Membri pubblici"; }
trPublicMembers() [2/2]
QCString TranslatorItalian::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 643 of file translator_it.h.
    { return "Membri pubblici"; }
trPublicSlots() [1/2]
QCString TranslatorItalian::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 645 of file translator_it.h.
    { return "Slot pubblici"; }
trPublicSlots() [2/2]
QCString TranslatorItalian::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 645 of file translator_it.h.
    { return "Slot pubblici"; }
trPublicTypes() [1/2]
QCString TranslatorItalian::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 909 of file translator_it.h.
    {
      return "Tipi pubblici";
    }
trPublicTypes() [2/2]
QCString TranslatorItalian::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 909 of file translator_it.h.
    {
      return "Tipi pubblici";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorItalian::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 973 of file translator_it.h.
    {
      return "Referenziato da";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorItalian::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 973 of file translator_it.h.
    {
      return "Referenziato da";
    }
trReferenceManual() [1/2]
QCString TranslatorItalian::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 432 of file translator_it.h.
    { return "Manuale di riferimento"; }
trReferenceManual() [2/2]
QCString TranslatorItalian::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 432 of file translator_it.h.
    { return "Manuale di riferimento"; }
trReferences() [1/2]
virtual QCString TranslatorItalian::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1265 of file translator_it.h.
    {
      return "Referenzia";
    }
trReferences() [2/2]
virtual QCString TranslatorItalian::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1265 of file translator_it.h.
    {
      return "Referenzia";
    }
trReimplementedFromList() [1/2]
QCString TranslatorItalian::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 708 of file translator_it.h.
    {
      return "Reimplementa "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedFromList() [2/2]
QCString TranslatorItalian::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 708 of file translator_it.h.
    {
      return "Reimplementa "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [1/2]
QCString TranslatorItalian::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 716 of file translator_it.h.
    {
      return "Reimplementata in "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [2/2]
QCString TranslatorItalian::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 716 of file translator_it.h.
    {
      return "Reimplementata in "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
QCString TranslatorItalian::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 596 of file translator_it.h.
    { return "Documentazione dei friend e delle funzioni collegate"; }
trRelatedFunctionDocumentation() [2/2]
QCString TranslatorItalian::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 596 of file translator_it.h.
    { return "Documentazione dei friend e delle funzioni collegate"; }
trRelatedFunctions() [1/2]
QCString TranslatorItalian::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 127 of file translator_it.h.
    { return "Funzioni collegate"; }
trRelatedFunctions() [2/2]
QCString TranslatorItalian::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 127 of file translator_it.h.
    { return "Funzioni collegate"; }
trRelatedPages() [1/2]
QCString TranslatorItalian::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 262 of file translator_it.h.
    { return "Pagine collegate"; }
trRelatedPages() [2/2]
QCString TranslatorItalian::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 262 of file translator_it.h.
    { return "Pagine collegate"; }
trRelatedPagesDescription() [1/2]
QCString TranslatorItalian::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 361 of file translator_it.h.
    { return "Questo l'elenco di tutte le pagine di documentazione collegate:"; }
trRelatedPagesDescription() [2/2]
QCString TranslatorItalian::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 361 of file translator_it.h.
    { return "Questo l'elenco di tutte le pagine di documentazione collegate:"; }
trRelatedSubscript() [1/2]
QCString TranslatorItalian::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 131 of file translator_it.h.
    { return "(Si noti che queste non sono funzioni membro.)"; }
trRelatedSubscript() [2/2]
QCString TranslatorItalian::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 131 of file translator_it.h.
    { return "(Si noti che queste non sono funzioni membro.)"; }
trRemarks() [1/2]
virtual QCString TranslatorItalian::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 977 of file translator_it.h.
    {
      return "Osservazioni";
    }
trRemarks() [2/2]
virtual QCString TranslatorItalian::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 977 of file translator_it.h.
    {
      return "Osservazioni";
    }
trReturns() [1/2]
QCString TranslatorItalian::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 546 of file translator_it.h.
    { return "Restituisce"; }
trReturns() [2/2]
QCString TranslatorItalian::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 546 of file translator_it.h.
    { return "Restituisce"; }
trReturnValues() [1/2]
QCString TranslatorItalian::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 794 of file translator_it.h.
    { return "Valori di ritorno"; }
trReturnValues() [2/2]
QCString TranslatorItalian::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 794 of file translator_it.h.
    { return "Valori di ritorno"; }
trRTFansicp() [1/2]
virtual QCString TranslatorItalian::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
Implements Translator.
Definition at line 1154 of file translator_it.h.
    {
      return "1252";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorItalian::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
Implements Translator.
Definition at line 1154 of file translator_it.h.
    {
      return "1252";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorItalian::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
Implements Translator.
Definition at line 1160 of file translator_it.h.
    {
      return "0";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorItalian::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
Implements Translator.
Definition at line 1160 of file translator_it.h.
    {
      return "0";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorItalian::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1166 of file translator_it.h.
    {
      return "Indice";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorItalian::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1166 of file translator_it.h.
    {
      return "Indice";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorItalian::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1297 of file translator_it.h.
    {
      return "Sommario";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorItalian::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1297 of file translator_it.h.
    {
      return "Sommario";
    }
trSearch() [1/2]
QCString TranslatorItalian::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 270 of file translator_it.h.
    { return "Cerca"; }
trSearch() [2/2]
QCString TranslatorItalian::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 270 of file translator_it.h.
    { return "Cerca"; }
trSearching() [1/2]
virtual QCString TranslatorItalian::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1739 of file translator_it.h.
    {
      return "Ricerca in corso...";
    }
trSearching() [2/2]
virtual QCString TranslatorItalian::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1739 of file translator_it.h.
    {
      return "Ricerca in corso...";
    }
trSearchMatches() [1/2]
virtual QCString TranslatorItalian::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1430 of file translator_it.h.
    {
      return "Corrispondenze:";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorItalian::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1430 of file translator_it.h.
    {
      return "Corrispondenze:";
    }
trSearchResults() [1/2]
virtual QCString TranslatorItalian::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1411 of file translator_it.h.
    {
      if (numDocuments==0)
      {
        return "Nessun documento soddisfa la tua richiesta.";
      }
      else if (numDocuments==1)
      {
        return "Trovato <b>1</b> documento che soddisfa la tua richiesta.";
      }
      else
      {
        return "Trovati <b>$num</b> documenti che soddisfano la tua richiesta. "
               "Le corrispondenze migliori sono in testa.";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorItalian::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1411 of file translator_it.h.
    {
      if (numDocuments==0)
      {
        return "Nessun documento soddisfa la tua richiesta.";
      }
      else if (numDocuments==1)
      {
        return "Trovato <b>1</b> documento che soddisfa la tua richiesta.";
      }
      else
      {
        return "Trovati <b>$num</b> documenti che soddisfano la tua richiesta. "
               "Le corrispondenze migliori sono in testa.";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorItalian::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1399 of file translator_it.h.
    {
      return "Risultati della ricerca";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorItalian::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1399 of file translator_it.h.
    {
      return "Risultati della ricerca";
    }
trSeeAlso() [1/2]
QCString TranslatorItalian::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 550 of file translator_it.h.
    { return "Si veda anche"; }
trSeeAlso() [2/2]
QCString TranslatorItalian::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 550 of file translator_it.h.
    { return "Si veda anche"; }
trServiceGeneratedFromFiles() [1/2]
virtual QCString TranslatorItalian::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 1968 of file translator_it.h.
    {
      // single is true implies a single file
      QCString result="La documentazione per questo servizio "
                                " stata generata a partire ";
      if (single) result+="dal seguente file:"; else result+="dai seguenti file:";
      return result;
    }
trServiceGeneratedFromFiles() [2/2]
virtual QCString TranslatorItalian::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 1968 of file translator_it.h.
    {
      // single is true implies a single file
      QCString result="La documentazione per questo servizio "
                                " stata generata a partire ";
      if (single) result+="dal seguente file:"; else result+="dai seguenti file:";
      return result;
    }
trServiceReference() [1/2]
virtual QCString TranslatorItalian::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 1954 of file translator_it.h.
    {
      QCString result="Riferimenti per il servizio ";
      result+=sName;
      return result;
    }
trServiceReference() [2/2]
virtual QCString TranslatorItalian::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 1954 of file translator_it.h.
    {
      QCString result="Riferimenti per il servizio ";
      result+=sName;
      return result;
    }
trServices() [1/2]
virtual QCString TranslatorItalian::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1939 of file translator_it.h.
    { return "Servizi inclusi"; }
trServices() [2/2]
virtual QCString TranslatorItalian::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1939 of file translator_it.h.
    { return "Servizi inclusi"; }
trSignals() [1/2]
QCString TranslatorItalian::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 647 of file translator_it.h.
    { return "Signal"; }
trSignals() [2/2]
QCString TranslatorItalian::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 647 of file translator_it.h.
    { return "Signal"; }
trSince() [1/2]
virtual QCString TranslatorItalian::trSince () [inline], [virtual]
Implements Translator.
Definition at line 989 of file translator_it.h.
    {
      return "A partire da";
    }
trSince() [2/2]
virtual QCString TranslatorItalian::trSince () [inline], [virtual]
Implements Translator.
Definition at line 989 of file translator_it.h.
    {
      return "A partire da";
    }
trSingletonGeneratedFromFiles() [1/2]
virtual QCString TranslatorItalian::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 1977 of file translator_it.h.
    {
      // single is true implies a single file
      QCString result="La documentazione per questo singleton "
                                " stata generata a partire ";
      if (single) result+="dal seguente file:"; else result+="dai seguenti file:";
      return result;
    }
trSingletonGeneratedFromFiles() [2/2]
virtual QCString TranslatorItalian::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 1977 of file translator_it.h.
    {
      // single is true implies a single file
      QCString result="La documentazione per questo singleton "
                                " stata generata a partire ";
      if (single) result+="dal seguente file:"; else result+="dai seguenti file:";
      return result;
    }
trSingletonReference() [1/2]
virtual QCString TranslatorItalian::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 1961 of file translator_it.h.
    {
      QCString result="Riferimenti per il singleton ";
      result+=sName;
      return result;
    }
trSingletonReference() [2/2]
virtual QCString TranslatorItalian::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 1961 of file translator_it.h.
    {
      QCString result="Riferimenti per il singleton ";
      result+=sName;
      return result;
    }
trSourceFile() [1/2]
virtual QCString TranslatorItalian::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1441 of file translator_it.h.
    {
      return " File sorgente " + filename ;
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorItalian::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1441 of file translator_it.h.
    {
      return " File sorgente " + filename ;
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorItalian::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1370 of file translator_it.h.
    {
      return "Attributi statici con visibilit di package";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorItalian::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1370 of file translator_it.h.
    {
      return "Attributi statici con visibilit di package";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorItalian::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1356 of file translator_it.h.
    {
      return "Funzioni statiche con visibilit di package";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorItalian::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1356 of file translator_it.h.
    {
      return "Funzioni statiche con visibilit di package";
    }
trStaticPrivateAttribs() [1/2]
QCString TranslatorItalian::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 949 of file translator_it.h.
    {
      return "Attributi privati statici";
    }
trStaticPrivateAttribs() [2/2]
QCString TranslatorItalian::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 949 of file translator_it.h.
    {
      return "Attributi privati statici";
    }
trStaticPrivateMembers() [1/2]
QCString TranslatorItalian::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 661 of file translator_it.h.
    { return "Membri privati statici"; }
trStaticPrivateMembers() [2/2]
QCString TranslatorItalian::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 661 of file translator_it.h.
    { return "Membri privati statici"; }
trStaticProtectedAttribs() [1/2]
QCString TranslatorItalian::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 937 of file translator_it.h.
    {
      return "Attributi protetti statici";
    }
trStaticProtectedAttribs() [2/2]
QCString TranslatorItalian::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 937 of file translator_it.h.
    {
      return "Attributi protetti statici";
    }
trStaticProtectedMembers() [1/2]
QCString TranslatorItalian::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 655 of file translator_it.h.
    { return "Membri protetti statici"; }
trStaticProtectedMembers() [2/2]
QCString TranslatorItalian::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 655 of file translator_it.h.
    { return "Membri protetti statici"; }
trStaticPublicAttribs() [1/2]
QCString TranslatorItalian::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 925 of file translator_it.h.
    {
      return "Attributi pubblici statici";
    }
trStaticPublicAttribs() [2/2]
QCString TranslatorItalian::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 925 of file translator_it.h.
    {
      return "Attributi pubblici statici";
    }
trStaticPublicMembers() [1/2]
QCString TranslatorItalian::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 649 of file translator_it.h.
    { return "Membri pubblici statici"; }
trStaticPublicMembers() [2/2]
QCString TranslatorItalian::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 649 of file translator_it.h.
    { return "Membri pubblici statici"; }
trSubprogram() [1/2]
virtual QCString TranslatorItalian::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1702 of file translator_it.h.
    {
      QCString result((first_capital ? "Sottoprogramm" : "sottoprogramm"));
      if (singular) result+="a";
      else result+="i";
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorItalian::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1702 of file translator_it.h.
    {
      QCString result((first_capital ? "Sottoprogramm" : "sottoprogramm"));
      if (singular) result+="a";
      else result+="i";
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorItalian::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1574 of file translator_it.h.
    { return "Documentazione funzioni/subroutine"; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorItalian::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1574 of file translator_it.h.
    { return "Documentazione funzioni/subroutine"; }
trSubprograms() [1/2]
virtual QCString TranslatorItalian::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1568 of file translator_it.h.
    { return "Funzioni/Subroutine"; }
trSubprograms() [2/2]
virtual QCString TranslatorItalian::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1568 of file translator_it.h.
    { return "Funzioni/Subroutine"; }
trTemplateParameters() [1/2]
virtual QCString TranslatorItalian::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1845 of file translator_it.h.
    { return "Parametri dei template"; }
trTemplateParameters() [2/2]
virtual QCString TranslatorItalian::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1845 of file translator_it.h.
    { return "Parametri dei template"; }
trTest() [1/2]
virtual QCString TranslatorItalian::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1072 of file translator_it.h.
    {
      return "Test";
    }
trTest() [2/2]
virtual QCString TranslatorItalian::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1072 of file translator_it.h.
    {
      return "Test";
    }
trTestList() [1/2]
virtual QCString TranslatorItalian::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1077 of file translator_it.h.
    {
      return "Lista dei test";
    }
trTestList() [2/2]
virtual QCString TranslatorItalian::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1077 of file translator_it.h.
    {
      return "Lista dei test";
    }
trThisIsTheListOfAllMembers() [1/2]
QCString TranslatorItalian::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 176 of file translator_it.h.
    { return "Questo l'elenco completo di tutti i membri di "; }
trThisIsTheListOfAllMembers() [2/2]
QCString TranslatorItalian::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 176 of file translator_it.h.
    { return "Questo l'elenco completo di tutti i membri di "; }
trTodo() [1/2]
virtual QCString TranslatorItalian::trTodo () [inline], [virtual]
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 959 of file translator_it.h.
    {
      return "Da fare";
    }
trTodo() [2/2]
virtual QCString TranslatorItalian::trTodo () [inline], [virtual]
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 959 of file translator_it.h.
    {
      return "Da fare";
    }
trTodoList() [1/2]
virtual QCString TranslatorItalian::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 964 of file translator_it.h.
    {
      return "Elenco delle cose da fare";
    }
trTodoList() [2/2]
virtual QCString TranslatorItalian::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 964 of file translator_it.h.
    {
      return "Elenco delle cose da fare";
    }
trType() [1/2]
virtual QCString TranslatorItalian::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1691 of file translator_it.h.
    {
      QCString result((first_capital ? "Tip" : "tip"));
      if (singular) result+="o";
      else result+="i";
      return result;
    }
trType() [2/2]
virtual QCString TranslatorItalian::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1691 of file translator_it.h.
    {
      QCString result((first_capital ? "Tip" : "tip"));
      if (singular) result+="o";
      else result+="i";
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorItalian::trTypeConstraints () [inline], [virtual]
C# Type Contraint list
Implements Translator.
Definition at line 1711 of file translator_it.h.
    {
      return "Vincoli dei tipi";
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorItalian::trTypeConstraints () [inline], [virtual]
C# Type Contraint list
Implements Translator.
Definition at line 1711 of file translator_it.h.
    {
      return "Vincoli dei tipi";
    }
trTypedefDocumentation() [1/2]
QCString TranslatorItalian::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 480 of file translator_it.h.
    { return "Documentazione delle ridefinizioni di tipo (typedef)"; }
trTypedefDocumentation() [2/2]
QCString TranslatorItalian::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 480 of file translator_it.h.
    { return "Documentazione delle ridefinizioni di tipo (typedef)"; }
trTypedefs() [1/2]
QCString TranslatorItalian::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 444 of file translator_it.h.
    { return "Ridefinizioni di tipo (typedef)"; }
trTypedefs() [2/2]
QCString TranslatorItalian::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 444 of file translator_it.h.
    { return "Ridefinizioni di tipo (typedef)"; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorItalian::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1562 of file translator_it.h.
    { return "Documentazione dei tipi dato"; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorItalian::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1562 of file translator_it.h.
    { return "Documentazione dei tipi dato"; }
trVariableDocumentation() [1/2]
QCString TranslatorItalian::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 498 of file translator_it.h.
    { return "Documentazione delle variabili"; }
trVariableDocumentation() [2/2]
QCString TranslatorItalian::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 498 of file translator_it.h.
    { return "Documentazione delle variabili"; }
trVariables() [1/2]
QCString TranslatorItalian::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 462 of file translator_it.h.
    { return "Variabili"; }
trVariables() [2/2]
QCString TranslatorItalian::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 462 of file translator_it.h.
    { return "Variabili"; }
trVersion() [1/2]
QCString TranslatorItalian::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 538 of file translator_it.h.
    { return "Versione"; }
trVersion() [2/2]
QCString TranslatorItalian::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 538 of file translator_it.h.
    { return "Versione"; }
trWarning() [1/2]
QCString TranslatorItalian::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 534 of file translator_it.h.
    { return "Avvertimento"; }
trWarning() [2/2]
QCString TranslatorItalian::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 534 of file translator_it.h.
    { return "Avvertimento"; }
trWriteList() [1/2]
QCString TranslatorItalian::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 667 of file translator_it.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=", e ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
QCString TranslatorItalian::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 667 of file translator_it.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=", e ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_it.h
doxygen/src/translator_it.h