ArgumentListContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
ArgumentListContext ()
ArgumentListContext (const ArgumentList &al, const Definition *def, const QCString &relPath)
virtual ~ArgumentListContext ()
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
ArgumentListContext ()
ArgumentListContext (const ArgumentList &al, const Definition *def, const QCString &relPath)
virtual ~ArgumentListContext ()
Static Public Member Functions
static TemplateListIntfPtr alloc ()
static TemplateListIntfPtr alloc (const ArgumentList &al, const Definition *def, const QCString &relPath)
static TemplateListIntfPtr alloc ()
static TemplateListIntfPtr alloc (const ArgumentList &al, const Definition *def, const QCString &relPath)
Private Attributes
std::unique_ptr< Private > p
Additional Inherited Members
Detailed Description
Definition at line 1203 of file context.h.
Constructor & Destructor Documentation
ArgumentListContext() [1/4]
ArgumentListContext::ArgumentListContext ()
Definition at line 8305 of file context.cpp.
                                         : p(std::make_unique<Private>())
{
}
ArgumentListContext() [2/4]
ArgumentListContext::ArgumentListContext (const ArgumentList & al, const Definition * def, const QCString & relPath)
Definition at line 8309 of file context.cpp.
                                                                       : p(std::make_unique<Private>())
{
  for (const Argument &arg : list)
  {
    p->addArgument(arg,def,relPath);
  }
}
References p.
 ArgumentListContext() [1/2]
ArgumentListContext::~ArgumentListContext () [virtual]
Definition at line 8318 of file context.cpp.
{
}
ArgumentListContext() [3/4]
ArgumentListContext::ArgumentListContext ()
ArgumentListContext() [4/4]
ArgumentListContext::ArgumentListContext (const ArgumentList & al, const Definition * def, const QCString & relPath)
 ArgumentListContext() [2/2]
virtual ArgumentListContext::~ArgumentListContext () [virtual]
Member Function Documentation
alloc() [1/4]
static TemplateListIntfPtr ArgumentListContext::alloc () [inline], [static]
Definition at line 1206 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<ArgumentListContext>()); }
Referenced by ClassContext::Private::addTemplateDecls(), MemberContext::Private::createParameters(), MemberContext::Private::createTemplateArgs(), MemberContext::Private::createTemplateDecls(), ConceptContext::Private::createTemplateDecls(), ClassContext::Private::createTypeConstraints(), and MemberContext::Private::createTypeConstraints().
alloc() [2/4]
static TemplateListIntfPtr ArgumentListContext::alloc () [inline], [static]
Definition at line 1206 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<ArgumentListContext>()); }
alloc() [3/4]
static TemplateListIntfPtr ArgumentListContext::alloc (const ArgumentList & al, const Definition * def, const QCString & relPath) [inline], [static]
Definition at line 1208 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<ArgumentListContext>(al,def,relPath)); }
alloc() [4/4]
static TemplateListIntfPtr ArgumentListContext::alloc (const ArgumentList & al, const Definition * def, const QCString & relPath) [inline], [static]
Definition at line 1208 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<ArgumentListContext>(al,def,relPath)); }
at() [1/2]
TemplateVariant ArgumentListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 8328 of file context.cpp.
{
  return p->at(index);
}
References p.
at() [2/2]
virtual TemplateVariant ArgumentListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
count() [1/2]
size_t ArgumentListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Definition at line 8323 of file context.cpp.
{
  return p->count();
}
References p.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
count() [2/2]
virtual size_t ArgumentListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
createIterator() [1/2]
TemplateListIntf::ConstIteratorPtr ArgumentListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 8333 of file context.cpp.
{
  return p->createIterator();
}
References p.
createIterator() [2/2]
virtual TemplateListIntf::ConstIteratorPtr ArgumentListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Member Data Documentation
p
std::unique_ptr< Private > ArgumentListContext::p [private]
Definition at line 1222 of file context.h.
Referenced by ArgumentListContext(), at(), count(), and createIterator().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.h
doxygen/src/context.h
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp