IndexList Class Reference
A list of index interfaces.
#include <indexlist.h>
Public Member Functions
void disable ()
void enable ()
bool isEnabled () const
template<class T , class... As>
void addIndex (As &&... args)
void initialize ()
void finalize ()
void incContentsDepth ()
void decContentsDepth ()
void addContentsItem (bool isDir, const QCString &name, const QCString &ref, const QCString &file, const QCString &anchor, bool separateIndex=FALSE, bool addToNavIndex=FALSE, const Definition *def=0)
void addIndexItem (const Definition *context, const MemberDef *md, const QCString &sectionAnchor=QCString(), const QCString &title=QCString())
void addIndexFile (const QCString &name)
void addImageFile (const QCString &name)
void addStyleSheetFile (const QCString &name)
void disable ()
void enable ()
bool isEnabled () const
template<class T , class... As>
void addIndex (As &&... args)
void initialize ()
void finalize ()
void incContentsDepth ()
void decContentsDepth ()
void addContentsItem (bool isDir, const QCString &name, const QCString &ref, const QCString &file, const QCString &anchor, bool separateIndex=FALSE, bool addToNavIndex=FALSE, const Definition *def=0)
void addIndexItem (const Definition *context, const MemberDef *md, const QCString &sectionAnchor=QCString(), const QCString &title=QCString())
void addIndexFile (const QCString &name)
void addImageFile (const QCString &name)
void addStyleSheetFile (const QCString &name)
Private Types
using IndexVariant = std::variant< DocSets, EclipseHelp, FTVHelp, HtmlHelp, Qhp >
using IndexVariant = std::variant< DocSets, EclipseHelp, FTVHelp, HtmlHelp, Qhp >
Private Member Functions
template<template< class > class IndexT, class... As>
void foreach (As &&... args)
template<template< class > class IndexT, class... As>
void foreach_locked (As &&... args)
template<template< class > class IndexT, class... As>
void foreach (As &&... args)
template<template< class > class IndexT, class... As>
void foreach_locked (As &&... args)
Private Attributes
bool m_enabled = true
std::mutex m_mutex
std::vector< IndexVariant > m_indices
Detailed Description
A list of index interfaces.
This class itself implements all methods of IndexIntf and just forwards the calls to all items in the list (composite design pattern).
Definition at line 59 of file indexlist.h.
Member Typedef Documentation
IndexVariant [1/2]
using IndexList::IndexVariant = std::variant<DocSets, EclipseHelp, FTVHelp, HtmlHelp, Qhp> [private]
Definition at line 61 of file indexlist.h.
IndexVariant [2/2]
using IndexList::IndexVariant = std::variant<DocSets, EclipseHelp, FTVHelp, HtmlHelp, Qhp> [private]
Definition at line 61 of file indexlist.h.
Member Function Documentation
addContentsItem() [1/2]
void IndexList::addContentsItem (bool isDir, const QCString & name, const QCString & ref, const QCString & file, const QCString & anchor, bool separateIndex = FALSE, bool addToNavIndex = FALSE, const Definition * def = 0) [inline]
Definition at line 111 of file indexlist.h.
    { if (m_enabled) foreach_locked<IndexIntf::addContentsItem>(isDir,name,ref,file,anchor,separateIndex,addToNavIndex,def); }
References caseconvert::file, m_enabled, and setup::name.
Referenced by addMembersToIndex(), DefinitionImpl::addSectionsToIndex(), writeAlphabeticalExceptionIndex(), writeAlphabeticalIndex(), writeAlphabeticalInterfaceIndex(), writeAlphabeticalStructIndex(), writeAnnotatedIndexGeneric(), writeClassMemberIndex(), writeClassMemberIndexFiltered(), writeClassTreeForList(), writeClassTreeInsideNamespaceElement(), writeClassTreeToOutput(), writeConceptIndex(), writeConceptList(), writeConceptRootList(), writeConceptTreeInsideNamespaceElement(), writeDirHierarchy(), writeDirTreeNode(), writeExampleIndex(), writeFileIndex(), writeFileMemberIndex(), writeFileMemberIndexFiltered(), writeGroupIndex(), writeGroupTreeNode(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), writeIndex(), writeIndexHierarchyEntries(), writeMemberToIndex(), writeNamespaceIndex(), writeNamespaceMemberIndex(), writeNamespaceMemberIndexFiltered(), writeNamespaceTreeElement(), and writePages().
addContentsItem() [2/2]
void IndexList::addContentsItem (bool isDir, const QCString & name, const QCString & ref, const QCString & file, const QCString & anchor, bool separateIndex = FALSE, bool addToNavIndex = FALSE, const Definition * def = 0) [inline]
Definition at line 111 of file indexlist.h.
    { if (m_enabled) foreach_locked<IndexIntf::addContentsItem>(isDir,name,ref,file,anchor,separateIndex,addToNavIndex,def); }
References caseconvert::file, m_enabled, and setup::name.
addImageFile() [1/2]
void IndexList::addImageFile (const QCString & name) [inline]
Definition at line 122 of file indexlist.h.
    { if (m_enabled) foreach_locked<IndexIntf::addImageFile>(name); }
References m_enabled, and setup::name.
Referenced by copyExtraFiles(), copyLogo(), FormulaManager::createLatexFile(), DocParser::findAndCopyImage(), PlantumlManager::generatePlantUMLOutput(), writeColoredImgData(), writeDotGraphFromFile(), DotGraph::writeGraph(), ClassDiagram::writeImage(), writeMscGraphFromFile(), HtmlGenerator::writeSearchData(), and HtmlGenerator::writeTabData().
addImageFile() [2/2]
void IndexList::addImageFile (const QCString & name) [inline]
Definition at line 122 of file indexlist.h.
    { if (m_enabled) foreach_locked<IndexIntf::addImageFile>(name); }
References m_enabled, and setup::name.
addIndex() [1/2]
template<class T , class... As>
void IndexList::addIndex (As &&... args) [inline]
Add an index generator to the list, using a syntax similar to std::make_unique<T>()
Definition at line 96 of file indexlist.h.
    { m_indices.push_back(std::move(T{std::forward<As>(args)...})); }
References m_indices.
Referenced by parseInput().
addIndex() [2/2]
template<class T , class... As>
void IndexList::addIndex (As &&... args) [inline]
Add an index generator to the list, using a syntax similar to std::make_unique<T>()
Definition at line 96 of file indexlist.h.
    { m_indices.push_back(std::move(T{std::forward<As>(args)...})); }
References m_indices.
addIndexFile() [1/2]
void IndexList::addIndexFile (const QCString & name) [inline]
Definition at line 119 of file indexlist.h.
    { if (m_enabled) foreach_locked<IndexIntf::addIndexFile>(name); }
References m_enabled, and setup::name.
Referenced by HtmlGenerator::startFile().
addIndexFile() [2/2]
void IndexList::addIndexFile (const QCString & name) [inline]
Definition at line 119 of file indexlist.h.
    { if (m_enabled) foreach_locked<IndexIntf::addIndexFile>(name); }
References m_enabled, and setup::name.
addIndexItem() [1/2]
void IndexList::addIndexItem (const Definition * context, const MemberDef * md, const QCString & sectionAnchor = QCString(), const QCString & title = QCString()) [inline]
Definition at line 116 of file indexlist.h.
    { if (m_enabled) foreach_locked<IndexIntf::addIndexItem>(context,md,sectionAnchor,title); }
References m_enabled.
Referenced by addToIndices(), and HtmlDocVisitor::operator()().
addIndexItem() [2/2]
void IndexList::addIndexItem (const Definition * context, const MemberDef * md, const QCString & sectionAnchor = QCString(), const QCString & title = QCString()) [inline]
Definition at line 116 of file indexlist.h.
    { if (m_enabled) foreach_locked<IndexIntf::addIndexItem>(context,md,sectionAnchor,title); }
References m_enabled.
addStyleSheetFile() [1/2]
void IndexList::addStyleSheetFile (const QCString & name) [inline]
Definition at line 125 of file indexlist.h.
    { if (m_enabled) foreach_locked<IndexIntf::addStyleSheetFile>(name); }
References m_enabled, and setup::name.
Referenced by writeJavaScriptSearchIndex(), HtmlGenerator::writeSearchData(), HtmlGenerator::writeStyleInfo(), and HtmlGenerator::writeTabData().
addStyleSheetFile() [2/2]
void IndexList::addStyleSheetFile (const QCString & name) [inline]
Definition at line 125 of file indexlist.h.
    { if (m_enabled) foreach_locked<IndexIntf::addStyleSheetFile>(name); }
References m_enabled, and setup::name.
decContentsDepth() [1/2]
void IndexList::decContentsDepth () [inline]
Definition at line 108 of file indexlist.h.
    { if (m_enabled) foreach_locked<IndexIntf::decContentsDepth>(); }
References m_enabled.
Referenced by addMembersToIndex(), DefinitionImpl::addSectionsToIndex(), toDefinition(), writeAnnotatedIndexGeneric(), writeClassHierarchy(), writeClassMemberIndex(), writeClassMemberIndexFiltered(), writeClassTreeInsideNamespaceElement(), writeClassTreeToOutput(), writeConceptIndex(), writeConceptTreeInsideNamespaceElement(), writeDirTreeNode(), writeExampleIndex(), writeFileIndex(), writeFileMemberIndex(), writeFileMemberIndexFiltered(), writeGroupIndex(), writeGroupTreeNode(), writeIndexHierarchyEntries(), writeMemberToIndex(), writeNamespaceIndex(), writeNamespaceMemberIndex(), writeNamespaceMemberIndexFiltered(), writeNamespaceTreeElement(), and writePages().
decContentsDepth() [2/2]
void IndexList::decContentsDepth () [inline]
Definition at line 108 of file indexlist.h.
    { if (m_enabled) foreach_locked<IndexIntf::decContentsDepth>(); }
References m_enabled.
disable() [1/2]
void IndexList::disable () [inline]
disable the indices
Definition at line 83 of file indexlist.h.
    { m_enabled = FALSE; }
References FALSE, and m_enabled.
Referenced by writeAnnotatedIndexGeneric(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), and writeHierarchicalInterfaceIndex().
disable() [2/2]
void IndexList::disable () [inline]
disable the indices
Definition at line 83 of file indexlist.h.
    { m_enabled = FALSE; }
References FALSE, and m_enabled.
enable() [1/2]
void IndexList::enable () [inline]
enable the indices
Definition at line 87 of file indexlist.h.
    { m_enabled = TRUE; }
References m_enabled, and TRUE.
Referenced by writeAnnotatedIndexGeneric(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), and writeHierarchicalInterfaceIndex().
enable() [2/2]
void IndexList::enable () [inline]
enable the indices
Definition at line 87 of file indexlist.h.
    { m_enabled = TRUE; }
References m_enabled, and TRUE.
finalize() [1/2]
void IndexList::finalize () [inline]
Definition at line 102 of file indexlist.h.
    { foreach<IndexIntf::finalize>(); }
Referenced by generateOutput().
finalize() [2/2]
void IndexList::finalize () [inline]
Definition at line 102 of file indexlist.h.
    { foreach<IndexIntf::finalize>(); }
foreach() [1/2]
template<template< class > class IndexT, class... As>
void IndexList::foreach (As &&... args) [inline], [private]
Definition at line 64 of file indexlist.h.
    {
      for (auto &v : m_indices)
      {
        dispatch_call<IndexT>(v,std::forward<As>(args)...);
      }
    }
References m_indices.
foreach() [2/2]
template<template< class > class IndexT, class... As>
void IndexList::foreach (As &&... args) [inline], [private]
Definition at line 64 of file indexlist.h.
    {
      for (auto &v : m_indices)
      {
        dispatch_call<IndexT>(v,std::forward<As>(args)...);
      }
    }
References m_indices.
foreach_locked() [1/2]
template<template< class > class IndexT, class... As>
void IndexList::foreach_locked (As &&... args) [inline], [private]
Definition at line 72 of file indexlist.h.
    {
      std::lock_guard<std::mutex> lock(m_mutex);
      for (auto &v : m_indices)
      {
        dispatch_call<IndexT>(v,std::forward<As>(args)...);
      }
    }
References m_indices, and m_mutex.
foreach_locked() [2/2]
template<template< class > class IndexT, class... As>
void IndexList::foreach_locked (As &&... args) [inline], [private]
Definition at line 72 of file indexlist.h.
    {
      std::lock_guard<std::mutex> lock(m_mutex);
      for (auto &v : m_indices)
      {
        dispatch_call<IndexT>(v,std::forward<As>(args)...);
      }
    }
References m_indices, and m_mutex.
incContentsDepth() [1/2]
void IndexList::incContentsDepth () [inline]
Definition at line 105 of file indexlist.h.
    { if (m_enabled) foreach_locked<IndexIntf::incContentsDepth>(); }
References m_enabled.
Referenced by addMembersToIndex(), DefinitionImpl::addSectionsToIndex(), writeAnnotatedIndexGeneric(), writeClassMemberIndex(), writeClassMemberIndexFiltered(), writeClassTreeForList(), writeClassTreeInsideNamespaceElement(), writeClassTreeToOutput(), writeConceptIndex(), writeConceptTreeInsideNamespaceElement(), writeDirTreeNode(), writeExampleIndex(), writeFileIndex(), writeFileMemberIndex(), writeFileMemberIndexFiltered(), writeGroupIndex(), writeGroupTreeNode(), writeIndexHierarchyEntries(), writeMemberToIndex(), writeNamespaceIndex(), writeNamespaceMemberIndex(), writeNamespaceMemberIndexFiltered(), writeNamespaceTreeElement(), and writePages().
incContentsDepth() [2/2]
void IndexList::incContentsDepth () [inline]
Definition at line 105 of file indexlist.h.
    { if (m_enabled) foreach_locked<IndexIntf::incContentsDepth>(); }
References m_enabled.
initialize() [1/2]
void IndexList::initialize () [inline]
Definition at line 99 of file indexlist.h.
    { foreach<IndexIntf::initialize>(); }
Referenced by parseInput().
initialize() [2/2]
void IndexList::initialize () [inline]
Definition at line 99 of file indexlist.h.
    { foreach<IndexIntf::initialize>(); }
isEnabled() [1/2]
bool IndexList::isEnabled () const [inline]
returns true iff the indices are enabled
Definition at line 91 of file indexlist.h.
    { return m_enabled; }
References m_enabled.
isEnabled() [2/2]
bool IndexList::isEnabled () const [inline]
returns true iff the indices are enabled
Definition at line 91 of file indexlist.h.
    { return m_enabled; }
References m_enabled.
Member Data Documentation
m_enabled
bool IndexList::m_enabled = true [private]
Definition at line 129 of file indexlist.h.
Referenced by addContentsItem(), addImageFile(), addIndexFile(), addIndexItem(), addStyleSheetFile(), decContentsDepth(), disable(), enable(), incContentsDepth(), and isEnabled().
m_indices
std::vector< IndexVariant > IndexList::m_indices [private]
Definition at line 131 of file indexlist.h.
Referenced by addIndex(), foreach(), and foreach_locked().
m_mutex
std::mutex IndexList::m_mutex [private]
Definition at line 130 of file indexlist.h.
Referenced by foreach_locked().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/indexlist.h
doxygen/src/indexlist.h