ClassListContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
ClassListContext ()
virtual ~ClassListContext ()
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
ClassListContext ()
virtual ~ClassListContext ()
Static Public Member Functions
static TemplateListIntfPtr alloc ()
static TemplateListIntfPtr alloc ()
Private Attributes
std::unique_ptr< Private > p
Additional Inherited Members
Detailed Description
Definition at line 358 of file context.h.
Constructor & Destructor Documentation
ClassListContext() [1/2]
ClassListContext::ClassListContext ()
Definition at line 5016 of file context.cpp.
                                   : p(std::make_unique<Private>())
{
  p->addClasses(*Doxygen::classLinkedMap);
  p->addClasses(*Doxygen::hiddenClassLinkedMap);
}
References Doxygen::classLinkedMap, Doxygen::hiddenClassLinkedMap, and p.
 ClassListContext() [1/2]
ClassListContext::~ClassListContext () [virtual]
Definition at line 5022 of file context.cpp.
{
}
ClassListContext() [2/2]
ClassListContext::ClassListContext ()
 ClassListContext() [2/2]
virtual ClassListContext::~ClassListContext () [virtual]
Member Function Documentation
alloc() [1/2]
static TemplateListIntfPtr ClassListContext::alloc () [inline], [static]
Definition at line 361 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<ClassListContext>()); }
Referenced by generateOutputViaTemplate().
alloc() [2/2]
static TemplateListIntfPtr ClassListContext::alloc () [inline], [static]
Definition at line 361 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<ClassListContext>()); }
at() [1/2]
TemplateVariant ClassListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 5032 of file context.cpp.
{
  return p->at(index);
}
References p.
at() [2/2]
virtual TemplateVariant ClassListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
count() [1/2]
size_t ClassListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Definition at line 5027 of file context.cpp.
{
  return p->count();
}
References p.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
count() [2/2]
virtual size_t ClassListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
createIterator() [1/2]
TemplateListIntf::ConstIteratorPtr ClassListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 5037 of file context.cpp.
{
  return p->createIterator();
}
References p.
createIterator() [2/2]
virtual TemplateListIntf::ConstIteratorPtr ClassListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Member Data Documentation
p
std::unique_ptr< Private > ClassListContext::p [private]
Definition at line 374 of file context.h.
Referenced by at(), ClassListContext(), count(), and createIterator().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.h
doxygen/src/context.h
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp