anonymous_namespace{CharStream.cc}::StringReaderStream Class Reference
Public Member Functions
StringReaderStream (const JJString &str)
virtual size_t read (JJChar *bufptr, int offset, size_t len)
virtual ~StringReaderStream ()
virtual bool endOfInput ()
StringReaderStream (const JJString &str)
virtual size_t read (JJChar *bufptr, int offset, size_t len)
virtual ~StringReaderStream ()
virtual bool endOfInput ()
Private Attributes
const JJString str_
size_t cur_
size_t max_
Detailed Description
Definition at line 13 of file CharStream.cc.
Constructor & Destructor Documentation
StringReaderStream() [1/2]
anonymous_namespace{CharStream.cc}::StringReaderStream::StringReaderStream (const JJString & str) [inline]
Definition at line 15 of file CharStream.cc.
: str_(str), cur_(0), max_(str.size()) {}
 StringReaderStream() [1/2]
virtual anonymous_namespace{CharStream.cc}::StringReaderStream::~StringReaderStream () [inline], [virtual]
Definition at line 22 of file CharStream.cc.
{}
StringReaderStream() [2/2]
anonymous_namespace{CharStream.cc}::StringReaderStream::StringReaderStream (const JJString & str) [inline]
Definition at line 15 of file CharStream.cc.
: str_(str), cur_(0), max_(str.size()) {}
 StringReaderStream() [2/2]
virtual anonymous_namespace{CharStream.cc}::StringReaderStream::~StringReaderStream () [inline], [virtual]
Definition at line 22 of file CharStream.cc.
{}
Member Function Documentation
endOfInput() [1/2]
virtual bool anonymous_namespace{CharStream.cc}::StringReaderStream::endOfInput () [inline], [virtual]
Reimplemented from ReaderStream.
Definition at line 23 of file CharStream.cc.
                            {
    return max_ == 0;
  }
endOfInput() [2/2]
virtual bool anonymous_namespace{CharStream.cc}::StringReaderStream::endOfInput () [inline], [virtual]
Reimplemented from ReaderStream.
Definition at line 23 of file CharStream.cc.
                            {
    return max_ == 0;
  }
read() [1/2]
virtual size_t anonymous_namespace{CharStream.cc}::StringReaderStream::read (JJChar * bufptr, int offset, size_t len) [inline], [virtual]
Reimplemented from ReaderStream.
Definition at line 16 of file CharStream.cc.
                                                              {
    size_t count = str_.copy(bufptr + offset, len > max_ ? max_ : len, cur_);
    cur_ += count;
    max_ -= count;
    return count;
  }
References len, and offset.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_read(), doxmlparser.compound.memberdefType::hasContent_(), and doxmlparser.compound.memberdefType::set_read().
read() [2/2]
virtual size_t anonymous_namespace{CharStream.cc}::StringReaderStream::read (JJChar * bufptr, int offset, size_t len) [inline], [virtual]
Reimplemented from ReaderStream.
Definition at line 16 of file CharStream.cc.
                                                              {
    size_t count = str_.copy(bufptr + offset, len > max_ ? max_ : len, cur_);
    cur_ += count;
    max_ -= count;
    return count;
  }
References len, and offset.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_read(), doxmlparser.compound.memberdefType::hasContent_(), and doxmlparser.compound.memberdefType::set_read().
Member Data Documentation
cur_
size_t anonymous_namespace{CharStream.cc}::StringReaderStream::cur_ [private]
Definition at line 29 of file CharStream.cc.
max_
size_t anonymous_namespace{CharStream.cc}::StringReaderStream::max_ [private]
Definition at line 30 of file CharStream.cc.
str_
const JJString anonymous_namespace{CharStream.cc}::StringReaderStream::str_ [private]
Definition at line 28 of file CharStream.cc.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/vhdlparser/CharStream.cc
doxygen/vhdlparser/CharStream.cc