TemplateEngine::Private::IncludeEntry Class Reference
Public Types
enum Type { Template
, Block
, Template
, Block
 }
enum Type { Template
, Block
, Template
, Block
 }
Public Member Functions
IncludeEntry (Type type, const QCString &fileName, const QCString &blockName, int line)
Type type () const
QCString fileName () const
QCString blockName () const
int line () const
IncludeEntry (Type type, const QCString &fileName, const QCString &blockName, int line)
Type type () const
QCString fileName () const
QCString blockName () const
int line () const
Private Attributes
Type m_type = Template
QCString m_fileName
QCString m_blockName
int m_line = 0
Detailed Description
Definition at line 5227 of file template.cpp.
Member Enumeration Documentation
Type [1/2]
enum TemplateEngine::Private::IncludeEntry::Type
Enumerator
Template
Block
Template
Block
Definition at line 5230 of file template.cpp.
{ Template, Block };
Type [2/2]
enum TemplateEngine::Private::IncludeEntry::Type
Enumerator
Template
Block
Template
Block
Definition at line 5230 of file template.cpp.
{ Template, Block };
Constructor & Destructor Documentation
IncludeEntry() [1/2]
TemplateEngine::Private::IncludeEntry::IncludeEntry (Type type, const QCString & fileName, const QCString & blockName, int line) [inline]
Definition at line 5231 of file template.cpp.
          : m_type(type), m_fileName(fileName), m_blockName(blockName), m_line(line) {}
IncludeEntry() [2/2]
TemplateEngine::Private::IncludeEntry::IncludeEntry (Type type, const QCString & fileName, const QCString & blockName, int line) [inline]
Definition at line 5231 of file template.cpp.
          : m_type(type), m_fileName(fileName), m_blockName(blockName), m_line(line) {}
Member Function Documentation
blockName() [1/2]
QCString TemplateEngine::Private::IncludeEntry::blockName () const [inline]
Definition at line 5235 of file template.cpp.
{ return m_blockName; }
References m_blockName.
Referenced by TemplateEngine::Private::printIncludeContext().
blockName() [2/2]
QCString TemplateEngine::Private::IncludeEntry::blockName () const [inline]
Definition at line 5235 of file template.cpp.
{ return m_blockName; }
References m_blockName.
fileName() [1/2]
QCString TemplateEngine::Private::IncludeEntry::fileName () const [inline]
Definition at line 5234 of file template.cpp.
{ return m_fileName; }
References m_fileName.
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), TemplateEngine::Private::printIncludeContext(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
fileName() [2/2]
QCString TemplateEngine::Private::IncludeEntry::fileName () const [inline]
Definition at line 5234 of file template.cpp.
{ return m_fileName; }
References m_fileName.
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
line() [1/2]
int TemplateEngine::Private::IncludeEntry::line () const [inline]
Definition at line 5236 of file template.cpp.
{ return m_line; }
References m_line.
Referenced by doxmlparser.compound.locationType::__init__(), doxmlparser.compound.locationType::buildAttributes(), doxmlparser.compound.locationType::exportAttributes(), doxmlparser.compound.locationType::get_line(), TemplateEngine::Private::printIncludeContext(), and doxmlparser.compound.locationType::set_line().
line() [2/2]
int TemplateEngine::Private::IncludeEntry::line () const [inline]
Definition at line 5236 of file template.cpp.
{ return m_line; }
References m_line.
Referenced by doxmlparser.compound.locationType::__init__(), doxmlparser.compound.locationType::buildAttributes(), doxmlparser.compound.locationType::exportAttributes(), doxmlparser.compound.locationType::get_line(), and doxmlparser.compound.locationType::set_line().
type() [1/2]
Type TemplateEngine::Private::IncludeEntry::type () const [inline]
Definition at line 5233 of file template.cpp.
{ return m_type; }
References m_type.
Referenced by TemplateEngine::Private::printIncludeContext().
type() [2/2]
Type TemplateEngine::Private::IncludeEntry::type () const [inline]
Definition at line 5233 of file template.cpp.
{ return m_type; }
References m_type.
Member Data Documentation
m_blockName
QCString TemplateEngine::Private::IncludeEntry::m_blockName [private]
Definition at line 5241 of file template.cpp.
Referenced by blockName().
m_fileName
QCString TemplateEngine::Private::IncludeEntry::m_fileName [private]
Definition at line 5240 of file template.cpp.
Referenced by fileName().
m_line
int TemplateEngine::Private::IncludeEntry::m_line = 0 [private]
Definition at line 5242 of file template.cpp.
Referenced by line().
m_type
Type TemplateEngine::Private::IncludeEntry::m_type = Template [private]
Definition at line 5239 of file template.cpp.
Referenced by type().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp