TranslatorChinesetraditional Class Reference
#include <translator_tw.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString latexFontenc ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool, bool)
virtual QCString trFile (bool, bool)
virtual QCString trNamespace (bool, bool)
virtual QCString trGroup (bool, bool)
virtual QCString trPage (bool, bool)
virtual QCString trMember (bool, bool)
virtual QCString trGlobal (bool, bool)
virtual QCString trAuthor (bool, bool)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool, bool)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool, bool)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool)
virtual QCString trType (bool, bool)
virtual QCString trSubprogram (bool, bool)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool)
virtual QCString trSingletonGeneratedFromFiles (bool)
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString latexFontenc ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool, bool)
virtual QCString trFile (bool, bool)
virtual QCString trNamespace (bool, bool)
virtual QCString trGroup (bool, bool)
virtual QCString trPage (bool, bool)
virtual QCString trMember (bool, bool)
virtual QCString trGlobal (bool, bool)
virtual QCString trAuthor (bool, bool)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool, bool)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool, bool)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool)
virtual QCString trType (bool, bool)
virtual QCString trSubprogram (bool, bool)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool)
virtual QCString trSingletonGeneratedFromFiles (bool)
Additional Inherited Members
Detailed Description
Definition at line 44 of file translator_tw.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorChinesetraditional::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 93 of file translator_tw.h.
    {
      return "0x404 Chinese (Taiwan)";
    }
getLanguageString() [2/2]
virtual QCString TranslatorChinesetraditional::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 93 of file translator_tw.h.
    {
      return "0x404 Chinese (Taiwan)";
    }
idLanguage() [1/2]
virtual QCString TranslatorChinesetraditional::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 56 of file translator_tw.h.
    { return "chinese-traditional"; }
idLanguage() [2/2]
virtual QCString TranslatorChinesetraditional::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 56 of file translator_tw.h.
    { return "chinese-traditional"; }
latexDocumentPost() [1/2]
virtual QCString TranslatorChinesetraditional::latexDocumentPost () [inline], [virtual]
Sets the commands to be inserted directly before the \\end{document} in the LaTeX document.
Reimplemented from Translator.
Definition at line 85 of file translator_tw.h.
    {
      return "\\end{CJK}\n";
    }
latexDocumentPost() [2/2]
virtual QCString TranslatorChinesetraditional::latexDocumentPost () [inline], [virtual]
Sets the commands to be inserted directly before the \\end{document} in the LaTeX document.
Reimplemented from Translator.
Definition at line 85 of file translator_tw.h.
    {
      return "\\end{CJK}\n";
    }
latexDocumentPre() [1/2]
virtual QCString TranslatorChinesetraditional::latexDocumentPre () [inline], [virtual]
Sets the commands to be inserted directly after the \\begin{document} in the LaTeX document.
Reimplemented from Translator.
Definition at line 81 of file translator_tw.h.
    {
      return "\\begin{CJK}{UTF8}{min}\n";
    }
latexDocumentPre() [2/2]
virtual QCString TranslatorChinesetraditional::latexDocumentPre () [inline], [virtual]
Sets the commands to be inserted directly after the \\begin{document} in the LaTeX document.
Reimplemented from Translator.
Definition at line 81 of file translator_tw.h.
    {
      return "\\begin{CJK}{UTF8}{min}\n";
    }
latexFontenc() [1/2]
virtual QCString TranslatorChinesetraditional::latexFontenc () [inline], [virtual]
Sets the LaTeX font encoding to be used. The default is set to T1, in case another font encoding has to be used this can be specified with this routine. In case no font encoding is required the empty string can be returned.
Reimplemented from Translator.
Definition at line 77 of file translator_tw.h.
    {
      return "";
    }
latexFontenc() [2/2]
virtual QCString TranslatorChinesetraditional::latexFontenc () [inline], [virtual]
Sets the LaTeX font encoding to be used. The default is set to T1, in case another font encoding has to be used this can be specified with this routine. In case no font encoding is required the empty string can be returned.
Reimplemented from Translator.
Definition at line 77 of file translator_tw.h.
    {
      return "";
    }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorChinesetraditional::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 73 of file translator_tw.h.
    {
      return "\\usepackage{CJKutf8}\n";
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorChinesetraditional::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 73 of file translator_tw.h.
    {
      return "\\usepackage{CJKutf8}\n";
    }
trAdditionalInheritedMembers() [1/2]
virtual QCString TranslatorChinesetraditional::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1871 of file translator_tw.h.
    { return ""; }
trAdditionalInheritedMembers() [2/2]
virtual QCString TranslatorChinesetraditional::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1871 of file translator_tw.h.
    { return ""; }
trAll() [1/2]
virtual QCString TranslatorChinesetraditional::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1399 of file translator_tw.h.
    {
      return "";
    }
trAll() [2/2]
virtual QCString TranslatorChinesetraditional::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1399 of file translator_tw.h.
    {
      return "";
    }
trAndMore() [1/2]
virtual QCString TranslatorChinesetraditional::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1849 of file translator_tw.h.
    { return " "+number+" ..."; }
trAndMore() [2/2]
virtual QCString TranslatorChinesetraditional::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1849 of file translator_tw.h.
    { return " "+number+" ..."; }
trAttention() [1/2]
virtual QCString TranslatorChinesetraditional::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 977 of file translator_tw.h.
    {
      return "";
    }
trAttention() [2/2]
virtual QCString TranslatorChinesetraditional::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 977 of file translator_tw.h.
    {
      return "";
    }
trAuthor() [1/2]
virtual QCString TranslatorChinesetraditional::trAuthor (bool , bool) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1272 of file translator_tw.h.
    {
      return QCString("");
    }
trAuthor() [2/2]
virtual QCString TranslatorChinesetraditional::trAuthor (bool , bool) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1272 of file translator_tw.h.
    {
      return QCString("");
    }
trBug() [1/2]
virtual QCString TranslatorChinesetraditional::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1144 of file translator_tw.h.
    {
      return "";
    }
trBug() [2/2]
virtual QCString TranslatorChinesetraditional::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1144 of file translator_tw.h.
    {
      return "";
    }
trBugList() [1/2]
virtual QCString TranslatorChinesetraditional::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1149 of file translator_tw.h.
    {
      return "";
    }
trBugList() [2/2]
virtual QCString TranslatorChinesetraditional::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1149 of file translator_tw.h.
    {
      return "";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorChinesetraditional::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1516 of file translator_tw.h.
    {
      return ":";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorChinesetraditional::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1516 of file translator_tw.h.
    {
      return ":";
    }
trCallGraph() [1/2]
virtual QCString TranslatorChinesetraditional::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1404 of file translator_tw.h.
    {
      return ":";
    }
trCallGraph() [2/2]
virtual QCString TranslatorChinesetraditional::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1404 of file translator_tw.h.
    {
      return ":";
    }
trCiteReferences() [1/2]
virtual QCString TranslatorChinesetraditional::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1825 of file translator_tw.h.
    { return ""; }
trCiteReferences() [2/2]
virtual QCString TranslatorChinesetraditional::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1825 of file translator_tw.h.
    { return ""; }
trClass() [1/2]
virtual QCString TranslatorChinesetraditional::trClass (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1207 of file translator_tw.h.
    {
      return QCString("");
    }
trClass() [2/2]
virtual QCString TranslatorChinesetraditional::trClass (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1207 of file translator_tw.h.
    {
      return QCString("");
    }
trClassDiagram() [1/2]
virtual QCString TranslatorChinesetraditional::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 531 of file translator_tw.h.
    {
      return ""+clName+":";
    }
trClassDiagram() [2/2]
virtual QCString TranslatorChinesetraditional::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 531 of file translator_tw.h.
    {
      return ""+clName+":";
    }
trClassDocumentation() [1/2]
virtual QCString TranslatorChinesetraditional::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 400 of file translator_tw.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorChinesetraditional::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 400 of file translator_tw.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorChinesetraditional::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1106 of file translator_tw.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorChinesetraditional::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1106 of file translator_tw.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorChinesetraditional::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 188 of file translator_tw.h.
    { return ""; }
trClassHierarchy() [2/2]
virtual QCString TranslatorChinesetraditional::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 188 of file translator_tw.h.
    { return ""; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorChinesetraditional::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 247 of file translator_tw.h.
    { return ": ";
    }
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorChinesetraditional::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 247 of file translator_tw.h.
    { return ": ";
    }
trClassMethods() [1/2]
virtual QCString TranslatorChinesetraditional::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1909 of file translator_tw.h.
    {
      return "";
    }
trClassMethods() [2/2]
virtual QCString TranslatorChinesetraditional::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1909 of file translator_tw.h.
    {
      return "";
    }
trCode() [1/2]
virtual QCString TranslatorChinesetraditional::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 877 of file translator_tw.h.
    {
      return "";
    }
trCode() [2/2]
virtual QCString TranslatorChinesetraditional::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 877 of file translator_tw.h.
    {
      return "";
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorChinesetraditional::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 832 of file translator_tw.h.
    {
      return ""+clName+":";
    }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorChinesetraditional::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 832 of file translator_tw.h.
    {
      return ""+clName+":";
    }
trCompoundIndex() [1/2]
virtual QCString TranslatorChinesetraditional::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 373 of file translator_tw.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorChinesetraditional::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 373 of file translator_tw.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorChinesetraditional::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1566 of file translator_tw.h.
    { return ""; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorChinesetraditional::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1566 of file translator_tw.h.
    { return ""; }
trCompoundList() [1/2]
virtual QCString TranslatorChinesetraditional::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 192 of file translator_tw.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorChinesetraditional::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 192 of file translator_tw.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorChinesetraditional::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 261 of file translator_tw.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return ":";
      }
      else
      {
        return ""
               "(unions)(interfaces):";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorChinesetraditional::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 261 of file translator_tw.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return ":";
      }
      else
      {
        return ""
               "(unions)(interfaces):";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorChinesetraditional::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1539 of file translator_tw.h.
    { return ":"; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorChinesetraditional::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1539 of file translator_tw.h.
    { return ":"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorChinesetraditional::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1531 of file translator_tw.h.
    { return ""; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorChinesetraditional::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1531 of file translator_tw.h.
    { return ""; }
trCompoundMembers() [1/2]
virtual QCString TranslatorChinesetraditional::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 209 of file translator_tw.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorChinesetraditional::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 209 of file translator_tw.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorChinesetraditional::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 276 of file translator_tw.h.
    {
      QCString result="";
      if (!extractAll)
      {
        result+="";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="";
      }
      else
      {
        result+="";
      }
      result+=", ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="/:";
        }
        else
        {
          result+=":";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="/:";
        }
        else
        {
          result+=":";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorChinesetraditional::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 276 of file translator_tw.h.
    {
      QCString result="";
      if (!extractAll)
      {
        result+="";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="";
      }
      else
      {
        result+="";
      }
      result+=", ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="/:";
        }
        else
        {
          result+=":";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="/:";
        }
        else
        {
          result+=":";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorChinesetraditional::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1543 of file translator_tw.h.
    {
      QCString result="";
      if (!extractAll)
      {
        result+="";
      }
      result+="";
      result+=" ";
      if (!extractAll)
      {
         result+="";
      }
      else
      {
         result+="";
      }
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorChinesetraditional::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1543 of file translator_tw.h.
    {
      QCString result="";
      if (!extractAll)
      {
        result+="";
      }
      result+="";
      result+=" ";
      if (!extractAll)
      {
         result+="";
      }
      else
      {
         result+="";
      }
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorChinesetraditional::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1535 of file translator_tw.h.
    { return ""; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorChinesetraditional::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1535 of file translator_tw.h.
    { return ""; }
trCompoundReference() [1/2]
virtual QCString TranslatorChinesetraditional::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 606 of file translator_tw.h.
    {
      QCString result=clName+" ";
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      if (isTemplate) result+=" ";
      result+=" ";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorChinesetraditional::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 606 of file translator_tw.h.
    {
      QCString result=clName+" ";
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      if (isTemplate) result+=" ";
      result+=" ";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorChinesetraditional::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1607 of file translator_tw.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=""; break;
        case ClassDef::Struct: result+=""; break;
        case ClassDef::Union: result+=""; break;
        case ClassDef::Interface: result+=""; break;
        case ClassDef::Protocol: result+=""; break;
        case ClassDef::Category: result+=""; break;
        case ClassDef::Exception: result+=""; break;
        default: break;
      }
      if (isTemplate) result+=" Template";
      result+="";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorChinesetraditional::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1607 of file translator_tw.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=""; break;
        case ClassDef::Struct: result+=""; break;
        case ClassDef::Union: result+=""; break;
        case ClassDef::Interface: result+=""; break;
        case ClassDef::Protocol: result+=""; break;
        case ClassDef::Category: result+=""; break;
        case ClassDef::Exception: result+=""; break;
        default: break;
      }
      if (isTemplate) result+=" Template";
      result+="";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorChinesetraditional::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 507 of file translator_tw.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorChinesetraditional::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 507 of file translator_tw.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trConstantGroupReference() [1/2]
virtual QCString TranslatorChinesetraditional::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1946 of file translator_tw.h.
    {
      QCString result=namespaceName;
      result+="";
      return result;
    }
trConstantGroupReference() [2/2]
virtual QCString TranslatorChinesetraditional::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1946 of file translator_tw.h.
    {
      QCString result=namespaceName;
      result+="";
      return result;
    }
trConstantGroups() [1/2]
virtual QCString TranslatorChinesetraditional::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1942 of file translator_tw.h.
    { return ""; }
trConstantGroups() [2/2]
virtual QCString TranslatorChinesetraditional::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1942 of file translator_tw.h.
    { return ""; }
trConstructorDocumentation() [1/2]
virtual QCString TranslatorChinesetraditional::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 842 of file translator_tw.h.
    {
      return "";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorChinesetraditional::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 842 of file translator_tw.h.
    {
      return "";
    }
trCopyright() [1/2]
virtual QCString TranslatorChinesetraditional::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1829 of file translator_tw.h.
    { return ""; }
trCopyright() [2/2]
virtual QCString TranslatorChinesetraditional::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1829 of file translator_tw.h.
    { return ""; }
trDataTypes() [1/2]
virtual QCString TranslatorChinesetraditional::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1590 of file translator_tw.h.
    { return ""; }
trDataTypes() [2/2]
virtual QCString TranslatorChinesetraditional::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1590 of file translator_tw.h.
    { return ""; }
trDate() [1/2]
virtual QCString TranslatorChinesetraditional::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 545 of file translator_tw.h.
    { return ""; }
trDate() [2/2]
virtual QCString TranslatorChinesetraditional::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 545 of file translator_tw.h.
    { return ""; }
trDateTime() [1/2]
virtual QCString TranslatorChinesetraditional::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1784 of file translator_tw.h.
    {
      static const char *days[] = { "","","","","","","" };
      static const char *months[] = { "1","2","3","4","5","6","7","8","9","10","11","12" };
      QCString sdate;
      sdate.sprintf("%d%s%d %s",year,months[month-1],day,days[dayOfWeek-1]);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDateTime() [2/2]
virtual QCString TranslatorChinesetraditional::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1784 of file translator_tw.h.
    {
      static const char *days[] = { "","","","","","","" };
      static const char *months[] = { "1","2","3","4","5","6","7","8","9","10","11","12" };
      QCString sdate;
      sdate.sprintf("%d%s%d %s",year,months[month-1],day,days[dayOfWeek-1]);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDayOfWeek() [1/2]
virtual QCString TranslatorChinesetraditional::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1800 of file translator_tw.h.
    {
      static const char *days_short[] = { "", "", "", "", "", "", "" };
      static const char *days_full[] = { "", "", "", "", "", "", "" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      return text;
    }
trDayOfWeek() [2/2]
virtual QCString TranslatorChinesetraditional::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1800 of file translator_tw.h.
    {
      static const char *days_short[] = { "", "", "", "", "", "", "" };
      static const char *days_full[] = { "", "", "", "", "", "", "" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      return text;
    }
trDayPeriod() [1/2]
virtual QCString TranslatorChinesetraditional::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1814 of file translator_tw.h.
    {
      static const char *dayPeriod[] = { "", "" };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorChinesetraditional::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1814 of file translator_tw.h.
    {
      static const char *dayPeriod[] = { "", "" };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorChinesetraditional::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 809 of file translator_tw.h.
    {
      return " @1 @0 .";
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorChinesetraditional::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 809 of file translator_tw.h.
    {
      return " @1 @0 .";
    }
trDefinedIn() [1/2]
virtual QCString TranslatorChinesetraditional::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 176 of file translator_tw.h.
    { return ""; }
trDefinedIn() [2/2]
virtual QCString TranslatorChinesetraditional::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 176 of file translator_tw.h.
    { return ""; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorChinesetraditional::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 813 of file translator_tw.h.
    {
      return " @0 .";
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorChinesetraditional::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 813 of file translator_tw.h.
    {
      return " @0 .";
    }
trDefineDocumentation() [1/2]
virtual QCString TranslatorChinesetraditional::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 471 of file translator_tw.h.
    { return ""; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorChinesetraditional::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 471 of file translator_tw.h.
    { return ""; }
trDefines() [1/2]
virtual QCString TranslatorChinesetraditional::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 435 of file translator_tw.h.
    { return ""; }
trDefines() [2/2]
virtual QCString TranslatorChinesetraditional::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 435 of file translator_tw.h.
    { return ""; }
trDefineValue() [1/2]
virtual QCString TranslatorChinesetraditional::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1134 of file translator_tw.h.
    {
      return ":";
    }
trDefineValue() [2/2]
virtual QCString TranslatorChinesetraditional::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1134 of file translator_tw.h.
    {
      return ":";
    }
trDeprecated() [1/2]
virtual QCString TranslatorChinesetraditional::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 822 of file translator_tw.h.
    {
      return "";
    }
trDeprecated() [2/2]
virtual QCString TranslatorChinesetraditional::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 822 of file translator_tw.h.
    {
      return "";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorChinesetraditional::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1327 of file translator_tw.h.
    {
      return "(Deprecated) ";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorChinesetraditional::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1327 of file translator_tw.h.
    {
      return "(Deprecated) ";
    }
trDetailedDescription() [1/2]
virtual QCString TranslatorChinesetraditional::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 109 of file translator_tw.h.
    { return ""; }
trDetailedDescription() [2/2]
virtual QCString TranslatorChinesetraditional::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 109 of file translator_tw.h.
    { return ""; }
trDetailLevel() [1/2]
virtual QCString TranslatorChinesetraditional::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1841 of file translator_tw.h.
    { return ""; }
trDetailLevel() [2/2]
virtual QCString TranslatorChinesetraditional::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1841 of file translator_tw.h.
    { return ""; }
trDir() [1/2]
virtual QCString TranslatorChinesetraditional::trDir (bool , bool) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1494 of file translator_tw.h.
    {
      return QCString("");
    }
trDir() [2/2]
virtual QCString TranslatorChinesetraditional::trDir (bool , bool) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1494 of file translator_tw.h.
    {
      return QCString("");
    }
trDirDepGraph() [1/2]
virtual QCString TranslatorChinesetraditional::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1833 of file translator_tw.h.
    { return QCString(name)+""+":"; }
References setup::name.
trDirDepGraph() [2/2]
virtual QCString TranslatorChinesetraditional::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1833 of file translator_tw.h.
    { return QCString(name)+""+":"; }
References setup::name.
trDirDocumentation() [1/2]
virtual QCString TranslatorChinesetraditional::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1476 of file translator_tw.h.
    { return ""; }
trDirDocumentation() [2/2]
virtual QCString TranslatorChinesetraditional::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1476 of file translator_tw.h.
    { return ""; }
trDirectories() [1/2]
virtual QCString TranslatorChinesetraditional::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1482 of file translator_tw.h.
    { return ""; }
trDirectories() [2/2]
virtual QCString TranslatorChinesetraditional::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1482 of file translator_tw.h.
    { return ""; }
trDirIndex() [1/2]
virtual QCString TranslatorChinesetraditional::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1470 of file translator_tw.h.
    { return ""; }
trDirIndex() [2/2]
virtual QCString TranslatorChinesetraditional::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1470 of file translator_tw.h.
    { return ""; }
trDirReference() [1/2]
virtual QCString TranslatorChinesetraditional::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1488 of file translator_tw.h.
    { QCString result=dirName; result+=" "; return result; }
trDirReference() [2/2]
virtual QCString TranslatorChinesetraditional::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1488 of file translator_tw.h.
    { QCString result=dirName; result+=" "; return result; }
trDirRelation() [1/2]
virtual QCString TranslatorChinesetraditional::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1723 of file translator_tw.h.
    {
      return QCString(name)+" ";
    }
References setup::name.
trDirRelation() [2/2]
virtual QCString TranslatorChinesetraditional::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1723 of file translator_tw.h.
    {
      return QCString(name)+" ";
    }
References setup::name.
trDocumentation() [1/2]
virtual QCString TranslatorChinesetraditional::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 355 of file translator_tw.h.
    { return ""; }
trDocumentation() [2/2]
virtual QCString TranslatorChinesetraditional::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 355 of file translator_tw.h.
    { return ""; }
trEnumerations() [1/2]
virtual QCString TranslatorChinesetraditional::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 447 of file translator_tw.h.
    { return ""; }
trEnumerations() [2/2]
virtual QCString TranslatorChinesetraditional::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 447 of file translator_tw.h.
    { return ""; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorChinesetraditional::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 483 of file translator_tw.h.
    { return ""; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorChinesetraditional::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 483 of file translator_tw.h.
    { return ""; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorChinesetraditional::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 489 of file translator_tw.h.
    { return ""; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorChinesetraditional::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 489 of file translator_tw.h.
    { return ""; }
trEnumerationValues() [1/2]
virtual QCString TranslatorChinesetraditional::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 465 of file translator_tw.h.
    { return ""; }
trEnumerationValues() [2/2]
virtual QCString TranslatorChinesetraditional::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 465 of file translator_tw.h.
    { return ""; }
trEnumGeneratedFromFiles() [1/2]
virtual QCString TranslatorChinesetraditional::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1853 of file translator_tw.h.
    { QCString result = "";
      if (!single) result += "";
      result+=":";
      return result;
    }
trEnumGeneratedFromFiles() [2/2]
virtual QCString TranslatorChinesetraditional::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1853 of file translator_tw.h.
    { QCString result = "";
      if (!single) result += "";
      result+=":";
      return result;
    }
trEnumName() [1/2]
virtual QCString TranslatorChinesetraditional::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 168 of file translator_tw.h.
    { return ""; }
trEnumName() [2/2]
virtual QCString TranslatorChinesetraditional::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 168 of file translator_tw.h.
    { return ""; }
trEnumReference() [1/2]
virtual QCString TranslatorChinesetraditional::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1861 of file translator_tw.h.
    { return QCString(name)+" "; }
References setup::name.
trEnumReference() [2/2]
virtual QCString TranslatorChinesetraditional::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1861 of file translator_tw.h.
    { return QCString(name)+" "; }
References setup::name.
trEnumValue() [1/2]
virtual QCString TranslatorChinesetraditional::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 172 of file translator_tw.h.
    { return ""; }
trEnumValue() [2/2]
virtual QCString TranslatorChinesetraditional::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 172 of file translator_tw.h.
    { return ""; }
trEventDocumentation() [1/2]
virtual QCString TranslatorChinesetraditional::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1344 of file translator_tw.h.
    {
      return "Event ";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorChinesetraditional::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1344 of file translator_tw.h.
    {
      return "Event ";
    }
trEvents() [1/2]
virtual QCString TranslatorChinesetraditional::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1339 of file translator_tw.h.
    {
      return "Events";
    }
trEvents() [2/2]
virtual QCString TranslatorChinesetraditional::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1339 of file translator_tw.h.
    {
      return "Events";
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorChinesetraditional::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 425 of file translator_tw.h.
    { return ""; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorChinesetraditional::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 425 of file translator_tw.h.
    { return ""; }
trExamples() [1/2]
virtual QCString TranslatorChinesetraditional::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 239 of file translator_tw.h.
    { return ""; }
trExamples() [2/2]
virtual QCString TranslatorChinesetraditional::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 239 of file translator_tw.h.
    { return ""; }
trExamplesDescription() [1/2]
virtual QCString TranslatorChinesetraditional::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 340 of file translator_tw.h.
    { return ":"; }
trExamplesDescription() [2/2]
virtual QCString TranslatorChinesetraditional::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 340 of file translator_tw.h.
    { return ":"; }
trExceptions() [1/2]
virtual QCString TranslatorChinesetraditional::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 561 of file translator_tw.h.
    { return ""; }
trExceptions() [2/2]
virtual QCString TranslatorChinesetraditional::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 561 of file translator_tw.h.
    { return ""; }
trExtendsClass() [1/2]
virtual QCString TranslatorChinesetraditional::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1901 of file translator_tw.h.
    {
      return " @0 .";
    }
trExtendsClass() [2/2]
virtual QCString TranslatorChinesetraditional::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1901 of file translator_tw.h.
    {
      return " @0 .";
    }
trFile() [1/2]
virtual QCString TranslatorChinesetraditional::trFile (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1216 of file translator_tw.h.
    {
      return QCString("");
    }
trFile() [2/2]
virtual QCString TranslatorChinesetraditional::trFile (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1216 of file translator_tw.h.
    {
      return QCString("");
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorChinesetraditional::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 419 of file translator_tw.h.
    { return ""; }
trFileDocumentation() [2/2]
virtual QCString TranslatorChinesetraditional::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 419 of file translator_tw.h.
    { return ""; }
trFileIn() [1/2]
virtual QCString TranslatorChinesetraditional::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1760 of file translator_tw.h.
    {
      return ""+name;
    }
References setup::name.
trFileIn() [2/2]
virtual QCString TranslatorChinesetraditional::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1760 of file translator_tw.h.
    {
      return ""+name;
    }
References setup::name.
trFileIndex() [1/2]
virtual QCString TranslatorChinesetraditional::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 388 of file translator_tw.h.
    { return ""; }
trFileIndex() [2/2]
virtual QCString TranslatorChinesetraditional::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 388 of file translator_tw.h.
    { return ""; }
trFileList() [1/2]
virtual QCString TranslatorChinesetraditional::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 205 of file translator_tw.h.
    { return ""; }
trFileList() [2/2]
virtual QCString TranslatorChinesetraditional::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 205 of file translator_tw.h.
    { return ""; }
trFileListDescription() [1/2]
virtual QCString TranslatorChinesetraditional::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 252 of file translator_tw.h.
    {
      QCString result="";
      if (!extractAll) result+="";
      result+=":";
      return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorChinesetraditional::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 252 of file translator_tw.h.
    {
      QCString result="";
      if (!extractAll) result+="";
      result+=":";
      return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorChinesetraditional::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 222 of file translator_tw.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trFileMembers() [2/2]
virtual QCString TranslatorChinesetraditional::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 222 of file translator_tw.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
virtual QCString TranslatorChinesetraditional::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 318 of file translator_tw.h.
    {
      QCString result="";
      if (!extractAll) result+="";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="";
      }
      else
      {
        result+="";
      }
      result+="";
      if (extractAll)
        result+=":";
      else
        result+=":";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorChinesetraditional::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 318 of file translator_tw.h.
    {
      QCString result="";
      if (!extractAll) result+="";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="";
      }
      else
      {
        result+="";
      }
      result+="";
      if (extractAll)
        result+=":";
      else
        result+=":";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorChinesetraditional::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 628 of file translator_tw.h.
    {
      QCString result=fileName;
      result+=" ";
      return result;
    }
trFileReference() [2/2]
virtual QCString TranslatorChinesetraditional::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 628 of file translator_tw.h.
    {
      QCString result=fileName;
      result+=" ";
      return result;
    }
trFriends() [1/2]
virtual QCString TranslatorChinesetraditional::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 588 of file translator_tw.h.
    { return "(Friends)"; }
trFriends() [2/2]
virtual QCString TranslatorChinesetraditional::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 588 of file translator_tw.h.
    { return "(Friends)"; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorChinesetraditional::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 495 of file translator_tw.h.
    { return ""; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorChinesetraditional::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 495 of file translator_tw.h.
    { return ""; }
trFunctions() [1/2]
virtual QCString TranslatorChinesetraditional::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 453 of file translator_tw.h.
    { return ""; }
trFunctions() [2/2]
virtual QCString TranslatorChinesetraditional::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 453 of file translator_tw.h.
    { return ""; }
trGeneratedAt() [1/2]
virtual QCString TranslatorChinesetraditional::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 522 of file translator_tw.h.
    {
      QCString result=":"+date;
      if (!projName.isEmpty()) result+=", :"+projName;
      result+=", :";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorChinesetraditional::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 522 of file translator_tw.h.
    {
      QCString result=":"+date;
      if (!projName.isEmpty()) result+=", :"+projName;
      result+=", :";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorChinesetraditional::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 160 of file translator_tw.h.
    { QCString result="Doxygen";
      if (!s.isEmpty()) result+=" "+s;
      result+=" .";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorChinesetraditional::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 160 of file translator_tw.h.
    { QCString result="Doxygen";
      if (!s.isEmpty()) result+=" "+s;
      result+=" .";
      return result;
    }
References s.
trGeneratedBy() [1/2]
virtual QCString TranslatorChinesetraditional::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 565 of file translator_tw.h.
    { return ":"; }
trGeneratedBy() [2/2]
virtual QCString TranslatorChinesetraditional::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 565 of file translator_tw.h.
    { return ":"; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorChinesetraditional::trGeneratedFromFiles (ClassDef::CompoundType compType, bool) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 766 of file translator_tw.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="";
      switch(compType)
      {
        case ClassDef::Class: result+="(class)"; break;
        case ClassDef::Struct: result+="(structure)"; break;
        case ClassDef::Union: result+="(union)"; break;
        case ClassDef::Interface: result+="(interface)"; break;
        case ClassDef::Protocol: result+="(protocol)"; break;
        case ClassDef::Category: result+="(category)"; break;
        case ClassDef::Exception: result+="(exception)"; break;
        default: break;
      }
      result+=" ";
      result+=":";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorChinesetraditional::trGeneratedFromFiles (ClassDef::CompoundType compType, bool) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 766 of file translator_tw.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="";
      switch(compType)
      {
        case ClassDef::Class: result+="(class)"; break;
        case ClassDef::Struct: result+="(structure)"; break;
        case ClassDef::Union: result+="(union)"; break;
        case ClassDef::Interface: result+="(interface)"; break;
        case ClassDef::Protocol: result+="(protocol)"; break;
        case ClassDef::Category: result+="(category)"; break;
        case ClassDef::Exception: result+="(exception)"; break;
        default: break;
      }
      result+=" ";
      result+=":";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorChinesetraditional::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1674 of file translator_tw.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="";
      switch(compType)
      {
        case ClassDef::Class: result+=""; break;
        case ClassDef::Struct: result+=""; break;
        case ClassDef::Union: result+=""; break;
        case ClassDef::Interface: result+=""; break;
        case ClassDef::Protocol: result+=""; break;
        case ClassDef::Category: result+=""; break;
        case ClassDef::Exception: result+=""; break;
        default: break;
      }
      result+="";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorChinesetraditional::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1674 of file translator_tw.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="";
      switch(compType)
      {
        case ClassDef::Class: result+=""; break;
        case ClassDef::Struct: result+=""; break;
        case ClassDef::Union: result+=""; break;
        case ClassDef::Interface: result+=""; break;
        case ClassDef::Protocol: result+=""; break;
        case ClassDef::Category: result+=""; break;
        case ClassDef::Exception: result+=""; break;
        default: break;
      }
      result+="";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorChinesetraditional::trGlobal (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1261 of file translator_tw.h.
    {
      return QCString("");
    }
trGlobal() [2/2]
virtual QCString TranslatorChinesetraditional::trGlobal (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1261 of file translator_tw.h.
    {
      return QCString("");
    }
trGlobalNamespace() [1/2]
virtual QCString TranslatorChinesetraditional::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1735 of file translator_tw.h.
    {
      return "";
    }
trGlobalNamespace() [2/2]
virtual QCString TranslatorChinesetraditional::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1735 of file translator_tw.h.
    {
      return "";
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorChinesetraditional::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 852 of file translator_tw.h.
    {
      return ".";
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorChinesetraditional::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 852 of file translator_tw.h.
    {
      return ".";
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorChinesetraditional::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 885 of file translator_tw.h.
    {
      return "";
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorChinesetraditional::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 885 of file translator_tw.h.
    {
      return "";
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorChinesetraditional::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 847 of file translator_tw.h.
    {
      return ".";
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorChinesetraditional::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 847 of file translator_tw.h.
    {
      return ".";
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorChinesetraditional::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 889 of file translator_tw.h.
    {
      return "";
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorChinesetraditional::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 889 of file translator_tw.h.
    {
      return "";
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorChinesetraditional::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 881 of file translator_tw.h.
    {
      return "";
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorChinesetraditional::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 881 of file translator_tw.h.
    {
      return "";
    }
trGroup() [1/2]
virtual QCString TranslatorChinesetraditional::trGroup (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1234 of file translator_tw.h.
    {
      return QCString("");
    }
trGroup() [2/2]
virtual QCString TranslatorChinesetraditional::trGroup (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1234 of file translator_tw.h.
    {
      return QCString("");
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorChinesetraditional::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 367 of file translator_tw.h.
    { return ""; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorChinesetraditional::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 367 of file translator_tw.h.
    { return ""; }
trImplementedFromList() [1/2]
virtual QCString TranslatorChinesetraditional::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1295 of file translator_tw.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorChinesetraditional::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1295 of file translator_tw.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorChinesetraditional::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1303 of file translator_tw.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorChinesetraditional::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1303 of file translator_tw.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorChinesetraditional::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 981 of file translator_tw.h.
    {
      return "include "
             ":";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorChinesetraditional::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 981 of file translator_tw.h.
    {
      return "include "
             ":";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorChinesetraditional::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 837 of file translator_tw.h.
    {
      return ""+fName+":";
    }
trInclDepGraph() [2/2]
virtual QCString TranslatorChinesetraditional::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 837 of file translator_tw.h.
    {
      return ""+fName+":";
    }
trIncludesFileIn() [1/2]
virtual QCString TranslatorChinesetraditional::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1769 of file translator_tw.h.
    {
      return ""+name;
    }
References setup::name.
trIncludesFileIn() [2/2]
virtual QCString TranslatorChinesetraditional::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1769 of file translator_tw.h.
    {
      return ""+name;
    }
References setup::name.
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorChinesetraditional::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 154 of file translator_tw.h.
    { return ", "; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorChinesetraditional::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 154 of file translator_tw.h.
    { return ", "; }
trInheritedByList() [1/2]
virtual QCString TranslatorChinesetraditional::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 700 of file translator_tw.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorChinesetraditional::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 700 of file translator_tw.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom() [1/2]
virtual QCString TranslatorChinesetraditional::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1865 of file translator_tw.h.
    { return QCString(members)+" "+what; }
trInheritedFrom() [2/2]
virtual QCString TranslatorChinesetraditional::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1865 of file translator_tw.h.
    { return QCString(members)+" "+what; }
trInheritsList() [1/2]
virtual QCString TranslatorChinesetraditional::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 692 of file translator_tw.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorChinesetraditional::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 692 of file translator_tw.h.
    {
      return " "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorChinesetraditional::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 872 of file translator_tw.h.
    {
      return ":";
    }
trInitialValue() [2/2]
virtual QCString TranslatorChinesetraditional::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 872 of file translator_tw.h.
    {
      return ":";
    }
trInstanceMethods() [1/2]
virtual QCString TranslatorChinesetraditional::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1917 of file translator_tw.h.
    {
      return "";
    }
trInstanceMethods() [2/2]
virtual QCString TranslatorChinesetraditional::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1917 of file translator_tw.h.
    {
      return "";
    }
trInterfaces() [1/2]
virtual QCString TranslatorChinesetraditional::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1934 of file translator_tw.h.
    { return ""; }
trInterfaces() [2/2]
virtual QCString TranslatorChinesetraditional::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1934 of file translator_tw.h.
    { return ""; }
trInvariant() [1/2]
virtual QCString TranslatorChinesetraditional::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 867 of file translator_tw.h.
    {
      return "";
    }
trInvariant() [2/2]
virtual QCString TranslatorChinesetraditional::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 867 of file translator_tw.h.
    {
      return "";
    }
trISOLang() [1/2]
virtual QCString TranslatorChinesetraditional::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 89 of file translator_tw.h.
    {
      return "zh-Hant";
    }
trISOLang() [2/2]
virtual QCString TranslatorChinesetraditional::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 89 of file translator_tw.h.
    {
      return "zh-Hant";
    }
trLegend() [1/2]
virtual QCString TranslatorChinesetraditional::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1066 of file translator_tw.h.
    {
      return "";
    }
trLegend() [2/2]
virtual QCString TranslatorChinesetraditional::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1066 of file translator_tw.h.
    {
      return "";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorChinesetraditional::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 1003 of file translator_tw.h.
    {
      return
        "doxygen "
        ".<p>\n"
        ":\n"
        "\\code\n"
        "/*! */\n"
        "class Invisible { };\n\n"
        "/*! , */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* doxygen */\n"
        "class Undocumented { };\n\n"
        "/*! (Public) */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! */\n"
        "template<class T> class Templ { };\n\n"
        "/*! (Protected) */\n"
        "class ProtectedBase { };\n\n"
        "/*! (Private) */\n"
        "class PrivateBase { };\n\n"
        "/*! */\n"
        "class Used { };\n\n"
        "/*! (Super Class) */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        ":"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        ":\n"
        "</p>\n"
        "<ul>\n"
        "<li>%A "
        ".\n"
        "<li>%A .</li>\n"
        "<li>%A .</li>\n"
        "<li>%A "
        ". %A "
        ".</li>\n"
        "</ul>\n"
        "<p>\n"
        ":\n"
        "</p>\n"
        "<ul>\n"
        "<li>%A "
        ".\n"
        "<li>%A </li>\n"
        "<li>%A </li>\n"
        "<li>%A ."
        "</li>\n"
        "<li>%A "
        "</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorChinesetraditional::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 1003 of file translator_tw.h.
    {
      return
        "doxygen "
        ".<p>\n"
        ":\n"
        "\\code\n"
        "/*! */\n"
        "class Invisible { };\n\n"
        "/*! , */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* doxygen */\n"
        "class Undocumented { };\n\n"
        "/*! (Public) */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! */\n"
        "template<class T> class Templ { };\n\n"
        "/*! (Protected) */\n"
        "class ProtectedBase { };\n\n"
        "/*! (Private) */\n"
        "class PrivateBase { };\n\n"
        "/*! */\n"
        "class Used { };\n\n"
        "/*! (Super Class) */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        ":"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        ":\n"
        "</p>\n"
        "<ul>\n"
        "<li>%A "
        ".\n"
        "<li>%A .</li>\n"
        "<li>%A .</li>\n"
        "<li>%A "
        ". %A "
        ".</li>\n"
        "</ul>\n"
        "<p>\n"
        ":\n"
        "</p>\n"
        "<ul>\n"
        "<li>%A "
        ".\n"
        "<li>%A </li>\n"
        "<li>%A </li>\n"
        "<li>%A ."
        "</li>\n"
        "<li>%A "
        "</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorChinesetraditional::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 996 of file translator_tw.h.
    {
      return "";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorChinesetraditional::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 996 of file translator_tw.h.
    {
      return "";
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorChinesetraditional::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 142 of file translator_tw.h.
    { return ""; }
trListOfAllMembers() [2/2]
virtual QCString TranslatorChinesetraditional::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 142 of file translator_tw.h.
    { return ""; }
trLoading() [1/2]
virtual QCString TranslatorChinesetraditional::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1729 of file translator_tw.h.
    {
      return "...";
    }
trLoading() [2/2]
virtual QCString TranslatorChinesetraditional::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1729 of file translator_tw.h.
    {
      return "...";
    }
trMainPage() [1/2]
virtual QCString TranslatorChinesetraditional::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 796 of file translator_tw.h.
    { return ""; }
trMainPage() [2/2]
virtual QCString TranslatorChinesetraditional::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 796 of file translator_tw.h.
    { return ""; }
trMember() [1/2]
virtual QCString TranslatorChinesetraditional::trMember (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1252 of file translator_tw.h.
    {
      return QCString("");
    }
trMember() [2/2]
virtual QCString TranslatorChinesetraditional::trMember (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1252 of file translator_tw.h.
    {
      return QCString("");
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorChinesetraditional::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 125 of file translator_tw.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorChinesetraditional::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 125 of file translator_tw.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorChinesetraditional::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 117 of file translator_tw.h.
    { return ""; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorChinesetraditional::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 117 of file translator_tw.h.
    { return ""; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorChinesetraditional::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 121 of file translator_tw.h.
    { return ""; }
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorChinesetraditional::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 121 of file translator_tw.h.
    { return ""; }
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorChinesetraditional::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1527 of file translator_tw.h.
    { return "/ "; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorChinesetraditional::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1527 of file translator_tw.h.
    { return "/ "; }
trMemberList() [1/2]
virtual QCString TranslatorChinesetraditional::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 146 of file translator_tw.h.
    { return ""; }
trMemberList() [2/2]
virtual QCString TranslatorChinesetraditional::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 146 of file translator_tw.h.
    { return ""; }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorChinesetraditional::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 113 of file translator_tw.h.
    { return ""; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorChinesetraditional::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 113 of file translator_tw.h.
    { return ""; }
trMethodDocumentation() [1/2]
virtual QCString TranslatorChinesetraditional::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1924 of file translator_tw.h.
    {
      return "";
    }
trMethodDocumentation() [2/2]
virtual QCString TranslatorChinesetraditional::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1924 of file translator_tw.h.
    {
      return "";
    }
trModule() [1/2]
virtual QCString TranslatorChinesetraditional::trModule (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1666 of file translator_tw.h.
    {
      QCString result("");
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorChinesetraditional::trModule (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1666 of file translator_tw.h.
    {
      QCString result("");
      return result;
    }
trModuleDocumentation() [1/2]
virtual QCString TranslatorChinesetraditional::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 394 of file translator_tw.h.
    { return ""; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorChinesetraditional::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 394 of file translator_tw.h.
    { return ""; }
trModuleIndex() [1/2]
virtual QCString TranslatorChinesetraditional::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 361 of file translator_tw.h.
    { return ""; }
trModuleIndex() [2/2]
virtual QCString TranslatorChinesetraditional::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 361 of file translator_tw.h.
    { return ""; }
trModuleReference() [1/2]
virtual QCString TranslatorChinesetraditional::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1628 of file translator_tw.h.
    {
      QCString result=namespaceName;
      result+="";
      return result;
    }
trModuleReference() [2/2]
virtual QCString TranslatorChinesetraditional::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1628 of file translator_tw.h.
    {
      QCString result=namespaceName;
      result+="";
      return result;
    }
trModules() [1/2]
virtual QCString TranslatorChinesetraditional::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 184 of file translator_tw.h.
    { return ""; }
trModules() [2/2]
virtual QCString TranslatorChinesetraditional::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 184 of file translator_tw.h.
    { return ""; }
trModulesDescription() [1/2]
virtual QCString TranslatorChinesetraditional::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 348 of file translator_tw.h.
    { return ":"; }
trModulesDescription() [2/2]
virtual QCString TranslatorChinesetraditional::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 348 of file translator_tw.h.
    { return ":"; }
trModulesIndex() [1/2]
virtual QCString TranslatorChinesetraditional::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1659 of file translator_tw.h.
    { return ""; }
trModulesIndex() [2/2]
virtual QCString TranslatorChinesetraditional::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1659 of file translator_tw.h.
    { return ""; }
trModulesList() [1/2]
virtual QCString TranslatorChinesetraditional::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1594 of file translator_tw.h.
    { return ""; }
trModulesList() [2/2]
virtual QCString TranslatorChinesetraditional::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1594 of file translator_tw.h.
    { return ""; }
trModulesListDescription() [1/2]
virtual QCString TranslatorChinesetraditional::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1598 of file translator_tw.h.
    {
      QCString result="";
      if (!extractAll) result+="";
      result+=":";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorChinesetraditional::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1598 of file translator_tw.h.
    {
      QCString result="";
      if (!extractAll) result+="";
      result+=":";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorChinesetraditional::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1640 of file translator_tw.h.
    {
      QCString result="";
      if (!extractAll) result+="";
      result+="";
      if (extractAll)
      {
        result+=":";
      }
      else
      {
        result+=":";
      }
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorChinesetraditional::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1640 of file translator_tw.h.
    {
      QCString result="";
      if (!extractAll) result+="";
      result+="";
      if (extractAll)
      {
        result+=":";
      }
      else
      {
        result+=":";
      }
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorChinesetraditional::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1636 of file translator_tw.h.
    { return ""; }
trModulesMembers() [2/2]
virtual QCString TranslatorChinesetraditional::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1636 of file translator_tw.h.
    { return ""; }
trMonth() [1/2]
virtual QCString TranslatorChinesetraditional::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1807 of file translator_tw.h.
    {
      static const char *months_short[] = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" };
      static const char *months_full[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      return text;
    }
trMonth() [2/2]
virtual QCString TranslatorChinesetraditional::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1807 of file translator_tw.h.
    {
      static const char *months_short[] = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" };
      static const char *months_full[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      return text;
    }
trMore() [1/2]
virtual QCString TranslatorChinesetraditional::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 138 of file translator_tw.h.
    { return "..."; }
trMore() [2/2]
virtual QCString TranslatorChinesetraditional::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 138 of file translator_tw.h.
    { return "..."; }
trNamespace() [1/2]
virtual QCString TranslatorChinesetraditional::trNamespace (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1225 of file translator_tw.h.
    {
      return QCString("");
    }
trNamespace() [2/2]
virtual QCString TranslatorChinesetraditional::trNamespace (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1225 of file translator_tw.h.
    {
      return QCString("");
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorChinesetraditional::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 746 of file translator_tw.h.
    { return "(Namespace)"; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorChinesetraditional::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 746 of file translator_tw.h.
    { return "(Namespace)"; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorChinesetraditional::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 740 of file translator_tw.h.
    { return "(Namespace)"; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorChinesetraditional::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 740 of file translator_tw.h.
    { return "(Namespace)"; }
trNamespaceList() [1/2]
virtual QCString TranslatorChinesetraditional::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 573 of file translator_tw.h.
    { return "(name space)"; }
trNamespaceList() [2/2]
virtual QCString TranslatorChinesetraditional::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 573 of file translator_tw.h.
    { return "(name space)"; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorChinesetraditional::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 577 of file translator_tw.h.
    {
      QCString result="";
      if (!extractAll) result+="";
      result+="(namespaces):";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorChinesetraditional::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 577 of file translator_tw.h.
    {
      QCString result="";
      if (!extractAll) result+="";
      result+="(namespaces):";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorChinesetraditional::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 726 of file translator_tw.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+="(namespace) ";
      if (extractAll)
        result+=":";
      else
        result+=":";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorChinesetraditional::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 726 of file translator_tw.h.
    {
      QCString result=" ";
      if (!extractAll) result+=" ";
      result+="(namespace) ";
      if (extractAll)
        result+=":";
      else
        result+=":";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorChinesetraditional::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 722 of file translator_tw.h.
    { return "(Namespace)"; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorChinesetraditional::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 722 of file translator_tw.h.
    { return "(Namespace)"; }
trNamespaceReference() [1/2]
virtual QCString TranslatorChinesetraditional::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 636 of file translator_tw.h.
    {
      QCString result=namespaceName;
      result+=" (Namespace)";
      return result;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorChinesetraditional::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 636 of file translator_tw.h.
    {
      QCString result=namespaceName;
      result+=" (Namespace)";
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorChinesetraditional::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 756 of file translator_tw.h.
    { return "(Namespaces)"; }
trNamespaces() [2/2]
virtual QCString TranslatorChinesetraditional::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 756 of file translator_tw.h.
    { return "(Namespaces)"; }
trNoMatches() [1/2]
virtual QCString TranslatorChinesetraditional::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1747 of file translator_tw.h.
    {
      return "";
    }
trNoMatches() [2/2]
virtual QCString TranslatorChinesetraditional::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1747 of file translator_tw.h.
    {
      return "";
    }
trNote() [1/2]
virtual QCString TranslatorChinesetraditional::trNote () [inline], [virtual]
Implements Translator.
Definition at line 902 of file translator_tw.h.
    {
      return "";
    }
trNote() [2/2]
virtual QCString TranslatorChinesetraditional::trNote () [inline], [virtual]
Implements Translator.
Definition at line 902 of file translator_tw.h.
    {
      return "";
    }
trOverloadText() [1/2]
virtual QCString TranslatorChinesetraditional::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1506 of file translator_tw.h.
    {
       return " overload "
              ".";
    }
trOverloadText() [2/2]
virtual QCString TranslatorChinesetraditional::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1506 of file translator_tw.h.
    {
       return " overload "
              ".";
    }
trPackage() [1/2]
virtual QCString TranslatorChinesetraditional::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1118 of file translator_tw.h.
    {
      return "Package "+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorChinesetraditional::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1118 of file translator_tw.h.
    {
      return "Package "+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorChinesetraditional::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1380 of file translator_tw.h.
    {
      return "Package ";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorChinesetraditional::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1380 of file translator_tw.h.
    {
      return "Package ";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorChinesetraditional::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1362 of file translator_tw.h.
    {
      return "Package ";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorChinesetraditional::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1362 of file translator_tw.h.
    {
      return "Package ";
    }
trPackageListDescription() [1/2]
virtual QCString TranslatorChinesetraditional::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1123 of file translator_tw.h.
    {
      return "Package():";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorChinesetraditional::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1123 of file translator_tw.h.
    {
      return "Package():";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorChinesetraditional::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1366 of file translator_tw.h.
    {
      return "Package ";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorChinesetraditional::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1366 of file translator_tw.h.
    {
      return "Package ";
    }
trPackages() [1/2]
virtual QCString TranslatorChinesetraditional::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1128 of file translator_tw.h.
    {
      return "Packages";
    }
trPackages() [2/2]
virtual QCString TranslatorChinesetraditional::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1128 of file translator_tw.h.
    {
      return "Packages";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorChinesetraditional::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1355 of file translator_tw.h.
    {
      return "Package ";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorChinesetraditional::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1355 of file translator_tw.h.
    {
      return "Package ";
    }
trPage() [1/2]
virtual QCString TranslatorChinesetraditional::trPage (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1243 of file translator_tw.h.
    {
      return QCString("");
    }
trPage() [2/2]
virtual QCString TranslatorChinesetraditional::trPage (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1243 of file translator_tw.h.
    {
      return QCString("");
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorChinesetraditional::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 802 of file translator_tw.h.
    { return "p."; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorChinesetraditional::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 802 of file translator_tw.h.
    { return "p."; }
trPageIndex() [1/2]
virtual QCString TranslatorChinesetraditional::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 893 of file translator_tw.h.
    {
      return "";
    }
trPageIndex() [2/2]
virtual QCString TranslatorChinesetraditional::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 893 of file translator_tw.h.
    {
      return "";
    }
trPanelSynchronisationTooltip() [1/2]
virtual QCString TranslatorChinesetraditional::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1882 of file translator_tw.h.
    {
      QCString opt = enable ? "" : "";
      return " "+opt+" ";
    }
trPanelSynchronisationTooltip() [2/2]
virtual QCString TranslatorChinesetraditional::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1882 of file translator_tw.h.
    {
      QCString opt = enable ? "" : "";
      return " "+opt+" ";
    }
trParameters() [1/2]
virtual QCString TranslatorChinesetraditional::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 557 of file translator_tw.h.
    { return ""; }
trParameters() [2/2]
virtual QCString TranslatorChinesetraditional::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 557 of file translator_tw.h.
    { return ""; }
trPostcondition() [1/2]
virtual QCString TranslatorChinesetraditional::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 862 of file translator_tw.h.
    {
      return "";
    }
trPostcondition() [2/2]
virtual QCString TranslatorChinesetraditional::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 862 of file translator_tw.h.
    {
      return "";
    }
trPrecondition() [1/2]
virtual QCString TranslatorChinesetraditional::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 857 of file translator_tw.h.
    {
      return "";
    }
trPrecondition() [2/2]
virtual QCString TranslatorChinesetraditional::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 857 of file translator_tw.h.
    {
      return "";
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorChinesetraditional::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 941 of file translator_tw.h.
    {
      return "";
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorChinesetraditional::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 941 of file translator_tw.h.
    {
      return "";
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorChinesetraditional::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 657 of file translator_tw.h.
    { return "(Private Methods)"; }
trPrivateMembers() [2/2]
virtual QCString TranslatorChinesetraditional::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 657 of file translator_tw.h.
    { return "(Private Methods)"; }
trPrivateSlots() [1/2]
virtual QCString TranslatorChinesetraditional::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 659 of file translator_tw.h.
    { return "(Private Slots)"; }
trPrivateSlots() [2/2]
virtual QCString TranslatorChinesetraditional::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 659 of file translator_tw.h.
    { return "(Private Slots)"; }
trPrivateTypes() [1/2]
virtual QCString TranslatorChinesetraditional::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 937 of file translator_tw.h.
    {
      return "";
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorChinesetraditional::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 937 of file translator_tw.h.
    {
      return "";
    }
trProperties() [1/2]
virtual QCString TranslatorChinesetraditional::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1091 of file translator_tw.h.
    {
      return "(properties)";
    }
trProperties() [2/2]
virtual QCString TranslatorChinesetraditional::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1091 of file translator_tw.h.
    {
      return "(properties)";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorChinesetraditional::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1096 of file translator_tw.h.
    {
      return "(property)";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorChinesetraditional::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1096 of file translator_tw.h.
    {
      return "(property)";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorChinesetraditional::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 929 of file translator_tw.h.
    {
      return "";
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorChinesetraditional::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 929 of file translator_tw.h.
    {
      return "";
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorChinesetraditional::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 651 of file translator_tw.h.
    { return "(Protected Methods)"; }
trProtectedMembers() [2/2]
virtual QCString TranslatorChinesetraditional::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 651 of file translator_tw.h.
    { return "(Protected Methods)"; }
trProtectedSlots() [1/2]
virtual QCString TranslatorChinesetraditional::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 653 of file translator_tw.h.
    { return "(Protected Slots)"; }
trProtectedSlots() [2/2]
virtual QCString TranslatorChinesetraditional::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 653 of file translator_tw.h.
    { return "(Protected Slots)"; }
trProtectedTypes() [1/2]
virtual QCString TranslatorChinesetraditional::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 925 of file translator_tw.h.
    {
      return "";
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorChinesetraditional::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 925 of file translator_tw.h.
    {
      return "";
    }
trProvidedByCategory() [1/2]
virtual QCString TranslatorChinesetraditional::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1892 of file translator_tw.h.
    {
      return " @0 .";
    }
trProvidedByCategory() [2/2]
virtual QCString TranslatorChinesetraditional::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1892 of file translator_tw.h.
    {
      return " @0 .";
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorChinesetraditional::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 910 of file translator_tw.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorChinesetraditional::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 910 of file translator_tw.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorChinesetraditional::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 643 of file translator_tw.h.
    { return "(Public Methods)"; }
trPublicMembers() [2/2]
virtual QCString TranslatorChinesetraditional::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 643 of file translator_tw.h.
    { return "(Public Methods)"; }
trPublicSlots() [1/2]
virtual QCString TranslatorChinesetraditional::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 645 of file translator_tw.h.
    { return "(Public Slots)"; }
trPublicSlots() [2/2]
virtual QCString TranslatorChinesetraditional::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 645 of file translator_tw.h.
    { return "(Public Slots)"; }
trPublicTypes() [1/2]
virtual QCString TranslatorChinesetraditional::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 906 of file translator_tw.h.
    {
      return "";
    }
trPublicTypes() [2/2]
virtual QCString TranslatorChinesetraditional::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 906 of file translator_tw.h.
    {
      return "";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorChinesetraditional::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 969 of file translator_tw.h.
    {
      return "";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorChinesetraditional::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 969 of file translator_tw.h.
    {
      return "";
    }
trReferenceManual() [1/2]
virtual QCString TranslatorChinesetraditional::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 429 of file translator_tw.h.
    { return ""; }
trReferenceManual() [2/2]
virtual QCString TranslatorChinesetraditional::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 429 of file translator_tw.h.
    { return ""; }
trReferences() [1/2]
virtual QCString TranslatorChinesetraditional::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1283 of file translator_tw.h.
    {
      return "";
    }
trReferences() [2/2]
virtual QCString TranslatorChinesetraditional::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1283 of file translator_tw.h.
    {
      return "";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorChinesetraditional::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 708 of file translator_tw.h.
    {
      return ""+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorChinesetraditional::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 708 of file translator_tw.h.
    {
      return ""+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorChinesetraditional::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 716 of file translator_tw.h.
    {
      return ""+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorChinesetraditional::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 716 of file translator_tw.h.
    {
      return ""+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorChinesetraditional::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 598 of file translator_tw.h.
    { return ""; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorChinesetraditional::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 598 of file translator_tw.h.
    { return ""; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorChinesetraditional::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 101 of file translator_tw.h.
    { return ""; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorChinesetraditional::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 101 of file translator_tw.h.
    { return ""; }
trRelatedPages() [1/2]
virtual QCString TranslatorChinesetraditional::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 235 of file translator_tw.h.
    { return ""; }
trRelatedPages() [2/2]
virtual QCString TranslatorChinesetraditional::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 235 of file translator_tw.h.
    { return ""; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorChinesetraditional::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 344 of file translator_tw.h.
    { return ":"; }
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorChinesetraditional::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 344 of file translator_tw.h.
    { return ":"; }
trRelatedSubscript() [1/2]
virtual QCString TranslatorChinesetraditional::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 105 of file translator_tw.h.
    { return "()"; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorChinesetraditional::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 105 of file translator_tw.h.
    { return "()"; }
trRemarks() [1/2]
virtual QCString TranslatorChinesetraditional::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 973 of file translator_tw.h.
    {
      return "";
    }
trRemarks() [2/2]
virtual QCString TranslatorChinesetraditional::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 973 of file translator_tw.h.
    {
      return "";
    }
trReturns() [1/2]
virtual QCString TranslatorChinesetraditional::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 549 of file translator_tw.h.
    { return ""; }
trReturns() [2/2]
virtual QCString TranslatorChinesetraditional::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 549 of file translator_tw.h.
    { return ""; }
trReturnValues() [1/2]
virtual QCString TranslatorChinesetraditional::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 791 of file translator_tw.h.
    { return ""; }
trReturnValues() [2/2]
virtual QCString TranslatorChinesetraditional::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 791 of file translator_tw.h.
    { return ""; }
trRTFansicp() [1/2]
virtual QCString TranslatorChinesetraditional::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1183 of file translator_tw.h.
    {
      return "950";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorChinesetraditional::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1183 of file translator_tw.h.
    {
      return "950";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorChinesetraditional::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1192 of file translator_tw.h.
    {
      return "136";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorChinesetraditional::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1192 of file translator_tw.h.
    {
      return "136";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorChinesetraditional::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1198 of file translator_tw.h.
    {
      return "";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorChinesetraditional::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1198 of file translator_tw.h.
    {
      return "";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorChinesetraditional::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1315 of file translator_tw.h.
    {
      return "";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorChinesetraditional::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1315 of file translator_tw.h.
    {
      return "";
    }
trSearch() [1/2]
virtual QCString TranslatorChinesetraditional::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 243 of file translator_tw.h.
    { return ""; }
trSearch() [2/2]
virtual QCString TranslatorChinesetraditional::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 243 of file translator_tw.h.
    { return ""; }
trSearching() [1/2]
virtual QCString TranslatorChinesetraditional::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1741 of file translator_tw.h.
    {
      return "...";
    }
trSearching() [2/2]
virtual QCString TranslatorChinesetraditional::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1741 of file translator_tw.h.
    {
      return "...";
    }
trSearchMatches() [1/2]
virtual QCString TranslatorChinesetraditional::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1447 of file translator_tw.h.
    {
      return ":";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorChinesetraditional::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1447 of file translator_tw.h.
    {
      return ":";
    }
trSearchResults() [1/2]
virtual QCString TranslatorChinesetraditional::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1428 of file translator_tw.h.
    {
      if (numDocuments==0)
      {
        return ".";
      }
      else if (numDocuments==1)
      {
        return " <b>1</b> .";
      }
      else
      {
        return " <b>$num</b> . "
               ".";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorChinesetraditional::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1428 of file translator_tw.h.
    {
      if (numDocuments==0)
      {
        return ".";
      }
      else if (numDocuments==1)
      {
        return " <b>1</b> .";
      }
      else
      {
        return " <b>$num</b> . "
               ".";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorChinesetraditional::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1416 of file translator_tw.h.
    {
      return "";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorChinesetraditional::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1416 of file translator_tw.h.
    {
      return "";
    }
trSeeAlso() [1/2]
virtual QCString TranslatorChinesetraditional::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 553 of file translator_tw.h.
    { return ""; }
trSeeAlso() [2/2]
virtual QCString TranslatorChinesetraditional::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 553 of file translator_tw.h.
    { return ""; }
trServiceGeneratedFromFiles() [1/2]
virtual QCString TranslatorChinesetraditional::trServiceGeneratedFromFiles (bool) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 1967 of file translator_tw.h.
    {
      // single is true implies a single file
      QCString result=""
                                "";
      result+=":";
      return result;
    }
trServiceGeneratedFromFiles() [2/2]
virtual QCString TranslatorChinesetraditional::trServiceGeneratedFromFiles (bool) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 1967 of file translator_tw.h.
    {
      // single is true implies a single file
      QCString result=""
                                "";
      result+=":";
      return result;
    }
trServiceReference() [1/2]
virtual QCString TranslatorChinesetraditional::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 1953 of file translator_tw.h.
    {
      QCString result=sName;
      result+="";
      return result;
    }
trServiceReference() [2/2]
virtual QCString TranslatorChinesetraditional::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 1953 of file translator_tw.h.
    {
      QCString result=sName;
      result+="";
      return result;
    }
trServices() [1/2]
virtual QCString TranslatorChinesetraditional::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1938 of file translator_tw.h.
    { return ""; }
trServices() [2/2]
virtual QCString TranslatorChinesetraditional::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1938 of file translator_tw.h.
    { return ""; }
trSignals() [1/2]
virtual QCString TranslatorChinesetraditional::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 647 of file translator_tw.h.
    { return "(Signals)"; }
trSignals() [2/2]
virtual QCString TranslatorChinesetraditional::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 647 of file translator_tw.h.
    { return "(Signals)"; }
trSince() [1/2]
virtual QCString TranslatorChinesetraditional::trSince () [inline], [virtual]
Implements Translator.
Definition at line 986 of file translator_tw.h.
    {
      return "";
    }
trSince() [2/2]
virtual QCString TranslatorChinesetraditional::trSince () [inline], [virtual]
Implements Translator.
Definition at line 986 of file translator_tw.h.
    {
      return "";
    }
trSingletonGeneratedFromFiles() [1/2]
virtual QCString TranslatorChinesetraditional::trSingletonGeneratedFromFiles (bool) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 1976 of file translator_tw.h.
    {
      // single is true implies a single file
      QCString result="singleton"
                                "";
      result+=":";
      return result;
    }
trSingletonGeneratedFromFiles() [2/2]
virtual QCString TranslatorChinesetraditional::trSingletonGeneratedFromFiles (bool) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 1976 of file translator_tw.h.
    {
      // single is true implies a single file
      QCString result="singleton"
                                "";
      result+=":";
      return result;
    }
trSingletonReference() [1/2]
virtual QCString TranslatorChinesetraditional::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 1960 of file translator_tw.h.
    {
      QCString result=sName;
      result+="Singleton";
      return result;
    }
trSingletonReference() [2/2]
virtual QCString TranslatorChinesetraditional::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 1960 of file translator_tw.h.
    {
      QCString result=sName;
      result+="Singleton";
      return result;
    }
trSourceFile() [1/2]
virtual QCString TranslatorChinesetraditional::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1458 of file translator_tw.h.
    {
      return filename + " ";
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorChinesetraditional::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1458 of file translator_tw.h.
    {
      return filename + " ";
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorChinesetraditional::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1387 of file translator_tw.h.
    {
      return " Package ";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorChinesetraditional::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1387 of file translator_tw.h.
    {
      return " Package ";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorChinesetraditional::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1373 of file translator_tw.h.
    {
      return " Package ";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorChinesetraditional::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1373 of file translator_tw.h.
    {
      return " Package ";
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorChinesetraditional::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 945 of file translator_tw.h.
    {
      return "";
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorChinesetraditional::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 945 of file translator_tw.h.
    {
      return "";
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorChinesetraditional::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 661 of file translator_tw.h.
    { return "(Static Private Methods)"; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorChinesetraditional::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 661 of file translator_tw.h.
    { return "(Static Private Methods)"; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorChinesetraditional::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 933 of file translator_tw.h.
    {
      return "";
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorChinesetraditional::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 933 of file translator_tw.h.
    {
      return "";
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorChinesetraditional::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 655 of file translator_tw.h.
    { return "(Static Protected Methods)"; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorChinesetraditional::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 655 of file translator_tw.h.
    { return "(Static Protected Methods)"; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorChinesetraditional::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 921 of file translator_tw.h.
    {
      return "";
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorChinesetraditional::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 921 of file translator_tw.h.
    {
      return "";
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorChinesetraditional::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 649 of file translator_tw.h.
    { return "(Static Public Methods)"; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorChinesetraditional::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 649 of file translator_tw.h.
    { return "(Static Public Methods)"; }
trSubprogram() [1/2]
virtual QCString TranslatorChinesetraditional::trSubprogram (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1706 of file translator_tw.h.
    {
      QCString result("");
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorChinesetraditional::trSubprogram (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1706 of file translator_tw.h.
    {
      QCString result("");
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorChinesetraditional::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1584 of file translator_tw.h.
    { return "/ "; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorChinesetraditional::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1584 of file translator_tw.h.
    { return "/ "; }
trSubprograms() [1/2]
virtual QCString TranslatorChinesetraditional::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1578 of file translator_tw.h.
    { return "/"; }
trSubprograms() [2/2]
virtual QCString TranslatorChinesetraditional::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1578 of file translator_tw.h.
    { return "/"; }
trTemplateParameters() [1/2]
virtual QCString TranslatorChinesetraditional::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1845 of file translator_tw.h.
    { return ""; }
trTemplateParameters() [2/2]
virtual QCString TranslatorChinesetraditional::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1845 of file translator_tw.h.
    { return ""; }
trTest() [1/2]
virtual QCString TranslatorChinesetraditional::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1076 of file translator_tw.h.
    {
      return "";
    }
trTest() [2/2]
virtual QCString TranslatorChinesetraditional::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1076 of file translator_tw.h.
    {
      return "";
    }
trTestList() [1/2]
virtual QCString TranslatorChinesetraditional::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1081 of file translator_tw.h.
    {
      return "";
    }
trTestList() [2/2]
virtual QCString TranslatorChinesetraditional::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1081 of file translator_tw.h.
    {
      return "";
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorChinesetraditional::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 150 of file translator_tw.h.
    { return ""; }
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorChinesetraditional::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 150 of file translator_tw.h.
    { return ""; }
trTodo() [1/2]
virtual QCString TranslatorChinesetraditional::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 955 of file translator_tw.h.
    {
      return "";
    }
trTodo() [2/2]
virtual QCString TranslatorChinesetraditional::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 955 of file translator_tw.h.
    {
      return "";
    }
trTodoList() [1/2]
virtual QCString TranslatorChinesetraditional::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 960 of file translator_tw.h.
    {
      return "";
    }
trTodoList() [2/2]
virtual QCString TranslatorChinesetraditional::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 960 of file translator_tw.h.
    {
      return "";
    }
trType() [1/2]
virtual QCString TranslatorChinesetraditional::trType (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1697 of file translator_tw.h.
    {
      QCString result("");
      return result;
    }
trType() [2/2]
virtual QCString TranslatorChinesetraditional::trType (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1697 of file translator_tw.h.
    {
      QCString result("");
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorChinesetraditional::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1713 of file translator_tw.h.
    {
      return "";
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorChinesetraditional::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1713 of file translator_tw.h.
    {
      return "";
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorChinesetraditional::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 477 of file translator_tw.h.
    { return ""; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorChinesetraditional::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 477 of file translator_tw.h.
    { return ""; }
trTypedefs() [1/2]
virtual QCString TranslatorChinesetraditional::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 441 of file translator_tw.h.
    { return ""; }
trTypedefs() [2/2]
virtual QCString TranslatorChinesetraditional::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 441 of file translator_tw.h.
    { return ""; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorChinesetraditional::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1572 of file translator_tw.h.
    { return ""; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorChinesetraditional::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1572 of file translator_tw.h.
    { return ""; }
trVariableDocumentation() [1/2]
virtual QCString TranslatorChinesetraditional::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 501 of file translator_tw.h.
    { return ""; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorChinesetraditional::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 501 of file translator_tw.h.
    { return ""; }
trVariables() [1/2]
virtual QCString TranslatorChinesetraditional::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 459 of file translator_tw.h.
    { return ""; }
trVariables() [2/2]
virtual QCString TranslatorChinesetraditional::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 459 of file translator_tw.h.
    { return ""; }
trVersion() [1/2]
virtual QCString TranslatorChinesetraditional::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 541 of file translator_tw.h.
    { return ""; }
trVersion() [2/2]
virtual QCString TranslatorChinesetraditional::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 541 of file translator_tw.h.
    { return ""; }
trWarning() [1/2]
virtual QCString TranslatorChinesetraditional::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 537 of file translator_tw.h.
    { return ""; }
trWarning() [2/2]
virtual QCString TranslatorChinesetraditional::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 537 of file translator_tw.h.
    { return ""; }
trWriteList() [1/2]
virtual QCString TranslatorChinesetraditional::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 667 of file translator_tw.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=", ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorChinesetraditional::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 667 of file translator_tw.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=", ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_tw.h
doxygen/src/translator_tw.h