Trace Class Reference
Public Member Functions
Trace (const QCString &func)
Trace (const QCString &func, const QCString &data)
~Trace ()
void trace (const char *fmt,...)
void setResult (bool b)
void setResult (ExplicitPageResult ep)
void setResult (int i)
void setResult (const char *s)
void setResult (const QCString &s)
Trace (const QCString &func)
Trace (const QCString &func, const QCString &data)
~Trace ()
void trace (const char *fmt,...)
void setResult (bool b)
void setResult (ExplicitPageResult ep)
void setResult (int i)
void setResult (const char *s)
void setResult (const QCString &s)
Private Member Functions
void indent ()
void indent ()
Private Attributes
QCString m_func
bool m_resultSet = false
QCString m_resultValue
Static Private Attributes
static int s_indent = 0
Detailed Description
Definition at line 76 of file markdown.cpp.
Constructor & Destructor Documentation
Trace() [1/4]
Trace::Trace (const QCString & func) [inline]
Definition at line 79 of file markdown.cpp.
                                : m_func(func)
    {
      if (Debug::isFlagSet(Debug::Markdown))
      {
        fprintf(IOSTREAM,"> %s\n",qPrint(func));
        s_indent++;
      }
    }
References docstring::func(), IOSTREAM, Debug::isFlagSet(), Debug::Markdown, qPrint(), and s_indent.
Trace() [2/4]
Trace::Trace (const QCString & func, const QCString & data) [inline]
Definition at line 87 of file markdown.cpp.
                                                     : m_func(func)
    {
      if (Debug::isFlagSet(Debug::Markdown))
      {
        indent();
        char data_s[DATA_BUFSIZE*2+1] = ""; // worst case each input char outputs 2 chars + 0 terminator.
        int j=0;
        if (!data.isEmpty())
        {
          for (int i=0;i<DATA_BUFSIZE;i++)
          {
            char c=data[i];
            if (c==0) break;
            else if (c=='\n') { data_s[j++]='\\'; data_s[j++]='n'; }
            else if (c=='\t') { data_s[j++]='\\'; data_s[j++]='t'; }
            else if (c=='\r') { data_s[j++]='\\'; data_s[j++]='r'; }
            else if (c=='\\') { data_s[j++]='\\'; data_s[j++]='\\'; }
            else data_s[j++]=c;
          }
        }
        data_s[j++]=0;
        fprintf(IOSTREAM,"> %s data=[%s...]\n",qPrint(func),data_s);
        s_indent++;
      }
    }
References c, data, DATA_BUFSIZE, docstring::func(), indent(), IOSTREAM, Debug::isFlagSet(), Debug::Markdown, qPrint(), and s_indent.
 Trace() [1/2]
Trace::~Trace () [inline]
Definition at line 112 of file markdown.cpp.
    {
      if (Debug::isFlagSet(Debug::Markdown))
      {
        s_indent--;
        indent();
        if (m_resultSet)
        {
          fprintf(IOSTREAM,"< %s result=%s\n",qPrint(m_func),qPrint(m_resultValue));
        }
        else
        {
          fprintf(IOSTREAM,"< %s\n",qPrint(m_func));
        }
      }
    }
References indent(), IOSTREAM, Debug::isFlagSet(), m_func, m_resultSet, m_resultValue, Debug::Markdown, qPrint(), and s_indent.
Trace() [3/4]
Trace::Trace (const QCString & func) [inline]
Definition at line 79 of file markdown.cpp.
                                : m_func(func)
    {
      if (Debug::isFlagSet(Debug::Markdown))
      {
        fprintf(IOSTREAM,"> %s\n",qPrint(func));
        s_indent++;
      }
    }
References docstring::func(), IOSTREAM, Debug::isFlagSet(), Debug::Markdown, qPrint(), and s_indent.
Trace() [4/4]
Trace::Trace (const QCString & func, const QCString & data) [inline]
Definition at line 87 of file markdown.cpp.
                                                     : m_func(func)
    {
      if (Debug::isFlagSet(Debug::Markdown))
      {
        indent();
        char data_s[DATA_BUFSIZE*2+1] = ""; // worst case each input char outputs 2 chars + 0 terminator.
        int j=0;
        if (!data.isEmpty())
        {
          for (int i=0;i<DATA_BUFSIZE;i++)
          {
            char c=data[i];
            if (c==0) break;
            else if (c=='\n') { data_s[j++]='\\'; data_s[j++]='n'; }
            else if (c=='\t') { data_s[j++]='\\'; data_s[j++]='t'; }
            else if (c=='\r') { data_s[j++]='\\'; data_s[j++]='r'; }
            else if (c=='\\') { data_s[j++]='\\'; data_s[j++]='\\'; }
            else data_s[j++]=c;
          }
        }
        data_s[j++]=0;
        fprintf(IOSTREAM,"> %s data=[%s...]\n",qPrint(func),data_s);
        s_indent++;
      }
    }
References c, data, DATA_BUFSIZE, docstring::func(), indent(), IOSTREAM, Debug::isFlagSet(), Debug::Markdown, qPrint(), and s_indent.
 Trace() [2/2]
Trace::~Trace () [inline]
Definition at line 112 of file markdown.cpp.
    {
      if (Debug::isFlagSet(Debug::Markdown))
      {
        s_indent--;
        indent();
        if (m_resultSet)
        {
          fprintf(IOSTREAM,"< %s result=%s\n",qPrint(m_func),qPrint(m_resultValue));
        }
        else
        {
          fprintf(IOSTREAM,"< %s\n",qPrint(m_func));
        }
      }
    }
References indent(), IOSTREAM, Debug::isFlagSet(), m_func, m_resultSet, m_resultValue, Debug::Markdown, qPrint(), and s_indent.
Member Function Documentation
indent() [1/2]
void Trace::indent () [inline], [private]
Definition at line 166 of file markdown.cpp.
{ for (int i=0;i<s_indent;i++) fputs(" ",IOSTREAM); }
References IOSTREAM, and s_indent.
Referenced by trace(), Trace(), and ~Trace().
indent() [2/2]
void Trace::indent () [inline], [private]
Definition at line 166 of file markdown.cpp.
{ for (int i=0;i<s_indent;i++) fputs(" ",IOSTREAM); }
References IOSTREAM, and s_indent.
setResult() [1/10]
void Trace::setResult (bool b) [inline]
Definition at line 140 of file markdown.cpp.
    {
      m_resultSet = true;
      m_resultValue = b ? "true" : "false";
    }
References b, m_resultSet, and m_resultValue.
setResult() [2/10]
void Trace::setResult (bool b) [inline]
Definition at line 140 of file markdown.cpp.
    {
      m_resultSet = true;
      m_resultValue = b ? "true" : "false";
    }
References b, m_resultSet, and m_resultValue.
setResult() [3/10]
void Trace::setResult (const char * s) [inline]
Definition at line 155 of file markdown.cpp.
    {
      m_resultSet = true;
      m_resultValue = s;
    }
References m_resultSet, m_resultValue, and s.
setResult() [4/10]
void Trace::setResult (const char * s) [inline]
Definition at line 155 of file markdown.cpp.
    {
      m_resultSet = true;
      m_resultValue = s;
    }
References m_resultSet, m_resultValue, and s.
setResult() [5/10]
void Trace::setResult (const QCString & s) [inline]
Definition at line 160 of file markdown.cpp.
    {
      m_resultSet = true;
      m_resultValue = s;
    }
References m_resultSet, m_resultValue, and s.
setResult() [6/10]
void Trace::setResult (const QCString & s) [inline]
Definition at line 160 of file markdown.cpp.
    {
      m_resultSet = true;
      m_resultValue = s;
    }
References m_resultSet, m_resultValue, and s.
setResult() [7/10]
void Trace::setResult (ExplicitPageResult ep) [inline]
Definition at line 145 of file markdown.cpp.
    {
      m_resultSet = true;
      m_resultValue = QCString().setNum(static_cast<int>(ep));
    }
References m_resultSet, m_resultValue, and QCString::setNum().
setResult() [8/10]
void Trace::setResult (ExplicitPageResult ep) [inline]
Definition at line 145 of file markdown.cpp.
    {
      m_resultSet = true;
      m_resultValue = QCString().setNum(static_cast<int>(ep));
    }
References m_resultSet, m_resultValue, and QCString::setNum().
setResult() [9/10]
void Trace::setResult (int i) [inline]
Definition at line 150 of file markdown.cpp.
    {
      m_resultSet = true;
      m_resultValue = QCString().setNum(i);
    }
References m_resultSet, m_resultValue, and QCString::setNum().
setResult() [10/10]
void Trace::setResult (int i) [inline]
Definition at line 150 of file markdown.cpp.
    {
      m_resultSet = true;
      m_resultValue = QCString().setNum(i);
    }
References m_resultSet, m_resultValue, and QCString::setNum().
trace() [1/2]
void Trace::trace (const char * fmt, ...) [inline]
Definition at line 128 of file markdown.cpp.
    {
      if (Debug::isFlagSet(Debug::Markdown))
      {
        indent();
        fprintf(IOSTREAM,": %s: ",qPrint(m_func));
        va_list args;
        va_start(args,fmt);
        vfprintf(IOSTREAM, fmt, args);
        va_end(args);
      }
    }
References fmt, indent(), IOSTREAM, Debug::isFlagSet(), m_func, Debug::Markdown, and qPrint().
trace() [2/2]
void Trace::trace (const char * fmt, ...) [inline]
Definition at line 128 of file markdown.cpp.
    {
      if (Debug::isFlagSet(Debug::Markdown))
      {
        indent();
        fprintf(IOSTREAM,": %s: ",qPrint(m_func));
        va_list args;
        va_start(args,fmt);
        vfprintf(IOSTREAM, fmt, args);
        va_end(args);
      }
    }
References fmt, indent(), IOSTREAM, Debug::isFlagSet(), m_func, Debug::Markdown, and qPrint().
Member Data Documentation
m_func
QCString Trace::m_func [private]
Definition at line 167 of file markdown.cpp.
Referenced by trace(), and ~Trace().
m_resultSet
bool Trace::m_resultSet = false [private]
Definition at line 168 of file markdown.cpp.
Referenced by setResult(), and ~Trace().
m_resultValue
QCString Trace::m_resultValue [private]
Definition at line 169 of file markdown.cpp.
Referenced by setResult(), and ~Trace().
s_indent
int Trace::s_indent = 0 [static], [private]
Definition at line 170 of file markdown.cpp.
Referenced by indent(), Trace(), and ~Trace().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/markdown.cpp
doxygen/src/markdown.cpp