Autolink_Test Class Reference
Public Types
enum EType { Val1
, Val2
, Val1
, Val2
 }
enum EType { Val1
, Val2
, Val1
, Val2
 }
Public Member Functions
Autolink_Test ()
constructor
~Autolink_Test ()
destructor
void member (int)
void member (int, int)
Autolink_Test ()
constructor
~Autolink_Test ()
destructor
void member (int)
void member (int, int)
Protected Attributes
int var
Detailed Description
Since this documentation block belongs to the class Autolink_Test no link to Autolink_Test is generated.
Two ways to link to a constructor are: Autolink_Test and Autolink_Test().
Links to the destructor are: ~Autolink_Test and ~Autolink_Test().
A link to a member in this class: member().
More specific links to the each of the overloaded members: member(int) and member(int,int).
A link to the variable var.
A link to the global typedef B.
A link to the global enumeration type GlobEnum.
A link to the define ABS(x).
A link to a variable using another text as a link.
A link to the enumeration type EType.
A link to some enumeration values: Val1 and GVal1.
And last but not least a link to a file: autolink.cpp.
See also
Inside a see also section any word is checked, so EType, Val1, GVal1, ~Autolink_Test and member will be replaced by links in HTML.
Definition at line 57 of file autolink.cpp.
Member Enumeration Documentation
EType [1/2]
enum Autolink_Test::EType
An enum type. More details
Enumerator
Val1 enum value 1
Val2 enum value 2
Val1 enum value 1
Val2 enum value 2
Definition at line 66 of file autolink.cpp.
               {
      Val1,
      Val2
    };
EType [2/2]
enum Autolink_Test::EType
An enum type. More details
Enumerator
Val1 enum value 1
Val2 enum value 2
Val1 enum value 1
Val2 enum value 2
Definition at line 66 of file autolink.cpp.
               {
      Val1,
      Val2
    };
Constructor & Destructor Documentation
Autolink_Test() [1/2]
Autolink_Test::Autolink_Test ()
constructor
details.
Definition at line 76 of file autolink.cpp.
{ }
 Autolink_Test() [1/2]
Autolink_Test::~Autolink_Test ()
destructor
details.
Definition at line 79 of file autolink.cpp.
{ }
Autolink_Test() [2/2]
Autolink_Test::Autolink_Test ()
constructor
 Autolink_Test() [2/2]
Autolink_Test::~Autolink_Test ()
destructor
Member Function Documentation
member() [1/4]
void Autolink_Test::member (int)
A member function. Details.
Referenced by doxmlparser.compound.listofallmembersType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.listofallmembersType::add_member(), doxmlparser.index.CompoundType::add_member(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.listofallmembersType::get_member(), doxmlparser.index.CompoundType::get_member(), doxmlparser.compound.listofallmembersType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.compound.listofallmembersType::insert_member_at(), doxmlparser.index.CompoundType::insert_member_at(), doxmlparser.compound.listofallmembersType::replace_member_at(), doxmlparser.index.CompoundType::replace_member_at(), doxmlparser.compound.listofallmembersType::set_member(), and doxmlparser.index.CompoundType::set_member().
member() [2/4]
void Autolink_Test::member (int)
A member function. Details.
Referenced by doxmlparser.compound.listofallmembersType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.listofallmembersType::add_member(), doxmlparser.index.CompoundType::add_member(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.listofallmembersType::get_member(), doxmlparser.index.CompoundType::get_member(), doxmlparser.compound.listofallmembersType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.compound.listofallmembersType::insert_member_at(), doxmlparser.index.CompoundType::insert_member_at(), doxmlparser.compound.listofallmembersType::replace_member_at(), doxmlparser.index.CompoundType::replace_member_at(), doxmlparser.compound.listofallmembersType::set_member(), and doxmlparser.index.CompoundType::set_member().
member() [3/4]
void Autolink_Test::member (int , int)
An overloaded member function. Details
Referenced by doxmlparser.compound.listofallmembersType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.listofallmembersType::add_member(), doxmlparser.index.CompoundType::add_member(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.listofallmembersType::get_member(), doxmlparser.index.CompoundType::get_member(), doxmlparser.compound.listofallmembersType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.compound.listofallmembersType::insert_member_at(), doxmlparser.index.CompoundType::insert_member_at(), doxmlparser.compound.listofallmembersType::replace_member_at(), doxmlparser.index.CompoundType::replace_member_at(), doxmlparser.compound.listofallmembersType::set_member(), and doxmlparser.index.CompoundType::set_member().
member() [4/4]
void Autolink_Test::member (int , int)
An overloaded member function. Details
Referenced by doxmlparser.compound.listofallmembersType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.listofallmembersType::add_member(), doxmlparser.index.CompoundType::add_member(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.listofallmembersType::get_member(), doxmlparser.index.CompoundType::get_member(), doxmlparser.compound.listofallmembersType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.compound.listofallmembersType::insert_member_at(), doxmlparser.index.CompoundType::insert_member_at(), doxmlparser.compound.listofallmembersType::replace_member_at(), doxmlparser.index.CompoundType::replace_member_at(), doxmlparser.compound.listofallmembersType::set_member(), and doxmlparser.index.CompoundType::set_member().
Member Data Documentation
var
int Autolink_Test::var [protected]
A member variable
Definition at line 72 of file autolink.cpp.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/examples/autolink.cpp
doxygen/examples/autolink.cpp