NamespaceDefAliasImpl Class Reference
Public Member Functions
NamespaceDefAliasImpl (const Definition *newScope, const NamespaceDef *nd)
virtual ~NamespaceDefAliasImpl ()
virtual DefType definitionType () const
const NamespaceDef * getNSAlias () const
virtual CodeSymbolType codeSymbolType () const
virtual QCString getOutputFileBase () const
virtual QCString anchor () const
virtual int numDocMembers () const
virtual const LinkedRefMap< const NamespaceDef > & getUsedNamespaces () const
virtual const LinkedRefMap< const ClassDef > & getUsedClasses () const
virtual QCString displayName (bool b=TRUE) const
virtual QCString localName () const
virtual bool isConstantGroup () const
virtual bool isModule () const
virtual bool isLibrary () const
virtual bool isInline () const
virtual bool isLinkableInProject () const
virtual bool isLinkable () const
virtual bool hasDetailedDescription () const
virtual const Definition * findInnerCompound (const QCString &name) const
virtual bool subGrouping () const
virtual MemberList * getMemberList (MemberListType lt) const
virtual const MemberLists & getMemberLists () const
virtual const MemberDef * getMemberByName (const QCString &name) const
virtual const MemberGroupList & getMemberGroups () const
virtual ClassLinkedRefMap getClasses () const
virtual ClassLinkedRefMap getInterfaces () const
virtual ClassLinkedRefMap getStructs () const
virtual ClassLinkedRefMap getExceptions () const
virtual NamespaceLinkedRefMap getNamespaces () const
virtual ConceptLinkedRefMap getConcepts () const
virtual QCString title () const
virtual QCString compoundTypeString () const
NamespaceDefAliasImpl (const Definition *newScope, const NamespaceDef *nd)
virtual ~NamespaceDefAliasImpl ()
virtual DefType definitionType () const
const NamespaceDef * getNSAlias () const
virtual CodeSymbolType codeSymbolType () const
virtual QCString getOutputFileBase () const
virtual QCString anchor () const
virtual int numDocMembers () const
virtual const LinkedRefMap< const NamespaceDef > & getUsedNamespaces () const
virtual const LinkedRefMap< const ClassDef > & getUsedClasses () const
virtual QCString displayName (bool b=TRUE) const
virtual QCString localName () const
virtual bool isConstantGroup () const
virtual bool isModule () const
virtual bool isLibrary () const
virtual bool isInline () const
virtual bool isLinkableInProject () const
virtual bool isLinkable () const
virtual bool hasDetailedDescription () const
virtual const Definition * findInnerCompound (const QCString &name) const
virtual bool subGrouping () const
virtual MemberList * getMemberList (MemberListType lt) const
virtual const MemberLists & getMemberLists () const
virtual const MemberDef * getMemberByName (const QCString &name) const
virtual const MemberGroupList & getMemberGroups () const
virtual ClassLinkedRefMap getClasses () const
virtual ClassLinkedRefMap getInterfaces () const
virtual ClassLinkedRefMap getStructs () const
virtual ClassLinkedRefMap getExceptions () const
virtual NamespaceLinkedRefMap getNamespaces () const
virtual ConceptLinkedRefMap getConcepts () const
virtual QCString title () const
virtual QCString compoundTypeString () const
Additional Inherited Members
Detailed Description
Definition at line 174 of file namespacedef.cpp.
Constructor & Destructor Documentation
NamespaceDefAliasImpl() [1/2]
NamespaceDefAliasImpl::NamespaceDefAliasImpl (const Definition * newScope, const NamespaceDef * nd) [inline]
Definition at line 177 of file namespacedef.cpp.
      : DefinitionAliasMixin(newScope,nd) { init(); }
References DefinitionAliasMixin< NamespaceDef >::init().
 NamespaceDefAliasImpl() [1/2]
virtual NamespaceDefAliasImpl::~NamespaceDefAliasImpl () [inline], [virtual]
Definition at line 179 of file namespacedef.cpp.
{ deinit(); }
References DefinitionAliasMixin< NamespaceDef >::deinit().
NamespaceDefAliasImpl() [2/2]
NamespaceDefAliasImpl::NamespaceDefAliasImpl (const Definition * newScope, const NamespaceDef * nd) [inline]
Definition at line 177 of file namespacedef.cpp.
      : DefinitionAliasMixin(newScope,nd) { init(); }
References DefinitionAliasMixin< NamespaceDef >::init().
 NamespaceDefAliasImpl() [2/2]
virtual NamespaceDefAliasImpl::~NamespaceDefAliasImpl () [inline], [virtual]
Definition at line 179 of file namespacedef.cpp.
{ deinit(); }
References DefinitionAliasMixin< NamespaceDef >::deinit().
Member Function Documentation
anchor() [1/2]
virtual QCString NamespaceDefAliasImpl::anchor () const [inline], [virtual]
Returns the anchor within a page where this item can be found
Implements NamespaceDef.
Definition at line 189 of file namespacedef.cpp.
    { return getNSAlias()->anchor(); }
References NamespaceDef::anchor(), and getNSAlias().
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
anchor() [2/2]
virtual QCString NamespaceDefAliasImpl::anchor () const [inline], [virtual]
Returns the anchor within a page where this item can be found
Implements NamespaceDef.
Definition at line 189 of file namespacedef.cpp.
    { return getNSAlias()->anchor(); }
References NamespaceDef::anchor(), and getNSAlias().
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
codeSymbolType() [1/2]
virtual CodeSymbolType NamespaceDefAliasImpl::codeSymbolType () const [inline], [virtual]
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 185 of file namespacedef.cpp.
    { return getNSAlias()->codeSymbolType(); }
References Definition::codeSymbolType(), and getNSAlias().
codeSymbolType() [2/2]
virtual CodeSymbolType NamespaceDefAliasImpl::codeSymbolType () const [inline], [virtual]
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 185 of file namespacedef.cpp.
    { return getNSAlias()->codeSymbolType(); }
References Definition::codeSymbolType(), and getNSAlias().
compoundTypeString() [1/2]
virtual QCString NamespaceDefAliasImpl::compoundTypeString () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 241 of file namespacedef.cpp.
    { return getNSAlias()->compoundTypeString(); }
References NamespaceDef::compoundTypeString(), and getNSAlias().
compoundTypeString() [2/2]
virtual QCString NamespaceDefAliasImpl::compoundTypeString () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 241 of file namespacedef.cpp.
    { return getNSAlias()->compoundTypeString(); }
References NamespaceDef::compoundTypeString(), and getNSAlias().
definitionType() [1/2]
virtual DefType NamespaceDefAliasImpl::definitionType () const [inline], [virtual]
Use this for dynamic inspection of the type of the derived class
Implements NamespaceDef.
Definition at line 180 of file namespacedef.cpp.
{ return TypeNamespace; }
References Definition::TypeNamespace.
definitionType() [2/2]
virtual DefType NamespaceDefAliasImpl::definitionType () const [inline], [virtual]
Use this for dynamic inspection of the type of the derived class
Implements NamespaceDef.
Definition at line 180 of file namespacedef.cpp.
{ return TypeNamespace; }
References Definition::TypeNamespace.
displayName() [1/2]
virtual QCString NamespaceDefAliasImpl::displayName (bool includeScope = TRUE) const [inline], [virtual]
Returns the name of the definition as it appears in the output
Implements NamespaceDef.
Definition at line 197 of file namespacedef.cpp.
    { return makeDisplayName(this,b); }
References b, and makeDisplayName().
displayName() [2/2]
virtual QCString NamespaceDefAliasImpl::displayName (bool includeScope = TRUE) const [inline], [virtual]
Returns the name of the definition as it appears in the output
Implements NamespaceDef.
Definition at line 197 of file namespacedef.cpp.
    { return makeDisplayName(this,b); }
References b, and makeDisplayName().
findInnerCompound() [1/2]
virtual const Definition * NamespaceDefAliasImpl::findInnerCompound (const QCString & name) const [inline], [virtual]
Reimplemented from DefinitionAliasMixin< NamespaceDef >.
Definition at line 215 of file namespacedef.cpp.
    { return getNSAlias()->findInnerCompound(name); }
References NamespaceDef::findInnerCompound(), getNSAlias(), and DefinitionAliasMixin< NamespaceDef >::name().
findInnerCompound() [2/2]
virtual const Definition * NamespaceDefAliasImpl::findInnerCompound (const QCString & name) const [inline], [virtual]
Reimplemented from DefinitionAliasMixin< NamespaceDef >.
Definition at line 215 of file namespacedef.cpp.
    { return getNSAlias()->findInnerCompound(name); }
References NamespaceDef::findInnerCompound(), getNSAlias(), and DefinitionAliasMixin< NamespaceDef >::name().
getClasses() [1/2]
virtual ClassLinkedRefMap NamespaceDefAliasImpl::getClasses () const [inline], [virtual]
Returns the classes contained in this namespace
Implements NamespaceDef.
Definition at line 227 of file namespacedef.cpp.
    { return getNSAlias()->getClasses(); }
References NamespaceDef::getClasses(), and getNSAlias().
getClasses() [2/2]
virtual ClassLinkedRefMap NamespaceDefAliasImpl::getClasses () const [inline], [virtual]
Returns the classes contained in this namespace
Implements NamespaceDef.
Definition at line 227 of file namespacedef.cpp.
    { return getNSAlias()->getClasses(); }
References NamespaceDef::getClasses(), and getNSAlias().
getConcepts() [1/2]
virtual ConceptLinkedRefMap NamespaceDefAliasImpl::getConcepts () const [inline], [virtual]
Returns the concepts contained in this namespace
Implements NamespaceDef.
Definition at line 237 of file namespacedef.cpp.
    { return getNSAlias()->getConcepts(); }
References NamespaceDef::getConcepts(), and getNSAlias().
getConcepts() [2/2]
virtual ConceptLinkedRefMap NamespaceDefAliasImpl::getConcepts () const [inline], [virtual]
Returns the concepts contained in this namespace
Implements NamespaceDef.
Definition at line 237 of file namespacedef.cpp.
    { return getNSAlias()->getConcepts(); }
References NamespaceDef::getConcepts(), and getNSAlias().
getExceptions() [1/2]
virtual ClassLinkedRefMap NamespaceDefAliasImpl::getExceptions () const [inline], [virtual]
Returns the Slice exceptions contained in this namespace
Implements NamespaceDef.
Definition at line 233 of file namespacedef.cpp.
    { return getNSAlias()->getExceptions(); }
References NamespaceDef::getExceptions(), and getNSAlias().
getExceptions() [2/2]
virtual ClassLinkedRefMap NamespaceDefAliasImpl::getExceptions () const [inline], [virtual]
Returns the Slice exceptions contained in this namespace
Implements NamespaceDef.
Definition at line 233 of file namespacedef.cpp.
    { return getNSAlias()->getExceptions(); }
References NamespaceDef::getExceptions(), and getNSAlias().
getInterfaces() [1/2]
virtual ClassLinkedRefMap NamespaceDefAliasImpl::getInterfaces () const [inline], [virtual]
Returns the Slice interfaces contained in this namespace
Implements NamespaceDef.
Definition at line 229 of file namespacedef.cpp.
    { return getNSAlias()->getInterfaces(); }
References NamespaceDef::getInterfaces(), and getNSAlias().
getInterfaces() [2/2]
virtual ClassLinkedRefMap NamespaceDefAliasImpl::getInterfaces () const [inline], [virtual]
Returns the Slice interfaces contained in this namespace
Implements NamespaceDef.
Definition at line 229 of file namespacedef.cpp.
    { return getNSAlias()->getInterfaces(); }
References NamespaceDef::getInterfaces(), and getNSAlias().
getMemberByName() [1/2]
virtual const MemberDef * NamespaceDefAliasImpl::getMemberByName (const QCString & name) const [inline], [virtual]
Implements NamespaceDef.
Definition at line 223 of file namespacedef.cpp.
    { return getNSAlias()->getMemberByName(name); }
References NamespaceDef::getMemberByName(), getNSAlias(), and DefinitionAliasMixin< NamespaceDef >::name().
getMemberByName() [2/2]
virtual const MemberDef * NamespaceDefAliasImpl::getMemberByName (const QCString & name) const [inline], [virtual]
Implements NamespaceDef.
Definition at line 223 of file namespacedef.cpp.
    { return getNSAlias()->getMemberByName(name); }
References NamespaceDef::getMemberByName(), getNSAlias(), and DefinitionAliasMixin< NamespaceDef >::name().
getMemberGroups() [1/2]
virtual const MemberGroupList & NamespaceDefAliasImpl::getMemberGroups () const [inline], [virtual]
Returns the user defined member groups
Implements NamespaceDef.
Definition at line 225 of file namespacedef.cpp.
    { return getNSAlias()->getMemberGroups(); }
References NamespaceDef::getMemberGroups(), and getNSAlias().
getMemberGroups() [2/2]
virtual const MemberGroupList & NamespaceDefAliasImpl::getMemberGroups () const [inline], [virtual]
Returns the user defined member groups
Implements NamespaceDef.
Definition at line 225 of file namespacedef.cpp.
    { return getNSAlias()->getMemberGroups(); }
References NamespaceDef::getMemberGroups(), and getNSAlias().
getMemberList() [1/2]
virtual MemberList * NamespaceDefAliasImpl::getMemberList (MemberListType lt) const [inline], [virtual]
Implements NamespaceDef.
Definition at line 219 of file namespacedef.cpp.
    { return getNSAlias()->getMemberList(lt); }
References NamespaceDef::getMemberList(), and getNSAlias().
getMemberList() [2/2]
virtual MemberList * NamespaceDefAliasImpl::getMemberList (MemberListType lt) const [inline], [virtual]
Implements NamespaceDef.
Definition at line 219 of file namespacedef.cpp.
    { return getNSAlias()->getMemberList(lt); }
References NamespaceDef::getMemberList(), and getNSAlias().
getMemberLists() [1/2]
virtual const MemberLists & NamespaceDefAliasImpl::getMemberLists () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 221 of file namespacedef.cpp.
    { return getNSAlias()->getMemberLists(); }
References NamespaceDef::getMemberLists(), and getNSAlias().
getMemberLists() [2/2]
virtual const MemberLists & NamespaceDefAliasImpl::getMemberLists () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 221 of file namespacedef.cpp.
    { return getNSAlias()->getMemberLists(); }
References NamespaceDef::getMemberLists(), and getNSAlias().
getNamespaces() [1/2]
virtual NamespaceLinkedRefMap NamespaceDefAliasImpl::getNamespaces () const [inline], [virtual]
Returns the namespaces contained in this namespace
Implements NamespaceDef.
Definition at line 235 of file namespacedef.cpp.
    { return getNSAlias()->getNamespaces(); }
References NamespaceDef::getNamespaces(), and getNSAlias().
getNamespaces() [2/2]
virtual NamespaceLinkedRefMap NamespaceDefAliasImpl::getNamespaces () const [inline], [virtual]
Returns the namespaces contained in this namespace
Implements NamespaceDef.
Definition at line 235 of file namespacedef.cpp.
    { return getNSAlias()->getNamespaces(); }
References NamespaceDef::getNamespaces(), and getNSAlias().
getNSAlias() [1/2]
const NamespaceDef * NamespaceDefAliasImpl::getNSAlias () const [inline]
Definition at line 182 of file namespacedef.cpp.
{ return toNamespaceDef(getAlias()); }
References DefinitionAliasMixin< NamespaceDef >::getAlias(), and toNamespaceDef().
Referenced by anchor(), codeSymbolType(), compoundTypeString(), findInnerCompound(), getClasses(), getConcepts(), getExceptions(), getInterfaces(), getMemberByName(), getMemberGroups(), getMemberList(), getMemberLists(), getNamespaces(), getOutputFileBase(), getStructs(), getUsedClasses(), getUsedNamespaces(), hasDetailedDescription(), isConstantGroup(), isInline(), isLibrary(), isLinkable(), isLinkableInProject(), isModule(), localName(), numDocMembers(), subGrouping(), and title().
getNSAlias() [2/2]
const NamespaceDef * NamespaceDefAliasImpl::getNSAlias () const [inline]
Definition at line 182 of file namespacedef.cpp.
{ return toNamespaceDef(getAlias()); }
References DefinitionAliasMixin< NamespaceDef >::getAlias(), and toNamespaceDef().
getOutputFileBase() [1/2]
virtual QCString NamespaceDefAliasImpl::getOutputFileBase () const [inline], [virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements NamespaceDef.
Definition at line 187 of file namespacedef.cpp.
    { return getNSAlias()->getOutputFileBase(); }
References getNSAlias(), and NamespaceDef::getOutputFileBase().
getOutputFileBase() [2/2]
virtual QCString NamespaceDefAliasImpl::getOutputFileBase () const [inline], [virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements NamespaceDef.
Definition at line 187 of file namespacedef.cpp.
    { return getNSAlias()->getOutputFileBase(); }
References getNSAlias(), and NamespaceDef::getOutputFileBase().
getStructs() [1/2]
virtual ClassLinkedRefMap NamespaceDefAliasImpl::getStructs () const [inline], [virtual]
Returns the Slice structs contained in this namespace
Implements NamespaceDef.
Definition at line 231 of file namespacedef.cpp.
    { return getNSAlias()->getStructs(); }
References getNSAlias(), and NamespaceDef::getStructs().
getStructs() [2/2]
virtual ClassLinkedRefMap NamespaceDefAliasImpl::getStructs () const [inline], [virtual]
Returns the Slice structs contained in this namespace
Implements NamespaceDef.
Definition at line 231 of file namespacedef.cpp.
    { return getNSAlias()->getStructs(); }
References getNSAlias(), and NamespaceDef::getStructs().
getUsedClasses() [1/2]
virtual const LinkedRefMap< const ClassDef > & NamespaceDefAliasImpl::getUsedClasses () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 195 of file namespacedef.cpp.
    { return getNSAlias()->getUsedClasses(); }
References getNSAlias(), and NamespaceDef::getUsedClasses().
getUsedClasses() [2/2]
virtual const LinkedRefMap< const ClassDef > & NamespaceDefAliasImpl::getUsedClasses () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 195 of file namespacedef.cpp.
    { return getNSAlias()->getUsedClasses(); }
References getNSAlias(), and NamespaceDef::getUsedClasses().
getUsedNamespaces() [1/2]
virtual const LinkedRefMap< const NamespaceDef > & NamespaceDefAliasImpl::getUsedNamespaces () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 193 of file namespacedef.cpp.
    { return getNSAlias()->getUsedNamespaces(); }
References getNSAlias(), and NamespaceDef::getUsedNamespaces().
getUsedNamespaces() [2/2]
virtual const LinkedRefMap< const NamespaceDef > & NamespaceDefAliasImpl::getUsedNamespaces () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 193 of file namespacedef.cpp.
    { return getNSAlias()->getUsedNamespaces(); }
References getNSAlias(), and NamespaceDef::getUsedNamespaces().
hasDetailedDescription() [1/2]
virtual bool NamespaceDefAliasImpl::hasDetailedDescription () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 213 of file namespacedef.cpp.
    { return getNSAlias()->hasDetailedDescription(); }
References getNSAlias(), and NamespaceDef::hasDetailedDescription().
hasDetailedDescription() [2/2]
virtual bool NamespaceDefAliasImpl::hasDetailedDescription () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 213 of file namespacedef.cpp.
    { return getNSAlias()->hasDetailedDescription(); }
References getNSAlias(), and NamespaceDef::hasDetailedDescription().
isConstantGroup() [1/2]
virtual bool NamespaceDefAliasImpl::isConstantGroup () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 201 of file namespacedef.cpp.
    { return getNSAlias()->isConstantGroup(); }
References getNSAlias(), and NamespaceDef::isConstantGroup().
isConstantGroup() [2/2]
virtual bool NamespaceDefAliasImpl::isConstantGroup () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 201 of file namespacedef.cpp.
    { return getNSAlias()->isConstantGroup(); }
References getNSAlias(), and NamespaceDef::isConstantGroup().
isInline() [1/2]
virtual bool NamespaceDefAliasImpl::isInline () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 207 of file namespacedef.cpp.
    { return getNSAlias()->isInline(); }
References getNSAlias(), and NamespaceDef::isInline().
isInline() [2/2]
virtual bool NamespaceDefAliasImpl::isInline () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 207 of file namespacedef.cpp.
    { return getNSAlias()->isInline(); }
References getNSAlias(), and NamespaceDef::isInline().
isLibrary() [1/2]
virtual bool NamespaceDefAliasImpl::isLibrary () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 205 of file namespacedef.cpp.
    { return getNSAlias()->isLibrary(); }
References getNSAlias(), and NamespaceDef::isLibrary().
isLibrary() [2/2]
virtual bool NamespaceDefAliasImpl::isLibrary () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 205 of file namespacedef.cpp.
    { return getNSAlias()->isLibrary(); }
References getNSAlias(), and NamespaceDef::isLibrary().
isLinkable() [1/2]
virtual bool NamespaceDefAliasImpl::isLinkable () const [inline], [virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements NamespaceDef.
Definition at line 211 of file namespacedef.cpp.
    { return getNSAlias()->isLinkable(); }
References getNSAlias(), and NamespaceDef::isLinkable().
isLinkable() [2/2]
virtual bool NamespaceDefAliasImpl::isLinkable () const [inline], [virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements NamespaceDef.
Definition at line 211 of file namespacedef.cpp.
    { return getNSAlias()->isLinkable(); }
References getNSAlias(), and NamespaceDef::isLinkable().
isLinkableInProject() [1/2]
virtual bool NamespaceDefAliasImpl::isLinkableInProject () const [inline], [virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements NamespaceDef.
Definition at line 209 of file namespacedef.cpp.
    { return getNSAlias()->isLinkableInProject(); }
References getNSAlias(), and NamespaceDef::isLinkableInProject().
isLinkableInProject() [2/2]
virtual bool NamespaceDefAliasImpl::isLinkableInProject () const [inline], [virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements NamespaceDef.
Definition at line 209 of file namespacedef.cpp.
    { return getNSAlias()->isLinkableInProject(); }
References getNSAlias(), and NamespaceDef::isLinkableInProject().
isModule() [1/2]
virtual bool NamespaceDefAliasImpl::isModule () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 203 of file namespacedef.cpp.
    { return getNSAlias()->isModule(); }
References getNSAlias(), and NamespaceDef::isModule().
isModule() [2/2]
virtual bool NamespaceDefAliasImpl::isModule () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 203 of file namespacedef.cpp.
    { return getNSAlias()->isModule(); }
References getNSAlias(), and NamespaceDef::isModule().
localName() [1/2]
virtual QCString NamespaceDefAliasImpl::localName () const [inline], [virtual]
Returns the local name without any scope qualifiers.
Reimplemented from DefinitionAliasMixin< NamespaceDef >.
Definition at line 199 of file namespacedef.cpp.
    { return getNSAlias()->localName(); }
References getNSAlias(), and NamespaceDef::localName().
localName() [2/2]
virtual QCString NamespaceDefAliasImpl::localName () const [inline], [virtual]
Returns the local name without any scope qualifiers.
Reimplemented from DefinitionAliasMixin< NamespaceDef >.
Definition at line 199 of file namespacedef.cpp.
    { return getNSAlias()->localName(); }
References getNSAlias(), and NamespaceDef::localName().
numDocMembers() [1/2]
virtual int NamespaceDefAliasImpl::numDocMembers () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 191 of file namespacedef.cpp.
    { return getNSAlias()->numDocMembers(); }
References getNSAlias(), and NamespaceDef::numDocMembers().
numDocMembers() [2/2]
virtual int NamespaceDefAliasImpl::numDocMembers () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 191 of file namespacedef.cpp.
    { return getNSAlias()->numDocMembers(); }
References getNSAlias(), and NamespaceDef::numDocMembers().
subGrouping() [1/2]
virtual bool NamespaceDefAliasImpl::subGrouping () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 217 of file namespacedef.cpp.
    { return getNSAlias()->subGrouping(); }
References getNSAlias(), and NamespaceDef::subGrouping().
subGrouping() [2/2]
virtual bool NamespaceDefAliasImpl::subGrouping () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 217 of file namespacedef.cpp.
    { return getNSAlias()->subGrouping(); }
References getNSAlias(), and NamespaceDef::subGrouping().
title() [1/2]
virtual QCString NamespaceDefAliasImpl::title () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 239 of file namespacedef.cpp.
    { return getNSAlias()->title(); }
References getNSAlias(), and NamespaceDef::title().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
title() [2/2]
virtual QCString NamespaceDefAliasImpl::title () const [inline], [virtual]
Implements NamespaceDef.
Definition at line 239 of file namespacedef.cpp.
    { return getNSAlias()->title(); }
References getNSAlias(), and NamespaceDef::title().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/namespacedef.cpp
doxygen/src/namespacedef.cpp