DocAutoListItem Class Reference
#include <docnode.h>
Public Member Functions
DocAutoListItem (DocParser *parser, DocNodeVariant *parent, int indent, int num)
int itemNumber () const
int parse (DocNodeVariant *)
DocAutoListItem (DocParser *parser, DocNodeVariant *parent, int indent, int num)
int itemNumber () const
int parse (DocNodeVariant *)
Private Attributes
int m_indent = 0
int m_itemNum = 0
Additional Inherited Members
Detailed Description
Node representing an item of a auto list
Definition at line 557 of file docnode.h.
Constructor & Destructor Documentation
DocAutoListItem() [1/2]
DocAutoListItem::DocAutoListItem (DocParser * parser, DocNodeVariant * parent, int indent, int num)
Definition at line 2650 of file docnode.cpp.
      : DocCompoundNode(parser,parent), m_indent(indent), m_itemNum(num)
{
}
DocAutoListItem() [2/2]
DocAutoListItem::DocAutoListItem (DocParser * parser, DocNodeVariant * parent, int indent, int num)
Member Function Documentation
itemNumber() [1/2]
int DocAutoListItem::itemNumber () const [inline]
Definition at line 561 of file docnode.h.
{ return m_itemNum; }
References m_itemNum.
Referenced by ManDocVisitor::operator()().
itemNumber() [2/2]
int DocAutoListItem::itemNumber () const [inline]
Definition at line 561 of file docnode.h.
{ return m_itemNum; }
References m_itemNum.
parse() [1/2]
int DocAutoListItem::parse (DocNodeVariant * thisVariant)
Definition at line 2655 of file docnode.cpp.
{
  int retval = RetVal_OK;
  auto ns = AutoNodeStack(parser(),thisVariant);
  // first parse any number of paragraphs
  bool isFirst=TRUE;
  DocPara *lastPar=0;
  do
  {
    auto vDocPara = children().append<DocPara>(parser(),thisVariant);
    DocPara *par = children().get_last<DocPara>();
    if (isFirst) { par->markFirst(); isFirst=FALSE; }
    retval=par->parse(vDocPara);
    if (!par->isEmpty())
    {
      if (lastPar) lastPar->markLast(FALSE);
      lastPar=par;
    }
    else
    {
      children().pop_back();
    }
    // next paragraph should be more indented than the - marker to belong
    // to this item
  } while (retval==TK_NEWPARA && parser()->context.token->indent>m_indent);
  if (lastPar) lastPar->markLast();
  //printf("DocAutoListItem: retval=%d indent=%d\n",retval,parser()->context.token->indent);
  return retval;
}
References DocNodeList::append(), DocCompoundNode::children(), FALSE, DocNodeList::get_last(), m_indent, DocPara::markFirst(), DocPara::markLast(), DocNode::parser(), GrowVector< T >::pop_back(), RetVal_OK, TK_NEWPARA, and TRUE.
Referenced by DocAutoList::parse().
parse() [2/2]
int DocAutoListItem::parse (DocNodeVariant *)
Member Data Documentation
m_indent
int DocAutoListItem::m_indent = 0 [private]
Definition at line 565 of file docnode.h.
Referenced by parse().
m_itemNum
int DocAutoListItem::m_itemNum = 0 [private]
Definition at line 566 of file docnode.h.
Referenced by itemNumber().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docnode.h
doxygen/src/docnode.h
doxygen/build/doxygen/src/docnode.cpp
doxygen/src/docnode.cpp