Step3 Class Reference
#include <wizard.h>
Public Member Functions
Step3 (Wizard *parent, const QHash< QString, Input * > &modelData)
void init ()
Step3 (Wizard *parent, const QHash< QString, Input * > &modelData)
void init ()
Private Slots
void setHtmlEnabled (bool)
void setLatexEnabled (bool)
void setManEnabled (int)
void setRtfEnabled (int)
void setXmlEnabled (int)
void setDocbookEnabled (int)
void setSearchEnabled (int)
void setHtmlOptions (int)
void setLatexOptions (int)
void tuneColorDialog ()
void setHtmlEnabled (bool)
void setLatexEnabled (bool)
void setManEnabled (int)
void setRtfEnabled (int)
void setXmlEnabled (int)
void setDocbookEnabled (int)
void setSearchEnabled (int)
void setHtmlOptions (int)
void setLatexOptions (int)
void tuneColorDialog ()
Private Attributes
QGroupBox * m_texOptions = 0
QButtonGroup * m_texOptionsGroup = 0
QGroupBox * m_htmlOptions = 0
QButtonGroup * m_htmlOptionsGroup = 0
QCheckBox * m_htmlEnabled = 0
QCheckBox * m_latexEnabled = 0
QCheckBox * m_manEnabled = 0
QCheckBox * m_rtfEnabled = 0
QCheckBox * m_xmlEnabled = 0
QCheckBox * m_docbookEnabled = 0
QCheckBox * m_searchEnabled = 0
QPushButton * m_tuneColor = 0
Wizard * m_wizard = 0
const QHash< QString, Input * > & m_modelData
Detailed Description
Definition at line 151 of file wizard.h.
Constructor & Destructor Documentation
Step3() [1/2]
Step3::Step3 (Wizard * parent, const QHash< QString, Input * > & modelData)
Definition at line 919 of file wizard.cpp.
  : m_wizard(wizard), m_modelData(modelData)
{
  QVBoxLayout *vbox = 0;
  QRadioButton *r = 0;
  QGridLayout *gbox = new QGridLayout(this);
  gbox->addWidget(new QLabel(tr("Select the output format(s) to generate")),0,0);
  {
    m_htmlOptions = new QGroupBox(tr("HTML"));
    m_htmlOptions->setCheckable(true);
    // GENERATE_HTML
    m_htmlOptionsGroup = new QButtonGroup(m_htmlOptions);
    QRadioButton *r = new QRadioButton(tr("plain HTML"));
    r->setChecked(true);
    m_htmlOptionsGroup->addButton(r, 0);
    vbox = new QVBoxLayout;
    vbox->addWidget(r);
    r = new QRadioButton(tr("with navigation panel"));
    m_htmlOptionsGroup->addButton(r, 1);
    // GENERATE_TREEVIEW
    vbox->addWidget(r);
    r = new QRadioButton(tr("prepare for compressed HTML (.chm)"));
    m_htmlOptionsGroup->addButton(r, 2);
    // GENERATE_HTMLHELP
    vbox->addWidget(r);
    m_searchEnabled=new QCheckBox(tr("With search function"));
    vbox->addWidget(m_searchEnabled);
    // SEARCH_ENGINE
    QHBoxLayout *hbox = new QHBoxLayout;
    m_tuneColor=new QPushButton(tr("Change color..."));
    hbox->addWidget(m_tuneColor);
    hbox->addStretch(1);
    vbox->addLayout(hbox);
    m_htmlOptions->setLayout(vbox);
    m_htmlOptions->setChecked(true);
  }
  gbox->addWidget(m_htmlOptions,1,0);
  {
    m_texOptions = new QGroupBox(tr("LaTeX"));
    m_texOptions->setCheckable(true);
    // GENERATE_LATEX
    m_texOptionsGroup = new QButtonGroup(m_texOptions);
    vbox = new QVBoxLayout;
    r = new QRadioButton(tr("as intermediate format for hyperlinked PDF"));
    m_texOptionsGroup->addButton(r, 0);
    // PDF_HYPERLINKS = YES
    r->setChecked(true);
    vbox->addWidget(r);
    r = new QRadioButton(tr("as intermediate format for PDF"));
    m_texOptionsGroup->addButton(r, 1);
    // PDF_HYPERLINKS = NO, USE_PDFLATEX = YES
    vbox->addWidget(r);
    r = new QRadioButton(tr("as intermediate format for PostScript"));
    m_texOptionsGroup->addButton(r, 2);
    // USE_PDFLATEX = NO
    vbox->addWidget(r);
    vbox->addStretch(1);
    m_texOptions->setLayout(vbox);
    m_texOptions->setChecked(true);
  }
  gbox->addWidget(m_texOptions,2,0);
  m_manEnabled=new QCheckBox(tr("Man pages"));
  // GENERATE_MAN
  m_rtfEnabled=new QCheckBox(tr("Rich Text Format (RTF)"));
  // GENERATE_RTF
  m_xmlEnabled=new QCheckBox(tr("XML"));
  // GENERATE_XML
  m_docbookEnabled=new QCheckBox(tr("Docbook"));
  // GENERATE_DOCBOOK
  gbox->addWidget(m_manEnabled,3,0);
  gbox->addWidget(m_rtfEnabled,4,0);
  gbox->addWidget(m_xmlEnabled,5,0);
  gbox->addWidget(m_docbookEnabled,6,0);
  gbox->setRowStretch(7,1);
  connect(m_htmlOptions,SIGNAL(toggled(bool)),SLOT(setHtmlEnabled(bool)));
  connect(m_texOptions,SIGNAL(toggled(bool)),SLOT(setLatexEnabled(bool)));
  connect(m_manEnabled,SIGNAL(stateChanged(int)),SLOT(setManEnabled(int)));
  connect(m_rtfEnabled,SIGNAL(stateChanged(int)),SLOT(setRtfEnabled(int)));
  connect(m_xmlEnabled,SIGNAL(stateChanged(int)),SLOT(setXmlEnabled(int)));
  connect(m_docbookEnabled,SIGNAL(stateChanged(int)),SLOT(setDocbookEnabled(int)));
  connect(m_searchEnabled,SIGNAL(stateChanged(int)),SLOT(setSearchEnabled(int)));
#if QT_VERSION < QT_VERSION_CHECK(5, 15, 0)
  connect(m_htmlOptionsGroup,SIGNAL(buttonClicked(int)),SLOT(setHtmlOptions(int)));
  connect(m_texOptionsGroup,SIGNAL(buttonClicked(int)),SLOT(setLatexOptions(int)));
#else
  connect(m_htmlOptionsGroup,SIGNAL(idClicked(int)),SLOT(setHtmlOptions(int)));
  connect(m_texOptionsGroup,SIGNAL(idClicked(int)),SLOT(setLatexOptions(int)));
#endif
  connect(m_tuneColor,SIGNAL(clicked()),SLOT(tuneColorDialog()));
}
References m_docbookEnabled, m_htmlOptions, m_htmlOptionsGroup, m_manEnabled, m_rtfEnabled, m_searchEnabled, m_texOptions, m_texOptionsGroup, m_tuneColor, m_xmlEnabled, r, setDocbookEnabled(), setHtmlEnabled(), setHtmlOptions(), setLatexEnabled(), setLatexOptions(), setManEnabled(), setRtfEnabled(), setSearchEnabled(), setXmlEnabled(), and tuneColorDialog().
Step3() [2/2]
Step3::Step3 (Wizard * parent, const QHash< QString, Input * > & modelData)
Member Function Documentation
init() [1/2]
void Step3::init ()
Definition at line 1101 of file wizard.cpp.
{
  m_htmlOptions->setChecked(getBoolOption(m_modelData,STR_GENERATE_HTML));
  m_texOptions->setChecked(getBoolOption(m_modelData,STR_GENERATE_LATEX));
  m_manEnabled->setChecked(getBoolOption(m_modelData,STR_GENERATE_MAN));
  m_rtfEnabled->setChecked(getBoolOption(m_modelData,STR_GENERATE_RTF));
  m_xmlEnabled->setChecked(getBoolOption(m_modelData,STR_GENERATE_XML));
  m_docbookEnabled->setChecked(getBoolOption(m_modelData,STR_GENERATE_DOCBOOK));
  m_searchEnabled->setChecked(getBoolOption(m_modelData,STR_SEARCHENGINE));
  if (getBoolOption(m_modelData,STR_GENERATE_HTMLHELP))
  {
    m_htmlOptionsGroup->button(2)->setChecked(true); // compiled help
  }
  else if (getBoolOption(m_modelData,STR_GENERATE_TREEVIEW))
  {
    m_htmlOptionsGroup->button(1)->setChecked(true); // navigation tree
  }
  else
  {
    m_htmlOptionsGroup->button(0)->setChecked(true); // plain HTML
  }
  if (!getBoolOption(m_modelData,STR_USE_PDFLATEX))
  {
    m_texOptionsGroup->button(2)->setChecked(true); // PostScript
  }
  else if (!getBoolOption(m_modelData,STR_PDF_HYPERLINKS))
  {
    m_texOptionsGroup->button(1)->setChecked(true); // Plain PDF
  }
  else
  {
    m_texOptionsGroup->button(0)->setChecked(true); // PDF with hyperlinks
  }
}
References getBoolOption(), m_docbookEnabled, m_htmlOptions, m_htmlOptionsGroup, m_manEnabled, m_modelData, m_rtfEnabled, m_searchEnabled, m_texOptions, m_texOptionsGroup, m_xmlEnabled, STR_GENERATE_DOCBOOK, STR_GENERATE_HTML, STR_GENERATE_HTMLHELP, STR_GENERATE_LATEX, STR_GENERATE_MAN, STR_GENERATE_RTF, STR_GENERATE_TREEVIEW, STR_GENERATE_XML, STR_PDF_HYPERLINKS, STR_SEARCHENGINE, and STR_USE_PDFLATEX.
Referenced by Wizard::refresh().
init() [2/2]
void Step3::init ()
setDocbookEnabled [1/2]
void Step3::setDocbookEnabled (int state) [private], [slot]
Definition at line 1053 of file wizard.cpp.
{
  updateBoolOption(m_modelData,STR_GENERATE_DOCBOOK,state==Qt::Checked);
}
References m_modelData, STR_GENERATE_DOCBOOK, and updateBoolOption().
Referenced by Step3().
setDocbookEnabled [2/2]
void Step3::setDocbookEnabled (int) [private], [slot]
setHtmlEnabled [1/2]
void Step3::setHtmlEnabled (bool b) [private], [slot]
Definition at line 1028 of file wizard.cpp.
{
  updateBoolOption(m_modelData,STR_GENERATE_HTML,b);
}
References b, m_modelData, STR_GENERATE_HTML, and updateBoolOption().
Referenced by Step3().
setHtmlEnabled [2/2]
void Step3::setHtmlEnabled (bool) [private], [slot]
setHtmlOptions [1/2]
void Step3::setHtmlOptions (int id) [private], [slot]
Definition at line 1063 of file wizard.cpp.
{
  if (id==0) // plain HTML
  {
    updateBoolOption(m_modelData,STR_GENERATE_HTMLHELP,false);
    updateBoolOption(m_modelData,STR_GENERATE_TREEVIEW,false);
  }
  else if (id==1) // with navigation tree
  {
    updateBoolOption(m_modelData,STR_GENERATE_HTMLHELP,false);
    updateBoolOption(m_modelData,STR_GENERATE_TREEVIEW,true);
  }
  else if (id==2) // with compiled help
  {
    updateBoolOption(m_modelData,STR_GENERATE_HTMLHELP,true);
    updateBoolOption(m_modelData,STR_GENERATE_TREEVIEW,false);
  }
}
References m_modelData, STR_GENERATE_HTMLHELP, STR_GENERATE_TREEVIEW, and updateBoolOption().
Referenced by Step3().
setHtmlOptions [2/2]
void Step3::setHtmlOptions (int) [private], [slot]
setLatexEnabled [1/2]
void Step3::setLatexEnabled (bool b) [private], [slot]
Definition at line 1033 of file wizard.cpp.
{
  updateBoolOption(m_modelData,STR_GENERATE_LATEX,b);
}
References b, m_modelData, STR_GENERATE_LATEX, and updateBoolOption().
Referenced by Step3().
setLatexEnabled [2/2]
void Step3::setLatexEnabled (bool) [private], [slot]
setLatexOptions [1/2]
void Step3::setLatexOptions (int id) [private], [slot]
Definition at line 1082 of file wizard.cpp.
{
  if (id==0) // hyperlinked PDF
  {
    updateBoolOption(m_modelData,STR_USE_PDFLATEX,true);
    updateBoolOption(m_modelData,STR_PDF_HYPERLINKS,true);
  }
  else if (id==1) // PDF
  {
    updateBoolOption(m_modelData,STR_USE_PDFLATEX,true);
    updateBoolOption(m_modelData,STR_PDF_HYPERLINKS,false);
  }
  else if (id==2) // PostScript
  {
    updateBoolOption(m_modelData,STR_USE_PDFLATEX,false);
    updateBoolOption(m_modelData,STR_PDF_HYPERLINKS,false);
  }
}
References m_modelData, STR_PDF_HYPERLINKS, STR_USE_PDFLATEX, and updateBoolOption().
Referenced by Step3().
setLatexOptions [2/2]
void Step3::setLatexOptions (int) [private], [slot]
setManEnabled [1/2]
void Step3::setManEnabled (int state) [private], [slot]
Definition at line 1038 of file wizard.cpp.
{
  updateBoolOption(m_modelData,STR_GENERATE_MAN,state==Qt::Checked);
}
References m_modelData, STR_GENERATE_MAN, and updateBoolOption().
Referenced by Step3().
setManEnabled [2/2]
void Step3::setManEnabled (int) [private], [slot]
setRtfEnabled [1/2]
void Step3::setRtfEnabled (int state) [private], [slot]
Definition at line 1043 of file wizard.cpp.
{
  updateBoolOption(m_modelData,STR_GENERATE_RTF,state==Qt::Checked);
}
References m_modelData, STR_GENERATE_RTF, and updateBoolOption().
Referenced by Step3().
setRtfEnabled [2/2]
void Step3::setRtfEnabled (int) [private], [slot]
setSearchEnabled [1/2]
void Step3::setSearchEnabled (int state) [private], [slot]
Definition at line 1058 of file wizard.cpp.
{
  updateBoolOption(m_modelData,STR_SEARCHENGINE,state==Qt::Checked);
}
References m_modelData, STR_SEARCHENGINE, and updateBoolOption().
Referenced by Step3().
setSearchEnabled [2/2]
void Step3::setSearchEnabled (int) [private], [slot]
setXmlEnabled [1/2]
void Step3::setXmlEnabled (int state) [private], [slot]
Definition at line 1048 of file wizard.cpp.
{
  updateBoolOption(m_modelData,STR_GENERATE_XML,state==Qt::Checked);
}
References m_modelData, STR_GENERATE_XML, and updateBoolOption().
Referenced by Step3().
setXmlEnabled [2/2]
void Step3::setXmlEnabled (int) [private], [slot]
tuneColorDialog [1/2]
void Step3::tuneColorDialog () [private], [slot]
Definition at line 1014 of file wizard.cpp.
{
  int hue = getIntOption(m_modelData,STR_HTML_COLORSTYLE_HUE);
  int sat = getIntOption(m_modelData,STR_HTML_COLORSTYLE_SAT);
  int gam = getIntOption(m_modelData,STR_HTML_COLORSTYLE_GAMMA);
  TuneColorDialog tuneColor(hue,sat,gam,this);
  if (tuneColor.exec()==QDialog::Accepted)
  {
    updateIntOption(m_modelData,STR_HTML_COLORSTYLE_HUE,tuneColor.getHue());
    updateIntOption(m_modelData,STR_HTML_COLORSTYLE_SAT,tuneColor.getSaturation());
    updateIntOption(m_modelData,STR_HTML_COLORSTYLE_GAMMA,tuneColor.getGamma());
  }
}
References TuneColorDialog::getGamma(), TuneColorDialog::getHue(), getIntOption(), TuneColorDialog::getSaturation(), m_modelData, STR_HTML_COLORSTYLE_GAMMA, STR_HTML_COLORSTYLE_HUE, STR_HTML_COLORSTYLE_SAT, and updateIntOption().
Referenced by Step3().
tuneColorDialog [2/2]
void Step3::tuneColorDialog () [private], [slot]
Member Data Documentation
m_docbookEnabled
QCheckBox * Step3::m_docbookEnabled = 0 [private]
Definition at line 181 of file wizard.h.
Referenced by init(), and Step3().
m_htmlEnabled
QCheckBox * Step3::m_htmlEnabled = 0 [private]
Definition at line 176 of file wizard.h.
m_htmlOptions
QGroupBox * Step3::m_htmlOptions = 0 [private]
Definition at line 174 of file wizard.h.
Referenced by init(), and Step3().
m_htmlOptionsGroup
QButtonGroup * Step3::m_htmlOptionsGroup = 0 [private]
Definition at line 175 of file wizard.h.
Referenced by init(), and Step3().
m_latexEnabled
QCheckBox * Step3::m_latexEnabled = 0 [private]
Definition at line 177 of file wizard.h.
m_manEnabled
QCheckBox * Step3::m_manEnabled = 0 [private]
Definition at line 178 of file wizard.h.
Referenced by init(), and Step3().
m_modelData
const QHash< QString, Input * > & Step3::m_modelData [private]
Definition at line 185 of file wizard.h.
Referenced by init(), setDocbookEnabled(), setHtmlEnabled(), setHtmlOptions(), setLatexEnabled(), setLatexOptions(), setManEnabled(), setRtfEnabled(), setSearchEnabled(), setXmlEnabled(), and tuneColorDialog().
m_rtfEnabled
QCheckBox * Step3::m_rtfEnabled = 0 [private]
Definition at line 179 of file wizard.h.
Referenced by init(), and Step3().
m_searchEnabled
QCheckBox * Step3::m_searchEnabled = 0 [private]
Definition at line 182 of file wizard.h.
Referenced by init(), and Step3().
m_texOptions
QGroupBox * Step3::m_texOptions = 0 [private]
Definition at line 172 of file wizard.h.
Referenced by init(), and Step3().
m_texOptionsGroup
QButtonGroup * Step3::m_texOptionsGroup = 0 [private]
Definition at line 173 of file wizard.h.
Referenced by init(), and Step3().
m_tuneColor
QPushButton * Step3::m_tuneColor = 0 [private]
Definition at line 183 of file wizard.h.
Referenced by Step3().
m_wizard
Wizard * Step3::m_wizard = 0 [private]
Definition at line 184 of file wizard.h.
m_xmlEnabled
QCheckBox * Step3::m_xmlEnabled = 0 [private]
Definition at line 180 of file wizard.h.
Referenced by init(), and Step3().
The documentation for this class was generated from the following files:
doxygen/addon/doxywizard/wizard.h
doxygen/build/doxygen/addon/doxywizard/wizard.h
doxygen/addon/doxywizard/wizard.cpp
doxygen/build/doxygen/addon/doxywizard/wizard.cpp