OutputList Class Reference
#include <outputlist.h>
Public Member Functions
OutputList ()
OutputList (const OutputList &ol)
OutputList & operator= (const OutputList &ol)
virtual ~OutputList ()
template<class Generator >
void add ()
size_t size () const
int id () const
void disableAllBut (OutputGenerator::OutputType o)
void enableAll ()
void disableAll ()
void disable (OutputGenerator::OutputType o)
void enable (OutputGenerator::OutputType o)
bool isEnabled (OutputGenerator::OutputType o)
void pushGeneratorState ()
void popGeneratorState ()
void generateDoc (const QCString &fileName, int startLine, const Definition *ctx, const MemberDef *md, const QCString &docStr, bool indexWords, bool isExample, const QCString &exampleName, bool singleLine, bool linkFromIndex, bool markdownSupport)
void writeDoc (const IDocNodeAST *ast, const Definition *ctx, const MemberDef *md, int id=0)
void parseText (const QCString &textStr)
void startIndexSection (IndexSections is)
void endIndexSection (IndexSections is)
void writePageLink (const QCString &name, bool first)
void startProjectNumber ()
void endProjectNumber ()
void writeStyleInfo (int part)
void startFile (const QCString &name, const QCString &manName, const QCString &title)
void writeSearchInfo ()
void writeFooter (const QCString &navPath)
void endFile ()
void startTitleHead (const QCString &fileName)
void endTitleHead (const QCString &fileName, const QCString &name)
void startTitle ()
void endTitle ()
void startParagraph (const QCString &classDef=QCString())
void endParagraph ()
void writeString (const QCString &text)
void startIndexListItem ()
void endIndexListItem ()
void startIndexList ()
void endIndexList ()
void startIndexKey ()
void endIndexKey ()
void startIndexValue (bool b)
void endIndexValue (const QCString &name, bool b)
void startItemList ()
void endItemList ()
void startIndexItem (const QCString &ref, const QCString &file)
void endIndexItem (const QCString &ref, const QCString &file)
void docify (const QCString &s)
void codify (const QCString &s)
void writeObjectLink (const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name)
void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip)
void writeTooltip (const QCString &id, const DocLinkInfo &docInfo, const QCString &decl, const QCString &desc, const SourceLinkInfo &defInfo, const SourceLinkInfo &declInfo)
void startTextLink (const QCString &file, const QCString &anchor)
void endTextLink ()
void startHtmlLink (const QCString &url)
void endHtmlLink ()
void writeStartAnnoItem (const QCString &type, const QCString &file, const QCString &path, const QCString &name)
void writeEndAnnoItem (const QCString &name)
void startTypewriter ()
void endTypewriter ()
void startGroupHeader (int extraLevels=0)
void endGroupHeader (int extraLevels=0)
void startItemListItem ()
void endItemListItem ()
void startMemberSections ()
void endMemberSections ()
void startHeaderSection ()
void endHeaderSection ()
void startMemberHeader (const QCString &anchor, int typ=2)
void endMemberHeader ()
void startMemberSubtitle ()
void endMemberSubtitle ()
void startMemberDocList ()
void endMemberDocList ()
void startMemberList ()
void endMemberList ()
void startInlineHeader ()
void endInlineHeader ()
void startAnonTypeScope (int i1)
void endAnonTypeScope (int i1)
void startMemberItem (const QCString &anchor, int i1, const QCString &id=QCString())
void endMemberItem ()
void startMemberTemplateParams ()
void endMemberTemplateParams (const QCString &anchor, const QCString &inheritId)
void startCompoundTemplateParams ()
void endCompoundTemplateParams ()
void startMemberGroupHeader (bool b)
void endMemberGroupHeader ()
void startMemberGroupDocs ()
void endMemberGroupDocs ()
void startMemberGroup ()
void endMemberGroup (bool last)
void insertMemberAlign (bool templ=FALSE)
void insertMemberAlignLeft (int typ=0, bool templ=FALSE)
void writeRuler ()
void writeAnchor (const QCString &fileName, const QCString &name)
void startCodeFragment (const QCString &style)
void endCodeFragment (const QCString &style)
void startCodeLine (bool hasLineNumbers)
void endCodeLine ()
void writeLineNumber (const QCString &ref, const QCString &file, const QCString &anchor, int lineNumber, bool writeLineAnchor)
void startEmphasis ()
void endEmphasis ()
void writeChar (char c)
void startMemberDoc (const QCString &clName, const QCString &memName, const QCString &anchor, const QCString &title, int memCount, int memTotal, bool showInline)
void endMemberDoc (bool hasArgs)
void startDoxyAnchor (const QCString &fName, const QCString &manName, const QCString &anchor, const QCString &name, const QCString &args)
void endDoxyAnchor (const QCString &fn, const QCString &anchor)
void writeLatexSpacing ()
void startDescription ()
void endDescription ()
void startDescItem ()
void endDescItem ()
void startDescForItem ()
void endDescForItem ()
void startSubsection ()
void endSubsection ()
void startSubsubsection ()
void endSubsubsection ()
void startCenter ()
void endCenter ()
void startSmall ()
void endSmall ()
void lineBreak (const QCString &style=QCString())
void startBold ()
void endBold ()
void startMemberDescription (const QCString &anchor, const QCString &inheritId=QCString(), bool typ=false)
void endMemberDescription ()
void startMemberDeclaration ()
void endMemberDeclaration (const QCString &anchor, const QCString &inheritId)
void writeInheritedSectionTitle (const QCString &id, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &title, const QCString &name)
void startExamples ()
void endExamples ()
void startParamList (ParamListTypes t, const QCString &title)
void endParamList ()
void startIndent ()
void endIndent ()
void startSection (const QCString &lab, const QCString &title, SectionType t)
void endSection (const QCString &lab, SectionType t)
void addIndexItem (const QCString &s1, const QCString &s2)
void writeSynopsis ()
void startClassDiagram ()
void endClassDiagram (const ClassDiagram &d, const QCString &f, const QCString &n)
void startPageRef ()
void endPageRef (const QCString &c, const QCString &a)
void startQuickIndices ()
void endQuickIndices ()
void writeSplitBar (const QCString &name)
void writeNavigationPath (const QCString &s)
void writeLogo ()
void writeQuickLinks (bool compact, HighlightedItem hli, const QCString &file)
void writeSummaryLink (const QCString &file, const QCString &anchor, const QCString &title, bool first)
void startContents ()
void endContents ()
void startPageDoc (const QCString &pageTitle)
void endPageDoc ()
void writeNonBreakableSpace (int num)
void startDescTable (const QCString &title)
void endDescTable ()
void startDescTableRow ()
void endDescTableRow ()
void startDescTableTitle ()
void endDescTableTitle ()
void startDescTableData ()
void endDescTableData ()
void startDotGraph ()
void endDotGraph (DotClassGraph &g)
void startInclDepGraph ()
void endInclDepGraph (DotInclDepGraph &g)
void startCallGraph ()
void endCallGraph (DotCallGraph &g)
void startDirDepGraph ()
void endDirDepGraph (DotDirDeps &g)
void startGroupCollaboration ()
void endGroupCollaboration (DotGroupCollaboration &g)
void writeGraphicalHierarchy (DotGfxHierarchyTable &g)
void startTextBlock (bool dense=FALSE)
void endTextBlock (bool paraBreak=FALSE)
void lastIndexPage ()
void startMemberDocPrefixItem ()
void endMemberDocPrefixItem ()
void startMemberDocName (bool align)
void endMemberDocName ()
void startParameterType (bool first, const QCString &key)
void endParameterType ()
void startParameterName (bool one)
void endParameterName (bool last, bool one, bool bracket)
void startParameterList (bool openBracket)
void endParameterList ()
void exceptionEntry (const QCString &prefix, bool closeBracket)
void startConstraintList (const QCString &header)
void startConstraintParam ()
void endConstraintParam ()
void startConstraintType ()
void endConstraintType ()
void startConstraintDocs ()
void endConstraintDocs ()
void endConstraintList ()
void startMemberDocSimple (bool b)
void endMemberDocSimple (bool b)
void startInlineMemberType ()
void endInlineMemberType ()
void startInlineMemberName ()
void endInlineMemberName ()
void startInlineMemberDoc ()
void endInlineMemberDoc ()
void startLabels ()
void writeLabel (const QCString &l, bool isLast)
void endLabels ()
void cleanup ()
void startFontClass (const QCString &c)
void endFontClass ()
void writeCodeAnchor (const QCString &name)
void setCurrentDoc (const Definition *context, const QCString &anchor, bool isSourceFile)
void addWord (const QCString &word, bool hiPriority)
void indexSearchData ()
void startPlainFile (const QCString &name)
void endPlainFile ()
OutputList ()
OutputList (const OutputList &ol)
OutputList & operator= (const OutputList &ol)
virtual ~OutputList ()
template<class Generator >
void add ()
size_t size () const
int id () const
void disableAllBut (OutputGenerator::OutputType o)
void enableAll ()
void disableAll ()
void disable (OutputGenerator::OutputType o)
void enable (OutputGenerator::OutputType o)
bool isEnabled (OutputGenerator::OutputType o)
void pushGeneratorState ()
void popGeneratorState ()
void generateDoc (const QCString &fileName, int startLine, const Definition *ctx, const MemberDef *md, const QCString &docStr, bool indexWords, bool isExample, const QCString &exampleName, bool singleLine, bool linkFromIndex, bool markdownSupport)
void writeDoc (const IDocNodeAST *ast, const Definition *ctx, const MemberDef *md, int id=0)
void parseText (const QCString &textStr)
void startIndexSection (IndexSections is)
void endIndexSection (IndexSections is)
void writePageLink (const QCString &name, bool first)
void startProjectNumber ()
void endProjectNumber ()
void writeStyleInfo (int part)
void startFile (const QCString &name, const QCString &manName, const QCString &title)
void writeSearchInfo ()
void writeFooter (const QCString &navPath)
void endFile ()
void startTitleHead (const QCString &fileName)
void endTitleHead (const QCString &fileName, const QCString &name)
void startTitle ()
void endTitle ()
void startParagraph (const QCString &classDef=QCString())
void endParagraph ()
void writeString (const QCString &text)
void startIndexListItem ()
void endIndexListItem ()
void startIndexList ()
void endIndexList ()
void startIndexKey ()
void endIndexKey ()
void startIndexValue (bool b)
void endIndexValue (const QCString &name, bool b)
void startItemList ()
void endItemList ()
void startIndexItem (const QCString &ref, const QCString &file)
void endIndexItem (const QCString &ref, const QCString &file)
void docify (const QCString &s)
void codify (const QCString &s)
void writeObjectLink (const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name)
void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip)
void writeTooltip (const QCString &id, const DocLinkInfo &docInfo, const QCString &decl, const QCString &desc, const SourceLinkInfo &defInfo, const SourceLinkInfo &declInfo)
void startTextLink (const QCString &file, const QCString &anchor)
void endTextLink ()
void startHtmlLink (const QCString &url)
void endHtmlLink ()
void writeStartAnnoItem (const QCString &type, const QCString &file, const QCString &path, const QCString &name)
void writeEndAnnoItem (const QCString &name)
void startTypewriter ()
void endTypewriter ()
void startGroupHeader (int extraLevels=0)
void endGroupHeader (int extraLevels=0)
void startItemListItem ()
void endItemListItem ()
void startMemberSections ()
void endMemberSections ()
void startHeaderSection ()
void endHeaderSection ()
void startMemberHeader (const QCString &anchor, int typ=2)
void endMemberHeader ()
void startMemberSubtitle ()
void endMemberSubtitle ()
void startMemberDocList ()
void endMemberDocList ()
void startMemberList ()
void endMemberList ()
void startInlineHeader ()
void endInlineHeader ()
void startAnonTypeScope (int i1)
void endAnonTypeScope (int i1)
void startMemberItem (const QCString &anchor, int i1, const QCString &id=QCString())
void endMemberItem ()
void startMemberTemplateParams ()
void endMemberTemplateParams (const QCString &anchor, const QCString &inheritId)
void startCompoundTemplateParams ()
void endCompoundTemplateParams ()
void startMemberGroupHeader (bool b)
void endMemberGroupHeader ()
void startMemberGroupDocs ()
void endMemberGroupDocs ()
void startMemberGroup ()
void endMemberGroup (bool last)
void insertMemberAlign (bool templ=FALSE)
void insertMemberAlignLeft (int typ=0, bool templ=FALSE)
void writeRuler ()
void writeAnchor (const QCString &fileName, const QCString &name)
void startCodeFragment (const QCString &style)
void endCodeFragment (const QCString &style)
void startCodeLine (bool hasLineNumbers)
void endCodeLine ()
void writeLineNumber (const QCString &ref, const QCString &file, const QCString &anchor, int lineNumber, bool writeLineAnchor)
void startEmphasis ()
void endEmphasis ()
void writeChar (char c)
void startMemberDoc (const QCString &clName, const QCString &memName, const QCString &anchor, const QCString &title, int memCount, int memTotal, bool showInline)
void endMemberDoc (bool hasArgs)
void startDoxyAnchor (const QCString &fName, const QCString &manName, const QCString &anchor, const QCString &name, const QCString &args)
void endDoxyAnchor (const QCString &fn, const QCString &anchor)
void writeLatexSpacing ()
void startDescription ()
void endDescription ()
void startDescItem ()
void endDescItem ()
void startDescForItem ()
void endDescForItem ()
void startSubsection ()
void endSubsection ()
void startSubsubsection ()
void endSubsubsection ()
void startCenter ()
void endCenter ()
void startSmall ()
void endSmall ()
void lineBreak (const QCString &style=QCString())
void startBold ()
void endBold ()
void startMemberDescription (const QCString &anchor, const QCString &inheritId=QCString(), bool typ=false)
void endMemberDescription ()
void startMemberDeclaration ()
void endMemberDeclaration (const QCString &anchor, const QCString &inheritId)
void writeInheritedSectionTitle (const QCString &id, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &title, const QCString &name)
void startExamples ()
void endExamples ()
void startParamList (ParamListTypes t, const QCString &title)
void endParamList ()
void startIndent ()
void endIndent ()
void startSection (const QCString &lab, const QCString &title, SectionType t)
void endSection (const QCString &lab, SectionType t)
void addIndexItem (const QCString &s1, const QCString &s2)
void writeSynopsis ()
void startClassDiagram ()
void endClassDiagram (const ClassDiagram &d, const QCString &f, const QCString &n)
void startPageRef ()
void endPageRef (const QCString &c, const QCString &a)
void startQuickIndices ()
void endQuickIndices ()
void writeSplitBar (const QCString &name)
void writeNavigationPath (const QCString &s)
void writeLogo ()
void writeQuickLinks (bool compact, HighlightedItem hli, const QCString &file)
void writeSummaryLink (const QCString &file, const QCString &anchor, const QCString &title, bool first)
void startContents ()
void endContents ()
void startPageDoc (const QCString &pageTitle)
void endPageDoc ()
void writeNonBreakableSpace (int num)
void startDescTable (const QCString &title)
void endDescTable ()
void startDescTableRow ()
void endDescTableRow ()
void startDescTableTitle ()
void endDescTableTitle ()
void startDescTableData ()
void endDescTableData ()
void startDotGraph ()
void endDotGraph (DotClassGraph &g)
void startInclDepGraph ()
void endInclDepGraph (DotInclDepGraph &g)
void startCallGraph ()
void endCallGraph (DotCallGraph &g)
void startDirDepGraph ()
void endDirDepGraph (DotDirDeps &g)
void startGroupCollaboration ()
void endGroupCollaboration (DotGroupCollaboration &g)
void writeGraphicalHierarchy (DotGfxHierarchyTable &g)
void startTextBlock (bool dense=FALSE)
void endTextBlock (bool paraBreak=FALSE)
void lastIndexPage ()
void startMemberDocPrefixItem ()
void endMemberDocPrefixItem ()
void startMemberDocName (bool align)
void endMemberDocName ()
void startParameterType (bool first, const QCString &key)
void endParameterType ()
void startParameterName (bool one)
void endParameterName (bool last, bool one, bool bracket)
void startParameterList (bool openBracket)
void endParameterList ()
void exceptionEntry (const QCString &prefix, bool closeBracket)
void startConstraintList (const QCString &header)
void startConstraintParam ()
void endConstraintParam ()
void startConstraintType ()
void endConstraintType ()
void startConstraintDocs ()
void endConstraintDocs ()
void endConstraintList ()
void startMemberDocSimple (bool b)
void endMemberDocSimple (bool b)
void startInlineMemberType ()
void endInlineMemberType ()
void startInlineMemberName ()
void endInlineMemberName ()
void startInlineMemberDoc ()
void endInlineMemberDoc ()
void startLabels ()
void writeLabel (const QCString &l, bool isLast)
void endLabels ()
void cleanup ()
void startFontClass (const QCString &c)
void endFontClass ()
void writeCodeAnchor (const QCString &name)
void setCurrentDoc (const Definition *context, const QCString &anchor, bool isSourceFile)
void addWord (const QCString &word, bool hiPriority)
void indexSearchData ()
void startPlainFile (const QCString &name)
void endPlainFile ()
Private Member Functions
void debug ()
void clear ()
void newId ()
template<typename T , class... Ts, class... As>
void forall (void(T::*methodPtr)(Ts...), As &&... args)
void debug ()
void clear ()
void newId ()
template<typename T , class... Ts, class... As>
void forall (void(T::*methodPtr)(Ts...), As &&... args)
Private Attributes
std::vector< std::unique_ptr< OutputGenerator > > m_outputs
int m_id
SIDataCollection m_searchData
Additional Inherited Members
Detailed Description
Class representing a list of output generators that are written to in parallel.
Definition at line 37 of file outputlist.h.
Constructor & Destructor Documentation
OutputList() [1/4]
OutputList::OutputList ()
Definition at line 38 of file outputlist.cpp.
{
  newId();
  //printf("OutputList::OutputList()\n");
}
References newId().
OutputList() [2/4]
OutputList::OutputList (const OutputList & ol)
Definition at line 44 of file outputlist.cpp.
{
  m_id = ol.m_id;
  for (const auto &og : ol.m_outputs)
  {
    m_outputs.emplace_back(og->clone());
  }
}
References m_id, and m_outputs.
 OutputList() [1/2]
OutputList::~OutputList () [virtual]
Definition at line 66 of file outputlist.cpp.
{
  //printf("OutputList::~OutputList()\n");
}
OutputList() [3/4]
OutputList::OutputList ()
OutputList() [4/4]
OutputList::OutputList (const OutputList & ol)
 OutputList() [2/2]
virtual OutputList::~OutputList () [virtual]
Member Function Documentation
add() [1/2]
template<class Generator >
void OutputList::add () [inline]
Definition at line 46 of file outputlist.h.
    {
      m_outputs.emplace_back(std::make_unique<Generator>());
    }
References m_outputs.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), generateOutput(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
add() [2/2]
template<class Generator >
void OutputList::add () [inline]
Definition at line 46 of file outputlist.h.
    {
      m_outputs.emplace_back(std::make_unique<Generator>());
    }
References m_outputs.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
addIndexItem() [1/2]
void OutputList::addIndexItem (const QCString & s1, const QCString & s2) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 335 of file outputlist.h.
    { forall(&OutputGenerator::addIndexItem,s1,s2); }
References BaseOutputDocInterface::addIndexItem(), and forall().
Referenced by MemberDefImpl::_writeEnumValues(), and ClassDefImpl::writeInlineDocumentation().
addIndexItem() [2/2]
void OutputList::addIndexItem (const QCString & s1, const QCString & s2) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 335 of file outputlist.h.
    { forall(&OutputGenerator::addIndexItem,s1,s2); }
References BaseOutputDocInterface::addIndexItem(), and forall().
addWord() [1/2]
void OutputList::addWord (const QCString & word, bool hiPriority) [inline], [virtual]
Reimplemented from CodeOutputInterface.
Definition at line 493 of file outputlist.h.
    { /*forall(&OutputGenerator::addWord,word,hiPriority);*/
      m_searchData.addWord(word,hiPriority);
    }
References SIDataCollection::addWord(), m_searchData, and word.
addWord() [2/2]
void OutputList::addWord (const QCString & word, bool hiPriority) [inline], [virtual]
Reimplemented from CodeOutputInterface.
Definition at line 493 of file outputlist.h.
    { /*forall(&OutputGenerator::addWord,word,hiPriority);*/
      m_searchData.addWord(word,hiPriority);
    }
References SIDataCollection::addWord(), m_searchData, and word.
cleanup() [1/2]
void OutputList::cleanup () [inline]
Definition at line 479 of file outputlist.h.
    { forall(&OutputGenerator::cleanup); }
References OutputGenerator::cleanup(), and forall().
Referenced by generateOutput().
cleanup() [2/2]
void OutputList::cleanup () [inline]
Definition at line 479 of file outputlist.h.
    { forall(&OutputGenerator::cleanup); }
References OutputGenerator::cleanup(), and forall().
clear() [1/2]
void OutputList::clear () [private]
clear() [2/2]
void OutputList::clear () [private]
codify() [1/2]
void OutputList::codify (const QCString & s) [inline], [virtual]
Writes an code fragment to the output. This function should keep spaces visible, should break lines at a newline and should convert tabs to the right number of spaces.
Implements CodeOutputInterface.
Definition at line 139 of file outputlist.h.
    { forall(&OutputGenerator::codify,s); }
References CodeOutputInterface::codify(), forall(), and s.
codify() [2/2]
void OutputList::codify (const QCString & s) [inline], [virtual]
Writes an code fragment to the output. This function should keep spaces visible, should break lines at a newline and should convert tabs to the right number of spaces.
Implements CodeOutputInterface.
Definition at line 139 of file outputlist.h.
    { forall(&OutputGenerator::codify,s); }
References CodeOutputInterface::codify(), forall(), and s.
debug() [1/2]
void OutputList::debug () [private]
debug() [2/2]
void OutputList::debug () [private]
disable() [1/2]
void OutputList::disable (OutputGenerator::OutputType o)
Definition at line 100 of file outputlist.cpp.
{
  for (const auto &og : m_outputs)
  {
    og->disableIf(o);
  }
}
References m_outputs.
Referenced by MemberDefImpl::_writeCallerGraph(), MemberDefImpl::_writeCallGraph(), endIndexHierarchy(), generateExampleDocs(), ClassDefImpl::showUsedFiles(), startIndexHierarchy(), FileDefImpl::startMemberDocumentation(), GroupDefImpl::startMemberDocumentation(), NamespaceDefImpl::startMemberDocumentation(), ClassDefImpl::startMemberDocumentation(), startTitle(), writeAnnotatedClassList(), writeAnnotatedIndexGeneric(), ConceptDefImpl::writeBriefDescription(), DirDefImpl::writeBriefDescription(), FileDefImpl::writeBriefDescription(), GroupDefImpl::writeBriefDescription(), NamespaceDefImpl::writeBriefDescription(), ClassDefImpl::writeBriefDescription(), writeClassHierarchy(), ClassDefImpl::writeCollaborationGraph(), writeConceptIndex(), MemberDefImpl::writeDeclaration(), writeDefArgumentList(), ClassDefImpl::writeDetailedDescription(), DirDefImpl::writeDetailedDescription(), FileDefImpl::writeDetailedDescription(), GroupDefImpl::writeDetailedDescription(), NamespaceDefImpl::writeDetailedDescription(), ConceptDefImpl::writeDetailedDescription(), ClassDefImpl::writeDetailedDocumentationBody(), DirDefImpl::writeDirectoryGraph(), writeDirHierarchy(), MemberDefImpl::writeDocumentation(), DirDefImpl::writeDocumentation(), FileDefImpl::writeDocumentation(), GroupDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), MemberList::writeDocumentation(), MemberDefImpl::writeEnumDeclaration(), writeExampleIndex(), writeExamples(), writeFileIndex(), VhdlDocGen::writeFuncProcDocu(), GroupDefImpl::writeGroupGraph(), writeGroupHierarchy(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), FileDefImpl::writeIncludedByGraph(), FileDefImpl::writeIncludeFiles(), ClassDefImpl::writeIncludeFiles(), ConceptDefImpl::writeIncludeFiles(), FileDefImpl::writeIncludeGraph(), writeIndex(), ClassDefImpl::writeInheritanceGraph(), FileDefImpl::writeInlineClasses(), VhdlDocGen::writeInlineClassLink(), ClassDefImpl::writeInlineDocumentation(), MemberDefImpl::writeMemberDocSimple(), ClassDefImpl::writeMoreLink(), writeNamespaceIndex(), writePageRef(), FileDefImpl::writeSourceHeader(), and VhdlDocGen::writeVHDLDeclaration().
disable() [2/2]
void OutputList::disable (OutputGenerator::OutputType o)
disableAll() [1/2]
void OutputList::disableAll ()
Definition at line 92 of file outputlist.cpp.
{
  for (const auto &og : m_outputs)
  {
    og->disable();
  }
}
References m_outputs.
Referenced by MemberDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), and PageDefImpl::writePageDocumentation().
disableAll() [2/2]
void OutputList::disableAll ()
disableAllBut() [1/2]
void OutputList::disableAllBut (OutputGenerator::OutputType o)
Definition at line 76 of file outputlist.cpp.
{
  for (const auto &og : m_outputs)
  {
    og->disableIfNot(o);
  }
}
References m_outputs.
Referenced by MemberDefImpl::_writeEnumValues(), ClassDefImpl::addClassAttributes(), NamespaceDefImpl::addNamespaceAttributes(), endFile(), endFileWithNavPath(), generateDirDocs(), recursivelyAddGroupListToTitle(), ClassDefImpl::showUsedFiles(), writeAlphabeticalExceptionIndex(), writeAlphabeticalIndex(), writeAlphabeticalInterfaceIndex(), writeAlphabeticalStructIndex(), writeAnnotatedIndexGeneric(), FileDefImpl::writeAuthorSection(), GroupDefImpl::writeAuthorSection(), NamespaceDefImpl::writeAuthorSection(), ClassDefImpl::writeAuthorSection(), ConceptDefImpl::writeAuthorSection(), ConceptDefImpl::writeBriefDescription(), DirDefImpl::writeBriefDescription(), FileDefImpl::writeBriefDescription(), GroupDefImpl::writeBriefDescription(), NamespaceDefImpl::writeBriefDescription(), ClassDefImpl::writeBriefDescription(), writeClassMemberIndexFiltered(), writeConceptIndex(), MemberDefImpl::writeDeclaration(), MemberList::writeDeclarations(), ClassDefImpl::writeDetailedDescription(), DirDefImpl::writeDetailedDescription(), FileDefImpl::writeDetailedDescription(), GroupDefImpl::writeDetailedDescription(), NamespaceDefImpl::writeDetailedDescription(), ConceptDefImpl::writeDetailedDescription(), DirDefImpl::writeDocumentation(), DirRelation::writeDocumentation(), FileDefImpl::writeDocumentation(), GroupDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), MemberDefImpl::writeEnumDeclaration(), writeFileIndex(), DirDefImpl::writeFileList(), writeFileMemberIndexFiltered(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeGraphInfo(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), FileDefImpl::writeIncludeFiles(), ClassDefImpl::writeIncludeFiles(), ConceptDefImpl::writeIncludeFiles(), writeIndex(), ClassDefImpl::writeInheritanceGraph(), ClassDefImpl::writeInheritedMemberDeclarations(), ClassDefImpl::writeInlineDocumentation(), ClassDefImpl::writeMemberList(), FileDefImpl::writeMemberPages(), GroupDefImpl::writeMemberPages(), NamespaceDefImpl::writeMemberPages(), ClassDefImpl::writeMemberPages(), ClassDefImpl::writeMoreLink(), writeNamespaceIndex(), writeNamespaceMemberIndexFiltered(), DefinitionImpl::writeNavigationPath(), PageDefImpl::writePageDocumentation(), writePageIndex(), MemberList::writePlainDeclarations(), writeSingleFileIndex(), FileDefImpl::writeSourceLink(), ClassDefImpl::writeSummaryLinks(), FileDefImpl::writeSummaryLinks(), GroupDefImpl::writeSummaryLinks(), NamespaceDefImpl::writeSummaryLinks(), DefinitionImpl::writeToc(), writeUserGroupStubPage(), and VhdlDocGen::writeVHDLDeclaration().
disableAllBut() [2/2]
void OutputList::disableAllBut (OutputGenerator::OutputType o)
docify() [1/2]
void OutputList::docify (const QCString & s) [inline], [virtual]
Writes an ASCII string to the output. Converts characters that have A special meaning, like & in html.
Implements BaseOutputDocInterface.
Definition at line 137 of file outputlist.h.
    { forall(&OutputGenerator::docify,s); }
References BaseOutputDocInterface::docify(), forall(), and s.
Referenced by MemberDefImpl::_writeEnumValues(), MemberDefImpl::_writeGroupInclude(), DefinitionImpl::_writeSourceRefList(), MemberDefImpl::_writeTemplatePrefix(), generateExampleDocs(), generateFileRef(), generateLink(), ClassDefImpl::showUsedFiles(), startFonts(), writeAlphabeticalClassList(), writeAnnotatedClassList(), NamespaceDefImpl::writeBriefDescription(), writeClassTreeForList(), writeClassTreeToOutput(), MemberDefImpl::writeDeclaration(), ClassDefImpl::writeDeclaration(), NamespaceLinkedRefMap::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), ConceptDefImpl::writeDeclarationLink(), writeDefArgumentList(), writeDirTreeNode(), MemberDefImpl::writeDocumentation(), FileDefImpl::writeDocumentation(), MemberDefImpl::writeEnumDeclaration(), writeExceptionListImpl(), DirDefImpl::writeFileList(), GroupDefImpl::writeFiles(), VhdlDocGen::writeFormatString(), VhdlDocGen::writeFuncProcDocu(), VhdlDocGen::writeFunctionProto(), writeGroupTreeNode(), FileDefImpl::writeIncludeFiles(), ClassDefImpl::writeIncludeFiles(), ConceptDefImpl::writeIncludeFiles(), ClassDefImpl::writeIncludeFilesForSlice(), ClassDefImpl::writeInheritanceGraph(), writeInheritanceSpecifier(), MemberDefImpl::writeLink(), MemberDefImpl::writeMemberDocSimple(), ClassDefImpl::writeMemberList(), writeMemberList(), ClassDefImpl::writeMoreLink(), GroupDefImpl::writePageDocumentation(), writePageRef(), writePartialFilePath(), MemberList::writePlainDeclarations(), VhdlDocGen::writeProcedureProto(), VhdlDocGen::writeProcessProto(), writeSingleFileIndex(), VhdlDocGen::writeStringLink(), ClassDefImpl::writeTemplateSpec(), writeUCFLink(), VhdlDocGen::writeVHDLDeclaration(), VhdlDocGen::writeVHDLDeclarations(), VhdlDocGen::writeVhdlLink(), and VhdlDocGen::writeVHDLTypeDocumentation().
docify() [2/2]
void OutputList::docify (const QCString & s) [inline], [virtual]
Writes an ASCII string to the output. Converts characters that have A special meaning, like & in html.
Implements BaseOutputDocInterface.
Definition at line 137 of file outputlist.h.
    { forall(&OutputGenerator::docify,s); }
References BaseOutputDocInterface::docify(), forall(), and s.
enable() [1/2]
void OutputList::enable (OutputGenerator::OutputType o)
Definition at line 108 of file outputlist.cpp.
{
  for (const auto &og : m_outputs)
  {
    og->enableIf(o);
  }
}
References m_outputs.
Referenced by FileDefImpl::endMemberDocumentation(), NamespaceDefImpl::endMemberDocumentation(), ClassDefImpl::endMemberDocumentation(), generateExampleDocs(), ClassDefImpl::showUsedFiles(), ConceptDefImpl::writeBriefDescription(), DirDefImpl::writeBriefDescription(), FileDefImpl::writeBriefDescription(), GroupDefImpl::writeBriefDescription(), NamespaceDefImpl::writeBriefDescription(), ClassDefImpl::writeBriefDescription(), MemberDefImpl::writeDeclaration(), writeDefArgumentList(), DirDefImpl::writeDetailedDescription(), FileDefImpl::writeDetailedDescription(), GroupDefImpl::writeDetailedDescription(), NamespaceDefImpl::writeDetailedDescription(), MemberDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), MemberDefImpl::writeEnumDeclaration(), VhdlDocGen::writeFuncProcDocu(), writeHierarchicalExceptionIndex(), writeHierarchicalInterfaceIndex(), ClassDefImpl::writeIncludeFiles(), ConceptDefImpl::writeIncludeFiles(), writeIndex(), ClassDefImpl::writeInheritanceGraph(), FileDefImpl::writeInlineClasses(), VhdlDocGen::writeInlineClassLink(), MemberDefImpl::writeMemberDocSimple(), PageDefImpl::writePageDocumentation(), and VhdlDocGen::writeVHDLDeclaration().
enable() [2/2]
void OutputList::enable (OutputGenerator::OutputType o)
enableAll() [1/2]
void OutputList::enableAll ()
Definition at line 84 of file outputlist.cpp.
{
  for (const auto &og : m_outputs)
  {
    og->enable();
  }
}
References m_outputs.
Referenced by MemberDefImpl::_writeCallerGraph(), MemberDefImpl::_writeCallGraph(), MemberDefImpl::_writeEnumValues(), writeDefArgumentList(), DirDefImpl::writeDetailedDescription(), FileDefImpl::writeDetailedDescription(), GroupDefImpl::writeDetailedDescription(), NamespaceDefImpl::writeDetailedDescription(), DirDefImpl::writeDirectoryGraph(), DirDefImpl::writeDocumentation(), FileDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), VhdlDocGen::writeFuncProcDocu(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), FileDefImpl::writeIncludedByGraph(), FileDefImpl::writeIncludeFiles(), FileDefImpl::writeIncludeGraph(), ClassDefImpl::writeInheritanceGraph(), MemberList::writePlainDeclarations(), FileDefImpl::writeSourceFooter(), and FileDefImpl::writeSourceLink().
enableAll() [2/2]
void OutputList::enableAll ()
endAnonTypeScope() [1/2]
void OutputList::endAnonTypeScope (int i1) [inline]
Definition at line 207 of file outputlist.h.
    { forall(&OutputGenerator::endAnonTypeScope,i1); }
References OutputGenerator::endAnonTypeScope(), and forall().
Referenced by MemberDefImpl::writeDeclaration().
endAnonTypeScope() [2/2]
void OutputList::endAnonTypeScope (int i1) [inline]
Definition at line 207 of file outputlist.h.
    { forall(&OutputGenerator::endAnonTypeScope,i1); }
References OutputGenerator::endAnonTypeScope(), and forall().
endBold() [1/2]
void OutputList::endBold () [inline], [virtual]
End a section of text displayed in bold face.
Implements BaseOutputDocInterface.
Definition at line 304 of file outputlist.h.
    { forall(&OutputGenerator::endBold); }
References BaseOutputDocInterface::endBold(), and forall().
Referenced by MemberDefImpl::_writeMultiLineInitializer(), VhdlDocGen::writeClassType(), ClassDefImpl::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), ConceptDefImpl::writeDeclarationLink(), MemberDefImpl::writeEnumDeclaration(), DirDefImpl::writeFileList(), VhdlDocGen::writeFormatString(), VhdlDocGen::writeFunctionProto(), MemberDefImpl::writeLink(), ClassDefImpl::writeMemberList(), writePartialFilePath(), VhdlDocGen::writeProcedureProto(), VhdlDocGen::writeProcessProto(), VhdlDocGen::writeRecordUnit(), VhdlDocGen::writeStringLink(), VhdlDocGen::writeVHDLDeclaration(), VhdlDocGen::writeVhdlLink(), and VhdlDocGen::writeVHDLTypeDocumentation().
endBold() [2/2]
void OutputList::endBold () [inline], [virtual]
End a section of text displayed in bold face.
Implements BaseOutputDocInterface.
Definition at line 304 of file outputlist.h.
    { forall(&OutputGenerator::endBold); }
References BaseOutputDocInterface::endBold(), and forall().
endCallGraph() [1/2]
void OutputList::endCallGraph (DotCallGraph & g) [inline]
Definition at line 397 of file outputlist.h.
    { forall(&OutputGenerator::endCallGraph,g); }
References OutputGenerator::endCallGraph(), forall(), and g.
Referenced by MemberDefImpl::_writeCallerGraph(), and MemberDefImpl::_writeCallGraph().
endCallGraph() [2/2]
void OutputList::endCallGraph (DotCallGraph & g) [inline]
Definition at line 397 of file outputlist.h.
    { forall(&OutputGenerator::endCallGraph,g); }
References OutputGenerator::endCallGraph(), forall(), and g.
endCenter() [1/2]
void OutputList::endCenter () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 294 of file outputlist.h.
    { forall(&OutputGenerator::endCenter); }
References BaseOutputDocInterface::endCenter(), and forall().
endCenter() [2/2]
void OutputList::endCenter () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 294 of file outputlist.h.
    { forall(&OutputGenerator::endCenter); }
References BaseOutputDocInterface::endCenter(), and forall().
endClassDiagram() [1/2]
void OutputList::endClassDiagram (const ClassDiagram & d, const QCString & f, const QCString & n) [inline]
Definition at line 341 of file outputlist.h.
    { forall(&OutputGenerator::endClassDiagram,d,f,n); }
References OutputGenerator::endClassDiagram(), f, forall(), and n.
Referenced by ClassDefImpl::writeInheritanceGraph().
endClassDiagram() [2/2]
void OutputList::endClassDiagram (const ClassDiagram & d, const QCString & f, const QCString & n) [inline]
Definition at line 341 of file outputlist.h.
    { forall(&OutputGenerator::endClassDiagram,d,f,n); }
References OutputGenerator::endClassDiagram(), f, forall(), and n.
endCodeFragment() [1/2]
void OutputList::endCodeFragment (const QCString & style) [inline], [virtual]
Ends a block of code
Implements CodeOutputInterface.
Definition at line 243 of file outputlist.h.
    { forall(&OutputGenerator::endCodeFragment,style); }
References CodeOutputInterface::endCodeFragment(), forall(), and style.
Referenced by MemberDefImpl::_writeMultiLineInitializer(), ConceptDefImpl::writeDefinition(), DefinitionImpl::writeInlineCode(), VhdlDocGen::writeSource(), and FileDefImpl::writeSourceBody().
endCodeFragment() [2/2]
void OutputList::endCodeFragment (const QCString & style) [inline], [virtual]
Ends a block of code
Implements CodeOutputInterface.
Definition at line 243 of file outputlist.h.
    { forall(&OutputGenerator::endCodeFragment,style); }
References CodeOutputInterface::endCodeFragment(), forall(), and style.
endCodeLine() [1/2]
void OutputList::endCodeLine () [inline], [virtual]
Ends a line of code started with startCodeLine()
Implements CodeOutputInterface.
Definition at line 247 of file outputlist.h.
    { forall(&OutputGenerator::endCodeLine); }
References CodeOutputInterface::endCodeLine(), and forall().
endCodeLine() [2/2]
void OutputList::endCodeLine () [inline], [virtual]
Ends a line of code started with startCodeLine()
Implements CodeOutputInterface.
Definition at line 247 of file outputlist.h.
    { forall(&OutputGenerator::endCodeLine); }
References CodeOutputInterface::endCodeLine(), and forall().
endCompoundTemplateParams() [1/2]
void OutputList::endCompoundTemplateParams () [inline]
Definition at line 219 of file outputlist.h.
    { forall(&OutputGenerator::endCompoundTemplateParams); }
References OutputGenerator::endCompoundTemplateParams(), and forall().
Referenced by ClassDefImpl::writeTemplateSpec().
endCompoundTemplateParams() [2/2]
void OutputList::endCompoundTemplateParams () [inline]
Definition at line 219 of file outputlist.h.
    { forall(&OutputGenerator::endCompoundTemplateParams); }
References OutputGenerator::endCompoundTemplateParams(), and forall().
endConstraintDocs() [1/2]
void OutputList::endConstraintDocs () [inline]
Definition at line 450 of file outputlist.h.
    { forall(&OutputGenerator::endConstraintDocs); }
References OutputGenerator::endConstraintDocs(), and forall().
Referenced by writeTypeConstraints().
endConstraintDocs() [2/2]
void OutputList::endConstraintDocs () [inline]
Definition at line 450 of file outputlist.h.
    { forall(&OutputGenerator::endConstraintDocs); }
References OutputGenerator::endConstraintDocs(), and forall().
endConstraintList() [1/2]
void OutputList::endConstraintList () [inline]
Definition at line 452 of file outputlist.h.
    { forall(&OutputGenerator::endConstraintList); }
References OutputGenerator::endConstraintList(), and forall().
Referenced by writeTypeConstraints().
endConstraintList() [2/2]
void OutputList::endConstraintList () [inline]
Definition at line 452 of file outputlist.h.
    { forall(&OutputGenerator::endConstraintList); }
References OutputGenerator::endConstraintList(), and forall().
endConstraintParam() [1/2]
void OutputList::endConstraintParam () [inline]
Definition at line 442 of file outputlist.h.
    { forall(&OutputGenerator::endConstraintParam); }
References OutputGenerator::endConstraintParam(), and forall().
Referenced by writeTypeConstraints().
endConstraintParam() [2/2]
void OutputList::endConstraintParam () [inline]
Definition at line 442 of file outputlist.h.
    { forall(&OutputGenerator::endConstraintParam); }
References OutputGenerator::endConstraintParam(), and forall().
endConstraintType() [1/2]
void OutputList::endConstraintType () [inline]
Definition at line 446 of file outputlist.h.
    { forall(&OutputGenerator::endConstraintType); }
References OutputGenerator::endConstraintType(), and forall().
Referenced by writeTypeConstraints().
endConstraintType() [2/2]
void OutputList::endConstraintType () [inline]
Definition at line 446 of file outputlist.h.
    { forall(&OutputGenerator::endConstraintType); }
References OutputGenerator::endConstraintType(), and forall().
endContents() [1/2]
void OutputList::endContents () [inline]
Definition at line 363 of file outputlist.h.
    { forall(&OutputGenerator::endContents); }
References OutputGenerator::endContents(), and forall().
Referenced by endFile(), ConceptDefImpl::writeDocumentation(), DirDefImpl::writeDocumentation(), DirRelation::writeDocumentation(), FileDefImpl::writeDocumentation(), NamespaceDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), ClassDefImpl::writeDocumentationContents(), MemberList::writeDocumentationPage(), and FileDefImpl::writeSourceFooter().
endContents() [2/2]
void OutputList::endContents () [inline]
Definition at line 363 of file outputlist.h.
    { forall(&OutputGenerator::endContents); }
References OutputGenerator::endContents(), and forall().
endDescForItem() [1/2]
void OutputList::endDescForItem () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 282 of file outputlist.h.
    { forall(&OutputGenerator::endDescForItem); }
References BaseOutputDocInterface::endDescForItem(), and forall().
Referenced by MemberDefImpl::_writeExamples(), and ClassDefImpl::writeDetailedDocumentationBody().
endDescForItem() [2/2]
void OutputList::endDescForItem () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 282 of file outputlist.h.
    { forall(&OutputGenerator::endDescForItem); }
References BaseOutputDocInterface::endDescForItem(), and forall().
endDescItem() [1/2]
void OutputList::endDescItem () [inline], [virtual]
Ends an item of a description list and starts the description itself: e.g. </dt> in HTML.
Implements BaseOutputDocInterface.
Definition at line 278 of file outputlist.h.
    { forall(&OutputGenerator::endDescItem); }
References BaseOutputDocInterface::endDescItem(), and forall().
endDescItem() [2/2]
void OutputList::endDescItem () [inline], [virtual]
Ends an item of a description list and starts the description itself: e.g. </dt> in HTML.
Implements BaseOutputDocInterface.
Definition at line 278 of file outputlist.h.
    { forall(&OutputGenerator::endDescItem); }
References BaseOutputDocInterface::endDescItem(), and forall().
endDescription() [1/2]
void OutputList::endDescription () [inline], [virtual]
Ends a description list: e.g. </dl> in HTML
Implements BaseOutputDocInterface.
Definition at line 274 of file outputlist.h.
    { forall(&OutputGenerator::endDescription); }
References BaseOutputDocInterface::endDescription(), and forall().
endDescription() [2/2]
void OutputList::endDescription () [inline], [virtual]
Ends a description list: e.g. </dl> in HTML
Implements BaseOutputDocInterface.
Definition at line 274 of file outputlist.h.
    { forall(&OutputGenerator::endDescription); }
References BaseOutputDocInterface::endDescription(), and forall().
endDescTable() [1/2]
void OutputList::endDescTable () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 373 of file outputlist.h.
    { forall(&OutputGenerator::endDescTable); }
References BaseOutputDocInterface::endDescTable(), and forall().
Referenced by MemberDefImpl::_writeEnumValues().
endDescTable() [2/2]
void OutputList::endDescTable () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 373 of file outputlist.h.
    { forall(&OutputGenerator::endDescTable); }
References BaseOutputDocInterface::endDescTable(), and forall().
endDescTableData() [1/2]
void OutputList::endDescTableData () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 385 of file outputlist.h.
    { forall(&OutputGenerator::endDescTableData); }
References BaseOutputDocInterface::endDescTableData(), and forall().
Referenced by MemberDefImpl::_writeEnumValues().
endDescTableData() [2/2]
void OutputList::endDescTableData () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 385 of file outputlist.h.
    { forall(&OutputGenerator::endDescTableData); }
References BaseOutputDocInterface::endDescTableData(), and forall().
endDescTableRow() [1/2]
void OutputList::endDescTableRow () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 377 of file outputlist.h.
    { forall(&OutputGenerator::endDescTableRow); }
References BaseOutputDocInterface::endDescTableRow(), and forall().
Referenced by MemberDefImpl::_writeEnumValues().
endDescTableRow() [2/2]
void OutputList::endDescTableRow () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 377 of file outputlist.h.
    { forall(&OutputGenerator::endDescTableRow); }
References BaseOutputDocInterface::endDescTableRow(), and forall().
endDescTableTitle() [1/2]
void OutputList::endDescTableTitle () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 381 of file outputlist.h.
    { forall(&OutputGenerator::endDescTableTitle); }
References BaseOutputDocInterface::endDescTableTitle(), and forall().
Referenced by MemberDefImpl::_writeEnumValues().
endDescTableTitle() [2/2]
void OutputList::endDescTableTitle () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 381 of file outputlist.h.
    { forall(&OutputGenerator::endDescTableTitle); }
References BaseOutputDocInterface::endDescTableTitle(), and forall().
endDirDepGraph() [1/2]
void OutputList::endDirDepGraph (DotDirDeps & g) [inline]
Definition at line 401 of file outputlist.h.
    { forall(&OutputGenerator::endDirDepGraph,g); }
References OutputGenerator::endDirDepGraph(), forall(), and g.
Referenced by DirDefImpl::writeDirectoryGraph().
endDirDepGraph() [2/2]
void OutputList::endDirDepGraph (DotDirDeps & g) [inline]
Definition at line 401 of file outputlist.h.
    { forall(&OutputGenerator::endDirDepGraph,g); }
References OutputGenerator::endDirDepGraph(), forall(), and g.
endDotGraph() [1/2]
void OutputList::endDotGraph (DotClassGraph & g) [inline]
Definition at line 389 of file outputlist.h.
    { forall(&OutputGenerator::endDotGraph,g); }
References OutputGenerator::endDotGraph(), forall(), and g.
Referenced by ClassDefImpl::writeCollaborationGraph(), and ClassDefImpl::writeInheritanceGraph().
endDotGraph() [2/2]
void OutputList::endDotGraph (DotClassGraph & g) [inline]
Definition at line 389 of file outputlist.h.
    { forall(&OutputGenerator::endDotGraph,g); }
References OutputGenerator::endDotGraph(), forall(), and g.
endDoxyAnchor() [1/2]
void OutputList::endDoxyAnchor (const QCString & fn, const QCString & anchor) [inline]
Definition at line 268 of file outputlist.h.
    { forall(&OutputGenerator::endDoxyAnchor,fn,anchor); }
References OutputGenerator::endDoxyAnchor(), and forall().
Referenced by MemberDefImpl::_writeEnumValues(), MemberDefImpl::writeDeclaration(), MemberDefImpl::writeDocumentation(), MemberDefImpl::writeMemberDocSimple(), MemberList::writePlainDeclarations(), and VhdlDocGen::writeVHDLDeclaration().
endDoxyAnchor() [2/2]
void OutputList::endDoxyAnchor (const QCString & fn, const QCString & anchor) [inline]
Definition at line 268 of file outputlist.h.
    { forall(&OutputGenerator::endDoxyAnchor,fn,anchor); }
References OutputGenerator::endDoxyAnchor(), and forall().
endEmphasis() [1/2]
void OutputList::endEmphasis () [inline], [virtual]
Ends a section of text displayed in italic.
Implements BaseOutputDocInterface.
Definition at line 254 of file outputlist.h.
    { forall(&OutputGenerator::endEmphasis); }
References BaseOutputDocInterface::endEmphasis(), and forall().
Referenced by writeDefArgumentList(), VhdlDocGen::writeFuncProcDocu(), and VhdlDocGen::writeVHDLDeclaration().
endEmphasis() [2/2]
void OutputList::endEmphasis () [inline], [virtual]
Ends a section of text displayed in italic.
Implements BaseOutputDocInterface.
Definition at line 254 of file outputlist.h.
    { forall(&OutputGenerator::endEmphasis); }
References BaseOutputDocInterface::endEmphasis(), and forall().
endExamples() [1/2]
void OutputList::endExamples () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 321 of file outputlist.h.
    { forall(&OutputGenerator::endExamples); }
References BaseOutputDocInterface::endExamples(), and forall().
Referenced by MemberDefImpl::_writeExamples(), and ClassDefImpl::writeDetailedDocumentationBody().
endExamples() [2/2]
void OutputList::endExamples () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 321 of file outputlist.h.
    { forall(&OutputGenerator::endExamples); }
References BaseOutputDocInterface::endExamples(), and forall().
endFile() [1/2]
void OutputList::endFile () [inline]
Definition at line 97 of file outputlist.h.
    { forall(&OutputGenerator::endFile); }
References OutputGenerator::endFile(), and forall().
Referenced by endFile().
endFile() [2/2]
void OutputList::endFile () [inline]
Definition at line 97 of file outputlist.h.
    { forall(&OutputGenerator::endFile); }
References OutputGenerator::endFile(), and forall().
endFontClass() [1/2]
void OutputList::endFontClass () [inline], [virtual]
Ends a block started with startFontClass()
Implements CodeOutputInterface.
Definition at line 484 of file outputlist.h.
    { forall(&OutputGenerator::endFontClass); }
References CodeOutputInterface::endFontClass(), and forall().
Referenced by startFonts().
endFontClass() [2/2]
void OutputList::endFontClass () [inline], [virtual]
Ends a block started with startFontClass()
Implements CodeOutputInterface.
Definition at line 484 of file outputlist.h.
    { forall(&OutputGenerator::endFontClass); }
References CodeOutputInterface::endFontClass(), and forall().
endGroupCollaboration() [1/2]
void OutputList::endGroupCollaboration (DotGroupCollaboration & g) [inline]
Definition at line 405 of file outputlist.h.
    { forall(&OutputGenerator::endGroupCollaboration,g); }
References OutputGenerator::endGroupCollaboration(), forall(), and g.
Referenced by GroupDefImpl::writeGroupGraph().
endGroupCollaboration() [2/2]
void OutputList::endGroupCollaboration (DotGroupCollaboration & g) [inline]
Definition at line 405 of file outputlist.h.
    { forall(&OutputGenerator::endGroupCollaboration,g); }
References OutputGenerator::endGroupCollaboration(), forall(), and g.
endGroupHeader() [1/2]
void OutputList::endGroupHeader (int extraLevels = 0) [inline]
Definition at line 171 of file outputlist.h.
    { forall(&OutputGenerator::endGroupHeader,extraLevels); }
References OutputGenerator::endGroupHeader(), and forall().
Referenced by FileDefImpl::writeAuthorSection(), GroupDefImpl::writeAuthorSection(), NamespaceDefImpl::writeAuthorSection(), ClassDefImpl::writeAuthorSection(), ConceptDefImpl::writeAuthorSection(), ConceptDefImpl::writeDefinition(), ClassDefImpl::writeDetailedDescription(), DirDefImpl::writeDetailedDescription(), FileDefImpl::writeDetailedDescription(), GroupDefImpl::writeDetailedDescription(), NamespaceDefImpl::writeDetailedDescription(), ConceptDefImpl::writeDetailedDescription(), ClassLinkedRefMap::writeDocumentation(), MemberList::writeDocumentation(), and ClassDefImpl::writeInlineDocumentation().
endGroupHeader() [2/2]
void OutputList::endGroupHeader (int extraLevels = 0) [inline]
Definition at line 171 of file outputlist.h.
    { forall(&OutputGenerator::endGroupHeader,extraLevels); }
References OutputGenerator::endGroupHeader(), and forall().
endHeaderSection() [1/2]
void OutputList::endHeaderSection () [inline]
Definition at line 183 of file outputlist.h.
    { forall(&OutputGenerator::endHeaderSection); }
References OutputGenerator::endHeaderSection(), and forall().
Referenced by endTitle(), GroupDefImpl::writeDocumentation(), and writeIndex().
endHeaderSection() [2/2]
void OutputList::endHeaderSection () [inline]
Definition at line 183 of file outputlist.h.
    { forall(&OutputGenerator::endHeaderSection); }
References OutputGenerator::endHeaderSection(), and forall().
endHtmlLink() [1/2]
void OutputList::endHtmlLink () [inline], [virtual]
Ends a link started by startHtmlLink().
Implements BaseOutputDocInterface.
Definition at line 158 of file outputlist.h.
    { forall(&OutputGenerator::endHtmlLink); }
References BaseOutputDocInterface::endHtmlLink(), and forall().
endHtmlLink() [2/2]
void OutputList::endHtmlLink () [inline], [virtual]
Ends a link started by startHtmlLink().
Implements BaseOutputDocInterface.
Definition at line 158 of file outputlist.h.
    { forall(&OutputGenerator::endHtmlLink); }
References BaseOutputDocInterface::endHtmlLink(), and forall().
endInclDepGraph() [1/2]
void OutputList::endInclDepGraph (DotInclDepGraph & g) [inline]
Definition at line 393 of file outputlist.h.
    { forall(&OutputGenerator::endInclDepGraph,g); }
References OutputGenerator::endInclDepGraph(), forall(), and g.
Referenced by FileDefImpl::writeIncludedByGraph(), and FileDefImpl::writeIncludeGraph().
endInclDepGraph() [2/2]
void OutputList::endInclDepGraph (DotInclDepGraph & g) [inline]
Definition at line 393 of file outputlist.h.
    { forall(&OutputGenerator::endInclDepGraph,g); }
References OutputGenerator::endInclDepGraph(), forall(), and g.
endIndent() [1/2]
void OutputList::endIndent () [inline]
Definition at line 329 of file outputlist.h.
    { forall(&OutputGenerator::endIndent); }
References OutputGenerator::endIndent(), and forall().
Referenced by MemberDefImpl::writeDocumentation(), and ClassDefImpl::writeInlineDocumentation().
endIndent() [2/2]
void OutputList::endIndent () [inline]
Definition at line 329 of file outputlist.h.
    { forall(&OutputGenerator::endIndent); }
References OutputGenerator::endIndent(), and forall().
endIndexItem() [1/2]
void OutputList::endIndexItem (const QCString & ref, const QCString & file) [inline]
Definition at line 135 of file outputlist.h.
    { forall(&OutputGenerator::endIndexItem,ref,file); }
References OutputGenerator::endIndexItem(), caseconvert::file, and forall().
Referenced by writeClassTreeForList(), writeClassTreeToOutput(), writeDirTreeNode(), and writeGroupTreeNode().
endIndexItem() [2/2]
void OutputList::endIndexItem (const QCString & ref, const QCString & file) [inline]
Definition at line 135 of file outputlist.h.
    { forall(&OutputGenerator::endIndexItem,ref,file); }
References OutputGenerator::endIndexItem(), caseconvert::file, and forall().
endIndexKey() [1/2]
void OutputList::endIndexKey () [inline]
Definition at line 123 of file outputlist.h.
    { forall(&OutputGenerator::endIndexKey); }
References OutputGenerator::endIndexKey(), and forall().
Referenced by writeAnnotatedClassList(), writeConceptIndex(), writeNamespaceIndex(), and writeSingleFileIndex().
endIndexKey() [2/2]
void OutputList::endIndexKey () [inline]
Definition at line 123 of file outputlist.h.
    { forall(&OutputGenerator::endIndexKey); }
References OutputGenerator::endIndexKey(), and forall().
endIndexList() [1/2]
void OutputList::endIndexList () [inline]
Definition at line 119 of file outputlist.h.
    { forall(&OutputGenerator::endIndexList); }
References OutputGenerator::endIndexList(), and forall().
Referenced by endIndexHierarchy(), writeAnnotatedClassList(), writeConceptIndex(), writeFileIndex(), and writeNamespaceIndex().
endIndexList() [2/2]
void OutputList::endIndexList () [inline]
Definition at line 119 of file outputlist.h.
    { forall(&OutputGenerator::endIndexList); }
References OutputGenerator::endIndexList(), and forall().
endIndexListItem() [1/2]
void OutputList::endIndexListItem () [inline]
Definition at line 115 of file outputlist.h.
    { forall(&OutputGenerator::endIndexListItem); }
References OutputGenerator::endIndexListItem(), and forall().
Referenced by writeClassTreeForList(), writeClassTreeToOutput(), writeDirTreeNode(), and writeGroupTreeNode().
endIndexListItem() [2/2]
void OutputList::endIndexListItem () [inline]
Definition at line 115 of file outputlist.h.
    { forall(&OutputGenerator::endIndexListItem); }
References OutputGenerator::endIndexListItem(), and forall().
endIndexSection() [1/2]
void OutputList::endIndexSection (IndexSections is) [inline]
Definition at line 78 of file outputlist.h.
    { forall(&OutputGenerator::endIndexSection,is); }
References OutputGenerator::endIndexSection(), and forall().
Referenced by writeIndex().
endIndexSection() [2/2]
void OutputList::endIndexSection (IndexSections is) [inline]
Definition at line 78 of file outputlist.h.
    { forall(&OutputGenerator::endIndexSection,is); }
References OutputGenerator::endIndexSection(), and forall().
endIndexValue() [1/2]
void OutputList::endIndexValue (const QCString & name, bool b) [inline]
Definition at line 127 of file outputlist.h.
    { forall(&OutputGenerator::endIndexValue,name,b); }
References b, OutputGenerator::endIndexValue(), forall(), and setup::name.
Referenced by writeAnnotatedClassList(), writeConceptIndex(), writeNamespaceIndex(), and writeSingleFileIndex().
endIndexValue() [2/2]
void OutputList::endIndexValue (const QCString & name, bool b) [inline]
Definition at line 127 of file outputlist.h.
    { forall(&OutputGenerator::endIndexValue,name,b); }
References b, OutputGenerator::endIndexValue(), forall(), and setup::name.
endInlineHeader() [1/2]
void OutputList::endInlineHeader () [inline]
Definition at line 203 of file outputlist.h.
    { forall(&OutputGenerator::endInlineHeader); }
References OutputGenerator::endInlineHeader(), and forall().
Referenced by MemberList::writeDeclarations().
endInlineHeader() [2/2]
void OutputList::endInlineHeader () [inline]
Definition at line 203 of file outputlist.h.
    { forall(&OutputGenerator::endInlineHeader); }
References OutputGenerator::endInlineHeader(), and forall().
endInlineMemberDoc() [1/2]
void OutputList::endInlineMemberDoc () [inline]
Definition at line 469 of file outputlist.h.
    { forall(&OutputGenerator::endInlineMemberDoc); }
References OutputGenerator::endInlineMemberDoc(), and forall().
Referenced by MemberDefImpl::writeMemberDocSimple().
endInlineMemberDoc() [2/2]
void OutputList::endInlineMemberDoc () [inline]
Definition at line 469 of file outputlist.h.
    { forall(&OutputGenerator::endInlineMemberDoc); }
References OutputGenerator::endInlineMemberDoc(), and forall().
endInlineMemberName() [1/2]
void OutputList::endInlineMemberName () [inline]
Definition at line 465 of file outputlist.h.
    { forall(&OutputGenerator::endInlineMemberName); }
References OutputGenerator::endInlineMemberName(), and forall().
Referenced by MemberDefImpl::writeMemberDocSimple().
endInlineMemberName() [2/2]
void OutputList::endInlineMemberName () [inline]
Definition at line 465 of file outputlist.h.
    { forall(&OutputGenerator::endInlineMemberName); }
References OutputGenerator::endInlineMemberName(), and forall().
endInlineMemberType() [1/2]
void OutputList::endInlineMemberType () [inline]
Definition at line 461 of file outputlist.h.
    { forall(&OutputGenerator::endInlineMemberType); }
References OutputGenerator::endInlineMemberType(), and forall().
Referenced by MemberDefImpl::writeMemberDocSimple().
endInlineMemberType() [2/2]
void OutputList::endInlineMemberType () [inline]
Definition at line 461 of file outputlist.h.
    { forall(&OutputGenerator::endInlineMemberType); }
References OutputGenerator::endInlineMemberType(), and forall().
endItemList() [1/2]
void OutputList::endItemList () [inline], [virtual]
Ends a bullet list: e.g. </ul> in html
Implements BaseOutputDocInterface.
Definition at line 131 of file outputlist.h.
    { forall(&OutputGenerator::endItemList); }
References BaseOutputDocInterface::endItemList(), and forall().
Referenced by endIndexHierarchy(), ClassDefImpl::showUsedFiles(), writeExampleIndex(), and writeMemberList().
endItemList() [2/2]
void OutputList::endItemList () [inline], [virtual]
Ends a bullet list: e.g. </ul> in html
Implements BaseOutputDocInterface.
Definition at line 131 of file outputlist.h.
    { forall(&OutputGenerator::endItemList); }
References BaseOutputDocInterface::endItemList(), and forall().
endItemListItem() [1/2]
void OutputList::endItemListItem () [inline], [virtual]
Writes a list item for a bullet or enumerated list: e.g. </li> in html
Implements BaseOutputDocInterface.
Definition at line 175 of file outputlist.h.
    { forall(&OutputGenerator::endItemListItem); }
References BaseOutputDocInterface::endItemListItem(), and forall().
Referenced by ClassDefImpl::showUsedFiles(), writeExampleIndex(), and writeMemberList().
endItemListItem() [2/2]
void OutputList::endItemListItem () [inline], [virtual]
Writes a list item for a bullet or enumerated list: e.g. </li> in html
Implements BaseOutputDocInterface.
Definition at line 175 of file outputlist.h.
    { forall(&OutputGenerator::endItemListItem); }
References BaseOutputDocInterface::endItemListItem(), and forall().
endLabels() [1/2]
void OutputList::endLabels () [inline]
Definition at line 476 of file outputlist.h.
    { forall(&OutputGenerator::endLabels); }
References OutputGenerator::endLabels(), and forall().
Referenced by ClassDefImpl::addClassAttributes(), NamespaceDefImpl::addNamespaceAttributes(), and MemberDefImpl::writeDocumentation().
endLabels() [2/2]
void OutputList::endLabels () [inline]
Definition at line 476 of file outputlist.h.
    { forall(&OutputGenerator::endLabels); }
References OutputGenerator::endLabels(), and forall().
endMemberDeclaration() [1/2]
void OutputList::endMemberDeclaration (const QCString & anchor, const QCString & inheritId) [inline]
Definition at line 312 of file outputlist.h.
    { forall(&OutputGenerator::endMemberDeclaration,anchor,inheritId); }
References OutputGenerator::endMemberDeclaration(), and forall().
Referenced by MemberDefImpl::writeDeclaration(), NamespaceLinkedRefMap::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), ConceptDefImpl::writeDeclarationLink(), GroupDefImpl::writeDirs(), DirDefImpl::writeFileList(), GroupDefImpl::writeFiles(), GroupDefImpl::writeNestedGroups(), MemberList::writePlainDeclarations(), and DirDefImpl::writeSubDirList().
endMemberDeclaration() [2/2]
void OutputList::endMemberDeclaration (const QCString & anchor, const QCString & inheritId) [inline]
Definition at line 312 of file outputlist.h.
    { forall(&OutputGenerator::endMemberDeclaration,anchor,inheritId); }
References OutputGenerator::endMemberDeclaration(), and forall().
endMemberDescription() [1/2]
void OutputList::endMemberDescription () [inline]
Definition at line 308 of file outputlist.h.
    { forall(&OutputGenerator::endMemberDescription); }
References OutputGenerator::endMemberDescription(), and forall().
Referenced by MemberDefImpl::writeDeclaration(), NamespaceLinkedRefMap::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), ConceptDefImpl::writeDeclarationLink(), GroupDefImpl::writeDirs(), DirDefImpl::writeFileList(), GroupDefImpl::writeFiles(), GroupDefImpl::writeNestedGroups(), MemberList::writePlainDeclarations(), DirDefImpl::writeSubDirList(), and VhdlDocGen::writeVHDLDeclaration().
endMemberDescription() [2/2]
void OutputList::endMemberDescription () [inline]
Definition at line 308 of file outputlist.h.
    { forall(&OutputGenerator::endMemberDescription); }
References OutputGenerator::endMemberDescription(), and forall().
endMemberDoc() [1/2]
void OutputList::endMemberDoc (bool hasArgs) [inline]
Definition at line 262 of file outputlist.h.
    { forall(&OutputGenerator::endMemberDoc,hasArgs); }
References OutputGenerator::endMemberDoc(), and forall().
Referenced by MemberDefImpl::writeDocumentation(), and ClassDefImpl::writeInlineDocumentation().
endMemberDoc() [2/2]
void OutputList::endMemberDoc (bool hasArgs) [inline]
Definition at line 262 of file outputlist.h.
    { forall(&OutputGenerator::endMemberDoc,hasArgs); }
References OutputGenerator::endMemberDoc(), and forall().
endMemberDocList() [1/2]
void OutputList::endMemberDocList () [inline]
Definition at line 195 of file outputlist.h.
    { forall(&OutputGenerator::endMemberDocList); }
References OutputGenerator::endMemberDocList(), and forall().
Referenced by MemberList::writeDocumentation().
endMemberDocList() [2/2]
void OutputList::endMemberDocList () [inline]
Definition at line 195 of file outputlist.h.
    { forall(&OutputGenerator::endMemberDocList); }
References OutputGenerator::endMemberDocList(), and forall().
endMemberDocName() [1/2]
void OutputList::endMemberDocName () [inline]
Definition at line 421 of file outputlist.h.
    { forall(&OutputGenerator::endMemberDocName); }
References OutputGenerator::endMemberDocName(), and forall().
Referenced by writeDefArgumentList(), MemberDefImpl::writeDocumentation(), VhdlDocGen::writeFuncProcDocu(), and ClassDefImpl::writeInlineDocumentation().
endMemberDocName() [2/2]
void OutputList::endMemberDocName () [inline]
Definition at line 421 of file outputlist.h.
    { forall(&OutputGenerator::endMemberDocName); }
References OutputGenerator::endMemberDocName(), and forall().
endMemberDocPrefixItem() [1/2]
void OutputList::endMemberDocPrefixItem () [inline]
Definition at line 417 of file outputlist.h.
    { forall(&OutputGenerator::endMemberDocPrefixItem); }
References OutputGenerator::endMemberDocPrefixItem(), and forall().
Referenced by MemberDefImpl::writeDocumentation().
endMemberDocPrefixItem() [2/2]
void OutputList::endMemberDocPrefixItem () [inline]
Definition at line 417 of file outputlist.h.
    { forall(&OutputGenerator::endMemberDocPrefixItem); }
References OutputGenerator::endMemberDocPrefixItem(), and forall().
endMemberDocSimple() [1/2]
void OutputList::endMemberDocSimple (bool b) [inline]
Definition at line 457 of file outputlist.h.
    { forall(&OutputGenerator::endMemberDocSimple,b); }
References b, OutputGenerator::endMemberDocSimple(), and forall().
Referenced by MemberList::writeSimpleDocumentation().
endMemberDocSimple() [2/2]
void OutputList::endMemberDocSimple (bool b) [inline]
Definition at line 457 of file outputlist.h.
    { forall(&OutputGenerator::endMemberDocSimple,b); }
References b, OutputGenerator::endMemberDocSimple(), and forall().
endMemberGroup() [1/2]
void OutputList::endMemberGroup (bool last) [inline]
Definition at line 231 of file outputlist.h.
    { forall(&OutputGenerator::endMemberGroup,last); }
References OutputGenerator::endMemberGroup(), and forall().
Referenced by MemberList::writeDeclarations(), and VhdlDocGen::writeVHDLDeclarations().
endMemberGroup() [2/2]
void OutputList::endMemberGroup (bool last) [inline]
Definition at line 231 of file outputlist.h.
    { forall(&OutputGenerator::endMemberGroup,last); }
References OutputGenerator::endMemberGroup(), and forall().
endMemberGroupDocs() [1/2]
void OutputList::endMemberGroupDocs () [inline]
Definition at line 227 of file outputlist.h.
    { forall(&OutputGenerator::endMemberGroupDocs); }
References OutputGenerator::endMemberGroupDocs(), and forall().
Referenced by MemberList::writeDeclarations(), and VhdlDocGen::writeVHDLDeclarations().
endMemberGroupDocs() [2/2]
void OutputList::endMemberGroupDocs () [inline]
Definition at line 227 of file outputlist.h.
    { forall(&OutputGenerator::endMemberGroupDocs); }
References OutputGenerator::endMemberGroupDocs(), and forall().
endMemberGroupHeader() [1/2]
void OutputList::endMemberGroupHeader () [inline]
Definition at line 223 of file outputlist.h.
    { forall(&OutputGenerator::endMemberGroupHeader); }
References OutputGenerator::endMemberGroupHeader(), and forall().
Referenced by MemberList::writeDeclarations(), and VhdlDocGen::writeVHDLDeclarations().
endMemberGroupHeader() [2/2]
void OutputList::endMemberGroupHeader () [inline]
Definition at line 223 of file outputlist.h.
    { forall(&OutputGenerator::endMemberGroupHeader); }
References OutputGenerator::endMemberGroupHeader(), and forall().
endMemberHeader() [1/2]
void OutputList::endMemberHeader () [inline]
Definition at line 187 of file outputlist.h.
    { forall(&OutputGenerator::endMemberHeader); }
References OutputGenerator::endMemberHeader(), and forall().
Referenced by ClassDefImpl::endMemberDeclarations(), NamespaceLinkedRefMap::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), ConceptDefImpl::writeDeclarationLink(), MemberList::writeDeclarations(), GroupDefImpl::writeDirs(), DirDefImpl::writeFileList(), GroupDefImpl::writeFiles(), GroupDefImpl::writeNestedGroups(), DirDefImpl::writeSubDirList(), and VhdlDocGen::writeVHDLDeclarations().
endMemberHeader() [2/2]
void OutputList::endMemberHeader () [inline]
Definition at line 187 of file outputlist.h.
    { forall(&OutputGenerator::endMemberHeader); }
References OutputGenerator::endMemberHeader(), and forall().
endMemberItem() [1/2]
void OutputList::endMemberItem () [inline]
Definition at line 211 of file outputlist.h.
    { forall(&OutputGenerator::endMemberItem); }
References OutputGenerator::endMemberItem(), and forall().
Referenced by MemberDefImpl::writeDeclaration(), ClassDefImpl::writeDeclaration(), NamespaceLinkedRefMap::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), ConceptDefImpl::writeDeclarationLink(), GroupDefImpl::writeDirs(), DirDefImpl::writeFileList(), GroupDefImpl::writeFiles(), GroupDefImpl::writeNestedGroups(), MemberList::writePlainDeclarations(), DirDefImpl::writeSubDirList(), and VhdlDocGen::writeVHDLDeclaration().
endMemberItem() [2/2]
void OutputList::endMemberItem () [inline]
Definition at line 211 of file outputlist.h.
    { forall(&OutputGenerator::endMemberItem); }
References OutputGenerator::endMemberItem(), and forall().
endMemberList() [1/2]
void OutputList::endMemberList () [inline]
Definition at line 199 of file outputlist.h.
    { forall(&OutputGenerator::endMemberList); }
References OutputGenerator::endMemberList(), and forall().
Referenced by ClassLinkedRefMap::writeDeclaration(), ConceptLinkedRefMap::writeDeclaration(), NamespaceLinkedRefMap::writeDeclaration(), GroupDefImpl::writeDirs(), DirDefImpl::writeFileList(), GroupDefImpl::writeFiles(), GroupDefImpl::writeNestedGroups(), MemberList::writePlainDeclarations(), VhdlDocGen::writePlainVHDLDeclarations(), and DirDefImpl::writeSubDirList().
endMemberList() [2/2]
void OutputList::endMemberList () [inline]
Definition at line 199 of file outputlist.h.
    { forall(&OutputGenerator::endMemberList); }
References OutputGenerator::endMemberList(), and forall().
endMemberSections() [1/2]
void OutputList::endMemberSections () [inline]
Definition at line 179 of file outputlist.h.
    { forall(&OutputGenerator::endMemberSections); }
References OutputGenerator::endMemberSections(), and forall().
Referenced by DirDefImpl::endMemberDeclarations(), FileDefImpl::endMemberDeclarations(), GroupDefImpl::endMemberDeclarations(), NamespaceDefImpl::endMemberDeclarations(), and ClassDefImpl::endMemberDeclarations().
endMemberSections() [2/2]
void OutputList::endMemberSections () [inline]
Definition at line 179 of file outputlist.h.
    { forall(&OutputGenerator::endMemberSections); }
References OutputGenerator::endMemberSections(), and forall().
endMemberSubtitle() [1/2]
void OutputList::endMemberSubtitle () [inline]
Definition at line 191 of file outputlist.h.
    { forall(&OutputGenerator::endMemberSubtitle); }
References OutputGenerator::endMemberSubtitle(), and forall().
Referenced by MemberList::writeDeclarations(), and VhdlDocGen::writeVHDLDeclarations().
endMemberSubtitle() [2/2]
void OutputList::endMemberSubtitle () [inline]
Definition at line 191 of file outputlist.h.
    { forall(&OutputGenerator::endMemberSubtitle); }
References OutputGenerator::endMemberSubtitle(), and forall().
endMemberTemplateParams() [1/2]
void OutputList::endMemberTemplateParams (const QCString & anchor, const QCString & inheritId) [inline]
Definition at line 215 of file outputlist.h.
    { forall(&OutputGenerator::endMemberTemplateParams,anchor,inheritId); }
References OutputGenerator::endMemberTemplateParams(), and forall().
Referenced by MemberDefImpl::writeDeclaration().
endMemberTemplateParams() [2/2]
void OutputList::endMemberTemplateParams (const QCString & anchor, const QCString & inheritId) [inline]
Definition at line 215 of file outputlist.h.
    { forall(&OutputGenerator::endMemberTemplateParams,anchor,inheritId); }
References OutputGenerator::endMemberTemplateParams(), and forall().
endPageDoc() [1/2]
void OutputList::endPageDoc () [inline]
Definition at line 367 of file outputlist.h.
    { forall(&OutputGenerator::endPageDoc); }
References OutputGenerator::endPageDoc(), and forall().
Referenced by PageDefImpl::writeDocumentation(), and writeIndex().
endPageDoc() [2/2]
void OutputList::endPageDoc () [inline]
Definition at line 367 of file outputlist.h.
    { forall(&OutputGenerator::endPageDoc); }
References OutputGenerator::endPageDoc(), and forall().
endPageRef() [1/2]
void OutputList::endPageRef (const QCString & c, const QCString & a) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 345 of file outputlist.h.
    { forall(&OutputGenerator::endPageRef,c,a); }
References a, c, BaseOutputDocInterface::endPageRef(), and forall().
Referenced by writePageRef().
endPageRef() [2/2]
void OutputList::endPageRef (const QCString & c, const QCString & a) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 345 of file outputlist.h.
    { forall(&OutputGenerator::endPageRef,c,a); }
References a, c, BaseOutputDocInterface::endPageRef(), and forall().
endParagraph() [1/2]
void OutputList::endParagraph () [inline], [virtual]
Ends a paragraph
Implements BaseOutputDocInterface.
Definition at line 109 of file outputlist.h.
    { forall(&OutputGenerator::endParagraph); }
References BaseOutputDocInterface::endParagraph(), and forall().
Referenced by MemberDefImpl::_writeCategoryRelation(), MemberDefImpl::_writeGroupInclude(), MemberDefImpl::_writeReimplementedBy(), MemberDefImpl::_writeReimplements(), DefinitionImpl::_writeSourceRefList(), ClassDefImpl::showUsedFiles(), ConceptDefImpl::writeBriefDescription(), DirDefImpl::writeBriefDescription(), FileDefImpl::writeBriefDescription(), GroupDefImpl::writeBriefDescription(), NamespaceDefImpl::writeBriefDescription(), ClassDefImpl::writeBriefDescription(), MemberDefImpl::writeDeclaration(), FileDefImpl::writeDetailedDescription(), MemberDefImpl::writeDocumentation(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), ClassDefImpl::writeIncludeFiles(), ConceptDefImpl::writeIncludeFiles(), ClassDefImpl::writeIncludeFilesForSlice(), ClassDefImpl::writeInheritanceGraph(), ClassDefImpl::writeMemberList(), DefinitionImpl::writeSourceDef(), and FileDefImpl::writeSourceLink().
endParagraph() [2/2]
void OutputList::endParagraph () [inline], [virtual]
Ends a paragraph
Implements BaseOutputDocInterface.
Definition at line 109 of file outputlist.h.
    { forall(&OutputGenerator::endParagraph); }
References BaseOutputDocInterface::endParagraph(), and forall().
endParameterList() [1/2]
void OutputList::endParameterList () [inline]
Definition at line 433 of file outputlist.h.
    { forall(&OutputGenerator::endParameterList); }
References OutputGenerator::endParameterList(), and forall().
Referenced by MemberDefImpl::writeDocumentation().
endParameterList() [2/2]
void OutputList::endParameterList () [inline]
Definition at line 433 of file outputlist.h.
    { forall(&OutputGenerator::endParameterList); }
References OutputGenerator::endParameterList(), and forall().
endParameterName() [1/2]
void OutputList::endParameterName (bool last, bool one, bool bracket) [inline]
Definition at line 429 of file outputlist.h.
    { forall(&OutputGenerator::endParameterName,last,one,bracket); }
References OutputGenerator::endParameterName(), and forall().
Referenced by writeDefArgumentList(), VhdlDocGen::writeFuncProcDocu(), and VhdlDocGen::writeRecUnitDocu().
endParameterName() [2/2]
void OutputList::endParameterName (bool last, bool one, bool bracket) [inline]
Definition at line 429 of file outputlist.h.
    { forall(&OutputGenerator::endParameterName,last,one,bracket); }
References OutputGenerator::endParameterName(), and forall().
endParameterType() [1/2]
void OutputList::endParameterType () [inline]
Definition at line 425 of file outputlist.h.
    { forall(&OutputGenerator::endParameterType); }
References OutputGenerator::endParameterType(), and forall().
Referenced by writeDefArgumentList(), VhdlDocGen::writeFuncProcDocu(), and VhdlDocGen::writeRecUnitDocu().
endParameterType() [2/2]
void OutputList::endParameterType () [inline]
Definition at line 425 of file outputlist.h.
    { forall(&OutputGenerator::endParameterType); }
References OutputGenerator::endParameterType(), and forall().
endParamList() [1/2]
void OutputList::endParamList () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 325 of file outputlist.h.
    { forall(&OutputGenerator::endParamList); }
References BaseOutputDocInterface::endParamList(), and forall().
endParamList() [2/2]
void OutputList::endParamList () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 325 of file outputlist.h.
    { forall(&OutputGenerator::endParamList); }
References BaseOutputDocInterface::endParamList(), and forall().
endPlainFile() [1/2]
void OutputList::endPlainFile () [inline]
Definition at line 504 of file outputlist.h.
    { forall(&OutputGenerator::endPlainFile); }
References OutputGenerator::endPlainFile(), and forall().
endPlainFile() [2/2]
void OutputList::endPlainFile () [inline]
Definition at line 504 of file outputlist.h.
    { forall(&OutputGenerator::endPlainFile); }
References OutputGenerator::endPlainFile(), and forall().
endProjectNumber() [1/2]
void OutputList::endProjectNumber () [inline]
Definition at line 84 of file outputlist.h.
    { forall(&OutputGenerator::endProjectNumber); }
References OutputGenerator::endProjectNumber(), and forall().
Referenced by FileDefImpl::writeDocumentation(), and writeIndex().
endProjectNumber() [2/2]
void OutputList::endProjectNumber () [inline]
Definition at line 84 of file outputlist.h.
    { forall(&OutputGenerator::endProjectNumber); }
References OutputGenerator::endProjectNumber(), and forall().
endQuickIndices() [1/2]
void OutputList::endQuickIndices () [inline]
Definition at line 349 of file outputlist.h.
    { forall(&OutputGenerator::endQuickIndices); }
References OutputGenerator::endQuickIndices(), and forall().
Referenced by startFile(), writeClassMemberIndexFiltered(), ConceptDefImpl::writeDocumentation(), DirDefImpl::writeDocumentation(), DirRelation::writeDocumentation(), FileDefImpl::writeDocumentation(), NamespaceDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), ClassDefImpl::writeDocumentation(), MemberList::writeDocumentationPage(), writeFileMemberIndexFiltered(), writeIndex(), ClassDefImpl::writeMemberList(), writeNamespaceMemberIndexFiltered(), and FileDefImpl::writeSourceHeader().
endQuickIndices() [2/2]
void OutputList::endQuickIndices () [inline]
Definition at line 349 of file outputlist.h.
    { forall(&OutputGenerator::endQuickIndices); }
References OutputGenerator::endQuickIndices(), and forall().
endSection() [1/2]
void OutputList::endSection (const QCString & lab, SectionType t) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 333 of file outputlist.h.
    { forall(&OutputGenerator::endSection,lab,t); }
References BaseOutputDocInterface::endSection(), and forall().
Referenced by PageDefImpl::writeDocumentation(), writeMemberList(), GroupDefImpl::writePageDocumentation(), and PageDefImpl::writePageDocumentation().
endSection() [2/2]
void OutputList::endSection (const QCString & lab, SectionType t) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 333 of file outputlist.h.
    { forall(&OutputGenerator::endSection,lab,t); }
References BaseOutputDocInterface::endSection(), and forall().
endSmall() [1/2]
void OutputList::endSmall () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 298 of file outputlist.h.
    { forall(&OutputGenerator::endSmall); }
References BaseOutputDocInterface::endSmall(), and forall().
endSmall() [2/2]
void OutputList::endSmall () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 298 of file outputlist.h.
    { forall(&OutputGenerator::endSmall); }
References BaseOutputDocInterface::endSmall(), and forall().
endSubsection() [1/2]
void OutputList::endSubsection () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 286 of file outputlist.h.
    { forall(&OutputGenerator::endSubsection); }
References BaseOutputDocInterface::endSubsection(), and forall().
endSubsection() [2/2]
void OutputList::endSubsection () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 286 of file outputlist.h.
    { forall(&OutputGenerator::endSubsection); }
References BaseOutputDocInterface::endSubsection(), and forall().
endSubsubsection() [1/2]
void OutputList::endSubsubsection () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 290 of file outputlist.h.
    { forall(&OutputGenerator::endSubsubsection); }
References BaseOutputDocInterface::endSubsubsection(), and forall().
endSubsubsection() [2/2]
void OutputList::endSubsubsection () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 290 of file outputlist.h.
    { forall(&OutputGenerator::endSubsubsection); }
References BaseOutputDocInterface::endSubsubsection(), and forall().
endTextBlock() [1/2]
void OutputList::endTextBlock (bool paraBreak = FALSE) [inline]
Definition at line 411 of file outputlist.h.
    { forall(&OutputGenerator::endTextBlock,paraBreak); }
References OutputGenerator::endTextBlock(), and forall().
Referenced by writeAnnotatedIndexGeneric(), writeClassMemberIndexFiltered(), writeConceptIndex(), FileDefImpl::writeDetailedDescription(), NamespaceDefImpl::writeDetailedDescription(), ConceptDefImpl::writeDetailedDescription(), ClassDefImpl::writeDetailedDocumentationBody(), writeExampleIndex(), writeFileIndex(), writeFileMemberIndexFiltered(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), FileDefImpl::writeIncludedByGraph(), FileDefImpl::writeIncludeFiles(), FileDefImpl::writeIncludeGraph(), writeIndex(), writeNamespaceIndex(), writeNamespaceMemberIndexFiltered(), GroupDefImpl::writePageDocumentation(), PageDefImpl::writePageDocumentation(), and writePageIndex().
endTextBlock() [2/2]
void OutputList::endTextBlock (bool paraBreak = FALSE) [inline]
Definition at line 411 of file outputlist.h.
    { forall(&OutputGenerator::endTextBlock,paraBreak); }
References OutputGenerator::endTextBlock(), and forall().
endTextLink() [1/2]
void OutputList::endTextLink () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 154 of file outputlist.h.
    { forall(&OutputGenerator::endTextLink); }
References BaseOutputDocInterface::endTextLink(), and forall().
Referenced by ConceptDefImpl::writeBriefDescription(), DirDefImpl::writeBriefDescription(), FileDefImpl::writeBriefDescription(), GroupDefImpl::writeBriefDescription(), NamespaceDefImpl::writeBriefDescription(), MemberDefImpl::writeDeclaration(), DirDefImpl::writeFileList(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), ClassDefImpl::writeMoreLink(), MemberList::writePlainDeclarations(), writeSingleFileIndex(), FileDefImpl::writeSourceHeader(), FileDefImpl::writeSourceLink(), and VhdlDocGen::writeVHDLDeclaration().
endTextLink() [2/2]
void OutputList::endTextLink () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 154 of file outputlist.h.
    { forall(&OutputGenerator::endTextLink); }
References BaseOutputDocInterface::endTextLink(), and forall().
endTitle() [1/2]
void OutputList::endTitle () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 105 of file outputlist.h.
    { forall(&OutputGenerator::endTitle); }
References BaseOutputDocInterface::endTitle(), and forall().
endTitle() [2/2]
void OutputList::endTitle () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 105 of file outputlist.h.
    { forall(&OutputGenerator::endTitle); }
References BaseOutputDocInterface::endTitle(), and forall().
endTitleHead() [1/2]
void OutputList::endTitleHead (const QCString & fileName, const QCString & name) [inline]
Definition at line 101 of file outputlist.h.
    { forall(&OutputGenerator::endTitleHead,fileName,name); }
References OutputGenerator::endTitleHead(), forall(), and setup::name.
Referenced by endTitle(), GroupDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), and writeIndex().
endTitleHead() [2/2]
void OutputList::endTitleHead (const QCString & fileName, const QCString & name) [inline]
Definition at line 101 of file outputlist.h.
    { forall(&OutputGenerator::endTitleHead,fileName,name); }
References OutputGenerator::endTitleHead(), forall(), and setup::name.
endTypewriter() [1/2]
void OutputList::endTypewriter () [inline], [virtual]
End a section of text displayed in typewriter style.
Implements BaseOutputDocInterface.
Definition at line 167 of file outputlist.h.
    { forall(&OutputGenerator::endTypewriter); }
References BaseOutputDocInterface::endTypewriter(), and forall().
Referenced by MemberDefImpl::_writeGroupInclude(), NamespaceDefImpl::writeBriefDescription(), writeClassTreeForList(), writeClassTreeToOutput(), MemberDefImpl::writeDeclaration(), writeDefArgumentList(), writeDirTreeNode(), writeGroupTreeNode(), FileDefImpl::writeIncludeFiles(), ClassDefImpl::writeIncludeFiles(), ConceptDefImpl::writeIncludeFiles(), ClassDefImpl::writeIncludeFilesForSlice(), and writeInheritanceSpecifier().
endTypewriter() [2/2]
void OutputList::endTypewriter () [inline], [virtual]
End a section of text displayed in typewriter style.
Implements BaseOutputDocInterface.
Definition at line 167 of file outputlist.h.
    { forall(&OutputGenerator::endTypewriter); }
References BaseOutputDocInterface::endTypewriter(), and forall().
exceptionEntry() [1/2]
void OutputList::exceptionEntry (const QCString & prefix, bool closeBracket) [inline]
Definition at line 435 of file outputlist.h.
    { forall(&OutputGenerator::exceptionEntry,prefix,closeBracket); }
References OutputGenerator::exceptionEntry(), and forall().
Referenced by writeExceptionListImpl().
exceptionEntry() [2/2]
void OutputList::exceptionEntry (const QCString & prefix, bool closeBracket) [inline]
Definition at line 435 of file outputlist.h.
    { forall(&OutputGenerator::exceptionEntry,prefix,closeBracket); }
References OutputGenerator::exceptionEntry(), and forall().
forall() [1/2]
template<typename T , class... Ts, class... As>
void OutputList::forall (void(T::*)(Ts...) methodPtr, As &&... args) [inline], [private]
Definition at line 517 of file outputlist.h.
    {
      for (const auto &og : m_outputs)
      {
        if (og->isEnabled()) (og.get()->*methodPtr)(std::forward<As>(args)...);
      }
    }
References m_outputs.
Referenced by addIndexItem(), cleanup(), codify(), docify(), endAnonTypeScope(), endBold(), endCallGraph(), endCenter(), endClassDiagram(), endCodeFragment(), endCodeLine(), endCompoundTemplateParams(), endConstraintDocs(), endConstraintList(), endConstraintParam(), endConstraintType(), endContents(), endDescForItem(), endDescItem(), endDescription(), endDescTable(), endDescTableData(), endDescTableRow(), endDescTableTitle(), endDirDepGraph(), endDotGraph(), endDoxyAnchor(), endEmphasis(), endExamples(), endFile(), endFontClass(), endGroupCollaboration(), endGroupHeader(), endHeaderSection(), endHtmlLink(), endInclDepGraph(), endIndent(), endIndexItem(), endIndexKey(), endIndexList(), endIndexListItem(), endIndexSection(), endIndexValue(), endInlineHeader(), endInlineMemberDoc(), endInlineMemberName(), endInlineMemberType(), endItemList(), endItemListItem(), endLabels(), endMemberDeclaration(), endMemberDescription(), endMemberDoc(), endMemberDocList(), endMemberDocName(), endMemberDocPrefixItem(), endMemberDocSimple(), endMemberGroup(), endMemberGroupDocs(), endMemberGroupHeader(), endMemberHeader(), endMemberItem(), endMemberList(), endMemberSections(), endMemberSubtitle(), endMemberTemplateParams(), endPageDoc(), endPageRef(), endParagraph(), endParameterList(), endParameterName(), endParameterType(), endParamList(), endPlainFile(), endProjectNumber(), endQuickIndices(), endSection(), endSmall(), endSubsection(), endSubsubsection(), endTextBlock(), endTextLink(), endTitle(), endTitleHead(), endTypewriter(), exceptionEntry(), insertMemberAlign(), insertMemberAlignLeft(), lastIndexPage(), lineBreak(), startAnonTypeScope(), startBold(), startCallGraph(), startCenter(), startClassDiagram(), startCodeFragment(), startCodeLine(), startCompoundTemplateParams(), startConstraintDocs(), startConstraintList(), startConstraintParam(), startConstraintType(), startContents(), startDescForItem(), startDescItem(), startDescription(), startDescTable(), startDescTableData(), startDescTableRow(), startDescTableTitle(), startDirDepGraph(), startDotGraph(), startDoxyAnchor(), startEmphasis(), startExamples(), startFile(), startFontClass(), startGroupCollaboration(), startGroupHeader(), startHeaderSection(), startHtmlLink(), startInclDepGraph(), startIndent(), startIndexItem(), startIndexKey(), startIndexList(), startIndexListItem(), startIndexSection(), startIndexValue(), startInlineHeader(), startInlineMemberDoc(), startInlineMemberName(), startInlineMemberType(), startItemList(), startItemListItem(), startLabels(), startMemberDeclaration(), startMemberDescription(), startMemberDoc(), startMemberDocList(), startMemberDocName(), startMemberDocPrefixItem(), startMemberDocSimple(), startMemberGroup(), startMemberGroupDocs(), startMemberGroupHeader(), startMemberHeader(), startMemberItem(), startMemberList(), startMemberSections(), startMemberSubtitle(), startMemberTemplateParams(), startPageDoc(), startPageRef(), startParagraph(), startParameterList(), startParameterName(), startParameterType(), startParamList(), startPlainFile(), startProjectNumber(), startQuickIndices(), startSection(), startSmall(), startSubsection(), startSubsubsection(), startTextBlock(), startTextLink(), startTitle(), startTitleHead(), startTypewriter(), writeAnchor(), writeChar(), writeCodeAnchor(), writeCodeLink(), writeEndAnnoItem(), writeFooter(), writeGraphicalHierarchy(), writeInheritedSectionTitle(), writeLabel(), writeLatexSpacing(), writeLineNumber(), writeLogo(), writeNavigationPath(), writeNonBreakableSpace(), writeObjectLink(), writePageLink(), writeQuickLinks(), writeRuler(), writeSearchInfo(), writeSplitBar(), writeStartAnnoItem(), writeString(), writeStyleInfo(), writeSummaryLink(), writeSynopsis(), and writeTooltip().
forall() [2/2]
template<typename T , class... Ts, class... As>
void OutputList::forall (void(T::*)(Ts...) methodPtr, As &&... args) [inline], [private]
Definition at line 517 of file outputlist.h.
    {
      for (const auto &og : m_outputs)
      {
        if (og->isEnabled()) (og.get()->*methodPtr)(std::forward<As>(args)...);
      }
    }
References m_outputs.
generateDoc() [1/2]
void OutputList::generateDoc (const QCString & fileName, int startLine, const Definition * ctx, const MemberDef * md, const QCString & docStr, bool indexWords, bool isExample, const QCString & exampleName, bool singleLine, bool linkFromIndex, bool markdownSupport)
Definition at line 142 of file outputlist.cpp.
{
  int count=0;
  if (docStr.isEmpty()) return;
  for (const auto &og : m_outputs)
  {
    if (og->isEnabled()) count++;
  }
  if (count>0)
  {
    // we want to validate irrespective of the number of output formats
    // specified as:
    // - when only XML format there should be warnings as well (XML has its own write routines)
    // - no formats there should be warnings as well
    auto parser { createDocParser() };
    auto ast { validatingParseDoc(*parser.get(),
                                     fileName,startLine,
                                     ctx,md,docStr,indexWords,isExample,exampleName,
                                     singleLine,linkFromIndex,markdownSupport) };
    if (ast) writeDoc(ast.get(),ctx,md,m_id);
  }
}
References createDocParser(), QCString::isEmpty(), m_id, m_outputs, validatingParseDoc(), and writeDoc().
Referenced by MemberDefImpl::_writeEnumValues(), generateExampleDocs(), writeAnnotatedClassList(), ClassDefImpl::writeBriefDescription(), writeConceptIndex(), NamespaceLinkedRefMap::writeDeclaration(), MemberList::writeDeclarations(), DirDefImpl::writeDetailedDescription(), FileDefImpl::writeDetailedDescription(), GroupDefImpl::writeDetailedDescription(), NamespaceDefImpl::writeDetailedDescription(), ConceptDefImpl::writeDetailedDescription(), ClassDefImpl::writeDetailedDocumentationBody(), GroupDefImpl::writeDirs(), MemberDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), DirDefImpl::writeFileList(), GroupDefImpl::writeFiles(), writeGraphInfo(), writeIndex(), MemberDefImpl::writeMemberDocSimple(), writeNamespaceIndex(), GroupDefImpl::writeNestedGroups(), GroupDefImpl::writePageDocumentation(), PageDefImpl::writePageDocumentation(), writeSingleFileIndex(), DirDefImpl::writeSubDirList(), writeTypeConstraints(), VhdlDocGen::writeVHDLDeclaration(), and VhdlDocGen::writeVHDLDeclarations().
generateDoc() [2/2]
void OutputList::generateDoc (const QCString & fileName, int startLine, const Definition * ctx, const MemberDef * md, const QCString & docStr, bool indexWords, bool isExample, const QCString & exampleName, bool singleLine, bool linkFromIndex, bool markdownSupport)
id() [1/2]
int OutputList::id () const [inline], [virtual]
Identifier for the output file
Reimplemented from CodeOutputInterface.
Definition at line 52 of file outputlist.h.
{ return m_id; }
References m_id.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), and doxmlparser.compound.docXRefSectType::set_id().
id() [2/2]
int OutputList::id () const [inline], [virtual]
Identifier for the output file
Reimplemented from CodeOutputInterface.
Definition at line 52 of file outputlist.h.
{ return m_id; }
References m_id.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), and doxmlparser.compound.docXRefSectType::set_id().
indexSearchData() [1/2]
void OutputList::indexSearchData () [inline]
Definition at line 497 of file outputlist.h.
    {
      m_searchData.transfer();
    }
References m_searchData, and SIDataCollection::transfer().
indexSearchData() [2/2]
void OutputList::indexSearchData () [inline]
Definition at line 497 of file outputlist.h.
    {
      m_searchData.transfer();
    }
References m_searchData, and SIDataCollection::transfer().
insertMemberAlign() [1/2]
void OutputList::insertMemberAlign (bool templ = FALSE) [inline]
Definition at line 233 of file outputlist.h.
    { forall(&OutputGenerator::insertMemberAlign,templ); }
References forall(), and OutputGenerator::insertMemberAlign().
Referenced by MemberDefImpl::writeDeclaration(), NamespaceLinkedRefMap::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), ConceptDefImpl::writeDeclarationLink(), GroupDefImpl::writeDirs(), DirDefImpl::writeFileList(), GroupDefImpl::writeFiles(), VhdlDocGen::writeFunctionProto(), GroupDefImpl::writeNestedGroups(), MemberList::writePlainDeclarations(), VhdlDocGen::writeRecordUnit(), DirDefImpl::writeSubDirList(), writeUCFLink(), and VhdlDocGen::writeVHDLDeclaration().
insertMemberAlign() [2/2]
void OutputList::insertMemberAlign (bool templ = FALSE) [inline]
Definition at line 233 of file outputlist.h.
    { forall(&OutputGenerator::insertMemberAlign,templ); }
References forall(), and OutputGenerator::insertMemberAlign().
insertMemberAlignLeft() [1/2]
void OutputList::insertMemberAlignLeft (int typ = 0, bool templ = FALSE) [inline]
Definition at line 235 of file outputlist.h.
    { forall(&OutputGenerator::insertMemberAlignLeft,typ,templ); }
References forall(), and OutputGenerator::insertMemberAlignLeft().
Referenced by VhdlDocGen::writeVHDLDeclaration().
insertMemberAlignLeft() [2/2]
void OutputList::insertMemberAlignLeft (int typ = 0, bool templ = FALSE) [inline]
Definition at line 235 of file outputlist.h.
    { forall(&OutputGenerator::insertMemberAlignLeft,typ,templ); }
References forall(), and OutputGenerator::insertMemberAlignLeft().
isEnabled() [1/2]
bool OutputList::isEnabled (OutputGenerator::OutputType o)
Definition at line 116 of file outputlist.cpp.
{
  bool result=FALSE;
  for (const auto &og : m_outputs)
  {
    result=result || og->isEnabled(o);
  }
  return result;
}
References FALSE, and m_outputs.
Referenced by MemberDefImpl::writeDeclaration(), writeDefArgumentList(), FileDefImpl::writeInlineClasses(), and VhdlDocGen::writeVHDLDeclaration().
isEnabled() [2/2]
bool OutputList::isEnabled (OutputGenerator::OutputType o)
lastIndexPage() [1/2]
void OutputList::lastIndexPage () [inline]
Definition at line 413 of file outputlist.h.
    { forall(&OutputGenerator::lastIndexPage); }
References forall(), and OutputGenerator::lastIndexPage().
Referenced by writeIndex().
lastIndexPage() [2/2]
void OutputList::lastIndexPage () [inline]
Definition at line 413 of file outputlist.h.
    { forall(&OutputGenerator::lastIndexPage); }
References forall(), and OutputGenerator::lastIndexPage().
lineBreak() [1/2]
void OutputList::lineBreak (const QCString & style = QCString()) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 300 of file outputlist.h.
    { forall(&OutputGenerator::lineBreak,style); }
References forall(), BaseOutputDocInterface::lineBreak(), and style.
Referenced by MemberDefImpl::_writeTemplatePrefix(), NamespaceDefImpl::writeBriefDescription(), MemberDefImpl::writeEnumDeclaration(), VhdlDocGen::writeFunctionProto(), FileDefImpl::writeIncludeFiles(), ClassDefImpl::writeIncludeFilesForSlice(), MemberDefImpl::writeMemberDocSimple(), VhdlDocGen::writeProcedureProto(), ClassDefImpl::writeTemplateSpec(), and VhdlDocGen::writeVhdlLink().
lineBreak() [2/2]
void OutputList::lineBreak (const QCString & style = QCString()) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 300 of file outputlist.h.
    { forall(&OutputGenerator::lineBreak,style); }
References forall(), BaseOutputDocInterface::lineBreak(), and style.
newId() [1/2]
void OutputList::newId () [private]
Definition at line 71 of file outputlist.cpp.
{
  m_id = ++g_outId;
}
References g_outId, and m_id.
Referenced by OutputList(), and startFile().
newId() [2/2]
void OutputList::newId () [private]
operator=() [1/2]
OutputList & OutputList::operator= (const OutputList & ol)
Definition at line 53 of file outputlist.cpp.
{
  if (this!=&ol)
  {
    m_id = ol.m_id;
    for (const auto &og : ol.m_outputs)
    {
      m_outputs.emplace_back(og->clone());
    }
  }
  return *this;
}
References m_id, and m_outputs.
operator=() [2/2]
OutputList & OutputList::operator= (const OutputList & ol)
parseText() [1/2]
void OutputList::parseText (const QCString & textStr) [virtual]
Reimplemented from BaseOutputDocInterface.
Definition at line 182 of file outputlist.cpp.
{
  int count=0;
  for (const auto &og : m_outputs)
  {
    if (og->isEnabled()) count++;
  }
  // we want to validate irrespective of the number of output formats
  // specified as:
  // - when only XML format there should be warnings as well (XML has its own write routines)
  // - no formats there should be warnings as well
  auto parser { createDocParser() };
  auto textNode { validatingParseText(*parser.get(), textStr) };
  if (textNode && count>0)
  {
    for (const auto &og : m_outputs)
    {
      if (og->isEnabled()) og->writeDoc(textNode.get(),0,0,m_id);
    }
  }
}
References createDocParser(), m_id, m_outputs, textNode, and validatingParseText().
Referenced by MemberDefImpl::_writeCallerGraph(), MemberDefImpl::_writeCallGraph(), MemberDefImpl::_writeCategoryRelation(), MemberDefImpl::_writeMultiLineInitializer(), MemberDefImpl::_writeReimplements(), DefinitionImpl::_writeSourceRefList(), ClassDefImpl::endMemberDeclarations(), ClassDefImpl::showUsedFiles(), writeAlphabeticalExceptionIndex(), writeAlphabeticalIndex(), writeAlphabeticalInterfaceIndex(), writeAlphabeticalStructIndex(), writeAnnotatedIndexGeneric(), FileDefImpl::writeAuthorSection(), GroupDefImpl::writeAuthorSection(), NamespaceDefImpl::writeAuthorSection(), ClassDefImpl::writeAuthorSection(), ConceptDefImpl::writeAuthorSection(), ConceptDefImpl::writeBriefDescription(), DirDefImpl::writeBriefDescription(), FileDefImpl::writeBriefDescription(), GroupDefImpl::writeBriefDescription(), NamespaceDefImpl::writeBriefDescription(), writeClassMemberIndexFiltered(), writeClassTreeForList(), writeClassTreeToOutput(), ClassDefImpl::writeCollaborationGraph(), writeConceptIndex(), MemberDefImpl::writeDeclaration(), NamespaceLinkedRefMap::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), ConceptDefImpl::writeDeclarationLink(), MemberList::writeDeclarations(), ConceptDefImpl::writeDefinition(), ClassDefImpl::writeDetailedDescription(), DirDefImpl::writeDetailedDescription(), FileDefImpl::writeDetailedDescription(), GroupDefImpl::writeDetailedDescription(), NamespaceDefImpl::writeDetailedDescription(), ConceptDefImpl::writeDetailedDescription(), DirDefImpl::writeDirectoryGraph(), GroupDefImpl::writeDirs(), writeDirTreeNode(), ConceptDefImpl::writeDocumentation(), DirDefImpl::writeDocumentation(), DirRelation::writeDocumentation(), FileDefImpl::writeDocumentation(), GroupDefImpl::writeDocumentation(), NamespaceDefImpl::writeDocumentation(), ClassDefImpl::writeDocumentation(), ClassLinkedRefMap::writeDocumentation(), MemberList::writeDocumentation(), MemberDefImpl::writeEnumDeclaration(), writeExampleIndex(), writeFileIndex(), DirDefImpl::writeFileList(), writeFileMemberIndexFiltered(), GroupDefImpl::writeFiles(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeGraphInfo(), GroupDefImpl::writeGroupGraph(), writeGroupIndex(), writeGroupTreeNode(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), FileDefImpl::writeIncludedByGraph(), FileDefImpl::writeIncludeGraph(), writeIndex(), ClassDefImpl::writeInheritanceGraph(), ClassDefImpl::writeInlineDocumentation(), writeMarkerList(), ClassDefImpl::writeMemberList(), ClassDefImpl::writeMoreLink(), writeNamespaceIndex(), writeNamespaceMemberIndexFiltered(), GroupDefImpl::writeNestedGroups(), PageDefImpl::writePageDocumentation(), writePageIndex(), MemberList::writePlainDeclarations(), writeSingleFileIndex(), DefinitionImpl::writeSourceDef(), FileDefImpl::writeSourceHeader(), FileDefImpl::writeSourceLink(), DirDefImpl::writeSubDirList(), writeTypeConstraints(), writeUserGroupStubPage(), and VhdlDocGen::writeVHDLDeclarations().
parseText() [2/2]
void OutputList::parseText (const QCString & textStr) [virtual]
Reimplemented from BaseOutputDocInterface.
popGeneratorState() [1/2]
void OutputList::popGeneratorState ()
Definition at line 134 of file outputlist.cpp.
{
  for (const auto &og : m_outputs)
  {
    og->popGeneratorState();
  }
}
References m_outputs.
Referenced by ClassDefImpl::addClassAttributes(), NamespaceDefImpl::addNamespaceAttributes(), endFile(), endFileWithNavPath(), endIndexHierarchy(), GroupDefImpl::endMemberDocumentation(), endTitle(), generateDirDocs(), recursivelyAddGroupListToTitle(), ClassDefImpl::showUsedFiles(), startIndexHierarchy(), writeAlphabeticalExceptionIndex(), writeAlphabeticalIndex(), writeAlphabeticalInterfaceIndex(), writeAlphabeticalStructIndex(), writeAnnotatedClassList(), writeAnnotatedIndexGeneric(), FileDefImpl::writeAuthorSection(), GroupDefImpl::writeAuthorSection(), NamespaceDefImpl::writeAuthorSection(), ClassDefImpl::writeAuthorSection(), ConceptDefImpl::writeAuthorSection(), ConceptDefImpl::writeBriefDescription(), DirDefImpl::writeBriefDescription(), FileDefImpl::writeBriefDescription(), GroupDefImpl::writeBriefDescription(), NamespaceDefImpl::writeBriefDescription(), ClassDefImpl::writeBriefDescription(), writeClassHierarchy(), writeClassMemberIndexFiltered(), ClassDefImpl::writeCollaborationGraph(), writeConceptIndex(), MemberDefImpl::writeDeclaration(), MemberList::writeDeclarations(), writeDefArgumentList(), ClassDefImpl::writeDetailedDescription(), DirDefImpl::writeDetailedDescription(), FileDefImpl::writeDetailedDescription(), GroupDefImpl::writeDetailedDescription(), NamespaceDefImpl::writeDetailedDescription(), ConceptDefImpl::writeDetailedDescription(), ClassDefImpl::writeDetailedDocumentationBody(), writeDirHierarchy(), MemberDefImpl::writeDocumentation(), DirDefImpl::writeDocumentation(), DirRelation::writeDocumentation(), FileDefImpl::writeDocumentation(), GroupDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), MemberList::writeDocumentation(), MemberDefImpl::writeEnumDeclaration(), writeExampleIndex(), writeExamples(), writeFileIndex(), DirDefImpl::writeFileList(), writeFileMemberIndexFiltered(), writeGraphInfo(), GroupDefImpl::writeGroupGraph(), writeGroupHierarchy(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), ClassDefImpl::writeIncludeFiles(), ConceptDefImpl::writeIncludeFiles(), writeIndex(), ClassDefImpl::writeInheritanceGraph(), ClassDefImpl::writeInheritedMemberDeclarations(), DefinitionImpl::writeInlineCode(), ClassDefImpl::writeInlineDocumentation(), ClassDefImpl::writeMemberList(), FileDefImpl::writeMemberPages(), GroupDefImpl::writeMemberPages(), NamespaceDefImpl::writeMemberPages(), ClassDefImpl::writeMemberPages(), ClassDefImpl::writeMoreLink(), writeNamespaceIndex(), writeNamespaceMemberIndexFiltered(), DefinitionImpl::writeNavigationPath(), PageDefImpl::writePageDocumentation(), writePageIndex(), writePageRef(), MemberList::writePlainDeclarations(), writeSingleFileIndex(), VhdlDocGen::writeSource(), ClassDefImpl::writeSummaryLinks(), FileDefImpl::writeSummaryLinks(), GroupDefImpl::writeSummaryLinks(), NamespaceDefImpl::writeSummaryLinks(), DefinitionImpl::writeToc(), writeUserGroupStubPage(), and VhdlDocGen::writeVHDLDeclaration().
popGeneratorState() [2/2]
void OutputList::popGeneratorState ()
pushGeneratorState() [1/2]
void OutputList::pushGeneratorState ()
Definition at line 126 of file outputlist.cpp.
{
  for (const auto &og : m_outputs)
  {
    og->pushGeneratorState();
  }
}
References m_outputs.
Referenced by ClassDefImpl::addClassAttributes(), NamespaceDefImpl::addNamespaceAttributes(), endFile(), endFileWithNavPath(), endIndexHierarchy(), generateDirDocs(), recursivelyAddGroupListToTitle(), ClassDefImpl::showUsedFiles(), startIndexHierarchy(), GroupDefImpl::startMemberDocumentation(), startTitle(), writeAlphabeticalExceptionIndex(), writeAlphabeticalIndex(), writeAlphabeticalInterfaceIndex(), writeAlphabeticalStructIndex(), writeAnnotatedClassList(), writeAnnotatedIndexGeneric(), FileDefImpl::writeAuthorSection(), GroupDefImpl::writeAuthorSection(), NamespaceDefImpl::writeAuthorSection(), ClassDefImpl::writeAuthorSection(), ConceptDefImpl::writeAuthorSection(), ConceptDefImpl::writeBriefDescription(), DirDefImpl::writeBriefDescription(), FileDefImpl::writeBriefDescription(), GroupDefImpl::writeBriefDescription(), NamespaceDefImpl::writeBriefDescription(), ClassDefImpl::writeBriefDescription(), writeClassHierarchy(), writeClassMemberIndexFiltered(), ClassDefImpl::writeCollaborationGraph(), writeConceptIndex(), MemberDefImpl::writeDeclaration(), MemberList::writeDeclarations(), writeDefArgumentList(), ClassDefImpl::writeDetailedDescription(), DirDefImpl::writeDetailedDescription(), FileDefImpl::writeDetailedDescription(), GroupDefImpl::writeDetailedDescription(), NamespaceDefImpl::writeDetailedDescription(), ConceptDefImpl::writeDetailedDescription(), ClassDefImpl::writeDetailedDocumentationBody(), writeDirHierarchy(), MemberDefImpl::writeDocumentation(), DirDefImpl::writeDocumentation(), DirRelation::writeDocumentation(), FileDefImpl::writeDocumentation(), GroupDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), MemberList::writeDocumentation(), MemberDefImpl::writeEnumDeclaration(), writeExampleIndex(), writeExamples(), writeFileIndex(), DirDefImpl::writeFileList(), writeFileMemberIndexFiltered(), writeGraphInfo(), GroupDefImpl::writeGroupGraph(), writeGroupHierarchy(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), ClassDefImpl::writeIncludeFiles(), ConceptDefImpl::writeIncludeFiles(), writeIndex(), ClassDefImpl::writeInheritanceGraph(), ClassDefImpl::writeInheritedMemberDeclarations(), DefinitionImpl::writeInlineCode(), ClassDefImpl::writeInlineDocumentation(), ClassDefImpl::writeMemberList(), FileDefImpl::writeMemberPages(), GroupDefImpl::writeMemberPages(), NamespaceDefImpl::writeMemberPages(), ClassDefImpl::writeMemberPages(), ClassDefImpl::writeMoreLink(), writeNamespaceIndex(), writeNamespaceMemberIndexFiltered(), DefinitionImpl::writeNavigationPath(), PageDefImpl::writePageDocumentation(), writePageIndex(), writePageRef(), MemberList::writePlainDeclarations(), writeSingleFileIndex(), VhdlDocGen::writeSource(), ClassDefImpl::writeSummaryLinks(), FileDefImpl::writeSummaryLinks(), GroupDefImpl::writeSummaryLinks(), NamespaceDefImpl::writeSummaryLinks(), DefinitionImpl::writeToc(), writeUserGroupStubPage(), and VhdlDocGen::writeVHDLDeclaration().
pushGeneratorState() [2/2]
void OutputList::pushGeneratorState ()
setCurrentDoc() [1/2]
void OutputList::setCurrentDoc (const Definition * context, const QCString & anchor, bool isSourceFile) [inline], [virtual]
Reimplemented from CodeOutputInterface.
Definition at line 489 of file outputlist.h.
    { /*forall(&OutputGenerator::setCurrentDoc,context,anchor,isSourceFile);*/
      m_searchData.setCurrentDoc(context,anchor,isSourceFile);
    }
References m_searchData, and SIDataCollection::setCurrentDoc().
setCurrentDoc() [2/2]
void OutputList::setCurrentDoc (const Definition * context, const QCString & anchor, bool isSourceFile) [inline], [virtual]
Reimplemented from CodeOutputInterface.
Definition at line 489 of file outputlist.h.
    { /*forall(&OutputGenerator::setCurrentDoc,context,anchor,isSourceFile);*/
      m_searchData.setCurrentDoc(context,anchor,isSourceFile);
    }
References m_searchData, and SIDataCollection::setCurrentDoc().
size() [1/2]
size_t OutputList::size () const [inline]
Definition at line 51 of file outputlist.h.
{ return m_outputs.size(); }
References m_outputs.
Referenced by generateOutput().
size() [2/2]
size_t OutputList::size () const [inline]
Definition at line 51 of file outputlist.h.
{ return m_outputs.size(); }
References m_outputs.
startAnonTypeScope() [1/2]
void OutputList::startAnonTypeScope (int i1) [inline]
Definition at line 205 of file outputlist.h.
    { forall(&OutputGenerator::startAnonTypeScope,i1); }
References forall(), and OutputGenerator::startAnonTypeScope().
Referenced by MemberDefImpl::writeDeclaration().
startAnonTypeScope() [2/2]
void OutputList::startAnonTypeScope (int i1) [inline]
Definition at line 205 of file outputlist.h.
    { forall(&OutputGenerator::startAnonTypeScope,i1); }
References forall(), and OutputGenerator::startAnonTypeScope().
startBold() [1/2]
void OutputList::startBold () [inline], [virtual]
Changes the text font to bold face. The bold section ends with endBold()
Implements BaseOutputDocInterface.
Definition at line 302 of file outputlist.h.
    { forall(&OutputGenerator::startBold); }
References forall(), and BaseOutputDocInterface::startBold().
Referenced by MemberDefImpl::_writeMultiLineInitializer(), VhdlDocGen::writeClassType(), ClassDefImpl::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), ConceptDefImpl::writeDeclarationLink(), MemberDefImpl::writeEnumDeclaration(), DirDefImpl::writeFileList(), VhdlDocGen::writeFormatString(), VhdlDocGen::writeFunctionProto(), MemberDefImpl::writeLink(), ClassDefImpl::writeMemberList(), writePartialFilePath(), VhdlDocGen::writeProcedureProto(), VhdlDocGen::writeProcessProto(), VhdlDocGen::writeRecordUnit(), VhdlDocGen::writeStringLink(), VhdlDocGen::writeVHDLDeclaration(), VhdlDocGen::writeVhdlLink(), and VhdlDocGen::writeVHDLTypeDocumentation().
startBold() [2/2]
void OutputList::startBold () [inline], [virtual]
Changes the text font to bold face. The bold section ends with endBold()
Implements BaseOutputDocInterface.
Definition at line 302 of file outputlist.h.
    { forall(&OutputGenerator::startBold); }
References forall(), and BaseOutputDocInterface::startBold().
startCallGraph() [1/2]
void OutputList::startCallGraph () [inline]
Definition at line 395 of file outputlist.h.
    { forall(&OutputGenerator::startCallGraph); }
References forall(), and OutputGenerator::startCallGraph().
Referenced by MemberDefImpl::_writeCallerGraph(), and MemberDefImpl::_writeCallGraph().
startCallGraph() [2/2]
void OutputList::startCallGraph () [inline]
Definition at line 395 of file outputlist.h.
    { forall(&OutputGenerator::startCallGraph); }
References forall(), and OutputGenerator::startCallGraph().
startCenter() [1/2]
void OutputList::startCenter () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 292 of file outputlist.h.
    { forall(&OutputGenerator::startCenter); }
References forall(), and BaseOutputDocInterface::startCenter().
startCenter() [2/2]
void OutputList::startCenter () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 292 of file outputlist.h.
    { forall(&OutputGenerator::startCenter); }
References forall(), and BaseOutputDocInterface::startCenter().
startClassDiagram() [1/2]
void OutputList::startClassDiagram () [inline]
Definition at line 339 of file outputlist.h.
    { forall(&OutputGenerator::startClassDiagram); }
References forall(), and OutputGenerator::startClassDiagram().
Referenced by ClassDefImpl::writeInheritanceGraph().
startClassDiagram() [2/2]
void OutputList::startClassDiagram () [inline]
Definition at line 339 of file outputlist.h.
    { forall(&OutputGenerator::startClassDiagram); }
References forall(), and OutputGenerator::startClassDiagram().
startCodeFragment() [1/2]
void OutputList::startCodeFragment (const QCString & style) [inline], [virtual]
Starts a source code fragment. The fragment will be fed to the code parser (see code.h) for syntax highlighting and cross-referencing. The fragment ends by a call to endCodeFragment()
Parameters
style The kind of code fragment.
Implements CodeOutputInterface.
Definition at line 241 of file outputlist.h.
    { forall(&OutputGenerator::startCodeFragment,style); }
References forall(), CodeOutputInterface::startCodeFragment(), and style.
Referenced by MemberDefImpl::_writeMultiLineInitializer(), ConceptDefImpl::writeDefinition(), DefinitionImpl::writeInlineCode(), VhdlDocGen::writeSource(), and FileDefImpl::writeSourceBody().
startCodeFragment() [2/2]
void OutputList::startCodeFragment (const QCString & style) [inline], [virtual]
Starts a source code fragment. The fragment will be fed to the code parser (see code.h) for syntax highlighting and cross-referencing. The fragment ends by a call to endCodeFragment()
Parameters
style The kind of code fragment.
Implements CodeOutputInterface.
Definition at line 241 of file outputlist.h.
    { forall(&OutputGenerator::startCodeFragment,style); }
References forall(), CodeOutputInterface::startCodeFragment(), and style.
startCodeLine() [1/2]
void OutputList::startCodeLine (bool hasLineNumbers) [inline], [virtual]
Implements CodeOutputInterface.
Definition at line 245 of file outputlist.h.
    { forall(&OutputGenerator::startCodeLine,hasLineNumbers); }
References forall(), and CodeOutputInterface::startCodeLine().
startCodeLine() [2/2]
void OutputList::startCodeLine (bool hasLineNumbers) [inline], [virtual]
Implements CodeOutputInterface.
Definition at line 245 of file outputlist.h.
    { forall(&OutputGenerator::startCodeLine,hasLineNumbers); }
References forall(), and CodeOutputInterface::startCodeLine().
startCompoundTemplateParams() [1/2]
void OutputList::startCompoundTemplateParams () [inline]
Definition at line 217 of file outputlist.h.
    { forall(&OutputGenerator::startCompoundTemplateParams); }
References forall(), and OutputGenerator::startCompoundTemplateParams().
Referenced by ClassDefImpl::writeTemplateSpec().
startCompoundTemplateParams() [2/2]
void OutputList::startCompoundTemplateParams () [inline]
Definition at line 217 of file outputlist.h.
    { forall(&OutputGenerator::startCompoundTemplateParams); }
References forall(), and OutputGenerator::startCompoundTemplateParams().
startConstraintDocs() [1/2]
void OutputList::startConstraintDocs () [inline]
Definition at line 448 of file outputlist.h.
    { forall(&OutputGenerator::startConstraintDocs); }
References forall(), and OutputGenerator::startConstraintDocs().
Referenced by writeTypeConstraints().
startConstraintDocs() [2/2]
void OutputList::startConstraintDocs () [inline]
Definition at line 448 of file outputlist.h.
    { forall(&OutputGenerator::startConstraintDocs); }
References forall(), and OutputGenerator::startConstraintDocs().
startConstraintList() [1/2]
void OutputList::startConstraintList (const QCString & header) [inline]
Definition at line 438 of file outputlist.h.
    { forall(&OutputGenerator::startConstraintList,header); }
References forall(), and OutputGenerator::startConstraintList().
Referenced by writeTypeConstraints().
startConstraintList() [2/2]
void OutputList::startConstraintList (const QCString & header) [inline]
Definition at line 438 of file outputlist.h.
    { forall(&OutputGenerator::startConstraintList,header); }
References forall(), and OutputGenerator::startConstraintList().
startConstraintParam() [1/2]
void OutputList::startConstraintParam () [inline]
Definition at line 440 of file outputlist.h.
    { forall(&OutputGenerator::startConstraintParam); }
References forall(), and OutputGenerator::startConstraintParam().
Referenced by writeTypeConstraints().
startConstraintParam() [2/2]
void OutputList::startConstraintParam () [inline]
Definition at line 440 of file outputlist.h.
    { forall(&OutputGenerator::startConstraintParam); }
References forall(), and OutputGenerator::startConstraintParam().
startConstraintType() [1/2]
void OutputList::startConstraintType () [inline]
Definition at line 444 of file outputlist.h.
    { forall(&OutputGenerator::startConstraintType); }
References forall(), and OutputGenerator::startConstraintType().
Referenced by writeTypeConstraints().
startConstraintType() [2/2]
void OutputList::startConstraintType () [inline]
Definition at line 444 of file outputlist.h.
    { forall(&OutputGenerator::startConstraintType); }
References forall(), and OutputGenerator::startConstraintType().
startContents() [1/2]
void OutputList::startContents () [inline]
Definition at line 361 of file outputlist.h.
    { forall(&OutputGenerator::startContents); }
References forall(), and OutputGenerator::startContents().
Referenced by generateExampleDocs(), writeAlphabeticalExceptionIndex(), writeAlphabeticalIndex(), writeAlphabeticalInterfaceIndex(), writeAlphabeticalStructIndex(), writeAnnotatedIndexGeneric(), writeClassMemberIndexFiltered(), writeConceptIndex(), ConceptDefImpl::writeDocumentation(), DirDefImpl::writeDocumentation(), DirRelation::writeDocumentation(), FileDefImpl::writeDocumentation(), GroupDefImpl::writeDocumentation(), NamespaceDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), ClassDefImpl::writeDocumentationContents(), MemberList::writeDocumentationPage(), writeExampleIndex(), writeFileIndex(), writeFileMemberIndexFiltered(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeGraphInfo(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), writeIndex(), ClassDefImpl::writeMemberList(), writeNamespaceIndex(), writeNamespaceMemberIndexFiltered(), writePageIndex(), FileDefImpl::writeSourceHeader(), and writeUserGroupStubPage().
startContents() [2/2]
void OutputList::startContents () [inline]
Definition at line 361 of file outputlist.h.
    { forall(&OutputGenerator::startContents); }
References forall(), and OutputGenerator::startContents().
startDescForItem() [1/2]
void OutputList::startDescForItem () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 280 of file outputlist.h.
    { forall(&OutputGenerator::startDescForItem); }
References forall(), and BaseOutputDocInterface::startDescForItem().
Referenced by MemberDefImpl::_writeExamples(), and ClassDefImpl::writeDetailedDocumentationBody().
startDescForItem() [2/2]
void OutputList::startDescForItem () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 280 of file outputlist.h.
    { forall(&OutputGenerator::startDescForItem); }
References forall(), and BaseOutputDocInterface::startDescForItem().
startDescItem() [1/2]
void OutputList::startDescItem () [inline], [virtual]
Starts an item of a description list: e.g. <dt> in HTML.
Implements BaseOutputDocInterface.
Definition at line 276 of file outputlist.h.
    { forall(&OutputGenerator::startDescItem); }
References forall(), and BaseOutputDocInterface::startDescItem().
startDescItem() [2/2]
void OutputList::startDescItem () [inline], [virtual]
Starts an item of a description list: e.g. <dt> in HTML.
Implements BaseOutputDocInterface.
Definition at line 276 of file outputlist.h.
    { forall(&OutputGenerator::startDescItem); }
References forall(), and BaseOutputDocInterface::startDescItem().
startDescription() [1/2]
void OutputList::startDescription () [inline], [virtual]
Starts a description list: e.g. <dl> in HTML Items are surrounded by startDescItem() and endDescItem()
Implements BaseOutputDocInterface.
Definition at line 272 of file outputlist.h.
    { forall(&OutputGenerator::startDescription); }
References forall(), and BaseOutputDocInterface::startDescription().
startDescription() [2/2]
void OutputList::startDescription () [inline], [virtual]
Starts a description list: e.g. <dl> in HTML Items are surrounded by startDescItem() and endDescItem()
Implements BaseOutputDocInterface.
Definition at line 272 of file outputlist.h.
    { forall(&OutputGenerator::startDescription); }
References forall(), and BaseOutputDocInterface::startDescription().
startDescTable() [1/2]
void OutputList::startDescTable (const QCString & title) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 371 of file outputlist.h.
    { forall(&OutputGenerator::startDescTable,title); }
References forall(), and BaseOutputDocInterface::startDescTable().
Referenced by MemberDefImpl::_writeEnumValues().
startDescTable() [2/2]
void OutputList::startDescTable (const QCString & title) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 371 of file outputlist.h.
    { forall(&OutputGenerator::startDescTable,title); }
References forall(), and BaseOutputDocInterface::startDescTable().
startDescTableData() [1/2]
void OutputList::startDescTableData () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 383 of file outputlist.h.
    { forall(&OutputGenerator::startDescTableData); }
References forall(), and BaseOutputDocInterface::startDescTableData().
Referenced by MemberDefImpl::_writeEnumValues().
startDescTableData() [2/2]
void OutputList::startDescTableData () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 383 of file outputlist.h.
    { forall(&OutputGenerator::startDescTableData); }
References forall(), and BaseOutputDocInterface::startDescTableData().
startDescTableRow() [1/2]
void OutputList::startDescTableRow () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 375 of file outputlist.h.
    { forall(&OutputGenerator::startDescTableRow); }
References forall(), and BaseOutputDocInterface::startDescTableRow().
Referenced by MemberDefImpl::_writeEnumValues().
startDescTableRow() [2/2]
void OutputList::startDescTableRow () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 375 of file outputlist.h.
    { forall(&OutputGenerator::startDescTableRow); }
References forall(), and BaseOutputDocInterface::startDescTableRow().
startDescTableTitle() [1/2]
void OutputList::startDescTableTitle () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 379 of file outputlist.h.
    { forall(&OutputGenerator::startDescTableTitle); }
References forall(), and BaseOutputDocInterface::startDescTableTitle().
Referenced by MemberDefImpl::_writeEnumValues().
startDescTableTitle() [2/2]
void OutputList::startDescTableTitle () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 379 of file outputlist.h.
    { forall(&OutputGenerator::startDescTableTitle); }
References forall(), and BaseOutputDocInterface::startDescTableTitle().
startDirDepGraph() [1/2]
void OutputList::startDirDepGraph () [inline]
Definition at line 399 of file outputlist.h.
    { forall(&OutputGenerator::startDirDepGraph); }
References forall(), and OutputGenerator::startDirDepGraph().
Referenced by DirDefImpl::writeDirectoryGraph().
startDirDepGraph() [2/2]
void OutputList::startDirDepGraph () [inline]
Definition at line 399 of file outputlist.h.
    { forall(&OutputGenerator::startDirDepGraph); }
References forall(), and OutputGenerator::startDirDepGraph().
startDotGraph() [1/2]
void OutputList::startDotGraph () [inline]
Definition at line 387 of file outputlist.h.
    { forall(&OutputGenerator::startDotGraph); }
References forall(), and OutputGenerator::startDotGraph().
Referenced by ClassDefImpl::writeCollaborationGraph(), and ClassDefImpl::writeInheritanceGraph().
startDotGraph() [2/2]
void OutputList::startDotGraph () [inline]
Definition at line 387 of file outputlist.h.
    { forall(&OutputGenerator::startDotGraph); }
References forall(), and OutputGenerator::startDotGraph().
startDoxyAnchor() [1/2]
void OutputList::startDoxyAnchor (const QCString & fName, const QCString & manName, const QCString & anchor, const QCString & name, const QCString & args) [inline]
Definition at line 264 of file outputlist.h.
    { forall(&OutputGenerator::startDoxyAnchor,fName,manName,anchor,name,args); }
References forall(), setup::name, and OutputGenerator::startDoxyAnchor().
Referenced by MemberDefImpl::_writeEnumValues(), MemberDefImpl::writeDeclaration(), MemberDefImpl::writeDocumentation(), MemberDefImpl::writeMemberDocSimple(), MemberList::writePlainDeclarations(), and VhdlDocGen::writeVHDLDeclaration().
startDoxyAnchor() [2/2]
void OutputList::startDoxyAnchor (const QCString & fName, const QCString & manName, const QCString & anchor, const QCString & name, const QCString & args) [inline]
Definition at line 264 of file outputlist.h.
    { forall(&OutputGenerator::startDoxyAnchor,fName,manName,anchor,name,args); }
References forall(), setup::name, and OutputGenerator::startDoxyAnchor().
startEmphasis() [1/2]
void OutputList::startEmphasis () [inline], [virtual]
Changes the text font to italic. The italic section ends with endEmphasis()
Implements BaseOutputDocInterface.
Definition at line 252 of file outputlist.h.
    { forall(&OutputGenerator::startEmphasis); }
References forall(), and BaseOutputDocInterface::startEmphasis().
Referenced by writeDefArgumentList(), VhdlDocGen::writeFuncProcDocu(), and VhdlDocGen::writeVHDLDeclaration().
startEmphasis() [2/2]
void OutputList::startEmphasis () [inline], [virtual]
Changes the text font to italic. The italic section ends with endEmphasis()
Implements BaseOutputDocInterface.
Definition at line 252 of file outputlist.h.
    { forall(&OutputGenerator::startEmphasis); }
References forall(), and BaseOutputDocInterface::startEmphasis().
startExamples() [1/2]
void OutputList::startExamples () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 319 of file outputlist.h.
    { forall(&OutputGenerator::startExamples); }
References forall(), and BaseOutputDocInterface::startExamples().
Referenced by MemberDefImpl::_writeExamples(), and ClassDefImpl::writeDetailedDocumentationBody().
startExamples() [2/2]
void OutputList::startExamples () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 319 of file outputlist.h.
    { forall(&OutputGenerator::startExamples); }
References forall(), and BaseOutputDocInterface::startExamples().
startFile() [1/2]
void OutputList::startFile (const QCString & name, const QCString & manName, const QCString & title) [inline]
Definition at line 88 of file outputlist.h.
    {
      newId();
      forall(&OutputGenerator::startFile,name,manName,title,m_id);
    }
References forall(), m_id, setup::name, newId(), and OutputGenerator::startFile().
Referenced by startFile(), writeClassMemberIndexFiltered(), writeFileMemberIndexFiltered(), writeIndex(), and writeNamespaceMemberIndexFiltered().
startFile() [2/2]
void OutputList::startFile (const QCString & name, const QCString & manName, const QCString & title) [inline]
Definition at line 88 of file outputlist.h.
    {
      newId();
      forall(&OutputGenerator::startFile,name,manName,title,m_id);
    }
References forall(), m_id, setup::name, newId(), and OutputGenerator::startFile().
startFontClass() [1/2]
void OutputList::startFontClass (const QCString & clsName) [inline], [virtual]
Starts a block with a certain meaning. Used for syntax highlighting, which elements of the same type are rendered using the same 'font class'.
Parameters
clsName The category name.
Implements CodeOutputInterface.
Definition at line 482 of file outputlist.h.
    { forall(&OutputGenerator::startFontClass,c); }
References c, forall(), and CodeOutputInterface::startFontClass().
Referenced by startFonts().
startFontClass() [2/2]
void OutputList::startFontClass (const QCString & clsName) [inline], [virtual]
Starts a block with a certain meaning. Used for syntax highlighting, which elements of the same type are rendered using the same 'font class'.
Parameters
clsName The category name.
Implements CodeOutputInterface.
Definition at line 482 of file outputlist.h.
    { forall(&OutputGenerator::startFontClass,c); }
References c, forall(), and CodeOutputInterface::startFontClass().
startGroupCollaboration() [1/2]
void OutputList::startGroupCollaboration () [inline]
Definition at line 403 of file outputlist.h.
    { forall(&OutputGenerator::startGroupCollaboration); }
References forall(), and OutputGenerator::startGroupCollaboration().
Referenced by GroupDefImpl::writeGroupGraph().
startGroupCollaboration() [2/2]
void OutputList::startGroupCollaboration () [inline]
Definition at line 403 of file outputlist.h.
    { forall(&OutputGenerator::startGroupCollaboration); }
References forall(), and OutputGenerator::startGroupCollaboration().
startGroupHeader() [1/2]
void OutputList::startGroupHeader (int extraLevels = 0) [inline]
Definition at line 169 of file outputlist.h.
    { forall(&OutputGenerator::startGroupHeader,extraLevels); }
References forall(), and OutputGenerator::startGroupHeader().
Referenced by FileDefImpl::writeAuthorSection(), GroupDefImpl::writeAuthorSection(), NamespaceDefImpl::writeAuthorSection(), ClassDefImpl::writeAuthorSection(), ConceptDefImpl::writeAuthorSection(), ConceptDefImpl::writeDefinition(), ClassDefImpl::writeDetailedDescription(), DirDefImpl::writeDetailedDescription(), FileDefImpl::writeDetailedDescription(), GroupDefImpl::writeDetailedDescription(), NamespaceDefImpl::writeDetailedDescription(), ConceptDefImpl::writeDetailedDescription(), ClassLinkedRefMap::writeDocumentation(), MemberList::writeDocumentation(), and ClassDefImpl::writeInlineDocumentation().
startGroupHeader() [2/2]
void OutputList::startGroupHeader (int extraLevels = 0) [inline]
Definition at line 169 of file outputlist.h.
    { forall(&OutputGenerator::startGroupHeader,extraLevels); }
References forall(), and OutputGenerator::startGroupHeader().
startHeaderSection() [1/2]
void OutputList::startHeaderSection () [inline]
Definition at line 181 of file outputlist.h.
    { forall(&OutputGenerator::startHeaderSection); }
References forall(), and OutputGenerator::startHeaderSection().
Referenced by startTitle(), GroupDefImpl::writeDocumentation(), and writeIndex().
startHeaderSection() [2/2]
void OutputList::startHeaderSection () [inline]
Definition at line 181 of file outputlist.h.
    { forall(&OutputGenerator::startHeaderSection); }
References forall(), and OutputGenerator::startHeaderSection().
startHtmlLink() [1/2]
void OutputList::startHtmlLink (const QCString & url) [inline], [virtual]
Starts a (link to an) URL found in the documentation.
Parameters
url The URL to link to.
Implements BaseOutputDocInterface.
Definition at line 156 of file outputlist.h.
    { forall(&OutputGenerator::startHtmlLink,url); }
References forall(), BaseOutputDocInterface::startHtmlLink(), and setup::url.
startHtmlLink() [2/2]
void OutputList::startHtmlLink (const QCString & url) [inline], [virtual]
Starts a (link to an) URL found in the documentation.
Parameters
url The URL to link to.
Implements BaseOutputDocInterface.
Definition at line 156 of file outputlist.h.
    { forall(&OutputGenerator::startHtmlLink,url); }
References forall(), BaseOutputDocInterface::startHtmlLink(), and setup::url.
startInclDepGraph() [1/2]
void OutputList::startInclDepGraph () [inline]
Definition at line 391 of file outputlist.h.
    { forall(&OutputGenerator::startInclDepGraph); }
References forall(), and OutputGenerator::startInclDepGraph().
Referenced by FileDefImpl::writeIncludedByGraph(), and FileDefImpl::writeIncludeGraph().
startInclDepGraph() [2/2]
void OutputList::startInclDepGraph () [inline]
Definition at line 391 of file outputlist.h.
    { forall(&OutputGenerator::startInclDepGraph); }
References forall(), and OutputGenerator::startInclDepGraph().
startIndent() [1/2]
void OutputList::startIndent () [inline]
Definition at line 327 of file outputlist.h.
    { forall(&OutputGenerator::startIndent); }
References forall(), and OutputGenerator::startIndent().
Referenced by MemberDefImpl::writeDocumentation(), and ClassDefImpl::writeInlineDocumentation().
startIndent() [2/2]
void OutputList::startIndent () [inline]
Definition at line 327 of file outputlist.h.
    { forall(&OutputGenerator::startIndent); }
References forall(), and OutputGenerator::startIndent().
startIndexItem() [1/2]
void OutputList::startIndexItem (const QCString & ref, const QCString & file) [inline]
Definition at line 133 of file outputlist.h.
    { forall(&OutputGenerator::startIndexItem,ref,file); }
References caseconvert::file, forall(), and OutputGenerator::startIndexItem().
Referenced by writeClassTreeForList(), writeClassTreeToOutput(), writeDirTreeNode(), and writeGroupTreeNode().
startIndexItem() [2/2]
void OutputList::startIndexItem (const QCString & ref, const QCString & file) [inline]
Definition at line 133 of file outputlist.h.
    { forall(&OutputGenerator::startIndexItem,ref,file); }
References caseconvert::file, forall(), and OutputGenerator::startIndexItem().
startIndexKey() [1/2]
void OutputList::startIndexKey () [inline]
Definition at line 121 of file outputlist.h.
    { forall(&OutputGenerator::startIndexKey); }
References forall(), and OutputGenerator::startIndexKey().
Referenced by writeAnnotatedClassList(), writeConceptIndex(), writeNamespaceIndex(), and writeSingleFileIndex().
startIndexKey() [2/2]
void OutputList::startIndexKey () [inline]
Definition at line 121 of file outputlist.h.
    { forall(&OutputGenerator::startIndexKey); }
References forall(), and OutputGenerator::startIndexKey().
startIndexList() [1/2]
void OutputList::startIndexList () [inline]
Definition at line 117 of file outputlist.h.
    { forall(&OutputGenerator::startIndexList); }
References forall(), and OutputGenerator::startIndexList().
Referenced by startIndexHierarchy(), writeAnnotatedClassList(), writeConceptIndex(), writeFileIndex(), and writeNamespaceIndex().
startIndexList() [2/2]
void OutputList::startIndexList () [inline]
Definition at line 117 of file outputlist.h.
    { forall(&OutputGenerator::startIndexList); }
References forall(), and OutputGenerator::startIndexList().
startIndexListItem() [1/2]
void OutputList::startIndexListItem () [inline]
Definition at line 113 of file outputlist.h.
    { forall(&OutputGenerator::startIndexListItem); }
References forall(), and OutputGenerator::startIndexListItem().
Referenced by writeClassTreeForList(), writeClassTreeToOutput(), writeDirTreeNode(), and writeGroupTreeNode().
startIndexListItem() [2/2]
void OutputList::startIndexListItem () [inline]
Definition at line 113 of file outputlist.h.
    { forall(&OutputGenerator::startIndexListItem); }
References forall(), and OutputGenerator::startIndexListItem().
startIndexSection() [1/2]
void OutputList::startIndexSection (IndexSections is) [inline]
Definition at line 76 of file outputlist.h.
    { forall(&OutputGenerator::startIndexSection,is); }
References forall(), and OutputGenerator::startIndexSection().
Referenced by writeIndex().
startIndexSection() [2/2]
void OutputList::startIndexSection (IndexSections is) [inline]
Definition at line 76 of file outputlist.h.
    { forall(&OutputGenerator::startIndexSection,is); }
References forall(), and OutputGenerator::startIndexSection().
startIndexValue() [1/2]
void OutputList::startIndexValue (bool b) [inline]
Definition at line 125 of file outputlist.h.
    { forall(&OutputGenerator::startIndexValue,b); }
References b, forall(), and OutputGenerator::startIndexValue().
Referenced by writeAnnotatedClassList(), writeConceptIndex(), writeNamespaceIndex(), and writeSingleFileIndex().
startIndexValue() [2/2]
void OutputList::startIndexValue (bool b) [inline]
Definition at line 125 of file outputlist.h.
    { forall(&OutputGenerator::startIndexValue,b); }
References b, forall(), and OutputGenerator::startIndexValue().
startInlineHeader() [1/2]
void OutputList::startInlineHeader () [inline]
Definition at line 201 of file outputlist.h.
    { forall(&OutputGenerator::startInlineHeader); }
References forall(), and OutputGenerator::startInlineHeader().
Referenced by MemberList::writeDeclarations().
startInlineHeader() [2/2]
void OutputList::startInlineHeader () [inline]
Definition at line 201 of file outputlist.h.
    { forall(&OutputGenerator::startInlineHeader); }
References forall(), and OutputGenerator::startInlineHeader().
startInlineMemberDoc() [1/2]
void OutputList::startInlineMemberDoc () [inline]
Definition at line 467 of file outputlist.h.
    { forall(&OutputGenerator::startInlineMemberDoc); }
References forall(), and OutputGenerator::startInlineMemberDoc().
Referenced by MemberDefImpl::writeMemberDocSimple().
startInlineMemberDoc() [2/2]
void OutputList::startInlineMemberDoc () [inline]
Definition at line 467 of file outputlist.h.
    { forall(&OutputGenerator::startInlineMemberDoc); }
References forall(), and OutputGenerator::startInlineMemberDoc().
startInlineMemberName() [1/2]
void OutputList::startInlineMemberName () [inline]
Definition at line 463 of file outputlist.h.
    { forall(&OutputGenerator::startInlineMemberName); }
References forall(), and OutputGenerator::startInlineMemberName().
Referenced by MemberDefImpl::writeMemberDocSimple().
startInlineMemberName() [2/2]
void OutputList::startInlineMemberName () [inline]
Definition at line 463 of file outputlist.h.
    { forall(&OutputGenerator::startInlineMemberName); }
References forall(), and OutputGenerator::startInlineMemberName().
startInlineMemberType() [1/2]
void OutputList::startInlineMemberType () [inline]
Definition at line 459 of file outputlist.h.
    { forall(&OutputGenerator::startInlineMemberType); }
References forall(), and OutputGenerator::startInlineMemberType().
Referenced by MemberDefImpl::writeMemberDocSimple().
startInlineMemberType() [2/2]
void OutputList::startInlineMemberType () [inline]
Definition at line 459 of file outputlist.h.
    { forall(&OutputGenerator::startInlineMemberType); }
References forall(), and OutputGenerator::startInlineMemberType().
startItemList() [1/2]
void OutputList::startItemList () [inline], [virtual]
Start of a bullet list: e.g. <ul> in html. startItemListItem() is Used for the bullet items.
Implements BaseOutputDocInterface.
Definition at line 129 of file outputlist.h.
    { forall(&OutputGenerator::startItemList); }
References forall(), and BaseOutputDocInterface::startItemList().
Referenced by ClassDefImpl::showUsedFiles(), startIndexHierarchy(), writeExampleIndex(), and writeMemberList().
startItemList() [2/2]
void OutputList::startItemList () [inline], [virtual]
Start of a bullet list: e.g. <ul> in html. startItemListItem() is Used for the bullet items.
Implements BaseOutputDocInterface.
Definition at line 129 of file outputlist.h.
    { forall(&OutputGenerator::startItemList); }
References forall(), and BaseOutputDocInterface::startItemList().
startItemListItem() [1/2]
void OutputList::startItemListItem () [inline], [virtual]
Writes a list item for a bullet or enumerated list: e.g. <li> in html
Implements BaseOutputDocInterface.
Definition at line 173 of file outputlist.h.
    { forall(&OutputGenerator::startItemListItem); }
References forall(), and BaseOutputDocInterface::startItemListItem().
Referenced by ClassDefImpl::showUsedFiles(), writeExampleIndex(), and writeMemberList().
startItemListItem() [2/2]
void OutputList::startItemListItem () [inline], [virtual]
Writes a list item for a bullet or enumerated list: e.g. <li> in html
Implements BaseOutputDocInterface.
Definition at line 173 of file outputlist.h.
    { forall(&OutputGenerator::startItemListItem); }
References forall(), and BaseOutputDocInterface::startItemListItem().
startLabels() [1/2]
void OutputList::startLabels () [inline]
Definition at line 472 of file outputlist.h.
    { forall(&OutputGenerator::startLabels); }
References forall(), and OutputGenerator::startLabels().
Referenced by ClassDefImpl::addClassAttributes(), NamespaceDefImpl::addNamespaceAttributes(), and MemberDefImpl::writeDocumentation().
startLabels() [2/2]
void OutputList::startLabels () [inline]
Definition at line 472 of file outputlist.h.
    { forall(&OutputGenerator::startLabels); }
References forall(), and OutputGenerator::startLabels().
startMemberDeclaration() [1/2]
void OutputList::startMemberDeclaration () [inline]
Definition at line 310 of file outputlist.h.
    { forall(&OutputGenerator::startMemberDeclaration); }
References forall(), and OutputGenerator::startMemberDeclaration().
Referenced by MemberDefImpl::writeDeclaration(), NamespaceLinkedRefMap::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), ConceptDefImpl::writeDeclarationLink(), GroupDefImpl::writeDirs(), DirDefImpl::writeFileList(), GroupDefImpl::writeFiles(), GroupDefImpl::writeNestedGroups(), MemberList::writePlainDeclarations(), and DirDefImpl::writeSubDirList().
startMemberDeclaration() [2/2]
void OutputList::startMemberDeclaration () [inline]
Definition at line 310 of file outputlist.h.
    { forall(&OutputGenerator::startMemberDeclaration); }
References forall(), and OutputGenerator::startMemberDeclaration().
startMemberDescription() [1/2]
void OutputList::startMemberDescription (const QCString & anchor, const QCString & inheritId = QCString(), bool typ = false) [inline]
Definition at line 306 of file outputlist.h.
    { forall(&OutputGenerator::startMemberDescription,anchor,inheritId, typ); }
References forall(), and OutputGenerator::startMemberDescription().
Referenced by MemberDefImpl::writeDeclaration(), NamespaceLinkedRefMap::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), ConceptDefImpl::writeDeclarationLink(), GroupDefImpl::writeDirs(), DirDefImpl::writeFileList(), GroupDefImpl::writeFiles(), GroupDefImpl::writeNestedGroups(), MemberList::writePlainDeclarations(), DirDefImpl::writeSubDirList(), and VhdlDocGen::writeVHDLDeclaration().
startMemberDescription() [2/2]
void OutputList::startMemberDescription (const QCString & anchor, const QCString & inheritId = QCString(), bool typ = false) [inline]
Definition at line 306 of file outputlist.h.
    { forall(&OutputGenerator::startMemberDescription,anchor,inheritId, typ); }
References forall(), and OutputGenerator::startMemberDescription().
startMemberDoc() [1/2]
void OutputList::startMemberDoc (const QCString & clName, const QCString & memName, const QCString & anchor, const QCString & title, int memCount, int memTotal, bool showInline) [inline]
Definition at line 258 of file outputlist.h.
    { forall(&OutputGenerator::startMemberDoc,clName,memName,anchor,title,memCount,memTotal,showInline); }
References forall(), and OutputGenerator::startMemberDoc().
Referenced by MemberDefImpl::writeDocumentation(), and ClassDefImpl::writeInlineDocumentation().
startMemberDoc() [2/2]
void OutputList::startMemberDoc (const QCString & clName, const QCString & memName, const QCString & anchor, const QCString & title, int memCount, int memTotal, bool showInline) [inline]
Definition at line 258 of file outputlist.h.
    { forall(&OutputGenerator::startMemberDoc,clName,memName,anchor,title,memCount,memTotal,showInline); }
References forall(), and OutputGenerator::startMemberDoc().
startMemberDocList() [1/2]
void OutputList::startMemberDocList () [inline]
Definition at line 193 of file outputlist.h.
    { forall(&OutputGenerator::startMemberDocList); }
References forall(), and OutputGenerator::startMemberDocList().
Referenced by MemberList::writeDocumentation().
startMemberDocList() [2/2]
void OutputList::startMemberDocList () [inline]
Definition at line 193 of file outputlist.h.
    { forall(&OutputGenerator::startMemberDocList); }
References forall(), and OutputGenerator::startMemberDocList().
startMemberDocName() [1/2]
void OutputList::startMemberDocName (bool align) [inline]
Definition at line 419 of file outputlist.h.
    { forall(&OutputGenerator::startMemberDocName,align); }
References align(), forall(), and OutputGenerator::startMemberDocName().
Referenced by MemberDefImpl::writeDocumentation(), and ClassDefImpl::writeInlineDocumentation().
startMemberDocName() [2/2]
void OutputList::startMemberDocName (bool align) [inline]
Definition at line 419 of file outputlist.h.
    { forall(&OutputGenerator::startMemberDocName,align); }
References align(), forall(), and OutputGenerator::startMemberDocName().
startMemberDocPrefixItem() [1/2]
void OutputList::startMemberDocPrefixItem () [inline]
Definition at line 415 of file outputlist.h.
    { forall(&OutputGenerator::startMemberDocPrefixItem); }
References forall(), and OutputGenerator::startMemberDocPrefixItem().
Referenced by MemberDefImpl::writeDocumentation().
startMemberDocPrefixItem() [2/2]
void OutputList::startMemberDocPrefixItem () [inline]
Definition at line 415 of file outputlist.h.
    { forall(&OutputGenerator::startMemberDocPrefixItem); }
References forall(), and OutputGenerator::startMemberDocPrefixItem().
startMemberDocSimple() [1/2]
void OutputList::startMemberDocSimple (bool b) [inline]
Definition at line 455 of file outputlist.h.
    { forall(&OutputGenerator::startMemberDocSimple,b); }
References b, forall(), and OutputGenerator::startMemberDocSimple().
Referenced by MemberList::writeSimpleDocumentation().
startMemberDocSimple() [2/2]
void OutputList::startMemberDocSimple (bool b) [inline]
Definition at line 455 of file outputlist.h.
    { forall(&OutputGenerator::startMemberDocSimple,b); }
References b, forall(), and OutputGenerator::startMemberDocSimple().
startMemberGroup() [1/2]
void OutputList::startMemberGroup () [inline]
Definition at line 229 of file outputlist.h.
    { forall(&OutputGenerator::startMemberGroup); }
References forall(), and OutputGenerator::startMemberGroup().
Referenced by MemberList::writeDeclarations(), and VhdlDocGen::writeVHDLDeclarations().
startMemberGroup() [2/2]
void OutputList::startMemberGroup () [inline]
Definition at line 229 of file outputlist.h.
    { forall(&OutputGenerator::startMemberGroup); }
References forall(), and OutputGenerator::startMemberGroup().
startMemberGroupDocs() [1/2]
void OutputList::startMemberGroupDocs () [inline]
Definition at line 225 of file outputlist.h.
    { forall(&OutputGenerator::startMemberGroupDocs); }
References forall(), and OutputGenerator::startMemberGroupDocs().
Referenced by MemberList::writeDeclarations(), and VhdlDocGen::writeVHDLDeclarations().
startMemberGroupDocs() [2/2]
void OutputList::startMemberGroupDocs () [inline]
Definition at line 225 of file outputlist.h.
    { forall(&OutputGenerator::startMemberGroupDocs); }
References forall(), and OutputGenerator::startMemberGroupDocs().
startMemberGroupHeader() [1/2]
void OutputList::startMemberGroupHeader (bool b) [inline]
Definition at line 221 of file outputlist.h.
    { forall(&OutputGenerator::startMemberGroupHeader,b); }
References b, forall(), and OutputGenerator::startMemberGroupHeader().
Referenced by MemberList::writeDeclarations(), and VhdlDocGen::writeVHDLDeclarations().
startMemberGroupHeader() [2/2]
void OutputList::startMemberGroupHeader (bool b) [inline]
Definition at line 221 of file outputlist.h.
    { forall(&OutputGenerator::startMemberGroupHeader,b); }
References b, forall(), and OutputGenerator::startMemberGroupHeader().
startMemberHeader() [1/2]
void OutputList::startMemberHeader (const QCString & anchor, int typ = 2) [inline]
Definition at line 185 of file outputlist.h.
    { forall(&OutputGenerator::startMemberHeader,anchor,typ); }
References forall(), and OutputGenerator::startMemberHeader().
Referenced by ClassDefImpl::endMemberDeclarations(), NamespaceLinkedRefMap::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), ConceptDefImpl::writeDeclarationLink(), MemberList::writeDeclarations(), GroupDefImpl::writeDirs(), DirDefImpl::writeFileList(), GroupDefImpl::writeFiles(), GroupDefImpl::writeNestedGroups(), DirDefImpl::writeSubDirList(), and VhdlDocGen::writeVHDLDeclarations().
startMemberHeader() [2/2]
void OutputList::startMemberHeader (const QCString & anchor, int typ = 2) [inline]
Definition at line 185 of file outputlist.h.
    { forall(&OutputGenerator::startMemberHeader,anchor,typ); }
References forall(), and OutputGenerator::startMemberHeader().
startMemberItem() [1/2]
void OutputList::startMemberItem (const QCString & anchor, int i1, const QCString & id = QCString()) [inline]
Definition at line 209 of file outputlist.h.
    { forall(&OutputGenerator::startMemberItem,anchor,i1,id); }
References forall(), and OutputGenerator::startMemberItem().
Referenced by MemberDefImpl::writeDeclaration(), NamespaceLinkedRefMap::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), ConceptDefImpl::writeDeclarationLink(), GroupDefImpl::writeDirs(), DirDefImpl::writeFileList(), GroupDefImpl::writeFiles(), GroupDefImpl::writeNestedGroups(), MemberList::writePlainDeclarations(), DirDefImpl::writeSubDirList(), and VhdlDocGen::writeVHDLDeclaration().
startMemberItem() [2/2]
void OutputList::startMemberItem (const QCString & anchor, int i1, const QCString & id = QCString()) [inline]
Definition at line 209 of file outputlist.h.
    { forall(&OutputGenerator::startMemberItem,anchor,i1,id); }
References forall(), and OutputGenerator::startMemberItem().
startMemberList() [1/2]
void OutputList::startMemberList () [inline]
Definition at line 197 of file outputlist.h.
    { forall(&OutputGenerator::startMemberList); }
References forall(), and OutputGenerator::startMemberList().
Referenced by NamespaceLinkedRefMap::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), ConceptDefImpl::writeDeclarationLink(), GroupDefImpl::writeDirs(), DirDefImpl::writeFileList(), GroupDefImpl::writeFiles(), GroupDefImpl::writeNestedGroups(), MemberList::writePlainDeclarations(), VhdlDocGen::writePlainVHDLDeclarations(), and DirDefImpl::writeSubDirList().
startMemberList() [2/2]
void OutputList::startMemberList () [inline]
Definition at line 197 of file outputlist.h.
    { forall(&OutputGenerator::startMemberList); }
References forall(), and OutputGenerator::startMemberList().
startMemberSections() [1/2]
void OutputList::startMemberSections () [inline]
Definition at line 177 of file outputlist.h.
    { forall(&OutputGenerator::startMemberSections); }
References forall(), and OutputGenerator::startMemberSections().
Referenced by DirDefImpl::startMemberDeclarations(), FileDefImpl::startMemberDeclarations(), GroupDefImpl::startMemberDeclarations(), NamespaceDefImpl::startMemberDeclarations(), and ClassDefImpl::startMemberDeclarations().
startMemberSections() [2/2]
void OutputList::startMemberSections () [inline]
Definition at line 177 of file outputlist.h.
    { forall(&OutputGenerator::startMemberSections); }
References forall(), and OutputGenerator::startMemberSections().
startMemberSubtitle() [1/2]
void OutputList::startMemberSubtitle () [inline]
Definition at line 189 of file outputlist.h.
    { forall(&OutputGenerator::startMemberSubtitle); }
References forall(), and OutputGenerator::startMemberSubtitle().
Referenced by MemberList::writeDeclarations(), and VhdlDocGen::writeVHDLDeclarations().
startMemberSubtitle() [2/2]
void OutputList::startMemberSubtitle () [inline]
Definition at line 189 of file outputlist.h.
    { forall(&OutputGenerator::startMemberSubtitle); }
References forall(), and OutputGenerator::startMemberSubtitle().
startMemberTemplateParams() [1/2]
void OutputList::startMemberTemplateParams () [inline]
Definition at line 213 of file outputlist.h.
    { forall(&OutputGenerator::startMemberTemplateParams); }
References forall(), and OutputGenerator::startMemberTemplateParams().
Referenced by MemberDefImpl::writeDeclaration().
startMemberTemplateParams() [2/2]
void OutputList::startMemberTemplateParams () [inline]
Definition at line 213 of file outputlist.h.
    { forall(&OutputGenerator::startMemberTemplateParams); }
References forall(), and OutputGenerator::startMemberTemplateParams().
startPageDoc() [1/2]
void OutputList::startPageDoc (const QCString & pageTitle) [inline]
Definition at line 365 of file outputlist.h.
    { forall(&OutputGenerator::startPageDoc, pageTitle); }
References forall(), and OutputGenerator::startPageDoc().
Referenced by PageDefImpl::writeDocumentation(), and writeIndex().
startPageDoc() [2/2]
void OutputList::startPageDoc (const QCString & pageTitle) [inline]
Definition at line 365 of file outputlist.h.
    { forall(&OutputGenerator::startPageDoc, pageTitle); }
References forall(), and OutputGenerator::startPageDoc().
startPageRef() [1/2]
void OutputList::startPageRef () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 343 of file outputlist.h.
    { forall(&OutputGenerator::startPageRef); }
References forall(), and BaseOutputDocInterface::startPageRef().
Referenced by writePageRef().
startPageRef() [2/2]
void OutputList::startPageRef () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 343 of file outputlist.h.
    { forall(&OutputGenerator::startPageRef); }
References forall(), and BaseOutputDocInterface::startPageRef().
startParagraph() [1/2]
void OutputList::startParagraph (const QCString & classDef = QCString()) [inline], [virtual]
Starts a new paragraph
Starts a new paragraph
Implements BaseOutputDocInterface.
Definition at line 107 of file outputlist.h.
    { forall(&OutputGenerator::startParagraph,classDef); }
References forall(), and BaseOutputDocInterface::startParagraph().
Referenced by MemberDefImpl::_writeCategoryRelation(), MemberDefImpl::_writeGroupInclude(), MemberDefImpl::_writeReimplementedBy(), MemberDefImpl::_writeReimplements(), DefinitionImpl::_writeSourceRefList(), ClassDefImpl::showUsedFiles(), ConceptDefImpl::writeBriefDescription(), DirDefImpl::writeBriefDescription(), FileDefImpl::writeBriefDescription(), GroupDefImpl::writeBriefDescription(), NamespaceDefImpl::writeBriefDescription(), ClassDefImpl::writeBriefDescription(), MemberDefImpl::writeDeclaration(), FileDefImpl::writeDetailedDescription(), MemberDefImpl::writeDocumentation(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), ClassDefImpl::writeIncludeFiles(), ConceptDefImpl::writeIncludeFiles(), ClassDefImpl::writeIncludeFilesForSlice(), ClassDefImpl::writeInheritanceGraph(), ClassDefImpl::writeMemberList(), DefinitionImpl::writeSourceDef(), and FileDefImpl::writeSourceLink().
startParagraph() [2/2]
void OutputList::startParagraph (const QCString & classDef = QCString()) [inline], [virtual]
Starts a new paragraph
Starts a new paragraph
Implements BaseOutputDocInterface.
Definition at line 107 of file outputlist.h.
    { forall(&OutputGenerator::startParagraph,classDef); }
References forall(), and BaseOutputDocInterface::startParagraph().
startParameterList() [1/2]
void OutputList::startParameterList (bool openBracket) [inline]
Definition at line 431 of file outputlist.h.
    { forall(&OutputGenerator::startParameterList,openBracket); }
References forall(), and OutputGenerator::startParameterList().
Referenced by writeDefArgumentList(), VhdlDocGen::writeFuncProcDocu(), and VhdlDocGen::writeRecUnitDocu().
startParameterList() [2/2]
void OutputList::startParameterList (bool openBracket) [inline]
Definition at line 431 of file outputlist.h.
    { forall(&OutputGenerator::startParameterList,openBracket); }
References forall(), and OutputGenerator::startParameterList().
startParameterName() [1/2]
void OutputList::startParameterName (bool one) [inline]
Definition at line 427 of file outputlist.h.
    { forall(&OutputGenerator::startParameterName,one); }
References forall(), and OutputGenerator::startParameterName().
Referenced by writeDefArgumentList(), VhdlDocGen::writeFuncProcDocu(), and VhdlDocGen::writeRecUnitDocu().
startParameterName() [2/2]
void OutputList::startParameterName (bool one) [inline]
Definition at line 427 of file outputlist.h.
    { forall(&OutputGenerator::startParameterName,one); }
References forall(), and OutputGenerator::startParameterName().
startParameterType() [1/2]
void OutputList::startParameterType (bool first, const QCString & key) [inline]
Definition at line 423 of file outputlist.h.
    { forall(&OutputGenerator::startParameterType,first,key); }
References forall(), and OutputGenerator::startParameterType().
Referenced by writeDefArgumentList(), VhdlDocGen::writeFuncProcDocu(), and VhdlDocGen::writeRecUnitDocu().
startParameterType() [2/2]
void OutputList::startParameterType (bool first, const QCString & key) [inline]
Definition at line 423 of file outputlist.h.
    { forall(&OutputGenerator::startParameterType,first,key); }
References forall(), and OutputGenerator::startParameterType().
startParamList() [1/2]
void OutputList::startParamList (ParamListTypes t, const QCString & title) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 323 of file outputlist.h.
    { forall(&OutputGenerator::startParamList,t,title); }
References forall(), and BaseOutputDocInterface::startParamList().
startParamList() [2/2]
void OutputList::startParamList (ParamListTypes t, const QCString & title) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 323 of file outputlist.h.
    { forall(&OutputGenerator::startParamList,t,title); }
References forall(), and BaseOutputDocInterface::startParamList().
startPlainFile() [1/2]
void OutputList::startPlainFile (const QCString & name) [inline]
Definition at line 502 of file outputlist.h.
    { forall(&OutputGenerator::startPlainFile,name); }
References forall(), setup::name, and OutputGenerator::startPlainFile().
startPlainFile() [2/2]
void OutputList::startPlainFile (const QCString & name) [inline]
Definition at line 502 of file outputlist.h.
    { forall(&OutputGenerator::startPlainFile,name); }
References forall(), setup::name, and OutputGenerator::startPlainFile().
startProjectNumber() [1/2]
void OutputList::startProjectNumber () [inline]
Definition at line 82 of file outputlist.h.
    { forall(&OutputGenerator::startProjectNumber); }
References forall(), and OutputGenerator::startProjectNumber().
Referenced by FileDefImpl::writeDocumentation(), and writeIndex().
startProjectNumber() [2/2]
void OutputList::startProjectNumber () [inline]
Definition at line 82 of file outputlist.h.
    { forall(&OutputGenerator::startProjectNumber); }
References forall(), and OutputGenerator::startProjectNumber().
startQuickIndices() [1/2]
void OutputList::startQuickIndices () [inline]
Definition at line 347 of file outputlist.h.
    { forall(&OutputGenerator::startQuickIndices); }
References forall(), and OutputGenerator::startQuickIndices().
Referenced by startFile(), writeClassMemberIndexFiltered(), writeFileMemberIndexFiltered(), writeIndex(), and writeNamespaceMemberIndexFiltered().
startQuickIndices() [2/2]
void OutputList::startQuickIndices () [inline]
Definition at line 347 of file outputlist.h.
    { forall(&OutputGenerator::startQuickIndices); }
References forall(), and OutputGenerator::startQuickIndices().
startSection() [1/2]
void OutputList::startSection (const QCString & lab, const QCString & title, SectionType t) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 331 of file outputlist.h.
    { forall(&OutputGenerator::startSection,lab,title,t); }
References forall(), and BaseOutputDocInterface::startSection().
Referenced by writeMemberList(), GroupDefImpl::writePageDocumentation(), and PageDefImpl::writePageDocumentation().
startSection() [2/2]
void OutputList::startSection (const QCString & lab, const QCString & title, SectionType t) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 331 of file outputlist.h.
    { forall(&OutputGenerator::startSection,lab,title,t); }
References forall(), and BaseOutputDocInterface::startSection().
startSmall() [1/2]
void OutputList::startSmall () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 296 of file outputlist.h.
    { forall(&OutputGenerator::startSmall); }
References forall(), and BaseOutputDocInterface::startSmall().
startSmall() [2/2]
void OutputList::startSmall () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 296 of file outputlist.h.
    { forall(&OutputGenerator::startSmall); }
References forall(), and BaseOutputDocInterface::startSmall().
startSubsection() [1/2]
void OutputList::startSubsection () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 284 of file outputlist.h.
    { forall(&OutputGenerator::startSubsection); }
References forall(), and BaseOutputDocInterface::startSubsection().
startSubsection() [2/2]
void OutputList::startSubsection () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 284 of file outputlist.h.
    { forall(&OutputGenerator::startSubsection); }
References forall(), and BaseOutputDocInterface::startSubsection().
startSubsubsection() [1/2]
void OutputList::startSubsubsection () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 288 of file outputlist.h.
    { forall(&OutputGenerator::startSubsubsection); }
References forall(), and BaseOutputDocInterface::startSubsubsection().
startSubsubsection() [2/2]
void OutputList::startSubsubsection () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 288 of file outputlist.h.
    { forall(&OutputGenerator::startSubsubsection); }
References forall(), and BaseOutputDocInterface::startSubsubsection().
startTextBlock() [1/2]
void OutputList::startTextBlock (bool dense = FALSE) [inline]
Definition at line 409 of file outputlist.h.
    { forall(&OutputGenerator::startTextBlock,dense); }
References forall(), and OutputGenerator::startTextBlock().
Referenced by writeAnnotatedIndexGeneric(), writeClassMemberIndexFiltered(), writeConceptIndex(), FileDefImpl::writeDetailedDescription(), NamespaceDefImpl::writeDetailedDescription(), ConceptDefImpl::writeDetailedDescription(), ClassDefImpl::writeDetailedDocumentationBody(), writeExampleIndex(), writeFileIndex(), writeFileMemberIndexFiltered(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), FileDefImpl::writeIncludedByGraph(), FileDefImpl::writeIncludeFiles(), FileDefImpl::writeIncludeGraph(), writeIndex(), writeNamespaceIndex(), writeNamespaceMemberIndexFiltered(), GroupDefImpl::writePageDocumentation(), PageDefImpl::writePageDocumentation(), and writePageIndex().
startTextBlock() [2/2]
void OutputList::startTextBlock (bool dense = FALSE) [inline]
Definition at line 409 of file outputlist.h.
    { forall(&OutputGenerator::startTextBlock,dense); }
References forall(), and OutputGenerator::startTextBlock().
startTextLink() [1/2]
void OutputList::startTextLink (const QCString & file, const QCString & anchor) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 152 of file outputlist.h.
    { forall(&OutputGenerator::startTextLink,file,anchor); }
References caseconvert::file, forall(), and BaseOutputDocInterface::startTextLink().
Referenced by ConceptDefImpl::writeBriefDescription(), DirDefImpl::writeBriefDescription(), FileDefImpl::writeBriefDescription(), GroupDefImpl::writeBriefDescription(), NamespaceDefImpl::writeBriefDescription(), MemberDefImpl::writeDeclaration(), DirDefImpl::writeFileList(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), ClassDefImpl::writeMoreLink(), MemberList::writePlainDeclarations(), writeSingleFileIndex(), FileDefImpl::writeSourceHeader(), FileDefImpl::writeSourceLink(), and VhdlDocGen::writeVHDLDeclaration().
startTextLink() [2/2]
void OutputList::startTextLink (const QCString & file, const QCString & anchor) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 152 of file outputlist.h.
    { forall(&OutputGenerator::startTextLink,file,anchor); }
References caseconvert::file, forall(), and BaseOutputDocInterface::startTextLink().
startTitle() [1/2]
void OutputList::startTitle () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 103 of file outputlist.h.
    { forall(&OutputGenerator::startTitle); }
References forall(), and BaseOutputDocInterface::startTitle().
startTitle() [2/2]
void OutputList::startTitle () [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 103 of file outputlist.h.
    { forall(&OutputGenerator::startTitle); }
References forall(), and BaseOutputDocInterface::startTitle().
startTitleHead() [1/2]
void OutputList::startTitleHead (const QCString & fileName) [inline]
Definition at line 99 of file outputlist.h.
    { forall(&OutputGenerator::startTitleHead,fileName); }
References forall(), and OutputGenerator::startTitleHead().
Referenced by startTitle(), GroupDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), and writeIndex().
startTitleHead() [2/2]
void OutputList::startTitleHead (const QCString & fileName) [inline]
Definition at line 99 of file outputlist.h.
    { forall(&OutputGenerator::startTitleHead,fileName); }
References forall(), and OutputGenerator::startTitleHead().
startTypewriter() [1/2]
void OutputList::startTypewriter () [inline], [virtual]
Changes the text font to fixed size. The section ends with endTypewriter()
Implements BaseOutputDocInterface.
Definition at line 165 of file outputlist.h.
    { forall(&OutputGenerator::startTypewriter); }
References forall(), and BaseOutputDocInterface::startTypewriter().
Referenced by MemberDefImpl::_writeGroupInclude(), NamespaceDefImpl::writeBriefDescription(), writeClassTreeForList(), writeClassTreeToOutput(), MemberDefImpl::writeDeclaration(), writeDefArgumentList(), writeDirTreeNode(), writeGroupTreeNode(), FileDefImpl::writeIncludeFiles(), ClassDefImpl::writeIncludeFiles(), ConceptDefImpl::writeIncludeFiles(), ClassDefImpl::writeIncludeFilesForSlice(), and writeInheritanceSpecifier().
startTypewriter() [2/2]
void OutputList::startTypewriter () [inline], [virtual]
Changes the text font to fixed size. The section ends with endTypewriter()
Implements BaseOutputDocInterface.
Definition at line 165 of file outputlist.h.
    { forall(&OutputGenerator::startTypewriter); }
References forall(), and BaseOutputDocInterface::startTypewriter().
writeAnchor() [1/2]
void OutputList::writeAnchor (const QCString & fileName, const QCString & name) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 239 of file outputlist.h.
    { forall(&OutputGenerator::writeAnchor,fileName,name); }
References forall(), setup::name, and BaseOutputDocInterface::writeAnchor().
Referenced by ClassDefImpl::writeDetailedDescription(), DirDefImpl::writeDetailedDescription(), FileDefImpl::writeDetailedDescription(), GroupDefImpl::writeDetailedDescription(), NamespaceDefImpl::writeDetailedDescription(), ConceptDefImpl::writeDetailedDescription(), writeIndex(), and ClassDefImpl::writeInlineDocumentation().
writeAnchor() [2/2]
void OutputList::writeAnchor (const QCString & fileName, const QCString & name) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 239 of file outputlist.h.
    { forall(&OutputGenerator::writeAnchor,fileName,name); }
References forall(), setup::name, and BaseOutputDocInterface::writeAnchor().
writeChar() [1/2]
void OutputList::writeChar (char c) [inline], [virtual]
Writes a single ASCII character to the output. Converts characters that have a special meaning.
Implements BaseOutputDocInterface.
Definition at line 256 of file outputlist.h.
    { forall(&OutputGenerator::writeChar,c); }
References c, forall(), and BaseOutputDocInterface::writeChar().
Referenced by MemberDefImpl::writeEnumDeclaration(), and VhdlDocGen::writeProcedureProto().
writeChar() [2/2]
void OutputList::writeChar (char c) [inline], [virtual]
Writes a single ASCII character to the output. Converts characters that have a special meaning.
Implements BaseOutputDocInterface.
Definition at line 256 of file outputlist.h.
    { forall(&OutputGenerator::writeChar,c); }
References c, forall(), and BaseOutputDocInterface::writeChar().
writeCodeAnchor() [1/2]
void OutputList::writeCodeAnchor (const QCString & name) [inline], [virtual]
Write an anchor to a source listing.
Parameters
name The name of the anchor.
Implements CodeOutputInterface.
Definition at line 486 of file outputlist.h.
    { forall(&OutputGenerator::writeCodeAnchor,name); }
References forall(), setup::name, and CodeOutputInterface::writeCodeAnchor().
writeCodeAnchor() [2/2]
void OutputList::writeCodeAnchor (const QCString & name) [inline], [virtual]
Write an anchor to a source listing.
Parameters
name The name of the anchor.
Implements CodeOutputInterface.
Definition at line 486 of file outputlist.h.
    { forall(&OutputGenerator::writeCodeAnchor,name); }
References forall(), setup::name, and CodeOutputInterface::writeCodeAnchor().
writeCodeLink() [1/2]
void OutputList::writeCodeLink (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) [inline], [virtual]
Writes a link to an object in a code fragment.
Parameters
type The type of symbol, used for semantic syntax highlighting, may be Default is no info is available.
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
tooltip The tooltip to display when the mouse is on the link.
Implements CodeOutputInterface.
Definition at line 144 of file outputlist.h.
    { forall(&OutputGenerator::writeCodeLink,type,ref,file,anchor,name,tooltip); }
References caseconvert::file, forall(), setup::name, and CodeOutputInterface::writeCodeLink().
writeCodeLink() [2/2]
void OutputList::writeCodeLink (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) [inline], [virtual]
Writes a link to an object in a code fragment.
Parameters
type The type of symbol, used for semantic syntax highlighting, may be Default is no info is available.
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
tooltip The tooltip to display when the mouse is on the link.
Implements CodeOutputInterface.
Definition at line 144 of file outputlist.h.
    { forall(&OutputGenerator::writeCodeLink,type,ref,file,anchor,name,tooltip); }
References caseconvert::file, forall(), setup::name, and CodeOutputInterface::writeCodeLink().
writeDoc() [1/2]
void OutputList::writeDoc (const IDocNodeAST * ast, const Definition * ctx, const MemberDef * md, int id = 0)
Definition at line 172 of file outputlist.cpp.
{
  for (const auto &og : m_outputs)
  {
    //printf("og->printDoc(extension=%s)\n",
    // ctx?qPrint(ctx->getDefFileExtension()):"<null>");
    if (og->isEnabled()) og->writeDoc(ast,ctx,md,m_id);
  }
}
References m_id, and m_outputs.
Referenced by generateDoc(), ConceptDefImpl::writeBriefDescription(), DirDefImpl::writeBriefDescription(), FileDefImpl::writeBriefDescription(), GroupDefImpl::writeBriefDescription(), NamespaceDefImpl::writeBriefDescription(), MemberDefImpl::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), ConceptDefImpl::writeDeclarationLink(), and MemberList::writePlainDeclarations().
writeDoc() [2/2]
void OutputList::writeDoc (const IDocNodeAST * ast, const Definition * ctx, const MemberDef * md, int id = 0)
writeEndAnnoItem() [1/2]
void OutputList::writeEndAnnoItem (const QCString & name) [inline]
Definition at line 163 of file outputlist.h.
    { forall(&OutputGenerator::writeEndAnnoItem,name); }
References forall(), setup::name, and OutputGenerator::writeEndAnnoItem().
writeEndAnnoItem() [2/2]
void OutputList::writeEndAnnoItem (const QCString & name) [inline]
Definition at line 163 of file outputlist.h.
    { forall(&OutputGenerator::writeEndAnnoItem,name); }
References forall(), setup::name, and OutputGenerator::writeEndAnnoItem().
writeFooter() [1/2]
void OutputList::writeFooter (const QCString & navPath) [inline]
Definition at line 95 of file outputlist.h.
    { forall(&OutputGenerator::writeFooter,navPath); }
References forall(), and OutputGenerator::writeFooter().
Referenced by endFile().
writeFooter() [2/2]
void OutputList::writeFooter (const QCString & navPath) [inline]
Definition at line 95 of file outputlist.h.
    { forall(&OutputGenerator::writeFooter,navPath); }
References forall(), and OutputGenerator::writeFooter().
writeGraphicalHierarchy() [1/2]
void OutputList::writeGraphicalHierarchy (DotGfxHierarchyTable & g) [inline]
Definition at line 407 of file outputlist.h.
    { forall(&OutputGenerator::writeGraphicalHierarchy,g); }
References forall(), g, and OutputGenerator::writeGraphicalHierarchy().
Referenced by writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), and writeGraphicalInterfaceHierarchy().
writeGraphicalHierarchy() [2/2]
void OutputList::writeGraphicalHierarchy (DotGfxHierarchyTable & g) [inline]
Definition at line 407 of file outputlist.h.
    { forall(&OutputGenerator::writeGraphicalHierarchy,g); }
References forall(), g, and OutputGenerator::writeGraphicalHierarchy().
writeInheritedSectionTitle() [1/2]
void OutputList::writeInheritedSectionTitle (const QCString & id, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & title, const QCString & name) [inline]
Definition at line 314 of file outputlist.h.
    { forall(&OutputGenerator::writeInheritedSectionTitle,id,ref,
                                    file,anchor,title,name); }
References caseconvert::file, forall(), setup::name, and OutputGenerator::writeInheritedSectionTitle().
Referenced by MemberList::writeDeclarations().
writeInheritedSectionTitle() [2/2]
void OutputList::writeInheritedSectionTitle (const QCString & id, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & title, const QCString & name) [inline]
Definition at line 314 of file outputlist.h.
    { forall(&OutputGenerator::writeInheritedSectionTitle,id,ref,
                                    file,anchor,title,name); }
References caseconvert::file, forall(), setup::name, and OutputGenerator::writeInheritedSectionTitle().
writeLabel() [1/2]
void OutputList::writeLabel (const QCString & l, bool isLast) [inline]
Definition at line 474 of file outputlist.h.
    { forall(&OutputGenerator::writeLabel,l,isLast); }
References forall(), and OutputGenerator::writeLabel().
Referenced by ClassDefImpl::addClassAttributes(), NamespaceDefImpl::addNamespaceAttributes(), and MemberDefImpl::writeDocumentation().
writeLabel() [2/2]
void OutputList::writeLabel (const QCString & l, bool isLast) [inline]
Definition at line 474 of file outputlist.h.
    { forall(&OutputGenerator::writeLabel,l,isLast); }
References forall(), and OutputGenerator::writeLabel().
writeLatexSpacing() [1/2]
void OutputList::writeLatexSpacing () [inline]
Definition at line 270 of file outputlist.h.
    { forall(&OutputGenerator::writeLatexSpacing); }
References forall(), and OutputGenerator::writeLatexSpacing().
Referenced by MemberDefImpl::writeDeclaration().
writeLatexSpacing() [2/2]
void OutputList::writeLatexSpacing () [inline]
Definition at line 270 of file outputlist.h.
    { forall(&OutputGenerator::writeLatexSpacing); }
References forall(), and OutputGenerator::writeLatexSpacing().
writeLineNumber() [1/2]
void OutputList::writeLineNumber (const QCString & ref, const QCString & file, const QCString & anchor, int lineNumber, bool writeLineAnchor) [inline], [virtual]
Writes the line number of a source listing
Parameters
ref External reference (when imported from a tag file)
file The file part of the URL pointing to the docs.
anchor The anchor part of the URL pointing to the docs.
lineNumber The line number to write
writeLineAnchor Indicates if an anchor for the line number needs to be written
Implements CodeOutputInterface.
Definition at line 249 of file outputlist.h.
    { forall(&OutputGenerator::writeLineNumber,ref,file,anchor,lineNumber,writeLineAnchor); }
References caseconvert::file, forall(), and CodeOutputInterface::writeLineNumber().
writeLineNumber() [2/2]
void OutputList::writeLineNumber (const QCString & ref, const QCString & file, const QCString & anchor, int lineNumber, bool writeLineAnchor) [inline], [virtual]
Writes the line number of a source listing
Parameters
ref External reference (when imported from a tag file)
file The file part of the URL pointing to the docs.
anchor The anchor part of the URL pointing to the docs.
lineNumber The line number to write
writeLineAnchor Indicates if an anchor for the line number needs to be written
Implements CodeOutputInterface.
Definition at line 249 of file outputlist.h.
    { forall(&OutputGenerator::writeLineNumber,ref,file,anchor,lineNumber,writeLineAnchor); }
References caseconvert::file, forall(), and CodeOutputInterface::writeLineNumber().
writeLogo() [1/2]
void OutputList::writeLogo () [inline]
Definition at line 355 of file outputlist.h.
    { forall(&OutputGenerator::writeLogo); }
References forall(), and OutputGenerator::writeLogo().
writeLogo() [2/2]
void OutputList::writeLogo () [inline]
Definition at line 355 of file outputlist.h.
    { forall(&OutputGenerator::writeLogo); }
References forall(), and OutputGenerator::writeLogo().
writeNavigationPath() [1/2]
void OutputList::writeNavigationPath (const QCString & s) [inline]
Definition at line 353 of file outputlist.h.
    { forall(&OutputGenerator::writeNavigationPath,s); }
References forall(), s, and OutputGenerator::writeNavigationPath().
Referenced by DefinitionImpl::writeNavigationPath().
writeNavigationPath() [2/2]
void OutputList::writeNavigationPath (const QCString & s) [inline]
Definition at line 353 of file outputlist.h.
    { forall(&OutputGenerator::writeNavigationPath,s); }
References forall(), s, and OutputGenerator::writeNavigationPath().
writeNonBreakableSpace() [1/2]
void OutputList::writeNonBreakableSpace (int num) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 369 of file outputlist.h.
    { forall(&OutputGenerator::writeNonBreakableSpace,num); }
References forall(), and BaseOutputDocInterface::writeNonBreakableSpace().
Referenced by MemberDefImpl::writeDeclaration(), and MemberDefImpl::writeDocumentation().
writeNonBreakableSpace() [2/2]
void OutputList::writeNonBreakableSpace (int num) [inline], [virtual]
Implements BaseOutputDocInterface.
Definition at line 369 of file outputlist.h.
    { forall(&OutputGenerator::writeNonBreakableSpace,num); }
References forall(), and BaseOutputDocInterface::writeNonBreakableSpace().
writeObjectLink() [1/2]
void OutputList::writeObjectLink (const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name) [inline], [virtual]
Writes a link to an object in the documentation.
Parameters
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
Implements BaseOutputDocInterface.
Definition at line 141 of file outputlist.h.
    { forall(&OutputGenerator::writeObjectLink,ref,file,anchor,name); }
References caseconvert::file, forall(), setup::name, and BaseOutputDocInterface::writeObjectLink().
Referenced by MemberDefImpl::_writeCategoryRelation(), MemberDefImpl::_writeGroupInclude(), MemberDefImpl::_writeReimplementedBy(), MemberDefImpl::_writeReimplements(), DefinitionImpl::_writeSourceRefList(), generateFileRef(), generateLink(), recursivelyAddGroupListToTitle(), ClassDefImpl::showUsedFiles(), writeAlphabeticalClassList(), writeAnnotatedClassList(), writeClassLinkForMember(), writeConceptIndex(), ClassDefImpl::writeDeclaration(), NamespaceLinkedRefMap::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), ConceptDefImpl::writeDeclarationLink(), FileDefImpl::writeDetailedDescription(), GroupDefImpl::writeDirs(), writeExampleIndex(), writeExamples(), writeFileLinkForMember(), DirDefImpl::writeFileList(), GroupDefImpl::writeFiles(), FileDefImpl::writeIncludeFiles(), ClassDefImpl::writeIncludeFiles(), ConceptDefImpl::writeIncludeFiles(), ClassDefImpl::writeIncludeFilesForSlice(), ClassDefImpl::writeInheritanceGraph(), writeLink(), MemberDefImpl::writeLink(), MemberDefImpl::writeMemberDocSimple(), ClassDefImpl::writeMemberList(), writeNamespaceIndex(), writeNamespaceLinkForMember(), GroupDefImpl::writeNestedGroups(), writePartialDirPath(), writePartialFilePath(), writeSingleFileIndex(), DefinitionImpl::writeSourceDef(), DirDefImpl::writeSubDirList(), VhdlDocGen::writeVHDLDeclaration(), and VhdlDocGen::writeVhdlLink().
writeObjectLink() [2/2]
void OutputList::writeObjectLink (const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name) [inline], [virtual]
Writes a link to an object in the documentation.
Parameters
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
Implements BaseOutputDocInterface.
Definition at line 141 of file outputlist.h.
    { forall(&OutputGenerator::writeObjectLink,ref,file,anchor,name); }
References caseconvert::file, forall(), setup::name, and BaseOutputDocInterface::writeObjectLink().
writePageLink() [1/2]
void OutputList::writePageLink (const QCString & name, bool first) [inline]
Definition at line 80 of file outputlist.h.
    { forall(&OutputGenerator::writePageLink,name,first); }
References forall(), setup::name, and OutputGenerator::writePageLink().
Referenced by writeIndex().
writePageLink() [2/2]
void OutputList::writePageLink (const QCString & name, bool first) [inline]
Definition at line 80 of file outputlist.h.
    { forall(&OutputGenerator::writePageLink,name,first); }
References forall(), setup::name, and OutputGenerator::writePageLink().
writeQuickLinks() [1/2]
void OutputList::writeQuickLinks (bool compact, HighlightedItem hli, const QCString & file) [inline]
Definition at line 357 of file outputlist.h.
    { forall(&OutputGenerator::writeQuickLinks,compact,hli,file); }
References caseconvert::file, forall(), and OutputGenerator::writeQuickLinks().
Referenced by startFile(), writeClassMemberIndexFiltered(), writeFileMemberIndexFiltered(), writeIndex(), and writeNamespaceMemberIndexFiltered().
writeQuickLinks() [2/2]
void OutputList::writeQuickLinks (bool compact, HighlightedItem hli, const QCString & file) [inline]
Definition at line 357 of file outputlist.h.
    { forall(&OutputGenerator::writeQuickLinks,compact,hli,file); }
References caseconvert::file, forall(), and OutputGenerator::writeQuickLinks().
writeRuler() [1/2]
void OutputList::writeRuler () [inline], [virtual]
Writes a horizontal ruler to the output
Implements BaseOutputDocInterface.
Definition at line 237 of file outputlist.h.
    { forall(&OutputGenerator::writeRuler); }
References forall(), and BaseOutputDocInterface::writeRuler().
Referenced by ClassDefImpl::showUsedFiles(), ClassDefImpl::writeDetailedDescription(), DirDefImpl::writeDetailedDescription(), FileDefImpl::writeDetailedDescription(), GroupDefImpl::writeDetailedDescription(), NamespaceDefImpl::writeDetailedDescription(), ConceptDefImpl::writeDetailedDescription(), ClassLinkedRefMap::writeDocumentation(), and MemberList::writeDocumentation().
writeRuler() [2/2]
void OutputList::writeRuler () [inline], [virtual]
Writes a horizontal ruler to the output
Implements BaseOutputDocInterface.
Definition at line 237 of file outputlist.h.
    { forall(&OutputGenerator::writeRuler); }
References forall(), and BaseOutputDocInterface::writeRuler().
writeSearchInfo() [1/2]
void OutputList::writeSearchInfo () [inline]
Definition at line 93 of file outputlist.h.
    { forall(&OutputGenerator::writeSearchInfo); }
References forall(), and OutputGenerator::writeSearchInfo().
Referenced by startFile(), writeClassMemberIndexFiltered(), writeFileMemberIndexFiltered(), writeIndex(), and writeNamespaceMemberIndexFiltered().
writeSearchInfo() [2/2]
void OutputList::writeSearchInfo () [inline]
Definition at line 93 of file outputlist.h.
    { forall(&OutputGenerator::writeSearchInfo); }
References forall(), and OutputGenerator::writeSearchInfo().
writeSplitBar() [1/2]
void OutputList::writeSplitBar (const QCString & name) [inline]
Definition at line 351 of file outputlist.h.
    { forall(&OutputGenerator::writeSplitBar,name); }
References forall(), setup::name, and OutputGenerator::writeSplitBar().
Referenced by startFile(), writeClassMemberIndexFiltered(), writeFileMemberIndexFiltered(), writeIndex(), and writeNamespaceMemberIndexFiltered().
writeSplitBar() [2/2]
void OutputList::writeSplitBar (const QCString & name) [inline]
Definition at line 351 of file outputlist.h.
    { forall(&OutputGenerator::writeSplitBar,name); }
References forall(), setup::name, and OutputGenerator::writeSplitBar().
writeStartAnnoItem() [1/2]
void OutputList::writeStartAnnoItem (const QCString & type, const QCString & file, const QCString & path, const QCString & name) [inline]
Definition at line 160 of file outputlist.h.
    { forall(&OutputGenerator::writeStartAnnoItem,type,file,path,name); }
References caseconvert::file, forall(), setup::name, and OutputGenerator::writeStartAnnoItem().
writeStartAnnoItem() [2/2]
void OutputList::writeStartAnnoItem (const QCString & type, const QCString & file, const QCString & path, const QCString & name) [inline]
Definition at line 160 of file outputlist.h.
    { forall(&OutputGenerator::writeStartAnnoItem,type,file,path,name); }
References caseconvert::file, forall(), setup::name, and OutputGenerator::writeStartAnnoItem().
writeString() [1/2]
void OutputList::writeString (const QCString & text) [inline], [virtual]
Writes an ASCII string to the output, without converting special characters.
Implements BaseOutputDocInterface.
Definition at line 111 of file outputlist.h.
    { forall(&OutputGenerator::writeString,text); }
References forall(), and BaseOutputDocInterface::writeString().
Referenced by MemberDefImpl::_writeEnumValues(), DefinitionImpl::_writeSourceRefList(), endFile(), endFileWithNavPath(), endQuickIndexItem(), endQuickIndexList(), recursivelyAddGroupListToTitle(), startQuickIndexItem(), startQuickIndexList(), writeAlphabeticalClassList(), writeAnnotatedClassList(), writeAnnotatedIndexGeneric(), ClassDefImpl::writeAuthorSection(), ConceptDefImpl::writeBriefDescription(), DirDefImpl::writeBriefDescription(), FileDefImpl::writeBriefDescription(), GroupDefImpl::writeBriefDescription(), NamespaceDefImpl::writeBriefDescription(), ClassDefImpl::writeBriefDescription(), writeClassLinkForMember(), writeClassMemberIndexFiltered(), VhdlDocGen::writeClassType(), writeConceptIndex(), MemberDefImpl::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), ConceptDefImpl::writeDeclarationLink(), DirDefImpl::writeDetailedDescription(), FileDefImpl::writeDetailedDescription(), GroupDefImpl::writeDetailedDescription(), NamespaceDefImpl::writeDetailedDescription(), ConceptDefImpl::writeDetailedDescription(), ClassDefImpl::writeDetailedDocumentationBody(), MemberDefImpl::writeDocumentation(), DirRelation::writeDocumentation(), GroupDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), MemberList::writeDocumentationPage(), MemberDefImpl::writeEnumDeclaration(), writeExamples(), writeFileIndex(), writeFileLinkForMember(), writeFileMemberIndexFiltered(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), ClassDefImpl::writeInlineDocumentation(), MemberDefImpl::writeMemberDocSimple(), ClassDefImpl::writeMemberList(), ClassDefImpl::writeMoreLink(), writeNamespaceIndex(), writeNamespaceLinkForMember(), writeNamespaceMemberIndexFiltered(), PageDefImpl::writePageDocumentation(), writePageIndex(), writePartialDirPath(), writePartialFilePath(), MemberList::writePlainDeclarations(), writeQuickMemberIndex(), FileDefImpl::writeQuickMemberLinks(), GroupDefImpl::writeQuickMemberLinks(), NamespaceDefImpl::writeQuickMemberLinks(), ClassDefImpl::writeQuickMemberLinks(), ClassDefImpl::writeSummaryLinks(), FileDefImpl::writeSummaryLinks(), GroupDefImpl::writeSummaryLinks(), NamespaceDefImpl::writeSummaryLinks(), DefinitionImpl::writeToc(), writeUCFLink(), and writeUserGroupStubPage().
writeString() [2/2]
void OutputList::writeString (const QCString & text) [inline], [virtual]
Writes an ASCII string to the output, without converting special characters.
Implements BaseOutputDocInterface.
Definition at line 111 of file outputlist.h.
    { forall(&OutputGenerator::writeString,text); }
References forall(), and BaseOutputDocInterface::writeString().
writeStyleInfo() [1/2]
void OutputList::writeStyleInfo (int part) [inline]
Definition at line 86 of file outputlist.h.
    { forall(&OutputGenerator::writeStyleInfo,part); }
References forall(), and OutputGenerator::writeStyleInfo().
Referenced by generateOutput().
writeStyleInfo() [2/2]
void OutputList::writeStyleInfo (int part) [inline]
Definition at line 86 of file outputlist.h.
    { forall(&OutputGenerator::writeStyleInfo,part); }
References forall(), and OutputGenerator::writeStyleInfo().
writeSummaryLink() [1/2]
void OutputList::writeSummaryLink (const QCString & file, const QCString & anchor, const QCString & title, bool first) [inline]
Definition at line 359 of file outputlist.h.
    { forall(&OutputGenerator::writeSummaryLink,file,anchor,title,first); }
References caseconvert::file, forall(), and OutputGenerator::writeSummaryLink().
Referenced by ClassDefImpl::writeSummaryLinks(), FileDefImpl::writeSummaryLinks(), GroupDefImpl::writeSummaryLinks(), and NamespaceDefImpl::writeSummaryLinks().
writeSummaryLink() [2/2]
void OutputList::writeSummaryLink (const QCString & file, const QCString & anchor, const QCString & title, bool first) [inline]
Definition at line 359 of file outputlist.h.
    { forall(&OutputGenerator::writeSummaryLink,file,anchor,title,first); }
References caseconvert::file, forall(), and OutputGenerator::writeSummaryLink().
writeSynopsis() [1/2]
void OutputList::writeSynopsis () [inline]
Definition at line 337 of file outputlist.h.
    { forall(&OutputGenerator::writeSynopsis); }
References forall(), and OutputGenerator::writeSynopsis().
Referenced by ConceptDefImpl::writeBriefDescription(), DirDefImpl::writeBriefDescription(), FileDefImpl::writeBriefDescription(), GroupDefImpl::writeBriefDescription(), NamespaceDefImpl::writeBriefDescription(), and ClassDefImpl::writeBriefDescription().
writeSynopsis() [2/2]
void OutputList::writeSynopsis () [inline]
Definition at line 337 of file outputlist.h.
    { forall(&OutputGenerator::writeSynopsis); }
References forall(), and OutputGenerator::writeSynopsis().
writeTooltip() [1/2]
void OutputList::writeTooltip (const QCString & id, const DocLinkInfo & docInfo, const QCString & decl, const QCString & desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) [inline], [virtual]
Writes a tool tip definition
Parameters
id unique identifier for the tooltip
docInfo Info about the symbol's documentation.
decl full declaration of the symbol (for functions)
desc brief description for the symbol
defInfo Info about the symbol's definition in the source code
declInfo Info about the symbol's declaration in the source code
Implements CodeOutputInterface.
Definition at line 149 of file outputlist.h.
    { forall(&OutputGenerator::writeTooltip,id,docInfo,decl,desc,defInfo,declInfo); }
References forall(), and CodeOutputInterface::writeTooltip().
writeTooltip() [2/2]
void OutputList::writeTooltip (const QCString & id, const DocLinkInfo & docInfo, const QCString & decl, const QCString & desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) [inline], [virtual]
Writes a tool tip definition
Parameters
id unique identifier for the tooltip
docInfo Info about the symbol's documentation.
decl full declaration of the symbol (for functions)
desc brief description for the symbol
defInfo Info about the symbol's definition in the source code
declInfo Info about the symbol's declaration in the source code
Implements CodeOutputInterface.
Definition at line 149 of file outputlist.h.
    { forall(&OutputGenerator::writeTooltip,id,docInfo,decl,desc,defInfo,declInfo); }
References forall(), and CodeOutputInterface::writeTooltip().
Member Data Documentation
m_id
int OutputList::m_id [private]
Definition at line 526 of file outputlist.h.
Referenced by generateDoc(), id(), newId(), operator=(), OutputList(), parseText(), startFile(), and writeDoc().
m_outputs
std::vector< std::unique_ptr< OutputGenerator > > OutputList::m_outputs [private]
Definition at line 525 of file outputlist.h.
Referenced by add(), disable(), disableAll(), disableAllBut(), enable(), enableAll(), forall(), generateDoc(), isEnabled(), operator=(), OutputList(), parseText(), popGeneratorState(), pushGeneratorState(), size(), and writeDoc().
m_searchData
SIDataCollection OutputList::m_searchData [private]
Definition at line 527 of file outputlist.h.
Referenced by addWord(), indexSearchData(), and setCurrentDoc().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/outputlist.h
doxygen/src/outputlist.h
doxygen/build/doxygen/src/outputlist.cpp
doxygen/src/outputlist.cpp