InheritanceGraphContext::Private Class Reference
Public Member Functions
Private (DotGfxHierarchyTablePtr hierarchy, DotNode *n, int id)
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private (DotGfxHierarchyTablePtr hierarchy, DotNode *n, int id)
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private Member Functions
TemplateVariant graph () const
TemplateVariant createGraph () const
TemplateVariant graph () const
TemplateVariant createGraph () const
Private Attributes
DotGfxHierarchyTablePtr m_hierarchy
DotNode * m_node
CachedItem< TemplateVariant, Private,&Private::createGraph > m_graph
int m_id
Static Private Attributes
static const PropertyMap< InheritanceGraphContext::Private > s_inst
Detailed Description
Definition at line 7399 of file context.cpp.
Constructor & Destructor Documentation
Private() [1/2]
InheritanceGraphContext::Private::Private (DotGfxHierarchyTablePtr hierarchy, DotNode * n, int id) [inline]
Definition at line 7402 of file context.cpp.
      : m_hierarchy(hierarchy), m_node(n), m_id(id) { }
Private() [2/2]
InheritanceGraphContext::Private::Private (DotGfxHierarchyTablePtr hierarchy, DotNode * n, int id) [inline]
Definition at line 7402 of file context.cpp.
      : m_hierarchy(hierarchy), m_node(n), m_id(id) { }
Member Function Documentation
createGraph() [1/2]
TemplateVariant InheritanceGraphContext::Private::createGraph () const [inline], [private]
Definition at line 7414 of file context.cpp.
    {
      TextStream t;
      bool haveDot = Config_getBool(HAVE_DOT);
      bool graphicalHierarchy = Config_getBool(GRAPHICAL_HIERARCHY);
      if (haveDot && graphicalHierarchy)
      {
        m_hierarchy->createGraph(m_node,t,
                          /*GOF_BITMAP,
                          EOF_Html,*/
                          g_globals.outputDir,
                          g_globals.outputDir+Portable::pathSeparator()+"inherits"+Doxygen::htmlFileExtension,
                          m_id);
      }
      return TemplateVariant(t.str().c_str(),TRUE);
    }
References Config_getBool, g_globals, Doxygen::htmlFileExtension, m_hierarchy, m_id, m_node, ContextGlobals::outputDir, Portable::pathSeparator(), TextStream::str(), and TRUE.
createGraph() [2/2]
TemplateVariant InheritanceGraphContext::Private::createGraph () const [inline], [private]
Definition at line 7414 of file context.cpp.
    {
      TextStream t;
      bool haveDot = Config_getBool(HAVE_DOT);
      bool graphicalHierarchy = Config_getBool(GRAPHICAL_HIERARCHY);
      if (haveDot && graphicalHierarchy)
      {
        m_hierarchy->createGraph(m_node,t,
                          /*GOF_BITMAP,
                          EOF_Html,*/
                          g_globals.outputDir,
                          g_globals.outputDir+Portable::pathSeparator()+"inherits"+Doxygen::htmlFileExtension,
                          m_id);
      }
      return TemplateVariant(t.str().c_str(),TRUE);
    }
References Config_getBool, g_globals, Doxygen::htmlFileExtension, ContextGlobals::outputDir, Portable::pathSeparator(), TextStream::str(), and TRUE.
fields() [1/2]
StringVector InheritanceGraphContext::Private::fields () const [inline]
Definition at line 7407 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
fields() [2/2]
StringVector InheritanceGraphContext::Private::fields () const [inline]
Definition at line 7407 of file context.cpp.
{ return s_inst.fields(); }
get() [1/2]
TemplateVariant InheritanceGraphContext::Private::get (const QCString & n) const [inline]
Definition at line 7406 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), n, and s_inst.
get() [2/2]
TemplateVariant InheritanceGraphContext::Private::get (const QCString & n) const [inline]
Definition at line 7406 of file context.cpp.
{ return s_inst.get(this,n); }
References n.
graph() [1/2]
TemplateVariant InheritanceGraphContext::Private::graph () const [inline], [private]
Definition at line 7411 of file context.cpp.
{ return m_graph.get(this); }
References m_graph.
graph() [2/2]
TemplateVariant InheritanceGraphContext::Private::graph () const [inline], [private]
Definition at line 7411 of file context.cpp.
{ return m_graph.get(this); }
Member Data Documentation
m_graph
CachedItem< TemplateVariant, Private,&Private::createGraph > InheritanceGraphContext::Private::m_graph [private]
Definition at line 7432 of file context.cpp.
Referenced by graph().
m_hierarchy
DotGfxHierarchyTablePtr InheritanceGraphContext::Private::m_hierarchy [private]
Definition at line 7430 of file context.cpp.
Referenced by createGraph().
m_id
int InheritanceGraphContext::Private::m_id [private]
Definition at line 7433 of file context.cpp.
Referenced by createGraph().
m_node
DotNode * InheritanceGraphContext::Private::m_node [private]
Definition at line 7431 of file context.cpp.
Referenced by createGraph().
s_inst
const PropertyMap< InheritanceGraphContext::Private > InheritanceGraphContext::Private::s_inst [static], [private]
Initial value:
{
  { "graph",&Private::graph }
}
Definition at line 7434 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp