SymbolResolver Class Reference
#include <symbolresolver.h>
Classes
struct Private
Public Member Functions
SymbolResolver (const FileDef *fileScope=0)
~SymbolResolver ()
const ClassDef * resolveClass (const Definition *scope, const QCString &name, bool maybeUnlinkable=false, bool mayBeHidden=false)
ClassDefMutable * resolveClassMutable (const Definition *scope, const QCString &name, bool mayBeUnlinkable=false, bool mayBeHidden=false)
const Definition * resolveSymbol (const Definition *scope, const QCString &name, const QCString &args=QCString(), bool checkCV=false)
int isAccessibleFrom (const Definition *scope, const Definition *item)
int isAccessibleFromWithExpScope (const Definition *scope, const Definition *item, const QCString &explicitScopePart)
void setFileScope (const FileDef *fd)
const MemberDef * getTypedef () const
QCString getTemplateSpec () const
QCString getResolvedType () const
SymbolResolver (const FileDef *fileScope=0)
~SymbolResolver ()
const ClassDef * resolveClass (const Definition *scope, const QCString &name, bool maybeUnlinkable=false, bool mayBeHidden=false)
ClassDefMutable * resolveClassMutable (const Definition *scope, const QCString &name, bool mayBeUnlinkable=false, bool mayBeHidden=false)
const Definition * resolveSymbol (const Definition *scope, const QCString &name, const QCString &args=QCString(), bool checkCV=false)
int isAccessibleFrom (const Definition *scope, const Definition *item)
int isAccessibleFromWithExpScope (const Definition *scope, const Definition *item, const QCString &explicitScopePart)
void setFileScope (const FileDef *fd)
const MemberDef * getTypedef () const
QCString getTemplateSpec () const
QCString getResolvedType () const
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Helper class to find a class definition or check if A symbol is accessible in a given scope.
Definition at line 30 of file symbolresolver.h.
Constructor & Destructor Documentation
SymbolResolver() [1/2]
SymbolResolver::SymbolResolver (const FileDef * fileScope = 0) [explicit]
Definition at line 1464 of file symbolresolver.cpp.
  : p(std::make_unique<Private>(fileScope))
{
}
 SymbolResolver() [1/2]
SymbolResolver::~SymbolResolver ()
Definition at line 1469 of file symbolresolver.cpp.
{
}
SymbolResolver() [2/2]
SymbolResolver::SymbolResolver (const FileDef * fileScope = 0) [explicit]
 SymbolResolver() [2/2]
SymbolResolver::~SymbolResolver ()
Member Function Documentation
getResolvedType() [1/2]
QCString SymbolResolver::getResolvedType () const
In case a call to resolveClass() points to a typedef or using declaration. The type name it resolved to is returned via this method.
Definition at line 1567 of file symbolresolver.cpp.
{
  return p->resolvedType;
}
References p.
Referenced by getCanonicalTypeForIdentifier().
getResolvedType() [2/2]
QCString SymbolResolver::getResolvedType () const
In case a call to resolveClass() points to a typedef or using declaration. The type name it resolved to is returned via this method.
getTemplateSpec() [1/2]
QCString SymbolResolver::getTemplateSpec () const
In case a call to resolveClass() points to a template specialization, the template part is return via this method.
Definition at line 1562 of file symbolresolver.cpp.
{
  return p->templateSpec;
}
References p.
Referenced by findClassRelation(), and getCanonicalTypeForIdentifier().
getTemplateSpec() [2/2]
QCString SymbolResolver::getTemplateSpec () const
In case a call to resolveClass() points to a template specialization, the template part is return via this method.
getTypedef() [1/2]
const MemberDef * SymbolResolver::getTypedef () const
In case a call to resolveClass() resolves to a type member (e.g. an enum) this method will return it.
Definition at line 1557 of file symbolresolver.cpp.
{
  return p->typeDef;
}
References p.
Referenced by findClassRelation(), getCanonicalTypeForIdentifier(), getDefsOld(), and if().
getTypedef() [2/2]
const MemberDef * SymbolResolver::getTypedef () const
In case a call to resolveClass() resolves to a type member (e.g. an enum) this method will return it.
isAccessibleFrom() [1/2]
int SymbolResolver::isAccessibleFrom (const Definition * scope, const Definition * item)
Checks if symbol item is accessible from within scope.
Returns
-1 if item is not accessible or a number indicating how many scope levels up the nearest match was found.
Definition at line 1536 of file symbolresolver.cpp.
{
  p->reset();
  AccessStack accessStack;
  return p->isAccessibleFrom(accessStack,scope,item);
}
References p.
Referenced by SymbolResolver::Private::isAccessibleFrom(), SymbolResolver::Private::isAccessibleFromWithExpScope(), and resolveTypeDef().
isAccessibleFrom() [2/2]
int SymbolResolver::isAccessibleFrom (const Definition * scope, const Definition * item)
Checks if symbol item is accessible from within scope.
Returns
-1 if item is not accessible or a number indicating how many scope levels up the nearest match was found.
isAccessibleFromWithExpScope() [1/2]
int SymbolResolver::isAccessibleFromWithExpScope (const Definition * scope, const Definition * item, const QCString & explicitScopePart)
Check if symbol item is accessible from within scope, where it has to match the explicitScopePart.
Returns
-1 if item is not accessible or a number indicating how many scope levels up the nearest match was found.
Definition at line 1543 of file symbolresolver.cpp.
{
  p->reset();
  VisitedNamespaces visitedNamespaces;
  AccessStack accessStack;
  return p->isAccessibleFromWithExpScope(visitedNamespaces,accessStack,scope,item,explicitScopePart);
}
References p.
Referenced by getMemberFromSymbol(), SymbolResolver::Private::getResolvedSymbol(), SymbolResolver::Private::getResolvedType(), SymbolResolver::Private::isAccessibleFromWithExpScope(), and SymbolResolver::Private::substTypedef().
isAccessibleFromWithExpScope() [2/2]
int SymbolResolver::isAccessibleFromWithExpScope (const Definition * scope, const Definition * item, const QCString & explicitScopePart)
Check if symbol item is accessible from within scope, where it has to match the explicitScopePart.
Returns
-1 if item is not accessible or a number indicating how many scope levels up the nearest match was found.
resolveClass() [1/2]
const ClassDef * SymbolResolver::resolveClass (const Definition * scope, const QCString & name, bool maybeUnlinkable = false, bool mayBeHidden = false)
Find the class definition matching name within the scope set.
Parameters
scope The scope to search from.
name The name of the symbol.
maybeUnlinkable include unlinkable symbols in the search.
mayBeHidden include hidden symbols in the search.
Note
As a result of this call the getters getTypedef(), getTemplateSpec(), and getResolvedType() are set as well.
Definition at line 1474 of file symbolresolver.cpp.
{
  p->reset();
  if (scope==0 ||
      (scope->definitionType()!=Definition::TypeClass &&
       scope->definitionType()!=Definition::TypeNamespace
      ) ||
      (name.stripWhiteSpace().startsWith("::")) ||
      (scope->getLanguage()==SrcLangExt_Java && QCString(name).find("::")!=-1)
     )
  {
    scope=Doxygen::globalScope;
  }
  //fprintf(stderr,"------------ resolveClass(scope=%s,name=%s,mayUnlinkable=%d)\n",
  // scope?qPrint(scope->name()):"<global>",
  // qPrint(name),
  // mayBeUnlinkable
  //);
  const ClassDef *result=0;
  if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
  {
    result = getClass(name);
  }
  else
  {
    result = p->getResolvedTypeRec(scope,name,&p->typeDef,&p->templateSpec,&p->resolvedType);
    if (result==0) // for nested classes imported via tag files, the scope may not
                   // present, so we check the class name directly as well.
                   // See also bug701314
    {
      result = getClass(name);
    }
  }
  if (!mayBeUnlinkable && result && !result->isLinkable())
  {
    if (!mayBeHidden || !result->isHidden())
    {
      //fprintf(stderr,"result was %s\n",result?qPrint(result->name()):"<none>");
      result=0; // don't link to artificial/hidden classes unless explicitly allowed
    }
  }
  //fprintf(stderr,"ResolvedClass(%s,%s)=%s\n",scope?qPrint(scope->name()):"<global>",
  // qPrint(name),result?qPrint(result->name()):"<none>");
  return result;
}
References Config_getBool, Definition::definitionType(), getClass(), Definition::getLanguage(), Doxygen::globalScope, Definition::isHidden(), ClassDef::isLinkable(), setup::name, p, SrcLangExt_Java, Definition::TypeClass, and Definition::TypeNamespace.
Referenced by findClassDefinition(), findClassWithinClassContext(), findUsingDeclImports(), getCanonicalTypeForIdentifier(), getDefsOld(), if(), isVarWithConstructor(), normalizeNonTemplateArgumentsInString(), and resolveClassMutable().
resolveClass() [2/2]
const ClassDef * SymbolResolver::resolveClass (const Definition * scope, const QCString & name, bool maybeUnlinkable = false, bool mayBeHidden = false)
Find the class definition matching name within the scope set.
Parameters
scope The scope to search from.
name The name of the symbol.
maybeUnlinkable include unlinkable symbols in the search.
mayBeHidden include hidden symbols in the search.
Note
As a result of this call the getters getTypedef(), getTemplateSpec(), and getResolvedType() are set as well.
resolveClassMutable() [1/2]
ClassDefMutable * SymbolResolver::resolveClassMutable (const Definition * scope, const QCString & name, bool mayBeUnlinkable = false, bool mayBeHidden = false) [inline]
Wrapper around resolveClass that returns a mutable interface to the class object or a nullptr if the symbol is immutable.
Definition at line 55 of file symbolresolver.h.
    {
      return toClassDefMutable(resolveClass(scope,name,mayBeUnlinkable,mayBeHidden));
    }
References setup::name, resolveClass(), and toClassDefMutable().
Referenced by ClassDefImpl::addTypeConstraint(), findClassRelation(), findUsedClassesForClass(), and findUsingDeclarations().
resolveClassMutable() [2/2]
ClassDefMutable * SymbolResolver::resolveClassMutable (const Definition * scope, const QCString & name, bool mayBeUnlinkable = false, bool mayBeHidden = false) [inline]
Wrapper around resolveClass that returns a mutable interface to the class object or a nullptr if the symbol is immutable.
Definition at line 55 of file symbolresolver.h.
    {
      return toClassDefMutable(resolveClass(scope,name,mayBeUnlinkable,mayBeHidden));
    }
References setup::name, resolveClass(), and toClassDefMutable().
resolveSymbol() [1/2]
const Definition * SymbolResolver::resolveSymbol (const Definition * scope, const QCString & name, const QCString & args = QCString(), bool checkCV = false)
Find the symbool definition matching name within the scope set.
Parameters
scope The scope to search from.
name The name of the symbol.
args Argument list associated with the symbol (for functions)
checkCV Check const/volatile qualifiers (for methods)
Definition at line 1524 of file symbolresolver.cpp.
{
  p->reset();
  if (scope==0) scope=Doxygen::globalScope;
  const Definition *result = p->getResolvedSymbolRec(scope,name,args,checkCV,&p->typeDef,&p->templateSpec,&p->resolvedType);
  //printf("resolveSymbol(%s,%s,%s,%d)=%s\n",qPrint(scope?scope->name():QCString()),qPrint(name),qPrint(args),checkCV,qPrint(result?result->qualifiedName():QCString()));
  return result;
}
References Doxygen::globalScope, setup::name, and p.
Referenced by getDefsNew().
resolveSymbol() [2/2]
const Definition * SymbolResolver::resolveSymbol (const Definition * scope, const QCString & name, const QCString & args = QCString(), bool checkCV = false)
Find the symbool definition matching name within the scope set.
Parameters
scope The scope to search from.
name The name of the symbol.
args Argument list associated with the symbol (for functions)
checkCV Check const/volatile qualifiers (for methods)
setFileScope() [1/2]
void SymbolResolver::setFileScope (const FileDef * fd)
Sets or updates the file scope using when resolving symbols.
Definition at line 1552 of file symbolresolver.cpp.
{
  p->setFileScope(fileScope);
}
References p.
Referenced by getDefsNew().
setFileScope() [2/2]
void SymbolResolver::setFileScope (const FileDef * fd)
Sets or updates the file scope using when resolving symbols.
Member Data Documentation
p
std::unique_ptr< Private > SymbolResolver::p [private]
Definition at line 113 of file symbolresolver.h.
Referenced by getResolvedType(), getTemplateSpec(), getTypedef(), isAccessibleFrom(), isAccessibleFromWithExpScope(), resolveClass(), resolveSymbol(), and setFileScope().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/symbolresolver.h
doxygen/src/symbolresolver.h
doxygen/build/doxygen/src/symbolresolver.cpp
doxygen/src/symbolresolver.cpp