Dir Class Reference
#include <dir.h>
Classes
struct Private
Public Member Functions
Dir ()
Dir (const std::string &path)
Dir (const Dir &d)
Dir & operator= (const Dir &d)
~Dir ()
void setPath (const std::string &path)
std::string path () const
DirIterator iterator () const
bool isEmpty (const std::string subdir) const
bool exists () const
std::string filePath (const std::string &path, bool acceptsAbsPath=true) const
bool exists (const std::string &path, bool acceptsAbsPath=true) const
bool mkdir (const std::string &path, bool acceptsAbsPath=true) const
bool rmdir (const std::string &path, bool acceptsAbsPath=true) const
bool remove (const std::string &path, bool acceptsAbsPath=true) const
bool rename (const std::string &orgName, const std::string &newName, bool acceptsAbsPath=true) const
bool copy (const std::string &src, const std::string &dest, bool acceptsAbsPath=true) const
std::string absPath () const
bool isRelative () const
Dir ()
Dir (const std::string &path)
Dir (const Dir &d)
Dir & operator= (const Dir &d)
~Dir ()
void setPath (const std::string &path)
std::string path () const
DirIterator iterator () const
bool isEmpty (const std::string subdir) const
bool exists () const
std::string filePath (const std::string &path, bool acceptsAbsPath=true) const
bool exists (const std::string &path, bool acceptsAbsPath=true) const
bool mkdir (const std::string &path, bool acceptsAbsPath=true) const
bool rmdir (const std::string &path, bool acceptsAbsPath=true) const
bool remove (const std::string &path, bool acceptsAbsPath=true) const
bool rename (const std::string &orgName, const std::string &newName, bool acceptsAbsPath=true) const
bool copy (const std::string &src, const std::string &dest, bool acceptsAbsPath=true) const
std::string absPath () const
bool isRelative () const
Static Public Member Functions
static bool isRelativePath (const std::string &path)
static std::string currentDirPath ()
static bool setCurrent (const std::string &path)
static std::string cleanDirPath (const std::string &path)
static bool isRelativePath (const std::string &path)
static std::string currentDirPath ()
static bool setCurrent (const std::string &path)
static std::string cleanDirPath (const std::string &path)
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Class representing a directory in the file system
Definition at line 68 of file dir.h.
Constructor & Destructor Documentation
Dir() [1/6]
Dir::Dir ()
Definition at line 143 of file dir.cpp.
         : p(std::make_unique<Private>())
{
  std::error_code ec;
  p->path = fs::current_path(ec);
}
References ghc::filesystem::current_path(), and p.
Dir() [2/6]
Dir::Dir (const std::string & path)
Definition at line 163 of file dir.cpp.
                              : p(std::make_unique<Private>())
{
  setPath(path);
}
References path(), and setPath().
Dir() [3/6]
Dir::Dir (const Dir & d)
Definition at line 149 of file dir.cpp.
                     : p(std::make_unique<Private>())
{
  p->path = d.p->path;
}
References p.
 Dir() [1/2]
Dir::~Dir ()
Definition at line 168 of file dir.cpp.
{
}
Dir() [4/6]
Dir::Dir ()
Dir() [5/6]
Dir::Dir (const std::string & path)
Dir() [6/6]
Dir::Dir (const Dir & d)
 Dir() [2/2]
Dir::~Dir ()
Member Function Documentation
absPath() [1/2]
std::string Dir::absPath () const
Definition at line 306 of file dir.cpp.
{
  std::error_code ec;
  std::string result = fs::absolute(p->path,ec).string();
  correctPath(result);
  return result;
}
References ghc::filesystem::absolute(), correctPath(), p, ghc::filesystem::path::string(), and string.
Referenced by Htags::execute(), PerlModGenerator::generate(), FormulaManager::generateImages(), parseInput(), Htags::path2URL(), RTFGenerator::preProcessFileInplace(), writeDotGraphFromFile(), writeDotImageMapFromFile(), and DotGraph::writeGraph().
absPath() [2/2]
std::string Dir::absPath () const
cleanDirPath() [1/2]
std::string Dir::cleanDirPath (const std::string & path) [static]
Definition at line 298 of file dir.cpp.
{
  std::error_code ec;
  std::string result = fs::path(path).lexically_normal().string();
  correctPath(result);
  return result;
}
References correctPath(), ghc::filesystem::path::lexically_normal(), path(), ghc::filesystem::path::string(), and string.
Referenced by findFileDef(), and resolveSymlink().
cleanDirPath() [2/2]
static std::string Dir::cleanDirPath (const std::string & path) [static]
copy() [1/2]
bool Dir::copy (const std::string & src, const std::string & dest, bool acceptsAbsPath = true) const
Definition at line 273 of file dir.cpp.
{
  const auto copyOptions = fs::copy_options::overwrite_existing;
  std::error_code ec;
  std::string sn = filePath(srcName,acceptsAbsPath);
  std::string dn = filePath(dstName,acceptsAbsPath);
  fs::copy(sn,dn,copyOptions,ec);
  return !ec;
}
References ghc::filesystem::copy(), filePath(), and string.
copy() [2/2]
bool Dir::copy (const std::string & src, const std::string & dest, bool acceptsAbsPath = true) const
currentDirPath() [1/2]
std::string Dir::currentDirPath () [static]
Definition at line 283 of file dir.cpp.
{
  std::error_code ec;
  std::string result = fs::current_path(ec).string();
  correctPath(result);
  return result;
}
References correctPath(), ghc::filesystem::current_path(), ghc::filesystem::path::string(), and string.
Referenced by Config::checkAndCorrect(), Htags::execute(), FormulaManager::generateImages(), generateOutput(), CitationManager::generatePage(), parseInput(), RTFGenerator::preProcessFileInplace(), runHtmlHelpCompiler(), runQHelpGenerator(), setPerlModDoxyfile(), Portable::setShortDir(), and writeDiaGraphFromFile().
currentDirPath() [2/2]
static std::string Dir::currentDirPath () [static]
exists() [1/4]
bool Dir::exists () const
Definition at line 200 of file dir.cpp.
{
  FileInfo fi(p->path.string());
  return fi.exists() && fi.isDir();
}
References FileInfo::exists(), FileInfo::isDir(), and p.
Referenced by clearSubDirs(), PerlModGenerator::createOutputDir(), createOutputDirectory(), createSubDirs(), Htags::execute(), generateDEF(), FormulaManager::generateImages(), generateOutput(), CitationManager::generatePage(), generateTemplateFiles(), DocbookGenerator::init(), HtmlGenerator::init(), LatexGenerator::init(), ManGenerator::init(), RTFGenerator::init(), mkdir(), TemplateNodeCreator< T >::mkpath(), parseInput(), DotGraph::prepareDotFile(), RTFGenerator::preProcessFileInplace(), writeDotGraphFromFile(), writeDotImageMapFromFile(), and DotGfxHierarchyTable::writeGraph().
exists() [2/4]
bool Dir::exists () const
exists() [3/4]
bool Dir::exists (const std::string & path, bool acceptsAbsPath = true) const
Definition at line 192 of file dir.cpp.
{
  std::string result = filePath(path,acceptsAbsPath);
  std::error_code ec;
  bool exist = fs::exists(fs::path(result),ec);
  return !ec && exist;
}
References ghc::filesystem::exists(), filePath(), path(), and string.
exists() [4/4]
bool Dir::exists (const std::string & path, bool acceptsAbsPath = true) const
filePath() [1/2]
std::string Dir::filePath (const std::string & path, bool acceptsAbsPath = true) const
Definition at line 223 of file dir.cpp.
{
  std::string result;
  if (acceptsAbsPath && !isRelativePath(path))
  {
    result = path;
  }
  else
  {
    result = (p->path / path).string();
  }
  correctPath(result);
  return result;
}
References correctPath(), isRelativePath(), p, path(), and string.
Referenced by copy(), exists(), mkdir(), remove(), and rename().
filePath() [2/2]
std::string Dir::filePath (const std::string & path, bool acceptsAbsPath = true) const
isEmpty() [1/2]
bool Dir::isEmpty (const std::string subdir) const
Definition at line 206 of file dir.cpp.
{
  fs::path pth = path();
  pth /= subdir;
  return fs::is_empty(pth);
}
References ghc::filesystem::is_empty(), and path().
Referenced by clearSubDirs().
isEmpty() [2/2]
bool Dir::isEmpty (const std::string subdir) const
isRelative() [1/2]
bool Dir::isRelative () const
Definition at line 213 of file dir.cpp.
{
  return isRelativePath(p->path.string());
}
References isRelativePath(), and p.
isRelative() [2/2]
bool Dir::isRelative () const
isRelativePath() [1/2]
bool Dir::isRelativePath (const std::string & path) [static]
Definition at line 218 of file dir.cpp.
{
  return fs::path(path).is_relative();
}
References ghc::filesystem::path::is_relative(), and path().
Referenced by filePath(), and isRelative().
isRelativePath() [2/2]
static bool Dir::isRelativePath (const std::string & path) [static]
iterator() [1/2]
DirIterator Dir::iterator () const
Definition at line 182 of file dir.cpp.
{
  return DirIterator(p->path.string());
}
References p.
Referenced by readDir().
iterator() [2/2]
DirIterator Dir::iterator () const
mkdir() [1/2]
bool Dir::mkdir (const std::string & path, bool acceptsAbsPath = true) const
Definition at line 238 of file dir.cpp.
{
  std::error_code ec;
  std::string result = filePath(path,acceptsAbsPath);
  if (exists(path,acceptsAbsPath))
  {
    return true;
  }
  else
  {
    return fs::create_directory(result,ec);
  }
}
References ghc::filesystem::create_directory(), exists(), filePath(), path(), and string.
Referenced by PerlModGenerator::createOutputDir(), createOutputDirectory(), createSubDirs(), generateDEF(), generateOutput(), CitationManager::generatePage(), generateTemplateFiles(), DocbookGenerator::init(), HtmlGenerator::init(), LatexGenerator::init(), ManGenerator::init(), RTFGenerator::init(), TemplateNodeCreator< T >::mkpath(), and parseInput().
mkdir() [2/2]
bool Dir::mkdir (const std::string & path, bool acceptsAbsPath = true) const
operator=() [1/2]
Dir & Dir::operator= (const Dir & d)
Definition at line 154 of file dir.cpp.
{
  if (&d!=this)
  {
    p->path = d.p->path;
  }
  return *this;
}
References p.
operator=() [2/2]
Dir & Dir::operator= (const Dir & d)
path() [1/2]
std::string Dir::path () const
Definition at line 177 of file dir.cpp.
{
  return p->path.string();
}
References p.
Referenced by cleanDirPath(), Dir(), exists(), filePath(), isEmpty(), isRelativePath(), mkdir(), DotGraph::prepareDotFile(), remove(), rmdir(), setCurrent(), and setPath().
path() [2/2]
std::string Dir::path () const
remove() [1/2]
bool Dir::remove (const std::string & path, bool acceptsAbsPath = true) const
Definition at line 257 of file dir.cpp.
{
  std::error_code ec;
  std::string result = filePath(path,acceptsAbsPath);
  return fs::remove(result,ec);
}
References filePath(), path(), ghc::filesystem::remove(), and string.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), determineInkscapeVersion(), exitDoxygen(), doxmlparser.compound.memberdefType::exportAttributes(), DocParser::findAndCopyImage(), FormulaManager::generateImages(), generateOutput(), CitationManager::generatePage(), doxmlparser.compound.memberdefType::get_remove(), getMscImageMapFromFile(), main(), openOutputFile(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), RTFDocVisitor::operator()(), preProcessFile(), RTFGenerator::preProcessFileInplace(), resetPDFSize(), rmdir(), DotFilePatcher::run(), doxmlparser.compound.memberdefType::set_remove(), stopDoxygen(), and writeDotImageMapFromFile().
remove() [2/2]
bool Dir::remove (const std::string & path, bool acceptsAbsPath = true) const
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_remove(), and doxmlparser.compound.memberdefType::set_remove().
rename() [1/2]
bool Dir::rename (const std::string & orgName, const std::string & newName, bool acceptsAbsPath = true) const
Definition at line 264 of file dir.cpp.
{
  std::error_code ec;
  std::string fn1 = filePath(orgName,acceptsAbsPath);
  std::string fn2 = filePath(newName,acceptsAbsPath);
  fs::rename(fn1,fn2,ec);
  return !ec;
}
References filePath(), ghc::filesystem::rename(), and string.
Referenced by openOutputFile(), RTFGenerator::preProcessFileInplace(), resetPDFSize(), and DotFilePatcher::run().
rename() [2/2]
bool Dir::rename (const std::string & orgName, const std::string & newName, bool acceptsAbsPath = true) const
rmdir() [1/2]
bool Dir::rmdir (const std::string & path, bool acceptsAbsPath = true) const
Definition at line 252 of file dir.cpp.
{
  return remove(path,acceptsAbsPath);
}
References path(), and remove().
Referenced by clearSubDirs(), CitationManager::generatePage(), and main().
rmdir() [2/2]
bool Dir::rmdir (const std::string & path, bool acceptsAbsPath = true) const
setCurrent() [1/2]
bool Dir::setCurrent (const std::string & path) [static]
Definition at line 291 of file dir.cpp.
{
  std::error_code ec;
  fs::current_path(path,ec);
  return !ec;
}
References ghc::filesystem::current_path(), and path().
Referenced by Htags::execute(), FormulaManager::generateImages(), CitationManager::generatePage(), RTFGenerator::preProcessFileInplace(), runHtmlHelpCompiler(), runQHelpGenerator(), Portable::setShortDir(), and writeDiaGraphFromFile().
setCurrent() [2/2]
static bool Dir::setCurrent (const std::string & path) [static]
setPath() [1/2]
void Dir::setPath (const std::string & path)
Definition at line 172 of file dir.cpp.
{
  p->path = path;
}
References p, and path().
Referenced by PerlModGenerator::createOutputDir(), Dir(), Htags::execute(), TemplateNodeCreator< T >::mkpath(), and parseInput().
setPath() [2/2]
void Dir::setPath (const std::string & path)
Member Data Documentation
p
std::unique_ptr< Private > Dir::p [private]
Definition at line 102 of file dir.h.
Referenced by absPath(), Dir(), exists(), filePath(), isRelative(), iterator(), operator=(), path(), and setPath().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/dir.h
doxygen/src/dir.h
doxygen/build/doxygen/src/dir.cpp
doxygen/src/dir.cpp