DocGroup Class Reference
#include <docgroup.h>
Public Member Functions
DocGroup ()
void enterFile (const QCString &fileName, int)
void leaveFile (const QCString &fileName, int line)
void enterCompound (const QCString &fileName, int line, const QCString &name)
void leaveCompound (const QCString &, int, const QCString &)
void open (Entry *e, const QCString &, int, bool implicit=false)
void close (Entry *e, const QCString &fileName, int line, bool foundInline, bool implicit=false)
void initGroupInfo (Entry *e)
bool isEmpty () const
void clearHeader ()
void appendHeader (const char)
void addDocs (Entry *e)
DocGroup ()
void enterFile (const QCString &fileName, int)
void leaveFile (const QCString &fileName, int line)
void enterCompound (const QCString &fileName, int line, const QCString &name)
void leaveCompound (const QCString &, int, const QCString &)
void open (Entry *e, const QCString &, int, bool implicit=false)
void close (Entry *e, const QCString &fileName, int line, bool foundInline, bool implicit=false)
void initGroupInfo (Entry *e)
bool isEmpty () const
void clearHeader ()
void appendHeader (const char)
void addDocs (Entry *e)
Private Member Functions
int findExistingGroup (const MemberGroupInfo *info)
int findExistingGroup (const MemberGroupInfo *info)
Private Attributes
int m_openCount = 0
QCString m_memberGroupHeader
int m_memberGroupId = 0
QCString m_memberGroupRelates
QCString m_memberGroupDocs
std::vector< Grouping > m_autoGroupStack
QCString m_compoundName
Detailed Description
Definition at line 24 of file docgroup.h.
Constructor & Destructor Documentation
DocGroup() [1/2]
DocGroup::DocGroup () [inline]
Definition at line 27 of file docgroup.h.
{};
DocGroup() [2/2]
DocGroup::DocGroup () [inline]
Definition at line 27 of file docgroup.h.
{};
Member Function Documentation
addDocs() [1/2]
void DocGroup::addDocs (Entry * e)
Definition at line 193 of file docgroup.cpp.
{
  if (e->section==Entry::MEMBERGRP_SEC)
  {
    m_memberGroupDocs=e->brief.stripWhiteSpace();
    e->doc = stripLeadingAndTrailingEmptyLines(e->doc,e->docLine);
    if (!m_memberGroupDocs.isEmpty() && !e->doc.isEmpty())
    {
      m_memberGroupDocs+="\n\n";
    }
    m_memberGroupDocs+=e->doc;
    auto it =Doxygen::memberGroupInfoMap.find(m_memberGroupId);
    if (it!=Doxygen::memberGroupInfoMap.end())
    {
      auto &info = it->second;
      info->doc = m_memberGroupDocs;
      info->docFile = e->docFile;
      info->docLine = e->docLine;
      info->setRefItems(e->sli);
    }
    e->doc.resize(0);
    e->brief.resize(0);
  }
}
References e, ghc::filesystem::end(), QCString::isEmpty(), m_memberGroupDocs, m_memberGroupId, Doxygen::memberGroupInfoMap, Entry::MEMBERGRP_SEC, and stripLeadingAndTrailingEmptyLines().
addDocs() [2/2]
void DocGroup::addDocs (Entry * e)
appendHeader() [1/2]
void DocGroup::appendHeader (const char text)
Definition at line 228 of file docgroup.cpp.
{
  m_memberGroupHeader += text;
}
References m_memberGroupHeader.
appendHeader() [2/2]
void DocGroup::appendHeader (const char)
clearHeader() [1/2]
void DocGroup::clearHeader ()
Definition at line 223 of file docgroup.cpp.
{
  m_memberGroupHeader.resize(0);
}
References m_memberGroupHeader, and QCString::resize().
clearHeader() [2/2]
void DocGroup::clearHeader ()
close() [1/2]
void DocGroup::close (Entry * e, const QCString & fileName, int line, bool foundInline, bool implicit = false)
Definition at line 136 of file docgroup.cpp.
{
  if (!implicit)
  {
    if (m_openCount < 1)
    {
      warn(fileName,line,"unbalanced grouping commands");
    }
    else
    {
      m_openCount--;
    }
  }
  //printf("==> closeGroup(name=%s,sec=%x,file=%s,line=%d) m_autoGroupStack=%zu\n",
  // qPrint(e->name),e->section,qPrint(fileName),line,m_autoGroupStack.size());
  if (m_memberGroupId!=DOX_NOGROUP) // end of member group
  {
    auto it = Doxygen::memberGroupInfoMap.find(m_memberGroupId);
    if (it!=Doxygen::memberGroupInfoMap.end()) // known group
    {
      auto &info = it->second;
      info->doc = m_memberGroupDocs;
      //info->docFile = fileName;
      //info->docLine = line;
    }
    m_memberGroupId=DOX_NOGROUP;
    m_memberGroupRelates.resize(0);
    m_memberGroupDocs.resize(0);
    if (!foundInline) e->mGrpId=DOX_NOGROUP;
    //printf("new group id=%d\n",m_memberGroupId);
  }
  else if (!m_autoGroupStack.empty()) // end of auto group
  {
    Grouping grp = m_autoGroupStack.back();
    m_autoGroupStack.pop_back();
    // see bug577005: we should not remove the last group for e
    if (!foundInline && !e->groups.empty()) e->groups.pop_back();
    //printf("Removing %s e=%p\n",qPrint(grp->groupname),e);
    if (!foundInline) initGroupInfo(e);
  }
}
References DOX_NOGROUP, e, ghc::filesystem::end(), initGroupInfo(), m_autoGroupStack, m_memberGroupDocs, m_memberGroupId, m_memberGroupRelates, m_openCount, Doxygen::memberGroupInfoMap, QCString::resize(), and warn().
close() [2/2]
void DocGroup::close (Entry * e, const QCString & fileName, int line, bool foundInline, bool implicit = false)
enterCompound() [1/2]
void DocGroup::enterCompound (const QCString & fileName, int line, const QCString & name)
Definition at line 54 of file docgroup.cpp.
{
  if (m_memberGroupId!=DOX_NOGROUP)
  {
    warn(fileName,line,"try to put compound %s inside a member group\n",qPrint(name));
  }
  m_memberGroupId=DOX_NOGROUP;
  m_memberGroupRelates.resize(0);
  m_memberGroupDocs.resize(0);
  m_compoundName = name;
  int i = m_compoundName.find('(');
  if (i!=-1)
  {
    m_compoundName=m_compoundName.left(i); // strip category (Obj-C)
  }
  if (m_compoundName.isEmpty())
  {
    m_compoundName=fileName;
  }
  //printf("groupEnterCompound(%s)\n",qPrint(name));
}
References DOX_NOGROUP, QCString::find(), QCString::isEmpty(), QCString::left(), m_compoundName, m_memberGroupDocs, m_memberGroupId, m_memberGroupRelates, setup::name, qPrint(), QCString::resize(), and warn().
enterCompound() [2/2]
void DocGroup::enterCompound (const QCString & fileName, int line, const QCString & name)
enterFile() [1/2]
void DocGroup::enterFile (const QCString & fileName, int)
Definition at line 25 of file docgroup.cpp.
{
  m_openCount = 0;
  m_autoGroupStack.clear();
  m_memberGroupId = DOX_NOGROUP;
  m_memberGroupDocs.resize(0);
  m_memberGroupRelates.resize(0);
  m_compoundName=fileName;
}
References DOX_NOGROUP, m_autoGroupStack, m_compoundName, m_memberGroupDocs, m_memberGroupId, m_memberGroupRelates, m_openCount, and QCString::resize().
enterFile() [2/2]
void DocGroup::enterFile (const QCString & fileName, int)
findExistingGroup() [1/2]
int DocGroup::findExistingGroup (const MemberGroupInfo * info) [private]
Definition at line 89 of file docgroup.cpp.
{
  //printf("findExistingGroup %s:%s\n",qPrint(info->header),qPrint(info->compoundName));
  for (const auto &kv : Doxygen::memberGroupInfoMap)
  {
    if (m_compoundName==kv.second->compoundName && // same file or scope
    !kv.second->header.isEmpty() && // not a nameless group
    qstricmp(kv.second->header,info->header)==0 // same header name
       )
    {
      //printf("Found it!\n");
      return kv.first; // put the item in this group
    }
  }
  return ++g_groupId; // start new group
}
References g_groupId, MemberGroupInfo::header, QCString::isEmpty(), m_compoundName, Doxygen::memberGroupInfoMap, and qstricmp().
Referenced by open().
findExistingGroup() [2/2]
int DocGroup::findExistingGroup (const MemberGroupInfo * info) [private]
initGroupInfo() [1/2]
void DocGroup::initGroupInfo (Entry * e)
Definition at line 178 of file docgroup.cpp.
{
  //printf("==> initGroup(id=%d,related=%s,e=%p,#stack=%zu)\n",m_memberGroupId,
  // qPrint(m_memberGroupRelates),(void*)e,m_autoGroupStack.size());
  e->mGrpId = m_memberGroupId;
  e->relates = m_memberGroupRelates;
  if (!m_autoGroupStack.empty())
  {
    //printf("Appending group %s to %s: count=%zu entry=%p\n",
    // qPrint(m_autoGroupStack.back().groupname),
    // qPrint(e->name),e->groups.size(),(void*)e);
    e->groups.push_back(Grouping(m_autoGroupStack.back()));
  }
}
References e, m_autoGroupStack, m_memberGroupId, and m_memberGroupRelates.
Referenced by close().
initGroupInfo() [2/2]
void DocGroup::initGroupInfo (Entry * e)
isEmpty() [1/2]
bool DocGroup::isEmpty () const
Definition at line 218 of file docgroup.cpp.
{
  return (m_memberGroupId==DOX_NOGROUP);
}
References DOX_NOGROUP, and m_memberGroupId.
isEmpty() [2/2]
bool DocGroup::isEmpty () const
leaveCompound() [1/2]
void DocGroup::leaveCompound (const QCString & , int , const QCString & name)
Definition at line 76 of file docgroup.cpp.
{
  //printf("groupLeaveCompound(%s)\n",qPrint(name));
  //if (m_memberGroupId!=DOX_NOGROUP)
  //{
  // warn(fileName,line,"end of compound %s while inside a member group\n",qPrint(name));
  //}
  m_memberGroupId=DOX_NOGROUP;
  m_memberGroupRelates.resize(0);
  m_memberGroupDocs.resize(0);
  m_compoundName.resize(0);
}
References DOX_NOGROUP, m_compoundName, m_memberGroupDocs, m_memberGroupId, m_memberGroupRelates, and QCString::resize().
leaveCompound() [2/2]
void DocGroup::leaveCompound (const QCString & , int , const QCString &)
leaveFile() [1/2]
void DocGroup::leaveFile (const QCString & fileName, int line)
Definition at line 35 of file docgroup.cpp.
{
  //if (m_memberGroupId!=DOX_NOGROUP)
  //{
  // warn(fileName,line,"end of file while inside a member group\n");
  //}
  m_memberGroupId=DOX_NOGROUP;
  m_memberGroupRelates.resize(0);
  m_memberGroupDocs.resize(0);
  if (!m_autoGroupStack.empty())
  {
    warn(fileName,line,"end of file while inside a group");
  }
  else if (m_openCount > 0) // < 0 is already handled on close call
  {
    warn(fileName,line,"end of file with unbalanced grouping commands");
  }
}
References DOX_NOGROUP, m_autoGroupStack, m_memberGroupDocs, m_memberGroupId, m_memberGroupRelates, m_openCount, QCString::resize(), and warn().
leaveFile() [2/2]
void DocGroup::leaveFile (const QCString & fileName, int line)
open() [1/2]
void DocGroup::open (Entry * e, const QCString & , int , bool implicit = false)
Definition at line 106 of file docgroup.cpp.
{
  if (!implicit) m_openCount++;
  //printf("==> openGroup(name=%s,sec=%x) m_autoGroupStack=%zu\n",
  // qPrint(e->name),e->section,m_autoGroupStack.size());
  if (e->section==Entry::GROUPDOC_SEC) // auto group
  {
    m_autoGroupStack.push_back(Grouping(e->name,e->groupingPri()));
  }
  else // start of a member group
  {
    //printf(" membergroup id=%d %s\n",m_memberGroupId,qPrint(m_memberGroupHeader));
    if (m_memberGroupId==DOX_NOGROUP) // no group started yet
    {
      auto info = std::make_unique<MemberGroupInfo>();
      info->header = m_memberGroupHeader.stripWhiteSpace();
      info->compoundName = m_compoundName;
      m_memberGroupId = findExistingGroup(info.get());
      auto it = Doxygen::memberGroupInfoMap.find(m_memberGroupId);
      if (it==Doxygen::memberGroupInfoMap.end())
      {
         //printf(" use membergroup %d\n",m_memberGroupId);
         Doxygen::memberGroupInfoMap.insert(std::make_pair(m_memberGroupId,std::move(info)));
      }
      m_memberGroupRelates = e->relates;
      e->mGrpId = m_memberGroupId;
    }
  }
}
References DOX_NOGROUP, e, ghc::filesystem::end(), findExistingGroup(), Entry::GROUPDOC_SEC, m_autoGroupStack, m_compoundName, m_memberGroupHeader, m_memberGroupId, m_memberGroupRelates, m_openCount, Doxygen::memberGroupInfoMap, and QCString::stripWhiteSpace().
open() [2/2]
void DocGroup::open (Entry * e, const QCString & , int , bool implicit = false)
Member Data Documentation
m_autoGroupStack
std::vector< Grouping > DocGroup::m_autoGroupStack [private]
Definition at line 49 of file docgroup.h.
Referenced by close(), enterFile(), initGroupInfo(), leaveFile(), and open().
m_compoundName
QCString DocGroup::m_compoundName [private]
Definition at line 50 of file docgroup.h.
Referenced by enterCompound(), enterFile(), findExistingGroup(), leaveCompound(), and open().
m_memberGroupDocs
QCString DocGroup::m_memberGroupDocs [private]
Definition at line 48 of file docgroup.h.
Referenced by addDocs(), close(), enterCompound(), enterFile(), leaveCompound(), and leaveFile().
m_memberGroupHeader
QCString DocGroup::m_memberGroupHeader [private]
Definition at line 45 of file docgroup.h.
Referenced by appendHeader(), clearHeader(), and open().
m_memberGroupId
int DocGroup::m_memberGroupId = 0 [private]
Definition at line 46 of file docgroup.h.
Referenced by addDocs(), close(), enterCompound(), enterFile(), initGroupInfo(), isEmpty(), leaveCompound(), leaveFile(), and open().
m_memberGroupRelates
QCString DocGroup::m_memberGroupRelates [private]
Definition at line 47 of file docgroup.h.
Referenced by close(), enterCompound(), enterFile(), initGroupInfo(), leaveCompound(), leaveFile(), and open().
m_openCount
int DocGroup::m_openCount = 0 [private]
Definition at line 44 of file docgroup.h.
Referenced by close(), enterFile(), leaveFile(), and open().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docgroup.h
doxygen/src/docgroup.h
doxygen/build/doxygen/src/docgroup.cpp
doxygen/src/docgroup.cpp