PropertyMap< T > Class Template Reference
Public Types
using Map = std::map< std::string, TemplateVariant(T::*)() const >
using Map = std::map< std::string, TemplateVariant(T::*)() const >
Public Member Functions
PropertyMap (std::initializer_list< typename Map::value_type > init)
TemplateVariant get (const T *obj, const QCString &n) const
StringVector fields () const
Map & map ()
PropertyMap (std::initializer_list< typename Map::value_type > init)
TemplateVariant get (const T *obj, const QCString &n) const
StringVector fields () const
Map & map ()
Private Attributes
const Map m_map
Detailed Description
template<class T>
class PropertyMap< T >
Class representing a mapping of properties and the corresponding getter function. The map should be initialized at initialization time.
Definition at line 118 of file context.cpp.
Member Typedef Documentation
Map [1/2]
template<class T >
using PropertyMap< T >::Map = std::map< std::string, TemplateVariant(T::*)() const >
Definition at line 121 of file context.cpp.
Map [2/2]
template<class T >
using PropertyMap< T >::Map = std::map< std::string, TemplateVariant(T::*)() const >
Definition at line 121 of file context.cpp.
Constructor & Destructor Documentation
PropertyMap() [1/2]
template<class T >
PropertyMap< T >::PropertyMap (std::initializer_list< typename Map::value_type > init) [inline]
Definition at line 123 of file context.cpp.
      : m_map(init) {}
PropertyMap() [2/2]
template<class T >
PropertyMap< T >::PropertyMap (std::initializer_list< typename Map::value_type > init) [inline]
Definition at line 123 of file context.cpp.
      : m_map(init) {}
Member Function Documentation
fields() [1/2]
template<class T >
StringVector PropertyMap< T >::fields () const [inline]
Definition at line 131 of file context.cpp.
    {
      StringVector result;
      result.reserve(m_map.size());
      for (const auto &imap : m_map) result.push_back(imap.first);
      return result;
    }
References PropertyMap< T >::m_map.
Referenced by DoxygenContext::Private::fields(), TranslateContext::Private::fields(), IncludeInfoContext::Private::fields(), ClassContext::Private::fields(), NamespaceContext::Private::fields(), FileContext::Private::fields(), DirContext::Private::fields(), PageContext::Private::fields(), MemberContext::Private::fields(), ConceptContext::Private::fields(), ModuleContext::Private::fields(), ClassIndexContext::Private::fields(), ClassHierarchyContext::Private::fields(), NestingNodeContext::Private::fields(), ClassTreeContext::Private::fields(), NamespaceTreeContext::Private::fields(), FileTreeContext::Private::fields(), PageTreeContext::Private::fields(), ConceptTreeContext::Private::fields(), ModuleTreeContext::Private::fields(), ExampleTreeContext::Private::fields(), NavPathElemContext::Private::fields(), GlobalsIndexContext::Private::fields(), ClassMembersIndexContext::Private::fields(), NamespaceMembersIndexContext::Private::fields(), InheritanceGraphContext::Private::fields(), InheritanceNodeContext::Private::fields(), MemberInfoContext::Private::fields(), MemberGroupInfoContext::Private::fields(), MemberListInfoContext::Private::fields(), InheritedMemberInfoContext::Private::fields(), ArgumentContext::Private::fields(), SymbolContext::Private::fields(), SymbolGroupContext::Private::fields(), SymbolIndexContext::Private::fields(), and SearchIndexContext::Private::fields().
fields() [2/2]
template<class T >
StringVector PropertyMap< T >::fields () const [inline]
Definition at line 131 of file context.cpp.
    {
      StringVector result;
      result.reserve(m_map.size());
      for (const auto &imap : m_map) result.push_back(imap.first);
      return result;
    }
References PropertyMap< T >::m_map.
get() [1/2]
template<class T >
TemplateVariant PropertyMap< T >::get (const T * obj, const QCString & n) const [inline]
Definition at line 126 of file context.cpp.
    {
      auto it = m_map.find(n.str());
      return it!=m_map.end() ? (obj->*(it->second))() : TemplateVariant();
    }
References PropertyMap< T >::m_map, and n.
Referenced by DoxygenContext::Private::get(), TranslateContext::Private::get(), IncludeInfoContext::Private::get(), ClassContext::Private::get(), NamespaceContext::Private::get(), FileContext::Private::get(), DirContext::Private::get(), PageContext::Private::get(), MemberContext::Private::get(), ConceptContext::Private::get(), ModuleContext::Private::get(), ClassIndexContext::Private::get(), ClassHierarchyContext::Private::get(), NestingNodeContext::Private::get(), ClassTreeContext::Private::get(), NamespaceTreeContext::Private::get(), FileTreeContext::Private::get(), PageTreeContext::Private::get(), ConceptTreeContext::Private::get(), ModuleTreeContext::Private::get(), ExampleTreeContext::Private::get(), NavPathElemContext::Private::get(), GlobalsIndexContext::Private::get(), ClassMembersIndexContext::Private::get(), NamespaceMembersIndexContext::Private::get(), InheritanceGraphContext::Private::get(), InheritanceNodeContext::Private::get(), MemberInfoContext::Private::get(), MemberGroupInfoContext::Private::get(), MemberListInfoContext::Private::get(), InheritedMemberInfoContext::Private::get(), ArgumentContext::Private::get(), SymbolContext::Private::get(), SymbolGroupContext::Private::get(), SymbolIndexContext::Private::get(), and SearchIndexContext::Private::get().
get() [2/2]
template<class T >
TemplateVariant PropertyMap< T >::get (const T * obj, const QCString & n) const [inline]
Definition at line 126 of file context.cpp.
    {
      auto it = m_map.find(n.str());
      return it!=m_map.end() ? (obj->*(it->second))() : TemplateVariant();
    }
References PropertyMap< T >::m_map, and n.
map() [1/2]
template<class T >
Map & PropertyMap< T >::map () [inline]
Definition at line 139 of file context.cpp.
{ return m_map; }
References PropertyMap< T >::m_map.
map() [2/2]
template<class T >
Map & PropertyMap< T >::map () [inline]
Definition at line 139 of file context.cpp.
{ return m_map; }
References PropertyMap< T >::m_map.
Member Data Documentation
m_map
template<class T >
const Map PropertyMap< T >::m_map [private]
Definition at line 142 of file context.cpp.
Referenced by PropertyMap< T >::fields(), PropertyMap< T >::get(), and PropertyMap< T >::map().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp