ClassMembersIndexContext::Private Class Reference
Public Member Functions
TemplateVariant get (const QCString &n) const
StringVector fields () const
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private Types
using MemberFilter = bool(MemberDef::*)() const
using MemberFilter = bool(MemberDef::*)() const
Private Member Functions
TemplateVariant all () const
TemplateVariant functions () const
TemplateVariant variables () const
TemplateVariant typedefs () const
TemplateVariant enums () const
TemplateVariant enumValues () const
TemplateVariant macros () const
TemplateVariant properties () const
TemplateVariant events () const
TemplateVariant related () const
TemplateVariant fileName () const
TemplateVariant relPath () const
TemplateVariant highlight () const
TemplateVariant subhighlight () const
TemplateVariant title () const
TemplateVariant createMembersFiltered (MemberFilter filter) const
TemplateVariant createAll () const
TemplateVariant createFunctions () const
TemplateVariant createVariables () const
TemplateVariant createTypedefs () const
TemplateVariant createEnums () const
TemplateVariant createEnumValues () const
TemplateVariant createProperties () const
TemplateVariant createEvents () const
TemplateVariant createRelated () const
TemplateVariant all () const
TemplateVariant functions () const
TemplateVariant variables () const
TemplateVariant typedefs () const
TemplateVariant enums () const
TemplateVariant enumValues () const
TemplateVariant macros () const
TemplateVariant properties () const
TemplateVariant events () const
TemplateVariant related () const
TemplateVariant fileName () const
TemplateVariant relPath () const
TemplateVariant highlight () const
TemplateVariant subhighlight () const
TemplateVariant title () const
TemplateVariant createMembersFiltered (MemberFilter filter) const
TemplateVariant createAll () const
TemplateVariant createFunctions () const
TemplateVariant createVariables () const
TemplateVariant createTypedefs () const
TemplateVariant createEnums () const
TemplateVariant createEnumValues () const
TemplateVariant createProperties () const
TemplateVariant createEvents () const
TemplateVariant createRelated () const
Private Attributes
CachedItem< TemplateVariant, Private, &Private::createAll > m_all
CachedItem< TemplateVariant, Private, &Private::createFunctions > m_functions
CachedItem< TemplateVariant, Private, &Private::createVariables > m_variables
CachedItem< TemplateVariant, Private, &Private::createTypedefs > m_typedefs
CachedItem< TemplateVariant, Private, &Private::createEnums > m_enums
CachedItem< TemplateVariant, Private, &Private::createEnumValues > m_enumValues
CachedItem< TemplateVariant, Private, &Private::createProperties > m_properties
CachedItem< TemplateVariant, Private, &Private::createEvents > m_events
CachedItem< TemplateVariant, Private, &Private::createRelated > m_related
Static Private Attributes
static const PropertyMap< ClassMembersIndexContext::Private > s_inst
Detailed Description
Definition at line 7182 of file context.cpp.
Member Typedef Documentation
MemberFilter [1/2]
using ClassMembersIndexContext::Private::MemberFilter = bool (MemberDef::*)() const [private]
Definition at line 7208 of file context.cpp.
MemberFilter [2/2]
using ClassMembersIndexContext::Private::MemberFilter = bool (MemberDef::*)() const [private]
Definition at line 7208 of file context.cpp.
Member Function Documentation
all() [1/2]
TemplateVariant ClassMembersIndexContext::Private::all () const [inline], [private]
Definition at line 7191 of file context.cpp.
{ return m_all.get(this); }
References m_all.
all() [2/2]
TemplateVariant ClassMembersIndexContext::Private::all () const [inline], [private]
Definition at line 7191 of file context.cpp.
{ return m_all.get(this); }
createAll() [1/2]
TemplateVariant ClassMembersIndexContext::Private::createAll () const [inline], [private]
Definition at line 7229 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isNotFriend); }
References createMembersFiltered(), and MemberDef::isNotFriend().
createAll() [2/2]
TemplateVariant ClassMembersIndexContext::Private::createAll () const [inline], [private]
Definition at line 7229 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isNotFriend); }
References MemberDef::isNotFriend().
createEnums() [1/2]
TemplateVariant ClassMembersIndexContext::Private::createEnums () const [inline], [private]
Definition at line 7233 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isEnumerate); }
References createMembersFiltered(), and MemberDef::isEnumerate().
createEnums() [2/2]
TemplateVariant ClassMembersIndexContext::Private::createEnums () const [inline], [private]
Definition at line 7233 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isEnumerate); }
References MemberDef::isEnumerate().
createEnumValues() [1/2]
TemplateVariant ClassMembersIndexContext::Private::createEnumValues () const [inline], [private]
Definition at line 7234 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isEnumValue); }
References createMembersFiltered(), and MemberDef::isEnumValue().
createEnumValues() [2/2]
TemplateVariant ClassMembersIndexContext::Private::createEnumValues () const [inline], [private]
Definition at line 7234 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isEnumValue); }
References MemberDef::isEnumValue().
createEvents() [1/2]
TemplateVariant ClassMembersIndexContext::Private::createEvents () const [inline], [private]
Definition at line 7236 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isEvent); }
References createMembersFiltered(), and MemberDef::isEvent().
createEvents() [2/2]
TemplateVariant ClassMembersIndexContext::Private::createEvents () const [inline], [private]
Definition at line 7236 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isEvent); }
References MemberDef::isEvent().
createFunctions() [1/2]
TemplateVariant ClassMembersIndexContext::Private::createFunctions () const [inline], [private]
Definition at line 7230 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isFunctionOrSignalSlot); }
References createMembersFiltered(), and MemberDef::isFunctionOrSignalSlot().
createFunctions() [2/2]
TemplateVariant ClassMembersIndexContext::Private::createFunctions () const [inline], [private]
Definition at line 7230 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isFunctionOrSignalSlot); }
References MemberDef::isFunctionOrSignalSlot().
createMembersFiltered() [1/2]
TemplateVariant ClassMembersIndexContext::Private::createMembersFiltered (MemberFilter filter) const [inline], [private]
Definition at line 7209 of file context.cpp.
    {
      TemplateVariantList list;
      for (const auto &mn : *Doxygen::memberNameLinkedMap)
      {
        for (const auto &md : *mn)
        {
          const ClassDef *cd = md->getClassDef();
          if (cd && cd->isLinkableInProject() && cd->templateMaster()==0 &&
              md->isLinkableInProject() && !md->name().isEmpty())
          {
            if (filter==0 || (md.get()->*filter)())
            {
              list.push_back(MemberContext::alloc(md.get()));
            }
          }
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References MemberContext::alloc(), TemplateImmutableList::alloc(), filter, ClassDef::isLinkableInProject(), Doxygen::memberNameLinkedMap, and ClassDef::templateMaster().
Referenced by createAll(), createEnums(), createEnumValues(), createEvents(), createFunctions(), createProperties(), createRelated(), createTypedefs(), and createVariables().
createMembersFiltered() [2/2]
TemplateVariant ClassMembersIndexContext::Private::createMembersFiltered (MemberFilter filter) const [inline], [private]
Definition at line 7209 of file context.cpp.
    {
      TemplateVariantList list;
      for (const auto &mn : *Doxygen::memberNameLinkedMap)
      {
        for (const auto &md : *mn)
        {
          const ClassDef *cd = md->getClassDef();
          if (cd && cd->isLinkableInProject() && cd->templateMaster()==0 &&
              md->isLinkableInProject() && !md->name().isEmpty())
          {
            if (filter==0 || (md.get()->*filter)())
            {
              list.push_back(MemberContext::alloc(md.get()));
            }
          }
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References MemberContext::alloc(), TemplateImmutableList::alloc(), filter, ClassDef::isLinkableInProject(), Doxygen::memberNameLinkedMap, and ClassDef::templateMaster().
createProperties() [1/2]
TemplateVariant ClassMembersIndexContext::Private::createProperties () const [inline], [private]
Definition at line 7235 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isProperty); }
References createMembersFiltered(), and MemberDef::isProperty().
createProperties() [2/2]
TemplateVariant ClassMembersIndexContext::Private::createProperties () const [inline], [private]
Definition at line 7235 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isProperty); }
References MemberDef::isProperty().
createRelated() [1/2]
TemplateVariant ClassMembersIndexContext::Private::createRelated () const [inline], [private]
Definition at line 7237 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isRelated); }
References createMembersFiltered(), and MemberDef::isRelated().
createRelated() [2/2]
TemplateVariant ClassMembersIndexContext::Private::createRelated () const [inline], [private]
Definition at line 7237 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isRelated); }
References MemberDef::isRelated().
createTypedefs() [1/2]
TemplateVariant ClassMembersIndexContext::Private::createTypedefs () const [inline], [private]
Definition at line 7232 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isTypedef); }
References createMembersFiltered(), and MemberDef::isTypedef().
createTypedefs() [2/2]
TemplateVariant ClassMembersIndexContext::Private::createTypedefs () const [inline], [private]
Definition at line 7232 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isTypedef); }
References MemberDef::isTypedef().
createVariables() [1/2]
TemplateVariant ClassMembersIndexContext::Private::createVariables () const [inline], [private]
Definition at line 7231 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isVariable); }
References createMembersFiltered(), and MemberDef::isVariable().
createVariables() [2/2]
TemplateVariant ClassMembersIndexContext::Private::createVariables () const [inline], [private]
Definition at line 7231 of file context.cpp.
{ return createMembersFiltered(&MemberDef::isVariable); }
References MemberDef::isVariable().
enums() [1/2]
TemplateVariant ClassMembersIndexContext::Private::enums () const [inline], [private]
Definition at line 7195 of file context.cpp.
{ return m_enums.get(this); }
References m_enums.
enums() [2/2]
TemplateVariant ClassMembersIndexContext::Private::enums () const [inline], [private]
Definition at line 7195 of file context.cpp.
{ return m_enums.get(this); }
enumValues() [1/2]
TemplateVariant ClassMembersIndexContext::Private::enumValues () const [inline], [private]
Definition at line 7196 of file context.cpp.
{ return m_enumValues.get(this); }
References m_enumValues.
enumValues() [2/2]
TemplateVariant ClassMembersIndexContext::Private::enumValues () const [inline], [private]
Definition at line 7196 of file context.cpp.
{ return m_enumValues.get(this); }
events() [1/2]
TemplateVariant ClassMembersIndexContext::Private::events () const [inline], [private]
Definition at line 7199 of file context.cpp.
{ return m_events.get(this); }
References m_events.
events() [2/2]
TemplateVariant ClassMembersIndexContext::Private::events () const [inline], [private]
Definition at line 7199 of file context.cpp.
{ return m_events.get(this); }
fields() [1/2]
StringVector ClassMembersIndexContext::Private::fields () const [inline]
Definition at line 7187 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
fields() [2/2]
StringVector ClassMembersIndexContext::Private::fields () const [inline]
Definition at line 7187 of file context.cpp.
{ return s_inst.fields(); }
fileName() [1/2]
TemplateVariant ClassMembersIndexContext::Private::fileName () const [inline], [private]
Definition at line 7201 of file context.cpp.
{ return "functions"; }
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
fileName() [2/2]
TemplateVariant ClassMembersIndexContext::Private::fileName () const [inline], [private]
Definition at line 7201 of file context.cpp.
{ return "functions"; }
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
functions() [1/2]
TemplateVariant ClassMembersIndexContext::Private::functions () const [inline], [private]
Definition at line 7192 of file context.cpp.
{ return m_functions.get(this); }
References m_functions.
functions() [2/2]
TemplateVariant ClassMembersIndexContext::Private::functions () const [inline], [private]
Definition at line 7192 of file context.cpp.
{ return m_functions.get(this); }
get() [1/2]
TemplateVariant ClassMembersIndexContext::Private::get (const QCString & n) const [inline]
Definition at line 7186 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), n, and s_inst.
get() [2/2]
TemplateVariant ClassMembersIndexContext::Private::get (const QCString & n) const [inline]
Definition at line 7186 of file context.cpp.
{ return s_inst.get(this,n); }
References n.
highlight() [1/2]
TemplateVariant ClassMembersIndexContext::Private::highlight () const [inline], [private]
Definition at line 7203 of file context.cpp.
{ return "classes"; }
Referenced by doxmlparser.compound.codelineType::__init__(), doxmlparser.compound.codelineType::add_highlight(), doxmlparser.compound.codelineType::buildChildren(), doxmlparser.compound.codelineType::exportChildren(), doxmlparser.compound.codelineType::get_highlight(), doxmlparser.compound.codelineType::hasContent_(), doxmlparser.compound.codelineType::insert_highlight_at(), doxmlparser.compound.codelineType::replace_highlight_at(), and doxmlparser.compound.codelineType::set_highlight().
highlight() [2/2]
TemplateVariant ClassMembersIndexContext::Private::highlight () const [inline], [private]
Definition at line 7203 of file context.cpp.
{ return "classes"; }
Referenced by doxmlparser.compound.codelineType::__init__(), doxmlparser.compound.codelineType::add_highlight(), doxmlparser.compound.codelineType::buildChildren(), doxmlparser.compound.codelineType::exportChildren(), doxmlparser.compound.codelineType::get_highlight(), doxmlparser.compound.codelineType::hasContent_(), doxmlparser.compound.codelineType::insert_highlight_at(), doxmlparser.compound.codelineType::replace_highlight_at(), and doxmlparser.compound.codelineType::set_highlight().
macros() [1/2]
TemplateVariant ClassMembersIndexContext::Private::macros () const [inline], [private]
Definition at line 7197 of file context.cpp.
{ return FALSE; }
References FALSE.
macros() [2/2]
TemplateVariant ClassMembersIndexContext::Private::macros () const [inline], [private]
Definition at line 7197 of file context.cpp.
{ return FALSE; }
References FALSE.
properties() [1/2]
TemplateVariant ClassMembersIndexContext::Private::properties () const [inline], [private]
Definition at line 7198 of file context.cpp.
{ return m_properties.get(this); }
References m_properties.
properties() [2/2]
TemplateVariant ClassMembersIndexContext::Private::properties () const [inline], [private]
Definition at line 7198 of file context.cpp.
{ return m_properties.get(this); }
related() [1/2]
TemplateVariant ClassMembersIndexContext::Private::related () const [inline], [private]
Definition at line 7200 of file context.cpp.
{ return m_related.get(this); }
References m_related.
related() [2/2]
TemplateVariant ClassMembersIndexContext::Private::related () const [inline], [private]
Definition at line 7200 of file context.cpp.
{ return m_related.get(this); }
relPath() [1/2]
TemplateVariant ClassMembersIndexContext::Private::relPath () const [inline], [private]
Definition at line 7202 of file context.cpp.
{ return ""; }
relPath() [2/2]
TemplateVariant ClassMembersIndexContext::Private::relPath () const [inline], [private]
Definition at line 7202 of file context.cpp.
{ return ""; }
subhighlight() [1/2]
TemplateVariant ClassMembersIndexContext::Private::subhighlight () const [inline], [private]
Definition at line 7204 of file context.cpp.
{ return "classmembers"; }
subhighlight() [2/2]
TemplateVariant ClassMembersIndexContext::Private::subhighlight () const [inline], [private]
Definition at line 7204 of file context.cpp.
{ return "classmembers"; }
title() [1/2]
TemplateVariant ClassMembersIndexContext::Private::title () const [inline], [private]
Definition at line 7205 of file context.cpp.
{ return theTranslator->trCompoundMembers(); }
References theTranslator, and Translator::trCompoundMembers().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
title() [2/2]
TemplateVariant ClassMembersIndexContext::Private::title () const [inline], [private]
Definition at line 7205 of file context.cpp.
{ return theTranslator->trCompoundMembers(); }
References theTranslator, and Translator::trCompoundMembers().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
typedefs() [1/2]
TemplateVariant ClassMembersIndexContext::Private::typedefs () const [inline], [private]
Definition at line 7194 of file context.cpp.
{ return m_typedefs.get(this); }
References m_typedefs.
typedefs() [2/2]
TemplateVariant ClassMembersIndexContext::Private::typedefs () const [inline], [private]
Definition at line 7194 of file context.cpp.
{ return m_typedefs.get(this); }
variables() [1/2]
TemplateVariant ClassMembersIndexContext::Private::variables () const [inline], [private]
Definition at line 7193 of file context.cpp.
{ return m_variables.get(this); }
References m_variables.
variables() [2/2]
TemplateVariant ClassMembersIndexContext::Private::variables () const [inline], [private]
Definition at line 7193 of file context.cpp.
{ return m_variables.get(this); }
Member Data Documentation
m_all
CachedItem< TemplateVariant, Private, &Private::createAll > ClassMembersIndexContext::Private::m_all [private]
Definition at line 7239 of file context.cpp.
Referenced by all().
m_enums
CachedItem< TemplateVariant, Private, &Private::createEnums > ClassMembersIndexContext::Private::m_enums [private]
Definition at line 7243 of file context.cpp.
Referenced by enums().
m_enumValues
CachedItem< TemplateVariant, Private, &Private::createEnumValues > ClassMembersIndexContext::Private::m_enumValues [private]
Definition at line 7244 of file context.cpp.
Referenced by enumValues().
m_events
CachedItem< TemplateVariant, Private, &Private::createEvents > ClassMembersIndexContext::Private::m_events [private]
Definition at line 7246 of file context.cpp.
Referenced by events().
m_functions
CachedItem< TemplateVariant, Private, &Private::createFunctions > ClassMembersIndexContext::Private::m_functions [private]
Definition at line 7240 of file context.cpp.
Referenced by functions().
m_properties
CachedItem< TemplateVariant, Private, &Private::createProperties > ClassMembersIndexContext::Private::m_properties [private]
Definition at line 7245 of file context.cpp.
Referenced by properties().
m_related
CachedItem< TemplateVariant, Private, &Private::createRelated > ClassMembersIndexContext::Private::m_related [private]
Definition at line 7247 of file context.cpp.
Referenced by related().
m_typedefs
CachedItem< TemplateVariant, Private, &Private::createTypedefs > ClassMembersIndexContext::Private::m_typedefs [private]
Definition at line 7242 of file context.cpp.
Referenced by typedefs().
m_variables
CachedItem< TemplateVariant, Private, &Private::createVariables > ClassMembersIndexContext::Private::m_variables [private]
Definition at line 7241 of file context.cpp.
Referenced by variables().
s_inst
const PropertyMap< ClassMembersIndexContext::Private > ClassMembersIndexContext::Private::s_inst [static], [private]
Initial value:
{
  { "all", &Private::all },
  { "functions", &Private::functions },
  { "variables", &Private::variables },
  { "typedefs", &Private::typedefs },
  { "enums", &Private::enums },
  { "enumValues", &Private::enumValues },
  { "macros", &Private::macros },
  { "properties", &Private::properties },
  { "events", &Private::events },
  { "related", &Private::related },
  { "fileName", &Private::fileName },
  { "relPath", &Private::relPath },
  { "highlight", &Private::highlight },
  { "subhighlight",&Private::subhighlight },
  { "title", &Private::title }
}
Definition at line 7248 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp