DocRef Class Reference
#include <docnode.h>
Public Member Functions
DocRef (DocParser *parser, DocNodeVariant *parent, const QCString &target, const QCString &context)
void parse (DocNodeVariant *)
QCString file () const
QCString relPath () const
QCString ref () const
QCString anchor () const
QCString targetTitle () const
bool hasLinkText () const
bool refToAnchor () const
bool refToSection () const
bool refToTable () const
bool isSubPage () const
DocRef (DocParser *parser, DocNodeVariant *parent, const QCString &target, const QCString &context)
void parse (DocNodeVariant *)
QCString file () const
QCString relPath () const
QCString ref () const
QCString anchor () const
QCString targetTitle () const
bool hasLinkText () const
bool refToAnchor () const
bool refToSection () const
bool refToTable () const
bool isSubPage () const
Private Attributes
RefType m_refType = Unknown
bool m_isSubPage = false
QCString m_file
QCString m_relPath
QCString m_ref
QCString m_anchor
QCString m_text
Additional Inherited Members
Detailed Description
Node representing a reference to some item
Definition at line 732 of file docnode.h.
Constructor & Destructor Documentation
DocRef() [1/2]
DocRef::DocRef (DocParser * parser, DocNodeVariant * parent, const QCString & target, const QCString & context)
Definition at line 695 of file docnode.cpp.
                                                                                                      :
   DocCompoundNode(parser,parent), m_refType(Unknown), m_isSubPage(FALSE)
{
  const Definition *compound = 0;
  QCString anchor;
  //printf("DocRef::DocRef(target=%s,context=%s)\n",qPrint(target),qPrint(context));
  ASSERT(!target.isEmpty());
  SrcLangExt lang = getLanguageFromFileName(target);
  m_relPath = parser->context.relPath;
  const SectionInfo *sec = SectionManager::instance().find(target);
  if (sec==0 && lang==SrcLangExt_Markdown) // lookup as markdown file
  {
    sec = SectionManager::instance().find(markdownFileNameToId(target));
  }
  if (sec) // ref to section or anchor
  {
    PageDef *pd = 0;
    if (sec->type()==SectionType::Page)
    {
      pd = Doxygen::pageLinkedMap->find(target);
    }
    m_text = sec->title();
    if (m_text.isEmpty()) m_text = sec->label();
    m_ref = sec->ref();
    m_file = stripKnownExtensions(sec->fileName());
    if (sec->type()==SectionType::Anchor)
    {
      m_refType = Anchor;
    }
    else if (sec->type()==SectionType::Table)
    {
      m_refType = Table;
    }
    else
    {
      m_refType = Section;
    }
    m_isSubPage = pd && pd->hasParentPage();
    if (sec->type()!=SectionType::Page || m_isSubPage) m_anchor = sec->label();
    //printf("m_text=%s,m_ref=%s,m_file=%s,type=%d\n",
    // qPrint(m_text),qPrint(m_ref),qPrint(m_file),m_refType);
    return;
  }
  else if (resolveLink(context,target,TRUE,&compound,anchor))
  {
    bool isFile = compound ?
                 (compound->definitionType()==Definition::TypeFile ||
                  compound->definitionType()==Definition::TypePage ? TRUE : FALSE) :
                 FALSE;
    m_text = linkToText(compound?compound->getLanguage():SrcLangExt_Unknown,target,isFile);
    m_anchor = anchor;
    if (compound && compound->isLinkable()) // ref to compound
    {
      if (anchor.isEmpty() && /* compound link */
          compound->definitionType()==Definition::TypeGroup && /* is group */
          !toGroupDef(compound)->groupTitle().isEmpty() /* with title */
         )
      {
        m_text=(toGroupDef(compound))->groupTitle(); // use group's title as link
      }
      else if (compound->definitionType()==Definition::TypeMember &&
          toMemberDef(compound)->isObjCMethod())
      {
        // Objective C Method
        const MemberDef *member = toMemberDef(compound);
        bool localLink = parser->context.memberDef ? member->getClassDef()==parser->context.memberDef->getClassDef() : FALSE;
        m_text = member->objCMethodName(localLink,parser->context.inSeeBlock);
      }
      m_file = compound->getOutputFileBase();
      m_ref = compound->getReference();
      //printf("isFile=%d compound=%s (%d)\n",isFile,qPrint(compound->name()),
      // compound->definitionType());
      return;
    }
    else if (compound && compound->definitionType()==Definition::TypeFile &&
             toFileDef(compound)->generateSourceFile()
            ) // undocumented file that has source code we can link to
    {
      m_file = compound->getSourceFileBase();
      m_ref = compound->getReference();
      return;
    }
  }
  m_text = target;
  warn_doc_error(parser->context.fileName,parser->tokenizer.getLineNr(),"unable to resolve reference to '%s' for \\ref command",
           qPrint(target));
}
References DocNode::Anchor, anchor(), Anchor, ASSERT, DocParser::context, Definition::definitionType(), FALSE, DocParserContext::fileName, SectionInfo::fileName(), LinkedMap< T, Hash, KeyEqual, Map >::find(), MemberDef::getClassDef(), Definition::getLanguage(), getLanguageFromFileName(), DocTokenizer::getLineNr(), Definition::getOutputFileBase(), Definition::getReference(), Definition::getSourceFileBase(), PageDef::hasParentPage(), DocParserContext::inSeeBlock, SectionManager::instance(), QCString::isEmpty(), Definition::isLinkable(), MemberDef::isObjCMethod(), SectionInfo::label(), linkToText(), m_anchor, m_file, m_isSubPage, m_ref, m_refType, m_relPath, m_text, markdownFileNameToId(), DocParserContext::memberDef, MemberDef::objCMethodName(), Page, Doxygen::pageLinkedMap, DocNode::parser(), qPrint(), SectionInfo::ref(), DocParserContext::relPath, resolveLink(), DocNode::Section, SrcLangExt_Markdown, SrcLangExt_Unknown, stripKnownExtensions(), DocNode::Table, Table, SectionInfo::title(), toFileDef(), toGroupDef(), DocParser::tokenizer, toMemberDef(), TRUE, SectionInfo::type(), Definition::TypeFile, Definition::TypeGroup, Definition::TypeMember, Definition::TypePage, and warn_doc_error().
DocRef() [2/2]
DocRef::DocRef (DocParser * parser, DocNodeVariant * parent, const QCString & target, const QCString & context)
Member Function Documentation
anchor() [1/2]
QCString DocRef::anchor () const [inline]
Definition at line 740 of file docnode.h.
{ return m_anchor; }
References m_anchor.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), convertMapFile(), DocRef(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), XmlDocVisitor::operator()(), LatexDocVisitor::operator()(), PrintDocVisitor::operator()(), RTFDocVisitor::operator()(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), replaceRef(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
anchor() [2/2]
QCString DocRef::anchor () const [inline]
Definition at line 740 of file docnode.h.
{ return m_anchor; }
References m_anchor.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
file() [1/2]
QCString DocRef::file () const [inline]
Definition at line 737 of file docnode.h.
{ return m_file; }
References m_file.
Referenced by doxmlparser.compound.locationType::__init__(), doxmlparser.compound.locationType::buildAttributes(), convertMapFile(), doxmlparser.compound.locationType::exportAttributes(), doxmlparser.compound.locationType::get_file(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), XmlDocVisitor::operator()(), LatexDocVisitor::operator()(), PrintDocVisitor::operator()(), RTFDocVisitor::operator()(), replaceRef(), and doxmlparser.compound.locationType::set_file().
file() [2/2]
QCString DocRef::file () const [inline]
Definition at line 737 of file docnode.h.
{ return m_file; }
References m_file.
Referenced by doxmlparser.compound.locationType::__init__(), doxmlparser.compound.locationType::buildAttributes(), doxmlparser.compound.locationType::exportAttributes(), doxmlparser.compound.locationType::get_file(), and doxmlparser.compound.locationType::set_file().
hasLinkText() [1/2]
bool DocRef::hasLinkText () const [inline]
Definition at line 742 of file docnode.h.
{ return !children().empty(); }
References DocCompoundNode::children(), and GrowVector< T >::empty().
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), PerlModDocVisitor::operator()(), XmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), PrintDocVisitor::operator()(), and RTFDocVisitor::operator()().
hasLinkText() [2/2]
bool DocRef::hasLinkText () const [inline]
Definition at line 742 of file docnode.h.
{ return !children().empty(); }
References DocCompoundNode::children(), and GrowVector< T >::empty().
isSubPage() [1/2]
bool DocRef::isSubPage () const [inline]
Definition at line 746 of file docnode.h.
{ return m_isSubPage; }
References m_isSubPage.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), XmlDocVisitor::operator()(), LatexDocVisitor::operator()(), and RTFDocVisitor::operator()().
isSubPage() [2/2]
bool DocRef::isSubPage () const [inline]
Definition at line 746 of file docnode.h.
{ return m_isSubPage; }
References m_isSubPage.
parse() [1/2]
void DocRef::parse (DocNodeVariant * thisVariant)
Definition at line 808 of file docnode.cpp.
{
  auto ns = AutoNodeStack(parser(),thisVariant);
  DBG(("DocRef::parse() start\n"));
  int tok;
  while ((tok=parser()->tokenizer.lex()))
  {
    if (!parser()->defaultHandleToken(thisVariant,tok,children()))
    {
      switch (tok)
      {
        case TK_HTMLTAG:
          break;
        default:
          parser()->errorHandleDefaultToken(thisVariant,tok,children(),"\\ref");
          break;
      }
    }
  }
  if (children().empty() && !m_text.isEmpty())
  {
    parser()->context.insideHtmlLink=TRUE;
    parser()->pushContext();
    parser()->internalValidatingParseDoc(thisVariant,children(),m_text);
    parser()->popContext();
    parser()->context.insideHtmlLink=FALSE;
    flattenParagraphs(thisVariant,children());
  }
  parser()->handlePendingStyleCommands(thisVariant,children());
}
References DocCompoundNode::children(), DocParser::context, DBG, DocParser::errorHandleDefaultToken(), FALSE, flattenParagraphs(), DocParser::handlePendingStyleCommands(), DocParserContext::insideHtmlLink, DocParser::internalValidatingParseDoc(), QCString::isEmpty(), m_text, DocNode::parser(), DocParser::popContext(), DocParser::pushContext(), TK_HTMLTAG, and TRUE.
parse() [2/2]
void DocRef::parse (DocNodeVariant *)
ref() [1/2]
QCString DocRef::ref () const [inline]
Definition at line 739 of file docnode.h.
{ return m_ref; }
References m_ref.
Referenced by doxmlparser.compound.highlightType::__init__(), doxmlparser.compound.docParamName::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.linkedTextType::__init__(), doxmlparser.compound.docParamType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.linkedTextType::add_ref(), doxmlparser.compound.highlightType::add_ref(), doxmlparser.compound.docTitleType::add_ref(), doxmlparser.compound.docSummaryType::add_ref(), doxmlparser.compound.docParaType::add_ref(), doxmlparser.compound.docMarkupType::add_ref(), doxmlparser.compound.docURLLink::add_ref(), doxmlparser.compound.docRefTextType::add_ref(), doxmlparser.compound.docCaptionType::add_ref(), doxmlparser.compound.docHeadingType::add_ref(), doxmlparser.compound.docImageType::add_ref(), doxmlparser.compound.docDotMscType::add_ref(), doxmlparser.compound.docImageFileType::add_ref(), doxmlparser.compound.docPlantumlType::add_ref(), doxmlparser.compound.docTocItemType::add_ref(), convertMapFile(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docParamName::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.highlightType::exportChildren(), doxmlparser.compound.linkedTextType::get_ref(), doxmlparser.compound.highlightType::get_ref(), doxmlparser.compound.docTitleType::get_ref(), doxmlparser.compound.docSummaryType::get_ref(), doxmlparser.compound.docParaType::get_ref(), doxmlparser.compound.docMarkupType::get_ref(), doxmlparser.compound.docURLLink::get_ref(), doxmlparser.compound.docRefTextType::get_ref(), doxmlparser.compound.docCaptionType::get_ref(), doxmlparser.compound.docHeadingType::get_ref(), doxmlparser.compound.docImageType::get_ref(), doxmlparser.compound.docDotMscType::get_ref(), doxmlparser.compound.docImageFileType::get_ref(), doxmlparser.compound.docPlantumlType::get_ref(), doxmlparser.compound.docTocItemType::get_ref(), doxmlparser.compound.docParamType::get_ref(), doxmlparser.compound.docParamName::get_ref(), doxmlparser.compound.linkedTextType::hasContent_(), doxmlparser.compound.highlightType::hasContent_(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docParamType::hasContent_(), doxmlparser.compound.docParamName::hasContent_(), doxmlparser.compound.linkedTextType::insert_ref_at(), doxmlparser.compound.highlightType::insert_ref_at(), doxmlparser.compound.docTitleType::insert_ref_at(), doxmlparser.compound.docSummaryType::insert_ref_at(), doxmlparser.compound.docParaType::insert_ref_at(), doxmlparser.compound.docMarkupType::insert_ref_at(), doxmlparser.compound.docURLLink::insert_ref_at(), doxmlparser.compound.docRefTextType::insert_ref_at(), doxmlparser.compound.docCaptionType::insert_ref_at(), doxmlparser.compound.docHeadingType::insert_ref_at(), doxmlparser.compound.docImageType::insert_ref_at(), doxmlparser.compound.docDotMscType::insert_ref_at(), doxmlparser.compound.docImageFileType::insert_ref_at(), doxmlparser.compound.docPlantumlType::insert_ref_at(), doxmlparser.compound.docTocItemType::insert_ref_at(), HtmlDocVisitor::operator()(), XmlDocVisitor::operator()(), LatexDocVisitor::operator()(), PrintDocVisitor::operator()(), RTFDocVisitor::operator()(), doxmlparser.compound.linkedTextType::replace_ref_at(), doxmlparser.compound.highlightType::replace_ref_at(), doxmlparser.compound.docTitleType::replace_ref_at(), doxmlparser.compound.docSummaryType::replace_ref_at(), doxmlparser.compound.docParaType::replace_ref_at(), doxmlparser.compound.docMarkupType::replace_ref_at(), doxmlparser.compound.docURLLink::replace_ref_at(), doxmlparser.compound.docRefTextType::replace_ref_at(), doxmlparser.compound.docCaptionType::replace_ref_at(), doxmlparser.compound.docHeadingType::replace_ref_at(), doxmlparser.compound.docImageType::replace_ref_at(), doxmlparser.compound.docDotMscType::replace_ref_at(), doxmlparser.compound.docImageFileType::replace_ref_at(), doxmlparser.compound.docPlantumlType::replace_ref_at(), doxmlparser.compound.docTocItemType::replace_ref_at(), replaceRef(), doxmlparser.compound.linkedTextType::set_ref(), doxmlparser.compound.highlightType::set_ref(), doxmlparser.compound.docTitleType::set_ref(), doxmlparser.compound.docSummaryType::set_ref(), doxmlparser.compound.docParaType::set_ref(), doxmlparser.compound.docMarkupType::set_ref(), doxmlparser.compound.docURLLink::set_ref(), doxmlparser.compound.docRefTextType::set_ref(), doxmlparser.compound.docCaptionType::set_ref(), doxmlparser.compound.docHeadingType::set_ref(), doxmlparser.compound.docImageType::set_ref(), doxmlparser.compound.docDotMscType::set_ref(), doxmlparser.compound.docImageFileType::set_ref(), doxmlparser.compound.docPlantumlType::set_ref(), doxmlparser.compound.docTocItemType::set_ref(), doxmlparser.compound.docParamType::set_ref(), and doxmlparser.compound.docParamName::set_ref().
ref() [2/2]
QCString DocRef::ref () const [inline]
Definition at line 739 of file docnode.h.
{ return m_ref; }
References m_ref.
Referenced by doxmlparser.compound.highlightType::__init__(), doxmlparser.compound.docParamName::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.linkedTextType::__init__(), doxmlparser.compound.docParamType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.linkedTextType::add_ref(), doxmlparser.compound.highlightType::add_ref(), doxmlparser.compound.docTitleType::add_ref(), doxmlparser.compound.docSummaryType::add_ref(), doxmlparser.compound.docParaType::add_ref(), doxmlparser.compound.docMarkupType::add_ref(), doxmlparser.compound.docURLLink::add_ref(), doxmlparser.compound.docRefTextType::add_ref(), doxmlparser.compound.docCaptionType::add_ref(), doxmlparser.compound.docHeadingType::add_ref(), doxmlparser.compound.docImageType::add_ref(), doxmlparser.compound.docDotMscType::add_ref(), doxmlparser.compound.docImageFileType::add_ref(), doxmlparser.compound.docPlantumlType::add_ref(), doxmlparser.compound.docTocItemType::add_ref(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docParamName::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.highlightType::exportChildren(), doxmlparser.compound.linkedTextType::get_ref(), doxmlparser.compound.highlightType::get_ref(), doxmlparser.compound.docTitleType::get_ref(), doxmlparser.compound.docSummaryType::get_ref(), doxmlparser.compound.docParaType::get_ref(), doxmlparser.compound.docMarkupType::get_ref(), doxmlparser.compound.docURLLink::get_ref(), doxmlparser.compound.docRefTextType::get_ref(), doxmlparser.compound.docCaptionType::get_ref(), doxmlparser.compound.docHeadingType::get_ref(), doxmlparser.compound.docImageType::get_ref(), doxmlparser.compound.docDotMscType::get_ref(), doxmlparser.compound.docImageFileType::get_ref(), doxmlparser.compound.docPlantumlType::get_ref(), doxmlparser.compound.docTocItemType::get_ref(), doxmlparser.compound.docParamType::get_ref(), doxmlparser.compound.docParamName::get_ref(), doxmlparser.compound.linkedTextType::hasContent_(), doxmlparser.compound.highlightType::hasContent_(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docParamType::hasContent_(), doxmlparser.compound.docParamName::hasContent_(), doxmlparser.compound.linkedTextType::insert_ref_at(), doxmlparser.compound.highlightType::insert_ref_at(), doxmlparser.compound.docTitleType::insert_ref_at(), doxmlparser.compound.docSummaryType::insert_ref_at(), doxmlparser.compound.docParaType::insert_ref_at(), doxmlparser.compound.docMarkupType::insert_ref_at(), doxmlparser.compound.docURLLink::insert_ref_at(), doxmlparser.compound.docRefTextType::insert_ref_at(), doxmlparser.compound.docCaptionType::insert_ref_at(), doxmlparser.compound.docHeadingType::insert_ref_at(), doxmlparser.compound.docImageType::insert_ref_at(), doxmlparser.compound.docDotMscType::insert_ref_at(), doxmlparser.compound.docImageFileType::insert_ref_at(), doxmlparser.compound.docPlantumlType::insert_ref_at(), doxmlparser.compound.docTocItemType::insert_ref_at(), doxmlparser.compound.linkedTextType::replace_ref_at(), doxmlparser.compound.highlightType::replace_ref_at(), doxmlparser.compound.docTitleType::replace_ref_at(), doxmlparser.compound.docSummaryType::replace_ref_at(), doxmlparser.compound.docParaType::replace_ref_at(), doxmlparser.compound.docMarkupType::replace_ref_at(), doxmlparser.compound.docURLLink::replace_ref_at(), doxmlparser.compound.docRefTextType::replace_ref_at(), doxmlparser.compound.docCaptionType::replace_ref_at(), doxmlparser.compound.docHeadingType::replace_ref_at(), doxmlparser.compound.docImageType::replace_ref_at(), doxmlparser.compound.docDotMscType::replace_ref_at(), doxmlparser.compound.docImageFileType::replace_ref_at(), doxmlparser.compound.docPlantumlType::replace_ref_at(), doxmlparser.compound.docTocItemType::replace_ref_at(), doxmlparser.compound.linkedTextType::set_ref(), doxmlparser.compound.highlightType::set_ref(), doxmlparser.compound.docTitleType::set_ref(), doxmlparser.compound.docSummaryType::set_ref(), doxmlparser.compound.docParaType::set_ref(), doxmlparser.compound.docMarkupType::set_ref(), doxmlparser.compound.docURLLink::set_ref(), doxmlparser.compound.docRefTextType::set_ref(), doxmlparser.compound.docCaptionType::set_ref(), doxmlparser.compound.docHeadingType::set_ref(), doxmlparser.compound.docImageType::set_ref(), doxmlparser.compound.docDotMscType::set_ref(), doxmlparser.compound.docImageFileType::set_ref(), doxmlparser.compound.docPlantumlType::set_ref(), doxmlparser.compound.docTocItemType::set_ref(), doxmlparser.compound.docParamType::set_ref(), and doxmlparser.compound.docParamName::set_ref().
refToAnchor() [1/2]
bool DocRef::refToAnchor () const [inline]
Definition at line 743 of file docnode.h.
{ return m_refType==Anchor; }
References DocNode::Anchor, and m_refType.
Referenced by PrintDocVisitor::operator()().
refToAnchor() [2/2]
bool DocRef::refToAnchor () const [inline]
Definition at line 743 of file docnode.h.
{ return m_refType==Anchor; }
References DocNode::Anchor, and m_refType.
refToSection() [1/2]
bool DocRef::refToSection () const [inline]
Definition at line 744 of file docnode.h.
{ return m_refType==Section; }
References m_refType, and DocNode::Section.
Referenced by PrintDocVisitor::operator()().
refToSection() [2/2]
bool DocRef::refToSection () const [inline]
Definition at line 744 of file docnode.h.
{ return m_refType==Section; }
References m_refType, and DocNode::Section.
refToTable() [1/2]
bool DocRef::refToTable () const [inline]
Definition at line 745 of file docnode.h.
{ return m_refType==Table; }
References m_refType, and DocNode::Table.
Referenced by LatexDocVisitor::operator()(), and PrintDocVisitor::operator()().
refToTable() [2/2]
bool DocRef::refToTable () const [inline]
Definition at line 745 of file docnode.h.
{ return m_refType==Table; }
References m_refType, and DocNode::Table.
relPath() [1/2]
QCString DocRef::relPath () const [inline]
Definition at line 738 of file docnode.h.
{ return m_relPath; }
References m_relPath.
Referenced by HtmlDocVisitor::operator()().
relPath() [2/2]
QCString DocRef::relPath () const [inline]
Definition at line 738 of file docnode.h.
{ return m_relPath; }
References m_relPath.
targetTitle() [1/2]
QCString DocRef::targetTitle () const [inline]
Definition at line 741 of file docnode.h.
{ return m_text; }
References m_text.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), PerlModDocVisitor::operator()(), XmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), PrintDocVisitor::operator()(), and RTFDocVisitor::operator()().
targetTitle() [2/2]
QCString DocRef::targetTitle () const [inline]
Definition at line 741 of file docnode.h.
{ return m_text; }
References m_text.
Member Data Documentation
m_anchor
QCString DocRef::m_anchor [private]
Definition at line 754 of file docnode.h.
Referenced by anchor(), and DocRef().
m_file
QCString DocRef::m_file [private]
Definition at line 751 of file docnode.h.
Referenced by DocRef(), and file().
m_isSubPage
bool DocRef::m_isSubPage = false [private]
Definition at line 750 of file docnode.h.
Referenced by DocRef(), and isSubPage().
m_ref
QCString DocRef::m_ref [private]
Definition at line 753 of file docnode.h.
Referenced by DocRef(), and ref().
m_refType
RefType DocRef::m_refType = Unknown [private]
Definition at line 749 of file docnode.h.
Referenced by DocRef(), refToAnchor(), refToSection(), and refToTable().
m_relPath
QCString DocRef::m_relPath [private]
Definition at line 752 of file docnode.h.
Referenced by DocRef(), and relPath().
m_text
QCString DocRef::m_text [private]
Definition at line 755 of file docnode.h.
Referenced by DocRef(), parse(), and targetTitle().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docnode.h
doxygen/src/docnode.h
doxygen/build/doxygen/src/docnode.cpp
doxygen/src/docnode.cpp