UsedDir Class Reference
#include <dirdef.h>
Public Member Functions
UsedDir (const DirDef *dir)
virtual ~UsedDir ()
void addFileDep (const FileDef *srcFd, const FileDef *dstFd, bool srcDirect, bool dstDirect)
FilePair * findFilePair (const QCString &name)
const FilePairLinkedMap & filePairs () const
const DirDef * dir () const
bool hasDirectDeps () const
bool hasDirectSrcDeps () const
bool hasDirectDstDeps () const
void sort ()
UsedDir (const DirDef *dir)
virtual ~UsedDir ()
void addFileDep (const FileDef *srcFd, const FileDef *dstFd, bool srcDirect, bool dstDirect)
FilePair * findFilePair (const QCString &name)
const FilePairLinkedMap & filePairs () const
const DirDef * dir () const
bool hasDirectDeps () const
bool hasDirectSrcDeps () const
bool hasDirectDstDeps () const
void sort ()
Private Attributes
const DirDef * m_dir
FilePairLinkedMap m_filePairs
bool m_hasDirectDeps = false
bool m_hasDirectSrcDeps = false
bool m_hasDirectDstDeps = false
Detailed Description
Usage information of a directory.
Definition at line 63 of file dirdef.h.
Constructor & Destructor Documentation
UsedDir() [1/2]
UsedDir::UsedDir (const DirDef * dir)
Definition at line 761 of file dirdef.cpp.
                                  :
   m_dir(dir)
{
}
 UsedDir() [1/2]
UsedDir::~UsedDir () [virtual]
Definition at line 766 of file dirdef.cpp.
{
}
UsedDir() [2/2]
UsedDir::UsedDir (const DirDef * dir)
 UsedDir() [2/2]
virtual UsedDir::~UsedDir () [virtual]
Member Function Documentation
addFileDep() [1/2]
void UsedDir::addFileDep (const FileDef * srcFd, const FileDef * dstFd, bool srcDirect, bool dstDirect)
Take up dependency between files.
Parameters
 in srcFd dependent file which depends on dstFd
 in dstFd dependee file on which srcFd depends on
 in srcDirect true iff the source dependency was the direct (not inherited from a sub dir)
 in dstDirect true iff the destination dependency was direct (not inherited from a sub dir)
Definition at line 770 of file dirdef.cpp.
{
  m_filePairs.add(FilePair::key(srcFd,dstFd),std::make_unique<FilePair>(srcFd,dstFd));
  m_hasDirectDeps = m_hasDirectDeps || (srcDirect && dstDirect);
  m_hasDirectSrcDeps = m_hasDirectSrcDeps || srcDirect;
  m_hasDirectDstDeps = m_hasDirectDstDeps || dstDirect;
}
References LinkedMap< T, Hash, KeyEqual, Map >::add(), FilePair::key(), m_filePairs, m_hasDirectDeps, m_hasDirectDstDeps, and m_hasDirectSrcDeps.
Referenced by DirDefImpl::addUsesDependency().
addFileDep() [2/2]
void UsedDir::addFileDep (const FileDef * srcFd, const FileDef * dstFd, bool srcDirect, bool dstDirect)
Take up dependency between files.
Parameters
 in srcFd dependent file which depends on dstFd
 in dstFd dependee file on which srcFd depends on
 in srcDirect true iff the source dependency was the direct (not inherited from a sub dir)
 in dstDirect true iff the destination dependency was direct (not inherited from a sub dir)
dir() [1/2]
const DirDef * UsedDir::dir () const [inline]
Definition at line 79 of file dirdef.h.
{ return m_dir; }
References m_dir.
Referenced by DirRelation::writeDocumentation().
dir() [2/2]
const DirDef * UsedDir::dir () const [inline]
Definition at line 79 of file dirdef.h.
{ return m_dir; }
References m_dir.
filePairs() [1/2]
const FilePairLinkedMap & UsedDir::filePairs () const [inline]
Definition at line 78 of file dirdef.h.
{ return m_filePairs; }
References m_filePairs.
Referenced by DirRelation::writeDocumentation().
filePairs() [2/2]
const FilePairLinkedMap & UsedDir::filePairs () const [inline]
Definition at line 78 of file dirdef.h.
{ return m_filePairs; }
References m_filePairs.
findFilePair() [1/2]
FilePair * UsedDir::findFilePair (const QCString & name)
Definition at line 791 of file dirdef.cpp.
{
  return m_filePairs.find(name);
}
References LinkedMap< T, Hash, KeyEqual, Map >::find(), m_filePairs, and setup::name.
Referenced by DirDefImpl::addUsesDependency().
findFilePair() [2/2]
FilePair * UsedDir::findFilePair (const QCString & name)
hasDirectDeps() [1/2]
bool UsedDir::hasDirectDeps () const [inline]
Returns true iff any of the dependencies between source and destination files are direct (i.e. not `inherited` from sub directories)
Definition at line 84 of file dirdef.h.
{ return m_hasDirectDeps; }
References m_hasDirectDeps.
hasDirectDeps() [2/2]
bool UsedDir::hasDirectDeps () const [inline]
Returns true iff any of the dependencies between source and destination files are direct (i.e. not `inherited` from sub directories)
Definition at line 84 of file dirdef.h.
{ return m_hasDirectDeps; }
References m_hasDirectDeps.
hasDirectDstDeps() [1/2]
bool UsedDir::hasDirectDstDeps () const [inline]
Returns true iff any of the dependencies from the source file to the destination file are directly targeting a file in the destination directory (i.e. not inherited via sub directories)
Definition at line 94 of file dirdef.h.
{ return m_hasDirectDstDeps; }
References m_hasDirectDstDeps.
hasDirectDstDeps() [2/2]
bool UsedDir::hasDirectDstDeps () const [inline]
Returns true iff any of the dependencies from the source file to the destination file are directly targeting a file in the destination directory (i.e. not inherited via sub directories)
Definition at line 94 of file dirdef.h.
{ return m_hasDirectDstDeps; }
References m_hasDirectDstDeps.
hasDirectSrcDeps() [1/2]
bool UsedDir::hasDirectSrcDeps () const [inline]
Returns true iff any of the dependencies from the source file to the destination file are directly coming from a file in the source directory (i.e. not inherited via sub directories)
Definition at line 89 of file dirdef.h.
{ return m_hasDirectSrcDeps; }
References m_hasDirectSrcDeps.
hasDirectSrcDeps() [2/2]
bool UsedDir::hasDirectSrcDeps () const [inline]
Returns true iff any of the dependencies from the source file to the destination file are directly coming from a file in the source directory (i.e. not inherited via sub directories)
Definition at line 89 of file dirdef.h.
{ return m_hasDirectSrcDeps; }
References m_hasDirectSrcDeps.
sort() [1/2]
void UsedDir::sort ()
Definition at line 778 of file dirdef.cpp.
{
  std::sort(m_filePairs.begin(),
            m_filePairs.end(),
            [](const auto &left,const auto &right)
            {
              int orderHi = qstricmp(left->source()->name(),right->source()->name());
              if (orderHi!=0) return orderHi<0;
              int orderLo = qstricmp(left->destination()->name(),right->destination()->name());
              return orderLo<0;
            });
}
References LinkedMap< T, Hash, KeyEqual, Map >::begin(), LinkedMap< T, Hash, KeyEqual, Map >::end(), and m_filePairs.
Referenced by translator.TrManager::generateTranslatorReport().
sort() [2/2]
void UsedDir::sort ()
Referenced by translator.TrManager::generateTranslatorReport().
Member Data Documentation
m_dir
const DirDef * UsedDir::m_dir [private]
Definition at line 99 of file dirdef.h.
Referenced by dir().
m_filePairs
FilePairLinkedMap UsedDir::m_filePairs [private]
Definition at line 100 of file dirdef.h.
Referenced by addFileDep(), filePairs(), findFilePair(), and sort().
m_hasDirectDeps
bool UsedDir::m_hasDirectDeps = false [private]
Definition at line 102 of file dirdef.h.
Referenced by addFileDep(), and hasDirectDeps().
m_hasDirectDstDeps
bool UsedDir::m_hasDirectDstDeps = false [private]
Definition at line 104 of file dirdef.h.
Referenced by addFileDep(), and hasDirectDstDeps().
m_hasDirectSrcDeps
bool UsedDir::m_hasDirectSrcDeps = false [private]
Definition at line 103 of file dirdef.h.
Referenced by addFileDep(), and hasDirectSrcDeps().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/dirdef.h
doxygen/src/dirdef.h
doxygen/build/doxygen/src/dirdef.cpp
doxygen/src/dirdef.cpp