NamespaceContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const QCString &name) const
virtual StringVector fields () const
NamespaceContext (const NamespaceDef *)
virtual ~NamespaceContext ()
virtual TemplateVariant get (const QCString &name) const
virtual StringVector fields () const
NamespaceContext (const NamespaceDef *)
virtual ~NamespaceContext ()
Static Public Member Functions
static TemplateStructIntfPtr alloc (const NamespaceDef *nd)
static TemplateStructIntfPtr alloc (const NamespaceDef *nd)
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Definition at line 237 of file context.h.
Constructor & Destructor Documentation
NamespaceContext() [1/2]
NamespaceContext::NamespaceContext (const NamespaceDef * nd)
Definition at line 2718 of file context.cpp.
                                                         : p(std::make_unique<Private>(nd))
{
}
 NamespaceContext() [1/2]
NamespaceContext::~NamespaceContext () [virtual]
Definition at line 2722 of file context.cpp.
{
}
NamespaceContext() [2/2]
NamespaceContext::NamespaceContext (const NamespaceDef *)
 NamespaceContext() [2/2]
virtual NamespaceContext::~NamespaceContext () [virtual]
Member Function Documentation
alloc() [1/2]
static TemplateStructIntfPtr NamespaceContext::alloc (const NamespaceDef * nd) [inline], [static]
Definition at line 240 of file context.h.
    { return std::static_pointer_cast<TemplateStructIntf>(std::make_shared<NamespaceContext>(nd)); }
Referenced by NamespaceListContext::Private::addNamespaces(), NamespaceContext::Private::createConstantgroups(), FileContext::Private::createConstantgroups(), ModuleContext::Private::createConstantgroups(), NestingNodeContext::Private::createNamespace(), MemberContext::Private::createNamespaceDef(), NamespaceContext::Private::createNamespaces(), FileContext::Private::createNamespaces(), and ModuleContext::Private::createNamespaces().
alloc() [2/2]
static TemplateStructIntfPtr NamespaceContext::alloc (const NamespaceDef * nd) [inline], [static]
Definition at line 240 of file context.h.
    { return std::static_pointer_cast<TemplateStructIntf>(std::make_shared<NamespaceContext>(nd)); }
fields() [1/2]
StringVector NamespaceContext::fields () const [virtual]
Return the list of fields.
Implements TemplateStructIntf.
Definition at line 2731 of file context.cpp.
{
  return p->fields();
}
References p.
fields() [2/2]
virtual StringVector NamespaceContext::fields () const [virtual]
Return the list of fields.
Implements TemplateStructIntf.
get() [1/2]
TemplateVariant NamespaceContext::get (const QCString & name) const [virtual]
Gets the value for a field name.
Parameters
 in name The name of the field.
Implements TemplateStructIntf.
Definition at line 2726 of file context.cpp.
{
  return p->get(n);
}
References n, and p.
get() [2/2]
virtual TemplateVariant NamespaceContext::get (const QCString & name) const [virtual]
Gets the value for a field name.
Parameters
 in name The name of the field.
Implements TemplateStructIntf.
Member Data Documentation
p
std::unique_ptr< Private > NamespaceContext::p [private]
Definition at line 252 of file context.h.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.h
doxygen/src/context.h
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp