TranslatorBrazilian Class Reference
#include <translator_br.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
virtual QCString trDesignUnitHierarchy ()
virtual QCString trDesignUnitList ()
virtual QCString trDesignUnitMembers ()
virtual QCString trDesignUnitListDescription ()
virtual QCString trDesignUnitIndex ()
virtual QCString trDesignUnits ()
virtual QCString trFunctionAndProc ()
virtual QCString trVhdlType (uint64 type, bool single)
virtual QCString trCustomReference (const QCString &name)
virtual QCString trConstants ()
virtual QCString trConstantDocumentation ()
virtual QCString trSequences ()
virtual QCString trSequenceDocumentation ()
virtual QCString trDictionaries ()
virtual QCString trDictionaryDocumentation ()
virtual QCString trSliceInterfaces ()
virtual QCString trInterfaceIndex ()
virtual QCString trInterfaceList ()
virtual QCString trInterfaceListDescription ()
virtual QCString trInterfaceHierarchy ()
virtual QCString trInterfaceHierarchyDescription ()
virtual QCString trInterfaceDocumentation ()
virtual QCString trStructs ()
virtual QCString trStructIndex ()
virtual QCString trStructList ()
virtual QCString trStructListDescription ()
virtual QCString trStructDocumentation ()
virtual QCString trExceptionIndex ()
virtual QCString trExceptionList ()
virtual QCString trExceptionListDescription ()
virtual QCString trExceptionHierarchy ()
virtual QCString trExceptionHierarchyDescription ()
virtual QCString trExceptionDocumentation ()
virtual QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal)
virtual QCString trOperations ()
virtual QCString trOperationDocumentation ()
virtual QCString trDataMembers ()
virtual QCString trDataMemberDocumentation ()
virtual QCString trDesignUnitDocumentation ()
virtual QCString trConcept (bool first_capital, bool singular)
virtual QCString trConceptReference (const QCString &conceptName)
virtual QCString trConceptList ()
virtual QCString trConceptIndex ()
virtual QCString trConceptDocumentation ()
virtual QCString trConceptListDescription (bool extractAll)
virtual QCString trConceptDefinition ()
virtual QCString trPackageList ()
virtual QCString trFlowchart ()
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
virtual QCString trDesignUnitHierarchy ()
virtual QCString trDesignUnitList ()
virtual QCString trDesignUnitMembers ()
virtual QCString trDesignUnitListDescription ()
virtual QCString trDesignUnitIndex ()
virtual QCString trDesignUnits ()
virtual QCString trFunctionAndProc ()
virtual QCString trVhdlType (uint64 type, bool single)
virtual QCString trCustomReference (const QCString &name)
virtual QCString trConstants ()
virtual QCString trConstantDocumentation ()
virtual QCString trSequences ()
virtual QCString trSequenceDocumentation ()
virtual QCString trDictionaries ()
virtual QCString trDictionaryDocumentation ()
virtual QCString trSliceInterfaces ()
virtual QCString trInterfaceIndex ()
virtual QCString trInterfaceList ()
virtual QCString trInterfaceListDescription ()
virtual QCString trInterfaceHierarchy ()
virtual QCString trInterfaceHierarchyDescription ()
virtual QCString trInterfaceDocumentation ()
virtual QCString trStructs ()
virtual QCString trStructIndex ()
virtual QCString trStructList ()
virtual QCString trStructListDescription ()
virtual QCString trStructDocumentation ()
virtual QCString trExceptionIndex ()
virtual QCString trExceptionList ()
virtual QCString trExceptionListDescription ()
virtual QCString trExceptionHierarchy ()
virtual QCString trExceptionHierarchyDescription ()
virtual QCString trExceptionDocumentation ()
virtual QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal)
virtual QCString trOperations ()
virtual QCString trOperationDocumentation ()
virtual QCString trDataMembers ()
virtual QCString trDataMemberDocumentation ()
virtual QCString trDesignUnitDocumentation ()
virtual QCString trConcept (bool first_capital, bool singular)
virtual QCString trConceptReference (const QCString &conceptName)
virtual QCString trConceptList ()
virtual QCString trConceptIndex ()
virtual QCString trConceptDocumentation ()
virtual QCString trConceptListDescription (bool extractAll)
virtual QCString trConceptDefinition ()
virtual QCString trPackageList ()
virtual QCString trFlowchart ()
Detailed Description
Definition at line 61 of file translator_br.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorBrazilian::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 101 of file translator_br.h.
    {
      return "0x416 Portuguese(Brazil)";
    }
getLanguageString() [2/2]
virtual QCString TranslatorBrazilian::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 101 of file translator_br.h.
    {
      return "0x416 Portuguese(Brazil)";
    }
idLanguage() [1/2]
virtual QCString TranslatorBrazilian::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 73 of file translator_br.h.
    {
      return "brazilian";
    }
idLanguage() [2/2]
virtual QCString TranslatorBrazilian::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 73 of file translator_br.h.
    {
      return "brazilian";
    }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorBrazilian::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 92 of file translator_br.h.
    {
      return "\\usepackage[brazil]{babel}";
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorBrazilian::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 92 of file translator_br.h.
    {
      return "\\usepackage[brazil]{babel}";
    }
trAdditionalInheritedMembers() [1/2]
virtual QCString TranslatorBrazilian::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1987 of file translator_br.h.
    { return "Outros membros herdados"; }
trAdditionalInheritedMembers() [2/2]
virtual QCString TranslatorBrazilian::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1987 of file translator_br.h.
    { return "Outros membros herdados"; }
trAll() [1/2]
virtual QCString TranslatorBrazilian::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1478 of file translator_br.h.
    {
      return "Todos";
    }
trAll() [2/2]
virtual QCString TranslatorBrazilian::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1478 of file translator_br.h.
    {
      return "Todos";
    }
trAndMore() [1/2]
virtual QCString TranslatorBrazilian::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1959 of file translator_br.h.
    { return "e "+number+" mais..."; }
trAndMore() [2/2]
virtual QCString TranslatorBrazilian::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1959 of file translator_br.h.
    { return "e "+number+" mais..."; }
trAttention() [1/2]
virtual QCString TranslatorBrazilian::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 1035 of file translator_br.h.
    {
      return "Ateno";
    }
trAttention() [2/2]
virtual QCString TranslatorBrazilian::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 1035 of file translator_br.h.
    {
      return "Ateno";
    }
trAuthor() [1/2]
virtual QCString TranslatorBrazilian::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1349 of file translator_br.h.
    {
      QCString result((first_capital ? "Autor" : "autor"));
      if (!singular) result+="es";
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorBrazilian::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1349 of file translator_br.h.
    {
      QCString result((first_capital ? "Autor" : "autor"));
      if (!singular) result+="es";
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorBrazilian::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1203 of file translator_br.h.
    {
      return "Bug";
    }
trBug() [2/2]
virtual QCString TranslatorBrazilian::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1203 of file translator_br.h.
    {
      return "Bug";
    }
trBugList() [1/2]
virtual QCString TranslatorBrazilian::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1208 of file translator_br.h.
    {
      return "Lista de Bugs";
    }
trBugList() [2/2]
virtual QCString TranslatorBrazilian::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1208 of file translator_br.h.
    {
      return "Lista de Bugs";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorBrazilian::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1603 of file translator_br.h.
    {
      return "Esse o diagrama das funes que utilizam essa funo:";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorBrazilian::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1603 of file translator_br.h.
    {
      return "Esse o diagrama das funes que utilizam essa funo:";
    }
trCallGraph() [1/2]
virtual QCString TranslatorBrazilian::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1483 of file translator_br.h.
    {
      return "Este o diagrama das funes utilizadas por essa funo:";
    }
trCallGraph() [2/2]
virtual QCString TranslatorBrazilian::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1483 of file translator_br.h.
    {
      return "Este o diagrama das funes utilizadas por essa funo:";
    }
trCiteReferences() [1/2]
virtual QCString TranslatorBrazilian::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1931 of file translator_br.h.
    { return "Referncias Bibliogrficas"; }
trCiteReferences() [2/2]
virtual QCString TranslatorBrazilian::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1931 of file translator_br.h.
    { return "Referncias Bibliogrficas"; }
trClass() [1/2]
virtual QCString TranslatorBrazilian::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1266 of file translator_br.h.
    {
      QCString result((first_capital ? "Classe" : "classe"));
      if (!singular) result+="s";
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorBrazilian::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1266 of file translator_br.h.
    {
      QCString result((first_capital ? "Classe" : "classe"));
      if (!singular) result+="s";
      return result;
    }
trClassDiagram() [1/2]
virtual QCString TranslatorBrazilian::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 550 of file translator_br.h.
    {
      return "Diagrama de hierarquia para "+clName+":";
    }
trClassDiagram() [2/2]
virtual QCString TranslatorBrazilian::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 550 of file translator_br.h.
    {
      return "Diagrama de hierarquia para "+clName+":";
    }
trClassDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 425 of file translator_br.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estruturas";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Classes";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 425 of file translator_br.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estruturas";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Classes";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorBrazilian::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1166 of file translator_br.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estruturas de Dados";
      }
      else
      {
        return "Classes";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorBrazilian::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1166 of file translator_br.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estruturas de Dados";
      }
      else
      {
        return "Classes";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorBrazilian::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 205 of file translator_br.h.
    { return "Hierarquia de Classes"; }
trClassHierarchy() [2/2]
virtual QCString TranslatorBrazilian::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 205 of file translator_br.h.
    { return "Hierarquia de Classes"; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorBrazilian::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 264 of file translator_br.h.
    { return "Esta lista de hierarquias est parcialmente ordenada (ordem alfabtica):"; }
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorBrazilian::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 264 of file translator_br.h.
    { return "Esta lista de hierarquias est parcialmente ordenada (ordem alfabtica):"; }
trClassMethods() [1/2]
virtual QCString TranslatorBrazilian::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 2025 of file translator_br.h.
    {
      return "Mtodos da classe";
    }
trClassMethods() [2/2]
virtual QCString TranslatorBrazilian::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 2025 of file translator_br.h.
    {
      return "Mtodos da classe";
    }
trCode() [1/2]
virtual QCString TranslatorBrazilian::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 935 of file translator_br.h.
    {
      return "cdigo";
    }
trCode() [2/2]
virtual QCString TranslatorBrazilian::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 935 of file translator_br.h.
    {
      return "cdigo";
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorBrazilian::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 890 of file translator_br.h.
    {
      return "Diagrama de colaborao para "+clName+":";
    }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorBrazilian::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 890 of file translator_br.h.
    {
      return "Diagrama de colaborao para "+clName+":";
    }
trCompoundIndex() [1/2]
virtual QCString TranslatorBrazilian::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 398 of file translator_br.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "ndice das Estruturas de Dados";
      }
      else
      {
        return "ndice dos Componentes";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorBrazilian::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 398 of file translator_br.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "ndice das Estruturas de Dados";
      }
      else
      {
        return "ndice dos Componentes";
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorBrazilian::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1655 of file translator_br.h.
    { return "ndice de Tipos de Dados"; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorBrazilian::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1655 of file translator_br.h.
    { return "ndice de Tipos de Dados"; }
trCompoundList() [1/2]
virtual QCString TranslatorBrazilian::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 209 of file translator_br.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estruturas de Dados";
      }
      else
      {
        return "Lista de Classes";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorBrazilian::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 209 of file translator_br.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estruturas de Dados";
      }
      else
      {
        return "Lista de Classes";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorBrazilian::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 277 of file translator_br.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Aqui esto as estruturas de dados, unies e suas respectivas descries:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Aqui esto as classes e suas respectivas descries:";
      }
      else
      {
        return "Aqui esto as classes, estruturas, unies e interfaces e suas respectivas descries:";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorBrazilian::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 277 of file translator_br.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Aqui esto as estruturas de dados, unies e suas respectivas descries:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Aqui esto as classes e suas respectivas descries:";
      }
      else
      {
        return "Aqui esto as classes, estruturas, unies e interfaces e suas respectivas descries:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorBrazilian::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1632 of file translator_br.h.
    { return "Aqui esto os tipos de dados com descries resumidas:"; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorBrazilian::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1632 of file translator_br.h.
    { return "Aqui esto os tipos de dados com descries resumidas:"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorBrazilian::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1624 of file translator_br.h.
    { return "Lista de Tipos de Dados"; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorBrazilian::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1624 of file translator_br.h.
    { return "Lista de Tipos de Dados"; }
trCompoundMembers() [1/2]
virtual QCString TranslatorBrazilian::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 226 of file translator_br.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Campos de Dados";
      }
      else
      {
        return "Membros de classe";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorBrazilian::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 226 of file translator_br.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Campos de Dados";
      }
      else
      {
        return "Membros de classe";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorBrazilian::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 294 of file translator_br.h.
    {
      QCString result="Esta a lista de ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="todas as estruturas e campos de unies ";
        if (!extractAll)
        {
          result+="documentados";
        }
      }
      else
      {
        result+="todos os membros de classes ";
        if (!extractAll)
        {
          result+="documentados";
        }
      }
      result+=" com referncias para ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="a documentao da estrutura/unio de cada campo:";
        }
        else
        {
          result+="a documentao da classe de cada membro:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="a estrutura/unio a que pertencem:";
        }
        else
        {
          result+="a classe a que pertencem:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorBrazilian::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 294 of file translator_br.h.
    {
      QCString result="Esta a lista de ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="todas as estruturas e campos de unies ";
        if (!extractAll)
        {
          result+="documentados";
        }
      }
      else
      {
        result+="todos os membros de classes ";
        if (!extractAll)
        {
          result+="documentados";
        }
      }
      result+=" com referncias para ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="a documentao da estrutura/unio de cada campo:";
        }
        else
        {
          result+="a documentao da classe de cada membro:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="a estrutura/unio a que pertencem:";
        }
        else
        {
          result+="a classe a que pertencem:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorBrazilian::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1636 of file translator_br.h.
    {
      QCString result="Esta a lista de todos os membros ";
      if (!extractAll) result+="documentados ";
      result+="dos tipos de dados com links para ";
      if (extractAll)
      {
        result+="a documentao dos tipos de dados para cada membro:";
      }
      else
      {
        result+="os tipos de dados a que pertencem:";
      }
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorBrazilian::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1636 of file translator_br.h.
    {
      QCString result="Esta a lista de todos os membros ";
      if (!extractAll) result+="documentados ";
      result+="dos tipos de dados com links para ";
      if (extractAll)
      {
        result+="a documentao dos tipos de dados para cada membro:";
      }
      else
      {
        result+="os tipos de dados a que pertencem:";
      }
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorBrazilian::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1628 of file translator_br.h.
    { return "Campos de Dados"; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorBrazilian::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1628 of file translator_br.h.
    { return "Campos de Dados"; }
trCompoundReference() [1/2]
virtual QCString TranslatorBrazilian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 625 of file translator_br.h.
    {
      QCString result="Referncia";
      if (isTemplate) result+=" do <em>Template</em>";
      if (compType == ClassDef::Protocol)
      {
        result+=" do ";
      }
      else
      {
        result+=" da ";
      }
      switch(compType)
      {
        case ClassDef::Class: result+="Classe "; break;
        case ClassDef::Struct: result+="Estrutura "; break;
        case ClassDef::Union: result+="Unio "; break;
        case ClassDef::Interface: result+="Interface "; break;
        case ClassDef::Protocol: result+="Protocolo "; break;
        case ClassDef::Category: result+="Categoria "; break;
        case ClassDef::Exception: result+="Exceo "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorBrazilian::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 625 of file translator_br.h.
    {
      QCString result="Referncia";
      if (isTemplate) result+=" do <em>Template</em>";
      if (compType == ClassDef::Protocol)
      {
        result+=" do ";
      }
      else
      {
        result+=" da ";
      }
      switch(compType)
      {
        case ClassDef::Class: result+="Classe "; break;
        case ClassDef::Struct: result+="Estrutura "; break;
        case ClassDef::Union: result+="Unio "; break;
        case ClassDef::Interface: result+="Interface "; break;
        case ClassDef::Protocol: result+="Protocolo "; break;
        case ClassDef::Category: result+="Categoria "; break;
        case ClassDef::Exception: result+="Exceo "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorBrazilian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1696 of file translator_br.h.
    {
      QCString result = "Referncia ";
      if (isTemplate) result+="do <em>Template</em> ";
      switch(compType)
      {
        case ClassDef::Class: result+="do Modulo "; break;
        case ClassDef::Struct: result+="do Tipo "; break;
        case ClassDef::Union: result+="da Unio "; break;
        case ClassDef::Interface: result+="da Interface "; break;
        case ClassDef::Protocol: result+="do Protocolo "; break;
        case ClassDef::Category: result+="da Categoria "; break;
        case ClassDef::Exception: result+="da Exceo "; break;
        default: break;
      }
      result += clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorBrazilian::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1696 of file translator_br.h.
    {
      QCString result = "Referncia ";
      if (isTemplate) result+="do <em>Template</em> ";
      switch(compType)
      {
        case ClassDef::Class: result+="do Modulo "; break;
        case ClassDef::Struct: result+="do Tipo "; break;
        case ClassDef::Union: result+="da Unio "; break;
        case ClassDef::Interface: result+="da Interface "; break;
        case ClassDef::Protocol: result+="do Protocolo "; break;
        case ClassDef::Category: result+="da Categoria "; break;
        case ClassDef::Exception: result+="da Exceo "; break;
        default: break;
      }
      result += clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice() [1/2]
virtual QCString TranslatorBrazilian::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) [inline], [virtual]
Implements Translator.
Definition at line 2325 of file translator_br.h.
    {
      QCString result="Referncia ";
      switch(compType)
      {
        case ClassDef::Class: result+="da Classe "; break;
        case ClassDef::Struct: result+="da Estrutura "; break;
        case ClassDef::Union: result+="da Unio "; break;
        case ClassDef::Interface: result+="da Interface "; break;
        case ClassDef::Protocol: result+="do Protocolo "; break;
        case ClassDef::Category: result+="da Categoria "; break;
        case ClassDef::Exception: result+="da Exceo "; break;
        default: break;
      }
      if (isLocal) result+="Local ";
      result+= clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice() [2/2]
virtual QCString TranslatorBrazilian::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) [inline], [virtual]
Implements Translator.
Definition at line 2325 of file translator_br.h.
    {
      QCString result="Referncia ";
      switch(compType)
      {
        case ClassDef::Class: result+="da Classe "; break;
        case ClassDef::Struct: result+="da Estrutura "; break;
        case ClassDef::Union: result+="da Unio "; break;
        case ClassDef::Interface: result+="da Interface "; break;
        case ClassDef::Protocol: result+="do Protocolo "; break;
        case ClassDef::Category: result+="da Categoria "; break;
        case ClassDef::Exception: result+="da Exceo "; break;
        default: break;
      }
      if (isLocal) result+="Local ";
      result+= clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorBrazilian::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 526 of file translator_br.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estruturas de Dados";
      }
      else
      {
        return "Componentes";
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorBrazilian::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 526 of file translator_br.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Estruturas de Dados";
      }
      else
      {
        return "Componentes";
      }
    }
References Config_getBool.
trConcept() [1/2]
virtual QCString TranslatorBrazilian::trConcept (bool first_capital, bool singular) [inline], [virtual]
C++20 concept
Implements Translator.
Definition at line 2375 of file translator_br.h.
    {
        QCString result((first_capital ? "Conceito" : "conceito"));
        if (!singular) result+="s";
        return result;
    }
trConcept() [2/2]
virtual QCString TranslatorBrazilian::trConcept (bool first_capital, bool singular) [inline], [virtual]
C++20 concept
Implements Translator.
Definition at line 2375 of file translator_br.h.
    {
        QCString result((first_capital ? "Conceito" : "conceito"));
        if (!singular) result+="s";
        return result;
    }
trConceptDefinition() [1/2]
virtual QCString TranslatorBrazilian::trConceptDefinition () [inline], [virtual]
used to introduce the definition of the C++20 concept
Implements Translator.
Definition at line 2411 of file translator_br.h.
    {
        return "Definio de conceito";
    }
trConceptDefinition() [2/2]
virtual QCString TranslatorBrazilian::trConceptDefinition () [inline], [virtual]
used to introduce the definition of the C++20 concept
Implements Translator.
Definition at line 2411 of file translator_br.h.
    {
        return "Definio de conceito";
    }
trConceptDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trConceptDocumentation () [inline], [virtual]
used as the title of chapter containing all information about concepts.
Implements Translator.
Definition at line 2398 of file translator_br.h.
    { return "Documentao do Conceito"; }
trConceptDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trConceptDocumentation () [inline], [virtual]
used as the title of chapter containing all information about concepts.
Implements Translator.
Definition at line 2398 of file translator_br.h.
    { return "Documentao do Conceito"; }
trConceptIndex() [1/2]
virtual QCString TranslatorBrazilian::trConceptIndex () [inline], [virtual]
used as the title of chapter containing the index listing all concepts.
Implements Translator.
Definition at line 2394 of file translator_br.h.
    { return "ndice de Conceitos"; }
trConceptIndex() [2/2]
virtual QCString TranslatorBrazilian::trConceptIndex () [inline], [virtual]
used as the title of chapter containing the index listing all concepts.
Implements Translator.
Definition at line 2394 of file translator_br.h.
    { return "ndice de Conceitos"; }
trConceptList() [1/2]
virtual QCString TranslatorBrazilian::trConceptList () [inline], [virtual]
used as the title of page containing all the index of all concepts.
Implements Translator.
Definition at line 2390 of file translator_br.h.
    { return "Lista de Conceitos"; }
trConceptList() [2/2]
virtual QCString TranslatorBrazilian::trConceptList () [inline], [virtual]
used as the title of page containing all the index of all concepts.
Implements Translator.
Definition at line 2390 of file translator_br.h.
    { return "Lista de Conceitos"; }
trConceptListDescription() [1/2]
virtual QCString TranslatorBrazilian::trConceptListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the concept list
Implements Translator.
Definition at line 2402 of file translator_br.h.
    {
        QCString result="Esta a lista de todos os conceitos ";
        if (!extractAll) result+="documentados ";
        result+="com suas respectivas descries:";
        return result;
    }
trConceptListDescription() [2/2]
virtual QCString TranslatorBrazilian::trConceptListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the concept list
Implements Translator.
Definition at line 2402 of file translator_br.h.
    {
        QCString result="Esta a lista de todos os conceitos ";
        if (!extractAll) result+="documentados ";
        result+="com suas respectivas descries:";
        return result;
    }
trConceptReference() [1/2]
virtual QCString TranslatorBrazilian::trConceptReference (const QCString & conceptName) [inline], [virtual]
used as the title of the HTML page of a C++20 concept page
Implements Translator.
Definition at line 2382 of file translator_br.h.
    {
        QCString result= "Referncia do Conceito ";
        result+=conceptName;
        return result;
    }
trConceptReference() [2/2]
virtual QCString TranslatorBrazilian::trConceptReference (const QCString & conceptName) [inline], [virtual]
used as the title of the HTML page of a C++20 concept page
Implements Translator.
Definition at line 2382 of file translator_br.h.
    {
        QCString result= "Referncia do Conceito ";
        result+=conceptName;
        return result;
    }
trConstantDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trConstantDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2233 of file translator_br.h.
    {
        return "Constantes";
    }
trConstantDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trConstantDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2233 of file translator_br.h.
    {
        return "Constantes";
    }
trConstantGroupReference() [1/2]
virtual QCString TranslatorBrazilian::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 2062 of file translator_br.h.
    {
      QCString result = "Referncia do grupo de constantes ";
      result += namespaceName;
      return result;
    }
trConstantGroupReference() [2/2]
virtual QCString TranslatorBrazilian::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 2062 of file translator_br.h.
    {
      QCString result = "Referncia do grupo de constantes ";
      result += namespaceName;
      return result;
    }
trConstantGroups() [1/2]
virtual QCString TranslatorBrazilian::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 2058 of file translator_br.h.
    { return "Grupos de Constantes"; }
trConstantGroups() [2/2]
virtual QCString TranslatorBrazilian::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 2058 of file translator_br.h.
    { return "Grupos de Constantes"; }
trConstants() [1/2]
virtual QCString TranslatorBrazilian::trConstants () [inline], [virtual]
Implements Translator.
Definition at line 2229 of file translator_br.h.
    {
        return "Constantes";
    }
trConstants() [2/2]
virtual QCString TranslatorBrazilian::trConstants () [inline], [virtual]
Implements Translator.
Definition at line 2229 of file translator_br.h.
    {
        return "Constantes";
    }
trConstructorDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 900 of file translator_br.h.
    {
      return "Construtores e Destrutores";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 900 of file translator_br.h.
    {
      return "Construtores e Destrutores";
    }
trCopyright() [1/2]
virtual QCString TranslatorBrazilian::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1935 of file translator_br.h.
    {
      // Note: I will left it as is because "Direitos autorais" may not fit
      // in the text.
      return "Copyright";
    }
trCopyright() [2/2]
virtual QCString TranslatorBrazilian::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1935 of file translator_br.h.
    {
      // Note: I will left it as is because "Direitos autorais" may not fit
      // in the text.
      return "Copyright";
    }
trCustomReference() [1/2]
virtual QCString TranslatorBrazilian::trCustomReference (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 2225 of file translator_br.h.
    { return "Referncia de " + QCString(name); }
References setup::name.
trCustomReference() [2/2]
virtual QCString TranslatorBrazilian::trCustomReference (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 2225 of file translator_br.h.
    { return "Referncia de " + QCString(name); }
References setup::name.
trDataMemberDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trDataMemberDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2355 of file translator_br.h.
    {
        return "Dados Membros";
    }
trDataMemberDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trDataMemberDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2355 of file translator_br.h.
    {
        return "Dados Membros";
    }
trDataMembers() [1/2]
virtual QCString TranslatorBrazilian::trDataMembers () [inline], [virtual]
Implements Translator.
Definition at line 2351 of file translator_br.h.
    {
        return "Dados Membros";
    }
trDataMembers() [2/2]
virtual QCString TranslatorBrazilian::trDataMembers () [inline], [virtual]
Implements Translator.
Definition at line 2351 of file translator_br.h.
    {
        return "Dados Membros";
    }
trDataTypes() [1/2]
virtual QCString TranslatorBrazilian::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1679 of file translator_br.h.
    { return "Tipos de Dados"; }
trDataTypes() [2/2]
virtual QCString TranslatorBrazilian::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1679 of file translator_br.h.
    { return "Tipos de Dados"; }
trDate() [1/2]
virtual QCString TranslatorBrazilian::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 564 of file translator_br.h.
    { return "Data"; }
trDate() [2/2]
virtual QCString TranslatorBrazilian::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 564 of file translator_br.h.
    { return "Data"; }
trDateTime() [1/2]
virtual QCString TranslatorBrazilian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1888 of file translator_br.h.
    {
      static const char *days[] = { "Segunda","Tera","Quarta","Quinta","Sexta","Sbado","Domingo" };
      static const char *months[] = { "Janeiro","Fevereiro","Maro","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro" };
      QCString sdate;
      sdate.sprintf("%s, %d de %s de %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDateTime() [2/2]
virtual QCString TranslatorBrazilian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1888 of file translator_br.h.
    {
      static const char *days[] = { "Segunda","Tera","Quarta","Quinta","Sexta","Sbado","Domingo" };
      static const char *months[] = { "Janeiro","Fevereiro","Maro","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro" };
      QCString sdate;
      sdate.sprintf("%s, %d de %s de %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDayOfWeek() [1/2]
virtual QCString TranslatorBrazilian::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1904 of file translator_br.h.
    {
      static const char *days_short[] = { "seg", "ter", "qua", "qui", "sex", "sb", "dom" };
      static const char *days_full[] = { "segunda-feira", "tera-feira", "quarta-feira", "quinta-feira", "sexta-feira", "sbado", "domingo" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayOfWeek() [2/2]
virtual QCString TranslatorBrazilian::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1904 of file translator_br.h.
    {
      static const char *days_short[] = { "seg", "ter", "qua", "qui", "sex", "sb", "dom" };
      static const char *days_full[] = { "segunda-feira", "tera-feira", "quarta-feira", "quinta-feira", "sexta-feira", "sbado", "domingo" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod() [1/2]
virtual QCString TranslatorBrazilian::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1920 of file translator_br.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorBrazilian::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1920 of file translator_br.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorBrazilian::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 867 of file translator_br.h.
    {
      return "Definio na linha @0 do arquivo @1.";
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorBrazilian::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 867 of file translator_br.h.
    {
      return "Definio na linha @0 do arquivo @1.";
    }
trDefinedIn() [1/2]
virtual QCString TranslatorBrazilian::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 193 of file translator_br.h.
    { return "definido(a) em"; }
trDefinedIn() [2/2]
virtual QCString TranslatorBrazilian::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 193 of file translator_br.h.
    { return "definido(a) em"; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorBrazilian::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 871 of file translator_br.h.
    {
      return "Definio no arquivo @0.";
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorBrazilian::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 871 of file translator_br.h.
    {
      return "Definio no arquivo @0.";
    }
trDefineDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 496 of file translator_br.h.
    { return "Definies e macros"; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 496 of file translator_br.h.
    { return "Definies e macros"; }
trDefines() [1/2]
virtual QCString TranslatorBrazilian::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 460 of file translator_br.h.
    { return "Definies e Macros"; }
trDefines() [2/2]
virtual QCString TranslatorBrazilian::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 460 of file translator_br.h.
    { return "Definies e Macros"; }
trDefineValue() [1/2]
virtual QCString TranslatorBrazilian::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1193 of file translator_br.h.
    {
      return "Valor:";
    }
trDefineValue() [2/2]
virtual QCString TranslatorBrazilian::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1193 of file translator_br.h.
    {
      return "Valor:";
    }
trDeprecated() [1/2]
virtual QCString TranslatorBrazilian::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 880 of file translator_br.h.
    {
      return "Obsoleto(a)";
    }
trDeprecated() [2/2]
virtual QCString TranslatorBrazilian::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 880 of file translator_br.h.
    {
      return "Obsoleto(a)";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorBrazilian::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1406 of file translator_br.h.
    {
      return "Lista de itens obsoletos";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorBrazilian::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1406 of file translator_br.h.
    {
      return "Lista de itens obsoletos";
    }
trDesignUnitDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trDesignUnitDocumentation () [inline], [virtual]
VHDL design unit documentation
Implements Translator.
Definition at line 2365 of file translator_br.h.
    {
        return "Documentao da Unidade de Projeto";
    }
Referenced by trClassDocumentation().
trDesignUnitDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trDesignUnitDocumentation () [inline], [virtual]
VHDL design unit documentation
Implements Translator.
Definition at line 2365 of file translator_br.h.
    {
        return "Documentao da Unidade de Projeto";
    }
trDesignUnitHierarchy() [1/2]
virtual QCString TranslatorBrazilian::trDesignUnitHierarchy () [inline], [virtual]
VHDL design unit hierarchy
Implements Translator.
Definition at line 2116 of file translator_br.h.
    { return "Hierarquia da Unidade de Design"; }
trDesignUnitHierarchy() [2/2]
virtual QCString TranslatorBrazilian::trDesignUnitHierarchy () [inline], [virtual]
VHDL design unit hierarchy
Implements Translator.
Definition at line 2116 of file translator_br.h.
    { return "Hierarquia da Unidade de Design"; }
trDesignUnitIndex() [1/2]
virtual QCString TranslatorBrazilian::trDesignUnitIndex () [inline], [virtual]
VHDL design unit index
Implements Translator.
Definition at line 2131 of file translator_br.h.
    { return "ndice de Unidades de Design"; }
trDesignUnitIndex() [2/2]
virtual QCString TranslatorBrazilian::trDesignUnitIndex () [inline], [virtual]
VHDL design unit index
Implements Translator.
Definition at line 2131 of file translator_br.h.
    { return "ndice de Unidades de Design"; }
trDesignUnitList() [1/2]
virtual QCString TranslatorBrazilian::trDesignUnitList () [inline], [virtual]
VHDL design unit list
Implements Translator.
Definition at line 2119 of file translator_br.h.
    { return "Lista de Unidades de Design"; }
trDesignUnitList() [2/2]
virtual QCString TranslatorBrazilian::trDesignUnitList () [inline], [virtual]
VHDL design unit list
Implements Translator.
Definition at line 2119 of file translator_br.h.
    { return "Lista de Unidades de Design"; }
trDesignUnitListDescription() [1/2]
virtual QCString TranslatorBrazilian::trDesignUnitListDescription () [inline], [virtual]
VHDL design unit list description
Implements Translator.
Definition at line 2125 of file translator_br.h.
    {
        return "Esta uma lista de todos os membros de unidades de design "
                "com ligaes para as entidades s quais pertencem:";
    }
trDesignUnitListDescription() [2/2]
virtual QCString TranslatorBrazilian::trDesignUnitListDescription () [inline], [virtual]
VHDL design unit list description
Implements Translator.
Definition at line 2125 of file translator_br.h.
    {
        return "Esta uma lista de todos os membros de unidades de design "
                "com ligaes para as entidades s quais pertencem:";
    }
trDesignUnitMembers() [1/2]
virtual QCString TranslatorBrazilian::trDesignUnitMembers () [inline], [virtual]
VHDL design unit members
Implements Translator.
Definition at line 2122 of file translator_br.h.
    { return "Membros da Unidade de Design"; }
trDesignUnitMembers() [2/2]
virtual QCString TranslatorBrazilian::trDesignUnitMembers () [inline], [virtual]
VHDL design unit members
Implements Translator.
Definition at line 2122 of file translator_br.h.
    { return "Membros da Unidade de Design"; }
trDesignUnits() [1/2]
virtual QCString TranslatorBrazilian::trDesignUnits () [inline], [virtual]
VHDL design units
Implements Translator.
Definition at line 2134 of file translator_br.h.
    { return "Unidades de Design"; }
trDesignUnits() [2/2]
virtual QCString TranslatorBrazilian::trDesignUnits () [inline], [virtual]
VHDL design units
Implements Translator.
Definition at line 2134 of file translator_br.h.
    { return "Unidades de Design"; }
trDetailedDescription() [1/2]
virtual QCString TranslatorBrazilian::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 117 of file translator_br.h.
    { return "Descrio detalhada"; }
trDetailedDescription() [2/2]
virtual QCString TranslatorBrazilian::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 117 of file translator_br.h.
    { return "Descrio detalhada"; }
trDetailLevel() [1/2]
virtual QCString TranslatorBrazilian::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1951 of file translator_br.h.
    { return "nvel de detalhes"; }
trDetailLevel() [2/2]
virtual QCString TranslatorBrazilian::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1951 of file translator_br.h.
    { return "nvel de detalhes"; }
trDictionaries() [1/2]
virtual QCString TranslatorBrazilian::trDictionaries () [inline], [virtual]
Implements Translator.
Definition at line 2245 of file translator_br.h.
    {
        return "Dicionrios";
    }
trDictionaries() [2/2]
virtual QCString TranslatorBrazilian::trDictionaries () [inline], [virtual]
Implements Translator.
Definition at line 2245 of file translator_br.h.
    {
        return "Dicionrios";
    }
trDictionaryDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trDictionaryDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2249 of file translator_br.h.
    {
        return "Dicionrios";
    }
trDictionaryDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trDictionaryDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2249 of file translator_br.h.
    {
        return "Dicionrios";
    }
trDir() [1/2]
virtual QCString TranslatorBrazilian::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1577 of file translator_br.h.
    {
      QCString result((first_capital ? "Diretrio" : "diretrio"));
      if (!singular) result+="s";
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorBrazilian::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1577 of file translator_br.h.
    {
      QCString result((first_capital ? "Diretrio" : "diretrio"));
      if (!singular) result+="s";
      return result;
    }
trDirDepGraph() [1/2]
virtual QCString TranslatorBrazilian::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1943 of file translator_br.h.
    { return QCString("Grafo de dependncias do diretrio ")+name+":"; }
References setup::name.
trDirDepGraph() [2/2]
virtual QCString TranslatorBrazilian::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1943 of file translator_br.h.
    { return QCString("Grafo de dependncias do diretrio ")+name+":"; }
References setup::name.
trDirDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1555 of file translator_br.h.
    { return "Documentao do Diretrio"; }
trDirDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1555 of file translator_br.h.
    { return "Documentao do Diretrio"; }
trDirectories() [1/2]
virtual QCString TranslatorBrazilian::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1561 of file translator_br.h.
    { return "Diretrios"; }
trDirectories() [2/2]
virtual QCString TranslatorBrazilian::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1561 of file translator_br.h.
    { return "Diretrios"; }
trDirIndex() [1/2]
virtual QCString TranslatorBrazilian::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1549 of file translator_br.h.
    { return "Hierarquia de Diretrios"; }
trDirIndex() [2/2]
virtual QCString TranslatorBrazilian::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1549 of file translator_br.h.
    { return "Hierarquia de Diretrios"; }
trDirReference() [1/2]
virtual QCString TranslatorBrazilian::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1567 of file translator_br.h.
    {
        QCString result = "Referncia do diretrio ";
        result += dirName;
        return result;
    }
trDirReference() [2/2]
virtual QCString TranslatorBrazilian::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1567 of file translator_br.h.
    {
        QCString result = "Referncia do diretrio ";
        result += dirName;
        return result;
    }
trDirRelation() [1/2]
virtual QCString TranslatorBrazilian::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1827 of file translator_br.h.
    {
      return "Relao " + QCString(name);
    }
References setup::name.
trDirRelation() [2/2]
virtual QCString TranslatorBrazilian::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1827 of file translator_br.h.
    {
      return "Relao " + QCString(name);
    }
References setup::name.
trDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 375 of file translator_br.h.
    {
      // TODO In the future, I think I'll suggest the replacement of this
      // method to something like trDocumentationOf(projPrefix). This will allow
      // the latin construction "Documentao de ProjA"
      return "Documentao";
    }
trDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 375 of file translator_br.h.
    {
      // TODO In the future, I think I'll suggest the replacement of this
      // method to something like trDocumentationOf(projPrefix). This will allow
      // the latin construction "Documentao de ProjA"
      return "Documentao";
    }
trEnumerations() [1/2]
virtual QCString TranslatorBrazilian::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 472 of file translator_br.h.
    { return "Enumeraes"; }
trEnumerations() [2/2]
virtual QCString TranslatorBrazilian::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 472 of file translator_br.h.
    { return "Enumeraes"; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 508 of file translator_br.h.
    { return "Enumeraes"; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 508 of file translator_br.h.
    { return "Enumeraes"; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1611 of file translator_br.h.
    { return "Documentao da enumerao"; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1611 of file translator_br.h.
    { return "Documentao da enumerao"; }
trEnumerationValues() [1/2]
virtual QCString TranslatorBrazilian::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 490 of file translator_br.h.
    { return "Enumeradores"; }
trEnumerationValues() [2/2]
virtual QCString TranslatorBrazilian::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 490 of file translator_br.h.
    { return "Enumeradores"; }
trEnumGeneratedFromFiles() [1/2]
virtual QCString TranslatorBrazilian::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1963 of file translator_br.h.
    { QCString result = "A documentao para essa enumerao foi gerada a partir ";
      if (single) {
        result += "do seguinte arquivo:";
      } else {
        result += "dos seguintes arquivos:";
      }
      return result;
    }
trEnumGeneratedFromFiles() [2/2]
virtual QCString TranslatorBrazilian::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1963 of file translator_br.h.
    { QCString result = "A documentao para essa enumerao foi gerada a partir ";
      if (single) {
        result += "do seguinte arquivo:";
      } else {
        result += "dos seguintes arquivos:";
      }
      return result;
    }
trEnumName() [1/2]
virtual QCString TranslatorBrazilian::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 185 of file translator_br.h.
    { return "Enumerao"; }
trEnumName() [2/2]
virtual QCString TranslatorBrazilian::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 185 of file translator_br.h.
    { return "Enumerao"; }
trEnumReference() [1/2]
virtual QCString TranslatorBrazilian::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1974 of file translator_br.h.
    {
      QCString result = "Referncia da enumerao ";
      return result + name;
    }
References setup::name.
trEnumReference() [2/2]
virtual QCString TranslatorBrazilian::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1974 of file translator_br.h.
    {
      QCString result = "Referncia da enumerao ";
      return result + name;
    }
References setup::name.
trEnumValue() [1/2]
virtual QCString TranslatorBrazilian::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 189 of file translator_br.h.
    { return "Valor da enumerao"; }
trEnumValue() [2/2]
virtual QCString TranslatorBrazilian::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 189 of file translator_br.h.
    { return "Valor da enumerao"; }
trEventDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1423 of file translator_br.h.
    {
      return "Eventos";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1423 of file translator_br.h.
    {
      return "Eventos";
    }
trEvents() [1/2]
virtual QCString TranslatorBrazilian::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1418 of file translator_br.h.
    {
      return "Eventos";
    }
trEvents() [2/2]
virtual QCString TranslatorBrazilian::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1418 of file translator_br.h.
    {
      return "Eventos";
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 450 of file translator_br.h.
    { return "Exemplos"; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 450 of file translator_br.h.
    { return "Exemplos"; }
trExamples() [1/2]
virtual QCString TranslatorBrazilian::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 256 of file translator_br.h.
    { return "Exemplos"; }
trExamples() [2/2]
virtual QCString TranslatorBrazilian::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 256 of file translator_br.h.
    { return "Exemplos"; }
trExamplesDescription() [1/2]
virtual QCString TranslatorBrazilian::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 363 of file translator_br.h.
    { return "Esta a lista de todos os exemplos:"; }
trExamplesDescription() [2/2]
virtual QCString TranslatorBrazilian::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 363 of file translator_br.h.
    { return "Esta a lista de todos os exemplos:"; }
trExceptionDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trExceptionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2321 of file translator_br.h.
    {
        return "Excees";
    }
trExceptionDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trExceptionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2321 of file translator_br.h.
    {
        return "Excees";
    }
trExceptionHierarchy() [1/2]
virtual QCString TranslatorBrazilian::trExceptionHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2313 of file translator_br.h.
    {
        return "Hierarquia de Excees";
    }
trExceptionHierarchy() [2/2]
virtual QCString TranslatorBrazilian::trExceptionHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2313 of file translator_br.h.
    {
        return "Hierarquia de Excees";
    }
trExceptionHierarchyDescription() [1/2]
virtual QCString TranslatorBrazilian::trExceptionHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2317 of file translator_br.h.
    {
        return "Esta a lista parcialmente ordenadas de heranas:";
    }
trExceptionHierarchyDescription() [2/2]
virtual QCString TranslatorBrazilian::trExceptionHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2317 of file translator_br.h.
    {
        return "Esta a lista parcialmente ordenadas de heranas:";
    }
trExceptionIndex() [1/2]
virtual QCString TranslatorBrazilian::trExceptionIndex () [inline], [virtual]
Implements Translator.
Definition at line 2301 of file translator_br.h.
    {
        return "ndice the Excees";
    }
trExceptionIndex() [2/2]
virtual QCString TranslatorBrazilian::trExceptionIndex () [inline], [virtual]
Implements Translator.
Definition at line 2301 of file translator_br.h.
    {
        return "ndice the Excees";
    }
trExceptionList() [1/2]
virtual QCString TranslatorBrazilian::trExceptionList () [inline], [virtual]
Implements Translator.
Definition at line 2305 of file translator_br.h.
    {
        return "Lista de Excees";
    }
trExceptionList() [2/2]
virtual QCString TranslatorBrazilian::trExceptionList () [inline], [virtual]
Implements Translator.
Definition at line 2305 of file translator_br.h.
    {
        return "Lista de Excees";
    }
trExceptionListDescription() [1/2]
virtual QCString TranslatorBrazilian::trExceptionListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2309 of file translator_br.h.
    {
        return "Estas so as excees com suas respectivas descries:";
    }
trExceptionListDescription() [2/2]
virtual QCString TranslatorBrazilian::trExceptionListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2309 of file translator_br.h.
    {
        return "Estas so as excees com suas respectivas descries:";
    }
trExceptions() [1/2]
virtual QCString TranslatorBrazilian::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 580 of file translator_br.h.
    { return "Excees"; }
trExceptions() [2/2]
virtual QCString TranslatorBrazilian::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 580 of file translator_br.h.
    { return "Excees"; }
trExtendsClass() [1/2]
virtual QCString TranslatorBrazilian::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 2017 of file translator_br.h.
    {
      return "estende a classe @0.";
    }
trExtendsClass() [2/2]
virtual QCString TranslatorBrazilian::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 2017 of file translator_br.h.
    {
      return "estende a classe @0.";
    }
trFile() [1/2]
virtual QCString TranslatorBrazilian::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1277 of file translator_br.h.
    {
      QCString result((first_capital ? "Arquivo": "arquivo"));
      if (!singular) result+="s";
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorBrazilian::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1277 of file translator_br.h.
    {
      QCString result((first_capital ? "Arquivo": "arquivo"));
      if (!singular) result+="s";
      return result;
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 444 of file translator_br.h.
    { return "Arquivos"; }
trFileDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 444 of file translator_br.h.
    { return "Arquivos"; }
trFileIn() [1/2]
virtual QCString TranslatorBrazilian::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1864 of file translator_br.h.
    {
      return "Arquivo em "+name;
    }
References setup::name.
trFileIn() [2/2]
virtual QCString TranslatorBrazilian::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1864 of file translator_br.h.
    {
      return "Arquivo em "+name;
    }
References setup::name.
trFileIndex() [1/2]
virtual QCString TranslatorBrazilian::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 413 of file translator_br.h.
    { return "ndice dos Arquivos"; }
trFileIndex() [2/2]
virtual QCString TranslatorBrazilian::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 413 of file translator_br.h.
    { return "ndice dos Arquivos"; }
trFileList() [1/2]
virtual QCString TranslatorBrazilian::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 222 of file translator_br.h.
    { return "Lista de Arquivos"; }
trFileList() [2/2]
virtual QCString TranslatorBrazilian::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 222 of file translator_br.h.
    { return "Lista de Arquivos"; }
trFileListDescription() [1/2]
virtual QCString TranslatorBrazilian::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 268 of file translator_br.h.
    {
      QCString result="Esta a lista de todos os arquivos ";
      if (!extractAll) result+="documentados ";
      result+="e suas respectivas descries:";
      return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorBrazilian::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 268 of file translator_br.h.
    {
      QCString result="Esta a lista de todos os arquivos ";
      if (!extractAll) result+="documentados ";
      result+="e suas respectivas descries:";
      return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorBrazilian::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 239 of file translator_br.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "tens globais";
      }
      else
      {
        return "Membros dos Arquivos";
      }
    }
References Config_getBool.
trFileMembers() [2/2]
virtual QCString TranslatorBrazilian::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 239 of file translator_br.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "tens globais";
      }
      else
      {
        return "Membros dos Arquivos";
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
virtual QCString TranslatorBrazilian::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 341 of file translator_br.h.
    {
      QCString result="Esta a lista de ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="todas as funes, variveis, definies, enumeraes e definies de tipos ";
        if (!extractAll) result+="documentadas ";
      }
      else
      {
        result+="todos os membros dos arquivos ";
        if (!extractAll) result+="documentados ";
      }
      result+="com referncias para ";
      if (extractAll)
        result+="seus respectivos arquivos:";
      else
        result+="suas respectivas documentaes:";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorBrazilian::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 341 of file translator_br.h.
    {
      QCString result="Esta a lista de ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="todas as funes, variveis, definies, enumeraes e definies de tipos ";
        if (!extractAll) result+="documentadas ";
      }
      else
      {
        result+="todos os membros dos arquivos ";
        if (!extractAll) result+="documentados ";
      }
      result+="com referncias para ";
      if (extractAll)
        result+="seus respectivos arquivos:";
      else
        result+="suas respectivas documentaes:";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorBrazilian::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 655 of file translator_br.h.
    {
      QCString result = "Referncia do Arquivo ";
      result += fileName;
      return result;
    }
trFileReference() [2/2]
virtual QCString TranslatorBrazilian::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 655 of file translator_br.h.
    {
      QCString result = "Referncia do Arquivo ";
      result += fileName;
      return result;
    }
trFlowchart() [1/2]
virtual QCString TranslatorBrazilian::trFlowchart () [inline], [virtual]
This is used for translation of the word that will be followed by a single name of the VHDL process flowchart.
Implements Translator.
Definition at line 2429 of file translator_br.h.
    {
        return "Fluxograma: ";
    }
trFlowchart() [2/2]
virtual QCString TranslatorBrazilian::trFlowchart () [inline], [virtual]
This is used for translation of the word that will be followed by a single name of the VHDL process flowchart.
Implements Translator.
Definition at line 2429 of file translator_br.h.
    {
        return "Fluxograma: ";
    }
trFriends() [1/2]
virtual QCString TranslatorBrazilian::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 607 of file translator_br.h.
    { return "Amigas"; }
trFriends() [2/2]
virtual QCString TranslatorBrazilian::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 607 of file translator_br.h.
    { return "Amigas"; }
trFunctionAndProc() [1/2]
virtual QCString TranslatorBrazilian::trFunctionAndProc () [inline], [virtual]
VHDL functions/procedures/processes
Implements Translator.
Definition at line 2137 of file translator_br.h.
    { return "Funes/Procedimentos/Processos"; }
trFunctionAndProc() [2/2]
virtual QCString TranslatorBrazilian::trFunctionAndProc () [inline], [virtual]
VHDL functions/procedures/processes
Implements Translator.
Definition at line 2137 of file translator_br.h.
    { return "Funes/Procedimentos/Processos"; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 514 of file translator_br.h.
    { return "Funes"; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 514 of file translator_br.h.
    { return "Funes"; }
trFunctions() [1/2]
virtual QCString TranslatorBrazilian::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 478 of file translator_br.h.
    { return "Funes"; }
trFunctions() [2/2]
virtual QCString TranslatorBrazilian::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 478 of file translator_br.h.
    { return "Funes"; }
trGeneratedAt() [1/2]
virtual QCString TranslatorBrazilian::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 541 of file translator_br.h.
    {
      QCString result="Gerado em "+date;
      if (!projName.isEmpty()) result+=" para "+projName;
      result+=" por";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorBrazilian::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 541 of file translator_br.h.
    {
      QCString result="Gerado em "+date;
      if (!projName.isEmpty()) result+=" para "+projName;
      result+=" por";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorBrazilian::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 177 of file translator_br.h.
    { QCString result="Gerado automaticamente por Doxygen";
      if (!s.isEmpty()) result+=" para "+s;
      result+=" a partir do cdigo-fonte.";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorBrazilian::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 177 of file translator_br.h.
    { QCString result="Gerado automaticamente por Doxygen";
      if (!s.isEmpty()) result+=" para "+s;
      result+=" a partir do cdigo-fonte.";
      return result;
    }
References s.
trGeneratedBy() [1/2]
virtual QCString TranslatorBrazilian::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 584 of file translator_br.h.
    { return "Gerado por"; }
trGeneratedBy() [2/2]
virtual QCString TranslatorBrazilian::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 584 of file translator_br.h.
    { return "Gerado por"; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorBrazilian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 811 of file translator_br.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      QCString result="A documentao para ";
      if (compType == ClassDef::Protocol)
      {
         result+= "esse ";
      }
      else
      {
         result+= "essa ";
      }
      switch(compType)
      {
        case ClassDef::Class: result+=vhdlOpt?"Unidade de Design ":"classe "; break;
        case ClassDef::Struct: result+="estrutura "; break;
        case ClassDef::Union: result+="unio "; break;
        case ClassDef::Interface: result+="interface "; break;
        case ClassDef::Protocol: result+="protocolo "; break;
        case ClassDef::Category: result+="categoria "; break;
        case ClassDef::Exception: result+="exceo "; break;
        default: break;
      }
      result+=" foi gerada a partir ";
      if (single) result+="do seguinte arquivo:"; else result+="dos seguintes arquivos:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, Config_getBool, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorBrazilian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 811 of file translator_br.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      QCString result="A documentao para ";
      if (compType == ClassDef::Protocol)
      {
         result+= "esse ";
      }
      else
      {
         result+= "essa ";
      }
      switch(compType)
      {
        case ClassDef::Class: result+=vhdlOpt?"Unidade de Design ":"classe "; break;
        case ClassDef::Struct: result+="estrutura "; break;
        case ClassDef::Union: result+="unio "; break;
        case ClassDef::Interface: result+="interface "; break;
        case ClassDef::Protocol: result+="protocolo "; break;
        case ClassDef::Category: result+="categoria "; break;
        case ClassDef::Exception: result+="exceo "; break;
        default: break;
      }
      result+=" foi gerada a partir ";
      if (single) result+="do seguinte arquivo:"; else result+="dos seguintes arquivos:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, Config_getBool, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorBrazilian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1768 of file translator_br.h.
    {
      // single is true implies a single file
      QCString result="A documentao para ";
      switch(compType)
      {
        case ClassDef::Class: result+="esse modulo "; break;
        case ClassDef::Struct: result+="esse tipo "; break;
        case ClassDef::Union: result+="essa unio "; break;
        case ClassDef::Interface: result+="essa interface "; break;
        case ClassDef::Protocol: result+="esso protocolo "; break;
        case ClassDef::Category: result+="essa categoria "; break;
        case ClassDef::Exception: result+="essa exceo "; break;
        default: break;
      }
      result+=" foi gerada a partir do";
      if (single)
        result+=" seguinte arquivo:";
      else
        result+="s seguintes arquivos:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorBrazilian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1768 of file translator_br.h.
    {
      // single is true implies a single file
      QCString result="A documentao para ";
      switch(compType)
      {
        case ClassDef::Class: result+="esse modulo "; break;
        case ClassDef::Struct: result+="esse tipo "; break;
        case ClassDef::Union: result+="essa unio "; break;
        case ClassDef::Interface: result+="essa interface "; break;
        case ClassDef::Protocol: result+="esso protocolo "; break;
        case ClassDef::Category: result+="essa categoria "; break;
        case ClassDef::Exception: result+="essa exceo "; break;
        default: break;
      }
      result+=" foi gerada a partir do";
      if (single)
        result+=" seguinte arquivo:";
      else
        result+="s seguintes arquivos:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorBrazilian::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1332 of file translator_br.h.
    {
      QCString result((first_capital ? "Globa" : "globa"));
      if (!singular){
        result+="is";
      }else{
        result+="l";
      }
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorBrazilian::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1332 of file translator_br.h.
    {
      QCString result((first_capital ? "Globa" : "globa"));
      if (!singular){
        result+="is";
      }else{
        result+="l";
      }
      return result;
    }
trGlobalNamespace() [1/2]
virtual QCString TranslatorBrazilian::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1839 of file translator_br.h.
    {
      return "<em>Namespace</em> global";
    }
trGlobalNamespace() [2/2]
virtual QCString TranslatorBrazilian::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1839 of file translator_br.h.
    {
      return "<em>Namespace</em> global";
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 910 of file translator_br.h.
    {
      return "V para a documentao desse arquivo.";
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 910 of file translator_br.h.
    {
      return "V para a documentao desse arquivo.";
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorBrazilian::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 943 of file translator_br.h.
    {
      return "V para o grfico de hierarquia de classes";
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorBrazilian::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 943 of file translator_br.h.
    {
      return "V para o grfico de hierarquia de classes";
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorBrazilian::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 905 of file translator_br.h.
    {
      return "V para o cdigo-fonte desse arquivo.";
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorBrazilian::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 905 of file translator_br.h.
    {
      return "V para o cdigo-fonte desse arquivo.";
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorBrazilian::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 947 of file translator_br.h.
    {
      return "V para a hierarquia de classes (texto)";
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorBrazilian::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 947 of file translator_br.h.
    {
      return "V para a hierarquia de classes (texto)";
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorBrazilian::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 939 of file translator_br.h.
    {
      return "Grfico de Hierarquia de Classes";
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorBrazilian::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 939 of file translator_br.h.
    {
      return "Grfico de Hierarquia de Classes";
    }
trGroup() [1/2]
virtual QCString TranslatorBrazilian::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1299 of file translator_br.h.
    {
      QCString result((first_capital ? "Grupo" : "grupo"));
      if (!singular) result+="s";
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorBrazilian::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1299 of file translator_br.h.
    {
      QCString result((first_capital ? "Grupo" : "grupo"));
      if (!singular) result+="s";
      return result;
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorBrazilian::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 392 of file translator_br.h.
    { return "ndice Hierrquico"; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorBrazilian::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 392 of file translator_br.h.
    { return "ndice Hierrquico"; }
trImplementedFromList() [1/2]
virtual QCString TranslatorBrazilian::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1374 of file translator_br.h.
    {
      return "Implementa "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorBrazilian::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1374 of file translator_br.h.
    {
      return "Implementa "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorBrazilian::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implementation this member.
Implements Translator.
Definition at line 1382 of file translator_br.h.
    {
      return "Implementado por "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorBrazilian::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implementation this member.
Implements Translator.
Definition at line 1382 of file translator_br.h.
    {
      return "Implementado por "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorBrazilian::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 1039 of file translator_br.h.
    {
      return "Este grafo mostra quais arquivos esto direta ou indiretamente relacionados com esse arquivo:";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorBrazilian::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 1039 of file translator_br.h.
    {
      return "Este grafo mostra quais arquivos esto direta ou indiretamente relacionados com esse arquivo:";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorBrazilian::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 895 of file translator_br.h.
    {
      return "Grfico de dependncia de incluses para "+fName+":";
    }
trInclDepGraph() [2/2]
virtual QCString TranslatorBrazilian::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 895 of file translator_br.h.
    {
      return "Grfico de dependncia de incluses para "+fName+":";
    }
trIncludesFileIn() [1/2]
virtual QCString TranslatorBrazilian::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1873 of file translator_br.h.
    {
      return "Inclui arquivo em "+name;
    }
References setup::name.
trIncludesFileIn() [2/2]
virtual QCString TranslatorBrazilian::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1873 of file translator_br.h.
    {
      return "Inclui arquivo em "+name;
    }
References setup::name.
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorBrazilian::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 171 of file translator_br.h.
    { return ", incluindo os membros herdados."; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorBrazilian::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 171 of file translator_br.h.
    { return ", incluindo os membros herdados."; }
trInheritedByList() [1/2]
virtual QCString TranslatorBrazilian::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 745 of file translator_br.h.
    {
      return "Superclasse de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorBrazilian::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 745 of file translator_br.h.
    {
      return "Superclasse de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom() [1/2]
virtual QCString TranslatorBrazilian::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1981 of file translator_br.h.
    { return QCString(members)+" herdados de "+what; }
trInheritedFrom() [2/2]
virtual QCString TranslatorBrazilian::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1981 of file translator_br.h.
    { return QCString(members)+" herdados de "+what; }
trInheritsList() [1/2]
virtual QCString TranslatorBrazilian::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 737 of file translator_br.h.
    {
      return "Subclasse de " + trWriteList(numEntries) + ".";
    }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorBrazilian::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 737 of file translator_br.h.
    {
      return "Subclasse de " + trWriteList(numEntries) + ".";
    }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorBrazilian::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 930 of file translator_br.h.
    {
      return "Valor inicial:";
    }
trInitialValue() [2/2]
virtual QCString TranslatorBrazilian::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 930 of file translator_br.h.
    {
      return "Valor inicial:";
    }
trInstanceMethods() [1/2]
virtual QCString TranslatorBrazilian::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 2033 of file translator_br.h.
    {
      return "Mtodos da instncia";
    }
trInstanceMethods() [2/2]
virtual QCString TranslatorBrazilian::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 2033 of file translator_br.h.
    {
      return "Mtodos da instncia";
    }
trInterfaceDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trInterfaceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2277 of file translator_br.h.
    {
        return "Interfaces";
    }
trInterfaceDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trInterfaceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2277 of file translator_br.h.
    {
        return "Interfaces";
    }
trInterfaceHierarchy() [1/2]
virtual QCString TranslatorBrazilian::trInterfaceHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2269 of file translator_br.h.
    {
        return "Hierarquia de Interfaces";
    }
trInterfaceHierarchy() [2/2]
virtual QCString TranslatorBrazilian::trInterfaceHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2269 of file translator_br.h.
    {
        return "Hierarquia de Interfaces";
    }
trInterfaceHierarchyDescription() [1/2]
virtual QCString TranslatorBrazilian::trInterfaceHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2273 of file translator_br.h.
    {
        return "Esta a lista parcialmente ordenadas de heranas:";
    }
trInterfaceHierarchyDescription() [2/2]
virtual QCString TranslatorBrazilian::trInterfaceHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2273 of file translator_br.h.
    {
        return "Esta a lista parcialmente ordenadas de heranas:";
    }
trInterfaceIndex() [1/2]
virtual QCString TranslatorBrazilian::trInterfaceIndex () [inline], [virtual]
Implements Translator.
Definition at line 2257 of file translator_br.h.
    {
        return "ndice de Interfaces";
    }
trInterfaceIndex() [2/2]
virtual QCString TranslatorBrazilian::trInterfaceIndex () [inline], [virtual]
Implements Translator.
Definition at line 2257 of file translator_br.h.
    {
        return "ndice de Interfaces";
    }
trInterfaceList() [1/2]
virtual QCString TranslatorBrazilian::trInterfaceList () [inline], [virtual]
Implements Translator.
Definition at line 2261 of file translator_br.h.
    {
        return "Lista de Interfaces";
    }
trInterfaceList() [2/2]
virtual QCString TranslatorBrazilian::trInterfaceList () [inline], [virtual]
Implements Translator.
Definition at line 2261 of file translator_br.h.
    {
        return "Lista de Interfaces";
    }
trInterfaceListDescription() [1/2]
virtual QCString TranslatorBrazilian::trInterfaceListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2265 of file translator_br.h.
    {
        return "Estas so as interfaces com suas respectivas descries:";
    }
trInterfaceListDescription() [2/2]
virtual QCString TranslatorBrazilian::trInterfaceListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2265 of file translator_br.h.
    {
        return "Estas so as interfaces com suas respectivas descries:";
    }
trInterfaces() [1/2]
virtual QCString TranslatorBrazilian::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 2050 of file translator_br.h.
    { return "Interfaces Exportadas"; }
trInterfaces() [2/2]
virtual QCString TranslatorBrazilian::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 2050 of file translator_br.h.
    { return "Interfaces Exportadas"; }
trInvariant() [1/2]
virtual QCString TranslatorBrazilian::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 925 of file translator_br.h.
    {
      return "Invariante";
    }
trInvariant() [2/2]
virtual QCString TranslatorBrazilian::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 925 of file translator_br.h.
    {
      return "Invariante";
    }
trISOLang() [1/2]
virtual QCString TranslatorBrazilian::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 97 of file translator_br.h.
    {
      return "pt-BR";
    }
trISOLang() [2/2]
virtual QCString TranslatorBrazilian::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 97 of file translator_br.h.
    {
      return "pt-BR";
    }
trLegend() [1/2]
virtual QCString TranslatorBrazilian::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1126 of file translator_br.h.
    {
      return "legenda";
    }
trLegend() [2/2]
virtual QCString TranslatorBrazilian::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1126 of file translator_br.h.
    {
      return "legenda";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorBrazilian::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 1060 of file translator_br.h.
    {
      return
        "Esta pgina explica como interpretar os grafos gerados pelo doxygen.<p>\n"
        "Considere o seguinte exemplo:\n"
        "\\code\n"
        "/*! Classe oculta por causa da truncagem */\n"
        "class Invisible { };\n\n"
        "/*! Classe Truncated, relao de herana est oculta */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Classe no documentada com os comentrios do Doxygen */\n"
        "class Undocumented { };\n\n"
        "/*! Classe possui que possui uma relao de herana pblica */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! Um template de classe */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Classe possui que possui uma relao de herana protegida */\n"
        "class ProtectedBase { };\n\n"
        "/*! Classe possui que possui uma relao de herana privada */\n"
        "class PrivateBase { };\n\n"
        "/*! Classe utilizada pela classe Inherited */\n"
        "class Used { };\n\n"
        "/*! Super classe que herda outras classes */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Isto ir gerar o seguinte grfo:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "As caixas no grafo acima possuem os seguintes significados:\n"
        "</p>\n"
        "<ul>\n"
        "<li>Uma caixa cinza denota a estrutura ou a classe que gerou"
    "este grafo.</li>\n"
        "<li>Uma caixa com a borda preta denota uma estrutura ou classe documentada.</li>\n"
        "<li>Uma caixa com a borda cinza denota uma estrutura ou classe no documentada.</li>\n"
        "<li>Uma caixa com a borda vermelha denota uma estrutura ou classe na"
        "qual nem todas as relaes so mostradas. Um grafo truncado quando "
        "esse no cabe no espao especificado.</li>\n"
        "</ul>\n"
        "<p>\n"
        "As setas possuem os seguintes significados:\n"
        "</p>\n"
        "<ul>\n"
        "<li>Uma seta azul escura denota a relao de herana pblica entre "
        "duas classes.</li>\n"
        "<li>Uma seta verde escura denota a relao de herana protegida entre "
        "duas classes.</li>\n"
        "<li>Uma seta vermelha escura denota a relao de herana privada entre "
        "duas classes.</li>\n"
        "<li>Uma seta pontilhada prpura denota a relao de uso e/ou agragao "
        "por outra classe/estrutura. A etiqueta da seta denota o nome do(s) campo(s) "
        "que representa(m) este apontamento.</li>\n"
        "<li>Uma seta pontilhada amarela denota a relao de instanciao de uma "
        "<em>template</em>. A etiqueta da seta denota os parmetros de instanciao "
        "desta <em>template</em>.</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorBrazilian::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 1060 of file translator_br.h.
    {
      return
        "Esta pgina explica como interpretar os grafos gerados pelo doxygen.<p>\n"
        "Considere o seguinte exemplo:\n"
        "\\code\n"
        "/*! Classe oculta por causa da truncagem */\n"
        "class Invisible { };\n\n"
        "/*! Classe Truncated, relao de herana est oculta */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Classe no documentada com os comentrios do Doxygen */\n"
        "class Undocumented { };\n\n"
        "/*! Classe possui que possui uma relao de herana pblica */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! Um template de classe */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Classe possui que possui uma relao de herana protegida */\n"
        "class ProtectedBase { };\n\n"
        "/*! Classe possui que possui uma relao de herana privada */\n"
        "class PrivateBase { };\n\n"
        "/*! Classe utilizada pela classe Inherited */\n"
        "class Used { };\n\n"
        "/*! Super classe que herda outras classes */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Isto ir gerar o seguinte grfo:"
        "<p><center><img src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "As caixas no grafo acima possuem os seguintes significados:\n"
        "</p>\n"
        "<ul>\n"
        "<li>Uma caixa cinza denota a estrutura ou a classe que gerou"
    "este grafo.</li>\n"
        "<li>Uma caixa com a borda preta denota uma estrutura ou classe documentada.</li>\n"
        "<li>Uma caixa com a borda cinza denota uma estrutura ou classe no documentada.</li>\n"
        "<li>Uma caixa com a borda vermelha denota uma estrutura ou classe na"
        "qual nem todas as relaes so mostradas. Um grafo truncado quando "
        "esse no cabe no espao especificado.</li>\n"
        "</ul>\n"
        "<p>\n"
        "As setas possuem os seguintes significados:\n"
        "</p>\n"
        "<ul>\n"
        "<li>Uma seta azul escura denota a relao de herana pblica entre "
        "duas classes.</li>\n"
        "<li>Uma seta verde escura denota a relao de herana protegida entre "
        "duas classes.</li>\n"
        "<li>Uma seta vermelha escura denota a relao de herana privada entre "
        "duas classes.</li>\n"
        "<li>Uma seta pontilhada prpura denota a relao de uso e/ou agragao "
        "por outra classe/estrutura. A etiqueta da seta denota o nome do(s) campo(s) "
        "que representa(m) este apontamento.</li>\n"
        "<li>Uma seta pontilhada amarela denota a relao de instanciao de uma "
        "<em>template</em>. A etiqueta da seta denota os parmetros de instanciao "
        "desta <em>template</em>.</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorBrazilian::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 1053 of file translator_br.h.
    {
      return "Legenda do Grafo";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorBrazilian::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 1053 of file translator_br.h.
    {
      return "Legenda do Grafo";
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorBrazilian::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 159 of file translator_br.h.
    { return "Lista de todos os Membros"; }
trListOfAllMembers() [2/2]
virtual QCString TranslatorBrazilian::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 159 of file translator_br.h.
    { return "Lista de todos os Membros"; }
trLoading() [1/2]
virtual QCString TranslatorBrazilian::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1833 of file translator_br.h.
    {
      return "Carregando...";
    }
trLoading() [2/2]
virtual QCString TranslatorBrazilian::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1833 of file translator_br.h.
    {
      return "Carregando...";
    }
trMainPage() [1/2]
virtual QCString TranslatorBrazilian::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 851 of file translator_br.h.
    { return "Pgina Principal"; }
trMainPage() [2/2]
virtual QCString TranslatorBrazilian::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 851 of file translator_br.h.
    { return "Pgina Principal"; }
trMember() [1/2]
virtual QCString TranslatorBrazilian::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1321 of file translator_br.h.
    {
      QCString result((first_capital ? "Membro" : "membro"));
      if (!singular) result+="s";
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorBrazilian::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1321 of file translator_br.h.
    {
      QCString result((first_capital ? "Membro" : "membro"));
      if (!singular) result+="s";
      return result;
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 142 of file translator_br.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Campos";
      }
      else
      {
        return "Atributos";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 142 of file translator_br.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Campos";
      }
      else
      {
        return "Atributos";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 125 of file translator_br.h.
    { return "Documentao das enumeraes"; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 125 of file translator_br.h.
    { return "Documentao das enumeraes"; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 129 of file translator_br.h.
    {
        if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
        {
          return "Documentao das funes, procedimentos e processos";
        }
        else
        {
            return "Documentao das funes";
        }
    }
References Config_getBool.
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 129 of file translator_br.h.
    {
        if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
        {
          return "Documentao das funes, procedimentos e processos";
        }
        else
        {
            return "Documentao das funes";
        }
    }
References Config_getBool.
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorBrazilian::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1620 of file translator_br.h.
    { return "Documentao de Funo Membro/Subrotina"; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorBrazilian::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1620 of file translator_br.h.
    { return "Documentao de Funo Membro/Subrotina"; }
trMemberList() [1/2]
virtual QCString TranslatorBrazilian::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 163 of file translator_br.h.
    { return "Lista dos Membros"; }
trMemberList() [2/2]
virtual QCString TranslatorBrazilian::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 163 of file translator_br.h.
    { return "Lista dos Membros"; }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 121 of file translator_br.h.
    { return "Documentao das definies de tipos"; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 121 of file translator_br.h.
    { return "Documentao das definies de tipos"; }
trMethodDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 2040 of file translator_br.h.
    {
      return "Documentao do mtodo";
    }
trMethodDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 2040 of file translator_br.h.
    {
      return "Documentao do mtodo";
    }
trModule() [1/2]
virtual QCString TranslatorBrazilian::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1758 of file translator_br.h.
    {
      QCString result((first_capital ? "Mdulo" : "mdulo"));
      if (!singular) result+="s";
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorBrazilian::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1758 of file translator_br.h.
    {
      QCString result((first_capital ? "Mdulo" : "mdulo"));
      if (!singular) result+="s";
      return result;
    }
trModuleDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 419 of file translator_br.h.
    { return "Mdulos"; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 419 of file translator_br.h.
    { return "Mdulos"; }
trModuleIndex() [1/2]
virtual QCString TranslatorBrazilian::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 386 of file translator_br.h.
    { return "ndice dos Mdulos"; }
trModuleIndex() [2/2]
virtual QCString TranslatorBrazilian::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 386 of file translator_br.h.
    { return "ndice dos Mdulos"; }
trModuleReference() [1/2]
virtual QCString TranslatorBrazilian::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1720 of file translator_br.h.
    {
      QCString result = "Referncia do Mdulo ";
      result += namespaceName;
      return result;
    }
trModuleReference() [2/2]
virtual QCString TranslatorBrazilian::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1720 of file translator_br.h.
    {
      QCString result = "Referncia do Mdulo ";
      result += namespaceName;
      return result;
    }
trModules() [1/2]
virtual QCString TranslatorBrazilian::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 201 of file translator_br.h.
    { return "Mdulos"; }
trModules() [2/2]
virtual QCString TranslatorBrazilian::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 201 of file translator_br.h.
    { return "Mdulos"; }
trModulesDescription() [1/2]
virtual QCString TranslatorBrazilian::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 371 of file translator_br.h.
    { return "Esta a lista de todos os mdulos:"; }
trModulesDescription() [2/2]
virtual QCString TranslatorBrazilian::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 371 of file translator_br.h.
    { return "Esta a lista de todos os mdulos:"; }
trModulesIndex() [1/2]
virtual QCString TranslatorBrazilian::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1751 of file translator_br.h.
    { return "ndice dos Mdulos"; }
trModulesIndex() [2/2]
virtual QCString TranslatorBrazilian::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1751 of file translator_br.h.
    { return "ndice dos Mdulos"; }
trModulesList() [1/2]
virtual QCString TranslatorBrazilian::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1683 of file translator_br.h.
    { return "Lista de Mdulos"; }
trModulesList() [2/2]
virtual QCString TranslatorBrazilian::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1683 of file translator_br.h.
    { return "Lista de Mdulos"; }
trModulesListDescription() [1/2]
virtual QCString TranslatorBrazilian::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1687 of file translator_br.h.
    {
      QCString result="Esta a lista de todos os mdulos ";
      if (!extractAll) result+="documentados ";
      result+="com descries resumidas:";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorBrazilian::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1687 of file translator_br.h.
    {
      QCString result="Esta a lista de todos os mdulos ";
      if (!extractAll) result+="documentados ";
      result+="com descries resumidas:";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorBrazilian::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1732 of file translator_br.h.
    {
      QCString result="Esta a lista de todos os membros ";
      if (!extractAll) result+="documentados ";
      result+="dos mdulos com links para ";
      if (extractAll)
      {
        result+="a documentao dos mdulos para cada membro:";
      }
      else
      {
        result+="os mdulos a que pertencem:";
      }
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorBrazilian::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1732 of file translator_br.h.
    {
      QCString result="Esta a lista de todos os membros ";
      if (!extractAll) result+="documentados ";
      result+="dos mdulos com links para ";
      if (extractAll)
      {
        result+="a documentao dos mdulos para cada membro:";
      }
      else
      {
        result+="os mdulos a que pertencem:";
      }
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorBrazilian::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1728 of file translator_br.h.
    { return "Membros do Mdulo"; }
trModulesMembers() [2/2]
virtual QCString TranslatorBrazilian::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1728 of file translator_br.h.
    { return "Membros do Mdulo"; }
trMonth() [1/2]
virtual QCString TranslatorBrazilian::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1912 of file translator_br.h.
    {
      static const char *months_short[] = { "jan", "fev", "mar", "abr", "mai", "jun", "jul", "ago", "set", "out", "nov", "dez" };
      static const char *months_full[] = { "janeiro", "fevereiro", "maro", "abril", "maio", "junho", "julho", "agosto", "setembro", "outubro", "novembro", "dezembro" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMonth() [2/2]
virtual QCString TranslatorBrazilian::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1912 of file translator_br.h.
    {
      static const char *months_short[] = { "jan", "fev", "mar", "abr", "mai", "jun", "jul", "ago", "set", "out", "nov", "dez" };
      static const char *months_full[] = { "janeiro", "fevereiro", "maro", "abril", "maio", "junho", "julho", "agosto", "setembro", "outubro", "novembro", "dezembro" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore() [1/2]
virtual QCString TranslatorBrazilian::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 155 of file translator_br.h.
    { return "Mais..."; }
trMore() [2/2]
virtual QCString TranslatorBrazilian::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 155 of file translator_br.h.
    { return "Mais..."; }
trNamespace() [1/2]
virtual QCString TranslatorBrazilian::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1288 of file translator_br.h.
    {
      QCString result((first_capital ? "Namespace" : "namespace"));
      if (!singular) result+="s";
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorBrazilian::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1288 of file translator_br.h.
    {
      QCString result((first_capital ? "Namespace" : "namespace"));
      if (!singular) result+="s";
      return result;
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 791 of file translator_br.h.
    { return "<em>Namespace</em>"; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 791 of file translator_br.h.
    { return "<em>Namespace</em>"; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorBrazilian::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 785 of file translator_br.h.
    { return "<em>Namespaces</em>"; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorBrazilian::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 785 of file translator_br.h.
    { return "<em>Namespaces</em>"; }
trNamespaceList() [1/2]
virtual QCString TranslatorBrazilian::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 592 of file translator_br.h.
    { return "Lista de Namespaces"; }
trNamespaceList() [2/2]
virtual QCString TranslatorBrazilian::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 592 of file translator_br.h.
    { return "Lista de Namespaces"; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorBrazilian::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 596 of file translator_br.h.
    {
      QCString result="Esta a lista de todos os Namespaces ";
      if (!extractAll) result+="documentados ";
      result+="com suas respectivas descries:";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorBrazilian::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 596 of file translator_br.h.
    {
      QCString result="Esta a lista de todos os Namespaces ";
      if (!extractAll) result+="documentados ";
      result+="com suas respectivas descries:";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorBrazilian::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 771 of file translator_br.h.
    {
      QCString result="Essa a lista com todos os membros ";
      if (!extractAll) result+="documentados ";
      result+="do <em>Namespace</em> com referncias para ";
      if (extractAll)
        result+="a documentao do <em>Namespace</em> para cada membro:";
      else
        result+="os seus respectivos <em>Namespaces</em>:";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorBrazilian::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 771 of file translator_br.h.
    {
      QCString result="Essa a lista com todos os membros ";
      if (!extractAll) result+="documentados ";
      result+="do <em>Namespace</em> com referncias para ";
      if (extractAll)
        result+="a documentao do <em>Namespace</em> para cada membro:";
      else
        result+="os seus respectivos <em>Namespaces</em>:";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorBrazilian::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 767 of file translator_br.h.
    { return "Membros do <em>Namespace</em>"; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorBrazilian::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 767 of file translator_br.h.
    { return "Membros do <em>Namespace</em>"; }
trNamespaceReference() [1/2]
virtual QCString TranslatorBrazilian::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 663 of file translator_br.h.
    {
      QCString result ="Refncia do Namespace ";
      result += namespaceName;
      return result;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorBrazilian::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 663 of file translator_br.h.
    {
      QCString result ="Refncia do Namespace ";
      result += namespaceName;
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorBrazilian::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 801 of file translator_br.h.
    { return "<em>Namespaces</em>"; }
trNamespaces() [2/2]
virtual QCString TranslatorBrazilian::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 801 of file translator_br.h.
    { return "<em>Namespaces</em>"; }
trNoMatches() [1/2]
virtual QCString TranslatorBrazilian::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1851 of file translator_br.h.
    {
      return "Nenhum resultado encontrado";
    }
trNoMatches() [2/2]
virtual QCString TranslatorBrazilian::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1851 of file translator_br.h.
    {
      return "Nenhum resultado encontrado";
    }
trNote() [1/2]
virtual QCString TranslatorBrazilian::trNote () [inline], [virtual]
Implements Translator.
Definition at line 960 of file translator_br.h.
    {
      return "Observao";
    }
trNote() [2/2]
virtual QCString TranslatorBrazilian::trNote () [inline], [virtual]
Implements Translator.
Definition at line 960 of file translator_br.h.
    {
      return "Observao";
    }
trOperationDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trOperationDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2347 of file translator_br.h.
    {
        return "Operaes";
    }
trOperationDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trOperationDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2347 of file translator_br.h.
    {
        return "Operaes";
    }
trOperations() [1/2]
virtual QCString TranslatorBrazilian::trOperations () [inline], [virtual]
Implements Translator.
Definition at line 2343 of file translator_br.h.
    {
        return "Operaes";
    }
trOperations() [2/2]
virtual QCString TranslatorBrazilian::trOperations () [inline], [virtual]
Implements Translator.
Definition at line 2343 of file translator_br.h.
    {
        return "Operaes";
    }
trOverloadText() [1/2]
virtual QCString TranslatorBrazilian::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1591 of file translator_br.h.
    {
       return "Esse um mtodo provido por convenincia. "
            "Ele difere do mtodo acima apenas na lista de "
            "argumentos que devem ser utilizados.";
    }
trOverloadText() [2/2]
virtual QCString TranslatorBrazilian::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1591 of file translator_br.h.
    {
       return "Esse um mtodo provido por convenincia. "
            "Ele difere do mtodo acima apenas na lista de "
            "argumentos que devem ser utilizados.";
    }
trPackage() [1/2]
virtual QCString TranslatorBrazilian::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1178 of file translator_br.h.
    {
      return "Pacote "+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorBrazilian::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1178 of file translator_br.h.
    {
      return "Pacote "+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorBrazilian::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1459 of file translator_br.h.
    {
      return "Atributos do Pacote";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorBrazilian::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1459 of file translator_br.h.
    {
      return "Atributos do Pacote";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorBrazilian::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1441 of file translator_br.h.
    {
      return "Funes do Pacote";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorBrazilian::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1441 of file translator_br.h.
    {
      return "Funes do Pacote";
    }
trPackageList() [1/2]
virtual QCString TranslatorBrazilian::trPackageList () [inline], [virtual]
Implements Translator.
Definition at line 2419 of file translator_br.h.
    { return "Lista de pacotes"; }
trPackageList() [2/2]
virtual QCString TranslatorBrazilian::trPackageList () [inline], [virtual]
Implements Translator.
Definition at line 2419 of file translator_br.h.
    { return "Lista de pacotes"; }
trPackageListDescription() [1/2]
virtual QCString TranslatorBrazilian::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1183 of file translator_br.h.
    {
      return "Esta a lista com os pacotes e suas respectivas descries (quando disponveis):";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorBrazilian::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1183 of file translator_br.h.
    {
      return "Esta a lista com os pacotes e suas respectivas descries (quando disponveis):";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorBrazilian::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1445 of file translator_br.h.
    {
      return "Membros do Pacote";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorBrazilian::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1445 of file translator_br.h.
    {
      return "Membros do Pacote";
    }
trPackages() [1/2]
virtual QCString TranslatorBrazilian::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1188 of file translator_br.h.
    {
      return "Pacotes";
    }
trPackages() [2/2]
virtual QCString TranslatorBrazilian::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1188 of file translator_br.h.
    {
      return "Pacotes";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorBrazilian::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1434 of file translator_br.h.
    {
      return "Tipos do Pacote";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorBrazilian::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1434 of file translator_br.h.
    {
      return "Tipos do Pacote";
    }
trPage() [1/2]
virtual QCString TranslatorBrazilian::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1310 of file translator_br.h.
    {
      QCString result((first_capital ? "Pgina" : "pgina"));
      if (!singular) result+="s";
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorBrazilian::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1310 of file translator_br.h.
    {
      QCString result((first_capital ? "Pgina" : "pgina"));
      if (!singular) result+="s";
      return result;
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorBrazilian::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 857 of file translator_br.h.
    {
      // Decidi mudar de pgina para "p." para ficar mais compacto.
      return "p.";
    }
trPageAbbreviation() [2/2]
virtual QCString TranslatorBrazilian::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 857 of file translator_br.h.
    {
      // Decidi mudar de pgina para "p." para ficar mais compacto.
      return "p.";
    }
trPageIndex() [1/2]
virtual QCString TranslatorBrazilian::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 951 of file translator_br.h.
    {
      return "ndice da Pgina";
    }
trPageIndex() [2/2]
virtual QCString TranslatorBrazilian::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 951 of file translator_br.h.
    {
      return "ndice da Pgina";
    }
trPanelSynchronisationTooltip() [1/2]
virtual QCString TranslatorBrazilian::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1998 of file translator_br.h.
    {
      QCString opt = enable ? "ativar" : "desativar";
      return "clique para "+opt+" a sincronizao do painel";
    }
trPanelSynchronisationTooltip() [2/2]
virtual QCString TranslatorBrazilian::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1998 of file translator_br.h.
    {
      QCString opt = enable ? "ativar" : "desativar";
      return "clique para "+opt+" a sincronizao do painel";
    }
trParameters() [1/2]
virtual QCString TranslatorBrazilian::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 576 of file translator_br.h.
    { return "Parmetros"; }
trParameters() [2/2]
virtual QCString TranslatorBrazilian::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 576 of file translator_br.h.
    { return "Parmetros"; }
trPostcondition() [1/2]
virtual QCString TranslatorBrazilian::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 920 of file translator_br.h.
    {
      return "Ps-condio";
    }
trPostcondition() [2/2]
virtual QCString TranslatorBrazilian::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 920 of file translator_br.h.
    {
      return "Ps-condio";
    }
trPrecondition() [1/2]
virtual QCString TranslatorBrazilian::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 915 of file translator_br.h.
    {
      return "Pr-condio";
    }
trPrecondition() [2/2]
virtual QCString TranslatorBrazilian::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 915 of file translator_br.h.
    {
      return "Pr-condio";
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorBrazilian::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 999 of file translator_br.h.
    {
      return "Atributos Privados";
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorBrazilian::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 999 of file translator_br.h.
    {
      return "Atributos Privados";
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorBrazilian::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 700 of file translator_br.h.
    { return "Membros Privados"; }
trPrivateMembers() [2/2]
virtual QCString TranslatorBrazilian::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 700 of file translator_br.h.
    { return "Membros Privados"; }
trPrivateSlots() [1/2]
virtual QCString TranslatorBrazilian::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 703 of file translator_br.h.
    { return "Slots Privados"; }
trPrivateSlots() [2/2]
virtual QCString TranslatorBrazilian::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 703 of file translator_br.h.
    { return "Slots Privados"; }
trPrivateTypes() [1/2]
virtual QCString TranslatorBrazilian::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 995 of file translator_br.h.
    {
      return "Tipos Privados";
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorBrazilian::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 995 of file translator_br.h.
    {
      return "Tipos Privados";
    }
trProperties() [1/2]
virtual QCString TranslatorBrazilian::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1151 of file translator_br.h.
    {
      return "Propriedades";
    }
trProperties() [2/2]
virtual QCString TranslatorBrazilian::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1151 of file translator_br.h.
    {
      return "Propriedades";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1156 of file translator_br.h.
    {
      return "Propriedades";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1156 of file translator_br.h.
    {
      return "Propriedades";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorBrazilian::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 987 of file translator_br.h.
    {
      return "Atributos Protegidos";
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorBrazilian::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 987 of file translator_br.h.
    {
      return "Atributos Protegidos";
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorBrazilian::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 691 of file translator_br.h.
    { return "Membros Protegidos"; }
trProtectedMembers() [2/2]
virtual QCString TranslatorBrazilian::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 691 of file translator_br.h.
    { return "Membros Protegidos"; }
trProtectedSlots() [1/2]
virtual QCString TranslatorBrazilian::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 694 of file translator_br.h.
    { return "Slots Protegidos"; }
trProtectedSlots() [2/2]
virtual QCString TranslatorBrazilian::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 694 of file translator_br.h.
    { return "Slots Protegidos"; }
trProtectedTypes() [1/2]
virtual QCString TranslatorBrazilian::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 983 of file translator_br.h.
    {
      return "Tipos Protegidos";
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorBrazilian::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 983 of file translator_br.h.
    {
      return "Tipos Protegidos";
    }
trProvidedByCategory() [1/2]
virtual QCString TranslatorBrazilian::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 2008 of file translator_br.h.
    {
      return "Provido pela categoria @0.";
    }
trProvidedByCategory() [2/2]
virtual QCString TranslatorBrazilian::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 2008 of file translator_br.h.
    {
      return "Provido pela categoria @0.";
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorBrazilian::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 968 of file translator_br.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Campos de Dados";
      }
      else
      {
        return "Atributos Pblicos";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorBrazilian::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 968 of file translator_br.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Campos de Dados";
      }
      else
      {
        return "Atributos Pblicos";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorBrazilian::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 670 of file translator_br.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_JAVA))
      {
        return "Mtodos Pblicos";
      }
      else
      {
        return "Membros Pblicos";
      }
    }
References Config_getBool.
trPublicMembers() [2/2]
virtual QCString TranslatorBrazilian::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 670 of file translator_br.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_JAVA))
      {
        return "Mtodos Pblicos";
      }
      else
      {
        return "Membros Pblicos";
      }
    }
References Config_getBool.
trPublicSlots() [1/2]
virtual QCString TranslatorBrazilian::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 682 of file translator_br.h.
    { return "Slots Pblicos"; }
trPublicSlots() [2/2]
virtual QCString TranslatorBrazilian::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 682 of file translator_br.h.
    { return "Slots Pblicos"; }
trPublicTypes() [1/2]
virtual QCString TranslatorBrazilian::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 964 of file translator_br.h.
    {
      return "Tipos Pblicos";
    }
trPublicTypes() [2/2]
virtual QCString TranslatorBrazilian::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 964 of file translator_br.h.
    {
      return "Tipos Pblicos";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorBrazilian::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 1027 of file translator_br.h.
    {
      return "Referenciado(a) por";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorBrazilian::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 1027 of file translator_br.h.
    {
      return "Referenciado(a) por";
    }
trReferenceManual() [1/2]
virtual QCString TranslatorBrazilian::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 454 of file translator_br.h.
    { return "Guia de Referncia"; }
trReferenceManual() [2/2]
virtual QCString TranslatorBrazilian::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 454 of file translator_br.h.
    { return "Guia de Referncia"; }
trReferences() [1/2]
virtual QCString TranslatorBrazilian::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1362 of file translator_br.h.
    {
      return "Referencias";
    }
trReferences() [2/2]
virtual QCString TranslatorBrazilian::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1362 of file translator_br.h.
    {
      return "Referencias";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorBrazilian::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 753 of file translator_br.h.
    {
      return "Reimplementa "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorBrazilian::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 753 of file translator_br.h.
    {
      return "Reimplementa "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorBrazilian::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 761 of file translator_br.h.
    {
      return "Reimplementado por "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorBrazilian::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 761 of file translator_br.h.
    {
      return "Reimplementado por "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 617 of file translator_br.h.
    { return "Amigas e Funes Relacionadas"; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 617 of file translator_br.h.
    { return "Amigas e Funes Relacionadas"; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorBrazilian::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 109 of file translator_br.h.
    { return "Funes Relacionadas"; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorBrazilian::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 109 of file translator_br.h.
    { return "Funes Relacionadas"; }
trRelatedPages() [1/2]
virtual QCString TranslatorBrazilian::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 252 of file translator_br.h.
    { return "Pginas relacionadas"; }
trRelatedPages() [2/2]
virtual QCString TranslatorBrazilian::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 252 of file translator_br.h.
    { return "Pginas relacionadas"; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorBrazilian::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 367 of file translator_br.h.
    { return "Esta a lista de toda a documentao relacionadas:"; }
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorBrazilian::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 367 of file translator_br.h.
    { return "Esta a lista de toda a documentao relacionadas:"; }
trRelatedSubscript() [1/2]
virtual QCString TranslatorBrazilian::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 113 of file translator_br.h.
    { return "(Note que estas no so funes membros.)"; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorBrazilian::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 113 of file translator_br.h.
    { return "(Note que estas no so funes membros.)"; }
trRemarks() [1/2]
virtual QCString TranslatorBrazilian::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 1031 of file translator_br.h.
    {
      return "Anotaes";
    }
trRemarks() [2/2]
virtual QCString TranslatorBrazilian::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 1031 of file translator_br.h.
    {
      return "Anotaes";
    }
trReturns() [1/2]
virtual QCString TranslatorBrazilian::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 568 of file translator_br.h.
    { return "Retorna"; }
trReturns() [2/2]
virtual QCString TranslatorBrazilian::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 568 of file translator_br.h.
    { return "Retorna"; }
trReturnValues() [1/2]
virtual QCString TranslatorBrazilian::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 846 of file translator_br.h.
    { return "Valores Retornados"; }
trReturnValues() [2/2]
virtual QCString TranslatorBrazilian::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 846 of file translator_br.h.
    { return "Valores Retornados"; }
trRTFansicp() [1/2]
virtual QCString TranslatorBrazilian::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1242 of file translator_br.h.
    {
      return "1252";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorBrazilian::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1242 of file translator_br.h.
    {
      return "1252";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorBrazilian::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1251 of file translator_br.h.
    {
      return "0";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorBrazilian::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1251 of file translator_br.h.
    {
      return "0";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorBrazilian::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1257 of file translator_br.h.
    {
      return "Sumrio";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorBrazilian::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1257 of file translator_br.h.
    {
      return "Sumrio";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorBrazilian::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1394 of file translator_br.h.
    {
      return "Sumrio";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorBrazilian::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1394 of file translator_br.h.
    {
      return "Sumrio";
    }
trSearch() [1/2]
virtual QCString TranslatorBrazilian::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 260 of file translator_br.h.
    { return "Busca"; }
trSearch() [2/2]
virtual QCString TranslatorBrazilian::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 260 of file translator_br.h.
    { return "Busca"; }
trSearching() [1/2]
virtual QCString TranslatorBrazilian::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1845 of file translator_br.h.
    {
      return "Procurando...";
    }
trSearching() [2/2]
virtual QCString TranslatorBrazilian::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1845 of file translator_br.h.
    {
      return "Procurando...";
    }
trSearchMatches() [1/2]
virtual QCString TranslatorBrazilian::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1526 of file translator_br.h.
    {
      return "Resultados:";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorBrazilian::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1526 of file translator_br.h.
    {
      return "Resultados:";
    }
trSearchResults() [1/2]
virtual QCString TranslatorBrazilian::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1507 of file translator_br.h.
    {
      if (numDocuments==0)
      {
        return "Nenhum documento foi encontrado.";
      }
      else if (numDocuments==1)
      {
        return "Apenas <b>1</b> documento foi encontrado.";
      }
      else
      {
        return "<b>$num</b> documentos encontrados. "
               "Mostrando os melhores resultados primeiro.";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorBrazilian::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1507 of file translator_br.h.
    {
      if (numDocuments==0)
      {
        return "Nenhum documento foi encontrado.";
      }
      else if (numDocuments==1)
      {
        return "Apenas <b>1</b> documento foi encontrado.";
      }
      else
      {
        return "<b>$num</b> documentos encontrados. "
               "Mostrando os melhores resultados primeiro.";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorBrazilian::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1495 of file translator_br.h.
    {
      return "Resultado(s) da Busca";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorBrazilian::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1495 of file translator_br.h.
    {
      return "Resultado(s) da Busca";
    }
trSeeAlso() [1/2]
virtual QCString TranslatorBrazilian::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 572 of file translator_br.h.
    { return "Veja tambm"; }
trSeeAlso() [2/2]
virtual QCString TranslatorBrazilian::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 572 of file translator_br.h.
    { return "Veja tambm"; }
trSequenceDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trSequenceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2241 of file translator_br.h.
    {
        return "Sequncias";
    }
trSequenceDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trSequenceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2241 of file translator_br.h.
    {
        return "Sequncias";
    }
trSequences() [1/2]
virtual QCString TranslatorBrazilian::trSequences () [inline], [virtual]
Implements Translator.
Definition at line 2237 of file translator_br.h.
    {
        return "Sequncias";
    }
trSequences() [2/2]
virtual QCString TranslatorBrazilian::trSequences () [inline], [virtual]
Implements Translator.
Definition at line 2237 of file translator_br.h.
    {
        return "Sequncias";
    }
trServiceGeneratedFromFiles() [1/2]
virtual QCString TranslatorBrazilian::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 2085 of file translator_br.h.
    {
      // single is true implies a single file
      QCString result="A documentao para esse servio "
                                "foi gerada a partir ";
      if (single) {
        result+="do seguinte arquivo:";
      } else {
        result+="dos seguintes arquivos:";
      }
      return result;
    }
trServiceGeneratedFromFiles() [2/2]
virtual QCString TranslatorBrazilian::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 2085 of file translator_br.h.
    {
      // single is true implies a single file
      QCString result="A documentao para esse servio "
                                "foi gerada a partir ";
      if (single) {
        result+="do seguinte arquivo:";
      } else {
        result+="dos seguintes arquivos:";
      }
      return result;
    }
trServiceReference() [1/2]
virtual QCString TranslatorBrazilian::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 2069 of file translator_br.h.
    {
      QCString result = "Referncia do servio ";
      result += sName;
      return result;
    }
trServiceReference() [2/2]
virtual QCString TranslatorBrazilian::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 2069 of file translator_br.h.
    {
      QCString result = "Referncia do servio ";
      result += sName;
      return result;
    }
trServices() [1/2]
virtual QCString TranslatorBrazilian::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 2054 of file translator_br.h.
    { return "Servios Inclusos"; }
trServices() [2/2]
virtual QCString TranslatorBrazilian::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 2054 of file translator_br.h.
    { return "Servios Inclusos"; }
trSignals() [1/2]
virtual QCString TranslatorBrazilian::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 685 of file translator_br.h.
    { return "Sinais"; }
trSignals() [2/2]
virtual QCString TranslatorBrazilian::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 685 of file translator_br.h.
    { return "Sinais"; }
trSince() [1/2]
virtual QCString TranslatorBrazilian::trSince () [inline], [virtual]
Implements Translator.
Definition at line 1043 of file translator_br.h.
    {
      return "Desde";
    }
trSince() [2/2]
virtual QCString TranslatorBrazilian::trSince () [inline], [virtual]
Implements Translator.
Definition at line 1043 of file translator_br.h.
    {
      return "Desde";
    }
trSingletonGeneratedFromFiles() [1/2]
virtual QCString TranslatorBrazilian::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 2098 of file translator_br.h.
    {
      // single is true implies a single file
      QCString result="A documentao para esse <em>Singleton</em> "
                                "foi gerada a partir ";
      if (single) {
        result+="do seguinte arquivo:";
      } else {
        result+="dos: seguintes arquivos:";
      }
      return result;
    }
trSingletonGeneratedFromFiles() [2/2]
virtual QCString TranslatorBrazilian::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 2098 of file translator_br.h.
    {
      // single is true implies a single file
      QCString result="A documentao para esse <em>Singleton</em> "
                                "foi gerada a partir ";
      if (single) {
        result+="do seguinte arquivo:";
      } else {
        result+="dos: seguintes arquivos:";
      }
      return result;
    }
trSingletonReference() [1/2]
virtual QCString TranslatorBrazilian::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 2076 of file translator_br.h.
    {
      // TODO: Emerson Ferreira proposes to add emphasis around the word
      // Singleton but I'm not sure if this will work for non HTML generators.
      QCString result = "Referncia do Singleton ";
      result += sName;
      return result;
    }
trSingletonReference() [2/2]
virtual QCString TranslatorBrazilian::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 2076 of file translator_br.h.
    {
      // TODO: Emerson Ferreira proposes to add emphasis around the word
      // Singleton but I'm not sure if this will work for non HTML generators.
      QCString result = "Referncia do Singleton ";
      result += sName;
      return result;
    }
trSliceInterfaces() [1/2]
virtual QCString TranslatorBrazilian::trSliceInterfaces () [inline], [virtual]
Implements Translator.
Definition at line 2253 of file translator_br.h.
    {
        return "Interfaces";
    }
trSliceInterfaces() [2/2]
virtual QCString TranslatorBrazilian::trSliceInterfaces () [inline], [virtual]
Implements Translator.
Definition at line 2253 of file translator_br.h.
    {
        return "Interfaces";
    }
trSourceFile() [1/2]
virtual QCString TranslatorBrazilian::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1537 of file translator_br.h.
    {
      return "Cdigo-Fonte de " + filename;
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorBrazilian::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1537 of file translator_br.h.
    {
      return "Cdigo-Fonte de " + filename;
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorBrazilian::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1466 of file translator_br.h.
    {
      return "Atributos Estticos do Pacote";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorBrazilian::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1466 of file translator_br.h.
    {
      return "Atributos Estticos do Pacote";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorBrazilian::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1452 of file translator_br.h.
    {
      return "Funes Estticas do Pacote";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorBrazilian::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1452 of file translator_br.h.
    {
      return "Funes Estticas do Pacote";
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorBrazilian::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1003 of file translator_br.h.
    {
      return "Atributos Privados Estticos";
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorBrazilian::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1003 of file translator_br.h.
    {
      return "Atributos Privados Estticos";
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorBrazilian::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 706 of file translator_br.h.
    { return "Membros Privados Estticos"; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorBrazilian::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 706 of file translator_br.h.
    { return "Membros Privados Estticos"; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorBrazilian::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 991 of file translator_br.h.
    {
      return "Atributos Estticos Protegidos";
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorBrazilian::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 991 of file translator_br.h.
    {
      return "Atributos Estticos Protegidos";
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorBrazilian::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 697 of file translator_br.h.
    { return "Membros Protegidos Estticos"; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorBrazilian::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 697 of file translator_br.h.
    { return "Membros Protegidos Estticos"; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorBrazilian::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 979 of file translator_br.h.
    {
      return "Atributos Estticos Pblicos";
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorBrazilian::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 979 of file translator_br.h.
    {
      return "Atributos Estticos Pblicos";
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorBrazilian::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 688 of file translator_br.h.
    { return "Membros Pblicos Estticos"; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorBrazilian::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 688 of file translator_br.h.
    { return "Membros Pblicos Estticos"; }
trStructDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trStructDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2297 of file translator_br.h.
    {
        return "Estruturas";
    }
trStructDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trStructDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2297 of file translator_br.h.
    {
        return "Estruturas";
    }
trStructIndex() [1/2]
virtual QCString TranslatorBrazilian::trStructIndex () [inline], [virtual]
Implements Translator.
Definition at line 2285 of file translator_br.h.
    {
        return "ndice de Estruturas";
    }
trStructIndex() [2/2]
virtual QCString TranslatorBrazilian::trStructIndex () [inline], [virtual]
Implements Translator.
Definition at line 2285 of file translator_br.h.
    {
        return "ndice de Estruturas";
    }
trStructList() [1/2]
virtual QCString TranslatorBrazilian::trStructList () [inline], [virtual]
Implements Translator.
Definition at line 2289 of file translator_br.h.
    {
        return "Lista de Estruturas";
    }
trStructList() [2/2]
virtual QCString TranslatorBrazilian::trStructList () [inline], [virtual]
Implements Translator.
Definition at line 2289 of file translator_br.h.
    {
        return "Lista de Estruturas";
    }
trStructListDescription() [1/2]
virtual QCString TranslatorBrazilian::trStructListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2293 of file translator_br.h.
    {
        return "Estas so as estruturas com suas respectivas descries:";
    }
trStructListDescription() [2/2]
virtual QCString TranslatorBrazilian::trStructListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2293 of file translator_br.h.
    {
        return "Estas so as estruturas com suas respectivas descries:";
    }
trStructs() [1/2]
virtual QCString TranslatorBrazilian::trStructs () [inline], [virtual]
Implements Translator.
Definition at line 2281 of file translator_br.h.
    {
        return "Estruturas";
    }
trStructs() [2/2]
virtual QCString TranslatorBrazilian::trStructs () [inline], [virtual]
Implements Translator.
Definition at line 2281 of file translator_br.h.
    {
        return "Estruturas";
    }
trSubprogram() [1/2]
virtual QCString TranslatorBrazilian::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1809 of file translator_br.h.
    {
      QCString result((first_capital ? "Subrotina" : "subrotina"));
      if (!singular) result+="s";
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorBrazilian::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1809 of file translator_br.h.
    {
      QCString result((first_capital ? "Subrotina" : "subrotina"));
      if (!singular) result+="s";
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1673 of file translator_br.h.
    { return "Documentao da Funo/Subrotina"; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1673 of file translator_br.h.
    { return "Documentao da Funo/Subrotina"; }
trSubprograms() [1/2]
virtual QCString TranslatorBrazilian::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1667 of file translator_br.h.
    { return "Funes/Subrotinas"; }
trSubprograms() [2/2]
virtual QCString TranslatorBrazilian::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1667 of file translator_br.h.
    { return "Funes/Subrotinas"; }
trTemplateParameters() [1/2]
virtual QCString TranslatorBrazilian::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1955 of file translator_br.h.
    { return "Parmetros do <em>template</em>"; }
trTemplateParameters() [2/2]
virtual QCString TranslatorBrazilian::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1955 of file translator_br.h.
    { return "Parmetros do <em>template</em>"; }
trTest() [1/2]
virtual QCString TranslatorBrazilian::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1136 of file translator_br.h.
    {
      return "Teste";
    }
trTest() [2/2]
virtual QCString TranslatorBrazilian::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1136 of file translator_br.h.
    {
      return "Teste";
    }
trTestList() [1/2]
virtual QCString TranslatorBrazilian::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1141 of file translator_br.h.
    {
      return "Lista de Testes";
    }
trTestList() [2/2]
virtual QCString TranslatorBrazilian::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1141 of file translator_br.h.
    {
      return "Lista de Testes";
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorBrazilian::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 167 of file translator_br.h.
    { return "Esta a lista de todos os membros de "; }
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorBrazilian::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 167 of file translator_br.h.
    { return "Esta a lista de todos os membros de "; }
trTodo() [1/2]
virtual QCString TranslatorBrazilian::trTodo () [inline], [virtual]
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 1013 of file translator_br.h.
    {
      return "Atividades futuras";
    }
trTodo() [2/2]
virtual QCString TranslatorBrazilian::trTodo () [inline], [virtual]
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 1013 of file translator_br.h.
    {
      return "Atividades futuras";
    }
trTodoList() [1/2]
virtual QCString TranslatorBrazilian::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 1018 of file translator_br.h.
    {
      return "Lista de atividades futuras";
    }
trTodoList() [2/2]
virtual QCString TranslatorBrazilian::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 1018 of file translator_br.h.
    {
      return "Lista de atividades futuras";
    }
trType() [1/2]
virtual QCString TranslatorBrazilian::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1798 of file translator_br.h.
    {
      QCString result((first_capital ? "Tipo" : "tipo"));
      if (!singular) result+="s";
      return result;
    }
trType() [2/2]
virtual QCString TranslatorBrazilian::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1798 of file translator_br.h.
    {
      QCString result((first_capital ? "Tipo" : "tipo"));
      if (!singular) result+="s";
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorBrazilian::trTypeConstraints () [inline], [virtual]
C# Type Contraint list
Implements Translator.
Definition at line 1817 of file translator_br.h.
    {
      return "Restries do Tipo";
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorBrazilian::trTypeConstraints () [inline], [virtual]
C# Type Contraint list
Implements Translator.
Definition at line 1817 of file translator_br.h.
    {
      return "Restries do Tipo";
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 502 of file translator_br.h.
    { return "Definies dos tipos"; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 502 of file translator_br.h.
    { return "Definies dos tipos"; }
trTypedefs() [1/2]
virtual QCString TranslatorBrazilian::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 466 of file translator_br.h.
    { return "Definies de Tipos"; }
trTypedefs() [2/2]
virtual QCString TranslatorBrazilian::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 466 of file translator_br.h.
    { return "Definies de Tipos"; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1661 of file translator_br.h.
    { return "Documentao dos Tipos de Dados"; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1661 of file translator_br.h.
    { return "Documentao dos Tipos de Dados"; }
trVariableDocumentation() [1/2]
virtual QCString TranslatorBrazilian::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 520 of file translator_br.h.
    { return "Variveis"; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorBrazilian::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 520 of file translator_br.h.
    { return "Variveis"; }
trVariables() [1/2]
virtual QCString TranslatorBrazilian::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 484 of file translator_br.h.
    { return "Variveis"; }
trVariables() [2/2]
virtual QCString TranslatorBrazilian::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 484 of file translator_br.h.
    { return "Variveis"; }
trVersion() [1/2]
virtual QCString TranslatorBrazilian::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 560 of file translator_br.h.
    { return "Verso"; }
trVersion() [2/2]
virtual QCString TranslatorBrazilian::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 560 of file translator_br.h.
    { return "Verso"; }
trVhdlType() [1/2]
virtual QCString TranslatorBrazilian::trVhdlType (uint64 type, bool single) [inline], [virtual]
VHDL type
Implements Translator.
Definition at line 2140 of file translator_br.h.
    {
      switch(type)
      {
        case VhdlDocGen::LIBRARY:
          if (single) return "Biblioteca";
          else return "Bibliotecas";
        case VhdlDocGen::PACKAGE:
          if (single) return "Pacote";
          else return "Pacotes";
        case VhdlDocGen::SIGNAL:
          if (single) return "Sinal";
          else return "Sinais";
        case VhdlDocGen::COMPONENT:
          if (single) return "Componente";
          else return "Componentes";
        case VhdlDocGen::CONSTANT:
          if (single) return "Constante";
          else return "Constantes";
        case VhdlDocGen::ENTITY:
          if (single) return "Entidade";
          else return "Entidades";
        case VhdlDocGen::TYPE:
          if (single) return "Tipo";
          else return "Tipos";
        case VhdlDocGen::SUBTYPE:
          if (single) return "Subtipo";
          else return "Subtipos";
        case VhdlDocGen::FUNCTION:
          if (single) return "Funo";
          else return "Funes";
        case VhdlDocGen::RECORD:
          if (single) return "Registro";
          else return "Registros";
        case VhdlDocGen::PROCEDURE:
          if (single) return "Procedimento";
          else return "Procedimentos";
        case VhdlDocGen::ARCHITECTURE:
          if (single) return "Arquitetura";
          else return "Arquiteturas";
        case VhdlDocGen::ATTRIBUTE:
          if (single) return "Atributo";
          else return "Atributos";
        case VhdlDocGen::PROCESS:
          if (single) return "Processo";
          else return "Processos";
        case VhdlDocGen::PORT:
          if (single) return "Porta";
          else return "Portas";
        case VhdlDocGen::USE:
          if (single) return "clusula de uso";
          else return "clusulas de uso";
        case VhdlDocGen::GENERIC:
          if (single) return "Generico";
          else return "Genericos";
        case VhdlDocGen::PACKAGE_BODY:
          return "Corpo do Pacote";
        case VhdlDocGen::UNITS:
          return "Unidades";
        case VhdlDocGen::SHAREDVARIABLE:
          if (single) return "Varivel Compartilhada";
          else return "Variveis Compartilhadas";
        case VhdlDocGen::VFILE:
          if (single) return "Arquivo";
          else return "Arquivos";
        case VhdlDocGen::GROUP:
          if (single) return "Grupo";
          else return "Grupos";
        case VhdlDocGen::INSTANTIATION:
            if (single) return "Instncia";
            else return "Instncias";
        case VhdlDocGen::ALIAS:
          if (single) return "Apelido";
          else return "Apelidos";
        case VhdlDocGen::CONFIG:
          if (single) return "Configurao";
          else return "Configuraes";
        case VhdlDocGen::MISCELLANEOUS:
          return "Outros"; // Is this correct for VHDL?
        case VhdlDocGen::UCF_CONST:
          return "Restries";
        default:
          return "Classe";
      }
    }
References VhdlDocGen::ALIAS, VhdlDocGen::ARCHITECTURE, VhdlDocGen::ATTRIBUTE, VhdlDocGen::COMPONENT, VhdlDocGen::CONFIG, VhdlDocGen::CONSTANT, VhdlDocGen::ENTITY, VhdlDocGen::FUNCTION, VhdlDocGen::GENERIC, VhdlDocGen::GROUP, VhdlDocGen::INSTANTIATION, VhdlDocGen::LIBRARY, VhdlDocGen::MISCELLANEOUS, VhdlDocGen::PACKAGE, VhdlDocGen::PACKAGE_BODY, VhdlDocGen::PORT, VhdlDocGen::PROCEDURE, VhdlDocGen::PROCESS, VhdlDocGen::RECORD, VhdlDocGen::SHAREDVARIABLE, VhdlDocGen::SIGNAL, VhdlDocGen::SUBTYPE, VhdlDocGen::TYPE, VhdlDocGen::UCF_CONST, VhdlDocGen::UNITS, VhdlDocGen::USE, and VhdlDocGen::VFILE.
trVhdlType() [2/2]
virtual QCString TranslatorBrazilian::trVhdlType (uint64 type, bool single) [inline], [virtual]
VHDL type
Implements Translator.
Definition at line 2140 of file translator_br.h.
    {
      switch(type)
      {
        case VhdlDocGen::LIBRARY:
          if (single) return "Biblioteca";
          else return "Bibliotecas";
        case VhdlDocGen::PACKAGE:
          if (single) return "Pacote";
          else return "Pacotes";
        case VhdlDocGen::SIGNAL:
          if (single) return "Sinal";
          else return "Sinais";
        case VhdlDocGen::COMPONENT:
          if (single) return "Componente";
          else return "Componentes";
        case VhdlDocGen::CONSTANT:
          if (single) return "Constante";
          else return "Constantes";
        case VhdlDocGen::ENTITY:
          if (single) return "Entidade";
          else return "Entidades";
        case VhdlDocGen::TYPE:
          if (single) return "Tipo";
          else return "Tipos";
        case VhdlDocGen::SUBTYPE:
          if (single) return "Subtipo";
          else return "Subtipos";
        case VhdlDocGen::FUNCTION:
          if (single) return "Funo";
          else return "Funes";
        case VhdlDocGen::RECORD:
          if (single) return "Registro";
          else return "Registros";
        case VhdlDocGen::PROCEDURE:
          if (single) return "Procedimento";
          else return "Procedimentos";
        case VhdlDocGen::ARCHITECTURE:
          if (single) return "Arquitetura";
          else return "Arquiteturas";
        case VhdlDocGen::ATTRIBUTE:
          if (single) return "Atributo";
          else return "Atributos";
        case VhdlDocGen::PROCESS:
          if (single) return "Processo";
          else return "Processos";
        case VhdlDocGen::PORT:
          if (single) return "Porta";
          else return "Portas";
        case VhdlDocGen::USE:
          if (single) return "clusula de uso";
          else return "clusulas de uso";
        case VhdlDocGen::GENERIC:
          if (single) return "Generico";
          else return "Genericos";
        case VhdlDocGen::PACKAGE_BODY:
          return "Corpo do Pacote";
        case VhdlDocGen::UNITS:
          return "Unidades";
        case VhdlDocGen::SHAREDVARIABLE:
          if (single) return "Varivel Compartilhada";
          else return "Variveis Compartilhadas";
        case VhdlDocGen::VFILE:
          if (single) return "Arquivo";
          else return "Arquivos";
        case VhdlDocGen::GROUP:
          if (single) return "Grupo";
          else return "Grupos";
        case VhdlDocGen::INSTANTIATION:
            if (single) return "Instncia";
            else return "Instncias";
        case VhdlDocGen::ALIAS:
          if (single) return "Apelido";
          else return "Apelidos";
        case VhdlDocGen::CONFIG:
          if (single) return "Configurao";
          else return "Configuraes";
        case VhdlDocGen::MISCELLANEOUS:
          return "Outros"; // Is this correct for VHDL?
        case VhdlDocGen::UCF_CONST:
          return "Restries";
        default:
          return "Classe";
      }
    }
References VhdlDocGen::ALIAS, VhdlDocGen::ARCHITECTURE, VhdlDocGen::ATTRIBUTE, VhdlDocGen::COMPONENT, VhdlDocGen::CONFIG, VhdlDocGen::CONSTANT, VhdlDocGen::ENTITY, VhdlDocGen::FUNCTION, VhdlDocGen::GENERIC, VhdlDocGen::GROUP, VhdlDocGen::INSTANTIATION, VhdlDocGen::LIBRARY, VhdlDocGen::MISCELLANEOUS, VhdlDocGen::PACKAGE, VhdlDocGen::PACKAGE_BODY, VhdlDocGen::PORT, VhdlDocGen::PROCEDURE, VhdlDocGen::PROCESS, VhdlDocGen::RECORD, VhdlDocGen::SHAREDVARIABLE, VhdlDocGen::SIGNAL, VhdlDocGen::SUBTYPE, VhdlDocGen::TYPE, VhdlDocGen::UCF_CONST, VhdlDocGen::UNITS, VhdlDocGen::USE, and VhdlDocGen::VFILE.
trWarning() [1/2]
virtual QCString TranslatorBrazilian::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 556 of file translator_br.h.
    { return "Aviso"; }
trWarning() [2/2]
virtual QCString TranslatorBrazilian::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 556 of file translator_br.h.
    { return "Aviso"; }
trWriteList() [1/2]
virtual QCString TranslatorBrazilian::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 712 of file translator_br.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" e ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorBrazilian::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 712 of file translator_br.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" e ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_br.h
doxygen/src/translator_br.h