FTVHelp Class Reference
#include <ftvhelp.h>
Classes
struct Private
Public Member Functions
FTVHelp (bool LTI)
~FTVHelp ()
FTVHelp (FTVHelp &&)
void initialize ()
void finalize ()
void incContentsDepth ()
void decContentsDepth ()
void addContentsItem (bool isDir, const QCString &name, const QCString &ref, const QCString &file, const QCString &anchor, bool separateIndex, bool addToNavIndex, const Definition *def)
void addIndexItem (const Definition *, const MemberDef *, const QCString &, const QCString &)
void addIndexFile (const QCString &)
void addImageFile (const QCString &)
void addStyleSheetFile (const QCString &)
void generateTreeView ()
void generateTreeViewInline (TextStream &t)
void generateTreeViewScripts ()
FTVHelp (bool LTI)
~FTVHelp ()
FTVHelp (FTVHelp &&)
void initialize ()
void finalize ()
void incContentsDepth ()
void decContentsDepth ()
void addContentsItem (bool isDir, const QCString &name, const QCString &ref, const QCString &file, const QCString &anchor, bool separateIndex, bool addToNavIndex, const Definition *def)
void addIndexItem (const Definition *, const MemberDef *, const QCString &, const QCString &)
void addIndexFile (const QCString &)
void addImageFile (const QCString &)
void addStyleSheetFile (const QCString &)
void generateTreeView ()
void generateTreeViewInline (TextStream &t)
void generateTreeViewScripts ()
Static Public Member Functions
static void generateTreeViewImages ()
static void generateTreeViewImages ()
Private Attributes
std::unique_ptr< Private > p
Detailed Description
A class that generates a dynamic tree view side panel.
Definition at line 38 of file ftvhelp.h.
Constructor & Destructor Documentation
FTVHelp() [1/4]
FTVHelp::FTVHelp (bool TLI)
Constructs an ftv help object. The object has to be initialized before it can be used.
Definition at line 142 of file ftvhelp.cpp.
: p(std::make_unique<Private>(TLI)) {}
 FTVHelp() [1/2]
FTVHelp::~FTVHelp () [default]
FTVHelp() [2/4]
FTVHelp::FTVHelp (FTVHelp &&) [default]
FTVHelp() [3/4]
FTVHelp::FTVHelp (bool LTI)
 FTVHelp() [2/2]
FTVHelp::~FTVHelp ()
FTVHelp() [4/4]
FTVHelp::FTVHelp (FTVHelp &&)
Member Function Documentation
addContentsItem() [1/2]
void FTVHelp::addContentsItem (bool isDir, const QCString & name, const QCString & ref, const QCString & file, const QCString & anchor, bool separateIndex, bool addToNavIndex, const Definition * def)
Add a list item to the contents file.
Parameters
isDir TRUE if the item is a directory, FALSE if it is a text
name the name of the item.
ref the URL of to the item.
file the file containing the definition of the item
anchor the anchor within the file.
separateIndex put the entries in a separate index file
addToNavIndex add this entry to the quick navigation index
def Definition corresponding to this entry
Definition at line 208 of file ftvhelp.cpp.
{
  //printf("%p: p->indent=%d addContentsItem(%s,%s,%s,%s)\n",this,p->indent,name,ref,file,anchor);
  auto &nl = p->indentNodes[p->indent];
  if (!nl.empty())
  {
    nl.back()->isLast=FALSE;
  }
  auto newNode = std::make_shared<FTVNode>(isDir,ref,file,anchor,name,separateIndex,addToNavIndex,def);
  nl.push_back(newNode);
  newNode->index = static_cast<int>(nl.size()-1);
  if (p->indent>0)
  {
    auto &pnl = p->indentNodes[p->indent-1];
    if (!pnl.empty())
    {
      newNode->parent = pnl.back();
    }
  }
}
References FALSE, caseconvert::file, setup::name, and p.
Referenced by writeClassTree(), writeClassTreeForList(), writeClassTreeInsideNamespaceElement(), writeClassTreeToOutput(), writeConceptList(), writeConceptRootList(), writeConceptTreeInsideNamespaceElement(), writeDirHierarchy(), writeDirTreeNode(), writeGroupTreeNode(), writeNamespaceTreeElement(), and writePages().
addContentsItem() [2/2]
void FTVHelp::addContentsItem (bool isDir, const QCString & name, const QCString & ref, const QCString & file, const QCString & anchor, bool separateIndex, bool addToNavIndex, const Definition * def)
addImageFile() [1/2]
void FTVHelp::addImageFile (const QCString &) [inline]
Definition at line 58 of file ftvhelp.h.
{}
addImageFile() [2/2]
void FTVHelp::addImageFile (const QCString &) [inline]
Definition at line 58 of file ftvhelp.h.
{}
addIndexFile() [1/2]
void FTVHelp::addIndexFile (const QCString &) [inline]
Definition at line 57 of file ftvhelp.h.
{}
addIndexFile() [2/2]
void FTVHelp::addIndexFile (const QCString &) [inline]
Definition at line 57 of file ftvhelp.h.
{}
addIndexItem() [1/2]
void FTVHelp::addIndexItem (const Definition * , const MemberDef * , const QCString & , const QCString &) [inline]
Definition at line 56 of file ftvhelp.h.
{}
addIndexItem() [2/2]
void FTVHelp::addIndexItem (const Definition * , const MemberDef * , const QCString & , const QCString &) [inline]
Definition at line 56 of file ftvhelp.h.
{}
addStyleSheetFile() [1/2]
void FTVHelp::addStyleSheetFile (const QCString &) [inline]
Definition at line 59 of file ftvhelp.h.
{}
addStyleSheetFile() [2/2]
void FTVHelp::addStyleSheetFile (const QCString &) [inline]
Definition at line 59 of file ftvhelp.h.
{}
decContentsDepth() [1/2]
void FTVHelp::decContentsDepth ()
Decrease the level of the contents hierarchy. This will end the current sublist.
See also
incContentsDepth()
Definition at line 177 of file ftvhelp.cpp.
{
  //printf("%p: decContentsDepth() indent=%d\n",this,p->indent);
  ASSERT(p->indent>0);
  if (p->indent>0)
  {
    p->indent--;
    auto &nl = p->indentNodes[p->indent];
    if (!nl.empty())
    {
      auto &parent = nl.back();
      auto &children = p->indentNodes[p->indent+1];
      for (const auto &child : children)
      {
        parent->children.push_back(child);
      }
      children.clear();
    }
  }
}
References ASSERT, p, and parent().
Referenced by writeClassTree(), writeClassTreeInsideNamespaceElement(), writeClassTreeToOutput(), writeConceptTreeInsideNamespaceElement(), writeDirTreeNode(), writeGroupTreeNode(), writeNamespaceTreeElement(), and writePages().
decContentsDepth() [2/2]
void FTVHelp::decContentsDepth ()
finalize() [1/2]
void FTVHelp::finalize ()
Finalizes the FTV help. This will finish and close the contents file (index.js).
See also
initialize()
Definition at line 157 of file ftvhelp.cpp.
{
  generateTreeView();
}
References generateTreeView().
finalize() [2/2]
void FTVHelp::finalize ()
generateTreeView() [1/2]
void FTVHelp::generateTreeView ()
Definition at line 873 of file ftvhelp.cpp.
{
  generateTreeViewImages();
  generateTreeViewScripts();
}
References generateTreeViewImages(), and generateTreeViewScripts().
Referenced by finalize().
generateTreeView() [2/2]
void FTVHelp::generateTreeView ()
generateTreeViewImages() [1/2]
void FTVHelp::generateTreeViewImages () [static]
Definition at line 771 of file ftvhelp.cpp.
{
  QCString dname=Config_getString(HTML_OUTPUT);
  const ResourceMgr &rm = ResourceMgr::instance();
  rm.copyResource("doc.luma",dname);
  rm.copyResource("docd.luma",dname);
  rm.copyResource("folderopen.luma",dname);
  rm.copyResource("folderclosed.luma",dname);
  rm.copyResource("splitbar.lum",dname);
  rm.copyResource("splitbard.lum",dname);
}
References Config_getString, ResourceMgr::copyResource(), and ResourceMgr::instance().
Referenced by generateOutput(), and generateTreeView().
generateTreeViewImages() [2/2]
static void FTVHelp::generateTreeViewImages () [static]
generateTreeViewInline() [1/2]
void FTVHelp::generateTreeViewInline (TextStream & t)
Definition at line 812 of file ftvhelp.cpp.
{
  int preferredNumEntries = Config_getInt(HTML_INDEX_NUM_ENTRIES);
  t << "<div class=\"directory\">\n";
  int d=1, depth=1;
  for (const auto &n : p->indentNodes[0])
  {
    if (!n->children.empty())
    {
      d = n->computeTreeDepth(2);
      if (d>depth) depth=d;
    }
  }
  int preferredDepth = depth;
  // write level selector
  if (depth>1)
  {
    t << "<div class=\"levels\">[";
    t << theTranslator->trDetailLevel();
    t << " ";
    for (int i=1;i<=depth;i++)
    {
      t << "<span onclick=\"javascript:toggleLevel(" << i << ");\">" << i << "</span>";
    }
    t << "]</div>";
    if (preferredNumEntries>0)
    {
      preferredDepth=1;
      for (int i=1;i<=depth;i++)
      {
        int num=0;
        for (const auto &n : p->indentNodes[0])
        {
          num+=n->numNodesAtLevel(0,i);
        }
        if (num<=preferredNumEntries)
        {
          preferredDepth=i;
        }
        else
        {
          break;
        }
      }
    }
  }
  //printf("preferred depth=%d\n",preferredDepth);
  if (!p->indentNodes[0].empty())
  {
    t << "<table class=\"directory\">\n";
    int index=0;
    p->generateTree(t,p->indentNodes[0],0,preferredDepth,index);
    t << "</table>\n";
  }
  t << "</div><!-- directory -->\n";
}
References Config_getInt, n, p, theTranslator, and Translator::trDetailLevel().
Referenced by writeAnnotatedIndexGeneric(), writeConceptIndex(), writeFileIndex(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), writeNamespaceIndex(), and writePageIndex().
generateTreeViewInline() [2/2]
void FTVHelp::generateTreeViewInline (TextStream & t)
generateTreeViewScripts() [1/2]
void FTVHelp::generateTreeViewScripts ()
Definition at line 784 of file ftvhelp.cpp.
{
  QCString htmlOutput = Config_getString(HTML_OUTPUT);
  // generate navtree.js & navtreeindex.js
  generateJSNavTree(p->indentNodes[0]);
  // copy resize.js & navtree.css
  auto &mgr = ResourceMgr::instance();
  {
    std::ofstream f(htmlOutput.str()+"/resize.js",std::ofstream::out | std::ofstream::binary);
    if (f.is_open())
    {
      TextStream t(&f);
      t << substitute(mgr.getAsString("resize.js"), "$TREEVIEW_WIDTH", QCString().setNum(Config_getInt(TREEVIEW_WIDTH)));
    }
  }
  {
    std::ofstream f(htmlOutput.str()+"/navtree.css",std::ofstream::out | std::ofstream::binary);
    if (f.is_open())
    {
      TextStream t(&f);
      t << HtmlGenerator::getNavTreeCss();
    }
  }
}
References Config_getInt, Config_getString, f, generateJSNavTree(), HtmlGenerator::getNavTreeCss(), ResourceMgr::instance(), out, p, QCString::str(), and substitute().
Referenced by generateTreeView().
generateTreeViewScripts() [2/2]
void FTVHelp::generateTreeViewScripts ()
incContentsDepth() [1/2]
void FTVHelp::incContentsDepth ()
Increase the level of the contents hierarchy. This will start a new sublist in contents file.
See also
decContentsDepth()
Definition at line 166 of file ftvhelp.cpp.
{
  //printf("%p: incContentsDepth() indent=%d\n",this,p->indent);
  p->indent++;
  p->indentNodes.resize(p->indent+1);
}
References p.
Referenced by writeClassTree(), writeClassTreeInsideNamespaceElement(), writeClassTreeToOutput(), writeConceptTreeInsideNamespaceElement(), writeDirTreeNode(), writeGroupTreeNode(), writeNamespaceTreeElement(), and writePages().
incContentsDepth() [2/2]
void FTVHelp::incContentsDepth ()
initialize() [1/2]
void FTVHelp::initialize ()
This will create a folder tree view table of contents file (tree.js).
See also
finalize()
Definition at line 149 of file ftvhelp.cpp.
{
}
initialize() [2/2]
void FTVHelp::initialize ()
Member Data Documentation
p
std::unique_ptr< Private > FTVHelp::p [private]
Definition at line 66 of file ftvhelp.h.
Referenced by addContentsItem(), decContentsDepth(), generateTreeViewInline(), generateTreeViewScripts(), and incContentsDepth().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/ftvhelp.h
doxygen/src/ftvhelp.h
doxygen/build/doxygen/src/ftvhelp.cpp
doxygen/src/ftvhelp.cpp