MemberContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const QCString &name) const
virtual StringVector fields () const
MemberContext (const MemberDef *)
virtual ~MemberContext ()
virtual TemplateVariant get (const QCString &name) const
virtual StringVector fields () const
MemberContext (const MemberDef *)
virtual ~MemberContext ()
Static Public Member Functions
static TemplateStructIntfPtr alloc (const MemberDef *md)
static TemplateStructIntfPtr alloc (const MemberDef *md)
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Definition at line 317 of file context.h.
Constructor & Destructor Documentation
MemberContext() [1/2]
MemberContext::MemberContext (const MemberDef * md)
Definition at line 4410 of file context.cpp.
                                                : p(std::make_unique<Private>(md))
{
}
 MemberContext() [1/2]
MemberContext::~MemberContext () [virtual]
Definition at line 4414 of file context.cpp.
{
}
MemberContext() [2/2]
MemberContext::MemberContext (const MemberDef *)
 MemberContext() [2/2]
virtual MemberContext::~MemberContext () [virtual]
Member Function Documentation
alloc() [1/2]
static TemplateStructIntfPtr MemberContext::alloc (const MemberDef * md) [inline], [static]
Definition at line 320 of file context.h.
    { return std::static_pointer_cast<TemplateStructIntf>(std::make_shared<MemberContext>(md)); }
Referenced by MemberListContext::Private::addMember(), MemberContext::Private::createAnonymousMember(), MemberContext::Private::createCategoryRelation(), MemberContext::Private::createImplementedBy(), MemberContext::Private::createImplements(), NestingNodeContext::Private::createMember(), MemberInfoContext::Private::createMember(), GlobalsIndexContext::Private::createMembersFiltered(), ClassMembersIndexContext::Private::createMembersFiltered(), NamespaceMembersIndexContext::Private::createMembersFiltered(), MemberContext::Private::createReimplementedBy(), and MemberContext::Private::createReimplements().
alloc() [2/2]
static TemplateStructIntfPtr MemberContext::alloc (const MemberDef * md) [inline], [static]
Definition at line 320 of file context.h.
    { return std::static_pointer_cast<TemplateStructIntf>(std::make_shared<MemberContext>(md)); }
fields() [1/2]
StringVector MemberContext::fields () const [virtual]
Return the list of fields.
Implements TemplateStructIntf.
Definition at line 4423 of file context.cpp.
{
  return p->fields();
}
References p.
fields() [2/2]
virtual StringVector MemberContext::fields () const [virtual]
Return the list of fields.
Implements TemplateStructIntf.
get() [1/2]
TemplateVariant MemberContext::get (const QCString & name) const [virtual]
Gets the value for a field name.
Parameters
 in name The name of the field.
Implements TemplateStructIntf.
Definition at line 4418 of file context.cpp.
{
  return p->get(n);
}
References n, and p.
get() [2/2]
virtual TemplateVariant MemberContext::get (const QCString & name) const [virtual]
Gets the value for a field name.
Parameters
 in name The name of the field.
Implements TemplateStructIntf.
Member Data Documentation
p
std::unique_ptr< Private > MemberContext::p [private]
Definition at line 332 of file context.h.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.h
doxygen/src/context.h
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp