DocbookCodeGenerator Class Reference
#include <docbookgen.h>
Public Member Functions
DocbookCodeGenerator (TextStream &t)
void setRelativePath (const QCString &path)
void setSourceFileName (const QCString &sourceFileName)
QCString sourceFileName ()
void codify (const QCString &text)
void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip)
void writeCodeLinkLine (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip, bool)
void writeTooltip (const QCString &, const DocLinkInfo &, const QCString &, const QCString &, const SourceLinkInfo &, const SourceLinkInfo &)
void startCodeLine (bool)
void endCodeLine ()
void startFontClass (const QCString &colorClass)
void endFontClass ()
void writeCodeAnchor (const QCString &)
void writeLineNumber (const QCString &extRef, const QCString &compId, const QCString &anchorId, int l, bool writeLineAnchor)
void finish ()
void startCodeFragment (const QCString &style)
void endCodeFragment (const QCString &style)
DocbookCodeGenerator (TextStream &t)
void setRelativePath (const QCString &path)
void setSourceFileName (const QCString &sourceFileName)
QCString sourceFileName ()
void codify (const QCString &text)
void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip)
void writeCodeLinkLine (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip, bool)
void writeTooltip (const QCString &, const DocLinkInfo &, const QCString &, const QCString &, const SourceLinkInfo &, const SourceLinkInfo &)
void startCodeLine (bool)
void endCodeLine ()
void startFontClass (const QCString &colorClass)
void endFontClass ()
void writeCodeAnchor (const QCString &)
void writeLineNumber (const QCString &extRef, const QCString &compId, const QCString &anchorId, int l, bool writeLineAnchor)
void finish ()
void startCodeFragment (const QCString &style)
void endCodeFragment (const QCString &style)
Private Attributes
TextStream & m_t
QCString m_refId
QCString m_external
int m_lineNumber = -1
int m_col = 0
bool m_insideCodeLine = false
bool m_insideSpecialHL = false
QCString m_relPath
QCString m_sourceFileName
Detailed Description
Definition at line 23 of file docbookgen.h.
Constructor & Destructor Documentation
DocbookCodeGenerator() [1/2]
DocbookCodeGenerator::DocbookCodeGenerator (TextStream & t)
Definition at line 146 of file docbookgen.cpp.
                                                        : m_t(t)
{
}
DocbookCodeGenerator() [2/2]
DocbookCodeGenerator::DocbookCodeGenerator (TextStream & t)
Member Function Documentation
codify() [1/2]
void DocbookCodeGenerator::codify (const QCString & s) [virtual]
Writes an code fragment to the output. This function should keep spaces visible, should break lines at a newline and should convert tabs to the right number of spaces.
Implements CodeOutputInterface.
Definition at line 150 of file docbookgen.cpp.
{
  Docbook_DB(("(codify \"%s\")\n",text));
  writeDocbookCodeString(m_t,text,m_col);
}
References Docbook_DB, m_col, m_t, and writeDocbookCodeString().
Referenced by DocbookGenerator::codify(), and writeLineNumber().
codify() [2/2]
void DocbookCodeGenerator::codify (const QCString & s) [virtual]
Writes an code fragment to the output. This function should keep spaces visible, should break lines at a newline and should convert tabs to the right number of spaces.
Implements CodeOutputInterface.
endCodeFragment() [1/2]
void DocbookCodeGenerator::endCodeFragment (const QCString & style) [virtual]
Ends a block of code
Implements CodeOutputInterface.
Definition at line 265 of file docbookgen.cpp.
{
DB_GEN_C1(m_t)
  //endCodeLine checks is there is still an open code line, if so closes it.
  endCodeLine();
  m_t << "</programlisting>";
}
References DB_GEN_C1, endCodeLine(), and m_t.
Referenced by DocbookGenerator::endCodeFragment().
endCodeFragment() [2/2]
void DocbookCodeGenerator::endCodeFragment (const QCString & style) [virtual]
Ends a block of code
Implements CodeOutputInterface.
endCodeLine() [1/2]
void DocbookCodeGenerator::endCodeLine () [virtual]
Ends a line of code started with startCodeLine()
Implements CodeOutputInterface.
Definition at line 194 of file docbookgen.cpp.
{
  if (m_insideCodeLine) m_t << "\n";
  Docbook_DB(("(endCodeLine)\n"));
  m_lineNumber = -1;
  m_refId.resize(0);
  m_external.resize(0);
  m_insideCodeLine=FALSE;
}
References Docbook_DB, FALSE, m_external, m_insideCodeLine, m_lineNumber, m_refId, m_t, and QCString::resize().
Referenced by endCodeFragment(), DocbookGenerator::endCodeLine(), and finish().
endCodeLine() [2/2]
void DocbookCodeGenerator::endCodeLine () [virtual]
Ends a line of code started with startCodeLine()
Implements CodeOutputInterface.
endFontClass() [1/2]
void DocbookCodeGenerator::endFontClass () [virtual]
Ends a block started with startFontClass()
Implements CodeOutputInterface.
Definition at line 211 of file docbookgen.cpp.
{
  Docbook_DB(("(endFontClass)\n"));
  m_t << "</emphasis>"; // non DocBook
  m_insideSpecialHL=FALSE;
}
References Docbook_DB, FALSE, m_insideSpecialHL, and m_t.
Referenced by DocbookGenerator::endFontClass().
endFontClass() [2/2]
void DocbookCodeGenerator::endFontClass () [virtual]
Ends a block started with startFontClass()
Implements CodeOutputInterface.
finish() [1/2]
void DocbookCodeGenerator::finish ()
Definition at line 254 of file docbookgen.cpp.
{
  endCodeLine();
}
References endCodeLine().
finish() [2/2]
void DocbookCodeGenerator::finish ()
setRelativePath() [1/2]
void DocbookCodeGenerator::setRelativePath (const QCString & path) [inline]
Definition at line 27 of file docbookgen.h.
{ m_relPath = path; }
References m_relPath.
Referenced by DocbookGenerator::startFile().
setRelativePath() [2/2]
void DocbookCodeGenerator::setRelativePath (const QCString & path) [inline]
Definition at line 27 of file docbookgen.h.
{ m_relPath = path; }
References m_relPath.
setSourceFileName() [1/2]
void DocbookCodeGenerator::setSourceFileName (const QCString & sourceFileName) [inline]
Definition at line 28 of file docbookgen.h.
{ m_sourceFileName = sourceFileName; }
References m_sourceFileName, and sourceFileName().
Referenced by DocbookGenerator::endFile(), and DocbookGenerator::startFile().
setSourceFileName() [2/2]
void DocbookCodeGenerator::setSourceFileName (const QCString & sourceFileName) [inline]
Definition at line 28 of file docbookgen.h.
{ m_sourceFileName = sourceFileName; }
References m_sourceFileName, and sourceFileName().
sourceFileName() [1/2]
QCString DocbookCodeGenerator::sourceFileName () [inline]
Definition at line 29 of file docbookgen.h.
{ return m_sourceFileName; }
References m_sourceFileName.
Referenced by DocbookGenerator::endFile(), and setSourceFileName().
sourceFileName() [2/2]
QCString DocbookCodeGenerator::sourceFileName () [inline]
Definition at line 29 of file docbookgen.h.
{ return m_sourceFileName; }
References m_sourceFileName.
startCodeFragment() [1/2]
void DocbookCodeGenerator::startCodeFragment (const QCString & style) [virtual]
Starts a source code fragment. The fragment will be fed to the code parser (see code.h) for syntax highlighting and cross-referencing. The fragment ends by a call to endCodeFragment()
Parameters
style The kind of code fragment.
Implements CodeOutputInterface.
Definition at line 259 of file docbookgen.cpp.
{
DB_GEN_C1(m_t)
  m_t << "<programlisting linenumbering=\"unnumbered\">";
}
References DB_GEN_C1, and m_t.
Referenced by DocbookGenerator::startCodeFragment().
startCodeFragment() [2/2]
void DocbookCodeGenerator::startCodeFragment (const QCString & style) [virtual]
Starts a source code fragment. The fragment will be fed to the code parser (see code.h) for syntax highlighting and cross-referencing. The fragment ends by a call to endCodeFragment()
Parameters
style The kind of code fragment.
Implements CodeOutputInterface.
startCodeLine() [1/2]
void DocbookCodeGenerator::startCodeLine (bool) [virtual]
Implements CodeOutputInterface.
Definition at line 187 of file docbookgen.cpp.
{
  Docbook_DB(("(startCodeLine)\n"));
  m_insideCodeLine=TRUE;
  m_col=0;
}
References Docbook_DB, m_col, m_insideCodeLine, and TRUE.
Referenced by DocbookGenerator::startCodeLine().
startCodeLine() [2/2]
void DocbookCodeGenerator::startCodeLine (bool) [virtual]
Implements CodeOutputInterface.
startFontClass() [1/2]
void DocbookCodeGenerator::startFontClass (const QCString & clsName) [virtual]
Starts a block with a certain meaning. Used for syntax highlighting, which elements of the same type are rendered using the same 'font class'.
Parameters
clsName The category name.
Implements CodeOutputInterface.
Definition at line 204 of file docbookgen.cpp.
{
  Docbook_DB(("(startFontClass)\n"));
  m_t << "<emphasis role=\"" << colorClass << "\">";
  m_insideSpecialHL=TRUE;
}
References Docbook_DB, m_insideSpecialHL, m_t, and TRUE.
Referenced by DocbookGenerator::startFontClass().
startFontClass() [2/2]
void DocbookCodeGenerator::startFontClass (const QCString & clsName) [virtual]
Starts a block with a certain meaning. Used for syntax highlighting, which elements of the same type are rendered using the same 'font class'.
Parameters
clsName The category name.
Implements CodeOutputInterface.
writeCodeAnchor() [1/2]
void DocbookCodeGenerator::writeCodeAnchor (const QCString & name) [virtual]
Write an anchor to a source listing.
Parameters
name The name of the anchor.
Implements CodeOutputInterface.
Definition at line 218 of file docbookgen.cpp.
{
  Docbook_DB(("(writeCodeAnchor)\n"));
}
References Docbook_DB.
Referenced by DocbookGenerator::writeCodeAnchor().
writeCodeAnchor() [2/2]
void DocbookCodeGenerator::writeCodeAnchor (const QCString & name) [virtual]
Write an anchor to a source listing.
Parameters
name The name of the anchor.
Implements CodeOutputInterface.
writeCodeLink() [1/2]
void DocbookCodeGenerator::writeCodeLink (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) [virtual]
Writes a link to an object in a code fragment.
Parameters
type The type of symbol, used for semantic syntax highlighting, may be Default is no info is available.
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
tooltip The tooltip to display when the mouse is on the link.
Implements CodeOutputInterface.
Definition at line 156 of file docbookgen.cpp.
{
  Docbook_DB(("(writeCodeLink)\n"));
  writeDocbookLink(m_t,ref,file,anchor,name,tooltip);
  m_col+=name.length();
}
References Docbook_DB, caseconvert::file, m_col, m_t, setup::name, and writeDocbookLink().
Referenced by DocbookGenerator::writeCodeLink(), and writeLineNumber().
writeCodeLink() [2/2]
void DocbookCodeGenerator::writeCodeLink (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) [virtual]
Writes a link to an object in a code fragment.
Parameters
type The type of symbol, used for semantic syntax highlighting, may be Default is no info is available.
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
tooltip The tooltip to display when the mouse is on the link.
Implements CodeOutputInterface.
writeCodeLinkLine() [1/2]
void DocbookCodeGenerator::writeCodeLinkLine (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip, bool writeLineAnchor)
Definition at line 166 of file docbookgen.cpp.
{
  Docbook_DB(("(writeCodeLinkLine)\n"));
  if (!writeLineAnchor) return;
  m_t << "<anchor xml:id=\"_" << stripExtensionGeneral(stripPath(file),".xml");
  m_t << "_1l";
  writeDocbookString(m_t,name);
  m_t << "\"/>";
  m_col+=name.length();
}
References Docbook_DB, caseconvert::file, m_col, m_t, setup::name, stripExtensionGeneral(), stripPath(), and writeDocbookString().
Referenced by writeLineNumber().
writeCodeLinkLine() [2/2]
void DocbookCodeGenerator::writeCodeLinkLine (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip, bool)
writeLineNumber() [1/2]
void DocbookCodeGenerator::writeLineNumber (const QCString & ref, const QCString & file, const QCString & anchor, int lineNumber, bool writeLineAnchor) [virtual]
Writes the line number of a source listing
Parameters
ref External reference (when imported from a tag file)
file The file part of the URL pointing to the docs.
anchor The anchor part of the URL pointing to the docs.
lineNumber The line number to write
writeLineAnchor Indicates if an anchor for the line number needs to be written
Implements CodeOutputInterface.
Definition at line 223 of file docbookgen.cpp.
{
  Docbook_DB(("(writeLineNumber)\n"));
  m_insideCodeLine = TRUE;
  if (Config_getBool(SOURCE_BROWSER))
  {
    QCString lineNumber;
    lineNumber.sprintf("%05d",l);
    if (!m_sourceFileName.isEmpty())
    {
      writeCodeLinkLine(CodeSymbolType::Default,ref,m_sourceFileName,anchor,lineNumber,QCString(),writeLineAnchor);
    }
    if (!fileName.isEmpty())
    {
      writeCodeLink(CodeSymbolType::Default,ref,fileName,anchor,lineNumber,QCString());
    }
    else
    {
      codify(lineNumber);
    }
    m_t << " ";
  }
  else
  {
    m_t << l << " ";
  }
  m_col=0;
}
References codify(), Config_getBool, Default, Docbook_DB, QCString::isEmpty(), m_col, m_insideCodeLine, m_sourceFileName, m_t, QCString::sprintf(), TRUE, writeCodeLink(), and writeCodeLinkLine().
Referenced by DocbookGenerator::writeLineNumber().
writeLineNumber() [2/2]
void DocbookCodeGenerator::writeLineNumber (const QCString & ref, const QCString & file, const QCString & anchor, int lineNumber, bool writeLineAnchor) [virtual]
Writes the line number of a source listing
Parameters
ref External reference (when imported from a tag file)
file The file part of the URL pointing to the docs.
anchor The anchor part of the URL pointing to the docs.
lineNumber The line number to write
writeLineAnchor Indicates if an anchor for the line number needs to be written
Implements CodeOutputInterface.
writeTooltip() [1/2]
void DocbookCodeGenerator::writeTooltip (const QCString & id, const DocLinkInfo & docInfo, const QCString & decl, const QCString & desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) [virtual]
Writes a tool tip definition
Parameters
id unique identifier for the tooltip
docInfo Info about the symbol's documentation.
decl full declaration of the symbol (for functions)
desc brief description for the symbol
defInfo Info about the symbol's definition in the source code
declInfo Info about the symbol's declaration in the source code
Implements CodeOutputInterface.
Definition at line 180 of file docbookgen.cpp.
{
  Docbook_DB(("(writeToolTip)\n"));
}
References Docbook_DB.
Referenced by DocbookGenerator::writeTooltip().
writeTooltip() [2/2]
void DocbookCodeGenerator::writeTooltip (const QCString & id, const DocLinkInfo & docInfo, const QCString & decl, const QCString & desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) [virtual]
Writes a tool tip definition
Parameters
id unique identifier for the tooltip
docInfo Info about the symbol's documentation.
decl full declaration of the symbol (for functions)
desc brief description for the symbol
defInfo Info about the symbol's definition in the source code
declInfo Info about the symbol's declaration in the source code
Implements CodeOutputInterface.
Member Data Documentation
m_col
int DocbookCodeGenerator::m_col = 0 [private]
Definition at line 59 of file docbookgen.h.
Referenced by codify(), startCodeLine(), writeCodeLink(), writeCodeLinkLine(), and writeLineNumber().
m_external
QCString DocbookCodeGenerator::m_external [private]
Definition at line 57 of file docbookgen.h.
Referenced by endCodeLine().
m_insideCodeLine
bool DocbookCodeGenerator::m_insideCodeLine = false [private]
Definition at line 60 of file docbookgen.h.
Referenced by endCodeLine(), startCodeLine(), and writeLineNumber().
m_insideSpecialHL
bool DocbookCodeGenerator::m_insideSpecialHL = false [private]
Definition at line 61 of file docbookgen.h.
Referenced by endFontClass(), and startFontClass().
m_lineNumber
int DocbookCodeGenerator::m_lineNumber = -1 [private]
Definition at line 58 of file docbookgen.h.
Referenced by endCodeLine().
m_refId
QCString DocbookCodeGenerator::m_refId [private]
Definition at line 56 of file docbookgen.h.
Referenced by endCodeLine().
m_relPath
QCString DocbookCodeGenerator::m_relPath [private]
Definition at line 62 of file docbookgen.h.
Referenced by setRelativePath().
m_sourceFileName
QCString DocbookCodeGenerator::m_sourceFileName [private]
Definition at line 63 of file docbookgen.h.
Referenced by setSourceFileName(), sourceFileName(), and writeLineNumber().
m_t
TextStream & DocbookCodeGenerator::m_t [private]
Definition at line 55 of file docbookgen.h.
Referenced by codify(), endCodeFragment(), endCodeLine(), endFontClass(), startCodeFragment(), startFontClass(), writeCodeLink(), writeCodeLinkLine(), and writeLineNumber().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docbookgen.h
doxygen/src/docbookgen.h
doxygen/build/doxygen/src/docbookgen.cpp
doxygen/src/docbookgen.cpp