FileInfo Class Reference
Minimal replacement for QFileInfo.
#include <fileinfo.h>
Public Member Functions
FileInfo (const std::string &name)
bool exists () const
size_t size () const
bool isWritable () const
bool isReadable () const
bool isExecutable () const
bool isRelative () const
bool isFile () const
bool isDir () const
bool isSymLink () const
std::string readLink () const
std::string filePath () const
std::string absFilePath () const
std::string fileName () const
std::string baseName () const
std::string extension (bool complete) const
std::string dirPath (bool absPath=true) const
FileInfo (const std::string &name)
bool exists () const
size_t size () const
bool isWritable () const
bool isReadable () const
bool isExecutable () const
bool isRelative () const
bool isFile () const
bool isDir () const
bool isSymLink () const
std::string readLink () const
std::string filePath () const
std::string absFilePath () const
std::string fileName () const
std::string baseName () const
std::string extension (bool complete) const
std::string dirPath (bool absPath=true) const
Static Private Member Functions
static void correctPath (std::string &s)
static void correctPath (std::string &s)
Private Attributes
std::string m_name
Detailed Description
Minimal replacement for QFileInfo.
Definition at line 22 of file fileinfo.h.
Constructor & Destructor Documentation
FileInfo() [1/2]
FileInfo::FileInfo (const std::string & name) [inline], [explicit]
Definition at line 25 of file fileinfo.h.
: m_name(name) {}
FileInfo() [2/2]
FileInfo::FileInfo (const std::string & name) [inline], [explicit]
Definition at line 25 of file fileinfo.h.
: m_name(name) {}
Member Function Documentation
absFilePath() [1/2]
std::string FileInfo::absFilePath () const
Definition at line 101 of file fileinfo.cpp.
{
  std::string result;
  std::error_code ec;
  fs::path path(m_name);
  if (!path.is_relative())
  {
    result = path.lexically_normal().string();
  }
  else
  {
    result = (fs::current_path(ec) / m_name).lexically_normal().string();
  }
  correctPath(result);
  return result;
}
References correctPath(), ghc::filesystem::current_path(), ghc::filesystem::path::is_relative(), ghc::filesystem::path::lexically_normal(), m_name, ghc::filesystem::path::string(), and string.
Referenced by Preprocessor::addSearchDir(), checkAndOpenFile(), cleanUpPaths(), FormulaManager::createLatexFile(), determineAbsoluteIncludeName(), dirPath(), genericPatternMatch(), getConvertLatexMacro(), markdownFileNameToId(), parseFile(), MarkdownOutlineParser::parseInput(), Markdown::processLink(), readConfiguration(), readDir(), readFileOrDirectory(), readTagFile(), resolveLink(), setFileName(), substituteLatexKeywords(), and ClassDefImpl::writeIncludeFilesForSlice().
absFilePath() [2/2]
std::string FileInfo::absFilePath () const
baseName() [1/2]
std::string FileInfo::baseName () const
Definition at line 123 of file fileinfo.cpp.
{
  std::string s = fileName();
  size_t pos = s.find('.');
  return pos!=std::string::npos ? s.substr(0,pos) : s;
}
References fileName(), s, and string.
Referenced by parseMain().
baseName() [2/2]
std::string FileInfo::baseName () const
correctPath() [1/2]
void FileInfo::correctPath (std::string & s) [static], [private]
Definition at line 96 of file fileinfo.cpp.
{
  std::replace(s.begin(), s.end(), '\\', '/');
}
References reg::replace(), and s.
Referenced by absFilePath(), and dirPath().
correctPath() [2/2]
static void FileInfo::correctPath (std::string & s) [static], [private]
dirPath() [1/2]
std::string FileInfo::dirPath (bool absPath = true) const
Definition at line 137 of file fileinfo.cpp.
{
  std::string result;
  if (absPath)
  {
    result = absFilePath();
  }
  else
  {
    result = m_name;
    correctPath(result);
  }
  size_t pos = result.rfind('/');
  if (pos==std::string::npos)
  {
    return ".";
  }
  else if (pos==0)
  {
    return "/";
  }
  else
  {
    return result.substr(0,pos);
  }
}
References absFilePath(), correctPath(), m_name, and string.
Referenced by Config::checkAndCorrect(), determineAbsoluteIncludeName(), findFile(), findPackageScope(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), readDir(), and readFileOrDirectory().
dirPath() [2/2]
std::string FileInfo::dirPath (bool absPath = true) const
exists() [1/2]
bool FileInfo::exists () const
Definition at line 30 of file fileinfo.cpp.
{
  std::error_code ec;
  bool result = fs::exists(fs::path(m_name),ec);
  return !ec && result;
}
References ghc::filesystem::exists(), and m_name.
Referenced by Config::checkAndCorrect(), checkAndOpenFile(), cleanUpPaths(), computeVerifiedDotPath(), copyExtraFiles(), copyLatexStyleSheet(), copyLogo(), copyStyleSheet(), deliverablesPresent(), determineAbsoluteIncludeName(), Dir::exists(), ExistsOnPath(), extractBoundingBox(), extraLatexStyleSheet(), fileToString(), DocParser::findAndCopyImage(), findFile(), findPackageScopeFromPath(), CitationManager::generatePage(), FormulaManager::initFromRepository(), CitationManager::insertCrossReferencesForBibFile(), insertMapFile(), CitationManager::latexBibFiles(), Htags::loadFilemap(), openOutputFile(), parseInput(), Markdown::processLink(), readConfiguration(), readDir(), readFileOrDirectory(), readInputFile(), readTagFile(), DocParser::readTextFileByName(), runPlantumlContent(), ManGenerator::startDoxyAnchor(), substituteHtmlKeywords(), tryPath(), ClassDefImpl::writeIncludeFilesForSlice(), and HtmlGenerator::writeStyleInfo().
exists() [2/2]
bool FileInfo::exists () const
extension() [1/2]
std::string FileInfo::extension (bool complete) const
Definition at line 130 of file fileinfo.cpp.
{
  std::string fn = fileName();
  size_t pos = complete ? fn.find('.') : fn.rfind('.');
  return pos!=std::string::npos ? fn.substr(pos+1) : std::string();
}
References fileName(), and string.
Referenced by getLanguageFromFileName().
extension() [2/2]
std::string FileInfo::extension (bool complete) const
fileName() [1/2]
std::string FileInfo::fileName () const
Definition at line 118 of file fileinfo.cpp.
{
  return fs::path(m_name).filename().string();
}
References ghc::filesystem::path::filename(), m_name, and ghc::filesystem::path::string().
Referenced by res2cc_cmd.File::__init__(), baseName(), copyExtraFiles(), copyLatexStyleSheet(), copyLogo(), copyStyleSheet(), FormulaManager::createLatexFile(), extension(), extraLatexStyleSheet(), search.Finder::function(), genericPatternMatch(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), openOutputFile(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), MarkdownOutlineParser::parseInput(), Markdown::processLink(), readDir(), readFileOrDirectory(), substituteHtmlKeywords(), substituteLatexKeywords(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), res2cc_cmd.LumaFile::writeDirEntry(), and HtmlGenerator::writeStyleInfo().
fileName() [2/2]
std::string FileInfo::fileName () const
Referenced by res2cc_cmd.File::__init__(), search.Finder::function(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::typedef(), search.Finder::variable(), res2cc_cmd.VerbatimFile::writeDirEntry(), res2cc_cmd.CSSFile::writeDirEntry(), res2cc_cmd.SVGFile::writeDirEntry(), res2cc_cmd.LumFile::writeDirEntry(), and res2cc_cmd.LumaFile::writeDirEntry().
filePath() [1/2]
std::string FileInfo::filePath () const
Definition at line 91 of file fileinfo.cpp.
{
  return m_name;
}
References m_name.
Referenced by genericPatternMatch().
filePath() [2/2]
std::string FileInfo::filePath () const
isDir() [1/2]
bool FileInfo::isDir () const
Definition at line 70 of file fileinfo.cpp.
{
  std::error_code ec;
  fs::file_status status = fs::status(m_name,ec);
  return !ec && fs::is_directory(status);
}
References ghc::filesystem::is_directory(), m_name, and ghc::filesystem::status().
Referenced by Preprocessor::addSearchDir(), Config::checkAndCorrect(), cleanUpPaths(), determineAbsoluteIncludeName(), Dir::exists(), readDir(), readFileOrDirectory(), and resolveSymlink().
isDir() [2/2]
bool FileInfo::isDir () const
isExecutable() [1/2]
bool FileInfo::isExecutable () const
Definition at line 51 of file fileinfo.cpp.
{
  std::error_code ec;
  fs::file_status status = fs::status(m_name,ec);
  return !ec && (status.permissions() & fs::perms::owner_exec)!=fs::perms::none;
}
References m_name, ghc::filesystem::file_status::permissions(), and ghc::filesystem::status().
isExecutable() [2/2]
bool FileInfo::isExecutable () const
isFile() [1/2]
bool FileInfo::isFile () const
Definition at line 63 of file fileinfo.cpp.
{
  std::error_code ec;
  fs::file_status status = fs::status(m_name,ec);
  return !ec && fs::is_regular_file(status);
}
References ghc::filesystem::is_regular_file(), m_name, and ghc::filesystem::status().
Referenced by Config::checkAndCorrect(), checkAndOpenFile(), computeVerifiedDotPath(), fileToString(), readDir(), readFileOrDirectory(), readTagFile(), runPlantumlContent(), tryPath(), and HtmlGenerator::writeStyleInfo().
isFile() [2/2]
bool FileInfo::isFile () const
isReadable() [1/2]
bool FileInfo::isReadable () const
Definition at line 44 of file fileinfo.cpp.
{
  std::error_code ec;
  fs::file_status status = fs::status(m_name,ec);
  return !ec && (status.permissions() & fs::perms::owner_read)!=fs::perms::none;
}
References m_name, ghc::filesystem::file_status::permissions(), and ghc::filesystem::status().
Referenced by Htags::loadFilemap(), Markdown::processLink(), readDir(), readFileOrDirectory(), and HtmlGenerator::writeStyleInfo().
isReadable() [2/2]
bool FileInfo::isReadable () const
isRelative() [1/2]
bool FileInfo::isRelative () const
Definition at line 58 of file fileinfo.cpp.
{
  return fs::path(m_name).is_relative();
}
References ghc::filesystem::path::is_relative(), and m_name.
Referenced by resolveSymlink().
isRelative() [2/2]
bool FileInfo::isRelative () const
isSymLink() [1/2]
bool FileInfo::isSymLink () const
Definition at line 77 of file fileinfo.cpp.
{
  std::error_code ec;
  fs::file_status status = fs::symlink_status(m_name,ec);
  return !ec && fs::is_symlink(status);
}
References ghc::filesystem::is_symlink(), m_name, ghc::filesystem::status(), and ghc::filesystem::symlink_status().
Referenced by DocParser::findAndCopyImage(), readDir(), readFileOrDirectory(), and resolveSymlink().
isSymLink() [2/2]
bool FileInfo::isSymLink () const
isWritable() [1/2]
bool FileInfo::isWritable () const
Definition at line 37 of file fileinfo.cpp.
{
  std::error_code ec;
  fs::file_status status = fs::status(m_name,ec);
  return !ec && (status.permissions() & fs::perms::owner_write)!=fs::perms::none;
}
References m_name, ghc::filesystem::file_status::permissions(), and ghc::filesystem::status().
isWritable() [2/2]
bool FileInfo::isWritable () const
readLink() [1/2]
std::string FileInfo::readLink () const
Definition at line 84 of file fileinfo.cpp.
{
  std::error_code ec;
  fs::path targetPath = fs::read_symlink(fs::path(m_name));
  return !ec ? targetPath.string() : std::string();
}
References m_name, ghc::filesystem::read_symlink(), ghc::filesystem::path::string(), and string.
Referenced by resolveSymlink().
readLink() [2/2]
std::string FileInfo::readLink () const
size() [1/2]
size_t FileInfo::size () const
Definition at line 23 of file fileinfo.cpp.
{
  std::error_code ec;
  size_t result = static_cast<size_t>(fs::file_size(fs::path(m_name),ec));
  return ec ? 0 : result;
}
References ghc::filesystem::file_size(), and m_name.
Referenced by checkAndOpenFile(), deliverablesPresent(), fileToString(), insertMapFile(), TemplateEngine::Private::loadByName(), parseFile(), and readInputFile().
size() [2/2]
size_t FileInfo::size () const
Member Data Documentation
m_name
std::string FileInfo::m_name [private]
Definition at line 44 of file fileinfo.h.
Referenced by absFilePath(), dirPath(), exists(), fileName(), filePath(), isDir(), isExecutable(), isFile(), isReadable(), isRelative(), isSymLink(), isWritable(), readLink(), and size().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/fileinfo.h
doxygen/src/fileinfo.h
doxygen/build/doxygen/src/fileinfo.cpp
doxygen/src/fileinfo.cpp