EdgeInfo Class Reference
#include <dotnode.h>
Public Types
enum Colors {
Blue =0
, Green =1
, Red =2
, Purple =3
,
Grey =4
, Orange =5
, Orange2 =6
, Blue =0
,
Green =1
, Red =2
, Purple =3
, Grey =4
,
Orange =5
, Orange2 =6
 }
enum Styles { Solid =0
, Dashed =1
, Solid =0
, Dashed =1
 }
enum Colors {
Blue =0
, Green =1
, Red =2
, Purple =3
,
Grey =4
, Orange =5
, Orange2 =6
, Blue =0
,
Green =1
, Red =2
, Purple =3
, Grey =4
,
Orange =5
, Orange2 =6
 }
enum Styles { Solid =0
, Dashed =1
, Solid =0
, Dashed =1
 }
Public Member Functions
EdgeInfo (int color, int style, const QCString &lab, const QCString &url, int labColor)
~EdgeInfo ()
int color () const
int style () const
QCString label () const
QCString url () const
int labelColor () const
EdgeInfo (int color, int style, const QCString &lab, const QCString &url, int labColor)
~EdgeInfo ()
int color () const
int style () const
QCString label () const
QCString url () const
int labelColor () const
Private Attributes
int m_color
int m_style
QCString m_label
QCString m_url
int m_labColor
Detailed Description
Attributes of an edge of a dot graph
Definition at line 31 of file dotnode.h.
Member Enumeration Documentation
Colors [1/2]
enum EdgeInfo::Colors
Enumerator
Blue
Green
Red
Purple
Grey
Orange
Orange2
Blue
Green
Red
Purple
Grey
Orange
Orange2
Definition at line 34 of file dotnode.h.
{ Blue=0, Green=1, Red=2, Purple=3, Grey=4, Orange=5, Orange2=6 };
Colors [2/2]
enum EdgeInfo::Colors
Enumerator
Blue
Green
Red
Purple
Grey
Orange
Orange2
Blue
Green
Red
Purple
Grey
Orange
Orange2
Definition at line 34 of file dotnode.h.
{ Blue=0, Green=1, Red=2, Purple=3, Grey=4, Orange=5, Orange2=6 };
Styles [1/2]
enum EdgeInfo::Styles
Enumerator
Solid
Dashed
Solid
Dashed
Definition at line 35 of file dotnode.h.
{ Solid=0, Dashed=1 };
Styles [2/2]
enum EdgeInfo::Styles
Enumerator
Solid
Dashed
Solid
Dashed
Definition at line 35 of file dotnode.h.
{ Solid=0, Dashed=1 };
Constructor & Destructor Documentation
EdgeInfo() [1/2]
EdgeInfo::EdgeInfo (int color, int style, const QCString & lab, const QCString & url, int labColor) [inline]
Definition at line 36 of file dotnode.h.
        : m_color(color), m_style(style), m_label(lab), m_url(url), m_labColor(labColor) {}
 EdgeInfo() [1/2]
EdgeInfo::~EdgeInfo () [inline]
Definition at line 38 of file dotnode.h.
{}
EdgeInfo() [2/2]
EdgeInfo::EdgeInfo (int color, int style, const QCString & lab, const QCString & url, int labColor) [inline]
Definition at line 36 of file dotnode.h.
        : m_color(color), m_style(style), m_label(lab), m_url(url), m_labColor(labColor) {}
 EdgeInfo() [2/2]
EdgeInfo::~EdgeInfo () [inline]
Definition at line 38 of file dotnode.h.
{}
Member Function Documentation
color() [1/2]
int EdgeInfo::color () const [inline]
Definition at line 39 of file dotnode.h.
{ return m_color; }
References m_color.
Referenced by DotNode::writeArrow().
color() [2/2]
int EdgeInfo::color () const [inline]
Definition at line 39 of file dotnode.h.
{ return m_color; }
References m_color.
label() [1/2]
QCString EdgeInfo::label () const [inline]
Definition at line 41 of file dotnode.h.
{ return m_label; }
References m_label.
Referenced by doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.nodeType::buildChildren(), doxmlparser.compound.nodeType::exportChildren(), doxmlparser.compound.nodeType::get_label(), doxmlparser.compound.nodeType::hasContent_(), doxmlparser.compound.nodeType::set_label(), and DotNode::writeArrow().
label() [2/2]
QCString EdgeInfo::label () const [inline]
Definition at line 41 of file dotnode.h.
{ return m_label; }
References m_label.
Referenced by doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.nodeType::buildChildren(), doxmlparser.compound.nodeType::exportChildren(), doxmlparser.compound.nodeType::get_label(), doxmlparser.compound.nodeType::hasContent_(), and doxmlparser.compound.nodeType::set_label().
labelColor() [1/2]
int EdgeInfo::labelColor () const [inline]
Definition at line 43 of file dotnode.h.
{ return m_labColor; }
References m_labColor.
labelColor() [2/2]
int EdgeInfo::labelColor () const [inline]
Definition at line 43 of file dotnode.h.
{ return m_labColor; }
References m_labColor.
style() [1/2]
int EdgeInfo::style () const [inline]
Definition at line 40 of file dotnode.h.
{ return m_style; }
References m_style.
Referenced by DotNode::writeArrow().
style() [2/2]
int EdgeInfo::style () const [inline]
Definition at line 40 of file dotnode.h.
{ return m_style; }
References m_style.
url() [1/2]
QCString EdgeInfo::url () const [inline]
Definition at line 42 of file dotnode.h.
{ return m_url; }
References m_url.
Referenced by doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docURLLink::buildAttributes(), doxmlparser.compound.docURLLink::exportAttributes(), doxmlparser.compound.docURLLink::get_url(), and doxmlparser.compound.docURLLink::set_url().
url() [2/2]
QCString EdgeInfo::url () const [inline]
Definition at line 42 of file dotnode.h.
{ return m_url; }
References m_url.
Referenced by doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docURLLink::buildAttributes(), doxmlparser.compound.docURLLink::exportAttributes(), doxmlparser.compound.docURLLink::get_url(), and doxmlparser.compound.docURLLink::set_url().
Member Data Documentation
m_color
int EdgeInfo::m_color [private]
Definition at line 45 of file dotnode.h.
Referenced by color().
m_labColor
int EdgeInfo::m_labColor [private]
Definition at line 49 of file dotnode.h.
Referenced by labelColor().
m_label
QCString EdgeInfo::m_label [private]
Definition at line 47 of file dotnode.h.
Referenced by label().
m_style
int EdgeInfo::m_style [private]
Definition at line 46 of file dotnode.h.
Referenced by style().
m_url
QCString EdgeInfo::m_url [private]
Definition at line 48 of file dotnode.h.
Referenced by url().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/dotnode.h
doxygen/src/dotnode.h