Mapper Class Reference
#include <cmdmapper.h>
Public Member Functions
int map (const QCString &n)
QCString find (const int n)
Mapper (const CommandMap *cm, bool caseSensitive)
int map (const QCString &n)
QCString find (const int n)
Mapper (const CommandMap *cm, bool caseSensitive)
Private Attributes
std::map< std::string, int > m_map
bool m_cs
Detailed Description
Class representing a mapping from command names to command IDs.
Definition at line 229 of file cmdmapper.h.
Constructor & Destructor Documentation
Mapper() [1/2]
Mapper::Mapper (const CommandMap * cm, bool caseSensitive)
Definition at line 266 of file cmdmapper.cpp.
                                                      : m_cs(caseSensitive)
{
  const CommandMap *p = cm;
  while (p->cmdName)
  {
    m_map.insert(std::make_pair(p->cmdName,p->cmdId));
    p++;
  }
}
References m_map, and p.
Mapper() [2/2]
Mapper::Mapper (const CommandMap * cm, bool caseSensitive)
Member Function Documentation
find() [1/2]
QCString Mapper::find (const int n)
Definition at line 256 of file cmdmapper.cpp.
{
  for (const auto &kv : m_map)
  {
    int curVal = kv.second;
    if (curVal == n || (curVal == (n | SIMPLESECT_BIT))) return kv.first.c_str();
  }
  return QCString();
}
References m_map, n, and SIMPLESECT_BIT.
find() [2/2]
QCString Mapper::find (const int n)
map() [1/2]
int Mapper::map (const QCString & n)
Definition at line 247 of file cmdmapper.cpp.
{
  if (n.isEmpty()) return 0;
  QCString name = n;
  if (!m_cs) name=name.lower();
  auto it = m_map.find(name.str());
  return it!=m_map.end() ? it->second : 0;
}
References m_cs, m_map, n, and setup::name.
Referenced by DocPara::handleCommand(), DocPara::handleHtmlEndTag(), DocPara::handleHtmlStartTag(), DocHRef::parse(), DocHtmlHeader::parse(), DocHtmlDescTitle::parse(), DocHtmlDescList::parse(), DocHtmlList::parse(), DocPara::parse(), DocHtmlCell::parse(), DocHtmlCaption::parse(), DocHtmlRow::parse(), DocHtmlTable::parse(), DocHtmlList::parseXml(), DocHtmlCell::parseXml(), DocHtmlTable::parseXml(), DocHtmlRow::parseXml(), and DocParamList::parseXml().
map() [2/2]
int Mapper::map (const QCString & n)
Member Data Documentation
m_cs
bool Mapper::m_cs [private]
Definition at line 237 of file cmdmapper.h.
Referenced by map().
m_map
std::map< std::string, int > Mapper::m_map [private]
Definition at line 236 of file cmdmapper.h.
Referenced by find(), map(), and Mapper().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/cmdmapper.h
doxygen/src/cmdmapper.h
doxygen/build/doxygen/src/cmdmapper.cpp
doxygen/src/cmdmapper.cpp