DotDirDeps Class Reference
#include <dotdirdeps.h>
Public Member Functions
DotDirDeps (const DirDef *dir)
~DotDirDeps ()
bool isTrivial () const
QCString writeGraph (TextStream &out, GraphOutputFormat gf, EmbeddedOutputFormat ef, const QCString &path, const QCString &fileName, const QCString &relPath, bool writeImageMap=TRUE, int graphId=-1, bool linkRelations=TRUE)
DotDirDeps (const DirDef *dir)
~DotDirDeps ()
bool isTrivial () const
QCString writeGraph (TextStream &out, GraphOutputFormat gf, EmbeddedOutputFormat ef, const QCString &path, const QCString &fileName, const QCString &relPath, bool writeImageMap=TRUE, int graphId=-1, bool linkRelations=TRUE)
Protected Member Functions
virtual QCString getBaseName () const
virtual QCString getMapLabel () const
virtual void computeTheGraph ()
virtual QCString getImgAltText () const
virtual QCString getBaseName () const
virtual QCString getMapLabel () const
virtual void computeTheGraph ()
virtual QCString getImgAltText () const
Private Attributes
const DirDef * m_dir = 0
bool m_linkRelations = false
Additional Inherited Members
Detailed Description
Representation of an directory dependency graph
Definition at line 25 of file dotdirdeps.h.
Constructor & Destructor Documentation
DotDirDeps() [1/2]
DotDirDeps::DotDirDeps (const DirDef * dir)
Definition at line 398 of file dotdirdeps.cpp.
                                        : m_dir(dir)
{
}
 DotDirDeps() [1/2]
DotDirDeps::~DotDirDeps ()
Definition at line 402 of file dotdirdeps.cpp.
{
}
DotDirDeps() [2/2]
DotDirDeps::DotDirDeps (const DirDef * dir)
 DotDirDeps() [2/2]
DotDirDeps::~DotDirDeps ()
Member Function Documentation
computeTheGraph() [1/2]
void DotDirDeps::computeTheGraph () [protected], [virtual]
Implements DotGraph.
Definition at line 412 of file dotdirdeps.cpp.
{
  // compute md5 checksum of the graph were are about to generate
  TextStream md5stream;
  writeGraphHeader(md5stream, m_dir->displayName());
  md5stream << " compound=true\n";
  writeDotDirDepGraph(md5stream,m_dir,m_linkRelations);
  writeGraphFooter(md5stream);
  m_theGraph = md5stream.str();
}
References DirDef::displayName(), m_dir, m_linkRelations, DotGraph::m_theGraph, TextStream::str(), writeDotDirDepGraph(), DotGraph::writeGraphFooter(), and DotGraph::writeGraphHeader().
computeTheGraph() [2/2]
virtual void DotDirDeps::computeTheGraph () [protected], [virtual]
Implements DotGraph.
getBaseName() [1/2]
QCString DotDirDeps::getBaseName () const [protected], [virtual]
Implements DotGraph.
Definition at line 406 of file dotdirdeps.cpp.
{
  return m_dir->getOutputFileBase()+"_dep";
}
References DirDef::getOutputFileBase(), and m_dir.
getBaseName() [2/2]
virtual QCString DotDirDeps::getBaseName () const [protected], [virtual]
Implements DotGraph.
getImgAltText() [1/2]
QCString DotDirDeps::getImgAltText () const [protected], [virtual]
Reimplemented from DotGraph.
Definition at line 428 of file dotdirdeps.cpp.
{
  return convertToXML(m_dir->displayName());
}
References convertToXML(), DirDef::displayName(), and m_dir.
getImgAltText() [2/2]
virtual QCString DotDirDeps::getImgAltText () const [protected], [virtual]
Reimplemented from DotGraph.
getMapLabel() [1/2]
QCString DotDirDeps::getMapLabel () const [protected], [virtual]
Implements DotGraph.
Definition at line 423 of file dotdirdeps.cpp.
{
  return escapeCharsInString(m_baseName,FALSE);
}
References escapeCharsInString(), FALSE, and DotGraph::m_baseName.
getMapLabel() [2/2]
virtual QCString DotDirDeps::getMapLabel () const [protected], [virtual]
Implements DotGraph.
isTrivial() [1/2]
bool DotDirDeps::isTrivial () const
Definition at line 442 of file dotdirdeps.cpp.
{
  return m_dir->depGraphIsTrivial();
}
References DirDef::depGraphIsTrivial(), and m_dir.
Referenced by DirDefImpl::writeDirectoryGraph().
isTrivial() [2/2]
bool DotDirDeps::isTrivial () const
writeGraph() [1/2]
QCString DotDirDeps::writeGraph (TextStream & out, GraphOutputFormat gf, EmbeddedOutputFormat ef, const QCString & path, const QCString & fileName, const QCString & relPath, bool writeImageMap = TRUE, int graphId = -1, bool linkRelations = TRUE)
Definition at line 433 of file dotdirdeps.cpp.
{
  m_linkRelations = linkRelations;
  m_urlOnly = TRUE;
  return DotGraph::writeGraph(out, graphFormat, textFormat, path, fileName, relPath, generateImageMap, graphId);
}
References m_linkRelations, DotGraph::m_urlOnly, out, TRUE, and DotGraph::writeGraph().
writeGraph() [2/2]
QCString DotDirDeps::writeGraph (TextStream & out, GraphOutputFormat gf, EmbeddedOutputFormat ef, const QCString & path, const QCString & fileName, const QCString & relPath, bool writeImageMap = TRUE, int graphId = -1, bool linkRelations = TRUE)
Member Data Documentation
m_dir
const DirDef * DotDirDeps::m_dir = 0 [private]
Definition at line 48 of file dotdirdeps.h.
Referenced by computeTheGraph(), getBaseName(), getImgAltText(), and isTrivial().
m_linkRelations
bool DotDirDeps::m_linkRelations = false [private]
Definition at line 50 of file dotdirdeps.h.
Referenced by computeTheGraph(), and writeGraph().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/dotdirdeps.h
doxygen/src/dotdirdeps.h
doxygen/build/doxygen/src/dotdirdeps.cpp
doxygen/src/dotdirdeps.cpp