DocParamSect Class Reference
#include <docnode.h>
Public Types
enum Type {
Unknown
, Param
, RetVal
, Exception
,
TemplateParam
, Unknown
, Param
, RetVal
,
Exception
, TemplateParam
 }
enum Direction {
In =1
, Out =2
, InOut =3
, Unspecified =0
,
In =1
, Out =2
, InOut =3
, Unspecified =0
 }
enum Type {
Unknown
, Param
, RetVal
, Exception
,
TemplateParam
, Unknown
, Param
, RetVal
,
Exception
, TemplateParam
 }
enum Direction {
In =1
, Out =2
, InOut =3
, Unspecified =0
,
In =1
, Out =2
, InOut =3
, Unspecified =0
 }
Public Member Functions
DocParamSect (DocParser *parser, DocNodeVariant *parent, Type t)
int parse (DocNodeVariant *, const QCString &cmdName, bool xmlContext, Direction d)
Type type () const
bool hasInOutSpecifier () const
bool hasTypeSpecifier () const
DocParamSect (DocParser *parser, DocNodeVariant *parent, Type t)
int parse (DocNodeVariant *, const QCString &cmdName, bool xmlContext, Direction d)
Type type () const
bool hasInOutSpecifier () const
bool hasTypeSpecifier () const
Private Attributes
Type m_type = Unknown
bool m_hasInOutSpecifier = false
bool m_hasTypeSpecifier = false
Friends
class DocParamList
Additional Inherited Members
Detailed Description
Node representing a parameter section
Definition at line 1004 of file docnode.h.
Member Enumeration Documentation
Direction [1/2]
enum DocParamSect::Direction
Enumerator
In
Out
InOut
Unspecified
In
Out
InOut
Unspecified
Definition at line 1012 of file docnode.h.
    {
       In=1, Out=2, InOut=3, Unspecified=0
    };
Direction [2/2]
enum DocParamSect::Direction
Enumerator
In
Out
InOut
Unspecified
In
Out
InOut
Unspecified
Definition at line 1012 of file docnode.h.
    {
       In=1, Out=2, InOut=3, Unspecified=0
    };
Type [1/2]
enum DocParamSect::Type
Enumerator
Unknown
Param
RetVal
Exception
TemplateParam
Unknown
Param
RetVal
Exception
TemplateParam
Definition at line 1008 of file docnode.h.
    {
       Unknown, Param, RetVal, Exception, TemplateParam
    };
Type [2/2]
enum DocParamSect::Type
Enumerator
Unknown
Param
RetVal
Exception
TemplateParam
Unknown
Param
RetVal
Exception
TemplateParam
Definition at line 1008 of file docnode.h.
    {
       Unknown, Param, RetVal, Exception, TemplateParam
    };
Constructor & Destructor Documentation
DocParamSect() [1/2]
DocParamSect::DocParamSect (DocParser * parser, DocNodeVariant * parent, Type t) [inline]
Definition at line 1016 of file docnode.h.
      : DocCompoundNode(parser,parent), m_type(t), m_hasInOutSpecifier(FALSE), m_hasTypeSpecifier(FALSE)
    {}
DocParamSect() [2/2]
DocParamSect::DocParamSect (DocParser * parser, DocNodeVariant * parent, Type t) [inline]
Definition at line 1016 of file docnode.h.
      : DocCompoundNode(parser,parent), m_type(t), m_hasInOutSpecifier(FALSE), m_hasTypeSpecifier(FALSE)
    {}
Member Function Documentation
hasInOutSpecifier() [1/2]
bool DocParamSect::hasInOutSpecifier () const [inline]
Definition at line 1021 of file docnode.h.
{ return m_hasInOutSpecifier; }
References m_hasInOutSpecifier.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), PerlModDocVisitor::operator()(), and RTFDocVisitor::operator()().
hasInOutSpecifier() [2/2]
bool DocParamSect::hasInOutSpecifier () const [inline]
Definition at line 1021 of file docnode.h.
{ return m_hasInOutSpecifier; }
References m_hasInOutSpecifier.
hasTypeSpecifier() [1/2]
bool DocParamSect::hasTypeSpecifier () const [inline]
Definition at line 1022 of file docnode.h.
{ return m_hasTypeSpecifier; }
References m_hasTypeSpecifier.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), and RTFDocVisitor::operator()().
hasTypeSpecifier() [2/2]
bool DocParamSect::hasTypeSpecifier () const [inline]
Definition at line 1022 of file docnode.h.
{ return m_hasTypeSpecifier; }
References m_hasTypeSpecifier.
parse() [1/2]
int DocParamSect::parse (DocNodeVariant * thisVariant, const QCString & cmdName, bool xmlContext, Direction d)
Definition at line 3054 of file docnode.cpp.
{
  int retval=RetVal_OK;
  DBG(("DocParamSect::parse() start\n"));
  auto ns = AutoNodeStack(parser(),thisVariant);
  if (d!=Unspecified)
  {
    m_hasInOutSpecifier=TRUE;
  }
  if (!children().empty() && std::holds_alternative<DocParamList>(children().back()))
  {
    DocParamList &lastPl = std::get<DocParamList>(children().back());
    lastPl.markLast(false);
  }
  bool markFirst = children().empty();
  auto vDocParamList = children().append<DocParamList>(parser(),thisVariant,m_type,d);
  DocParamList *pl = children().get_last<DocParamList>();
  if (markFirst)
  {
    pl->markFirst();
  }
  pl->markLast();
  if (xmlContext)
  {
    retval = pl->parseXml(vDocParamList,cmdName);
  }
  else
  {
    retval = pl->parse(vDocParamList,cmdName);
  }
  if (retval==RetVal_EndParBlock)
  {
    retval = RetVal_OK;
  }
  DBG(("DocParamSect::parse() end retval=%d\n",retval));
  return retval;
}
References DocNodeList::append(), DocCompoundNode::children(), DBG, GrowVector< T >::empty(), DocNodeList::get_last(), m_hasInOutSpecifier, m_type, DocParamList::markFirst(), DocParamList::markLast(), DocNode::parser(), RetVal_EndParBlock, RetVal_OK, TRUE, and Unspecified.
Referenced by DocPara::handleParamSection().
parse() [2/2]
int DocParamSect::parse (DocNodeVariant * , const QCString & cmdName, bool xmlContext, Direction d)
type() [1/2]
Type DocParamSect::type () const [inline]
Definition at line 1020 of file docnode.h.
{ return m_type; }
References m_type.
Referenced by DocPara::handleParamSection(), LatexDocVisitor::operator()(), RTFDocVisitor::operator()(), and PrintDocVisitor::operator()().
type() [2/2]
Type DocParamSect::type () const [inline]
Definition at line 1020 of file docnode.h.
{ return m_type; }
References m_type.
Friends And Related Function Documentation
DocParamList
DocParamList [friend]
Definition at line 1006 of file docnode.h.
Member Data Documentation
m_hasInOutSpecifier
bool DocParamSect::m_hasInOutSpecifier = false [private]
Definition at line 1026 of file docnode.h.
Referenced by hasInOutSpecifier(), and parse().
m_hasTypeSpecifier
bool DocParamSect::m_hasTypeSpecifier = false [private]
Definition at line 1027 of file docnode.h.
Referenced by hasTypeSpecifier().
m_type
Type DocParamSect::m_type = Unknown [private]
Definition at line 1025 of file docnode.h.
Referenced by parse(), and type().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docnode.h
doxygen/src/docnode.h
doxygen/build/doxygen/src/docnode.cpp
doxygen/src/docnode.cpp