QCString Class Reference
#include <qcstring.h>
Public Member Functions
QCString ()=default
~QCString ()=default
QCString (const QCString &s)=default
QCString & operator= (const QCString &s)=default
QCString (QCString &&s)=default
QCString & operator= (QCString &&s)=default
QCString (const std::string &s)
QCString (std::string &&s)
QCString (size_t size)
QCString (const char *str)
QCString (const char *str, size_t maxlen)
QCString & operator= (const char *str)
QCString & operator= (const std::string &s)
bool isNull () const
bool isEmpty () const
uint length () const
uint size () const
const char * data () const
char * rawData ()
bool resize (size_t newlen)
bool truncate (size_t pos)
bool fill (char c, int len=-1)
QCString & sprintf (const char *format,...)
int find (char c, int index=0, bool cs=TRUE) const
int find (const char *str, int index=0, bool cs=TRUE) const
int find (const QCString &str, int index=0, bool cs=TRUE) const
int findRev (char c, int index=-1, bool cs=TRUE) const
int findRev (const char *str, int index=-1, bool cs=TRUE) const
int contains (char c, bool cs=TRUE) const
int contains (const char *str, bool cs=TRUE) const
bool stripPrefix (const QCString &prefix)
bool stripPrefix (const char *prefix)
QCString left (size_t len) const
QCString right (size_t len) const
QCString mid (size_t index, size_t len=static_cast< size_t >(-1)) const
QCString lower () const
QCString upper () const
QCString stripWhiteSpace () const
returns a copy of this string with leading and trailing whitespace removed
QCString quoted () const
QCString removeWhiteSpace () const
returns a copy of this string with all whitespace removed
QCString simplifyWhiteSpace () const
QCString & insert (size_t index, const QCString &s)
QCString & insert (size_t index, const char *s)
QCString & insert (size_t index, char c)
QCString & append (char c)
QCString & append (const char *s)
QCString & append (const QCString &s)
QCString & append (const std::string &s)
QCString & prepend (const char *s)
QCString & prepend (const QCString &s)
QCString & prepend (const std::string &s)
QCString & remove (size_t index, size_t len)
QCString & replace (size_t index, size_t len, const char *s)
short toShort (bool *ok=0, int base=10) const
ushort toUShort (bool *ok=0, int base=10) const
int toInt (bool *ok=0, int base=10) const
uint toUInt (bool *ok=0, int base=10) const
long toLong (bool *ok=0, int base=10) const
ulong toULong (bool *ok=0, int base=10) const
uint64 toUInt64 (bool *ok=0, int base=10) const
QCString & setNum (short n)
QCString & setNum (ushort n)
QCString & setNum (int n)
QCString & setNum (uint n)
QCString & setNum (long n)
QCString & setNum (long long n)
QCString & setNum (unsigned long long n)
QCString & setNum (ulong n)
bool startsWith (const char *s) const
bool startsWith (const QCString &s) const
bool endsWith (const char *s) const
bool endsWith (const QCString &s) const
const std::string & str () const
QCString & operator+= (const QCString &s)
QCString & operator+= (const std::string &s)
QCString & operator+= (const char *s)
QCString & operator+= (char c)
char & at (size_t i)
const char & at (size_t i) const
char & operator[] (int i)
const char & operator[] (int i) const
QCString ()=default
~QCString ()=default
QCString (const QCString &s)=default
QCString & operator= (const QCString &s)=default
QCString (QCString &&s)=default
QCString & operator= (QCString &&s)=default
QCString (const std::string &s)
QCString (std::string &&s)
QCString (size_t size)
QCString (const char *str)
QCString (const char *str, size_t maxlen)
QCString & operator= (const char *str)
QCString & operator= (const std::string &s)
bool isNull () const
bool isEmpty () const
uint length () const
uint size () const
const char * data () const
char * rawData ()
bool resize (size_t newlen)
bool truncate (size_t pos)
bool fill (char c, int len=-1)
QCString & sprintf (const char *format,...)
int find (char c, int index=0, bool cs=TRUE) const
int find (const char *str, int index=0, bool cs=TRUE) const
int find (const QCString &str, int index=0, bool cs=TRUE) const
int findRev (char c, int index=-1, bool cs=TRUE) const
int findRev (const char *str, int index=-1, bool cs=TRUE) const
int contains (char c, bool cs=TRUE) const
int contains (const char *str, bool cs=TRUE) const
bool stripPrefix (const QCString &prefix)
bool stripPrefix (const char *prefix)
QCString left (size_t len) const
QCString right (size_t len) const
QCString mid (size_t index, size_t len=static_cast< size_t >(-1)) const
QCString lower () const
QCString upper () const
QCString stripWhiteSpace () const
returns a copy of this string with leading and trailing whitespace removed
QCString quoted () const
QCString removeWhiteSpace () const
returns a copy of this string with all whitespace removed
QCString simplifyWhiteSpace () const
QCString & insert (size_t index, const QCString &s)
QCString & insert (size_t index, const char *s)
QCString & insert (size_t index, char c)
QCString & append (char c)
QCString & append (const char *s)
QCString & append (const QCString &s)
QCString & append (const std::string &s)
QCString & prepend (const char *s)
QCString & prepend (const QCString &s)
QCString & prepend (const std::string &s)
QCString & remove (size_t index, size_t len)
QCString & replace (size_t index, size_t len, const char *s)
short toShort (bool *ok=0, int base=10) const
ushort toUShort (bool *ok=0, int base=10) const
int toInt (bool *ok=0, int base=10) const
uint toUInt (bool *ok=0, int base=10) const
long toLong (bool *ok=0, int base=10) const
ulong toULong (bool *ok=0, int base=10) const
uint64 toUInt64 (bool *ok=0, int base=10) const
QCString & setNum (short n)
QCString & setNum (ushort n)
QCString & setNum (int n)
QCString & setNum (uint n)
QCString & setNum (long n)
QCString & setNum (long long n)
QCString & setNum (unsigned long long n)
QCString & setNum (ulong n)
bool startsWith (const char *s) const
bool startsWith (const QCString &s) const
bool endsWith (const char *s) const
bool endsWith (const QCString &s) const
const std::string & str () const
QCString & operator+= (const QCString &s)
QCString & operator+= (const std::string &s)
QCString & operator+= (const char *s)
QCString & operator+= (char c)
char & at (size_t i)
const char & at (size_t i) const
char & operator[] (int i)
const char & operator[] (int i) const
Private Attributes
std::string m_rep
Detailed Description
This is an alternative implementation of QCString. It provides basically the same functions but uses std::string as the underlying string type
Definition at line 108 of file qcstring.h.
Constructor & Destructor Documentation
QCString() [1/16]
QCString::QCString () [default]
Referenced by left(), lower(), mid(), quoted(), removeWhiteSpace(), right(), stripPrefix(), stripWhiteSpace(), and upper().
 QCString() [1/2]
QCString::~QCString () [default]
QCString() [2/16]
QCString::QCString (const QCString & s) [default]
QCString() [3/16]
QCString::QCString (QCString && s) [default]
QCString() [4/16]
QCString::QCString (const std::string & s) [inline], [explicit]
Definition at line 118 of file qcstring.h.
: m_rep(s) {}
QCString() [5/16]
QCString::QCString (std::string && s) [inline]
Definition at line 120 of file qcstring.h.
: m_rep(std::move(s)) {}
QCString() [6/16]
QCString::QCString (size_t size) [inline], [explicit]
creates a string with room for size characters
Parameters
 in size the number of character to allocate (also counting the 0-terminator!)
Definition at line 125 of file qcstring.h.
{ m_rep.resize(size>0 ? size-1 : 0); }
References m_rep, and size().
QCString() [7/16]
QCString::QCString (const char * str) [inline]
creates a string from a plain C string.
Parameters
 in str A zero terminated C string. When 0 an empty string is created.
Definition at line 130 of file qcstring.h.
: m_rep(str?str:"") {}
QCString() [8/16]
QCString::QCString (const char * str, size_t maxlen) [inline]
creates a string from str and copies over the first maxlen characters.
Definition at line 133 of file qcstring.h.
: m_rep(str?str:"") { m_rep.resize(maxlen); }
References m_rep.
QCString() [9/16]
QCString::QCString () [default]
 QCString() [2/2]
QCString::~QCString () [default]
QCString() [10/16]
QCString::QCString (const QCString & s) [default]
QCString() [11/16]
QCString::QCString (QCString && s) [default]
QCString() [12/16]
QCString::QCString (const std::string & s) [inline], [explicit]
Definition at line 118 of file qcstring.h.
: m_rep(s) {}
QCString() [13/16]
QCString::QCString (std::string && s) [inline]
Definition at line 120 of file qcstring.h.
: m_rep(std::move(s)) {}
QCString() [14/16]
QCString::QCString (size_t size) [inline], [explicit]
creates a string with room for size characters
Parameters
 in size the number of character to allocate (also counting the 0-terminator!)
Definition at line 125 of file qcstring.h.
{ m_rep.resize(size>0 ? size-1 : 0); }
References m_rep, and size().
QCString() [15/16]
QCString::QCString (const char * str) [inline]
creates a string from a plain C string.
Parameters
 in str A zero terminated C string. When 0 an empty string is created.
Definition at line 130 of file qcstring.h.
: m_rep(str?str:"") {}
QCString() [16/16]
QCString::QCString (const char * str, size_t maxlen) [inline]
creates a string from str and copies over the first maxlen characters.
Definition at line 133 of file qcstring.h.
: m_rep(str?str:"") { m_rep.resize(maxlen); }
References m_rep.
Member Function Documentation
append() [1/8]
QCString & QCString::append (char c) [inline]
Definition at line 344 of file qcstring.h.
    {
      m_rep+=c;
      return *this;
    }
References c, and m_rep.
Referenced by addModule(), alignText(), FilterGroupBy::apply(), appStringLower(), VhdlDocGen::convertArgumentListToString(), DocEmoji::DocEmoji(), externalRef(), generateDEFForMember(), MemberDefImpl::getDeclType(), VhdlDocGen::getProcessNumber(), SymbolResolver::Private::newResolveTypedef(), operator+(), VhdlDocGen::parseUCF(), vhdl::parser::VhdlParser::procedure_call(), quoted(), MemberDefImpl::writeDeclaration(), and VhdlDocGen::writeSource().
append() [2/8]
QCString & QCString::append (char c) [inline]
Definition at line 344 of file qcstring.h.
    {
      m_rep+=c;
      return *this;
    }
References c, and m_rep.
append() [3/8]
QCString & QCString::append (const char * s) [inline]
Definition at line 350 of file qcstring.h.
    {
      return operator+=(s);
    }
References operator+=(), and s.
append() [4/8]
QCString & QCString::append (const char * s) [inline]
Definition at line 350 of file qcstring.h.
    {
      return operator+=(s);
    }
References operator+=(), and s.
append() [5/8]
QCString & QCString::append (const QCString & s) [inline]
Definition at line 355 of file qcstring.h.
    {
      return operator+=(s);
    }
References operator+=(), and s.
append() [6/8]
QCString & QCString::append (const QCString & s) [inline]
Definition at line 355 of file qcstring.h.
    {
      return operator+=(s);
    }
References operator+=(), and s.
append() [7/8]
QCString & QCString::append (const std::string & s) [inline]
Definition at line 360 of file qcstring.h.
    {
      return operator+=(s);
    }
References operator+=(), and s.
append() [8/8]
QCString & QCString::append (const std::string & s) [inline]
Definition at line 360 of file qcstring.h.
    {
      return operator+=(s);
    }
References operator+=(), and s.
at() [1/4]
char & QCString::at (size_t i) [inline]
Returns a reference to the character at index i.
Definition at line 515 of file qcstring.h.
    {
      return m_rep[i];
    }
References m_rep.
Referenced by DefinitionImpl::_setBriefDescription(), abbreviate(), addIncludeFile(), adjustConfiguration(), Config::checkAndCorrect(), computeVerifiedDotPath(), configStringRecode(), TranslatorPersian::convertDigitsToFarsi(), countAliasArguments(), DirDefImpl::DirDefImpl(), MemberDefImpl::displayDefinition(), DocEmoji::DocEmoji(), DocLink::DocLink(), elemIsVisible(), expandExpression(), externalRef(), DefinitionImpl::externalReference(), extractAliasArgs(), extractPartAfterNewLine(), findDirDocumentation(), findEnumDocumentation(), VhdlDocGen::formatString(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), getCanonicalTemplateSpec(), getCurrentChar(), getExtension(), getLanguageFromCodeLang(), getLanguageFromFileName(), getNextChar(), getNextId(), getScopeDefs(), handleHtmlTag(), DocParser::handleLinkedWord(), DocPara::handleStartCode(), Markdown::isAtxHeader(), DocFormula::isInline(), NamespaceDefImpl::isLinkableInProject(), leftScopeMatch(), linkToText(), listSymbol(), lookupSymbol(), makeFileName(), matchExcludedSymbols(), ArgumentContext::Private::namePart(), SymbolResolver::Private::newResolveTypedef(), HtmlDocVisitor::operator()(), DocbookDocVisitor::operator()(), parseCommentAsText(), parseFuncDecl(), Markdown::processLink(), readCodeFragment(), readIncludeFile(), HtmlHelpRecoder::recode(), TemplateContextImpl::recode(), recognizeFixedForm(), replaceAliasArguments(), replaceFunctionMacro(), resolveSymlink(), rightScopeMatch(), searchInputFiles(), TemplateContextImpl::setEscapeIntf(), MemberDefImpl::setInitializer(), DefinitionImpl::setName(), startsWithKeyword(), stripIrrelevantString(), stripScope(), stripTemplateSpecifiersFromScope(), substEnvVarsInStrList(), Portable::system(), transcodeCharacterStringToUTF8(), updateLanguageMapping(), validatingParseDoc(), MemberDefImpl::writeDeclaration(), MemberDefImpl::writeDocumentation(), writeExceptionList(), Markdown::writeFencedCodeBlock(), VhdlDocGen::writeFormatString(), ClassDefImpl::writeIncludeFilesForSlice(), MemberDefImpl::writeMemberDocSimple(), writeMemberList(), writeObjCMethodCall(), PlantumlManager::writePlantUMLSource(), writeSingleFileIndex(), writeWord(), and HtmlEntityMapper::writeXMLSchema().
at() [2/4]
char & QCString::at (size_t i) [inline]
Returns a reference to the character at index i.
Definition at line 515 of file qcstring.h.
    {
      return m_rep[i];
    }
References m_rep.
at() [3/4]
const char & QCString::at (size_t i) const [inline]
Definition at line 520 of file qcstring.h.
    {
      return m_rep[i];
    }
References m_rep.
at() [4/4]
const char & QCString::at (size_t i) const [inline]
Definition at line 520 of file qcstring.h.
    {
      return m_rep[i];
    }
References m_rep.
contains() [1/4]
int QCString::contains (char c, bool cs = TRUE) const
Definition at line 143 of file qcstring.cpp.
{
  if (length()==0) return 0;
  int count=0;
  const char *pos = data();
  if (cs)
  {
    while (*pos) if (*pos++ == c) count++;
  }
  else
  {
    c = toLowerChar(c);
    while (*pos)
    {
      if (toLowerChar(*pos)==c) count++;
      pos++;
    }
  }
  return count;
}
References c, cs, data(), length(), and toLowerChar().
Referenced by addMacroDefinition(), applyModifiers(), VHDLOutlineParser::checkInlineCode(), vhdl::parser::VhdlParser::component_instantiation_statement(), DotNode::convertLabel(), vhdl::parser::VhdlParser::full_type_declaration(), DocPara::handleInclude(), SymbolModifiers::operator|=(), DocInclude::parse(), VhdlDocGen::parseForConfig(), FlowChart::printPlantUmlNode(), MemberDefImpl::setInitializer(), vhdl::parser::VhdlParserTokenManager::SkipLexicalActions(), and writeUCFLink().
contains() [2/4]
int QCString::contains (char c, bool cs = TRUE) const
contains() [3/4]
int QCString::contains (const char * str, bool cs = TRUE) const
Definition at line 164 of file qcstring.cpp.
{
  if (str==0 || length()==0) return 0;
  int count=0;
  const char *pos = data();
  int len = qstrlen(str);
  while (*pos)
  {
    if (cs)
    {
      if (qstrncmp(pos,str,len)==0) count++;
    }
    else
    {
      if (qstrnicmp(pos,str,len)==0) count++;
    }
    pos++;
  }
  return count;
}
References cs, data(), len, length(), qstrlen(), qstrncmp(), qstrnicmp(), and str().
contains() [4/4]
int QCString::contains (const char * str, bool cs = TRUE) const
data() [1/2]
const char * QCString::data () const [inline]
Returns a pointer to the contents of the string in the form of a 0-terminated C string
Definition at line 153 of file qcstring.h.
{ return m_rep.c_str(); }
References m_rep.
Referenced by DefinitionImpl::_docsAlreadyAdded(), SectionManager::add(), addMacroDefinition(), addXRefItem(), adjustConfiguration(), vhdl::parser::VhdlParser::alias_declaration(), vhdl::parser::VhdlParser::architecture_body(), argumentData(), vhdl::parser::VhdlParser::attribute_declaration(), vhdl::parser::VhdlParser::attribute_specification(), classInformation(), cModule(), HtmlCodeGenerator::codify(), ManGenerator::codify(), RTFGenerator::codify(), LatexCodeGenerator::codify(), codify(), FlowChart::codify(), codifyLines(), codifyMapLines(), vhdl::parser::VhdlParser::component_instantiation_statement(), configStringRecode(), vhdl::parser::VhdlParser::constant_declaration(), contains(), vhdl::parser::VhdlParser::context_declaration(), convertCharEntitiesToUTF8(), convertCppComments(), convertNameToFile(), convertToComment(), Portable::correct_path(), countAliasArguments(), VhdlDocGen::createFlowChart(), HtmlCodeGenerator::docify(), ManGenerator::docify(), RTFGenerator::docify(), HtmlGenerator::docify(), vhdl::parser::VhdlParser::element_declaration(), encodeDirName(), encodeForOutput(), escapeAt(), escapeTooltip(), ExprAstFilter::ExprAstFilter(), ExprAstLiteral::ExprAstLiteral(), ExprAstVariable::ExprAstVariable(), extractBoundingBox(), Markdown::extractPageTitle(), vhdl::parser::VhdlParser::file_declaration(), ManDocVisitor::filter(), TextDocVisitor::filter(), RTFDocVisitor::filter(), HtmlDocVisitor::filter(), filterLatexString(), HtmlDocVisitor::filterQuotedCdataAttr(), find(), Markdown::findEmphasisChar(), Markdown::findEndOfLine(), findRev(), DocTokenizer::findSections(), VhdlDocGen::findVhdlClass(), Portable::fopen(), format_warn(), formatDateTime(), vhdl::parser::VhdlParser::full_type_declaration(), functionSignature(), generateOutput(), generateXML(), Portable::getenv(), getMscImageMapFromFile(), ParserManager::getParsers(), SymbolResolver::Private::getResolvedSymbolRec(), SymbolResolver::Private::getResolvedTypeRec(), handle_warn_as_error(), handleCommentBlock(), DocPara::handleInclude(), handleToc(), PerlModOutput::iaddQuoted(), vhdl::parser::VhdlParser::ifunc(), LayoutDocManager::init(), HtmlHelpRecoder::initialize(), Qhp::initialize(), initWarningFormat(), vhdl::parser::VhdlParser::interface_declaration(), vhdl::parser::VhdlParser::interface_file_declaration(), vhdl::parser::VhdlParser::interface_variable_declaration(), DocParser::internalValidatingParseDoc(), Portable::isAbsolutePath(), isExplicitPage(), letterToLabel(), XRefDummyCodeGenerator::linkableSymbol(), listSymbol(), lookupSymbol(), operator!=(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), RTFDocVisitor::operator()(), operator<(), operator<=(), operator==(), operator>(), operator>=(), vhdl::parser::VhdlParser::package_instantiation_declaration(), ExpressionParser::parse(), LayoutDocManager::parse(), CondParser::parse(), DocInclude::parse(), DocIncOperator::parse(), TemplateParser::parse(), FileCodeParser::parseCode(), FortranCodeParser::parseCode(), PythonCodeParser::parseCode(), LexCodeParser::parseCode(), SQLCodeParser::parseCode(), XMLCodeParser::parseCode(), parseCommentAsText(), parseFuncDecl(), parsePrototype(), ConfigImpl::parseString(), parseTagFile(), VHDLOutlineParser::Private::parseVhdlfile(), Portable::popen(), DotGraph::prepareDotFile(), preProcessFile(), RTFGenerator::preProcessFileInplace(), printModule(), printReferenceTo(), Markdown::process(), vhdl::parser::VhdlParser::process_statement(), Markdown::processBlocks(), DocParser::processCopyDoc(), Markdown::processLink(), Markdown::processQuotations(), Markdown::processSpecialCommand(), pushBuffer(), qstricmp(), qstrnicmp(), readConfiguration(), Portable::recodeUtf8StringToW(), referenceTo(), TemplateNodeBlock::render(), SectionManager::replace(), replaceAliasArguments(), replaceAliases(), replaceAnonymousScopes(), replaceVariables(), DotRunner::run(), DotFilePatcher::run(), runPlantumlContent(), sanitizeString(), Image::save(), ColoredImage::save(), vhdl::parser::VhdlParser::secondary_unit_declaration(), MemberDefImpl::setAnchor(), TemplateContextImpl::setEncoding(), Portable::setenv(), vhdl::parser::VhdlParser::signal_declaration(), simplifyWhiteSpace(), skipToEndMarker(), startCondSection(), OutputGenerator::startPlainFile(), stringToArgumentList(), stripIndentation(), stripPrefix(), vhdl::parser::VhdlParser::subprogram_instantiation_declaration(), substitute(), vhdl::parser::VhdlParser::subtype_declaration(), Portable::system(), TemplateLexer::tokenize(), toLong(), toUInt64(), toULong(), transcodeCharacterBuffer(), transcodeCharacterStringToUTF8(), Portable::unlink(), DocTokenizer::unputString(), Portable::unsetenv(), updateLanguageMapping(), validatingParseDoc(), validatingParseText(), vhdl::parser::VhdlParser::variable_declaration(), writeDocbookCodeString(), MemberDefImpl::writeDocumentation(), ClassDefImpl::writeIncludeFilesForSlice(), writeMscGraphFromFile(), writeMultiLineCodeLink(), writeObjCMethodCall(), ConfigOption::writeStringValue(), and writeXMLCodeString().
data() [2/2]
const char * QCString::data () const [inline]
Returns a pointer to the contents of the string in the form of a 0-terminated C string
Definition at line 153 of file qcstring.h.
{ return m_rep.c_str(); }
References m_rep.
endsWith() [1/4]
bool QCString::endsWith (const char * s) const [inline]
Definition at line 458 of file qcstring.h.
    {
      if (m_rep.empty() || s==0) return s==0;
      size_t l = strlen(s);
      return m_rep.length()>=l && m_rep.compare(m_rep.length()-l, l, s, l)==0;
    }
References m_rep, and s.
Referenced by DocSets::addIndexItem(), addRelatedPage(), DocParser::checkArgumentName(), DocParser::checkUnOrMultipleDocumentedParams(), computeClassRelations(), createTagLessInstance(), extractNamespaceName(), DocParser::findAndCopyImage(), findClassRelation(), findUsedClassesForClass(), findUsingDeclarations(), MemberDefImpl::IMPL::init(), DotFilePatcher::isSVGFile(), isVarWithConstructor(), DefinitionImpl::navigationPathAsString(), LatexDocVisitor::operator()(), readIncludeFile(), DotFilePatcher::run(), searchTemplateSpecs(), simplifyTypeForTable(), DocbookGenerator::startFile(), LatexGenerator::startFile(), RTFGenerator::startFile(), stripKnownExtensions(), NavPathElemContext::Private::text(), MemberDefImpl::warnIfUndocumentedParams(), and HtmlEntityMapper::writeXMLSchema().
endsWith() [2/4]
bool QCString::endsWith (const char * s) const [inline]
Definition at line 458 of file qcstring.h.
    {
      if (m_rep.empty() || s==0) return s==0;
      size_t l = strlen(s);
      return m_rep.length()>=l && m_rep.compare(m_rep.length()-l, l, s, l)==0;
    }
References m_rep, and s.
endsWith() [3/4]
bool QCString::endsWith (const QCString & s) const [inline]
Definition at line 465 of file qcstring.h.
    {
      size_t l = s.length();
      return m_rep.length()>=l && m_rep.compare(m_rep.length()-l, l, s.str())==0;
    }
References m_rep, and s.
endsWith() [4/4]
bool QCString::endsWith (const QCString & s) const [inline]
Definition at line 465 of file qcstring.h.
    {
      size_t l = s.length();
      return m_rep.length()>=l && m_rep.compare(m_rep.length()-l, l, s.str())==0;
    }
References m_rep, and s.
fill() [1/2]
bool QCString::fill (char c, int len = -1) [inline]
Fills a string with a predefined character
Parameters
 in c the character used to fill the string with.
 in len the number of character to fill. Use -1 to fill the whole string.
Note
the string will be resized to contain len characters. The contents of the string will be lost.
Definition at line 175 of file qcstring.h.
    {
      int l = len==-1 ? static_cast<int>(m_rep.size()) : len;
      m_rep = std::string(l,c);
      return TRUE;
    }
References c, len, m_rep, string, and TRUE.
Referenced by FlowChart::alignFuncProc(), codifyMapLines(), ConfigOption::ConfigOption(), generateJSTree(), DocSets::Private::indent(), ManDocVisitor::operator()(), printNavTree(), FlowChart::printNode(), readCodeFragment(), and writeTemplateArgumentList().
fill() [2/2]
bool QCString::fill (char c, int len = -1) [inline]
Fills a string with a predefined character
Parameters
 in c the character used to fill the string with.
 in len the number of character to fill. Use -1 to fill the whole string.
Note
the string will be resized to contain len characters. The contents of the string will be lost.
Definition at line 175 of file qcstring.h.
    {
      int l = len==-1 ? static_cast<int>(m_rep.size()) : len;
      m_rep = std::string(l,c);
      return TRUE;
    }
References c, len, m_rep, string, and TRUE.
find() [1/6]
int QCString::find (char c, int index = 0, bool cs = TRUE) const
Definition at line 43 of file qcstring.cpp.
{
  if (index<0 || index>=static_cast<int>(length())) return -1; // index outside string
  const char *pos;
  if (cs)
  {
    pos = strchr(data()+index,c);
  }
  else
  {
    pos = data()+index;
    c = toLowerChar(c);
    while (*pos && toLowerChar(*pos)!=c) pos++;
    if (!*pos && c) pos=0; // not found
  }
  return pos ? static_cast<int>(pos - data()) : -1;
}
References c, cs, data(), length(), and toLowerChar().
Referenced by MemberDefImpl::_computeIsConstructor(), MemberDefImpl::_computeIsDestructor(), DefinitionImpl::_docsAlreadyAdded(), MemberDefImpl::_writeCategoryRelation(), MemberDefImpl::_writeReimplements(), addClassToContext(), addConceptToContext(), addMacroDefinition(), addSubprogram(), addTemplateNames(), addVariableToFile(), adjustConfiguration(), argListToString(), buildScopeFromQualifiedName(), Config::checkAndCorrect(), VHDLOutlineParser::checkInlineCode(), checkList(), computeClassRelations(), DotFilePatcher::convertMapFile(), MemberList::countEnumValues(), createDVIFile(), FilterListSort::determineSortKey(), MemberDefImpl::displayDefinition(), DocInternalRef::DocInternalRef(), DocGroup::enterCompound(), escapeAliases(), ExistsOnPath(), extractBlock(), extractBoundingBox(), extractClassName(), extractFromParens(), extractLanguageSpecificTitle(), extractPartAfterNewLine(), fillColorStyleMap(), filterMemberDocumentation(), find(), VhdlDocGen::findAllArchitectures(), DocParser::findDocsForMemberOrCompound(), findGlobalMember(), findMember(), findPackageScopeFromPath(), findUsedClassesForClass(), findUsingDeclImports(), generateClassOrGlobalLink(), generateDEFForClass(), generateFileSources(), generateFunctionLink(), CitationManager::generatePage(), TemplateContextImpl::get(), getDefsOld(), getDotImageExtension(), getFilteredImageAttributes(), getFilterFromList(), DocPara::handleCommand(), DocParser::handleParameterType(), handleToc(), CitationManager::insertCrossReferencesForBibFile(), insertTemplateSpecifierInScope(), ClassDefImpl::internalInsertMember(), MemberDefImpl::isDocumentedFriendClass(), MemberDefImpl::isFunctionPtr(), DocImage::isSVG(), isURL(), isVarWithConstructor(), lineBlock(), linkToText(), Htags::loadFilemap(), makeQualifiedNameWithTemplateParameters(), matchExcludedSymbols(), mergeArguments(), mergeCategories(), DirDefImpl::mergeDirectoryInTree(), SymbolResolver::Private::newResolveTypedef(), VHDLOutlineParser::oneLineComment(), SymbolModifiers::operator|=(), DocIncOperator::parse(), DocParamList::parse(), TemplateParser::parse(), VhdlDocGen::parseFuncProto(), parseMain(), VhdlDocGen::parseUCF(), VhdlDocGen::prepareComment(), Markdown::processLink(), processTagLessClasses(), readAliases(), readTagFile(), replaceRef(), replaceVariables(), resolveRef(), resolveSymlink(), resolveTypeDef(), DotFilePatcher::run(), searchTemplateSpecs(), MemberList::setAnonymousEnumType(), DefinitionImpl::setName(), split(), splitString(), LatexDocVisitor::startDiaFile(), LatexDocVisitor::startDotFile(), LatexDocVisitor::startMscFile(), stripIrrelevantString(), stripTemplateSpecifiersFromScope(), subrHandleCommentBlock(), substEnvVarsInStrList(), Portable::system(), TemplateNodeCloseSubIndex::TemplateNodeCloseSubIndex(), TemplateNodeIndexEntry::TemplateNodeIndexEntry(), TemplateNodeOpenSubIndex::TemplateNodeOpenSubIndex(), TemplateNodeWith::TemplateNodeWith(), Portable::unsetenv(), MemberDefImpl::warnIfUndocumented(), MemberDefImpl::warnIfUndocumentedParams(), writeDefArgumentList(), FileDefImpl::writeDetailedDescription(), HtmlDocVisitor::writeDiaFile(), MemberDefImpl::writeDocumentation(), HtmlDocVisitor::writeDotFile(), writeExceptionList(), writeExceptionListImpl(), HtmlGenerator::writeExternalSearchPage(), writeFileIndex(), VhdlDocGen::writeFormatString(), writeGraphInfo(), HtmlDocVisitor::writeMscFile(), LatexDocVisitor::writePlantUMLFile(), VhdlDocGen::writeRecordUnit(), VhdlDocGen::writeSource(), and DefinitionImpl::writeSourceDef().
find() [2/6]
int QCString::find (char c, int index = 0, bool cs = TRUE) const
find() [3/6]
int QCString::find (const char * str, int index = 0, bool cs = TRUE) const
Definition at line 61 of file qcstring.cpp.
{
  int l = length();
  if (index<0 || index>=l) return -1; // index outside string
  if (!str) return -1; // no string to search for
  if (!*str) return index; // empty string matching at index
  const char *pos;
  if (cs) // case sensitive
  {
    pos = strstr(data()+index,str);
  }
  else // case insensitive
  {
    pos = data();
    int len = qstrlen(str);
    while (*pos)
    {
      if (qstrnicmp(pos,str,len)==0) break;
      pos++;
    }
    if (!*pos) pos = 0; // not found
  }
  return pos ? static_cast<int>(pos - data()) : -1;
}
References cs, data(), len, length(), qstrlen(), qstrnicmp(), and str().
find() [4/6]
int QCString::find (const char * str, int index = 0, bool cs = TRUE) const
find() [5/6]
int QCString::find (const QCString & str, int index = 0, bool cs = TRUE) const
Definition at line 86 of file qcstring.cpp.
{
  return find(str.data(),index,cs);
}
References cs, find(), and str().
find() [6/6]
int QCString::find (const QCString & str, int index = 0, bool cs = TRUE) const
findRev() [1/4]
int QCString::findRev (char c, int index = -1, bool cs = TRUE) const
Definition at line 91 of file qcstring.cpp.
{
  const char *b = data();
  const char *pos;
  int len = length();
  if (len==0) return -1; // empty string
  if (index<0) // start from end
  {
    if (cs)
    {
      pos = strrchr(b,c);
      return pos ? static_cast<int>(pos - b) : -1;
    }
    index=len;
  }
  else if (index>len) // bad index
  {
    return -1;
  }
  pos = b+index;
  if (cs)
  {
    while (pos>=b && *pos!=c) pos--;
  }
  else
  {
    c = toLowerChar(c);
    while (pos>=b && toLowerChar(*pos)!=c) pos--;
  }
  return pos>=b ? static_cast<int>(pos - b) : -1;
}
References b, c, cs, data(), len, length(), and toLowerChar().
Referenced by abbreviate(), addClassToContext(), addEnumValuesToEnums(), addMemberFunction(), addModule(), addTemplateNames(), TooltipManager::addTooltip(), alignText(), FilterStripPath::apply(), buildFileList(), computeCommonDirPrefix(), convertFileId2Var(), VhdlDocGen::correctMemberProperties(), DirDefImpl::DirDefImpl(), MemberDefImpl::displayDefinition(), LayoutParser::endMemberDecl(), LayoutParser::endMemberDef(), DocInclude::extension(), extractFromParens(), extractNamespaceName(), DocParser::findAndCopyImage(), findClassRelation(), findDirDocumentation(), DocParser::findDocsForMemberOrCompound(), findEnumDocumentation(), findEnums(), findGlobalMember(), findPackageScopeFromPath(), findUsedClassesForClass(), findUsingDirectives(), generateClassOrGlobalLink(), generateFunctionLink(), generateMemberLink(), PlantumlManager::generatePlantUMLOutput(), getBaseNameOfOutput(), getDefsOld(), getFileNameExtension(), getParserForFile(), getScopeDefs(), if(), FileDefImpl::isDocumentationFile(), NamespaceDefImpl::isLinkableInProject(), Htags::loadFilemap(), NamespaceDefImpl::localName(), markdownFileNameToId(), mergeScopes(), SymbolResolver::Private::newResolveTypedef(), HtmlDocVisitor::operator()(), PerlModDocVisitor::operator()(), DocbookDocVisitor::operator()(), parseFile(), VhdlDocGen::parseForBinding(), VhdlDocGen::parseForConfig(), VhdlDocGen::parseFuncProto(), VHDLOutlineParser::popLabel(), readCodeFragment(), TemplateNodeCreate::render(), resolveRef(), resolveTypeDef(), DefinitionImpl::IMPL::setDefFileName(), LatexDocVisitor::startDiaFile(), LatexDocVisitor::startDotFile(), ManGenerator::startDoxyAnchor(), LatexDocVisitor::startMscFile(), stripPath(), version(), writeDefArgumentList(), RTFDocVisitor::writeDiaFile(), LatexDocVisitor::writeDiaFile(), HtmlDocVisitor::writeDiaFile(), MemberDefImpl::writeDocumentation(), RTFDocVisitor::writeDotFile(), HtmlDocVisitor::writeDotFile(), RTFDocVisitor::writeMscFile(), LatexDocVisitor::writeMscFile(), HtmlDocVisitor::writeMscFile(), RTFDocVisitor::writePlantUMLFile(), LatexDocVisitor::writePlantUMLFile(), HtmlDocVisitor::writePlantUMLFile(), PlantumlManager::writePlantUMLSource(), FlowChart::writeShape(), and DotNode::writeUrl().
findRev() [2/4]
int QCString::findRev (char c, int index = -1, bool cs = TRUE) const
findRev() [3/4]
int QCString::findRev (const char * str, int index = -1, bool cs = TRUE) const
Definition at line 123 of file qcstring.cpp.
{
  int slen = qstrlen(str);
  int len = length();
  if (index<0) index = len-slen; // start from end
  else if (index>len) return -1; // bad index
  else if (index+slen>len) index=len-slen; // str would be too long
  if (index<0) return -1; // no match possible
  const char *pos = data()+index;
  if (cs) // case sensitive
  {
    for (int i=index; i>=0; i--) if (qstrncmp(pos--,str,slen)==0) return i;
  }
  else // case insensitive
  {
    for (int i=index; i>=0; i--) if (qstrnicmp(pos,str,slen)==0) return i;
  }
  return -1;
}
References cs, data(), len, length(), qstrlen(), qstrncmp(), qstrnicmp(), and str().
findRev() [4/4]
int QCString::findRev (const char * str, int index = -1, bool cs = TRUE) const
insert() [1/6]
QCString & QCString::insert (size_t index, char c) [inline]
Definition at line 338 of file qcstring.h.
    {
      char s[2] = { c, '\0' };
      return insert(index,s);
    }
References c, insert(), and s.
insert() [2/6]
QCString & QCString::insert (size_t index, char c) [inline]
Definition at line 338 of file qcstring.h.
    {
      char s[2] = { c, '\0' };
      return insert(index,s);
    }
References c, insert(), and s.
insert() [3/6]
QCString & QCString::insert (size_t index, const char * s) [inline]
Definition at line 318 of file qcstring.h.
    {
      size_t len = s ? qstrlen(s) : 0;
      if (len>0)
      {
        size_t ol = m_rep.size();
        if (index>ol) // insert beyond end of string and fill gap with spaces
        {
          m_rep.resize(index+len);
          std::memset(&m_rep[ol],' ',index-ol);
          std::memcpy(&m_rep[index],s,len+1);
        }
        else // insert inside the string
        {
          m_rep.insert(index,s);
        }
      }
      return *this;
    }
References len, m_rep, qstrlen(), and s.
insert() [4/6]
QCString & QCString::insert (size_t index, const char * s) [inline]
Definition at line 318 of file qcstring.h.
    {
      size_t len = s ? qstrlen(s) : 0;
      if (len>0)
      {
        size_t ol = m_rep.size();
        if (index>ol) // insert beyond end of string and fill gap with spaces
        {
          m_rep.resize(index+len);
          std::memset(&m_rep[ol],' ',index-ol);
          std::memcpy(&m_rep[index],s,len+1);
        }
        else // insert inside the string
        {
          m_rep.insert(index,s);
        }
      }
      return *this;
    }
References len, m_rep, qstrlen(), and s.
insert() [5/6]
QCString & QCString::insert (size_t index, const QCString & s) [inline]
Definition at line 300 of file qcstring.h.
    {
      if (s.length()>0)
      {
        size_t ol = m_rep.size();
        if (index>ol) // insert beyond end of string and fill gap with spaces
        {
          m_rep.resize(index+s.length());
          std::memset(&m_rep[ol],' ',index-ol);
          std::memcpy(&m_rep[index],s.data(),s.length()+1);
        }
        else // insert inside the string
        {
          m_rep.insert(index,s.str());
        }
      }
      return *this;
    }
References gdFont::data, m_rep, and s.
Referenced by drawClusterOpening(), expandAlias(), findPackageScopeFromPath(), initPredefined(), insert(), SymbolResolver::Private::newResolveTypedef(), prepend(), replace(), resolveClassNestingRelations(), and resolveSymlink().
insert() [6/6]
QCString & QCString::insert (size_t index, const QCString & s) [inline]
Definition at line 300 of file qcstring.h.
    {
      if (s.length()>0)
      {
        size_t ol = m_rep.size();
        if (index>ol) // insert beyond end of string and fill gap with spaces
        {
          m_rep.resize(index+s.length());
          std::memset(&m_rep[ol],' ',index-ol);
          std::memcpy(&m_rep[index],s.data(),s.length()+1);
        }
        else // insert inside the string
        {
          m_rep.insert(index,s.str());
        }
      }
      return *this;
    }
References gdFont::data, m_rep, and s.
isEmpty() [1/2]
bool QCString::isEmpty () const [inline]
Returns TRUE iff the string is empty
Definition at line 144 of file qcstring.h.
{ return m_rep.empty(); }
References m_rep.
Referenced by DefinitionImpl::_setBriefDescription(), DefinitionImpl::_setDocumentation(), DefinitionImpl::_setInbodyDocumentation(), MemberDefImpl::_writeCategoryRelation(), HtmlCodeGenerator::_writeCodeLink(), MemberDefImpl::_writeGroupInclude(), DefinitionImpl::_writeSourceRefList(), MemberDefImpl::_writeTemplatePrefix(), abbreviate(), SymbolResolver::Private::accessibleViaUsingClass(), SymbolResolver::Private::accessibleViaUsingNamespace(), FileDefImpl::acquireFileVersion(), addAnchor(), DotClassGraph::addClass(), addClassToContext(), addConceptToContext(), DocSets::addContentsItem(), EclipseHelp::addContentsItem(), HtmlHelp::addContentsItem(), addDefine(), DocGroup::addDocs(), DotGroupCollaboration::addEdge(), addEnumDocs(), addEnumValuesToEnums(), FlowChart::addFlowChart(), DotGfxHierarchyTable::addHierarchy(), addHtmlExtensionIfMissing(), FileDefImpl::addIncludedByDependency(), FileDefImpl::addIncludeDependency(), addIncludeFile(), PerlModGenerator::addIncludeInfo(), HtmlHelp::addIndexItem(), Qhp::addIndexItem(), LatexGenerator::addIndexItem(), RTFGenerator::addIndexItem(), addInstance(), HtmlHelpIndex::addItem(), addKnRArgInfo(), PerlModDocVisitor::addLink(), addMemberDocs(), addMemberFunction(), addMemberToGroups(), addPerlModDocBlock(), addRefItem(), addRelatedPage(), addSection(), DefinitionImpl::addSectionsToIndex(), DefinitionImpl::addSourceReferencedBy(), DefinitionImpl::addSourceReferences(), addToMap(), TooltipManager::addTooltip(), ClassDefImpl::addTypeConstraint(), addVariable(), addVariableToClass(), addVariableToFile(), addXRefItem(), adjustConfiguration(), FilterDefault::apply(), applyModifiers(), argListToString(), argumentData(), buildClassDocList(), buildClassList(), buildDefineList(), buildDirectories(), buildExampleList(), buildFileList(), buildGroupListFiltered(), buildNamespaceList(), buildPageList(), buildScopeFromQualifiedName(), Config::checkAndCorrect(), DocParser::checkArgumentName(), VHDLOutlineParser::checkInlineCode(), checkList(), DocParser::checkUnOrMultipleDocumentedParams(), ClassDefImpl::ClassDefImpl(), ClassDefImpl::className(), HtmlCodeGenerator::codify(), ManGenerator::codify(), RTFGenerator::codify(), LatexCodeGenerator::codify(), codify(), FlowChart::codify(), codifyLines(), codifyMapLines(), combineDeclarationAndDefinition(), ConfigImpl::compareDoxyfile(), computeClassRelations(), DotGraph::computeGraph(), computePageRelations(), DefinitionImpl::computeTooltip(), computeVerifiedDotPath(), ConceptDefImpl::ConceptDefImpl(), configStringRecode(), containsWord(), convertCharEntitiesToUTF8(), convertMapFile(), ConfigEnum::convertStrToVal(), ConfigInt::convertStrToVal(), ConfigBool::convertStrToVal(), convertToComment(), copyLogo(), copyStyleSheet(), correctURL(), MemberGroupInfoContext::Private::createDocs(), ArgumentContext::Private::createDocs(), createDVIFile(), VHDLOutlineParser::createFunction(), DefinitionContext< T >::createInbodyDocs(), FormulaManager::createLatexFile(), createOutputDirectory(), SymbolContext::Private::createScope(), MemberContext::Private::createTrailingReturnType(), dateTimeFromString(), DefinitionContext< T >::DefinitionContext(), deliverablesPresent(), MemberDefImpl::displayDefinition(), MemberGroup::distributeMemberGroupDocumentation(), DocCite::DocCite(), DocFormula::DocFormula(), HtmlCodeGenerator::docify(), ManGenerator::docify(), RTFGenerator::docify(), HtmlGenerator::docify(), DocLink::DocLink(), DocLinkedWord::DocLinkedWord(), DocRef::DocRef(), DocWord::DocWord(), DotClassGraph::DotClassGraph(), elemIsVisible(), ConfigString::emptyValueToDefault(), encodeForOutput(), RTFGenerator::endDoxyAnchor(), LayoutParser::endElement(), HtmlGenerator::endIndexItem(), LatexGenerator::endIndexItem(), RTFGenerator::endIndexItem(), RTFGenerator::endIndexSection(), RTFDocVisitor::endLink(), LatexDocVisitor::endLink(), HtmlGenerator::endMemberDeclaration(), HtmlGenerator::endMemberTemplateParams(), LatexGenerator::endPageRef(), RTFGenerator::endPageRef(), endQuickIndexItem(), RTFGenerator::endTitleHead(), DocGroup::enterCompound(), escapeAt(), escapeTooltip(), DocbookGenerator::exceptionEntry(), HtmlGenerator::exceptionEntry(), LatexGenerator::exceptionEntry(), RTFGenerator::exceptionEntry(), Htags::execute(), ExistsOnPath(), expandAliasRec(), expandExpression(), externalRef(), DefinitionImpl::externalReference(), extractCanonicalArgType(), extractCanonicalType(), extractClassNameFromType(), extractNamespaceName(), MemberDefImpl::fieldType(), FileDefImpl::FileDefImpl(), ManDocVisitor::filter(), TextDocVisitor::filter(), RTFDocVisitor::filter(), HtmlDocVisitor::filter(), filterLatexString(), filterMemberDocumentation(), HtmlDocVisitor::filterQuotedCdataAttr(), findClassRelation(), findDefineDocumentation(), DocParser::findDocsForMemberOrCompound(), Markdown::findEmphasisChar(), Markdown::findEndOfLine(), findEnumDocumentation(), findEnums(), DocGroup::findExistingGroup(), findFile(), findFileDef(), findGlobalMember(), findGroupScope(), FlowChart::findLabel(), findMainPage(), findMember(), findMemberDocumentation(), findMembersWithSpecificName(), findPackageScope(), findPackageScopeFromPath(), DocTokenizer::findSections(), findUsedClassesForClass(), findUsingDeclarations(), findUsingDeclImports(), findUsingDirectives(), generateBriefDoc(), generateClassOrGlobalLink(), generateDEFForMember(), OutputList::generateDoc(), generateFileRef(), generateFunctionLink(), generateJSNavTree(), generateLink(), generateMemberLink(), generateMemLink(), generateOutput(), CitationManager::generatePage(), PerlModGenerator::generatePerlModForMember(), PerlModGenerator::generatePerlModSection(), generateTemplateFiles(), generateXMLForClass(), generateXMLForMember(), genericCompareMembers(), TemplateContextImpl::get(), DotGfxHierarchyTable::getBaseName(), getCanonicalTemplateSpec(), getCanonicalTypeForIdentifier(), MemberDefImpl::getClassDefOfAnonymousType(), getConvertLatexMacro(), getCurrentChar(), getCurrentDateTime(), getDefsNew(), getDefsOld(), getExtension(), getFileFilter(), getFileNameExtension(), getFortranDefs(), getFortranNamespaceDefs(), getFortranTypeDefs(), getFullProjectName(), getLanguageFromFileName(), getLink(), getLinkInScope(), getNextChar(), MemberDefImpl::getOutputFileBase(), ParserManager::getParsers(), Qhp::getQchFileName(), MemberDefImpl::getReference(), SymbolResolver::Private::getResolvedSymbol(), SymbolResolver::Private::getResolvedSymbolRec(), SymbolResolver::Private::getResolvedType(), SymbolResolver::Private::getResolvedTypeRec(), getScopeDefs(), getSubdir(), GroupDefImpl::GroupDefImpl(), DocPara::handleCommand(), VHDLOutlineParser::handleCommentBlock(), DocPara::handleHtmlStartTag(), DocParser::handleImage(), DocPara::handleInclude(), DocPara::handleLink(), DocParser::handleLinkedWord(), DocPara::handleShowDate(), DocPara::handleStartCode(), handleToc(), DefinitionImpl::hasBriefDescription(), DirDefImpl::hasDetailedDescription(), MemberDefImpl::hasDetailedDescription(), Argument::hasDocumentation(), DefinitionImpl::hasDocumentation(), MemberDefImpl::hasOneLineInitializer(), PageDefImpl::hasTitle(), DefinitionImpl::hasUserDocumentation(), PerlModOutput::iaddQuoted(), vhdl::parser::VhdlParser::ifunc(), inheritDocumentation(), ConfigImpl::init(), RTFGenerator::init(), ClassDefImpl::IMPL::init(), MemberDefImpl::IMPL::init(), initDoxygen(), DocSets::initialize(), EclipseHelp::initialize(), HtmlHelpRecoder::initialize(), Qhp::initialize(), initPredefined(), initUCF(), initWarningFormat(), CitationManager::insertCrossReferencesForBibFile(), insertTemplateSpecifierInScope(), DocParser::internalValidatingParseDoc(), SymbolResolver::Private::isAccessibleFromWithExpScope(), MemberDefImpl::isBriefSectionVisible(), isClassSection(), ConfigList::isDefault(), FileDefImpl::isIncluded(), ClassDefImpl::isLinkableInProject(), NamespaceDefImpl::isLinkableInProject(), isLinkRef(), DefinitionImpl::isReference(), isVarWithConstructor(), DiagramItem::label(), CitationManager::latexBibFiles(), Translator::latexCommandName(), TranslatorGreek::latexCommandName(), TranslatorKoreanEn::latexCommandName(), TranslatorKorean::latexCommandName(), TranslatorVietnamese::latexCommandName(), letterToLabel(), XRefDummyCodeGenerator::linkableSymbol(), linkifyText(), linkToText(), lookupSymbols(), vhdl::parser::VhdlParser::loop_statement(), mainPageHasOwnTitle(), makeFileName(), makeIndex(), makeQualifiedNameWithTemplateParameters(), makeRef(), matchArgument2(), matchExcludedSymbols(), mergeArguments(), mergeScopes(), NamespaceDefImpl::NamespaceDefImpl(), DefinitionImpl::navigationPathAsString(), TemplateContextImpl::needsRecoding(), DocbookGenerator::openSection(), RTFDocVisitor::operator()(), LatexDocVisitor::operator()(), PerlModDocVisitor::operator()(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), ManDocVisitor::operator()(), XmlDocVisitor::operator()(), organizeSubGroupsFiltered(), ExpressionParser::parse(), CondParser::parse(), DocInclude::parse(), DocIncOperator::parse(), DocXRefItem::parse(), DocRef::parse(), DocSection::parse(), DocSecRefItem::parse(), TemplateParser::parse(), CCodeParser::parseCode(), FileCodeParser::parseCode(), FortranCodeParser::parseCode(), PythonCodeParser::parseCode(), LexCodeParser::parseCode(), SQLCodeParser::parseCode(), XMLCodeParser::parseCode(), parseCommentAsText(), CommentScanner::parseCommentBlock(), parseFuncDecl(), parseInput(), MarkdownOutlineParser::parseInput(), VHDLOutlineParser::parseInput(), parsePrototype(), VhdlDocGen::parseUCF(), CondParser::parseVar(), Htags::path2URL(), DefinitionImpl::pathFragment(), vhdl::parser::VhdlParser::pathname_element(), printNavTree(), Markdown::process(), Markdown::processBlocks(), processConcatOperators(), Markdown::processLink(), processList(), Markdown::processSpecialCommand(), processTagLessClasses(), DefinitionImpl::qualifiedName(), readCodeFragment(), readConfiguration(), readInputFile(), readTagFile(), Portable::recodeUtf8StringToW(), ParserManager::registerExtension(), removeAnonymousScopes(), TemplateNodeCreate::render(), TemplateNodeIndexEntry::render(), TemplateNodeOpenSubIndex::render(), TemplateNodeCloseSubIndex::render(), TemplateNodeResource::render(), TemplateNodeExtend::render(), TemplateNodeInclude::render(), TemplateNodeMarkers::render(), TemplateNodeEncoding::render(), replaceAnonymousScopes(), replaceColorMarkers(), replaceFunctionMacro(), replaceRef(), resolveClassNestingRelations(), resolveLink(), resolveRef(), resolveTypeDef(), MemberDefImpl::resolveUnnamedParameters(), DotRunner::run(), runPlantumlContent(), sanitizeString(), searchTemplateSpecs(), MemberDefImpl::setAnchor(), setCallContextForVar(), SearchIndex::setCurrentDoc(), SearchIndexExternal::setCurrentDoc(), DefinitionImpl::setDocumentation(), setDotFontPath(), TemplateContextImpl::setEncoding(), Portable::setenv(), TemplateContextImpl::setEscapeIntf(), GroupDefImpl::setGroupTitle(), DefinitionImpl::setInbodyDocumentation(), ClassDefImpl::setIncludeFile(), ConceptDefImpl::setIncludeFile(), DefinitionImpl::setName(), showFileDefMatches(), simplifyWhiteSpace(), XMLCodeGenerator::startCodeLine(), DocbookGenerator::startDescTable(), LatexGenerator::startDoxyAnchor(), DocbookGenerator::startDoxyAnchor(), DocbookGenerator::startFile(), startFile(), HtmlGenerator::startIndexItem(), LatexGenerator::startIndexItem(), RTFGenerator::startIndexSection(), DocbookDocVisitor::startLink(), RTFDocVisitor::startLink(), XmlDocVisitor::startLink(), LatexDocVisitor::startLink(), HtmlDocVisitor::startLink(), LayoutParser::startMemberDeclEntry(), LayoutParser::startMemberDefEntry(), HtmlGenerator::startMemberDescription(), DocbookGenerator::startMemberDoc(), LatexGenerator::startMemberDoc(), RTFGenerator::startMemberDoc(), DocbookGenerator::startMemberDocSimple(), HtmlGenerator::startMemberHeader(), HtmlGenerator::startMemberItem(), LayoutParser::startNavEntry(), HtmlGenerator::startParagraph(), LatexGenerator::startParameterType(), RTFGenerator::startParameterType(), startQuickIndexItem(), LayoutParser::startSectionEntry(), LatexGenerator::startTextLink(), RTFGenerator::startTextLink(), HtmlGenerator::startTextLink(), LatexGenerator::startTitleHead(), stringToArgumentList(), stripAnonymousNamespaceScope(), stripIndentation(), stripPrefix(), subrHandleCommentBlock(), subrHandleCommentBlockResult(), substEnvVarsInString(), substEnvVarsInStrList(), substituteHtmlKeywords(), substituteKeywords(), substituteLatexKeywords(), substituteTemplateArgumentsInString(), substituteTemplatesInString(), Portable::system(), TemplateNodeBlock::TemplateNodeBlock(), TemplateNodeCloseSubIndex::TemplateNodeCloseSubIndex(), TemplateNodeFor::TemplateNodeFor(), TemplateNodeOpenSubIndex::TemplateNodeOpenSubIndex(), TemplateNodeRange::TemplateNodeRange(), PageContext::Private::title(), TemplateLexer::tokenize(), transcodeCharacterBuffer(), transcodeCharacterStringToUTF8(), transferArgumentDocumentation(), TranslatorArmenian::trGeneratedAt(), TranslatorArabic::trGeneratedAt(), TranslatorBulgarian::trGeneratedAt(), TranslatorBrazilian::trGeneratedAt(), TranslatorCatalan::trGeneratedAt(), TranslatorChinese::trGeneratedAt(), TranslatorCzech::trGeneratedAt(), TranslatorGerman::trGeneratedAt(), TranslatorDanish::trGeneratedAt(), TranslatorEnglish::trGeneratedAt(), TranslatorEsperanto::trGeneratedAt(), TranslatorSpanish::trGeneratedAt(), TranslatorPersian::trGeneratedAt(), TranslatorFinnish::trGeneratedAt(), TranslatorFrench::trGeneratedAt(), TranslatorGreek::trGeneratedAt(), TranslatorHindi::trGeneratedAt(), TranslatorCroatian::trGeneratedAt(), TranslatorHungarian::trGeneratedAt(), TranslatorIndonesian::trGeneratedAt(), TranslatorItalian::trGeneratedAt(), TranslatorJapanese::trGeneratedAt(), TranslatorKorean::trGeneratedAt(), TranslatorLithuanian::trGeneratedAt(), TranslatorLatvian::trGeneratedAt(), TranslatorMacedonian::trGeneratedAt(), TranslatorDutch::trGeneratedAt(), TranslatorNorwegian::trGeneratedAt(), TranslatorPolish::trGeneratedAt(), TranslatorPortuguese::trGeneratedAt(), TranslatorRomanian::trGeneratedAt(), TranslatorRussian::trGeneratedAt(), TranslatorSerbianCyrillic::trGeneratedAt(), TranslatorSlovene::trGeneratedAt(), TranslatorSlovak::trGeneratedAt(), TranslatorSerbian::trGeneratedAt(), TranslatorSwedish::trGeneratedAt(), TranslatorTurkish::trGeneratedAt(), TranslatorChinesetraditional::trGeneratedAt(), TranslatorUkrainian::trGeneratedAt(), TranslatorVietnamese::trGeneratedAt(), TranslatorAfrikaans::trGeneratedAt(), tryPath(), unsetDotFontPath(), Portable::unsetenv(), updateAttribute(), updateLanguageMapping(), Config::updateObsolete(), DotAttributes::updateValue(), LayoutNavEntry::url(), validatingParseDoc(), validatingParseText(), version(), visitPreStart(), DocbookDocVisitor::visitPreStart(), MemberDefImpl::warnIfUndocumentedParams(), SearchIndexExternal::write(), writeAlphabeticalClassList(), LatexGenerator::writeAnchor(), RTFGenerator::writeAnchor(), DotNode::writeArrow(), DotNode::writeBox(), NamespaceDefImpl::writeBriefDescription(), RTFGenerator::writeCodeLink(), LatexCodeGenerator::writeCodeLink(), writeColumn(), MemberDefImpl::writeDeclaration(), ClassDefImpl::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), ConceptDefImpl::writeDeclarationLink(), MemberList::writeDeclarations(), DotNode::writeDEF(), writeDefArgumentList(), ClassDefImpl::writeDetailedDescription(), DefinitionImpl::writeDocAnchorsToTagFile(), DotNode::writeDocbook(), writeDocbookCodeString(), writeDocbookLink(), MemberDefImpl::writeDocumentation(), FileDefImpl::writeDocumentation(), GroupDefImpl::writeDocumentation(), MemberList::writeDocumentation(), MemberDefImpl::writeEnumDeclaration(), HtmlGenerator::writeExternalSearchPage(), Markdown::writeFencedCodeBlock(), HtmlHelpIndex::writeFields(), writeFileIndex(), FlowChart::writeFlowLinks(), writeFont(), VhdlDocGen::writeFormatString(), VhdlDocGen::writeFunctionProto(), DotGraph::writeGraphHeader(), ClassDefImpl::writeIncludeFiles(), ConceptDefImpl::writeIncludeFiles(), ClassDefImpl::writeIncludeFilesForSlice(), writeIncludeInfo(), writeIndex(), HtmlGenerator::writeInheritedSectionTitle(), writeJavaScriptSearchIndex(), RTFGenerator::writeLineNumber(), LatexCodeGenerator::writeLineNumber(), DocbookCodeGenerator::writeLineNumber(), XMLCodeGenerator::writeLineNumber(), TextGeneratorHtml::writeLink(), TextGeneratorLatex::writeLink(), writeMapArea(), Markdown::writeMarkdownImage(), MemberDefImpl::writeMemberDocSimple(), ClassDefImpl::writeMemberList(), writeMemberList(), writeMemberReference(), ClassDefImpl::writeMoreLink(), writeMscImageMapFromFile(), writeMultiLineCodeLink(), writeObjCMethodCall(), DocbookGenerator::writeObjectLink(), HtmlGenerator::writeObjectLink(), LatexGenerator::writeObjectLink(), RTFGenerator::writeObjectLink(), PageDefImpl::writePageDocumentation(), writePages(), PlantumlManager::writePlantUMLSource(), VhdlDocGen::writeRecordUnit(), FlowChart::writeShape(), writeSingleFileIndex(), VhdlDocGen::writeSource(), FileDefImpl::writeSourceBody(), DefinitionImpl::writeSourceDef(), FileDefImpl::writeSourceHeader(), HtmlGenerator::writeStartAnnoItem(), LatexGenerator::writeStartAnnoItem(), RTFGenerator::writeStartAnnoItem(), ConfigOption::writeStringValue(), HtmlGenerator::writeSummaryLink(), writeTagFile(), ClassDefImpl::writeTagFile(), ConceptDefImpl::writeTagFile(), NamespaceDefImpl::writeTagFile(), MemberDefImpl::writeTagFile(), ConfigImpl::writeTemplate(), ConfigInt::writeTemplate(), ConfigBool::writeTemplate(), ConfigList::writeTemplate(), ConfigEnum::writeTemplate(), ConfigString::writeTemplate(), ClassDefImpl::writeTemplateSpec(), DefinitionImpl::writeToc(), DocSets::writeToken(), HtmlCodeGenerator::writeTooltip(), DotNode::writeUrl(), VhdlDocGen::writeVHDLDeclaration(), VhdlDocGen::writeVHDLDeclarations(), writeVhdlEntityToolTip(), VhdlDocGen::writeVhdlLink(), writeWord(), DotNode::writeXML(), writeXMLCodeString(), writeXMLDocBlock(), writeXMLLink(), and HtmlEntityMapper::writeXMLSchema().
isEmpty() [2/2]
bool QCString::isEmpty () const [inline]
Returns TRUE iff the string is empty
Definition at line 144 of file qcstring.h.
{ return m_rep.empty(); }
References m_rep.
isNull() [1/2]
bool QCString::isNull () const [inline]
Returns TRUE iff the string is empty. Equivalent to isEmpty().
Definition at line 141 of file qcstring.h.
{ return m_rep.empty(); }
References m_rep.
Referenced by applyModifiers(), and SymbolModifiers::operator|=().
isNull() [2/2]
bool QCString::isNull () const [inline]
Returns TRUE iff the string is empty. Equivalent to isEmpty().
Definition at line 141 of file qcstring.h.
{ return m_rep.empty(); }
References m_rep.
left() [1/2]
QCString QCString::left (size_t len) const [inline]
Definition at line 212 of file qcstring.h.
    {
      return m_rep.empty() ? QCString() : QCString(m_rep.substr(0,len));
    }
References len, m_rep, and QCString().
Referenced by MemberDefImpl::_computeIsConstructor(), MemberDefImpl::_writeCategoryRelation(), MemberDefImpl::_writeReimplements(), abbreviate(), addClassToContext(), addEnumValuesToEnums(), DocSets::addIndexItem(), addMacroDefinition(), addMemberFunction(), addRelatedPage(), addTemplateNames(), adjustConfiguration(), alignText(), argListToString(), buildFileList(), DocParser::checkArgumentName(), checkList(), DocParser::checkUnOrMultipleDocumentedParams(), HtmlCodeGenerator::codify(), ManGenerator::codify(), RTFGenerator::codify(), codifyLines(), computeCommonDirPrefix(), DotFilePatcher::convertMapFile(), convertNameToFile(), VhdlDocGen::correctMemberProperties(), createTagLessInstance(), DocParser::defaultHandleTitleAndSize(), DirDefImpl::DirDefImpl(), MemberDefImpl::displayDefinition(), DocInternalRef::DocInternalRef(), LayoutParser::endElement(), LayoutParser::endMemberDecl(), LayoutParser::endMemberDef(), DocGroup::enterCompound(), expandExpression(), extractClassName(), extractLanguageSpecificTitle(), extractNamespaceName(), extractTitleId(), fillColorStyleMap(), filterMemberDocumentation(), DocParser::findAndCopyImage(), findClassRelation(), findDirDocumentation(), DocParser::findDocsForMemberOrCompound(), findEnumDocumentation(), findEnums(), findGlobalMember(), findMember(), findPackageScopeFromPath(), findScopeFromQualifiedName(), findUsingDeclImports(), findUsingDirectives(), generateClassOrGlobalLink(), generateFunctionLink(), generateMemberLink(), CitationManager::generatePage(), TemplateContextImpl::get(), getBaseNameOfOutput(), MemberDefImpl::getClassDefOfAnonymousType(), getDefsOld(), getDotImageExtension(), getFilteredImageAttributes(), ParserManager::getParsers(), getScopeDefs(), DocPara::handleCommand(), DocParser::handleLinkedWord(), handleToc(), if(), initUCF(), insertTemplateSpecifierInScope(), Markdown::isAtxHeader(), MemberDefImpl::isDocumentedFriendClass(), isURL(), isVarWithConstructor(), leftScopeMatch(), Htags::loadFilemap(), markdownFileNameToId(), matchExcludedSymbols(), mergeArguments(), mergeCategories(), DirDefImpl::mergeDirectoryInTree(), ClassDefImpl::mergeMembers(), mergeScopes(), DefinitionImpl::navigationPathAsString(), SymbolResolver::Private::newResolveTypedef(), LatexDocVisitor::operator()(), TemplateParser::parse(), parseCommentAsText(), parseFuncDecl(), VhdlDocGen::parseFuncProto(), MarkdownOutlineParser::parseInput(), parseMain(), VhdlDocGen::parseUCF(), VHDLOutlineParser::popLabel(), FlowChart::printNode(), Markdown::processLink(), Markdown::processQuotations(), readAliases(), readTagFile(), replaceNamespaceAliases(), replaceRef(), resolveRef(), resolveSymlink(), resolveTypeDef(), DotFilePatcher::run(), searchInputFiles(), searchTemplateSpecs(), MemberDefImpl::setInitializer(), simplifyTypeForTable(), splitKnRArg(), splitString(), DocbookDocVisitor::startDiaFile(), LatexDocVisitor::startDiaFile(), DocbookDocVisitor::startDotFile(), LatexDocVisitor::startDotFile(), DocbookDocVisitor::startMscFile(), LatexDocVisitor::startMscFile(), stripExtensionGeneral(), stripFromPath(), stripIrrelevantString(), stripKnownExtensions(), TemplateNodeIndexEntry::TemplateNodeIndexEntry(), TemplateNodeWith::TemplateNodeWith(), NavPathElemContext::Private::text(), DotAttributes::updateValue(), MemberDefImpl::writeDeclaration(), FileDefImpl::writeDetailedDescription(), HtmlDocVisitor::writeDiaFile(), MemberDefImpl::writeDocumentation(), HtmlDocVisitor::writeDotFile(), writeExceptionListImpl(), HtmlGenerator::writeExternalSearchPage(), HtmlHelpIndex::writeFields(), VhdlDocGen::writeFormatString(), writeGraphInfo(), ClassDefImpl::writeIncludeFilesForSlice(), MemberDefImpl::writeMemberDocSimple(), HtmlDocVisitor::writeMscFile(), HtmlDocVisitor::writePlantUMLFile(), PlantumlManager::writePlantUMLSource(), VhdlDocGen::writeRecordUnit(), VhdlDocGen::writeSource(), DefinitionImpl::writeSourceDef(), ConfigInt::writeTemplate(), ConfigBool::writeTemplate(), ConfigList::writeTemplate(), ConfigEnum::writeTemplate(), ConfigString::writeTemplate(), and DotNode::writeUrl().
left() [2/2]
QCString QCString::left (size_t len) const [inline]
Definition at line 212 of file qcstring.h.
    {
      return m_rep.empty() ? QCString() : QCString(m_rep.substr(0,len));
    }
References len, m_rep, and QCString().
length() [1/2]
uint QCString::length () const [inline]
Returns the length of the string, not counting the 0-terminator. Equivalent to size().
Definition at line 147 of file qcstring.h.
{ return static_cast<uint>(m_rep.size()); }
References m_rep.
Referenced by DefinitionImpl::_docsAlreadyAdded(), DefinitionImpl::_setBriefDescription(), MemberDefImpl::_writeReimplements(), abbreviate(), addEnumValuesToEnums(), addIncludeFile(), DocSets::addIndexItem(), addMacroDefinition(), addMemberToGroups(), addModule(), addRelatedPage(), addTemplateNames(), FlowChart::alignFuncProc(), alignText(), FilterLength::apply(), buildFileName(), buildGroupListFiltered(), Config::checkAndCorrect(), DocParser::checkArgumentName(), checkExtension(), VHDLOutlineParser::checkInlineCode(), checkList(), DocParser::checkUnOrMultipleDocumentedParams(), computeCommonDirPrefix(), computeVerifiedDotPath(), configStringRecode(), contains(), TranslatorPersian::convertDigitsToFarsi(), DotFilePatcher::convertMapFile(), convertNameToFile(), countAliasArguments(), createOutputDirectory(), createTagLessInstance(), DocParser::defaultHandleTitleAndSize(), FilterListSort::determineSortKey(), DirDefImpl::DirDefImpl(), MemberDefImpl::displayDefinition(), DocAnchor::DocAnchor(), DocEmoji::DocEmoji(), DocInternalRef::DocInternalRef(), DocLink::DocLink(), elemIsVisible(), encodeDirName(), LayoutParser::endElement(), escapeAliases(), escapeId(), expandAliasRec(), expandExpression(), DocInclude::extension(), externalRef(), DefinitionImpl::externalReference(), extractAliasArgs(), extractBind(), extractBlock(), extractCanonicalType(), extractClassNameFromType(), extractFromParens(), extractLanguageSpecificTitle(), extractNamespaceName(), filterMemberDocumentation(), find(), DocParser::findAndCopyImage(), findClassRelation(), findDirDocumentation(), DocParser::findDocsForMemberOrCompound(), Markdown::findEmphasisChar(), findEndOfCommand(), Markdown::findEndOfLine(), findEnumDocumentation(), findEnums(), findFileDef(), findMember(), findRev(), findScopeFromQualifiedName(), findUsingDeclImports(), findUsingDirectives(), format_warn(), VhdlDocGen::formatString(), generateClassOrGlobalLink(), generateFunctionLink(), generateMemberLink(), CitationManager::generatePage(), PlantumlManager::generatePlantUMLOutput(), TemplateContextImpl::get(), getCanonicalTemplateSpec(), MemberDefImpl::getClassDefOfAnonymousType(), getCurrentChar(), getDefsOld(), getExtension(), getFileFilter(), getMemberFromSymbol(), getNextChar(), getNextId(), getParserForFile(), ParserManager::getParsers(), SymbolResolver::Private::getResolvedSymbolRec(), SymbolResolver::Private::getResolvedTypeRec(), getScopeDefs(), handle_warn_as_error(), DocParser::handleLinkedWord(), DocPara::handleStartCode(), DocParser::handleStyleArgument(), handleToc(), insertTemplateSpecifierInScope(), Portable::isAbsolutePath(), Markdown::isAtxHeader(), isConstraintFile(), DocFormula::isInline(), DocImage::isSVG(), leftScopeMatch(), linkToText(), matchArgument2(), matchExcludedSymbols(), DirDefImpl::matchPath(), mergeArguments(), ClassDefImpl::mergeMembers(), mergeScopes(), ArgumentContext::Private::namePart(), DefinitionImpl::navigationPathAsString(), SymbolResolver::Private::newResolveTypedef(), VHDLOutlineParser::oneLineComment(), LatexDocVisitor::operator()(), PerlModDocVisitor::operator()(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), RTFDocVisitor::operator()(), DocInclude::parse(), FileCodeParser::parseCode(), parseCommentAsText(), parseFile(), parseFuncDecl(), VhdlDocGen::parseFuncProto(), MarkdownOutlineParser::parseInput(), parseMain(), Htags::path2URL(), DotGraph::prepareDotFile(), Markdown::processBlocks(), DocParser::processCopyDoc(), Markdown::processLink(), Markdown::processQuotations(), Markdown::processSpecialCommand(), DocTokenizer::pushBackHtmlTag(), readAliases(), readCodeFragment(), readIncludeFile(), readTagFile(), Portable::recodeUtf8StringToW(), recognizeFixedForm(), TemplateNodeCreate::render(), replaceAliasArguments(), replaceAliases(), replaceFunctionMacro(), replaceNamespaceAliases(), replaceVariables(), resolveRef(), resolveSymlink(), resolveTypeDef(), resolveUserReferences(), rightScopeMatch(), rtfFormatBmkStr(), DotFilePatcher::run(), runPlantumlContent(), searchInputFiles(), searchTemplateSpecs(), MemberDefImpl::setAnchor(), MemberDefImpl::setInitializer(), showFileDefMatches(), simplifyTypeForTable(), simplifyWhiteSpace(), skipToEndMarker(), split(), sprintf(), LatexDocVisitor::startDiaFile(), LatexDocVisitor::startDotFile(), ManGenerator::startDoxyAnchor(), LatexDocVisitor::startMscFile(), startsWithKeyword(), stripExtensionGeneral(), stripFromPath(), stripIrrelevantString(), stripKnownExtensions(), stripPrefix(), stripScope(), stripTemplateSpecifiersFromScope(), subrHandleCommentBlock(), substEnvVarsInStrList(), NavPathElemContext::Private::text(), toLong(), toUInt64(), toULong(), transcodeCharacterStringToUTF8(), trimBaseClassScope(), TranslatorJapanese::trWriteList(), unputChar(), DocTokenizer::unputString(), validatingParseDoc(), MemberDefImpl::writeDeclaration(), FileDefImpl::writeDetailedDescription(), RTFDocVisitor::writeDiaFile(), LatexDocVisitor::writeDiaFile(), HtmlDocVisitor::writeDiaFile(), MemberDefImpl::writeDocumentation(), RTFDocVisitor::writeDotFile(), HtmlDocVisitor::writeDotFile(), HtmlGenerator::writeExternalSearchPage(), ClassDefImpl::writeIncludeFilesForSlice(), RTFDocVisitor::writeMscFile(), LatexDocVisitor::writeMscFile(), HtmlDocVisitor::writeMscFile(), RTFDocVisitor::writePlantUMLFile(), LatexDocVisitor::writePlantUMLFile(), HtmlDocVisitor::writePlantUMLFile(), PlantumlManager::writePlantUMLSource(), FlowChart::writeShape(), writeSingleFileIndex(), DefinitionImpl::writeSourceDef(), ConfigInt::writeTemplate(), ConfigBool::writeTemplate(), ConfigList::writeTemplate(), ConfigEnum::writeTemplate(), ConfigString::writeTemplate(), writeUCFLink(), DotNode::writeUrl(), writeWord(), and HtmlEntityMapper::writeXMLSchema().
length() [2/2]
uint QCString::length () const [inline]
Returns the length of the string, not counting the 0-terminator. Equivalent to size().
Definition at line 147 of file qcstring.h.
{ return static_cast<uint>(m_rep.size()); }
References m_rep.
lower() [1/2]
QCString QCString::lower () const [inline]
Definition at line 232 of file qcstring.h.
    {
      return QCString(convertUTF8ToLower(m_rep));
    }
References convertUTF8ToLower(), m_rep, and QCString().
Referenced by DocSets::addIndexItem(), VHDLOutlineParser::addLibUseClause(), addLocalVar(), addSubprogram(), SearchIndex::addWordRec(), adjustConfiguration(), DocHtmlCell::alignment(), FilterLower::apply(), Config::checkAndCorrect(), DocParser::checkArgumentName(), DocParser::checkUnOrMultipleDocumentedParams(), codifyMapLines(), vhdl::parser::VhdlParser::component_instantiation_statement(), convertStringToBool(), ConfigEnum::convertStrToVal(), VhdlDocGen::correctMemberProperties(), DocStyleChange::DocStyleChange(), elemIsVisible(), endScope(), extractClassNameFromType(), findArgument(), findFileDef(), VhdlDocGen::findKeyWord(), VhdlDocGen::findMember(), genericPatternMatch(), getFilteredImageAttributes(), getFilterFromList(), getFortranDefs(), getLanguageFromCodeLang(), getLanguageFromFileName(), ParserManager::getParsers(), DocPara::handleCommand(), handleFileInfo(), handleHtmlTag(), DocParser::handleImage(), handleImage(), DocParser::handleStyleLeave(), handleToc(), PageDefImpl::hasTitle(), MemberDefImpl::IMPL::init(), FortranOutlineParser::needsPreprocessing(), COutlineParser::needsPreprocessing(), SymbolModifiers::operator|=(), Markdown::processHtmlTagWrite(), Markdown::processLink(), subrHandleCommentBlock(), subrHandleCommentBlockResult(), substituteHtmlKeywords(), updateLanguageMapping(), Config::updateObsolete(), DocHtmlCell::valignment(), VhdlConfNode::VhdlConfNode(), and ClassDefImpl::writeTemplateSpec().
lower() [2/2]
QCString QCString::lower () const [inline]
Definition at line 232 of file qcstring.h.
    {
      return QCString(convertUTF8ToLower(m_rep));
    }
References convertUTF8ToLower(), m_rep, and QCString().
mid() [1/2]
QCString QCString::mid (size_t index, size_t len = static_cast<size_t>(-1)) const [inline]
Definition at line 224 of file qcstring.h.
    {
      size_t slen = m_rep.size();
      if (len==static_cast<uint>(-1)) len = slen-index;
      return m_rep.empty() || index>slen || len==0 ? QCString() :
             QCString(m_rep.substr(index,len));
    }
References len, m_rep, and QCString().
Referenced by MemberDefImpl::_writeCategoryRelation(), abbreviate(), addClassToContext(), addIncludeFile(), addMacroDefinition(), addMemberFunction(), addToMap(), addVariableToClass(), addVariableToFile(), adjustConfiguration(), FilterStripPath::apply(), argListToString(), VHDLOutlineParser::checkInlineCode(), convertFileId2Var(), FilterListSort::determineSortKey(), DirDefImpl::DirDefImpl(), MemberDefImpl::displayDefinition(), elemIsVisible(), escapeAliases(), ExistsOnPath(), expandExpression(), extractAliasArgs(), extractBind(), extractBlock(), extractCanonicalType(), extractClassNameFromType(), extractLanguageSpecificTitle(), Markdown::extractPageTitle(), extractPartAfterNewLine(), fillColorStyleMap(), VhdlDocGen::findAllArchitectures(), findClassRelation(), findGlobalMember(), findPackageScopeFromPath(), findScopeFromQualifiedName(), SymbolResolver::Private::followPath(), generateClassOrGlobalLink(), generateFunctionLink(), CitationManager::generatePage(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), TemplateContextImpl::get(), getDefsOld(), getExtension(), getFileFilter(), getFileNameExtension(), getFilteredImageAttributes(), getLanguageFromCodeLang(), DocPara::handleCommand(), handleHtmlTag(), DocParser::handleImage(), handleImage(), DocParser::handleParameterType(), if(), CitationManager::insertCrossReferencesForBibFile(), DocImage::isSVG(), Htags::loadFilemap(), NamespaceDefImpl::localName(), makeFileName(), matchExcludedSymbols(), ArgumentContext::Private::namePart(), SymbolResolver::Private::newResolveTypedef(), LatexDocVisitor::operator()(), HtmlDocVisitor::operator()(), DocbookDocVisitor::operator()(), DocIncOperator::parse(), DocPara::parse(), DocParamList::parse(), TemplateParser::parse(), FileCodeParser::parseCode(), VhdlDocGen::parseFuncProto(), Htags::path2URL(), Markdown::process(), Markdown::processLink(), readIncludeFile(), replaceAliasArguments(), replaceRef(), replaceVariables(), resolveRef(), resolveSymlink(), resolveTypeDef(), DotFilePatcher::run(), saveObjCContext(), TemplateContextImpl::setEscapeIntf(), split(), splitKnRArg(), stripPath(), stripTemplateSpecifiersFromScope(), stripTrailingReturn(), substEnvVarsInStrList(), substituteTemplateArgumentsInString(), substituteTemplatesInString(), TemplateNodeIndexEntry::TemplateNodeIndexEntry(), TemplateNodeWith::TemplateNodeWith(), TranslatorBrazilian::trDayOfWeek(), TranslatorCatalan::trDayOfWeek(), TranslatorCzech::trDayOfWeek(), TranslatorDanish::trDayOfWeek(), TranslatorEsperanto::trDayOfWeek(), TranslatorSpanish::trDayOfWeek(), TranslatorFinnish::trDayOfWeek(), TranslatorFrench::trDayOfWeek(), TranslatorHungarian::trDayOfWeek(), TranslatorItalian::trDayOfWeek(), TranslatorLithuanian::trDayOfWeek(), TranslatorLatvian::trDayOfWeek(), TranslatorDutch::trDayOfWeek(), TranslatorNorwegian::trDayOfWeek(), TranslatorPolish::trDayOfWeek(), TranslatorPortuguese::trDayOfWeek(), TranslatorRomanian::trDayOfWeek(), TranslatorSlovene::trDayOfWeek(), TranslatorSlovak::trDayOfWeek(), TranslatorSerbian::trDayOfWeek(), TranslatorSwedish::trDayOfWeek(), TranslatorAfrikaans::trDayOfWeek(), TranslatorBrazilian::trMonth(), TranslatorCatalan::trMonth(), TranslatorCzech::trMonth(), TranslatorDanish::trMonth(), TranslatorEsperanto::trMonth(), TranslatorSpanish::trMonth(), TranslatorFinnish::trMonth(), TranslatorFrench::trMonth(), TranslatorHungarian::trMonth(), TranslatorItalian::trMonth(), TranslatorLithuanian::trMonth(), TranslatorLatvian::trMonth(), TranslatorDutch::trMonth(), TranslatorNorwegian::trMonth(), TranslatorPolish::trMonth(), TranslatorPortuguese::trMonth(), TranslatorRomanian::trMonth(), TranslatorSlovene::trMonth(), TranslatorSlovak::trMonth(), TranslatorSerbian::trMonth(), TranslatorSwedish::trMonth(), TranslatorAfrikaans::trMonth(), DotAttributes::updateValue(), LayoutNavEntry::url(), writeDefArgumentList(), MemberDefImpl::writeDocumentation(), writeExceptionList(), writeExceptionListImpl(), Markdown::writeFencedCodeBlock(), writeGraphInfo(), Markdown::writeMarkdownImage(), MemberDefImpl::writeMemberDocSimple(), DefinitionImpl::writeSourceDef(), DotNode::writeUrl(), and HtmlEntityMapper::writeXMLSchema().
mid() [2/2]
QCString QCString::mid (size_t index, size_t len = static_cast<size_t>(-1)) const [inline]
Definition at line 224 of file qcstring.h.
    {
      size_t slen = m_rep.size();
      if (len==static_cast<uint>(-1)) len = slen-index;
      return m_rep.empty() || index>slen || len==0 ? QCString() :
             QCString(m_rep.substr(index,len));
    }
References len, m_rep, and QCString().
operator+=() [1/8]
QCString & QCString::operator+= (char c) [inline]
Appends character c to this string and returns a reference to the result.
Definition at line 507 of file qcstring.h.
    {
      m_rep+=c;
      return *this;
    }
References c, and m_rep.
operator+=() [2/8]
QCString & QCString::operator+= (char c) [inline]
Appends character c to this string and returns a reference to the result.
Definition at line 507 of file qcstring.h.
    {
      m_rep+=c;
      return *this;
    }
References c, and m_rep.
operator+=() [3/8]
QCString & QCString::operator+= (const char * s) [inline]
Appends string str to this string and returns a reference to the result.
Definition at line 498 of file qcstring.h.
    {
      if (s) m_rep+=s;
      return *this;
    }
References m_rep, and s.
operator+=() [4/8]
QCString & QCString::operator+= (const char * s) [inline]
Appends string str to this string and returns a reference to the result.
Definition at line 498 of file qcstring.h.
    {
      if (s) m_rep+=s;
      return *this;
    }
References m_rep, and s.
operator+=() [5/8]
QCString & QCString::operator+= (const QCString & s) [inline]
Definition at line 485 of file qcstring.h.
    {
      m_rep+=s.str();
      return *this;
    }
References m_rep, and s.
Referenced by append().
operator+=() [6/8]
QCString & QCString::operator+= (const QCString & s) [inline]
Definition at line 485 of file qcstring.h.
    {
      m_rep+=s.str();
      return *this;
    }
References m_rep, and s.
operator+=() [7/8]
QCString & QCString::operator+= (const std::string & s) [inline]
Definition at line 491 of file qcstring.h.
    {
      m_rep+=s;
      return *this;
    }
References m_rep, and s.
operator+=() [8/8]
QCString & QCString::operator+= (const std::string & s) [inline]
Definition at line 491 of file qcstring.h.
    {
      m_rep+=s;
      return *this;
    }
References m_rep, and s.
operator=() [1/8]
QCString & QCString::operator= (const char * str) [inline]
replaces the contents by that of C string str.
Definition at line 136 of file qcstring.h.
{ m_rep = str?str:""; return *this; }
References m_rep, and str().
operator=() [2/8]
QCString & QCString::operator= (const char * str) [inline]
replaces the contents by that of C string str.
Definition at line 136 of file qcstring.h.
{ m_rep = str?str:""; return *this; }
References m_rep, and str().
operator=() [3/8]
QCString & QCString::operator= (const QCString & s) [default]
operator=() [4/8]
QCString & QCString::operator= (const QCString & s) [default]
operator=() [5/8]
QCString & QCString::operator= (const std::string & s) [inline]
Definition at line 138 of file qcstring.h.
{ m_rep = s; return *this; }
References m_rep, and s.
operator=() [6/8]
QCString & QCString::operator= (const std::string & s) [inline]
Definition at line 138 of file qcstring.h.
{ m_rep = s; return *this; }
References m_rep, and s.
operator=() [7/8]
QCString & QCString::operator= (QCString && s) [default]
operator=() [8/8]
QCString & QCString::operator= (QCString && s) [default]
operator[]() [1/4]
char & QCString::operator[] (int i) [inline]
Indexing operator. Equivalent to at().
Definition at line 526 of file qcstring.h.
    {
      return m_rep[i];
    }
References m_rep.
operator[]() [2/4]
char & QCString::operator[] (int i) [inline]
Indexing operator. Equivalent to at().
Definition at line 526 of file qcstring.h.
    {
      return m_rep[i];
    }
References m_rep.
operator[]() [3/4]
const char & QCString::operator[] (int i) const [inline]
Definition at line 531 of file qcstring.h.
    {
      return m_rep[i];
    }
References m_rep.
operator[]() [4/4]
const char & QCString::operator[] (int i) const [inline]
Definition at line 531 of file qcstring.h.
    {
      return m_rep[i];
    }
References m_rep.
prepend() [1/6]
QCString & QCString::prepend (const char * s) [inline]
Definition at line 365 of file qcstring.h.
    {
      return insert(0,s);
    }
References insert(), and s.
Referenced by DefinitionImpl::_writeSourceRefList(), addClassToContext(), addConceptToContext(), MemberDefImpl::addListReference(), addMemberFunction(), addModule(), DefinitionImpl::addSourceReferencedBy(), DefinitionImpl::addSourceReferences(), addSTLClass(), ClassDefImpl::addUsedByClass(), ClassDefImpl::addUsedClass(), FlowChart::alignFuncProc(), MemberDefImpl::anchor(), vhdl::parser::VhdlParser::assertion(), vhdl::parser::VhdlParser::constant_declaration(), convertNameToFile(), correctURL(), VHDLOutlineParser::createFlow(), createOutputDirectory(), MemberDefImpl::displayDefinition(), DocEmoji::DocEmoji(), vhdl::parser::VhdlParser::exit_statement(), externalRef(), DefinitionImpl::externalReference(), MemberDefImpl::fieldType(), FileDefImpl::FileDefImpl(), filterMemberDocumentation(), findClassRelation(), DocParser::findDocsForMemberOrCompound(), findEnumDocumentation(), findEnums(), findMember(), generateOutput(), MemberDefImpl::getDeclType(), getExtension(), getLanguageFromFileName(), FlowChart::getNodeName(), getScopeDefs(), vhdl::parser::VhdlParser::if_statement(), vhdl::parser::VhdlParser::ifunc(), SymbolResolver::Private::newResolveTypedef(), vhdl::parser::VhdlParser::next_statement(), HtmlDocVisitor::operator()(), parseInput(), MarkdownOutlineParser::parseInput(), vhdl::parser::VhdlParser::procedure_call(), quoted(), TemplateNodeCreate::render(), replaceRef(), vhdl::parser::VhdlParser::report_statement(), MemberDefImpl::setAnchor(), setDotFontPath(), vhdl::parser::VhdlParser::signal_declaration(), DocbookDocVisitor::startDiaFile(), LatexDocVisitor::startDiaFile(), DocbookDocVisitor::startDotFile(), LatexDocVisitor::startDotFile(), DocbookDocVisitor::startMscFile(), LatexDocVisitor::startMscFile(), substituteHtmlKeywords(), unputChar(), updateLanguageMapping(), vhdl::parser::VhdlParser::variable_declaration(), vhdl::parser::VhdlParser::waveform_element(), MemberDefImpl::writeDeclaration(), HtmlDocVisitor::writeDiaFile(), MemberDefImpl::writeDocumentation(), HtmlDocVisitor::writeDotFile(), VhdlDocGen::writeInlineClassLink(), RTFGenerator::writeLineNumber(), LatexCodeGenerator::writeLineNumber(), HtmlDocVisitor::writeMscFile(), PlantumlManager::writePlantUMLSource(), writeSingleFileIndex(), VhdlDocGen::writeSource(), VhdlDocGen::writeVHDLDeclaration(), and VhdlDocGen::writeVhdlLink().
prepend() [2/6]
QCString & QCString::prepend (const char * s) [inline]
Definition at line 365 of file qcstring.h.
    {
      return insert(0,s);
    }
References insert(), and s.
prepend() [3/6]
QCString & QCString::prepend (const QCString & s) [inline]
Definition at line 370 of file qcstring.h.
    {
      return insert(0,s.data());
    }
References gdFont::data, insert(), and s.
prepend() [4/6]
QCString & QCString::prepend (const QCString & s) [inline]
Definition at line 370 of file qcstring.h.
    {
      return insert(0,s.data());
    }
References gdFont::data, insert(), and s.
prepend() [5/6]
QCString & QCString::prepend (const std::string & s) [inline]
Definition at line 375 of file qcstring.h.
    {
      return insert(0,s.c_str());
    }
References insert(), and s.
prepend() [6/6]
QCString & QCString::prepend (const std::string & s) [inline]
Definition at line 375 of file qcstring.h.
    {
      return insert(0,s.c_str());
    }
References insert(), and s.
quoted() [1/2]
QCString QCString::quoted () const [inline]
Definition at line 256 of file qcstring.h.
    {
      size_t start=0, sl=m_rep.size(), end=sl-1;
      while (start<sl && qisspace(m_rep[start])) start++; // skip over leading whitespace
      if (start==sl) return QCString(); // only whitespace
      while (end>start && qisspace(m_rep[end])) end--; // skip over trailing whitespace
      bool needsQuotes=false;
      size_t i=start;
      if (i<end && m_rep[i]!='"') // stripped string has at least non-whitespace unquoted character
      {
        while (i<end && !needsQuotes) // check if the to be quoted part has at least one whitespace character
        {
          needsQuotes = qisspace(m_rep[i++]);
        }
      }
      QCString result(m_rep.substr(start,1+end-start));
      if (needsQuotes)
      {
        result.prepend("\"");
        result.append("\"");
      }
      return result;
    }
References append(), ghc::filesystem::end(), m_rep, prepend(), QCString(), qisspace(), and caseconvert::sl.
Referenced by DotAttributes::updateValue(), writeLatexMakefile(), and writeMakeBat().
quoted() [2/2]
QCString QCString::quoted () const [inline]
Definition at line 256 of file qcstring.h.
    {
      size_t start=0, sl=m_rep.size(), end=sl-1;
      while (start<sl && qisspace(m_rep[start])) start++; // skip over leading whitespace
      if (start==sl) return QCString(); // only whitespace
      while (end>start && qisspace(m_rep[end])) end--; // skip over trailing whitespace
      bool needsQuotes=false;
      size_t i=start;
      if (i<end && m_rep[i]!='"') // stripped string has at least non-whitespace unquoted character
      {
        while (i<end && !needsQuotes) // check if the to be quoted part has at least one whitespace character
        {
          needsQuotes = qisspace(m_rep[i++]);
        }
      }
      QCString result(m_rep.substr(start,1+end-start));
      if (needsQuotes)
      {
        result.prepend("\"");
        result.append("\"");
      }
      return result;
    }
References append(), ghc::filesystem::end(), m_rep, prepend(), QCString(), qisspace(), and caseconvert::sl.
rawData() [1/2]
char * QCString::rawData () [inline]
Returns a writable pointer to the data.
Definition at line 157 of file qcstring.h.
{ return &m_rep[0]; }
References m_rep.
Referenced by clearBlock(), configStringRecode(), ResourceMgr::copyResourceAs(), do_warn(), ResourceMgr::getAsString(), SymbolResolver::Private::getResolvedSymbolRec(), SymbolResolver::Private::getResolvedTypeRec(), markdownFileNameToId(), HtmlHelpRecoder::recode(), TemplateContextImpl::recode(), rtfFormatBmkStr(), simplifyWhiteSpace(), sprintf(), stripIndentation(), substitute(), and transcodeCharacterStringToUTF8().
rawData() [2/2]
char * QCString::rawData () [inline]
Returns a writable pointer to the data.
Definition at line 157 of file qcstring.h.
{ return &m_rep[0]; }
References m_rep.
remove() [1/2]
QCString & QCString::remove (size_t index, size_t len) [inline]
Definition at line 380 of file qcstring.h.
    {
      size_t ol = m_rep.size();
      if (index<ol && len>0) m_rep.erase(index,index+len>=ol ? std::string::npos : len);
      return *this;
    }
References len, and m_rep.
Referenced by doxmlparser.compound.memberdefType::__init__(), alignText(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), extractFromParens(), doxmlparser.compound.memberdefType::get_remove(), initUCF(), VhdlDocGen::parseForBinding(), VhdlDocGen::parseForConfig(), VhdlDocGen::parseUCF(), VhdlDocGen::prepareComment(), replace(), doxmlparser.compound.memberdefType::set_remove(), splitString(), MemberDefImpl::writeDocumentation(), VhdlDocGen::writeFormatString(), and FlowChart::writeShape().
remove() [2/2]
QCString & QCString::remove (size_t index, size_t len) [inline]
Definition at line 380 of file qcstring.h.
    {
      size_t ol = m_rep.size();
      if (index<ol && len>0) m_rep.erase(index,index+len>=ol ? std::string::npos : len);
      return *this;
    }
References len, and m_rep.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_remove(), and doxmlparser.compound.memberdefType::set_remove().
removeWhiteSpace() [1/2]
QCString QCString::removeWhiteSpace () const [inline]
returns a copy of this string with all whitespace removed
Definition at line 281 of file qcstring.h.
    {
      size_t sl = m_rep.size();
      if (sl==0) return *this;
      std::string result = m_rep;
      size_t src=0,dst=0;
      while (src<sl)
      {
        if (!qisspace(m_rep[src])) result[dst++]=m_rep[src];
        src++;
      }
      if (dst<m_rep.size()) result.resize(dst);
      return QCString(result);
    }
References dst, m_rep, QCString(), qisspace(), caseconvert::sl, src, and string.
removeWhiteSpace() [2/2]
QCString QCString::removeWhiteSpace () const [inline]
returns a copy of this string with all whitespace removed
Definition at line 281 of file qcstring.h.
    {
      size_t sl = m_rep.size();
      if (sl==0) return *this;
      std::string result = m_rep;
      size_t src=0,dst=0;
      while (src<sl)
      {
        if (!qisspace(m_rep[src])) result[dst++]=m_rep[src];
        src++;
      }
      if (dst<m_rep.size()) result.resize(dst);
      return QCString(result);
    }
References dst, m_rep, QCString(), qisspace(), caseconvert::sl, src, and string.
replace() [1/2]
QCString & QCString::replace (size_t index, size_t len, const char * s)
Definition at line 212 of file qcstring.cpp.
{
  remove(index, len);
  insert(index, s);
  return *this;
}
References insert(), len, remove(), and s.
Referenced by VhdlDocGen::formatString(), version(), and writeNamespaceIndex().
replace() [2/2]
QCString & QCString::replace (size_t index, size_t len, const char * s)
resize() [1/2]
bool QCString::resize (size_t newlen) [inline]
Resizes the string to hold newlen characters (this value should also count the 0-terminator). If the string is enlarged the contents will be left unmodified.
Definition at line 164 of file qcstring.h.
{ m_rep.resize(newlen>0 ? newlen-1 : 0); return TRUE; }
References m_rep, and TRUE.
Referenced by adjustConfiguration(), alignText(), appStringLower(), vhdl::parser::VhdlParser::architecture_body(), DocGroup::clearHeader(), DocGroup::close(), codifyMapLines(), configStringRecode(), vhdl::parser::VhdlParser::configuration_declaration(), DocbookCodeGenerator::endCodeLine(), XMLCodeGenerator::endCodeLine(), OutputGenerator::endPlainFile(), DocGroup::enterCompound(), DocGroup::enterFile(), vhdl::parser::VhdlParser::entity_declaration(), vhdl::parser::VhdlParser::exit_statement(), extractClassNameFromType(), extractNamespaceName(), findClassRelation(), findMember(), TemplateContextImpl::get(), getDefsOld(), ExpressionParser::getNextToken(), SymbolResolver::Private::getResolvedSymbol(), SymbolResolver::Private::getResolvedType(), CondParser::getToken(), handleParametersCommentBlocks(), initUCF(), isLinkRef(), DocGroup::leaveCompound(), DocGroup::leaveFile(), mergeArguments(), vhdl::parser::VhdlParser::next_statement(), vhdl::parser::VhdlParser::package_body(), vhdl::parser::VhdlParser::package_declaration(), HtmlHelpRecoder::recode(), TemplateContextImpl::recode(), replaceFunctionMacro(), ArgumentList::reset(), Entry::reset(), SymbolResolver::Private::reset(), DefinitionImpl::setOuterScope(), simplifyWhiteSpace(), sprintf(), startCodeLine(), stripIndentation(), stripIrrelevantString(), substitute(), ConfigImpl::takeStartComment(), ConfigImpl::takeStoreRepl(), ConfigImpl::takeUserComment(), transcodeCharacterStringToUTF8(), truncate(), writeDefArgumentList(), writeFuncProto(), VhdlDocGen::writeInlineClassLink(), ClassDefImpl::writeMemberDeclarations(), and writeWord().
resize() [2/2]
bool QCString::resize (size_t newlen) [inline]
Resizes the string to hold newlen characters (this value should also count the 0-terminator). If the string is enlarged the contents will be left unmodified.
Definition at line 164 of file qcstring.h.
{ m_rep.resize(newlen>0 ? newlen-1 : 0); return TRUE; }
References m_rep, and TRUE.
right() [1/2]
QCString QCString::right (size_t len) const [inline]
Definition at line 217 of file qcstring.h.
    {
      return m_rep.empty() ? QCString() :
             len<m_rep.size() ? QCString(m_rep.substr(m_rep.size()-len,len)) :
             *this;
    }
References len, m_rep, and QCString().
Referenced by MemberDefImpl::_writeReimplements(), addEnumValuesToEnums(), addMacroDefinition(), addModule(), addRelatedPage(), addTemplateNames(), buildFileName(), checkExtension(), checkList(), computeCommonDirPrefix(), DotFilePatcher::convertMapFile(), FilterListSort::determineSortKey(), DocInternalRef::DocInternalRef(), DocLink::DocLink(), LayoutParser::endElement(), expandExpression(), DocInclude::extension(), extractCanonicalType(), extractNamespaceName(), filterMemberDocumentation(), DocParser::findAndCopyImage(), findClassRelation(), DocParser::findDocsForMemberOrCompound(), findEnumDocumentation(), findEnums(), findFileDef(), findMember(), findScopeFromQualifiedName(), findUsingDeclImports(), generateClassOrGlobalLink(), generateDiskNames(), generateFunctionLink(), generateMemberLink(), CitationManager::generatePage(), PlantumlManager::generatePlantUMLOutput(), getCanonicalTemplateSpec(), getDefsOld(), getNextChar(), getParserForFile(), getScopeDefs(), handleToc(), insertTemplateSpecifierInScope(), isConstraintFile(), linkToText(), matchArgument2(), mergeArguments(), mergeScopes(), SymbolResolver::Private::newResolveTypedef(), VHDLOutlineParser::oneLineComment(), RTFDocVisitor::operator()(), HtmlDocVisitor::operator()(), PerlModDocVisitor::operator()(), DocbookDocVisitor::operator()(), parseFile(), MarkdownOutlineParser::parseInput(), readAliases(), readTagFile(), TemplateNodeCreate::render(), replaceAliasArguments(), replaceNamespaceAliases(), resolveRef(), resolveTypeDef(), rightScopeMatch(), DocbookDocVisitor::startDiaFile(), LatexDocVisitor::startDiaFile(), DocbookDocVisitor::startDotFile(), LatexDocVisitor::startDotFile(), ManGenerator::startDoxyAnchor(), DocbookDocVisitor::startMscFile(), LatexDocVisitor::startMscFile(), stripExtensionGeneral(), stripFromPath(), stripIrrelevantString(), stripKnownExtensions(), stripScope(), stripTemplateSpecifiersFromScope(), subrHandleCommentBlock(), substEnvVarsInStrList(), MemberDefImpl::writeDeclaration(), FileDefImpl::writeDetailedDescription(), RTFDocVisitor::writeDiaFile(), DocbookDocVisitor::writeDiaFile(), LatexDocVisitor::writeDiaFile(), HtmlDocVisitor::writeDiaFile(), RTFDocVisitor::writeDotFile(), DocbookDocVisitor::writeDotFile(), HtmlDocVisitor::writeDotFile(), HtmlGenerator::writeExternalSearchPage(), ClassDefImpl::writeIncludeFilesForSlice(), RTFDocVisitor::writeMscFile(), DocbookDocVisitor::writeMscFile(), LatexDocVisitor::writeMscFile(), HtmlDocVisitor::writeMscFile(), RTFDocVisitor::writePlantUMLFile(), DocbookDocVisitor::writePlantUMLFile(), LatexDocVisitor::writePlantUMLFile(), HtmlDocVisitor::writePlantUMLFile(), PlantumlManager::writePlantUMLSource(), DefinitionImpl::writeSourceDef(), and DotNode::writeUrl().
right() [2/2]
QCString QCString::right (size_t len) const [inline]
Definition at line 217 of file qcstring.h.
    {
      return m_rep.empty() ? QCString() :
             len<m_rep.size() ? QCString(m_rep.substr(m_rep.size()-len,len)) :
             *this;
    }
References len, m_rep, and QCString().
setNum() [1/16]
QCString & QCString::setNum (int n) [inline]
Definition at line 410 of file qcstring.h.
    {
      m_rep = std::to_string(n);
      return *this;
    }
References m_rep, and n.
setNum() [2/16]
QCString & QCString::setNum (int n) [inline]
Definition at line 410 of file qcstring.h.
    {
      m_rep = std::to_string(n);
      return *this;
    }
References m_rep, and n.
setNum() [3/16]
QCString & QCString::setNum (long long n) [inline]
Definition at line 428 of file qcstring.h.
    {
      m_rep = std::to_string(n);
      return *this;
    }
References m_rep, and n.
setNum() [4/16]
QCString & QCString::setNum (long long n) [inline]
Definition at line 428 of file qcstring.h.
    {
      m_rep = std::to_string(n);
      return *this;
    }
References m_rep, and n.
setNum() [5/16]
QCString & QCString::setNum (long n) [inline]
Definition at line 422 of file qcstring.h.
    {
      m_rep = std::to_string(n);
      return *this;
    }
References m_rep, and n.
setNum() [6/16]
QCString & QCString::setNum (long n) [inline]
Definition at line 422 of file qcstring.h.
    {
      m_rep = std::to_string(n);
      return *this;
    }
References m_rep, and n.
setNum() [7/16]
QCString & QCString::setNum (short n) [inline]
Definition at line 398 of file qcstring.h.
    {
      m_rep = std::to_string(n);
      return *this;
    }
References m_rep, and n.
Referenced by addModule(), compileOptions(), convertCppComments(), convertIndexWordToAnchor(), CondParser::evalOperator(), format_warn(), generateIndentLabel(), generateJSNavTree(), CitationManager::generatePage(), VHDLOutlineParser::getNameID(), FlowChart::getNodeName(), RTFDocVisitor::getStyle(), NestingNodeContext::Private::id(), CitationManager::latexBibFiles(), PerlModDocVisitor::operator()(), pathToNode(), DocParser::processCopyDoc(), removeIdsAndMarkers(), Trace::setResult(), TemplateVariant::toString(), warn_line(), PlantumlManager::writePlantUMLSource(), Markdown::writeTableBlock(), and yearToString().
setNum() [8/16]
QCString & QCString::setNum (short n) [inline]
Definition at line 398 of file qcstring.h.
    {
      m_rep = std::to_string(n);
      return *this;
    }
References m_rep, and n.
setNum() [9/16]
QCString & QCString::setNum (uint n) [inline]
Definition at line 416 of file qcstring.h.
    {
      m_rep = std::to_string(n);
      return *this;
    }
References m_rep, and n.
setNum() [10/16]
QCString & QCString::setNum (uint n) [inline]
Definition at line 416 of file qcstring.h.
    {
      m_rep = std::to_string(n);
      return *this;
    }
References m_rep, and n.
setNum() [11/16]
QCString & QCString::setNum (ulong n) [inline]
Definition at line 440 of file qcstring.h.
    {
      m_rep = std::to_string(n);
      return *this;
    }
References m_rep, and n.
setNum() [12/16]
QCString & QCString::setNum (ulong n) [inline]
Definition at line 440 of file qcstring.h.
    {
      m_rep = std::to_string(n);
      return *this;
    }
References m_rep, and n.
setNum() [13/16]
QCString & QCString::setNum (unsigned long long n) [inline]
Definition at line 434 of file qcstring.h.
    {
      m_rep = std::to_string(n);
      return *this;
    }
References m_rep, and n.
setNum() [14/16]
QCString & QCString::setNum (unsigned long long n) [inline]
Definition at line 434 of file qcstring.h.
    {
      m_rep = std::to_string(n);
      return *this;
    }
References m_rep, and n.
setNum() [15/16]
QCString & QCString::setNum (ushort n) [inline]
Definition at line 404 of file qcstring.h.
    {
      m_rep = std::to_string(n);
      return *this;
    }
References m_rep, and n.
setNum() [16/16]
QCString & QCString::setNum (ushort n) [inline]
Definition at line 404 of file qcstring.h.
    {
      m_rep = std::to_string(n);
      return *this;
    }
References m_rep, and n.
simplifyWhiteSpace() [1/2]
QCString QCString::simplifyWhiteSpace () const
return a copy of this string with leading and trailing whitespace removed and multiple whitespace characters replaced by a single space
Definition at line 185 of file qcstring.cpp.
{
  if (isEmpty()) // nothing to do
    return *this;
  QCString result(length()+1);
  const char *from = data();
  char *to = result.rawData();
  char *first = to;
  while (TRUE)
  {
    while (*from && qisspace(*from))
      from++;
    while (*from && !qisspace(*from))
      *to++ = *from++;
    if (*from)
      *to++ = 0x20; // ' '
    else
      break;
  }
  if (to > first && *(to-1) == 0x20)
    to--;
  *to = '\0';
  result.resize(static_cast<int>(to - result.data()) + 1);
  return result;
}
References data(), isEmpty(), length(), qisspace(), rawData(), resize(), and TRUE.
Referenced by DefinitionImpl::_docsAlreadyAdded(), addVariable(), VHDLOutlineParser::checkInlineCode(), findAndRemoveWord(), Markdown::processLink(), MemberDefImpl::setBitfields(), MemberDefImpl::writeDeclaration(), MemberDefImpl::writeDocumentation(), FlowChart::writeFlowLinks(), and MemberDefImpl::writeMemberDocSimple().
simplifyWhiteSpace() [2/2]
QCString QCString::simplifyWhiteSpace () const
return a copy of this string with leading and trailing whitespace removed and multiple whitespace characters replaced by a single space
size() [1/2]
uint QCString::size () const [inline]
Returns the length of the string, not counting the 0-terminator.
Definition at line 150 of file qcstring.h.
{ return static_cast<uint>(m_rep.size()); }
References m_rep.
Referenced by argumentData(), Markdown::extractPageTitle(), DocParser::findDocsForMemberOrCompound(), findGlobalMember(), isExplicitPage(), QCString(), searchInputFiles(), and writeTable().
size() [2/2]
uint QCString::size () const [inline]
Returns the length of the string, not counting the 0-terminator.
Definition at line 150 of file qcstring.h.
{ return static_cast<uint>(m_rep.size()); }
References m_rep.
sprintf() [1/2]
QCString & QCString::sprintf (const char * format, ...)
Definition at line 29 of file qcstring.cpp.
{
  va_list ap;
  va_start(ap, format);
  const int minlen=256;
  int l = length();
  if (l<minlen) { resize(minlen); l=minlen; }
  int n=vsnprintf(rawData(), l, format, ap);
  if (n<0) n=l;
  resize(n+1);
  va_end(ap);
  return *this;
}
References length(), n, rawData(), and resize().
Referenced by addDependencies(), addFormula(), addIncludeFile(), addXRefItem(), FilterHex::apply(), buildFileList(), DocParser::checkArgumentName(), clearSubDirs(), convertCppComments(), convertNameToFile(), FormulaManager::createFormulasTexFile(), FormulaManager::createLatexFile(), createSubDirs(), dateTimeFromString(), dateToRTFDateString(), DocFormula::DocFormula(), encodeForOutput(), escapeComment(), escapeName(), escapeObject(), escapeWord(), expandAliasRec(), DocParser::findAndCopyImage(), generateClassMemberLink(), generateClassOrGlobalLink(), DotGfxHierarchyTable::getBaseName(), getLinkInScope(), FormulaManager::initFromRepository(), initPredefined(), XRefDummyCodeGenerator::linkableSymbol(), PerlModDocVisitor::operator()(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), RTFDocVisitor::operator()(), parseInput(), Preprocessor::processFile(), readIncludeFile(), replaceFunctionMacro(), runPlantumlContent(), saveObjCContext(), startCodeLine(), LayoutParser::startNavEntry(), RTFGenerator::startSection(), TranslatorArmenian::trDateTime(), TranslatorBulgarian::trDateTime(), TranslatorBrazilian::trDateTime(), TranslatorCatalan::trDateTime(), TranslatorChinese::trDateTime(), TranslatorCzech::trDateTime(), TranslatorGerman::trDateTime(), TranslatorDanish::trDateTime(), TranslatorEnglish::trDateTime(), TranslatorEsperanto::trDateTime(), TranslatorSpanish::trDateTime(), TranslatorPersian::trDateTime(), TranslatorFrench::trDateTime(), TranslatorGreek::trDateTime(), TranslatorHindi::trDateTime(), TranslatorCroatian::trDateTime(), TranslatorHungarian::trDateTime(), TranslatorIndonesian::trDateTime(), TranslatorItalian::trDateTime(), TranslatorJapanese::trDateTime(), TranslatorKorean::trDateTime(), TranslatorLatvian::trDateTime(), TranslatorDutch::trDateTime(), TranslatorPolish::trDateTime(), TranslatorPortuguese::trDateTime(), TranslatorRomanian::trDateTime(), TranslatorRussian::trDateTime(), TranslatorSlovak::trDateTime(), TranslatorSwedish::trDateTime(), TranslatorTurkish::trDateTime(), TranslatorChinesetraditional::trDateTime(), TranslatorUkrainian::trDateTime(), TranslatorJapanese::trWriteList(), writeDiaGraphFromFile(), ClassDiagram::writeFigure(), writeJavaScriptSearchIndex(), RTFGenerator::writeLineNumber(), LatexCodeGenerator::writeLineNumber(), DocbookCodeGenerator::writeLineNumber(), writeMscGraphFromFile(), Markdown::writeOneLineHeaderOrRuler(), and DefinitionImpl::writeSourceDef().
sprintf() [2/2]
QCString & QCString::sprintf (const char * format, ...)
startsWith() [1/4]
bool QCString::startsWith (const char * s) const [inline]
Definition at line 446 of file qcstring.h.
    {
      if (m_rep.empty() || s==0) return s==0;
      return m_rep.rfind(s,0)==0; // looking "backward" starting and ending at index 0
    }
References m_rep, and s.
Referenced by DocHtmlCell::alignment(), FilterRelative::apply(), DotFilePatcher::convertMapFile(), copyStyleSheet(), MemberDefImpl::createTemplateInstanceMember(), extractClassNameFromType(), fillColorStyleMap(), filterMemberDocumentation(), DocParser::findAndCopyImage(), findClassRelation(), DocParser::findDocsForMemberOrCompound(), findMember(), SymbolResolver::Private::followPath(), generateFunctionLink(), getCanonicalTypeForIdentifier(), getDefsOld(), DocParser::handleImage(), handleImage(), DocParser::handleLinkedWord(), CitationManager::insertCrossReferencesForBibFile(), SymbolResolver::Private::isAccessibleFrom(), DocFormula::isInline(), HtmlDocVisitor::operator()(), RTFDocVisitor::operator()(), SymbolModifiers::operator|=(), parseFuncDecl(), replaceRef(), resolveRef(), resolveSymlink(), startsWithKeyword(), stripTrailingReturn(), substituteHtmlKeywords(), substituteTemplateArgumentsInString(), substituteTemplatesInString(), LayoutNavEntry::url(), DefinitionImpl::writeDocAnchorsToTagFile(), HtmlGenerator::writeStyleInfo(), and writeUserGroupStubPage().
startsWith() [2/4]
bool QCString::startsWith (const char * s) const [inline]
Definition at line 446 of file qcstring.h.
    {
      if (m_rep.empty() || s==0) return s==0;
      return m_rep.rfind(s,0)==0; // looking "backward" starting and ending at index 0
    }
References m_rep, and s.
startsWith() [3/4]
bool QCString::startsWith (const QCString & s) const [inline]
Definition at line 452 of file qcstring.h.
    {
      if (m_rep.empty() || s.isEmpty()) return s.isEmpty();
      return m_rep.rfind(s.str(),0)==0; // looking "backward" starting and ending at index 0
    }
References m_rep, and s.
startsWith() [4/4]
bool QCString::startsWith (const QCString & s) const [inline]
Definition at line 452 of file qcstring.h.
    {
      if (m_rep.empty() || s.isEmpty()) return s.isEmpty();
      return m_rep.rfind(s.str(),0)==0; // looking "backward" starting and ending at index 0
    }
References m_rep, and s.
str() [1/2]
const std::string & QCString::str () const [inline]
Definition at line 480 of file qcstring.h.
    {
      return m_rep;
    }
References m_rep.
Referenced by DefinitionImpl::_setBriefDescription(), MemberDefImpl::_writeReimplementedBy(), DefinitionImpl::_writeSourceRefList(), SymbolResolver::Private::accessibleViaUsingNamespace(), LinkedMap< T, Hash, KeyEqual, Map >::add(), LinkedRefMap< T, Hash, KeyEqual, Map >::add(), DotClassGraph::addClass(), addDefine(), DotGfxHierarchyTable::addHierarchy(), HtmlHelp::addImageFile(), FileDefImpl::addIncludedByDependency(), FileDefImpl::addIncludeDependency(), TemplateContextImpl::addIndexEntry(), DocSets::addIndexItem(), HtmlHelpIndex::addItem(), addLocalVar(), addMemberToSearchIndex(), Preprocessor::addSearchDir(), DefinitionImpl::addSourceReferencedBy(), DefinitionImpl::addSourceReferences(), HtmlHelp::addStyleSheetFile(), addToIndices(), addVariable(), addVariableToFile(), SearchIndex::addWordRec(), FlowChart::alignCommentNode(), DotInclDepGraph::buildGraph(), DotCallGraph::buildGraph(), Config::checkAndCorrect(), checkAndOpenFile(), DocParser::checkArgumentName(), VHDLOutlineParser::checkInlineCode(), DocParser::checkUnOrMultipleDocumentedParams(), DocbookGenerator::cleanup(), HtmlGenerator::cleanup(), LatexGenerator::cleanup(), ManGenerator::cleanup(), RTFGenerator::cleanup(), clearSubDirs(), TemplateContextImpl::closeSubIndex(), computeTemplateClassRelations(), computeVerifiedDotPath(), contains(), containsEnvVar(), containsWord(), DotFilePatcher::convertMapFile(), convertMapFile(), copyFile(), copyLogo(), ResourceMgr::copyResourceAs(), copyStyleSheet(), DotManager::createFilePatcher(), FormulaManager::createFormulasTexFile(), VHDLOutlineParser::createFunction(), FormulaManager::createLatexFile(), createOutputDirectory(), HtmlHelp::Private::createProjectFile(), DotManager::createRunner(), createSubDirs(), dateTimeFromString(), LinkedMap< T, Hash, KeyEqual, Map >::del(), LinkedRefMap< T, Hash, KeyEqual, Map >::del(), deliverablesPresent(), determineAbsoluteIncludeName(), determineInkscapeVersion(), FilterAlphaIndex::determineSortKey(), MemberDefImpl::displayDefinition(), DocEmoji::DocEmoji(), DotCallGraph::DotCallGraph(), DotClassGraph::DotClassGraph(), DotGroupCollaboration::DotGroupCollaboration(), DotInclDepGraph::DotInclDepGraph(), vhdl::parser::VhdlParser::element_declaration(), LayoutParser::endElement(), anonymous_namespace{tagreader.cpp}::TagFileParser::endEnumValue(), endScope(), escapeAliases(), CondParser::evalVariable(), ExistsOnPath(), expandAlias(), expandAliasRec(), expandExpression(), externalRef(), DefinitionImpl::externalReference(), extractCanonicalType(), extractClassNameFromType(), extractDirection(), extractTitleId(), fillColorStyleMap(), filterMemberDocumentation(), filterTitle(), find(), LinkedMap< T, Hash, KeyEqual, Map >::find(), LinkedRefMap< T, Hash, KeyEqual, Map >::find(), CitationManager::find(), SectionRefs::find(), DocParser::findAndCopyImage(), findAndRemoveWord(), VhdlDocGen::findArchitecture(), findBaseClassesForClass(), findClassEntries(), findClassRelation(), findFileDef(), VhdlDocGen::findKeyWord(), VhdlDocGen::findMemberDef(), findPackageScope(), findPackageScopeFromPath(), findRev(), findTemplateInstanceRelation(), findUsedClassesForClass(), formatBriefNote(), generateDEF(), generateFileSources(), generateFunctionLink(), FormulaManager::generateImages(), generateJSNavTree(), generateJSTree(), generateOutput(), generateOutputViaTemplate(), CitationManager::generatePage(), generateTemplateFiles(), FTVHelp::generateTreeViewScripts(), generateXML(), generateXMLForClass(), generateXMLForConcept(), generateXMLForDir(), generateXMLForFile(), generateXMLForGroup(), generateXMLForNamespace(), generateXMLForPage(), genericPatternMatch(), MemberDefImpl::getClassDefOfAnonymousType(), DocVisitor::getCodeParser(), getConvertLatexMacro(), Portable::getenv(), FilterCache::getFileContents(), getFilteredImageAttributes(), getFilterFromList(), getFortranDefs(), getLanguageFromFileName(), SymbolResolver::Private::getResolvedSymbolRec(), SymbolResolver::Private::getResolvedTypeRec(), guessSection(), DocPara::handleCommand(), handleFileInfo(), DocParser::handleImage(), DocParser::handleStyleArgument(), DocbookGenerator::init(), HtmlGenerator::init(), LatexGenerator::init(), ManGenerator::init(), RTFGenerator::init(), FormulaManager::initFromRepository(), DocSets::initialize(), HtmlHelp::initialize(), Qhp::initialize(), initPredefined(), initUCF(), CitationManager::insert(), CitationManager::insertCrossReferencesForBibFile(), insertDimension(), insertMapFile(), ClassDefImpl::internalInsertMember(), FileDefImpl::isIncluded(), isURL(), isVarWithConstructor(), labelToEnumValue(), CitationManager::latexBibFiles(), linkifyText(), TemplateEngine::Private::loadByName(), Htags::loadFilemap(), markdownFileNameToId(), matchExcludedSymbols(), TemplateNodeCreator< T >::mkpath(), HtmlEntityMapper::name2sym(), SymbolResolver::Private::newResolveTypedef(), TemplateContextImpl::openSubIndex(), operator!=(), ManDocVisitor::operator()(), XmlDocVisitor::operator()(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), RTFDocVisitor::operator()(), operator+(), operator=(), operator==(), TemplateParser::parse(), parseFile(), VhdlDocGen::parseForBinding(), VhdlDocGen::parseForConfig(), parseInput(), MarkdownOutlineParser::parseInput(), parseMain(), VhdlDocGen::parseUCF(), Htags::path2URL(), LinkedMap< T, Hash, KeyEqual, Map >::prepend(), LinkedRefMap< T, Hash, KeyEqual, Map >::prepend(), preProcessFile(), RTFGenerator::preProcessFileInplace(), FlowChart::printNode(), processConcatOperators(), Markdown::processLink(), readAliases(), readCodeFragment(), readConfiguration(), readIncludeFile(), readInputFile(), readSVGSize(), readTagFile(), ParserManager::registerExtension(), removeAnonymousScopes(), TemplateNodeCreate::render(), TemplateNodeResource::render(), TemplateNodeMarkers::render(), replaceColorMarkers(), replaceFunctionMacro(), replaceVariables(), resetPDFSize(), resolveLink(), resolveSymlink(), rtfFormatBmkStr(), DotFilePatcher::run(), runPlantumlContent(), sameMd5Signature(), searchId(), TemplateContextImpl::selectEscapeIntf(), SearchIndex::setCurrentDoc(), SearchIndexExternal::setCurrentDoc(), Portable::setenv(), TemplateContextImpl::setEscapeIntf(), simplifyTypeForTable(), ManGenerator::startDoxyAnchor(), LayoutParser::startElement(), RTFGenerator::startSection(), substEnvVarsInString(), substEnvVarsInStrList(), substituteHtmlKeywords(), substituteLatexKeywords(), substituteTemplateArgumentsInString(), substituteTemplatesInString(), tryPath(), Portable::unsetenv(), updateEPSBoundingBox(), updateLanguageMapping(), DotAttributes::updateValue(), SearchIndex::write(), SearchIndexExternal::write(), writeAlphabeticalClassList(), ResourceMgr::writeCategory(), writeCombineScript(), MemberDefImpl::writeDeclaration(), writeDiaGraphFromFile(), MemberDefImpl::writeDocumentation(), MemberList::writeDocumentationPage(), writeDotDirDepGraph(), writeDotGraphFromFile(), writeDotImageMapFromFile(), FlowChart::writeEdge(), writeExamples(), HtmlGenerator::writeExternalSearchPage(), ClassDiagram::writeFigure(), writeFileIndex(), FlowChart::writeFlowChart(), VhdlDocGen::writeFormatString(), DotGfxHierarchyTable::writeGraph(), DotGraph::writeGraph(), ClassDefImpl::writeInheritanceGraph(), VhdlDocGen::writeInlineClassLink(), writeJavaScriptSearchIndex(), DotNode::writeLabel(), writeLatexMakefile(), writeMakeBat(), ClassDefImpl::writeMemberList(), writeMenuData(), VhdlDocGen::writeOverview(), VhdlDocGen::writePlainVHDLDeclarations(), PlantumlManager::writePlantUMLSource(), VhdlDocGen::writeRecUnitDocu(), HtmlGenerator::writeSearchData(), HtmlGenerator::writeSearchPage(), FlowChart::writeShape(), HtmlGenerator::writeStyleInfo(), writeTagFile(), and writeWord().
str() [2/2]
const std::string & QCString::str () const [inline]
Definition at line 480 of file qcstring.h.
    {
      return m_rep;
    }
References m_rep.
stripPrefix() [1/4]
bool QCString::stripPrefix (const char * prefix) [inline]
Definition at line 207 of file qcstring.h.
    {
      return stripPrefix(QCString(prefix));
    }
References QCString(), and stripPrefix().
stripPrefix() [2/4]
bool QCString::stripPrefix (const char * prefix) [inline]
Definition at line 207 of file qcstring.h.
    {
      return stripPrefix(QCString(prefix));
    }
References QCString(), and stripPrefix().
stripPrefix() [3/4]
bool QCString::stripPrefix (const QCString & prefix) [inline]
Definition at line 197 of file qcstring.h.
    {
      if (prefix.isEmpty() || m_rep.empty()) return FALSE;
      if (m_rep.rfind(prefix.data(),0)==0) // string starts with prefix
      {
        m_rep.erase(0,prefix.length());
        return TRUE;
      }
      return FALSE;
    }
References data(), FALSE, isEmpty(), length(), m_rep, and TRUE.
Referenced by VHDLOutlineParser::addLibUseClause(), addMemberDocs(), addMemberFunction(), addVariable(), addVariableToClass(), addVariableToFile(), VhdlDocGen::correctMemberProperties(), extractCanonicalType(), findMember(), VhdlDocGen::formatString(), generateClassOrGlobalLink(), generateMemLink(), getCanonicalTypeForIdentifier(), MemberDefImpl::getClassDefOfAnonymousType(), VhdlDocGen::getClassName(), MemberDefImpl::getDeclType(), VHDLOutlineParser::handleFlowComment(), MemberDefImpl::IMPL::init(), initUCF(), SymbolResolver::Private::newResolveTypedef(), VhdlDocGen::parseUCF(), stripPrefix(), stripQualifiers(), subrHandleCommentBlock(), subrHandleCommentBlockResult(), MemberDefImpl::writeDeclaration(), VhdlDocGen::writeFuncProcDocu(), writeFuncProto(), VhdlDocGen::writeFunctionProto(), VhdlDocGen::writeInlineClassLink(), VhdlDocGen::writeVHDLDeclaration(), VhdlDocGen::writeVhdlLink(), and VhdlDocGen::writeVHDLTypeDocumentation().
stripPrefix() [4/4]
bool QCString::stripPrefix (const QCString & prefix) [inline]
Definition at line 197 of file qcstring.h.
    {
      if (prefix.isEmpty() || m_rep.empty()) return FALSE;
      if (m_rep.rfind(prefix.data(),0)==0) // string starts with prefix
      {
        m_rep.erase(0,prefix.length());
        return TRUE;
      }
      return FALSE;
    }
References data(), FALSE, isEmpty(), length(), m_rep, and TRUE.
stripWhiteSpace() [1/2]
QCString QCString::stripWhiteSpace () const [inline]
returns a copy of this string with leading and trailing whitespace removed
Definition at line 243 of file qcstring.h.
    {
      size_t sl = m_rep.size();
      if (sl==0 || (!qisspace(m_rep[0]) && !qisspace(m_rep[sl-1]))) return *this;
      size_t start=0,end=sl-1;
      while (start<sl && qisspace(m_rep[start])) start++;
      if (start==sl) return QCString(); // only whitespace
      while (end>start && qisspace(m_rep[end])) end--;
      return QCString(m_rep.substr(start,1+end-start));
    }
References ghc::filesystem::end(), m_rep, QCString(), qisspace(), and caseconvert::sl.
Referenced by DefinitionImpl::_setBriefDescription(), abbreviate(), FileDefImpl::acquireFileVersion(), addDefine(), addIncludeFile(), addKnRArgInfo(), addMacroDefinition(), addPerlModDocBlock(), addRelatedPage(), addSubprogram(), TemplateLexer::addToken(), adjustConfiguration(), appStringLower(), buildPageList(), Config::checkAndCorrect(), DocParser::checkArgumentName(), checkList(), DocParser::checkUnOrMultipleDocumentedParams(), compareString(), convertCppComments(), convertStringToBool(), ConfigEnum::convertStrToVal(), ConfigBool::convertStrToVal(), anonymous_namespace{tagreader.cpp}::TagFileParser::endEnumValue(), expandExpression(), extractBind(), extractCanonicalArgType(), extractCanonicalType(), extractFromParens(), fillColorStyleMap(), findMainPage(), findMember(), VhdlDocGen::formatString(), generateFunctionLink(), getCanonicalTemplateSpec(), getFilteredImageAttributes(), DocPara::handleCommand(), handleFileInfo(), VHDLOutlineParser::handleFlowComment(), handleGuard(), DocParser::handleImage(), handleImage(), DocPara::handleInclude(), DocPara::handleShowDate(), handleToc(), initUCF(), CitationManager::insertCrossReferencesForBibFile(), ConfigList::isDefault(), ConfigString::isDefault(), Htags::loadFilemap(), mergeArguments(), DocGroup::open(), DocIndexEntry::parse(), parseCommentAsText(), VhdlDocGen::parseFuncProto(), MarkdownOutlineParser::parseInput(), VhdlDocGen::parseUCF(), VhdlDocGen::prepareComment(), FlowChart::printNode(), FlowChart::printPlantUmlNode(), Markdown::processLink(), processList(), processStoreRepl(), processString(), readAliases(), readIncludeFile(), readTagFile(), replaceFunctionMacro(), split(), splitKnRArg(), startOfRequiresExpression(), stripIrrelevantString(), stripTrailingReturn(), subrHandleCommentBlock(), subrHandleCommentBlockResult(), substEnvVarsInString(), substituteTemplateArgumentsInString(), Portable::system(), LayoutNavEntry::url(), MemberList::writeDeclarations(), writeExceptionList(), HtmlGenerator::writeExternalSearchPage(), VhdlDocGen::writeFunctionProto(), VhdlDocGen::writeVHDLTypeDocumentation(), and writeXMLDocBlock().
stripWhiteSpace() [2/2]
QCString QCString::stripWhiteSpace () const [inline]
returns a copy of this string with leading and trailing whitespace removed
Definition at line 243 of file qcstring.h.
    {
      size_t sl = m_rep.size();
      if (sl==0 || (!qisspace(m_rep[0]) && !qisspace(m_rep[sl-1]))) return *this;
      size_t start=0,end=sl-1;
      while (start<sl && qisspace(m_rep[start])) start++;
      if (start==sl) return QCString(); // only whitespace
      while (end>start && qisspace(m_rep[end])) end--;
      return QCString(m_rep.substr(start,1+end-start));
    }
References ghc::filesystem::end(), m_rep, QCString(), qisspace(), and caseconvert::sl.
toInt() [1/2]
int QCString::toInt (bool * ok = 0, int base = 10) const
Definition at line 249 of file qcstring.cpp.
{
  return static_cast<int>(toLong(ok, base));
}
References toLong().
Referenced by ConfigInt::convertStrToVal(), TemplateContextImpl::get(), insertDimension(), replaceAliasArguments(), runQHelpGenerator(), TranslatorSlovak::trAndMore(), FilterAdd::variantIntValue(), and writeObjCMethodCall().
toInt() [2/2]
int QCString::toInt (bool * ok = 0, int base = 10) const
toLong() [1/2]
long QCString::toLong (bool * ok = 0, int base = 10) const
Definition at line 260 of file qcstring.cpp.
{
  const char *p = data();
  long val=0;
  int l = length();
  const long max_mult = INT_MAX / base;
  bool is_ok = FALSE;
  int neg = 0;
  if (!p)
    goto bye;
  while (l && qisspace(*p)) // skip leading space
    l--,p++;
  if (l && *p == '-') {
    l--;
    p++;
    neg = 1;
  } else if (*p == '+') {
    l--;
    p++;
  }
  // NOTE: toULong() code is similar
  if (!l || !ok_in_base(*p,base))
    goto bye;
  while (l && ok_in_base(*p,base)) {
    l--;
    int dv;
    if (*p>='0' && *p<='9') {
      dv = *p-'0';
    } else {
      if (*p >= 'a' && *p <= 'z')
        dv = *p - 'a' + 10;
      else
        dv = *p - 'A' + 10;
    }
    if (val > max_mult || (val == max_mult && dv > (INT_MAX%base)+neg))
      goto bye;
    val = base*val + dv;
    p++;
  }
  if (neg)
    val = -val;
  while (l && qisspace(*p)) // skip trailing space
    l--,p++;
  if (!l)
    is_ok = TRUE;
bye:
  if (ok)
    *ok = is_ok;
  return is_ok ? val : 0;
}
References data(), FALSE, length(), ok_in_base(), p, qisspace(), TRUE, and testsqlite3::val.
Referenced by toInt(), and toShort().
toLong() [2/2]
long QCString::toLong (bool * ok = 0, int base = 10) const
toShort() [1/2]
short QCString::toShort (bool * ok = 0, int base = 10) const
Definition at line 229 of file qcstring.cpp.
{
  long v = toLong(ok, base);
  if (ok && *ok && (v < -32768 || v > 32767)) {
    *ok = FALSE;
    v = 0;
  }
  return static_cast<short>(v);
}
References FALSE, and toLong().
toShort() [2/2]
short QCString::toShort (bool * ok = 0, int base = 10) const
toUInt() [1/2]
uint QCString::toUInt (bool * ok = 0, int base = 10) const
Definition at line 254 of file qcstring.cpp.
{
  return static_cast<uint>(toULong(ok, base));
}
References toULong().
Referenced by extractLanguageSpecificTitle().
toUInt() [2/2]
uint QCString::toUInt (bool * ok = 0, int base = 10) const
toUInt64() [1/2]
uint64 QCString::toUInt64 (bool * ok = 0, int base = 10) const
Definition at line 356 of file qcstring.cpp.
{
  const char *p = data();
  uint64 val=0;
  int l = length();
  const uint64 max_mult = 1844674407370955161ULL; // ULLONG_MAX/10, rounded down
  bool is_ok = FALSE;
  if (!p)
    goto bye;
  while (l && qisspace(*p)) // skip leading space
    l--,p++;
  if (*p == '+')
    l--,p++;
  // NOTE: toULong() code is similar
  if (!l || !ok_in_base(*p,base))
    goto bye;
  while (l && ok_in_base(*p,base)) {
    l--;
    uint dv;
    if (*p>='0' && *p<='9') {
      dv = *p-'0';
    } else {
      if (*p >= 'a' && *p <= 'z')
        dv = *p - 'a' + 10;
      else
        dv = *p - 'A' + 10;
    }
    if (val > max_mult || (val == max_mult && dv > (ULLONG_MAX%base)))
      goto bye;
    val = base*val + dv;
    p++;
  }
  while (l && qisspace(*p)) // skip trailing space
    l--,p++;
  if (!l)
    is_ok = TRUE;
bye:
  if (ok)
    *ok = is_ok;
  return is_ok ? val : 0;
}
References data(), FALSE, length(), ok_in_base(), p, qisspace(), TRUE, and testsqlite3::val.
Referenced by getCurrentDateTime().
toUInt64() [2/2]
uint64 QCString::toUInt64 (bool * ok = 0, int base = 10) const
toULong() [1/2]
ulong QCString::toULong (bool * ok = 0, int base = 10) const
Definition at line 312 of file qcstring.cpp.
{
  const char *p = data();
  ulong val=0;
  int l = length();
  const ulong max_mult = 429496729; // UINT_MAX/10, rounded down
  bool is_ok = FALSE;
  if (!p)
    goto bye;
  while (l && qisspace(*p)) // skip leading space
    l--,p++;
  if (*p == '+')
    l--,p++;
  // NOTE: toLong() code is similar
  if (!l || !ok_in_base(*p,base))
    goto bye;
  while (l && ok_in_base(*p,base)) {
    l--;
    uint dv;
    if (*p>='0' && *p<='9') {
      dv = *p-'0';
    } else {
      if (*p >= 'a' && *p <= 'z')
        dv = *p - 'a' + 10;
      else
        dv = *p - 'A' + 10;
    }
    if (val > max_mult || (val == max_mult && dv > (UINT_MAX%base)))
      goto bye;
    val = base*val + dv;
    p++;
  }
  while (l && qisspace(*p)) // skip trailing space
    l--,p++;
  if (!l)
    is_ok = TRUE;
bye:
  if (ok)
    *ok = is_ok;
  return is_ok ? val : 0;
}
References data(), FALSE, length(), ok_in_base(), p, qisspace(), TRUE, and testsqlite3::val.
Referenced by toUInt(), and toUShort().
toULong() [2/2]
ulong QCString::toULong (bool * ok = 0, int base = 10) const
toUShort() [1/2]
ushort QCString::toUShort (bool * ok = 0, int base = 10) const
Definition at line 239 of file qcstring.cpp.
{
  ulong v = toULong(ok, base);
  if (ok && *ok && (v > 65535)) {
    *ok = FALSE;
    v = 0;
  }
  return static_cast<ushort>(v);
}
References FALSE, and toULong().
toUShort() [2/2]
ushort QCString::toUShort (bool * ok = 0, int base = 10) const
truncate() [1/2]
bool QCString::truncate (size_t pos) [inline]
Truncates the string at position pos.
Definition at line 167 of file qcstring.h.
{ return resize(pos + 1); }
References resize().
Referenced by readCodeFragment().
truncate() [2/2]
bool QCString::truncate (size_t pos) [inline]
Truncates the string at position pos.
Definition at line 167 of file qcstring.h.
{ return resize(pos + 1); }
References resize().
upper() [1/2]
QCString QCString::upper () const [inline]
Definition at line 237 of file qcstring.h.
    {
      return QCString(convertUTF8ToUpper(m_rep));
    }
References convertUTF8ToUpper(), m_rep, and QCString().
Referenced by FilterUpper::apply(), VhdlDocGen::findMember(), TranslatorBrazilian::trDayOfWeek(), TranslatorCatalan::trDayOfWeek(), TranslatorCzech::trDayOfWeek(), TranslatorDanish::trDayOfWeek(), TranslatorEsperanto::trDayOfWeek(), TranslatorSpanish::trDayOfWeek(), TranslatorFinnish::trDayOfWeek(), TranslatorFrench::trDayOfWeek(), TranslatorHungarian::trDayOfWeek(), TranslatorItalian::trDayOfWeek(), TranslatorLithuanian::trDayOfWeek(), TranslatorLatvian::trDayOfWeek(), TranslatorDutch::trDayOfWeek(), TranslatorNorwegian::trDayOfWeek(), TranslatorPolish::trDayOfWeek(), TranslatorPortuguese::trDayOfWeek(), TranslatorRomanian::trDayOfWeek(), TranslatorSlovene::trDayOfWeek(), TranslatorSlovak::trDayOfWeek(), TranslatorSerbian::trDayOfWeek(), TranslatorSwedish::trDayOfWeek(), TranslatorAfrikaans::trDayOfWeek(), TranslatorBrazilian::trMonth(), TranslatorCatalan::trMonth(), TranslatorCzech::trMonth(), TranslatorDanish::trMonth(), TranslatorEsperanto::trMonth(), TranslatorSpanish::trMonth(), TranslatorFinnish::trMonth(), TranslatorFrench::trMonth(), TranslatorHungarian::trMonth(), TranslatorItalian::trMonth(), TranslatorLithuanian::trMonth(), TranslatorLatvian::trMonth(), TranslatorDutch::trMonth(), TranslatorNorwegian::trMonth(), TranslatorPolish::trMonth(), TranslatorPortuguese::trMonth(), TranslatorRomanian::trMonth(), TranslatorSlovene::trMonth(), TranslatorSlovak::trMonth(), TranslatorSerbian::trMonth(), TranslatorSwedish::trMonth(), and TranslatorAfrikaans::trMonth().
upper() [2/2]
QCString QCString::upper () const [inline]
Definition at line 237 of file qcstring.h.
    {
      return QCString(convertUTF8ToUpper(m_rep));
    }
References convertUTF8ToUpper(), m_rep, and QCString().
Member Data Documentation
m_rep
std::string QCString::m_rep [private]
Definition at line 537 of file qcstring.h.
Referenced by append(), at(), data(), endsWith(), fill(), insert(), isEmpty(), isNull(), left(), length(), lower(), mid(), operator+=(), operator=(), operator[](), QCString(), quoted(), rawData(), remove(), removeWhiteSpace(), resize(), right(), setNum(), size(), startsWith(), str(), stripPrefix(), stripWhiteSpace(), and upper().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/qcstring.h
doxygen/src/qcstring.h
doxygen/build/doxygen/src/qcstring.cpp
doxygen/src/qcstring.cpp