DirContext::Private Class Reference
Classes
struct Cachable
Public Member Functions
Private (const DirDef *dd)
TemplateVariant get (const QCString &n) const
StringVector fields () const
TemplateVariant title () const
TemplateVariant highlight () const
TemplateVariant subHighlight () const
TemplateVariant dirName () const
TemplateVariant dirs () const
TemplateVariant files () const
TemplateVariant hasDetails () const
TemplateVariant compoundType () const
TemplateVariant relPath () const
DotDirDepsPtr getDirDepsGraph () const
TemplateVariant hasDirGraph () const
TemplateVariant dirGraph () const
Private (const DirDef *dd)
TemplateVariant get (const QCString &n) const
StringVector fields () const
TemplateVariant title () const
TemplateVariant highlight () const
TemplateVariant subHighlight () const
TemplateVariant dirName () const
TemplateVariant dirs () const
TemplateVariant files () const
TemplateVariant hasDetails () const
TemplateVariant compoundType () const
TemplateVariant relPath () const
DotDirDepsPtr getDirDepsGraph () const
TemplateVariant hasDirGraph () const
TemplateVariant dirGraph () const
Private Member Functions
TemplateVariant createDirs () const
TemplateVariant createFiles () const
DotDirDepsPtr createDirDepsGraph () const
TemplateVariant createDirs () const
TemplateVariant createFiles () const
DotDirDepsPtr createDirDepsGraph () const
Private Attributes
const DirDef * m_dirDef
Cachable m_cachable
Static Private Attributes
static const PropertyMap< DirContext::Private > s_inst
Additional Inherited Members
Detailed Description
Definition at line 3114 of file context.cpp.
Constructor & Destructor Documentation
Private() [1/2]
DirContext::Private::Private (const DirDef * dd) [inline]
Definition at line 3117 of file context.cpp.
                              : DefinitionContext<DirContext::Private>(dd) , m_dirDef(dd)
    {
    }
Private() [2/2]
DirContext::Private::Private (const DirDef * dd) [inline]
Definition at line 3117 of file context.cpp.
                              : DefinitionContext<DirContext::Private>(dd) , m_dirDef(dd)
    {
    }
Member Function Documentation
compoundType() [1/2]
TemplateVariant DirContext::Private::compoundType () const [inline]
Definition at line 3133 of file context.cpp.
{ return theTranslator->trDir(FALSE,TRUE); }
References FALSE, theTranslator, Translator::trDir(), and TRUE.
compoundType() [2/2]
TemplateVariant DirContext::Private::compoundType () const [inline]
Definition at line 3133 of file context.cpp.
{ return theTranslator->trDir(FALSE,TRUE); }
References FALSE, theTranslator, Translator::trDir(), and TRUE.
createDirDepsGraph() [1/2]
DotDirDepsPtr DirContext::Private::createDirDepsGraph () const [inline], [private]
Definition at line 3214 of file context.cpp.
    {
      return std::make_shared<DotDirDeps>(m_dirDef);
    }
References m_dirDef.
createDirDepsGraph() [2/2]
DotDirDepsPtr DirContext::Private::createDirDepsGraph () const [inline], [private]
Definition at line 3214 of file context.cpp.
    {
      return std::make_shared<DotDirDeps>(m_dirDef);
    }
createDirs() [1/2]
TemplateVariant DirContext::Private::createDirs () const [inline], [private]
Definition at line 3194 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_dirDef->subDirs().size());
      for(const auto dd : m_dirDef->subDirs())
      {
        list.push_back(DirContext::alloc(dd));
      }
      return TemplateImmutableList::alloc(list);
    }
References DirContext::alloc(), TemplateImmutableList::alloc(), m_dirDef, and DirDef::subDirs().
createDirs() [2/2]
TemplateVariant DirContext::Private::createDirs () const [inline], [private]
Definition at line 3194 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_dirDef->subDirs().size());
      for(const auto dd : m_dirDef->subDirs())
      {
        list.push_back(DirContext::alloc(dd));
      }
      return TemplateImmutableList::alloc(list);
    }
References DirContext::alloc(), and TemplateImmutableList::alloc().
createFiles() [1/2]
TemplateVariant DirContext::Private::createFiles () const [inline], [private]
Definition at line 3204 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_dirDef->getFiles().size());
      for (const auto &fd : m_dirDef->getFiles())
      {
        list.push_back(FileContext::alloc(fd));
      }
      return TemplateImmutableList::alloc(list);
    }
References FileContext::alloc(), TemplateImmutableList::alloc(), DirDef::getFiles(), and m_dirDef.
createFiles() [2/2]
TemplateVariant DirContext::Private::createFiles () const [inline], [private]
Definition at line 3204 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_dirDef->getFiles().size());
      for (const auto &fd : m_dirDef->getFiles())
      {
        list.push_back(FileContext::alloc(fd));
      }
      return TemplateImmutableList::alloc(list);
    }
References FileContext::alloc(), and TemplateImmutableList::alloc().
dirGraph() [1/2]
TemplateVariant DirContext::Private::dirGraph () const [inline]
Definition at line 3149 of file context.cpp.
    {
      TextStream t;
      bool haveDot = Config_getBool(HAVE_DOT);
      bool dirGraph = Config_getBool(DIRECTORY_GRAPH);
      if (haveDot && dirGraph)
      {
        DotDirDepsPtr graph = getDirDepsGraph();
        switch (g_globals.outputFormat)
        {
          case ContextOutputFormat_Html:
            {
              graph->writeGraph(t,GOF_BITMAP,
                                EOF_Html,
                                g_globals.outputDir,
                                g_globals.outputDir+Portable::pathSeparator()+addHtmlExtensionIfMissing(m_dirDef->getOutputFileBase()),
                                relPathAsString(),
                                TRUE,
                                g_globals.dynSectionId,
                                FALSE);
            }
            break;
          case ContextOutputFormat_Latex:
            {
              graph->writeGraph(t,GOF_EPS,
                                EOF_LaTeX,
                                g_globals.outputDir,
                                g_globals.outputDir+Portable::pathSeparator()+m_dirDef->getOutputFileBase()+".tex",
                                relPathAsString(),
                                TRUE,
                                g_globals.dynSectionId,
                                FALSE);
            }
            break;
            // TODO: support other generators
          default:
            err("context.cpp: output format not yet supported\n");
            break;
        }
        g_globals.dynSectionId++;
      }
      return TemplateVariant(t.str().c_str(),TRUE);
    }
References addHtmlExtensionIfMissing(), Config_getBool, ContextOutputFormat_Html, ContextOutputFormat_Latex, dirGraph(), ContextGlobals::dynSectionId, EOF_Html, EOF_LaTeX, err(), FALSE, g_globals, getDirDepsGraph(), DirDef::getOutputFileBase(), GOF_BITMAP, GOF_EPS, m_dirDef, ContextGlobals::outputDir, ContextGlobals::outputFormat, Portable::pathSeparator(), DefinitionContext< DirContext::Private >::relPathAsString(), TextStream::str(), and TRUE.
Referenced by dirGraph(), and hasDirGraph().
dirGraph() [2/2]
TemplateVariant DirContext::Private::dirGraph () const [inline]
Definition at line 3149 of file context.cpp.
    {
      TextStream t;
      bool haveDot = Config_getBool(HAVE_DOT);
      bool dirGraph = Config_getBool(DIRECTORY_GRAPH);
      if (haveDot && dirGraph)
      {
        DotDirDepsPtr graph = getDirDepsGraph();
        switch (g_globals.outputFormat)
        {
          case ContextOutputFormat_Html:
            {
              graph->writeGraph(t,GOF_BITMAP,
                                EOF_Html,
                                g_globals.outputDir,
                                g_globals.outputDir+Portable::pathSeparator()+addHtmlExtensionIfMissing(m_dirDef->getOutputFileBase()),
                                relPathAsString(),
                                TRUE,
                                g_globals.dynSectionId,
                                FALSE);
            }
            break;
          case ContextOutputFormat_Latex:
            {
              graph->writeGraph(t,GOF_EPS,
                                EOF_LaTeX,
                                g_globals.outputDir,
                                g_globals.outputDir+Portable::pathSeparator()+m_dirDef->getOutputFileBase()+".tex",
                                relPathAsString(),
                                TRUE,
                                g_globals.dynSectionId,
                                FALSE);
            }
            break;
            // TODO: support other generators
          default:
            err("context.cpp: output format not yet supported\n");
            break;
        }
        g_globals.dynSectionId++;
      }
      return TemplateVariant(t.str().c_str(),TRUE);
    }
References addHtmlExtensionIfMissing(), Config_getBool, ContextOutputFormat_Html, ContextOutputFormat_Latex, ContextGlobals::dynSectionId, EOF_Html, EOF_LaTeX, err(), FALSE, g_globals, GOF_BITMAP, GOF_EPS, ContextGlobals::outputDir, ContextGlobals::outputFormat, Portable::pathSeparator(), TextStream::str(), and TRUE.
dirName() [1/2]
TemplateVariant DirContext::Private::dirName () const [inline]
Definition at line 3129 of file context.cpp.
{ return TemplateVariant(m_dirDef->shortName()); }
References m_dirDef, and DirDef::shortName().
dirName() [2/2]
TemplateVariant DirContext::Private::dirName () const [inline]
Definition at line 3129 of file context.cpp.
{ return TemplateVariant(m_dirDef->shortName()); }
dirs() [1/2]
TemplateVariant DirContext::Private::dirs () const [inline]
Definition at line 3130 of file context.cpp.
{ return m_cachable.dirs.get(this); }
References DirContext::Private::Cachable::dirs, and m_cachable.
dirs() [2/2]
TemplateVariant DirContext::Private::dirs () const [inline]
Definition at line 3130 of file context.cpp.
{ return m_cachable.dirs.get(this); }
fields() [1/2]
StringVector DirContext::Private::fields () const [inline]
Definition at line 3123 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
fields() [2/2]
StringVector DirContext::Private::fields () const [inline]
Definition at line 3123 of file context.cpp.
{ return s_inst.fields(); }
files() [1/2]
TemplateVariant DirContext::Private::files () const [inline]
Definition at line 3131 of file context.cpp.
{ return m_cachable.files.get(this); }
References DirContext::Private::Cachable::files, and m_cachable.
files() [2/2]
TemplateVariant DirContext::Private::files () const [inline]
Definition at line 3131 of file context.cpp.
{ return m_cachable.files.get(this); }
get() [1/2]
TemplateVariant DirContext::Private::get (const QCString & n) const [inline]
Definition at line 3122 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), n, and s_inst.
get() [2/2]
TemplateVariant DirContext::Private::get (const QCString & n) const [inline]
Definition at line 3122 of file context.cpp.
{ return s_inst.get(this,n); }
References n.
getDirDepsGraph() [1/2]
DotDirDepsPtr DirContext::Private::getDirDepsGraph () const [inline]
Definition at line 3135 of file context.cpp.
{ return m_cachable.dirDepsGraph.get(this); }
References DirContext::Private::Cachable::dirDepsGraph, and m_cachable.
Referenced by dirGraph(), and hasDirGraph().
getDirDepsGraph() [2/2]
DotDirDepsPtr DirContext::Private::getDirDepsGraph () const [inline]
Definition at line 3135 of file context.cpp.
{ return m_cachable.dirDepsGraph.get(this); }
hasDetails() [1/2]
TemplateVariant DirContext::Private::hasDetails () const [inline]
Definition at line 3132 of file context.cpp.
{ return m_dirDef->hasDetailedDescription(); }
References DirDef::hasDetailedDescription(), and m_dirDef.
hasDetails() [2/2]
TemplateVariant DirContext::Private::hasDetails () const [inline]
Definition at line 3132 of file context.cpp.
{ return m_dirDef->hasDetailedDescription(); }
hasDirGraph() [1/2]
TemplateVariant DirContext::Private::hasDirGraph () const [inline]
Definition at line 3137 of file context.cpp.
    {
      bool result=FALSE;
      bool haveDot = Config_getBool(HAVE_DOT);
      bool dirGraph = Config_getBool(DIRECTORY_GRAPH);
      if (haveDot && dirGraph)
      {
        DotDirDepsPtr graph = getDirDepsGraph();
        result = !graph->isTrivial();
      }
      return result;
    }
References Config_getBool, dirGraph(), FALSE, and getDirDepsGraph().
hasDirGraph() [2/2]
TemplateVariant DirContext::Private::hasDirGraph () const [inline]
Definition at line 3137 of file context.cpp.
    {
      bool result=FALSE;
      bool haveDot = Config_getBool(HAVE_DOT);
      bool dirGraph = Config_getBool(DIRECTORY_GRAPH);
      if (haveDot && dirGraph)
      {
        DotDirDepsPtr graph = getDirDepsGraph();
        result = !graph->isTrivial();
      }
      return result;
    }
References Config_getBool, and FALSE.
highlight() [1/2]
TemplateVariant DirContext::Private::highlight () const [inline]
Definition at line 3127 of file context.cpp.
{ return TemplateVariant("files"); }
Referenced by doxmlparser.compound.codelineType::__init__(), doxmlparser.compound.codelineType::add_highlight(), doxmlparser.compound.codelineType::buildChildren(), doxmlparser.compound.codelineType::exportChildren(), doxmlparser.compound.codelineType::get_highlight(), doxmlparser.compound.codelineType::hasContent_(), doxmlparser.compound.codelineType::insert_highlight_at(), doxmlparser.compound.codelineType::replace_highlight_at(), and doxmlparser.compound.codelineType::set_highlight().
highlight() [2/2]
TemplateVariant DirContext::Private::highlight () const [inline]
Definition at line 3127 of file context.cpp.
{ return TemplateVariant("files"); }
Referenced by doxmlparser.compound.codelineType::__init__(), doxmlparser.compound.codelineType::add_highlight(), doxmlparser.compound.codelineType::buildChildren(), doxmlparser.compound.codelineType::exportChildren(), doxmlparser.compound.codelineType::get_highlight(), doxmlparser.compound.codelineType::hasContent_(), doxmlparser.compound.codelineType::insert_highlight_at(), doxmlparser.compound.codelineType::replace_highlight_at(), and doxmlparser.compound.codelineType::set_highlight().
relPath() [1/2]
TemplateVariant DirContext::Private::relPath () const [inline], [virtual]
Reimplemented from DefinitionContext< DirContext::Private >.
Definition at line 3134 of file context.cpp.
{ return ""; }
relPath() [2/2]
TemplateVariant DirContext::Private::relPath () const [inline], [virtual]
Reimplemented from DefinitionContext< DirContext::Private >.
Definition at line 3134 of file context.cpp.
{ return ""; }
subHighlight() [1/2]
TemplateVariant DirContext::Private::subHighlight () const [inline]
Definition at line 3128 of file context.cpp.
{ return TemplateVariant(""); }
subHighlight() [2/2]
TemplateVariant DirContext::Private::subHighlight () const [inline]
Definition at line 3128 of file context.cpp.
{ return TemplateVariant(""); }
title() [1/2]
TemplateVariant DirContext::Private::title () const [inline]
Definition at line 3126 of file context.cpp.
{ return TemplateVariant(m_dirDef->shortTitle()); }
References m_dirDef, and DirDef::shortTitle().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
title() [2/2]
TemplateVariant DirContext::Private::title () const [inline]
Definition at line 3126 of file context.cpp.
{ return TemplateVariant(m_dirDef->shortTitle()); }
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
Member Data Documentation
m_cachable
Cachable DirContext::Private::m_cachable [private]
Definition at line 3225 of file context.cpp.
Referenced by dirs(), files(), and getDirDepsGraph().
m_dirDef
const DirDef * DirContext::Private::m_dirDef [private]
Definition at line 3218 of file context.cpp.
Referenced by createDirDepsGraph(), createDirs(), createFiles(), dirGraph(), dirName(), hasDetails(), and title().
s_inst
const PropertyMap< DirContext::Private > DirContext::Private::s_inst [static], [private]
Initial value:
{
  BASE_PROPERTIES,
  { "title", &Private::title },
  { "highlight", &Private::highlight },
  { "subhighlight", &Private::subHighlight },
  { "dirName", &Private::dirName },
  { "dirs", &Private::dirs },
  { "files", &Private::files },
  { "hasDetails", &Private::hasDetails },
  { "hasDirGraph", &Private::hasDirGraph },
  { "dirGraph", &Private::dirGraph },
  { "compoundType", &Private::compoundType }
}
Definition at line 3226 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp