AllMembersListContext::Private Class Reference
Public Member Functions
Private (const MemberNameInfoLinkedMap &ml)
Private (const MemberNameInfoLinkedMap &ml)
Additional Inherited Members
Detailed Description
Definition at line 7719 of file context.cpp.
Constructor & Destructor Documentation
Private() [1/2]
AllMembersListContext::Private::Private (const MemberNameInfoLinkedMap & ml) [inline]
Definition at line 7722 of file context.cpp.
    {
      bool hideUndocMembers = Config_getBool(HIDE_UNDOC_MEMBERS);
      for (auto &mni : ml)
      {
        for (auto &mi : *mni)
        {
          const MemberDef *md=mi->memberDef();
          const ClassDef *cd=md->getClassDef();
          if (cd && !md->isAnonymous())
          {
            if ((cd->isLinkable() && md->isLinkable()) ||
                (!cd->isArtificial() && !hideUndocMembers &&
                 (protectionLevelVisible(md->protection()) || md->isFriend())
                )
               )
            {
              append(MemberInfoContext::alloc(mi.get()));
            }
          }
        }
      }
    }
References MemberInfoContext::alloc(), GenericNodeListContext::append(), Config_getBool, MemberDef::getClassDef(), Definition::isAnonymous(), Definition::isArtificial(), MemberDef::isFriend(), ClassDef::isLinkable(), MemberDef::isLinkable(), MemberDef::protection(), and protectionLevelVisible().
Private() [2/2]
AllMembersListContext::Private::Private (const MemberNameInfoLinkedMap & ml) [inline]
Definition at line 7722 of file context.cpp.
    {
      bool hideUndocMembers = Config_getBool(HIDE_UNDOC_MEMBERS);
      for (auto &mni : ml)
      {
        for (auto &mi : *mni)
        {
          const MemberDef *md=mi->memberDef();
          const ClassDef *cd=md->getClassDef();
          if (cd && !md->isAnonymous())
          {
            if ((cd->isLinkable() && md->isLinkable()) ||
                (!cd->isArtificial() && !hideUndocMembers &&
                 (protectionLevelVisible(md->protection()) || md->isFriend())
                )
               )
            {
              append(MemberInfoContext::alloc(mi.get()));
            }
          }
        }
      }
    }
References MemberInfoContext::alloc(), Config_getBool, MemberDef::getClassDef(), Definition::isAnonymous(), Definition::isArtificial(), MemberDef::isFriend(), ClassDef::isLinkable(), MemberDef::isLinkable(), MemberDef::protection(), and protectionLevelVisible().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp