PerlModOutputStream Class Reference
Public Member Functions
PerlModOutputStream (std::ostream &t)
void add (char c)
void add (const QCString &s)
void add (int n)
void add (unsigned int n)
PerlModOutputStream (std::ostream &t)
void add (char c)
void add (const QCString &s)
void add (int n)
void add (unsigned int n)
Public Attributes
std::ostream & m_t
Detailed Description
Definition at line 47 of file perlmodgen.cpp.
Constructor & Destructor Documentation
PerlModOutputStream() [1/2]
PerlModOutputStream::PerlModOutputStream (std::ostream & t) [inline]
Definition at line 53 of file perlmodgen.cpp.
: m_t(t) { }
PerlModOutputStream() [2/2]
PerlModOutputStream::PerlModOutputStream (std::ostream & t) [inline]
Definition at line 53 of file perlmodgen.cpp.
: m_t(t) { }
Member Function Documentation
add() [1/8]
void PerlModOutputStream::add (char c)
Definition at line 61 of file perlmodgen.cpp.
{
  m_t << c;
  //if (m_t != 0)
  // (*m_t) << c;
  //else
  // m_s += c;
}
References c, and m_t.
Referenced by doxmlparser.compound.memberdefType::__init__(), PerlModOutput::add(), doxmlparser.compound.memberdefType::buildAttributes(), PerlModOutput::continueBlock(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), PerlModOutput::iaddField(), PerlModOutput::iaddFieldQuotedChar(), PerlModOutput::iaddFieldQuotedString(), PerlModOutput::iaddQuoted(), PerlModOutput::iclose(), PerlModOutput::indent(), PerlModOutput::iopen(), and doxmlparser.compound.memberdefType::set_add().
add() [2/8]
void PerlModOutputStream::add (char c)
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
add() [3/8]
void PerlModOutputStream::add (const QCString & s)
Definition at line 70 of file perlmodgen.cpp.
{
  m_t << s;
  //if (m_t != 0)
  // (*m_t) << s;
  //else
  // m_s += s;
}
References m_t, and s.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
add() [4/8]
void PerlModOutputStream::add (const QCString & s)
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
add() [5/8]
void PerlModOutputStream::add (int n)
Definition at line 79 of file perlmodgen.cpp.
{
  m_t << n;
  //if (m_t != 0)
  // (*m_t) << n;
  //else
  // m_s += QCString().setNum(n);
}
References m_t, and n.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
add() [6/8]
void PerlModOutputStream::add (int n)
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
add() [7/8]
void PerlModOutputStream::add (unsigned int n)
Definition at line 88 of file perlmodgen.cpp.
{
  m_t << n;
  //if (m_t != 0)
  // (*m_t) << n;
  //else
  // m_s += QCString().setNum(n);
}
References m_t, and n.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
add() [8/8]
void PerlModOutputStream::add (unsigned int n)
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
Member Data Documentation
m_t
std::ostream & PerlModOutputStream::m_t
Definition at line 51 of file perlmodgen.cpp.
Referenced by add().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/perlmodgen.cpp
doxygen/src/perlmodgen.cpp