FilterAppend Class Reference
The implementation of the `append` filter.
Static Public Member Functions
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &arg)
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &arg)
Detailed Description
The implementation of the `append` filter.
Definition at line 924 of file template.cpp.
Member Function Documentation
apply() [1/2]
static TemplateVariant FilterAppend::apply (const TemplateVariant & v, const TemplateVariant & arg) [inline], [static]
Definition at line 927 of file template.cpp.
    {
      if ((v.isString() || v.isInt()) &&
          (arg.isString() || arg.isInt()))
      {
        return TemplateVariant(v.toString() + arg.toString());
      }
      else
      {
        return v;
      }
    }
References TemplateVariant::isInt(), TemplateVariant::isString(), and TemplateVariant::toString().
apply() [2/2]
static TemplateVariant FilterAppend::apply (const TemplateVariant & v, const TemplateVariant & arg) [inline], [static]
Definition at line 927 of file template.cpp.
    {
      if ((v.isString() || v.isInt()) &&
          (arg.isString() || arg.isInt()))
      {
        return TemplateVariant(v.toString() + arg.toString());
      }
      else
      {
        return v;
      }
    }
References TemplateVariant::isInt(), TemplateVariant::isString(), and TemplateVariant::toString().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp