MemberDefMutable Class Reference
#include <memberdef.h>
Public Member Functions
virtual void setMemberType (MemberType t)=0
virtual void setDefinition (const QCString &d)=0
virtual void setFileDef (const FileDef *fd)=0
virtual void setAnchor ()=0
virtual void setProtection (Protection p)=0
virtual void setMemberSpecifiers (uint64 s)=0
virtual void mergeMemberSpecifiers (uint64 s)=0
virtual void setInitializer (const QCString &i)=0
virtual void setBitfields (const QCString &s)=0
virtual void setMaxInitLines (int lines)=0
virtual void setMemberClass (const ClassDef *cd)=0
virtual void setSectionList (const Definition *container, const MemberList *sl)=0
virtual void setGroupDef (const GroupDef *gd, Grouping::GroupPri_t pri, const QCString &fileName, int startLine, bool hasDocs, MemberDef *member=0)=0
virtual void setReadAccessor (const QCString &r)=0
virtual void setWriteAccessor (const QCString &w)=0
virtual void setTemplateSpecialization (bool b)=0
virtual void makeRelated ()=0
virtual void makeForeign ()=0
virtual void setInheritsDocsFrom (const MemberDef *md)=0
virtual void setTagInfo (const TagInfo *i)=0
virtual void setArgsString (const QCString &as)=0
virtual void incrementFlowKeyWordCount ()=0
virtual void setEnumBaseType (const QCString &type)=0
virtual void setReimplements (const MemberDef *md)=0
virtual void insertReimplementedBy (const MemberDef *md)=0
virtual void setRelatedAlso (ClassDef *cd)=0
virtual void insertEnumField (const MemberDef *md)=0
virtual void setEnumScope (const MemberDef *md, bool livesInsideEnum=FALSE)=0
virtual void setEnumClassScope (const ClassDef *cd)=0
virtual void setDocumentedEnumValues (bool value)=0
virtual void setAnonymousEnumType (const MemberDef *md)=0
virtual bool addExample (const QCString &anchor, const QCString &name, const QCString &file)=0
virtual void setPrototype (bool p, const QCString &df, int line, int column)=0
virtual void setExplicitExternal (bool b, const QCString &df, int line, int column)=0
virtual void setDeclFile (const QCString &df, int line, int column)=0
virtual void moveArgumentList (std::unique_ptr< ArgumentList > al)=0
virtual void moveDeclArgumentList (std::unique_ptr< ArgumentList > al)=0
virtual void resolveUnnamedParameters (const MemberDef *md)=0
virtual void setDefinitionTemplateParameterLists (const ArgumentLists &lists)=0
virtual void setTypeConstraints (const ArgumentList &al)=0
virtual void setType (const QCString &t)=0
virtual void setAccessorType (ClassDef *cd, const QCString &t)=0
virtual void setNamespace (const NamespaceDef *nd)=0
virtual void setMemberGroupId (int id)=0
virtual void makeImplementationDetail ()=0
virtual void setFromAnonymousMember (MemberDef *m)=0
virtual void enableCallGraph (bool e)=0
virtual void enableCallerGraph (bool e)=0
virtual void enableReferencedByRelation (bool e)=0
virtual void enableReferencesRelation (bool e)=0
virtual void setTemplateMaster (const MemberDef *mt)=0
virtual void addListReference (Definition *d)=0
virtual void setDocsForDefinition (bool b)=0
virtual void setGroupAlias (const MemberDef *md)=0
virtual void cacheTypedefVal (const ClassDef *val, const QCString &templSpec, const QCString &resolvedType)=0
virtual void invalidateTypedefValCache ()=0
virtual void invalidateCachedArgumentTypes ()=0
virtual void setMemberDefinition (MemberDef *md)=0
virtual void setMemberDeclaration (MemberDef *md)=0
virtual void copyArgumentNames (const MemberDef *bmd)=0
virtual void setCategory (ClassDef *)=0
virtual void setCategoryRelation (const MemberDef *)=0
virtual void setDocumentation (const QCString &d, const QCString &docFile, int docLine, bool stripWhiteSpace=TRUE)=0
virtual void setBriefDescription (const QCString &b, const QCString &briefFile, int briefLine)=0
virtual void setInbodyDocumentation (const QCString &d, const QCString &inbodyFile, int inbodyLine)=0
virtual void setHidden (bool b)=0
virtual void setRequiresClause (const QCString &req)=0
virtual void findSectionsInDocumentation ()=0
virtual void writeDocumentation (const MemberList *ml, int memCount, int memTotal, OutputList &ol, const QCString &scopeName, const Definition *container, bool inGroup, bool showEnumValues=FALSE, bool showInline=FALSE) const =0
virtual void writeMemberDocSimple (OutputList &ol, const Definition *container) const =0
virtual void writeTagFile (TextStream &, bool useQualifiedName) const =0
virtual void writeLink (OutputList &ol, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd, bool onlyText=FALSE) const =0
virtual void setAnonymousUsed () const =0
virtual void setFromAnonymousScope (bool b) const =0
virtual void setMemberType (MemberType t)=0
virtual void setDefinition (const QCString &d)=0
virtual void setFileDef (const FileDef *fd)=0
virtual void setAnchor ()=0
virtual void setProtection (Protection p)=0
virtual void setMemberSpecifiers (uint64 s)=0
virtual void mergeMemberSpecifiers (uint64 s)=0
virtual void setInitializer (const QCString &i)=0
virtual void setBitfields (const QCString &s)=0
virtual void setMaxInitLines (int lines)=0
virtual void setMemberClass (const ClassDef *cd)=0
virtual void setSectionList (const Definition *container, const MemberList *sl)=0
virtual void setGroupDef (const GroupDef *gd, Grouping::GroupPri_t pri, const QCString &fileName, int startLine, bool hasDocs, MemberDef *member=0)=0
virtual void setReadAccessor (const QCString &r)=0
virtual void setWriteAccessor (const QCString &w)=0
virtual void setTemplateSpecialization (bool b)=0
virtual void makeRelated ()=0
virtual void makeForeign ()=0
virtual void setInheritsDocsFrom (const MemberDef *md)=0
virtual void setTagInfo (const TagInfo *i)=0
virtual void setArgsString (const QCString &as)=0
virtual void incrementFlowKeyWordCount ()=0
virtual void setEnumBaseType (const QCString &type)=0
virtual void setReimplements (const MemberDef *md)=0
virtual void insertReimplementedBy (const MemberDef *md)=0
virtual void setRelatedAlso (ClassDef *cd)=0
virtual void insertEnumField (const MemberDef *md)=0
virtual void setEnumScope (const MemberDef *md, bool livesInsideEnum=FALSE)=0
virtual void setEnumClassScope (const ClassDef *cd)=0
virtual void setDocumentedEnumValues (bool value)=0
virtual void setAnonymousEnumType (const MemberDef *md)=0
virtual bool addExample (const QCString &anchor, const QCString &name, const QCString &file)=0
virtual void setPrototype (bool p, const QCString &df, int line, int column)=0
virtual void setExplicitExternal (bool b, const QCString &df, int line, int column)=0
virtual void setDeclFile (const QCString &df, int line, int column)=0
virtual void moveArgumentList (std::unique_ptr< ArgumentList > al)=0
virtual void moveDeclArgumentList (std::unique_ptr< ArgumentList > al)=0
virtual void resolveUnnamedParameters (const MemberDef *md)=0
virtual void setDefinitionTemplateParameterLists (const ArgumentLists &lists)=0
virtual void setTypeConstraints (const ArgumentList &al)=0
virtual void setType (const QCString &t)=0
virtual void setAccessorType (ClassDef *cd, const QCString &t)=0
virtual void setNamespace (const NamespaceDef *nd)=0
virtual void setMemberGroupId (int id)=0
virtual void makeImplementationDetail ()=0
virtual void setFromAnonymousMember (MemberDef *m)=0
virtual void enableCallGraph (bool e)=0
virtual void enableCallerGraph (bool e)=0
virtual void enableReferencedByRelation (bool e)=0
virtual void enableReferencesRelation (bool e)=0
virtual void setTemplateMaster (const MemberDef *mt)=0
virtual void addListReference (Definition *d)=0
virtual void setDocsForDefinition (bool b)=0
virtual void setGroupAlias (const MemberDef *md)=0
virtual void cacheTypedefVal (const ClassDef *val, const QCString &templSpec, const QCString &resolvedType)=0
virtual void invalidateTypedefValCache ()=0
virtual void invalidateCachedArgumentTypes ()=0
virtual void setMemberDefinition (MemberDef *md)=0
virtual void setMemberDeclaration (MemberDef *md)=0
virtual void copyArgumentNames (const MemberDef *bmd)=0
virtual void setCategory (ClassDef *)=0
virtual void setCategoryRelation (const MemberDef *)=0
virtual void setDocumentation (const QCString &d, const QCString &docFile, int docLine, bool stripWhiteSpace=TRUE)=0
virtual void setBriefDescription (const QCString &b, const QCString &briefFile, int briefLine)=0
virtual void setInbodyDocumentation (const QCString &d, const QCString &inbodyFile, int inbodyLine)=0
virtual void setHidden (bool b)=0
virtual void setRequiresClause (const QCString &req)=0
virtual void findSectionsInDocumentation ()=0
virtual void writeDocumentation (const MemberList *ml, int memCount, int memTotal, OutputList &ol, const QCString &scopeName, const Definition *container, bool inGroup, bool showEnumValues=FALSE, bool showInline=FALSE) const =0
virtual void writeMemberDocSimple (OutputList &ol, const Definition *container) const =0
virtual void writeTagFile (TextStream &, bool useQualifiedName) const =0
virtual void writeLink (OutputList &ol, const ClassDef *cd, const NamespaceDef *nd, const FileDef *fd, const GroupDef *gd, bool onlyText=FALSE) const =0
virtual void setAnonymousUsed () const =0
virtual void setFromAnonymousScope (bool b) const =0
Additional Inherited Members
Detailed Description
Definition at line 295 of file memberdef.h.
Member Function Documentation
addExample() [1/2]
virtual bool MemberDefMutable::addExample (const QCString & anchor, const QCString & name, const QCString & file) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by generateClassMemberLink(), and getLinkInScope().
addExample() [2/2]
virtual bool MemberDefMutable::addExample (const QCString & anchor, const QCString & name, const QCString & file) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
addListReference() [1/2]
virtual void MemberDefMutable::addListReference (Definition * d) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by MemberList::addListReferences().
addListReference() [2/2]
virtual void MemberDefMutable::addListReference (Definition * d) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
cacheTypedefVal() [1/2]
virtual void MemberDefMutable::cacheTypedefVal (const ClassDef * val, const QCString & templSpec, const QCString & resolvedType) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by SymbolResolver::Private::newResolveTypedef().
cacheTypedefVal() [2/2]
virtual void MemberDefMutable::cacheTypedefVal (const ClassDef * val, const QCString & templSpec, const QCString & resolvedType) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
copyArgumentNames() [1/2]
virtual void MemberDefMutable::copyArgumentNames (const MemberDef * bmd) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by inheritDocumentation().
copyArgumentNames() [2/2]
virtual void MemberDefMutable::copyArgumentNames (const MemberDef * bmd) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
enableCallerGraph() [1/2]
virtual void MemberDefMutable::enableCallerGraph (bool e) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by addLocalObjCMethod(), addMemberDocs(), addMemberSpecialization(), addOverloaded(), combineDeclarationAndDefinition(), findEnums(), and findMember().
enableCallerGraph() [2/2]
virtual void MemberDefMutable::enableCallerGraph (bool e) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
enableCallGraph() [1/2]
virtual void MemberDefMutable::enableCallGraph (bool e) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by addLocalObjCMethod(), addMemberDocs(), addMemberSpecialization(), addOverloaded(), combineDeclarationAndDefinition(), findEnums(), and findMember().
enableCallGraph() [2/2]
virtual void MemberDefMutable::enableCallGraph (bool e) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
enableReferencedByRelation() [1/2]
virtual void MemberDefMutable::enableReferencedByRelation (bool e) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by addLocalObjCMethod(), addMemberDocs(), addMemberSpecialization(), addOverloaded(), combineDeclarationAndDefinition(), findEnums(), and findMember().
enableReferencedByRelation() [2/2]
virtual void MemberDefMutable::enableReferencedByRelation (bool e) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
enableReferencesRelation() [1/2]
virtual void MemberDefMutable::enableReferencesRelation (bool e) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by addLocalObjCMethod(), addMemberDocs(), addMemberSpecialization(), addOverloaded(), combineDeclarationAndDefinition(), findEnums(), and findMember().
enableReferencesRelation() [2/2]
virtual void MemberDefMutable::enableReferencesRelation (bool e) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
findSectionsInDocumentation() [1/2]
virtual void MemberDefMutable::findSectionsInDocumentation () [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by MemberList::findSectionsInDocumentation().
findSectionsInDocumentation() [2/2]
virtual void MemberDefMutable::findSectionsInDocumentation () [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
incrementFlowKeyWordCount() [1/2]
virtual void MemberDefMutable::incrementFlowKeyWordCount () [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by incrementFlowKeyWordCount().
incrementFlowKeyWordCount() [2/2]
virtual void MemberDefMutable::incrementFlowKeyWordCount () [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
insertEnumField() [1/2]
virtual void MemberDefMutable::insertEnumField (const MemberDef * md) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by addEnumValuesToEnums().
insertEnumField() [2/2]
virtual void MemberDefMutable::insertEnumField (const MemberDef * md) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
insertReimplementedBy() [1/2]
virtual void MemberDefMutable::insertReimplementedBy (const MemberDef * md) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by computeMemberRelations(), and MemberDefImpl::insertReimplementedBy().
insertReimplementedBy() [2/2]
virtual void MemberDefMutable::insertReimplementedBy (const MemberDef * md) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
invalidateCachedArgumentTypes() [1/2]
virtual void MemberDefMutable::invalidateCachedArgumentTypes () [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by flushUnresolvedRelations().
invalidateCachedArgumentTypes() [2/2]
virtual void MemberDefMutable::invalidateCachedArgumentTypes () [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
invalidateTypedefValCache() [1/2]
virtual void MemberDefMutable::invalidateTypedefValCache () [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by flushCachedTemplateRelations().
invalidateTypedefValCache() [2/2]
virtual void MemberDefMutable::invalidateTypedefValCache () [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
makeForeign() [1/2]
virtual void MemberDefMutable::makeForeign () [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by transferRelatedFunctionDocumentation().
makeForeign() [2/2]
virtual void MemberDefMutable::makeForeign () [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
makeImplementationDetail() [1/2]
virtual void MemberDefMutable::makeImplementationDetail () [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by addLocalObjCMethod().
makeImplementationDetail() [2/2]
virtual void MemberDefMutable::makeImplementationDetail () [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
makeRelated() [1/2]
virtual void MemberDefMutable::makeRelated () [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by addEnumValuesToEnums(), and transferRelatedFunctionDocumentation().
makeRelated() [2/2]
virtual void MemberDefMutable::makeRelated () [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
mergeMemberSpecifiers() [1/2]
virtual void MemberDefMutable::mergeMemberSpecifiers (uint64 s) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by addMemberDocs(), and combineDeclarationAndDefinition().
mergeMemberSpecifiers() [2/2]
virtual void MemberDefMutable::mergeMemberSpecifiers (uint64 s) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
moveArgumentList() [1/2]
virtual void MemberDefMutable::moveArgumentList (std::unique_ptr< ArgumentList > al) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by addMemberFunction(), buildDefineList(), combineDeclarationAndDefinition(), and MemberDefImpl::createTemplateInstanceMember().
moveArgumentList() [2/2]
virtual void MemberDefMutable::moveArgumentList (std::unique_ptr< ArgumentList > al) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
moveDeclArgumentList() [1/2]
virtual void MemberDefMutable::moveDeclArgumentList (std::unique_ptr< ArgumentList > al) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by combineDeclarationAndDefinition().
moveDeclArgumentList() [2/2]
virtual void MemberDefMutable::moveDeclArgumentList (std::unique_ptr< ArgumentList > al) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
resolveUnnamedParameters() [1/2]
virtual void MemberDefMutable::resolveUnnamedParameters (const MemberDef * md) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by combineDeclarationAndDefinition().
resolveUnnamedParameters() [2/2]
virtual void MemberDefMutable::resolveUnnamedParameters (const MemberDef * md) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setAccessorType() [1/2]
virtual void MemberDefMutable::setAccessorType (ClassDef * cd, const QCString & t) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by processTagLessClasses().
setAccessorType() [2/2]
virtual void MemberDefMutable::setAccessorType (ClassDef * cd, const QCString & t) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setAnchor() [1/2]
virtual void MemberDefMutable::setAnchor () [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by addEnumValuesToEnums(), and MemberList::setAnchors().
setAnchor() [2/2]
virtual void MemberDefMutable::setAnchor () [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setAnonymousEnumType() [1/2]
virtual void MemberDefMutable::setAnonymousEnumType (const MemberDef * md) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by MemberList::setAnonymousEnumType().
setAnonymousEnumType() [2/2]
virtual void MemberDefMutable::setAnonymousEnumType (const MemberDef * md) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setAnonymousUsed() [1/2]
virtual void MemberDefMutable::setAnonymousUsed () const [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by MemberDefImpl::writeDeclaration().
setAnonymousUsed() [2/2]
virtual void MemberDefMutable::setAnonymousUsed () const [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setArgsString() [1/2]
virtual void MemberDefMutable::setArgsString (const QCString & as) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setArgsString() [2/2]
virtual void MemberDefMutable::setArgsString (const QCString & as) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setBitfields() [1/2]
virtual void MemberDefMutable::setBitfields (const QCString & s) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by createTagLessInstance().
setBitfields() [2/2]
virtual void MemberDefMutable::setBitfields (const QCString & s) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setBriefDescription() [1/2]
virtual void MemberDefMutable::setBriefDescription (const QCString & b, const QCString & briefFile, int briefLine) [pure virtual]
Sets the brief description of this definition to b. A dot is added to the sentence if not available.
Implements DefinitionMutable.
Implemented in MemberDefImpl, MemberDefImpl, DefinitionMixin< MemberDefMutable >, and DefinitionMixin< MemberDefMutable >.
Referenced by addEnumDocs(), addEnumValuesToEnums(), addInstance(), addLocalObjCMethod(), addMemberDocs(), addMemberSpecialization(), addOverloaded(), combineDeclarationAndDefinition(), createTagLessInstance(), MemberGroup::distributeMemberGroupDocumentation(), findDefineDocumentation(), findEnums(), findMember(), and inheritDocumentation().
setBriefDescription() [2/2]
virtual void MemberDefMutable::setBriefDescription (const QCString & b, const QCString & briefFile, int briefLine) [pure virtual]
Sets the brief description of this definition to b. A dot is added to the sentence if not available.
Implements DefinitionMutable.
Implemented in MemberDefImpl, MemberDefImpl, DefinitionMixin< MemberDefMutable >, and DefinitionMixin< MemberDefMutable >.
setCategory() [1/2]
virtual void MemberDefMutable::setCategory (ClassDef *) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by ClassDefImpl::mergeCategory().
setCategory() [2/2]
virtual void MemberDefMutable::setCategory (ClassDef *) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setCategoryRelation() [1/2]
virtual void MemberDefMutable::setCategoryRelation (const MemberDef *) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by ClassDefImpl::mergeCategory().
setCategoryRelation() [2/2]
virtual void MemberDefMutable::setCategoryRelation (const MemberDef *) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setDeclFile() [1/2]
virtual void MemberDefMutable::setDeclFile (const QCString & df, int line, int column) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by addVariableToFile().
setDeclFile() [2/2]
virtual void MemberDefMutable::setDeclFile (const QCString & df, int line, int column) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setDefinition() [1/2]
virtual void MemberDefMutable::setDefinition (const QCString & d) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by addLocalObjCMethod(), addMemberDocs(), addMemberSpecialization(), addOverloaded(), buildDefineList(), MemberDefImpl::createTemplateInstanceMember(), findEnums(), and findMember().
setDefinition() [2/2]
virtual void MemberDefMutable::setDefinition (const QCString & d) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setDefinitionTemplateParameterLists() [1/2]
virtual void MemberDefMutable::setDefinitionTemplateParameterLists (const ArgumentLists & lists) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by addMemberFunction(), and findMember().
setDefinitionTemplateParameterLists() [2/2]
virtual void MemberDefMutable::setDefinitionTemplateParameterLists (const ArgumentLists & lists) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setDocsForDefinition() [1/2]
virtual void MemberDefMutable::setDocsForDefinition (bool b) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by addEnumDocs(), addLocalObjCMethod(), addMemberDocs(), addMemberSpecialization(), addOverloaded(), combineDeclarationAndDefinition(), findDefineDocumentation(), findEnums(), findMember(), and inheritDocumentation().
setDocsForDefinition() [2/2]
virtual void MemberDefMutable::setDocsForDefinition (bool b) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setDocumentation() [1/2]
virtual void MemberDefMutable::setDocumentation (const QCString & d, const QCString & docFile, int docLine, bool stripWhiteSpace = TRUE) [pure virtual]
Sets the documentation of this definition to d.
Implements DefinitionMutable.
Implemented in MemberDefImpl, MemberDefImpl, DefinitionMixin< MemberDefMutable >, and DefinitionMixin< MemberDefMutable >.
Referenced by addEnumDocs(), addEnumValuesToEnums(), addInstance(), addLocalObjCMethod(), addMemberDocs(), addMemberSpecialization(), addOverloaded(), combineDeclarationAndDefinition(), createTagLessInstance(), MemberGroup::distributeMemberGroupDocumentation(), findDefineDocumentation(), findEnums(), findMember(), and inheritDocumentation().
setDocumentation() [2/2]
virtual void MemberDefMutable::setDocumentation (const QCString & d, const QCString & docFile, int docLine, bool stripWhiteSpace = TRUE) [pure virtual]
Sets the documentation of this definition to d.
Implements DefinitionMutable.
Implemented in MemberDefImpl, MemberDefImpl, DefinitionMixin< MemberDefMutable >, and DefinitionMixin< MemberDefMutable >.
setDocumentedEnumValues() [1/2]
virtual void MemberDefMutable::setDocumentedEnumValues (bool value) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by findDEV().
setDocumentedEnumValues() [2/2]
virtual void MemberDefMutable::setDocumentedEnumValues (bool value) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setEnumBaseType() [1/2]
virtual void MemberDefMutable::setEnumBaseType (const QCString & type) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by findEnums().
setEnumBaseType() [2/2]
virtual void MemberDefMutable::setEnumBaseType (const QCString & type) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setEnumClassScope() [1/2]
virtual void MemberDefMutable::setEnumClassScope (const ClassDef * cd) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by addEnumValuesToEnums().
setEnumClassScope() [2/2]
virtual void MemberDefMutable::setEnumClassScope (const ClassDef * cd) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setEnumScope() [1/2]
virtual void MemberDefMutable::setEnumScope (const MemberDef * md, bool livesInsideEnum = FALSE) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by addEnumValuesToEnums().
setEnumScope() [2/2]
virtual void MemberDefMutable::setEnumScope (const MemberDef * md, bool livesInsideEnum = FALSE) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setExplicitExternal() [1/2]
virtual void MemberDefMutable::setExplicitExternal (bool b, const QCString & df, int line, int column) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by addEnumValuesToEnums(), and addVariableToFile().
setExplicitExternal() [2/2]
virtual void MemberDefMutable::setExplicitExternal (bool b, const QCString & df, int line, int column) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setFileDef() [1/2]
virtual void MemberDefMutable::setFileDef (const FileDef * fd) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by addEnumValuesToEnums(), buildDefineList(), findDefineDocumentation(), findEnums(), and NamespaceDefImpl::insertMember().
setFileDef() [2/2]
virtual void MemberDefMutable::setFileDef (const FileDef * fd) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setFromAnonymousMember() [1/2]
virtual void MemberDefMutable::setFromAnonymousMember (MemberDef * m) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setFromAnonymousMember() [2/2]
virtual void MemberDefMutable::setFromAnonymousMember (MemberDef * m) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setFromAnonymousScope() [1/2]
virtual void MemberDefMutable::setFromAnonymousScope (bool b) const [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by MemberList::writePlainDeclarations().
setFromAnonymousScope() [2/2]
virtual void MemberDefMutable::setFromAnonymousScope (bool b) const [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setGroupAlias() [1/2]
virtual void MemberDefMutable::setGroupAlias (const MemberDef * md) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by GroupDefImpl::insertMember().
setGroupAlias() [2/2]
virtual void MemberDefMutable::setGroupAlias (const MemberDef * md) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setGroupDef() [1/2]
virtual void MemberDefMutable::setGroupDef (const GroupDef * gd, Grouping::GroupPri_t pri, const QCString & fileName, int startLine, bool hasDocs, MemberDef * member = 0) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by addMemberToGroups(), combineDeclarationAndDefinition(), MemberGroup::insertMember(), and ClassDefImpl::setGroupDefForAllMembers().
setGroupDef() [2/2]
virtual void MemberDefMutable::setGroupDef (const GroupDef * gd, Grouping::GroupPri_t pri, const QCString & fileName, int startLine, bool hasDocs, MemberDef * member = 0) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setHidden() [1/2]
virtual void MemberDefMutable::setHidden (bool b) [pure virtual]
Implements DefinitionMutable.
Implemented in DefinitionMixin< MemberDefMutable >, MemberDefImpl, DefinitionMixin< MemberDefMutable >, and MemberDefImpl.
Referenced by findMember().
setHidden() [2/2]
virtual void MemberDefMutable::setHidden (bool b) [pure virtual]
Implements DefinitionMutable.
Implemented in DefinitionMixin< MemberDefMutable >, MemberDefImpl, DefinitionMixin< MemberDefMutable >, and MemberDefImpl.
setInbodyDocumentation() [1/2]
virtual void MemberDefMutable::setInbodyDocumentation (const QCString & d, const QCString & docFile, int docLine) [pure virtual]
Set the documentation that was found inside the body of an item. If there was already some documentation set, the new documentation will be appended.
Implements DefinitionMutable.
Implemented in MemberDefImpl, MemberDefImpl, DefinitionMixin< MemberDefMutable >, and DefinitionMixin< MemberDefMutable >.
Referenced by addEnumDocs(), addLocalObjCMethod(), addMemberDocs(), addMemberSpecialization(), addOverloaded(), combineDeclarationAndDefinition(), createTagLessInstance(), MemberGroup::distributeMemberGroupDocumentation(), findDefineDocumentation(), findEnums(), findMember(), and inheritDocumentation().
setInbodyDocumentation() [2/2]
virtual void MemberDefMutable::setInbodyDocumentation (const QCString & d, const QCString & docFile, int docLine) [pure virtual]
Set the documentation that was found inside the body of an item. If there was already some documentation set, the new documentation will be appended.
Implements DefinitionMutable.
Implemented in MemberDefImpl, MemberDefImpl, DefinitionMixin< MemberDefMutable >, and DefinitionMixin< MemberDefMutable >.
setInheritsDocsFrom() [1/2]
virtual void MemberDefMutable::setInheritsDocsFrom (const MemberDef * md) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by inheritDocumentation().
setInheritsDocsFrom() [2/2]
virtual void MemberDefMutable::setInheritsDocsFrom (const MemberDef * md) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setInitializer() [1/2]
virtual void MemberDefMutable::setInitializer (const QCString & i) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by addEnumValuesToEnums(), addMemberDocs(), buildDefineList(), createTagLessInstance(), and findMember().
setInitializer() [2/2]
virtual void MemberDefMutable::setInitializer (const QCString & i) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setMaxInitLines() [1/2]
virtual void MemberDefMutable::setMaxInitLines (int lines) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by addEnumValuesToEnums(), addMemberDocs(), createTagLessInstance(), and findDefineDocumentation().
setMaxInitLines() [2/2]
virtual void MemberDefMutable::setMaxInitLines (int lines) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setMemberClass() [1/2]
virtual void MemberDefMutable::setMemberClass (const ClassDef * cd) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by addEnumValuesToEnums(), addLocalObjCMethod(), addMemberSpecialization(), ClassDefImpl::addMembersToTemplateInstance(), addOverloaded(), createTagLessInstance(), findEnums(), findMember(), and findUsingDeclImports().
setMemberClass() [2/2]
virtual void MemberDefMutable::setMemberClass (const ClassDef * cd) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setMemberDeclaration() [1/2]
virtual void MemberDefMutable::setMemberDeclaration (MemberDef * md) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by combineDeclarationAndDefinition().
setMemberDeclaration() [2/2]
virtual void MemberDefMutable::setMemberDeclaration (MemberDef * md) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setMemberDefinition() [1/2]
virtual void MemberDefMutable::setMemberDefinition (MemberDef * md) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by combineDeclarationAndDefinition().
setMemberDefinition() [2/2]
virtual void MemberDefMutable::setMemberDefinition (MemberDef * md) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setMemberGroupId() [1/2]
virtual void MemberDefMutable::setMemberGroupId (int id) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by addEnumDocs(), addEnumValuesToEnums(), addLocalObjCMethod(), addMemberDocs(), addMemberSpecialization(), addOverloaded(), createTagLessInstance(), findDefineDocumentation(), findEnums(), and findMember().
setMemberGroupId() [2/2]
virtual void MemberDefMutable::setMemberGroupId (int id) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setMemberSpecifiers() [1/2]
virtual void MemberDefMutable::setMemberSpecifiers (uint64 s) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by addInstance(), addLocalObjCMethod(), addMemberSpecialization(), addOverloaded(), VhdlDocGen::correctMemberProperties(), createTagLessInstance(), findEnums(), and findMember().
setMemberSpecifiers() [2/2]
virtual void MemberDefMutable::setMemberSpecifiers (uint64 s) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setMemberType() [1/2]
virtual void MemberDefMutable::setMemberType (MemberType t) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by ClassDefImpl::reclassifyMember().
setMemberType() [2/2]
virtual void MemberDefMutable::setMemberType (MemberType t) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setNamespace() [1/2]
virtual void MemberDefMutable::setNamespace (const NamespaceDef * nd) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by addEnumValuesToEnums(), findEnums(), and NamespaceDefImpl::insertMember().
setNamespace() [2/2]
virtual void MemberDefMutable::setNamespace (const NamespaceDef * nd) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setProtection() [1/2]
virtual void MemberDefMutable::setProtection (Protection p) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by addVariableToClass().
setProtection() [2/2]
virtual void MemberDefMutable::setProtection (Protection p) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setPrototype() [1/2]
virtual void MemberDefMutable::setPrototype (bool p, const QCString & df, int line, int column) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by addLocalObjCMethod(), addMemberSpecialization(), addOverloaded(), and findMember().
setPrototype() [2/2]
virtual void MemberDefMutable::setPrototype (bool p, const QCString & df, int line, int column) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setReadAccessor() [1/2]
virtual void MemberDefMutable::setReadAccessor (const QCString & r) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setReadAccessor() [2/2]
virtual void MemberDefMutable::setReadAccessor (const QCString & r) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setReimplements() [1/2]
virtual void MemberDefMutable::setReimplements (const MemberDef * md) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by computeMemberRelations().
setReimplements() [2/2]
virtual void MemberDefMutable::setReimplements (const MemberDef * md) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setRelatedAlso() [1/2]
virtual void MemberDefMutable::setRelatedAlso (ClassDef * cd) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by findMember(), and transferRelatedFunctionDocumentation().
setRelatedAlso() [2/2]
virtual void MemberDefMutable::setRelatedAlso (ClassDef * cd) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setRequiresClause() [1/2]
virtual void MemberDefMutable::setRequiresClause (const QCString & req) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by addMemberDocs(), and createTagLessInstance().
setRequiresClause() [2/2]
virtual void MemberDefMutable::setRequiresClause (const QCString & req) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setSectionList() [1/2]
virtual void MemberDefMutable::setSectionList (const Definition * container, const MemberList * sl) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by ClassDefImpl::addMemberToList(), FileDefImpl::addMemberToList(), and NamespaceDefImpl::addMemberToList().
setSectionList() [2/2]
virtual void MemberDefMutable::setSectionList (const Definition * container, const MemberList * sl) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setTagInfo() [1/2]
virtual void MemberDefMutable::setTagInfo (const TagInfo * i) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by addEnumValuesToEnums(), addInstance(), addLocalObjCMethod(), addMemberSpecialization(), addOverloaded(), addVariableToClass(), addVariableToFile(), findDefineDocumentation(), findEnums(), and findMember().
setTagInfo() [2/2]
virtual void MemberDefMutable::setTagInfo (const TagInfo * i) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setTemplateMaster() [1/2]
virtual void MemberDefMutable::setTemplateMaster (const MemberDef * mt) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setTemplateMaster() [2/2]
virtual void MemberDefMutable::setTemplateMaster (const MemberDef * mt) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setTemplateSpecialization() [1/2]
virtual void MemberDefMutable::setTemplateSpecialization (bool b) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by addMemberSpecialization().
setTemplateSpecialization() [2/2]
virtual void MemberDefMutable::setTemplateSpecialization (bool b) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setType() [1/2]
virtual void MemberDefMutable::setType (const QCString & t) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by VhdlDocGen::correctMemberProperties().
setType() [2/2]
virtual void MemberDefMutable::setType (const QCString & t) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setTypeConstraints() [1/2]
virtual void MemberDefMutable::setTypeConstraints (const ArgumentList & al) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by addMemberSpecialization(), and addOverloaded().
setTypeConstraints() [2/2]
virtual void MemberDefMutable::setTypeConstraints (const ArgumentList & al) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setWriteAccessor() [1/2]
virtual void MemberDefMutable::setWriteAccessor (const QCString & w) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
setWriteAccessor() [2/2]
virtual void MemberDefMutable::setWriteAccessor (const QCString & w) [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
writeDocumentation() [1/2]
virtual void MemberDefMutable::writeDocumentation (const MemberList * ml, int memCount, int memTotal, OutputList & ol, const QCString & scopeName, const Definition * container, bool inGroup, bool showEnumValues = FALSE, bool showInline = FALSE) const [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by MemberList::writeDocumentation(), and MemberList::writeDocumentationPage().
writeDocumentation() [2/2]
virtual void MemberDefMutable::writeDocumentation (const MemberList * ml, int memCount, int memTotal, OutputList & ol, const QCString & scopeName, const Definition * container, bool inGroup, bool showEnumValues = FALSE, bool showInline = FALSE) const [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
writeLink() [1/2]
virtual void MemberDefMutable::writeLink (OutputList & ol, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd, bool onlyText = FALSE) const [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by MemberDefImpl::writeDeclaration(), and MemberDefImpl::writeEnumDeclaration().
writeLink() [2/2]
virtual void MemberDefMutable::writeLink (OutputList & ol, const ClassDef * cd, const NamespaceDef * nd, const FileDef * fd, const GroupDef * gd, bool onlyText = FALSE) const [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
writeMemberDocSimple() [1/2]
virtual void MemberDefMutable::writeMemberDocSimple (OutputList & ol, const Definition * container) const [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by MemberList::writeSimpleDocumentation().
writeMemberDocSimple() [2/2]
virtual void MemberDefMutable::writeMemberDocSimple (OutputList & ol, const Definition * container) const [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
writeTagFile() [1/2]
virtual void MemberDefMutable::writeTagFile (TextStream & , bool useQualifiedName) const [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
Referenced by MemberList::writeTagFile().
writeTagFile() [2/2]
virtual void MemberDefMutable::writeTagFile (TextStream & , bool useQualifiedName) const [pure virtual]
Implemented in MemberDefImpl, and MemberDefImpl.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/memberdef.h
doxygen/src/memberdef.h