FilterTexLabel Class Reference
The implementation of the `texlabel` filter.
Static Public Member Functions
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &)
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &)
Detailed Description
The implementation of the `texlabel` filter.
Definition at line 886 of file template.cpp.
Member Function Documentation
apply() [1/2]
static TemplateVariant FilterTexLabel::apply (const TemplateVariant & v, const TemplateVariant &) [inline], [static]
Definition at line 889 of file template.cpp.
    {
      if (v.isValid() && (v.isString()))
      {
        return TemplateVariant(latexEscapeLabelName(v.toString()),TRUE);
      }
      else
      {
        return v;
      }
    }
References TemplateVariant::isString(), TemplateVariant::isValid(), latexEscapeLabelName(), TemplateVariant::toString(), and TRUE.
apply() [2/2]
static TemplateVariant FilterTexLabel::apply (const TemplateVariant & v, const TemplateVariant &) [inline], [static]
Definition at line 889 of file template.cpp.
    {
      if (v.isValid() && (v.isString()))
      {
        return TemplateVariant(latexEscapeLabelName(v.toString()),TRUE);
      }
      else
      {
        return v;
      }
    }
References TemplateVariant::isString(), TemplateVariant::isValid(), latexEscapeLabelName(), TemplateVariant::toString(), and TRUE.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp