TranslatorAfrikaans Class Reference
#include <translator_za.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
Additional Inherited Members
Detailed Description
Definition at line 29 of file translator_za.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorAfrikaans::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 66 of file translator_za.h.
    {
      return "0x436 Afrikaans";
    }
getLanguageString() [2/2]
virtual QCString TranslatorAfrikaans::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 66 of file translator_za.h.
    {
      return "0x436 Afrikaans";
    }
idLanguage() [1/2]
virtual QCString TranslatorAfrikaans::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 41 of file translator_za.h.
    { return "afrikaans"; }
idLanguage() [2/2]
virtual QCString TranslatorAfrikaans::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 41 of file translator_za.h.
    { return "afrikaans"; }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorAfrikaans::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The Afrikaans LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 58 of file translator_za.h.
    {
      return "\\usepackage[afrikaans]{babel}\n";
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorAfrikaans::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The Afrikaans LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 58 of file translator_za.h.
    {
      return "\\usepackage[afrikaans]{babel}\n";
    }
trAll() [1/2]
virtual QCString TranslatorAfrikaans::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1384 of file translator_za.h.
    {
      return "Alle Lede";
    }
trAll() [2/2]
virtual QCString TranslatorAfrikaans::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1384 of file translator_za.h.
    {
      return "Alle Lede";
    }
trAttention() [1/2]
virtual QCString TranslatorAfrikaans::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 947 of file translator_za.h.
    {
      return "Aandag";
    }
trAttention() [2/2]
virtual QCString TranslatorAfrikaans::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 947 of file translator_za.h.
    {
      return "Aandag";
    }
trAuthor() [1/2]
virtual QCString TranslatorAfrikaans::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1255 of file translator_za.h.
    {
      QCString result((first_capital ? "Outeur" : "outeur"));
      if (!singular) result+="s";
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorAfrikaans::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1255 of file translator_za.h.
    {
      QCString result((first_capital ? "Outeur" : "outeur"));
      if (!singular) result+="s";
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorAfrikaans::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1113 of file translator_za.h.
    {
      return "Bug";
    }
trBug() [2/2]
virtual QCString TranslatorAfrikaans::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1113 of file translator_za.h.
    {
      return "Bug";
    }
trBugList() [1/2]
virtual QCString TranslatorAfrikaans::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1118 of file translator_za.h.
    {
      return "Bug Lys";
    }
trBugList() [2/2]
virtual QCString TranslatorAfrikaans::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1118 of file translator_za.h.
    {
      return "Bug Lys";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorAfrikaans::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1505 of file translator_za.h.
    {
      return "Hier is die roep skema vir die funksie:";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorAfrikaans::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1505 of file translator_za.h.
    {
      return "Hier is die roep skema vir die funksie:";
    }
trCallGraph() [1/2]
virtual QCString TranslatorAfrikaans::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1389 of file translator_za.h.
    {
      return "'n gebruiks diagram vir hierdie funksie:";
    }
trCallGraph() [2/2]
virtual QCString TranslatorAfrikaans::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1389 of file translator_za.h.
    {
      return "'n gebruiks diagram vir hierdie funksie:";
    }
trClass() [1/2]
virtual QCString TranslatorAfrikaans::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1176 of file translator_za.h.
    {
      QCString result((first_capital ? "Klas" : "klas"));
      if (!singular) result+="se";
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorAfrikaans::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1176 of file translator_za.h.
    {
      QCString result((first_capital ? "Klas" : "klas"));
      if (!singular) result+="se";
      return result;
    }
trClassDiagram() [1/2]
virtual QCString TranslatorAfrikaans::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 500 of file translator_za.h.
    {
      return "Afleidings diagram vir "+clName+":";
    }
trClassDiagram() [2/2]
virtual QCString TranslatorAfrikaans::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 500 of file translator_za.h.
    {
      return "Afleidings diagram vir "+clName+":";
    }
trClassDocumentation() [1/2]
virtual QCString TranslatorAfrikaans::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 375 of file translator_za.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Strukture Dokumentasie";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Klas Dokumentasie";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorAfrikaans::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 375 of file translator_za.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Strukture Dokumentasie";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Klas Dokumentasie";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorAfrikaans::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1076 of file translator_za.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Strukture";
      }
      else
      {
        return "Klasse";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorAfrikaans::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1076 of file translator_za.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Strukture";
      }
      else
      {
        return "Klasse";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorAfrikaans::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 161 of file translator_za.h.
    { return "Klas Hierargie"; }
trClassHierarchy() [2/2]
virtual QCString TranslatorAfrikaans::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 161 of file translator_za.h.
    { return "Klas Hierargie"; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorAfrikaans::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 220 of file translator_za.h.
    {
      return "Hierdie afgeleide lys word rofweg gesorteer: ";
    }
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorAfrikaans::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 220 of file translator_za.h.
    {
      return "Hierdie afgeleide lys word rofweg gesorteer: ";
    }
trCode() [1/2]
virtual QCString TranslatorAfrikaans::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 847 of file translator_za.h.
    {
      return "kode";
    }
trCode() [2/2]
virtual QCString TranslatorAfrikaans::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 847 of file translator_za.h.
    {
      return "kode";
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorAfrikaans::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 802 of file translator_za.h.
    {
      return "Samewerkings diagram vir "+clName+":";
    }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorAfrikaans::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 802 of file translator_za.h.
    {
      return "Samewerkings diagram vir "+clName+":";
    }
trCompoundIndex() [1/2]
virtual QCString TranslatorAfrikaans::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 348 of file translator_za.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Strukture Indeks";
      }
      else
      {
        return "Klas Indeks";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorAfrikaans::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 348 of file translator_za.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Strukture Indeks";
      }
      else
      {
        return "Klas Indeks";
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorAfrikaans::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1560 of file translator_za.h.
    { return "Data Tipe Indeks"; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorAfrikaans::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1560 of file translator_za.h.
    { return "Data Tipe Indeks"; }
trCompoundList() [1/2]
virtual QCString TranslatorAfrikaans::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 165 of file translator_za.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Strukture";
      }
      else
      {
        return "Klas Lys";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorAfrikaans::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 165 of file translator_za.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Strukture";
      }
      else
      {
        return "Klas Lys";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorAfrikaans::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 235 of file translator_za.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " Data strukture met kort beskrywings:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Klasse met kort beskrywings:";
      }
      else
      {
        return "Klasse, structs, "
               "unions en intervlakke met kort beskrywings:";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorAfrikaans::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 235 of file translator_za.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return " Data strukture met kort beskrywings:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Klasse met kort beskrywings:";
      }
      else
      {
        return "Klasse, structs, "
               "unions en intervlakke met kort beskrywings:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorAfrikaans::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1533 of file translator_za.h.
    { return "Hier is die data tipes met kort beskrywings:"; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorAfrikaans::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1533 of file translator_za.h.
    { return "Hier is die data tipes met kort beskrywings:"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorAfrikaans::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1525 of file translator_za.h.
    { return "Data Tipes Lys"; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorAfrikaans::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1525 of file translator_za.h.
    { return "Data Tipes Lys"; }
trCompoundMembers() [1/2]
virtual QCString TranslatorAfrikaans::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 182 of file translator_za.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Velde";
      }
      else
      {
        return "Klas Lede";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorAfrikaans::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 182 of file translator_za.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Velde";
      }
      else
      {
        return "Klas Lede";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorAfrikaans::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 254 of file translator_za.h.
    {
      QCString result="'n Lys van alle ";
      if (!extractAll)
      {
        result+="gedokumenteerde ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="struct en union velde";
      }
      else
      {
        result+="klas lede";
      }
      result+=" met skakels na ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="die struct/union dokumentasie vir elke veld:";
        }
        else
        {
          result+="die klas dokumentasie vir elke lid:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="die structures/unions waaraan hulle behoort:";
        }
        else
        {
          result+="die klasse waaraan hulle behoort:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorAfrikaans::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 254 of file translator_za.h.
    {
      QCString result="'n Lys van alle ";
      if (!extractAll)
      {
        result+="gedokumenteerde ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="struct en union velde";
      }
      else
      {
        result+="klas lede";
      }
      result+=" met skakels na ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="die struct/union dokumentasie vir elke veld:";
        }
        else
        {
          result+="die klas dokumentasie vir elke lid:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="die structures/unions waaraan hulle behoort:";
        }
        else
        {
          result+="die klasse waaraan hulle behoort:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorAfrikaans::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1537 of file translator_za.h.
    {
      QCString result="Hier is 'n lys van alle ";
      if (!extractAll)
      {
        result+="gedokumenteerde ";
      }
      result+="data tipe lede";
      result+=" met skakels na ";
      if (!extractAll)
      {
         result+="die data strukture dokumentasie vir elke lid";
      }
      else
      {
         result+="die data tipes waaraan hulle behoort:";
      }
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorAfrikaans::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1537 of file translator_za.h.
    {
      QCString result="Hier is 'n lys van alle ";
      if (!extractAll)
      {
        result+="gedokumenteerde ";
      }
      result+="data tipe lede";
      result+=" met skakels na ";
      if (!extractAll)
      {
         result+="die data strukture dokumentasie vir elke lid";
      }
      else
      {
         result+="die data tipes waaraan hulle behoort:";
      }
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorAfrikaans::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1529 of file translator_za.h.
    { return "Data Velde"; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorAfrikaans::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1529 of file translator_za.h.
    { return "Data Velde"; }
trCompoundReference() [1/2]
virtual QCString TranslatorAfrikaans::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 575 of file translator_za.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" klas"; break;
        case ClassDef::Struct: result+=" Struct"; break;
        case ClassDef::Union: result+=" Union"; break;
        case ClassDef::Interface: result+=" Intervlak"; break;
        case ClassDef::Protocol: result+=" Protocol"; break;
        case ClassDef::Category: result+=" Kategorie"; break;
        case ClassDef::Exception: result+=" Exception"; break;
        default: break;
      }
      if (isTemplate) result+=" Template";
      result+=" Verwysing";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorAfrikaans::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 575 of file translator_za.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" klas"; break;
        case ClassDef::Struct: result+=" Struct"; break;
        case ClassDef::Union: result+=" Union"; break;
        case ClassDef::Interface: result+=" Intervlak"; break;
        case ClassDef::Protocol: result+=" Protocol"; break;
        case ClassDef::Category: result+=" Kategorie"; break;
        case ClassDef::Exception: result+=" Exception"; break;
        default: break;
      }
      if (isTemplate) result+=" Template";
      result+=" Verwysing";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorAfrikaans::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1601 of file translator_za.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" Module"; break;
        case ClassDef::Struct: result+=" Tipe"; break;
        case ClassDef::Union: result+=" Unie"; break;
        case ClassDef::Interface: result+=" Interflak"; break;
        case ClassDef::Protocol: result+=" Protokol"; break;
        case ClassDef::Category: result+=" Kategorie"; break;
        case ClassDef::Exception: result+=" Eksepsie"; break;
        default: break;
      }
      if (isTemplate) result+=" Template";
      result+=" Bron";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorAfrikaans::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1601 of file translator_za.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" Module"; break;
        case ClassDef::Struct: result+=" Tipe"; break;
        case ClassDef::Union: result+=" Unie"; break;
        case ClassDef::Interface: result+=" Interflak"; break;
        case ClassDef::Protocol: result+=" Protokol"; break;
        case ClassDef::Category: result+=" Kategorie"; break;
        case ClassDef::Exception: result+=" Eksepsie"; break;
        default: break;
      }
      if (isTemplate) result+=" Template";
      result+=" Bron";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorAfrikaans::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 476 of file translator_za.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Strukture";
      }
      else
      {
        return "Klasse";
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorAfrikaans::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 476 of file translator_za.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Strukture";
      }
      else
      {
        return "Klasse";
      }
    }
References Config_getBool.
trConstructorDocumentation() [1/2]
virtual QCString TranslatorAfrikaans::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 812 of file translator_za.h.
    {
      return "Konstruktor & Destruktor Dokumentasie";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorAfrikaans::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 812 of file translator_za.h.
    {
      return "Konstruktor & Destruktor Dokumentasie";
    }
trDataTypes() [1/2]
virtual QCString TranslatorAfrikaans::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1584 of file translator_za.h.
    { return "Data Tipes"; }
trDataTypes() [2/2]
virtual QCString TranslatorAfrikaans::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1584 of file translator_za.h.
    { return "Data Tipes"; }
trDate() [1/2]
virtual QCString TranslatorAfrikaans::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 514 of file translator_za.h.
    { return "Datum"; }
trDate() [2/2]
virtual QCString TranslatorAfrikaans::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 514 of file translator_za.h.
    { return "Datum"; }
trDayOfWeek() [1/2]
virtual QCString TranslatorAfrikaans::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1716 of file translator_za.h.
    {
      static const char *days_short[] = { "Ma.", "Di.", "Wo.", "Do.", "Vr.", "Sa.", "So." };
      static const char *days_full[] = { "Maandag", "Dinsdag", "Woensdag", "Donderdag", "Vrydag", "Saterdag", "Sondag" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayOfWeek() [2/2]
virtual QCString TranslatorAfrikaans::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1716 of file translator_za.h.
    {
      static const char *days_short[] = { "Ma.", "Di.", "Wo.", "Do.", "Vr.", "Sa.", "So." };
      static const char *days_full[] = { "Maandag", "Dinsdag", "Woensdag", "Donderdag", "Vrydag", "Saterdag", "Sondag" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod() [1/2]
virtual QCString TranslatorAfrikaans::trDayPeriod (int period) [inline], [virtual]
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1732 of file translator_za.h.
    {
      static const char *dayPeriod[] = { "vm.", "nm." };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorAfrikaans::trDayPeriod (int period) [inline], [virtual]
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1732 of file translator_za.h.
    {
      static const char *dayPeriod[] = { "vm.", "nm." };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorAfrikaans::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 779 of file translator_za.h.
    {
      return "Gedefinier by lyn @0 van ler @1.";
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorAfrikaans::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 779 of file translator_za.h.
    {
      return "Gedefinier by lyn @0 van ler @1.";
    }
trDefinedIn() [1/2]
virtual QCString TranslatorAfrikaans::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 149 of file translator_za.h.
    { return "gedefinier in"; }
trDefinedIn() [2/2]
virtual QCString TranslatorAfrikaans::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 149 of file translator_za.h.
    { return "gedefinier in"; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorAfrikaans::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 783 of file translator_za.h.
    {
      return "Definisie in ler @0.";
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorAfrikaans::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 783 of file translator_za.h.
    {
      return "Definisie in ler @0.";
    }
trDefineDocumentation() [1/2]
virtual QCString TranslatorAfrikaans::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 446 of file translator_za.h.
    { return "Define Documentation"; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorAfrikaans::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 446 of file translator_za.h.
    { return "Define Documentation"; }
trDefines() [1/2]
virtual QCString TranslatorAfrikaans::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 410 of file translator_za.h.
    { return "Definiesies"; }
trDefines() [2/2]
virtual QCString TranslatorAfrikaans::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 410 of file translator_za.h.
    { return "Definiesies"; }
trDefineValue() [1/2]
virtual QCString TranslatorAfrikaans::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1103 of file translator_za.h.
    {
      return "Waarde:";
    }
trDefineValue() [2/2]
virtual QCString TranslatorAfrikaans::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1103 of file translator_za.h.
    {
      return "Waarde:";
    }
trDeprecated() [1/2]
virtual QCString TranslatorAfrikaans::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 792 of file translator_za.h.
    {
      return "Verouderd";
    }
trDeprecated() [2/2]
virtual QCString TranslatorAfrikaans::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 792 of file translator_za.h.
    {
      return "Verouderd";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorAfrikaans::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1312 of file translator_za.h.
    {
      return "Verouderde Lys";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorAfrikaans::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1312 of file translator_za.h.
    {
      return "Verouderde Lys";
    }
trDetailedDescription() [1/2]
virtual QCString TranslatorAfrikaans::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 82 of file translator_za.h.
    { return "Detail Beskrywing"; }
trDetailedDescription() [2/2]
virtual QCString TranslatorAfrikaans::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 82 of file translator_za.h.
    { return "Detail Beskrywing"; }
trDir() [1/2]
virtual QCString TranslatorAfrikaans::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1479 of file translator_za.h.
    {
      QCString result((first_capital ? "Director" : "director"));
      if (singular) result+="y"; else result+="ies";
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorAfrikaans::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1479 of file translator_za.h.
    {
      QCString result((first_capital ? "Director" : "director"));
      if (singular) result+="y"; else result+="ies";
      return result;
    }
trDirDocumentation() [1/2]
virtual QCString TranslatorAfrikaans::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1461 of file translator_za.h.
    { return "Directory Documentasie"; }
trDirDocumentation() [2/2]
virtual QCString TranslatorAfrikaans::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1461 of file translator_za.h.
    { return "Directory Documentasie"; }
trDirectories() [1/2]
virtual QCString TranslatorAfrikaans::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1467 of file translator_za.h.
    { return "Directories"; }
trDirectories() [2/2]
virtual QCString TranslatorAfrikaans::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1467 of file translator_za.h.
    { return "Directories"; }
trDirIndex() [1/2]
virtual QCString TranslatorAfrikaans::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1455 of file translator_za.h.
    { return "Directory Hirargie"; }
trDirIndex() [2/2]
virtual QCString TranslatorAfrikaans::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1455 of file translator_za.h.
    { return "Directory Hirargie"; }
trDirReference() [1/2]
virtual QCString TranslatorAfrikaans::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1473 of file translator_za.h.
    { QCString result=dirName; result+=" Directory Verwysing"; return result; }
trDirReference() [2/2]
virtual QCString TranslatorAfrikaans::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1473 of file translator_za.h.
    { QCString result=dirName; result+=" Directory Verwysing"; return result; }
trDocumentation() [1/2]
virtual QCString TranslatorAfrikaans::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 330 of file translator_za.h.
    { return "Dokumentasie"; }
trDocumentation() [2/2]
virtual QCString TranslatorAfrikaans::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 330 of file translator_za.h.
    { return "Dokumentasie"; }
trEnumerations() [1/2]
virtual QCString TranslatorAfrikaans::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 422 of file translator_za.h.
    { return "Enumerations"; }
trEnumerations() [2/2]
virtual QCString TranslatorAfrikaans::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 422 of file translator_za.h.
    { return "Enumerations"; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorAfrikaans::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 458 of file translator_za.h.
    { return "Enumeration Type Dokumentasie"; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorAfrikaans::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 458 of file translator_za.h.
    { return "Enumeration Type Dokumentasie"; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorAfrikaans::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1513 of file translator_za.h.
    { return "Enumerator Dokumentasie"; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorAfrikaans::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1513 of file translator_za.h.
    { return "Enumerator Dokumentasie"; }
trEnumerationValues() [1/2]
virtual QCString TranslatorAfrikaans::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 440 of file translator_za.h.
    { return "Enumeration waardes"; }
trEnumerationValues() [2/2]
virtual QCString TranslatorAfrikaans::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 440 of file translator_za.h.
    { return "Enumeration waardes"; }
trEnumName() [1/2]
virtual QCString TranslatorAfrikaans::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 141 of file translator_za.h.
    { return "enum naam"; }
trEnumName() [2/2]
virtual QCString TranslatorAfrikaans::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 141 of file translator_za.h.
    { return "enum naam"; }
trEnumValue() [1/2]
virtual QCString TranslatorAfrikaans::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 145 of file translator_za.h.
    { return "enum waarde"; }
trEnumValue() [2/2]
virtual QCString TranslatorAfrikaans::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 145 of file translator_za.h.
    { return "enum waarde"; }
trEventDocumentation() [1/2]
virtual QCString TranslatorAfrikaans::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1329 of file translator_za.h.
    {
      return "Event Dokumentasie";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorAfrikaans::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1329 of file translator_za.h.
    {
      return "Event Dokumentasie";
    }
trEvents() [1/2]
virtual QCString TranslatorAfrikaans::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1324 of file translator_za.h.
    {
      return "Events";
    }
trEvents() [2/2]
virtual QCString TranslatorAfrikaans::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1324 of file translator_za.h.
    {
      return "Events";
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorAfrikaans::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 400 of file translator_za.h.
    { return "Voorbeeld Dokumentasie"; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorAfrikaans::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 400 of file translator_za.h.
    { return "Voorbeeld Dokumentasie"; }
trExamples() [1/2]
virtual QCString TranslatorAfrikaans::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 212 of file translator_za.h.
    { return "Voorbeelde"; }
trExamples() [2/2]
virtual QCString TranslatorAfrikaans::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 212 of file translator_za.h.
    { return "Voorbeelde"; }
trExamplesDescription() [1/2]
virtual QCString TranslatorAfrikaans::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 318 of file translator_za.h.
    { return "'n Lys van alle voorbeelde:"; }
trExamplesDescription() [2/2]
virtual QCString TranslatorAfrikaans::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 318 of file translator_za.h.
    { return "'n Lys van alle voorbeelde:"; }
trExceptions() [1/2]
virtual QCString TranslatorAfrikaans::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 530 of file translator_za.h.
    { return "Exceptions"; }
trExceptions() [2/2]
virtual QCString TranslatorAfrikaans::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 530 of file translator_za.h.
    { return "Exceptions"; }
trFile() [1/2]
virtual QCString TranslatorAfrikaans::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1187 of file translator_za.h.
    {
      QCString result((first_capital ? "Ler" : "ler"));
      if (!singular) result+="s";
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorAfrikaans::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1187 of file translator_za.h.
    {
      QCString result((first_capital ? "Ler" : "ler"));
      if (!singular) result+="s";
      return result;
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorAfrikaans::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 394 of file translator_za.h.
    { return "Ler Dokumentasie"; }
trFileDocumentation() [2/2]
virtual QCString TranslatorAfrikaans::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 394 of file translator_za.h.
    { return "Ler Dokumentasie"; }
trFileIndex() [1/2]
virtual QCString TranslatorAfrikaans::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 363 of file translator_za.h.
    { return "Ler Indeks"; }
trFileIndex() [2/2]
virtual QCString TranslatorAfrikaans::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 363 of file translator_za.h.
    { return "Ler Indeks"; }
trFileList() [1/2]
virtual QCString TranslatorAfrikaans::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 178 of file translator_za.h.
    { return "Ler Lys"; }
trFileList() [2/2]
virtual QCString TranslatorAfrikaans::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 178 of file translator_za.h.
    { return "Ler Lys"; }
trFileListDescription() [1/2]
virtual QCString TranslatorAfrikaans::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 226 of file translator_za.h.
    {
      QCString result="Hier is 'n lys van alle ";
      if (!extractAll) result+="gedokumenteerde ";
      result+="lers met kort beskrywings:";
      return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorAfrikaans::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 226 of file translator_za.h.
    {
      QCString result="Hier is 'n lys van alle ";
      if (!extractAll) result+="gedokumenteerde ";
      result+="lers met kort beskrywings:";
      return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorAfrikaans::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 195 of file translator_za.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globals";
      }
      else
      {
        return "Ler Lede";
      }
    }
References Config_getBool.
trFileMembers() [2/2]
virtual QCString TranslatorAfrikaans::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 195 of file translator_za.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globals";
      }
      else
      {
        return "Ler Lede";
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
virtual QCString TranslatorAfrikaans::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 296 of file translator_za.h.
    {
      QCString result="'n Lys van alle ";
      if (!extractAll) result+="gedokumenteerde ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funksies, veranderlikes, defines, enums, en typedefs";
      }
      else
      {
        result+="ler lede";
      }
      result+=" met skakels na ";
      if (extractAll)
        result+="die lers waaraan hulle behoort:";
      else
        result+="die dokumentasie:";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorAfrikaans::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 296 of file translator_za.h.
    {
      QCString result="'n Lys van alle ";
      if (!extractAll) result+="gedokumenteerde ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funksies, veranderlikes, defines, enums, en typedefs";
      }
      else
      {
        result+="ler lede";
      }
      result+=" met skakels na ";
      if (extractAll)
        result+="die lers waaraan hulle behoort:";
      else
        result+="die dokumentasie:";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorAfrikaans::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 597 of file translator_za.h.
    {
      QCString result=fileName;
      result+=" Ler Verwysing";
      return result;
    }
trFileReference() [2/2]
virtual QCString TranslatorAfrikaans::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 597 of file translator_za.h.
    {
      QCString result=fileName;
      result+=" Ler Verwysing";
      return result;
    }
trFriends() [1/2]
virtual QCString TranslatorAfrikaans::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 557 of file translator_za.h.
    { return "Friends"; }
trFriends() [2/2]
virtual QCString TranslatorAfrikaans::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 557 of file translator_za.h.
    { return "Friends"; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorAfrikaans::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 464 of file translator_za.h.
    { return "Funksie Dokumentasie"; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorAfrikaans::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 464 of file translator_za.h.
    { return "Funksie Dokumentasie"; }
trFunctions() [1/2]
virtual QCString TranslatorAfrikaans::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 428 of file translator_za.h.
    { return "Funksies"; }
trFunctions() [2/2]
virtual QCString TranslatorAfrikaans::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 428 of file translator_za.h.
    { return "Funksies"; }
trGeneratedAt() [1/2]
virtual QCString TranslatorAfrikaans::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 491 of file translator_za.h.
    {
      QCString result="Gegenereer op "+date;
      if (!projName.isEmpty()) result+=" vir "+projName;
      result+=" deur";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorAfrikaans::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 491 of file translator_za.h.
    {
      QCString result="Gegenereer op "+date;
      if (!projName.isEmpty()) result+=" vir "+projName;
      result+=" deur";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorAfrikaans::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 133 of file translator_za.h.
    { QCString result="Automaties gegenereer deur Doxygen";
      if (!s.isEmpty()) result+=" vir "+s;
      result+=" van die bron kode af.";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorAfrikaans::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 133 of file translator_za.h.
    { QCString result="Automaties gegenereer deur Doxygen";
      if (!s.isEmpty()) result+=" vir "+s;
      result+=" van die bron kode af.";
      return result;
    }
References s.
trGeneratedBy() [1/2]
virtual QCString TranslatorAfrikaans::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 534 of file translator_za.h.
    { return "Gegenereer deur"; }
trGeneratedBy() [2/2]
virtual QCString TranslatorAfrikaans::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 534 of file translator_za.h.
    { return "Gegenereer deur"; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorAfrikaans::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 735 of file translator_za.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Die dokumentasie vir hierdie ";
      switch(compType)
      {
        case ClassDef::Class: result+="klas"; break;
        case ClassDef::Struct: result+="struct"; break;
        case ClassDef::Union: result+="union"; break;
        case ClassDef::Interface: result+="intervlak"; break;
        case ClassDef::Protocol: result+="protokol"; break;
        case ClassDef::Category: result+="kategorie"; break;
        case ClassDef::Exception: result+="eksepsie"; break;
        default: break;
      }
      result+=" is gegenereer vanaf die volgende ler";
      if (single) result+=":"; else result+="s:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorAfrikaans::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 735 of file translator_za.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Die dokumentasie vir hierdie ";
      switch(compType)
      {
        case ClassDef::Class: result+="klas"; break;
        case ClassDef::Struct: result+="struct"; break;
        case ClassDef::Union: result+="union"; break;
        case ClassDef::Interface: result+="intervlak"; break;
        case ClassDef::Protocol: result+="protokol"; break;
        case ClassDef::Category: result+="kategorie"; break;
        case ClassDef::Exception: result+="eksepsie"; break;
        default: break;
      }
      result+=" is gegenereer vanaf die volgende ler";
      if (single) result+=":"; else result+="s:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorAfrikaans::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1669 of file translator_za.h.
    {
      // single is true implies a single file
      QCString result="The documentation for this ";
      switch(compType)
      {
        case ClassDef::Class: result+="module"; break;
        case ClassDef::Struct: result+="tipe"; break;
        case ClassDef::Union: result+="unie"; break;
        case ClassDef::Interface: result+="Interflak"; break;
        case ClassDef::Protocol: result+="protokcol"; break;
        case ClassDef::Category: result+="kategorie"; break;
        case ClassDef::Exception: result+="eksepsie"; break;
        default: break;
      }
      result+=" is gegenereer vanaf die foldende leer";
      if (single) result+=":"; else result+="s:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorAfrikaans::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1669 of file translator_za.h.
    {
      // single is true implies a single file
      QCString result="The documentation for this ";
      switch(compType)
      {
        case ClassDef::Class: result+="module"; break;
        case ClassDef::Struct: result+="tipe"; break;
        case ClassDef::Union: result+="unie"; break;
        case ClassDef::Interface: result+="Interflak"; break;
        case ClassDef::Protocol: result+="protokcol"; break;
        case ClassDef::Category: result+="kategorie"; break;
        case ClassDef::Exception: result+="eksepsie"; break;
        default: break;
      }
      result+=" is gegenereer vanaf die foldende leer";
      if (single) result+=":"; else result+="s:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorAfrikaans::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1242 of file translator_za.h.
    {
      QCString result((first_capital ? "Global" : "global"));
      if (!singular) result+="s";
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorAfrikaans::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1242 of file translator_za.h.
    {
      QCString result((first_capital ? "Global" : "global"));
      if (!singular) result+="s";
      return result;
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorAfrikaans::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 822 of file translator_za.h.
    {
      return "Skakel na die dokumentasie van hierdie ler.";
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorAfrikaans::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 822 of file translator_za.h.
    {
      return "Skakel na die dokumentasie van hierdie ler.";
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorAfrikaans::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 855 of file translator_za.h.
    {
      return "Skakel na die grafiese klasse hierargie";
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorAfrikaans::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 855 of file translator_za.h.
    {
      return "Skakel na die grafiese klasse hierargie";
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorAfrikaans::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 817 of file translator_za.h.
    {
      return "Skakel na die bron kode van hierdie ler.";
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorAfrikaans::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 817 of file translator_za.h.
    {
      return "Skakel na die bron kode van hierdie ler.";
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorAfrikaans::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 859 of file translator_za.h.
    {
      return "Skakel na die teks klasse hierargie";
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorAfrikaans::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 859 of file translator_za.h.
    {
      return "Skakel na die teks klasse hierargie";
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorAfrikaans::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 851 of file translator_za.h.
    {
      return "Grafiese Klasse Hierargie";
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorAfrikaans::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 851 of file translator_za.h.
    {
      return "Grafiese Klasse Hierargie";
    }
trGroup() [1/2]
virtual QCString TranslatorAfrikaans::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1209 of file translator_za.h.
    {
      QCString result((first_capital ? "Groep" : "groep"));
      if (!singular) result+="e";
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorAfrikaans::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1209 of file translator_za.h.
    {
      QCString result((first_capital ? "Groep" : "groep"));
      if (!singular) result+="e";
      return result;
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorAfrikaans::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 342 of file translator_za.h.
    { return "Hierargiese Indeks"; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorAfrikaans::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 342 of file translator_za.h.
    { return "Hierargiese Indeks"; }
trImplementedFromList() [1/2]
virtual QCString TranslatorAfrikaans::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1280 of file translator_za.h.
    {
      return "Implimenteer "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorAfrikaans::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1280 of file translator_za.h.
    {
      return "Implimenteer "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorAfrikaans::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1288 of file translator_za.h.
    {
      return "Geimplimenteer in "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorAfrikaans::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1288 of file translator_za.h.
    {
      return "Geimplimenteer in "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorAfrikaans::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 951 of file translator_za.h.
    {
      return "Hierdie diagram verduidelik watter lers direk of"
             "indirek hierdie ler insluit:";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorAfrikaans::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 951 of file translator_za.h.
    {
      return "Hierdie diagram verduidelik watter lers direk of"
             "indirek hierdie ler insluit:";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorAfrikaans::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 807 of file translator_za.h.
    {
      return "Insluitings afhanklikheid diagram vir "+fName+":";
    }
trInclDepGraph() [2/2]
virtual QCString TranslatorAfrikaans::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 807 of file translator_za.h.
    {
      return "Insluitings afhanklikheid diagram vir "+fName+":";
    }
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorAfrikaans::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 127 of file translator_za.h.
    { return ", insluitend alle afgeleide lede."; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorAfrikaans::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 127 of file translator_za.h.
    { return ", insluitend alle afgeleide lede."; }
trInheritedByList() [1/2]
virtual QCString TranslatorAfrikaans::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 669 of file translator_za.h.
    {
      return "Afgelei van"+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorAfrikaans::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 669 of file translator_za.h.
    {
      return "Afgelei van"+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [1/2]
virtual QCString TranslatorAfrikaans::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 661 of file translator_za.h.
    {
      return "Afgelei van"+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorAfrikaans::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 661 of file translator_za.h.
    {
      return "Afgelei van"+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorAfrikaans::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 842 of file translator_za.h.
    {
      return "Oorspronklike waarde:";
    }
trInitialValue() [2/2]
virtual QCString TranslatorAfrikaans::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 842 of file translator_za.h.
    {
      return "Oorspronklike waarde:";
    }
trInvariant() [1/2]
virtual QCString TranslatorAfrikaans::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 837 of file translator_za.h.
    {
      return "Invariant";
    }
trInvariant() [2/2]
virtual QCString TranslatorAfrikaans::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 837 of file translator_za.h.
    {
      return "Invariant";
    }
trISOLang() [1/2]
virtual QCString TranslatorAfrikaans::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 62 of file translator_za.h.
    {
      return "af";
    }
trISOLang() [2/2]
virtual QCString TranslatorAfrikaans::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 62 of file translator_za.h.
    {
      return "af";
    }
trLegend() [1/2]
virtual QCString TranslatorAfrikaans::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1036 of file translator_za.h.
    {
      return "beskrywing";
    }
trLegend() [2/2]
virtual QCString TranslatorAfrikaans::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1036 of file translator_za.h.
    {
      return "beskrywing";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorAfrikaans::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 973 of file translator_za.h.
    {
      return
        "Hierdie bladsy beskryf die diagram konvensies wat gebruik word "
        "deur doxygen.<p>\n"
        "in hierdie voorbeeld:\n"
        "\\code\n"
        "/*! Onsigbare klas weens afkorting */\n"
        "class Invisible { };\n\n"
        "/*! Afgekorte klas, afgeleide verwantskap word versteek */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Ongedokumenteerde Klas, geen doxygen kommentaar nie */\n"
        "class Undocumented{ };\n\n"
        "/*! 'n Klas wat afgelei is met 'n publieke verwantskap */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! 'n template klas */\n"
        "template<class T> class Templ { };\n\n"
        "/*! 'n Klas wat afgelei is met 'n beskermde verwantskap */\n"
        "class ProtectedBase { };\n\n"
        "/*! 'n Klas wat afgelei is met 'n private verwantskap */\n"
        "class PrivateBase { };\n\n"
        "/*! 'n Klas wat gebrui word deur die Afgeleide klas */\n"
        "class GebruikMy { };\n\n"
        "/*! 'n Super klas wat afgelei word van 'n aantal basis klasse */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Ongedokumenteer,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "As die \\c MAX_DOT_GRAPH_HEIGHT merker in die konfigurasie ler "
        "aan 240 gelyk gestel is, word die volgende diagram geproduseer:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "Die reghoeke in die diagram het die volgende betekenis:\n"
        "<ul>\n"
        "<li>%'n Soliede swart reghoek verteenwoordig die klas waarvoor "
        "die diagram gegenereer is.\n"
        "<li>%'n Reghoek met 'n swart omlyning verteenwoordig 'n gedokumenteerde klas.\n"
        "<li>%'n Reghoek met 'n grys omlyning verteenwoordig 'n ongedokumenteerde klas.\n"
        "<li>%'n Reghoek met 'n rooi omlyning verteenwoordig 'n gedokumenteerde klas waarvoor"
        "alle verwante klasse (afgeleide of gebruik) nie getoon word nie. %'n Diagram word "
        "op hierie manier afgekort as dit nie in die gespesifiseerde raam pas nie.\n"
        "</ul>\n"
        "Die pyltjies het die volgende betekenis:\n"
        "<ul>\n"
        "<li>%'n Donker blou pyltjie verteenwoordig 'n publieke afgeleide "
        "verwantskap tussen twee klasse.\n"
        "<li>%'n Donker groen pyltjie word gebruik vir 'n beskermde verwantskap.\n"
        "<li>%'n Donker rooi pyltjie verteenwoordig private verwantskappe.\n"
        "<li>%'n Pers pyltjie word gebruik as 'n klas gebruik of bevat word "
        "deur 'n ander klas. Die pyltjie word gemerk met die veranderlike(s) waar deur "
        "die verwysde klass verkrygbaar is.\n"
        "<li>%'n Geel stippel pyl verteenwoordig die verwantslap tussen 'n template instansie en "
        "die template waarvan die klas vervaardig is. Die pyltjie word gemerk met die "
        "template parameters van die instansie.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorAfrikaans::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 973 of file translator_za.h.
    {
      return
        "Hierdie bladsy beskryf die diagram konvensies wat gebruik word "
        "deur doxygen.<p>\n"
        "in hierdie voorbeeld:\n"
        "\\code\n"
        "/*! Onsigbare klas weens afkorting */\n"
        "class Invisible { };\n\n"
        "/*! Afgekorte klas, afgeleide verwantskap word versteek */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Ongedokumenteerde Klas, geen doxygen kommentaar nie */\n"
        "class Undocumented{ };\n\n"
        "/*! 'n Klas wat afgelei is met 'n publieke verwantskap */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! 'n template klas */\n"
        "template<class T> class Templ { };\n\n"
        "/*! 'n Klas wat afgelei is met 'n beskermde verwantskap */\n"
        "class ProtectedBase { };\n\n"
        "/*! 'n Klas wat afgelei is met 'n private verwantskap */\n"
        "class PrivateBase { };\n\n"
        "/*! 'n Klas wat gebrui word deur die Afgeleide klas */\n"
        "class GebruikMy { };\n\n"
        "/*! 'n Super klas wat afgelei word van 'n aantal basis klasse */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Ongedokumenteer,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "As die \\c MAX_DOT_GRAPH_HEIGHT merker in die konfigurasie ler "
        "aan 240 gelyk gestel is, word die volgende diagram geproduseer:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "Die reghoeke in die diagram het die volgende betekenis:\n"
        "<ul>\n"
        "<li>%'n Soliede swart reghoek verteenwoordig die klas waarvoor "
        "die diagram gegenereer is.\n"
        "<li>%'n Reghoek met 'n swart omlyning verteenwoordig 'n gedokumenteerde klas.\n"
        "<li>%'n Reghoek met 'n grys omlyning verteenwoordig 'n ongedokumenteerde klas.\n"
        "<li>%'n Reghoek met 'n rooi omlyning verteenwoordig 'n gedokumenteerde klas waarvoor"
        "alle verwante klasse (afgeleide of gebruik) nie getoon word nie. %'n Diagram word "
        "op hierie manier afgekort as dit nie in die gespesifiseerde raam pas nie.\n"
        "</ul>\n"
        "Die pyltjies het die volgende betekenis:\n"
        "<ul>\n"
        "<li>%'n Donker blou pyltjie verteenwoordig 'n publieke afgeleide "
        "verwantskap tussen twee klasse.\n"
        "<li>%'n Donker groen pyltjie word gebruik vir 'n beskermde verwantskap.\n"
        "<li>%'n Donker rooi pyltjie verteenwoordig private verwantskappe.\n"
        "<li>%'n Pers pyltjie word gebruik as 'n klas gebruik of bevat word "
        "deur 'n ander klas. Die pyltjie word gemerk met die veranderlike(s) waar deur "
        "die verwysde klass verkrygbaar is.\n"
        "<li>%'n Geel stippel pyl verteenwoordig die verwantslap tussen 'n template instansie en "
        "die template waarvan die klas vervaardig is. Die pyltjie word gemerk met die "
        "template parameters van die instansie.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorAfrikaans::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 966 of file translator_za.h.
    {
      return "Diagram beskrywing";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorAfrikaans::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 966 of file translator_za.h.
    {
      return "Diagram beskrywing";
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorAfrikaans::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 115 of file translator_za.h.
    { return "Lys van alle lede"; }
trListOfAllMembers() [2/2]
virtual QCString TranslatorAfrikaans::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 115 of file translator_za.h.
    { return "Lys van alle lede"; }
trMainPage() [1/2]
virtual QCString TranslatorAfrikaans::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 766 of file translator_za.h.
    { return "Hoof Bladsy"; }
trMainPage() [2/2]
virtual QCString TranslatorAfrikaans::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 766 of file translator_za.h.
    { return "Hoof Bladsy"; }
trMember() [1/2]
virtual QCString TranslatorAfrikaans::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1231 of file translator_za.h.
    {
      QCString result((first_capital ? "Lid" : "lid"));
      if (!singular) result = (first_capital ? "Lede" : "lede");
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorAfrikaans::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1231 of file translator_za.h.
    {
      QCString result((first_capital ? "Lid" : "lid"));
      if (!singular) result = (first_capital ? "Lede" : "lede");
      return result;
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorAfrikaans::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 98 of file translator_za.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Veld Dokumentasie";
      }
      else
      {
        return "Lede Data Dokumentasie";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorAfrikaans::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 98 of file translator_za.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Veld Dokumentasie";
      }
      else
      {
        return "Lede Data Dokumentasie";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorAfrikaans::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 90 of file translator_za.h.
    { return "Lede Enumerasie Dokumentasie"; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorAfrikaans::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 90 of file translator_za.h.
    { return "Lede Enumerasie Dokumentasie"; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorAfrikaans::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 94 of file translator_za.h.
    { return "Lede Funksie Dokumentasie"; }
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorAfrikaans::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 94 of file translator_za.h.
    { return "Lede Funksie Dokumentasie"; }
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorAfrikaans::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1521 of file translator_za.h.
    { return "Lede Funksie/Subroetine Dokumentasie"; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorAfrikaans::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1521 of file translator_za.h.
    { return "Lede Funksie/Subroetine Dokumentasie"; }
trMemberList() [1/2]
virtual QCString TranslatorAfrikaans::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 119 of file translator_za.h.
    { return "Lede Lys"; }
trMemberList() [2/2]
virtual QCString TranslatorAfrikaans::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 119 of file translator_za.h.
    { return "Lede Lys"; }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorAfrikaans::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 86 of file translator_za.h.
    { return "Lede Typedef Dokumentasie"; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorAfrikaans::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 86 of file translator_za.h.
    { return "Lede Typedef Dokumentasie"; }
trModule() [1/2]
virtual QCString TranslatorAfrikaans::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1660 of file translator_za.h.
    {
      QCString result((first_capital ? "Module" : "module"));
      if (!singular) result+="s";
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorAfrikaans::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1660 of file translator_za.h.
    {
      QCString result((first_capital ? "Module" : "module"));
      if (!singular) result+="s";
      return result;
    }
trModuleDocumentation() [1/2]
virtual QCString TranslatorAfrikaans::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 369 of file translator_za.h.
    { return "Module Dokumentasie"; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorAfrikaans::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 369 of file translator_za.h.
    { return "Module Dokumentasie"; }
trModuleIndex() [1/2]
virtual QCString TranslatorAfrikaans::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 336 of file translator_za.h.
    { return "Module Indeks"; }
trModuleIndex() [2/2]
virtual QCString TranslatorAfrikaans::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 336 of file translator_za.h.
    { return "Module Indeks"; }
trModuleReference() [1/2]
virtual QCString TranslatorAfrikaans::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1622 of file translator_za.h.
    {
      QCString result=namespaceName;
      result+=" Module Bron";
      return result;
    }
trModuleReference() [2/2]
virtual QCString TranslatorAfrikaans::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1622 of file translator_za.h.
    {
      QCString result=namespaceName;
      result+=" Module Bron";
      return result;
    }
trModules() [1/2]
virtual QCString TranslatorAfrikaans::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 157 of file translator_za.h.
    { return "Modules"; }
trModules() [2/2]
virtual QCString TranslatorAfrikaans::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 157 of file translator_za.h.
    { return "Modules"; }
trModulesDescription() [1/2]
virtual QCString TranslatorAfrikaans::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 326 of file translator_za.h.
    { return "'n Lys van alle modules:"; }
trModulesDescription() [2/2]
virtual QCString TranslatorAfrikaans::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 326 of file translator_za.h.
    { return "'n Lys van alle modules:"; }
trModulesIndex() [1/2]
virtual QCString TranslatorAfrikaans::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1653 of file translator_za.h.
    { return "Modules Indeks"; }
trModulesIndex() [2/2]
virtual QCString TranslatorAfrikaans::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1653 of file translator_za.h.
    { return "Modules Indeks"; }
trModulesList() [1/2]
virtual QCString TranslatorAfrikaans::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1588 of file translator_za.h.
    { return "Modules Lys"; }
trModulesList() [2/2]
virtual QCString TranslatorAfrikaans::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1588 of file translator_za.h.
    { return "Modules Lys"; }
trModulesListDescription() [1/2]
virtual QCString TranslatorAfrikaans::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1592 of file translator_za.h.
    {
      QCString result="Hier is 'n lys van alle ";
      if (!extractAll) result+="gedokumenteerde ";
      result+="modules met kort beskrywings:";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorAfrikaans::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1592 of file translator_za.h.
    {
      QCString result="Hier is 'n lys van alle ";
      if (!extractAll) result+="gedokumenteerde ";
      result+="modules met kort beskrywings:";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorAfrikaans::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1634 of file translator_za.h.
    {
      QCString result="Hier is 'n lys van alle ";
      if (!extractAll) result+="gedokumenteerde ";
      result+="module lede met skakels na ";
      if (extractAll)
      {
        result+="die module dokumentasie vir elke lid:";
      }
      else
      {
        result+="die modules waaraan hulle behoort:";
      }
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorAfrikaans::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1634 of file translator_za.h.
    {
      QCString result="Hier is 'n lys van alle ";
      if (!extractAll) result+="gedokumenteerde ";
      result+="module lede met skakels na ";
      if (extractAll)
      {
        result+="die module dokumentasie vir elke lid:";
      }
      else
      {
        result+="die modules waaraan hulle behoort:";
      }
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorAfrikaans::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1630 of file translator_za.h.
    { return "Module Lede"; }
trModulesMembers() [2/2]
virtual QCString TranslatorAfrikaans::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1630 of file translator_za.h.
    { return "Module Lede"; }
trMonth() [1/2]
virtual QCString TranslatorAfrikaans::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1724 of file translator_za.h.
    {
      static const char *months_short[] = { "Jan.", "Feb.", "Mrt.", "Apr.", "Mei", "Jun.", "Jul.", "Aug.", "Sep.", "Okt.", "Nov.", "Des." };
      static const char *months_full[] = { "Januarie", "Februarie", "Maart", "April", "Mei", "Junie", "Julie", "Augustus", "September", "Oktober", "November", "Desember" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMonth() [2/2]
virtual QCString TranslatorAfrikaans::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1724 of file translator_za.h.
    {
      static const char *months_short[] = { "Jan.", "Feb.", "Mrt.", "Apr.", "Mei", "Jun.", "Jul.", "Aug.", "Sep.", "Okt.", "Nov.", "Des." };
      static const char *months_full[] = { "Januarie", "Februarie", "Maart", "April", "Mei", "Junie", "Julie", "Augustus", "September", "Oktober", "November", "Desember" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore() [1/2]
virtual QCString TranslatorAfrikaans::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 111 of file translator_za.h.
    { return "Meer detail..."; }
trMore() [2/2]
virtual QCString TranslatorAfrikaans::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 111 of file translator_za.h.
    { return "Meer detail..."; }
trNamespace() [1/2]
virtual QCString TranslatorAfrikaans::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1198 of file translator_za.h.
    {
      QCString result((first_capital ? "Namespace" : "namespace"));
      if (!singular) result+="s";
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorAfrikaans::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1198 of file translator_za.h.
    {
      QCString result((first_capital ? "Namespace" : "namespace"));
      if (!singular) result+="s";
      return result;
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorAfrikaans::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 715 of file translator_za.h.
    { return "Namespace Dokumentasie"; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorAfrikaans::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 715 of file translator_za.h.
    { return "Namespace Dokumentasie"; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorAfrikaans::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 709 of file translator_za.h.
    { return "Namespace Indeks"; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorAfrikaans::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 709 of file translator_za.h.
    { return "Namespace Indeks"; }
trNamespaceList() [1/2]
virtual QCString TranslatorAfrikaans::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 542 of file translator_za.h.
    { return "Namespace Lys"; }
trNamespaceList() [2/2]
virtual QCString TranslatorAfrikaans::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 542 of file translator_za.h.
    { return "Namespace Lys"; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorAfrikaans::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 546 of file translator_za.h.
    {
      QCString result="'n Lys van alle ";
      if (!extractAll) result+="gedokumenteerde ";
      result+="namespaces met kort beskrywings:";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorAfrikaans::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 546 of file translator_za.h.
    {
      QCString result="'n Lys van alle ";
      if (!extractAll) result+="gedokumenteerde ";
      result+="namespaces met kort beskrywings:";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorAfrikaans::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 695 of file translator_za.h.
    {
      QCString result="'n Lys van alle ";
      if (!extractAll) result+="gedokumenteerde ";
      result+="namespace lede met skakels na ";
      if (extractAll)
        result+="die namespace dokumentasie vir elke lid:";
      else
        result+="die namespaces waaraan hulle behoort:";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorAfrikaans::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 695 of file translator_za.h.
    {
      QCString result="'n Lys van alle ";
      if (!extractAll) result+="gedokumenteerde ";
      result+="namespace lede met skakels na ";
      if (extractAll)
        result+="die namespace dokumentasie vir elke lid:";
      else
        result+="die namespaces waaraan hulle behoort:";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorAfrikaans::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 691 of file translator_za.h.
    { return "Namespace Lede"; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorAfrikaans::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 691 of file translator_za.h.
    { return "Namespace Lede"; }
trNamespaceReference() [1/2]
virtual QCString TranslatorAfrikaans::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 605 of file translator_za.h.
    {
      QCString result=namespaceName;
      result+=" Namespace Verwysing";
      return result;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorAfrikaans::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 605 of file translator_za.h.
    {
      QCString result=namespaceName;
      result+=" Namespace Verwysing";
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorAfrikaans::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 725 of file translator_za.h.
    { return "Namespaces"; }
trNamespaces() [2/2]
virtual QCString TranslatorAfrikaans::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 725 of file translator_za.h.
    { return "Namespaces"; }
trNote() [1/2]
virtual QCString TranslatorAfrikaans::trNote () [inline], [virtual]
Implements Translator.
Definition at line 872 of file translator_za.h.
    {
      return "Nota";
    }
trNote() [2/2]
virtual QCString TranslatorAfrikaans::trNote () [inline], [virtual]
Implements Translator.
Definition at line 872 of file translator_za.h.
    {
      return "Nota";
    }
trOverloadText() [1/2]
virtual QCString TranslatorAfrikaans::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1493 of file translator_za.h.
    {
       return "Hierdie is 'n oorlaaide lede funksie, "
              "vertoon vir volledigheid. Dit verskil slegs van die bogegewe "
              "funksie in die argument(e) wat dit aanvaar.";
    }
trOverloadText() [2/2]
virtual QCString TranslatorAfrikaans::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1493 of file translator_za.h.
    {
       return "Hierdie is 'n oorlaaide lede funksie, "
              "vertoon vir volledigheid. Dit verskil slegs van die bogegewe "
              "funksie in die argument(e) wat dit aanvaar.";
    }
trPackage() [1/2]
virtual QCString TranslatorAfrikaans::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1088 of file translator_za.h.
    {
      return "Pakket "+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorAfrikaans::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1088 of file translator_za.h.
    {
      return "Pakket "+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorAfrikaans::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1365 of file translator_za.h.
    {
      return "Pakket Eienskappe";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorAfrikaans::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1365 of file translator_za.h.
    {
      return "Pakket Eienskappe";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorAfrikaans::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1347 of file translator_za.h.
    {
      return "Pakket Funksies";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorAfrikaans::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1347 of file translator_za.h.
    {
      return "Pakket Funksies";
    }
trPackageListDescription() [1/2]
virtual QCString TranslatorAfrikaans::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1093 of file translator_za.h.
    {
      return "Die pakkette met kort beskrywings (indien beskikbaar):";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorAfrikaans::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1093 of file translator_za.h.
    {
      return "Die pakkette met kort beskrywings (indien beskikbaar):";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorAfrikaans::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1351 of file translator_za.h.
    {
      return "Pakket Lede";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorAfrikaans::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1351 of file translator_za.h.
    {
      return "Pakket Lede";
    }
trPackages() [1/2]
virtual QCString TranslatorAfrikaans::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1098 of file translator_za.h.
    {
      return "Pakkette";
    }
trPackages() [2/2]
virtual QCString TranslatorAfrikaans::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1098 of file translator_za.h.
    {
      return "Pakkette";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorAfrikaans::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1340 of file translator_za.h.
    {
      return "Pakket Tipes";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorAfrikaans::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1340 of file translator_za.h.
    {
      return "Pakket Tipes";
    }
trPage() [1/2]
virtual QCString TranslatorAfrikaans::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1220 of file translator_za.h.
    {
      QCString result((first_capital ? "Bladsy" : "bladsy"));
      if (!singular) result+="e";
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorAfrikaans::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1220 of file translator_za.h.
    {
      QCString result((first_capital ? "Bladsy" : "bladsy"));
      if (!singular) result+="e";
      return result;
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorAfrikaans::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 772 of file translator_za.h.
    { return "p."; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorAfrikaans::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 772 of file translator_za.h.
    { return "p."; }
trPageIndex() [1/2]
virtual QCString TranslatorAfrikaans::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 863 of file translator_za.h.
    {
      return "Bladsy Indeks";
    }
trPageIndex() [2/2]
virtual QCString TranslatorAfrikaans::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 863 of file translator_za.h.
    {
      return "Bladsy Indeks";
    }
trParameters() [1/2]
virtual QCString TranslatorAfrikaans::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 526 of file translator_za.h.
    { return "Parameters"; }
trParameters() [2/2]
virtual QCString TranslatorAfrikaans::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 526 of file translator_za.h.
    { return "Parameters"; }
trPostcondition() [1/2]
virtual QCString TranslatorAfrikaans::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 832 of file translator_za.h.
    {
      return "Postkondisie";
    }
trPostcondition() [2/2]
virtual QCString TranslatorAfrikaans::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 832 of file translator_za.h.
    {
      return "Postkondisie";
    }
trPrecondition() [1/2]
virtual QCString TranslatorAfrikaans::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 827 of file translator_za.h.
    {
      return "Prekondisie";
    }
trPrecondition() [2/2]
virtual QCString TranslatorAfrikaans::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 827 of file translator_za.h.
    {
      return "Prekondisie";
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorAfrikaans::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 911 of file translator_za.h.
    {
      return "Private Attribute";
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorAfrikaans::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 911 of file translator_za.h.
    {
      return "Private Attribute";
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorAfrikaans::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 626 of file translator_za.h.
    { return "Private Lede Funksies"; }
trPrivateMembers() [2/2]
virtual QCString TranslatorAfrikaans::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 626 of file translator_za.h.
    { return "Private Lede Funksies"; }
trPrivateSlots() [1/2]
virtual QCString TranslatorAfrikaans::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 628 of file translator_za.h.
    { return "Private Slots"; }
trPrivateSlots() [2/2]
virtual QCString TranslatorAfrikaans::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 628 of file translator_za.h.
    { return "Private Slots"; }
trPrivateTypes() [1/2]
virtual QCString TranslatorAfrikaans::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 907 of file translator_za.h.
    {
      return "Private Tipes";
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorAfrikaans::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 907 of file translator_za.h.
    {
      return "Private Tipes";
    }
trProperties() [1/2]
virtual QCString TranslatorAfrikaans::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1061 of file translator_za.h.
    {
      return "Eienskappe";
    }
trProperties() [2/2]
virtual QCString TranslatorAfrikaans::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1061 of file translator_za.h.
    {
      return "Eienskappe";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorAfrikaans::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1066 of file translator_za.h.
    {
      return "Eienskap Dokumentasie";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorAfrikaans::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1066 of file translator_za.h.
    {
      return "Eienskap Dokumentasie";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorAfrikaans::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 899 of file translator_za.h.
    {
      return "Beskermde Attribute";
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorAfrikaans::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 899 of file translator_za.h.
    {
      return "Beskermde Attribute";
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorAfrikaans::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 620 of file translator_za.h.
    { return "Beskermde Lede Funksies"; }
trProtectedMembers() [2/2]
virtual QCString TranslatorAfrikaans::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 620 of file translator_za.h.
    { return "Beskermde Lede Funksies"; }
trProtectedSlots() [1/2]
virtual QCString TranslatorAfrikaans::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 622 of file translator_za.h.
    { return "Beskermde Slots"; }
trProtectedSlots() [2/2]
virtual QCString TranslatorAfrikaans::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 622 of file translator_za.h.
    { return "Beskermde Slots"; }
trProtectedTypes() [1/2]
virtual QCString TranslatorAfrikaans::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 895 of file translator_za.h.
    {
      return "Beskermde Tipes";
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorAfrikaans::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 895 of file translator_za.h.
    {
      return "Beskermde Tipes";
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorAfrikaans::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 880 of file translator_za.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Velde";
      }
      else
      {
        return "Publieke Public Attributes";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorAfrikaans::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 880 of file translator_za.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Data Velde";
      }
      else
      {
        return "Publieke Public Attributes";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorAfrikaans::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 612 of file translator_za.h.
    { return "Publieke Lede Funksies"; }
trPublicMembers() [2/2]
virtual QCString TranslatorAfrikaans::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 612 of file translator_za.h.
    { return "Publieke Lede Funksies"; }
trPublicSlots() [1/2]
virtual QCString TranslatorAfrikaans::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 614 of file translator_za.h.
    { return "Publieke Slots"; }
trPublicSlots() [2/2]
virtual QCString TranslatorAfrikaans::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 614 of file translator_za.h.
    { return "Publieke Slots"; }
trPublicTypes() [1/2]
virtual QCString TranslatorAfrikaans::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 876 of file translator_za.h.
    {
      return "Publieke Tipes";
    }
trPublicTypes() [2/2]
virtual QCString TranslatorAfrikaans::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 876 of file translator_za.h.
    {
      return "Publieke Tipes";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorAfrikaans::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 939 of file translator_za.h.
    {
      return "Verwysing van";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorAfrikaans::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 939 of file translator_za.h.
    {
      return "Verwysing van";
    }
trReferenceManual() [1/2]
virtual QCString TranslatorAfrikaans::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 404 of file translator_za.h.
    { return "Verwysings Handleiding"; }
trReferenceManual() [2/2]
virtual QCString TranslatorAfrikaans::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 404 of file translator_za.h.
    { return "Verwysings Handleiding"; }
trReferences() [1/2]
virtual QCString TranslatorAfrikaans::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1268 of file translator_za.h.
    {
      return "Verwysings";
    }
trReferences() [2/2]
virtual QCString TranslatorAfrikaans::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1268 of file translator_za.h.
    {
      return "Verwysings";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorAfrikaans::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 677 of file translator_za.h.
    {
      return "Hergeimplimenteer van "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorAfrikaans::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 677 of file translator_za.h.
    {
      return "Hergeimplimenteer van "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorAfrikaans::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 685 of file translator_za.h.
    {
      return "Hergeimplimenter in "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorAfrikaans::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 685 of file translator_za.h.
    {
      return "Hergeimplimenter in "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorAfrikaans::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 567 of file translator_za.h.
    { return "Friends En Verwante Funksie Dokumentasie"; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorAfrikaans::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 567 of file translator_za.h.
    { return "Friends En Verwante Funksie Dokumentasie"; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorAfrikaans::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 74 of file translator_za.h.
    { return "Verwante Funksies"; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorAfrikaans::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 74 of file translator_za.h.
    { return "Verwante Funksies"; }
trRelatedPages() [1/2]
virtual QCString TranslatorAfrikaans::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 208 of file translator_za.h.
    { return "Verwante Bladsye"; }
trRelatedPages() [2/2]
virtual QCString TranslatorAfrikaans::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 208 of file translator_za.h.
    { return "Verwante Bladsye"; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorAfrikaans::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 322 of file translator_za.h.
    { return "'n Lys van alle verwante dokumentasie:"; }
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorAfrikaans::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 322 of file translator_za.h.
    { return "'n Lys van alle verwante dokumentasie:"; }
trRelatedSubscript() [1/2]
virtual QCString TranslatorAfrikaans::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 78 of file translator_za.h.
    { return "(Let daarop dat hierdie nie lede funksies is nie.)"; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorAfrikaans::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 78 of file translator_za.h.
    { return "(Let daarop dat hierdie nie lede funksies is nie.)"; }
trRemarks() [1/2]
virtual QCString TranslatorAfrikaans::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 943 of file translator_za.h.
    {
      return "Opmerkings";
    }
trRemarks() [2/2]
virtual QCString TranslatorAfrikaans::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 943 of file translator_za.h.
    {
      return "Opmerkings";
    }
trReturns() [1/2]
virtual QCString TranslatorAfrikaans::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 518 of file translator_za.h.
    { return "Returns"; }
trReturns() [2/2]
virtual QCString TranslatorAfrikaans::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 518 of file translator_za.h.
    { return "Returns"; }
trReturnValues() [1/2]
virtual QCString TranslatorAfrikaans::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 761 of file translator_za.h.
    { return "Return waardes"; }
trReturnValues() [2/2]
virtual QCString TranslatorAfrikaans::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 761 of file translator_za.h.
    { return "Return waardes"; }
trRTFansicp() [1/2]
virtual QCString TranslatorAfrikaans::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1152 of file translator_za.h.
    {
      return "1252";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorAfrikaans::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1152 of file translator_za.h.
    {
      return "1252";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorAfrikaans::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1161 of file translator_za.h.
    {
      return "0";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorAfrikaans::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1161 of file translator_za.h.
    {
      return "0";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorAfrikaans::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1167 of file translator_za.h.
    {
      return "Indeks";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorAfrikaans::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1167 of file translator_za.h.
    {
      return "Indeks";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorAfrikaans::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1300 of file translator_za.h.
    {
      return "Inhoudsopgawe";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorAfrikaans::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1300 of file translator_za.h.
    {
      return "Inhoudsopgawe";
    }
trSearch() [1/2]
virtual QCString TranslatorAfrikaans::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 216 of file translator_za.h.
    { return "Soek"; }
trSearch() [2/2]
virtual QCString TranslatorAfrikaans::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 216 of file translator_za.h.
    { return "Soek"; }
trSearchMatches() [1/2]
virtual QCString TranslatorAfrikaans::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1432 of file translator_za.h.
    {
      return "Teikens:";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorAfrikaans::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1432 of file translator_za.h.
    {
      return "Teikens:";
    }
trSearchResults() [1/2]
virtual QCString TranslatorAfrikaans::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1413 of file translator_za.h.
    {
      if (numDocuments==0)
      {
        return "Geen dokumente na gelang van jou navraag nie.";
      }
      else if (numDocuments==1)
      {
        return "Die soektog het <b>1</b> dokument gevind na gelang van jou navraag.";
      }
      else
      {
        return "Die soektog het <b>$num</b> dokumente gevind na gelang van jou navraag. "
               "Beste resultate eerste.";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorAfrikaans::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1413 of file translator_za.h.
    {
      if (numDocuments==0)
      {
        return "Geen dokumente na gelang van jou navraag nie.";
      }
      else if (numDocuments==1)
      {
        return "Die soektog het <b>1</b> dokument gevind na gelang van jou navraag.";
      }
      else
      {
        return "Die soektog het <b>$num</b> dokumente gevind na gelang van jou navraag. "
               "Beste resultate eerste.";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorAfrikaans::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1401 of file translator_za.h.
    {
      return "Soektog Resultate";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorAfrikaans::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1401 of file translator_za.h.
    {
      return "Soektog Resultate";
    }
trSeeAlso() [1/2]
virtual QCString TranslatorAfrikaans::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 522 of file translator_za.h.
    { return "Sien ook"; }
trSeeAlso() [2/2]
virtual QCString TranslatorAfrikaans::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 522 of file translator_za.h.
    { return "Sien ook"; }
trSignals() [1/2]
virtual QCString TranslatorAfrikaans::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 616 of file translator_za.h.
    { return "Signals"; }
trSignals() [2/2]
virtual QCString TranslatorAfrikaans::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 616 of file translator_za.h.
    { return "Signals"; }
trSince() [1/2]
virtual QCString TranslatorAfrikaans::trSince () [inline], [virtual]
Implements Translator.
Definition at line 956 of file translator_za.h.
    {
      return "Sederd";
    }
trSince() [2/2]
virtual QCString TranslatorAfrikaans::trSince () [inline], [virtual]
Implements Translator.
Definition at line 956 of file translator_za.h.
    {
      return "Sederd";
    }
trSourceFile() [1/2]
virtual QCString TranslatorAfrikaans::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1443 of file translator_za.h.
    {
      return filename + " Bron kode Ler";
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorAfrikaans::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1443 of file translator_za.h.
    {
      return filename + " Bron kode Ler";
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorAfrikaans::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1372 of file translator_za.h.
    {
      return "Statiese Pakket Eienskappe";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorAfrikaans::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1372 of file translator_za.h.
    {
      return "Statiese Pakket Eienskappe";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorAfrikaans::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1358 of file translator_za.h.
    {
      return "Statiese Pakket Funksies";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorAfrikaans::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1358 of file translator_za.h.
    {
      return "Statiese Pakket Funksies";
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorAfrikaans::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 915 of file translator_za.h.
    {
      return "Statiese Private Attribute";
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorAfrikaans::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 915 of file translator_za.h.
    {
      return "Statiese Private Attribute";
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorAfrikaans::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 630 of file translator_za.h.
    { return "Statiese Private Lede Funksies"; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorAfrikaans::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 630 of file translator_za.h.
    { return "Statiese Private Lede Funksies"; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorAfrikaans::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 903 of file translator_za.h.
    {
      return "Statiese Beskermde Attribute";
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorAfrikaans::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 903 of file translator_za.h.
    {
      return "Statiese Beskermde Attribute";
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorAfrikaans::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 624 of file translator_za.h.
    { return "Statiese Beskermde Lede Funksies"; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorAfrikaans::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 624 of file translator_za.h.
    { return "Statiese Beskermde Lede Funksies"; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorAfrikaans::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 891 of file translator_za.h.
    {
      return "Statiese Publieke Attribute";
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorAfrikaans::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 891 of file translator_za.h.
    {
      return "Statiese Publieke Attribute";
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorAfrikaans::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 618 of file translator_za.h.
    { return "Statiese Publieke Lede Funksies"; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorAfrikaans::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 618 of file translator_za.h.
    { return "Statiese Publieke Lede Funksies"; }
trSubprogram() [1/2]
virtual QCString TranslatorAfrikaans::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1703 of file translator_za.h.
    {
      QCString result((first_capital ? "Subprogram" : "subprogram"));
      if (!singular) result+="me";
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorAfrikaans::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1703 of file translator_za.h.
    {
      QCString result((first_capital ? "Subprogram" : "subprogram"));
      if (!singular) result+="me";
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorAfrikaans::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1578 of file translator_za.h.
    { return "Funksies/Subroetine Dokumentasie"; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorAfrikaans::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1578 of file translator_za.h.
    { return "Funksies/Subroetine Dokumentasie"; }
trSubprograms() [1/2]
virtual QCString TranslatorAfrikaans::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1572 of file translator_za.h.
    { return "Funksies/Subroetines"; }
trSubprograms() [2/2]
virtual QCString TranslatorAfrikaans::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1572 of file translator_za.h.
    { return "Funksies/Subroetines"; }
trTest() [1/2]
virtual QCString TranslatorAfrikaans::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1046 of file translator_za.h.
    {
      return "Toets";
    }
trTest() [2/2]
virtual QCString TranslatorAfrikaans::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1046 of file translator_za.h.
    {
      return "Toets";
    }
trTestList() [1/2]
virtual QCString TranslatorAfrikaans::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1051 of file translator_za.h.
    {
      return "Toets Lys";
    }
trTestList() [2/2]
virtual QCString TranslatorAfrikaans::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1051 of file translator_za.h.
    {
      return "Toets Lys";
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorAfrikaans::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 123 of file translator_za.h.
    { return "Hierdie is 'n volledige lys van lede vir "; }
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorAfrikaans::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 123 of file translator_za.h.
    { return "Hierdie is 'n volledige lys van lede vir "; }
trTodo() [1/2]
virtual QCString TranslatorAfrikaans::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 925 of file translator_za.h.
    {
      return "Aksies";
    }
trTodo() [2/2]
virtual QCString TranslatorAfrikaans::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 925 of file translator_za.h.
    {
      return "Aksies";
    }
trTodoList() [1/2]
virtual QCString TranslatorAfrikaans::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 930 of file translator_za.h.
    {
      return "Aksie Lys";
    }
trTodoList() [2/2]
virtual QCString TranslatorAfrikaans::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 930 of file translator_za.h.
    {
      return "Aksie Lys";
    }
trType() [1/2]
virtual QCString TranslatorAfrikaans::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1693 of file translator_za.h.
    {
      QCString result((first_capital ? "Tipe" : "tipe"));
      if (!singular) result+="s";
      return result;
    }
trType() [2/2]
virtual QCString TranslatorAfrikaans::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1693 of file translator_za.h.
    {
      QCString result((first_capital ? "Tipe" : "tipe"));
      if (!singular) result+="s";
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorAfrikaans::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1711 of file translator_za.h.
    {
      return "Tipe Limiete";
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorAfrikaans::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1711 of file translator_za.h.
    {
      return "Tipe Limiete";
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorAfrikaans::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 452 of file translator_za.h.
    { return "Typedef Dokumentasie"; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorAfrikaans::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 452 of file translator_za.h.
    { return "Typedef Dokumentasie"; }
trTypedefs() [1/2]
virtual QCString TranslatorAfrikaans::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 416 of file translator_za.h.
    { return "Typedefs"; }
trTypedefs() [2/2]
virtual QCString TranslatorAfrikaans::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 416 of file translator_za.h.
    { return "Typedefs"; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorAfrikaans::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1566 of file translator_za.h.
    { return "Data Tipe Dokumentasie"; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorAfrikaans::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1566 of file translator_za.h.
    { return "Data Tipe Dokumentasie"; }
trVariableDocumentation() [1/2]
virtual QCString TranslatorAfrikaans::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 470 of file translator_za.h.
    { return "Veranderlike Dokumentasie"; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorAfrikaans::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 470 of file translator_za.h.
    { return "Veranderlike Dokumentasie"; }
trVariables() [1/2]
virtual QCString TranslatorAfrikaans::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 434 of file translator_za.h.
    { return "Veranderlikes"; }
trVariables() [2/2]
virtual QCString TranslatorAfrikaans::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 434 of file translator_za.h.
    { return "Veranderlikes"; }
trVersion() [1/2]
virtual QCString TranslatorAfrikaans::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 510 of file translator_za.h.
    { return "Weergawe"; }
trVersion() [2/2]
virtual QCString TranslatorAfrikaans::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 510 of file translator_za.h.
    { return "Weergawe"; }
trWarning() [1/2]
virtual QCString TranslatorAfrikaans::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 506 of file translator_za.h.
    { return "Waarskuwing"; }
trWarning() [2/2]
virtual QCString TranslatorAfrikaans::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 506 of file translator_za.h.
    { return "Waarskuwing"; }
trWriteList() [1/2]
virtual QCString TranslatorAfrikaans::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 636 of file translator_za.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=", en ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorAfrikaans::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 636 of file translator_za.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=", en ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_za.h
doxygen/src/translator_za.h