TranslatorFrench Class Reference
#include <translator_fr.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
virtual QCString trDesignUnitHierarchy ()
virtual QCString trDesignUnitList ()
virtual QCString trDesignUnitMembers ()
virtual QCString trDesignUnitListDescription ()
virtual QCString trDesignUnitIndex ()
virtual QCString trDesignUnits ()
virtual QCString trFunctionAndProc ()
virtual QCString trVhdlType (uint64 type, bool single)
virtual QCString trCustomReference (const QCString &name)
virtual QCString trConstants ()
virtual QCString trConstantDocumentation ()
virtual QCString trSequences ()
virtual QCString trSequenceDocumentation ()
virtual QCString trDictionaries ()
virtual QCString trDictionaryDocumentation ()
virtual QCString trSliceInterfaces ()
virtual QCString trInterfaceIndex ()
virtual QCString trInterfaceList ()
virtual QCString trInterfaceListDescription ()
virtual QCString trInterfaceHierarchy ()
virtual QCString trInterfaceHierarchyDescription ()
virtual QCString trInterfaceDocumentation ()
virtual QCString trStructs ()
virtual QCString trStructIndex ()
virtual QCString trStructList ()
virtual QCString trStructListDescription ()
virtual QCString trStructDocumentation ()
virtual QCString trExceptionIndex ()
virtual QCString trExceptionList ()
virtual QCString trExceptionListDescription ()
virtual QCString trExceptionHierarchy ()
virtual QCString trExceptionHierarchyDescription ()
virtual QCString trExceptionDocumentation ()
virtual QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal)
virtual QCString trOperations ()
virtual QCString trOperationDocumentation ()
virtual QCString trDataMembers ()
virtual QCString trDataMemberDocumentation ()
virtual QCString trDesignUnitDocumentation ()
virtual QCString trConcept (bool first_capital, bool singular)
virtual QCString trConceptReference (const QCString &conceptName)
virtual QCString trConceptList ()
virtual QCString trConceptIndex ()
virtual QCString trConceptDocumentation ()
virtual QCString trConceptListDescription (bool extractAll)
virtual QCString trConceptDefinition ()
virtual QCString trPackageList ()
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
virtual QCString trDesignUnitHierarchy ()
virtual QCString trDesignUnitList ()
virtual QCString trDesignUnitMembers ()
virtual QCString trDesignUnitListDescription ()
virtual QCString trDesignUnitIndex ()
virtual QCString trDesignUnits ()
virtual QCString trFunctionAndProc ()
virtual QCString trVhdlType (uint64 type, bool single)
virtual QCString trCustomReference (const QCString &name)
virtual QCString trConstants ()
virtual QCString trConstantDocumentation ()
virtual QCString trSequences ()
virtual QCString trSequenceDocumentation ()
virtual QCString trDictionaries ()
virtual QCString trDictionaryDocumentation ()
virtual QCString trSliceInterfaces ()
virtual QCString trInterfaceIndex ()
virtual QCString trInterfaceList ()
virtual QCString trInterfaceListDescription ()
virtual QCString trInterfaceHierarchy ()
virtual QCString trInterfaceHierarchyDescription ()
virtual QCString trInterfaceDocumentation ()
virtual QCString trStructs ()
virtual QCString trStructIndex ()
virtual QCString trStructList ()
virtual QCString trStructListDescription ()
virtual QCString trStructDocumentation ()
virtual QCString trExceptionIndex ()
virtual QCString trExceptionList ()
virtual QCString trExceptionListDescription ()
virtual QCString trExceptionHierarchy ()
virtual QCString trExceptionHierarchyDescription ()
virtual QCString trExceptionDocumentation ()
virtual QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal)
virtual QCString trOperations ()
virtual QCString trOperationDocumentation ()
virtual QCString trDataMembers ()
virtual QCString trDataMemberDocumentation ()
virtual QCString trDesignUnitDocumentation ()
virtual QCString trConcept (bool first_capital, bool singular)
virtual QCString trConceptReference (const QCString &conceptName)
virtual QCString trConceptList ()
virtual QCString trConceptIndex ()
virtual QCString trConceptDocumentation ()
virtual QCString trConceptListDescription (bool extractAll)
virtual QCString trConceptDefinition ()
virtual QCString trPackageList ()
Additional Inherited Members
Detailed Description
Definition at line 106 of file translator_fr.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorFrench::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 142 of file translator_fr.h.
    {
      return "0x40C French";
    }
getLanguageString() [2/2]
virtual QCString TranslatorFrench::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 142 of file translator_fr.h.
    {
      return "0x40C French";
    }
idLanguage() [1/2]
virtual QCString TranslatorFrench::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 118 of file translator_fr.h.
    { return "french"; }
idLanguage() [2/2]
virtual QCString TranslatorFrench::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 118 of file translator_fr.h.
    { return "french"; }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorFrench::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
"\\usepackage[latin2]{inputenc}\n"
"\\usepackage[T1]{fontenc}\n"
Implements Translator.
Definition at line 132 of file translator_fr.h.
    {
      return "\\usepackage[french]{babel}\n"
             "\\NoAutoSpaceBeforeFDP\n";
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorFrench::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
"\\usepackage[latin2]{inputenc}\n"
"\\usepackage[T1]{fontenc}\n"
Implements Translator.
Definition at line 132 of file translator_fr.h.
    {
      return "\\usepackage[french]{babel}\n"
             "\\NoAutoSpaceBeforeFDP\n";
    }
trAdditionalInheritedMembers() [1/2]
virtual QCString TranslatorFrench::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1964 of file translator_fr.h.
    { return "Membres hrits additionnels"; }
trAdditionalInheritedMembers() [2/2]
virtual QCString TranslatorFrench::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1964 of file translator_fr.h.
    { return "Membres hrits additionnels"; }
trAll() [1/2]
virtual QCString TranslatorFrench::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1474 of file translator_fr.h.
    {
      return "Tout";
    }
trAll() [2/2]
virtual QCString TranslatorFrench::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1474 of file translator_fr.h.
    {
      return "Tout";
    }
trAndMore() [1/2]
virtual QCString TranslatorFrench::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1942 of file translator_fr.h.
    { return "et "+number+" de plus..."; }
trAndMore() [2/2]
virtual QCString TranslatorFrench::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1942 of file translator_fr.h.
    { return "et "+number+" de plus..."; }
trAttention() [1/2]
virtual QCString TranslatorFrench::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 1034 of file translator_fr.h.
    {
      return "Attention";
    }
trAttention() [2/2]
virtual QCString TranslatorFrench::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 1034 of file translator_fr.h.
    {
      return "Attention";
    }
trAuthor() [1/2]
virtual QCString TranslatorFrench::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1345 of file translator_fr.h.
    {
      QCString result((first_capital ? "Auteur" : "auteur"));
      if (!singular) result+="s";
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorFrench::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1345 of file translator_fr.h.
    {
      QCString result((first_capital ? "Auteur" : "auteur"));
      if (!singular) result+="s";
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorFrench::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1202 of file translator_fr.h.
    {
      return "Bogue";
    }
trBug() [2/2]
virtual QCString TranslatorFrench::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1202 of file translator_fr.h.
    {
      return "Bogue";
    }
trBugList() [1/2]
virtual QCString TranslatorFrench::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1207 of file translator_fr.h.
    {
      return "Liste des bogues";
    }
trBugList() [2/2]
virtual QCString TranslatorFrench::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1207 of file translator_fr.h.
    {
      return "Liste des bogues";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorFrench::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1595 of file translator_fr.h.
    {
      return "Voici le graphe des appelants de cette fonction :";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorFrench::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1595 of file translator_fr.h.
    {
      return "Voici le graphe des appelants de cette fonction :";
    }
trCallGraph() [1/2]
virtual QCString TranslatorFrench::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1479 of file translator_fr.h.
    {
      return "Voici le graphe d'appel pour cette fonction :";
    }
trCallGraph() [2/2]
virtual QCString TranslatorFrench::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1479 of file translator_fr.h.
    {
      return "Voici le graphe d'appel pour cette fonction :";
    }
trCiteReferences() [1/2]
virtual QCString TranslatorFrench::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1917 of file translator_fr.h.
    { return "Rfrences bibliographiques"; }
trCiteReferences() [2/2]
virtual QCString TranslatorFrench::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1917 of file translator_fr.h.
    { return "Rfrences bibliographiques"; }
trClass() [1/2]
virtual QCString TranslatorFrench::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1265 of file translator_fr.h.
    {
      QCString result((first_capital ? "Classe" : "classe"));
      if (!singular) result+="s";
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorFrench::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1265 of file translator_fr.h.
    {
      QCString result((first_capital ? "Classe" : "classe"));
      if (!singular) result+="s";
      return result;
    }
trClassDiagram() [1/2]
virtual QCString TranslatorFrench::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 583 of file translator_fr.h.
    {
      return "Graphe d'hritage de "+clName+":";
    }
trClassDiagram() [2/2]
virtual QCString TranslatorFrench::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 583 of file translator_fr.h.
    {
      return "Graphe d'hritage de "+clName+":";
    }
trClassDocumentation() [1/2]
virtual QCString TranslatorFrench::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 458 of file translator_fr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentation des structures de donnes";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Documentation des classes";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorFrench::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 458 of file translator_fr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentation des structures de donnes";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Documentation des classes";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorFrench::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1165 of file translator_fr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Structures de donnes";
      }
      else
      {
        return "Classes";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorFrench::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1165 of file translator_fr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Structures de donnes";
      }
      else
      {
        return "Classes";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorFrench::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 237 of file translator_fr.h.
    { return "Hirarchie des classes"; }
trClassHierarchy() [2/2]
virtual QCString TranslatorFrench::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 237 of file translator_fr.h.
    { return "Hirarchie des classes"; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorFrench::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 296 of file translator_fr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return "Liste hirarchique de toutes les entits :";
      }
      else
      {
        return "Cette liste d'hritage est classe "
               "approximativement par ordre alphabtique :";
      }
    }
References Config_getBool.
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorFrench::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 296 of file translator_fr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return "Liste hirarchique de toutes les entits :";
      }
      else
      {
        return "Cette liste d'hritage est classe "
               "approximativement par ordre alphabtique :";
      }
    }
References Config_getBool.
trClassMethods() [1/2]
virtual QCString TranslatorFrench::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 2002 of file translator_fr.h.
    {
      return "Mthodes de classe";
    }
trClassMethods() [2/2]
virtual QCString TranslatorFrench::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 2002 of file translator_fr.h.
    {
      return "Mthodes de classe";
    }
trCode() [1/2]
virtual QCString TranslatorFrench::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 934 of file translator_fr.h.
    {
      return "code";
    }
trCode() [2/2]
virtual QCString TranslatorFrench::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 934 of file translator_fr.h.
    {
      return "code";
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorFrench::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 889 of file translator_fr.h.
    {
      return "Graphe de collaboration de "+clName+":";
    }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorFrench::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 889 of file translator_fr.h.
    {
      return "Graphe de collaboration de "+clName+":";
    }
trCompoundIndex() [1/2]
virtual QCString TranslatorFrench::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 431 of file translator_fr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Index des structures de donnes";
      }
      else
      {
        return "Index des classes";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorFrench::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 431 of file translator_fr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Index des structures de donnes";
      }
      else
      {
        return "Index des classes";
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorFrench::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1649 of file translator_fr.h.
    { return "Index du type de donnes"; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorFrench::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1649 of file translator_fr.h.
    { return "Index du type de donnes"; }
trCompoundList() [1/2]
virtual QCString TranslatorFrench::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 241 of file translator_fr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Structures de donnes";
      }
      else
      {
        return "Liste des classes";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorFrench::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 241 of file translator_fr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Structures de donnes";
      }
      else
      {
        return "Liste des classes";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorFrench::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 319 of file translator_fr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Liste des structures de donnes avec une brve description :";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Liste des classes avec une brve description :";
      }
      else
      {
        return "Liste des classes, structures, "
               "unions et interfaces avec une brve description :";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorFrench::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 319 of file translator_fr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Liste des structures de donnes avec une brve description :";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Liste des classes avec une brve description :";
      }
      else
      {
        return "Liste des classes, structures, "
               "unions et interfaces avec une brve description :";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorFrench::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1623 of file translator_fr.h.
    { return "Liste des types de donnes avec une brve description :"; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorFrench::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1623 of file translator_fr.h.
    { return "Liste des types de donnes avec une brve description :"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorFrench::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1615 of file translator_fr.h.
    { return "Liste des types de donnes"; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorFrench::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1615 of file translator_fr.h.
    { return "Liste des types de donnes"; }
trCompoundMembers() [1/2]
virtual QCString TranslatorFrench::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 258 of file translator_fr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Champs de donne";
      }
      else
      {
        return "Membres de classe";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorFrench::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 258 of file translator_fr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Champs de donne";
      }
      else
      {
        return "Membres de classe";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorFrench::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 337 of file translator_fr.h.
    {
      QCString result="Liste de tous les ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="champs de structure et d'union ";
      }
      else
      {
        result+="membres de classe ";
      }
      if (!extractAll)
      {
        result+="documents ";
      }
      result+="avec des liens vers ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="la documentation de structure/union de chaque champ :";
        }
        else
        {
          result+="la documentation de classe de chaque membre :";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="les structures/unions auxquelles ils appartiennent :";
        }
        else
        {
          result+="les classes auxquelles ils appartiennent :";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorFrench::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 337 of file translator_fr.h.
    {
      QCString result="Liste de tous les ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="champs de structure et d'union ";
      }
      else
      {
        result+="membres de classe ";
      }
      if (!extractAll)
      {
        result+="documents ";
      }
      result+="avec des liens vers ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="la documentation de structure/union de chaque champ :";
        }
        else
        {
          result+="la documentation de classe de chaque membre :";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="les structures/unions auxquelles ils appartiennent :";
        }
        else
        {
          result+="les classes auxquelles ils appartiennent :";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorFrench::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1627 of file translator_fr.h.
    {
      QCString result="Liste de tous les membres de types de donnes ";
      if (!extractAll)
      {
        result+="documents ";
      }
      result+="avec des liens vers ";
      if (!extractAll)
      {
         result+="la documentation de la structure des donnes de chaque membre :";
      }
      else
      {
         result+="les types des donnes auxquels ils appartiennent :";
      }
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorFrench::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1627 of file translator_fr.h.
    {
      QCString result="Liste de tous les membres de types de donnes ";
      if (!extractAll)
      {
        result+="documents ";
      }
      result+="avec des liens vers ";
      if (!extractAll)
      {
         result+="la documentation de la structure des donnes de chaque membre :";
      }
      else
      {
         result+="les types des donnes auxquels ils appartiennent :";
      }
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorFrench::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1619 of file translator_fr.h.
    { return "Champs de donnes"; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorFrench::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1619 of file translator_fr.h.
    { return "Champs de donnes"; }
trCompoundReference() [1/2]
virtual QCString TranslatorFrench::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 658 of file translator_fr.h.
    {
      QCString result="Rfrence ";
      if (isTemplate) result+="du modle ";
      result+="de ";
      switch(compType)
      {
        case ClassDef::Class: result+="la classe "; break;
        case ClassDef::Struct: result+="la structure "; break;
        case ClassDef::Union: result+="l'union "; break;
        case ClassDef::Interface: result+="l'interface "; break;
        case ClassDef::Protocol: result+="le protocol "; break;
        case ClassDef::Category: result+="la catgorie "; break;
        case ClassDef::Exception: result+="l'exception "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorFrench::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 658 of file translator_fr.h.
    {
      QCString result="Rfrence ";
      if (isTemplate) result+="du modle ";
      result+="de ";
      switch(compType)
      {
        case ClassDef::Class: result+="la classe "; break;
        case ClassDef::Struct: result+="la structure "; break;
        case ClassDef::Union: result+="l'union "; break;
        case ClassDef::Interface: result+="l'interface "; break;
        case ClassDef::Protocol: result+="le protocol "; break;
        case ClassDef::Category: result+="la catgorie "; break;
        case ClassDef::Exception: result+="l'exception "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorFrench::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1690 of file translator_fr.h.
    {
      QCString result="Rference ";
      if (isTemplate) result+="du modle ";
      switch(compType)
      {
        case ClassDef::Class: result+="du module "; break;
        case ClassDef::Struct: result+="du type "; break;
        case ClassDef::Union: result+="de l'union "; break;
        case ClassDef::Interface: result+="de l'interface "; break;
        case ClassDef::Protocol: result+="du protocole "; break;
        case ClassDef::Category: result+="de la catgorie "; break;
        case ClassDef::Exception: result+="de l'exception "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorFrench::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1690 of file translator_fr.h.
    {
      QCString result="Rference ";
      if (isTemplate) result+="du modle ";
      switch(compType)
      {
        case ClassDef::Class: result+="du module "; break;
        case ClassDef::Struct: result+="du type "; break;
        case ClassDef::Union: result+="de l'union "; break;
        case ClassDef::Interface: result+="de l'interface "; break;
        case ClassDef::Protocol: result+="du protocole "; break;
        case ClassDef::Category: result+="de la catgorie "; break;
        case ClassDef::Exception: result+="de l'exception "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice() [1/2]
virtual QCString TranslatorFrench::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) [inline], [virtual]
Implements Translator.
Definition at line 2291 of file translator_fr.h.
    {
      QCString result = "Rfrence ";
      bool feminine = true;
      switch(compType)
      {
        case ClassDef::Class: result+="de la classe "; break;
        case ClassDef::Struct: result+="de la structure "; break;
        case ClassDef::Union: result+="de l'union "; break;
        case ClassDef::Interface: result+="de l'interface "; break;
        case ClassDef::Protocol: result+="du protocole "; feminine=false; break;
        case ClassDef::Category: result+="de la catgorie "; break;
        case ClassDef::Exception: result+="de l'exception "; break;
        default: break;
      }
      if(isLocal)
      {
        result += (feminine) ? "locale " : "local ";
      }
      result += clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice() [2/2]
virtual QCString TranslatorFrench::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) [inline], [virtual]
Implements Translator.
Definition at line 2291 of file translator_fr.h.
    {
      QCString result = "Rfrence ";
      bool feminine = true;
      switch(compType)
      {
        case ClassDef::Class: result+="de la classe "; break;
        case ClassDef::Struct: result+="de la structure "; break;
        case ClassDef::Union: result+="de l'union "; break;
        case ClassDef::Interface: result+="de l'interface "; break;
        case ClassDef::Protocol: result+="du protocole "; feminine=false; break;
        case ClassDef::Category: result+="de la catgorie "; break;
        case ClassDef::Exception: result+="de l'exception "; break;
        default: break;
      }
      if(isLocal)
      {
        result += (feminine) ? "locale " : "local ";
      }
      result += clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorFrench::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 559 of file translator_fr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Structures de donnes";
      }
      else
      {
        return "Classes";
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorFrench::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 559 of file translator_fr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Structures de donnes";
      }
      else
      {
        return "Classes";
      }
    }
References Config_getBool.
trConcept() [1/2]
virtual QCString TranslatorFrench::trConcept (bool first_capital, bool singular) [inline], [virtual]
C++20 concept
Implements Translator.
Definition at line 2346 of file translator_fr.h.
    {
      QCString result((first_capital ? "Concept" : "concept"));
      if (!singular) result+="s";
      return result;
    }
trConcept() [2/2]
virtual QCString TranslatorFrench::trConcept (bool first_capital, bool singular) [inline], [virtual]
C++20 concept
Implements Translator.
Definition at line 2346 of file translator_fr.h.
    {
      QCString result((first_capital ? "Concept" : "concept"));
      if (!singular) result+="s";
      return result;
    }
trConceptDefinition() [1/2]
virtual QCString TranslatorFrench::trConceptDefinition () [inline], [virtual]
used to introduce the definition of the C++20 concept
Implements Translator.
Definition at line 2382 of file translator_fr.h.
    {
      return "Dfinition du concept";
    }
trConceptDefinition() [2/2]
virtual QCString TranslatorFrench::trConceptDefinition () [inline], [virtual]
used to introduce the definition of the C++20 concept
Implements Translator.
Definition at line 2382 of file translator_fr.h.
    {
      return "Dfinition du concept";
    }
trConceptDocumentation() [1/2]
virtual QCString TranslatorFrench::trConceptDocumentation () [inline], [virtual]
used as the title of chapter containing all information about concepts.
Implements Translator.
Definition at line 2369 of file translator_fr.h.
    { return "Documentation des concepts"; }
trConceptDocumentation() [2/2]
virtual QCString TranslatorFrench::trConceptDocumentation () [inline], [virtual]
used as the title of chapter containing all information about concepts.
Implements Translator.
Definition at line 2369 of file translator_fr.h.
    { return "Documentation des concepts"; }
trConceptIndex() [1/2]
virtual QCString TranslatorFrench::trConceptIndex () [inline], [virtual]
used as the title of chapter containing the index listing all concepts.
Implements Translator.
Definition at line 2365 of file translator_fr.h.
    { return "Index des concepts"; }
trConceptIndex() [2/2]
virtual QCString TranslatorFrench::trConceptIndex () [inline], [virtual]
used as the title of chapter containing the index listing all concepts.
Implements Translator.
Definition at line 2365 of file translator_fr.h.
    { return "Index des concepts"; }
trConceptList() [1/2]
virtual QCString TranslatorFrench::trConceptList () [inline], [virtual]
used as the title of page containing all the index of all concepts.
Implements Translator.
Definition at line 2361 of file translator_fr.h.
    { return "Liste des concepts"; }
trConceptList() [2/2]
virtual QCString TranslatorFrench::trConceptList () [inline], [virtual]
used as the title of page containing all the index of all concepts.
Implements Translator.
Definition at line 2361 of file translator_fr.h.
    { return "Liste des concepts"; }
trConceptListDescription() [1/2]
virtual QCString TranslatorFrench::trConceptListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the concept list
Implements Translator.
Definition at line 2373 of file translator_fr.h.
    {
      QCString result="Liste de tous les concepts ";
      if (!extractAll) result+="documents ";
      result+="avec une brve description :";
      return result;
    }
trConceptListDescription() [2/2]
virtual QCString TranslatorFrench::trConceptListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the concept list
Implements Translator.
Definition at line 2373 of file translator_fr.h.
    {
      QCString result="Liste de tous les concepts ";
      if (!extractAll) result+="documents ";
      result+="avec une brve description :";
      return result;
    }
trConceptReference() [1/2]
virtual QCString TranslatorFrench::trConceptReference (const QCString & conceptName) [inline], [virtual]
used as the title of the HTML page of a C++20 concept page
Implements Translator.
Definition at line 2353 of file translator_fr.h.
    {
      QCString result="Reference du concept ";
      result+=conceptName;
      return result;
    }
trConceptReference() [2/2]
virtual QCString TranslatorFrench::trConceptReference (const QCString & conceptName) [inline], [virtual]
used as the title of the HTML page of a C++20 concept page
Implements Translator.
Definition at line 2353 of file translator_fr.h.
    {
      QCString result="Reference du concept ";
      result+=conceptName;
      return result;
    }
trConstantDocumentation() [1/2]
virtual QCString TranslatorFrench::trConstantDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2199 of file translator_fr.h.
    {
        return "Documentation des constantes";
    }
trConstantDocumentation() [2/2]
virtual QCString TranslatorFrench::trConstantDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2199 of file translator_fr.h.
    {
        return "Documentation des constantes";
    }
trConstantGroupReference() [1/2]
virtual QCString TranslatorFrench::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 2039 of file translator_fr.h.
    {
      QCString result="Rfrence du groupe constant ";
      result+=namespaceName;
      return result;
    }
trConstantGroupReference() [2/2]
virtual QCString TranslatorFrench::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 2039 of file translator_fr.h.
    {
      QCString result="Rfrence du groupe constant ";
      result+=namespaceName;
      return result;
    }
trConstantGroups() [1/2]
virtual QCString TranslatorFrench::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 2035 of file translator_fr.h.
    { return "Groupes constants"; }
trConstantGroups() [2/2]
virtual QCString TranslatorFrench::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 2035 of file translator_fr.h.
    { return "Groupes constants"; }
trConstants() [1/2]
virtual QCString TranslatorFrench::trConstants () [inline], [virtual]
Implements Translator.
Definition at line 2195 of file translator_fr.h.
    {
        return "Constantes";
    }
trConstants() [2/2]
virtual QCString TranslatorFrench::trConstants () [inline], [virtual]
Implements Translator.
Definition at line 2195 of file translator_fr.h.
    {
        return "Constantes";
    }
trConstructorDocumentation() [1/2]
virtual QCString TranslatorFrench::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 899 of file translator_fr.h.
    {
      return "Documentation des constructeurs et destructeur";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorFrench::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 899 of file translator_fr.h.
    {
      return "Documentation des constructeurs et destructeur";
    }
trCopyright() [1/2]
virtual QCString TranslatorFrench::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1921 of file translator_fr.h.
    { return "Copyright"; }
trCopyright() [2/2]
virtual QCString TranslatorFrench::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1921 of file translator_fr.h.
    { return "Copyright"; }
trCustomReference() [1/2]
virtual QCString TranslatorFrench::trCustomReference (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 2192 of file translator_fr.h.
    { return QCString("Rfrence ") + QCString(name); }
References setup::name.
trCustomReference() [2/2]
virtual QCString TranslatorFrench::trCustomReference (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 2192 of file translator_fr.h.
    { return QCString("Rfrence ") + QCString(name); }
References setup::name.
trDataMemberDocumentation() [1/2]
virtual QCString TranslatorFrench::trDataMemberDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2328 of file translator_fr.h.
    {
        return "Documentation des champs de donnes";
    }
trDataMemberDocumentation() [2/2]
virtual QCString TranslatorFrench::trDataMemberDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2328 of file translator_fr.h.
    {
        return "Documentation des champs de donnes";
    }
trDataMembers() [1/2]
virtual QCString TranslatorFrench::trDataMembers () [inline], [virtual]
Implements Translator.
Definition at line 2324 of file translator_fr.h.
    {
        return "Champs de donnes";
    }
trDataMembers() [2/2]
virtual QCString TranslatorFrench::trDataMembers () [inline], [virtual]
Implements Translator.
Definition at line 2324 of file translator_fr.h.
    {
        return "Champs de donnes";
    }
trDataTypes() [1/2]
virtual QCString TranslatorFrench::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1673 of file translator_fr.h.
    { return "Les types de donnes"; }
trDataTypes() [2/2]
virtual QCString TranslatorFrench::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1673 of file translator_fr.h.
    { return "Les types de donnes"; }
trDate() [1/2]
virtual QCString TranslatorFrench::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 597 of file translator_fr.h.
    { return "Date"; }
trDate() [2/2]
virtual QCString TranslatorFrench::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 597 of file translator_fr.h.
    { return "Date"; }
trDateTime() [1/2]
virtual QCString TranslatorFrench::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1874 of file translator_fr.h.
    {
      static const char *days[] = { "Lundi","Mardi","Mercredi","Jeudi","Vendredi","Samedi","Dimanche" };
      static const char *months[] = { "Janvier","Fvrier","Mars","Avril","Mai","Juin","Juillet","Aot","Septembre","Octobre","Novembre","Dcembre" };
      QCString sdate;
      sdate.sprintf("%s %d %s %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDateTime() [2/2]
virtual QCString TranslatorFrench::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1874 of file translator_fr.h.
    {
      static const char *days[] = { "Lundi","Mardi","Mercredi","Jeudi","Vendredi","Samedi","Dimanche" };
      static const char *months[] = { "Janvier","Fvrier","Mars","Avril","Mai","Juin","Juillet","Aot","Septembre","Octobre","Novembre","Dcembre" };
      QCString sdate;
      sdate.sprintf("%s %d %s %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDayOfWeek() [1/2]
virtual QCString TranslatorFrench::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1890 of file translator_fr.h.
    {
      static const char *days_short[] = { "lun.", "mar.", "mer.", "jeu.", "ven.", "sam.", "dim." };
      static const char *days_full[] = { "lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi", "dimanche" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayOfWeek() [2/2]
virtual QCString TranslatorFrench::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1890 of file translator_fr.h.
    {
      static const char *days_short[] = { "lun.", "mar.", "mer.", "jeu.", "ven.", "sam.", "dim." };
      static const char *days_full[] = { "lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi", "dimanche" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod() [1/2]
virtual QCString TranslatorFrench::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1906 of file translator_fr.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorFrench::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1906 of file translator_fr.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorFrench::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 866 of file translator_fr.h.
    {
      return "Dfinition la ligne @0 du fichier @1.";
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorFrench::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 866 of file translator_fr.h.
    {
      return "Dfinition la ligne @0 du fichier @1.";
    }
trDefinedIn() [1/2]
virtual QCString TranslatorFrench::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 225 of file translator_fr.h.
    { return "dfini dans"; }
trDefinedIn() [2/2]
virtual QCString TranslatorFrench::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 225 of file translator_fr.h.
    { return "dfini dans"; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorFrench::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 870 of file translator_fr.h.
    {
      return "Dfinition dans le fichier @0.";
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorFrench::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 870 of file translator_fr.h.
    {
      return "Dfinition dans le fichier @0.";
    }
trDefineDocumentation() [1/2]
virtual QCString TranslatorFrench::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 529 of file translator_fr.h.
    { return "Documentation des macros"; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorFrench::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 529 of file translator_fr.h.
    { return "Documentation des macros"; }
trDefines() [1/2]
virtual QCString TranslatorFrench::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 493 of file translator_fr.h.
    { return "Macros"; }
trDefines() [2/2]
virtual QCString TranslatorFrench::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 493 of file translator_fr.h.
    { return "Macros"; }
trDefineValue() [1/2]
virtual QCString TranslatorFrench::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1192 of file translator_fr.h.
    {
      return "Valeur :";
    }
trDefineValue() [2/2]
virtual QCString TranslatorFrench::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1192 of file translator_fr.h.
    {
      return "Valeur :";
    }
trDeprecated() [1/2]
virtual QCString TranslatorFrench::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 879 of file translator_fr.h.
    {
      return "Obsolte";
    }
trDeprecated() [2/2]
virtual QCString TranslatorFrench::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 879 of file translator_fr.h.
    {
      return "Obsolte";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorFrench::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1402 of file translator_fr.h.
    {
      return "Liste des lments obsoltes";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorFrench::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1402 of file translator_fr.h.
    {
      return "Liste des lments obsoltes";
    }
trDesignUnitDocumentation() [1/2]
virtual QCString TranslatorFrench::trDesignUnitDocumentation () [inline], [virtual]
VHDL design unit documentation
Implements Translator.
Definition at line 2338 of file translator_fr.h.
    { return "Documentation de l'unit de conception"; }
Referenced by trClassDocumentation().
trDesignUnitDocumentation() [2/2]
virtual QCString TranslatorFrench::trDesignUnitDocumentation () [inline], [virtual]
VHDL design unit documentation
Implements Translator.
Definition at line 2338 of file translator_fr.h.
    { return "Documentation de l'unit de conception"; }
trDesignUnitHierarchy() [1/2]
virtual QCString TranslatorFrench::trDesignUnitHierarchy () [inline], [virtual]
VHDL design unit hierarchy
Implements Translator.
Definition at line 2083 of file translator_fr.h.
    { return "Hirarchie des units de conception"; }
trDesignUnitHierarchy() [2/2]
virtual QCString TranslatorFrench::trDesignUnitHierarchy () [inline], [virtual]
VHDL design unit hierarchy
Implements Translator.
Definition at line 2083 of file translator_fr.h.
    { return "Hirarchie des units de conception"; }
trDesignUnitIndex() [1/2]
virtual QCString TranslatorFrench::trDesignUnitIndex () [inline], [virtual]
VHDL design unit index
Implements Translator.
Definition at line 2098 of file translator_fr.h.
    { return "Index des units de conception"; }
trDesignUnitIndex() [2/2]
virtual QCString TranslatorFrench::trDesignUnitIndex () [inline], [virtual]
VHDL design unit index
Implements Translator.
Definition at line 2098 of file translator_fr.h.
    { return "Index des units de conception"; }
trDesignUnitList() [1/2]
virtual QCString TranslatorFrench::trDesignUnitList () [inline], [virtual]
VHDL design unit list
Implements Translator.
Definition at line 2086 of file translator_fr.h.
    { return "Liste des units de conception"; }
trDesignUnitList() [2/2]
virtual QCString TranslatorFrench::trDesignUnitList () [inline], [virtual]
VHDL design unit list
Implements Translator.
Definition at line 2086 of file translator_fr.h.
    { return "Liste des units de conception"; }
trDesignUnitListDescription() [1/2]
virtual QCString TranslatorFrench::trDesignUnitListDescription () [inline], [virtual]
VHDL design unit list description
Implements Translator.
Definition at line 2092 of file translator_fr.h.
    {
        return "Liste de tous les membres des units de conception avec liens vers "
            "les entits auxquelles ils appartiennent :";
    }
trDesignUnitListDescription() [2/2]
virtual QCString TranslatorFrench::trDesignUnitListDescription () [inline], [virtual]
VHDL design unit list description
Implements Translator.
Definition at line 2092 of file translator_fr.h.
    {
        return "Liste de tous les membres des units de conception avec liens vers "
            "les entits auxquelles ils appartiennent :";
    }
trDesignUnitMembers() [1/2]
virtual QCString TranslatorFrench::trDesignUnitMembers () [inline], [virtual]
VHDL design unit members
Implements Translator.
Definition at line 2089 of file translator_fr.h.
    { return "Membres des units de conception"; }
trDesignUnitMembers() [2/2]
virtual QCString TranslatorFrench::trDesignUnitMembers () [inline], [virtual]
VHDL design unit members
Implements Translator.
Definition at line 2089 of file translator_fr.h.
    { return "Membres des units de conception"; }
trDesignUnits() [1/2]
virtual QCString TranslatorFrench::trDesignUnits () [inline], [virtual]
VHDL design units
Implements Translator.
Definition at line 2101 of file translator_fr.h.
    { return "Units de conception"; }
trDesignUnits() [2/2]
virtual QCString TranslatorFrench::trDesignUnits () [inline], [virtual]
VHDL design units
Implements Translator.
Definition at line 2101 of file translator_fr.h.
    { return "Units de conception"; }
trDetailedDescription() [1/2]
virtual QCString TranslatorFrench::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 158 of file translator_fr.h.
    { return "Description dtaille"; }
trDetailedDescription() [2/2]
virtual QCString TranslatorFrench::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 158 of file translator_fr.h.
    { return "Description dtaille"; }
trDetailLevel() [1/2]
virtual QCString TranslatorFrench::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1934 of file translator_fr.h.
    { return "Niveau de dtails"; }
trDetailLevel() [2/2]
virtual QCString TranslatorFrench::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1934 of file translator_fr.h.
    { return "Niveau de dtails"; }
trDictionaries() [1/2]
virtual QCString TranslatorFrench::trDictionaries () [inline], [virtual]
Implements Translator.
Definition at line 2211 of file translator_fr.h.
    {
        return "Dictionnaires";
    }
trDictionaries() [2/2]
virtual QCString TranslatorFrench::trDictionaries () [inline], [virtual]
Implements Translator.
Definition at line 2211 of file translator_fr.h.
    {
        return "Dictionnaires";
    }
trDictionaryDocumentation() [1/2]
virtual QCString TranslatorFrench::trDictionaryDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2215 of file translator_fr.h.
    {
        return "Documentation des dictionnaires";
    }
trDictionaryDocumentation() [2/2]
virtual QCString TranslatorFrench::trDictionaryDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2215 of file translator_fr.h.
    {
        return "Documentation des dictionnaires";
    }
trDir() [1/2]
virtual QCString TranslatorFrench::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in singular or plural form (singular).
Implements Translator.
Definition at line 1569 of file translator_fr.h.
    {
      QCString result((first_capital ? "Rpertoire" : "rpertoire"));
      if (singular) result+=""; else result+="s";
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorFrench::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in singular or plural form (singular).
Implements Translator.
Definition at line 1569 of file translator_fr.h.
    {
      QCString result((first_capital ? "Rpertoire" : "rpertoire"));
      if (singular) result+=""; else result+="s";
      return result;
    }
trDirDepGraph() [1/2]
virtual QCString TranslatorFrench::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1925 of file translator_fr.h.
    { return QCString("Graphe des dpendances de rpertoires pour ")+name+":"; }
References setup::name.
trDirDepGraph() [2/2]
virtual QCString TranslatorFrench::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1925 of file translator_fr.h.
    { return QCString("Graphe des dpendances de rpertoires pour ")+name+":"; }
References setup::name.
trDirDocumentation() [1/2]
virtual QCString TranslatorFrench::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1551 of file translator_fr.h.
    { return "Documentation des rpertoires"; }
trDirDocumentation() [2/2]
virtual QCString TranslatorFrench::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1551 of file translator_fr.h.
    { return "Documentation des rpertoires"; }
trDirectories() [1/2]
virtual QCString TranslatorFrench::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1557 of file translator_fr.h.
    { return "Rpertoires"; }
trDirectories() [2/2]
virtual QCString TranslatorFrench::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1557 of file translator_fr.h.
    { return "Rpertoires"; }
trDirIndex() [1/2]
virtual QCString TranslatorFrench::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1545 of file translator_fr.h.
    { return "Hirarchie de rpertoires"; }
trDirIndex() [2/2]
virtual QCString TranslatorFrench::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1545 of file translator_fr.h.
    { return "Hirarchie de rpertoires"; }
trDirReference() [1/2]
virtual QCString TranslatorFrench::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1563 of file translator_fr.h.
    { QCString result="Rpertoire de rfrence de "; result+=dirName; return result; }
trDirReference() [2/2]
virtual QCString TranslatorFrench::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1563 of file translator_fr.h.
    { QCString result="Rpertoire de rfrence de "; result+=dirName; return result; }
trDirRelation() [1/2]
virtual QCString TranslatorFrench::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1813 of file translator_fr.h.
    {
      return "Relation " + QCString(name);
    }
References setup::name.
trDirRelation() [2/2]
virtual QCString TranslatorFrench::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1813 of file translator_fr.h.
    {
      return "Relation " + QCString(name);
    }
References setup::name.
trDocumentation() [1/2]
virtual QCString TranslatorFrench::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 413 of file translator_fr.h.
    { return "Documentation"; }
trDocumentation() [2/2]
virtual QCString TranslatorFrench::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 413 of file translator_fr.h.
    { return "Documentation"; }
trEnumerations() [1/2]
virtual QCString TranslatorFrench::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 505 of file translator_fr.h.
    { return "numrations"; }
trEnumerations() [2/2]
virtual QCString TranslatorFrench::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 505 of file translator_fr.h.
    { return "numrations"; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorFrench::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 541 of file translator_fr.h.
    { return "Documentation du type de l'numration"; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorFrench::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 541 of file translator_fr.h.
    { return "Documentation du type de l'numration"; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorFrench::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1603 of file translator_fr.h.
    { return "Documentation des numrations"; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorFrench::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1603 of file translator_fr.h.
    { return "Documentation des numrations"; }
trEnumerationValues() [1/2]
virtual QCString TranslatorFrench::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 523 of file translator_fr.h.
    { return "Valeurs numres"; }
trEnumerationValues() [2/2]
virtual QCString TranslatorFrench::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 523 of file translator_fr.h.
    { return "Valeurs numres"; }
trEnumGeneratedFromFiles() [1/2]
virtual QCString TranslatorFrench::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1946 of file translator_fr.h.
    { QCString result = "La documentation pour cette numration a t gnre partir ";
      if (!single) result += "du fichier suivant"; else result += "des fichiers suivants";
      result+=" :";
      return result;
    }
trEnumGeneratedFromFiles() [2/2]
virtual QCString TranslatorFrench::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1946 of file translator_fr.h.
    { QCString result = "La documentation pour cette numration a t gnre partir ";
      if (!single) result += "du fichier suivant"; else result += "des fichiers suivants";
      result+=" :";
      return result;
    }
trEnumName() [1/2]
virtual QCString TranslatorFrench::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 217 of file translator_fr.h.
    { return "numration"; }
trEnumName() [2/2]
virtual QCString TranslatorFrench::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 217 of file translator_fr.h.
    { return "numration"; }
trEnumReference() [1/2]
virtual QCString TranslatorFrench::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1954 of file translator_fr.h.
    { return QCString(name)+" Rfrence de l'numration"; }
References setup::name.
trEnumReference() [2/2]
virtual QCString TranslatorFrench::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1954 of file translator_fr.h.
    { return QCString(name)+" Rfrence de l'numration"; }
References setup::name.
trEnumValue() [1/2]
virtual QCString TranslatorFrench::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 221 of file translator_fr.h.
    { return "valeur numre"; }
trEnumValue() [2/2]
virtual QCString TranslatorFrench::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 221 of file translator_fr.h.
    { return "valeur numre"; }
trEventDocumentation() [1/2]
virtual QCString TranslatorFrench::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1419 of file translator_fr.h.
    {
      return "Documentation des vnements";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorFrench::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1419 of file translator_fr.h.
    {
      return "Documentation des vnements";
    }
trEvents() [1/2]
virtual QCString TranslatorFrench::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1414 of file translator_fr.h.
    {
      return "vnements";
    }
trEvents() [2/2]
virtual QCString TranslatorFrench::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1414 of file translator_fr.h.
    {
      return "vnements";
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorFrench::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 483 of file translator_fr.h.
    { return "Documentation des exemples"; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorFrench::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 483 of file translator_fr.h.
    { return "Documentation des exemples"; }
trExamples() [1/2]
virtual QCString TranslatorFrench::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 288 of file translator_fr.h.
    { return "Exemples"; }
trExamples() [2/2]
virtual QCString TranslatorFrench::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 288 of file translator_fr.h.
    { return "Exemples"; }
trExamplesDescription() [1/2]
virtual QCString TranslatorFrench::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 401 of file translator_fr.h.
    { return "Liste de tous les exemples :"; }
trExamplesDescription() [2/2]
virtual QCString TranslatorFrench::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 401 of file translator_fr.h.
    { return "Liste de tous les exemples :"; }
trExceptionDocumentation() [1/2]
virtual QCString TranslatorFrench::trExceptionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2287 of file translator_fr.h.
    {
        return "Documentation des exceptions";
    }
trExceptionDocumentation() [2/2]
virtual QCString TranslatorFrench::trExceptionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2287 of file translator_fr.h.
    {
        return "Documentation des exceptions";
    }
trExceptionHierarchy() [1/2]
virtual QCString TranslatorFrench::trExceptionHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2279 of file translator_fr.h.
    {
        return "Hirarchies des exceptions";
    }
trExceptionHierarchy() [2/2]
virtual QCString TranslatorFrench::trExceptionHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2279 of file translator_fr.h.
    {
        return "Hirarchies des exceptions";
    }
trExceptionHierarchyDescription() [1/2]
virtual QCString TranslatorFrench::trExceptionHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2283 of file translator_fr.h.
    {
        return "Cette liste d'hritage est classe approximativement par ordre alphabtique :";
    }
trExceptionHierarchyDescription() [2/2]
virtual QCString TranslatorFrench::trExceptionHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2283 of file translator_fr.h.
    {
        return "Cette liste d'hritage est classe approximativement par ordre alphabtique :";
    }
trExceptionIndex() [1/2]
virtual QCString TranslatorFrench::trExceptionIndex () [inline], [virtual]
Implements Translator.
Definition at line 2267 of file translator_fr.h.
    {
        return "Index des exceptions";
    }
trExceptionIndex() [2/2]
virtual QCString TranslatorFrench::trExceptionIndex () [inline], [virtual]
Implements Translator.
Definition at line 2267 of file translator_fr.h.
    {
        return "Index des exceptions";
    }
trExceptionList() [1/2]
virtual QCString TranslatorFrench::trExceptionList () [inline], [virtual]
Implements Translator.
Definition at line 2271 of file translator_fr.h.
    {
        return "Liste des exceptions";
    }
trExceptionList() [2/2]
virtual QCString TranslatorFrench::trExceptionList () [inline], [virtual]
Implements Translator.
Definition at line 2271 of file translator_fr.h.
    {
        return "Liste des exceptions";
    }
trExceptionListDescription() [1/2]
virtual QCString TranslatorFrench::trExceptionListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2275 of file translator_fr.h.
    {
        return "Liste des exceptions avec une brve description :";
    }
trExceptionListDescription() [2/2]
virtual QCString TranslatorFrench::trExceptionListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2275 of file translator_fr.h.
    {
        return "Liste des exceptions avec une brve description :";
    }
trExceptions() [1/2]
virtual QCString TranslatorFrench::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 613 of file translator_fr.h.
    { return "Exceptions"; }
trExceptions() [2/2]
virtual QCString TranslatorFrench::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 613 of file translator_fr.h.
    { return "Exceptions"; }
trExtendsClass() [1/2]
virtual QCString TranslatorFrench::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1994 of file translator_fr.h.
    {
      return "Drive la classe @0.";
    }
trExtendsClass() [2/2]
virtual QCString TranslatorFrench::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1994 of file translator_fr.h.
    {
      return "Drive la classe @0.";
    }
trFile() [1/2]
virtual QCString TranslatorFrench::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1276 of file translator_fr.h.
    {
      QCString result((first_capital ? "Fichier" : "fichier"));
      if (!singular) result+="s";
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorFrench::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1276 of file translator_fr.h.
    {
      QCString result((first_capital ? "Fichier" : "fichier"));
      if (!singular) result+="s";
      return result;
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorFrench::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 477 of file translator_fr.h.
    { return "Documentation des fichiers"; }
trFileDocumentation() [2/2]
virtual QCString TranslatorFrench::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 477 of file translator_fr.h.
    { return "Documentation des fichiers"; }
trFileIn() [1/2]
virtual QCString TranslatorFrench::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1850 of file translator_fr.h.
    {
      return "Fichier dans "+name;
    }
References setup::name.
trFileIn() [2/2]
virtual QCString TranslatorFrench::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1850 of file translator_fr.h.
    {
      return "Fichier dans "+name;
    }
References setup::name.
trFileIndex() [1/2]
virtual QCString TranslatorFrench::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 446 of file translator_fr.h.
    { return "Index des fichiers"; }
trFileIndex() [2/2]
virtual QCString TranslatorFrench::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 446 of file translator_fr.h.
    { return "Index des fichiers"; }
trFileList() [1/2]
virtual QCString TranslatorFrench::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 254 of file translator_fr.h.
    { return "Liste des fichiers"; }
trFileList() [2/2]
virtual QCString TranslatorFrench::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 254 of file translator_fr.h.
    { return "Liste des fichiers"; }
trFileListDescription() [1/2]
virtual QCString TranslatorFrench::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 310 of file translator_fr.h.
    {
      QCString result="Liste de tous les fichiers ";
      if (!extractAll) result+="documents ";
      result+="avec une brve description :";
      return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorFrench::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 310 of file translator_fr.h.
    {
      QCString result="Liste de tous les fichiers ";
      if (!extractAll) result+="documents ";
      result+="avec une brve description :";
      return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorFrench::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 271 of file translator_fr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Variables globale";
      }
      else
      {
        return "Membres de fichier";
      }
    }
References Config_getBool.
trFileMembers() [2/2]
virtual QCString TranslatorFrench::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 271 of file translator_fr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Variables globale";
      }
      else
      {
        return "Membres de fichier";
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
virtual QCString TranslatorFrench::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 379 of file translator_fr.h.
    {
      QCString result="Liste ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="de toutes les fonctions, variables, macros, enumrations, et dfinitions de type ";
      }
      else
      {
        result+="de tous les membres de fichier ";
      }
      if (!extractAll) result+="documents ";
      result+="avec des liens vers ";
      if (extractAll)
        result+="les fichiers auxquels ils appartiennent :";
      else
        result+="la documentation :";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorFrench::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 379 of file translator_fr.h.
    {
      QCString result="Liste ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="de toutes les fonctions, variables, macros, enumrations, et dfinitions de type ";
      }
      else
      {
        result+="de tous les membres de fichier ";
      }
      if (!extractAll) result+="documents ";
      result+="avec des liens vers ";
      if (extractAll)
        result+="les fichiers auxquels ils appartiennent :";
      else
        result+="la documentation :";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorFrench::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 681 of file translator_fr.h.
    {
      QCString result= "Rfrence du fichier ";
      result+=fileName;
      return result;
    }
trFileReference() [2/2]
virtual QCString TranslatorFrench::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 681 of file translator_fr.h.
    {
      QCString result= "Rfrence du fichier ";
      result+=fileName;
      return result;
    }
trFriends() [1/2]
virtual QCString TranslatorFrench::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 640 of file translator_fr.h.
    { return "Amis"; }
trFriends() [2/2]
virtual QCString TranslatorFrench::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 640 of file translator_fr.h.
    { return "Amis"; }
trFunctionAndProc() [1/2]
virtual QCString TranslatorFrench::trFunctionAndProc () [inline], [virtual]
VHDL functions/procedures/processes
Implements Translator.
Definition at line 2104 of file translator_fr.h.
    { return "Fonctions/Procdures/Processes"; }
trFunctionAndProc() [2/2]
virtual QCString TranslatorFrench::trFunctionAndProc () [inline], [virtual]
VHDL functions/procedures/processes
Implements Translator.
Definition at line 2104 of file translator_fr.h.
    { return "Fonctions/Procdures/Processes"; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorFrench::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 547 of file translator_fr.h.
    { return "Documentation des fonctions"; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorFrench::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 547 of file translator_fr.h.
    { return "Documentation des fonctions"; }
trFunctions() [1/2]
virtual QCString TranslatorFrench::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 511 of file translator_fr.h.
    { return "Fonctions"; }
trFunctions() [2/2]
virtual QCString TranslatorFrench::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 511 of file translator_fr.h.
    { return "Fonctions"; }
trGeneratedAt() [1/2]
virtual QCString TranslatorFrench::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 574 of file translator_fr.h.
    {
      QCString result="Gnr le "+date;
      if (!projName.isEmpty()) result+=" pour "+projName;
      result+=" par";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorFrench::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 574 of file translator_fr.h.
    {
      QCString result="Gnr le "+date;
      if (!projName.isEmpty()) result+=" pour "+projName;
      result+=" par";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorFrench::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 209 of file translator_fr.h.
    { QCString result="Gnr automatiquement par Doxygen";
      if (!s.isEmpty()) result+=" pour "+s;
      result+=" partir du code source.";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorFrench::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 209 of file translator_fr.h.
    { QCString result="Gnr automatiquement par Doxygen";
      if (!s.isEmpty()) result+=" pour "+s;
      result+=" partir du code source.";
      return result;
    }
References s.
trGeneratedBy() [1/2]
virtual QCString TranslatorFrench::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 617 of file translator_fr.h.
    { return "Gnr par"; }
trGeneratedBy() [2/2]
virtual QCString TranslatorFrench::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 617 of file translator_fr.h.
    { return "Gnr par"; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorFrench::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 819 of file translator_fr.h.
    { // single is true implies a single file
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      bool feminine = true;
      QCString result="La documentation de ";
      switch(compType)
      {
        case ClassDef::Class: result+=vhdlOpt? "cette units de conception":"cette classe"; break;
        case ClassDef::Struct: result+="cette structure"; break;
        case ClassDef::Union: result+="cette union"; break;
        case ClassDef::Interface: result+="cette interface"; break;
        case ClassDef::Protocol: result+="ce protocol"; feminine = false; break;
        case ClassDef::Category: result+="cette catgorie"; break;
        case ClassDef::Exception: result+="cette exception"; break;
        default: break;
      }
      if (feminine) result+= " a t gnre partir ";
      else result+=" a t gnr partir ";
      if (single) result+="du fichier suivant :";
      else result+="des fichiers suivants :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, Config_getBool, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorFrench::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 819 of file translator_fr.h.
    { // single is true implies a single file
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      bool feminine = true;
      QCString result="La documentation de ";
      switch(compType)
      {
        case ClassDef::Class: result+=vhdlOpt? "cette units de conception":"cette classe"; break;
        case ClassDef::Struct: result+="cette structure"; break;
        case ClassDef::Union: result+="cette union"; break;
        case ClassDef::Interface: result+="cette interface"; break;
        case ClassDef::Protocol: result+="ce protocol"; feminine = false; break;
        case ClassDef::Category: result+="cette catgorie"; break;
        case ClassDef::Exception: result+="cette exception"; break;
        default: break;
      }
      if (feminine) result+= " a t gnre partir ";
      else result+=" a t gnr partir ";
      if (single) result+="du fichier suivant :";
      else result+="des fichiers suivants :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, Config_getBool, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorFrench::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1759 of file translator_fr.h.
    {
      // single is true implies a single file
      QCString result="La documentation de ";
      switch(compType)
      {
        case ClassDef::Class: result+="ce module"; break;
        case ClassDef::Struct: result+="ce type"; break;
        case ClassDef::Union: result+="cette union"; break;
        case ClassDef::Interface: result+="cette interface"; break;
        case ClassDef::Protocol: result+="ce protocole"; break;
        case ClassDef::Category: result+="cette catgorie"; break;
        case ClassDef::Exception: result+="cette exception"; break;
        default: break;
      }
      result+=" a t gnre partir ";
      if (single) result+="du fichier suivant :"; else result+="des fichiers suivants :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorFrench::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1759 of file translator_fr.h.
    {
      // single is true implies a single file
      QCString result="La documentation de ";
      switch(compType)
      {
        case ClassDef::Class: result+="ce module"; break;
        case ClassDef::Struct: result+="ce type"; break;
        case ClassDef::Union: result+="cette union"; break;
        case ClassDef::Interface: result+="cette interface"; break;
        case ClassDef::Protocol: result+="ce protocole"; break;
        case ClassDef::Category: result+="cette catgorie"; break;
        case ClassDef::Exception: result+="cette exception"; break;
        default: break;
      }
      result+=" a t gnre partir ";
      if (single) result+="du fichier suivant :"; else result+="des fichiers suivants :";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorFrench::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1332 of file translator_fr.h.
    {
      QCString result((first_capital ? "Globa" : "globa"));
      if (!singular) result+="ux(ales)"; else result+="l(e)";
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorFrench::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1332 of file translator_fr.h.
    {
      QCString result((first_capital ? "Globa" : "globa"));
      if (!singular) result+="ux(ales)"; else result+="l(e)";
      return result;
    }
trGlobalNamespace() [1/2]
virtual QCString TranslatorFrench::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1825 of file translator_fr.h.
    {
      return "Espace de nommage global";
    }
trGlobalNamespace() [2/2]
virtual QCString TranslatorFrench::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1825 of file translator_fr.h.
    {
      return "Espace de nommage global";
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorFrench::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 909 of file translator_fr.h.
    {
      return "Aller la documentation de ce fichier.";
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorFrench::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 909 of file translator_fr.h.
    {
      return "Aller la documentation de ce fichier.";
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorFrench::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 942 of file translator_fr.h.
    {
      return "Aller au graphe hirarchique des classes";
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorFrench::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 942 of file translator_fr.h.
    {
      return "Aller au graphe hirarchique des classes";
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorFrench::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 904 of file translator_fr.h.
    {
      return "Aller au code source de ce fichier.";
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorFrench::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 904 of file translator_fr.h.
    {
      return "Aller au code source de ce fichier.";
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorFrench::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 946 of file translator_fr.h.
    {
      return "Aller la hirarchie des classes en mode texte";
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorFrench::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 946 of file translator_fr.h.
    {
      return "Aller la hirarchie des classes en mode texte";
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorFrench::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 938 of file translator_fr.h.
    {
      return "Graphe hirarchique des classes";
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorFrench::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 938 of file translator_fr.h.
    {
      return "Graphe hirarchique des classes";
    }
trGroup() [1/2]
virtual QCString TranslatorFrench::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1299 of file translator_fr.h.
    {
      QCString result((first_capital ? "Groupe" : "groupe"));
      if (!singular) result+="s";
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorFrench::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1299 of file translator_fr.h.
    {
      QCString result((first_capital ? "Groupe" : "groupe"));
      if (!singular) result+="s";
      return result;
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorFrench::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 425 of file translator_fr.h.
    { return "Index hirarchique"; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorFrench::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 425 of file translator_fr.h.
    { return "Index hirarchique"; }
trImplementedFromList() [1/2]
virtual QCString TranslatorFrench::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1370 of file translator_fr.h.
    {
      return "Implmente "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorFrench::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1370 of file translator_fr.h.
    {
      return "Implmente "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorFrench::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1378 of file translator_fr.h.
    {
      return "Implment dans "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorFrench::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1378 of file translator_fr.h.
    {
      return "Implment dans "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorFrench::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 1038 of file translator_fr.h.
    {
      return "Ce graphe montre quels fichiers incluent directement "
             "ou indirectement ce fichier :";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorFrench::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 1038 of file translator_fr.h.
    {
      return "Ce graphe montre quels fichiers incluent directement "
             "ou indirectement ce fichier :";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorFrench::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 894 of file translator_fr.h.
    {
      return "Graphe des dpendances par inclusion de "+fName+":";
    }
trInclDepGraph() [2/2]
virtual QCString TranslatorFrench::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 894 of file translator_fr.h.
    {
      return "Graphe des dpendances par inclusion de "+fName+":";
    }
trIncludesFileIn() [1/2]
virtual QCString TranslatorFrench::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1859 of file translator_fr.h.
    {
      return "Inclut le fichier dans "+name;
    }
References setup::name.
trIncludesFileIn() [2/2]
virtual QCString TranslatorFrench::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1859 of file translator_fr.h.
    {
      return "Inclut le fichier dans "+name;
    }
References setup::name.
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorFrench::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 203 of file translator_fr.h.
    { return ", y compris les membres hrits :"; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorFrench::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 203 of file translator_fr.h.
    { return ", y compris les membres hrits :"; }
trInheritedByList() [1/2]
virtual QCString TranslatorFrench::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 753 of file translator_fr.h.
    {
      return "Drive par "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorFrench::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 753 of file translator_fr.h.
    {
      return "Drive par "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom() [1/2]
virtual QCString TranslatorFrench::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1958 of file translator_fr.h.
    { return QCString(members)+" hrits de "+what; }
trInheritedFrom() [2/2]
virtual QCString TranslatorFrench::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1958 of file translator_fr.h.
    { return QCString(members)+" hrits de "+what; }
trInheritsList() [1/2]
virtual QCString TranslatorFrench::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 745 of file translator_fr.h.
    {
      return "Est drive de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorFrench::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 745 of file translator_fr.h.
    {
      return "Est drive de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorFrench::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 929 of file translator_fr.h.
    {
      return "Valeur initiale :";
    }
trInitialValue() [2/2]
virtual QCString TranslatorFrench::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 929 of file translator_fr.h.
    {
      return "Valeur initiale :";
    }
trInstanceMethods() [1/2]
virtual QCString TranslatorFrench::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 2010 of file translator_fr.h.
    {
      return "Mthodes d'instance";
    }
trInstanceMethods() [2/2]
virtual QCString TranslatorFrench::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 2010 of file translator_fr.h.
    {
      return "Mthodes d'instance";
    }
trInterfaceDocumentation() [1/2]
virtual QCString TranslatorFrench::trInterfaceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2243 of file translator_fr.h.
    {
        return "Documentation des interfaces";
    }
trInterfaceDocumentation() [2/2]
virtual QCString TranslatorFrench::trInterfaceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2243 of file translator_fr.h.
    {
        return "Documentation des interfaces";
    }
trInterfaceHierarchy() [1/2]
virtual QCString TranslatorFrench::trInterfaceHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2235 of file translator_fr.h.
    {
        return "Hirarchies des interfaces";
    }
trInterfaceHierarchy() [2/2]
virtual QCString TranslatorFrench::trInterfaceHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2235 of file translator_fr.h.
    {
        return "Hirarchies des interfaces";
    }
trInterfaceHierarchyDescription() [1/2]
virtual QCString TranslatorFrench::trInterfaceHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2239 of file translator_fr.h.
    {
        return "Cette liste d'hritage est classe approximativement par ordre alphabtique :";
    }
trInterfaceHierarchyDescription() [2/2]
virtual QCString TranslatorFrench::trInterfaceHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2239 of file translator_fr.h.
    {
        return "Cette liste d'hritage est classe approximativement par ordre alphabtique :";
    }
trInterfaceIndex() [1/2]
virtual QCString TranslatorFrench::trInterfaceIndex () [inline], [virtual]
Implements Translator.
Definition at line 2223 of file translator_fr.h.
    {
        return "Index des interfaces";
    }
trInterfaceIndex() [2/2]
virtual QCString TranslatorFrench::trInterfaceIndex () [inline], [virtual]
Implements Translator.
Definition at line 2223 of file translator_fr.h.
    {
        return "Index des interfaces";
    }
trInterfaceList() [1/2]
virtual QCString TranslatorFrench::trInterfaceList () [inline], [virtual]
Implements Translator.
Definition at line 2227 of file translator_fr.h.
    {
        return "Liste des interfaces";
    }
trInterfaceList() [2/2]
virtual QCString TranslatorFrench::trInterfaceList () [inline], [virtual]
Implements Translator.
Definition at line 2227 of file translator_fr.h.
    {
        return "Liste des interfaces";
    }
trInterfaceListDescription() [1/2]
virtual QCString TranslatorFrench::trInterfaceListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2231 of file translator_fr.h.
    {
        return "Liste des interfaces avec une brve description :";
    }
trInterfaceListDescription() [2/2]
virtual QCString TranslatorFrench::trInterfaceListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2231 of file translator_fr.h.
    {
        return "Liste des interfaces avec une brve description :";
    }
trInterfaces() [1/2]
virtual QCString TranslatorFrench::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 2027 of file translator_fr.h.
    { return "Interfaces exportes"; }
trInterfaces() [2/2]
virtual QCString TranslatorFrench::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 2027 of file translator_fr.h.
    { return "Interfaces exportes"; }
trInvariant() [1/2]
virtual QCString TranslatorFrench::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 924 of file translator_fr.h.
    {
      return "Invariant";
    }
trInvariant() [2/2]
virtual QCString TranslatorFrench::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 924 of file translator_fr.h.
    {
      return "Invariant";
    }
trISOLang() [1/2]
virtual QCString TranslatorFrench::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 138 of file translator_fr.h.
    {
      return "fr";
    }
trISOLang() [2/2]
virtual QCString TranslatorFrench::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 138 of file translator_fr.h.
    {
      return "fr";
    }
trLegend() [1/2]
virtual QCString TranslatorFrench::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1125 of file translator_fr.h.
    {
      return "lgende";
    }
trLegend() [2/2]
virtual QCString TranslatorFrench::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1125 of file translator_fr.h.
    {
      return "lgende";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorFrench::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 1060 of file translator_fr.h.
    {
      return
        "Cette page explique comment interprter les graphes gnrs "
        "par doxygen.<p>\n"
        "Considrez l'exemple suivant :\n"
        "\\code\n"
        "/*! Classe invisible cause d'une troncature */\n"
        "class Invisible { };\n\n"
        "/*! Classe tronque, la relation d'hritage est masque */\n"
        "class Truncated : public Invisible { };\n\n"
        "/*! Classe non documente avec des commentaires Doxygen */\n"
        "class Undocumented { };\n\n"
        "/*! Classe drive par hritage public */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! Un modle de classe */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Classe drive par hritage protg */\n"
        "class ProtectedBase { };\n\n"
        "/*! Classe drive par hritage priv */\n"
        "class PrivateBase { };\n\n"
        "/*! Classe utilise par la classe drive */\n"
        "class Used { };\n\n"
        "/*! Super-classe qui hrite de plusieurs autres classes */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Cela aboutira au graphe suivant :"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        "Les rectangles du graphe ci-dessus ont la signification suivante :\n"
        "</p>\n"
        "<ul>\n"
        "<li>Un rectangle plein noir reprsente la structure ou la classe pour laquelle "
        "le graphe est gnr.\n"
        "<li>Un rectangle avec un bord noir indique une classe ou une structure documente.\n"
        "<li>Un rectangle avec un bord gris indique une classe ou une structure non documente.\n"
        "<li>Un rectangle avec un bord rouge indique une structure ou une classe documente\n"
        "pour laquelle des relations d'hritage ou de collaboration manquent. Un graphe est "
        "tronqu s'il n'entre pas dans les limites spcifies."
        "</ul>\n"
        "<p>\n"
        "Les flches ont la signification suivante :\n"
        "</p>\n"
        "<ul>\n"
        "<li>Une bleu fonc est utilise pour visualiser une relation d'hritage publique "
        "entre deux classes.\n"
        "<li>Une flche vert fonc est utilise pour une relation d'hritage protge.\n"
        "<li>Une flche rouge fonc est utilise pour une relation d'hritage prive.\n"
        "<li>Une flche violette en pointills est utilise si une classe est contenue ou "
        "utilise par une autre classe. La flche est tiquete avec la ou les variable(s) "
        "qui permettent d'accder la classe ou structure pointe. \n"
        "<li>Une flche jaune en pointills indique une relation entre un modle d'instance et "
        "le modle de classe duquel il est instanci. La flche est tiquete avec "
        "les paramtres de modle de l'instance.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorFrench::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 1060 of file translator_fr.h.
    {
      return
        "Cette page explique comment interprter les graphes gnrs "
        "par doxygen.<p>\n"
        "Considrez l'exemple suivant :\n"
        "\\code\n"
        "/*! Classe invisible cause d'une troncature */\n"
        "class Invisible { };\n\n"
        "/*! Classe tronque, la relation d'hritage est masque */\n"
        "class Truncated : public Invisible { };\n\n"
        "/*! Classe non documente avec des commentaires Doxygen */\n"
        "class Undocumented { };\n\n"
        "/*! Classe drive par hritage public */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! Un modle de classe */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Classe drive par hritage protg */\n"
        "class ProtectedBase { };\n\n"
        "/*! Classe drive par hritage priv */\n"
        "class PrivateBase { };\n\n"
        "/*! Classe utilise par la classe drive */\n"
        "class Used { };\n\n"
        "/*! Super-classe qui hrite de plusieurs autres classes */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Cela aboutira au graphe suivant :"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        "Les rectangles du graphe ci-dessus ont la signification suivante :\n"
        "</p>\n"
        "<ul>\n"
        "<li>Un rectangle plein noir reprsente la structure ou la classe pour laquelle "
        "le graphe est gnr.\n"
        "<li>Un rectangle avec un bord noir indique une classe ou une structure documente.\n"
        "<li>Un rectangle avec un bord gris indique une classe ou une structure non documente.\n"
        "<li>Un rectangle avec un bord rouge indique une structure ou une classe documente\n"
        "pour laquelle des relations d'hritage ou de collaboration manquent. Un graphe est "
        "tronqu s'il n'entre pas dans les limites spcifies."
        "</ul>\n"
        "<p>\n"
        "Les flches ont la signification suivante :\n"
        "</p>\n"
        "<ul>\n"
        "<li>Une bleu fonc est utilise pour visualiser une relation d'hritage publique "
        "entre deux classes.\n"
        "<li>Une flche vert fonc est utilise pour une relation d'hritage protge.\n"
        "<li>Une flche rouge fonc est utilise pour une relation d'hritage prive.\n"
        "<li>Une flche violette en pointills est utilise si une classe est contenue ou "
        "utilise par une autre classe. La flche est tiquete avec la ou les variable(s) "
        "qui permettent d'accder la classe ou structure pointe. \n"
        "<li>Une flche jaune en pointills indique une relation entre un modle d'instance et "
        "le modle de classe duquel il est instanci. La flche est tiquete avec "
        "les paramtres de modle de l'instance.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorFrench::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 1053 of file translator_fr.h.
    {
      return "Lgende du graphe";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorFrench::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 1053 of file translator_fr.h.
    {
      return "Lgende du graphe";
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorFrench::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 191 of file translator_fr.h.
    { return "Liste de tous les membres"; }
trListOfAllMembers() [2/2]
virtual QCString TranslatorFrench::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 191 of file translator_fr.h.
    { return "Liste de tous les membres"; }
trLoading() [1/2]
virtual QCString TranslatorFrench::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1819 of file translator_fr.h.
    {
      return "Chargement...";
    }
trLoading() [2/2]
virtual QCString TranslatorFrench::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1819 of file translator_fr.h.
    {
      return "Chargement...";
    }
trMainPage() [1/2]
virtual QCString TranslatorFrench::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 853 of file translator_fr.h.
    { return "Page principale"; }
trMainPage() [2/2]
virtual QCString TranslatorFrench::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 853 of file translator_fr.h.
    { return "Page principale"; }
trMember() [1/2]
virtual QCString TranslatorFrench::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1321 of file translator_fr.h.
    {
      QCString result((first_capital ? "Membre" : "membre"));
      if (!singular) result+="s";
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorFrench::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1321 of file translator_fr.h.
    {
      QCString result((first_capital ? "Membre" : "membre"));
      if (!singular) result+="s";
      return result;
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorFrench::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 174 of file translator_fr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentation des champs";
      }
      else
      {
        return "Documentation des donnes membres";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorFrench::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 174 of file translator_fr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Documentation des champs";
      }
      else
      {
        return "Documentation des donnes membres";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorFrench::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 166 of file translator_fr.h.
    { return "Documentation des numrations membres"; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorFrench::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 166 of file translator_fr.h.
    { return "Documentation des numrations membres"; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorFrench::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 170 of file translator_fr.h.
    { return "Documentation des fonctions membres"; }
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorFrench::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 170 of file translator_fr.h.
    { return "Documentation des fonctions membres"; }
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorFrench::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1611 of file translator_fr.h.
    { return "Documentation des fonctions/subroutines membres"; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorFrench::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1611 of file translator_fr.h.
    { return "Documentation des fonctions/subroutines membres"; }
trMemberList() [1/2]
virtual QCString TranslatorFrench::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 195 of file translator_fr.h.
    { return "Liste des membres"; }
trMemberList() [2/2]
virtual QCString TranslatorFrench::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 195 of file translator_fr.h.
    { return "Liste des membres"; }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorFrench::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 162 of file translator_fr.h.
    { return "Documentation des dfinitions de type membres"; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorFrench::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 162 of file translator_fr.h.
    { return "Documentation des dfinitions de type membres"; }
trMethodDocumentation() [1/2]
virtual QCString TranslatorFrench::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 2017 of file translator_fr.h.
    {
      return "Documentation des mthodes";
    }
trMethodDocumentation() [2/2]
virtual QCString TranslatorFrench::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 2017 of file translator_fr.h.
    {
      return "Documentation des mthodes";
    }
trModule() [1/2]
virtual QCString TranslatorFrench::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1749 of file translator_fr.h.
    {
      QCString result((first_capital ? "Module" : "module"));
      if (!singular) result+="s";
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorFrench::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1749 of file translator_fr.h.
    {
      QCString result((first_capital ? "Module" : "module"));
      if (!singular) result+="s";
      return result;
    }
trModuleDocumentation() [1/2]
virtual QCString TranslatorFrench::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 452 of file translator_fr.h.
    { return "Documentation des modules"; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorFrench::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 452 of file translator_fr.h.
    { return "Documentation des modules"; }
trModuleIndex() [1/2]
virtual QCString TranslatorFrench::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 419 of file translator_fr.h.
    { return "Index des modules"; }
trModuleIndex() [2/2]
virtual QCString TranslatorFrench::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 419 of file translator_fr.h.
    { return "Index des modules"; }
trModuleReference() [1/2]
virtual QCString TranslatorFrench::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1711 of file translator_fr.h.
    {
      QCString result="Rfrence du module ";
      result+= namespaceName;
      return result;
    }
trModuleReference() [2/2]
virtual QCString TranslatorFrench::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1711 of file translator_fr.h.
    {
      QCString result="Rfrence du module ";
      result+= namespaceName;
      return result;
    }
trModules() [1/2]
virtual QCString TranslatorFrench::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 233 of file translator_fr.h.
    { return "Modules"; }
trModules() [2/2]
virtual QCString TranslatorFrench::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 233 of file translator_fr.h.
    { return "Modules"; }
trModulesDescription() [1/2]
virtual QCString TranslatorFrench::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 409 of file translator_fr.h.
    { return "Liste de tous les modules :"; }
trModulesDescription() [2/2]
virtual QCString TranslatorFrench::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 409 of file translator_fr.h.
    { return "Liste de tous les modules :"; }
trModulesIndex() [1/2]
virtual QCString TranslatorFrench::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1742 of file translator_fr.h.
    { return "Index des modules"; }
trModulesIndex() [2/2]
virtual QCString TranslatorFrench::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1742 of file translator_fr.h.
    { return "Index des modules"; }
trModulesList() [1/2]
virtual QCString TranslatorFrench::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1677 of file translator_fr.h.
    { return "Liste des modules"; }
trModulesList() [2/2]
virtual QCString TranslatorFrench::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1677 of file translator_fr.h.
    { return "Liste des modules"; }
trModulesListDescription() [1/2]
virtual QCString TranslatorFrench::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1681 of file translator_fr.h.
    {
      QCString result="Liste de tous les modules ";
      if (!extractAll) result+="documents ";
      result+="avec une brve description :";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorFrench::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1681 of file translator_fr.h.
    {
      QCString result="Liste de tous les modules ";
      if (!extractAll) result+="documents ";
      result+="avec une brve description :";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorFrench::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1723 of file translator_fr.h.
    {
      QCString result="Liste de tous les membres ";
      if (!extractAll) result+="documents ";
      result+="du module avec des liens vers ";
      if (extractAll)
      {
        result+="la documentation du module de chaque membre :";
      }
      else
      {
        result+="les modules auxquels ils appartiennent :";
      }
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorFrench::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1723 of file translator_fr.h.
    {
      QCString result="Liste de tous les membres ";
      if (!extractAll) result+="documents ";
      result+="du module avec des liens vers ";
      if (extractAll)
      {
        result+="la documentation du module de chaque membre :";
      }
      else
      {
        result+="les modules auxquels ils appartiennent :";
      }
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorFrench::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1719 of file translator_fr.h.
    { return "Membres du module"; }
trModulesMembers() [2/2]
virtual QCString TranslatorFrench::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1719 of file translator_fr.h.
    { return "Membres du module"; }
trMonth() [1/2]
virtual QCString TranslatorFrench::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1898 of file translator_fr.h.
    {
      static const char *months_short[] = { "janv.", "fvr.", "mars", "avr.", "mai", "juin", "juil.", "aot", "sept.", "oct.", "nov.", "dc." };
      static const char *months_full[] = { "janvier", "fvrier", "mars", "avril", "mai", "juin", "juillet", "aot", "septembre", "octobre", "novembre", "dcembre" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMonth() [2/2]
virtual QCString TranslatorFrench::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1898 of file translator_fr.h.
    {
      static const char *months_short[] = { "janv.", "fvr.", "mars", "avr.", "mai", "juin", "juil.", "aot", "sept.", "oct.", "nov.", "dc." };
      static const char *months_full[] = { "janvier", "fvrier", "mars", "avril", "mai", "juin", "juillet", "aot", "septembre", "octobre", "novembre", "dcembre" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore() [1/2]
virtual QCString TranslatorFrench::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 187 of file translator_fr.h.
    { return "Plus de dtails..."; }
trMore() [2/2]
virtual QCString TranslatorFrench::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 187 of file translator_fr.h.
    { return "Plus de dtails..."; }
trNamespace() [1/2]
virtual QCString TranslatorFrench::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1287 of file translator_fr.h.
    {
      QCString result((first_capital ? "Espace" : "espace"));
      if (!singular) result+="s";
      result+=" de nommage";
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorFrench::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1287 of file translator_fr.h.
    {
      QCString result((first_capital ? "Espace" : "espace"));
      if (!singular) result+="s";
      result+=" de nommage";
      return result;
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorFrench::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 799 of file translator_fr.h.
    { return "Documentation des espaces de nommage"; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorFrench::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 799 of file translator_fr.h.
    { return "Documentation des espaces de nommage"; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorFrench::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 793 of file translator_fr.h.
    { return "Index des espaces de nommage"; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorFrench::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 793 of file translator_fr.h.
    { return "Index des espaces de nommage"; }
trNamespaceList() [1/2]
virtual QCString TranslatorFrench::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 625 of file translator_fr.h.
    { return "Liste des espaces de nommage"; }
trNamespaceList() [2/2]
virtual QCString TranslatorFrench::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 625 of file translator_fr.h.
    { return "Liste des espaces de nommage"; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorFrench::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 629 of file translator_fr.h.
    {
      QCString result="Liste de tous les espaces de nommage ";
      if (!extractAll) result+="documents ";
      result+="avec une brve description:";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorFrench::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 629 of file translator_fr.h.
    {
      QCString result="Liste de tous les espaces de nommage ";
      if (!extractAll) result+="documents ";
      result+="avec une brve description:";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorFrench::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 779 of file translator_fr.h.
    {
      QCString result="Liste de tous les membres des espaces de nommage ";
      if (!extractAll) result+="documents ";
        result+="avec des liens vers ";
      if (extractAll)
        result+="la documentation de namespace de chaque membre :";
      else
        result+="les espaces de nommage auxquels ils appartiennent :";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorFrench::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 779 of file translator_fr.h.
    {
      QCString result="Liste de tous les membres des espaces de nommage ";
      if (!extractAll) result+="documents ";
        result+="avec des liens vers ";
      if (extractAll)
        result+="la documentation de namespace de chaque membre :";
      else
        result+="les espaces de nommage auxquels ils appartiennent :";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorFrench::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 775 of file translator_fr.h.
    { return "Membres de l'espace de nommage"; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorFrench::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 775 of file translator_fr.h.
    { return "Membres de l'espace de nommage"; }
trNamespaceReference() [1/2]
virtual QCString TranslatorFrench::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 689 of file translator_fr.h.
    {
      QCString result= "Rfrence de l'espace de nommage ";
      result+=namespaceName;
      return result;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorFrench::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 689 of file translator_fr.h.
    {
      QCString result= "Rfrence de l'espace de nommage ";
      result+=namespaceName;
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorFrench::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 809 of file translator_fr.h.
    { return "Espaces de nommage"; }
trNamespaces() [2/2]
virtual QCString TranslatorFrench::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 809 of file translator_fr.h.
    { return "Espaces de nommage"; }
trNoMatches() [1/2]
virtual QCString TranslatorFrench::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1837 of file translator_fr.h.
    {
      return "Aucune correspondance";
    }
trNoMatches() [2/2]
virtual QCString TranslatorFrench::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1837 of file translator_fr.h.
    {
      return "Aucune correspondance";
    }
trNote() [1/2]
virtual QCString TranslatorFrench::trNote () [inline], [virtual]
Implements Translator.
Definition at line 959 of file translator_fr.h.
    {
      return "Note";
    }
trNote() [2/2]
virtual QCString TranslatorFrench::trNote () [inline], [virtual]
Implements Translator.
Definition at line 959 of file translator_fr.h.
    {
      return "Note";
    }
trOperationDocumentation() [1/2]
virtual QCString TranslatorFrench::trOperationDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2320 of file translator_fr.h.
    {
        return "Documentation des oprations";
    }
trOperationDocumentation() [2/2]
virtual QCString TranslatorFrench::trOperationDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2320 of file translator_fr.h.
    {
        return "Documentation des oprations";
    }
trOperations() [1/2]
virtual QCString TranslatorFrench::trOperations () [inline], [virtual]
Implements Translator.
Definition at line 2316 of file translator_fr.h.
    {
        return "Oprations";
    }
trOperations() [2/2]
virtual QCString TranslatorFrench::trOperations () [inline], [virtual]
Implements Translator.
Definition at line 2316 of file translator_fr.h.
    {
        return "Oprations";
    }
trOverloadText() [1/2]
virtual QCString TranslatorFrench::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1583 of file translator_fr.h.
    {
       return "Ceci est une fonction membre surcharge, "
              "propose par commodit. Elle diffre de la fonction "
              "ci-dessus uniquement par le(s) argument(s) qu'elle accepte.";
    }
trOverloadText() [2/2]
virtual QCString TranslatorFrench::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1583 of file translator_fr.h.
    {
       return "Ceci est une fonction membre surcharge, "
              "propose par commodit. Elle diffre de la fonction "
              "ci-dessus uniquement par le(s) argument(s) qu'elle accepte.";
    }
trPackage() [1/2]
virtual QCString TranslatorFrench::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1177 of file translator_fr.h.
    {
      return "Paquetage "+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorFrench::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1177 of file translator_fr.h.
    {
      return "Paquetage "+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorFrench::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1455 of file translator_fr.h.
    {
      return "Attributs de paquetage";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorFrench::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1455 of file translator_fr.h.
    {
      return "Attributs de paquetage";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorFrench::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1437 of file translator_fr.h.
    {
      return "Fonctions de paquetage";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorFrench::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1437 of file translator_fr.h.
    {
      return "Fonctions de paquetage";
    }
trPackageList() [1/2]
virtual QCString TranslatorFrench::trPackageList () [inline], [virtual]
Implements Translator.
Definition at line 2391 of file translator_fr.h.
    { return "Liste des paquetages"; }
trPackageList() [2/2]
virtual QCString TranslatorFrench::trPackageList () [inline], [virtual]
Implements Translator.
Definition at line 2391 of file translator_fr.h.
    { return "Liste des paquetages"; }
trPackageListDescription() [1/2]
virtual QCString TranslatorFrench::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1182 of file translator_fr.h.
    {
      return "Liste des paquetages avec une brve description (si disponible) :";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorFrench::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1182 of file translator_fr.h.
    {
      return "Liste des paquetages avec une brve description (si disponible) :";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorFrench::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1441 of file translator_fr.h.
    {
      return "Membres de paquetage";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorFrench::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1441 of file translator_fr.h.
    {
      return "Membres de paquetage";
    }
trPackages() [1/2]
virtual QCString TranslatorFrench::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1187 of file translator_fr.h.
    {
      return "Paquetages";
    }
trPackages() [2/2]
virtual QCString TranslatorFrench::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1187 of file translator_fr.h.
    {
      return "Paquetages";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorFrench::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1430 of file translator_fr.h.
    {
      return "Types de paquetage";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorFrench::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1430 of file translator_fr.h.
    {
      return "Types de paquetage";
    }
trPage() [1/2]
virtual QCString TranslatorFrench::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1310 of file translator_fr.h.
    {
      QCString result((first_capital ? "Page" : "page"));
      if (!singular) result+="s";
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorFrench::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1310 of file translator_fr.h.
    {
      QCString result((first_capital ? "Page" : "page"));
      if (!singular) result+="s";
      return result;
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorFrench::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 859 of file translator_fr.h.
    { return "p."; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorFrench::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 859 of file translator_fr.h.
    { return "p."; }
trPageIndex() [1/2]
virtual QCString TranslatorFrench::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 950 of file translator_fr.h.
    {
      return "Index des pages";
    }
trPageIndex() [2/2]
virtual QCString TranslatorFrench::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 950 of file translator_fr.h.
    {
      return "Index des pages";
    }
trPanelSynchronisationTooltip() [1/2]
virtual QCString TranslatorFrench::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1975 of file translator_fr.h.
    {
      QCString opt = enable ? "activer" : "dsactiver";
      return "cliquez pour "+opt+" la synchronisation du panel";
    }
trPanelSynchronisationTooltip() [2/2]
virtual QCString TranslatorFrench::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1975 of file translator_fr.h.
    {
      QCString opt = enable ? "activer" : "dsactiver";
      return "cliquez pour "+opt+" la synchronisation du panel";
    }
trParameters() [1/2]
virtual QCString TranslatorFrench::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 609 of file translator_fr.h.
    { return "Paramtres"; }
trParameters() [2/2]
virtual QCString TranslatorFrench::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 609 of file translator_fr.h.
    { return "Paramtres"; }
trPostcondition() [1/2]
virtual QCString TranslatorFrench::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 919 of file translator_fr.h.
    {
      return "Postcondition";
    }
trPostcondition() [2/2]
virtual QCString TranslatorFrench::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 919 of file translator_fr.h.
    {
      return "Postcondition";
    }
trPrecondition() [1/2]
virtual QCString TranslatorFrench::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 914 of file translator_fr.h.
    {
      return "Prcondition";
    }
trPrecondition() [2/2]
virtual QCString TranslatorFrench::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 914 of file translator_fr.h.
    {
      return "Prcondition";
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorFrench::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 998 of file translator_fr.h.
    {
      return "Attributs privs";
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorFrench::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 998 of file translator_fr.h.
    {
      return "Attributs privs";
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorFrench::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 710 of file translator_fr.h.
    { return "Fonctions membres prives"; }
trPrivateMembers() [2/2]
virtual QCString TranslatorFrench::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 710 of file translator_fr.h.
    { return "Fonctions membres prives"; }
trPrivateSlots() [1/2]
virtual QCString TranslatorFrench::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 712 of file translator_fr.h.
    { return "Connecteurs privs"; }
trPrivateSlots() [2/2]
virtual QCString TranslatorFrench::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 712 of file translator_fr.h.
    { return "Connecteurs privs"; }
trPrivateTypes() [1/2]
virtual QCString TranslatorFrench::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 994 of file translator_fr.h.
    {
      return "Types privs";
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorFrench::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 994 of file translator_fr.h.
    {
      return "Types privs";
    }
trProperties() [1/2]
virtual QCString TranslatorFrench::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1150 of file translator_fr.h.
    {
      return "Proprits";
    }
trProperties() [2/2]
virtual QCString TranslatorFrench::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1150 of file translator_fr.h.
    {
      return "Proprits";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorFrench::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1155 of file translator_fr.h.
    {
      return "Documentation des proprits";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorFrench::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1155 of file translator_fr.h.
    {
      return "Documentation des proprits";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorFrench::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 986 of file translator_fr.h.
    {
      return "Attributs protgs";
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorFrench::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 986 of file translator_fr.h.
    {
      return "Attributs protgs";
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorFrench::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 704 of file translator_fr.h.
    { return "Fonctions membres protges"; }
trProtectedMembers() [2/2]
virtual QCString TranslatorFrench::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 704 of file translator_fr.h.
    { return "Fonctions membres protges"; }
trProtectedSlots() [1/2]
virtual QCString TranslatorFrench::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 706 of file translator_fr.h.
    { return "Connecteurs protgs"; }
trProtectedSlots() [2/2]
virtual QCString TranslatorFrench::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 706 of file translator_fr.h.
    { return "Connecteurs protgs"; }
trProtectedTypes() [1/2]
virtual QCString TranslatorFrench::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 982 of file translator_fr.h.
    {
      return "Types protgs";
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorFrench::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 982 of file translator_fr.h.
    {
      return "Types protgs";
    }
trProvidedByCategory() [1/2]
virtual QCString TranslatorFrench::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1985 of file translator_fr.h.
    {
      return "Dclare dans la catgorie @0.";
    }
trProvidedByCategory() [2/2]
virtual QCString TranslatorFrench::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1985 of file translator_fr.h.
    {
      return "Dclare dans la catgorie @0.";
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorFrench::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 967 of file translator_fr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Champs de donnes";
      }
      else
      {
        return "Attributs publics";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorFrench::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 967 of file translator_fr.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Champs de donnes";
      }
      else
      {
        return "Attributs publics";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorFrench::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 696 of file translator_fr.h.
    { return "Fonctions membres publiques"; }
trPublicMembers() [2/2]
virtual QCString TranslatorFrench::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 696 of file translator_fr.h.
    { return "Fonctions membres publiques"; }
trPublicSlots() [1/2]
virtual QCString TranslatorFrench::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 698 of file translator_fr.h.
    { return "Connecteurs publics"; }
trPublicSlots() [2/2]
virtual QCString TranslatorFrench::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 698 of file translator_fr.h.
    { return "Connecteurs publics"; }
trPublicTypes() [1/2]
virtual QCString TranslatorFrench::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 963 of file translator_fr.h.
    {
      return "Types publics";
    }
trPublicTypes() [2/2]
virtual QCString TranslatorFrench::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 963 of file translator_fr.h.
    {
      return "Types publics";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorFrench::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 1026 of file translator_fr.h.
    {
      return "Rfrenc par";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorFrench::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 1026 of file translator_fr.h.
    {
      return "Rfrenc par";
    }
trReferenceManual() [1/2]
virtual QCString TranslatorFrench::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 487 of file translator_fr.h.
    { return "Manuel de rfrence"; }
trReferenceManual() [2/2]
virtual QCString TranslatorFrench::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 487 of file translator_fr.h.
    { return "Manuel de rfrence"; }
trReferences() [1/2]
virtual QCString TranslatorFrench::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1358 of file translator_fr.h.
    {
      return "Rfrences";
    }
trReferences() [2/2]
virtual QCString TranslatorFrench::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1358 of file translator_fr.h.
    {
      return "Rfrences";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorFrench::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 761 of file translator_fr.h.
    {
      return "Rimplmente partir de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorFrench::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 761 of file translator_fr.h.
    {
      return "Rimplmente partir de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorFrench::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 769 of file translator_fr.h.
    {
      return "Rimplmente dans "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorFrench::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 769 of file translator_fr.h.
    {
      return "Rimplmente dans "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorFrench::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 650 of file translator_fr.h.
    { return "Documentation des fonctions amies et associes"; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorFrench::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 650 of file translator_fr.h.
    { return "Documentation des fonctions amies et associes"; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorFrench::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 150 of file translator_fr.h.
    { return "Fonctions associes"; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorFrench::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 150 of file translator_fr.h.
    { return "Fonctions associes"; }
trRelatedPages() [1/2]
virtual QCString TranslatorFrench::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 284 of file translator_fr.h.
    { return "Pages associes"; }
trRelatedPages() [2/2]
virtual QCString TranslatorFrench::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 284 of file translator_fr.h.
    { return "Pages associes"; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorFrench::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 405 of file translator_fr.h.
    { return "Liste de toutes les pages de documentation associes :"; }
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorFrench::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 405 of file translator_fr.h.
    { return "Liste de toutes les pages de documentation associes :"; }
trRelatedSubscript() [1/2]
virtual QCString TranslatorFrench::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 154 of file translator_fr.h.
    { return "(Notez que ce ne sont pas des fonctions membres)"; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorFrench::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 154 of file translator_fr.h.
    { return "(Notez que ce ne sont pas des fonctions membres)"; }
trRemarks() [1/2]
virtual QCString TranslatorFrench::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 1030 of file translator_fr.h.
    {
      return "Remarques";
    }
trRemarks() [2/2]
virtual QCString TranslatorFrench::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 1030 of file translator_fr.h.
    {
      return "Remarques";
    }
trReturns() [1/2]
virtual QCString TranslatorFrench::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 601 of file translator_fr.h.
    { return "Renvoie"; }
trReturns() [2/2]
virtual QCString TranslatorFrench::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 601 of file translator_fr.h.
    { return "Renvoie"; }
trReturnValues() [1/2]
virtual QCString TranslatorFrench::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 848 of file translator_fr.h.
    { return "Valeurs retournes"; }
trReturnValues() [2/2]
virtual QCString TranslatorFrench::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 848 of file translator_fr.h.
    { return "Valeurs retournes"; }
trRTFansicp() [1/2]
virtual QCString TranslatorFrench::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1241 of file translator_fr.h.
    {
      return "1252";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorFrench::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1241 of file translator_fr.h.
    {
      return "1252";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorFrench::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1250 of file translator_fr.h.
    {
      return "0";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorFrench::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1250 of file translator_fr.h.
    {
      return "0";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorFrench::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1256 of file translator_fr.h.
    {
      return "Index";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorFrench::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1256 of file translator_fr.h.
    {
      return "Index";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorFrench::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1390 of file translator_fr.h.
    {
      return "Table des matires";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorFrench::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1390 of file translator_fr.h.
    {
      return "Table des matires";
    }
trSearch() [1/2]
virtual QCString TranslatorFrench::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 292 of file translator_fr.h.
    { return "Recherche"; }
trSearch() [2/2]
virtual QCString TranslatorFrench::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 292 of file translator_fr.h.
    { return "Recherche"; }
trSearching() [1/2]
virtual QCString TranslatorFrench::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1831 of file translator_fr.h.
    {
      return "Recherche...";
    }
trSearching() [2/2]
virtual QCString TranslatorFrench::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1831 of file translator_fr.h.
    {
      return "Recherche...";
    }
trSearchMatches() [1/2]
virtual QCString TranslatorFrench::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1522 of file translator_fr.h.
    {
      return "Correspondances :";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorFrench::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1522 of file translator_fr.h.
    {
      return "Correspondances :";
    }
trSearchResults() [1/2]
virtual QCString TranslatorFrench::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1503 of file translator_fr.h.
    {
      if (numDocuments==0)
      {
        return "Dsol, aucun document ne correspond votre requte.";
      }
      else if (numDocuments==1)
      {
        return "Trouv <b>1</b> document correspondant votre requte.";
      }
      else
      {
        return "Trouv <b>$num</b> documents correspondant votre requte. "
               "Class par ordre de pertinence dcroissant.";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorFrench::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1503 of file translator_fr.h.
    {
      if (numDocuments==0)
      {
        return "Dsol, aucun document ne correspond votre requte.";
      }
      else if (numDocuments==1)
      {
        return "Trouv <b>1</b> document correspondant votre requte.";
      }
      else
      {
        return "Trouv <b>$num</b> documents correspondant votre requte. "
               "Class par ordre de pertinence dcroissant.";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorFrench::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1491 of file translator_fr.h.
    {
      return "Rsultats de la recherche";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorFrench::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1491 of file translator_fr.h.
    {
      return "Rsultats de la recherche";
    }
trSeeAlso() [1/2]
virtual QCString TranslatorFrench::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 605 of file translator_fr.h.
    { return "Voir galement"; }
trSeeAlso() [2/2]
virtual QCString TranslatorFrench::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 605 of file translator_fr.h.
    { return "Voir galement"; }
trSequenceDocumentation() [1/2]
virtual QCString TranslatorFrench::trSequenceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2207 of file translator_fr.h.
    {
        return "Documentation des squences";
    }
trSequenceDocumentation() [2/2]
virtual QCString TranslatorFrench::trSequenceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2207 of file translator_fr.h.
    {
        return "Documentation des squences";
    }
trSequences() [1/2]
virtual QCString TranslatorFrench::trSequences () [inline], [virtual]
Implements Translator.
Definition at line 2203 of file translator_fr.h.
    {
        return "Squences";
    }
trSequences() [2/2]
virtual QCString TranslatorFrench::trSequences () [inline], [virtual]
Implements Translator.
Definition at line 2203 of file translator_fr.h.
    {
        return "Squences";
    }
trServiceGeneratedFromFiles() [1/2]
virtual QCString TranslatorFrench::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 2060 of file translator_fr.h.
    {
      // single is true implies a single file
      QCString result="La documentation pour ce service "
                                "a t gnre par ";
      if (single) result+="le fichier suivant :"; else result+="les fichiers suivants :";
      return result;
    }
trServiceGeneratedFromFiles() [2/2]
virtual QCString TranslatorFrench::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 2060 of file translator_fr.h.
    {
      // single is true implies a single file
      QCString result="La documentation pour ce service "
                                "a t gnre par ";
      if (single) result+="le fichier suivant :"; else result+="les fichiers suivants :";
      return result;
    }
trServiceReference() [1/2]
virtual QCString TranslatorFrench::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 2046 of file translator_fr.h.
    {
      QCString result="Rfrence du service ";
      result+=sName;
      return result;
    }
trServiceReference() [2/2]
virtual QCString TranslatorFrench::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 2046 of file translator_fr.h.
    {
      QCString result="Rfrence du service ";
      result+=sName;
      return result;
    }
trServices() [1/2]
virtual QCString TranslatorFrench::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 2031 of file translator_fr.h.
    { return "Services inclus"; }
trServices() [2/2]
virtual QCString TranslatorFrench::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 2031 of file translator_fr.h.
    { return "Services inclus"; }
trSignals() [1/2]
virtual QCString TranslatorFrench::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 700 of file translator_fr.h.
    { return "Signaux"; }
trSignals() [2/2]
virtual QCString TranslatorFrench::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 700 of file translator_fr.h.
    { return "Signaux"; }
trSince() [1/2]
virtual QCString TranslatorFrench::trSince () [inline], [virtual]
Implements Translator.
Definition at line 1043 of file translator_fr.h.
    {
      return "Depuis";
    }
trSince() [2/2]
virtual QCString TranslatorFrench::trSince () [inline], [virtual]
Implements Translator.
Definition at line 1043 of file translator_fr.h.
    {
      return "Depuis";
    }
trSingletonGeneratedFromFiles() [1/2]
virtual QCString TranslatorFrench::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 2069 of file translator_fr.h.
    {
      // single is true implies a single file
      QCString result="La documentation pour ce singleton "
                                "a t gnre par ";
      if (single) result+="le fichier suivant :"; else result+="les fichiers suivants :";
      return result;
    }
trSingletonGeneratedFromFiles() [2/2]
virtual QCString TranslatorFrench::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 2069 of file translator_fr.h.
    {
      // single is true implies a single file
      QCString result="La documentation pour ce singleton "
                                "a t gnre par ";
      if (single) result+="le fichier suivant :"; else result+="les fichiers suivants :";
      return result;
    }
trSingletonReference() [1/2]
virtual QCString TranslatorFrench::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 2053 of file translator_fr.h.
    {
      QCString result="Rfrence du singleton ";
      result+=sName;
      return result;
    }
trSingletonReference() [2/2]
virtual QCString TranslatorFrench::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 2053 of file translator_fr.h.
    {
      QCString result="Rfrence du singleton ";
      result+=sName;
      return result;
    }
trSliceInterfaces() [1/2]
virtual QCString TranslatorFrench::trSliceInterfaces () [inline], [virtual]
Implements Translator.
Definition at line 2219 of file translator_fr.h.
    {
        return "Interfaces";
    }
trSliceInterfaces() [2/2]
virtual QCString TranslatorFrench::trSliceInterfaces () [inline], [virtual]
Implements Translator.
Definition at line 2219 of file translator_fr.h.
    {
        return "Interfaces";
    }
trSourceFile() [1/2]
virtual QCString TranslatorFrench::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1533 of file translator_fr.h.
    {
      return " Fichier source de " + filename;
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorFrench::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1533 of file translator_fr.h.
    {
      return " Fichier source de " + filename;
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorFrench::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1462 of file translator_fr.h.
    {
      return "Attributs statiques de paquetage";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorFrench::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1462 of file translator_fr.h.
    {
      return "Attributs statiques de paquetage";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorFrench::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1448 of file translator_fr.h.
    {
      return "Fonctions statiques de paquetage";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorFrench::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1448 of file translator_fr.h.
    {
      return "Fonctions statiques de paquetage";
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorFrench::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1002 of file translator_fr.h.
    {
      return "Attributs privs statiques";
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorFrench::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1002 of file translator_fr.h.
    {
      return "Attributs privs statiques";
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorFrench::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 714 of file translator_fr.h.
    { return "Fonctions membres prives statiques"; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorFrench::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 714 of file translator_fr.h.
    { return "Fonctions membres prives statiques"; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorFrench::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 990 of file translator_fr.h.
    {
      return "Attributs protgs statiques";
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorFrench::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 990 of file translator_fr.h.
    {
      return "Attributs protgs statiques";
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorFrench::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 708 of file translator_fr.h.
    { return "Fonctions membres protges statiques"; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorFrench::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 708 of file translator_fr.h.
    { return "Fonctions membres protges statiques"; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorFrench::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 978 of file translator_fr.h.
    {
      return "Attributs publics statiques";
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorFrench::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 978 of file translator_fr.h.
    {
      return "Attributs publics statiques";
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorFrench::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 702 of file translator_fr.h.
    { return "Fonctions membres publiques statiques"; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorFrench::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 702 of file translator_fr.h.
    { return "Fonctions membres publiques statiques"; }
trStructDocumentation() [1/2]
virtual QCString TranslatorFrench::trStructDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2263 of file translator_fr.h.
    {
        return "Documentation des structures";
    }
trStructDocumentation() [2/2]
virtual QCString TranslatorFrench::trStructDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2263 of file translator_fr.h.
    {
        return "Documentation des structures";
    }
trStructIndex() [1/2]
virtual QCString TranslatorFrench::trStructIndex () [inline], [virtual]
Implements Translator.
Definition at line 2251 of file translator_fr.h.
    {
        return "Index des structures";
    }
trStructIndex() [2/2]
virtual QCString TranslatorFrench::trStructIndex () [inline], [virtual]
Implements Translator.
Definition at line 2251 of file translator_fr.h.
    {
        return "Index des structures";
    }
trStructList() [1/2]
virtual QCString TranslatorFrench::trStructList () [inline], [virtual]
Implements Translator.
Definition at line 2255 of file translator_fr.h.
    {
        return "Liste des structures";
    }
trStructList() [2/2]
virtual QCString TranslatorFrench::trStructList () [inline], [virtual]
Implements Translator.
Definition at line 2255 of file translator_fr.h.
    {
        return "Liste des structures";
    }
trStructListDescription() [1/2]
virtual QCString TranslatorFrench::trStructListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2259 of file translator_fr.h.
    {
        return "Liste des structures avec une brve description :";
    }
trStructListDescription() [2/2]
virtual QCString TranslatorFrench::trStructListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2259 of file translator_fr.h.
    {
        return "Liste des structures avec une brve description :";
    }
trStructs() [1/2]
virtual QCString TranslatorFrench::trStructs () [inline], [virtual]
Implements Translator.
Definition at line 2247 of file translator_fr.h.
    {
        return "Structures";
    }
trStructs() [2/2]
virtual QCString TranslatorFrench::trStructs () [inline], [virtual]
Implements Translator.
Definition at line 2247 of file translator_fr.h.
    {
        return "Structures";
    }
trSubprogram() [1/2]
virtual QCString TranslatorFrench::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1795 of file translator_fr.h.
    {
      QCString result((first_capital ? "Sous-programme" : "sous-programme"));
      if (!singular) result+="s";
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorFrench::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1795 of file translator_fr.h.
    {
      QCString result((first_capital ? "Sous-programme" : "sous-programme"));
      if (!singular) result+="s";
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorFrench::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1667 of file translator_fr.h.
    { return "Documentation de la fonction/subroutine"; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorFrench::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1667 of file translator_fr.h.
    { return "Documentation de la fonction/subroutine"; }
trSubprograms() [1/2]
virtual QCString TranslatorFrench::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1661 of file translator_fr.h.
    { return "Fonctions/Subroutines"; }
trSubprograms() [2/2]
virtual QCString TranslatorFrench::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1661 of file translator_fr.h.
    { return "Fonctions/Subroutines"; }
trTemplateParameters() [1/2]
virtual QCString TranslatorFrench::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1938 of file translator_fr.h.
    { return "Paramtres du template"; }
trTemplateParameters() [2/2]
virtual QCString TranslatorFrench::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1938 of file translator_fr.h.
    { return "Paramtres du template"; }
trTest() [1/2]
virtual QCString TranslatorFrench::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1135 of file translator_fr.h.
    {
      return "Test";
    }
trTest() [2/2]
virtual QCString TranslatorFrench::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1135 of file translator_fr.h.
    {
      return "Test";
    }
trTestList() [1/2]
virtual QCString TranslatorFrench::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1140 of file translator_fr.h.
    {
      return "Liste des tests";
    }
trTestList() [2/2]
virtual QCString TranslatorFrench::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1140 of file translator_fr.h.
    {
      return "Liste des tests";
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorFrench::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 199 of file translator_fr.h.
    { return "Liste complte des membres de "; }
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorFrench::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 199 of file translator_fr.h.
    { return "Liste complte des membres de "; }
trTodo() [1/2]
virtual QCString TranslatorFrench::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 1012 of file translator_fr.h.
    {
      return "A faire";
    }
trTodo() [2/2]
virtual QCString TranslatorFrench::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 1012 of file translator_fr.h.
    {
      return "A faire";
    }
trTodoList() [1/2]
virtual QCString TranslatorFrench::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 1017 of file translator_fr.h.
    {
      return "Liste des choses faire";
    }
trTodoList() [2/2]
virtual QCString TranslatorFrench::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 1017 of file translator_fr.h.
    {
      return "Liste des choses faire";
    }
trType() [1/2]
virtual QCString TranslatorFrench::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1784 of file translator_fr.h.
    {
      QCString result((first_capital ? "Type" : "type"));
      if (!singular) result+="s";
      return result;
    }
trType() [2/2]
virtual QCString TranslatorFrench::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1784 of file translator_fr.h.
    {
      QCString result((first_capital ? "Type" : "type"));
      if (!singular) result+="s";
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorFrench::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1803 of file translator_fr.h.
    {
      return "Contraintes de type";
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorFrench::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1803 of file translator_fr.h.
    {
      return "Contraintes de type";
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorFrench::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 535 of file translator_fr.h.
    { return "Documentation des dfinitions de type"; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorFrench::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 535 of file translator_fr.h.
    { return "Documentation des dfinitions de type"; }
trTypedefs() [1/2]
virtual QCString TranslatorFrench::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 499 of file translator_fr.h.
    { return "Dfinitions de type"; }
trTypedefs() [2/2]
virtual QCString TranslatorFrench::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 499 of file translator_fr.h.
    { return "Dfinitions de type"; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorFrench::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1655 of file translator_fr.h.
    { return "Documentation du type de donnes"; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorFrench::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1655 of file translator_fr.h.
    { return "Documentation du type de donnes"; }
trVariableDocumentation() [1/2]
virtual QCString TranslatorFrench::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 553 of file translator_fr.h.
    { return "Documentation des variables"; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorFrench::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 553 of file translator_fr.h.
    { return "Documentation des variables"; }
trVariables() [1/2]
virtual QCString TranslatorFrench::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 517 of file translator_fr.h.
    { return "Variables"; }
trVariables() [2/2]
virtual QCString TranslatorFrench::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 517 of file translator_fr.h.
    { return "Variables"; }
trVersion() [1/2]
virtual QCString TranslatorFrench::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 593 of file translator_fr.h.
    { return "Version"; }
trVersion() [2/2]
virtual QCString TranslatorFrench::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 593 of file translator_fr.h.
    { return "Version"; }
trVhdlType() [1/2]
virtual QCString TranslatorFrench::trVhdlType (uint64 type, bool single) [inline], [virtual]
VHDL type
Implements Translator.
Definition at line 2107 of file translator_fr.h.
    {
      switch(type)
      {
        case VhdlDocGen::LIBRARY:
          if (single) return "Librairie";
          else return "Librairies";
        case VhdlDocGen::PACKAGE:
          if (single) return "Paquetage";
          else return "Paquetages";
        case VhdlDocGen::SIGNAL:
          if (single) return "Signal";
          else return "Signaux";
        case VhdlDocGen::COMPONENT:
          if (single) return "Composant";
          else return "Composants";
        case VhdlDocGen::CONSTANT:
          if (single) return "Constante";
          else return "Constantes";
        case VhdlDocGen::ENTITY:
          if (single) return "Entit";
          else return "Entits";
        case VhdlDocGen::TYPE:
          if (single) return "Type";
          else return "Types";
        case VhdlDocGen::SUBTYPE:
          if (single) return "Sous-type";
          else return "Sous-types";
        case VhdlDocGen::FUNCTION:
          if (single) return "Fonction";
          else return "Fonctions";
        case VhdlDocGen::RECORD:
          if (single) return "Enregistrement";
          else return "Enregistrements";
        case VhdlDocGen::PROCEDURE:
          if (single) return "Procdure";
          else return "Procdures";
        case VhdlDocGen::ARCHITECTURE:
          if (single) return "Architecture";
          else return "Architectures";
        case VhdlDocGen::ATTRIBUTE:
          if (single) return "Attribut";
          else return "Attributs";
        case VhdlDocGen::PROCESS:
          if (single) return "Process";
          else return "Processes";
        case VhdlDocGen::PORT:
          if (single) return "Port";
          else return "Ports";
        case VhdlDocGen::USE:
          if (single) return "Clause d'utilisation";
          else return "Clauses d'utilisation";
        case VhdlDocGen::GENERIC:
          if (single) return "Generique";
          else return "Generiques";
        case VhdlDocGen::PACKAGE_BODY:
          return "Corps du paquetage";
        case VhdlDocGen::UNITS:
          return "Units";
        case VhdlDocGen::SHAREDVARIABLE:
          if (single) return "Variable partage";
          else return "Variables partages";
        case VhdlDocGen::VFILE:
          if (single) return "Fichier";
          else return "Fichiers";
        case VhdlDocGen::GROUP:
          if (single) return "Groupe";
          else return "Groupes";
        case VhdlDocGen::INSTANTIATION:
          if (single) return "Instanciation";
          else return "Instanciations";
        case VhdlDocGen::ALIAS:
          if (single) return "Alias";
          else return "Alias";
        case VhdlDocGen::CONFIG:
          if (single) return "Configuration";
          else return "Configurations";
        case VhdlDocGen::MISCELLANEOUS:
          return "Divers";
        case VhdlDocGen::UCF_CONST:
          return "Contraintes";
        default:
          return "Classe";
      }
    }
References VhdlDocGen::ALIAS, VhdlDocGen::ARCHITECTURE, VhdlDocGen::ATTRIBUTE, VhdlDocGen::COMPONENT, VhdlDocGen::CONFIG, VhdlDocGen::CONSTANT, VhdlDocGen::ENTITY, VhdlDocGen::FUNCTION, VhdlDocGen::GENERIC, VhdlDocGen::GROUP, VhdlDocGen::INSTANTIATION, VhdlDocGen::LIBRARY, VhdlDocGen::MISCELLANEOUS, VhdlDocGen::PACKAGE, VhdlDocGen::PACKAGE_BODY, VhdlDocGen::PORT, VhdlDocGen::PROCEDURE, VhdlDocGen::PROCESS, VhdlDocGen::RECORD, VhdlDocGen::SHAREDVARIABLE, VhdlDocGen::SIGNAL, VhdlDocGen::SUBTYPE, VhdlDocGen::TYPE, VhdlDocGen::UCF_CONST, VhdlDocGen::UNITS, VhdlDocGen::USE, and VhdlDocGen::VFILE.
trVhdlType() [2/2]
virtual QCString TranslatorFrench::trVhdlType (uint64 type, bool single) [inline], [virtual]
VHDL type
Implements Translator.
Definition at line 2107 of file translator_fr.h.
    {
      switch(type)
      {
        case VhdlDocGen::LIBRARY:
          if (single) return "Librairie";
          else return "Librairies";
        case VhdlDocGen::PACKAGE:
          if (single) return "Paquetage";
          else return "Paquetages";
        case VhdlDocGen::SIGNAL:
          if (single) return "Signal";
          else return "Signaux";
        case VhdlDocGen::COMPONENT:
          if (single) return "Composant";
          else return "Composants";
        case VhdlDocGen::CONSTANT:
          if (single) return "Constante";
          else return "Constantes";
        case VhdlDocGen::ENTITY:
          if (single) return "Entit";
          else return "Entits";
        case VhdlDocGen::TYPE:
          if (single) return "Type";
          else return "Types";
        case VhdlDocGen::SUBTYPE:
          if (single) return "Sous-type";
          else return "Sous-types";
        case VhdlDocGen::FUNCTION:
          if (single) return "Fonction";
          else return "Fonctions";
        case VhdlDocGen::RECORD:
          if (single) return "Enregistrement";
          else return "Enregistrements";
        case VhdlDocGen::PROCEDURE:
          if (single) return "Procdure";
          else return "Procdures";
        case VhdlDocGen::ARCHITECTURE:
          if (single) return "Architecture";
          else return "Architectures";
        case VhdlDocGen::ATTRIBUTE:
          if (single) return "Attribut";
          else return "Attributs";
        case VhdlDocGen::PROCESS:
          if (single) return "Process";
          else return "Processes";
        case VhdlDocGen::PORT:
          if (single) return "Port";
          else return "Ports";
        case VhdlDocGen::USE:
          if (single) return "Clause d'utilisation";
          else return "Clauses d'utilisation";
        case VhdlDocGen::GENERIC:
          if (single) return "Generique";
          else return "Generiques";
        case VhdlDocGen::PACKAGE_BODY:
          return "Corps du paquetage";
        case VhdlDocGen::UNITS:
          return "Units";
        case VhdlDocGen::SHAREDVARIABLE:
          if (single) return "Variable partage";
          else return "Variables partages";
        case VhdlDocGen::VFILE:
          if (single) return "Fichier";
          else return "Fichiers";
        case VhdlDocGen::GROUP:
          if (single) return "Groupe";
          else return "Groupes";
        case VhdlDocGen::INSTANTIATION:
          if (single) return "Instanciation";
          else return "Instanciations";
        case VhdlDocGen::ALIAS:
          if (single) return "Alias";
          else return "Alias";
        case VhdlDocGen::CONFIG:
          if (single) return "Configuration";
          else return "Configurations";
        case VhdlDocGen::MISCELLANEOUS:
          return "Divers";
        case VhdlDocGen::UCF_CONST:
          return "Contraintes";
        default:
          return "Classe";
      }
    }
References VhdlDocGen::ALIAS, VhdlDocGen::ARCHITECTURE, VhdlDocGen::ATTRIBUTE, VhdlDocGen::COMPONENT, VhdlDocGen::CONFIG, VhdlDocGen::CONSTANT, VhdlDocGen::ENTITY, VhdlDocGen::FUNCTION, VhdlDocGen::GENERIC, VhdlDocGen::GROUP, VhdlDocGen::INSTANTIATION, VhdlDocGen::LIBRARY, VhdlDocGen::MISCELLANEOUS, VhdlDocGen::PACKAGE, VhdlDocGen::PACKAGE_BODY, VhdlDocGen::PORT, VhdlDocGen::PROCEDURE, VhdlDocGen::PROCESS, VhdlDocGen::RECORD, VhdlDocGen::SHAREDVARIABLE, VhdlDocGen::SIGNAL, VhdlDocGen::SUBTYPE, VhdlDocGen::TYPE, VhdlDocGen::UCF_CONST, VhdlDocGen::UNITS, VhdlDocGen::USE, and VhdlDocGen::VFILE.
trWarning() [1/2]
virtual QCString TranslatorFrench::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 589 of file translator_fr.h.
    { return "Avertissement"; }
trWarning() [2/2]
virtual QCString TranslatorFrench::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 589 of file translator_fr.h.
    { return "Avertissement"; }
trWriteList() [1/2]
virtual QCString TranslatorFrench::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 720 of file translator_fr.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=", et ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorFrench::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 720 of file translator_fr.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=", et ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_fr.h
doxygen/src/translator_fr.h