SectionRefs Class Reference
class that represents a list of constant references to sections.
#include <section.h>
Public Types
using const_iterator = SectionInfoVec::const_iterator
using const_iterator = SectionInfoVec::const_iterator
Public Member Functions
const SectionInfo * find (const QCString &label) const
void add (const SectionInfo *si)
Adds a non-owning section reference.
const_iterator begin () const
const_iterator end () const
bool empty () const
size_t size () const
const SectionInfo * find (const QCString &label) const
void add (const SectionInfo *si)
Adds a non-owning section reference.
const_iterator begin () const
const_iterator end () const
bool empty () const
size_t size () const
Private Types
using SectionInfoVec = std::vector< const SectionInfo * >
using SectionInfoVec = std::vector< const SectionInfo * >
Private Attributes
SectionInfoVec m_entries
std::unordered_map< std::string, const SectionInfo * > m_lookup
Detailed Description
class that represents a list of constant references to sections.
Definition at line 98 of file section.h.
Member Typedef Documentation
const_iterator [1/2]
using SectionRefs::const_iterator = SectionInfoVec::const_iterator
Definition at line 102 of file section.h.
const_iterator [2/2]
using SectionRefs::const_iterator = SectionInfoVec::const_iterator
Definition at line 102 of file section.h.
SectionInfoVec [1/2]
using SectionRefs::SectionInfoVec = std::vector<const SectionInfo*> [private]
Definition at line 100 of file section.h.
SectionInfoVec [2/2]
using SectionRefs::SectionInfoVec = std::vector<const SectionInfo*> [private]
Definition at line 100 of file section.h.
Member Function Documentation
add() [1/2]
void SectionRefs::add (const SectionInfo * si) [inline]
Adds a non-owning section reference.
Definition at line 113 of file section.h.
    {
      m_lookup.insert({toStdString(si->label()),si});
      m_entries.push_back(si);
    }
References SectionInfo::label(), m_entries, m_lookup, and toStdString().
Referenced by doxmlparser.compound.memberdefType::__init__(), DefinitionImpl::addSectionsToDefinition(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
add() [2/2]
void SectionRefs::add (const SectionInfo * si) [inline]
Adds a non-owning section reference.
Definition at line 113 of file section.h.
    {
      m_lookup.insert({toStdString(si->label()),si});
      m_entries.push_back(si);
    }
References SectionInfo::label(), m_entries, m_lookup, and toStdString().
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
begin() [1/2]
const_iterator SectionRefs::begin () const [inline]
Definition at line 119 of file section.h.
{ return m_entries.cbegin(); }
References m_entries.
Referenced by DefinitionImpl::addSectionsToIndex().
begin() [2/2]
const_iterator SectionRefs::begin () const [inline]
Definition at line 119 of file section.h.
{ return m_entries.cbegin(); }
References m_entries.
empty() [1/2]
bool SectionRefs::empty () const [inline]
Definition at line 121 of file section.h.
{ return m_entries.empty(); }
References m_entries.
Referenced by DefinitionImpl::addSectionsToIndex(), generateXMLForPage(), DefinitionImpl::hasSections(), DefinitionImpl::writeDocAnchorsToTagFile(), and DefinitionImpl::writeToc().
empty() [2/2]
bool SectionRefs::empty () const [inline]
Definition at line 121 of file section.h.
{ return m_entries.empty(); }
References m_entries.
end() [1/2]
const_iterator SectionRefs::end () const [inline]
Definition at line 120 of file section.h.
{ return m_entries.cend(); }
References m_entries.
Referenced by DefinitionImpl::addSectionsToIndex().
end() [2/2]
const_iterator SectionRefs::end () const [inline]
Definition at line 120 of file section.h.
{ return m_entries.cend(); }
References m_entries.
find() [1/2]
const SectionInfo * SectionRefs::find (const QCString & label) const [inline]
Returns a constant pointer to the section info given a section label or nullptr if no section with the given label can be found.
Definition at line 106 of file section.h.
    {
      auto it = m_lookup.find(label.str());
      return it!=m_lookup.end() ? it->second : nullptr;
    }
References m_lookup, and QCString::str().
Referenced by DefinitionImpl::addSectionsToDefinition().
find() [2/2]
const SectionInfo * SectionRefs::find (const QCString & label) const [inline]
Returns a constant pointer to the section info given a section label or nullptr if no section with the given label can be found.
Definition at line 106 of file section.h.
    {
      auto it = m_lookup.find(label.str());
      return it!=m_lookup.end() ? it->second : nullptr;
    }
References m_lookup, and QCString::str().
size() [1/2]
size_t SectionRefs::size () const [inline]
Definition at line 122 of file section.h.
{ return m_entries.size(); }
References m_entries.
size() [2/2]
size_t SectionRefs::size () const [inline]
Definition at line 122 of file section.h.
{ return m_entries.size(); }
References m_entries.
Member Data Documentation
m_entries
SectionInfoVec SectionRefs::m_entries [private]
Definition at line 125 of file section.h.
Referenced by add(), begin(), empty(), end(), and size().
m_lookup
std::unordered_map< std::string, const SectionInfo * > SectionRefs::m_lookup [private]
Definition at line 126 of file section.h.
Referenced by add(), and find().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/section.h
doxygen/src/section.h