IncludeInfoContext::Private Class Reference
Public Member Functions
Private (const IncludeInfo *info, SrcLangExt lang)
TemplateVariant get (const QCString &n) const
StringVector fields () const
TemplateVariant isLocal () const
TemplateVariant isImport () const
TemplateVariant file () const
TemplateVariant name () const
Private (const IncludeInfo *info, SrcLangExt lang)
TemplateVariant get (const QCString &n) const
StringVector fields () const
TemplateVariant isLocal () const
TemplateVariant isImport () const
TemplateVariant file () const
TemplateVariant name () const
Private Member Functions
TemplateVariant createFileContext () const
TemplateVariant createFileContext () const
Private Attributes
const IncludeInfo * m_info
CachedItem< TemplateVariant, Private, &Private::createFileContext > m_fileContext
SrcLangExt m_lang
Static Private Attributes
static const PropertyMap< IncludeInfoContext::Private > s_inst
Detailed Description
Definition at line 1597 of file context.cpp.
Constructor & Destructor Documentation
Private() [1/2]
IncludeInfoContext::Private::Private (const IncludeInfo * info, SrcLangExt lang) [inline]
Definition at line 1600 of file context.cpp.
                                                     :
      m_info(info),
      m_lang(lang)
    {
    }
Private() [2/2]
IncludeInfoContext::Private::Private (const IncludeInfo * info, SrcLangExt lang) [inline]
Definition at line 1600 of file context.cpp.
                                                     :
      m_info(info),
      m_lang(lang)
    {
    }
Member Function Documentation
createFileContext() [1/2]
TemplateVariant IncludeInfoContext::Private::createFileContext () const [inline], [private]
Definition at line 1632 of file context.cpp.
    {
      return m_info && m_info->fileDef ?
             TemplateVariant(FileContext::alloc(m_info->fileDef)) :
             TemplateVariant(false);
    }
References FileContext::alloc(), IncludeInfo::fileDef, and m_info.
createFileContext() [2/2]
TemplateVariant IncludeInfoContext::Private::createFileContext () const [inline], [private]
Definition at line 1632 of file context.cpp.
    {
      return m_info && m_info->fileDef ?
             TemplateVariant(FileContext::alloc(m_info->fileDef)) :
             TemplateVariant(false);
    }
References FileContext::alloc(), and IncludeInfo::fileDef.
fields() [1/2]
StringVector IncludeInfoContext::Private::fields () const [inline]
Definition at line 1609 of file context.cpp.
    {
      return s_inst.fields();
    }
References PropertyMap< T >::fields(), and s_inst.
fields() [2/2]
StringVector IncludeInfoContext::Private::fields () const [inline]
Definition at line 1609 of file context.cpp.
    {
      return s_inst.fields();
    }
file() [1/2]
TemplateVariant IncludeInfoContext::Private::file () const [inline]
Definition at line 1622 of file context.cpp.
    {
      return m_fileContext.get(this);
    }
References m_fileContext.
Referenced by doxmlparser.compound.locationType::__init__(), doxmlparser.compound.locationType::buildAttributes(), doxmlparser.compound.locationType::exportAttributes(), doxmlparser.compound.locationType::get_file(), and doxmlparser.compound.locationType::set_file().
file() [2/2]
TemplateVariant IncludeInfoContext::Private::file () const [inline]
Definition at line 1622 of file context.cpp.
    {
      return m_fileContext.get(this);
    }
Referenced by doxmlparser.compound.locationType::__init__(), doxmlparser.compound.locationType::buildAttributes(), doxmlparser.compound.locationType::exportAttributes(), doxmlparser.compound.locationType::get_file(), and doxmlparser.compound.locationType::set_file().
get() [1/2]
TemplateVariant IncludeInfoContext::Private::get (const QCString & n) const [inline]
Definition at line 1605 of file context.cpp.
    {
      return s_inst.get(this,n);
    }
References PropertyMap< T >::get(), n, and s_inst.
get() [2/2]
TemplateVariant IncludeInfoContext::Private::get (const QCString & n) const [inline]
Definition at line 1605 of file context.cpp.
    {
      return s_inst.get(this,n);
    }
References n.
isImport() [1/2]
TemplateVariant IncludeInfoContext::Private::isImport () const [inline]
Definition at line 1618 of file context.cpp.
    {
      return m_info->imported || m_lang==SrcLangExt_ObjC;
    }
References IncludeInfo::imported, m_info, m_lang, and SrcLangExt_ObjC.
isImport() [2/2]
TemplateVariant IncludeInfoContext::Private::isImport () const [inline]
Definition at line 1618 of file context.cpp.
    {
      return m_info->imported || m_lang==SrcLangExt_ObjC;
    }
References SrcLangExt_ObjC.
isLocal() [1/2]
TemplateVariant IncludeInfoContext::Private::isLocal () const [inline]
Definition at line 1613 of file context.cpp.
    {
      bool isIDLorJava = m_lang==SrcLangExt_IDL || m_lang==SrcLangExt_Java;
      return m_info->local || isIDLorJava;
    }
References m_info, m_lang, SrcLangExt_IDL, and SrcLangExt_Java.
isLocal() [2/2]
TemplateVariant IncludeInfoContext::Private::isLocal () const [inline]
Definition at line 1613 of file context.cpp.
    {
      bool isIDLorJava = m_lang==SrcLangExt_IDL || m_lang==SrcLangExt_Java;
      return m_info->local || isIDLorJava;
    }
References SrcLangExt_IDL, and SrcLangExt_Java.
name() [1/2]
TemplateVariant IncludeInfoContext::Private::name () const [inline]
Definition at line 1626 of file context.cpp.
    {
      return m_info->includeName;
    }
References IncludeInfo::includeName, and m_info.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
name() [2/2]
TemplateVariant IncludeInfoContext::Private::name () const [inline]
Definition at line 1626 of file context.cpp.
    {
      return m_info->includeName;
    }
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
Member Data Documentation
m_fileContext
CachedItem< TemplateVariant, Private, &Private::createFileContext > IncludeInfoContext::Private::m_fileContext [private]
Definition at line 1638 of file context.cpp.
Referenced by file().
m_info
const IncludeInfo * IncludeInfoContext::Private::m_info [private]
Definition at line 1631 of file context.cpp.
Referenced by createFileContext(), isImport(), isLocal(), and name().
m_lang
SrcLangExt IncludeInfoContext::Private::m_lang [private]
Definition at line 1639 of file context.cpp.
Referenced by isImport(), and isLocal().
s_inst
const PropertyMap< IncludeInfoContext::Private > IncludeInfoContext::Private::s_inst [static], [private]
Initial value:
{
  { "file",&Private::file },
  { "name",&Private::name },
  { "isImport",&Private::isImport },
  { "isLocal",&Private::isLocal }
}
Definition at line 1640 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp