TemplateContextImpl Class Reference
Internal class representing the implementation of a template context.
Public Types
using EscapeIntfMap = std::unordered_map< std::string, std::unique_ptr< TemplateEscapeIntf > >
using EscapeIntfMap = std::unordered_map< std::string, std::unique_ptr< TemplateEscapeIntf > >
Public Member Functions
TemplateContextImpl (const TemplateEngine *e)
virtual ~TemplateContextImpl ()
void copyEscapeIntfMap (const EscapeIntfMap &map)
void push ()
void pop ()
void set (const QCString &name, const TemplateVariant &v)
TemplateVariant get (const QCString &name) const
const TemplateVariant * getRef (const QCString &name) const
void setOutputDirectory (const QCString &dir)
void setEscapeIntf (const QCString &ext, std::unique_ptr< TemplateEscapeIntf > intf)
void selectEscapeIntf (const QCString &ext)
void setActiveEscapeIntf (TemplateEscapeIntf *intf)
TemplateEscapeIntf * escapeIntf ()
const TemplateEscapeIntf * escapeIntf () const
void setSpacelessIntf (std::unique_ptr< TemplateSpacelessIntf > intf)
TemplateBlockContext * blockContext ()
TemplateVariant getPrimary (const QCString &name) const
void setLocation (const QCString &templateName, int line)
QCString templateName () const
int line () const
QCString outputDirectory () const
std::unique_ptr< TemplateSpacelessIntf > & spacelessIntf ()
const std::unique_ptr< TemplateSpacelessIntf > & spacelessInfo () const
void enableSpaceless (bool b)
bool spacelessEnabled () const
void enableTabbing (bool b)
bool tabbingEnabled () const
bool needsRecoding () const
QCString encoding () const
void setEncoding (const QCString &file, int line, const QCString &enc)
QCString recode (const QCString &s)
void warn (const QCString &fileName, int line, const char *fmt,...) const
void openSubIndex (const QCString &indexName)
void closeSubIndex (const QCString &indexName)
void addIndexEntry (const QCString &indexName, const std::vector< TemplateKeyValue > &arguments)
const TemplateStructPtr indices () const
TemplateContextImpl (const TemplateEngine *e)
virtual ~TemplateContextImpl ()
void copyEscapeIntfMap (const EscapeIntfMap &map)
void push ()
void pop ()
void set (const QCString &name, const TemplateVariant &v)
TemplateVariant get (const QCString &name) const
const TemplateVariant * getRef (const QCString &name) const
void setOutputDirectory (const QCString &dir)
void setEscapeIntf (const QCString &ext, std::unique_ptr< TemplateEscapeIntf > intf)
void selectEscapeIntf (const QCString &ext)
void setActiveEscapeIntf (TemplateEscapeIntf *intf)
TemplateEscapeIntf * escapeIntf ()
const TemplateEscapeIntf * escapeIntf () const
void setSpacelessIntf (std::unique_ptr< TemplateSpacelessIntf > intf)
TemplateBlockContext * blockContext ()
TemplateVariant getPrimary (const QCString &name) const
void setLocation (const QCString &templateName, int line)
QCString templateName () const
int line () const
QCString outputDirectory () const
std::unique_ptr< TemplateSpacelessIntf > & spacelessIntf ()
const std::unique_ptr< TemplateSpacelessIntf > & spacelessInfo () const
void enableSpaceless (bool b)
bool spacelessEnabled () const
void enableTabbing (bool b)
bool tabbingEnabled () const
bool needsRecoding () const
QCString encoding () const
void setEncoding (const QCString &file, int line, const QCString &enc)
QCString recode (const QCString &s)
void warn (const QCString &fileName, int line, const char *fmt,...) const
void openSubIndex (const QCString &indexName)
void closeSubIndex (const QCString &indexName)
void addIndexEntry (const QCString &indexName, const std::vector< TemplateKeyValue > &arguments)
const TemplateStructPtr indices () const
Private Attributes
const TemplateEngine * m_engine = 0
QCString m_templateName = `<unknown>`
int m_line = 1
QCString m_outputDir
std::deque< std::unordered_map< std::string, TemplateVariant > > m_contextStack
TemplateBlockContext m_blockContext
EscapeIntfMap m_escapeIntfMap
TemplateEscapeIntf * m_activeEscapeIntf = 0
std::unique_ptr< TemplateSpacelessIntf > m_spacelessIntf
bool m_spacelessEnabled = false
bool m_tabbingEnabled = false
TemplateStructPtr m_indices
std::unordered_map< std::string, std::stack< TemplateVariant > > m_indexStacks
QCString m_encoding
void * m_fromUtf8 = 0
Detailed Description
Internal class representing the implementation of a template context.
Definition at line 639 of file template.cpp.
Member Typedef Documentation
EscapeIntfMap [1/2]
using TemplateContextImpl::EscapeIntfMap = std::unordered_map<std::string, std::unique_ptr<TemplateEscapeIntf> >
Definition at line 645 of file template.cpp.
EscapeIntfMap [2/2]
using TemplateContextImpl::EscapeIntfMap = std::unordered_map<std::string, std::unique_ptr<TemplateEscapeIntf> >
Definition at line 645 of file template.cpp.
Constructor & Destructor Documentation
TemplateContextImpl() [1/2]
TemplateContextImpl::TemplateContextImpl (const TemplateEngine * e)
Definition at line 2573 of file template.cpp.
  : m_engine(e), m_indices(TemplateStruct::alloc())
{
  //printf("%p:TemplateContextImpl::TemplateContextImpl()\n",(void*)this);
  m_fromUtf8 = reinterpret_cast<void*>(-1);
  push();
  set("index",std::static_pointer_cast<TemplateStructIntf>(m_indices));
}
References m_fromUtf8, m_indices, push(), and set().
 TemplateContextImpl() [1/2]
TemplateContextImpl::~TemplateContextImpl () [virtual]
Definition at line 2582 of file template.cpp.
{
  pop();
  //printf("%p:TemplateContextImpl::~TemplateContextImpl()\n",(void*)this);
}
References pop().
TemplateContextImpl() [2/2]
TemplateContextImpl::TemplateContextImpl (const TemplateEngine * e)
 TemplateContextImpl() [2/2]
virtual TemplateContextImpl::~TemplateContextImpl () [virtual]
Member Function Documentation
addIndexEntry() [1/2]
void TemplateContextImpl::addIndexEntry (const QCString & indexName, const std::vector< TemplateKeyValue > & arguments)
Definition at line 2852 of file template.cpp.
{
  //auto it = arguments.begin();
  //printf("%p:> TemplateContextImpl::addIndexEntry(%s)\n",(void*)this,qPrint(indexName));
  //while (it!=arguments.end())
  //{
  // printf(" key=%s value=%s\n",(*it).key.data(),(*it).value.toString().data());
  // ++it;
  //}
  TemplateVariant parent(FALSE);
  auto kv = m_indexStacks.find(indexName.str());
  if (kv==m_indexStacks.end()) // no stack yet, create it!
  {
    kv = m_indexStacks.insert(std::make_pair(indexName.str(),std::stack<TemplateVariant>())).first;
  }
  TemplateListPtr list;
  auto &stack = kv->second;
  if (stack.empty()) // first item, create empty list and add it to the index
  {
    list = TemplateList::alloc();
    stack.emplace(std::static_pointer_cast<TemplateListIntf>(list));
    m_indices->set(indexName,std::static_pointer_cast<TemplateListIntf>(list)); // make list available under index
  }
  else // stack not empty
  {
    if (stack.top().isStruct() || stack.top().isWeakStruct()) // already an entry in the list
    {
      // remove current entry from the stack
      stack.pop();
    }
    else // first entry after opensubindex
    {
      ASSERT(stack.top().isList());
    }
    if (stack.size()>1)
    {
      TemplateVariant tmp = stack.top();
      stack.pop();
      // To prevent a cyclic dependency between parent and child which causes a memory
      // leak, we wrap the parent into a weak reference version.
      //parent = TemplateVariant(TemplateStructIntfWeakPtr(stack.top().toStruct()));
      stack.push(tmp);
    }
    // get list to add new item
    list = std::dynamic_pointer_cast<TemplateList>(stack.top().toList());
  }
  TemplateStructPtr entry = TemplateStruct::alloc();
  // add user specified fields to the entry
  for (auto it=arguments.begin();it!=arguments.end();++it)
  {
    entry->set((*it).key,(*it).value);
  }
  if (list->count()>0)
  {
    TemplateStructPtr lastEntry = std::dynamic_pointer_cast<TemplateStruct>(list->at(list->count()-1).toStruct());
    if (lastEntry)
    {
      lastEntry->set("last",false);
    }
  }
  entry->set("is_leaf_node",true);
  entry->set("first",list->count()==0);
  entry->set("index",list->count());
  entry->set("parent",parent);
  TemplateStructIntfWeakPtr entryWeak(std::static_pointer_cast<TemplateStructIntf>(entry));
  entry->set("path",TemplateVariant([entryWeak](const TemplateVariantList &){ return getPathFunc(entryWeak); }));
  entry->set("last",true);
  stack.push(TemplateVariant(std::static_pointer_cast<TemplateStructIntf>(entry)));
  list->append(TemplateVariant(std::static_pointer_cast<TemplateStructIntf>(entry)));
}
References TemplateStruct::alloc(), TemplateList::alloc(), ASSERT, FALSE, getPathFunc(), m_indexStacks, m_indices, parent(), and QCString::str().
Referenced by TemplateNodeIndexEntry::render().
addIndexEntry() [2/2]
void TemplateContextImpl::addIndexEntry (const QCString & indexName, const std::vector< TemplateKeyValue > & arguments)
blockContext() [1/2]
TemplateBlockContext * TemplateContextImpl::blockContext ()
Definition at line 2767 of file template.cpp.
{
  return &m_blockContext;
}
References m_blockContext.
Referenced by TemplateImpl::render(), TemplateNodeBlock::render(), and TemplateNodeExtend::render().
blockContext() [2/2]
TemplateBlockContext * TemplateContextImpl::blockContext ()
closeSubIndex() [1/2]
void TemplateContextImpl::closeSubIndex (const QCString & indexName)
Definition at line 2803 of file template.cpp.
{
  //printf("TemplateContextImpl::closeSubIndex(%s)\n",qPrint(indexName));
  auto kv = m_indexStacks.find(indexName.str());
  if (kv==m_indexStacks.end() || kv->second.size()<3)
  {
    warn(m_templateName,m_line,"closesubindex for index %s without matching open",qPrint(indexName));
  }
  else
  {
    auto &stack = kv->second; // stack.size()>2
    if (stack.top().isStruct() || stack.top().isWeakStruct())
    {
      stack.pop(); // pop struct
      stack.pop(); // pop list
    }
    else // empty list! correct "is_left_node" attribute of the parent entry
    {
      stack.pop(); // pop list
      TemplateStructPtr entry = std::dynamic_pointer_cast<TemplateStruct>(stack.top().toStruct());
      if (entry)
      {
        entry->set("is_leaf_node",true);
      }
    }
  }
  //fprintf(stderr,"TemplateContextImpl::closeSubIndex(%s) end g_count=%d\n\n",qPrint(indexName),g_count);
}
References m_indexStacks, m_line, m_templateName, qPrint(), QCString::str(), and warn().
Referenced by TemplateNodeCloseSubIndex::render().
closeSubIndex() [2/2]
void TemplateContextImpl::closeSubIndex (const QCString & indexName)
copyEscapeIntfMap() [1/2]
void TemplateContextImpl::copyEscapeIntfMap (const EscapeIntfMap & map) [inline]
Definition at line 646 of file template.cpp.
    {
      for (const auto &kv : map)
      {
        m_escapeIntfMap.insert(std::make_pair(kv.first,kv.second->clone()));
      }
    }
References m_escapeIntfMap.
copyEscapeIntfMap() [2/2]
void TemplateContextImpl::copyEscapeIntfMap (const EscapeIntfMap & map) [inline]
Definition at line 646 of file template.cpp.
    {
      for (const auto &kv : map)
      {
        m_escapeIntfMap.insert(std::make_pair(kv.first,kv.second->clone()));
      }
    }
enableSpaceless() [1/2]
void TemplateContextImpl::enableSpaceless (bool b) [inline]
Definition at line 688 of file template.cpp.
                                                 { if (b && !m_spacelessEnabled) m_spacelessIntf->reset();
                                                   m_spacelessEnabled=b;
                                                 }
References b, m_spacelessEnabled, and m_spacelessIntf.
Referenced by TemplateNodeMsg::render(), TemplateNodeSpaceless::render(), and TemplateNodeMarkers::render().
enableSpaceless() [2/2]
void TemplateContextImpl::enableSpaceless (bool b) [inline]
Definition at line 688 of file template.cpp.
                                                 { if (b && !m_spacelessEnabled) m_spacelessIntf->reset();
                                                   m_spacelessEnabled=b;
                                                 }
References b.
enableTabbing() [1/2]
void TemplateContextImpl::enableTabbing (bool b) [inline]
Definition at line 692 of file template.cpp.
                                                 { m_tabbingEnabled=b;
                                                   if (m_activeEscapeIntf) m_activeEscapeIntf->enableTabbing(b);
                                                 }
References b, TemplateEscapeIntf::enableTabbing(), m_activeEscapeIntf, and m_tabbingEnabled.
Referenced by TemplateNodeTabbing::render().
enableTabbing() [2/2]
void TemplateContextImpl::enableTabbing (bool b) [inline]
Definition at line 692 of file template.cpp.
                                                 { m_tabbingEnabled=b;
                                                   if (m_activeEscapeIntf) m_activeEscapeIntf->enableTabbing(b);
                                                 }
References b.
encoding() [1/2]
QCString TemplateContextImpl::encoding () const [inline]
Definition at line 697 of file template.cpp.
{ return m_encoding; }
References m_encoding.
Referenced by TemplateNodeEncoding::render().
encoding() [2/2]
QCString TemplateContextImpl::encoding () const [inline]
Definition at line 697 of file template.cpp.
{ return m_encoding; }
escapeIntf() [1/4]
TemplateEscapeIntf * TemplateContextImpl::escapeIntf () [inline]
Definition at line 674 of file template.cpp.
{ return m_activeEscapeIntf; }
References m_activeEscapeIntf.
Referenced by TemplateNodeMsg::render(), TemplateNodeCreate::render(), TemplateNodeVariable::render(), and TemplateNodeCycle::render().
escapeIntf() [2/4]
TemplateEscapeIntf * TemplateContextImpl::escapeIntf () [inline]
Definition at line 674 of file template.cpp.
{ return m_activeEscapeIntf; }
escapeIntf() [3/4]
const TemplateEscapeIntf * TemplateContextImpl::escapeIntf () const [inline]
Definition at line 675 of file template.cpp.
{ return m_activeEscapeIntf; }
References m_activeEscapeIntf.
escapeIntf() [4/4]
const TemplateEscapeIntf * TemplateContextImpl::escapeIntf () const [inline]
Definition at line 675 of file template.cpp.
{ return m_activeEscapeIntf; }
get() [1/2]
TemplateVariant TemplateContextImpl::get (const QCString & name) const [virtual]
Gets the value for a given key
Parameters
 in name The name of key.
Returns
The value, which can be an invalid variant in case the key was not found.
Implements TemplateContext.
Definition at line 2645 of file template.cpp.
{
  int i=name.find('.');
  if (i==-1) // simple name
  {
    return getPrimary(name);
  }
  else // obj.prop
  {
    QCString objName = name.left(i);
    TemplateVariant v = getPrimary(objName);
    QCString propName = name.mid(i+1);
    while (!propName.isEmpty())
    {
      //printf("getPrimary(%s) type=%zu:%s\n",qPrint(objName),v.type(),qPrint(v.toString()));
      if (v.isStruct() || v.isWeakStruct())
      {
        TemplateStructIntfPtr s = v.toStruct();
        if (s)
        {
          i = propName.find(".");
          int l = i==-1 ? propName.length() : i;
          v = s->get(propName.left(l));
          if (!v.isValid())
          {
            warn(m_templateName,m_line,"requesting non-existing property '%s' for object '%s'",qPrint(propName.left(l)),qPrint(objName));
          }
          if (i!=-1)
          {
            objName = propName.left(i);
            propName = propName.mid(i+1);
          }
          else
          {
            propName.resize(0);
          }
        }
        else
        {
          return TemplateVariant();
        }
      }
      else if (v.isList())
      {
        TemplateListIntfPtr list = v.toList();
        if (list)
        {
          i = propName.find(".");
          int l = i==-1 ? propName.length() : i;
          bool b;
          int index = propName.left(l).toInt(&b);
          if (b)
          {
            v = list->at(index);
          }
          else
          {
            warn(m_templateName,m_line,"list index '%s' is not valid",qPrint(propName));
            break;
          }
          if (i!=-1)
          {
            propName = propName.mid(i+1);
          }
          else
          {
            propName.resize(0);
          }
        }
        else
        {
          return TemplateVariant();
        }
      }
      else
      {
        warn(m_templateName,m_line,"using . on an object '%s' is not an struct or list",qPrint(objName));
        return TemplateVariant();
      }
    }
    return v;
  }
}
References b, QCString::find(), getPrimary(), QCString::isEmpty(), TemplateVariant::isList(), TemplateVariant::isStruct(), TemplateVariant::isValid(), TemplateVariant::isWeakStruct(), QCString::left(), QCString::length(), m_line, m_templateName, QCString::mid(), setup::name, qPrint(), QCString::resize(), s, QCString::toInt(), TemplateVariant::toList(), TemplateVariant::toStruct(), and warn().
get() [2/2]
TemplateVariant TemplateContextImpl::get (const QCString & name) const [virtual]
Gets the value for a given key
Parameters
 in name The name of key.
Returns
The value, which can be an invalid variant in case the key was not found.
Implements TemplateContext.
getPrimary() [1/2]
TemplateVariant TemplateContextImpl::getPrimary (const QCString & name) const
Definition at line 2742 of file template.cpp.
{
  const TemplateVariant *v = getRef(name);
  return v ? *v : TemplateVariant();
}
References getRef(), and setup::name.
Referenced by get().
getPrimary() [2/2]
TemplateVariant TemplateContextImpl::getPrimary (const QCString & name) const
getRef() [1/2]
const TemplateVariant * TemplateContextImpl::getRef (const QCString & name) const [virtual]
Returns a pointer to the value corresponding to a given key.
Parameters
 in name The name of key.
Returns
A pointer to the value, or 0 in case the key was not found.
Implements TemplateContext.
Definition at line 2729 of file template.cpp.
{
  for (const auto &ctx : m_contextStack)
  {
    auto it = ctx.find(name.str());
    if (it!=ctx.end())
    {
      return &it->second;
    }
  }
  return 0; // not found
}
References m_contextStack, and setup::name.
Referenced by getPrimary().
getRef() [2/2]
const TemplateVariant * TemplateContextImpl::getRef (const QCString & name) const [virtual]
Returns a pointer to the value corresponding to a given key.
Parameters
 in name The name of key.
Returns
A pointer to the value, or 0 in case the key was not found.
Implements TemplateContext.
indices() [1/2]
const TemplateStructPtr TemplateContextImpl::indices () const [inline]
Definition at line 706 of file template.cpp.
{ return m_indices; }
References m_indices.
indices() [2/2]
const TemplateStructPtr TemplateContextImpl::indices () const [inline]
Definition at line 706 of file template.cpp.
{ return m_indices; }
line() [1/2]
int TemplateContextImpl::line () const [inline]
Definition at line 684 of file template.cpp.
{ return m_line; }
References m_line.
Referenced by doxmlparser.compound.locationType::__init__(), ExprAstFilter::apply(), doxmlparser.compound.locationType::buildAttributes(), doxmlparser.compound.locationType::exportAttributes(), doxmlparser.compound.locationType::get_line(), ExprAstVariable::resolve(), ExprAstBinary::resolve(), doxmlparser.compound.locationType::set_line(), setEncoding(), setLocation(), and warn().
line() [2/2]
int TemplateContextImpl::line () const [inline]
Definition at line 684 of file template.cpp.
{ return m_line; }
Referenced by doxmlparser.compound.locationType::__init__(), doxmlparser.compound.locationType::buildAttributes(), doxmlparser.compound.locationType::exportAttributes(), doxmlparser.compound.locationType::get_line(), and doxmlparser.compound.locationType::set_line().
needsRecoding() [1/2]
bool TemplateContextImpl::needsRecoding () const [inline]
Definition at line 696 of file template.cpp.
{ return !m_encoding.isEmpty(); }
References QCString::isEmpty(), and m_encoding.
Referenced by TemplateNodeText::render(), TemplateNodeVariable::render(), TemplateNodeCycle::render(), and TemplateNodeMarkers::render().
needsRecoding() [2/2]
bool TemplateContextImpl::needsRecoding () const [inline]
Definition at line 696 of file template.cpp.
{ return !m_encoding.isEmpty(); }
openSubIndex() [1/2]
void TemplateContextImpl::openSubIndex (const QCString & indexName)
Definition at line 2781 of file template.cpp.
{
  //printf("TemplateContextImpl::openSubIndex(%s)\n",qPrint(indexName));
  auto kv = m_indexStacks.find(indexName.str());
  if (kv==m_indexStacks.end() || kv->second.empty() || kv->second.top().isList()) // error: no stack yet or no entry
  {
    warn(m_templateName,m_line,"opensubindex for index %s without preceding indexentry",qPrint(indexName));
    return;
  }
  // get the parent entry to add the list to
  auto &stack = kv->second;
  TemplateStructPtr entry = std::dynamic_pointer_cast<TemplateStruct>(stack.top().toStruct());
  if (entry)
  {
    // add new list to the stack
    TemplateListPtr list = TemplateList::alloc();
    stack.emplace(std::static_pointer_cast<TemplateListIntf>(list));
    entry->set("children",std::static_pointer_cast<TemplateListIntf>(list));
    entry->set("is_leaf_node",false);
  }
}
References TemplateList::alloc(), m_indexStacks, m_line, m_templateName, qPrint(), QCString::str(), and warn().
Referenced by TemplateNodeOpenSubIndex::render().
openSubIndex() [2/2]
void TemplateContextImpl::openSubIndex (const QCString & indexName)
outputDirectory() [1/2]
QCString TemplateContextImpl::outputDirectory () const [inline]
Definition at line 685 of file template.cpp.
{ return m_outputDir; }
References m_outputDir.
Referenced by TemplateNodeCreator< T >::mkpath(), TemplateNodeCreate::render(), and TemplateNodeResource::render().
outputDirectory() [2/2]
QCString TemplateContextImpl::outputDirectory () const [inline]
Definition at line 685 of file template.cpp.
{ return m_outputDir; }
pop() [1/2]
void TemplateContextImpl::pop () [virtual]
Pop the current scope from the stack.
Implements TemplateContext.
Definition at line 2754 of file template.cpp.
{
  //printf("TemplateContextImpl::pop() #stacks=%lu\n",m_contextStack.size());
  if (m_contextStack.empty())
  {
    warn(m_templateName,m_line,"pop() called on empty context stack!\n");
  }
  else
  {
    m_contextStack.pop_front();
  }
}
References m_contextStack, m_line, m_templateName, and warn().
Referenced by TemplateNodeBlock::render(), and ~TemplateContextImpl().
pop() [2/2]
void TemplateContextImpl::pop () [virtual]
Pop the current scope from the stack.
Implements TemplateContext.
push() [1/2]
void TemplateContextImpl::push () [virtual]
Push a new scope on the stack.
Implements TemplateContext.
Definition at line 2748 of file template.cpp.
{
  m_contextStack.push_front(std::unordered_map<std::string,TemplateVariant>());
  //printf("TemplateContextImpl::push() #stacks=%lu\n",m_contextStack.size());
}
References m_contextStack.
Referenced by TemplateNodeBlock::render(), and TemplateContextImpl().
push() [2/2]
void TemplateContextImpl::push () [virtual]
Push a new scope on the stack.
Implements TemplateContext.
recode() [1/2]
QCString TemplateContextImpl::recode (const QCString & s)
Definition at line 2608 of file template.cpp.
{
  //printf("TemplateContextImpl::recode(%s)\n",qPrint(s));
  size_t iSize = s.length();
  size_t oSize = iSize*4+1;
  QCString output(oSize);
  size_t iLeft = iSize;
  size_t oLeft = oSize;
  const char *iPtr = s.data();
  char *oPtr = output.rawData();
  if (!portable_iconv(m_fromUtf8,&iPtr,&iLeft,&oPtr,&oLeft))
  {
    oSize -= oLeft;
    output.resize(oSize+1);
    output.at(oSize)='\0';
    return output;
  }
  else
  {
    return s;
  }
}
References QCString::at(), gdFont::data, m_fromUtf8, portable_iconv(), QCString::rawData(), QCString::resize(), and s.
Referenced by TemplateNodeText::render(), TemplateNodeVariable::render(), TemplateNodeCycle::render(), and TemplateNodeMarkers::render().
recode() [2/2]
QCString TemplateContextImpl::recode (const QCString & s)
selectEscapeIntf() [1/2]
void TemplateContextImpl::selectEscapeIntf (const QCString & ext) [inline]
Definition at line 668 of file template.cpp.
    {
      auto it = m_escapeIntfMap.find(ext.str());
      m_activeEscapeIntf = it!=m_escapeIntfMap.end() ? it->second.get() : 0;
    }
References m_activeEscapeIntf, m_escapeIntfMap, and QCString::str().
Referenced by TemplateNodeCreate::render().
selectEscapeIntf() [2/2]
void TemplateContextImpl::selectEscapeIntf (const QCString & ext) [inline]
Definition at line 668 of file template.cpp.
    {
      auto it = m_escapeIntfMap.find(ext.str());
      m_activeEscapeIntf = it!=m_escapeIntfMap.end() ? it->second.get() : 0;
    }
References QCString::str().
set() [1/2]
void TemplateContextImpl::set (const QCString & name, const TemplateVariant & v) [virtual]
Sets a value in the current scope.
Parameters
 in name The name of the value; the key in the dictionary.
 in v The value associated with the key.
Note
When a given key is already present, its value will be replaced by v
Implements TemplateContext.
Definition at line 2631 of file template.cpp.
{
  auto &ctx = m_contextStack.front();
  auto it = ctx.find(name.str());
  if (it!=ctx.end())
  {
    ctx.erase(it);
  }
  ctx.insert(std::make_pair(name.str(),v));
  //printf("TemplateContextImpl::set(%s) #stacks=%lu front().size()=%lu\n",
  // qPrint(name),m_contextStack.size(),m_contextStack.size()>0 ? m_contextStack.front().size() : 0);
}
References m_contextStack, and setup::name.
Referenced by TemplateNodeSet::render(), TemplateNodeBlock::render(), TemplateNodeWith::render(), and TemplateContextImpl().
set() [2/2]
void TemplateContextImpl::set (const QCString & name, const TemplateVariant & v) [virtual]
Sets a value in the current scope.
Parameters
 in name The name of the value; the key in the dictionary.
 in v The value associated with the key.
Note
When a given key is already present, its value will be replaced by v
Implements TemplateContext.
setActiveEscapeIntf() [1/2]
void TemplateContextImpl::setActiveEscapeIntf (TemplateEscapeIntf * intf) [inline]
Definition at line 673 of file template.cpp.
{ m_activeEscapeIntf = intf; }
References m_activeEscapeIntf.
Referenced by TemplateNodeMsg::render(), and TemplateNodeCreate::render().
setActiveEscapeIntf() [2/2]
void TemplateContextImpl::setActiveEscapeIntf (TemplateEscapeIntf * intf) [inline]
Definition at line 673 of file template.cpp.
{ m_activeEscapeIntf = intf; }
setEncoding() [1/2]
void TemplateContextImpl::setEncoding (const QCString & file, int line, const QCString & enc)
Definition at line 2588 of file template.cpp.
{
  if (enc==m_encoding) return; // nothing changed
  if (m_fromUtf8!=reinterpret_cast<void *>(-1))
  {
    portable_iconv_close(m_fromUtf8);
    m_fromUtf8 = reinterpret_cast<void*>(-1);
  }
  m_encoding=enc;
  if (!enc.isEmpty())
  {
    m_fromUtf8 = portable_iconv_open(enc.data(),"UTF-8");
    if (m_fromUtf8==reinterpret_cast<void*>(-1))
    {
      warn(templateName,line,"unsupported character conversion: '%s'->'UTF-8'\n", qPrint(enc));
    }
  }
  //printf("TemplateContextImpl::setEncoding(%s)\n",qPrint(enc));
}
References QCString::data(), QCString::isEmpty(), line(), m_encoding, m_fromUtf8, portable_iconv_close(), portable_iconv_open(), qPrint(), templateName(), and warn().
Referenced by TemplateNodeEncoding::render().
setEncoding() [2/2]
void TemplateContextImpl::setEncoding (const QCString & file, int line, const QCString & enc)
setEscapeIntf() [1/2]
void TemplateContextImpl::setEscapeIntf (const QCString & extension, std::unique_ptr< TemplateEscapeIntf > intf) [inline], [virtual]
Sets the interface that will be used for escaping the result of variable expansion before writing it to the output.
Implements TemplateContext.
Definition at line 663 of file template.cpp.
    {
      int i=(!ext.isEmpty() && ext.at(0)=='.') ? 1 : 0;
      m_escapeIntfMap.insert(std::make_pair(ext.mid(i).str(),std::move(intf)));
    }
References QCString::at(), QCString::isEmpty(), m_escapeIntfMap, QCString::mid(), and QCString::str().
setEscapeIntf() [2/2]
void TemplateContextImpl::setEscapeIntf (const QCString & extension, std::unique_ptr< TemplateEscapeIntf > intf) [inline], [virtual]
Sets the interface that will be used for escaping the result of variable expansion before writing it to the output.
Implements TemplateContext.
Definition at line 663 of file template.cpp.
    {
      int i=(!ext.isEmpty() && ext.at(0)=='.') ? 1 : 0;
      m_escapeIntfMap.insert(std::make_pair(ext.mid(i).str(),std::move(intf)));
    }
References QCString::at(), QCString::isEmpty(), QCString::mid(), and QCString::str().
setLocation() [1/2]
void TemplateContextImpl::setLocation (const QCString & templateName, int line) [inline]
Definition at line 681 of file template.cpp.
    { m_templateName=templateName; m_line=line; }
References line(), m_line, m_templateName, and templateName().
Referenced by TemplateNodeMsg::render(), TemplateNodeCreate::render(), TemplateNodeIndexEntry::render(), TemplateNodeOpenSubIndex::render(), TemplateNodeCloseSubIndex::render(), TemplateNodeSet::render(), TemplateNodeResource::render(), TemplateNodeVariable::render(), TemplateNodeIf::render(), TemplateNodeRepeat::render(), TemplateNodeRange::render(), TemplateNodeFor::render(), TemplateNodeBlock::render(), TemplateNodeExtend::render(), TemplateNodeInclude::render(), TemplateNodeTree::render(), TemplateNodeWith::render(), TemplateNodeCycle::render(), TemplateNodeSpaceless::render(), TemplateNodeMarkers::render(), TemplateNodeTabbing::render(), and TemplateNodeEncoding::render().
setLocation() [2/2]
void TemplateContextImpl::setLocation (const QCString & templateName, int line) [inline]
Definition at line 681 of file template.cpp.
    { m_templateName=templateName; m_line=line; }
setOutputDirectory() [1/2]
void TemplateContextImpl::setOutputDirectory (const QCString & dir) [inline], [virtual]
When files are created (i.e. by {% create ... %}) they written to the directory dir.
Implements TemplateContext.
Definition at line 661 of file template.cpp.
    { m_outputDir = dir; }
References m_outputDir.
setOutputDirectory() [2/2]
void TemplateContextImpl::setOutputDirectory (const QCString & dir) [inline], [virtual]
When files are created (i.e. by {% create ... %}) they written to the directory dir.
Implements TemplateContext.
Definition at line 661 of file template.cpp.
    { m_outputDir = dir; }
setSpacelessIntf() [1/2]
void TemplateContextImpl::setSpacelessIntf (std::unique_ptr< TemplateSpacelessIntf > intf) [inline], [virtual]
Sets the interface that will be used inside a spaceless block to remove any redundant whitespace.
Implements TemplateContext.
Definition at line 676 of file template.cpp.
{ m_spacelessIntf = std::move(intf); }
References m_spacelessIntf.
setSpacelessIntf() [2/2]
void TemplateContextImpl::setSpacelessIntf (std::unique_ptr< TemplateSpacelessIntf > intf) [inline], [virtual]
Sets the interface that will be used inside a spaceless block to remove any redundant whitespace.
Implements TemplateContext.
Definition at line 676 of file template.cpp.
{ m_spacelessIntf = std::move(intf); }
spacelessEnabled() [1/2]
bool TemplateContextImpl::spacelessEnabled () const [inline]
Definition at line 691 of file template.cpp.
{ return m_spacelessEnabled && m_spacelessIntf; }
References m_spacelessEnabled, and m_spacelessIntf.
Referenced by TemplateNodeMsg::render(), TemplateNodeText::render(), TemplateNodeSpaceless::render(), and TemplateNodeMarkers::render().
spacelessEnabled() [2/2]
bool TemplateContextImpl::spacelessEnabled () const [inline]
Definition at line 691 of file template.cpp.
{ return m_spacelessEnabled && m_spacelessIntf; }
spacelessInfo() [1/2]
const std::unique_ptr< TemplateSpacelessIntf > & TemplateContextImpl::spacelessInfo () const [inline]
Definition at line 687 of file template.cpp.
{ return m_spacelessIntf; }
References m_spacelessIntf.
spacelessInfo() [2/2]
const std::unique_ptr< TemplateSpacelessIntf > & TemplateContextImpl::spacelessInfo () const [inline]
Definition at line 687 of file template.cpp.
{ return m_spacelessIntf; }
spacelessIntf() [1/2]
std::unique_ptr< TemplateSpacelessIntf > & TemplateContextImpl::spacelessIntf () [inline]
Definition at line 686 of file template.cpp.
{ return m_spacelessIntf; }
References m_spacelessIntf.
Referenced by TemplateNodeText::render().
spacelessIntf() [2/2]
std::unique_ptr< TemplateSpacelessIntf > & TemplateContextImpl::spacelessIntf () [inline]
Definition at line 686 of file template.cpp.
{ return m_spacelessIntf; }
tabbingEnabled() [1/2]
bool TemplateContextImpl::tabbingEnabled () const [inline]
Definition at line 695 of file template.cpp.
{ return m_tabbingEnabled; }
References m_tabbingEnabled.
Referenced by TemplateNodeTabbing::render().
tabbingEnabled() [2/2]
bool TemplateContextImpl::tabbingEnabled () const [inline]
Definition at line 695 of file template.cpp.
{ return m_tabbingEnabled; }
templateName() [1/2]
QCString TemplateContextImpl::templateName () const [inline]
Definition at line 683 of file template.cpp.
{ return m_templateName; }
References m_templateName.
Referenced by ExprAstFilter::apply(), ExprAstVariable::resolve(), ExprAstBinary::resolve(), setEncoding(), and setLocation().
templateName() [2/2]
QCString TemplateContextImpl::templateName () const [inline]
Definition at line 683 of file template.cpp.
{ return m_templateName; }
warn() [1/2]
void TemplateContextImpl::warn (const QCString & fileName, int line, const char * fmt, ...) const
Definition at line 2772 of file template.cpp.
{
  va_list args;
  va_start(args,fmt);
  va_warn(fileName,line,fmt,args);
  va_end(args);
  m_engine->printIncludeContext(fileName,line);
}
References fmt, line(), m_engine, TemplateEngine::printIncludeContext(), and va_warn().
Referenced by ExprAstFilter::apply(), closeSubIndex(), get(), openSubIndex(), pop(), TemplateNodeCreate::render(), TemplateNodeResource::render(), TemplateNodeIf::render(), TemplateNodeRepeat::render(), TemplateNodeRange::render(), TemplateNodeFor::render(), TemplateNodeExtend::render(), TemplateNodeInclude::render(), TemplateNodeTree::render(), TemplateNodeMarkers::render(), TemplateNodeTree::renderChildren(), ExprAstVariable::resolve(), ExprAstBinary::resolve(), and setEncoding().
warn() [2/2]
void TemplateContextImpl::warn (const QCString & fileName, int line, const char * fmt, ...) const
Member Data Documentation
m_activeEscapeIntf
TemplateEscapeIntf * TemplateContextImpl::m_activeEscapeIntf = 0 [private]
Definition at line 716 of file template.cpp.
Referenced by enableTabbing(), escapeIntf(), selectEscapeIntf(), and setActiveEscapeIntf().
m_blockContext
TemplateBlockContext TemplateContextImpl::m_blockContext [private]
Definition at line 714 of file template.cpp.
Referenced by blockContext().
m_contextStack
std::deque< std::unordered_map< std::string, TemplateVariant > > TemplateContextImpl::m_contextStack [private]
Definition at line 713 of file template.cpp.
Referenced by getRef(), pop(), push(), and set().
m_encoding
QCString TemplateContextImpl::m_encoding [private]
Definition at line 722 of file template.cpp.
Referenced by encoding(), needsRecoding(), and setEncoding().
m_engine
const TemplateEngine * TemplateContextImpl::m_engine = 0 [private]
Definition at line 709 of file template.cpp.
Referenced by warn().
m_escapeIntfMap
EscapeIntfMap TemplateContextImpl::m_escapeIntfMap [private]
Definition at line 715 of file template.cpp.
Referenced by copyEscapeIntfMap(), selectEscapeIntf(), and setEscapeIntf().
m_fromUtf8
void * TemplateContextImpl::m_fromUtf8 = 0 [private]
Definition at line 723 of file template.cpp.
Referenced by recode(), setEncoding(), and TemplateContextImpl().
m_indexStacks
std::unordered_map< std::string, std::stack< TemplateVariant > > TemplateContextImpl::m_indexStacks [private]
Definition at line 721 of file template.cpp.
Referenced by addIndexEntry(), closeSubIndex(), and openSubIndex().
m_indices
TemplateStructPtr TemplateContextImpl::m_indices [private]
Definition at line 720 of file template.cpp.
Referenced by addIndexEntry(), indices(), and TemplateContextImpl().
m_line
int TemplateContextImpl::m_line = 1 [private]
Definition at line 711 of file template.cpp.
Referenced by closeSubIndex(), get(), line(), openSubIndex(), pop(), and setLocation().
m_outputDir
QCString TemplateContextImpl::m_outputDir [private]
Definition at line 712 of file template.cpp.
Referenced by outputDirectory(), and setOutputDirectory().
m_spacelessEnabled
bool TemplateContextImpl::m_spacelessEnabled = false [private]
Definition at line 718 of file template.cpp.
Referenced by enableSpaceless(), and spacelessEnabled().
m_spacelessIntf
std::unique_ptr< TemplateSpacelessIntf > TemplateContextImpl::m_spacelessIntf [private]
Definition at line 717 of file template.cpp.
Referenced by enableSpaceless(), setSpacelessIntf(), spacelessEnabled(), spacelessInfo(), and spacelessIntf().
m_tabbingEnabled
bool TemplateContextImpl::m_tabbingEnabled = false [private]
Definition at line 719 of file template.cpp.
Referenced by enableTabbing(), and tabbingEnabled().
m_templateName
QCString TemplateContextImpl::m_templateName = `<unknown>` [private]
Definition at line 710 of file template.cpp.
Referenced by closeSubIndex(), get(), openSubIndex(), pop(), setLocation(), and templateName().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp