FilterEscape Class Reference
The implementation of the `e` filter.
Static Public Member Functions
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &)
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &)
Detailed Description
The implementation of the `e` filter.
Definition at line 1540 of file template.cpp.
Member Function Documentation
apply() [1/2]
static TemplateVariant FilterEscape::apply (const TemplateVariant & v, const TemplateVariant &) [inline], [static]
Definition at line 1543 of file template.cpp.
    {
      if (v.isValid() && v.isString())
      {
        return convertToHtml(v.toString());
      }
      return v;
    }
References convertToHtml(), TemplateVariant::isString(), TemplateVariant::isValid(), and TemplateVariant::toString().
apply() [2/2]
static TemplateVariant FilterEscape::apply (const TemplateVariant & v, const TemplateVariant &) [inline], [static]
Definition at line 1543 of file template.cpp.
    {
      if (v.isValid() && v.isString())
      {
        return convertToHtml(v.toString());
      }
      return v;
    }
References convertToHtml(), TemplateVariant::isString(), TemplateVariant::isValid(), and TemplateVariant::toString().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp