ClangParser Class Reference
Wrapper for to let libclang assisted parsing.
#include <clangparser.h>
Classes
class Private
Public Member Functions
std::unique_ptr< ClangTUParser > createTUParser (const FileDef *fd) const
std::unique_ptr< ClangTUParser > createTUParser (const FileDef *fd) const
Static Public Member Functions
static ClangParser * instance ()
static ClangParser * instance ()
Private Member Functions
const clang::tooling::CompilationDatabase * database () const
ClangParser ()
virtual ~ClangParser ()
const clang::tooling::CompilationDatabase * database () const
ClangParser ()
virtual ~ClangParser ()
Private Attributes
std::unique_ptr< Private > p
Static Private Attributes
static ClangParser * s_instance = 0
Friends
class ClangTUParser
Detailed Description
Wrapper for to let libclang assisted parsing.
Definition at line 75 of file clangparser.h.
Constructor & Destructor Documentation
ClangParser() [1/2]
ClangParser::ClangParser () [private]
Definition at line 940 of file clangparser.cpp.
                         : p(std::make_unique<Private>())
{
}
Referenced by instance().
 ClangParser() [1/2]
ClangParser::~ClangParser () [private], [virtual]
Definition at line 944 of file clangparser.cpp.
{
}
ClangParser() [2/2]
ClangParser::ClangParser () [private]
 ClangParser() [2/2]
virtual ClangParser::~ClangParser () [private], [virtual]
Member Function Documentation
createTUParser() [1/2]
std::unique_ptr< ClangTUParser > ClangParser::createTUParser (const FileDef * fd) const
Definition at line 948 of file clangparser.cpp.
{
  return nullptr;
}
Referenced by generateFileSources(), parseFilesMultiThreading(), and parseFilesSingleThreading().
createTUParser() [2/2]
std::unique_ptr< ClangTUParser > ClangParser::createTUParser (const FileDef * fd) const
database() [1/2]
const clang::tooling::CompilationDatabase * ClangParser::database () const [private]
database() [2/2]
const clang::tooling::CompilationDatabase * ClangParser::database () const [private]
instance() [1/2]
ClangParser * ClangParser::instance () [static]
Returns the one and only instance of the class
Definition at line 29 of file clangparser.cpp.
{
  std::lock_guard<std::mutex> lock(g_clangMutex);
  if (!s_instance) s_instance = new ClangParser;
  return s_instance;
}
References ClangParser(), g_clangMutex, and s_instance.
Referenced by generateFileSources(), parseFilesMultiThreading(), and parseFilesSingleThreading().
instance() [2/2]
static ClangParser * ClangParser::instance () [static]
Returns the one and only instance of the class
Friends And Related Function Documentation
ClangTUParser
ClangTUParser [friend]
Definition at line 77 of file clangparser.h.
Member Data Documentation
p
std::unique_ptr< Private > ClangParser::p [private]
Definition at line 86 of file clangparser.h.
s_instance
static ClangParser * ClangParser::s_instance = 0 [static], [private]
Definition at line 89 of file clangparser.h.
Referenced by instance().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/clangparser.h
doxygen/src/clangparser.h
doxygen/build/doxygen/src/clangparser.cpp
doxygen/src/clangparser.cpp