TemplateNodeBlock Class Reference
Class representing a 'block' tag in a template.
Public Member Functions
TemplateNodeBlock (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void render (TextStream &ts, TemplateContext *c)
QCString name () const
TemplateNodeBlock (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void render (TextStream &ts, TemplateContext *c)
QCString name () const
Private Attributes
QCString m_blockName
TemplateNodeList m_nodes
Additional Inherited Members
Detailed Description
Class representing a 'block' tag in a template.
Definition at line 3599 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeBlock() [1/2]
TemplateNodeBlock::TemplateNodeBlock (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 3602 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeBlock>(parser,parent,line)
    {
      TRACE(("{TemplateNodeBlock(%s)\n",qPrint(data)));
      m_blockName = data;
      if (m_blockName.isEmpty())
      {
        parser->warn(parser->templateName(),line,"block tag without name");
      }
      StringVector stopAt = { "endblock" };
      parser->parse(this,line,stopAt,m_nodes);
      parser->removeNextToken(); // skip over endblock
      TRACE(("}TemplateNodeBlock(%s)\n",qPrint(data)));
    }
References data, QCString::isEmpty(), m_blockName, m_nodes, TemplateParser::parse(), qPrint(), TemplateParser::removeNextToken(), TemplateParser::templateName(), TRACE, and TemplateParser::warn().
TemplateNodeBlock() [2/2]
TemplateNodeBlock::TemplateNodeBlock (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 3602 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeBlock>(parser,parent,line)
    {
      TRACE(("{TemplateNodeBlock(%s)\n",qPrint(data)));
      m_blockName = data;
      if (m_blockName.isEmpty())
      {
        parser->warn(parser->templateName(),line,"block tag without name");
      }
      StringVector stopAt = { "endblock" };
      parser->parse(this,line,stopAt,m_nodes);
      parser->removeNextToken(); // skip over endblock
      TRACE(("}TemplateNodeBlock(%s)\n",qPrint(data)));
    }
References data, QCString::isEmpty(), m_blockName, m_nodes, TemplateParser::parse(), qPrint(), TemplateParser::removeNextToken(), TemplateParser::templateName(), TRACE, and TemplateParser::warn().
Member Function Documentation
name() [1/2]
QCString TemplateNodeBlock::name () const [inline]
Definition at line 3663 of file template.cpp.
    {
      return m_blockName;
    }
References m_blockName.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
name() [2/2]
QCString TemplateNodeBlock::name () const [inline]
Definition at line 3663 of file template.cpp.
    {
      return m_blockName;
    }
References m_blockName.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
render() [1/2]
void TemplateNodeBlock::render (TextStream & ts, TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 3617 of file template.cpp.
    {
      TemplateContextImpl *ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      TemplateImpl *t = getTemplate();
      if (t)
      {
        // remove block from the context, so block.super can work
        TemplateNodeBlock *nb = ci->blockContext()->pop(m_blockName);
        if (nb) // block is overruled
        {
          ci->push();
          TextStream ss;
          // get super block of block nb
          TemplateNodeBlock *sb = ci->blockContext()->get(m_blockName);
          if (sb && sb!=nb && sb!=this) // nb and sb both overrule this block
          {
            sb->render(ss,c); // render parent of nb to string
          }
          else if (nb!=this) // only nb overrules this block
          {
            m_nodes.render(ss,c); // render parent of nb to string
          }
          QCString super = ss.str();
          // add 'block.super' variable to allow access to parent block content
          TemplateStructPtr superBlock = TemplateStruct::alloc();
          superBlock->set("super",TemplateVariant(super.data(),TRUE));
          ci->set("block",std::static_pointer_cast<TemplateStructIntf>(superBlock));
          // render the overruled block contents
          t->engine()->enterBlock(nb->m_templateName,nb->m_blockName,nb->m_line);
          nb->m_nodes.render(ts,c);
          t->engine()->leaveBlock();
          ci->pop();
          // re-add block to the context
          ci->blockContext()->push(nb);
        }
        else // block has no overrule
        {
          t->engine()->enterBlock(m_templateName,m_blockName,m_line);
          m_nodes.render(ts,c);
          t->engine()->leaveBlock();
        }
      }
    }
References TemplateStruct::alloc(), TemplateContextImpl::blockContext(), c, QCString::data(), TemplateImpl::engine(), TemplateEngine::enterBlock(), TemplateBlockContext::get(), TemplateNodeCreator< TemplateNodeBlock >::getTemplate(), TemplateEngine::leaveBlock(), m_blockName, TemplateNodeCreator< T >::m_line, TemplateNodeCreator< TemplateNodeBlock >::m_line, m_nodes, TemplateNodeCreator< T >::m_templateName, TemplateNodeCreator< TemplateNodeBlock >::m_templateName, TemplateContextImpl::pop(), TemplateBlockContext::pop(), TemplateContextImpl::push(), TemplateBlockContext::push(), TemplateNodeList::render(), render(), TemplateContextImpl::set(), TemplateContextImpl::setLocation(), TextStream::str(), and TRUE.
Referenced by render().
render() [2/2]
void TemplateNodeBlock::render (TextStream & ts, TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 3617 of file template.cpp.
    {
      TemplateContextImpl *ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      ci->setLocation(m_templateName,m_line);
      TemplateImpl *t = getTemplate();
      if (t)
      {
        // remove block from the context, so block.super can work
        TemplateNodeBlock *nb = ci->blockContext()->pop(m_blockName);
        if (nb) // block is overruled
        {
          ci->push();
          TextStream ss;
          // get super block of block nb
          TemplateNodeBlock *sb = ci->blockContext()->get(m_blockName);
          if (sb && sb!=nb && sb!=this) // nb and sb both overrule this block
          {
            sb->render(ss,c); // render parent of nb to string
          }
          else if (nb!=this) // only nb overrules this block
          {
            m_nodes.render(ss,c); // render parent of nb to string
          }
          QCString super = ss.str();
          // add 'block.super' variable to allow access to parent block content
          TemplateStructPtr superBlock = TemplateStruct::alloc();
          superBlock->set("super",TemplateVariant(super.data(),TRUE));
          ci->set("block",std::static_pointer_cast<TemplateStructIntf>(superBlock));
          // render the overruled block contents
          t->engine()->enterBlock(nb->m_templateName,nb->m_blockName,nb->m_line);
          nb->m_nodes.render(ts,c);
          t->engine()->leaveBlock();
          ci->pop();
          // re-add block to the context
          ci->blockContext()->push(nb);
        }
        else // block has no overrule
        {
          t->engine()->enterBlock(m_templateName,m_blockName,m_line);
          m_nodes.render(ts,c);
          t->engine()->leaveBlock();
        }
      }
    }
References TemplateStruct::alloc(), TemplateContextImpl::blockContext(), c, QCString::data(), TemplateImpl::engine(), TemplateEngine::enterBlock(), TemplateBlockContext::get(), TemplateNodeCreator< TemplateNodeBlock >::getTemplate(), TemplateEngine::leaveBlock(), m_blockName, TemplateNodeCreator< T >::m_line, TemplateNodeCreator< TemplateNodeBlock >::m_line, m_nodes, TemplateNodeCreator< T >::m_templateName, TemplateNodeCreator< TemplateNodeBlock >::m_templateName, TemplateContextImpl::pop(), TemplateBlockContext::pop(), TemplateContextImpl::push(), TemplateBlockContext::push(), TemplateNodeList::render(), render(), TemplateContextImpl::set(), TemplateContextImpl::setLocation(), TextStream::str(), and TRUE.
Member Data Documentation
m_blockName
QCString TemplateNodeBlock::m_blockName [private]
Definition at line 3669 of file template.cpp.
Referenced by name(), render(), and TemplateNodeBlock().
m_nodes
TemplateNodeList TemplateNodeBlock::m_nodes [private]
Definition at line 3670 of file template.cpp.
Referenced by render(), and TemplateNodeBlock().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp