DocIncOperator Class Reference
#include <docnode.h>
Public Types
enum Type {
Line
, SkipLine
, Skip
, Until
,
Line
, SkipLine
, Skip
, Until
 }
enum Type {
Line
, SkipLine
, Skip
, Until
,
Line
, SkipLine
, Skip
, Until
 }
Public Member Functions
DocIncOperator (DocParser *parser, DocNodeVariant *parent, Type t, const QCString &pat, const QCString &context, bool isExample, const QCString &exampleFile)
Type type () const
const char * typeAsString () const
int line () const
bool showLineNo () const
QCString text () const
QCString pattern () const
QCString context () const
bool isFirst () const
bool isLast () const
void markFirst (bool v=TRUE)
void markLast (bool v=TRUE)
bool isExample () const
QCString exampleFile () const
QCString includeFileName () const
void parse (DocNodeVariant *)
DocIncOperator (DocParser *parser, DocNodeVariant *parent, Type t, const QCString &pat, const QCString &context, bool isExample, const QCString &exampleFile)
Type type () const
const char * typeAsString () const
int line () const
bool showLineNo () const
QCString text () const
QCString pattern () const
QCString context () const
bool isFirst () const
bool isLast () const
void markFirst (bool v=TRUE)
void markLast (bool v=TRUE)
bool isExample () const
QCString exampleFile () const
QCString includeFileName () const
void parse (DocNodeVariant *)
Private Attributes
Type m_type = Line
int m_line = 0
bool m_showLineNo = false
QCString m_text
QCString m_pattern
QCString m_context
bool m_isFirst = false
bool m_isLast = false
bool m_isExample = false
QCString m_exampleFile
QCString m_includeFileName
Additional Inherited Members
Detailed Description
Node representing a include/dontinclude operator block
Definition at line 449 of file docnode.h.
Member Enumeration Documentation
Type [1/2]
enum DocIncOperator::Type
Enumerator
Line
SkipLine
Skip
Until
Line
SkipLine
Skip
Until
Definition at line 452 of file docnode.h.
{ Line, SkipLine, Skip, Until };
Type [2/2]
enum DocIncOperator::Type
Enumerator
Line
SkipLine
Skip
Until
Line
SkipLine
Skip
Until
Definition at line 452 of file docnode.h.
{ Line, SkipLine, Skip, Until };
Constructor & Destructor Documentation
DocIncOperator() [1/2]
DocIncOperator::DocIncOperator (DocParser * parser, DocNodeVariant * parent, Type t, const QCString & pat, const QCString & context, bool isExample, const QCString & exampleFile) [inline]
Definition at line 453 of file docnode.h.
    : DocNode(parser,parent), m_type(t), m_pattern(pat), m_context(context),
      m_isFirst(FALSE), m_isLast(FALSE),
      m_isExample(isExample), m_exampleFile(exampleFile) {}
DocIncOperator() [2/2]
DocIncOperator::DocIncOperator (DocParser * parser, DocNodeVariant * parent, Type t, const QCString & pat, const QCString & context, bool isExample, const QCString & exampleFile) [inline]
Definition at line 453 of file docnode.h.
    : DocNode(parser,parent), m_type(t), m_pattern(pat), m_context(context),
      m_isFirst(FALSE), m_isLast(FALSE),
      m_isExample(isExample), m_exampleFile(exampleFile) {}
Member Function Documentation
context() [1/2]
QCString DocIncOperator::context () const [inline]
Definition at line 474 of file docnode.h.
{ return m_context; }
References m_context.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), and parse().
context() [2/2]
QCString DocIncOperator::context () const [inline]
Definition at line 474 of file docnode.h.
{ return m_context; }
References m_context.
exampleFile() [1/2]
QCString DocIncOperator::exampleFile () const [inline]
Definition at line 480 of file docnode.h.
{ return m_exampleFile; }
References m_exampleFile.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
exampleFile() [2/2]
QCString DocIncOperator::exampleFile () const [inline]
Definition at line 480 of file docnode.h.
{ return m_exampleFile; }
References m_exampleFile.
includeFileName() [1/2]
QCString DocIncOperator::includeFileName () const [inline]
Definition at line 481 of file docnode.h.
{ return m_includeFileName; }
References m_includeFileName.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
includeFileName() [2/2]
QCString DocIncOperator::includeFileName () const [inline]
Definition at line 481 of file docnode.h.
{ return m_includeFileName; }
References m_includeFileName.
isExample() [1/2]
bool DocIncOperator::isExample () const [inline]
Definition at line 479 of file docnode.h.
{ return m_isExample; }
References m_isExample.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
isExample() [2/2]
bool DocIncOperator::isExample () const [inline]
Definition at line 479 of file docnode.h.
{ return m_isExample; }
References m_isExample.
isFirst() [1/2]
bool DocIncOperator::isFirst () const [inline]
Definition at line 475 of file docnode.h.
{ return m_isFirst; }
References m_isFirst.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
isFirst() [2/2]
bool DocIncOperator::isFirst () const [inline]
Definition at line 475 of file docnode.h.
{ return m_isFirst; }
References m_isFirst.
isLast() [1/2]
bool DocIncOperator::isLast () const [inline]
Definition at line 476 of file docnode.h.
{ return m_isLast; }
References m_isLast.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
isLast() [2/2]
bool DocIncOperator::isLast () const [inline]
Definition at line 476 of file docnode.h.
{ return m_isLast; }
References m_isLast.
line() [1/2]
int DocIncOperator::line () const [inline]
Definition at line 470 of file docnode.h.
{ return m_line; }
References m_line.
Referenced by doxmlparser.compound.locationType::__init__(), doxmlparser.compound.locationType::buildAttributes(), doxmlparser.compound.locationType::exportAttributes(), doxmlparser.compound.locationType::get_line(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), and doxmlparser.compound.locationType::set_line().
line() [2/2]
int DocIncOperator::line () const [inline]
Definition at line 470 of file docnode.h.
{ return m_line; }
References m_line.
Referenced by doxmlparser.compound.locationType::__init__(), doxmlparser.compound.locationType::buildAttributes(), doxmlparser.compound.locationType::exportAttributes(), doxmlparser.compound.locationType::get_line(), and doxmlparser.compound.locationType::set_line().
markFirst() [1/2]
void DocIncOperator::markFirst (bool v = TRUE) [inline]
Definition at line 477 of file docnode.h.
{ m_isFirst = v; }
References m_isFirst.
markFirst() [2/2]
void DocIncOperator::markFirst (bool v = TRUE) [inline]
Definition at line 477 of file docnode.h.
{ m_isFirst = v; }
References m_isFirst.
markLast() [1/2]
void DocIncOperator::markLast (bool v = TRUE) [inline]
Definition at line 478 of file docnode.h.
{ m_isLast = v; }
References m_isLast.
Referenced by DocPara::handleIncludeOperator().
markLast() [2/2]
void DocIncOperator::markLast (bool v = TRUE) [inline]
Definition at line 478 of file docnode.h.
{ m_isLast = v; }
References m_isLast.
parse() [1/2]
void DocIncOperator::parse (DocNodeVariant *)
Definition at line 317 of file docnode.cpp.
{
  if (parser()->context.includeFileName.isEmpty())
  {
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),
                   "No previous '\\include' or '\\dontinclude' command for '\\%s' present",
                   typeAsString());
  }
  m_includeFileName = parser()->context.includeFileName;
  const char *p = parser()->context.includeFileText.data();
  uint l = parser()->context.includeFileLength;
  uint o = parser()->context.includeFileOffset;
  int il = parser()->context.includeFileLine;
  DBG(("DocIncOperator::parse() text=%s off=%d len=%d\n",p,o,l));
  uint so = o,bo;
  bool nonEmpty = FALSE;
  switch(type())
  {
    case Line:
      while (o<l)
      {
        char c = p[o];
        if (c=='\n')
        {
          parser()->context.includeFileLine++;
          if (nonEmpty) break; // we have a pattern to match
          so=o+1; // no pattern, skip empty line
        }
        else if (!isspace(static_cast<uchar>(c))) // no white space char
        {
          nonEmpty=TRUE;
        }
        o++;
      }
      if (parser()->context.includeFileText.mid(so,o-so).find(m_pattern)!=-1)
      {
        m_line = il;
        m_text = parser()->context.includeFileText.mid(so,o-so);
        DBG(("DocIncOperator::parse() Line: %s\n",qPrint(m_text)));
      }
      parser()->context.includeFileOffset = std::min(l,o+1); // set pointer to start of new line
      m_showLineNo = parser()->context.includeFileShowLineNo;
      break;
    case SkipLine:
      while (o<l)
      {
        so=o;
        while (o<l)
        {
          char c = p[o];
          if (c=='\n')
          {
            parser()->context.includeFileLine++;
            if (nonEmpty) break; // we have a pattern to match
            so=o+1; // no pattern, skip empty line
          }
          else if (!isspace(static_cast<uchar>(c))) // no white space char
          {
            nonEmpty=TRUE;
          }
          o++;
        }
        if (parser()->context.includeFileText.mid(so,o-so).find(m_pattern)!=-1)
        {
          m_line = il;
          m_text = parser()->context.includeFileText.mid(so,o-so);
          DBG(("DocIncOperator::parse() SkipLine: %s\n",qPrint(m_text)));
          break;
        }
        o++; // skip new line
      }
      parser()->context.includeFileOffset = std::min(l,o+1); // set pointer to start of new line
      m_showLineNo = parser()->context.includeFileShowLineNo;
      break;
    case Skip:
      while (o<l)
      {
        so=o;
        while (o<l)
        {
          char c = p[o];
          if (c=='\n')
          {
            parser()->context.includeFileLine++;
            if (nonEmpty) break; // we have a pattern to match
            so=o+1; // no pattern, skip empty line
          }
          else if (!isspace(static_cast<uchar>(c))) // no white space char
          {
            nonEmpty=TRUE;
          }
          o++;
        }
        if (parser()->context.includeFileText.mid(so,o-so).find(m_pattern)!=-1)
        {
          break;
        }
        o++; // skip new line
      }
      parser()->context.includeFileOffset = so; // set pointer to start of new line
      m_showLineNo = parser()->context.includeFileShowLineNo;
      break;
    case Until:
      bo=o;
      while (o<l)
      {
        so=o;
        while (o<l)
        {
          char c = p[o];
          if (c=='\n')
          {
            parser()->context.includeFileLine++;
            if (nonEmpty) break; // we have a pattern to match
            so=o+1; // no pattern, skip empty line
          }
          else if (!isspace(static_cast<uchar>(c))) // no white space char
          {
            nonEmpty=TRUE;
          }
          o++;
        }
        if (parser()->context.includeFileText.mid(so,o-so).find(m_pattern)!=-1)
        {
          m_line = il;
          m_text = parser()->context.includeFileText.mid(bo,o-bo);
          DBG(("DocIncOperator::parse() Until: %s\n",qPrint(m_text)));
          break;
        }
        o++; // skip new line
      }
      parser()->context.includeFileOffset = std::min(l,o+1); // set pointer to start of new line
      m_showLineNo = parser()->context.includeFileShowLineNo;
      break;
  }
}
References c, context(), DocParser::context, QCString::data(), DBG, FALSE, QCString::find(), DocParserContext::includeFileLength, DocParserContext::includeFileLine, DocParserContext::includeFileName, DocParserContext::includeFileOffset, DocParserContext::includeFileShowLineNo, DocParserContext::includeFileText, QCString::isEmpty(), reg::isspace(), Line, m_includeFileName, m_line, m_pattern, m_showLineNo, m_text, QCString::mid(), p, DocNode::parser(), qPrint(), Skip, SkipLine, TRUE, type(), typeAsString(), Until, and warn_doc_error().
parse() [2/2]
void DocIncOperator::parse (DocNodeVariant *)
pattern() [1/2]
QCString DocIncOperator::pattern () const [inline]
Definition at line 473 of file docnode.h.
{ return m_pattern; }
References m_pattern.
Referenced by PrintDocVisitor::operator()().
pattern() [2/2]
QCString DocIncOperator::pattern () const [inline]
Definition at line 473 of file docnode.h.
{ return m_pattern; }
References m_pattern.
showLineNo() [1/2]
bool DocIncOperator::showLineNo () const [inline]
Definition at line 471 of file docnode.h.
{ return m_showLineNo; }
References m_showLineNo.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
showLineNo() [2/2]
bool DocIncOperator::showLineNo () const [inline]
Definition at line 471 of file docnode.h.
{ return m_showLineNo; }
References m_showLineNo.
text() [1/2]
QCString DocIncOperator::text () const [inline]
Definition at line 472 of file docnode.h.
{ return m_text; }
References m_text.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
text() [2/2]
QCString DocIncOperator::text () const [inline]
Definition at line 472 of file docnode.h.
{ return m_text; }
References m_text.
type() [1/2]
Type DocIncOperator::type () const [inline]
Definition at line 458 of file docnode.h.
{ return m_type; }
References m_type.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), PrintDocVisitor::operator()(), and parse().
type() [2/2]
Type DocIncOperator::type () const [inline]
Definition at line 458 of file docnode.h.
{ return m_type; }
References m_type.
typeAsString() [1/2]
const char * DocIncOperator::typeAsString () const [inline]
Definition at line 459 of file docnode.h.
    {
      switch(m_type)
      {
        case Line: return "line";
        case SkipLine: return "skipline";
        case Skip: return "skip";
        case Until: return "until";
      }
      return "";
    }
References Line, m_type, Skip, SkipLine, and Until.
Referenced by parse().
typeAsString() [2/2]
const char * DocIncOperator::typeAsString () const [inline]
Definition at line 459 of file docnode.h.
    {
      switch(m_type)
      {
        case Line: return "line";
        case SkipLine: return "skipline";
        case Skip: return "skip";
        case Until: return "until";
      }
      return "";
    }
References Line, m_type, Skip, SkipLine, and Until.
Member Data Documentation
m_context
QCString DocIncOperator::m_context [private]
Definition at line 490 of file docnode.h.
Referenced by context().
m_exampleFile
QCString DocIncOperator::m_exampleFile [private]
Definition at line 494 of file docnode.h.
Referenced by exampleFile().
m_includeFileName
QCString DocIncOperator::m_includeFileName [private]
Definition at line 495 of file docnode.h.
Referenced by includeFileName(), and parse().
m_isExample
bool DocIncOperator::m_isExample = false [private]
Definition at line 493 of file docnode.h.
Referenced by isExample().
m_isFirst
bool DocIncOperator::m_isFirst = false [private]
Definition at line 491 of file docnode.h.
Referenced by isFirst(), and markFirst().
m_isLast
bool DocIncOperator::m_isLast = false [private]
Definition at line 492 of file docnode.h.
Referenced by isLast(), and markLast().
m_line
int DocIncOperator::m_line = 0 [private]
Definition at line 486 of file docnode.h.
Referenced by line(), and parse().
m_pattern
QCString DocIncOperator::m_pattern [private]
Definition at line 489 of file docnode.h.
Referenced by parse(), and pattern().
m_showLineNo
bool DocIncOperator::m_showLineNo = false [private]
Definition at line 487 of file docnode.h.
Referenced by parse(), and showLineNo().
m_text
QCString DocIncOperator::m_text [private]
Definition at line 488 of file docnode.h.
Referenced by parse(), and text().
m_type
Type DocIncOperator::m_type = Line [private]
Definition at line 485 of file docnode.h.
Referenced by type(), and typeAsString().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docnode.h
doxygen/src/docnode.h
doxygen/build/doxygen/src/docnode.cpp
doxygen/src/docnode.cpp