TranslatorAdapter_1_7_5 Class Reference
#include <translator_adapter.h>
Public Member Functions
virtual QCString updateNeededMessage ()
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayPeriod (int period)
virtual QCString updateNeededMessage ()
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayPeriod (int period)
Additional Inherited Members
Detailed Description
Adapter class for languages that only contain translations up to version 1.7.5.
Definition at line 314 of file translator_adapter.h.
Member Function Documentation
trCiteReferences() [1/2]
virtual QCString TranslatorAdapter_1_7_5::trCiteReferences () [inline], [virtual]
Implements Translator.
Definition at line 320 of file translator_adapter.h.
    { return english.trCiteReferences(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trCiteReferences().
trCiteReferences() [2/2]
virtual QCString TranslatorAdapter_1_7_5::trCiteReferences () [inline], [virtual]
Implements Translator.
Definition at line 320 of file translator_adapter.h.
    { return english.trCiteReferences(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trCiteReferences().
trCopyright() [1/2]
virtual QCString TranslatorAdapter_1_7_5::trCopyright () [inline], [virtual]
Implements Translator.
Definition at line 323 of file translator_adapter.h.
    { return english.trCopyright(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trCopyright().
trCopyright() [2/2]
virtual QCString TranslatorAdapter_1_7_5::trCopyright () [inline], [virtual]
Implements Translator.
Definition at line 323 of file translator_adapter.h.
    { return english.trCopyright(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trCopyright().
trDateTime() [1/2]
virtual QCString TranslatorAdapter_1_7_5::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorPersian, TranslatorTurkish, TranslatorPersian, and TranslatorTurkish.
Definition at line 333 of file translator_adapter.h.
    { return english.trDateTime(year,month,day,dayOfWeek,hour,minutes,seconds,includeTime); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trDateTime().
trDateTime() [2/2]
virtual QCString TranslatorAdapter_1_7_5::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorPersian, TranslatorTurkish, TranslatorPersian, and TranslatorTurkish.
Definition at line 333 of file translator_adapter.h.
    { return english.trDateTime(year,month,day,dayOfWeek,hour,minutes,seconds,includeTime); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trDateTime().
trDayPeriod() [1/2]
virtual QCString TranslatorAdapter_1_7_5::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorArabic, TranslatorPersian, TranslatorFinnish, TranslatorLithuanian, TranslatorMacedonian, TranslatorNorwegian, TranslatorSerbianCyrillic, TranslatorSlovene, TranslatorSerbian, TranslatorTurkish, TranslatorVietnamese, TranslatorAfrikaans, TranslatorArabic, TranslatorPersian, TranslatorFinnish, TranslatorLithuanian, TranslatorMacedonian, TranslatorNorwegian, TranslatorSerbianCyrillic, TranslatorSlovene, TranslatorSerbian, TranslatorTurkish, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 337 of file translator_adapter.h.
    { return english.trDayPeriod(period); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trDayPeriod().
trDayPeriod() [2/2]
virtual QCString TranslatorAdapter_1_7_5::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorArabic, TranslatorPersian, TranslatorFinnish, TranslatorLithuanian, TranslatorMacedonian, TranslatorNorwegian, TranslatorSerbianCyrillic, TranslatorSlovene, TranslatorSerbian, TranslatorTurkish, TranslatorVietnamese, TranslatorAfrikaans, TranslatorArabic, TranslatorPersian, TranslatorFinnish, TranslatorLithuanian, TranslatorMacedonian, TranslatorNorwegian, TranslatorSerbianCyrillic, TranslatorSlovene, TranslatorSerbian, TranslatorTurkish, TranslatorVietnamese, and TranslatorAfrikaans.
Definition at line 337 of file translator_adapter.h.
    { return english.trDayPeriod(period); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trDayPeriod().
trDirDepGraph() [1/2]
virtual QCString TranslatorAdapter_1_7_5::trDirDepGraph (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 326 of file translator_adapter.h.
    { return english.trDirDepGraph(name); }
References TranslatorAdapterBase::english, setup::name, and TranslatorEnglish::trDirDepGraph().
trDirDepGraph() [2/2]
virtual QCString TranslatorAdapter_1_7_5::trDirDepGraph (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 326 of file translator_adapter.h.
    { return english.trDirDepGraph(name); }
References TranslatorAdapterBase::english, setup::name, and TranslatorEnglish::trDirDepGraph().
trFileIn() [1/2]
virtual QCString TranslatorAdapter_1_7_5::trFileIn (const QCString & name) [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorPersian, TranslatorTurkish, TranslatorPersian, and TranslatorTurkish.
Definition at line 329 of file translator_adapter.h.
    { return english.trFileIn(name); }
References TranslatorAdapterBase::english, setup::name, and TranslatorEnglish::trFileIn().
trFileIn() [2/2]
virtual QCString TranslatorAdapter_1_7_5::trFileIn (const QCString & name) [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorPersian, TranslatorTurkish, TranslatorPersian, and TranslatorTurkish.
Definition at line 329 of file translator_adapter.h.
    { return english.trFileIn(name); }
References TranslatorAdapterBase::english, setup::name, and TranslatorEnglish::trFileIn().
trIncludesFileIn() [1/2]
virtual QCString TranslatorAdapter_1_7_5::trIncludesFileIn (const QCString & name) [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorPersian, TranslatorTurkish, TranslatorPersian, and TranslatorTurkish.
Definition at line 331 of file translator_adapter.h.
    { return english.trIncludesFileIn(name); }
References TranslatorAdapterBase::english, setup::name, and TranslatorEnglish::trIncludesFileIn().
trIncludesFileIn() [2/2]
virtual QCString TranslatorAdapter_1_7_5::trIncludesFileIn (const QCString & name) [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorPersian, TranslatorTurkish, TranslatorPersian, and TranslatorTurkish.
Definition at line 331 of file translator_adapter.h.
    { return english.trIncludesFileIn(name); }
References TranslatorAdapterBase::english, setup::name, and TranslatorEnglish::trIncludesFileIn().
updateNeededMessage() [1/2]
virtual QCString TranslatorAdapter_1_7_5::updateNeededMessage () [inline], [virtual]
This method is used to generate a warning message to signal the user that the translation of his/her language of choice needs updating. It must be implemented by the translator adapter class (pure virtual).
See also
createUpdateNeededMessage()
Reimplemented from TranslatorAdapter_1_8_0.
Reimplemented in TranslatorAdapter_1_6_0, TranslatorAdapter_1_4_6, TranslatorAdapter_1_6_0, and TranslatorAdapter_1_4_6.
Definition at line 317 of file translator_adapter.h.
    { return createUpdateNeededMessage(idLanguage(),"release 1.7.5"); }
References TranslatorAdapterBase::createUpdateNeededMessage(), and Translator::idLanguage().
updateNeededMessage() [2/2]
virtual QCString TranslatorAdapter_1_7_5::updateNeededMessage () [inline], [virtual]
This method is used to generate a warning message to signal the user that the translation of his/her language of choice needs updating. It must be implemented by the translator adapter class (pure virtual).
See also
createUpdateNeededMessage()
Reimplemented from TranslatorAdapter_1_8_0.
Reimplemented in TranslatorAdapter_1_6_0, TranslatorAdapter_1_4_6, TranslatorAdapter_1_6_0, and TranslatorAdapter_1_4_6.
Definition at line 317 of file translator_adapter.h.
    { return createUpdateNeededMessage(idLanguage(),"release 1.7.5"); }
References TranslatorAdapterBase::createUpdateNeededMessage(), and Translator::idLanguage().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_adapter.h
doxygen/src/translator_adapter.h