DocDiagramFileBase Class Reference
#include <docnode.h>
Classes
struct Private
Public Member Functions
DocDiagramFileBase (DocParser *parser, DocNodeVariant *parent, const QCString &name, const QCString &context, const QCString &srcFile, int srcLine)
QCString name () const
QCString file () const
QCString relPath () const
bool hasCaption () const
QCString width () const
QCString height () const
QCString context () const
QCString srcFile () const
int srcLine () const
DocDiagramFileBase (DocParser *parser, DocNodeVariant *parent, const QCString &name, const QCString &context, const QCString &srcFile, int srcLine)
QCString name () const
QCString file () const
QCString relPath () const
bool hasCaption () const
QCString width () const
QCString height () const
QCString context () const
QCString srcFile () const
int srcLine () const
Protected Attributes
std::unique_ptr< Private > p
Additional Inherited Members
Detailed Description
Definition at line 642 of file docnode.h.
Constructor & Destructor Documentation
DocDiagramFileBase() [1/2]
DocDiagramFileBase::DocDiagramFileBase (DocParser * parser, DocNodeVariant * parent, const QCString & name, const QCString & context, const QCString & srcFile, int srcLine) [inline]
Definition at line 645 of file docnode.h.
    : DocCompoundNode(parser,parent), p(std::make_unique<Private>(name, context, srcFile, srcLine)) {}
DocDiagramFileBase() [2/2]
DocDiagramFileBase::DocDiagramFileBase (DocParser * parser, DocNodeVariant * parent, const QCString & name, const QCString & context, const QCString & srcFile, int srcLine) [inline]
Definition at line 645 of file docnode.h.
    : DocCompoundNode(parser,parent), p(std::make_unique<Private>(name, context, srcFile, srcLine)) {}
Member Function Documentation
context() [1/2]
QCString DocDiagramFileBase::context () const [inline]
Definition at line 654 of file docnode.h.
{ return p->context; }
References p.
Referenced by HtmlDocVisitor::operator()(), DocDotFile::parse(), DocMscFile::parse(), and DocDiaFile::parse().
context() [2/2]
QCString DocDiagramFileBase::context () const [inline]
Definition at line 654 of file docnode.h.
{ return p->context; }
References p.
file() [1/2]
QCString DocDiagramFileBase::file () const [inline]
Definition at line 649 of file docnode.h.
{ return p->file; }
References p.
Referenced by doxmlparser.compound.locationType::__init__(), doxmlparser.compound.locationType::buildAttributes(), doxmlparser.compound.locationType::exportAttributes(), doxmlparser.compound.locationType::get_file(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), PerlModDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), doxmlparser.compound.locationType::set_file(), RTFDocVisitor::writeDiaFile(), RTFDocVisitor::writeDotFile(), and RTFDocVisitor::writeMscFile().
file() [2/2]
QCString DocDiagramFileBase::file () const [inline]
Definition at line 649 of file docnode.h.
{ return p->file; }
References p.
Referenced by doxmlparser.compound.locationType::__init__(), doxmlparser.compound.locationType::buildAttributes(), doxmlparser.compound.locationType::exportAttributes(), doxmlparser.compound.locationType::get_file(), and doxmlparser.compound.locationType::set_file().
hasCaption() [1/2]
bool DocDiagramFileBase::hasCaption () const [inline]
Definition at line 651 of file docnode.h.
{ return !children().empty(); }
References DocCompoundNode::children(), and GrowVector< T >::empty().
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), RTFDocVisitor::operator()(), RTFDocVisitor::writeDiaFile(), RTFDocVisitor::writeDotFile(), and RTFDocVisitor::writeMscFile().
hasCaption() [2/2]
bool DocDiagramFileBase::hasCaption () const [inline]
Definition at line 651 of file docnode.h.
{ return !children().empty(); }
References DocCompoundNode::children(), and GrowVector< T >::empty().
height() [1/2]
QCString DocDiagramFileBase::height () const [inline]
Definition at line 653 of file docnode.h.
{ return p->height; }
References p.
Referenced by doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.compound.docImageType::get_height(), doxmlparser.compound.docDotMscType::get_height(), doxmlparser.compound.docImageFileType::get_height(), doxmlparser.compound.docPlantumlType::get_height(), DocbookDocVisitor::operator()(), LatexDocVisitor::operator()(), XmlDocVisitor::operator()(), doxmlparser.compound.docImageType::set_height(), doxmlparser.compound.docDotMscType::set_height(), doxmlparser.compound.docImageFileType::set_height(), and doxmlparser.compound.docPlantumlType::set_height().
height() [2/2]
QCString DocDiagramFileBase::height () const [inline]
Definition at line 653 of file docnode.h.
{ return p->height; }
References p.
Referenced by doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.compound.docImageType::get_height(), doxmlparser.compound.docDotMscType::get_height(), doxmlparser.compound.docImageFileType::get_height(), doxmlparser.compound.docPlantumlType::get_height(), doxmlparser.compound.docImageType::set_height(), doxmlparser.compound.docDotMscType::set_height(), doxmlparser.compound.docImageFileType::set_height(), and doxmlparser.compound.docPlantumlType::set_height().
name() [1/2]
QCString DocDiagramFileBase::name () const [inline]
Definition at line 648 of file docnode.h.
{ return p->name; }
References p.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), PrintDocVisitor::operator()(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
name() [2/2]
QCString DocDiagramFileBase::name () const [inline]
Definition at line 648 of file docnode.h.
{ return p->name; }
References p.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
relPath() [1/2]
QCString DocDiagramFileBase::relPath () const [inline]
Definition at line 650 of file docnode.h.
{ return p->relPath; }
References p.
Referenced by HtmlDocVisitor::operator()().
relPath() [2/2]
QCString DocDiagramFileBase::relPath () const [inline]
Definition at line 650 of file docnode.h.
{ return p->relPath; }
References p.
srcFile() [1/2]
QCString DocDiagramFileBase::srcFile () const [inline]
Definition at line 655 of file docnode.h.
{ return p->srcFile; }
References p.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), RTFDocVisitor::writeDiaFile(), RTFDocVisitor::writeDotFile(), and RTFDocVisitor::writeMscFile().
srcFile() [2/2]
QCString DocDiagramFileBase::srcFile () const [inline]
Definition at line 655 of file docnode.h.
{ return p->srcFile; }
References p.
srcLine() [1/2]
int DocDiagramFileBase::srcLine () const [inline]
Definition at line 656 of file docnode.h.
{ return p->srcLine; }
References p.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), RTFDocVisitor::writeDiaFile(), RTFDocVisitor::writeDotFile(), and RTFDocVisitor::writeMscFile().
srcLine() [2/2]
int DocDiagramFileBase::srcLine () const [inline]
Definition at line 656 of file docnode.h.
{ return p->srcLine; }
References p.
width() [1/2]
QCString DocDiagramFileBase::width () const [inline]
Definition at line 652 of file docnode.h.
{ return p->width; }
References p.
Referenced by doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docTableType::__init__(), doxmlparser.compound.docEntryType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docTableType::buildAttributes(), doxmlparser.compound.docEntryType::buildAttributes(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEntryType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.compound.docTableType::exportAttributes(), doxmlparser.compound.docTableType::get_width(), doxmlparser.compound.docEntryType::get_width(), doxmlparser.compound.docImageType::get_width(), doxmlparser.compound.docDotMscType::get_width(), doxmlparser.compound.docImageFileType::get_width(), doxmlparser.compound.docPlantumlType::get_width(), DocbookDocVisitor::operator()(), LatexDocVisitor::operator()(), XmlDocVisitor::operator()(), doxmlparser.compound.docTableType::set_width(), doxmlparser.compound.docEntryType::set_width(), doxmlparser.compound.docImageType::set_width(), doxmlparser.compound.docDotMscType::set_width(), doxmlparser.compound.docImageFileType::set_width(), and doxmlparser.compound.docPlantumlType::set_width().
width() [2/2]
QCString DocDiagramFileBase::width () const [inline]
Definition at line 652 of file docnode.h.
{ return p->width; }
References p.
Referenced by doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docTableType::__init__(), doxmlparser.compound.docEntryType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docTableType::buildAttributes(), doxmlparser.compound.docEntryType::buildAttributes(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEntryType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.compound.docTableType::exportAttributes(), doxmlparser.compound.docTableType::get_width(), doxmlparser.compound.docEntryType::get_width(), doxmlparser.compound.docImageType::get_width(), doxmlparser.compound.docDotMscType::get_width(), doxmlparser.compound.docImageFileType::get_width(), doxmlparser.compound.docPlantumlType::get_width(), doxmlparser.compound.docTableType::set_width(), doxmlparser.compound.docEntryType::set_width(), doxmlparser.compound.docImageType::set_width(), doxmlparser.compound.docDotMscType::set_width(), doxmlparser.compound.docImageFileType::set_width(), and doxmlparser.compound.docPlantumlType::set_width().
Member Data Documentation
p
std::unique_ptr< Private > DocDiagramFileBase::p [protected]
Definition at line 672 of file docnode.h.
Referenced by context(), DocDiaFile::DocDiaFile(), DocDotFile::DocDotFile(), DocMscFile::DocMscFile(), file(), height(), name(), DocDotFile::parse(), DocMscFile::parse(), DocDiaFile::parse(), relPath(), srcFile(), srcLine(), and width().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docnode.h
doxygen/src/docnode.h