FilterPrepend Class Reference
The implementation of the `prepend` filter.
Static Public Member Functions
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &arg)
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &arg)
Detailed Description
The implementation of the `prepend` filter.
Definition at line 944 of file template.cpp.
Member Function Documentation
apply() [1/2]
static TemplateVariant FilterPrepend::apply (const TemplateVariant & v, const TemplateVariant & arg) [inline], [static]
Definition at line 947 of file template.cpp.
    {
      if ((v.isString() || v.isInt()) &&
          arg.isString())
      {
        return TemplateVariant(arg.toString() + v.toString());
      }
      else
      {
        return v;
      }
    }
References TemplateVariant::isInt(), TemplateVariant::isString(), and TemplateVariant::toString().
apply() [2/2]
static TemplateVariant FilterPrepend::apply (const TemplateVariant & v, const TemplateVariant & arg) [inline], [static]
Definition at line 947 of file template.cpp.
    {
      if ((v.isString() || v.isInt()) &&
          arg.isString())
      {
        return TemplateVariant(arg.toString() + v.toString());
      }
      else
      {
        return v;
      }
    }
References TemplateVariant::isInt(), TemplateVariant::isString(), and TemplateVariant::toString().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp