DocStyleChange Class Reference
#include <docnode.h>
Public Types
enum Style {
Bold = (1<<0)
, Italic = (1<<1)
, Code = (1<<2)
, Center = (1<<3)
,
Small = (1<<4)
, Subscript = (1<<5)
, Superscript = (1<<6)
, Preformatted = (1<<7)
,
Span = (1<<8)
, Div = (1<<9)
, Strike = (1<<10)
, Underline = (1<<11)
,
Del = (1<<12)
, Ins = (1<<13)
, S = (1<<14)
, Cite = (1<<15)
,
Bold = (1<<0)
, Italic = (1<<1)
, Code = (1<<2)
, Center = (1<<3)
,
Small = (1<<4)
, Subscript = (1<<5)
, Superscript = (1<<6)
, Preformatted = (1<<7)
,
Span = (1<<8)
, Div = (1<<9)
, Strike = (1<<10)
, Underline = (1<<11)
,
Del = (1<<12)
, Ins = (1<<13)
, S = (1<<14)
, Cite = (1<<15)
 }
enum Style {
Bold = (1<<0)
, Italic = (1<<1)
, Code = (1<<2)
, Center = (1<<3)
,
Small = (1<<4)
, Subscript = (1<<5)
, Superscript = (1<<6)
, Preformatted = (1<<7)
,
Span = (1<<8)
, Div = (1<<9)
, Strike = (1<<10)
, Underline = (1<<11)
,
Del = (1<<12)
, Ins = (1<<13)
, S = (1<<14)
, Cite = (1<<15)
,
Bold = (1<<0)
, Italic = (1<<1)
, Code = (1<<2)
, Center = (1<<3)
,
Small = (1<<4)
, Subscript = (1<<5)
, Superscript = (1<<6)
, Preformatted = (1<<7)
,
Span = (1<<8)
, Div = (1<<9)
, Strike = (1<<10)
, Underline = (1<<11)
,
Del = (1<<12)
, Ins = (1<<13)
, S = (1<<14)
, Cite = (1<<15)
 }
Public Member Functions
DocStyleChange (DocParser *parser, DocNodeVariant *parent, size_t position, Style s, const QCString &tagName, bool enable, const HtmlAttribList *attribs=0)
Style style () const
const char * styleString () const
bool enable () const
size_t position () const
const HtmlAttribList & attribs () const
QCString tagName () const
DocStyleChange (DocParser *parser, DocNodeVariant *parent, size_t position, Style s, const QCString &tagName, bool enable, const HtmlAttribList *attribs=0)
Style style () const
const char * styleString () const
bool enable () const
size_t position () const
const HtmlAttribList & attribs () const
QCString tagName () const
Private Attributes
size_t m_position = 0
Style m_style = Bold
bool m_enable = false
HtmlAttribList m_attribs
QCString m_tagName
Additional Inherited Members
Detailed Description
Node representing a style change
Definition at line 257 of file docnode.h.
Member Enumeration Documentation
Style [1/2]
enum DocStyleChange::Style
Enumerator
Bold
Italic
Code
Center
Small
Subscript
Superscript
Preformatted
Span
Div
Strike
Underline
Del
Ins
S
Cite
Bold
Italic
Code
Center
Small
Subscript
Superscript
Preformatted
Span
Div
Strike
Underline
Del
Ins
S
Cite
Definition at line 260 of file docnode.h.
               { Bold = (1<<0),
                 Italic = (1<<1),
                 Code = (1<<2),
                 Center = (1<<3),
                 Small = (1<<4),
                 Subscript = (1<<5),
                 Superscript = (1<<6),
                 Preformatted = (1<<7),
                 Span = (1<<8),
                 Div = (1<<9),
                 Strike = (1<<10),
                 Underline = (1<<11),
                 Del = (1<<12),
                 Ins = (1<<13),
                 S = (1<<14),
                 Cite = (1<<15)
               };
Style [2/2]
enum DocStyleChange::Style
Enumerator
Bold
Italic
Code
Center
Small
Subscript
Superscript
Preformatted
Span
Div
Strike
Underline
Del
Ins
S
Cite
Bold
Italic
Code
Center
Small
Subscript
Superscript
Preformatted
Span
Div
Strike
Underline
Del
Ins
S
Cite
Definition at line 260 of file docnode.h.
               { Bold = (1<<0),
                 Italic = (1<<1),
                 Code = (1<<2),
                 Center = (1<<3),
                 Small = (1<<4),
                 Subscript = (1<<5),
                 Superscript = (1<<6),
                 Preformatted = (1<<7),
                 Span = (1<<8),
                 Div = (1<<9),
                 Strike = (1<<10),
                 Underline = (1<<11),
                 Del = (1<<12),
                 Ins = (1<<13),
                 S = (1<<14),
                 Cite = (1<<15)
               };
Constructor & Destructor Documentation
DocStyleChange() [1/2]
DocStyleChange::DocStyleChange (DocParser * parser, DocNodeVariant * parent, size_t position, Style s, const QCString & tagName, bool enable, const HtmlAttribList * attribs = 0) [inline]
Definition at line 278 of file docnode.h.
      : DocNode(parser,parent), m_position(position), m_style(s), m_enable(enable)
    {
      if (attribs) m_attribs=*attribs;
      m_tagName = tagName.lower();
    }
References attribs(), QCString::lower(), m_attribs, m_tagName, and tagName().
DocStyleChange() [2/2]
DocStyleChange::DocStyleChange (DocParser * parser, DocNodeVariant * parent, size_t position, Style s, const QCString & tagName, bool enable, const HtmlAttribList * attribs = 0) [inline]
Definition at line 278 of file docnode.h.
      : DocNode(parser,parent), m_position(position), m_style(s), m_enable(enable)
    {
      if (attribs) m_attribs=*attribs;
      m_tagName = tagName.lower();
    }
References attribs(), QCString::lower(), m_attribs, m_tagName, and tagName().
Member Function Documentation
attribs() [1/2]
const HtmlAttribList & DocStyleChange::attribs () const [inline]
Definition at line 289 of file docnode.h.
{ return m_attribs; }
References m_attribs.
Referenced by DocStyleChange(), and DocParser::handleInitialStyleCommands().
attribs() [2/2]
const HtmlAttribList & DocStyleChange::attribs () const [inline]
Definition at line 289 of file docnode.h.
{ return m_attribs; }
References m_attribs.
enable() [1/2]
bool DocStyleChange::enable () const [inline]
Definition at line 287 of file docnode.h.
{ return m_enable; }
References m_enable.
Referenced by insideStyleChangeThatIsOutsideParagraph().
enable() [2/2]
bool DocStyleChange::enable () const [inline]
Definition at line 287 of file docnode.h.
{ return m_enable; }
References m_enable.
position() [1/2]
size_t DocStyleChange::position () const [inline]
Definition at line 288 of file docnode.h.
{ return m_position; }
References m_position.
Referenced by DocParser::handlePendingStyleCommands().
position() [2/2]
size_t DocStyleChange::position () const [inline]
Definition at line 288 of file docnode.h.
{ return m_position; }
References m_position.
style() [1/2]
Style DocStyleChange::style () const [inline]
Definition at line 285 of file docnode.h.
{ return m_style; }
References m_style.
Referenced by DocParser::handleInitialStyleCommands(), DocParser::handlePendingStyleCommands(), insideStyleChangeThatIsOutsideParagraph(), and mustBeOutsideParagraph().
style() [2/2]
Style DocStyleChange::style () const [inline]
Definition at line 285 of file docnode.h.
{ return m_style; }
References m_style.
styleString() [1/2]
const char * DocStyleChange::styleString () const
Definition at line 120 of file docnode.cpp.
{
  switch (m_style)
  {
    case DocStyleChange::Bold: return "b";
    case DocStyleChange::Italic: return "em";
    case DocStyleChange::Code: return "code";
    case DocStyleChange::Center: return "center";
    case DocStyleChange::Small: return "small";
    case DocStyleChange::Cite: return "cite";
    case DocStyleChange::Subscript: return "subscript";
    case DocStyleChange::Superscript: return "superscript";
    case DocStyleChange::Preformatted: return "pre";
    case DocStyleChange::Div: return "div";
    case DocStyleChange::Span: return "span";
    case DocStyleChange::Strike: return "strike";
    case DocStyleChange::S: return "s";
    case DocStyleChange::Del: return "del";
    case DocStyleChange::Underline: return "u";
    case DocStyleChange::Ins: return "ins";
  }
  return "<invalid>";
}
References Bold, Center, Cite, Code, Del, Div, Ins, Italic, m_style, Preformatted, S, Small, Span, Strike, Subscript, Superscript, and Underline.
styleString() [2/2]
const char * DocStyleChange::styleString () const
tagName() [1/2]
QCString DocStyleChange::tagName () const [inline]
Definition at line 290 of file docnode.h.
{ return m_tagName; }
References m_tagName.
Referenced by DocStyleChange(), DocParser::handleInitialStyleCommands(), and DocParser::handlePendingStyleCommands().
tagName() [2/2]
QCString DocStyleChange::tagName () const [inline]
Definition at line 290 of file docnode.h.
{ return m_tagName; }
References m_tagName.
Member Data Documentation
m_attribs
HtmlAttribList DocStyleChange::m_attribs [private]
Definition at line 296 of file docnode.h.
Referenced by attribs(), and DocStyleChange().
m_enable
bool DocStyleChange::m_enable = false [private]
Definition at line 295 of file docnode.h.
Referenced by enable().
m_position
size_t DocStyleChange::m_position = 0 [private]
Definition at line 293 of file docnode.h.
Referenced by position().
m_style
Style DocStyleChange::m_style = Bold [private]
Definition at line 294 of file docnode.h.
Referenced by style(), and styleString().
m_tagName
QCString DocStyleChange::m_tagName [private]
Definition at line 297 of file docnode.h.
Referenced by DocStyleChange(), and tagName().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docnode.h
doxygen/src/docnode.h
doxygen/build/doxygen/src/docnode.cpp
doxygen/src/docnode.cpp