DocHtmlListItem Class Reference
#include <docnode.h>
Public Member Functions
DocHtmlListItem (DocParser *parser, DocNodeVariant *parent, const HtmlAttribList &attribs, int num)
int itemNumber () const
const HtmlAttribList & attribs () const
int parse (DocNodeVariant *)
int parseXml (DocNodeVariant *)
DocHtmlListItem (DocParser *parser, DocNodeVariant *parent, const HtmlAttribList &attribs, int num)
int itemNumber () const
const HtmlAttribList & attribs () const
int parse (DocNodeVariant *)
int parseXml (DocNodeVariant *)
Private Attributes
HtmlAttribList m_attribs
int m_itemNum = 0
Additional Inherited Members
Detailed Description
Node representing a HTML list item
Definition at line 1117 of file docnode.h.
Constructor & Destructor Documentation
DocHtmlListItem() [1/2]
DocHtmlListItem::DocHtmlListItem (DocParser * parser, DocNodeVariant * parent, const HtmlAttribList & attribs, int num) [inline]
Definition at line 1120 of file docnode.h.
    : DocCompoundNode(parser,parent), m_attribs(attribs), m_itemNum(num) {}
DocHtmlListItem() [2/2]
DocHtmlListItem::DocHtmlListItem (DocParser * parser, DocNodeVariant * parent, const HtmlAttribList & attribs, int num) [inline]
Definition at line 1120 of file docnode.h.
    : DocCompoundNode(parser,parent), m_attribs(attribs), m_itemNum(num) {}
Member Function Documentation
attribs() [1/2]
const HtmlAttribList & DocHtmlListItem::attribs () const [inline]
Definition at line 1123 of file docnode.h.
{ return m_attribs; }
References m_attribs.
Referenced by HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), PerlModDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), and PrintDocVisitor::operator()().
attribs() [2/2]
const HtmlAttribList & DocHtmlListItem::attribs () const [inline]
Definition at line 1123 of file docnode.h.
{ return m_attribs; }
References m_attribs.
itemNumber() [1/2]
int DocHtmlListItem::itemNumber () const [inline]
Definition at line 1122 of file docnode.h.
{ return m_itemNum; }
References m_itemNum.
itemNumber() [2/2]
int DocHtmlListItem::itemNumber () const [inline]
Definition at line 1122 of file docnode.h.
{ return m_itemNum; }
References m_itemNum.
parse() [1/2]
int DocHtmlListItem::parse (DocNodeVariant * thisVariant)
Definition at line 2369 of file docnode.cpp.
{
  DBG(("DocHtmlListItem::parse() start\n"));
  int retval=0;
  auto ns = AutoNodeStack(parser(),thisVariant);
  // parse one or more paragraphs
  bool isFirst=TRUE;
  DocPara *par=0;
  do
  {
    auto vDocPara = children().append<DocPara>(parser(),thisVariant);
    par = children().get_last<DocPara>();
    if (isFirst) { par->markFirst(); isFirst=FALSE; }
    retval=par->parse(vDocPara);
  }
  while (retval==TK_NEWPARA);
  if (par) par->markLast();
  DBG(("DocHtmlListItem::parse() end retval=%s\n",DocTokenizer::retvalToString(retval)));
  return retval;
}
References DocNodeList::append(), DocCompoundNode::children(), DBG, FALSE, DocNodeList::get_last(), DocPara::markFirst(), DocPara::markLast(), DocPara::parse(), DocNode::parser(), DocTokenizer::retvalToString(), TK_NEWPARA, and TRUE.
Referenced by DocHtmlList::parse().
parse() [2/2]
int DocHtmlListItem::parse (DocNodeVariant *)
parseXml() [1/2]
int DocHtmlListItem::parseXml (DocNodeVariant * thisVariant)
Definition at line 2392 of file docnode.cpp.
{
  DBG(("DocHtmlListItem::parseXml() start\n"));
  int retval=0;
  auto ns = AutoNodeStack(parser(),thisVariant);
  // parse one or more paragraphs
  bool isFirst=TRUE;
  DocPara *par=0;
  do
  {
    auto vDocPara = children().append<DocPara>(parser(),thisVariant);
    par = children().get_last<DocPara>();
    if (isFirst) { par->markFirst(); isFirst=FALSE; }
    retval=par->parse(vDocPara);
    if (retval==0) break;
    //printf("new item: retval=%x parser()->context.token->name=%s parser()->context.token->endTag=%d\n",
    // retval,qPrint(parser()->context.token->name),parser()->context.token->endTag);
    if (retval==RetVal_ListItem)
    {
      break;
    }
  }
  while (retval!=RetVal_CloseXml);
  if (par) par->markLast();
  DBG(("DocHtmlListItem::parseXml() end retval=%s\n",DocTokenizer::retvalToString(retval)));
  return retval;
}
References DocNodeList::append(), DocCompoundNode::children(), DBG, FALSE, DocNodeList::get_last(), DocPara::markFirst(), DocPara::markLast(), DocPara::parse(), DocNode::parser(), RetVal_CloseXml, RetVal_ListItem, DocTokenizer::retvalToString(), and TRUE.
Referenced by DocHtmlList::parseXml().
parseXml() [2/2]
int DocHtmlListItem::parseXml (DocNodeVariant *)
Member Data Documentation
m_attribs
HtmlAttribList DocHtmlListItem::m_attribs [private]
Definition at line 1128 of file docnode.h.
Referenced by attribs().
m_itemNum
int DocHtmlListItem::m_itemNum = 0 [private]
Definition at line 1129 of file docnode.h.
Referenced by itemNumber().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docnode.h
doxygen/src/docnode.h
doxygen/build/doxygen/src/docnode.cpp
doxygen/src/docnode.cpp