Definition Class Reference
#include <definition.h>
Public Types
enum DefType {
TypeClass = 0
, TypeFile = 1
, TypeNamespace = 2
, TypeMember = 3
,
TypeGroup = 4
, TypePackage = 5
, TypePage = 6
, TypeDir = 7
,
TypeConcept = 8
, TypeClass = 0
, TypeFile = 1
, TypeNamespace = 2
,
TypeMember = 3
, TypeGroup = 4
, TypePackage = 5
, TypePage = 6
,
TypeDir = 7
, TypeConcept = 8
 }
enum DefType {
TypeClass = 0
, TypeFile = 1
, TypeNamespace = 2
, TypeMember = 3
,
TypeGroup = 4
, TypePackage = 5
, TypePage = 6
, TypeDir = 7
,
TypeConcept = 8
, TypeClass = 0
, TypeFile = 1
, TypeNamespace = 2
,
TypeMember = 3
, TypeGroup = 4
, TypePackage = 5
, TypePage = 6
,
TypeDir = 7
, TypeConcept = 8
 }
Public Member Functions
virtual DefType definitionType () const =0
virtual CodeSymbolType codeSymbolType () const =0
virtual bool isAlias () const =0
virtual QCString name () const =0
virtual bool isAnonymous () const =0
virtual QCString displayName (bool includeScope=TRUE) const =0
virtual QCString localName () const =0
virtual QCString qualifiedName () const =0
virtual QCString symbolName () const =0
virtual QCString getOutputFileBase () const =0
virtual QCString anchor () const =0
virtual QCString getSourceFileBase () const =0
virtual QCString getSourceAnchor () const =0
virtual QCString documentation () const =0
virtual int docLine () const =0
virtual QCString docFile () const =0
virtual QCString briefDescription (bool abbreviate=FALSE) const =0
virtual QCString briefDescriptionAsTooltip () const =0
virtual int briefLine () const =0
virtual QCString inbodyDocumentation () const =0
virtual QCString inbodyFile () const =0
virtual int inbodyLine () const =0
virtual QCString briefFile () const =0
virtual QCString getDefFileName () const =0
virtual QCString getDefFileExtension () const =0
virtual int getDefLine () const =0
virtual int getDefColumn () const =0
virtual bool hasDocumentation () const =0
virtual bool hasUserDocumentation () const =0
virtual bool isLinkableInProject () const =0
virtual bool isLinkable () const =0
virtual bool isVisibleInProject () const =0
virtual bool isVisible () const =0
virtual bool isHidden () const =0
virtual bool isArtificial () const =0
virtual QCString getReference () const =0
virtual bool isReference () const =0
virtual QCString externalReference (const QCString &relPath) const =0
virtual int getStartDefLine () const =0
virtual int getStartBodyLine () const =0
virtual int getEndBodyLine () const =0
virtual const FileDef * getBodyDef () const =0
virtual SrcLangExt getLanguage () const =0
virtual const GroupList & partOfGroups () const =0
virtual bool isLinkableViaGroup () const =0
virtual const RefItemVector & xrefListItems () const =0
virtual const Definition * findInnerCompound (const QCString &name) const =0
virtual Definition * getOuterScope () const =0
virtual const MemberVector & getReferencesMembers () const =0
virtual const MemberVector & getReferencedByMembers () const =0
virtual bool hasSections () const =0
virtual bool hasSources () const =0
virtual bool hasBriefDescription () const =0
virtual QCString id () const =0
virtual const SectionRefs & getSectionRefs () const =0
virtual QCString navigationPathAsString () const =0
virtual QCString pathFragment () const =0
virtual void _setSymbolName (const QCString &name)=0
virtual QCString _symbolName () const =0
virtual ~Definition ()=default
virtual DefType definitionType () const =0
virtual CodeSymbolType codeSymbolType () const =0
virtual bool isAlias () const =0
virtual QCString name () const =0
virtual bool isAnonymous () const =0
virtual QCString displayName (bool includeScope=TRUE) const =0
virtual QCString localName () const =0
virtual QCString qualifiedName () const =0
virtual QCString symbolName () const =0
virtual QCString getOutputFileBase () const =0
virtual QCString anchor () const =0
virtual QCString getSourceFileBase () const =0
virtual QCString getSourceAnchor () const =0
virtual QCString documentation () const =0
virtual int docLine () const =0
virtual QCString docFile () const =0
virtual QCString briefDescription (bool abbreviate=FALSE) const =0
virtual QCString briefDescriptionAsTooltip () const =0
virtual int briefLine () const =0
virtual QCString inbodyDocumentation () const =0
virtual QCString inbodyFile () const =0
virtual int inbodyLine () const =0
virtual QCString briefFile () const =0
virtual QCString getDefFileName () const =0
virtual QCString getDefFileExtension () const =0
virtual int getDefLine () const =0
virtual int getDefColumn () const =0
virtual bool hasDocumentation () const =0
virtual bool hasUserDocumentation () const =0
virtual bool isLinkableInProject () const =0
virtual bool isLinkable () const =0
virtual bool isVisibleInProject () const =0
virtual bool isVisible () const =0
virtual bool isHidden () const =0
virtual bool isArtificial () const =0
virtual QCString getReference () const =0
virtual bool isReference () const =0
virtual QCString externalReference (const QCString &relPath) const =0
virtual int getStartDefLine () const =0
virtual int getStartBodyLine () const =0
virtual int getEndBodyLine () const =0
virtual const FileDef * getBodyDef () const =0
virtual SrcLangExt getLanguage () const =0
virtual const GroupList & partOfGroups () const =0
virtual bool isLinkableViaGroup () const =0
virtual const RefItemVector & xrefListItems () const =0
virtual const Definition * findInnerCompound (const QCString &name) const =0
virtual Definition * getOuterScope () const =0
virtual const MemberVector & getReferencesMembers () const =0
virtual const MemberVector & getReferencedByMembers () const =0
virtual bool hasSections () const =0
virtual bool hasSources () const =0
virtual bool hasBriefDescription () const =0
virtual QCString id () const =0
virtual const SectionRefs & getSectionRefs () const =0
virtual QCString navigationPathAsString () const =0
virtual QCString pathFragment () const =0
virtual void _setSymbolName (const QCString &name)=0
virtual QCString _symbolName () const =0
virtual ~Definition ()=default
Private Member Functions
virtual DefinitionMutable * toDefinitionMutable_ ()=0
virtual const DefinitionImpl * toDefinitionImpl_ () const =0
virtual DefinitionMutable * toDefinitionMutable_ ()=0
virtual const DefinitionImpl * toDefinitionImpl_ () const =0
Friends
class DefinitionImpl
DefinitionMutable * toDefinitionMutable (Definition *)
DefinitionMutable * toDefinitionMutable (const Definition *)
DefinitionMutable * toDefinitionMutable (Definition *)
DefinitionMutable * toDefinitionMutable (const Definition *)
Detailed Description
The common base class of all entity definitions found in the sources.
This can be a class or a member function, or a file, or a namespace, etc. Use definitionType() to find which type of definition this is.
Definition at line 76 of file definition.h.
Member Enumeration Documentation
DefType [1/2]
enum Definition::DefType
Types of derived classes
Enumerator
TypeClass
TypeFile
TypeNamespace
TypeMember
TypeGroup
TypePackage
TypePage
TypeDir
TypeConcept
TypeClass
TypeFile
TypeNamespace
TypeMember
TypeGroup
TypePackage
TypePage
TypeDir
TypeConcept
Definition at line 80 of file definition.h.
    {
      TypeClass = 0,
      TypeFile = 1,
      TypeNamespace = 2,
      TypeMember = 3,
      TypeGroup = 4,
      TypePackage = 5,
      TypePage = 6,
      TypeDir = 7,
      TypeConcept = 8
    };
DefType [2/2]
enum Definition::DefType
Types of derived classes
Enumerator
TypeClass
TypeFile
TypeNamespace
TypeMember
TypeGroup
TypePackage
TypePage
TypeDir
TypeConcept
TypeClass
TypeFile
TypeNamespace
TypeMember
TypeGroup
TypePackage
TypePage
TypeDir
TypeConcept
Definition at line 80 of file definition.h.
    {
      TypeClass = 0,
      TypeFile = 1,
      TypeNamespace = 2,
      TypeMember = 3,
      TypeGroup = 4,
      TypePackage = 5,
      TypePage = 6,
      TypeDir = 7,
      TypeConcept = 8
    };
Constructor & Destructor Documentation
 Definition() [1/2]
virtual Definition::~Definition () [virtual], [default]
 Definition() [2/2]
virtual Definition::~Definition () [virtual], [default]
Member Function Documentation
_setSymbolName() [1/2]
virtual void Definition::_setSymbolName (const QCString & name) [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by addToMap().
_setSymbolName() [2/2]
virtual void Definition::_setSymbolName (const QCString & name) [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
_symbolName() [1/2]
virtual QCString Definition::_symbolName () const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
_symbolName() [2/2]
virtual QCString Definition::_symbolName () const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
anchor() [1/2]
virtual QCString Definition::anchor () const [pure virtual]
Returns the anchor within a page where this item can be found
Implemented in ClassDefImpl, ClassDefAliasImpl, ConceptDefImpl, ConceptDefAliasImpl, DirDefImpl, FileDefImpl, GroupDefImpl, MemberDefImpl, MemberDefAliasImpl, NamespaceDefImpl, NamespaceDefAliasImpl, PageDefImpl, ClassDefImpl, ClassDefAliasImpl, ConceptDefImpl, ConceptDefAliasImpl, DirDefImpl, FileDefImpl, GroupDefImpl, MemberDefImpl, MemberDefAliasImpl, NamespaceDefImpl, NamespaceDefAliasImpl, PageDefImpl, ClassDef, ConceptDef, DirDef, FileDef, GroupDef, MemberDef, NamespaceDef, PageDef, ClassDef, ConceptDef, DirDef, FileDef, GroupDef, MemberDef, NamespaceDef, and PageDef.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), TooltipManager::addTooltip(), DefinitionContext< T >::anchor(), NestingNodeContext::Private::anchor(), NavPathElemContext::Private::anchor(), SymbolContext::Private::anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), DocParser::handleLinkedWord(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), DefinitionImpl::navigationPathAsString(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), doxmlparser.compound.docTocItemType::set_anchor(), validatingParseDoc(), writeJavaScriptSearchIndex(), writeMultiLineCodeLink(), and TooltipManager::writeTooltips().
anchor() [2/2]
virtual QCString Definition::anchor () const [pure virtual]
Returns the anchor within a page where this item can be found
Implemented in ClassDefImpl, ClassDefAliasImpl, ConceptDefImpl, ConceptDefAliasImpl, DirDefImpl, FileDefImpl, GroupDefImpl, MemberDefImpl, MemberDefAliasImpl, NamespaceDefImpl, NamespaceDefAliasImpl, PageDefImpl, ClassDefImpl, ClassDefAliasImpl, ConceptDefImpl, ConceptDefAliasImpl, DirDefImpl, FileDefImpl, GroupDefImpl, MemberDefImpl, MemberDefAliasImpl, NamespaceDefImpl, NamespaceDefAliasImpl, PageDefImpl, ClassDef, ConceptDef, DirDef, FileDef, GroupDef, MemberDef, NamespaceDef, PageDef, ClassDef, ConceptDef, DirDef, FileDef, GroupDef, MemberDef, NamespaceDef, and PageDef.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
briefDescription() [1/2]
virtual QCString Definition::briefDescription (bool abbreviate = FALSE) const [pure virtual]
Returns the brief description of this definition. This can include commands.
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, MemberDefAliasImpl, MemberDef, MemberDef, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by MemberDefImpl::_writeEnumValues(), DefinitionAliasMixin< Base >::briefDescription(), DefinitionContext< T >::createBrief(), NestingNodeContext::Private::createBrief(), createTagLessInstance(), DocParser::findDocsForMemberOrCompound(), generateBriefDoc(), generateDEFForClass(), generateDEFForFile(), generateDEFForNamespace(), PerlModGenerator::generatePerlModForClass(), PerlModGenerator::generatePerlModForConcept(), PerlModGenerator::generatePerlModForFile(), PerlModGenerator::generatePerlModForGroup(), PerlModGenerator::generatePerlModForNamespace(), generateXMLForClass(), generateXMLForConcept(), generateXMLForDir(), generateXMLForFile(), generateXMLForGroup(), generateXMLForNamespace(), generateXMLForPage(), MemberList::writePlainDeclarations(), writeSingleFileIndex(), and writeVhdlEntityToolTip().
briefDescription() [2/2]
virtual QCString Definition::briefDescription (bool abbreviate = FALSE) const [pure virtual]
Returns the brief description of this definition. This can include commands.
Implemented in MemberDefImpl, MemberDefAliasImpl, MemberDefImpl, MemberDefAliasImpl, MemberDef, MemberDef, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
briefDescriptionAsTooltip() [1/2]
virtual QCString Definition::briefDescriptionAsTooltip () const [pure virtual]
Returns a plain text version of the brief description suitable for use as a tool tip.
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by DotClassGraph::addClass(), DotGfxHierarchyTable::addHierarchy(), DefinitionAliasMixin< Base >::briefDescriptionAsTooltip(), DotInclDepGraph::buildGraph(), common_attributes(), DotCallGraph::DotCallGraph(), DotClassGraph::DotClassGraph(), DotGroupCollaboration::DotGroupCollaboration(), DotInclDepGraph::DotInclDepGraph(), DocParser::handleLinkedWord(), writeColumn(), writeMapArea(), writeMultiLineCodeLink(), DocSets::writeToken(), and TooltipManager::writeTooltips().
briefDescriptionAsTooltip() [2/2]
virtual QCString Definition::briefDescriptionAsTooltip () const [pure virtual]
Returns a plain text version of the brief description suitable for use as a tool tip.
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
briefFile() [1/2]
virtual QCString Definition::briefFile () const [pure virtual]
Returns the file in which the brief description was found. This can differ from getDefFileName().
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by ClassDefImpl::addMembersToTemplateInstance(), DefinitionAliasMixin< Base >::briefFile(), combineDeclarationAndDefinition(), DefinitionContext< T >::createBrief(), NestingNodeContext::Private::createBrief(), createTagLessInstance(), MemberGroup::distributeMemberGroupDocumentation(), findUsingDeclImports(), generateBriefDoc(), generateXMLForClass(), generateXMLForConcept(), generateXMLForDir(), generateXMLForFile(), generateXMLForGroup(), generateXMLForMember(), generateXMLForNamespace(), generateXMLForPage(), inheritDocumentation(), DocParser::processCopyDoc(), writeSingleFileIndex(), and VhdlDocGen::writeVHDLDeclaration().
briefFile() [2/2]
virtual QCString Definition::briefFile () const [pure virtual]
Returns the file in which the brief description was found. This can differ from getDefFileName().
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
briefLine() [1/2]
virtual int Definition::briefLine () const [pure virtual]
Returns the line number at which the brief description was found.
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by ClassDefImpl::addMembersToTemplateInstance(), DefinitionAliasMixin< Base >::briefLine(), combineDeclarationAndDefinition(), DefinitionContext< T >::createBrief(), NestingNodeContext::Private::createBrief(), createTagLessInstance(), MemberGroup::distributeMemberGroupDocumentation(), findUsingDeclImports(), formatBriefNote(), generateBriefDoc(), generateXMLForClass(), generateXMLForConcept(), generateXMLForDir(), generateXMLForFile(), generateXMLForGroup(), generateXMLForMember(), generateXMLForNamespace(), generateXMLForPage(), inheritDocumentation(), DocParser::processCopyDoc(), writeSingleFileIndex(), and VhdlDocGen::writeVHDLDeclaration().
briefLine() [2/2]
virtual int Definition::briefLine () const [pure virtual]
Returns the line number at which the brief description was found.
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
codeSymbolType() [1/2]
virtual CodeSymbolType Definition::codeSymbolType () const [pure virtual]
Used for syntax highlighting symbol class
Implemented in ClassDefImpl, ClassDefAliasImpl, ConceptDefImpl, ConceptDefAliasImpl, DirDefImpl, FileDefImpl, GroupDefImpl, MemberDefImpl, MemberDefAliasImpl, NamespaceDefImpl, NamespaceDefAliasImpl, PageDefImpl, ClassDefImpl, ClassDefAliasImpl, ConceptDefImpl, ConceptDefAliasImpl, DirDefImpl, FileDefImpl, GroupDefImpl, MemberDefImpl, MemberDefAliasImpl, NamespaceDefImpl, NamespaceDefAliasImpl, and PageDefImpl.
Referenced by ClassDefAliasImpl::codeSymbolType(), ConceptDefAliasImpl::codeSymbolType(), MemberDefAliasImpl::codeSymbolType(), NamespaceDefAliasImpl::codeSymbolType(), and writeMultiLineCodeLink().
codeSymbolType() [2/2]
virtual CodeSymbolType Definition::codeSymbolType () const [pure virtual]
Used for syntax highlighting symbol class
Implemented in ClassDefImpl, ClassDefAliasImpl, ConceptDefImpl, ConceptDefAliasImpl, DirDefImpl, FileDefImpl, GroupDefImpl, MemberDefImpl, MemberDefAliasImpl, NamespaceDefImpl, NamespaceDefAliasImpl, PageDefImpl, ClassDefImpl, ClassDefAliasImpl, ConceptDefImpl, ConceptDefAliasImpl, DirDefImpl, FileDefImpl, GroupDefImpl, MemberDefImpl, MemberDefAliasImpl, NamespaceDefImpl, NamespaceDefAliasImpl, and PageDefImpl.
definitionType() [1/2]
virtual DefType Definition::definitionType () const [pure virtual]
Use this for dynamic inspection of the type of the derived class
Implemented in ClassDefImpl, ClassDefAliasImpl, ConceptDefImpl, ConceptDefAliasImpl, DirDefImpl, FileDefImpl, GroupDefImpl, MemberDefImpl, MemberDefAliasImpl, NamespaceDefImpl, NamespaceDefAliasImpl, PageDefImpl, ClassDefImpl, ClassDefAliasImpl, ConceptDefImpl, ConceptDefAliasImpl, DirDefImpl, FileDefImpl, GroupDefImpl, MemberDefImpl, MemberDefAliasImpl, NamespaceDefImpl, NamespaceDefAliasImpl, PageDefImpl, ClassDef, ConceptDef, DirDef, FileDef, GroupDef, MemberDef, NamespaceDef, PageDef, ClassDef, ConceptDef, DirDef, FileDef, GroupDef, MemberDef, NamespaceDef, and PageDef.
Referenced by addConceptToContext(), DocSets::addIndexItem(), ClassDefImpl::addInnerCompound(), NamespaceDefImpl::addInnerCompound(), PageDefImpl::addInnerCompound(), MemberDefImpl::addListReference(), MemberList::addListReferences(), NestingNodeContext::Private::addMembers(), NestingContext::Private::addPage(), ClassContext::Private::addTemplateDecls(), buildNamespaceList(), DefinitionContext< T >::compoundKind(), DefinitionImpl::computeTooltip(), NestingNodeContext::Private::createClass(), NestingNodeContext::Private::createDir(), NestingNodeContext::Private::createFile(), MemberListInfoContext::Private::createInherited(), NestingNodeContext::Private::createMember(), NestingNodeContext::Private::createModule(), NestingNodeContext::Private::createNamespace(), DefinitionContext< T >::createNavigationPath(), NestingNodeContext::Private::createPage(), SymbolContext::Private::createScope(), DefinitionContext< T >::DefinitionContext(), definitionToName(), DocLink::DocLink(), DocRef::DocRef(), dumpSymbol(), DefinitionContext< T >::fillPath(), findGlobalMember(), findMemberLink(), findTagLessClasses(), SymbolResolver::Private::followPath(), generateClassDocs(), generateClassMemberLink(), generateClassOrGlobalLink(), generateLink(), generateXMLForMember(), getDefsNew(), MemberDefImpl::getLabels(), getMemberFromSymbol(), SymbolResolver::Private::getResolvedSymbol(), SymbolResolver::Private::getResolvedType(), DefinitionImpl::getSourceFileBase(), ClassDefImpl::getTemplateParameterLists(), DocParser::handleLinkedWord(), PageDefImpl::hasParentPage(), if(), GroupDefImpl::insertMember(), NamespaceDefImpl::insertMember(), SymbolResolver::Private::isAccessibleFrom(), SymbolResolver::Private::isAccessibleFromWithExpScope(), XRefDummyCodeGenerator::linkableSymbol(), lookupSymbol(), makeQualifiedNameWithTemplateParameters(), memberVisible(), MemberDefImpl::moveTo(), NestingNodeContext::Private::name(), DefinitionImpl::navigationPathAsString(), NestingNodeContext::Private::partOfGroup(), DefinitionImpl::pathFragment(), SymbolResolver::resolveClass(), resolveClassNestingRelations(), resolveTypeDef(), scopeIsTemplate(), searchName(), searchTemplateSpecs(), SearchIndex::setCurrentDoc(), SearchIndexExternal::setCurrentDoc(), NavPathElemContext::Private::text(), updateCallContextForSmartPointer(), validatingParseDoc(), writeClassTree(), writeDefArgumentList(), DefinitionImpl::writeDocAnchorsToTagFile(), MemberDefImpl::writeDocumentation(), DefinitionImpl::writeInlineCode(), writeJavaScriptSearchIndex(), MemberDefImpl::writeMemberDocSimple(), and TooltipManager::writeTooltips().
definitionType() [2/2]
virtual DefType Definition::definitionType () const [pure virtual]
Use this for dynamic inspection of the type of the derived class
Implemented in ClassDefImpl, ClassDefAliasImpl, ConceptDefImpl, ConceptDefAliasImpl, DirDefImpl, FileDefImpl, GroupDefImpl, MemberDefImpl, MemberDefAliasImpl, NamespaceDefImpl, NamespaceDefAliasImpl, PageDefImpl, ClassDefImpl, ClassDefAliasImpl, ConceptDefImpl, ConceptDefAliasImpl, DirDefImpl, FileDefImpl, GroupDefImpl, MemberDefImpl, MemberDefAliasImpl, NamespaceDefImpl, NamespaceDefAliasImpl, PageDefImpl, ClassDef, ConceptDef, DirDef, FileDef, GroupDef, MemberDef, NamespaceDef, PageDef, ClassDef, ConceptDef, DirDef, FileDef, GroupDef, MemberDef, NamespaceDef, and PageDef.
displayName() [1/2]
virtual QCString Definition::displayName (bool includeScope = TRUE) const [pure virtual]
Returns the name of the definition as it appears in the output
Implemented in MemberDefAliasImpl, NamespaceDefAliasImpl, MemberDefAliasImpl, NamespaceDefAliasImpl, ClassDefImpl, ClassDefAliasImpl, ConceptDefImpl, ConceptDefAliasImpl, ClassDefImpl, ClassDefAliasImpl, ConceptDefImpl, ConceptDefAliasImpl, ClassDef, ConceptDef, ClassDef, ConceptDef, DirDefImpl, FileDefImpl, GroupDefImpl, MemberDefImpl, NamespaceDefImpl, PageDefImpl, DirDefImpl, FileDefImpl, GroupDefImpl, MemberDefImpl, NamespaceDefImpl, PageDefImpl, DirDef, FileDef, GroupDef, MemberDef, NamespaceDef, PageDef, DirDef, FileDef, GroupDef, MemberDef, NamespaceDef, and PageDef.
Referenced by DefinitionContext< T >::bareName(), DefinitionImpl::briefDescription(), SymbolContext::Private::createScope(), DefinitionContext< T >::DefinitionContext(), generateClassOrGlobalLink(), DefinitionContext< T >::name(), NestingNodeContext::Private::name(), MemberDefImpl::writeDeclaration(), and MemberDefImpl::writeDocumentation().
displayName() [2/2]
virtual QCString Definition::displayName (bool includeScope = TRUE) const [pure virtual]
Returns the name of the definition as it appears in the output
Implemented in MemberDefAliasImpl, NamespaceDefAliasImpl, MemberDefAliasImpl, NamespaceDefAliasImpl, ClassDefImpl, ClassDefAliasImpl, ConceptDefImpl, ConceptDefAliasImpl, ClassDefImpl, ClassDefAliasImpl, ConceptDefImpl, ConceptDefAliasImpl, ClassDef, ConceptDef, ClassDef, ConceptDef, DirDefImpl, FileDefImpl, GroupDefImpl, MemberDefImpl, NamespaceDefImpl, PageDefImpl, DirDefImpl, FileDefImpl, GroupDefImpl, MemberDefImpl, NamespaceDefImpl, PageDefImpl, DirDef, FileDef, GroupDef, MemberDef, NamespaceDef, PageDef, DirDef, FileDef, GroupDef, MemberDef, NamespaceDef, and PageDef.
docFile() [1/2]
virtual QCString Definition::docFile () const [pure virtual]
Returns the file in which the detailed documentation block was found. This can differ from getDefFileName().
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by addMembersToMemberGroup(), ClassDefImpl::addMembersToTemplateInstance(), addRelatedPage(), DocParser::checkArgumentName(), DocParser::checkUnOrMultipleDocumentedParams(), combineDeclarationAndDefinition(), computePageRelations(), DefinitionContext< T >::createDetails(), ArgumentContext::Private::createDocs(), PageContext::Private::createExample(), MemberContext::Private::createParamDocs(), createTagLessInstance(), MemberGroup::distributeMemberGroupDocumentation(), DefinitionAliasMixin< Base >::docFile(), findUsingDeclImports(), PerlModGenerator::generatePerlModForPage(), generateXMLForClass(), generateXMLForConcept(), generateXMLForDir(), generateXMLForFile(), generateXMLForGroup(), generateXMLForMember(), generateXMLForNamespace(), generateXMLForPage(), generateXMLSection(), inheritDocumentation(), parseCode(), DocParser::processCopyDoc(), and writeTypeConstraints().
docFile() [2/2]
virtual QCString Definition::docFile () const [pure virtual]
Returns the file in which the detailed documentation block was found. This can differ from getDefFileName().
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
docLine() [1/2]
virtual int Definition::docLine () const [pure virtual]
Returns the line number at which the detailed documentation was found.
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by ClassDefImpl::addMembersToTemplateInstance(), DocParser::checkArgumentName(), DocParser::checkUnOrMultipleDocumentedParams(), combineDeclarationAndDefinition(), computePageRelations(), DefinitionContext< T >::createDetails(), ArgumentContext::Private::createDocs(), PageContext::Private::createExample(), MemberContext::Private::createParamDocs(), createTagLessInstance(), MemberGroup::distributeMemberGroupDocumentation(), DefinitionAliasMixin< Base >::docLine(), findUsingDeclImports(), PerlModGenerator::generatePerlModForPage(), generateXMLForClass(), generateXMLForConcept(), generateXMLForDir(), generateXMLForFile(), generateXMLForGroup(), generateXMLForMember(), generateXMLForNamespace(), generateXMLForPage(), generateXMLSection(), inheritDocumentation(), DocParser::processCopyDoc(), and writeTypeConstraints().
docLine() [2/2]
virtual int Definition::docLine () const [pure virtual]
Returns the line number at which the detailed documentation was found.
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
documentation() [1/2]
virtual QCString Definition::documentation () const [pure virtual]
Returns the detailed description of this definition
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, MemberDefImpl, MemberDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, MemberDefImpl, MemberDefAliasImpl, MemberDef, and MemberDef.
Referenced by MemberDefImpl::_writeEnumValues(), DefinitionContext< T >::createDetails(), createTagLessInstance(), DefinitionAliasMixin< Base >::documentation(), DocParser::findDocsForMemberOrCompound(), generateDEFForClass(), generateDEFForFile(), generateDEFForNamespace(), PerlModGenerator::generatePerlModForClass(), PerlModGenerator::generatePerlModForConcept(), PerlModGenerator::generatePerlModForFile(), PerlModGenerator::generatePerlModForGroup(), PerlModGenerator::generatePerlModForNamespace(), PerlModGenerator::generatePerlModForPage(), generateXMLForClass(), generateXMLForConcept(), generateXMLForDir(), generateXMLForFile(), generateXMLForGroup(), generateXMLForNamespace(), and generateXMLForPage().
documentation() [2/2]
virtual QCString Definition::documentation () const [pure virtual]
Returns the detailed description of this definition
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, MemberDefImpl, MemberDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, MemberDefImpl, MemberDefAliasImpl, MemberDef, and MemberDef.
externalReference() [1/2]
virtual QCString Definition::externalReference (const QCString & relPath) const [pure virtual]
Convenience method to return a resolved external link
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by DefinitionContext< T >::externalReference(), NestingNodeContext::Private::externalReference(), NavPathElemContext::Private::externalReference(), and DefinitionAliasMixin< Base >::externalReference().
externalReference() [2/2]
virtual QCString Definition::externalReference (const QCString & relPath) const [pure virtual]
Convenience method to return a resolved external link
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
findInnerCompound() [1/2]
virtual const Definition * Definition::findInnerCompound (const QCString & name) const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, NamespaceDefImpl, NamespaceDefAliasImpl, ClassDefImpl, ClassDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, NamespaceDefImpl, NamespaceDefAliasImpl, ClassDef, NamespaceDef, ClassDef, and NamespaceDef.
Referenced by DefinitionAliasMixin< Base >::findInnerCompound(), findScopeFromQualifiedName(), SymbolResolver::Private::followPath(), and resolveTypeDef().
findInnerCompound() [2/2]
virtual const Definition * Definition::findInnerCompound (const QCString & name) const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, NamespaceDefImpl, NamespaceDefAliasImpl, ClassDefImpl, ClassDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, NamespaceDefImpl, NamespaceDefAliasImpl, ClassDef, NamespaceDef, ClassDef, and NamespaceDef.
getBodyDef() [1/2]
virtual const FileDef * Definition::getBodyDef () const [pure virtual]
Returns the file in which the body of this item is located or 0 if no body is available.
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by DefinitionImpl::_writeSourceRefList(), addSourceReferences(), combineDeclarationAndDefinition(), createLinkedText(), SymbolContext::Private::createScope(), MemberContext::Private::createSourceCode(), createTagLessInstance(), DefinitionContext< T >::DefinitionContext(), findMember(), findUsingDeclImports(), generateClassOrGlobalLink(), generateXMLForClass(), generateXMLForMember(), DefinitionAliasMixin< Base >::getBodyDef(), getLink(), getLinkInScope(), parseCode(), writeDefArgumentList(), writeExceptionListImpl(), writeJavaScriptSearchIndex(), writeMemberReference(), and TooltipManager::writeTooltips().
getBodyDef() [2/2]
virtual const FileDef * Definition::getBodyDef () const [pure virtual]
Returns the file in which the body of this item is located or 0 if no body is available.
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
getDefColumn() [1/2]
virtual int Definition::getDefColumn () const [pure virtual]
returns the column number at which the definition was found
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by addVariableToFile(), createTagLessInstance(), findUsedClassesForClass(), generateXMLForClass(), generateXMLForConcept(), generateXMLForMember(), generateXMLForNamespace(), and DefinitionAliasMixin< Base >::getDefColumn().
getDefColumn() [2/2]
virtual int Definition::getDefColumn () const [pure virtual]
returns the column number at which the definition was found
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
getDefFileExtension() [1/2]
virtual QCString Definition::getDefFileExtension () const [pure virtual]
returns the extension of the file in which this definition was found
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by findXRefSymbols(), DefinitionAliasMixin< Base >::getDefFileExtension(), HtmlDocVisitor::HtmlDocVisitor(), parseCode(), parseDoc(), ManGenerator::writeDoc(), RTFGenerator::writeDoc(), LatexGenerator::writeDoc(), DocbookGenerator::writeDoc(), writeXMLCodeBlock(), and writeXMLDocBlock().
getDefFileExtension() [2/2]
virtual QCString Definition::getDefFileExtension () const [pure virtual]
returns the extension of the file in which this definition was found
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
getDefFileName() [1/2]
virtual QCString Definition::getDefFileName () const [pure virtual]
returns the file in which this definition was found
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by addInstance(), addMemberFunction(), addVariableToFile(), DocParser::checkArgumentName(), DocParser::checkRetvalName(), createTagLessInstance(), dumpSymbol(), findGlobalMember(), findUsedClassesForClass(), formatBriefNote(), generateDEFForClass(), generateDEFForFile(), generateDEFForMember(), generateDEFForNamespace(), PerlModGenerator::generatePerlModForClass(), PerlModGenerator::generatePerlModForConcept(), PerlModGenerator::generatePerlModForFile(), PerlModGenerator::generatePerlModForGroup(), PerlModGenerator::generatePerlModForMember(), PerlModGenerator::generatePerlModForNamespace(), generateXMLForClass(), generateXMLForConcept(), generateXMLForFile(), generateXMLForMember(), generateXMLForNamespace(), generateXMLForPage(), genericCompareMembers(), DefinitionAliasMixin< Base >::getDefFileName(), MemberDefImpl::IMPL::init(), ClassDefImpl::internalInsertMember(), XRefDummyCodeGenerator::linkableSymbol(), lookupSymbol(), SymbolResolver::Private::newResolveTypedef(), resolveClassNestingRelations(), writeDirTreeNode(), writeExceptionListImpl(), and writeGroupTreeNode().
getDefFileName() [2/2]
virtual QCString Definition::getDefFileName () const [pure virtual]
returns the file in which this definition was found
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
getDefLine() [1/2]
virtual int Definition::getDefLine () const [pure virtual]
returns the line number at which the definition was found (can be the declaration)
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by addMemberFunction(), addVariableToFile(), DocParser::checkArgumentName(), DocParser::checkRetvalName(), combineDeclarationAndDefinition(), createTagLessInstance(), dumpSymbol(), findGlobalMember(), findMember(), findUsedClassesForClass(), findUsingDeclImports(), generateDEFForClass(), generateDEFForFile(), generateDEFForMember(), generateDEFForNamespace(), PerlModGenerator::generatePerlModForClass(), PerlModGenerator::generatePerlModForConcept(), PerlModGenerator::generatePerlModForFile(), PerlModGenerator::generatePerlModForGroup(), PerlModGenerator::generatePerlModForMember(), PerlModGenerator::generatePerlModForNamespace(), generateXMLForClass(), generateXMLForConcept(), generateXMLForMember(), generateXMLForNamespace(), genericCompareMembers(), DefinitionAliasMixin< Base >::getDefLine(), ClassDefImpl::internalInsertMember(), XRefDummyCodeGenerator::linkableSymbol(), lookupSymbol(), resolveClassNestingRelations(), writeDirTreeNode(), writeExceptionListImpl(), and writeGroupTreeNode().
getDefLine() [2/2]
virtual int Definition::getDefLine () const [pure virtual]
returns the line number at which the definition was found (can be the declaration)
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
getEndBodyLine() [1/2]
virtual int Definition::getEndBodyLine () const [pure virtual]
Returns the last line of the body of this item (applicable to classes and functions).
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by combineDeclarationAndDefinition(), VhdlDocGen::createFlowChart(), MemberContext::Private::createSourceCode(), createTagLessInstance(), findMember(), findUsingDeclImports(), functionInformation(), PerlModGenerator::generatePerlModForClass(), generateXMLForClass(), generateXMLForMember(), DefinitionAliasMixin< Base >::getEndBodyLine(), writeMemberReference(), and VhdlDocGen::writeSource().
getEndBodyLine() [2/2]
virtual int Definition::getEndBodyLine () const [pure virtual]
Returns the last line of the body of this item (applicable to classes and functions).
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
getLanguage() [1/2]
virtual SrcLangExt Definition::getLanguage () const [pure virtual]
Returns the programming language this definition was written in.
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by SymbolResolver::Private::accessibleViaUsingNamespace(), NestingContext::Private::addClass(), NestingNodeContext::Private::addClasses(), NestingContext::Private::addDerivedClasses(), DocSets::addIndexItem(), addMemberFunction(), addVariableToClass(), addVariableToFile(), buildNamespaceList(), DocParser::checkArgumentName(), DocParser::checkUnOrMultipleDocumentedParams(), classHasVisibleChildren(), combineDeclarationAndDefinition(), compoundIcon(), computeMemberRelations(), computeTemplateClassRelations(), ClassContext::Private::createAdditionalInheritedMembers(), NamespaceContext::Private::createDetailedFunctions(), FileContext::Private::createDetailedFunctions(), ModuleContext::Private::createDetailedFunctions(), NamespaceContext::Private::createFunctions(), FileContext::Private::createFunctions(), ModuleContext::Private::createFunctions(), ClassContext::Private::createIncludeInfo(), ConceptContext::Private::createIncludeInfo(), FileContext::Private::createIncludeList(), ClassContext::Private::createPublicMethods(), ClassContext::Private::createPublicStaticMethods(), SymbolContext::Private::createScope(), createTagLessInstance(), DocRef::DocRef(), DotCallGraph::DotCallGraph(), findMembersWithSpecificName(), findUsedClassesForClass(), findUsingDirectives(), generateDEFForMember(), generateFileSources(), generateLink(), PerlModGenerator::generatePerlModForMember(), generateXMLForClass(), generateXMLForFile(), generateXMLForMember(), generateXMLForNamespace(), getCanonicalTypeForIdentifier(), getDefsOld(), DefinitionAliasMixin< Base >::getLanguage(), getLink(), SymbolResolver::Private::getResolvedSymbol(), SymbolResolver::Private::getResolvedSymbolRec(), SymbolResolver::Private::getResolvedTypeRec(), MemberContext::Private::handleNameWithContextFor(), if(), MemberDefImpl::IMPL::init(), GroupDefImpl::insertMember(), DefinitionContext< T >::language(), makeDisplayName(), makeQualifiedNameWithTemplateParameters(), ClassDefImpl::mergeMembers(), parseCode(), parseFilesMultiThreading(), DefinitionAliasImpl::qualifiedName(), SymbolResolver::resolveClass(), resolveClassNestingRelations(), SearchIndex::setCurrentDoc(), transferFunctionReferences(), transferRelatedFunctionDocumentation(), GroupDefImpl::updateLanguage(), writeClassTree(), writeClassTreeInsideNamespaceElement(), writeClassTreeToOutput(), writeDefArgumentList(), FileDefImpl::writeIncludeFiles(), writeJavaScriptSearchIndex(), DotNode::writeLabel(), ClassDefImpl::writeMemberList(), writeMemberReference(), writeNamespaceTreeElement(), MemberList::writeTagFile(), and FileDefImpl::writeTagFile().
getLanguage() [2/2]
virtual SrcLangExt Definition::getLanguage () const [pure virtual]
Returns the programming language this definition was written in.
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
getOuterScope() [1/2]
virtual Definition * Definition::getOuterScope () const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by SymbolResolver::Private::accessibleViaUsingNamespace(), NestingContext::Private::addClass(), NestingContext::Private::addConcept(), addEnumValuesToEnums(), addMemberDocs(), NestingContext::Private::addNamespace(), NestingContext::Private::addPage(), addSourceReferences(), ClassContext::Private::addTemplateDecls(), addVariableToFile(), buildNamespaceList(), checkPageRelations(), combineDeclarationAndDefinition(), computeMemberRelations(), DefinitionImpl::computeTooltip(), ConceptContext::Private::createInitializerAsCode(), MemberContext::Private::createLabels(), createLinkedText(), DefinitionContext< T >::createNavigationPath(), SymbolContext::Private::createScope(), createTagLessInstance(), DotCallGraph::DotCallGraph(), dumpSymbol(), DefinitionContext< T >::fillPath(), findGlobalMember(), findMember(), VhdlDocGen::findMember(), findMemberLink(), findMembersWithSpecificName(), findTagLessClasses(), findUsingDirectives(), SymbolResolver::Private::followPath(), generateClassDocs(), generateClassMemberLink(), generateClassOrGlobalLink(), generateConceptDocs(), generateDocsForClassList(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), getDefsOld(), getLink(), getLinkInScope(), getResolvedConcept(), SymbolResolver::Private::getResolvedSymbol(), SymbolResolver::Private::getResolvedType(), ClassDefImpl::getTemplateParameterLists(), DocPara::handleInheritDoc(), if(), GroupDefImpl::insertMember(), SymbolResolver::Private::isAccessibleFrom(), SymbolResolver::Private::isAccessibleFromWithExpScope(), isSymbolHidden(), XRefDummyCodeGenerator::linkableSymbol(), makeQualifiedNameWithTemplateParameters(), ClassDefImpl::mergeMembers(), SymbolResolver::Private::newResolveTypedef(), resolveClassNestingRelations(), resolveRef(), resolveTypeDef(), scopeIsTemplate(), searchTemplateSpecs(), setCallContextForVar(), transferFunctionReferences(), transferRelatedFunctionDocumentation(), updateCallContextForSmartPointer(), writeClassTree(), writeClassTreeInsideNamespaceElement(), writeConceptTreeInsideNamespaceElement(), writeJavaScriptSearchIndex(), writeMemberToIndex(), writeNamespaceTreeElement(), and VhdlDocGen::writeVHDLDeclaration().
getOuterScope() [2/2]
virtual Definition * Definition::getOuterScope () const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
getOutputFileBase() [1/2]
virtual QCString Definition::getOutputFileBase () const [pure virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implemented in ClassDefImpl, ClassDefAliasImpl, ConceptDefImpl, ConceptDefAliasImpl, DirDefImpl, FileDefImpl, GroupDefImpl, MemberDefImpl, MemberDefAliasImpl, NamespaceDefImpl, NamespaceDefAliasImpl, PageDefImpl, ClassDefImpl, ClassDefAliasImpl, ConceptDefImpl, ConceptDefAliasImpl, DirDefImpl, FileDefImpl, GroupDefImpl, MemberDefImpl, MemberDefAliasImpl, NamespaceDefImpl, NamespaceDefAliasImpl, PageDefImpl, ClassDef, ConceptDef, DirDef, FileDef, GroupDef, MemberDef, NamespaceDef, PageDef, ClassDef, ConceptDef, DirDef, FileDef, GroupDef, MemberDef, NamespaceDef, and PageDef.
Referenced by DocSets::addIndexItem(), HtmlHelp::addIndexItem(), Qhp::addIndexItem(), DefinitionImpl::addSectionsToIndex(), TooltipManager::addTooltip(), DocLink::DocLink(), DocRef::DocRef(), dumpSymbol(), DefinitionContext< T >::fileName(), NestingNodeContext::Private::fileName(), NavPathElemContext::Private::fileName(), SymbolContext::Private::fileName(), generateBriefDoc(), generateLink(), getLinkInScope(), ClassDefImpl::getOutputFileBase(), DocParser::handleLinkedWord(), DefinitionImpl::navigationPathAsString(), SearchIndex::setCurrentDoc(), SearchIndexExternal::setCurrentDoc(), startCodeLine(), LayoutNavEntry::url(), validatingParseDoc(), writeJavaScriptSearchIndex(), writeMemberToIndex(), writeMultiLineCodeLink(), DocSets::writeToken(), TooltipManager::writeTooltips(), and VhdlDocGen::writeVHDLDeclaration().
getOutputFileBase() [2/2]
virtual QCString Definition::getOutputFileBase () const [pure virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implemented in ClassDefImpl, ClassDefAliasImpl, ConceptDefImpl, ConceptDefAliasImpl, DirDefImpl, FileDefImpl, GroupDefImpl, MemberDefImpl, MemberDefAliasImpl, NamespaceDefImpl, NamespaceDefAliasImpl, PageDefImpl, ClassDefImpl, ClassDefAliasImpl, ConceptDefImpl, ConceptDefAliasImpl, DirDefImpl, FileDefImpl, GroupDefImpl, MemberDefImpl, MemberDefAliasImpl, NamespaceDefImpl, NamespaceDefAliasImpl, PageDefImpl, ClassDef, ConceptDef, DirDef, FileDef, GroupDef, MemberDef, NamespaceDef, PageDef, ClassDef, ConceptDef, DirDef, FileDef, GroupDef, MemberDef, NamespaceDef, and PageDef.
getReference() [1/2]
virtual QCString Definition::getReference () const [pure virtual]
If this definition was imported via a tag file, this function returns the tagfile for the external project. This can be translated into an external link target via Doxygen::tagDestinationDict
Implemented in ClassDefImpl, ClassDefAliasImpl, ConceptDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, MemberDefImpl, MemberDefAliasImpl, ClassDefImpl, ClassDefAliasImpl, ConceptDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, MemberDefImpl, MemberDefAliasImpl, ClassDef, MemberDef, ClassDef, and MemberDef.
Referenced by MemberDefImpl::_writeGroupInclude(), addRelatedPage(), buildDirectories(), DotInclDepGraph::buildGraph(), DocLink::DocLink(), DocRef::DocRef(), DotGroupCollaboration::DotGroupCollaboration(), DotInclDepGraph::DotInclDepGraph(), generateFileRef(), generateLink(), getLinkInScope(), ConceptDefAliasImpl::getReference(), DefinitionAliasMixin< Base >::getReference(), MemberDefImpl::getReference(), DocParser::handleLinkedWord(), if(), SymbolContext::Private::relPath(), startCodeLine(), writeAlphabeticalClassList(), writeClassTreeInsideNamespaceElement(), writeConceptTreeInsideNamespaceElement(), writeDirTreeNode(), writeGroupTreeNode(), FileDefImpl::writeIncludeFiles(), writeJavaScriptSearchIndex(), MemberDefImpl::writeLink(), writeMemberToIndex(), writeMultiLineCodeLink(), writeNamespaceTreeElement(), writePages(), writePartialDirPath(), writePartialFilePath(), and TooltipManager::writeTooltips().
getReference() [2/2]
virtual QCString Definition::getReference () const [pure virtual]
If this definition was imported via a tag file, this function returns the tagfile for the external project. This can be translated into an external link target via Doxygen::tagDestinationDict
Implemented in ClassDefImpl, ClassDefAliasImpl, ConceptDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, MemberDefImpl, MemberDefAliasImpl, ClassDefImpl, ClassDefAliasImpl, ConceptDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, MemberDefImpl, MemberDefAliasImpl, ClassDef, MemberDef, ClassDef, and MemberDef.
getReferencedByMembers() [1/2]
virtual const MemberVector & Definition::getReferencedByMembers () const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by DotCallGraph::buildGraph(), MemberContext::Private::createSourceRefBys(), generateDEFForMember(), generateXMLForMember(), DefinitionAliasMixin< Base >::getReferencedByMembers(), and DotCallGraph::isTrivial().
getReferencedByMembers() [2/2]
virtual const MemberVector & Definition::getReferencedByMembers () const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
getReferencesMembers() [1/2]
virtual const MemberVector & Definition::getReferencesMembers () const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by DotCallGraph::buildGraph(), MemberContext::Private::createSourceRefs(), functionInformation(), generateDEFForMember(), generateXMLForMember(), DefinitionAliasMixin< Base >::getReferencesMembers(), and DotCallGraph::isTrivial().
getReferencesMembers() [2/2]
virtual const MemberVector & Definition::getReferencesMembers () const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
getSectionRefs() [1/2]
virtual const SectionRefs & Definition::getSectionRefs () const [pure virtual]
returns the section dictionary, only of importance for pagedef
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by generateXMLForPage(), and DefinitionAliasMixin< Base >::getSectionRefs().
getSectionRefs() [2/2]
virtual const SectionRefs & Definition::getSectionRefs () const [pure virtual]
returns the section dictionary, only of importance for pagedef
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
getSourceAnchor() [1/2]
virtual QCString Definition::getSourceAnchor () const [pure virtual]
Returns the anchor of the source listing of this definition.
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by DefinitionContext< T >::DefinitionContext(), DefinitionAliasMixin< Base >::getSourceAnchor(), and TooltipManager::writeTooltips().
getSourceAnchor() [2/2]
virtual QCString Definition::getSourceAnchor () const [pure virtual]
Returns the anchor of the source listing of this definition.
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
getSourceFileBase() [1/2]
virtual QCString Definition::getSourceFileBase () const [pure virtual]
Returns the name of the source listing of this definition.
Implemented in ClassDefImpl, ClassDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, FileDefImpl, ClassDefImpl, ClassDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, FileDefImpl, ClassDef, FileDef, ClassDef, and FileDef.
Referenced by DefinitionContext< T >::DefinitionContext(), DocLink::DocLink(), DocRef::DocRef(), DefinitionAliasMixin< Base >::getSourceFileBase(), DocParser::handleLinkedWord(), DefinitionContext< T >::sourceFileName(), and TooltipManager::writeTooltips().
getSourceFileBase() [2/2]
virtual QCString Definition::getSourceFileBase () const [pure virtual]
Returns the name of the source listing of this definition.
Implemented in ClassDefImpl, ClassDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, FileDefImpl, ClassDefImpl, ClassDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, FileDefImpl, ClassDef, FileDef, ClassDef, and FileDef.
getStartBodyLine() [1/2]
virtual int Definition::getStartBodyLine () const [pure virtual]
Returns the first line of the body of this item (applicable to classes and functions).
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by DefinitionImpl::_writeSourceRefList(), addMemberDocs(), addRelatedPage(), combineDeclarationAndDefinition(), VhdlDocGen::createFlowChart(), MemberContext::Private::createSourceCode(), createTagLessInstance(), DefinitionContext< T >::DefinitionContext(), findMember(), findMemFlow(), findUsingDeclImports(), functionInformation(), PerlModGenerator::generatePerlModForClass(), generateXMLForClass(), generateXMLForMember(), DefinitionAliasMixin< Base >::getStartBodyLine(), writeMemberReference(), VhdlDocGen::writeSource(), and TooltipManager::writeTooltips().
getStartBodyLine() [2/2]
virtual int Definition::getStartBodyLine () const [pure virtual]
Returns the first line of the body of this item (applicable to classes and functions).
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
getStartDefLine() [1/2]
virtual int Definition::getStartDefLine () const [pure virtual]
Returns the first line of the implementation of this item. See also getDefLine()
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by addSourceReferences(), and DefinitionAliasMixin< Base >::getStartDefLine().
getStartDefLine() [2/2]
virtual int Definition::getStartDefLine () const [pure virtual]
Returns the first line of the implementation of this item. See also getDefLine()
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
hasBriefDescription() [1/2]
virtual bool Definition::hasBriefDescription () const [pure virtual]
returns TRUE if this class has a brief description
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by DefinitionContext< T >::createBrief(), NestingNodeContext::Private::createBrief(), and DefinitionAliasMixin< Base >::hasBriefDescription().
hasBriefDescription() [2/2]
virtual bool Definition::hasBriefDescription () const [pure virtual]
returns TRUE if this class has a brief description
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
hasDocumentation() [1/2]
virtual bool Definition::hasDocumentation () const [pure virtual]
Returns TRUE iff the definition is documented (which could be generated documentation)
See also
hasUserDocumentation()
Implemented in ClassDefImpl, ClassDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, MemberDefImpl, MemberDefAliasImpl, ClassDefImpl, ClassDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, MemberDefImpl, MemberDefAliasImpl, ClassDef, MemberDef, ClassDef, and MemberDef.
Referenced by dirHasVisibleChildren(), generateDirDocs(), and DefinitionAliasMixin< Base >::hasDocumentation().
hasDocumentation() [2/2]
virtual bool Definition::hasDocumentation () const [pure virtual]
Returns TRUE iff the definition is documented (which could be generated documentation)
See also
hasUserDocumentation()
Implemented in ClassDefImpl, ClassDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, MemberDefImpl, MemberDefAliasImpl, ClassDefImpl, ClassDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, MemberDefImpl, MemberDefAliasImpl, ClassDef, MemberDef, ClassDef, and MemberDef.
hasSections() [1/2]
virtual bool Definition::hasSections () const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by DefinitionAliasMixin< Base >::hasSections(), and writePages().
hasSections() [2/2]
virtual bool Definition::hasSections () const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
hasSources() [1/2]
virtual bool Definition::hasSources () const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by MemberContext::Private::hasSources(), and DefinitionAliasMixin< Base >::hasSources().
hasSources() [2/2]
virtual bool Definition::hasSources () const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
hasUserDocumentation() [1/2]
virtual bool Definition::hasUserDocumentation () const [pure virtual]
Returns TRUE iff the definition is documented by the user.
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by DefinitionAliasMixin< Base >::hasUserDocumentation().
hasUserDocumentation() [2/2]
virtual bool Definition::hasUserDocumentation () const [pure virtual]
Returns TRUE iff the definition is documented by the user.
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
id() [1/2]
virtual QCString Definition::id () const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), DefinitionAliasMixin< Base >::id(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), and doxmlparser.compound.docXRefSectType::set_id().
id() [2/2]
virtual QCString Definition::id () const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), and doxmlparser.compound.docXRefSectType::set_id().
inbodyDocumentation() [1/2]
virtual QCString Definition::inbodyDocumentation () const [pure virtual]
Returns the documentation found inside the body of a member
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by addEnumDocs(), addMemberDocs(), ClassDefImpl::addMembersToTemplateInstance(), combineDeclarationAndDefinition(), DefinitionContext< T >::createInbodyDocs(), MemberGroup::distributeMemberGroupDocumentation(), findDefineDocumentation(), findUsingDeclImports(), generateXMLForMember(), DefinitionAliasMixin< Base >::inbodyDocumentation(), and inheritDocumentation().
inbodyDocumentation() [2/2]
virtual QCString Definition::inbodyDocumentation () const [pure virtual]
Returns the documentation found inside the body of a member
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
inbodyFile() [1/2]
virtual QCString Definition::inbodyFile () const [pure virtual]
Returns the file in which the in body documentation was found
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by ClassDefImpl::addMembersToTemplateInstance(), combineDeclarationAndDefinition(), DefinitionContext< T >::createInbodyDocs(), MemberGroup::distributeMemberGroupDocumentation(), findUsingDeclImports(), DefinitionAliasMixin< Base >::inbodyFile(), and inheritDocumentation().
inbodyFile() [2/2]
virtual QCString Definition::inbodyFile () const [pure virtual]
Returns the file in which the in body documentation was found
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
inbodyLine() [1/2]
virtual int Definition::inbodyLine () const [pure virtual]
Returns the line at which the first in body documentation part was found
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by ClassDefImpl::addMembersToTemplateInstance(), combineDeclarationAndDefinition(), DefinitionContext< T >::createInbodyDocs(), MemberGroup::distributeMemberGroupDocumentation(), findUsingDeclImports(), generateXMLForMember(), DefinitionAliasMixin< Base >::inbodyLine(), and inheritDocumentation().
inbodyLine() [2/2]
virtual int Definition::inbodyLine () const [pure virtual]
Returns the line at which the first in body documentation part was found
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
isAlias() [1/2]
virtual bool Definition::isAlias () const [pure virtual]
Returns TRUE if this is an alias of another definition
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by MemberList::addListReferences(), findGlobalMember(), and MemberGroup::insertMember().
isAlias() [2/2]
virtual bool Definition::isAlias () const [pure virtual]
Returns TRUE if this is an alias of another definition
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
isAnonymous() [1/2]
virtual bool Definition::isAnonymous () const [pure virtual]
Returns TRUE iff this definition has an artificially generated name (typically starting with a @) that is used for nameless definitions
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by DotClassGraph::addClass(), addEnumValuesToEnums(), NestingContext::Private::addNamespace(), addToIndices(), addVariableToFile(), findEnums(), PerlModGenerator::generatePerlModForClass(), PerlModGenerator::generatePerlModForMember(), generateXMLForClass(), MemberDefImpl::getOutputFileBase(), SymbolResolver::Private::isAccessibleFrom(), MemberContext::Private::isAnonymous(), DefinitionAliasMixin< Base >::isAnonymous(), makeDisplayName(), AllMembersListContext::Private::Private(), writeClassTreeInsideNamespaceElement(), writeConceptTreeInsideNamespaceElement(), writeListOfAllMembers(), ClassDefImpl::writeMemberList(), writeMemberToIndex(), writeNamespaceTreeElement(), and TooltipManager::writeTooltips().
isAnonymous() [2/2]
virtual bool Definition::isAnonymous () const [pure virtual]
Returns TRUE iff this definition has an artificially generated name (typically starting with a @) that is used for nameless definitions
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
isArtificial() [1/2]
virtual bool Definition::isArtificial () const [pure virtual]
returns TRUE if this entity was artificially introduced, for instance because it is used to show a template instantiation relation.
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by buildNamespaceList(), findClassRelation(), generateXMLForClass(), DefinitionAliasMixin< Base >::isArtificial(), AllMembersListContext::Private::Private(), and ClassDefImpl::writeMemberList().
isArtificial() [2/2]
virtual bool Definition::isArtificial () const [pure virtual]
returns TRUE if this entity was artificially introduced, for instance because it is used to show a template instantiation relation.
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
isHidden() [1/2]
virtual bool Definition::isHidden () const [pure virtual]
Returns TRUE iff this item is supposed to be hidden from the output.
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by DotClassGraph::addClass(), GroupDefImpl::addClass(), GroupDefImpl::addConcept(), GroupDefImpl::addDir(), GroupDefImpl::addExample(), GroupDefImpl::addFile(), DotGfxHierarchyTable::addHierarchy(), GroupDefImpl::addNamespace(), GroupDefImpl::addPage(), DotInclDepGraph::buildGraph(), DotClassGraph::DotClassGraph(), generateConceptDocs(), generateDocsForClassList(), generateNamespaceClassDocs(), generateNamespaceConceptDocs(), generateXMLForClass(), generateXMLForConcept(), generateXMLForMember(), generateXMLForNamespace(), hasNonReferenceSuperClassRec(), FileDefImpl::insertClass(), FileDefImpl::insertConcept(), GroupDefImpl::insertMember(), FileDefImpl::insertMember(), NamespaceDefImpl::insertMember(), FileDefImpl::insertNamespace(), ClassDefImpl::internalInsertMember(), DefinitionAliasMixin< Base >::isHidden(), isSymbolHidden(), SymbolResolver::resolveClass(), and DefinitionImpl::setOuterScope().
isHidden() [2/2]
virtual bool Definition::isHidden () const [pure virtual]
Returns TRUE iff this item is supposed to be hidden from the output.
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
isLinkable() [1/2]
virtual bool Definition::isLinkable () const [pure virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implemented in ClassDefImpl, ClassDefAliasImpl, ConceptDefImpl, ConceptDefAliasImpl, DirDefImpl, FileDefImpl, GroupDefImpl, MemberDefImpl, MemberDefAliasImpl, NamespaceDefImpl, NamespaceDefAliasImpl, PageDefImpl, ClassDefImpl, ClassDefAliasImpl, ConceptDefImpl, ConceptDefAliasImpl, DirDefImpl, FileDefImpl, GroupDefImpl, MemberDefImpl, MemberDefAliasImpl, NamespaceDefImpl, NamespaceDefAliasImpl, PageDefImpl, ClassDef, ConceptDef, DirDef, FileDef, GroupDef, MemberDef, NamespaceDef, PageDef, ClassDef, ConceptDef, DirDef, FileDef, GroupDef, MemberDef, NamespaceDef, and PageDef.
Referenced by DocSets::addIndexItem(), DocLink::DocLink(), DocRef::DocRef(), generateClassMemberLink(), generateClassOrGlobalLink(), getLink(), getLinkInScope(), DocParser::handleLinkedWord(), DefinitionContext< T >::isLinkable(), NestingNodeContext::Private::isLinkable(), NavPathElemContext::Private::isLinkable(), DefinitionImpl::isVisible(), DefinitionImpl::navigationPathAsString(), DefinitionImpl::pathFragment(), and LayoutNavEntry::url().
isLinkable() [2/2]
virtual bool Definition::isLinkable () const [pure virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implemented in ClassDefImpl, ClassDefAliasImpl, ConceptDefImpl, ConceptDefAliasImpl, DirDefImpl, FileDefImpl, GroupDefImpl, MemberDefImpl, MemberDefAliasImpl, NamespaceDefImpl, NamespaceDefAliasImpl, PageDefImpl, ClassDefImpl, ClassDefAliasImpl, ConceptDefImpl, ConceptDefAliasImpl, DirDefImpl, FileDefImpl, GroupDefImpl, MemberDefImpl, MemberDefAliasImpl, NamespaceDefImpl, NamespaceDefAliasImpl, PageDefImpl, ClassDef, ConceptDef, DirDef, FileDef, GroupDef, MemberDef, NamespaceDef, PageDef, ClassDef, ConceptDef, DirDef, FileDef, GroupDef, MemberDef, NamespaceDef, and PageDef.
isLinkableInProject() [1/2]
virtual bool Definition::isLinkableInProject () const [pure virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implemented in ClassDefImpl, ClassDefAliasImpl, ConceptDefImpl, ConceptDefAliasImpl, DirDefImpl, FileDefImpl, GroupDefImpl, MemberDefImpl, MemberDefAliasImpl, NamespaceDefImpl, NamespaceDefAliasImpl, PageDefImpl, ClassDefImpl, ClassDefAliasImpl, ConceptDefImpl, ConceptDefAliasImpl, DirDefImpl, FileDefImpl, GroupDefImpl, MemberDefImpl, MemberDefAliasImpl, NamespaceDefImpl, NamespaceDefAliasImpl, PageDefImpl, ClassDef, ConceptDef, DirDef, FileDef, GroupDef, MemberDef, NamespaceDef, PageDef, ClassDef, ConceptDef, DirDef, FileDef, GroupDef, MemberDef, NamespaceDef, and PageDef.
Referenced by ClassDefImpl::getOutputFileBase(), ClassDefImpl::isEmbeddedInOuterScope(), DefinitionContext< T >::isLinkableInProject(), DefinitionImpl::isVisibleInProject(), and startCodeLine().
isLinkableInProject() [2/2]
virtual bool Definition::isLinkableInProject () const [pure virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implemented in ClassDefImpl, ClassDefAliasImpl, ConceptDefImpl, ConceptDefAliasImpl, DirDefImpl, FileDefImpl, GroupDefImpl, MemberDefImpl, MemberDefAliasImpl, NamespaceDefImpl, NamespaceDefAliasImpl, PageDefImpl, ClassDefImpl, ClassDefAliasImpl, ConceptDefImpl, ConceptDefAliasImpl, DirDefImpl, FileDefImpl, GroupDefImpl, MemberDefImpl, MemberDefAliasImpl, NamespaceDefImpl, NamespaceDefAliasImpl, PageDefImpl, ClassDef, ConceptDef, DirDef, FileDef, GroupDef, MemberDef, NamespaceDef, PageDef, ClassDef, ConceptDef, DirDef, FileDef, GroupDef, MemberDef, NamespaceDef, and PageDef.
isLinkableViaGroup() [1/2]
virtual bool Definition::isLinkableViaGroup () const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by DefinitionAliasMixin< Base >::isLinkableViaGroup().
isLinkableViaGroup() [2/2]
virtual bool Definition::isLinkableViaGroup () const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
isReference() [1/2]
virtual bool Definition::isReference () const [pure virtual]
Returns TRUE if this definition is imported via a tag file.
Implemented in ClassDefImpl, ClassDefAliasImpl, ConceptDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, MemberDefImpl, MemberDefAliasImpl, ClassDefImpl, ClassDefAliasImpl, ConceptDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, MemberDefImpl, MemberDefAliasImpl, ClassDef, MemberDef, ClassDef, and MemberDef.
Referenced by addRelatedPage(), generateDEFForFile(), generateDEFForNamespace(), generateDiskNames(), generateFileSources(), generateGroupDocs(), generateLink(), PerlModGenerator::generatePerlModForConcept(), PerlModGenerator::generatePerlModForFile(), PerlModGenerator::generatePerlModForGroup(), PerlModGenerator::generatePerlModForNamespace(), PerlModGenerator::generatePerlModForPage(), generateXMLForConcept(), generateXMLForDir(), generateXMLForFile(), generateXMLForGroup(), generateXMLForNamespace(), generateXMLForPage(), ConceptDefAliasImpl::isReference(), DefinitionContext< T >::isReference(), NestingNodeContext::Private::isReference(), NavPathElemContext::Private::isReference(), DefinitionAliasMixin< Base >::isReference(), parseFilesMultiThreading(), parseFilesSingleThreading(), writeDirTreeNode(), writeGroupTreeNode(), writeIncludeInfo(), writeSingleFileIndex(), and FileDefImpl::writeTagFile().
isReference() [2/2]
virtual bool Definition::isReference () const [pure virtual]
Returns TRUE if this definition is imported via a tag file.
Implemented in ClassDefImpl, ClassDefAliasImpl, ConceptDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, MemberDefImpl, MemberDefAliasImpl, ClassDefImpl, ClassDefAliasImpl, ConceptDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, MemberDefImpl, MemberDefAliasImpl, ClassDef, MemberDef, ClassDef, and MemberDef.
isVisible() [1/2]
virtual bool Definition::isVisible () const [pure virtual]
Returns TRUE iff the name may appear in the output
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by DefinitionAliasMixin< Base >::isVisible(), and writeGroupTreeNode().
isVisible() [2/2]
virtual bool Definition::isVisible () const [pure virtual]
Returns TRUE iff the name may appear in the output
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
isVisibleInProject() [1/2]
virtual bool Definition::isVisibleInProject () const [pure virtual]
Returns TRUE iff the name is part of this project and may appear in the output
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by DefinitionAliasMixin< Base >::isVisibleInProject().
isVisibleInProject() [2/2]
virtual bool Definition::isVisibleInProject () const [pure virtual]
Returns TRUE iff the name is part of this project and may appear in the output
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
localName() [1/2]
virtual QCString Definition::localName () const [pure virtual]
Returns the local name without any scope qualifiers.
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, NamespaceDefImpl, NamespaceDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDef, and NamespaceDef.
Referenced by MemberDefImpl::_computeIsConstructor(), ClassDefImpl::addInnerCompound(), NamespaceDefImpl::addInnerCompound(), addToIndices(), SymbolContext::Private::createScope(), getDefsOld(), NamespaceDefImpl::insertMember(), DefinitionAliasMixin< Base >::localName(), makeQualifiedNameWithTemplateParameters(), DefinitionAliasImpl::qualifiedName(), searchName(), searchTemplateSpecs(), NavPathElemContext::Private::text(), writeJavaScriptSearchIndex(), and VhdlDocGen::writeVHDLDeclaration().
localName() [2/2]
virtual QCString Definition::localName () const [pure virtual]
Returns the local name without any scope qualifiers.
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, NamespaceDefImpl, NamespaceDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, NamespaceDefImpl, NamespaceDefAliasImpl, NamespaceDef, and NamespaceDef.
name() [1/2]
virtual QCString Definition::name () const [pure virtual]
Returns the name of the definition
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, FileDefImpl, MemberDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, FileDefImpl, MemberDefAliasImpl, FileDef, and FileDef.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), DefinitionImpl::_writeSourceRefList(), DotClassGraph::addClass(), GroupDefImpl::addClass(), addClassMemberNameToIndex(), addClassToContext(), GroupDefImpl::addConcept(), addConceptToContext(), GroupDefImpl::addExample(), addFileMemberNameToIndex(), addGroupToGroups(), DotGfxHierarchyTable::addHierarchy(), DocSets::addIndexItem(), HtmlHelp::addIndexItem(), Qhp::addIndexItem(), PageDefImpl::addInnerCompound(), addInstance(), PerlModGenerator::addListOfAllMembers(), MemberDefImpl::addListReference(), addMemberDocs(), addMemberFunction(), addMemberToGroups(), addMemberToSearchIndex(), GroupDefImpl::addNamespace(), addNamespaceMemberNameToIndex(), addOverloaded(), GroupDefImpl::addPage(), addPageToContext(), addRelatedPage(), DefinitionImpl::addSourceReferencedBy(), DefinitionImpl::addSourceReferences(), addTemplateList(), addVariableToFile(), FlowChart::alignFuncProc(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), buildDirectories(), buildExampleList(), DotCallGraph::buildGraph(), buildNamespaceList(), DocParser::checkArgumentName(), checkOverrideArg(), classInformation(), classInheritedProtectionLevel(), cModule(), computeCommonDirPrefix(), computePageRelations(), computeTemplateClassRelations(), FlowChart::convertNameToFileName(), VhdlDocGen::correctMemberProperties(), MemberList::countEnumValues(), PageContext::Private::createExample(), MemberContext::Private::createInitializerAsCode(), ConceptContext::Private::createInitializerAsCode(), SymbolContext::Private::createScope(), MemberContext::Private::createSourceCode(), createTagLessInstance(), DefinitionContext< T >::DefinitionContext(), DotCallGraph::DotCallGraph(), DotGroupCollaboration::DotGroupCollaboration(), dumpSymbol(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), extractNamespaceName(), search.Finder::file(), VhdlDocGen::findArchitecture(), findClassRelation(), findDirDocumentation(), findEnumDocumentation(), findEnums(), findGlobalMember(), findGroupScope(), findMember(), VhdlDocGen::findMember(), findMemberLink(), findMemFlow(), findScopeFromQualifiedName(), findTemplateInstanceRelation(), findUsedClassesForClass(), findUsingDeclarations(), SymbolResolver::Private::followPath(), search.Finder::function(), functionSignature(), generateClassMemberLink(), generateClassOrGlobalLink(), generateConceptDocs(), generateDEFForClass(), generateDEFForMember(), generateDEFForNamespace(), generateDocsForClassList(), generateFuncLink(), generateNamespaceClassDocs(), generateNamespaceConceptDocs(), generateNamespaceDocs(), PerlModGenerator::generatePerlModForClass(), PerlModGenerator::generatePerlModForConcept(), PerlModGenerator::generatePerlModForGroup(), PerlModGenerator::generatePerlModForMember(), PerlModGenerator::generatePerlModForNamespace(), PerlModGenerator::generatePerlModForPage(), generateXMLForClass(), generateXMLForConcept(), generateXMLForDir(), generateXMLForGroup(), generateXMLForMember(), generateXMLForNamespace(), generateXMLForPage(), genericCompareMembers(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), getCanonicalTypeForIdentifier(), MemberDefImpl::getClassDefOfAnonymousType(), VhdlDocGen::getClassName(), getDefs(), getDefsOld(), getFortranDefs(), getLinkInScope(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), getResolvedConcept(), SymbolResolver::Private::getResolvedSymbolRec(), SymbolResolver::Private::getResolvedTypeRec(), DocPara::handleInheritDoc(), MemberContext::Private::handleNameWithContextFor(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), hasNonReferenceSuperClassRec(), if(), search.Finder::includees(), search.Finder::includers(), MemberDefImpl::IMPL::init(), FileDefImpl::insertClass(), NamespaceDefImpl::insertClass(), FileDefImpl::insertConcept(), NamespaceDefImpl::insertConcept(), GroupDefImpl::insertMember(), FileDefImpl::insertMember(), NamespaceDefImpl::insertMember(), FileDefImpl::insertNamespace(), NamespaceDefImpl::insertNamespace(), ClassDefImpl::internalInsertMember(), SymbolResolver::Private::isAccessibleFrom(), SymbolResolver::Private::isAccessibleFromWithExpScope(), ClassDefImpl::isBaseClass(), isStandardFunc(), ClassDefImpl::isSubClass(), VhdlDocGen::isSubClass(), DiagramItem::label(), XRefDummyCodeGenerator::linkableSymbol(), listSymbol(), lookupSymbol(), search.Finder::macro(), makeDisplayName(), search.Finder::members(), mergeCategories(), ClassDefImpl::mergeMembers(), minClassDistance(), MemberDefAliasImpl::name(), normalizeNonTemplateArgumentsInString(), MemberDefImpl::objCMethodName(), HtmlDocVisitor::operator()(), search.Finder::params(), CCodeParser::parseCode(), VHDLCodeParser::parseCode(), processTagLessClasses(), DefinitionImpl::qualifiedName(), MemberDefImpl::qualifiedName(), search.Finder::references(), referenceTo(), GroupDefImpl::removeMember(), resolveClassNestingRelations(), resolveLink(), ScopedTypeVariant::ScopedTypeVariant(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), setCallContextForVar(), SearchIndex::setCurrentDoc(), ScopedTypeVariant::setGlobal(), setParameterList(), FileDefImpl::sortMemberLists(), GroupDefImpl::sortMemberLists(), NamespaceDefImpl::sortMemberLists(), startCodeLine(), search.Finder::struct(), search.Finder::subClasses(), PageContext::Private::title(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), transferRelatedFunctionDocumentation(), trimBaseClassScope(), search.Finder::typedef(), validatingParseDoc(), search.Finder::variable(), MemberDefImpl::warnIfUndocumented(), writeClassToDot(), writeClassTree(), writeClassTreeToOutput(), writeColumn(), MemberDefImpl::writeDeclaration(), writeDefArgumentList(), ConceptDefImpl::writeDefinition(), writeDirTreeNode(), MemberDefImpl::writeDocumentation(), MemberList::writeDocumentationPage(), MemberDefImpl::writeEnumDeclaration(), writeExceptionListImpl(), writeGroupTreeNode(), ClassDefImpl::writeIncludeFilesForSlice(), writeJavaScriptSearchIndex(), writeLink(), writeListOfAllMembers(), MemberDefImpl::writeMemberDocSimple(), ClassDefImpl::writeMemberList(), writeMemberReference(), writeMemberToIndex(), writeObjCMethodCall(), VhdlDocGen::writeOverview(), writePages(), VhdlDocGen::writePlainVHDLDeclarations(), ClassDefImpl::writeQuickMemberLinks(), VhdlDocGen::writeRecordUnit(), VhdlDocGen::writeStringLink(), VhdlDocGen::writeTagFile(), ClassDefImpl::writeTagFile(), DocSets::writeToken(), writeUCFLink(), VhdlDocGen::writeVHDLDeclaration(), writeVhdlEntityToolTip(), and VhdlDocGen::writeVHDLTypeDocumentation().
name() [2/2]
virtual QCString Definition::name () const [pure virtual]
Returns the name of the definition
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, FileDefImpl, MemberDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, FileDefImpl, MemberDefAliasImpl, FileDef, and FileDef.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
navigationPathAsString() [1/2]
virtual QCString Definition::navigationPathAsString () const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by endFileWithNavPath(), DefinitionImpl::navigationPathAsString(), and DefinitionAliasMixin< Base >::navigationPathAsString().
navigationPathAsString() [2/2]
virtual QCString Definition::navigationPathAsString () const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
partOfGroups() [1/2]
virtual const GroupList & Definition::partOfGroups () const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by DotGroupCollaboration::addCollaborationMember(), NestingNodeContext::Private::addMembers(), DotGroupCollaboration::buildGraph(), DefinitionContext< T >::createPartOfGroups(), createTagLessInstance(), distributeClassGroupRelations(), distributeConceptGroups(), NestingNodeContext::Private::partOfGroup(), DefinitionAliasMixin< Base >::partOfGroups(), recursivelyAddGroupListToTitle(), writeClassTree(), ClassLinkedRefMap::writeDocumentation(), and writeNamespaceTreeElement().
partOfGroups() [2/2]
virtual const GroupList & Definition::partOfGroups () const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
pathFragment() [1/2]
virtual QCString Definition::pathFragment () const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by DefinitionImpl::pathFragment(), DefinitionAliasMixin< Base >::pathFragment(), and DirRelation::writeDocumentation().
pathFragment() [2/2]
virtual QCString Definition::pathFragment () const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
qualifiedName() [1/2]
virtual QCString Definition::qualifiedName () const [pure virtual]
Returns the fully qualified name of this definition
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, MemberDefImpl, MemberDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, MemberDefImpl, MemberDefAliasImpl, MemberDef, and MemberDef.
Referenced by DotGroupCollaboration::addCollaborationMember(), DocSets::addIndexItem(), FileDefImpl::addUsingDeclaration(), NamespaceDefImpl::addUsingDeclaration(), FileDefImpl::addUsingDirective(), NamespaceDefImpl::addUsingDirective(), SymbolContext::Private::createScope(), findGlobalMember(), getCanonicalTypeForIdentifier(), SymbolResolver::Private::getResolvedSymbol(), SymbolResolver::Private::getResolvedType(), makeQualifiedNameWithTemplateParameters(), SymbolResolver::Private::newResolveTypedef(), DefinitionImpl::qualifiedName(), DefinitionAliasImpl::qualifiedName(), resolveClassNestingRelations(), searchTemplateSpecs(), SearchIndex::setCurrentDoc(), SearchIndexExternal::setCurrentDoc(), writeJavaScriptSearchIndex(), and TooltipManager::writeTooltips().
qualifiedName() [2/2]
virtual QCString Definition::qualifiedName () const [pure virtual]
Returns the fully qualified name of this definition
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, MemberDefImpl, MemberDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, MemberDefImpl, MemberDefAliasImpl, MemberDef, and MemberDef.
symbolName() [1/2]
virtual QCString Definition::symbolName () const [pure virtual]
Returns the name of this definition as it appears in the symbol map.
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by VhdlDocGen::findMemberDef(), and DefinitionAliasMixin< Base >::symbolName().
symbolName() [2/2]
virtual QCString Definition::symbolName () const [pure virtual]
Returns the name of this definition as it appears in the symbol map.
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
toDefinitionImpl_() [1/2]
virtual const DefinitionImpl * Definition::toDefinitionImpl_ () const [private], [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by DefinitionImpl::mergeReferencedBy(), and DefinitionImpl::mergeReferences().
toDefinitionImpl_() [2/2]
virtual const DefinitionImpl * Definition::toDefinitionImpl_ () const [private], [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
toDefinitionMutable_() [1/2]
virtual DefinitionMutable * Definition::toDefinitionMutable_ () [private], [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by toDefinitionMutable().
toDefinitionMutable_() [2/2]
virtual DefinitionMutable * Definition::toDefinitionMutable_ () [private], [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
xrefListItems() [1/2]
virtual const RefItemVector & Definition::xrefListItems () const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Referenced by DefinitionImpl::mergeRefItems(), and DefinitionAliasMixin< Base >::xrefListItems().
xrefListItems() [2/2]
virtual const RefItemVector & Definition::xrefListItems () const [pure virtual]
Implemented in DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, DefinitionAliasMixin< NamespaceDef >, DefinitionMixin< ClassDefMutable >, DefinitionMixin< ConceptDefMutable >, DefinitionMixin< DirDef >, DefinitionMixin< FileDef >, DefinitionMixin< GroupDef >, DefinitionMixin< MemberDefMutable >, DefinitionMixin< NamespaceDefMutable >, DefinitionMixin< PageDef >, DefinitionAliasMixin< ClassDef >, DefinitionAliasMixin< ConceptDef >, DefinitionAliasMixin< MemberDef >, and DefinitionAliasMixin< NamespaceDef >.
Friends And Related Function Documentation
DefinitionImpl
DefinitionImpl [friend]
Definition at line 296 of file definition.h.
toDefinitionMutable [1/4]
DefinitionMutable * toDefinitionMutable (const Definition *) [friend]
Definition at line 1964 of file definition.cpp.
{
  return toDefinitionMutable(const_cast<Definition*>(d));
}
toDefinitionMutable [2/4]
DefinitionMutable * toDefinitionMutable (const Definition *) [friend]
Definition at line 1964 of file definition.cpp.
{
  return toDefinitionMutable(const_cast<Definition*>(d));
}
toDefinitionMutable [3/4]
DefinitionMutable * toDefinitionMutable (Definition *) [friend]
Definition at line 1958 of file definition.cpp.
{
  if (d==0) return 0;
  return d->toDefinitionMutable_();
}
Referenced by PageDefImpl::writeDocumentation().
toDefinitionMutable [4/4]
DefinitionMutable * toDefinitionMutable (Definition *) [friend]
Definition at line 1958 of file definition.cpp.
{
  if (d==0) return 0;
  return d->toDefinitionMutable_();
}
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/definition.h
doxygen/src/definition.h