FilterUpper Class Reference
The implementation of the `upper` filter.
Static Public Member Functions
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &)
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &)
Detailed Description
The implementation of the `upper` filter.
Definition at line 1507 of file template.cpp.
Member Function Documentation
apply() [1/2]
static TemplateVariant FilterUpper::apply (const TemplateVariant & v, const TemplateVariant &) [inline], [static]
Definition at line 1510 of file template.cpp.
    {
      if (v.isValid() && v.isString())
      {
        return v.toString().upper();
      }
      return v;
    }
References TemplateVariant::isString(), TemplateVariant::isValid(), TemplateVariant::toString(), and QCString::upper().
apply() [2/2]
static TemplateVariant FilterUpper::apply (const TemplateVariant & v, const TemplateVariant &) [inline], [static]
Definition at line 1510 of file template.cpp.
    {
      if (v.isValid() && v.isString())
      {
        return v.toString().upper();
      }
      return v;
    }
References TemplateVariant::isString(), TemplateVariant::isValid(), TemplateVariant::toString(), and QCString::upper().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp