SymbolMap< T > Class Template Reference
#include <symbolmap.h>
Public Types
using Ptr = T *
using VectorPtr = std::vector< Ptr >
using Map = std::unordered_map< std::string, VectorPtr >
using iterator = typename Map::iterator
using const_iterator = typename Map::const_iterator
using Ptr = T *
using VectorPtr = std::vector< Ptr >
using Map = std::unordered_map< std::string, VectorPtr >
using iterator = typename Map::iterator
using const_iterator = typename Map::const_iterator
Public Member Functions
void add (const QCString &name, Ptr def)
Add a symbol def into the map under key name.
void remove (const QCString &name, Ptr def)
Remove a symbol def from the map that was stored under key name.
const VectorPtr & find (const QCString &name) const
VectorPtr & find (const QCString &name)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
bool empty () const
void add (const QCString &name, Ptr def)
Add a symbol def into the map under key name.
void remove (const QCString &name, Ptr def)
Remove a symbol def from the map that was stored under key name.
const VectorPtr & find (const QCString &name) const
VectorPtr & find (const QCString &name)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
bool empty () const
Private Attributes
Map m_map
VectorPtr m_noMatch
Detailed Description
template<class T>
class SymbolMap< T >
Class implementing a symbol map that maps symbol names to objects. Symbol names do not have to be unique. Supports adding symbols with add(), removing symbols with remove(), and finding symbols with find().
Definition at line 30 of file symbolmap.h.
Member Typedef Documentation
const_iterator [1/2]
template<class T >
using SymbolMap< T >::const_iterator = typename Map::const_iterator
Definition at line 37 of file symbolmap.h.
const_iterator [2/2]
template<class T >
using SymbolMap< T >::const_iterator = typename Map::const_iterator
Definition at line 37 of file symbolmap.h.
iterator [1/2]
template<class T >
using SymbolMap< T >::iterator = typename Map::iterator
Definition at line 36 of file symbolmap.h.
iterator [2/2]
template<class T >
using SymbolMap< T >::iterator = typename Map::iterator
Definition at line 36 of file symbolmap.h.
Map [1/2]
template<class T >
using SymbolMap< T >::Map = std::unordered_map<std::string,VectorPtr>
Definition at line 35 of file symbolmap.h.
Map [2/2]
template<class T >
using SymbolMap< T >::Map = std::unordered_map<std::string,VectorPtr>
Definition at line 35 of file symbolmap.h.
Ptr [1/2]
template<class T >
using SymbolMap< T >::Ptr = T *
Definition at line 33 of file symbolmap.h.
Ptr [2/2]
template<class T >
using SymbolMap< T >::Ptr = T *
Definition at line 33 of file symbolmap.h.
VectorPtr [1/2]
template<class T >
using SymbolMap< T >::VectorPtr = std::vector<Ptr>
Definition at line 34 of file symbolmap.h.
VectorPtr [2/2]
template<class T >
using SymbolMap< T >::VectorPtr = std::vector<Ptr>
Definition at line 34 of file symbolmap.h.
Member Function Documentation
add() [1/2]
template<class T >
void SymbolMap< T >::add (const QCString & name, Ptr def) [inline]
Add a symbol def into the map under key name.
Definition at line 40 of file symbolmap.h.
    {
      auto it = m_map.find(name.str());
      if (it!=m_map.end())
      {
        it->second.push_back(def);
      }
      else
      {
        m_map.emplace(std::make_pair(name.str(),VectorPtr({def})));
      }
    }
References SymbolMap< T >::m_map, and setup::name.
Referenced by doxmlparser.compound.memberdefType::__init__(), addToMap(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
add() [2/2]
template<class T >
void SymbolMap< T >::add (const QCString & name, Ptr def) [inline]
Add a symbol def into the map under key name.
Definition at line 40 of file symbolmap.h.
    {
      auto it = m_map.find(name.str());
      if (it!=m_map.end())
      {
        it->second.push_back(def);
      }
      else
      {
        m_map.emplace(std::make_pair(name.str(),VectorPtr({def})));
      }
    }
References SymbolMap< T >::m_map, and setup::name.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_add(), and doxmlparser.compound.memberdefType::set_add().
begin() [1/4]
template<class T >
iterator SymbolMap< T >::begin () [inline]
Definition at line 84 of file symbolmap.h.
{ return m_map.begin(); }
References SymbolMap< T >::m_map.
begin() [2/4]
template<class T >
iterator SymbolMap< T >::begin () [inline]
Definition at line 84 of file symbolmap.h.
{ return m_map.begin(); }
References SymbolMap< T >::m_map.
begin() [3/4]
template<class T >
const_iterator SymbolMap< T >::begin () const [inline]
Definition at line 86 of file symbolmap.h.
{ return m_map.cbegin(); }
References SymbolMap< T >::m_map.
begin() [4/4]
template<class T >
const_iterator SymbolMap< T >::begin () const [inline]
Definition at line 86 of file symbolmap.h.
{ return m_map.cbegin(); }
References SymbolMap< T >::m_map.
empty() [1/2]
template<class T >
bool SymbolMap< T >::empty () const [inline]
Definition at line 88 of file symbolmap.h.
{ return m_map.empty(); }
References SymbolMap< T >::m_map.
empty() [2/2]
template<class T >
bool SymbolMap< T >::empty () const [inline]
Definition at line 88 of file symbolmap.h.
{ return m_map.empty(); }
References SymbolMap< T >::m_map.
end() [1/4]
template<class T >
iterator SymbolMap< T >::end () [inline]
Definition at line 85 of file symbolmap.h.
{ return m_map.end(); }
References SymbolMap< T >::m_map.
end() [2/4]
template<class T >
iterator SymbolMap< T >::end () [inline]
Definition at line 85 of file symbolmap.h.
{ return m_map.end(); }
References SymbolMap< T >::m_map.
end() [3/4]
template<class T >
const_iterator SymbolMap< T >::end () const [inline]
Definition at line 87 of file symbolmap.h.
{ return m_map.cend(); }
References SymbolMap< T >::m_map.
end() [4/4]
template<class T >
const_iterator SymbolMap< T >::end () const [inline]
Definition at line 87 of file symbolmap.h.
{ return m_map.cend(); }
References SymbolMap< T >::m_map.
find() [1/4]
template<class T >
VectorPtr & SymbolMap< T >::find (const QCString & name) [inline]
Find the list of symbols stored under key name Returns a pair of iterators pointing to the start and end of the range of matching symbols
Definition at line 78 of file symbolmap.h.
    {
      auto it = m_map.find(name.str());
      return it==m_map.end() ? m_noMatch : it->second;
    }
References SymbolMap< T >::m_map, SymbolMap< T >::m_noMatch, and setup::name.
find() [2/4]
template<class T >
VectorPtr & SymbolMap< T >::find (const QCString & name) [inline]
Find the list of symbols stored under key name Returns a pair of iterators pointing to the start and end of the range of matching symbols
Definition at line 78 of file symbolmap.h.
    {
      auto it = m_map.find(name.str());
      return it==m_map.end() ? m_noMatch : it->second;
    }
References SymbolMap< T >::m_map, SymbolMap< T >::m_noMatch, and setup::name.
find() [3/4]
template<class T >
const VectorPtr & SymbolMap< T >::find (const QCString & name) const [inline]
Find the list of symbols stored under key name Returns a pair of iterators pointing to the start and end of the range of matching symbols
Definition at line 70 of file symbolmap.h.
    {
      auto it = m_map.find(name.str());
      return it==m_map.end() ? m_noMatch : it->second;
    }
References SymbolMap< T >::m_map, SymbolMap< T >::m_noMatch, and setup::name.
Referenced by findMemberLink(), SymbolResolver::Private::followPath(), getMemberFromSymbol(), SymbolResolver::Private::getResolvedSymbolRec(), SymbolResolver::Private::getResolvedTypeRec(), lookupSymbols(), SymbolMap< T >::remove(), and SymbolResolver::Private::substTypedef().
find() [4/4]
template<class T >
const VectorPtr & SymbolMap< T >::find (const QCString & name) const [inline]
Find the list of symbols stored under key name Returns a pair of iterators pointing to the start and end of the range of matching symbols
Definition at line 70 of file symbolmap.h.
    {
      auto it = m_map.find(name.str());
      return it==m_map.end() ? m_noMatch : it->second;
    }
References SymbolMap< T >::m_map, SymbolMap< T >::m_noMatch, and setup::name.
remove() [1/2]
template<class T >
void SymbolMap< T >::remove (const QCString & name, Ptr def) [inline]
Remove a symbol def from the map that was stored under key name.
Definition at line 54 of file symbolmap.h.
    {
      VectorPtr &v = find(name);
      auto it = std::find(v.begin(),v.end(),def);
      if (it!=v.end())
      {
        v.erase(it);
        if (v.empty())
        {
          m_map.erase(name.str());
        }
      }
    }
References SymbolMap< T >::find(), SymbolMap< T >::m_map, and setup::name.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_remove(), removeFromMap(), and doxmlparser.compound.memberdefType::set_remove().
remove() [2/2]
template<class T >
void SymbolMap< T >::remove (const QCString & name, Ptr def) [inline]
Remove a symbol def from the map that was stored under key name.
Definition at line 54 of file symbolmap.h.
    {
      VectorPtr &v = find(name);
      auto it = std::find(v.begin(),v.end(),def);
      if (it!=v.end())
      {
        v.erase(it);
        if (v.empty())
        {
          m_map.erase(name.str());
        }
      }
    }
References SymbolMap< T >::find(), SymbolMap< T >::m_map, and setup::name.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.memberdefType::get_remove(), and doxmlparser.compound.memberdefType::set_remove().
Member Data Documentation
m_map
template<class T >
Map SymbolMap< T >::m_map [private]
Definition at line 91 of file symbolmap.h.
Referenced by SymbolMap< T >::add(), SymbolMap< T >::begin(), SymbolMap< T >::empty(), SymbolMap< T >::end(), SymbolMap< T >::find(), and SymbolMap< T >::remove().
m_noMatch
template<class T >
VectorPtr SymbolMap< T >::m_noMatch [private]
Definition at line 92 of file symbolmap.h.
Referenced by SymbolMap< T >::find().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/symbolmap.h
doxygen/src/symbolmap.h