ExprAstBinary Class Reference
Class representing a binary operator in the AST.
Public Member Functions
ExprAstBinary (Operator::Type op, ExprAstPtr &&lhs, ExprAstPtr &&rhs)
virtual TemplateVariant resolve (TemplateContext *c)
ExprAstBinary (Operator::Type op, ExprAstPtr &&lhs, ExprAstPtr &&rhs)
virtual TemplateVariant resolve (TemplateContext *c)
Private Attributes
Operator::Type m_operator = Operator::Or
ExprAstPtr m_lhs
ExprAstPtr m_rhs
Detailed Description
Class representing a binary operator in the AST.
Definition at line 1823 of file template.cpp.
Constructor & Destructor Documentation
ExprAstBinary() [1/2]
ExprAstBinary::ExprAstBinary (Operator::Type op, ExprAstPtr && lhs, ExprAstPtr && rhs) [inline]
Definition at line 1826 of file template.cpp.
      : m_operator(op), m_lhs(std::move(lhs)), m_rhs(std::move(rhs))
    { TRACE(("ExprAstBinary %s\n",Operator::toString(op))); }
References Operator::toString(), and TRACE.
ExprAstBinary() [2/2]
ExprAstBinary::ExprAstBinary (Operator::Type op, ExprAstPtr && lhs, ExprAstPtr && rhs) [inline]
Definition at line 1826 of file template.cpp.
      : m_operator(op), m_lhs(std::move(lhs)), m_rhs(std::move(rhs))
    { TRACE(("ExprAstBinary %s\n",Operator::toString(op))); }
References Operator::toString(), and TRACE.
Member Function Documentation
resolve() [1/2]
virtual TemplateVariant ExprAstBinary::resolve (TemplateContext * c) [inline], [virtual]
Reimplemented from ExprAst.
Definition at line 1829 of file template.cpp.
    {
      TemplateContextImpl *ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return TemplateVariant(); // should not happen
      TemplateVariant lhs = m_lhs->resolve(c);
      TemplateVariant rhs = m_rhs ? m_rhs->resolve(c) : TemplateVariant();
      switch(m_operator)
      {
        case Operator::Or:
          return TemplateVariant(lhs.toBool() || rhs.toBool());
        case Operator::And:
          return TemplateVariant(lhs.toBool() && rhs.toBool());
        case Operator::Equal:
          return TemplateVariant(lhs == rhs);
        case Operator::NotEqual:
          return TemplateVariant(!(lhs == rhs));
        case Operator::Less:
          if (lhs.isString() && rhs.isString())
          {
            return lhs.toString()<rhs.toString();
          }
          else
          {
            return lhs.toInt()<rhs.toInt();
          }
        case Operator::Greater:
          if (lhs.isString() && rhs.isString())
          {
            return !(lhs.toString()<rhs.toString());
          }
          else
          {
            return lhs.toInt()>rhs.toInt();
          }
        case Operator::LessEqual:
          if (lhs.isString() && rhs.isString())
          {
            return lhs.toString()==rhs.toString() || lhs.toString()<rhs.toString();
          }
          else
          {
            return lhs.toInt()<=rhs.toInt();
          }
        case Operator::GreaterEqual:
          if (lhs.isString() && rhs.isString())
          {
            return lhs.toString()==rhs.toString() || !(lhs.toString()<rhs.toString());
          }
          else
          {
            return lhs.toInt()>=rhs.toInt();
          }
        case Operator::Plus:
          {
            return TemplateVariant(lhs.toInt() + rhs.toInt());
          }
        case Operator::Minus:
          {
            return TemplateVariant(lhs.toInt() - rhs.toInt());
          }
        case Operator::Multiply:
          {
            return TemplateVariant(lhs.toInt() * rhs.toInt());
          }
        case Operator::Divide:
          {
            int denom = rhs.toInt();
            if (denom!=0)
            {
              return TemplateVariant(lhs.toInt() / denom);
            }
            else // divide by zero
            {
              ci->warn(ci->templateName(),ci->line(),"division by zero while evaluating expression is undefined");
              return 0;
            }
          }
        case Operator::Modulo:
          {
            int denom = rhs.toInt();
            if (denom!=0)
            {
              return TemplateVariant(lhs.toInt() % denom);
            }
            else // module zero
            {
              ci->warn(ci->templateName(),ci->line(),"modulo zero while evaluating expression is undefined");
              return 0;
            }
          }
        default:
          return TemplateVariant();
      }
    }
References Operator::And, c, Operator::Divide, Operator::Equal, Operator::Greater, Operator::GreaterEqual, TemplateVariant::isString(), Operator::Less, Operator::LessEqual, TemplateContextImpl::line(), m_lhs, m_operator, m_rhs, Operator::Minus, Operator::Modulo, Operator::Multiply, Operator::NotEqual, Operator::Or, Operator::Plus, TemplateContextImpl::templateName(), TemplateVariant::toBool(), TemplateVariant::toInt(), TemplateVariant::toString(), and TemplateContextImpl::warn().
resolve() [2/2]
virtual TemplateVariant ExprAstBinary::resolve (TemplateContext * c) [inline], [virtual]
Reimplemented from ExprAst.
Definition at line 1829 of file template.cpp.
    {
      TemplateContextImpl *ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return TemplateVariant(); // should not happen
      TemplateVariant lhs = m_lhs->resolve(c);
      TemplateVariant rhs = m_rhs ? m_rhs->resolve(c) : TemplateVariant();
      switch(m_operator)
      {
        case Operator::Or:
          return TemplateVariant(lhs.toBool() || rhs.toBool());
        case Operator::And:
          return TemplateVariant(lhs.toBool() && rhs.toBool());
        case Operator::Equal:
          return TemplateVariant(lhs == rhs);
        case Operator::NotEqual:
          return TemplateVariant(!(lhs == rhs));
        case Operator::Less:
          if (lhs.isString() && rhs.isString())
          {
            return lhs.toString()<rhs.toString();
          }
          else
          {
            return lhs.toInt()<rhs.toInt();
          }
        case Operator::Greater:
          if (lhs.isString() && rhs.isString())
          {
            return !(lhs.toString()<rhs.toString());
          }
          else
          {
            return lhs.toInt()>rhs.toInt();
          }
        case Operator::LessEqual:
          if (lhs.isString() && rhs.isString())
          {
            return lhs.toString()==rhs.toString() || lhs.toString()<rhs.toString();
          }
          else
          {
            return lhs.toInt()<=rhs.toInt();
          }
        case Operator::GreaterEqual:
          if (lhs.isString() && rhs.isString())
          {
            return lhs.toString()==rhs.toString() || !(lhs.toString()<rhs.toString());
          }
          else
          {
            return lhs.toInt()>=rhs.toInt();
          }
        case Operator::Plus:
          {
            return TemplateVariant(lhs.toInt() + rhs.toInt());
          }
        case Operator::Minus:
          {
            return TemplateVariant(lhs.toInt() - rhs.toInt());
          }
        case Operator::Multiply:
          {
            return TemplateVariant(lhs.toInt() * rhs.toInt());
          }
        case Operator::Divide:
          {
            int denom = rhs.toInt();
            if (denom!=0)
            {
              return TemplateVariant(lhs.toInt() / denom);
            }
            else // divide by zero
            {
              ci->warn(ci->templateName(),ci->line(),"division by zero while evaluating expression is undefined");
              return 0;
            }
          }
        case Operator::Modulo:
          {
            int denom = rhs.toInt();
            if (denom!=0)
            {
              return TemplateVariant(lhs.toInt() % denom);
            }
            else // module zero
            {
              ci->warn(ci->templateName(),ci->line(),"modulo zero while evaluating expression is undefined");
              return 0;
            }
          }
        default:
          return TemplateVariant();
      }
    }
References Operator::And, c, Operator::Divide, Operator::Equal, Operator::Greater, Operator::GreaterEqual, TemplateVariant::isString(), Operator::Less, Operator::LessEqual, TemplateContextImpl::line(), Operator::Minus, Operator::Modulo, Operator::Multiply, Operator::NotEqual, Operator::Or, Operator::Plus, TemplateContextImpl::templateName(), TemplateVariant::toBool(), TemplateVariant::toInt(), TemplateVariant::toString(), and TemplateContextImpl::warn().
Member Data Documentation
m_lhs
ExprAstPtr ExprAstBinary::m_lhs [private]
Definition at line 1925 of file template.cpp.
Referenced by resolve().
m_operator
Operator::Type ExprAstBinary::m_operator = Operator::Or [private]
Definition at line 1924 of file template.cpp.
Referenced by resolve().
m_rhs
ExprAstPtr ExprAstBinary::m_rhs [private]
Definition at line 1926 of file template.cpp.
Referenced by resolve().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp