IncludeInfoListContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
IncludeInfoListContext (const IncludeInfoList &list, SrcLangExt lang)
virtual ~IncludeInfoListContext ()
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
IncludeInfoListContext (const IncludeInfoList &list, SrcLangExt lang)
virtual ~IncludeInfoListContext ()
Static Public Member Functions
static TemplateListIntfPtr alloc (const IncludeInfoList &list, SrcLangExt lang)
static TemplateListIntfPtr alloc (const IncludeInfoList &list, SrcLangExt lang)
Private Attributes
std::unique_ptr< Private > p
Additional Inherited Members
Detailed Description
Definition at line 175 of file context.h.
Constructor & Destructor Documentation
IncludeInfoListContext() [1/2]
IncludeInfoListContext::IncludeInfoListContext (const IncludeInfoList & list, SrcLangExt lang)
Definition at line 1688 of file context.cpp.
                                                                                          : p(std::make_unique<Private>(list,lang))
{
}
 IncludeInfoListContext() [1/2]
IncludeInfoListContext::~IncludeInfoListContext () [virtual]
Definition at line 1692 of file context.cpp.
{
}
IncludeInfoListContext() [2/2]
IncludeInfoListContext::IncludeInfoListContext (const IncludeInfoList & list, SrcLangExt lang)
 IncludeInfoListContext() [2/2]
virtual IncludeInfoListContext::~IncludeInfoListContext () [virtual]
Member Function Documentation
alloc() [1/2]
static TemplateListIntfPtr IncludeInfoListContext::alloc (const IncludeInfoList & list, SrcLangExt lang) [inline], [static]
Definition at line 178 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<IncludeInfoListContext>(list,lang)); }
Referenced by FileContext::Private::createIncludeList().
alloc() [2/2]
static TemplateListIntfPtr IncludeInfoListContext::alloc (const IncludeInfoList & list, SrcLangExt lang) [inline], [static]
Definition at line 178 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<IncludeInfoListContext>(list,lang)); }
at() [1/2]
TemplateVariant IncludeInfoListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 1702 of file context.cpp.
{
  return p->at(index);
}
References p.
at() [2/2]
virtual TemplateVariant IncludeInfoListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
count() [1/2]
size_t IncludeInfoListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Definition at line 1697 of file context.cpp.
{
  return p->count();
}
References p.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
count() [2/2]
virtual size_t IncludeInfoListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
createIterator() [1/2]
TemplateListIntf::ConstIteratorPtr IncludeInfoListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 1707 of file context.cpp.
{
  return p->createIterator();
}
References p.
createIterator() [2/2]
virtual TemplateListIntf::ConstIteratorPtr IncludeInfoListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Member Data Documentation
p
std::unique_ptr< Private > IncludeInfoListContext::p [private]
Definition at line 191 of file context.h.
Referenced by at(), count(), and createIterator().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.h
doxygen/src/context.h
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp