GroupDef Class Reference
#include <groupdef.h>
Public Member Functions
virtual DefType definitionType () const =0
virtual QCString getOutputFileBase () const =0
virtual QCString anchor () const =0
virtual QCString displayName (bool=TRUE) const =0
virtual QCString groupTitle () const =0
virtual void setGroupTitle (const QCString &newtitle)=0
virtual bool hasGroupTitle () const =0
virtual void addFile (const FileDef *def)=0
virtual bool addClass (const ClassDef *def)=0
virtual bool addConcept (const ConceptDef *def)=0
virtual bool addNamespace (const NamespaceDef *def)=0
virtual void addGroup (const GroupDef *def)=0
virtual void addPage (const PageDef *def)=0
virtual void addExample (const PageDef *def)=0
virtual void addDir (DirDef *dd)=0
virtual bool insertMember (const MemberDef *def, bool docOnly=FALSE)=0
virtual void removeMember (MemberDef *md)=0
virtual bool findGroup (const GroupDef *def) const =0
virtual void writeDocumentation (OutputList &ol)=0
virtual void writeMemberPages (OutputList &ol)=0
virtual void writeQuickMemberLinks (OutputList &ol, const MemberDef *currentMd) const =0
virtual void writeTagFile (TextStream &)=0
virtual size_t numDocMembers () const =0
virtual bool isLinkableInProject () const =0
virtual bool isLinkable () const =0
virtual bool isASubGroup () const =0
virtual void computeAnchors ()=0
virtual void countMembers ()=0
virtual void addMembersToMemberGroup ()=0
virtual void distributeMemberGroupDocumentation ()=0
virtual void findSectionsInDocumentation ()=0
virtual void addListReferences ()=0
virtual void sortMemberLists ()=0
virtual bool subGrouping () const =0
virtual void setGroupScope (Definition *d)=0
virtual Definition * getGroupScope () const =0
virtual MemberList * getMemberList (MemberListType lt) const =0
virtual const MemberLists & getMemberLists () const =0
virtual const MemberGroupList & getMemberGroups () const =0
virtual const FileList & getFiles () const =0
virtual const ClassLinkedRefMap & getClasses () const =0
virtual const ConceptLinkedRefMap & getConcepts () const =0
virtual const NamespaceLinkedRefMap & getNamespaces () const =0
virtual const GroupList & getSubGroups () const =0
virtual const PageLinkedRefMap & getPages () const =0
virtual const DirList & getDirs () const =0
virtual const PageLinkedRefMap & getExamples () const =0
virtual bool hasDetailedDescription () const =0
virtual void sortSubGroups ()=0
virtual DefType definitionType () const =0
virtual QCString getOutputFileBase () const =0
virtual QCString anchor () const =0
virtual QCString displayName (bool=TRUE) const =0
virtual QCString groupTitle () const =0
virtual void setGroupTitle (const QCString &newtitle)=0
virtual bool hasGroupTitle () const =0
virtual void addFile (const FileDef *def)=0
virtual bool addClass (const ClassDef *def)=0
virtual bool addConcept (const ConceptDef *def)=0
virtual bool addNamespace (const NamespaceDef *def)=0
virtual void addGroup (const GroupDef *def)=0
virtual void addPage (const PageDef *def)=0
virtual void addExample (const PageDef *def)=0
virtual void addDir (DirDef *dd)=0
virtual bool insertMember (const MemberDef *def, bool docOnly=FALSE)=0
virtual void removeMember (MemberDef *md)=0
virtual bool findGroup (const GroupDef *def) const =0
virtual void writeDocumentation (OutputList &ol)=0
virtual void writeMemberPages (OutputList &ol)=0
virtual void writeQuickMemberLinks (OutputList &ol, const MemberDef *currentMd) const =0
virtual void writeTagFile (TextStream &)=0
virtual size_t numDocMembers () const =0
virtual bool isLinkableInProject () const =0
virtual bool isLinkable () const =0
virtual bool isASubGroup () const =0
virtual void computeAnchors ()=0
virtual void countMembers ()=0
virtual void addMembersToMemberGroup ()=0
virtual void distributeMemberGroupDocumentation ()=0
virtual void findSectionsInDocumentation ()=0
virtual void addListReferences ()=0
virtual void sortMemberLists ()=0
virtual bool subGrouping () const =0
virtual void setGroupScope (Definition *d)=0
virtual Definition * getGroupScope () const =0
virtual MemberList * getMemberList (MemberListType lt) const =0
virtual const MemberLists & getMemberLists () const =0
virtual const MemberGroupList & getMemberGroups () const =0
virtual const FileList & getFiles () const =0
virtual const ClassLinkedRefMap & getClasses () const =0
virtual const ConceptLinkedRefMap & getConcepts () const =0
virtual const NamespaceLinkedRefMap & getNamespaces () const =0
virtual const GroupList & getSubGroups () const =0
virtual const PageLinkedRefMap & getPages () const =0
virtual const DirList & getDirs () const =0
virtual const PageLinkedRefMap & getExamples () const =0
virtual bool hasDetailedDescription () const =0
virtual void sortSubGroups ()=0
Additional Inherited Members
Detailed Description
A model of a group of symbols.
Definition at line 49 of file groupdef.h.
Member Function Documentation
addClass() [1/2]
virtual bool GroupDef::addClass (const ClassDef * def) [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by addClassToGroups(), and ClassDefImpl::setGroupDefForAllMembers().
addClass() [2/2]
virtual bool GroupDef::addClass (const ClassDef * def) [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
addConcept() [1/2]
virtual bool GroupDef::addConcept (const ConceptDef * def) [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by addConceptToGroups().
addConcept() [2/2]
virtual bool GroupDef::addConcept (const ConceptDef * def) [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
addDir() [1/2]
virtual void GroupDef::addDir (DirDef * dd) [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by addDirToGroups().
addDir() [2/2]
virtual void GroupDef::addDir (DirDef * dd) [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
addExample() [1/2]
virtual void GroupDef::addExample (const PageDef * def) [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by addExampleToGroups().
addExample() [2/2]
virtual void GroupDef::addExample (const PageDef * def) [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
addFile() [1/2]
virtual void GroupDef::addFile (const FileDef * def) [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by buildFileList().
addFile() [2/2]
virtual void GroupDef::addFile (const FileDef * def) [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
addGroup() [1/2]
virtual void GroupDef::addGroup (const GroupDef * def) [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by addGroupToGroups().
addGroup() [2/2]
virtual void GroupDef::addGroup (const GroupDef * def) [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
addListReferences() [1/2]
virtual void GroupDef::addListReferences () [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by addListReferences().
addListReferences() [2/2]
virtual void GroupDef::addListReferences () [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
addMembersToMemberGroup() [1/2]
virtual void GroupDef::addMembersToMemberGroup () [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by addMembersToMemberGroup().
addMembersToMemberGroup() [2/2]
virtual void GroupDef::addMembersToMemberGroup () [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
addNamespace() [1/2]
virtual bool GroupDef::addNamespace (const NamespaceDef * def) [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by addNamespaceToGroups(), and findUsingDirectives().
addNamespace() [2/2]
virtual bool GroupDef::addNamespace (const NamespaceDef * def) [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
addPage() [1/2]
virtual void GroupDef::addPage (const PageDef * def) [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by addRelatedPage().
addPage() [2/2]
virtual void GroupDef::addPage (const PageDef * def) [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
anchor() [1/2]
virtual QCString GroupDef::anchor () const [pure virtual]
Returns the anchor within a page where this item can be found
Implements Definition.
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), addToIndices(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
anchor() [2/2]
virtual QCString GroupDef::anchor () const [pure virtual]
Returns the anchor within a page where this item can be found
Implements Definition.
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
computeAnchors() [1/2]
virtual void GroupDef::computeAnchors () [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by computeMemberReferences().
computeAnchors() [2/2]
virtual void GroupDef::computeAnchors () [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
countMembers() [1/2]
virtual void GroupDef::countMembers () [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by countMembers().
countMembers() [2/2]
virtual void GroupDef::countMembers () [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
definitionType() [1/2]
virtual DefType GroupDef::definitionType () const [pure virtual]
Use this for dynamic inspection of the type of the derived class
Implements Definition.
Implemented in GroupDefImpl, and GroupDefImpl.
definitionType() [2/2]
virtual DefType GroupDef::definitionType () const [pure virtual]
Use this for dynamic inspection of the type of the derived class
Implements Definition.
Implemented in GroupDefImpl, and GroupDefImpl.
displayName() [1/2]
virtual QCString GroupDef::displayName (bool includeScope = TRUE) const [pure virtual]
Returns the name of the definition as it appears in the output
Implements Definition.
Implemented in GroupDefImpl, and GroupDefImpl.
displayName() [2/2]
virtual QCString GroupDef::displayName (bool includeScope = TRUE) const [pure virtual]
Returns the name of the definition as it appears in the output
Implements Definition.
Implemented in GroupDefImpl, and GroupDefImpl.
distributeMemberGroupDocumentation() [1/2]
virtual void GroupDef::distributeMemberGroupDocumentation () [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by distributeMemberGroupDocumentation().
distributeMemberGroupDocumentation() [2/2]
virtual void GroupDef::distributeMemberGroupDocumentation () [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
findGroup() [1/2]
virtual bool GroupDef::findGroup (const GroupDef * def) const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by addGroupToGroups().
findGroup() [2/2]
virtual bool GroupDef::findGroup (const GroupDef * def) const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
findSectionsInDocumentation() [1/2]
virtual void GroupDef::findSectionsInDocumentation () [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by findSectionsInDocumentation().
findSectionsInDocumentation() [2/2]
virtual void GroupDef::findSectionsInDocumentation () [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
getClasses() [1/2]
virtual const ClassLinkedRefMap & GroupDef::getClasses () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by NestingNodeContext::Private::addClasses(), DotGroupCollaboration::buildGraph(), ModuleContext::Private::createClasses(), ModuleContext::Private::createInlineClasses(), PerlModGenerator::generatePerlModForGroup(), generateXMLForGroup(), and writeGroupTreeNode().
getClasses() [2/2]
virtual const ClassLinkedRefMap & GroupDef::getClasses () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
getConcepts() [1/2]
virtual const ConceptLinkedRefMap & GroupDef::getConcepts () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by NestingNodeContext::Private::addConcepts(), NestingNodeContext::Private::addNamespaces(), generateXMLForGroup(), and writeGroupTreeNode().
getConcepts() [2/2]
virtual const ConceptLinkedRefMap & GroupDef::getConcepts () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
getDirs() [1/2]
virtual const DirList & GroupDef::getDirs () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by NestingNodeContext::Private::addDirFiles(), DotGroupCollaboration::buildGraph(), ModuleContext::Private::createDirs(), and writeGroupTreeNode().
getDirs() [2/2]
virtual const DirList & GroupDef::getDirs () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
getExamples() [1/2]
virtual const PageLinkedRefMap & GroupDef::getExamples () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by ModuleContext::Private::createExamples().
getExamples() [2/2]
virtual const PageLinkedRefMap & GroupDef::getExamples () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
getFiles() [1/2]
virtual const FileList & GroupDef::getFiles () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by DotGroupCollaboration::buildGraph(), ModuleContext::Private::createFiles(), PerlModGenerator::generatePerlModForGroup(), generateXMLForGroup(), and writeGroupTreeNode().
getFiles() [2/2]
virtual const FileList & GroupDef::getFiles () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
getGroupScope() [1/2]
virtual Definition * GroupDef::getGroupScope () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
getGroupScope() [2/2]
virtual Definition * GroupDef::getGroupScope () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
getMemberGroups() [1/2]
virtual const MemberGroupList & GroupDef::getMemberGroups () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by ModuleContext::Private::createMemberGroups(), PerlModGenerator::generatePerlModForGroup(), and generateXMLForGroup().
getMemberGroups() [2/2]
virtual const MemberGroupList & GroupDef::getMemberGroups () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
getMemberList() [1/2]
virtual MemberList * GroupDef::getMemberList (MemberListType lt) const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by NestingNodeContext::Private::addMembers(), DotGroupCollaboration::buildGraph(), ModuleContext::Private::createMemberList(), PerlModGenerator::generatePerlModForGroup(), and writeGroupTreeNode().
getMemberList() [2/2]
virtual MemberList * GroupDef::getMemberList (MemberListType lt) const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
getMemberLists() [1/2]
virtual const MemberLists & GroupDef::getMemberLists () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by generateXMLForGroup(), and writeGroupTreeNode().
getMemberLists() [2/2]
virtual const MemberLists & GroupDef::getMemberLists () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
getNamespaces() [1/2]
virtual const NamespaceLinkedRefMap & GroupDef::getNamespaces () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by DotGroupCollaboration::buildGraph(), ModuleContext::Private::createConstantgroups(), ModuleContext::Private::createNamespaces(), PerlModGenerator::generatePerlModForGroup(), generateXMLForGroup(), and writeGroupTreeNode().
getNamespaces() [2/2]
virtual const NamespaceLinkedRefMap & GroupDef::getNamespaces () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
getOutputFileBase() [1/2]
virtual QCString GroupDef::getOutputFileBase () const [pure virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements Definition.
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by addRelatedPage(), DotGroupCollaboration::DotGroupCollaboration(), generateXMLForGroup(), generateXMLForMember(), MemberDefImpl::getOutputFileBase(), PageDefImpl::getOutputFileBase(), ModuleContext::Private::groupGraph(), resolveUserReferences(), writeGroupTreeNode(), and MemberDefImpl::writeLink().
getOutputFileBase() [2/2]
virtual QCString GroupDef::getOutputFileBase () const [pure virtual]
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements Definition.
Implemented in GroupDefImpl, and GroupDefImpl.
getPages() [1/2]
virtual const PageLinkedRefMap & GroupDef::getPages () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by NestingNodeContext::Private::addPages(), DotGroupCollaboration::buildGraph(), ModuleContext::Private::createPages(), PerlModGenerator::generatePerlModForGroup(), generateXMLForGroup(), and writeGroupTreeNode().
getPages() [2/2]
virtual const PageLinkedRefMap & GroupDef::getPages () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
getSubGroups() [1/2]
virtual const GroupList & GroupDef::getSubGroups () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by NestingNodeContext::Private::addModules(), DotGroupCollaboration::buildGraph(), ModuleContext::Private::createModules(), PerlModGenerator::generatePerlModForGroup(), generateXMLForGroup(), and writeGroupTreeNode().
getSubGroups() [2/2]
virtual const GroupList & GroupDef::getSubGroups () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
groupTitle() [1/2]
virtual QCString GroupDef::groupTitle () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by addToIndices(), buildGroupListFiltered(), DotGroupCollaboration::DotGroupCollaboration(), PerlModGenerator::generatePerlModForGroup(), generateXMLForGroup(), DocParser::handleLinkedWord(), DefinitionImpl::navigationPathAsString(), DefinitionImpl::pathFragment(), SearchIndex::setCurrentDoc(), ModuleContext::Private::title(), and writeGroupTreeNode().
groupTitle() [2/2]
virtual QCString GroupDef::groupTitle () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
hasDetailedDescription() [1/2]
virtual bool GroupDef::hasDetailedDescription () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by ModuleContext::Private::hasDetails().
hasDetailedDescription() [2/2]
virtual bool GroupDef::hasDetailedDescription () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
hasGroupTitle() [1/2]
virtual bool GroupDef::hasGroupTitle () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by buildGroupListFiltered().
hasGroupTitle() [2/2]
virtual bool GroupDef::hasGroupTitle () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
insertMember() [1/2]
virtual bool GroupDef::insertMember (const MemberDef * def, bool docOnly = FALSE) [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by addMemberToGroups(), MemberGroup::insertMember(), and ClassDefImpl::setGroupDefForAllMembers().
insertMember() [2/2]
virtual bool GroupDef::insertMember (const MemberDef * def, bool docOnly = FALSE) [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
isASubGroup() [1/2]
virtual bool GroupDef::isASubGroup () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by writeGroupTreeNode().
isASubGroup() [2/2]
virtual bool GroupDef::isASubGroup () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
isLinkable() [1/2]
virtual bool GroupDef::isLinkable () const [pure virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements Definition.
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by addMemberToSearchIndex(), findMembersWithSpecificName(), getDefsOld(), and getFortranDefs().
isLinkable() [2/2]
virtual bool GroupDef::isLinkable () const [pure virtual]
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements Definition.
Implemented in GroupDefImpl, and GroupDefImpl.
isLinkableInProject() [1/2]
virtual bool GroupDef::isLinkableInProject () const [pure virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements Definition.
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by MemberDefImpl::_computeLinkableInProject(), addToIndices(), and writeTagFile().
isLinkableInProject() [2/2]
virtual bool GroupDef::isLinkableInProject () const [pure virtual]
Returns TRUE iff it is possible to link to this item within this project.
Implements Definition.
Implemented in GroupDefImpl, and GroupDefImpl.
numDocMembers() [1/2]
virtual size_t GroupDef::numDocMembers () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
numDocMembers() [2/2]
virtual size_t GroupDef::numDocMembers () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
removeMember() [1/2]
virtual void GroupDef::removeMember (MemberDef * md) [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by addMemberToGroups().
removeMember() [2/2]
virtual void GroupDef::removeMember (MemberDef * md) [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
setGroupScope() [1/2]
virtual void GroupDef::setGroupScope (Definition * d) [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by findGroupScope().
setGroupScope() [2/2]
virtual void GroupDef::setGroupScope (Definition * d) [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
setGroupTitle() [1/2]
virtual void GroupDef::setGroupTitle (const QCString & newtitle) [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by buildGroupListFiltered().
setGroupTitle() [2/2]
virtual void GroupDef::setGroupTitle (const QCString & newtitle) [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
sortMemberLists() [1/2]
virtual void GroupDef::sortMemberLists () [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by sortMemberLists().
sortMemberLists() [2/2]
virtual void GroupDef::sortMemberLists () [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
sortSubGroups() [1/2]
virtual void GroupDef::sortSubGroups () [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by parseInput().
sortSubGroups() [2/2]
virtual void GroupDef::sortSubGroups () [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
subGrouping() [1/2]
virtual bool GroupDef::subGrouping () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by ModuleContext::Private::createMemberGroups().
subGrouping() [2/2]
virtual bool GroupDef::subGrouping () const [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
writeDocumentation() [1/2]
virtual void GroupDef::writeDocumentation (OutputList & ol) [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by generateGroupDocs().
writeDocumentation() [2/2]
virtual void GroupDef::writeDocumentation (OutputList & ol) [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
writeMemberPages() [1/2]
virtual void GroupDef::writeMemberPages (OutputList & ol) [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
writeMemberPages() [2/2]
virtual void GroupDef::writeMemberPages (OutputList & ol) [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
writeQuickMemberLinks() [1/2]
virtual void GroupDef::writeQuickMemberLinks (OutputList & ol, const MemberDef * currentMd) const [pure virtual]
Implements DefinitionMutable.
Implemented in GroupDefImpl, GroupDefImpl, DefinitionMixin< GroupDef >, and DefinitionMixin< GroupDef >.
writeQuickMemberLinks() [2/2]
virtual void GroupDef::writeQuickMemberLinks (OutputList & ol, const MemberDef * currentMd) const [pure virtual]
Implements DefinitionMutable.
Implemented in GroupDefImpl, GroupDefImpl, DefinitionMixin< GroupDef >, and DefinitionMixin< GroupDef >.
writeTagFile() [1/2]
virtual void GroupDef::writeTagFile (TextStream &) [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
Referenced by writeTagFile().
writeTagFile() [2/2]
virtual void GroupDef::writeTagFile (TextStream &) [pure virtual]
Implemented in GroupDefImpl, and GroupDefImpl.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/groupdef.h
doxygen/src/groupdef.h