ExprAstUnary Class Reference
Public Member Functions
ExprAstUnary (Operator::Type op, ExprAstPtr &&expr)
virtual TemplateVariant resolve (TemplateContext *c)
ExprAstUnary (Operator::Type op, ExprAstPtr &&expr)
virtual TemplateVariant resolve (TemplateContext *c)
Private Attributes
Operator::Type m_operator = Operator::Or
ExprAstPtr m_expr
Detailed Description
Definition at line 1801 of file template.cpp.
Constructor & Destructor Documentation
ExprAstUnary() [1/2]
ExprAstUnary::ExprAstUnary (Operator::Type op, ExprAstPtr && expr) [inline]
Definition at line 1804 of file template.cpp.
                                                    : m_operator(op), m_expr(std::move(expr))
    { TRACE(("ExprAstUnary %s\n",Operator::toString(op))); }
References Operator::toString(), and TRACE.
ExprAstUnary() [2/2]
ExprAstUnary::ExprAstUnary (Operator::Type op, ExprAstPtr && expr) [inline]
Definition at line 1804 of file template.cpp.
                                                    : m_operator(op), m_expr(std::move(expr))
    { TRACE(("ExprAstUnary %s\n",Operator::toString(op))); }
References Operator::toString(), and TRACE.
Member Function Documentation
resolve() [1/2]
virtual TemplateVariant ExprAstUnary::resolve (TemplateContext * c) [inline], [virtual]
Reimplemented from ExprAst.
Definition at line 1806 of file template.cpp.
    {
      TemplateVariant expr = m_expr->resolve(c);
      switch (m_operator)
      {
        case Operator::Minus:
          return -expr.toInt();
        default:
          return TemplateVariant();
      }
    }
References c, m_expr, m_operator, Operator::Minus, and TemplateVariant::toInt().
resolve() [2/2]
virtual TemplateVariant ExprAstUnary::resolve (TemplateContext * c) [inline], [virtual]
Reimplemented from ExprAst.
Definition at line 1806 of file template.cpp.
    {
      TemplateVariant expr = m_expr->resolve(c);
      switch (m_operator)
      {
        case Operator::Minus:
          return -expr.toInt();
        default:
          return TemplateVariant();
      }
    }
References c, Operator::Minus, and TemplateVariant::toInt().
Member Data Documentation
m_expr
ExprAstPtr ExprAstUnary::m_expr [private]
Definition at line 1819 of file template.cpp.
Referenced by resolve().
m_operator
Operator::Type ExprAstUnary::m_operator = Operator::Or [private]
Definition at line 1818 of file template.cpp.
Referenced by resolve().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp