CCodeParser Class Reference
#include <code.h>
Classes
struct Private
Public Member Functions
CCodeParser ()
virtual ~CCodeParser ()
void parseCode (CodeOutputInterface &codeOutIntf, const QCString &scopeName, const QCString &input, SrcLangExt lang, bool isExampleBlock, const QCString &exampleName=QCString(), const FileDef *fileDef=0, int startLine=-1, int endLine=-1, bool inlineFragment=FALSE, const MemberDef *memberDef=0, bool showLineNumbers=TRUE, const Definition *searchCtx=0, bool collectXRefs=TRUE)
void resetCodeParserState ()
void setInsideCodeLine (bool inp)
bool insideCodeLine () const
CCodeParser ()
virtual ~CCodeParser ()
void parseCode (CodeOutputInterface &codeOutIntf, const QCString &scopeName, const QCString &input, SrcLangExt lang, bool isExampleBlock, const QCString &exampleName=QCString(), const FileDef *fileDef=0, int startLine=-1, int endLine=-1, bool inlineFragment=FALSE, const MemberDef *memberDef=0, bool showLineNumbers=TRUE, const Definition *searchCtx=0, bool collectXRefs=TRUE)
void resetCodeParserState ()
void setInsideCodeLine (bool inp)
bool insideCodeLine () const
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Definition at line 28 of file code.h.
Constructor & Destructor Documentation
CCodeParser() [1/2]
CCodeParser::CCodeParser ()
Definition at line 3913 of file code.l.
                         : p(std::make_unique<CCodeParser::Private>())
{
  codeYYlex_init_extra(&p->state,&p->yyscanner);
#ifdef FLEX_DEBUG
  codeYYset_debug(1,p->yyscanner);
#endif
  resetCodeParserState();
}
References p, and resetCodeParserState().
 CCodeParser() [1/2]
CCodeParser::~CCodeParser () [virtual]
Definition at line 3922 of file code.l.
{
  codeYYlex_destroy(p->yyscanner);
}
References p.
CCodeParser() [2/2]
CCodeParser::CCodeParser ()
 CCodeParser() [2/2]
virtual CCodeParser::~CCodeParser () [virtual]
Member Function Documentation
insideCodeLine() [1/2]
bool CCodeParser::insideCodeLine () const
Definition at line 3945 of file code.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)p->yyscanner;
  return yyextra->insideCodeLine;
}
References p.
insideCodeLine() [2/2]
bool CCodeParser::insideCodeLine () const
parseCode() [1/2]
void CCodeParser::parseCode (CodeOutputInterface & codeOutIntf, const QCString & scopeName, const QCString & input, SrcLangExt lang, bool isExampleBlock, const QCString & exampleName = QCString(), const FileDef * fileDef = 0, int startLine = -1, int endLine = -1, bool inlineFragment = FALSE, const MemberDef * memberDef = 0, bool showLineNumbers = TRUE, const Definition * searchCtx = 0, bool collectXRefs = TRUE) [virtual]
Parses a source file or fragment with the goal to produce highlighted and cross-referenced output.
Parameters
 in codeOutIntf Abstract interface for writing the result.
 in scopeName Name of scope to which the code belongs.
 in input Actual code in the form of a string
 in lang The programming language of the code fragment.
 in isExampleBlock TRUE iff the code is part of an example.
 in exampleName Name of the example.
 in fileDef File definition to which the code is associated.
 in startLine Starting line in case of a code fragment.
 in endLine Ending line of the code fragment.
 in inlineFragment Code fragment that is to be shown inline as part of the documentation.
 in memberDef Member definition to which the code is associated (non null in case of an inline fragment for a member).
 in showLineNumbers if set to TRUE and also fileDef is not 0, line numbers will be added to the source fragment
 in searchCtx context under which search data has to be stored.
 in collectXRefs collect cross-reference relations.
Implements CodeParserInterface.
Definition at line 3951 of file code.l.
{
  yyscan_t yyscanner = p->yyscanner;
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  DBG_CTX((stderr,"***parseCode() exBlock=%d exName=%s fd=%p className=%s searchCtx=%s\n",
           exBlock,qPrint(exName),(void*)fd,qPrint(className),searchCtx?qPrint(searchCtx->name()):"<none>"));
  if (s.isEmpty()) return;
  printlex(yy_flex_debug, TRUE, __FILE__, fd ? qPrint(fd->fileName()): !exName.isEmpty() ? qPrint(exName) : NULL);
  yyextra->code = &od;
  yyextra->inputString = s.data();
  yyextra->fileName = fd ? fd->fileName():"";
  yyextra->inputPosition = 0;
  codeYYrestart(0,yyscanner);
  yyextra->currentFontClass = 0;
  yyextra->searchCtx = searchCtx;
  yyextra->collectXRefs = collectXRefs;
  yyextra->inFunctionTryBlock = FALSE;
  yyextra->symbolResolver.setFileScope(fd);
  if (startLine!=-1)
    yyextra->yyLineNr = startLine;
  else
    yyextra->yyLineNr = 1;
  if (endLine!=-1)
    yyextra->inputLines = endLine+1;
  else
    yyextra->inputLines = yyextra->yyLineNr + countLines(yyscanner) - 1;
  yyextra->curlyCount = 0;
  yyextra->bodyCurlyCount = 0;
  yyextra->bracketCount = 0;
  yyextra->sharpCount = 0;
  yyextra->insideTemplate = FALSE;
  yyextra->theCallContext.clear();
  while (!yyextra->scopeStack.empty()) yyextra->scopeStack.pop();
  yyextra->classScope = className;
  DBG_CTX((stderr,"parseCCode %s\n",qPrint(className)));
  yyextra->exampleBlock = exBlock;
  yyextra->exampleName = exName;
  yyextra->sourceFileDef = fd;
  yyextra->lineNumbers = fd!=0 && showLineNumbers;
  bool cleanupSourceDef = FALSE;
  if (fd==0)
  {
    // create a dummy filedef for the example
    yyextra->sourceFileDef = createFileDef(QCString(),(!exName.isEmpty()?exName:"generated"));
    cleanupSourceDef = TRUE;
  }
  yyextra->lang = lang;
  yyextra->insideObjC = lang==SrcLangExt_ObjC;
  if (yyextra->sourceFileDef)
  {
    setCurrentDoc(yyscanner,"l00001");
  }
  yyextra->currentDefinition = searchCtx ? searchCtx : getResolvedNamespace(className);
  yyextra->currentMemberDef = 0;
  yyextra->searchingForBody = exBlock;
  yyextra->insideBody = FALSE;
  yyextra->bracketCount = 0;
  if (!yyextra->exampleName.isEmpty())
  {
    yyextra->exampleFile = convertNameToFile(yyextra->exampleName+"-example",FALSE,TRUE);
    DBG_CTX((stderr,"yyextra->exampleFile=%s\n",qPrint(yyextra->exampleFile)));
  }
  yyextra->includeCodeFragment = inlineFragment;
  DBG_CTX((stderr,"** exBlock=%d exName=%s include=%d\n",exBlock,qPrint(exName),inlineFragment));
  if (!yyextra->insideCodeLine)
  {
    startCodeLine(yyscanner);
  }
  yyextra->type.resize(0);
  yyextra->name.resize(0);
  yyextra->args.resize(0);
  yyextra->parmName.resize(0);
  yyextra->parmType.resize(0);
  if (memberDef) setParameterList(yyscanner,memberDef);
  BEGIN(Body);
  codeYYlex(yyscanner);
  yyextra->lexInit=TRUE;
  if (yyextra->insideCodeLine)
  {
    endCodeLine(yyscanner);
  }
  if (cleanupSourceDef)
  {
    // delete the temporary file definition used for this example
    delete yyextra->sourceFileDef;
    yyextra->sourceFileDef=0;
  }
  // write the tooltips
  yyextra->tooltipManager.writeTooltips(od);
  printlex(yy_flex_debug, FALSE, __FILE__, fd ? qPrint(fd->fileName()): NULL);
}
References convertNameToFile(), countLines(), createFileDef(), gdFont::data, DBG_CTX, endCodeLine(), FALSE, FileDef::fileName(), getResolvedNamespace(), QCString::isEmpty(), Definition::name(), p, printlex(), qPrint(), s, setCurrentDoc(), setParameterList(), SrcLangExt_ObjC, startCodeLine(), and TRUE.
parseCode() [2/2]
void CCodeParser::parseCode (CodeOutputInterface & codeOutIntf, const QCString & scopeName, const QCString & input, SrcLangExt lang, bool isExampleBlock, const QCString & exampleName = QCString(), const FileDef * fileDef = 0, int startLine = -1, int endLine = -1, bool inlineFragment = FALSE, const MemberDef * memberDef = 0, bool showLineNumbers = TRUE, const Definition * searchCtx = 0, bool collectXRefs = TRUE) [virtual]
Parses a source file or fragment with the goal to produce highlighted and cross-referenced output.
Parameters
 in codeOutIntf Abstract interface for writing the result.
 in scopeName Name of scope to which the code belongs.
 in input Actual code in the form of a string
 in lang The programming language of the code fragment.
 in isExampleBlock TRUE iff the code is part of an example.
 in exampleName Name of the example.
 in fileDef File definition to which the code is associated.
 in startLine Starting line in case of a code fragment.
 in endLine Ending line of the code fragment.
 in inlineFragment Code fragment that is to be shown inline as part of the documentation.
 in memberDef Member definition to which the code is associated (non null in case of an inline fragment for a member).
 in showLineNumbers if set to TRUE and also fileDef is not 0, line numbers will be added to the source fragment
 in searchCtx context under which search data has to be stored.
 in collectXRefs collect cross-reference relations.
Implements CodeParserInterface.
resetCodeParserState() [1/2]
void CCodeParser::resetCodeParserState () [virtual]
Resets the state of the code parser. Since multiple code fragments can together form a single example, an explicit function is used to reset the code parser state.
See also
parseCode()
Implements CodeParserInterface.
Definition at line 3927 of file code.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)p->yyscanner;
  DBG_CTX((stderr,"***CodeParser::reset()\n"));
  yyextra->theVarContext.clear();
  while (!yyextra->classScopeLengthStack.empty()) yyextra->classScopeLengthStack.pop();
  yyextra->codeClassMap.clear();
  yyextra->curClassBases.clear();
  yyextra->anchorCount = 0;
  yyextra->insideCodeLine = false;
}
References DBG_CTX, and p.
Referenced by CCodeParser().
resetCodeParserState() [2/2]
void CCodeParser::resetCodeParserState () [virtual]
Resets the state of the code parser. Since multiple code fragments can together form a single example, an explicit function is used to reset the code parser state.
See also
parseCode()
Implements CodeParserInterface.
setInsideCodeLine() [1/2]
void CCodeParser::setInsideCodeLine (bool inp)
Definition at line 3939 of file code.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)p->yyscanner;
  yyextra->insideCodeLine = inp;
}
References p.
setInsideCodeLine() [2/2]
void CCodeParser::setInsideCodeLine (bool inp)
Member Data Documentation
p
std::unique_ptr< Private > CCodeParser::p [private]
Definition at line 53 of file code.h.
Referenced by CCodeParser(), insideCodeLine(), parseCode(), resetCodeParserState(), setInsideCodeLine(), and ~CCodeParser().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/code.h
doxygen/src/code.h
doxygen/build/doxygen/src/code.l
doxygen/src/code.l