LayoutDocManager Class Reference
Singleton providing access to the (user configurable) layout of the documentation.
#include <layout.h>
Classes
class Private
Public Types
enum LayoutPart {
Undefined = -1
, Class
, Concept
, Namespace
,
File
, Group
, Directory
, NrParts
,
Undefined = -1
, Class
, Concept
, Namespace
,
File
, Group
, Directory
, NrParts
 }
enum LayoutPart {
Undefined = -1
, Class
, Concept
, Namespace
,
File
, Group
, Directory
, NrParts
,
Undefined = -1
, Class
, Concept
, Namespace
,
File
, Group
, Directory
, NrParts
 }
Public Member Functions
const LayoutDocEntryList & docEntries (LayoutPart part) const
LayoutNavEntry * rootNavEntry () const
void parse (const QCString &fileName)
void init ()
const LayoutDocEntryList & docEntries (LayoutPart part) const
LayoutNavEntry * rootNavEntry () const
void parse (const QCString &fileName)
void init ()
Static Public Member Functions
static LayoutDocManager & instance ()
static LayoutDocManager & instance ()
Private Member Functions
void addEntry (LayoutPart p, LayoutDocEntry *e)
void clear (LayoutPart p)
LayoutDocManager ()
~LayoutDocManager ()
void addEntry (LayoutPart p, LayoutDocEntry *e)
void clear (LayoutPart p)
LayoutDocManager ()
~LayoutDocManager ()
Private Attributes
std::unique_ptr< Private > d
Friends
class LayoutParser
Detailed Description
Singleton providing access to the (user configurable) layout of the documentation.
Definition at line 197 of file layout.h.
Member Enumeration Documentation
LayoutPart [1/2]
enum LayoutDocManager::LayoutPart
Enumerator
Undefined
Class
Concept
Namespace
File
Group
Directory
NrParts
Undefined
Class
Concept
Namespace
File
Group
Directory
NrParts
Definition at line 201 of file layout.h.
    {
      Undefined = -1,
      Class, Concept, Namespace, File, Group, Directory,
      NrParts
    };
LayoutPart [2/2]
enum LayoutDocManager::LayoutPart
Enumerator
Undefined
Class
Concept
Namespace
File
Group
Directory
NrParts
Undefined
Class
Concept
Namespace
File
Group
Directory
NrParts
Definition at line 201 of file layout.h.
    {
      Undefined = -1,
      Class, Concept, Namespace, File, Group, Directory,
      NrParts
    };
Constructor & Destructor Documentation
LayoutDocManager() [1/2]
LayoutDocManager::LayoutDocManager () [private]
Definition at line 1559 of file layout.cpp.
                                   : d(std::make_unique<Private>())
{
  d->rootNav = new LayoutNavEntry;
}
References d.
Referenced by instance().
 LayoutDocManager() [1/2]
LayoutDocManager::~LayoutDocManager () [private]
Definition at line 1578 of file layout.cpp.
{
  delete d->rootNav;
}
References d.
LayoutDocManager() [2/2]
LayoutDocManager::LayoutDocManager () [private]
 LayoutDocManager() [2/2]
LayoutDocManager::~LayoutDocManager () [private]
Member Function Documentation
addEntry() [1/2]
void LayoutDocManager::addEntry (LayoutDocManager::LayoutPart p, LayoutDocEntry * e) [private]
Definition at line 1599 of file layout.cpp.
{
  d->docEntries[static_cast<int>(p)].push_back(std::unique_ptr<LayoutDocEntry>(e));
}
References d, e, and p.
Referenced by LayoutParser::endMemberDecl(), LayoutParser::endMemberDef(), LayoutParser::startMemberDecl(), LayoutParser::startMemberDeclEntry(), LayoutParser::startMemberDef(), LayoutParser::startMemberDefEntry(), LayoutParser::startSectionEntry(), and LayoutParser::startSimpleEntry().
addEntry() [2/2]
void LayoutDocManager::addEntry (LayoutPart p, LayoutDocEntry * e) [private]
clear() [1/2]
void LayoutDocManager::clear (LayoutDocManager::LayoutPart p) [private]
Definition at line 1604 of file layout.cpp.
{
  d->docEntries[static_cast<int>(p)].clear();
}
References clear(), d, and p.
Referenced by clear(), LayoutParser::startClass(), LayoutParser::startConcept(), LayoutParser::startDirectory(), LayoutParser::startFile(), LayoutParser::startGroup(), and LayoutParser::startNamespace().
clear() [2/2]
void LayoutDocManager::clear (LayoutPart p) [private]
docEntries() [1/2]
const LayoutDocEntryList & LayoutDocManager::docEntries (LayoutDocManager::LayoutPart part) const
Returns the list of LayoutDocEntry's in representation order for a given page identified by part.
Definition at line 1589 of file layout.cpp.
{
  return d->docEntries[static_cast<int>(part)];
}
References d.
Referenced by addMembersToIndex().
docEntries() [2/2]
const LayoutDocEntryList & LayoutDocManager::docEntries (LayoutPart part) const
Returns the list of LayoutDocEntry's in representation order for a given page identified by part.
init() [1/2]
void LayoutDocManager::init ()
Definition at line 1565 of file layout.cpp.
{
  LayoutParser &layoutParser = LayoutParser::instance();
  XMLHandlers handlers;
  handlers.startElement = [&layoutParser](const std::string &name,const XMLHandlers::Attributes &attrs) { layoutParser.startElement(name,attrs); };
  handlers.endElement = [&layoutParser](const std::string &name) { layoutParser.endElement(name); };
  handlers.error = [&layoutParser](const std::string &fileName,int lineNr,const std::string &msg) { layoutParser.error(fileName,lineNr,msg); };
  XMLParser parser(handlers);
  layoutParser.setDocumentLocator(&parser);
  QCString layout_default = ResourceMgr::instance().getAsString("layout_default.xml");
  parser.parse("layout_default.xml",layout_default.data(),Debug::isFlagSet(Debug::Lex));
}
References QCString::data(), XMLHandlers::endElement, LayoutParser::endElement(), XMLHandlers::error, LayoutParser::error(), ResourceMgr::getAsString(), LayoutParser::instance(), ResourceMgr::instance(), Debug::isFlagSet(), Debug::Lex, msg(), setup::name, XMLParser::parse(), LayoutParser::setDocumentLocator(), XMLHandlers::startElement, LayoutParser::startElement(), and string.
Referenced by parseInput().
init() [2/2]
void LayoutDocManager::init ()
instance() [1/2]
LayoutDocManager & LayoutDocManager::instance () [static]
Returns a reference to this singleton.
Definition at line 1583 of file layout.cpp.
{
  static LayoutDocManager *theInstance = new LayoutDocManager;
  return *theInstance;
}
References LayoutDocManager().
Referenced by NestingNodeContext::Private::addMembers(), addMembersToIndex(), ClassDefImpl::countAdditionalInheritedMembers(), countVisibleMembers(), LayoutParser::endMemberDecl(), LayoutParser::endMemberDef(), generateJSNavTree(), ClassDefImpl::getTitleForMemberListType(), parseInput(), renderQuickLinksAsTabs(), ClassDefImpl::setAnonymousEnumType(), LayoutParser::startClass(), LayoutParser::startConcept(), LayoutParser::startDirectory(), LayoutParser::startFile(), LayoutParser::startGroup(), LayoutParser::startMemberDecl(), LayoutParser::startMemberDeclEntry(), LayoutParser::startMemberDef(), LayoutParser::startMemberDefEntry(), LayoutParser::startNamespace(), LayoutParser::startNavEntry(), LayoutParser::startNavIndex(), LayoutParser::startSectionEntry(), LayoutParser::startSimpleEntry(), ClassDefImpl::writeAdditionalInheritedMembers(), writeAlphabeticalExceptionIndex(), writeAlphabeticalIndex(), writeAlphabeticalInterfaceIndex(), writeAlphabeticalStructIndex(), writeAnnotatedIndexGeneric(), writeClassMemberIndex(), writeClassMemberIndexFiltered(), writeConceptIndex(), ClassDefImpl::writeDeclaration(), writeDefaultQuickLinks(), ConceptDefImpl::writeDocumentation(), DirDefImpl::writeDocumentation(), FileDefImpl::writeDocumentation(), GroupDefImpl::writeDocumentation(), NamespaceDefImpl::writeDocumentation(), ClassDefImpl::writeDocumentationContents(), writeExampleIndex(), writeFileIndex(), writeFileMemberIndex(), writeFileMemberIndexFiltered(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeGroupIndex(), writeGroupTreeNode(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), writeIndexHierarchy(), writeIndexHierarchyEntries(), ClassDefImpl::writeInlineDocumentation(), writeMenuData(), writeNamespaceIndex(), writeNamespaceMemberIndex(), writeNamespaceMemberIndexFiltered(), writeNamespaceMembers(), writePageIndex(), writePages(), ClassDefImpl::writeSummaryLinks(), FileDefImpl::writeSummaryLinks(), GroupDefImpl::writeSummaryLinks(), NamespaceDefImpl::writeSummaryLinks(), ClassDefImpl::writeTagFile(), GroupDefImpl::writeTagFile(), NamespaceDefImpl::writeTagFile(), DirDefImpl::writeTagFile(), and FileDefImpl::writeTagFile().
instance() [2/2]
static LayoutDocManager & LayoutDocManager::instance () [static]
Returns a reference to this singleton.
parse() [1/2]
void LayoutDocManager::parse (const QCString & fileName)
Parses a user provided layout
Definition at line 1609 of file layout.cpp.
{
  LayoutParser &layoutParser = LayoutParser::instance();
  XMLHandlers handlers;
  handlers.startElement = [&layoutParser](const std::string &name,const XMLHandlers::Attributes &attrs) { layoutParser.startElement(name,attrs); };
  handlers.endElement = [&layoutParser](const std::string &name) { layoutParser.endElement(name); };
  handlers.error = [&layoutParser](const std::string &fn,int lineNr,const std::string &msg) { layoutParser.error(fn,lineNr,msg); };
  XMLParser parser(handlers);
  layoutParser.setDocumentLocator(&parser);
  parser.parse(fileName.data(),fileToString(fileName).data(),Debug::isFlagSet(Debug::Lex));
}
References data, QCString::data(), XMLHandlers::endElement, LayoutParser::endElement(), XMLHandlers::error, LayoutParser::error(), fileToString(), LayoutParser::instance(), Debug::isFlagSet(), Debug::Lex, msg(), setup::name, XMLParser::parse(), LayoutParser::setDocumentLocator(), XMLHandlers::startElement, LayoutParser::startElement(), and string.
Referenced by parseInput().
parse() [2/2]
void LayoutDocManager::parse (const QCString & fileName)
Parses a user provided layout
rootNavEntry() [1/2]
LayoutNavEntry * LayoutDocManager::rootNavEntry () const
returns the (invisible) root of the navigation tree.
Definition at line 1594 of file layout.cpp.
{
  return d->rootNav;
}
References d.
Referenced by generateJSNavTree(), renderQuickLinksAsTabs(), LayoutParser::startNavIndex(), writeAlphabeticalExceptionIndex(), writeAlphabeticalIndex(), writeAlphabeticalInterfaceIndex(), writeAlphabeticalStructIndex(), writeAnnotatedIndexGeneric(), writeClassMemberIndex(), writeClassMemberIndexFiltered(), writeConceptIndex(), writeDefaultQuickLinks(), writeExampleIndex(), writeFileIndex(), writeFileMemberIndex(), writeFileMemberIndexFiltered(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), writeIndexHierarchy(), writeMenuData(), writeNamespaceIndex(), writeNamespaceMemberIndex(), writeNamespaceMemberIndexFiltered(), writePageIndex(), and writePages().
rootNavEntry() [2/2]
LayoutNavEntry * LayoutDocManager::rootNavEntry () const
returns the (invisible) root of the navigation tree.
Friends And Related Function Documentation
LayoutParser
LayoutParser [friend]
Definition at line 225 of file layout.h.
Member Data Documentation
d
std::unique_ptr< Private > LayoutDocManager::d [private]
Definition at line 224 of file layout.h.
Referenced by addEntry(), clear(), docEntries(), LayoutDocManager(), rootNavEntry(), and ~LayoutDocManager().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/layout.h
doxygen/src/layout.h
doxygen/build/doxygen/src/layout.cpp
doxygen/src/layout.cpp