DocMscFile Class Reference
#include <docnode.h>
Public Member Functions
DocMscFile (DocParser *parser, DocNodeVariant *parent, const QCString &name, const QCString &context, const QCString &srcFile, int srcLine)
bool parse (DocNodeVariant *)
DocMscFile (DocParser *parser, DocNodeVariant *parent, const QCString &name, const QCString &context, const QCString &srcFile, int srcLine)
bool parse (DocNodeVariant *)
Additional Inherited Members
Detailed Description
Node representing a msc file
Definition at line 685 of file docnode.h.
Constructor & Destructor Documentation
DocMscFile() [1/2]
DocMscFile::DocMscFile (DocParser * parser, DocNodeVariant * parent, const QCString & name, const QCString & context, const QCString & srcFile, int srcLine)
Definition at line 1048 of file docnode.cpp.
                                                             :
  DocDiagramFileBase(parser,parent,name,context,srcFile,srcLine)
{
  p->relPath = parser->context.relPath;
}
References DocParser::context, DocDiagramFileBase::p, DocNode::parser(), and DocParserContext::relPath.
DocMscFile() [2/2]
DocMscFile::DocMscFile (DocParser * parser, DocNodeVariant * parent, const QCString & name, const QCString & context, const QCString & srcFile, int srcLine)
Member Function Documentation
parse() [1/2]
bool DocMscFile::parse (DocNodeVariant * thisVariant)
Definition at line 1055 of file docnode.cpp.
{
  bool ok = false;
  parser()->defaultHandleTitleAndSize(CMD_MSCFILE,thisVariant,children(),p->width,p->height);
  bool ambig;
  FileDef *fd = findFileDef(Doxygen::mscFileNameLinkedMap,p->name,ambig);
  if (fd==0 && !p->name.endsWith(".msc")) // try with .msc extension as well
  {
    fd = findFileDef(Doxygen::mscFileNameLinkedMap,p->name+".msc",ambig);
  }
  if (fd)
  {
    p->file = fd->absFilePath();
    ok = true;
    if (ambig)
    {
      warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"included msc file name %s is ambiguous.\n"
           "Possible candidates:\n%s",qPrint(p->name),
           qPrint(showFileDefMatches(Doxygen::mscFileNameLinkedMap,p->name))
          );
    }
  }
  else
  {
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"included msc file %s is not found "
           "in any of the paths specified via MSCFILE_DIRS!",qPrint(p->name));
  }
  return ok;
}
References FileDef::absFilePath(), DocCompoundNode::children(), CMD_MSCFILE, DocDiagramFileBase::context(), DocParser::defaultHandleTitleAndSize(), findFileDef(), Doxygen::mscFileNameLinkedMap, DocDiagramFileBase::p, DocNode::parser(), qPrint(), showFileDefMatches(), and warn_doc_error().
parse() [2/2]
bool DocMscFile::parse (DocNodeVariant *)
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docnode.h
doxygen/src/docnode.h
doxygen/build/doxygen/src/docnode.cpp
doxygen/src/docnode.cpp