TranslatorChinese Class Reference
#include <translator_cn.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString latexFontenc ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual bool needsPunctuation ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool, bool)
virtual QCString trFile (bool, bool)
virtual QCString trNamespace (bool, bool)
virtual QCString trGroup (bool, bool)
virtual QCString trPage (bool, bool)
virtual QCString trMember (bool, bool)
virtual QCString trGlobal (bool, bool)
virtual QCString trAuthor (bool, bool)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool, bool)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool, bool)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool)
virtual QCString trType (bool, bool)
virtual QCString trSubprogram (bool, bool)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
virtual QCString trDesignUnitHierarchy ()
virtual QCString trDesignUnitList ()
virtual QCString trDesignUnitMembers ()
virtual QCString trDesignUnitListDescription ()
virtual QCString trDesignUnitIndex ()
virtual QCString trDesignUnits ()
virtual QCString trFunctionAndProc ()
virtual QCString trVhdlType (uint64 type, bool single)
virtual QCString trCustomReference (const QCString &name)
virtual QCString trConstants ()
virtual QCString trConstantDocumentation ()
virtual QCString trSequences ()
virtual QCString trSequenceDocumentation ()
virtual QCString trDictionaries ()
virtual QCString trDictionaryDocumentation ()
virtual QCString trSliceInterfaces ()
virtual QCString trInterfaceIndex ()
virtual QCString trInterfaceList ()
virtual QCString trInterfaceListDescription ()
virtual QCString trInterfaceHierarchy ()
virtual QCString trInterfaceHierarchyDescription ()
virtual QCString trInterfaceDocumentation ()
virtual QCString trStructs ()
virtual QCString trStructIndex ()
virtual QCString trStructList ()
virtual QCString trStructListDescription ()
virtual QCString trStructDocumentation ()
virtual QCString trExceptionIndex ()
virtual QCString trExceptionList ()
virtual QCString trExceptionListDescription ()
virtual QCString trExceptionHierarchy ()
virtual QCString trExceptionHierarchyDescription ()
virtual QCString trExceptionDocumentation ()
virtual QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal)
virtual QCString trOperations ()
virtual QCString trOperationDocumentation ()
virtual QCString trDataMembers ()
virtual QCString trDataMemberDocumentation ()
virtual QCString trDesignUnitDocumentation ()
virtual QCString trConcept (bool first_capital, bool singular)
virtual QCString trConceptReference (const QCString &conceptName)
virtual QCString trConceptList ()
virtual QCString trConceptIndex ()
virtual QCString trConceptDocumentation ()
virtual QCString trConceptListDescription (bool extractAll)
virtual QCString trConceptDefinition ()
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString latexFontenc ()
virtual QCString latexDocumentPre ()
virtual QCString latexDocumentPost ()
virtual bool needsPunctuation ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool, bool)
virtual QCString trFile (bool, bool)
virtual QCString trNamespace (bool, bool)
virtual QCString trGroup (bool, bool)
virtual QCString trPage (bool, bool)
virtual QCString trMember (bool, bool)
virtual QCString trGlobal (bool, bool)
virtual QCString trAuthor (bool, bool)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool, bool)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool, bool)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool)
virtual QCString trType (bool, bool)
virtual QCString trSubprogram (bool, bool)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
virtual QCString trDesignUnitHierarchy ()
virtual QCString trDesignUnitList ()
virtual QCString trDesignUnitMembers ()
virtual QCString trDesignUnitListDescription ()
virtual QCString trDesignUnitIndex ()
virtual QCString trDesignUnits ()
virtual QCString trFunctionAndProc ()
virtual QCString trVhdlType (uint64 type, bool single)
virtual QCString trCustomReference (const QCString &name)
virtual QCString trConstants ()
virtual QCString trConstantDocumentation ()
virtual QCString trSequences ()
virtual QCString trSequenceDocumentation ()
virtual QCString trDictionaries ()
virtual QCString trDictionaryDocumentation ()
virtual QCString trSliceInterfaces ()
virtual QCString trInterfaceIndex ()
virtual QCString trInterfaceList ()
virtual QCString trInterfaceListDescription ()
virtual QCString trInterfaceHierarchy ()
virtual QCString trInterfaceHierarchyDescription ()
virtual QCString trInterfaceDocumentation ()
virtual QCString trStructs ()
virtual QCString trStructIndex ()
virtual QCString trStructList ()
virtual QCString trStructListDescription ()
virtual QCString trStructDocumentation ()
virtual QCString trExceptionIndex ()
virtual QCString trExceptionList ()
virtual QCString trExceptionListDescription ()
virtual QCString trExceptionHierarchy ()
virtual QCString trExceptionHierarchyDescription ()
virtual QCString trExceptionDocumentation ()
virtual QCString trCompoundReferenceSlice (const QCString &clName, ClassDef::CompoundType compType, bool isLocal)
virtual QCString trOperations ()
virtual QCString trOperationDocumentation ()
virtual QCString trDataMembers ()
virtual QCString trDataMemberDocumentation ()
virtual QCString trDesignUnitDocumentation ()
virtual QCString trConcept (bool first_capital, bool singular)
virtual QCString trConceptReference (const QCString &conceptName)
virtual QCString trConceptList ()
virtual QCString trConceptIndex ()
virtual QCString trConceptDocumentation ()
virtual QCString trConceptListDescription (bool extractAll)
virtual QCString trConceptDefinition ()
Additional Inherited Members
Detailed Description
Definition at line 27 of file translator_cn.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorChinese::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 62 of file translator_cn.h.
    {
      return "0x804 Chinese (PRC)";
    }
getLanguageString() [2/2]
virtual QCString TranslatorChinese::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 62 of file translator_cn.h.
    {
      return "0x804 Chinese (PRC)";
    }
idLanguage() [1/2]
virtual QCString TranslatorChinese::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in the language.cpp.
Implements Translator.
Definition at line 37 of file translator_cn.h.
    { return "chinese"; }
idLanguage() [2/2]
virtual QCString TranslatorChinese::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in the language.cpp.
Implements Translator.
Definition at line 37 of file translator_cn.h.
    { return "chinese"; }
latexDocumentPost() [1/2]
virtual QCString TranslatorChinese::latexDocumentPost () [inline], [virtual]
Sets the commands to be inserted directly before the \\end{document} in the LaTeX document.
Reimplemented from Translator.
Definition at line 74 of file translator_cn.h.
    {
      return "\\end{CJK}\n";
    }
latexDocumentPost() [2/2]
virtual QCString TranslatorChinese::latexDocumentPost () [inline], [virtual]
Sets the commands to be inserted directly before the \\end{document} in the LaTeX document.
Reimplemented from Translator.
Definition at line 74 of file translator_cn.h.
    {
      return "\\end{CJK}\n";
    }
latexDocumentPre() [1/2]
virtual QCString TranslatorChinese::latexDocumentPre () [inline], [virtual]
Sets the commands to be inserted directly after the \\begin{document} in the LaTeX document.
Reimplemented from Translator.
Definition at line 70 of file translator_cn.h.
    {
      return "\\begin{CJK}{UTF8}{gbsn}\n";
    }
latexDocumentPre() [2/2]
virtual QCString TranslatorChinese::latexDocumentPre () [inline], [virtual]
Sets the commands to be inserted directly after the \\begin{document} in the LaTeX document.
Reimplemented from Translator.
Definition at line 70 of file translator_cn.h.
    {
      return "\\begin{CJK}{UTF8}{gbsn}\n";
    }
latexFontenc() [1/2]
virtual QCString TranslatorChinese::latexFontenc () [inline], [virtual]
Sets the LaTeX font encoding to be used. The default is set to T1, in case another font encoding has to be used this can be specified with this routine. In case no font encoding is required the empty string can be returned.
Reimplemented from Translator.
Definition at line 66 of file translator_cn.h.
    {
      return "";
    }
latexFontenc() [2/2]
virtual QCString TranslatorChinese::latexFontenc () [inline], [virtual]
Sets the LaTeX font encoding to be used. The default is set to T1, in case another font encoding has to be used this can be specified with this routine. In case no font encoding is required the empty string can be returned.
Reimplemented from Translator.
Definition at line 66 of file translator_cn.h.
    {
      return "";
    }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorChinese::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
"\\usepackage[latin2]{inputenc}\n"
"\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 54 of file translator_cn.h.
    {
      return "\\usepackage{CJKutf8}\n";
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorChinese::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
"\\usepackage[latin2]{inputenc}\n"
"\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 54 of file translator_cn.h.
    {
      return "\\usepackage{CJKutf8}\n";
    }
needsPunctuation() [1/2]
virtual bool TranslatorChinese::needsPunctuation () [inline], [virtual]
add punctuation at the end of a brief description when needed and supported by the language
Reimplemented from Translator.
Definition at line 78 of file translator_cn.h.
    {
      return false;
    }
needsPunctuation() [2/2]
virtual bool TranslatorChinese::needsPunctuation () [inline], [virtual]
add punctuation at the end of a brief description when needed and supported by the language
Reimplemented from Translator.
Definition at line 78 of file translator_cn.h.
    {
      return false;
    }
trAdditionalInheritedMembers() [1/2]
virtual QCString TranslatorChinese::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1823 of file translator_cn.h.
    { return ""; }
trAdditionalInheritedMembers() [2/2]
virtual QCString TranslatorChinese::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1823 of file translator_cn.h.
    { return ""; }
trAll() [1/2]
virtual QCString TranslatorChinese::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1346 of file translator_cn.h.
    {
      return "";
    }
trAll() [2/2]
virtual QCString TranslatorChinese::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1346 of file translator_cn.h.
    {
      return "";
    }
trAndMore() [1/2]
virtual QCString TranslatorChinese::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1805 of file translator_cn.h.
    { return "" CN_SPC+number+CN_SPC "..."; }
References CN_SPC.
trAndMore() [2/2]
virtual QCString TranslatorChinese::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1805 of file translator_cn.h.
    { return "" CN_SPC+number+CN_SPC "..."; }
References CN_SPC.
trAttention() [1/2]
virtual QCString TranslatorChinese::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 876 of file translator_cn.h.
    {
      return "";
    }
trAttention() [2/2]
virtual QCString TranslatorChinese::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 876 of file translator_cn.h.
    {
      return "";
    }
trAuthor() [1/2]
virtual QCString TranslatorChinese::trAuthor (bool , bool) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1206 of file translator_cn.h.
    {
      /*
       QCString result((first_capital ? "Author" : "author"));
      if (!singular) result+="s";
      return result;
      */
      return "";
    }
trAuthor() [2/2]
virtual QCString TranslatorChinese::trAuthor (bool , bool) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1206 of file translator_cn.h.
    {
      /*
       QCString result((first_capital ? "Author" : "author"));
      if (!singular) result+="s";
      return result;
      */
      return "";
    }
trBug() [1/2]
virtual QCString TranslatorChinese::trBug () [inline], [virtual]
Implements Translator.
Definition at line 1041 of file translator_cn.h.
    {
      return "Bug";
    }
trBug() [2/2]
virtual QCString TranslatorChinese::trBug () [inline], [virtual]
Implements Translator.
Definition at line 1041 of file translator_cn.h.
    {
      return "Bug";
    }
trBugList() [1/2]
virtual QCString TranslatorChinese::trBugList () [inline], [virtual]
Implements Translator.
Definition at line 1046 of file translator_cn.h.
    {
      return "Bug" CN_SPC "";
    }
References CN_SPC.
trBugList() [2/2]
virtual QCString TranslatorChinese::trBugList () [inline], [virtual]
Implements Translator.
Definition at line 1046 of file translator_cn.h.
    {
      return "Bug" CN_SPC "";
    }
References CN_SPC.
trCallerGraph() [1/2]
virtual QCString TranslatorChinese::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1474 of file translator_cn.h.
    {
      return ":";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorChinese::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1474 of file translator_cn.h.
    {
      return ":";
    }
trCallGraph() [1/2]
virtual QCString TranslatorChinese::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1352 of file translator_cn.h.
    {
      return ":";
    }
trCallGraph() [2/2]
virtual QCString TranslatorChinese::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1352 of file translator_cn.h.
    {
      return ":";
    }
trCiteReferences() [1/2]
virtual QCString TranslatorChinese::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1779 of file translator_cn.h.
    { return ""; }
trCiteReferences() [2/2]
virtual QCString TranslatorChinese::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1779 of file translator_cn.h.
    { return ""; }
trClass() [1/2]
virtual QCString TranslatorChinese::trClass (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1105 of file translator_cn.h.
    {
      /*
       QCString result((first_capital ? "Class" : "class"));
      if (!singular) result+="es";
      return result;
      */
      return "";
    }
trClass() [2/2]
virtual QCString TranslatorChinese::trClass (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1105 of file translator_cn.h.
    {
      /*
       QCString result((first_capital ? "Class" : "class"));
      if (!singular) result+="es";
      return result;
      */
      return "";
    }
trClassDiagram() [1/2]
virtual QCString TranslatorChinese::trClassDiagram (const QCString & clName) [inline], [virtual]
Implements Translator.
Definition at line 410 of file translator_cn.h.
    {
      return "" CN_SPC+clName+CN_SPC ":";
    }
References CN_SPC.
trClassDiagram() [2/2]
virtual QCString TranslatorChinese::trClassDiagram (const QCString & clName) [inline], [virtual]
Implements Translator.
Definition at line 410 of file translator_cn.h.
    {
      return "" CN_SPC+clName+CN_SPC ":";
    }
References CN_SPC.
trClassDocumentation() [1/2]
virtual QCString TranslatorChinese::trClassDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 334 of file translator_cn.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else {
        return "";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorChinese::trClassDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 334 of file translator_cn.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else {
        return "";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorChinese::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1001 of file translator_cn.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorChinese::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1001 of file translator_cn.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorChinese::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 175 of file translator_cn.h.
    { return ""; }
trClassHierarchy() [2/2]
virtual QCString TranslatorChinese::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 175 of file translator_cn.h.
    { return ""; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorChinese::trClassHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 225 of file translator_cn.h.
    { return ":" CN_SPC; }
References CN_SPC.
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorChinese::trClassHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 225 of file translator_cn.h.
    { return ":" CN_SPC; }
References CN_SPC.
trClassMethods() [1/2]
virtual QCString TranslatorChinese::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1863 of file translator_cn.h.
    {
      return "";
    }
trClassMethods() [2/2]
virtual QCString TranslatorChinese::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1863 of file translator_cn.h.
    {
      return "";
    }
trCode() [1/2]
virtual QCString TranslatorChinese::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 760 of file translator_cn.h.
    {
      return "";
    }
trCode() [2/2]
virtual QCString TranslatorChinese::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 760 of file translator_cn.h.
    {
      return "";
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorChinese::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 706 of file translator_cn.h.
    {
      return clName+CN_SPC ":";
    }
References CN_SPC.
trCollaborationDiagram() [2/2]
virtual QCString TranslatorChinese::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 706 of file translator_cn.h.
    {
      return clName+CN_SPC ":";
    }
References CN_SPC.
trCompoundIndex() [1/2]
virtual QCString TranslatorChinese::trCompoundIndex () [inline], [virtual]
Implements Translator.
Definition at line 317 of file translator_cn.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else {
        return "";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorChinese::trCompoundIndex () [inline], [virtual]
Implements Translator.
Definition at line 317 of file translator_cn.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else {
        return "";
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorChinese::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1531 of file translator_cn.h.
    { return ""; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorChinese::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1531 of file translator_cn.h.
    { return ""; }
trCompoundList() [1/2]
virtual QCString TranslatorChinese::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated class
Implements Translator.
Definition at line 179 of file translator_cn.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "";
      }
      else {
        return "";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorChinese::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated class
Implements Translator.
Definition at line 179 of file translator_cn.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "";
      }
      else {
        return "";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorChinese::trCompoundListDescription () [inline], [virtual]
Implements Translator.
Definition at line 236 of file translator_cn.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return ":";
      }
      else
      {
        return ":";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorChinese::trCompoundListDescription () [inline], [virtual]
Implements Translator.
Definition at line 236 of file translator_cn.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return ":";
      }
      else
      {
        return ":";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorChinese::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1504 of file translator_cn.h.
    { return ":"; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorChinese::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1504 of file translator_cn.h.
    { return ":"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorChinese::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1496 of file translator_cn.h.
    { return ""; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorChinese::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1496 of file translator_cn.h.
    { return ""; }
trCompoundMembers() [1/2]
virtual QCString TranslatorChinese::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 194 of file translator_cn.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "";
      }
      else {
        return "";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorChinese::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 194 of file translator_cn.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "";
      }
      else {
        return "";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorChinese::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 248 of file translator_cn.h.
    {
      QCString result="";
      if (!extractAll) {
        result+="";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        result+="";
      }
      else {
        result+="";
      }
      //result+=" with links to ";
      if (extractAll) {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
          result+=":";
        }
        else {
          result+=":";
        }
      }
      else {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
          result+=":";
        }
        else {
          result+=":";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorChinese::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 248 of file translator_cn.h.
    {
      QCString result="";
      if (!extractAll) {
        result+="";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        result+="";
      }
      else {
        result+="";
      }
      //result+=" with links to ";
      if (extractAll) {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
          result+=":";
        }
        else {
          result+=":";
        }
      }
      else {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
          result+=":";
        }
        else {
          result+=":";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorChinese::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1508 of file translator_cn.h.
    {
      QCString result="";
      if (!extractAll)
      {
        result+="";
      }
      result+=",";
      //result+=" with links to ";
      if (!extractAll)
      {
        result+=":";
      }
      else
      {
        result+=":";
      }
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorChinese::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1508 of file translator_cn.h.
    {
      QCString result="";
      if (!extractAll)
      {
        result+="";
      }
      result+=",";
      //result+=" with links to ";
      if (!extractAll)
      {
        result+=":";
      }
      else
      {
        result+=":";
      }
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorChinese::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1500 of file translator_cn.h.
    { return ""; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorChinese::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1500 of file translator_cn.h.
    { return ""; }
trCompoundReference() [1/2]
virtual QCString TranslatorChinese::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
Implements Translator.
Definition at line 468 of file translator_cn.h.
    {
       QCString result=clName;
      if (isTemplate) result+=CN_SPC "";
      switch(compType)
      {
        case ClassDef::Class: result+=""; break;
        case ClassDef::Struct: result+=""; break;
        case ClassDef::Union: result+=""; break;
        case ClassDef::Interface: result+=""; break;
        case ClassDef::Protocol: result+=""; break;
        case ClassDef::Category: result+=""; break;
        case ClassDef::Exception: result+=""; break;
        default: break;
      }
      result+=CN_SPC "";
      return result;
    }
References ClassDef::Category, ClassDef::Class, CN_SPC, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorChinese::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
Implements Translator.
Definition at line 468 of file translator_cn.h.
    {
       QCString result=clName;
      if (isTemplate) result+=CN_SPC "";
      switch(compType)
      {
        case ClassDef::Class: result+=""; break;
        case ClassDef::Struct: result+=""; break;
        case ClassDef::Union: result+=""; break;
        case ClassDef::Interface: result+=""; break;
        case ClassDef::Protocol: result+=""; break;
        case ClassDef::Category: result+=""; break;
        case ClassDef::Exception: result+=""; break;
        default: break;
      }
      result+=CN_SPC "";
      return result;
    }
References ClassDef::Category, ClassDef::Class, CN_SPC, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorChinese::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1574 of file translator_cn.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=CN_SPC ""; break;
        case ClassDef::Struct: result+=CN_SPC ""; break;
        case ClassDef::Union: result+=CN_SPC ""; break;
        case ClassDef::Interface: result+=CN_SPC ""; break;
        case ClassDef::Protocol: result+=CN_SPC ""; break;
        case ClassDef::Category: result+=CN_SPC ""; break;
        case ClassDef::Exception: result+=CN_SPC ""; break;
        default: break;
      }
      if (isTemplate) result+="" CN_SPC;
      result+="";
      return result;
    }
References ClassDef::Category, ClassDef::Class, CN_SPC, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorChinese::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1574 of file translator_cn.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=CN_SPC ""; break;
        case ClassDef::Struct: result+=CN_SPC ""; break;
        case ClassDef::Union: result+=CN_SPC ""; break;
        case ClassDef::Interface: result+=CN_SPC ""; break;
        case ClassDef::Protocol: result+=CN_SPC ""; break;
        case ClassDef::Category: result+=CN_SPC ""; break;
        case ClassDef::Exception: result+=CN_SPC ""; break;
        default: break;
      }
      if (isTemplate) result+="" CN_SPC;
      result+="";
      return result;
    }
References ClassDef::Category, ClassDef::Class, CN_SPC, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice() [1/2]
virtual QCString TranslatorChinese::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) [inline], [virtual]
Implements Translator.
Definition at line 2124 of file translator_cn.h.
    {
      QCString result=clName;
      if (isLocal) result+=" ";
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      result+=" ";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceSlice() [2/2]
virtual QCString TranslatorChinese::trCompoundReferenceSlice (const QCString & clName, ClassDef::CompoundType compType, bool isLocal) [inline], [virtual]
Implements Translator.
Definition at line 2124 of file translator_cn.h.
    {
      QCString result=clName;
      if (isLocal) result+=" ";
      switch(compType)
      {
        case ClassDef::Class: result+=" "; break;
        case ClassDef::Struct: result+=" "; break;
        case ClassDef::Union: result+=" "; break;
        case ClassDef::Interface: result+=" "; break;
        case ClassDef::Protocol: result+=" "; break;
        case ClassDef::Category: result+=" "; break;
        case ClassDef::Exception: result+=" "; break;
        default: break;
      }
      result+=" ";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorChinese::trCompounds () [inline], [virtual]
Implements Translator.
Definition at line 392 of file translator_cn.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else {
        return "";
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorChinese::trCompounds () [inline], [virtual]
Implements Translator.
Definition at line 392 of file translator_cn.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else {
        return "";
      }
    }
References Config_getBool.
trConcept() [1/2]
virtual QCString TranslatorChinese::trConcept (bool first_capital, bool singular) [inline], [virtual]
C++20 concept
Implements Translator.
Definition at line 2172 of file translator_cn.h.
    {
      return "";
    }
trConcept() [2/2]
virtual QCString TranslatorChinese::trConcept (bool first_capital, bool singular) [inline], [virtual]
C++20 concept
Implements Translator.
Definition at line 2172 of file translator_cn.h.
    {
      return "";
    }
trConceptDefinition() [1/2]
virtual QCString TranslatorChinese::trConceptDefinition () [inline], [virtual]
used to introduce the definition of the C++20 concept
Implements Translator.
Definition at line 2203 of file translator_cn.h.
    {
      return "";
    }
trConceptDefinition() [2/2]
virtual QCString TranslatorChinese::trConceptDefinition () [inline], [virtual]
used to introduce the definition of the C++20 concept
Implements Translator.
Definition at line 2203 of file translator_cn.h.
    {
      return "";
    }
trConceptDocumentation() [1/2]
virtual QCString TranslatorChinese::trConceptDocumentation () [inline], [virtual]
used as the title of chapter containing all information about concepts.
Implements Translator.
Definition at line 2193 of file translator_cn.h.
    { return ""; }
trConceptDocumentation() [2/2]
virtual QCString TranslatorChinese::trConceptDocumentation () [inline], [virtual]
used as the title of chapter containing all information about concepts.
Implements Translator.
Definition at line 2193 of file translator_cn.h.
    { return ""; }
trConceptIndex() [1/2]
virtual QCString TranslatorChinese::trConceptIndex () [inline], [virtual]
used as the title of chapter containing the index listing all concepts.
Implements Translator.
Definition at line 2189 of file translator_cn.h.
    { return ""; }
trConceptIndex() [2/2]
virtual QCString TranslatorChinese::trConceptIndex () [inline], [virtual]
used as the title of chapter containing the index listing all concepts.
Implements Translator.
Definition at line 2189 of file translator_cn.h.
    { return ""; }
trConceptList() [1/2]
virtual QCString TranslatorChinese::trConceptList () [inline], [virtual]
used as the title of page containing all the index of all concepts.
Implements Translator.
Definition at line 2185 of file translator_cn.h.
    { return ""; }
trConceptList() [2/2]
virtual QCString TranslatorChinese::trConceptList () [inline], [virtual]
used as the title of page containing all the index of all concepts.
Implements Translator.
Definition at line 2185 of file translator_cn.h.
    { return ""; }
trConceptListDescription() [1/2]
virtual QCString TranslatorChinese::trConceptListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the concept list
Implements Translator.
Definition at line 2197 of file translator_cn.h.
    {
      return "";
    }
trConceptListDescription() [2/2]
virtual QCString TranslatorChinese::trConceptListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the concept list
Implements Translator.
Definition at line 2197 of file translator_cn.h.
    {
      return "";
    }
trConceptReference() [1/2]
virtual QCString TranslatorChinese::trConceptReference (const QCString & conceptName) [inline], [virtual]
used as the title of the HTML page of a C++20 concept page
Implements Translator.
Definition at line 2177 of file translator_cn.h.
    {
      QCString result=conceptName;
      result+=" ";
      return result;
    }
trConceptReference() [2/2]
virtual QCString TranslatorChinese::trConceptReference (const QCString & conceptName) [inline], [virtual]
used as the title of the HTML page of a C++20 concept page
Implements Translator.
Definition at line 2177 of file translator_cn.h.
    {
      QCString result=conceptName;
      result+=" ";
      return result;
    }
trConstantDocumentation() [1/2]
virtual QCString TranslatorChinese::trConstantDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2032 of file translator_cn.h.
    {
        return "";
    }
trConstantDocumentation() [2/2]
virtual QCString TranslatorChinese::trConstantDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2032 of file translator_cn.h.
    {
        return "";
    }
trConstantGroupReference() [1/2]
virtual QCString TranslatorChinese::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1900 of file translator_cn.h.
    {
      QCString result=namespaceName;
      result+= CN_SPC "";
      return result;
    }
References CN_SPC.
trConstantGroupReference() [2/2]
virtual QCString TranslatorChinese::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1900 of file translator_cn.h.
    {
      QCString result=namespaceName;
      result+= CN_SPC "";
      return result;
    }
References CN_SPC.
trConstantGroups() [1/2]
virtual QCString TranslatorChinese::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1896 of file translator_cn.h.
    { return ""; }
trConstantGroups() [2/2]
virtual QCString TranslatorChinese::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 1896 of file translator_cn.h.
    { return ""; }
trConstants() [1/2]
virtual QCString TranslatorChinese::trConstants () [inline], [virtual]
Implements Translator.
Definition at line 2028 of file translator_cn.h.
    {
        return "";
    }
trConstants() [2/2]
virtual QCString TranslatorChinese::trConstants () [inline], [virtual]
Implements Translator.
Definition at line 2028 of file translator_cn.h.
    {
        return "";
    }
trConstructorDocumentation() [1/2]
virtual QCString TranslatorChinese::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 718 of file translator_cn.h.
    {
      return "";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorChinese::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 718 of file translator_cn.h.
    {
      return "";
    }
trCopyright() [1/2]
virtual QCString TranslatorChinese::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1783 of file translator_cn.h.
    { return ""; }
trCopyright() [2/2]
virtual QCString TranslatorChinese::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1783 of file translator_cn.h.
    { return ""; }
trCustomReference() [1/2]
virtual QCString TranslatorChinese::trCustomReference (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 2024 of file translator_cn.h.
    { return QCString(name)+" "; }
References setup::name.
trCustomReference() [2/2]
virtual QCString TranslatorChinese::trCustomReference (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 2024 of file translator_cn.h.
    { return QCString(name)+" "; }
References setup::name.
trDataMemberDocumentation() [1/2]
virtual QCString TranslatorChinese::trDataMemberDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2154 of file translator_cn.h.
    {
        return "";
    }
trDataMemberDocumentation() [2/2]
virtual QCString TranslatorChinese::trDataMemberDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2154 of file translator_cn.h.
    {
        return "";
    }
trDataMembers() [1/2]
virtual QCString TranslatorChinese::trDataMembers () [inline], [virtual]
Implements Translator.
Definition at line 2150 of file translator_cn.h.
    {
        return "";
    }
trDataMembers() [2/2]
virtual QCString TranslatorChinese::trDataMembers () [inline], [virtual]
Implements Translator.
Definition at line 2150 of file translator_cn.h.
    {
        return "";
    }
trDataTypes() [1/2]
virtual QCString TranslatorChinese::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1557 of file translator_cn.h.
    { return ""; }
trDataTypes() [2/2]
virtual QCString TranslatorChinese::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1557 of file translator_cn.h.
    { return ""; }
trDate() [1/2]
virtual QCString TranslatorChinese::trDate () [inline], [virtual]
Implements Translator.
Definition at line 421 of file translator_cn.h.
    { return ""; }
trDate() [2/2]
virtual QCString TranslatorChinese::trDate () [inline], [virtual]
Implements Translator.
Definition at line 421 of file translator_cn.h.
    { return ""; }
trDateTime() [1/2]
virtual QCString TranslatorChinese::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Implements Translator.
Definition at line 1737 of file translator_cn.h.
  {
    static const char *days[] = { "","","","","","","" };
    static const char *months[] = { "","","","","","","","","","","","" };
    QCString sdate;
    sdate.sprintf("%d" CN_SPC "%s" CN_SPC "%d" CN_SPC "%s",year, months[month-1], day, days[dayOfWeek-1]);
    if (includeTime)
    {
      QCString stime;
      stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
      sdate+=stime;
    }
    return sdate;
  }
References CN_SPC, and QCString::sprintf().
trDateTime() [2/2]
virtual QCString TranslatorChinese::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Implements Translator.
Definition at line 1737 of file translator_cn.h.
  {
    static const char *days[] = { "","","","","","","" };
    static const char *months[] = { "","","","","","","","","","","","" };
    QCString sdate;
    sdate.sprintf("%d" CN_SPC "%s" CN_SPC "%d" CN_SPC "%s",year, months[month-1], day, days[dayOfWeek-1]);
    if (includeTime)
    {
      QCString stime;
      stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
      sdate+=stime;
    }
    return sdate;
  }
References CN_SPC, and QCString::sprintf().
trDayOfWeek() [1/2]
virtual QCString TranslatorChinese::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1756 of file translator_cn.h.
  {
    static const char *days_short[] = { "", "", "", "", "", "", "" };
    static const char *days_full[] = { "", "", "", "", "", "", "" };
    return full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
  }
trDayOfWeek() [2/2]
virtual QCString TranslatorChinese::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1756 of file translator_cn.h.
  {
    static const char *days_short[] = { "", "", "", "", "", "", "" };
    static const char *days_full[] = { "", "", "", "", "", "", "" };
    return full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
  }
trDayPeriod() [1/2]
virtual QCString TranslatorChinese::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1768 of file translator_cn.h.
  {
    static const char *dayPeriod[] = { "", "" };
    return dayPeriod[period];
  }
trDayPeriod() [2/2]
virtual QCString TranslatorChinese::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1768 of file translator_cn.h.
  {
    static const char *dayPeriod[] = { "", "" };
    return dayPeriod[period];
  }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorChinese::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 682 of file translator_cn.h.
    {
      return "" CN_SPC "@1" CN_SPC "" CN_SPC "@0" CN_SPC ".";
    }
References CN_SPC.
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorChinese::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 682 of file translator_cn.h.
    {
      return "" CN_SPC "@1" CN_SPC "" CN_SPC "@0" CN_SPC ".";
    }
References CN_SPC.
trDefinedIn() [1/2]
virtual QCString TranslatorChinese::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 163 of file translator_cn.h.
    { return "" CN_SPC; }
References CN_SPC.
trDefinedIn() [2/2]
virtual QCString TranslatorChinese::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 163 of file translator_cn.h.
    { return "" CN_SPC; }
References CN_SPC.
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorChinese::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 687 of file translator_cn.h.
    {
      return "" CN_SPC "@0" CN_SPC ".";
    }
References CN_SPC.
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorChinese::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 687 of file translator_cn.h.
    {
      return "" CN_SPC "@0" CN_SPC ".";
    }
References CN_SPC.
trDefineDocumentation() [1/2]
virtual QCString TranslatorChinese::trDefineDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 377 of file translator_cn.h.
    { return ""; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorChinese::trDefineDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 377 of file translator_cn.h.
    { return ""; }
trDefines() [1/2]
virtual QCString TranslatorChinese::trDefines () [inline], [virtual]
Implements Translator.
Definition at line 358 of file translator_cn.h.
    { return ""; }
trDefines() [2/2]
virtual QCString TranslatorChinese::trDefines () [inline], [virtual]
Implements Translator.
Definition at line 358 of file translator_cn.h.
    { return ""; }
trDefineValue() [1/2]
virtual QCString TranslatorChinese::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1033 of file translator_cn.h.
    {
      return ":";
    }
trDefineValue() [2/2]
virtual QCString TranslatorChinese::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1033 of file translator_cn.h.
    {
      return ":";
    }
trDeprecated() [1/2]
virtual QCString TranslatorChinese::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 696 of file translator_cn.h.
    {
      return "";
    }
trDeprecated() [2/2]
virtual QCString TranslatorChinese::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 696 of file translator_cn.h.
    {
      return "";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorChinese::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1269 of file translator_cn.h.
    {
      return "";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorChinese::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1269 of file translator_cn.h.
    {
      return "";
    }
trDesignUnitDocumentation() [1/2]
virtual QCString TranslatorChinese::trDesignUnitDocumentation () [inline], [virtual]
VHDL design unit documentation
Implements Translator.
Definition at line 2164 of file translator_cn.h.
    { return ""; }
Referenced by trClassDocumentation().
trDesignUnitDocumentation() [2/2]
virtual QCString TranslatorChinese::trDesignUnitDocumentation () [inline], [virtual]
VHDL design unit documentation
Implements Translator.
Definition at line 2164 of file translator_cn.h.
    { return ""; }
trDesignUnitHierarchy() [1/2]
virtual QCString TranslatorChinese::trDesignUnitHierarchy () [inline], [virtual]
VHDL design unit hierarchy
Implements Translator.
Definition at line 1938 of file translator_cn.h.
    { return ""; }
trDesignUnitHierarchy() [2/2]
virtual QCString TranslatorChinese::trDesignUnitHierarchy () [inline], [virtual]
VHDL design unit hierarchy
Implements Translator.
Definition at line 1938 of file translator_cn.h.
    { return ""; }
trDesignUnitIndex() [1/2]
virtual QCString TranslatorChinese::trDesignUnitIndex () [inline], [virtual]
VHDL design unit index
Implements Translator.
Definition at line 1952 of file translator_cn.h.
    { return ""; }
trDesignUnitIndex() [2/2]
virtual QCString TranslatorChinese::trDesignUnitIndex () [inline], [virtual]
VHDL design unit index
Implements Translator.
Definition at line 1952 of file translator_cn.h.
    { return ""; }
trDesignUnitList() [1/2]
virtual QCString TranslatorChinese::trDesignUnitList () [inline], [virtual]
VHDL design unit list
Implements Translator.
Definition at line 1941 of file translator_cn.h.
    { return ""; }
trDesignUnitList() [2/2]
virtual QCString TranslatorChinese::trDesignUnitList () [inline], [virtual]
VHDL design unit list
Implements Translator.
Definition at line 1941 of file translator_cn.h.
    { return ""; }
trDesignUnitListDescription() [1/2]
virtual QCString TranslatorChinese::trDesignUnitListDescription () [inline], [virtual]
VHDL design unit list description
Implements Translator.
Definition at line 1947 of file translator_cn.h.
    {
        return ":";
    }
trDesignUnitListDescription() [2/2]
virtual QCString TranslatorChinese::trDesignUnitListDescription () [inline], [virtual]
VHDL design unit list description
Implements Translator.
Definition at line 1947 of file translator_cn.h.
    {
        return ":";
    }
trDesignUnitMembers() [1/2]
virtual QCString TranslatorChinese::trDesignUnitMembers () [inline], [virtual]
VHDL design unit members
Implements Translator.
Definition at line 1944 of file translator_cn.h.
    { return ""; }
trDesignUnitMembers() [2/2]
virtual QCString TranslatorChinese::trDesignUnitMembers () [inline], [virtual]
VHDL design unit members
Implements Translator.
Definition at line 1944 of file translator_cn.h.
    { return ""; }
trDesignUnits() [1/2]
virtual QCString TranslatorChinese::trDesignUnits () [inline], [virtual]
VHDL design units
Implements Translator.
Definition at line 1955 of file translator_cn.h.
    { return ""; }
trDesignUnits() [2/2]
virtual QCString TranslatorChinese::trDesignUnits () [inline], [virtual]
VHDL design units
Implements Translator.
Definition at line 1955 of file translator_cn.h.
    { return ""; }
trDetailedDescription() [1/2]
virtual QCString TranslatorChinese::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 95 of file translator_cn.h.
    { return ""; }
trDetailedDescription() [2/2]
virtual QCString TranslatorChinese::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 95 of file translator_cn.h.
    { return ""; }
trDetailLevel() [1/2]
virtual QCString TranslatorChinese::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1797 of file translator_cn.h.
    { return ""; }
trDetailLevel() [2/2]
virtual QCString TranslatorChinese::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1797 of file translator_cn.h.
    { return ""; }
trDictionaries() [1/2]
virtual QCString TranslatorChinese::trDictionaries () [inline], [virtual]
Implements Translator.
Definition at line 2044 of file translator_cn.h.
    {
        return "";
    }
trDictionaries() [2/2]
virtual QCString TranslatorChinese::trDictionaries () [inline], [virtual]
Implements Translator.
Definition at line 2044 of file translator_cn.h.
    {
        return "";
    }
trDictionaryDocumentation() [1/2]
virtual QCString TranslatorChinese::trDictionaryDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2048 of file translator_cn.h.
    {
        return "";
    }
trDictionaryDocumentation() [2/2]
virtual QCString TranslatorChinese::trDictionaryDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2048 of file translator_cn.h.
    {
        return "";
    }
trDir() [1/2]
virtual QCString TranslatorChinese::trDir (bool , bool) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1451 of file translator_cn.h.
    {
      return "";
    }
trDir() [2/2]
virtual QCString TranslatorChinese::trDir (bool , bool) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1451 of file translator_cn.h.
    {
      return "";
    }
trDirDepGraph() [1/2]
virtual QCString TranslatorChinese::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1787 of file translator_cn.h.
    {
      return QCString(name)+CN_SPC "";
    }
References CN_SPC, and setup::name.
trDirDepGraph() [2/2]
virtual QCString TranslatorChinese::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1787 of file translator_cn.h.
    {
      return QCString(name)+CN_SPC "";
    }
References CN_SPC, and setup::name.
trDirDocumentation() [1/2]
virtual QCString TranslatorChinese::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1427 of file translator_cn.h.
    {
      return "";
    }
trDirDocumentation() [2/2]
virtual QCString TranslatorChinese::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1427 of file translator_cn.h.
    {
      return "";
    }
trDirectories() [1/2]
virtual QCString TranslatorChinese::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1435 of file translator_cn.h.
    { return ""; }
trDirectories() [2/2]
virtual QCString TranslatorChinese::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1435 of file translator_cn.h.
    { return ""; }
trDirIndex() [1/2]
virtual QCString TranslatorChinese::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1419 of file translator_cn.h.
    {
      return "";
    }
trDirIndex() [2/2]
virtual QCString TranslatorChinese::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1419 of file translator_cn.h.
    {
      return "";
    }
trDirReference() [1/2]
virtual QCString TranslatorChinese::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1441 of file translator_cn.h.
    {
      QCString result=dirName;
      result+=CN_SPC "";
      return result;
    }
References CN_SPC.
trDirReference() [2/2]
virtual QCString TranslatorChinese::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1441 of file translator_cn.h.
    {
      QCString result=dirName;
      result+=CN_SPC "";
      return result;
    }
References CN_SPC.
trDirRelation() [1/2]
virtual QCString TranslatorChinese::trDirRelation (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 1696 of file translator_cn.h.
  {
    // return QCString(name)+" Relation";
    // unsure
    return QCString(name)+CN_SPC "";
  }
References CN_SPC, and setup::name.
trDirRelation() [2/2]
virtual QCString TranslatorChinese::trDirRelation (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 1696 of file translator_cn.h.
  {
    // return QCString(name)+" Relation";
    // unsure
    return QCString(name)+CN_SPC "";
  }
References CN_SPC, and setup::name.
trDocumentation() [1/2]
virtual QCString TranslatorChinese::trDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 308 of file translator_cn.h.
    { return ""; }
trDocumentation() [2/2]
virtual QCString TranslatorChinese::trDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 308 of file translator_cn.h.
    { return ""; }
trEnumerations() [1/2]
virtual QCString TranslatorChinese::trEnumerations () [inline], [virtual]
Implements Translator.
Definition at line 364 of file translator_cn.h.
    { return ""; }
trEnumerations() [2/2]
virtual QCString TranslatorChinese::trEnumerations () [inline], [virtual]
Implements Translator.
Definition at line 364 of file translator_cn.h.
    { return ""; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorChinese::trEnumerationTypeDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 383 of file translator_cn.h.
    { return ""; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorChinese::trEnumerationTypeDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 383 of file translator_cn.h.
    { return ""; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorChinese::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1482 of file translator_cn.h.
    {
      return "";
    }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorChinese::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1482 of file translator_cn.h.
    {
      return "";
    }
trEnumerationValues() [1/2]
virtual QCString TranslatorChinese::trEnumerationValues () [inline], [virtual]
Implements Translator.
Definition at line 373 of file translator_cn.h.
    { return ""; }
trEnumerationValues() [2/2]
virtual QCString TranslatorChinese::trEnumerationValues () [inline], [virtual]
Implements Translator.
Definition at line 373 of file translator_cn.h.
    { return ""; }
trEnumGeneratedFromFiles() [1/2]
virtual QCString TranslatorChinese::trEnumGeneratedFromFiles (bool) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1809 of file translator_cn.h.
    { return ":"; }
trEnumGeneratedFromFiles() [2/2]
virtual QCString TranslatorChinese::trEnumGeneratedFromFiles (bool) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1809 of file translator_cn.h.
    { return ":"; }
trEnumName() [1/2]
virtual QCString TranslatorChinese::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 155 of file translator_cn.h.
    { return ""; }
trEnumName() [2/2]
virtual QCString TranslatorChinese::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 155 of file translator_cn.h.
    { return ""; }
trEnumReference() [1/2]
virtual QCString TranslatorChinese::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1813 of file translator_cn.h.
    { return QCString(name)+CN_SPC ""; }
References CN_SPC, and setup::name.
trEnumReference() [2/2]
virtual QCString TranslatorChinese::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1813 of file translator_cn.h.
    { return QCString(name)+CN_SPC ""; }
References CN_SPC, and setup::name.
trEnumValue() [1/2]
virtual QCString TranslatorChinese::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 159 of file translator_cn.h.
    { return ""; }
trEnumValue() [2/2]
virtual QCString TranslatorChinese::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 159 of file translator_cn.h.
    { return ""; }
trEventDocumentation() [1/2]
virtual QCString TranslatorChinese::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1287 of file translator_cn.h.
    {
      return "";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorChinese::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1287 of file translator_cn.h.
    {
      return "";
    }
trEvents() [1/2]
virtual QCString TranslatorChinese::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1281 of file translator_cn.h.
    {
      return "";
    }
trEvents() [2/2]
virtual QCString TranslatorChinese::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1281 of file translator_cn.h.
    {
      return "";
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorChinese::trExampleDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 352 of file translator_cn.h.
    { return ""; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorChinese::trExampleDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 352 of file translator_cn.h.
    { return ""; }
trExamples() [1/2]
virtual QCString TranslatorChinese::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 219 of file translator_cn.h.
    { return ""; }
trExamples() [2/2]
virtual QCString TranslatorChinese::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 219 of file translator_cn.h.
    { return ""; }
trExamplesDescription() [1/2]
virtual QCString TranslatorChinese::trExamplesDescription () [inline], [virtual]
Implements Translator.
Definition at line 299 of file translator_cn.h.
    { return ":"; }
trExamplesDescription() [2/2]
virtual QCString TranslatorChinese::trExamplesDescription () [inline], [virtual]
Implements Translator.
Definition at line 299 of file translator_cn.h.
    { return ":"; }
trExceptionDocumentation() [1/2]
virtual QCString TranslatorChinese::trExceptionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2120 of file translator_cn.h.
    {
        return "";
    }
trExceptionDocumentation() [2/2]
virtual QCString TranslatorChinese::trExceptionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2120 of file translator_cn.h.
    {
        return "";
    }
trExceptionHierarchy() [1/2]
virtual QCString TranslatorChinese::trExceptionHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2112 of file translator_cn.h.
    {
        return "";
    }
trExceptionHierarchy() [2/2]
virtual QCString TranslatorChinese::trExceptionHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2112 of file translator_cn.h.
    {
        return "";
    }
trExceptionHierarchyDescription() [1/2]
virtual QCString TranslatorChinese::trExceptionHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2116 of file translator_cn.h.
    {
        return ":";
    }
trExceptionHierarchyDescription() [2/2]
virtual QCString TranslatorChinese::trExceptionHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2116 of file translator_cn.h.
    {
        return ":";
    }
trExceptionIndex() [1/2]
virtual QCString TranslatorChinese::trExceptionIndex () [inline], [virtual]
Implements Translator.
Definition at line 2100 of file translator_cn.h.
    {
        return "";
    }
trExceptionIndex() [2/2]
virtual QCString TranslatorChinese::trExceptionIndex () [inline], [virtual]
Implements Translator.
Definition at line 2100 of file translator_cn.h.
    {
        return "";
    }
trExceptionList() [1/2]
virtual QCString TranslatorChinese::trExceptionList () [inline], [virtual]
Implements Translator.
Definition at line 2104 of file translator_cn.h.
    {
        return "";
    }
trExceptionList() [2/2]
virtual QCString TranslatorChinese::trExceptionList () [inline], [virtual]
Implements Translator.
Definition at line 2104 of file translator_cn.h.
    {
        return "";
    }
trExceptionListDescription() [1/2]
virtual QCString TranslatorChinese::trExceptionListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2108 of file translator_cn.h.
    {
        return ":";
    }
trExceptionListDescription() [2/2]
virtual QCString TranslatorChinese::trExceptionListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2108 of file translator_cn.h.
    {
        return ":";
    }
trExceptions() [1/2]
virtual QCString TranslatorChinese::trExceptions () [inline], [virtual]
Implements Translator.
Definition at line 433 of file translator_cn.h.
    { return ""; }
trExceptions() [2/2]
virtual QCString TranslatorChinese::trExceptions () [inline], [virtual]
Implements Translator.
Definition at line 433 of file translator_cn.h.
    { return ""; }
trExtendsClass() [1/2]
virtual QCString TranslatorChinese::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1855 of file translator_cn.h.
    {
      return " @0.";
    }
trExtendsClass() [2/2]
virtual QCString TranslatorChinese::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1855 of file translator_cn.h.
    {
      return " @0.";
    }
trFile() [1/2]
virtual QCString TranslatorChinese::trFile (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1119 of file translator_cn.h.
    {
      /*
       QCString result((first_capital ? "File" : "file"));
      if (!singular) result+="s";
      return result;
      */
      return "";
    }
trFile() [2/2]
virtual QCString TranslatorChinese::trFile (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1119 of file translator_cn.h.
    {
      /*
       QCString result((first_capital ? "File" : "file"));
      if (!singular) result+="s";
      return result;
      */
      return "";
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorChinese::trFileDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 349 of file translator_cn.h.
    { return ""; }
trFileDocumentation() [2/2]
virtual QCString TranslatorChinese::trFileDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 349 of file translator_cn.h.
    { return ""; }
trFileIn() [1/2]
virtual QCString TranslatorChinese::trFileIn (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 1727 of file translator_cn.h.
  {
    return QCString("")+CN_SPC+name;
  }
References CN_SPC, and setup::name.
trFileIn() [2/2]
virtual QCString TranslatorChinese::trFileIn (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 1727 of file translator_cn.h.
  {
    return QCString("")+CN_SPC+name;
  }
References CN_SPC, and setup::name.
trFileIndex() [1/2]
virtual QCString TranslatorChinese::trFileIndex () [inline], [virtual]
Implements Translator.
Definition at line 328 of file translator_cn.h.
    { return ""; }
trFileIndex() [2/2]
virtual QCString TranslatorChinese::trFileIndex () [inline], [virtual]
Implements Translator.
Definition at line 328 of file translator_cn.h.
    { return ""; }
trFileList() [1/2]
virtual QCString TranslatorChinese::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 190 of file translator_cn.h.
    { return ""; }
trFileList() [2/2]
virtual QCString TranslatorChinese::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 190 of file translator_cn.h.
    { return ""; }
trFileListDescription() [1/2]
virtual QCString TranslatorChinese::trFileListDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 228 of file translator_cn.h.
    {
      QCString result="";
      if (!extractAll) result+="";
      result+=":";
      return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorChinese::trFileListDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 228 of file translator_cn.h.
    {
      QCString result="";
      if (!extractAll) result+="";
      result+=":";
      return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorChinese::trFileMembers () [inline], [virtual]
This is put above each page as a link to all member of files.
Implements Translator.
Definition at line 205 of file translator_cn.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "";
      } else {
        return "";
      }
    }
References Config_getBool.
trFileMembers() [2/2]
virtual QCString TranslatorChinese::trFileMembers () [inline], [virtual]
This is put above each page as a link to all member of files.
Implements Translator.
Definition at line 205 of file translator_cn.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        return "";
      } else {
        return "";
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
virtual QCString TranslatorChinese::trFileMembersDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 280 of file translator_cn.h.
    {
      QCString result="";
      if (!extractAll)
        result +="";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        result +=",,,,";
      }
      else {
        result +=",";
      }
      if (extractAll)
        result+=":";
      else
        result+=":";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorChinese::trFileMembersDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 280 of file translator_cn.h.
    {
      QCString result="";
      if (!extractAll)
        result +="";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C)) {
        result +=",,,,";
      }
      else {
        result +=",";
      }
      if (extractAll)
        result+=":";
      else
        result+=":";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorChinese::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 491 of file translator_cn.h.
    {
      QCString result=fileName;
      result+=CN_SPC "";
      return result;
    }
References CN_SPC.
trFileReference() [2/2]
virtual QCString TranslatorChinese::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 491 of file translator_cn.h.
    {
      QCString result=fileName;
      result+=CN_SPC "";
      return result;
    }
References CN_SPC.
trFriends() [1/2]
virtual QCString TranslatorChinese::trFriends () [inline], [virtual]
Implements Translator.
Definition at line 454 of file translator_cn.h.
    { return ""; }
trFriends() [2/2]
virtual QCString TranslatorChinese::trFriends () [inline], [virtual]
Implements Translator.
Definition at line 454 of file translator_cn.h.
    { return ""; }
trFunctionAndProc() [1/2]
virtual QCString TranslatorChinese::trFunctionAndProc () [inline], [virtual]
VHDL functions/procedures/processes
Implements Translator.
Definition at line 1958 of file translator_cn.h.
    { return "//"; }
trFunctionAndProc() [2/2]
virtual QCString TranslatorChinese::trFunctionAndProc () [inline], [virtual]
VHDL functions/procedures/processes
Implements Translator.
Definition at line 1958 of file translator_cn.h.
    { return "//"; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorChinese::trFunctionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 386 of file translator_cn.h.
    { return ""; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorChinese::trFunctionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 386 of file translator_cn.h.
    { return ""; }
trFunctions() [1/2]
virtual QCString TranslatorChinese::trFunctions () [inline], [virtual]
Implements Translator.
Definition at line 367 of file translator_cn.h.
    { return ""; }
trFunctions() [2/2]
virtual QCString TranslatorChinese::trFunctions () [inline], [virtual]
Implements Translator.
Definition at line 367 of file translator_cn.h.
    { return ""; }
trGeneratedAt() [1/2]
virtual QCString TranslatorChinese::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
Implements Translator.
Definition at line 403 of file translator_cn.h.
    { QCString result="" CN_SPC+date;
      if (!projName.isEmpty()) result+=CN_SPC ", " CN_SPC+projName;
      result+="" CN_SPC;
      return result;
    }
References CN_SPC, and QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorChinese::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
Implements Translator.
Definition at line 403 of file translator_cn.h.
    { QCString result="" CN_SPC+date;
      if (!projName.isEmpty()) result+=CN_SPC ", " CN_SPC+projName;
      result+="" CN_SPC;
      return result;
    }
References CN_SPC, and QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorChinese::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 146 of file translator_cn.h.
    { QCString result;
      result = "" CN_SPC "Doyxgen" CN_SPC "" CN_SPC;
      if (!s.isEmpty()) result += (s+CN_SPC "" CN_SPC);
      result+= ".";
      return result;
    }
References CN_SPC, and s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorChinese::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 146 of file translator_cn.h.
    { QCString result;
      result = "" CN_SPC "Doyxgen" CN_SPC "" CN_SPC;
      if (!s.isEmpty()) result += (s+CN_SPC "" CN_SPC);
      result+= ".";
      return result;
    }
References CN_SPC, and s.
trGeneratedBy() [1/2]
virtual QCString TranslatorChinese::trGeneratedBy () [inline], [virtual]
Implements Translator.
Definition at line 436 of file translator_cn.h.
    { return ""; }
trGeneratedBy() [2/2]
virtual QCString TranslatorChinese::trGeneratedBy () [inline], [virtual]
Implements Translator.
Definition at line 436 of file translator_cn.h.
    { return ""; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorChinese::trGeneratedFromFiles (ClassDef::CompoundType compType, bool) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 639 of file translator_cn.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
       QCString result="";
      switch(compType)
      {
        case ClassDef::Class: result+=""; break;
        case ClassDef::Struct: result+=""; break;
        case ClassDef::Union: result+=""; break;
        case ClassDef::Interface: result+=""; break;
        case ClassDef::Protocol: result+=""; break;
        case ClassDef::Category: result+=""; break;
        case ClassDef::Exception: result+=""; break;
        default: break;
      }
      result+=":";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorChinese::trGeneratedFromFiles (ClassDef::CompoundType compType, bool) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 639 of file translator_cn.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
       QCString result="";
      switch(compType)
      {
        case ClassDef::Class: result+=""; break;
        case ClassDef::Struct: result+=""; break;
        case ClassDef::Union: result+=""; break;
        case ClassDef::Interface: result+=""; break;
        case ClassDef::Protocol: result+=""; break;
        case ClassDef::Category: result+=""; break;
        case ClassDef::Exception: result+=""; break;
        default: break;
      }
      result+=":";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorChinese::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1650 of file translator_cn.h.
    {
      QCString result="";
      switch(compType)
      {
        case ClassDef::Class: result+=CN_SPC ""; break;
        case ClassDef::Struct: result+=CN_SPC ""; break;
        case ClassDef::Union: result+=CN_SPC ""; break;
        case ClassDef::Interface: result+=CN_SPC ""; break;
        case ClassDef::Protocol: result+=CN_SPC ""; break;
        case ClassDef::Category: result+=CN_SPC ""; break;
        case ClassDef::Exception: result+=CN_SPC ""; break;
        default: break;
      }
      result+=CN_SPC ":";
      return result;
    }
References ClassDef::Category, ClassDef::Class, CN_SPC, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorChinese::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1650 of file translator_cn.h.
    {
      QCString result="";
      switch(compType)
      {
        case ClassDef::Class: result+=CN_SPC ""; break;
        case ClassDef::Struct: result+=CN_SPC ""; break;
        case ClassDef::Union: result+=CN_SPC ""; break;
        case ClassDef::Interface: result+=CN_SPC ""; break;
        case ClassDef::Protocol: result+=CN_SPC ""; break;
        case ClassDef::Category: result+=CN_SPC ""; break;
        case ClassDef::Exception: result+=CN_SPC ""; break;
        default: break;
      }
      result+=CN_SPC ":";
      return result;
    }
References ClassDef::Category, ClassDef::Class, CN_SPC, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorChinese::trGlobal (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1190 of file translator_cn.h.
    {
      /*
       QCString result((first_capital ? "Global" : "global"));
      if (!singular) result+="s";
      return result;
      */
      return "";
    }
trGlobal() [2/2]
virtual QCString TranslatorChinese::trGlobal (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1190 of file translator_cn.h.
    {
      /*
       QCString result((first_capital ? "Global" : "global"));
      if (!singular) result+="s";
      return result;
      */
      return "";
    }
trGlobalNamespace() [1/2]
virtual QCString TranslatorChinese::trGlobalNamespace () [inline], [virtual]
Implements Translator.
Definition at line 1708 of file translator_cn.h.
  {
    return "";
  }
trGlobalNamespace() [2/2]
virtual QCString TranslatorChinese::trGlobalNamespace () [inline], [virtual]
Implements Translator.
Definition at line 1708 of file translator_cn.h.
  {
    return "";
  }
trGotoDocumentation() [1/2]
virtual QCString TranslatorChinese::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 730 of file translator_cn.h.
    {
      return ".";
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorChinese::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 730 of file translator_cn.h.
    {
      return ".";
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorChinese::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 770 of file translator_cn.h.
    {
      return "";
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorChinese::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 770 of file translator_cn.h.
    {
      return "";
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorChinese::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 724 of file translator_cn.h.
    {
      return ".";
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorChinese::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 724 of file translator_cn.h.
    {
      return ".";
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorChinese::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 775 of file translator_cn.h.
    {
      return "";
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorChinese::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 775 of file translator_cn.h.
    {
      return "";
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorChinese::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 765 of file translator_cn.h.
    {
      return "";
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorChinese::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 765 of file translator_cn.h.
    {
      return "";
    }
trGroup() [1/2]
virtual QCString TranslatorChinese::trGroup (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1148 of file translator_cn.h.
    {
      /*
       QCString result((first_capital ? "Group" : "group"));
      if (!singular) result+="s";
      return result;
      */
      return "";
    }
trGroup() [2/2]
virtual QCString TranslatorChinese::trGroup (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1148 of file translator_cn.h.
    {
      /*
       QCString result((first_capital ? "Group" : "group"));
      if (!singular) result+="s";
      return result;
      */
      return "";
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorChinese::trHierarchicalIndex () [inline], [virtual]
Implements Translator.
Definition at line 314 of file translator_cn.h.
    { return ""; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorChinese::trHierarchicalIndex () [inline], [virtual]
Implements Translator.
Definition at line 314 of file translator_cn.h.
    { return ""; }
trImplementedFromList() [1/2]
virtual QCString TranslatorChinese::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1234 of file translator_cn.h.
    {
      /* return "Implements "+trWriteList(numEntries)+"."; */
      return "" CN_SPC+trWriteList(numEntries)+".";
    }
References CN_SPC, and trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorChinese::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1234 of file translator_cn.h.
    {
      /* return "Implements "+trWriteList(numEntries)+"."; */
      return "" CN_SPC+trWriteList(numEntries)+".";
    }
References CN_SPC, and trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorChinese::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1243 of file translator_cn.h.
    {
      /* return "Implemented in "+trWriteList(numEntries)+"."; */
      return "" CN_SPC+trWriteList(numEntries)+CN_SPC ".";
    }
References CN_SPC, and trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorChinese::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1243 of file translator_cn.h.
    {
      /* return "Implemented in "+trWriteList(numEntries)+"."; */
      return "" CN_SPC+trWriteList(numEntries)+CN_SPC ".";
    }
References CN_SPC, and trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorChinese::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 881 of file translator_cn.h.
    {
      return ":";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorChinese::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 881 of file translator_cn.h.
    {
      return ":";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorChinese::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 712 of file translator_cn.h.
    {
      return fName+CN_SPC "(Include):";
    }
References CN_SPC.
trInclDepGraph() [2/2]
virtual QCString TranslatorChinese::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 712 of file translator_cn.h.
    {
      return fName+CN_SPC "(Include):";
    }
References CN_SPC.
trIncludesFileIn() [1/2]
virtual QCString TranslatorChinese::trIncludesFileIn (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 1732 of file translator_cn.h.
  {
    return "" CN_SPC+name+CN_SPC "";
  }
References CN_SPC, and setup::name.
trIncludesFileIn() [2/2]
virtual QCString TranslatorChinese::trIncludesFileIn (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 1732 of file translator_cn.h.
  {
    return "" CN_SPC+name+CN_SPC "";
  }
References CN_SPC, and setup::name.
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorChinese::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 140 of file translator_cn.h.
    { return ","; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorChinese::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 140 of file translator_cn.h.
    { return ","; }
trInheritedByList() [1/2]
virtual QCString TranslatorChinese::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 570 of file translator_cn.h.
    {
      return "" CN_SPC+trWriteList(numEntries)+CN_SPC ".";
    }
References CN_SPC, and trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorChinese::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 570 of file translator_cn.h.
    {
      return "" CN_SPC+trWriteList(numEntries)+CN_SPC ".";
    }
References CN_SPC, and trWriteList().
trInheritedFrom() [1/2]
virtual QCString TranslatorChinese::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1817 of file translator_cn.h.
    { return QCString(members)+CN_SPC "" CN_SPC+what; }
References CN_SPC.
trInheritedFrom() [2/2]
virtual QCString TranslatorChinese::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1817 of file translator_cn.h.
    { return QCString(members)+CN_SPC "" CN_SPC+what; }
References CN_SPC.
trInheritsList() [1/2]
virtual QCString TranslatorChinese::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 564 of file translator_cn.h.
    { return "" CN_SPC+trWriteList(numEntries)+CN_SPC "."; }
References CN_SPC, and trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorChinese::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 564 of file translator_cn.h.
    { return "" CN_SPC+trWriteList(numEntries)+CN_SPC "."; }
References CN_SPC, and trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorChinese::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 754 of file translator_cn.h.
    {
      return ":";
    }
trInitialValue() [2/2]
virtual QCString TranslatorChinese::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 754 of file translator_cn.h.
    {
      return ":";
    }
trInstanceMethods() [1/2]
virtual QCString TranslatorChinese::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1871 of file translator_cn.h.
    {
      return "";
    }
trInstanceMethods() [2/2]
virtual QCString TranslatorChinese::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1871 of file translator_cn.h.
    {
      return "";
    }
trInterfaceDocumentation() [1/2]
virtual QCString TranslatorChinese::trInterfaceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2076 of file translator_cn.h.
    {
        return "";
    }
trInterfaceDocumentation() [2/2]
virtual QCString TranslatorChinese::trInterfaceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2076 of file translator_cn.h.
    {
        return "";
    }
trInterfaceHierarchy() [1/2]
virtual QCString TranslatorChinese::trInterfaceHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2068 of file translator_cn.h.
    {
        return "";
    }
trInterfaceHierarchy() [2/2]
virtual QCString TranslatorChinese::trInterfaceHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 2068 of file translator_cn.h.
    {
        return "";
    }
trInterfaceHierarchyDescription() [1/2]
virtual QCString TranslatorChinese::trInterfaceHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2072 of file translator_cn.h.
    {
        return ":";
    }
trInterfaceHierarchyDescription() [2/2]
virtual QCString TranslatorChinese::trInterfaceHierarchyDescription () [inline], [virtual]
Implements Translator.
Definition at line 2072 of file translator_cn.h.
    {
        return ":";
    }
trInterfaceIndex() [1/2]
virtual QCString TranslatorChinese::trInterfaceIndex () [inline], [virtual]
Implements Translator.
Definition at line 2056 of file translator_cn.h.
    {
        return "";
    }
trInterfaceIndex() [2/2]
virtual QCString TranslatorChinese::trInterfaceIndex () [inline], [virtual]
Implements Translator.
Definition at line 2056 of file translator_cn.h.
    {
        return "";
    }
trInterfaceList() [1/2]
virtual QCString TranslatorChinese::trInterfaceList () [inline], [virtual]
Implements Translator.
Definition at line 2060 of file translator_cn.h.
    {
        return "";
    }
trInterfaceList() [2/2]
virtual QCString TranslatorChinese::trInterfaceList () [inline], [virtual]
Implements Translator.
Definition at line 2060 of file translator_cn.h.
    {
        return "";
    }
trInterfaceListDescription() [1/2]
virtual QCString TranslatorChinese::trInterfaceListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2064 of file translator_cn.h.
    {
        return ":";
    }
trInterfaceListDescription() [2/2]
virtual QCString TranslatorChinese::trInterfaceListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2064 of file translator_cn.h.
    {
        return ":";
    }
trInterfaces() [1/2]
virtual QCString TranslatorChinese::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1888 of file translator_cn.h.
    { return ""; }
trInterfaces() [2/2]
virtual QCString TranslatorChinese::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 1888 of file translator_cn.h.
    { return ""; }
trInvariant() [1/2]
virtual QCString TranslatorChinese::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 748 of file translator_cn.h.
    {
      return "";
    }
trInvariant() [2/2]
virtual QCString TranslatorChinese::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 748 of file translator_cn.h.
    {
      return "";
    }
trISOLang() [1/2]
virtual QCString TranslatorChinese::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 58 of file translator_cn.h.
    {
      return "zh";
    }
trISOLang() [2/2]
virtual QCString TranslatorChinese::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 58 of file translator_cn.h.
    {
      return "zh";
    }
trLegend() [1/2]
virtual QCString TranslatorChinese::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 959 of file translator_cn.h.
    {
      return "";
    }
trLegend() [2/2]
virtual QCString TranslatorChinese::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 959 of file translator_cn.h.
    {
      return "";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorChinese::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 902 of file translator_cn.h.
    {
      return "" CN_SPC "doxygen" CN_SPC ".<p>\n"
        ":\n"
        "\\code\n"
        "/*! Invisible */\n"
        "class Invisible { };\n\n"
        "/*! Truncated */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* doxygen */\n"
        "class Undocumented { };\n\n"
        "/*! public */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! */\n"
        "template<class T> class Templ { };\n\n"
        "/*! protected */\n"
        "class ProtectedBase { };\n\n"
        "/*! private */\n"
        "class PrivateBase { };\n\n"
        "/*! Inherited */\n"
        "class Used { };\n\n"
        "/*! */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        ":"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        ":\n"
        "</p>\n"
        "<ul>\n"
        "<li>% .</li>\n"
        "<li>% .</li>\n"
        "<li>% .</li>\n"
        "<li>% ."
        "%.</li>\n"
        "</ul>\n"
        "<p>\n"
        ":\n"
        "</p>\n"
        "<ul>\n"
        "<li>% public .</li>\n"
        "<li>% protected .</li>\n"
        "<li>% privated .</li>\n"
        "<li>%. ,.</li>\n"
        "<li>%. .</li>\n"
        "</ul>\n";
    }
References CN_SPC, and getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorChinese::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 902 of file translator_cn.h.
    {
      return "" CN_SPC "doxygen" CN_SPC ".<p>\n"
        ":\n"
        "\\code\n"
        "/*! Invisible */\n"
        "class Invisible { };\n\n"
        "/*! Truncated */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* doxygen */\n"
        "class Undocumented { };\n\n"
        "/*! public */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! */\n"
        "template<class T> class Templ { };\n\n"
        "/*! protected */\n"
        "class ProtectedBase { };\n\n"
        "/*! private */\n"
        "class PrivateBase { };\n\n"
        "/*! Inherited */\n"
        "class Used { };\n\n"
        "/*! */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        ":"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        ":\n"
        "</p>\n"
        "<ul>\n"
        "<li>% .</li>\n"
        "<li>% .</li>\n"
        "<li>% .</li>\n"
        "<li>% ."
        "%.</li>\n"
        "</ul>\n"
        "<p>\n"
        ":\n"
        "</p>\n"
        "<ul>\n"
        "<li>% public .</li>\n"
        "<li>% protected .</li>\n"
        "<li>% privated .</li>\n"
        "<li>%. ,.</li>\n"
        "<li>%. .</li>\n"
        "</ul>\n";
    }
References CN_SPC, and getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorChinese::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 896 of file translator_cn.h.
    {
      return "";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorChinese::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 896 of file translator_cn.h.
    {
      return "";
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorChinese::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 128 of file translator_cn.h.
    { return ""; }
trListOfAllMembers() [2/2]
virtual QCString TranslatorChinese::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 128 of file translator_cn.h.
    { return ""; }
trLoading() [1/2]
virtual QCString TranslatorChinese::trLoading () [inline], [virtual]
Implements Translator.
Definition at line 1703 of file translator_cn.h.
  {
    return "...";
  }
trLoading() [2/2]
virtual QCString TranslatorChinese::trLoading () [inline], [virtual]
Implements Translator.
Definition at line 1703 of file translator_cn.h.
  {
    return "...";
  }
trMainPage() [1/2]
virtual QCString TranslatorChinese::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 669 of file translator_cn.h.
    { return ""; }
trMainPage() [2/2]
virtual QCString TranslatorChinese::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 669 of file translator_cn.h.
    { return ""; }
trMember() [1/2]
virtual QCString TranslatorChinese::trMember (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1176 of file translator_cn.h.
    {
      /*
       QCString result((first_capital ? "Member" : "member"));
      if (!singular) result+="s";
      return result;
      */
      return "";
    }
trMember() [2/2]
virtual QCString TranslatorChinese::trMember (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1176 of file translator_cn.h.
    {
      /*
       QCString result((first_capital ? "Member" : "member"));
      if (!singular) result+="s";
      return result;
      */
      return "";
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorChinese::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 111 of file translator_cn.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorChinese::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 111 of file translator_cn.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "";
      }
      else
      {
        return "";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorChinese::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 103 of file translator_cn.h.
    { return ""; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorChinese::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 103 of file translator_cn.h.
    { return ""; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorChinese::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member function.
Implements Translator.
Definition at line 107 of file translator_cn.h.
    { return ""; }
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorChinese::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member function.
Implements Translator.
Definition at line 107 of file translator_cn.h.
    { return ""; }
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorChinese::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1492 of file translator_cn.h.
    { return "/"; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorChinese::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1492 of file translator_cn.h.
    { return "/"; }
trMemberList() [1/2]
virtual QCString TranslatorChinese::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 132 of file translator_cn.h.
    { return ""; }
trMemberList() [2/2]
virtual QCString TranslatorChinese::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 132 of file translator_cn.h.
    { return ""; }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorChinese::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 99 of file translator_cn.h.
    { return ""; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorChinese::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 99 of file translator_cn.h.
    { return ""; }
trMethodDocumentation() [1/2]
virtual QCString TranslatorChinese::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1878 of file translator_cn.h.
    {
      return "";
    }
trMethodDocumentation() [2/2]
virtual QCString TranslatorChinese::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1878 of file translator_cn.h.
    {
      return "";
    }
trModule() [1/2]
virtual QCString TranslatorChinese::trModule (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1640 of file translator_cn.h.
    {
      // QCString result((first_capital ? "Module" : "module"));
      // if (!singular) result+="s";
      // return result;
      return "";
    }
trModule() [2/2]
virtual QCString TranslatorChinese::trModule (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1640 of file translator_cn.h.
    {
      // QCString result((first_capital ? "Module" : "module"));
      // if (!singular) result+="s";
      // return result;
      return "";
    }
trModuleDocumentation() [1/2]
virtual QCString TranslatorChinese::trModuleDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 331 of file translator_cn.h.
    { return ""; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorChinese::trModuleDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 331 of file translator_cn.h.
    { return ""; }
trModuleIndex() [1/2]
virtual QCString TranslatorChinese::trModuleIndex () [inline], [virtual]
Implements Translator.
Definition at line 311 of file translator_cn.h.
    { return ""; }
trModuleIndex() [2/2]
virtual QCString TranslatorChinese::trModuleIndex () [inline], [virtual]
Implements Translator.
Definition at line 311 of file translator_cn.h.
    { return ""; }
trModuleReference() [1/2]
virtual QCString TranslatorChinese::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1596 of file translator_cn.h.
    {
      QCString result=namespaceName;
      result += CN_SPC "";
      return result;
    }
References CN_SPC.
trModuleReference() [2/2]
virtual QCString TranslatorChinese::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1596 of file translator_cn.h.
    {
      QCString result=namespaceName;
      result += CN_SPC "";
      return result;
    }
References CN_SPC.
trModules() [1/2]
virtual QCString TranslatorChinese::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 171 of file translator_cn.h.
    { return ""; }
trModules() [2/2]
virtual QCString TranslatorChinese::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 171 of file translator_cn.h.
    { return ""; }
trModulesDescription() [1/2]
virtual QCString TranslatorChinese::trModulesDescription () [inline], [virtual]
Implements Translator.
Definition at line 305 of file translator_cn.h.
    { return ":"; }
trModulesDescription() [2/2]
virtual QCString TranslatorChinese::trModulesDescription () [inline], [virtual]
Implements Translator.
Definition at line 305 of file translator_cn.h.
    { return ":"; }
trModulesIndex() [1/2]
virtual QCString TranslatorChinese::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1632 of file translator_cn.h.
    { return ""; }
trModulesIndex() [2/2]
virtual QCString TranslatorChinese::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1632 of file translator_cn.h.
    { return ""; }
trModulesList() [1/2]
virtual QCString TranslatorChinese::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1561 of file translator_cn.h.
    { return ""; }
trModulesList() [2/2]
virtual QCString TranslatorChinese::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1561 of file translator_cn.h.
    { return ""; }
trModulesListDescription() [1/2]
virtual QCString TranslatorChinese::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1565 of file translator_cn.h.
    {
      QCString result="";
      if (!extractAll) result+="";
      result+=":";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorChinese::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1565 of file translator_cn.h.
    {
      QCString result="";
      if (!extractAll) result+="";
      result+=":";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorChinese::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1608 of file translator_cn.h.
    {
      // QCString result="Here is a list of all ";
      // if (!extractAll) result+="documented ";
      // result+="module members with links to ";
      // if (extractAll)
      // {
      // result+="the module documentation for each member:";
      // }
      // else
      // {
      // result+="the modules they belong to:";
      // }
      // return result;
      if(!extractAll) {
        return ":";
      } else {
        return ":";
      }
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorChinese::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1608 of file translator_cn.h.
    {
      // QCString result="Here is a list of all ";
      // if (!extractAll) result+="documented ";
      // result+="module members with links to ";
      // if (extractAll)
      // {
      // result+="the module documentation for each member:";
      // }
      // else
      // {
      // result+="the modules they belong to:";
      // }
      // return result;
      if(!extractAll) {
        return ":";
      } else {
        return ":";
      }
    }
trModulesMembers() [1/2]
virtual QCString TranslatorChinese::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1604 of file translator_cn.h.
    { return ""; }
trModulesMembers() [2/2]
virtual QCString TranslatorChinese::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1604 of file translator_cn.h.
    { return ""; }
trMonth() [1/2]
virtual QCString TranslatorChinese::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1762 of file translator_cn.h.
  {
    static const char *months_short[] = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" };
    static const char *months_full[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
    return full? months_full[month-1] : months_short[month-1];
  }
trMonth() [2/2]
virtual QCString TranslatorChinese::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1762 of file translator_cn.h.
  {
    static const char *months_short[] = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" };
    static const char *months_full[] = { "", "", "", "", "", "", "", "", "", "", "", "" };
    return full? months_full[month-1] : months_short[month-1];
  }
trMore() [1/2]
virtual QCString TranslatorChinese::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 124 of file translator_cn.h.
    { return "..."; }
trMore() [2/2]
virtual QCString TranslatorChinese::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 124 of file translator_cn.h.
    { return "..."; }
trNamespace() [1/2]
virtual QCString TranslatorChinese::trNamespace (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1134 of file translator_cn.h.
    {
      /*
       QCString result((first_capital ? "Namespace" : "namespace"));
      if (!singular) result+="s";
      return result;
      */
      return "";
    }
trNamespace() [2/2]
virtual QCString TranslatorChinese::trNamespace (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1134 of file translator_cn.h.
    {
      /*
       QCString result((first_capital ? "Namespace" : "namespace"));
      if (!singular) result+="s";
      return result;
      */
      return "";
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorChinese::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 617 of file translator_cn.h.
    { return ""; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorChinese::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 617 of file translator_cn.h.
    { return ""; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorChinese::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 611 of file translator_cn.h.
    { return ""; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorChinese::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 611 of file translator_cn.h.
    { return ""; }
trNamespaceList() [1/2]
virtual QCString TranslatorChinese::trNamespaceList () [inline], [virtual]
Implements Translator.
Definition at line 443 of file translator_cn.h.
    { return ""; }
trNamespaceList() [2/2]
virtual QCString TranslatorChinese::trNamespaceList () [inline], [virtual]
Implements Translator.
Definition at line 443 of file translator_cn.h.
    { return ""; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorChinese::trNamespaceListDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 446 of file translator_cn.h.
    {
       QCString result="";
      if (!extractAll) result+="";
      result+=",:";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorChinese::trNamespaceListDescription (bool extractAll) [inline], [virtual]
Implements Translator.
Definition at line 446 of file translator_cn.h.
    {
       QCString result="";
      if (!extractAll) result+="";
      result+=",:";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorChinese::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 596 of file translator_cn.h.
    {
       QCString result="";
      if (!extractAll) result+="";
      result+="";
      if (extractAll)
        result+=":";
      else
        result+=":";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorChinese::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 596 of file translator_cn.h.
    {
       QCString result="";
      if (!extractAll) result+="";
      result+="";
      if (extractAll)
        result+=":";
      else
        result+=":";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorChinese::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 592 of file translator_cn.h.
    { return ""; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorChinese::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 592 of file translator_cn.h.
    { return ""; }
trNamespaceReference() [1/2]
virtual QCString TranslatorChinese::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 499 of file translator_cn.h.
    { QCString result=namespaceName;
      result+=CN_SPC "";
      return result;
    }
References CN_SPC.
trNamespaceReference() [2/2]
virtual QCString TranslatorChinese::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 499 of file translator_cn.h.
    { QCString result=namespaceName;
      result+=CN_SPC "";
      return result;
    }
References CN_SPC.
trNamespaces() [1/2]
virtual QCString TranslatorChinese::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 627 of file translator_cn.h.
    {
      return "";
    }
trNamespaces() [2/2]
virtual QCString TranslatorChinese::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 627 of file translator_cn.h.
    {
      return "";
    }
trNoMatches() [1/2]
virtual QCString TranslatorChinese::trNoMatches () [inline], [virtual]
Implements Translator.
Definition at line 1718 of file translator_cn.h.
  {
    return "";
  }
trNoMatches() [2/2]
virtual QCString TranslatorChinese::trNoMatches () [inline], [virtual]
Implements Translator.
Definition at line 1718 of file translator_cn.h.
  {
    return "";
  }
trNote() [1/2]
virtual QCString TranslatorChinese::trNote () [inline], [virtual]
Implements Translator.
Definition at line 789 of file translator_cn.h.
    {
      return "";
    }
trNote() [2/2]
virtual QCString TranslatorChinese::trNote () [inline], [virtual]
Implements Translator.
Definition at line 789 of file translator_cn.h.
    {
      return "";
    }
trOperationDocumentation() [1/2]
virtual QCString TranslatorChinese::trOperationDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2146 of file translator_cn.h.
    {
        return "";
    }
trOperationDocumentation() [2/2]
virtual QCString TranslatorChinese::trOperationDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2146 of file translator_cn.h.
    {
        return "";
    }
trOperations() [1/2]
virtual QCString TranslatorChinese::trOperations () [inline], [virtual]
Implements Translator.
Definition at line 2142 of file translator_cn.h.
    {
        return "";
    }
trOperations() [2/2]
virtual QCString TranslatorChinese::trOperations () [inline], [virtual]
Implements Translator.
Definition at line 2142 of file translator_cn.h.
    {
        return "";
    }
trOverloadText() [1/2]
virtual QCString TranslatorChinese::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1463 of file translator_cn.h.
    {
      return "."
             ".";
    }
trOverloadText() [2/2]
virtual QCString TranslatorChinese::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1463 of file translator_cn.h.
    {
      return "."
             ".";
    }
trPackage() [1/2]
virtual QCString TranslatorChinese::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1014 of file translator_cn.h.
    {
      return "" CN_SPC+name;
    }
References CN_SPC, and setup::name.
trPackage() [2/2]
virtual QCString TranslatorChinese::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1014 of file translator_cn.h.
    {
      return "" CN_SPC+name;
    }
References CN_SPC, and setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorChinese::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1326 of file translator_cn.h.
    {
      return "";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorChinese::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1326 of file translator_cn.h.
    {
      return "";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorChinese::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1306 of file translator_cn.h.
    {
      return "";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorChinese::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1306 of file translator_cn.h.
    {
      return "";
    }
trPackageListDescription() [1/2]
virtual QCString TranslatorChinese::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1021 of file translator_cn.h.
    {
       return "():";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorChinese::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1021 of file translator_cn.h.
    {
       return "():";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorChinese::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1310 of file translator_cn.h.
    {
      return "";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorChinese::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1310 of file translator_cn.h.
    {
      return "";
    }
trPackages() [1/2]
virtual QCString TranslatorChinese::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1027 of file translator_cn.h.
    {
      return "";
    }
trPackages() [2/2]
virtual QCString TranslatorChinese::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1027 of file translator_cn.h.
    {
      return "";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorChinese::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1298 of file translator_cn.h.
    {
      return "";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorChinese::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1298 of file translator_cn.h.
    {
      return "";
    }
trPage() [1/2]
virtual QCString TranslatorChinese::trPage (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1162 of file translator_cn.h.
    {
      /*
       QCString result((first_capital ? "Page" : "page"));
      if (!singular) result+="s";
      return result;
      */
      return "";
    }
trPage() [2/2]
virtual QCString TranslatorChinese::trPage (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1162 of file translator_cn.h.
    {
      /*
       QCString result((first_capital ? "Page" : "page"));
      if (!singular) result+="s";
      return result;
      */
      return "";
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorChinese::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 675 of file translator_cn.h.
    { return "p."; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorChinese::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 675 of file translator_cn.h.
    { return "p."; }
trPageIndex() [1/2]
virtual QCString TranslatorChinese::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 780 of file translator_cn.h.
    {
      return "";
    }
trPageIndex() [2/2]
virtual QCString TranslatorChinese::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 780 of file translator_cn.h.
    {
      return "";
    }
trPanelSynchronisationTooltip() [1/2]
virtual QCString TranslatorChinese::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1836 of file translator_cn.h.
    {
      QCString opt = enable ? "" : "";
      return "" CN_SPC+opt+CN_SPC "";
    }
References CN_SPC.
trPanelSynchronisationTooltip() [2/2]
virtual QCString TranslatorChinese::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1836 of file translator_cn.h.
    {
      QCString opt = enable ? "" : "";
      return "" CN_SPC+opt+CN_SPC "";
    }
References CN_SPC.
trParameters() [1/2]
virtual QCString TranslatorChinese::trParameters () [inline], [virtual]
Implements Translator.
Definition at line 430 of file translator_cn.h.
    { return ""; }
trParameters() [2/2]
virtual QCString TranslatorChinese::trParameters () [inline], [virtual]
Implements Translator.
Definition at line 430 of file translator_cn.h.
    { return ""; }
trPostcondition() [1/2]
virtual QCString TranslatorChinese::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 742 of file translator_cn.h.
    {
      return "";
    }
trPostcondition() [2/2]
virtual QCString TranslatorChinese::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 742 of file translator_cn.h.
    {
      return "";
    }
trPrecondition() [1/2]
virtual QCString TranslatorChinese::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 736 of file translator_cn.h.
    {
      return "";
    }
trPrecondition() [2/2]
virtual QCString TranslatorChinese::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 736 of file translator_cn.h.
    {
      return "";
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorChinese::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 835 of file translator_cn.h.
    {
      return "Private ";
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorChinese::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 835 of file translator_cn.h.
    {
      return "Private ";
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorChinese::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 527 of file translator_cn.h.
    { return "Private "; }
trPrivateMembers() [2/2]
virtual QCString TranslatorChinese::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 527 of file translator_cn.h.
    { return "Private "; }
trPrivateSlots() [1/2]
virtual QCString TranslatorChinese::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 530 of file translator_cn.h.
    { return "Private "; }
trPrivateSlots() [2/2]
virtual QCString TranslatorChinese::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 530 of file translator_cn.h.
    { return "Private "; }
trPrivateTypes() [1/2]
virtual QCString TranslatorChinese::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 830 of file translator_cn.h.
    {
      return "Private ";
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorChinese::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 830 of file translator_cn.h.
    {
      return "Private ";
    }
trProperties() [1/2]
virtual QCString TranslatorChinese::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 985 of file translator_cn.h.
    {
      return "";
    }
trProperties() [2/2]
virtual QCString TranslatorChinese::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 985 of file translator_cn.h.
    {
      return "";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorChinese::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 991 of file translator_cn.h.
    {
      return "";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorChinese::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 991 of file translator_cn.h.
    {
      return "";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorChinese::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 820 of file translator_cn.h.
    {
      return "Protected ";
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorChinese::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 820 of file translator_cn.h.
    {
      return "Protected ";
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorChinese::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 518 of file translator_cn.h.
    { return "Protected "; }
trProtectedMembers() [2/2]
virtual QCString TranslatorChinese::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 518 of file translator_cn.h.
    { return "Protected "; }
trProtectedSlots() [1/2]
virtual QCString TranslatorChinese::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 521 of file translator_cn.h.
    { return "Protected "; }
trProtectedSlots() [2/2]
virtual QCString TranslatorChinese::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 521 of file translator_cn.h.
    { return "Protected "; }
trProtectedTypes() [1/2]
virtual QCString TranslatorChinese::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 815 of file translator_cn.h.
    {
      return "Protected ";
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorChinese::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 815 of file translator_cn.h.
    {
      return "Protected ";
    }
trProvidedByCategory() [1/2]
virtual QCString TranslatorChinese::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1846 of file translator_cn.h.
    {
      return " category @0 .";
    }
trProvidedByCategory() [2/2]
virtual QCString TranslatorChinese::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1846 of file translator_cn.h.
    {
      return " category @0 .";
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorChinese::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 799 of file translator_cn.h.
    {
       if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
       {
         return "";
       }
       else {
         return "Public ";
       }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorChinese::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 799 of file translator_cn.h.
    {
       if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
       {
         return "";
       }
       else {
         return "Public ";
       }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorChinese::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 506 of file translator_cn.h.
    { return "Public "; }
trPublicMembers() [2/2]
virtual QCString TranslatorChinese::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 506 of file translator_cn.h.
    { return "Public "; }
trPublicSlots() [1/2]
virtual QCString TranslatorChinese::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 509 of file translator_cn.h.
    { return "Public "; }
trPublicSlots() [2/2]
virtual QCString TranslatorChinese::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 509 of file translator_cn.h.
    { return "Public "; }
trPublicTypes() [1/2]
virtual QCString TranslatorChinese::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 794 of file translator_cn.h.
    {
      return "Public ";
    }
trPublicTypes() [2/2]
virtual QCString TranslatorChinese::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 794 of file translator_cn.h.
    {
      return "Public ";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorChinese::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 866 of file translator_cn.h.
    {
      return "";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorChinese::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 866 of file translator_cn.h.
    {
      return "";
    }
trReferenceManual() [1/2]
virtual QCString TranslatorChinese::trReferenceManual () [inline], [virtual]
Implements Translator.
Definition at line 355 of file translator_cn.h.
    { return ""; }
trReferenceManual() [2/2]
virtual QCString TranslatorChinese::trReferenceManual () [inline], [virtual]
Implements Translator.
Definition at line 355 of file translator_cn.h.
    { return ""; }
trReferences() [1/2]
virtual QCString TranslatorChinese::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1222 of file translator_cn.h.
    {
      return "";
    }
trReferences() [2/2]
virtual QCString TranslatorChinese::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1222 of file translator_cn.h.
    {
      return "";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorChinese::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 578 of file translator_cn.h.
    {
      return "" CN_SPC+trWriteList(numEntries)+CN_SPC ".";
    }
References CN_SPC, and trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorChinese::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 578 of file translator_cn.h.
    {
      return "" CN_SPC+trWriteList(numEntries)+CN_SPC ".";
    }
References CN_SPC, and trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorChinese::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 586 of file translator_cn.h.
    {
      return "" CN_SPC+trWriteList(numEntries)+CN_SPC ".";
    }
References CN_SPC, and trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorChinese::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 586 of file translator_cn.h.
    {
      return "" CN_SPC+trWriteList(numEntries)+CN_SPC ".";
    }
References CN_SPC, and trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorChinese::trRelatedFunctionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 461 of file translator_cn.h.
    { return ""; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorChinese::trRelatedFunctionDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 461 of file translator_cn.h.
    { return ""; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorChinese::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 85 of file translator_cn.h.
    { return ""; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorChinese::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 85 of file translator_cn.h.
    { return ""; }
trRelatedPages() [1/2]
virtual QCString TranslatorChinese::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 215 of file translator_cn.h.
    { return ""; }
trRelatedPages() [2/2]
virtual QCString TranslatorChinese::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 215 of file translator_cn.h.
    { return ""; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorChinese::trRelatedPagesDescription () [inline], [virtual]
Implements Translator.
Definition at line 302 of file translator_cn.h.
    { return ":"; }
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorChinese::trRelatedPagesDescription () [inline], [virtual]
Implements Translator.
Definition at line 302 of file translator_cn.h.
    { return ":"; }
trRelatedSubscript() [1/2]
virtual QCString TranslatorChinese::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 89 of file translator_cn.h.
    { return "(: .)"; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorChinese::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 89 of file translator_cn.h.
    { return "(: .)"; }
trRemarks() [1/2]
virtual QCString TranslatorChinese::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 871 of file translator_cn.h.
    {
      return "";
    }
trRemarks() [2/2]
virtual QCString TranslatorChinese::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 871 of file translator_cn.h.
    {
      return "";
    }
trReturns() [1/2]
virtual QCString TranslatorChinese::trReturns () [inline], [virtual]
Implements Translator.
Definition at line 424 of file translator_cn.h.
    { return ""; }
trReturns() [2/2]
virtual QCString TranslatorChinese::trReturns () [inline], [virtual]
Implements Translator.
Definition at line 424 of file translator_cn.h.
    { return ""; }
trReturnValues() [1/2]
virtual QCString TranslatorChinese::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 664 of file translator_cn.h.
    { return ""; }
trReturnValues() [2/2]
virtual QCString TranslatorChinese::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 664 of file translator_cn.h.
    { return ""; }
trRTFansicp() [1/2]
virtual QCString TranslatorChinese::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1080 of file translator_cn.h.
    {
      return "936";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorChinese::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1080 of file translator_cn.h.
    {
      return "936";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorChinese::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1088 of file translator_cn.h.
    {
      return "134";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorChinese::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1088 of file translator_cn.h.
    {
      return "134";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorChinese::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1095 of file translator_cn.h.
    {
      return "";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorChinese::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1095 of file translator_cn.h.
    {
      return "";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorChinese::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1256 of file translator_cn.h.
    {
      /* return "Table of Contents"; */
      return "";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorChinese::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1256 of file translator_cn.h.
    {
      /* return "Table of Contents"; */
      return "";
    }
trSearch() [1/2]
virtual QCString TranslatorChinese::trSearch () [inline], [virtual]
Implements Translator.
Definition at line 222 of file translator_cn.h.
    { return ""; }
trSearch() [2/2]
virtual QCString TranslatorChinese::trSearch () [inline], [virtual]
Implements Translator.
Definition at line 222 of file translator_cn.h.
    { return ""; }
trSearching() [1/2]
virtual QCString TranslatorChinese::trSearching () [inline], [virtual]
Implements Translator.
Definition at line 1713 of file translator_cn.h.
  {
    return "...";
  }
trSearching() [2/2]
virtual QCString TranslatorChinese::trSearching () [inline], [virtual]
Implements Translator.
Definition at line 1713 of file translator_cn.h.
  {
    return "...";
  }
trSearchMatches() [1/2]
virtual QCString TranslatorChinese::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1396 of file translator_cn.h.
    {
      return ":";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorChinese::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1396 of file translator_cn.h.
    {
      return ":";
    }
trSearchResults() [1/2]
virtual QCString TranslatorChinese::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1377 of file translator_cn.h.
    {
      if (numDocuments==0)
      {
        return ",.";
      }
      else if (numDocuments==1)
      {
        return "<b>1</b>.";
      }
      else
      {
        return "<b>$num</b>."
               ".";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorChinese::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1377 of file translator_cn.h.
    {
      if (numDocuments==0)
      {
        return ",.";
      }
      else if (numDocuments==1)
      {
        return "<b>1</b>.";
      }
      else
      {
        return "<b>$num</b>."
               ".";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorChinese::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1364 of file translator_cn.h.
    {
      return "";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorChinese::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1364 of file translator_cn.h.
    {
      return "";
    }
trSeeAlso() [1/2]
virtual QCString TranslatorChinese::trSeeAlso () [inline], [virtual]
Implements Translator.
Definition at line 427 of file translator_cn.h.
    { return ""; }
trSeeAlso() [2/2]
virtual QCString TranslatorChinese::trSeeAlso () [inline], [virtual]
Implements Translator.
Definition at line 427 of file translator_cn.h.
    { return ""; }
trSequenceDocumentation() [1/2]
virtual QCString TranslatorChinese::trSequenceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2040 of file translator_cn.h.
    {
        return "";
    }
trSequenceDocumentation() [2/2]
virtual QCString TranslatorChinese::trSequenceDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2040 of file translator_cn.h.
    {
        return "";
    }
trSequences() [1/2]
virtual QCString TranslatorChinese::trSequences () [inline], [virtual]
Implements Translator.
Definition at line 2036 of file translator_cn.h.
    {
        return "";
    }
trSequences() [2/2]
virtual QCString TranslatorChinese::trSequences () [inline], [virtual]
Implements Translator.
Definition at line 2036 of file translator_cn.h.
    {
        return "";
    }
trServiceGeneratedFromFiles() [1/2]
virtual QCString TranslatorChinese::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 1921 of file translator_cn.h.
    {
      // single is true implies a single file
      return ":";
    }
trServiceGeneratedFromFiles() [2/2]
virtual QCString TranslatorChinese::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 1921 of file translator_cn.h.
    {
      // single is true implies a single file
      return ":";
    }
trServiceReference() [1/2]
virtual QCString TranslatorChinese::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 1907 of file translator_cn.h.
    {
      QCString result=sName;
      result+= CN_SPC "";
      return result;
    }
References CN_SPC.
trServiceReference() [2/2]
virtual QCString TranslatorChinese::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 1907 of file translator_cn.h.
    {
      QCString result=sName;
      result+= CN_SPC "";
      return result;
    }
References CN_SPC.
trServices() [1/2]
virtual QCString TranslatorChinese::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1892 of file translator_cn.h.
    { return ""; }
trServices() [2/2]
virtual QCString TranslatorChinese::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 1892 of file translator_cn.h.
    { return ""; }
trSignals() [1/2]
virtual QCString TranslatorChinese::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 512 of file translator_cn.h.
    { return ""; }
trSignals() [2/2]
virtual QCString TranslatorChinese::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 512 of file translator_cn.h.
    { return ""; }
trSince() [1/2]
virtual QCString TranslatorChinese::trSince () [inline], [virtual]
Implements Translator.
Definition at line 886 of file translator_cn.h.
    {
      return "";
    }
trSince() [2/2]
virtual QCString TranslatorChinese::trSince () [inline], [virtual]
Implements Translator.
Definition at line 886 of file translator_cn.h.
    {
      return "";
    }
trSingletonGeneratedFromFiles() [1/2]
virtual QCString TranslatorChinese::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 1927 of file translator_cn.h.
    {
      // single is true implies a single file
      return ":";
    }
trSingletonGeneratedFromFiles() [2/2]
virtual QCString TranslatorChinese::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 1927 of file translator_cn.h.
    {
      // single is true implies a single file
      return ":";
    }
trSingletonReference() [1/2]
virtual QCString TranslatorChinese::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 1914 of file translator_cn.h.
    {
      QCString result=sName;
      result+= CN_SPC "";
      return result;
    }
References CN_SPC.
trSingletonReference() [2/2]
virtual QCString TranslatorChinese::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 1914 of file translator_cn.h.
    {
      QCString result=sName;
      result+= CN_SPC "";
      return result;
    }
References CN_SPC.
trSliceInterfaces() [1/2]
virtual QCString TranslatorChinese::trSliceInterfaces () [inline], [virtual]
Implements Translator.
Definition at line 2052 of file translator_cn.h.
    {
        return "";
    }
trSliceInterfaces() [2/2]
virtual QCString TranslatorChinese::trSliceInterfaces () [inline], [virtual]
Implements Translator.
Definition at line 2052 of file translator_cn.h.
    {
        return "";
    }
trSourceFile() [1/2]
virtual QCString TranslatorChinese::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1407 of file translator_cn.h.
    {
      /* return filename + " Source File"; */
      return filename + CN_SPC "";
    }
References CN_SPC, and filename.
trSourceFile() [2/2]
virtual QCString TranslatorChinese::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1407 of file translator_cn.h.
    {
      /* return filename + " Source File"; */
      return filename + CN_SPC "";
    }
References CN_SPC, and filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorChinese::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1334 of file translator_cn.h.
    {
      return "";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorChinese::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1334 of file translator_cn.h.
    {
      return "";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorChinese::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1318 of file translator_cn.h.
    {
      return "";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorChinese::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1318 of file translator_cn.h.
    {
      return "";
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorChinese::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 840 of file translator_cn.h.
    {
      return " Private ";
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorChinese::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 840 of file translator_cn.h.
    {
      return " Private ";
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorChinese::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 533 of file translator_cn.h.
    { return " Private "; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorChinese::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 533 of file translator_cn.h.
    { return " Private "; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorChinese::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 825 of file translator_cn.h.
    {
      return " Protected ";
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorChinese::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 825 of file translator_cn.h.
    {
      return " Protected ";
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorChinese::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 524 of file translator_cn.h.
    { return " Protected "; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorChinese::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 524 of file translator_cn.h.
    { return " Protected "; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorChinese::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 810 of file translator_cn.h.
    {
      return " Public ";
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorChinese::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 810 of file translator_cn.h.
    {
      return " Public ";
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorChinese::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 515 of file translator_cn.h.
    { return " Public "; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorChinese::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 515 of file translator_cn.h.
    { return " Public "; }
trStructDocumentation() [1/2]
virtual QCString TranslatorChinese::trStructDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2096 of file translator_cn.h.
    {
        return "";
    }
trStructDocumentation() [2/2]
virtual QCString TranslatorChinese::trStructDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 2096 of file translator_cn.h.
    {
        return "";
    }
trStructIndex() [1/2]
virtual QCString TranslatorChinese::trStructIndex () [inline], [virtual]
Implements Translator.
Definition at line 2084 of file translator_cn.h.
    {
        return "";
    }
trStructIndex() [2/2]
virtual QCString TranslatorChinese::trStructIndex () [inline], [virtual]
Implements Translator.
Definition at line 2084 of file translator_cn.h.
    {
        return "";
    }
trStructList() [1/2]
virtual QCString TranslatorChinese::trStructList () [inline], [virtual]
Implements Translator.
Definition at line 2088 of file translator_cn.h.
    {
        return "";
    }
trStructList() [2/2]
virtual QCString TranslatorChinese::trStructList () [inline], [virtual]
Implements Translator.
Definition at line 2088 of file translator_cn.h.
    {
        return "";
    }
trStructListDescription() [1/2]
virtual QCString TranslatorChinese::trStructListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2092 of file translator_cn.h.
    {
        return ":";
    }
trStructListDescription() [2/2]
virtual QCString TranslatorChinese::trStructListDescription () [inline], [virtual]
Implements Translator.
Definition at line 2092 of file translator_cn.h.
    {
        return ":";
    }
trStructs() [1/2]
virtual QCString TranslatorChinese::trStructs () [inline], [virtual]
Implements Translator.
Definition at line 2080 of file translator_cn.h.
    {
        return "";
    }
trStructs() [2/2]
virtual QCString TranslatorChinese::trStructs () [inline], [virtual]
Implements Translator.
Definition at line 2080 of file translator_cn.h.
    {
        return "";
    }
trSubprogram() [1/2]
virtual QCString TranslatorChinese::trSubprogram (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1682 of file translator_cn.h.
    {
      return "";
    }
trSubprogram() [2/2]
virtual QCString TranslatorChinese::trSubprogram (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1682 of file translator_cn.h.
    {
      return "";
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorChinese::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1550 of file translator_cn.h.
    { return "/"; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorChinese::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1550 of file translator_cn.h.
    { return "/"; }
trSubprograms() [1/2]
virtual QCString TranslatorChinese::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1544 of file translator_cn.h.
    { return "/"; }
trSubprograms() [2/2]
virtual QCString TranslatorChinese::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1544 of file translator_cn.h.
    { return "/"; }
trTemplateParameters() [1/2]
virtual QCString TranslatorChinese::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1801 of file translator_cn.h.
    { return ""; }
trTemplateParameters() [2/2]
virtual QCString TranslatorChinese::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1801 of file translator_cn.h.
    { return ""; }
trTest() [1/2]
virtual QCString TranslatorChinese::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 969 of file translator_cn.h.
    {
      return "";
    }
trTest() [2/2]
virtual QCString TranslatorChinese::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 969 of file translator_cn.h.
    {
      return "";
    }
trTestList() [1/2]
virtual QCString TranslatorChinese::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 975 of file translator_cn.h.
    {
      return "";
    }
trTestList() [2/2]
virtual QCString TranslatorChinese::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 975 of file translator_cn.h.
    {
      return "";
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorChinese::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 136 of file translator_cn.h.
    { return "" CN_SPC; }
References CN_SPC.
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorChinese::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 136 of file translator_cn.h.
    { return "" CN_SPC; }
References CN_SPC.
trTodo() [1/2]
virtual QCString TranslatorChinese::trTodo () [inline], [virtual]
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 851 of file translator_cn.h.
    {
      return "";
    }
trTodo() [2/2]
virtual QCString TranslatorChinese::trTodo () [inline], [virtual]
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 851 of file translator_cn.h.
    {
      return "";
    }
trTodoList() [1/2]
virtual QCString TranslatorChinese::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 857 of file translator_cn.h.
    {
      return "";
    }
trTodoList() [2/2]
virtual QCString TranslatorChinese::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 857 of file translator_cn.h.
    {
      return "";
    }
trType() [1/2]
virtual QCString TranslatorChinese::trType (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1673 of file translator_cn.h.
    {
      return "";
    }
trType() [2/2]
virtual QCString TranslatorChinese::trType (bool , bool) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1673 of file translator_cn.h.
    {
      return "";
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorChinese::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1688 of file translator_cn.h.
    {
      return "";
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorChinese::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1688 of file translator_cn.h.
    {
      return "";
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorChinese::trTypedefDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 380 of file translator_cn.h.
    { return ""; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorChinese::trTypedefDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 380 of file translator_cn.h.
    { return ""; }
trTypedefs() [1/2]
virtual QCString TranslatorChinese::trTypedefs () [inline], [virtual]
Implements Translator.
Definition at line 361 of file translator_cn.h.
    { return ""; }
trTypedefs() [2/2]
virtual QCString TranslatorChinese::trTypedefs () [inline], [virtual]
Implements Translator.
Definition at line 361 of file translator_cn.h.
    { return ""; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorChinese::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1538 of file translator_cn.h.
    { return ""; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorChinese::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1538 of file translator_cn.h.
    { return ""; }
trVariableDocumentation() [1/2]
virtual QCString TranslatorChinese::trVariableDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 389 of file translator_cn.h.
    { return ""; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorChinese::trVariableDocumentation () [inline], [virtual]
Implements Translator.
Definition at line 389 of file translator_cn.h.
    { return ""; }
trVariables() [1/2]
virtual QCString TranslatorChinese::trVariables () [inline], [virtual]
Implements Translator.
Definition at line 370 of file translator_cn.h.
    { return ""; }
trVariables() [2/2]
virtual QCString TranslatorChinese::trVariables () [inline], [virtual]
Implements Translator.
Definition at line 370 of file translator_cn.h.
    { return ""; }
trVersion() [1/2]
virtual QCString TranslatorChinese::trVersion () [inline], [virtual]
Implements Translator.
Definition at line 418 of file translator_cn.h.
    { return ""; }
trVersion() [2/2]
virtual QCString TranslatorChinese::trVersion () [inline], [virtual]
Implements Translator.
Definition at line 418 of file translator_cn.h.
    { return ""; }
trVhdlType() [1/2]
virtual QCString TranslatorChinese::trVhdlType (uint64 type, bool single) [inline], [virtual]
VHDL type
Implements Translator.
Definition at line 1961 of file translator_cn.h.
    {
      switch(type)
      {
        case VhdlDocGen::LIBRARY:
          return "";
        case VhdlDocGen::PACKAGE:
          return "";
        case VhdlDocGen::SIGNAL:
          return "";
        case VhdlDocGen::COMPONENT:
          return "";
        case VhdlDocGen::CONSTANT:
          return "";
        case VhdlDocGen::ENTITY:
          return "";
        case VhdlDocGen::TYPE:
          return "";
        case VhdlDocGen::SUBTYPE:
          return "";
        case VhdlDocGen::FUNCTION:
          return "";
        case VhdlDocGen::RECORD:
          return "";
        case VhdlDocGen::PROCEDURE:
          return "";
        case VhdlDocGen::ARCHITECTURE:
          return "";
        case VhdlDocGen::ATTRIBUTE:
          return "";
        case VhdlDocGen::PROCESS:
          return "";
        case VhdlDocGen::PORT:
          return "";
        case VhdlDocGen::USE:
          if (single) return "";
          else return "";
        case VhdlDocGen::GENERIC:
          return "";
        case VhdlDocGen::PACKAGE_BODY:
          return "";
        case VhdlDocGen::UNITS:
          return "";
        case VhdlDocGen::SHAREDVARIABLE:
          return "";
        case VhdlDocGen::VFILE:
          return "";
        case VhdlDocGen::GROUP:
          return "";
        case VhdlDocGen::INSTANTIATION:
          return "";
        case VhdlDocGen::ALIAS:
          return "";
        case VhdlDocGen::CONFIG:
          return " ";
        case VhdlDocGen::MISCELLANEOUS:
          return "";
        case VhdlDocGen::UCF_CONST:
          return "";
        default:
          return "";
      }
    }
References VhdlDocGen::ALIAS, VhdlDocGen::ARCHITECTURE, VhdlDocGen::ATTRIBUTE, VhdlDocGen::COMPONENT, VhdlDocGen::CONFIG, VhdlDocGen::CONSTANT, VhdlDocGen::ENTITY, VhdlDocGen::FUNCTION, VhdlDocGen::GENERIC, VhdlDocGen::GROUP, VhdlDocGen::INSTANTIATION, VhdlDocGen::LIBRARY, VhdlDocGen::MISCELLANEOUS, VhdlDocGen::PACKAGE, VhdlDocGen::PACKAGE_BODY, VhdlDocGen::PORT, VhdlDocGen::PROCEDURE, VhdlDocGen::PROCESS, VhdlDocGen::RECORD, VhdlDocGen::SHAREDVARIABLE, VhdlDocGen::SIGNAL, VhdlDocGen::SUBTYPE, VhdlDocGen::TYPE, VhdlDocGen::UCF_CONST, VhdlDocGen::UNITS, VhdlDocGen::USE, and VhdlDocGen::VFILE.
trVhdlType() [2/2]
virtual QCString TranslatorChinese::trVhdlType (uint64 type, bool single) [inline], [virtual]
VHDL type
Implements Translator.
Definition at line 1961 of file translator_cn.h.
    {
      switch(type)
      {
        case VhdlDocGen::LIBRARY:
          return "";
        case VhdlDocGen::PACKAGE:
          return "";
        case VhdlDocGen::SIGNAL:
          return "";
        case VhdlDocGen::COMPONENT:
          return "";
        case VhdlDocGen::CONSTANT:
          return "";
        case VhdlDocGen::ENTITY:
          return "";
        case VhdlDocGen::TYPE:
          return "";
        case VhdlDocGen::SUBTYPE:
          return "";
        case VhdlDocGen::FUNCTION:
          return "";
        case VhdlDocGen::RECORD:
          return "";
        case VhdlDocGen::PROCEDURE:
          return "";
        case VhdlDocGen::ARCHITECTURE:
          return "";
        case VhdlDocGen::ATTRIBUTE:
          return "";
        case VhdlDocGen::PROCESS:
          return "";
        case VhdlDocGen::PORT:
          return "";
        case VhdlDocGen::USE:
          if (single) return "";
          else return "";
        case VhdlDocGen::GENERIC:
          return "";
        case VhdlDocGen::PACKAGE_BODY:
          return "";
        case VhdlDocGen::UNITS:
          return "";
        case VhdlDocGen::SHAREDVARIABLE:
          return "";
        case VhdlDocGen::VFILE:
          return "";
        case VhdlDocGen::GROUP:
          return "";
        case VhdlDocGen::INSTANTIATION:
          return "";
        case VhdlDocGen::ALIAS:
          return "";
        case VhdlDocGen::CONFIG:
          return " ";
        case VhdlDocGen::MISCELLANEOUS:
          return "";
        case VhdlDocGen::UCF_CONST:
          return "";
        default:
          return "";
      }
    }
References VhdlDocGen::ALIAS, VhdlDocGen::ARCHITECTURE, VhdlDocGen::ATTRIBUTE, VhdlDocGen::COMPONENT, VhdlDocGen::CONFIG, VhdlDocGen::CONSTANT, VhdlDocGen::ENTITY, VhdlDocGen::FUNCTION, VhdlDocGen::GENERIC, VhdlDocGen::GROUP, VhdlDocGen::INSTANTIATION, VhdlDocGen::LIBRARY, VhdlDocGen::MISCELLANEOUS, VhdlDocGen::PACKAGE, VhdlDocGen::PACKAGE_BODY, VhdlDocGen::PORT, VhdlDocGen::PROCEDURE, VhdlDocGen::PROCESS, VhdlDocGen::RECORD, VhdlDocGen::SHAREDVARIABLE, VhdlDocGen::SIGNAL, VhdlDocGen::SUBTYPE, VhdlDocGen::TYPE, VhdlDocGen::UCF_CONST, VhdlDocGen::UNITS, VhdlDocGen::USE, and VhdlDocGen::VFILE.
trWarning() [1/2]
virtual QCString TranslatorChinese::trWarning () [inline], [virtual]
Implements Translator.
Definition at line 415 of file translator_cn.h.
    { return ""; }
trWarning() [2/2]
virtual QCString TranslatorChinese::trWarning () [inline], [virtual]
Implements Translator.
Definition at line 415 of file translator_cn.h.
    { return ""; }
trWriteList() [1/2]
virtual QCString TranslatorChinese::trWriteList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 537 of file translator_cn.h.
    {
      // this function is used to produce a comma-separated list of items.
      // use generateMarker(i) to indicate where item i should be put.
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+="," CN_SPC;
          else // the fore last entry
            result+=CN_SPC ", " CN_SPC;
        }
      }
      return result;
    }
References CN_SPC, and generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorChinese::trWriteList (int numEntries) [inline], [virtual]
Implements Translator.
Definition at line 537 of file translator_cn.h.
    {
      // this function is used to produce a comma-separated list of items.
      // use generateMarker(i) to indicate where item i should be put.
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+="," CN_SPC;
          else // the fore last entry
            result+=CN_SPC ", " CN_SPC;
        }
      }
      return result;
    }
References CN_SPC, and generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_cn.h
doxygen/src/translator_cn.h