Input Class Reference
#include <input.h>
Public Types
enum Kind {
Bool
, Int
, String
, StrList
,
Obsolete
, Bool
, Int
, String
,
StrList
, Obsolete
 }
enum Kind {
Bool
, Int
, String
, StrList
,
Obsolete
, Bool
, Int
, String
,
StrList
, Obsolete
 }
Public Member Functions
virtual ~Input ()
virtual QVariant & value ()=0
virtual void update ()=0
virtual Kind kind () const =0
virtual QString docs () const =0
virtual QString id () const =0
virtual QString templateDocs () const =0
virtual void addDependency (Input *option)=0
virtual void setEnabled (bool)=0
virtual void updateDependencies ()=0
virtual void reset ()=0
virtual bool isDefault ()=0
virtual void writeValue (QTextStream &t, TextCodecAdapter *codec)=0
virtual void setTemplateDocs (const QString &docs)=0
virtual bool isEmpty ()
virtual ~Input ()
virtual QVariant & value ()=0
virtual void update ()=0
virtual Kind kind () const =0
virtual QString docs () const =0
virtual QString id () const =0
virtual QString templateDocs () const =0
virtual void addDependency (Input *option)=0
virtual void setEnabled (bool)=0
virtual void updateDependencies ()=0
virtual void reset ()=0
virtual bool isDefault ()=0
virtual void writeValue (QTextStream &t, TextCodecAdapter *codec)=0
virtual void setTemplateDocs (const QString &docs)=0
virtual bool isEmpty ()
Detailed Description
Definition at line 22 of file input.h.
Member Enumeration Documentation
Kind [1/2]
enum Input::Kind
Enumerator
Bool
Int
String
StrList
Obsolete
Bool
Int
String
StrList
Obsolete
Definition at line 25 of file input.h.
    {
      Bool,
      Int,
      String,
      StrList,
      Obsolete
    };
Kind [2/2]
enum Input::Kind
Enumerator
Bool
Int
String
StrList
Obsolete
Bool
Int
String
StrList
Obsolete
Definition at line 25 of file input.h.
    {
      Bool,
      Int,
      String,
      StrList,
      Obsolete
    };
Constructor & Destructor Documentation
 Input() [1/2]
virtual Input::~Input () [inline], [virtual]
Definition at line 33 of file input.h.
{}
 Input() [2/2]
virtual Input::~Input () [inline], [virtual]
Definition at line 33 of file input.h.
{}
Member Function Documentation
addDependency() [1/2]
virtual void Input::addDependency (Input * option) [pure virtual]
Implemented in InputInt, InputObsolete, InputString, InputStrList, InputInt, InputObsolete, InputString, InputStrList, InputBool, and InputBool.
Referenced by Expert::createTopicWidget().
addDependency() [2/2]
virtual void Input::addDependency (Input * option) [pure virtual]
Implemented in InputInt, InputObsolete, InputString, InputStrList, InputInt, InputObsolete, InputString, InputStrList, InputBool, and InputBool.
docs() [1/2]
virtual QString Input::docs () const [pure virtual]
Implemented in InputBool, InputInt, InputObsolete, InputString, InputStrList, InputBool, InputInt, InputObsolete, InputString, and InputStrList.
Referenced by Expert::showHelp().
docs() [2/2]
virtual QString Input::docs () const [pure virtual]
Implemented in InputBool, InputInt, InputObsolete, InputString, InputStrList, InputBool, InputInt, InputObsolete, InputString, and InputStrList.
id() [1/2]
virtual QString Input::id () const [pure virtual]
Implemented in InputBool, InputInt, InputObsolete, InputString, InputStrList, InputBool, InputInt, InputObsolete, InputString, and InputStrList.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), doxmlparser.compound.docXRefSectType::set_id(), and Expert::showHelp().
id() [2/2]
virtual QString Input::id () const [pure virtual]
Implemented in InputBool, InputInt, InputObsolete, InputString, InputStrList, InputBool, InputInt, InputObsolete, InputString, and InputStrList.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), and doxmlparser.compound.docXRefSectType::set_id().
isDefault() [1/2]
virtual bool Input::isDefault () [pure virtual]
Implemented in InputBool, InputInt, InputObsolete, InputString, InputStrList, InputBool, InputInt, InputObsolete, InputString, and InputStrList.
Referenced by Expert::saveTopic().
isDefault() [2/2]
virtual bool Input::isDefault () [pure virtual]
Implemented in InputBool, InputInt, InputObsolete, InputString, InputStrList, InputBool, InputInt, InputObsolete, InputString, and InputStrList.
isEmpty() [1/2]
virtual bool Input::isEmpty () [inline], [virtual]
Reimplemented in InputObsolete, InputString, InputStrList, InputObsolete, InputString, and InputStrList.
Definition at line 47 of file input.h.
{ return false; };
Referenced by Expert::saveTopic().
isEmpty() [2/2]
virtual bool Input::isEmpty () [inline], [virtual]
Reimplemented in InputObsolete, InputString, InputStrList, InputObsolete, InputString, and InputStrList.
Definition at line 47 of file input.h.
{ return false; };
kind() [1/2]
virtual Kind Input::kind () const [pure virtual]
Implemented in InputBool, InputInt, InputObsolete, InputString, InputStrList, InputBool, InputInt, InputObsolete, InputString, and InputStrList.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.sectiondefType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.docParamListType::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.sectiondefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.docSimpleSectType::buildAttributes(), doxmlparser.compound.docParamListType::buildAttributes(), doxmlparser.index.CompoundType::buildAttributes(), doxmlparser.index.MemberType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.index.CompoundType::exportAttributes(), doxmlparser.compound.docParamListType::exportAttributes(), doxmlparser.compound.docSimpleSectType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.index.MemberType::exportAttributes(), doxmlparser.compound.sectiondefType::exportAttributes(), doxmlparser.compound.compounddefType::get_kind(), doxmlparser.compound.sectiondefType::get_kind(), doxmlparser.compound.memberdefType::get_kind(), doxmlparser.compound.docSimpleSectType::get_kind(), doxmlparser.compound.docParamListType::get_kind(), doxmlparser.index.CompoundType::get_kind(), doxmlparser.index.MemberType::get_kind(), Expert::saveTopic(), doxmlparser.compound.compounddefType::set_kind(), doxmlparser.compound.sectiondefType::set_kind(), doxmlparser.compound.memberdefType::set_kind(), doxmlparser.compound.docSimpleSectType::set_kind(), doxmlparser.compound.docParamListType::set_kind(), doxmlparser.index.CompoundType::set_kind(), and doxmlparser.index.MemberType::set_kind().
kind() [2/2]
virtual Kind Input::kind () const [pure virtual]
Implemented in InputBool, InputInt, InputObsolete, InputString, InputStrList, InputBool, InputInt, InputObsolete, InputString, and InputStrList.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.sectiondefType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.docParamListType::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.sectiondefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.docSimpleSectType::buildAttributes(), doxmlparser.compound.docParamListType::buildAttributes(), doxmlparser.index.CompoundType::buildAttributes(), doxmlparser.index.MemberType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.index.CompoundType::exportAttributes(), doxmlparser.compound.docParamListType::exportAttributes(), doxmlparser.compound.docSimpleSectType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.index.MemberType::exportAttributes(), doxmlparser.compound.sectiondefType::exportAttributes(), doxmlparser.compound.compounddefType::get_kind(), doxmlparser.compound.sectiondefType::get_kind(), doxmlparser.compound.memberdefType::get_kind(), doxmlparser.compound.docSimpleSectType::get_kind(), doxmlparser.compound.docParamListType::get_kind(), doxmlparser.index.CompoundType::get_kind(), doxmlparser.index.MemberType::get_kind(), doxmlparser.compound.compounddefType::set_kind(), doxmlparser.compound.sectiondefType::set_kind(), doxmlparser.compound.memberdefType::set_kind(), doxmlparser.compound.docSimpleSectType::set_kind(), doxmlparser.compound.docParamListType::set_kind(), doxmlparser.index.CompoundType::set_kind(), and doxmlparser.index.MemberType::set_kind().
reset() [1/2]
virtual void Input::reset () [pure virtual]
Implemented in InputObsolete, and InputObsolete.
reset() [2/2]
virtual void Input::reset () [pure virtual]
Implemented in InputObsolete, and InputObsolete.
setEnabled() [1/2]
virtual void Input::setEnabled (bool) [pure virtual]
Implemented in InputBool, InputInt, InputObsolete, InputString, InputStrList, InputBool, InputInt, InputObsolete, InputString, and InputStrList.
setEnabled() [2/2]
virtual void Input::setEnabled (bool) [pure virtual]
Implemented in InputBool, InputInt, InputObsolete, InputString, InputStrList, InputBool, InputInt, InputObsolete, InputString, and InputStrList.
setTemplateDocs() [1/2]
virtual void Input::setTemplateDocs (const QString & docs) [pure virtual]
Implemented in InputObsolete, InputObsolete, InputBool, InputInt, InputString, InputStrList, InputBool, InputInt, InputString, and InputStrList.
Referenced by Expert::add().
setTemplateDocs() [2/2]
virtual void Input::setTemplateDocs (const QString & docs) [pure virtual]
Implemented in InputObsolete, InputObsolete, InputBool, InputInt, InputString, InputStrList, InputBool, InputInt, InputString, and InputStrList.
templateDocs() [1/2]
virtual QString Input::templateDocs () const [pure virtual]
Implemented in InputBool, InputInt, InputObsolete, InputString, InputStrList, InputBool, InputInt, InputObsolete, InputString, and InputStrList.
Referenced by Expert::saveTopic().
templateDocs() [2/2]
virtual QString Input::templateDocs () const [pure virtual]
Implemented in InputBool, InputInt, InputObsolete, InputString, InputStrList, InputBool, InputInt, InputObsolete, InputString, and InputStrList.
update() [1/2]
virtual void Input::update () [pure virtual]
Implemented in InputBool, InputInt, InputObsolete, InputString, InputStrList, InputBool, InputInt, InputObsolete, InputString, and InputStrList.
Referenced by runtests.Tester::__init__(), runtests.Tester::run(), Step1::setSourceDir(), updateBoolOption(), updateIntOption(), and updateStringOption().
update() [2/2]
virtual void Input::update () [pure virtual]
Implemented in InputBool, InputInt, InputObsolete, InputString, InputStrList, InputBool, InputInt, InputObsolete, InputString, and InputStrList.
Referenced by runtests.Tester::__init__(), and runtests.Tester::run().
updateDependencies() [1/2]
virtual void Input::updateDependencies () [pure virtual]
Implemented in InputBool, InputInt, InputObsolete, InputString, InputStrList, InputBool, InputInt, InputObsolete, InputString, and InputStrList.
updateDependencies() [2/2]
virtual void Input::updateDependencies () [pure virtual]
Implemented in InputBool, InputInt, InputObsolete, InputString, InputStrList, InputBool, InputInt, InputObsolete, InputString, and InputStrList.
value() [1/2]
virtual QVariant & Input::value () [pure virtual]
Implemented in InputBool, InputInt, InputObsolete, InputString, InputStrList, InputBool, InputInt, InputObsolete, InputString, and InputStrList.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), doxmlparser.compound.docListItemType::__init__(), doxmlparser.compound.spType::__init__(), doxmlparser.compound.spType::buildAttributes(), doxmlparser.compound.docListItemType::buildAttributes(), checkEncoding(), doxmlparser.compound.MixedContainer::export(), doxmlparser.index.MixedContainer::export(), doxmlparser.compound.docListItemType::exportAttributes(), doxmlparser.compound.spType::exportAttributes(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), doxmlparser.compound.spType::get_value(), doxmlparser.compound.docListItemType::get_value(), getBoolOption(), getIntOption(), getStringOption(), doxmlparser.compound.MixedContainer::getValue(), doxmlparser.index.MixedContainer::getValue(), Step1::init(), Expert::saveTopic(), doxmlparser.compound.spType::set_value(), doxmlparser.compound.docListItemType::set_value(), Step1::setSourceDir(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), doxmlparser.compound.MixedContainer::to_etree_simple(), doxmlparser.index.MixedContainer::to_etree_simple(), updateBoolOption(), updateIntOption(), updateStringOption(), and Expert::writeConfig().
value() [2/2]
virtual QVariant & Input::value () [pure virtual]
Implemented in InputBool, InputInt, InputObsolete, InputString, InputStrList, InputBool, InputInt, InputObsolete, InputString, and InputStrList.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), doxmlparser.compound.docListItemType::__init__(), doxmlparser.compound.spType::__init__(), doxmlparser.compound.spType::buildAttributes(), doxmlparser.compound.docListItemType::buildAttributes(), doxmlparser.compound.MixedContainer::export(), doxmlparser.index.MixedContainer::export(), doxmlparser.compound.docListItemType::exportAttributes(), doxmlparser.compound.spType::exportAttributes(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), doxmlparser.compound.spType::get_value(), doxmlparser.compound.docListItemType::get_value(), doxmlparser.compound.MixedContainer::getValue(), doxmlparser.index.MixedContainer::getValue(), doxmlparser.compound.spType::set_value(), doxmlparser.compound.docListItemType::set_value(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), doxmlparser.compound.MixedContainer::to_etree_simple(), and doxmlparser.index.MixedContainer::to_etree_simple().
writeValue() [1/2]
virtual void Input::writeValue (QTextStream & t, TextCodecAdapter * codec) [pure virtual]
Implemented in InputObsolete, InputObsolete, InputBool, InputInt, InputString, InputStrList, InputBool, InputInt, InputString, and InputStrList.
Referenced by Expert::saveTopic().
writeValue() [2/2]
virtual void Input::writeValue (QTextStream & t, TextCodecAdapter * codec) [pure virtual]
Implemented in InputObsolete, InputObsolete, InputBool, InputInt, InputString, InputStrList, InputBool, InputInt, InputString, and InputStrList.
The documentation for this class was generated from the following files:
doxygen/addon/doxywizard/input.h
doxygen/build/doxygen/addon/doxywizard/input.h