DocSimpleListItem Class Reference
#include <docnode.h>
Public Member Functions
DocSimpleListItem (DocParser *parser, DocNodeVariant *parent)
int parse (DocNodeVariant *)
const DocNodeVariant * paragraph () const
DocSimpleListItem (DocParser *parser, DocNodeVariant *parent)
int parse (DocNodeVariant *)
const DocNodeVariant * paragraph () const
Private Attributes
std::unique_ptr< DocNodeVariant > m_paragraph
Additional Inherited Members
Detailed Description
Node representing a simple list item
Definition at line 1105 of file docnode.h.
Constructor & Destructor Documentation
DocSimpleListItem() [1/2]
DocSimpleListItem::DocSimpleListItem (DocParser * parser, DocNodeVariant * parent)
Definition at line 2616 of file docnode.cpp.
      : DocNode(parser,parent)
{
}
DocSimpleListItem() [2/2]
DocSimpleListItem::DocSimpleListItem (DocParser * parser, DocNodeVariant * parent)
Member Function Documentation
paragraph() [1/2]
const DocNodeVariant * DocSimpleListItem::paragraph () const [inline]
Definition at line 1110 of file docnode.h.
{ return m_paragraph.get(); }
References m_paragraph.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), PerlModDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), and PrintDocVisitor::operator()().
paragraph() [2/2]
const DocNodeVariant * DocSimpleListItem::paragraph () const [inline]
Definition at line 1110 of file docnode.h.
{ return m_paragraph.get(); }
References m_paragraph.
parse() [1/2]
int DocSimpleListItem::parse (DocNodeVariant * thisVariant)
Definition at line 2622 of file docnode.cpp.
{
  auto ns = AutoNodeStack(parser(),thisVariant);
  m_paragraph = std::make_unique<DocNodeVariant>(DocPara(parser(),thisVariant));
  DocPara *par = &std::get<DocPara>(*m_paragraph);
  int rv=par->parse(m_paragraph.get());
  par->markFirst();
  par->markLast();
  return rv;
}
References m_paragraph, DocPara::markFirst(), DocPara::markLast(), DocPara::parse(), and DocNode::parser().
Referenced by DocSimpleList::parse().
parse() [2/2]
int DocSimpleListItem::parse (DocNodeVariant *)
Member Data Documentation
m_paragraph
std::unique_ptr< DocNodeVariant > DocSimpleListItem::m_paragraph [private]
Definition at line 1113 of file docnode.h.
Referenced by paragraph(), and parse().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docnode.h
doxygen/src/docnode.h
doxygen/build/doxygen/src/docnode.cpp
doxygen/src/docnode.cpp