FilterGroupBy Class Reference
The implementation of the `groupBy` filter.
Classes
struct ListElem
Static Public Member Functions
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &args)
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &args)
Static Private Member Functions
static QCString determineSortKey (const TemplateStructIntfPtr s, const QCString &attribName)
static QCString determineSortKey (const TemplateStructIntfPtr s, const QCString &attribName)
Detailed Description
The implementation of the `groupBy` filter.
Definition at line 1147 of file template.cpp.
Member Function Documentation
apply() [1/2]
static TemplateVariant FilterGroupBy::apply (const TemplateVariant & v, const TemplateVariant & args) [inline], [static]
Definition at line 1156 of file template.cpp.
    {
      if (v.isList() && args.isString())
      {
        TemplateListIntfPtr list = v.toList();
        if (list)
        {
          //printf("FilterListSort::apply: v=%s args=%s\n",qPrint(v.toString()),qPrint(args.toString()));
          TemplateListIntf::ConstIteratorPtr it = list->createIterator();
          TemplateVariant item;
          TemplateListPtr result = TemplateList::alloc();
          // create list of items based on v using the data in args as a sort key
          using SortList = std::vector<ListElem>;
          SortList sortList;
          sortList.reserve(v.toList()->count());
          for (it->toFirst();(it->current(item));it->toNext())
          {
            TemplateStructIntfPtr s = item.toStruct();
            if (s)
            {
              QCString sortKey = determineSortKey(s,args.toString());
              sortList.emplace_back(sortKey,item);
              //printf("sortKey=%s\n",qPrint(sortKey));
            }
          }
          // sort the list
          std::sort(sortList.begin(),
              sortList.end(),
              [](const auto &lhs,const auto &rhs) { return lhs.key < rhs.key; });
          // add sorted items to the result list
          TemplateListPtr groupList;
          QCString prevKey;
          for (const auto &elem : sortList)
          {
            if (groupList==0 || elem.key!=prevKey)
            {
              groupList = TemplateList::alloc();
              result->append(std::static_pointer_cast<TemplateListIntf>(groupList));
              prevKey = elem.key;
            }
            groupList->append(elem.value);
          }
          return TemplateVariant(std::static_pointer_cast<TemplateListIntf>(result));
        }
      }
      return v;
    }
References TemplateList::alloc(), QCString::append(), determineSortKey(), TemplateVariant::isList(), TemplateVariant::isString(), s, TemplateVariant::toList(), TemplateVariant::toString(), and TemplateVariant::toStruct().
apply() [2/2]
static TemplateVariant FilterGroupBy::apply (const TemplateVariant & v, const TemplateVariant & args) [inline], [static]
Definition at line 1156 of file template.cpp.
    {
      if (v.isList() && args.isString())
      {
        TemplateListIntfPtr list = v.toList();
        if (list)
        {
          //printf("FilterListSort::apply: v=%s args=%s\n",qPrint(v.toString()),qPrint(args.toString()));
          TemplateListIntf::ConstIteratorPtr it = list->createIterator();
          TemplateVariant item;
          TemplateListPtr result = TemplateList::alloc();
          // create list of items based on v using the data in args as a sort key
          using SortList = std::vector<ListElem>;
          SortList sortList;
          sortList.reserve(v.toList()->count());
          for (it->toFirst();(it->current(item));it->toNext())
          {
            TemplateStructIntfPtr s = item.toStruct();
            if (s)
            {
              QCString sortKey = determineSortKey(s,args.toString());
              sortList.emplace_back(sortKey,item);
              //printf("sortKey=%s\n",qPrint(sortKey));
            }
          }
          // sort the list
          std::sort(sortList.begin(),
              sortList.end(),
              [](const auto &lhs,const auto &rhs) { return lhs.key < rhs.key; });
          // add sorted items to the result list
          TemplateListPtr groupList;
          QCString prevKey;
          for (const auto &elem : sortList)
          {
            if (groupList==0 || elem.key!=prevKey)
            {
              groupList = TemplateList::alloc();
              result->append(std::static_pointer_cast<TemplateListIntf>(groupList));
              prevKey = elem.key;
            }
            groupList->append(elem.value);
          }
          return TemplateVariant(std::static_pointer_cast<TemplateListIntf>(result));
        }
      }
      return v;
    }
References TemplateList::alloc(), QCString::append(), TemplateVariant::isList(), TemplateVariant::isString(), s, TemplateVariant::toList(), TemplateVariant::toString(), and TemplateVariant::toStruct().
determineSortKey() [1/2]
static QCString FilterGroupBy::determineSortKey (const TemplateStructIntfPtr s, const QCString & attribName) [inline], [static], [private]
Definition at line 1209 of file template.cpp.
    {
       TemplateVariant v = s->get(attribName);
       return v.toString();
    }
References s, and TemplateVariant::toString().
Referenced by apply().
determineSortKey() [2/2]
static QCString FilterGroupBy::determineSortKey (const TemplateStructIntfPtr s, const QCString & attribName) [inline], [static], [private]
Definition at line 1209 of file template.cpp.
    {
       TemplateVariant v = s->get(attribName);
       return v.toString();
    }
References s, and TemplateVariant::toString().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp