InheritedMemberInfoListContext::Private Class Reference
Public Member Functions
void addMemberList (const ClassDef *inheritedFrom, const MemberList &ml, MemberList *combinedList)
void addMemberListIncludingGrouped (const ClassDef *inheritedFrom, const MemberList *ml, MemberList *combinedList)
void addMemberGroupsOfClass (const ClassDef *inheritedFrom, const ClassDef *cd, MemberListType lt, MemberList *combinedList)
void addInheritedMembers (const ClassDef *inheritedFrom, const ClassDef *cd, MemberListType lt, MemberListType lt1, int lt2, const QCString &title, bool additionalList)
void findInheritedMembers (const ClassDef *inheritedFrom, const ClassDef *cd, MemberListType lt, int lt2, const QCString &title, bool additionalList, ClassDefSet &visitedClasses)
void addMemberList (const ClassDef *inheritedFrom, const MemberList &ml, MemberList *combinedList)
void addMemberListIncludingGrouped (const ClassDef *inheritedFrom, const MemberList *ml, MemberList *combinedList)
void addMemberGroupsOfClass (const ClassDef *inheritedFrom, const ClassDef *cd, MemberListType lt, MemberList *combinedList)
void addInheritedMembers (const ClassDef *inheritedFrom, const ClassDef *cd, MemberListType lt, MemberListType lt1, int lt2, const QCString &title, bool additionalList)
void findInheritedMembers (const ClassDef *inheritedFrom, const ClassDef *cd, MemberListType lt, int lt2, const QCString &title, bool additionalList, ClassDefSet &visitedClasses)
Additional Inherited Members
Detailed Description
Definition at line 8074 of file context.cpp.
Member Function Documentation
addInheritedMembers() [1/2]
void InheritedMemberInfoListContext::Private::addInheritedMembers (const ClassDef * inheritedFrom, const ClassDef * cd, MemberListType lt, MemberListType lt1, int lt2, const QCString & title, bool additionalList) [inline]
Definition at line 8119 of file context.cpp.
    {
      int count = cd->countMembersIncludingGrouped(lt1,inheritedFrom,additionalList);
      if (lt2!=-1) count += cd->countMembersIncludingGrouped(static_cast<MemberListType>(lt2),inheritedFrom,additionalList);
      if (count>0)
      {
        const MemberList *ml = cd->getMemberList(lt1);
        const MemberList *ml2 = lt2!=-1 ? cd->getMemberList(static_cast<MemberListType>(lt2)) : 0;
        std::unique_ptr<MemberList> combinedList = std::make_unique<MemberList>(lt,MemberListContainer::Class);
        addMemberListIncludingGrouped(inheritedFrom,ml,combinedList.get());
        addMemberListIncludingGrouped(inheritedFrom,ml2,combinedList.get());
        addMemberGroupsOfClass(inheritedFrom,cd,lt,combinedList.get());
        if (lt2!=-1) addMemberGroupsOfClass(inheritedFrom,cd,static_cast<MemberListType>(lt2),combinedList.get());
        append(InheritedMemberInfoContext::alloc(cd,std::move(combinedList),title));
      }
    }
References addMemberGroupsOfClass(), addMemberListIncludingGrouped(), InheritedMemberInfoContext::alloc(), GenericNodeListContext::append(), Class, GenericNodeListContext::count(), ClassDef::countMembersIncludingGrouped(), and ClassDef::getMemberList().
Referenced by findInheritedMembers().
addInheritedMembers() [2/2]
void InheritedMemberInfoListContext::Private::addInheritedMembers (const ClassDef * inheritedFrom, const ClassDef * cd, MemberListType lt, MemberListType lt1, int lt2, const QCString & title, bool additionalList) [inline]
Definition at line 8119 of file context.cpp.
    {
      int count = cd->countMembersIncludingGrouped(lt1,inheritedFrom,additionalList);
      if (lt2!=-1) count += cd->countMembersIncludingGrouped(static_cast<MemberListType>(lt2),inheritedFrom,additionalList);
      if (count>0)
      {
        const MemberList *ml = cd->getMemberList(lt1);
        const MemberList *ml2 = lt2!=-1 ? cd->getMemberList(static_cast<MemberListType>(lt2)) : 0;
        std::unique_ptr<MemberList> combinedList = std::make_unique<MemberList>(lt,MemberListContainer::Class);
        addMemberListIncludingGrouped(inheritedFrom,ml,combinedList.get());
        addMemberListIncludingGrouped(inheritedFrom,ml2,combinedList.get());
        addMemberGroupsOfClass(inheritedFrom,cd,lt,combinedList.get());
        if (lt2!=-1) addMemberGroupsOfClass(inheritedFrom,cd,static_cast<MemberListType>(lt2),combinedList.get());
        append(InheritedMemberInfoContext::alloc(cd,std::move(combinedList),title));
      }
    }
References InheritedMemberInfoContext::alloc(), Class, ClassDef::countMembersIncludingGrouped(), and ClassDef::getMemberList().
addMemberGroupsOfClass() [1/2]
void InheritedMemberInfoListContext::Private::addMemberGroupsOfClass (const ClassDef * inheritedFrom, const ClassDef * cd, MemberListType lt, MemberList * combinedList) [inline]
Definition at line 8098 of file context.cpp.
    {
      // TODO: why this there no addMemberGroupsOfNamespace, addMembersGroupsOfFile,
      // addMemberGroupsOfGroup?
      for (const auto &mg: cd->getMemberGroups())
      {
        if (!mg->members().empty() && (!mg->allMembersInSameSection() || !cd->subGrouping())) // group is in its own section
        {
          for (const auto &md : mg->members())
          {
            if (lt==md->getSectionList(mg->container())->listType() &&
                !md->isReimplementedBy(inheritedFrom) &&
                md->isBriefSectionVisible())
            {
              combinedList->push_back(md);
            }
          }
        }
      }
    }
References ClassDef::getMemberGroups(), MemberVector::push_back(), and ClassDef::subGrouping().
Referenced by addInheritedMembers().
addMemberGroupsOfClass() [2/2]
void InheritedMemberInfoListContext::Private::addMemberGroupsOfClass (const ClassDef * inheritedFrom, const ClassDef * cd, MemberListType lt, MemberList * combinedList) [inline]
Definition at line 8098 of file context.cpp.
    {
      // TODO: why this there no addMemberGroupsOfNamespace, addMembersGroupsOfFile,
      // addMemberGroupsOfGroup?
      for (const auto &mg: cd->getMemberGroups())
      {
        if (!mg->members().empty() && (!mg->allMembersInSameSection() || !cd->subGrouping())) // group is in its own section
        {
          for (const auto &md : mg->members())
          {
            if (lt==md->getSectionList(mg->container())->listType() &&
                !md->isReimplementedBy(inheritedFrom) &&
                md->isBriefSectionVisible())
            {
              combinedList->push_back(md);
            }
          }
        }
      }
    }
References ClassDef::getMemberGroups(), MemberVector::push_back(), and ClassDef::subGrouping().
addMemberList() [1/2]
void InheritedMemberInfoListContext::Private::addMemberList (const ClassDef * inheritedFrom, const MemberList & ml, MemberList * combinedList) [inline]
Definition at line 8077 of file context.cpp.
    {
      for (const auto &md : ml)
      {
        if (md->isBriefSectionVisible() && !md->isReimplementedBy(inheritedFrom))
        {
          combinedList->push_back(md);
        }
      }
    }
References MemberVector::push_back().
Referenced by addMemberListIncludingGrouped().
addMemberList() [2/2]
void InheritedMemberInfoListContext::Private::addMemberList (const ClassDef * inheritedFrom, const MemberList & ml, MemberList * combinedList) [inline]
Definition at line 8077 of file context.cpp.
    {
      for (const auto &md : ml)
      {
        if (md->isBriefSectionVisible() && !md->isReimplementedBy(inheritedFrom))
        {
          combinedList->push_back(md);
        }
      }
    }
References MemberVector::push_back().
addMemberListIncludingGrouped() [1/2]
void InheritedMemberInfoListContext::Private::addMemberListIncludingGrouped (const ClassDef * inheritedFrom, const MemberList * ml, MemberList * combinedList) [inline]
Definition at line 8087 of file context.cpp.
    {
      if (ml)
      {
        addMemberList(inheritedFrom,*ml,combinedList);
        for (const auto *mg : ml->getMemberGroupList())
        {
          addMemberList(inheritedFrom,mg->members(),combinedList);
        }
      }
    }
References addMemberList(), and MemberList::getMemberGroupList().
Referenced by addInheritedMembers().
addMemberListIncludingGrouped() [2/2]
void InheritedMemberInfoListContext::Private::addMemberListIncludingGrouped (const ClassDef * inheritedFrom, const MemberList * ml, MemberList * combinedList) [inline]
Definition at line 8087 of file context.cpp.
    {
      if (ml)
      {
        addMemberList(inheritedFrom,*ml,combinedList);
        for (const auto *mg : ml->getMemberGroupList())
        {
          addMemberList(inheritedFrom,mg->members(),combinedList);
        }
      }
    }
References MemberList::getMemberGroupList().
findInheritedMembers() [1/2]
void InheritedMemberInfoListContext::Private::findInheritedMembers (const ClassDef * inheritedFrom, const ClassDef * cd, MemberListType lt, int lt2, const QCString & title, bool additionalList, ClassDefSet & visitedClasses) [inline]
Definition at line 8136 of file context.cpp.
    {
      for (const auto &ibcd : cd->baseClasses())
      {
        ClassDef *icd=ibcd.classDef;
        if (icd->isLinkable())
        {
          int lt1,lt3;
          convertProtectionLevel(lt,ibcd.prot,&lt1,&lt3);
          if (lt2==-1 && lt3!=-1)
          {
            lt2=lt3;
          }
          if (visitedClasses.find(icd)==visitedClasses.end())
          {
            visitedClasses.insert(icd); // guard for multiple virtual inheritance
            if (lt1!=-1)
            {
              // add member info for members of cd with list type lt
              addInheritedMembers(inheritedFrom,icd,lt,static_cast<MemberListType>(lt1),lt2,title,additionalList);
              // recurse down the inheritance tree
              findInheritedMembers(inheritedFrom,icd,static_cast<MemberListType>(lt1),lt2,title,additionalList,visitedClasses);
            }
          }
        }
      }
    }
References addInheritedMembers(), ClassDef::baseClasses(), convertProtectionLevel(), findInheritedMembers(), and ClassDef::isLinkable().
Referenced by findInheritedMembers().
findInheritedMembers() [2/2]
void InheritedMemberInfoListContext::Private::findInheritedMembers (const ClassDef * inheritedFrom, const ClassDef * cd, MemberListType lt, int lt2, const QCString & title, bool additionalList, ClassDefSet & visitedClasses) [inline]
Definition at line 8136 of file context.cpp.
    {
      for (const auto &ibcd : cd->baseClasses())
      {
        ClassDef *icd=ibcd.classDef;
        if (icd->isLinkable())
        {
          int lt1,lt3;
          convertProtectionLevel(lt,ibcd.prot,&lt1,&lt3);
          if (lt2==-1 && lt3!=-1)
          {
            lt2=lt3;
          }
          if (visitedClasses.find(icd)==visitedClasses.end())
          {
            visitedClasses.insert(icd); // guard for multiple virtual inheritance
            if (lt1!=-1)
            {
              // add member info for members of cd with list type lt
              addInheritedMembers(inheritedFrom,icd,lt,static_cast<MemberListType>(lt1),lt2,title,additionalList);
              // recurse down the inheritance tree
              findInheritedMembers(inheritedFrom,icd,static_cast<MemberListType>(lt1),lt2,title,additionalList,visitedClasses);
            }
          }
        }
      }
    }
References ClassDef::baseClasses(), convertProtectionLevel(), and ClassDef::isLinkable().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp