FilterGet Class Reference
The implementation of the `get` filter.
Static Public Member Functions
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &arg)
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &arg)
Detailed Description
The implementation of the `get` filter.
Definition at line 768 of file template.cpp.
Member Function Documentation
apply() [1/2]
static TemplateVariant FilterGet::apply (const TemplateVariant & v, const TemplateVariant & arg) [inline], [static]
Definition at line 771 of file template.cpp.
    {
      if (v.isValid() && (v.isStruct() || v.isWeakStruct()) && arg.isString())
      {
        TemplateStructIntfPtr s = v.toStruct();
        if (s)
        {
          TemplateVariant result = v.toStruct()->get(arg.toString());
          //printf("\nok[%s]=%d\n",qPrint(arg.toString()),result.type());
          return result;
        }
        else
        {
          return false;
        }
      }
      else
      {
        //printf("\nnok[%s]\n",qPrint(arg.toString()));
        return false;
      }
    }
References TemplateVariant::isString(), TemplateVariant::isStruct(), TemplateVariant::isValid(), TemplateVariant::isWeakStruct(), s, TemplateVariant::toString(), and TemplateVariant::toStruct().
apply() [2/2]
static TemplateVariant FilterGet::apply (const TemplateVariant & v, const TemplateVariant & arg) [inline], [static]
Definition at line 771 of file template.cpp.
    {
      if (v.isValid() && (v.isStruct() || v.isWeakStruct()) && arg.isString())
      {
        TemplateStructIntfPtr s = v.toStruct();
        if (s)
        {
          TemplateVariant result = v.toStruct()->get(arg.toString());
          //printf("\nok[%s]=%d\n",qPrint(arg.toString()),result.type());
          return result;
        }
        else
        {
          return false;
        }
      }
      else
      {
        //printf("\nnok[%s]\n",qPrint(arg.toString()));
        return false;
      }
    }
References TemplateVariant::isString(), TemplateVariant::isStruct(), TemplateVariant::isValid(), TemplateVariant::isWeakStruct(), s, TemplateVariant::toString(), and TemplateVariant::toStruct().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp