FlowChart Class Reference
#include <vhdldocgen.h>
Public Types
enum nodeTypes {
IF_NO = 1<<1
, ELSIF_NO = 1<<2
, ELSE_NO = 1<<3
, CASE_NO = 1<<4
,
WHEN_NO = 1<<5
, EXIT_NO = 1<<6
, END_NO = 1<<7
, TEXT_NO = 1<<8
,
START_NO = 1<<9
, ENDIF_NO = 1<<10
, FOR_NO = 1<<11
, WHILE_NO = 1<<12
,
END_LOOP = 1<<13
, END_CASE = 1<<14
, VARIABLE_NO = 1<<15
, RETURN_NO = 1<<16
,
LOOP_NO = 1<<17
, NEXT_NO = 1<<18
, EMPTY_NO = 1<<19
, COMMENT_NO = 1<<20
,
BEGIN_NO = 1<<21
, IF_NO = 1<<1
, ELSIF_NO = 1<<2
, ELSE_NO = 1<<3
,
CASE_NO = 1<<4
, WHEN_NO = 1<<5
, EXIT_NO = 1<<6
, END_NO = 1<<7
,
TEXT_NO = 1<<8
, START_NO = 1<<9
, ENDIF_NO = 1<<10
, FOR_NO = 1<<11
,
WHILE_NO = 1<<12
, END_LOOP = 1<<13
, END_CASE = 1<<14
, VARIABLE_NO = 1<<15
,
RETURN_NO = 1<<16
, LOOP_NO = 1<<17
, NEXT_NO = 1<<18
, EMPTY_NO = 1<<19
,
COMMENT_NO = 1<<20
, BEGIN_NO = 1<<21
 }
enum nodeTypes {
IF_NO = 1<<1
, ELSIF_NO = 1<<2
, ELSE_NO = 1<<3
, CASE_NO = 1<<4
,
WHEN_NO = 1<<5
, EXIT_NO = 1<<6
, END_NO = 1<<7
, TEXT_NO = 1<<8
,
START_NO = 1<<9
, ENDIF_NO = 1<<10
, FOR_NO = 1<<11
, WHILE_NO = 1<<12
,
END_LOOP = 1<<13
, END_CASE = 1<<14
, VARIABLE_NO = 1<<15
, RETURN_NO = 1<<16
,
LOOP_NO = 1<<17
, NEXT_NO = 1<<18
, EMPTY_NO = 1<<19
, COMMENT_NO = 1<<20
,
BEGIN_NO = 1<<21
, IF_NO = 1<<1
, ELSIF_NO = 1<<2
, ELSE_NO = 1<<3
,
CASE_NO = 1<<4
, WHEN_NO = 1<<5
, EXIT_NO = 1<<6
, END_NO = 1<<7
,
TEXT_NO = 1<<8
, START_NO = 1<<9
, ENDIF_NO = 1<<10
, FOR_NO = 1<<11
,
WHILE_NO = 1<<12
, END_LOOP = 1<<13
, END_CASE = 1<<14
, VARIABLE_NO = 1<<15
,
RETURN_NO = 1<<16
, LOOP_NO = 1<<17
, NEXT_NO = 1<<18
, EMPTY_NO = 1<<19
,
COMMENT_NO = 1<<20
, BEGIN_NO = 1<<21
 }
Public Member Functions
FlowChart (int typ, const QCString &t, const QCString &ex, const QCString &label=QCString())
~FlowChart ()
FlowChart (int typ, const QCString &t, const QCString &ex, const QCString &label=QCString())
~FlowChart ()
Static Public Member Functions
static void createSVG ()
static void startDot (TextStream &t)
static void endDot (TextStream &t)
static void codify (TextStream &t, const QCString &str)
static void writeShape (TextStream &t, const FlowChart &fl)
static void writeEdge (TextStream &t, int fl_from, int fl_to, int i, bool bFrom=FALSE, bool bTo=FALSE)
static void writeEdge (TextStream &t, const FlowChart &fl_from, const FlowChart &fl_to, int i)
static void writeFlowLinks (TextStream &t)
static QCString getNodeName (int n)
static void colTextNodes ()
static size_t getNextIfLink (const FlowChart &, size_t)
static size_t getNextNode (size_t index, int stamp)
static size_t findNode (size_t index, int stamp, int type)
static size_t findNode (size_t index, int type)
static size_t findNextLoop (size_t j, int stamp)
static size_t findPrevLoop (size_t j, int stamp, bool endif=FALSE)
static size_t findLabel (size_t j, const QCString &)
static void delFlowList ()
static const char * getNodeType (int c)
static void addFlowChart (int type, const QCString &text, const QCString &exp, const QCString &label=QCString())
static void moveToPrevLevel ()
static int getTimeStamp ()
static void writeFlowChart ()
static void alignFuncProc (QCString &q, const ArgumentList &al, bool isFunc)
static QCString convertNameToFileName ()
static void printNode (const FlowChart &n)
static void printFlowTree ()
static void buildCommentNodes (TextStream &t)
static void alignCommentNode (TextStream &t, QCString com)
static void printUmlTree ()
static QCString printPlantUmlNode (const FlowChart &flo, bool, bool)
static void createSVG ()
static void startDot (TextStream &t)
static void endDot (TextStream &t)
static void codify (TextStream &t, const QCString &str)
static void writeShape (TextStream &t, const FlowChart &fl)
static void writeEdge (TextStream &t, int fl_from, int fl_to, int i, bool bFrom=FALSE, bool bTo=FALSE)
static void writeEdge (TextStream &t, const FlowChart &fl_from, const FlowChart &fl_to, int i)
static void writeFlowLinks (TextStream &t)
static QCString getNodeName (int n)
static void colTextNodes ()
static size_t getNextIfLink (const FlowChart &, size_t)
static size_t getNextNode (size_t index, int stamp)
static size_t findNode (size_t index, int stamp, int type)
static size_t findNode (size_t index, int type)
static size_t findNextLoop (size_t j, int stamp)
static size_t findPrevLoop (size_t j, int stamp, bool endif=FALSE)
static size_t findLabel (size_t j, const QCString &)
static void delFlowList ()
static const char * getNodeType (int c)
static void addFlowChart (int type, const QCString &text, const QCString &exp, const QCString &label=QCString())
static void moveToPrevLevel ()
static int getTimeStamp ()
static void writeFlowChart ()
static void alignFuncProc (QCString &q, const ArgumentList &al, bool isFunc)
static QCString convertNameToFileName ()
static void printNode (const FlowChart &n)
static void printFlowTree ()
static void buildCommentNodes (TextStream &t)
static void alignCommentNode (TextStream &t, QCString com)
static void printUmlTree ()
static QCString printPlantUmlNode (const FlowChart &flo, bool, bool)
Private Attributes
int id = 0
int stamp = 0
int type = 0
int line = 0
QCString label
QCString text
QCString exp
Detailed Description
Definition at line 273 of file vhdldocgen.h.
Member Enumeration Documentation
nodeTypes [1/2]
enum FlowChart::nodeTypes
Enumerator
IF_NO
ELSIF_NO
ELSE_NO
CASE_NO
WHEN_NO
EXIT_NO
END_NO
TEXT_NO
START_NO
ENDIF_NO
FOR_NO
WHILE_NO
END_LOOP
END_CASE
VARIABLE_NO
RETURN_NO
LOOP_NO
NEXT_NO
EMPTY_NO
COMMENT_NO
BEGIN_NO
IF_NO
ELSIF_NO
ELSE_NO
CASE_NO
WHEN_NO
EXIT_NO
END_NO
TEXT_NO
START_NO
ENDIF_NO
FOR_NO
WHILE_NO
END_LOOP
END_CASE
VARIABLE_NO
RETURN_NO
LOOP_NO
NEXT_NO
EMPTY_NO
COMMENT_NO
BEGIN_NO
Definition at line 276 of file vhdldocgen.h.
                   {
      IF_NO = 1<<1,
      ELSIF_NO = 1<<2,
      ELSE_NO = 1<<3,
      CASE_NO = 1<<4,
      WHEN_NO = 1<<5,
      EXIT_NO = 1<<6,
      END_NO = 1<<7,
      TEXT_NO = 1<<8,
      START_NO = 1<<9,
      ENDIF_NO = 1<<10,
      FOR_NO = 1<<11,
      WHILE_NO = 1<<12,
      END_LOOP = 1<<13,
      END_CASE = 1<<14,
      VARIABLE_NO = 1<<15,
      RETURN_NO = 1<<16,
      LOOP_NO = 1<<17,
      NEXT_NO = 1<<18,
      EMPTY_NO = 1<<19,
      COMMENT_NO = 1<<20,
      BEGIN_NO = 1<<21
    };
nodeTypes [2/2]
enum FlowChart::nodeTypes
Enumerator
IF_NO
ELSIF_NO
ELSE_NO
CASE_NO
WHEN_NO
EXIT_NO
END_NO
TEXT_NO
START_NO
ENDIF_NO
FOR_NO
WHILE_NO
END_LOOP
END_CASE
VARIABLE_NO
RETURN_NO
LOOP_NO
NEXT_NO
EMPTY_NO
COMMENT_NO
BEGIN_NO
IF_NO
ELSIF_NO
ELSE_NO
CASE_NO
WHEN_NO
EXIT_NO
END_NO
TEXT_NO
START_NO
ENDIF_NO
FOR_NO
WHILE_NO
END_LOOP
END_CASE
VARIABLE_NO
RETURN_NO
LOOP_NO
NEXT_NO
EMPTY_NO
COMMENT_NO
BEGIN_NO
Definition at line 276 of file vhdldocgen.h.
                   {
      IF_NO = 1<<1,
      ELSIF_NO = 1<<2,
      ELSE_NO = 1<<3,
      CASE_NO = 1<<4,
      WHEN_NO = 1<<5,
      EXIT_NO = 1<<6,
      END_NO = 1<<7,
      TEXT_NO = 1<<8,
      START_NO = 1<<9,
      ENDIF_NO = 1<<10,
      FOR_NO = 1<<11,
      WHILE_NO = 1<<12,
      END_LOOP = 1<<13,
      END_CASE = 1<<14,
      VARIABLE_NO = 1<<15,
      RETURN_NO = 1<<16,
      LOOP_NO = 1<<17,
      NEXT_NO = 1<<18,
      EMPTY_NO = 1<<19,
      COMMENT_NO = 1<<20,
      BEGIN_NO = 1<<21
    };
Constructor & Destructor Documentation
FlowChart() [1/2]
FlowChart::FlowChart (int typ, const QCString & t, const QCString & ex, const QCString & label = QCString())
Definition at line 3210 of file vhdldocgen.cpp.
{
  stamp=ifcounter;
  if (typ & STARTL)
  {
    ifcounter++;
  }
  text=t;
  exp=ex;
  type=typ;
  label=lab;
  if (typ & (ELSE_NO | ELSIF_NO))
  {
    stamp--;
  }
  if (typ & (START_NO | END_NO | VARIABLE_NO))
  {
    stamp=0;
  }
  id=nodeCounter++;
}
References ELSE_NO, ELSIF_NO, END_NO, exp, ifcounter, label, nodeCounter, stamp, START_NO, STARTL, text, type, and VARIABLE_NO.
 FlowChart() [1/2]
FlowChart::~FlowChart ()
Definition at line 3206 of file vhdldocgen.cpp.
{
}
FlowChart() [2/2]
FlowChart::FlowChart (int typ, const QCString & t, const QCString & ex, const QCString & label = QCString())
 FlowChart() [2/2]
FlowChart::~FlowChart ()
Member Function Documentation
addFlowChart() [1/2]
void FlowChart::addFlowChart (int type, const QCString & text, const QCString & exp, const QCString & label = QCString()) [static]
Definition at line 3237 of file vhdldocgen.cpp.
{
  if (!VhdlDocGen::getFlowMember()) return;
  QCString typeString(text);
  QCString expression(exp);
  if (!text.isEmpty())
  {
    typeString=substitute(typeString,";","\n");
  }
  if (!exp.isEmpty())
  {
    expression=substitute(expression,"\"","\\\"");
  }
  if (type & VARIABLE_NO)
  {
  // Ignore the empty section of the VHDL variable definition.
  // This is section between `process` and `begin` keywords, where any source text is missing, probably a bug in the VHDL source parser.
    if(text.isEmpty()) return;
    flowList.insert(flowList.begin(),FlowChart(type,typeString,expression,label));
    flowList.front().line=1; // TODO: use getLine(); of the parser
  }
  else if (type & START_NO)
  {
    flowList.insert(flowList.begin(),FlowChart(type,typeString,expression,label));
    flowList.front().line=1; // TODO: use getLine(); of the parser
  }
  else
  {
    flowList.emplace_back(type,typeString,expression,label);
    flowList.back().line=1; // TODO: use getLine(); of the parser
  }
}
References exp, flowList, VhdlDocGen::getFlowMember(), QCString::isEmpty(), label, START_NO, substitute(), text, type, and VARIABLE_NO.
Referenced by vhdl::parser::VhdlParser::case_statement(), vhdl::parser::VhdlParser::case_statement_alternative(), VHDLOutlineParser::createFlow(), vhdl::parser::VhdlParser::exit_statement(), VHDLOutlineParser::handleFlowComment(), vhdl::parser::VhdlParser::if_statement(), vhdl::parser::VhdlParser::iteration_scheme(), vhdl::parser::VhdlParser::loop_statement(), vhdl::parser::VhdlParser::next_statement(), vhdl::parser::VhdlParser::process_statement(), vhdl::parser::VhdlParser::sequential_statement(), and vhdl::parser::VhdlParser::subprogram_body().
addFlowChart() [2/2]
static void FlowChart::addFlowChart (int type, const QCString & text, const QCString & exp, const QCString & label = QCString()) [static]
alignCommentNode() [1/2]
void FlowChart::alignCommentNode (TextStream & t, QCString com) [static]
Definition at line 3062 of file vhdldocgen.cpp.
{
  uint max=0;
  QCString s;
  StringVector ql=split(com.str(),"\n");
  for (size_t j=0;j<ql.size();j++)
  {
    s=ql[j];
    if (max<s.length()) max=s.length();
  }
  s=ql.back();
  int diff=max-s.length();
  QCString n(1);
  if (diff>0)
  {
    n.fill(' ',2*diff);
    n.append(".");
    s+=n;
    ql.pop_back();
    ql.push_back(s.str());
  }
  for (size_t j=0;j<ql.size();j++)
  {
    s=ql[j];
    if (j<ql.size()-1)
    {
      s+="\n";
    }
    FlowChart::codify(t,s);
  }
}
References codify(), n, s, split(), and QCString::str().
Referenced by buildCommentNodes(), and writeShape().
alignCommentNode() [2/2]
static void FlowChart::alignCommentNode (TextStream & t, QCString com) [static]
alignFuncProc() [1/2]
void FlowChart::alignFuncProc (QCString & q, const ArgumentList & al, bool isFunc) [static]
Definition at line 3625 of file vhdldocgen.cpp.
{
  size_t index=al.size();
  if (index==0) return;
  int len=q.length()+VhdlDocGen::getFlowMember()->name().length();
  QCString prev,temp;
  prev.fill(' ',len+1);
  q+="\n";
  for (const Argument &arg : al)
  {
    QCString attl=arg.defval+" ";
    attl+=arg.name+" ";
    if (!isFunc)
    {
      attl+=arg.attrib+" ";
    }
    else
    {
      attl+=" in ";
    }
    attl+=arg.type;
    if (--index) attl+=",\n"; else attl+="\n";
    attl.prepend(prev);
    temp+=attl;
  }
  q+=temp;
}
References QCString::fill(), VhdlDocGen::getFlowMember(), len, QCString::length(), Definition::name(), QCString::prepend(), and ArgumentList::size().
Referenced by VHDLOutlineParser::createFlow().
alignFuncProc() [2/2]
static void FlowChart::alignFuncProc (QCString & q, const ArgumentList & al, bool isFunc) [static]
buildCommentNodes() [1/2]
void FlowChart::buildCommentNodes (TextStream & t) [static]
Definition at line 3098 of file vhdldocgen.cpp.
{
  size_t size=flowList.size();
  bool begin=false;
  if (size>0)
  {
    for (uint j=0;j < size-1 ;j++)
    {
      FlowChart &fll = flowList[j];
      if (fll.type & COMMENT_NO)
      {
        FlowChart &to=flowList[j+1];
        if (to.type & COMMENT_NO)
        {
          to.label = fll.label+"\n"+to.label;
          flowList.erase(flowList.begin()+j);
          if (size>0) size--;
          if (j>0) j--;
        }
      }
    }// for
  }
  for (size_t j=0;j <flowList.size() ;j++)
  {
    const FlowChart &fll=flowList[j];
    if (fll.type & BEGIN_NO)
    {
      begin = true;
      continue;
    }
    if (fll.type & COMMENT_NO)
    {
      const FlowChart *to;
      if (!begin)
      {
        // comment between function/process .. begin is linked to start node
        to = &flowList[0];
      }
      else if (j>0 && flowList[j-1].line==fll.line)
      {
        to = &flowList[j-1];
      }
      else
      {
        to = &flowList[j+1];
      }
      t << getNodeName(fll.id);
      t << "[shape=none, label=<\n";
      t << "<TABLE BORDER=\"0\" CELLBORDER=\"1\" CELLSPACING=\"0\" CELLPADDING=\"2\" >\n ";
      t << "<TR><TD BGCOLOR=\"";
      t << flowCol.comment;
      t << "\" > ";
      FlowChart::alignCommentNode(t,fll.label);
      t << " </TD></TR></TABLE>>];";
      writeEdge(t,fll.id,to->id,2);
    }
  }// for
  // delete comment nodes;
  size=flowList.size();
  for (size_t j=0; j<size; j++)
  {
    FlowChart &fll=flowList[j];
    if (fll.type & (COMMENT_NO | BEGIN_NO))
    {
      size_t diff=FLOWLEN-(j+1);
      if ((fll.type & COMMENT_NO) && diff > 1)
      {
        flowList[j+1].label = fll.label;
      }
      flowList.erase(flowList.begin()+j);
      if (size>0) size--;
      if (j>0) j--;
    }
  }// for;
}
References alignCommentNode(), ghc::filesystem::begin(), BEGIN_NO, COMMENT_NO, flowCol, FLOWLEN, flowList, getNodeName(), id, label, line, size, type, and writeEdge().
Referenced by writeFlowChart().
buildCommentNodes() [2/2]
static void FlowChart::buildCommentNodes (TextStream & t) [static]
codify() [1/2]
void FlowChart::codify (TextStream & t, const QCString & str) [static]
Definition at line 3183 of file vhdldocgen.cpp.
{
  if (!str.isEmpty())
  {
    const char *p=str.data();
    char c;
    while (*p)
    {
      c=*p++;
      switch(c)
      {
        case '<': t << "&lt;"; break;
        case '>': t << "&gt;"; break;
        case '&': t << "&amp;"; break;
        case '\'': t << "&#39;"; break;
        case '"': t << "&quot;"; break;
        case '\n': t <<"<BR ALIGN=\"LEFT\"/>"; break;
        default: t << c; break;
      }
    }
  }
}//codify
References c, QCString::data(), QCString::isEmpty(), and p.
Referenced by alignCommentNode().
codify() [2/2]
static void FlowChart::codify (TextStream & t, const QCString & str) [static]
colTextNodes() [1/2]
void FlowChart::colTextNodes () [static]
Definition at line 2998 of file vhdldocgen.cpp.
{
  FlowChart *flno = nullptr;
  bool found=FALSE;
  for (size_t j=0;j<flowList.size();j++)
  {
    FlowChart &flo = flowList[j];
    if (flo.type&TEXT_NO)
    {
      if (!found)
      {
        flno=&flo;
      }
      else
      {
        flno->text+=flo.text;
        flowList.erase(flowList.begin()+j);
        if (j>0) j=j-1;
      }
      found=TRUE;
    }
    else
    {
      found=FALSE;
    }
  }
  // find if..endif without text
  // if..elseif without text
  if (!flowList.empty())
  {
    for (size_t j=0;j<flowList.size()-1;j++)
    {
      const FlowChart &flo = flowList[j];
      int kind = flo.type;
      if ((kind & IFF) || (flo.type & ELSE_NO))
      {
        const FlowChart &ftemp = flowList[j+1];
        if (ftemp.type & EMPTY)
        {
          FlowChart fc(TEXT_NO,"empty ",QCString());
          fc.stamp = flo.stamp;
          flowList.insert(flowList.begin()+j+1,fc);
        }
      }
    }
  }
}// colTextNode
References ELSE_NO, EMPTY, FALSE, flowList, found, IFF, stamp, text, TEXT_NO, TRUE, and type.
Referenced by writeFlowChart().
colTextNodes() [2/2]
static void FlowChart::colTextNodes () [static]
convertNameToFileName() [1/2]
QCString FlowChart::convertNameToFileName () [static]
Definition at line 3362 of file vhdldocgen.cpp.
{
  return VhdlDocGen::getFlowMember()->name();
}
References VhdlDocGen::getFlowMember(), and Definition::name().
Referenced by createSVG(), HtmlDocVisitor::operator()(), and printUmlTree().
convertNameToFileName() [2/2]
static QCString FlowChart::convertNameToFileName () [static]
createSVG() [1/2]
void FlowChart::createSVG () [static]
Definition at line 3396 of file vhdldocgen.cpp.
{
  QCString qcs("/");
  QCString ov = Config_getString(HTML_OUTPUT);
  qcs+=FlowChart::convertNameToFileName()+".svg";
  //const MemberDef *m=VhdlDocGen::getFlowMember();
  //if (m)
  // fprintf(stderr,"\n creating flowchart : %s %s in file %s \n",theTranslator->trVhdlType(m->getMemberSpecifiers(),TRUE),qPrint(m->name()),qPrint(m->getFileDef()->name()));
  QCString dir=" -o \""+ov+qcs+"\"";
  ov+="/flow_design.dot";
  QCString vlargs="-Tsvg \""+ov+"\" "+dir ;
  if (Portable::system(Doxygen::verifiedDotPath,vlargs)!=0)
  {
    err("could not create dot file");
  }
}
References Config_getString, convertNameToFileName(), err(), Portable::system(), and Doxygen::verifiedDotPath.
Referenced by writeFlowChart().
createSVG() [2/2]
static void FlowChart::createSVG () [static]
delFlowList() [1/2]
void FlowChart::delFlowList () [static]
Definition at line 3055 of file vhdldocgen.cpp.
{
  ifcounter=0;
  nodeCounter=0;
  flowList.clear();
}
References flowList, ifcounter, and nodeCounter.
Referenced by writeFlowChart().
delFlowList() [2/2]
static void FlowChart::delFlowList () [static]
endDot() [1/2]
void FlowChart::endDot (TextStream & t) [static]
Definition at line 3426 of file vhdldocgen.cpp.
{
  t << " } \n";
}
Referenced by writeFlowChart().
endDot() [2/2]
static void FlowChart::endDot (TextStream & t) [static]
findLabel() [1/2]
size_t FlowChart::findLabel (size_t j, const QCString & label) [static]
Definition at line 3698 of file vhdldocgen.cpp.
{
  for (size_t j=index;j>0;j--)
  {
    const FlowChart &flo = flowList[j];
    if ((flo.type & LOOP) && !flo.label.isEmpty() && qstricmp(flo.label,label)==0)
    {
      return j;
    }
  }
  err("could not find label: %s",qPrint(label));
  return 0;
}
References err(), flowList, QCString::isEmpty(), label, LOOP, qPrint(), qstricmp(), and type.
Referenced by writeFlowLinks().
findLabel() [2/2]
static size_t FlowChart::findLabel (size_t j, const QCString &) [static]
findNextLoop() [1/2]
size_t FlowChart::findNextLoop (size_t j, int stamp) [static]
Definition at line 3658 of file vhdldocgen.cpp.
{
  for (size_t j=index+1; j<flowList.size(); j++)
  {
    const FlowChart &flo = flowList[j];
    if (flo.stamp==stamp)
    {
      continue;
    }
    if (flo.type&END_LOOP)
    {
      return j;
    }
  }
  return flowList.size()-1;
}
References END_LOOP, flowList, stamp, and type.
Referenced by writeFlowLinks().
findNextLoop() [2/2]
static size_t FlowChart::findNextLoop (size_t j, int stamp) [static]
findNode() [1/4]
size_t FlowChart::findNode (size_t index, int stamp, int type) [static]
Definition at line 3712 of file vhdldocgen.cpp.
{
  for (size_t j=index+1; j<flowList.size(); j++)
  {
    const FlowChart &flo = flowList[j];
    if (flo.type==type && flo.stamp==stamp)
    {
      return j;
    }
  }
  return 0;
}// findNode
References flowList, stamp, and type.
Referenced by getNextIfLink(), getNextNode(), and writeFlowLinks().
findNode() [2/4]
static size_t FlowChart::findNode (size_t index, int stamp, int type) [static]
findNode() [3/4]
static size_t FlowChart::findNode (size_t index, int type) [static]
findNode() [4/4]
static size_t FlowChart::findNode (size_t index, int type) [static]
findPrevLoop() [1/2]
size_t FlowChart::findPrevLoop (size_t j, int stamp, bool endif = FALSE) [static]
Definition at line 3675 of file vhdldocgen.cpp.
{
  for (size_t j=index;j>0;j--)
  {
    const FlowChart &flo = flowList[j];
    if (flo.type & LOOP)
    {
      if (flo.stamp==stamp && endif)
      {
        return j;
      }
      else
      {
        if (flo.stamp<stamp)
        {
          return j;
        }
      }
    }
  }
  return flowList.size()-1;
}
References flowList, LOOP, stamp, and type.
Referenced by writeFlowLinks().
findPrevLoop() [2/2]
static size_t FlowChart::findPrevLoop (size_t j, int stamp, bool endif = FALSE) [static]
getNextIfLink() [1/2]
size_t FlowChart::getNextIfLink (const FlowChart & fl, size_t index) [static]
Definition at line 3766 of file vhdldocgen.cpp.
{
  int stamp=fl.stamp;
  size_t start = index+1;
  size_t endifNode = findNode(start,stamp,ENDIF_NO);
  size_t elseifNode = findNode(start,stamp,ELSIF_NO);
  size_t elseNode = findNode(start,stamp,ELSE_NO);
  if (elseifNode>0 && elseifNode<endifNode)
  {
    return elseifNode;
  }
  if (elseNode>0 && elseNode<endifNode)
  {
    return elseNode+1;
  }
  stamp=flowList[endifNode].stamp;
  return getNextNode(endifNode,stamp);
}
References ELSE_NO, ELSIF_NO, ENDIF_NO, findNode(), flowList, getNextNode(), and stamp.
Referenced by writeFlowLinks().
getNextIfLink() [2/2]
static size_t FlowChart::getNextIfLink (const FlowChart & , size_t) [static]
getNextNode() [1/2]
size_t FlowChart::getNextNode (size_t index, int stamp) [static]
Definition at line 3725 of file vhdldocgen.cpp.
{
  for (size_t j=index+1; j<flowList.size(); j++)
  {
    const FlowChart &flo = flowList[j];
    int kind = flo.type;
    int s = flo.stamp;
    if (s>stamp)
    {
      continue;
    }
    if (kind & ENDIF_NO)
    {
      if (s<stamp && stamp>0)
      {
        stamp--;
        continue;
      }
    }
    if (kind & (ELSE_NO | ELSIF_NO))
    {
      if (s<stamp && stamp>0)
      {
        stamp--;
      }
      j=findNode(j,stamp,ENDIF_NO);
      continue;
    }
    if (kind & WHEN_NO)
    {
      if (s<stamp && stamp>0)
      {
        stamp--;
      }
      return findNode(j,stamp-1,END_CASE);
    }
    return j;
  }
  return FLOWLEN;
}
References ELSE_NO, ELSIF_NO, END_CASE, ENDIF_NO, findNode(), FLOWLEN, flowList, s, stamp, type, and WHEN_NO.
Referenced by getNextIfLink(), and writeFlowLinks().
getNextNode() [2/2]
static size_t FlowChart::getNextNode (size_t index, int stamp) [static]
getNodeName() [1/2]
QCString FlowChart::getNodeName (int n) [static]
Definition at line 3048 of file vhdldocgen.cpp.
{
  QCString node;
  node.setNum(n);
  return node.prepend("node");
}
References n, QCString::prepend(), and QCString::setNum().
Referenced by buildCommentNodes(), writeEdge(), and writeShape().
getNodeName() [2/2]
static QCString FlowChart::getNodeName (int n) [static]
getNodeType() [1/2]
const char * FlowChart::getNodeType (int c) [static]
Definition at line 3367 of file vhdldocgen.cpp.
{
  switch(c)
  {
    case IF_NO: return "if ";
    case ELSIF_NO: return "elsif ";
    case ELSE_NO: return "else ";
    case CASE_NO: return "case ";
    case WHEN_NO: return "when ";
    case EXIT_NO: return "exit ";
    case END_NO: return "end ";
    case TEXT_NO: return "text ";
    case START_NO: return "start ";
    case ENDIF_NO: return "endif ";
    case FOR_NO: return "for ";
    case WHILE_NO: return "while ";
    case END_LOOP: return "end_loop ";
    case END_CASE: return "end_case ";
    case VARIABLE_NO: return "variable_decl ";
    case RETURN_NO: return "return ";
    case LOOP_NO: return "infinite loop ";
    case NEXT_NO: return "next ";
    case COMMENT_NO: return "comment ";
    case EMPTY_NO: return "empty ";
    case BEGIN_NO: return "<begin> ";
    default: return "--failure--";
  }
}
References BEGIN_NO, c, CASE_NO, COMMENT_NO, ELSE_NO, ELSIF_NO, EMPTY_NO, END_CASE, END_LOOP, END_NO, ENDIF_NO, EXIT_NO, FOR_NO, IF_NO, LOOP_NO, NEXT_NO, RETURN_NO, START_NO, TEXT_NO, VARIABLE_NO, WHEN_NO, and WHILE_NO.
Referenced by printNode().
getNodeType() [2/2]
static const char * FlowChart::getNodeType (int c) [static]
getTimeStamp() [1/2]
static int FlowChart::getTimeStamp () [static]
getTimeStamp() [2/2]
static int FlowChart::getTimeStamp () [static]
moveToPrevLevel() [1/2]
void FlowChart::moveToPrevLevel () [static]
Definition at line 3276 of file vhdldocgen.cpp.
{
  if (!VhdlDocGen::getFlowMember()) return;
  ifcounter--;
}
References VhdlDocGen::getFlowMember(), and ifcounter.
Referenced by vhdl::parser::VhdlParser::case_statement(), vhdl::parser::VhdlParser::case_statement_alternative(), vhdl::parser::VhdlParser::if_statement(), and vhdl::parser::VhdlParser::loop_statement().
moveToPrevLevel() [2/2]
static void FlowChart::moveToPrevLevel () [static]
printFlowTree() [1/2]
void FlowChart::printFlowTree () [static]
Definition at line 2990 of file vhdldocgen.cpp.
{
  for (const auto &flowChart : flowList)
  {
    printNode(flowChart);
  }
}
References flowList, and printNode().
Referenced by writeFlowChart().
printFlowTree() [2/2]
static void FlowChart::printFlowTree () [static]
printNode() [1/2]
void FlowChart::printNode (const FlowChart & n) [static]
Definition at line 2930 of file vhdldocgen.cpp.
{
  QCString ui="-";
  std::string q;
  std::string t;
  ui.fill('-',255);
  if (flo.type & STARTL)
  {
    if (flo.stamp>0)
    {
      q=ui.left(2*flo.stamp).str();
    }
    else
    {
      q=" ";
    }
    QCString nn=flo.exp.stripWhiteSpace();
    printf("\nYES: %s%s[%d,%d]",qPrint(q),qPrint(nn),flo.stamp,flo.id);
  }
  else
  {
    if (flo.type & COMMENT_NO)
    {
      t=flo.label.str();
    }
    else
    {
      t=flo.text.str();
    }
    static const reg::Ex ep(R"(\s)");
    t = reg::replace(t,ep,std::string());
    if (t.empty())
    {
      t=" ";
    }
    if (flo.stamp>0)
    {
      q=ui.left(2*flo.stamp).str();
    }
    else
    {
      q=" ";
    }
    if (flo.type & EMPTNODE)
    {
      printf("\n NO: %s%s[%d,%d]",q.c_str(),FlowChart::getNodeType(flo.type),flo.stamp,flo.id);
    }
    else if (flo.type & COMMENT_NO)
    {
      printf("\n NO: %s%s[%d,%d]",t.c_str(),FlowChart::getNodeType(flo.type),flo.stamp,flo.id);
    }
    else
    {
      printf("\n NO: %s[%d,%d]",t.c_str(),flo.stamp,flo.id);
    }
  }
}
References COMMENT_NO, EMPTNODE, exp, QCString::fill(), getNodeType(), id, label, QCString::left(), qPrint(), reg::replace(), stamp, STARTL, QCString::str(), string, QCString::stripWhiteSpace(), text, and type.
Referenced by printFlowTree().
printNode() [2/2]
static void FlowChart::printNode (const FlowChart & n) [static]
printPlantUmlNode() [1/2]
QCString FlowChart::printPlantUmlNode (const FlowChart & flo, bool ca, bool endL) [static]
Definition at line 3282 of file vhdldocgen.cpp.
{
  QCString t;
  QCString exp=flo.exp.stripWhiteSpace();
  QCString text=flo.text.stripWhiteSpace();
  switch (flo.type)
  {
    case START_NO: t=":"+text+"|"; break;
    case IF_NO : t="\nif ("+exp+") then (yes)"; break;
    case ELSIF_NO: t="\nelseif ("+exp+") then (yes)"; break;
    case ELSE_NO: t="\nelse"; break;
    case CASE_NO: t="\n:"+exp+";"; break;
    case WHEN_NO: t="\n";
                     if (!ca) t+="else";
                     t+="if ("+exp+") then (yes)";
                     break;
    case EXIT_NO: break;
    case END_NO: if (text.contains(" function")==0) t="\n:"+text+";";
                     break;
    case TEXT_NO: t="\n:"+text+"]"; break;
    case ENDIF_NO: t="\nendif"; break;
    case FOR_NO: t="\nwhile ("+exp+") is (yes)"; break;
    case WHILE_NO: t="\nwhile ("+exp+") is (yes)"; break;
    case END_LOOP: t="\nendwhile"; break;
    case END_CASE: t="\nendif\n:end case;"; break;
    case VARIABLE_NO:t="\n:"+text+";"; break;
    case RETURN_NO: t="\n:"+text+";";
                     if (!endL) t+="\nstop";
                     break;
    case LOOP_NO: t="\nwhile (infinite loop)"; break;
    case NEXT_NO: break;
    case EMPTY_NO: break;
    case COMMENT_NO: t="\n note left \n "+flo.label+"\nend note \n"; break;
    case BEGIN_NO: t="\n:begin;"; break;
    default: assert(false); break;
  }
  return t;
}
References BEGIN_NO, CASE_NO, COMMENT_NO, QCString::contains(), ELSE_NO, ELSIF_NO, EMPTY_NO, END_CASE, END_LOOP, END_NO, ENDIF_NO, EXIT_NO, exp, FOR_NO, IF_NO, label, LOOP_NO, NEXT_NO, RETURN_NO, START_NO, QCString::stripWhiteSpace(), text, TEXT_NO, type, VARIABLE_NO, WHEN_NO, and WHILE_NO.
Referenced by printUmlTree().
printPlantUmlNode() [2/2]
static QCString FlowChart::printPlantUmlNode (const FlowChart & flo, bool , bool) [static]
printUmlTree() [1/2]
void FlowChart::printUmlTree () [static]
Definition at line 3321 of file vhdldocgen.cpp.
{
  int caseCounter = 0;
  int whenCounter = 0;
  QCString qcs;
  size_t size=flowList.size();
  for (size_t j=0;j<size;j++)
  {
    bool endList = j==FLOWLEN;
    const FlowChart &flo = flowList[j];
    if (flo.type==CASE_NO)
    {
      caseCounter++;
      whenCounter=0;
    }
    if (flo.type==END_CASE)
    {
      caseCounter--;
    }
    bool ca = (caseCounter>0 && whenCounter==0);
    qcs+=printPlantUmlNode(flo,ca,endList);
    if (flo.type==WHEN_NO)
    {
      whenCounter++;
    }
  }
  qcs+="\n";
  QCString htmlOutDir = Config_getString(HTML_OUTPUT);
  QCString n=convertNameToFileName();
  n=PlantumlManager::instance().writePlantUMLSource(htmlOutDir,n,qcs,PlantumlManager::PUML_SVG,"uml",n,1);
  PlantumlManager::instance().generatePlantUMLOutput(n,htmlOutDir,PlantumlManager::PUML_SVG);
}
References CASE_NO, Config_getString, convertNameToFileName(), END_CASE, FLOWLEN, flowList, PlantumlManager::generatePlantUMLOutput(), PlantumlManager::instance(), n, printPlantUmlNode(), PlantumlManager::PUML_SVG, size, type, WHEN_NO, and PlantumlManager::writePlantUMLSource().
Referenced by writeFlowChart().
printUmlTree() [2/2]
static void FlowChart::printUmlTree () [static]
startDot() [1/2]
void FlowChart::startDot (TextStream & t) [static]
Definition at line 3418 of file vhdldocgen.cpp.
{
  t << " digraph G { \n";
  t << "rankdir=TB \n";
  t << "concentrate=true\n";
  t << "stylesheet=\"doxygen.css\"\n";
}
Referenced by writeFlowChart().
startDot() [2/2]
static void FlowChart::startDot (TextStream & t) [static]
writeEdge() [1/4]
void FlowChart::writeEdge (TextStream & t, const FlowChart & fl_from, const FlowChart & fl_to, int i) [static]
Definition at line 3578 of file vhdldocgen.cpp.
{
  bool b=fl_from.type & STARTL;
  bool c=fl_to.type & STARTL;
#ifdef DEBUGFLOW
  QCString s1(getNodeName(fl_from.id));
  QCString s2(getNodeName(fl_to.id));
  auto it = g_keyMap.find(s1.str());
  auto it1 = g_keyMap.find(s2.str());
  // checks if the link is connected to a valid node
  assert(it!=g_keyMap.end());
  assert(it1!=g_keyMap.end());
#endif
  writeEdge(t,fl_from.id,fl_to.id,i,b,c);
}
References b, c, getNodeName(), id, STARTL, QCString::str(), type, and writeEdge().
writeEdge() [2/4]
static void FlowChart::writeEdge (TextStream & t, const FlowChart & fl_from, const FlowChart & fl_to, int i) [static]
writeEdge() [3/4]
void FlowChart::writeEdge (TextStream & t, int fl_from, int fl_to, int i, bool bFrom = FALSE, bool bTo = FALSE) [static]
Definition at line 3596 of file vhdldocgen.cpp.
{
  QCString label,col;
  if (i==0)
  {
    col=flowCol.yesNodeLink;
    label="yes";
  }
  else if (i==1)
  {
    col=flowCol.noNodeLink;
    label="no";
  }
  else
  {
    col=flowCol.textNodeLink;
    label="";
  }
  t << "edge [color=\""+col+"\",label=\""+label+"\"]\n";
  t << getNodeName(fl_from);
  if (bFrom) t << ":s";
  t << "->";
  t << getNodeName(fl_to);
  if (bTo) t << ":n";
  t << "\n";
}
References flowCol, getNodeName(), and label.
Referenced by buildCommentNodes(), writeEdge(), and writeFlowLinks().
writeEdge() [4/4]
static void FlowChart::writeEdge (TextStream & t, int fl_from, int fl_to, int i, bool bFrom = FALSE, bool bTo = FALSE) [static]
writeFlowChart() [1/2]
void FlowChart::writeFlowChart () [static]
Definition at line 3431 of file vhdldocgen.cpp.
{
  // assert(VhdlDocGen::flowMember);
  QCString ov = Config_getString(HTML_OUTPUT);
  QCString fileName = ov+"/flow_design.dot";
  std::ofstream f(fileName.str(),std::ofstream::out | std::ofstream::binary);
  if (!f.is_open())
  {
    err("Cannot open file %s for writing\n",qPrint(fileName));
    return;
  }
  TextStream t(&f);
  colTextNodes();
  // buildCommentNodes(t);
#ifdef DEBUGFLOW
   printFlowTree();
#endif
  if (!Config_getString(PLANTUML_JAR_PATH).isEmpty())
  {
    printUmlTree();
    delFlowList();
    t.flush();
    f.close();
    return;
  }
  startDot(t);
  buildCommentNodes(t);
  for (const auto &fll : flowList)
  {
    writeShape(t,fll);
  }
  writeFlowLinks(t);
  FlowChart::endDot(t);
  delFlowList();
  t.flush();
  f.close();
  FlowChart::createSVG();
}// writeFlowChart
References buildCommentNodes(), colTextNodes(), Config_getString, createSVG(), delFlowList(), endDot(), err(), f, flowList, TextStream::flush(), out, printFlowTree(), printUmlTree(), qPrint(), startDot(), QCString::str(), writeFlowLinks(), and writeShape().
Referenced by VHDLOutlineParser::createFlow().
writeFlowChart() [2/2]
static void FlowChart::writeFlowChart () [static]
writeFlowLinks() [1/2]
void FlowChart::writeFlowLinks (TextStream & t) [static]
Definition at line 3788 of file vhdldocgen.cpp.
{
  size_t size=flowList.size();
  if (size<2) return;
  // write start link
  writeEdge(t,flowList[0],flowList[1],2);
  for (size_t j=0;j<size;j++)
  {
    const FlowChart &fll = flowList[j];
    int kind = fll.type;
    int stamp = fll.stamp;
    if (kind & EEND)
    {
      continue;
    }
    if (kind & IFF)
    {
      writeEdge(t,fll,flowList[j+1],0);
      size_t z=getNextIfLink(fll,j);
      // assert(z>-1);
      writeEdge(t,fll,flowList[z],1);
    }
    else if (kind & LOOP_NO)
    {
      writeEdge(t,fll,flowList[j+1],2);
      continue;
    }
    else if (kind & (CASE_NO | FOR_NO | WHILE_NO))
    {
      if (kind & CASE_NO)
      {
        writeEdge(t,fll,flowList[j+1],2);
        continue;
      }
      else
      {
        writeEdge(t,fll,flowList[j+1],0);
      }
      kind=END_LOOP;
      size_t z=findNode(j+1,fll.stamp,kind);
      z=getNextNode(z,flowList[z].stamp);
      // assert(z>-1);
      writeEdge(t,fll,flowList[z],1);
      continue;
    }
    else if (kind & (TEXT_NO | VARIABLE_NO))
    {
      size_t z=getNextNode(j,stamp);
      writeEdge(t,fll,flowList[z],2);
    }
    else if (kind & WHEN_NO)
    {
      // default value
      if (qstricmp(fll.text.simplifyWhiteSpace(),"others")==0)
      {
        writeEdge(t,fll,flowList[j+1],2);
        continue;
      }
      writeEdge(t,fll,flowList[j+1],0);
      size_t u=findNode(j,stamp,WHEN_NO);
      size_t v=findNode(j,stamp-1,END_CASE);
      if (u>0 && u<v)
      {
        writeEdge(t,fll,flowList[u],1);
      }
      else
      {
        writeEdge(t,fll,flowList[v],1);
      }
    }
    else if (kind & END_CASE)
    {
      size_t z=FlowChart::getNextNode(j,fll.stamp);
      writeEdge(t,fll,flowList[z],2);
    }
    else if (kind & END_LOOP)
    {
      size_t z=findPrevLoop(j,fll.stamp,true);
      writeEdge(t,fll,flowList[z],2);
    }
    else if (kind & RETURN_NO)
    {
      writeEdge(t,fll,flowList[size-1],2);
    }
    else if (kind & (EXIT_NO | NEXT_NO))
    {
      size_t z;
      bool b = kind==NEXT_NO;
      if (!fll.exp.isEmpty())
      {
        writeEdge(t,fll,flowList[j+1],1);
      }
      if (!fll.label.isEmpty())
      {
        z=findLabel(j,fll.label);
        if (b)
        {
          writeEdge(t,fll,flowList[z],0);
        }
        else
        {
          z=findNode(z,flowList[z].stamp,END_LOOP);
          z=getNextNode(z,flowList[z].stamp);
          writeEdge(t,fll,flowList[z],0);
        }
        continue;
      }
      else
      {
        if (b)
        {
          z=findPrevLoop(j,fll.stamp);
          writeEdge(t,fll,flowList[z],0);
          continue;
        }
        else
        {
          z =findNextLoop(j,fll.stamp-1);
        }
        z=getNextNode(z,flowList[z].stamp);
      }
      writeEdge(t,fll,flowList[z],0);
    }
  } //for
} //writeFlowLinks
References b, CASE_NO, EEND, END_CASE, END_LOOP, EXIT_NO, exp, findLabel(), findNextLoop(), findNode(), findPrevLoop(), flowList, FOR_NO, getNextIfLink(), getNextNode(), IFF, QCString::isEmpty(), label, LOOP_NO, NEXT_NO, qstricmp(), RETURN_NO, QCString::simplifyWhiteSpace(), size, stamp, text, TEXT_NO, type, VARIABLE_NO, WHEN_NO, WHILE_NO, and writeEdge().
Referenced by writeFlowChart().
writeFlowLinks() [2/2]
static void FlowChart::writeFlowLinks (TextStream & t) [static]
writeShape() [1/2]
void FlowChart::writeShape (TextStream & t, const FlowChart & fl) [static]
Definition at line 3476 of file vhdldocgen.cpp.
{
  if (fl.type & EEND) return;
  QCString var;
  if (fl.type & LOOP)
  {
    var=" loop";
  }
  else if (fl.type & IFF)
  {
    var=" then";
  }
  else
  {
    var="";
  }
  t << getNodeName(fl.id);
#ifdef DEBUGFLOW
  QCString qq(getNodeName(fl.id));
  g_keyMap.insert({qq.str(),fl.id});
#endif
  bool dec=(fl.type & DECLN);
  bool exit=(fl.type & EXITNEXT);
  if (exit && !fl.exp.isEmpty())
  {
    dec=TRUE;
  }
  if (dec)
  {
    QCString exp=fl.exp;
    alignText(exp);
    t << " [shape=diamond,style=filled,color=\"";
    t << flowCol.decisionNode;
    t << "\",label=\" ";
    QCString kl;
    if (exit) kl=fl.text+" ";
    if (!fl.label.isEmpty())
    {
      kl+=fl.label+":"+exp+var;
    }
    else
    {
      kl+=exp+var;
    }
    FlowChart::alignCommentNode(t,kl);
    t << "\"]\n";
  }
  else if (fl.type & ENDCL)
  {
    QCString val=fl.text;
    t << " [shape=ellipse ,label=\""+val+"\"]\n";
  }
  else if (fl.type & STARTFIN)
  {
    QCString val=fl.text;
    t << "[shape=box , style=rounded label=<\n";
    t << "<TABLE BORDER=\"0\" CELLBORDER=\"0\" CELLSPACING=\"0\" CELLPADDING=\"0\" >\n ";
    t << "<TR><TD BGCOLOR=\"";
    t<< flowCol.startEndNode;
    t<< "\"> ";
    FlowChart::alignCommentNode(t,val);
    t << " </TD></TR></TABLE>>];";
  }
  else
  {
    if (fl.text.isEmpty()) return;
    bool isVar=(fl.type & FlowChart::VARIABLE_NO);
    QCString q=fl.text;
    if (exit)
    {
      q+=" "+fl.label;
    }
    int z=q.findRev("\n");
    if (z==static_cast<int>(q.length())-1)
    {
      q=q.remove(z,2);
    }
    t << "[shape=none margin=0.1, label=<\n";
    t << "<TABLE BORDER=\"0\" CELLBORDER=\"1\" CELLSPACING=\"0\" CELLPADDING=\"2\" >\n ";
    if (isVar)
    {
      t << "<TR><TD BGCOLOR=\"" << flowCol.varNode << "\" > ";
    }
    else
    {
      t << "<TR><TD BGCOLOR=\"" << flowCol.textNode << "\" > ";
    }
    FlowChart::alignCommentNode(t,q);
    t << " </TD></TR></TABLE>>];";
  }
}
References alignCommentNode(), alignText(), DECLN, EEND, ENDCL, EXITNEXT, exp, QCString::findRev(), flowCol, getNodeName(), id, IFF, QCString::isEmpty(), label, QCString::length(), LOOP, QCString::remove(), STARTFIN, QCString::str(), text, TRUE, type, testsqlite3::val, var, and VARIABLE_NO.
Referenced by writeFlowChart().
writeShape() [2/2]
static void FlowChart::writeShape (TextStream & t, const FlowChart & fl) [static]
Member Data Documentation
exp
QCString FlowChart::exp [private]
Definition at line 349 of file vhdldocgen.h.
Referenced by addFlowChart(), FlowChart(), printNode(), printPlantUmlNode(), writeFlowLinks(), and writeShape().
id
int FlowChart::id = 0 [private]
Definition at line 341 of file vhdldocgen.h.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), buildCommentNodes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), printNode(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), doxmlparser.compound.docXRefSectType::set_id(), writeEdge(), and writeShape().
label
QCString FlowChart::label [private]
Definition at line 347 of file vhdldocgen.h.
Referenced by doxmlparser.compound.nodeType::__init__(), addFlowChart(), doxmlparser.compound.nodeType::buildChildren(), buildCommentNodes(), doxmlparser.compound.nodeType::exportChildren(), findLabel(), FlowChart(), doxmlparser.compound.nodeType::get_label(), doxmlparser.compound.nodeType::hasContent_(), printNode(), printPlantUmlNode(), doxmlparser.compound.nodeType::set_label(), writeEdge(), writeFlowLinks(), and writeShape().
line
int FlowChart::line = 0 [private]
Definition at line 345 of file vhdldocgen.h.
Referenced by doxmlparser.compound.locationType::__init__(), doxmlparser.compound.locationType::buildAttributes(), buildCommentNodes(), doxmlparser.compound.locationType::exportAttributes(), doxmlparser.compound.locationType::get_line(), and doxmlparser.compound.locationType::set_line().
stamp
int FlowChart::stamp = 0 [private]
Definition at line 342 of file vhdldocgen.h.
Referenced by colTextNodes(), findNextLoop(), findNode(), findPrevLoop(), FlowChart(), getNextIfLink(), getNextNode(), printNode(), and writeFlowLinks().
text
QCString FlowChart::text [private]
Definition at line 348 of file vhdldocgen.h.
Referenced by addFlowChart(), colTextNodes(), FlowChart(), printNode(), printPlantUmlNode(), writeFlowLinks(), and writeShape().
type
int FlowChart::type = 0 [private]
Definition at line 343 of file vhdldocgen.h.
Referenced by addFlowChart(), buildCommentNodes(), colTextNodes(), findLabel(), findNextLoop(), findNode(), findPrevLoop(), FlowChart(), getNextNode(), printNode(), printPlantUmlNode(), printUmlTree(), writeEdge(), writeFlowLinks(), and writeShape().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/vhdldocgen.h
doxygen/src/vhdldocgen.h
doxygen/build/doxygen/src/vhdldocgen.cpp
doxygen/src/vhdldocgen.cpp