FileListContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
FileListContext ()
virtual ~FileListContext ()
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
FileListContext ()
virtual ~FileListContext ()
Static Public Member Functions
static TemplateListIntfPtr alloc ()
static TemplateListIntfPtr alloc ()
Private Attributes
std::unique_ptr< Private > p
Additional Inherited Members
Detailed Description
Definition at line 669 of file context.h.
Constructor & Destructor Documentation
FileListContext() [1/2]
FileListContext::FileListContext ()
Definition at line 6360 of file context.cpp.
                                 : p(std::make_unique<Private>())
{
  if (Doxygen::inputNameLinkedMap) p->addFiles(*Doxygen::inputNameLinkedMap);
}
References Doxygen::inputNameLinkedMap, and p.
 FileListContext() [1/2]
FileListContext::~FileListContext () [virtual]
Definition at line 6365 of file context.cpp.
{
}
FileListContext() [2/2]
FileListContext::FileListContext ()
 FileListContext() [2/2]
virtual FileListContext::~FileListContext () [virtual]
Member Function Documentation
alloc() [1/2]
static TemplateListIntfPtr FileListContext::alloc () [inline], [static]
Definition at line 672 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<FileListContext>()); }
Referenced by generateOutputViaTemplate().
alloc() [2/2]
static TemplateListIntfPtr FileListContext::alloc () [inline], [static]
Definition at line 672 of file context.h.
    { return std::static_pointer_cast<TemplateListIntf>(std::make_shared<FileListContext>()); }
at() [1/2]
TemplateVariant FileListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 6375 of file context.cpp.
{
  return p->at(index);
}
References p.
at() [2/2]
virtual TemplateVariant FileListContext::at (size_t index) const [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
count() [1/2]
size_t FileListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Definition at line 6370 of file context.cpp.
{
  return p->count();
}
References p.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
count() [2/2]
virtual size_t FileListContext::count () const [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
createIterator() [1/2]
TemplateListIntf::ConstIteratorPtr FileListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 6380 of file context.cpp.
{
  return p->createIterator();
}
References p.
createIterator() [2/2]
virtual TemplateListIntf::ConstIteratorPtr FileListContext::createIterator () const [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Member Data Documentation
p
std::unique_ptr< Private > FileListContext::p [private]
Definition at line 685 of file context.h.
Referenced by at(), count(), createIterator(), and FileListContext().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.h
doxygen/src/context.h
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp