HtmlDocVisitor Class Reference
Concrete visitor implementation for HTML output.
#include <htmldocvisitor.h>
Public Member Functions
HtmlDocVisitor (TextStream &t, CodeOutputInterface &ci, const Definition *ctx)
void operator() (const DocWord &)
void operator() (const DocLinkedWord &)
void operator() (const DocWhiteSpace &)
void operator() (const DocSymbol &)
void operator() (const DocEmoji &)
void operator() (const DocURL &)
void operator() (const DocLineBreak &)
void operator() (const DocHorRuler &)
void operator() (const DocStyleChange &)
void operator() (const DocVerbatim &)
void operator() (const DocAnchor &)
void operator() (const DocInclude &)
void operator() (const DocIncOperator &)
void operator() (const DocFormula &)
void operator() (const DocIndexEntry &)
void operator() (const DocSimpleSectSep &)
void operator() (const DocCite &)
void operator() (const DocSeparator &)
void operator() (const DocAutoList &)
void operator() (const DocAutoListItem &)
void operator() (const DocPara &)
void operator() (const DocRoot &)
void operator() (const DocSimpleSect &)
void operator() (const DocTitle &)
void operator() (const DocSimpleList &)
void operator() (const DocSimpleListItem &)
void operator() (const DocSection &)
void operator() (const DocHtmlList &)
void operator() (const DocHtmlListItem &)
void operator() (const DocHtmlDescList &)
void operator() (const DocHtmlDescTitle &)
void operator() (const DocHtmlDescData &)
void operator() (const DocHtmlTable &)
void operator() (const DocHtmlRow &)
void operator() (const DocHtmlCell &)
void operator() (const DocHtmlCaption &)
void operator() (const DocInternal &)
void operator() (const DocHRef &)
void operator() (const DocHtmlSummary &)
void operator() (const DocHtmlDetails &)
void operator() (const DocHtmlHeader &)
void operator() (const DocImage &)
void operator() (const DocDotFile &)
void operator() (const DocMscFile &)
void operator() (const DocDiaFile &)
void operator() (const DocLink &)
void operator() (const DocRef &)
void operator() (const DocSecRefItem &)
void operator() (const DocSecRefList &)
void operator() (const DocParamSect &)
void operator() (const DocParamList &)
void operator() (const DocXRefItem &)
void operator() (const DocInternalRef &)
void operator() (const DocText &)
void operator() (const DocHtmlBlockQuote &)
void operator() (const DocVhdlFlow &)
void operator() (const DocParBlock &)
HtmlDocVisitor (TextStream &t, CodeOutputInterface &ci, const Definition *ctx)
void operator() (const DocWord &)
void operator() (const DocLinkedWord &)
void operator() (const DocWhiteSpace &)
void operator() (const DocSymbol &)
void operator() (const DocEmoji &)
void operator() (const DocURL &)
void operator() (const DocLineBreak &)
void operator() (const DocHorRuler &)
void operator() (const DocStyleChange &)
void operator() (const DocVerbatim &)
void operator() (const DocAnchor &)
void operator() (const DocInclude &)
void operator() (const DocIncOperator &)
void operator() (const DocFormula &)
void operator() (const DocIndexEntry &)
void operator() (const DocSimpleSectSep &)
void operator() (const DocCite &)
void operator() (const DocSeparator &)
void operator() (const DocAutoList &)
void operator() (const DocAutoListItem &)
void operator() (const DocPara &)
void operator() (const DocRoot &)
void operator() (const DocSimpleSect &)
void operator() (const DocTitle &)
void operator() (const DocSimpleList &)
void operator() (const DocSimpleListItem &)
void operator() (const DocSection &)
void operator() (const DocHtmlList &)
void operator() (const DocHtmlListItem &)
void operator() (const DocHtmlDescList &)
void operator() (const DocHtmlDescTitle &)
void operator() (const DocHtmlDescData &)
void operator() (const DocHtmlTable &)
void operator() (const DocHtmlRow &)
void operator() (const DocHtmlCell &)
void operator() (const DocHtmlCaption &)
void operator() (const DocInternal &)
void operator() (const DocHRef &)
void operator() (const DocHtmlSummary &)
void operator() (const DocHtmlDetails &)
void operator() (const DocHtmlHeader &)
void operator() (const DocImage &)
void operator() (const DocDotFile &)
void operator() (const DocMscFile &)
void operator() (const DocDiaFile &)
void operator() (const DocLink &)
void operator() (const DocRef &)
void operator() (const DocSecRefItem &)
void operator() (const DocSecRefList &)
void operator() (const DocParamSect &)
void operator() (const DocParamList &)
void operator() (const DocXRefItem &)
void operator() (const DocInternalRef &)
void operator() (const DocText &)
void operator() (const DocHtmlBlockQuote &)
void operator() (const DocVhdlFlow &)
void operator() (const DocParBlock &)
template<class Node >
void forceEndParagraph (const Node &n)
template<class Node >
void forceStartParagraph (const Node &n)
Private Member Functions
template<class T >
void visitChildren (const T &t)
template<class T >
void visitCaption (TextStream &t, const T &n)
void writeObfuscatedMailAddress (const QCString &url)
void filter (const QCString &str, const bool retainNewline=false)
QCString filterQuotedCdataAttr (const QCString &str)
void startLink (const QCString &ref, const QCString &file, const QCString &relPath, const QCString &anchor, const QCString &tooltip=``)
void endLink ()
void writeDotFile (const QCString &fileName, const QCString &relPath, const QCString &context, const QCString &srcFile, int srcLine)
void writeMscFile (const QCString &fileName, const QCString &relPath, const QCString &context, const QCString &srcFile, int srcLine)
void writeDiaFile (const QCString &fileName, const QCString &relPath, const QCString &context, const QCString &srcFile, int srcLine)
void writePlantUMLFile (const QCString &fileName, const QCString &relPath, const QCString &context, const QCString &srcFile, int srcLine)
template<class DocNode >
void forceEndParagraph (const DocNode &n)
template<class DocNode >
void forceStartParagraph (const DocNode &n)
template<class T >
void visitChildren (const T &t)
template<class T >
void visitCaption (TextStream &t, const T &n)
void writeObfuscatedMailAddress (const QCString &url)
void filter (const QCString &str, const bool retainNewline=false)
QCString filterQuotedCdataAttr (const QCString &str)
void startLink (const QCString &ref, const QCString &file, const QCString &relPath, const QCString &anchor, const QCString &tooltip=``)
void endLink ()
void writeDotFile (const QCString &fileName, const QCString &relPath, const QCString &context, const QCString &srcFile, int srcLine)
void writeMscFile (const QCString &fileName, const QCString &relPath, const QCString &context, const QCString &srcFile, int srcLine)
void writeDiaFile (const QCString &fileName, const QCString &relPath, const QCString &context, const QCString &srcFile, int srcLine)
void writePlantUMLFile (const QCString &fileName, const QCString &relPath, const QCString &context, const QCString &srcFile, int srcLine)
template<class DocNode >
void forceEndParagraph (const DocNode &n)
template<class DocNode >
void forceStartParagraph (const DocNode &n)
Private Attributes
TextStream & m_t
CodeOutputInterface & m_ci
bool m_insidePre = false
bool m_hide = false
bool m_insideTitle = false
const Definition * m_ctx
QCString m_langExt
Detailed Description
Concrete visitor implementation for HTML output.
Definition at line 29 of file htmldocvisitor.h.
Constructor & Destructor Documentation
HtmlDocVisitor() [1/2]
HtmlDocVisitor::HtmlDocVisitor (TextStream & t, CodeOutputInterface & ci, const Definition * ctx)
Definition at line 277 of file htmldocvisitor.cpp.
  : m_t(t), m_ci(ci), m_ctx(ctx)
{
  if (ctx) m_langExt=ctx->getDefFileExtension();
}
References Definition::getDefFileExtension(), and m_langExt.
HtmlDocVisitor() [2/2]
HtmlDocVisitor::HtmlDocVisitor (TextStream & t, CodeOutputInterface & ci, const Definition * ctx)
Member Function Documentation
endLink() [1/2]
void HtmlDocVisitor::endLink () [private]
Definition at line 2178 of file htmldocvisitor.cpp.
{
  m_t << "</a>";
}
References m_t.
Referenced by operator()().
endLink() [2/2]
void HtmlDocVisitor::endLink () [private]
filter() [1/2]
void HtmlDocVisitor::filter (const QCString & str, const bool retainNewline = false) [private]
Definition at line 2066 of file htmldocvisitor.cpp.
{
  if (str.isEmpty()) return;
  const char *p=str.data();
  char c;
  while (*p)
  {
    c=*p++;
    switch(c)
    {
      case '\n': if(retainNewline) m_t << "<br/>"; m_t << c; break;
      case '<': m_t << "&lt;"; break;
      case '>': m_t << "&gt;"; break;
      case '&': m_t << "&amp;"; break;
      case '\\': if ((*p == '(') || (*p == ')'))
          m_t << "\\&zwj;" << *p++;
        else
          m_t << c;
        break;
      default:
        {
          uchar uc = static_cast<uchar>(c);
          if (uc<32 && !isspace(c)) // non-printable control characters
          {
            m_t << "&#x24" << hex[uc>>4] << hex[uc&0xF] << ";";
          }
          else
          {
            m_t << c;
          }
        }
        break;
    }
  }
}
References c, QCString::data(), hex, QCString::isEmpty(), reg::isspace(), m_t, and p.
Referenced by operator()().
filter() [2/2]
void HtmlDocVisitor::filter (const QCString & str, const bool retainNewline = false) [private]
filterQuotedCdataAttr() [1/2]
QCString HtmlDocVisitor::filterQuotedCdataAttr (const QCString & str) [private]
Escape basic entities to produce a valid CDATA attribute value, assume that the outer quoting will be using the double quote "
Definition at line 2104 of file htmldocvisitor.cpp.
{
  GrowBuf growBuf;
  if (str.isEmpty()) return str;
  const char *p=str.data();
  char c;
  while (*p)
  {
    c=*p++;
    switch(c)
    {
      case '&': growBuf.addStr("&amp;"); break;
      case '"': growBuf.addStr("&quot;"); break;
      case '<': growBuf.addStr("&lt;"); break;
      case '>': growBuf.addStr("&gt;"); break;
      case '\\':
        if ((*p == '(') || (*p == ')'))
        {
          growBuf.addStr("\\&zwj;");
          growBuf.addChar(*p++);
        }
        else
        {
          growBuf.addChar(c);
        }
        break;
      default:
        {
          uchar uc = static_cast<uchar>(c);
          if (uc<32 && !isspace(c)) // non-printable control characters
          {
            growBuf.addStr("&#x24");
            growBuf.addChar(hex[uc>>4]);
            growBuf.addChar(hex[uc&0xF]);
            growBuf.addStr(";");
          }
          else
          {
            growBuf.addChar(c);
          }
        }
        break;
    }
  }
  growBuf.addChar(0);
  return growBuf.get();
}
References GrowBuf::addChar(), GrowBuf::addStr(), c, QCString::data(), GrowBuf::get(), hex, QCString::isEmpty(), reg::isspace(), and p.
Referenced by operator()().
filterQuotedCdataAttr() [2/2]
QCString HtmlDocVisitor::filterQuotedCdataAttr (const QCString & str) [private]
forceEndParagraph() [1/3]
template<class DocNode >
void HtmlDocVisitor::forceEndParagraph (const DocNode & n) [private]
Referenced by operator()().
forceEndParagraph() [2/3]
template<class DocNode >
void HtmlDocVisitor::forceEndParagraph (const DocNode & n) [private]
forceEndParagraph() [3/3]
template<class Node >
void HtmlDocVisitor::forceEndParagraph (const Node & n)
Used for items found inside a paragraph, which due to XHTML restrictions have to be outside of the paragraph. This method will forcefully end the current paragraph and forceStartParagraph() will restart it.
Definition at line 2324 of file htmldocvisitor.cpp.
{
  const DocPara *para=std::get_if<DocPara>(n.parent());
  if (para)
  {
    const DocNodeList &children = para->children();
    //printf("forceEndParagraph\n");
    //dumpDocNodeList(children);
    auto it = std::find_if(std::begin(children),std::end(children),
        [&n](const auto &np) { return holds_value(&n,np); });
    if (it==std::end(children)) return;
    if (it==std::begin(children)) return; // first node in paragraph
    it = std::prev(it);
    bool found=false;
    while (!found)
    {
      found = !isInvisibleNode(*it);
      if (found) break;
      if (it!=std::begin(children))
      {
        --it;
      }
      else
      {
        break;
      }
    }
    if (!found) return; // first visible node in paragraph
    const DocNodeVariant &v = *it;
    if (mustBeOutsideParagraph(v)) return; // previous node already outside paragraph context
    bool styleOutsideParagraph=false;
    if (it!=std::begin(children))
    {
      it = std::prev(it);
      styleOutsideParagraph=insideStyleChangeThatIsOutsideParagraph(para,it);
    }
    bool isFirst;
    bool isLast;
    getParagraphContext(*para,isFirst,isLast);
    //printf("forceEnd first=%d last=%d styleOutsideParagraph=%d\n",isFirst,isLast,styleOutsideParagraph);
    if (isFirst && isLast) return;
    if (styleOutsideParagraph) return;
    //printf("adding </p>\n");
    m_t << "</p>";
  }
}
References ghc::filesystem::begin(), DocCompoundNode::children(), ghc::filesystem::end(), found, getParagraphContext(), holds_value(), insideStyleChangeThatIsOutsideParagraph(), isInvisibleNode(), m_t, mustBeOutsideParagraph(), and n.
forceStartParagraph() [1/3]
template<class DocNode >
void HtmlDocVisitor::forceStartParagraph (const DocNode & n) [private]
Referenced by operator()().
forceStartParagraph() [2/3]
template<class DocNode >
void HtmlDocVisitor::forceStartParagraph (const DocNode & n) [private]
forceStartParagraph() [3/3]
template<class Node >
void HtmlDocVisitor::forceStartParagraph (const Node & n)
Used for items found inside a paragraph, which due to XHTML restrictions have to be outside of the paragraph. This method will forcefully start the paragraph, that was previously ended by forceEndParagraph().
Definition at line 2379 of file htmldocvisitor.cpp.
{
  //printf("> forceStartParagraph(%s)\n",docNodeName(n));
  const DocPara *para=0;
  if (n.parent() && (para = std::get_if<DocPara>(n.parent()))) // if we are inside a paragraph
  {
    const DocNodeList &children = para->children();
    auto it = std::find_if(std::begin(children),
                           std::end(children),
                           [&n](const auto &np)
                           { return holds_value(&n,np); });
    if (it==std::end(children)) return;
    bool styleOutsideParagraph=insideStyleChangeThatIsOutsideParagraph(para,it);
    //printf("it=%s (%p) styleOutsideParagraph=%d\n",
    // docNodeName(*it), (void *)&*it, styleOutsideParagraph);
    if (styleOutsideParagraph) return;
    it = std::next(it);
    while (it!=std::end(children) && isInvisibleNode(*it))
    {
      ++it;
    }
    if (it!=std::end(children))
    {
      const DocNodeVariant &v = *it;
      if (mustBeOutsideParagraph(v)) return; // next element also outside paragraph
    }
    else
    {
      return; // only whitespace at the end!
    }
    bool needsTag = TRUE;
    bool isFirst;
    bool isLast;
    getParagraphContext(*para,isFirst,isLast);
    if (isFirst && isLast) needsTag = FALSE;
    //printf("forceStart first=%d last=%d needsTag=%d\n",isFirst,isLast,needsTag);
    if (needsTag) m_t << "<p>";
  }
}
References ghc::filesystem::begin(), DocCompoundNode::children(), ghc::filesystem::end(), FALSE, getParagraphContext(), holds_value(), insideStyleChangeThatIsOutsideParagraph(), isInvisibleNode(), m_t, mustBeOutsideParagraph(), n, and TRUE.
operator()() [1/114]
void HtmlDocVisitor::operator() (const DocAnchor & anc)
Definition at line 685 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<a class=\"anchor\" id=\"" << anc.anchor() << "\"" << htmlAttribsToString(anc.attribs()) << "></a>";
}
References DocAnchor::anchor(), DocAnchor::attribs(), htmlAttribsToString(), m_hide, and m_t.
operator()() [2/114]
void HtmlDocVisitor::operator() (const DocAnchor &)
operator()() [3/114]
void HtmlDocVisitor::operator() (const DocAutoList & l)
Definition at line 1039 of file htmldocvisitor.cpp.
{
  //printf("DocAutoList::visitPre\n");
  if (m_hide) return;
  forceEndParagraph(l);
  if (l.isEnumList())
  {
    //
    // Do list type based on depth:
    // 1.
    // a.
    // i.
    // A.
    // 1. (repeat)...
    //
    m_t << "<ol type=\"" << types[l.depth() % NUM_HTML_LIST_TYPES] << "\">";
  }
  else
  {
    m_t << "<ul>";
  }
  if (!l.isPreformatted()) m_t << "\n";
  visitChildren(l);
  if (l.isEnumList())
  {
    m_t << "</ol>";
  }
  else
  {
    m_t << "</ul>";
  }
  if (!l.isPreformatted()) m_t << "\n";
  forceStartParagraph(l);
}
References DocAutoList::depth(), forceEndParagraph(), forceStartParagraph(), DocAutoList::isEnumList(), DocNode::isPreformatted(), m_hide, m_t, NUM_HTML_LIST_TYPES, types, and visitChildren().
operator()() [4/114]
void HtmlDocVisitor::operator() (const DocAutoList &)
operator()() [5/114]
void HtmlDocVisitor::operator() (const DocAutoListItem & li)
Definition at line 1074 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<li>";
  visitChildren(li);
  m_t << "</li>";
  if (!li.isPreformatted()) m_t << "\n";
}
References DocNode::isPreformatted(), m_hide, m_t, and visitChildren().
operator()() [6/114]
void HtmlDocVisitor::operator() (const DocAutoListItem &)
operator()() [7/114]
void HtmlDocVisitor::operator() (const DocCite & cite)
Definition at line 1011 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  if (!cite.file().isEmpty())
  {
    startLink(cite.ref(),cite.file(),cite.relPath(),cite.anchor());
  }
  else
  {
    m_t << "<b>[";
  }
  filter(cite.text());
  if (!cite.file().isEmpty())
  {
    endLink();
  }
  else
  {
    m_t << "]</b>";
  }
}
References DocCite::anchor(), endLink(), DocCite::file(), filter(), QCString::isEmpty(), m_hide, m_t, DocCite::ref(), DocCite::relPath(), startLink(), and DocCite::text().
operator()() [8/114]
void HtmlDocVisitor::operator() (const DocCite &)
operator()() [9/114]
void HtmlDocVisitor::operator() (const DocDiaFile & df)
Definition at line 1817 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  if (!Config_getBool(DOT_CLEANUP)) copyFile(df.file(),Config_getString(HTML_OUTPUT)+"/"+stripPath(df.file()));
  m_t << "<div class=\"diagraph\">\n";
  writeDiaFile(df.file(),df.relPath(),df.context(),df.srcFile(),df.srcLine());
  if (df.hasCaption())
  {
    m_t << "<div class=\"caption\">\n";
  }
  visitChildren(df);
  if (df.hasCaption())
  {
    m_t << "</div>\n";
  }
  m_t << "</div>\n";
}
References Config_getBool, Config_getString, DocDiagramFileBase::context(), copyFile(), DocDiagramFileBase::file(), DocDiagramFileBase::hasCaption(), m_hide, m_t, DocDiagramFileBase::relPath(), DocDiagramFileBase::srcFile(), DocDiagramFileBase::srcLine(), stripPath(), visitChildren(), and writeDiaFile().
operator()() [10/114]
void HtmlDocVisitor::operator() (const DocDiaFile &)
operator()() [11/114]
void HtmlDocVisitor::operator() (const DocDotFile & df)
Definition at line 1781 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  if (!Config_getBool(DOT_CLEANUP)) copyFile(df.file(),Config_getString(HTML_OUTPUT)+"/"+stripPath(df.file()));
  m_t << "<div class=\"dotgraph\">\n";
  writeDotFile(df.file(),df.relPath(),df.context(),df.srcFile(),df.srcLine());
  if (df.hasCaption())
  {
    m_t << "<div class=\"caption\">\n";
  }
  visitChildren(df);
  if (df.hasCaption())
  {
    m_t << "</div>\n";
  }
  m_t << "</div>\n";
}
References Config_getBool, Config_getString, DocDiagramFileBase::context(), copyFile(), DocDiagramFileBase::file(), DocDiagramFileBase::hasCaption(), m_hide, m_t, DocDiagramFileBase::relPath(), DocDiagramFileBase::srcFile(), DocDiagramFileBase::srcLine(), stripPath(), visitChildren(), and writeDotFile().
operator()() [12/114]
void HtmlDocVisitor::operator() (const DocDotFile &)
operator()() [13/114]
void HtmlDocVisitor::operator() (const DocEmoji & s)
Definition at line 353 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  const char *res = EmojiEntityMapper::instance()->unicode(s.index());
  if (res)
  {
    m_t << "<span class=\"emoji\">" << res << "</span>";
  }
  else
  {
    m_t << s.name();
  }
}
References EmojiEntityMapper::instance(), m_hide, m_t, s, and EmojiEntityMapper::unicode().
operator()() [14/114]
void HtmlDocVisitor::operator() (const DocEmoji &)
operator()() [15/114]
void HtmlDocVisitor::operator() (const DocFormula & f)
Definition at line 876 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  bool bDisplay = !f.isInline();
  if (bDisplay)
  {
    forceEndParagraph(f);
    m_t << "<p class=\"formulaDsp\">\n";
  }
  if (Config_getBool(USE_MATHJAX))
  {
    QCString text = f.text();
    bool closeInline = FALSE;
    if (!bDisplay && !text.isEmpty() && text.at(0)=='$' &&
                      text.at(text.length()-1)=='$')
    {
      closeInline=TRUE;
      text = text.mid(1,text.length()-2);
      m_t << "\\(";
    }
    else if (!bDisplay && !text.isEmpty())
    {
      closeInline=TRUE;
      m_t << "\\(";
    }
    m_t << convertToHtml(text);
    if (closeInline)
    {
      m_t << "\\)";
    }
  }
  else
  {
    const Formula *formula = FormulaManager::instance().findFormula(f.id());
    enum class ImageType { Light, Dark };
    enum class Visibility { Always, Dark, Light, AutoDark, AutoLight };
    auto writeFormula = [&](ImageType imgType,Visibility visibility) -> QCString {
      // see https://chipcullen.com/how-to-have-dark-mode-image-that-works-with-user-choice for the design idea
      TextStream t;
      QCString extension = Config_getEnum(HTML_FORMULA_FORMAT)==HTML_FORMULA_FORMAT_t::svg ? ".svg":".png" ;
      if (visibility==Visibility::AutoDark || visibility==Visibility::AutoLight)
      {
        t << "<picture>";
        t << "<source srcset=\"" << f.relPath() << f.name();
        if (visibility==Visibility::AutoDark)
        {
          t << extension;
          t << "\" media=\"(prefers-color-scheme: light)\"";
        }
        else // AutoLight
        {
          t << "_dark";
          t << extension;
          t << "\" media=\"(prefers-color-scheme: dark)\"";
        }
        t << "/>";
      }
      t << "<img class=\"formula";
      t << (bDisplay ? "Dsp" : "Inl");
      if (visibility==Visibility::Light) t << " light-mode-visible";
      else if (visibility==Visibility::Dark) t << " dark-mode-visible";
      t << "\" alt=\"" << filterQuotedCdataAttr(f.text()) << "\"" << " src=\"" << f.relPath() << f.name();
      if (imgType==ImageType::Dark) t << "_dark";
      t << extension;
      if (formula && formula->width()!=-1)
      {
        t << "\" width=\"";
        t << formula->width();
      }
      if (formula && formula->height()!=-1)
      {
        t << "\" height=\"";
        t << formula->height();
      }
      t << "\"/>";
      if (visibility==Visibility::AutoDark || visibility==Visibility::AutoLight)
      {
        t << "</picture>";
      }
      return QCString(t.str());
    };
    auto colorStyle = Config_getEnum(HTML_COLORSTYLE);
    switch(colorStyle)
    {
      case HTML_COLORSTYLE_t::LIGHT:
        m_t << writeFormula(ImageType::Light,Visibility::Always);
        break;
      case HTML_COLORSTYLE_t::DARK:
        m_t << writeFormula(ImageType::Dark, Visibility::Always);
        break;
      case HTML_COLORSTYLE_t::AUTO_LIGHT:
        m_t << writeFormula(ImageType::Light, Visibility::AutoLight);
        break;
      case HTML_COLORSTYLE_t::AUTO_DARK:
        m_t << writeFormula(ImageType::Dark, Visibility::AutoDark);
        break;
      case HTML_COLORSTYLE_t::TOGGLE:
        // write the image twice and use javascript (darkmode_toggle.js) to show only one of them
        m_t << writeFormula(ImageType::Light,Visibility::Light);
        m_t << writeFormula(ImageType::Dark, Visibility::Dark);
        break;
    }
  }
  if (bDisplay)
  {
    m_t << "\n</p>\n";
    forceStartParagraph(f);
  }
}
References QCString::at(), Config_getBool, Config_getEnum, convertToHtml(), f, FALSE, filterQuotedCdataAttr(), FormulaManager::findFormula(), forceEndParagraph(), forceStartParagraph(), Formula::height(), FormulaManager::instance(), QCString::isEmpty(), QCString::length(), m_hide, m_t, QCString::mid(), TextStream::str(), TRUE, and Formula::width().
operator()() [16/114]
void HtmlDocVisitor::operator() (const DocFormula &)
operator()() [17/114]
void HtmlDocVisitor::operator() (const DocHorRuler & hr)
Definition at line 439 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  forceEndParagraph(hr);
  m_t << "<hr "<< htmlAttribsToString(hr.attribs()) << " />\n";
  forceStartParagraph(hr);
}
References DocHorRuler::attribs(), forceEndParagraph(), forceStartParagraph(), htmlAttribsToString(), m_hide, and m_t.
operator()() [18/114]
void HtmlDocVisitor::operator() (const DocHorRuler &)
operator()() [19/114]
void HtmlDocVisitor::operator() (const DocHRef & href)
Definition at line 1613 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  if (href.url().startsWith("mailto:"))
  {
    writeObfuscatedMailAddress(href.url().mid(7));
  }
  else
  {
    QCString url = correctURL(href.url(),href.relPath());
    m_t << "<a href=\"" << convertToHtml(url) << "\""
        << htmlAttribsToString(href.attribs()) << ">";
  }
  visitChildren(href);
  m_t << "</a>";
}
References DocHRef::attribs(), convertToHtml(), correctURL(), htmlAttribsToString(), m_hide, m_t, QCString::mid(), DocHRef::relPath(), QCString::startsWith(), setup::url, DocHRef::url(), visitChildren(), and writeObfuscatedMailAddress().
operator()() [20/114]
void HtmlDocVisitor::operator() (const DocHRef &)
operator()() [21/114]
void HtmlDocVisitor::operator() (const DocHtmlBlockQuote & b)
Definition at line 2023 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  forceEndParagraph(b);
  m_t << "<blockquote class=\"doxtable\"" << htmlAttribsToString(b.attribs()) << ">\n";
  visitChildren(b);
  m_t << "</blockquote>\n";
  forceStartParagraph(b);
}
References b, forceEndParagraph(), forceStartParagraph(), htmlAttribsToString(), m_hide, m_t, and visitChildren().
operator()() [22/114]
void HtmlDocVisitor::operator() (const DocHtmlBlockQuote &)
operator()() [23/114]
void HtmlDocVisitor::operator() (const DocHtmlCaption & c)
Definition at line 1599 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<caption" << htmlAttribsToString(c.attribs()) << ">";
  visitChildren(c);
  m_t << "</caption>\n";
}
References c, htmlAttribsToString(), m_hide, m_t, and visitChildren().
operator()() [24/114]
void HtmlDocVisitor::operator() (const DocHtmlCaption &)
operator()() [25/114]
void HtmlDocVisitor::operator() (const DocHtmlCell & c)
Definition at line 1584 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  if (c.isHeading())
  {
    m_t << "<th" << htmlAttribsToString(c.attribs()) << ">";
  }
  else
  {
    m_t << "<td" << htmlAttribsToString(c.attribs()) << ">";
  }
  visitChildren(c);
  if (c.isHeading()) m_t << "</th>"; else m_t << "</td>";
}
References c, htmlAttribsToString(), m_hide, m_t, and visitChildren().
operator()() [26/114]
void HtmlDocVisitor::operator() (const DocHtmlCell &)
operator()() [27/114]
void HtmlDocVisitor::operator() (const DocHtmlDescData & dd)
Definition at line 1535 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<dd" << htmlAttribsToString(dd.attribs()) << ">";
  visitChildren(dd);
  m_t << "</dd>\n";
}
References DocHtmlDescData::attribs(), htmlAttribsToString(), m_hide, m_t, and visitChildren().
operator()() [28/114]
void HtmlDocVisitor::operator() (const DocHtmlDescData &)
operator()() [29/114]
void HtmlDocVisitor::operator() (const DocHtmlDescList & dl)
Definition at line 1517 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  forceEndParagraph(dl);
  m_t << "<dl" << htmlAttribsToString(dl.attribs()) << ">\n";
  visitChildren(dl);
  m_t << "</dl>\n";
  forceStartParagraph(dl);
}
References DocHtmlDescList::attribs(), forceEndParagraph(), forceStartParagraph(), htmlAttribsToString(), m_hide, m_t, and visitChildren().
operator()() [30/114]
void HtmlDocVisitor::operator() (const DocHtmlDescList &)
operator()() [31/114]
void HtmlDocVisitor::operator() (const DocHtmlDescTitle & dt)
Definition at line 1527 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<dt" << htmlAttribsToString(dt.attribs()) << ">";
  visitChildren(dt);
  m_t << "</dt>\n";
}
References DocHtmlDescTitle::attribs(), htmlAttribsToString(), m_hide, m_t, and visitChildren().
operator()() [32/114]
void HtmlDocVisitor::operator() (const DocHtmlDescTitle &)
operator()() [33/114]
void HtmlDocVisitor::operator() (const DocHtmlDetails & d)
Definition at line 1638 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  forceEndParagraph(d);
  m_t << "<details " << htmlAttribsToString(d.attribs()) << ">\n";
  auto summary = d.summary();
  if (summary)
  {
    std::visit(*this,*summary);
  }
  visitChildren(d);
  m_t << "</details>\n";
  forceStartParagraph(d);
}
References DocHtmlDetails::attribs(), forceEndParagraph(), forceStartParagraph(), htmlAttribsToString(), m_hide, m_t, DocHtmlDetails::summary(), and visitChildren().
operator()() [34/114]
void HtmlDocVisitor::operator() (const DocHtmlDetails &)
operator()() [35/114]
void HtmlDocVisitor::operator() (const DocHtmlHeader & header)
Definition at line 1653 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  forceEndParagraph(header);
  m_t << "<h" << header.level() << htmlAttribsToString(header.attribs()) << ">";
  visitChildren(header);
  m_t << "</h" << header.level() << ">\n";
  forceStartParagraph(header);
}
References DocHtmlHeader::attribs(), forceEndParagraph(), forceStartParagraph(), htmlAttribsToString(), DocHtmlHeader::level(), m_hide, m_t, and visitChildren().
operator()() [36/114]
void HtmlDocVisitor::operator() (const DocHtmlHeader &)
operator()() [37/114]
void HtmlDocVisitor::operator() (const DocHtmlList & s)
Definition at line 1482 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  forceEndParagraph(s);
  if (s.type()==DocHtmlList::Ordered)
  {
    m_t << "<ol" << htmlAttribsToString(s.attribs());
  }
  else
  {
    m_t << "<ul" << htmlAttribsToString(s.attribs());
  }
  m_t << ">\n";
  visitChildren(s);
  if (s.type()==DocHtmlList::Ordered)
  {
    m_t << "</ol>";
  }
  else
  {
    m_t << "</ul>";
  }
  if (!s.isPreformatted()) m_t << "\n";
  forceStartParagraph(s);
}
References forceEndParagraph(), forceStartParagraph(), htmlAttribsToString(), m_hide, m_t, DocHtmlList::Ordered, s, and visitChildren().
operator()() [38/114]
void HtmlDocVisitor::operator() (const DocHtmlList &)
operator()() [39/114]
void HtmlDocVisitor::operator() (const DocHtmlListItem & i)
Definition at line 1508 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<li" << htmlAttribsToString(i.attribs()) << ">";
  if (!i.isPreformatted()) m_t << "\n";
  visitChildren(i);
  m_t << "</li>\n";
}
References DocHtmlListItem::attribs(), htmlAttribsToString(), DocNode::isPreformatted(), m_hide, m_t, and visitChildren().
operator()() [40/114]
void HtmlDocVisitor::operator() (const DocHtmlListItem &)
operator()() [41/114]
void HtmlDocVisitor::operator() (const DocHtmlRow & tr)
Definition at line 1576 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<tr" << htmlAttribsToString(tr.attribs()) << ">\n";
  visitChildren(tr);
  m_t << "</tr>\n";
}
References DocHtmlRow::attribs(), htmlAttribsToString(), m_hide, m_t, and visitChildren().
operator()() [42/114]
void HtmlDocVisitor::operator() (const DocHtmlRow &)
operator()() [43/114]
void HtmlDocVisitor::operator() (const DocHtmlSummary & s)
Definition at line 1630 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<summary " << htmlAttribsToString(s.attribs()) << ">\n";
  visitChildren(s);
  m_t << "</summary>\n";
}
References htmlAttribsToString(), m_hide, m_t, s, and visitChildren().
operator()() [44/114]
void HtmlDocVisitor::operator() (const DocHtmlSummary &)
operator()() [45/114]
void HtmlDocVisitor::operator() (const DocHtmlTable & t)
Definition at line 1543 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  forceEndParagraph(t);
  if (t.caption())
  {
    QCString anc = std::get<DocHtmlCaption>(*t.caption()).anchor();
    if (!anc.isEmpty())
    {
      m_t << "<a class=\"anchor\" id=\"" << anc << "\"></a>\n";
    }
  }
  QCString attrs = htmlAttribsToString(t.attribs());
  if (attrs.isEmpty())
  {
    m_t << "<table class=\"doxtable\">\n";
  }
  else
  {
    m_t << "<table" << htmlAttribsToString(t.attribs()) << ">\n";
  }
  if (t.caption())
  {
    std::visit(*this,*t.caption());
  }
  visitChildren(t);
  m_t << "</table>\n";
  forceStartParagraph(t);
}
References DocHtmlTable::attribs(), DocHtmlTable::caption(), forceEndParagraph(), forceStartParagraph(), htmlAttribsToString(), QCString::isEmpty(), m_hide, m_t, and visitChildren().
operator()() [46/114]
void HtmlDocVisitor::operator() (const DocHtmlTable &)
operator()() [47/114]
void HtmlDocVisitor::operator() (const DocImage & img)
Definition at line 1663 of file htmldocvisitor.cpp.
{
  if (img.type()==DocImage::Html)
  {
    bool inlineImage = img.isInlineImage();
    bool typeSVG = img.isSVG();
    QCString url = img.url();
    if (!inlineImage)
    {
      forceEndParagraph(img);
    }
    if (m_hide) return;
    QCString baseName=img.name();
    int i;
    if ((i=baseName.findRev('/'))!=-1 || (i=baseName.findRev('\\'))!=-1)
    {
      baseName=baseName.right(baseName.length()-i-1);
    }
    if (!inlineImage) m_t << "<div class=\"image\">\n";
    QCString sizeAttribs;
    if (!img.width().isEmpty())
    {
      sizeAttribs+=" width=\""+img.width()+"\"";
    }
    if (!img.height().isEmpty()) // link to local file
    {
      sizeAttribs+=" height=\""+img.height()+"\"";
    }
    // 16 cases: url.isEmpty() | typeSVG | inlineImage | img.hasCaption()
    HtmlAttribList extraAttribs;
    if (typeSVG)
    {
      HtmlAttrib opt;
      opt.name = "style";
      opt.value = "pointer-events: none;";
      extraAttribs.push_back(opt);
    }
    QCString alt;
    mergeHtmlAttributes(img.attribs(),extraAttribs);
    QCString attrs = htmlAttribsToString(extraAttribs,&alt);
    QCString src;
    if (url.isEmpty())
    {
      src = img.relPath()+img.name();
    }
    else
    {
      src = correctURL(url,img.relPath());
    }
    if (typeSVG && !inlineImage)
    {
      m_t << "<object type=\"image/svg+xml\" data=\"" << convertToHtml(src)
        << "\"" << sizeAttribs << attrs;
      if (inlineImage)
      {
        // skip closing tag
      }
      else
      {
        m_t << ">" << alt << "</object>\n";
      }
    }
    else
    {
      m_t << "<img src=\"" << convertToHtml(src) << "\" alt=\"" << alt << "\"" << sizeAttribs << attrs;
      if (inlineImage)
      {
        m_t << " class=\"inline\"";
      }
      else
      {
        m_t << "/>\n";
      }
    }
    if (img.hasCaption())
    {
      if (inlineImage)
      {
        m_t << " title=\"";
        m_insideTitle=true;
      }
      else
      {
        m_t << "<div class=\"caption\">\n";
      }
    }
    else if (inlineImage)
    {
      m_t << "/>";
    }
    visitChildren(img);
    if (img.hasCaption())
    {
      if (inlineImage)
      {
        m_t << "\"/>";
        m_insideTitle=false;
      }
      else // end <div class="caption">
      {
        m_t << "</div>";
      }
    }
    if (!inlineImage) // end <div class="image">
    {
      m_t << "</div>\n";
      forceStartParagraph(img);
    }
  }
  else // other format -> skip
  {
  }
}
References DocImage::attribs(), convertToHtml(), correctURL(), QCString::findRev(), forceEndParagraph(), forceStartParagraph(), DocImage::hasCaption(), DocImage::height(), DocImage::Html, htmlAttribsToString(), QCString::isEmpty(), DocImage::isInlineImage(), DocImage::isSVG(), QCString::length(), m_hide, m_insideTitle, m_t, mergeHtmlAttributes(), DocImage::name(), HtmlAttrib::name, DocImage::relPath(), QCString::right(), src, DocImage::type(), setup::url, DocImage::url(), HtmlAttrib::value, visitChildren(), and DocImage::width().
operator()() [48/114]
void HtmlDocVisitor::operator() (const DocImage &)
operator()() [49/114]
void HtmlDocVisitor::operator() (const DocInclude & inc)
Definition at line 691 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  SrcLangExt langExt = getLanguageFromFileName(inc.extension());
  switch(inc.type())
  {
    case DocInclude::Include:
      forceEndParagraph(inc);
      m_ci.startCodeFragment("DoxyCode");
      getCodeParser(inc.extension()).parseCode(m_ci,
                                        inc.context(),
                                        inc.text(),
                                        langExt,
                                        inc.isExample(),
                                        inc.exampleFile(),
                                        0, // fileDef
                                        -1, // startLine
                                        -1, // endLine
                                        TRUE, // inlineFragment
                                        0, // memberDef
                                        FALSE, // show line numbers
                                        m_ctx // search context
                                       );
      m_ci.endCodeFragment("DoxyCode");
      forceStartParagraph(inc);
      break;
    case DocInclude::IncWithLines:
      {
         forceEndParagraph(inc);
         m_ci.startCodeFragment("DoxyCode");
         FileInfo cfi(inc.file().str());
         FileDef *fd = createFileDef(cfi.dirPath(), cfi.fileName());
         getCodeParser(inc.extension()).parseCode(m_ci,
                                           inc.context(),
                                           inc.text(),
                                           langExt,
                                           inc.isExample(),
                                           inc.exampleFile(),
                                           fd, // fileDef,
                                           -1, // start line
                                           -1, // end line
                                           FALSE, // inline fragment
                                           0, // memberDef
                                           TRUE, // show line numbers
                                           m_ctx // search context
                                           );
         delete fd;
         m_ci.endCodeFragment("DoxyCode");
         forceStartParagraph(inc);
      }
      break;
    case DocInclude::DontInclude:
    case DocInclude::LatexInclude:
    case DocInclude::RtfInclude:
    case DocInclude::ManInclude:
    case DocInclude::XmlInclude:
    case DocInclude::DocbookInclude:
    case DocInclude::DontIncWithLines:
      break;
    case DocInclude::HtmlInclude:
      {
        if (inc.isBlock()) forceEndParagraph(inc);
        m_t << inc.text();
        if (inc.isBlock()) forceStartParagraph(inc);
      }
      break;
    case DocInclude::VerbInclude:
      forceEndParagraph(inc);
      m_t << "<pre class=\"fragment\">";
      filter(inc.text());
      m_t << "</pre>";
      forceStartParagraph(inc);
      break;
    case DocInclude::Snippet:
      {
         forceEndParagraph(inc);
         m_ci.startCodeFragment("DoxyCode");
         getCodeParser(inc.extension()).parseCode(m_ci,
                                           inc.context(),
                                           extractBlock(inc.text(),inc.blockId()),
                                           langExt,
                                           inc.isExample(),
                                           inc.exampleFile(),
                                           0,
                                           -1, // startLine
                                           -1, // endLine
                                           TRUE, // inlineFragment
                                           0, // memberDef
                                           FALSE, // show line number
                                           m_ctx // search context
                                          );
         m_ci.endCodeFragment("DoxyCode");
         forceStartParagraph(inc);
      }
      break;
    case DocInclude::SnipWithLines:
      {
         forceEndParagraph(inc);
         m_ci.startCodeFragment("DoxyCode");
         FileInfo cfi(inc.file().str());
         FileDef *fd = createFileDef(cfi.dirPath(), cfi.fileName());
         getCodeParser(inc.extension()).parseCode(m_ci,
                                           inc.context(),
                                           extractBlock(inc.text(),inc.blockId()),
                                           langExt,
                                           inc.isExample(),
                                           inc.exampleFile(),
                                           fd,
                                           lineBlock(inc.text(),inc.blockId()),
                                           -1, // endLine
                                           FALSE, // inlineFragment
                                           0, // memberDef
                                           TRUE, // show line number
                                           m_ctx // search context
                                          );
         delete fd;
         m_ci.endCodeFragment("DoxyCode");
         forceStartParagraph(inc);
      }
      break;
    case DocInclude::SnippetDoc:
    case DocInclude::IncludeDoc:
      err("Internal inconsistency: found switch SnippetDoc / IncludeDoc in file: %s"
          "Please create a bug report\n",__FILE__);
      break;
  }
}
References DocInclude::blockId(), DocInclude::context(), createFileDef(), FileInfo::dirPath(), DocInclude::DocbookInclude, DocInclude::DontInclude, DocInclude::DontIncWithLines, CodeOutputInterface::endCodeFragment(), err(), DocInclude::exampleFile(), DocInclude::extension(), extractBlock(), FALSE, DocInclude::file(), FileInfo::fileName(), filter(), forceEndParagraph(), forceStartParagraph(), DocVisitor::getCodeParser(), getLanguageFromFileName(), DocInclude::HtmlInclude, DocInclude::Include, DocInclude::IncludeDoc, DocInclude::IncWithLines, DocInclude::isBlock(), DocInclude::isExample(), DocInclude::LatexInclude, lineBlock(), m_ci, m_ctx, m_hide, m_t, DocInclude::ManInclude, CodeParserInterface::parseCode(), DocInclude::RtfInclude, DocInclude::Snippet, DocInclude::SnippetDoc, DocInclude::SnipWithLines, CodeOutputInterface::startCodeFragment(), QCString::str(), DocInclude::text(), TRUE, DocInclude::type(), DocInclude::VerbInclude, and DocInclude::XmlInclude.
operator()() [50/114]
void HtmlDocVisitor::operator() (const DocInclude &)
operator()() [51/114]
void HtmlDocVisitor::operator() (const DocIncOperator & op)
Definition at line 819 of file htmldocvisitor.cpp.
{
  //printf("DocIncOperator: type=%d first=%d, last=%d text='%s'\n",
  // op.type(),op.isFirst(),op.isLast(),qPrint(op.text()));
  if (op.isFirst())
  {
    forceEndParagraph(op);
    if (!m_hide) m_ci.startCodeFragment("DoxyCode");
    pushHidden(m_hide);
    m_hide=TRUE;
  }
  QCString locLangExt = getFileNameExtension(op.includeFileName());
  if (locLangExt.isEmpty()) locLangExt = m_langExt;
  SrcLangExt langExt = getLanguageFromFileName(locLangExt);
  if (op.type()!=DocIncOperator::Skip)
  {
    m_hide = popHidden();
    if (!m_hide)
    {
      FileDef *fd = 0;
      if (!op.includeFileName().isEmpty())
      {
        FileInfo cfi(op.includeFileName().str());
        fd = createFileDef(cfi.dirPath(), cfi.fileName());
      }
      getCodeParser(locLangExt).parseCode(
                                m_ci,
                                op.context(),
                                op.text(),
                                langExt,
                                op.isExample(),
                                op.exampleFile(),
                                fd, // fileDef
                                op.line(), // startLine
                                -1, // endLine
                                FALSE, // inline fragment
                                0, // memberDef
                                op.showLineNo(), // show line numbers
                                m_ctx // search context
                               );
      if (fd) delete fd;
    }
    pushHidden(m_hide);
    m_hide=TRUE;
  }
  if (op.isLast())
  {
    m_hide = popHidden();
    if (!m_hide) m_ci.endCodeFragment("DoxyCode");
    forceStartParagraph(op);
  }
  else
  {
    if (!m_hide) m_t << "\n";
  }
}
References DocIncOperator::context(), createFileDef(), FileInfo::dirPath(), CodeOutputInterface::endCodeFragment(), DocIncOperator::exampleFile(), FALSE, FileInfo::fileName(), forceEndParagraph(), forceStartParagraph(), DocVisitor::getCodeParser(), getFileNameExtension(), getLanguageFromFileName(), DocIncOperator::includeFileName(), QCString::isEmpty(), DocIncOperator::isExample(), DocIncOperator::isFirst(), DocIncOperator::isLast(), DocIncOperator::line(), m_ci, m_ctx, m_hide, m_langExt, m_t, CodeParserInterface::parseCode(), DocVisitor::popHidden(), DocVisitor::pushHidden(), DocIncOperator::showLineNo(), DocIncOperator::Skip, CodeOutputInterface::startCodeFragment(), QCString::str(), DocIncOperator::text(), TRUE, and DocIncOperator::type().
operator()() [52/114]
void HtmlDocVisitor::operator() (const DocIncOperator &)
operator()() [53/114]
void HtmlDocVisitor::operator() (const DocIndexEntry & e)
Definition at line 989 of file htmldocvisitor.cpp.
{
  QCString anchor = convertIndexWordToAnchor(e.entry());
  if (e.member())
  {
    anchor.prepend(e.member()->anchor()+"_");
  }
  m_t << "<a id=\"" << anchor << "\" name=\"" << anchor << "\"></a>";
  //printf("*** DocIndexEntry: word='%s' scope='%s' member='%s'\n",
  // qPrint(e.entry()),
  // e.scope() ? qPrint(e.scope()->name()) : "<null>",
  // e.member() ? qPrint(e.member()->name()) : "<null>"
  //);
  Doxygen::indexList->addIndexItem(e.scope(),e.member(),anchor,e.entry());
}
References IndexList::addIndexItem(), convertIndexWordToAnchor(), e, Doxygen::indexList, m_t, and QCString::prepend().
operator()() [54/114]
void HtmlDocVisitor::operator() (const DocIndexEntry &)
operator()() [55/114]
void HtmlDocVisitor::operator() (const DocInternal & i)
Definition at line 1607 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  visitChildren(i);
}
References m_hide, and visitChildren().
operator()() [56/114]
void HtmlDocVisitor::operator() (const DocInternal &)
operator()() [57/114]
void HtmlDocVisitor::operator() (const DocInternalRef & ref)
Definition at line 2009 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  startLink(QCString(),ref.file(),ref.relPath(),ref.anchor());
  visitChildren(ref);
  endLink();
  m_t << " ";
}
References DocInternalRef::anchor(), endLink(), DocInternalRef::file(), m_hide, m_t, DocInternalRef::relPath(), startLink(), and visitChildren().
operator()() [58/114]
void HtmlDocVisitor::operator() (const DocInternalRef &)
operator()() [59/114]
void HtmlDocVisitor::operator() (const DocLineBreak & br)
Definition at line 433 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<br "<< htmlAttribsToString(br.attribs()) << " />\n";
}
References DocLineBreak::attribs(), htmlAttribsToString(), m_hide, and m_t.
operator()() [60/114]
void HtmlDocVisitor::operator() (const DocLineBreak &)
operator()() [61/114]
void HtmlDocVisitor::operator() (const DocLink & lnk)
Definition at line 1835 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  startLink(lnk.ref(),lnk.file(),lnk.relPath(),lnk.anchor());
  visitChildren(lnk);
  endLink();
}
References DocLink::anchor(), endLink(), DocLink::file(), m_hide, DocLink::ref(), DocLink::relPath(), startLink(), and visitChildren().
operator()() [62/114]
void HtmlDocVisitor::operator() (const DocLink &)
operator()() [63/114]
void HtmlDocVisitor::operator() (const DocLinkedWord & w)
Definition at line 308 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  //printf("linked word: %s\n",qPrint(w.word()));
  startLink(w.ref(),w.file(),w.relPath(),w.anchor(),w.tooltip());
  filter(w.word());
  endLink();
}
References endLink(), filter(), m_hide, startLink(), and w.
operator()() [64/114]
void HtmlDocVisitor::operator() (const DocLinkedWord &)
operator()() [65/114]
void HtmlDocVisitor::operator() (const DocMscFile & df)
Definition at line 1799 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  if (!Config_getBool(DOT_CLEANUP)) copyFile(df.file(),Config_getString(HTML_OUTPUT)+"/"+stripPath(df.file()));
  m_t << "<div class=\"mscgraph\">\n";
  writeMscFile(df.file(),df.relPath(),df.context(),df.srcFile(),df.srcLine());
  if (df.hasCaption())
  {
    m_t << "<div class=\"caption\">\n";
  }
  visitChildren(df);
  if (df.hasCaption())
  {
    m_t << "</div>\n";
  }
  m_t << "</div>\n";
}
References Config_getBool, Config_getString, DocDiagramFileBase::context(), copyFile(), DocDiagramFileBase::file(), DocDiagramFileBase::hasCaption(), m_hide, m_t, DocDiagramFileBase::relPath(), DocDiagramFileBase::srcFile(), DocDiagramFileBase::srcLine(), stripPath(), visitChildren(), and writeMscFile().
operator()() [66/114]
void HtmlDocVisitor::operator() (const DocMscFile &)
operator()() [67/114]
void HtmlDocVisitor::operator() (const DocPara & p)
Definition at line 1290 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  //printf("> DocPara\n");
  //dumpDocNodeList(p.children());
  bool needsTag = determineIfNeedsTag(p);
  //printf(" needsTag=%d\n",needsTag);
  bool needsTagBefore = needsTag;
  bool needsTagAfter = needsTag;
  // if the first element of a paragraph is something that should be outside of
  // the paragraph (<ul>,<dl>,<table>,..) then that will already started the
  // paragraph and we don't need to do it here
  if (!p.children().empty())
  {
    auto it = std::find_if(std::begin(p.children()),std::end(p.children()),
                           [](const auto &node) { return !isInvisibleNode(node); });
    if (it!=std::end(p.children()))
    {
      const DocNodeVariant &n = *it;
      if (mustBeOutsideParagraph(n))
      {
        needsTagBefore = FALSE;
      }
    }
  }
  // check if this paragraph is the first or last or intermediate child of a <li> or <dd>.
  // this allows us to mark the tag with a special class so we can
  // fix the otherwise ugly spacing.
  int t;
  bool isFirst;
  bool isLast;
  t = getParagraphContext(p,isFirst,isLast);
  //printf("startPara first=%d last=%d\n",isFirst,isLast);
  if (isFirst && isLast) needsTagBefore=FALSE;
  //printf(" needsTagBefore=%d\n",needsTagBefore);
  // write the paragraph tag (if needed)
  if (needsTagBefore)
  {
    if (strlen(contexts[t]))
      m_t << "<p class=\"" << contexts[t] << "\"" << htmlAttribsToString(p.attribs()) << ">";
    else
      m_t << "<p" << htmlAttribsToString(p.attribs()) << ">";
  }
  visitChildren(p);
  // if the last element of a paragraph is something that should be outside of
  // the paragraph (<ul>,<dl>,<table>) then that will already have ended the
  // paragraph and we don't need to do it here
  if (!p.children().empty())
  {
    auto it = std::prev(std::end(p.children()));
    for (;;)
    {
      const DocNodeVariant &n = *it;
      if (!isInvisibleNode(n))
      {
        if (mustBeOutsideParagraph(n))
        {
          needsTagAfter = FALSE;
        }
        // stop searching if we found a node that is visible
        break;
      }
      if (it==std::begin(p.children()))
      {
        // stop searching if we are at the beginning of the list
        break;
      }
      else
      {
        --it;
      }
    }
  }
  //printf("endPara first=%d last=%d\n",isFirst,isLast);
  if (isFirst && isLast) needsTagAfter=FALSE;
  //printf(" needsTagAfter=%d\n",needsTagAfter);
  if (needsTagAfter) m_t << "</p>\n";
  //printf("< DocPara\n");
}
References ghc::filesystem::begin(), contexts, determineIfNeedsTag(), ghc::filesystem::end(), FALSE, getParagraphContext(), htmlAttribsToString(), isInvisibleNode(), m_hide, m_t, mustBeOutsideParagraph(), n, p, and visitChildren().
operator()() [68/114]
void HtmlDocVisitor::operator() (const DocPara &)
operator()() [69/114]
void HtmlDocVisitor::operator() (const DocParamList & pl)
Definition at line 1930 of file htmldocvisitor.cpp.
{
  //printf("DocParamList::visitPre\n");
  if (m_hide) return;
  m_t << " <tr>";
  const DocParamSect *sect = std::get_if<DocParamSect>(pl.parent());
  if (sect && sect->hasInOutSpecifier())
  {
    m_t << "<td class=\"paramdir\">";
    if (pl.direction()!=DocParamSect::Unspecified)
    {
      m_t << "[";
      if (pl.direction()==DocParamSect::In)
      {
        m_t << "in";
      }
      else if (pl.direction()==DocParamSect::Out)
      {
        m_t << "out";
      }
      else if (pl.direction()==DocParamSect::InOut)
      {
        m_t << "in,out";
      }
      m_t << "]";
    }
    m_t << "</td>";
  }
  if (sect && sect->hasTypeSpecifier())
  {
    m_t << "<td class=\"paramtype\">";
    for (const auto &type : pl.paramTypes())
    {
      std::visit(*this,type);
    }
    m_t << "</td>";
  }
  m_t << "<td class=\"paramname\">";
  bool first=TRUE;
  for (const auto &param : pl.parameters())
  {
    if (!first) m_t << ","; else first=FALSE;
    std::visit(*this,param);
  }
  m_t << "</td><td>";
  for (const auto &par : pl.paragraphs())
  {
    std::visit(*this,par);
  }
  m_t << "</td></tr>\n";
}
References DocParamList::direction(), FALSE, DocParamSect::hasInOutSpecifier(), DocParamSect::hasTypeSpecifier(), DocParamSect::In, DocParamSect::InOut, m_hide, m_t, DocParamSect::Out, DocParamList::paragraphs(), DocParamList::parameters(), DocParamList::paramTypes(), DocNode::parent(), TRUE, and DocParamSect::Unspecified.
operator()() [70/114]
void HtmlDocVisitor::operator() (const DocParamList &)
operator()() [71/114]
void HtmlDocVisitor::operator() (const DocParamSect & s)
Definition at line 1886 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  forceEndParagraph(s);
  QCString className;
  QCString heading;
  switch(s.type())
  {
    case DocParamSect::Param:
      heading=theTranslator->trParameters();
      className="params";
      break;
    case DocParamSect::RetVal:
      heading=theTranslator->trReturnValues();
      className="retval";
      break;
    case DocParamSect::Exception:
      heading=theTranslator->trExceptions();
      className="exception";
      break;
    case DocParamSect::TemplateParam:
      heading=theTranslator->trTemplateParameters();
      className="tparams";
      break;
    default:
      ASSERT(0);
  }
  m_t << "<dl class=\"" << className << "\"><dt>";
  m_t << heading;
  m_t << "</dt><dd>\n";
  m_t << " <table class=\"" << className << "\">\n";
  visitChildren(s);
  m_t << " </table>\n";
  m_t << " </dd>\n";
  m_t << "</dl>\n";
  forceStartParagraph(s);
}
References ASSERT, DocParamSect::Exception, forceEndParagraph(), forceStartParagraph(), m_hide, m_t, DocParamSect::Param, DocParamSect::RetVal, s, DocParamSect::TemplateParam, theTranslator, Translator::trExceptions(), Translator::trParameters(), Translator::trReturnValues(), Translator::trTemplateParameters(), and visitChildren().
operator()() [72/114]
void HtmlDocVisitor::operator() (const DocParamSect &)
operator()() [73/114]
void HtmlDocVisitor::operator() (const DocParBlock & pb)
Definition at line 2060 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  visitChildren(pb);
}
References m_hide, and visitChildren().
operator()() [74/114]
void HtmlDocVisitor::operator() (const DocParBlock &)
operator()() [75/114]
void HtmlDocVisitor::operator() (const DocRef & ref)
Definition at line 1843 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  if (!ref.file().isEmpty())
  {
    // when ref.isSubPage()==TRUE we use ref.file() for HTML and
    // ref.anchor() for LaTeX/RTF
    startLink(ref.ref(),ref.file(),ref.relPath(),ref.isSubPage() ? QCString() : ref.anchor());
  }
  if (!ref.hasLinkText()) filter(ref.targetTitle());
  visitChildren(ref);
  if (!ref.file().isEmpty()) endLink();
  //m_t << " ";
}
References DocRef::anchor(), endLink(), DocRef::file(), filter(), DocRef::hasLinkText(), QCString::isEmpty(), DocRef::isSubPage(), m_hide, DocRef::ref(), DocRef::relPath(), startLink(), DocRef::targetTitle(), and visitChildren().
operator()() [76/114]
void HtmlDocVisitor::operator() (const DocRef &)
operator()() [77/114]
void HtmlDocVisitor::operator() (const DocRoot & r)
Definition at line 1379 of file htmldocvisitor.cpp.
{
  //printf("> DocRoot\n");
  //dumpDocNodeList(r.children());
  visitChildren(r);
  //printf("< DocRoot\n");
}
References r, and visitChildren().
operator()() [78/114]
void HtmlDocVisitor::operator() (const DocRoot &)
operator()() [79/114]
void HtmlDocVisitor::operator() (const DocSecRefItem & ref)
Definition at line 1858 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  if (!ref.file().isEmpty())
  {
    m_t << "<li>";
    startLink(ref.ref(),ref.file(),ref.relPath(),ref.isSubPage() ? QCString() : ref.anchor());
  }
  visitChildren(ref);
  if (!ref.file().isEmpty())
  {
    endLink();
    m_t << "</li>\n";
  }
}
References DocSecRefItem::anchor(), endLink(), DocSecRefItem::file(), QCString::isEmpty(), DocSecRefItem::isSubPage(), m_hide, m_t, DocSecRefItem::ref(), DocSecRefItem::relPath(), startLink(), and visitChildren().
operator()() [80/114]
void HtmlDocVisitor::operator() (const DocSecRefItem &)
operator()() [81/114]
void HtmlDocVisitor::operator() (const DocSecRefList & s)
Definition at line 1874 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  forceEndParagraph(s);
  m_t << "<div>\n";
  m_t << "<ul class=\"multicol\">\n";
  visitChildren(s);
  m_t << "</ul>\n";
  m_t << "</div>\n";
  forceStartParagraph(s);
}
References forceEndParagraph(), forceStartParagraph(), m_hide, m_t, s, and visitChildren().
operator()() [82/114]
void HtmlDocVisitor::operator() (const DocSecRefList &)
operator()() [83/114]
void HtmlDocVisitor::operator() (const DocSection & s)
Definition at line 1469 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  forceEndParagraph(s);
  m_t << "<h" << s.level() << ">";
  m_t << "<a class=\"anchor\" id=\"" << s.anchor();
  m_t << "\"></a>\n";
  filter(convertCharEntitiesToUTF8(s.title()));
  m_t << "</h" << s.level() << ">\n";
  visitChildren(s);
  forceStartParagraph(s);
}
References convertCharEntitiesToUTF8(), filter(), forceEndParagraph(), forceStartParagraph(), m_hide, m_t, s, and visitChildren().
operator()() [84/114]
void HtmlDocVisitor::operator() (const DocSection &)
operator()() [85/114]
void HtmlDocVisitor::operator() (const DocSeparator & s)
Definition at line 1924 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "&#160;" << s.chars() << "&#160;";
}
References m_hide, m_t, and s.
operator()() [86/114]
void HtmlDocVisitor::operator() (const DocSeparator &)
operator()() [87/114]
void HtmlDocVisitor::operator() (const DocSimpleList & sl)
Definition at line 1445 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  forceEndParagraph(sl);
  m_t << "<ul>";
  if (!sl.isPreformatted()) m_t << "\n";
  visitChildren(sl);
  m_t << "</ul>";
  if (!sl.isPreformatted()) m_t << "\n";
  forceStartParagraph(sl);
}
References forceEndParagraph(), forceStartParagraph(), m_hide, m_t, caseconvert::sl, and visitChildren().
operator()() [88/114]
void HtmlDocVisitor::operator() (const DocSimpleList &)
operator()() [89/114]
void HtmlDocVisitor::operator() (const DocSimpleListItem & li)
Definition at line 1457 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "<li>";
  if (li.paragraph())
  {
    visit(*this,*li.paragraph());
  }
  m_t << "</li>";
  if (!li.isPreformatted()) m_t << "\n";
}
References DocNode::isPreformatted(), m_hide, m_t, and DocSimpleListItem::paragraph().
operator()() [90/114]
void HtmlDocVisitor::operator() (const DocSimpleListItem &)
operator()() [91/114]
void HtmlDocVisitor::operator() (const DocSimpleSect & s)
Definition at line 1387 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  forceEndParagraph(s);
  m_t << "<dl class=\"section " << s.typeString() << "\"><dt>";
  switch(s.type())
  {
    case DocSimpleSect::See:
      m_t << theTranslator->trSeeAlso(); break;
    case DocSimpleSect::Return:
      m_t << theTranslator->trReturns(); break;
    case DocSimpleSect::Author:
      m_t << theTranslator->trAuthor(TRUE,TRUE); break;
    case DocSimpleSect::Authors:
      m_t << theTranslator->trAuthor(TRUE,FALSE); break;
    case DocSimpleSect::Version:
      m_t << theTranslator->trVersion(); break;
    case DocSimpleSect::Since:
      m_t << theTranslator->trSince(); break;
    case DocSimpleSect::Date:
      m_t << theTranslator->trDate(); break;
    case DocSimpleSect::Note:
      m_t << theTranslator->trNote(); break;
    case DocSimpleSect::Warning:
      m_t << theTranslator->trWarning(); break;
    case DocSimpleSect::Pre:
      m_t << theTranslator->trPrecondition(); break;
    case DocSimpleSect::Post:
      m_t << theTranslator->trPostcondition(); break;
    case DocSimpleSect::Copyright:
      m_t << theTranslator->trCopyright(); break;
    case DocSimpleSect::Invar:
      m_t << theTranslator->trInvariant(); break;
    case DocSimpleSect::Remark:
      m_t << theTranslator->trRemarks(); break;
    case DocSimpleSect::Attention:
      m_t << theTranslator->trAttention(); break;
    case DocSimpleSect::User: break;
    case DocSimpleSect::Rcs: break;
    case DocSimpleSect::Unknown: break;
  }
  if (s.title())
  {
    std::visit(*this,*s.title());
  }
  m_t << "</dt><dd>";
  visitChildren(s);
  m_t << "</dd></dl>\n";
  forceStartParagraph(s);
}
References DocSimpleSect::Attention, DocSimpleSect::Author, DocSimpleSect::Authors, DocSimpleSect::Copyright, DocSimpleSect::Date, FALSE, forceEndParagraph(), forceStartParagraph(), DocSimpleSect::Invar, m_hide, m_t, DocSimpleSect::Note, DocSimpleSect::Post, DocSimpleSect::Pre, DocSimpleSect::Rcs, DocSimpleSect::Remark, DocSimpleSect::Return, s, DocSimpleSect::See, DocSimpleSect::Since, theTranslator, Translator::trAttention(), Translator::trAuthor(), Translator::trCopyright(), Translator::trDate(), Translator::trInvariant(), Translator::trNote(), Translator::trPostcondition(), Translator::trPrecondition(), Translator::trRemarks(), Translator::trReturns(), Translator::trSeeAlso(), Translator::trSince(), TRUE, Translator::trVersion(), Translator::trWarning(), DocSimpleSect::Unknown, DocSimpleSect::User, DocSimpleSect::Version, visitChildren(), and DocSimpleSect::Warning.
operator()() [92/114]
void HtmlDocVisitor::operator() (const DocSimpleSect &)
operator()() [93/114]
void HtmlDocVisitor::operator() (const DocSimpleSectSep &)
Definition at line 1005 of file htmldocvisitor.cpp.
{
  m_t << "</dd>\n";
  m_t << "<dd>\n";
}
References m_t.
operator()() [94/114]
void HtmlDocVisitor::operator() (const DocSimpleSectSep &)
operator()() [95/114]
void HtmlDocVisitor::operator() (const DocStyleChange & s)
Definition at line 447 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  switch (s.style())
  {
    case DocStyleChange::Bold:
      if (s.enable()) m_t << "<b" << htmlAttribsToString(s.attribs()) << ">"; else m_t << "</b>";
      break;
    case DocStyleChange::S:
      if (s.enable()) m_t << "<s" << htmlAttribsToString(s.attribs()) << ">"; else m_t << "</s>";
      break;
    case DocStyleChange::Strike:
      if (s.enable()) m_t << "<strike" << htmlAttribsToString(s.attribs()) << ">"; else m_t << "</strike>";
      break;
    case DocStyleChange::Del:
      if (s.enable()) m_t << "<del" << htmlAttribsToString(s.attribs()) << ">"; else m_t << "</del>";
      break;
    case DocStyleChange::Underline:
      if (s.enable()) m_t << "<u" << htmlAttribsToString(s.attribs()) << ">"; else m_t << "</u>";
      break;
    case DocStyleChange::Ins:
      if (s.enable()) m_t << "<ins" << htmlAttribsToString(s.attribs()) << ">"; else m_t << "</ins>";
      break;
    case DocStyleChange::Italic:
      if (s.enable()) m_t << "<em" << htmlAttribsToString(s.attribs()) << ">"; else m_t << "</em>";
      break;
    case DocStyleChange::Code:
      if (s.enable()) m_t << "<code" << htmlAttribsToString(s.attribs()) << ">"; else m_t << "</code>";
      break;
    case DocStyleChange::Subscript:
      if (s.enable()) m_t << "<sub" << htmlAttribsToString(s.attribs()) << ">"; else m_t << "</sub>";
      break;
    case DocStyleChange::Superscript:
      if (s.enable()) m_t << "<sup" << htmlAttribsToString(s.attribs()) << ">"; else m_t << "</sup>";
      break;
    case DocStyleChange::Center:
      if (s.enable())
      {
        forceEndParagraph(s);
        m_t << "<center" << htmlAttribsToString(s.attribs()) << ">";
      }
      else
      {
        m_t << "</center>";
        forceStartParagraph(s);
      }
      break;
    case DocStyleChange::Small:
      if (s.enable()) m_t << "<small" << htmlAttribsToString(s.attribs()) << ">"; else m_t << "</small>";
      break;
    case DocStyleChange::Cite:
      if (s.enable()) m_t << "<cite" << htmlAttribsToString(s.attribs()) << ">"; else m_t << "</cite>";
      break;
    case DocStyleChange::Preformatted:
      if (s.enable())
      {
        forceEndParagraph(s);
        m_t << "<pre" << htmlAttribsToString(s.attribs()) << ">";
        m_insidePre=TRUE;
      }
      else
      {
        m_insidePre=FALSE;
        m_t << "</pre>";
        forceStartParagraph(s);
      }
      break;
    case DocStyleChange::Div:
      if (s.enable())
      {
        forceEndParagraph(s);
        m_t << "<div" << htmlAttribsToString(s.attribs()) << ">";
      }
      else
      {
        m_t << "</div>";
        forceStartParagraph(s);
      }
      break;
    case DocStyleChange::Span:
      if (s.enable()) m_t << "<span" << htmlAttribsToString(s.attribs()) << ">"; else m_t << "</span>";
      break;
  }
}
References DocStyleChange::Bold, DocStyleChange::Center, DocStyleChange::Cite, DocStyleChange::Code, DocStyleChange::Del, DocStyleChange::Div, FALSE, forceEndParagraph(), forceStartParagraph(), htmlAttribsToString(), DocStyleChange::Ins, DocStyleChange::Italic, m_hide, m_insidePre, m_t, DocStyleChange::Preformatted, s, DocStyleChange::S, DocStyleChange::Small, DocStyleChange::Span, DocStyleChange::Strike, DocStyleChange::Subscript, DocStyleChange::Superscript, TRUE, and DocStyleChange::Underline.
operator()() [96/114]
void HtmlDocVisitor::operator() (const DocStyleChange &)
operator()() [97/114]
void HtmlDocVisitor::operator() (const DocSymbol & s)
Definition at line 330 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  if (m_insideTitle &&
      (s.symbol()==HtmlEntityMapper::Sym_Quot || s.symbol()==HtmlEntityMapper::Sym_quot)) // escape "'s inside title="..."
  {
    m_t << "&quot;";
  }
  else
  {
    const char *res = HtmlEntityMapper::instance()->html(s.symbol());
    if (res)
    {
      m_t << res;
    }
    else
    {
      err("HTML: non supported HTML-entity found: %s\n",
          HtmlEntityMapper::instance()->html(s.symbol(),TRUE));
    }
  }
}
References err(), HtmlEntityMapper::html(), HtmlEntityMapper::instance(), m_hide, m_insideTitle, m_t, s, HtmlEntityMapper::Sym_quot, HtmlEntityMapper::Sym_Quot, and TRUE.
operator()() [98/114]
void HtmlDocVisitor::operator() (const DocSymbol &)
operator()() [99/114]
void HtmlDocVisitor::operator() (const DocText & t)
Definition at line 2018 of file htmldocvisitor.cpp.
{
  visitChildren(t);
}
References visitChildren().
operator()() [100/114]
void HtmlDocVisitor::operator() (const DocText &)
operator()() [101/114]
void HtmlDocVisitor::operator() (const DocTitle & t)
Definition at line 1439 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  visitChildren(t);
}
References m_hide, and visitChildren().
operator()() [102/114]
void HtmlDocVisitor::operator() (const DocTitle &)
operator()() [103/114]
void HtmlDocVisitor::operator() (const DocURL & u)
Definition at line 395 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  if (u.isEmail()) // mail address
  {
    QCString url = u.url();
    // obfuscate the mail address link
    writeObfuscatedMailAddress(url);
    if (!Config_getBool(OBFUSCATE_EMAILS))
    {
      m_t << url;
    }
    else
    {
      const char *p = url.data();
      // also obfuscate the address as shown on the web page
      uint size=5;
      while (*p)
      {
        for (uint j=0;j<size && *p;j++)
        {
          p = writeUTF8Char(m_t,p);
        }
        if (*p) m_t << "<span class=\"obfuscator\">.nosp@m.</span>";
        if (size==5) size=4; else size=5;
      }
    }
    m_t << "</a>";
  }
  else // web address
  {
    m_t << "<a href=\"";
    m_t << u.url() << "\">";
    filter(u.url());
    m_t << "</a>";
  }
}
References Config_getBool, filter(), DocURL::isEmail(), m_hide, m_t, p, size, setup::url, DocURL::url(), writeObfuscatedMailAddress(), and writeUTF8Char().
operator()() [104/114]
void HtmlDocVisitor::operator() (const DocURL &)
operator()() [105/114]
void HtmlDocVisitor::operator() (const DocVerbatim & s)
0
Definition at line 534 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  QCString lang = m_langExt;
  if (!s.language().isEmpty()) // explicit language setting
  {
    lang = s.language();
  }
  SrcLangExt langExt = getLanguageFromCodeLang(lang);
  switch(s.type())
  {
    case DocVerbatim::Code:
      forceEndParagraph(s);
      m_ci.startCodeFragment("DoxyCode");
      getCodeParser(lang).parseCode(m_ci,
                                        s.context(),
                                        s.text(),
                                        langExt,
                                        s.isExample(),
                                        s.exampleFile(),
                                        0, // fileDef
                                        -1, // startLine
                                        -1, // endLine
                                        FALSE, // inlineFragment
                                        0, // memberDef
                                        TRUE, // show line numbers
                                        m_ctx // search context
                                       );
      m_ci.endCodeFragment("DoxyCode");
      forceStartParagraph(s);
      break;
    case DocVerbatim::Verbatim:
      forceEndParagraph(s);
      m_t << "<pre class=\"fragment\">";
      filter(s.text());
      m_t << "</pre>";
      forceStartParagraph(s);
      break;
    case DocVerbatim::JavaDocLiteral:
      filter(s.text(), true);
      break;
    case DocVerbatim::JavaDocCode:
      m_t << "<code class=\"JavaDocCode\">";
      filter(s.text(), true);
      m_t << "</code>";
      break;
    case DocVerbatim::HtmlOnly:
      {
        if (s.isBlock()) forceEndParagraph(s);
        m_t << s.text();
        if (s.isBlock()) forceStartParagraph(s);
      }
      break;
    case DocVerbatim::ManOnly:
    case DocVerbatim::LatexOnly:
    case DocVerbatim::XmlOnly:
    case DocVerbatim::RtfOnly:
    case DocVerbatim::DocbookOnly:
      /* nothing */
      break;
    case DocVerbatim::Dot:
      {
        static int dotindex = 1;
        QCString fileName(4096);
        forceEndParagraph(s);
        fileName.sprintf("%s%d%s",
            qPrint(Config_getString(HTML_OUTPUT)+"/inline_dotgraph_"),
            dotindex++,
            ".dot"
           );
        std::ofstream file(fileName.str(),std::ofstream::out | std::ofstream::binary);
        if (!file.is_open())
        {
          err("Could not open file %s for writing\n",qPrint(fileName));
        }
        else
        {
          QCString stext = s.text();
          file.write(stext.data(), stext.length());
          file.close();
          m_t << "<div class=\"dotgraph\">\n";
          writeDotFile(fileName,s.relPath(),s.context(),s.srcFile(),s.srcLine());
          visitCaption(m_t, s);
          m_t << "</div>\n";
          if (Config_getBool(DOT_CLEANUP)) Dir().remove(fileName.str());
        }
        forceStartParagraph(s);
      }
      break;
    case DocVerbatim::Msc:
      {
        forceEndParagraph(s);
        static int mscindex = 1;
        QCString baseName(4096);
        baseName.sprintf("%s%d",
            qPrint(Config_getString(HTML_OUTPUT)+"/inline_mscgraph_"),
            mscindex++
            );
        std::ofstream file(baseName.str()+".msc",std::ofstream::out | std::ofstream::binary);
        if (!file.is_open())
        {
          err("Could not open file %s.msc for writing\n",qPrint(baseName));
        }
        else
        {
          QCString text = "msc {";
          text+=s.text();
          text+="}";
          file.write(text.data(), text.length());
          file.close();
          m_t << "<div class=\"mscgraph\">\n";
          writeMscFile(baseName+".msc",s.relPath(),s.context(),s.srcFile(),s.srcLine());
          visitCaption(m_t, s);
          m_t << "</div>\n";
          if (Config_getBool(DOT_CLEANUP)) Dir().remove(baseName.str()+".msc");
        }
        forceStartParagraph(s);
      }
      break;
    case DocVerbatim::PlantUML:
      {
        forceEndParagraph(s);
        QCString htmlOutput = Config_getString(HTML_OUTPUT);
        QCString imgExt = getDotImageExtension();
        PlantumlManager::OutputFormat format = PlantumlManager::PUML_BITMAP; // default : PUML_BITMAP
        if (imgExt=="svg")
        {
          format = PlantumlManager::PUML_SVG;
        }
        QCString baseName = PlantumlManager::instance().writePlantUMLSource(
                                    htmlOutput,s.exampleFile(),
                                    s.text(),format,s.engine(),s.srcFile(),s.srcLine());
        m_t << "<div class=\"plantumlgraph\">\n";
        writePlantUMLFile(baseName,s.relPath(),s.context(),s.srcFile(),s.srcLine());
        visitCaption(m_t, s);
        m_t << "</div>\n";
        forceStartParagraph(s);
      }
      break;
  }
}
References DocVerbatim::Code, Config_getBool, Config_getString, QCString::data(), DocVerbatim::DocbookOnly, DocVerbatim::Dot, CodeOutputInterface::endCodeFragment(), err(), FALSE, caseconvert::file, filter(), forceEndParagraph(), forceStartParagraph(), DocVisitor::getCodeParser(), getDotImageExtension(), getLanguageFromCodeLang(), DocVerbatim::HtmlOnly, PlantumlManager::instance(), DocVerbatim::JavaDocCode, DocVerbatim::JavaDocLiteral, DocVerbatim::LatexOnly, QCString::length(), m_ci, m_ctx, m_hide, m_langExt, m_t, DocVerbatim::ManOnly, DocVerbatim::Msc, out, CodeParserInterface::parseCode(), DocVerbatim::PlantUML, PlantumlManager::PUML_BITMAP, PlantumlManager::PUML_SVG, qPrint(), Dir::remove(), DocVerbatim::RtfOnly, s, QCString::sprintf(), CodeOutputInterface::startCodeFragment(), QCString::str(), TRUE, DocVerbatim::Verbatim, visitCaption(), writeDotFile(), writeMscFile(), writePlantUMLFile(), PlantumlManager::writePlantUMLSource(), and DocVerbatim::XmlOnly.
operator()() [106/114]
void HtmlDocVisitor::operator() (const DocVerbatim &)
operator()() [107/114]
void HtmlDocVisitor::operator() (const DocVhdlFlow & vf)
Definition at line 2033 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  if (VhdlDocGen::getFlowMember()) // use VHDL flow chart creator
  {
    forceEndParagraph(vf);
    QCString fname=FlowChart::convertNameToFileName();
    m_t << "<p>";
    m_t << theTranslator->trFlowchart();
    m_t << "<a href=\"";
    m_t << fname;
    m_t << ".svg\">";
    m_t << VhdlDocGen::getFlowMember()->name();
    m_t << "</a>";
    if (vf.hasCaption())
    {
      m_t << "<br />";
    }
  }
  visitChildren(vf);
  if (VhdlDocGen::getFlowMember()) // use VHDL flow chart creator
  {
    m_t << "</p>";
    forceStartParagraph(vf);
  }
}
References FlowChart::convertNameToFileName(), forceEndParagraph(), forceStartParagraph(), VhdlDocGen::getFlowMember(), DocVhdlFlow::hasCaption(), m_hide, m_t, Definition::name(), theTranslator, Translator::trFlowchart(), and visitChildren().
operator()() [108/114]
void HtmlDocVisitor::operator() (const DocVhdlFlow &)
operator()() [109/114]
void HtmlDocVisitor::operator() (const DocWhiteSpace & w)
Definition at line 317 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  if (m_insidePre)
  {
    m_t << w.chars();
  }
  else
  {
    m_t << " ";
  }
}
References m_hide, m_insidePre, m_t, and w.
operator()() [110/114]
void HtmlDocVisitor::operator() (const DocWhiteSpace &)
operator()() [111/114]
void HtmlDocVisitor::operator() (const DocWord & w)
Definition at line 302 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  filter(w.word());
}
References filter(), m_hide, and w.
operator()() [112/114]
void HtmlDocVisitor::operator() (const DocWord &)
operator()() [113/114]
void HtmlDocVisitor::operator() (const DocXRefItem & x)
Definition at line 1982 of file htmldocvisitor.cpp.
{
  if (m_hide) return;
  if (x.title().isEmpty()) return;
  forceEndParagraph(x);
  bool anonymousEnum = x.file()=="@";
  if (!anonymousEnum)
  {
    m_t << "<dl class=\"" << x.key() << "\"><dt><b><a class=\"el\" href=\""
        << x.relPath() << addHtmlExtensionIfMissing(x.file())
        << "#" << x.anchor() << "\">";
  }
  else
  {
    m_t << "<dl class=\"" << x.key() << "\"><dt><b>";
  }
  filter(x.title());
  m_t << ":";
  if (!anonymousEnum) m_t << "</a>";
  m_t << "</b></dt><dd>";
  visitChildren(x);
  if (x.title().isEmpty()) return;
  m_t << "</dd></dl>\n";
  forceStartParagraph(x);
}
References addHtmlExtensionIfMissing(), filter(), forceEndParagraph(), forceStartParagraph(), m_hide, m_t, visitChildren(), and x.
operator()() [114/114]
void HtmlDocVisitor::operator() (const DocXRefItem &)
startLink() [1/2]
void HtmlDocVisitor::startLink (const QCString & ref, const QCString & file, const QCString & relPath, const QCString & anchor, const QCString & tooltip = ``) [private]
Definition at line 2152 of file htmldocvisitor.cpp.
{
  //printf("HtmlDocVisitor: file=%s anchor=%s\n",qPrint(file),qPrint(anchor));
  if (!ref.isEmpty()) // link to entity imported via tag file
  {
    m_t << "<a class=\"elRef\" ";
    m_t << externalLinkTarget();
  }
  else // local link
  {
    m_t << "<a class=\"el\" ";
  }
  m_t << "href=\"";
  m_t << externalRef(relPath,ref,TRUE);
  if (!file.isEmpty())
  {
    m_t << addHtmlExtensionIfMissing(file);
  }
  if (!anchor.isEmpty()) m_t << "#" << anchor;
  m_t << "\"";
  if (!tooltip.isEmpty()) m_t << " title=\"" << convertToHtml(tooltip) << "\"";
  m_t << ">";
}
References addHtmlExtensionIfMissing(), convertToHtml(), externalLinkTarget(), externalRef(), caseconvert::file, QCString::isEmpty(), m_t, and TRUE.
Referenced by operator()().
startLink() [2/2]
void HtmlDocVisitor::startLink (const QCString & ref, const QCString & file, const QCString & relPath, const QCString & anchor, const QCString & tooltip = ``) [private]
visitCaption() [1/2]
template<class T >
void HtmlDocVisitor::visitCaption (TextStream & t, const T & n) [private]
Definition at line 285 of file htmldocvisitor.cpp.
{
  if (n.hasCaption())
  {
    t << "<div class=\"caption\">\n";
    for (const auto &child : n.children())
    {
      std::visit(*this, child);
    }
    t << "</div>\n";
  }
}
References n.
Referenced by operator()().
visitCaption() [2/2]
template<class T >
void HtmlDocVisitor::visitCaption (TextStream & t, const T & n) [private]
visitChildren() [1/2]
template<class T >
void HtmlDocVisitor::visitChildren (const T & t) [inline], [private]
Definition at line 104 of file htmldocvisitor.h.
    {
      for (const auto &child : t.children())
      {
        std::visit(*this, child);
      }
    }
Referenced by operator()().
visitChildren() [2/2]
template<class T >
void HtmlDocVisitor::visitChildren (const T & t) [inline], [private]
Definition at line 104 of file htmldocvisitor.h.
    {
      for (const auto &child : t.children())
      {
        std::visit(*this, child);
      }
    }
writeDiaFile() [1/2]
void HtmlDocVisitor::writeDiaFile (const QCString & fileName, const QCString & relPath, const QCString & context, const QCString & srcFile, int srcLine) [private]
Definition at line 2225 of file htmldocvisitor.cpp.
{
  QCString baseName=fileName;
  int i;
  if ((i=baseName.findRev('/'))!=-1) // strip path
  {
    baseName=baseName.right(baseName.length()-i-1);
  }
  if ((i=baseName.find('.'))!=-1) // strip extension
  {
    baseName=baseName.left(i);
  }
  baseName.prepend("dia_");
  QCString outDir = Config_getString(HTML_OUTPUT);
  writeDiaGraphFromFile(fileName,outDir,baseName,DIA_BITMAP,srcFile,srcLine);
  m_t << "<img src=\"" << relPath << baseName << ".png" << "\" />\n";
}
References Config_getString, DIA_BITMAP, QCString::find(), QCString::findRev(), QCString::left(), QCString::length(), m_t, QCString::prepend(), QCString::right(), and writeDiaGraphFromFile().
Referenced by operator()().
writeDiaFile() [2/2]
void HtmlDocVisitor::writeDiaFile (const QCString & fileName, const QCString & relPath, const QCString & context, const QCString & srcFile, int srcLine) [private]
writeDotFile() [1/2]
void HtmlDocVisitor::writeDotFile (const QCString & fileName, const QCString & relPath, const QCString & context, const QCString & srcFile, int srcLine) [private]
Definition at line 2183 of file htmldocvisitor.cpp.
{
  QCString baseName=fn;
  int i;
  if ((i=baseName.findRev('/'))!=-1)
  {
    baseName=baseName.right(baseName.length()-i-1);
  }
  if ((i=baseName.find('.'))!=-1) // strip extension
  {
    baseName=baseName.left(i);
  }
  baseName.prepend("dot_");
  QCString outDir = Config_getString(HTML_OUTPUT);
  writeDotGraphFromFile(fn,outDir,baseName,GOF_BITMAP,srcFile,srcLine);
  writeDotImageMapFromFile(m_t,fn,outDir,relPath,baseName,context,-1,srcFile,srcLine);
}
References Config_getString, QCString::find(), QCString::findRev(), GOF_BITMAP, QCString::left(), QCString::length(), m_t, QCString::prepend(), QCString::right(), writeDotGraphFromFile(), and writeDotImageMapFromFile().
Referenced by operator()().
writeDotFile() [2/2]
void HtmlDocVisitor::writeDotFile (const QCString & fileName, const QCString & relPath, const QCString & context, const QCString & srcFile, int srcLine) [private]
writeMscFile() [1/2]
void HtmlDocVisitor::writeMscFile (const QCString & fileName, const QCString & relPath, const QCString & context, const QCString & srcFile, int srcLine) [private]
Definition at line 2202 of file htmldocvisitor.cpp.
{
  QCString baseName=fileName;
  int i;
  if ((i=baseName.findRev('/'))!=-1) // strip path
  {
    baseName=baseName.right(baseName.length()-i-1);
  }
  if ((i=baseName.find('.'))!=-1) // strip extension
  {
    baseName=baseName.left(i);
  }
  baseName.prepend("msc_");
  QCString outDir = Config_getString(HTML_OUTPUT);
  QCString imgExt = getDotImageExtension();
  MscOutputFormat mscFormat = MSC_BITMAP;
  if ("svg" == imgExt)
    mscFormat = MSC_SVG;
  writeMscGraphFromFile(fileName,outDir,baseName,mscFormat,srcFile,srcLine);
  writeMscImageMapFromFile(m_t,fileName,outDir,relPath,baseName,context,mscFormat,srcFile,srcLine);
}
References Config_getString, QCString::find(), QCString::findRev(), getDotImageExtension(), QCString::left(), QCString::length(), m_t, MSC_BITMAP, MSC_SVG, QCString::prepend(), QCString::right(), writeMscGraphFromFile(), and writeMscImageMapFromFile().
Referenced by operator()().
writeMscFile() [2/2]
void HtmlDocVisitor::writeMscFile (const QCString & fileName, const QCString & relPath, const QCString & context, const QCString & srcFile, int srcLine) [private]
writeObfuscatedMailAddress() [1/2]
void HtmlDocVisitor::writeObfuscatedMailAddress (const QCString & url) [private]
Definition at line 367 of file htmldocvisitor.cpp.
{
  if (!Config_getBool(OBFUSCATE_EMAILS))
  {
    m_t << "<a href=\"mailto:" << url << "\">";
  }
  else
  {
    m_t << "<a href=\"#\" onclick=\"location.href='mai'+'lto:'";
    if (!url.isEmpty())
    {
      const char *p = url.data();
      uint size=3;
      while (*p)
      {
        m_t << "+'";
        for (uint j=0;j<size && *p;j++)
        {
          p = writeUTF8Char(m_t,p);
        }
        m_t << "'";
        if (size==3) size=2; else size=3;
      }
    }
    m_t << "; return false;\">";
  }
}
References Config_getBool, m_t, p, size, setup::url, and writeUTF8Char().
Referenced by operator()().
writeObfuscatedMailAddress() [2/2]
void HtmlDocVisitor::writeObfuscatedMailAddress (const QCString & url) [private]
writePlantUMLFile() [1/2]
void HtmlDocVisitor::writePlantUMLFile (const QCString & fileName, const QCString & relPath, const QCString & context, const QCString & srcFile, int srcLine) [private]
Definition at line 2245 of file htmldocvisitor.cpp.
{
  QCString baseName=fileName;
  int i;
  if ((i=baseName.findRev('/'))!=-1) // strip path
  {
    baseName=baseName.right(baseName.length()-i-1);
  }
  if ((i=baseName.findRev('.'))!=-1) // strip extension
  {
    baseName=baseName.left(i);
  }
  QCString outDir = Config_getString(HTML_OUTPUT);
  QCString imgExt = getDotImageExtension();
  if (imgExt=="svg")
  {
    PlantumlManager::instance().generatePlantUMLOutput(fileName,outDir,PlantumlManager::PUML_SVG);
    //m_t << "<iframe scrolling=\"no\" frameborder=\"0\" src=\"" << relPath << baseName << ".svg" << "\" />\n";
    //m_t << "<p><b>This browser is not able to show SVG: try Firefox, Chrome, Safari, or Opera instead.</b></p>";
    //m_t << "</iframe>\n";
    m_t << "<object type=\"image/svg+xml\" data=\"" << relPath << baseName << ".svg\"></object>\n";
  }
  else
  {
    PlantumlManager::instance().generatePlantUMLOutput(fileName,outDir,PlantumlManager::PUML_BITMAP);
    m_t << "<img src=\"" << relPath << baseName << ".png" << "\" />\n";
  }
}
References Config_getString, QCString::findRev(), PlantumlManager::generatePlantUMLOutput(), getDotImageExtension(), PlantumlManager::instance(), QCString::left(), QCString::length(), m_t, PlantumlManager::PUML_BITMAP, PlantumlManager::PUML_SVG, and QCString::right().
Referenced by operator()().
writePlantUMLFile() [2/2]
void HtmlDocVisitor::writePlantUMLFile (const QCString & fileName, const QCString & relPath, const QCString & context, const QCString & srcFile, int srcLine) [private]
Member Data Documentation
m_ci
CodeOutputInterface & HtmlDocVisitor::m_ci [private]
Definition at line 144 of file htmldocvisitor.h.
Referenced by operator()().
m_ctx
const Definition * HtmlDocVisitor::m_ctx [private]
Definition at line 148 of file htmldocvisitor.h.
Referenced by operator()().
m_hide
bool HtmlDocVisitor::m_hide = false [private]
Definition at line 146 of file htmldocvisitor.h.
Referenced by operator()().
m_insidePre
bool HtmlDocVisitor::m_insidePre = false [private]
Definition at line 145 of file htmldocvisitor.h.
Referenced by operator()().
m_insideTitle
bool HtmlDocVisitor::m_insideTitle = false [private]
Definition at line 147 of file htmldocvisitor.h.
Referenced by operator()().
m_langExt
QCString HtmlDocVisitor::m_langExt [private]
Definition at line 149 of file htmldocvisitor.h.
Referenced by HtmlDocVisitor(), and operator()().
m_t
TextStream & HtmlDocVisitor::m_t [private]
Definition at line 143 of file htmldocvisitor.h.
Referenced by endLink(), filter(), forceEndParagraph(), forceStartParagraph(), operator()(), startLink(), writeDiaFile(), writeDotFile(), writeMscFile(), writeObfuscatedMailAddress(), and writePlantUMLFile().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/htmldocvisitor.h
doxygen/src/htmldocvisitor.h
doxygen/build/doxygen/src/htmldocvisitor.cpp
doxygen/src/htmldocvisitor.cpp