Debug Class Reference
#include <debug.h>
Public Types
enum DebugMask {
Quiet = 0x00000000
, FindMembers = 0x00000001
, Functions = 0x00000002
, Variables = 0x00000004
,
Preprocessor = 0x00000008
, Classes = 0x00000010
, CommentCnv = 0x00000020
, CommentScan = 0x00000040
,
PrintTree = 0x00000100
, Time = 0x00000200
, ExtCmd = 0x00000400
, Markdown = 0x00000800
,
FilterOutput = 0x00001000
, Lex = 0x00002000
, Plantuml = 0x00004000
, FortranFixed2Free = 0x00008000
,
Cite = 0x00010000
, NoLineNo = 0x00020000
, Rtf = 0x00040000
, Qhp = 0x00080000
,
Tag = 0x00100000
, Quiet = 0x00000000
, FindMembers = 0x00000001
, Functions = 0x00000002
,
Variables = 0x00000004
, Preprocessor = 0x00000008
, Classes = 0x00000010
, CommentCnv = 0x00000020
,
CommentScan = 0x00000040
, PrintTree = 0x00000100
, Time = 0x00000200
, ExtCmd = 0x00000400
,
Markdown = 0x00000800
, FilterOutput = 0x00001000
, Lex = 0x00002000
, Plantuml = 0x00004000
,
FortranFixed2Free = 0x00008000
, Cite = 0x00010000
, NoLineNo = 0x00020000
, Rtf = 0x00040000
,
Qhp = 0x00080000
, Tag = 0x00100000
 }
enum DebugMask {
Quiet = 0x00000000
, FindMembers = 0x00000001
, Functions = 0x00000002
, Variables = 0x00000004
,
Preprocessor = 0x00000008
, Classes = 0x00000010
, CommentCnv = 0x00000020
, CommentScan = 0x00000040
,
PrintTree = 0x00000100
, Time = 0x00000200
, ExtCmd = 0x00000400
, Markdown = 0x00000800
,
FilterOutput = 0x00001000
, Lex = 0x00002000
, Plantuml = 0x00004000
, FortranFixed2Free = 0x00008000
,
Cite = 0x00010000
, NoLineNo = 0x00020000
, Rtf = 0x00040000
, Qhp = 0x00080000
,
Tag = 0x00100000
, Quiet = 0x00000000
, FindMembers = 0x00000001
, Functions = 0x00000002
,
Variables = 0x00000004
, Preprocessor = 0x00000008
, Classes = 0x00000010
, CommentCnv = 0x00000020
,
CommentScan = 0x00000040
, PrintTree = 0x00000100
, Time = 0x00000200
, ExtCmd = 0x00000400
,
Markdown = 0x00000800
, FilterOutput = 0x00001000
, Lex = 0x00002000
, Plantuml = 0x00004000
,
FortranFixed2Free = 0x00008000
, Cite = 0x00010000
, NoLineNo = 0x00020000
, Rtf = 0x00040000
,
Qhp = 0x00080000
, Tag = 0x00100000
 }
Static Public Member Functions
static void print (DebugMask mask, int prio, const char *fmt,...)
static int setFlag (const QCString &label)
static void clearFlag (const QCString &label)
static bool isFlagSet (DebugMask mask)
static void printFlags ()
static void setPriority (int p)
static void startTimer ()
static double elapsedTime ()
static void print (DebugMask mask, int prio, const char *fmt,...)
static int setFlag (const QCString &label)
static void clearFlag (const QCString &label)
static bool isFlagSet (DebugMask mask)
static void printFlags ()
static void setPriority (int p)
static void startTimer ()
static double elapsedTime ()
Static Private Attributes
static DebugMask curMask = Debug::Quiet
static int curPrio = 0
Detailed Description
Class containing a print function for diagnostics.
Definition at line 22 of file debug.h.
Member Enumeration Documentation
DebugMask [1/2]
enum Debug::DebugMask
Enumerator
Quiet
FindMembers
Functions
Variables
Preprocessor
Classes
CommentCnv
CommentScan
PrintTree
Time
ExtCmd
Markdown
FilterOutput
Lex
Plantuml
FortranFixed2Free
Cite
NoLineNo
Rtf
Qhp
Tag
Quiet
FindMembers
Functions
Variables
Preprocessor
Classes
CommentCnv
CommentScan
PrintTree
Time
ExtCmd
Markdown
FilterOutput
Lex
Plantuml
FortranFixed2Free
Cite
NoLineNo
Rtf
Qhp
Tag
Definition at line 25 of file debug.h.
                   { Quiet = 0x00000000,
                     FindMembers = 0x00000001,
                     Functions = 0x00000002,
                     Variables = 0x00000004,
                     Preprocessor = 0x00000008,
                     Classes = 0x00000010,
                     CommentCnv = 0x00000020,
                     CommentScan = 0x00000040,
                     PrintTree = 0x00000100,
                     Time = 0x00000200,
                     ExtCmd = 0x00000400,
                     Markdown = 0x00000800,
                     FilterOutput = 0x00001000,
                     Lex = 0x00002000,
                     Plantuml = 0x00004000,
                     FortranFixed2Free = 0x00008000,
                     Cite = 0x00010000,
                     NoLineNo = 0x00020000,
                     Rtf = 0x00040000,
                     Qhp = 0x00080000,
                     Tag = 0x00100000,
                   };
DebugMask [2/2]
enum Debug::DebugMask
Enumerator
Quiet
FindMembers
Functions
Variables
Preprocessor
Classes
CommentCnv
CommentScan
PrintTree
Time
ExtCmd
Markdown
FilterOutput
Lex
Plantuml
FortranFixed2Free
Cite
NoLineNo
Rtf
Qhp
Tag
Quiet
FindMembers
Functions
Variables
Preprocessor
Classes
CommentCnv
CommentScan
PrintTree
Time
ExtCmd
Markdown
FilterOutput
Lex
Plantuml
FortranFixed2Free
Cite
NoLineNo
Rtf
Qhp
Tag
Definition at line 25 of file debug.h.
                   { Quiet = 0x00000000,
                     FindMembers = 0x00000001,
                     Functions = 0x00000002,
                     Variables = 0x00000004,
                     Preprocessor = 0x00000008,
                     Classes = 0x00000010,
                     CommentCnv = 0x00000020,
                     CommentScan = 0x00000040,
                     PrintTree = 0x00000100,
                     Time = 0x00000200,
                     ExtCmd = 0x00000400,
                     Markdown = 0x00000800,
                     FilterOutput = 0x00001000,
                     Lex = 0x00002000,
                     Plantuml = 0x00004000,
                     FortranFixed2Free = 0x00008000,
                     Cite = 0x00010000,
                     NoLineNo = 0x00020000,
                     Rtf = 0x00040000,
                     Qhp = 0x00080000,
                     Tag = 0x00100000,
                   };
Member Function Documentation
clearFlag() [1/2]
void Debug::clearFlag (const QCString & label) [static]
Definition at line 90 of file debug.cpp.
{
  curMask = static_cast<DebugMask>(curMask & ~labelToEnumValue(lab));
}
References curMask.
Referenced by Statistics::print().
clearFlag() [2/2]
static void Debug::clearFlag (const QCString & label) [static]
elapsedTime() [1/2]
double Debug::elapsedTime () [static]
Definition at line 140 of file debug.cpp.
{
  return g_runningTime.elapsedTimeS();
}
References Timer::elapsedTimeS(), and g_runningTime.
Referenced by generateOutput(), and msg().
elapsedTime() [2/2]
static double Debug::elapsedTime () [static]
isFlagSet() [1/2]
bool Debug::isFlagSet (DebugMask mask) [static]
Definition at line 100 of file debug.cpp.
{
  return (curMask & mask)!=0;
}
References curMask.
Referenced by convertCppComments(), generateOutput(), CitationManager::generatePage(), LayoutDocManager::init(), msg(), LayoutDocManager::parse(), parseTagFile(), preProcessFile(), RTFGenerator::preProcessFileInplace(), Statistics::print(), print(), Preprocessor::processFile(), readIncludeFile(), runHtmlHelpCompiler(), runQHelpGenerator(), Trace::trace(), Trace::Trace(), validatingParseDoc(), validatingParseText(), writeIndent(), and Trace::~Trace().
isFlagSet() [2/2]
static bool Debug::isFlagSet (DebugMask mask) [static]
print() [1/2]
void Debug::print (DebugMask mask, int prio, const char * fmt, ...) [static]
Definition at line 58 of file debug.cpp.
{
  if ((curMask&mask) && prio<=curPrio)
  {
    va_list args;
    va_start(args,fmt);
    vfprintf(stdout, fmt, args);
    va_end(args);
  }
}
References curMask, curPrio, and fmt.
Referenced by FileDefImpl::acquireFileVersion(), addClassToContext(), addConceptToContext(), addLocalObjCMethod(), addMemberFunction(), addVariableToClass(), addVariableToFile(), computeClassRelations(), computeTemplateClassRelations(), convertCppComments(), filterMemberDocumentation(), findClassRelation(), findEnumDocumentation(), findGlobalMember(), findInheritedTemplateInstances(), findMember(), findTemplateInstanceRelation(), findUsedClassesForClass(), findUsedTemplateInstances(), findUsingDeclarations(), FilterCache::getFileContents(), PlantumlManager::insert(), ClassDefImpl::insertTemplateInstance(), CommentScanner::parseCommentBlock(), MarkdownOutlineParser::parseInput(), parseMain(), print(), printlex(), Markdown::process(), Preprocessor::processFile(), readCodeFragment(), readIncludeFile(), readInputFile(), rtfFormatBmkStr(), PlantumlManager::run(), runPlantumlContent(), runQHelpGenerator(), Portable::system(), and PlantumlManager::writePlantUMLSource().
print() [2/2]
static void Debug::print (DebugMask mask, int prio, const char * fmt, ...) [static]
printFlags() [1/2]
void Debug::printFlags () [static]
Definition at line 105 of file debug.cpp.
{
  for (const auto &v : s_labels)
  {
     msg("\t%s\n",v.first.c_str());
  }
}
References msg(), and s_labels.
Referenced by devUsage().
printFlags() [2/2]
static void Debug::printFlags () [static]
setFlag() [1/2]
int Debug::setFlag (const QCString & label) [static]
Definition at line 83 of file debug.cpp.
{
  int retVal = labelToEnumValue(lab);
  curMask = static_cast<DebugMask>(curMask | retVal);
  return retVal;
}
References curMask, and labelToEnumValue().
Referenced by Statistics::print(), and readConfiguration().
setFlag() [2/2]
static int Debug::setFlag (const QCString & label) [static]
setPriority() [1/2]
void Debug::setPriority (int p) [static]
Definition at line 95 of file debug.cpp.
{
  curPrio = p;
}
References curPrio, and p.
setPriority() [2/2]
static void Debug::setPriority (int p) [static]
startTimer() [1/2]
void Debug::startTimer () [static]
Definition at line 135 of file debug.cpp.
{
  g_runningTime.start();
}
References g_runningTime, and Timer::start().
Referenced by initDoxygen().
startTimer() [2/2]
static void Debug::startTimer () [static]
Member Data Documentation
curMask
static DebugMask Debug::curMask = Debug::Quiet [static], [private]
Definition at line 59 of file debug.h.
Referenced by clearFlag(), isFlagSet(), print(), and setFlag().
curPrio
static int Debug::curPrio = 0 [static], [private]
Definition at line 60 of file debug.h.
Referenced by print(), and setPriority().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/debug.h
doxygen/src/debug.h
doxygen/build/doxygen/src/debug.cpp
doxygen/src/debug.cpp