DocWord Class Reference
#include <docnode.h>
Public Member Functions
DocWord (DocParser *parser, DocNodeVariant *parent, const QCString &word)
QCString word () const
DocWord (DocParser *parser, DocNodeVariant *parent, const QCString &word)
QCString word () const
Private Attributes
QCString m_word
Additional Inherited Members
Detailed Description
Node representing a word
Definition at line 145 of file docnode.h.
Constructor & Destructor Documentation
DocWord() [1/2]
DocWord::DocWord (DocParser * parser, DocNodeVariant * parent, const QCString & word)
Definition at line 174 of file docnode.cpp.
                                                                              :
      DocNode(parser,parent), m_word(word)
{
  //printf("new word %s url=%s\n",qPrint(word),qPrint(parser->context.searchUrl));
  if (Doxygen::searchIndex && !parser->context.searchUrl.isEmpty())
  {
    parser->searchData.addWord(word,false);
  }
}
References SIDataCollection::addWord(), DocParser::context, QCString::isEmpty(), DocNode::parser(), DocParser::searchData, Doxygen::searchIndex, DocParserContext::searchUrl, and word().
DocWord() [2/2]
DocWord::DocWord (DocParser * parser, DocNodeVariant * parent, const QCString & word)
Member Function Documentation
word() [1/2]
QCString DocWord::word () const [inline]
Definition at line 149 of file docnode.h.
{ return m_word; }
References m_word.
Referenced by DocWord().
word() [2/2]
QCString DocWord::word () const [inline]
Definition at line 149 of file docnode.h.
{ return m_word; }
References m_word.
Member Data Documentation
m_word
QCString DocWord::m_word [private]
Definition at line 152 of file docnode.h.
Referenced by word().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docnode.h
doxygen/src/docnode.h
doxygen/build/doxygen/src/docnode.cpp
doxygen/src/docnode.cpp