ConfigOption Class Reference
#include <configimpl.h>
Public Types
enum OptionType {
O_Info
, O_List
, O_Enum
, O_String
,
O_Int
, O_Bool
, O_Obsolete
, O_Disabled
,
O_Info
, O_List
, O_Enum
, O_String
,
O_Int
, O_Bool
, O_Obsolete
, O_Disabled
 }
enum { MAX_OPTION_LENGTH = 23
 }
enum OptionType {
O_Info
, O_List
, O_Enum
, O_String
,
O_Int
, O_Bool
, O_Obsolete
, O_Disabled
,
O_Info
, O_List
, O_Enum
, O_String
,
O_Int
, O_Bool
, O_Obsolete
, O_Disabled
 }
enum { MAX_OPTION_LENGTH = 23
 }
Public Member Functions
ConfigOption (OptionType t)
virtual ~ConfigOption ()
OptionType kind () const
QCString name () const
QCString docs () const
QCString dependsOn () const
void addDependency (const char *dep)
void setEncoding (const QCString &e)
void setUserComment (const QCString &u)
ConfigOption (OptionType t)
virtual ~ConfigOption ()
OptionType kind () const
QCString name () const
QCString docs () const
QCString dependsOn () const
void addDependency (const char *dep)
void setEncoding (const QCString &e)
void setUserComment (const QCString &u)
Protected Member Functions
virtual void writeTemplate (TextStream &t, bool sl, bool upd)=0
virtual void compareDoxyfile (TextStream &t, Config::CompareMode compareMode)=0
virtual void writeXMLDoxyfile (TextStream &t)=0
virtual void convertStrToVal (Config::CompareMode compareMode)
virtual void emptyValueToDefault ()
virtual void substEnvVars ()=0
virtual void init ()
virtual bool isDefault ()
void writeBoolValue (TextStream &t, bool v, bool initSpace=true)
void writeIntValue (TextStream &t, int i, bool initSpace=true)
void writeStringValue (TextStream &t, const QCString &s, bool initSpace=true, bool wasQuoted=false)
void writeStringList (TextStream &t, const StringVector &l)
virtual void writeTemplate (TextStream &t, bool sl, bool upd)=0
virtual void compareDoxyfile (TextStream &t, Config::CompareMode compareMode)=0
virtual void writeXMLDoxyfile (TextStream &t)=0
virtual void convertStrToVal (Config::CompareMode compareMode)
virtual void emptyValueToDefault ()
virtual void substEnvVars ()=0
virtual void init ()
virtual bool isDefault ()
void writeBoolValue (TextStream &t, bool v, bool initSpace=true)
void writeIntValue (TextStream &t, int i, bool initSpace=true)
void writeStringValue (TextStream &t, const QCString &s, bool initSpace=true, bool wasQuoted=false)
void writeStringList (TextStream &t, const StringVector &l)
Protected Attributes
QCString m_spaces
QCString m_name
QCString m_doc
QCString m_dependency
QCString m_encoding
QCString m_userComment
OptionType m_kind
Friends
class ConfigImpl
Detailed Description
Abstract base class for any configuration option.
Definition at line 36 of file configimpl.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
MAX_OPTION_LENGTH Maximum length of an option in the config file. Used for alignment purposes.
Definition at line 54 of file configimpl.h.
    {
      MAX_OPTION_LENGTH = 23
    };
anonymous enum
anonymous enum
Enumerator
MAX_OPTION_LENGTH Maximum length of an option in the config file. Used for alignment purposes.
Definition at line 54 of file configimpl.h.
    {
      MAX_OPTION_LENGTH = 23
    };
OptionType [1/2]
enum ConfigOption::OptionType
The type of option
Enumerator
O_Info A section header.
O_List A list of items.
O_Enum A fixed set of items.
O_String A single item.
O_Int An integer value.
O_Bool A boolean value.
O_Obsolete An obsolete option.
O_Disabled Disabled compile time option.
O_Info A section header.
O_List A list of items.
O_Enum A fixed set of items.
O_String A single item.
O_Int An integer value.
O_Bool A boolean value.
O_Obsolete An obsolete option.
O_Disabled Disabled compile time option.
Definition at line 43 of file configimpl.h.
    {
      O_Info,
      O_List,
      O_Enum,
      O_String,
      O_Int,
      O_Bool,
      O_Obsolete,
      O_Disabled
    };
OptionType [2/2]
enum ConfigOption::OptionType
The type of option
Enumerator
O_Info A section header.
O_List A list of items.
O_Enum A fixed set of items.
O_String A single item.
O_Int An integer value.
O_Bool A boolean value.
O_Obsolete An obsolete option.
O_Disabled Disabled compile time option.
O_Info A section header.
O_List A list of items.
O_Enum A fixed set of items.
O_String A single item.
O_Int An integer value.
O_Bool A boolean value.
O_Obsolete An obsolete option.
O_Disabled Disabled compile time option.
Definition at line 43 of file configimpl.h.
    {
      O_Info,
      O_List,
      O_Enum,
      O_String,
      O_Int,
      O_Bool,
      O_Obsolete,
      O_Disabled
    };
Constructor & Destructor Documentation
ConfigOption() [1/2]
ConfigOption::ConfigOption (OptionType t) [inline]
Definition at line 61 of file configimpl.h.
                               : m_kind(t)
    {
      m_spaces.fill(' ',40);
    }
References QCString::fill(), and m_spaces.
 ConfigOption() [1/2]
virtual ConfigOption::~ConfigOption () [inline], [virtual]
Definition at line 65 of file configimpl.h.
    {
    }
ConfigOption() [2/2]
ConfigOption::ConfigOption (OptionType t) [inline]
Definition at line 61 of file configimpl.h.
                               : m_kind(t)
    {
      m_spaces.fill(' ',40);
    }
References QCString::fill(), and m_spaces.
 ConfigOption() [2/2]
virtual ConfigOption::~ConfigOption () [inline], [virtual]
Definition at line 65 of file configimpl.h.
    {
    }
Member Function Documentation
addDependency() [1/2]
void ConfigOption::addDependency (const char * dep) [inline]
Definition at line 75 of file configimpl.h.
{ m_dependency = dep; }
References m_dependency.
addDependency() [2/2]
void ConfigOption::addDependency (const char * dep) [inline]
Definition at line 75 of file configimpl.h.
{ m_dependency = dep; }
References m_dependency.
compareDoxyfile() [1/2]
virtual void ConfigOption::compareDoxyfile (TextStream & t, Config::CompareMode compareMode) [protected], [pure virtual]
Implemented in ConfigInfo, ConfigObsolete, ConfigDisabled, ConfigInfo, ConfigObsolete, ConfigDisabled, ConfigList, ConfigEnum, ConfigString, ConfigInt, ConfigBool, ConfigList, ConfigEnum, ConfigString, ConfigInt, and ConfigBool.
Referenced by ConfigImpl::compareDoxyfile().
compareDoxyfile() [2/2]
virtual void ConfigOption::compareDoxyfile (TextStream & t, Config::CompareMode compareMode) [protected], [pure virtual]
Implemented in ConfigInfo, ConfigObsolete, ConfigDisabled, ConfigInfo, ConfigObsolete, ConfigDisabled, ConfigList, ConfigEnum, ConfigString, ConfigInt, ConfigBool, ConfigList, ConfigEnum, ConfigString, ConfigInt, and ConfigBool.
convertStrToVal() [1/2]
virtual void ConfigOption::convertStrToVal (Config::CompareMode compareMode) [inline], [protected], [virtual]
Reimplemented in ConfigEnum, ConfigInt, ConfigBool, ConfigEnum, ConfigInt, and ConfigBool.
Definition at line 83 of file configimpl.h.
{}
Referenced by ConfigImpl::convertStrToVal().
convertStrToVal() [2/2]
virtual void ConfigOption::convertStrToVal (Config::CompareMode compareMode) [inline], [protected], [virtual]
Reimplemented in ConfigEnum, ConfigInt, ConfigBool, ConfigEnum, ConfigInt, and ConfigBool.
Definition at line 83 of file configimpl.h.
{}
dependsOn() [1/2]
QCString ConfigOption::dependsOn () const [inline]
Definition at line 74 of file configimpl.h.
{ return m_dependency; }
References m_dependency.
Referenced by Config::checkAndCorrect(), and ConfigImpl::init().
dependsOn() [2/2]
QCString ConfigOption::dependsOn () const [inline]
Definition at line 74 of file configimpl.h.
{ return m_dependency; }
References m_dependency.
docs() [1/2]
QCString ConfigOption::docs () const [inline]
Definition at line 72 of file configimpl.h.
{ return m_doc; }
References m_doc.
docs() [2/2]
QCString ConfigOption::docs () const [inline]
Definition at line 72 of file configimpl.h.
{ return m_doc; }
References m_doc.
emptyValueToDefault() [1/2]
virtual void ConfigOption::emptyValueToDefault () [inline], [protected], [virtual]
Reimplemented in ConfigList, ConfigString, ConfigList, and ConfigString.
Definition at line 84 of file configimpl.h.
{}
Referenced by ConfigImpl::emptyValueToDefault().
emptyValueToDefault() [2/2]
virtual void ConfigOption::emptyValueToDefault () [inline], [protected], [virtual]
Reimplemented in ConfigList, ConfigString, ConfigList, and ConfigString.
Definition at line 84 of file configimpl.h.
{}
init() [1/2]
virtual void ConfigOption::init () [inline], [protected], [virtual]
Reimplemented in ConfigList, ConfigEnum, ConfigString, ConfigInt, ConfigBool, ConfigList, ConfigEnum, ConfigString, ConfigInt, and ConfigBool.
Definition at line 86 of file configimpl.h.
{}
Referenced by ConfigImpl::init().
init() [2/2]
virtual void ConfigOption::init () [inline], [protected], [virtual]
Reimplemented in ConfigList, ConfigEnum, ConfigString, ConfigInt, ConfigBool, ConfigList, ConfigEnum, ConfigString, ConfigInt, and ConfigBool.
Definition at line 86 of file configimpl.h.
{}
isDefault() [1/2]
virtual bool ConfigOption::isDefault () [inline], [protected], [virtual]
Reimplemented in ConfigList, ConfigEnum, ConfigString, ConfigInt, ConfigBool, ConfigList, ConfigEnum, ConfigString, ConfigInt, and ConfigBool.
Definition at line 87 of file configimpl.h.
{ return true; }
isDefault() [2/2]
virtual bool ConfigOption::isDefault () [inline], [protected], [virtual]
Reimplemented in ConfigList, ConfigEnum, ConfigString, ConfigInt, ConfigBool, ConfigList, ConfigEnum, ConfigString, ConfigInt, and ConfigBool.
Definition at line 87 of file configimpl.h.
{ return true; }
kind() [1/2]
OptionType ConfigOption::kind () const [inline]
returns the kind of option this is.
Definition at line 70 of file configimpl.h.
{ return m_kind; }
References m_kind.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.sectiondefType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.docParamListType::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.sectiondefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.docSimpleSectType::buildAttributes(), doxmlparser.compound.docParamListType::buildAttributes(), doxmlparser.index.CompoundType::buildAttributes(), doxmlparser.index.MemberType::buildAttributes(), Config::checkAndCorrect(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.index.CompoundType::exportAttributes(), doxmlparser.compound.docParamListType::exportAttributes(), doxmlparser.compound.docSimpleSectType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.index.MemberType::exportAttributes(), doxmlparser.compound.sectiondefType::exportAttributes(), doxmlparser.compound.compounddefType::get_kind(), doxmlparser.compound.sectiondefType::get_kind(), doxmlparser.compound.memberdefType::get_kind(), doxmlparser.compound.docSimpleSectType::get_kind(), doxmlparser.compound.docParamListType::get_kind(), doxmlparser.index.CompoundType::get_kind(), doxmlparser.index.MemberType::get_kind(), doxmlparser.compound.compounddefType::set_kind(), doxmlparser.compound.sectiondefType::set_kind(), doxmlparser.compound.memberdefType::set_kind(), doxmlparser.compound.docSimpleSectType::set_kind(), doxmlparser.compound.docParamListType::set_kind(), doxmlparser.index.CompoundType::set_kind(), doxmlparser.index.MemberType::set_kind(), and Config::updateObsolete().
kind() [2/2]
OptionType ConfigOption::kind () const [inline]
returns the kind of option this is.
Definition at line 70 of file configimpl.h.
{ return m_kind; }
References m_kind.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.sectiondefType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.docParamListType::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.sectiondefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.docSimpleSectType::buildAttributes(), doxmlparser.compound.docParamListType::buildAttributes(), doxmlparser.index.CompoundType::buildAttributes(), doxmlparser.index.MemberType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.index.CompoundType::exportAttributes(), doxmlparser.compound.docParamListType::exportAttributes(), doxmlparser.compound.docSimpleSectType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.index.MemberType::exportAttributes(), doxmlparser.compound.sectiondefType::exportAttributes(), doxmlparser.compound.compounddefType::get_kind(), doxmlparser.compound.sectiondefType::get_kind(), doxmlparser.compound.memberdefType::get_kind(), doxmlparser.compound.docSimpleSectType::get_kind(), doxmlparser.compound.docParamListType::get_kind(), doxmlparser.index.CompoundType::get_kind(), doxmlparser.index.MemberType::get_kind(), doxmlparser.compound.compounddefType::set_kind(), doxmlparser.compound.sectiondefType::set_kind(), doxmlparser.compound.memberdefType::set_kind(), doxmlparser.compound.docSimpleSectType::set_kind(), doxmlparser.compound.docParamListType::set_kind(), doxmlparser.index.CompoundType::set_kind(), and doxmlparser.index.MemberType::set_kind().
name() [1/2]
QCString ConfigOption::name () const [inline]
Definition at line 71 of file configimpl.h.
{ return m_name; }
References m_name.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), Config::checkAndCorrect(), ConfigBool::ConfigBool(), ConfigDisabled::ConfigDisabled(), ConfigEnum::ConfigEnum(), ConfigInfo::ConfigInfo(), ConfigInt::ConfigInt(), ConfigList::ConfigList(), ConfigObsolete::ConfigObsolete(), ConfigString::ConfigString(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), ConfigImpl::init(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
name() [2/2]
QCString ConfigOption::name () const [inline]
Definition at line 71 of file configimpl.h.
{ return m_name; }
References m_name.
Referenced by doxmlparser.compound.MixedContainer::__init__(), doxmlparser.index.MixedContainer::__init__(), search.Finder::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.MemberSpec_::__init__(), doxmlparser.index.MemberSpec_::__init__(), doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.docEmojiType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.memberRefType::__init__(), doxmlparser.compound.docImageType::__init__(), search.Finder::baseClasses(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docEmojiType::buildAttributes(), doxmlparser.compound.memberRefType::buildChildren(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.index.CompoundType::buildChildren(), doxmlparser.index.MemberType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEmojiType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.index.CompoundType::exportChildren(), doxmlparser.compound.enumvalueType::exportChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberRefType::exportChildren(), doxmlparser.index.MemberType::exportChildren(), doxmlparser.compound.MixedContainer::exportLiteral(), doxmlparser.index.MixedContainer::exportLiteral(), doxmlparser.compound.MixedContainer::exportSimple(), doxmlparser.index.MixedContainer::exportSimple(), search.Finder::file(), search.Finder::function(), doxmlparser.compound.memberRefType::get_name(), doxmlparser.compound.memberdefType::get_name(), doxmlparser.compound.enumvalueType::get_name(), doxmlparser.compound.docImageType::get_name(), doxmlparser.compound.docDotMscType::get_name(), doxmlparser.compound.docImageFileType::get_name(), doxmlparser.compound.docPlantumlType::get_name(), doxmlparser.compound.tableofcontentsKindType::get_name(), doxmlparser.compound.docEmojiType::get_name(), doxmlparser.index.CompoundType::get_name(), doxmlparser.index.MemberType::get_name(), doxmlparser.compound.MixedContainer::getName(), doxmlparser.index.MixedContainer::getName(), doxmlparser.compound.memberRefType::hasContent_(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.enumvalueType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.index.CompoundType::hasContent_(), doxmlparser.index.MemberType::hasContent_(), search.Finder::includees(), search.Finder::includers(), search.Finder::macro(), search.Finder::members(), search.Finder::params(), search.Finder::references(), doxmlparser.compound.memberRefType::set_name(), doxmlparser.compound.memberdefType::set_name(), doxmlparser.compound.enumvalueType::set_name(), doxmlparser.compound.docImageType::set_name(), doxmlparser.compound.docDotMscType::set_name(), doxmlparser.compound.docImageFileType::set_name(), doxmlparser.compound.docPlantumlType::set_name(), doxmlparser.compound.tableofcontentsKindType::set_name(), doxmlparser.compound.docEmojiType::set_name(), doxmlparser.index.CompoundType::set_name(), doxmlparser.index.MemberType::set_name(), search.Finder::struct(), search.Finder::subClasses(), doxmlparser.compound.MixedContainer::to_etree(), doxmlparser.index.MixedContainer::to_etree(), search.Finder::typedef(), and search.Finder::variable().
setEncoding() [1/2]
void ConfigOption::setEncoding (const QCString & e) [inline]
Definition at line 76 of file configimpl.h.
{ m_encoding = e; }
References e, and m_encoding.
setEncoding() [2/2]
void ConfigOption::setEncoding (const QCString & e) [inline]
Definition at line 76 of file configimpl.h.
{ m_encoding = e; }
References e, and m_encoding.
setUserComment() [1/2]
void ConfigOption::setUserComment (const QCString & u) [inline]
Definition at line 77 of file configimpl.h.
{ m_userComment += u; }
References m_userComment.
setUserComment() [2/2]
void ConfigOption::setUserComment (const QCString & u) [inline]
Definition at line 77 of file configimpl.h.
{ m_userComment += u; }
References m_userComment.
substEnvVars() [1/2]
virtual void ConfigOption::substEnvVars () [protected], [pure virtual]
Implemented in ConfigInfo, ConfigList, ConfigEnum, ConfigString, ConfigInt, ConfigBool, ConfigObsolete, ConfigDisabled, ConfigInfo, ConfigList, ConfigEnum, ConfigString, ConfigInt, ConfigBool, ConfigObsolete, and ConfigDisabled.
Referenced by ConfigImpl::substituteEnvironmentVars().
substEnvVars() [2/2]
virtual void ConfigOption::substEnvVars () [protected], [pure virtual]
Implemented in ConfigInfo, ConfigList, ConfigEnum, ConfigString, ConfigInt, ConfigBool, ConfigObsolete, ConfigDisabled, ConfigInfo, ConfigList, ConfigEnum, ConfigString, ConfigInt, ConfigBool, ConfigObsolete, and ConfigDisabled.
writeBoolValue() [1/2]
void ConfigOption::writeBoolValue (TextStream & t, bool v, bool initSpace = true) [protected]
Definition at line 139 of file configimpl.l.
{
  if (initSpace) t << " ";
  if (v) t << "YES"; else t << "NO";
}
Referenced by ConfigBool::writeTemplate(), and ConfigBool::writeXMLDoxyfile().
writeBoolValue() [2/2]
void ConfigOption::writeBoolValue (TextStream & t, bool v, bool initSpace = true) [protected]
writeIntValue() [1/2]
void ConfigOption::writeIntValue (TextStream & t, int i, bool initSpace = true) [protected]
Definition at line 145 of file configimpl.l.
{
  if (initSpace) t << " ";
  t << i;
}
Referenced by ConfigInt::writeTemplate(), and ConfigInt::writeXMLDoxyfile().
writeIntValue() [2/2]
void ConfigOption::writeIntValue (TextStream & t, int i, bool initSpace = true) [protected]
writeStringList() [1/2]
void ConfigOption::writeStringList (TextStream & t, const StringVector & l) [protected]
Definition at line 183 of file configimpl.l.
{
  bool first=TRUE;
  for (const auto &p : l)
  {
    if (!first) t << " \\\n";
    QCString s=p.c_str();
    if (!first)
      t << " ";
    bool wasQuoted = ((s.at(0)=='"') && (s.at(s.length()-1)=='"'));
    if (wasQuoted)
    {
      s = s.mid(1,s.length()-2);
    }
    writeStringValue(t,s,true,wasQuoted);
    first=FALSE;
  }
}
References FALSE, p, s, TRUE, and writeStringValue().
Referenced by ConfigList::writeTemplate().
writeStringList() [2/2]
void ConfigOption::writeStringList (TextStream & t, const StringVector & l) [protected]
writeStringValue() [1/2]
void ConfigOption::writeStringValue (TextStream & t, const QCString & s, bool initSpace = true, bool wasQuoted = false) [protected]
Definition at line 151 of file configimpl.l.
{
  char c;
  bool needsEscaping=wasQuoted;
  // convert the string back to it original g_encoding
  QCString se = configStringRecode(s,"UTF-8",m_encoding);
  if (se.isEmpty()) return;
  const char *p=se.data();
  if (p)
  {
    if (initSpace) t << " ";
    while ((c=*p++)!=0 && !needsEscaping)
      needsEscaping = (c==' ' || c== ',' || c=='\n' || c=='\t' || c=='"' || c=='#');
    if (needsEscaping)
    {
      t << "\"";
      p=se.data();
      while (*p)
      {
        if (*p==' ' && *(p+1)=='\0') break; // skip inserted space at the end
        if (*p=='"') t << "\\"; // escape quotes
        t << *p++;
      }
      t << "\"";
    }
    else
    {
      t << se;
    }
  }
}
References c, configStringRecode(), QCString::data(), QCString::isEmpty(), m_encoding, p, and s.
Referenced by writeStringList(), ConfigInt::writeTemplate(), ConfigBool::writeTemplate(), ConfigEnum::writeTemplate(), ConfigString::writeTemplate(), ConfigList::writeXMLDoxyfile(), ConfigEnum::writeXMLDoxyfile(), and ConfigString::writeXMLDoxyfile().
writeStringValue() [2/2]
void ConfigOption::writeStringValue (TextStream & t, const QCString & s, bool initSpace = true, bool wasQuoted = false) [protected]
writeTemplate() [1/2]
virtual void ConfigOption::writeTemplate (TextStream & t, bool sl, bool upd) [protected], [pure virtual]
Implemented in ConfigObsolete, ConfigDisabled, ConfigObsolete, ConfigDisabled, ConfigInt, ConfigBool, ConfigInt, ConfigBool, ConfigInfo, ConfigList, ConfigEnum, ConfigString, ConfigInfo, ConfigList, ConfigEnum, and ConfigString.
Referenced by ConfigImpl::writeTemplate().
writeTemplate() [2/2]
virtual void ConfigOption::writeTemplate (TextStream & t, bool sl, bool upd) [protected], [pure virtual]
Implemented in ConfigObsolete, ConfigDisabled, ConfigObsolete, ConfigDisabled, ConfigInt, ConfigBool, ConfigInt, ConfigBool, ConfigInfo, ConfigList, ConfigEnum, ConfigString, ConfigInfo, ConfigList, ConfigEnum, and ConfigString.
writeXMLDoxyfile() [1/2]
virtual void ConfigOption::writeXMLDoxyfile (TextStream & t) [protected], [pure virtual]
Implemented in ConfigInfo, ConfigObsolete, ConfigDisabled, ConfigInfo, ConfigObsolete, ConfigDisabled, ConfigList, ConfigEnum, ConfigString, ConfigInt, ConfigBool, ConfigList, ConfigEnum, ConfigString, ConfigInt, and ConfigBool.
Referenced by ConfigImpl::writeXMLDoxyfile().
writeXMLDoxyfile() [2/2]
virtual void ConfigOption::writeXMLDoxyfile (TextStream & t) [protected], [pure virtual]
Implemented in ConfigInfo, ConfigObsolete, ConfigDisabled, ConfigInfo, ConfigObsolete, ConfigDisabled, ConfigList, ConfigEnum, ConfigString, ConfigInt, ConfigBool, ConfigList, ConfigEnum, ConfigString, ConfigInt, and ConfigBool.
Friends And Related Function Documentation
ConfigImpl
ConfigImpl [friend]
Definition at line 38 of file configimpl.h.
Member Data Documentation
m_dependency
QCString ConfigOption::m_dependency [protected]
Definition at line 97 of file configimpl.h.
Referenced by addDependency(), and dependsOn().
m_doc
QCString ConfigOption::m_doc [protected]
Definition at line 96 of file configimpl.h.
Referenced by ConfigBool::ConfigBool(), ConfigEnum::ConfigEnum(), ConfigInfo::ConfigInfo(), ConfigInt::ConfigInt(), ConfigList::ConfigList(), ConfigString::ConfigString(), docs(), ConfigInt::writeTemplate(), ConfigBool::writeTemplate(), ConfigInfo::writeTemplate(), ConfigList::writeTemplate(), ConfigEnum::writeTemplate(), and ConfigString::writeTemplate().
m_encoding
QCString ConfigOption::m_encoding [protected]
Definition at line 98 of file configimpl.h.
Referenced by setEncoding(), and writeStringValue().
m_kind
OptionType ConfigOption::m_kind [protected]
Definition at line 100 of file configimpl.h.
Referenced by kind().
m_name
QCString ConfigOption::m_name [protected]
Definition at line 95 of file configimpl.h.
Referenced by ConfigBool::ConfigBool(), ConfigDisabled::ConfigDisabled(), ConfigEnum::ConfigEnum(), ConfigInfo::ConfigInfo(), ConfigInt::ConfigInt(), ConfigList::ConfigList(), ConfigObsolete::ConfigObsolete(), ConfigString::ConfigString(), ConfigEnum::convertStrToVal(), ConfigInt::convertStrToVal(), ConfigBool::convertStrToVal(), name(), ConfigInt::writeTemplate(), ConfigBool::writeTemplate(), ConfigList::writeTemplate(), ConfigEnum::writeTemplate(), ConfigString::writeTemplate(), ConfigList::writeXMLDoxyfile(), ConfigEnum::writeXMLDoxyfile(), ConfigString::writeXMLDoxyfile(), ConfigInt::writeXMLDoxyfile(), and ConfigBool::writeXMLDoxyfile().
m_spaces
QCString ConfigOption::m_spaces [protected]
Definition at line 94 of file configimpl.h.
Referenced by ConfigOption(), ConfigInt::writeTemplate(), ConfigBool::writeTemplate(), ConfigList::writeTemplate(), ConfigEnum::writeTemplate(), and ConfigString::writeTemplate().
m_userComment
QCString ConfigOption::m_userComment [protected]
Definition at line 99 of file configimpl.h.
Referenced by ConfigImpl::compareDoxyfile(), setUserComment(), ConfigInt::writeTemplate(), ConfigBool::writeTemplate(), ConfigList::writeTemplate(), ConfigEnum::writeTemplate(), and ConfigString::writeTemplate().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/configimpl.h
doxygen/src/configimpl.h
doxygen/build/doxygen/src/configimpl.l
doxygen/src/configimpl.l