DocInclude Class Reference
#include <docnode.h>
Public Types
enum Type {
Include
, DontInclude
, VerbInclude
, HtmlInclude
,
LatexInclude
, IncWithLines
, Snippet
, IncludeDoc
,
SnippetDoc
, SnipWithLines
, DontIncWithLines
, RtfInclude
,
ManInclude
, DocbookInclude
, XmlInclude
, Include
,
DontInclude
, VerbInclude
, HtmlInclude
, LatexInclude
,
IncWithLines
, Snippet
, IncludeDoc
, SnippetDoc
,
SnipWithLines
, DontIncWithLines
, RtfInclude
, ManInclude
,
DocbookInclude
, XmlInclude
 }
enum Type {
Include
, DontInclude
, VerbInclude
, HtmlInclude
,
LatexInclude
, IncWithLines
, Snippet
, IncludeDoc
,
SnippetDoc
, SnipWithLines
, DontIncWithLines
, RtfInclude
,
ManInclude
, DocbookInclude
, XmlInclude
, Include
,
DontInclude
, VerbInclude
, HtmlInclude
, LatexInclude
,
IncWithLines
, Snippet
, IncludeDoc
, SnippetDoc
,
SnipWithLines
, DontIncWithLines
, RtfInclude
, ManInclude
,
DocbookInclude
, XmlInclude
 }
Public Member Functions
DocInclude (DocParser *parser, DocNodeVariant *parent, const QCString &file, const QCString &context, Type t, bool isExample, const QCString &exampleFile, const QCString &blockId, bool isBlock)
QCString file () const
QCString extension () const
Type type () const
QCString text () const
QCString context () const
QCString blockId () const
bool isExample () const
QCString exampleFile () const
bool isBlock () const
void parse (DocNodeVariant *)
DocInclude (DocParser *parser, DocNodeVariant *parent, const QCString &file, const QCString &context, Type t, bool isExample, const QCString &exampleFile, const QCString &blockId, bool isBlock)
QCString file () const
QCString extension () const
Type type () const
QCString text () const
QCString context () const
QCString blockId () const
bool isExample () const
QCString exampleFile () const
bool isBlock () const
void parse (DocNodeVariant *)
Private Attributes
QCString m_file
QCString m_context
QCString m_text
Type m_type
bool m_isExample
bool m_isBlock
QCString m_exampleFile
QCString m_blockId
Additional Inherited Members
Detailed Description
Node representing an included text block from file
Definition at line 408 of file docnode.h.
Member Enumeration Documentation
Type [1/2]
enum DocInclude::Type
Enumerator
Include
DontInclude
VerbInclude
HtmlInclude
LatexInclude
IncWithLines
Snippet
IncludeDoc
SnippetDoc
SnipWithLines
DontIncWithLines
RtfInclude
ManInclude
DocbookInclude
XmlInclude
Include
DontInclude
VerbInclude
HtmlInclude
LatexInclude
IncWithLines
Snippet
IncludeDoc
SnippetDoc
SnipWithLines
DontIncWithLines
RtfInclude
ManInclude
DocbookInclude
XmlInclude
Definition at line 411 of file docnode.h.
            { Include, DontInclude, VerbInclude, HtmlInclude, LatexInclude,
          IncWithLines, Snippet , IncludeDoc, SnippetDoc, SnipWithLines,
          DontIncWithLines, RtfInclude, ManInclude, DocbookInclude, XmlInclude};
Type [2/2]
enum DocInclude::Type
Enumerator
Include
DontInclude
VerbInclude
HtmlInclude
LatexInclude
IncWithLines
Snippet
IncludeDoc
SnippetDoc
SnipWithLines
DontIncWithLines
RtfInclude
ManInclude
DocbookInclude
XmlInclude
Include
DontInclude
VerbInclude
HtmlInclude
LatexInclude
IncWithLines
Snippet
IncludeDoc
SnippetDoc
SnipWithLines
DontIncWithLines
RtfInclude
ManInclude
DocbookInclude
XmlInclude
Definition at line 411 of file docnode.h.
            { Include, DontInclude, VerbInclude, HtmlInclude, LatexInclude,
          IncWithLines, Snippet , IncludeDoc, SnippetDoc, SnipWithLines,
          DontIncWithLines, RtfInclude, ManInclude, DocbookInclude, XmlInclude};
Constructor & Destructor Documentation
DocInclude() [1/2]
DocInclude::DocInclude (DocParser * parser, DocNodeVariant * parent, const QCString & file, const QCString & context, Type t, bool isExample, const QCString & exampleFile, const QCString & blockId, bool isBlock) [inline]
Definition at line 414 of file docnode.h.
    : DocNode(parser,parent), m_file(file), m_context(context), m_type(t),
      m_isExample(isExample), m_isBlock(isBlock),
      m_exampleFile(exampleFile), m_blockId(blockId) {}
DocInclude() [2/2]
DocInclude::DocInclude (DocParser * parser, DocNodeVariant * parent, const QCString & file, const QCString & context, Type t, bool isExample, const QCString & exampleFile, const QCString & blockId, bool isBlock) [inline]
Definition at line 414 of file docnode.h.
    : DocNode(parser,parent), m_file(file), m_context(context), m_type(t),
      m_isExample(isExample), m_isBlock(isBlock),
      m_exampleFile(exampleFile), m_blockId(blockId) {}
Member Function Documentation
blockId() [1/2]
QCString DocInclude::blockId () const [inline]
Definition at line 431 of file docnode.h.
{ return m_blockId; }
References m_blockId.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
blockId() [2/2]
QCString DocInclude::blockId () const [inline]
Definition at line 431 of file docnode.h.
{ return m_blockId; }
References m_blockId.
context() [1/2]
QCString DocInclude::context () const [inline]
Definition at line 430 of file docnode.h.
{ return m_context; }
References m_context.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), and parse().
context() [2/2]
QCString DocInclude::context () const [inline]
Definition at line 430 of file docnode.h.
{ return m_context; }
References m_context.
exampleFile() [1/2]
QCString DocInclude::exampleFile () const [inline]
Definition at line 433 of file docnode.h.
{ return m_exampleFile; }
References m_exampleFile.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
exampleFile() [2/2]
QCString DocInclude::exampleFile () const [inline]
Definition at line 433 of file docnode.h.
{ return m_exampleFile; }
References m_exampleFile.
extension() [1/2]
QCString DocInclude::extension () const [inline]
Definition at line 422 of file docnode.h.
                                 { int i=m_file.findRev('.');
                                   if (i!=-1)
                                     return m_file.right(m_file.length()-static_cast<uint>(i));
                                   else
                                     return QCString();
                                 }
References QCString::findRev(), QCString::length(), m_file, and QCString::right().
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
extension() [2/2]
QCString DocInclude::extension () const [inline]
Definition at line 422 of file docnode.h.
                                 { int i=m_file.findRev('.');
                                   if (i!=-1)
                                     return m_file.right(m_file.length()-static_cast<uint>(i));
                                   else
                                     return QCString();
                                 }
References QCString::findRev(), QCString::length(), m_file, and QCString::right().
file() [1/2]
QCString DocInclude::file () const [inline]
Definition at line 421 of file docnode.h.
{ return m_file; }
References m_file.
Referenced by doxmlparser.compound.locationType::__init__(), doxmlparser.compound.locationType::buildAttributes(), doxmlparser.compound.locationType::exportAttributes(), doxmlparser.compound.locationType::get_file(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), PrintDocVisitor::operator()(), and doxmlparser.compound.locationType::set_file().
file() [2/2]
QCString DocInclude::file () const [inline]
Definition at line 421 of file docnode.h.
{ return m_file; }
References m_file.
Referenced by doxmlparser.compound.locationType::__init__(), doxmlparser.compound.locationType::buildAttributes(), doxmlparser.compound.locationType::exportAttributes(), doxmlparser.compound.locationType::get_file(), and doxmlparser.compound.locationType::set_file().
isBlock() [1/2]
bool DocInclude::isBlock () const [inline]
Definition at line 434 of file docnode.h.
{ return m_isBlock; }
References m_isBlock.
Referenced by HtmlDocVisitor::operator()(), XmlDocVisitor::operator()(), and PrintDocVisitor::operator()().
isBlock() [2/2]
bool DocInclude::isBlock () const [inline]
Definition at line 434 of file docnode.h.
{ return m_isBlock; }
References m_isBlock.
isExample() [1/2]
bool DocInclude::isExample () const [inline]
Definition at line 432 of file docnode.h.
{ return m_isExample; }
References m_isExample.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
isExample() [2/2]
bool DocInclude::isExample () const [inline]
Definition at line 432 of file docnode.h.
{ return m_isExample; }
References m_isExample.
parse() [1/2]
void DocInclude::parse (DocNodeVariant *)
Definition at line 262 of file docnode.cpp.
{
  DBG(("DocInclude::parse(file=%s,text=%s)\n",qPrint(m_file),qPrint(m_text)));
  switch(m_type)
  {
    case DontIncWithLines:
      // fall through
    case IncWithLines:
      // fall through
    case Include:
      // fall through
    case DontInclude:
      parser()->readTextFileByName(m_file,m_text);
      parser()->context.includeFileName = m_file;
      parser()->context.includeFileText = m_text;
      parser()->context.includeFileOffset = 0;
      parser()->context.includeFileLength = m_text.length();
      parser()->context.includeFileLine = 0;
      parser()->context.includeFileShowLineNo = (m_type == DontIncWithLines || m_type == IncWithLines);
      //printf("parser->context.includeFile=<<%s>>\n",qPrint(parser->context.includeFileText));
      break;
    case VerbInclude:
      // fall through
    case HtmlInclude:
    case LatexInclude:
    case DocInclude::RtfInclude:
    case DocInclude::ManInclude:
    case DocInclude::XmlInclude:
    case DocInclude::DocbookInclude:
      parser()->readTextFileByName(m_file,m_text);
      break;
    case Snippet:
    case SnipWithLines:
      parser()->readTextFileByName(m_file,m_text);
      // check here for the existence of the blockId inside the file, so we
      // only generate the warning once.
      int count;
      if (!m_blockId.isEmpty() && (count=m_text.contains(m_blockId.data()))!=2)
      {
        warn_doc_error(parser()->context.fileName,
                       parser()->tokenizer.getLineNr(),
                       "block marked with %s for \\snippet should appear twice in file %s, found it %d times\n",
                       qPrint(m_blockId),qPrint(m_file),count);
      }
      break;
    case DocInclude::SnippetDoc:
    case DocInclude::IncludeDoc:
      err("Internal inconsistency: found switch SnippetDoc / IncludeDoc in file: %s"
          "Please create a bug report\n",__FILE__);
      break;
  }
}
References QCString::contains(), context(), DocParser::context, QCString::data(), DBG, DocbookInclude, DontInclude, DontIncWithLines, err(), HtmlInclude, Include, IncludeDoc, DocParserContext::includeFileLength, DocParserContext::includeFileLine, DocParserContext::includeFileName, DocParserContext::includeFileOffset, DocParserContext::includeFileShowLineNo, DocParserContext::includeFileText, IncWithLines, QCString::isEmpty(), LatexInclude, QCString::length(), m_blockId, m_file, m_text, m_type, ManInclude, DocNode::parser(), qPrint(), DocParser::readTextFileByName(), RtfInclude, Snippet, SnippetDoc, SnipWithLines, VerbInclude, warn_doc_error(), and XmlInclude.
parse() [2/2]
void DocInclude::parse (DocNodeVariant *)
text() [1/2]
QCString DocInclude::text () const [inline]
Definition at line 429 of file docnode.h.
{ return m_text; }
References m_text.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), PerlModDocVisitor::operator()(), RTFDocVisitor::operator()(), and XmlDocVisitor::operator()().
text() [2/2]
QCString DocInclude::text () const [inline]
Definition at line 429 of file docnode.h.
{ return m_text; }
References m_text.
type() [1/2]
Type DocInclude::type () const [inline]
Definition at line 428 of file docnode.h.
{ return m_type; }
References m_type.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), PerlModDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), and PrintDocVisitor::operator()().
type() [2/2]
Type DocInclude::type () const [inline]
Definition at line 428 of file docnode.h.
{ return m_type; }
References m_type.
Member Data Documentation
m_blockId
QCString DocInclude::m_blockId [private]
Definition at line 445 of file docnode.h.
Referenced by blockId(), and parse().
m_context
QCString DocInclude::m_context [private]
Definition at line 439 of file docnode.h.
Referenced by context().
m_exampleFile
QCString DocInclude::m_exampleFile [private]
Definition at line 444 of file docnode.h.
Referenced by exampleFile().
m_file
QCString DocInclude::m_file [private]
Definition at line 438 of file docnode.h.
Referenced by extension(), file(), and parse().
m_isBlock
bool DocInclude::m_isBlock [private]
Definition at line 443 of file docnode.h.
Referenced by isBlock().
m_isExample
bool DocInclude::m_isExample [private]
Definition at line 442 of file docnode.h.
Referenced by isExample().
m_text
QCString DocInclude::m_text [private]
Definition at line 440 of file docnode.h.
Referenced by parse(), and text().
m_type
Type DocInclude::m_type [private]
Definition at line 441 of file docnode.h.
Referenced by parse(), and type().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docnode.h
doxygen/src/docnode.h
doxygen/build/doxygen/src/docnode.cpp
doxygen/src/docnode.cpp