TemplateNodeFactory Class Reference
Factory class for creating tag AST nodes found in a template.
Classes
class AutoRegister
Helper class for registering a template AST node.
Public Types
typedef TemplateNodePtr(* CreateFunc) (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
typedef TemplateNodePtr(* CreateFunc) (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
Public Member Functions
TemplateNodePtr create (const QCString &name, TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void registerTemplateNode (const QCString &name, CreateFunc func)
TemplateNodePtr create (const QCString &name, TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void registerTemplateNode (const QCString &name, CreateFunc func)
Static Public Member Functions
static TemplateNodeFactory & instance ()
static TemplateNodeFactory & instance ()
Private Attributes
std::unordered_map< std::string, CreateFunc > m_registry
Detailed Description
Factory class for creating tag AST nodes found in a template.
Definition at line 4662 of file template.cpp.
Member Typedef Documentation
CreateFunc [1/2]
typedef TemplateNodePtr(* TemplateNodeFactory::CreateFunc) (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
Definition at line 4665 of file template.cpp.
CreateFunc [2/2]
typedef TemplateNodePtr(* TemplateNodeFactory::CreateFunc) (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
Definition at line 4665 of file template.cpp.
Member Function Documentation
create() [1/2]
TemplateNodePtr TemplateNodeFactory::create (const QCString & name, TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 4677 of file template.cpp.
    {
      auto it = m_registry.find(name.str());
      if (it==m_registry.end()) return 0;
      return it->second(parser,parent,line,data);
    }
References data, m_registry, setup::name, and parent().
Referenced by TemplateParser::parse().
create() [2/2]
TemplateNodePtr TemplateNodeFactory::create (const QCString & name, TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 4677 of file template.cpp.
    {
      auto it = m_registry.find(name.str());
      if (it==m_registry.end()) return 0;
      return it->second(parser,parent,line,data);
    }
References data, m_registry, setup::name, and parent().
instance() [1/2]
static TemplateNodeFactory & TemplateNodeFactory::instance () [inline], [static]
Definition at line 4670 of file template.cpp.
    {
      static std::unique_ptr<TemplateNodeFactory> instance;
      if (instance==0) instance = std::make_unique<TemplateNodeFactory>();
      return *instance;
    }
References instance().
Referenced by instance(), and TemplateParser::parse().
instance() [2/2]
static TemplateNodeFactory & TemplateNodeFactory::instance () [inline], [static]
Definition at line 4670 of file template.cpp.
    {
      static std::unique_ptr<TemplateNodeFactory> instance;
      if (instance==0) instance = std::make_unique<TemplateNodeFactory>();
      return *instance;
    }
References instance().
registerTemplateNode() [1/2]
void TemplateNodeFactory::registerTemplateNode (const QCString & name, CreateFunc func) [inline]
Definition at line 4688 of file template.cpp.
    {
      m_registry.insert(std::make_pair(name.str(),func));
    }
References docstring::func(), m_registry, and setup::name.
registerTemplateNode() [2/2]
void TemplateNodeFactory::registerTemplateNode (const QCString & name, CreateFunc func) [inline]
Definition at line 4688 of file template.cpp.
    {
      m_registry.insert(std::make_pair(name.str(),func));
    }
References docstring::func(), m_registry, and setup::name.
Member Data Documentation
m_registry
std::unordered_map< std::string, CreateFunc > TemplateNodeFactory::m_registry [private]
Definition at line 4704 of file template.cpp.
Referenced by create(), and registerTemplateNode().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp