PythonOutlineParser Class Reference
Python Language parser using state-based lexical scanning.
#include <pyscanner.h>
Classes
struct Private
Public Member Functions
PythonOutlineParser ()
virtual ~PythonOutlineParser ()
void parseInput (const QCString &fileName, const char *fileBuf, const std::shared_ptr< Entry > &root, ClangTUParser *clangParser)
bool needsPreprocessing (const QCString &extension) const
void parsePrototype (const QCString &text)
PythonOutlineParser ()
virtual ~PythonOutlineParser ()
void parseInput (const QCString &fileName, const char *fileBuf, const std::shared_ptr< Entry > &root, ClangTUParser *clangParser)
bool needsPreprocessing (const QCString &extension) const
void parsePrototype (const QCString &text)
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Python Language parser using state-based lexical scanning.
This is the Python language parser for doxygen.
Definition at line 34 of file pyscanner.h.
Constructor & Destructor Documentation
PythonOutlineParser() [1/2]
PythonOutlineParser::PythonOutlineParser ()
Definition at line 1974 of file pyscanner.l.
                                         : p(std::make_unique<PythonOutlineParser::Private>())
{
  pyscannerYYlex_init_extra(&p->state,&p->yyscanner);
#ifdef FLEX_DEBUG
  pyscannerYYset_debug(1,p->yyscanner);
#endif
}
References p.
 PythonOutlineParser() [1/2]
PythonOutlineParser::~PythonOutlineParser () [virtual]
Definition at line 1982 of file pyscanner.l.
{
  pyscannerYYlex_destroy(p->yyscanner);
}
References p.
PythonOutlineParser() [2/2]
PythonOutlineParser::PythonOutlineParser ()
 PythonOutlineParser() [2/2]
virtual PythonOutlineParser::~PythonOutlineParser () [virtual]
Member Function Documentation
needsPreprocessing() [1/2]
bool PythonOutlineParser::needsPreprocessing (const QCString & extension) const [virtual]
Returns TRUE if the language identified by extension needs the C preprocessor to be run before feed the result to the input parser.
See also
parseInput()
Implements OutlineParserInterface.
Definition at line 2003 of file pyscanner.l.
{
  return FALSE;
}
References FALSE.
needsPreprocessing() [2/2]
bool PythonOutlineParser::needsPreprocessing (const QCString & extension) const [virtual]
Returns TRUE if the language identified by extension needs the C preprocessor to be run before feed the result to the input parser.
See also
parseInput()
Implements OutlineParserInterface.
parseInput() [1/2]
void PythonOutlineParser::parseInput (const QCString & fileName, const char * fileBuf, const std::shared_ptr< Entry > & root, ClangTUParser * clangParser) [virtual]
Parses a single input file with the goal to build an Entry tree.
Parameters
 in fileName The full name of the file.
 in fileBuf The contents of the file (zero terminated).
 in,out root The root of the tree of Entry *nodes representing the information extracted from the file.
 in clangParser The clang translation unit parser object or nullptr if disabled.
Implements OutlineParserInterface.
Definition at line 1988 of file pyscanner.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)p->yyscanner;
  yyextra->thisParser = this;
  printlex(yy_flex_debug, TRUE, __FILE__, qPrint(fileName));
  ::parseMain(p->yyscanner, fileName,fileBuf,root);
  printlex(yy_flex_debug, FALSE, __FILE__, qPrint(fileName));
  // May print the AST for debugging purposes
  // printAST(global_root);
}
References FALSE, p, parseMain(), printlex(), qPrint(), and TRUE.
parseInput() [2/2]
void PythonOutlineParser::parseInput (const QCString & fileName, const char * fileBuf, const std::shared_ptr< Entry > & root, ClangTUParser * clangParser) [virtual]
Parses a single input file with the goal to build an Entry tree.
Parameters
 in fileName The full name of the file.
 in fileBuf The contents of the file (zero terminated).
 in,out root The root of the tree of Entry *nodes representing the information extracted from the file.
 in clangParser The clang translation unit parser object or nullptr if disabled.
Implements OutlineParserInterface.
parsePrototype() [1/2]
void PythonOutlineParser::parsePrototype (const QCString & text) [virtual]
Callback function called by the comment block scanner. It provides a string text containing the prototype of a function or variable. The parser should parse this and store the information in the Entry node that corresponds with the node for which the comment block parser was invoked.
Implements OutlineParserInterface.
Definition at line 2008 of file pyscanner.l.
{
  ::parsePrototype(p->yyscanner,text);
}
References p, and parsePrototype().
Referenced by parsePrototype().
parsePrototype() [2/2]
void PythonOutlineParser::parsePrototype (const QCString & text) [virtual]
Callback function called by the comment block scanner. It provides a string text containing the prototype of a function or variable. The parser should parse this and store the information in the Entry node that corresponds with the node for which the comment block parser was invoked.
Implements OutlineParserInterface.
Member Data Documentation
p
std::unique_ptr< Private > PythonOutlineParser::p [private]
Definition at line 47 of file pyscanner.h.
Referenced by parseInput(), parsePrototype(), PythonOutlineParser(), and ~PythonOutlineParser().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/pyscanner.h
doxygen/src/pyscanner.h
doxygen/build/doxygen/src/pyscanner.l
doxygen/src/pyscanner.l