DocHtmlTable Class Reference
#include <docnode.h>
Public Member Functions
DocHtmlTable (DocParser *parser, DocNodeVariant *parent, const HtmlAttribList &attribs)
size_t numRows () const
bool hasCaption () const
const HtmlAttribList & attribs () const
int parse (DocNodeVariant *)
int parseXml (DocNodeVariant *)
size_t numColumns () const
const DocNodeVariant * caption () const
const DocNodeVariant * firstRow () const
DocHtmlTable (DocParser *parser, DocNodeVariant *parent, const HtmlAttribList &attribs)
size_t numRows () const
bool hasCaption () const
const HtmlAttribList & attribs () const
int parse (DocNodeVariant *)
int parseXml (DocNodeVariant *)
size_t numColumns () const
const DocNodeVariant * caption () const
const DocNodeVariant * firstRow () const
Private Member Functions
void computeTableGrid ()
void computeTableGrid ()
Private Attributes
std::unique_ptr< DocNodeVariant > m_caption
HtmlAttribList m_attribs
size_t m_numCols = 0
Additional Inherited Members
Detailed Description
Node representing a HTML table
Definition at line 1221 of file docnode.h.
Constructor & Destructor Documentation
DocHtmlTable() [1/2]
DocHtmlTable::DocHtmlTable (DocParser * parser, DocNodeVariant * parent, const HtmlAttribList & attribs) [inline]
Definition at line 1224 of file docnode.h.
      : DocCompoundNode(parser,parent), m_attribs(attribs) {}
DocHtmlTable() [2/2]
DocHtmlTable::DocHtmlTable (DocParser * parser, DocNodeVariant * parent, const HtmlAttribList & attribs) [inline]
Definition at line 1224 of file docnode.h.
      : DocCompoundNode(parser,parent), m_attribs(attribs) {}
Member Function Documentation
attribs() [1/2]
const HtmlAttribList & DocHtmlTable::attribs () const [inline]
Definition at line 1228 of file docnode.h.
{ return m_attribs; }
References m_attribs.
Referenced by HtmlDocVisitor::operator()(), and XmlDocVisitor::operator()().
attribs() [2/2]
const HtmlAttribList & DocHtmlTable::attribs () const [inline]
Definition at line 1228 of file docnode.h.
{ return m_attribs; }
References m_attribs.
caption() [1/2]
const DocNodeVariant * DocHtmlTable::caption () const
Definition at line 1929 of file docnode.cpp.
{
  return m_caption.get();
}
References m_caption.
Referenced by doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docTableType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docTableType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.compound.docTableType::exportChildren(), doxmlparser.compound.docTableType::get_caption(), doxmlparser.compound.docImageType::get_caption(), doxmlparser.compound.docDotMscType::get_caption(), doxmlparser.compound.docPlantumlType::get_caption(), doxmlparser.compound.docTableType::hasContent_(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), PerlModDocVisitor::operator()(), XmlDocVisitor::operator()(), LatexDocVisitor::operator()(), PrintDocVisitor::operator()(), RTFDocVisitor::operator()(), doxmlparser.compound.docTableType::set_caption(), doxmlparser.compound.docImageType::set_caption(), doxmlparser.compound.docDotMscType::set_caption(), and doxmlparser.compound.docPlantumlType::set_caption().
caption() [2/2]
const DocNodeVariant * DocHtmlTable::caption () const
Referenced by doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docTableType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docTableType::buildChildren(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.compound.docTableType::exportChildren(), doxmlparser.compound.docTableType::get_caption(), doxmlparser.compound.docImageType::get_caption(), doxmlparser.compound.docDotMscType::get_caption(), doxmlparser.compound.docPlantumlType::get_caption(), doxmlparser.compound.docTableType::hasContent_(), doxmlparser.compound.docTableType::set_caption(), doxmlparser.compound.docImageType::set_caption(), doxmlparser.compound.docDotMscType::set_caption(), and doxmlparser.compound.docPlantumlType::set_caption().
computeTableGrid() [1/2]
void DocHtmlTable::computeTableGrid () [private]
determines the location of all cells in a grid, resolving row and column spans. For each the total number of visible cells is computed, and the total number of visible columns over all rows is stored.
Definition at line 2069 of file docnode.cpp.
{
  //printf("computeTableGrid()\n");
  RowSpanList rowSpans;
  uint maxCols=0;
  uint rowIdx=1;
  for (auto &rowNode : children())
  {
    uint colIdx=1;
    uint cells=0;
    DocHtmlRow *row = std::get_if<DocHtmlRow>(&rowNode);
    if (row)
    {
      size_t i;
      for (auto &cellNode : row->children())
      {
        DocHtmlCell *cell = std::get_if<DocHtmlCell>(&cellNode);
        if (cell)
        {
          uint rs = cell->rowSpan();
          uint cs = cell->colSpan();
          for (i=0;i<rowSpans.size();i++)
          {
            if (rowSpans[i].rowsLeft>0 &&
                rowSpans[i].column==colIdx)
            {
              colIdx=rowSpans[i].column+1;
              cells++;
            }
          }
          if (rs>0) rowSpans.emplace_back(rs,colIdx);
          //printf("found cell at (%d,%d)\n",rowIdx,colIdx);
          cell->setRowIndex(rowIdx);
          cell->setColumnIndex(colIdx);
          colIdx+=cs;
          cells++;
        }
      }
      for (i=0;i<rowSpans.size();i++)
      {
        if (rowSpans[i].rowsLeft>0) rowSpans[i].rowsLeft--;
      }
      row->setVisibleCells(cells);
      row->setRowIndex(rowIdx);
      rowIdx++;
    }
    if (colIdx-1>maxCols) maxCols=colIdx-1;
  }
  m_numCols = maxCols;
}
References DocCompoundNode::children(), DocHtmlCell::colSpan(), cs, m_numCols, DocHtmlCell::rowSpan(), DocHtmlCell::setColumnIndex(), DocHtmlCell::setRowIndex(), DocHtmlRow::setRowIndex(), and DocHtmlRow::setVisibleCells().
Referenced by parse(), and parseXml().
computeTableGrid() [2/2]
void DocHtmlTable::computeTableGrid () [private]
firstRow() [1/2]
const DocNodeVariant * DocHtmlTable::firstRow () const
Definition at line 1934 of file docnode.cpp.
{
  if (!children().empty() && std::holds_alternative<DocHtmlRow>(children().front()))
  {
    return &children().front();
  }
  return 0;
}
References DocCompoundNode::children(), and GrowVector< T >::front().
Referenced by LatexDocVisitor::operator()().
firstRow() [2/2]
const DocNodeVariant * DocHtmlTable::firstRow () const
hasCaption() [1/2]
bool DocHtmlTable::hasCaption () const
Definition at line 1924 of file docnode.cpp.
{
  return m_caption!=nullptr;
}
References m_caption.
hasCaption() [2/2]
bool DocHtmlTable::hasCaption () const
numColumns() [1/2]
size_t DocHtmlTable::numColumns () const [inline]
Definition at line 1231 of file docnode.h.
{ return m_numCols; }
References m_numCols.
Referenced by DocbookDocVisitor::operator()(), XmlDocVisitor::operator()(), LatexDocVisitor::operator()(), and PrintDocVisitor::operator()().
numColumns() [2/2]
size_t DocHtmlTable::numColumns () const [inline]
Definition at line 1231 of file docnode.h.
{ return m_numCols; }
References m_numCols.
numRows() [1/2]
size_t DocHtmlTable::numRows () const [inline]
Definition at line 1226 of file docnode.h.
{ return children().size(); }
References DocCompoundNode::children(), and GrowVector< T >::size().
Referenced by PerlModDocVisitor::operator()(), XmlDocVisitor::operator()(), and PrintDocVisitor::operator()().
numRows() [2/2]
size_t DocHtmlTable::numRows () const [inline]
Definition at line 1226 of file docnode.h.
{ return children().size(); }
References DocCompoundNode::children(), and GrowVector< T >::size().
parse() [1/2]
int DocHtmlTable::parse (DocNodeVariant * thisVariant)
Definition at line 1943 of file docnode.cpp.
{
  int retval=RetVal_OK;
  auto ns = AutoNodeStack(parser(),thisVariant);
  DBG(("DocHtmlTable::parse() start\n"));
getrow:
  // get next token
  int tok=parser()->tokenizer.lex();
  // skip whitespace
  while (tok==TK_WHITESPACE || tok==TK_NEWPARA) tok=parser()->tokenizer.lex();
  // should find a html tag now
  if (tok==TK_HTMLTAG)
  {
    int tagId=Mappers::htmlTagMapper->map(parser()->context.token->name);
    if (tagId==HTML_TR && !parser()->context.token->endTag) // found <tr> tag
    {
      // no caption, just rows
      retval=RetVal_TableRow;
    }
    else if (tagId==HTML_CAPTION && !parser()->context.token->endTag) // found <caption> tag
    {
      if (m_caption)
      {
        warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"table already has a caption, found another one");
      }
      else
      {
        m_caption = std::make_unique<DocNodeVariant>(
            DocHtmlCaption(parser(),thisVariant,parser()->context.token->attribs));
        retval=std::get<DocHtmlCaption>(*m_caption).parse(m_caption.get());
        if (retval==RetVal_OK) // caption was parsed ok
        {
          goto getrow;
        }
      }
    }
    else // found wrong token
    {
      warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"expected <tr> or <caption> tag but "
          "found <%s%s> instead!", parser()->context.token->endTag ? "/" : "", qPrint(parser()->context.token->name));
    }
  }
  else if (tok==0) // premature end of comment
  {
      warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"unexpected end of comment while looking"
          " for a <tr> or <caption> tag");
  }
  else // token other than html token
  {
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"expected <tr> tag but found %s token instead!",
        DocTokenizer::tokToString(tok));
  }
  // parse one or more rows
  while (retval==RetVal_TableRow)
  {
    auto vDocHtmlRow = children().append<DocHtmlRow>(parser(),thisVariant,parser()->context.token->attribs);
    retval = children().get_last<DocHtmlRow>()->parse(vDocHtmlRow);
  }
  computeTableGrid();
  DBG(("DocHtmlTable::parse() end\n"));
  return retval==RetVal_EndTable ? RetVal_OK : retval;
}
References DocNodeList::append(), TokenInfo::attribs, DocCompoundNode::children(), computeTableGrid(), DocParser::context, DBG, DocNodeList::get_last(), HTML_CAPTION, HTML_TR, Mappers::htmlTagMapper, DocTokenizer::lex(), m_caption, Mapper::map(), parse(), DocNode::parser(), qPrint(), RetVal_EndTable, RetVal_OK, RetVal_TableRow, TK_HTMLTAG, TK_NEWPARA, TK_WHITESPACE, DocParserContext::token, DocParser::tokenizer, DocTokenizer::tokToString(), and warn_doc_error().
Referenced by parse().
parse() [2/2]
int DocHtmlTable::parse (DocNodeVariant *)
parseXml() [1/2]
int DocHtmlTable::parseXml (DocNodeVariant * thisVariant)
Definition at line 2011 of file docnode.cpp.
{
  int retval=RetVal_OK;
  auto ns = AutoNodeStack(parser(),thisVariant);
  DBG(("DocHtmlTable::parseXml() start\n"));
  // get next token
  int tok=parser()->tokenizer.lex();
  // skip whitespace
  while (tok==TK_WHITESPACE || tok==TK_NEWPARA) tok=parser()->tokenizer.lex();
  // should find a html tag now
  int tagId=0;
  bool isHeader=FALSE;
  if (tok==TK_HTMLTAG)
  {
    tagId=Mappers::htmlTagMapper->map(parser()->context.token->name);
    if (tagId==XML_ITEM && !parser()->context.token->endTag) // found <item> tag
    {
      retval=RetVal_TableRow;
    }
    if (tagId==XML_LISTHEADER && !parser()->context.token->endTag) // found <listheader> tag
    {
      retval=RetVal_TableRow;
      isHeader=TRUE;
    }
  }
  // parse one or more rows
  while (retval==RetVal_TableRow)
  {
    auto vDocHtmlRow = children().append<DocHtmlRow>(parser(),thisVariant,parser()->context.token->attribs);
    DocHtmlRow *tr = children().get_last<DocHtmlRow>();
    retval=tr->parseXml(vDocHtmlRow,isHeader);
    isHeader=FALSE;
  }
  computeTableGrid();
  DBG(("DocHtmlTable::parseXml() end\n"));
  tagId=Mappers::htmlTagMapper->map(parser()->context.token->name);
  return tagId==XML_LIST && parser()->context.token->endTag ? RetVal_OK : retval;
}
References DocNodeList::append(), TokenInfo::attribs, DocCompoundNode::children(), computeTableGrid(), DocParser::context, DBG, TokenInfo::endTag, FALSE, DocNodeList::get_last(), Mappers::htmlTagMapper, DocTokenizer::lex(), Mapper::map(), DocNode::parser(), DocHtmlRow::parseXml(), RetVal_OK, RetVal_TableRow, TK_HTMLTAG, TK_NEWPARA, TK_WHITESPACE, DocParserContext::token, DocParser::tokenizer, TRUE, XML_ITEM, XML_LIST, and XML_LISTHEADER.
parseXml() [2/2]
int DocHtmlTable::parseXml (DocNodeVariant *)
Member Data Documentation
m_attribs
HtmlAttribList DocHtmlTable::m_attribs [private]
Definition at line 1238 of file docnode.h.
Referenced by attribs().
m_caption
std::unique_ptr< DocNodeVariant > DocHtmlTable::m_caption [private]
Definition at line 1237 of file docnode.h.
Referenced by caption(), hasCaption(), and parse().
m_numCols
size_t DocHtmlTable::m_numCols = 0 [private]
Definition at line 1239 of file docnode.h.
Referenced by computeTableGrid(), and numColumns().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docnode.h
doxygen/src/docnode.h
doxygen/build/doxygen/src/docnode.cpp
doxygen/src/docnode.cpp