TemplateList Class Reference
Default implementation of a context value of type list.
Public Member Functions
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
virtual void append (const TemplateVariant &v)
void removeAt (size_t index)
void insertAt (size_t index, TemplateListPtr list)
TemplateList ()=default
virtual ~TemplateList ()=default
virtual size_t count () const
virtual TemplateVariant at (size_t index) const
virtual TemplateListIntf::ConstIteratorPtr createIterator () const
virtual void append (const TemplateVariant &v)
void removeAt (size_t index)
void insertAt (size_t index, TemplateListPtr list)
TemplateList ()=default
virtual ~TemplateList ()=default
Static Public Member Functions
static TemplateListPtr alloc ()
static TemplateListPtr alloc ()
Private Attributes
TemplateVariantList m_elems
Additional Inherited Members
Detailed Description
Default implementation of a context value of type list.
Definition at line 272 of file template.cpp.
Constructor & Destructor Documentation
TemplateList() [1/2]
TemplateList::TemplateList () [default]
Creates a list
 TemplateList() [1/2]
virtual TemplateList::~TemplateList () [virtual], [default]
Destroys the list
TemplateList() [2/2]
TemplateList::TemplateList () [default]
Creates a list
 TemplateList() [2/2]
virtual TemplateList::~TemplateList () [virtual], [default]
Destroys the list
Member Function Documentation
alloc() [1/2]
static TemplateListPtr TemplateList::alloc () [inline], [static]
Creates an instance and returns a shared pointer to it
Definition at line 290 of file template.cpp.
    {
      return std::make_shared<TemplateList>();
    }
Referenced by TemplateContextImpl::addIndexEntry(), FilterList::apply(), FilterFlatten::apply(), FilterKeep::apply(), FilterListSort::apply(), FilterGroupBy::apply(), FilterPaginate::apply(), FilterAlphaIndex::apply(), getPathFunc(), and TemplateContextImpl::openSubIndex().
alloc() [2/2]
static TemplateListPtr TemplateList::alloc () [inline], [static]
Creates an instance and returns a shared pointer to it
Definition at line 290 of file template.cpp.
    {
      return std::make_shared<TemplateList>();
    }
append() [1/2]
virtual void TemplateList::append (const TemplateVariant & v) [inline], [virtual]
Appends element v to the end of the list
Definition at line 296 of file template.cpp.
    {
      m_elems.push_back(v);
    }
References m_elems.
append() [2/2]
virtual void TemplateList::append (const TemplateVariant & v) [inline], [virtual]
Appends element v to the end of the list
Definition at line 296 of file template.cpp.
    {
      m_elems.push_back(v);
    }
References m_elems.
at() [1/2]
virtual TemplateVariant TemplateList::at (size_t index) const [inline], [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 280 of file template.cpp.
    {
      return index < m_elems.size() ? m_elems[static_cast<int>(index)] : TemplateVariant();
    }
References m_elems.
at() [2/2]
virtual TemplateVariant TemplateList::at (size_t index) const [inline], [virtual]
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 280 of file template.cpp.
    {
      return index < m_elems.size() ? m_elems[static_cast<int>(index)] : TemplateVariant();
    }
References m_elems.
count() [1/2]
virtual size_t TemplateList::count () const [inline], [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Definition at line 276 of file template.cpp.
    {
      return m_elems.size();
    }
References m_elems.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
count() [2/2]
virtual size_t TemplateList::count () const [inline], [virtual]
Returns the number of elements in the list
Implements TemplateListIntf.
Definition at line 276 of file template.cpp.
    {
      return m_elems.size();
    }
References m_elems.
Referenced by runtests.TestManager::__init__(), and runtests.TestManager::ok().
createIterator() [1/2]
virtual TemplateListIntf::ConstIteratorPtr TemplateList::createIterator () const [inline], [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 284 of file template.cpp.
    {
      return std::make_unique< TemplateListGenericConstIterator<TemplateList> >(*this);
    }
createIterator() [2/2]
virtual TemplateListIntf::ConstIteratorPtr TemplateList::createIterator () const [inline], [virtual]
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 284 of file template.cpp.
    {
      return std::make_unique< TemplateListGenericConstIterator<TemplateList> >(*this);
    }
insertAt() [1/2]
void TemplateList::insertAt (size_t index, TemplateListPtr list) [inline]
Definition at line 309 of file template.cpp.
    {
      auto it = m_elems.begin()+index;
      m_elems.insert(it,list->m_elems.begin(),list->m_elems.end());
    }
References m_elems.
insertAt() [2/2]
void TemplateList::insertAt (size_t index, TemplateListPtr list) [inline]
Definition at line 309 of file template.cpp.
    {
      auto it = m_elems.begin()+index;
      m_elems.insert(it,list->m_elems.begin(),list->m_elems.end());
    }
References m_elems.
removeAt() [1/2]
void TemplateList::removeAt (size_t index) [inline]
Definition at line 301 of file template.cpp.
    {
      if (index<m_elems.size())
      {
        m_elems.erase(m_elems.begin()+index);
      }
    }
References m_elems.
removeAt() [2/2]
void TemplateList::removeAt (size_t index) [inline]
Definition at line 301 of file template.cpp.
    {
      if (index<m_elems.size())
      {
        m_elems.erase(m_elems.begin()+index);
      }
    }
References m_elems.
Member Data Documentation
m_elems
TemplateVariantList TemplateList::m_elems [private]
Definition at line 321 of file template.cpp.
Referenced by append(), at(), count(), insertAt(), and removeAt().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp