ClassDef Class Reference
#include <classdef.h>
Public Types
enum CompoundType {
Class
, Struct
, Union
, Interface
,
Protocol
, Category
, Exception
, Service
,
Singleton
, Class
, Struct
, Union
,
Interface
, Protocol
, Category
, Exception
,
Service
, Singleton
 }
enum CompoundType {
Class
, Struct
, Union
, Interface
,
Protocol
, Category
, Exception
, Service
,
Singleton
, Class
, Struct
, Union
,
Interface
, Protocol
, Category
, Exception
,
Service
, Singleton
 }
Public Member Functions
virtual DefType definitionType () const =0
virtual QCString getOutputFileBase () const =0
virtual QCString getInstanceOutputFileBase () const =0
virtual QCString getSourceFileBase () const =0
virtual QCString getReference () const =0
virtual bool isReference () const =0
virtual bool isLocal () const =0
virtual ClassLinkedRefMap getClasses () const =0
virtual bool hasDocumentation () const =0
virtual bool hasDetailedDescription () const =0
virtual QCString collaborationGraphFileName () const =0
virtual QCString inheritanceGraphFileName () const =0
virtual QCString displayName (bool includeScope=TRUE) const =0
virtual CompoundType compoundType () const =0
virtual QCString compoundTypeString () const =0
virtual const BaseClassList & baseClasses () const =0
virtual void updateBaseClasses (const BaseClassList &bcd)=0
virtual const BaseClassList & subClasses () const =0
virtual void updateSubClasses (const BaseClassList &bcd)=0
virtual const MemberNameInfoLinkedMap & memberNameInfoLinkedMap () const =0
virtual Protection protection () const =0
virtual bool isLinkableInProject () const =0
virtual bool isLinkable () const =0
virtual bool isVisibleInHierarchy () const =0
virtual bool visibleInParentsDeclList () const =0
virtual const ArgumentList & templateArguments () const =0
virtual FileDef * getFileDef () const =0
virtual const MemberDef * getMemberByName (const QCString &) const =0
virtual int isBaseClass (const ClassDef *bcd, bool followInstances) const =0
virtual bool isSubClass (ClassDef *bcd, int level=0) const =0
virtual bool isAccessibleMember (const MemberDef *md) const =0
virtual const TemplateInstanceList & getTemplateInstances () const =0
virtual const ClassDef * templateMaster () const =0
virtual bool isTemplate () const =0
virtual const IncludeInfo * includeInfo () const =0
virtual const UsesClassList & usedImplementationClasses () const =0
virtual const UsesClassList & usedByImplementationClasses () const =0
virtual const ConstraintClassList & templateTypeConstraints () const =0
virtual bool isTemplateArgument () const =0
virtual const Definition * findInnerCompound (const QCString &name) const =0
virtual ArgumentLists getTemplateParameterLists () const =0
virtual QCString qualifiedNameWithTemplateParameters (const ArgumentLists *actualParams=0, uint *actualParamIndex=0) const =0
virtual bool isAbstract () const =0
virtual bool isObjectiveC () const =0
virtual bool isFortran () const =0
virtual bool isCSharp () const =0
virtual bool isFinal () const =0
virtual bool isSealed () const =0
virtual bool isPublished () const =0
virtual bool isExtension () const =0
virtual bool isForwardDeclared () const =0
virtual bool isInterface () const =0
virtual ClassDef * categoryOf () const =0
virtual QCString className () const =0
virtual MemberList * getMemberList (MemberListType lt) const =0
virtual const MemberLists & getMemberLists () const =0
virtual const MemberGroupList & getMemberGroups () const =0
virtual const TemplateNameMap & getTemplateBaseClassNames () const =0
virtual bool isUsedOnly () const =0
virtual QCString anchor () const =0
virtual bool isEmbeddedInOuterScope () const =0
virtual bool isSimple () const =0
virtual const ClassDef * tagLessReference () const =0
virtual const MemberDef * isSmartPointer () const =0
virtual bool isJavaEnum () const =0
virtual QCString title () const =0
virtual QCString generatedFromFiles () const =0
virtual const FileList & usedFiles () const =0
virtual const ArgumentList & typeConstraints () const =0
virtual const ExampleList & getExamples () const =0
virtual bool hasExamples () const =0
virtual QCString getMemberListFileName () const =0
virtual bool subGrouping () const =0
virtual bool isSliceLocal () const =0
virtual bool hasNonReferenceSuperClass () const =0
virtual QCString requiresClause () const =0
virtual int countMembersIncludingGrouped (MemberListType lt, const ClassDef *inheritedFrom, bool additional) const =0
virtual int countInheritanceNodes () const =0
virtual int countMemberDeclarations (MemberListType lt, const ClassDef *inheritedFrom, int lt2, bool invert, bool showAlways, ClassDefSet &visitedClasses) const =0
virtual ClassDef * insertTemplateInstance (const QCString &fileName, int startLine, int startColumn, const QCString &templSpec, bool &freshInstance) const =0
virtual void writeDeclarationLink (OutputList &ol, bool &found, const QCString &header, bool localNames) const =0
virtual DefType definitionType () const =0
virtual QCString getOutputFileBase () const =0
virtual QCString getInstanceOutputFileBase () const =0
virtual QCString getSourceFileBase () const =0
virtual QCString getReference () const =0
virtual bool isReference () const =0
virtual bool isLocal () const =0
virtual ClassLinkedRefMap getClasses () const =0
virtual bool hasDocumentation () const =0
virtual bool hasDetailedDescription () const =0
virtual QCString collaborationGraphFileName () const =0
virtual QCString inheritanceGraphFileName () const =0
virtual QCString displayName (bool includeScope=TRUE) const =0
virtual CompoundType compoundType () const =0
virtual QCString compoundTypeString () const =0
virtual const BaseClassList & baseClasses () const =0
virtual void updateBaseClasses (const BaseClassList &bcd)=0
virtual const BaseClassList & subClasses () const =0
virtual void updateSubClasses (const BaseClassList &bcd)=0
virtual const MemberNameInfoLinkedMap & memberNameInfoLinkedMap () const =0
virtual Protection protection () const =0
virtual bool isLinkableInProject () const =0
virtual bool isLinkable () const =0
virtual bool isVisibleInHierarchy () const =0
virtual bool visibleInParentsDeclList () const =0
virtual const ArgumentList & templateArguments () const =0
virtual FileDef * getFileDef () const =0
virtual const MemberDef * getMemberByName (const QCString &) const =0
virtual int isBaseClass (const ClassDef *bcd, bool followInstances) const =0
virtual bool isSubClass (ClassDef *bcd, int level=0) const =0
virtual bool isAccessibleMember (const MemberDef *md) const =0
virtual const TemplateInstanceList & getTemplateInstances () const =0
virtual const ClassDef * templateMaster () const =0
virtual bool isTemplate () const =0
virtual const IncludeInfo * includeInfo () const =0
virtual const UsesClassList & usedImplementationClasses () const =0
virtual const UsesClassList & usedByImplementationClasses () const =0
virtual const ConstraintClassList & templateTypeConstraints () const =0
virtual bool isTemplateArgument () const =0
virtual const Definition * findInnerCompound (const QCString &name) const =0
virtual ArgumentLists getTemplateParameterLists () const =0
virtual QCString qualifiedNameWithTemplateParameters (const ArgumentLists *actualParams=0, uint *actualParamIndex=0) const =0
virtual bool isAbstract () const =0
virtual bool isObjectiveC () const =0
virtual bool isFortran () const =0
virtual bool isCSharp () const =0
virtual bool isFinal () const =0
virtual bool isSealed () const =0
virtual bool isPublished () const =0
virtual bool isExtension () const =0
virtual bool isForwardDeclared () const =0
virtual bool isInterface () const =0
virtual ClassDef * categoryOf () const =0
virtual QCString className () const =0
virtual MemberList * getMemberList (MemberListType lt) const =0
virtual const MemberLists & getMemberLists () const =0
virtual const MemberGroupList & getMemberGroups () const =0
virtual const TemplateNameMap & getTemplateBaseClassNames () const =0
virtual bool isUsedOnly () const =0
virtual QCString anchor () const =0
virtual bool isEmbeddedInOuterScope () const =0
virtual bool isSimple () const =0
virtual const ClassDef * tagLessReference () const =0
virtual const MemberDef * isSmartPointer () const =0
virtual bool isJavaEnum () const =0
virtual QCString title () const =0
virtual QCString generatedFromFiles () const =0
virtual const FileList & usedFiles () const =0
virtual const ArgumentList & typeConstraints () const =0
virtual const ExampleList & getExamples () const =0
virtual bool hasExamples () const =0
virtual QCString getMemberListFileName () const =0
virtual bool subGrouping () const =0
virtual bool isSliceLocal () const =0
virtual bool hasNonReferenceSuperClass () const =0
virtual QCString requiresClause () const =0
virtual int countMembersIncludingGrouped (MemberListType lt, const ClassDef *inheritedFrom, bool additional) const =0
virtual int countInheritanceNodes () const =0
virtual int countMemberDeclarations (MemberListType lt, const ClassDef *inheritedFrom, int lt2, bool invert, bool showAlways, ClassDefSet &visitedClasses) const =0
virtual ClassDef * insertTemplateInstance (const QCString &fileName, int startLine, int startColumn, const QCString &templSpec, bool &freshInstance) const =0
virtual void writeDeclarationLink (OutputList &ol, bool &found, const QCString &header, bool localNames) const =0
Detailed Description
A abstract class representing of a compound symbol.
A compound can be a class, struct, union, interface, service, singleton, or exception.
Definition at line 103 of file classdef.h.
Member Enumeration Documentation
CompoundType [1/2]
enum ClassDef::CompoundType
The various compound types
Enumerator
Class
Struct
Union
Interface
Protocol
Category
Exception
Service
Singleton
Class
Struct
Union
Interface
Protocol
Category
Exception
Service
Singleton
Definition at line 107 of file classdef.h.
                      { Class, //=Entry::CLASS_SEC,
                        Struct, //=Entry::STRUCT_SEC,
                        Union, //=Entry::UNION_SEC,
                        Interface, //=Entry::INTERFACE_SEC,
                        Protocol, //=Entry::PROTOCOL_SEC,
                        Category, //=Entry::CATEGORY_SEC,
                        Exception, //=Entry::EXCEPTION_SEC
                        Service, //=Entry::CLASS_SEC
                        Singleton, //=Entry::CLASS_SEC
                      };
CompoundType [2/2]
enum ClassDef::CompoundType
The various compound types
Enumerator
Class
Struct
Union
Interface
Protocol
Category
Exception
Service
Singleton
Class
Struct
Union
Interface
Protocol
Category
Exception
Service
Singleton
Definition at line 107 of file classdef.h.
                      { Class, //=Entry::CLASS_SEC,
                        Struct, //=Entry::STRUCT_SEC,
                        Union, //=Entry::UNION_SEC,
                        Interface, //=Entry::INTERFACE_SEC,
                        Protocol, //=Entry::PROTOCOL_SEC,
                        Category, //=Entry::CATEGORY_SEC,
                        Exception, //=Entry::EXCEPTION_SEC
                        Service, //=Entry::CLASS_SEC
                        Singleton, //=Entry::CLASS_SEC
                      };
Member Function Documentation
anchor() [1/2]
virtual QCString ClassDef::anchor () const [pure virtual]
Returns the anchor within a page where this item can be found
Implements Definition.
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), MemberDefImpl::_writeReimplements(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), DotClassGraph::addClass(), DotGfxHierarchyTable::addHierarchy(), addToIndices(), ClassDefAliasImpl::anchor(), DotClassGraph::DotClassGraph(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), DocParser::handleLinkedWord(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), if(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), resolveLink(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), doxmlparser.compound.docTocItemType::set_anchor(), writeClassTree(), writeClassTreeToOutput(), MemberList::writeDeclarations(), ClassDefImpl::writeInheritanceGraph(), writeMapArea(), MemberDefImpl::writeMemberDocSimple(), and ClassDefImpl::writeMemberList().
anchor() [2/2]
virtual QCString ClassDef::anchor () const [pure virtual]
Returns the anchor within a page where this item can be found
Implements Definition.
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docHeadingType::__init__(), doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docRefTextType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docTitleType::__init__(), doxmlparser.compound.docSummaryType::__init__(), doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docTitleType::add_anchor(), doxmlparser.compound.docSummaryType::add_anchor(), doxmlparser.compound.docParaType::add_anchor(), doxmlparser.compound.docMarkupType::add_anchor(), doxmlparser.compound.docURLLink::add_anchor(), doxmlparser.compound.docRefTextType::add_anchor(), doxmlparser.compound.docCaptionType::add_anchor(), doxmlparser.compound.docHeadingType::add_anchor(), doxmlparser.compound.docImageType::add_anchor(), doxmlparser.compound.docDotMscType::add_anchor(), doxmlparser.compound.docImageFileType::add_anchor(), doxmlparser.compound.docPlantumlType::add_anchor(), doxmlparser.compound.docTocItemType::add_anchor(), doxmlparser.compound.docCaptionType::exportChildren(), doxmlparser.compound.docDotMscType::exportChildren(), doxmlparser.compound.docHeadingType::exportChildren(), doxmlparser.compound.docImageFileType::exportChildren(), doxmlparser.compound.docImageType::exportChildren(), doxmlparser.compound.docPlantumlType::exportChildren(), doxmlparser.compound.docRefTextType::exportChildren(), doxmlparser.compound.docTocItemType::exportChildren(), doxmlparser.compound.docURLLink::exportChildren(), doxmlparser.compound.docTitleType::get_anchor(), doxmlparser.compound.docSummaryType::get_anchor(), doxmlparser.compound.docParaType::get_anchor(), doxmlparser.compound.docMarkupType::get_anchor(), doxmlparser.compound.docURLLink::get_anchor(), doxmlparser.compound.docRefTextType::get_anchor(), doxmlparser.compound.docCaptionType::get_anchor(), doxmlparser.compound.docHeadingType::get_anchor(), doxmlparser.compound.docImageType::get_anchor(), doxmlparser.compound.docDotMscType::get_anchor(), doxmlparser.compound.docImageFileType::get_anchor(), doxmlparser.compound.docPlantumlType::get_anchor(), doxmlparser.compound.docTocItemType::get_anchor(), doxmlparser.compound.docTitleType::hasContent_(), doxmlparser.compound.docSummaryType::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docURLLink::hasContent_(), doxmlparser.compound.docRefTextType::hasContent_(), doxmlparser.compound.docCaptionType::hasContent_(), doxmlparser.compound.docHeadingType::hasContent_(), doxmlparser.compound.docImageType::hasContent_(), doxmlparser.compound.docDotMscType::hasContent_(), doxmlparser.compound.docImageFileType::hasContent_(), doxmlparser.compound.docPlantumlType::hasContent_(), doxmlparser.compound.docTocItemType::hasContent_(), doxmlparser.compound.docTitleType::insert_anchor_at(), doxmlparser.compound.docSummaryType::insert_anchor_at(), doxmlparser.compound.docParaType::insert_anchor_at(), doxmlparser.compound.docMarkupType::insert_anchor_at(), doxmlparser.compound.docURLLink::insert_anchor_at(), doxmlparser.compound.docRefTextType::insert_anchor_at(), doxmlparser.compound.docCaptionType::insert_anchor_at(), doxmlparser.compound.docHeadingType::insert_anchor_at(), doxmlparser.compound.docImageType::insert_anchor_at(), doxmlparser.compound.docDotMscType::insert_anchor_at(), doxmlparser.compound.docImageFileType::insert_anchor_at(), doxmlparser.compound.docPlantumlType::insert_anchor_at(), doxmlparser.compound.docTocItemType::insert_anchor_at(), doxmlparser.compound.docTitleType::replace_anchor_at(), doxmlparser.compound.docSummaryType::replace_anchor_at(), doxmlparser.compound.docParaType::replace_anchor_at(), doxmlparser.compound.docMarkupType::replace_anchor_at(), doxmlparser.compound.docURLLink::replace_anchor_at(), doxmlparser.compound.docRefTextType::replace_anchor_at(), doxmlparser.compound.docCaptionType::replace_anchor_at(), doxmlparser.compound.docHeadingType::replace_anchor_at(), doxmlparser.compound.docImageType::replace_anchor_at(), doxmlparser.compound.docDotMscType::replace_anchor_at(), doxmlparser.compound.docImageFileType::replace_anchor_at(), doxmlparser.compound.docPlantumlType::replace_anchor_at(), doxmlparser.compound.docTocItemType::replace_anchor_at(), doxmlparser.compound.docTitleType::set_anchor(), doxmlparser.compound.docSummaryType::set_anchor(), doxmlparser.compound.docParaType::set_anchor(), doxmlparser.compound.docMarkupType::set_anchor(), doxmlparser.compound.docURLLink::set_anchor(), doxmlparser.compound.docRefTextType::set_anchor(), doxmlparser.compound.docCaptionType::set_anchor(), doxmlparser.compound.docHeadingType::set_anchor(), doxmlparser.compound.docImageType::set_anchor(), doxmlparser.compound.docDotMscType::set_anchor(), doxmlparser.compound.docImageFileType::set_anchor(), doxmlparser.compound.docPlantumlType::set_anchor(), and doxmlparser.compound.docTocItemType::set_anchor().
baseClasses() [1/2]
virtual const BaseClassList & ClassDef::baseClasses () const [pure virtual]
Returns the list of base classes from which this class directly inherits.
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by VhdlDocGen::addBaseClass(), NestingNodeContext::Private::addClasses(), NestingContext::Private::addDerivedClasses(), DotGfxHierarchyTable::addHierarchy(), ClassDefAliasImpl::baseClasses(), buildCompleteMemberLists(), DotClassGraph::buildGraph(), classHasVisibleChildren(), classInformation(), classInheritedProtectionLevel(), computeMemberRelations(), ClassContext::Private::createInheritsList(), InheritedMemberInfoListContext::Private::findInheritedMembers(), generateDEFForClass(), PerlModGenerator::generatePerlModForClass(), generateXMLForClass(), hasVisibleRoot(), DiagramRow::insertClass(), ClassDefImpl::mergeCategory(), minClassDistance(), trimBaseClassScope(), writeClassTreeToOutput(), and writeObjCMethodCall().
baseClasses() [2/2]
virtual const BaseClassList & ClassDef::baseClasses () const [pure virtual]
Returns the list of base classes from which this class directly inherits.
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
categoryOf() [1/2]
virtual ClassDef * ClassDef::categoryOf () const [pure virtual]
Returns the class of which this is a category (Objective-C only)
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by MemberDefImpl::_writeCategoryRelation(), ClassDefAliasImpl::categoryOf(), classInheritedProtectionLevel(), ClassContext::Private::createCategoryOf(), minClassDistance(), and writeObjCMethodCall().
categoryOf() [2/2]
virtual ClassDef * ClassDef::categoryOf () const [pure virtual]
Returns the class of which this is a category (Objective-C only)
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
className() [1/2]
virtual QCString ClassDef::className () const [pure virtual]
Returns the name of the class including outer classes, but not including namespaces.
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by ClassDefAliasImpl::className(), VhdlDocGen::findAllArchitectures(), VhdlDocGen::getClassName(), makeDisplayName(), makeQualifiedNameWithTemplateParameters(), FileDefImpl::sortMemberLists(), GroupDefImpl::sortMemberLists(), NamespaceDefImpl::sortMemberLists(), and VhdlDocGen::writeInlineClassLink().
className() [2/2]
virtual QCString ClassDef::className () const [pure virtual]
Returns the name of the class including outer classes, but not including namespaces.
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
collaborationGraphFileName() [1/2]
virtual QCString ClassDef::collaborationGraphFileName () const [pure virtual]
returns the file name to use for the collaboration graph
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by ClassDefAliasImpl::collaborationGraphFileName(), and DotClassGraph::DotClassGraph().
collaborationGraphFileName() [2/2]
virtual QCString ClassDef::collaborationGraphFileName () const [pure virtual]
returns the file name to use for the collaboration graph
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
compoundType() [1/2]
virtual CompoundType ClassDef::compoundType () const [pure virtual]
Returns the type of compound this is, i.e. class/struct/union/..
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by MemberDefImpl::_writeReimplements(), DocSets::addIndexItem(), compoundIcon(), ClassDefAliasImpl::compoundType(), computeMemberRelations(), MemberContext::Private::createImplementedBy(), MemberContext::Private::createImplements(), MemberContext::Private::createReimplementedBy(), MemberContext::Private::createReimplements(), createTagLessInstance(), generateLink(), FileDefImpl::insertClass(), NamespaceDefImpl::insertClass(), makeDisplayName(), ClassDefImpl::mergeMembers(), and writeClassTree().
compoundType() [2/2]
virtual CompoundType ClassDef::compoundType () const [pure virtual]
Returns the type of compound this is, i.e. class/struct/union/..
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
compoundTypeString() [1/2]
virtual QCString ClassDef::compoundTypeString () const [pure virtual]
Returns the type of compound as a string
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by ClassContext::Private::compoundType(), ClassDefAliasImpl::compoundTypeString(), generateDEFForClass(), PerlModGenerator::generatePerlModForClass(), generateXMLForClass(), lookupSymbol(), SearchIndex::setCurrentDoc(), and MemberDefImpl::warnIfUndocumented().
compoundTypeString() [2/2]
virtual QCString ClassDef::compoundTypeString () const [pure virtual]
Returns the type of compound as a string
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
countInheritanceNodes() [1/2]
virtual int ClassDef::countInheritanceNodes () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by ClassDefAliasImpl::countInheritanceNodes(), and ClassContext::Private::createNumInheritanceNodes().
countInheritanceNodes() [2/2]
virtual int ClassDef::countInheritanceNodes () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
countMemberDeclarations() [1/2]
virtual int ClassDef::countMemberDeclarations (MemberListType lt, const ClassDef * inheritedFrom, int lt2, bool invert, bool showAlways, ClassDefSet & visitedClasses) const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by ClassDefImpl::countInheritedDecMembers(), and ClassDefAliasImpl::countMemberDeclarations().
countMemberDeclarations() [2/2]
virtual int ClassDef::countMemberDeclarations (MemberListType lt, const ClassDef * inheritedFrom, int lt2, bool invert, bool showAlways, ClassDefSet & visitedClasses) const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
countMembersIncludingGrouped() [1/2]
virtual int ClassDef::countMembersIncludingGrouped (MemberListType lt, const ClassDef * inheritedFrom, bool additional) const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by InheritedMemberInfoListContext::Private::addInheritedMembers(), InheritedMemberInfoListContext::addMemberList(), ClassDefAliasImpl::countMembersIncludingGrouped(), and MemberList::writeDeclarations().
countMembersIncludingGrouped() [2/2]
virtual int ClassDef::countMembersIncludingGrouped (MemberListType lt, const ClassDef * inheritedFrom, bool additional) const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
definitionType() [1/2]
virtual DefType ClassDef::definitionType () const [pure virtual]
Used for RTTI, this is a class
Implements Definition.
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by SymbolResolver::Private::newResolveTypedef().
definitionType() [2/2]
virtual DefType ClassDef::definitionType () const [pure virtual]
Used for RTTI, this is a class
Implements Definition.
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
displayName() [1/2]
virtual QCString ClassDef::displayName (bool includeScope = TRUE) const [pure virtual]
Returns the name as it is appears in the documentation
Implements Definition.
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by MemberDefImpl::_writeCategoryRelation(), MemberDefImpl::_writeReimplementedBy(), MemberDefImpl::_writeReimplements(), DotClassGraph::addClass(), DotGfxHierarchyTable::addHierarchy(), addToIndices(), DotClassGraph::DotClassGraph(), MemberDefImpl::getScopeString(), MemberContext::Private::handleNameWithContextFor(), ClassContext::Private::inheritanceDiagram(), InheritanceListContext::InheritanceListContext(), DiagramItem::label(), writeClassLinkForMember(), writeClassTree(), writeClassTreeToOutput(), MemberList::writeDeclarations(), MemberDefImpl::writeDocumentation(), ClassDefImpl::writeInheritanceGraph(), MemberDefImpl::writeLink(), writeMapArea(), and ClassDefImpl::writeMemberList().
displayName() [2/2]
virtual QCString ClassDef::displayName (bool includeScope = TRUE) const [pure virtual]
Returns the name as it is appears in the documentation
Implements Definition.
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
findInnerCompound() [1/2]
virtual const Definition * ClassDef::findInnerCompound (const QCString & name) const [pure virtual]
Returns the definition of a nested compound if available, or 0 otherwise.
Parameters
name The name of the nested compound
Implements Definition.
Implemented in ClassDefImpl, ClassDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionAliasMixin< ClassDef >, ClassDefImpl, ClassDefAliasImpl, DefinitionMixin< ClassDefMutable >, and DefinitionAliasMixin< ClassDef >.
Referenced by ClassDefAliasImpl::findInnerCompound(), and generateClassMemberLink().
findInnerCompound() [2/2]
virtual const Definition * ClassDef::findInnerCompound (const QCString & name) const [pure virtual]
Returns the definition of a nested compound if available, or 0 otherwise.
Parameters
name The name of the nested compound
Implements Definition.
Implemented in ClassDefImpl, ClassDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionAliasMixin< ClassDef >, ClassDefImpl, ClassDefAliasImpl, DefinitionMixin< ClassDefMutable >, and DefinitionAliasMixin< ClassDef >.
generatedFromFiles() [1/2]
virtual QCString ClassDef::generatedFromFiles () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by ClassDefAliasImpl::generatedFromFiles(), and ClassContext::Private::generatedFromFiles().
generatedFromFiles() [2/2]
virtual QCString ClassDef::generatedFromFiles () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
getClasses() [1/2]
virtual ClassLinkedRefMap ClassDef::getClasses () const [pure virtual]
returns the classes nested into this class
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by addClassAndNestedClasses(), NestingNodeContext::Private::addClasses(), ClassDefImpl::addMembersToTemplateInstance(), ClassContext::Private::createClasses(), ClassContext::Private::createInnerClasses(), distributeClassGroupRelations(), findTagLessClasses(), PerlModGenerator::generatePerlModForClass(), generateXMLForClass(), ClassDefAliasImpl::getClasses(), processTagLessClasses(), and writeClassTree().
getClasses() [2/2]
virtual ClassLinkedRefMap ClassDef::getClasses () const [pure virtual]
returns the classes nested into this class
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
getExamples() [1/2]
virtual const ExampleList & ClassDef::getExamples () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by ClassContext::Private::createExamples(), and ClassDefAliasImpl::getExamples().
getExamples() [2/2]
virtual const ExampleList & ClassDef::getExamples () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
getFileDef() [1/2]
virtual FileDef * ClassDef::getFileDef () const [pure virtual]
Returns the namespace this compound is in, or 0 if it has a global scope. Returns the file in which this compound's definition can be found. Should not return 0 (but it might be a good idea to check anyway).
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by addInstance(), cModule(), createTagLessInstance(), findClassRelation(), findClassWithinClassContext(), findUsedClassesForClass(), generateClassOrGlobalLink(), generateXMLForClass(), getDefsOld(), ClassDefAliasImpl::getFileDef(), SymbolResolver::Private::isAccessibleFrom(), referenceTo(), and writeTemplateList().
getFileDef() [2/2]
virtual FileDef * ClassDef::getFileDef () const [pure virtual]
Returns the namespace this compound is in, or 0 if it has a global scope. Returns the file in which this compound's definition can be found. Should not return 0 (but it might be a good idea to check anyway).
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
getInstanceOutputFileBase() [1/2]
virtual QCString ClassDef::getInstanceOutputFileBase () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by ClassDefAliasImpl::getInstanceOutputFileBase().
getInstanceOutputFileBase() [2/2]
virtual QCString ClassDef::getInstanceOutputFileBase () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
getMemberByName() [1/2]
virtual const MemberDef * ClassDef::getMemberByName (const QCString &) const [pure virtual]
Returns the member with the given name
Implemented in ClassDefImpl, ClassDefImpl, ClassDefAliasImpl, and ClassDefAliasImpl.
Referenced by SymbolResolver::Private::followPath(), generateClassMemberLink(), generateClassOrGlobalLink(), ClassDefAliasImpl::getMemberByName(), setCallContextForVar(), and writeObjCMethodCall().
getMemberByName() [2/2]
virtual const MemberDef * ClassDef::getMemberByName (const QCString &) const [pure virtual]
Returns the member with the given name
Implemented in ClassDefImpl, ClassDefImpl, ClassDefAliasImpl, and ClassDefAliasImpl.
getMemberGroups() [1/2]
virtual const MemberGroupList & ClassDef::getMemberGroups () const [pure virtual]
Returns the member groups defined for this class
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by InheritedMemberInfoListContext::Private::addMemberGroupsOfClass(), ClassContext::Private::createMemberGroups(), PerlModGenerator::generatePerlModForClass(), generateXMLForClass(), ClassDefAliasImpl::getMemberGroups(), and DotNode::writeLabel().
getMemberGroups() [2/2]
virtual const MemberGroupList & ClassDef::getMemberGroups () const [pure virtual]
Returns the member groups defined for this class
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
getMemberList() [1/2]
virtual MemberList * ClassDef::getMemberList (MemberListType lt) const [pure virtual]
Returns the members in the list identified by lt
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by InheritedMemberInfoListContext::Private::addInheritedMembers(), NestingNodeContext::Private::addMembers(), ClassContext::Private::addMembers(), cModule(), ClassContext::Private::createMemberList(), createTagLessInstance(), VhdlDocGen::findAllPackages(), VhdlDocGen::findFunction(), VhdlDocGen::findMemberDef(), generateDEFForClass(), PerlModGenerator::generatePerlModForClass(), ClassDefAliasImpl::getMemberList(), getPorts(), listAllMembers(), processTagLessClasses(), and DotNode::writeLabel().
getMemberList() [2/2]
virtual MemberList * ClassDef::getMemberList (MemberListType lt) const [pure virtual]
Returns the members in the list identified by lt
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
getMemberListFileName() [1/2]
virtual QCString ClassDef::getMemberListFileName () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by ClassContext::Private::allMembersFileName(), and ClassDefAliasImpl::getMemberListFileName().
getMemberListFileName() [2/2]
virtual QCString ClassDef::getMemberListFileName () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
getMemberLists() [1/2]
virtual const MemberLists & ClassDef::getMemberLists () const [pure virtual]
Returns the list containing the list of members sorted per type
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by generateDEFForClass(), generateXMLForClass(), and ClassDefAliasImpl::getMemberLists().
getMemberLists() [2/2]
virtual const MemberLists & ClassDef::getMemberLists () const [pure virtual]
Returns the list containing the list of members sorted per type
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
getOutputFileBase() [1/2]
virtual QCString ClassDef::getOutputFileBase () const [pure virtual]
Returns the unique base name (without extension) of the class's file on disk
Implements Definition.
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by MemberDefImpl::_writeReimplements(), DotClassGraph::addClass(), DotGfxHierarchyTable::addHierarchy(), addInstance(), ClassDefImpl::anchor(), classOutputFileBase(), ClassContext::Private::collaborationDiagram(), DotClassGraph::DotClassGraph(), DiagramItem::fileName(), generateDEFForClass(), ClassDefImpl::getOutputFileBase(), ClassDefAliasImpl::getOutputFileBase(), MemberDefImpl::getOutputFileBase(), DocParser::handleLinkedWord(), InheritedMemberInfoContext::Private::id(), if(), ClassContext::Private::inheritanceDiagram(), writeClassToDot(), writeClassTree(), writeClassTreeToOutput(), MemberList::writeDeclarations(), ClassDefImpl::writeInheritanceGraph(), writeMapArea(), MemberDefImpl::writeMemberDocSimple(), ClassDefImpl::writeMemberList(), VhdlDocGen::writeVHDLDeclaration(), and VhdlDocGen::writeVhdlLink().
getOutputFileBase() [2/2]
virtual QCString ClassDef::getOutputFileBase () const [pure virtual]
Returns the unique base name (without extension) of the class's file on disk
Implements Definition.
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
getReference() [1/2]
virtual QCString ClassDef::getReference () const [pure virtual]
If this class originated from a tagfile, this will return the tag file reference
Implements Definition.
Implemented in ClassDefImpl, ClassDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionAliasMixin< ClassDef >, ClassDefImpl, ClassDefAliasImpl, DefinitionMixin< ClassDefMutable >, and DefinitionAliasMixin< ClassDef >.
Referenced by MemberDefImpl::_writeReimplements(), DotClassGraph::addClass(), DotGfxHierarchyTable::addHierarchy(), DotClassGraph::DotClassGraph(), ClassDefImpl::getReference(), ClassDefAliasImpl::getReference(), MemberDefImpl::getReference(), DocParser::handleLinkedWord(), if(), writeClassTree(), writeClassTreeToOutput(), MemberList::writeDeclarations(), ClassDefImpl::writeInheritanceGraph(), writeMapArea(), MemberDefImpl::writeMemberDocSimple(), ClassDefImpl::writeMemberList(), VhdlDocGen::writeVHDLDeclaration(), and VhdlDocGen::writeVhdlLink().
getReference() [2/2]
virtual QCString ClassDef::getReference () const [pure virtual]
If this class originated from a tagfile, this will return the tag file reference
Implements Definition.
Implemented in ClassDefImpl, ClassDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionAliasMixin< ClassDef >, ClassDefImpl, ClassDefAliasImpl, DefinitionMixin< ClassDefMutable >, and DefinitionAliasMixin< ClassDef >.
getSourceFileBase() [1/2]
virtual QCString ClassDef::getSourceFileBase () const [pure virtual]
Returns the base name for the source code file
Implements Definition.
Implemented in ClassDefImpl, ClassDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionAliasMixin< ClassDef >, ClassDefImpl, ClassDefAliasImpl, DefinitionMixin< ClassDefMutable >, and DefinitionAliasMixin< ClassDef >.
Referenced by ClassDefImpl::getSourceFileBase(), and ClassDefAliasImpl::getSourceFileBase().
getSourceFileBase() [2/2]
virtual QCString ClassDef::getSourceFileBase () const [pure virtual]
Returns the base name for the source code file
Implements Definition.
Implemented in ClassDefImpl, ClassDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionAliasMixin< ClassDef >, ClassDefImpl, ClassDefAliasImpl, DefinitionMixin< ClassDefMutable >, and DefinitionAliasMixin< ClassDef >.
getTemplateBaseClassNames() [1/2]
virtual const TemplateNameMap & ClassDef::getTemplateBaseClassNames () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by computeTemplateClassRelations(), and ClassDefAliasImpl::getTemplateBaseClassNames().
getTemplateBaseClassNames() [2/2]
virtual const TemplateNameMap & ClassDef::getTemplateBaseClassNames () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
getTemplateInstances() [1/2]
virtual const TemplateInstanceList & ClassDef::getTemplateInstances () const [pure virtual]
Returns a sorted dictionary with all template instances found for this template class. Returns 0 if not a template or no instances.
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by DotClassGraph::buildGraph(), computeTemplateClassRelations(), createTemplateInstanceMembers(), ClassDefAliasImpl::getTemplateInstances(), and hasNonReferenceSuperClassRec().
getTemplateInstances() [2/2]
virtual const TemplateInstanceList & ClassDef::getTemplateInstances () const [pure virtual]
Returns a sorted dictionary with all template instances found for this template class. Returns 0 if not a template or no instances.
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
getTemplateParameterLists() [1/2]
virtual ArgumentLists ClassDef::getTemplateParameterLists () const [pure virtual]
Returns the template parameter lists that form the template declaration of this class.
Example: template<class T> class TC {} = 0; will return a list with one ArgumentList containing one argument with type=`class` and name=`T`.
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by addMemberFunction(), MemberContext::Private::createTemplateDecls(), ClassDefAliasImpl::getTemplateParameterLists(), and MemberDefImpl::writeDocumentation().
getTemplateParameterLists() [2/2]
virtual ArgumentLists ClassDef::getTemplateParameterLists () const [pure virtual]
Returns the template parameter lists that form the template declaration of this class.
Example: template<class T> class TC {} = 0; will return a list with one ArgumentList containing one argument with type=`class` and name=`T`.
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
hasDetailedDescription() [1/2]
virtual bool ClassDef::hasDetailedDescription () const [pure virtual]
returns TRUE if this class has a non-empty detailed description
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by ClassDefAliasImpl::hasDetailedDescription(), and ClassContext::Private::hasDetails().
hasDetailedDescription() [2/2]
virtual bool ClassDef::hasDetailedDescription () const [pure virtual]
returns TRUE if this class has a non-empty detailed description
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
hasDocumentation() [1/2]
virtual bool ClassDef::hasDocumentation () const [pure virtual]
returns TRUE if this class has documentation
Implements Definition.
Implemented in ClassDefImpl, ClassDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionAliasMixin< ClassDef >, ClassDefImpl, ClassDefAliasImpl, DefinitionMixin< ClassDefMutable >, and DefinitionAliasMixin< ClassDef >.
Referenced by addClassToContext(), computeClassRelations(), ClassDefAliasImpl::hasDocumentation(), ClassDefImpl::isVisibleInHierarchy(), and DotNode::writeBox().
hasDocumentation() [2/2]
virtual bool ClassDef::hasDocumentation () const [pure virtual]
returns TRUE if this class has documentation
Implements Definition.
Implemented in ClassDefImpl, ClassDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionAliasMixin< ClassDef >, ClassDefImpl, ClassDefAliasImpl, DefinitionMixin< ClassDefMutable >, and DefinitionAliasMixin< ClassDef >.
hasExamples() [1/2]
virtual bool ClassDef::hasExamples () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by ClassContext::Private::createExamples(), and ClassDefAliasImpl::hasExamples().
hasExamples() [2/2]
virtual bool ClassDef::hasExamples () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
hasNonReferenceSuperClass() [1/2]
virtual bool ClassDef::hasNonReferenceSuperClass () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by ClassDefAliasImpl::hasNonReferenceSuperClass().
hasNonReferenceSuperClass() [2/2]
virtual bool ClassDef::hasNonReferenceSuperClass () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
includeInfo() [1/2]
virtual const IncludeInfo * ClassDef::includeInfo () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by DocSets::addIndexItem(), ClassContext::Private::createIncludeInfo(), PerlModGenerator::generatePerlModForClass(), generateXMLForClass(), and ClassDefAliasImpl::includeInfo().
includeInfo() [2/2]
virtual const IncludeInfo * ClassDef::includeInfo () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
inheritanceGraphFileName() [1/2]
virtual QCString ClassDef::inheritanceGraphFileName () const [pure virtual]
returns the file name to use for the inheritance graph
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by DotClassGraph::DotClassGraph(), and ClassDefAliasImpl::inheritanceGraphFileName().
inheritanceGraphFileName() [2/2]
virtual QCString ClassDef::inheritanceGraphFileName () const [pure virtual]
returns the file name to use for the inheritance graph
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
insertTemplateInstance() [1/2]
virtual ClassDef * ClassDef::insertTemplateInstance (const QCString & fileName, int startLine, int startColumn, const QCString & templSpec, bool & freshInstance) const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by findTemplateInstanceRelation(), and ClassDefAliasImpl::insertTemplateInstance().
insertTemplateInstance() [2/2]
virtual ClassDef * ClassDef::insertTemplateInstance (const QCString & fileName, int startLine, int startColumn, const QCString & templSpec, bool & freshInstance) const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
isAbstract() [1/2]
virtual bool ClassDef::isAbstract () const [pure virtual]
Returns TRUE if there is at least one pure virtual member in this class.
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by classInformation(), generateXMLForClass(), and ClassDefAliasImpl::isAbstract().
isAbstract() [2/2]
virtual bool ClassDef::isAbstract () const [pure virtual]
Returns TRUE if there is at least one pure virtual member in this class.
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
isAccessibleMember() [1/2]
virtual bool ClassDef::isAccessibleMember (const MemberDef * md) const [pure virtual]
returns TRUE iff md is a member of this class or of the the public/protected members of a base class
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by ClassDefAliasImpl::isAccessibleMember().
isAccessibleMember() [2/2]
virtual bool ClassDef::isAccessibleMember (const MemberDef * md) const [pure virtual]
returns TRUE iff md is a member of this class or of the the public/protected members of a base class
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
isBaseClass() [1/2]
virtual int ClassDef::isBaseClass (const ClassDef * bcd, bool followInstances) const [pure virtual]
Returns TRUE iff bcd is a direct or indirect base class of this class. This function will recursively traverse all branches of the inheritance tree.
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by addInstance(), computeMemberRelations(), findMemberLink(), SymbolResolver::Private::isAccessibleFrom(), ClassDefImpl::isBaseClass(), ClassDefAliasImpl::isBaseClass(), MemberDefImpl::isReimplementedBy(), VhdlDocGen::isSubClass(), and ClassDefImpl::mergeMembers().
isBaseClass() [2/2]
virtual int ClassDef::isBaseClass (const ClassDef * bcd, bool followInstances) const [pure virtual]
Returns TRUE iff bcd is a direct or indirect base class of this class. This function will recursively traverse all branches of the inheritance tree.
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
isCSharp() [1/2]
virtual bool ClassDef::isCSharp () const [pure virtual]
Returns TRUE if this class is implemented in C#
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by findClassRelation(), and ClassDefAliasImpl::isCSharp().
isCSharp() [2/2]
virtual bool ClassDef::isCSharp () const [pure virtual]
Returns TRUE if this class is implemented in C#
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
isEmbeddedInOuterScope() [1/2]
virtual bool ClassDef::isEmbeddedInOuterScope () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by addClassAndNestedClasses(), generateDocsForClassList(), generateNamespaceClassDocs(), and ClassDefAliasImpl::isEmbeddedInOuterScope().
isEmbeddedInOuterScope() [2/2]
virtual bool ClassDef::isEmbeddedInOuterScope () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
isExtension() [1/2]
virtual bool ClassDef::isExtension () const [pure virtual]
Returns TRUE if this class represents an Objective-C 2.0 extension (nameless category)
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by ClassDefAliasImpl::isExtension(), and ClassDefImpl::mergeCategory().
isExtension() [2/2]
virtual bool ClassDef::isExtension () const [pure virtual]
Returns TRUE if this class represents an Objective-C 2.0 extension (nameless category)
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
isFinal() [1/2]
virtual bool ClassDef::isFinal () const [pure virtual]
Returns TRUE if this class is marked as final
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by generateXMLForClass(), and ClassDefAliasImpl::isFinal().
isFinal() [2/2]
virtual bool ClassDef::isFinal () const [pure virtual]
Returns TRUE if this class is marked as final
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
isFortran() [1/2]
virtual bool ClassDef::isFortran () const [pure virtual]
Returns TRUE if this class is implemented in Fortran
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by ClassDefAliasImpl::isFortran().
isFortran() [2/2]
virtual bool ClassDef::isFortran () const [pure virtual]
Returns TRUE if this class is implemented in Fortran
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
isForwardDeclared() [1/2]
virtual bool ClassDef::isForwardDeclared () const [pure virtual]
Returns TRUE if this class represents a forward declaration of a template class
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by addClassToContext(), and ClassDefAliasImpl::isForwardDeclared().
isForwardDeclared() [2/2]
virtual bool ClassDef::isForwardDeclared () const [pure virtual]
Returns TRUE if this class represents a forward declaration of a template class
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
isInterface() [1/2]
virtual bool ClassDef::isInterface () const [pure virtual]
Returns TRUE if this class represents an interface
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by ClassDefAliasImpl::isInterface(), and ClassDefImpl::writeIncludeFilesForSlice().
isInterface() [2/2]
virtual bool ClassDef::isInterface () const [pure virtual]
Returns TRUE if this class represents an interface
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
isJavaEnum() [1/2]
virtual bool ClassDef::isJavaEnum () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by ClassDefAliasImpl::isJavaEnum(), and MemberList::writeSimpleDocumentation().
isJavaEnum() [2/2]
virtual bool ClassDef::isJavaEnum () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
isLinkable() [1/2]
virtual bool ClassDef::isLinkable () const [pure virtual]
return TRUE iff a link to this class is possible (either within this project, or as a cross-reference to another project).
Implements Definition.
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by MemberDefImpl::_countReimplementedBy(), MemberDefImpl::_isReimplements(), MemberDefImpl::_writeReimplementedBy(), MemberDefImpl::_writeReimplements(), DotClassGraph::addClass(), DotGfxHierarchyTable::addHierarchy(), addMemberToSearchIndex(), classVisibleInIndex(), computeMemberRelations(), ClassDefImpl::countInheritedDecMembers(), DotClassGraph::DotClassGraph(), TreeDiagram::drawBoxes(), InheritedMemberInfoListContext::Private::findInheritedMembers(), generateClassOrGlobalLink(), generateLink(), generateMemberLink(), getDefsOld(), getScopeDefs(), if(), MemberDefImpl::isDocumentedFriendClass(), ClassDefImpl::isLinkable(), ClassDefAliasImpl::isLinkable(), AllMembersListContext::Private::Private(), SymbolResolver::resolveClass(), writeClassTreeToOutput(), ClassDefImpl::writeInheritanceGraph(), ClassDefImpl::writeInheritedMemberDeclarations(), writeMapArea(), ClassDefImpl::writeMemberList(), writeObjCMethodCall(), and ClassDefImpl::writeTagFile().
isLinkable() [2/2]
virtual bool ClassDef::isLinkable () const [pure virtual]
return TRUE iff a link to this class is possible (either within this project, or as a cross-reference to another project).
Implements Definition.
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
isLinkableInProject() [1/2]
virtual bool ClassDef::isLinkableInProject () const [pure virtual]
returns TRUE iff a link is possible to this item within this project.
Implements Definition.
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by MemberDefImpl::_computeLinkableInProject(), MemberDefImpl::_writeReimplements(), addClassAndNestedClasses(), addClassMemberNameToIndex(), addSourceReferences(), addToIndices(), classVisibleInIndex(), ClassMembersIndexContext::Private::createMembersFiltered(), generateDocsForClassList(), generateNamespaceClassDocs(), generateNamespaceConceptDocs(), hasNonReferenceSuperClassRec(), if(), ClassDefImpl::isLinkableInProject(), ClassDefAliasImpl::isLinkableInProject(), namespaceHasNestedClass(), and writeTagFile().
isLinkableInProject() [2/2]
virtual bool ClassDef::isLinkableInProject () const [pure virtual]
returns TRUE iff a link is possible to this item within this project.
Implements Definition.
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
isLocal() [1/2]
virtual bool ClassDef::isLocal () const [pure virtual]
Returns TRUE if this is a local class definition, see EXTRACT_LOCAL_CLASSES
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by ClassDefAliasImpl::isLocal(), and ClassDefImpl::mergeCategory().
isLocal() [2/2]
virtual bool ClassDef::isLocal () const [pure virtual]
Returns TRUE if this is a local class definition, see EXTRACT_LOCAL_CLASSES
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
isObjectiveC() [1/2]
virtual bool ClassDef::isObjectiveC () const [pure virtual]
Returns TRUE if this class is implemented in Objective-C
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by MemberDefImpl::displayDefinition(), ClassDefAliasImpl::isObjectiveC(), MemberDefImpl::writeDocumentation(), and ClassDefImpl::writeMemberList().
isObjectiveC() [2/2]
virtual bool ClassDef::isObjectiveC () const [pure virtual]
Returns TRUE if this class is implemented in Objective-C
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
isPublished() [1/2]
virtual bool ClassDef::isPublished () const [pure virtual]
Returns TRUE if this class is marked as published
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by ClassDefAliasImpl::isPublished().
isPublished() [2/2]
virtual bool ClassDef::isPublished () const [pure virtual]
Returns TRUE if this class is marked as published
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
isReference() [1/2]
virtual bool ClassDef::isReference () const [pure virtual]
Returns TRUE if this class is imported via a tag file
Implements Definition.
Implemented in ClassDefImpl, ClassDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionAliasMixin< ClassDef >, ClassDefImpl, ClassDefAliasImpl, DefinitionMixin< ClassDefMutable >, and DefinitionAliasMixin< ClassDef >.
Referenced by computeClassRelations(), generateDEFForClass(), PerlModGenerator::generatePerlModForClass(), generateXMLForClass(), hasNonReferenceSuperClassRec(), ClassDefImpl::isReference(), ClassDefAliasImpl::isReference(), and writeClassTreeToOutput().
isReference() [2/2]
virtual bool ClassDef::isReference () const [pure virtual]
Returns TRUE if this class is imported via a tag file
Implements Definition.
Implemented in ClassDefImpl, ClassDefAliasImpl, DefinitionMixin< ClassDefMutable >, DefinitionAliasMixin< ClassDef >, ClassDefImpl, ClassDefAliasImpl, DefinitionMixin< ClassDefMutable >, and DefinitionAliasMixin< ClassDef >.
isSealed() [1/2]
virtual bool ClassDef::isSealed () const [pure virtual]
Returns TRUE if this class is marked as sealed
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by generateXMLForClass(), and ClassDefAliasImpl::isSealed().
isSealed() [2/2]
virtual bool ClassDef::isSealed () const [pure virtual]
Returns TRUE if this class is marked as sealed
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
isSimple() [1/2]
virtual bool ClassDef::isSimple () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by MemberDefImpl::getOutputFileBase(), MemberDefImpl::isDetailedSectionVisible(), ClassDefAliasImpl::isSimple(), ClassContext::Private::isSimple(), and writeClassTree().
isSimple() [2/2]
virtual bool ClassDef::isSimple () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
isSliceLocal() [1/2]
virtual bool ClassDef::isSliceLocal () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by ClassDefAliasImpl::isSliceLocal().
isSliceLocal() [2/2]
virtual bool ClassDef::isSliceLocal () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
isSmartPointer() [1/2]
virtual const MemberDef * ClassDef::isSmartPointer () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by ClassDefAliasImpl::isSmartPointer().
isSmartPointer() [2/2]
virtual const MemberDef * ClassDef::isSmartPointer () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
isSubClass() [1/2]
virtual bool ClassDef::isSubClass (ClassDef * bcd, int level = 0) const [pure virtual]
Returns TRUE iff bcd is a direct or indirect sub class of this class.
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by findClassRelation(), ClassDefImpl::isSubClass(), and ClassDefAliasImpl::isSubClass().
isSubClass() [2/2]
virtual bool ClassDef::isSubClass (ClassDef * bcd, int level = 0) const [pure virtual]
Returns TRUE iff bcd is a direct or indirect sub class of this class.
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
isTemplate() [1/2]
virtual bool ClassDef::isTemplate () const [pure virtual]
Returns TRUE if this class is a template
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by DocSets::addIndexItem(), flushCachedTemplateRelations(), getCanonicalTypeForIdentifier(), ClassDefAliasImpl::isTemplate(), and SymbolResolver::Private::newResolveTypedef().
isTemplate() [2/2]
virtual bool ClassDef::isTemplate () const [pure virtual]
Returns TRUE if this class is a template
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
isTemplateArgument() [1/2]
virtual bool ClassDef::isTemplateArgument () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by SymbolResolver::Private::getResolvedSymbol(), SymbolResolver::Private::getResolvedType(), and ClassDefAliasImpl::isTemplateArgument().
isTemplateArgument() [2/2]
virtual bool ClassDef::isTemplateArgument () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
isUsedOnly() [1/2]
virtual bool ClassDef::isUsedOnly () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by getCanonicalTypeForIdentifier(), and ClassDefAliasImpl::isUsedOnly().
isUsedOnly() [2/2]
virtual bool ClassDef::isUsedOnly () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
isVisibleInHierarchy() [1/2]
virtual bool ClassDef::isVisibleInHierarchy () const [pure virtual]
the class is visible in a class diagram, or class hierarchy
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by NestingContext::Private::addDerivedClasses(), DotGfxHierarchyTable::addHierarchy(), classHasVisibleChildren(), ClassDefImpl::countInheritanceNodes(), hasVisibleRoot(), DiagramRow::insertClass(), ClassDefAliasImpl::isVisibleInHierarchy(), and writeClassTreeToOutput().
isVisibleInHierarchy() [2/2]
virtual bool ClassDef::isVisibleInHierarchy () const [pure virtual]
the class is visible in a class diagram, or class hierarchy
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
memberNameInfoLinkedMap() [1/2]
virtual const MemberNameInfoLinkedMap & ClassDef::memberNameInfoLinkedMap () const [pure virtual]
Returns a dictionary of all members. This includes any inherited members. Members are sorted alphabetically.
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by PerlModGenerator::addListOfAllMembers(), ClassDefImpl::addMembersToTemplateInstance(), computeClassRelations(), ClassContext::Private::createAllMembersList(), findUsedClassesForClass(), findUsingDeclImports(), ClassDefAliasImpl::memberNameInfoLinkedMap(), ClassDefImpl::mergeCategory(), ClassDefImpl::mergeMembers(), and writeListOfAllMembers().
memberNameInfoLinkedMap() [2/2]
virtual const MemberNameInfoLinkedMap & ClassDef::memberNameInfoLinkedMap () const [pure virtual]
Returns a dictionary of all members. This includes any inherited members. Members are sorted alphabetically.
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
protection() [1/2]
virtual Protection ClassDef::protection () const [pure virtual]
Return the protection level (Public,Protected,Private) in which this compound was found.
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by NestingContext::Private::addClass(), addClassAndNestedClasses(), NestingContext::Private::addDerivedClasses(), VhdlDocGen::findMember(), generateMemLink(), generateXMLForClass(), VhdlDocGen::getClassName(), VhdlDocGen::getClassTitle(), ClassDefImpl::insertSubClass(), ClassDefAliasImpl::protection(), writeClassTree(), writeClassTreeToOutput(), VhdlDocGen::writeClassType(), VhdlDocGen::writeInlineClassLink(), and VhdlDocGen::writeVHDLDeclaration().
protection() [2/2]
virtual Protection ClassDef::protection () const [pure virtual]
Return the protection level (Public,Protected,Private) in which this compound was found.
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
qualifiedNameWithTemplateParameters() [1/2]
virtual QCString ClassDef::qualifiedNameWithTemplateParameters (const ArgumentLists * actualParams = 0, uint * actualParamIndex = 0) const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by addMemberFunction(), addVariableToClass(), findMember(), getCanonicalTypeForIdentifier(), makeDisplayName(), and makeQualifiedNameWithTemplateParameters().
qualifiedNameWithTemplateParameters() [2/2]
virtual QCString ClassDef::qualifiedNameWithTemplateParameters (const ArgumentLists * actualParams = 0, uint * actualParamIndex = 0) const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
requiresClause() [1/2]
virtual QCString ClassDef::requiresClause () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by addClassToContext(), generateXMLForClass(), and ClassDefAliasImpl::requiresClause().
requiresClause() [2/2]
virtual QCString ClassDef::requiresClause () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
subClasses() [1/2]
virtual const BaseClassList & ClassDef::subClasses () const [pure virtual]
Returns the list of sub classes that directly derive from this class
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by NestingNodeContext::Private::addClasses(), NestingContext::Private::addDerivedClasses(), DotGfxHierarchyTable::addHierarchy(), buildCompleteMemberLists(), DotClassGraph::buildGraph(), classHasVisibleChildren(), ClassContext::Private::createInheritedByList(), generateDEFForClass(), PerlModGenerator::generatePerlModForClass(), generateXMLForClass(), hasNonReferenceSuperClassRec(), DiagramRow::insertClass(), VhdlDocGen::isSubClass(), ClassDefAliasImpl::subClasses(), and writeClassTreeToOutput().
subClasses() [2/2]
virtual const BaseClassList & ClassDef::subClasses () const [pure virtual]
Returns the list of sub classes that directly derive from this class
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
subGrouping() [1/2]
virtual bool ClassDef::subGrouping () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by InheritedMemberInfoListContext::Private::addMemberGroupsOfClass(), ClassContext::Private::createMemberGroups(), and ClassDefAliasImpl::subGrouping().
subGrouping() [2/2]
virtual bool ClassDef::subGrouping () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
tagLessReference() [1/2]
virtual const ClassDef * ClassDef::tagLessReference () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by ClassDefAliasImpl::tagLessReference().
tagLessReference() [2/2]
virtual const ClassDef * ClassDef::tagLessReference () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
templateArguments() [1/2]
virtual const ArgumentList & ClassDef::templateArguments () const [pure virtual]
Returns the template arguments of this class
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by addClassToContext(), ClassDefImpl::addMembersToTemplateInstance(), ClassContext::Private::addTemplateDecls(), addTemplateList(), computeTemplateClassRelations(), createTemplateInstanceMembers(), findBaseClassesForClass(), findTemplateInstanceRelation(), findUsedClassesForClass(), getTemplateArgumentsFromName(), insertTemplateSpecifierInScope(), makeQualifiedNameWithTemplateParameters(), SymbolResolver::Private::newResolveTypedef(), searchTemplateSpecs(), ClassDefAliasImpl::templateArguments(), and writeTemplateList().
templateArguments() [2/2]
virtual const ArgumentList & ClassDef::templateArguments () const [pure virtual]
Returns the template arguments of this class
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
templateMaster() [1/2]
virtual const ClassDef * ClassDef::templateMaster () const [pure virtual]
Returns the template master of which this class is an instance. Returns 0 if not applicable.
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by NestingContext::Private::addClass(), addClassAndNestedClasses(), addClassMemberNameToIndex(), addMemberToSearchIndex(), DotClassGraph::buildGraph(), ClassMembersIndexContext::Private::createMembersFiltered(), generateDEFForClass(), generateDocsForClassList(), generateNamespaceClassDocs(), PerlModGenerator::generatePerlModForClass(), generateXMLForClass(), ClassDefImpl::isBaseClass(), VhdlDocGen::isSubClass(), namespaceHasNestedClass(), ClassDefAliasImpl::templateMaster(), DotNode::writeBox(), and writeClassTree().
templateMaster() [2/2]
virtual const ClassDef * ClassDef::templateMaster () const [pure virtual]
Returns the template master of which this class is an instance. Returns 0 if not applicable.
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
templateTypeConstraints() [1/2]
virtual const ConstraintClassList & ClassDef::templateTypeConstraints () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by DotClassGraph::buildGraph(), and ClassDefAliasImpl::templateTypeConstraints().
templateTypeConstraints() [2/2]
virtual const ConstraintClassList & ClassDef::templateTypeConstraints () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
title() [1/2]
virtual QCString ClassDef::title () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), doxmlparser.compound.docSimpleSectType::set_title(), ClassDefAliasImpl::title(), and ClassContext::Private::title().
title() [2/2]
virtual QCString ClassDef::title () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
typeConstraints() [1/2]
virtual const ArgumentList & ClassDef::typeConstraints () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by ClassContext::Private::createTypeConstraints(), and ClassDefAliasImpl::typeConstraints().
typeConstraints() [2/2]
virtual const ArgumentList & ClassDef::typeConstraints () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
updateBaseClasses() [1/2]
virtual void ClassDef::updateBaseClasses (const BaseClassList & bcd) [pure virtual]
Update the list of base classes to the one passed
Implemented in ClassDefAliasImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefImpl.
Referenced by VhdlDocGen::addBaseClass().
updateBaseClasses() [2/2]
virtual void ClassDef::updateBaseClasses (const BaseClassList & bcd) [pure virtual]
Update the list of base classes to the one passed
Implemented in ClassDefAliasImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefImpl.
updateSubClasses() [1/2]
virtual void ClassDef::updateSubClasses (const BaseClassList & bcd) [pure virtual]
Update the list of sub classes to the one passed
Implemented in ClassDefAliasImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefImpl.
updateSubClasses() [2/2]
virtual void ClassDef::updateSubClasses (const BaseClassList & bcd) [pure virtual]
Update the list of sub classes to the one passed
Implemented in ClassDefAliasImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefImpl.
usedByImplementationClasses() [1/2]
virtual const UsesClassList & ClassDef::usedByImplementationClasses () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by DotClassGraph::buildGraph(), and ClassDefAliasImpl::usedByImplementationClasses().
usedByImplementationClasses() [2/2]
virtual const UsesClassList & ClassDef::usedByImplementationClasses () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
usedFiles() [1/2]
virtual const FileList & ClassDef::usedFiles () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by ClassDefAliasImpl::usedFiles(), and UsedFilesContext::UsedFilesContext().
usedFiles() [2/2]
virtual const FileList & ClassDef::usedFiles () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
usedImplementationClasses() [1/2]
virtual const UsesClassList & ClassDef::usedImplementationClasses () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by DotClassGraph::buildGraph(), and ClassDefAliasImpl::usedImplementationClasses().
usedImplementationClasses() [2/2]
virtual const UsesClassList & ClassDef::usedImplementationClasses () const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
visibleInParentsDeclList() [1/2]
virtual bool ClassDef::visibleInParentsDeclList () const [pure virtual]
show this class in the declaration section of its parent?
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by ClassDefAliasImpl::visibleInParentsDeclList().
visibleInParentsDeclList() [2/2]
virtual bool ClassDef::visibleInParentsDeclList () const [pure virtual]
show this class in the declaration section of its parent?
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
writeDeclarationLink() [1/2]
virtual void ClassDef::writeDeclarationLink (OutputList & ol, bool & found, const QCString & header, bool localNames) const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
Referenced by ClassDefAliasImpl::writeDeclarationLink().
writeDeclarationLink() [2/2]
virtual void ClassDef::writeDeclarationLink (OutputList & ol, bool & found, const QCString & header, bool localNames) const [pure virtual]
Implemented in ClassDefImpl, ClassDefAliasImpl, ClassDefImpl, and ClassDefAliasImpl.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/classdef.h
doxygen/src/classdef.h