Image Class Reference
#include <image.h>
Public Member Functions
Image (uint w, uint h)
~Image ()
void setPixel (uint x, uint y, uchar val)
uchar getPixel (uint x, uint y) const
void writeChar (uint x, uint y, char c, uchar fg)
void writeString (uint x, uint y, const QCString &s, uchar fg)
void drawHorzLine (uint y, uint xs, uint xe, uchar colIndex, uint mask)
void drawHorzArrow (uint y, uint xs, uint xe, uchar colIndex, uint mask)
void drawVertLine (uint x, uint ys, uint ye, uchar colIndex, uint mask)
void drawVertArrow (uint x, uint ys, uint ye, uchar colIndex, uint mask)
void drawRect (uint x, uint y, uint width, uint height, uchar colIndex, uint mask)
void fillRect (uint x, uint y, uint width, uint height, uchar colIndex, uint mask)
bool save (const QCString &fileName)
uint width () const
uint height () const
Image (uint w, uint h)
~Image ()
void setPixel (uint x, uint y, uchar val)
uchar getPixel (uint x, uint y) const
void writeChar (uint x, uint y, char c, uchar fg)
void writeString (uint x, uint y, const QCString &s, uchar fg)
void drawHorzLine (uint y, uint xs, uint xe, uchar colIndex, uint mask)
void drawHorzArrow (uint y, uint xs, uint xe, uchar colIndex, uint mask)
void drawVertLine (uint x, uint ys, uint ye, uchar colIndex, uint mask)
void drawVertArrow (uint x, uint ys, uint ye, uchar colIndex, uint mask)
void drawRect (uint x, uint y, uint width, uint height, uchar colIndex, uint mask)
void fillRect (uint x, uint y, uint width, uint height, uchar colIndex, uint mask)
bool save (const QCString &fileName)
uint width () const
uint height () const
Static Public Member Functions
static uint stringLength (const QCString &s)
static uint stringLength (const QCString &s)
Private Attributes
uint m_width
uint m_height
std::vector< uchar > m_data
Friends
uint stringLength (const QCString &s)
uint stringLength (const QCString &s)
Detailed Description
Class representing a bitmap image generated by doxygen.
Definition at line 27 of file image.h.
Constructor & Destructor Documentation
Image() [1/2]
Image::Image (uint w, uint h)
Definition at line 168 of file image.cpp.
{
  int hue = Config_getInt(HTML_COLORSTYLE_HUE);
  int sat = Config_getInt(HTML_COLORSTYLE_SAT);
  int gamma = Config_getInt(HTML_COLORSTYLE_GAMMA);
  double red1,green1,blue1;
  double red2,green2,blue2;
  ColoredImage::hsl2rgb(hue/360.0, // hue
                        sat/255.0, // saturation
                        pow(235/255.0,gamma/100.0), // luma (gamma corrected)
                        &red1,&green1,&blue1
                       );
  ColoredImage::hsl2rgb(hue/360.0, // hue
                        sat/255.0, // saturation
                        pow(138/255.0,gamma/100.0), // luma (gamma corrected)
                        &red2,&green2,&blue2
                       );
  palette[2].red = static_cast<Byte>(red1 * 255.0);
  palette[2].green = static_cast<Byte>(green1 * 255.0);
  palette[2].blue = static_cast<Byte>(blue1 * 255.0);
  palette[3].red = static_cast<Byte>(red2 * 255.0);
  palette[3].green = static_cast<Byte>(green2 * 255.0);
  palette[3].blue = static_cast<Byte>(blue2 * 255.0);
  m_data.resize(w*h);
  m_width = w;
  m_height = h;
}
References Color::blue, Config_getInt, Color::green, h, ColoredImage::hsl2rgb(), m_data, m_height, m_width, palette, Color::red, and w.
 Image() [1/2]
Image::~Image ()
Definition at line 202 of file image.cpp.
{
}
Image() [2/2]
Image::Image (uint w, uint h)
 Image() [2/2]
Image::~Image ()
Member Function Documentation
drawHorzArrow() [1/2]
void Image::drawHorzArrow (uint y, uint xs, uint xe, uchar colIndex, uint mask)
Definition at line 293 of file image.cpp.
{
  drawHorzLine(y,xs,xe,colIndex,mask);
  uint i;
  for (i=0;i<6;i++)
  {
    uint h=i>>1;
    drawVertLine(xe-i,y-h,y+h,colIndex,0xffffffff);
  }
}
References drawHorzLine(), drawVertLine(), h, and y.
Referenced by TreeDiagram::drawConnectors().
drawHorzArrow() [2/2]
void Image::drawHorzArrow (uint y, uint xs, uint xe, uchar colIndex, uint mask)
drawHorzLine() [1/2]
void Image::drawHorzLine (uint y, uint xs, uint xe, uchar colIndex, uint mask)
Definition at line 283 of file image.cpp.
{
  uint x,i=0,j=0;
  for (x=xs;x<=xe;x++,j++)
  {
    if (j&1) i++;
    if (mask&(1<<(i&0x1f))) setPixel(x,y,colIndex);
  }
}
References setPixel(), x, and y.
Referenced by TreeDiagram::drawConnectors(), drawHorzArrow(), drawRect(), drawVertArrow(), and writeBitmapBox().
drawHorzLine() [2/2]
void Image::drawHorzLine (uint y, uint xs, uint xe, uchar colIndex, uint mask)
drawRect() [1/2]
void Image::drawRect (uint x, uint y, uint width, uint height, uchar colIndex, uint mask)
Definition at line 324 of file image.cpp.
{
  drawHorzLine(y,x,x+w-1,colIndex,mask);
  drawHorzLine(y+h-1,x,x+w-1,colIndex,mask);
  drawVertLine(x,y,y+h-1,colIndex,mask);
  drawVertLine(x+w-1,y,y+h-1,colIndex,mask);
}
References drawHorzLine(), drawVertLine(), h, w, x, and y.
Referenced by writeBitmapBox().
drawRect() [2/2]
void Image::drawRect (uint x, uint y, uint width, uint height, uchar colIndex, uint mask)
drawVertArrow() [1/2]
void Image::drawVertArrow (uint x, uint ys, uint ye, uchar colIndex, uint mask)
Definition at line 313 of file image.cpp.
{
  drawVertLine(x,ys,ye,colIndex,mask);
  uint i;
  for (i=0;i<6;i++)
  {
    uint h=i>>1;
    drawHorzLine(ys+i,x-h,x+h,colIndex,0xffffffff);
  }
}
References drawHorzLine(), drawVertLine(), h, and x.
Referenced by TreeDiagram::drawConnectors().
drawVertArrow() [2/2]
void Image::drawVertArrow (uint x, uint ys, uint ye, uchar colIndex, uint mask)
drawVertLine() [1/2]
void Image::drawVertLine (uint x, uint ys, uint ye, uchar colIndex, uint mask)
Definition at line 304 of file image.cpp.
{
  uint y,i=0;
  for (y=ys;y<=ye;y++,i++)
  {
    if (mask&(1<<(i&0x1f))) setPixel(x,y,colIndex);
  }
}
References setPixel(), x, and y.
Referenced by TreeDiagram::drawConnectors(), drawHorzArrow(), drawRect(), and drawVertArrow().
drawVertLine() [2/2]
void Image::drawVertLine (uint x, uint ys, uint ye, uchar colIndex, uint mask)
fillRect() [1/2]
void Image::fillRect (uint x, uint y, uint width, uint height, uchar colIndex, uint mask)
Definition at line 332 of file image.cpp.
{
  uint xp,yp,xi,yi;
  for (yp=y,yi=0;yp<y+height;yp++,yi++)
    for (xp=x,xi=0;xp<x+width;xp++,xi++)
      if (mask&(1<<((xi+yi)&0x1f)))
        setPixel(xp,yp,colIndex);
}
References height(), setPixel(), width(), x, and y.
Referenced by writeBitmapBox().
fillRect() [2/2]
void Image::fillRect (uint x, uint y, uint width, uint height, uchar colIndex, uint mask)
getPixel() [1/2]
uchar Image::getPixel (uint x, uint y) const
Definition at line 212 of file image.cpp.
{
  if (x<m_width && y<m_height)
    return m_data[y*m_width+x];
  else
    return 0;
}
References m_data, m_height, m_width, x, and y.
Referenced by writeChar().
getPixel() [2/2]
uchar Image::getPixel (uint x, uint y) const
height() [1/2]
uint Image::height () const [inline]
Definition at line 46 of file image.h.
{ return m_height; }
References m_height.
Referenced by doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), TreeDiagram::drawBoxes(), TreeDiagram::drawConnectors(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), fillRect(), doxmlparser.compound.docImageType::get_height(), doxmlparser.compound.docDotMscType::get_height(), doxmlparser.compound.docImageFileType::get_height(), doxmlparser.compound.docPlantumlType::get_height(), doxmlparser.compound.docImageType::set_height(), doxmlparser.compound.docDotMscType::set_height(), doxmlparser.compound.docImageFileType::set_height(), and doxmlparser.compound.docPlantumlType::set_height().
height() [2/2]
uint Image::height () const [inline]
Definition at line 46 of file image.h.
{ return m_height; }
References m_height.
Referenced by doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.compound.docImageType::get_height(), doxmlparser.compound.docDotMscType::get_height(), doxmlparser.compound.docImageFileType::get_height(), doxmlparser.compound.docPlantumlType::get_height(), doxmlparser.compound.docImageType::set_height(), doxmlparser.compound.docDotMscType::set_height(), doxmlparser.compound.docImageFileType::set_height(), and doxmlparser.compound.docPlantumlType::set_height().
save() [1/2]
bool Image::save (const QCString & fileName)
Definition at line 341 of file image.cpp.
{
  uchar* buffer;
  size_t bufferSize;
  LodePNG_Encoder encoder;
  LodePNG_Encoder_init(&encoder);
  uint numCols = 9;
  Color *pPal = palette;
  uint i;
  for (i=0;i<numCols;i++,pPal++)
  {
    LodePNG_InfoColor_addPalette(&encoder.infoPng.color,
                                 pPal->red,pPal->green,pPal->blue,pPal->alpha);
  }
  encoder.infoPng.color.colorType = 3;
  encoder.infoRaw.color.colorType = 3;
  LodePNG_encode(&encoder, &buffer, &bufferSize, &m_data[0], m_width, m_height);
  LodePNG_saveFile(buffer, bufferSize, fileName.data());
  free(buffer);
  LodePNG_Encoder_cleanup(&encoder);
  return TRUE;
}
References Color::alpha, Color::blue, LodePNG_InfoPng::color, LodePNG_InfoRaw::color, LodePNG_InfoColor::colorType, QCString::data(), Color::green, LodePNG_Encoder::infoPng, LodePNG_Encoder::infoRaw, LodePNG_encode(), LodePNG_Encoder_cleanup(), LodePNG_Encoder_init(), LodePNG_InfoColor_addPalette(), LodePNG_saveFile(), m_data, m_height, m_width, palette, Color::red, and TRUE.
save() [2/2]
bool Image::save (const QCString & fileName)
setPixel() [1/2]
void Image::setPixel (uint x, uint y, uchar val)
Definition at line 206 of file image.cpp.
{
  if (x<m_width && y<m_height)
    m_data[y*m_width+x] = val;
}
References m_data, m_height, m_width, testsqlite3::val, x, and y.
Referenced by drawHorzLine(), drawVertLine(), fillRect(), and writeChar().
setPixel() [2/2]
void Image::setPixel (uint x, uint y, uchar val)
stringLength() [1/2]
static uint Image::stringLength (const QCString & s) [static]
stringLength() [2/2]
static uint Image::stringLength (const QCString & s) [static]
width() [1/2]
uint Image::width () const [inline]
Definition at line 45 of file image.h.
{ return m_width; }
References m_width.
Referenced by doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docTableType::__init__(), doxmlparser.compound.docEntryType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docTableType::buildAttributes(), doxmlparser.compound.docEntryType::buildAttributes(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEntryType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.compound.docTableType::exportAttributes(), fillRect(), doxmlparser.compound.docTableType::get_width(), doxmlparser.compound.docEntryType::get_width(), doxmlparser.compound.docImageType::get_width(), doxmlparser.compound.docDotMscType::get_width(), doxmlparser.compound.docImageFileType::get_width(), doxmlparser.compound.docPlantumlType::get_width(), doxmlparser.compound.docTableType::set_width(), doxmlparser.compound.docEntryType::set_width(), doxmlparser.compound.docImageType::set_width(), doxmlparser.compound.docDotMscType::set_width(), doxmlparser.compound.docImageFileType::set_width(), and doxmlparser.compound.docPlantumlType::set_width().
width() [2/2]
uint Image::width () const [inline]
Definition at line 45 of file image.h.
{ return m_width; }
References m_width.
Referenced by doxmlparser.compound.docPlantumlType::__init__(), doxmlparser.compound.docDotMscType::__init__(), doxmlparser.compound.docImageFileType::__init__(), doxmlparser.compound.docTableType::__init__(), doxmlparser.compound.docEntryType::__init__(), doxmlparser.compound.docImageType::__init__(), doxmlparser.compound.docTableType::buildAttributes(), doxmlparser.compound.docEntryType::buildAttributes(), doxmlparser.compound.docImageType::buildAttributes(), doxmlparser.compound.docDotMscType::buildAttributes(), doxmlparser.compound.docImageFileType::buildAttributes(), doxmlparser.compound.docPlantumlType::buildAttributes(), doxmlparser.compound.docDotMscType::exportAttributes(), doxmlparser.compound.docEntryType::exportAttributes(), doxmlparser.compound.docImageFileType::exportAttributes(), doxmlparser.compound.docImageType::exportAttributes(), doxmlparser.compound.docPlantumlType::exportAttributes(), doxmlparser.compound.docTableType::exportAttributes(), doxmlparser.compound.docTableType::get_width(), doxmlparser.compound.docEntryType::get_width(), doxmlparser.compound.docImageType::get_width(), doxmlparser.compound.docDotMscType::get_width(), doxmlparser.compound.docImageFileType::get_width(), doxmlparser.compound.docPlantumlType::get_width(), doxmlparser.compound.docTableType::set_width(), doxmlparser.compound.docEntryType::set_width(), doxmlparser.compound.docImageType::set_width(), doxmlparser.compound.docDotMscType::set_width(), doxmlparser.compound.docImageFileType::set_width(), and doxmlparser.compound.docPlantumlType::set_width().
writeChar() [1/2]
void Image::writeChar (uint x, uint y, char c, uchar fg)
Definition at line 220 of file image.cpp.
{
  if (c>=' ')
  {
    uint xf,yf,ci=c-' ';
    uint rowOffset=0;
    uint cw = charWidth[ci];
    uint cp = charPos[ci];
    for (yf=0;yf<charHeight;yf++)
    {
      unsigned short bitPattern=0;
      uint bitsLeft=cw;
      uint byteOffset = rowOffset+(cp>>3);
      uint bitOffset = cp&7;
      // get the bit pattern for row yf of the character from the font data
      while (bitsLeft>0)
      {
        uint bits=8-bitOffset;
        if (bits>bitsLeft) bits=bitsLeft;
        bitPattern<<=bits;
        bitPattern|=((fontRaw[byteOffset]<<bitOffset)&0xff)>>(8-bits);
        bitsLeft-=bits;
        bitOffset=0;
        byteOffset++;
      }
      uint mask=1<<(cw-1);
      // draw character row yf
      for (xf=0;xf<cw;xf++)
      {
        setPixel(x+xf,y+yf,(bitPattern&mask) ? fg : getPixel(x+xf,y+yf));
        mask>>=1;
      }
      rowOffset+=charSetWidth;
    }
  }
}
References c, charHeight, charPos, charSetWidth, charWidth, fg, fontRaw, getPixel(), setPixel(), x, and y.
Referenced by writeString().
writeChar() [2/2]
void Image::writeChar (uint x, uint y, char c, uchar fg)
writeString() [1/2]
void Image::writeString (uint x, uint y, const QCString & s, uchar fg)
Definition at line 257 of file image.cpp.
{
  if (!s.isEmpty())
  {
    const char *p = s.data();
    char c;
    while ((c=*p++))
    {
      writeChar(x,y,c,fg);
      x+=charWidth[c-' '];
    }
  }
}
References c, charWidth, gdFont::data, fg, p, s, writeChar(), x, and y.
Referenced by writeBitmapBox().
writeString() [2/2]
void Image::writeString (uint x, uint y, const QCString & s, uchar fg)
Friends And Related Function Documentation
stringLength [1/2]
uint Image::stringLength (const QCString & s) [friend]
Definition at line 271 of file image.cpp.
{
  uint w=0;
  if (!s.isEmpty())
  {
    const char *p = s.data();
    char c;
    while ((c=*p++)) w+=charWidth[c-' '];
  }
  return w;
}
Referenced by TreeDiagram::computeExtremes(), and writeBitmapBox().
stringLength [2/2]
uint stringLength (const QCString & s) [friend]
Member Data Documentation
m_data
std::vector< uchar > Image::m_data [private]
Definition at line 52 of file image.h.
Referenced by getPixel(), Image(), save(), and setPixel().
m_height
uint Image::m_height [private]
Definition at line 51 of file image.h.
Referenced by getPixel(), height(), Image(), save(), and setPixel().
m_width
uint Image::m_width [private]
Definition at line 50 of file image.h.
Referenced by getPixel(), Image(), save(), setPixel(), and width().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/image.h
doxygen/src/image.h
doxygen/build/doxygen/src/image.cpp
doxygen/src/image.cpp