SIDataCollection Class Reference
#include <searchindex.h>
Public Member Functions
void setCurrentDoc (const Definition *ctx, const QCString &anchor, bool isSourceFile)
void addWord (const QCString &word, bool hiPriority)
void transfer ()
void setCurrentDoc (const Definition *ctx, const QCString &anchor, bool isSourceFile)
void addWord (const QCString &word, bool hiPriority)
void transfer ()
Private Types
using SIData = std::variant< SIData_CurrentDoc, SIData_Word >
using SIData = std::variant< SIData_CurrentDoc, SIData_Word >
Private Attributes
std::vector< SIData > m_data
Detailed Description
Definition at line 66 of file searchindex.h.
Member Typedef Documentation
SIData [1/2]
using SIDataCollection::SIData = std::variant<SIData_CurrentDoc,SIData_Word> [private]
Definition at line 82 of file searchindex.h.
SIData [2/2]
using SIDataCollection::SIData = std::variant<SIData_CurrentDoc,SIData_Word> [private]
Definition at line 82 of file searchindex.h.
Member Function Documentation
addWord() [1/2]
void SIDataCollection::addWord (const QCString & word, bool hiPriority) [inline]
Definition at line 73 of file searchindex.h.
    {
      m_data.emplace_back(SIData_Word(word,hiPriority));
    }
References m_data, and word.
Referenced by OutputList::addWord(), DocLinkedWord::DocLinkedWord(), and DocWord::DocWord().
addWord() [2/2]
void SIDataCollection::addWord (const QCString & word, bool hiPriority) [inline]
Definition at line 73 of file searchindex.h.
    {
      m_data.emplace_back(SIData_Word(word,hiPriority));
    }
References m_data, and word.
setCurrentDoc() [1/2]
void SIDataCollection::setCurrentDoc (const Definition * ctx, const QCString & anchor, bool isSourceFile) [inline]
Definition at line 69 of file searchindex.h.
    {
      m_data.emplace_back(SIData_CurrentDoc(ctx,anchor,isSourceFile));
    }
References m_data.
Referenced by OutputList::setCurrentDoc(), and validatingParseDoc().
setCurrentDoc() [2/2]
void SIDataCollection::setCurrentDoc (const Definition * ctx, const QCString & anchor, bool isSourceFile) [inline]
Definition at line 69 of file searchindex.h.
    {
      m_data.emplace_back(SIData_CurrentDoc(ctx,anchor,isSourceFile));
    }
References m_data.
transfer() [1/2]
void SIDataCollection::transfer ()
Definition at line 378 of file searchindex.cpp.
{
  if (Doxygen::searchIndex)
  {
    std::lock_guard<std::mutex> lock(g_transferSearchIndexMutex);
    for (const auto &v : m_data)
    {
      if (std::holds_alternative<SIData_Word>(v))
      {
        const auto &d = std::get<SIData_Word>(v);
        Doxygen::searchIndex->addWord(d.word,d.hiPrio);
      }
      else if (std::holds_alternative<SIData_CurrentDoc>(v))
      {
        const auto &d = std::get<SIData_CurrentDoc>(v);
        Doxygen::searchIndex->setCurrentDoc(d.ctx,d.anchor,d.isSourceFile);
      }
    }
  }
  m_data.clear();
}
References SearchIndexIntf::addWord(), g_transferSearchIndexMutex, Doxygen::searchIndex, and SearchIndexIntf::setCurrentDoc().
Referenced by OutputList::indexSearchData(), and DocParser::~DocParser().
transfer() [2/2]
void SIDataCollection::transfer ()
Member Data Documentation
m_data
std::vector< SIData > SIDataCollection::m_data [private]
Definition at line 83 of file searchindex.h.
Referenced by addWord(), and setCurrentDoc().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/searchindex.h
doxygen/src/searchindex.h
doxygen/build/doxygen/src/searchindex.cpp
doxygen/src/searchindex.cpp