ConfigEnum Class Reference
#include <configimpl.h>
Public Member Functions
ConfigEnum (const char *name, const char *doc, const char *defVal)
void addValue (const char *v)
const std::vector< QCString > & values () const
QCString * valueRef ()
void substEnvVars ()
void writeTemplate (TextStream &t, bool sl, bool)
void convertStrToVal (Config::CompareMode compareMode)
void compareDoxyfile (TextStream &t, Config::CompareMode compareMode)
void writeXMLDoxyfile (TextStream &t)
void init ()
bool isDefault ()
ConfigEnum (const char *name, const char *doc, const char *defVal)
void addValue (const char *v)
const std::vector< QCString > & values () const
QCString * valueRef ()
void substEnvVars ()
void writeTemplate (TextStream &t, bool sl, bool)
void convertStrToVal (Config::CompareMode compareMode)
void compareDoxyfile (TextStream &t, Config::CompareMode compareMode)
void writeXMLDoxyfile (TextStream &t)
void init ()
bool isDefault ()
Private Attributes
std::vector< QCString > m_valueRange
QCString m_value
QCString m_defValue
Additional Inherited Members
Detailed Description
Class representing an enum type option.
Definition at line 153 of file configimpl.h.
Constructor & Destructor Documentation
ConfigEnum() [1/2]
ConfigEnum::ConfigEnum (const char * name, const char * doc, const char * defVal) [inline]
Definition at line 156 of file configimpl.h.
      : ConfigOption(O_Enum)
    {
      m_name = name;
      m_doc = doc;
      m_value = defVal;
      m_defValue = defVal;
    }
References m_defValue, ConfigOption::m_doc, ConfigOption::m_name, m_value, and ConfigOption::name().
ConfigEnum() [2/2]
ConfigEnum::ConfigEnum (const char * name, const char * doc, const char * defVal) [inline]
Definition at line 156 of file configimpl.h.
      : ConfigOption(O_Enum)
    {
      m_name = name;
      m_doc = doc;
      m_value = defVal;
      m_defValue = defVal;
    }
References m_defValue, ConfigOption::m_doc, ConfigOption::m_name, m_value, and ConfigOption::name().
Member Function Documentation
addValue() [1/2]
void ConfigEnum::addValue (const char * v) [inline]
Definition at line 164 of file configimpl.h.
{ m_valueRange.push_back(v); }
References m_valueRange.
addValue() [2/2]
void ConfigEnum::addValue (const char * v) [inline]
Definition at line 164 of file configimpl.h.
{ m_valueRange.push_back(v); }
References m_valueRange.
compareDoxyfile() [1/2]
void ConfigEnum::compareDoxyfile (TextStream & t, Config::CompareMode compareMode) [virtual]
Implements ConfigOption.
Definition at line 470 of file configimpl.l.
{
  if (!isDefault()) writeTemplate(t,TRUE,TRUE);
}
References isDefault(), TRUE, and writeTemplate().
compareDoxyfile() [2/2]
void ConfigEnum::compareDoxyfile (TextStream & t, Config::CompareMode compareMode) [virtual]
Implements ConfigOption.
convertStrToVal() [1/2]
void ConfigEnum::convertStrToVal (Config::CompareMode compareMode) [virtual]
Reimplemented from ConfigOption.
Definition at line 271 of file configimpl.l.
{
  if (m_value.isEmpty())
  {
    m_value = m_defValue;
    return;
  }
  if (compareMode == Config::CompareMode::CompressedNoEnv)
  {
     if (containsEnvVar(m_value)) return;
  }
  QCString val = m_value.stripWhiteSpace().lower();
  for (const auto &s : m_valueRange)
  {
    if (s.lower() == val)
    {
       m_value = s;
       return;
    }
  }
  config_warn("argument '%s' for option %s is not a valid enum value\n"
              "Using the default: %s!\n",qPrint(m_value),qPrint(m_name),qPrint(m_defValue));
  m_value = m_defValue;
}
References Config::CompressedNoEnv, config_warn(), containsEnvVar(), QCString::isEmpty(), QCString::lower(), m_defValue, ConfigOption::m_name, m_value, m_valueRange, qPrint(), s, QCString::stripWhiteSpace(), and testsqlite3::val.
convertStrToVal() [2/2]
void ConfigEnum::convertStrToVal (Config::CompareMode compareMode) [virtual]
Reimplemented from ConfigOption.
init() [1/2]
void ConfigEnum::init () [inline], [virtual]
Reimplemented from ConfigOption.
Definition at line 172 of file configimpl.h.
{ m_value = m_defValue; }
References m_defValue, and m_value.
init() [2/2]
void ConfigEnum::init () [inline], [virtual]
Reimplemented from ConfigOption.
Definition at line 172 of file configimpl.h.
{ m_value = m_defValue; }
References m_defValue, and m_value.
isDefault() [1/2]
bool ConfigEnum::isDefault () [inline], [virtual]
Reimplemented from ConfigOption.
Definition at line 173 of file configimpl.h.
{ return m_value == m_defValue; }
References m_defValue, and m_value.
Referenced by compareDoxyfile(), and writeXMLDoxyfile().
isDefault() [2/2]
bool ConfigEnum::isDefault () [inline], [virtual]
Reimplemented from ConfigOption.
Definition at line 173 of file configimpl.h.
{ return m_value == m_defValue; }
References m_defValue, and m_value.
substEnvVars() [1/2]
void ConfigEnum::substEnvVars () [virtual]
Implements ConfigOption.
Definition at line 1494 of file configimpl.l.
{
  substEnvVarsInString(m_value);
}
References m_value, and substEnvVarsInString().
substEnvVars() [2/2]
void ConfigEnum::substEnvVars () [virtual]
Implements ConfigOption.
valueRef() [1/2]
QCString * ConfigEnum::valueRef () [inline]
Definition at line 166 of file configimpl.h.
{ return &m_value; }
References m_value.
Referenced by Config::updateObsolete().
valueRef() [2/2]
QCString * ConfigEnum::valueRef () [inline]
Definition at line 166 of file configimpl.h.
{ return &m_value; }
References m_value.
values() [1/2]
const std::vector< QCString > & ConfigEnum::values () const [inline]
Definition at line 165 of file configimpl.h.
{ return m_valueRange; }
References m_valueRange.
values() [2/2]
const std::vector< QCString > & ConfigEnum::values () const [inline]
Definition at line 165 of file configimpl.h.
{ return m_valueRange; }
References m_valueRange.
writeTemplate() [1/2]
void ConfigEnum::writeTemplate (TextStream & t, bool sl, bool) [virtual]
Implements ConfigOption.
Definition at line 453 of file configimpl.l.
{
  if (!sl)
  {
    t << "\n";
    t << convertToComment(m_doc, m_userComment);
    t << "\n";
  }
  else if (!m_userComment.isEmpty())
  {
    t << convertToComment("", m_userComment);
  }
  t << m_name << m_spaces.left(MAX_OPTION_LENGTH-m_name.length()) << "=";
  writeStringValue(t,m_value);
  t << "\n";
}
References convertToComment(), QCString::isEmpty(), QCString::left(), QCString::length(), ConfigOption::m_doc, ConfigOption::m_name, ConfigOption::m_spaces, ConfigOption::m_userComment, m_value, ConfigOption::MAX_OPTION_LENGTH, caseconvert::sl, and ConfigOption::writeStringValue().
Referenced by compareDoxyfile().
writeTemplate() [2/2]
void ConfigEnum::writeTemplate (TextStream & t, bool sl, bool) [virtual]
Implements ConfigOption.
writeXMLDoxyfile() [1/2]
void ConfigEnum::writeXMLDoxyfile (TextStream & t) [virtual]
Implements ConfigOption.
Definition at line 475 of file configimpl.l.
{
  t << " <option id='" << m_name << "'";
  t << " default='" << (isDefault() ? "yes" : "no") << "'";
  t << " type='string'";
  t << ">";
  t << "<value>";
  writeStringValue(t,m_value,false);
  t << "</value>";
  t << "</option>\n";
}
References isDefault(), ConfigOption::m_name, m_value, and ConfigOption::writeStringValue().
writeXMLDoxyfile() [2/2]
void ConfigEnum::writeXMLDoxyfile (TextStream & t) [virtual]
Implements ConfigOption.
Member Data Documentation
m_defValue
QCString ConfigEnum::m_defValue [private]
Definition at line 178 of file configimpl.h.
Referenced by ConfigEnum(), convertStrToVal(), init(), and isDefault().
m_value
QCString ConfigEnum::m_value [private]
Definition at line 177 of file configimpl.h.
Referenced by ConfigEnum(), convertStrToVal(), init(), isDefault(), substEnvVars(), valueRef(), writeTemplate(), and writeXMLDoxyfile().
m_valueRange
std::vector< QCString > ConfigEnum::m_valueRange [private]
Definition at line 176 of file configimpl.h.
Referenced by addValue(), convertStrToVal(), and values().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/configimpl.h
doxygen/src/configimpl.h
doxygen/build/doxygen/src/configimpl.l
doxygen/src/configimpl.l