TemplateNodeCloseSubIndex Class Reference
Class representing an 'closesubindex' tag in a template.
Public Member Functions
TemplateNodeCloseSubIndex (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void render (TextStream &, TemplateContext *c)
TemplateNodeCloseSubIndex (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void render (TextStream &, TemplateContext *c)
Private Attributes
QCString m_name
Additional Inherited Members
Detailed Description
Class representing an 'closesubindex' tag in a template.
Definition at line 4144 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeCloseSubIndex() [1/2]
TemplateNodeCloseSubIndex::TemplateNodeCloseSubIndex (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 4147 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeCloseSubIndex>(parser,parent,line)
    {
      TRACE(("{TemplateNodeCloseSubIndex(%s)\n",qPrint(data)));
      m_name = data.stripWhiteSpace();
      if (m_name.isEmpty())
      {
        parser->warn(parser->templateName(),line,"Missing argument for closesubindex tag");
      }
      else if (m_name.find(' ')!=-1 || m_name.isEmpty())
      {
        parser->warn(parser->templateName(),line,"Expected single argument for closesubindex tag got '%s'",qPrint(data));
        m_name="";
      }
      TRACE(("}TemplateNodeCloseSubIndex(%s)\n",qPrint(data)));
    }
References data, QCString::find(), QCString::isEmpty(), m_name, qPrint(), TemplateParser::templateName(), TRACE, and TemplateParser::warn().
TemplateNodeCloseSubIndex() [2/2]
TemplateNodeCloseSubIndex::TemplateNodeCloseSubIndex (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) [inline]
Definition at line 4147 of file template.cpp.
      : TemplateNodeCreator<TemplateNodeCloseSubIndex>(parser,parent,line)
    {
      TRACE(("{TemplateNodeCloseSubIndex(%s)\n",qPrint(data)));
      m_name = data.stripWhiteSpace();
      if (m_name.isEmpty())
      {
        parser->warn(parser->templateName(),line,"Missing argument for closesubindex tag");
      }
      else if (m_name.find(' ')!=-1 || m_name.isEmpty())
      {
        parser->warn(parser->templateName(),line,"Expected single argument for closesubindex tag got '%s'",qPrint(data));
        m_name="";
      }
      TRACE(("}TemplateNodeCloseSubIndex(%s)\n",qPrint(data)));
    }
References data, QCString::find(), QCString::isEmpty(), m_name, qPrint(), TemplateParser::templateName(), TRACE, and TemplateParser::warn().
Member Function Documentation
render() [1/2]
void TemplateNodeCloseSubIndex::render (TextStream & , TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 4163 of file template.cpp.
    {
      TemplateContextImpl *ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      if (!m_name.isEmpty())
      {
        ci->setLocation(m_templateName,m_line);
        ci->closeSubIndex(m_name);
      }
    }
References c, TemplateContextImpl::closeSubIndex(), QCString::isEmpty(), TemplateNodeCreator< TemplateNodeCloseSubIndex >::m_line, m_name, TemplateNodeCreator< TemplateNodeCloseSubIndex >::m_templateName, and TemplateContextImpl::setLocation().
render() [2/2]
void TemplateNodeCloseSubIndex::render (TextStream & , TemplateContext * c) [inline], [virtual]
Implements TemplateNode.
Definition at line 4163 of file template.cpp.
    {
      TemplateContextImpl *ci = dynamic_cast<TemplateContextImpl*>(c);
      if (ci==0) return; // should not happen
      if (!m_name.isEmpty())
      {
        ci->setLocation(m_templateName,m_line);
        ci->closeSubIndex(m_name);
      }
    }
References c, TemplateContextImpl::closeSubIndex(), QCString::isEmpty(), TemplateNodeCreator< TemplateNodeCloseSubIndex >::m_line, m_name, TemplateNodeCreator< TemplateNodeCloseSubIndex >::m_templateName, and TemplateContextImpl::setLocation().
Member Data Documentation
m_name
QCString TemplateNodeCloseSubIndex::m_name [private]
Definition at line 4174 of file template.cpp.
Referenced by render(), and TemplateNodeCloseSubIndex().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp