GrowVector< T > Class Template Reference
std::vector like container optimised for pushing elements to the back.
#include <growvector.h>
Classes
struct Chunk
class Iterator
bidirectional iterator
Public Types
using iterator = Iterator< GrowVector, T >
using const_iterator = Iterator< const GrowVector, const T >
using iterator = Iterator< GrowVector, T >
using const_iterator = Iterator< const GrowVector, const T >
Public Member Functions
iterator begin ()
returns an iterator to the beginning
const_iterator begin () const
returns an iterator to the beginning
iterator end ()
returns an iterator to the end
const_iterator end () const
returns an iterator to the end
size_t size () const
returns the number of elements
void push_back (T &&t)
adds an element to the end
template<class... Args>
void emplace_back (Args &&...args)
constructs an element in-place at the end
void pop_back ()
removes the last element
T & at (size_t i)
access specified element
const T & at (size_t i) const
access specified element
T & front ()
access the first element
const T & front () const
access the first element
T & back ()
access the last element
const T & back () const
access the last element
bool empty () const
checks whether the container is empty
void clear ()
clears the contents
iterator begin ()
returns an iterator to the beginning
const_iterator begin () const
returns an iterator to the beginning
iterator end ()
returns an iterator to the end
const_iterator end () const
returns an iterator to the end
size_t size () const
returns the number of elements
void push_back (T &&t)
adds an element to the end
template<class... Args>
void emplace_back (Args &&...args)
constructs an element in-place at the end
void pop_back ()
removes the last element
T & at (size_t i)
access specified element
const T & at (size_t i) const
access specified element
T & front ()
access the first element
const T & front () const
access the first element
T & back ()
access the last element
const T & back () const
access the last element
bool empty () const
checks whether the container is empty
void clear ()
clears the contents
Private Types
using ChunkPtr = std::unique_ptr< Chunk >
using ChunkPtr = std::unique_ptr< Chunk >
Private Member Functions
void make_room ()
void make_room ()
Private Attributes
std::vector< ChunkPtr > m_chunks
Static Private Attributes
static const size_t chunkBits = 4
static const size_t chunkSize = 1 << chunkBits
static const size_t chunkMask = chunkSize-1
Detailed Description
template<class T>
class GrowVector< T >
std::vector like container optimised for pushing elements to the back.
It differs from std::vector in that it can grow without invalidating pointers to its members just like std::deque and std::list.
It differs from std::deque in that the value can be incomplete just like std::vector.
It differs from std::list in that it does not need to allocate each node separately and provides random access to its members.
It is implemented as a vector of chunks where each chunk is a fixed capacity vector of T.
Definition at line 37 of file growvector.h.
Member Typedef Documentation
ChunkPtr [1/2]
template<class T >
using GrowVector< T >::ChunkPtr = std::unique_ptr<Chunk> [private]
Definition at line 48 of file growvector.h.
ChunkPtr [2/2]
template<class T >
using GrowVector< T >::ChunkPtr = std::unique_ptr<Chunk> [private]
Definition at line 48 of file growvector.h.
const_iterator [1/2]
template<class T >
using GrowVector< T >::const_iterator = Iterator<const GrowVector,const T>
Definition at line 79 of file growvector.h.
const_iterator [2/2]
template<class T >
using GrowVector< T >::const_iterator = Iterator<const GrowVector,const T>
Definition at line 79 of file growvector.h.
iterator [1/2]
template<class T >
using GrowVector< T >::iterator = Iterator<GrowVector,T>
Definition at line 78 of file growvector.h.
iterator [2/2]
template<class T >
using GrowVector< T >::iterator = Iterator<GrowVector,T>
Definition at line 78 of file growvector.h.
Member Function Documentation
at() [1/4]
template<class T >
T & GrowVector< T >::at (size_t i) [inline]
access specified element
Definition at line 124 of file growvector.h.
{ return m_chunks.at(i>>chunkBits)->data.at(i&chunkMask); }
References GrowVector< T >::chunkBits, GrowVector< T >::chunkMask, and GrowVector< T >::m_chunks.
at() [2/4]
template<class T >
T & GrowVector< T >::at (size_t i) [inline]
access specified element
Definition at line 124 of file growvector.h.
{ return m_chunks.at(i>>chunkBits)->data.at(i&chunkMask); }
References GrowVector< T >::chunkBits, GrowVector< T >::chunkMask, and GrowVector< T >::m_chunks.
at() [3/4]
template<class T >
const T & GrowVector< T >::at (size_t i) const [inline]
access specified element
Definition at line 126 of file growvector.h.
{ return m_chunks.at(i>>chunkBits)->data.at(i&chunkMask); }
References GrowVector< T >::chunkBits, GrowVector< T >::chunkMask, and GrowVector< T >::m_chunks.
at() [4/4]
template<class T >
const T & GrowVector< T >::at (size_t i) const [inline]
access specified element
Definition at line 126 of file growvector.h.
{ return m_chunks.at(i>>chunkBits)->data.at(i&chunkMask); }
References GrowVector< T >::chunkBits, GrowVector< T >::chunkMask, and GrowVector< T >::m_chunks.
back() [1/4]
template<class T >
T & GrowVector< T >::back () [inline]
access the last element
Definition at line 134 of file growvector.h.
{ return m_chunks.back()->data.back(); }
References GrowVector< T >::m_chunks.
Referenced by DocPara::handleIncludeOperator(), DocPara::handleParamSection(), DocPara::handleSimpleSection(), DocParser::handleStyleEnter(), DocParser::internalValidatingParseDoc(), DocPara::parse(), and DocParamList::parseXml().
back() [2/4]
template<class T >
T & GrowVector< T >::back () [inline]
access the last element
Definition at line 134 of file growvector.h.
{ return m_chunks.back()->data.back(); }
References GrowVector< T >::m_chunks.
back() [3/4]
template<class T >
const T & GrowVector< T >::back () const [inline]
access the last element
Definition at line 136 of file growvector.h.
{ return m_chunks.back()->data.back(); }
References GrowVector< T >::m_chunks.
back() [4/4]
template<class T >
const T & GrowVector< T >::back () const [inline]
access the last element
Definition at line 136 of file growvector.h.
{ return m_chunks.back()->data.back(); }
References GrowVector< T >::m_chunks.
begin() [1/4]
template<class T >
iterator GrowVector< T >::begin () [inline]
returns an iterator to the beginning
Definition at line 82 of file growvector.h.
{ return iterator(*this,0); }
begin() [2/4]
template<class T >
iterator GrowVector< T >::begin () [inline]
returns an iterator to the beginning
Definition at line 82 of file growvector.h.
{ return iterator(*this,0); }
begin() [3/4]
template<class T >
const_iterator GrowVector< T >::begin () const [inline]
returns an iterator to the beginning
Definition at line 84 of file growvector.h.
{ return const_iterator(*this,0); }
begin() [4/4]
template<class T >
const_iterator GrowVector< T >::begin () const [inline]
returns an iterator to the beginning
Definition at line 84 of file growvector.h.
{ return const_iterator(*this,0); }
clear() [1/2]
template<class T >
void GrowVector< T >::clear () [inline]
clears the contents
Definition at line 142 of file growvector.h.
{ m_chunks.clear(); }
References GrowVector< T >::m_chunks.
Referenced by flattenParagraphs(), and DocNodeList::move_append().
clear() [2/2]
template<class T >
void GrowVector< T >::clear () [inline]
clears the contents
Definition at line 142 of file growvector.h.
{ m_chunks.clear(); }
References GrowVector< T >::m_chunks.
emplace_back() [1/2]
template<class T >
template<class... Args>
void GrowVector< T >::emplace_back (Args &&... args) [inline]
constructs an element in-place at the end
Definition at line 107 of file growvector.h.
    {
      make_room();
      m_chunks.back()->data.emplace_back(std::forward<Args>(args)...);
    }
References GrowVector< T >::m_chunks, and GrowVector< T >::make_room().
emplace_back() [2/2]
template<class T >
template<class... Args>
void GrowVector< T >::emplace_back (Args &&... args) [inline]
constructs an element in-place at the end
Definition at line 107 of file growvector.h.
    {
      make_room();
      m_chunks.back()->data.emplace_back(std::forward<Args>(args)...);
    }
References GrowVector< T >::m_chunks, and GrowVector< T >::make_room().
empty() [1/2]
template<class T >
bool GrowVector< T >::empty () const [inline]
checks whether the container is empty
Definition at line 139 of file growvector.h.
{ return m_chunks.empty(); }
References GrowVector< T >::m_chunks.
Referenced by DocParser::defaultHandleToken(), DocImage::hasCaption(), DocDiagramFileBase::hasCaption(), DocVhdlFlow::hasCaption(), DocRef::hasLinkText(), DocTitle::hasTitle(), DocParser::internalValidatingParseDoc(), DocPara::isEmpty(), DocText::isEmpty(), DocRoot::isEmpty(), DocHtmlRow::isHeading(), DocbookDocVisitor::operator()(), XmlDocVisitor::operator()(), PrintDocVisitor::operator()(), DocPara::parse(), DocSimpleSect::parse(), DocParamSect::parse(), DocSimpleSect::parseXml(), and DocParamList::parseXml().
empty() [2/2]
template<class T >
bool GrowVector< T >::empty () const [inline]
checks whether the container is empty
Definition at line 139 of file growvector.h.
{ return m_chunks.empty(); }
References GrowVector< T >::m_chunks.
end() [1/4]
template<class T >
iterator GrowVector< T >::end () [inline]
returns an iterator to the end
Definition at line 87 of file growvector.h.
{ return iterator(*this,size()); }
References GrowVector< T >::size().
Referenced by DocPara::handleIncludeOperator().
end() [2/4]
template<class T >
iterator GrowVector< T >::end () [inline]
returns an iterator to the end
Definition at line 87 of file growvector.h.
{ return iterator(*this,size()); }
References GrowVector< T >::size().
end() [3/4]
template<class T >
const_iterator GrowVector< T >::end () const [inline]
returns an iterator to the end
Definition at line 89 of file growvector.h.
{ return const_iterator(*this,size()); }
References GrowVector< T >::size().
end() [4/4]
template<class T >
const_iterator GrowVector< T >::end () const [inline]
returns an iterator to the end
Definition at line 89 of file growvector.h.
{ return const_iterator(*this,size()); }
References GrowVector< T >::size().
front() [1/4]
template<class T >
T & GrowVector< T >::front () [inline]
access the first element
Definition at line 129 of file growvector.h.
{ return m_chunks.front()->data.front(); }
References GrowVector< T >::m_chunks.
Referenced by DocHtmlTable::firstRow(), and DocbookDocVisitor::operator()().
front() [2/4]
template<class T >
T & GrowVector< T >::front () [inline]
access the first element
Definition at line 129 of file growvector.h.
{ return m_chunks.front()->data.front(); }
References GrowVector< T >::m_chunks.
front() [3/4]
template<class T >
const T & GrowVector< T >::front () const [inline]
access the first element
Definition at line 131 of file growvector.h.
{ return m_chunks.front()->data.front(); }
References GrowVector< T >::m_chunks.
front() [4/4]
template<class T >
const T & GrowVector< T >::front () const [inline]
access the first element
Definition at line 131 of file growvector.h.
{ return m_chunks.front()->data.front(); }
References GrowVector< T >::m_chunks.
make_room() [1/2]
template<class T >
void GrowVector< T >::make_room () [inline], [private]
Definition at line 145 of file growvector.h.
    {
      if (m_chunks.empty() ||
          m_chunks.back()->data.size()==chunkSize) // add new chuck if needed
      {
        m_chunks.push_back(std::make_unique<Chunk>());
      }
    }
References GrowVector< T >::chunkSize, and GrowVector< T >::m_chunks.
Referenced by GrowVector< T >::emplace_back(), and GrowVector< T >::push_back().
make_room() [2/2]
template<class T >
void GrowVector< T >::make_room () [inline], [private]
Definition at line 145 of file growvector.h.
    {
      if (m_chunks.empty() ||
          m_chunks.back()->data.size()==chunkSize) // add new chuck if needed
      {
        m_chunks.push_back(std::make_unique<Chunk>());
      }
    }
References GrowVector< T >::chunkSize, and GrowVector< T >::m_chunks.
pop_back() [1/2]
template<class T >
void GrowVector< T >::pop_back () [inline]
removes the last element
Definition at line 114 of file growvector.h.
    {
      m_chunks.back()->data.pop_back();
      if (m_chunks.back()->data.size()==0) // remove chunk if empty
      {
        m_chunks.pop_back();
      }
    }
References GrowVector< T >::m_chunks.
Referenced by DocPara::handleCommand(), DocPara::handleFile(), DocPara::handleXRefItem(), DocParser::internalValidatingParseDoc(), DocAutoListItem::parse(), DocSection::parse(), DocRoot::parse(), DocInternal::parse(), and DocParamList::parseXml().
pop_back() [2/2]
template<class T >
void GrowVector< T >::pop_back () [inline]
removes the last element
Definition at line 114 of file growvector.h.
    {
      m_chunks.back()->data.pop_back();
      if (m_chunks.back()->data.size()==0) // remove chunk if empty
      {
        m_chunks.pop_back();
      }
    }
References GrowVector< T >::m_chunks.
push_back() [1/2]
template<class T >
void GrowVector< T >::push_back (T && t) [inline]
adds an element to the end
Definition at line 99 of file growvector.h.
    {
      make_room();
      m_chunks.back()->data.push_back(std::move(t));
    }
References GrowVector< T >::m_chunks, and GrowVector< T >::make_room().
push_back() [2/2]
template<class T >
void GrowVector< T >::push_back (T && t) [inline]
adds an element to the end
Definition at line 99 of file growvector.h.
    {
      make_room();
      m_chunks.back()->data.push_back(std::move(t));
    }
References GrowVector< T >::m_chunks, and GrowVector< T >::make_room().
size() [1/2]
template<class T >
size_t GrowVector< T >::size () const [inline]
returns the number of elements
Definition at line 92 of file growvector.h.
    {
      return m_chunks.empty() ? 0 : (m_chunks.size()-1)*chunkSize +
                                     m_chunks.back()->data.size();
    }
References GrowVector< T >::chunkSize, and GrowVector< T >::m_chunks.
Referenced by GrowVector< T >::end(), DocPara::handleIncludeOperator(), DocHtmlRow::numCells(), and DocHtmlTable::numRows().
size() [2/2]
template<class T >
size_t GrowVector< T >::size () const [inline]
returns the number of elements
Definition at line 92 of file growvector.h.
    {
      return m_chunks.empty() ? 0 : (m_chunks.size()-1)*chunkSize +
                                     m_chunks.back()->data.size();
    }
References GrowVector< T >::chunkSize, and GrowVector< T >::m_chunks.
Member Data Documentation
chunkBits
template<class T >
static const size_t GrowVector< T >::chunkBits = 4 [static], [private]
Definition at line 40 of file growvector.h.
Referenced by GrowVector< T >::at().
chunkMask
template<class T >
static const size_t GrowVector< T >::chunkMask = chunkSize-1 [static], [private]
Definition at line 42 of file growvector.h.
Referenced by GrowVector< T >::at().
chunkSize
template<class T >
static const size_t GrowVector< T >::chunkSize = 1 << chunkBits [static], [private]
Definition at line 41 of file growvector.h.
Referenced by GrowVector< T >::Chunk::Chunk(), GrowVector< T >::make_room(), and GrowVector< T >::size().
m_chunks
template<class T >
std::vector< ChunkPtr > GrowVector< T >::m_chunks [private]
Definition at line 153 of file growvector.h.
Referenced by GrowVector< T >::at(), GrowVector< T >::back(), GrowVector< T >::clear(), GrowVector< T >::emplace_back(), GrowVector< T >::empty(), GrowVector< T >::front(), GrowVector< T >::make_room(), GrowVector< T >::pop_back(), GrowVector< T >::push_back(), and GrowVector< T >::size().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/growvector.h
doxygen/src/growvector.h