TranslatorFinnish Class Reference
#include <translator_fi.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
Additional Inherited Members
Detailed Description
Definition at line 89 of file translator_fi.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorFinnish::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 126 of file translator_fi.h.
    {
      return "0x40B Finnish";
    }
getLanguageString() [2/2]
virtual QCString TranslatorFinnish::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 126 of file translator_fi.h.
    {
      return "0x40B Finnish";
    }
idLanguage() [1/2]
virtual QCString TranslatorFinnish::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 100 of file translator_fi.h.
    { return "finnish"; }
idLanguage() [2/2]
virtual QCString TranslatorFinnish::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 100 of file translator_fi.h.
    { return "finnish"; }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorFinnish::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 117 of file translator_fi.h.
    {
      return "\\usepackage[finnish]{babel}\n";
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorFinnish::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 117 of file translator_fi.h.
    {
      return "\\usepackage[finnish]{babel}\n";
    }
trAll() [1/2]
virtual QCString TranslatorFinnish::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1507 of file translator_fi.h.
    {
      return "Kaikki"; // "All"
    }
trAll() [2/2]
virtual QCString TranslatorFinnish::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1507 of file translator_fi.h.
    {
      return "Kaikki"; // "All"
    }
trAttention() [1/2]
virtual QCString TranslatorFinnish::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 1020 of file translator_fi.h.
    {
      return "Huomio"; // "Attention"
    }
trAttention() [2/2]
virtual QCString TranslatorFinnish::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 1020 of file translator_fi.h.
    {
      return "Huomio"; // "Attention"
    }
trAuthor() [1/2]
virtual QCString TranslatorFinnish::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1378 of file translator_fi.h.
    {
      QCString result((first_capital ? "Tekij" : "tekij")); // "Author" / "author"
      if (!singular) result+="t"; // "+s"
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorFinnish::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1378 of file translator_fi.h.
    {
      QCString result((first_capital ? "Tekij" : "tekij")); // "Author" / "author"
      if (!singular) result+="t"; // "+s"
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorFinnish::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1236 of file translator_fi.h.
    {
      return "Bugi"; // "Bug"
    }
trBug() [2/2]
virtual QCString TranslatorFinnish::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1236 of file translator_fi.h.
    {
      return "Bugi"; // "Bug"
    }
trBugList() [1/2]
virtual QCString TranslatorFinnish::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1241 of file translator_fi.h.
    {
      return "Bugilista"; // "Bug List"
    }
trBugList() [2/2]
virtual QCString TranslatorFinnish::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1241 of file translator_fi.h.
    {
      return "Bugilista"; // "Bug List"
    }
trCallerGraph() [1/2]
virtual QCString TranslatorFinnish::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1632 of file translator_fi.h.
    {
      return "Tss on kutsukaavio tlle funktiolle:"; // "Here is the caller graph for this function:"
    }
trCallerGraph() [2/2]
virtual QCString TranslatorFinnish::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1632 of file translator_fi.h.
    {
      return "Tss on kutsukaavio tlle funktiolle:"; // "Here is the caller graph for this function:"
    }
trCallGraph() [1/2]
virtual QCString TranslatorFinnish::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1512 of file translator_fi.h.
    {
      return "Tss on kutsukaavio tlle funktiolle:"; // "Here is the call graph for this function:"
    }
trCallGraph() [2/2]
virtual QCString TranslatorFinnish::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1512 of file translator_fi.h.
    {
      return "Tss on kutsukaavio tlle funktiolle:"; // "Here is the call graph for this function:"
    }
trClass() [1/2]
virtual QCString TranslatorFinnish::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1299 of file translator_fi.h.
    {
      QCString result((first_capital ? "Luokka" : "luokka")); // "Class" / "class"
      if (!singular) result=(first_capital ? "Luokat" : "luokat"); // "+es" -> "Classes" / "classes"
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorFinnish::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1299 of file translator_fi.h.
    {
      QCString result((first_capital ? "Luokka" : "luokka")); // "Class" / "class"
      if (!singular) result=(first_capital ? "Luokat" : "luokat"); // "+es" -> "Classes" / "classes"
      return result;
    }
trClassDiagram() [1/2]
virtual QCString TranslatorFinnish::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 572 of file translator_fi.h.
    {
      return "Luokan "+clName+" luokkakaavio"; // "Inheritance diagram for "
    }
trClassDiagram() [2/2]
virtual QCString TranslatorFinnish::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 572 of file translator_fi.h.
    {
      return "Luokan "+clName+" luokkakaavio"; // "Inheritance diagram for "
    }
trClassDocumentation() [1/2]
virtual QCString TranslatorFinnish::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 443 of file translator_fi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Tietueiden dokumentaatio"; // "Data Structure Documentation"
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Luokkien dokumentaatio"; // "Class Documentation"
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorFinnish::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 443 of file translator_fi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Tietueiden dokumentaatio"; // "Data Structure Documentation"
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Luokkien dokumentaatio"; // "Class Documentation"
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorFinnish::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1199 of file translator_fi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Tietueet"; // "Data Structures"
      }
      else
      {
        return "Luokat"; // "Classes"
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorFinnish::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1199 of file translator_fi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Tietueet"; // "Data Structures"
      }
      else
      {
        return "Luokat"; // "Classes"
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorFinnish::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 226 of file translator_fi.h.
    { return "Luokkahierarkia"; } // "Class Hierarchy"
trClassHierarchy() [2/2]
virtual QCString TranslatorFinnish::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 226 of file translator_fi.h.
    { return "Luokkahierarkia"; } // "Class Hierarchy"
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorFinnish::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 285 of file translator_fi.h.
    { return "Tm periytymislista on ptasoltaan aakkostettu " // "This inheritance list is sorted roughly, "
             "mutta alijsenet on aakkostettu itsenisesti:"; // "but not completely, alphabetically:";
    }
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorFinnish::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 285 of file translator_fi.h.
    { return "Tm periytymislista on ptasoltaan aakkostettu " // "This inheritance list is sorted roughly, "
             "mutta alijsenet on aakkostettu itsenisesti:"; // "but not completely, alphabetically:";
    }
trCode() [1/2]
virtual QCString TranslatorFinnish::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 919 of file translator_fi.h.
    {
      return "koodi"; // "code"
    }
trCode() [2/2]
virtual QCString TranslatorFinnish::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 919 of file translator_fi.h.
    {
      return "koodi"; // "code"
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorFinnish::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 874 of file translator_fi.h.
    {
      return "Yhteistykaavio luokalle "+clName+":"; // "Collaboration diagram for "+clName+":"
    }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorFinnish::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 874 of file translator_fi.h.
    {
      return "Yhteistykaavio luokalle "+clName+":"; // "Collaboration diagram for "+clName+":"
    }
trCompoundIndex() [1/2]
virtual QCString TranslatorFinnish::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 416 of file translator_fi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Tietueluettelo"; // "Data Structure Index"
      }
      else
      {
        return "Luokkaluettelo"; // "Class Index"
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorFinnish::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 416 of file translator_fi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Tietueluettelo"; // "Data Structure Index"
      }
      else
      {
        return "Luokkaluettelo"; // "Class Index"
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorFinnish::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1687 of file translator_fi.h.
    { return "Tietotyyppien hakemisto"; } // "Data Type Index"
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorFinnish::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1687 of file translator_fi.h.
    { return "Tietotyyppien hakemisto"; } // "Data Type Index"
trCompoundList() [1/2]
virtual QCString TranslatorFinnish::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 230 of file translator_fi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Tietueet"; // "Data Structures"
      }
      else
      {
        return "Luokkalista"; // "Class List"
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorFinnish::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 230 of file translator_fi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Tietueet"; // "Data Structures"
      }
      else
      {
        return "Luokkalista"; // "Class List"
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorFinnish::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 300 of file translator_fi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Tss ovat tietueet lyhyen selitteen kanssa:"; // "Here are the data structures with brief descriptions:"
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Tss ovat luokat " // "Here are the classes
             "lyhyen selitteen kanssa:"; // "with brief descriptions:"
      }
      else
      {
        return "Tss ovat luokat, tietueet ja " // "Here are the classes, structs and "
             "yhdisteet lyhyen selitteen kanssa:"; // "unions with brief descriptions:"
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorFinnish::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 300 of file translator_fi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Tss ovat tietueet lyhyen selitteen kanssa:"; // "Here are the data structures with brief descriptions:"
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Tss ovat luokat " // "Here are the classes
             "lyhyen selitteen kanssa:"; // "with brief descriptions:"
      }
      else
      {
        return "Tss ovat luokat, tietueet ja " // "Here are the classes, structs and "
             "yhdisteet lyhyen selitteen kanssa:"; // "unions with brief descriptions:"
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorFinnish::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1660 of file translator_fi.h.
    { return "Tss ovat tietotyypit lyhyiden selitysten kanssa:"; } // "Here are the data types with brief descriptions:"
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorFinnish::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1660 of file translator_fi.h.
    { return "Tss ovat tietotyypit lyhyiden selitysten kanssa:"; } // "Here are the data types with brief descriptions:"
trCompoundListFortran() [1/2]
virtual QCString TranslatorFinnish::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1652 of file translator_fi.h.
    { return "Tietotyyppien lista"; } // "Data Types List"
trCompoundListFortran() [2/2]
virtual QCString TranslatorFinnish::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1652 of file translator_fi.h.
    { return "Tietotyyppien lista"; } // "Data Types List"
trCompoundMembers() [1/2]
virtual QCString TranslatorFinnish::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 247 of file translator_fi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Tietueen kentt"; // "Data Fields"
      }
      else
      {
        return "Luokan jsenet"; // "Class Members"
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorFinnish::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 247 of file translator_fi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Tietueen kentt"; // "Data Fields"
      }
      else
      {
        return "Luokan jsenet"; // "Class Members"
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorFinnish::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 320 of file translator_fi.h.
    {
      QCString result="Tss on lista kaikista "; // "Here is a list of all "
      if (!extractAll)
      {
        result+="dokumentoiduista "; // "documented "
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="tietuiden ja yhdisteiden kentist"; // "struct and union fields"
      }
      else
      {
        result+="luokkien jsenist"; // "class members"
      }
      result+=" linkitettyin "; // " with links to "
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="jokaisen kentn tietueen/yhdisteen dokumentaatioon:"; // "the struct/union documentation for each field:"
        }
        else
        {
          result+="jokaisen jsenen luokkadokumentaatioon:"; // "the class documentation for each member:"
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+= "tietueisiin/yhdisteisiin, joihin ne kuuluvat:"; // "the structures/unions they belong to:"
        }
        else
        {
          result+="luokkiin, joihin ne kuuluvat"; //"the classes they belong to:"
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorFinnish::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 320 of file translator_fi.h.
    {
      QCString result="Tss on lista kaikista "; // "Here is a list of all "
      if (!extractAll)
      {
        result+="dokumentoiduista "; // "documented "
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="tietuiden ja yhdisteiden kentist"; // "struct and union fields"
      }
      else
      {
        result+="luokkien jsenist"; // "class members"
      }
      result+=" linkitettyin "; // " with links to "
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="jokaisen kentn tietueen/yhdisteen dokumentaatioon:"; // "the struct/union documentation for each field:"
        }
        else
        {
          result+="jokaisen jsenen luokkadokumentaatioon:"; // "the class documentation for each member:"
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+= "tietueisiin/yhdisteisiin, joihin ne kuuluvat:"; // "the structures/unions they belong to:"
        }
        else
        {
          result+="luokkiin, joihin ne kuuluvat"; //"the classes they belong to:"
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorFinnish::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1664 of file translator_fi.h.
    {
      QCString result="Tss on lista kaikista "; // "Here is a list of all "
      if (!extractAll)
      {
        result+="dokumentoiduista "; // "documented "
      }
      result+="tietotyyppien jsenist"; // "data types members"
      result+=", sek linkit "; // " with links to "
      if (!extractAll)
      {
         result+="tietueen dokumentaatioon jokaiselle jsenelle"; // "the data structure documentation for each member"
      }
      else
      {
         result+="tietotyyppeihin, joihin ne kuuluvat:"; // "the data types they belong to:"
      }
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorFinnish::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1664 of file translator_fi.h.
    {
      QCString result="Tss on lista kaikista "; // "Here is a list of all "
      if (!extractAll)
      {
        result+="dokumentoiduista "; // "documented "
      }
      result+="tietotyyppien jsenist"; // "data types members"
      result+=", sek linkit "; // " with links to "
      if (!extractAll)
      {
         result+="tietueen dokumentaatioon jokaiselle jsenelle"; // "the data structure documentation for each member"
      }
      else
      {
         result+="tietotyyppeihin, joihin ne kuuluvat:"; // "the data types they belong to:"
      }
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorFinnish::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1656 of file translator_fi.h.
    { return "Kentt"; } // "Data Fields";
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorFinnish::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1656 of file translator_fi.h.
    { return "Kentt"; } // "Data Fields";
trCompoundReference() [1/2]
virtual QCString TranslatorFinnish::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 647 of file translator_fi.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" luokka"; break; // " Class"
        case ClassDef::Struct: result+=" tietue"; break; // " Struct"
        case ClassDef::Union: result+=" yhdiste"; break; // " Union"
        case ClassDef::Interface: result+=" rajapinta"; break; // " Interface"
        case ClassDef::Protocol: result+=" protokolla"; break; // " Protocol"
        case ClassDef::Category: result+=" kategoria"; break; // " Category"
        case ClassDef::Exception: result+=" poikkeus"; break; // " Exception"
        default: break;
      }
      if (isTemplate) result+="malli"; // " Template"
      result+="referenssi"; // " Reference"
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorFinnish::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 647 of file translator_fi.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" luokka"; break; // " Class"
        case ClassDef::Struct: result+=" tietue"; break; // " Struct"
        case ClassDef::Union: result+=" yhdiste"; break; // " Union"
        case ClassDef::Interface: result+=" rajapinta"; break; // " Interface"
        case ClassDef::Protocol: result+=" protokolla"; break; // " Protocol"
        case ClassDef::Category: result+=" kategoria"; break; // " Category"
        case ClassDef::Exception: result+=" poikkeus"; break; // " Exception"
        default: break;
      }
      if (isTemplate) result+="malli"; // " Template"
      result+="referenssi"; // " Reference"
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorFinnish::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1728 of file translator_fi.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" moduuli"; break; // " Module"
        case ClassDef::Struct: result+=" tyyppi"; break; // " Type"
        case ClassDef::Union: result+=" yhdiste"; break; // " Union"
        case ClassDef::Interface: result+=" rajapinta"; break; // " Interface"
        case ClassDef::Protocol: result+=" protokolla"; break; // " Protocol"
        case ClassDef::Category: result+=" kategoria"; break; // " Category"
        case ClassDef::Exception: result+=" poikkeus"; break; // " Exception"
        default: break;
      }
      if (isTemplate) result+="malli"; // " Template"
      result+="referenssi"; // " Reference"
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorFinnish::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1728 of file translator_fi.h.
    {
      QCString result=clName;
      switch(compType)
      {
        case ClassDef::Class: result+=" moduuli"; break; // " Module"
        case ClassDef::Struct: result+=" tyyppi"; break; // " Type"
        case ClassDef::Union: result+=" yhdiste"; break; // " Union"
        case ClassDef::Interface: result+=" rajapinta"; break; // " Interface"
        case ClassDef::Protocol: result+=" protokolla"; break; // " Protocol"
        case ClassDef::Category: result+=" kategoria"; break; // " Category"
        case ClassDef::Exception: result+=" poikkeus"; break; // " Exception"
        default: break;
      }
      if (isTemplate) result+="malli"; // " Template"
      result+="referenssi"; // " Reference"
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorFinnish::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 544 of file translator_fi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Tietueet"; // "Data Structures"
      }
      else
      {
        return "Luokat"; // "Classes"
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorFinnish::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 544 of file translator_fi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Tietueet"; // "Data Structures"
      }
      else
      {
        return "Luokat"; // "Classes"
      }
    }
References Config_getBool.
trConstructorDocumentation() [1/2]
virtual QCString TranslatorFinnish::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 884 of file translator_fi.h.
    {
      return "Rakentajien & purkajien dokumentaatio"; // "Constructor & Destructor Documentation";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorFinnish::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 884 of file translator_fi.h.
    {
      return "Rakentajien & purkajien dokumentaatio"; // "Constructor & Destructor Documentation";
    }
trDataTypes() [1/2]
virtual QCString TranslatorFinnish::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1711 of file translator_fi.h.
    { return "Tietotyypit"; } // "Data Types"
trDataTypes() [2/2]
virtual QCString TranslatorFinnish::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1711 of file translator_fi.h.
    { return "Tietotyypit"; } // "Data Types"
trDate() [1/2]
virtual QCString TranslatorFinnish::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 586 of file translator_fi.h.
    { return "Pivys"; } // "Date"
trDate() [2/2]
virtual QCString TranslatorFinnish::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 586 of file translator_fi.h.
    { return "Pivys"; } // "Date"
trDayOfWeek() [1/2]
virtual QCString TranslatorFinnish::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1843 of file translator_fi.h.
    {
      static const char *days_short[] = { "ma", "ti", "ke", "to", "pe", "la", "su" };
      static const char *days_full[] = { "maanantai", "tiistai", "keskiviikko", "torstai", "perjantai", "lauantai", "sunnuntai" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayOfWeek() [2/2]
virtual QCString TranslatorFinnish::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1843 of file translator_fi.h.
    {
      static const char *days_short[] = { "ma", "ti", "ke", "to", "pe", "la", "su" };
      static const char *days_full[] = { "maanantai", "tiistai", "keskiviikko", "torstai", "perjantai", "lauantai", "sunnuntai" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod() [1/2]
virtual QCString TranslatorFinnish::trDayPeriod (int period) [inline], [virtual]
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1859 of file translator_fi.h.
    {
      static const char *dayPeriod[] = { "ap.", "ip." };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorFinnish::trDayPeriod (int period) [inline], [virtual]
Reimplemented from TranslatorAdapter_1_7_5.
Definition at line 1859 of file translator_fi.h.
    {
      static const char *dayPeriod[] = { "ap.", "ip." };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorFinnish::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 851 of file translator_fi.h.
    {
      return "Mrittely tiedoston @1 rivill @0."; // "Definition at line @0 of file @1."
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorFinnish::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 851 of file translator_fi.h.
    {
      return "Mrittely tiedoston @1 rivill @0."; // "Definition at line @0 of file @1."
    }
trDefinedIn() [1/2]
virtual QCString TranslatorFinnish::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 214 of file translator_fi.h.
    { return "mritelty"; } // "defined in"
trDefinedIn() [2/2]
virtual QCString TranslatorFinnish::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 214 of file translator_fi.h.
    { return "mritelty"; } // "defined in"
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorFinnish::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 855 of file translator_fi.h.
    {
      return "Mrittely tiedostossa @0."; // "Definition in file @0."
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorFinnish::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 855 of file translator_fi.h.
    {
      return "Mrittely tiedostossa @0."; // "Definition in file @0."
    }
trDefineDocumentation() [1/2]
virtual QCString TranslatorFinnish::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 514 of file translator_fi.h.
    { return "Mritysten dokumentointi"; } // "Define Documentation"
trDefineDocumentation() [2/2]
virtual QCString TranslatorFinnish::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 514 of file translator_fi.h.
    { return "Mritysten dokumentointi"; } // "Define Documentation"
trDefines() [1/2]
virtual QCString TranslatorFinnish::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 478 of file translator_fi.h.
    { return "Mrittelyt"; } // "Defines"
trDefines() [2/2]
virtual QCString TranslatorFinnish::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 478 of file translator_fi.h.
    { return "Mrittelyt"; } // "Defines"
trDefineValue() [1/2]
virtual QCString TranslatorFinnish::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1226 of file translator_fi.h.
    {
      return "Arvo:"; // "Value:"
    }
trDefineValue() [2/2]
virtual QCString TranslatorFinnish::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1226 of file translator_fi.h.
    {
      return "Arvo:"; // "Value:"
    }
trDeprecated() [1/2]
virtual QCString TranslatorFinnish::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 864 of file translator_fi.h.
    {
      return "Vanhentunut"; // "Deprecated"
    }
trDeprecated() [2/2]
virtual QCString TranslatorFinnish::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 864 of file translator_fi.h.
    {
      return "Vanhentunut"; // "Deprecated"
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorFinnish::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1435 of file translator_fi.h.
    {
      return "Vanhentuneiden lista"; // "Deprecated List"
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorFinnish::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1435 of file translator_fi.h.
    {
      return "Vanhentuneiden lista"; // "Deprecated List"
    }
trDetailedDescription() [1/2]
virtual QCString TranslatorFinnish::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 141 of file translator_fi.h.
    { return "Yksityiskohtainen selite"; } // "Detailed Description"
trDetailedDescription() [2/2]
virtual QCString TranslatorFinnish::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 141 of file translator_fi.h.
    { return "Yksityiskohtainen selite"; } // "Detailed Description"
trDir() [1/2]
virtual QCString TranslatorFinnish::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1603 of file translator_fi.h.
    {
      QCString result((first_capital ? "Hakemisto" : "hakemisto")); // "Director" / "director"
      if (singular) result+=""; else result+="t"; // "+y" / "+ies"
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorFinnish::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1603 of file translator_fi.h.
    {
      QCString result((first_capital ? "Hakemisto" : "hakemisto")); // "Director" / "director"
      if (singular) result+=""; else result+="t"; // "+y" / "+ies"
      return result;
    }
trDirDocumentation() [1/2]
virtual QCString TranslatorFinnish::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1584 of file translator_fi.h.
    { return "Hakemistojen dokumentaatio"; } // "Directory Documentation"
trDirDocumentation() [2/2]
virtual QCString TranslatorFinnish::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1584 of file translator_fi.h.
    { return "Hakemistojen dokumentaatio"; } // "Directory Documentation"
trDirectories() [1/2]
virtual QCString TranslatorFinnish::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1590 of file translator_fi.h.
    { return "Hakemistot"; } // "Directories"
trDirectories() [2/2]
virtual QCString TranslatorFinnish::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1590 of file translator_fi.h.
    { return "Hakemistot"; } // "Directories"
trDirIndex() [1/2]
virtual QCString TranslatorFinnish::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1578 of file translator_fi.h.
    { return "Hakemistohierarkia"; } // "Directory Hierarchy"
trDirIndex() [2/2]
virtual QCString TranslatorFinnish::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1578 of file translator_fi.h.
    { return "Hakemistohierarkia"; } // "Directory Hierarchy"
trDirReference() [1/2]
virtual QCString TranslatorFinnish::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1596 of file translator_fi.h.
    { QCString result=dirName; result+=" hakemistoreferenssi"; return result; }
trDirReference() [2/2]
virtual QCString TranslatorFinnish::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1596 of file translator_fi.h.
    { QCString result=dirName; result+=" hakemistoreferenssi"; return result; }
trDocumentation() [1/2]
virtual QCString TranslatorFinnish::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 398 of file translator_fi.h.
    { return "Dokumentaatio"; } // "Documentation"
trDocumentation() [2/2]
virtual QCString TranslatorFinnish::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 398 of file translator_fi.h.
    { return "Dokumentaatio"; } // "Documentation"
trEnumerations() [1/2]
virtual QCString TranslatorFinnish::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 490 of file translator_fi.h.
    { return "Luettelotyypit"; } // "Enumerations"
trEnumerations() [2/2]
virtual QCString TranslatorFinnish::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 490 of file translator_fi.h.
    { return "Luettelotyypit"; } // "Enumerations"
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorFinnish::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 526 of file translator_fi.h.
    { return "Luettelotyyppien dokumentaatio"; } // "Enumeration Type Documentation"
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorFinnish::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 526 of file translator_fi.h.
    { return "Luettelotyyppien dokumentaatio"; } // "Enumeration Type Documentation"
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorFinnish::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1640 of file translator_fi.h.
    { return "Luettelotyypin dokumentaatio"; } // "Enumerator Documentation"
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorFinnish::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1640 of file translator_fi.h.
    { return "Luettelotyypin dokumentaatio"; } // "Enumerator Documentation"
trEnumerationValues() [1/2]
virtual QCString TranslatorFinnish::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 508 of file translator_fi.h.
    { return "Luettelotyyppien arvot"; } // "Enumerator"
trEnumerationValues() [2/2]
virtual QCString TranslatorFinnish::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 508 of file translator_fi.h.
    { return "Luettelotyyppien arvot"; } // "Enumerator"
trEnumName() [1/2]
virtual QCString TranslatorFinnish::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 206 of file translator_fi.h.
    { return "luettelotyypin nimi"; } // "enum name"
trEnumName() [2/2]
virtual QCString TranslatorFinnish::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 206 of file translator_fi.h.
    { return "luettelotyypin nimi"; } // "enum name"
trEnumValue() [1/2]
virtual QCString TranslatorFinnish::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 210 of file translator_fi.h.
    { return "luettelotyypin arvo"; } // "enum value"
trEnumValue() [2/2]
virtual QCString TranslatorFinnish::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 210 of file translator_fi.h.
    { return "luettelotyypin arvo"; } // "enum value"
trEventDocumentation() [1/2]
virtual QCString TranslatorFinnish::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1452 of file translator_fi.h.
    {
      return "Tapahtumien dokumentaatio"; // "Event Documentation"
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorFinnish::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1452 of file translator_fi.h.
    {
      return "Tapahtumien dokumentaatio"; // "Event Documentation"
    }
trEvents() [1/2]
virtual QCString TranslatorFinnish::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1447 of file translator_fi.h.
    {
      return "Tapahtumat"; // "Events"
    }
trEvents() [2/2]
virtual QCString TranslatorFinnish::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1447 of file translator_fi.h.
    {
      return "Tapahtumat"; // "Events"
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorFinnish::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 468 of file translator_fi.h.
    { return "Esimerkkien dokumentaatio"; } // "Example Documentation"
trExampleDocumentation() [2/2]
virtual QCString TranslatorFinnish::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 468 of file translator_fi.h.
    { return "Esimerkkien dokumentaatio"; } // "Example Documentation"
trExamples() [1/2]
virtual QCString TranslatorFinnish::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 277 of file translator_fi.h.
    { return "Esimerkit"; } // "Examples"
trExamples() [2/2]
virtual QCString TranslatorFinnish::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 277 of file translator_fi.h.
    { return "Esimerkit"; } // "Examples"
trExamplesDescription() [1/2]
virtual QCString TranslatorFinnish::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 384 of file translator_fi.h.
    { return "Tss on lista kaikista esimerkeist:"; } // "Here is a list of all examples:"
trExamplesDescription() [2/2]
virtual QCString TranslatorFinnish::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 384 of file translator_fi.h.
    { return "Tss on lista kaikista esimerkeist:"; } // "Here is a list of all examples:"
trExceptions() [1/2]
virtual QCString TranslatorFinnish::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 602 of file translator_fi.h.
    { return "Poikkeukset"; } // "Exceptions"
trExceptions() [2/2]
virtual QCString TranslatorFinnish::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 602 of file translator_fi.h.
    { return "Poikkeukset"; } // "Exceptions"
trFile() [1/2]
virtual QCString TranslatorFinnish::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1310 of file translator_fi.h.
    {
      QCString result((first_capital ? "Tiedosto" : "tiedosto")); // "File" / "file"
      if (!singular) result+="t"; // "+s" -> "Files" / "files"
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorFinnish::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1310 of file translator_fi.h.
    {
      QCString result((first_capital ? "Tiedosto" : "tiedosto")); // "File" / "file"
      if (!singular) result+="t"; // "+s" -> "Files" / "files"
      return result;
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorFinnish::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 462 of file translator_fi.h.
    { return "Tiedostojen dokumentaatio"; } // "File Documentation"
trFileDocumentation() [2/2]
virtual QCString TranslatorFinnish::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 462 of file translator_fi.h.
    { return "Tiedostojen dokumentaatio"; } // "File Documentation"
trFileIndex() [1/2]
virtual QCString TranslatorFinnish::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 431 of file translator_fi.h.
    { return "Tiedostoluettelo"; } // "File Index"
trFileIndex() [2/2]
virtual QCString TranslatorFinnish::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 431 of file translator_fi.h.
    { return "Tiedostoluettelo"; } // "File Index"
trFileList() [1/2]
virtual QCString TranslatorFinnish::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 243 of file translator_fi.h.
    { return "Tiedostolista"; } // "File List"
trFileList() [2/2]
virtual QCString TranslatorFinnish::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 243 of file translator_fi.h.
    { return "Tiedostolista"; } // "File List"
trFileListDescription() [1/2]
virtual QCString TranslatorFinnish::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 291 of file translator_fi.h.
    {
      QCString result="Tss on lista kaikista ";
      if (!extractAll) result+="dokumentoiduista "; // "documented "
      result+="tiedostoista lyhyen selitteen kanssa:"; // "files with brief descriptions:"
      return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorFinnish::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 291 of file translator_fi.h.
    {
      QCString result="Tss on lista kaikista ";
      if (!extractAll) result+="dokumentoiduista "; // "documented "
      result+="tiedostoista lyhyen selitteen kanssa:"; // "files with brief descriptions:"
      return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorFinnish::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 260 of file translator_fi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globaalit"; // "Globals"
      }
      else
      {
        return "Tiedoston jsenet"; // "File Members"
      }
    }
References Config_getBool.
trFileMembers() [2/2]
virtual QCString TranslatorFinnish::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 260 of file translator_fi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globaalit"; // "Globals"
      }
      else
      {
        return "Tiedoston jsenet"; // "File Members"
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
virtual QCString TranslatorFinnish::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 362 of file translator_fi.h.
    {
      QCString result="Tss on lista kaikista "; // "Here is a list of all "
      if (!extractAll) result+="dokumentoiduista "; // "documented "
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funktioista, muuttujista, mrittelyist, luettelotyypeist ja tyyppimrittelyist"; // "functions, variables, defines, enums, and typedefs"
      }
      else
      {
        result+="tiedoston jsenist"; // "file members"
      }
      result+=" linkitettyin "; // " with links to "
      if (extractAll)
        result+="tiedostoihin, joihin ne kuuluvat:"; // "the files they belong to:"
      else
        result+="dokumentaatioon:"; // "the documentation:"
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorFinnish::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 362 of file translator_fi.h.
    {
      QCString result="Tss on lista kaikista "; // "Here is a list of all "
      if (!extractAll) result+="dokumentoiduista "; // "documented "
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funktioista, muuttujista, mrittelyist, luettelotyypeist ja tyyppimrittelyist"; // "functions, variables, defines, enums, and typedefs"
      }
      else
      {
        result+="tiedoston jsenist"; // "file members"
      }
      result+=" linkitettyin "; // " with links to "
      if (extractAll)
        result+="tiedostoihin, joihin ne kuuluvat:"; // "the files they belong to:"
      else
        result+="dokumentaatioon:"; // "the documentation:"
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorFinnish::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 669 of file translator_fi.h.
    {
      QCString result=fileName;
      result+=" tiedostoreferenssi"; // " File Reference"
      return result;
    }
trFileReference() [2/2]
virtual QCString TranslatorFinnish::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 669 of file translator_fi.h.
    {
      QCString result=fileName;
      result+=" tiedostoreferenssi"; // " File Reference"
      return result;
    }
trFriends() [1/2]
virtual QCString TranslatorFinnish::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 629 of file translator_fi.h.
    { return "Ystvt"; } // "Friends"
trFriends() [2/2]
virtual QCString TranslatorFinnish::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 629 of file translator_fi.h.
    { return "Ystvt"; } // "Friends"
trFunctionDocumentation() [1/2]
virtual QCString TranslatorFinnish::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 532 of file translator_fi.h.
    { return "Funktioiden dokumentaatio"; } // "Function Documentation"
trFunctionDocumentation() [2/2]
virtual QCString TranslatorFinnish::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 532 of file translator_fi.h.
    { return "Funktioiden dokumentaatio"; } // "Function Documentation"
trFunctions() [1/2]
virtual QCString TranslatorFinnish::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 496 of file translator_fi.h.
    { return "Funktiot"; } // "Functions"
trFunctions() [2/2]
virtual QCString TranslatorFinnish::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 496 of file translator_fi.h.
    { return "Funktiot"; } // "Functions"
trGeneratedAt() [1/2]
virtual QCString TranslatorFinnish::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 559 of file translator_fi.h.
    {
        // funktio on hiukan vaikea knt prepositioihin sidotun rakenteen vuoksi.
        // Muutetaan siis lauserakennetta suomalaisemmaksi
        // Generated on $date for $project by:
        // -> Generated for $project on $date by:
      QCString result="Generoinut ";
      if (!projName.isEmpty()) result+="projektille "+projName+" ";
      result+=date+" ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorFinnish::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 559 of file translator_fi.h.
    {
        // funktio on hiukan vaikea knt prepositioihin sidotun rakenteen vuoksi.
        // Muutetaan siis lauserakennetta suomalaisemmaksi
        // Generated on $date for $project by:
        // -> Generated for $project on $date by:
      QCString result="Generoinut ";
      if (!projName.isEmpty()) result+="projektille "+projName+" ";
      result+=date+" ";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorFinnish::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 193 of file translator_fi.h.
    { QCString result="Automaattisesti luotu Doxygenilla "
                      "lhdekoodista projektille "+s; // "Generated automatically by Doxygen" ... "for" ... "from the sourcecode"
      //if (s) result+=" voor "+s;
      // tss on ongelma, kuinka taivuttaa parametria, esim. "Jcad"+"in"; "IFC2VRML konversio"+"n"
      // mutta ratkaistaan ongelma ktevsti kaksoispisteell -> "Jcad:n" / "IFC2VRML konversio:n"
      // lopputulos on vhemmn kkk ja tysin luettava, mutta ei kuitenkaan tydellinen.
      //
      // kierretn ongelma taivuttamalla sanaa projekti :)
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorFinnish::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 193 of file translator_fi.h.
    { QCString result="Automaattisesti luotu Doxygenilla "
                      "lhdekoodista projektille "+s; // "Generated automatically by Doxygen" ... "for" ... "from the sourcecode"
      //if (s) result+=" voor "+s;
      // tss on ongelma, kuinka taivuttaa parametria, esim. "Jcad"+"in"; "IFC2VRML konversio"+"n"
      // mutta ratkaistaan ongelma ktevsti kaksoispisteell -> "Jcad:n" / "IFC2VRML konversio:n"
      // lopputulos on vhemmn kkk ja tysin luettava, mutta ei kuitenkaan tydellinen.
      //
      // kierretn ongelma taivuttamalla sanaa projekti :)
      return result;
    }
References s.
trGeneratedBy() [1/2]
virtual QCString TranslatorFinnish::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 606 of file translator_fi.h.
    { return "Generoinut"; } // "Generated by"
trGeneratedBy() [2/2]
virtual QCString TranslatorFinnish::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 606 of file translator_fi.h.
    { return "Generoinut"; } // "Generated by"
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorFinnish::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 807 of file translator_fi.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentaatio tlle "; // "The documentation for this "
      switch(compType)
      {
        case ClassDef::Class: result+="luokalle"; break; // "class"
        case ClassDef::Struct: result+="tietueelle"; break; // "struct"
        case ClassDef::Union: result+="yhdisteelle"; break; // "union"
        case ClassDef::Interface: result+="rajapinnalle"; break; // "interface"
        case ClassDef::Protocol: result+="protokollalle"; break; // "protocol"
        case ClassDef::Category: result+="kategorialle"; break; // "category"
        case ClassDef::Exception: result+="poikkeukselle"; break; // "exception"
        default: break;
      }
      if (single) result+=" luotiin seuraavasta tiedostosta:"; // " was generated from the following file"
      else result+=" luotiin seuraavista tiedostoista:"; // ":" or "s:"
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorFinnish::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 807 of file translator_fi.h.
    { // here s is one of " Class", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentaatio tlle "; // "The documentation for this "
      switch(compType)
      {
        case ClassDef::Class: result+="luokalle"; break; // "class"
        case ClassDef::Struct: result+="tietueelle"; break; // "struct"
        case ClassDef::Union: result+="yhdisteelle"; break; // "union"
        case ClassDef::Interface: result+="rajapinnalle"; break; // "interface"
        case ClassDef::Protocol: result+="protokollalle"; break; // "protocol"
        case ClassDef::Category: result+="kategorialle"; break; // "category"
        case ClassDef::Exception: result+="poikkeukselle"; break; // "exception"
        default: break;
      }
      if (single) result+=" luotiin seuraavasta tiedostosta:"; // " was generated from the following file"
      else result+=" luotiin seuraavista tiedostoista:"; // ":" or "s:"
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorFinnish::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1796 of file translator_fi.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentaatio tlle "; // "The documentation for this "
      switch(compType)
      {
        case ClassDef::Class: result+="moduulille"; break; // "module"
        case ClassDef::Struct: result+="tyypille"; break; // "type"
        case ClassDef::Union: result+="yhdisteelle"; break; // "union"
        case ClassDef::Interface: result+="rajapinnalle"; break; // "interface"
        case ClassDef::Protocol: result+="protokollalle"; break; // "protocol"
        case ClassDef::Category: result+="kategorialle"; break; // "category"
        case ClassDef::Exception: result+="poikkeukselle"; break; // "exception"
        default: break;
      }
      result+=" luotiin "; // " was generated from the following file"
      if (single) result+="seuraavasta tiedostosta:"; else result+="seuraavista tiedostoista:"; // ":" / "s:"
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorFinnish::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1796 of file translator_fi.h.
    { // here s is one of " Module", " Struct" or " Union"
      // single is true implies a single file
      QCString result="Dokumentaatio tlle "; // "The documentation for this "
      switch(compType)
      {
        case ClassDef::Class: result+="moduulille"; break; // "module"
        case ClassDef::Struct: result+="tyypille"; break; // "type"
        case ClassDef::Union: result+="yhdisteelle"; break; // "union"
        case ClassDef::Interface: result+="rajapinnalle"; break; // "interface"
        case ClassDef::Protocol: result+="protokollalle"; break; // "protocol"
        case ClassDef::Category: result+="kategorialle"; break; // "category"
        case ClassDef::Exception: result+="poikkeukselle"; break; // "exception"
        default: break;
      }
      result+=" luotiin "; // " was generated from the following file"
      if (single) result+="seuraavasta tiedostosta:"; else result+="seuraavista tiedostoista:"; // ":" / "s:"
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorFinnish::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1365 of file translator_fi.h.
    {
      QCString result((first_capital ? "Globaali" : "globaali")); // "Global" / "global"
      if (!singular) result+="t"; // "+s"
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorFinnish::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1365 of file translator_fi.h.
    {
      QCString result((first_capital ? "Globaali" : "globaali")); // "Global" / "global"
      if (!singular) result+="t"; // "+s"
      return result;
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorFinnish::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 894 of file translator_fi.h.
    {
      return "Siirry tmn tiedoston dokumentaatioon."; // "Go to the documentation of this file."
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorFinnish::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 894 of file translator_fi.h.
    {
      return "Siirry tmn tiedoston dokumentaatioon."; // "Go to the documentation of this file."
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorFinnish::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 927 of file translator_fi.h.
    {
      return "Siirry graafiseen luokkahierarkiaan"; // "Go to the graphical class hierarchy"
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorFinnish::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 927 of file translator_fi.h.
    {
      return "Siirry graafiseen luokkahierarkiaan"; // "Go to the graphical class hierarchy"
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorFinnish::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 889 of file translator_fi.h.
    {
      return "Siirry tmn tiedoston lhdekoodiin."; // "Go to the source code of this file."
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorFinnish::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 889 of file translator_fi.h.
    {
      return "Siirry tmn tiedoston lhdekoodiin."; // "Go to the source code of this file."
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorFinnish::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 931 of file translator_fi.h.
    {
      return "Siirry tekstimuotoiseen luokkahierarkiaan"; // "Go to the textual class hierarchy"
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorFinnish::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 931 of file translator_fi.h.
    {
      return "Siirry tekstimuotoiseen luokkahierarkiaan"; // "Go to the textual class hierarchy"
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorFinnish::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 923 of file translator_fi.h.
    {
      return "Graafinen luokkahierarkia"; // "Graphical Class Hierarchy"
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorFinnish::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 923 of file translator_fi.h.
    {
      return "Graafinen luokkahierarkia"; // "Graphical Class Hierarchy"
    }
trGroup() [1/2]
virtual QCString TranslatorFinnish::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1332 of file translator_fi.h.
    {
      QCString result((first_capital ? "Ryhm" : "ryhm")); // "Group" / "group"
      if (!singular) result+="t"; // "+s"
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorFinnish::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1332 of file translator_fi.h.
    {
      QCString result((first_capital ? "Ryhm" : "ryhm")); // "Group" / "group"
      if (!singular) result+="t"; // "+s"
      return result;
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorFinnish::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 410 of file translator_fi.h.
    { return "Hierarkinen luettelo"; } // "Hierarchical Index"
trHierarchicalIndex() [2/2]
virtual QCString TranslatorFinnish::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 410 of file translator_fi.h.
    { return "Hierarkinen luettelo"; } // "Hierarchical Index"
trImplementedFromList() [1/2]
virtual QCString TranslatorFinnish::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1403 of file translator_fi.h.
    {
      return "Toteuttaa luokan "+trWriteList(numEntries)+"."; // "Implements "
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorFinnish::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1403 of file translator_fi.h.
    {
      return "Toteuttaa luokan "+trWriteList(numEntries)+"."; // "Implements "
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorFinnish::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1411 of file translator_fi.h.
    {
      return "Toteutettu luokassa "+trWriteList(numEntries)+"."; // "Implemented in "
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorFinnish::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1411 of file translator_fi.h.
    {
      return "Toteutettu luokassa "+trWriteList(numEntries)+"."; // "Implemented in "
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorFinnish::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 1024 of file translator_fi.h.
    {
      return "Tm kaavio nytt, mitk tiedostot suorasti "
             "tai epsuorasti sisllyttvt tmn tiedoston";
             // "This graph shows which files directly or "
             // "indirectly include this file:"
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorFinnish::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 1024 of file translator_fi.h.
    {
      return "Tm kaavio nytt, mitk tiedostot suorasti "
             "tai epsuorasti sisllyttvt tmn tiedoston";
             // "This graph shows which files directly or "
             // "indirectly include this file:"
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorFinnish::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 879 of file translator_fi.h.
    {
    }
trInclDepGraph() [2/2]
virtual QCString TranslatorFinnish::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 879 of file translator_fi.h.
    {
    }
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorFinnish::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 187 of file translator_fi.h.
    { return ", sislten kaikki perityt jsenet."; } // ", including all inherited members."
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorFinnish::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 187 of file translator_fi.h.
    { return ", sislten kaikki perityt jsenet."; } // ", including all inherited members."
trInheritedByList() [1/2]
virtual QCString TranslatorFinnish::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 741 of file translator_fi.h.
    {
      return QCString("Periytetn ")+(numEntries > 1 ? "luokissa " : "luokassa ")+trWriteList(numEntries)+"."; // "Inherited by "
    }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorFinnish::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 741 of file translator_fi.h.
    {
      return QCString("Periytetn ")+(numEntries > 1 ? "luokissa " : "luokassa ")+trWriteList(numEntries)+"."; // "Inherited by "
    }
References trWriteList().
trInheritsList() [1/2]
virtual QCString TranslatorFinnish::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 733 of file translator_fi.h.
    {
      return QCString("Periytyy ")+(numEntries > 1 ? "luokista " : "luokasta ")+trWriteList(numEntries)+"."; // "Inherits "
    }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorFinnish::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 733 of file translator_fi.h.
    {
      return QCString("Periytyy ")+(numEntries > 1 ? "luokista " : "luokasta ")+trWriteList(numEntries)+"."; // "Inherits "
    }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorFinnish::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 914 of file translator_fi.h.
    {
      return "Alkuarvo:"; // "Initial value:"
    }
trInitialValue() [2/2]
virtual QCString TranslatorFinnish::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 914 of file translator_fi.h.
    {
      return "Alkuarvo:"; // "Initial value:"
    }
trInvariant() [1/2]
virtual QCString TranslatorFinnish::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 909 of file translator_fi.h.
    {
      return "Invariantti"; // vai "Pysyvisvittm"? "Invariant"
    }
trInvariant() [2/2]
virtual QCString TranslatorFinnish::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 909 of file translator_fi.h.
    {
      return "Invariantti"; // vai "Pysyvisvittm"? "Invariant"
    }
trISOLang() [1/2]
virtual QCString TranslatorFinnish::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 122 of file translator_fi.h.
    {
      return "fi";
    }
trISOLang() [2/2]
virtual QCString TranslatorFinnish::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 122 of file translator_fi.h.
    {
      return "fi";
    }
trLegend() [1/2]
virtual QCString TranslatorFinnish::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1159 of file translator_fi.h.
    {
      return "selite"; // "legend"
    }
trLegend() [2/2]
virtual QCString TranslatorFinnish::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1159 of file translator_fi.h.
    {
      return "selite"; // "legend"
    }
trLegendDocs() [1/2]
virtual QCString TranslatorFinnish::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 1049 of file translator_fi.h.
    {
      return
        "Tm sivu selitt, kuinka doxygenin luomia kaavioita tulkitaan.<p>\n"
        // "This page explains how to interpret the graphs that are generated "
        // "by doxygen.<p>\n"
        "Ajattele seuraavaa esimerkki:\n"
        // "Consider the following example:\n"
        "\\code\n"
        "/*! Nkymtn luokka katkaisun vuoksi */\n"
        // "/*! Invisible class because of truncation */\n"
        "class Nakymaton { };\n\n"
        // "class Invisible { };\n\n"
        "/*! Katkaistu luokka, periytymissuhde on piilotettu */\n"
        // "/*! Truncated class, inheritance relation is hidden */\n"
        "class Katkaistu : public Nakymaton { };\n\n"
        // "class Truncated : public Invisible { };\n\n"
        "/* Luokkaa ei ole dokumentoitu doxygen-kommenteilla */\n"
        // "/* Class not documented with doxygen comments */\n"
        "class Dokumentoimaton {};\n\n"
        // "class Undocumented { };\n\n"
        "/*! Julkista periyttmist kytten periytetty luokka */\n"
        // "/*! Class that is inherited using public inheritance */\n"
        "class JulkinenKanta : public Katkaistu { };\n\n"
        // "class PublicBase : public Truncated { };\n\n"
        "/*! Malliluokka */\n"
        // "/*! A template class */\n"
        "template<class T> class Malli { };\n\n"
        // "template<class T> class Templ { };\n\n"
        "/*! Suojeltua periytymist kytten periytetty luokka */\n"
        // "/*! Class that is inherited using protected inheritance */\n"
        "class SuojeltuKanta { };\n\n"
        // "class ProtectedBase { };\n\n"
        "/*! Yksityist periytymist kytten periytetty luokka */\n"
        // "/*! Class that is inherited using private inheritance */\n"
        "class YksityisKanta { };\n\n"
        // "class PrivateBase { };\n\n"
        "/*! Luokka jota periytetty luokka kytt */\n"
        // "/*! Class that is used by the Inherited class */\n"
        "class Kaytetty { };\n\n"
        // "class Used { };\n\n"
        "/*! Kantaluokka joka periytyy useasta muusta luokasta */\n"
        // "/*! Super class that inherits a number of other classes */\n"
        "class Periytetty : public JulkinenKanta,\n"
        " : protected SuojeltuKanta,\n"
        " : private YksityisKanta,\n"
        " : public Dokumentoimaton,\n"
        " : public Malli<int>\n"
        "{\n"
        " private:\n"
        " Kaytetty *m_kaytettyLuokka;\n"
        "}\n"
        // "class Inherited : public PublicBase,\n"
        // " protected ProtectedBase,\n"
        // " private PrivateBase,\n"
        // " public Undocumented,\n"
        // " public Templ<int>\n"
        // "{\n"
        // " private:\n"
        // " Used *m_usedClass;\n"
        // "};\n"
        "\\endcode\n"
        "Tuloksena on seuraavanlainen kaavio:"
        //"This will result in the following graph:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "Yllolevassa kaaviossa laatikoilla on seuraavat merkitykset\n:"
        // "The boxes in the above graph have the following meaning:\n"
        "<ul>\n"
        "<li>Tytetty harmaa laatikko esitt tietuetta tai luokkaa, jolle "
        // "<li>%A filled gray box represents the struct or class for which the "
        "kaavio on luotu.\n"
        // "graph is generated.\n"
        "<li>Mustareunainen laatikko merkitsee dokumentoitua tietuetta tai luokkaa.\n"
        // "<li>%A box with a black border denotes a documented struct or class.\n"
        "<li>Harmaareunainen laatikko merkitsee dokumentoimatonta tietuetta tai luokkaa.\n"
        // "<li>%A box with a grey border denotes an undocumented struct or class.\n"
        "<li>Punareunainen laatikko merkistee dokumentoitua luokkaa tai structia "
        // "<li>%A box with a red border denotes a documented struct or class for"
        "jolle ei nytet kaikkia periytymis-/sisllyssuhteita. Kaavio "
        // "which not all inheritance/containment relations are shown. %A graph is "
        "katkaistaan, jos se ei mahdu mriteltyjen rajojen sisn.\n"
        // "truncated if it does not fit within the specified boundaries.\n"
        "</ul>\n"
        "Nuolilla on seuraavat merkitykset:\n"
        // "The arrows have the following meaning:\n"
        "<ul>\n"
        "<li>Tummansinist nuolta kytetn osoittamaan julkista periytymis"
        // "<li>%A dark blue arrow is used to visualize a public inheritance "
        "suhdetta kahden luokan vlill.\n"
        // "relation between two classes.\n"
        "<li>Tummanvihre nuolta kytetn suojellussa periytymisess.\n"
        // "<li>%A dark green arrow is used for protected inheritance.\n"
        "<li>Tummanpunaista nuolta kytetn yksityisess periytymisess.\n"
        // "<li>%A dark red arrow is used for private inheritance.\n"
        "<li>Purppuranvrist katkoviivaa kytetn, jos luokka sisltyy tai "
        // "<li>%A purple dashed arrow is used if a class is contained or used "
        "on toisen luokan kyttm. Nuoli nimetn sill muuttujalla/muuttujilla "
        // "by another class. The arrow is labeled with the variable(s) "
        "jonka lpi osoitettua luokkaa tai tietuetta kytetn.\n"
        // "through which the pointed class or struct is accessible.\n"
        "<li>Keltainen katkoviivalla piirretty nuoli merkitsee suhdetta mallin esiintymn ja "
        // "<li>%A yellow dashed arrow denotes a relation between a template instance and "
        "malliluokan vlill. Nuoli nimetn "
        // "the template class it was instantiated from. The arrow is labeled with "
        "mallin esiintymn malliparametrilla.\n"
        // "the template parameters of the instance.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorFinnish::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 1049 of file translator_fi.h.
    {
      return
        "Tm sivu selitt, kuinka doxygenin luomia kaavioita tulkitaan.<p>\n"
        // "This page explains how to interpret the graphs that are generated "
        // "by doxygen.<p>\n"
        "Ajattele seuraavaa esimerkki:\n"
        // "Consider the following example:\n"
        "\\code\n"
        "/*! Nkymtn luokka katkaisun vuoksi */\n"
        // "/*! Invisible class because of truncation */\n"
        "class Nakymaton { };\n\n"
        // "class Invisible { };\n\n"
        "/*! Katkaistu luokka, periytymissuhde on piilotettu */\n"
        // "/*! Truncated class, inheritance relation is hidden */\n"
        "class Katkaistu : public Nakymaton { };\n\n"
        // "class Truncated : public Invisible { };\n\n"
        "/* Luokkaa ei ole dokumentoitu doxygen-kommenteilla */\n"
        // "/* Class not documented with doxygen comments */\n"
        "class Dokumentoimaton {};\n\n"
        // "class Undocumented { };\n\n"
        "/*! Julkista periyttmist kytten periytetty luokka */\n"
        // "/*! Class that is inherited using public inheritance */\n"
        "class JulkinenKanta : public Katkaistu { };\n\n"
        // "class PublicBase : public Truncated { };\n\n"
        "/*! Malliluokka */\n"
        // "/*! A template class */\n"
        "template<class T> class Malli { };\n\n"
        // "template<class T> class Templ { };\n\n"
        "/*! Suojeltua periytymist kytten periytetty luokka */\n"
        // "/*! Class that is inherited using protected inheritance */\n"
        "class SuojeltuKanta { };\n\n"
        // "class ProtectedBase { };\n\n"
        "/*! Yksityist periytymist kytten periytetty luokka */\n"
        // "/*! Class that is inherited using private inheritance */\n"
        "class YksityisKanta { };\n\n"
        // "class PrivateBase { };\n\n"
        "/*! Luokka jota periytetty luokka kytt */\n"
        // "/*! Class that is used by the Inherited class */\n"
        "class Kaytetty { };\n\n"
        // "class Used { };\n\n"
        "/*! Kantaluokka joka periytyy useasta muusta luokasta */\n"
        // "/*! Super class that inherits a number of other classes */\n"
        "class Periytetty : public JulkinenKanta,\n"
        " : protected SuojeltuKanta,\n"
        " : private YksityisKanta,\n"
        " : public Dokumentoimaton,\n"
        " : public Malli<int>\n"
        "{\n"
        " private:\n"
        " Kaytetty *m_kaytettyLuokka;\n"
        "}\n"
        // "class Inherited : public PublicBase,\n"
        // " protected ProtectedBase,\n"
        // " private PrivateBase,\n"
        // " public Undocumented,\n"
        // " public Templ<int>\n"
        // "{\n"
        // " private:\n"
        // " Used *m_usedClass;\n"
        // "};\n"
        "\\endcode\n"
        "Tuloksena on seuraavanlainen kaavio:"
        //"This will result in the following graph:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "Yllolevassa kaaviossa laatikoilla on seuraavat merkitykset\n:"
        // "The boxes in the above graph have the following meaning:\n"
        "<ul>\n"
        "<li>Tytetty harmaa laatikko esitt tietuetta tai luokkaa, jolle "
        // "<li>%A filled gray box represents the struct or class for which the "
        "kaavio on luotu.\n"
        // "graph is generated.\n"
        "<li>Mustareunainen laatikko merkitsee dokumentoitua tietuetta tai luokkaa.\n"
        // "<li>%A box with a black border denotes a documented struct or class.\n"
        "<li>Harmaareunainen laatikko merkitsee dokumentoimatonta tietuetta tai luokkaa.\n"
        // "<li>%A box with a grey border denotes an undocumented struct or class.\n"
        "<li>Punareunainen laatikko merkistee dokumentoitua luokkaa tai structia "
        // "<li>%A box with a red border denotes a documented struct or class for"
        "jolle ei nytet kaikkia periytymis-/sisllyssuhteita. Kaavio "
        // "which not all inheritance/containment relations are shown. %A graph is "
        "katkaistaan, jos se ei mahdu mriteltyjen rajojen sisn.\n"
        // "truncated if it does not fit within the specified boundaries.\n"
        "</ul>\n"
        "Nuolilla on seuraavat merkitykset:\n"
        // "The arrows have the following meaning:\n"
        "<ul>\n"
        "<li>Tummansinist nuolta kytetn osoittamaan julkista periytymis"
        // "<li>%A dark blue arrow is used to visualize a public inheritance "
        "suhdetta kahden luokan vlill.\n"
        // "relation between two classes.\n"
        "<li>Tummanvihre nuolta kytetn suojellussa periytymisess.\n"
        // "<li>%A dark green arrow is used for protected inheritance.\n"
        "<li>Tummanpunaista nuolta kytetn yksityisess periytymisess.\n"
        // "<li>%A dark red arrow is used for private inheritance.\n"
        "<li>Purppuranvrist katkoviivaa kytetn, jos luokka sisltyy tai "
        // "<li>%A purple dashed arrow is used if a class is contained or used "
        "on toisen luokan kyttm. Nuoli nimetn sill muuttujalla/muuttujilla "
        // "by another class. The arrow is labeled with the variable(s) "
        "jonka lpi osoitettua luokkaa tai tietuetta kytetn.\n"
        // "through which the pointed class or struct is accessible.\n"
        "<li>Keltainen katkoviivalla piirretty nuoli merkitsee suhdetta mallin esiintymn ja "
        // "<li>%A yellow dashed arrow denotes a relation between a template instance and "
        "malliluokan vlill. Nuoli nimetn "
        // "the template class it was instantiated from. The arrow is labeled with "
        "mallin esiintymn malliparametrilla.\n"
        // "the template parameters of the instance.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorFinnish::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 1042 of file translator_fi.h.
    {
      return "Kaavion selite"; // "Graph Legend"
    }
trLegendTitle() [2/2]
virtual QCString TranslatorFinnish::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 1042 of file translator_fi.h.
    {
      return "Kaavion selite"; // "Graph Legend"
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorFinnish::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 175 of file translator_fi.h.
    { return "Lista kaikista jsenist"; } // "List of all members."
trListOfAllMembers() [2/2]
virtual QCString TranslatorFinnish::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 175 of file translator_fi.h.
    { return "Lista kaikista jsenist"; } // "List of all members."
trMainPage() [1/2]
virtual QCString TranslatorFinnish::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 838 of file translator_fi.h.
    { return "Psivu"; } // "Main Page"
trMainPage() [2/2]
virtual QCString TranslatorFinnish::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 838 of file translator_fi.h.
    { return "Psivu"; } // "Main Page"
trMember() [1/2]
virtual QCString TranslatorFinnish::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1354 of file translator_fi.h.
    {
      QCString result((first_capital ? "Jsen" : "jsen")); // "Member" / "member"
      if (!singular) result+="et"; // "+s"
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorFinnish::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1354 of file translator_fi.h.
    {
      QCString result((first_capital ? "Jsen" : "jsen")); // "Member" / "member"
      if (!singular) result+="et"; // "+s"
      return result;
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorFinnish::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 158 of file translator_fi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Kenttien dokumentaatio"; // "Field Documentation";
      }
      else
      {
        return "Jsendatan dokumentaatio"; // "Member Data Documentation"
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorFinnish::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 158 of file translator_fi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Kenttien dokumentaatio"; // "Field Documentation";
      }
      else
      {
        return "Jsendatan dokumentaatio"; // "Member Data Documentation"
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorFinnish::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 150 of file translator_fi.h.
    { return "Jsenluettelotyyppien dokumentaatio"; } // "Member Enumeration Documentation"
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorFinnish::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 150 of file translator_fi.h.
    { return "Jsenluettelotyyppien dokumentaatio"; } // "Member Enumeration Documentation"
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorFinnish::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 154 of file translator_fi.h.
    { return "Jsenfunktioiden dokumentaatio"; } // "Member Function Documentation"
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorFinnish::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 154 of file translator_fi.h.
    { return "Jsenfunktioiden dokumentaatio"; } // "Member Function Documentation"
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorFinnish::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1648 of file translator_fi.h.
    { return "Jsenfunktioiden/aliohjelmien dokumentaatio"; } // "Member Function/Subroutine Documentation"
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorFinnish::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1648 of file translator_fi.h.
    { return "Jsenfunktioiden/aliohjelmien dokumentaatio"; } // "Member Function/Subroutine Documentation"
trMemberList() [1/2]
virtual QCString TranslatorFinnish::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 177 of file translator_fi.h.
    { return "Jsenlista"; } // "Member List"
trMemberList() [2/2]
virtual QCString TranslatorFinnish::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 177 of file translator_fi.h.
    { return "Jsenlista"; } // "Member List"
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorFinnish::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 145 of file translator_fi.h.
    { return "Jsentyyppimrittelyiden dokumentaatio"; } // "Member Typedef Documentation"
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorFinnish::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 145 of file translator_fi.h.
    { return "Jsentyyppimrittelyiden dokumentaatio"; } // "Member Typedef Documentation"
trModule() [1/2]
virtual QCString TranslatorFinnish::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1787 of file translator_fi.h.
    {
      QCString result((first_capital ? "Moduuli" : "moduuli")); // "Module" / "module"
      if (!singular) result+="t"; // "+s"
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorFinnish::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1787 of file translator_fi.h.
    {
      QCString result((first_capital ? "Moduuli" : "moduuli")); // "Module" / "module"
      if (!singular) result+="t"; // "+s"
      return result;
    }
trModuleDocumentation() [1/2]
virtual QCString TranslatorFinnish::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 437 of file translator_fi.h.
    { return "Moduulien dokumentaatio"; } // "Module Documentation"
trModuleDocumentation() [2/2]
virtual QCString TranslatorFinnish::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 437 of file translator_fi.h.
    { return "Moduulien dokumentaatio"; } // "Module Documentation"
trModuleIndex() [1/2]
virtual QCString TranslatorFinnish::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 404 of file translator_fi.h.
    { return "Moduuliluettelo"; } // "Module Index"
trModuleIndex() [2/2]
virtual QCString TranslatorFinnish::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 404 of file translator_fi.h.
    { return "Moduuliluettelo"; } // "Module Index"
trModuleReference() [1/2]
virtual QCString TranslatorFinnish::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1749 of file translator_fi.h.
    {
      QCString result=namespaceName;
      result+=" moduulin referenssi"; // " Module Reference"
      return result;
    }
trModuleReference() [2/2]
virtual QCString TranslatorFinnish::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1749 of file translator_fi.h.
    {
      QCString result=namespaceName;
      result+=" moduulin referenssi"; // " Module Reference"
      return result;
    }
trModules() [1/2]
virtual QCString TranslatorFinnish::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 222 of file translator_fi.h.
    { return "Moduulit"; } // "Modules"
trModules() [2/2]
virtual QCString TranslatorFinnish::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 222 of file translator_fi.h.
    { return "Moduulit"; } // "Modules"
trModulesDescription() [1/2]
virtual QCString TranslatorFinnish::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 392 of file translator_fi.h.
    { return "Tss on lista kaikista moduleista:"; } // "Here is a list of all modules:"
trModulesDescription() [2/2]
virtual QCString TranslatorFinnish::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 392 of file translator_fi.h.
    { return "Tss on lista kaikista moduleista:"; } // "Here is a list of all modules:"
trModulesIndex() [1/2]
virtual QCString TranslatorFinnish::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1780 of file translator_fi.h.
    { return "Moduulien hakemisto"; } // "Modules Index"
trModulesIndex() [2/2]
virtual QCString TranslatorFinnish::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1780 of file translator_fi.h.
    { return "Moduulien hakemisto"; } // "Modules Index"
trModulesList() [1/2]
virtual QCString TranslatorFinnish::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1715 of file translator_fi.h.
    { return "Moduulilista"; } // "Modules List"
trModulesList() [2/2]
virtual QCString TranslatorFinnish::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1715 of file translator_fi.h.
    { return "Moduulilista"; } // "Modules List"
trModulesListDescription() [1/2]
virtual QCString TranslatorFinnish::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1719 of file translator_fi.h.
    {
      QCString result="Tss on lista kaikista "; // "Here is a list of all "
      if (!extractAll) result+="dokumentoiduista "; // "documented "
      result+="moduuleista lyhyiden selitysten kanssa:"; // "modules with brief descriptions:"
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorFinnish::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1719 of file translator_fi.h.
    {
      QCString result="Tss on lista kaikista "; // "Here is a list of all "
      if (!extractAll) result+="dokumentoiduista "; // "documented "
      result+="moduuleista lyhyiden selitysten kanssa:"; // "modules with brief descriptions:"
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorFinnish::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1761 of file translator_fi.h.
    {
      QCString result="Tss on lista moduulin kaikista "; // "Here is a list of all "
      if (!extractAll) result+="dokumentoiduista"; // "documented "
      result+="jsenist, sek linkit "; // "module members with links to "
      if (extractAll)
      {
        result+="moduulin dokumentaatioon jokaiselle jsenelle:"; // "the module documentation for each member:"
      }
      else
      {
        result+="moduuleihin, joihin ne kuuluvat:"; // "the modules they belong to:"
      }
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorFinnish::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1761 of file translator_fi.h.
    {
      QCString result="Tss on lista moduulin kaikista "; // "Here is a list of all "
      if (!extractAll) result+="dokumentoiduista"; // "documented "
      result+="jsenist, sek linkit "; // "module members with links to "
      if (extractAll)
      {
        result+="moduulin dokumentaatioon jokaiselle jsenelle:"; // "the module documentation for each member:"
      }
      else
      {
        result+="moduuleihin, joihin ne kuuluvat:"; // "the modules they belong to:"
      }
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorFinnish::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1757 of file translator_fi.h.
    { return "Moduulin jsenet"; } // "Module Members"
trModulesMembers() [2/2]
virtual QCString TranslatorFinnish::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1757 of file translator_fi.h.
    { return "Moduulin jsenet"; } // "Module Members"
trMonth() [1/2]
virtual QCString TranslatorFinnish::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1851 of file translator_fi.h.
    {
      static const char *months_short[] = { "tammi", "helmi", "maalis", "huhti", "touko", "kes", "hein", "elo", "syys", "loka", "marras", "joulu" };
      static const char *months_full[] = { "tammikuu", "helmikuu", "maaliskuu", "huhtikuu", "toukokuu", "keskuu", "heinkuu", "elokuu", "syyskuu", "lokakuu", "marraskuu", "joulukuu" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMonth() [2/2]
virtual QCString TranslatorFinnish::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1851 of file translator_fi.h.
    {
      static const char *months_short[] = { "tammi", "helmi", "maalis", "huhti", "touko", "kes", "hein", "elo", "syys", "loka", "marras", "joulu" };
      static const char *months_full[] = { "tammikuu", "helmikuu", "maaliskuu", "huhtikuu", "toukokuu", "keskuu", "heinkuu", "elokuu", "syyskuu", "lokakuu", "marraskuu", "joulukuu" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore() [1/2]
virtual QCString TranslatorFinnish::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 171 of file translator_fi.h.
    { return "Lis..."; } // "More..."
trMore() [2/2]
virtual QCString TranslatorFinnish::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 171 of file translator_fi.h.
    { return "Lis..."; } // "More..."
trNamespace() [1/2]
virtual QCString TranslatorFinnish::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1321 of file translator_fi.h.
    {
      QCString result((first_capital ? "Nimiavaruus" : "nimiavaruus")); // "Namespace" / "namespace"
      if (!singular) result=(first_capital ? "Nimiavaruudet" : "nimiavaruudet"); // "+s"
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorFinnish::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1321 of file translator_fi.h.
    {
      QCString result((first_capital ? "Nimiavaruus" : "nimiavaruus")); // "Namespace" / "namespace"
      if (!singular) result=(first_capital ? "Nimiavaruudet" : "nimiavaruudet"); // "+s"
      return result;
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorFinnish::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 787 of file translator_fi.h.
    { return "Nimiavaruuden dokumentaatio"; } // "Namespace Documentation"
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorFinnish::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 787 of file translator_fi.h.
    { return "Nimiavaruuden dokumentaatio"; } // "Namespace Documentation"
trNamespaceIndex() [1/2]
virtual QCString TranslatorFinnish::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 781 of file translator_fi.h.
    { return "Nimiavaruuksien luettelo"; } // "Namespace Index"
trNamespaceIndex() [2/2]
virtual QCString TranslatorFinnish::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 781 of file translator_fi.h.
    { return "Nimiavaruuksien luettelo"; } // "Namespace Index"
trNamespaceList() [1/2]
virtual QCString TranslatorFinnish::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 614 of file translator_fi.h.
    { return "Nimiavaruus Lista"; } // "Namespace List"
trNamespaceList() [2/2]
virtual QCString TranslatorFinnish::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 614 of file translator_fi.h.
    { return "Nimiavaruus Lista"; } // "Namespace List"
trNamespaceListDescription() [1/2]
virtual QCString TranslatorFinnish::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 618 of file translator_fi.h.
    {
      QCString result="Tss on lista kaikista "; // "Here is a list of all "
      if (!extractAll) result+="dokumentoiduista "; // "documented "
      result+="nimiavaruuksista lyhyen selitteen kanssa:"; // "namespaces with brief descriptions:"
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorFinnish::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 618 of file translator_fi.h.
    {
      QCString result="Tss on lista kaikista "; // "Here is a list of all "
      if (!extractAll) result+="dokumentoiduista "; // "documented "
      result+="nimiavaruuksista lyhyen selitteen kanssa:"; // "namespaces with brief descriptions:"
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorFinnish::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 767 of file translator_fi.h.
    {
      QCString result="Tss on lista kaikista "; // "Here is a list of all "
      if (!extractAll) result+="dokumentoiduista "; // "documented "
      result+="nimiavaruuden jsenist linkitettyn "; // "namespace members with links to "
      if (extractAll)
        result+="nimiavaruuden dokumentaatioon johon ne kuuluvat:"; // "the namespace documentation for each member:";
      else
        result+="nimiavaruuksiin joihin ne kuuluvat:"; // "the namespaces they belong to:"
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorFinnish::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 767 of file translator_fi.h.
    {
      QCString result="Tss on lista kaikista "; // "Here is a list of all "
      if (!extractAll) result+="dokumentoiduista "; // "documented "
      result+="nimiavaruuden jsenist linkitettyn "; // "namespace members with links to "
      if (extractAll)
        result+="nimiavaruuden dokumentaatioon johon ne kuuluvat:"; // "the namespace documentation for each member:";
      else
        result+="nimiavaruuksiin joihin ne kuuluvat:"; // "the namespaces they belong to:"
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorFinnish::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 763 of file translator_fi.h.
    { return "Nimiavaruuden jsenet"; } // "Namespace Members"
trNamespaceMembers() [2/2]
virtual QCString TranslatorFinnish::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 763 of file translator_fi.h.
    { return "Nimiavaruuden jsenet"; } // "Namespace Members"
trNamespaceReference() [1/2]
virtual QCString TranslatorFinnish::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 677 of file translator_fi.h.
    {
      QCString result=namespaceName;
      result+=" nimiavaruusreferenssi"; // " Namespace Reference"
      return result;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorFinnish::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 677 of file translator_fi.h.
    {
      QCString result=namespaceName;
      result+=" nimiavaruusreferenssi"; // " Namespace Reference"
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorFinnish::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 797 of file translator_fi.h.
    { return "Nimiavaruudet"; } // "Namespaces"; }
trNamespaces() [2/2]
virtual QCString TranslatorFinnish::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 797 of file translator_fi.h.
    { return "Nimiavaruudet"; } // "Namespaces"; }
trNote() [1/2]
virtual QCString TranslatorFinnish::trNote () [inline], [virtual]
Implements Translator.
Definition at line 944 of file translator_fi.h.
    {
        // FIXME: Misshn merkityksess tt kytetn?
      return "Huomautus"; // "Note"
    }
trNote() [2/2]
virtual QCString TranslatorFinnish::trNote () [inline], [virtual]
Implements Translator.
Definition at line 944 of file translator_fi.h.
    {
        // FIXME: Misshn merkityksess tt kytetn?
      return "Huomautus"; // "Note"
    }
trOverloadText() [1/2]
virtual QCString TranslatorFinnish::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1617 of file translator_fi.h.
    {
       return "Tm on ylikuormitettu jsenfunktio, ja se tarjotaan "
              "kytn helpottamiseksi. Se eroaa yllolevasta "
              "funktiosta ainoastaan hyvksymiltn parametreilta.";
              // "This is an overloaded member function, "
              // "provided for convenience. It differs from the above "
              // "function only in what argument(s) it accepts."
    }
trOverloadText() [2/2]
virtual QCString TranslatorFinnish::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1617 of file translator_fi.h.
    {
       return "Tm on ylikuormitettu jsenfunktio, ja se tarjotaan "
              "kytn helpottamiseksi. Se eroaa yllolevasta "
              "funktiosta ainoastaan hyvksymiltn parametreilta.";
              // "This is an overloaded member function, "
              // "provided for convenience. It differs from the above "
              // "function only in what argument(s) it accepts."
    }
trPackage() [1/2]
virtual QCString TranslatorFinnish::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1211 of file translator_fi.h.
    {
      return "Paketti "+name; // "Package "
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorFinnish::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1211 of file translator_fi.h.
    {
      return "Paketti "+name; // "Package "
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorFinnish::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1488 of file translator_fi.h.
    {
      return "Paketin attribuutit"; // "Package Attributes"
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorFinnish::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1488 of file translator_fi.h.
    {
      return "Paketin attribuutit"; // "Package Attributes"
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorFinnish::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1470 of file translator_fi.h.
    {
      return "Paketin funktiot"; // "Package Functions"
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorFinnish::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1470 of file translator_fi.h.
    {
      return "Paketin funktiot"; // "Package Functions"
    }
trPackageListDescription() [1/2]
virtual QCString TranslatorFinnish::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1216 of file translator_fi.h.
    {
      return "Tss ovat paketit lyhyiden selitysten kanssa (jos saatavilla):"; // "Here are the packages with brief descriptions (if available):"
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorFinnish::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1216 of file translator_fi.h.
    {
      return "Tss ovat paketit lyhyiden selitysten kanssa (jos saatavilla):"; // "Here are the packages with brief descriptions (if available):"
    }
trPackageMembers() [1/2]
virtual QCString TranslatorFinnish::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1474 of file translator_fi.h.
    {
      return "Paketin jsenet"; // "Package Members"
    }
trPackageMembers() [2/2]
virtual QCString TranslatorFinnish::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1474 of file translator_fi.h.
    {
      return "Paketin jsenet"; // "Package Members"
    }
trPackages() [1/2]
virtual QCString TranslatorFinnish::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1221 of file translator_fi.h.
    {
      return "Paketit"; // "Packages"
    }
trPackages() [2/2]
virtual QCString TranslatorFinnish::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1221 of file translator_fi.h.
    {
      return "Paketit"; // "Packages"
    }
trPackageTypes() [1/2]
virtual QCString TranslatorFinnish::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1463 of file translator_fi.h.
    {
      return "Paketin tyypit"; // "Package Types"
    }
trPackageTypes() [2/2]
virtual QCString TranslatorFinnish::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1463 of file translator_fi.h.
    {
      return "Paketin tyypit"; // "Package Types"
    }
trPage() [1/2]
virtual QCString TranslatorFinnish::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1343 of file translator_fi.h.
    {
      QCString result((first_capital ? "Sivu" : "sivu")); // "Page" / "page"
      if (!singular) result+="t"; // "+s"
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorFinnish::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1343 of file translator_fi.h.
    {
      QCString result((first_capital ? "Sivu" : "sivu")); // "Page" / "page"
      if (!singular) result+="t"; // "+s"
      return result;
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorFinnish::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 844 of file translator_fi.h.
    { return "s."; } // "p."
trPageAbbreviation() [2/2]
virtual QCString TranslatorFinnish::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 844 of file translator_fi.h.
    { return "s."; } // "p."
trPageIndex() [1/2]
virtual QCString TranslatorFinnish::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 935 of file translator_fi.h.
    {
      return "Sivuhakemisto"; // "Page Index"
    }
trPageIndex() [2/2]
virtual QCString TranslatorFinnish::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 935 of file translator_fi.h.
    {
      return "Sivuhakemisto"; // "Page Index"
    }
trParameters() [1/2]
virtual QCString TranslatorFinnish::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 598 of file translator_fi.h.
    { return "Parametrit"; } // "Parameters"
trParameters() [2/2]
virtual QCString TranslatorFinnish::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 598 of file translator_fi.h.
    { return "Parametrit"; } // "Parameters"
trPostcondition() [1/2]
virtual QCString TranslatorFinnish::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 904 of file translator_fi.h.
    {
      return "Jlkiehto"; // "Postcondition"
    }
trPostcondition() [2/2]
virtual QCString TranslatorFinnish::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 904 of file translator_fi.h.
    {
      return "Jlkiehto"; // "Postcondition"
    }
trPrecondition() [1/2]
virtual QCString TranslatorFinnish::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 899 of file translator_fi.h.
    {
      return "Esiehto"; //"Precondition"
    }
trPrecondition() [2/2]
virtual QCString TranslatorFinnish::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 899 of file translator_fi.h.
    {
      return "Esiehto"; //"Precondition"
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorFinnish::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 984 of file translator_fi.h.
    {
      return "Yksityiset attribuutit"; // "Private Attributes"
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorFinnish::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 984 of file translator_fi.h.
    {
      return "Yksityiset attribuutit"; // "Private Attributes"
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorFinnish::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 698 of file translator_fi.h.
    { return "Yksityiset jsenfunktiot"; } // "Private Member Functions"
trPrivateMembers() [2/2]
virtual QCString TranslatorFinnish::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 698 of file translator_fi.h.
    { return "Yksityiset jsenfunktiot"; } // "Private Member Functions"
trPrivateSlots() [1/2]
virtual QCString TranslatorFinnish::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 700 of file translator_fi.h.
    { return "Yksityiset vastineet"; } // "Private Slots"
trPrivateSlots() [2/2]
virtual QCString TranslatorFinnish::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 700 of file translator_fi.h.
    { return "Yksityiset vastineet"; } // "Private Slots"
trPrivateTypes() [1/2]
virtual QCString TranslatorFinnish::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 980 of file translator_fi.h.
    {
      return "Yksityiset tyypit"; // "Private Types"
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorFinnish::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 980 of file translator_fi.h.
    {
      return "Yksityiset tyypit"; // "Private Types"
    }
trProperties() [1/2]
virtual QCString TranslatorFinnish::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1184 of file translator_fi.h.
    {
      return "Ominaisuudet"; // "Properties"
    }
trProperties() [2/2]
virtual QCString TranslatorFinnish::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1184 of file translator_fi.h.
    {
      return "Ominaisuudet"; // "Properties"
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorFinnish::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1189 of file translator_fi.h.
    {
      return "Ominaisuuksien dokumentaatio"; // "Property Documentation"
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorFinnish::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1189 of file translator_fi.h.
    {
      return "Ominaisuuksien dokumentaatio"; // "Property Documentation"
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorFinnish::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 972 of file translator_fi.h.
    {
      return "Suojellut attribuutit"; // "Protected Attributes"
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorFinnish::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 972 of file translator_fi.h.
    {
      return "Suojellut attribuutit"; // "Protected Attributes"
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorFinnish::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 692 of file translator_fi.h.
    { return "Suojatut jsenfunktiot"; } // "Protected Member Functions"
trProtectedMembers() [2/2]
virtual QCString TranslatorFinnish::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 692 of file translator_fi.h.
    { return "Suojatut jsenfunktiot"; } // "Protected Member Functions"
trProtectedSlots() [1/2]
virtual QCString TranslatorFinnish::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 694 of file translator_fi.h.
    { return "Suojatut vastineet"; } // "Protected Slots"
trProtectedSlots() [2/2]
virtual QCString TranslatorFinnish::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 694 of file translator_fi.h.
    { return "Suojatut vastineet"; } // "Protected Slots"
trProtectedTypes() [1/2]
virtual QCString TranslatorFinnish::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 968 of file translator_fi.h.
    {
      return "Suojellut tyypit"; // "Protected Types"
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorFinnish::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 968 of file translator_fi.h.
    {
      return "Suojellut tyypit"; // "Protected Types"
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorFinnish::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 953 of file translator_fi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Tietueen kentt"; // "Data Fields"
      }
      else
      {
        return "Julkiset attribuutit"; // "Public Attributes"
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorFinnish::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 953 of file translator_fi.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Tietueen kentt"; // "Data Fields"
      }
      else
      {
        return "Julkiset attribuutit"; // "Public Attributes"
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorFinnish::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 684 of file translator_fi.h.
    { return "Julkiset jsenfunktiot"; } // "Public Member Functions"
trPublicMembers() [2/2]
virtual QCString TranslatorFinnish::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 684 of file translator_fi.h.
    { return "Julkiset jsenfunktiot"; } // "Public Member Functions"
trPublicSlots() [1/2]
virtual QCString TranslatorFinnish::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 686 of file translator_fi.h.
    { return "Julkiset vastineet"; } // "Public Slots"
trPublicSlots() [2/2]
virtual QCString TranslatorFinnish::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 686 of file translator_fi.h.
    { return "Julkiset vastineet"; } // "Public Slots"
trPublicTypes() [1/2]
virtual QCString TranslatorFinnish::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 949 of file translator_fi.h.
    {
      return "Julkiset tyypit"; // "Public Types"
    }
trPublicTypes() [2/2]
virtual QCString TranslatorFinnish::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 949 of file translator_fi.h.
    {
      return "Julkiset tyypit"; // "Public Types"
    }
trReferencedBy() [1/2]
virtual QCString TranslatorFinnish::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 1012 of file translator_fi.h.
    {
      return "Viitattu"; // "Referenced by"
    }
trReferencedBy() [2/2]
virtual QCString TranslatorFinnish::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 1012 of file translator_fi.h.
    {
      return "Viitattu"; // "Referenced by"
    }
trReferenceManual() [1/2]
virtual QCString TranslatorFinnish::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 472 of file translator_fi.h.
    { return "Ksikirja"; } // "Reference Manual"
trReferenceManual() [2/2]
virtual QCString TranslatorFinnish::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 472 of file translator_fi.h.
    { return "Ksikirja"; } // "Reference Manual"
trReferences() [1/2]
virtual QCString TranslatorFinnish::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1391 of file translator_fi.h.
    {
      return "Viittaukset"; // "References"
    }
trReferences() [2/2]
virtual QCString TranslatorFinnish::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1391 of file translator_fi.h.
    {
      return "Viittaukset"; // "References"
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorFinnish::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 749 of file translator_fi.h.
    {
      return QCString("Uudelleentoteuttaa ")+(numEntries > 1 ? "luokat " : "luokan ")+trWriteList(numEntries)+"."; // "Reimplemented from "
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorFinnish::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 749 of file translator_fi.h.
    {
      return QCString("Uudelleentoteuttaa ")+(numEntries > 1 ? "luokat " : "luokan ")+trWriteList(numEntries)+"."; // "Reimplemented from "
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorFinnish::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 757 of file translator_fi.h.
    {
      return QCString("Uudelleentoteutetaan ")+(numEntries > 1 ? "luokissa " : "luokassa ")+trWriteList(numEntries)+"."; // "Reimplemented in "
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorFinnish::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 757 of file translator_fi.h.
    {
      return QCString("Uudelleentoteutetaan ")+(numEntries > 1 ? "luokissa " : "luokassa ")+trWriteList(numEntries)+"."; // "Reimplemented in "
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorFinnish::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 639 of file translator_fi.h.
    { return "Ystvt ja niihin liittyvien funktioiden dokumentaatio"; } // "Friends And Related Function Documentation"
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorFinnish::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 639 of file translator_fi.h.
    { return "Ystvt ja niihin liittyvien funktioiden dokumentaatio"; } // "Friends And Related Function Documentation"
trRelatedFunctions() [1/2]
virtual QCString TranslatorFinnish::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 133 of file translator_fi.h.
    { return "Liittyvt funktiot"; } // "Related Functions";
trRelatedFunctions() [2/2]
virtual QCString TranslatorFinnish::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 133 of file translator_fi.h.
    { return "Liittyvt funktiot"; } // "Related Functions";
trRelatedPages() [1/2]
virtual QCString TranslatorFinnish::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 273 of file translator_fi.h.
    { return "Liittyvt sivut"; } // "Related Pages"
trRelatedPages() [2/2]
virtual QCString TranslatorFinnish::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 273 of file translator_fi.h.
    { return "Liittyvt sivut"; } // "Related Pages"
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorFinnish::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 388 of file translator_fi.h.
    { return "Tss on lista kaikista liittyvist dokumentaatiosivuista:"; } // "Here is a list of all related documentation pages:"
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorFinnish::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 388 of file translator_fi.h.
    { return "Tss on lista kaikista liittyvist dokumentaatiosivuista:"; } // "Here is a list of all related documentation pages:"
trRelatedSubscript() [1/2]
virtual QCString TranslatorFinnish::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 137 of file translator_fi.h.
    { return "(Huomaa, ett nm eivt ole jsenfunktioita.)"; } // "(Note that these are not member functions.)"
trRelatedSubscript() [2/2]
virtual QCString TranslatorFinnish::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 137 of file translator_fi.h.
    { return "(Huomaa, ett nm eivt ole jsenfunktioita.)"; } // "(Note that these are not member functions.)"
trRemarks() [1/2]
virtual QCString TranslatorFinnish::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 1016 of file translator_fi.h.
    {
      return "Huomioita"; // "Remarks"
    }
trRemarks() [2/2]
virtual QCString TranslatorFinnish::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 1016 of file translator_fi.h.
    {
      return "Huomioita"; // "Remarks"
    }
trReturns() [1/2]
virtual QCString TranslatorFinnish::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 590 of file translator_fi.h.
    { return "Palauttaa"; } // "Returns"
trReturns() [2/2]
virtual QCString TranslatorFinnish::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 590 of file translator_fi.h.
    { return "Palauttaa"; } // "Returns"
trReturnValues() [1/2]
virtual QCString TranslatorFinnish::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 833 of file translator_fi.h.
    { return "Paluuarvot"; } // "Return values"
trReturnValues() [2/2]
virtual QCString TranslatorFinnish::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 833 of file translator_fi.h.
    { return "Paluuarvot"; } // "Return values"
trRTFansicp() [1/2]
virtual QCString TranslatorFinnish::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1275 of file translator_fi.h.
    {
      return "1252";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorFinnish::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1275 of file translator_fi.h.
    {
      return "1252";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorFinnish::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1284 of file translator_fi.h.
    {
      return "0";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorFinnish::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1284 of file translator_fi.h.
    {
      return "0";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorFinnish::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1290 of file translator_fi.h.
    {
      return "Hakemisto"; // "Index"
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorFinnish::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1290 of file translator_fi.h.
    {
      return "Hakemisto"; // "Index"
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorFinnish::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1423 of file translator_fi.h.
    {
      return "Sisllysluettelo"; // "Table of Contents"
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorFinnish::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1423 of file translator_fi.h.
    {
      return "Sisllysluettelo"; // "Table of Contents"
    }
trSearch() [1/2]
virtual QCString TranslatorFinnish::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 281 of file translator_fi.h.
    { return "Etsi"; } // "Search"
trSearch() [2/2]
virtual QCString TranslatorFinnish::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 281 of file translator_fi.h.
    { return "Etsi"; } // "Search"
trSearchMatches() [1/2]
virtual QCString TranslatorFinnish::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1555 of file translator_fi.h.
    {
      return "Osumat:"; // "Matches:"
    }
trSearchMatches() [2/2]
virtual QCString TranslatorFinnish::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1555 of file translator_fi.h.
    {
      return "Osumat:"; // "Matches:"
    }
trSearchResults() [1/2]
virtual QCString TranslatorFinnish::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1536 of file translator_fi.h.
    {
      if (numDocuments==0)
      {
        return "Valitettavasti yksikn dokumentti ei vastannut hakuasi."; // "Sorry, no documents matching your query."
      }
      else if (numDocuments==1)
      {
        return "Lytyi <b>1</b> dokumentti, joka vastasi hakuasi."; // "Found <b>1</b> document matching your query.";
      }
      else
      {
        return "Lytyi <b>$num</b> dokumenttia, jotka vastasivat hakuasi. " // "Found <b>$num</b> documents matching your query. "
                "Parhaat tulokset nytetn ensin."; // "Showing best matches first."
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorFinnish::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1536 of file translator_fi.h.
    {
      if (numDocuments==0)
      {
        return "Valitettavasti yksikn dokumentti ei vastannut hakuasi."; // "Sorry, no documents matching your query."
      }
      else if (numDocuments==1)
      {
        return "Lytyi <b>1</b> dokumentti, joka vastasi hakuasi."; // "Found <b>1</b> document matching your query.";
      }
      else
      {
        return "Lytyi <b>$num</b> dokumenttia, jotka vastasivat hakuasi. " // "Found <b>$num</b> documents matching your query. "
                "Parhaat tulokset nytetn ensin."; // "Showing best matches first."
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorFinnish::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1524 of file translator_fi.h.
    {
      return "Hakutulokset"; // "Search Results"
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorFinnish::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1524 of file translator_fi.h.
    {
      return "Hakutulokset"; // "Search Results"
    }
trSeeAlso() [1/2]
virtual QCString TranslatorFinnish::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 594 of file translator_fi.h.
    { return "Katso mys"; } // "See also"
trSeeAlso() [2/2]
virtual QCString TranslatorFinnish::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 594 of file translator_fi.h.
    { return "Katso mys"; } // "See also"
trSignals() [1/2]
virtual QCString TranslatorFinnish::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 688 of file translator_fi.h.
    { return "Signaalit"; } // "Signals"
trSignals() [2/2]
virtual QCString TranslatorFinnish::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 688 of file translator_fi.h.
    { return "Signaalit"; } // "Signals"
trSince() [1/2]
virtual QCString TranslatorFinnish::trSince () [inline], [virtual]
Implements Translator.
Definition at line 1031 of file translator_fi.h.
    {
        // FIXME: Miss merkityksess tt kytetn?
      return "Lhtien"; // "Since"
    }
trSince() [2/2]
virtual QCString TranslatorFinnish::trSince () [inline], [virtual]
Implements Translator.
Definition at line 1031 of file translator_fi.h.
    {
        // FIXME: Miss merkityksess tt kytetn?
      return "Lhtien"; // "Since"
    }
trSourceFile() [1/2]
virtual QCString TranslatorFinnish::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1566 of file translator_fi.h.
    {
      return filename + " lhdekooditiedosto"; // " Source File"
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorFinnish::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1566 of file translator_fi.h.
    {
      return filename + " lhdekooditiedosto"; // " Source File"
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorFinnish::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1495 of file translator_fi.h.
    {
      return "Paketin staattiset attribuutit"; // "Static Package Attributes"
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorFinnish::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1495 of file translator_fi.h.
    {
      return "Paketin staattiset attribuutit"; // "Static Package Attributes"
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorFinnish::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1481 of file translator_fi.h.
    {
      return "Paketin staattiset funktiot"; // "Static Package Functions"
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorFinnish::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1481 of file translator_fi.h.
    {
      return "Paketin staattiset funktiot"; // "Static Package Functions"
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorFinnish::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 988 of file translator_fi.h.
    {
      return "Staattiset yksityiset attribuutit"; // "Static Private Attributes"
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorFinnish::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 988 of file translator_fi.h.
    {
      return "Staattiset yksityiset attribuutit"; // "Static Private Attributes"
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorFinnish::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 702 of file translator_fi.h.
    { return "Staattiset yksityiset jsenfunktiot"; } // "Static Private Member Functions"
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorFinnish::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 702 of file translator_fi.h.
    { return "Staattiset yksityiset jsenfunktiot"; } // "Static Private Member Functions"
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorFinnish::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 976 of file translator_fi.h.
    {
      return "Staattiset suojellut attribuutit"; // "Static Protected Attributes"
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorFinnish::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 976 of file translator_fi.h.
    {
      return "Staattiset suojellut attribuutit"; // "Static Protected Attributes"
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorFinnish::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 696 of file translator_fi.h.
    { return "Staattiset suojatut jsenfunktiot"; } // "Static Protected Member Functions"
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorFinnish::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 696 of file translator_fi.h.
    { return "Staattiset suojatut jsenfunktiot"; } // "Static Protected Member Functions"
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorFinnish::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 964 of file translator_fi.h.
    {
      return "Staattiset julkiset attribuutit"; // "Static Public Attributes"
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorFinnish::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 964 of file translator_fi.h.
    {
      return "Staattiset julkiset attribuutit"; // "Static Public Attributes"
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorFinnish::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 690 of file translator_fi.h.
    { return "Staattiset julkiset jsenfunktiot"; } // "Static Public Member Functions"
trStaticPublicMembers() [2/2]
virtual QCString TranslatorFinnish::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 690 of file translator_fi.h.
    { return "Staattiset julkiset jsenfunktiot"; } // "Static Public Member Functions"
trSubprogram() [1/2]
virtual QCString TranslatorFinnish::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1830 of file translator_fi.h.
    {
      QCString result((first_capital ? "Aliohjelma" : "aliohjelma")); // "Subprogram" / "subprogram"
      if (!singular) result+="t"; // "+s"
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorFinnish::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1830 of file translator_fi.h.
    {
      QCString result((first_capital ? "Aliohjelma" : "aliohjelma")); // "Subprogram" / "subprogram"
      if (!singular) result+="t"; // "+s"
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorFinnish::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1705 of file translator_fi.h.
    { return "Funktioiden/aliohjelmien dokumentaatio"; } // "Function/Subroutine Documentation"
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorFinnish::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1705 of file translator_fi.h.
    { return "Funktioiden/aliohjelmien dokumentaatio"; } // "Function/Subroutine Documentation"
trSubprograms() [1/2]
virtual QCString TranslatorFinnish::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1699 of file translator_fi.h.
    { return "Funktiot/aliohjelmat"; } // "Functions/Subroutines"
trSubprograms() [2/2]
virtual QCString TranslatorFinnish::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1699 of file translator_fi.h.
    { return "Funktiot/aliohjelmat"; } // "Functions/Subroutines"
trTest() [1/2]
virtual QCString TranslatorFinnish::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1169 of file translator_fi.h.
    {
      return "Testi"; // "Test"
    }
trTest() [2/2]
virtual QCString TranslatorFinnish::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1169 of file translator_fi.h.
    {
      return "Testi"; // "Test"
    }
trTestList() [1/2]
virtual QCString TranslatorFinnish::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1174 of file translator_fi.h.
    {
      return "Testilista"; // "Test List"
    }
trTestList() [2/2]
virtual QCString TranslatorFinnish::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1174 of file translator_fi.h.
    {
      return "Testilista"; // "Test List"
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorFinnish::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 183 of file translator_fi.h.
    { return "Tm on lista kaikista jsenist luokassa "; } // "This is the complete list of members for "
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorFinnish::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 183 of file translator_fi.h.
    { return "Tm on lista kaikista jsenist luokassa "; } // "This is the complete list of members for "
trTodo() [1/2]
virtual QCString TranslatorFinnish::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 998 of file translator_fi.h.
    {
      return "Viel tehtvn"; // "Todo"
    }
trTodo() [2/2]
virtual QCString TranslatorFinnish::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 998 of file translator_fi.h.
    {
      return "Viel tehtvn"; // "Todo"
    }
trTodoList() [1/2]
virtual QCString TranslatorFinnish::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 1003 of file translator_fi.h.
    {
      return "Tehtvlista"; // "Todo List"
    }
trTodoList() [2/2]
virtual QCString TranslatorFinnish::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 1003 of file translator_fi.h.
    {
      return "Tehtvlista"; // "Todo List"
    }
trType() [1/2]
virtual QCString TranslatorFinnish::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1820 of file translator_fi.h.
    {
      QCString result((first_capital ? "Tyyppi" : "tyyppi")); // "Type" / "type"
      if (!singular) result=(first_capital ? "Tyypit" : "tyypit"); // "+s"
      return result;
    }
trType() [2/2]
virtual QCString TranslatorFinnish::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1820 of file translator_fi.h.
    {
      QCString result((first_capital ? "Tyyppi" : "tyyppi")); // "Type" / "type"
      if (!singular) result=(first_capital ? "Tyypit" : "tyypit"); // "+s"
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorFinnish::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1838 of file translator_fi.h.
    {
      return "Tyyppien rajoitteet"; // "Type Constraints"
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorFinnish::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1838 of file translator_fi.h.
    {
      return "Tyyppien rajoitteet"; // "Type Constraints"
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorFinnish::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 520 of file translator_fi.h.
    { return "Tyyppimritysten dokumentaatio"; } // "Typedef Documentation"
trTypedefDocumentation() [2/2]
virtual QCString TranslatorFinnish::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 520 of file translator_fi.h.
    { return "Tyyppimritysten dokumentaatio"; } // "Typedef Documentation"
trTypedefs() [1/2]
virtual QCString TranslatorFinnish::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 484 of file translator_fi.h.
    { return "Tyyppimrittelyt"; } // "Typedefs"
trTypedefs() [2/2]
virtual QCString TranslatorFinnish::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 484 of file translator_fi.h.
    { return "Tyyppimrittelyt"; } // "Typedefs"
trTypeDocumentation() [1/2]
virtual QCString TranslatorFinnish::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1693 of file translator_fi.h.
    { return "Tietotyyppien dokumentaatio"; } // "Data Type Documentation"
trTypeDocumentation() [2/2]
virtual QCString TranslatorFinnish::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 1693 of file translator_fi.h.
    { return "Tietotyyppien dokumentaatio"; } // "Data Type Documentation"
trVariableDocumentation() [1/2]
virtual QCString TranslatorFinnish::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 538 of file translator_fi.h.
    { return "Muuttujien dokumentaatio"; } // "Variable Documentation"
trVariableDocumentation() [2/2]
virtual QCString TranslatorFinnish::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 538 of file translator_fi.h.
    { return "Muuttujien dokumentaatio"; } // "Variable Documentation"
trVariables() [1/2]
virtual QCString TranslatorFinnish::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 502 of file translator_fi.h.
    { return "Muuttujat"; } // "Variables"
trVariables() [2/2]
virtual QCString TranslatorFinnish::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 502 of file translator_fi.h.
    { return "Muuttujat"; } // "Variables"
trVersion() [1/2]
virtual QCString TranslatorFinnish::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 582 of file translator_fi.h.
    { return "Versio"; } // "Version"
trVersion() [2/2]
virtual QCString TranslatorFinnish::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 582 of file translator_fi.h.
    { return "Versio"; } // "Version"
trWarning() [1/2]
virtual QCString TranslatorFinnish::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 578 of file translator_fi.h.
    { return "Varoitus"; } // "Warning"
trWarning() [2/2]
virtual QCString TranslatorFinnish::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 578 of file translator_fi.h.
    { return "Varoitus"; } // "Warning"
trWriteList() [1/2]
virtual QCString TranslatorFinnish::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 708 of file translator_fi.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" ja "; // ", and "
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorFinnish::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 708 of file translator_fi.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" ja "; // ", and "
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_fi.h
doxygen/src/translator_fi.h