HtmlHelp::Private Class Reference
Public Member Functions
Private ()
void createProjectFile ()
Private ()
void createProjectFile ()
Public Attributes
std::ofstream cts
std::ofstream kts
QCString prevFile
QCString prevAnc
bool ctsItemPresent = false
int dc = 0
StringSet indexFiles
StringSet imageFiles
StringSet styleFiles
HtmlHelpRecoder recoder
HtmlHelpIndex index
Detailed Description
Definition at line 313 of file htmlhelp.cpp.
Constructor & Destructor Documentation
Private() [1/2]
HtmlHelp::Private::Private () [inline]
Definition at line 316 of file htmlhelp.cpp.
: index(recoder) {}
Private() [2/2]
HtmlHelp::Private::Private () [inline]
Definition at line 316 of file htmlhelp.cpp.
: index(recoder) {}
Member Function Documentation
createProjectFile() [1/2]
void HtmlHelp::Private::createProjectFile ()
Definition at line 380 of file htmlhelp.cpp.
{
  /* Write the project file */
  QCString fName = Config_getString(HTML_OUTPUT) + "/" + hhpFileName;
  std::ofstream t(fName.str(),std::ofstream::out | std::ofstream::binary);
  if (t.is_open())
  {
    QCString hhcFile = "\"" + hhcFileName + "\"";
    QCString hhkFile = "\"" + hhkFileName + "\"";
    bool hhkPresent = index.size()>0;
    if (!ctsItemPresent) hhcFile = "";
    if (!hhkPresent) hhkFile = "";
    QCString indexName="index"+Doxygen::htmlFileExtension;
    t << "[OPTIONS]\n";
    if (!Config_getString(CHM_FILE).isEmpty())
    {
      t << "Compiled file=" << Config_getString(CHM_FILE) << "\n";
    }
    t << "Compatibility=1.1\n"
         "Full-text search=Yes\n";
    if (ctsItemPresent) t << "Contents file=" + hhcFileName + "\n";
    t << "Default Window=main\n"
         "Default topic=" << indexName << "\n";
    if (hhkPresent) t << "Index file=" + hhkFileName + "\n";
    t << "Language=" << theTranslator->getLanguageString() << "\n";
    if (Config_getBool(BINARY_TOC)) t << "Binary TOC=YES\n";
    if (Config_getBool(GENERATE_CHI)) t << "Create CHI file=YES\n";
    t << "Title=" << recoder.recode(Config_getString(PROJECT_NAME)) << "\n\n";
    t << "[WINDOWS]\n";
    // NOTE: the 0x10387e number is a set of bits specifying the buttons
    // which should appear in the CHM viewer; that specific value
    // means "show all buttons including the font-size one";
    // the font-size one is not normally settable by the HTML Help Workshop
    // utility but the way to set it is described here:
    // http://support.microsoft.com/?scid=kb%3Ben-us%3B240062&x=17&y=18
    // NOTE: the 0x70387e number in addition to the above the Next and Prev button
    // are shown. They can only be shown in case of a binary toc.
    // dee http://www.mif2go.com/xhtml/htmlhelp_0016_943addingtabsandtoolbarbuttonstohtmlhelp.htm#Rz108x95873
    // Value has been taken from htmlhelp.h file of the HTML Help Workshop
    if (Config_getBool(BINARY_TOC))
    {
      t << "main=\"" << recoder.recode(Config_getString(PROJECT_NAME)) << "\"," << hhcFile << ","
         << hhkFile << ",\"" << indexName << "\",\"" <<
         indexName << "\",,,,,0x23520,,0x70387e,,,,,,,,0\n\n";
    }
    else
    {
      t << "main=\"" << recoder.recode(Config_getString(PROJECT_NAME)) << "\"," << hhcFile << ","
         << hhkFile << ",\"" << indexName << "\",\"" <<
         indexName << "\",,,,,0x23520,,0x10387e,,,,,,,,0\n\n";
    }
    t << "[FILES]\n";
    for (auto &s : indexFiles)
    {
      t << s.c_str() << "\n";
    }
    for (auto &s : imageFiles)
    {
      t << s.c_str() << "\n";
    }
    for (auto &s : styleFiles)
    {
      t << s.c_str() << "\n";
    }
    t.close();
  }
  else
  {
    err("Could not open file %s for writing\n",qPrint(fName));
  }
}
References Config_getBool, Config_getString, ctsItemPresent, err(), Translator::getLanguageString(), HtmlHelp::hhcFileName, HtmlHelp::hhkFileName, HtmlHelp::hhpFileName, Doxygen::htmlFileExtension, imageFiles, index, indexFiles, out, qPrint(), HtmlHelpRecoder::recode(), recoder, s, HtmlHelpIndex::size(), QCString::str(), styleFiles, and theTranslator.
createProjectFile() [2/2]
void HtmlHelp::Private::createProjectFile ()
Member Data Documentation
cts
std::ofstream HtmlHelp::Private::cts
Definition at line 318 of file htmlhelp.cpp.
ctsItemPresent
bool HtmlHelp::Private::ctsItemPresent = false
Definition at line 321 of file htmlhelp.cpp.
Referenced by createProjectFile().
dc
int HtmlHelp::Private::dc = 0
Definition at line 322 of file htmlhelp.cpp.
imageFiles
StringSet HtmlHelp::Private::imageFiles
Definition at line 324 of file htmlhelp.cpp.
Referenced by createProjectFile().
index
HtmlHelpIndex HtmlHelp::Private::index
Definition at line 327 of file htmlhelp.cpp.
Referenced by createProjectFile().
indexFiles
StringSet HtmlHelp::Private::indexFiles
Definition at line 323 of file htmlhelp.cpp.
Referenced by createProjectFile().
kts
std::ofstream HtmlHelp::Private::kts
Definition at line 318 of file htmlhelp.cpp.
prevAnc
QCString HtmlHelp::Private::prevAnc
Definition at line 320 of file htmlhelp.cpp.
prevFile
QCString HtmlHelp::Private::prevFile
Definition at line 319 of file htmlhelp.cpp.
recoder
HtmlHelpRecoder HtmlHelp::Private::recoder
Definition at line 326 of file htmlhelp.cpp.
Referenced by createProjectFile().
styleFiles
StringSet HtmlHelp::Private::styleFiles
Definition at line 325 of file htmlhelp.cpp.
Referenced by createProjectFile().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/htmlhelp.cpp
doxygen/src/htmlhelp.cpp