TemplateNodeList Class Reference
Class representing a list of AST nodes in a template.
Public Member Functions
void render (TextStream &ts, TemplateContext *c)
void render (TextStream &ts, TemplateContext *c)
Detailed Description
Class representing a list of AST nodes in a template.
Definition at line 1967 of file template.cpp.
Member Function Documentation
render() [1/2]
void TemplateNodeList::render (TextStream & ts, TemplateContext * c) [inline]
Definition at line 1970 of file template.cpp.
    {
      TRACE(("{TemplateNodeList::render\n"));
      for (const auto &tn : *this)
      {
        tn->render(ts,c);
      }
      TRACE(("}TemplateNodeList::render\n"));
    }
References c, and TRACE.
Referenced by TemplateNodeMsg::render(), TemplateImpl::render(), TemplateNodeIf::render(), TemplateNodeRepeat::render(), TemplateNodeRange::render(), TemplateNodeFor::render(), TemplateNodeBlock::render(), TemplateNodeWith::render(), TemplateNodeSpaceless::render(), TemplateNodeMarkers::render(), TemplateNodeTabbing::render(), TemplateNodeEncoding::render(), and TemplateNodeTree::renderChildren().
render() [2/2]
void TemplateNodeList::render (TextStream & ts, TemplateContext * c) [inline]
Definition at line 1970 of file template.cpp.
    {
      TRACE(("{TemplateNodeList::render\n"));
      for (const auto &tn : *this)
      {
        tn->render(ts,c);
      }
      TRACE(("}TemplateNodeList::render\n"));
    }
References c, and TRACE.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp