reg::Iterator Class Reference
#include <regex.h>
Public Types
using value_type = Match
using difference_type = std::ptrdiff_t
using pointer = value_type *
using reference = value_type &
using iterator_category = std::forward_iterator_tag
using value_type = Match
using difference_type = std::ptrdiff_t
using pointer = value_type *
using reference = value_type &
using iterator_category = std::forward_iterator_tag
Public Member Functions
Iterator ()
Iterator (const std::string &str, const Ex &re, size_t pos=0)
Iterator (std::string &&str, const Ex &re)=delete
Iterator (const std::string &str, Ex &&re)=delete
Iterator (std::string &&str, Ex &&re)=delete
bool operator== (const Iterator &rhs) const
bool operator!= (const Iterator &rhs) const
const value_type & operator* () const
const value_type * operator-> () const
Iterator & operator++ ()
Iterator ()
Iterator (const std::string &str, const Ex &re, size_t pos=0)
Iterator (std::string &&str, const Ex &re)=delete
Iterator (const std::string &str, Ex &&re)=delete
Iterator (std::string &&str, Ex &&re)=delete
bool operator== (const Iterator &rhs) const
bool operator!= (const Iterator &rhs) const
const value_type & operator* () const
const value_type * operator-> () const
Iterator & operator++ ()
Private Member Functions
void findNext ()
void findNext ()
Private Attributes
const std::string * m_str = nullptr
const Ex * m_re = nullptr
size_t m_pos = std::string::npos
Match m_match
Detailed Description
Iterator class to iterator through matches.
Definition at line 229 of file regex.h.
Member Typedef Documentation
difference_type [1/2]
using reg::Iterator::difference_type = std::ptrdiff_t
Definition at line 233 of file regex.h.
difference_type [2/2]
using reg::Iterator::difference_type = std::ptrdiff_t
Definition at line 233 of file regex.h.
iterator_category [1/2]
using reg::Iterator::iterator_category = std::forward_iterator_tag
Definition at line 236 of file regex.h.
iterator_category [2/2]
using reg::Iterator::iterator_category = std::forward_iterator_tag
Definition at line 236 of file regex.h.
pointer [1/2]
using reg::Iterator::pointer = value_type*
Definition at line 234 of file regex.h.
pointer [2/2]
using reg::Iterator::pointer = value_type*
Definition at line 234 of file regex.h.
reference [1/2]
using reg::Iterator::reference = value_type&
Definition at line 235 of file regex.h.
reference [2/2]
using reg::Iterator::reference = value_type&
Definition at line 235 of file regex.h.
value_type [1/2]
using reg::Iterator::value_type = Match
Definition at line 232 of file regex.h.
value_type [2/2]
using reg::Iterator::value_type = Match
Definition at line 232 of file regex.h.
Constructor & Destructor Documentation
Iterator() [1/10]
reg::Iterator::Iterator () [inline]
Creates an end-of-sequence iterator
Definition at line 239 of file regex.h.
{}
Iterator() [2/10]
reg::Iterator::Iterator (const std::string & str, const Ex & re, size_t pos = 0) [inline]
Creates an iterator for input string str, using regular expression re to search.
Note
the string and regular expression objects should remain valid while iterating.
Definition at line 244 of file regex.h.
      : m_str(&str), m_re(&re), m_pos(pos) { findNext(); }
References findNext().
Iterator() [3/10]
reg::Iterator::Iterator (std::string && str, const Ex & re) [delete]
Iterator() [4/10]
reg::Iterator::Iterator (const std::string & str, Ex && re) [delete]
Iterator() [5/10]
reg::Iterator::Iterator (std::string && str, Ex && re) [delete]
Iterator() [6/10]
reg::Iterator::Iterator () [inline]
Creates an end-of-sequence iterator
Definition at line 239 of file regex.h.
{}
Iterator() [7/10]
reg::Iterator::Iterator (const std::string & str, const Ex & re, size_t pos = 0) [inline]
Creates an iterator for input string str, using regular expression re to search.
Note
the string and regular expression objects should remain valid while iterating.
Definition at line 244 of file regex.h.
      : m_str(&str), m_re(&re), m_pos(pos) { findNext(); }
References findNext().
Iterator() [8/10]
reg::Iterator::Iterator (std::string && str, const Ex & re) [delete]
Iterator() [9/10]
reg::Iterator::Iterator (const std::string & str, Ex && re) [delete]
Iterator() [10/10]
reg::Iterator::Iterator (std::string && str, Ex && re) [delete]
Member Function Documentation
findNext() [1/2]
void reg::Iterator::findNext () [inline], [private]
Definition at line 269 of file regex.h.
    {
      if (!m_re || !m_str) { m_pos=std::string::npos; return; } // end marker
      if (m_re->match(*m_str,m_match,m_pos))
      {
        m_pos=m_match.position()+m_match.length(); // update m_pos to point beyond last match
      }
      else // no more matches, make the iterator point to the 'end-of-sequence'
      {
        m_pos=std::string::npos;
      }
    }
References reg::Match::length(), m_match, m_pos, m_re, m_str, reg::Ex::match(), and reg::Match::position().
Referenced by Iterator(), and operator++().
findNext() [2/2]
void reg::Iterator::findNext () [inline], [private]
Definition at line 269 of file regex.h.
    {
      if (!m_re || !m_str) { m_pos=std::string::npos; return; } // end marker
      if (m_re->match(*m_str,m_match,m_pos))
      {
        m_pos=m_match.position()+m_match.length(); // update m_pos to point beyond last match
      }
      else // no more matches, make the iterator point to the 'end-of-sequence'
      {
        m_pos=std::string::npos;
      }
    }
References reg::Match::length(), m_match, m_pos, m_re, m_str, reg::Ex::match(), and reg::Match::position().
operator!=() [1/2]
bool reg::Iterator::operator!= (const Iterator & rhs) const [inline]
Returns true if the iterators are not pointing to the same match
Definition at line 257 of file regex.h.
{ return rhs.m_pos!=m_pos; }
References m_pos.
operator!=() [2/2]
bool reg::Iterator::operator!= (const Iterator & rhs) const [inline]
Returns true if the iterators are not pointing to the same match
Definition at line 257 of file regex.h.
{ return rhs.m_pos!=m_pos; }
References m_pos.
operator*() [1/2]
const value_type & reg::Iterator::operator* () const [inline]
Returns a reference to the current match
Definition at line 260 of file regex.h.
{ return m_match; }
References m_match.
operator*() [2/2]
const value_type & reg::Iterator::operator* () const [inline]
Returns a reference to the current match
Definition at line 260 of file regex.h.
{ return m_match; }
References m_match.
operator++() [1/2]
Iterator & reg::Iterator::operator++ () [inline]
Advances the iterator to the next match.
Definition at line 266 of file regex.h.
{ findNext(); return *this; }
References findNext().
operator++() [2/2]
Iterator & reg::Iterator::operator++ () [inline]
Advances the iterator to the next match.
Definition at line 266 of file regex.h.
{ findNext(); return *this; }
References findNext().
operator->() [1/2]
const value_type * reg::Iterator::operator-> () const [inline]
Returns a pointer to the current match
Definition at line 263 of file regex.h.
{ return &m_match; }
References m_match.
operator->() [2/2]
const value_type * reg::Iterator::operator-> () const [inline]
Returns a pointer to the current match
Definition at line 263 of file regex.h.
{ return &m_match; }
References m_match.
operator==() [1/2]
bool reg::Iterator::operator== (const Iterator & rhs) const [inline]
Returns true if the iterators point to the same match (or both are end-of-sequence iterators)
Definition at line 254 of file regex.h.
{ return rhs.m_pos==m_pos; }
References m_pos.
operator==() [2/2]
bool reg::Iterator::operator== (const Iterator & rhs) const [inline]
Returns true if the iterators point to the same match (or both are end-of-sequence iterators)
Definition at line 254 of file regex.h.
{ return rhs.m_pos==m_pos; }
References m_pos.
Member Data Documentation
m_match
Match reg::Iterator::m_match [private]
Definition at line 284 of file regex.h.
Referenced by findNext(), operator*(), and operator->().
m_pos
size_t reg::Iterator::m_pos = std::string::npos [private]
Definition at line 283 of file regex.h.
Referenced by findNext(), operator!=(), and operator==().
m_re
const Ex * reg::Iterator::m_re = nullptr [private]
Definition at line 282 of file regex.h.
Referenced by findNext().
m_str
const std::string * reg::Iterator::m_str = nullptr [private]
Definition at line 281 of file regex.h.
Referenced by findNext().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/regex.h
doxygen/src/regex.h