TranslatorAdapter_1_4_6 Class Reference
#include <translator_adapter.h>
Public Member Functions
virtual QCString updateNeededMessage ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString updateNeededMessage ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
Additional Inherited Members
Detailed Description
Adapter class for languages that only contain translations up to version 1.4.6
Definition at line 439 of file translator_adapter.h.
Member Function Documentation
trCallerGraph() [1/2]
virtual QCString TranslatorAdapter_1_4_6::trCallerGraph () [inline], [virtual]
Implements Translator.
Definition at line 445 of file translator_adapter.h.
    {
      return english.trCallerGraph();
    }
References TranslatorAdapterBase::english, and TranslatorEnglish::trCallerGraph().
trCallerGraph() [2/2]
virtual QCString TranslatorAdapter_1_4_6::trCallerGraph () [inline], [virtual]
Implements Translator.
Definition at line 445 of file translator_adapter.h.
    {
      return english.trCallerGraph();
    }
References TranslatorAdapterBase::english, and TranslatorEnglish::trCallerGraph().
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorAdapter_1_4_6::trEnumerationValueDocumentation () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorArabic, TranslatorNorwegian, TranslatorArabic, and TranslatorNorwegian.
Definition at line 449 of file translator_adapter.h.
    {
      return english.trEnumerationValueDocumentation();
    }
References TranslatorAdapterBase::english, and TranslatorEnglish::trEnumerationValueDocumentation().
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorAdapter_1_4_6::trEnumerationValueDocumentation () [inline], [virtual]
Implements Translator.
Reimplemented in TranslatorArabic, TranslatorNorwegian, TranslatorArabic, and TranslatorNorwegian.
Definition at line 449 of file translator_adapter.h.
    {
      return english.trEnumerationValueDocumentation();
    }
References TranslatorAdapterBase::english, and TranslatorEnglish::trEnumerationValueDocumentation().
updateNeededMessage() [1/2]
virtual QCString TranslatorAdapter_1_4_6::updateNeededMessage () [inline], [virtual]
This method is used to generate a warning message to signal the user that the translation of his/her language of choice needs updating. It must be implemented by the translator adapter class (pure virtual).
See also
createUpdateNeededMessage()
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 442 of file translator_adapter.h.
    { return createUpdateNeededMessage(idLanguage(),"release 1.4.6"); }
References TranslatorAdapterBase::createUpdateNeededMessage(), and Translator::idLanguage().
updateNeededMessage() [2/2]
virtual QCString TranslatorAdapter_1_4_6::updateNeededMessage () [inline], [virtual]
This method is used to generate a warning message to signal the user that the translation of his/her language of choice needs updating. It must be implemented by the translator adapter class (pure virtual).
See also
createUpdateNeededMessage()
Reimplemented from TranslatorAdapter_1_6_0.
Definition at line 442 of file translator_adapter.h.
    { return createUpdateNeededMessage(idLanguage(),"release 1.4.6"); }
References TranslatorAdapterBase::createUpdateNeededMessage(), and Translator::idLanguage().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_adapter.h
doxygen/src/translator_adapter.h