HtmlEntityMapper Class Reference
Singleton helper class to map html entities to other formats.
#include <htmlentity.h>
Classes
struct PerlSymb
Public Types
enum SymType {
Sym_Unknown = -1
, Sym_nbsp
, Sym_iexcl
, Sym_cent
,
Sym_pound
, Sym_curren
, Sym_yen
, Sym_brvbar
,
Sym_sect
, Sym_uml
, Sym_copy
, Sym_ordf
,
Sym_laquo
, Sym_not
, Sym_shy
, Sym_reg
,
Sym_macr
, Sym_deg
, Sym_plusmn
, Sym_sup2
,
Sym_sup3
, Sym_acute
, Sym_micro
, Sym_para
,
Sym_middot
, Sym_cedil
, Sym_sup1
, Sym_ordm
,
Sym_raquo
, Sym_frac14
, Sym_frac12
, Sym_frac34
,
Sym_iquest
, Sym_Agrave
, Sym_Aacute
, Sym_Acirc
,
Sym_Atilde
, Sym_Auml
, Sym_Aring
, Sym_AElig
,
Sym_Ccedil
, Sym_Egrave
, Sym_Eacute
, Sym_Ecirc
,
Sym_Euml
, Sym_Igrave
, Sym_Iacute
, Sym_Icirc
,
Sym_Iuml
, Sym_ETH
, Sym_Ntilde
, Sym_Ograve
,
Sym_Oacute
, Sym_Ocirc
, Sym_Otilde
, Sym_Ouml
,
Sym_times
, Sym_Oslash
, Sym_Ugrave
, Sym_Uacute
,
Sym_Ucirc
, Sym_Uuml
, Sym_Yacute
, Sym_THORN
,
Sym_szlig
, Sym_agrave
, Sym_aacute
, Sym_acirc
,
Sym_atilde
, Sym_auml
, Sym_aring
, Sym_aelig
,
Sym_ccedil
, Sym_egrave
, Sym_eacute
, Sym_ecirc
,
Sym_euml
, Sym_igrave
, Sym_iacute
, Sym_icirc
,
Sym_iuml
, Sym_eth
, Sym_ntilde
, Sym_ograve
,
Sym_oacute
, Sym_ocirc
, Sym_otilde
, Sym_ouml
,
Sym_divide
, Sym_oslash
, Sym_ugrave
, Sym_uacute
,
Sym_ucirc
, Sym_uuml
, Sym_yacute
, Sym_thorn
,
Sym_yuml
, Sym_fnof
, Sym_Alpha
, Sym_Beta
,
Sym_Gamma
, Sym_Delta
, Sym_Epsilon
, Sym_Zeta
,
Sym_Eta
, Sym_Theta
, Sym_Iota
, Sym_Kappa
,
Sym_Lambda
, Sym_Mu
, Sym_Nu
, Sym_Xi
,
Sym_Omicron
, Sym_Pi
, Sym_Rho
, Sym_Sigma
,
Sym_Tau
, Sym_Upsilon
, Sym_Phi
, Sym_Chi
,
Sym_Psi
, Sym_Omega
, Sym_alpha
, Sym_beta
,
Sym_gamma
, Sym_delta
, Sym_epsilon
, Sym_zeta
,
Sym_eta
, Sym_theta
, Sym_iota
, Sym_kappa
,
Sym_lambda
, Sym_mu
, Sym_nu
, Sym_xi
,
Sym_omicron
, Sym_pi
, Sym_rho
, Sym_sigmaf
,
Sym_sigma
, Sym_tau
, Sym_upsilon
, Sym_phi
,
Sym_chi
, Sym_psi
, Sym_omega
, Sym_thetasym
,
Sym_upsih
, Sym_piv
, Sym_bull
, Sym_hellip
,
Sym_prime
, Sym_Prime
, Sym_oline
, Sym_frasl
,
Sym_weierp
, Sym_image
, Sym_real
, Sym_trade
,
Sym_alefsym
, Sym_larr
, Sym_uarr
, Sym_rarr
,
Sym_darr
, Sym_harr
, Sym_crarr
, Sym_lArr
,
Sym_uArr
, Sym_rArr
, Sym_dArr
, Sym_hArr
,
Sym_forall
, Sym_part
, Sym_exist
, Sym_empty
,
Sym_nabla
, Sym_isin
, Sym_notin
, Sym_ni
,
Sym_prod
, Sym_sum
, Sym_minus
, Sym_lowast
,
Sym_radic
, Sym_prop
, Sym_infin
, Sym_ang
,
Sym_and
, Sym_or
, Sym_cap
, Sym_cup
,
Sym_int
, Sym_there4
, Sym_sim
, Sym_cong
,
Sym_asymp
, Sym_ne
, Sym_equiv
, Sym_le
,
Sym_ge
, Sym_sub
, Sym_sup
, Sym_nsub
,
Sym_sube
, Sym_supe
, Sym_oplus
, Sym_otimes
,
Sym_perp
, Sym_sdot
, Sym_lceil
, Sym_rceil
,
Sym_lfloor
, Sym_rfloor
, Sym_lang
, Sym_rang
,
Sym_loz
, Sym_spades
, Sym_clubs
, Sym_hearts
,
Sym_diams
, Sym_quot
, Sym_amp
, Sym_lt
,
Sym_gt
, Sym_OElig
, Sym_oelig
, Sym_Scaron
,
Sym_scaron
, Sym_Yuml
, Sym_circ
, Sym_tilde
,
Sym_ensp
, Sym_emsp
, Sym_thinsp
, Sym_zwnj
,
Sym_zwj
, Sym_lrm
, Sym_rlm
, Sym_ndash
,
Sym_mdash
, Sym_lsquo
, Sym_rsquo
, Sym_sbquo
,
Sym_ldquo
, Sym_rdquo
, Sym_bdquo
, Sym_dagger
,
Sym_Dagger
, Sym_permil
, Sym_lsaquo
, Sym_rsaquo
,
Sym_euro
, Sym_tm
, Sym_apos
, Sym_BSlash
,
Sym_At
, Sym_Less
, Sym_Greater
, Sym_Amp
,
Sym_Dollar
, Sym_Hash
, Sym_DoubleColon
, Sym_Percent
,
Sym_Pipe
, Sym_Quot
, Sym_Minus
, Sym_Plus
,
Sym_Dot
, Sym_Colon
, Sym_Equal
, Sym_Unknown = -1
,
Sym_nbsp
, Sym_iexcl
, Sym_cent
, Sym_pound
,
Sym_curren
, Sym_yen
, Sym_brvbar
, Sym_sect
,
Sym_uml
, Sym_copy
, Sym_ordf
, Sym_laquo
,
Sym_not
, Sym_shy
, Sym_reg
, Sym_macr
,
Sym_deg
, Sym_plusmn
, Sym_sup2
, Sym_sup3
,
Sym_acute
, Sym_micro
, Sym_para
, Sym_middot
,
Sym_cedil
, Sym_sup1
, Sym_ordm
, Sym_raquo
,
Sym_frac14
, Sym_frac12
, Sym_frac34
, Sym_iquest
,
Sym_Agrave
, Sym_Aacute
, Sym_Acirc
, Sym_Atilde
,
Sym_Auml
, Sym_Aring
, Sym_AElig
, Sym_Ccedil
,
Sym_Egrave
, Sym_Eacute
, Sym_Ecirc
, Sym_Euml
,
Sym_Igrave
, Sym_Iacute
, Sym_Icirc
, Sym_Iuml
,
Sym_ETH
, Sym_Ntilde
, Sym_Ograve
, Sym_Oacute
,
Sym_Ocirc
, Sym_Otilde
, Sym_Ouml
, Sym_times
,
Sym_Oslash
, Sym_Ugrave
, Sym_Uacute
, Sym_Ucirc
,
Sym_Uuml
, Sym_Yacute
, Sym_THORN
, Sym_szlig
,
Sym_agrave
, Sym_aacute
, Sym_acirc
, Sym_atilde
,
Sym_auml
, Sym_aring
, Sym_aelig
, Sym_ccedil
,
Sym_egrave
, Sym_eacute
, Sym_ecirc
, Sym_euml
,
Sym_igrave
, Sym_iacute
, Sym_icirc
, Sym_iuml
,
Sym_eth
, Sym_ntilde
, Sym_ograve
, Sym_oacute
,
Sym_ocirc
, Sym_otilde
, Sym_ouml
, Sym_divide
,
Sym_oslash
, Sym_ugrave
, Sym_uacute
, Sym_ucirc
,
Sym_uuml
, Sym_yacute
, Sym_thorn
, Sym_yuml
,
Sym_fnof
, Sym_Alpha
, Sym_Beta
, Sym_Gamma
,
Sym_Delta
, Sym_Epsilon
, Sym_Zeta
, Sym_Eta
,
Sym_Theta
, Sym_Iota
, Sym_Kappa
, Sym_Lambda
,
Sym_Mu
, Sym_Nu
, Sym_Xi
, Sym_Omicron
,
Sym_Pi
, Sym_Rho
, Sym_Sigma
, Sym_Tau
,
Sym_Upsilon
, Sym_Phi
, Sym_Chi
, Sym_Psi
,
Sym_Omega
, Sym_alpha
, Sym_beta
, Sym_gamma
,
Sym_delta
, Sym_epsilon
, Sym_zeta
, Sym_eta
,
Sym_theta
, Sym_iota
, Sym_kappa
, Sym_lambda
,
Sym_mu
, Sym_nu
, Sym_xi
, Sym_omicron
,
Sym_pi
, Sym_rho
, Sym_sigmaf
, Sym_sigma
,
Sym_tau
, Sym_upsilon
, Sym_phi
, Sym_chi
,
Sym_psi
, Sym_omega
, Sym_thetasym
, Sym_upsih
,
Sym_piv
, Sym_bull
, Sym_hellip
, Sym_prime
,
Sym_Prime
, Sym_oline
, Sym_frasl
, Sym_weierp
,
Sym_image
, Sym_real
, Sym_trade
, Sym_alefsym
,
Sym_larr
, Sym_uarr
, Sym_rarr
, Sym_darr
,
Sym_harr
, Sym_crarr
, Sym_lArr
, Sym_uArr
,
Sym_rArr
, Sym_dArr
, Sym_hArr
, Sym_forall
,
Sym_part
, Sym_exist
, Sym_empty
, Sym_nabla
,
Sym_isin
, Sym_notin
, Sym_ni
, Sym_prod
,
Sym_sum
, Sym_minus
, Sym_lowast
, Sym_radic
,
Sym_prop
, Sym_infin
, Sym_ang
, Sym_and
,
Sym_or
, Sym_cap
, Sym_cup
, Sym_int
,
Sym_there4
, Sym_sim
, Sym_cong
, Sym_asymp
,
Sym_ne
, Sym_equiv
, Sym_le
, Sym_ge
,
Sym_sub
, Sym_sup
, Sym_nsub
, Sym_sube
,
Sym_supe
, Sym_oplus
, Sym_otimes
, Sym_perp
,
Sym_sdot
, Sym_lceil
, Sym_rceil
, Sym_lfloor
,
Sym_rfloor
, Sym_lang
, Sym_rang
, Sym_loz
,
Sym_spades
, Sym_clubs
, Sym_hearts
, Sym_diams
,
Sym_quot
, Sym_amp
, Sym_lt
, Sym_gt
,
Sym_OElig
, Sym_oelig
, Sym_Scaron
, Sym_scaron
,
Sym_Yuml
, Sym_circ
, Sym_tilde
, Sym_ensp
,
Sym_emsp
, Sym_thinsp
, Sym_zwnj
, Sym_zwj
,
Sym_lrm
, Sym_rlm
, Sym_ndash
, Sym_mdash
,
Sym_lsquo
, Sym_rsquo
, Sym_sbquo
, Sym_ldquo
,
Sym_rdquo
, Sym_bdquo
, Sym_dagger
, Sym_Dagger
,
Sym_permil
, Sym_lsaquo
, Sym_rsaquo
, Sym_euro
,
Sym_tm
, Sym_apos
, Sym_BSlash
, Sym_At
,
Sym_Less
, Sym_Greater
, Sym_Amp
, Sym_Dollar
,
Sym_Hash
, Sym_DoubleColon
, Sym_Percent
, Sym_Pipe
,
Sym_Quot
, Sym_Minus
, Sym_Plus
, Sym_Dot
,
Sym_Colon
, Sym_Equal
 }
enum PerlType {
Perl_unknown = 0
, Perl_string
, Perl_char
, Perl_symbol
,
Perl_umlaut
, Perl_acute
, Perl_grave
, Perl_circ
,
Perl_slash
, Perl_tilde
, Perl_cedilla
, Perl_ring
,
Perl_unknown = 0
, Perl_string
, Perl_char
, Perl_symbol
,
Perl_umlaut
, Perl_acute
, Perl_grave
, Perl_circ
,
Perl_slash
, Perl_tilde
, Perl_cedilla
, Perl_ring
 }
enum SymType {
Sym_Unknown = -1
, Sym_nbsp
, Sym_iexcl
, Sym_cent
,
Sym_pound
, Sym_curren
, Sym_yen
, Sym_brvbar
,
Sym_sect
, Sym_uml
, Sym_copy
, Sym_ordf
,
Sym_laquo
, Sym_not
, Sym_shy
, Sym_reg
,
Sym_macr
, Sym_deg
, Sym_plusmn
, Sym_sup2
,
Sym_sup3
, Sym_acute
, Sym_micro
, Sym_para
,
Sym_middot
, Sym_cedil
, Sym_sup1
, Sym_ordm
,
Sym_raquo
, Sym_frac14
, Sym_frac12
, Sym_frac34
,
Sym_iquest
, Sym_Agrave
, Sym_Aacute
, Sym_Acirc
,
Sym_Atilde
, Sym_Auml
, Sym_Aring
, Sym_AElig
,
Sym_Ccedil
, Sym_Egrave
, Sym_Eacute
, Sym_Ecirc
,
Sym_Euml
, Sym_Igrave
, Sym_Iacute
, Sym_Icirc
,
Sym_Iuml
, Sym_ETH
, Sym_Ntilde
, Sym_Ograve
,
Sym_Oacute
, Sym_Ocirc
, Sym_Otilde
, Sym_Ouml
,
Sym_times
, Sym_Oslash
, Sym_Ugrave
, Sym_Uacute
,
Sym_Ucirc
, Sym_Uuml
, Sym_Yacute
, Sym_THORN
,
Sym_szlig
, Sym_agrave
, Sym_aacute
, Sym_acirc
,
Sym_atilde
, Sym_auml
, Sym_aring
, Sym_aelig
,
Sym_ccedil
, Sym_egrave
, Sym_eacute
, Sym_ecirc
,
Sym_euml
, Sym_igrave
, Sym_iacute
, Sym_icirc
,
Sym_iuml
, Sym_eth
, Sym_ntilde
, Sym_ograve
,
Sym_oacute
, Sym_ocirc
, Sym_otilde
, Sym_ouml
,
Sym_divide
, Sym_oslash
, Sym_ugrave
, Sym_uacute
,
Sym_ucirc
, Sym_uuml
, Sym_yacute
, Sym_thorn
,
Sym_yuml
, Sym_fnof
, Sym_Alpha
, Sym_Beta
,
Sym_Gamma
, Sym_Delta
, Sym_Epsilon
, Sym_Zeta
,
Sym_Eta
, Sym_Theta
, Sym_Iota
, Sym_Kappa
,
Sym_Lambda
, Sym_Mu
, Sym_Nu
, Sym_Xi
,
Sym_Omicron
, Sym_Pi
, Sym_Rho
, Sym_Sigma
,
Sym_Tau
, Sym_Upsilon
, Sym_Phi
, Sym_Chi
,
Sym_Psi
, Sym_Omega
, Sym_alpha
, Sym_beta
,
Sym_gamma
, Sym_delta
, Sym_epsilon
, Sym_zeta
,
Sym_eta
, Sym_theta
, Sym_iota
, Sym_kappa
,
Sym_lambda
, Sym_mu
, Sym_nu
, Sym_xi
,
Sym_omicron
, Sym_pi
, Sym_rho
, Sym_sigmaf
,
Sym_sigma
, Sym_tau
, Sym_upsilon
, Sym_phi
,
Sym_chi
, Sym_psi
, Sym_omega
, Sym_thetasym
,
Sym_upsih
, Sym_piv
, Sym_bull
, Sym_hellip
,
Sym_prime
, Sym_Prime
, Sym_oline
, Sym_frasl
,
Sym_weierp
, Sym_image
, Sym_real
, Sym_trade
,
Sym_alefsym
, Sym_larr
, Sym_uarr
, Sym_rarr
,
Sym_darr
, Sym_harr
, Sym_crarr
, Sym_lArr
,
Sym_uArr
, Sym_rArr
, Sym_dArr
, Sym_hArr
,
Sym_forall
, Sym_part
, Sym_exist
, Sym_empty
,
Sym_nabla
, Sym_isin
, Sym_notin
, Sym_ni
,
Sym_prod
, Sym_sum
, Sym_minus
, Sym_lowast
,
Sym_radic
, Sym_prop
, Sym_infin
, Sym_ang
,
Sym_and
, Sym_or
, Sym_cap
, Sym_cup
,
Sym_int
, Sym_there4
, Sym_sim
, Sym_cong
,
Sym_asymp
, Sym_ne
, Sym_equiv
, Sym_le
,
Sym_ge
, Sym_sub
, Sym_sup
, Sym_nsub
,
Sym_sube
, Sym_supe
, Sym_oplus
, Sym_otimes
,
Sym_perp
, Sym_sdot
, Sym_lceil
, Sym_rceil
,
Sym_lfloor
, Sym_rfloor
, Sym_lang
, Sym_rang
,
Sym_loz
, Sym_spades
, Sym_clubs
, Sym_hearts
,
Sym_diams
, Sym_quot
, Sym_amp
, Sym_lt
,
Sym_gt
, Sym_OElig
, Sym_oelig
, Sym_Scaron
,
Sym_scaron
, Sym_Yuml
, Sym_circ
, Sym_tilde
,
Sym_ensp
, Sym_emsp
, Sym_thinsp
, Sym_zwnj
,
Sym_zwj
, Sym_lrm
, Sym_rlm
, Sym_ndash
,
Sym_mdash
, Sym_lsquo
, Sym_rsquo
, Sym_sbquo
,
Sym_ldquo
, Sym_rdquo
, Sym_bdquo
, Sym_dagger
,
Sym_Dagger
, Sym_permil
, Sym_lsaquo
, Sym_rsaquo
,
Sym_euro
, Sym_tm
, Sym_apos
, Sym_BSlash
,
Sym_At
, Sym_Less
, Sym_Greater
, Sym_Amp
,
Sym_Dollar
, Sym_Hash
, Sym_DoubleColon
, Sym_Percent
,
Sym_Pipe
, Sym_Quot
, Sym_Minus
, Sym_Plus
,
Sym_Dot
, Sym_Colon
, Sym_Equal
, Sym_Unknown = -1
,
Sym_nbsp
, Sym_iexcl
, Sym_cent
, Sym_pound
,
Sym_curren
, Sym_yen
, Sym_brvbar
, Sym_sect
,
Sym_uml
, Sym_copy
, Sym_ordf
, Sym_laquo
,
Sym_not
, Sym_shy
, Sym_reg
, Sym_macr
,
Sym_deg
, Sym_plusmn
, Sym_sup2
, Sym_sup3
,
Sym_acute
, Sym_micro
, Sym_para
, Sym_middot
,
Sym_cedil
, Sym_sup1
, Sym_ordm
, Sym_raquo
,
Sym_frac14
, Sym_frac12
, Sym_frac34
, Sym_iquest
,
Sym_Agrave
, Sym_Aacute
, Sym_Acirc
, Sym_Atilde
,
Sym_Auml
, Sym_Aring
, Sym_AElig
, Sym_Ccedil
,
Sym_Egrave
, Sym_Eacute
, Sym_Ecirc
, Sym_Euml
,
Sym_Igrave
, Sym_Iacute
, Sym_Icirc
, Sym_Iuml
,
Sym_ETH
, Sym_Ntilde
, Sym_Ograve
, Sym_Oacute
,
Sym_Ocirc
, Sym_Otilde
, Sym_Ouml
, Sym_times
,
Sym_Oslash
, Sym_Ugrave
, Sym_Uacute
, Sym_Ucirc
,
Sym_Uuml
, Sym_Yacute
, Sym_THORN
, Sym_szlig
,
Sym_agrave
, Sym_aacute
, Sym_acirc
, Sym_atilde
,
Sym_auml
, Sym_aring
, Sym_aelig
, Sym_ccedil
,
Sym_egrave
, Sym_eacute
, Sym_ecirc
, Sym_euml
,
Sym_igrave
, Sym_iacute
, Sym_icirc
, Sym_iuml
,
Sym_eth
, Sym_ntilde
, Sym_ograve
, Sym_oacute
,
Sym_ocirc
, Sym_otilde
, Sym_ouml
, Sym_divide
,
Sym_oslash
, Sym_ugrave
, Sym_uacute
, Sym_ucirc
,
Sym_uuml
, Sym_yacute
, Sym_thorn
, Sym_yuml
,
Sym_fnof
, Sym_Alpha
, Sym_Beta
, Sym_Gamma
,
Sym_Delta
, Sym_Epsilon
, Sym_Zeta
, Sym_Eta
,
Sym_Theta
, Sym_Iota
, Sym_Kappa
, Sym_Lambda
,
Sym_Mu
, Sym_Nu
, Sym_Xi
, Sym_Omicron
,
Sym_Pi
, Sym_Rho
, Sym_Sigma
, Sym_Tau
,
Sym_Upsilon
, Sym_Phi
, Sym_Chi
, Sym_Psi
,
Sym_Omega
, Sym_alpha
, Sym_beta
, Sym_gamma
,
Sym_delta
, Sym_epsilon
, Sym_zeta
, Sym_eta
,
Sym_theta
, Sym_iota
, Sym_kappa
, Sym_lambda
,
Sym_mu
, Sym_nu
, Sym_xi
, Sym_omicron
,
Sym_pi
, Sym_rho
, Sym_sigmaf
, Sym_sigma
,
Sym_tau
, Sym_upsilon
, Sym_phi
, Sym_chi
,
Sym_psi
, Sym_omega
, Sym_thetasym
, Sym_upsih
,
Sym_piv
, Sym_bull
, Sym_hellip
, Sym_prime
,
Sym_Prime
, Sym_oline
, Sym_frasl
, Sym_weierp
,
Sym_image
, Sym_real
, Sym_trade
, Sym_alefsym
,
Sym_larr
, Sym_uarr
, Sym_rarr
, Sym_darr
,
Sym_harr
, Sym_crarr
, Sym_lArr
, Sym_uArr
,
Sym_rArr
, Sym_dArr
, Sym_hArr
, Sym_forall
,
Sym_part
, Sym_exist
, Sym_empty
, Sym_nabla
,
Sym_isin
, Sym_notin
, Sym_ni
, Sym_prod
,
Sym_sum
, Sym_minus
, Sym_lowast
, Sym_radic
,
Sym_prop
, Sym_infin
, Sym_ang
, Sym_and
,
Sym_or
, Sym_cap
, Sym_cup
, Sym_int
,
Sym_there4
, Sym_sim
, Sym_cong
, Sym_asymp
,
Sym_ne
, Sym_equiv
, Sym_le
, Sym_ge
,
Sym_sub
, Sym_sup
, Sym_nsub
, Sym_sube
,
Sym_supe
, Sym_oplus
, Sym_otimes
, Sym_perp
,
Sym_sdot
, Sym_lceil
, Sym_rceil
, Sym_lfloor
,
Sym_rfloor
, Sym_lang
, Sym_rang
, Sym_loz
,
Sym_spades
, Sym_clubs
, Sym_hearts
, Sym_diams
,
Sym_quot
, Sym_amp
, Sym_lt
, Sym_gt
,
Sym_OElig
, Sym_oelig
, Sym_Scaron
, Sym_scaron
,
Sym_Yuml
, Sym_circ
, Sym_tilde
, Sym_ensp
,
Sym_emsp
, Sym_thinsp
, Sym_zwnj
, Sym_zwj
,
Sym_lrm
, Sym_rlm
, Sym_ndash
, Sym_mdash
,
Sym_lsquo
, Sym_rsquo
, Sym_sbquo
, Sym_ldquo
,
Sym_rdquo
, Sym_bdquo
, Sym_dagger
, Sym_Dagger
,
Sym_permil
, Sym_lsaquo
, Sym_rsaquo
, Sym_euro
,
Sym_tm
, Sym_apos
, Sym_BSlash
, Sym_At
,
Sym_Less
, Sym_Greater
, Sym_Amp
, Sym_Dollar
,
Sym_Hash
, Sym_DoubleColon
, Sym_Percent
, Sym_Pipe
,
Sym_Quot
, Sym_Minus
, Sym_Plus
, Sym_Dot
,
Sym_Colon
, Sym_Equal
 }
enum PerlType {
Perl_unknown = 0
, Perl_string
, Perl_char
, Perl_symbol
,
Perl_umlaut
, Perl_acute
, Perl_grave
, Perl_circ
,
Perl_slash
, Perl_tilde
, Perl_cedilla
, Perl_ring
,
Perl_unknown = 0
, Perl_string
, Perl_char
, Perl_symbol
,
Perl_umlaut
, Perl_acute
, Perl_grave
, Perl_circ
,
Perl_slash
, Perl_tilde
, Perl_cedilla
, Perl_ring
 }
Public Member Functions
SymType name2sym (const QCString &symName) const
Give code of the requested HTML entity name.
const char * utf8 (SymType symb, bool useInPrintf=FALSE) const
Access routine to the UTF8 code of the HTML entity.
const char * html (SymType symb, bool useInPrintf=FALSE) const
Access routine to the html code of the HTML entity.
const char * xml (SymType symb) const
Access routine to the XML code of the HTML entity.
const char * docbook (SymType symb) const
Access routine to the docbook code of the HTML entity.
const char * latex (SymType symb) const
Access routine to the LaTeX code of the HTML entity.
const char * man (SymType symb) const
Access routine to the man code of the HTML entity.
const char * rtf (SymType symb) const
Access routine to the RTF code of the HTML entity.
const PerlSymb * perl (SymType symb) const
Access routine to the perl struct with the perl code of the HTML entity.
void writeXMLSchema (TextStream &t)
SymType name2sym (const QCString &symName) const
const char * utf8 (SymType symb, bool useInPrintf=FALSE) const
const char * html (SymType symb, bool useInPrintf=FALSE) const
const char * xml (SymType symb) const
const char * docbook (SymType symb) const
const char * latex (SymType symb) const
const char * man (SymType symb) const
const char * rtf (SymType symb) const
const PerlSymb * perl (SymType symb) const
void writeXMLSchema (TextStream &t)
Static Public Member Functions
static HtmlEntityMapper * instance ()
static void deleteInstance ()
static HtmlEntityMapper * instance ()
static void deleteInstance ()
Private Member Functions
void validate ()
Routine to check if the entries of the html_entities are numbered correctly.
HtmlEntityMapper ()
~HtmlEntityMapper ()
void validate ()
HtmlEntityMapper ()
~HtmlEntityMapper ()
Private Attributes
std::unordered_map< std::string, SymType > m_name2sym
Static Private Attributes
static HtmlEntityMapper * s_instance = 0
Detailed Description
Singleton helper class to map html entities to other formats.
Definition at line 26 of file htmlentity.h.
Member Enumeration Documentation
PerlType [1/2]
enum HtmlEntityMapper::PerlType
Enumerator
Perl_unknown
Perl_string
Perl_char
Perl_symbol
Perl_umlaut
Perl_acute
Perl_grave
Perl_circ
Perl_slash
Perl_tilde
Perl_cedilla
Perl_ring
Perl_unknown
Perl_string
Perl_char
Perl_symbol
Perl_umlaut
Perl_acute
Perl_grave
Perl_circ
Perl_slash
Perl_tilde
Perl_cedilla
Perl_ring
Definition at line 90 of file htmlentity.h.
                  { Perl_unknown = 0, Perl_string, Perl_char, Perl_symbol, Perl_umlaut,
                    Perl_acute, Perl_grave, Perl_circ, Perl_slash, Perl_tilde,
                    Perl_cedilla, Perl_ring
                  };
PerlType [2/2]
enum HtmlEntityMapper::PerlType
Enumerator
Perl_unknown
Perl_string
Perl_char
Perl_symbol
Perl_umlaut
Perl_acute
Perl_grave
Perl_circ
Perl_slash
Perl_tilde
Perl_cedilla
Perl_ring
Perl_unknown
Perl_string
Perl_char
Perl_symbol
Perl_umlaut
Perl_acute
Perl_grave
Perl_circ
Perl_slash
Perl_tilde
Perl_cedilla
Perl_ring
Definition at line 90 of file htmlentity.h.
                  { Perl_unknown = 0, Perl_string, Perl_char, Perl_symbol, Perl_umlaut,
                    Perl_acute, Perl_grave, Perl_circ, Perl_slash, Perl_tilde,
                    Perl_cedilla, Perl_ring
                  };
SymType [1/2]
enum HtmlEntityMapper::SymType
Enumerator
Sym_Unknown
Sym_nbsp
Sym_iexcl
Sym_cent
Sym_pound
Sym_curren
Sym_yen
Sym_brvbar
Sym_sect
Sym_uml
Sym_copy
Sym_ordf
Sym_laquo
Sym_not
Sym_shy
Sym_reg
Sym_macr
Sym_deg
Sym_plusmn
Sym_sup2
Sym_sup3
Sym_acute
Sym_micro
Sym_para
Sym_middot
Sym_cedil
Sym_sup1
Sym_ordm
Sym_raquo
Sym_frac14
Sym_frac12
Sym_frac34
Sym_iquest
Sym_Agrave
Sym_Aacute
Sym_Acirc
Sym_Atilde
Sym_Auml
Sym_Aring
Sym_AElig
Sym_Ccedil
Sym_Egrave
Sym_Eacute
Sym_Ecirc
Sym_Euml
Sym_Igrave
Sym_Iacute
Sym_Icirc
Sym_Iuml
Sym_ETH
Sym_Ntilde
Sym_Ograve
Sym_Oacute
Sym_Ocirc
Sym_Otilde
Sym_Ouml
Sym_times
Sym_Oslash
Sym_Ugrave
Sym_Uacute
Sym_Ucirc
Sym_Uuml
Sym_Yacute
Sym_THORN
Sym_szlig
Sym_agrave
Sym_aacute
Sym_acirc
Sym_atilde
Sym_auml
Sym_aring
Sym_aelig
Sym_ccedil
Sym_egrave
Sym_eacute
Sym_ecirc
Sym_euml
Sym_igrave
Sym_iacute
Sym_icirc
Sym_iuml
Sym_eth
Sym_ntilde
Sym_ograve
Sym_oacute
Sym_ocirc
Sym_otilde
Sym_ouml
Sym_divide
Sym_oslash
Sym_ugrave
Sym_uacute
Sym_ucirc
Sym_uuml
Sym_yacute
Sym_thorn
Sym_yuml
Sym_fnof
Sym_Alpha
Sym_Beta
Sym_Gamma
Sym_Delta
Sym_Epsilon
Sym_Zeta
Sym_Eta
Sym_Theta
Sym_Iota
Sym_Kappa
Sym_Lambda
Sym_Mu
Sym_Nu
Sym_Xi
Sym_Omicron
Sym_Pi
Sym_Rho
Sym_Sigma
Sym_Tau
Sym_Upsilon
Sym_Phi
Sym_Chi
Sym_Psi
Sym_Omega
Sym_alpha
Sym_beta
Sym_gamma
Sym_delta
Sym_epsilon
Sym_zeta
Sym_eta
Sym_theta
Sym_iota
Sym_kappa
Sym_lambda
Sym_mu
Sym_nu
Sym_xi
Sym_omicron
Sym_pi
Sym_rho
Sym_sigmaf
Sym_sigma
Sym_tau
Sym_upsilon
Sym_phi
Sym_chi
Sym_psi
Sym_omega
Sym_thetasym
Sym_upsih
Sym_piv
Sym_bull
Sym_hellip
Sym_prime
Sym_Prime
Sym_oline
Sym_frasl
Sym_weierp
Sym_image
Sym_real
Sym_trade
Sym_alefsym
Sym_larr
Sym_uarr
Sym_rarr
Sym_darr
Sym_harr
Sym_crarr
Sym_lArr
Sym_uArr
Sym_rArr
Sym_dArr
Sym_hArr
Sym_forall
Sym_part
Sym_exist
Sym_empty
Sym_nabla
Sym_isin
Sym_notin
Sym_ni
Sym_prod
Sym_sum
Sym_minus
Sym_lowast
Sym_radic
Sym_prop
Sym_infin
Sym_ang
Sym_and
Sym_or
Sym_cap
Sym_cup
Sym_int
Sym_there4
Sym_sim
Sym_cong
Sym_asymp
Sym_ne
Sym_equiv
Sym_le
Sym_ge
Sym_sub
Sym_sup
Sym_nsub
Sym_sube
Sym_supe
Sym_oplus
Sym_otimes
Sym_perp
Sym_sdot
Sym_lceil
Sym_rceil
Sym_lfloor
Sym_rfloor
Sym_lang
Sym_rang
Sym_loz
Sym_spades
Sym_clubs
Sym_hearts
Sym_diams
Sym_quot
Sym_amp
Sym_lt
Sym_gt
Sym_OElig
Sym_oelig
Sym_Scaron
Sym_scaron
Sym_Yuml
Sym_circ
Sym_tilde
Sym_ensp
Sym_emsp
Sym_thinsp
Sym_zwnj
Sym_zwj
Sym_lrm
Sym_rlm
Sym_ndash
Sym_mdash
Sym_lsquo
Sym_rsquo
Sym_sbquo
Sym_ldquo
Sym_rdquo
Sym_bdquo
Sym_dagger
Sym_Dagger
Sym_permil
Sym_lsaquo
Sym_rsaquo
Sym_euro
Sym_tm
Sym_apos
Sym_BSlash
Sym_At
Sym_Less
Sym_Greater
Sym_Amp
Sym_Dollar
Sym_Hash
Sym_DoubleColon
Sym_Percent
Sym_Pipe
Sym_Quot
Sym_Minus
Sym_Plus
Sym_Dot
Sym_Colon
Sym_Equal
Sym_Unknown
Sym_nbsp
Sym_iexcl
Sym_cent
Sym_pound
Sym_curren
Sym_yen
Sym_brvbar
Sym_sect
Sym_uml
Sym_copy
Sym_ordf
Sym_laquo
Sym_not
Sym_shy
Sym_reg
Sym_macr
Sym_deg
Sym_plusmn
Sym_sup2
Sym_sup3
Sym_acute
Sym_micro
Sym_para
Sym_middot
Sym_cedil
Sym_sup1
Sym_ordm
Sym_raquo
Sym_frac14
Sym_frac12
Sym_frac34
Sym_iquest
Sym_Agrave
Sym_Aacute
Sym_Acirc
Sym_Atilde
Sym_Auml
Sym_Aring
Sym_AElig
Sym_Ccedil
Sym_Egrave
Sym_Eacute
Sym_Ecirc
Sym_Euml
Sym_Igrave
Sym_Iacute
Sym_Icirc
Sym_Iuml
Sym_ETH
Sym_Ntilde
Sym_Ograve
Sym_Oacute
Sym_Ocirc
Sym_Otilde
Sym_Ouml
Sym_times
Sym_Oslash
Sym_Ugrave
Sym_Uacute
Sym_Ucirc
Sym_Uuml
Sym_Yacute
Sym_THORN
Sym_szlig
Sym_agrave
Sym_aacute
Sym_acirc
Sym_atilde
Sym_auml
Sym_aring
Sym_aelig
Sym_ccedil
Sym_egrave
Sym_eacute
Sym_ecirc
Sym_euml
Sym_igrave
Sym_iacute
Sym_icirc
Sym_iuml
Sym_eth
Sym_ntilde
Sym_ograve
Sym_oacute
Sym_ocirc
Sym_otilde
Sym_ouml
Sym_divide
Sym_oslash
Sym_ugrave
Sym_uacute
Sym_ucirc
Sym_uuml
Sym_yacute
Sym_thorn
Sym_yuml
Sym_fnof
Sym_Alpha
Sym_Beta
Sym_Gamma
Sym_Delta
Sym_Epsilon
Sym_Zeta
Sym_Eta
Sym_Theta
Sym_Iota
Sym_Kappa
Sym_Lambda
Sym_Mu
Sym_Nu
Sym_Xi
Sym_Omicron
Sym_Pi
Sym_Rho
Sym_Sigma
Sym_Tau
Sym_Upsilon
Sym_Phi
Sym_Chi
Sym_Psi
Sym_Omega
Sym_alpha
Sym_beta
Sym_gamma
Sym_delta
Sym_epsilon
Sym_zeta
Sym_eta
Sym_theta
Sym_iota
Sym_kappa
Sym_lambda
Sym_mu
Sym_nu
Sym_xi
Sym_omicron
Sym_pi
Sym_rho
Sym_sigmaf
Sym_sigma
Sym_tau
Sym_upsilon
Sym_phi
Sym_chi
Sym_psi
Sym_omega
Sym_thetasym
Sym_upsih
Sym_piv
Sym_bull
Sym_hellip
Sym_prime
Sym_Prime
Sym_oline
Sym_frasl
Sym_weierp
Sym_image
Sym_real
Sym_trade
Sym_alefsym
Sym_larr
Sym_uarr
Sym_rarr
Sym_darr
Sym_harr
Sym_crarr
Sym_lArr
Sym_uArr
Sym_rArr
Sym_dArr
Sym_hArr
Sym_forall
Sym_part
Sym_exist
Sym_empty
Sym_nabla
Sym_isin
Sym_notin
Sym_ni
Sym_prod
Sym_sum
Sym_minus
Sym_lowast
Sym_radic
Sym_prop
Sym_infin
Sym_ang
Sym_and
Sym_or
Sym_cap
Sym_cup
Sym_int
Sym_there4
Sym_sim
Sym_cong
Sym_asymp
Sym_ne
Sym_equiv
Sym_le
Sym_ge
Sym_sub
Sym_sup
Sym_nsub
Sym_sube
Sym_supe
Sym_oplus
Sym_otimes
Sym_perp
Sym_sdot
Sym_lceil
Sym_rceil
Sym_lfloor
Sym_rfloor
Sym_lang
Sym_rang
Sym_loz
Sym_spades
Sym_clubs
Sym_hearts
Sym_diams
Sym_quot
Sym_amp
Sym_lt
Sym_gt
Sym_OElig
Sym_oelig
Sym_Scaron
Sym_scaron
Sym_Yuml
Sym_circ
Sym_tilde
Sym_ensp
Sym_emsp
Sym_thinsp
Sym_zwnj
Sym_zwj
Sym_lrm
Sym_rlm
Sym_ndash
Sym_mdash
Sym_lsquo
Sym_rsquo
Sym_sbquo
Sym_ldquo
Sym_rdquo
Sym_bdquo
Sym_dagger
Sym_Dagger
Sym_permil
Sym_lsaquo
Sym_rsaquo
Sym_euro
Sym_tm
Sym_apos
Sym_BSlash
Sym_At
Sym_Less
Sym_Greater
Sym_Amp
Sym_Dollar
Sym_Hash
Sym_DoubleColon
Sym_Percent
Sym_Pipe
Sym_Quot
Sym_Minus
Sym_Plus
Sym_Dot
Sym_Colon
Sym_Equal
Definition at line 29 of file htmlentity.h.
                 { Sym_Unknown = -1,
                   Sym_nbsp, Sym_iexcl, Sym_cent, Sym_pound, Sym_curren,
                   Sym_yen, Sym_brvbar, Sym_sect, Sym_uml, Sym_copy,
                   Sym_ordf, Sym_laquo, Sym_not, Sym_shy, Sym_reg,
                   Sym_macr, Sym_deg, Sym_plusmn, Sym_sup2, Sym_sup3,
                   Sym_acute, Sym_micro, Sym_para, Sym_middot, Sym_cedil,
                   Sym_sup1, Sym_ordm, Sym_raquo, Sym_frac14, Sym_frac12,
                   Sym_frac34, Sym_iquest, Sym_Agrave, Sym_Aacute, Sym_Acirc,
                   Sym_Atilde, Sym_Auml, Sym_Aring, Sym_AElig, Sym_Ccedil,
                   Sym_Egrave, Sym_Eacute, Sym_Ecirc, Sym_Euml, Sym_Igrave,
                   Sym_Iacute, Sym_Icirc, Sym_Iuml, Sym_ETH, Sym_Ntilde,
                   Sym_Ograve, Sym_Oacute, Sym_Ocirc, Sym_Otilde, Sym_Ouml,
                   Sym_times, Sym_Oslash, Sym_Ugrave, Sym_Uacute, Sym_Ucirc,
                   Sym_Uuml, Sym_Yacute, Sym_THORN, Sym_szlig, Sym_agrave,
                   Sym_aacute, Sym_acirc, Sym_atilde, Sym_auml, Sym_aring,
                   Sym_aelig, Sym_ccedil, Sym_egrave, Sym_eacute, Sym_ecirc,
                   Sym_euml, Sym_igrave, Sym_iacute, Sym_icirc, Sym_iuml,
                   Sym_eth, Sym_ntilde, Sym_ograve, Sym_oacute, Sym_ocirc,
                   Sym_otilde, Sym_ouml, Sym_divide, Sym_oslash, Sym_ugrave,
                   Sym_uacute, Sym_ucirc, Sym_uuml, Sym_yacute, Sym_thorn,
                   Sym_yuml, Sym_fnof, Sym_Alpha, Sym_Beta, Sym_Gamma,
                   Sym_Delta, Sym_Epsilon, Sym_Zeta, Sym_Eta, Sym_Theta,
                   Sym_Iota, Sym_Kappa, Sym_Lambda, Sym_Mu, Sym_Nu,
                   Sym_Xi, Sym_Omicron, Sym_Pi, Sym_Rho, Sym_Sigma,
                   Sym_Tau, Sym_Upsilon, Sym_Phi, Sym_Chi, Sym_Psi,
                   Sym_Omega, Sym_alpha, Sym_beta, Sym_gamma, Sym_delta,
                   Sym_epsilon, Sym_zeta, Sym_eta, Sym_theta, Sym_iota,
                   Sym_kappa, Sym_lambda, Sym_mu, Sym_nu, Sym_xi,
                   Sym_omicron, Sym_pi, Sym_rho, Sym_sigmaf, Sym_sigma,
                   Sym_tau, Sym_upsilon, Sym_phi, Sym_chi, Sym_psi,
                   Sym_omega, Sym_thetasym, Sym_upsih, Sym_piv, Sym_bull,
                   Sym_hellip, Sym_prime, Sym_Prime, Sym_oline, Sym_frasl,
                   Sym_weierp, Sym_image, Sym_real, Sym_trade, Sym_alefsym,
                   Sym_larr, Sym_uarr, Sym_rarr, Sym_darr, Sym_harr,
                   Sym_crarr, Sym_lArr, Sym_uArr, Sym_rArr, Sym_dArr,
                   Sym_hArr, Sym_forall, Sym_part, Sym_exist, Sym_empty,
                   Sym_nabla, Sym_isin, Sym_notin, Sym_ni, Sym_prod,
                   Sym_sum, Sym_minus, Sym_lowast, Sym_radic, Sym_prop,
                   Sym_infin, Sym_ang, Sym_and, Sym_or, Sym_cap,
                   Sym_cup, Sym_int, Sym_there4, Sym_sim, Sym_cong,
                   Sym_asymp, Sym_ne, Sym_equiv, Sym_le, Sym_ge,
                   Sym_sub, Sym_sup, Sym_nsub, Sym_sube, Sym_supe,
                   Sym_oplus, Sym_otimes, Sym_perp, Sym_sdot, Sym_lceil,
                   Sym_rceil, Sym_lfloor, Sym_rfloor, Sym_lang, Sym_rang,
                   Sym_loz, Sym_spades, Sym_clubs, Sym_hearts, Sym_diams,
                   Sym_quot, Sym_amp, Sym_lt, Sym_gt, Sym_OElig,
                   Sym_oelig, Sym_Scaron, Sym_scaron, Sym_Yuml, Sym_circ,
                   Sym_tilde, Sym_ensp, Sym_emsp, Sym_thinsp, Sym_zwnj,
                   Sym_zwj, Sym_lrm, Sym_rlm, Sym_ndash, Sym_mdash,
                   Sym_lsquo, Sym_rsquo, Sym_sbquo, Sym_ldquo, Sym_rdquo,
                   Sym_bdquo, Sym_dagger, Sym_Dagger, Sym_permil, Sym_lsaquo,
                   Sym_rsaquo, Sym_euro,
                   /* doxygen extensions */
                   Sym_tm, Sym_apos,
                   /* doxygen commands mapped */
                   Sym_BSlash, Sym_At, Sym_Less, Sym_Greater, Sym_Amp,
                   Sym_Dollar, Sym_Hash, Sym_DoubleColon, Sym_Percent, Sym_Pipe,
                   Sym_Quot, Sym_Minus, Sym_Plus, Sym_Dot, Sym_Colon, Sym_Equal
                 };
SymType [2/2]
enum HtmlEntityMapper::SymType
Enumerator
Sym_Unknown
Sym_nbsp
Sym_iexcl
Sym_cent
Sym_pound
Sym_curren
Sym_yen
Sym_brvbar
Sym_sect
Sym_uml
Sym_copy
Sym_ordf
Sym_laquo
Sym_not
Sym_shy
Sym_reg
Sym_macr
Sym_deg
Sym_plusmn
Sym_sup2
Sym_sup3
Sym_acute
Sym_micro
Sym_para
Sym_middot
Sym_cedil
Sym_sup1
Sym_ordm
Sym_raquo
Sym_frac14
Sym_frac12
Sym_frac34
Sym_iquest
Sym_Agrave
Sym_Aacute
Sym_Acirc
Sym_Atilde
Sym_Auml
Sym_Aring
Sym_AElig
Sym_Ccedil
Sym_Egrave
Sym_Eacute
Sym_Ecirc
Sym_Euml
Sym_Igrave
Sym_Iacute
Sym_Icirc
Sym_Iuml
Sym_ETH
Sym_Ntilde
Sym_Ograve
Sym_Oacute
Sym_Ocirc
Sym_Otilde
Sym_Ouml
Sym_times
Sym_Oslash
Sym_Ugrave
Sym_Uacute
Sym_Ucirc
Sym_Uuml
Sym_Yacute
Sym_THORN
Sym_szlig
Sym_agrave
Sym_aacute
Sym_acirc
Sym_atilde
Sym_auml
Sym_aring
Sym_aelig
Sym_ccedil
Sym_egrave
Sym_eacute
Sym_ecirc
Sym_euml
Sym_igrave
Sym_iacute
Sym_icirc
Sym_iuml
Sym_eth
Sym_ntilde
Sym_ograve
Sym_oacute
Sym_ocirc
Sym_otilde
Sym_ouml
Sym_divide
Sym_oslash
Sym_ugrave
Sym_uacute
Sym_ucirc
Sym_uuml
Sym_yacute
Sym_thorn
Sym_yuml
Sym_fnof
Sym_Alpha
Sym_Beta
Sym_Gamma
Sym_Delta
Sym_Epsilon
Sym_Zeta
Sym_Eta
Sym_Theta
Sym_Iota
Sym_Kappa
Sym_Lambda
Sym_Mu
Sym_Nu
Sym_Xi
Sym_Omicron
Sym_Pi
Sym_Rho
Sym_Sigma
Sym_Tau
Sym_Upsilon
Sym_Phi
Sym_Chi
Sym_Psi
Sym_Omega
Sym_alpha
Sym_beta
Sym_gamma
Sym_delta
Sym_epsilon
Sym_zeta
Sym_eta
Sym_theta
Sym_iota
Sym_kappa
Sym_lambda
Sym_mu
Sym_nu
Sym_xi
Sym_omicron
Sym_pi
Sym_rho
Sym_sigmaf
Sym_sigma
Sym_tau
Sym_upsilon
Sym_phi
Sym_chi
Sym_psi
Sym_omega
Sym_thetasym
Sym_upsih
Sym_piv
Sym_bull
Sym_hellip
Sym_prime
Sym_Prime
Sym_oline
Sym_frasl
Sym_weierp
Sym_image
Sym_real
Sym_trade
Sym_alefsym
Sym_larr
Sym_uarr
Sym_rarr
Sym_darr
Sym_harr
Sym_crarr
Sym_lArr
Sym_uArr
Sym_rArr
Sym_dArr
Sym_hArr
Sym_forall
Sym_part
Sym_exist
Sym_empty
Sym_nabla
Sym_isin
Sym_notin
Sym_ni
Sym_prod
Sym_sum
Sym_minus
Sym_lowast
Sym_radic
Sym_prop
Sym_infin
Sym_ang
Sym_and
Sym_or
Sym_cap
Sym_cup
Sym_int
Sym_there4
Sym_sim
Sym_cong
Sym_asymp
Sym_ne
Sym_equiv
Sym_le
Sym_ge
Sym_sub
Sym_sup
Sym_nsub
Sym_sube
Sym_supe
Sym_oplus
Sym_otimes
Sym_perp
Sym_sdot
Sym_lceil
Sym_rceil
Sym_lfloor
Sym_rfloor
Sym_lang
Sym_rang
Sym_loz
Sym_spades
Sym_clubs
Sym_hearts
Sym_diams
Sym_quot
Sym_amp
Sym_lt
Sym_gt
Sym_OElig
Sym_oelig
Sym_Scaron
Sym_scaron
Sym_Yuml
Sym_circ
Sym_tilde
Sym_ensp
Sym_emsp
Sym_thinsp
Sym_zwnj
Sym_zwj
Sym_lrm
Sym_rlm
Sym_ndash
Sym_mdash
Sym_lsquo
Sym_rsquo
Sym_sbquo
Sym_ldquo
Sym_rdquo
Sym_bdquo
Sym_dagger
Sym_Dagger
Sym_permil
Sym_lsaquo
Sym_rsaquo
Sym_euro
Sym_tm
Sym_apos
Sym_BSlash
Sym_At
Sym_Less
Sym_Greater
Sym_Amp
Sym_Dollar
Sym_Hash
Sym_DoubleColon
Sym_Percent
Sym_Pipe
Sym_Quot
Sym_Minus
Sym_Plus
Sym_Dot
Sym_Colon
Sym_Equal
Sym_Unknown
Sym_nbsp
Sym_iexcl
Sym_cent
Sym_pound
Sym_curren
Sym_yen
Sym_brvbar
Sym_sect
Sym_uml
Sym_copy
Sym_ordf
Sym_laquo
Sym_not
Sym_shy
Sym_reg
Sym_macr
Sym_deg
Sym_plusmn
Sym_sup2
Sym_sup3
Sym_acute
Sym_micro
Sym_para
Sym_middot
Sym_cedil
Sym_sup1
Sym_ordm
Sym_raquo
Sym_frac14
Sym_frac12
Sym_frac34
Sym_iquest
Sym_Agrave
Sym_Aacute
Sym_Acirc
Sym_Atilde
Sym_Auml
Sym_Aring
Sym_AElig
Sym_Ccedil
Sym_Egrave
Sym_Eacute
Sym_Ecirc
Sym_Euml
Sym_Igrave
Sym_Iacute
Sym_Icirc
Sym_Iuml
Sym_ETH
Sym_Ntilde
Sym_Ograve
Sym_Oacute
Sym_Ocirc
Sym_Otilde
Sym_Ouml
Sym_times
Sym_Oslash
Sym_Ugrave
Sym_Uacute
Sym_Ucirc
Sym_Uuml
Sym_Yacute
Sym_THORN
Sym_szlig
Sym_agrave
Sym_aacute
Sym_acirc
Sym_atilde
Sym_auml
Sym_aring
Sym_aelig
Sym_ccedil
Sym_egrave
Sym_eacute
Sym_ecirc
Sym_euml
Sym_igrave
Sym_iacute
Sym_icirc
Sym_iuml
Sym_eth
Sym_ntilde
Sym_ograve
Sym_oacute
Sym_ocirc
Sym_otilde
Sym_ouml
Sym_divide
Sym_oslash
Sym_ugrave
Sym_uacute
Sym_ucirc
Sym_uuml
Sym_yacute
Sym_thorn
Sym_yuml
Sym_fnof
Sym_Alpha
Sym_Beta
Sym_Gamma
Sym_Delta
Sym_Epsilon
Sym_Zeta
Sym_Eta
Sym_Theta
Sym_Iota
Sym_Kappa
Sym_Lambda
Sym_Mu
Sym_Nu
Sym_Xi
Sym_Omicron
Sym_Pi
Sym_Rho
Sym_Sigma
Sym_Tau
Sym_Upsilon
Sym_Phi
Sym_Chi
Sym_Psi
Sym_Omega
Sym_alpha
Sym_beta
Sym_gamma
Sym_delta
Sym_epsilon
Sym_zeta
Sym_eta
Sym_theta
Sym_iota
Sym_kappa
Sym_lambda
Sym_mu
Sym_nu
Sym_xi
Sym_omicron
Sym_pi
Sym_rho
Sym_sigmaf
Sym_sigma
Sym_tau
Sym_upsilon
Sym_phi
Sym_chi
Sym_psi
Sym_omega
Sym_thetasym
Sym_upsih
Sym_piv
Sym_bull
Sym_hellip
Sym_prime
Sym_Prime
Sym_oline
Sym_frasl
Sym_weierp
Sym_image
Sym_real
Sym_trade
Sym_alefsym
Sym_larr
Sym_uarr
Sym_rarr
Sym_darr
Sym_harr
Sym_crarr
Sym_lArr
Sym_uArr
Sym_rArr
Sym_dArr
Sym_hArr
Sym_forall
Sym_part
Sym_exist
Sym_empty
Sym_nabla
Sym_isin
Sym_notin
Sym_ni
Sym_prod
Sym_sum
Sym_minus
Sym_lowast
Sym_radic
Sym_prop
Sym_infin
Sym_ang
Sym_and
Sym_or
Sym_cap
Sym_cup
Sym_int
Sym_there4
Sym_sim
Sym_cong
Sym_asymp
Sym_ne
Sym_equiv
Sym_le
Sym_ge
Sym_sub
Sym_sup
Sym_nsub
Sym_sube
Sym_supe
Sym_oplus
Sym_otimes
Sym_perp
Sym_sdot
Sym_lceil
Sym_rceil
Sym_lfloor
Sym_rfloor
Sym_lang
Sym_rang
Sym_loz
Sym_spades
Sym_clubs
Sym_hearts
Sym_diams
Sym_quot
Sym_amp
Sym_lt
Sym_gt
Sym_OElig
Sym_oelig
Sym_Scaron
Sym_scaron
Sym_Yuml
Sym_circ
Sym_tilde
Sym_ensp
Sym_emsp
Sym_thinsp
Sym_zwnj
Sym_zwj
Sym_lrm
Sym_rlm
Sym_ndash
Sym_mdash
Sym_lsquo
Sym_rsquo
Sym_sbquo
Sym_ldquo
Sym_rdquo
Sym_bdquo
Sym_dagger
Sym_Dagger
Sym_permil
Sym_lsaquo
Sym_rsaquo
Sym_euro
Sym_tm
Sym_apos
Sym_BSlash
Sym_At
Sym_Less
Sym_Greater
Sym_Amp
Sym_Dollar
Sym_Hash
Sym_DoubleColon
Sym_Percent
Sym_Pipe
Sym_Quot
Sym_Minus
Sym_Plus
Sym_Dot
Sym_Colon
Sym_Equal
Definition at line 29 of file htmlentity.h.
                 { Sym_Unknown = -1,
                   Sym_nbsp, Sym_iexcl, Sym_cent, Sym_pound, Sym_curren,
                   Sym_yen, Sym_brvbar, Sym_sect, Sym_uml, Sym_copy,
                   Sym_ordf, Sym_laquo, Sym_not, Sym_shy, Sym_reg,
                   Sym_macr, Sym_deg, Sym_plusmn, Sym_sup2, Sym_sup3,
                   Sym_acute, Sym_micro, Sym_para, Sym_middot, Sym_cedil,
                   Sym_sup1, Sym_ordm, Sym_raquo, Sym_frac14, Sym_frac12,
                   Sym_frac34, Sym_iquest, Sym_Agrave, Sym_Aacute, Sym_Acirc,
                   Sym_Atilde, Sym_Auml, Sym_Aring, Sym_AElig, Sym_Ccedil,
                   Sym_Egrave, Sym_Eacute, Sym_Ecirc, Sym_Euml, Sym_Igrave,
                   Sym_Iacute, Sym_Icirc, Sym_Iuml, Sym_ETH, Sym_Ntilde,
                   Sym_Ograve, Sym_Oacute, Sym_Ocirc, Sym_Otilde, Sym_Ouml,
                   Sym_times, Sym_Oslash, Sym_Ugrave, Sym_Uacute, Sym_Ucirc,
                   Sym_Uuml, Sym_Yacute, Sym_THORN, Sym_szlig, Sym_agrave,
                   Sym_aacute, Sym_acirc, Sym_atilde, Sym_auml, Sym_aring,
                   Sym_aelig, Sym_ccedil, Sym_egrave, Sym_eacute, Sym_ecirc,
                   Sym_euml, Sym_igrave, Sym_iacute, Sym_icirc, Sym_iuml,
                   Sym_eth, Sym_ntilde, Sym_ograve, Sym_oacute, Sym_ocirc,
                   Sym_otilde, Sym_ouml, Sym_divide, Sym_oslash, Sym_ugrave,
                   Sym_uacute, Sym_ucirc, Sym_uuml, Sym_yacute, Sym_thorn,
                   Sym_yuml, Sym_fnof, Sym_Alpha, Sym_Beta, Sym_Gamma,
                   Sym_Delta, Sym_Epsilon, Sym_Zeta, Sym_Eta, Sym_Theta,
                   Sym_Iota, Sym_Kappa, Sym_Lambda, Sym_Mu, Sym_Nu,
                   Sym_Xi, Sym_Omicron, Sym_Pi, Sym_Rho, Sym_Sigma,
                   Sym_Tau, Sym_Upsilon, Sym_Phi, Sym_Chi, Sym_Psi,
                   Sym_Omega, Sym_alpha, Sym_beta, Sym_gamma, Sym_delta,
                   Sym_epsilon, Sym_zeta, Sym_eta, Sym_theta, Sym_iota,
                   Sym_kappa, Sym_lambda, Sym_mu, Sym_nu, Sym_xi,
                   Sym_omicron, Sym_pi, Sym_rho, Sym_sigmaf, Sym_sigma,
                   Sym_tau, Sym_upsilon, Sym_phi, Sym_chi, Sym_psi,
                   Sym_omega, Sym_thetasym, Sym_upsih, Sym_piv, Sym_bull,
                   Sym_hellip, Sym_prime, Sym_Prime, Sym_oline, Sym_frasl,
                   Sym_weierp, Sym_image, Sym_real, Sym_trade, Sym_alefsym,
                   Sym_larr, Sym_uarr, Sym_rarr, Sym_darr, Sym_harr,
                   Sym_crarr, Sym_lArr, Sym_uArr, Sym_rArr, Sym_dArr,
                   Sym_hArr, Sym_forall, Sym_part, Sym_exist, Sym_empty,
                   Sym_nabla, Sym_isin, Sym_notin, Sym_ni, Sym_prod,
                   Sym_sum, Sym_minus, Sym_lowast, Sym_radic, Sym_prop,
                   Sym_infin, Sym_ang, Sym_and, Sym_or, Sym_cap,
                   Sym_cup, Sym_int, Sym_there4, Sym_sim, Sym_cong,
                   Sym_asymp, Sym_ne, Sym_equiv, Sym_le, Sym_ge,
                   Sym_sub, Sym_sup, Sym_nsub, Sym_sube, Sym_supe,
                   Sym_oplus, Sym_otimes, Sym_perp, Sym_sdot, Sym_lceil,
                   Sym_rceil, Sym_lfloor, Sym_rfloor, Sym_lang, Sym_rang,
                   Sym_loz, Sym_spades, Sym_clubs, Sym_hearts, Sym_diams,
                   Sym_quot, Sym_amp, Sym_lt, Sym_gt, Sym_OElig,
                   Sym_oelig, Sym_Scaron, Sym_scaron, Sym_Yuml, Sym_circ,
                   Sym_tilde, Sym_ensp, Sym_emsp, Sym_thinsp, Sym_zwnj,
                   Sym_zwj, Sym_lrm, Sym_rlm, Sym_ndash, Sym_mdash,
                   Sym_lsquo, Sym_rsquo, Sym_sbquo, Sym_ldquo, Sym_rdquo,
                   Sym_bdquo, Sym_dagger, Sym_Dagger, Sym_permil, Sym_lsaquo,
                   Sym_rsaquo, Sym_euro,
                   /* doxygen extensions */
                   Sym_tm, Sym_apos,
                   /* doxygen commands mapped */
                   Sym_BSlash, Sym_At, Sym_Less, Sym_Greater, Sym_Amp,
                   Sym_Dollar, Sym_Hash, Sym_DoubleColon, Sym_Percent, Sym_Pipe,
                   Sym_Quot, Sym_Minus, Sym_Plus, Sym_Dot, Sym_Colon, Sym_Equal
                 };
Constructor & Destructor Documentation
HtmlEntityMapper() [1/2]
HtmlEntityMapper::HtmlEntityMapper () [private]
Definition at line 326 of file htmlentity.cpp.
{
  for (int i = 0; i < g_numHtmlEntities; i++)
  {
    m_name2sym.insert(std::make_pair(g_htmlEntities[i].item,g_htmlEntities[i].symb));
  }
  validate();
}
References g_htmlEntities, g_numHtmlEntities, m_name2sym, and validate().
Referenced by instance().
 HtmlEntityMapper() [1/2]
HtmlEntityMapper::~HtmlEntityMapper () [private]
Definition at line 336 of file htmlentity.cpp.
{
}
HtmlEntityMapper() [2/2]
HtmlEntityMapper::HtmlEntityMapper () [private]
 HtmlEntityMapper() [2/2]
HtmlEntityMapper::~HtmlEntityMapper () [private]
Member Function Documentation
deleteInstance() [1/2]
void HtmlEntityMapper::deleteInstance () [static]
Deletes the one and only instance of the HTML entity mapper
Definition at line 351 of file htmlentity.cpp.
{
  delete s_instance;
  s_instance=0;
}
References s_instance.
deleteInstance() [2/2]
static void HtmlEntityMapper::deleteInstance () [static]
docbook() [1/2]
const char * HtmlEntityMapper::docbook (HtmlEntityMapper::SymType symb) const
Access routine to the docbook code of the HTML entity.
Parameters
symb Code of the requested HTML entity
Returns
the docbook code of the HTML entity, in case the docbook code is unknown NULL is returned.
Definition at line 415 of file htmlentity.cpp.
{
  return g_htmlEntities[symb].docbook;
}
References htmlEntityInfo::docbook, and g_htmlEntities.
Referenced by DocbookDocVisitor::operator()().
docbook() [2/2]
const char * HtmlEntityMapper::docbook (SymType symb) const
html() [1/2]
const char * HtmlEntityMapper::html (HtmlEntityMapper::SymType symb, bool useInPrintf = FALSE) const
Access routine to the html code of the HTML entity.
Parameters
symb Code of the requested HTML entity
useInPrintf If TRUE the result will be escaped such that it can be used in a printf string pattern
Returns
the html representation of the HTML entity, in case the html code is unknown NULL is returned.
Definition at line 386 of file htmlentity.cpp.
{
  if (useInPrintf && symb==HtmlEntityMapper::Sym_Percent)
  {
    return "%%"; // escape for printf
  }
  else
  {
    return g_htmlEntities[symb].html;
  }
}
References g_htmlEntities, htmlEntityInfo::html, and Sym_Percent.
Referenced by HtmlDocVisitor::operator()(), and TextDocVisitor::operator()().
html() [2/2]
const char * HtmlEntityMapper::html (SymType symb, bool useInPrintf = FALSE) const
instance() [1/2]
HtmlEntityMapper * HtmlEntityMapper::instance () [static]
Returns the one and only instance of the HTML entity mapper
Definition at line 341 of file htmlentity.cpp.
{
  if (s_instance==0)
  {
    s_instance = new HtmlEntityMapper;
  }
  return s_instance;
}
References HtmlEntityMapper(), and s_instance.
Referenced by convertCharEntitiesToUTF8(), convertToDocBook(), DocSymbol::decodeSymbol(), filterLatexString(), generateXML(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), PerlModDocVisitor::operator()(), RTFDocVisitor::operator()(), TextDocVisitor::operator()(), XmlDocVisitor::operator()(), and PrintDocVisitor::operator()().
instance() [2/2]
static HtmlEntityMapper * HtmlEntityMapper::instance () [static]
latex() [1/2]
const char * HtmlEntityMapper::latex (HtmlEntityMapper::SymType symb) const
Access routine to the LaTeX code of the HTML entity.
Parameters
symb Code of the requested HTML entity
Returns
the LaTeX code of the HTML entity, in case the LaTeX code is unknown NULL is returned.
Definition at line 426 of file htmlentity.cpp.
{
  return g_htmlEntities[symb].latex;
}
References g_htmlEntities, and htmlEntityInfo::latex.
Referenced by filterLatexString(), and LatexDocVisitor::operator()().
latex() [2/2]
const char * HtmlEntityMapper::latex (SymType symb) const
man() [1/2]
const char * HtmlEntityMapper::man (HtmlEntityMapper::SymType symb) const
Access routine to the man code of the HTML entity.
Parameters
symb Code of the requested HTML entity
Returns
the man of the HTML entity, in case the man code is unknown NULL is returned.
Definition at line 437 of file htmlentity.cpp.
{
  return g_htmlEntities[symb].man;
}
References g_htmlEntities, and htmlEntityInfo::man.
Referenced by ManDocVisitor::operator()().
man() [2/2]
const char * HtmlEntityMapper::man (SymType symb) const
name2sym() [1/2]
HtmlEntityMapper::SymType HtmlEntityMapper::name2sym (const QCString & symName) const
Give code of the requested HTML entity name.
Parameters
symName HTML entity name without & and ;
Returns
the code for the requested HTML entity name, in case the requested HTML item does not exist HtmlEntityMapper::Sym_unknown is returned.
Definition at line 471 of file htmlentity.cpp.
{
  auto it = m_name2sym.find(symName.str());
  return it!=m_name2sym.end() ? it->second : HtmlEntityMapper::Sym_Unknown;
}
References m_name2sym, QCString::str(), and Sym_Unknown.
Referenced by convertCharEntitiesToUTF8(), convertToDocBook(), DocSymbol::decodeSymbol(), and filterLatexString().
name2sym() [2/2]
SymType HtmlEntityMapper::name2sym (const QCString & symName) const
perl() [1/2]
const HtmlEntityMapper::PerlSymb * HtmlEntityMapper::perl (HtmlEntityMapper::SymType symb) const
Access routine to the perl struct with the perl code of the HTML entity.
Parameters
symb Code of the requested HTML entity
Returns
the pointer to perl struct with the perl code of the HTML entity, in case the perl code does not exists the NULL pointer is entered in the symb field and in the HtmlEntityMapper::Perl_unknown in the type field.
Definition at line 460 of file htmlentity.cpp.
{
  return &g_htmlEntities[symb].perl;
}
References g_htmlEntities, and htmlEntityInfo::perl.
Referenced by PerlModDocVisitor::operator()().
perl() [2/2]
const PerlSymb * HtmlEntityMapper::perl (SymType symb) const
rtf() [1/2]
const char * HtmlEntityMapper::rtf (HtmlEntityMapper::SymType symb) const
Access routine to the RTF code of the HTML entity.
Parameters
symb Code of the requested HTML entity
Returns
the RTF of the HTML entity, in case the RTF code is unknown NULL is returned.
Definition at line 448 of file htmlentity.cpp.
{
  return g_htmlEntities[symb].rtf;
}
References g_htmlEntities, and htmlEntityInfo::rtf.
Referenced by RTFDocVisitor::operator()().
rtf() [2/2]
const char * HtmlEntityMapper::rtf (SymType symb) const
utf8() [1/2]
const char * HtmlEntityMapper::utf8 (HtmlEntityMapper::SymType symb, bool useInPrintf = FALSE) const
Access routine to the UTF8 code of the HTML entity.
Parameters
symb Code of the requested HTML entity
useInPrintf If TRUE the result will be escaped such that it can be used in a printf string pattern
Returns
the UTF8 code of the HTML entity, in case the UTF code is unknown NULL is returned.
Definition at line 366 of file htmlentity.cpp.
{
  if (useInPrintf && symb==HtmlEntityMapper::Sym_Percent)
  {
    return "%%"; // escape for printf
  }
  else
  {
    return g_htmlEntities[symb].UTF8;
  }
}
References g_htmlEntities, Sym_Percent, and htmlEntityInfo::UTF8.
Referenced by PrintDocVisitor::operator()().
utf8() [2/2]
const char * HtmlEntityMapper::utf8 (SymType symb, bool useInPrintf = FALSE) const
validate() [1/2]
void HtmlEntityMapper::validate () [private]
Routine to check if the entries of the html_entities are numbered correctly.
in case of a mismatch a warning message is given.
Definition at line 493 of file htmlentity.cpp.
{
  for (int i = 0; i < g_numHtmlEntities; i++)
  {
    if (i != g_htmlEntities[i].symb)
    {
      warn_uncond("Internal inconsistency, htmlentries code %d (item=%s)\n",i,g_htmlEntities[i].item);
    }
  }
}
References g_htmlEntities, g_numHtmlEntities, and warn_uncond().
Referenced by HtmlEntityMapper().
validate() [2/2]
void HtmlEntityMapper::validate () [private]
writeXMLSchema() [1/2]
void HtmlEntityMapper::writeXMLSchema (TextStream & t)
Definition at line 477 of file htmlentity.cpp.
{
  for (int i=0;i<g_numHtmlEntities - g_numberHtmlMappedCmds;i++)
  {
    QCString bareName = g_htmlEntities[i].xml;
    if (!bareName.isEmpty() && bareName.at(0)=='<' && bareName.endsWith("/>"))
    {
      bareName = bareName.mid(1,bareName.length()-3); // strip < and />
      t << " <xsd:element name=\"" << bareName << "\" type=\"docEmptyType\" />\n";
    }
  }
}
References QCString::at(), QCString::endsWith(), g_htmlEntities, g_numberHtmlMappedCmds, g_numHtmlEntities, QCString::isEmpty(), QCString::length(), QCString::mid(), and htmlEntityInfo::xml.
Referenced by generateXML().
writeXMLSchema() [2/2]
void HtmlEntityMapper::writeXMLSchema (TextStream & t)
xml() [1/2]
const char * HtmlEntityMapper::xml (HtmlEntityMapper::SymType symb) const
Access routine to the XML code of the HTML entity.
Parameters
symb Code of the requested HTML entity
Returns
the XML code of the HTML entity, in case the XML code is unknown NULL is returned.
Definition at line 404 of file htmlentity.cpp.
{
  return g_htmlEntities[symb].xml;
}
References g_htmlEntities, and htmlEntityInfo::xml.
Referenced by XmlDocVisitor::operator()().
xml() [2/2]
const char * HtmlEntityMapper::xml (SymType symb) const
Member Data Documentation
m_name2sym
std::unordered_map< std::string, SymType > HtmlEntityMapper::m_name2sym [private]
Definition at line 116 of file htmlentity.h.
Referenced by HtmlEntityMapper(), and name2sym().
s_instance
static HtmlEntityMapper * HtmlEntityMapper::s_instance = 0 [static], [private]
Definition at line 115 of file htmlentity.h.
Referenced by deleteInstance(), and instance().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/htmlentity.h
doxygen/src/htmlentity.h
doxygen/build/doxygen/src/htmlentity.cpp
doxygen/src/htmlentity.cpp