MemberListContext::Private Class Reference
Public Member Functions
void addMember (const MemberDef *md)
void addMember (const MemberDef *md)
Additional Inherited Members
Detailed Description
Definition at line 7571 of file context.cpp.
Member Function Documentation
addMember() [1/2]
void MemberListContext::Private::addMember (const MemberDef * md) [inline]
Definition at line 7574 of file context.cpp.
    {
      append(MemberContext::alloc(md));
    }
References MemberContext::alloc(), and GenericNodeListContext::append().
addMember() [2/2]
void MemberListContext::Private::addMember (const MemberDef * md) [inline]
Definition at line 7574 of file context.cpp.
    {
      append(MemberContext::alloc(md));
    }
References MemberContext::alloc().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp