ClassContext::Private Class Reference
Classes
struct Cachable
Public Member Functions
Private (const ClassDef *cd)
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private (const ClassDef *cd)
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private Member Functions
TemplateVariant title () const
TemplateVariant highlight () const
TemplateVariant subHighlight () const
TemplateVariant hasDetails () const
TemplateVariant generatedFromFiles () const
TemplateVariant usedFiles () const
DotClassGraphPtr getClassGraph () const
int numInheritanceNodes () const
TemplateVariant includeInfo () const
TemplateVariant inherits () const
TemplateVariant inheritedBy () const
TemplateVariant unoIDLServices () const
TemplateVariant unoIDLInterfaces () const
TemplateVariant signals () const
TemplateVariant publicTypes () const
TemplateVariant publicMethods () const
TemplateVariant publicStaticMethods () const
TemplateVariant publicAttributes () const
TemplateVariant publicStaticAttributes () const
TemplateVariant publicSlots () const
TemplateVariant protectedTypes () const
TemplateVariant protectedMethods () const
TemplateVariant protectedStaticMethods () const
TemplateVariant protectedAttributes () const
TemplateVariant protectedStaticAttributes () const
TemplateVariant protectedSlots () const
TemplateVariant privateTypes () const
TemplateVariant privateSlots () const
TemplateVariant privateMethods () const
TemplateVariant privateStaticMethods () const
TemplateVariant privateAttributes () const
TemplateVariant privateStaticAttributes () const
TemplateVariant packageTypes () const
TemplateVariant packageMethods () const
TemplateVariant packageStaticMethods () const
TemplateVariant packageAttributes () const
TemplateVariant packageStaticAttributes () const
TemplateVariant properties () const
TemplateVariant events () const
TemplateVariant friends () const
TemplateVariant related () const
TemplateVariant detailedTypedefs () const
TemplateVariant detailedEnums () const
TemplateVariant detailedServices () const
TemplateVariant detailedInterfaces () const
TemplateVariant detailedConstructors () const
TemplateVariant detailedMethods () const
TemplateVariant detailedRelated () const
TemplateVariant detailedVariables () const
TemplateVariant detailedProperties () const
TemplateVariant detailedEvents () const
TemplateVariant classes () const
TemplateVariant innerClasses () const
TemplateVariant compoundType () const
TemplateVariant templateDecls () const
TemplateVariant typeConstraints () const
TemplateVariant examples () const
TemplateVariant members () const
TemplateVariant allMembersList () const
TemplateVariant allMembersFileName () const
TemplateVariant memberGroups () const
TemplateVariant additionalInheritedMembers () const
TemplateVariant isSimple () const
TemplateVariant categoryOf () const
TemplateVariant hasInheritanceDiagram () const
TemplateVariant inheritanceDiagram () const
DotClassGraphPtr getCollaborationGraph () const
TemplateVariant hasCollaborationDiagram () const
TemplateVariant collaborationDiagram () const
TemplateVariant createIncludeInfo () const
TemplateVariant createInheritsList () const
TemplateVariant createInheritedByList () const
DotClassGraphPtr createClassGraph () const
DotClassGraphPtr createCollaborationGraph () const
TemplateVariant createClasses () const
TemplateVariant createInnerClasses () const
TemplateVariant createMemberList (MemberListType type, const QCString &title) const
TemplateVariant createPublicTypes () const
TemplateVariant createPublicMethods () const
TemplateVariant createPublicStaticMethods () const
TemplateVariant createPublicAttributes () const
TemplateVariant createPublicStaticAttributes () const
TemplateVariant createPublicSlots () const
TemplateVariant createUnoIDLServices () const
TemplateVariant createUnoIDLInterfaces () const
TemplateVariant createSignals () const
TemplateVariant createProtectedTypes () const
TemplateVariant createProtectedMethods () const
TemplateVariant createProtectedStaticMethods () const
TemplateVariant createProtectedAttributes () const
TemplateVariant createProtectedStaticAttributes () const
TemplateVariant createProtectedSlots () const
TemplateVariant createPrivateTypes () const
TemplateVariant createPrivateSlots () const
TemplateVariant createPrivateMethods () const
TemplateVariant createPrivateStaticMethods () const
TemplateVariant createPrivateAttributes () const
TemplateVariant createPrivateStaticAttributes () const
TemplateVariant createPackageTypes () const
TemplateVariant createPackageMethods () const
TemplateVariant createPackageStaticMethods () const
TemplateVariant createPackageAttributes () const
TemplateVariant createPackageStaticAttributes () const
TemplateVariant createProperties () const
TemplateVariant createEvents () const
TemplateVariant createFriends () const
TemplateVariant createRelated () const
TemplateVariant createDetailedTypedefs () const
TemplateVariant createDetailedEnums () const
TemplateVariant createDetailedServices () const
TemplateVariant createDetailedInterfaces () const
TemplateVariant createDetailedConstructors () const
TemplateVariant createDetailedMethods () const
TemplateVariant createDetailedRelated () const
TemplateVariant createDetailedVariables () const
TemplateVariant createDetailedProperties () const
TemplateVariant createDetailedEvents () const
TemplateVariant createMemberGroups () const
TemplateVariant createAllMembersList () const
TemplateVariant createTypeConstraints () const
TemplateVariant createExamples () const
void addTemplateDecls (const Definition *d, TemplateVariantList &tl) const
TemplateVariant createTemplateDecls () const
TemplateVariant createAdditionalInheritedMembers () const
void addMembers (MemberList &list, const ClassDef *cd, MemberListType lt) const
TemplateVariant createMembers () const
TemplateVariant createUsedFiles () const
TemplateVariant createCategoryOf () const
int createNumInheritanceNodes () const
TemplateVariant title () const
TemplateVariant highlight () const
TemplateVariant subHighlight () const
TemplateVariant hasDetails () const
TemplateVariant generatedFromFiles () const
TemplateVariant usedFiles () const
DotClassGraphPtr getClassGraph () const
int numInheritanceNodes () const
TemplateVariant includeInfo () const
TemplateVariant inherits () const
TemplateVariant inheritedBy () const
TemplateVariant unoIDLServices () const
TemplateVariant unoIDLInterfaces () const
TemplateVariant signals () const
TemplateVariant publicTypes () const
TemplateVariant publicMethods () const
TemplateVariant publicStaticMethods () const
TemplateVariant publicAttributes () const
TemplateVariant publicStaticAttributes () const
TemplateVariant publicSlots () const
TemplateVariant protectedTypes () const
TemplateVariant protectedMethods () const
TemplateVariant protectedStaticMethods () const
TemplateVariant protectedAttributes () const
TemplateVariant protectedStaticAttributes () const
TemplateVariant protectedSlots () const
TemplateVariant privateTypes () const
TemplateVariant privateSlots () const
TemplateVariant privateMethods () const
TemplateVariant privateStaticMethods () const
TemplateVariant privateAttributes () const
TemplateVariant privateStaticAttributes () const
TemplateVariant packageTypes () const
TemplateVariant packageMethods () const
TemplateVariant packageStaticMethods () const
TemplateVariant packageAttributes () const
TemplateVariant packageStaticAttributes () const
TemplateVariant properties () const
TemplateVariant events () const
TemplateVariant friends () const
TemplateVariant related () const
TemplateVariant detailedTypedefs () const
TemplateVariant detailedEnums () const
TemplateVariant detailedServices () const
TemplateVariant detailedInterfaces () const
TemplateVariant detailedConstructors () const
TemplateVariant detailedMethods () const
TemplateVariant detailedRelated () const
TemplateVariant detailedVariables () const
TemplateVariant detailedProperties () const
TemplateVariant detailedEvents () const
TemplateVariant classes () const
TemplateVariant innerClasses () const
TemplateVariant compoundType () const
TemplateVariant templateDecls () const
TemplateVariant typeConstraints () const
TemplateVariant examples () const
TemplateVariant members () const
TemplateVariant allMembersList () const
TemplateVariant allMembersFileName () const
TemplateVariant memberGroups () const
TemplateVariant additionalInheritedMembers () const
TemplateVariant isSimple () const
TemplateVariant categoryOf () const
TemplateVariant hasInheritanceDiagram () const
TemplateVariant inheritanceDiagram () const
DotClassGraphPtr getCollaborationGraph () const
TemplateVariant hasCollaborationDiagram () const
TemplateVariant collaborationDiagram () const
TemplateVariant createIncludeInfo () const
TemplateVariant createInheritsList () const
TemplateVariant createInheritedByList () const
DotClassGraphPtr createClassGraph () const
DotClassGraphPtr createCollaborationGraph () const
TemplateVariant createClasses () const
TemplateVariant createInnerClasses () const
TemplateVariant createMemberList (MemberListType type, const QCString &title) const
TemplateVariant createPublicTypes () const
TemplateVariant createPublicMethods () const
TemplateVariant createPublicStaticMethods () const
TemplateVariant createPublicAttributes () const
TemplateVariant createPublicStaticAttributes () const
TemplateVariant createPublicSlots () const
TemplateVariant createUnoIDLServices () const
TemplateVariant createUnoIDLInterfaces () const
TemplateVariant createSignals () const
TemplateVariant createProtectedTypes () const
TemplateVariant createProtectedMethods () const
TemplateVariant createProtectedStaticMethods () const
TemplateVariant createProtectedAttributes () const
TemplateVariant createProtectedStaticAttributes () const
TemplateVariant createProtectedSlots () const
TemplateVariant createPrivateTypes () const
TemplateVariant createPrivateSlots () const
TemplateVariant createPrivateMethods () const
TemplateVariant createPrivateStaticMethods () const
TemplateVariant createPrivateAttributes () const
TemplateVariant createPrivateStaticAttributes () const
TemplateVariant createPackageTypes () const
TemplateVariant createPackageMethods () const
TemplateVariant createPackageStaticMethods () const
TemplateVariant createPackageAttributes () const
TemplateVariant createPackageStaticAttributes () const
TemplateVariant createProperties () const
TemplateVariant createEvents () const
TemplateVariant createFriends () const
TemplateVariant createRelated () const
TemplateVariant createDetailedTypedefs () const
TemplateVariant createDetailedEnums () const
TemplateVariant createDetailedServices () const
TemplateVariant createDetailedInterfaces () const
TemplateVariant createDetailedConstructors () const
TemplateVariant createDetailedMethods () const
TemplateVariant createDetailedRelated () const
TemplateVariant createDetailedVariables () const
TemplateVariant createDetailedProperties () const
TemplateVariant createDetailedEvents () const
TemplateVariant createMemberGroups () const
TemplateVariant createAllMembersList () const
TemplateVariant createTypeConstraints () const
TemplateVariant createExamples () const
void addTemplateDecls (const Definition *d, TemplateVariantList &tl) const
TemplateVariant createTemplateDecls () const
TemplateVariant createAdditionalInheritedMembers () const
void addMembers (MemberList &list, const ClassDef *cd, MemberListType lt) const
TemplateVariant createMembers () const
TemplateVariant createUsedFiles () const
TemplateVariant createCategoryOf () const
int createNumInheritanceNodes () const
Private Attributes
const ClassDef * m_classDef
Cachable m_cachable
Static Private Attributes
static const PropertyMap< ClassContext::Private > s_inst
Additional Inherited Members
Detailed Description
Definition at line 1714 of file context.cpp.
Constructor & Destructor Documentation
Private() [1/2]
ClassContext::Private::Private (const ClassDef * cd) [inline]
Definition at line 1717 of file context.cpp.
                                : DefinitionContext<ClassContext::Private>(cd),
       m_classDef(cd)
    {
    }
Private() [2/2]
ClassContext::Private::Private (const ClassDef * cd) [inline]
Definition at line 1717 of file context.cpp.
                                : DefinitionContext<ClassContext::Private>(cd),
       m_classDef(cd)
    {
    }
Member Function Documentation
additionalInheritedMembers() [1/2]
TemplateVariant ClassContext::Private::additionalInheritedMembers () const [inline], [private]
Definition at line 1789 of file context.cpp.
{ return m_cachable.additionalInheritedMembers.get(this); }
References ClassContext::Private::Cachable::additionalInheritedMembers, and m_cachable.
additionalInheritedMembers() [2/2]
TemplateVariant ClassContext::Private::additionalInheritedMembers () const [inline], [private]
Definition at line 1789 of file context.cpp.
{ return m_cachable.additionalInheritedMembers.get(this); }
addMembers() [1/2]
void ClassContext::Private::addMembers (MemberList & list, const ClassDef * cd, MemberListType lt) const [inline], [private]
Definition at line 2269 of file context.cpp.
    {
      const MemberList *ml = cd->getMemberList(lt);
      if (ml)
      {
        for (const auto &md : *ml)
        {
          if (md->isBriefSectionVisible())
          {
            list.push_back(md);
          }
        }
      }
    }
References ClassDef::getMemberList(), and MemberVector::push_back().
Referenced by createMembers().
addMembers() [2/2]
void ClassContext::Private::addMembers (MemberList & list, const ClassDef * cd, MemberListType lt) const [inline], [private]
Definition at line 2269 of file context.cpp.
    {
      const MemberList *ml = cd->getMemberList(lt);
      if (ml)
      {
        for (const auto &md : *ml)
        {
          if (md->isBriefSectionVisible())
          {
            list.push_back(md);
          }
        }
      }
    }
References ClassDef::getMemberList(), and MemberVector::push_back().
addTemplateDecls() [1/2]
void ClassContext::Private::addTemplateDecls (const Definition * d, TemplateVariantList & tl) const [inline], [private]
Definition at line 2205 of file context.cpp.
    {
      if (d->definitionType()==Definition::TypeClass)
      {
        const Definition *parent = d->getOuterScope();
        if (parent)
        {
          addTemplateDecls(parent,tl);
        }
        const ClassDef *cd=toClassDef(d);
        if (!cd->templateArguments().empty())
        {
          TemplateListIntfPtr al = ArgumentListContext::alloc(cd->templateArguments(),cd,relPathAsString());
          // since a TemplateVariant does take ownership of the object, we add it
          // a separate list just to be able to delete it and avoid a memory leak
          tl.push_back(al);
        }
      }
    }
References addTemplateDecls(), ArgumentListContext::alloc(), Definition::definitionType(), ArgumentList::empty(), Definition::getOuterScope(), parent(), DefinitionContext< ClassContext::Private >::relPathAsString(), ClassDef::templateArguments(), toClassDef(), and Definition::TypeClass.
Referenced by addTemplateDecls(), and createTemplateDecls().
addTemplateDecls() [2/2]
void ClassContext::Private::addTemplateDecls (const Definition * d, TemplateVariantList & tl) const [inline], [private]
Definition at line 2205 of file context.cpp.
    {
      if (d->definitionType()==Definition::TypeClass)
      {
        const Definition *parent = d->getOuterScope();
        if (parent)
        {
          addTemplateDecls(parent,tl);
        }
        const ClassDef *cd=toClassDef(d);
        if (!cd->templateArguments().empty())
        {
          TemplateListIntfPtr al = ArgumentListContext::alloc(cd->templateArguments(),cd,relPathAsString());
          // since a TemplateVariant does take ownership of the object, we add it
          // a separate list just to be able to delete it and avoid a memory leak
          tl.push_back(al);
        }
      }
    }
References ArgumentListContext::alloc(), Definition::definitionType(), ArgumentList::empty(), Definition::getOuterScope(), parent(), ClassDef::templateArguments(), toClassDef(), and Definition::TypeClass.
allMembersFileName() [1/2]
TemplateVariant ClassContext::Private::allMembersFileName () const [inline], [private]
Definition at line 1787 of file context.cpp.
{ return m_classDef->getMemberListFileName(); }
References ClassDef::getMemberListFileName(), and m_classDef.
allMembersFileName() [2/2]
TemplateVariant ClassContext::Private::allMembersFileName () const [inline], [private]
Definition at line 1787 of file context.cpp.
{ return m_classDef->getMemberListFileName(); }
allMembersList() [1/2]
TemplateVariant ClassContext::Private::allMembersList () const [inline], [private]
Definition at line 1786 of file context.cpp.
{ return m_cachable.allMembersList.get(this); }
References ClassContext::Private::Cachable::allMembersList, and m_cachable.
allMembersList() [2/2]
TemplateVariant ClassContext::Private::allMembersList () const [inline], [private]
Definition at line 1786 of file context.cpp.
{ return m_cachable.allMembersList.get(this); }
categoryOf() [1/2]
TemplateVariant ClassContext::Private::categoryOf () const [inline], [private]
Definition at line 1791 of file context.cpp.
{ return m_cachable.categoryOf.get(this); }
References ClassContext::Private::Cachable::categoryOf, and m_cachable.
categoryOf() [2/2]
TemplateVariant ClassContext::Private::categoryOf () const [inline], [private]
Definition at line 1791 of file context.cpp.
{ return m_cachable.categoryOf.get(this); }
classes() [1/2]
TemplateVariant ClassContext::Private::classes () const [inline], [private]
Definition at line 1779 of file context.cpp.
{ return m_cachable.classes.get(this); }
References ClassContext::Private::Cachable::classes, and m_cachable.
classes() [2/2]
TemplateVariant ClassContext::Private::classes () const [inline], [private]
Definition at line 1779 of file context.cpp.
{ return m_cachable.classes.get(this); }
collaborationDiagram() [1/2]
TemplateVariant ClassContext::Private::collaborationDiagram () const [inline], [private]
Definition at line 1905 of file context.cpp.
    {
      bool haveDot = Config_getBool(HAVE_DOT);
      TextStream t;
      if (haveDot)
      {
        DotClassGraphPtr cg = getCollaborationGraph();
        switch (g_globals.outputFormat)
        {
          case ContextOutputFormat_Html:
            {
              cg->writeGraph(t,GOF_BITMAP,EOF_Html,
                             g_globals.outputDir,
                             g_globals.outputDir+Portable::pathSeparator()+addHtmlExtensionIfMissing(m_classDef->getOutputFileBase()),
                             relPathAsString(),TRUE,TRUE,g_globals.dynSectionId
                            );
            }
            break;
          case ContextOutputFormat_Latex:
            {
              cg->writeGraph(t,GOF_EPS,EOF_LaTeX,
                             g_globals.outputDir,
                             g_globals.outputDir+Portable::pathSeparator()+m_classDef->getOutputFileBase()+".tex",
                             relPathAsString(),TRUE,TRUE,g_globals.dynSectionId
                            );
            }
            break;
            // TODO: support other generators
          default:
            err("context.cpp: output format not yet supported\n");
            break;
        }
        g_globals.dynSectionId++;
      }
      return TemplateVariant(t.str().c_str(),TRUE);
    }
References addHtmlExtensionIfMissing(), Config_getBool, ContextOutputFormat_Html, ContextOutputFormat_Latex, ContextGlobals::dynSectionId, EOF_Html, EOF_LaTeX, err(), g_globals, getCollaborationGraph(), ClassDef::getOutputFileBase(), GOF_BITMAP, GOF_EPS, m_classDef, ContextGlobals::outputDir, ContextGlobals::outputFormat, Portable::pathSeparator(), DefinitionContext< ClassContext::Private >::relPathAsString(), TextStream::str(), and TRUE.
collaborationDiagram() [2/2]
TemplateVariant ClassContext::Private::collaborationDiagram () const [inline], [private]
Definition at line 1905 of file context.cpp.
    {
      bool haveDot = Config_getBool(HAVE_DOT);
      TextStream t;
      if (haveDot)
      {
        DotClassGraphPtr cg = getCollaborationGraph();
        switch (g_globals.outputFormat)
        {
          case ContextOutputFormat_Html:
            {
              cg->writeGraph(t,GOF_BITMAP,EOF_Html,
                             g_globals.outputDir,
                             g_globals.outputDir+Portable::pathSeparator()+addHtmlExtensionIfMissing(m_classDef->getOutputFileBase()),
                             relPathAsString(),TRUE,TRUE,g_globals.dynSectionId
                            );
            }
            break;
          case ContextOutputFormat_Latex:
            {
              cg->writeGraph(t,GOF_EPS,EOF_LaTeX,
                             g_globals.outputDir,
                             g_globals.outputDir+Portable::pathSeparator()+m_classDef->getOutputFileBase()+".tex",
                             relPathAsString(),TRUE,TRUE,g_globals.dynSectionId
                            );
            }
            break;
            // TODO: support other generators
          default:
            err("context.cpp: output format not yet supported\n");
            break;
        }
        g_globals.dynSectionId++;
      }
      return TemplateVariant(t.str().c_str(),TRUE);
    }
References addHtmlExtensionIfMissing(), Config_getBool, ContextOutputFormat_Html, ContextOutputFormat_Latex, ContextGlobals::dynSectionId, EOF_Html, EOF_LaTeX, err(), g_globals, GOF_BITMAP, GOF_EPS, ContextGlobals::outputDir, ContextGlobals::outputFormat, Portable::pathSeparator(), TextStream::str(), and TRUE.
compoundType() [1/2]
TemplateVariant ClassContext::Private::compoundType () const [inline], [private]
Definition at line 1781 of file context.cpp.
{ return m_classDef->compoundTypeString(); }
References ClassDef::compoundTypeString(), and m_classDef.
compoundType() [2/2]
TemplateVariant ClassContext::Private::compoundType () const [inline], [private]
Definition at line 1781 of file context.cpp.
{ return m_classDef->compoundTypeString(); }
createAdditionalInheritedMembers() [1/2]
TemplateVariant ClassContext::Private::createAdditionalInheritedMembers () const [inline], [private]
Definition at line 2230 of file context.cpp.
    {
      TemplateListIntfPtr list = InheritedMemberInfoListContext::alloc();
      auto ctx = std::dynamic_pointer_cast<InheritedMemberInfoListContext>(list);
      ctx->addMemberList(m_classDef,MemberListType_pubTypes,theTranslator->trPublicTypes());
      ctx->addMemberList(m_classDef,MemberListType_services,theTranslator->trServices());
      ctx->addMemberList(m_classDef,MemberListType_interfaces,theTranslator->trInterfaces());
      ctx->addMemberList(m_classDef,MemberListType_pubSlots,theTranslator->trPublicSlots());
      ctx->addMemberList(m_classDef,MemberListType_signals,theTranslator->trSignals());
      ctx->addMemberList(m_classDef,MemberListType_pubMethods,
        m_classDef->getLanguage()==SrcLangExt_ObjC ? theTranslator->trInstanceMethods()
                                                   : theTranslator->trPublicMembers());
      ctx->addMemberList(m_classDef,MemberListType_pubStaticMethods,
        m_classDef->getLanguage()==SrcLangExt_ObjC ? theTranslator->trClassMethods()
                                                   : theTranslator->trStaticPublicMembers());
      ctx->addMemberList(m_classDef,MemberListType_pubAttribs,theTranslator->trPublicAttribs());
      ctx->addMemberList(m_classDef,MemberListType_pubStaticAttribs,theTranslator->trStaticPublicAttribs());
      ctx->addMemberList(m_classDef,MemberListType_proTypes,theTranslator->trProtectedTypes());
      ctx->addMemberList(m_classDef,MemberListType_proSlots,theTranslator->trProtectedSlots());
      ctx->addMemberList(m_classDef,MemberListType_proMethods,theTranslator->trProtectedMembers());
      ctx->addMemberList(m_classDef,MemberListType_proStaticMethods,theTranslator->trStaticProtectedMembers());
      ctx->addMemberList(m_classDef,MemberListType_proAttribs,theTranslator->trProtectedAttribs());
      ctx->addMemberList(m_classDef,MemberListType_proStaticAttribs,theTranslator->trStaticProtectedAttribs());
      ctx->addMemberList(m_classDef,MemberListType_pacTypes,theTranslator->trPackageTypes());
      ctx->addMemberList(m_classDef,MemberListType_pacMethods,theTranslator->trPackageFunctions());
      ctx->addMemberList(m_classDef,MemberListType_pacStaticMethods,theTranslator->trStaticPackageFunctions());
      ctx->addMemberList(m_classDef,MemberListType_pacAttribs,theTranslator->trPackageAttribs());
      ctx->addMemberList(m_classDef,MemberListType_pacStaticAttribs,theTranslator->trStaticPackageAttribs());
      ctx->addMemberList(m_classDef,MemberListType_properties,theTranslator->trProperties());
      ctx->addMemberList(m_classDef,MemberListType_events,theTranslator->trEvents());
      ctx->addMemberList(m_classDef,MemberListType_priTypes,theTranslator->trPrivateTypes());
      ctx->addMemberList(m_classDef,MemberListType_priSlots,theTranslator->trPrivateSlots());
      ctx->addMemberList(m_classDef,MemberListType_priMethods,theTranslator->trPrivateMembers());
      ctx->addMemberList(m_classDef,MemberListType_priStaticMethods,theTranslator->trStaticPrivateMembers());
      ctx->addMemberList(m_classDef,MemberListType_priAttribs,theTranslator->trPrivateAttribs());
      ctx->addMemberList(m_classDef,MemberListType_priStaticAttribs,theTranslator->trStaticPrivateAttribs());
      ctx->addMemberList(m_classDef,MemberListType_related,theTranslator->trRelatedFunctions());
      return list;
    }
References InheritedMemberInfoListContext::alloc(), Definition::getLanguage(), m_classDef, MemberListType_events, MemberListType_interfaces, MemberListType_pacAttribs, MemberListType_pacMethods, MemberListType_pacStaticAttribs, MemberListType_pacStaticMethods, MemberListType_pacTypes, MemberListType_priAttribs, MemberListType_priMethods, MemberListType_priSlots, MemberListType_priStaticAttribs, MemberListType_priStaticMethods, MemberListType_priTypes, MemberListType_proAttribs, MemberListType_proMethods, MemberListType_properties, MemberListType_proSlots, MemberListType_proStaticAttribs, MemberListType_proStaticMethods, MemberListType_proTypes, MemberListType_pubAttribs, MemberListType_pubMethods, MemberListType_pubSlots, MemberListType_pubStaticAttribs, MemberListType_pubStaticMethods, MemberListType_pubTypes, MemberListType_related, MemberListType_services, MemberListType_signals, SrcLangExt_ObjC, theTranslator, Translator::trClassMethods(), Translator::trEvents(), Translator::trInstanceMethods(), Translator::trInterfaces(), Translator::trPackageAttribs(), Translator::trPackageFunctions(), Translator::trPackageTypes(), Translator::trPrivateAttribs(), Translator::trPrivateMembers(), Translator::trPrivateSlots(), Translator::trPrivateTypes(), Translator::trProperties(), Translator::trProtectedAttribs(), Translator::trProtectedMembers(), Translator::trProtectedSlots(), Translator::trProtectedTypes(), Translator::trPublicAttribs(), Translator::trPublicMembers(), Translator::trPublicSlots(), Translator::trPublicTypes(), Translator::trRelatedFunctions(), Translator::trServices(), Translator::trSignals(), Translator::trStaticPackageAttribs(), Translator::trStaticPackageFunctions(), Translator::trStaticPrivateAttribs(), Translator::trStaticPrivateMembers(), Translator::trStaticProtectedAttribs(), Translator::trStaticProtectedMembers(), Translator::trStaticPublicAttribs(), and Translator::trStaticPublicMembers().
createAdditionalInheritedMembers() [2/2]
TemplateVariant ClassContext::Private::createAdditionalInheritedMembers () const [inline], [private]
Definition at line 2230 of file context.cpp.
    {
      TemplateListIntfPtr list = InheritedMemberInfoListContext::alloc();
      auto ctx = std::dynamic_pointer_cast<InheritedMemberInfoListContext>(list);
      ctx->addMemberList(m_classDef,MemberListType_pubTypes,theTranslator->trPublicTypes());
      ctx->addMemberList(m_classDef,MemberListType_services,theTranslator->trServices());
      ctx->addMemberList(m_classDef,MemberListType_interfaces,theTranslator->trInterfaces());
      ctx->addMemberList(m_classDef,MemberListType_pubSlots,theTranslator->trPublicSlots());
      ctx->addMemberList(m_classDef,MemberListType_signals,theTranslator->trSignals());
      ctx->addMemberList(m_classDef,MemberListType_pubMethods,
        m_classDef->getLanguage()==SrcLangExt_ObjC ? theTranslator->trInstanceMethods()
                                                   : theTranslator->trPublicMembers());
      ctx->addMemberList(m_classDef,MemberListType_pubStaticMethods,
        m_classDef->getLanguage()==SrcLangExt_ObjC ? theTranslator->trClassMethods()
                                                   : theTranslator->trStaticPublicMembers());
      ctx->addMemberList(m_classDef,MemberListType_pubAttribs,theTranslator->trPublicAttribs());
      ctx->addMemberList(m_classDef,MemberListType_pubStaticAttribs,theTranslator->trStaticPublicAttribs());
      ctx->addMemberList(m_classDef,MemberListType_proTypes,theTranslator->trProtectedTypes());
      ctx->addMemberList(m_classDef,MemberListType_proSlots,theTranslator->trProtectedSlots());
      ctx->addMemberList(m_classDef,MemberListType_proMethods,theTranslator->trProtectedMembers());
      ctx->addMemberList(m_classDef,MemberListType_proStaticMethods,theTranslator->trStaticProtectedMembers());
      ctx->addMemberList(m_classDef,MemberListType_proAttribs,theTranslator->trProtectedAttribs());
      ctx->addMemberList(m_classDef,MemberListType_proStaticAttribs,theTranslator->trStaticProtectedAttribs());
      ctx->addMemberList(m_classDef,MemberListType_pacTypes,theTranslator->trPackageTypes());
      ctx->addMemberList(m_classDef,MemberListType_pacMethods,theTranslator->trPackageFunctions());
      ctx->addMemberList(m_classDef,MemberListType_pacStaticMethods,theTranslator->trStaticPackageFunctions());
      ctx->addMemberList(m_classDef,MemberListType_pacAttribs,theTranslator->trPackageAttribs());
      ctx->addMemberList(m_classDef,MemberListType_pacStaticAttribs,theTranslator->trStaticPackageAttribs());
      ctx->addMemberList(m_classDef,MemberListType_properties,theTranslator->trProperties());
      ctx->addMemberList(m_classDef,MemberListType_events,theTranslator->trEvents());
      ctx->addMemberList(m_classDef,MemberListType_priTypes,theTranslator->trPrivateTypes());
      ctx->addMemberList(m_classDef,MemberListType_priSlots,theTranslator->trPrivateSlots());
      ctx->addMemberList(m_classDef,MemberListType_priMethods,theTranslator->trPrivateMembers());
      ctx->addMemberList(m_classDef,MemberListType_priStaticMethods,theTranslator->trStaticPrivateMembers());
      ctx->addMemberList(m_classDef,MemberListType_priAttribs,theTranslator->trPrivateAttribs());
      ctx->addMemberList(m_classDef,MemberListType_priStaticAttribs,theTranslator->trStaticPrivateAttribs());
      ctx->addMemberList(m_classDef,MemberListType_related,theTranslator->trRelatedFunctions());
      return list;
    }
References InheritedMemberInfoListContext::alloc(), MemberListType_events, MemberListType_interfaces, MemberListType_pacAttribs, MemberListType_pacMethods, MemberListType_pacStaticAttribs, MemberListType_pacStaticMethods, MemberListType_pacTypes, MemberListType_priAttribs, MemberListType_priMethods, MemberListType_priSlots, MemberListType_priStaticAttribs, MemberListType_priStaticMethods, MemberListType_priTypes, MemberListType_proAttribs, MemberListType_proMethods, MemberListType_properties, MemberListType_proSlots, MemberListType_proStaticAttribs, MemberListType_proStaticMethods, MemberListType_proTypes, MemberListType_pubAttribs, MemberListType_pubMethods, MemberListType_pubSlots, MemberListType_pubStaticAttribs, MemberListType_pubStaticMethods, MemberListType_pubTypes, MemberListType_related, MemberListType_services, MemberListType_signals, SrcLangExt_ObjC, theTranslator, Translator::trClassMethods(), Translator::trEvents(), Translator::trInstanceMethods(), Translator::trInterfaces(), Translator::trPackageAttribs(), Translator::trPackageFunctions(), Translator::trPackageTypes(), Translator::trPrivateAttribs(), Translator::trPrivateMembers(), Translator::trPrivateSlots(), Translator::trPrivateTypes(), Translator::trProperties(), Translator::trProtectedAttribs(), Translator::trProtectedMembers(), Translator::trProtectedSlots(), Translator::trProtectedTypes(), Translator::trPublicAttribs(), Translator::trPublicMembers(), Translator::trPublicSlots(), Translator::trPublicTypes(), Translator::trRelatedFunctions(), Translator::trServices(), Translator::trSignals(), Translator::trStaticPackageAttribs(), Translator::trStaticPackageFunctions(), Translator::trStaticPrivateAttribs(), Translator::trStaticPrivateMembers(), Translator::trStaticProtectedAttribs(), Translator::trStaticProtectedMembers(), Translator::trStaticPublicAttribs(), and Translator::trStaticPublicMembers().
createAllMembersList() [1/2]
TemplateVariant ClassContext::Private::createAllMembersList () const [inline], [private]
Definition at line 2173 of file context.cpp.
    {
       return AllMembersListContext::alloc(m_classDef->memberNameInfoLinkedMap());
    }
References AllMembersListContext::alloc(), m_classDef, and ClassDef::memberNameInfoLinkedMap().
createAllMembersList() [2/2]
TemplateVariant ClassContext::Private::createAllMembersList () const [inline], [private]
Definition at line 2173 of file context.cpp.
    {
       return AllMembersListContext::alloc(m_classDef->memberNameInfoLinkedMap());
    }
References AllMembersListContext::alloc().
createCategoryOf() [1/2]
TemplateVariant ClassContext::Private::createCategoryOf () const [inline], [private]
Definition at line 2321 of file context.cpp.
    {
      return m_classDef->categoryOf() ?
         TemplateVariant(ClassContext::alloc(m_classDef->categoryOf())) :
         TemplateVariant(FALSE);
    }
References ClassContext::alloc(), ClassDef::categoryOf(), FALSE, and m_classDef.
createCategoryOf() [2/2]
TemplateVariant ClassContext::Private::createCategoryOf () const [inline], [private]
Definition at line 2321 of file context.cpp.
    {
      return m_classDef->categoryOf() ?
         TemplateVariant(ClassContext::alloc(m_classDef->categoryOf())) :
         TemplateVariant(FALSE);
    }
References ClassContext::alloc(), and FALSE.
createClasses() [1/2]
TemplateVariant ClassContext::Private::createClasses () const [inline], [private]
Definition at line 1967 of file context.cpp.
    {
      TemplateVariantList classList;
      classList.reserve(m_classDef->getClasses().size());
      for (const auto &cd : m_classDef->getClasses())
      {
        if (cd->visibleInParentsDeclList())
        {
          classList.push_back(ClassContext::alloc(cd));
        }
      }
      return TemplateImmutableList::alloc(classList);
    }
References ClassContext::alloc(), TemplateImmutableList::alloc(), ClassDef::getClasses(), m_classDef, and LinkedRefMap< T, Hash, KeyEqual, Map >::size().
createClasses() [2/2]
TemplateVariant ClassContext::Private::createClasses () const [inline], [private]
Definition at line 1967 of file context.cpp.
    {
      TemplateVariantList classList;
      classList.reserve(m_classDef->getClasses().size());
      for (const auto &cd : m_classDef->getClasses())
      {
        if (cd->visibleInParentsDeclList())
        {
          classList.push_back(ClassContext::alloc(cd));
        }
      }
      return TemplateImmutableList::alloc(classList);
    }
References ClassContext::alloc(), and TemplateImmutableList::alloc().
createClassGraph() [1/2]
DotClassGraphPtr ClassContext::Private::createClassGraph () const [inline], [private]
Definition at line 1959 of file context.cpp.
    {
      return std::make_shared<DotClassGraph>(m_classDef,Inheritance);
    }
References Inheritance, and m_classDef.
createClassGraph() [2/2]
DotClassGraphPtr ClassContext::Private::createClassGraph () const [inline], [private]
Definition at line 1959 of file context.cpp.
    {
      return std::make_shared<DotClassGraph>(m_classDef,Inheritance);
    }
References Inheritance.
createCollaborationGraph() [1/2]
DotClassGraphPtr ClassContext::Private::createCollaborationGraph () const [inline], [private]
Definition at line 1963 of file context.cpp.
    {
      return std::make_shared<DotClassGraph>(m_classDef,Collaboration);
    }
References Collaboration, and m_classDef.
createCollaborationGraph() [2/2]
DotClassGraphPtr ClassContext::Private::createCollaborationGraph () const [inline], [private]
Definition at line 1963 of file context.cpp.
    {
      return std::make_shared<DotClassGraph>(m_classDef,Collaboration);
    }
References Collaboration.
createDetailedConstructors() [1/2]
TemplateVariant ClassContext::Private::createDetailedConstructors () const [inline], [private]
Definition at line 2143 of file context.cpp.
    {
      return createMemberList(MemberListType_constructors,theTranslator->trConstructorDocumentation());
    }
References createMemberList(), MemberListType_constructors, theTranslator, and Translator::trConstructorDocumentation().
createDetailedConstructors() [2/2]
TemplateVariant ClassContext::Private::createDetailedConstructors () const [inline], [private]
Definition at line 2143 of file context.cpp.
    {
      return createMemberList(MemberListType_constructors,theTranslator->trConstructorDocumentation());
    }
References MemberListType_constructors, theTranslator, and Translator::trConstructorDocumentation().
createDetailedEnums() [1/2]
TemplateVariant ClassContext::Private::createDetailedEnums () const [inline], [private]
Definition at line 2131 of file context.cpp.
    {
      return createMemberList(MemberListType_enumMembers,theTranslator->trMemberEnumerationDocumentation());
    }
References createMemberList(), MemberListType_enumMembers, theTranslator, and Translator::trMemberEnumerationDocumentation().
createDetailedEnums() [2/2]
TemplateVariant ClassContext::Private::createDetailedEnums () const [inline], [private]
Definition at line 2131 of file context.cpp.
    {
      return createMemberList(MemberListType_enumMembers,theTranslator->trMemberEnumerationDocumentation());
    }
References MemberListType_enumMembers, theTranslator, and Translator::trMemberEnumerationDocumentation().
createDetailedEvents() [1/2]
TemplateVariant ClassContext::Private::createDetailedEvents () const [inline], [private]
Definition at line 2163 of file context.cpp.
    {
      return createMemberList(MemberListType_eventMembers,theTranslator->trEventDocumentation());
    }
References createMemberList(), MemberListType_eventMembers, theTranslator, and Translator::trEventDocumentation().
createDetailedEvents() [2/2]
TemplateVariant ClassContext::Private::createDetailedEvents () const [inline], [private]
Definition at line 2163 of file context.cpp.
    {
      return createMemberList(MemberListType_eventMembers,theTranslator->trEventDocumentation());
    }
References MemberListType_eventMembers, theTranslator, and Translator::trEventDocumentation().
createDetailedInterfaces() [1/2]
TemplateVariant ClassContext::Private::createDetailedInterfaces () const [inline], [private]
Definition at line 2139 of file context.cpp.
    {
      return createMemberList(MemberListType_interfaceMembers,theTranslator->trInterfaces());
    }
References createMemberList(), MemberListType_interfaceMembers, theTranslator, and Translator::trInterfaces().
createDetailedInterfaces() [2/2]
TemplateVariant ClassContext::Private::createDetailedInterfaces () const [inline], [private]
Definition at line 2139 of file context.cpp.
    {
      return createMemberList(MemberListType_interfaceMembers,theTranslator->trInterfaces());
    }
References MemberListType_interfaceMembers, theTranslator, and Translator::trInterfaces().
createDetailedMethods() [1/2]
TemplateVariant ClassContext::Private::createDetailedMethods () const [inline], [private]
Definition at line 2147 of file context.cpp.
    {
      return createMemberList(MemberListType_functionMembers,theTranslator->trMemberFunctionDocumentation());
    }
References createMemberList(), MemberListType_functionMembers, theTranslator, and Translator::trMemberFunctionDocumentation().
createDetailedMethods() [2/2]
TemplateVariant ClassContext::Private::createDetailedMethods () const [inline], [private]
Definition at line 2147 of file context.cpp.
    {
      return createMemberList(MemberListType_functionMembers,theTranslator->trMemberFunctionDocumentation());
    }
References MemberListType_functionMembers, theTranslator, and Translator::trMemberFunctionDocumentation().
createDetailedProperties() [1/2]
TemplateVariant ClassContext::Private::createDetailedProperties () const [inline], [private]
Definition at line 2159 of file context.cpp.
    {
      return createMemberList(MemberListType_propertyMembers,theTranslator->trPropertyDocumentation());
    }
References createMemberList(), MemberListType_propertyMembers, theTranslator, and Translator::trPropertyDocumentation().
createDetailedProperties() [2/2]
TemplateVariant ClassContext::Private::createDetailedProperties () const [inline], [private]
Definition at line 2159 of file context.cpp.
    {
      return createMemberList(MemberListType_propertyMembers,theTranslator->trPropertyDocumentation());
    }
References MemberListType_propertyMembers, theTranslator, and Translator::trPropertyDocumentation().
createDetailedRelated() [1/2]
TemplateVariant ClassContext::Private::createDetailedRelated () const [inline], [private]
Definition at line 2151 of file context.cpp.
    {
      return createMemberList(MemberListType_relatedMembers,theTranslator->trRelatedFunctionDocumentation());
    }
References createMemberList(), MemberListType_relatedMembers, theTranslator, and Translator::trRelatedFunctionDocumentation().
createDetailedRelated() [2/2]
TemplateVariant ClassContext::Private::createDetailedRelated () const [inline], [private]
Definition at line 2151 of file context.cpp.
    {
      return createMemberList(MemberListType_relatedMembers,theTranslator->trRelatedFunctionDocumentation());
    }
References MemberListType_relatedMembers, theTranslator, and Translator::trRelatedFunctionDocumentation().
createDetailedServices() [1/2]
TemplateVariant ClassContext::Private::createDetailedServices () const [inline], [private]
Definition at line 2135 of file context.cpp.
    {
      return createMemberList(MemberListType_serviceMembers,theTranslator->trServices());
    }
References createMemberList(), MemberListType_serviceMembers, theTranslator, and Translator::trServices().
createDetailedServices() [2/2]
TemplateVariant ClassContext::Private::createDetailedServices () const [inline], [private]
Definition at line 2135 of file context.cpp.
    {
      return createMemberList(MemberListType_serviceMembers,theTranslator->trServices());
    }
References MemberListType_serviceMembers, theTranslator, and Translator::trServices().
createDetailedTypedefs() [1/2]
TemplateVariant ClassContext::Private::createDetailedTypedefs () const [inline], [private]
Definition at line 2127 of file context.cpp.
    {
      return createMemberList(MemberListType_typedefMembers,theTranslator->trMemberTypedefDocumentation());
    }
References createMemberList(), MemberListType_typedefMembers, theTranslator, and Translator::trMemberTypedefDocumentation().
createDetailedTypedefs() [2/2]
TemplateVariant ClassContext::Private::createDetailedTypedefs () const [inline], [private]
Definition at line 2127 of file context.cpp.
    {
      return createMemberList(MemberListType_typedefMembers,theTranslator->trMemberTypedefDocumentation());
    }
References MemberListType_typedefMembers, theTranslator, and Translator::trMemberTypedefDocumentation().
createDetailedVariables() [1/2]
TemplateVariant ClassContext::Private::createDetailedVariables () const [inline], [private]
Definition at line 2155 of file context.cpp.
    {
      return createMemberList(MemberListType_variableMembers,theTranslator->trMemberDataDocumentation());
    }
References createMemberList(), MemberListType_variableMembers, theTranslator, and Translator::trMemberDataDocumentation().
createDetailedVariables() [2/2]
TemplateVariant ClassContext::Private::createDetailedVariables () const [inline], [private]
Definition at line 2155 of file context.cpp.
    {
      return createMemberList(MemberListType_variableMembers,theTranslator->trMemberDataDocumentation());
    }
References MemberListType_variableMembers, theTranslator, and Translator::trMemberDataDocumentation().
createEvents() [1/2]
TemplateVariant ClassContext::Private::createEvents () const [inline], [private]
Definition at line 2115 of file context.cpp.
    {
      return createMemberList(MemberListType_events,theTranslator->trEvents());
    }
References createMemberList(), MemberListType_events, theTranslator, and Translator::trEvents().
createEvents() [2/2]
TemplateVariant ClassContext::Private::createEvents () const [inline], [private]
Definition at line 2115 of file context.cpp.
    {
      return createMemberList(MemberListType_events,theTranslator->trEvents());
    }
References MemberListType_events, theTranslator, and Translator::trEvents().
createExamples() [1/2]
TemplateVariant ClassContext::Private::createExamples () const [inline], [private]
Definition at line 2183 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_classDef->getExamples().size());
      if (m_classDef->hasExamples())
      {
        for (const auto &ex : m_classDef->getExamples())
        {
          TemplateStructIntfPtr s = TemplateImmutableStruct::alloc(
          {
            { "text", TemplateVariant(ex.name) },
            { "isLinkable", TemplateVariant(TRUE) },
            { "anchor", TemplateVariant(ex.anchor) },
            { "fileName", TemplateVariant(ex.file) },
            { "isReference", TemplateVariant(FALSE) },
            { "externalReference", TemplateVariant("") }
          });
          list.push_back(s);
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References TemplateImmutableStruct::alloc(), TemplateImmutableList::alloc(), FALSE, ClassDef::getExamples(), ClassDef::hasExamples(), m_classDef, s, and TRUE.
createExamples() [2/2]
TemplateVariant ClassContext::Private::createExamples () const [inline], [private]
Definition at line 2183 of file context.cpp.
    {
      TemplateVariantList list;
      list.reserve(m_classDef->getExamples().size());
      if (m_classDef->hasExamples())
      {
        for (const auto &ex : m_classDef->getExamples())
        {
          TemplateStructIntfPtr s = TemplateImmutableStruct::alloc(
          {
            { "text", TemplateVariant(ex.name) },
            { "isLinkable", TemplateVariant(TRUE) },
            { "anchor", TemplateVariant(ex.anchor) },
            { "fileName", TemplateVariant(ex.file) },
            { "isReference", TemplateVariant(FALSE) },
            { "externalReference", TemplateVariant("") }
          });
          list.push_back(s);
        }
      }
      return TemplateImmutableList::alloc(list);
    }
References TemplateImmutableStruct::alloc(), TemplateImmutableList::alloc(), FALSE, s, and TRUE.
createFriends() [1/2]
TemplateVariant ClassContext::Private::createFriends () const [inline], [private]
Definition at line 2119 of file context.cpp.
    {
      return createMemberList(MemberListType_friends,theTranslator->trFriends());
    }
References createMemberList(), MemberListType_friends, theTranslator, and Translator::trFriends().
createFriends() [2/2]
TemplateVariant ClassContext::Private::createFriends () const [inline], [private]
Definition at line 2119 of file context.cpp.
    {
      return createMemberList(MemberListType_friends,theTranslator->trFriends());
    }
References MemberListType_friends, theTranslator, and Translator::trFriends().
createIncludeInfo() [1/2]
TemplateVariant ClassContext::Private::createIncludeInfo () const [inline], [private]
Definition at line 1945 of file context.cpp.
    {
      return m_classDef->includeInfo() ?
             IncludeInfoContext::alloc(m_classDef->includeInfo(),m_classDef->getLanguage()) :
             TemplateVariant(false);
    }
References IncludeInfoContext::alloc(), Definition::getLanguage(), ClassDef::includeInfo(), and m_classDef.
createIncludeInfo() [2/2]
TemplateVariant ClassContext::Private::createIncludeInfo () const [inline], [private]
Definition at line 1945 of file context.cpp.
    {
      return m_classDef->includeInfo() ?
             IncludeInfoContext::alloc(m_classDef->includeInfo(),m_classDef->getLanguage()) :
             TemplateVariant(false);
    }
References IncludeInfoContext::alloc().
createInheritedByList() [1/2]
TemplateVariant ClassContext::Private::createInheritedByList () const [inline], [private]
Definition at line 1955 of file context.cpp.
    {
      return InheritanceListContext::alloc(m_classDef->subClasses(),FALSE);
    }
References InheritanceListContext::alloc(), FALSE, m_classDef, and ClassDef::subClasses().
createInheritedByList() [2/2]
TemplateVariant ClassContext::Private::createInheritedByList () const [inline], [private]
Definition at line 1955 of file context.cpp.
    {
      return InheritanceListContext::alloc(m_classDef->subClasses(),FALSE);
    }
References InheritanceListContext::alloc(), and FALSE.
createInheritsList() [1/2]
TemplateVariant ClassContext::Private::createInheritsList () const [inline], [private]
Definition at line 1951 of file context.cpp.
    {
      return InheritanceListContext::alloc(m_classDef->baseClasses(),TRUE);
    }
References InheritanceListContext::alloc(), ClassDef::baseClasses(), m_classDef, and TRUE.
createInheritsList() [2/2]
TemplateVariant ClassContext::Private::createInheritsList () const [inline], [private]
Definition at line 1951 of file context.cpp.
    {
      return InheritanceListContext::alloc(m_classDef->baseClasses(),TRUE);
    }
References InheritanceListContext::alloc(), and TRUE.
createInnerClasses() [1/2]
TemplateVariant ClassContext::Private::createInnerClasses () const [inline], [private]
Definition at line 1980 of file context.cpp.
    {
      TemplateVariantList classList;
      classList.reserve(m_classDef->getClasses().size());
      for (const auto &cd : m_classDef->getClasses())
      {
        if (!cd->isAnonymous() &&
            cd->isLinkableInProject() &&
            cd->isEmbeddedInOuterScope() &&
            cd->partOfGroups().empty()
           )
        {
          classList.push_back(ClassContext::alloc(cd));
        }
      }
      return TemplateImmutableList::alloc(classList);
    }
References ClassContext::alloc(), TemplateImmutableList::alloc(), ClassDef::getClasses(), m_classDef, and LinkedRefMap< T, Hash, KeyEqual, Map >::size().
createInnerClasses() [2/2]
TemplateVariant ClassContext::Private::createInnerClasses () const [inline], [private]
Definition at line 1980 of file context.cpp.
    {
      TemplateVariantList classList;
      classList.reserve(m_classDef->getClasses().size());
      for (const auto &cd : m_classDef->getClasses())
      {
        if (!cd->isAnonymous() &&
            cd->isLinkableInProject() &&
            cd->isEmbeddedInOuterScope() &&
            cd->partOfGroups().empty()
           )
        {
          classList.push_back(ClassContext::alloc(cd));
        }
      }
      return TemplateImmutableList::alloc(classList);
    }
References ClassContext::alloc(), and TemplateImmutableList::alloc().
createMemberGroups() [1/2]
TemplateVariant ClassContext::Private::createMemberGroups () const [inline], [private]
Definition at line 2167 of file context.cpp.
    {
      return !m_classDef->getMemberGroups().empty() ?
        MemberGroupListContext::alloc(m_classDef,relPathAsString(),m_classDef->getMemberGroups(),m_classDef->subGrouping()) :
        MemberGroupListContext::alloc();
    }
References MemberGroupListContext::alloc(), ClassDef::getMemberGroups(), m_classDef, DefinitionContext< ClassContext::Private >::relPathAsString(), and ClassDef::subGrouping().
createMemberGroups() [2/2]
TemplateVariant ClassContext::Private::createMemberGroups () const [inline], [private]
Definition at line 2167 of file context.cpp.
    {
      return !m_classDef->getMemberGroups().empty() ?
        MemberGroupListContext::alloc(m_classDef,relPathAsString(),m_classDef->getMemberGroups(),m_classDef->subGrouping()) :
        MemberGroupListContext::alloc();
    }
References MemberGroupListContext::alloc().
createMemberList() [1/2]
TemplateVariant ClassContext::Private::createMemberList (MemberListType type, const QCString & title) const [inline], [private]
Definition at line 1997 of file context.cpp.
    {
      const MemberList *ml = m_classDef->getMemberList(type);
      return ml ? TemplateVariant(MemberListInfoContext::alloc(m_classDef,relPathAsString(),ml,title,""))
                : TemplateVariant(false);
    }
References MemberListInfoContext::alloc(), ClassDef::getMemberList(), m_classDef, DefinitionContext< ClassContext::Private >::relPathAsString(), and title().
Referenced by createDetailedConstructors(), createDetailedEnums(), createDetailedEvents(), createDetailedInterfaces(), createDetailedMethods(), createDetailedProperties(), createDetailedRelated(), createDetailedServices(), createDetailedTypedefs(), createDetailedVariables(), createEvents(), createFriends(), createPackageAttributes(), createPackageMethods(), createPackageStaticAttributes(), createPackageStaticMethods(), createPackageTypes(), createPrivateAttributes(), createPrivateMethods(), createPrivateSlots(), createPrivateStaticAttributes(), createPrivateStaticMethods(), createPrivateTypes(), createProperties(), createProtectedAttributes(), createProtectedMethods(), createProtectedSlots(), createProtectedStaticAttributes(), createProtectedStaticMethods(), createProtectedTypes(), createPublicAttributes(), createPublicMethods(), createPublicSlots(), createPublicStaticAttributes(), createPublicStaticMethods(), createPublicTypes(), createRelated(), createSignals(), createUnoIDLInterfaces(), and createUnoIDLServices().
createMemberList() [2/2]
TemplateVariant ClassContext::Private::createMemberList (MemberListType type, const QCString & title) const [inline], [private]
Definition at line 1997 of file context.cpp.
    {
      const MemberList *ml = m_classDef->getMemberList(type);
      return ml ? TemplateVariant(MemberListInfoContext::alloc(m_classDef,relPathAsString(),ml,title,""))
                : TemplateVariant(false);
    }
References MemberListInfoContext::alloc().
createMembers() [1/2]
TemplateVariant ClassContext::Private::createMembers () const [inline], [private]
Definition at line 2283 of file context.cpp.
    {
      MemberList list(MemberListType_allMembersList,MemberListContainer::Class);
      addMembers(list,m_classDef,MemberListType_pubTypes);
      addMembers(list,m_classDef,MemberListType_services);
      addMembers(list,m_classDef,MemberListType_interfaces);
      addMembers(list,m_classDef,MemberListType_pubSlots);
      addMembers(list,m_classDef,MemberListType_signals);
      addMembers(list,m_classDef,MemberListType_pubMethods);
      addMembers(list,m_classDef,MemberListType_pubStaticMethods);
      addMembers(list,m_classDef,MemberListType_pubAttribs);
      addMembers(list,m_classDef,MemberListType_pubStaticAttribs);
      addMembers(list,m_classDef,MemberListType_proTypes);
      addMembers(list,m_classDef,MemberListType_proSlots);
      addMembers(list,m_classDef,MemberListType_proMethods);
      addMembers(list,m_classDef,MemberListType_proStaticMethods);
      addMembers(list,m_classDef,MemberListType_proAttribs);
      addMembers(list,m_classDef,MemberListType_proStaticAttribs);
      addMembers(list,m_classDef,MemberListType_pacTypes);
      addMembers(list,m_classDef,MemberListType_pacMethods);
      addMembers(list,m_classDef,MemberListType_pacStaticMethods);
      addMembers(list,m_classDef,MemberListType_pacAttribs);
      addMembers(list,m_classDef,MemberListType_pacStaticAttribs);
      addMembers(list,m_classDef,MemberListType_properties);
      addMembers(list,m_classDef,MemberListType_events);
      addMembers(list,m_classDef,MemberListType_priTypes);
      addMembers(list,m_classDef,MemberListType_priSlots);
      addMembers(list,m_classDef,MemberListType_priMethods);
      addMembers(list,m_classDef,MemberListType_priStaticMethods);
      addMembers(list,m_classDef,MemberListType_priAttribs);
      addMembers(list,m_classDef,MemberListType_priStaticAttribs);
      addMembers(list,m_classDef,MemberListType_related);
      return MemberListContext::alloc(list);
    }
References addMembers(), MemberListContext::alloc(), Class, m_classDef, MemberListType_allMembersList, MemberListType_events, MemberListType_interfaces, MemberListType_pacAttribs, MemberListType_pacMethods, MemberListType_pacStaticAttribs, MemberListType_pacStaticMethods, MemberListType_pacTypes, MemberListType_priAttribs, MemberListType_priMethods, MemberListType_priSlots, MemberListType_priStaticAttribs, MemberListType_priStaticMethods, MemberListType_priTypes, MemberListType_proAttribs, MemberListType_proMethods, MemberListType_properties, MemberListType_proSlots, MemberListType_proStaticAttribs, MemberListType_proStaticMethods, MemberListType_proTypes, MemberListType_pubAttribs, MemberListType_pubMethods, MemberListType_pubSlots, MemberListType_pubStaticAttribs, MemberListType_pubStaticMethods, MemberListType_pubTypes, MemberListType_related, MemberListType_services, and MemberListType_signals.
createMembers() [2/2]
TemplateVariant ClassContext::Private::createMembers () const [inline], [private]
Definition at line 2283 of file context.cpp.
    {
      MemberList list(MemberListType_allMembersList,MemberListContainer::Class);
      addMembers(list,m_classDef,MemberListType_pubTypes);
      addMembers(list,m_classDef,MemberListType_services);
      addMembers(list,m_classDef,MemberListType_interfaces);
      addMembers(list,m_classDef,MemberListType_pubSlots);
      addMembers(list,m_classDef,MemberListType_signals);
      addMembers(list,m_classDef,MemberListType_pubMethods);
      addMembers(list,m_classDef,MemberListType_pubStaticMethods);
      addMembers(list,m_classDef,MemberListType_pubAttribs);
      addMembers(list,m_classDef,MemberListType_pubStaticAttribs);
      addMembers(list,m_classDef,MemberListType_proTypes);
      addMembers(list,m_classDef,MemberListType_proSlots);
      addMembers(list,m_classDef,MemberListType_proMethods);
      addMembers(list,m_classDef,MemberListType_proStaticMethods);
      addMembers(list,m_classDef,MemberListType_proAttribs);
      addMembers(list,m_classDef,MemberListType_proStaticAttribs);
      addMembers(list,m_classDef,MemberListType_pacTypes);
      addMembers(list,m_classDef,MemberListType_pacMethods);
      addMembers(list,m_classDef,MemberListType_pacStaticMethods);
      addMembers(list,m_classDef,MemberListType_pacAttribs);
      addMembers(list,m_classDef,MemberListType_pacStaticAttribs);
      addMembers(list,m_classDef,MemberListType_properties);
      addMembers(list,m_classDef,MemberListType_events);
      addMembers(list,m_classDef,MemberListType_priTypes);
      addMembers(list,m_classDef,MemberListType_priSlots);
      addMembers(list,m_classDef,MemberListType_priMethods);
      addMembers(list,m_classDef,MemberListType_priStaticMethods);
      addMembers(list,m_classDef,MemberListType_priAttribs);
      addMembers(list,m_classDef,MemberListType_priStaticAttribs);
      addMembers(list,m_classDef,MemberListType_related);
      return MemberListContext::alloc(list);
    }
References MemberListContext::alloc(), Class, MemberListType_allMembersList, MemberListType_events, MemberListType_interfaces, MemberListType_pacAttribs, MemberListType_pacMethods, MemberListType_pacStaticAttribs, MemberListType_pacStaticMethods, MemberListType_pacTypes, MemberListType_priAttribs, MemberListType_priMethods, MemberListType_priSlots, MemberListType_priStaticAttribs, MemberListType_priStaticMethods, MemberListType_priTypes, MemberListType_proAttribs, MemberListType_proMethods, MemberListType_properties, MemberListType_proSlots, MemberListType_proStaticAttribs, MemberListType_proStaticMethods, MemberListType_proTypes, MemberListType_pubAttribs, MemberListType_pubMethods, MemberListType_pubSlots, MemberListType_pubStaticAttribs, MemberListType_pubStaticMethods, MemberListType_pubTypes, MemberListType_related, MemberListType_services, and MemberListType_signals.
createNumInheritanceNodes() [1/2]
int ClassContext::Private::createNumInheritanceNodes () const [inline], [private]
Definition at line 2327 of file context.cpp.
    {
      return m_classDef->countInheritanceNodes();
    }
References ClassDef::countInheritanceNodes(), and m_classDef.
createNumInheritanceNodes() [2/2]
int ClassContext::Private::createNumInheritanceNodes () const [inline], [private]
Definition at line 2327 of file context.cpp.
    {
      return m_classDef->countInheritanceNodes();
    }
createPackageAttributes() [1/2]
TemplateVariant ClassContext::Private::createPackageAttributes () const [inline], [private]
Definition at line 2103 of file context.cpp.
    {
      return createMemberList(MemberListType_pacAttribs,theTranslator->trPackageAttribs());
    }
References createMemberList(), MemberListType_pacAttribs, theTranslator, and Translator::trPackageAttribs().
createPackageAttributes() [2/2]
TemplateVariant ClassContext::Private::createPackageAttributes () const [inline], [private]
Definition at line 2103 of file context.cpp.
    {
      return createMemberList(MemberListType_pacAttribs,theTranslator->trPackageAttribs());
    }
References MemberListType_pacAttribs, theTranslator, and Translator::trPackageAttribs().
createPackageMethods() [1/2]
TemplateVariant ClassContext::Private::createPackageMethods () const [inline], [private]
Definition at line 2095 of file context.cpp.
    {
      return createMemberList(MemberListType_pacMethods,theTranslator->trPackageFunctions());
    }
References createMemberList(), MemberListType_pacMethods, theTranslator, and Translator::trPackageFunctions().
createPackageMethods() [2/2]
TemplateVariant ClassContext::Private::createPackageMethods () const [inline], [private]
Definition at line 2095 of file context.cpp.
    {
      return createMemberList(MemberListType_pacMethods,theTranslator->trPackageFunctions());
    }
References MemberListType_pacMethods, theTranslator, and Translator::trPackageFunctions().
createPackageStaticAttributes() [1/2]
TemplateVariant ClassContext::Private::createPackageStaticAttributes () const [inline], [private]
Definition at line 2107 of file context.cpp.
    {
      return createMemberList(MemberListType_pacStaticAttribs,theTranslator->trStaticPackageAttribs());
    }
References createMemberList(), MemberListType_pacStaticAttribs, theTranslator, and Translator::trStaticPackageAttribs().
createPackageStaticAttributes() [2/2]
TemplateVariant ClassContext::Private::createPackageStaticAttributes () const [inline], [private]
Definition at line 2107 of file context.cpp.
    {
      return createMemberList(MemberListType_pacStaticAttribs,theTranslator->trStaticPackageAttribs());
    }
References MemberListType_pacStaticAttribs, theTranslator, and Translator::trStaticPackageAttribs().
createPackageStaticMethods() [1/2]
TemplateVariant ClassContext::Private::createPackageStaticMethods () const [inline], [private]
Definition at line 2099 of file context.cpp.
    {
      return createMemberList(MemberListType_pacStaticMethods,theTranslator->trStaticPackageFunctions());
    }
References createMemberList(), MemberListType_pacStaticMethods, theTranslator, and Translator::trStaticPackageFunctions().
createPackageStaticMethods() [2/2]
TemplateVariant ClassContext::Private::createPackageStaticMethods () const [inline], [private]
Definition at line 2099 of file context.cpp.
    {
      return createMemberList(MemberListType_pacStaticMethods,theTranslator->trStaticPackageFunctions());
    }
References MemberListType_pacStaticMethods, theTranslator, and Translator::trStaticPackageFunctions().
createPackageTypes() [1/2]
TemplateVariant ClassContext::Private::createPackageTypes () const [inline], [private]
Definition at line 2091 of file context.cpp.
    {
      return createMemberList(MemberListType_pacTypes,theTranslator->trPackageTypes());
    }
References createMemberList(), MemberListType_pacTypes, theTranslator, and Translator::trPackageTypes().
createPackageTypes() [2/2]
TemplateVariant ClassContext::Private::createPackageTypes () const [inline], [private]
Definition at line 2091 of file context.cpp.
    {
      return createMemberList(MemberListType_pacTypes,theTranslator->trPackageTypes());
    }
References MemberListType_pacTypes, theTranslator, and Translator::trPackageTypes().
createPrivateAttributes() [1/2]
TemplateVariant ClassContext::Private::createPrivateAttributes () const [inline], [private]
Definition at line 2083 of file context.cpp.
    {
      return createMemberList(MemberListType_priAttribs,theTranslator->trPrivateAttribs());
    }
References createMemberList(), MemberListType_priAttribs, theTranslator, and Translator::trPrivateAttribs().
createPrivateAttributes() [2/2]
TemplateVariant ClassContext::Private::createPrivateAttributes () const [inline], [private]
Definition at line 2083 of file context.cpp.
    {
      return createMemberList(MemberListType_priAttribs,theTranslator->trPrivateAttribs());
    }
References MemberListType_priAttribs, theTranslator, and Translator::trPrivateAttribs().
createPrivateMethods() [1/2]
TemplateVariant ClassContext::Private::createPrivateMethods () const [inline], [private]
Definition at line 2075 of file context.cpp.
    {
      return createMemberList(MemberListType_priMethods,theTranslator->trPrivateMembers());
    }
References createMemberList(), MemberListType_priMethods, theTranslator, and Translator::trPrivateMembers().
createPrivateMethods() [2/2]
TemplateVariant ClassContext::Private::createPrivateMethods () const [inline], [private]
Definition at line 2075 of file context.cpp.
    {
      return createMemberList(MemberListType_priMethods,theTranslator->trPrivateMembers());
    }
References MemberListType_priMethods, theTranslator, and Translator::trPrivateMembers().
createPrivateSlots() [1/2]
TemplateVariant ClassContext::Private::createPrivateSlots () const [inline], [private]
Definition at line 2071 of file context.cpp.
    {
      return createMemberList(MemberListType_priSlots,theTranslator->trPrivateSlots());
    }
References createMemberList(), MemberListType_priSlots, theTranslator, and Translator::trPrivateSlots().
createPrivateSlots() [2/2]
TemplateVariant ClassContext::Private::createPrivateSlots () const [inline], [private]
Definition at line 2071 of file context.cpp.
    {
      return createMemberList(MemberListType_priSlots,theTranslator->trPrivateSlots());
    }
References MemberListType_priSlots, theTranslator, and Translator::trPrivateSlots().
createPrivateStaticAttributes() [1/2]
TemplateVariant ClassContext::Private::createPrivateStaticAttributes () const [inline], [private]
Definition at line 2087 of file context.cpp.
    {
      return createMemberList(MemberListType_priStaticAttribs,theTranslator->trStaticPrivateAttribs());
    }
References createMemberList(), MemberListType_priStaticAttribs, theTranslator, and Translator::trStaticPrivateAttribs().
createPrivateStaticAttributes() [2/2]
TemplateVariant ClassContext::Private::createPrivateStaticAttributes () const [inline], [private]
Definition at line 2087 of file context.cpp.
    {
      return createMemberList(MemberListType_priStaticAttribs,theTranslator->trStaticPrivateAttribs());
    }
References MemberListType_priStaticAttribs, theTranslator, and Translator::trStaticPrivateAttribs().
createPrivateStaticMethods() [1/2]
TemplateVariant ClassContext::Private::createPrivateStaticMethods () const [inline], [private]
Definition at line 2079 of file context.cpp.
    {
      return createMemberList(MemberListType_priStaticMethods,theTranslator->trStaticPrivateMembers());
    }
References createMemberList(), MemberListType_priStaticMethods, theTranslator, and Translator::trStaticPrivateMembers().
createPrivateStaticMethods() [2/2]
TemplateVariant ClassContext::Private::createPrivateStaticMethods () const [inline], [private]
Definition at line 2079 of file context.cpp.
    {
      return createMemberList(MemberListType_priStaticMethods,theTranslator->trStaticPrivateMembers());
    }
References MemberListType_priStaticMethods, theTranslator, and Translator::trStaticPrivateMembers().
createPrivateTypes() [1/2]
TemplateVariant ClassContext::Private::createPrivateTypes () const [inline], [private]
Definition at line 2067 of file context.cpp.
    {
      return createMemberList(MemberListType_priTypes,theTranslator->trPrivateTypes());
    }
References createMemberList(), MemberListType_priTypes, theTranslator, and Translator::trPrivateTypes().
createPrivateTypes() [2/2]
TemplateVariant ClassContext::Private::createPrivateTypes () const [inline], [private]
Definition at line 2067 of file context.cpp.
    {
      return createMemberList(MemberListType_priTypes,theTranslator->trPrivateTypes());
    }
References MemberListType_priTypes, theTranslator, and Translator::trPrivateTypes().
createProperties() [1/2]
TemplateVariant ClassContext::Private::createProperties () const [inline], [private]
Definition at line 2111 of file context.cpp.
    {
      return createMemberList(MemberListType_properties,theTranslator->trProperties());
    }
References createMemberList(), MemberListType_properties, theTranslator, and Translator::trProperties().
createProperties() [2/2]
TemplateVariant ClassContext::Private::createProperties () const [inline], [private]
Definition at line 2111 of file context.cpp.
    {
      return createMemberList(MemberListType_properties,theTranslator->trProperties());
    }
References MemberListType_properties, theTranslator, and Translator::trProperties().
createProtectedAttributes() [1/2]
TemplateVariant ClassContext::Private::createProtectedAttributes () const [inline], [private]
Definition at line 2055 of file context.cpp.
    {
      return createMemberList(MemberListType_proAttribs,theTranslator->trProtectedAttribs());
    }
References createMemberList(), MemberListType_proAttribs, theTranslator, and Translator::trProtectedAttribs().
createProtectedAttributes() [2/2]
TemplateVariant ClassContext::Private::createProtectedAttributes () const [inline], [private]
Definition at line 2055 of file context.cpp.
    {
      return createMemberList(MemberListType_proAttribs,theTranslator->trProtectedAttribs());
    }
References MemberListType_proAttribs, theTranslator, and Translator::trProtectedAttribs().
createProtectedMethods() [1/2]
TemplateVariant ClassContext::Private::createProtectedMethods () const [inline], [private]
Definition at line 2047 of file context.cpp.
    {
      return createMemberList(MemberListType_proMethods,theTranslator->trProtectedMembers());
    }
References createMemberList(), MemberListType_proMethods, theTranslator, and Translator::trProtectedMembers().
createProtectedMethods() [2/2]
TemplateVariant ClassContext::Private::createProtectedMethods () const [inline], [private]
Definition at line 2047 of file context.cpp.
    {
      return createMemberList(MemberListType_proMethods,theTranslator->trProtectedMembers());
    }
References MemberListType_proMethods, theTranslator, and Translator::trProtectedMembers().
createProtectedSlots() [1/2]
TemplateVariant ClassContext::Private::createProtectedSlots () const [inline], [private]
Definition at line 2063 of file context.cpp.
    {
      return createMemberList(MemberListType_proSlots,theTranslator->trProtectedSlots());
    }
References createMemberList(), MemberListType_proSlots, theTranslator, and Translator::trProtectedSlots().
createProtectedSlots() [2/2]
TemplateVariant ClassContext::Private::createProtectedSlots () const [inline], [private]
Definition at line 2063 of file context.cpp.
    {
      return createMemberList(MemberListType_proSlots,theTranslator->trProtectedSlots());
    }
References MemberListType_proSlots, theTranslator, and Translator::trProtectedSlots().
createProtectedStaticAttributes() [1/2]
TemplateVariant ClassContext::Private::createProtectedStaticAttributes () const [inline], [private]
Definition at line 2059 of file context.cpp.
    {
      return createMemberList(MemberListType_proStaticAttribs,theTranslator->trStaticProtectedAttribs());
    }
References createMemberList(), MemberListType_proStaticAttribs, theTranslator, and Translator::trStaticProtectedAttribs().
createProtectedStaticAttributes() [2/2]
TemplateVariant ClassContext::Private::createProtectedStaticAttributes () const [inline], [private]
Definition at line 2059 of file context.cpp.
    {
      return createMemberList(MemberListType_proStaticAttribs,theTranslator->trStaticProtectedAttribs());
    }
References MemberListType_proStaticAttribs, theTranslator, and Translator::trStaticProtectedAttribs().
createProtectedStaticMethods() [1/2]
TemplateVariant ClassContext::Private::createProtectedStaticMethods () const [inline], [private]
Definition at line 2051 of file context.cpp.
    {
      return createMemberList(MemberListType_proStaticMethods,theTranslator->trStaticProtectedMembers());
    }
References createMemberList(), MemberListType_proStaticMethods, theTranslator, and Translator::trStaticProtectedMembers().
createProtectedStaticMethods() [2/2]
TemplateVariant ClassContext::Private::createProtectedStaticMethods () const [inline], [private]
Definition at line 2051 of file context.cpp.
    {
      return createMemberList(MemberListType_proStaticMethods,theTranslator->trStaticProtectedMembers());
    }
References MemberListType_proStaticMethods, theTranslator, and Translator::trStaticProtectedMembers().
createProtectedTypes() [1/2]
TemplateVariant ClassContext::Private::createProtectedTypes () const [inline], [private]
Definition at line 2043 of file context.cpp.
    {
      return createMemberList(MemberListType_proTypes,theTranslator->trProtectedTypes());
    }
References createMemberList(), MemberListType_proTypes, theTranslator, and Translator::trProtectedTypes().
createProtectedTypes() [2/2]
TemplateVariant ClassContext::Private::createProtectedTypes () const [inline], [private]
Definition at line 2043 of file context.cpp.
    {
      return createMemberList(MemberListType_proTypes,theTranslator->trProtectedTypes());
    }
References MemberListType_proTypes, theTranslator, and Translator::trProtectedTypes().
createPublicAttributes() [1/2]
TemplateVariant ClassContext::Private::createPublicAttributes () const [inline], [private]
Definition at line 2019 of file context.cpp.
    {
      return createMemberList(MemberListType_pubAttribs,theTranslator->trPublicAttribs());
    }
References createMemberList(), MemberListType_pubAttribs, theTranslator, and Translator::trPublicAttribs().
createPublicAttributes() [2/2]
TemplateVariant ClassContext::Private::createPublicAttributes () const [inline], [private]
Definition at line 2019 of file context.cpp.
    {
      return createMemberList(MemberListType_pubAttribs,theTranslator->trPublicAttribs());
    }
References MemberListType_pubAttribs, theTranslator, and Translator::trPublicAttribs().
createPublicMethods() [1/2]
TemplateVariant ClassContext::Private::createPublicMethods () const [inline], [private]
Definition at line 2007 of file context.cpp.
    {
      return createMemberList(MemberListType_pubMethods,
          m_classDef->getLanguage()==SrcLangExt_ObjC ? theTranslator->trInstanceMethods()
                                                     : theTranslator->trPublicMembers());
    }
References createMemberList(), Definition::getLanguage(), m_classDef, MemberListType_pubMethods, SrcLangExt_ObjC, theTranslator, Translator::trInstanceMethods(), and Translator::trPublicMembers().
createPublicMethods() [2/2]
TemplateVariant ClassContext::Private::createPublicMethods () const [inline], [private]
Definition at line 2007 of file context.cpp.
    {
      return createMemberList(MemberListType_pubMethods,
          m_classDef->getLanguage()==SrcLangExt_ObjC ? theTranslator->trInstanceMethods()
                                                     : theTranslator->trPublicMembers());
    }
References MemberListType_pubMethods, SrcLangExt_ObjC, theTranslator, Translator::trInstanceMethods(), and Translator::trPublicMembers().
createPublicSlots() [1/2]
TemplateVariant ClassContext::Private::createPublicSlots () const [inline], [private]
Definition at line 2027 of file context.cpp.
    {
      return createMemberList(MemberListType_pubSlots,theTranslator->trPublicSlots());
    }
References createMemberList(), MemberListType_pubSlots, theTranslator, and Translator::trPublicSlots().
createPublicSlots() [2/2]
TemplateVariant ClassContext::Private::createPublicSlots () const [inline], [private]
Definition at line 2027 of file context.cpp.
    {
      return createMemberList(MemberListType_pubSlots,theTranslator->trPublicSlots());
    }
References MemberListType_pubSlots, theTranslator, and Translator::trPublicSlots().
createPublicStaticAttributes() [1/2]
TemplateVariant ClassContext::Private::createPublicStaticAttributes () const [inline], [private]
Definition at line 2023 of file context.cpp.
    {
      return createMemberList(MemberListType_pubStaticAttribs,theTranslator->trStaticPublicAttribs());
    }
References createMemberList(), MemberListType_pubStaticAttribs, theTranslator, and Translator::trStaticPublicAttribs().
createPublicStaticAttributes() [2/2]
TemplateVariant ClassContext::Private::createPublicStaticAttributes () const [inline], [private]
Definition at line 2023 of file context.cpp.
    {
      return createMemberList(MemberListType_pubStaticAttribs,theTranslator->trStaticPublicAttribs());
    }
References MemberListType_pubStaticAttribs, theTranslator, and Translator::trStaticPublicAttribs().
createPublicStaticMethods() [1/2]
TemplateVariant ClassContext::Private::createPublicStaticMethods () const [inline], [private]
Definition at line 2013 of file context.cpp.
    {
      return createMemberList(MemberListType_pubStaticMethods,
          m_classDef->getLanguage()==SrcLangExt_ObjC ? theTranslator->trClassMethods()
                                                     : theTranslator->trStaticPublicMembers());
    }
References createMemberList(), Definition::getLanguage(), m_classDef, MemberListType_pubStaticMethods, SrcLangExt_ObjC, theTranslator, Translator::trClassMethods(), and Translator::trStaticPublicMembers().
createPublicStaticMethods() [2/2]
TemplateVariant ClassContext::Private::createPublicStaticMethods () const [inline], [private]
Definition at line 2013 of file context.cpp.
    {
      return createMemberList(MemberListType_pubStaticMethods,
          m_classDef->getLanguage()==SrcLangExt_ObjC ? theTranslator->trClassMethods()
                                                     : theTranslator->trStaticPublicMembers());
    }
References MemberListType_pubStaticMethods, SrcLangExt_ObjC, theTranslator, Translator::trClassMethods(), and Translator::trStaticPublicMembers().
createPublicTypes() [1/2]
TemplateVariant ClassContext::Private::createPublicTypes () const [inline], [private]
Definition at line 2003 of file context.cpp.
    {
      return createMemberList(MemberListType_pubTypes,theTranslator->trPublicTypes());
    }
References createMemberList(), MemberListType_pubTypes, theTranslator, and Translator::trPublicTypes().
createPublicTypes() [2/2]
TemplateVariant ClassContext::Private::createPublicTypes () const [inline], [private]
Definition at line 2003 of file context.cpp.
    {
      return createMemberList(MemberListType_pubTypes,theTranslator->trPublicTypes());
    }
References MemberListType_pubTypes, theTranslator, and Translator::trPublicTypes().
createRelated() [1/2]
TemplateVariant ClassContext::Private::createRelated () const [inline], [private]
Definition at line 2123 of file context.cpp.
    {
      return createMemberList(MemberListType_related,theTranslator->trRelatedFunctions());
    }
References createMemberList(), MemberListType_related, theTranslator, and Translator::trRelatedFunctions().
createRelated() [2/2]
TemplateVariant ClassContext::Private::createRelated () const [inline], [private]
Definition at line 2123 of file context.cpp.
    {
      return createMemberList(MemberListType_related,theTranslator->trRelatedFunctions());
    }
References MemberListType_related, theTranslator, and Translator::trRelatedFunctions().
createSignals() [1/2]
TemplateVariant ClassContext::Private::createSignals () const [inline], [private]
Definition at line 2039 of file context.cpp.
    {
      return createMemberList(MemberListType_signals,theTranslator->trSignals());
    }
References createMemberList(), MemberListType_signals, theTranslator, and Translator::trSignals().
createSignals() [2/2]
TemplateVariant ClassContext::Private::createSignals () const [inline], [private]
Definition at line 2039 of file context.cpp.
    {
      return createMemberList(MemberListType_signals,theTranslator->trSignals());
    }
References MemberListType_signals, theTranslator, and Translator::trSignals().
createTemplateDecls() [1/2]
TemplateVariant ClassContext::Private::createTemplateDecls () const [inline], [private]
Definition at line 2224 of file context.cpp.
    {
      TemplateVariantList tl;
      addTemplateDecls(m_classDef,tl);
      return TemplateImmutableList::alloc(tl);
    }
References addTemplateDecls(), TemplateImmutableList::alloc(), and m_classDef.
createTemplateDecls() [2/2]
TemplateVariant ClassContext::Private::createTemplateDecls () const [inline], [private]
Definition at line 2224 of file context.cpp.
    {
      TemplateVariantList tl;
      addTemplateDecls(m_classDef,tl);
      return TemplateImmutableList::alloc(tl);
    }
References TemplateImmutableList::alloc().
createTypeConstraints() [1/2]
TemplateVariant ClassContext::Private::createTypeConstraints () const [inline], [private]
Definition at line 2177 of file context.cpp.
    {
      return !m_classDef->typeConstraints().empty() ?
          TemplateVariant(ArgumentListContext::alloc(m_classDef->typeConstraints(),m_classDef,relPathAsString())) :
          TemplateVariant(false);
    }
References ArgumentListContext::alloc(), ArgumentList::empty(), m_classDef, DefinitionContext< ClassContext::Private >::relPathAsString(), and ClassDef::typeConstraints().
createTypeConstraints() [2/2]
TemplateVariant ClassContext::Private::createTypeConstraints () const [inline], [private]
Definition at line 2177 of file context.cpp.
    {
      return !m_classDef->typeConstraints().empty() ?
          TemplateVariant(ArgumentListContext::alloc(m_classDef->typeConstraints(),m_classDef,relPathAsString())) :
          TemplateVariant(false);
    }
References ArgumentListContext::alloc().
createUnoIDLInterfaces() [1/2]
TemplateVariant ClassContext::Private::createUnoIDLInterfaces () const [inline], [private]
Definition at line 2035 of file context.cpp.
    {
      return createMemberList(MemberListType_interfaces,theTranslator->trInterfaces());
    }
References createMemberList(), MemberListType_interfaces, theTranslator, and Translator::trInterfaces().
createUnoIDLInterfaces() [2/2]
TemplateVariant ClassContext::Private::createUnoIDLInterfaces () const [inline], [private]
Definition at line 2035 of file context.cpp.
    {
      return createMemberList(MemberListType_interfaces,theTranslator->trInterfaces());
    }
References MemberListType_interfaces, theTranslator, and Translator::trInterfaces().
createUnoIDLServices() [1/2]
TemplateVariant ClassContext::Private::createUnoIDLServices () const [inline], [private]
Definition at line 2031 of file context.cpp.
    {
      return createMemberList(MemberListType_services,theTranslator->trServices());
    }
References createMemberList(), MemberListType_services, theTranslator, and Translator::trServices().
createUnoIDLServices() [2/2]
TemplateVariant ClassContext::Private::createUnoIDLServices () const [inline], [private]
Definition at line 2031 of file context.cpp.
    {
      return createMemberList(MemberListType_services,theTranslator->trServices());
    }
References MemberListType_services, theTranslator, and Translator::trServices().
createUsedFiles() [1/2]
TemplateVariant ClassContext::Private::createUsedFiles () const [inline], [private]
Definition at line 2317 of file context.cpp.
    {
      return UsedFilesContext::alloc(m_classDef);
    }
References UsedFilesContext::alloc(), and m_classDef.
createUsedFiles() [2/2]
TemplateVariant ClassContext::Private::createUsedFiles () const [inline], [private]
Definition at line 2317 of file context.cpp.
    {
      return UsedFilesContext::alloc(m_classDef);
    }
References UsedFilesContext::alloc().
detailedConstructors() [1/2]
TemplateVariant ClassContext::Private::detailedConstructors () const [inline], [private]
Definition at line 1773 of file context.cpp.
{ return m_cachable.detailedConstructors.get(this); }
References ClassContext::Private::Cachable::detailedConstructors, and m_cachable.
detailedConstructors() [2/2]
TemplateVariant ClassContext::Private::detailedConstructors () const [inline], [private]
Definition at line 1773 of file context.cpp.
{ return m_cachable.detailedConstructors.get(this); }
detailedEnums() [1/2]
TemplateVariant ClassContext::Private::detailedEnums () const [inline], [private]
Definition at line 1770 of file context.cpp.
{ return m_cachable.detailedEnums.get(this); }
References ClassContext::Private::Cachable::detailedEnums, and m_cachable.
detailedEnums() [2/2]
TemplateVariant ClassContext::Private::detailedEnums () const [inline], [private]
Definition at line 1770 of file context.cpp.
{ return m_cachable.detailedEnums.get(this); }
detailedEvents() [1/2]
TemplateVariant ClassContext::Private::detailedEvents () const [inline], [private]
Definition at line 1778 of file context.cpp.
{ return m_cachable.detailedEvents.get(this); }
References ClassContext::Private::Cachable::detailedEvents, and m_cachable.
detailedEvents() [2/2]
TemplateVariant ClassContext::Private::detailedEvents () const [inline], [private]
Definition at line 1778 of file context.cpp.
{ return m_cachable.detailedEvents.get(this); }
detailedInterfaces() [1/2]
TemplateVariant ClassContext::Private::detailedInterfaces () const [inline], [private]
Definition at line 1772 of file context.cpp.
{ return m_cachable.detailedInterfaces.get(this); }
References ClassContext::Private::Cachable::detailedInterfaces, and m_cachable.
detailedInterfaces() [2/2]
TemplateVariant ClassContext::Private::detailedInterfaces () const [inline], [private]
Definition at line 1772 of file context.cpp.
{ return m_cachable.detailedInterfaces.get(this); }
detailedMethods() [1/2]
TemplateVariant ClassContext::Private::detailedMethods () const [inline], [private]
Definition at line 1774 of file context.cpp.
{ return m_cachable.detailedMethods.get(this); }
References ClassContext::Private::Cachable::detailedMethods, and m_cachable.
detailedMethods() [2/2]
TemplateVariant ClassContext::Private::detailedMethods () const [inline], [private]
Definition at line 1774 of file context.cpp.
{ return m_cachable.detailedMethods.get(this); }
detailedProperties() [1/2]
TemplateVariant ClassContext::Private::detailedProperties () const [inline], [private]
Definition at line 1777 of file context.cpp.
{ return m_cachable.detailedProperties.get(this); }
References ClassContext::Private::Cachable::detailedProperties, and m_cachable.
detailedProperties() [2/2]
TemplateVariant ClassContext::Private::detailedProperties () const [inline], [private]
Definition at line 1777 of file context.cpp.
{ return m_cachable.detailedProperties.get(this); }
detailedRelated() [1/2]
TemplateVariant ClassContext::Private::detailedRelated () const [inline], [private]
Definition at line 1775 of file context.cpp.
{ return m_cachable.detailedRelated.get(this); }
References ClassContext::Private::Cachable::detailedRelated, and m_cachable.
detailedRelated() [2/2]
TemplateVariant ClassContext::Private::detailedRelated () const [inline], [private]
Definition at line 1775 of file context.cpp.
{ return m_cachable.detailedRelated.get(this); }
detailedServices() [1/2]
TemplateVariant ClassContext::Private::detailedServices () const [inline], [private]
Definition at line 1771 of file context.cpp.
{ return m_cachable.detailedServices.get(this); }
References ClassContext::Private::Cachable::detailedServices, and m_cachable.
detailedServices() [2/2]
TemplateVariant ClassContext::Private::detailedServices () const [inline], [private]
Definition at line 1771 of file context.cpp.
{ return m_cachable.detailedServices.get(this); }
detailedTypedefs() [1/2]
TemplateVariant ClassContext::Private::detailedTypedefs () const [inline], [private]
Definition at line 1769 of file context.cpp.
{ return m_cachable.detailedTypedefs.get(this); }
References ClassContext::Private::Cachable::detailedTypedefs, and m_cachable.
detailedTypedefs() [2/2]
TemplateVariant ClassContext::Private::detailedTypedefs () const [inline], [private]
Definition at line 1769 of file context.cpp.
{ return m_cachable.detailedTypedefs.get(this); }
detailedVariables() [1/2]
TemplateVariant ClassContext::Private::detailedVariables () const [inline], [private]
Definition at line 1776 of file context.cpp.
{ return m_cachable.detailedVariables.get(this); }
References ClassContext::Private::Cachable::detailedVariables, and m_cachable.
detailedVariables() [2/2]
TemplateVariant ClassContext::Private::detailedVariables () const [inline], [private]
Definition at line 1776 of file context.cpp.
{ return m_cachable.detailedVariables.get(this); }
events() [1/2]
TemplateVariant ClassContext::Private::events () const [inline], [private]
Definition at line 1766 of file context.cpp.
{ return m_cachable.events.get(this); }
References ClassContext::Private::Cachable::events, and m_cachable.
events() [2/2]
TemplateVariant ClassContext::Private::events () const [inline], [private]
Definition at line 1766 of file context.cpp.
{ return m_cachable.events.get(this); }
examples() [1/2]
TemplateVariant ClassContext::Private::examples () const [inline], [private]
Definition at line 1784 of file context.cpp.
{ return m_cachable.examples.get(this); }
References ClassContext::Private::Cachable::examples, and m_cachable.
examples() [2/2]
TemplateVariant ClassContext::Private::examples () const [inline], [private]
Definition at line 1784 of file context.cpp.
{ return m_cachable.examples.get(this); }
fields() [1/2]
StringVector ClassContext::Private::fields () const [inline]
Definition at line 1724 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
fields() [2/2]
StringVector ClassContext::Private::fields () const [inline]
Definition at line 1724 of file context.cpp.
{ return s_inst.fields(); }
friends() [1/2]
TemplateVariant ClassContext::Private::friends () const [inline], [private]
Definition at line 1767 of file context.cpp.
{ return m_cachable.friends.get(this); }
References ClassContext::Private::Cachable::friends, and m_cachable.
friends() [2/2]
TemplateVariant ClassContext::Private::friends () const [inline], [private]
Definition at line 1767 of file context.cpp.
{ return m_cachable.friends.get(this); }
generatedFromFiles() [1/2]
TemplateVariant ClassContext::Private::generatedFromFiles () const [inline], [private]
Definition at line 1732 of file context.cpp.
{ return m_classDef->generatedFromFiles(); }
References ClassDef::generatedFromFiles(), and m_classDef.
generatedFromFiles() [2/2]
TemplateVariant ClassContext::Private::generatedFromFiles () const [inline], [private]
Definition at line 1732 of file context.cpp.
{ return m_classDef->generatedFromFiles(); }
get() [1/2]
TemplateVariant ClassContext::Private::get (const QCString & n) const [inline]
Definition at line 1723 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), n, and s_inst.
get() [2/2]
TemplateVariant ClassContext::Private::get (const QCString & n) const [inline]
Definition at line 1723 of file context.cpp.
{ return s_inst.get(this,n); }
References n.
getClassGraph() [1/2]
DotClassGraphPtr ClassContext::Private::getClassGraph () const [inline], [private]
Definition at line 1734 of file context.cpp.
{ return m_cachable.classGraph.get(this); }
References ClassContext::Private::Cachable::classGraph, and m_cachable.
Referenced by hasInheritanceDiagram(), and inheritanceDiagram().
getClassGraph() [2/2]
DotClassGraphPtr ClassContext::Private::getClassGraph () const [inline], [private]
Definition at line 1734 of file context.cpp.
{ return m_cachable.classGraph.get(this); }
getCollaborationGraph() [1/2]
DotClassGraphPtr ClassContext::Private::getCollaborationGraph () const [inline], [private]
Definition at line 1896 of file context.cpp.
    {
      return m_cachable.collaborationGraph.get(this);
    }
References ClassContext::Private::Cachable::collaborationGraph, and m_cachable.
Referenced by collaborationDiagram(), and hasCollaborationDiagram().
getCollaborationGraph() [2/2]
DotClassGraphPtr ClassContext::Private::getCollaborationGraph () const [inline], [private]
Definition at line 1896 of file context.cpp.
    {
      return m_cachable.collaborationGraph.get(this);
    }
hasCollaborationDiagram() [1/2]
TemplateVariant ClassContext::Private::hasCollaborationDiagram () const [inline], [private]
Definition at line 1900 of file context.cpp.
    {
      bool haveDot = Config_getBool(HAVE_DOT);
      return haveDot && !getCollaborationGraph()->isTrivial();
    }
References Config_getBool, and getCollaborationGraph().
hasCollaborationDiagram() [2/2]
TemplateVariant ClassContext::Private::hasCollaborationDiagram () const [inline], [private]
Definition at line 1900 of file context.cpp.
    {
      bool haveDot = Config_getBool(HAVE_DOT);
      return haveDot && !getCollaborationGraph()->isTrivial();
    }
References Config_getBool.
hasDetails() [1/2]
TemplateVariant ClassContext::Private::hasDetails () const [inline], [private]
Definition at line 1731 of file context.cpp.
{ return m_classDef->hasDetailedDescription(); }
References ClassDef::hasDetailedDescription(), and m_classDef.
hasDetails() [2/2]
TemplateVariant ClassContext::Private::hasDetails () const [inline], [private]
Definition at line 1731 of file context.cpp.
{ return m_classDef->hasDetailedDescription(); }
hasInheritanceDiagram() [1/2]
TemplateVariant ClassContext::Private::hasInheritanceDiagram () const [inline], [private]
Definition at line 1793 of file context.cpp.
    {
      bool result=FALSE;
      bool haveDot = Config_getBool(HAVE_DOT);
      auto classGraph = Config_getEnum(CLASS_GRAPH);
      bool classGraphEnabled = classGraph==CLASS_GRAPH_t::YES || classGraph==CLASS_GRAPH_t::GRAPH;
      if (haveDot && classGraphEnabled)
      {
        DotClassGraphPtr cg = getClassGraph();
        result = !cg->isTrivial() && !cg->isTooBig();
      }
      else if (classGraphEnabled)
      {
        result = numInheritanceNodes()>0;
      }
      return result;
    }
References Config_getBool, Config_getEnum, FALSE, getClassGraph(), and numInheritanceNodes().
hasInheritanceDiagram() [2/2]
TemplateVariant ClassContext::Private::hasInheritanceDiagram () const [inline], [private]
Definition at line 1793 of file context.cpp.
    {
      bool result=FALSE;
      bool haveDot = Config_getBool(HAVE_DOT);
      auto classGraph = Config_getEnum(CLASS_GRAPH);
      bool classGraphEnabled = classGraph==CLASS_GRAPH_t::YES || classGraph==CLASS_GRAPH_t::GRAPH;
      if (haveDot && classGraphEnabled)
      {
        DotClassGraphPtr cg = getClassGraph();
        result = !cg->isTrivial() && !cg->isTooBig();
      }
      else if (classGraphEnabled)
      {
        result = numInheritanceNodes()>0;
      }
      return result;
    }
References Config_getBool, Config_getEnum, and FALSE.
highlight() [1/2]
TemplateVariant ClassContext::Private::highlight () const [inline], [private]
Definition at line 1729 of file context.cpp.
{ return TemplateVariant("classes"); }
Referenced by doxmlparser.compound.codelineType::__init__(), doxmlparser.compound.codelineType::add_highlight(), doxmlparser.compound.codelineType::buildChildren(), doxmlparser.compound.codelineType::exportChildren(), doxmlparser.compound.codelineType::get_highlight(), doxmlparser.compound.codelineType::hasContent_(), doxmlparser.compound.codelineType::insert_highlight_at(), doxmlparser.compound.codelineType::replace_highlight_at(), and doxmlparser.compound.codelineType::set_highlight().
highlight() [2/2]
TemplateVariant ClassContext::Private::highlight () const [inline], [private]
Definition at line 1729 of file context.cpp.
{ return TemplateVariant("classes"); }
Referenced by doxmlparser.compound.codelineType::__init__(), doxmlparser.compound.codelineType::add_highlight(), doxmlparser.compound.codelineType::buildChildren(), doxmlparser.compound.codelineType::exportChildren(), doxmlparser.compound.codelineType::get_highlight(), doxmlparser.compound.codelineType::hasContent_(), doxmlparser.compound.codelineType::insert_highlight_at(), doxmlparser.compound.codelineType::replace_highlight_at(), and doxmlparser.compound.codelineType::set_highlight().
includeInfo() [1/2]
TemplateVariant ClassContext::Private::includeInfo () const [inline], [private]
Definition at line 1736 of file context.cpp.
{ return m_cachable.includeInfo.get(this); }
References ClassContext::Private::Cachable::includeInfo, and m_cachable.
includeInfo() [2/2]
TemplateVariant ClassContext::Private::includeInfo () const [inline], [private]
Definition at line 1736 of file context.cpp.
{ return m_cachable.includeInfo.get(this); }
inheritanceDiagram() [1/2]
TemplateVariant ClassContext::Private::inheritanceDiagram () const [inline], [private]
Definition at line 1811 of file context.cpp.
    {
      TextStream t;
      bool haveDot = Config_getBool(HAVE_DOT);
      auto classGraph = Config_getEnum(CLASS_GRAPH);
      bool classGraphEnabled = classGraph==CLASS_GRAPH_t::YES || classGraph==CLASS_GRAPH_t::GRAPH;
      if (haveDot && classGraphEnabled)
      {
        DotClassGraphPtr cg = getClassGraph();
        switch (g_globals.outputFormat)
        {
          case ContextOutputFormat_Html:
            {
              cg->writeGraph(t,GOF_BITMAP,EOF_Html,
                             g_globals.outputDir,
                             g_globals.outputDir+Portable::pathSeparator()+addHtmlExtensionIfMissing(m_classDef->getOutputFileBase()),
                             relPathAsString(),TRUE,TRUE,g_globals.dynSectionId
                            );
            }
            break;
          case ContextOutputFormat_Latex:
            {
              cg->writeGraph(t,GOF_EPS,EOF_LaTeX,
                             g_globals.outputDir,
                             g_globals.outputDir+Portable::pathSeparator()+m_classDef->getOutputFileBase()+".tex",
                             relPathAsString(),TRUE,TRUE,g_globals.dynSectionId
                            );
            }
            break;
            // TODO: support other generators
          default:
            err("context.cpp: output format not yet supported\n");
            break;
        }
        g_globals.dynSectionId++;
      }
      else if (classGraphEnabled)
      {
        ClassDiagram d(m_classDef);
        switch (g_globals.outputFormat)
        {
          case ContextOutputFormat_Html:
            {
              TextStream tt;
              QCString name = convertToHtml(m_classDef->displayName());
              d.writeImage(tt,g_globals.outputDir,
                           relPathAsString(),
                           m_classDef->getOutputFileBase());
              if (!tt.empty())
              {
                t << "<div class=\"center\">\n";
                t << " <img src=\"";
                t << relPathAsString() << m_classDef->getOutputFileBase();
                t << ".png\" usemap=\"#" << convertToId(name) << "_map\" alt=\"\"/>\n";
                t << " <map id=\"" << convertToId(name) << "_map\" name=\"" << convertToId(name) << "_map\">\n";
            t << tt.str();
            t << " </map>\n";
                t << "</div>";
              }
              else
              {
                t << "<div class=\"center\">\n";
                t << " <img src=\"";
                t << relPathAsString() << m_classDef->getOutputFileBase();
                t << ".png\" alt=\"\"/>\n";
                t << "</div>";
              }
            }
            break;
          case ContextOutputFormat_Latex:
            {
              d.writeFigure(t,g_globals.outputDir,m_classDef->getOutputFileBase());
            }
            break;
            // TODO: support other generators
          default:
            err("context.cpp: output format not yet supported\n");
            break;
        }
        g_globals.dynSectionId++;
      }
      return TemplateVariant(t.str().c_str(),TRUE);
    }
References addHtmlExtensionIfMissing(), Config_getBool, Config_getEnum, ContextOutputFormat_Html, ContextOutputFormat_Latex, convertToHtml(), convertToId(), ClassDef::displayName(), ContextGlobals::dynSectionId, TextStream::empty(), EOF_Html, EOF_LaTeX, err(), g_globals, getClassGraph(), ClassDef::getOutputFileBase(), GOF_BITMAP, GOF_EPS, m_classDef, DefinitionContext< ClassContext::Private >::name(), ContextGlobals::outputDir, ContextGlobals::outputFormat, Portable::pathSeparator(), DefinitionContext< ClassContext::Private >::relPathAsString(), TextStream::str(), TRUE, ClassDiagram::writeFigure(), and ClassDiagram::writeImage().
inheritanceDiagram() [2/2]
TemplateVariant ClassContext::Private::inheritanceDiagram () const [inline], [private]
Definition at line 1811 of file context.cpp.
    {
      TextStream t;
      bool haveDot = Config_getBool(HAVE_DOT);
      auto classGraph = Config_getEnum(CLASS_GRAPH);
      bool classGraphEnabled = classGraph==CLASS_GRAPH_t::YES || classGraph==CLASS_GRAPH_t::GRAPH;
      if (haveDot && classGraphEnabled)
      {
        DotClassGraphPtr cg = getClassGraph();
        switch (g_globals.outputFormat)
        {
          case ContextOutputFormat_Html:
            {
              cg->writeGraph(t,GOF_BITMAP,EOF_Html,
                             g_globals.outputDir,
                             g_globals.outputDir+Portable::pathSeparator()+addHtmlExtensionIfMissing(m_classDef->getOutputFileBase()),
                             relPathAsString(),TRUE,TRUE,g_globals.dynSectionId
                            );
            }
            break;
          case ContextOutputFormat_Latex:
            {
              cg->writeGraph(t,GOF_EPS,EOF_LaTeX,
                             g_globals.outputDir,
                             g_globals.outputDir+Portable::pathSeparator()+m_classDef->getOutputFileBase()+".tex",
                             relPathAsString(),TRUE,TRUE,g_globals.dynSectionId
                            );
            }
            break;
            // TODO: support other generators
          default:
            err("context.cpp: output format not yet supported\n");
            break;
        }
        g_globals.dynSectionId++;
      }
      else if (classGraphEnabled)
      {
        ClassDiagram d(m_classDef);
        switch (g_globals.outputFormat)
        {
          case ContextOutputFormat_Html:
            {
              TextStream tt;
              QCString name = convertToHtml(m_classDef->displayName());
              d.writeImage(tt,g_globals.outputDir,
                           relPathAsString(),
                           m_classDef->getOutputFileBase());
              if (!tt.empty())
              {
                t << "<div class=\"center\">\n";
                t << " <img src=\"";
                t << relPathAsString() << m_classDef->getOutputFileBase();
                t << ".png\" usemap=\"#" << convertToId(name) << "_map\" alt=\"\"/>\n";
                t << " <map id=\"" << convertToId(name) << "_map\" name=\"" << convertToId(name) << "_map\">\n";
            t << tt.str();
            t << " </map>\n";
                t << "</div>";
              }
              else
              {
                t << "<div class=\"center\">\n";
                t << " <img src=\"";
                t << relPathAsString() << m_classDef->getOutputFileBase();
                t << ".png\" alt=\"\"/>\n";
                t << "</div>";
              }
            }
            break;
          case ContextOutputFormat_Latex:
            {
              d.writeFigure(t,g_globals.outputDir,m_classDef->getOutputFileBase());
            }
            break;
            // TODO: support other generators
          default:
            err("context.cpp: output format not yet supported\n");
            break;
        }
        g_globals.dynSectionId++;
      }
      return TemplateVariant(t.str().c_str(),TRUE);
    }
References addHtmlExtensionIfMissing(), Config_getBool, Config_getEnum, ContextOutputFormat_Html, ContextOutputFormat_Latex, convertToHtml(), convertToId(), ContextGlobals::dynSectionId, TextStream::empty(), EOF_Html, EOF_LaTeX, err(), g_globals, GOF_BITMAP, GOF_EPS, setup::name, ContextGlobals::outputDir, ContextGlobals::outputFormat, Portable::pathSeparator(), TextStream::str(), TRUE, ClassDiagram::writeFigure(), and ClassDiagram::writeImage().
inheritedBy() [1/2]
TemplateVariant ClassContext::Private::inheritedBy () const [inline], [private]
Definition at line 1738 of file context.cpp.
{ return m_cachable.inheritedByList.get(this); }
References ClassContext::Private::Cachable::inheritedByList, and m_cachable.
inheritedBy() [2/2]
TemplateVariant ClassContext::Private::inheritedBy () const [inline], [private]
Definition at line 1738 of file context.cpp.
{ return m_cachable.inheritedByList.get(this); }
inherits() [1/2]
TemplateVariant ClassContext::Private::inherits () const [inline], [private]
Definition at line 1737 of file context.cpp.
{ return m_cachable.inheritsList.get(this); }
References ClassContext::Private::Cachable::inheritsList, and m_cachable.
inherits() [2/2]
TemplateVariant ClassContext::Private::inherits () const [inline], [private]
Definition at line 1737 of file context.cpp.
{ return m_cachable.inheritsList.get(this); }
innerClasses() [1/2]
TemplateVariant ClassContext::Private::innerClasses () const [inline], [private]
Definition at line 1780 of file context.cpp.
{ return m_cachable.innerClasses.get(this); }
References ClassContext::Private::Cachable::innerClasses, and m_cachable.
innerClasses() [2/2]
TemplateVariant ClassContext::Private::innerClasses () const [inline], [private]
Definition at line 1780 of file context.cpp.
{ return m_cachable.innerClasses.get(this); }
isSimple() [1/2]
TemplateVariant ClassContext::Private::isSimple () const [inline], [private]
Definition at line 1790 of file context.cpp.
{ return m_classDef->isSimple(); }
References ClassDef::isSimple(), and m_classDef.
isSimple() [2/2]
TemplateVariant ClassContext::Private::isSimple () const [inline], [private]
Definition at line 1790 of file context.cpp.
{ return m_classDef->isSimple(); }
memberGroups() [1/2]
TemplateVariant ClassContext::Private::memberGroups () const [inline], [private]
Definition at line 1788 of file context.cpp.
{ return m_cachable.memberGroups.get(this); }
References m_cachable, and ClassContext::Private::Cachable::memberGroups.
memberGroups() [2/2]
TemplateVariant ClassContext::Private::memberGroups () const [inline], [private]
Definition at line 1788 of file context.cpp.
{ return m_cachable.memberGroups.get(this); }
members() [1/2]
TemplateVariant ClassContext::Private::members () const [inline], [private]
Definition at line 1785 of file context.cpp.
{ return m_cachable.members.get(this); }
References m_cachable, and ClassContext::Private::Cachable::members.
members() [2/2]
TemplateVariant ClassContext::Private::members () const [inline], [private]
Definition at line 1785 of file context.cpp.
{ return m_cachable.members.get(this); }
numInheritanceNodes() [1/2]
int ClassContext::Private::numInheritanceNodes () const [inline], [private]
Definition at line 1735 of file context.cpp.
{ return m_cachable.numInheritanceNodes.get(this); }
References m_cachable, and ClassContext::Private::Cachable::numInheritanceNodes.
Referenced by hasInheritanceDiagram().
numInheritanceNodes() [2/2]
int ClassContext::Private::numInheritanceNodes () const [inline], [private]
Definition at line 1735 of file context.cpp.
{ return m_cachable.numInheritanceNodes.get(this); }
packageAttributes() [1/2]
TemplateVariant ClassContext::Private::packageAttributes () const [inline], [private]
Definition at line 1763 of file context.cpp.
{ return m_cachable.packageAttributes.get(this); }
References m_cachable, and ClassContext::Private::Cachable::packageAttributes.
packageAttributes() [2/2]
TemplateVariant ClassContext::Private::packageAttributes () const [inline], [private]
Definition at line 1763 of file context.cpp.
{ return m_cachable.packageAttributes.get(this); }
packageMethods() [1/2]
TemplateVariant ClassContext::Private::packageMethods () const [inline], [private]
Definition at line 1761 of file context.cpp.
{ return m_cachable.packageMethods.get(this); }
References m_cachable, and ClassContext::Private::Cachable::packageMethods.
packageMethods() [2/2]
TemplateVariant ClassContext::Private::packageMethods () const [inline], [private]
Definition at line 1761 of file context.cpp.
{ return m_cachable.packageMethods.get(this); }
packageStaticAttributes() [1/2]
TemplateVariant ClassContext::Private::packageStaticAttributes () const [inline], [private]
Definition at line 1764 of file context.cpp.
{ return m_cachable.packageStaticAttributes.get(this); }
References m_cachable, and ClassContext::Private::Cachable::packageStaticAttributes.
packageStaticAttributes() [2/2]
TemplateVariant ClassContext::Private::packageStaticAttributes () const [inline], [private]
Definition at line 1764 of file context.cpp.
{ return m_cachable.packageStaticAttributes.get(this); }
packageStaticMethods() [1/2]
TemplateVariant ClassContext::Private::packageStaticMethods () const [inline], [private]
Definition at line 1762 of file context.cpp.
{ return m_cachable.packageStaticMethods.get(this); }
References m_cachable, and ClassContext::Private::Cachable::packageStaticMethods.
packageStaticMethods() [2/2]
TemplateVariant ClassContext::Private::packageStaticMethods () const [inline], [private]
Definition at line 1762 of file context.cpp.
{ return m_cachable.packageStaticMethods.get(this); }
packageTypes() [1/2]
TemplateVariant ClassContext::Private::packageTypes () const [inline], [private]
Definition at line 1760 of file context.cpp.
{ return m_cachable.packageTypes.get(this); }
References m_cachable, and ClassContext::Private::Cachable::packageTypes.
packageTypes() [2/2]
TemplateVariant ClassContext::Private::packageTypes () const [inline], [private]
Definition at line 1760 of file context.cpp.
{ return m_cachable.packageTypes.get(this); }
privateAttributes() [1/2]
TemplateVariant ClassContext::Private::privateAttributes () const [inline], [private]
Definition at line 1758 of file context.cpp.
{ return m_cachable.privateAttributes.get(this); }
References m_cachable, and ClassContext::Private::Cachable::privateAttributes.
privateAttributes() [2/2]
TemplateVariant ClassContext::Private::privateAttributes () const [inline], [private]
Definition at line 1758 of file context.cpp.
{ return m_cachable.privateAttributes.get(this); }
privateMethods() [1/2]
TemplateVariant ClassContext::Private::privateMethods () const [inline], [private]
Definition at line 1756 of file context.cpp.
{ return m_cachable.privateMethods.get(this); }
References m_cachable, and ClassContext::Private::Cachable::privateMethods.
privateMethods() [2/2]
TemplateVariant ClassContext::Private::privateMethods () const [inline], [private]
Definition at line 1756 of file context.cpp.
{ return m_cachable.privateMethods.get(this); }
privateSlots() [1/2]
TemplateVariant ClassContext::Private::privateSlots () const [inline], [private]
Definition at line 1755 of file context.cpp.
{ return m_cachable.privateSlots.get(this); }
References m_cachable, and ClassContext::Private::Cachable::privateSlots.
privateSlots() [2/2]
TemplateVariant ClassContext::Private::privateSlots () const [inline], [private]
Definition at line 1755 of file context.cpp.
{ return m_cachable.privateSlots.get(this); }
privateStaticAttributes() [1/2]
TemplateVariant ClassContext::Private::privateStaticAttributes () const [inline], [private]
Definition at line 1759 of file context.cpp.
{ return m_cachable.privateStaticAttributes.get(this); }
References m_cachable, and ClassContext::Private::Cachable::privateStaticAttributes.
privateStaticAttributes() [2/2]
TemplateVariant ClassContext::Private::privateStaticAttributes () const [inline], [private]
Definition at line 1759 of file context.cpp.
{ return m_cachable.privateStaticAttributes.get(this); }
privateStaticMethods() [1/2]
TemplateVariant ClassContext::Private::privateStaticMethods () const [inline], [private]
Definition at line 1757 of file context.cpp.
{ return m_cachable.privateStaticMethods.get(this); }
References m_cachable, and ClassContext::Private::Cachable::privateStaticMethods.
privateStaticMethods() [2/2]
TemplateVariant ClassContext::Private::privateStaticMethods () const [inline], [private]
Definition at line 1757 of file context.cpp.
{ return m_cachable.privateStaticMethods.get(this); }
privateTypes() [1/2]
TemplateVariant ClassContext::Private::privateTypes () const [inline], [private]
Definition at line 1754 of file context.cpp.
{ return m_cachable.privateTypes.get(this); }
References m_cachable, and ClassContext::Private::Cachable::privateTypes.
privateTypes() [2/2]
TemplateVariant ClassContext::Private::privateTypes () const [inline], [private]
Definition at line 1754 of file context.cpp.
{ return m_cachable.privateTypes.get(this); }
properties() [1/2]
TemplateVariant ClassContext::Private::properties () const [inline], [private]
Definition at line 1765 of file context.cpp.
{ return m_cachable.properties.get(this); }
References m_cachable, and ClassContext::Private::Cachable::properties.
properties() [2/2]
TemplateVariant ClassContext::Private::properties () const [inline], [private]
Definition at line 1765 of file context.cpp.
{ return m_cachable.properties.get(this); }
protectedAttributes() [1/2]
TemplateVariant ClassContext::Private::protectedAttributes () const [inline], [private]
Definition at line 1751 of file context.cpp.
{ return m_cachable.protectedAttributes.get(this); }
References m_cachable, and ClassContext::Private::Cachable::protectedAttributes.
protectedAttributes() [2/2]
TemplateVariant ClassContext::Private::protectedAttributes () const [inline], [private]
Definition at line 1751 of file context.cpp.
{ return m_cachable.protectedAttributes.get(this); }
protectedMethods() [1/2]
TemplateVariant ClassContext::Private::protectedMethods () const [inline], [private]
Definition at line 1749 of file context.cpp.
{ return m_cachable.protectedMethods.get(this); }
References m_cachable, and ClassContext::Private::Cachable::protectedMethods.
protectedMethods() [2/2]
TemplateVariant ClassContext::Private::protectedMethods () const [inline], [private]
Definition at line 1749 of file context.cpp.
{ return m_cachable.protectedMethods.get(this); }
protectedSlots() [1/2]
TemplateVariant ClassContext::Private::protectedSlots () const [inline], [private]
Definition at line 1753 of file context.cpp.
{ return m_cachable.protectedSlots.get(this); }
References m_cachable, and ClassContext::Private::Cachable::protectedSlots.
protectedSlots() [2/2]
TemplateVariant ClassContext::Private::protectedSlots () const [inline], [private]
Definition at line 1753 of file context.cpp.
{ return m_cachable.protectedSlots.get(this); }
protectedStaticAttributes() [1/2]
TemplateVariant ClassContext::Private::protectedStaticAttributes () const [inline], [private]
Definition at line 1752 of file context.cpp.
{ return m_cachable.protectedStaticAttributes.get(this); }
References m_cachable, and ClassContext::Private::Cachable::protectedStaticAttributes.
protectedStaticAttributes() [2/2]
TemplateVariant ClassContext::Private::protectedStaticAttributes () const [inline], [private]
Definition at line 1752 of file context.cpp.
{ return m_cachable.protectedStaticAttributes.get(this); }
protectedStaticMethods() [1/2]
TemplateVariant ClassContext::Private::protectedStaticMethods () const [inline], [private]
Definition at line 1750 of file context.cpp.
{ return m_cachable.protectedStaticMethods.get(this); }
References m_cachable, and ClassContext::Private::Cachable::protectedStaticMethods.
protectedStaticMethods() [2/2]
TemplateVariant ClassContext::Private::protectedStaticMethods () const [inline], [private]
Definition at line 1750 of file context.cpp.
{ return m_cachable.protectedStaticMethods.get(this); }
protectedTypes() [1/2]
TemplateVariant ClassContext::Private::protectedTypes () const [inline], [private]
Definition at line 1748 of file context.cpp.
{ return m_cachable.protectedTypes.get(this); }
References m_cachable, and ClassContext::Private::Cachable::protectedTypes.
protectedTypes() [2/2]
TemplateVariant ClassContext::Private::protectedTypes () const [inline], [private]
Definition at line 1748 of file context.cpp.
{ return m_cachable.protectedTypes.get(this); }
publicAttributes() [1/2]
TemplateVariant ClassContext::Private::publicAttributes () const [inline], [private]
Definition at line 1745 of file context.cpp.
{ return m_cachable.publicAttributes.get(this); }
References m_cachable, and ClassContext::Private::Cachable::publicAttributes.
publicAttributes() [2/2]
TemplateVariant ClassContext::Private::publicAttributes () const [inline], [private]
Definition at line 1745 of file context.cpp.
{ return m_cachable.publicAttributes.get(this); }
publicMethods() [1/2]
TemplateVariant ClassContext::Private::publicMethods () const [inline], [private]
Definition at line 1743 of file context.cpp.
{ return m_cachable.publicMethods.get(this); }
References m_cachable, and ClassContext::Private::Cachable::publicMethods.
publicMethods() [2/2]
TemplateVariant ClassContext::Private::publicMethods () const [inline], [private]
Definition at line 1743 of file context.cpp.
{ return m_cachable.publicMethods.get(this); }
publicSlots() [1/2]
TemplateVariant ClassContext::Private::publicSlots () const [inline], [private]
Definition at line 1747 of file context.cpp.
{ return m_cachable.publicSlots.get(this); }
References m_cachable, and ClassContext::Private::Cachable::publicSlots.
publicSlots() [2/2]
TemplateVariant ClassContext::Private::publicSlots () const [inline], [private]
Definition at line 1747 of file context.cpp.
{ return m_cachable.publicSlots.get(this); }
publicStaticAttributes() [1/2]
TemplateVariant ClassContext::Private::publicStaticAttributes () const [inline], [private]
Definition at line 1746 of file context.cpp.
{ return m_cachable.publicStaticAttributes.get(this); }
References m_cachable, and ClassContext::Private::Cachable::publicStaticAttributes.
publicStaticAttributes() [2/2]
TemplateVariant ClassContext::Private::publicStaticAttributes () const [inline], [private]
Definition at line 1746 of file context.cpp.
{ return m_cachable.publicStaticAttributes.get(this); }
publicStaticMethods() [1/2]
TemplateVariant ClassContext::Private::publicStaticMethods () const [inline], [private]
Definition at line 1744 of file context.cpp.
{ return m_cachable.publicStaticMethods.get(this); }
References m_cachable, and ClassContext::Private::Cachable::publicStaticMethods.
publicStaticMethods() [2/2]
TemplateVariant ClassContext::Private::publicStaticMethods () const [inline], [private]
Definition at line 1744 of file context.cpp.
{ return m_cachable.publicStaticMethods.get(this); }
publicTypes() [1/2]
TemplateVariant ClassContext::Private::publicTypes () const [inline], [private]
Definition at line 1742 of file context.cpp.
{ return m_cachable.publicTypes.get(this); }
References m_cachable, and ClassContext::Private::Cachable::publicTypes.
publicTypes() [2/2]
TemplateVariant ClassContext::Private::publicTypes () const [inline], [private]
Definition at line 1742 of file context.cpp.
{ return m_cachable.publicTypes.get(this); }
related() [1/2]
TemplateVariant ClassContext::Private::related () const [inline], [private]
Definition at line 1768 of file context.cpp.
{ return m_cachable.related.get(this); }
References m_cachable, and ClassContext::Private::Cachable::related.
related() [2/2]
TemplateVariant ClassContext::Private::related () const [inline], [private]
Definition at line 1768 of file context.cpp.
{ return m_cachable.related.get(this); }
signals() [1/2]
TemplateVariant ClassContext::Private::signals () const [inline], [private]
Definition at line 1741 of file context.cpp.
{ return m_cachable.signals.get(this); }
References m_cachable, and ClassContext::Private::Cachable::signals.
signals() [2/2]
TemplateVariant ClassContext::Private::signals () const [inline], [private]
Definition at line 1741 of file context.cpp.
{ return m_cachable.signals.get(this); }
subHighlight() [1/2]
TemplateVariant ClassContext::Private::subHighlight () const [inline], [private]
Definition at line 1730 of file context.cpp.
{ return TemplateVariant(""); }
subHighlight() [2/2]
TemplateVariant ClassContext::Private::subHighlight () const [inline], [private]
Definition at line 1730 of file context.cpp.
{ return TemplateVariant(""); }
templateDecls() [1/2]
TemplateVariant ClassContext::Private::templateDecls () const [inline], [private]
Definition at line 1782 of file context.cpp.
{ return m_cachable.templateDecls.get(this); }
References m_cachable, and ClassContext::Private::Cachable::templateDecls.
templateDecls() [2/2]
TemplateVariant ClassContext::Private::templateDecls () const [inline], [private]
Definition at line 1782 of file context.cpp.
{ return m_cachable.templateDecls.get(this); }
title() [1/2]
TemplateVariant ClassContext::Private::title () const [inline], [private]
Definition at line 1728 of file context.cpp.
{ return TemplateVariant(m_classDef->title()); }
References m_classDef, and ClassDef::title().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), createMemberList(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
title() [2/2]
TemplateVariant ClassContext::Private::title () const [inline], [private]
Definition at line 1728 of file context.cpp.
{ return TemplateVariant(m_classDef->title()); }
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
typeConstraints() [1/2]
TemplateVariant ClassContext::Private::typeConstraints () const [inline], [private]
Definition at line 1783 of file context.cpp.
{ return m_cachable.typeConstraints.get(this); }
References m_cachable, and ClassContext::Private::Cachable::typeConstraints.
typeConstraints() [2/2]
TemplateVariant ClassContext::Private::typeConstraints () const [inline], [private]
Definition at line 1783 of file context.cpp.
{ return m_cachable.typeConstraints.get(this); }
unoIDLInterfaces() [1/2]
TemplateVariant ClassContext::Private::unoIDLInterfaces () const [inline], [private]
Definition at line 1740 of file context.cpp.
{ return m_cachable.unoIDLInterfaces.get(this); }
References m_cachable, and ClassContext::Private::Cachable::unoIDLInterfaces.
unoIDLInterfaces() [2/2]
TemplateVariant ClassContext::Private::unoIDLInterfaces () const [inline], [private]
Definition at line 1740 of file context.cpp.
{ return m_cachable.unoIDLInterfaces.get(this); }
unoIDLServices() [1/2]
TemplateVariant ClassContext::Private::unoIDLServices () const [inline], [private]
Definition at line 1739 of file context.cpp.
{ return m_cachable.unoIDLServices.get(this); }
References m_cachable, and ClassContext::Private::Cachable::unoIDLServices.
unoIDLServices() [2/2]
TemplateVariant ClassContext::Private::unoIDLServices () const [inline], [private]
Definition at line 1739 of file context.cpp.
{ return m_cachable.unoIDLServices.get(this); }
usedFiles() [1/2]
TemplateVariant ClassContext::Private::usedFiles () const [inline], [private]
Definition at line 1733 of file context.cpp.
{ return m_cachable.usedFiles.get(this); }
References m_cachable, and ClassContext::Private::Cachable::usedFiles.
usedFiles() [2/2]
TemplateVariant ClassContext::Private::usedFiles () const [inline], [private]
Definition at line 1733 of file context.cpp.
{ return m_cachable.usedFiles.get(this); }
Member Data Documentation
m_cachable
Cachable ClassContext::Private::m_cachable [private]
Definition at line 2393 of file context.cpp.
Referenced by additionalInheritedMembers(), allMembersList(), categoryOf(), classes(), detailedConstructors(), detailedEnums(), detailedEvents(), detailedInterfaces(), detailedMethods(), detailedProperties(), detailedRelated(), detailedServices(), detailedTypedefs(), detailedVariables(), events(), examples(), friends(), getClassGraph(), getCollaborationGraph(), includeInfo(), inheritedBy(), inherits(), innerClasses(), memberGroups(), members(), numInheritanceNodes(), packageAttributes(), packageMethods(), packageStaticAttributes(), packageStaticMethods(), packageTypes(), privateAttributes(), privateMethods(), privateSlots(), privateStaticAttributes(), privateStaticMethods(), privateTypes(), properties(), protectedAttributes(), protectedMethods(), protectedSlots(), protectedStaticAttributes(), protectedStaticMethods(), protectedTypes(), publicAttributes(), publicMethods(), publicSlots(), publicStaticAttributes(), publicStaticMethods(), publicTypes(), related(), signals(), templateDecls(), typeConstraints(), unoIDLInterfaces(), unoIDLServices(), and usedFiles().
m_classDef
const ClassDef * ClassContext::Private::m_classDef [private]
Definition at line 2332 of file context.cpp.
Referenced by allMembersFileName(), collaborationDiagram(), compoundType(), createAdditionalInheritedMembers(), createAllMembersList(), createCategoryOf(), createClasses(), createClassGraph(), createCollaborationGraph(), createExamples(), createIncludeInfo(), createInheritedByList(), createInheritsList(), createInnerClasses(), createMemberGroups(), createMemberList(), createMembers(), createNumInheritanceNodes(), createPublicMethods(), createPublicStaticMethods(), createTemplateDecls(), createTypeConstraints(), createUsedFiles(), generatedFromFiles(), hasDetails(), inheritanceDiagram(), isSimple(), and title().
s_inst
const PropertyMap< ClassContext::Private > ClassContext::Private::s_inst [static], [private]
Definition at line 2394 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp