TemplateEngine Class Reference
Engine to create templates and template contexts.
#include <template.h>
Classes
class Private
Private data of the template engine.
Public Member Functions
TemplateEngine ()
~TemplateEngine ()
std::unique_ptr< TemplateContext > createContext () const
Template * loadByName (const QCString &fileName, int fromLine)
void unload (Template *t)
void printIncludeContext (const QCString &fileName, int line) const
void setTemplateDir (const QCString &dirName)
TemplateEngine ()
~TemplateEngine ()
std::unique_ptr< TemplateContext > createContext () const
Template * loadByName (const QCString &fileName, int fromLine)
void unload (Template *t)
void printIncludeContext (const QCString &fileName, int line) const
void setTemplateDir (const QCString &dirName)
Private Member Functions
void enterBlock (const QCString &fileName, const QCString &blockName, int line)
void leaveBlock ()
void setOutputExtension (const QCString &extension)
QCString outputExtension () const
void enterBlock (const QCString &fileName, const QCString &blockName, int line)
void leaveBlock ()
void setOutputExtension (const QCString &extension)
QCString outputExtension () const
Private Attributes
std::unique_ptr< Private > p
Friends
class TemplateNodeBlock
class TemplateNodeCreate
Detailed Description
Engine to create templates and template contexts.
Definition at line 504 of file template.h.
Constructor & Destructor Documentation
TemplateEngine() [1/2]
TemplateEngine::TemplateEngine ()
Create a template engine.
Definition at line 5367 of file template.cpp.
                               : p(std::make_unique<Private>(this))
{
}
 TemplateEngine() [1/2]
TemplateEngine::~TemplateEngine ()
Destroys the template engine.
Definition at line 5371 of file template.cpp.
{
}
TemplateEngine() [2/2]
TemplateEngine::TemplateEngine ()
Create a template engine.
 TemplateEngine() [2/2]
TemplateEngine::~TemplateEngine ()
Destroys the template engine.
Member Function Documentation
createContext() [1/2]
std::unique_ptr< TemplateContext > TemplateEngine::createContext () const
Creates a new context that can be using to render a template.
See also
Template::render()
Definition at line 5375 of file template.cpp.
{
  return std::make_unique<TemplateContextImpl>(this);
}
createContext() [2/2]
std::unique_ptr< TemplateContext > TemplateEngine::createContext () const
Creates a new context that can be using to render a template.
See also
Template::render()
enterBlock() [1/2]
void TemplateEngine::enterBlock (const QCString & fileName, const QCString & blockName, int line) [private]
Definition at line 5390 of file template.cpp.
{
  p->enterBlock(fileName,blockName,line);
}
References p.
Referenced by TemplateNodeBlock::render().
enterBlock() [2/2]
void TemplateEngine::enterBlock (const QCString & fileName, const QCString & blockName, int line) [private]
leaveBlock() [1/2]
void TemplateEngine::leaveBlock () [private]
Definition at line 5395 of file template.cpp.
{
  p->leaveBlock();
}
References p.
Referenced by TemplateNodeBlock::render().
leaveBlock() [2/2]
void TemplateEngine::leaveBlock () [private]
loadByName() [1/2]
Template * TemplateEngine::loadByName (const QCString & fileName, int fromLine)
Creates a new template whose contents are in a file.
Parameters
 in fileName The name of the file containing the template data
 in fromLine The line number of the statement that triggered the load
Returns
the new template, the engine will keep ownership of the object.
Definition at line 5380 of file template.cpp.
{
  return p->loadByName(fileName,line);
}
References p.
Referenced by TemplateNodeCreate::render(), TemplateNodeExtend::render(), and TemplateNodeInclude::render().
loadByName() [2/2]
Template * TemplateEngine::loadByName (const QCString & fileName, int fromLine)
Creates a new template whose contents are in a file.
Parameters
 in fileName The name of the file containing the template data
 in fromLine The line number of the statement that triggered the load
Returns
the new template, the engine will keep ownership of the object.
outputExtension() [1/2]
QCString TemplateEngine::outputExtension () const [private]
Returns the output extension, set via setOutputExtension()
Definition at line 5410 of file template.cpp.
{
  return p->outputExtension();
}
References p.
outputExtension() [2/2]
QCString TemplateEngine::outputExtension () const [private]
Returns the output extension, set via setOutputExtension()
printIncludeContext() [1/2]
void TemplateEngine::printIncludeContext (const QCString & fileName, int line) const
Prints the current template file include stack
Definition at line 5400 of file template.cpp.
{
  p->printIncludeContext(fileName,line);
}
References p.
Referenced by TemplateLexer::tokenize(), TemplateContextImpl::warn(), and TemplateParser::warn().
printIncludeContext() [2/2]
void TemplateEngine::printIncludeContext (const QCString & fileName, int line) const
Prints the current template file include stack
setOutputExtension() [1/2]
void TemplateEngine::setOutputExtension (const QCString & extension) [private]
Sets the extension of the output file. This is used to control the format of 'special' tags in the template
Definition at line 5405 of file template.cpp.
{
  p->setOutputExtension(extension);
}
References p.
Referenced by TemplateNodeCreate::render().
setOutputExtension() [2/2]
void TemplateEngine::setOutputExtension (const QCString & extension) [private]
Sets the extension of the output file. This is used to control the format of 'special' tags in the template
setTemplateDir() [1/2]
void TemplateEngine::setTemplateDir (const QCString & dirName)
Sets the search directory where to look for template files
Definition at line 5415 of file template.cpp.
{
  p->setTemplateDir(dirName);
}
References p.
setTemplateDir() [2/2]
void TemplateEngine::setTemplateDir (const QCString & dirName)
Sets the search directory where to look for template files
unload() [1/2]
void TemplateEngine::unload (Template * t)
Indicates that template t is no longer needed. The engine may decide to delete it.
Definition at line 5385 of file template.cpp.
{
  p->unload(t);
}
References p.
Referenced by TemplateNodeCreate::render(), TemplateNodeExtend::render(), and TemplateNodeInclude::render().
unload() [2/2]
void TemplateEngine::unload (Template * t)
Indicates that template t is no longer needed. The engine may decide to delete it.
Friends And Related Function Documentation
TemplateNodeBlock
TemplateNodeBlock [friend]
Definition at line 537 of file template.h.
TemplateNodeCreate
TemplateNodeCreate [friend]
Definition at line 538 of file template.h.
Member Data Documentation
p
std::unique_ptr< Private > TemplateEngine::p [private]
Definition at line 552 of file template.h.
Referenced by enterBlock(), leaveBlock(), loadByName(), outputExtension(), printIncludeContext(), setOutputExtension(), setTemplateDir(), and unload().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.h
doxygen/src/template.h
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp