DocHtmlList Class Reference
#include <docnode.h>
Public Types
enum Type { Unordered
, Ordered
, Unordered
, Ordered
 }
enum Type { Unordered
, Ordered
, Unordered
, Ordered
 }
Public Member Functions
DocHtmlList (DocParser *parser, DocNodeVariant *parent, const HtmlAttribList &attribs, Type t)
Type type () const
const HtmlAttribList & attribs () const
int parse (DocNodeVariant *)
int parseXml (DocNodeVariant *)
DocHtmlList (DocParser *parser, DocNodeVariant *parent, const HtmlAttribList &attribs, Type t)
Type type () const
const HtmlAttribList & attribs () const
int parse (DocNodeVariant *)
int parseXml (DocNodeVariant *)
Private Attributes
Type m_type = Unordered
HtmlAttribList m_attribs
Additional Inherited Members
Detailed Description
Node representing a Html list
Definition at line 952 of file docnode.h.
Member Enumeration Documentation
Type [1/2]
enum DocHtmlList::Type
Enumerator
Unordered
Ordered
Unordered
Ordered
Definition at line 955 of file docnode.h.
{ Unordered, Ordered };
Type [2/2]
enum DocHtmlList::Type
Enumerator
Unordered
Ordered
Unordered
Ordered
Definition at line 955 of file docnode.h.
{ Unordered, Ordered };
Constructor & Destructor Documentation
DocHtmlList() [1/2]
DocHtmlList::DocHtmlList (DocParser * parser, DocNodeVariant * parent, const HtmlAttribList & attribs, Type t) [inline]
Definition at line 956 of file docnode.h.
                                                                                               :
      DocCompoundNode(parser,parent), m_type(t), m_attribs(attribs) {}
DocHtmlList() [2/2]
DocHtmlList::DocHtmlList (DocParser * parser, DocNodeVariant * parent, const HtmlAttribList & attribs, Type t) [inline]
Definition at line 956 of file docnode.h.
                                                                                               :
      DocCompoundNode(parser,parent), m_type(t), m_attribs(attribs) {}
Member Function Documentation
attribs() [1/2]
const HtmlAttribList & DocHtmlList::attribs () const [inline]
Definition at line 959 of file docnode.h.
{ return m_attribs; }
References m_attribs.
Referenced by PerlModDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), and DocbookDocVisitor::operator()().
attribs() [2/2]
const HtmlAttribList & DocHtmlList::attribs () const [inline]
Definition at line 959 of file docnode.h.
{ return m_attribs; }
References m_attribs.
parse() [1/2]
int DocHtmlList::parse (DocNodeVariant * thisVariant)
Definition at line 2426 of file docnode.cpp.
{
  DBG(("DocHtmlList::parse() start\n"));
  int retval=RetVal_OK;
  int num=1;
  auto ns = AutoNodeStack(parser(),thisVariant);
  // get next token
  int tok=parser()->tokenizer.lex();
  // skip whitespace and paragraph breaks
  while (tok==TK_WHITESPACE || tok==TK_NEWPARA) tok=parser()->tokenizer.lex();
  // should find a html tag now
  if (tok==TK_HTMLTAG)
  {
    int tagId=Mappers::htmlTagMapper->map(parser()->context.token->name);
    if (tagId==HTML_LI && !parser()->context.token->endTag) // found <li> tag
    {
      // ok, we can go on.
    }
    else if (((m_type==Unordered && tagId==HTML_UL) ||
              (m_type==Ordered && tagId==HTML_OL)
             ) && parser()->context.token->endTag
            ) // found empty list
    {
      // add dummy item to obtain valid HTML
      children().append<DocHtmlListItem>(parser(),thisVariant,HtmlAttribList(),1);
      warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"empty list!");
      retval = RetVal_EndList;
      goto endlist;
    }
    else // found some other tag
    {
      // add dummy item to obtain valid HTML
      children().append<DocHtmlListItem>(parser(),thisVariant,HtmlAttribList(),1);
      warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"expected <li> tag but "
          "found <%s%s> instead!",parser()->context.token->endTag?"/":"",qPrint(parser()->context.token->name));
      parser()->tokenizer.pushBackHtmlTag(parser()->context.token->name);
      goto endlist;
    }
  }
  else if (tok==0) // premature end of comment
  {
    // add dummy item to obtain valid HTML
    children().append<DocHtmlListItem>(parser(),thisVariant,HtmlAttribList(),1);
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"unexpected end of comment while looking"
        " for a html list item");
    goto endlist;
  }
  else // token other than html token
  {
    // add dummy item to obtain valid HTML
    children().append<DocHtmlListItem>(parser(),thisVariant,HtmlAttribList(),1);
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"expected <li> tag but found %s token instead!",
        DocTokenizer::tokToString(tok));
    goto endlist;
  }
  do
  {
    auto vDocHtmlListItem = children().append<DocHtmlListItem>(parser(),thisVariant,parser()->context.token->attribs,num++);
    DocHtmlListItem *li = children().get_last<DocHtmlListItem>();
    retval=li->parse(vDocHtmlListItem);
  } while (retval==RetVal_ListItem);
  if (retval==0)
  {
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"unexpected end of comment while inside <%cl> block",
        m_type==Unordered ? 'u' : 'o');
  }
endlist:
  DBG(("DocHtmlList::parse() end retval=%s\n",DocTokenizer::retvalToString(retval)));
  return retval==RetVal_EndList ? RetVal_OK : retval;
}
References DocNodeList::append(), TokenInfo::attribs, DocCompoundNode::children(), DocParser::context, DBG, DocNodeList::get_last(), HTML_LI, HTML_OL, HTML_UL, Mappers::htmlTagMapper, DocTokenizer::lex(), m_type, Mapper::map(), Ordered, DocHtmlListItem::parse(), DocNode::parser(), DocTokenizer::pushBackHtmlTag(), qPrint(), RetVal_EndList, RetVal_ListItem, RetVal_OK, DocTokenizer::retvalToString(), TK_HTMLTAG, TK_NEWPARA, TK_WHITESPACE, DocParserContext::token, DocParser::tokenizer, DocTokenizer::tokToString(), Unordered, and warn_doc_error().
parse() [2/2]
int DocHtmlList::parse (DocNodeVariant *)
parseXml() [1/2]
int DocHtmlList::parseXml (DocNodeVariant * thisVariant)
Definition at line 2501 of file docnode.cpp.
{
  DBG(("DocHtmlList::parseXml() start\n"));
  int retval=RetVal_OK;
  int num=1;
  auto ns = AutoNodeStack(parser(),thisVariant);
  // get next token
  int tok=parser()->tokenizer.lex();
  // skip whitespace and paragraph breaks
  while (tok==TK_WHITESPACE || tok==TK_NEWPARA) tok=parser()->tokenizer.lex();
  // should find a html tag now
  if (tok==TK_HTMLTAG)
  {
    int tagId=Mappers::htmlTagMapper->map(parser()->context.token->name);
    //printf("parser()->context.token->name=%s parser()->context.token->endTag=%d\n",qPrint(parser()->context.token->name),parser()->context.token->endTag);
    if (tagId==XML_ITEM && !parser()->context.token->endTag) // found <item> tag
    {
      // ok, we can go on.
    }
    else // found some other tag
    {
      warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"expected <item> tag but "
          "found <%s> instead!",qPrint(parser()->context.token->name));
      parser()->tokenizer.pushBackHtmlTag(parser()->context.token->name);
      goto endlist;
    }
  }
  else if (tok==0) // premature end of comment
  {
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"unexpected end of comment while looking"
        " for a html list item");
    goto endlist;
  }
  else // token other than html token
  {
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"expected <item> tag but found %s token instead!",
        DocTokenizer::tokToString(tok));
    goto endlist;
  }
  do
  {
    auto vDocHtmlListItem = children().append<DocHtmlListItem>(parser(),thisVariant,parser()->context.token->attribs,num++);
    DocHtmlListItem *li = children().get_last<DocHtmlListItem>();
    retval=li->parseXml(vDocHtmlListItem);
    if (retval==0) break;
    //printf("retval=%x parser()->context.token->name=%s\n",retval,qPrint(parser()->context.token->name));
  } while (retval==RetVal_ListItem);
  if (retval==0)
  {
    warn_doc_error(parser()->context.fileName,parser()->tokenizer.getLineNr(),"unexpected end of comment while inside <list type=\"%s\"> block",
        m_type==Unordered ? "bullet" : "number");
  }
endlist:
  DBG(("DocHtmlList::parseXml() end retval=%s\n",DocTokenizer::retvalToString(retval)));
  return retval==RetVal_EndList ||
         (retval==RetVal_CloseXml || parser()->context.token->name=="list") ?
         RetVal_OK : retval;
}
References DocNodeList::append(), TokenInfo::attribs, DocCompoundNode::children(), DocParser::context, DBG, DocNodeList::get_last(), Mappers::htmlTagMapper, DocTokenizer::lex(), m_type, Mapper::map(), TokenInfo::name, DocNode::parser(), DocHtmlListItem::parseXml(), DocTokenizer::pushBackHtmlTag(), qPrint(), RetVal_CloseXml, RetVal_EndList, RetVal_ListItem, RetVal_OK, DocTokenizer::retvalToString(), TK_HTMLTAG, TK_NEWPARA, TK_WHITESPACE, DocParserContext::token, DocParser::tokenizer, DocTokenizer::tokToString(), Unordered, warn_doc_error(), and XML_ITEM.
parseXml() [2/2]
int DocHtmlList::parseXml (DocNodeVariant *)
type() [1/2]
Type DocHtmlList::type () const [inline]
Definition at line 958 of file docnode.h.
{ return m_type; }
References m_type.
Referenced by PerlModDocVisitor::operator()(), RTFDocVisitor::operator()(), DocbookDocVisitor::operator()(), and ManDocVisitor::operator()().
type() [2/2]
Type DocHtmlList::type () const [inline]
Definition at line 958 of file docnode.h.
{ return m_type; }
References m_type.
Member Data Documentation
m_attribs
HtmlAttribList DocHtmlList::m_attribs [private]
Definition at line 965 of file docnode.h.
Referenced by attribs().
m_type
Type DocHtmlList::m_type = Unordered [private]
Definition at line 964 of file docnode.h.
Referenced by parse(), parseXml(), and type().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/docnode.h
doxygen/src/docnode.h
doxygen/build/doxygen/src/docnode.cpp
doxygen/src/docnode.cpp