MainWindow Class Reference
#include <doxywizard.h>
Public Slots
void manual ()
void about ()
void openConfig ()
bool saveConfig ()
bool saveConfigAs ()
void makeDefaults ()
void resetToDefaults ()
void selectTab (int)
void quit ()
void manual ()
void about ()
void openConfig ()
bool saveConfig ()
bool saveConfigAs ()
void makeDefaults ()
void resetToDefaults ()
void selectTab (int)
void quit ()
Public Member Functions
void loadConfigFromFile (const QString &fileName)
void loadSettings ()
void saveSettings ()
void closeEvent (QCloseEvent *event)
QString configFileName () const
void updateTitle ()
void outputLogStart ()
void outputLogText (QString text)
void outputLogFinish ()
void loadConfigFromFile (const QString &fileName)
void loadSettings ()
void saveSettings ()
void closeEvent (QCloseEvent *event)
QString configFileName () const
void updateTitle ()
void outputLogStart ()
void outputLogText (QString text)
void outputLogFinish ()
Static Public Member Functions
static MainWindow & instance ()
static MainWindow & instance ()
Private Slots
void openRecent (QAction *action)
void selectWorkingDir ()
void updateWorkingDir ()
void runDoxygen ()
void readStdout ()
void runComplete ()
void showHtmlOutput ()
void saveLog ()
void showSettings ()
void configChanged ()
void clearRecent ()
void selectRunTab ()
void openRecent (QAction *action)
void selectWorkingDir ()
void updateWorkingDir ()
void runDoxygen ()
void readStdout ()
void runComplete ()
void showHtmlOutput ()
void saveLog ()
void showSettings ()
void configChanged ()
void clearRecent ()
void selectRunTab ()
Private Member Functions
MainWindow ()
void saveConfig (const QString &fileName)
void addRecentFile (const QString &fileName)
void addRecentFileList (const QString &fileName)
void updateRecentFile (void)
void updateConfigFileName (const QString &fileName)
void setWorkingDir (const QString &dirName)
void updateLaunchButtonState ()
bool discardUnsavedChanges (bool saveOption=true)
MainWindow ()
void saveConfig (const QString &fileName)
void addRecentFile (const QString &fileName)
void addRecentFileList (const QString &fileName)
void updateRecentFile (void)
void updateConfigFileName (const QString &fileName)
void setWorkingDir (const QString &dirName)
void updateLaunchButtonState ()
bool discardUnsavedChanges (bool saveOption=true)
Private Attributes
QLineEdit * m_workingDir
QLineEdit * m_runOptions
QPushButton * m_selWorkingDir
QPushButton * m_run
QPushButton * m_saveLog
QCheckBox * m_showCondensedSettings
QPushButton * m_launchHtml
QPushButton * m_launchPdf
QTextBrowser * m_outputLog
QLabel * m_runStatus
Expert * m_expert
Wizard * m_wizard
QString m_fileName
QSettings m_settings
QMenu * m_recentMenu
QStringList m_recentFiles
QAction * m_resetDefault
QAction * m_clearRecent
QProcess * m_runProcess
QTimer * m_timer
QTabWidget * m_tabs
int m_outputLogTextCount = 0
bool m_running
bool m_modified
Detailed Description
Definition at line 32 of file doxywizard.h.
Constructor & Destructor Documentation
MainWindow() [1/2]
MainWindow::MainWindow () [private]
Definition at line 62 of file doxywizard.cpp.
  : m_settings(QString::fromLatin1("Doxygen.org"), QString::fromLatin1("Doxywizard"))
{
  QMenu *file = menuBar()->addMenu(tr("File"));
  file->addAction(tr("Open..."),
                  this, SLOT(openConfig()), Qt::CTRL|Qt::Key_O);
  m_recentMenu = file->addMenu(tr("Open recent"));
  file->addAction(tr("Save"),
                  this, SLOT(saveConfig()), Qt::CTRL|Qt::Key_S);
  file->addAction(tr("Save as..."),
                  this, SLOT(saveConfigAs()), Qt::SHIFT|Qt::CTRL|Qt::Key_S);
  file->addAction(tr("Quit"),
                  this, SLOT(quit()), Qt::CTRL|Qt::Key_Q);
  QMenu *settings = menuBar()->addMenu(tr("Settings"));
  m_resetDefault = settings->addAction(tr("Reset to factory defaults"),
                  this,SLOT(resetToDefaults()));
  settings->addAction(tr("Use current settings at startup"),
                  this,SLOT(makeDefaults()));
  m_clearRecent = settings->addAction(tr("Clear recent list"),
                  this,SLOT(clearRecent()));
  QMenu *help = menuBar()->addMenu(tr("Help"));
  help->addAction(tr("Online manual"),
                  this, SLOT(manual()), Qt::Key_F1);
  help->addAction(tr("About"),
                  this, SLOT(about()));
  m_expert = new Expert;
  m_wizard = new Wizard(m_expert->modelData());
  // ----------- top part ------------------
  QWidget *mainPart = new QWidget;
  QVBoxLayout *mainLayout = new QVBoxLayout(mainPart);
  QWidget *topPart = new QWidget;
  QVBoxLayout *rowLayout = new QVBoxLayout(topPart);
  mainLayout->addWidget(topPart);
  // select working directory
  QHBoxLayout *dirLayout = new QHBoxLayout;
  m_workingDir = new QLineEdit;
  m_selWorkingDir = new QPushButton(tr("Select..."));
  dirLayout->addWidget(m_workingDir);
  dirLayout->addWidget(m_selWorkingDir);
  //------------- bottom part --------------
  QWidget *runTab = new QWidget;
  QVBoxLayout *runTabLayout = new QVBoxLayout(runTab);
  // run doxygen
  QHBoxLayout *runLayout = new QHBoxLayout;
  m_run = new QPushButton(tr("Run doxygen"));
  m_run->setEnabled(false);
  m_runStatus = new QLabel(tr("Status: not running"));
  m_saveLog = new QPushButton(tr("Save log..."));
  m_saveLog->setEnabled(false);
  QPushButton *showSettings = new QPushButton(tr("Show configuration"));
  m_showCondensedSettings = new QCheckBox(this);
  m_showCondensedSettings->setText(tr("Condensed"));
  m_showCondensedSettings->setChecked(false);
  m_showCondensedSettings->setToolTip(tr("Show only configuration settings different from default settings"));
  // select extra run options
  m_runOptions = new QLineEdit;
  runTabLayout->addWidget(new QLabel(tr("Specify additional command line options for running doxygen")));
  runTabLayout->addWidget(m_runOptions);
  QVBoxLayout *runVLayout = new QVBoxLayout;
  runLayout->addLayout(runVLayout);
  QHBoxLayout *runVHLayout = new QHBoxLayout;
  runVLayout->addLayout(runVHLayout);
  runVHLayout->addWidget(m_run);
  runVHLayout->addWidget(m_runStatus);
  QHBoxLayout *runVH2Layout = new QHBoxLayout;
  runVLayout->addLayout(runVH2Layout);
  m_launchHtml = new QPushButton(tr("Show HTML output"));
  runVH2Layout->addWidget(m_launchHtml);
  runVH2Layout->addStretch(1); // to have launch button not being stretched
  runLayout->addStretch(1);
  QVBoxLayout *settingsLayout = new QVBoxLayout;
  runLayout->addLayout(settingsLayout);
  settingsLayout->addWidget(m_showCondensedSettings);
  settingsLayout->addWidget(showSettings);
  QVBoxLayout *saveLayout = new QVBoxLayout;
  runLayout->addLayout(saveLayout);
  saveLayout->addWidget(m_saveLog);
  saveLayout->setAlignment(Qt::AlignTop);
  // saveLayout->addWidget(new QWidget); // to have the save button at the top
  // output produced by Doxygen
  runTabLayout->addLayout(runLayout);
  runTabLayout->addWidget(new QLabel(tr("Output produced by doxygen")));
  QGridLayout *grid = new QGridLayout;
  //m_outputLog = new QTextEdit;
  m_outputLog = new QTextBrowser;
  //m_outputLog = new QPlainTextEdit;
  m_outputLog->setReadOnly(true);
  m_outputLog->setFontFamily(QString::fromLatin1("courier"));
  m_outputLog->setMinimumWidth(600);
  grid->addWidget(m_outputLog,0,0);
  grid->setColumnStretch(0,1);
  grid->setRowStretch(0,1);
  runTabLayout->addLayout(grid);
  m_tabs = new QTabWidget;
  m_tabs->addTab(m_wizard,tr("Wizard"));
  m_tabs->addTab(m_expert,tr("Expert"));
  m_tabs->addTab(runTab,tr("Run"));
  rowLayout->addWidget(new QLabel(tr("Specify the working directory from which doxygen will run")));
  rowLayout->addLayout(dirLayout);
  rowLayout->addWidget(new QLabel(tr("Configure doxygen using the Wizard and/or Expert tab, then switch to the Run tab to generate the documentation")));
  mainLayout->addWidget(m_tabs);
  setCentralWidget(mainPart);
  statusBar()->showMessage(tr("Welcome to Doxygen"),messageTimeout);
  m_runProcess = new QProcess;
  m_running = false;
  m_timer = new QTimer;
  // connect signals and slots
  connect(m_tabs,SIGNAL(currentChanged(int)),SLOT(selectTab(int)));
  connect(m_selWorkingDir,SIGNAL(clicked()),SLOT(selectWorkingDir()));
  connect(m_recentMenu,SIGNAL(triggered(QAction*)),SLOT(openRecent(QAction*)));
  connect(m_workingDir,SIGNAL(returnPressed()),SLOT(updateWorkingDir()));
  connect(m_runProcess,SIGNAL(readyReadStandardOutput()),SLOT(readStdout()));
  connect(m_runProcess,SIGNAL(finished(int, QProcess::ExitStatus)),SLOT(runComplete()));
  connect(m_timer,SIGNAL(timeout()),SLOT(readStdout()));
  connect(m_run,SIGNAL(clicked()),SLOT(runDoxygen()));
  connect(m_launchHtml,SIGNAL(clicked()),SLOT(showHtmlOutput()));
  connect(m_saveLog,SIGNAL(clicked()),SLOT(saveLog()));
  connect(showSettings,SIGNAL(clicked()),SLOT(showSettings()));
  connect(m_expert,SIGNAL(changed()),SLOT(configChanged()));
  connect(m_wizard,SIGNAL(done()),SLOT(selectRunTab()));
  connect(m_expert,SIGNAL(done()),SLOT(selectRunTab()));
  loadSettings();
  updateLaunchButtonState();
  m_modified = false;
  updateTitle();
  m_wizard->refresh();
}
References about(), clearRecent(), configChanged(), caseconvert::file, loadSettings(), m_clearRecent, m_expert, m_launchHtml, m_modified, m_outputLog, m_recentMenu, m_resetDefault, m_run, m_running, m_runOptions, m_runProcess, m_runStatus, m_saveLog, m_selWorkingDir, m_showCondensedSettings, m_tabs, m_timer, m_wizard, m_workingDir, makeDefaults(), manual(), messageTimeout, Expert::modelData(), openConfig(), openRecent(), quit(), readStdout(), Wizard::refresh(), resetToDefaults(), runComplete(), runDoxygen(), saveConfig(), saveConfigAs(), saveLog(), selectRunTab(), selectTab(), selectWorkingDir(), showHtmlOutput(), showSettings(), updateLaunchButtonState(), updateTitle(), and updateWorkingDir().
Referenced by instance().
MainWindow() [2/2]
MainWindow::MainWindow () [private]
Member Function Documentation
about [1/2]
void MainWindow::about () [slot]
Definition at line 265 of file doxywizard.cpp.
{
  QString msg;
  QTextStream t(&msg,QIODevice::WriteOnly);
  t << QString::fromLatin1("<qt><center>A tool to configure and run doxygen version ")+
       QString::fromLatin1(getDoxygenVersion())+
       QString::fromLatin1(" on your source files.</center>")+
       QString::fromLatin1("<center>(Created with Qt version ")+
       QString::fromLatin1(QT_VERSION_STR);
       if (qstrcmp(qVersion(),QT_VERSION_STR))
       {
         t << QString::fromLatin1(", running with ")+
              QString::fromLatin1(qVersion());
       }
  t << QString::fromLatin1(")</center><p><br>"
       "<center>Written by<br> Dimitri van Heesch<br>&copy; 2000-");
  t << QDate::currentDate().year();
  t << QString::fromLatin1("</center><p></qt>");
  QMessageBox::about(this,tr("Doxygen GUI"),msg);
}
References getDoxygenVersion(), msg(), and qstrcmp().
Referenced by MainWindow().
about [2/2]
void MainWindow::about () [slot]
addRecentFile() [1/2]
void MainWindow::addRecentFile (const QString & fileName) [private]
Definition at line 476 of file doxywizard.cpp.
{
  addRecentFileList(fileName);
  updateRecentFile();
}
References addRecentFileList(), and updateRecentFile().
Referenced by updateConfigFileName().
addRecentFile() [2/2]
void MainWindow::addRecentFile (const QString & fileName) [private]
addRecentFileList() [1/2]
void MainWindow::addRecentFileList (const QString & fileName) [private]
Definition at line 481 of file doxywizard.cpp.
{
  int i=m_recentFiles.indexOf(fileName);
  if (i!=-1) m_recentFiles.removeAt(i);
  // not found
  if (m_recentFiles.count() < MAX_RECENT_FILES) // append
  {
    m_recentFiles.prepend(fileName);
  }
  else // add + drop last item
  {
    m_recentFiles.removeLast();
    m_recentFiles.prepend(fileName);
  }
  m_clearRecent->setEnabled(m_recentFiles.count()>0);
  m_recentMenu->setEnabled(m_recentFiles.count()>0);
  m_settings.sync();
}
References m_clearRecent, m_recentFiles, m_recentMenu, m_settings, and MAX_RECENT_FILES.
Referenced by addRecentFile(), and loadSettings().
addRecentFileList() [2/2]
void MainWindow::addRecentFileList (const QString & fileName) [private]
clearRecent [1/2]
void MainWindow::clearRecent () [private], [slot]
Definition at line 383 of file doxywizard.cpp.
{
  if (QMessageBox::question(this,tr("Clear the list of recent files?"),
                        tr("Do you want to clear the list of recently "
                           "loaded configuration files?"),
                        QMessageBox::Yes|
                        QMessageBox::Cancel)==QMessageBox::Yes)
  {
    m_recentMenu->clear();
    m_recentFiles.clear();
    for (int i=0;i<MAX_RECENT_FILES;i++)
    {
      m_settings.setValue(QString::fromLatin1("recent/config%1").arg(i),QString::fromLatin1(""));
    }
    m_clearRecent->setEnabled(false);
    m_recentMenu->setEnabled(false);
    m_settings.sync();
  }
}
References m_clearRecent, m_recentFiles, m_recentMenu, m_settings, and MAX_RECENT_FILES.
Referenced by MainWindow().
clearRecent [2/2]
void MainWindow::clearRecent () [private], [slot]
closeEvent() [1/2]
void MainWindow::closeEvent (QCloseEvent * event)
Definition at line 212 of file doxywizard.cpp.
{
  if (discardUnsavedChanges())
  {
    saveSettings();
    event->accept();
  }
  else
  {
    event->ignore();
  }
}
References discardUnsavedChanges(), and saveSettings().
closeEvent() [2/2]
void MainWindow::closeEvent (QCloseEvent * event)
configChanged [1/2]
void MainWindow::configChanged () [private], [slot]
Definition at line 705 of file doxywizard.cpp.
{
  m_modified = true;
  updateTitle();
}
References m_modified, and updateTitle().
Referenced by MainWindow().
configChanged [2/2]
void MainWindow::configChanged () [private], [slot]
configFileName() [1/2]
QString MainWindow::configFileName () const [inline]
Definition at line 42 of file doxywizard.h.
{ return m_fileName; }
References m_fileName.
configFileName() [2/2]
QString MainWindow::configFileName () const [inline]
Definition at line 42 of file doxywizard.h.
{ return m_fileName; }
References m_fileName.
discardUnsavedChanges() [1/2]
bool MainWindow::discardUnsavedChanges (bool saveOption = true) [private]
Definition at line 726 of file doxywizard.cpp.
{
  if (m_modified)
  {
    QMessageBox::StandardButton button;
    if (saveOption)
    {
      button = QMessageBox::question(this,
          tr("Unsaved changes"),
          tr("Unsaved changes will be lost! Do you want to save the configuration file?"),
          QMessageBox::Save |
          QMessageBox::Discard |
          QMessageBox::Cancel
          );
      if (button==QMessageBox::Save)
      {
        return saveConfig();
      }
    }
    else
    {
      button = QMessageBox::question(this,
          tr("Unsaved changes"),
          tr("Unsaved changes will be lost! Do you want to continue?"),
          QMessageBox::Discard |
          QMessageBox::Cancel
          );
    }
    return button==QMessageBox::Discard;
  }
  return true;
}
References m_modified, and saveConfig().
Referenced by closeEvent(), openConfig(), openRecent(), and quit().
discardUnsavedChanges() [2/2]
bool MainWindow::discardUnsavedChanges (bool saveOption = true) [private]
instance() [1/2]
MainWindow & MainWindow::instance () [static]
Definition at line 56 of file doxywizard.cpp.
{
  static MainWindow *theInstance = new MainWindow;
  return *theInstance;
}
References MainWindow().
Referenced by InputString::browseDir(), InputStrList::browseDir(), InputString::browseFile(), InputStrList::browseFiles(), config_err(), config_finish(), config_open(), config_term(), config_warn(), main(), Step1::selectDestinationDir(), Step1::selectProjectIcon(), and Step1::selectSourceDir().
instance() [2/2]
static MainWindow & MainWindow::instance () [static]
loadConfigFromFile() [1/2]
void MainWindow::loadConfigFromFile (const QString & fileName)
Definition at line 312 of file doxywizard.cpp.
{
  // save full path info of original file
  QString absFileName = QFileInfo(fileName).absoluteFilePath();
  // updates the current directory
  updateConfigFileName(fileName);
  // open the specified configuration file
  m_expert->loadConfig(absFileName);
  m_wizard->refresh();
  updateLaunchButtonState();
  m_modified = false;
  updateTitle();
}
References Expert::loadConfig(), m_expert, m_modified, m_wizard, Wizard::refresh(), updateConfigFileName(), updateLaunchButtonState(), and updateTitle().
Referenced by openConfig(), and openRecent().
loadConfigFromFile() [2/2]
void MainWindow::loadConfigFromFile (const QString & fileName)
loadSettings() [1/2]
void MainWindow::loadSettings ()
Definition at line 422 of file doxywizard.cpp.
{
  QVariant geometry = m_settings.value(QString::fromLatin1("main/geometry"));
  QVariant state = m_settings.value(QString::fromLatin1("main/state"));
  QVariant wizState = m_settings.value(QString::fromLatin1("wizard/state"));
  QVariant loadSettings = m_settings.value(QString::fromLatin1("wizard/loadsettings"));
  QVariant workingDir = m_settings.value(QString::fromLatin1("wizard/workingdir"));
  if (!geometry.isNull()) restoreGeometry(geometry.toByteArray());
  if (!state.isNull()) restoreState (state.toByteArray());
  if (!wizState.isNull()) m_wizard->restoreState(wizState.toByteArray());
  if (!loadSettings.isNull() && loadSettings.toBool())
  {
    m_expert->loadSettings(&m_settings);
    if (!workingDir.isNull() && QDir(workingDir.toString()).exists())
    {
      setWorkingDir(workingDir.toString());
    }
  }
  /* due to prepend use list in reversed order */
  for (int i=MAX_RECENT_FILES;i>=0;i--)
  {
    QString entry = m_settings.value(QString::fromLatin1("recent/config%1").arg(i)).toString();
    if (!entry.isEmpty() && QFileInfo(entry).exists())
    {
      addRecentFileList(entry);
    }
  }
  updateRecentFile();
}
References addRecentFileList(), ghc::filesystem::exists(), loadSettings(), Expert::loadSettings(), m_expert, m_settings, m_wizard, MAX_RECENT_FILES, setWorkingDir(), and updateRecentFile().
Referenced by loadSettings(), and MainWindow().
loadSettings() [2/2]
void MainWindow::loadSettings ()
makeDefaults [1/2]
void MainWindow::makeDefaults () [slot]
Definition at line 368 of file doxywizard.cpp.
{
  if (QMessageBox::question(this,tr("Use current setting at startup?"),
                        tr("Do you want to save the current settings "
                           "and use them next time Doxywizard starts?"),
                        QMessageBox::Save|
                        QMessageBox::Cancel)==QMessageBox::Save)
  {
    //printf("MainWindow:makeDefaults()\n");
    m_expert->saveSettings(&m_settings);
    m_settings.setValue(QString::fromLatin1("wizard/loadsettings"), true);
    m_settings.sync();
  }
}
References m_expert, m_settings, and Expert::saveSettings().
Referenced by MainWindow().
makeDefaults [2/2]
void MainWindow::makeDefaults () [slot]
manual [1/2]
void MainWindow::manual () [slot]
Definition at line 260 of file doxywizard.cpp.
{
  QDesktopServices::openUrl(QUrl(QString::fromLatin1("https://www.doxygen.org/manual/index.html")));
}
Referenced by MainWindow().
manual [2/2]
void MainWindow::manual () [slot]
openConfig [1/2]
void MainWindow::openConfig () [slot]
Definition at line 286 of file doxywizard.cpp.
{
  if (discardUnsavedChanges(false))
  {
    QString fn = QFileDialog::getOpenFileName(this,
        tr("Open configuration file"),
        m_workingDir->text());
    if (!fn.isEmpty())
    {
      loadConfigFromFile(fn);
    }
  }
}
References discardUnsavedChanges(), loadConfigFromFile(), and m_workingDir.
Referenced by MainWindow().
openConfig [2/2]
void MainWindow::openConfig () [slot]
openRecent [1/2]
void MainWindow::openRecent (QAction * action) [private], [slot]
Definition at line 518 of file doxywizard.cpp.
{
  if (discardUnsavedChanges(false))
  {
    loadConfigFromFile(action->text());
  }
}
References discardUnsavedChanges(), and loadConfigFromFile().
Referenced by MainWindow().
openRecent [2/2]
void MainWindow::openRecent (QAction * action) [private], [slot]
outputLogFinish() [1/2]
void MainWindow::outputLogFinish ()
Definition at line 769 of file doxywizard.cpp.
{
  if (m_outputLogTextCount > 0)
  {
    selectRunTab();
  }
  m_outputLog->ensureCursorVisible();
  m_saveLog->setEnabled(true);
}
References m_outputLog, m_outputLogTextCount, m_saveLog, and selectRunTab().
Referenced by config_finish().
outputLogFinish() [2/2]
void MainWindow::outputLogFinish ()
outputLogStart() [1/2]
void MainWindow::outputLogStart ()
Definition at line 759 of file doxywizard.cpp.
{
  m_outputLogTextCount = 0;
  m_outputLog->clear();
}
References m_outputLog, and m_outputLogTextCount.
Referenced by config_open().
outputLogStart() [2/2]
void MainWindow::outputLogStart ()
outputLogText() [1/2]
void MainWindow::outputLogText (QString text)
Definition at line 764 of file doxywizard.cpp.
{
  m_outputLogTextCount++;
  m_outputLog->append(APPQT(text));
}
References APPQT, m_outputLog, and m_outputLogTextCount.
Referenced by config_err(), config_term(), and config_warn().
outputLogText() [2/2]
void MainWindow::outputLogText (QString text)
quit [1/2]
void MainWindow::quit () [slot]
Definition at line 225 of file doxywizard.cpp.
{
  if (discardUnsavedChanges())
  {
    saveSettings();
  }
  else
  {
    return;
  }
  QApplication::exit(0);
}
References discardUnsavedChanges(), and saveSettings().
Referenced by MainWindow().
quit [2/2]
void MainWindow::quit () [slot]
readStdout [1/2]
void MainWindow::readStdout () [private], [slot]
Definition at line 608 of file doxywizard.cpp.
{
  if (m_running)
  {
    QByteArray data = m_runProcess->readAllStandardOutput();
    QString text = QString::fromUtf8(data);
    if (!text.isEmpty())
    {
      text1 += text;
      m_outputLog->clear();
      m_outputLog->append(APPQT(text1.toHtmlEscaped().trimmed()));
    }
  }
}
References APPQT, data, ghc::filesystem::detail::fromUtf8(), m_outputLog, m_running, m_runProcess, and text1.
Referenced by MainWindow().
readStdout [2/2]
void MainWindow::readStdout () [private], [slot]
resetToDefaults [1/2]
void MainWindow::resetToDefaults () [slot]
Definition at line 404 of file doxywizard.cpp.
{
  if (QMessageBox::question(this,tr("Reset settings to their default values?"),
                        tr("Do you want to revert all settings back "
                           "to their original values?"),
                        QMessageBox::Reset|
                        QMessageBox::Cancel)==QMessageBox::Reset)
  {
    //printf("MainWindow:resetToDefaults()\n");
    m_expert->resetToDefaults();
    m_settings.setValue(QString::fromLatin1("wizard/loadsettings"), false);
    m_settings.sync();
    m_modified = false;
    updateTitle();
    m_wizard->refresh();
  }
}
References m_expert, m_modified, m_settings, m_wizard, Wizard::refresh(), Expert::resetToDefaults(), and updateTitle().
Referenced by MainWindow().
resetToDefaults [2/2]
void MainWindow::resetToDefaults () [slot]
runComplete [1/2]
void MainWindow::runComplete () [private], [slot]
Definition at line 623 of file doxywizard.cpp.
{
  if (m_running)
  {
    m_outputLog->append(APPQT(tr("*** Doxygen has finished\n")));
  }
  else
  {
    m_outputLog->append(APPQT(tr("*** Cancelled by user\n")));
  }
  m_outputLog->ensureCursorVisible();
  m_run->setText(tr("Run doxygen"));
  m_runStatus->setText(tr("Status: not running"));
  m_running=false;
  updateLaunchButtonState();
  //updateRunnable(m_workingDir->text());
  m_saveLog->setEnabled(true);
}
References APPQT, m_outputLog, m_run, m_running, m_runStatus, m_saveLog, and updateLaunchButtonState().
Referenced by MainWindow().
runComplete [2/2]
void MainWindow::runComplete () [private], [slot]
runDoxygen [1/2]
void MainWindow::runDoxygen () [private], [slot]
Definition at line 526 of file doxywizard.cpp.
{
  if (!m_running)
  {
    QString doxygenPath;
#if defined(Q_OS_MACX)
    doxygenPath = qApp->applicationDirPath()+QString::fromLatin1("/../Resources/");
    qDebug() << tr("Doxygen path: ") << doxygenPath;
    if (!QFile(doxygenPath + QString::fromLatin1("doxygen")).exists())
    {
      // No Doxygen binary in the resources, if there is a system Doxygen binary, use that instead
      if (QFile(QString::fromLatin1("/usr/local/bin/doxygen")).exists())
      {
        doxygenPath = QString::fromLatin1("/usr/local/bin/");
      }
      else
      {
        qDebug() << tr("Can't find the doxygen command, make sure it's in your $$PATH");
        doxygenPath = QString::fromLatin1("");
      }
    }
    qDebug() << tr("Getting doxygen from: ") << doxygenPath;
#endif
    m_runProcess->setReadChannel(QProcess::StandardOutput);
    m_runProcess->setProcessChannelMode(QProcess::MergedChannels);
    m_runProcess->setWorkingDirectory(m_workingDir->text());
    QStringList env=QProcess::systemEnvironment();
    // set PWD environment variable to m_workingDir
    env.replaceInStrings(QRegularExpression(QString::fromLatin1("^PWD=(.*)"),QRegularExpression::CaseInsensitiveOption),
                         QString::fromLatin1("PWD=")+m_workingDir->text());
    m_runProcess->setEnvironment(env);
    QStringList args;
#if QT_VERSION < QT_VERSION_CHECK(5, 15, 0)
    QStringList runOptions = m_runOptions->text().split(QLatin1Char(' '),QString::SkipEmptyParts);
#else
    QStringList runOptions = m_runOptions->text().split(QLatin1Char(' '),Qt::SkipEmptyParts);
#endif
    args << runOptions;
    args << QString::fromLatin1("-b"); // make stdout unbuffered
    args << QString::fromLatin1("-"); // read config from stdin
    m_outputLog->clear();
    text1 = QString::fromLatin1("");
    m_runProcess->start(doxygenPath + QString::fromLatin1("doxygen"), args);
    if (!m_runProcess->waitForStarted())
    {
      m_outputLog->append(APPQT(QString::fromLatin1("*** Failed to run doxygen\n")));
      return;
    }
    QTextStream t(m_runProcess);
    m_expert->writeConfig(t,false,false);
    t.flush();
    m_runProcess->closeWriteChannel();
    if (m_runProcess->state() == QProcess::NotRunning)
    {
      m_outputLog->append(APPQT(QString::fromLatin1("*** Failed to run doxygen\n")));
    }
    else
    {
      m_saveLog->setEnabled(false);
      m_running=true;
      m_run->setText(tr("Stop doxygen"));
      m_runStatus->setText(tr("Status: running"));
      m_timer->start(1000);
    }
  }
  else
  {
    m_running=false;
    m_run->setText(tr("Run doxygen"));
    m_runStatus->setText(tr("Status: not running"));
    m_runProcess->kill();
    m_timer->stop();
    //updateRunnable(m_workingDir->text());
  }
}
References APPQT, ghc::filesystem::exists(), m_expert, m_outputLog, m_run, m_running, m_runOptions, m_runProcess, m_runStatus, m_saveLog, m_timer, m_workingDir, text1, and Expert::writeConfig().
Referenced by MainWindow().
runDoxygen [2/2]
void MainWindow::runDoxygen () [private], [slot]
saveConfig [1/4]
bool MainWindow::saveConfig () [slot]
Definition at line 346 of file doxywizard.cpp.
{
  if (m_fileName.isEmpty())
  {
    return saveConfigAs();
  }
  else
  {
    saveConfig(m_fileName);
    return true;
  }
}
References m_fileName, saveConfig(), and saveConfigAs().
Referenced by discardUnsavedChanges(), MainWindow(), saveConfig(), and saveConfigAs().
saveConfig [2/4]
bool MainWindow::saveConfig () [slot]
saveConfig() [3/4]
void MainWindow::saveConfig (const QString & fileName) [private]
Definition at line 326 of file doxywizard.cpp.
{
  if (fileName.isEmpty()) return;
  QFile f(fileName);
  if (!f.open(QIODevice::WriteOnly | QIODevice::Text))
  {
    QMessageBox::warning(this,
        tr("Error saving"),
        QString(tr("Error: cannot open the file "))+fileName+tr(" for writing!\n")+
        tr("Reason given: ")+QString::number(f.error()));
    return;
  }
  QTextStream t(&f);
  t.device()->setTextModeEnabled(false);
  m_expert->writeConfig(t,false,false);
  updateConfigFileName(fileName);
  m_modified = false;
  updateTitle();
}
References f, m_expert, m_modified, updateConfigFileName(), updateTitle(), and Expert::writeConfig().
saveConfig() [4/4]
void MainWindow::saveConfig (const QString & fileName) [private]
saveConfigAs [1/2]
bool MainWindow::saveConfigAs () [slot]
Definition at line 359 of file doxywizard.cpp.
{
  QString fileName = QFileDialog::getSaveFileName(this, QString(),
             m_workingDir->text()+QString::fromLatin1("/Doxyfile"));
  if (fileName.isEmpty()) return false;
  saveConfig(fileName);
  return true;
}
References m_workingDir, and saveConfig().
Referenced by MainWindow(), and saveConfig().
saveConfigAs [2/2]
bool MainWindow::saveConfigAs () [slot]
saveLog [1/2]
void MainWindow::saveLog () [private], [slot]
Definition at line 665 of file doxywizard.cpp.
{
  QString fn = QFileDialog::getSaveFileName(this, tr("Save log file"),
        m_workingDir->text()+
        QString::fromLatin1("/doxygen_log.txt"));
  if (!fn.isEmpty())
  {
    QFile f(fn);
    if (f.open(QIODevice::WriteOnly))
    {
      QTextStream t(&f);
      t << m_outputLog->toPlainText();
      statusBar()->showMessage(tr("Output log saved"),messageTimeout);
    }
    else
    {
      QMessageBox::warning(0,tr("Warning"),
          tr("Cannot open file ")+fn+tr(" for writing. Nothing saved!"),tr("ok"));
    }
  }
}
References f, m_outputLog, m_workingDir, and messageTimeout.
Referenced by MainWindow().
saveLog [2/2]
void MainWindow::saveLog () [private], [slot]
saveSettings() [1/2]
void MainWindow::saveSettings ()
Definition at line 455 of file doxywizard.cpp.
{
  QSettings settings(QString::fromLatin1("Doxygen.org"), QString::fromLatin1("Doxywizard"));
  m_settings.setValue(QString::fromLatin1("main/geometry"), saveGeometry());
  m_settings.setValue(QString::fromLatin1("main/state"), saveState());
  m_settings.setValue(QString::fromLatin1("wizard/state"), m_wizard->saveState());
  m_settings.setValue(QString::fromLatin1("wizard/workingdir"), m_workingDir->text());
}
References m_settings, m_wizard, and m_workingDir.
Referenced by closeEvent(), and quit().
saveSettings() [2/2]
void MainWindow::saveSettings ()
selectRunTab [1/2]
void MainWindow::selectRunTab () [private], [slot]
Definition at line 471 of file doxywizard.cpp.
{
  m_tabs->setCurrentIndex(2);
}
References m_tabs.
Referenced by MainWindow(), and outputLogFinish().
selectRunTab [2/2]
void MainWindow::selectRunTab () [private], [slot]
selectTab [1/2]
void MainWindow::selectTab (int id) [slot]
Definition at line 465 of file doxywizard.cpp.
{
  if (id==0) m_wizard->refresh();
  else if (id==1) m_expert->refresh();
}
References m_expert, m_wizard, Expert::refresh(), and Wizard::refresh().
Referenced by MainWindow().
selectTab [2/2]
void MainWindow::selectTab (int) [slot]
selectWorkingDir [1/2]
void MainWindow::selectWorkingDir () [private], [slot]
Definition at line 245 of file doxywizard.cpp.
{
  QString dirName = QFileDialog::getExistingDirectory(this,
        tr("Select working directory"),m_workingDir->text());
  if (!dirName.isEmpty())
  {
    setWorkingDir(dirName);
  }
}
References m_workingDir, and setWorkingDir().
Referenced by MainWindow().
selectWorkingDir [2/2]
void MainWindow::selectWorkingDir () [private], [slot]
setWorkingDir() [1/2]
void MainWindow::setWorkingDir (const QString & dirName) [private]
Definition at line 238 of file doxywizard.cpp.
{
    QDir::setCurrent(dirName);
    m_workingDir->setText(dirName);
    m_run->setEnabled(!dirName.isEmpty());
}
References m_run, and m_workingDir.
Referenced by loadSettings(), selectWorkingDir(), updateConfigFileName(), and updateWorkingDir().
setWorkingDir() [2/2]
void MainWindow::setWorkingDir (const QString & dirName) [private]
showHtmlOutput [1/2]
void MainWindow::showHtmlOutput () [private], [slot]
Definition at line 650 of file doxywizard.cpp.
{
  QString indexFile = m_expert->getHtmlOutputIndex(m_workingDir->text());
  QFileInfo fi(indexFile);
  // TODO: the following doesn't seem to work with IE
#ifdef _WIN32
  //QString indexUrl(QString::fromLatin1("file:///"));
  ShellExecute(NULL, L"open", (LPCWSTR)fi.absoluteFilePath().utf16(), NULL, NULL, SW_SHOWNORMAL);
#else
  QString indexUrl(QString::fromLatin1("file://"));
  indexUrl+=fi.absoluteFilePath();
  QDesktopServices::openUrl(QUrl(indexUrl));
#endif
}
References Expert::getHtmlOutputIndex(), m_expert, and m_workingDir.
Referenced by MainWindow().
showHtmlOutput [2/2]
void MainWindow::showHtmlOutput () [private], [slot]
showSettings [1/2]
void MainWindow::showSettings () [private], [slot]
Definition at line 687 of file doxywizard.cpp.
{
  QString text;
  QTextStream t(&text);
  if (m_showCondensedSettings->isChecked())
  {
    m_expert->writeConfig(t,true,true);
  }
  else
  {
    m_expert->writeConfig(t,true,false);
  }
  m_outputLog->clear();
  m_outputLog->append(APPQT(text));
  m_outputLog->ensureCursorVisible();
  m_saveLog->setEnabled(true);
}
References APPQT, m_expert, m_outputLog, m_saveLog, m_showCondensedSettings, and Expert::writeConfig().
Referenced by MainWindow().
showSettings [2/2]
void MainWindow::showSettings () [private], [slot]
updateConfigFileName() [1/2]
void MainWindow::updateConfigFileName (const QString & fileName) [private]
Definition at line 300 of file doxywizard.cpp.
{
  if (m_fileName!=fileName)
  {
    m_fileName = fileName;
    QString curPath = QFileInfo(fileName).path();
    setWorkingDir(curPath);
    addRecentFile(fileName);
    updateTitle();
  }
}
References addRecentFile(), m_fileName, setWorkingDir(), and updateTitle().
Referenced by loadConfigFromFile(), and saveConfig().
updateConfigFileName() [2/2]
void MainWindow::updateConfigFileName (const QString & fileName) [private]
updateLaunchButtonState() [1/2]
void MainWindow::updateLaunchButtonState () [private]
Definition at line 642 of file doxywizard.cpp.
{
  m_launchHtml->setEnabled(m_expert->htmlOutputPresent(m_workingDir->text()));
#if 0
  m_launchPdf->setEnabled(m_expert->pdfOutputPresent(m_workingDir->text()));
#endif
}
References Expert::htmlOutputPresent(), m_expert, m_launchHtml, m_launchPdf, m_workingDir, and Expert::pdfOutputPresent().
Referenced by loadConfigFromFile(), MainWindow(), and runComplete().
updateLaunchButtonState() [2/2]
void MainWindow::updateLaunchButtonState () [private]
updateRecentFile() [1/2]
void MainWindow::updateRecentFile (void) [private]
Definition at line 500 of file doxywizard.cpp.
{
  m_recentMenu->clear();
  int i=0;
  foreach(QString str, m_recentFiles)
  {
    m_recentMenu->addAction(str);
    m_settings.setValue(QString::fromLatin1("recent/config%1").arg(i++),str);
  }
  for (;i<MAX_RECENT_FILES;i++)
  {
    m_settings.setValue(QString::fromLatin1("recent/config%1").arg(i),QString::fromLatin1(""));
  }
  m_clearRecent->setEnabled(m_recentFiles.count()>0);
  m_recentMenu->setEnabled(m_recentFiles.count()>0);
  m_settings.sync();
}
References m_clearRecent, m_recentFiles, m_recentMenu, m_settings, and MAX_RECENT_FILES.
Referenced by addRecentFile(), and loadSettings().
updateRecentFile() [2/2]
void MainWindow::updateRecentFile (void) [private]
updateTitle() [1/2]
void MainWindow::updateTitle ()
Definition at line 711 of file doxywizard.cpp.
{
  QString title = tr("Doxygen GUI frontend");
  m_resetDefault->setEnabled(m_modified);
  if (m_modified)
  {
    title+=QString::fromLatin1(" +");
  }
  if (!m_fileName.isEmpty())
  {
    title+=QString::fromLatin1(" (")+m_fileName+QString::fromLatin1(")");
  }
  setWindowTitle(title);
}
References m_fileName, m_modified, and m_resetDefault.
Referenced by configChanged(), loadConfigFromFile(), MainWindow(), resetToDefaults(), saveConfig(), and updateConfigFileName().
updateTitle() [2/2]
void MainWindow::updateTitle ()
updateWorkingDir [1/2]
void MainWindow::updateWorkingDir () [private], [slot]
Definition at line 255 of file doxywizard.cpp.
{
  setWorkingDir(m_workingDir->text());
}
References m_workingDir, and setWorkingDir().
Referenced by MainWindow().
updateWorkingDir [2/2]
void MainWindow::updateWorkingDir () [private], [slot]
Member Data Documentation
m_clearRecent
QAction * MainWindow::m_clearRecent [private]
Definition at line 102 of file doxywizard.h.
Referenced by addRecentFileList(), clearRecent(), MainWindow(), and updateRecentFile().
m_expert
Expert * MainWindow::m_expert [private]
Definition at line 95 of file doxywizard.h.
Referenced by loadConfigFromFile(), loadSettings(), MainWindow(), makeDefaults(), resetToDefaults(), runDoxygen(), saveConfig(), selectTab(), showHtmlOutput(), showSettings(), and updateLaunchButtonState().
m_fileName
QString MainWindow::m_fileName [private]
Definition at line 97 of file doxywizard.h.
Referenced by configFileName(), saveConfig(), updateConfigFileName(), and updateTitle().
m_launchHtml
QPushButton * MainWindow::m_launchHtml [private]
Definition at line 91 of file doxywizard.h.
Referenced by MainWindow(), and updateLaunchButtonState().
m_launchPdf
QPushButton * MainWindow::m_launchPdf [private]
Definition at line 92 of file doxywizard.h.
Referenced by updateLaunchButtonState().
m_modified
bool MainWindow::m_modified [private]
Definition at line 108 of file doxywizard.h.
Referenced by configChanged(), discardUnsavedChanges(), loadConfigFromFile(), MainWindow(), resetToDefaults(), saveConfig(), and updateTitle().
m_outputLog
QTextBrowser * MainWindow::m_outputLog [private]
Definition at line 93 of file doxywizard.h.
Referenced by MainWindow(), outputLogFinish(), outputLogStart(), outputLogText(), readStdout(), runComplete(), runDoxygen(), saveLog(), and showSettings().
m_outputLogTextCount
int MainWindow::m_outputLogTextCount = 0 [private]
Definition at line 106 of file doxywizard.h.
Referenced by outputLogFinish(), outputLogStart(), and outputLogText().
m_recentFiles
QStringList MainWindow::m_recentFiles [private]
Definition at line 100 of file doxywizard.h.
Referenced by addRecentFileList(), clearRecent(), and updateRecentFile().
m_recentMenu
QMenu * MainWindow::m_recentMenu [private]
Definition at line 99 of file doxywizard.h.
Referenced by addRecentFileList(), clearRecent(), MainWindow(), and updateRecentFile().
m_resetDefault
QAction * MainWindow::m_resetDefault [private]
Definition at line 101 of file doxywizard.h.
Referenced by MainWindow(), and updateTitle().
m_run
QPushButton * MainWindow::m_run [private]
Definition at line 88 of file doxywizard.h.
Referenced by MainWindow(), runComplete(), runDoxygen(), and setWorkingDir().
m_running
bool MainWindow::m_running [private]
Definition at line 107 of file doxywizard.h.
Referenced by MainWindow(), readStdout(), runComplete(), and runDoxygen().
m_runOptions
QLineEdit * MainWindow::m_runOptions [private]
Definition at line 86 of file doxywizard.h.
Referenced by MainWindow(), and runDoxygen().
m_runProcess
QProcess * MainWindow::m_runProcess [private]
Definition at line 103 of file doxywizard.h.
Referenced by MainWindow(), readStdout(), and runDoxygen().
m_runStatus
QLabel * MainWindow::m_runStatus [private]
Definition at line 94 of file doxywizard.h.
Referenced by MainWindow(), runComplete(), and runDoxygen().
m_saveLog
QPushButton * MainWindow::m_saveLog [private]
Definition at line 89 of file doxywizard.h.
Referenced by MainWindow(), outputLogFinish(), runComplete(), runDoxygen(), and showSettings().
m_selWorkingDir
QPushButton * MainWindow::m_selWorkingDir [private]
Definition at line 87 of file doxywizard.h.
Referenced by MainWindow().
m_settings
QSettings MainWindow::m_settings [private]
Definition at line 98 of file doxywizard.h.
Referenced by addRecentFileList(), clearRecent(), loadSettings(), makeDefaults(), resetToDefaults(), saveSettings(), and updateRecentFile().
m_showCondensedSettings
QCheckBox * MainWindow::m_showCondensedSettings [private]
Definition at line 90 of file doxywizard.h.
Referenced by MainWindow(), and showSettings().
m_tabs
QTabWidget * MainWindow::m_tabs [private]
Definition at line 105 of file doxywizard.h.
Referenced by MainWindow(), and selectRunTab().
m_timer
QTimer * MainWindow::m_timer [private]
Definition at line 104 of file doxywizard.h.
Referenced by MainWindow(), and runDoxygen().
m_wizard
Wizard * MainWindow::m_wizard [private]
Definition at line 96 of file doxywizard.h.
Referenced by loadConfigFromFile(), loadSettings(), MainWindow(), resetToDefaults(), saveSettings(), and selectTab().
m_workingDir
QLineEdit * MainWindow::m_workingDir [private]
Definition at line 85 of file doxywizard.h.
Referenced by MainWindow(), openConfig(), runDoxygen(), saveConfigAs(), saveLog(), saveSettings(), selectWorkingDir(), setWorkingDir(), showHtmlOutput(), updateLaunchButtonState(), and updateWorkingDir().
The documentation for this class was generated from the following files:
doxygen/addon/doxywizard/doxywizard.h
doxygen/build/doxygen/addon/doxywizard/doxywizard.h
doxygen/addon/doxywizard/doxywizard.cpp
doxygen/build/doxygen/addon/doxywizard/doxywizard.cpp