ManDocVisitor Class Reference
Concrete visitor implementation for LaTeX output.
#include <mandocvisitor.h>
Public Member Functions
ManDocVisitor (TextStream &t, CodeOutputInterface &ci, const QCString &langExt)
void operator() (const DocWord &)
void operator() (const DocLinkedWord &)
void operator() (const DocWhiteSpace &)
void operator() (const DocSymbol &)
void operator() (const DocEmoji &)
void operator() (const DocURL &)
void operator() (const DocLineBreak &)
void operator() (const DocHorRuler &)
void operator() (const DocStyleChange &)
void operator() (const DocVerbatim &)
void operator() (const DocAnchor &)
void operator() (const DocInclude &)
void operator() (const DocIncOperator &)
void operator() (const DocFormula &)
void operator() (const DocIndexEntry &)
void operator() (const DocSimpleSectSep &)
void operator() (const DocCite &)
void operator() (const DocSeparator &)
void operator() (const DocAutoList &)
void operator() (const DocAutoListItem &)
void operator() (const DocPara &)
void operator() (const DocRoot &)
void operator() (const DocSimpleSect &)
void operator() (const DocTitle &)
void operator() (const DocSimpleList &)
void operator() (const DocSimpleListItem &)
void operator() (const DocSection &s)
void operator() (const DocHtmlList &s)
void operator() (const DocHtmlListItem &)
void operator() (const DocHtmlDescList &)
void operator() (const DocHtmlDescTitle &)
void operator() (const DocHtmlDescData &)
void operator() (const DocHtmlTable &t)
void operator() (const DocHtmlCaption &)
void operator() (const DocHtmlRow &)
void operator() (const DocHtmlCell &)
void operator() (const DocInternal &)
void operator() (const DocHRef &)
void operator() (const DocHtmlSummary &)
void operator() (const DocHtmlDetails &)
void operator() (const DocHtmlHeader &)
void operator() (const DocImage &)
void operator() (const DocDotFile &)
void operator() (const DocMscFile &)
void operator() (const DocDiaFile &)
void operator() (const DocLink &lnk)
void operator() (const DocRef &ref)
void operator() (const DocSecRefItem &)
void operator() (const DocSecRefList &)
void operator() (const DocParamSect &)
void operator() (const DocParamList &)
void operator() (const DocXRefItem &)
void operator() (const DocInternalRef &)
void operator() (const DocText &)
void operator() (const DocHtmlBlockQuote &)
void operator() (const DocVhdlFlow &)
void operator() (const DocParBlock &)
ManDocVisitor (TextStream &t, CodeOutputInterface &ci, const QCString &langExt)
void operator() (const DocWord &)
void operator() (const DocLinkedWord &)
void operator() (const DocWhiteSpace &)
void operator() (const DocSymbol &)
void operator() (const DocEmoji &)
void operator() (const DocURL &)
void operator() (const DocLineBreak &)
void operator() (const DocHorRuler &)
void operator() (const DocStyleChange &)
void operator() (const DocVerbatim &)
void operator() (const DocAnchor &)
void operator() (const DocInclude &)
void operator() (const DocIncOperator &)
void operator() (const DocFormula &)
void operator() (const DocIndexEntry &)
void operator() (const DocSimpleSectSep &)
void operator() (const DocCite &)
void operator() (const DocSeparator &)
void operator() (const DocAutoList &)
void operator() (const DocAutoListItem &)
void operator() (const DocPara &)
void operator() (const DocRoot &)
void operator() (const DocSimpleSect &)
void operator() (const DocTitle &)
void operator() (const DocSimpleList &)
void operator() (const DocSimpleListItem &)
void operator() (const DocSection &s)
void operator() (const DocHtmlList &s)
void operator() (const DocHtmlListItem &)
void operator() (const DocHtmlDescList &)
void operator() (const DocHtmlDescTitle &)
void operator() (const DocHtmlDescData &)
void operator() (const DocHtmlTable &t)
void operator() (const DocHtmlCaption &)
void operator() (const DocHtmlRow &)
void operator() (const DocHtmlCell &)
void operator() (const DocInternal &)
void operator() (const DocHRef &)
void operator() (const DocHtmlSummary &)
void operator() (const DocHtmlDetails &)
void operator() (const DocHtmlHeader &)
void operator() (const DocImage &)
void operator() (const DocDotFile &)
void operator() (const DocMscFile &)
void operator() (const DocDiaFile &)
void operator() (const DocLink &lnk)
void operator() (const DocRef &ref)
void operator() (const DocSecRefItem &)
void operator() (const DocSecRefList &)
void operator() (const DocParamSect &)
void operator() (const DocParamList &)
void operator() (const DocXRefItem &)
void operator() (const DocInternalRef &)
void operator() (const DocText &)
void operator() (const DocHtmlBlockQuote &)
void operator() (const DocVhdlFlow &)
void operator() (const DocParBlock &)
Private Member Functions
template<class T >
void visitChildren (const T &t)
void filter (const QCString &str)
template<class T >
void visitChildren (const T &t)
void filter (const QCString &str)
Private Attributes
TextStream & m_t
CodeOutputInterface & m_ci
bool m_insidePre
bool m_hide
bool m_firstCol
int m_indent
QCString m_langExt
Detailed Description
Concrete visitor implementation for LaTeX output.
Definition at line 32 of file mandocvisitor.h.
Constructor & Destructor Documentation
ManDocVisitor() [1/2]
ManDocVisitor::ManDocVisitor (TextStream & t, CodeOutputInterface & ci, const QCString & langExt)
Definition at line 33 of file mandocvisitor.cpp.
  : m_t(t), m_ci(ci), m_insidePre(FALSE), m_hide(FALSE), m_firstCol(FALSE),
    m_indent(0), m_langExt(langExt)
{
}
ManDocVisitor() [2/2]
ManDocVisitor::ManDocVisitor (TextStream & t, CodeOutputInterface & ci, const QCString & langExt)
Member Function Documentation
filter() [1/2]
void ManDocVisitor::filter (const QCString & str) [private]
Definition at line 987 of file mandocvisitor.cpp.
{
  if (!str.isEmpty())
  {
    const char *p=str.data();
    char c=0;
    while ((c=*p++))
    {
      switch(c)
      {
        case '.': m_t << "\\&."; break; // see bug652277
        case '\\': m_t << "\\\\"; break;
        case '"': c = '\''; // fall through
        default: m_t << c; break;
      }
    }
  }
}
References c, QCString::data(), QCString::isEmpty(), m_t, and p.
Referenced by operator()().
filter() [2/2]
void ManDocVisitor::filter (const QCString & str) [private]
operator()() [1/114]
void ManDocVisitor::operator() (const DocAnchor &)
Definition at line 251 of file mandocvisitor.cpp.
{
  /* no support for anchors in man pages */
}
operator()() [2/114]
void ManDocVisitor::operator() (const DocAnchor &)
operator()() [3/114]
void ManDocVisitor::operator() (const DocAutoList & l)
Definition at line 477 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  m_indent+=2;
  visitChildren(l);
  m_indent-=2;
  m_t << ".PP\n";
}
References m_hide, m_indent, m_t, and visitChildren().
operator()() [4/114]
void ManDocVisitor::operator() (const DocAutoList &)
operator()() [5/114]
void ManDocVisitor::operator() (const DocAutoListItem & li)
Definition at line 486 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  QCString ws;
  ws.fill(' ',m_indent-2);
  if (!m_firstCol) m_t << "\n";
  m_t << ".IP \"" << ws;
  const DocAutoList *list = std::get_if<DocAutoList>(li.parent());
  if (list && list->isEnumList())
  {
    m_t << li.itemNumber() << ".\" " << m_indent+2;
  }
  else // bullet list
  {
    m_t << "\\(bu\" " << m_indent;
  }
  m_t << "\n";
  m_firstCol=TRUE;
  visitChildren(li);
  m_t << "\n";
  m_firstCol=TRUE;
}
References QCString::fill(), DocAutoList::isEnumList(), DocAutoListItem::itemNumber(), m_firstCol, m_hide, m_indent, m_t, DocNode::parent(), TRUE, and visitChildren().
operator()() [6/114]
void ManDocVisitor::operator() (const DocAutoListItem &)
operator()() [7/114]
void ManDocVisitor::operator() (const DocCite & cite)
Definition at line 456 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "\\fB";
  if (cite.file().isEmpty()) m_t << "[";
  filter(cite.text());
  if (cite.file().isEmpty()) m_t << "]";
  m_t << "\\fP";
}
References DocCite::file(), filter(), QCString::isEmpty(), m_hide, m_t, and DocCite::text().
operator()() [8/114]
void ManDocVisitor::operator() (const DocCite &)
operator()() [9/114]
void ManDocVisitor::operator() (const DocDiaFile &)
Definition at line 831 of file mandocvisitor.cpp.
{
}
operator()() [10/114]
void ManDocVisitor::operator() (const DocDiaFile &)
operator()() [11/114]
void ManDocVisitor::operator() (const DocDotFile & f)
Definition at line 823 of file mandocvisitor.cpp.
{
}
operator()() [12/114]
void ManDocVisitor::operator() (const DocDotFile &)
operator()() [13/114]
void ManDocVisitor::operator() (const DocEmoji & s)
Definition at line 91 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  const char *res = EmojiEntityMapper::instance()->name(s.index());
  if (res)
  {
    m_t << res;
  }
  else
  {
    m_t << s.name();
  }
  m_firstCol=FALSE;
}
References FALSE, EmojiEntityMapper::instance(), m_firstCol, m_hide, m_t, EmojiEntityMapper::name(), and s.
operator()() [14/114]
void ManDocVisitor::operator() (const DocEmoji &)
operator()() [15/114]
void ManDocVisitor::operator() (const DocFormula & f)
Definition at line 442 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  m_t << f.text();
}
References f, m_hide, and m_t.
operator()() [16/114]
void ManDocVisitor::operator() (const DocFormula &)
operator()() [17/114]
void ManDocVisitor::operator() (const DocHorRuler &)
Definition at line 120 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  if (!m_firstCol) m_t << "\n";
  m_t << ".PP\n";
  m_firstCol=TRUE;
}
References m_firstCol, m_hide, m_t, and TRUE.
operator()() [18/114]
void ManDocVisitor::operator() (const DocHorRuler &)
operator()() [19/114]
void ManDocVisitor::operator() (const DocHRef & href)
Definition at line 767 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "\\fC";
  visitChildren(href);
  m_t << "\\fP";
}
References m_hide, m_t, and visitChildren().
operator()() [20/114]
void ManDocVisitor::operator() (const DocHRef &)
operator()() [21/114]
void ManDocVisitor::operator() (const DocHtmlBlockQuote & q)
Definition at line 962 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  if (!m_firstCol)
  {
    m_t << "\n";
    m_t << ".PP\n";
  }
  m_t << ".RS 4\n"; // TODO: add support for nested block quotes
  visitChildren(q);
  if (!m_firstCol) m_t << "\n";
  m_t << ".RE\n";
  m_t << ".PP\n";
  m_firstCol=TRUE;
}
References m_firstCol, m_hide, m_t, TRUE, and visitChildren().
operator()() [22/114]
void ManDocVisitor::operator() (const DocHtmlBlockQuote &)
operator()() [23/114]
void ManDocVisitor::operator() (const DocHtmlCaption & c)
Definition at line 747 of file mandocvisitor.cpp.
{
  visitChildren(c);
}
References c, and visitChildren().
operator()() [24/114]
void ManDocVisitor::operator() (const DocHtmlCaption &)
operator()() [25/114]
void ManDocVisitor::operator() (const DocHtmlCell & c)
Definition at line 757 of file mandocvisitor.cpp.
{
  visitChildren(c);
}
References c, and visitChildren().
operator()() [26/114]
void ManDocVisitor::operator() (const DocHtmlCell &)
operator()() [27/114]
void ManDocVisitor::operator() (const DocHtmlDescData & dd)
Definition at line 737 of file mandocvisitor.cpp.
{
  visitChildren(dd);
}
References visitChildren().
operator()() [28/114]
void ManDocVisitor::operator() (const DocHtmlDescData &)
operator()() [29/114]
void ManDocVisitor::operator() (const DocHtmlDescList & dl)
Definition at line 717 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  visitChildren(dl);
  if (!m_firstCol) m_t << "\n";
  m_t << ".PP\n";
  m_firstCol=TRUE;
}
References m_firstCol, m_hide, m_t, TRUE, and visitChildren().
operator()() [30/114]
void ManDocVisitor::operator() (const DocHtmlDescList &)
operator()() [31/114]
void ManDocVisitor::operator() (const DocHtmlDescTitle & dt)
Definition at line 726 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  if (!m_firstCol) m_t << "\n";
  m_t << ".IP \"\\fB";
  m_firstCol=FALSE;
  visitChildren(dt);
  m_t << "\\fP\" 1c\n";
  m_firstCol=TRUE;
}
References FALSE, m_firstCol, m_hide, m_t, TRUE, and visitChildren().
operator()() [32/114]
void ManDocVisitor::operator() (const DocHtmlDescTitle &)
operator()() [33/114]
void ManDocVisitor::operator() (const DocHtmlDetails & d)
Definition at line 782 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  if (!m_firstCol)
  {
    m_t << "\n";
    m_t << ".PP\n";
  }
  auto summary = d.summary();
  if (summary)
  {
    std::visit(*this,*summary);
    m_t << ".PP\n";
    m_t << ".RS 4\n";
  }
  visitChildren(d);
  if (!m_firstCol) m_t << "\n";
  if (summary)
  {
    m_t << ".RE\n";
  }
  m_t << ".PP\n";
  m_firstCol=TRUE;
}
References m_firstCol, m_hide, m_t, DocHtmlDetails::summary(), TRUE, and visitChildren().
operator()() [34/114]
void ManDocVisitor::operator() (const DocHtmlDetails &)
operator()() [35/114]
void ManDocVisitor::operator() (const DocHtmlHeader & header)
Definition at line 807 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  if (!m_firstCol) m_t << "\n";
  if (header.level()==1) m_t << ".SH"; else m_t << ".SS";
  m_t << " \"";
  visitChildren(header);
  m_t << "\"\n";
  if (header.level()==1) m_t << ".PP\n";
  m_firstCol=TRUE;
}
References DocHtmlHeader::level(), m_firstCol, m_hide, m_t, TRUE, and visitChildren().
operator()() [36/114]
void ManDocVisitor::operator() (const DocHtmlHeader &)
operator()() [37/114]
void ManDocVisitor::operator() (const DocHtmlList & s)
Definition at line 636 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  m_indent+=2;
  if (!m_firstCol) m_t << "\n";
  m_t << ".PD 0\n";
  man_listItemInfo[m_indent].number = 1;
  man_listItemInfo[m_indent].type = '1';
  for (const auto &opt : l.attribs())
  {
    if (opt.name=="type")
    {
      man_listItemInfo[m_indent].type = opt.value[0];
    }
    if (opt.name=="start")
    {
      bool ok;
      int val = opt.value.toInt(&ok);
      if (ok) man_listItemInfo[m_indent].number = val;
    }
  }
  visitChildren(l);
  m_indent-=2;
  if (!m_firstCol) m_t << "\n";
  m_t << ".PP\n";
}
References DocHtmlList::attribs(), m_firstCol, m_hide, m_indent, m_t, man_listItemInfo, ManListItemInfo::number, ManListItemInfo::type, testsqlite3::val, and visitChildren().
operator()() [38/114]
void ManDocVisitor::operator() (const DocHtmlList & s)
operator()() [39/114]
void ManDocVisitor::operator() (const DocHtmlListItem & li)
Definition at line 663 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  QCString ws;
  ws.fill(' ',m_indent-2);
  if (!m_firstCol) m_t << "\n";
  m_t << ".IP \"" << ws;
  const DocHtmlList *list = std::get_if<DocHtmlList>(li.parent());
  if (list && list->type()==DocHtmlList::Ordered)
  {
    for (const auto &opt : li.attribs())
    {
      if (opt.name=="value")
      {
        bool ok;
        int val = opt.value.toInt(&ok);
        if (ok) man_listItemInfo[m_indent].number = val;
      }
    }
    switch (man_listItemInfo[m_indent].type)
    {
      case '1':
        m_t << man_listItemInfo[m_indent].number;
        break;
      case 'a':
        m_t << integerToAlpha(man_listItemInfo[m_indent].number,false);
        break;
      case 'A':
        m_t << integerToAlpha(man_listItemInfo[m_indent].number);
        break;
      case 'i':
        m_t << integerToRoman(man_listItemInfo[m_indent].number,false);
        break;
      case 'I':
        m_t << integerToRoman(man_listItemInfo[m_indent].number);
        break;
      default:
        m_t << man_listItemInfo[m_indent].number;
        break;
    }
    m_t << ".\" " << m_indent+2;
    man_listItemInfo[m_indent].number++;
  }
  else // bullet list
  {
    m_t << "\\(bu\" " << m_indent;
  }
  m_t << "\n";
  m_firstCol=TRUE;
  visitChildren(li);
  m_t << "\n";
  m_firstCol=TRUE;
}
References DocHtmlListItem::attribs(), QCString::fill(), integerToAlpha(), integerToRoman(), m_firstCol, m_hide, m_indent, m_t, man_listItemInfo, ManListItemInfo::number, DocHtmlList::Ordered, DocNode::parent(), TRUE, DocHtmlList::type(), testsqlite3::val, and visitChildren().
operator()() [40/114]
void ManDocVisitor::operator() (const DocHtmlListItem &)
operator()() [41/114]
void ManDocVisitor::operator() (const DocHtmlRow & r)
Definition at line 752 of file mandocvisitor.cpp.
{
  visitChildren(r);
}
References r, and visitChildren().
operator()() [42/114]
void ManDocVisitor::operator() (const DocHtmlRow &)
operator()() [43/114]
void ManDocVisitor::operator() (const DocHtmlSummary & s)
Definition at line 775 of file mandocvisitor.cpp.
{
  m_t << "\\fB";
  visitChildren(s);
  m_t << "\\fP\n.PP\n";
}
References m_t, s, and visitChildren().
operator()() [44/114]
void ManDocVisitor::operator() (const DocHtmlSummary &)
operator()() [45/114]
void ManDocVisitor::operator() (const DocHtmlTable & t)
Definition at line 742 of file mandocvisitor.cpp.
{
  visitChildren(t);
}
References visitChildren().
operator()() [46/114]
void ManDocVisitor::operator() (const DocHtmlTable & t)
operator()() [47/114]
void ManDocVisitor::operator() (const DocImage &)
Definition at line 819 of file mandocvisitor.cpp.
{
}
operator()() [48/114]
void ManDocVisitor::operator() (const DocImage &)
operator()() [49/114]
void ManDocVisitor::operator() (const DocInclude & inc)
Definition at line 256 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  SrcLangExt langExt = getLanguageFromFileName(inc.extension());
  switch(inc.type())
  {
    case DocInclude::IncWithLines:
      {
         if (!m_firstCol) m_t << "\n";
         m_t << ".PP\n";
         m_t << ".nf\n";
         FileInfo cfi(inc.file().str());
         FileDef *fd = createFileDef(cfi.dirPath(), cfi.fileName());
         getCodeParser(inc.extension()).parseCode(m_ci,inc.context(),
                                           inc.text(),
                                           langExt,
                                           inc.isExample(),
                                           inc.exampleFile(),
                                           fd, // fileDef,
                                           -1, // start line
                                           -1, // end line
                                           FALSE, // inline fragment
                                           0, // memberDef
                                           TRUE
                       );
         delete fd;
         if (!m_firstCol) m_t << "\n";
         m_t << ".fi\n";
         m_t << ".PP\n";
         m_firstCol=TRUE;
      }
      break;
    case DocInclude::Include:
      if (!m_firstCol) m_t << "\n";
      m_t << ".PP\n";
      m_t << ".nf\n";
      getCodeParser(inc.extension()).parseCode(m_ci,inc.context(),
                                        inc.text(),
                                        langExt,
                                        inc.isExample(),
                                        inc.exampleFile(),
                                        0, // fileDef
                                        -1, // startLine
                                        -1, // endLine
                                        TRUE, // inlineFragment
                                        0, // memberDef
                                        FALSE
                       );
      if (!m_firstCol) m_t << "\n";
      m_t << ".fi\n";
      m_t << ".PP\n";
      m_firstCol=TRUE;
      break;
    case DocInclude::DontInclude:
    case DocInclude::DontIncWithLines:
    case DocInclude::HtmlInclude:
    case DocInclude::LatexInclude:
    case DocInclude::RtfInclude:
    case DocInclude::XmlInclude:
    case DocInclude::DocbookInclude:
      break;
    case DocInclude::ManInclude:
      m_t << inc.text();
      break;
    case DocInclude::VerbInclude:
      if (!m_firstCol) m_t << "\n";
      m_t << ".PP\n";
      m_t << ".nf\n";
      m_t << inc.text();
      if (!m_firstCol) m_t << "\n";
      m_t << ".fi\n";
      m_t << ".PP\n";
      m_firstCol=TRUE;
      break;
    case DocInclude::Snippet:
      if (!m_firstCol) m_t << "\n";
      m_t << ".PP\n";
      m_t << ".nf\n";
      getCodeParser(inc.extension()).parseCode(m_ci,
                                        inc.context(),
                                        extractBlock(inc.text(),inc.blockId()),
                                        langExt,
                                        inc.isExample(),
                                        inc.exampleFile()
                                       );
      if (!m_firstCol) m_t << "\n";
      m_t << ".fi\n";
      m_t << ".PP\n";
      m_firstCol=TRUE;
      break;
    case DocInclude::SnipWithLines:
      {
         if (!m_firstCol) m_t << "\n";
         m_t << ".PP\n";
         m_t << ".nf\n";
         FileInfo cfi(inc.file().str());
         FileDef *fd = createFileDef(cfi.dirPath(), cfi.fileName());
         getCodeParser(inc.extension()).parseCode(m_ci,
                                           inc.context(),
                                           extractBlock(inc.text(),inc.blockId()),
                                           langExt,
                                           inc.isExample(),
                                           inc.exampleFile(),
                                           fd,
                                           lineBlock(inc.text(),inc.blockId()),
                                           -1, // endLine
                                           FALSE, // inlineFragment
                                           0, // memberDef
                                           TRUE // show line number
                                          );
         delete fd;
         if (!m_firstCol) m_t << "\n";
         m_t << ".fi\n";
         m_t << ".PP\n";
         m_firstCol=TRUE;
      }
      break;
    case DocInclude::SnippetDoc:
    case DocInclude::IncludeDoc:
      err("Internal inconsistency: found switch SnippetDoc / IncludeDoc in file: %s"
          "Please create a bug report\n",__FILE__);
      break;
  }
}
References DocInclude::blockId(), DocInclude::context(), createFileDef(), FileInfo::dirPath(), DocInclude::DocbookInclude, DocInclude::DontInclude, DocInclude::DontIncWithLines, err(), DocInclude::exampleFile(), DocInclude::extension(), extractBlock(), FALSE, DocInclude::file(), FileInfo::fileName(), DocVisitor::getCodeParser(), getLanguageFromFileName(), DocInclude::HtmlInclude, DocInclude::Include, DocInclude::IncludeDoc, DocInclude::IncWithLines, DocInclude::isExample(), DocInclude::LatexInclude, lineBlock(), m_ci, m_firstCol, m_hide, m_t, DocInclude::ManInclude, CodeParserInterface::parseCode(), DocInclude::RtfInclude, DocInclude::Snippet, DocInclude::SnippetDoc, DocInclude::SnipWithLines, QCString::str(), DocInclude::text(), TRUE, DocInclude::type(), DocInclude::VerbInclude, and DocInclude::XmlInclude.
operator()() [50/114]
void ManDocVisitor::operator() (const DocInclude &)
operator()() [51/114]
void ManDocVisitor::operator() (const DocIncOperator & op)
Definition at line 381 of file mandocvisitor.cpp.
{
  QCString locLangExt = getFileNameExtension(op.includeFileName());
  if (locLangExt.isEmpty()) locLangExt = m_langExt;
  SrcLangExt langExt = getLanguageFromFileName(locLangExt);
  //printf("DocIncOperator: type=%d first=%d, last=%d text='%s'\n",
  // op.type(),op.isFirst(),op.isLast(),qPrint(op.text()));
  if (op.isFirst())
  {
    if (!m_hide)
    {
      if (!m_firstCol) m_t << "\n";
      m_t << ".PP\n";
      m_t << ".nf\n";
    }
    pushHidden(m_hide);
    m_hide = TRUE;
  }
  if (op.type()!=DocIncOperator::Skip)
  {
    m_hide = popHidden();
    if (!m_hide)
    {
      FileDef *fd = 0;
      if (!op.includeFileName().isEmpty())
      {
        FileInfo cfi(op.includeFileName().str());
        fd = createFileDef(cfi.dirPath(), cfi.fileName());
      }
      getCodeParser(locLangExt).parseCode(m_ci,op.context(),op.text(),langExt,
                                        op.isExample(),op.exampleFile(),
                                        fd, // fileDef
                                        op.line(), // startLine
                                        -1, // endLine
                                        FALSE, // inline fragment
                                        0, // memberDef
                                        op.showLineNo() // show line numbers
                                       );
      if (fd) delete fd;
    }
    pushHidden(m_hide);
    m_hide=TRUE;
  }
  if (op.isLast())
  {
    m_hide = popHidden();
    if (!m_hide)
    {
      if (!m_firstCol) m_t << "\n";
      m_t << ".fi\n";
      m_t << ".PP\n";
      m_firstCol=TRUE;
    }
  }
  else
  {
    if (!m_hide) m_t << "\n";
  }
}
References DocIncOperator::context(), createFileDef(), FileInfo::dirPath(), DocIncOperator::exampleFile(), FALSE, FileInfo::fileName(), DocVisitor::getCodeParser(), getFileNameExtension(), getLanguageFromFileName(), DocIncOperator::includeFileName(), QCString::isEmpty(), DocIncOperator::isExample(), DocIncOperator::isFirst(), DocIncOperator::isLast(), DocIncOperator::line(), m_ci, m_firstCol, m_hide, m_langExt, m_t, CodeParserInterface::parseCode(), DocVisitor::popHidden(), DocVisitor::pushHidden(), DocIncOperator::showLineNo(), DocIncOperator::Skip, QCString::str(), DocIncOperator::text(), TRUE, and DocIncOperator::type().
operator()() [52/114]
void ManDocVisitor::operator() (const DocIncOperator &)
operator()() [53/114]
void ManDocVisitor::operator() (const DocIndexEntry &)
Definition at line 448 of file mandocvisitor.cpp.
{
}
operator()() [54/114]
void ManDocVisitor::operator() (const DocIndexEntry &)
operator()() [55/114]
void ManDocVisitor::operator() (const DocInternal & i)
Definition at line 762 of file mandocvisitor.cpp.
{
  visitChildren(i);
}
References visitChildren().
operator()() [56/114]
void ManDocVisitor::operator() (const DocInternal &)
operator()() [57/114]
void ManDocVisitor::operator() (const DocInternalRef & ref)
Definition at line 949 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "\\fB";
  visitChildren(ref);
  m_t << "\\fP";
}
References m_hide, m_t, and visitChildren().
operator()() [58/114]
void ManDocVisitor::operator() (const DocInternalRef &)
operator()() [59/114]
void ManDocVisitor::operator() (const DocLineBreak &)
Definition at line 113 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "\n.br\n";
  m_firstCol=TRUE;
}
References m_firstCol, m_hide, m_t, and TRUE.
operator()() [60/114]
void ManDocVisitor::operator() (const DocLineBreak &)
operator()() [61/114]
void ManDocVisitor::operator() (const DocLink & lnk)
Definition at line 835 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "\\fB";
  visitChildren(dl);
  m_t << "\\fP";
}
References m_hide, m_t, and visitChildren().
operator()() [62/114]
void ManDocVisitor::operator() (const DocLink & lnk)
operator()() [63/114]
void ManDocVisitor::operator() (const DocLinkedWord & w)
Definition at line 51 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "\\fB";
  filter(w.word());
  m_t << "\\fP";
  m_firstCol=FALSE;
}
References FALSE, filter(), m_firstCol, m_hide, m_t, and w.
operator()() [64/114]
void ManDocVisitor::operator() (const DocLinkedWord &)
operator()() [65/114]
void ManDocVisitor::operator() (const DocMscFile &)
Definition at line 827 of file mandocvisitor.cpp.
{
}
operator()() [66/114]
void ManDocVisitor::operator() (const DocMscFile &)
operator()() [67/114]
void ManDocVisitor::operator() (const DocPara & p)
Definition at line 509 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  visitChildren(p);
  if (!p.isLast() && // omit <p> for last paragraph
      !(p.parent() && // and for parameter sections
        std::get_if<DocParamSect>(p.parent())
       )
     )
  {
    if (!m_firstCol) m_t << "\n";
    m_t << ".PP\n";
    m_firstCol=TRUE;
  }
}
References m_firstCol, m_hide, m_t, p, TRUE, and visitChildren().
operator()() [68/114]
void ManDocVisitor::operator() (const DocPara &)
operator()() [69/114]
void ManDocVisitor::operator() (const DocParamList & pl)
Definition at line 906 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "\\fI";
  bool first=TRUE;
  for (const auto &param : pl.parameters())
  {
    if (!first) m_t << ","; else first=FALSE;
    std::visit(*this,param);
  }
  m_t << "\\fP ";
  for (const auto &par : pl.paragraphs())
  {
    std::visit(*this,par);
  }
  if (!pl.isLast())
  {
    if (!m_firstCol) m_t << "\n";
    m_t << ".br\n";
  }
}
References FALSE, DocParamList::isLast(), m_firstCol, m_hide, m_t, DocParamList::paragraphs(), DocParamList::parameters(), and TRUE.
operator()() [70/114]
void ManDocVisitor::operator() (const DocParamList &)
operator()() [71/114]
void ManDocVisitor::operator() (const DocParamSect & s)
Definition at line 875 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  if (!m_firstCol)
  {
    m_t << "\n";
    m_t << ".PP\n";
  }
  m_t << "\\fB";
  switch(s.type())
  {
    case DocParamSect::Param:
      m_t << theTranslator->trParameters(); break;
    case DocParamSect::RetVal:
      m_t << theTranslator->trReturnValues(); break;
    case DocParamSect::Exception:
      m_t << theTranslator->trExceptions(); break;
    case DocParamSect::TemplateParam:
      m_t << theTranslator->trTemplateParameters(); break;
    default:
      ASSERT(0);
  }
  m_t << "\\fP\n";
  m_t << ".RS 4\n";
  visitChildren(s);
  if (!m_firstCol) m_t << "\n";
  m_t << ".RE\n";
  m_t << ".PP\n";
  m_firstCol=TRUE;
}
References ASSERT, DocParamSect::Exception, m_firstCol, m_hide, m_t, DocParamSect::Param, DocParamSect::RetVal, s, DocParamSect::TemplateParam, theTranslator, Translator::trExceptions(), Translator::trParameters(), Translator::trReturnValues(), Translator::trTemplateParameters(), TRUE, and visitChildren().
operator()() [72/114]
void ManDocVisitor::operator() (const DocParamSect &)
operator()() [73/114]
void ManDocVisitor::operator() (const DocParBlock & pb)
Definition at line 982 of file mandocvisitor.cpp.
{
  visitChildren(pb);
}
References visitChildren().
operator()() [74/114]
void ManDocVisitor::operator() (const DocParBlock &)
operator()() [75/114]
void ManDocVisitor::operator() (const DocRef & ref)
Definition at line 843 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  m_t << "\\fB";
  if (!ref.hasLinkText()) filter(ref.targetTitle());
  visitChildren(ref);
  m_t << "\\fP";
}
References filter(), DocRef::hasLinkText(), m_hide, m_t, DocRef::targetTitle(), and visitChildren().
operator()() [76/114]
void ManDocVisitor::operator() (const DocRef & ref)
operator()() [77/114]
void ManDocVisitor::operator() (const DocRoot & r)
Definition at line 525 of file mandocvisitor.cpp.
{
  visitChildren(r);
}
References r, and visitChildren().
operator()() [78/114]
void ManDocVisitor::operator() (const DocRoot &)
operator()() [79/114]
void ManDocVisitor::operator() (const DocSecRefItem & ref)
Definition at line 852 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  QCString ws;
  ws.fill(' ',m_indent-2);
  if (!m_firstCol) m_t << "\n";
  m_t << ".IP \"" << ws << "\\(bu\" " << m_indent << "\n";
  m_firstCol=TRUE;
  visitChildren(ref);
  m_t << "\n";
  m_firstCol=TRUE;
}
References QCString::fill(), m_firstCol, m_hide, m_indent, m_t, TRUE, and visitChildren().
operator()() [80/114]
void ManDocVisitor::operator() (const DocSecRefItem &)
operator()() [81/114]
void ManDocVisitor::operator() (const DocSecRefList & l)
Definition at line 865 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  m_indent+=2;
  visitChildren(l);
  m_indent-=2;
  if (!m_firstCol) m_t << "\n";
  m_t << ".PP\n";
}
References m_firstCol, m_hide, m_indent, m_t, and visitChildren().
operator()() [82/114]
void ManDocVisitor::operator() (const DocSecRefList &)
operator()() [83/114]
void ManDocVisitor::operator() (const DocSection & s)
Definition at line 623 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  if (!m_firstCol) m_t << "\n";
  if (s.level()==1) m_t << ".SH"; else m_t << ".SS";
  m_t << " \"";
  filter(s.title());
  m_t << "\"\n";
  if (s.level()==1) m_t << ".PP\n";
  m_firstCol=TRUE;
  visitChildren(s);
}
References filter(), m_firstCol, m_hide, m_t, s, TRUE, and visitChildren().
operator()() [84/114]
void ManDocVisitor::operator() (const DocSection & s)
operator()() [85/114]
void ManDocVisitor::operator() (const DocSeparator & s)
Definition at line 466 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  m_t << s.chars();
}
References m_hide, m_t, and s.
operator()() [86/114]
void ManDocVisitor::operator() (const DocSeparator &)
operator()() [87/114]
void ManDocVisitor::operator() (const DocSimpleList & l)
Definition at line 596 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  m_indent+=2;
  if (!m_firstCol) m_t << "\n";
  m_t << ".PD 0\n";
  visitChildren(l);
  m_indent-=2;
  m_t << ".PP\n";
}
References m_firstCol, m_hide, m_indent, m_t, and visitChildren().
operator()() [88/114]
void ManDocVisitor::operator() (const DocSimpleList &)
operator()() [89/114]
void ManDocVisitor::operator() (const DocSimpleListItem & li)
Definition at line 607 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  QCString ws;
  ws.fill(' ',m_indent-2);
  if (!m_firstCol) m_t << "\n";
  m_t << ".IP \"" << ws << "\\(bu\" " << m_indent << "\n";
  m_firstCol=TRUE;
  if (li.paragraph())
  {
    visit(*this,*li.paragraph());
  }
  m_t << "\n";
  m_firstCol=TRUE;
}
References QCString::fill(), m_firstCol, m_hide, m_indent, m_t, DocSimpleListItem::paragraph(), and TRUE.
operator()() [90/114]
void ManDocVisitor::operator() (const DocSimpleListItem &)
operator()() [91/114]
void ManDocVisitor::operator() (const DocSimpleSect & s)
Definition at line 530 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  if (!m_firstCol)
  {
    m_t << "\n";
    m_t << ".PP\n";
  }
  m_t << "\\fB";
  switch(s.type())
  {
    case DocSimpleSect::See:
      m_t << theTranslator->trSeeAlso(); break;
    case DocSimpleSect::Return:
      m_t << theTranslator->trReturns(); break;
    case DocSimpleSect::Author:
      m_t << theTranslator->trAuthor(TRUE,TRUE); break;
    case DocSimpleSect::Authors:
      m_t << theTranslator->trAuthor(TRUE,FALSE); break;
    case DocSimpleSect::Version:
      m_t << theTranslator->trVersion(); break;
    case DocSimpleSect::Since:
      m_t << theTranslator->trSince(); break;
    case DocSimpleSect::Date:
      m_t << theTranslator->trDate(); break;
    case DocSimpleSect::Note:
      m_t << theTranslator->trNote(); break;
    case DocSimpleSect::Warning:
      m_t << theTranslator->trWarning(); break;
    case DocSimpleSect::Pre:
      m_t << theTranslator->trPrecondition(); break;
    case DocSimpleSect::Post:
      m_t << theTranslator->trPostcondition(); break;
    case DocSimpleSect::Copyright:
      m_t << theTranslator->trCopyright(); break;
    case DocSimpleSect::Invar:
      m_t << theTranslator->trInvariant(); break;
    case DocSimpleSect::Remark:
      m_t << theTranslator->trRemarks(); break;
    case DocSimpleSect::Attention:
      m_t << theTranslator->trAttention(); break;
    case DocSimpleSect::User: break;
    case DocSimpleSect::Rcs: break;
    case DocSimpleSect::Unknown: break;
  }
  // special case 1: user defined title
  if (s.title())
  {
    std::visit(*this,*s.title());
  }
  m_t << "\\fP\n";
  m_t << ".RS 4\n";
  visitChildren(s);
  if (!m_firstCol) m_t << "\n";
  m_t << ".RE\n";
  m_t << ".PP\n";
  m_firstCol=TRUE;
}
References DocSimpleSect::Attention, DocSimpleSect::Author, DocSimpleSect::Authors, DocSimpleSect::Copyright, DocSimpleSect::Date, FALSE, DocSimpleSect::Invar, m_firstCol, m_hide, m_t, DocSimpleSect::Note, DocSimpleSect::Post, DocSimpleSect::Pre, DocSimpleSect::Rcs, DocSimpleSect::Remark, DocSimpleSect::Return, s, DocSimpleSect::See, DocSimpleSect::Since, theTranslator, Translator::trAttention(), Translator::trAuthor(), Translator::trCopyright(), Translator::trDate(), Translator::trInvariant(), Translator::trNote(), Translator::trPostcondition(), Translator::trPrecondition(), Translator::trRemarks(), Translator::trReturns(), Translator::trSeeAlso(), Translator::trSince(), TRUE, Translator::trVersion(), Translator::trWarning(), DocSimpleSect::Unknown, DocSimpleSect::User, DocSimpleSect::Version, visitChildren(), and DocSimpleSect::Warning.
operator()() [92/114]
void ManDocVisitor::operator() (const DocSimpleSect &)
operator()() [93/114]
void ManDocVisitor::operator() (const DocSimpleSectSep &)
Definition at line 452 of file mandocvisitor.cpp.
{
}
operator()() [94/114]
void ManDocVisitor::operator() (const DocSimpleSectSep &)
operator()() [95/114]
void ManDocVisitor::operator() (const DocStyleChange & s)
Definition at line 128 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  switch (s.style())
  {
    case DocStyleChange::Bold:
      if (s.enable()) m_t << "\\fB"; else m_t << "\\fP";
      m_firstCol=FALSE;
      break;
    case DocStyleChange::S:
    case DocStyleChange::Strike:
    case DocStyleChange::Del:
      /* not supported */
      break;
    case DocStyleChange::Underline: //underline is shown as emphasis
    case DocStyleChange::Ins:
      if (s.enable()) m_t << "\\fI"; else m_t << "\\fP";
      m_firstCol=FALSE;
      break;
    case DocStyleChange::Italic:
      if (s.enable()) m_t << "\\fI"; else m_t << "\\fP";
      m_firstCol=FALSE;
      break;
    case DocStyleChange::Code:
      if (s.enable()) m_t << "\\fC"; else m_t << "\\fP";
      m_firstCol=FALSE;
      break;
    case DocStyleChange::Subscript:
      if (s.enable()) m_t << "\\*<"; else m_t << "\\*> ";
      m_firstCol=FALSE;
      break;
    case DocStyleChange::Superscript:
      if (s.enable()) m_t << "\\*{"; else m_t << "\\*} ";
      m_firstCol=FALSE;
      break;
    case DocStyleChange::Center:
      /* not supported */
      break;
    case DocStyleChange::Small:
      /* not supported */
      break;
    case DocStyleChange::Cite:
      /* not supported */
      break;
    case DocStyleChange::Preformatted:
      if (s.enable())
      {
        if (!m_firstCol) m_t << "\n";
        m_t << ".PP\n";
        m_t << ".nf\n";
        m_insidePre=TRUE;
      }
      else
      {
        m_insidePre=FALSE;
        if (!m_firstCol) m_t << "\n";
        m_t << ".fi\n";
        m_t << ".PP\n";
        m_firstCol=TRUE;
      }
      break;
    case DocStyleChange::Div: /* HTML only */ break;
    case DocStyleChange::Span: /* HTML only */ break;
  }
}
References DocStyleChange::Bold, DocStyleChange::Center, DocStyleChange::Cite, DocStyleChange::Code, DocStyleChange::Del, DocStyleChange::Div, FALSE, DocStyleChange::Ins, DocStyleChange::Italic, m_firstCol, m_hide, m_insidePre, m_t, DocStyleChange::Preformatted, s, DocStyleChange::S, DocStyleChange::Small, DocStyleChange::Span, DocStyleChange::Strike, DocStyleChange::Subscript, DocStyleChange::Superscript, TRUE, and DocStyleChange::Underline.
operator()() [96/114]
void ManDocVisitor::operator() (const DocStyleChange &)
operator()() [97/114]
void ManDocVisitor::operator() (const DocSymbol & s)
Definition at line 75 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  const char *res = HtmlEntityMapper::instance()->man(s.symbol());
  if (res)
  {
    m_t << res;
  }
  else
  {
    // no error or warning to be supplied
    // err("man: non supported HTML-entity found: &%s;\n",get_symbol_item(s->symbol()));
  }
  m_firstCol=FALSE;
}
References FALSE, HtmlEntityMapper::instance(), m_firstCol, m_hide, m_t, HtmlEntityMapper::man(), and s.
operator()() [98/114]
void ManDocVisitor::operator() (const DocSymbol &)
operator()() [99/114]
void ManDocVisitor::operator() (const DocText & t)
Definition at line 957 of file mandocvisitor.cpp.
{
  visitChildren(t);
}
References visitChildren().
operator()() [100/114]
void ManDocVisitor::operator() (const DocText &)
operator()() [101/114]
void ManDocVisitor::operator() (const DocTitle & t)
Definition at line 590 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  visitChildren(t);
}
References m_hide, and visitChildren().
operator()() [102/114]
void ManDocVisitor::operator() (const DocTitle &)
operator()() [103/114]
void ManDocVisitor::operator() (const DocURL & u)
Definition at line 106 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  m_t << u.url();
  m_firstCol=FALSE;
}
References FALSE, m_firstCol, m_hide, m_t, and DocURL::url().
operator()() [104/114]
void ManDocVisitor::operator() (const DocURL &)
operator()() [105/114]
void ManDocVisitor::operator() (const DocVerbatim & s)
Definition at line 194 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  QCString lang = m_langExt;
  if (!s.language().isEmpty()) // explicit language setting
  {
    lang = s.language();
  }
  SrcLangExt langExt = getLanguageFromCodeLang(lang);
  switch (s.type())
  {
    case DocVerbatim::Code:
      if (!m_firstCol) m_t << "\n";
      m_t << ".PP\n";
      m_t << ".nf\n";
      getCodeParser(lang).parseCode(m_ci,s.context(),s.text(),
                                        langExt,
                                        s.isExample(),s.exampleFile());
      if (!m_firstCol) m_t << "\n";
      m_t << ".fi\n";
      m_t << ".PP\n";
      m_firstCol=TRUE;
      break;
    case DocVerbatim::JavaDocLiteral:
      filter(s.text());
      break;
    case DocVerbatim::JavaDocCode:
      m_t << "\\fC\n";
      filter(s.text());
      m_t << "\\fP\n";
      break;
    case DocVerbatim::Verbatim:
      if (!m_firstCol) m_t << "\n";
      m_t << ".PP\n";
      m_t << ".nf\n";
      filter(s.text());
      if (!m_firstCol) m_t << "\n";
      m_t << ".fi\n";
      m_t << ".PP\n";
      m_firstCol=TRUE;
      break;
    case DocVerbatim::ManOnly:
      m_t << s.text();
      break;
    case DocVerbatim::HtmlOnly:
    case DocVerbatim::XmlOnly:
    case DocVerbatim::LatexOnly:
    case DocVerbatim::RtfOnly:
    case DocVerbatim::DocbookOnly:
    case DocVerbatim::Dot:
    case DocVerbatim::Msc:
    case DocVerbatim::PlantUML:
      /* nothing */
      break;
  }
}
References DocVerbatim::Code, DocVerbatim::DocbookOnly, DocVerbatim::Dot, filter(), DocVisitor::getCodeParser(), getLanguageFromCodeLang(), DocVerbatim::HtmlOnly, DocVerbatim::JavaDocCode, DocVerbatim::JavaDocLiteral, DocVerbatim::LatexOnly, m_ci, m_firstCol, m_hide, m_langExt, m_t, DocVerbatim::ManOnly, DocVerbatim::Msc, CodeParserInterface::parseCode(), DocVerbatim::PlantUML, DocVerbatim::RtfOnly, s, TRUE, DocVerbatim::Verbatim, and DocVerbatim::XmlOnly.
operator()() [106/114]
void ManDocVisitor::operator() (const DocVerbatim &)
operator()() [107/114]
void ManDocVisitor::operator() (const DocVhdlFlow &)
Definition at line 978 of file mandocvisitor.cpp.
{
}
operator()() [108/114]
void ManDocVisitor::operator() (const DocVhdlFlow &)
operator()() [109/114]
void ManDocVisitor::operator() (const DocWhiteSpace & w)
Definition at line 60 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  if (m_insidePre)
  {
    m_t << w.chars();
    m_firstCol=w.chars().at(w.chars().length()-1)=='\n';
  }
  else
  {
    m_t << " ";
    m_firstCol=FALSE;
  }
}
References FALSE, m_firstCol, m_hide, m_insidePre, m_t, and w.
operator()() [110/114]
void ManDocVisitor::operator() (const DocWhiteSpace &)
operator()() [111/114]
void ManDocVisitor::operator() (const DocWord & w)
Definition at line 44 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  filter(w.word());
  m_firstCol=FALSE;
}
References FALSE, filter(), m_firstCol, m_hide, and w.
operator()() [112/114]
void ManDocVisitor::operator() (const DocWord &)
operator()() [113/114]
void ManDocVisitor::operator() (const DocXRefItem & x)
Definition at line 928 of file mandocvisitor.cpp.
{
  if (m_hide) return;
  if (x.title().isEmpty()) return;
  if (!m_firstCol)
  {
    m_t << "\n";
    m_t << ".PP\n";
  }
  m_t << "\\fB";
  filter(x.title());
  m_t << "\\fP\n";
  m_t << ".RS 4\n";
  visitChildren(x);
  if (x.title().isEmpty()) return;
  if (!m_firstCol) m_t << "\n";
  m_t << ".RE\n";
  m_t << ".PP\n";
  m_firstCol=TRUE;
}
References filter(), m_firstCol, m_hide, m_t, TRUE, visitChildren(), and x.
operator()() [114/114]
void ManDocVisitor::operator() (const DocXRefItem &)
visitChildren() [1/2]
template<class T >
void ManDocVisitor::visitChildren (const T & t) [inline], [private]
Definition at line 106 of file mandocvisitor.h.
    {
      for (const auto &child : t.children())
      {
        std::visit(*this, child);
      }
    }
Referenced by operator()().
visitChildren() [2/2]
template<class T >
void ManDocVisitor::visitChildren (const T & t) [inline], [private]
Definition at line 106 of file mandocvisitor.h.
    {
      for (const auto &child : t.children())
      {
        std::visit(*this, child);
      }
    }
Member Data Documentation
m_ci
CodeOutputInterface & ManDocVisitor::m_ci [private]
Definition at line 125 of file mandocvisitor.h.
Referenced by operator()().
m_firstCol
bool ManDocVisitor::m_firstCol [private]
Definition at line 128 of file mandocvisitor.h.
Referenced by operator()().
m_hide
bool ManDocVisitor::m_hide [private]
Definition at line 127 of file mandocvisitor.h.
Referenced by operator()().
m_indent
int ManDocVisitor::m_indent [private]
Definition at line 129 of file mandocvisitor.h.
Referenced by operator()().
m_insidePre
bool ManDocVisitor::m_insidePre [private]
Definition at line 126 of file mandocvisitor.h.
Referenced by operator()().
m_langExt
QCString ManDocVisitor::m_langExt [private]
Definition at line 130 of file mandocvisitor.h.
Referenced by operator()().
m_t
TextStream & ManDocVisitor::m_t [private]
Definition at line 124 of file mandocvisitor.h.
Referenced by filter(), and operator()().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/mandocvisitor.h
doxygen/src/mandocvisitor.h
doxygen/build/doxygen/src/mandocvisitor.cpp
doxygen/src/mandocvisitor.cpp