FileNameFn Class Reference
#include <filename.h>
Public Member Functions
std::size_t operator() (const std::string &input) const noexcept
used as hash function
bool operator() (const std::string &t1, const std::string &t2) const
used as equal operator
std::size_t operator() (const std::string &input) const noexcept
used as hash function
bool operator() (const std::string &t1, const std::string &t2) const
used as equal operator
Private Member Functions
std::string searchKey (std::string input) const
std::string searchKey (std::string input) const
Detailed Description
Custom combined key compare and hash functor that uses a lower case string in case CASE_SENSE_NAMES is set to NO.
Definition at line 45 of file filename.h.
Member Function Documentation
operator()() [1/4]
std::size_t FileNameFn::operator() (const std::string & input) const [inline], [noexcept]
used as hash function
Definition at line 49 of file filename.h.
    {
      return std::hash<std::string>()(searchKey(input));
    }
References searchKey().
operator()() [2/4]
std::size_t FileNameFn::operator() (const std::string & input) const [inline], [noexcept]
used as hash function
Definition at line 49 of file filename.h.
    {
      return std::hash<std::string>()(searchKey(input));
    }
References searchKey().
operator()() [3/4]
bool FileNameFn::operator() (const std::string & t1, const std::string & t2) const [inline]
used as equal operator
Definition at line 54 of file filename.h.
    {
      return searchKey(t1) == searchKey(t2);
    }
References searchKey().
operator()() [4/4]
bool FileNameFn::operator() (const std::string & t1, const std::string & t2) const [inline]
used as equal operator
Definition at line 54 of file filename.h.
    {
      return searchKey(t1) == searchKey(t2);
    }
References searchKey().
searchKey() [1/2]
std::string FileNameFn::searchKey (std::string input) const [inline], [private]
Definition at line 59 of file filename.h.
    {
      std::string key = input;
      if (!getCaseSenseNames())
      {
        key = convertUTF8ToLower(key);
      }
      return key;
    }
References convertUTF8ToLower(), getCaseSenseNames(), and string.
Referenced by operator()().
searchKey() [2/2]
std::string FileNameFn::searchKey (std::string input) const [inline], [private]
Definition at line 59 of file filename.h.
    {
      std::string key = input;
      if (!getCaseSenseNames())
      {
        key = convertUTF8ToLower(key);
      }
      return key;
    }
References convertUTF8ToLower(), getCaseSenseNames(), and string.
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/filename.h
doxygen/src/filename.h