TemplateVariant Class Reference
Variant type which can hold one value of a fixed set of types.
#include <template.h>
Public Types
enum class Type : uint8_t {
None = 0
, Bool = 1
, Int = 2
, String = 3
,
Struct = 4
, List = 5
, Function = 6
, WeakStruct = 7
,
None = 0
, Bool = 1
, Int = 2
, String = 3
,
Struct = 4
, List = 5
, Function = 6
, WeakStruct = 7
 }
enum class Type : uint8_t {
None = 0
, Bool = 1
, Int = 2
, String = 3
,
Struct = 4
, List = 5
, Function = 6
, WeakStruct = 7
,
None = 0
, Bool = 1
, Int = 2
, String = 3
,
Struct = 4
, List = 5
, Function = 6
, WeakStruct = 7
 }
using FunctionDelegate = std::function< TemplateVariant(const std::vector< TemplateVariant > &)>
using VariantT = std::variant< std::monostate, bool, int, QCString, TemplateStructIntfPtr, TemplateListIntfPtr, FunctionDelegate, TemplateStructIntfWeakPtr >
using FunctionDelegate = std::function< TemplateVariant(const std::vector< TemplateVariant > &)>
using VariantT = std::variant< std::monostate, bool, int, QCString, TemplateStructIntfPtr, TemplateListIntfPtr, FunctionDelegate, TemplateStructIntfWeakPtr >
Public Member Functions
TemplateVariant ()
TemplateVariant (bool b)
TemplateVariant (int v)
TemplateVariant (unsigned int v)
template<typename T , typename std::enable_if< std::is_same< T, size_t >::value, T >::type * = nullptr>
TemplateVariant (T v)
TemplateVariant (const char *s, bool raw=FALSE)
TemplateVariant (const QCString &s, bool raw=FALSE)
TemplateVariant (const std::string &s, bool raw=FALSE)
TemplateVariant (TemplateStructIntfPtr s)
TemplateVariant (TemplateListIntfPtr l)
TemplateVariant (TemplateStructIntfWeakPtr s)
TemplateVariant (FunctionDelegate delegate)
~TemplateVariant ()=default
TemplateVariant (const TemplateVariant &v)=default
TemplateVariant (TemplateVariant &&v)
TemplateVariant & operator= (const TemplateVariant &v)=default
TemplateVariant & operator= (TemplateVariant &&v)
bool operator== (TemplateVariant &other) const
QCString toString () const
bool toBool () const
int toInt () const
constexpr bool isValid () const
constexpr bool isBool () const
constexpr bool isInt () const
constexpr bool isString () const
constexpr bool isStruct () const
constexpr bool isList () const
constexpr bool isFunction () const
constexpr bool isWeakStruct () const
TemplateListIntfPtr toList ()
const TemplateListIntfPtr toList () const
TemplateStructIntfPtr toStruct ()
const TemplateStructIntfPtr toStruct () const
TemplateVariant call (const std::vector< TemplateVariant > &args=std::vector< TemplateVariant >())
void setRaw (bool b)
constexpr bool raw () const
constexpr Type type () const
const char * typeAsString () const
TemplateVariant ()
TemplateVariant (bool b)
TemplateVariant (int v)
TemplateVariant (unsigned int v)
template<typename T , typename std::enable_if< std::is_same< T, size_t >::value, T >::type * = nullptr>
TemplateVariant (T v)
TemplateVariant (const char *s, bool raw=FALSE)
TemplateVariant (const QCString &s, bool raw=FALSE)
TemplateVariant (const std::string &s, bool raw=FALSE)
TemplateVariant (TemplateStructIntfPtr s)
TemplateVariant (TemplateListIntfPtr l)
TemplateVariant (TemplateStructIntfWeakPtr s)
TemplateVariant (FunctionDelegate delegate)
~TemplateVariant ()=default
TemplateVariant (const TemplateVariant &v)=default
TemplateVariant (TemplateVariant &&v)
TemplateVariant & operator= (const TemplateVariant &v)=default
TemplateVariant & operator= (TemplateVariant &&v)
bool operator== (TemplateVariant &other) const
QCString toString () const
bool toBool () const
int toInt () const
constexpr bool isValid () const
constexpr bool isBool () const
constexpr bool isInt () const
constexpr bool isString () const
constexpr bool isStruct () const
constexpr bool isList () const
constexpr bool isFunction () const
constexpr bool isWeakStruct () const
TemplateListIntfPtr toList ()
const TemplateListIntfPtr toList () const
TemplateStructIntfPtr toStruct ()
const TemplateStructIntfPtr toStruct () const
TemplateVariant call (const std::vector< TemplateVariant > &args=std::vector< TemplateVariant >())
void setRaw (bool b)
constexpr bool raw () const
constexpr Type type () const
const char * typeAsString () const
Private Member Functions
QCString listToString () const
QCString structToString () const
QCString listToString () const
QCString structToString () const
Private Attributes
VariantT m_variant
bool m_raw = false
Detailed Description
Variant type which can hold one value of a fixed set of types.
Definition at line 98 of file template.h.
Member Typedef Documentation
FunctionDelegate [1/2]
using TemplateVariant::FunctionDelegate = std::function<TemplateVariant(const std::vector<TemplateVariant>&)>
Type representing a function call in a template
Definition at line 102 of file template.h.
FunctionDelegate [2/2]
using TemplateVariant::FunctionDelegate = std::function<TemplateVariant(const std::vector<TemplateVariant>&)>
Type representing a function call in a template
Definition at line 102 of file template.h.
VariantT [1/2]
using TemplateVariant::VariantT = std::variant<std::monostate, bool, int, QCString, TemplateStructIntfPtr, TemplateListIntfPtr, FunctionDelegate, TemplateStructIntfWeakPtr >
Symbolic names for the possible types that this variant can hold.
Definition at line 105 of file template.h.
VariantT [2/2]
using TemplateVariant::VariantT = std::variant<std::monostate, bool, int, QCString, TemplateStructIntfPtr, TemplateListIntfPtr, FunctionDelegate, TemplateStructIntfWeakPtr >
Symbolic names for the possible types that this variant can hold.
Definition at line 105 of file template.h.
Member Enumeration Documentation
Type [1/2]
enum class TemplateVariant::Type : uint8_t [strong]
Enumerator
None
Bool
Int
String
Struct
List
Function
WeakStruct
None
Bool
Int
String
Struct
List
Function
WeakStruct
Definition at line 115 of file template.h.
    {
      None = 0,
      Bool = 1,
      Int = 2,
      String = 3,
      Struct = 4,
      List = 5,
      Function = 6,
      WeakStruct = 7
    };
Type [2/2]
enum class TemplateVariant::Type : uint8_t [strong]
Enumerator
None
Bool
Int
String
Struct
List
Function
WeakStruct
None
Bool
Int
String
Struct
List
Function
WeakStruct
Definition at line 115 of file template.h.
    {
      None = 0,
      Bool = 1,
      Int = 2,
      String = 3,
      Struct = 4,
      List = 5,
      Function = 6,
      WeakStruct = 7
    };
Constructor & Destructor Documentation
TemplateVariant() [1/28]
TemplateVariant::TemplateVariant () [inline]
Constructs an invalid variant.
Definition at line 128 of file template.h.
{}
Referenced by call().
TemplateVariant() [2/28]
TemplateVariant::TemplateVariant (bool b) [inline], [explicit]
Constructs a new variant with a boolean value b.
Definition at line 131 of file template.h.
{ m_variant = b; }
References b, and m_variant.
TemplateVariant() [3/28]
TemplateVariant::TemplateVariant (int v) [inline]
Constructs a new variant with a integer value v.
Definition at line 134 of file template.h.
{ m_variant = v; }
References m_variant.
TemplateVariant() [4/28]
TemplateVariant::TemplateVariant (unsigned int v) [inline]
Constructs a new variant with a integer value v.
Definition at line 137 of file template.h.
{ m_variant = static_cast<int>(v); }
References m_variant.
TemplateVariant() [5/28]
template<typename T , typename std::enable_if< std::is_same< T, size_t >::value, T >::type * = nullptr>
TemplateVariant::TemplateVariant (T v) [inline]
Constructs a new variant with a integer value v. We use SFINAE to avoid a compiler error in case size_t already matches the 'unsigned int' overload.
Definition at line 145 of file template.h.
{ m_variant = static_cast<int>(v); }
References m_variant.
TemplateVariant() [6/28]
TemplateVariant::TemplateVariant (const char * s, bool raw = FALSE) [inline]
Constructs a new variant with a string value s.
Definition at line 148 of file template.h.
: m_raw(raw) { m_variant = QCString(s); }
References m_variant, and s.
TemplateVariant() [7/28]
TemplateVariant::TemplateVariant (const QCString & s, bool raw = FALSE) [inline]
Constructs a new variant with a string value s.
Definition at line 151 of file template.h.
: m_raw(raw) { m_variant = s; }
References m_variant, and s.
TemplateVariant() [8/28]
TemplateVariant::TemplateVariant (const std::string & s, bool raw = FALSE) [inline]
Constructs a new variant with a string value s.
Definition at line 154 of file template.h.
: m_raw(raw) { m_variant = QCString(s); }
References m_variant, and s.
TemplateVariant() [9/28]
TemplateVariant::TemplateVariant (TemplateStructIntfPtr s) [inline]
Constructs a new variant with a struct value s.
Note
. The variant will hold a counting reference to the object.
Definition at line 159 of file template.h.
{ m_variant = s; }
References m_variant, and s.
TemplateVariant() [10/28]
TemplateVariant::TemplateVariant (TemplateListIntfPtr l) [inline]
Constructs a new variant with a list value l.
Note
. The variant will hold a counting reference to the object.
Definition at line 164 of file template.h.
{ m_variant = l; }
References m_variant.
TemplateVariant() [11/28]
TemplateVariant::TemplateVariant (TemplateStructIntfWeakPtr s) [inline]
Constructs a new variant with a struct value s.
Note
. The variant will hold a non-counting reference to the object.
Definition at line 169 of file template.h.
{ m_variant = s; }
References m_variant, and s.
TemplateVariant() [12/28]
TemplateVariant::TemplateVariant (FunctionDelegate delegate) [inline]
Constructs a new variant which represents a method call
Parameters
 in delegate FunctionDelegate object to invoke when calling call() on this variant.
Note
Use TemplateVariant::FunctionDelegate::fromMethod() and TemplateVariant::FunctionDelegate::fromFunction() to create FunctionDelegate objects.
Definition at line 178 of file template.h.
{ m_variant = delegate; }
References m_variant.
 TemplateVariant() [1/2]
TemplateVariant::~TemplateVariant () [default]
Destroys the Variant object
TemplateVariant() [13/28]
TemplateVariant::TemplateVariant (const TemplateVariant & v) [default]
Constructs a copy of the variant, v, passed as the argument to this constructor.
TemplateVariant() [14/28]
TemplateVariant::TemplateVariant (TemplateVariant && v)
Moves the contents of variant v into this variant. variant v will become invalid
Definition at line 326 of file template.cpp.
{
  m_raw = std::move(v.m_raw);
  m_variant = std::move(v.m_variant);
  v.m_variant = VariantT();
}
References m_raw, and m_variant.
TemplateVariant() [15/28]
TemplateVariant::TemplateVariant () [inline]
Constructs an invalid variant.
Definition at line 128 of file template.h.
{}
TemplateVariant() [16/28]
TemplateVariant::TemplateVariant (bool b) [inline], [explicit]
Constructs a new variant with a boolean value b.
Definition at line 131 of file template.h.
{ m_variant = b; }
References b, and m_variant.
TemplateVariant() [17/28]
TemplateVariant::TemplateVariant (int v) [inline]
Constructs a new variant with a integer value v.
Definition at line 134 of file template.h.
{ m_variant = v; }
References m_variant.
TemplateVariant() [18/28]
TemplateVariant::TemplateVariant (unsigned int v) [inline]
Constructs a new variant with a integer value v.
Definition at line 137 of file template.h.
{ m_variant = static_cast<int>(v); }
References m_variant.
TemplateVariant() [19/28]
template<typename T , typename std::enable_if< std::is_same< T, size_t >::value, T >::type * = nullptr>
TemplateVariant::TemplateVariant (T v) [inline]
Constructs a new variant with a integer value v. We use SFINAE to avoid a compiler error in case size_t already matches the 'unsigned int' overload.
Definition at line 145 of file template.h.
{ m_variant = static_cast<int>(v); }
References m_variant.
TemplateVariant() [20/28]
TemplateVariant::TemplateVariant (const char * s, bool raw = FALSE) [inline]
Constructs a new variant with a string value s.
Definition at line 148 of file template.h.
: m_raw(raw) { m_variant = QCString(s); }
References m_variant, and s.
TemplateVariant() [21/28]
TemplateVariant::TemplateVariant (const QCString & s, bool raw = FALSE) [inline]
Constructs a new variant with a string value s.
Definition at line 151 of file template.h.
: m_raw(raw) { m_variant = s; }
References m_variant, and s.
TemplateVariant() [22/28]
TemplateVariant::TemplateVariant (const std::string & s, bool raw = FALSE) [inline]
Constructs a new variant with a string value s.
Definition at line 154 of file template.h.
: m_raw(raw) { m_variant = QCString(s); }
References m_variant, and s.
TemplateVariant() [23/28]
TemplateVariant::TemplateVariant (TemplateStructIntfPtr s) [inline]
Constructs a new variant with a struct value s.
Note
. The variant will hold a counting reference to the object.
Definition at line 159 of file template.h.
{ m_variant = s; }
References m_variant, and s.
TemplateVariant() [24/28]
TemplateVariant::TemplateVariant (TemplateListIntfPtr l) [inline]
Constructs a new variant with a list value l.
Note
. The variant will hold a counting reference to the object.
Definition at line 164 of file template.h.
{ m_variant = l; }
References m_variant.
TemplateVariant() [25/28]
TemplateVariant::TemplateVariant (TemplateStructIntfWeakPtr s) [inline]
Constructs a new variant with a struct value s.
Note
. The variant will hold a non-counting reference to the object.
Definition at line 169 of file template.h.
{ m_variant = s; }
References m_variant, and s.
TemplateVariant() [26/28]
TemplateVariant::TemplateVariant (FunctionDelegate delegate) [inline]
Constructs a new variant which represents a method call
Parameters
 in delegate FunctionDelegate object to invoke when calling call() on this variant.
Note
Use TemplateVariant::FunctionDelegate::fromMethod() and TemplateVariant::FunctionDelegate::fromFunction() to create FunctionDelegate objects.
Definition at line 178 of file template.h.
{ m_variant = delegate; }
References m_variant.
 TemplateVariant() [2/2]
TemplateVariant::~TemplateVariant () [default]
Destroys the Variant object
TemplateVariant() [27/28]
TemplateVariant::TemplateVariant (const TemplateVariant & v) [default]
Constructs a copy of the variant, v, passed as the argument to this constructor.
TemplateVariant() [28/28]
TemplateVariant::TemplateVariant (TemplateVariant && v)
Moves the contents of variant v into this variant. variant v will become invalid
Member Function Documentation
call() [1/2]
TemplateVariant TemplateVariant::call (const std::vector< TemplateVariant > & args = std::vector<TemplateVariant>())
Return the result of apply this function with args. Returns an empty string if the variant type is not a function.
Definition at line 453 of file template.cpp.
{
  return isFunction() ? std::get<FunctionDelegate>(m_variant)(args) : TemplateVariant();
}
References isFunction(), m_variant, and TemplateVariant().
Referenced by TemplateNodeVariable::render(), TemplateNodeFor::render(), TemplateNodeCycle::render(), and ExprAstFunctionVariable::resolve().
call() [2/2]
TemplateVariant TemplateVariant::call (const std::vector< TemplateVariant > & args = std::vector< TemplateVariant >())
Return the result of apply this function with args. Returns an empty string if the variant type is not a function.
isBool() [1/2]
constexpr bool TemplateVariant::isBool () const [inline], [constexpr]
Returns TRUE if the variant holds a boolean value
Definition at line 217 of file template.h.
{ return std::holds_alternative<bool>(m_variant); }
References m_variant.
Referenced by operator==().
isBool() [2/2]
constexpr bool TemplateVariant::isBool () const [inline], [constexpr]
Returns TRUE if the variant holds a boolean value
Definition at line 217 of file template.h.
{ return std::holds_alternative<bool>(m_variant); }
References m_variant.
isFunction() [1/2]
constexpr bool TemplateVariant::isFunction () const [inline], [constexpr]
Returns TRUE if the variant holds a function value
Definition at line 227 of file template.h.
{ return std::holds_alternative<FunctionDelegate>(m_variant); }
References m_variant.
Referenced by call(), MemberContext::Private::isFunction(), TemplateNodeVariable::render(), TemplateNodeFor::render(), TemplateNodeCycle::render(), and ExprAstFunctionVariable::resolve().
isFunction() [2/2]
constexpr bool TemplateVariant::isFunction () const [inline], [constexpr]
Returns TRUE if the variant holds a function value
Definition at line 227 of file template.h.
{ return std::holds_alternative<FunctionDelegate>(m_variant); }
References m_variant.
isInt() [1/2]
constexpr bool TemplateVariant::isInt () const [inline], [constexpr]
Returns TRUE if the variant holds an integer value
Definition at line 219 of file template.h.
{ return std::holds_alternative<int>(m_variant); }
References m_variant.
Referenced by FilterRaw::apply(), FilterAppend::apply(), FilterPrepend::apply(), FilterPaginate::apply(), FilterDivisibleBy::apply(), operator==(), TemplateNodeRange::render(), and FilterAdd::variantIntValue().
isInt() [2/2]
constexpr bool TemplateVariant::isInt () const [inline], [constexpr]
Returns TRUE if the variant holds an integer value
Definition at line 219 of file template.h.
{ return std::holds_alternative<int>(m_variant); }
References m_variant.
isList() [1/2]
constexpr bool TemplateVariant::isList () const [inline], [constexpr]
Returns TRUE if the variant holds a list value
Definition at line 225 of file template.h.
{ return std::holds_alternative<TemplateListIntfPtr>(m_variant); }
References m_variant.
Referenced by FilterList::apply(), FilterLength::apply(), FilterFlatten::apply(), FilterKeep::apply(), FilterListSort::apply(), FilterGroupBy::apply(), FilterPaginate::apply(), FilterAlphaIndex::apply(), FilterFlatten::flatten(), TemplateContextImpl::get(), operator==(), and toList().
isList() [2/2]
constexpr bool TemplateVariant::isList () const [inline], [constexpr]
Returns TRUE if the variant holds a list value
Definition at line 225 of file template.h.
{ return std::holds_alternative<TemplateListIntfPtr>(m_variant); }
References m_variant.
isString() [1/2]
constexpr bool TemplateVariant::isString () const [inline], [constexpr]
Returns TRUE if the variant holds a string value
Definition at line 221 of file template.h.
{ return std::holds_alternative<QCString>(m_variant); }
References m_variant.
Referenced by FilterRaw::apply(), FilterTexLabel::apply(), FilterTexIndex::apply(), FilterLength::apply(), FilterRelative::apply(), FilterStripPath::apply(), FilterNoWrap::apply(), FilterIsRelativeURL::apply(), FilterIsAbsoluteURL::apply(), FilterLower::apply(), FilterUpper::apply(), FilterEscape::apply(), FilterDecodeURL::apply(), FilterAdd::apply(), FilterGet::apply(), FilterAppend::apply(), FilterPrepend::apply(), FilterDefault::apply(), FilterKeep::apply(), FilterListSort::apply(), FilterGroupBy::apply(), FilterAlphaIndex::apply(), TemplateNodeMarkers::render(), ExprAstBinary::resolve(), and FilterAdd::variantIntValue().
isString() [2/2]
constexpr bool TemplateVariant::isString () const [inline], [constexpr]
Returns TRUE if the variant holds a string value
Definition at line 221 of file template.h.
{ return std::holds_alternative<QCString>(m_variant); }
References m_variant.
isStruct() [1/2]
constexpr bool TemplateVariant::isStruct () const [inline], [constexpr]
Returns TRUE if the variant holds a struct value
Definition at line 223 of file template.h.
{ return std::holds_alternative<TemplateStructIntfPtr>(m_variant); }
References m_variant.
Referenced by FilterGet::apply(), TemplateContextImpl::get(), operator==(), TemplateNodeFor::render(), and toStruct().
isStruct() [2/2]
constexpr bool TemplateVariant::isStruct () const [inline], [constexpr]
Returns TRUE if the variant holds a struct value
Definition at line 223 of file template.h.
{ return std::holds_alternative<TemplateStructIntfPtr>(m_variant); }
References m_variant.
isValid() [1/2]
constexpr bool TemplateVariant::isValid () const [inline], [constexpr]
Returns TRUE if the variant holds a valid value, or FALSE otherwise
Definition at line 215 of file template.h.
{ return std::holds_alternative<std::monostate>(m_variant); }
References m_variant.
Referenced by FilterRaw::apply(), FilterList::apply(), FilterTexLabel::apply(), FilterTexIndex::apply(), FilterLength::apply(), FilterFlatten::apply(), FilterRelative::apply(), FilterStripPath::apply(), FilterNoWrap::apply(), FilterIsRelativeURL::apply(), FilterIsAbsoluteURL::apply(), FilterLower::apply(), FilterUpper::apply(), FilterHex::apply(), FilterEscape::apply(), FilterDecodeURL::apply(), FilterAdd::apply(), FilterGet::apply(), FilterDefault::apply(), FilterKeep::apply(), FilterPaginate::apply(), FilterDivisibleBy::apply(), FilterFlatten::flatten(), TemplateContextImpl::get(), operator==(), TemplateNodeTree::renderChildren(), and ExprAstVariable::resolve().
isValid() [2/2]
constexpr bool TemplateVariant::isValid () const [inline], [constexpr]
Returns TRUE if the variant holds a valid value, or FALSE otherwise
Definition at line 215 of file template.h.
{ return std::holds_alternative<std::monostate>(m_variant); }
References m_variant.
isWeakStruct() [1/2]
constexpr bool TemplateVariant::isWeakStruct () const [inline], [constexpr]
Returns TRUE if the variant holds a struct value
Definition at line 229 of file template.h.
{ return std::holds_alternative<TemplateStructIntfWeakPtr>(m_variant); }
References m_variant.
Referenced by FilterGet::apply(), TemplateContextImpl::get(), operator==(), TemplateNodeFor::render(), structToString(), and toStruct().
isWeakStruct() [2/2]
constexpr bool TemplateVariant::isWeakStruct () const [inline], [constexpr]
Returns TRUE if the variant holds a struct value
Definition at line 229 of file template.h.
{ return std::holds_alternative<TemplateStructIntfWeakPtr>(m_variant); }
References m_variant.
listToString() [1/2]
QCString TemplateVariant::listToString () const [private]
Definition at line 5422 of file template.cpp.
{
  QCString result="[";
  const TemplateListIntfPtr list = toList();
  if (list)
  {
    bool first=true;
    TemplateVariant ve;
    TemplateListIntf::ConstIteratorPtr it = list->createIterator();
    for (it->toFirst();it->current(ve);it->toNext())
    {
      if (!first) result+=",\n";
      result+="'"+ve.toString()+"'";
      first=false;
    }
  }
  result+="]";
  return result;
}
References toList(), and toString().
Referenced by toString().
listToString() [2/2]
QCString TemplateVariant::listToString () const [private]
operator=() [1/4]
TemplateVariant & TemplateVariant::operator= (const TemplateVariant & v) [default]
Assigns the value of the variant v to this variant.
operator=() [2/4]
TemplateVariant & TemplateVariant::operator= (const TemplateVariant & v) [default]
Assigns the value of the variant v to this variant.
operator=() [3/4]
TemplateVariant & TemplateVariant::operator= (TemplateVariant && v)
Move the value of the variant v into this variant. Variant v will become invalid
Definition at line 333 of file template.cpp.
{
  m_raw = std::move(v.m_raw);
  m_variant = std::move(v.m_variant);
  v.m_variant = VariantT();
  return *this;
}
References m_raw, and m_variant.
operator=() [4/4]
TemplateVariant & TemplateVariant::operator= (TemplateVariant && v)
Move the value of the variant v into this variant. Variant v will become invalid
operator==() [1/2]
bool TemplateVariant::operator== (TemplateVariant & other) const
Compares this QVariant with v and returns true if they are equal; otherwise returns false.
Definition at line 341 of file template.cpp.
{
  if (!isValid())
  {
    return FALSE;
  }
  if (isBool() && other.isBool())
  {
    return std::get<bool>(m_variant) == std::get<bool>(other.m_variant);
  }
  else if (isInt() && other.isInt())
  {
    return std::get<int>(m_variant) == std::get<int>(other.m_variant);
  }
  else if (isList() && other.isList())
  {
    return toList() == other.toList();
  }
  else if ((isStruct() || isWeakStruct()) && (other.isStruct() || other.isWeakStruct()))
  {
    return toStruct() == other.toStruct();
  }
  return toString()==other.toString();
}
References FALSE, isBool(), isInt(), isList(), isStruct(), isValid(), isWeakStruct(), m_variant, toList(), toString(), and toStruct().
operator==() [2/2]
bool TemplateVariant::operator== (TemplateVariant & other) const
Compares this QVariant with v and returns true if they are equal; otherwise returns false.
raw() [1/2]
constexpr bool TemplateVariant::raw () const [inline], [constexpr]
Returns whether or not the value of the Value is raw.
See also
setRaw()
Definition at line 257 of file template.h.
{ return m_raw; }
References m_raw.
Referenced by TemplateNodeVariable::render(), and TemplateNodeCycle::render().
raw() [2/2]
constexpr bool TemplateVariant::raw () const [inline], [constexpr]
Returns whether or not the value of the Value is raw.
See also
setRaw()
Definition at line 257 of file template.h.
{ return m_raw; }
References m_raw.
setRaw() [1/2]
void TemplateVariant::setRaw (bool b) [inline]
Sets whether or not the value of the Variant should be escaped or written as-is (raw).
Parameters
 in b TRUE means write as-is, FALSE means apply escaping.
Definition at line 252 of file template.h.
{ m_raw = b; }
References b, and m_raw.
Referenced by TemplateNodeTree::renderChildren().
setRaw() [2/2]
void TemplateVariant::setRaw (bool b) [inline]
Sets whether or not the value of the Variant should be escaped or written as-is (raw).
Parameters
 in b TRUE means write as-is, FALSE means apply escaping.
Definition at line 252 of file template.h.
{ m_raw = b; }
References b, and m_raw.
structToString() [1/2]
QCString TemplateVariant::structToString () const [private]
Definition at line 5442 of file template.cpp.
{
  QCString result="{";
  const TemplateStructIntfPtr strukt = toStruct();
  if (strukt)
  {
    bool first=true;
    for (const auto &s : strukt->fields())
    {
      if (!first) result+=",";
      result+=s;
      if (!isWeakStruct()) // avoid endless recursion
      {
        result+=":'";
        result+=strukt->get(QCString(s)).toString();
        result+="'";
      }
      first=false;
    }
  }
  result+="}";
  return result;
}
References isWeakStruct(), s, and toStruct().
Referenced by toString().
structToString() [2/2]
QCString TemplateVariant::structToString () const [private]
toBool() [1/2]
bool TemplateVariant::toBool () const
Returns the variant as a boolean.
Definition at line 366 of file template.cpp.
{
  switch (type())
  {
    case Type::None: return false;
    case Type::Bool: return std::get<bool>(m_variant);
    case Type::Int: return std::get<int>(m_variant)!=0;
    case Type::String: return !std::get<QCString>(m_variant).isEmpty();
    case Type::Struct: return true;
    case Type::List: return std::get<TemplateListIntfPtr>(m_variant)->count()!=0;
    case Type::Function: return false;
    case Type::WeakStruct: return true;
  }
  return FALSE;
}
References Bool, FALSE, Function, Int, List, m_variant, None, String, Struct, type(), and WeakStruct.
Referenced by FilterKeep::apply(), TemplateNodeIf::render(), and ExprAstBinary::resolve().
toBool() [2/2]
bool TemplateVariant::toBool () const
Returns the variant as a boolean.
toInt() [1/2]
int TemplateVariant::toInt () const
Returns the variant as an integer.
Definition at line 382 of file template.cpp.
{
  switch (type())
  {
    case Type::None: return 0;
    case Type::Bool: return std::get<bool>(m_variant) ? 1 : 0;
    case Type::Int: return std::get<int>(m_variant);
    case Type::String: return std::get<QCString>(m_variant).toInt();
    case Type::Struct: return 0;
    case Type::List: return static_cast<int>(std::get<TemplateListIntfPtr>(m_variant)->count());
    case Type::Function: return 0;
    case Type::WeakStruct: return 0;
  }
  return 0;
}
References Bool, Function, Int, List, m_variant, None, String, Struct, type(), and WeakStruct.
Referenced by FilterHex::apply(), FilterPaginate::apply(), FilterDivisibleBy::apply(), TemplateNodeRepeat::render(), TemplateNodeRange::render(), ExprAstUnary::resolve(), ExprAstBinary::resolve(), and FilterAdd::variantIntValue().
toInt() [2/2]
int TemplateVariant::toInt () const
Returns the variant as an integer.
toList() [1/4]
TemplateListIntfPtr TemplateVariant::toList ()
Returns the pointer to list referenced by this variant or 0 if this variant does not have list type.
Definition at line 431 of file template.cpp.
{
  return isList() ? std::get<TemplateListIntfPtr>(m_variant) : nullptr;
}
References isList(), and m_variant.
Referenced by FilterLength::apply(), FilterFlatten::apply(), FilterKeep::apply(), FilterListSort::apply(), FilterGroupBy::apply(), FilterPaginate::apply(), FilterAlphaIndex::apply(), computeMaxDepth(), computeNumNodesAtLevel(), FilterFlatten::flatten(), TemplateContextImpl::get(), listToString(), operator==(), TemplateNodeFor::render(), TemplateNodeTree::render(), TemplateNodeMarkers::render(), and TemplateNodeTree::renderChildren().
toList() [2/4]
TemplateListIntfPtr TemplateVariant::toList ()
Returns the pointer to list referenced by this variant or 0 if this variant does not have list type.
toList() [3/4]
const TemplateListIntfPtr TemplateVariant::toList () const
Definition at line 435 of file template.cpp.
{
  return isList() ? std::get<TemplateListIntfPtr>(m_variant) : nullptr;
}
References isList(), and m_variant.
toList() [4/4]
const TemplateListIntfPtr TemplateVariant::toList () const
toString() [1/2]
QCString TemplateVariant::toString () const
Returns the variant as a string.
Definition at line 398 of file template.cpp.
{
  switch (type())
  {
    case Type::None: return QCString();
    case Type::Bool: return std::get<bool>(m_variant) ? "true" : "false";
    case Type::Int: return QCString().setNum(std::get<int>(m_variant));
    case Type::String: return std::get<QCString>(m_variant);
    case Type::Struct: return structToString();
    case Type::List: return listToString();
    case Type::Function: return "[function]";
    case Type::WeakStruct: return structToString();
  }
  return QCString();
}
References Bool, Function, Int, List, listToString(), m_variant, None, QCString::setNum(), String, Struct, structToString(), type(), and WeakStruct.
Referenced by FilterRaw::apply(), FilterTexLabel::apply(), FilterTexIndex::apply(), FilterLength::apply(), FilterRelative::apply(), FilterStripPath::apply(), FilterNoWrap::apply(), FilterIsRelativeURL::apply(), FilterIsAbsoluteURL::apply(), FilterLower::apply(), FilterUpper::apply(), FilterEscape::apply(), FilterDecodeURL::apply(), FilterAdd::apply(), FilterGet::apply(), FilterAppend::apply(), FilterPrepend::apply(), FilterDefault::apply(), FilterKeep::apply(), FilterListSort::apply(), FilterGroupBy::apply(), FilterAlphaIndex::apply(), ExprAstFilter::apply(), FilterGroupBy::determineSortKey(), FilterAlphaIndex::determineSortKey(), listToString(), operator==(), TemplateNodeVariable::render(), TemplateNodeCycle::render(), TemplateNodeMarkers::render(), ExprAstBinary::resolve(), and FilterAdd::variantIntValue().
toString() [2/2]
QCString TemplateVariant::toString () const
Returns the variant as a string.
toStruct() [1/4]
TemplateStructIntfPtr TemplateVariant::toStruct ()
Returns the pointer to struct referenced by this variant or 0 if this variant does not have struct type.
Definition at line 440 of file template.cpp.
{
  return isStruct() ? std::get<TemplateStructIntfPtr>(m_variant) :
         isWeakStruct() ? std::get<TemplateStructIntfWeakPtr>(m_variant).lock() :
         nullptr;
}
References isStruct(), isWeakStruct(), and m_variant.
Referenced by FilterGet::apply(), FilterKeep::apply(), FilterListSort::apply(), FilterGroupBy::apply(), FilterAlphaIndex::apply(), computeMaxDepth(), computeNumNodesAtLevel(), computePreferredDepth(), FilterFlatten::flatten(), TemplateContextImpl::get(), operator==(), TemplateNodeFor::render(), TemplateNodeTree::renderChildren(), and structToString().
toStruct() [2/4]
TemplateStructIntfPtr TemplateVariant::toStruct ()
Returns the pointer to struct referenced by this variant or 0 if this variant does not have struct type.
toStruct() [3/4]
const TemplateStructIntfPtr TemplateVariant::toStruct () const
Definition at line 446 of file template.cpp.
{
  return isStruct() ? std::get<TemplateStructIntfPtr>(m_variant) :
         isWeakStruct() ? std::get<TemplateStructIntfWeakPtr>(m_variant).lock() :
         nullptr;
}
References isStruct(), isWeakStruct(), and m_variant.
toStruct() [4/4]
const TemplateStructIntfPtr TemplateVariant::toStruct () const
type() [1/2]
constexpr Type TemplateVariant::type () const [inline], [constexpr]
Returns the type held by this variant
Definition at line 260 of file template.h.
{ return static_cast<Type>(m_variant.index()); }
References m_variant.
Referenced by ExprAstFilter::apply(), toBool(), toInt(), toString(), and typeAsString().
type() [2/2]
constexpr Type TemplateVariant::type () const [inline], [constexpr]
Returns the type held by this variant
Definition at line 260 of file template.h.
{ return static_cast<Type>(m_variant.index()); }
References m_variant.
typeAsString() [1/2]
const char * TemplateVariant::typeAsString () const
Returns a string representation of this variant's type
Return a string representation of the type of the value stored in the variant
Definition at line 415 of file template.cpp.
{
  switch (type())
  {
    case Type::None: return "invalid";
    case Type::Bool: return "bool";
    case Type::Int: return "integer";
    case Type::String: return "string";
    case Type::Struct: return "struct";
    case Type::List: return "list";
    case Type::Function: return "function";
    case Type::WeakStruct: return "struct";
  }
  return "invalid";
}
References Bool, Function, Int, List, None, String, Struct, type(), and WeakStruct.
Referenced by TemplateNodeFor::render(), and TemplateNodeTree::renderChildren().
typeAsString() [2/2]
const char * TemplateVariant::typeAsString () const
Returns a string representation of this variant's type
Member Data Documentation
m_raw
bool TemplateVariant::m_raw = false [private]
Definition at line 270 of file template.h.
Referenced by operator=(), raw(), setRaw(), and TemplateVariant().
m_variant
VariantT TemplateVariant::m_variant [private]
Definition at line 269 of file template.h.
Referenced by call(), isBool(), isFunction(), isInt(), isList(), isString(), isStruct(), isValid(), isWeakStruct(), operator=(), operator==(), TemplateVariant(), toBool(), toInt(), toList(), toString(), toStruct(), and type().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.h
doxygen/src/template.h
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp