FilterPaginate Class Reference
The implementation of the `paginate` filter.
Static Public Member Functions
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &args)
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &args)
Detailed Description
The implementation of the `paginate` filter.
Definition at line 1238 of file template.cpp.
Member Function Documentation
apply() [1/2]
static TemplateVariant FilterPaginate::apply (const TemplateVariant & v, const TemplateVariant & args) [inline], [static]
Definition at line 1241 of file template.cpp.
    {
      if (v.isValid() && v.isList() &&
          args.isValid() && args.isInt())
      {
        int pageSize = args.toInt();
        const TemplateListIntfPtr list = v.toList();
        TemplateListPtr result = TemplateList::alloc();
        TemplateListIntf::ConstIteratorPtr it = list->createIterator();
        TemplateVariant item;
        TemplateListPtr pageList;
        int i = 0;
        for (it->toFirst();(it->current(item));it->toNext())
        {
          if (pageList==0)
          {
            pageList = TemplateList::alloc();
            result->append(std::static_pointer_cast<TemplateListIntf>(pageList));
          }
          pageList->append(item);
          i++;
          if (i==pageSize) // page is full start a new one
          {
            pageList=0;
            i=0;
          }
        }
        return TemplateVariant(std::static_pointer_cast<TemplateListIntf>(result));
      }
      else // wrong arguments
      {
        return v;
      }
    }
References TemplateList::alloc(), TemplateVariant::isInt(), TemplateVariant::isList(), TemplateVariant::isValid(), TemplateVariant::toInt(), and TemplateVariant::toList().
apply() [2/2]
static TemplateVariant FilterPaginate::apply (const TemplateVariant & v, const TemplateVariant & args) [inline], [static]
Definition at line 1241 of file template.cpp.
    {
      if (v.isValid() && v.isList() &&
          args.isValid() && args.isInt())
      {
        int pageSize = args.toInt();
        const TemplateListIntfPtr list = v.toList();
        TemplateListPtr result = TemplateList::alloc();
        TemplateListIntf::ConstIteratorPtr it = list->createIterator();
        TemplateVariant item;
        TemplateListPtr pageList;
        int i = 0;
        for (it->toFirst();(it->current(item));it->toNext())
        {
          if (pageList==0)
          {
            pageList = TemplateList::alloc();
            result->append(std::static_pointer_cast<TemplateListIntf>(pageList));
          }
          pageList->append(item);
          i++;
          if (i==pageSize) // page is full start a new one
          {
            pageList=0;
            i=0;
          }
        }
        return TemplateVariant(std::static_pointer_cast<TemplateListIntf>(result));
      }
      else // wrong arguments
      {
        return v;
      }
    }
References TemplateList::alloc(), TemplateVariant::isInt(), TemplateVariant::isList(), TemplateVariant::isValid(), TemplateVariant::toInt(), and TemplateVariant::toList().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/template.cpp
doxygen/src/template.cpp