TranslatorGerman Class Reference
#include <translator_de.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool, bool singular)
virtual QCString trFile (bool, bool singular)
virtual QCString trNamespace (bool, bool singular)
virtual QCString trGroup (bool, bool singular)
virtual QCString trPage (bool, bool singular)
virtual QCString trMember (bool, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool, bool singular)
virtual QCString trSubprogram (bool, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
virtual QCString trDesignUnitHierarchy ()
virtual QCString trDesignUnitList ()
virtual QCString trDesignUnitMembers ()
virtual QCString trDesignUnitListDescription ()
virtual QCString trDesignUnitIndex ()
virtual QCString trDesignUnits ()
virtual QCString trFunctionAndProc ()
virtual QCString trVhdlType (uint64 type, bool single)
virtual QCString trCustomReference (const QCString &name)
virtual QCString trDesignUnitDocumentation ()
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool, bool singular)
virtual QCString trFile (bool, bool singular)
virtual QCString trNamespace (bool, bool singular)
virtual QCString trGroup (bool, bool singular)
virtual QCString trPage (bool, bool singular)
virtual QCString trMember (bool, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool, bool singular)
virtual QCString trSubprogram (bool, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool, bool full)
virtual QCString trMonth (int month, bool, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const QCString &namespaceName)
virtual QCString trServiceReference (const QCString &sName)
virtual QCString trSingletonReference (const QCString &sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
virtual QCString trDesignUnitHierarchy ()
virtual QCString trDesignUnitList ()
virtual QCString trDesignUnitMembers ()
virtual QCString trDesignUnitListDescription ()
virtual QCString trDesignUnitIndex ()
virtual QCString trDesignUnits ()
virtual QCString trFunctionAndProc ()
virtual QCString trVhdlType (uint64 type, bool single)
virtual QCString trCustomReference (const QCString &name)
virtual QCString trDesignUnitDocumentation ()
Additional Inherited Members
Detailed Description
Definition at line 144 of file translator_de.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorGerman::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 171 of file translator_de.h.
    {
      return "0x407 German";
    }
getLanguageString() [2/2]
virtual QCString TranslatorGerman::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 171 of file translator_de.h.
    {
      return "0x407 German";
    }
idLanguage() [1/2]
virtual QCString TranslatorGerman::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 156 of file translator_de.h.
    { return "german"; }
idLanguage() [2/2]
virtual QCString TranslatorGerman::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 156 of file translator_de.h.
    { return "german"; }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorGerman::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method was designed for languages which do wish to use a babel package.
Implements Translator.
Definition at line 162 of file translator_de.h.
    {
      return "\\usepackage[ngerman]{babel}\n";
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorGerman::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method was designed for languages which do wish to use a babel package.
Implements Translator.
Definition at line 162 of file translator_de.h.
    {
      return "\\usepackage[ngerman]{babel}\n";
    }
trAdditionalInheritedMembers() [1/2]
virtual QCString TranslatorGerman::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 2029 of file translator_de.h.
    { return "Weitere Geerbte Elemente"; }
trAdditionalInheritedMembers() [2/2]
virtual QCString TranslatorGerman::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 2029 of file translator_de.h.
    { return "Weitere Geerbte Elemente"; }
trAll() [1/2]
virtual QCString TranslatorGerman::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1535 of file translator_de.h.
    {
      return "Alle";
    }
trAll() [2/2]
virtual QCString TranslatorGerman::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1535 of file translator_de.h.
    {
      return "Alle";
    }
trAndMore() [1/2]
virtual QCString TranslatorGerman::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 2004 of file translator_de.h.
    { return "und "+number+" mehr ..."; }
trAndMore() [2/2]
virtual QCString TranslatorGerman::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 2004 of file translator_de.h.
    { return "und "+number+" mehr ..."; }
trAttention() [1/2]
virtual QCString TranslatorGerman::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 1095 of file translator_de.h.
    {
      return "Achtung";
    }
trAttention() [2/2]
virtual QCString TranslatorGerman::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 1095 of file translator_de.h.
    {
      return "Achtung";
    }
trAuthor() [1/2]
virtual QCString TranslatorGerman::trAuthor (bool , bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1401 of file translator_de.h.
    {
      QCString result("Autor");
      if (!singular) result+="en";
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorGerman::trAuthor (bool , bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1401 of file translator_de.h.
    {
      QCString result("Autor");
      if (!singular) result+="en";
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorGerman::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1278 of file translator_de.h.
    {
      return "Fehler";
    }
trBug() [2/2]
virtual QCString TranslatorGerman::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1278 of file translator_de.h.
    {
      return "Fehler";
    }
trBugList() [1/2]
virtual QCString TranslatorGerman::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1284 of file translator_de.h.
    {
      return "Liste der bekannten Fehler";
    }
trBugList() [2/2]
virtual QCString TranslatorGerman::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1284 of file translator_de.h.
    {
      return "Liste der bekannten Fehler";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorGerman::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1656 of file translator_de.h.
    {
      return "Hier ist ein Graph der zeigt, wo diese Funktion aufgerufen wird:";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorGerman::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1656 of file translator_de.h.
    {
      return "Hier ist ein Graph der zeigt, wo diese Funktion aufgerufen wird:";
    }
trCallGraph() [1/2]
virtual QCString TranslatorGerman::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1540 of file translator_de.h.
    {
      return "Hier ist ein Graph, der zeigt, was diese Funktion aufruft:";
    }
trCallGraph() [2/2]
virtual QCString TranslatorGerman::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1540 of file translator_de.h.
    {
      return "Hier ist ein Graph, der zeigt, was diese Funktion aufruft:";
    }
trCiteReferences() [1/2]
virtual QCString TranslatorGerman::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1980 of file translator_de.h.
    { return "Literaturverzeichnis"; }
trCiteReferences() [2/2]
virtual QCString TranslatorGerman::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1980 of file translator_de.h.
    { return "Literaturverzeichnis"; }
trClass() [1/2]
virtual QCString TranslatorGerman::trClass (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1321 of file translator_de.h.
    {
      QCString result("Klasse");
      if (!singular) result+="n";
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorGerman::trClass (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1321 of file translator_de.h.
    {
      QCString result("Klasse");
      if (!singular) result+="n";
      return result;
    }
trClassDiagram() [1/2]
virtual QCString TranslatorGerman::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 611 of file translator_de.h.
    {
      return "Klassendiagramm fr "+clName+":";
    }
trClassDiagram() [2/2]
virtual QCString TranslatorGerman::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 611 of file translator_de.h.
    {
      return "Klassendiagramm fr "+clName+":";
    }
trClassDocumentation() [1/2]
virtual QCString TranslatorGerman::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 486 of file translator_de.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datenstruktur-Dokumentation";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Klassen-Dokumentation";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorGerman::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 486 of file translator_de.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datenstruktur-Dokumentation";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Klassen-Dokumentation";
      }
    }
References Config_getBool, and trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorGerman::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1236 of file translator_de.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datenstrukturen";
      }
      else
      {
        return "Klassen";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorGerman::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1236 of file translator_de.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datenstrukturen";
      }
      else
      {
        return "Klassen";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorGerman::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 266 of file translator_de.h.
    { return "Klassenhierarchie"; }
trClassHierarchy() [2/2]
virtual QCString TranslatorGerman::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 266 of file translator_de.h.
    { return "Klassenhierarchie"; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorGerman::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 325 of file translator_de.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return "Hier folgt eine hierarchische Auflistung der "
               "Entwurfseinheiten:";
      }
      else
      {
        return "Die Liste der Ableitungen ist -mit Einschrnkungen- "
               "alphabetisch sortiert:";
      }
    }
References Config_getBool.
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorGerman::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 325 of file translator_de.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
        return "Hier folgt eine hierarchische Auflistung der "
               "Entwurfseinheiten:";
      }
      else
      {
        return "Die Liste der Ableitungen ist -mit Einschrnkungen- "
               "alphabetisch sortiert:";
      }
    }
References Config_getBool.
trClassMethods() [1/2]
virtual QCString TranslatorGerman::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 2067 of file translator_de.h.
    {
      return "Klassenmethoden";
    }
trClassMethods() [2/2]
virtual QCString TranslatorGerman::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 2067 of file translator_de.h.
    {
      return "Klassenmethoden";
    }
trCode() [1/2]
virtual QCString TranslatorGerman::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 978 of file translator_de.h.
    {
      return "code";
    }
trCode() [2/2]
virtual QCString TranslatorGerman::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 978 of file translator_de.h.
    {
      return "code";
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorGerman::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 924 of file translator_de.h.
    {
      return "Zusammengehrigkeiten von "+clName+":";
    }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorGerman::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 924 of file translator_de.h.
    {
      return "Zusammengehrigkeiten von "+clName+":";
    }
trCompoundIndex() [1/2]
virtual QCString TranslatorGerman::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 463 of file translator_de.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
    return "Datenstruktur-Verzeichnis";
      else
        return "Klassen-Verzeichnis";
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorGerman::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 463 of file translator_de.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
    return "Datenstruktur-Verzeichnis";
      else
        return "Klassen-Verzeichnis";
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorGerman::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1711 of file translator_de.h.
    { return "Datentyp-Index"; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorGerman::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1711 of file translator_de.h.
    { return "Datentyp-Index"; }
trCompoundList() [1/2]
virtual QCString TranslatorGerman::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 270 of file translator_de.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datenstrukturen";
      }
      else
      {
        return "Auflistung der Klassen";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorGerman::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 270 of file translator_de.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datenstrukturen";
      }
      else
      {
        return "Auflistung der Klassen";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorGerman::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 349 of file translator_de.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Hier folgt die Aufzhlung aller Datenstrukturen "
               "mit einer Kurzbeschreibung:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Hier folgt die Aufzhlung aller Klassen mit einer Kurzbeschreibung:";
      }
      else
      {
        return "Hier folgt die Aufzhlung aller Klassen, Strukturen, "
               "Varianten und Schnittstellen mit einer Kurzbeschreibung:";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorGerman::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 349 of file translator_de.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Hier folgt die Aufzhlung aller Datenstrukturen "
               "mit einer Kurzbeschreibung:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Hier folgt die Aufzhlung aller Klassen mit einer Kurzbeschreibung:";
      }
      else
      {
        return "Hier folgt die Aufzhlung aller Klassen, Strukturen, "
               "Varianten und Schnittstellen mit einer Kurzbeschreibung:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorGerman::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1684 of file translator_de.h.
      { return "Hier folgen die Datentypen mit Kurzbeschreibungen:"; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorGerman::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1684 of file translator_de.h.
      { return "Hier folgen die Datentypen mit Kurzbeschreibungen:"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorGerman::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1676 of file translator_de.h.
    { return "Datentyp-Liste"; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorGerman::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1676 of file translator_de.h.
    { return "Datentyp-Liste"; }
trCompoundMembers() [1/2]
virtual QCString TranslatorGerman::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 287 of file translator_de.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datenstruktur-Elemente";
      }
      else
      {
        return "Klassen-Elemente";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorGerman::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 287 of file translator_de.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datenstruktur-Elemente";
      }
      else
      {
        return "Klassen-Elemente";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorGerman::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 368 of file translator_de.h.
    {
      QCString result="Hier folgt die Aufzhlung aller ";
      if (!extractAll)
      {
        result+="dokumentierten ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="Strukturen und Varianten";
      }
      else
      {
        result+="Klassenelemente";
      }
      result+=" mit Verweisen auf ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="die Dokumentation zu jedem Element:";
        }
        else
        {
          result+="die Klassendokumentation zu jedem Element:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="die zugehrigen Elemente:";
        }
        else
        {
          result+="die zugehrigen Klassen:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorGerman::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 368 of file translator_de.h.
    {
      QCString result="Hier folgt die Aufzhlung aller ";
      if (!extractAll)
      {
        result+="dokumentierten ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="Strukturen und Varianten";
      }
      else
      {
        result+="Klassenelemente";
      }
      result+=" mit Verweisen auf ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="die Dokumentation zu jedem Element:";
        }
        else
        {
          result+="die Klassendokumentation zu jedem Element:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="die zugehrigen Elemente:";
        }
        else
        {
          result+="die zugehrigen Klassen:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorGerman::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1688 of file translator_de.h.
    {
      QCString result="Hier folgt eine Liste aller ";
      if (!extractAll)
      {
        result+="dokumentierten ";
      }
      result+="Datentypelemente";
      result+=" mit Links ";
      if (!extractAll)
      {
         result+="zur Datenstruktur-Dokumentation fr jedes Element";
      }
      else
      {
         result+="zu den Datentypen, zu denen sie gehren:";
      }
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorGerman::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1688 of file translator_de.h.
    {
      QCString result="Hier folgt eine Liste aller ";
      if (!extractAll)
      {
        result+="dokumentierten ";
      }
      result+="Datentypelemente";
      result+=" mit Links ";
      if (!extractAll)
      {
         result+="zur Datenstruktur-Dokumentation fr jedes Element";
      }
      else
      {
         result+="zu den Datentypen, zu denen sie gehren:";
      }
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorGerman::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1680 of file translator_de.h.
    { return "Datenfelder"; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorGerman::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1680 of file translator_de.h.
    { return "Datenfelder"; }
trCompoundReference() [1/2]
virtual QCString TranslatorGerman::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 686 of file translator_de.h.
    {
      QCString result=clName+" ";
      if (isTemplate) result+="Template-";
      switch(compType)
      {
        case ClassDef::Class: result+="Klassen"; break;
        case ClassDef::Struct: result+="Struktur"; break;
        case ClassDef::Union: result+="Varianten"; break;
        case ClassDef::Interface: result+="Schnittstellen"; break;
        case ClassDef::Protocol: result+="Protokoll"; break;
        case ClassDef::Category: result+="Kategorie"; break;
        case ClassDef::Exception: result+="Ausnahmen"; break;
        default: break;
      }
      result+="referenz";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorGerman::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 686 of file translator_de.h.
    {
      QCString result=clName+" ";
      if (isTemplate) result+="Template-";
      switch(compType)
      {
        case ClassDef::Class: result+="Klassen"; break;
        case ClassDef::Struct: result+="Struktur"; break;
        case ClassDef::Union: result+="Varianten"; break;
        case ClassDef::Interface: result+="Schnittstellen"; break;
        case ClassDef::Protocol: result+="Protokoll"; break;
        case ClassDef::Category: result+="Kategorie"; break;
        case ClassDef::Exception: result+="Ausnahmen"; break;
        default: break;
      }
      result+="referenz";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorGerman::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1752 of file translator_de.h.
    {
      QCString result=clName;
      result += "-";
      switch(compType)
      {
        case ClassDef::Class: result+="Modul"; break;
        case ClassDef::Struct: result+="Typ"; break;
        case ClassDef::Union: result+="Union"; break;
        case ClassDef::Interface: result+="Interface"; break;
        case ClassDef::Protocol: result+="Protokoll"; break;
        case ClassDef::Category: result+="Kategorie"; break;
        case ClassDef::Exception: result+="Ausnahmen"; break;
        default: break;
      }
      if (isTemplate) result+="-Template";
      result+="-Referenz";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorGerman::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1752 of file translator_de.h.
    {
      QCString result=clName;
      result += "-";
      switch(compType)
      {
        case ClassDef::Class: result+="Modul"; break;
        case ClassDef::Struct: result+="Typ"; break;
        case ClassDef::Union: result+="Union"; break;
        case ClassDef::Interface: result+="Interface"; break;
        case ClassDef::Protocol: result+="Protokoll"; break;
        case ClassDef::Category: result+="Kategorie"; break;
        case ClassDef::Exception: result+="Ausnahmen"; break;
        default: break;
      }
      if (isTemplate) result+="-Template";
      result+="-Referenz";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorGerman::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 587 of file translator_de.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datenstrukturen";
      }
      else
      {
        return "Klassen";
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorGerman::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 587 of file translator_de.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datenstrukturen";
      }
      else
      {
        return "Klassen";
      }
    }
References Config_getBool.
trConstantGroupReference() [1/2]
virtual QCString TranslatorGerman::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 2104 of file translator_de.h.
    {
      QCString result=namespaceName;
      result+=" Konstantengruppen-Referenz";
      return result;
    }
trConstantGroupReference() [2/2]
virtual QCString TranslatorGerman::trConstantGroupReference (const QCString & namespaceName) [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 2104 of file translator_de.h.
    {
      QCString result=namespaceName;
      result+=" Konstantengruppen-Referenz";
      return result;
    }
trConstantGroups() [1/2]
virtual QCString TranslatorGerman::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 2100 of file translator_de.h.
    { return "Konstante Gruppen"; }
trConstantGroups() [2/2]
virtual QCString TranslatorGerman::trConstantGroups () [inline], [virtual]
UNO IDL constant groups
Implements Translator.
Definition at line 2100 of file translator_de.h.
    { return "Konstante Gruppen"; }
trConstructorDocumentation() [1/2]
virtual QCString TranslatorGerman::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 936 of file translator_de.h.
    {
      return "Beschreibung der Konstruktoren und Destruktoren";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorGerman::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 936 of file translator_de.h.
    {
      return "Beschreibung der Konstruktoren und Destruktoren";
    }
trCopyright() [1/2]
virtual QCString TranslatorGerman::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1984 of file translator_de.h.
    { return "Copyright"; }
trCopyright() [2/2]
virtual QCString TranslatorGerman::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1984 of file translator_de.h.
    { return "Copyright"; }
trCustomReference() [1/2]
virtual QCString TranslatorGerman::trCustomReference (const QCString & name) [inline], [virtual]
Reimplemented from TranslatorAdapter_1_8_15.
Definition at line 2258 of file translator_de.h.
    { return QCString(name)+"-Referenz"; }
References setup::name.
trCustomReference() [2/2]
virtual QCString TranslatorGerman::trCustomReference (const QCString & name) [inline], [virtual]
Reimplemented from TranslatorAdapter_1_8_15.
Definition at line 2258 of file translator_de.h.
    { return QCString(name)+"-Referenz"; }
References setup::name.
trDataTypes() [1/2]
virtual QCString TranslatorGerman::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1735 of file translator_de.h.
    { return "Datentypen"; }
trDataTypes() [2/2]
virtual QCString TranslatorGerman::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1735 of file translator_de.h.
    { return "Datentypen"; }
trDate() [1/2]
virtual QCString TranslatorGerman::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 625 of file translator_de.h.
    { return "Datum"; }
trDate() [2/2]
virtual QCString TranslatorGerman::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 625 of file translator_de.h.
    { return "Datum"; }
trDateTime() [1/2]
virtual QCString TranslatorGerman::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1939 of file translator_de.h.
    {
      static const char *days[] = { "Mon","Die","Mit","Don","Fre","Sam","Son" };
      static const char *months[] = { "Jan","Feb","Mr","Apr","Mai","Jun","Jul","Aug","Sep","Okt","Nov","Dez" };
      QCString sdate;
      sdate.sprintf("%s %s %d %d",days[dayOfWeek-1],months[month-1],day,year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDateTime() [2/2]
virtual QCString TranslatorGerman::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1939 of file translator_de.h.
    {
      static const char *days[] = { "Mon","Die","Mit","Don","Fre","Sam","Son" };
      static const char *months[] = { "Jan","Feb","Mr","Apr","Mai","Jun","Jul","Aug","Sep","Okt","Nov","Dez" };
      QCString sdate;
      sdate.sprintf("%s %s %d %d",days[dayOfWeek-1],months[month-1],day,year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDayOfWeek() [1/2]
virtual QCString TranslatorGerman::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1955 of file translator_de.h.
    {
      static const char *days_short[] = { "Mo", "Di", "Mi", "Do", "Fr", "Sa", "So" };
      static const char *days_full[] = { "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag", "Sonntag" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      return text;
    }
trDayOfWeek() [2/2]
virtual QCString TranslatorGerman::trDayOfWeek (int dayOfWeek, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1955 of file translator_de.h.
    {
      static const char *days_short[] = { "Mo", "Di", "Mi", "Do", "Fr", "Sa", "So" };
      static const char *days_full[] = { "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag", "Sonntag" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      return text;
    }
trDayPeriod() [1/2]
virtual QCString TranslatorGerman::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1969 of file translator_de.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorGerman::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1969 of file translator_de.h.
    {
      static const char *dayPeriod[] = { "AM", "PM" };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorGerman::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 900 of file translator_de.h.
    {
      return "Definiert in Zeile @0 der Datei @1.";
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorGerman::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 900 of file translator_de.h.
    {
      return "Definiert in Zeile @0 der Datei @1.";
    }
trDefinedIn() [1/2]
virtual QCString TranslatorGerman::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 254 of file translator_de.h.
    { return "Definiert in"; }
trDefinedIn() [2/2]
virtual QCString TranslatorGerman::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 254 of file translator_de.h.
    { return "Definiert in"; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorGerman::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 905 of file translator_de.h.
    {
      return "Definiert in Datei @0.";
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorGerman::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 905 of file translator_de.h.
    {
      return "Definiert in Datei @0.";
    }
trDefineDocumentation() [1/2]
virtual QCString TranslatorGerman::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 557 of file translator_de.h.
    { return "Makro-Dokumentation"; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorGerman::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 557 of file translator_de.h.
    { return "Makro-Dokumentation"; }
trDefines() [1/2]
virtual QCString TranslatorGerman::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 521 of file translator_de.h.
    { return "Makrodefinitionen"; }
trDefines() [2/2]
virtual QCString TranslatorGerman::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 521 of file translator_de.h.
    { return "Makrodefinitionen"; }
trDefineValue() [1/2]
virtual QCString TranslatorGerman::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1268 of file translator_de.h.
    {
      return "Wert:";
    }
trDefineValue() [2/2]
virtual QCString TranslatorGerman::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1268 of file translator_de.h.
    {
      return "Wert:";
    }
trDeprecated() [1/2]
virtual QCString TranslatorGerman::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 914 of file translator_de.h.
    {
      return "Veraltet";
    }
trDeprecated() [2/2]
virtual QCString TranslatorGerman::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 914 of file translator_de.h.
    {
      return "Veraltet";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorGerman::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1458 of file translator_de.h.
    {
      return "Veraltete Elemente";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorGerman::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1458 of file translator_de.h.
    {
      return "Veraltete Elemente";
    }
trDesignUnitDocumentation() [1/2]
virtual QCString TranslatorGerman::trDesignUnitDocumentation () [inline], [virtual]
VHDL design unit documentation
Reimplemented from TranslatorAdapter_1_8_19.
Definition at line 2266 of file translator_de.h.
    { return "Entwurfseinheiten-Dokumentation"; }
Referenced by trClassDocumentation().
trDesignUnitDocumentation() [2/2]
virtual QCString TranslatorGerman::trDesignUnitDocumentation () [inline], [virtual]
VHDL design unit documentation
Reimplemented from TranslatorAdapter_1_8_19.
Definition at line 2266 of file translator_de.h.
    { return "Entwurfseinheiten-Dokumentation"; }
trDesignUnitHierarchy() [1/2]
virtual QCString TranslatorGerman::trDesignUnitHierarchy () [inline], [virtual]
VHDL design unit hierarchy
Reimplemented from TranslatorAdapter_1_8_15.
Definition at line 2149 of file translator_de.h.
    { return "Entwurfseinheiten-Hierarchie"; }
trDesignUnitHierarchy() [2/2]
virtual QCString TranslatorGerman::trDesignUnitHierarchy () [inline], [virtual]
VHDL design unit hierarchy
Reimplemented from TranslatorAdapter_1_8_15.
Definition at line 2149 of file translator_de.h.
    { return "Entwurfseinheiten-Hierarchie"; }
trDesignUnitIndex() [1/2]
virtual QCString TranslatorGerman::trDesignUnitIndex () [inline], [virtual]
VHDL design unit index
Reimplemented from TranslatorAdapter_1_8_15.
Definition at line 2164 of file translator_de.h.
    { return "Entwurfseinheiten-Verzeichnis"; }
trDesignUnitIndex() [2/2]
virtual QCString TranslatorGerman::trDesignUnitIndex () [inline], [virtual]
VHDL design unit index
Reimplemented from TranslatorAdapter_1_8_15.
Definition at line 2164 of file translator_de.h.
    { return "Entwurfseinheiten-Verzeichnis"; }
trDesignUnitList() [1/2]
virtual QCString TranslatorGerman::trDesignUnitList () [inline], [virtual]
VHDL design unit list
Reimplemented from TranslatorAdapter_1_8_15.
Definition at line 2152 of file translator_de.h.
    { return "Auflistung der Entwurfseinheiten"; }
trDesignUnitList() [2/2]
virtual QCString TranslatorGerman::trDesignUnitList () [inline], [virtual]
VHDL design unit list
Reimplemented from TranslatorAdapter_1_8_15.
Definition at line 2152 of file translator_de.h.
    { return "Auflistung der Entwurfseinheiten"; }
trDesignUnitListDescription() [1/2]
virtual QCString TranslatorGerman::trDesignUnitListDescription () [inline], [virtual]
VHDL design unit list description
Reimplemented from TranslatorAdapter_1_8_15.
Definition at line 2158 of file translator_de.h.
    {
        return "Hier folgt die Aufzhlung aller Entwurfseinheiten und deren "
               "Elemente mit einer Kurzbeschreibung:";
    }
trDesignUnitListDescription() [2/2]
virtual QCString TranslatorGerman::trDesignUnitListDescription () [inline], [virtual]
VHDL design unit list description
Reimplemented from TranslatorAdapter_1_8_15.
Definition at line 2158 of file translator_de.h.
    {
        return "Hier folgt die Aufzhlung aller Entwurfseinheiten und deren "
               "Elemente mit einer Kurzbeschreibung:";
    }
trDesignUnitMembers() [1/2]
virtual QCString TranslatorGerman::trDesignUnitMembers () [inline], [virtual]
VHDL design unit members
Reimplemented from TranslatorAdapter_1_8_15.
Definition at line 2155 of file translator_de.h.
    { return "Entwurfseinheiten-Elemente"; }
trDesignUnitMembers() [2/2]
virtual QCString TranslatorGerman::trDesignUnitMembers () [inline], [virtual]
VHDL design unit members
Reimplemented from TranslatorAdapter_1_8_15.
Definition at line 2155 of file translator_de.h.
    { return "Entwurfseinheiten-Elemente"; }
trDesignUnits() [1/2]
virtual QCString TranslatorGerman::trDesignUnits () [inline], [virtual]
VHDL design units
Reimplemented from TranslatorAdapter_1_8_15.
Definition at line 2167 of file translator_de.h.
    { return "Entwurfseinheiten"; }
trDesignUnits() [2/2]
virtual QCString TranslatorGerman::trDesignUnits () [inline], [virtual]
VHDL design units
Reimplemented from TranslatorAdapter_1_8_15.
Definition at line 2167 of file translator_de.h.
    { return "Entwurfseinheiten"; }
trDetailedDescription() [1/2]
virtual QCString TranslatorGerman::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 187 of file translator_de.h.
    { return "Ausfhrliche Beschreibung"; }
trDetailedDescription() [2/2]
virtual QCString TranslatorGerman::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 187 of file translator_de.h.
    { return "Ausfhrliche Beschreibung"; }
trDetailLevel() [1/2]
virtual QCString TranslatorGerman::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1996 of file translator_de.h.
    { return "Detailebene"; }
trDetailLevel() [2/2]
virtual QCString TranslatorGerman::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1996 of file translator_de.h.
    { return "Detailebene"; }
trDir() [1/2]
virtual QCString TranslatorGerman::trDir (bool , bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1630 of file translator_de.h.
    {
      QCString result("Verzeichnis");
      if (!singular) result+="se";
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorGerman::trDir (bool , bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1630 of file translator_de.h.
    {
      QCString result("Verzeichnis");
      if (!singular) result+="se";
      return result;
    }
trDirDepGraph() [1/2]
virtual QCString TranslatorGerman::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1988 of file translator_de.h.
    { return QCString("Diagramm der Verzeichnisabhngigkeiten fr ")+name+":"; }
References setup::name.
trDirDepGraph() [2/2]
virtual QCString TranslatorGerman::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1988 of file translator_de.h.
    { return QCString("Diagramm der Verzeichnisabhngigkeiten fr ")+name+":"; }
References setup::name.
trDirDocumentation() [1/2]
virtual QCString TranslatorGerman::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1612 of file translator_de.h.
    { return "Verzeichnisdokumentation"; }
trDirDocumentation() [2/2]
virtual QCString TranslatorGerman::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1612 of file translator_de.h.
    { return "Verzeichnisdokumentation"; }
trDirectories() [1/2]
virtual QCString TranslatorGerman::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1618 of file translator_de.h.
    { return "Verzeichnisse"; }
trDirectories() [2/2]
virtual QCString TranslatorGerman::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1618 of file translator_de.h.
    { return "Verzeichnisse"; }
trDirIndex() [1/2]
virtual QCString TranslatorGerman::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1606 of file translator_de.h.
    { return "Verzeichnishierarchie"; }
trDirIndex() [2/2]
virtual QCString TranslatorGerman::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1606 of file translator_de.h.
    { return "Verzeichnishierarchie"; }
trDirReference() [1/2]
virtual QCString TranslatorGerman::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1624 of file translator_de.h.
    { QCString result=dirName; result+="-Verzeichnisreferenz"; return result; }
trDirReference() [2/2]
virtual QCString TranslatorGerman::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1624 of file translator_de.h.
    { QCString result=dirName; result+="-Verzeichnisreferenz"; return result; }
trDirRelation() [1/2]
virtual QCString TranslatorGerman::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1878 of file translator_de.h.
    {
      return "Bezug " + QCString(name);
    }
References setup::name.
trDirRelation() [2/2]
virtual QCString TranslatorGerman::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1878 of file translator_de.h.
    {
      return "Bezug " + QCString(name);
    }
References setup::name.
trDocumentation() [1/2]
virtual QCString TranslatorGerman::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 445 of file translator_de.h.
    { return "Dokumentation"; }
trDocumentation() [2/2]
virtual QCString TranslatorGerman::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 445 of file translator_de.h.
    { return "Dokumentation"; }
trEnumerations() [1/2]
virtual QCString TranslatorGerman::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 533 of file translator_de.h.
    { return "Aufzhlungen"; }
trEnumerations() [2/2]
virtual QCString TranslatorGerman::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 533 of file translator_de.h.
    { return "Aufzhlungen"; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorGerman::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 569 of file translator_de.h.
    { return "Dokumentation der Aufzhlungstypen"; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorGerman::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 569 of file translator_de.h.
    { return "Dokumentation der Aufzhlungstypen"; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorGerman::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1664 of file translator_de.h.
    { return "Dokumentation der Aufzhlungswerte"; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorGerman::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1664 of file translator_de.h.
    { return "Dokumentation der Aufzhlungswerte"; }
trEnumerationValues() [1/2]
virtual QCString TranslatorGerman::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 551 of file translator_de.h.
    { return "Aufzhlungswerte"; }
trEnumerationValues() [2/2]
virtual QCString TranslatorGerman::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 551 of file translator_de.h.
    { return "Aufzhlungswerte"; }
trEnumGeneratedFromFiles() [1/2]
virtual QCString TranslatorGerman::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 2008 of file translator_de.h.
    { QCString result = "Die Dokumentation fr diesen enum wurde aus ";
      if (single)
        result += "der folgenden Datei";
      else
        result += "den folgenden Dateien";
      result+=" generiert:";
      return result;
    }
trEnumGeneratedFromFiles() [2/2]
virtual QCString TranslatorGerman::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 2008 of file translator_de.h.
    { QCString result = "Die Dokumentation fr diesen enum wurde aus ";
      if (single)
        result += "der folgenden Datei";
      else
        result += "den folgenden Dateien";
      result+=" generiert:";
      return result;
    }
trEnumName() [1/2]
virtual QCString TranslatorGerman::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 246 of file translator_de.h.
    { return "enum-Bezeichner"; }
trEnumName() [2/2]
virtual QCString TranslatorGerman::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 246 of file translator_de.h.
    { return "enum-Bezeichner"; }
trEnumReference() [1/2]
virtual QCString TranslatorGerman::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 2019 of file translator_de.h.
    { return QCString(name)+" Enum-Referenz"; }
References setup::name.
trEnumReference() [2/2]
virtual QCString TranslatorGerman::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 2019 of file translator_de.h.
    { return QCString(name)+" Enum-Referenz"; }
References setup::name.
trEnumValue() [1/2]
virtual QCString TranslatorGerman::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 250 of file translator_de.h.
    { return "enum-Wert"; }
trEnumValue() [2/2]
virtual QCString TranslatorGerman::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 250 of file translator_de.h.
    { return "enum-Wert"; }
trEventDocumentation() [1/2]
virtual QCString TranslatorGerman::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1476 of file translator_de.h.
    {
      return "Ereignisdokumentation";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorGerman::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1476 of file translator_de.h.
    {
      return "Ereignisdokumentation";
    }
trEvents() [1/2]
virtual QCString TranslatorGerman::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1470 of file translator_de.h.
    {
      return "Ereignisse";
    }
trEvents() [2/2]
virtual QCString TranslatorGerman::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1470 of file translator_de.h.
    {
      return "Ereignisse";
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorGerman::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 511 of file translator_de.h.
    { return "Dokumentation der Beispiele"; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorGerman::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 511 of file translator_de.h.
    { return "Dokumentation der Beispiele"; }
trExamples() [1/2]
virtual QCString TranslatorGerman::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 317 of file translator_de.h.
    { return "Beispiele"; }
trExamples() [2/2]
virtual QCString TranslatorGerman::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 317 of file translator_de.h.
    { return "Beispiele"; }
trExamplesDescription() [1/2]
virtual QCString TranslatorGerman::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 431 of file translator_de.h.
    { return "Hier folgt eine Liste mit allen Beispielen:"; }
trExamplesDescription() [2/2]
virtual QCString TranslatorGerman::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 431 of file translator_de.h.
    { return "Hier folgt eine Liste mit allen Beispielen:"; }
trExceptions() [1/2]
virtual QCString TranslatorGerman::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 641 of file translator_de.h.
    { return "Ausnahmebehandlung"; }
trExceptions() [2/2]
virtual QCString TranslatorGerman::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 641 of file translator_de.h.
    { return "Ausnahmebehandlung"; }
trExtendsClass() [1/2]
virtual QCString TranslatorGerman::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 2059 of file translator_de.h.
    {
      return "Erweitert Klasse @0.";
    }
trExtendsClass() [2/2]
virtual QCString TranslatorGerman::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 2059 of file translator_de.h.
    {
      return "Erweitert Klasse @0.";
    }
trFile() [1/2]
virtual QCString TranslatorGerman::trFile (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1332 of file translator_de.h.
    {
      QCString result("Datei");
      if (!singular) result+="en";
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorGerman::trFile (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1332 of file translator_de.h.
    {
      QCString result("Datei");
      if (!singular) result+="en";
      return result;
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorGerman::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 505 of file translator_de.h.
    { return "Datei-Dokumentation"; }
trFileDocumentation() [2/2]
virtual QCString TranslatorGerman::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 505 of file translator_de.h.
    { return "Datei-Dokumentation"; }
trFileIn() [1/2]
virtual QCString TranslatorGerman::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1915 of file translator_de.h.
    {
      return "Datei in "+name;
    }
References setup::name.
trFileIn() [2/2]
virtual QCString TranslatorGerman::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1915 of file translator_de.h.
    {
      return "Datei in "+name;
    }
References setup::name.
trFileIndex() [1/2]
virtual QCString TranslatorGerman::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 474 of file translator_de.h.
    { return "Datei-Verzeichnis"; }
trFileIndex() [2/2]
virtual QCString TranslatorGerman::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 474 of file translator_de.h.
    { return "Datei-Verzeichnis"; }
trFileList() [1/2]
virtual QCString TranslatorGerman::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 283 of file translator_de.h.
    { return "Auflistung der Dateien"; }
trFileList() [2/2]
virtual QCString TranslatorGerman::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 283 of file translator_de.h.
    { return "Auflistung der Dateien"; }
trFileListDescription() [1/2]
virtual QCString TranslatorGerman::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 340 of file translator_de.h.
    {
      QCString result="Hier folgt die Aufzhlung aller ";
      if (!extractAll) result+="dokumentierten ";
      result+="Dateien mit einer Kurzbeschreibung:";
      return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorGerman::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 340 of file translator_de.h.
    {
      QCString result="Hier folgt die Aufzhlung aller ";
      if (!extractAll) result+="dokumentierten ";
      result+="Dateien mit einer Kurzbeschreibung:";
      return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorGerman::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 300 of file translator_de.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globale Elemente";
      }
      else
      {
        return "Datei-Elemente";
      }
    }
References Config_getBool.
trFileMembers() [2/2]
virtual QCString TranslatorGerman::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 300 of file translator_de.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Globale Elemente";
      }
      else
      {
        return "Datei-Elemente";
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
virtual QCString TranslatorGerman::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 410 of file translator_de.h.
    {
      QCString result="Hier folgt die Aufzhlung aller ";
      if (!extractAll) result+="dokumentierten ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="Funktionen, Variablen, Makros, Aufzhlungen und Typdefinitionen";
      }
      else
      {
        result+="Dateielemente";
      }
      result+=" mit Verweisen auf ";
      if (extractAll)
        result+="die Dokumentation zu jedem Element:";
      else
        result+="die zugehrigen Dateien:";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorGerman::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 410 of file translator_de.h.
    {
      QCString result="Hier folgt die Aufzhlung aller ";
      if (!extractAll) result+="dokumentierten ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="Funktionen, Variablen, Makros, Aufzhlungen und Typdefinitionen";
      }
      else
      {
        result+="Dateielemente";
      }
      result+=" mit Verweisen auf ";
      if (extractAll)
        result+="die Dokumentation zu jedem Element:";
      else
        result+="die zugehrigen Dateien:";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorGerman::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 708 of file translator_de.h.
    {
      QCString result=fileName;
      result+="-Dateireferenz";
      return result;
    }
trFileReference() [2/2]
virtual QCString TranslatorGerman::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 708 of file translator_de.h.
    {
      QCString result=fileName;
      result+="-Dateireferenz";
      return result;
    }
trFriends() [1/2]
virtual QCString TranslatorGerman::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 668 of file translator_de.h.
    { return "Freundbeziehungen"; }
trFriends() [2/2]
virtual QCString TranslatorGerman::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 668 of file translator_de.h.
    { return "Freundbeziehungen"; }
trFunctionAndProc() [1/2]
virtual QCString TranslatorGerman::trFunctionAndProc () [inline], [virtual]
VHDL functions/procedures/processes
Reimplemented from TranslatorAdapter_1_8_15.
Definition at line 2170 of file translator_de.h.
    { return "Funktionen/Prozeduren/Prozesse"; }
trFunctionAndProc() [2/2]
virtual QCString TranslatorGerman::trFunctionAndProc () [inline], [virtual]
VHDL functions/procedures/processes
Reimplemented from TranslatorAdapter_1_8_15.
Definition at line 2170 of file translator_de.h.
    { return "Funktionen/Prozeduren/Prozesse"; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorGerman::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 575 of file translator_de.h.
    { return "Dokumentation der Funktionen"; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorGerman::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 575 of file translator_de.h.
    { return "Dokumentation der Funktionen"; }
trFunctions() [1/2]
virtual QCString TranslatorGerman::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 539 of file translator_de.h.
    { return "Funktionen"; }
trFunctions() [2/2]
virtual QCString TranslatorGerman::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 539 of file translator_de.h.
    { return "Funktionen"; }
trGeneratedAt() [1/2]
virtual QCString TranslatorGerman::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 602 of file translator_de.h.
    {
      QCString result="Erzeugt am "+date;
      if (!projName.isEmpty()) result+=" fr "+projName;
      result+=" von";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorGerman::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 602 of file translator_de.h.
    {
      QCString result="Erzeugt am "+date;
      if (!projName.isEmpty()) result+=" fr "+projName;
      result+=" von";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorGerman::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 238 of file translator_de.h.
    { QCString result="Automatisch erzeugt von Doxygen";
      if (!s.isEmpty()) result+=" fr "+s;
      result+=" aus dem Quellcode.";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorGerman::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 238 of file translator_de.h.
    { QCString result="Automatisch erzeugt von Doxygen";
      if (!s.isEmpty()) result+=" fr "+s;
      result+=" aus dem Quellcode.";
      return result;
    }
References s.
trGeneratedBy() [1/2]
virtual QCString TranslatorGerman::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 645 of file translator_de.h.
    { return "Erzeugt von"; }
trGeneratedBy() [2/2]
virtual QCString TranslatorGerman::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 645 of file translator_de.h.
    { return "Erzeugt von"; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorGerman::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 856 of file translator_de.h.
    { // single is true implies a single file
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      QCString result="Die Dokumentation fr diese";
      switch(compType)
      {
        case ClassDef::Class: result+=vhdlOpt?" Entwurfseinheiten":" Klasse"; break;
        case ClassDef::Struct: result+=" Struktur"; break;
        case ClassDef::Union: result+=" Variante"; break;
        case ClassDef::Interface: result+=" Schnittstelle"; break;
        case ClassDef::Protocol: result+="s Protokoll"; break;
        case ClassDef::Category: result+=" Kategorie"; break;
        case ClassDef::Exception: result+=" Ausnahme"; break;
        default: break;
      }
      result+=" wurde erzeugt aufgrund der Datei";
      if (single) result+=":"; else result+="en:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, Config_getBool, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorGerman::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 856 of file translator_de.h.
    { // single is true implies a single file
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      QCString result="Die Dokumentation fr diese";
      switch(compType)
      {
        case ClassDef::Class: result+=vhdlOpt?" Entwurfseinheiten":" Klasse"; break;
        case ClassDef::Struct: result+=" Struktur"; break;
        case ClassDef::Union: result+=" Variante"; break;
        case ClassDef::Interface: result+=" Schnittstelle"; break;
        case ClassDef::Protocol: result+="s Protokoll"; break;
        case ClassDef::Category: result+=" Kategorie"; break;
        case ClassDef::Exception: result+=" Ausnahme"; break;
        default: break;
      }
      result+=" wurde erzeugt aufgrund der Datei";
      if (single) result+=":"; else result+="en:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, Config_getBool, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorGerman::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1822 of file translator_de.h.
    {
      // single is true implies a single file
      QCString result="Die Dokumentation fr ";
      switch(compType)
      {
        case ClassDef::Class: result+="dieses Modul"; break;
        case ClassDef::Struct: result+="diesen Typ"; break;
        case ClassDef::Union: result+="diese Union"; break;
        case ClassDef::Interface: result+="dieses Interface"; break;
        case ClassDef::Protocol: result+="dieses Protokoll"; break;
        case ClassDef::Category: result+="diese Kategorie"; break;
        case ClassDef::Exception: result+="diese Ausnahme"; break;
        default: break;
      }
      if (single)
        result+=" wurde aus der folgenden Datei erzeugt:";
      else
        result+=" wurde aus den folgenden Dateien erzeugt:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorGerman::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1822 of file translator_de.h.
    {
      // single is true implies a single file
      QCString result="Die Dokumentation fr ";
      switch(compType)
      {
        case ClassDef::Class: result+="dieses Modul"; break;
        case ClassDef::Struct: result+="diesen Typ"; break;
        case ClassDef::Union: result+="diese Union"; break;
        case ClassDef::Interface: result+="dieses Interface"; break;
        case ClassDef::Protocol: result+="dieses Protokoll"; break;
        case ClassDef::Category: result+="diese Kategorie"; break;
        case ClassDef::Exception: result+="diese Ausnahme"; break;
        default: break;
      }
      if (single)
        result+=" wurde aus der folgenden Datei erzeugt:";
      else
        result+=" wurde aus den folgenden Dateien erzeugt:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorGerman::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1387 of file translator_de.h.
    {
      QCString result((first_capital ? "Global" : "global")); // FIXME
      if (!singular) result+="";
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorGerman::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1387 of file translator_de.h.
    {
      QCString result((first_capital ? "Global" : "global")); // FIXME
      if (!singular) result+="";
      return result;
    }
trGlobalNamespace() [1/2]
virtual QCString TranslatorGerman::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1890 of file translator_de.h.
    {
      return "Globaler Namensbereich";
    }
trGlobalNamespace() [2/2]
virtual QCString TranslatorGerman::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1890 of file translator_de.h.
    {
      return "Globaler Namensbereich";
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorGerman::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 948 of file translator_de.h.
    {
      return "gehe zur Dokumentation dieser Datei";
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorGerman::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 948 of file translator_de.h.
    {
      return "gehe zur Dokumentation dieser Datei";
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorGerman::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 988 of file translator_de.h.
    {
      return "gehe zur grafischen Darstellung der Klassenhierarchie";
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorGerman::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 988 of file translator_de.h.
    {
      return "gehe zur grafischen Darstellung der Klassenhierarchie";
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorGerman::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 942 of file translator_de.h.
    {
      return "gehe zum Quellcode dieser Datei";
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorGerman::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 942 of file translator_de.h.
    {
      return "gehe zum Quellcode dieser Datei";
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorGerman::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 993 of file translator_de.h.
    {
      return "gehe zur textbasierten Darstellung der Klassenhierarchie";
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorGerman::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 993 of file translator_de.h.
    {
      return "gehe zur textbasierten Darstellung der Klassenhierarchie";
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorGerman::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 983 of file translator_de.h.
    {
      return "Grafische Darstellung der Klassenhierarchie";
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorGerman::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 983 of file translator_de.h.
    {
      return "Grafische Darstellung der Klassenhierarchie";
    }
trGroup() [1/2]
virtual QCString TranslatorGerman::trGroup (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1354 of file translator_de.h.
    {
      QCString result("Gruppe");
      if (!singular) result+="n";
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorGerman::trGroup (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1354 of file translator_de.h.
    {
      QCString result("Gruppe");
      if (!singular) result+="n";
      return result;
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorGerman::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 457 of file translator_de.h.
    { return "Hierarchie-Verzeichnis"; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorGerman::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 457 of file translator_de.h.
    { return "Hierarchie-Verzeichnis"; }
trImplementedFromList() [1/2]
virtual QCString TranslatorGerman::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1426 of file translator_de.h.
    {
      return "Implementiert " + trWriteList(numEntries) + ".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorGerman::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1426 of file translator_de.h.
    {
      return "Implementiert " + trWriteList(numEntries) + ".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorGerman::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1434 of file translator_de.h.
    {
      return "Implementiert in " + trWriteList(numEntries) + ".";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorGerman::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1434 of file translator_de.h.
    {
      return "Implementiert in " + trWriteList(numEntries) + ".";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorGerman::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 1100 of file translator_de.h.
    {
      return "Dieser Graph zeigt, welche Datei direkt oder "
             "indirekt diese Datei enthlt:";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorGerman::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 1100 of file translator_de.h.
    {
      return "Dieser Graph zeigt, welche Datei direkt oder "
             "indirekt diese Datei enthlt:";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorGerman::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 930 of file translator_de.h.
    {
      return "Include-Abhngigkeitsdiagramm fr "+fName+":";
    }
trInclDepGraph() [2/2]
virtual QCString TranslatorGerman::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 930 of file translator_de.h.
    {
      return "Include-Abhngigkeitsdiagramm fr "+fName+":";
    }
trIncludesFileIn() [1/2]
virtual QCString TranslatorGerman::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1924 of file translator_de.h.
    {
      return "Include-Dateien in "+name;
    }
References setup::name.
trIncludesFileIn() [2/2]
virtual QCString TranslatorGerman::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1924 of file translator_de.h.
    {
      return "Include-Dateien in "+name;
    }
References setup::name.
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorGerman::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 232 of file translator_de.h.
    { return " einschlielich aller geerbten Elemente."; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorGerman::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 232 of file translator_de.h.
    { return " einschlielich aller geerbten Elemente."; }
trInheritedByList() [1/2]
virtual QCString TranslatorGerman::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 789 of file translator_de.h.
    {
      return "Basisklasse fr "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorGerman::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 789 of file translator_de.h.
    {
      return "Basisklasse fr "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom() [1/2]
virtual QCString TranslatorGerman::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 2023 of file translator_de.h.
    { return QCString(members)+" geerbt von "+what; }
trInheritedFrom() [2/2]
virtual QCString TranslatorGerman::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 2023 of file translator_de.h.
    { return QCString(members)+" geerbt von "+what; }
trInheritsList() [1/2]
virtual QCString TranslatorGerman::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 781 of file translator_de.h.
    {
      return "Abgeleitet von "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorGerman::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 781 of file translator_de.h.
    {
      return "Abgeleitet von "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorGerman::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 972 of file translator_de.h.
    {
      return "Initialisierung:";
    }
trInitialValue() [2/2]
virtual QCString TranslatorGerman::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 972 of file translator_de.h.
    {
      return "Initialisierung:";
    }
trInstanceMethods() [1/2]
virtual QCString TranslatorGerman::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 2075 of file translator_de.h.
    {
      return "Instanzmethoden";
    }
trInstanceMethods() [2/2]
virtual QCString TranslatorGerman::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 2075 of file translator_de.h.
    {
      return "Instanzmethoden";
    }
trInterfaces() [1/2]
virtual QCString TranslatorGerman::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 2092 of file translator_de.h.
    { return "Exportierte Interfaces"; }
trInterfaces() [2/2]
virtual QCString TranslatorGerman::trInterfaces () [inline], [virtual]
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 2092 of file translator_de.h.
    { return "Exportierte Interfaces"; }
trInvariant() [1/2]
virtual QCString TranslatorGerman::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 966 of file translator_de.h.
    {
      return "Invariante";
    }
trInvariant() [2/2]
virtual QCString TranslatorGerman::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 966 of file translator_de.h.
    {
      return "Invariante";
    }
trISOLang() [1/2]
virtual QCString TranslatorGerman::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 167 of file translator_de.h.
    {
      return "de";
    }
trISOLang() [2/2]
virtual QCString TranslatorGerman::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 167 of file translator_de.h.
    {
      return "de";
    }
trLegend() [1/2]
virtual QCString TranslatorGerman::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1194 of file translator_de.h.
    {
      return "Legende";
    }
trLegend() [2/2]
virtual QCString TranslatorGerman::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1194 of file translator_de.h.
    {
      return "Legende";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorGerman::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 1124 of file translator_de.h.
    {
      return
        "Diese Seite erklrt die Interpretation der von doxygen "
        "erzeugten Graphen.<p>\n"
        "Beispiel:\n"
        "\\code\n"
        "/*! Wegen Verkrzung unsichtbare Klasse */\n"
        "class Invisible { };\n\n"
        "/*! Klasse verkrzt dargestellt, Vererbungsbeziehung ist versteckt */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Nicht mit doxygen-Kommentaren dokumentierte Klasse */\n"
        "class Undocumented { };\n\n"
        "/*! Mithilfe ffentlicher Vererbung vererbte Klasse */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! Eine Template-Klasse */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Mithilfe geschtzter Vererbung vererbte Klasse */\n"
        "class ProtectedBase { };\n\n"
        "/*! Mithilfe privater Vererbung vererbte Klasse */\n"
        "class PrivateBase { };\n\n"
        "/*! Von der Klasse Inherited benutzte Klasse */\n"
        "class Used { };\n\n"
        "/*! Superklasse, die von mehreren anderen Klassen erbt */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Dies liefert den folgenden Graphen:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        "Die Rechtecke in obigem Graphen bedeuten:\n"
        "</p>\n"
        "<ul>\n"
        "<li>Ein grau geflltes Rechteck stellt die Struktur oder "
        "Klasse dar, fr die der Graph erzeugt wurde.</li>\n"
        "<li>Ein Rechteck mit schwarzem Rahmen kennzeichnet eine dokumentierte "
        "Struktur oder Klasse.</li>\n"
        "<li>Ein Rechteck mit grauem Rahmen kennzeichnet eine undokumentierte "
        "Struktur oder Klasse.</li>\n"
        "<li>Ein Rechteck mit rotem Rahmen kennzeichnet eine dokumentierte "
        "Struktur oder Klasse, fr die nicht alle Vererbungs-/"
        "Enthaltenseinsbeziehungen dargestellt werden. Ein Graph wird gekrzt, "
        "wenn er nicht in die angegebenen Schranken passt.</li>\n"
        "</ul>\n"
        "<p>\n"
        "Die Pfeile bedeuten:\n"
        "</p>\n"
        "<ul>\n"
        "<li>Ein blauer Pfeil stellt eine ffentliche Vererbungsbeziehung "
        "zwischen zwei Klassen dar.</li>\n"
        "<li>Ein dunkelgrner Pfeil stellt geschtzte Vererbung dar.</li>\n"
        "<li>Ein dunkelroter Pfeil stellt private Vererbung dar.</li>\n"
        "<li>Ein gestrichelter violetter Pfeil bedeutet, dass eine Klasse in "
        "einer anderen enthalten ist oder von einer anderen benutzt wird. Am "
        "Pfeil stehen die Variable(n), mit deren Hilfe auf die Struktur oder "
        "Klasse an der Pfeilspitze zugegriffen werden kann.</li>\n"
        "<li>Ein gestrichelter gelber Pfeil kennzeichnet eine Verknpfung "
        "zwischen einer Template-Instanz und der Template-Klasse von welcher "
        "es abstammt. Neben dem Pfeil sind die Template-Parameter aufgefhrt.</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorGerman::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 1124 of file translator_de.h.
    {
      return
        "Diese Seite erklrt die Interpretation der von doxygen "
        "erzeugten Graphen.<p>\n"
        "Beispiel:\n"
        "\\code\n"
        "/*! Wegen Verkrzung unsichtbare Klasse */\n"
        "class Invisible { };\n\n"
        "/*! Klasse verkrzt dargestellt, Vererbungsbeziehung ist versteckt */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Nicht mit doxygen-Kommentaren dokumentierte Klasse */\n"
        "class Undocumented { };\n\n"
        "/*! Mithilfe ffentlicher Vererbung vererbte Klasse */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! Eine Template-Klasse */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Mithilfe geschtzter Vererbung vererbte Klasse */\n"
        "class ProtectedBase { };\n\n"
        "/*! Mithilfe privater Vererbung vererbte Klasse */\n"
        "class PrivateBase { };\n\n"
        "/*! Von der Klasse Inherited benutzte Klasse */\n"
        "class Used { };\n\n"
        "/*! Superklasse, die von mehreren anderen Klassen erbt */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Dies liefert den folgenden Graphen:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center></p>\n"
        "<p>\n"
        "Die Rechtecke in obigem Graphen bedeuten:\n"
        "</p>\n"
        "<ul>\n"
        "<li>Ein grau geflltes Rechteck stellt die Struktur oder "
        "Klasse dar, fr die der Graph erzeugt wurde.</li>\n"
        "<li>Ein Rechteck mit schwarzem Rahmen kennzeichnet eine dokumentierte "
        "Struktur oder Klasse.</li>\n"
        "<li>Ein Rechteck mit grauem Rahmen kennzeichnet eine undokumentierte "
        "Struktur oder Klasse.</li>\n"
        "<li>Ein Rechteck mit rotem Rahmen kennzeichnet eine dokumentierte "
        "Struktur oder Klasse, fr die nicht alle Vererbungs-/"
        "Enthaltenseinsbeziehungen dargestellt werden. Ein Graph wird gekrzt, "
        "wenn er nicht in die angegebenen Schranken passt.</li>\n"
        "</ul>\n"
        "<p>\n"
        "Die Pfeile bedeuten:\n"
        "</p>\n"
        "<ul>\n"
        "<li>Ein blauer Pfeil stellt eine ffentliche Vererbungsbeziehung "
        "zwischen zwei Klassen dar.</li>\n"
        "<li>Ein dunkelgrner Pfeil stellt geschtzte Vererbung dar.</li>\n"
        "<li>Ein dunkelroter Pfeil stellt private Vererbung dar.</li>\n"
        "<li>Ein gestrichelter violetter Pfeil bedeutet, dass eine Klasse in "
        "einer anderen enthalten ist oder von einer anderen benutzt wird. Am "
        "Pfeil stehen die Variable(n), mit deren Hilfe auf die Struktur oder "
        "Klasse an der Pfeilspitze zugegriffen werden kann.</li>\n"
        "<li>Ein gestrichelter gelber Pfeil kennzeichnet eine Verknpfung "
        "zwischen einer Template-Instanz und der Template-Klasse von welcher "
        "es abstammt. Neben dem Pfeil sind die Template-Parameter aufgefhrt.</li>\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorGerman::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 1116 of file translator_de.h.
    {
      return "Erklrung des Graphen";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorGerman::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 1116 of file translator_de.h.
    {
      return "Erklrung des Graphen";
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorGerman::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 220 of file translator_de.h.
    { return "Aufstellung aller Elemente"; }
trListOfAllMembers() [2/2]
virtual QCString TranslatorGerman::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 220 of file translator_de.h.
    { return "Aufstellung aller Elemente"; }
trLoading() [1/2]
virtual QCString TranslatorGerman::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1884 of file translator_de.h.
    {
      return "Lade ...";
    }
trLoading() [2/2]
virtual QCString TranslatorGerman::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1884 of file translator_de.h.
    {
      return "Lade ...";
    }
trMainPage() [1/2]
virtual QCString TranslatorGerman::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 887 of file translator_de.h.
    { return "Hauptseite"; }
trMainPage() [2/2]
virtual QCString TranslatorGerman::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 887 of file translator_de.h.
    { return "Hauptseite"; }
trMember() [1/2]
virtual QCString TranslatorGerman::trMember (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1376 of file translator_de.h.
    {
      QCString result("Element");
      if (!singular) result+="e";
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorGerman::trMember (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1376 of file translator_de.h.
    {
      QCString result("Element");
      if (!singular) result+="e";
      return result;
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorGerman::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 203 of file translator_de.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentation der Felder";
      }
      else
      {
        return "Dokumentation der Datenelemente";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorGerman::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 203 of file translator_de.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Dokumentation der Felder";
      }
      else
      {
        return "Dokumentation der Datenelemente";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorGerman::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 195 of file translator_de.h.
    { return "Dokumentation der Aufzhlungstypen"; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorGerman::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 195 of file translator_de.h.
    { return "Dokumentation der Aufzhlungstypen"; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorGerman::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 199 of file translator_de.h.
    { return "Dokumentation der Elementfunktionen"; }
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorGerman::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 199 of file translator_de.h.
    { return "Dokumentation der Elementfunktionen"; }
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorGerman::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1672 of file translator_de.h.
    { return "Elementfunktionen/Unterroutinen-Dokumentation"; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorGerman::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1672 of file translator_de.h.
    { return "Elementfunktionen/Unterroutinen-Dokumentation"; }
trMemberList() [1/2]
virtual QCString TranslatorGerman::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 224 of file translator_de.h.
    { return "Elementverzeichnis"; }
trMemberList() [2/2]
virtual QCString TranslatorGerman::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 224 of file translator_de.h.
    { return "Elementverzeichnis"; }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorGerman::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 191 of file translator_de.h.
    { return "Dokumentation der benutzerdefinierten Datentypen"; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorGerman::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 191 of file translator_de.h.
    { return "Dokumentation der benutzerdefinierten Datentypen"; }
trMethodDocumentation() [1/2]
virtual QCString TranslatorGerman::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 2082 of file translator_de.h.
    {
      return "Methodendokumentation";
    }
trMethodDocumentation() [2/2]
virtual QCString TranslatorGerman::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 2082 of file translator_de.h.
    {
      return "Methodendokumentation";
    }
trModule() [1/2]
virtual QCString TranslatorGerman::trModule (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1812 of file translator_de.h.
    {
      QCString result("Modul");
      if (!singular) result+="e";
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorGerman::trModule (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1812 of file translator_de.h.
    {
      QCString result("Modul");
      if (!singular) result+="e";
      return result;
    }
trModuleDocumentation() [1/2]
virtual QCString TranslatorGerman::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 480 of file translator_de.h.
    { return "Modul-Dokumentation"; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorGerman::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 480 of file translator_de.h.
    { return "Modul-Dokumentation"; }
trModuleIndex() [1/2]
virtual QCString TranslatorGerman::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 451 of file translator_de.h.
    { return "Modul-Verzeichnis"; }
trModuleIndex() [2/2]
virtual QCString TranslatorGerman::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 451 of file translator_de.h.
    { return "Modul-Verzeichnis"; }
trModuleReference() [1/2]
virtual QCString TranslatorGerman::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1774 of file translator_de.h.
    {
      QCString result=namespaceName;
      result+="-Modul-Referenz";
      return result;
    }
trModuleReference() [2/2]
virtual QCString TranslatorGerman::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1774 of file translator_de.h.
    {
      QCString result=namespaceName;
      result+="-Modul-Referenz";
      return result;
    }
trModules() [1/2]
virtual QCString TranslatorGerman::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 262 of file translator_de.h.
    { return "Module"; }
trModules() [2/2]
virtual QCString TranslatorGerman::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 262 of file translator_de.h.
    { return "Module"; }
trModulesDescription() [1/2]
virtual QCString TranslatorGerman::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 439 of file translator_de.h.
    { return "Hier folgt die Aufzhlung aller Module:"; }
trModulesDescription() [2/2]
virtual QCString TranslatorGerman::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 439 of file translator_de.h.
    { return "Hier folgt die Aufzhlung aller Module:"; }
trModulesIndex() [1/2]
virtual QCString TranslatorGerman::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1805 of file translator_de.h.
    { return "Modul-Index"; }
trModulesIndex() [2/2]
virtual QCString TranslatorGerman::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1805 of file translator_de.h.
    { return "Modul-Index"; }
trModulesList() [1/2]
virtual QCString TranslatorGerman::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1739 of file translator_de.h.
    { return "Modulliste"; }
trModulesList() [2/2]
virtual QCString TranslatorGerman::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1739 of file translator_de.h.
    { return "Modulliste"; }
trModulesListDescription() [1/2]
virtual QCString TranslatorGerman::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1743 of file translator_de.h.
    {
      QCString result="Hier folgt eine Liste aller ";
      if (!extractAll) result+="dokumentierten ";
      result+="Module mit ihren Kurzbeschreibungen:";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorGerman::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1743 of file translator_de.h.
    {
      QCString result="Hier folgt eine Liste aller ";
      if (!extractAll) result+="dokumentierten ";
      result+="Module mit ihren Kurzbeschreibungen:";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorGerman::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1786 of file translator_de.h.
    {
      QCString result="Hier folgt eine Liste aller ";
      if (!extractAll) result+="dokumentierten ";
      result+="Modulelemente mit Links ";
      if (extractAll)
      {
        result+="zur Moduldokumentation fr jedes Element:";
      }
      else
      {
        result+="zu den Modulen, zu denen sie gehren:";
      }
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorGerman::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1786 of file translator_de.h.
    {
      QCString result="Hier folgt eine Liste aller ";
      if (!extractAll) result+="dokumentierten ";
      result+="Modulelemente mit Links ";
      if (extractAll)
      {
        result+="zur Moduldokumentation fr jedes Element:";
      }
      else
      {
        result+="zu den Modulen, zu denen sie gehren:";
      }
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorGerman::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1782 of file translator_de.h.
    { return "Modul-Elemente"; }
trModulesMembers() [2/2]
virtual QCString TranslatorGerman::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1782 of file translator_de.h.
    { return "Modul-Elemente"; }
trMonth() [1/2]
virtual QCString TranslatorGerman::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1962 of file translator_de.h.
    {
      static const char *months_short[] = { "Jan", "Feb", "Mrz", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dez" };
      static const char *months_full[] = { "Januar", "Februar", "Mrz", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      return text;
    }
trMonth() [2/2]
virtual QCString TranslatorGerman::trMonth (int month, bool , bool full) [inline], [virtual]
Implements Translator.
Definition at line 1962 of file translator_de.h.
    {
      static const char *months_short[] = { "Jan", "Feb", "Mrz", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dez" };
      static const char *months_full[] = { "Januar", "Februar", "Mrz", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      return text;
    }
trMore() [1/2]
virtual QCString TranslatorGerman::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 216 of file translator_de.h.
    { return "Mehr ..."; }
trMore() [2/2]
virtual QCString TranslatorGerman::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 216 of file translator_de.h.
    { return "Mehr ..."; }
trNamespace() [1/2]
virtual QCString TranslatorGerman::trNamespace (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1343 of file translator_de.h.
    {
      QCString result("Namensbereich");
      if (!singular) result+="e";
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorGerman::trNamespace (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1343 of file translator_de.h.
    {
      QCString result("Namensbereich");
      if (!singular) result+="e";
      return result;
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorGerman::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 836 of file translator_de.h.
    { return "Dokumentation der Namensbereiche"; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorGerman::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 836 of file translator_de.h.
    { return "Dokumentation der Namensbereiche"; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorGerman::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 830 of file translator_de.h.
    { return "Verzeichnis der Namensbereiche"; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorGerman::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 830 of file translator_de.h.
    { return "Verzeichnis der Namensbereiche"; }
trNamespaceList() [1/2]
virtual QCString TranslatorGerman::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 653 of file translator_de.h.
    { return "Liste aller Namensbereiche"; }
trNamespaceList() [2/2]
virtual QCString TranslatorGerman::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 653 of file translator_de.h.
    { return "Liste aller Namensbereiche"; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorGerman::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 657 of file translator_de.h.
    {
      QCString result="Liste aller ";
      if (!extractAll) result+="dokumentierten ";
      result+="Namensbereiche mit Kurzbeschreibung:";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorGerman::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 657 of file translator_de.h.
    {
      QCString result="Liste aller ";
      if (!extractAll) result+="dokumentierten ";
      result+="Namensbereiche mit Kurzbeschreibung:";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorGerman::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 815 of file translator_de.h.
    {
      QCString result="Hier folgt die Aufzhlung aller ";
      if (!extractAll) result+="dokumentierten ";
      result+="Namensbereichselemente mit Verweisen auf ";
      if (extractAll)
        result+="die Namensbereichsdokumentation fr jedes Element:";
      else
        result+="die zugehrigen Dateien:";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorGerman::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 815 of file translator_de.h.
    {
      QCString result="Hier folgt die Aufzhlung aller ";
      if (!extractAll) result+="dokumentierten ";
      result+="Namensbereichselemente mit Verweisen auf ";
      if (extractAll)
        result+="die Namensbereichsdokumentation fr jedes Element:";
      else
        result+="die zugehrigen Dateien:";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorGerman::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 811 of file translator_de.h.
    { return "Elemente eines Namensbereiches"; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorGerman::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 811 of file translator_de.h.
    { return "Elemente eines Namensbereiches"; }
trNamespaceReference() [1/2]
virtual QCString TranslatorGerman::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 716 of file translator_de.h.
    {
      QCString result=namespaceName;
      result+="-Namensbereichsreferenz";
      return result;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorGerman::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 716 of file translator_de.h.
    {
      QCString result=namespaceName;
      result+="-Namensbereichsreferenz";
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorGerman::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 846 of file translator_de.h.
    { return "Namensbereiche"; }
trNamespaces() [2/2]
virtual QCString TranslatorGerman::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 846 of file translator_de.h.
    { return "Namensbereiche"; }
trNoMatches() [1/2]
virtual QCString TranslatorGerman::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1902 of file translator_de.h.
    {
      return "Keine Treffer";
    }
trNoMatches() [2/2]
virtual QCString TranslatorGerman::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1902 of file translator_de.h.
    {
      return "Keine Treffer";
    }
trNote() [1/2]
virtual QCString TranslatorGerman::trNote () [inline], [virtual]
Implements Translator.
Definition at line 1008 of file translator_de.h.
    {
      return "Zu beachten";
    }
trNote() [2/2]
virtual QCString TranslatorGerman::trNote () [inline], [virtual]
Implements Translator.
Definition at line 1008 of file translator_de.h.
    {
      return "Zu beachten";
    }
trOverloadText() [1/2]
virtual QCString TranslatorGerman::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1644 of file translator_de.h.
    {
       return "Dies ist eine berladene Methode, die der Bequemlichkeit "
              "wegen bereitgestellt wird. Sie unterscheidet sich von der "
              "obigen Funktion nur in den Argumenten die sie untersttzt.";
    }
trOverloadText() [2/2]
virtual QCString TranslatorGerman::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1644 of file translator_de.h.
    {
       return "Dies ist eine berladene Methode, die der Bequemlichkeit "
              "wegen bereitgestellt wird. Sie unterscheidet sich von der "
              "obigen Funktion nur in den Argumenten die sie untersttzt.";
    }
trPackage() [1/2]
virtual QCString TranslatorGerman::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1249 of file translator_de.h.
    {
      return "Paket "+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorGerman::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1249 of file translator_de.h.
    {
      return "Paket "+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorGerman::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1515 of file translator_de.h.
    {
      return "Paketattribute";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorGerman::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1515 of file translator_de.h.
    {
      return "Paketattribute";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorGerman::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1495 of file translator_de.h.
    {
      return "Paketfunktionen";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorGerman::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1495 of file translator_de.h.
    {
      return "Paketfunktionen";
    }
trPackageListDescription() [1/2]
virtual QCString TranslatorGerman::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1256 of file translator_de.h.
    {
      return "Hier folgen die Pakete mit einer Kurzbeschreibung (wenn verfgbar):";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorGerman::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1256 of file translator_de.h.
    {
      return "Hier folgen die Pakete mit einer Kurzbeschreibung (wenn verfgbar):";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorGerman::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1499 of file translator_de.h.
    {
      return "Paketelemente";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorGerman::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1499 of file translator_de.h.
    {
      return "Paketelemente";
    }
trPackages() [1/2]
virtual QCString TranslatorGerman::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1262 of file translator_de.h.
    {
      return "Pakete";
    }
trPackages() [2/2]
virtual QCString TranslatorGerman::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1262 of file translator_de.h.
    {
      return "Pakete";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorGerman::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1487 of file translator_de.h.
    {
      return "Pakettypen";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorGerman::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1487 of file translator_de.h.
    {
      return "Pakettypen";
    }
trPage() [1/2]
virtual QCString TranslatorGerman::trPage (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1365 of file translator_de.h.
    {
      QCString result("Seite");
      if (!singular) result+="n";
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorGerman::trPage (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1365 of file translator_de.h.
    {
      QCString result("Seite");
      if (!singular) result+="n";
      return result;
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorGerman::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 893 of file translator_de.h.
    { return "S."; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorGerman::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 893 of file translator_de.h.
    { return "S."; }
trPageIndex() [1/2]
virtual QCString TranslatorGerman::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 998 of file translator_de.h.
    {
      return "Seitenindex";
    }
trPageIndex() [2/2]
virtual QCString TranslatorGerman::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 998 of file translator_de.h.
    {
      return "Seitenindex";
    }
trPanelSynchronisationTooltip() [1/2]
virtual QCString TranslatorGerman::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button thatappears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 2040 of file translator_de.h.
    {
      QCString opt = enable ? "einzuschalten" : "auszuschalten";
      return "Klicken um Panelsynchronisation "+opt;
    }
trPanelSynchronisationTooltip() [2/2]
virtual QCString TranslatorGerman::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button thatappears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 2040 of file translator_de.h.
    {
      QCString opt = enable ? "einzuschalten" : "auszuschalten";
      return "Klicken um Panelsynchronisation "+opt;
    }
trParameters() [1/2]
virtual QCString TranslatorGerman::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 637 of file translator_de.h.
    { return "Parameter"; }
trParameters() [2/2]
virtual QCString TranslatorGerman::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 637 of file translator_de.h.
    { return "Parameter"; }
trPostcondition() [1/2]
virtual QCString TranslatorGerman::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 960 of file translator_de.h.
    {
      return "Nachbedingung";
    }
trPostcondition() [2/2]
virtual QCString TranslatorGerman::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 960 of file translator_de.h.
    {
      return "Nachbedingung";
    }
trPrecondition() [1/2]
virtual QCString TranslatorGerman::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 954 of file translator_de.h.
    {
      return "Vorbedingung";
    }
trPrecondition() [2/2]
virtual QCString TranslatorGerman::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 954 of file translator_de.h.
    {
      return "Vorbedingung";
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorGerman::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1055 of file translator_de.h.
    {
      return "Private Attribute";
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorGerman::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1055 of file translator_de.h.
    {
      return "Private Attribute";
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorGerman::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 744 of file translator_de.h.
    { return "Private Methoden"; }
trPrivateMembers() [2/2]
virtual QCString TranslatorGerman::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 744 of file translator_de.h.
    { return "Private Methoden"; }
trPrivateSlots() [1/2]
virtual QCString TranslatorGerman::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 747 of file translator_de.h.
    { return "Private Slots"; }
trPrivateSlots() [2/2]
virtual QCString TranslatorGerman::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 747 of file translator_de.h.
    { return "Private Slots"; }
trPrivateTypes() [1/2]
virtual QCString TranslatorGerman::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 1050 of file translator_de.h.
    {
      return "Private Typen";
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorGerman::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 1050 of file translator_de.h.
    {
      return "Private Typen";
    }
trProperties() [1/2]
virtual QCString TranslatorGerman::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1220 of file translator_de.h.
    {
      return "Propertys";
    }
trProperties() [2/2]
virtual QCString TranslatorGerman::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1220 of file translator_de.h.
    {
      return "Propertys";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorGerman::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1226 of file translator_de.h.
    {
      return "Dokumentation der Propertys";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorGerman::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1226 of file translator_de.h.
    {
      return "Dokumentation der Propertys";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorGerman::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1040 of file translator_de.h.
    {
      return "Geschtzte Attribute";
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorGerman::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1040 of file translator_de.h.
    {
      return "Geschtzte Attribute";
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorGerman::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 735 of file translator_de.h.
    { return "Geschtzte Methoden"; }
trProtectedMembers() [2/2]
virtual QCString TranslatorGerman::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 735 of file translator_de.h.
    { return "Geschtzte Methoden"; }
trProtectedSlots() [1/2]
virtual QCString TranslatorGerman::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 738 of file translator_de.h.
    { return "Geschtzte Slots"; }
trProtectedSlots() [2/2]
virtual QCString TranslatorGerman::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 738 of file translator_de.h.
    { return "Geschtzte Slots"; }
trProtectedTypes() [1/2]
virtual QCString TranslatorGerman::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 1035 of file translator_de.h.
    {
      return "Geschtzte Typen";
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorGerman::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 1035 of file translator_de.h.
    {
      return "Geschtzte Typen";
    }
trProvidedByCategory() [1/2]
virtual QCString TranslatorGerman::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 2050 of file translator_de.h.
    {
      return "Bestandteil der Kategorie @0.";
    }
trProvidedByCategory() [2/2]
virtual QCString TranslatorGerman::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 2050 of file translator_de.h.
    {
      return "Bestandteil der Kategorie @0.";
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorGerman::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1018 of file translator_de.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datenfelder";
      }
      else
      {
        return "ffentliche Attribute";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorGerman::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1018 of file translator_de.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datenfelder";
      }
      else
      {
        return "ffentliche Attribute";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorGerman::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 723 of file translator_de.h.
    { return "ffentliche Methoden"; }
trPublicMembers() [2/2]
virtual QCString TranslatorGerman::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 723 of file translator_de.h.
    { return "ffentliche Methoden"; }
trPublicSlots() [1/2]
virtual QCString TranslatorGerman::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 726 of file translator_de.h.
    { return "ffentliche Slots"; }
trPublicSlots() [2/2]
virtual QCString TranslatorGerman::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 726 of file translator_de.h.
    { return "ffentliche Slots"; }
trPublicTypes() [1/2]
virtual QCString TranslatorGerman::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 1013 of file translator_de.h.
    {
      return "ffentliche Typen";
    }
trPublicTypes() [2/2]
virtual QCString TranslatorGerman::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 1013 of file translator_de.h.
    {
      return "ffentliche Typen";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorGerman::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 1085 of file translator_de.h.
    {
      return "Wird benutzt von";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorGerman::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 1085 of file translator_de.h.
    {
      return "Wird benutzt von";
    }
trReferenceManual() [1/2]
virtual QCString TranslatorGerman::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 515 of file translator_de.h.
    { return "Nachschlagewerk"; }
trReferenceManual() [2/2]
virtual QCString TranslatorGerman::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 515 of file translator_de.h.
    { return "Nachschlagewerk"; }
trReferences() [1/2]
virtual QCString TranslatorGerman::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1414 of file translator_de.h.
    {
      return "Benutzt";
    }
trReferences() [2/2]
virtual QCString TranslatorGerman::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1414 of file translator_de.h.
    {
      return "Benutzt";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorGerman::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 797 of file translator_de.h.
    {
      return "Erneute Implementation von "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorGerman::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 797 of file translator_de.h.
    {
      return "Erneute Implementation von "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorGerman::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 805 of file translator_de.h.
    {
      return "Erneute Implementation in "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorGerman::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 805 of file translator_de.h.
    {
      return "Erneute Implementation in "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorGerman::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 678 of file translator_de.h.
    { return "Freundbeziehungen und Funktionsdokumentation"; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorGerman::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 678 of file translator_de.h.
    { return "Freundbeziehungen und Funktionsdokumentation"; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorGerman::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 179 of file translator_de.h.
    { return "Verwandte Funktionen"; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorGerman::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 179 of file translator_de.h.
    { return "Verwandte Funktionen"; }
trRelatedPages() [1/2]
virtual QCString TranslatorGerman::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 313 of file translator_de.h.
    { return "Zustzliche Informationen"; }
trRelatedPages() [2/2]
virtual QCString TranslatorGerman::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 313 of file translator_de.h.
    { return "Zustzliche Informationen"; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorGerman::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 435 of file translator_de.h.
    { return "Hier folgt eine Liste mit zusammengehrigen Themengebieten:"; }
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorGerman::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 435 of file translator_de.h.
    { return "Hier folgt eine Liste mit zusammengehrigen Themengebieten:"; }
trRelatedSubscript() [1/2]
virtual QCString TranslatorGerman::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 183 of file translator_de.h.
    { return "(Es handelt sich hierbei nicht um Elementfunktionen.)"; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorGerman::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 183 of file translator_de.h.
    { return "(Es handelt sich hierbei nicht um Elementfunktionen.)"; }
trRemarks() [1/2]
virtual QCString TranslatorGerman::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 1090 of file translator_de.h.
    {
      return "Bemerkungen";
    }
trRemarks() [2/2]
virtual QCString TranslatorGerman::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 1090 of file translator_de.h.
    {
      return "Bemerkungen";
    }
trReturns() [1/2]
virtual QCString TranslatorGerman::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 629 of file translator_de.h.
    { return "Rckgabe"; }
trReturns() [2/2]
virtual QCString TranslatorGerman::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 629 of file translator_de.h.
    { return "Rckgabe"; }
trReturnValues() [1/2]
virtual QCString TranslatorGerman::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 882 of file translator_de.h.
    { return "Rckgabewerte"; }
trReturnValues() [2/2]
virtual QCString TranslatorGerman::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 882 of file translator_de.h.
    { return "Rckgabewerte"; }
trRTFansicp() [1/2]
virtual QCString TranslatorGerman::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file. See translator_en.h for details.
Implements Translator.
Definition at line 1294 of file translator_de.h.
    {
      return "1252";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorGerman::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file. See translator_en.h for details.
Implements Translator.
Definition at line 1294 of file translator_de.h.
    {
      return "1252";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorGerman::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1302 of file translator_de.h.
    {
      return "0";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorGerman::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1302 of file translator_de.h.
    {
      return "0";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorGerman::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1308 of file translator_de.h.
    {
      return "Index";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorGerman::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1308 of file translator_de.h.
    {
      return "Index";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorGerman::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1446 of file translator_de.h.
    {
      return "Inhaltsverzeichnis";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorGerman::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1446 of file translator_de.h.
    {
      return "Inhaltsverzeichnis";
    }
trSearch() [1/2]
virtual QCString TranslatorGerman::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 321 of file translator_de.h.
    { return "Suchen"; }
trSearch() [2/2]
virtual QCString TranslatorGerman::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 321 of file translator_de.h.
    { return "Suchen"; }
trSearching() [1/2]
virtual QCString TranslatorGerman::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1896 of file translator_de.h.
    {
      return "Suche ...";
    }
trSearching() [2/2]
virtual QCString TranslatorGerman::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1896 of file translator_de.h.
    {
      return "Suche ...";
    }
trSearchMatches() [1/2]
virtual QCString TranslatorGerman::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1583 of file translator_de.h.
    {
      return "Treffer:";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorGerman::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1583 of file translator_de.h.
    {
      return "Treffer:";
    }
trSearchResults() [1/2]
virtual QCString TranslatorGerman::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1564 of file translator_de.h.
    {
      if (numDocuments==0)
      {
        return "Es wurden keine Dokumente zu Ihrer Suchanfrage gefunden.";
      }
      else if (numDocuments==1)
      {
        return "Es wurde <b>1</b> Dokument zu Ihrer Suchanfrage gefunden.";
      }
      else
      {
        return "Es wurden <b>$num</b> Dokumente zu Ihrer Suchanfrage "
           "gefunden. Die besten Treffer werden zuerst angezeigt.";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorGerman::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1564 of file translator_de.h.
    {
      if (numDocuments==0)
      {
        return "Es wurden keine Dokumente zu Ihrer Suchanfrage gefunden.";
      }
      else if (numDocuments==1)
      {
        return "Es wurde <b>1</b> Dokument zu Ihrer Suchanfrage gefunden.";
      }
      else
      {
        return "Es wurden <b>$num</b> Dokumente zu Ihrer Suchanfrage "
           "gefunden. Die besten Treffer werden zuerst angezeigt.";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorGerman::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1552 of file translator_de.h.
    {
      return "Suchergebnisse";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorGerman::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1552 of file translator_de.h.
    {
      return "Suchergebnisse";
    }
trSeeAlso() [1/2]
virtual QCString TranslatorGerman::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 633 of file translator_de.h.
    { return "Siehe auch"; }
trSeeAlso() [2/2]
virtual QCString TranslatorGerman::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 633 of file translator_de.h.
    { return "Siehe auch"; }
trServiceGeneratedFromFiles() [1/2]
virtual QCString TranslatorGerman::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 2128 of file translator_de.h.
    {
      QCString result="Die Dokumentation fr diesen Dienst "
                                "wurde generiert aus ";
      if (single) result+="folgender Datei: "; else result+="folgenden Dateien: ";
      return result;
    }
trServiceGeneratedFromFiles() [2/2]
virtual QCString TranslatorGerman::trServiceGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL service page
Implements Translator.
Definition at line 2128 of file translator_de.h.
    {
      QCString result="Die Dokumentation fr diesen Dienst "
                                "wurde generiert aus ";
      if (single) result+="folgender Datei: "; else result+="folgenden Dateien: ";
      return result;
    }
trServiceReference() [1/2]
virtual QCString TranslatorGerman::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 2112 of file translator_de.h.
    {
      QCString result=sName;
      result+=" Dienstreferenz";
      return result;
    }
trServiceReference() [2/2]
virtual QCString TranslatorGerman::trServiceReference (const QCString & sName) [inline], [virtual]
UNO IDL service page title
Implements Translator.
Definition at line 2112 of file translator_de.h.
    {
      QCString result=sName;
      result+=" Dienstreferenz";
      return result;
    }
trServices() [1/2]
virtual QCString TranslatorGerman::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 2096 of file translator_de.h.
    { return "Eingebundene Dienste"; }
trServices() [2/2]
virtual QCString TranslatorGerman::trServices () [inline], [virtual]
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 2096 of file translator_de.h.
    { return "Eingebundene Dienste"; }
trSignals() [1/2]
virtual QCString TranslatorGerman::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 729 of file translator_de.h.
    { return "Signale"; }
trSignals() [2/2]
virtual QCString TranslatorGerman::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 729 of file translator_de.h.
    { return "Signale"; }
trSince() [1/2]
virtual QCString TranslatorGerman::trSince () [inline], [virtual]
Implements Translator.
Definition at line 1106 of file translator_de.h.
    {
      return "Seit";
    }
trSince() [2/2]
virtual QCString TranslatorGerman::trSince () [inline], [virtual]
Implements Translator.
Definition at line 1106 of file translator_de.h.
    {
      return "Seit";
    }
trSingletonGeneratedFromFiles() [1/2]
virtual QCString TranslatorGerman::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 2137 of file translator_de.h.
    {
      QCString result="Die Dokumentation fr diesen Singleton wurde generiert aus ";
      if (single) result+="folgender Datei:"; else result+="folgenden Dateien:";
      return result;
    }
trSingletonGeneratedFromFiles() [2/2]
virtual QCString TranslatorGerman::trSingletonGeneratedFromFiles (bool single) [inline], [virtual]
UNO IDL singleton page
Implements Translator.
Definition at line 2137 of file translator_de.h.
    {
      QCString result="Die Dokumentation fr diesen Singleton wurde generiert aus ";
      if (single) result+="folgender Datei:"; else result+="folgenden Dateien:";
      return result;
    }
trSingletonReference() [1/2]
virtual QCString TranslatorGerman::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 2120 of file translator_de.h.
    {
      QCString result=sName;
      result+=" Singleton-Referenz";
      return result;
    }
trSingletonReference() [2/2]
virtual QCString TranslatorGerman::trSingletonReference (const QCString & sName) [inline], [virtual]
UNO IDL singleton page title
Implements Translator.
Definition at line 2120 of file translator_de.h.
    {
      QCString result=sName;
      result+=" Singleton-Referenz";
      return result;
    }
trSourceFile() [1/2]
virtual QCString TranslatorGerman::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1594 of file translator_de.h.
    {
      return filename + " Quellcode";
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorGerman::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1594 of file translator_de.h.
    {
      return filename + " Quellcode";
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorGerman::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1523 of file translator_de.h.
    {
      return "Statische Paketattribute";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorGerman::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1523 of file translator_de.h.
    {
      return "Statische Paketattribute";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorGerman::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1507 of file translator_de.h.
    {
      return "Statische Paketfunktionen";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorGerman::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1507 of file translator_de.h.
    {
      return "Statische Paketfunktionen";
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorGerman::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1060 of file translator_de.h.
    {
      return "Statische, private Attribute";
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorGerman::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1060 of file translator_de.h.
    {
      return "Statische, private Attribute";
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorGerman::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 750 of file translator_de.h.
    { return "Private, statische Methoden"; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorGerman::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 750 of file translator_de.h.
    { return "Private, statische Methoden"; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorGerman::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1045 of file translator_de.h.
    {
      return "Statische, geschtzte Attribute";
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorGerman::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1045 of file translator_de.h.
    {
      return "Statische, geschtzte Attribute";
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorGerman::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 741 of file translator_de.h.
    { return "Geschtzte, statische Methoden"; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorGerman::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 741 of file translator_de.h.
    { return "Geschtzte, statische Methoden"; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorGerman::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1030 of file translator_de.h.
    {
      return "Statische ffentliche Attribute";
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorGerman::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 1030 of file translator_de.h.
    {
      return "Statische ffentliche Attribute";
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorGerman::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 732 of file translator_de.h.
    { return "ffentliche, statische Methoden"; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorGerman::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 732 of file translator_de.h.
    { return "ffentliche, statische Methoden"; }
trSubprogram() [1/2]
virtual QCString TranslatorGerman::trSubprogram (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1860 of file translator_de.h.
    {
      QCString result("Unterprogramm");
      if (!singular) result+="e";
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorGerman::trSubprogram (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1860 of file translator_de.h.
    {
      QCString result("Unterprogramm");
      if (!singular) result+="e";
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorGerman::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1729 of file translator_de.h.
    { return "Funktionen/Unterroutinen-Dokumentation"; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorGerman::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1729 of file translator_de.h.
    { return "Funktionen/Unterroutinen-Dokumentation"; }
trSubprograms() [1/2]
virtual QCString TranslatorGerman::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1723 of file translator_de.h.
    { return "Funktionen/Unterroutinen"; }
trSubprograms() [2/2]
virtual QCString TranslatorGerman::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1723 of file translator_de.h.
    { return "Funktionen/Unterroutinen"; }
trTemplateParameters() [1/2]
virtual QCString TranslatorGerman::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 2000 of file translator_de.h.
    { return "Template-Parameter"; }
trTemplateParameters() [2/2]
virtual QCString TranslatorGerman::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 2000 of file translator_de.h.
    { return "Template-Parameter"; }
trTest() [1/2]
virtual QCString TranslatorGerman::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1204 of file translator_de.h.
    {
      return "Test";
    }
trTest() [2/2]
virtual QCString TranslatorGerman::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1204 of file translator_de.h.
    {
      return "Test";
    }
trTestList() [1/2]
virtual QCString TranslatorGerman::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1210 of file translator_de.h.
    {
      return "Test-Liste";
    }
trTestList() [2/2]
virtual QCString TranslatorGerman::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1210 of file translator_de.h.
    {
      return "Test-Liste";
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorGerman::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 228 of file translator_de.h.
    { return "Vollstndige Aufstellung aller Elemente fr "; }
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorGerman::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 228 of file translator_de.h.
    { return "Vollstndige Aufstellung aller Elemente fr "; }
trTodo() [1/2]
virtual QCString TranslatorGerman::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 1070 of file translator_de.h.
    {
      return "Noch zu erledigen";
    }
trTodo() [2/2]
virtual QCString TranslatorGerman::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 1070 of file translator_de.h.
    {
      return "Noch zu erledigen";
    }
trTodoList() [1/2]
virtual QCString TranslatorGerman::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 1076 of file translator_de.h.
    {
      return "Ausstehende Aufgaben";
    }
trTodoList() [2/2]
virtual QCString TranslatorGerman::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 1076 of file translator_de.h.
    {
      return "Ausstehende Aufgaben";
    }
trType() [1/2]
virtual QCString TranslatorGerman::trType (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1849 of file translator_de.h.
    {
      QCString result("Typ");
      if (!singular) result+="en";
      return result;
    }
trType() [2/2]
virtual QCString TranslatorGerman::trType (bool , bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1849 of file translator_de.h.
    {
      QCString result("Typ");
      if (!singular) result+="en";
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorGerman::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1868 of file translator_de.h.
    {
      return "Type Constraints";
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorGerman::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1868 of file translator_de.h.
    {
      return "Type Constraints";
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorGerman::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 563 of file translator_de.h.
    { return "Dokumentation der benutzerdefinierten Typen"; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorGerman::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 563 of file translator_de.h.
    { return "Dokumentation der benutzerdefinierten Typen"; }
trTypedefs() [1/2]
virtual QCString TranslatorGerman::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 527 of file translator_de.h.
    { return "Typdefinitionen"; }
trTypedefs() [2/2]
virtual QCString TranslatorGerman::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 527 of file translator_de.h.
    { return "Typdefinitionen"; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorGerman::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1717 of file translator_de.h.
    { return "Datentyp-Dokumentation"; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorGerman::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1717 of file translator_de.h.
    { return "Datentyp-Dokumentation"; }
trVariableDocumentation() [1/2]
virtual QCString TranslatorGerman::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 581 of file translator_de.h.
    { return "Variablen-Dokumentation"; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorGerman::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 581 of file translator_de.h.
    { return "Variablen-Dokumentation"; }
trVariables() [1/2]
virtual QCString TranslatorGerman::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 545 of file translator_de.h.
    { return "Variablen"; }
trVariables() [2/2]
virtual QCString TranslatorGerman::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 545 of file translator_de.h.
    { return "Variablen"; }
trVersion() [1/2]
virtual QCString TranslatorGerman::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 621 of file translator_de.h.
    { return "Version"; }
trVersion() [2/2]
virtual QCString TranslatorGerman::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 621 of file translator_de.h.
    { return "Version"; }
trVhdlType() [1/2]
virtual QCString TranslatorGerman::trVhdlType (uint64 type, bool single) [inline], [virtual]
VHDL type
Reimplemented from TranslatorAdapter_1_8_15.
Definition at line 2173 of file translator_de.h.
    {
      switch(type)
      {
        case VhdlDocGen::LIBRARY:
          if (single) return "Bibliothek";
          else return "Bibliotheken";
        case VhdlDocGen::PACKAGE:
          if (single) return "Paket";
          else return "Pakete";
        case VhdlDocGen::SIGNAL:
          if (single) return "Signal";
          else return "Signale";
        case VhdlDocGen::COMPONENT:
          if (single) return "Komponente";
          else return "Komponenten";
        case VhdlDocGen::CONSTANT:
          if (single) return "Konstante";
          else return "Konstanten";
        case VhdlDocGen::ENTITY:
          if (single) return "Entwurfseinheit";
          else return "Entwurfseinheiten";
        case VhdlDocGen::TYPE:
          if (single) return "Typ";
          else return "Typen";
        case VhdlDocGen::SUBTYPE:
          if (single) return "Subtyp";
          else return "Subtypen";
        case VhdlDocGen::FUNCTION:
          if (single) return "Funktion";
          else return "Funktionen";
        case VhdlDocGen::RECORD:
          if (single) return "Datenstruktur";
          else return "Datenstrukturen";
        case VhdlDocGen::PROCEDURE:
          if (single) return "Prozedur";
          else return "Prozeduren";
        case VhdlDocGen::ARCHITECTURE:
          if (single) return "Architektur";
          else return "Architekturen";
        case VhdlDocGen::ATTRIBUTE:
          if (single) return "Attribut";
          else return "Attribute";
        case VhdlDocGen::PROCESS:
          if (single) return "Prozess";
          else return "Prozesse";
        case VhdlDocGen::PORT:
          if (single) return "Schnittstelle";
          else return "Schnittstellen";
        case VhdlDocGen::USE:
          if (single) return "Use Klausel";
          else return "Use Klauseln";
        case VhdlDocGen::GENERIC:
          if (single) return "Parameter";
          else return "Parameter";
        case VhdlDocGen::PACKAGE_BODY:
          return "Paketkrper";
        case VhdlDocGen::UNITS:
          return "Einheiten";
        case VhdlDocGen::SHAREDVARIABLE:
          if (single) return "Geteilte Variable";
          else return "Geteilte Variablen";
        case VhdlDocGen::VFILE:
          if (single) return "Datei";
          else return "Dateien";
        case VhdlDocGen::GROUP:
          if (single) return "Gruppe";
          else return "Gruppen";
        case VhdlDocGen::INSTANTIATION:
          if (single) return "Instanziierung";
          else return "Instanziierungen";
        case VhdlDocGen::ALIAS:
          if (single) return "Alias";
          else return "Aliase";
        case VhdlDocGen::CONFIG:
          if (single) return "Konfiguration";
          else return "Konfigurationen";
        case VhdlDocGen::MISCELLANEOUS:
          return "Verschiedenes";
        case VhdlDocGen::UCF_CONST:
          return "Constraints";
        default:
          return "Klasse";
      }
    }
References VhdlDocGen::ALIAS, VhdlDocGen::ARCHITECTURE, VhdlDocGen::ATTRIBUTE, VhdlDocGen::COMPONENT, VhdlDocGen::CONFIG, VhdlDocGen::CONSTANT, VhdlDocGen::ENTITY, VhdlDocGen::FUNCTION, VhdlDocGen::GENERIC, VhdlDocGen::GROUP, VhdlDocGen::INSTANTIATION, VhdlDocGen::LIBRARY, VhdlDocGen::MISCELLANEOUS, VhdlDocGen::PACKAGE, VhdlDocGen::PACKAGE_BODY, VhdlDocGen::PORT, VhdlDocGen::PROCEDURE, VhdlDocGen::PROCESS, VhdlDocGen::RECORD, VhdlDocGen::SHAREDVARIABLE, VhdlDocGen::SIGNAL, VhdlDocGen::SUBTYPE, VhdlDocGen::TYPE, VhdlDocGen::UCF_CONST, VhdlDocGen::UNITS, VhdlDocGen::USE, and VhdlDocGen::VFILE.
trVhdlType() [2/2]
virtual QCString TranslatorGerman::trVhdlType (uint64 type, bool single) [inline], [virtual]
VHDL type
Reimplemented from TranslatorAdapter_1_8_15.
Definition at line 2173 of file translator_de.h.
    {
      switch(type)
      {
        case VhdlDocGen::LIBRARY:
          if (single) return "Bibliothek";
          else return "Bibliotheken";
        case VhdlDocGen::PACKAGE:
          if (single) return "Paket";
          else return "Pakete";
        case VhdlDocGen::SIGNAL:
          if (single) return "Signal";
          else return "Signale";
        case VhdlDocGen::COMPONENT:
          if (single) return "Komponente";
          else return "Komponenten";
        case VhdlDocGen::CONSTANT:
          if (single) return "Konstante";
          else return "Konstanten";
        case VhdlDocGen::ENTITY:
          if (single) return "Entwurfseinheit";
          else return "Entwurfseinheiten";
        case VhdlDocGen::TYPE:
          if (single) return "Typ";
          else return "Typen";
        case VhdlDocGen::SUBTYPE:
          if (single) return "Subtyp";
          else return "Subtypen";
        case VhdlDocGen::FUNCTION:
          if (single) return "Funktion";
          else return "Funktionen";
        case VhdlDocGen::RECORD:
          if (single) return "Datenstruktur";
          else return "Datenstrukturen";
        case VhdlDocGen::PROCEDURE:
          if (single) return "Prozedur";
          else return "Prozeduren";
        case VhdlDocGen::ARCHITECTURE:
          if (single) return "Architektur";
          else return "Architekturen";
        case VhdlDocGen::ATTRIBUTE:
          if (single) return "Attribut";
          else return "Attribute";
        case VhdlDocGen::PROCESS:
          if (single) return "Prozess";
          else return "Prozesse";
        case VhdlDocGen::PORT:
          if (single) return "Schnittstelle";
          else return "Schnittstellen";
        case VhdlDocGen::USE:
          if (single) return "Use Klausel";
          else return "Use Klauseln";
        case VhdlDocGen::GENERIC:
          if (single) return "Parameter";
          else return "Parameter";
        case VhdlDocGen::PACKAGE_BODY:
          return "Paketkrper";
        case VhdlDocGen::UNITS:
          return "Einheiten";
        case VhdlDocGen::SHAREDVARIABLE:
          if (single) return "Geteilte Variable";
          else return "Geteilte Variablen";
        case VhdlDocGen::VFILE:
          if (single) return "Datei";
          else return "Dateien";
        case VhdlDocGen::GROUP:
          if (single) return "Gruppe";
          else return "Gruppen";
        case VhdlDocGen::INSTANTIATION:
          if (single) return "Instanziierung";
          else return "Instanziierungen";
        case VhdlDocGen::ALIAS:
          if (single) return "Alias";
          else return "Aliase";
        case VhdlDocGen::CONFIG:
          if (single) return "Konfiguration";
          else return "Konfigurationen";
        case VhdlDocGen::MISCELLANEOUS:
          return "Verschiedenes";
        case VhdlDocGen::UCF_CONST:
          return "Constraints";
        default:
          return "Klasse";
      }
    }
References VhdlDocGen::ALIAS, VhdlDocGen::ARCHITECTURE, VhdlDocGen::ATTRIBUTE, VhdlDocGen::COMPONENT, VhdlDocGen::CONFIG, VhdlDocGen::CONSTANT, VhdlDocGen::ENTITY, VhdlDocGen::FUNCTION, VhdlDocGen::GENERIC, VhdlDocGen::GROUP, VhdlDocGen::INSTANTIATION, VhdlDocGen::LIBRARY, VhdlDocGen::MISCELLANEOUS, VhdlDocGen::PACKAGE, VhdlDocGen::PACKAGE_BODY, VhdlDocGen::PORT, VhdlDocGen::PROCEDURE, VhdlDocGen::PROCESS, VhdlDocGen::RECORD, VhdlDocGen::SHAREDVARIABLE, VhdlDocGen::SIGNAL, VhdlDocGen::SUBTYPE, VhdlDocGen::TYPE, VhdlDocGen::UCF_CONST, VhdlDocGen::UNITS, VhdlDocGen::USE, and VhdlDocGen::VFILE.
trWarning() [1/2]
virtual QCString TranslatorGerman::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 617 of file translator_de.h.
    { return "Warnung"; }
trWarning() [2/2]
virtual QCString TranslatorGerman::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 617 of file translator_de.h.
    { return "Warnung"; }
trWriteList() [1/2]
virtual QCString TranslatorGerman::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 756 of file translator_de.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" und ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorGerman::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 756 of file translator_de.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=" und ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_de.h
doxygen/src/translator_de.h