TranslatorEsperanto Class Reference
#include <translator_eo.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trISOLang ()
virtual QCString getLanguageString ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const QCString &s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const QCString &date, const QCString &projName)
virtual QCString trClassDiagram (const QCString &clName)
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const QCString &fileName)
virtual QCString trNamespaceReference (const QCString &namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const QCString &clName)
virtual QCString trInclDepGraph (const QCString &fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const QCString &name)
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageFunctions ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageFunctions ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirReference (const QCString &dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const QCString &clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const QCString &namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const QCString &name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const QCString &name)
virtual QCString trIncludesFileIn (const QCString &name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
virtual QCString trDayOfWeek (int dayOfWeek, bool first_capital, bool full)
virtual QCString trMonth (int month, bool first_capital, bool full)
virtual QCString trDayPeriod (int period)
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const QCString &name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
Additional Inherited Members
Detailed Description
When defining a translator class for the new language, follow the description in the documentation. One of the steps says that you should copy the translator_en.h (this) file to your translator_xx.h new file. Your new language should use the Translator class as the base class. This means that you need to implement exactly the same (pure virtual) methods as the TranslatorEnglish does. Because of this, it is a good idea to start with the copy of TranslatorEnglish and replace the strings one by one.
It is not necessary to include `translator.h` or `translator_adapter.h` here. The files are included in the language.cpp correctly. Not including any of the mentioned files frees the maintainer from thinking about whether the first, the second, or both files should be included or not, and why. This holds namely for localized translators because their base class is changed occasionally to adapter classes when the Translator class changes the interface, or back to the Translator class (by the local maintainer) when the localized translator is made up-to-date again.
Definition at line 45 of file translator_eo.h.
Member Function Documentation
getLanguageString() [1/2]
virtual QCString TranslatorEsperanto::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 85 of file translator_eo.h.
    {
      return "0x409 English (United States)";
    }
getLanguageString() [2/2]
virtual QCString TranslatorEsperanto::getLanguageString () [inline], [virtual]
language codes for Html help 0x402 Bulgarian 0x405 Czech 0x406 Danish 0x413 Dutch 0xC09 English (Australia) 0x809 English (Britain) 0x1009 English (Canada) 0x1809 English (Ireland) 0x1409 English (New Zealand) 0x1C09 English (South Africa) 0x409 English (United States) 0x40B Finnish 0x40C French 0x407 German 0x408 Greece 0x439 Hindi 0x40E Hungarian 0x410 Italian 0x814 Norwegian 0x415 Polish 0x816 Portuguese(Portugal) 0x416 Portuguese(Brazil) 0x419 Russian 0x80A Spanish(Mexico) 0xC0A Spanish(Modern Sort) 0x40A Spanish(Traditional Sort) 0x41D Swedish 0x41F Turkey 0x411 Japanese 0x412 Korean 0x804 Chinese (PRC) 0x404 Chinese (Taiwan)
New LCIDs: 0x421 Indonesian 0x41A Croatian 0x418 Romanian 0x424 Slovenian 0x41B Slovak 0x422 Ukrainian 0x81A Serbian (Serbia, Latin) 0x403 Catalan 0x426 Latvian 0x427 Lithuanian 0x436 Afrikaans 0x42A Vietnamese 0x429 Persian (Iran) 0xC01 Arabic (Egypt) - I don't know which version of arabic is used inside translator_ar.h , so I have chosen Egypt at random
Code for Esperanto should be as shown below but the htmlhelp compiler 1.3 does not support this (and no newer version is available). 0x48f Esperanto So do a fallback to the default language 0x409 English (United States)
0xC1A Serbian (Serbia, Cyrillic)
Implements Translator.
Definition at line 85 of file translator_eo.h.
    {
      return "0x409 English (United States)";
    }
idLanguage() [1/2]
virtual QCString TranslatorEsperanto::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 57 of file translator_eo.h.
    { return "esperanto"; }
idLanguage() [2/2]
virtual QCString TranslatorEsperanto::idLanguage () [inline], [virtual]
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. `czech`, `japanese`, `russian`, etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 57 of file translator_eo.h.
    { return "esperanto"; }
latexLanguageSupportCommand() [1/2]
virtual QCString TranslatorEsperanto::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 74 of file translator_eo.h.
    {
      return "\\usepackage[esperanto]{babel}\n";
    }
latexLanguageSupportCommand() [2/2]
virtual QCString TranslatorEsperanto::latexLanguageSupportCommand () [inline], [virtual]
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
 or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 74 of file translator_eo.h.
    {
      return "\\usepackage[esperanto]{babel}\n";
    }
trAdditionalInheritedMembers() [1/2]
virtual QCString TranslatorEsperanto::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1898 of file translator_eo.h.
    { return "Kromaj Hereditaj Membroj"; }
trAdditionalInheritedMembers() [2/2]
virtual QCString TranslatorEsperanto::trAdditionalInheritedMembers () [inline], [virtual]
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1898 of file translator_eo.h.
    { return "Kromaj Hereditaj Membroj"; }
trAll() [1/2]
virtual QCString TranslatorEsperanto::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1403 of file translator_eo.h.
    {
      return "iuj";
    }
trAll() [2/2]
virtual QCString TranslatorEsperanto::trAll () [inline], [virtual]
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1403 of file translator_eo.h.
    {
      return "iuj";
    }
trAndMore() [1/2]
virtual QCString TranslatorEsperanto::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1876 of file translator_eo.h.
    { return "kaj "+number+" pli..."; }
trAndMore() [2/2]
virtual QCString TranslatorEsperanto::trAndMore (const QCString & number) [inline], [virtual]
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1876 of file translator_eo.h.
    { return "kaj "+number+" pli..."; }
trAttention() [1/2]
virtual QCString TranslatorEsperanto::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 967 of file translator_eo.h.
    {
      return "Atentu";
    }
trAttention() [2/2]
virtual QCString TranslatorEsperanto::trAttention () [inline], [virtual]
Implements Translator.
Definition at line 967 of file translator_eo.h.
    {
      return "Atentu";
    }
trAuthor() [1/2]
virtual QCString TranslatorEsperanto::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1274 of file translator_eo.h.
    {
      QCString result((first_capital ? "Atoro" : "atoro"));
      if (!singular) result+="j";
      return result;
    }
trAuthor() [2/2]
virtual QCString TranslatorEsperanto::trAuthor (bool first_capital, bool singular) [inline], [virtual]
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1274 of file translator_eo.h.
    {
      QCString result((first_capital ? "Atoro" : "atoro"));
      if (!singular) result+="j";
      return result;
    }
trBug() [1/2]
virtual QCString TranslatorEsperanto::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1132 of file translator_eo.h.
    {
      return "Cimo";
    }
trBug() [2/2]
virtual QCString TranslatorEsperanto::trBug () [inline], [virtual]
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1132 of file translator_eo.h.
    {
      return "Cimo";
    }
trBugList() [1/2]
virtual QCString TranslatorEsperanto::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1137 of file translator_eo.h.
    {
      return "Cima Listo";
    }
trBugList() [2/2]
virtual QCString TranslatorEsperanto::trBugList () [inline], [virtual]
Used as the header of the bug list
Implements Translator.
Definition at line 1137 of file translator_eo.h.
    {
      return "Cima Listo";
    }
trCallerGraph() [1/2]
virtual QCString TranslatorEsperanto::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1524 of file translator_eo.h.
    {
      return "Jen la vokdiagramo por tiu i funkcio:";
    }
trCallerGraph() [2/2]
virtual QCString TranslatorEsperanto::trCallerGraph () [inline], [virtual]
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1524 of file translator_eo.h.
    {
      return "Jen la vokdiagramo por tiu i funkcio:";
    }
trCallGraph() [1/2]
virtual QCString TranslatorEsperanto::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1408 of file translator_eo.h.
    {
      return "Jen la vokdiagramo por tiu i funkcio:";
    }
trCallGraph() [2/2]
virtual QCString TranslatorEsperanto::trCallGraph () [inline], [virtual]
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1408 of file translator_eo.h.
    {
      return "Jen la vokdiagramo por tiu i funkcio:";
    }
trCiteReferences() [1/2]
virtual QCString TranslatorEsperanto::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1852 of file translator_eo.h.
    { return "Bibliografiaj Referencoj"; }
trCiteReferences() [2/2]
virtual QCString TranslatorEsperanto::trCiteReferences () [inline], [virtual]
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1852 of file translator_eo.h.
    { return "Bibliografiaj Referencoj"; }
trClass() [1/2]
virtual QCString TranslatorEsperanto::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1195 of file translator_eo.h.
    {
      QCString result((first_capital ? "Klaso" : "klaso"));
      if (!singular) result+="j";
      return result;
    }
trClass() [2/2]
virtual QCString TranslatorEsperanto::trClass (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1195 of file translator_eo.h.
    {
      QCString result((first_capital ? "Klaso" : "klaso"));
      if (!singular) result+="j";
      return result;
    }
trClassDiagram() [1/2]
virtual QCString TranslatorEsperanto::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 520 of file translator_eo.h.
    {
      return "Heredada diagramo por "+clName+":";
    }
trClassDiagram() [2/2]
virtual QCString TranslatorEsperanto::trClassDiagram (const QCString & clName) [inline], [virtual]
this text is put before a class diagram
Implements Translator.
Definition at line 520 of file translator_eo.h.
    {
      return "Heredada diagramo por "+clName+":";
    }
trClassDocumentation() [1/2]
virtual QCString TranslatorEsperanto::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 395 of file translator_eo.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datumstruktura Dokumentado";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Klasa Dokumentado";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClassDocumentation() [2/2]
virtual QCString TranslatorEsperanto::trClassDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 395 of file translator_eo.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datumstruktura Dokumentado";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_VHDL))
      {
          return trDesignUnitDocumentation();
      }
      else
      {
        return "Klasa Dokumentado";
      }
    }
References Config_getBool, and TranslatorAdapter_1_8_19::trDesignUnitDocumentation().
trClasses() [1/2]
virtual QCString TranslatorEsperanto::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1095 of file translator_eo.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datumstrukturoj";
      }
      else
      {
        return "Klasoj";
      }
    }
References Config_getBool.
trClasses() [2/2]
virtual QCString TranslatorEsperanto::trClasses () [inline], [virtual]
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1095 of file translator_eo.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datumstrukturoj";
      }
      else
      {
        return "Klasoj";
      }
    }
References Config_getBool.
trClassHierarchy() [1/2]
virtual QCString TranslatorEsperanto::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 179 of file translator_eo.h.
    { return "Klasa Hierarkio"; }
trClassHierarchy() [2/2]
virtual QCString TranslatorEsperanto::trClassHierarchy () [inline], [virtual]
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 179 of file translator_eo.h.
    { return "Klasa Hierarkio"; }
trClassHierarchyDescription() [1/2]
virtual QCString TranslatorEsperanto::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 238 of file translator_eo.h.
    { return "Tiu i heredada listo estas plimalpli, "
             "sed ne tute, ordigita alfabete:";
    }
trClassHierarchyDescription() [2/2]
virtual QCString TranslatorEsperanto::trClassHierarchyDescription () [inline], [virtual]
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 238 of file translator_eo.h.
    { return "Tiu i heredada listo estas plimalpli, "
             "sed ne tute, ordigita alfabete:";
    }
trClassMethods() [1/2]
virtual QCString TranslatorEsperanto::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1936 of file translator_eo.h.
    {
      return "Klasaj Metodoj";
    }
trClassMethods() [2/2]
virtual QCString TranslatorEsperanto::trClassMethods () [inline], [virtual]
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1936 of file translator_eo.h.
    {
      return "Klasaj Metodoj";
    }
trCode() [1/2]
virtual QCString TranslatorEsperanto::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 867 of file translator_eo.h.
    {
      return "kodo";
    }
trCode() [2/2]
virtual QCString TranslatorEsperanto::trCode () [inline], [virtual]
Text used the source code in the file index
Implements Translator.
Definition at line 867 of file translator_eo.h.
    {
      return "kodo";
    }
trCollaborationDiagram() [1/2]
virtual QCString TranslatorEsperanto::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 822 of file translator_eo.h.
    {
      return "Kunlaborada diagramo por "+clName+":";
    }
trCollaborationDiagram() [2/2]
virtual QCString TranslatorEsperanto::trCollaborationDiagram (const QCString & clName) [inline], [virtual]
this text is put before a collaboration diagram
Implements Translator.
Definition at line 822 of file translator_eo.h.
    {
      return "Kunlaborada diagramo por "+clName+":";
    }
trCompoundIndex() [1/2]
virtual QCString TranslatorEsperanto::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 368 of file translator_eo.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datumstruktura Indekso";
      }
      else
      {
        return "Klasa Indekso";
      }
    }
References Config_getBool.
trCompoundIndex() [2/2]
virtual QCString TranslatorEsperanto::trCompoundIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 368 of file translator_eo.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datumstruktura Indekso";
      }
      else
      {
        return "Klasa Indekso";
      }
    }
References Config_getBool.
trCompoundIndexFortran() [1/2]
virtual QCString TranslatorEsperanto::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1579 of file translator_eo.h.
    { return "Datumtipa Indekso"; }
trCompoundIndexFortran() [2/2]
virtual QCString TranslatorEsperanto::trCompoundIndexFortran () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1579 of file translator_eo.h.
    { return "Datumtipa Indekso"; }
trCompoundList() [1/2]
virtual QCString TranslatorEsperanto::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 183 of file translator_eo.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datumstruktoroj";
      }
      else
      {
        return "Klasaro";
      }
    }
References Config_getBool.
trCompoundList() [2/2]
virtual QCString TranslatorEsperanto::trCompoundList () [inline], [virtual]
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 183 of file translator_eo.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datumstruktoroj";
      }
      else
      {
        return "Klasaro";
      }
    }
References Config_getBool.
trCompoundListDescription() [1/2]
virtual QCString TranslatorEsperanto::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 253 of file translator_eo.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Jen datumstrukturoj kun mallongaj priskriboj:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Jen la klasoj kun mallongaj priskriboj:";
      }
      else
      {
        return "Jen la klasoj, strukturoj, kunigoj kaj interfacoj "
               "kun mallongaj priskriboj:";
      }
    }
References Config_getBool.
trCompoundListDescription() [2/2]
virtual QCString TranslatorEsperanto::trCompoundListDescription () [inline], [virtual]
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 253 of file translator_eo.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Jen datumstrukturoj kun mallongaj priskriboj:";
      }
      else if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
      {
        return "Jen la klasoj kun mallongaj priskriboj:";
      }
      else
      {
        return "Jen la klasoj, strukturoj, kunigoj kaj interfacoj "
               "kun mallongaj priskriboj:";
      }
    }
References Config_getBool.
trCompoundListDescriptionFortran() [1/2]
virtual QCString TranslatorEsperanto::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1552 of file translator_eo.h.
    { return "Jen la datumtipoj kun mallongaj priskriboj:"; }
trCompoundListDescriptionFortran() [2/2]
virtual QCString TranslatorEsperanto::trCompoundListDescriptionFortran () [inline], [virtual]
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1552 of file translator_eo.h.
    { return "Jen la datumtipoj kun mallongaj priskriboj:"; }
trCompoundListFortran() [1/2]
virtual QCString TranslatorEsperanto::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1544 of file translator_eo.h.
    { return "Datumtipa Listo"; }
trCompoundListFortran() [2/2]
virtual QCString TranslatorEsperanto::trCompoundListFortran () [inline], [virtual]
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1544 of file translator_eo.h.
    { return "Datumtipa Listo"; }
trCompoundMembers() [1/2]
virtual QCString TranslatorEsperanto::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 200 of file translator_eo.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datumkampoj";
      }
      else
      {
        return "Klasaj membroj";
      }
    }
References Config_getBool.
trCompoundMembers() [2/2]
virtual QCString TranslatorEsperanto::trCompoundMembers () [inline], [virtual]
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 200 of file translator_eo.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datumkampoj";
      }
      else
      {
        return "Klasaj membroj";
      }
    }
References Config_getBool.
trCompoundMembersDescription() [1/2]
virtual QCString TranslatorEsperanto::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 272 of file translator_eo.h.
    {
      QCString result="Jen listo de iuj ";
      if (!extractAll)
      {
        result+="dokumentitaj ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="strukturaj kaj kunigaj kampoj";
      }
      else
      {
        result+="klasaj membroj";
      }
      result+=" kun ligiloj al ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="la struktura/kuniga dokumentado por iu kampo:";
        }
        else
        {
          result+="la klasa dokumentado por iu membro:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="la strukturoj/kunigoj al kiuj ili apartenas:";
        }
        else
        {
          result+="la klasoj al kiuj ili apartenas:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescription() [2/2]
virtual QCString TranslatorEsperanto::trCompoundMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 272 of file translator_eo.h.
    {
      QCString result="Jen listo de iuj ";
      if (!extractAll)
      {
        result+="dokumentitaj ";
      }
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="strukturaj kaj kunigaj kampoj";
      }
      else
      {
        result+="klasaj membroj";
      }
      result+=" kun ligiloj al ";
      if (!extractAll)
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="la struktura/kuniga dokumentado por iu kampo:";
        }
        else
        {
          result+="la klasa dokumentado por iu membro:";
        }
      }
      else
      {
        if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
        {
          result+="la strukturoj/kunigoj al kiuj ili apartenas:";
        }
        else
        {
          result+="la klasoj al kiuj ili apartenas:";
        }
      }
      return result;
    }
References Config_getBool.
trCompoundMembersDescriptionFortran() [1/2]
virtual QCString TranslatorEsperanto::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1556 of file translator_eo.h.
    {
      QCString result="Jen listo de iuj ";
      if (!extractAll)
      {
        result+="dokumentitaj ";
      }
      result+="datumtipaj membroj";
      result+=" kun ligiloj al ";
      if (!extractAll)
      {
         result+="la datumstruktura dokumentado de iu membro";
      }
      else
      {
         result+="la datumtipoj al kiuj ili apartenas:";
      }
      return result;
    }
trCompoundMembersDescriptionFortran() [2/2]
virtual QCString TranslatorEsperanto::trCompoundMembersDescriptionFortran (bool extractAll) [inline], [virtual]
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1556 of file translator_eo.h.
    {
      QCString result="Jen listo de iuj ";
      if (!extractAll)
      {
        result+="dokumentitaj ";
      }
      result+="datumtipaj membroj";
      result+=" kun ligiloj al ";
      if (!extractAll)
      {
         result+="la datumstruktura dokumentado de iu membro";
      }
      else
      {
         result+="la datumtipoj al kiuj ili apartenas:";
      }
      return result;
    }
trCompoundMembersFortran() [1/2]
virtual QCString TranslatorEsperanto::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1548 of file translator_eo.h.
    { return "Datumkampoj"; }
trCompoundMembersFortran() [2/2]
virtual QCString TranslatorEsperanto::trCompoundMembersFortran () [inline], [virtual]
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1548 of file translator_eo.h.
    { return "Datumkampoj"; }
trCompoundReference() [1/2]
virtual QCString TranslatorEsperanto::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 595 of file translator_eo.h.
    {
      QCString result="Referenco de la ";
      if (isTemplate) result+=" ablono de la ";
      switch(compType)
      {
        case ClassDef::Class: result+="klaso "; break;
        case ClassDef::Struct: result+="strukturo "; break;
        case ClassDef::Union: result+="kunigo "; break;
        case ClassDef::Interface: result+="interfaco "; break;
        case ClassDef::Protocol: result+="protokolo "; break;
        case ClassDef::Category: result+="kategorio "; break;
        case ClassDef::Exception: result+="escepto "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReference() [2/2]
virtual QCString TranslatorEsperanto::trCompoundReference (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 595 of file translator_eo.h.
    {
      QCString result="Referenco de la ";
      if (isTemplate) result+=" ablono de la ";
      switch(compType)
      {
        case ClassDef::Class: result+="klaso "; break;
        case ClassDef::Struct: result+="strukturo "; break;
        case ClassDef::Union: result+="kunigo "; break;
        case ClassDef::Interface: result+="interfaco "; break;
        case ClassDef::Protocol: result+="protokolo "; break;
        case ClassDef::Category: result+="kategorio "; break;
        case ClassDef::Exception: result+="escepto "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [1/2]
virtual QCString TranslatorEsperanto::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1620 of file translator_eo.h.
    {
      QCString result="Referenco de la ";
      if (isTemplate) result+=" ablono de la ";
      switch(compType)
      {
        case ClassDef::Class: result+="modulo "; break;
        case ClassDef::Struct: result+="tipo "; break;
        case ClassDef::Union: result+="kunigo "; break;
        case ClassDef::Interface: result+="interfaco "; break;
        case ClassDef::Protocol: result+="protokolo "; break;
        case ClassDef::Category: result+="kategorio "; break;
        case ClassDef::Exception: result+="escepto "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran() [2/2]
virtual QCString TranslatorEsperanto::trCompoundReferenceFortran (const QCString & clName, ClassDef::CompoundType compType, bool isTemplate) [inline], [virtual]
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1620 of file translator_eo.h.
    {
      QCString result="Referenco de la ";
      if (isTemplate) result+=" ablono de la ";
      switch(compType)
      {
        case ClassDef::Class: result+="modulo "; break;
        case ClassDef::Struct: result+="tipo "; break;
        case ClassDef::Union: result+="kunigo "; break;
        case ClassDef::Interface: result+="interfaco "; break;
        case ClassDef::Protocol: result+="protokolo "; break;
        case ClassDef::Category: result+="kategorio "; break;
        case ClassDef::Exception: result+="escepto "; break;
        default: break;
      }
      result+=clName;
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds() [1/2]
virtual QCString TranslatorEsperanto::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 496 of file translator_eo.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datumstrukturoj";
      }
      else
      {
        return "Klasoj";
      }
    }
References Config_getBool.
trCompounds() [2/2]
virtual QCString TranslatorEsperanto::trCompounds () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 496 of file translator_eo.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datumstrukturoj";
      }
      else
      {
        return "Klasoj";
      }
    }
References Config_getBool.
trConstructorDocumentation() [1/2]
virtual QCString TranslatorEsperanto::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 832 of file translator_eo.h.
    {
      return "Konstruila kaj Detruila Dokumentado";
    }
trConstructorDocumentation() [2/2]
virtual QCString TranslatorEsperanto::trConstructorDocumentation () [inline], [virtual]
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 832 of file translator_eo.h.
    {
      return "Konstruila kaj Detruila Dokumentado";
    }
trCopyright() [1/2]
virtual QCString TranslatorEsperanto::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1856 of file translator_eo.h.
    { return "Kopirajto"; }
trCopyright() [2/2]
virtual QCString TranslatorEsperanto::trCopyright () [inline], [virtual]
Text for copyright paragraph
Implements Translator.
Definition at line 1856 of file translator_eo.h.
    { return "Kopirajto"; }
trDataTypes() [1/2]
virtual QCString TranslatorEsperanto::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1603 of file translator_eo.h.
    { return "Datumtipoj"; }
trDataTypes() [2/2]
virtual QCString TranslatorEsperanto::trDataTypes () [inline], [virtual]
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1603 of file translator_eo.h.
    { return "Datumtipoj"; }
trDate() [1/2]
virtual QCString TranslatorEsperanto::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 534 of file translator_eo.h.
    { return "Dato"; }
trDate() [2/2]
virtual QCString TranslatorEsperanto::trDate () [inline], [virtual]
this text is generated when the \date command is used.
Implements Translator.
Definition at line 534 of file translator_eo.h.
    { return "Dato"; }
trDateTime() [1/2]
virtual QCString TranslatorEsperanto::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1801 of file translator_eo.h.
    {
      static const char *days[] = { "lundo","mardo","merkredo",
                                        "ado","vendredo","sabato",
                                        "dimano" };
      static const char *months[] = { "Januaro", "Februaro", "Marto",
                                        "Aprilo", "Majo", "Junio",
                                        "Julio", "Agusto", "Septembro",
                                        "Oktobro", "Novembro",
                                        "Decembro"
                                    };
      QCString sdate;
      sdate.sprintf("%s, %d-a de %s %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDateTime() [2/2]
virtual QCString TranslatorEsperanto::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) [inline], [virtual]
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1801 of file translator_eo.h.
    {
      static const char *days[] = { "lundo","mardo","merkredo",
                                        "ado","vendredo","sabato",
                                        "dimano" };
      static const char *months[] = { "Januaro", "Februaro", "Marto",
                                        "Aprilo", "Majo", "Junio",
                                        "Julio", "Agusto", "Septembro",
                                        "Oktobro", "Novembro",
                                        "Decembro"
                                    };
      QCString sdate;
      sdate.sprintf("%s, %d-a de %s %d",days[dayOfWeek-1],day,months[month-1],year);
      if (includeTime)
      {
        QCString stime;
        stime.sprintf(" %.2d:%.2d:%.2d",hour,minutes,seconds);
        sdate+=stime;
      }
      return sdate;
    }
References QCString::sprintf().
trDayOfWeek() [1/2]
virtual QCString TranslatorEsperanto::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1825 of file translator_eo.h.
    {
      static const char *days_short[] = { "lu", "ma", "me", "a", "ve", "sa", "di" };
      static const char *days_full[] = { "lundo", "mardo", "merkredo", "ado", "vendredo", "sabato", "dimano" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayOfWeek() [2/2]
virtual QCString TranslatorEsperanto::trDayOfWeek (int dayOfWeek, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1825 of file translator_eo.h.
    {
      static const char *days_short[] = { "lu", "ma", "me", "a", "ve", "sa", "di" };
      static const char *days_full[] = { "lundo", "mardo", "merkredo", "ado", "vendredo", "sabato", "dimano" };
      QCString text = full? days_full[dayOfWeek-1] : days_short[dayOfWeek-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trDayPeriod() [1/2]
virtual QCString TranslatorEsperanto::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1841 of file translator_eo.h.
    {
      static const char *dayPeriod[] = { "atm", "ptm" };
      return dayPeriod[period];
    }
trDayPeriod() [2/2]
virtual QCString TranslatorEsperanto::trDayPeriod (int period) [inline], [virtual]
Implements Translator.
Definition at line 1841 of file translator_eo.h.
    {
      static const char *dayPeriod[] = { "atm", "ptm" };
      return dayPeriod[period];
    }
trDefinedAtLineInSourceFile() [1/2]
virtual QCString TranslatorEsperanto::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 799 of file translator_eo.h.
    {
      return "Difinita sur la lineo @0 de la dosiero @1.";
    }
trDefinedAtLineInSourceFile() [2/2]
virtual QCString TranslatorEsperanto::trDefinedAtLineInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 799 of file translator_eo.h.
    {
      return "Difinita sur la lineo @0 de la dosiero @1.";
    }
trDefinedIn() [1/2]
virtual QCString TranslatorEsperanto::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 167 of file translator_eo.h.
    { return "difinita en"; }
trDefinedIn() [2/2]
virtual QCString TranslatorEsperanto::trDefinedIn () [inline], [virtual]
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 167 of file translator_eo.h.
    { return "difinita en"; }
trDefinedInSourceFile() [1/2]
virtual QCString TranslatorEsperanto::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 803 of file translator_eo.h.
    {
      return "Difinita en la dosiero @0.";
    }
trDefinedInSourceFile() [2/2]
virtual QCString TranslatorEsperanto::trDefinedInSourceFile () [inline], [virtual]
Implements Translator.
Definition at line 803 of file translator_eo.h.
    {
      return "Difinita en la dosiero @0.";
    }
trDefineDocumentation() [1/2]
virtual QCString TranslatorEsperanto::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 466 of file translator_eo.h.
    { return "Difina Dokumentado"; }
trDefineDocumentation() [2/2]
virtual QCString TranslatorEsperanto::trDefineDocumentation () [inline], [virtual]
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 466 of file translator_eo.h.
    { return "Difina Dokumentado"; }
trDefines() [1/2]
virtual QCString TranslatorEsperanto::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 430 of file translator_eo.h.
    { return "Difinoj"; }
trDefines() [2/2]
virtual QCString TranslatorEsperanto::trDefines () [inline], [virtual]
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 430 of file translator_eo.h.
    { return "Difinoj"; }
trDefineValue() [1/2]
virtual QCString TranslatorEsperanto::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1122 of file translator_eo.h.
    {
      return "Valoro:";
    }
trDefineValue() [2/2]
virtual QCString TranslatorEsperanto::trDefineValue () [inline], [virtual]
Text shown before a multi-line define
Implements Translator.
Definition at line 1122 of file translator_eo.h.
    {
      return "Valoro:";
    }
trDeprecated() [1/2]
virtual QCString TranslatorEsperanto::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 812 of file translator_eo.h.
    {
      return "Evitinda";
    }
trDeprecated() [2/2]
virtual QCString TranslatorEsperanto::trDeprecated () [inline], [virtual]
Implements Translator.
Definition at line 812 of file translator_eo.h.
    {
      return "Evitinda";
    }
trDeprecatedList() [1/2]
virtual QCString TranslatorEsperanto::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1331 of file translator_eo.h.
    {
      return "Evitindaa Listo";
    }
trDeprecatedList() [2/2]
virtual QCString TranslatorEsperanto::trDeprecatedList () [inline], [virtual]
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1331 of file translator_eo.h.
    {
      return "Evitindaa Listo";
    }
trDetailedDescription() [1/2]
virtual QCString TranslatorEsperanto::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 100 of file translator_eo.h.
    { return "Detala Priskribo"; }
trDetailedDescription() [2/2]
virtual QCString TranslatorEsperanto::trDetailedDescription () [inline], [virtual]
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 100 of file translator_eo.h.
    { return "Detala Priskribo"; }
trDetailLevel() [1/2]
virtual QCString TranslatorEsperanto::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1868 of file translator_eo.h.
    { return "detala nivelo"; }
trDetailLevel() [2/2]
virtual QCString TranslatorEsperanto::trDetailLevel () [inline], [virtual]
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1868 of file translator_eo.h.
    { return "detala nivelo"; }
trDir() [1/2]
virtual QCString TranslatorEsperanto::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1498 of file translator_eo.h.
    {
      QCString result((first_capital ? "Dosierujo" : "dosierujo"));
      if (!singular) result+="j";
      return result;
    }
trDir() [2/2]
virtual QCString TranslatorEsperanto::trDir (bool first_capital, bool singular) [inline], [virtual]
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1498 of file translator_eo.h.
    {
      QCString result((first_capital ? "Dosierujo" : "dosierujo"));
      if (!singular) result+="j";
      return result;
    }
trDirDepGraph() [1/2]
virtual QCString TranslatorEsperanto::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1860 of file translator_eo.h.
    { return QCString("Dosieruja dependa diagramo por ")+name+":"; }
References setup::name.
trDirDepGraph() [2/2]
virtual QCString TranslatorEsperanto::trDirDepGraph (const QCString & name) [inline], [virtual]
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1860 of file translator_eo.h.
    { return QCString("Dosieruja dependa diagramo por ")+name+":"; }
References setup::name.
trDirDocumentation() [1/2]
virtual QCString TranslatorEsperanto::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1480 of file translator_eo.h.
    { return "Dosieruja Dokumentado"; }
trDirDocumentation() [2/2]
virtual QCString TranslatorEsperanto::trDirDocumentation () [inline], [virtual]
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1480 of file translator_eo.h.
    { return "Dosieruja Dokumentado"; }
trDirectories() [1/2]
virtual QCString TranslatorEsperanto::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1486 of file translator_eo.h.
    { return "Dosierujoj"; }
trDirectories() [2/2]
virtual QCString TranslatorEsperanto::trDirectories () [inline], [virtual]
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1486 of file translator_eo.h.
    { return "Dosierujoj"; }
trDirIndex() [1/2]
virtual QCString TranslatorEsperanto::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1474 of file translator_eo.h.
    { return "Dosieruja Hierarkio"; }
trDirIndex() [2/2]
virtual QCString TranslatorEsperanto::trDirIndex () [inline], [virtual]
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1474 of file translator_eo.h.
    { return "Dosieruja Hierarkio"; }
trDirReference() [1/2]
virtual QCString TranslatorEsperanto::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1492 of file translator_eo.h.
    { QCString result=dirName; result+=" Dosieruja Referenco"; return result; }
trDirReference() [2/2]
virtual QCString TranslatorEsperanto::trDirReference (const QCString & dirName) [inline], [virtual]
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1492 of file translator_eo.h.
    { QCString result=dirName; result+=" Dosieruja Referenco"; return result; }
trDirRelation() [1/2]
virtual QCString TranslatorEsperanto::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1740 of file translator_eo.h.
    {
      return QCString(name)+" Rilato";
    }
References setup::name.
trDirRelation() [2/2]
virtual QCString TranslatorEsperanto::trDirRelation (const QCString & name) [inline], [virtual]
directory relation for name
Implements Translator.
Definition at line 1740 of file translator_eo.h.
    {
      return QCString(name)+" Rilato";
    }
References setup::name.
trDocumentation() [1/2]
virtual QCString TranslatorEsperanto::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 350 of file translator_eo.h.
    { return "Dokumentado"; }
trDocumentation() [2/2]
virtual QCString TranslatorEsperanto::trDocumentation () [inline], [virtual]
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 350 of file translator_eo.h.
    { return "Dokumentado"; }
trEnumerations() [1/2]
virtual QCString TranslatorEsperanto::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 442 of file translator_eo.h.
    { return "Enumeracioj"; }
trEnumerations() [2/2]
virtual QCString TranslatorEsperanto::trEnumerations () [inline], [virtual]
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 442 of file translator_eo.h.
    { return "Enumeracioj"; }
trEnumerationTypeDocumentation() [1/2]
virtual QCString TranslatorEsperanto::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 478 of file translator_eo.h.
    { return "Enumeracitipa Dokumentado"; }
trEnumerationTypeDocumentation() [2/2]
virtual QCString TranslatorEsperanto::trEnumerationTypeDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 478 of file translator_eo.h.
    { return "Enumeracitipa Dokumentado"; }
trEnumerationValueDocumentation() [1/2]
virtual QCString TranslatorEsperanto::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1532 of file translator_eo.h.
    { return "Enumeraciila Dokumentado"; }
trEnumerationValueDocumentation() [2/2]
virtual QCString TranslatorEsperanto::trEnumerationValueDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1532 of file translator_eo.h.
    { return "Enumeraciila Dokumentado"; }
trEnumerationValues() [1/2]
virtual QCString TranslatorEsperanto::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 460 of file translator_eo.h.
    { return "Enumeraciilo"; }
trEnumerationValues() [2/2]
virtual QCString TranslatorEsperanto::trEnumerationValues () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 460 of file translator_eo.h.
    { return "Enumeraciilo"; }
trEnumGeneratedFromFiles() [1/2]
virtual QCString TranslatorEsperanto::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1880 of file translator_eo.h.
    { QCString result = "La dokumentaro por tiu i enum estis generita el la sekva dosiero";
      if (!single) result += "s";
      result+=":";
      return result;
    }
trEnumGeneratedFromFiles() [2/2]
virtual QCString TranslatorEsperanto::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Used file list for a Java enum
Implements Translator.
Definition at line 1880 of file translator_eo.h.
    { QCString result = "La dokumentaro por tiu i enum estis generita el la sekva dosiero";
      if (!single) result += "s";
      result+=":";
      return result;
    }
trEnumName() [1/2]
virtual QCString TranslatorEsperanto::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 159 of file translator_eo.h.
    { return "enum nomo"; }
trEnumName() [2/2]
virtual QCString TranslatorEsperanto::trEnumName () [inline], [virtual]
put after an enum name in the list of all members
Implements Translator.
Definition at line 159 of file translator_eo.h.
    { return "enum nomo"; }
trEnumReference() [1/2]
virtual QCString TranslatorEsperanto::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1888 of file translator_eo.h.
    { return QCString(name)+" Enum Referenco"; }
References setup::name.
trEnumReference() [2/2]
virtual QCString TranslatorEsperanto::trEnumReference (const QCString & name) [inline], [virtual]
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1888 of file translator_eo.h.
    { return QCString(name)+" Enum Referenco"; }
References setup::name.
trEnumValue() [1/2]
virtual QCString TranslatorEsperanto::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 163 of file translator_eo.h.
    { return "enum valoro"; }
trEnumValue() [2/2]
virtual QCString TranslatorEsperanto::trEnumValue () [inline], [virtual]
put after an enum value in the list of all members
Implements Translator.
Definition at line 163 of file translator_eo.h.
    { return "enum valoro"; }
trEventDocumentation() [1/2]
virtual QCString TranslatorEsperanto::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1348 of file translator_eo.h.
    {
      return "Eventa Dokumentado";
    }
trEventDocumentation() [2/2]
virtual QCString TranslatorEsperanto::trEventDocumentation () [inline], [virtual]
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1348 of file translator_eo.h.
    {
      return "Eventa Dokumentado";
    }
trEvents() [1/2]
virtual QCString TranslatorEsperanto::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1343 of file translator_eo.h.
    {
      return "Eventoj";
    }
trEvents() [2/2]
virtual QCString TranslatorEsperanto::trEvents () [inline], [virtual]
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1343 of file translator_eo.h.
    {
      return "Eventoj";
    }
trExampleDocumentation() [1/2]
virtual QCString TranslatorEsperanto::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 420 of file translator_eo.h.
    { return "Ekzempla Dokumentado"; }
trExampleDocumentation() [2/2]
virtual QCString TranslatorEsperanto::trExampleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 420 of file translator_eo.h.
    { return "Ekzempla Dokumentado"; }
trExamples() [1/2]
virtual QCString TranslatorEsperanto::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 230 of file translator_eo.h.
    { return "Ekzemploj"; }
trExamples() [2/2]
virtual QCString TranslatorEsperanto::trExamples () [inline], [virtual]
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 230 of file translator_eo.h.
    { return "Ekzemploj"; }
trExamplesDescription() [1/2]
virtual QCString TranslatorEsperanto::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 336 of file translator_eo.h.
    { return "Jen listo de iuj la ekzemploj:"; }
trExamplesDescription() [2/2]
virtual QCString TranslatorEsperanto::trExamplesDescription () [inline], [virtual]
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 336 of file translator_eo.h.
    { return "Jen listo de iuj la ekzemploj:"; }
trExceptions() [1/2]
virtual QCString TranslatorEsperanto::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 550 of file translator_eo.h.
    { return "Esceptoj"; }
trExceptions() [2/2]
virtual QCString TranslatorEsperanto::trExceptions () [inline], [virtual]
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 550 of file translator_eo.h.
    { return "Esceptoj"; }
trExtendsClass() [1/2]
virtual QCString TranslatorEsperanto::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1928 of file translator_eo.h.
    {
      return "Etendi klason @0.";
    }
trExtendsClass() [2/2]
virtual QCString TranslatorEsperanto::trExtendsClass () [inline], [virtual]
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1928 of file translator_eo.h.
    {
      return "Etendi klason @0.";
    }
trFile() [1/2]
virtual QCString TranslatorEsperanto::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1206 of file translator_eo.h.
    {
      QCString result((first_capital ? "Dosiero" : "dosiero"));
      if (!singular) result+="j";
      return result;
    }
trFile() [2/2]
virtual QCString TranslatorEsperanto::trFile (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1206 of file translator_eo.h.
    {
      QCString result((first_capital ? "Dosiero" : "dosiero"));
      if (!singular) result+="j";
      return result;
    }
trFileDocumentation() [1/2]
virtual QCString TranslatorEsperanto::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 414 of file translator_eo.h.
    { return "Dosiera Dokumentado"; }
trFileDocumentation() [2/2]
virtual QCString TranslatorEsperanto::trFileDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 414 of file translator_eo.h.
    { return "Dosiera Dokumentado"; }
trFileIn() [1/2]
virtual QCString TranslatorEsperanto::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1777 of file translator_eo.h.
    {
      return "Dosiero en "+name;
    }
References setup::name.
trFileIn() [2/2]
virtual QCString TranslatorEsperanto::trFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1777 of file translator_eo.h.
    {
      return "Dosiero en "+name;
    }
References setup::name.
trFileIndex() [1/2]
virtual QCString TranslatorEsperanto::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 383 of file translator_eo.h.
    { return "Dosiera Indekso"; }
trFileIndex() [2/2]
virtual QCString TranslatorEsperanto::trFileIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 383 of file translator_eo.h.
    { return "Dosiera Indekso"; }
trFileList() [1/2]
virtual QCString TranslatorEsperanto::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 196 of file translator_eo.h.
    { return "Dosieraro"; }
trFileList() [2/2]
virtual QCString TranslatorEsperanto::trFileList () [inline], [virtual]
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 196 of file translator_eo.h.
    { return "Dosieraro"; }
trFileListDescription() [1/2]
virtual QCString TranslatorEsperanto::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 244 of file translator_eo.h.
    {
      QCString result="Jen listo de iuj ";
      if (!extractAll) result+="dokumentitaj ";
      result+="dosieroj kun mallongaj priskriboj:";
      return result;
    }
trFileListDescription() [2/2]
virtual QCString TranslatorEsperanto::trFileListDescription (bool extractAll) [inline], [virtual]
This is an introduction to the list with all files.
Implements Translator.
Definition at line 244 of file translator_eo.h.
    {
      QCString result="Jen listo de iuj ";
      if (!extractAll) result+="dokumentitaj ";
      result+="dosieroj kun mallongaj priskriboj:";
      return result;
    }
trFileMembers() [1/2]
virtual QCString TranslatorEsperanto::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 213 of file translator_eo.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Mallokalaoj";
      }
      else
      {
        return "Dosieraj Membroj";
      }
    }
References Config_getBool.
trFileMembers() [2/2]
virtual QCString TranslatorEsperanto::trFileMembers () [inline], [virtual]
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 213 of file translator_eo.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Mallokalaoj";
      }
      else
      {
        return "Dosieraj Membroj";
      }
    }
References Config_getBool.
trFileMembersDescription() [1/2]
virtual QCString TranslatorEsperanto::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 314 of file translator_eo.h.
    {
      QCString result="Jen listo de iuj ";
      if (!extractAll) result+="dokumentitaj ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funkcioj, variabloj, difinoj, enumeracioj kaj tipodifinoj";
      }
      else
      {
        result+="dosieraj membroj";
      }
      result+=" kun ligiloj al ";
      if (extractAll)
        result+="la dosieroj al kiuj ili apartenas:";
      else
        result+="la dokumentado:";
      return result;
    }
References Config_getBool.
trFileMembersDescription() [2/2]
virtual QCString TranslatorEsperanto::trFileMembersDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 314 of file translator_eo.h.
    {
      QCString result="Jen listo de iuj ";
      if (!extractAll) result+="dokumentitaj ";
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        result+="funkcioj, variabloj, difinoj, enumeracioj kaj tipodifinoj";
      }
      else
      {
        result+="dosieraj membroj";
      }
      result+=" kun ligiloj al ";
      if (extractAll)
        result+="la dosieroj al kiuj ili apartenas:";
      else
        result+="la dokumentado:";
      return result;
    }
References Config_getBool.
trFileReference() [1/2]
virtual QCString TranslatorEsperanto::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 617 of file translator_eo.h.
    {
      QCString result=fileName;
      result+=" Dosiera referenco";
      return result;
    }
trFileReference() [2/2]
virtual QCString TranslatorEsperanto::trFileReference (const QCString & fileName) [inline], [virtual]
used as the title of the HTML page of a file
Implements Translator.
Definition at line 617 of file translator_eo.h.
    {
      QCString result=fileName;
      result+=" Dosiera referenco";
      return result;
    }
trFriends() [1/2]
virtual QCString TranslatorEsperanto::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 577 of file translator_eo.h.
    { return "Amikoj"; }
trFriends() [2/2]
virtual QCString TranslatorEsperanto::trFriends () [inline], [virtual]
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 577 of file translator_eo.h.
    { return "Amikoj"; }
trFunctionDocumentation() [1/2]
virtual QCString TranslatorEsperanto::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 484 of file translator_eo.h.
    { return "Funkcia Dokumentado"; }
trFunctionDocumentation() [2/2]
virtual QCString TranslatorEsperanto::trFunctionDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 484 of file translator_eo.h.
    { return "Funkcia Dokumentado"; }
trFunctions() [1/2]
virtual QCString TranslatorEsperanto::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 448 of file translator_eo.h.
    { return "Funkcioj"; }
trFunctions() [2/2]
virtual QCString TranslatorEsperanto::trFunctions () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 448 of file translator_eo.h.
    { return "Funkcioj"; }
trGeneratedAt() [1/2]
virtual QCString TranslatorEsperanto::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 511 of file translator_eo.h.
    {
      QCString result="Generita la "+date;
      if (!projName.isEmpty()) result+=" por "+projName;
      result+=" de";
      return result;
    }
References QCString::isEmpty().
trGeneratedAt() [2/2]
virtual QCString TranslatorEsperanto::trGeneratedAt (const QCString & date, const QCString & projName) [inline], [virtual]
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 511 of file translator_eo.h.
    {
      QCString result="Generita la "+date;
      if (!projName.isEmpty()) result+=" por "+projName;
      result+=" de";
      return result;
    }
References QCString::isEmpty().
trGeneratedAutomatically() [1/2]
virtual QCString TranslatorEsperanto::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 151 of file translator_eo.h.
    { QCString result="Generita atomate de Doxygen";
      if (!s.isEmpty()) result+=" por "+s;
      result+=" el la fontkodo.";
      return result;
    }
References s.
trGeneratedAutomatically() [2/2]
virtual QCString TranslatorEsperanto::trGeneratedAutomatically (const QCString & s) [inline], [virtual]
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 151 of file translator_eo.h.
    { QCString result="Generita atomate de Doxygen";
      if (!s.isEmpty()) result+=" por "+s;
      result+=" el la fontkodo.";
      return result;
    }
References s.
trGeneratedBy() [1/2]
virtual QCString TranslatorEsperanto::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 554 of file translator_eo.h.
    { return "Generita de"; }
trGeneratedBy() [2/2]
virtual QCString TranslatorEsperanto::trGeneratedBy () [inline], [virtual]
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 554 of file translator_eo.h.
    { return "Generita de"; }
trGeneratedFromFiles() [1/2]
virtual QCString TranslatorEsperanto::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 755 of file translator_eo.h.
    { // single is true implies a single file
      QCString result="La dokumentado por tiu i ";
      switch(compType)
      {
        case ClassDef::Class: result+="klaso"; break;
        case ClassDef::Struct: result+="strukturo"; break;
        case ClassDef::Union: result+="kunigo"; break;
        case ClassDef::Interface: result+="interfaco"; break;
        case ClassDef::Protocol: result+="protokolo"; break;
        case ClassDef::Category: result+="kategorio"; break;
        case ClassDef::Exception: result+="escepto"; break;
        default: break;
      }
      result+=" generitas el la ";
      if (single) result+="sekva dosiero:";
      else result+="sekvaj dosieroj:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFiles() [2/2]
virtual QCString TranslatorEsperanto::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 755 of file translator_eo.h.
    { // single is true implies a single file
      QCString result="La dokumentado por tiu i ";
      switch(compType)
      {
        case ClassDef::Class: result+="klaso"; break;
        case ClassDef::Struct: result+="strukturo"; break;
        case ClassDef::Union: result+="kunigo"; break;
        case ClassDef::Interface: result+="interfaco"; break;
        case ClassDef::Protocol: result+="protokolo"; break;
        case ClassDef::Category: result+="kategorio"; break;
        case ClassDef::Exception: result+="escepto"; break;
        default: break;
      }
      result+=" generitas el la ";
      if (single) result+="sekva dosiero:";
      else result+="sekvaj dosieroj:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [1/2]
virtual QCString TranslatorEsperanto::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1688 of file translator_eo.h.
    {
      // single is true implies a single file
      QCString result="La dokumentado por tiu i ";
      switch(compType)
      {
        case ClassDef::Class: result+="modulo"; break;
        case ClassDef::Struct: result+="tipo"; break;
        case ClassDef::Union: result+="kunigo"; break;
        case ClassDef::Interface: result+="interfaco"; break;
        case ClassDef::Protocol: result+="protokolo"; break;
        case ClassDef::Category: result+="kategorio"; break;
        case ClassDef::Exception: result+="escepto"; break;
        default: break;
      }
      result+=" kreiis el la ";
      if (single) result+="sekva dosiero:"; else result+="sekvaj dosieroj:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran() [2/2]
virtual QCString TranslatorEsperanto::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) [inline], [virtual]
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1688 of file translator_eo.h.
    {
      // single is true implies a single file
      QCString result="La dokumentado por tiu i ";
      switch(compType)
      {
        case ClassDef::Class: result+="modulo"; break;
        case ClassDef::Struct: result+="tipo"; break;
        case ClassDef::Union: result+="kunigo"; break;
        case ClassDef::Interface: result+="interfaco"; break;
        case ClassDef::Protocol: result+="protokolo"; break;
        case ClassDef::Category: result+="kategorio"; break;
        case ClassDef::Exception: result+="escepto"; break;
        default: break;
      }
      result+=" kreiis el la ";
      if (single) result+="sekva dosiero:"; else result+="sekvaj dosieroj:";
      return result;
    }
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal() [1/2]
virtual QCString TranslatorEsperanto::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1261 of file translator_eo.h.
    {
      QCString result((first_capital ? "Mallokalao" : "mallokalao"));
      if (!singular) result+="j";
      return result;
    }
trGlobal() [2/2]
virtual QCString TranslatorEsperanto::trGlobal (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1261 of file translator_eo.h.
    {
      QCString result((first_capital ? "Mallokalao" : "mallokalao"));
      if (!singular) result+="j";
      return result;
    }
trGlobalNamespace() [1/2]
virtual QCString TranslatorEsperanto::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1752 of file translator_eo.h.
    {
      return "Malloka Nomspaco";
    }
trGlobalNamespace() [2/2]
virtual QCString TranslatorEsperanto::trGlobalNamespace () [inline], [virtual]
Label used for search results in the global namespace
Implements Translator.
Definition at line 1752 of file translator_eo.h.
    {
      return "Malloka Nomspaco";
    }
trGotoDocumentation() [1/2]
virtual QCString TranslatorEsperanto::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 842 of file translator_eo.h.
    {
      return "Iri al la dokumentado de tiu i dosiero.";
    }
trGotoDocumentation() [2/2]
virtual QCString TranslatorEsperanto::trGotoDocumentation () [inline], [virtual]
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 842 of file translator_eo.h.
    {
      return "Iri al la dokumentado de tiu i dosiero.";
    }
trGotoGraphicalHierarchy() [1/2]
virtual QCString TranslatorEsperanto::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 875 of file translator_eo.h.
    {
      return "Iri al la grafika klasa hierarkio";
    }
trGotoGraphicalHierarchy() [2/2]
virtual QCString TranslatorEsperanto::trGotoGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 875 of file translator_eo.h.
    {
      return "Iri al la grafika klasa hierarkio";
    }
trGotoSourceCode() [1/2]
virtual QCString TranslatorEsperanto::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 837 of file translator_eo.h.
    {
      return "Iri al la fontkodo de tiu i dosiero.";
    }
trGotoSourceCode() [2/2]
virtual QCString TranslatorEsperanto::trGotoSourceCode () [inline], [virtual]
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 837 of file translator_eo.h.
    {
      return "Iri al la fontkodo de tiu i dosiero.";
    }
trGotoTextualHierarchy() [1/2]
virtual QCString TranslatorEsperanto::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 879 of file translator_eo.h.
    {
      return "Iri al la teksta klasa hierarkio";
    }
trGotoTextualHierarchy() [2/2]
virtual QCString TranslatorEsperanto::trGotoTextualHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 879 of file translator_eo.h.
    {
      return "Iri al la teksta klasa hierarkio";
    }
trGraphicalHierarchy() [1/2]
virtual QCString TranslatorEsperanto::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 871 of file translator_eo.h.
    {
      return "Grafika Klasa Hierarkio";
    }
trGraphicalHierarchy() [2/2]
virtual QCString TranslatorEsperanto::trGraphicalHierarchy () [inline], [virtual]
Implements Translator.
Definition at line 871 of file translator_eo.h.
    {
      return "Grafika Klasa Hierarkio";
    }
trGroup() [1/2]
virtual QCString TranslatorEsperanto::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1228 of file translator_eo.h.
    {
      QCString result((first_capital ? "Grupo" : "grupo"));
      if (!singular) result+="j";
      return result;
    }
trGroup() [2/2]
virtual QCString TranslatorEsperanto::trGroup (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1228 of file translator_eo.h.
    {
      QCString result((first_capital ? "Grupo" : "grupo"));
      if (!singular) result+="j";
      return result;
    }
trHierarchicalIndex() [1/2]
virtual QCString TranslatorEsperanto::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 362 of file translator_eo.h.
    { return "Hierarkia Indekso"; }
trHierarchicalIndex() [2/2]
virtual QCString TranslatorEsperanto::trHierarchicalIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 362 of file translator_eo.h.
    { return "Hierarkia Indekso"; }
trImplementedFromList() [1/2]
virtual QCString TranslatorEsperanto::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1299 of file translator_eo.h.
    {
      return "Realigas "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedFromList() [2/2]
virtual QCString TranslatorEsperanto::trImplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1299 of file translator_eo.h.
    {
      return "Realigas "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [1/2]
virtual QCString TranslatorEsperanto::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1307 of file translator_eo.h.
    {
      return "Realigita en "+trWriteList(numEntries)+".";
    }
References trWriteList().
trImplementedInList() [2/2]
virtual QCString TranslatorEsperanto::trImplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1307 of file translator_eo.h.
    {
      return "Realigita en "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInclByDepGraph() [1/2]
virtual QCString TranslatorEsperanto::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 971 of file translator_eo.h.
    {
      return "Tiu i diagramo montras kiuj dosieroj rekte a malrekte "
             "inkluzivas tiun i dosieron:";
    }
trInclByDepGraph() [2/2]
virtual QCString TranslatorEsperanto::trInclByDepGraph () [inline], [virtual]
Implements Translator.
Definition at line 971 of file translator_eo.h.
    {
      return "Tiu i diagramo montras kiuj dosieroj rekte a malrekte "
             "inkluzivas tiun i dosieron:";
    }
trInclDepGraph() [1/2]
virtual QCString TranslatorEsperanto::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 827 of file translator_eo.h.
    {
      return "Inkluzivaa dependeca diagramo por "+fName+":";
    }
trInclDepGraph() [2/2]
virtual QCString TranslatorEsperanto::trInclDepGraph (const QCString & fName) [inline], [virtual]
this text is put before an include dependency graph
Implements Translator.
Definition at line 827 of file translator_eo.h.
    {
      return "Inkluzivaa dependeca diagramo por "+fName+":";
    }
trIncludesFileIn() [1/2]
virtual QCString TranslatorEsperanto::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1786 of file translator_eo.h.
    {
      return "Inkluzivas dosieron en "+name;
    }
References setup::name.
trIncludesFileIn() [2/2]
virtual QCString TranslatorEsperanto::trIncludesFileIn (const QCString & name) [inline], [virtual]
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1786 of file translator_eo.h.
    {
      return "Inkluzivas dosieron en "+name;
    }
References setup::name.
trIncludingInheritedMembers() [1/2]
virtual QCString TranslatorEsperanto::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 145 of file translator_eo.h.
    { return ", inkluzive iujn hereditajn membrojn."; }
trIncludingInheritedMembers() [2/2]
virtual QCString TranslatorEsperanto::trIncludingInheritedMembers () [inline], [virtual]
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 145 of file translator_eo.h.
    { return ", inkluzive iujn hereditajn membrojn."; }
trInheritedByList() [1/2]
virtual QCString TranslatorEsperanto::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 689 of file translator_eo.h.
    {
      return "Heredita de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedByList() [2/2]
virtual QCString TranslatorEsperanto::trInheritedByList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 689 of file translator_eo.h.
    {
      return "Heredita de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritedFrom() [1/2]
virtual QCString TranslatorEsperanto::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1892 of file translator_eo.h.
    { return QCString(members)+" heredita el "+what; }
trInheritedFrom() [2/2]
virtual QCString TranslatorEsperanto::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Used for a section containing inherited members
Implements Translator.
Definition at line 1892 of file translator_eo.h.
    { return QCString(members)+" heredita el "+what; }
trInheritsList() [1/2]
virtual QCString TranslatorEsperanto::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 681 of file translator_eo.h.
    {
      return "Heredas de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInheritsList() [2/2]
virtual QCString TranslatorEsperanto::trInheritsList (int numEntries) [inline], [virtual]
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 681 of file translator_eo.h.
    {
      return "Heredas de "+trWriteList(numEntries)+".";
    }
References trWriteList().
trInitialValue() [1/2]
virtual QCString TranslatorEsperanto::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 862 of file translator_eo.h.
    {
      return "Komenca valoro:";
    }
trInitialValue() [2/2]
virtual QCString TranslatorEsperanto::trInitialValue () [inline], [virtual]
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 862 of file translator_eo.h.
    {
      return "Komenca valoro:";
    }
trInstanceMethods() [1/2]
virtual QCString TranslatorEsperanto::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1944 of file translator_eo.h.
    {
      return "Aperaj Metodoj";
    }
trInstanceMethods() [2/2]
virtual QCString TranslatorEsperanto::trInstanceMethods () [inline], [virtual]
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1944 of file translator_eo.h.
    {
      return "Aperaj Metodoj";
    }
trInvariant() [1/2]
virtual QCString TranslatorEsperanto::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 857 of file translator_eo.h.
    {
      return "Malvariao";
    }
trInvariant() [2/2]
virtual QCString TranslatorEsperanto::trInvariant () [inline], [virtual]
Text for the \invariant command
Implements Translator.
Definition at line 857 of file translator_eo.h.
    {
      return "Malvariao";
    }
trISOLang() [1/2]
virtual QCString TranslatorEsperanto::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 79 of file translator_eo.h.
    {
      return "eo";
    }
trISOLang() [2/2]
virtual QCString TranslatorEsperanto::trISOLang () [inline], [virtual]
Implements Translator.
Definition at line 79 of file translator_eo.h.
    {
      return "eo";
    }
trLegend() [1/2]
virtual QCString TranslatorEsperanto::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1055 of file translator_eo.h.
    {
      return "klarigeto";
    }
trLegend() [2/2]
virtual QCString TranslatorEsperanto::trLegend () [inline], [virtual]
text for the link to the legend page
Implements Translator.
Definition at line 1055 of file translator_eo.h.
    {
      return "klarigeto";
    }
trLegendDocs() [1/2]
virtual QCString TranslatorEsperanto::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 993 of file translator_eo.h.
    {
      return
        "Tiu i pao klarigas kiel interpreti la diagramojn generitajn "
        "de doxygen.<p>\n"
        "Konsideru la sekvan ekzemplon:\n"
        "\\code\n"
        "/*! Nevidebla klaso pro trunkado */\n"
        "class Invisible { };\n\n"
        "/*! Trunkita klaso, hereda rilato kaias */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Klaso ne dokumentita per komentoj de doxygen */\n"
        "class Undocumented { };\n\n"
        "/*! Klaso de kiu heredias per publika heredado */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! ablona klaso */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Klaso de kiu heredias per protektita heredado */\n"
        "class ProtectedBase { };\n\n"
        "/*! Klaso de kiu heredias per privata heredado */\n"
        "class PrivateBase { };\n\n"
        "/*! Klaso uzata de la klaso Inherited */\n"
        "class Used { };\n\n"
        "/*! Supra klaso kiu heredas de kelkaj aliaj klasoj */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Tio i liveros la sekvan diagramon:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "La skatoloj de la supra diagramo havas la sekvajn signifojn:\n"
        "<ul>\n"
        "<li>%Plene griza skatolo reprezentas la strukturon a klason "
        "kies diagramo generiis.\n"
        "<li>%Skatolo kun nigra bordero montras dokumentitan strukturon a klason.\n"
        "<li>%Skatolo kun griza bordero montras nedokumentitan strukturon a klason.\n"
        "<li>%Skatolo kun rua bordero montras dokumentitan strukturon a klason por "
        "kiu ne iuj heredadoj/enhavoj montrias. %Diagramo estas trunkota "
        "se i ne adaptias en la donitajn limojn.\n"
        "</ul>\n"
        "La sagoj havas la sekvajn signifojn:\n"
        "<ul>\n"
        "<li>%Malhelblua sago uzatas por montri publika heredado "
        "inter du klasoj.\n"
        "<li>%Malhelverda sago uzatas por protektita heredado.\n"
        "<li>%Malhelrua sago uzatas por privata heredado.\n"
        "<li>%Purpura streka sago uzatas se klaso enhavatas a uzatas "
        "de alia klaso. La sago estas etikedatas kun la variablo(j) "
        "tra kiu la montrita klaso a strukturo estas alirebla.\n"
        "<li>%Flava streka sago montras rilato inter ablona apero kaj "
        "la ablona klaso el kiu i realigitas. La sago etikeditas kun "
        "la parametroj de la ablona apero.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendDocs() [2/2]
virtual QCString TranslatorEsperanto::trLegendDocs () [inline], [virtual]
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called `A`.
Implements Translator.
Definition at line 993 of file translator_eo.h.
    {
      return
        "Tiu i pao klarigas kiel interpreti la diagramojn generitajn "
        "de doxygen.<p>\n"
        "Konsideru la sekvan ekzemplon:\n"
        "\\code\n"
        "/*! Nevidebla klaso pro trunkado */\n"
        "class Invisible { };\n\n"
        "/*! Trunkita klaso, hereda rilato kaias */\n"
        "class Truncated : public Invisible { };\n\n"
        "/* Klaso ne dokumentita per komentoj de doxygen */\n"
        "class Undocumented { };\n\n"
        "/*! Klaso de kiu heredias per publika heredado */\n"
        "class PublicBase : public Truncated { };\n\n"
        "/*! ablona klaso */\n"
        "template<class T> class Templ { };\n\n"
        "/*! Klaso de kiu heredias per protektita heredado */\n"
        "class ProtectedBase { };\n\n"
        "/*! Klaso de kiu heredias per privata heredado */\n"
        "class PrivateBase { };\n\n"
        "/*! Klaso uzata de la klaso Inherited */\n"
        "class Used { };\n\n"
        "/*! Supra klaso kiu heredas de kelkaj aliaj klasoj */\n"
        "class Inherited : public PublicBase,\n"
        " protected ProtectedBase,\n"
        " private PrivateBase,\n"
        " public Undocumented,\n"
        " public Templ<int>\n"
        "{\n"
        " private:\n"
        " Used *m_usedClass;\n"
        "};\n"
        "\\endcode\n"
        "Tio i liveros la sekvan diagramon:"
        "<p><center><img alt=\"\" src=\"graph_legend."+getDotImageExtension()+"\"></center>\n"
        "<p>\n"
        "La skatoloj de la supra diagramo havas la sekvajn signifojn:\n"
        "<ul>\n"
        "<li>%Plene griza skatolo reprezentas la strukturon a klason "
        "kies diagramo generiis.\n"
        "<li>%Skatolo kun nigra bordero montras dokumentitan strukturon a klason.\n"
        "<li>%Skatolo kun griza bordero montras nedokumentitan strukturon a klason.\n"
        "<li>%Skatolo kun rua bordero montras dokumentitan strukturon a klason por "
        "kiu ne iuj heredadoj/enhavoj montrias. %Diagramo estas trunkota "
        "se i ne adaptias en la donitajn limojn.\n"
        "</ul>\n"
        "La sagoj havas la sekvajn signifojn:\n"
        "<ul>\n"
        "<li>%Malhelblua sago uzatas por montri publika heredado "
        "inter du klasoj.\n"
        "<li>%Malhelverda sago uzatas por protektita heredado.\n"
        "<li>%Malhelrua sago uzatas por privata heredado.\n"
        "<li>%Purpura streka sago uzatas se klaso enhavatas a uzatas "
        "de alia klaso. La sago estas etikedatas kun la variablo(j) "
        "tra kiu la montrita klaso a strukturo estas alirebla.\n"
        "<li>%Flava streka sago montras rilato inter ablona apero kaj "
        "la ablona klaso el kiu i realigitas. La sago etikeditas kun "
        "la parametroj de la ablona apero.\n"
        "</ul>\n";
    }
References getDotImageExtension().
trLegendTitle() [1/2]
virtual QCString TranslatorEsperanto::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 986 of file translator_eo.h.
    {
      return "Diagrama Klarigeto";
    }
trLegendTitle() [2/2]
virtual QCString TranslatorEsperanto::trLegendTitle () [inline], [virtual]
title of the graph legend page
Implements Translator.
Definition at line 986 of file translator_eo.h.
    {
      return "Diagrama Klarigeto";
    }
trListOfAllMembers() [1/2]
virtual QCString TranslatorEsperanto::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 133 of file translator_eo.h.
    { return "Listo de iuj membroj"; }
trListOfAllMembers() [2/2]
virtual QCString TranslatorEsperanto::trListOfAllMembers () [inline], [virtual]
put in the class documentation
Implements Translator.
Definition at line 133 of file translator_eo.h.
    { return "Listo de iuj membroj"; }
trLoading() [1/2]
virtual QCString TranslatorEsperanto::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1746 of file translator_eo.h.
    {
      return "arante...";
    }
trLoading() [2/2]
virtual QCString TranslatorEsperanto::trLoading () [inline], [virtual]
Loading message shown when loading search results
Implements Translator.
Definition at line 1746 of file translator_eo.h.
    {
      return "arante...";
    }
trMainPage() [1/2]
virtual QCString TranslatorEsperanto::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 786 of file translator_eo.h.
    { return "efa Pao"; }
trMainPage() [2/2]
virtual QCString TranslatorEsperanto::trMainPage () [inline], [virtual]
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 786 of file translator_eo.h.
    { return "efa Pao"; }
trMember() [1/2]
virtual QCString TranslatorEsperanto::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1250 of file translator_eo.h.
    {
      QCString result((first_capital ? "Membro" : "membro"));
      if (!singular) result+="j";
      return result;
    }
trMember() [2/2]
virtual QCString TranslatorEsperanto::trMember (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1250 of file translator_eo.h.
    {
      QCString result((first_capital ? "Membro" : "membro"));
      if (!singular) result+="j";
      return result;
    }
trMemberDataDocumentation() [1/2]
virtual QCString TranslatorEsperanto::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 116 of file translator_eo.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Kampa Dokumentado";
      }
      else
      {
        return "Dokumentado de la Membraj Datumoj";
      }
    }
References Config_getBool.
trMemberDataDocumentation() [2/2]
virtual QCString TranslatorEsperanto::trMemberDataDocumentation () [inline], [virtual]
header that is put before the list of member attributes.
Implements Translator.
Definition at line 116 of file translator_eo.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Kampa Dokumentado";
      }
      else
      {
        return "Dokumentado de la Membraj Datumoj";
      }
    }
References Config_getBool.
trMemberEnumerationDocumentation() [1/2]
virtual QCString TranslatorEsperanto::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 108 of file translator_eo.h.
    { return "Dokumentado de la Membraj Enumeracioj"; }
trMemberEnumerationDocumentation() [2/2]
virtual QCString TranslatorEsperanto::trMemberEnumerationDocumentation () [inline], [virtual]
header that is put before the list of enumerations.
Implements Translator.
Definition at line 108 of file translator_eo.h.
    { return "Dokumentado de la Membraj Enumeracioj"; }
trMemberFunctionDocumentation() [1/2]
virtual QCString TranslatorEsperanto::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 112 of file translator_eo.h.
    { return "Dokumentado de la Membraj Funkcioj"; }
trMemberFunctionDocumentation() [2/2]
virtual QCString TranslatorEsperanto::trMemberFunctionDocumentation () [inline], [virtual]
header that is put before the list of member functions.
Implements Translator.
Definition at line 112 of file translator_eo.h.
    { return "Dokumentado de la Membraj Funkcioj"; }
trMemberFunctionDocumentationFortran() [1/2]
virtual QCString TranslatorEsperanto::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1540 of file translator_eo.h.
    { return "Dokumentado de Membraj Funkcioj/Subrutinoj"; }
trMemberFunctionDocumentationFortran() [2/2]
virtual QCString TranslatorEsperanto::trMemberFunctionDocumentationFortran () [inline], [virtual]
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1540 of file translator_eo.h.
    { return "Dokumentado de Membraj Funkcioj/Subrutinoj"; }
trMemberList() [1/2]
virtual QCString TranslatorEsperanto::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 137 of file translator_eo.h.
    { return "Membra Listo"; }
trMemberList() [2/2]
virtual QCString TranslatorEsperanto::trMemberList () [inline], [virtual]
used as the title of the `list of all members` page of a class
Implements Translator.
Definition at line 137 of file translator_eo.h.
    { return "Membra Listo"; }
trMemberTypedefDocumentation() [1/2]
virtual QCString TranslatorEsperanto::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 104 of file translator_eo.h.
    { return "Dokumentado de la Membraj Tipodifinoj"; }
trMemberTypedefDocumentation() [2/2]
virtual QCString TranslatorEsperanto::trMemberTypedefDocumentation () [inline], [virtual]
header that is put before the list of typedefs.
Implements Translator.
Definition at line 104 of file translator_eo.h.
    { return "Dokumentado de la Membraj Tipodifinoj"; }
trMethodDocumentation() [1/2]
virtual QCString TranslatorEsperanto::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1951 of file translator_eo.h.
    {
      return "Dokumentaro de la Metodo";
    }
trMethodDocumentation() [2/2]
virtual QCString TranslatorEsperanto::trMethodDocumentation () [inline], [virtual]
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 1951 of file translator_eo.h.
    {
      return "Dokumentaro de la Metodo";
    }
trModule() [1/2]
virtual QCString TranslatorEsperanto::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1679 of file translator_eo.h.
    {
      QCString result((first_capital ? "Modulo" : "modulo"));
      if (!singular) result+="j";
      return result;
    }
trModule() [2/2]
virtual QCString TranslatorEsperanto::trModule (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1679 of file translator_eo.h.
    {
      QCString result((first_capital ? "Modulo" : "modulo"));
      if (!singular) result+="j";
      return result;
    }
trModuleDocumentation() [1/2]
virtual QCString TranslatorEsperanto::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 389 of file translator_eo.h.
    { return "Modula Dokumentado"; }
trModuleDocumentation() [2/2]
virtual QCString TranslatorEsperanto::trModuleDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 389 of file translator_eo.h.
    { return "Modula Dokumentado"; }
trModuleIndex() [1/2]
virtual QCString TranslatorEsperanto::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 356 of file translator_eo.h.
    { return "Modula Indekso"; }
trModuleIndex() [2/2]
virtual QCString TranslatorEsperanto::trModuleIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 356 of file translator_eo.h.
    { return "Modula Indekso"; }
trModuleReference() [1/2]
virtual QCString TranslatorEsperanto::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1641 of file translator_eo.h.
    {
      QCString result=namespaceName;
      result+=" Modula Referenco";
      return result;
    }
trModuleReference() [2/2]
virtual QCString TranslatorEsperanto::trModuleReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1641 of file translator_eo.h.
    {
      QCString result=namespaceName;
      result+=" Modula Referenco";
      return result;
    }
trModules() [1/2]
virtual QCString TranslatorEsperanto::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 175 of file translator_eo.h.
    { return "Moduloj"; }
trModules() [2/2]
virtual QCString TranslatorEsperanto::trModules () [inline], [virtual]
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 175 of file translator_eo.h.
    { return "Moduloj"; }
trModulesDescription() [1/2]
virtual QCString TranslatorEsperanto::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 344 of file translator_eo.h.
    { return "Jen listo de iuj la moduloj:"; }
trModulesDescription() [2/2]
virtual QCString TranslatorEsperanto::trModulesDescription () [inline], [virtual]
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 344 of file translator_eo.h.
    { return "Jen listo de iuj la moduloj:"; }
trModulesIndex() [1/2]
virtual QCString TranslatorEsperanto::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1672 of file translator_eo.h.
    { return "Indekso de Moduloj"; }
trModulesIndex() [2/2]
virtual QCString TranslatorEsperanto::trModulesIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1672 of file translator_eo.h.
    { return "Indekso de Moduloj"; }
trModulesList() [1/2]
virtual QCString TranslatorEsperanto::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1607 of file translator_eo.h.
    { return "Modula Listo"; }
trModulesList() [2/2]
virtual QCString TranslatorEsperanto::trModulesList () [inline], [virtual]
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1607 of file translator_eo.h.
    { return "Modula Listo"; }
trModulesListDescription() [1/2]
virtual QCString TranslatorEsperanto::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1611 of file translator_eo.h.
    {
      QCString result="Jen listo de iuj ";
      if (!extractAll) result+="dokumentitaj ";
      result+="moduloj kun mallongaj priskriboj:";
      return result;
    }
trModulesListDescription() [2/2]
virtual QCString TranslatorEsperanto::trModulesListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1611 of file translator_eo.h.
    {
      QCString result="Jen listo de iuj ";
      if (!extractAll) result+="dokumentitaj ";
      result+="moduloj kun mallongaj priskriboj:";
      return result;
    }
trModulesMemberDescription() [1/2]
virtual QCString TranslatorEsperanto::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1653 of file translator_eo.h.
    {
      QCString result="Jen listo de iuj ";
      if (!extractAll) result+="dokumentitaj ";
      result+="modulaj membroj kun ligiloj al la ";
      if (extractAll)
      {
        result+="modula dokumentado de iu membro:";
      }
      else
      {
        result+="moduloj al kiuj ili apartenas:";
      }
      return result;
    }
trModulesMemberDescription() [2/2]
virtual QCString TranslatorEsperanto::trModulesMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1653 of file translator_eo.h.
    {
      QCString result="Jen listo de iuj ";
      if (!extractAll) result+="dokumentitaj ";
      result+="modulaj membroj kun ligiloj al la ";
      if (extractAll)
      {
        result+="modula dokumentado de iu membro:";
      }
      else
      {
        result+="moduloj al kiuj ili apartenas:";
      }
      return result;
    }
trModulesMembers() [1/2]
virtual QCString TranslatorEsperanto::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1649 of file translator_eo.h.
    { return "Modulaj Membroj"; }
trModulesMembers() [2/2]
virtual QCString TranslatorEsperanto::trModulesMembers () [inline], [virtual]
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1649 of file translator_eo.h.
    { return "Modulaj Membroj"; }
trMonth() [1/2]
virtual QCString TranslatorEsperanto::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1833 of file translator_eo.h.
    {
      static const char *months_short[] = { "jan", "feb", "mar", "apr", "maj", "jun", "jul", "ag", "sep", "okt", "nov", "dec" };
      static const char *months_full[] = { "januaro", "februaro", "marto", "aprilo", "majo", "junio", "julio", "agusto", "septembro", "oktobro", "novembro", "decembro" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMonth() [2/2]
virtual QCString TranslatorEsperanto::trMonth (int month, bool first_capital, bool full) [inline], [virtual]
Implements Translator.
Definition at line 1833 of file translator_eo.h.
    {
      static const char *months_short[] = { "jan", "feb", "mar", "apr", "maj", "jun", "jul", "ag", "sep", "okt", "nov", "dec" };
      static const char *months_full[] = { "januaro", "februaro", "marto", "aprilo", "majo", "junio", "julio", "agusto", "septembro", "oktobro", "novembro", "decembro" };
      QCString text = full? months_full[month-1] : months_short[month-1];
      if (first_capital) return text.mid(0,1).upper()+text.mid(1);
      else return text;
    }
References QCString::mid(), and QCString::upper().
trMore() [1/2]
virtual QCString TranslatorEsperanto::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 129 of file translator_eo.h.
    { return "Pli..."; }
trMore() [2/2]
virtual QCString TranslatorEsperanto::trMore () [inline], [virtual]
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 129 of file translator_eo.h.
    { return "Pli..."; }
trNamespace() [1/2]
virtual QCString TranslatorEsperanto::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1217 of file translator_eo.h.
    {
      QCString result((first_capital ? "Nomspaco" : "nomspaco"));
      if (!singular) result+="j";
      return result;
    }
trNamespace() [2/2]
virtual QCString TranslatorEsperanto::trNamespace (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1217 of file translator_eo.h.
    {
      QCString result((first_capital ? "Nomspaco" : "nomspaco"));
      if (!singular) result+="j";
      return result;
    }
trNamespaceDocumentation() [1/2]
virtual QCString TranslatorEsperanto::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 735 of file translator_eo.h.
    { return "Nomspaca Dokumentado"; }
trNamespaceDocumentation() [2/2]
virtual QCString TranslatorEsperanto::trNamespaceDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 735 of file translator_eo.h.
    { return "Nomspaca Dokumentado"; }
trNamespaceIndex() [1/2]
virtual QCString TranslatorEsperanto::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 729 of file translator_eo.h.
    { return "Nomspaca Indekso"; }
trNamespaceIndex() [2/2]
virtual QCString TranslatorEsperanto::trNamespaceIndex () [inline], [virtual]
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 729 of file translator_eo.h.
    { return "Nomspaca Indekso"; }
trNamespaceList() [1/2]
virtual QCString TranslatorEsperanto::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 562 of file translator_eo.h.
    { return "Nomspacaro"; }
trNamespaceList() [2/2]
virtual QCString TranslatorEsperanto::trNamespaceList () [inline], [virtual]
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 562 of file translator_eo.h.
    { return "Nomspacaro"; }
trNamespaceListDescription() [1/2]
virtual QCString TranslatorEsperanto::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 566 of file translator_eo.h.
    {
      QCString result="Jen listo de iuj ";
      if (!extractAll) result+="dokumentitaj ";
      result+="nomspacoj kun mallongaj priskriboj:";
      return result;
    }
trNamespaceListDescription() [2/2]
virtual QCString TranslatorEsperanto::trNamespaceListDescription (bool extractAll) [inline], [virtual]
used as an introduction to the namespace list
Implements Translator.
Definition at line 566 of file translator_eo.h.
    {
      QCString result="Jen listo de iuj ";
      if (!extractAll) result+="dokumentitaj ";
      result+="nomspacoj kun mallongaj priskriboj:";
      return result;
    }
trNamespaceMemberDescription() [1/2]
virtual QCString TranslatorEsperanto::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 715 of file translator_eo.h.
    {
      QCString result="Jen listo de iuj ";
      if (!extractAll) result+="dokumentitaj ";
      result+="nomspacaj membroj kun ligiloj al ";
      if (extractAll)
        result+="la nomspaca dokumentado de iu membro:";
      else
        result+="la nomspacoj al kiuj ili apartenas:";
      return result;
    }
trNamespaceMemberDescription() [2/2]
virtual QCString TranslatorEsperanto::trNamespaceMemberDescription (bool extractAll) [inline], [virtual]
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 715 of file translator_eo.h.
    {
      QCString result="Jen listo de iuj ";
      if (!extractAll) result+="dokumentitaj ";
      result+="nomspacaj membroj kun ligiloj al ";
      if (extractAll)
        result+="la nomspaca dokumentado de iu membro:";
      else
        result+="la nomspacoj al kiuj ili apartenas:";
      return result;
    }
trNamespaceMembers() [1/2]
virtual QCString TranslatorEsperanto::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 711 of file translator_eo.h.
    { return "Nomspacaj Membroj"; }
trNamespaceMembers() [2/2]
virtual QCString TranslatorEsperanto::trNamespaceMembers () [inline], [virtual]
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 711 of file translator_eo.h.
    { return "Nomspacaj Membroj"; }
trNamespaceReference() [1/2]
virtual QCString TranslatorEsperanto::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 625 of file translator_eo.h.
    {
      QCString result=namespaceName;
      result+=" Nomspaca referenco";
      return result;
    }
trNamespaceReference() [2/2]
virtual QCString TranslatorEsperanto::trNamespaceReference (const QCString & namespaceName) [inline], [virtual]
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 625 of file translator_eo.h.
    {
      QCString result=namespaceName;
      result+=" Nomspaca referenco";
      return result;
    }
trNamespaces() [1/2]
virtual QCString TranslatorEsperanto::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 745 of file translator_eo.h.
    { return "Nomspacoj"; }
trNamespaces() [2/2]
virtual QCString TranslatorEsperanto::trNamespaces () [inline], [virtual]
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 745 of file translator_eo.h.
    { return "Nomspacoj"; }
trNoMatches() [1/2]
virtual QCString TranslatorEsperanto::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1764 of file translator_eo.h.
    {
      return "Nenia kongruo";
    }
trNoMatches() [2/2]
virtual QCString TranslatorEsperanto::trNoMatches () [inline], [virtual]
Text shown when no search results are found
Implements Translator.
Definition at line 1764 of file translator_eo.h.
    {
      return "Nenia kongruo";
    }
trNote() [1/2]
virtual QCString TranslatorEsperanto::trNote () [inline], [virtual]
Implements Translator.
Definition at line 892 of file translator_eo.h.
    {
      return "Noto";
    }
trNote() [2/2]
virtual QCString TranslatorEsperanto::trNote () [inline], [virtual]
Implements Translator.
Definition at line 892 of file translator_eo.h.
    {
      return "Noto";
    }
trOverloadText() [1/2]
virtual QCString TranslatorEsperanto::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1512 of file translator_eo.h.
    {
       return "Tiu i estas superarita membra funkcio, "
              "donita por faciligo. i nur malsamas de la supra "
              "funkcio nur pro la argumento(j) kiujn ili akceptas.";
    }
trOverloadText() [2/2]
virtual QCString TranslatorEsperanto::trOverloadText () [inline], [virtual]
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1512 of file translator_eo.h.
    {
       return "Tiu i estas superarita membra funkcio, "
              "donita por faciligo. i nur malsamas de la supra "
              "funkcio nur pro la argumento(j) kiujn ili akceptas.";
    }
trPackage() [1/2]
virtual QCString TranslatorEsperanto::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1107 of file translator_eo.h.
    {
      return "Pakao "+name;
    }
References setup::name.
trPackage() [2/2]
virtual QCString TranslatorEsperanto::trPackage (const QCString & name) [inline], [virtual]
Used as the title of a Java package
Implements Translator.
Definition at line 1107 of file translator_eo.h.
    {
      return "Pakao "+name;
    }
References setup::name.
trPackageAttribs() [1/2]
virtual QCString TranslatorEsperanto::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1384 of file translator_eo.h.
    {
      return "Pakaaj Atributoj";
    }
trPackageAttribs() [2/2]
virtual QCString TranslatorEsperanto::trPackageAttribs () [inline], [virtual]
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1384 of file translator_eo.h.
    {
      return "Pakaaj Atributoj";
    }
trPackageFunctions() [1/2]
virtual QCString TranslatorEsperanto::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1366 of file translator_eo.h.
    {
      return "Pakaaj Funkcioj";
    }
trPackageFunctions() [2/2]
virtual QCString TranslatorEsperanto::trPackageFunctions () [inline], [virtual]
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1366 of file translator_eo.h.
    {
      return "Pakaaj Funkcioj";
    }
trPackageListDescription() [1/2]
virtual QCString TranslatorEsperanto::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1112 of file translator_eo.h.
    {
      return "Jen listo de pakaoj kun mallongaj priskriboj (se ekzistas):";
    }
trPackageListDescription() [2/2]
virtual QCString TranslatorEsperanto::trPackageListDescription () [inline], [virtual]
The description of the package index page
Implements Translator.
Definition at line 1112 of file translator_eo.h.
    {
      return "Jen listo de pakaoj kun mallongaj priskriboj (se ekzistas):";
    }
trPackageMembers() [1/2]
virtual QCString TranslatorEsperanto::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1370 of file translator_eo.h.
    {
      return "Pakaaj Membroj";
    }
trPackageMembers() [2/2]
virtual QCString TranslatorEsperanto::trPackageMembers () [inline], [virtual]
Implements Translator.
Definition at line 1370 of file translator_eo.h.
    {
      return "Pakaaj Membroj";
    }
trPackages() [1/2]
virtual QCString TranslatorEsperanto::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1117 of file translator_eo.h.
    {
      return "Pakaoj";
    }
trPackages() [2/2]
virtual QCString TranslatorEsperanto::trPackages () [inline], [virtual]
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1117 of file translator_eo.h.
    {
      return "Pakaoj";
    }
trPackageTypes() [1/2]
virtual QCString TranslatorEsperanto::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1359 of file translator_eo.h.
    {
      return "Pakaaj Tipoj";
    }
trPackageTypes() [2/2]
virtual QCString TranslatorEsperanto::trPackageTypes () [inline], [virtual]
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1359 of file translator_eo.h.
    {
      return "Pakaaj Tipoj";
    }
trPage() [1/2]
virtual QCString TranslatorEsperanto::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1239 of file translator_eo.h.
    {
      QCString result((first_capital ? "Pao" : "pao"));
      if (!singular) result+="j";
      return result;
    }
trPage() [2/2]
virtual QCString TranslatorEsperanto::trPage (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1239 of file translator_eo.h.
    {
      QCString result((first_capital ? "Pao" : "pao"));
      if (!singular) result+="j";
      return result;
    }
trPageAbbreviation() [1/2]
virtual QCString TranslatorEsperanto::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 792 of file translator_eo.h.
    { return "p."; }
trPageAbbreviation() [2/2]
virtual QCString TranslatorEsperanto::trPageAbbreviation () [inline], [virtual]
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 792 of file translator_eo.h.
    { return "p."; }
trPageIndex() [1/2]
virtual QCString TranslatorEsperanto::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 883 of file translator_eo.h.
    {
      return "Paa Indekso";
    }
trPageIndex() [2/2]
virtual QCString TranslatorEsperanto::trPageIndex () [inline], [virtual]
Implements Translator.
Definition at line 883 of file translator_eo.h.
    {
      return "Paa Indekso";
    }
trPanelSynchronisationTooltip() [1/2]
virtual QCString TranslatorEsperanto::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1909 of file translator_eo.h.
    {
      QCString opt = enable ? "aktivigi" : "malaktivigi";
      return "klaku por "+opt+" panelan sinkronigon";
    }
trPanelSynchronisationTooltip() [2/2]
virtual QCString TranslatorEsperanto::trPanelSynchronisationTooltip (bool enable) [inline], [virtual]
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1909 of file translator_eo.h.
    {
      QCString opt = enable ? "aktivigi" : "malaktivigi";
      return "klaku por "+opt+" panelan sinkronigon";
    }
trParameters() [1/2]
virtual QCString TranslatorEsperanto::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 546 of file translator_eo.h.
    { return "Parametroj"; }
trParameters() [2/2]
virtual QCString TranslatorEsperanto::trParameters () [inline], [virtual]
this text is generated when the \param command is used.
Implements Translator.
Definition at line 546 of file translator_eo.h.
    { return "Parametroj"; }
trPostcondition() [1/2]
virtual QCString TranslatorEsperanto::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 852 of file translator_eo.h.
    {
      return "Postkondio";
    }
trPostcondition() [2/2]
virtual QCString TranslatorEsperanto::trPostcondition () [inline], [virtual]
Text for the \post command
Implements Translator.
Definition at line 852 of file translator_eo.h.
    {
      return "Postkondio";
    }
trPrecondition() [1/2]
virtual QCString TranslatorEsperanto::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 847 of file translator_eo.h.
    {
      return "Antakondio";
    }
trPrecondition() [2/2]
virtual QCString TranslatorEsperanto::trPrecondition () [inline], [virtual]
Text for the \pre command
Implements Translator.
Definition at line 847 of file translator_eo.h.
    {
      return "Antakondio";
    }
trPrivateAttribs() [1/2]
virtual QCString TranslatorEsperanto::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 931 of file translator_eo.h.
    {
      return "Privataj Atributoj";
    }
trPrivateAttribs() [2/2]
virtual QCString TranslatorEsperanto::trPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 931 of file translator_eo.h.
    {
      return "Privataj Atributoj";
    }
trPrivateMembers() [1/2]
virtual QCString TranslatorEsperanto::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 646 of file translator_eo.h.
    { return "Privataj Membraj Funkcioj"; }
trPrivateMembers() [2/2]
virtual QCString TranslatorEsperanto::trPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 646 of file translator_eo.h.
    { return "Privataj Membraj Funkcioj"; }
trPrivateSlots() [1/2]
virtual QCString TranslatorEsperanto::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 648 of file translator_eo.h.
    { return "Privataj Ingoj"; }
trPrivateSlots() [2/2]
virtual QCString TranslatorEsperanto::trPrivateSlots () [inline], [virtual]
Implements Translator.
Definition at line 648 of file translator_eo.h.
    { return "Privataj Ingoj"; }
trPrivateTypes() [1/2]
virtual QCString TranslatorEsperanto::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 927 of file translator_eo.h.
    {
      return "Privataj Tipoj";
    }
trPrivateTypes() [2/2]
virtual QCString TranslatorEsperanto::trPrivateTypes () [inline], [virtual]
Implements Translator.
Definition at line 927 of file translator_eo.h.
    {
      return "Privataj Tipoj";
    }
trProperties() [1/2]
virtual QCString TranslatorEsperanto::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1080 of file translator_eo.h.
    {
      return "Atributoj";
    }
trProperties() [2/2]
virtual QCString TranslatorEsperanto::trProperties () [inline], [virtual]
Used as a section header for IDL properties
Implements Translator.
Definition at line 1080 of file translator_eo.h.
    {
      return "Atributoj";
    }
trPropertyDocumentation() [1/2]
virtual QCString TranslatorEsperanto::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1085 of file translator_eo.h.
    {
      return "Atributa Dokumentado";
    }
trPropertyDocumentation() [2/2]
virtual QCString TranslatorEsperanto::trPropertyDocumentation () [inline], [virtual]
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1085 of file translator_eo.h.
    {
      return "Atributa Dokumentado";
    }
trProtectedAttribs() [1/2]
virtual QCString TranslatorEsperanto::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 919 of file translator_eo.h.
    {
      return "Protektitaj Atributoj";
    }
trProtectedAttribs() [2/2]
virtual QCString TranslatorEsperanto::trProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 919 of file translator_eo.h.
    {
      return "Protektitaj Atributoj";
    }
trProtectedMembers() [1/2]
virtual QCString TranslatorEsperanto::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 640 of file translator_eo.h.
    { return "Protektitaj Membraj Funkcioj"; }
trProtectedMembers() [2/2]
virtual QCString TranslatorEsperanto::trProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 640 of file translator_eo.h.
    { return "Protektitaj Membraj Funkcioj"; }
trProtectedSlots() [1/2]
virtual QCString TranslatorEsperanto::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 642 of file translator_eo.h.
    { return "Protektitaj Ingoj"; }
trProtectedSlots() [2/2]
virtual QCString TranslatorEsperanto::trProtectedSlots () [inline], [virtual]
Implements Translator.
Definition at line 642 of file translator_eo.h.
    { return "Protektitaj Ingoj"; }
trProtectedTypes() [1/2]
virtual QCString TranslatorEsperanto::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 915 of file translator_eo.h.
    {
      return "Protektitaj Tipoj";
    }
trProtectedTypes() [2/2]
virtual QCString TranslatorEsperanto::trProtectedTypes () [inline], [virtual]
Implements Translator.
Definition at line 915 of file translator_eo.h.
    {
      return "Protektitaj Tipoj";
    }
trProvidedByCategory() [1/2]
virtual QCString TranslatorEsperanto::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1919 of file translator_eo.h.
    {
      return "Provizita de kategorio @0.";
    }
trProvidedByCategory() [2/2]
virtual QCString TranslatorEsperanto::trProvidedByCategory () [inline], [virtual]
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1919 of file translator_eo.h.
    {
      return "Provizita de kategorio @0.";
    }
trPublicAttribs() [1/2]
virtual QCString TranslatorEsperanto::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 900 of file translator_eo.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datumkampoj";
      }
      else
      {
        return "Publikaj Atributoj";
      }
    }
References Config_getBool.
trPublicAttribs() [2/2]
virtual QCString TranslatorEsperanto::trPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 900 of file translator_eo.h.
    {
      if (Config_getBool(OPTIMIZE_OUTPUT_FOR_C))
      {
        return "Datumkampoj";
      }
      else
      {
        return "Publikaj Atributoj";
      }
    }
References Config_getBool.
trPublicMembers() [1/2]
virtual QCString TranslatorEsperanto::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 632 of file translator_eo.h.
    { return "Publikaj Membraj Funkcioj"; }
trPublicMembers() [2/2]
virtual QCString TranslatorEsperanto::trPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 632 of file translator_eo.h.
    { return "Publikaj Membraj Funkcioj"; }
trPublicSlots() [1/2]
virtual QCString TranslatorEsperanto::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 634 of file translator_eo.h.
    { return "Pubikaj Ingoj"; }
trPublicSlots() [2/2]
virtual QCString TranslatorEsperanto::trPublicSlots () [inline], [virtual]
Implements Translator.
Definition at line 634 of file translator_eo.h.
    { return "Pubikaj Ingoj"; }
trPublicTypes() [1/2]
virtual QCString TranslatorEsperanto::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 896 of file translator_eo.h.
    {
      return "Publikaj Tipoj";
    }
trPublicTypes() [2/2]
virtual QCString TranslatorEsperanto::trPublicTypes () [inline], [virtual]
Implements Translator.
Definition at line 896 of file translator_eo.h.
    {
      return "Publikaj Tipoj";
    }
trReferencedBy() [1/2]
virtual QCString TranslatorEsperanto::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 959 of file translator_eo.h.
    {
      return "Referencita de";
    }
trReferencedBy() [2/2]
virtual QCString TranslatorEsperanto::trReferencedBy () [inline], [virtual]
Implements Translator.
Definition at line 959 of file translator_eo.h.
    {
      return "Referencita de";
    }
trReferenceManual() [1/2]
virtual QCString TranslatorEsperanto::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 424 of file translator_eo.h.
    { return "Referenca Manlibro"; }
trReferenceManual() [2/2]
virtual QCString TranslatorEsperanto::trReferenceManual () [inline], [virtual]
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 424 of file translator_eo.h.
    { return "Referenca Manlibro"; }
trReferences() [1/2]
virtual QCString TranslatorEsperanto::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1287 of file translator_eo.h.
    {
      return "Referencoj";
    }
trReferences() [2/2]
virtual QCString TranslatorEsperanto::trReferences () [inline], [virtual]
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1287 of file translator_eo.h.
    {
      return "Referencoj";
    }
trReimplementedFromList() [1/2]
virtual QCString TranslatorEsperanto::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 697 of file translator_eo.h.
    {
      return "Rerealigita el "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedFromList() [2/2]
virtual QCString TranslatorEsperanto::trReimplementedFromList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 697 of file translator_eo.h.
    {
      return "Rerealigita el "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [1/2]
virtual QCString TranslatorEsperanto::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 705 of file translator_eo.h.
    {
      return "Rerealigita en "+trWriteList(numEntries)+".";
    }
References trWriteList().
trReimplementedInList() [2/2]
virtual QCString TranslatorEsperanto::trReimplementedInList (int numEntries) [inline], [virtual]
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 705 of file translator_eo.h.
    {
      return "Rerealigita en "+trWriteList(numEntries)+".";
    }
References trWriteList().
trRelatedFunctionDocumentation() [1/2]
virtual QCString TranslatorEsperanto::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 587 of file translator_eo.h.
    { return "Dokumentado pri amikoj kaj rilatitaj funkcioj"; }
trRelatedFunctionDocumentation() [2/2]
virtual QCString TranslatorEsperanto::trRelatedFunctionDocumentation () [inline], [virtual]
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 587 of file translator_eo.h.
    { return "Dokumentado pri amikoj kaj rilatitaj funkcioj"; }
trRelatedFunctions() [1/2]
virtual QCString TranslatorEsperanto::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 92 of file translator_eo.h.
    { return "Rilataj Funkcioj"; }
trRelatedFunctions() [2/2]
virtual QCString TranslatorEsperanto::trRelatedFunctions () [inline], [virtual]
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 92 of file translator_eo.h.
    { return "Rilataj Funkcioj"; }
trRelatedPages() [1/2]
virtual QCString TranslatorEsperanto::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 226 of file translator_eo.h.
    { return "Rilataj Paoj"; }
trRelatedPages() [2/2]
virtual QCString TranslatorEsperanto::trRelatedPages () [inline], [virtual]
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 226 of file translator_eo.h.
    { return "Rilataj Paoj"; }
trRelatedPagesDescription() [1/2]
virtual QCString TranslatorEsperanto::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 340 of file translator_eo.h.
    { return "Jen listo de iuj rilataj dokumentadaj paoj:"; }
trRelatedPagesDescription() [2/2]
virtual QCString TranslatorEsperanto::trRelatedPagesDescription () [inline], [virtual]
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 340 of file translator_eo.h.
    { return "Jen listo de iuj rilataj dokumentadaj paoj:"; }
trRelatedSubscript() [1/2]
virtual QCString TranslatorEsperanto::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 96 of file translator_eo.h.
    { return "(Atentu ke tiuj i ne estas membraj funkcioj.)"; }
trRelatedSubscript() [2/2]
virtual QCString TranslatorEsperanto::trRelatedSubscript () [inline], [virtual]
subscript for the related functions.
Implements Translator.
Definition at line 96 of file translator_eo.h.
    { return "(Atentu ke tiuj i ne estas membraj funkcioj.)"; }
trRemarks() [1/2]
virtual QCString TranslatorEsperanto::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 963 of file translator_eo.h.
    {
      return "Rimarkoj";
    }
trRemarks() [2/2]
virtual QCString TranslatorEsperanto::trRemarks () [inline], [virtual]
Implements Translator.
Definition at line 963 of file translator_eo.h.
    {
      return "Rimarkoj";
    }
trReturns() [1/2]
virtual QCString TranslatorEsperanto::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 538 of file translator_eo.h.
    { return "Liveras"; }
trReturns() [2/2]
virtual QCString TranslatorEsperanto::trReturns () [inline], [virtual]
this text is generated when the \return command is used.
Implements Translator.
Definition at line 538 of file translator_eo.h.
    { return "Liveras"; }
trReturnValues() [1/2]
virtual QCString TranslatorEsperanto::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 781 of file translator_eo.h.
    { return "Liveraoj"; }
trReturnValues() [2/2]
virtual QCString TranslatorEsperanto::trReturnValues () [inline], [virtual]
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 781 of file translator_eo.h.
    { return "Liveraoj"; }
trRTFansicp() [1/2]
virtual QCString TranslatorEsperanto::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1171 of file translator_eo.h.
    {
      return "";
    }
trRTFansicp() [2/2]
virtual QCString TranslatorEsperanto::trRTFansicp () [inline], [virtual]
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name Charset Value(hex) Codepage number
------------------------------------------------------
DEFAULT_CHARSET 1 (x01)
SYMBOL_CHARSET 2 (x02)
OEM_CHARSET 255 (xFF)
ANSI_CHARSET 0 (x00) 1252
RUSSIAN_CHARSET 204 (xCC) 1251
EE_CHARSET 238 (xEE) 1250
GREEK_CHARSET 161 (xA1) 1253
TURKISH_CHARSET 162 (xA2) 1254
BALTIC_CHARSET 186 (xBA) 1257
HEBREW_CHARSET 177 (xB1) 1255
ARABIC _CHARSET 178 (xB2) 1256
SHIFTJIS_CHARSET 128 (x80) 932
HANGEUL_CHARSET 129 (x81) 949
GB2313_CHARSET 134 (x86) 936
CHINESEBIG5_CHARSET 136 (x88) 950
Implements Translator.
Definition at line 1171 of file translator_eo.h.
    {
      return "";
    }
trRTFCharSet() [1/2]
virtual QCString TranslatorEsperanto::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1180 of file translator_eo.h.
    {
      return "1";
    }
trRTFCharSet() [2/2]
virtual QCString TranslatorEsperanto::trRTFCharSet () [inline], [virtual]
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1180 of file translator_eo.h.
    {
      return "1";
    }
trRTFGeneralIndex() [1/2]
virtual QCString TranslatorEsperanto::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1186 of file translator_eo.h.
    {
      return "Indekso";
    }
trRTFGeneralIndex() [2/2]
virtual QCString TranslatorEsperanto::trRTFGeneralIndex () [inline], [virtual]
Used as header RTF general index
Implements Translator.
Definition at line 1186 of file translator_eo.h.
    {
      return "Indekso";
    }
trRTFTableOfContents() [1/2]
virtual QCString TranslatorEsperanto::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1319 of file translator_eo.h.
    {
      return "Enhava Tabelo";
    }
trRTFTableOfContents() [2/2]
virtual QCString TranslatorEsperanto::trRTFTableOfContents () [inline], [virtual]
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1319 of file translator_eo.h.
    {
      return "Enhava Tabelo";
    }
trSearch() [1/2]
virtual QCString TranslatorEsperanto::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 234 of file translator_eo.h.
    { return "Seri"; }
trSearch() [2/2]
virtual QCString TranslatorEsperanto::trSearch () [inline], [virtual]
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 234 of file translator_eo.h.
    { return "Seri"; }
trSearching() [1/2]
virtual QCString TranslatorEsperanto::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1758 of file translator_eo.h.
    {
      return "Serante...";
    }
trSearching() [2/2]
virtual QCString TranslatorEsperanto::trSearching () [inline], [virtual]
Message shown while searching
Implements Translator.
Definition at line 1758 of file translator_eo.h.
    {
      return "Serante...";
    }
trSearchMatches() [1/2]
virtual QCString TranslatorEsperanto::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1451 of file translator_eo.h.
    {
      return "Kongruoj:";
    }
trSearchMatches() [2/2]
virtual QCString TranslatorEsperanto::trSearchMatches () [inline], [virtual]
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1451 of file translator_eo.h.
    {
      return "Kongruoj:";
    }
trSearchResults() [1/2]
virtual QCString TranslatorEsperanto::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1432 of file translator_eo.h.
    {
      if (numDocuments==0)
      {
        return "Pardonu, nenio dokumento kongruas vian peton.";
      }
      else if (numDocuments==1)
      {
        return "Trafita <b>unu</b> dokumenton kongruantan vian peton.";
      }
      else
      {
        return "Trafitaj <b>$num</b> dokumentojn kongruantajn vian peton. "
               "Montrios plej bonaj kongruoj unue.";
      }
    }
trSearchResults() [2/2]
virtual QCString TranslatorEsperanto::trSearchResults (int numDocuments) [inline], [virtual]
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1432 of file translator_eo.h.
    {
      if (numDocuments==0)
      {
        return "Pardonu, nenio dokumento kongruas vian peton.";
      }
      else if (numDocuments==1)
      {
        return "Trafita <b>unu</b> dokumenton kongruantan vian peton.";
      }
      else
      {
        return "Trafitaj <b>$num</b> dokumentojn kongruantajn vian peton. "
               "Montrios plej bonaj kongruoj unue.";
      }
    }
trSearchResultsTitle() [1/2]
virtual QCString TranslatorEsperanto::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1420 of file translator_eo.h.
    {
      return "Seraj Rezultoj";
    }
trSearchResultsTitle() [2/2]
virtual QCString TranslatorEsperanto::trSearchResultsTitle () [inline], [virtual]
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1420 of file translator_eo.h.
    {
      return "Seraj Rezultoj";
    }
trSeeAlso() [1/2]
virtual QCString TranslatorEsperanto::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 542 of file translator_eo.h.
    { return "Vido anka"; }
trSeeAlso() [2/2]
virtual QCString TranslatorEsperanto::trSeeAlso () [inline], [virtual]
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 542 of file translator_eo.h.
    { return "Vido anka"; }
trSignals() [1/2]
virtual QCString TranslatorEsperanto::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 636 of file translator_eo.h.
    { return "Signaloj"; }
trSignals() [2/2]
virtual QCString TranslatorEsperanto::trSignals () [inline], [virtual]
Implements Translator.
Definition at line 636 of file translator_eo.h.
    { return "Signaloj"; }
trSince() [1/2]
virtual QCString TranslatorEsperanto::trSince () [inline], [virtual]
Implements Translator.
Definition at line 976 of file translator_eo.h.
    {
      return "De";
    }
trSince() [2/2]
virtual QCString TranslatorEsperanto::trSince () [inline], [virtual]
Implements Translator.
Definition at line 976 of file translator_eo.h.
    {
      return "De";
    }
trSourceFile() [1/2]
virtual QCString TranslatorEsperanto::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1462 of file translator_eo.h.
    {
      return filename + " Fonta Dosiero";
    }
References filename.
trSourceFile() [2/2]
virtual QCString TranslatorEsperanto::trSourceFile (QCString & filename) [inline], [virtual]
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1462 of file translator_eo.h.
    {
      return filename + " Fonta Dosiero";
    }
References filename.
trStaticPackageAttribs() [1/2]
virtual QCString TranslatorEsperanto::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1391 of file translator_eo.h.
    {
      return "Statikaj Pakaaj Atributoj";
    }
trStaticPackageAttribs() [2/2]
virtual QCString TranslatorEsperanto::trStaticPackageAttribs () [inline], [virtual]
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1391 of file translator_eo.h.
    {
      return "Statikaj Pakaaj Atributoj";
    }
trStaticPackageFunctions() [1/2]
virtual QCString TranslatorEsperanto::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1377 of file translator_eo.h.
    {
      return "Statikaj Pakaaj Funkcioj";
    }
trStaticPackageFunctions() [2/2]
virtual QCString TranslatorEsperanto::trStaticPackageFunctions () [inline], [virtual]
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1377 of file translator_eo.h.
    {
      return "Statikaj Pakaaj Funkcioj";
    }
trStaticPrivateAttribs() [1/2]
virtual QCString TranslatorEsperanto::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 935 of file translator_eo.h.
    {
      return "Statikaj Privataj Atributoj";
    }
trStaticPrivateAttribs() [2/2]
virtual QCString TranslatorEsperanto::trStaticPrivateAttribs () [inline], [virtual]
Implements Translator.
Definition at line 935 of file translator_eo.h.
    {
      return "Statikaj Privataj Atributoj";
    }
trStaticPrivateMembers() [1/2]
virtual QCString TranslatorEsperanto::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 650 of file translator_eo.h.
    { return "Statikaj Privataj Membraj Funkcioj"; }
trStaticPrivateMembers() [2/2]
virtual QCString TranslatorEsperanto::trStaticPrivateMembers () [inline], [virtual]
Implements Translator.
Definition at line 650 of file translator_eo.h.
    { return "Statikaj Privataj Membraj Funkcioj"; }
trStaticProtectedAttribs() [1/2]
virtual QCString TranslatorEsperanto::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 923 of file translator_eo.h.
    {
      return "Statikaj Protektitaj Atributoj";
    }
trStaticProtectedAttribs() [2/2]
virtual QCString TranslatorEsperanto::trStaticProtectedAttribs () [inline], [virtual]
Implements Translator.
Definition at line 923 of file translator_eo.h.
    {
      return "Statikaj Protektitaj Atributoj";
    }
trStaticProtectedMembers() [1/2]
virtual QCString TranslatorEsperanto::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 644 of file translator_eo.h.
    { return "Statikaj Protektitaj Membraj Funkcioj"; }
trStaticProtectedMembers() [2/2]
virtual QCString TranslatorEsperanto::trStaticProtectedMembers () [inline], [virtual]
Implements Translator.
Definition at line 644 of file translator_eo.h.
    { return "Statikaj Protektitaj Membraj Funkcioj"; }
trStaticPublicAttribs() [1/2]
virtual QCString TranslatorEsperanto::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 911 of file translator_eo.h.
    {
      return "Statikaj Publikaj Atributoj";
    }
trStaticPublicAttribs() [2/2]
virtual QCString TranslatorEsperanto::trStaticPublicAttribs () [inline], [virtual]
Implements Translator.
Definition at line 911 of file translator_eo.h.
    {
      return "Statikaj Publikaj Atributoj";
    }
trStaticPublicMembers() [1/2]
virtual QCString TranslatorEsperanto::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 638 of file translator_eo.h.
    { return "Statikaj Publikaj Membraj Funkcioj"; }
trStaticPublicMembers() [2/2]
virtual QCString TranslatorEsperanto::trStaticPublicMembers () [inline], [virtual]
Implements Translator.
Definition at line 638 of file translator_eo.h.
    { return "Statikaj Publikaj Membraj Funkcioj"; }
trSubprogram() [1/2]
virtual QCString TranslatorEsperanto::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1722 of file translator_eo.h.
    {
      QCString result((first_capital ? "Subprogramo" : "subprogramo"));
      if (!singular) result+="j";
      return result;
    }
trSubprogram() [2/2]
virtual QCString TranslatorEsperanto::trSubprogram (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1722 of file translator_eo.h.
    {
      QCString result((first_capital ? "Subprogramo" : "subprogramo"));
      if (!singular) result+="j";
      return result;
    }
trSubprogramDocumentation() [1/2]
virtual QCString TranslatorEsperanto::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1597 of file translator_eo.h.
    { return "Funkcia/Subrutina Dokumentado"; }
trSubprogramDocumentation() [2/2]
virtual QCString TranslatorEsperanto::trSubprogramDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1597 of file translator_eo.h.
    { return "Funkcia/Subrutina Dokumentado"; }
trSubprograms() [1/2]
virtual QCString TranslatorEsperanto::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1591 of file translator_eo.h.
    { return "Funkcioj/Subrutinoj"; }
trSubprograms() [2/2]
virtual QCString TranslatorEsperanto::trSubprograms () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1591 of file translator_eo.h.
    { return "Funkcioj/Subrutinoj"; }
trTemplateParameters() [1/2]
virtual QCString TranslatorEsperanto::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1872 of file translator_eo.h.
    { return "Parametroj de ablonoj"; }
trTemplateParameters() [2/2]
virtual QCString TranslatorEsperanto::trTemplateParameters () [inline], [virtual]
Section header for list of template parameters
Implements Translator.
Definition at line 1872 of file translator_eo.h.
    { return "Parametroj de ablonoj"; }
trTest() [1/2]
virtual QCString TranslatorEsperanto::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1065 of file translator_eo.h.
    {
      return "Testo";
    }
trTest() [2/2]
virtual QCString TranslatorEsperanto::trTest () [inline], [virtual]
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1065 of file translator_eo.h.
    {
      return "Testo";
    }
trTestList() [1/2]
virtual QCString TranslatorEsperanto::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1070 of file translator_eo.h.
    {
      return "Testa Listo";
    }
trTestList() [2/2]
virtual QCString TranslatorEsperanto::trTestList () [inline], [virtual]
Used as the header of the test list
Implements Translator.
Definition at line 1070 of file translator_eo.h.
    {
      return "Testa Listo";
    }
trThisIsTheListOfAllMembers() [1/2]
virtual QCString TranslatorEsperanto::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 141 of file translator_eo.h.
    { return "Tiu i estas la kompleta membraro de "; }
trThisIsTheListOfAllMembers() [2/2]
virtual QCString TranslatorEsperanto::trThisIsTheListOfAllMembers () [inline], [virtual]
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 141 of file translator_eo.h.
    { return "Tiu i estas la kompleta membraro de "; }
trTodo() [1/2]
virtual QCString TranslatorEsperanto::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 945 of file translator_eo.h.
    {
      return "Farendao";
    }
trTodo() [2/2]
virtual QCString TranslatorEsperanto::trTodo () [inline], [virtual]
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 945 of file translator_eo.h.
    {
      return "Farendao";
    }
trTodoList() [1/2]
virtual QCString TranslatorEsperanto::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 950 of file translator_eo.h.
    {
      return "Farendaaro";
    }
trTodoList() [2/2]
virtual QCString TranslatorEsperanto::trTodoList () [inline], [virtual]
Used as the header of the todo list
Implements Translator.
Definition at line 950 of file translator_eo.h.
    {
      return "Farendaaro";
    }
trType() [1/2]
virtual QCString TranslatorEsperanto::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1712 of file translator_eo.h.
    {
      QCString result((first_capital ? "Tipo" : "tipo"));
      if (!singular) result+="j";
      return result;
    }
trType() [2/2]
virtual QCString TranslatorEsperanto::trType (bool first_capital, bool singular) [inline], [virtual]
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1712 of file translator_eo.h.
    {
      QCString result((first_capital ? "Tipo" : "tipo"));
      if (!singular) result+="j";
      return result;
    }
trTypeConstraints() [1/2]
virtual QCString TranslatorEsperanto::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1730 of file translator_eo.h.
    {
      return "Tipaj Limigoj";
    }
trTypeConstraints() [2/2]
virtual QCString TranslatorEsperanto::trTypeConstraints () [inline], [virtual]
C# Type Constraint list
Implements Translator.
Definition at line 1730 of file translator_eo.h.
    {
      return "Tipaj Limigoj";
    }
trTypedefDocumentation() [1/2]
virtual QCString TranslatorEsperanto::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 472 of file translator_eo.h.
    { return "Tipdifina Dokumentado"; }
trTypedefDocumentation() [2/2]
virtual QCString TranslatorEsperanto::trTypedefDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 472 of file translator_eo.h.
    { return "Tipdifina Dokumentado"; }
trTypedefs() [1/2]
virtual QCString TranslatorEsperanto::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 436 of file translator_eo.h.
    { return "Tipdifinoj"; }
trTypedefs() [2/2]
virtual QCString TranslatorEsperanto::trTypedefs () [inline], [virtual]
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 436 of file translator_eo.h.
    { return "Tipdifinoj"; }
trTypeDocumentation() [1/2]
virtual QCString TranslatorEsperanto::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1585 of file translator_eo.h.
    { return "Datumtipa Dokumentado"; }
trTypeDocumentation() [2/2]
virtual QCString TranslatorEsperanto::trTypeDocumentation () [inline], [virtual]
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1585 of file translator_eo.h.
    { return "Datumtipa Dokumentado"; }
trVariableDocumentation() [1/2]
virtual QCString TranslatorEsperanto::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 490 of file translator_eo.h.
    { return "Variabla Dokumentado"; }
trVariableDocumentation() [2/2]
virtual QCString TranslatorEsperanto::trVariableDocumentation () [inline], [virtual]
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 490 of file translator_eo.h.
    { return "Variabla Dokumentado"; }
trVariables() [1/2]
virtual QCString TranslatorEsperanto::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 454 of file translator_eo.h.
    { return "Variabloj"; }
trVariables() [2/2]
virtual QCString TranslatorEsperanto::trVariables () [inline], [virtual]
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 454 of file translator_eo.h.
    { return "Variabloj"; }
trVersion() [1/2]
virtual QCString TranslatorEsperanto::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 530 of file translator_eo.h.
    { return "Versio"; }
trVersion() [2/2]
virtual QCString TranslatorEsperanto::trVersion () [inline], [virtual]
this text is generated when the \version command is used.
Implements Translator.
Definition at line 530 of file translator_eo.h.
    { return "Versio"; }
trWarning() [1/2]
virtual QCString TranslatorEsperanto::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 526 of file translator_eo.h.
    { return "Averto"; }
trWarning() [2/2]
virtual QCString TranslatorEsperanto::trWarning () [inline], [virtual]
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 526 of file translator_eo.h.
    { return "Averto"; }
trWriteList() [1/2]
virtual QCString TranslatorEsperanto::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 656 of file translator_eo.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=", kaj ";
        }
      }
      return result;
    }
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
trWriteList() [2/2]
virtual QCString TranslatorEsperanto::trWriteList (int numEntries) [inline], [virtual]
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 656 of file translator_eo.h.
    {
      QCString result;
      int i;
      // the inherits list contain `numEntries' classes
      for (i=0;i<numEntries;i++)
      {
        // use generateMarker to generate placeholders for the class links!
        result+=generateMarker(i); // generate marker for entry i in the list
                                   // (order is left to right)
        if (i!=numEntries-1) // not the last entry, so we need a separator
        {
          if (i<numEntries-2) // not the fore last entry
            result+=", ";
          else // the fore last entry
            result+=", kaj ";
        }
      }
      return result;
    }
References generateMarker().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_eo.h
doxygen/src/translator_eo.h