InheritedMemberInfoContext::Private Class Reference
Public Member Functions
Private (const ClassDef *cd, std::unique_ptr< MemberList > &&ml, const QCString &title)
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private (const ClassDef *cd, std::unique_ptr< MemberList > &&ml, const QCString &title)
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private Member Functions
TemplateVariant getClass () const
TemplateVariant title () const
TemplateVariant members () const
TemplateVariant inheritedFrom () const
TemplateVariant id () const
TemplateVariant createClass () const
TemplateVariant createMemberList () const
TemplateVariant createInheritedFrom () const
TemplateVariant getClass () const
TemplateVariant title () const
TemplateVariant members () const
TemplateVariant inheritedFrom () const
TemplateVariant id () const
TemplateVariant createClass () const
TemplateVariant createMemberList () const
TemplateVariant createInheritedFrom () const
Private Attributes
const ClassDef * m_class
std::unique_ptr< const MemberList > m_memberList
QCString m_title
CachedItem< TemplateVariant, Private, &Private::createClass > m_classCtx
CachedItem< TemplateVariant, Private, &Private::createMemberList > m_memberListCtx
CachedItem< TemplateVariant, Private, &Private::createInheritedFrom > m_inheritedFrom
Static Private Attributes
static const PropertyMap< InheritedMemberInfoContext::Private > s_inst
Detailed Description
Definition at line 7996 of file context.cpp.
Constructor & Destructor Documentation
Private() [1/2]
InheritedMemberInfoContext::Private::Private (const ClassDef * cd, std::unique_ptr< MemberList > && ml, const QCString & title) [inline]
Definition at line 7999 of file context.cpp.
      : m_class(cd), m_memberList(std::move(ml)), m_title(title) {}
Private() [2/2]
InheritedMemberInfoContext::Private::Private (const ClassDef * cd, std::unique_ptr< MemberList > && ml, const QCString & title) [inline]
Definition at line 7999 of file context.cpp.
      : m_class(cd), m_memberList(std::move(ml)), m_title(title) {}
Member Function Documentation
createClass() [1/2]
TemplateVariant InheritedMemberInfoContext::Private::createClass () const [inline], [private]
Definition at line 8019 of file context.cpp.
    {
      return ClassContext::alloc(m_class);
    }
References ClassContext::alloc(), and m_class.
createClass() [2/2]
TemplateVariant InheritedMemberInfoContext::Private::createClass () const [inline], [private]
Definition at line 8019 of file context.cpp.
    {
      return ClassContext::alloc(m_class);
    }
References ClassContext::alloc().
createInheritedFrom() [1/2]
TemplateVariant InheritedMemberInfoContext::Private::createInheritedFrom () const [inline], [private]
Definition at line 8027 of file context.cpp.
    {
      return TemplateImmutableList::alloc({ TemplateVariant(title()), TemplateVariant(getClass()) });
    }
References TemplateImmutableList::alloc(), getClass(), and title().
createInheritedFrom() [2/2]
TemplateVariant InheritedMemberInfoContext::Private::createInheritedFrom () const [inline], [private]
Definition at line 8027 of file context.cpp.
    {
      return TemplateImmutableList::alloc({ TemplateVariant(title()), TemplateVariant(getClass()) });
    }
References TemplateImmutableList::alloc(), and getClass().
createMemberList() [1/2]
TemplateVariant InheritedMemberInfoContext::Private::createMemberList () const [inline], [private]
Definition at line 8023 of file context.cpp.
    {
      return MemberListContext::alloc(m_memberList.get());
    }
References MemberListContext::alloc(), and m_memberList.
createMemberList() [2/2]
TemplateVariant InheritedMemberInfoContext::Private::createMemberList () const [inline], [private]
Definition at line 8023 of file context.cpp.
    {
      return MemberListContext::alloc(m_memberList.get());
    }
References MemberListContext::alloc().
fields() [1/2]
StringVector InheritedMemberInfoContext::Private::fields () const [inline]
Definition at line 8004 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
fields() [2/2]
StringVector InheritedMemberInfoContext::Private::fields () const [inline]
Definition at line 8004 of file context.cpp.
{ return s_inst.fields(); }
get() [1/2]
TemplateVariant InheritedMemberInfoContext::Private::get (const QCString & n) const [inline]
Definition at line 8003 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), n, and s_inst.
get() [2/2]
TemplateVariant InheritedMemberInfoContext::Private::get (const QCString & n) const [inline]
Definition at line 8003 of file context.cpp.
{ return s_inst.get(this,n); }
References n.
getClass() [1/2]
TemplateVariant InheritedMemberInfoContext::Private::getClass () const [inline], [private]
Definition at line 8008 of file context.cpp.
{ return m_classCtx.get(this); }
References m_classCtx.
Referenced by createInheritedFrom().
getClass() [2/2]
TemplateVariant InheritedMemberInfoContext::Private::getClass () const [inline], [private]
Definition at line 8008 of file context.cpp.
{ return m_classCtx.get(this); }
id() [1/2]
TemplateVariant InheritedMemberInfoContext::Private::id () const [inline], [private]
Definition at line 8012 of file context.cpp.
    {
      return substitute(MemberList::listTypeAsString(m_memberList->listType()),"-","_")+"_"+
                        stripPath(m_class->getOutputFileBase());
    }
References ClassDef::getOutputFileBase(), MemberList::listTypeAsString(), m_class, m_memberList, stripPath(), and substitute().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), and doxmlparser.compound.docXRefSectType::set_id().
id() [2/2]
TemplateVariant InheritedMemberInfoContext::Private::id () const [inline], [private]
Definition at line 8012 of file context.cpp.
    {
      return substitute(MemberList::listTypeAsString(m_memberList->listType()),"-","_")+"_"+
                        stripPath(m_class->getOutputFileBase());
    }
References MemberList::listTypeAsString(), stripPath(), and substitute().
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.enumvalueType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docCaptionType::__init__(), doxmlparser.compound.docTocItemType::__init__(), doxmlparser.compound.docAnchorType::__init__(), doxmlparser.compound.docFormulaType::__init__(), doxmlparser.compound.docXRefSectType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.enumvalueType::buildAttributes(), doxmlparser.compound.nodeType::buildAttributes(), doxmlparser.compound.docSect1Type::buildAttributes(), doxmlparser.compound.docSect2Type::buildAttributes(), doxmlparser.compound.docSect3Type::buildAttributes(), doxmlparser.compound.docSect4Type::buildAttributes(), doxmlparser.compound.docAnchorType::buildAttributes(), doxmlparser.compound.docFormulaType::buildAttributes(), doxmlparser.compound.docCaptionType::buildAttributes(), doxmlparser.compound.docTocItemType::buildAttributes(), doxmlparser.compound.docXRefSectType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.compound.docAnchorType::exportAttributes(), doxmlparser.compound.docCaptionType::exportAttributes(), doxmlparser.compound.docFormulaType::exportAttributes(), doxmlparser.compound.docSect1Type::exportAttributes(), doxmlparser.compound.docSect2Type::exportAttributes(), doxmlparser.compound.docSect3Type::exportAttributes(), doxmlparser.compound.docSect4Type::exportAttributes(), doxmlparser.compound.docTocItemType::exportAttributes(), doxmlparser.compound.docXRefSectType::exportAttributes(), doxmlparser.compound.enumvalueType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.compound.nodeType::exportAttributes(), doxmlparser.compound.compounddefType::get_id(), doxmlparser.compound.memberdefType::get_id(), doxmlparser.compound.enumvalueType::get_id(), doxmlparser.compound.nodeType::get_id(), doxmlparser.compound.docSect1Type::get_id(), doxmlparser.compound.docSect2Type::get_id(), doxmlparser.compound.docSect3Type::get_id(), doxmlparser.compound.docSect4Type::get_id(), doxmlparser.compound.docAnchorType::get_id(), doxmlparser.compound.docFormulaType::get_id(), doxmlparser.compound.docCaptionType::get_id(), doxmlparser.compound.docTocItemType::get_id(), doxmlparser.compound.docXRefSectType::get_id(), doxmlparser.compound.compounddefType::set_id(), doxmlparser.compound.memberdefType::set_id(), doxmlparser.compound.enumvalueType::set_id(), doxmlparser.compound.nodeType::set_id(), doxmlparser.compound.docSect1Type::set_id(), doxmlparser.compound.docSect2Type::set_id(), doxmlparser.compound.docSect3Type::set_id(), doxmlparser.compound.docSect4Type::set_id(), doxmlparser.compound.docAnchorType::set_id(), doxmlparser.compound.docFormulaType::set_id(), doxmlparser.compound.docCaptionType::set_id(), doxmlparser.compound.docTocItemType::set_id(), and doxmlparser.compound.docXRefSectType::set_id().
inheritedFrom() [1/2]
TemplateVariant InheritedMemberInfoContext::Private::inheritedFrom () const [inline], [private]
Definition at line 8011 of file context.cpp.
{ return m_inheritedFrom.get(this); }
References m_inheritedFrom.
inheritedFrom() [2/2]
TemplateVariant InheritedMemberInfoContext::Private::inheritedFrom () const [inline], [private]
Definition at line 8011 of file context.cpp.
{ return m_inheritedFrom.get(this); }
members() [1/2]
TemplateVariant InheritedMemberInfoContext::Private::members () const [inline], [private]
Definition at line 8010 of file context.cpp.
{ return m_memberListCtx.get(this); }
References m_memberListCtx.
members() [2/2]
TemplateVariant InheritedMemberInfoContext::Private::members () const [inline], [private]
Definition at line 8010 of file context.cpp.
{ return m_memberListCtx.get(this); }
title() [1/2]
TemplateVariant InheritedMemberInfoContext::Private::title () const [inline], [private]
Definition at line 8009 of file context.cpp.
{ return m_title; }
References m_title.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), createInheritedFrom(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
title() [2/2]
TemplateVariant InheritedMemberInfoContext::Private::title () const [inline], [private]
Definition at line 8009 of file context.cpp.
{ return m_title; }
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
Member Data Documentation
m_class
const ClassDef * InheritedMemberInfoContext::Private::m_class [private]
Definition at line 8032 of file context.cpp.
Referenced by createClass(), and id().
m_classCtx
CachedItem< TemplateVariant, Private, &Private::createClass > InheritedMemberInfoContext::Private::m_classCtx [private]
Definition at line 8035 of file context.cpp.
Referenced by getClass().
m_inheritedFrom
CachedItem< TemplateVariant, Private, &Private::createInheritedFrom > InheritedMemberInfoContext::Private::m_inheritedFrom [private]
Definition at line 8037 of file context.cpp.
Referenced by inheritedFrom().
m_memberList
std::unique_ptr< const MemberList > InheritedMemberInfoContext::Private::m_memberList [private]
Definition at line 8033 of file context.cpp.
Referenced by createMemberList(), and id().
m_memberListCtx
CachedItem< TemplateVariant, Private, &Private::createMemberList > InheritedMemberInfoContext::Private::m_memberListCtx [private]
Definition at line 8036 of file context.cpp.
Referenced by members().
m_title
QCString InheritedMemberInfoContext::Private::m_title [private]
Definition at line 8034 of file context.cpp.
Referenced by title().
s_inst
const PropertyMap< InheritedMemberInfoContext::Private > InheritedMemberInfoContext::Private::s_inst [static], [private]
Initial value:
{
  { "class", &Private::getClass },
  { "title", &Private::title },
  { "members", &Private::members },
  { "id", &Private::id },
  { "inheritedFrom", &Private::inheritedFrom }
}
Definition at line 8038 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp