ResourceMgr Class Reference
Singleton for managing resources compiled into an executable.
#include <resourcemgr.h>
Classes
class Private
Public Member Functions
void registerResources (std::initializer_list< Resource > resources)
bool writeCategory (const QCString &categoryName, const QCString &targetDir) const
bool copyResource (const QCString &name, const QCString &targetDir) const
bool copyResourceAs (const QCString &name, const QCString &targetDir, const QCString &targetName, bool append=false) const
QCString getAsString (const QCString &name) const
void registerResources (std::initializer_list< Resource > resources)
bool writeCategory (const QCString &categoryName, const QCString &targetDir) const
bool copyResource (const QCString &name, const QCString &targetDir) const
bool copyResourceAs (const QCString &name, const QCString &targetDir, const QCString &targetName, bool append=false) const
QCString getAsString (const QCString &name) const
Static Public Member Functions
static ResourceMgr & instance ()
static ResourceMgr & instance ()
Private Member Functions
const Resource * get (const QCString &name) const
ResourceMgr ()
~ResourceMgr ()
const Resource * get (const QCString &name) const
ResourceMgr ()
~ResourceMgr ()
Private Attributes
std::unique_ptr< Private > p
Detailed Description
Singleton for managing resources compiled into an executable.
Definition at line 35 of file resourcemgr.h.
Constructor & Destructor Documentation
ResourceMgr() [1/2]
ResourceMgr::ResourceMgr () [private]
Definition at line 38 of file resourcemgr.cpp.
                         : p(std::make_unique<Private>())
{
}
 ResourceMgr() [1/2]
ResourceMgr::~ResourceMgr () [private]
Definition at line 42 of file resourcemgr.cpp.
{
}
ResourceMgr() [2/2]
ResourceMgr::ResourceMgr () [private]
 ResourceMgr() [2/2]
ResourceMgr::~ResourceMgr () [private]
Member Function Documentation
copyResource() [1/2]
bool ResourceMgr::copyResource (const QCString & name, const QCString & targetDir) const
Copies a registered resource to a given target directory
Definition at line 180 of file resourcemgr.cpp.
{
  return copyResourceAs(name,targetDir,name);
}
References copyResourceAs(), and setup::name.
Referenced by generateJSNavTree(), CitationManager::generatePage(), FTVHelp::generateTreeViewImages(), generateXML(), HtmlGenerator::init(), TemplateNodeResource::render(), writeJavaScriptSearchIndex(), HtmlGenerator::writeSearchData(), HtmlGenerator::writeSearchPage(), and HtmlGenerator::writeTabData().
copyResource() [2/2]
bool ResourceMgr::copyResource (const QCString & name, const QCString & targetDir) const
Copies a registered resource to a given target directory
copyResourceAs() [1/2]
bool ResourceMgr::copyResourceAs (const QCString & name, const QCString & targetDir, const QCString & targetName, bool append = false) const
Copies a registered resource to a given target directory under a given target name
Definition at line 79 of file resourcemgr.cpp.
{
  std::string pathName = targetDir.str()+"/"+targetName.str();
  std::ios_base::openmode mode = std::ofstream::out | std::ofstream::binary;
  if (append) mode |= std::ofstream::app;
  const Resource *res = get(name);
  if (res)
  {
    switch (res->type)
    {
      case Resource::Verbatim:
        {
          std::ofstream f(pathName,mode);
          bool ok=false;
          if (f.is_open())
          {
            f.write(reinterpret_cast<const char *>(res->data),res->size);
            ok = !f.fail();
          }
          if (ok)
          {
            return TRUE;
          }
        }
        break;
      case Resource::Luminance:
        {
          QCString n = name;
          n = n.left(n.length()-4)+".png"; // replace .lum by .png
          const uchar *data = res->data;
          ushort width = (data[0]<<8)+data[1];
          ushort height = (data[2]<<8)+data[3];
          ColoredImgDataItem images[2];
          images[0].name = n.data();
          images[0].width = width;
          images[0].height = height;
          images[0].content = &data[4];
          images[0].alpha = 0;
          images[1].name = 0; // terminator
          writeColoredImgData(targetDir,images);
          return TRUE;
        }
        break;
      case Resource::LumAlpha:
        {
          QCString n = name;
          n = n.left(n.length()-5)+".png"; // replace .luma by .png
          const uchar *data = res->data;
          ushort width = (data[0]<<8)+data[1];
          ushort height = (data[2]<<8)+data[3];
          ColoredImgDataItem images[2];
          images[0].name = n.data();
          images[0].width = width;
          images[0].height = height;
          images[0].content = &data[4];
          images[0].alpha = &data[4+width*height];
          images[1].name = 0; // terminator
          writeColoredImgData(targetDir,images);
          return TRUE;
        }
        break;
      case Resource::CSS:
        {
          std::ofstream t(pathName,mode);
          if (t.is_open())
          {
            QCString buf(res->size+1);
            memcpy(buf.rawData(),res->data,res->size);
            buf = replaceColorMarkers(buf);
            if (name=="navtree.css")
            {
              t << substitute(buf,"$width",QCString().setNum(Config_getInt(TREEVIEW_WIDTH))+"px");
            }
            else
            {
              t << substitute(buf,"$doxygenversion",getDoxygenVersion());
            }
            return TRUE;
          }
        }
        break;
      case Resource::SVG:
        {
          std::ofstream t(pathName,mode);
          if (t.is_open())
          {
            QCString buf(res->size+1);
            memcpy(buf.rawData(),res->data,res->size);
            t << replaceColorMarkers(buf);
            return TRUE;
          }
        }
    }
  }
  else
  {
    err("requested resource '%s' not compiled in!\n",qPrint(name));
  }
  return FALSE;
}
References ColoredImgDataItem::alpha, Config_getInt, ColoredImgDataItem::content, Resource::CSS, data, Resource::data, err(), f, FALSE, get(), getDoxygenVersion(), ColoredImgDataItem::height, Resource::LumAlpha, Resource::Luminance, mode, n, setup::name, ColoredImgDataItem::name, out, qPrint(), QCString::rawData(), replaceColorMarkers(), Resource::size, QCString::str(), string, substitute(), Resource::SVG, TRUE, Resource::type, Resource::Verbatim, ColoredImgDataItem::width, and writeColoredImgData().
Referenced by copyResource(), and TemplateNodeResource::render().
copyResourceAs() [2/2]
bool ResourceMgr::copyResourceAs (const QCString & name, const QCString & targetDir, const QCString & targetName, bool append = false) const
Copies a registered resource to a given target directory under a given target name
get() [1/2]
const Resource * ResourceMgr::get (const QCString & name) const [private]
Returns a pointer to the resource object with the given name.
Definition at line 185 of file resourcemgr.cpp.
{
  auto it = p->resources.find(name.str());
  if (it!=p->resources.end()) return &it->second;
  return 0;
}
References setup::name, and p.
Referenced by copyResourceAs(), and getAsString().
get() [2/2]
const Resource * ResourceMgr::get (const QCString & name) const [private]
Returns a pointer to the resource object with the given name.
getAsString() [1/2]
QCString ResourceMgr::getAsString (const QCString & name) const
Gets the resource data as a C string
Definition at line 192 of file resourcemgr.cpp.
{
  const Resource *res = get(name);
  if (res)
  {
    QCString result(res->size+1);
    memcpy(result.rawData(),res->data,res->size);
    return result;
  }
  else
  {
    return QCString();
  }
}
References Resource::data, get(), setup::name, QCString::rawData(), and Resource::size.
Referenced by fillColorStyleMaps(), generateXML(), HtmlGenerator::getNavTreeCss(), HtmlGenerator::init(), LatexGenerator::init(), LayoutDocManager::init(), TemplateEngine::Private::loadByName(), writeDefaultLayoutFile(), writeDefaultStyleSheet(), HtmlGenerator::writeExternalSearchPage(), HtmlGenerator::writeFooterFile(), LatexGenerator::writeFooterFile(), LatexGenerator::writeHeaderFile(), HtmlGenerator::writeHeaderFile(), HtmlGenerator::writeSearchData(), HtmlGenerator::writeSearchPage(), and LatexGenerator::writeStyleInfo().
getAsString() [2/2]
QCString ResourceMgr::getAsString (const QCString & name) const
Gets the resource data as a C string
instance() [1/2]
ResourceMgr & ResourceMgr::instance () [static]
Returns the one and only instance of this class
Definition at line 32 of file resourcemgr.cpp.
{
  static ResourceMgr theInstance;
  return theInstance;
}
Referenced by fillColorStyleMaps(), generateJSNavTree(), CitationManager::generatePage(), generateTemplateFiles(), FTVHelp::generateTreeViewImages(), FTVHelp::generateTreeViewScripts(), generateXML(), HtmlGenerator::getNavTreeCss(), HtmlGenerator::init(), LatexGenerator::init(), LayoutDocManager::init(), TemplateEngine::Private::loadByName(), TemplateNodeResource::render(), writeDefaultLayoutFile(), writeDefaultStyleSheet(), HtmlGenerator::writeExternalSearchPage(), HtmlGenerator::writeFooterFile(), LatexGenerator::writeFooterFile(), LatexGenerator::writeHeaderFile(), HtmlGenerator::writeHeaderFile(), writeJavaScriptSearchIndex(), HtmlGenerator::writeSearchData(), HtmlGenerator::writeSearchPage(), LatexGenerator::writeStyleInfo(), and HtmlGenerator::writeTabData().
instance() [2/2]
static ResourceMgr & ResourceMgr::instance () [static]
Returns the one and only instance of this class
registerResources() [1/2]
void ResourceMgr::registerResources (std::initializer_list< Resource > resources)
Registers an array of resources
Definition at line 46 of file resourcemgr.cpp.
{
  for (auto &res : resources)
  {
    p->resources.insert({res.name,res});
  }
}
References p.
registerResources() [2/2]
void ResourceMgr::registerResources (std::initializer_list< Resource > resources)
Registers an array of resources
writeCategory() [1/2]
bool ResourceMgr::writeCategory (const QCString & categoryName, const QCString & targetDir) const
Writes all resource belonging to a given category to a given target directory
Definition at line 54 of file resourcemgr.cpp.
{
  for (auto &kv : p->resources)
  {
    Resource &res = kv.second;
    if (res.category==categoryName)
    {
      std::string pathName = targetDir.str()+"/"+res.name;
      std::ofstream f(pathName,std::ofstream::out | std::ofstream::binary);
      bool ok=false;
      if (f.is_open())
      {
        f.write(reinterpret_cast<const char *>(res.data),res.size);
        ok = !f.fail();
      }
      if (!ok)
      {
        err("Failed to write resource '%s' to directory '%s'\n",res.name,qPrint(targetDir));
        return FALSE;
      }
    }
  }
  return TRUE;
}
References Resource::category, Resource::data, err(), f, FALSE, Resource::name, out, p, qPrint(), Resource::size, QCString::str(), string, and TRUE.
Referenced by generateTemplateFiles().
writeCategory() [2/2]
bool ResourceMgr::writeCategory (const QCString & categoryName, const QCString & targetDir) const
Writes all resource belonging to a given category to a given target directory
Member Data Documentation
p
std::unique_ptr< Private > ResourceMgr::p [private]
Definition at line 63 of file resourcemgr.h.
Referenced by get(), registerResources(), and writeCategory().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/resourcemgr.h
doxygen/src/resourcemgr.h
doxygen/build/doxygen/src/resourcemgr.cpp
doxygen/src/resourcemgr.cpp