TranslatorAdapter_1_8_0 Class Reference
#include <translator_adapter.h>
Public Member Functions
virtual QCString updateNeededMessage ()
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString updateNeededMessage ()
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const QCString &name)
virtual QCString trInheritedFrom (const QCString &members, const QCString &what)
virtual QCString trAdditionalInheritedMembers ()
Additional Inherited Members
Detailed Description
Adapter class for languages that only contain translations up to version 1.8.0.
Definition at line 282 of file translator_adapter.h.
Member Function Documentation
trAdditionalInheritedMembers() [1/2]
virtual QCString TranslatorAdapter_1_8_0::trAdditionalInheritedMembers () [inline], [virtual]
Implements Translator.
Definition at line 306 of file translator_adapter.h.
    { return english.trAdditionalInheritedMembers(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trAdditionalInheritedMembers().
trAdditionalInheritedMembers() [2/2]
virtual QCString TranslatorAdapter_1_8_0::trAdditionalInheritedMembers () [inline], [virtual]
Implements Translator.
Definition at line 306 of file translator_adapter.h.
    { return english.trAdditionalInheritedMembers(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trAdditionalInheritedMembers().
trAndMore() [1/2]
virtual QCString TranslatorAdapter_1_8_0::trAndMore (const QCString & number) [inline], [virtual]
Implements Translator.
Definition at line 294 of file translator_adapter.h.
    { return english.trAndMore(number); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trAndMore().
trAndMore() [2/2]
virtual QCString TranslatorAdapter_1_8_0::trAndMore (const QCString & number) [inline], [virtual]
Implements Translator.
Definition at line 294 of file translator_adapter.h.
    { return english.trAndMore(number); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trAndMore().
trDetailLevel() [1/2]
virtual QCString TranslatorAdapter_1_8_0::trDetailLevel () [inline], [virtual]
Implements Translator.
Definition at line 288 of file translator_adapter.h.
    { return english.trDetailLevel(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trDetailLevel().
trDetailLevel() [2/2]
virtual QCString TranslatorAdapter_1_8_0::trDetailLevel () [inline], [virtual]
Implements Translator.
Definition at line 288 of file translator_adapter.h.
    { return english.trDetailLevel(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trDetailLevel().
trEnumGeneratedFromFiles() [1/2]
virtual QCString TranslatorAdapter_1_8_0::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Implements Translator.
Definition at line 297 of file translator_adapter.h.
    { return english.trEnumGeneratedFromFiles(single); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trEnumGeneratedFromFiles().
trEnumGeneratedFromFiles() [2/2]
virtual QCString TranslatorAdapter_1_8_0::trEnumGeneratedFromFiles (bool single) [inline], [virtual]
Implements Translator.
Definition at line 297 of file translator_adapter.h.
    { return english.trEnumGeneratedFromFiles(single); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trEnumGeneratedFromFiles().
trEnumReference() [1/2]
virtual QCString TranslatorAdapter_1_8_0::trEnumReference (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 300 of file translator_adapter.h.
    { return english.trEnumReference(name); }
References TranslatorAdapterBase::english, setup::name, and TranslatorEnglish::trEnumReference().
trEnumReference() [2/2]
virtual QCString TranslatorAdapter_1_8_0::trEnumReference (const QCString & name) [inline], [virtual]
Implements Translator.
Definition at line 300 of file translator_adapter.h.
    { return english.trEnumReference(name); }
References TranslatorAdapterBase::english, setup::name, and TranslatorEnglish::trEnumReference().
trInheritedFrom() [1/2]
virtual QCString TranslatorAdapter_1_8_0::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Implements Translator.
Definition at line 303 of file translator_adapter.h.
    { return english.trInheritedFrom(members,what); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trInheritedFrom().
trInheritedFrom() [2/2]
virtual QCString TranslatorAdapter_1_8_0::trInheritedFrom (const QCString & members, const QCString & what) [inline], [virtual]
Implements Translator.
Definition at line 303 of file translator_adapter.h.
    { return english.trInheritedFrom(members,what); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trInheritedFrom().
trTemplateParameters() [1/2]
virtual QCString TranslatorAdapter_1_8_0::trTemplateParameters () [inline], [virtual]
Implements Translator.
Definition at line 291 of file translator_adapter.h.
    { return english.trTemplateParameters(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trTemplateParameters().
trTemplateParameters() [2/2]
virtual QCString TranslatorAdapter_1_8_0::trTemplateParameters () [inline], [virtual]
Implements Translator.
Definition at line 291 of file translator_adapter.h.
    { return english.trTemplateParameters(); }
References TranslatorAdapterBase::english, and TranslatorEnglish::trTemplateParameters().
updateNeededMessage() [1/2]
virtual QCString TranslatorAdapter_1_8_0::updateNeededMessage () [inline], [virtual]
This method is used to generate a warning message to signal the user that the translation of his/her language of choice needs updating. It must be implemented by the translator adapter class (pure virtual).
See also
createUpdateNeededMessage()
Reimplemented from TranslatorAdapter_1_8_2.
Reimplemented in TranslatorAdapter_1_7_5, TranslatorAdapter_1_6_0, TranslatorAdapter_1_4_6, TranslatorAdapter_1_7_5, TranslatorAdapter_1_6_0, and TranslatorAdapter_1_4_6.
Definition at line 285 of file translator_adapter.h.
    { return createUpdateNeededMessage(idLanguage(),"release 1.8.0"); }
References TranslatorAdapterBase::createUpdateNeededMessage(), and Translator::idLanguage().
updateNeededMessage() [2/2]
virtual QCString TranslatorAdapter_1_8_0::updateNeededMessage () [inline], [virtual]
This method is used to generate a warning message to signal the user that the translation of his/her language of choice needs updating. It must be implemented by the translator adapter class (pure virtual).
See also
createUpdateNeededMessage()
Reimplemented from TranslatorAdapter_1_8_2.
Reimplemented in TranslatorAdapter_1_7_5, TranslatorAdapter_1_6_0, TranslatorAdapter_1_4_6, TranslatorAdapter_1_7_5, TranslatorAdapter_1_6_0, and TranslatorAdapter_1_4_6.
Definition at line 285 of file translator_adapter.h.
    { return createUpdateNeededMessage(idLanguage(),"release 1.8.0"); }
References TranslatorAdapterBase::createUpdateNeededMessage(), and Translator::idLanguage().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/translator_adapter.h
doxygen/src/translator_adapter.h