DoxygenContext::Private Class Reference
Public Member Functions
TemplateVariant get (const QCString &n) const
StringVector fields () const
TemplateVariant get (const QCString &n) const
StringVector fields () const
Private Member Functions
TemplateVariant version () const
TemplateVariant date () const
TemplateVariant mathJaxCodeFile () const
TemplateVariant mathJaxMacros () const
QCString createMathJaxCodeFile () const
QCString createMathJaxMacros () const
TemplateVariant version () const
TemplateVariant date () const
TemplateVariant mathJaxCodeFile () const
TemplateVariant mathJaxMacros () const
QCString createMathJaxCodeFile () const
QCString createMathJaxMacros () const
Private Attributes
CachedItem< QCString, Private, &Private::createMathJaxCodeFile > m_mathJaxCodeFile
CachedItem< QCString, Private, &Private::createMathJaxMacros > m_mathJaxMacros
Static Private Attributes
static const PropertyMap< DoxygenContext::Private > s_inst
Detailed Description
Definition at line 334 of file context.cpp.
Member Function Documentation
createMathJaxCodeFile() [1/2]
QCString DoxygenContext::Private::createMathJaxCodeFile () const [inline], [private]
Definition at line 349 of file context.cpp.
{ return fileToString(Config_getString(MATHJAX_CODEFILE)); }
References Config_getString, and fileToString().
createMathJaxCodeFile() [2/2]
QCString DoxygenContext::Private::createMathJaxCodeFile () const [inline], [private]
Definition at line 349 of file context.cpp.
{ return fileToString(Config_getString(MATHJAX_CODEFILE)); }
References Config_getString, and fileToString().
createMathJaxMacros() [1/2]
QCString DoxygenContext::Private::createMathJaxMacros () const [inline], [private]
Definition at line 350 of file context.cpp.
{ return HtmlGenerator::getMathJaxMacros(); }
References HtmlGenerator::getMathJaxMacros().
createMathJaxMacros() [2/2]
QCString DoxygenContext::Private::createMathJaxMacros () const [inline], [private]
Definition at line 350 of file context.cpp.
{ return HtmlGenerator::getMathJaxMacros(); }
References HtmlGenerator::getMathJaxMacros().
date() [1/2]
TemplateVariant DoxygenContext::Private::date () const [inline], [private]
Definition at line 344 of file context.cpp.
{ return dateToString(TRUE); }
References dateToString(), and TRUE.
date() [2/2]
TemplateVariant DoxygenContext::Private::date () const [inline], [private]
Definition at line 344 of file context.cpp.
{ return dateToString(TRUE); }
References dateToString(), and TRUE.
fields() [1/2]
StringVector DoxygenContext::Private::fields () const [inline]
Definition at line 339 of file context.cpp.
{ return s_inst.fields(); }
References PropertyMap< T >::fields(), and s_inst.
fields() [2/2]
StringVector DoxygenContext::Private::fields () const [inline]
Definition at line 339 of file context.cpp.
{ return s_inst.fields(); }
get() [1/2]
TemplateVariant DoxygenContext::Private::get (const QCString & n) const [inline]
Definition at line 338 of file context.cpp.
{ return s_inst.get(this,n); }
References PropertyMap< T >::get(), n, and s_inst.
get() [2/2]
TemplateVariant DoxygenContext::Private::get (const QCString & n) const [inline]
Definition at line 338 of file context.cpp.
{ return s_inst.get(this,n); }
References n.
mathJaxCodeFile() [1/2]
TemplateVariant DoxygenContext::Private::mathJaxCodeFile () const [inline], [private]
Definition at line 345 of file context.cpp.
{ return m_mathJaxCodeFile.get(this); }
References m_mathJaxCodeFile.
mathJaxCodeFile() [2/2]
TemplateVariant DoxygenContext::Private::mathJaxCodeFile () const [inline], [private]
Definition at line 345 of file context.cpp.
{ return m_mathJaxCodeFile.get(this); }
mathJaxMacros() [1/2]
TemplateVariant DoxygenContext::Private::mathJaxMacros () const [inline], [private]
Definition at line 346 of file context.cpp.
{ return m_mathJaxMacros.get(this); }
References m_mathJaxMacros.
mathJaxMacros() [2/2]
TemplateVariant DoxygenContext::Private::mathJaxMacros () const [inline], [private]
Definition at line 346 of file context.cpp.
{ return m_mathJaxMacros.get(this); }
version() [1/2]
TemplateVariant DoxygenContext::Private::version () const [inline], [private]
Definition at line 343 of file context.cpp.
{ return getDoxygenVersion(); }
References getDoxygenVersion().
Referenced by doxmlparser.index.DoxygenType::__init__(), doxmlparser.compound.DoxygenType::__init__(), doxmlparser.compound.DoxygenType::buildAttributes(), doxmlparser.index.DoxygenType::buildAttributes(), doxmlparser.compound.DoxygenType::exportAttributes(), doxmlparser.index.DoxygenType::exportAttributes(), doxmlparser.compound.DoxygenType::get_version(), doxmlparser.index.DoxygenType::get_version(), doxmlparser.compound.DoxygenType::set_version(), and doxmlparser.index.DoxygenType::set_version().
version() [2/2]
TemplateVariant DoxygenContext::Private::version () const [inline], [private]
Definition at line 343 of file context.cpp.
{ return getDoxygenVersion(); }
References getDoxygenVersion().
Referenced by doxmlparser.index.DoxygenType::__init__(), doxmlparser.compound.DoxygenType::__init__(), doxmlparser.compound.DoxygenType::buildAttributes(), doxmlparser.index.DoxygenType::buildAttributes(), doxmlparser.compound.DoxygenType::exportAttributes(), doxmlparser.index.DoxygenType::exportAttributes(), doxmlparser.compound.DoxygenType::get_version(), doxmlparser.index.DoxygenType::get_version(), doxmlparser.compound.DoxygenType::set_version(), and doxmlparser.index.DoxygenType::set_version().
Member Data Documentation
m_mathJaxCodeFile
CachedItem< QCString, Private, &Private::createMathJaxCodeFile > DoxygenContext::Private::m_mathJaxCodeFile [private]
Definition at line 351 of file context.cpp.
Referenced by mathJaxCodeFile().
m_mathJaxMacros
CachedItem< QCString, Private, &Private::createMathJaxMacros > DoxygenContext::Private::m_mathJaxMacros [private]
Definition at line 352 of file context.cpp.
Referenced by mathJaxMacros().
s_inst
const PropertyMap< DoxygenContext::Private > DoxygenContext::Private::s_inst [static], [private]
Initial value:
{
{
  
  { "version", &Private::version },
  
  { "date", &Private::date },
  
  { "mathJaxCodeFile", &Private::mathJaxCodeFile },
  
  { "mathJaxMacros", &Private::mathJaxMacros }
} }
Definition at line 353 of file context.cpp.
Referenced by fields(), and get().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/context.cpp
doxygen/src/context.cpp