AccessStack Class Reference
Classes
struct AccessElem
Public Member Functions
void push (const Definition *scope, const FileDef *fileScope, const Definition *item)
void push (const Definition *scope, const FileDef *fileScope, const Definition *item, const QCString &expScope)
void pop ()
bool find (const Definition *scope, const FileDef *fileScope, const Definition *item)
bool find (const Definition *scope, const FileDef *fileScope, const Definition *item, const QCString &expScope)
void clear ()
void push (const Definition *scope, const FileDef *fileScope, const Definition *item)
void push (const Definition *scope, const FileDef *fileScope, const Definition *item, const QCString &expScope)
void pop ()
bool find (const Definition *scope, const FileDef *fileScope, const Definition *item)
bool find (const Definition *scope, const FileDef *fileScope, const Definition *item, const QCString &expScope)
void clear ()
Private Attributes
std::vector< AccessElem > m_elements
Detailed Description
Helper class representing the stack of items considered while resolving the scope.
Definition at line 35 of file symbolresolver.cpp.
Member Function Documentation
clear() [1/2]
void AccessStack::clear () [inline]
Definition at line 72 of file symbolresolver.cpp.
    {
      m_elements.clear();
    }
References m_elements.
clear() [2/2]
void AccessStack::clear () [inline]
Definition at line 72 of file symbolresolver.cpp.
    {
      m_elements.clear();
    }
References m_elements.
find() [1/4]
bool AccessStack::find (const Definition * scope, const FileDef * fileScope, const Definition * item) [inline]
Definition at line 60 of file symbolresolver.cpp.
    {
      auto it = std::find_if(m_elements.begin(),m_elements.end(),
                             [&](const AccessElem &e) { return e.scope==scope && e.fileScope==fileScope && e.item==item; });
      return it!=m_elements.end();
    }
References e, and m_elements.
Referenced by SymbolResolver::Private::isAccessibleFrom(), and SymbolResolver::Private::isAccessibleFromWithExpScope().
find() [2/4]
bool AccessStack::find (const Definition * scope, const FileDef * fileScope, const Definition * item) [inline]
Definition at line 60 of file symbolresolver.cpp.
    {
      auto it = std::find_if(m_elements.begin(),m_elements.end(),
                             [&](const AccessElem &e) { return e.scope==scope && e.fileScope==fileScope && e.item==item; });
      return it!=m_elements.end();
    }
References e, and m_elements.
find() [3/4]
bool AccessStack::find (const Definition * scope, const FileDef * fileScope, const Definition * item, const QCString & expScope) [inline]
Definition at line 66 of file symbolresolver.cpp.
    {
      auto it = std::find_if(m_elements.begin(),m_elements.end(),
                             [&](const AccessElem &e) { return e.scope==scope && e.fileScope==fileScope && e.item==item && e.expScope==expScope; });
      return it!=m_elements.end();
    }
References e, and m_elements.
find() [4/4]
bool AccessStack::find (const Definition * scope, const FileDef * fileScope, const Definition * item, const QCString & expScope) [inline]
Definition at line 66 of file symbolresolver.cpp.
    {
      auto it = std::find_if(m_elements.begin(),m_elements.end(),
                             [&](const AccessElem &e) { return e.scope==scope && e.fileScope==fileScope && e.item==item && e.expScope==expScope; });
      return it!=m_elements.end();
    }
References e, and m_elements.
pop() [1/2]
void AccessStack::pop () [inline]
Definition at line 56 of file symbolresolver.cpp.
    {
      if (!m_elements.empty()) m_elements.pop_back();
    }
References m_elements.
Referenced by SymbolResolver::Private::isAccessibleFrom(), and SymbolResolver::Private::isAccessibleFromWithExpScope().
pop() [2/2]
void AccessStack::pop () [inline]
Definition at line 56 of file symbolresolver.cpp.
    {
      if (!m_elements.empty()) m_elements.pop_back();
    }
References m_elements.
push() [1/4]
void AccessStack::push (const Definition * scope, const FileDef * fileScope, const Definition * item) [inline]
Definition at line 48 of file symbolresolver.cpp.
    {
      m_elements.push_back(AccessElem(scope,fileScope,item));
    }
References m_elements.
Referenced by SymbolResolver::Private::isAccessibleFrom(), and SymbolResolver::Private::isAccessibleFromWithExpScope().
push() [2/4]
void AccessStack::push (const Definition * scope, const FileDef * fileScope, const Definition * item) [inline]
Definition at line 48 of file symbolresolver.cpp.
    {
      m_elements.push_back(AccessElem(scope,fileScope,item));
    }
References m_elements.
push() [3/4]
void AccessStack::push (const Definition * scope, const FileDef * fileScope, const Definition * item, const QCString & expScope) [inline]
Definition at line 52 of file symbolresolver.cpp.
    {
      m_elements.push_back(AccessElem(scope,fileScope,item,expScope));
    }
References m_elements.
push() [4/4]
void AccessStack::push (const Definition * scope, const FileDef * fileScope, const Definition * item, const QCString & expScope) [inline]
Definition at line 52 of file symbolresolver.cpp.
    {
      m_elements.push_back(AccessElem(scope,fileScope,item,expScope));
    }
References m_elements.
Member Data Documentation
m_elements
std::vector< AccessElem > AccessStack::m_elements [private]
Definition at line 78 of file symbolresolver.cpp.
Referenced by clear(), find(), pop(), and push().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/symbolresolver.cpp
doxygen/src/symbolresolver.cpp