LayoutParser Class Reference
Public Member Functions
void setDocumentLocator (const XMLLocator *locator)
void error (const std::string &fileName, int lineNr, const std::string &msg)
void startElement (const std::string &name, const XMLHandlers::Attributes &attrib)
void endElement (const std::string &name)
void startSimpleEntry (LayoutDocEntry::Kind k, const XMLHandlers::Attributes &attrib)
void startSectionEntry (LayoutDocEntry::Kind k, const XMLHandlers::Attributes &attrib, const QCString &title)
void startMemberDeclEntry (const XMLHandlers::Attributes &attrib, MemberListType type, const QCString &title, const QCString &subscript)
void startMemberDefEntry (const XMLHandlers::Attributes &attrib, MemberListType type, const QCString &title, const QCString &)
void startLayout (const XMLHandlers::Attributes &)
void startNavIndex (const XMLHandlers::Attributes &)
void endNavIndex ()
void startNavEntry (const XMLHandlers::Attributes &attrib)
void endNavEntry ()
void startClass (const XMLHandlers::Attributes &)
void endClass ()
void startNamespace (const XMLHandlers::Attributes &)
void endNamespace ()
void startConcept (const XMLHandlers::Attributes &)
void endConcept ()
void startFile (const XMLHandlers::Attributes &)
void endFile ()
void startGroup (const XMLHandlers::Attributes &)
void endGroup ()
void startDirectory (const XMLHandlers::Attributes &)
void endDirectory ()
void startMemberDef (const XMLHandlers::Attributes &)
void endMemberDef ()
void startMemberDecl (const XMLHandlers::Attributes &)
void endMemberDecl ()
void setDocumentLocator (const XMLLocator *locator)
void error (const std::string &fileName, int lineNr, const std::string &msg)
void startElement (const std::string &name, const XMLHandlers::Attributes &attrib)
void endElement (const std::string &name)
void startSimpleEntry (LayoutDocEntry::Kind k, const XMLHandlers::Attributes &attrib)
void startSectionEntry (LayoutDocEntry::Kind k, const XMLHandlers::Attributes &attrib, const QCString &title)
void startMemberDeclEntry (const XMLHandlers::Attributes &attrib, MemberListType type, const QCString &title, const QCString &subscript)
void startMemberDefEntry (const XMLHandlers::Attributes &attrib, MemberListType type, const QCString &title, const QCString &)
void startLayout (const XMLHandlers::Attributes &)
void startNavIndex (const XMLHandlers::Attributes &)
void endNavIndex ()
void startNavEntry (const XMLHandlers::Attributes &attrib)
void endNavEntry ()
void startClass (const XMLHandlers::Attributes &)
void endClass ()
void startNamespace (const XMLHandlers::Attributes &)
void endNamespace ()
void startConcept (const XMLHandlers::Attributes &)
void endConcept ()
void startFile (const XMLHandlers::Attributes &)
void endFile ()
void startGroup (const XMLHandlers::Attributes &)
void endGroup ()
void startDirectory (const XMLHandlers::Attributes &)
void endDirectory ()
void startMemberDef (const XMLHandlers::Attributes &)
void endMemberDef ()
void startMemberDecl (const XMLHandlers::Attributes &)
void endMemberDecl ()
Static Public Member Functions
static LayoutParser & instance ()
static LayoutParser & instance ()
Private Member Functions
LayoutParser ()
~LayoutParser ()
LayoutParser ()
~LayoutParser ()
Private Attributes
QCString m_scope
LayoutDocManager::LayoutPart m_part = LayoutDocManager::Undefined
LayoutNavEntry * m_rootNav = 0
bool m_invalidEntry = false
const XMLLocator * m_locator = nullptr
Static Private Attributes
static int m_userGroupCount =0
Detailed Description
Definition at line 174 of file layout.cpp.
Constructor & Destructor Documentation
LayoutParser() [1/2]
LayoutParser::LayoutParser () [inline], [private]
Definition at line 705 of file layout.cpp.
{ }
Referenced by instance().
 LayoutParser() [1/2]
LayoutParser::~LayoutParser () [inline], [private]
Definition at line 706 of file layout.cpp.
{ delete m_rootNav; }
References m_rootNav.
LayoutParser() [2/2]
LayoutParser::LayoutParser () [inline], [private]
Definition at line 705 of file layout.cpp.
{ }
 LayoutParser() [2/2]
LayoutParser::~LayoutParser () [inline], [private]
Definition at line 706 of file layout.cpp.
{ delete m_rootNav; }
References m_rootNav.
Member Function Documentation
endClass() [1/2]
void LayoutParser::endClass () [inline]
Definition at line 588 of file layout.cpp.
    {
      m_scope="";
      m_part = LayoutDocManager::Undefined;
    }
References m_part, m_scope, and LayoutDocManager::Undefined.
endClass() [2/2]
void LayoutParser::endClass () [inline]
Definition at line 588 of file layout.cpp.
    {
      m_scope="";
      m_part = LayoutDocManager::Undefined;
    }
References m_part, m_scope, and LayoutDocManager::Undefined.
endConcept() [1/2]
void LayoutParser::endConcept () [inline]
Definition at line 614 of file layout.cpp.
    {
      m_scope="";
      m_part = LayoutDocManager::Undefined;
    }
References m_part, m_scope, and LayoutDocManager::Undefined.
endConcept() [2/2]
void LayoutParser::endConcept () [inline]
Definition at line 614 of file layout.cpp.
    {
      m_scope="";
      m_part = LayoutDocManager::Undefined;
    }
References m_part, m_scope, and LayoutDocManager::Undefined.
endDirectory() [1/2]
void LayoutParser::endDirectory () [inline]
Definition at line 653 of file layout.cpp.
    {
      m_scope="";
      m_part = LayoutDocManager::Undefined;
    }
References m_part, m_scope, and LayoutDocManager::Undefined.
endDirectory() [2/2]
void LayoutParser::endDirectory () [inline]
Definition at line 653 of file layout.cpp.
    {
      m_scope="";
      m_part = LayoutDocManager::Undefined;
    }
References m_part, m_scope, and LayoutDocManager::Undefined.
endElement() [1/2]
void LayoutParser::endElement (const std::string & name)
Definition at line 1527 of file layout.cpp.
{
  //printf("endElement [%s]::[%s]\n",qPrint(m_scope),qPrint(name));
  auto it=g_elementHandlers.end();
  if (!m_scope.isEmpty() && m_scope.right(static_cast<uint>(name.length())+1)==name+"/")
  { // element ends current scope
    it = g_elementHandlers.find(m_scope.left(m_scope.length()-1).str());
  }
  else // continue with current scope
  {
    it = g_elementHandlers.find(m_scope.str()+name);
  }
  if (it!=g_elementHandlers.end())
  {
    it->second.endCb(*this);
  }
}
References anonymous_namespace{layout.cpp}::g_elementHandlers, QCString::isEmpty(), QCString::left(), QCString::length(), m_scope, setup::name, QCString::right(), and QCString::str().
Referenced by LayoutDocManager::init(), and LayoutDocManager::parse().
endElement() [2/2]
void LayoutParser::endElement (const std::string & name)
endFile() [1/2]
void LayoutParser::endFile () [inline]
Definition at line 627 of file layout.cpp.
    {
      m_scope="";
      m_part = LayoutDocManager::Undefined;
    }
References m_part, m_scope, and LayoutDocManager::Undefined.
endFile() [2/2]
void LayoutParser::endFile () [inline]
Definition at line 627 of file layout.cpp.
    {
      m_scope="";
      m_part = LayoutDocManager::Undefined;
    }
References m_part, m_scope, and LayoutDocManager::Undefined.
endGroup() [1/2]
void LayoutParser::endGroup () [inline]
Definition at line 640 of file layout.cpp.
    {
      m_scope="";
      m_part = LayoutDocManager::Undefined;
    }
References m_part, m_scope, and LayoutDocManager::Undefined.
endGroup() [2/2]
void LayoutParser::endGroup () [inline]
Definition at line 640 of file layout.cpp.
    {
      m_scope="";
      m_part = LayoutDocManager::Undefined;
    }
References m_part, m_scope, and LayoutDocManager::Undefined.
endMemberDecl() [1/2]
void LayoutParser::endMemberDecl () [inline]
Definition at line 690 of file layout.cpp.
    {
      int i=m_scope.findRev("memberdecl/");
      if (i!=-1)
      {
        m_scope=m_scope.left(i);
        if (m_part!=LayoutDocManager::Undefined)
        {
          LayoutDocManager::instance().addEntry(m_part,new LayoutDocEntrySimple(LayoutDocEntry::MemberDeclEnd));
        }
      }
    }
References LayoutDocManager::addEntry(), QCString::findRev(), LayoutDocManager::instance(), QCString::left(), m_part, m_scope, LayoutDocEntry::MemberDeclEnd, and LayoutDocManager::Undefined.
endMemberDecl() [2/2]
void LayoutParser::endMemberDecl () [inline]
Definition at line 690 of file layout.cpp.
    {
      int i=m_scope.findRev("memberdecl/");
      if (i!=-1)
      {
        m_scope=m_scope.left(i);
        if (m_part!=LayoutDocManager::Undefined)
        {
          LayoutDocManager::instance().addEntry(m_part,new LayoutDocEntrySimple(LayoutDocEntry::MemberDeclEnd));
        }
      }
    }
References LayoutDocManager::addEntry(), QCString::findRev(), LayoutDocManager::instance(), QCString::left(), m_part, m_scope, LayoutDocEntry::MemberDeclEnd, and LayoutDocManager::Undefined.
endMemberDef() [1/2]
void LayoutParser::endMemberDef () [inline]
Definition at line 668 of file layout.cpp.
    {
      int i=m_scope.findRev("memberdef/");
      if (i!=-1)
      {
        m_scope=m_scope.left(i);
        if (m_part!=LayoutDocManager::Undefined)
        {
          LayoutDocManager::instance().addEntry(m_part,new LayoutDocEntrySimple(LayoutDocEntry::MemberDefEnd));
        }
      }
    }
References LayoutDocManager::addEntry(), QCString::findRev(), LayoutDocManager::instance(), QCString::left(), m_part, m_scope, LayoutDocEntry::MemberDefEnd, and LayoutDocManager::Undefined.
endMemberDef() [2/2]
void LayoutParser::endMemberDef () [inline]
Definition at line 668 of file layout.cpp.
    {
      int i=m_scope.findRev("memberdef/");
      if (i!=-1)
      {
        m_scope=m_scope.left(i);
        if (m_part!=LayoutDocManager::Undefined)
        {
          LayoutDocManager::instance().addEntry(m_part,new LayoutDocEntrySimple(LayoutDocEntry::MemberDefEnd));
        }
      }
    }
References LayoutDocManager::addEntry(), QCString::findRev(), LayoutDocManager::instance(), QCString::left(), m_part, m_scope, LayoutDocEntry::MemberDefEnd, and LayoutDocManager::Undefined.
endNamespace() [1/2]
void LayoutParser::endNamespace () [inline]
Definition at line 601 of file layout.cpp.
    {
      m_scope="";
      m_part = LayoutDocManager::Undefined;
    }
References m_part, m_scope, and LayoutDocManager::Undefined.
endNamespace() [2/2]
void LayoutParser::endNamespace () [inline]
Definition at line 601 of file layout.cpp.
    {
      m_scope="";
      m_part = LayoutDocManager::Undefined;
    }
References m_part, m_scope, and LayoutDocManager::Undefined.
endNavEntry() [1/2]
void LayoutParser::endNavEntry () [inline]
Definition at line 574 of file layout.cpp.
    {
      // set the root back to the parent
      if (m_rootNav && !m_invalidEntry) m_rootNav = m_rootNav->parent();
      m_invalidEntry=FALSE;
    }
References FALSE, m_invalidEntry, m_rootNav, and LayoutNavEntry::parent().
endNavEntry() [2/2]
void LayoutParser::endNavEntry () [inline]
Definition at line 574 of file layout.cpp.
    {
      // set the root back to the parent
      if (m_rootNav && !m_invalidEntry) m_rootNav = m_rootNav->parent();
      m_invalidEntry=FALSE;
    }
References FALSE, m_invalidEntry, m_rootNav, and LayoutNavEntry::parent().
endNavIndex() [1/2]
void LayoutParser::endNavIndex () [inline]
Definition at line 264 of file layout.cpp.
    {
      m_scope="";
      if (m_rootNav && !m_rootNav->find(LayoutNavEntry::MainPage))
      {
        // no MainPage node... add one as the first item of the root node...
        new LayoutNavEntry(m_rootNav,LayoutNavEntry::MainPage, TRUE,
            /*Config_getBool(GENERATE_TREEVIEW) ? "main" :*/ "index",
            theTranslator->trMainPage(),"",TRUE);
      }
    }
References LayoutNavEntry::find(), m_rootNav, m_scope, LayoutNavEntry::MainPage, theTranslator, Translator::trMainPage(), and TRUE.
endNavIndex() [2/2]
void LayoutParser::endNavIndex () [inline]
Definition at line 264 of file layout.cpp.
    {
      m_scope="";
      if (m_rootNav && !m_rootNav->find(LayoutNavEntry::MainPage))
      {
        // no MainPage node... add one as the first item of the root node...
        new LayoutNavEntry(m_rootNav,LayoutNavEntry::MainPage, TRUE,
            /*Config_getBool(GENERATE_TREEVIEW) ? "main" :*/ "index",
            theTranslator->trMainPage(),"",TRUE);
      }
    }
References LayoutNavEntry::find(), m_rootNav, m_scope, LayoutNavEntry::MainPage, theTranslator, Translator::trMainPage(), and TRUE.
error() [1/2]
void LayoutParser::error (const std::string & fileName, int lineNr, const std::string & msg) [inline]
Definition at line 188 of file layout.cpp.
    {
      ::warn(fileName.c_str(),lineNr,"%s",msg.c_str());
    }
References msg(), and warn().
Referenced by LayoutDocManager::init(), and LayoutDocManager::parse().
error() [2/2]
void LayoutParser::error (const std::string & fileName, int lineNr, const std::string & msg) [inline]
Definition at line 188 of file layout.cpp.
    {
      ::warn(fileName.c_str(),lineNr,"%s",msg.c_str());
    }
References msg(), and warn().
instance() [1/2]
static LayoutParser & LayoutParser::instance () [inline], [static]
Definition at line 177 of file layout.cpp.
    {
      static LayoutParser *theInstance = new LayoutParser;
      return *theInstance;
    }
References LayoutParser().
Referenced by LayoutDocManager::init(), and LayoutDocManager::parse().
instance() [2/2]
static LayoutParser & LayoutParser::instance () [inline], [static]
Definition at line 177 of file layout.cpp.
    {
      static LayoutParser *theInstance = new LayoutParser;
      return *theInstance;
    }
References LayoutParser().
setDocumentLocator() [1/2]
void LayoutParser::setDocumentLocator (const XMLLocator * locator) [inline]
Definition at line 184 of file layout.cpp.
    {
      m_locator = locator;
    }
References m_locator.
Referenced by LayoutDocManager::init(), and LayoutDocManager::parse().
setDocumentLocator() [2/2]
void LayoutParser::setDocumentLocator (const XMLLocator * locator) [inline]
Definition at line 184 of file layout.cpp.
    {
      m_locator = locator;
    }
References m_locator.
startClass() [1/2]
void LayoutParser::startClass (const XMLHandlers::Attributes &) [inline]
Definition at line 581 of file layout.cpp.
    {
      LayoutDocManager::instance().clear(LayoutDocManager::Class);
      m_scope="class/";
      m_part = LayoutDocManager::Class;
    }
References LayoutDocManager::Class, LayoutDocManager::clear(), LayoutDocManager::instance(), m_part, and m_scope.
startClass() [2/2]
void LayoutParser::startClass (const XMLHandlers::Attributes &) [inline]
Definition at line 581 of file layout.cpp.
    {
      LayoutDocManager::instance().clear(LayoutDocManager::Class);
      m_scope="class/";
      m_part = LayoutDocManager::Class;
    }
References LayoutDocManager::Class, LayoutDocManager::clear(), LayoutDocManager::instance(), m_part, and m_scope.
startConcept() [1/2]
void LayoutParser::startConcept (const XMLHandlers::Attributes &) [inline]
Definition at line 607 of file layout.cpp.
    {
      LayoutDocManager::instance().clear(LayoutDocManager::Concept);
      m_scope="concept/";
      m_part = LayoutDocManager::Concept;
    }
References LayoutDocManager::clear(), LayoutDocManager::Concept, LayoutDocManager::instance(), m_part, and m_scope.
startConcept() [2/2]
void LayoutParser::startConcept (const XMLHandlers::Attributes &) [inline]
Definition at line 607 of file layout.cpp.
    {
      LayoutDocManager::instance().clear(LayoutDocManager::Concept);
      m_scope="concept/";
      m_part = LayoutDocManager::Concept;
    }
References LayoutDocManager::clear(), LayoutDocManager::Concept, LayoutDocManager::instance(), m_part, and m_scope.
startDirectory() [1/2]
void LayoutParser::startDirectory (const XMLHandlers::Attributes &) [inline]
Definition at line 646 of file layout.cpp.
    {
      LayoutDocManager::instance().clear(LayoutDocManager::Directory);
      m_scope="directory/";
      m_part = LayoutDocManager::Directory;
    }
References LayoutDocManager::clear(), LayoutDocManager::Directory, LayoutDocManager::instance(), m_part, and m_scope.
startDirectory() [2/2]
void LayoutParser::startDirectory (const XMLHandlers::Attributes &) [inline]
Definition at line 646 of file layout.cpp.
    {
      LayoutDocManager::instance().clear(LayoutDocManager::Directory);
      m_scope="directory/";
      m_part = LayoutDocManager::Directory;
    }
References LayoutDocManager::clear(), LayoutDocManager::Directory, LayoutDocManager::instance(), m_part, and m_scope.
startElement() [1/2]
void LayoutParser::startElement (const std::string & name, const XMLHandlers::Attributes & attrib)
Definition at line 1511 of file layout.cpp.
{
  //printf("startElement [%s]::[%s]\n",qPrint(m_scope),qPrint(name));
  auto it = g_elementHandlers.find(m_scope.str()+name);
  if (it!=g_elementHandlers.end())
  {
    it->second.startCb(*this,attrib);
  }
  else
  {
    std::string fileName = m_locator->fileName();
    ::warn(fileName.c_str(),m_locator->lineNr(),"Unexpected start tag '%s' found in scope='%s'!\n",
        qPrint(name),qPrint(m_scope));
  }
}
References XMLLocator::fileName(), anonymous_namespace{layout.cpp}::g_elementHandlers, XMLLocator::lineNr(), m_locator, m_scope, setup::name, qPrint(), QCString::str(), string, and warn().
Referenced by LayoutDocManager::init(), and LayoutDocManager::parse().
startElement() [2/2]
void LayoutParser::startElement (const std::string & name, const XMLHandlers::Attributes & attrib)
startFile() [1/2]
void LayoutParser::startFile (const XMLHandlers::Attributes &) [inline]
Definition at line 620 of file layout.cpp.
    {
      LayoutDocManager::instance().clear(LayoutDocManager::File);
      m_scope="file/";
      m_part = LayoutDocManager::File;
    }
References LayoutDocManager::clear(), LayoutDocManager::File, LayoutDocManager::instance(), m_part, and m_scope.
startFile() [2/2]
void LayoutParser::startFile (const XMLHandlers::Attributes &) [inline]
Definition at line 620 of file layout.cpp.
    {
      LayoutDocManager::instance().clear(LayoutDocManager::File);
      m_scope="file/";
      m_part = LayoutDocManager::File;
    }
References LayoutDocManager::clear(), LayoutDocManager::File, LayoutDocManager::instance(), m_part, and m_scope.
startGroup() [1/2]
void LayoutParser::startGroup (const XMLHandlers::Attributes &) [inline]
Definition at line 633 of file layout.cpp.
    {
      LayoutDocManager::instance().clear(LayoutDocManager::Group);
      m_scope="group/";
      m_part = LayoutDocManager::Group;
    }
References LayoutDocManager::clear(), LayoutDocManager::Group, LayoutDocManager::instance(), m_part, and m_scope.
startGroup() [2/2]
void LayoutParser::startGroup (const XMLHandlers::Attributes &) [inline]
Definition at line 633 of file layout.cpp.
    {
      LayoutDocManager::instance().clear(LayoutDocManager::Group);
      m_scope="group/";
      m_part = LayoutDocManager::Group;
    }
References LayoutDocManager::clear(), LayoutDocManager::Group, LayoutDocManager::instance(), m_part, and m_scope.
startLayout() [1/2]
void LayoutParser::startLayout (const XMLHandlers::Attributes &) [inline]
Definition at line 250 of file layout.cpp.
    {
    }
startLayout() [2/2]
void LayoutParser::startLayout (const XMLHandlers::Attributes &) [inline]
Definition at line 250 of file layout.cpp.
    {
    }
startMemberDecl() [1/2]
void LayoutParser::startMemberDecl (const XMLHandlers::Attributes &) [inline]
Definition at line 681 of file layout.cpp.
    {
      m_scope+="memberdecl/";
      if (m_part!=LayoutDocManager::Undefined)
      {
        LayoutDocManager::instance().addEntry(m_part,new LayoutDocEntrySimple(LayoutDocEntry::MemberDeclStart));
      }
    }
References LayoutDocManager::addEntry(), LayoutDocManager::instance(), m_part, m_scope, LayoutDocEntry::MemberDeclStart, and LayoutDocManager::Undefined.
startMemberDecl() [2/2]
void LayoutParser::startMemberDecl (const XMLHandlers::Attributes &) [inline]
Definition at line 681 of file layout.cpp.
    {
      m_scope+="memberdecl/";
      if (m_part!=LayoutDocManager::Undefined)
      {
        LayoutDocManager::instance().addEntry(m_part,new LayoutDocEntrySimple(LayoutDocEntry::MemberDeclStart));
      }
    }
References LayoutDocManager::addEntry(), LayoutDocManager::instance(), m_part, m_scope, LayoutDocEntry::MemberDeclStart, and LayoutDocManager::Undefined.
startMemberDeclEntry() [1/2]
void LayoutParser::startMemberDeclEntry (const XMLHandlers::Attributes & attrib, MemberListType type, const QCString & title, const QCString & subscript) [inline]
Definition at line 221 of file layout.cpp.
    {
      //QCString visible = convertToQCString(XMLHandlers::value(attrib,"visible"));
      //bool isVisible = visible.isEmpty() || (visible!="no" && visible!="0");
      QCString userTitle = XMLHandlers::value(attrib,"title");
      QCString userSubscript = XMLHandlers::value(attrib,"subtitle");
      if (userTitle.isEmpty()) userTitle = title;
      if (userSubscript.isEmpty()) userSubscript = subscript;
      //printf("memberdecl: %s\n",qPrint(userTitle));
      if (m_part!=LayoutDocManager::Undefined)
      {
        LayoutDocManager::instance().addEntry(m_part,new LayoutDocEntryMemberDecl(type,userTitle,userSubscript));
      }
    }
References LayoutDocManager::addEntry(), LayoutDocManager::instance(), QCString::isEmpty(), m_part, LayoutDocManager::Undefined, and XMLHandlers::value().
startMemberDeclEntry() [2/2]
void LayoutParser::startMemberDeclEntry (const XMLHandlers::Attributes & attrib, MemberListType type, const QCString & title, const QCString & subscript) [inline]
Definition at line 221 of file layout.cpp.
    {
      //QCString visible = convertToQCString(XMLHandlers::value(attrib,"visible"));
      //bool isVisible = visible.isEmpty() || (visible!="no" && visible!="0");
      QCString userTitle = XMLHandlers::value(attrib,"title");
      QCString userSubscript = XMLHandlers::value(attrib,"subtitle");
      if (userTitle.isEmpty()) userTitle = title;
      if (userSubscript.isEmpty()) userSubscript = subscript;
      //printf("memberdecl: %s\n",qPrint(userTitle));
      if (m_part!=LayoutDocManager::Undefined)
      {
        LayoutDocManager::instance().addEntry(m_part,new LayoutDocEntryMemberDecl(type,userTitle,userSubscript));
      }
    }
References LayoutDocManager::addEntry(), LayoutDocManager::instance(), QCString::isEmpty(), m_part, LayoutDocManager::Undefined, and XMLHandlers::value().
startMemberDef() [1/2]
void LayoutParser::startMemberDef (const XMLHandlers::Attributes &) [inline]
Definition at line 659 of file layout.cpp.
    {
      m_scope+="memberdef/";
      if (m_part!=LayoutDocManager::Undefined)
      {
        LayoutDocManager::instance().addEntry(m_part,new LayoutDocEntrySimple(LayoutDocEntry::MemberDefStart));
      }
    }
References LayoutDocManager::addEntry(), LayoutDocManager::instance(), m_part, m_scope, LayoutDocEntry::MemberDefStart, and LayoutDocManager::Undefined.
startMemberDef() [2/2]
void LayoutParser::startMemberDef (const XMLHandlers::Attributes &) [inline]
Definition at line 659 of file layout.cpp.
    {
      m_scope+="memberdef/";
      if (m_part!=LayoutDocManager::Undefined)
      {
        LayoutDocManager::instance().addEntry(m_part,new LayoutDocEntrySimple(LayoutDocEntry::MemberDefStart));
      }
    }
References LayoutDocManager::addEntry(), LayoutDocManager::instance(), m_part, m_scope, LayoutDocEntry::MemberDefStart, and LayoutDocManager::Undefined.
startMemberDefEntry() [1/2]
void LayoutParser::startMemberDefEntry (const XMLHandlers::Attributes & attrib, MemberListType type, const QCString & title, const QCString &) [inline]
Definition at line 237 of file layout.cpp.
    {
      QCString userTitle = XMLHandlers::value(attrib,"title");
      if (userTitle.isEmpty()) userTitle = title;
      //printf("memberdef: %s\n",qPrint(userTitle));
      if (m_part!=LayoutDocManager::Undefined)
      {
        LayoutDocManager::instance().addEntry(m_part,
                                              new LayoutDocEntryMemberDef(type,userTitle));
      }
    }
References LayoutDocManager::addEntry(), LayoutDocManager::instance(), QCString::isEmpty(), m_part, LayoutDocManager::Undefined, and XMLHandlers::value().
startMemberDefEntry() [2/2]
void LayoutParser::startMemberDefEntry (const XMLHandlers::Attributes & attrib, MemberListType type, const QCString & title, const QCString &) [inline]
Definition at line 237 of file layout.cpp.
    {
      QCString userTitle = XMLHandlers::value(attrib,"title");
      if (userTitle.isEmpty()) userTitle = title;
      //printf("memberdef: %s\n",qPrint(userTitle));
      if (m_part!=LayoutDocManager::Undefined)
      {
        LayoutDocManager::instance().addEntry(m_part,
                                              new LayoutDocEntryMemberDef(type,userTitle));
      }
    }
References LayoutDocManager::addEntry(), LayoutDocManager::instance(), QCString::isEmpty(), m_part, LayoutDocManager::Undefined, and XMLHandlers::value().
startNamespace() [1/2]
void LayoutParser::startNamespace (const XMLHandlers::Attributes &) [inline]
Definition at line 594 of file layout.cpp.
    {
      LayoutDocManager::instance().clear(LayoutDocManager::Namespace);
      m_scope="namespace/";
      m_part = LayoutDocManager::Namespace;
    }
References LayoutDocManager::clear(), LayoutDocManager::instance(), m_part, m_scope, and LayoutDocManager::Namespace.
startNamespace() [2/2]
void LayoutParser::startNamespace (const XMLHandlers::Attributes &) [inline]
Definition at line 594 of file layout.cpp.
    {
      LayoutDocManager::instance().clear(LayoutDocManager::Namespace);
      m_scope="namespace/";
      m_part = LayoutDocManager::Namespace;
    }
References LayoutDocManager::clear(), LayoutDocManager::instance(), m_part, m_scope, and LayoutDocManager::Namespace.
startNavEntry() [1/2]
void LayoutParser::startNavEntry (const XMLHandlers::Attributes & attrib) [inline]
Definition at line 276 of file layout.cpp.
    {
      bool javaOpt = Config_getBool(OPTIMIZE_OUTPUT_JAVA);
      bool fortranOpt = Config_getBool(OPTIMIZE_FOR_FORTRAN);
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      bool sliceOpt = Config_getBool(OPTIMIZE_OUTPUT_SLICE);
      bool hasGraphicalHierarchy = Config_getBool(HAVE_DOT) &&
                                          Config_getBool(GRAPHICAL_HIERARCHY);
      bool extractAll = Config_getBool(EXTRACT_ALL);
      static struct NavEntryMap
      {
        const char *typeStr; // type attribute name in the XML file
        LayoutNavEntry::Kind kind; // corresponding enum name
        QCString mainName; // default title for an item if it has children
        QCString subName; // optional name for an item if it is rendered as a child
        QCString intro; // introduction text to be put on the index page
        QCString baseFile; // base name of the file containing the index page
      } mapping[] =
      {
        { "mainpage",
          LayoutNavEntry::MainPage,
          theTranslator->trMainPage(),
          QCString(),
          QCString(),
          "index"
        },
        { "pages",
          LayoutNavEntry::Pages,
          theTranslator->trRelatedPages(),
          QCString(),
          theTranslator->trRelatedPagesDescription(),
          "pages"
        },
        { "modules",
          LayoutNavEntry::Modules,
          theTranslator->trModules(),
          QCString(),
          theTranslator->trModulesDescription(),
          "modules"
        },
        { "namespaces",
          LayoutNavEntry::Namespaces,
          javaOpt || vhdlOpt ? theTranslator->trPackages() : fortranOpt || sliceOpt ? theTranslator->trModules() : theTranslator->trNamespaces(),
          javaOpt || vhdlOpt ? theTranslator->trPackageList() : fortranOpt || sliceOpt ? theTranslator->trModulesList() : theTranslator->trNamespaceList(),
          javaOpt || vhdlOpt ? theTranslator->trPackageListDescription() : fortranOpt || sliceOpt ? theTranslator->trModulesListDescription(extractAll) : theTranslator->trNamespaceListDescription(extractAll),
          "namespaces"
        },
        { "namespacelist",
          LayoutNavEntry::NamespaceList,
          javaOpt || vhdlOpt ? theTranslator->trPackageList() : fortranOpt || sliceOpt ? theTranslator->trModulesList() : theTranslator->trNamespaceList(),
          QCString(),
          javaOpt || vhdlOpt ? theTranslator->trPackageListDescription() : fortranOpt || sliceOpt ? theTranslator->trModulesListDescription(extractAll) : theTranslator->trNamespaceListDescription(extractAll),
          "namespaces"
        },
        { "namespacemembers",
          LayoutNavEntry::NamespaceMembers,
          javaOpt || vhdlOpt ? theTranslator->trPackageMembers() : fortranOpt || sliceOpt ? theTranslator->trModulesMembers() : theTranslator->trNamespaceMembers(),
          QCString(),
          fortranOpt || sliceOpt ? theTranslator->trModulesMemberDescription(extractAll) : theTranslator->trNamespaceMemberDescription(extractAll),
          "namespacemembers"
        },
        { "concepts",
          LayoutNavEntry::Concepts,
          theTranslator->trConcept(true,false),
          theTranslator->trConceptList(),
          theTranslator->trConceptListDescription(extractAll),
          "concepts"
        },
        { "classindex",
          LayoutNavEntry::ClassIndex,
          fortranOpt ? theTranslator->trCompoundIndexFortran() : vhdlOpt ? theTranslator->trDesignUnitIndex() : theTranslator->trCompoundIndex(),
          QCString(),
          QCString(),
          "classes"
        },
        { "classes",
          LayoutNavEntry::Classes,
          fortranOpt ? theTranslator->trDataTypes() : vhdlOpt ? theTranslator->trDesignUnits() : theTranslator->trClasses(),
          theTranslator->trCompoundList(),
          fortranOpt ? theTranslator->trCompoundListDescriptionFortran() : vhdlOpt ? theTranslator->trDesignUnitListDescription() : theTranslator->trCompoundListDescription(),
          "annotated"
        },
        { "classlist",
          LayoutNavEntry::ClassList,
          fortranOpt ? theTranslator->trCompoundListFortran() : vhdlOpt ? theTranslator->trDesignUnitList() : theTranslator->trCompoundList(),
          QCString(),
          fortranOpt ? theTranslator->trCompoundListDescriptionFortran() : vhdlOpt ? theTranslator->trDesignUnitListDescription() : theTranslator->trCompoundListDescription(),
          "annotated"
        },
        { "hierarchy",
          LayoutNavEntry::ClassHierarchy,
          vhdlOpt ? theTranslator->trDesignUnitHierarchy() : theTranslator->trClassHierarchy(),
          QCString(),
          theTranslator->trClassHierarchyDescription(),
          hasGraphicalHierarchy ? "inherits" : "hierarchy"
        },
        { "classmembers",
          LayoutNavEntry::ClassMembers,
          fortranOpt ? theTranslator->trCompoundMembersFortran() : vhdlOpt ? theTranslator->trDesignUnitMembers() : theTranslator->trCompoundMembers(),
          QCString(),
          fortranOpt ? theTranslator->trCompoundMembersDescriptionFortran(extractAll) : theTranslator->trCompoundMembersDescription(extractAll),
          "functions"
        },
        { "interfaceindex",
          LayoutNavEntry::InterfaceIndex,
          theTranslator->trInterfaceIndex(),
          QCString(),
          QCString(),
          "interfaces"
        },
        { "interfaces",
          LayoutNavEntry::Interfaces,
          theTranslator->trSliceInterfaces(),
          theTranslator->trInterfaceList(),
          theTranslator->trInterfaceListDescription(),
          "annotatedinterfaces"
        },
        { "interfacelist",
          LayoutNavEntry::InterfaceList,
          theTranslator->trInterfaceList(),
          QCString(),
          theTranslator->trInterfaceListDescription(),
          "annotatedinterfaces"
        },
        { "interfacehierarchy",
          LayoutNavEntry::InterfaceHierarchy,
          theTranslator->trInterfaceHierarchy(),
          QCString(),
          theTranslator->trInterfaceHierarchyDescription(),
          hasGraphicalHierarchy ? "interfaceinherits" : "interfacehierarchy"
        },
        { "structindex",
          LayoutNavEntry::StructIndex,
          theTranslator->trStructIndex(),
          QCString(),
          QCString(),
          "structs"
        },
        { "structs",
          LayoutNavEntry::Structs,
          theTranslator->trStructs(),
          theTranslator->trStructList(),
          theTranslator->trStructListDescription(),
          "annotatedstructs"
        },
        { "structlist",
          LayoutNavEntry::StructList,
          theTranslator->trStructList(),
          QCString(),
          theTranslator->trStructListDescription(),
          "annotatedstructs"
        },
        { "exceptionindex",
          LayoutNavEntry::ExceptionIndex,
          theTranslator->trExceptionIndex(),
          QCString(),
          QCString(),
          "exceptions"
        },
        { "exceptions",
          LayoutNavEntry::Exceptions,
          theTranslator->trExceptions(),
          theTranslator->trExceptionList(),
          theTranslator->trExceptionListDescription(),
          "annotatedexceptions"
        },
        { "exceptionlist",
          LayoutNavEntry::ExceptionList,
          theTranslator->trExceptionList(),
          QCString(),
          theTranslator->trExceptionListDescription(),
          "annotatedexceptions"
        },
        { "exceptionhierarchy",
          LayoutNavEntry::ExceptionHierarchy,
          theTranslator->trExceptionHierarchy(),
          QCString(),
          theTranslator->trExceptionHierarchyDescription(),
          hasGraphicalHierarchy ? "exceptioninherits" : "exceptionhierarchy"
        },
        { "files",
          LayoutNavEntry::Files,
          theTranslator->trFile(TRUE,FALSE),
          theTranslator->trFileList(),
          theTranslator->trFileListDescription(extractAll),
          "files"
        },
        { "filelist",
          LayoutNavEntry::FileList,
          theTranslator->trFileList(),
          QCString(),
          theTranslator->trFileListDescription(extractAll),
          "files"
        },
        { "globals",
          LayoutNavEntry::FileGlobals,
          theTranslator->trFileMembers(),
          QCString(),
          theTranslator->trFileMembersDescription(extractAll),
          "globals"
        },
        { "examples",
          LayoutNavEntry::Examples,
          theTranslator->trExamples(),
          QCString(),
          theTranslator->trExamplesDescription(),
          "examples"
        },
        { "user",
          LayoutNavEntry::User,
          QCString(),
          QCString(),
          QCString(),
          "user"
        },
        { "usergroup",
          LayoutNavEntry::UserGroup,
          QCString(),
          QCString(),
          QCString(),
          "usergroup"
        },
        { 0, // end of list
          static_cast<LayoutNavEntry::Kind>(0),
          QCString(),
          QCString(),
          QCString(),
          QCString()
        }
      };
      // find type in the table
      int i=0;
      QCString type = XMLHandlers::value(attrib,"type");
      while (mapping[i].typeStr)
      {
        if (mapping[i].typeStr==type)
          break;
        i++;
      }
      if (mapping[i].typeStr==0)
      {
        std::string fileName = m_locator->fileName();
        if (type.isEmpty())
        {
          ::warn(fileName.c_str(),m_locator->lineNr(),"an entry tag within a navindex has no type attribute! Check your layout file!\n");
        }
        else
        {
          ::warn(fileName.c_str(),m_locator->lineNr(),"the type '%s' is not supported for the entry tag within a navindex! Check your layout file!\n",qPrint(type));
        }
        m_invalidEntry=TRUE;
        return;
      }
      LayoutNavEntry::Kind kind = mapping[i].kind;
      QCString baseFile = mapping[i].baseFile;
      QCString title = XMLHandlers::value(attrib,"title");
      bool isVisible = elemIsVisible(attrib) && parentIsVisible(m_rootNav);
      if (title.isEmpty()) // use default title
      {
        title = mapping[i].mainName; // use title for main row
        if (m_rootNav!=LayoutDocManager::instance().rootNavEntry() && !mapping[i].subName.isEmpty())
        {
          title = mapping[i].subName; // if this is a child of another row, use the subName if available
                                      // this is mainly done to get compatible naming with older versions.
        }
      }
      QCString intro = XMLHandlers::value(attrib,"intro");
      if (intro.isEmpty()) // use default intro text
      {
        intro = mapping[i].intro;
      }
      QCString url = XMLHandlers::value(attrib,"url");
      if (mapping[i].kind==LayoutNavEntry::User && !url.isEmpty())
      {
        baseFile=url;
      }
      else if (kind==LayoutNavEntry::UserGroup)
      {
        if (!url.isEmpty())
        {
          if (url == "[none]")
          {
            baseFile = QCString();
          }
          else
          {
            baseFile=url;
          }
        }
        else
        {
          baseFile+=QCString().sprintf("%d",m_userGroupCount++);
        }
      }
      // create new item and make it the new root
      m_rootNav = new LayoutNavEntry(m_rootNav,kind,isVisible,baseFile,title,intro);
    }
References LayoutNavEntry::Classes, LayoutNavEntry::ClassHierarchy, LayoutNavEntry::ClassIndex, LayoutNavEntry::ClassList, LayoutNavEntry::ClassMembers, LayoutNavEntry::Concepts, Config_getBool, elemIsVisible(), LayoutNavEntry::Examples, LayoutNavEntry::ExceptionHierarchy, LayoutNavEntry::ExceptionIndex, LayoutNavEntry::ExceptionList, LayoutNavEntry::Exceptions, FALSE, LayoutNavEntry::FileGlobals, LayoutNavEntry::FileList, XMLLocator::fileName(), LayoutNavEntry::Files, LayoutDocManager::instance(), LayoutNavEntry::InterfaceHierarchy, LayoutNavEntry::InterfaceIndex, LayoutNavEntry::InterfaceList, LayoutNavEntry::Interfaces, QCString::isEmpty(), XMLLocator::lineNr(), m_invalidEntry, m_locator, m_rootNav, m_userGroupCount, LayoutNavEntry::MainPage, LayoutNavEntry::Modules, LayoutNavEntry::NamespaceList, LayoutNavEntry::NamespaceMembers, LayoutNavEntry::Namespaces, LayoutNavEntry::Pages, parentIsVisible(), qPrint(), QCString::sprintf(), string, LayoutNavEntry::StructIndex, LayoutNavEntry::StructList, LayoutNavEntry::Structs, theTranslator, Translator::trClasses(), Translator::trClassHierarchy(), Translator::trClassHierarchyDescription(), Translator::trCompoundIndex(), Translator::trCompoundIndexFortran(), Translator::trCompoundList(), Translator::trCompoundListDescription(), Translator::trCompoundListDescriptionFortran(), Translator::trCompoundListFortran(), Translator::trCompoundMembers(), Translator::trCompoundMembersDescription(), Translator::trCompoundMembersDescriptionFortran(), Translator::trCompoundMembersFortran(), Translator::trConcept(), Translator::trConceptList(), Translator::trConceptListDescription(), Translator::trDataTypes(), Translator::trDesignUnitHierarchy(), Translator::trDesignUnitIndex(), Translator::trDesignUnitList(), Translator::trDesignUnitListDescription(), Translator::trDesignUnitMembers(), Translator::trDesignUnits(), Translator::trExamples(), Translator::trExamplesDescription(), Translator::trExceptionHierarchy(), Translator::trExceptionHierarchyDescription(), Translator::trExceptionIndex(), Translator::trExceptionList(), Translator::trExceptionListDescription(), Translator::trExceptions(), Translator::trFile(), Translator::trFileList(), Translator::trFileListDescription(), Translator::trFileMembers(), Translator::trFileMembersDescription(), Translator::trInterfaceHierarchy(), Translator::trInterfaceHierarchyDescription(), Translator::trInterfaceIndex(), Translator::trInterfaceList(), Translator::trInterfaceListDescription(), Translator::trMainPage(), Translator::trModules(), Translator::trModulesDescription(), Translator::trModulesList(), Translator::trModulesListDescription(), Translator::trModulesMemberDescription(), Translator::trModulesMembers(), Translator::trNamespaceList(), Translator::trNamespaceListDescription(), Translator::trNamespaceMemberDescription(), Translator::trNamespaceMembers(), Translator::trNamespaces(), Translator::trPackageList(), Translator::trPackageListDescription(), Translator::trPackageMembers(), Translator::trPackages(), Translator::trRelatedPages(), Translator::trRelatedPagesDescription(), Translator::trSliceInterfaces(), Translator::trStructIndex(), Translator::trStructList(), Translator::trStructListDescription(), Translator::trStructs(), TRUE, setup::url, LayoutNavEntry::User, LayoutNavEntry::UserGroup, XMLHandlers::value(), and warn().
startNavEntry() [2/2]
void LayoutParser::startNavEntry (const XMLHandlers::Attributes & attrib) [inline]
Definition at line 276 of file layout.cpp.
    {
      bool javaOpt = Config_getBool(OPTIMIZE_OUTPUT_JAVA);
      bool fortranOpt = Config_getBool(OPTIMIZE_FOR_FORTRAN);
      bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
      bool sliceOpt = Config_getBool(OPTIMIZE_OUTPUT_SLICE);
      bool hasGraphicalHierarchy = Config_getBool(HAVE_DOT) &&
                                          Config_getBool(GRAPHICAL_HIERARCHY);
      bool extractAll = Config_getBool(EXTRACT_ALL);
      static struct NavEntryMap
      {
        const char *typeStr; // type attribute name in the XML file
        LayoutNavEntry::Kind kind; // corresponding enum name
        QCString mainName; // default title for an item if it has children
        QCString subName; // optional name for an item if it is rendered as a child
        QCString intro; // introduction text to be put on the index page
        QCString baseFile; // base name of the file containing the index page
      } mapping[] =
      {
        { "mainpage",
          LayoutNavEntry::MainPage,
          theTranslator->trMainPage(),
          QCString(),
          QCString(),
          "index"
        },
        { "pages",
          LayoutNavEntry::Pages,
          theTranslator->trRelatedPages(),
          QCString(),
          theTranslator->trRelatedPagesDescription(),
          "pages"
        },
        { "modules",
          LayoutNavEntry::Modules,
          theTranslator->trModules(),
          QCString(),
          theTranslator->trModulesDescription(),
          "modules"
        },
        { "namespaces",
          LayoutNavEntry::Namespaces,
          javaOpt || vhdlOpt ? theTranslator->trPackages() : fortranOpt || sliceOpt ? theTranslator->trModules() : theTranslator->trNamespaces(),
          javaOpt || vhdlOpt ? theTranslator->trPackageList() : fortranOpt || sliceOpt ? theTranslator->trModulesList() : theTranslator->trNamespaceList(),
          javaOpt || vhdlOpt ? theTranslator->trPackageListDescription() : fortranOpt || sliceOpt ? theTranslator->trModulesListDescription(extractAll) : theTranslator->trNamespaceListDescription(extractAll),
          "namespaces"
        },
        { "namespacelist",
          LayoutNavEntry::NamespaceList,
          javaOpt || vhdlOpt ? theTranslator->trPackageList() : fortranOpt || sliceOpt ? theTranslator->trModulesList() : theTranslator->trNamespaceList(),
          QCString(),
          javaOpt || vhdlOpt ? theTranslator->trPackageListDescription() : fortranOpt || sliceOpt ? theTranslator->trModulesListDescription(extractAll) : theTranslator->trNamespaceListDescription(extractAll),
          "namespaces"
        },
        { "namespacemembers",
          LayoutNavEntry::NamespaceMembers,
          javaOpt || vhdlOpt ? theTranslator->trPackageMembers() : fortranOpt || sliceOpt ? theTranslator->trModulesMembers() : theTranslator->trNamespaceMembers(),
          QCString(),
          fortranOpt || sliceOpt ? theTranslator->trModulesMemberDescription(extractAll) : theTranslator->trNamespaceMemberDescription(extractAll),
          "namespacemembers"
        },
        { "concepts",
          LayoutNavEntry::Concepts,
          theTranslator->trConcept(true,false),
          theTranslator->trConceptList(),
          theTranslator->trConceptListDescription(extractAll),
          "concepts"
        },
        { "classindex",
          LayoutNavEntry::ClassIndex,
          fortranOpt ? theTranslator->trCompoundIndexFortran() : vhdlOpt ? theTranslator->trDesignUnitIndex() : theTranslator->trCompoundIndex(),
          QCString(),
          QCString(),
          "classes"
        },
        { "classes",
          LayoutNavEntry::Classes,
          fortranOpt ? theTranslator->trDataTypes() : vhdlOpt ? theTranslator->trDesignUnits() : theTranslator->trClasses(),
          theTranslator->trCompoundList(),
          fortranOpt ? theTranslator->trCompoundListDescriptionFortran() : vhdlOpt ? theTranslator->trDesignUnitListDescription() : theTranslator->trCompoundListDescription(),
          "annotated"
        },
        { "classlist",
          LayoutNavEntry::ClassList,
          fortranOpt ? theTranslator->trCompoundListFortran() : vhdlOpt ? theTranslator->trDesignUnitList() : theTranslator->trCompoundList(),
          QCString(),
          fortranOpt ? theTranslator->trCompoundListDescriptionFortran() : vhdlOpt ? theTranslator->trDesignUnitListDescription() : theTranslator->trCompoundListDescription(),
          "annotated"
        },
        { "hierarchy",
          LayoutNavEntry::ClassHierarchy,
          vhdlOpt ? theTranslator->trDesignUnitHierarchy() : theTranslator->trClassHierarchy(),
          QCString(),
          theTranslator->trClassHierarchyDescription(),
          hasGraphicalHierarchy ? "inherits" : "hierarchy"
        },
        { "classmembers",
          LayoutNavEntry::ClassMembers,
          fortranOpt ? theTranslator->trCompoundMembersFortran() : vhdlOpt ? theTranslator->trDesignUnitMembers() : theTranslator->trCompoundMembers(),
          QCString(),
          fortranOpt ? theTranslator->trCompoundMembersDescriptionFortran(extractAll) : theTranslator->trCompoundMembersDescription(extractAll),
          "functions"
        },
        { "interfaceindex",
          LayoutNavEntry::InterfaceIndex,
          theTranslator->trInterfaceIndex(),
          QCString(),
          QCString(),
          "interfaces"
        },
        { "interfaces",
          LayoutNavEntry::Interfaces,
          theTranslator->trSliceInterfaces(),
          theTranslator->trInterfaceList(),
          theTranslator->trInterfaceListDescription(),
          "annotatedinterfaces"
        },
        { "interfacelist",
          LayoutNavEntry::InterfaceList,
          theTranslator->trInterfaceList(),
          QCString(),
          theTranslator->trInterfaceListDescription(),
          "annotatedinterfaces"
        },
        { "interfacehierarchy",
          LayoutNavEntry::InterfaceHierarchy,
          theTranslator->trInterfaceHierarchy(),
          QCString(),
          theTranslator->trInterfaceHierarchyDescription(),
          hasGraphicalHierarchy ? "interfaceinherits" : "interfacehierarchy"
        },
        { "structindex",
          LayoutNavEntry::StructIndex,
          theTranslator->trStructIndex(),
          QCString(),
          QCString(),
          "structs"
        },
        { "structs",
          LayoutNavEntry::Structs,
          theTranslator->trStructs(),
          theTranslator->trStructList(),
          theTranslator->trStructListDescription(),
          "annotatedstructs"
        },
        { "structlist",
          LayoutNavEntry::StructList,
          theTranslator->trStructList(),
          QCString(),
          theTranslator->trStructListDescription(),
          "annotatedstructs"
        },
        { "exceptionindex",
          LayoutNavEntry::ExceptionIndex,
          theTranslator->trExceptionIndex(),
          QCString(),
          QCString(),
          "exceptions"
        },
        { "exceptions",
          LayoutNavEntry::Exceptions,
          theTranslator->trExceptions(),
          theTranslator->trExceptionList(),
          theTranslator->trExceptionListDescription(),
          "annotatedexceptions"
        },
        { "exceptionlist",
          LayoutNavEntry::ExceptionList,
          theTranslator->trExceptionList(),
          QCString(),
          theTranslator->trExceptionListDescription(),
          "annotatedexceptions"
        },
        { "exceptionhierarchy",
          LayoutNavEntry::ExceptionHierarchy,
          theTranslator->trExceptionHierarchy(),
          QCString(),
          theTranslator->trExceptionHierarchyDescription(),
          hasGraphicalHierarchy ? "exceptioninherits" : "exceptionhierarchy"
        },
        { "files",
          LayoutNavEntry::Files,
          theTranslator->trFile(TRUE,FALSE),
          theTranslator->trFileList(),
          theTranslator->trFileListDescription(extractAll),
          "files"
        },
        { "filelist",
          LayoutNavEntry::FileList,
          theTranslator->trFileList(),
          QCString(),
          theTranslator->trFileListDescription(extractAll),
          "files"
        },
        { "globals",
          LayoutNavEntry::FileGlobals,
          theTranslator->trFileMembers(),
          QCString(),
          theTranslator->trFileMembersDescription(extractAll),
          "globals"
        },
        { "examples",
          LayoutNavEntry::Examples,
          theTranslator->trExamples(),
          QCString(),
          theTranslator->trExamplesDescription(),
          "examples"
        },
        { "user",
          LayoutNavEntry::User,
          QCString(),
          QCString(),
          QCString(),
          "user"
        },
        { "usergroup",
          LayoutNavEntry::UserGroup,
          QCString(),
          QCString(),
          QCString(),
          "usergroup"
        },
        { 0, // end of list
          static_cast<LayoutNavEntry::Kind>(0),
          QCString(),
          QCString(),
          QCString(),
          QCString()
        }
      };
      // find type in the table
      int i=0;
      QCString type = XMLHandlers::value(attrib,"type");
      while (mapping[i].typeStr)
      {
        if (mapping[i].typeStr==type)
          break;
        i++;
      }
      if (mapping[i].typeStr==0)
      {
        std::string fileName = m_locator->fileName();
        if (type.isEmpty())
        {
          ::warn(fileName.c_str(),m_locator->lineNr(),"an entry tag within a navindex has no type attribute! Check your layout file!\n");
        }
        else
        {
          ::warn(fileName.c_str(),m_locator->lineNr(),"the type '%s' is not supported for the entry tag within a navindex! Check your layout file!\n",qPrint(type));
        }
        m_invalidEntry=TRUE;
        return;
      }
      LayoutNavEntry::Kind kind = mapping[i].kind;
      QCString baseFile = mapping[i].baseFile;
      QCString title = XMLHandlers::value(attrib,"title");
      bool isVisible = elemIsVisible(attrib) && parentIsVisible(m_rootNav);
      if (title.isEmpty()) // use default title
      {
        title = mapping[i].mainName; // use title for main row
        if (m_rootNav!=LayoutDocManager::instance().rootNavEntry() && !mapping[i].subName.isEmpty())
        {
          title = mapping[i].subName; // if this is a child of another row, use the subName if available
                                      // this is mainly done to get compatible naming with older versions.
        }
      }
      QCString intro = XMLHandlers::value(attrib,"intro");
      if (intro.isEmpty()) // use default intro text
      {
        intro = mapping[i].intro;
      }
      QCString url = XMLHandlers::value(attrib,"url");
      if (mapping[i].kind==LayoutNavEntry::User && !url.isEmpty())
      {
        baseFile=url;
      }
      else if (kind==LayoutNavEntry::UserGroup)
      {
        if (!url.isEmpty())
        {
          if (url == "[none]")
          {
            baseFile = QCString();
          }
          else
          {
            baseFile=url;
          }
        }
        else
        {
          baseFile+=QCString().sprintf("%d",m_userGroupCount++);
        }
      }
      // create new item and make it the new root
      m_rootNav = new LayoutNavEntry(m_rootNav,kind,isVisible,baseFile,title,intro);
    }
References LayoutNavEntry::Classes, LayoutNavEntry::ClassHierarchy, LayoutNavEntry::ClassIndex, LayoutNavEntry::ClassList, LayoutNavEntry::ClassMembers, LayoutNavEntry::Concepts, Config_getBool, elemIsVisible(), LayoutNavEntry::Examples, LayoutNavEntry::ExceptionHierarchy, LayoutNavEntry::ExceptionIndex, LayoutNavEntry::ExceptionList, LayoutNavEntry::Exceptions, FALSE, LayoutNavEntry::FileGlobals, LayoutNavEntry::FileList, XMLLocator::fileName(), LayoutNavEntry::Files, LayoutDocManager::instance(), LayoutNavEntry::InterfaceHierarchy, LayoutNavEntry::InterfaceIndex, LayoutNavEntry::InterfaceList, LayoutNavEntry::Interfaces, QCString::isEmpty(), XMLLocator::lineNr(), m_invalidEntry, m_locator, m_rootNav, m_userGroupCount, LayoutNavEntry::MainPage, LayoutNavEntry::Modules, LayoutNavEntry::NamespaceList, LayoutNavEntry::NamespaceMembers, LayoutNavEntry::Namespaces, LayoutNavEntry::Pages, parentIsVisible(), qPrint(), QCString::sprintf(), string, LayoutNavEntry::StructIndex, LayoutNavEntry::StructList, LayoutNavEntry::Structs, theTranslator, Translator::trClasses(), Translator::trClassHierarchy(), Translator::trClassHierarchyDescription(), Translator::trCompoundIndex(), Translator::trCompoundIndexFortran(), Translator::trCompoundList(), Translator::trCompoundListDescription(), Translator::trCompoundListDescriptionFortran(), Translator::trCompoundListFortran(), Translator::trCompoundMembers(), Translator::trCompoundMembersDescription(), Translator::trCompoundMembersDescriptionFortran(), Translator::trCompoundMembersFortran(), Translator::trConcept(), Translator::trConceptList(), Translator::trConceptListDescription(), Translator::trDataTypes(), Translator::trDesignUnitHierarchy(), Translator::trDesignUnitIndex(), Translator::trDesignUnitList(), Translator::trDesignUnitListDescription(), Translator::trDesignUnitMembers(), Translator::trDesignUnits(), Translator::trExamples(), Translator::trExamplesDescription(), Translator::trExceptionHierarchy(), Translator::trExceptionHierarchyDescription(), Translator::trExceptionIndex(), Translator::trExceptionList(), Translator::trExceptionListDescription(), Translator::trExceptions(), Translator::trFile(), Translator::trFileList(), Translator::trFileListDescription(), Translator::trFileMembers(), Translator::trFileMembersDescription(), Translator::trInterfaceHierarchy(), Translator::trInterfaceHierarchyDescription(), Translator::trInterfaceIndex(), Translator::trInterfaceList(), Translator::trInterfaceListDescription(), Translator::trMainPage(), Translator::trModules(), Translator::trModulesDescription(), Translator::trModulesList(), Translator::trModulesListDescription(), Translator::trModulesMemberDescription(), Translator::trModulesMembers(), Translator::trNamespaceList(), Translator::trNamespaceListDescription(), Translator::trNamespaceMemberDescription(), Translator::trNamespaceMembers(), Translator::trNamespaces(), Translator::trPackageList(), Translator::trPackageListDescription(), Translator::trPackageMembers(), Translator::trPackages(), Translator::trRelatedPages(), Translator::trRelatedPagesDescription(), Translator::trSliceInterfaces(), Translator::trStructIndex(), Translator::trStructList(), Translator::trStructListDescription(), Translator::trStructs(), TRUE, setup::url, LayoutNavEntry::User, LayoutNavEntry::UserGroup, XMLHandlers::value(), and warn().
startNavIndex() [1/2]
void LayoutParser::startNavIndex (const XMLHandlers::Attributes &) [inline]
Definition at line 254 of file layout.cpp.
    {
      m_scope="navindex/";
      m_rootNav = LayoutDocManager::instance().rootNavEntry();
      if (m_rootNav)
      {
        m_rootNav->clear();
      }
    }
References LayoutNavEntry::clear(), LayoutDocManager::instance(), m_rootNav, m_scope, and LayoutDocManager::rootNavEntry().
startNavIndex() [2/2]
void LayoutParser::startNavIndex (const XMLHandlers::Attributes &) [inline]
Definition at line 254 of file layout.cpp.
    {
      m_scope="navindex/";
      m_rootNav = LayoutDocManager::instance().rootNavEntry();
      if (m_rootNav)
      {
        m_rootNav->clear();
      }
    }
References LayoutNavEntry::clear(), LayoutDocManager::instance(), m_rootNav, m_scope, and LayoutDocManager::rootNavEntry().
startSectionEntry() [1/2]
void LayoutParser::startSectionEntry (LayoutDocEntry::Kind k, const XMLHandlers::Attributes & attrib, const QCString & title) [inline]
Definition at line 206 of file layout.cpp.
    {
      bool isVisible = elemIsVisible(attrib) && parentIsVisible(m_rootNav);
      QCString userTitle = XMLHandlers::value(attrib,"title");
      //printf("startSectionEntry: title='%s' userTitle='%s'\n",
      // qPrint(title),qPrint(userTitle));
      if (userTitle.isEmpty()) userTitle = title;
      if (m_part!=LayoutDocManager::Undefined && isVisible)
      {
        LayoutDocManager::instance().addEntry(m_part,new LayoutDocEntrySection(k,userTitle));
      }
    }
References LayoutDocManager::addEntry(), elemIsVisible(), LayoutDocManager::instance(), QCString::isEmpty(), m_part, m_rootNav, parentIsVisible(), LayoutDocManager::Undefined, and XMLHandlers::value().
startSectionEntry() [2/2]
void LayoutParser::startSectionEntry (LayoutDocEntry::Kind k, const XMLHandlers::Attributes & attrib, const QCString & title) [inline]
Definition at line 206 of file layout.cpp.
    {
      bool isVisible = elemIsVisible(attrib) && parentIsVisible(m_rootNav);
      QCString userTitle = XMLHandlers::value(attrib,"title");
      //printf("startSectionEntry: title='%s' userTitle='%s'\n",
      // qPrint(title),qPrint(userTitle));
      if (userTitle.isEmpty()) userTitle = title;
      if (m_part!=LayoutDocManager::Undefined && isVisible)
      {
        LayoutDocManager::instance().addEntry(m_part,new LayoutDocEntrySection(k,userTitle));
      }
    }
References LayoutDocManager::addEntry(), elemIsVisible(), LayoutDocManager::instance(), QCString::isEmpty(), m_part, m_rootNav, parentIsVisible(), LayoutDocManager::Undefined, and XMLHandlers::value().
startSimpleEntry() [1/2]
void LayoutParser::startSimpleEntry (LayoutDocEntry::Kind k, const XMLHandlers::Attributes & attrib) [inline]
Definition at line 195 of file layout.cpp.
    {
      bool isVisible = elemIsVisible(attrib) && parentIsVisible(m_rootNav);
      if (m_part!=LayoutDocManager::Undefined && isVisible)
      {
        LayoutDocManager::instance().addEntry(m_part,new LayoutDocEntrySimple(k));
      }
    }
References LayoutDocManager::addEntry(), elemIsVisible(), LayoutDocManager::instance(), m_part, m_rootNav, parentIsVisible(), and LayoutDocManager::Undefined.
startSimpleEntry() [2/2]
void LayoutParser::startSimpleEntry (LayoutDocEntry::Kind k, const XMLHandlers::Attributes & attrib) [inline]
Definition at line 195 of file layout.cpp.
    {
      bool isVisible = elemIsVisible(attrib) && parentIsVisible(m_rootNav);
      if (m_part!=LayoutDocManager::Undefined && isVisible)
      {
        LayoutDocManager::instance().addEntry(m_part,new LayoutDocEntrySimple(k));
      }
    }
References LayoutDocManager::addEntry(), elemIsVisible(), LayoutDocManager::instance(), m_part, m_rootNav, parentIsVisible(), and LayoutDocManager::Undefined.
Member Data Documentation
m_invalidEntry
bool LayoutParser::m_invalidEntry = false [private]
Definition at line 711 of file layout.cpp.
Referenced by endNavEntry(), and startNavEntry().
m_locator
const XMLLocator * LayoutParser::m_locator = nullptr [private]
Definition at line 713 of file layout.cpp.
Referenced by setDocumentLocator(), startElement(), and startNavEntry().
m_part
LayoutDocManager::LayoutPart LayoutParser::m_part = LayoutDocManager::Undefined [private]
Definition at line 709 of file layout.cpp.
Referenced by endClass(), endConcept(), endDirectory(), endFile(), endGroup(), endMemberDecl(), endMemberDef(), endNamespace(), startClass(), startConcept(), startDirectory(), startFile(), startGroup(), startMemberDecl(), startMemberDeclEntry(), startMemberDef(), startMemberDefEntry(), startNamespace(), startSectionEntry(), and startSimpleEntry().
m_rootNav
LayoutNavEntry * LayoutParser::m_rootNav = 0 [private]
Definition at line 710 of file layout.cpp.
Referenced by endNavEntry(), endNavIndex(), startNavEntry(), startNavIndex(), startSectionEntry(), startSimpleEntry(), and ~LayoutParser().
m_scope
QCString LayoutParser::m_scope [private]
Definition at line 708 of file layout.cpp.
Referenced by endClass(), endConcept(), endDirectory(), endElement(), endFile(), endGroup(), endMemberDecl(), endMemberDef(), endNamespace(), endNavIndex(), startClass(), startConcept(), startDirectory(), startElement(), startFile(), startGroup(), startMemberDecl(), startMemberDef(), startNamespace(), and startNavIndex().
m_userGroupCount
int LayoutParser::m_userGroupCount =0 [static], [private]
Definition at line 712 of file layout.cpp.
Referenced by startNavEntry().
The documentation for this class was generated from the following files:
doxygen/build/doxygen/src/layout.cpp
doxygen/src/layout.cpp