doxygen/build/doxygen/src/main.cpp File Reference
main entry point for doxygen
#include `doxygen.h`
Functions
int main (int argc, char **argv)
Detailed Description
main entry point for doxygen
This file contains main()
Definition in file main.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Default main. The idea of separating this from the rest of doxygen, is to make it possible to write your own main, with a different generateOutput() function for instance.
Definition at line 31 of file main.cpp.
{
  initDoxygen();
  readConfiguration(argc,argv);
  checkConfiguration();
  adjustConfiguration();
  parseInput();
  generateOutput();
  return 0;
}
References adjustConfiguration(), checkConfiguration(), generateOutput(), initDoxygen(), parseInput(), and readConfiguration().