doxygen/build/doxygen/build/generated_src/doxyversion.cpp File Reference
#include `version.h`
Functions
const char * getDoxygenVersion (void)
Function Documentation
getDoxygenVersion()
const char * getDoxygenVersion (void)
Definition at line 3 of file doxyversion.cpp.
{
  static char versionString[] = "1.9.6";
  return versionString;
}
Referenced by MainWindow::about(), ResourceMgr::copyResourceAs(), RTFGenerator::endIndexSection(), generateXML(), getFullVersion(), HtmlGenerator::startFile(), substituteKeywords(), DoxygenContext::Private::version(), Expert::writeConfig(), writeDefaultLayoutFile(), writeDefaultStyleSheet(), RTFGenerator::writeExtensionsFile(), HtmlGenerator::writeExternalSearchPage(), HtmlGenerator::writeFooterFile(), LatexGenerator::writeFooterFile(), LatexGenerator::writeHeaderFile(), HtmlGenerator::writeHeaderFile(), HtmlGenerator::writeLogoAsString(), HtmlGenerator::writeSearchData(), HtmlGenerator::writeSearchPage(), LatexGenerator::writeStyleSheetFile(), RTFGenerator::writeStyleSheetFile(), writeTagFile(), ConfigImpl::writeTemplate(), ConfigImpl::writeXMLDoxyfile(), and writeXMLHeader().