Arc handling functions
Functions
void MscResetArcIterator (Msc m)
Boolean MscNextArc (struct MscTag *m)
const char * MscGetCurrentArcSource (Msc m)
const char * MscGetCurrentArcDest (Msc m)
MscArcType MscGetCurrentArcType (struct MscTag *m)
const char * MscGetCurrentArcAttrib (Msc m, MscAttribType a)
unsigned int MscGetCurrentArcInputLine (Msc m)
Detailed Description
Function Documentation
MscGetCurrentArcAttrib()
const char * MscGetCurrentArcAttrib (Msc m, MscAttribType a)
Get the value of some attribute for the current arc.
Return values
The attribute string, or NULL if unset.
MscGetCurrentArcDest()
const char * MscGetCurrentArcDest (Msc m)
Get the name of the entity at which the current arc terminates.
Return values
The label for the entity at which the current arc stops. The returned string must not be modified.
MscGetCurrentArcInputLine()
unsigned int MscGetCurrentArcInputLine (Msc m)
Get the line of the input file at which the current arc was defined.
Return values
The line number of the input file.
MscGetCurrentArcSource()
const char * MscGetCurrentArcSource (Msc m)
Get the name of the entity from which the current arc originates.
Return values
The label for the entity from which the current arc starts. The returned string must not be modified.
MscGetCurrentArcType()
MscArcType MscGetCurrentArcType (struct MscTag * m)
Get the type for some arc.
Definition at line 715 of file mscgen_msc.c.
{
    return m->nextArc ? m->nextArc->type : MSC_INVALID_ARC_TYPE;
}
References MSC_INVALID_ARC_TYPE, MscTag::nextArc, and MscArcTag::type.
Referenced by checkMsc(), computeCanvasSize(), and mscgen_generate().
MscNextArc()
Boolean MscNextArc (struct MscTag * m)
Move to the next arc in the MSC.
Return values
TRUE if there is another arc, otherwise FALSE if the end of the list has been reached.
Definition at line 692 of file mscgen_msc.c.
{
    if(m->nextArc->next != NULL)
    {
        m->nextArc = m->nextArc->next;
        return TRUE;
    }
    else
    {
        return FALSE;
    }
}
References FALSE, MscArcTag::next, MscTag::nextArc, and TRUE.
Referenced by checkMsc(), computeCanvasSize(), and mscgen_generate().
MscResetArcIterator()
void MscResetArcIterator (Msc m)
Reset the arc iterator. This moves the pointer to the current arc to the head of the list.