Entity handling functions
Functions
void MscResetEntityIterator (Msc m)
Boolean MscNextEntity (struct MscTag *m)
const char * MscGetCurrentEntAttrib (Msc m, MscAttribType a)
const char * MscGetEntAttrib (Msc m, unsigned int entIdx, MscAttribType a)
Detailed Description
Function Documentation
MscGetCurrentEntAttrib()
const char * MscGetCurrentEntAttrib (Msc m, MscAttribType a)
Get the value of some attribute for the current entity.
Return values
The attribute string, or NULL if unset.
MscGetEntAttrib()
const char * MscGetEntAttrib (Msc m, unsigned int entIdx, MscAttribType a)
Get an attribute associated with some entity.
Parameters
 in entIdx The index of the entity.
Return values
The attribute string, or NULL if unset.
Definition at line 651 of file mscgen_msc.c.
{
    struct MscEntityTag *entity;
    const char *r;
    /* Find the entity */
    entity = m->entityList->head;
    while(entIdx > 0 && entity != NULL)
    {
        entity = entity->next;
        entIdx--;
    }
    /* Search the attribute list if the entity was found */
    if(entity)
    {
        r = findAttrib(entity->attr, a);
        /* If the entity label was sought but not found, return entity name */
        if(r == NULL && a == MSC_ATTR_LABEL)
        {
            return m->nextEntity->label;
        }
        else
        {
            return r;
        }
    }
    else
    {
        /* Entity was not found */
        return NULL;
    }
}
References a, MscEntityTag::attr, MscTag::entityList, findAttrib(), MscEntityListTag::head, MscEntityTag::label, MSC_ATTR_LABEL, MscEntityTag::next, MscTag::nextEntity, and r.
Referenced by mscgen_generate().
MscNextEntity()
Boolean MscNextEntity (struct MscTag * m)
Move to the next entity in the MSC.
Return values
TRUE if there is another entity, otherwise FALSE if the end of the list has been reached.
Definition at line 614 of file mscgen_msc.c.
{
    if(m->nextEntity->next != NULL)
    {
        m->nextEntity = m->nextEntity->next;
        return TRUE;
    }
    else
    {
        return FALSE;
    }
}
References FALSE, MscEntityTag::next, MscTag::nextEntity, and TRUE.
Referenced by mscgen_generate().
MscResetEntityIterator()
void MscResetEntityIterator (Msc m)
Reset the entity iterator. This moves the pointer to the current entity to the head of the list.