doxygen/libmscgen/mscgen_ps_out.c File Reference
#include `mscgen_config.h`
#include <stdio.h>
#include <errno.h>
#include <stdlib.h>
#include <assert.h>
#include <string.h>
#include `mscgen_adraw_int.h`
#include `mscgen_utf8.h`
#include `mscgen_safe.h`
Classes
struct PsContextTag
struct PsCharMetric
Macros
#define PS_OUT_SCALE 0.7f
Typedefs
typedef struct PsContextTag PsContext
Functions
static PsContext * getPsCtx (struct ADrawTag *ctx)
static FILE * getPsFile (struct ADrawTag *ctx)
static int getSpace (struct ADrawTag *ctx, long thousanths)
static void writeEscaped (struct ADrawTag *ctx, const char *string)
static void setColour (struct ADrawTag *ctx, ADrawColour col)
unsigned int PsTextWidth (struct ADrawTag *ctx, const char *string)
int PsTextHeight (struct ADrawTag *ctx)
void PsLine (struct ADrawTag *ctx, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2)
void PsDottedLine (struct ADrawTag *ctx, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2)
void PsFilledRectangle (struct ADrawTag *ctx, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2)
void PsTextR (struct ADrawTag *ctx, unsigned int x, unsigned int y, const char *string)
void PsTextL (struct ADrawTag *ctx, unsigned int x, unsigned int y, const char *string)
void PsTextC (struct ADrawTag *ctx, unsigned int x, unsigned int y, const char *string)
void PsFilledTriangle (struct ADrawTag *ctx, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2, unsigned int x3, unsigned int y3)
void PsFilledCircle (struct ADrawTag *ctx, unsigned int x, unsigned int y, unsigned int r)
void PsArc (struct ADrawTag *ctx, unsigned int cx, unsigned int cy, unsigned int w, unsigned int h, unsigned int s, unsigned int e)
void PsDottedArc (struct ADrawTag *ctx, unsigned int cx, unsigned int cy, unsigned int w, unsigned int h, unsigned int s, unsigned int e)
void PsSetPen (struct ADrawTag *ctx, ADrawColour col)
void PsSetBgPen (struct ADrawTag *ctx, ADrawColour col)
void PsSetFontSize (struct ADrawTag *ctx, ADrawFontSize size)
Boolean PsClose (struct ADrawTag *ctx)
Boolean PsInit (unsigned int w, unsigned int h, const char *file, struct ADrawTag *outContext)
Variables
static const PsCharMetric PsHelvetica
Macro Definition Documentation
PS_OUT_SCALE
#define PS_OUT_SCALE 0.7f
Overall scaling of the Postscript output.
Definition at line 39 of file mscgen_ps_out.c.
Typedef Documentation
PsContext
typedef struct PsContextTag PsContext
Function Documentation
getPsCtx()
static PsContext * getPsCtx (struct ADrawTag * ctx) [static]
Get the context pointer from an ADraw structure.
Definition at line 118 of file mscgen_ps_out.c.
{
    return (PsContext *)ctx->internal;
}
References ADrawTag::internal.
Referenced by getPsFile(), getSpace(), PsClose(), PsSetBgPen(), PsSetFontSize(), PsSetPen(), PsTextC(), PsTextL(), and PsTextR().
getPsFile()
static FILE * getPsFile (struct ADrawTag * ctx) [static]
Get the context pointer from an ADraw structure.
Definition at line 125 of file mscgen_ps_out.c.
{
    return getPsCtx(ctx)->of;
}
References getPsCtx(), and PsContextTag::of.
Referenced by PsArc(), PsDottedArc(), PsDottedLine(), PsFilledCircle(), PsFilledRectangle(), PsFilledTriangle(), PsLine(), PsTextC(), PsTextL(), PsTextR(), setColour(), and writeEscaped().
getSpace()
static int getSpace (struct ADrawTag * ctx, long thousanths) [static]
Given a font metric measurement, return device dependent units. Font metric data is stored as 1/1000th of a point, and therefore needs to be multiplied by the font point size and divided by 1000 to give a value in device dependent units.
Definition at line 135 of file mscgen_ps_out.c.
{
    return ((thousanths * getPsCtx(ctx)->fontPoints) + 500) / 1000;
}
References getPsCtx().
Referenced by PsTextC(), PsTextHeight(), PsTextL(), PsTextR(), and PsTextWidth().
PsArc()
void PsArc (struct ADrawTag * ctx, unsigned int cx, unsigned int cy, unsigned int w, unsigned int h, unsigned int s, unsigned int e)
Definition at line 393 of file mscgen_ps_out.c.
{
    fprintf(getPsFile(ctx),
            "newpath "
            "%d %d %d %d %d %d ellipse "
            "stroke\n",
            cx, 0-cy, w, h, s, e);
}
References cx, cy, e, getPsFile(), h, s, and w.
PsClose()
Boolean PsClose (struct ADrawTag * ctx)
Definition at line 475 of file mscgen_ps_out.c.
{
    PsContext *context = getPsCtx(ctx);
    /* Close the output file */
    if(context->of != stdout)
    {
        fclose(context->of);
    }
    /* Free and destroy context */
    free(context);
    ctx->internal = NULL;
    return TRUE;
}
References Portable::fclose(), getPsCtx(), ADrawTag::internal, PsContextTag::of, and TRUE.
PsDottedArc()
void PsDottedArc (struct ADrawTag * ctx, unsigned int cx, unsigned int cy, unsigned int w, unsigned int h, unsigned int s, unsigned int e)
Definition at line 409 of file mscgen_ps_out.c.
{
    fprintf(getPsFile(ctx), "[2] 0 setdash\n");
    PsArc(ctx, cx, cy, w, h, s, e);
    fprintf(getPsFile(ctx), "[] 0 setdash\n");
}
References cx, cy, e, getPsFile(), h, PsArc(), s, and w.
PsDottedLine()
void PsDottedLine (struct ADrawTag * ctx, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2)
Definition at line 233 of file mscgen_ps_out.c.
{
    fprintf(getPsFile(ctx), "[2] 0 setdash\n");
    PsLine(ctx, x1, y1, x2, y2);
    fprintf(getPsFile(ctx), "[] 0 setdash\n");
}
References getPsFile(), PsLine(), x1, x2, y1, and y2.
PsFilledCircle()
void PsFilledCircle (struct ADrawTag * ctx, unsigned int x, unsigned int y, unsigned int r)
Definition at line 379 of file mscgen_ps_out.c.
{
    fprintf(getPsFile(ctx),
            "newpath "
            "%d %d %d 0 360 arc "
            "closepath "
            "fill\n",
            x, 0-y, r);
}
References getPsFile(), r, x, and y.
PsFilledRectangle()
void PsFilledRectangle (struct ADrawTag * ctx, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2)
Definition at line 245 of file mscgen_ps_out.c.
{
    fprintf(getPsFile(ctx),
            "newpath "
            "%d %d moveto "
            "%d %d lineto "
            "%d %d lineto "
            "%d %d lineto "
            "closepath "
            "fill\n",
            x1, 0-y1,
            x2, 0-y1,
            x2, 0-y2,
            x1, 0-y2);
}
References getPsFile(), x1, x2, y1, and y2.
PsFilledTriangle()
void PsFilledTriangle (struct ADrawTag * ctx, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2, unsigned int x3, unsigned int y3)
Definition at line 358 of file mscgen_ps_out.c.
{
    fprintf(getPsFile(ctx),
            "newpath "
            "%d %d moveto "
            "%d %d lineto "
            "%d %d lineto "
            "closepath "
            "fill\n",
            x1, 0-y1,
            x2, 0-y2,
            x3, 0-y3);
}
References getPsFile(), x1, x2, y1, and y2.
PsInit()
Boolean PsInit (unsigned int w, unsigned int h, const char * file, struct ADrawTag * outContext)
Definition at line 494 of file mscgen_ps_out.c.
{
    PsContext *context;
    /* Create context */
    context = outContext->internal = malloc_s(sizeof(PsContext));
    if(context == NULL)
    {
        return FALSE;
    }
    /* Open the output file */
    if(strcmp(file, "-") == 0)
    {
        context->of = stdout;
    }
    else
    {
        context->of = fopen(file, "wb");
        if(!context->of)
        {
            fprintf(stderr, "PsInit: Failed to open output file '%s': %s\n", file, strerror(errno));
            return FALSE;
        }
    }
    /* Write the header */
    fprintf(context->of, "%%!PS-Adobe-3.0 EPSF-2.0\n"
                         "%%%%BoundingBox: 0 0 %.0f %.0f\n", w * PS_OUT_SCALE, h * PS_OUT_SCALE);
    fprintf(context->of, "%%%%Creator: mscgen %s\n", PACKAGE_VERSION);
    fprintf(context->of, "%%%%EndComments\n");
    /* Shrink everything by 70% */
    fprintf(context->of, "%f %f scale\n", PS_OUT_SCALE, PS_OUT_SCALE);
    /* Create clipping rectangle to constrain dimensions */
    fprintf(context->of, "0 0 moveto\n");
    fprintf(context->of, "0 %u lineto\n", h);
    fprintf(context->of, "%u %u lineto\n", w, h);
    fprintf(context->of, "%u 0 lineto\n", w);
    fprintf(context->of, "closepath\n");
    fprintf(context->of, "clip\n");
    fprintf(context->of, "%%PageTrailer\n");
    fprintf(context->of, "%%Page: 1 1\n");
    /* Set default font */
    fprintf(context->of, "/Helvetica findfont\n");
    fprintf(context->of, "10 scalefont\n");
    fprintf(context->of, "setfont\n");
    /* Get the default font size */
    PsSetFontSize(outContext, ADRAW_FONT_SMALL);
    /* Translate up by the height, y-axis will be inverted */
    fprintf(context->of, "0 %d translate\n", h);
    /* Arc drawing function */
    fprintf(context->of, "/mtrx matrix def\n"
                         "/ellipse\n"
                         " { /endangle exch def\n"
                         " /startangle exch def\n"
                         " /ydia exch def\n"
                         " /xdia exch def\n"
                         " /y exch def\n"
                         " /x exch def\n"
                         " /savematrix mtrx currentmatrix def\n"
                         " x y translate\n"
                         " xdia 2 div ydia 2 div scale\n"
                         " 1 -1 scale\n"
                         " 0 0 1 startangle endangle arc\n"
                         " savematrix setmatrix\n"
                         "} def\n");
    /* Set the current pen colours */
    context->penColour = ADRAW_COL_BLACK;
    context->penBgColour = ADRAW_COL_WHITE;
    /* Now fill in the function pointers */
    outContext->line = PsLine;
    outContext->dottedLine = PsDottedLine;
    outContext->textL = PsTextL;
    outContext->textC = PsTextC;
    outContext->textR = PsTextR;
    outContext->textWidth = PsTextWidth;
    outContext->textHeight = PsTextHeight;
    outContext->filledRectangle = PsFilledRectangle;
    outContext->filledTriangle = PsFilledTriangle;
    outContext->filledCircle = PsFilledCircle;
    outContext->arc = PsArc;
    outContext->dottedArc = PsDottedArc;
    outContext->setPen = PsSetPen;
    outContext->setBgPen = PsSetBgPen;
    outContext->setFontSize = PsSetFontSize;
    outContext->close = PsClose;
    return TRUE;
}
References ADRAW_COL_BLACK, ADRAW_COL_WHITE, ADRAW_FONT_SMALL, ADrawTag::arc, ADrawTag::close, ADrawTag::dottedArc, ADrawTag::dottedLine, errno, FALSE, caseconvert::file, ADrawTag::filledCircle, ADrawTag::filledRectangle, ADrawTag::filledTriangle, Portable::fopen(), h, ADrawTag::internal, ADrawTag::line, malloc_s(), PsContextTag::of, PACKAGE_VERSION, PsContextTag::penBgColour, PsContextTag::penColour, PS_OUT_SCALE, PsArc(), PsClose(), PsDottedArc(), PsDottedLine(), PsFilledCircle(), PsFilledRectangle(), PsFilledTriangle(), PsLine(), PsSetBgPen(), PsSetFontSize(), PsSetPen(), PsTextC(), PsTextHeight(), PsTextL(), PsTextR(), PsTextWidth(), ADrawTag::setBgPen, ADrawTag::setFontSize, ADrawTag::setPen, strcmp(), ADrawTag::textC, ADrawTag::textHeight, ADrawTag::textL, ADrawTag::textR, ADrawTag::textWidth, TRUE, and w.
Referenced by ADrawOpen().
PsLine()
void PsLine (struct ADrawTag * ctx, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2)
Definition at line 220 of file mscgen_ps_out.c.
{
    fprintf(getPsFile(ctx),
            "newpath %d %d moveto %d %d lineto stroke\n",
            x1, 0-y1, x2, 0-y2);
}
References getPsFile(), x1, x2, y1, and y2.
PsSetBgPen()
void PsSetBgPen (struct ADrawTag * ctx, ADrawColour col)
Definition at line 441 of file mscgen_ps_out.c.
{
    PsContext *context = getPsCtx(ctx);
    context->penBgColour = col;
}
References getPsCtx(), and PsContextTag::penBgColour.
PsSetFontSize()
void PsSetFontSize (struct ADrawTag * ctx, ADrawFontSize size)
Definition at line 450 of file mscgen_ps_out.c.
{
    PsContext *context = getPsCtx(ctx);
    switch(size)
    {
        case ADRAW_FONT_TINY:
            getPsCtx(ctx)->fontPoints = 8;
            break;
        case ADRAW_FONT_SMALL:
            getPsCtx(ctx)->fontPoints = 12;
            break;
        default:
            assert(0);
    }
    fprintf(context->of, "/Helvetica findfont\n");
    fprintf(context->of, "%d scalefont\n", getPsCtx(ctx)->fontPoints);
    fprintf(context->of, "setfont\n");
}
References ADRAW_FONT_SMALL, ADRAW_FONT_TINY, PsContextTag::fontPoints, getPsCtx(), PsContextTag::of, and size.
PsSetPen()
void PsSetPen (struct ADrawTag * ctx, ADrawColour col)
Definition at line 423 of file mscgen_ps_out.c.
{
    PsContext *context = getPsCtx(ctx);
    assert(col != ADRAW_COL_INVALID);
    /* Check if the pen colour has changed */
    if(context->penColour != col)
    {
        setColour(ctx, col);
        /* Store the pen colour */
        context->penColour = col;
    }
}
References ADRAW_COL_INVALID, getPsCtx(), PsContextTag::penColour, and setColour().
PsTextC()
void PsTextC (struct ADrawTag * ctx, unsigned int x, unsigned int y, const char * string)
Definition at line 325 of file mscgen_ps_out.c.
{
    PsContext *context = getPsCtx(ctx);
    /* Push the string and get its width */
    fprintf(getPsFile(ctx), "(");
    writeEscaped(ctx, string);
    fprintf(getPsFile(ctx), ") dup stringwidth\n");
    /* Draw the background box */
    setColour(ctx, context->penBgColour);
    fprintf(getPsFile(ctx), "pop " /* Ignore y-value */
                            "dup dup " /* Duplicate string width twice */
                            "newpath "
                            "%d %d moveto " /* Starting point, centre bottom of box */
                            "2 div neg 0 rmoveto " /* Move to bottom left */
                            "0 rlineto " /* Move to bottom right of the box */
                            "0 %d rlineto " /* To top right */
                            "neg 0 rlineto " /* Back to bottom left */
                            "closepath fill\n", /* Done */
                            x, 0-y,
                            getSpace(ctx, PsHelvetica.ascender));
    /* Restore pen and show the string */
    setColour(ctx, context->penColour);
    fprintf(getPsFile(ctx), "%d %d moveto dup stringwidth pop 2 div neg 0 rmoveto show\n",
                             x, 0-y - getSpace(ctx, PsHelvetica.descender));
}
References PsCharMetric::ascender, PsCharMetric::descender, getPsCtx(), getPsFile(), getSpace(), PsContextTag::penBgColour, PsContextTag::penColour, PsHelvetica, setColour(), writeEscaped(), x, and y.
PsTextHeight()
int PsTextHeight (struct ADrawTag * ctx)
Definition at line 214 of file mscgen_ps_out.c.
{
    return getSpace(ctx, PsHelvetica.ascender - PsHelvetica.descender);
}
References PsCharMetric::ascender, PsCharMetric::descender, getSpace(), and PsHelvetica.
PsTextL()
void PsTextL (struct ADrawTag * ctx, unsigned int x, unsigned int y, const char * string)
Definition at line 298 of file mscgen_ps_out.c.
{
    PsContext *context = getPsCtx(ctx);
    /* Draw the background box */
    setColour(ctx, context->penBgColour);
    PsFilledRectangle(ctx, x, 0-y, x + 10, 0-y + 10);
    setColour(ctx, context->penColour);
    fprintf(getPsFile(ctx),
            "%d %d moveto "
            "(",
            x, 0-y - getSpace(ctx, PsHelvetica.descender));
    writeEscaped(ctx, string);
    fprintf(getPsFile(ctx),
            ") dup stringwidth "
            "pop " /* Ignore y value */
            "neg " /* Invert x value */
            "0 "
            "rmoveto "
            "show\n");
}
References PsCharMetric::descender, getPsCtx(), getPsFile(), getSpace(), PsContextTag::penBgColour, PsContextTag::penColour, PsFilledRectangle(), PsHelvetica, setColour(), writeEscaped(), x, and y.
PsTextR()
void PsTextR (struct ADrawTag * ctx, unsigned int x, unsigned int y, const char * string)
Definition at line 266 of file mscgen_ps_out.c.
{
    PsContext *context = getPsCtx(ctx);
    /* Push the string and get its width */
    fprintf(getPsFile(ctx), "(");
    writeEscaped(ctx, string);
    fprintf(getPsFile(ctx), ") dup stringwidth\n");
    /* Draw the background box */
    setColour(ctx, context->penBgColour);
    fprintf(getPsFile(ctx), "pop " /* Ignore y-value */
                            "dup " /* Duplicate string width */
                            "newpath "
                            "%d %d moveto " /* Bottom left of the box */
                            "0 rlineto " /* Move to bottom right of the box */
                            "0 %d rlineto " /* To top right */
                            "neg 0 rlineto " /* Back to bottom left */
                            "closepath fill\n", /* Done */
                            x, 0-y - getSpace(ctx, PsHelvetica.descender),
                            getSpace(ctx, PsHelvetica.ascender));
    /* Restore pen and show the string */
    setColour(ctx, context->penColour);
    fprintf(getPsFile(ctx), "%d %d moveto show\n",
                             x, 0-y - getSpace(ctx, PsHelvetica.descender));
}
References PsCharMetric::ascender, PsCharMetric::descender, getPsCtx(), getPsFile(), getSpace(), PsContextTag::penBgColour, PsContextTag::penColour, PsHelvetica, setColour(), writeEscaped(), x, and y.
PsTextWidth()
unsigned int PsTextWidth (struct ADrawTag * ctx, const char * string)
Definition at line 194 of file mscgen_ps_out.c.
{
    unsigned long width = 0;
    while(*string != '\0')
    {
        int i = *string & 0xff;
        unsigned long w = PsHelvetica.widths[i];
        /* Ignore undefined characters */
        width += w > 0 ? w : 0;
        string++;
    }
    return getSpace(ctx, width);
}
References getSpace(), PsHelvetica, w, and PsCharMetric::widths.
setColour()
static void setColour (struct ADrawTag * ctx, ADrawColour col) [static]
Definition at line 171 of file mscgen_ps_out.c.
{
    float r, g, b;
    /* Extract RGB values */
    r = (float)((col & 0xff0000) >> 16);
    g = (float)((col & 0x00ff00) >> 8);
    b = (float)((col & 0x0000ff) >> 0);
    /* Normalise */
    r /= 255.0f;
    g /= 255.0f;
    b /= 255.0f;
    /* Generate output command */
    fprintf(getPsFile(ctx), "%f %f %f setrgbcolor\n", r ,g ,b);
}
References b, g, getPsFile(), and r.
Referenced by PsSetPen(), PsTextC(), PsTextL(), and PsTextR().
writeEscaped()
static void writeEscaped (struct ADrawTag * ctx, const char * string) [static]
Write out a line of text, escaping special characters.
Definition at line 142 of file mscgen_ps_out.c.
{
    FILE *f = getPsFile(ctx);
    while(*string != '\0')
    {
        unsigned int code, bytes;
        switch(*string)
        {
            case '(': fprintf(f, "\\("); break;
            case ')': fprintf(f, "\\)"); break;
            default:
                if(Utf8Decode(string, &code, &bytes))
                {
                    fprintf(f, "\\%o", code);
                    string += bytes - 1;
                }
                else
                {
                    fputc(*string, f);
                }
                break;
        }
        string++;
    }
}
References f, getPsFile(), and Utf8Decode().
Referenced by PsTextC(), PsTextL(), and PsTextR().
Variable Documentation
PsHelvetica
const PsCharMetric PsHelvetica [static]
Helvetica character widths. This gives the width of each character is 1/1000ths of a point. The values are taken from the Adobe Font Metric file for Hevletica.
Definition at line 72 of file mscgen_ps_out.c.
Referenced by PsTextC(), PsTextHeight(), PsTextL(), PsTextR(), and PsTextWidth().