doxygen/libmscgen/gd.c File Reference
#include <stdio.h>
#include <math.h>
#include <string.h>
#include <stdlib.h>
#include <stdarg.h>
#include `gd_intern.h`
#include `gd.h`
#include `gdhelpers.h`
#include `gd_color.h`
#include `gd_errors.h`
Classes
struct RGBType
struct HWBType
struct seg
Macros
#define gdImageBoundsSafeMacro(im, x, y) (!((((y) < (im)->cy1) || ((y) > (im)->cy2)) || (((x) < (im)->cx1) || ((x) > (im)->cx2))))
#define ASC(ch) ch
#define RETURN_HWB(h, w, b) {HWB->H = h; HWB->W = w; HWB->B = b; return HWB;}
#define RETURN_RGB(r, g, b) {RGB->R = r; RGB->G = g; RGB->B = b; return RGB;}
#define HWB_UNDEFINED -1
#define SETUP_RGB(s, r, g, b) {s.R = r/255.0f; s.G = g/255.0f; s.B = b/255.0f;}
#define MIN(a, b) ((a)<(b)?(a):(b))
#define MIN3(a, b, c) ((a)<(b)?(MIN(a,c)):(MIN(b,c)))
#define MAX(a, b) ((a)<(b)?(b):(a))
#define MAX3(a, b, c) ((a)<(b)?(MAX(b,c)):(MAX(a,c)))
#define REPLACING_LOOP(pixel)
#define REPLACING_LOOP(pixel)
#define REPLACING_LOOP(pixel)
#define FILL_MAX ((int)(im->sy*im->sx)/4)
#define FILL_PUSH(Y, XL, XR, DY)
#define FILL_POP(Y, XL, XR, DY) {sp--; Y = sp->y+(DY = sp->dy); XL = sp->xl; XR = sp->xr;}
#define floor2(exp) ((long) exp)
#define BLEND_COLOR(a, nc, c, cc) nc = (cc) + (((((c) - (cc)) * (a)) + ((((c) - (cc)) * (a)) >> 8) + 0x80) >> 8);
Functions
void gd_stderr_error (int priority, const char *format, va_list args)
static void _gd_error_ex (int priority, const char *format, va_list args)
void gd_error (const char *format,...)
void gd_error_ex (int priority, const char *format,...)
BGD_DECLARE (void)
static void gdImageBrushApply (gdImagePtr im, int x, int y)
static void gdImageTileApply (gdImagePtr im, int x, int y)
BGD_DECLARE (int)
BGD_DECLARE (gdImagePtr)
static HWBType * RGB_to_HWB (RGBType RGB, HWBType *HWB)
static float HWB_Diff (int r1, int g1, int b1, int r2, int g2, int b2)
static int colorCmp (const void *x, const void *y)
static int clip_1d (int *x0, int *y0, int *x1, int *y1, int mindim, int maxdim)
static void gdImageAALine (gdImagePtr im, int x1, int y1, int x2, int y2, int col)
static void _gdImageFilledHRectangle (gdImagePtr im, int x1, int y1, int x2, int y2, int color)
static void gdImageHLine (gdImagePtr im, int y, int x1, int x2, int col)
static void gdImageVLine (gdImagePtr im, int x, int y1, int y2, int col)
static void dashedSet (gdImagePtr im, int x, int y, int color, int *onP, int *dashStepP, int wid, int vert)
static int strlen16 (unsigned short *s)
long lsqrt (long n)
static int gdImageTileGet (gdImagePtr im, int x, int y)
static void _gdImageFillTiled (gdImagePtr im, int x, int y, int nc)
static void _gdImageFilledVRectangle (gdImagePtr im, int x1, int y1, int x2, int y2, int color)
static void gdImageSetAAPixelColor (gdImagePtr im, int x, int y, int color, int t)
static int gdAlphaOverlayColor (int src, int dst, int max)
Variables
const int gdCosT []
const int gdSinT []
static gdErrorMethod gd_error_method = gd_stderr_error
Macro Definition Documentation
ASC
#define ASC(ch) ch
Definition at line 31 of file gd.c.
BLEND_COLOR
#define BLEND_COLOR(a, nc, c, cc) nc = (cc) + (((((c) - (cc)) * (a)) + ((((c) - (cc)) * (a)) >> 8) + 0x80) >> 8);
Definition at line 4310 of file gd.c.
FILL_MAX
#define FILL_MAX ((int)(im->sy*im->sx)/4)
Definition at line 2406 of file gd.c.
FILL_POP
#define FILL_POP(Y, XL, XR, DY) {sp--; Y = sp->y+(DY = sp->dy); XL = sp->xl; XR = sp->xr;}
Definition at line 2411 of file gd.c.
FILL_PUSH
#define FILL_PUSH(Y, XL, XR, DY)
Value:
    if (sp<stack+FILL_MAX && Y+(DY)>=0 && Y+(DY)<wy2) \
    {sp->y = Y; sp->xl = XL; sp->xr = XR; sp->dy = DY; sp++;}
Definition at line 2407 of file gd.c.
floor2
#define floor2(exp) ((long) exp)
Definition at line 3429 of file gd.c.
gdImageBoundsSafeMacro
#define gdImageBoundsSafeMacro(im, x, y) (!((((y) < (im)->cy1) || ((y) > (im)->cy2)) || (((x) < (im)->cx1) || ((x) > (im)->cx2))))
Definition at line 22 of file gd.c.
HWB_UNDEFINED
#define HWB_UNDEFINED -1
Definition at line 503 of file gd.c.
MAX
#define MAX(a, b) ((a)<(b)?(b):(a))
Definition at line 508 of file gd.c.
MAX3
#define MAX3(a, b, c) ((a)<(b)?(MAX(b,c)):(MAX(a,c)))
Definition at line 509 of file gd.c.
MIN
#define MIN(a, b) ((a)<(b)?(a):(b))
Definition at line 506 of file gd.c.
MIN3
#define MIN3(a, b, c) ((a)<(b)?(MIN(a,c)):(MIN(b,c)))
Definition at line 507 of file gd.c.
REPLACING_LOOP [1/3]
#define REPLACING_LOOP(pixel)
Value:
        do { \
        for (y = im->cy1; y <= im->cy2; y++) { \
            for (x = im->cx1; x <= im->cx2; x++) { \
                if (pixel(im, x, y) == src) { \
                    gdImageSetPixel(im, x, y, dst); \
                    n++; \
                } \
            } \
        } \
    } while (0)
REPLACING_LOOP [2/3]
#define REPLACING_LOOP(pixel)
Value:
        do { \
        for (y = im->cy1; y <= im->cy2; y++) { \
            for (x = im->cx1; x <= im->cx2; x++) { \
                if (gdColorMatch(im, src, pixel(im, x, y), threshold)) { \
                    gdImageSetPixel(im, x, y, dst); \
                    n++; \
                } \
            } \
        } \
    } while (0)
REPLACING_LOOP [3/3]
#define REPLACING_LOOP(pixel)
Value:
        do { \
        for (y = im->cy1; y <= im->cy2; y++) { \
            for (x = im->cx1; x <= im->cx2; x++) { \
                c = pixel(im, x, y); \
                if ((d = (int *)bsearch(&c, base, len, sizeof(int)<<1, colorCmp))) { \
                    gdImageSetPixel(im, x, y, d[1]); \
                    n++; \
                } \
            } \
        } \
    } while (0)
RETURN_HWB
#define RETURN_HWB(h, w, b) {HWB->H = h; HWB->W = w; HWB->B = b; return HWB;}
Definition at line 501 of file gd.c.
RETURN_RGB
#define RETURN_RGB(r, g, b) {RGB->R = r; RGB->G = g; RGB->B = b; return RGB;}
Definition at line 502 of file gd.c.
SETUP_RGB
#define SETUP_RGB(s, r, g, b) {s.R = r/255.0f; s.G = g/255.0f; s.B = b/255.0f;}
Definition at line 504 of file gd.c.
Function Documentation
_gd_error_ex()
static void _gd_error_ex (int priority, const char * format, va_list args) [static]
Definition at line 103 of file gd.c.
{
    if (gd_error_method) {
        gd_error_method(priority, format, args);
    }
}
References gd_error_method.
Referenced by gd_error(), and gd_error_ex().
_gdImageFilledHRectangle()
static void _gdImageFilledHRectangle (gdImagePtr im, int x1, int y1, int x2, int y2, int color) [static]
Definition at line 2706 of file gd.c.
{
    int x, y;
    if (x1 == x2 && y1 == y2) {
        gdImageSetPixel(im, x1, y1, color);
        return;
    }
    if (x1 > x2) {
        x = x1;
        x1 = x2;
        x2 = x;
    }
    if (y1 > y2) {
        y = y1;
        y1 = y2;
        y2 = y;
    }
    if (x1 < 0) {
        x1 = 0;
    }
    if (x2 >= gdImageSX(im)) {
        x2 = gdImageSX(im) - 1;
    }
    if (y1 < 0) {
        y1 = 0;
    }
    if (y2 >= gdImageSY(im)) {
        y2 = gdImageSY(im) - 1;
    }
    for (x = x1; (x <= x2); x++) {
        for (y = y1; (y <= y2); y++) {
            gdImageSetPixel (im, x, y, color);
        }
    }
}
References color, gdImageSX, gdImageSY, x, x1, x2, y, y1, and y2.
Referenced by gdImageHLine().
_gdImageFilledVRectangle()
static void _gdImageFilledVRectangle (gdImagePtr im, int x1, int y1, int x2, int y2, int color) [static]
Definition at line 2751 of file gd.c.
{
    int x, y;
    if (x1 == x2 && y1 == y2) {
        gdImageSetPixel(im, x1, y1, color);
        return;
    }
    if (x1 > x2) {
        x = x1;
        x1 = x2;
        x2 = x;
    }
    if (y1 > y2) {
        y = y1;
        y1 = y2;
        y2 = y;
    }
    if (x1 < 0) {
        x1 = 0;
    }
    if (x2 >= gdImageSX(im)) {
        x2 = gdImageSX(im) - 1;
    }
    if (y1 < 0) {
        y1 = 0;
    }
    if (y2 >= gdImageSY(im)) {
        y2 = gdImageSY(im) - 1;
    }
    for (y = y1; (y <= y2); y++) {
        for (x = x1; (x <= x2); x++) {
            gdImageSetPixel (im, x, y, color);
        }
    }
}
References color, gdImageSX, gdImageSY, x, x1, x2, y, y1, and y2.
_gdImageFillTiled()
static void _gdImageFillTiled (gdImagePtr im, int x, int y, int nc) [static]
Definition at line 2527 of file gd.c.
{
    int l, x1, x2, dy;
    int oc; /* old pixel value */
    int wx2,wy2;
    /* stack of filled segments */
    struct seg *stack;
    struct seg *sp;
    char *pts;
    if (!im->tile) {
        return;
    }
    wx2=im->sx;
    wy2=im->sy;
    if(overflow2(im->sy, im->sx)) {
        return;
    }
    if(overflow2(sizeof(struct seg), ((im->sy * im->sx) / 4))) {
        return;
    }
    pts = (char *) gdCalloc(im->sy * im->sx, sizeof(char));
    if (!pts) {
        return;
    }
    stack = (struct seg *)gdMalloc(sizeof(struct seg) * ((int)(im->sy*im->sx)/4));
    if (!stack) {
        gdFree(pts);
        return;
    }
    sp = stack;
    oc = gdImageGetPixel(im, x, y);
    /* required! */
    FILL_PUSH(y,x,x,1);
    /* seed segment (popped 1st) */
    FILL_PUSH(y+1, x, x, -1);
    while (sp>stack) {
        FILL_POP(y, x1, x2, dy);
        for (x=x1; x>=0 && (!pts[y + x*wy2] && gdImageGetPixel(im,x,y)==oc); x--) {
            nc = gdImageTileGet(im,x,y);
            pts[y + x*wy2]=1;
            gdImageSetPixel(im,x, y, nc);
        }
        if (x>=x1) {
            goto skip;
        }
        l = x+1;
        /* leak on left? */
        if (l<x1) {
            FILL_PUSH(y, l, x1-1, -dy);
        }
        x = x1+1;
        do {
            for (; x<wx2 && (!pts[y + x*wy2] && gdImageGetPixel(im,x, y)==oc) ; x++) {
                if (pts[y + x*wy2]) {
                    /* we should never be here */
                    break;
                }
                nc = gdImageTileGet(im,x,y);
                pts[y + x*wy2]=1;
                gdImageSetPixel(im, x, y, nc);
            }
            FILL_PUSH(y, l, x-1, dy);
            /* leak on right? */
            if (x>x2+1) {
                FILL_PUSH(y, x2+1, x-1, -dy);
            }
skip:
            for (x++; x<=x2 && (pts[y + x*wy2] || gdImageGetPixel(im,x, y)!=oc); x++);
            l = x;
        } while (x<=x2);
    }
    gdFree(pts);
    gdFree(stack);
}
References seg::dy, FILL_POP, FILL_PUSH, gdCalloc(), gdImageTileGet(), gdMalloc(), overflow2(), gdImageStruct::sx, gdImageStruct::sy, gdImageStruct::tile, x, x1, x2, and y.
BGD_DECLARE() [1/3]
BGD_DECLARE (gdImagePtr)
Group: Cloning and Copying Function: gdImageClone
Clones an image
Creates an exact duplicate of the given image.
Parameters: src - The source image.
Returns: The cloned image on success, NULL on failure.
Definition at line 291 of file gd.c.
{
    int i;
    gdImagePtr im;
    if (overflow2(sx, sy)) {
        return NULL;
    }
    if (overflow2(sizeof (int *), sy)) {
        return 0;
    }
    if (overflow2(sizeof(int *), sx)) {
        return NULL;
    }
    im = (gdImage *) gdMalloc (sizeof (gdImage));
    if (!im) {
        return 0;
    }
    memset (im, 0, sizeof (gdImage));
    im->tpixels = (int **) gdMalloc (sizeof (int *) * sy);
    if (!im->tpixels) {
        gdFree(im);
        return 0;
    }
    im->polyInts = 0;
    im->polyAllocated = 0;
    im->brush = 0;
    im->tile = 0;
    im->style = 0;
    for (i = 0; (i < sy); i++) {
        im->tpixels[i] = (int *) gdCalloc (sx, sizeof (int));
        if (!im->tpixels[i]) {
            /* 2.0.34 */
            i--;
            while (i >= 0) {
                gdFree(im->tpixels[i]);
                i--;
            }
            gdFree(im->tpixels);
            gdFree(im);
            return 0;
        }
    }
    im->sx = sx;
    im->sy = sy;
    im->transparent = (-1);
    im->interlace = 0;
    im->trueColor = 1;
    /* 2.0.2: alpha blending is now on by default, and saving of alpha is
       off by default. This allows font antialiasing to work as expected
       on the first try in JPEGs -- quite important -- and also allows
       for smaller PNGs when saving of alpha channel is not really
       desired, which it usually isn't! */
    im->saveAlphaFlag = 0;
    im->alphaBlendingFlag = 1;
    im->thick = 1;
    im->AA = 0;
    im->cx1 = 0;
    im->cy1 = 0;
    im->cx2 = im->sx - 1;
    im->cy2 = im->sy - 1;
    im->res_x = GD_RESOLUTION;
    im->res_y = GD_RESOLUTION;
    im->interpolation = NULL;
    im->interpolation_id = GD_BILINEAR_FIXED;
    return im;
}
References gdImageStruct::AA, gdImageStruct::alphaBlendingFlag, gdImageStruct::brush, gdImageStruct::cx1, gdImageStruct::cx2, gdImageStruct::cy1, gdImageStruct::cy2, GD_BILINEAR_FIXED, GD_RESOLUTION, gdCalloc(), gdMalloc(), gdImageStruct::interlace, gdImageStruct::interpolation, gdImageStruct::interpolation_id, overflow2(), gdImageStruct::polyAllocated, gdImageStruct::polyInts, gdImageStruct::res_x, gdImageStruct::res_y, gdImageStruct::saveAlphaFlag, gdImageStruct::style, gdImageStruct::sx, gdImageStruct::sy, sy, gdImageStruct::thick, gdImageStruct::tile, gdImageStruct::tpixels, gdImageStruct::transparent, and gdImageStruct::trueColor.
BGD_DECLARE() [2/3]
BGD_DECLARE (int)
Group: Color Function: gdImageColorClosest
Gets the closest color of the image
This is a simplified variant of <gdImageColorClosestAlpha> where the alpha channel is always opaque.
Parameters: im - The image. r - The value of the red component. g - The value of the green component. b - The value of the blue component.
Returns: The closest color already available in the palette for palette images; the color value of the given components for truecolor images.
See also:
<gdImageColorExact>
Function: gdImageColorClosestAlpha
Gets the closest color of the image
Parameters: im - The image. r - The value of the red component. g - The value of the green component. b - The value of the blue component. a - The value of the alpha component.
Returns: The closest color already available in the palette for palette images; the color value of the given components for truecolor images.
See also:
<gdImageColorExactAlpha>
Function: gdImageColorExact
Gets the exact color of the image
This is a simplified variant of <gdImageColorExactAlpha> where the alpha channel is always opaque.
Parameters: im - The image. r - The value of the red component. g - The value of the green component. b - The value of the blue component.
Returns: The exact color already available in the palette for palette images; if there is no exact color, -1 is returned. For truecolor images the color value of the given components is returned.
See also:
<gdImageColorClosest>
Function: gdImageColorExactAlpha
Gets the exact color of the image
Parameters: im - The image. r - The value of the red component. g - The value of the green component. b - The value of the blue component. a - The value of the alpha component.
Returns: The exact color already available in the palette for palette images; if there is no exact color, -1 is returned. For truecolor images the color value of the given components is returned.
See also:
<gdImageColorClosestAlpha>
<gdTrueColorAlpha>
Function: gdImageColorAllocate
Allocates a color
This is a simplified variant of <gdImageColorAllocateAlpha> where the alpha channel is always opaque.
Parameters: im - The image. r - The value of the red component. g - The value of the green component. b - The value of the blue component.
Returns: The color value.
See also:
<gdImageColorDeallocate>
Function: gdImageColorAllocateAlpha
Allocates a color
This is typically used for palette images, but can be used for truecolor images as well.
Parameters: im - The image. r - The value of the red component. g - The value of the green component. b - The value of the blue component.
Returns: The color value.
See also:
<gdImageColorDeallocate>
Function: gdImageGetPixel
Gets a pixel color as stored in the image.
Parameters: im - The image. x - The x-coordinate. y - The y-coordinate.
See also:
<gdImageGetTrueColorPixel>
<gdImagePalettePixel>
<gdImageTrueColorPixel>
Function: gdImageGetTrueColorPixel
Gets a pixel color always as truecolor value.
Parameters: im - The image. x - The x-coordinate. y - The y-coordinate.
See also:
<gdImageGetPixel>
<gdImageTrueColorPixel>
Function: gdImageCompare
Compare two images
Parameters: im1 - An image. im2 - Another image.
Returns: A bitmask of <Image Comparison> flags where each set flag signals which attributes of the images are different.
Function: gdAlphaBlend
Blend two colors
Parameters: dst - The color to blend onto. src - The color to blend.
See also:
<gdImageAlphaBlending>
<gdLayerOverlay>
<gdLayerMultiply>
Function: gdLayerOverlay
Overlay two colors
Parameters: dst - The color to overlay onto. src - The color to overlay.
See also:
<gdImageAlphaBlending>
<gdAlphaBlend>
<gdLayerMultiply>
Function: gdLayerMultiply
Overlay two colors with multiply effect
Parameters: dst - The color to overlay onto. src - The color to overlay.
See also:
<gdImageAlphaBlending>
<gdAlphaBlend>
<gdLayerOverlay>
Function: gdImagePaletteToTrueColor
Convert a palette image to true color
Parameters: src - The image.
Returns: Non-zero if the conversion succeeded, zero otherwise.
See also:
<gdImageTrueColorToPalette>
Definition at line 146 of file gd.c.
{
    int i;
    gdImagePtr im;
    if (overflow2(sx, sy)) {
        return NULL;
    }
    if (overflow2(sizeof (unsigned char *), sy)) {
        return NULL;
    }
    if (overflow2(sizeof (unsigned char *), sx)) {
        return NULL;
    }
    im = (gdImage *) gdCalloc(1, sizeof(gdImage));
    if (!im) {
        return NULL;
    }
    /* Row-major ever since gd 1.3 */
    im->pixels = (unsigned char **) gdMalloc (sizeof (unsigned char *) * sy);
    if (!im->pixels) {
        gdFree(im);
        return NULL;
    }
    im->polyInts = 0;
    im->polyAllocated = 0;
    im->brush = 0;
    im->tile = 0;
    im->style = 0;
    for (i = 0; (i < sy); i++) {
        /* Row-major ever since gd 1.3 */
        im->pixels[i] = (unsigned char *) gdCalloc (sx, sizeof (unsigned char));
        if (!im->pixels[i]) {
            for (--i ; i >= 0; i--) {
                gdFree(im->pixels[i]);
            }
            gdFree(im->pixels);
            gdFree(im);
            return NULL;
        }
    }
    im->sx = sx;
    im->sy = sy;
    im->colorsTotal = 0;
    im->transparent = (-1);
    im->interlace = 0;
    im->thick = 1;
    im->AA = 0;
    for (i = 0; (i < gdMaxColors); i++) {
        im->open[i] = 1;
    };
    im->trueColor = 0;
    im->tpixels = 0;
    im->cx1 = 0;
    im->cy1 = 0;
    im->cx2 = im->sx - 1;
    im->cy2 = im->sy - 1;
    im->res_x = GD_RESOLUTION;
    im->res_y = GD_RESOLUTION;
    im->interpolation = NULL;
    im->interpolation_id = GD_BILINEAR_FIXED;
    return im;
}
BGD_DECLARE() [3/3]
BGD_DECLARE (void)
Function: gdImageColorDeallocate
Removes a palette entry
This is a no-op for truecolor images.
Parameters: im - The image. color - The palette index.
See also:
<gdImageColorAllocate>
<gdImageColorAllocateAlpha>
Function: gdImageColorTransparent
Sets the transparent color of the image
Parameter: im - The image. color - The color.
See also:
<gdImageGetTransparent>
Group: Pixels
Group: Primitives
Function: gdImageChar
Draws a single character.
Parameters: im - The image to draw onto. f - The raster font. x - The x coordinate of the upper left pixel. y - The y coordinate of the upper left pixel. c - The character. color - The color.
Variants:
<gdImageCharUp>
See also:
<gdFontPtr>
Function: gdImageCharUp
Function: gdImageString
Draws a character string.
Parameters: im - The image to draw onto. f - The raster font. x - The x coordinate of the upper left pixel. y - The y coordinate of the upper left pixel. c - The character string. color - The color.
Variants:
<gdImageStringUp>
<gdImageString16>
<gdImageStringUp16>
See also:
<gdFontPtr>
<gdImageStringTTF>
Function: gdImageStringUp
Function: gdImageString16
Function: gdImageStringUp16
Function: gdImageRectangle
Draws a rectangle.
Parameters: im - The image. x1 - The x-coordinate of the upper left corner. y1 - The y-coordinate of the upper left corner. x2 - The x-coordinate of the lower right corner. y2 - The y-coordinate of the lower right corner. color - The color.
Note that x1,y1 and x2,y2 may be swapped, i.e. the former may designate the lower right corner and the latter the upper left corner. The behavior for specifying other corners is undefined.
See also:
<gdImageFilledRectangle>
Function: gdImageCopy
Copy an area of an image to another image
Parameters: dst - The destination image. src - The source image. dstX - The x-coordinate of the upper left corner to copy to. dstY - The y-coordinate of the upper left corner to copy to. srcX - The x-coordinate of the upper left corner to copy from. srcY - The y-coordinate of the upper left corner to copy from. w - The width of the area to copy. h - The height of the area to copy.
See also:
<gdImageCopyMerge>
<gdImageCopyMergeGray>
Function: gdImageCopyMerge
Copy an area of an image to another image ignoring alpha
The source area will be copied to the destination are by merging the pixels.
Note: This function is a substitute for real alpha channel operations, so it doesn't pay attention to the alpha channel.
Parameters: dst - The destination image. src - The source image. dstX - The x-coordinate of the upper left corner to copy to. dstY - The y-coordinate of the upper left corner to copy to. srcX - The x-coordinate of the upper left corner to copy from. srcY - The y-coordinate of the upper left corner to copy from. w - The width of the area to copy. h - The height of the area to copy. pct - The percentage in range 0..100.
See also:
<gdImageCopy>
<gdImageCopyMergeGray>
Function: gdImageCopyMergeGray
Copy an area of an image to another image ignoring alpha
The source area will be copied to the grayscaled destination area by merging the pixels.
Note: This function is a substitute for real alpha channel operations, so it doesn't pay attention to the alpha channel.
Parameters: dst - The destination image. src - The source image. dstX - The x-coordinate of the upper left corner to copy to. dstY - The y-coordinate of the upper left corner to copy to. srcX - The x-coordinate of the upper left corner to copy from. srcY - The y-coordinate of the upper left corner to copy from. w - The width of the area to copy. h - The height of the area to copy. pct - The percentage of the source color intensity in range 0..100.
See also:
<gdImageCopy>
<gdImageCopyMerge>
Function: gdImageCopyResized
Copy a resized area from an image to another image
If the source and destination area differ in size, the area will be resized using nearest-neighbor interpolation.
Parameters: dst - The destination image. src - The source image. dstX - The x-coordinate of the upper left corner to copy to. dstY - The y-coordinate of the upper left corner to copy to. srcX - The x-coordinate of the upper left corner to copy from. srcY - The y-coordinate of the upper left corner to copy from. dstW - The width of the area to copy to. dstH - The height of the area to copy to. srcW - The width of the area to copy from. srcH - The height of the area to copy from.
See also:
<gdImageCopyResampled>
<gdImageScale>
Function: gdImageCopyRotated
Copy a rotated area from an image to another image
The area is counter-clockwise rotated using nearest-neighbor interpolation.
Parameters: dst - The destination image. src - The source image. dstX - The x-coordinate of the center of the area to copy to. dstY - The y-coordinate of the center of the area to copy to. srcX - The x-coordinate of the upper left corner to copy from. srcY - The y-coordinate of the upper left corner to copy from. srcW - The width of the area to copy from. srcH - The height of the area to copy from. angle - The angle in degrees.
See also:
<gdImageRotateInterpolated>
Function: gdImageCopyResampled
Copy a resampled area from an image to another image
If the source and destination area differ in size, the area will be resized using bilinear interpolation for truecolor images, and nearest-neighbor interpolation for palette images.
Parameters: dst - The destination image. src - The source image. dstX - The x-coordinate of the upper left corner to copy to. dstY - The y-coordinate of the upper left corner to copy to. srcX - The x-coordinate of the upper left corner to copy from. srcY - The y-coordinate of the upper left corner to copy from. dstW - The width of the area to copy to. dstH - The height of the area to copy to. srcW - The width of the area to copy from. srcH - The height of the area to copy from.
See also:
<gdImageCopyResized>
<gdImageScale>
Group: Polygons Function: gdImagePolygon
Draws a closed polygon
Parameters: im - The image. p - The vertices as array of <gdPoint>s. n - The number of vertices. c - The color.
See also:
<gdImageOpenPolygon>
<gdImageFilledPolygon>
Function: gdImageOpenPolygon
Draws an open polygon
Parameters: im - The image. p - The vertices as array of <gdPoint>s. n - The number of vertices. c - The color
See also:
<gdImagePolygon>
Function: gdImageFilledPolygon
Draws a filled polygon
The polygon is filled using the even-odd fillrule what can leave unfilled regions inside of self-intersecting polygons. This behavior might change in a future version.
Parameters: im - The image. p - The vertices as array of <gdPoint>s. n - The number of vertices. c - The color
See also:
<gdImagePolygon>
Function: gdImageSetStyle
Sets the style for following drawing operations
Parameters: im - The image. style - An array of color values. noOfPixel - The number of color values.
Function: gdImageSetThickness
Sets the thickness for following drawing operations
Parameters: im - The image. thickness - The thickness in pixels.
Function: gdImageSetBrush
Sets the brush for following drawing operations
Parameters: im - The image. brush - The brush image.
Function: gdImageSetAntiAliased
Set the color for subsequent anti-aliased drawing
If <gdAntiAliased> is passed as color to drawing operations that support anti-aliased drawing (such as <gdImageLine> and <gdImagePolygon>), the actual color to be used can be set with this function.
Example: draw an anti-aliased blue line: | gdImageSetAntiAliased(im, gdTrueColorAlpha(0, 0, gdBlueMax, gdAlphaOpaque)); | gdImageLine(im, 10,10, 20,20, gdAntiAliased);
Parameters: im - The image. c - The color.
See also:
<gdImageSetAntiAliasedDontBlend>
Function: gdImageSetAntiAliasedDontBlend
Set the color and `dont_blend` color for subsequent anti-aliased drawing
This extended variant of <gdImageSetAntiAliased> allows to also specify a (background) color that will not be blended in anti-aliased drawing operations.
Parameters: im - The image. c - The color. dont_blend - Whether to blend.
Function: gdImageInterlace
Sets whether an image is interlaced
This is relevant only when saving the image in a format that supports interlacing.
Parameters: im - The image. interlaceArg - Whether the image is interlaced.
See also:
<gdImageGetInterlaced>
Function: gdImageAlphaBlending
Set the effect for subsequent drawing operations
Note that the effect is used for truecolor images only.
Parameters: im - The image. alphaBlendingArg - The effect.
See also:
<Effects>
Function: gdImageSaveAlpha
Sets the save alpha flag
The save alpha flag specifies whether the alpha channel of the pixels should be saved. This is supported only for image formats that support full alpha transparency, e.g. PNG.
Function: gdImageSetClip
Sets the clipping rectangle
The clipping rectangle restricts the drawing area for following drawing operations.
Parameters: im - The image. x1 - The x-coordinate of the upper left corner. y1 - The y-coordinate of the upper left corner. x2 - The x-coordinate of the lower right corner. y2 - The y-coordinate of the lower right corner.
See also:
<gdImageGetClip>
Function: gdImageGetClip
Gets the current clipping rectangle
Parameters: im - The image. x1P - (out) The x-coordinate of the upper left corner. y1P - (out) The y-coordinate of the upper left corner. x2P - (out) The x-coordinate of the lower right corner. y2P - (out) The y-coordinate of the lower right corner.
See also:
<gdImageSetClip>
Function: gdImageSetResolution
Sets the resolution of an image.
Parameters: im - The image. res_x - The horizontal resolution in DPI. res_y - The vertical resolution in DPI.
See also:
<gdImageResolutionX>
<gdImageResolutionY>
Definition at line 130 of file gd.c.
{
    gd_error_method = error_method;
}
References gd_error_method.
clip_1d()
static int clip_1d (int * x0, int * y0, int * x1, int * y1, int mindim, int maxdim) [static]
Definition at line 1181 of file gd.c.
{
    double m; /* gradient of line */
    if (*x0 < mindim) {
        /* start of line is left of window */
        if (*x1 < mindim) /* as is the end, so the line never cuts the window */
            return 0;
        m = (*y1 - *y0) / (double) (*x1 - *x0); /* calculate the slope of the line */
        /* adjust x0 to be on the left boundary (ie to be zero), and y0 to match */
        *y0 -= (int)(m * (*x0 - mindim));
        *x0 = mindim;
        /* now, perhaps, adjust the far end of the line as well */
        if (*x1 > maxdim) {
            *y1 += (int)(m * (maxdim - *x1));
            *x1 = maxdim;
        }
        return 1;
    }
    if (*x0 > maxdim) {
        /* start of line is right of window -
        complement of above */
        if (*x1 > maxdim) /* as is the end, so the line misses the window */
            return 0;
        m = (*y1 - *y0) / (double) (*x1 - *x0); /* calculate the slope of the line */
        *y0 += (int)(m * (maxdim - *x0)); /* adjust so point is on the right
                               boundary */
        *x0 = maxdim;
        /* now, perhaps, adjust the end of the line */
        if (*x1 < mindim) {
            *y1 -= (int)(m * (*x1 - mindim));
            *x1 = mindim;
        }
        return 1;
    }
    /* the final case - the start of the line is inside the window */
    if (*x1 > maxdim) {
        /* other end is outside to the right */
        m = (*y1 - *y0) / (double) (*x1 - *x0); /* calculate the slope of the line */
        *y1 += (int)(m * (maxdim - *x1));
        *x1 = maxdim;
        return 1;
    }
    if (*x1 < mindim) {
        /* other end is outside to the left */
        m = (*y1 - *y0) / (double) (*x1 - *x0); /* calculate the slope of the line */
        *y1 -= (int)(m * (*x1 - mindim));
        *x1 = mindim;
        return 1;
    }
    /* only get here if both points are inside the window */
    return 1;
}
References x1, and y1.
Referenced by gdImageAALine().
colorCmp()
static int colorCmp (const void * x, const void * y) [static]
Definition at line 1049 of file gd.c.
{
    int a = *(int const *)x;
    int b = *(int const *)y;
    return (a > b) - (a < b);
}
References a, b, x, and y.
dashedSet()
static void dashedSet (gdImagePtr im, int x, int y, int color, int * onP, int * dashStepP, int wid, int vert) [static]
Definition at line 1834 of file gd.c.
{
    int dashStep = *dashStepP;
    int on = *onP;
    int w, wstart;
    dashStep++;
    if (dashStep == gdDashSize) {
        dashStep = 0;
        on = !on;
    }
    if (on) {
        if (vert) {
            wstart = y - wid / 2;
            for (w = wstart; w < wstart + wid; w++)
                gdImageSetPixel (im, x, w, color);
        } else {
            wstart = x - wid / 2;
            for (w = wstart; w < wstart + wid; w++)
                gdImageSetPixel (im, w, y, color);
        }
    }
    *dashStepP = dashStep;
    *onP = on;
}
References color, gdDashSize, w, x, and y.
gd_error()
void gd_error (const char * format, ...)
Definition at line 110 of file gd.c.
{
    va_list args;
    va_start(args, format);
    _gd_error_ex(GD_WARNING, format, args);
    va_end(args);
}
References _gd_error_ex(), and GD_WARNING.
gd_error_ex()
void gd_error_ex (int priority, const char * format, ...)
Definition at line 118 of file gd.c.
{
    va_list args;
    va_start(args, format);
    _gd_error_ex(priority, format, args);
    va_end(args);
}
References _gd_error_ex().
gd_stderr_error()
void gd_stderr_error (int priority, const char * format, va_list args)
Group: Error Handling
Definition at line 78 of file gd.c.
{
    switch (priority) {
    case GD_ERROR:
        fputs("GD Error: ", stderr);
        break;
    case GD_WARNING:
        fputs("GD Warning: ", stderr);
        break;
    case GD_NOTICE:
        fputs("GD Notice: ", stderr);
        break;
    case GD_INFO:
        fputs("GD Info: ", stderr);
        break;
    case GD_DEBUG:
        fputs("GD Debug: ", stderr);
        break;
    }
    vfprintf(stderr, format, args);
    fflush(stderr);
}
References GD_DEBUG, GD_ERROR, GD_INFO, GD_NOTICE, and GD_WARNING.
gdAlphaOverlayColor()
static int gdAlphaOverlayColor (int src, int dst, int max) [static]
Definition at line 4133 of file gd.c.
{
    dst = dst << 1;
    if(dst > max) {
        /* in the "light" zone */
        return dst + (src << 1) - (dst * src / max) - max;
    } else {
        /* in the "dark" zone */
        return dst * src / max;
    }
}
References dst, and src.
gdImageAALine()
static void gdImageAALine (gdImagePtr im, int x1, int y1, int x2, int y2, int col) [static]
Definition at line 4343 of file gd.c.
{
    /* keep them as 32bits */
    long x, y, inc, frac;
    long dx, dy,tmp;
    int w, wid, wstart;
    int thick = im->thick;
    if (!im->trueColor) {
        /* TBB: don't crash when the image is of the wrong type */
        gdImageLine(im, x1, y1, x2, y2, col);
        return;
    }
    /* TBB: use the clipping rectangle */
    if (clip_1d (&x1, &y1, &x2, &y2, im->cx1, im->cx2) == 0)
        return;
    if (clip_1d (&y1, &x1, &y2, &x2, im->cy1, im->cy2) == 0)
        return;
    dx = x2 - x1;
    dy = y2 - y1;
    if (dx == 0 && dy == 0) {
        /* TBB: allow setting points */
        gdImageSetAAPixelColor(im, x1, y1, col, 0xFF);
        return;
    } else {
        double ag;
        /* Cast the long to an int to avoid compiler warnings about truncation.
         * This isn't a problem as computed dy/dx values came from ints above. */
        ag = fabs(abs((int)dy) < abs((int)dx) ? cos(atan2(dy, dx)) : sin(atan2(dy, dx)));
        if (ag != 0) {
            wid = (int)(thick / ag);
        } else {
            wid = 1;
        }
        if (wid == 0) {
            wid = 1;
        }
    }
    /* Axis aligned lines */
    if (dx == 0) {
        gdImageVLine(im, x1, y1, y2, col);
        return;
    } else if (dy == 0) {
        gdImageHLine(im, y1, x1, x2, col);
        return;
    }
    if (abs((int)dx) > abs((int)dy)) {
        if (dx < 0) {
            tmp = x1;
            x1 = x2;
            x2 = tmp;
            tmp = y1;
            y1 = y2;
            y2 = tmp;
            dx = x2 - x1;
            dy = y2 - y1;
        }
        y = y1;
        inc = (dy * 65536) / dx;
        frac = 0;
        /* TBB: set the last pixel for consistency (<=) */
        for (x = x1 ; x <= x2 ; x++) {
            wstart = y - wid / 2;
            for (w = wstart; w < wstart + wid; w++) {
                gdImageSetAAPixelColor(im, x , w , col , (frac >> 8) & 0xFF);
                gdImageSetAAPixelColor(im, x , w + 1 , col, (~frac >> 8) & 0xFF);
            }
            frac += inc;
            if (frac >= 65536) {
                frac -= 65536;
                y++;
            } else if (frac < 0) {
                frac += 65536;
                y--;
            }
        }
    } else {
        if (dy < 0) {
            tmp = x1;
            x1 = x2;
            x2 = tmp;
            tmp = y1;
            y1 = y2;
            y2 = tmp;
            dx = x2 - x1;
            dy = y2 - y1;
        }
        x = x1;
        inc = (dx * 65536) / dy;
        frac = 0;
        /* TBB: set the last pixel for consistency (<=) */
        for (y = y1 ; y <= y2 ; y++) {
            wstart = x - wid / 2;
            for (w = wstart; w < wstart + wid; w++) {
                gdImageSetAAPixelColor(im, w , y , col, (frac >> 8) & 0xFF);
                gdImageSetAAPixelColor(im, w + 1, y, col, (~frac >> 8) & 0xFF);
            }
            frac += inc;
            if (frac >= 65536) {
                frac -= 65536;
                x++;
            } else if (frac < 0) {
                frac += 65536;
                x--;
            }
        }
    }
}
References clip_1d(), gdImageStruct::cx1, gdImageStruct::cx2, gdImageStruct::cy1, gdImageStruct::cy2, seg::dy, gdImageHLine(), gdImageSetAAPixelColor(), gdImageVLine(), gdImageStruct::thick, gdImageStruct::trueColor, w, x, x1, x2, y, y1, and y2.
gdImageBrushApply()
static void gdImageBrushApply (gdImagePtr im, int x, int y) [static]
Definition at line 1309 of file gd.c.
{
    int lx, ly;
    int hy;
    int hx;
    int x1, y1, x2, y2;
    int srcx, srcy;
    if (!im->brush) {
        return;
    }
    hy = gdImageSY (im->brush) / 2;
    y1 = y - hy;
    y2 = y1 + gdImageSY (im->brush);
    hx = gdImageSX (im->brush) / 2;
    x1 = x - hx;
    x2 = x1 + gdImageSX (im->brush);
    srcy = 0;
    if (im->trueColor) {
        if (im->brush->trueColor) {
            for (ly = y1; (ly < y2); ly++) {
                srcx = 0;
                for (lx = x1; (lx < x2); lx++) {
                    int p;
                    p = gdImageGetTrueColorPixel (im->brush, srcx, srcy);
                    /* 2.0.9, Thomas Winzig: apply simple full transparency */
                    if (p != gdImageGetTransparent (im->brush)) {
                        gdImageSetPixel (im, lx, ly, p);
                    }
                    srcx++;
                }
                srcy++;
            }
        } else {
            /* 2.0.12: Brush palette, image truecolor (thanks to Thorben Kundinger
               for pointing out the issue) */
            for (ly = y1; (ly < y2); ly++) {
                srcx = 0;
                for (lx = x1; (lx < x2); lx++) {
                    int p, tc;
                    p = gdImageGetPixel (im->brush, srcx, srcy);
                    tc = gdImageGetTrueColorPixel (im->brush, srcx, srcy);
                    /* 2.0.9, Thomas Winzig: apply simple full transparency */
                    if (p != gdImageGetTransparent (im->brush)) {
                        gdImageSetPixel (im, lx, ly, tc);
                    }
                    srcx++;
                }
                srcy++;
            }
        }
    } else {
        for (ly = y1; (ly < y2); ly++) {
            srcx = 0;
            for (lx = x1; (lx < x2); lx++) {
                int p;
                p = gdImageGetPixel (im->brush, srcx, srcy);
                /* Allow for non-square brushes! */
                if (p != gdImageGetTransparent (im->brush)) {
                    /* Truecolor brush. Very slow
                       on a palette destination. */
                    if (im->brush->trueColor) {
                        gdImageSetPixel (im, lx, ly,
                                         gdImageColorResolveAlpha (im,
                                                 gdTrueColorGetRed
                                                 (p),
                                                 gdTrueColorGetGreen
                                                 (p),
                                                 gdTrueColorGetBlue
                                                 (p),
                                                 gdTrueColorGetAlpha
                                                 (p)));
                    } else {
                        gdImageSetPixel (im, lx, ly, im->brushColorMap[p]);
                    }
                }
                srcx++;
            }
            srcy++;
        }
    }
}
References gdImageStruct::brush, gdImageStruct::brushColorMap, gdImageGetTransparent, gdImageSX, gdImageSY, gdTrueColorGetAlpha, gdTrueColorGetBlue, gdTrueColorGetGreen, gdTrueColorGetRed, p, srcx, srcy, gdImageStruct::trueColor, x, x1, x2, y, y1, and y2.
gdImageHLine()
static void gdImageHLine (gdImagePtr im, int y, int x1, int x2, int col) [static]
Definition at line 1507 of file gd.c.
{
    if (im->thick > 1) {
        int thickhalf = im->thick >> 1;
        _gdImageFilledHRectangle(im, x1, y - thickhalf, x2, y + im->thick - thickhalf - 1, col);
    } else {
        if (x2 < x1) {
            int t = x2;
            x2 = x1;
            x1 = t;
        }
        for (; x1 <= x2; x1++) {
            gdImageSetPixel(im, x1, y, col);
        }
    }
    return;
}
References _gdImageFilledHRectangle(), gdImageStruct::thick, x1, x2, and y.
Referenced by gdImageAALine().
gdImageSetAAPixelColor()
static void gdImageSetAAPixelColor (gdImagePtr im, int x, int y, int color, int t) [static]
Group: other
Definition at line 4313 of file gd.c.
{
    int dr,dg,db,p,r,g,b;
    /* 2.0.34: watch out for out of range calls */
    if (!gdImageBoundsSafeMacro(im, x, y)) {
        return;
    }
    p = gdImageGetPixel(im,x,y);
    /* TBB: we have to implement the dont_blend stuff to provide
      the full feature set of the old implementation */
    if ((p == color)
            || ((p == im->AA_dont_blend)
                && (t != 0x00))) {
        return;
    }
    dr = gdTrueColorGetRed(color);
    dg = gdTrueColorGetGreen(color);
    db = gdTrueColorGetBlue(color);
    r = gdTrueColorGetRed(p);
    g = gdTrueColorGetGreen(p);
    b = gdTrueColorGetBlue(p);
    BLEND_COLOR(t, dr, r, dr);
    BLEND_COLOR(t, dg, g, dg);
    BLEND_COLOR(t, db, b, db);
    im->tpixels[y][x] = gdTrueColorAlpha(dr, dg, db, gdAlphaOpaque);
}
References gdImageStruct::AA_dont_blend, b, BLEND_COLOR, color, g, gdAlphaOpaque, gdImageBoundsSafeMacro, gdTrueColorAlpha, gdTrueColorGetBlue, gdTrueColorGetGreen, gdTrueColorGetRed, p, r, gdImageStruct::tpixels, x, and y.
Referenced by gdImageAALine().
gdImageTileApply()
static void gdImageTileApply (gdImagePtr im, int x, int y) [static]
Definition at line 1392 of file gd.c.
{
    gdImagePtr tile = im->tile;
    int srcx, srcy;
    int p;
    if (!tile) {
        return;
    }
    srcx = x % gdImageSX (tile);
    srcy = y % gdImageSY (tile);
    if (im->trueColor) {
        p = gdImageGetPixel (tile, srcx, srcy);
        if (p != gdImageGetTransparent (tile)) {
            if (!tile->trueColor) {
                p = gdTrueColorAlpha(tile->red[p], tile->green[p], tile->blue[p], tile->alpha[p]);
            }
            gdImageSetPixel (im, x, y, p);
        }
    } else {
        p = gdImageGetPixel (tile, srcx, srcy);
        /* Allow for transparency */
        if (p != gdImageGetTransparent (tile)) {
            if (tile->trueColor) {
                /* Truecolor tile. Very slow
                   on a palette destination. */
                gdImageSetPixel (im, x, y,
                                 gdImageColorResolveAlpha (im,
                                         gdTrueColorGetRed
                                         (p),
                                         gdTrueColorGetGreen
                                         (p),
                                         gdTrueColorGetBlue
                                         (p),
                                         gdTrueColorGetAlpha
                                         (p)));
            } else {
                gdImageSetPixel (im, x, y, im->tileColorMap[p]);
            }
        }
    }
}
References gdImageStruct::alpha, gdImageStruct::blue, gdImageGetTransparent, gdImageSX, gdImageSY, gdTrueColorAlpha, gdTrueColorGetAlpha, gdTrueColorGetBlue, gdTrueColorGetGreen, gdTrueColorGetRed, gdImageStruct::green, p, gdImageStruct::red, srcx, srcy, gdImageStruct::tile, tile, gdImageStruct::tileColorMap, gdImageStruct::trueColor, x, and y.
gdImageTileGet()
static int gdImageTileGet (gdImagePtr im, int x, int y) [static]
Definition at line 2370 of file gd.c.
{
    int srcx, srcy;
    int tileColor,p;
    if (!im->tile) {
        return -1;
    }
    srcx = x % gdImageSX(im->tile);
    srcy = y % gdImageSY(im->tile);
    p = gdImageGetPixel(im->tile, srcx, srcy);
    if (p == im->tile->transparent) {
        tileColor = im->transparent;
    } else if (im->trueColor) {
        if (im->tile->trueColor) {
            tileColor = p;
        } else {
            tileColor = gdTrueColorAlpha(gdImageRed(im->tile,p), gdImageGreen(im->tile,p), gdImageBlue (im->tile,p), gdImageAlpha (im->tile,p));
        }
    } else {
        if (im->tile->trueColor) {
            tileColor = gdImageColorResolveAlpha(im, gdTrueColorGetRed (p), gdTrueColorGetGreen (p), gdTrueColorGetBlue (p), gdTrueColorGetAlpha (p));
        } else {
            tileColor = gdImageColorResolveAlpha(im, gdImageRed (im->tile,p), gdImageGreen (im->tile,p), gdImageBlue (im->tile,p), gdImageAlpha (im->tile,p));
        }
    }
    return tileColor;
}
References gdImageAlpha, gdImageBlue, gdImageGreen, gdImageRed, gdImageSX, gdImageSY, gdTrueColorAlpha, gdTrueColorGetAlpha, gdTrueColorGetBlue, gdTrueColorGetGreen, gdTrueColorGetRed, p, srcx, srcy, gdImageStruct::tile, gdImageStruct::transparent, gdImageStruct::trueColor, x, and y.
Referenced by _gdImageFillTiled().
gdImageVLine()
static void gdImageVLine (gdImagePtr im, int x, int y1, int y2, int col) [static]
Definition at line 1526 of file gd.c.
{
    if (im->thick > 1) {
        int thickhalf = im->thick >> 1;
        gdImageFilledRectangle(im, x - thickhalf, y1, x + im->thick - thickhalf - 1, y2, col);
    } else {
        if (y2 < y1) {
            int t = y1;
            y1 = y2;
            y2 = t;
        }
        for (; y1 <= y2; y1++) {
            gdImageSetPixel(im, x, y1, col);
        }
    }
    return;
}
References gdImageStruct::thick, x, y1, and y2.
Referenced by gdImageAALine().
HWB_Diff()
static float HWB_Diff (int r1, int g1, int b1, int r2, int g2, int b2) [static]
Definition at line 550 of file gd.c.
{
    RGBType RGB1, RGB2;
    HWBType HWB1, HWB2;
    float diff;
    SETUP_RGB (RGB1, r1, g1, b1);
    SETUP_RGB (RGB2, r2, g2, b2);
    RGB_to_HWB (RGB1, &HWB1);
    RGB_to_HWB (RGB2, &HWB2);
    /*
     * I made this bit up; it seems to produce OK results, and it is certainly
     * more visually correct than the current RGB metric. (PJW)
     */
    if ((HWB1.H == HWB_UNDEFINED) || (HWB2.H == HWB_UNDEFINED)) {
        diff = 0; /* Undefined hues always match... */
    } else {
        diff = fabsf(HWB1.H - HWB2.H);
        if (diff > 3) {
            diff = 6 - diff; /* Remember, it's a colour circle */
        }
    }
    diff =
        diff * diff + (HWB1.W - HWB2.W) * (HWB1.W - HWB2.W) + (HWB1.B -
                HWB2.B) * (HWB1.B -
                           HWB2.B);
    return diff;
}
References HWBType::B, HWBType::H, HWB_UNDEFINED, RGB_to_HWB(), SETUP_RGB, and HWBType::W.
lsqrt()
long lsqrt (long n)
Definition at line 2040 of file gd.c.
{
    long result = (long) sqrt ((double) n);
    return result;
}
References n.
RGB_to_HWB()
static HWBType * RGB_to_HWB (RGBType RGB, HWBType * HWB) [static]
Definition at line 527 of file gd.c.
{
    /*
     * RGB are each on [0, 1]. W and B are returned on [0, 1] and H is
     * returned on [0, 6]. Exception: H is returned UNDEFINED if W == 1 - B.
     */
    float R = RGB.R, G = RGB.G, B = RGB.B, w, v, b, f;
    int i;
    w = MIN3 (R, G, B);
    v = MAX3 (R, G, B);
    b = 1 - v;
    if (v == w)
        RETURN_HWB (HWB_UNDEFINED, w, b);
    f = (R == w) ? G - B : ((G == w) ? B - R : R - G);
    i = (R == w) ? 3 : ((G == w) ? 5 : 1);
    RETURN_HWB (i - f / (v - w), w, b);
}
References RGBType::B, b, f, RGBType::G, HWB_UNDEFINED, MAX3, MIN3, RGBType::R, RETURN_HWB, and w.
Referenced by HWB_Diff().
strlen16()
static int strlen16 (unsigned short * s) [static]
Definition at line 2025 of file gd.c.
{
    int len = 0;
    while (*s) {
        s++;
        len++;
    }
    return len;
}
References len, and s.
Variable Documentation
gd_error_method
gdErrorMethod gd_error_method = gd_stderr_error [static]
Definition at line 101 of file gd.c.
Referenced by _gd_error_ex(), and BGD_DECLARE().
gdCosT
const int gdCosT[] [extern]
Definition at line 2 of file gdtables.c.
gdSinT
const int gdSinT[] [extern]
Definition at line 365 of file gdtables.c.