doxygen/libmscgen/mscgen_adraw_int.h File Reference
#include `mscgen_adraw.h`
Macros
#define UNUSED
Functions
Boolean NullInit (struct ADrawTag *outContext)
Boolean GdoInit (unsigned int w, unsigned int h, const char *file, const char *fontName, struct ADrawTag *outContext)
Boolean PsInit (unsigned int w, unsigned int h, const char *file, struct ADrawTag *outContext)
Boolean SvgInit (unsigned int w, unsigned int h, const char *file, struct ADrawTag *outContext)
Macro Definition Documentation
UNUSED
#define UNUSED
Definition at line 37 of file mscgen_adraw_int.h.
Function Documentation
GdoInit()
Boolean GdoInit (unsigned int w, unsigned int h, const char * file, const char * fontName, struct ADrawTag * outContext)
NullInit()
Boolean NullInit (struct ADrawTag * outContext)
Definition at line 148 of file mscgen_null_out.c.
{
    /* Fill in the function pointers */
    outContext->line = NullLine;
    outContext->dottedLine = NullDottedLine;
    outContext->textL = NullTextL;
    outContext->textC = NullTextC;
    outContext->textR = NullTextR;
    outContext->textWidth = NullTextWidth;
    outContext->textHeight = NullTextHeight;
    outContext->filledRectangle = NullFilledRectangle;
    outContext->filledTriangle = NullFilledTriangle;
    outContext->arc = NullArc;
    outContext->dottedArc = NullDottedArc;
    outContext->setPen = NullSetPen;
    outContext->setBgPen = NullSetPen;
    outContext->setFontSize = NullSetFontSize;
    outContext->close = NullClose;
    return TRUE;
}
References ADrawTag::arc, ADrawTag::close, ADrawTag::dottedArc, ADrawTag::dottedLine, ADrawTag::filledRectangle, ADrawTag::filledTriangle, ADrawTag::line, NullArc(), NullClose(), NullDottedArc(), NullDottedLine(), NullFilledRectangle(), NullFilledTriangle(), NullLine(), NullSetFontSize(), NullSetPen(), NullTextC(), NullTextHeight(), NullTextL(), NullTextR(), NullTextWidth(), ADrawTag::setBgPen, ADrawTag::setFontSize, ADrawTag::setPen, ADrawTag::textC, ADrawTag::textHeight, ADrawTag::textL, ADrawTag::textR, ADrawTag::textWidth, and TRUE.
PsInit()
Boolean PsInit (unsigned int w, unsigned int h, const char * file, struct ADrawTag * outContext)
Definition at line 494 of file mscgen_ps_out.c.
{
    PsContext *context;
    /* Create context */
    context = outContext->internal = malloc_s(sizeof(PsContext));
    if(context == NULL)
    {
        return FALSE;
    }
    /* Open the output file */
    if(strcmp(file, "-") == 0)
    {
        context->of = stdout;
    }
    else
    {
        context->of = fopen(file, "wb");
        if(!context->of)
        {
            fprintf(stderr, "PsInit: Failed to open output file '%s': %s\n", file, strerror(errno));
            return FALSE;
        }
    }
    /* Write the header */
    fprintf(context->of, "%%!PS-Adobe-3.0 EPSF-2.0\n"
                         "%%%%BoundingBox: 0 0 %.0f %.0f\n", w * PS_OUT_SCALE, h * PS_OUT_SCALE);
    fprintf(context->of, "%%%%Creator: mscgen %s\n", PACKAGE_VERSION);
    fprintf(context->of, "%%%%EndComments\n");
    /* Shrink everything by 70% */
    fprintf(context->of, "%f %f scale\n", PS_OUT_SCALE, PS_OUT_SCALE);
    /* Create clipping rectangle to constrain dimensions */
    fprintf(context->of, "0 0 moveto\n");
    fprintf(context->of, "0 %u lineto\n", h);
    fprintf(context->of, "%u %u lineto\n", w, h);
    fprintf(context->of, "%u 0 lineto\n", w);
    fprintf(context->of, "closepath\n");
    fprintf(context->of, "clip\n");
    fprintf(context->of, "%%PageTrailer\n");
    fprintf(context->of, "%%Page: 1 1\n");
    /* Set default font */
    fprintf(context->of, "/Helvetica findfont\n");
    fprintf(context->of, "10 scalefont\n");
    fprintf(context->of, "setfont\n");
    /* Get the default font size */
    PsSetFontSize(outContext, ADRAW_FONT_SMALL);
    /* Translate up by the height, y-axis will be inverted */
    fprintf(context->of, "0 %d translate\n", h);
    /* Arc drawing function */
    fprintf(context->of, "/mtrx matrix def\n"
                         "/ellipse\n"
                         " { /endangle exch def\n"
                         " /startangle exch def\n"
                         " /ydia exch def\n"
                         " /xdia exch def\n"
                         " /y exch def\n"
                         " /x exch def\n"
                         " /savematrix mtrx currentmatrix def\n"
                         " x y translate\n"
                         " xdia 2 div ydia 2 div scale\n"
                         " 1 -1 scale\n"
                         " 0 0 1 startangle endangle arc\n"
                         " savematrix setmatrix\n"
                         "} def\n");
    /* Set the current pen colours */
    context->penColour = ADRAW_COL_BLACK;
    context->penBgColour = ADRAW_COL_WHITE;
    /* Now fill in the function pointers */
    outContext->line = PsLine;
    outContext->dottedLine = PsDottedLine;
    outContext->textL = PsTextL;
    outContext->textC = PsTextC;
    outContext->textR = PsTextR;
    outContext->textWidth = PsTextWidth;
    outContext->textHeight = PsTextHeight;
    outContext->filledRectangle = PsFilledRectangle;
    outContext->filledTriangle = PsFilledTriangle;
    outContext->filledCircle = PsFilledCircle;
    outContext->arc = PsArc;
    outContext->dottedArc = PsDottedArc;
    outContext->setPen = PsSetPen;
    outContext->setBgPen = PsSetBgPen;
    outContext->setFontSize = PsSetFontSize;
    outContext->close = PsClose;
    return TRUE;
}
References ADRAW_COL_BLACK, ADRAW_COL_WHITE, ADRAW_FONT_SMALL, ADrawTag::arc, ADrawTag::close, ADrawTag::dottedArc, ADrawTag::dottedLine, errno, FALSE, caseconvert::file, ADrawTag::filledCircle, ADrawTag::filledRectangle, ADrawTag::filledTriangle, Portable::fopen(), h, ADrawTag::internal, ADrawTag::line, malloc_s(), PsContextTag::of, PACKAGE_VERSION, PsContextTag::penBgColour, PsContextTag::penColour, PS_OUT_SCALE, PsArc(), PsClose(), PsDottedArc(), PsDottedLine(), PsFilledCircle(), PsFilledRectangle(), PsFilledTriangle(), PsLine(), PsSetBgPen(), PsSetFontSize(), PsSetPen(), PsTextC(), PsTextHeight(), PsTextL(), PsTextR(), PsTextWidth(), ADrawTag::setBgPen, ADrawTag::setFontSize, ADrawTag::setPen, strcmp(), ADrawTag::textC, ADrawTag::textHeight, ADrawTag::textL, ADrawTag::textR, ADrawTag::textWidth, TRUE, and w.
SvgInit()
Boolean SvgInit (unsigned int w, unsigned int h, const char * file, struct ADrawTag * outContext)
Definition at line 518 of file mscgen_svg_out.c.
{
    SvgContext *context;
    /* Create context */
    context = outContext->internal = malloc_s(sizeof(SvgContext));
    if(context == NULL)
    {
        return FALSE;
    }
    /* Open the output file */
    if(strcmp(file, "-") == 0)
    {
        context->of = stdout;
    }
    else
    {
        context->of = fopen(file, "wb");
        if(!context->of)
        {
            fprintf(stderr, "SvgInit: Failed to open output file '%s': %s\n", file, strerror(errno));
            return FALSE;
        }
    }
    /* Set the initial pen state */
    SvgSetPen(outContext, ADRAW_COL_BLACK);
    SvgSetBgPen(outContext, ADRAW_COL_WHITE);
    /* Default to small font */
    SvgSetFontSize(outContext, ADRAW_FONT_SMALL);
    fprintf(context->of, "<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\"\n"
                         " \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">\n");
    fprintf(context->of, "<svg version=\"1.1\"\n"
                         " width=\"%upx\" height=\"%upx\"\n"
                         " viewBox=\"0 0 %u %u\"\n"
                         " xmlns=\"http://www.w3.org/2000/svg\" shape-rendering=\"crispEdges\"\n"
                         " stroke-width=\"1\" text-rendering=\"geometricPrecision\">\n",
                         w, h, w, h);
    /* Now fill in the function pointers */
    outContext->line = SvgLine;
    outContext->dottedLine = SvgDottedLine;
    outContext->textL = SvgTextL;
    outContext->textC = SvgTextC;
    outContext->textR = SvgTextR;
    outContext->textWidth = SvgTextWidth;
    outContext->textHeight = SvgTextHeight;
    outContext->filledRectangle = SvgFilledRectangle;
    outContext->filledTriangle = SvgFilledTriangle;
    outContext->filledCircle = SvgFilledCircle;
    outContext->arc = SvgArc;
    outContext->dottedArc = SvgDottedArc;
    outContext->setPen = SvgSetPen;
    outContext->setBgPen = SvgSetBgPen;
    outContext->setFontSize = SvgSetFontSize;
    outContext->close = SvgClose;
    return TRUE;
}
References ADRAW_COL_BLACK, ADRAW_COL_WHITE, ADRAW_FONT_SMALL, ADrawTag::arc, ADrawTag::close, ADrawTag::dottedArc, ADrawTag::dottedLine, errno, FALSE, caseconvert::file, ADrawTag::filledCircle, ADrawTag::filledRectangle, ADrawTag::filledTriangle, Portable::fopen(), h, ADrawTag::internal, ADrawTag::line, malloc_s(), SvgContextTag::of, ADrawTag::setBgPen, ADrawTag::setFontSize, ADrawTag::setPen, strcmp(), SvgArc(), SvgClose(), SvgDottedArc(), SvgDottedLine(), SvgFilledCircle(), SvgFilledRectangle(), SvgFilledTriangle(), SvgLine(), SvgSetBgPen(), SvgSetFontSize(), SvgSetPen(), SvgTextC(), SvgTextHeight(), SvgTextL(), SvgTextR(), SvgTextWidth(), ADrawTag::textC, ADrawTag::textHeight, ADrawTag::textL, ADrawTag::textR, ADrawTag::textWidth, TRUE, and w.