doxygen/libmscgen/mscgen_msc.h File Reference
#include `mscgen_bool.h`
Typedefs
typedef enum MscOptTypeTag MscOptType
typedef enum MscAttribTypeTag MscAttribType
typedef struct MscTag * Msc
typedef struct MscOptTag * MscOpt
typedef struct MscEntityTag * MscEntity
typedef struct MscEntityListTag * MscEntityList
typedef struct MscArcTag * MscArc
typedef struct MscArcListTag * MscArcList
typedef struct MscAttribTag * MscAttrib
Enumerations
enum MscOptTypeTag {
MSC_OPT_HSCALE
, MSC_OPT_WIDTH
, MSC_OPT_ARCGRADIENT
, MSC_OPT_WORDWRAPARCS
,
MSC_OPT_HSCALE
, MSC_OPT_WIDTH
, MSC_OPT_ARCGRADIENT
, MSC_OPT_WORDWRAPARCS
 }
enum MscAttribTypeTag {
MSC_ATTR_LABEL
, MSC_ATTR_ID
, MSC_ATTR_URL
, MSC_ATTR_IDURL
,
MSC_ATTR_LINE_COLOUR
, MSC_ATTR_TEXT_COLOUR
, MSC_ATTR_TEXT_BGCOLOUR
, MSC_ATTR_ARC_LINE_COLOUR
,
MSC_ATTR_ARC_TEXT_COLOUR
, MSC_ATTR_ARC_TEXT_BGCOLOUR
, MSC_ATTR_NO_ARROWS
, MSC_ATTR_BI_ARROWS
,
MSC_ATTR_ARC_SKIP
, MSC_ATTR_LABEL
, MSC_ATTR_ID
, MSC_ATTR_URL
,
MSC_ATTR_IDURL
, MSC_ATTR_LINE_COLOUR
, MSC_ATTR_TEXT_COLOUR
, MSC_ATTR_TEXT_BGCOLOUR
,
MSC_ATTR_ARC_LINE_COLOUR
, MSC_ATTR_ARC_TEXT_COLOUR
, MSC_ATTR_ARC_TEXT_BGCOLOUR
, MSC_ATTR_NO_ARROWS
,
MSC_ATTR_BI_ARROWS
, MSC_ATTR_ARC_SKIP
 }
enum MscArcType {
MSC_ARC_METHOD
, MSC_ARC_RETVAL
, MSC_ARC_SIGNAL
, MSC_ARC_CALLBACK
,
MSC_ARC_DOUBLE
, MSC_ARC_DISCO
, MSC_ARC_DIVIDER
, MSC_ARC_SPACE
,
MSC_ARC_PARALLEL
, MSC_ARC_BOX
, MSC_ARC_ABOX
, MSC_ARC_RBOX
,
MSC_ARC_NOTE
, MSC_ARC_LOSS
, MSC_INVALID_ARC_TYPE
, MSC_ARC_METHOD
,
MSC_ARC_RETVAL
, MSC_ARC_SIGNAL
, MSC_ARC_CALLBACK
, MSC_ARC_DOUBLE
,
MSC_ARC_DISCO
, MSC_ARC_DIVIDER
, MSC_ARC_SPACE
, MSC_ARC_PARALLEL
,
MSC_ARC_BOX
, MSC_ARC_ABOX
, MSC_ARC_RBOX
, MSC_ARC_NOTE
,
MSC_ARC_LOSS
, MSC_INVALID_ARC_TYPE
 }
Functions
Msc MscParse (FILE *in)
MscEntity MscAllocEntity (char *entityName)
MscEntityList MscLinkEntity (MscEntityList list, MscEntity elem)
void MscPrintEntityList (MscEntityList list)
MscOpt MscAllocOpt (MscOptType type, char *value)
MscOpt MscLinkOpt (MscOpt head, MscOpt newHead)
MscArc MscAllocArc (char *srcEntity, char *dstEntity, MscArcType type, unsigned int inputLine)
MscArcList MscLinkArc (MscArcList list, MscArc elem)
void MscPrintArcList (struct MscArcListTag *list)
MscAttrib MscAllocAttrib (MscAttribType type, char *value)
MscAttrib MscLinkAttrib (MscAttrib head, MscAttrib newHead)
void MscArcLinkAttrib (MscArc arc, MscAttrib att)
void MscEntityLinkAttrib (MscEntity ent, MscAttrib att)
void MscPrintAttrib (const struct MscAttribTag *att)
const char * MscPrettyAttribType (MscAttribType t)
Msc MscAlloc (MscOpt optList, MscEntityList entityList, MscArcList arcList)
void MscFree (struct MscTag *m)
void MscPrint (Msc m)
unsigned int MscGetNumEntities (Msc m)
unsigned int MscGetNumArcs (Msc m)
unsigned int MscGetNumParallelArcs (Msc m)
unsigned int MscGetNumOpts (Msc m)
Boolean MscGetOptAsFloat (struct MscTag *m, MscOptType type, float *const f)
Boolean MscGetOptAsBoolean (struct MscTag *m, MscOptType type, Boolean *const b)
int MscGetEntityIndex (struct MscTag *m, const char *label)
void MscResetEntityIterator (Msc m)
Boolean MscNextEntity (struct MscTag *m)
const char * MscGetCurrentEntAttrib (Msc m, MscAttribType a)
const char * MscGetEntAttrib (Msc m, unsigned int entIdx, MscAttribType a)
void MscResetArcIterator (Msc m)
Boolean MscNextArc (struct MscTag *m)
const char * MscGetCurrentArcSource (Msc m)
const char * MscGetCurrentArcDest (Msc m)
MscArcType MscGetCurrentArcType (struct MscTag *m)
const char * MscGetCurrentArcAttrib (Msc m, MscAttribType a)
unsigned int MscGetCurrentArcInputLine (Msc m)
Typedef Documentation
Msc
typedef struct MscTag* Msc
Definition at line 94 of file mscgen_msc.h.
MscArc
typedef struct MscArcTag* MscArc
Definition at line 102 of file mscgen_msc.h.
MscArcList
typedef struct MscArcListTag* MscArcList
Definition at line 104 of file mscgen_msc.h.
MscAttrib
typedef struct MscAttribTag* MscAttrib
Definition at line 106 of file mscgen_msc.h.
MscAttribType
typedef enum MscAttribTypeTag MscAttribType
Arc attributes. An arc may have one or more attributes listed in square brackets after the declaration. This gives an enumerated type for each permissible attribute.
MscEntity
typedef struct MscEntityTag* MscEntity
Definition at line 98 of file mscgen_msc.h.
MscEntityList
typedef struct MscEntityListTag* MscEntityList
Definition at line 100 of file mscgen_msc.h.
MscOpt
typedef struct MscOptTag* MscOpt
Definition at line 96 of file mscgen_msc.h.
MscOptType
typedef enum MscOptTypeTag MscOptType
Msc Options.
Enumeration Type Documentation
MscArcType
enum MscArcType
Enumerator
MSC_ARC_METHOD
MSC_ARC_RETVAL
MSC_ARC_SIGNAL
MSC_ARC_CALLBACK
MSC_ARC_DOUBLE
MSC_ARC_DISCO
MSC_ARC_DIVIDER
MSC_ARC_SPACE
MSC_ARC_PARALLEL
MSC_ARC_BOX
MSC_ARC_ABOX
MSC_ARC_RBOX
MSC_ARC_NOTE
MSC_ARC_LOSS
MSC_INVALID_ARC_TYPE
MSC_ARC_METHOD
MSC_ARC_RETVAL
MSC_ARC_SIGNAL
MSC_ARC_CALLBACK
MSC_ARC_DOUBLE
MSC_ARC_DISCO
MSC_ARC_DIVIDER
MSC_ARC_SPACE
MSC_ARC_PARALLEL
MSC_ARC_BOX
MSC_ARC_ABOX
MSC_ARC_RBOX
MSC_ARC_NOTE
MSC_ARC_LOSS
MSC_INVALID_ARC_TYPE
Definition at line 68 of file mscgen_msc.h.
{
    MSC_ARC_METHOD,
    MSC_ARC_RETVAL,
    MSC_ARC_SIGNAL,
    MSC_ARC_CALLBACK,
    MSC_ARC_DOUBLE,
    MSC_ARC_DISCO, /* ... Discontinuity in time line */
    MSC_ARC_DIVIDER, /* --- Divider */
    MSC_ARC_SPACE, /* ||| */
    MSC_ARC_PARALLEL, /* Comma instead of semicolon */
    MSC_ARC_BOX,
    MSC_ARC_ABOX,
    MSC_ARC_RBOX,
    MSC_ARC_NOTE,
    MSC_ARC_LOSS, /* -x or x- */
    MSC_INVALID_ARC_TYPE
}
MscAttribTypeTag
enum MscAttribTypeTag
Arc attributes. An arc may have one or more attributes listed in square brackets after the declaration. This gives an enumerated type for each permissible attribute.
Enumerator
MSC_ATTR_LABEL
MSC_ATTR_ID
MSC_ATTR_URL
MSC_ATTR_IDURL
MSC_ATTR_LINE_COLOUR
MSC_ATTR_TEXT_COLOUR
MSC_ATTR_TEXT_BGCOLOUR
MSC_ATTR_ARC_LINE_COLOUR
MSC_ATTR_ARC_TEXT_COLOUR
MSC_ATTR_ARC_TEXT_BGCOLOUR
MSC_ATTR_NO_ARROWS
MSC_ATTR_BI_ARROWS
MSC_ATTR_ARC_SKIP
MSC_ATTR_LABEL
MSC_ATTR_ID
MSC_ATTR_URL
MSC_ATTR_IDURL
MSC_ATTR_LINE_COLOUR
MSC_ATTR_TEXT_COLOUR
MSC_ATTR_TEXT_BGCOLOUR
MSC_ATTR_ARC_LINE_COLOUR
MSC_ATTR_ARC_TEXT_COLOUR
MSC_ATTR_ARC_TEXT_BGCOLOUR
MSC_ATTR_NO_ARROWS
MSC_ATTR_BI_ARROWS
MSC_ATTR_ARC_SKIP
Definition at line 49 of file mscgen_msc.h.
{
    MSC_ATTR_LABEL,
    MSC_ATTR_ID,
    MSC_ATTR_URL,
    MSC_ATTR_IDURL,
    MSC_ATTR_LINE_COLOUR,
    MSC_ATTR_TEXT_COLOUR,
    MSC_ATTR_TEXT_BGCOLOUR,
    MSC_ATTR_ARC_LINE_COLOUR,
    MSC_ATTR_ARC_TEXT_COLOUR,
    MSC_ATTR_ARC_TEXT_BGCOLOUR,
    MSC_ATTR_NO_ARROWS,
    MSC_ATTR_BI_ARROWS,
    MSC_ATTR_ARC_SKIP
}
MscOptTypeTag
enum MscOptTypeTag
Msc Options.
Enumerator
MSC_OPT_HSCALE
MSC_OPT_WIDTH
MSC_OPT_ARCGRADIENT
MSC_OPT_WORDWRAPARCS
MSC_OPT_HSCALE
MSC_OPT_WIDTH
MSC_OPT_ARCGRADIENT
MSC_OPT_WORDWRAPARCS
Definition at line 34 of file mscgen_msc.h.
{
    MSC_OPT_HSCALE,
    MSC_OPT_WIDTH,
    MSC_OPT_ARCGRADIENT,
    MSC_OPT_WORDWRAPARCS
}
Function Documentation
MscAlloc()
Msc MscAlloc (MscOpt optList, MscEntityList entityList, MscArcList arcList)
MscAllocArc()
MscArc MscAllocArc (char * srcEntity, char * dstEntity, MscArcType type, unsigned int inputLine)
Definition at line 282 of file mscgen_msc.c.
{
    struct MscArcTag *a = malloc_s(sizeof(struct MscArcTag));
    /* A discontinuity arcs are not between entities */
    if(type == MSC_ARC_DISCO)
    {
        assert(srcEntity == NULL && dstEntity == NULL);
    }
    a->inputLine = inputLine;
    a->src = srcEntity;
    a->dst = dstEntity;
    a->type = type;
    a->next = NULL;
    a->attr = NULL;
    return a;
}
References a, MscArcTag::inputLine, malloc_s(), MSC_ARC_DISCO, and MscArcTag::type.
MscAllocAttrib()
MscAttrib MscAllocAttrib (MscAttribType type, char * value)
Definition at line 369 of file mscgen_msc.c.
{
    struct MscAttribTag *a = malloc_s(sizeof(struct MscAttribTag));
    a->type = type;
    a->value = value;
    a->next = NULL;
    return a;
}
References a, malloc_s(), MscAttribTag::type, and MscAttribTag::value.
MscAllocEntity()
MscEntity MscAllocEntity (char * entityName)
Definition at line 220 of file mscgen_msc.c.
{
    struct MscEntityTag *e = malloc_s(sizeof(struct MscEntityListTag));
    e->label = entityName;
    e->attr = NULL;
    e->next = NULL;
    return e;
}
References e, and malloc_s().
MscAllocOpt()
MscOpt MscAllocOpt (MscOptType type, char * value)
Definition at line 137 of file mscgen_msc.c.
{
    struct MscOptTag *a = malloc_s(sizeof(struct MscOptTag));
    a->type = type;
    a->value = value;
    a->next = NULL;
    return a;
}
References a, malloc_s(), MscOptTag::type, and MscOptTag::value.
MscArcLinkAttrib()
void MscArcLinkAttrib (MscArc arc, MscAttrib att)
MscEntityLinkAttrib()
void MscEntityLinkAttrib (MscEntity ent, MscAttrib att)
MscFree()
void MscFree (struct MscTag * m)
Definition at line 500 of file mscgen_msc.c.
{
    struct MscOptTag *opt = m->optList;
    struct MscEntityTag *entity = m->entityList->head;
    struct MscArcTag *arc = m->arcList->head;
    while(opt)
    {
        struct MscOptTag *next = opt->next;
        free(opt->value);
        free(opt);
        opt = next;
    }
    while(entity)
    {
        struct MscEntityTag *next = entity->next;
        freeAttribList(entity->attr);
        free(entity->label);
        free(entity);
        entity = next;
    }
    while(arc)
    {
        struct MscArcTag *next = arc->next;
        freeAttribList(arc->attr);
        free(arc->dst);
        free(arc->src);
        free(arc);
        arc = next;
    }
    free(m->entityList);
    free(m->arcList);
    free(m);
}
References MscTag::arcList, MscEntityTag::attr, MscArcTag::attr, MscArcTag::dst, MscTag::entityList, freeAttribList(), MscEntityListTag::head, MscArcListTag::head, MscEntityTag::label, MscEntityTag::next, MscArcTag::next, MscOptTag::next, MscTag::optList, MscArcTag::src, and MscOptTag::value.
Referenced by mscgen_generate().
MscGetEntityIndex()
int MscGetEntityIndex (struct MscTag * m, const char * label)
Get the index of some entity. This returns the column index for the entity identified by the passed label.
Parameters
m The MSC to analyse.
label The label to find.
Return values
-1 If the label was not found, otherwise the column index.
Definition at line 586 of file mscgen_msc.c.
{
    struct MscEntityTag *entity = m->entityList->head;
    int c = 0;
    assert(label);
    while(entity != NULL && strcmp(entity->label, label) != 0)
    {
        entity = entity->next;
        c++;
    }
    if(entity == NULL)
    {
        return -1;
    }
    else
    {
        return c;
    }
}
References c, MscTag::entityList, MscEntityListTag::head, MscEntityTag::label, MscEntityTag::next, and strcmp().
Referenced by checkMsc(), computeCanvasSize(), and mscgen_generate().
MscGetNumArcs()
unsigned int MscGetNumArcs (Msc m)
Definition at line 562 of file mscgen_msc.c.
{
    return m->arcList->elements;
}
References MscTag::arcList, and MscArcListTag::elements.
Referenced by computeCanvasSize(), getArcGradient(), mscgen_generate(), and MscPrint().
MscGetNumEntities()
unsigned int MscGetNumEntities (Msc m)
MscGetNumOpts()
unsigned int MscGetNumOpts (Msc m)
Definition at line 572 of file mscgen_msc.c.
{
    struct MscOptTag *elem = m->optList;
    unsigned int count = 0;
    while(elem)
    {
        count++;
        elem = elem->next;
    }
    return count;
}
References MscOptTag::next, and MscTag::optList.
Referenced by MscPrint().
MscGetNumParallelArcs()
unsigned int MscGetNumParallelArcs (Msc m)
Definition at line 567 of file mscgen_msc.c.
{
    return m->arcList->parElements;
}
References MscTag::arcList, and MscArcListTag::parElements.
Referenced by computeCanvasSize(), getArcGradient(), mscgen_generate(), and MscPrint().
MscGetOptAsBoolean()
Boolean MscGetOptAsBoolean (struct MscTag * m, MscOptType type, Boolean *const b)
Get an MSC option, returning the value as a Boolean.
Parameters
 in m The MSC to analyse.
 in type The option type to retrieve.
 in,out b Pointer to be filled with parsed value.
Return values
TRUE If the option was found and parsed successfully, otherwise FALSE in which case *b is unmodified.
Definition at line 772 of file mscgen_msc.c.
{
    struct MscOptTag *opt = MscFindOpt(m->optList, type);
    if(opt != NULL)
    {
        const char *v = opt->value;
        if(strcasecmp(v, "true") == 0 || strcasecmp(v, "yes") == 0 ||
           strcasecmp(v, "on") == 0 || strcasecmp(v, "1") == 0)
        {
            *b = TRUE;
            return TRUE;
        }
        else if(strcasecmp(v, "false") == 0 || strcasecmp(v, "no") == 0 ||
                strcasecmp(v, "off") == 0 || strcasecmp(v, "0") == 0)
        {
            *b = FALSE;
            return TRUE;
        }
        else
        {
            fprintf(stderr, "Warning: Unrecognised boolean option value '%s'. Valid values are 'true',\n"
                            " 'false', 'yes', 'no', 'on', 'off', '1' and '0'.\n",
                            v);
            return FALSE;
        }
    }
    return FALSE;
}
References b, FALSE, MscFindOpt(), MscTag::optList, TRUE, MscOptTag::type, and MscOptTag::value.
Referenced by mscgen_generate().
MscGetOptAsFloat()
Boolean MscGetOptAsFloat (struct MscTag * m, MscOptType type, float *const f)
Get an MSC option, returning the value as a float.
Parameters
 in m The MSC to analyse.
 in type The option type to retrieve.
 in,out f Pointer to be filled with parsed value.
Return values
TRUE If the option was found and parsed successfully.
Definition at line 747 of file mscgen_msc.c.
{
    struct MscOptTag *opt = MscFindOpt(m->optList, type);
    if(opt != NULL)
    {
        *f = (float)atof(opt->value);
        return *f != 0.0f;
    }
    return FALSE;
}
References f, FALSE, MscFindOpt(), MscTag::optList, MscOptTag::type, and MscOptTag::value.
Referenced by mscgen_generate().
MscLinkArc()
MscArcList MscLinkArc (MscArcList list, MscArc elem)
MscLinkAttrib()
MscAttrib MscLinkAttrib (MscAttrib head, MscAttrib newHead)
MscLinkEntity()
MscEntityList MscLinkEntity (MscEntityList list, MscEntity elem)
MscLinkOpt()
MscOpt MscLinkOpt (MscOpt head, MscOpt newHead)
MscParse()
Msc MscParse (FILE * in)
Parse some input to build a message sequence chart. This will parse characters from in and build a message sequence chart ADT.
Return values
Msc The message sequence chart, which may equal NULL is a parse error occurred.
MscPrettyAttribType()
const char * MscPrettyAttribType (MscAttribType t)
Definition at line 456 of file mscgen_msc.c.
{
    switch(t)
    {
        case MSC_ATTR_LABEL: return "label";
        case MSC_ATTR_URL: return "url";
        case MSC_ATTR_ID: return "id";
        case MSC_ATTR_IDURL: return "idurl";
        case MSC_ATTR_LINE_COLOUR: return "linecolour";
        case MSC_ATTR_TEXT_COLOUR: return "textcolour";
        case MSC_ATTR_TEXT_BGCOLOUR: return "textbgcolour";
        case MSC_ATTR_ARC_LINE_COLOUR: return "arclinecolour";
        case MSC_ATTR_ARC_TEXT_COLOUR: return "arctextcolour";
        case MSC_ATTR_ARC_TEXT_BGCOLOUR: return "arctextbgcolour";
        case MSC_ATTR_NO_ARROWS: return "noarrows";
        case MSC_ATTR_BI_ARROWS : return "biarrows";
        default:
            return "<unknown>";
    }
}
References MSC_ATTR_ARC_LINE_COLOUR, MSC_ATTR_ARC_TEXT_BGCOLOUR, MSC_ATTR_ARC_TEXT_COLOUR, MSC_ATTR_BI_ARROWS, MSC_ATTR_ID, MSC_ATTR_IDURL, MSC_ATTR_LABEL, MSC_ATTR_LINE_COLOUR, MSC_ATTR_NO_ARROWS, MSC_ATTR_TEXT_BGCOLOUR, MSC_ATTR_TEXT_COLOUR, and MSC_ATTR_URL.
Referenced by MscPrintAttrib().
MscPrint()
void MscPrint (Msc m)
Print the passed msc in textual form to stdout. This prints a human readable format of the parsed msc to stdout. This is primarily of use in debugging the parser.
MscPrintArcList()
void MscPrintArcList (struct MscArcListTag * list)
Definition at line 348 of file mscgen_msc.c.
{
    struct MscArcTag *elem = list->head;
    while(elem)
    {
        printf("%p: '%s' -> '%s'\n", elem, elem->src, elem->dst);
        MscPrintAttrib(elem->attr);
        elem = elem->next;
    }
}
References MscArcTag::attr, MscArcTag::dst, MscArcListTag::head, MscPrintAttrib(), MscArcTag::next, and MscArcTag::src.
Referenced by MscPrint().
MscPrintAttrib()
void MscPrintAttrib (const struct MscAttribTag * att)
Definition at line 441 of file mscgen_msc.c.
{
    while(att)
    {
        printf(" %s = %s\n", MscPrettyAttribType(att->type), att->value);
        att = att->next;
    }
}
References MscPrettyAttribType(), MscAttribTag::next, MscAttribTag::type, and MscAttribTag::value.
Referenced by MscPrintArcList(), and MscPrintEntityList().
MscPrintEntityList()
void MscPrintEntityList (MscEntityList list)