doxygen/libmscgen/gd_errors.h File Reference
#include <syslog.h>
Macros
#define GD_ERROR LOG_ERR
#define GD_WARNING LOG_WARNING
#define GD_NOTICE LOG_NOTICE
#define GD_INFO LOG_INFO
#define GD_DEBUG LOG_DEBUG
Functions
void gd_error (const char *format,...)
void gd_error_ex (int priority, const char *format,...)
Macro Definition Documentation
GD_DEBUG
#define GD_DEBUG LOG_DEBUG
Definition at line 41 of file gd_errors.h.
GD_ERROR
#define GD_ERROR LOG_ERR
Definition at line 37 of file gd_errors.h.
GD_INFO
#define GD_INFO LOG_INFO
Definition at line 40 of file gd_errors.h.
GD_NOTICE
#define GD_NOTICE LOG_NOTICE
Definition at line 39 of file gd_errors.h.
GD_WARNING
#define GD_WARNING LOG_WARNING
Definition at line 38 of file gd_errors.h.
Function Documentation
gd_error()
void gd_error (const char * format, ...)
Definition at line 110 of file gd.c.
{
    va_list args;
    va_start(args, format);
    _gd_error_ex(GD_WARNING, format, args);
    va_end(args);
}
References _gd_error_ex(), and GD_WARNING.
gd_error_ex()
void gd_error_ex (int priority, const char * format, ...)
Definition at line 118 of file gd.c.
{
    va_list args;
    va_start(args, format);
    _gd_error_ex(priority, format, args);
    va_end(args);
}
References _gd_error_ex().
Referenced by overflow2().