doxygen/libmscgen/gd_lodepng.c File Reference
#include `gd.h`
#include `lodepng.h`
Functions
BGD_DECLARE (void)
Function Documentation
BGD_DECLARE()
BGD_DECLARE (void)
Definition at line 4 of file gd_lodepng.c.
{
  unsigned char *buffer;
  size_t bufferSize;
  int **ptpixels = im->tpixels;
  unsigned char *pixelBuffer = (unsigned char *)malloc(3*im->sx*im->sy);
  unsigned char *pOut = pixelBuffer;
  int x,y;
  for (y=0;y<im->sy;y++)
  {
    int *pThisRow = *ptpixels++;
    for (x=0;x<im->sx;x++)
    {
      int thisPixel = *pThisRow++;
      *pOut++ = gdTrueColorGetRed(thisPixel);
      *pOut++ = gdTrueColorGetGreen(thisPixel);
      *pOut++ = gdTrueColorGetBlue(thisPixel);
    }
  }
  // TODO: convert ptPixels into pixelBuffer...
  LodePNG_Encoder encoder;
  LodePNG_Encoder_init(&encoder);
  encoder.infoPng.color.colorType = 2; // 2=RGB 24 bit
  encoder.infoRaw.color.colorType = 2; // 2=RGB 24 bit
  LodePNG_encode(&encoder, &buffer, &bufferSize, pixelBuffer, im->sx, im->sy);
  // write bufferSize bytes from buffer into outFile
  fwrite(buffer,1,bufferSize,outFile);
  LodePNG_Encoder_cleanup(&encoder);
  free(buffer);
  free(pixelBuffer);
}
References LodePNG_InfoPng::color, LodePNG_InfoRaw::color, LodePNG_InfoColor::colorType, gdTrueColorGetBlue, gdTrueColorGetGreen, gdTrueColorGetRed, LodePNG_Encoder::infoPng, LodePNG_Encoder::infoRaw, LodePNG_encode(), LodePNG_Encoder_cleanup(), LodePNG_Encoder_init(), outFile, gdImageStruct::sx, gdImageStruct::sy, gdImageStruct::tpixels, x, and y.