doxygen/libversion/version.h File Reference
Functions
const char * getDoxygenVersion (void)
const char * getGitVersion (void)
const char * getFullVersion (void)
Function Documentation
getDoxygenVersion()
const char * getDoxygenVersion (void)
Definition at line 3 of file doxyversion.cpp.
{
  static char versionString[] = "1.9.6";
  return versionString;
}
Referenced by MainWindow::about(), ResourceMgr::copyResourceAs(), RTFGenerator::endIndexSection(), generateXML(), getFullVersion(), HtmlGenerator::startFile(), substituteKeywords(), DoxygenContext::Private::version(), Expert::writeConfig(), writeDefaultLayoutFile(), writeDefaultStyleSheet(), RTFGenerator::writeExtensionsFile(), HtmlGenerator::writeExternalSearchPage(), HtmlGenerator::writeFooterFile(), LatexGenerator::writeFooterFile(), LatexGenerator::writeHeaderFile(), HtmlGenerator::writeHeaderFile(), HtmlGenerator::writeLogoAsString(), HtmlGenerator::writeSearchData(), HtmlGenerator::writeSearchPage(), LatexGenerator::writeStyleSheetFile(), RTFGenerator::writeStyleSheetFile(), writeTagFile(), ConfigImpl::writeTemplate(), ConfigImpl::writeXMLDoxyfile(), and writeXMLHeader().
getFullVersion()
const char * getFullVersion (void)
Definition at line 4 of file fullversion.cpp.
{
#define BUF_SIZE 100
  static char fullVersionString[BUF_SIZE];
  static bool init = false;
  if (!init)
  {
    strncpy(fullVersionString,getDoxygenVersion(),BUF_SIZE-1);
    if (strlen(getGitVersion())>0)
    {
      strncat(fullVersionString," (",BUF_SIZE-1);
      strncat(fullVersionString,getGitVersion(),BUF_SIZE-1);
      strncat(fullVersionString,")",BUF_SIZE-1);
    }
    fullVersionString[BUF_SIZE-1]='\0';
    init = true;
  }
  return fullVersionString;
}
References BUF_SIZE, getDoxygenVersion(), getGitVersion(), and Config::init().
Referenced by ConfigImpl::compareDoxyfile(), main(), parseInput(), readConfiguration(), and version().
getGitVersion()
const char * getGitVersion (void)