reg Namespace Reference
Classes
class Ex
class Iterator
class Match
class PToken
class SubMatch
Functions
static bool isspace (char c)
static bool isalpha (char c)
static bool isdigit (char c)
static bool isalnum (char c)
static std::string wildcard2regex (const std::string &pattern)
bool search (const std::string &str, Match &match, const Ex &re, size_t pos)
bool search (const std::string &str, const Ex &re, size_t pos)
bool match (const std::string &str, Match &match, const Ex &re)
bool match (const std::string &str, const Ex &re)
std::string replace (const std::string &str, const Ex &re, const std::string &replacement)
static bool isspace (char c)
static bool isalpha (char c)
static bool isdigit (char c)
static bool isalnum (char c)
static std::string wildcard2regex (const std::string &pattern)
Detailed Description
Namespace for the regular expression functions
Function Documentation
isalnum() [1/2]
static bool reg::isalnum (char c) [inline], [static]
Definition at line 48 of file regex.cpp.
{
  return isalpha(c) || isdigit(c);
}
References c, isalpha(), and isdigit().
Referenced by handleHtmlTag(), isId(), isIdJS(), reg::Ex::Private::matchAt(), and nextUTF8CharPosition().
isalnum() [2/2]
static bool reg::isalnum (char c) [inline], [static]
Definition at line 48 of file regex.cpp.
{
  return isalpha(c) || isdigit(c);
}
References c, isalpha(), and isdigit().
isalpha() [1/2]
static bool reg::isalpha (char c) [inline], [static]
Definition at line 38 of file regex.cpp.
{
  return static_cast<unsigned char>(c)>=128 || (c>='a' && c<='z') || (c>='A' && c<='Z');
}
References c.
Referenced by getNextId(), Portable::isAbsolutePath(), isalnum(), reg::Ex::Private::matchAt(), readConfiguration(), and removeIdsAndMarkers().
isalpha() [2/2]
static bool reg::isalpha (char c) [inline], [static]
Definition at line 38 of file regex.cpp.
{
  return static_cast<unsigned char>(c)>=128 || (c>='a' && c<='z') || (c>='A' && c<='Z');
}
References c.
isdigit() [1/2]
static bool reg::isdigit (char c) [inline], [static]
Definition at line 43 of file regex.cpp.
{
  return c>='0' && c<='9';
}
References c.
Referenced by translator.TrManager::__extractProcessedInfo(), getNextId(), isalnum(), reg::Ex::Private::matchAt(), nextUTF8CharPosition(), removeIdsAndMarkers(), and writeObjCMethodCall().
isdigit() [2/2]
static bool reg::isdigit (char c) [inline], [static]
Definition at line 43 of file regex.cpp.
{
  return c>='0' && c<='9';
}
References c.
isspace() [1/2]
static bool reg::isspace (char c) [inline], [static]
Definition at line 33 of file regex.cpp.
{
  return c==' ' || c=='\t' || c=='\n' || c=='\r';
}
References c.
Referenced by convertToHtml(), metrics::description_is_empty(), MemberDefImpl::displayDefinition(), HtmlCodeGenerator::docify(), HtmlDocVisitor::filter(), HtmlDocVisitor::filterQuotedCdataAttr(), handleHtmlTag(), highlighter(), reg::Ex::Private::matchAt(), DocIncOperator::parse(), metrics.Metrics::print(), processList(), removeIdsAndMarkers(), removeRedundantWhiteSpace(), replaceFunctionMacro(), MemberDefImpl::setInitializer(), splitKnRArg(), splitStringToWidth(), trimQstring(), trimSpaces(), MemberDefImpl::writeDocumentation(), and TextGeneratorHtml::writeString().
isspace() [2/2]
static bool reg::isspace (char c) [inline], [static]
Definition at line 33 of file regex.cpp.
{
  return c==' ' || c=='\t' || c=='\n' || c=='\r';
}
References c.
match() [1/2]
bool reg::match (const std::string & str, const Ex & re)
Matches a given string str for a match against regular expression re. Returns true iff a match was found for the whole string.
Definition at line 765 of file regex.cpp.
{
  Match match;
  return re.match(str,match,0) && match.position()==0 && match.length()==str.length();
}
References match(), and reg::Ex::match().
match() [2/2]
bool reg::match (const std::string & str, Match & match, const Ex & re)
Matches a given string str for a match against regular expression re. Returns true iff a match was found for the whole string. Any capture groups are returned via the match object.
Definition at line 760 of file regex.cpp.
{
  return re.match(str,match,0) && match.position()==0 && match.length()==str.length();
}
References match(), and reg::Ex::match().
Referenced by addIdentifiers(), addToIndices(), addVariableToFile(), DocParser::checkArgumentName(), VHDLOutlineParser::checkInlineCode(), convertCharEntitiesToUTF8(), dateTimeFromString(), MemberDefImpl::displayDefinition(), expandAliasRec(), extractCanonicalType(), extractClassNameFromType(), extractDirection(), extractTitleId(), filterTitle(), findAndRemoveWord(), findFunctionPtr(), findIndex(), findMembersWithSpecificName(), genericPatternMatch(), MemberDefImpl::getClassDefOfAnonymousType(), getDefsOld(), getFilterFromList(), SymbolResolver::Private::getResolvedSymbol(), getTemplateArgumentsInName(), DocParser::handleStyleArgument(), FormulaManager::initFromRepository(), initPredefined(), insertDimension(), VhdlDocGen::isNumber(), isVarWithConstructor(), linkifyText(), loadExtensions(), loadStylesheet(), match(), matchArguments2(), matchExcludedSymbols(), normalizeNonTemplateArgumentsInString(), MarkdownOutlineParser::parseInput(), processConcatOperators(), removeAnonymousScopes(), TemplateNodeMarkers::render(), replace(), replaceColorMarkers(), runQHelpGenerator(), search(), StyleData::setStyle(), simplifyTypeForTable(), split(), splitKnRArg(), StyleData::StyleData(), substEnvVarsInString(), substituteTemplateArgumentsInString(), substituteTemplatesInString(), DotAttributes::updateValue(), MemberDefImpl::writeDeclaration(), MemberDefImpl::writeDocumentation(), and writeMarkerList().
replace()
std::string reg::replace (const std::string & str, const Ex & re, const std::string & replacement)
Searching in a given input string for parts that match regular expression re and replaces those parts by string replacement.
Definition at line 771 of file regex.cpp.
{
  std::string result;
  Match match;
  size_t p=0;
  while (re.match(str,match,p))
  {
    size_t i=match.position();
    size_t l=match.length();
    if (i>p) result+=str.substr(p,i-p);
    result+=replacement;
    p=i+l;
  }
  if (p<str.length()) result+=str.substr(p);
  return result;
}
References match(), reg::Ex::match(), p, and string.
Referenced by VhdlDocGen::addBaseClass(), VHDLOutlineParser::checkInlineCode(), cleanUpPaths(), correctPath(), FileInfo::correctPath(), FlowChart::printNode(), replaceAnonymousScopes(), Expert::showHelp(), substEnvVarsInString(), substitute(), and TemplateNodeText::TemplateNodeText().
search() [1/2]
bool reg::search (const std::string & str, const Ex & re, size_t pos = 0)
Search in a given string str starting at position pos for a match against regular expression re. Returns true iff a match was found.
Definition at line 754 of file regex.cpp.
{
  Match match;
  return re.match(str,match,pos);
}
References match(), and reg::Ex::match().
search() [2/2]
bool reg::search (const std::string & str, Match & match, const Ex & re, size_t pos = 0)
Search in a given string str starting at position pos for a match against regular expression re. Returns true iff a match was found. Details of what part of the string has matched is returned via the match object.
An example to show how to match all identifiers in a string.
static reg::Ex re(R"(\a\w*)");
std::string = u8"void(Func是<B_C::Códe42>(42));";
while (reg::search(str,match,re,pos))
{
  std::cout << match.str() << std::endl;
  pos=match.position()+match.length();
}
 produces:
void
Func是
B_C
Códe42
See also
Ex::Ex() for details on the regular expression patterns.
Definition at line 749 of file regex.cpp.
{
  return re.match(str,match,pos);
}
References match(), and reg::Ex::match().
Referenced by HtmlHelpIndex::addItem(), addVariableToFile(), Config::checkAndCorrect(), VHDLOutlineParser::checkInlineCode(), containsEnvVar(), MemberDefImpl::displayDefinition(), expandAliasRec(), extractTitleId(), findFunctionPtr(), findIndex(), MemberDefImpl::getClassDefOfAnonymousType(), FormulaManager::initFromRepository(), insertDimension(), isVarWithConstructor(), loadExtensions(), loadStylesheet(), matchExcludedSymbols(), MarkdownOutlineParser::parseInput(), search::re_fn(), runQHelpGenerator(), StyleData::setStyle(), simplifyTypeForTable(), splitKnRArg(), StyleData::StyleData(), DotAttributes::updateValue(), MemberDefImpl::writeDeclaration(), and MemberDefImpl::writeDocumentation().
wildcard2regex() [1/2]
static std::string reg::wildcard2regex (const std::string & pattern) [static]
Definition at line 648 of file regex.cpp.
{
  std::string result="^"; // match start of input
  char c;
  const char *p = pattern.c_str();
  while ((c=*p++))
  {
    switch(c)
    {
      case '*':
        result+=".*";
        break; // '*' => '.*'
      case '?':
        result+='.';
        break; // '?' => '.'
      case '.':
      case '+':
      case '\\':
      case '$':
      case '^':
      case '(':
      case ')':
         result+='\\'; result+=c; // escape
         break;
      case '[':
         if (*p=='^') // don't escape ^ after [
         {
           result+="[^";
           p++;
         }
         else
         {
           result+=c;
         }
        break;
      default: // just copy
        result+=c;
        break;
    }
  }
  result+='$'; // match end of input
  return result;
}
References c, reg::Ex::p, and string.
wildcard2regex() [2/2]
static std::string reg::wildcard2regex (const std::string & pattern) [static]
Definition at line 648 of file regex.cpp.
{
  std::string result="^"; // match start of input
  char c;
  const char *p = pattern.c_str();
  while ((c=*p++))
  {
    switch(c)
    {
      case '*':
        result+=".*";
        break; // '*' => '.*'
      case '?':
        result+='.';
        break; // '?' => '.'
      case '.':
      case '+':
      case '\\':
      case '$':
      case '^':
      case '(':
      case ')':
         result+='\\'; result+=c; // escape
         break;
      case '[':
         if (*p=='^') // don't escape ^ after [
         {
           result+="[^";
           p++;
         }
         else
         {
           result+=c;
         }
        break;
      default: // just copy
        result+=c;
        break;
    }
  }
  result+='$'; // match end of input
  return result;
}
References c, reg::Ex::p, and string.