search Namespace Reference
Classes
class Finder
class MemberType
class RequestType
Functions
def re_fn (expr, item)
def openDb (dbname)
def process (f, kind)
def processHref (cn, ref)
def serveCgi ()
def usage ()
def serveCli (argv)
def main (argv)
Function Documentation
main()
def search.main (argv)
Definition at line 390 of file search.py.
def main(argv):
    if 'REQUEST_METHOD' in os.environ:
        serveCgi()
    else:
        serveCli(argv)
References main(), serveCgi(), and serveCli().
Referenced by main(), and search.Finder.subClasses().
openDb()
def search.openDb (dbname)
Definition at line 51 of file search.py.
def openDb(dbname):
    if dbname == None:
        dbname = "doxygen_sqlite3.db"
    if not os.path.isfile(dbname):
        raise BaseException("No such file %s" % dbname)
    conn = sqlite3.connect(dbname)
    conn.execute('PRAGMA temp_store = MEMORY;')
    conn.row_factory = sqlite3.Row
    conn.create_function("REGEXP", 2, re_fn)
    return conn
Referenced by serveCgi(), serveCli(), and search.Finder.subClasses().
process()
def search.process (f, kind)
Definition at line 255 of file search.py.
def process(f,kind):
    request_processors = {
        MemberType.Function: f.function,
        MemberType.File: f.file,
        MemberType.Define: f.macro,
        MemberType.Variable: f.variable,
        MemberType.Typedef: f.typedef,
        RequestType.References: f.references,
        RequestType.Struct: f.struct,
        RequestType.Includers: f.includers,
        RequestType.Includees: f.includees,
        RequestType.Members: f.members,
        RequestType.BaseClasses: f.baseClasses,
        RequestType.SubClasses: f.subClasses
    }
    return request_processors[kind]()
Referenced by ClassDefImpl.countInheritedDecMembers(), processHref(), serveCli(), search.Finder.subClasses(), and ClassDefImpl.writeInheritedMemberDeclarations().
processHref()
def search.processHref (cn, ref)
Definition at line 274 of file search.py.
def processHref(cn,ref):
    j={}
    # is it in memberdef ?
    table="memberdef"
    if (cn.execute("SELECT count(*) from %s WHERE rowid=?"%table,[ref]).fetchone()[0] > 0):
        for r in cn.execute("SELECT kind,rowid FROM %s WHERE rowid=?" % table,[ref]).fetchall():
            f=Finder(cn,r['rowid'],int)
            j=process(f,str(r['kind']))
    # is it in compounddef ?
    table="compounddef"
    if (cn.execute("SELECT count(*) from %s WHERE rowid=?"%table,[ref]).fetchone()[0] > 0):
        for r in cn.execute("SELECT rowid FROM %s WHERE rowid=?"%table,[ref]).fetchall():
            f=Finder(cn,r[0],int)
            j=process(f,RequestType.Struct)
    return j
References process().
Referenced by serveCgi(), serveCli(), and search.Finder.subClasses().
re_fn()
def search.re_fn (expr, item)
Definition at line 47 of file search.py.
def re_fn(expr, item):
    reg = re.compile(expr, re.I)
    return reg.search(item) is not None
References reg.search().
serveCgi()
def search.serveCgi ()
Definition at line 293 of file search.py.
def serveCgi():
    import cgi
    print('Content-Type: application/json\n')
    fieldStorage = cgi.FieldStorage()
    form = dict((key, fieldStorage.getvalue(key)) for key in fieldStorage.keys())
    if 'href' in form:
        ref = form['href']
    else:
        print('{"result": null, "error": "no refid given"}')
        sys.exit(0)
    cn=openDb('doxygen_sqlite3.db')
    j = processHref(cn,ref)
    print(json.dumps({"result":j,"error":None}))
References openDb(), print(), and processHref().
Referenced by main(), and search.Finder.subClasses().
serveCli()
def search.serveCli (argv)
Definition at line 331 of file search.py.
def serveCli(argv):
    try:
        opts, args = getopt.getopt(argv, "hr:RI:i:d:f:m:t:v:H:M:B:S:F:",["help"])
    except getopt.GetoptError:
        usage()
        sys.exit(1)
    ref=None
    dbname=None
    j={}
    global g_use_regexp
    for a, o in opts:
        if a in ('-h', '--help'):
            usage()
            sys.exit(0)
        elif a in ('-d'):
            dbname=o
            continue
        elif a in ('-r'):
            kind=RequestType.References
        elif a in ('-R'):
            g_use_regexp=True
            continue
        elif a in ('-I'):
            kind=RequestType.Includers
        elif a in ('-i'):
            kind=RequestType.Includees
        elif a in ('-M'):
            kind=RequestType.Members
        elif a in ('-B'):
            kind=RequestType.BaseClasses
        elif a in ('-S'):
            kind=RequestType.SubClasses
        elif a in ('-f'):
            kind=MemberType.Function
        elif a in ('-F'):
            # undocumented
            # seems to fit with the lower case "search" patterns?
            kind=MemberType.File
        elif a in ('-m'):
            kind=MemberType.Define
        elif a in ('-t'):
            kind=MemberType.Typedef
        elif a in ('-v'):
            kind=MemberType.Variable
        elif a in ('-H'):
            # undocumented
            ref = o
        cn=openDb(dbname)
        f=Finder(cn,o)
        if ref != None:
            j=processHref(cn,ref)
        else:
            j=process(f,kind)
        print(json.dumps(j,indent=4))
References openDb(), print(), process(), processHref(), and usage().
Referenced by main(), and search.Finder.subClasses().
usage()
def search.usage ()
Definition at line 313 of file search.py.
def usage():
    sys.stderr.write("""Usage: search.py [Options]
Options:
    -h, --help
    -d <D> Use database <D> for queries.
    -f <F> Search for definition of function <F>.
    -m <M> Search for definition of macro <M>.
    -r <F> Search for references to function <F>.
    -t <T> Search for definition of type <T>.
    -v <V> Search for definition of variable <V>.
    -I <I> What files are including <I>.
    -i <i> What files are included by <i>.
    -B <C> Get the base classes of class <C>.
    -M <C> Get all members of class <C>.
    -S <C> Get the sub classes of class <C>.
    -R Consider the search <term> to be a regex.
""")
Referenced by serveCli(), and search.Finder.subClasses().