ghc::filesystem::detail Namespace Reference
Typedefs
template<typename Enum >
using EnableBitmask = typename std::enable_if< std::is_same< Enum, perms >::value||std::is_same< Enum, perm_options >::value||std::is_same< Enum, copy_options >::value||std::is_same< Enum, directory_options >::value, Enum >::type
Enumerations
enum utf8_states_t { S_STRT = 0
, S_RJCT = 8
, S_STRT = 0
, S_RJCT = 8
 }
enum class portable_error {
none = 0
, exists
, not_found
, not_supported
,
not_implemented
, invalid_argument
, is_a_directory
, none = 0
,
exists
, not_found
, not_supported
, not_implemented
,
invalid_argument
, is_a_directory
 }
enum utf8_states_t { S_STRT = 0
, S_RJCT = 8
, S_STRT = 0
, S_RJCT = 8
 }
enum class portable_error {
none = 0
, exists
, not_found
, not_supported
,
not_implemented
, invalid_argument
, is_a_directory
, none = 0
,
exists
, not_found
, not_supported
, not_implemented
,
invalid_argument
, is_a_directory
 }
Functions
GHC_FS_API void appendUTF8 (std::string &str, uint32_t unicode)
GHC_FS_API bool is_surrogate (uint32_t c)
GHC_FS_API bool is_high_surrogate (uint32_t c)
GHC_FS_API bool is_low_surrogate (uint32_t c)
GHC_FS_API unsigned consumeUtf8Fragment (const unsigned state, const uint8_t fragment, uint32_t &codepoint)
GHC_FS_API std::error_code make_error_code (portable_error err)
GHC_FS_API std::error_code make_system_error (int err=0)
GHC_INLINE bool in_range (uint32_t c, uint32_t lo, uint32_t hi)
GHC_INLINE bool validUtf8 (const std::string &utf8String)
template<class StringType , class Utf8String , typename std::enable_if< path::_is_basic_string< Utf8String >::value &&(sizeof(typename Utf8String::value_type)==1) &&(sizeof(typename StringType::value_type)==1)>::type * = nullptr>
StringType fromUtf8 (const Utf8String &utf8String, const typename StringType::allocator_type &alloc=typename StringType::allocator_type())
template<class StringType , typename charT , std::size_t N>
StringType fromUtf8 (const charT(&utf8String)[N])
template<typename strT , typename std::enable_if< path::_is_basic_string< strT >::value &&(sizeof(typename strT::value_type)==1), int >::type size = 1>
std::string toUtf8 (const strT &unicodeString)
template<typename charT >
std::string toUtf8 (const charT *unicodeString)
template<typename strT , typename std::enable_if< path::_is_basic_string< strT >::value, bool >::type = true>
GHC_INLINE bool startsWith (const strT &what, const strT &with)
template<typename strT , typename std::enable_if< path::_is_basic_string< strT >::value, bool >::type = true>
GHC_INLINE bool endsWith (const strT &what, const strT &with)
GHC_INLINE bool equals_simple_insensitive (const path::value_type *str1, const path::value_type *str2)
GHC_INLINE int compare_simple_insensitive (const path::value_type *str1, size_t len1, const path::value_type *str2, size_t len2)
GHC_INLINE const char * strerror_adapter (char *gnu, char *)
GHC_INLINE const char * strerror_adapter (int posix, char *buffer)
template<typename ErrorNumber >
GHC_INLINE std::string systemErrorText (ErrorNumber code=0)
GHC_INLINE void create_symlink (const path &target_name, const path &new_symlink, bool, std::error_code &ec)
GHC_INLINE void create_hardlink (const path &target_name, const path &new_hardlink, std::error_code &ec)
template<typename T >
GHC_INLINE file_status file_status_from_st_mode (T mode)
GHC_INLINE path resolveSymlink (const path &p, std::error_code &ec)
GHC_INLINE bool is_not_found_error (std::error_code &ec)
GHC_INLINE file_status symlink_status_ex (const path &p, std::error_code &ec, uintmax_t *sz=nullptr, uintmax_t *nhl=nullptr, time_t *lwt=nullptr) noexcept
GHC_INLINE file_status status_ex (const path &p, std::error_code &ec, file_status *sls=nullptr, uintmax_t *sz=nullptr, uintmax_t *nhl=nullptr, time_t *lwt=nullptr, int recurse_count=0) noexcept
Typedef Documentation
EnableBitmask
template<typename Enum >
using ghc::filesystem::detail::EnableBitmask = typedef typename std::enable_if<std::is_same<Enum, perms>::value || std::is_same<Enum, perm_options>::value || std::is_same<Enum, copy_options>::value || std::is_same<Enum, directory_options>::value, Enum>::type
Definition at line 1367 of file filesystem.hpp.
Enumeration Type Documentation
portable_error [1/2]
enum class ghc::filesystem::detail::portable_error [strong]
Enumerator
none
exists
not_found
not_supported
not_implemented
invalid_argument
is_a_directory
none
exists
not_found
not_supported
not_implemented
invalid_argument
is_a_directory
Definition at line 1287 of file filesystem.hpp.
                          {
    none = 0,
    exists,
    not_found,
    not_supported,
    not_implemented,
    invalid_argument,
    is_a_directory,
};
portable_error [2/2]
enum class ghc::filesystem::detail::portable_error [strong]
Enumerator
none
exists
not_found
not_supported
not_implemented
invalid_argument
is_a_directory
none
exists
not_found
not_supported
not_implemented
invalid_argument
is_a_directory
Definition at line 1287 of file filesystem.hpp.
                          {
    none = 0,
    exists,
    not_found,
    not_supported,
    not_implemented,
    invalid_argument,
    is_a_directory,
};
utf8_states_t [1/2]
enum ghc::filesystem::detail::utf8_states_t
Enumerator
S_STRT
S_RJCT
S_STRT
S_RJCT
Definition at line 1281 of file filesystem.hpp.
{ S_STRT = 0, S_RJCT = 8 };
utf8_states_t [2/2]
enum ghc::filesystem::detail::utf8_states_t
Enumerator
S_STRT
S_RJCT
S_STRT
S_RJCT
Definition at line 1281 of file filesystem.hpp.
{ S_STRT = 0, S_RJCT = 8 };
Function Documentation
appendUTF8()
GHC_INLINE void ghc::filesystem::detail::appendUTF8 (std::string & str, uint32_t unicode)
Definition at line 1443 of file filesystem.hpp.
{
    if (unicode <= 0x7f) {
        str.push_back(static_cast<char>(unicode));
    }
    else if (unicode >= 0x80 && unicode <= 0x7ff) {
        str.push_back(static_cast<char>((unicode >> 6) + 192));
        str.push_back(static_cast<char>((unicode & 0x3f) + 128));
    }
    else if ((unicode >= 0x800 && unicode <= 0xd7ff) || (unicode >= 0xe000 && unicode <= 0xffff)) {
        str.push_back(static_cast<char>((unicode >> 12) + 224));
        str.push_back(static_cast<char>(((unicode & 0xfff) >> 6) + 128));
        str.push_back(static_cast<char>((unicode & 0x3f) + 128));
    }
    else if (unicode >= 0x10000 && unicode <= 0x10ffff) {
        str.push_back(static_cast<char>((unicode >> 18) + 240));
        str.push_back(static_cast<char>(((unicode & 0x3ffff) >> 12) + 128));
        str.push_back(static_cast<char>(((unicode & 0xfff) >> 6) + 128));
        str.push_back(static_cast<char>((unicode & 0x3f) + 128));
    }
    else {
#ifdef GHC_RAISE_UNICODE_ERRORS
        throw filesystem_error("Illegal code point for unicode character.", str, std::make_error_code(std::errc::illegal_byte_sequence));
#else
        appendUTF8(str, 0xfffd);
#endif
    }
}
References appendUTF8(), and make_error_code().
Referenced by appendUTF8().
compare_simple_insensitive()
GHC_INLINE int ghc::filesystem::detail::compare_simple_insensitive (const path::value_type * str1, size_t len1, const path::value_type * str2, size_t len2)
Definition at line 1833 of file filesystem.hpp.
{
    while (len1 > 0 && len2 > 0 && ::tolower(static_cast<unsigned char>(*str1)) == ::tolower(static_cast<unsigned char>(*str2))) {
        --len1;
        --len2;
        ++str1;
        ++str2;
    }
    if (len1 && len2) {
        return *str1 < *str2 ? -1 : 1;
    }
    if (len1 == 0 && len2 == 0) {
        return 0;
    }
    return len1 == 0 ? -1 : 1;
}
References caseconvert::tolower.
Referenced by ghc::filesystem::path::compare().
consumeUtf8Fragment()
GHC_INLINE unsigned ghc::filesystem::detail::consumeUtf8Fragment (const unsigned state, const uint8_t fragment, uint32_t & codepoint)
Definition at line 1475 of file filesystem.hpp.
{
    static const uint32_t utf8_state_info[] = {
        // encoded states
        0x11111111u, 0x11111111u, 0x77777777u, 0x77777777u, 0x88888888u, 0x88888888u, 0x88888888u, 0x88888888u, 0x22222299u, 0x22222222u, 0x22222222u, 0x22222222u, 0x3333333au, 0x33433333u, 0x9995666bu, 0x99999999u,
        0x88888880u, 0x22818108u, 0x88888881u, 0x88888882u, 0x88888884u, 0x88888887u, 0x88888886u, 0x82218108u, 0x82281108u, 0x88888888u, 0x88888883u, 0x88888885u, 0u, 0u, 0u, 0u,
    };
    uint8_t category = fragment < 128 ? 0 : (utf8_state_info[(fragment >> 3) & 0xf] >> ((fragment & 7) << 2)) & 0xf;
    codepoint = (state ? (codepoint << 6) | (fragment & 0x3fu) : (0xffu >> category) & fragment);
    return state == S_RJCT ? static_cast<unsigned>(S_RJCT) : static_cast<unsigned>((utf8_state_info[category + 16] >> (state << 2)) & 0xf);
}
References S_RJCT.
Referenced by validUtf8().
create_hardlink()
GHC_INLINE void ghc::filesystem::detail::create_hardlink (const path & target_name, const path & new_hardlink, std::error_code & ec)
Definition at line 1956 of file filesystem.hpp.
{
    if (::link(target_name.c_str(), new_hardlink.c_str()) != 0) {
        ec = detail::make_system_error();
    }
}
References ghc::filesystem::path::c_str(), and make_system_error().
Referenced by ghc::filesystem::create_hard_link().
create_symlink()
GHC_INLINE void ghc::filesystem::detail::create_symlink (const path & target_name, const path & new_symlink, bool , std::error_code & ec)
Definition at line 1948 of file filesystem.hpp.
{
    if (::symlink(target_name.c_str(), new_symlink.c_str()) != 0) {
        ec = detail::make_system_error();
    }
}
References ghc::filesystem::path::c_str(), and make_system_error().
Referenced by ghc::filesystem::create_directory_symlink(), and ghc::filesystem::create_symlink().
endsWith()
template<typename strT , typename std::enable_if< path::_is_basic_string< strT >::value, bool >::type = true>
GHC_INLINE bool ghc::filesystem::detail::endsWith (const strT & what, const strT & with)
Definition at line 1717 of file filesystem.hpp.
{
    return with.length() <= what.length() && what.compare(what.length() - with.length(), with.size(), with) == 0;
}
Referenced by resolveSymlink().
equals_simple_insensitive()
GHC_INLINE bool ghc::filesystem::detail::equals_simple_insensitive (const path::value_type * str1, const path::value_type * str2)
Definition at line 1812 of file filesystem.hpp.
{
#ifdef GHC_OS_WINDOWS
#ifdef __GNUC__
    while (::tolower((unsigned char)*str1) == ::tolower((unsigned char)*str2++)) {
        if (*str1++ == 0)
            return true;
    }
    return false;
#else // __GNUC__
#ifdef GHC_USE_WCHAR_T
    return 0 == ::_wcsicmp(str1, str2);
#else // GHC_USE_WCHAR_T
    return 0 == ::_stricmp(str1, str2);
#endif // GHC_USE_WCHAR_T
#endif // __GNUC__
#else // GHC_OS_WINDOWS
    return 0 == ::strcasecmp(str1, str2);
#endif // GHC_OS_WINDOWS
}
References caseconvert::tolower.
Referenced by ghc::filesystem::u8arguments::u8arguments().
file_status_from_st_mode()
template<typename T >
GHC_INLINE file_status ghc::filesystem::detail::file_status_from_st_mode (T mode)
Definition at line 1966 of file filesystem.hpp.
{
#ifdef GHC_OS_WINDOWS
    file_type ft = file_type::unknown;
    if ((mode & _S_IFDIR) == _S_IFDIR) {
        ft = file_type::directory;
    }
    else if ((mode & _S_IFREG) == _S_IFREG) {
        ft = file_type::regular;
    }
    else if ((mode & _S_IFCHR) == _S_IFCHR) {
        ft = file_type::character;
    }
    perms prms = static_cast<perms>(mode & 0xfff);
    return file_status(ft, prms);
#else
    file_type ft = file_type::unknown;
    if (S_ISDIR(mode)) {
        ft = file_type::directory;
    }
    else if (S_ISREG(mode)) {
        ft = file_type::regular;
    }
    else if (S_ISCHR(mode)) {
        ft = file_type::character;
    }
    else if (S_ISBLK(mode)) {
        ft = file_type::block;
    }
    else if (S_ISFIFO(mode)) {
        ft = file_type::fifo;
    }
    else if (S_ISLNK(mode)) {
        ft = file_type::symlink;
    }
    else if (S_ISSOCK(mode)) {
        ft = file_type::socket;
    }
    perms prms = static_cast<perms>(mode & 0xfff);
    return file_status(ft, prms);
#endif
}
References ghc::filesystem::block, ghc::filesystem::character, ghc::filesystem::directory, ghc::filesystem::fifo, mode, ghc::filesystem::regular, ghc::filesystem::socket, ghc::filesystem::symlink, and ghc::filesystem::unknown.
Referenced by status_ex(), and symlink_status_ex().
fromUtf8() [1/2]
template<class StringType , typename charT , std::size_t N>
StringType ghc::filesystem::detail::fromUtf8 (const charT(&) utf8String[N]) [inline]
Definition at line 1589 of file filesystem.hpp.
{
#ifdef GHC_WITH_STRING_VIEW
    return fromUtf8<StringType>(basic_string_view<charT>(utf8String, N - 1));
#else
    return fromUtf8<StringType>(std::basic_string<charT>(utf8String, N - 1));
#endif
}
fromUtf8() [2/2]
template<class StringType , class Utf8String , typename std::enable_if< path::_is_basic_string< Utf8String >::value &&(sizeof(typename Utf8String::value_type)==1) &&(sizeof(typename StringType::value_type)==1)>::type * = nullptr>
StringType ghc::filesystem::detail::fromUtf8 (const Utf8String & utf8String, const typename StringType::allocator_type & alloc = typename StringType::allocator_type()) [inline]
Definition at line 1510 of file filesystem.hpp.
{
    return StringType(utf8String.begin(), utf8String.end(), alloc);
}
Referenced by MainWindow::readStdout().
in_range()
GHC_INLINE bool ghc::filesystem::detail::in_range (uint32_t c, uint32_t lo, uint32_t hi)
Definition at line 1423 of file filesystem.hpp.
{
    return (static_cast<uint32_t>(c - lo) < (hi - lo + 1));
}
References c.
Referenced by is_surrogate().
is_high_surrogate()
GHC_INLINE bool ghc::filesystem::detail::is_high_surrogate (uint32_t c)
Definition at line 1433 of file filesystem.hpp.
{
    return (c & 0xfffffc00) == 0xd800;
}
References c.
is_low_surrogate()
GHC_INLINE bool ghc::filesystem::detail::is_low_surrogate (uint32_t c)
Definition at line 1438 of file filesystem.hpp.
{
    return (c & 0xfffffc00) == 0xdc00;
}
References c.
is_not_found_error()
GHC_INLINE bool ghc::filesystem::detail::is_not_found_error (std::error_code & ec)
Definition at line 2201 of file filesystem.hpp.
{
#ifdef GHC_OS_WINDOWS
    return ec.value() == ERROR_FILE_NOT_FOUND || ec.value() == ERROR_PATH_NOT_FOUND || ec.value() == ERROR_INVALID_NAME;
#else
    return ec.value() == ENOENT || ec.value() == ENOTDIR;
#endif
}
Referenced by ghc::filesystem::recursive_directory_iterator::increment(), ghc::filesystem::remove_all(), status_ex(), and symlink_status_ex().
is_surrogate()
GHC_INLINE bool ghc::filesystem::detail::is_surrogate (uint32_t c)
Definition at line 1428 of file filesystem.hpp.
{
    return in_range(c, 0xd800, 0xdfff);
}
References c, and in_range().
make_error_code()
GHC_INLINE std::error_code ghc::filesystem::detail::make_error_code (portable_error err)
Definition at line 1308 of file filesystem.hpp.
{
#ifdef GHC_OS_WINDOWS
    switch (err) {
        case portable_error::none:
            return std::error_code();
        case portable_error::exists:
            return std::error_code(ERROR_ALREADY_EXISTS, std::system_category());
        case portable_error::not_found:
            return std::error_code(ERROR_PATH_NOT_FOUND, std::system_category());
        case portable_error::not_supported:
            return std::error_code(ERROR_NOT_SUPPORTED, std::system_category());
        case portable_error::not_implemented:
            return std::error_code(ERROR_CALL_NOT_IMPLEMENTED, std::system_category());
        case portable_error::invalid_argument:
            return std::error_code(ERROR_INVALID_PARAMETER, std::system_category());
        case portable_error::is_a_directory:
#ifdef ERROR_DIRECTORY_NOT_SUPPORTED
            return std::error_code(ERROR_DIRECTORY_NOT_SUPPORTED, std::system_category());
#else
            return std::error_code(ERROR_NOT_SUPPORTED, std::system_category());
#endif
    }
#else
    switch (err) {
        case portable_error::none:
            return std::error_code();
        case portable_error::exists:
            return std::error_code(EEXIST, std::system_category());
        case portable_error::not_found:
            return std::error_code(ENOENT, std::system_category());
        case portable_error::not_supported:
            return std::error_code(ENOTSUP, std::system_category());
        case portable_error::not_implemented:
            return std::error_code(ENOSYS, std::system_category());
        case portable_error::invalid_argument:
            return std::error_code(EINVAL, std::system_category());
        case portable_error::is_a_directory:
            return std::error_code(EISDIR, std::system_category());
    }
#endif
    return std::error_code();
}
References err(), exists, invalid_argument, is_a_directory, none, not_found, not_implemented, and not_supported.
Referenced by appendUTF8(), ghc::filesystem::copy(), ghc::filesystem::copy_file(), ghc::filesystem::create_directories(), ghc::filesystem::hard_link_count(), ghc::filesystem::permissions(), ghc::filesystem::path::postprocess_path_with_format(), ghc::filesystem::read_symlink(), and ghc::filesystem::remove_all().
make_system_error()
GHC_INLINE std::error_code ghc::filesystem::detail::make_system_error (int err = 0)
Definition at line 1358 of file filesystem.hpp.
{
    return std::error_code(err ? err : errno, std::system_category());
}
References err(), and errno.
Referenced by ghc::filesystem::absolute(), ghc::filesystem::copy_file(), ghc::filesystem::create_directory(), create_hardlink(), create_symlink(), ghc::filesystem::current_path(), ghc::filesystem::equivalent(), ghc::filesystem::file_size(), ghc::filesystem::hard_link_count(), ghc::filesystem::directory_iterator::impl::impl(), ghc::filesystem::directory_iterator::impl::increment(), ghc::filesystem::last_write_time(), ghc::filesystem::permissions(), ghc::filesystem::remove(), ghc::filesystem::rename(), ghc::filesystem::resize_file(), resolveSymlink(), ghc::filesystem::space(), status_ex(), symlink_status_ex(), and ghc::filesystem::temp_directory_path().
resolveSymlink()
GHC_INLINE path ghc::filesystem::detail::resolveSymlink (const path & p, std::error_code & ec)
Definition at line 2066 of file filesystem.hpp.
{
#ifdef GHC_OS_WINDOWS
    path result;
    auto reparseData = detail::getReparseData(p, ec);
    if (!ec) {
        if (reparseData && IsReparseTagMicrosoft(reparseData->ReparseTag)) {
            switch (reparseData->ReparseTag) {
                case IO_REPARSE_TAG_SYMLINK: {
                    auto printName = std::wstring(&reparseData->SymbolicLinkReparseBuffer.PathBuffer[reparseData->SymbolicLinkReparseBuffer.PrintNameOffset / sizeof(WCHAR)], reparseData->SymbolicLinkReparseBuffer.PrintNameLength / sizeof(WCHAR));
                    auto substituteName =
                        std::wstring(&reparseData->SymbolicLinkReparseBuffer.PathBuffer[reparseData->SymbolicLinkReparseBuffer.SubstituteNameOffset / sizeof(WCHAR)], reparseData->SymbolicLinkReparseBuffer.SubstituteNameLength / sizeof(WCHAR));
                    if (detail::endsWith(substituteName, printName) && detail::startsWith(substituteName, std::wstring(L"\\??\\"))) {
                        result = printName;
                    }
                    else {
                        result = substituteName;
                    }
                    if (reparseData->SymbolicLinkReparseBuffer.Flags & 0x1 /*SYMLINK_FLAG_RELATIVE*/) {
                        result = p.parent_path() / result;
                    }
                    break;
                }
                case IO_REPARSE_TAG_MOUNT_POINT:
                    result = detail::getFullPathName(GHC_NATIVEWP(p), ec);
                    //result = std::wstring(&reparseData->MountPointReparseBuffer.PathBuffer[reparseData->MountPointReparseBuffer.SubstituteNameOffset / sizeof(WCHAR)], reparseData->MountPointReparseBuffer.SubstituteNameLength / sizeof(WCHAR));
                    break;
                default:
                    break;
            }
        }
    }
    return result;
#else
    size_t bufferSize = 256;
    while (true) {
        std::vector<char> buffer(bufferSize, static_cast<char>(0));
        auto rc = ::readlink(p.c_str(), buffer.data(), buffer.size());
        if (rc < 0) {
            ec = detail::make_system_error();
            return path();
        }
        else if (rc < static_cast<int>(bufferSize)) {
            return path(std::string(buffer.data(), static_cast<std::string::size_type>(rc)));
        }
        bufferSize *= 2;
    }
    return path();
#endif
}
References endsWith(), GHC_NATIVEWP, make_system_error(), p, startsWith(), and string.
Referenced by ghc::filesystem::read_symlink(), and status_ex().
startsWith()
template<typename strT , typename std::enable_if< path::_is_basic_string< strT >::value, bool >::type = true>
GHC_INLINE bool ghc::filesystem::detail::startsWith (const strT & what, const strT & with)
Definition at line 1711 of file filesystem.hpp.
{
    return with.length() <= what.length() && equal(with.begin(), with.end(), what.begin());
}
Referenced by ghc::filesystem::path::check_long_path(), MarkdownOutlineParser::parseInput(), ghc::filesystem::path::postprocess_path_with_format(), and resolveSymlink().
status_ex()
GHC_INLINE file_status ghc::filesystem::detail::status_ex (const path & p, std::error_code & ec, file_status * sls = nullptr, uintmax_t * sz = nullptr, uintmax_t * nhl = nullptr, time_t * lwt = nullptr, int recurse_count = 0) [noexcept]
Definition at line 2248 of file filesystem.hpp.
{
    ec.clear();
#ifdef GHC_OS_WINDOWS
    if (recurse_count > 16) {
        ec = detail::make_system_error(0x2A9 /*ERROR_STOPPED_ON_SYMLINK*/);
        return file_status(file_type::unknown);
    }
    WIN32_FILE_ATTRIBUTE_DATA attr;
    if (!::GetFileAttributesExW(GHC_NATIVEWP(p), GetFileExInfoStandard, &attr)) {
        ec = detail::make_system_error();
    }
    else if (attr.dwFileAttributes & FILE_ATTRIBUTE_REPARSE_POINT) {
        auto reparseData = detail::getReparseData(p, ec);
        if (!ec && reparseData && IsReparseTagMicrosoft(reparseData->ReparseTag) && reparseData->ReparseTag == IO_REPARSE_TAG_SYMLINK) {
            path target = resolveSymlink(p, ec);
            file_status result;
            if (!ec && !target.empty()) {
                if (sls) {
                    *sls = status_from_INFO(p, &attr, ec);
                }
                return detail::status_ex(target, ec, nullptr, sz, nhl, lwt, recurse_count + 1);
            }
            return file_status(file_type::unknown);
        }
    }
    if (ec) {
        if (detail::is_not_found_error(ec)) {
            return file_status(file_type::not_found);
        }
        return file_status(file_type::none);
    }
    if (nhl) {
        *nhl = 0;
    }
    return detail::status_from_INFO(p, &attr, ec, sz, lwt);
#else
    (void)recurse_count;
    struct ::stat st;
    auto result = ::lstat(p.c_str(), &st);
    if (result == 0) {
        ec.clear();
        file_status fs = detail::file_status_from_st_mode(st.st_mode);
        if (sls) {
            *sls = fs;
        }
        if (fs.type() == file_type::symlink) {
            result = ::stat(p.c_str(), &st);
            if (result == 0) {
                fs = detail::file_status_from_st_mode(st.st_mode);
            }
            else {
                ec = detail::make_system_error();
                if (detail::is_not_found_error(ec)) {
                    return file_status(file_type::not_found, perms::unknown);
                }
                return file_status(file_type::none);
            }
        }
        if (sz) {
            *sz = static_cast<uintmax_t>(st.st_size);
        }
        if (nhl) {
            *nhl = st.st_nlink;
        }
        if (lwt) {
            *lwt = st.st_mtime;
        }
        return fs;
    }
    else {
        ec = detail::make_system_error();
        if (detail::is_not_found_error(ec)) {
            return file_status(file_type::not_found, perms::unknown);
        }
        return file_status(file_type::none);
    }
#endif
}
References ghc::filesystem::path::empty(), file_status_from_st_mode(), GHC_NATIVEWP, is_not_found_error(), make_system_error(), ghc::filesystem::none, ghc::filesystem::not_found, p, resolveSymlink(), status_ex(), ghc::filesystem::symlink, and ghc::filesystem::unknown.
Referenced by ghc::filesystem::hard_link_count(), ghc::filesystem::last_write_time(), ghc::filesystem::directory_entry::refresh(), ghc::filesystem::status(), and status_ex().
strerror_adapter() [1/2]
GHC_INLINE const char * ghc::filesystem::detail::strerror_adapter (char * gnu, char *)
Definition at line 1850 of file filesystem.hpp.
{
    return gnu;
}
Referenced by systemErrorText().
strerror_adapter() [2/2]
GHC_INLINE const char * ghc::filesystem::detail::strerror_adapter (int posix, char * buffer)
Definition at line 1855 of file filesystem.hpp.
{
    if (posix) {
        return "Error in strerror_r!";
    }
    return buffer;
}
symlink_status_ex()
GHC_INLINE file_status ghc::filesystem::detail::symlink_status_ex (const path & p, std::error_code & ec, uintmax_t * sz = nullptr, uintmax_t * nhl = nullptr, time_t * lwt = nullptr) [noexcept]
Definition at line 2210 of file filesystem.hpp.
{
#ifdef GHC_OS_WINDOWS
    file_status fs;
    WIN32_FILE_ATTRIBUTE_DATA attr;
    if (!GetFileAttributesExW(GHC_NATIVEWP(p), GetFileExInfoStandard, &attr)) {
        ec = detail::make_system_error();
    }
    else {
        ec.clear();
        fs = detail::status_from_INFO(p, &attr, ec, sz, lwt);
        if (nhl) {
            *nhl = 0;
        }
    }
    if (detail::is_not_found_error(ec)) {
        return file_status(file_type::not_found);
    }
    return ec ? file_status(file_type::none) : fs;
#else
    (void)sz;
    (void)nhl;
    (void)lwt;
    struct ::stat fs;
    auto result = ::lstat(p.c_str(), &fs);
    if (result == 0) {
        ec.clear();
        file_status f_s = detail::file_status_from_st_mode(fs.st_mode);
        return f_s;
    }
    ec = detail::make_system_error();
    if (detail::is_not_found_error(ec)) {
        return file_status(file_type::not_found, perms::unknown);
    }
    return file_status(file_type::none);
#endif
}
References file_status_from_st_mode(), GHC_NATIVEWP, is_not_found_error(), make_system_error(), ghc::filesystem::none, ghc::filesystem::not_found, p, and ghc::filesystem::unknown.
Referenced by ghc::filesystem::symlink_status().
systemErrorText()
template<typename ErrorNumber >
GHC_INLINE std::string ghc::filesystem::detail::systemErrorText (ErrorNumber code = 0)
Definition at line 1864 of file filesystem.hpp.
{
#if defined(GHC_OS_WINDOWS)
    LPVOID msgBuf;
    DWORD dw = code ? static_cast<DWORD>(code) : ::GetLastError();
    FormatMessageW(FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS, NULL, dw, MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT), (LPWSTR)&msgBuf, 0, NULL);
    std::string msg = toUtf8(std::wstring((LPWSTR)msgBuf));
    LocalFree(msgBuf);
    return msg;
#else
    char buffer[512];
    return strerror_adapter(strerror_r(code ? code : errno, buffer, sizeof(buffer)), buffer);
#endif
}
References errno, msg(), strerror_adapter(), string, and toUtf8().
Referenced by ghc::filesystem::last_write_time().
toUtf8() [1/2]
template<typename charT >
std::string ghc::filesystem::detail::toUtf8 (const charT * unicodeString) [inline]
Definition at line 1644 of file filesystem.hpp.
{
#ifdef GHC_WITH_STRING_VIEW
    return toUtf8(basic_string_view<charT, std::char_traits<charT>>(unicodeString));
#else
    return toUtf8(std::basic_string<charT, std::char_traits<charT>>(unicodeString));
#endif
}
References toUtf8().
toUtf8() [2/2]
template<typename strT , typename std::enable_if< path::_is_basic_string< strT >::value &&(sizeof(typename strT::value_type)==1), int >::type size = 1>
std::string ghc::filesystem::detail::toUtf8 (const strT & unicodeString) [inline]
Definition at line 1599 of file filesystem.hpp.
{
    return std::string(unicodeString.begin(), unicodeString.end());
}
References string.
Referenced by ghc::filesystem::path::assign(), ghc::filesystem::path::string(), systemErrorText(), toUtf8(), ghc::filesystem::u8arguments::u8arguments(), and ghc::filesystem::path::u8string().
validUtf8()
GHC_INLINE bool ghc::filesystem::detail::validUtf8 (const std::string & utf8String)
Definition at line 1487 of file filesystem.hpp.
{
    std::string::const_iterator iter = utf8String.begin();
    unsigned utf8_state = S_STRT;
    std::uint32_t codepoint = 0;
    while (iter < utf8String.end()) {
        if ((utf8_state = consumeUtf8Fragment(utf8_state, static_cast<uint8_t>(*iter++), codepoint)) == S_RJCT) {
            return false;
        }
    }
    if (utf8_state) {
        return false;
    }
    return true;
}
References consumeUtf8Fragment(), S_RJCT, and S_STRT.
Referenced by ghc::filesystem::path::postprocess_path_with_format().