runtests Namespace Reference
Classes
class Tester
class TestManager
Functions
def xopen (fname, mode='r', encoding='utf-8')
def xpopen (cmd, cmd1=``, encoding='utf-8-sig', getStderr=False)
def clean_header (errmsg)
def do_generation_work (test)
def split_and_keep (s, sep)
def main ()
Variables
config_reg = re.compile('.*\/\/\s*(?P<name>\S+):\s*(?P<value>.*)$')
bkmk_reg = re.compile(r'.*bkmkstart\s+([A-Z][A-Z][A-Z][A-Z][A-Z][A-Z][A-Z][A-Z][A-Z][A-Z]).*')
hyper_reg = re.compile(r'.*HYPERLINK\s+[\\l]*\s+`([A-Z][A-Z][A-Z][A-Z][A-Z][A-Z][A-Z][A-Z][A-Z][A-Z])`.*')
pageref_reg = re.compile(r'.*PAGEREF\s+([A-Z][A-Z][A-Z][A-Z][A-Z][A-Z][A-Z][A-Z][A-Z][A-Z]).*')
Function Documentation
clean_header()
def runtests.clean_header (errmsg)
Definition at line 41 of file runtests.py.
def clean_header(errmsg):
    # messages (due to the usage of more) have a contents like:
    # ::::::::::::
    # <file name>
    # ::::::::::::
    # we want to skip these
    msg = errmsg.split('\n')
    rtnmsg = ""
    cnt = -1
    for o in msg:
        if (o):
            if (cnt == -1):
                if o.startswith(":::::::"):
                    cnt = 3
            if (cnt > 0):
                cnt-=1
            else:
                rtnmsg+=o
    return rtnmsg
 
Referenced by runtests.Tester.perform_test().
do_generation_work()
def runtests.do_generation_work (test)
Definition at line 542 of file runtests.py.
def do_generation_work(test):
    tester = Tester(test[0].args,test[1])
    return tester.run(test[0])
main()
def runtests.main (void)
Definition at line 610 of file runtests.py.
def main():
    # argument handling
    parser = argparse.ArgumentParser(description='run doxygen tests')
    parser.add_argument('--updateref',help=
        'update the reference files. Should be used in combination with --id to '
        'update the reference file(s) for the given test',action="store_true")
    parser.add_argument('--doxygen',nargs='?',default='doxygen',help=
        'path/name of the doxygen executable')
    parser.add_argument('--xmllint',nargs='?',default='xmllint',help=
        'path/name of the xmllint executable')
    parser.add_argument('--id',nargs='+',dest='ids',action='append',type=int,help=
        'run test with number n only (the option can be specified to run test with '
        'number n only (the option can be specified multiple times')
    parser.add_argument('--start_id',dest='start_id',type=int,help=
        'run tests starting with number n')
    parser.add_argument('--end_id',dest='end_id',type=int,help=
        'run tests ending with number n')
    parser.add_argument('--all',help=
        'can be used in combination with -updateref to update the reference files '
        'for all tests.',action="store_true")
    parser.add_argument('--inputdir',nargs='?',default='.',help=
        'input directory containing the tests')
    parser.add_argument('--outputdir',nargs='?',default='.',help=
        'output directory to write the doxygen output to')
    parser.add_argument('--noredir',help=
        'disable redirection of doxygen warnings',action="store_true")
    parser.add_argument('--pool',nargs='?',default='1',type=int,help=
        'pool size of multiprocess tests')
    parser.add_argument('--xml',help='create xml output and check',
        action="store_true")
    parser.add_argument('--rtf',help=
        'create rtf output',action="store_true")
    parser.add_argument('--docbook',help=
        'create docbook output and check with xmllint',action="store_true")
    parser.add_argument('--xhtml',help=
        'create xhtml output and check with xmllint',action="store_true")
    parser.add_argument('--qhp',help=
        'create qhp output and check with xmllint',action="store_true")
    parser.add_argument('--xmlxsd',help=
        'create xml output and check with xmllint against xsd',action="store_true")
    parser.add_argument('--pdf',help='create LaTeX output and create pdf from it',
        action="store_true")
    parser.add_argument('--subdirs',help='use the configuration parameter CREATE_SUBDIRS=YES',
        action="store_true")
    parser.add_argument('--clang',help='use CLANG_ASSISTED_PARSING, works only when '
                'doxygen has been compiled with "use_libclang"',
        action="store_true")
    parser.add_argument('--keep',help='keep result directories',
        action="store_true")
    parser.add_argument('--cfg',nargs='+',dest='cfgs',action='append',help=
        'run test with extra doxygen configuration settings '
        '(the option may be specified multiple times')
    test_flags = split_and_keep(os.getenv('TEST_FLAGS', default=''), '--')
    args = parser.parse_args(test_flags + sys.argv[1:])
    # sanity check
    if (not args.xml) and (not args.pdf) and (not args.xhtml) and (not args.qhp) and (not args.docbook and (not args.rtf) and (not args.xmlxsd)):
        args.xml=True
    if (not args.updateref is None) and (args.ids is None) and (args.all is None):
        parser.error('--updateref requires either --id or --all')
    starting_directory = os.getcwd()
    os.chdir(args.inputdir)
    # find the tests to run
    tests = []
    if args.start_id:
        if args.end_id:
            for id in range(args.start_id, args.end_id + 1):
                tests.append(glob.glob('%s_*'%id))
                tests.append(glob.glob('0%s_*'%id))
                tests.append(glob.glob('00%s_*'%id))
        else:
            parser.error('--start_id requires --end_id')
    elif args.end_id:
        parser.error('--end_id requires --start_id')
    if args.ids: # test ids are given by user
        for id in list(itertools.chain.from_iterable(args.ids)):
            tests.append(glob.glob('%s_*'%id))
            tests.append(glob.glob('0%s_*'%id))
            tests.append(glob.glob('00%s_*'%id))
    if (not args.ids and not args.start_id): # find all tests
        tests = sorted(glob.glob('[0-9][0-9][0-9]_*'))
    else:
        tests = list(itertools.chain.from_iterable(tests))
    os.chdir(starting_directory)
    # create test manager to run the tests
    testManager = TestManager(args,tests)
    sys.exit(testManager.perform_tests())
References main(), and split_and_keep().
Referenced by main(), and runtests.TestManager.prepare_dtd().
split_and_keep()
def runtests.split_and_keep (s, sep)
Definition at line 601 of file runtests.py.
def split_and_keep(s,sep):
    s = s.replace('"','') # add token separator
    s = s.replace(sep,'\0'+sep) # add token separator
    s = s.split('\0') # split by null delimiter
    s = [x.strip() for x in filter(None,s)] # strip and remove empty elements
    s = [z.split(' ',1) for z in s] # split by first space
    s = [i for ss in s for i in ss] # flatten the list
    return s
References filter.
Referenced by main(), and runtests.TestManager.prepare_dtd().
xopen()
def runtests.xopen (fname, mode = 'r', encoding = 'utf-8')
Unified file opening for Python 2 an Python 3.

Python 2 does not have the encoding argument. Python 3 has one.
Definition at line 14 of file runtests.py.
def xopen(fname, mode='r', encoding='utf-8'):
    '''Unified file opening for Python 2 an Python 3.
    Python 2 does not have the encoding argument. Python 3 has one.
    '''
    if sys.version_info[0] == 2:
        return open(fname, mode=mode) # Python 2 without encoding
    else:
        return open(fname, mode=mode, encoding=encoding) # Python 3 with encoding
References open().
Referenced by runtests.Tester.check_link_rtf_file(), runtests.Tester.get_config(), runtests.Tester.perform_test(), runtests.Tester.prepare_test(), and runtests.Tester.update_test().
xpopen()
def runtests.xpopen (cmd, cmd1 = ``, encoding = 'utf-8-sig', getStderr = False)
Unified file pipe opening for Python 2 an Python 3.

Python 2 does not have the encoding argument. Python 3 has one. and
Definition at line 25 of file runtests.py.
def xpopen(cmd, cmd1="",encoding='utf-8-sig', getStderr=False):
    '''Unified file pipe opening for Python 2 an Python 3.
    Python 2 does not have the encoding argument. Python 3 has one. and
    '''
    if sys.version_info[0] == 2:
        return os.popen(cmd).read() # Python 2 without encoding
    else:
        if (getStderr):
            proc = subprocess.Popen(shlex.split(cmd1),stdout=subprocess.PIPE,stderr=subprocess.PIPE,encoding=encoding) # Python 3 with encoding
            return proc.stderr.read()
        else:
            proc = subprocess.Popen(shlex.split(cmd),stdout=subprocess.PIPE,stderr=subprocess.PIPE,encoding=encoding) # Python 3 with encoding
            return proc.stdout.read()
References read().
Referenced by runtests.Tester.compare_ok(), runtests.Tester.perform_test(), and runtests.Tester.update_test().
Variable Documentation
bkmk_reg
runtests.bkmk_reg = re.compile(r'.*bkmkstart\s+([A-Z][A-Z][A-Z][A-Z][A-Z][A-Z][A-Z][A-Z][A-Z][A-Z]).*')
Definition at line 9 of file runtests.py.
config_reg
runtests.config_reg = re.compile('.*\/\/\s*(?P<name>\S+):\s*(?P<value>.*)$')
Definition at line 8 of file runtests.py.
hyper_reg
runtests.hyper_reg = re.compile(r'.*HYPERLINK\s+[\\l]*\s+`([A-Z][A-Z][A-Z][A-Z][A-Z][A-Z][A-Z][A-Z][A-Z][A-Z])`.*')
Definition at line 10 of file runtests.py.
pageref_reg
runtests.pageref_reg = re.compile(r'.*PAGEREF\s+([A-Z][A-Z][A-Z][A-Z][A-Z][A-Z][A-Z][A-Z][A-Z][A-Z]).*')
Definition at line 11 of file runtests.py.