generateDS_post Namespace Reference
Functions
def main ()
Function Documentation
main()
def generateDS_post.main (void)
Definition at line 17 of file generateDS_post.py.
def main():
    inputFile = open(sys.argv[1], 'r')
    outputFile = open(sys.argv[2], 'wb')
    lineStr = ""
    for line in inputFile:
        line = line.rstrip()
        line = re.sub(r'##','# #',line)
        line = re.sub(r'# Python.*','#',line)
        line = re.sub(r"('-o', ').*(/addon/doxmlparser/doxmlparser)","\\1...\\2",line)
        # python 2 slips the u in ...
        line = re.sub(r"u'","'",line)
        if line.find("generateDS") == -1:
            line = re.sub(r'(#).*(/templates/xml/)','\\1...\\2',line)
        else:
            line = re.sub(r'(#).*generateDS(.* -o ").*(/addon/doxmlparser/doxmlparser/.*).*(/templates/xml/)',
                           '\\1.../generateDS\\2...\\3...\\4',line)
        if line.find(" self") == 0:
            line = " " + line
        outputFile.write(str.encode(line))
        outputFile.write(str.encode('\n'))
References main(), and open().
Referenced by main().