testsqlite3 Namespace Reference
Functions
def print_unprocessed_attributes (node)
def extract_attribute (node, attribute, pnl)
def extract_element (node, chld, pnl)
def process_memberdef (node)
def load_xml (name)
def open_db (dbname)
def main (argv)
Variables
g_conn = None
list val = []
Function Documentation
extract_attribute()
def testsqlite3.extract_attribute (node, attribute, pnl)
Definition at line 18 of file testsqlite3.py.
def extract_attribute(node,attribute,pnl):
    if not attribute in node.attrib:
        return
    pnl.append("%s = ?" % attribute)
    val.append(node.attrib[attribute])
    node.attrib.pop(attribute)
Referenced by process_memberdef().
extract_element()
def testsqlite3.extract_element (node, chld, pnl)
Definition at line 25 of file testsqlite3.py.
def extract_element(node,chld,pnl):
    # deal with <tag />
    if chld.text == None:
        if len(chld.attrib)==0:
            node.remove(chld)
        return
    a=chld.text.strip()
    if not a == "":
        pnl.append("%s =?" % chld.tag)
        val.append(chld.text.strip())
    else:
        pnl.append("%s IS NULL OR %s = ''" % (chld.tag,chld.tag))
    node.remove(chld)
References len.
Referenced by process_memberdef().
load_xml()
def testsqlite3.load_xml (name)
Definition at line 101 of file testsqlite3.py.
def load_xml(name):
    context = ET.iterparse(name, events=("start", "end"))
    event, root = context.next()
    for event, elem in context:
        if event == "end" and elem.tag == "memberdef":
            process_memberdef(elem)
    print("\n== Unprocessed XML ==")
# ET.dump(root)
References print(), and process_memberdef().
Referenced by main().
main()
def testsqlite3.main (argv)
Definition at line 124 of file testsqlite3.py.
def main(argv):
    try:
        opts, args = getopt.getopt(argv, "hd:x:",["help"])
    except getopt.GetoptError:
        sys.exit(1)
    dbname=None
    xmlfile=None
    for a, o in opts:
        if a in ('-h', '--help'):
            sys.exit(0)
        elif a in ('-d'):
            dbname=o
            continue
        elif a in ('-x'):
            xmlfile=o
            continue
    open_db(dbname)
    load_xml(xmlfile)
References load_xml(), main(), and open_db().
Referenced by main().
open_db()
def testsqlite3.open_db (dbname)
Definition at line 111 of file testsqlite3.py.
def open_db(dbname):
    global g_conn
    if dbname == None:
        dbname = "doxygen_sqlite3.db"
    if not os.path.isfile(dbname):
        raise BaseException("No such file %s" % dbname)
    g_conn = sqlite3.connect(dbname)
    g_conn.execute('PRAGMA temp_store = MEMORY;')
    g_conn.row_factory = sqlite3.Row
Referenced by main().
print_unprocessed_attributes()
def testsqlite3.print_unprocessed_attributes (node)
Definition at line 14 of file testsqlite3.py.
def print_unprocessed_attributes(node):
    for key in node.attrib:
        print("WARNING: '%s' has unprocessed attr '%s'" % (node.tag,key))
References print().
Referenced by process_memberdef().
process_memberdef()
def testsqlite3.process_memberdef (node)
Definition at line 40 of file testsqlite3.py.
def process_memberdef(node):
    q=[]
    for chld in node.getchildren():
        if chld.tag == "referencedby":
            continue
        if chld.tag == "references":
            continue
        if chld.tag == "param":
            continue
        if chld.tag == "type":
            continue
        if chld.tag == "location":
            extract_attribute(chld,"line",q)
            extract_attribute(chld,"column",q)
            extract_attribute(chld,"bodystart",q)
            extract_attribute(chld,"bodyend",q)
            q.append("id_bodyfile=(select id from files where name=?)")
            val.append(chld.attrib["bodyfile"])
            chld.attrib.pop("bodyfile")
            q.append("id_file=(select id from files where name=?)")
            val.append(chld.attrib["file"])
            chld.attrib.pop("file")
            print_unprocessed_attributes(chld)
            if len(chld.attrib) == 0:
                node.remove(chld)
        else:
            extract_element(node,chld,q)
    for chld in node.getchildren():
        print("WARNING: '%s' has unprocessed child elem '%s'" % (node.tag,chld.tag))
    extract_attribute(node,"kind",q)
    extract_attribute(node,"prot",q)
    extract_attribute(node,"static",q)
    extract_attribute(node,"mutable",q)
    extract_attribute(node,"const",q)
    extract_attribute(node,"virt",q)
    extract_attribute(node,"explicit",q)
    extract_attribute(node,"inline",q)
    q.append("refid=?")
    val.append(node.attrib['id'])
    node.attrib.pop('id')
    print_unprocessed_attributes(node)
    query="SELECT * FROM memberdef WHERE %s" % " AND ".join(q)
    r=[]
    try:
        r = g_conn.execute(query,val).fetchall()
    except(sqlite3.OperationalError,e):
        print("SQL_ERROR:%s"%e)
    del val[:]
    if not len(r) > 0:
        print("TEST_ERROR: Member not found in SQL DB")
References extract_attribute(), extract_element(), join(), len, print(), and print_unprocessed_attributes().
Referenced by load_xml().
Variable Documentation
g_conn
testsqlite3.g_conn = None
Definition at line 12 of file testsqlite3.py.
val
list testsqlite3.val = []
Definition at line 13 of file testsqlite3.py.
Referenced by MemberDefImpl.cacheTypedefVal(), InputString.checkEnumVal(), checkFileName(), VHDLOutlineParser.checkInlineCode(), convertStringToBool(), ConfigEnum.convertStrToVal(), ConfigInt.convertStrToVal(), CPPValue.CPPValue(), FilterListSort.determineSortKey(), expandAliasRec(), VHDLOutlineParser.getLine(), holds_value(), main(), RTFDocVisitor.operator()(), LatexDocVisitor.operator()(), ManDocVisitor.operator()(), DocbookDocVisitor.operator()(), parseBinary(), parseDecimal(), parseHexadecimal(), parseOctal(), VHDLOutlineParser.pushLabel(), Image.setPixel(), vhdl::parser::CharStream.setTrackLineColumn(), InputInt.setValue(), QCString.toLong(), QCString.toUInt64(), QCString.toULong(), vhdl::parser::VhdlParser.variable_declaration(), writeLZ77data(), and FlowChart.writeShape().