vhdl_adj Namespace Reference
Functions
def main ()
Function Documentation
main()
def vhdl_adj.main (void)
Definition at line 17 of file vhdl_adj.py.
def main():
    inputFile = open(sys.argv[1], 'r')
    outputFile = open(sys.argv[2], 'w')
    for line in inputFile:
        outputFile.write(line.replace("assert(false);","assert(false);return QCString();"))
References main(), and open().
Referenced by main().