docstring Namespace Reference
Classes
class PyClass
Functions
def func ()
Detailed Description
@package docstring
Documentation for this module.

More details.
Function Documentation
func()
def docstring.func ()
Documentation for a function.

More details.
Definition at line 7 of file docstring.py.
def func():
    """Documentation for a function.
    More details.
    """
    pass
Referenced by VhdlDocGen.convertArgumentListToString(), TemplateFilterFactory.registerFilter(), TemplateNodeFactory.registerTemplateNode(), and Trace.Trace().