Portable Namespace Reference
Functions
int system (const QCString &command, const QCString &args, bool commandHasConsole=true)
unsigned int pid ()
QCString getenv (const QCString &variable)
void setenv (const QCString &variable, const QCString &value)
void unsetenv (const QCString &variable)
portable_off_t fseek (FILE *f, portable_off_t offset, int whence)
portable_off_t ftell (FILE *f)
FILE * fopen (const QCString &fileName, const QCString &mode)
int fclose (FILE *f)
void unlink (const QCString &fileName)
QCString pathSeparator ()
QCString pathListSeparator ()
const char * ghostScriptCommand ()
const char * commandExtension ()
bool fileSystemIsCaseSensitive ()
FILE * popen (const QCString &name, const QCString &type)
int pclose (FILE *stream)
void sysTimerStart ()
void sysTimerStop ()
double getSysElapsedTime ()
void sleep (int ms)
bool isAbsolutePath (const QCString &fileName)
void correct_path ()
void setShortDir ()
const char * strnstr (const char *haystack, const char *needle, size_t haystack_len)
const char * devNull ()
bool checkForExecutable (const QCString &fileName)
size_t recodeUtf8StringToW (const QCString &inputStr, uint16_t **buf)
Function Documentation
checkForExecutable()
bool Portable::checkForExecutable (const QCString & fileName)
Definition at line 390 of file portable.cpp.
{
#if defined(_WIN32) && !defined(__CYGWIN__)
  char *extensions[] = {".bat",".com",".exe"};
  for (int i = 0; i < sizeof(extensions) / sizeof(*extensions); i++)
  {
    if (ExistsOnPath(fileName + extensions[i])) return true;
  }
  return false;
#else
  return ExistsOnPath(fileName);
#endif
}
References ExistsOnPath().
Referenced by FormulaManager::createFormulasTexFile().
commandExtension()
const char * Portable::commandExtension ()
Definition at line 428 of file portable.cpp.
{
#if defined(_WIN32) && !defined(__CYGWIN__)
    return ".exe";
#else
    return "";
#endif
}
Referenced by Config::checkAndCorrect(), computeVerifiedDotPath(), and writeDiaGraphFromFile().
correct_path()
void Portable::correct_path ()
Correct a possible wrong PATH variable
This routine was inspired by the cause for bug 766059 was that in the Windows path there were forward slashes.
Definition at line 509 of file portable.cpp.
{
#if defined(_WIN32) && !defined(__CYGWIN__)
  QCString p = Portable::getenv("PATH");
  if (p.isEmpty()) return; // no path nothing to correct
  QCString result = substitute(p,"/","\\");
  if (result!=p) Portable::setenv("PATH",result.data());
#endif
}
References QCString::data(), getenv(), p, setenv(), and substitute().
Referenced by initDoxygen().
devNull()
const char * Portable::devNull ()
Definition at line 589 of file portable.cpp.
{
#if defined(_WIN32) && !defined(__CYGWIN__)
  return "NUL";
#else
  return "/dev/null";
#endif
}
Referenced by createDVIFile(), createSVGFromPDFviaInkscape(), and determineInkscapeVersion().
fclose()
int Portable::fclose (FILE * f)
Definition at line 336 of file portable.cpp.
{
  return ::fclose(f);
}
References f, and fclose().
Referenced by checkPngResult(), OutputGenerator::endPlainFile(), fclose(), gdoClose(), FilterCache::getFileContents(), LodePNG_saveFile(), mscgen_generate(), parseConfig(), PsClose(), DotRunner::readBoundingBox(), DotRunner::run(), run_query(), and SvgClose().
fileSystemIsCaseSensitive()
bool Portable::fileSystemIsCaseSensitive ()
Definition at line 437 of file portable.cpp.
{
#if defined(_WIN32) || defined(macintosh) || defined(__MACOSX__) || defined(__APPLE__) || defined(__CYGWIN__)
  return FALSE;
#else
  return TRUE;
#endif
}
References FALSE, and TRUE.
Referenced by findFileDef(), genericPatternMatch(), getCaseSenseNames(), and getFilterFromList().
fopen()
FILE * Portable::fopen (const QCString & fileName, const QCString & mode)
Definition at line 316 of file portable.cpp.
{
#if defined(_WIN32) && !defined(__CYGWIN__)
  uint16_t *fn = 0;
  size_t fn_len = recodeUtf8StringToW(fileName,&fn);
  uint16_t *m = 0;
  size_t m_len = recodeUtf8StringToW(mode,&m);
  FILE *result = 0;
  if (fn_len!=(size_t)-1 && m_len!=(size_t)-1)
  {
    result = _wfopen((wchar_t*)fn,(wchar_t*)m);
  }
  delete[] fn;
  delete[] m;
  return result;
#else
  return ::fopen(fileName.data(),mode.data());
#endif
}
References QCString::data(), fopen(), mode, and recodeUtf8StringToW().
Referenced by checkPngResult(), fopen(), GdoInit(), FilterCache::getFileContents(), initWarningFormat(), LodePNG_saveFile(), mscgen_generate(), parseConfig(), PsInit(), DotRunner::readBoundingBox(), DotRunner::run(), run_query(), OutputGenerator::startPlainFile(), SvgInit(), and tryPath().
fseek()
portable_off_t Portable::fseek (FILE * f, portable_off_t offset, int whence)
Definition at line 294 of file portable.cpp.
{
#if defined(__MINGW32__)
  return fseeko64(f,offset,whence);
#elif defined(_WIN32) && !defined(__CYGWIN__)
  return _fseeki64(f,offset,whence);
#else
  return fseeko(f,offset,whence);
#endif
}
References f, and offset.
Referenced by FilterCache::getFileContents(), and search().
ftell()
portable_off_t Portable::ftell (FILE * f)
Definition at line 305 of file portable.cpp.
{
#if defined(__MINGW32__)
  return ftello64(f);
#elif defined(_WIN32) && !defined(__CYGWIN__)
  return _ftelli64(f);
#else
  return ftello(f);
#endif
}
References f.
getenv()
QCString Portable::getenv (const QCString & variable)
Definition at line 273 of file portable.cpp.
{
#if defined(_WIN32) && !defined(__CYGWIN__)
    return ::getenv(variable.data());
#else
    if(!environmentLoaded) // if the environment variables are not loaded already...
    { // ...call loadEnvironment to store them in class
      loadEnvironment();
    }
    if (proc_env.find(variable.str()) != proc_env.end())
    {
      return QCString(proc_env[variable.str()]);
    }
    else
    {
      return QCString();
    }
#endif
}
References QCString::data(), environmentLoaded, getenv(), loadEnvironment(), proc_env, and QCString::str().
Referenced by correct_path(), ExistsOnPath(), getCurrentDateTime(), getenv(), initDoxygen(), main(), mscgen_getenv_s(), parseInput(), setDotFontPath(), substEnvVarsInString(), and ghc::filesystem::temp_directory_path().
getSysElapsedTime()
double Portable::getSysElapsedTime ()
Definition at line 476 of file portable.cpp.
{
  return g_sysElapsedTime;
}
References g_sysElapsedTime.
Referenced by generateOutput().
ghostScriptCommand()
const char * Portable::ghostScriptCommand ()
Definition at line 404 of file portable.cpp.
{
#if defined(_WIN32) && !defined(__CYGWIN__)
    static char *gsexe = NULL;
    if (!gsexe)
    {
        char *gsExec[] = {"gswin32c.exe","gswin64c.exe"};
        for (int i = 0; i < sizeof(gsExec) / sizeof(*gsExec); i++)
        {
            if (ExistsOnPath(gsExec[i]))
        {
                gsexe = gsExec[i];
                return gsexe;
            }
        }
        gsexe = gsExec[0];
        return gsexe;
    }
    return gsexe;
#else
    return "gs";
#endif
}
References ExistsOnPath().
Referenced by createCroppedEPS(), createCroppedPDF(), createEPSbboxFile(), createPNG(), and writeMakeBat().
isAbsolutePath()
bool Portable::isAbsolutePath (const QCString & fileName)
Definition at line 490 of file portable.cpp.
{
  const char *fn = fileName.data();
# ifdef _WIN32
  if (fileName.length()>1 && isalpha(fileName[0]) && fileName[1]==':') fn+=2;
# endif
  char const fst = fn[0];
  if (fst == '/') return true;
# ifdef _WIN32
  if (fst == '\\') return true;
# endif
  return false;
}
References QCString::data(), reg::isalpha(), and QCString::length().
Referenced by findFile(), generateOutput(), Markdown::processLink(), and DocParser::readTextFileByName().
pathListSeparator()
QCString Portable::pathListSeparator ()
Definition at line 350 of file portable.cpp.
{
#if defined(_WIN32) && !defined(__CYGWIN__)
  return ";";
#else
  return ":";
#endif
}
Referenced by ExistsOnPath(), parseInput(), runPlantumlContent(), and setDotFontPath().
pathSeparator()
QCString Portable::pathSeparator ()
Definition at line 341 of file portable.cpp.
{
#if defined(_WIN32) && !defined(__CYGWIN__)
  return "\\";
#else
  return "/";
#endif
}
Referenced by MemberContext::Private::callerGraph(), MemberContext::Private::callGraph(), Config::checkAndCorrect(), ClassContext::Private::collaborationDiagram(), InheritanceGraphContext::Private::createGraph(), DirContext::Private::dirGraph(), ExistsOnPath(), ModuleContext::Private::groupGraph(), FileContext::Private::includedByGraph(), FileContext::Private::includeGraph(), ClassContext::Private::inheritanceDiagram(), DocParser::readTextFileByName(), writeDiaGraphFromFile(), and writeMscGraphFromFile().
pclose()
int Portable::pclose (FILE * stream)
Definition at line 455 of file portable.cpp.
{
  #if defined(_MSC_VER) || defined(__BORLANDC__)
  return ::_pclose(stream);
  #else
  return ::pclose(stream);
  #endif
}
References pclose().
Referenced by FileDefImpl::acquireFileVersion(), FilterCache::getFileContents(), pclose(), readInputFile(), runQHelpGenerator(), and stackTrace().
pid()
unsigned int Portable::pid ()
Definition at line 201 of file portable.cpp.
{
  unsigned int pid;
#if !defined(_WIN32) || defined(__CYGWIN__)
  pid = static_cast<unsigned int>(getpid());
#else
  pid = static_cast<unsigned int>(GetCurrentProcessId());
#endif
  return pid;
}
References pid().
Referenced by main(), parseInput(), pid(), and system().
popen()
FILE * Portable::popen (const QCString & name, const QCString & type)
Definition at line 446 of file portable.cpp.
{
  #if defined(_MSC_VER) || defined(__BORLANDC__)
  return ::_popen(name.data(),type.data());
  #else
  return ::popen(name.data(),type.data());
  #endif
}
References QCString::data(), setup::name, and popen().
Referenced by FileDefImpl::acquireFileVersion(), FilterCache::getFileContents(), popen(), readInputFile(), runQHelpGenerator(), and stackTrace().
recodeUtf8StringToW()
size_t Portable::recodeUtf8StringToW (const QCString & inputStr, uint16_t ** buf)
Definition at line 598 of file portable.cpp.
{
  if (inputStr.isEmpty() || outBuf==0) return 0; // empty input or invalid output
  void *handle = portable_iconv_open("UTF-16LE","UTF-8");
  if (handle==reinterpret_cast<void *>(-1)) return 0; // invalid encoding
  size_t len = inputStr.length();
  uint16_t *buf = new uint16_t[len+1];
  *outBuf = buf;
  size_t inRemains = len;
  size_t outRemains = len*sizeof(uint16_t)+2; // chars + \0
  const char *p = inputStr.data();
  portable_iconv(handle,&p,&inRemains,reinterpret_cast<char **>(&buf),&outRemains);
  *buf=0;
  portable_iconv_close(handle);
  return len;
}
References QCString::data(), QCString::isEmpty(), len, QCString::length(), p, portable_iconv(), portable_iconv_close(), and portable_iconv_open().
Referenced by fopen(), and system().
setenv()
void Portable::setenv (const QCString & variable, const QCString & value)
Definition at line 240 of file portable.cpp.
{
#if defined(_WIN32) && !defined(__CYGWIN__)
    SetEnvironmentVariable(name.data(),!value.isEmpty() ? value.data() : "");
#else
    if(!environmentLoaded) // if the environment variables are not loaded already...
    { // ...call loadEnvironment to store them in class
      loadEnvironment();
    }
    proc_env[name.str()] = value.str(); // create or replace existing value
#endif
}
References QCString::data(), environmentLoaded, QCString::isEmpty(), loadEnvironment(), setup::name, proc_env, and QCString::str().
Referenced by correct_path(), initDoxygen(), parseInput(), setDotFontPath(), and unsetDotFontPath().
setShortDir()
void Portable::setShortDir ()
Definition at line 528 of file portable.cpp.
{
#if defined(_WIN32) && !defined(__CYGWIN__)
  long length = 0;
  TCHAR* buffer = NULL;
  // First obtain the size needed by passing NULL and 0.
  length = GetShortPathName(Dir::currentDirPath().c_str(), NULL, 0);
  // Dynamically allocate the correct size
  // (terminating null char was included in length)
  buffer = new TCHAR[length];
  // Now simply call again using same (long) path.
  length = GetShortPathName(Dir::currentDirPath().c_str(), buffer, length);
  // Set the correct directory (short name)
  Dir::setCurrent(buffer);
  delete [] buffer;
#endif
}
References Dir::currentDirPath(), and Dir::setCurrent().
Referenced by runHtmlHelpCompiler().
sleep()
void Portable::sleep (int ms)
Definition at line 481 of file portable.cpp.
{
#if defined(_WIN32) && !defined(__CYGWIN__)
  Sleep(ms);
#else
  usleep(1000*ms);
#endif
}
Referenced by DotManager::run().
strnstr()
const char * Portable::strnstr (const char * haystack, const char * needle, size_t haystack_len)
Definition at line 575 of file portable.cpp.
{
  size_t needle_len = strnlen(needle, haystack_len);
  if (needle_len < haystack_len || !needle[needle_len])
  {
    const char *x = portable_memmem(haystack, haystack_len, needle, needle_len);
    if (x && !memchr(haystack, 0, x - haystack))
    {
      return x;
    }
  }
  return 0;
}
References portable_memmem(), and x.
Referenced by Markdown::addStrEscapeUtf8Nbsp().
system()
int Portable::system (const QCString & command, const QCString & args, bool commandHasConsole = true)
taken from the system() manpage on my Linux box
Definition at line 42 of file portable.cpp.
{
  if (command.isEmpty()) return 1;
#if defined(_WIN32) && !defined(__CYGWIN__)
  QCString commandCorrectedPath = substitute(command,'/','\\');
  QCString fullCmd=commandCorrectedPath;
#else
  QCString fullCmd=command;
#endif
  fullCmd=fullCmd.stripWhiteSpace();
  if (fullCmd.at(0)!='"' && fullCmd.find(' ')!=-1)
  {
    // add quotes around command as it contains spaces and is not quoted already
    fullCmd="\""+fullCmd+"\"";
  }
  fullCmd += " ";
  fullCmd += args;
#ifndef NODEBUG
  Debug::print(Debug::ExtCmd,0,"Executing external command `%s`\n",qPrint(fullCmd));
#endif
#if !defined(_WIN32) || defined(__CYGWIN__)
  (void)commandHasConsole;
  int pid,status=0;
#ifdef _OS_SOLARIS // for Solaris we use vfork since it is more memory efficient
  // on Solaris fork() duplicates the memory usage
  // so we use vfork instead
  // spawn shell
  if ((pid=vfork())<0)
  {
    status=-1;
  }
  else if (pid==0)
  {
     execl("/bin/sh","sh","-c",fullCmd.data(),(char*)0);
     _exit(127);
  }
  else
  {
    while (waitpid(pid,&status,0)<0)
    {
      if (errno!=EINTR)
      {
        status=-1;
        break;
      }
    }
  }
  return status;
#else // Other Unices just use fork
  pid = fork();
  if (pid==-1)
  {
    perror("fork error");
      return -1;
  }
  if (pid==0)
  {
    const char * const argv[4] = { "sh", "-c", fullCmd.data(), 0 };
    execve("/bin/sh",const_cast<char * const*>(argv),environ);
    exit(127);
  }
  for (;;)
  {
    if (waitpid(pid,&status,0)==-1)
    {
      if (errno!=EINTR) return -1;
    }
    else
    {
      if (WIFEXITED(status))
      {
        return WEXITSTATUS(status);
      }
      else
      {
        return status;
      }
    }
  }
#endif // !_OS_SOLARIS
#else // Win32 specific
  if (commandHasConsole)
  {
    return ::system(fullCmd.data());
  }
  else
  {
    // Because ShellExecuteEx can delegate execution to Shell extensions
    // (data sources, context menu handlers, verb implementations) that
    // are activated using Component Object Model (COM), COM should be
    // initialized before ShellExecuteEx is called. Some Shell extensions
    // require the COM single-threaded apartment (STA) type.
    // For that case COM is initialized as follows
    CoInitializeEx(NULL, COINIT_APARTMENTTHREADED | COINIT_DISABLE_OLE1DDE);
    uint16_t *commandw = NULL;
    recodeUtf8StringToW(commandCorrectedPath, &commandw);
    uint16_t *argsw = NULL;
    recodeUtf8StringToW(args, &argsw);
    // gswin32 is a GUI api which will pop up a window and run
    // asynchronously. To prevent both, we use ShellExecuteEx and
    // WaitForSingleObject (thanks to Robert Golias for the code)
    SHELLEXECUTEINFOW sInfo = {
      sizeof(SHELLEXECUTEINFOW), /* structure size */
      SEE_MASK_NOCLOSEPROCESS | SEE_MASK_FLAG_NO_UI, /* tell us the process
                                                       * handle so we can wait till it's done |
                                                       * do not display msg box if error
                                                       */
      NULL, /* window handle */
      NULL, /* action to perform: open */
      (LPCWSTR)commandw, /* file to execute */
      (LPCWSTR)argsw, /* argument list */
      NULL, /* use current working dir */
      SW_HIDE, /* minimize on start-up */
      0, /* application instance handle */
      NULL, /* ignored: id list */
      NULL, /* ignored: class name */
      NULL, /* ignored: key class */
      0, /* ignored: hot key */
      NULL, /* ignored: icon */
      NULL /* resulting application handle */
    };
    if (!ShellExecuteExW(&sInfo))
    {
      delete[] commandw;
      delete[] argsw;
      return -1;
    }
    else if (sInfo.hProcess) /* executable was launched, wait for it to finish */
    {
      WaitForSingleObject(sInfo.hProcess,INFINITE);
      /* get process exit code */
      DWORD exitCode;
      bool retval = GetExitCodeProcess(sInfo.hProcess,&exitCode);
      CloseHandle(sInfo.hProcess);
      delete[] commandw;
      delete[] argsw;
      if (!retval) return -1;
      return exitCode;
    }
  }
#endif
  return 1; // we should never get here
}
References QCString::at(), QCString::data(), environ, errno, Debug::ExtCmd, QCString::find(), QCString::isEmpty(), pid(), Debug::print(), qPrint(), recodeUtf8StringToW(), ghc::filesystem::status(), QCString::stripWhiteSpace(), substitute(), and system().
Referenced by createCroppedEPS(), createCroppedPDF(), createDVIFile(), createEPSbboxFile(), createPNG(), createPostscriptFile(), createSVG(), FlowChart::createSVG(), createSVGFromPDF(), createSVGFromPDFviaInkscape(), determineInkscapeVersion(), Htags::execute(), DocParser::findAndCopyImage(), CitationManager::generatePage(), main(), DotRunner::run(), runHtmlHelpCompiler(), runPlantumlContent(), runQHelpGenerator(), system(), writeDiaGraphFromFile(), ClassDiagram::writeFigure(), and writeMscGraphFromFile().
sysTimerStart()
void Portable::sysTimerStart ()
Definition at line 464 of file portable.cpp.
{
  g_startTime = std::chrono::steady_clock::now();
}
References g_startTime.
Referenced by createCroppedEPS(), createCroppedPDF(), createDVIFile(), createEPSbboxFile(), createPNG(), createPostscriptFile(), createSVGFromPDF(), createSVGFromPDFviaInkscape(), determineInkscapeVersion(), Htags::execute(), DocParser::findAndCopyImage(), DotManager::run(), runHtmlHelpCompiler(), runPlantumlContent(), runQHelpGenerator(), writeDiaGraphFromFile(), ClassDiagram::writeFigure(), and writeMscGraphFromFile().
sysTimerStop()
void Portable::sysTimerStop ()
Definition at line 469 of file portable.cpp.
{
  std::chrono::steady_clock::time_point endTime = std::chrono::steady_clock::now();
  g_sysElapsedTime+= static_cast<double>(std::chrono::duration_cast<
                         std::chrono::microseconds>(endTime - g_startTime).count())/1000000.0;
}
References g_startTime, and g_sysElapsedTime.
Referenced by createCroppedEPS(), createCroppedPDF(), createDVIFile(), createEPSbboxFile(), createPNG(), createPostscriptFile(), createSVGFromPDF(), createSVGFromPDFviaInkscape(), determineInkscapeVersion(), Htags::execute(), DocParser::findAndCopyImage(), CitationManager::generatePage(), DotManager::run(), runHtmlHelpCompiler(), runPlantumlContent(), runQHelpGenerator(), writeDiaGraphFromFile(), ClassDiagram::writeFigure(), and writeMscGraphFromFile().
unlink()
void Portable::unlink (const QCString & fileName)
Definition at line 519 of file portable.cpp.
{
#if defined(_WIN32) && !defined(__CYGWIN__)
  _unlink(fileName.data());
#else
  ::unlink(fileName.data());
#endif
}
References QCString::data(), and unlink().
Referenced by DotRunner::run(), and unlink().
unsetenv()
void Portable::unsetenv (const QCString & variable)
Definition at line 254 of file portable.cpp.
{
#if defined(_WIN32) && !defined(__CYGWIN__)
    SetEnvironmentVariable(variable.data(),0);
#else
    /* Some systems don't have unsetenv(), so we do it ourselves */
    if (variable.isEmpty() || variable.find('=')!=-1)
    {
      return; // not properly formatted
    }
    auto it = proc_env.find(variable.str());
    if (it != proc_env.end())
    {
      proc_env.erase(it);
    }
#endif
}
References QCString::data(), QCString::find(), QCString::isEmpty(), proc_env, and QCString::str().
Referenced by setDotFontPath(), and unsetDotFontPath().