metrics Namespace Reference
Classes
class Metrics
Functions
def description_is_empty (description)
def is_documented (definition)
def section_is_protected (sectionkind)
def section_is_private (sectionkind)
def section_is_public (sectionkind)
def linked_text_to_string (linkedtext)
def parse_members (compounddef, sectiondef, metrics)
def parse_sections (compounddef, metrics)
def parse_compound (inDirName, baseName, metrics)
def parse_index (inDirName)
def usage ()
def main ()
Function Documentation
description_is_empty()
def metrics.description_is_empty (description)
Definition at line 81 of file metrics.py.
def description_is_empty(description):
    for content in description.content_:
        if content.getCategory()==MixedContainer.CategoryText:
            if not content.getValue().isspace():
                return False # non space-only text
        elif not content.getCategory()==MixedContainer.CategoryNone:
            return False # some internal object like a paragraph
    return True
References reg.isspace().
Referenced by is_documented(), and metrics.Metrics.print().
is_documented()
def metrics.is_documented (definition)
Definition at line 90 of file metrics.py.
def is_documented(definition):
    return not description_is_empty(definition.get_briefdescription()) or \
           not description_is_empty(definition.get_detaileddescription())
References description_is_empty().
Referenced by parse_compound(), parse_members(), and metrics.Metrics.print().
linked_text_to_string()
def metrics.linked_text_to_string (linkedtext)
Definition at line 113 of file metrics.py.
def linked_text_to_string(linkedtext):
    str=''
    if linkedtext:
        for text_or_ref in linkedtext.content_:
            if text_or_ref.getCategory()==MixedContainer.CategoryText:
                str+=text_or_ref.getValue()
            else:
                str+=text_or_ref.getValue().get_valueOf_()
    return str
Referenced by parse_members(), and metrics.Metrics.print().
main()
def metrics.main (void)
Definition at line 216 of file metrics.py.
def main():
    args = sys.argv[1:]
    if len(args)==1:
        parse_index(args[0])
    else:
        usage()
References len, main(), parse_index(), and usage().
Referenced by main(), and metrics.Metrics.print().
parse_compound()
def metrics.parse_compound (inDirName, baseName, metrics)
Definition at line 174 of file metrics.py.
def parse_compound(inDirName,baseName,metrics):
    rootObj = doxmlparser.compound.parse(inDirName+"/"+baseName+".xml",True)
    for compounddef in rootObj.get_compounddef():
        kind = compounddef.get_kind()
        if kind==DoxCompoundKind.CLASS:
            metrics.numClasses+=1
            if is_documented(compounddef):
                metrics.numDocClasses+=1
        elif kind==DoxCompoundKind.STRUCT:
            metrics.numStructs+=1
        elif kind==DoxCompoundKind.UNION:
            metrics.numUnions+=1
        elif kind==DoxCompoundKind.INTERFACE:
            metrics.numInterfaces+=1
        elif kind==DoxCompoundKind.EXCEPTION:
            metrics.numExceptions+=1
        elif kind==DoxCompoundKind.NAMESPACE:
            metrics.numNamespaces+=1
        elif kind==DoxCompoundKind.FILE:
            metrics.numFiles+=1
            if is_documented(compounddef):
                metrics.numDocFiles+=1
        elif kind==DoxCompoundKind.GROUP:
            metrics.numGroups+=1
        elif kind==DoxCompoundKind.PAGE:
            metrics.numPages+=1
        else:
            continue
        parse_sections(compounddef,metrics)
References is_documented(), doxmlparser.compound.parse(), and parse_sections().
Referenced by parse_index(), and metrics.Metrics.print().
parse_index()
def metrics.parse_index (inDirName)
Definition at line 204 of file metrics.py.
def parse_index(inDirName):
    metrics = Metrics()
    rootObj = doxmlparser.index.parse(inDirName+"/index.xml",True)
    for compound in rootObj.get_compound(): # for each compound defined in the index
        print("Processing {0}...".format(compound.get_name()))
        parse_compound(inDirName,compound.get_refid(),metrics)
    metrics.print()
References doxmlparser.index.parse(), parse_compound(), and print().
Referenced by main(), and metrics.Metrics.print().
parse_members()
def metrics.parse_members (compounddef, sectiondef, metrics)
Definition at line 123 of file metrics.py.
def parse_members(compounddef,sectiondef,metrics):
    functionLikeKind = [DoxMemberKind.FUNCTION,
                        DoxMemberKind.PROTOTYPE,
                        DoxMemberKind.SIGNAL,
                        DoxMemberKind.SLOT,
                        DoxMemberKind.DCOP]
    variableLikeKind = [DoxMemberKind.VARIABLE, DoxMemberKind.PROPERTY]
    for memberdef in sectiondef.get_memberdef():
        if compounddef.get_kind() in [DoxCompoundKind.CLASS, DoxCompoundKind.STRUCT, DoxCompoundKind.INTERFACE]:
            if memberdef.get_kind() in functionLikeKind:
                if section_is_public(sectiondef.get_kind()):
                    metrics.numPubMethods+=1
                    if is_documented(memberdef):
                        metrics.numDocPubMethods+=1
                elif section_is_protected(sectiondef.get_kind()):
                    metrics.numProMethods+=1
                    if is_documented(memberdef):
                        metrics.numDocProMethods+=1
                elif section_is_private(sectiondef.get_kind()):
                    metrics.numPriMethods+=1
                    if is_documented(memberdef):
                        metrics.numDocPriMethods+=1
            elif memberdef.get_kind() in variableLikeKind:
                metrics.numAttributes+=1
                if is_documented(memberdef):
                    metrics.numDocAttributes+=1
        elif compounddef.get_kind() in [DoxCompoundKind.FILE, DoxCompoundKind.NAMESPACE]:
            if memberdef.get_kind() in functionLikeKind:
                metrics.numFunctions+=1
                if is_documented(memberdef):
                    metrics.numDocFunctions+=1
            elif memberdef.get_kind() in variableLikeKind:
                metrics.numVariables+=1
                if is_documented(memberdef):
                    metrics.numDocVariables+=1
        #for param in memberdef.get_param():
        # name = ''
        # if param.get_defname():
        # name = param.get_defname()
        # if param.get_declname():
        # name = param.get_declname()
        # print("param '{}':'{}'".format(linked_text_to_string(param.get_type()),name))
        metrics.numParams+=len(memberdef.get_param())
        if memberdef.get_type() and memberdef.get_type()!="void" and linked_text_to_string(memberdef.get_type()):
            metrics.numParams+=1 # count non-void return types as well
            #print("returns '{}'".format(linked_text_to_string(memberdef.get_type())))
References is_documented(), len, linked_text_to_string(), section_is_private(), section_is_protected(), and section_is_public().
Referenced by parse_sections(), and metrics.Metrics.print().
parse_sections()
def metrics.parse_sections (compounddef, metrics)
Definition at line 170 of file metrics.py.
def parse_sections(compounddef,metrics):
    for sectiondef in compounddef.get_sectiondef():
        parse_members(compounddef,sectiondef,metrics)
References parse_members().
Referenced by parse_compound(), and metrics.Metrics.print().
section_is_private()
def metrics.section_is_private (sectionkind)
Definition at line 102 of file metrics.py.
def section_is_private(sectionkind):
    return sectionkind in [DoxSectionKind.PRIVATETYPE,
                           DoxSectionKind.PRIVATEFUNC,
                           DoxSectionKind.PRIVATEATTRIB,
                           DoxSectionKind.PRIVATESLOT,
                           DoxSectionKind.PRIVATESTATICFUNC,
                           DoxSectionKind.PRIVATESTATICATTRIB]
Referenced by parse_members(), metrics.Metrics.print(), and section_is_public().
section_is_protected()
def metrics.section_is_protected (sectionkind)
Definition at line 94 of file metrics.py.
def section_is_protected(sectionkind):
    return sectionkind in [DoxSectionKind.PROTECTEDTYPE,
                           DoxSectionKind.PROTECTEDFUNC,
                           DoxSectionKind.PROTECTEDATTRIB,
                           DoxSectionKind.PROTECTEDSLOT,
                           DoxSectionKind.PROTECTEDSTATICFUNC,
                           DoxSectionKind.PROTECTEDSTATICATTRIB]
Referenced by parse_members(), metrics.Metrics.print(), and section_is_public().
section_is_public()
def metrics.section_is_public (sectionkind)
Definition at line 110 of file metrics.py.
def section_is_public(sectionkind):
    return not section_is_protected(sectionkind) and not section_is_private(sectionkind)
References section_is_private(), and section_is_protected().
Referenced by parse_members(), and metrics.Metrics.print().
usage()
def metrics.usage ()
Definition at line 212 of file metrics.py.
def usage():
    print("Usage {0} <xml_output_dir>".format(sys.argv[0]))
    sys.exit(1)
References print().
Referenced by main(), and metrics.Metrics.print().