ghc::filesystem Namespace Reference
Namespaces
namespace detail
Classes
class basic_filebuf
class basic_fstream
class basic_ifstream
class basic_ofstream
class directory_entry
class directory_iterator
class file_status
class filesystem_error
class not_implemented_exception
class path
class path_helper_base
class recursive_directory_iterator
struct space_info
class u8arguments
Typedefs
using file_time_type = std::chrono::time_point< std::chrono::system_clock >
typedef basic_filebuf< char > filebuf
typedef basic_filebuf< wchar_t > wfilebuf
typedef basic_ifstream< char > ifstream
typedef basic_ifstream< wchar_t > wifstream
typedef basic_ofstream< char > ofstream
typedef basic_ofstream< wchar_t > wofstream
typedef basic_fstream< char > fstream
typedef basic_fstream< wchar_t > wfstream
Enumerations
enum class file_type {
none
, not_found
, regular
, directory
,
symlink
, block
, character
, fifo
,
socket
, unknown
, none
, not_found
,
regular
, directory
, symlink
, block
,
character
, fifo
, socket
, unknown
 }
enum class perms : uint16_t {
none = 0
, owner_read = 0400
, owner_write = 0200
, owner_exec = 0100
,
owner_all = 0700
, group_read = 040
, group_write = 020
, group_exec = 010
,
group_all = 070
, others_read = 04
, others_write = 02
, others_exec = 01
,
others_all = 07
, all = 0777
, set_uid = 04000
, set_gid = 02000
,
sticky_bit = 01000
, mask = 07777
, unknown = 0xffff
, none = 0
,
owner_read = 0400
, owner_write = 0200
, owner_exec = 0100
, owner_all = 0700
,
group_read = 040
, group_write = 020
, group_exec = 010
, group_all = 070
,
others_read = 04
, others_write = 02
, others_exec = 01
, others_all = 07
,
all = 0777
, set_uid = 04000
, set_gid = 02000
, sticky_bit = 01000
,
mask = 07777
, unknown = 0xffff
 }
enum class perm_options : uint16_t {
replace = 3
, add = 1
, remove = 2
, nofollow = 4
,
replace = 3
, add = 1
, remove = 2
, nofollow = 4
 }
enum class copy_options : uint16_t {
none = 0
, skip_existing = 1
, overwrite_existing = 2
, update_existing = 4
,
recursive = 8
, copy_symlinks = 0x10
, skip_symlinks = 0x20
, directories_only = 0x40
,
create_symlinks = 0x80
, create_hard_links = 0x100
, none = 0
, skip_existing = 1
,
overwrite_existing = 2
, update_existing = 4
, recursive = 8
, copy_symlinks = 0x10
,
skip_symlinks = 0x20
, directories_only = 0x40
, create_symlinks = 0x80
, create_hard_links = 0x100
 }
enum class directory_options : uint16_t {
none = 0
, follow_directory_symlink = 1
, skip_permission_denied = 2
, none = 0
,
follow_directory_symlink = 1
, skip_permission_denied = 2
 }
enum class file_type {
none
, not_found
, regular
, directory
,
symlink
, block
, character
, fifo
,
socket
, unknown
, none
, not_found
,
regular
, directory
, symlink
, block
,
character
, fifo
, socket
, unknown
 }
enum class perms : uint16_t {
none = 0
, owner_read = 0400
, owner_write = 0200
, owner_exec = 0100
,
owner_all = 0700
, group_read = 040
, group_write = 020
, group_exec = 010
,
group_all = 070
, others_read = 04
, others_write = 02
, others_exec = 01
,
others_all = 07
, all = 0777
, set_uid = 04000
, set_gid = 02000
,
sticky_bit = 01000
, mask = 07777
, unknown = 0xffff
, none = 0
,
owner_read = 0400
, owner_write = 0200
, owner_exec = 0100
, owner_all = 0700
,
group_read = 040
, group_write = 020
, group_exec = 010
, group_all = 070
,
others_read = 04
, others_write = 02
, others_exec = 01
, others_all = 07
,
all = 0777
, set_uid = 04000
, set_gid = 02000
, sticky_bit = 01000
,
mask = 07777
, unknown = 0xffff
 }
enum class perm_options : uint16_t {
replace = 3
, add = 1
, remove = 2
, nofollow = 4
,
replace = 3
, add = 1
, remove = 2
, nofollow = 4
 }
enum class copy_options : uint16_t {
none = 0
, skip_existing = 1
, overwrite_existing = 2
, update_existing = 4
,
recursive = 8
, copy_symlinks = 0x10
, skip_symlinks = 0x20
, directories_only = 0x40
,
create_symlinks = 0x80
, create_hard_links = 0x100
, none = 0
, skip_existing = 1
,
overwrite_existing = 2
, update_existing = 4
, recursive = 8
, copy_symlinks = 0x10
,
skip_symlinks = 0x20
, directories_only = 0x40
, create_symlinks = 0x80
, create_hard_links = 0x100
 }
enum class directory_options : uint16_t {
none = 0
, follow_directory_symlink = 1
, skip_permission_denied = 2
, none = 0
,
follow_directory_symlink = 1
, skip_permission_denied = 2
 }
Functions
GHC_FS_API void swap (path &lhs, path &rhs) noexcept
GHC_FS_API size_t hash_value (const path &p) noexcept
GHC_FS_API bool operator== (const path &lhs, const path &rhs) noexcept
GHC_FS_API bool operator!= (const path &lhs, const path &rhs) noexcept
GHC_FS_API bool operator< (const path &lhs, const path &rhs) noexcept
GHC_FS_API bool operator<= (const path &lhs, const path &rhs) noexcept
GHC_FS_API bool operator> (const path &lhs, const path &rhs) noexcept
GHC_FS_API bool operator>= (const path &lhs, const path &rhs) noexcept
GHC_FS_API path operator/ (const path &lhs, const path &rhs)
template<class charT , class traits >
std::basic_ostream< charT, traits > & operator<< (std::basic_ostream< charT, traits > &os, const path &p)
template<class charT , class traits >
std::basic_istream< charT, traits > & operator>> (std::basic_istream< charT, traits > &is, path &p)
template<class Source , typename = path::path_from_string<Source>>
path u8path (const Source &source)
template<class InputIterator >
path u8path (InputIterator first, InputIterator last)
GHC_FS_API directory_iterator begin (directory_iterator iter) noexcept
GHC_FS_API directory_iterator end (const directory_iterator &) noexcept
GHC_FS_API recursive_directory_iterator begin (recursive_directory_iterator iter) noexcept
GHC_FS_API recursive_directory_iterator end (const recursive_directory_iterator &) noexcept
GHC_FS_API path absolute (const path &p, std::error_code &ec)
GHC_FS_API path canonical (const path &p, std::error_code &ec)
GHC_FS_API void copy (const path &from, const path &to, std::error_code &ec) noexcept
GHC_FS_API void copy (const path &from, const path &to, copy_options options, std::error_code &ec) noexcept
GHC_FS_API bool copy_file (const path &from, const path &to, std::error_code &ec) noexcept
GHC_FS_API bool copy_file (const path &from, const path &to, copy_options option, std::error_code &ec) noexcept
GHC_FS_API void copy_symlink (const path &existing_symlink, const path &new_symlink, std::error_code &ec) noexcept
GHC_FS_API bool create_directories (const path &p, std::error_code &ec) noexcept
GHC_FS_API bool create_directory (const path &p, std::error_code &ec) noexcept
GHC_FS_API bool create_directory (const path &p, const path &attributes, std::error_code &ec) noexcept
GHC_FS_API void create_directory_symlink (const path &to, const path &new_symlink, std::error_code &ec) noexcept
GHC_FS_API void create_symlink (const path &to, const path &new_symlink, std::error_code &ec) noexcept
GHC_FS_API path current_path (std::error_code &ec)
GHC_FS_API void current_path (const path &p, std::error_code &ec) noexcept
GHC_FS_API bool exists (file_status s) noexcept
GHC_FS_API bool exists (const path &p, std::error_code &ec) noexcept
GHC_FS_API bool equivalent (const path &p1, const path &p2, std::error_code &ec) noexcept
GHC_FS_API uintmax_t file_size (const path &p, std::error_code &ec) noexcept
GHC_FS_API bool is_block_file (file_status s) noexcept
GHC_FS_API bool is_block_file (const path &p, std::error_code &ec) noexcept
GHC_FS_API bool is_character_file (file_status s) noexcept
GHC_FS_API bool is_character_file (const path &p, std::error_code &ec) noexcept
GHC_FS_API bool is_directory (file_status s) noexcept
GHC_FS_API bool is_directory (const path &p, std::error_code &ec) noexcept
GHC_FS_API bool is_empty (const path &p, std::error_code &ec) noexcept
GHC_FS_API bool is_fifo (file_status s) noexcept
GHC_FS_API bool is_fifo (const path &p, std::error_code &ec) noexcept
GHC_FS_API bool is_other (file_status s) noexcept
GHC_FS_API bool is_other (const path &p, std::error_code &ec) noexcept
GHC_FS_API bool is_regular_file (file_status s) noexcept
GHC_FS_API bool is_regular_file (const path &p, std::error_code &ec) noexcept
GHC_FS_API bool is_socket (file_status s) noexcept
GHC_FS_API bool is_socket (const path &p, std::error_code &ec) noexcept
GHC_FS_API bool is_symlink (file_status s) noexcept
GHC_FS_API bool is_symlink (const path &p, std::error_code &ec) noexcept
GHC_FS_API file_time_type last_write_time (const path &p, std::error_code &ec) noexcept
GHC_FS_API void last_write_time (const path &p, file_time_type new_time, std::error_code &ec) noexcept
GHC_FS_API void permissions (const path &p, perms prms, std::error_code &ec) noexcept
GHC_FS_API void permissions (const path &p, perms prms, perm_options opts, std::error_code &ec) noexcept
GHC_FS_API path proximate (const path &p, std::error_code &ec)
GHC_FS_API path proximate (const path &p, const path &base, std::error_code &ec)
GHC_FS_API path read_symlink (const path &p, std::error_code &ec)
GHC_FS_API path relative (const path &p, std::error_code &ec)
GHC_FS_API path relative (const path &p, const path &base, std::error_code &ec)
GHC_FS_API bool remove (const path &p, std::error_code &ec) noexcept
GHC_FS_API uintmax_t remove_all (const path &p, std::error_code &ec) noexcept
GHC_FS_API void rename (const path &from, const path &to, std::error_code &ec) noexcept
GHC_FS_API void resize_file (const path &p, uintmax_t size, std::error_code &ec) noexcept
GHC_FS_API space_info space (const path &p, std::error_code &ec) noexcept
GHC_FS_API file_status status (const path &p, std::error_code &ec) noexcept
GHC_FS_API bool status_known (file_status s) noexcept
GHC_FS_API file_status symlink_status (const path &p, std::error_code &ec) noexcept
GHC_FS_API path temp_directory_path (std::error_code &ec) noexcept
GHC_FS_API path weakly_canonical (const path &p, std::error_code &ec) noexcept
GHC_FS_API void create_hard_link (const path &to, const path &new_hard_link, std::error_code &ec) noexcept
GHC_FS_API uintmax_t hard_link_count (const path &p, std::error_code &ec) noexcept
template<typename Enum >
constexpr detail::EnableBitmask< Enum > operator& (Enum X, Enum Y)
template<typename Enum >
constexpr detail::EnableBitmask< Enum > operator| (Enum X, Enum Y)
template<typename Enum >
constexpr detail::EnableBitmask< Enum > operator^ (Enum X, Enum Y)
template<typename Enum >
constexpr detail::EnableBitmask< Enum > operator~ (Enum X)
template<typename Enum >
detail::EnableBitmask< Enum > & operator&= (Enum &X, Enum Y)
template<typename Enum >
detail::EnableBitmask< Enum > & operator|= (Enum &X, Enum Y)
template<typename Enum >
detail::EnableBitmask< Enum > & operator^= (Enum &X, Enum Y)
Typedef Documentation
file_time_type
typedef std::chrono::time_point< std::chrono::system_clock > ghc::filesystem::file_time_type
Definition at line 810 of file filesystem.hpp.
filebuf
typedef basic_filebuf< char > ghc::filesystem::filebuf
Definition at line 1243 of file filesystem.hpp.
fstream
typedef basic_fstream< char > ghc::filesystem::fstream
Definition at line 1249 of file filesystem.hpp.
ifstream
typedef basic_ifstream< char > ghc::filesystem::ifstream
Definition at line 1245 of file filesystem.hpp.
ofstream
typedef basic_ofstream< char > ghc::filesystem::ofstream
Definition at line 1247 of file filesystem.hpp.
wfilebuf
typedef basic_filebuf< wchar_t > ghc::filesystem::wfilebuf
Definition at line 1244 of file filesystem.hpp.
wfstream
typedef basic_fstream< wchar_t > ghc::filesystem::wfstream
Definition at line 1250 of file filesystem.hpp.
wifstream
typedef basic_ifstream< wchar_t > ghc::filesystem::wifstream
Definition at line 1246 of file filesystem.hpp.
wofstream
typedef basic_ofstream< wchar_t > ghc::filesystem::wofstream
Definition at line 1248 of file filesystem.hpp.
Enumeration Type Documentation
copy_options [1/2]
enum class ghc::filesystem::copy_options : uint16_t [strong]
Enumerator
none
skip_existing
overwrite_existing
update_existing
recursive
copy_symlinks
skip_symlinks
directories_only
create_symlinks
create_hard_links
none
skip_existing
overwrite_existing
update_existing
recursive
copy_symlinks
skip_symlinks
directories_only
create_symlinks
create_hard_links
Definition at line 759 of file filesystem.hpp.
                        : uint16_t {
    none = 0,
    skip_existing = 1,
    overwrite_existing = 2,
    update_existing = 4,
    recursive = 8,
    copy_symlinks = 0x10,
    skip_symlinks = 0x20,
    directories_only = 0x40,
    create_symlinks = 0x80,
#ifndef GHC_OS_WEB
    create_hard_links = 0x100
#endif
};
copy_options [2/2]
enum class ghc::filesystem::copy_options : uint16_t [strong]
Enumerator
none
skip_existing
overwrite_existing
update_existing
recursive
copy_symlinks
skip_symlinks
directories_only
create_symlinks
create_hard_links
none
skip_existing
overwrite_existing
update_existing
recursive
copy_symlinks
skip_symlinks
directories_only
create_symlinks
create_hard_links
Definition at line 759 of file filesystem.hpp.
                        : uint16_t {
    none = 0,
    skip_existing = 1,
    overwrite_existing = 2,
    update_existing = 4,
    recursive = 8,
    copy_symlinks = 0x10,
    skip_symlinks = 0x20,
    directories_only = 0x40,
    create_symlinks = 0x80,
#ifndef GHC_OS_WEB
    create_hard_links = 0x100
#endif
};
directory_options [1/2]
enum class ghc::filesystem::directory_options : uint16_t [strong]
Enumerator
none
follow_directory_symlink
skip_permission_denied
none
follow_directory_symlink
skip_permission_denied
Definition at line 779 of file filesystem.hpp.
                             : uint16_t {
    none = 0,
    follow_directory_symlink = 1,
    skip_permission_denied = 2,
};
directory_options [2/2]
enum class ghc::filesystem::directory_options : uint16_t [strong]
Enumerator
none
follow_directory_symlink
skip_permission_denied
none
follow_directory_symlink
skip_permission_denied
Definition at line 779 of file filesystem.hpp.
                             : uint16_t {
    none = 0,
    follow_directory_symlink = 1,
    skip_permission_denied = 2,
};
file_type [1/2]
enum class ghc::filesystem::file_type [strong]
Enumerator
none
not_found
regular
directory
symlink
block
character
fifo
socket
unknown
none
not_found
regular
directory
symlink
block
character
fifo
socket
unknown
Definition at line 709 of file filesystem.hpp.
                     {
    none,
    not_found,
    regular,
    directory,
    symlink,
    block,
    character,
    fifo,
    socket,
    unknown,
};
file_type [2/2]
enum class ghc::filesystem::file_type [strong]
Enumerator
none
not_found
regular
directory
symlink
block
character
fifo
socket
unknown
none
not_found
regular
directory
symlink
block
character
fifo
socket
unknown
Definition at line 709 of file filesystem.hpp.
                     {
    none,
    not_found,
    regular,
    directory,
    symlink,
    block,
    character,
    fifo,
    socket,
    unknown,
};
perm_options [1/2]
enum class ghc::filesystem::perm_options : uint16_t [strong]
Enumerator
replace
add
remove
nofollow
replace
add
remove
nofollow
Definition at line 751 of file filesystem.hpp.
                        : uint16_t {
    replace = 3,
    add = 1,
    remove = 2,
    nofollow = 4,
};
perm_options [2/2]
enum class ghc::filesystem::perm_options : uint16_t [strong]
Enumerator
replace
add
remove
nofollow
replace
add
remove
nofollow
Definition at line 751 of file filesystem.hpp.
                        : uint16_t {
    replace = 3,
    add = 1,
    remove = 2,
    nofollow = 4,
};
perms [1/2]
enum class ghc::filesystem::perms : uint16_t [strong]
Enumerator
none
owner_read
owner_write
owner_exec
owner_all
group_read
group_write
group_exec
group_all
others_read
others_write
others_exec
others_all
all
set_uid
set_gid
sticky_bit
mask
unknown
none
owner_read
owner_write
owner_exec
owner_all
group_read
group_write
group_exec
group_all
others_read
others_write
others_exec
others_all
all
set_uid
set_gid
sticky_bit
mask
unknown
Definition at line 723 of file filesystem.hpp.
                 : uint16_t {
    none = 0,
    owner_read = 0400,
    owner_write = 0200,
    owner_exec = 0100,
    owner_all = 0700,
    group_read = 040,
    group_write = 020,
    group_exec = 010,
    group_all = 070,
    others_read = 04,
    others_write = 02,
    others_exec = 01,
    others_all = 07,
    all = 0777,
    set_uid = 04000,
    set_gid = 02000,
    sticky_bit = 01000,
    mask = 07777,
    unknown = 0xffff
};
perms [2/2]
enum class ghc::filesystem::perms : uint16_t [strong]
Enumerator
none
owner_read
owner_write
owner_exec
owner_all
group_read
group_write
group_exec
group_all
others_read
others_write
others_exec
others_all
all
set_uid
set_gid
sticky_bit
mask
unknown
none
owner_read
owner_write
owner_exec
owner_all
group_read
group_write
group_exec
group_all
others_read
others_write
others_exec
others_all
all
set_uid
set_gid
sticky_bit
mask
unknown
Definition at line 723 of file filesystem.hpp.
                 : uint16_t {
    none = 0,
    owner_read = 0400,
    owner_write = 0200,
    owner_exec = 0100,
    owner_all = 0700,
    group_read = 040,
    group_write = 020,
    group_exec = 010,
    group_all = 070,
    others_read = 04,
    others_write = 02,
    others_exec = 01,
    others_all = 07,
    all = 0777,
    set_uid = 04000,
    set_gid = 02000,
    sticky_bit = 01000,
    mask = 07777,
    unknown = 0xffff
};
Function Documentation
absolute()
GHC_INLINE path ghc::filesystem::absolute (const path & p, std::error_code & ec)
Definition at line 3542 of file filesystem.hpp.
{
    ec.clear();
#ifdef GHC_OS_WINDOWS
    if (p.empty()) {
        return absolute(current_path(ec), ec) / "";
    }
    ULONG size = ::GetFullPathNameW(GHC_NATIVEWP(p), 0, 0, 0);
    if (size) {
        std::vector<wchar_t> buf(size, 0);
        ULONG s2 = GetFullPathNameW(GHC_NATIVEWP(p), size, buf.data(), nullptr);
        if (s2 && s2 < size) {
            path result = path(std::wstring(buf.data(), s2));
            if (p.filename() == ".") {
                result /= ".";
            }
            return result;
        }
    }
    ec = detail::make_system_error();
    return path();
#else
    path base = current_path(ec);
    if (!ec) {
        if (p.empty()) {
            return base / p;
        }
        if (p.has_root_name()) {
            if (p.has_root_directory()) {
                return p;
            }
            else {
                return p.root_name() / base.root_directory() / base.relative_path() / p.relative_path();
            }
        }
        else {
            if (p.has_root_directory()) {
                return base.root_name() / p;
            }
            else {
                return base / p;
            }
        }
    }
    ec = detail::make_system_error();
    return path();
#endif
}
References absolute(), ghc::filesystem::path::clear(), current_path(), GHC_NATIVEWP, ghc::filesystem::detail::make_system_error(), p, ghc::filesystem::path::relative_path(), ghc::filesystem::path::root_directory(), ghc::filesystem::path::root_name(), and size.
Referenced by absolute(), and Dir::absPath().
begin() [1/2]
GHC_INLINE directory_iterator ghc::filesystem::begin (directory_iterator iter) [noexcept]
Definition at line 5749 of file filesystem.hpp.
{
    return iter;
}
Referenced by addWords(), IterableStack< T, Container >::begin(), FlowChart::buildCommentNodes(), buildDirectories(), clearBlock(), HtmlDocVisitor::forceEndParagraph(), HtmlDocVisitor::forceStartParagraph(), MemberLists::get(), insideStyleChangeThatIsOutsideParagraph(), ExampleList::inSort(), isSeparatedParagraph(), joinLabels(), mergeHtmlAttributes(), HtmlDocVisitor::operator()(), parseInput(), portable_memmem(), searchInputFiles(), selectBlock(), and HtmlHelpIndex::writeFields().
begin() [2/2]
GHC_INLINE recursive_directory_iterator ghc::filesystem::begin (recursive_directory_iterator iter) [noexcept]
Definition at line 5926 of file filesystem.hpp.
{
    return iter;
}
canonical()
GHC_INLINE path ghc::filesystem::canonical (const path & p, std::error_code & ec)
Definition at line 3603 of file filesystem.hpp.
{
    if (p.empty()) {
        ec = detail::make_error_code(detail::portable_error::not_found);
        return path();
    }
    path work = p.is_absolute() ? p : absolute(p, ec);
    path result;
    auto fs = status(work, ec);
    if (ec) {
        return path();
    }
    if (fs.type() == file_type::not_found) {
        ec = detail::make_error_code(detail::portable_error::not_found);
        return path();
    }
    bool redo;
    do {
        auto rootPathLen = work._prefixLength + work.root_name_length() + (work.has_root_directory() ? 1 : 0);
        redo = false;
        result.clear();
        for (auto pe : work) {
            if (pe.empty() || pe == ".") {
                continue;
            }
            else if (pe == "..") {
                result = result.parent_path();
                continue;
            }
            else if ((result / pe).string().length() <= rootPathLen) {
                result /= pe;
                continue;
            }
            auto sls = symlink_status(result / pe, ec);
            if (ec) {
                return path();
            }
            if (is_symlink(sls)) {
                redo = true;
                auto target = read_symlink(result / pe, ec);
                if (ec) {
                    return path();
                }
                if (target.is_absolute()) {
                    result = target;
                    continue;
                }
                else {
                    result /= target;
                    continue;
                }
            }
            else {
                result /= pe;
            }
        }
        work = result;
    } while (redo);
    ec.clear();
    return result;
}
Referenced by copy(), and weakly_canonical().
copy() [1/2]
GHC_INLINE void ghc::filesystem::copy (const path & from, const path & to, copy_options options, std::error_code & ec) [noexcept]
Definition at line 3687 of file filesystem.hpp.
{
    std::error_code tec;
    file_status fs_from, fs_to;
    ec.clear();
    if ((options & (copy_options::skip_symlinks | copy_options::copy_symlinks | copy_options::create_symlinks)) != copy_options::none) {
        fs_from = symlink_status(from, ec);
    }
    else {
        fs_from = status(from, ec);
    }
    if (!exists(fs_from)) {
        if (!ec) {
            ec = detail::make_error_code(detail::portable_error::not_found);
        }
        return;
    }
    if ((options & (copy_options::skip_symlinks | copy_options::create_symlinks)) != copy_options::none) {
        fs_to = symlink_status(to, tec);
    }
    else {
        fs_to = status(to, tec);
    }
    if (is_other(fs_from) || is_other(fs_to) || (is_directory(fs_from) && is_regular_file(fs_to)) || (exists(fs_to) && equivalent(from, to, ec))) {
        ec = detail::make_error_code(detail::portable_error::invalid_argument);
    }
    else if (is_symlink(fs_from)) {
        if ((options & copy_options::skip_symlinks) == copy_options::none) {
            if (!exists(fs_to) && (options & copy_options::copy_symlinks) != copy_options::none) {
                copy_symlink(from, to, ec);
            }
            else {
                ec = detail::make_error_code(detail::portable_error::invalid_argument);
            }
        }
    }
    else if (is_regular_file(fs_from)) {
        if ((options & copy_options::directories_only) == copy_options::none) {
            if ((options & copy_options::create_symlinks) != copy_options::none) {
                create_symlink(from.is_absolute() ? from : canonical(from, ec), to, ec);
            }
#ifndef GHC_OS_WEB
            else if ((options & copy_options::create_hard_links) != copy_options::none) {
                create_hard_link(from, to, ec);
            }
#endif
            else if (is_directory(fs_to)) {
                copy_file(from, to / from.filename(), options, ec);
            }
            else {
                copy_file(from, to, options, ec);
            }
        }
    }
#ifdef LWG_2682_BEHAVIOUR
    else if (is_directory(fs_from) && (options & copy_options::create_symlinks) != copy_options::none) {
        ec = detail::make_error_code(detail::portable_error::is_a_directory);
    }
#endif
    else if (is_directory(fs_from) && (options == copy_options::none || (options & copy_options::recursive) != copy_options::none)) {
        if (!exists(fs_to)) {
            create_directory(to, from, ec);
            if (ec) {
                return;
            }
        }
        for (auto iter = directory_iterator(from, ec); iter != directory_iterator(); iter.increment(ec)) {
            if (!ec) {
                copy(iter->path(), to / iter->path().filename(), options | static_cast<copy_options>(0x8000), ec);
            }
            if (ec) {
                return;
            }
        }
    }
    return;
}
References canonical(), copy(), copy_file(), copy_symlink(), copy_symlinks, create_directory(), create_hard_link(), create_hard_links, create_symlink(), create_symlinks, directories_only, equivalent(), exists(), ghc::filesystem::detail::invalid_argument, ghc::filesystem::detail::is_a_directory, is_directory(), is_other(), is_regular_file(), is_symlink(), ghc::filesystem::detail::make_error_code(), none, ghc::filesystem::detail::not_found, recursive, skip_symlinks, status(), and symlink_status().
copy() [2/2]
GHC_INLINE void ghc::filesystem::copy (const path & from, const path & to, std::error_code & ec) [noexcept]
Definition at line 3682 of file filesystem.hpp.
{
    copy(from, to, copy_options::none, ec);
}
References copy(), and none.
Referenced by copy(), Dir::copy(), copyFile(), and Entry::copyToSubEntry().
copy_file() [1/2]
GHC_INLINE bool ghc::filesystem::copy_file (const path & from, const path & to, copy_options option, std::error_code & ec) [noexcept]
Definition at line 3787 of file filesystem.hpp.
{
    std::error_code tecf, tect;
    auto sf = status(from, tecf);
    auto st = status(to, tect);
    bool overwrite = false;
    ec.clear();
    if (!is_regular_file(sf)) {
        ec = tecf;
        return false;
    }
    if (exists(st) && (!is_regular_file(st) || equivalent(from, to, ec) || (options & (copy_options::skip_existing | copy_options::overwrite_existing | copy_options::update_existing)) == copy_options::none)) {
        ec = tect ? tect : detail::make_error_code(detail::portable_error::exists);
        return false;
    }
    if (exists(st)) {
        if ((options & copy_options::update_existing) == copy_options::update_existing) {
            auto from_time = last_write_time(from, ec);
            if (ec) {
                ec = detail::make_system_error();
                return false;
            }
            auto to_time = last_write_time(to, ec);
            if (ec) {
                ec = detail::make_system_error();
                return false;
            }
            if (from_time <= to_time) {
                return false;
            }
        }
        overwrite = true;
    }
#ifdef GHC_OS_WINDOWS
    if (!::CopyFileW(GHC_NATIVEWP(from), GHC_NATIVEWP(to), !overwrite)) {
        ec = detail::make_system_error();
        return false;
    }
    return true;
#else
    std::vector<char> buffer(16384, '\0');
    int in = -1, out = -1;
    if ((in = ::open(from.c_str(), O_RDONLY)) < 0) {
        ec = detail::make_system_error();
        return false;
    }
    int mode = O_CREAT | O_WRONLY | O_TRUNC;
    if (!overwrite) {
        mode |= O_EXCL;
    }
    if ((out = ::open(to.c_str(), mode, static_cast<int>(sf.permissions() & perms::all))) < 0) {
        ec = detail::make_system_error();
        ::close(in);
        return false;
    }
    ssize_t br, bw;
    while ((br = ::read(in, buffer.data(), buffer.size())) > 0) {
        ssize_t offset = 0;
        do {
            if ((bw = ::write(out, buffer.data() + offset, static_cast<size_t>(br))) > 0) {
                br -= bw;
                offset += bw;
            }
            else if (bw < 0) {
                ec = detail::make_system_error();
                ::close(in);
                ::close(out);
                return false;
            }
        } while (br);
    }
    ::close(in);
    ::close(out);
    return true;
#endif
}
References all, close(), equivalent(), ghc::filesystem::detail::exists, exists(), GHC_NATIVEWP, is_regular_file(), last_write_time(), ghc::filesystem::detail::make_error_code(), ghc::filesystem::detail::make_system_error(), mode, none, offset, open(), out, overwrite_existing, read(), skip_existing, status(), update_existing, and write().
copy_file() [2/2]
GHC_INLINE bool ghc::filesystem::copy_file (const path & from, const path & to, std::error_code & ec) [noexcept]
Definition at line 3782 of file filesystem.hpp.
{
    return copy_file(from, to, copy_options::none, ec);
}
References copy_file(), and none.
Referenced by copy(), and copy_file().
copy_symlink()
GHC_INLINE void ghc::filesystem::copy_symlink (const path & existing_symlink, const path & new_symlink, std::error_code & ec) [noexcept]
Definition at line 3875 of file filesystem.hpp.
{
    ec.clear();
    auto to = read_symlink(existing_symlink, ec);
    if (!ec) {
        if (exists(to, ec) && is_directory(to, ec)) {
            create_directory_symlink(to, new_symlink, ec);
        }
        else {
            create_symlink(to, new_symlink, ec);
        }
    }
}
References create_directory_symlink(), create_symlink(), exists(), is_directory(), and read_symlink().
Referenced by copy().
create_directories()
GHC_INLINE bool ghc::filesystem::create_directories (const path & p, std::error_code & ec) [noexcept]
Definition at line 3901 of file filesystem.hpp.
{
    path current;
    ec.clear();
    bool didCreate = false;
    for (path::string_type part : p) {
        current /= part;
        if (current != p.root_name() && current != p.root_path()) {
            std::error_code tec;
            auto fs = status(current, tec);
            if (tec && fs.type() != file_type::not_found) {
                ec = tec;
                return false;
            }
            if (!exists(fs)) {
                create_directory(current, ec);
                if (ec) {
                    std::error_code tmp_ec;
                    if (is_directory(current, tmp_ec)) {
                        ec.clear();
                    }
                    else {
                        return false;
                    }
                }
                didCreate = true;
            }
#ifndef LWG_2935_BEHAVIOUR
            else if (!is_directory(fs)) {
                ec = detail::make_error_code(detail::portable_error::exists);
                return false;
            }
#endif
        }
    }
    return didCreate;
}
References ghc::filesystem::path::clear(), create_directory(), ghc::filesystem::detail::exists, exists(), is_directory(), ghc::filesystem::detail::make_error_code(), not_found, p, and status().
create_directory() [1/2]
GHC_INLINE bool ghc::filesystem::create_directory (const path & p, const path & attributes, std::error_code & ec) [noexcept]
Definition at line 3968 of file filesystem.hpp.
{
    std::error_code tec;
    ec.clear();
    auto fs = status(p, tec);
#ifdef LWG_2935_BEHAVIOUR
    if (status_known(fs) && exists(fs)) {
        return false;
    }
#else
    if (status_known(fs) && exists(fs) && is_directory(fs)) {
        return false;
    }
#endif
#ifdef GHC_OS_WINDOWS
    if (!attributes.empty()) {
        if (!::CreateDirectoryExW(GHC_NATIVEWP(attributes), GHC_NATIVEWP(p), NULL)) {
            ec = detail::make_system_error();
            return false;
        }
    }
    else if (!::CreateDirectoryW(GHC_NATIVEWP(p), NULL)) {
        ec = detail::make_system_error();
        return false;
    }
#else
    ::mode_t attribs = static_cast<mode_t>(perms::all);
    if (!attributes.empty()) {
        struct ::stat fileStat;
        if (::stat(attributes.c_str(), &fileStat) != 0) {
            ec = detail::make_system_error();
            return false;
        }
        attribs = fileStat.st_mode;
    }
    if (::mkdir(p.c_str(), attribs) != 0) {
        ec = detail::make_system_error();
        return false;
    }
#endif
    return true;
}
References all, exists(), GHC_NATIVEWP, is_directory(), ghc::filesystem::detail::make_system_error(), p, status(), and status_known().
create_directory() [2/2]
GHC_INLINE bool ghc::filesystem::create_directory (const path & p, std::error_code & ec) [noexcept]
Definition at line 3951 of file filesystem.hpp.
{
    return create_directory(p, path(), ec);
}
References create_directory(), and p.
Referenced by copy(), create_directories(), create_directory(), and Dir::mkdir().
create_directory_symlink()
GHC_INLINE void ghc::filesystem::create_directory_symlink (const path & to, const path & new_symlink, std::error_code & ec) [noexcept]
Definition at line 4022 of file filesystem.hpp.
{
    detail::create_symlink(to, new_symlink, true, ec);
}
References ghc::filesystem::detail::create_symlink().
Referenced by copy_symlink().
create_hard_link()
GHC_INLINE void ghc::filesystem::create_hard_link (const path & to, const path & new_hard_link, std::error_code & ec) [noexcept]
Definition at line 4039 of file filesystem.hpp.
{
    detail::create_hardlink(to, new_hard_link, ec);
}
References ghc::filesystem::detail::create_hardlink().
Referenced by copy().
create_symlink()
GHC_INLINE void ghc::filesystem::create_symlink (const path & to, const path & new_symlink, std::error_code & ec) [noexcept]
Definition at line 4056 of file filesystem.hpp.
{
    detail::create_symlink(to, new_symlink, false, ec);
}
References ghc::filesystem::detail::create_symlink().
Referenced by copy(), and copy_symlink().
current_path() [1/2]
GHC_INLINE void ghc::filesystem::current_path (const path & p, std::error_code & ec) [noexcept]
Definition at line 4106 of file filesystem.hpp.
{
    ec.clear();
#ifdef GHC_OS_WINDOWS
    if (!::SetCurrentDirectoryW(GHC_NATIVEWP(p))) {
        ec = detail::make_system_error();
    }
#else
    if (::chdir(p.string().c_str()) == -1) {
        ec = detail::make_system_error();
    }
#endif
}
References ghc::filesystem::path::clear(), GHC_NATIVEWP, ghc::filesystem::detail::make_system_error(), and p.
current_path() [2/2]
GHC_INLINE path ghc::filesystem::current_path (std::error_code & ec)
Definition at line 4073 of file filesystem.hpp.
{
    ec.clear();
#ifdef GHC_OS_WINDOWS
    DWORD pathlen = ::GetCurrentDirectoryW(0, 0);
    std::unique_ptr<wchar_t[]> buffer(new wchar_t[size_t(pathlen) + 1]);
    if (::GetCurrentDirectoryW(pathlen, buffer.get()) == 0) {
        ec = detail::make_system_error();
        return path();
    }
    return path(std::wstring(buffer.get()), path::native_format);
#else
    size_t pathlen = static_cast<size_t>(std::max(int(::pathconf(".", _PC_PATH_MAX)), int(PATH_MAX)));
    std::unique_ptr<char[]> buffer(new char[pathlen + 1]);
    if (::getcwd(buffer.get(), pathlen) == nullptr) {
        ec = detail::make_system_error();
        return path();
    }
    return path(buffer.get());
#endif
}
References ghc::filesystem::path::clear(), ghc::filesystem::detail::make_system_error(), and ghc::filesystem::path::native_format.
Referenced by FileInfo::absFilePath(), absolute(), Dir::currentDirPath(), Dir::Dir(), relative(), and Dir::setCurrent().
end() [1/2]
GHC_INLINE directory_iterator ghc::filesystem::end (const directory_iterator &) [noexcept]
Definition at line 5754 of file filesystem.hpp.
{
    return directory_iterator();
}
Referenced by DocGroup::addDocs(), addMembersToMemberGroup(), addToIndices(), addWords(), SymbolListContext::alloc(), SymbolGroupContext::alloc(), buildDefineList(), buildDirectories(), DocParser::checkArgumentName(), clearBlock(), DocGroup::close(), convertCharEntitiesToUTF8(), IterableStack< T, Container >::end(), anonymous_namespace{tagreader.cpp}::TagFileParser::endElement(), endScope(), expandAliasRec(), externalRef(), DefinitionImpl::externalReference(), extractCanonicalType(), extractClassNameFromType(), extractDirection(), extractFromParens(), fileToString(), filterTitle(), findAndRemoveWord(), findClassRelation(), Markdown::findEndOfLine(), findTableColumns(), VariableContext::findVariable(), HtmlDocVisitor::forceEndParagraph(), HtmlDocVisitor::forceStartParagraph(), MemberLists::get(), getFortranDefs(), getResolvedNamespace(), getTemplateArgumentsInName(), DocPara::handleIncludeOperator(), ExampleList::inSort(), Markdown::isAtxHeader(), Markdown::isBlockCommand(), MemberDefImpl::isBriefSectionVisible(), isFencedCodeBlock(), isLinkRef(), isSeparatedParagraph(), Markdown::isSpecialCommand(), isTableBlock(), joinLabels(), linkifyText(), mergeHtmlAttributes(), normalizeNonTemplateArgumentsInString(), DocGroup::open(), HtmlDocVisitor::operator()(), ColorPicker::paintEvent(), VhdlDocGen::parseFuncProto(), parseInput(), SymbolListContext::Private::Private(), Markdown::processBlocks(), Markdown::processCodeSpan(), processConcatOperators(), Markdown::processInline(), Markdown::processQuotations(), QCString::quoted(), readAliases(), removeAnonymousScopes(), TemplateNodeMarkers::render(), replaceColorMarkers(), replaceNamespaceAliases(), resolveModuleProcedures(), searchInputFiles(), selectBlock(), split(), anonymous_namespace{tagreader.cpp}::TagFileParser::startElement(), stripEmptyLines(), QCString::stripWhiteSpace(), substEnvVarsInString(), substituteTemplateArgumentsInString(), substituteTemplatesInString(), TemplateNodeRange::TemplateNodeRange(), Markdown::writeBlockQuote(), writeBoxMemberList(), Markdown::writeCodeBlock(), writeDotDirDepGraph(), HtmlHelpIndex::writeFields(), writeMarkerList(), and Markdown::writeTableBlock().
end() [2/2]
GHC_INLINE recursive_directory_iterator ghc::filesystem::end (const recursive_directory_iterator &) [noexcept]
Definition at line 5931 of file filesystem.hpp.
{
    return recursive_directory_iterator();
}
equivalent()
GHC_INLINE bool ghc::filesystem::equivalent (const path & p1, const path & p2, std::error_code & ec) [noexcept]
Definition at line 4153 of file filesystem.hpp.
{
    ec.clear();
#ifdef GHC_OS_WINDOWS
    std::shared_ptr<void> file1(::CreateFileW(GHC_NATIVEWP(p1), 0, FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE, 0, OPEN_EXISTING, FILE_FLAG_BACKUP_SEMANTICS, 0), CloseHandle);
    auto e1 = ::GetLastError();
    std::shared_ptr<void> file2(::CreateFileW(GHC_NATIVEWP(p2), 0, FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE, 0, OPEN_EXISTING, FILE_FLAG_BACKUP_SEMANTICS, 0), CloseHandle);
    if (file1.get() == INVALID_HANDLE_VALUE || file2.get() == INVALID_HANDLE_VALUE) {
#ifdef LWG_2937_BEHAVIOUR
        ec = detail::make_system_error(e1 ? e1 : ::GetLastError());
#else
        if (file1 == file2) {
            ec = detail::make_system_error(e1 ? e1 : ::GetLastError());
        }
#endif
        return false;
    }
    BY_HANDLE_FILE_INFORMATION inf1, inf2;
    if (!::GetFileInformationByHandle(file1.get(), &inf1)) {
        ec = detail::make_system_error();
        return false;
    }
    if (!::GetFileInformationByHandle(file2.get(), &inf2)) {
        ec = detail::make_system_error();
        return false;
    }
    return inf1.ftLastWriteTime.dwLowDateTime == inf2.ftLastWriteTime.dwLowDateTime && inf1.ftLastWriteTime.dwHighDateTime == inf2.ftLastWriteTime.dwHighDateTime && inf1.nFileIndexHigh == inf2.nFileIndexHigh && inf1.nFileIndexLow == inf2.nFileIndexLow &&
           inf1.nFileSizeHigh == inf2.nFileSizeHigh && inf1.nFileSizeLow == inf2.nFileSizeLow && inf1.dwVolumeSerialNumber == inf2.dwVolumeSerialNumber;
#else
    struct ::stat s1, s2;
    auto rc1 = ::stat(p1.c_str(), &s1);
    auto e1 = errno;
    auto rc2 = ::stat(p2.c_str(), &s2);
    if (rc1 || rc2) {
#ifdef LWG_2937_BEHAVIOUR
        ec = detail::make_system_error(e1 ? e1 : errno);
#else
        if (rc1 && rc2) {
            ec = detail::make_system_error(e1 ? e1 : errno);
        }
#endif
        return false;
    }
    return s1.st_dev == s2.st_dev && s1.st_ino == s2.st_ino && s1.st_size == s2.st_size && s1.st_mtime == s2.st_mtime;
#endif
}
References errno, GHC_NATIVEWP, and ghc::filesystem::detail::make_system_error().
Referenced by copy(), and copy_file().
exists() [1/2]
GHC_INLINE bool ghc::filesystem::exists (const path & p, std::error_code & ec) [noexcept]
Definition at line 4132 of file filesystem.hpp.
{
    file_status s = status(p, ec);
    if (status_known(s)) {
        ec.clear();
    }
    return exists(s);
}
References exists(), p, s, status(), and status_known().
exists() [2/2]
GHC_INLINE bool ghc::filesystem::exists (file_status s) [noexcept]
Definition at line 4120 of file filesystem.hpp.
{
    return status_known(s) && s.type() != file_type::not_found;
}
References not_found, s, and status_known().
Referenced by copy(), copy_file(), copy_symlink(), create_directories(), create_directory(), FileInfo::exists(), exists(), Dir::exists(), GestaoHor::getDataAula(), is_other(), MainWindow::loadSettings(), readConfiguration(), remove_all(), MainWindow::runDoxygen(), and weakly_canonical().
file_size()
GHC_INLINE uintmax_t ghc::filesystem::file_size (const path & p, std::error_code & ec) [noexcept]
Definition at line 4212 of file filesystem.hpp.
{
    ec.clear();
#ifdef GHC_OS_WINDOWS
    WIN32_FILE_ATTRIBUTE_DATA attr;
    if (!GetFileAttributesExW(GHC_NATIVEWP(p), GetFileExInfoStandard, &attr)) {
        ec = detail::make_system_error();
        return static_cast<uintmax_t>(-1);
    }
    return static_cast<uintmax_t>(attr.nFileSizeHigh) << (sizeof(attr.nFileSizeHigh) * 8) | attr.nFileSizeLow;
#else
    struct ::stat fileStat;
    if (::stat(p.c_str(), &fileStat) == -1) {
        ec = detail::make_system_error();
        return static_cast<uintmax_t>(-1);
    }
    return static_cast<uintmax_t>(fileStat.st_size);
#endif
}
References GHC_NATIVEWP, if(), ghc::filesystem::detail::make_system_error(), and p.
Referenced by ghc::filesystem::directory_entry::file_size(), is_empty(), and FileInfo::size().
hard_link_count()
GHC_INLINE uintmax_t ghc::filesystem::hard_link_count (const path & p, std::error_code & ec) [noexcept]
Definition at line 4245 of file filesystem.hpp.
{
    ec.clear();
#ifdef GHC_OS_WINDOWS
    uintmax_t result = static_cast<uintmax_t>(-1);
    std::shared_ptr<void> file(::CreateFileW(GHC_NATIVEWP(p), 0, FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE, 0, OPEN_EXISTING, FILE_FLAG_BACKUP_SEMANTICS, 0), CloseHandle);
    BY_HANDLE_FILE_INFORMATION inf;
    if (file.get() == INVALID_HANDLE_VALUE) {
        ec = detail::make_system_error();
    }
    else {
        if (!::GetFileInformationByHandle(file.get(), &inf)) {
            ec = detail::make_system_error();
        }
        else {
            result = inf.nNumberOfLinks;
        }
    }
    return result;
#else
    uintmax_t result = 0;
    file_status fs = detail::status_ex(p, ec, nullptr, nullptr, &result, nullptr);
    if (fs.type() == file_type::not_found) {
        ec = detail::make_error_code(detail::portable_error::not_found);
    }
    return ec ? static_cast<uintmax_t>(-1) : result;
#endif
}
References caseconvert::file, GHC_NATIVEWP, ghc::filesystem::detail::make_error_code(), ghc::filesystem::detail::make_system_error(), not_found, ghc::filesystem::detail::not_found, p, and ghc::filesystem::detail::status_ex().
Referenced by ghc::filesystem::directory_entry::hard_link_count().
hash_value()
GHC_INLINE size_t ghc::filesystem::hash_value (const path & p) [noexcept]
Definition at line 3370 of file filesystem.hpp.
{
    return std::hash<std::string>()(p.generic_string());
}
is_block_file() [1/2]
GHC_INLINE bool ghc::filesystem::is_block_file (const path & p, std::error_code & ec) [noexcept]
Definition at line 4287 of file filesystem.hpp.
{
    return is_block_file(status(p, ec));
}
References is_block_file(), p, and status().
is_block_file() [2/2]
GHC_INLINE bool ghc::filesystem::is_block_file (file_status s) [noexcept]
Definition at line 4275 of file filesystem.hpp.
{
    return s.type() == file_type::block;
}
References block, and s.
Referenced by is_block_file().
is_character_file() [1/2]
GHC_INLINE bool ghc::filesystem::is_character_file (const path & p, std::error_code & ec) [noexcept]
Definition at line 4304 of file filesystem.hpp.
{
    return is_character_file(status(p, ec));
}
References is_character_file(), p, and status().
is_character_file() [2/2]
GHC_INLINE bool ghc::filesystem::is_character_file (file_status s) [noexcept]
Definition at line 4292 of file filesystem.hpp.
{
    return s.type() == file_type::character;
}
References character, and s.
Referenced by is_character_file().
is_directory() [1/2]
GHC_INLINE bool ghc::filesystem::is_directory (const path & p, std::error_code & ec) [noexcept]
Definition at line 4321 of file filesystem.hpp.
{
    return is_directory(status(p, ec));
}
References is_directory(), p, and status().
is_directory() [2/2]
GHC_INLINE bool ghc::filesystem::is_directory (file_status s) [noexcept]
Definition at line 4309 of file filesystem.hpp.
{
    return s.type() == file_type::directory;
}
References directory, and s.
Referenced by copy(), copy_symlink(), create_directories(), create_directory(), is_directory(), is_empty(), is_other(), FileInfo::isDir(), and remove_all().
is_empty()
GHC_INLINE bool ghc::filesystem::is_empty (const path & p, std::error_code & ec) [noexcept]
Definition at line 4338 of file filesystem.hpp.
{
    auto fs = status(p, ec);
    if (ec) {
        return false;
    }
    if (is_directory(fs)) {
        directory_iterator iter(p, ec);
        if (ec) {
            return false;
        }
        return iter == directory_iterator();
    }
    else {
        auto sz = file_size(p, ec);
        if (ec) {
            return false;
        }
        return sz == 0;
    }
}
References file_size(), is_directory(), p, and status().
Referenced by Dir::isEmpty().
is_fifo() [1/2]
GHC_INLINE bool ghc::filesystem::is_fifo (const path & p, std::error_code & ec) [noexcept]
Definition at line 4372 of file filesystem.hpp.
{
    return is_fifo(status(p, ec));
}
References is_fifo(), p, and status().
is_fifo() [2/2]
GHC_INLINE bool ghc::filesystem::is_fifo (file_status s) [noexcept]
Definition at line 4360 of file filesystem.hpp.
{
    return s.type() == file_type::fifo;
}
References fifo, and s.
Referenced by is_fifo().
is_other() [1/2]
GHC_INLINE bool ghc::filesystem::is_other (const path & p, std::error_code & ec) [noexcept]
Definition at line 4389 of file filesystem.hpp.
{
    return is_other(status(p, ec));
}
References is_other(), p, and status().
is_other() [2/2]
GHC_INLINE bool ghc::filesystem::is_other (file_status s) [noexcept]
Definition at line 4377 of file filesystem.hpp.
{
    return exists(s) && !is_regular_file(s) && !is_directory(s) && !is_symlink(s);
}
References exists(), is_directory(), is_regular_file(), is_symlink(), and s.
Referenced by copy(), and is_other().
is_regular_file() [1/2]
GHC_INLINE bool ghc::filesystem::is_regular_file (const path & p, std::error_code & ec) [noexcept]
Definition at line 4406 of file filesystem.hpp.
{
    return is_regular_file(status(p, ec));
}
References is_regular_file(), p, and status().
is_regular_file() [2/2]
GHC_INLINE bool ghc::filesystem::is_regular_file (file_status s) [noexcept]
Definition at line 4394 of file filesystem.hpp.
{
    return s.type() == file_type::regular;
}
References regular, and s.
Referenced by copy(), copy_file(), is_other(), is_regular_file(), and FileInfo::isFile().
is_socket() [1/2]
GHC_INLINE bool ghc::filesystem::is_socket (const path & p, std::error_code & ec) [noexcept]
Definition at line 4423 of file filesystem.hpp.
{
    return is_socket(status(p, ec));
}
References is_socket(), p, and status().
is_socket() [2/2]
GHC_INLINE bool ghc::filesystem::is_socket (file_status s) [noexcept]
Definition at line 4411 of file filesystem.hpp.
{
    return s.type() == file_type::socket;
}
References s, and socket.
Referenced by is_socket().
is_symlink() [1/2]
GHC_INLINE bool ghc::filesystem::is_symlink (const path & p, std::error_code & ec) [noexcept]
Definition at line 4440 of file filesystem.hpp.
{
    return is_symlink(symlink_status(p, ec));
}
References is_symlink(), p, and symlink_status().
is_symlink() [2/2]
GHC_INLINE bool ghc::filesystem::is_symlink (file_status s) [noexcept]
Definition at line 4428 of file filesystem.hpp.
{
    return s.type() == file_type::symlink;
}
References s, and symlink.
Referenced by copy(), is_other(), ghc::filesystem::directory_entry::is_other(), is_symlink(), ghc::filesystem::directory_entry::is_symlink(), and FileInfo::isSymLink().
last_write_time() [1/2]
GHC_INLINE void ghc::filesystem::last_write_time (const path & p, file_time_type new_time, std::error_code & ec) [noexcept]
Definition at line 4476 of file filesystem.hpp.
{
    ec.clear();
    auto d = new_time.time_since_epoch();
#ifdef GHC_OS_WINDOWS
    std::shared_ptr<void> file(::CreateFileW(GHC_NATIVEWP(p), FILE_WRITE_ATTRIBUTES, FILE_SHARE_DELETE | FILE_SHARE_READ | FILE_SHARE_WRITE, NULL, OPEN_EXISTING, FILE_FLAG_BACKUP_SEMANTICS, NULL), ::CloseHandle);
    FILETIME ft;
    auto tt = std::chrono::duration_cast<std::chrono::microseconds>(d).count() * 10 + 116444736000000000;
    ft.dwLowDateTime = static_cast<DWORD>(tt);
    ft.dwHighDateTime = static_cast<DWORD>(tt >> 32);
    if (!::SetFileTime(file.get(), 0, 0, &ft)) {
        ec = detail::make_system_error();
    }
#elif defined(GHC_OS_MACOS)
#ifdef __MAC_OS_X_VERSION_MIN_REQUIRED
#if __MAC_OS_X_VERSION_MIN_REQUIRED < 101300
    struct ::stat fs;
    if (::stat(p.c_str(), &fs) == 0) {
        struct ::timeval tv[2];
        tv[0].tv_sec = fs.st_atimespec.tv_sec;
        tv[0].tv_usec = static_cast<int>(fs.st_atimespec.tv_nsec / 1000);
        tv[1].tv_sec = std::chrono::duration_cast<std::chrono::seconds>(d).count();
        tv[1].tv_usec = static_cast<int>(std::chrono::duration_cast<std::chrono::microseconds>(d).count() % 1000000);
        if (::utimes(p.c_str(), tv) == 0) {
            return;
        }
    }
    ec = detail::make_system_error();
    return;
#else
    struct ::timespec times[2];
    times[0].tv_sec = 0;
    times[0].tv_nsec = UTIME_OMIT;
    times[1].tv_sec = std::chrono::duration_cast<std::chrono::seconds>(d).count();
    times[1].tv_nsec = 0; // std::chrono::duration_cast<std::chrono::nanoseconds>(d).count() % 1000000000;
    if (::utimensat(AT_FDCWD, p.c_str(), times, AT_SYMLINK_NOFOLLOW) != 0) {
        ec = detail::make_system_error();
    }
    return;
#endif
#endif
#else
#ifndef UTIME_OMIT
#define UTIME_OMIT ((1l << 30) - 2l)
#endif
    struct ::timespec times[2];
    times[0].tv_sec = 0;
    times[0].tv_nsec = UTIME_OMIT;
    times[1].tv_sec = static_cast<decltype(times[1].tv_sec)>(std::chrono::duration_cast<std::chrono::seconds>(d).count());
    times[1].tv_nsec = static_cast<decltype(times[1].tv_nsec)>(std::chrono::duration_cast<std::chrono::nanoseconds>(d).count() % 1000000000);
#if defined(__ANDROID_API__) && __ANDROID_API__ < 12
    if (syscall(__NR_utimensat, AT_FDCWD, p.c_str(), times, AT_SYMLINK_NOFOLLOW) != 0) {
#else
    if (::utimensat(AT_FDCWD, p.c_str(), times, AT_SYMLINK_NOFOLLOW) != 0) {
#endif
        ec = detail::make_system_error();
    }
    return;
#endif
}
References caseconvert::file, GHC_INLINE, GHC_NATIVEWP, ghc::filesystem::detail::make_system_error(), p, permissions(), ghc::filesystem::detail::systemErrorText(), and UTIME_OMIT.
last_write_time() [2/2]
GHC_INLINE file_time_type ghc::filesystem::last_write_time (const path & p, std::error_code & ec) [noexcept]
Definition at line 4457 of file filesystem.hpp.
{
    time_t result = 0;
    ec.clear();
    file_status fs = detail::status_ex(p, ec, nullptr, nullptr, nullptr, &result);
    return ec ? (file_time_type::min)() : std::chrono::system_clock::from_time_t(result);
}
References p, and ghc::filesystem::detail::status_ex().
Referenced by copy_file(), and ghc::filesystem::directory_entry::last_write_time().
operator!=()
GHC_INLINE bool ghc::filesystem::operator!= (const path & lhs, const path & rhs) [noexcept]
Definition at line 3387 of file filesystem.hpp.
{
    return !(lhs == rhs);
}
operator&()
template<typename Enum >
constexpr detail::EnableBitmask< Enum > ghc::filesystem::operator& (Enum X, Enum Y) [constexpr]
Definition at line 1371 of file filesystem.hpp.
{
    using underlying = typename std::underlying_type<Enum>::type;
    return static_cast<Enum>(static_cast<underlying>(X) & static_cast<underlying>(Y));
}
operator&=()
template<typename Enum >
detail::EnableBitmask< Enum > & ghc::filesystem::operator&= (Enum & X, Enum Y)
Definition at line 1399 of file filesystem.hpp.
{
    X = X & Y;
    return X;
}
operator/()
GHC_INLINE path ghc::filesystem::operator/ (const path & lhs, const path & rhs)
Definition at line 3412 of file filesystem.hpp.
{
    path result(lhs);
    result /= rhs;
    return result;
}
operator<()
GHC_INLINE bool ghc::filesystem::operator< (const path & lhs, const path & rhs) [noexcept]
Definition at line 3392 of file filesystem.hpp.
{
    return lhs.compare(rhs) < 0;
}
operator<<()
template<class charT , class traits >
std::basic_ostream< charT, traits > & ghc::filesystem::operator<< (std::basic_ostream< charT, traits > & os, const path & p) [inline]
Definition at line 3412 of file filesystem.hpp.
{
    os << "\"";
    auto ps = p.string<charT, traits>();
    for (auto c : ps) {
        if (c == '"' || c == '\\') {
            os << '\\';
        }
        os << c;
    }
    os << "\"";
    return os;
}
operator<=()
GHC_INLINE bool ghc::filesystem::operator<= (const path & lhs, const path & rhs) [noexcept]
Definition at line 3397 of file filesystem.hpp.
{
    return lhs.compare(rhs) <= 0;
}
operator==()
GHC_INLINE bool ghc::filesystem::operator== (const path & lhs, const path & rhs) [noexcept]
Definition at line 3382 of file filesystem.hpp.
{
    return lhs.compare(rhs) == 0;
}
operator>()
GHC_INLINE bool ghc::filesystem::operator> (const path & lhs, const path & rhs) [noexcept]
Definition at line 3402 of file filesystem.hpp.
{
    return lhs.compare(rhs) > 0;
}
operator>=()
GHC_INLINE bool ghc::filesystem::operator>= (const path & lhs, const path & rhs) [noexcept]
Definition at line 3407 of file filesystem.hpp.
{
    return lhs.compare(rhs) >= 0;
}
operator>>()
template<class charT , class traits >
std::basic_istream< charT, traits > & ghc::filesystem::operator>> (std::basic_istream< charT, traits > & is, path & p) [inline]
Definition at line 3439 of file filesystem.hpp.
{
    std::basic_string<charT, traits> tmp;
    charT c;
    is >> c;
    if (c == '"') {
        auto sf = is.flags();
        is >> std::noskipws;
        while (is) {
            auto c2 = is.get();
            if (is) {
                if (c2 == '\\') {
                    c2 = is.get();
                    if (is) {
                        tmp += static_cast<charT>(c2);
                    }
                }
                else if (c2 == '"') {
                    break;
                }
                else {
                    tmp += static_cast<charT>(c2);
                }
            }
        }
        if ((sf & std::ios_base::skipws) == std::ios_base::skipws) {
            is >> std::skipws;
        }
        p = path(tmp);
    }
    else {
        is >> tmp;
        p = path(static_cast<charT>(c) + tmp);
    }
    return is;
}
References c, and p.
operator^()
template<typename Enum >
constexpr detail::EnableBitmask< Enum > ghc::filesystem::operator^ (Enum X, Enum Y) [constexpr]
Definition at line 1385 of file filesystem.hpp.
{
    using underlying = typename std::underlying_type<Enum>::type;
    return static_cast<Enum>(static_cast<underlying>(X) ^ static_cast<underlying>(Y));
}
operator^=()
template<typename Enum >
detail::EnableBitmask< Enum > & ghc::filesystem::operator^= (Enum & X, Enum Y)
Definition at line 1413 of file filesystem.hpp.
{
    X = X ^ Y;
    return X;
}
operator|()
template<typename Enum >
constexpr detail::EnableBitmask< Enum > ghc::filesystem::operator| (Enum X, Enum Y) [constexpr]
Definition at line 1378 of file filesystem.hpp.
{
    using underlying = typename std::underlying_type<Enum>::type;
    return static_cast<Enum>(static_cast<underlying>(X) | static_cast<underlying>(Y));
}
operator|=()
template<typename Enum >
detail::EnableBitmask< Enum > & ghc::filesystem::operator|= (Enum & X, Enum Y)
Definition at line 1406 of file filesystem.hpp.
{
    X = X | Y;
    return X;
}
operator ()
template<typename Enum >
constexpr detail::EnableBitmask< Enum > ghc::filesystem::operator~ (Enum X) [constexpr]
Definition at line 1392 of file filesystem.hpp.
{
    using underlying = typename std::underlying_type<Enum>::type;
    return static_cast<Enum>(~static_cast<underlying>(X));
}
permissions() [1/2]
GHC_INLINE void ghc::filesystem::permissions (const path & p, perms prms, perm_options opts, std::error_code & ec) [noexcept]
Definition at line 4553 of file filesystem.hpp.
{
    if (static_cast<int>(opts & (perm_options::replace | perm_options::add | perm_options::remove)) == 0) {
        ec = detail::make_error_code(detail::portable_error::invalid_argument);
        return;
    }
    auto fs = symlink_status(p, ec);
    if ((opts & perm_options::replace) != perm_options::replace) {
        if ((opts & perm_options::add) == perm_options::add) {
            prms = fs.permissions() | prms;
        }
        else {
            prms = fs.permissions() & ~prms;
        }
    }
#ifdef GHC_OS_WINDOWS
#ifdef __GNUC__
    auto oldAttr = GetFileAttributesW(GHC_NATIVEWP(p));
    if (oldAttr != INVALID_FILE_ATTRIBUTES) {
        DWORD newAttr = ((prms & perms::owner_write) == perms::owner_write) ? oldAttr & ~(static_cast<DWORD>(FILE_ATTRIBUTE_READONLY)) : oldAttr | FILE_ATTRIBUTE_READONLY;
        if (oldAttr == newAttr || SetFileAttributesW(GHC_NATIVEWP(p), newAttr)) {
            return;
        }
    }
    ec = detail::make_system_error();
#else
    int mode = 0;
    if ((prms & perms::owner_read) == perms::owner_read) {
        mode |= _S_IREAD;
    }
    if ((prms & perms::owner_write) == perms::owner_write) {
        mode |= _S_IWRITE;
    }
    if (::_wchmod(p.wstring().c_str(), mode) != 0) {
        ec = detail::make_system_error();
    }
#endif
#else
    if ((opts & perm_options::nofollow) != perm_options::nofollow) {
        if (::chmod(p.c_str(), static_cast<mode_t>(prms)) != 0) {
            ec = detail::make_system_error();
        }
    }
#endif
}
References add, GHC_NATIVEWP, ghc::filesystem::detail::invalid_argument, ghc::filesystem::detail::make_error_code(), ghc::filesystem::detail::make_system_error(), mode, nofollow, owner_read, owner_write, p, remove, replace, and symlink_status().
permissions() [2/2]
GHC_INLINE void ghc::filesystem::permissions (const path & p, perms prms, std::error_code & ec) [noexcept]
Definition at line 4548 of file filesystem.hpp.
{
    permissions(p, prms, perm_options::replace, ec);
}
References p, permissions(), and replace.
Referenced by last_write_time(), and permissions().
proximate() [1/2]
GHC_INLINE path ghc::filesystem::proximate (const path & p, const path & base, std::error_code & ec)
Definition at line 4617 of file filesystem.hpp.
{
    return weakly_canonical(p, ec).lexically_proximate(weakly_canonical(base, ec));
}
References ghc::filesystem::path::lexically_proximate(), p, and weakly_canonical().
proximate() [2/2]
GHC_FS_API path ghc::filesystem::proximate (const path & p, std::error_code & ec)
read_symlink()
GHC_INLINE path ghc::filesystem::read_symlink (const path & p, std::error_code & ec)
Definition at line 4634 of file filesystem.hpp.
{
    file_status fs = symlink_status(p, ec);
    if (fs.type() != file_type::symlink) {
        ec = detail::make_error_code(detail::portable_error::invalid_argument);
        return path();
    }
    auto result = detail::resolveSymlink(p, ec);
    return ec ? path() : result;
}
References ghc::filesystem::detail::invalid_argument, ghc::filesystem::detail::make_error_code(), p, ghc::filesystem::detail::resolveSymlink(), symlink, and symlink_status().
Referenced by copy_symlink(), and FileInfo::readLink().
relative() [1/2]
GHC_INLINE path ghc::filesystem::relative (const path & p, const path & base, std::error_code & ec)
Definition at line 4657 of file filesystem.hpp.
{
    return weakly_canonical(p, ec).lexically_relative(weakly_canonical(base, ec));
}
References ghc::filesystem::path::lexically_relative(), p, and weakly_canonical().
relative() [2/2]
GHC_INLINE path ghc::filesystem::relative (const path & p, std::error_code & ec)
Definition at line 4645 of file filesystem.hpp.
{
    return relative(p, current_path(ec), ec);
}
References current_path(), p, and relative().
Referenced by relative().
remove()
GHC_INLINE bool ghc::filesystem::remove (const path & p, std::error_code & ec) [noexcept]
Definition at line 4674 of file filesystem.hpp.
{
    ec.clear();
#ifdef GHC_OS_WINDOWS
#ifdef GHC_USE_WCHAR_T
    auto cstr = p.c_str();
#else
    std::wstring np = detail::fromUtf8<std::wstring>(p.u8string());
    auto cstr = np.c_str();
#endif
    DWORD attr = GetFileAttributesW(cstr);
    if (attr == INVALID_FILE_ATTRIBUTES) {
        auto error = ::GetLastError();
        if (error == ERROR_FILE_NOT_FOUND || error == ERROR_PATH_NOT_FOUND) {
            return false;
        }
        ec = detail::make_system_error(error);
    }
    else if(attr & FILE_ATTRIBUTE_READONLY) {
        auto new_attr = attr & ~static_cast<DWORD>(FILE_ATTRIBUTE_READONLY);
        if(!SetFileAttributesW(cstr, new_attr)) {
            auto error = ::GetLastError();
            ec = detail::make_system_error(error);
        }
    }
    if (!ec) {
        if (attr & FILE_ATTRIBUTE_DIRECTORY) {
            if (!RemoveDirectoryW(cstr)) {
                ec = detail::make_system_error();
            }
        }
        else {
            if (!DeleteFileW(cstr)) {
                ec = detail::make_system_error();
            }
        }
    }
#else
    if (::remove(p.c_str()) == -1) {
        auto error = errno;
        if (error == ENOENT) {
            return false;
        }
        ec = detail::make_system_error();
    }
#endif
    return ec ? false : true;
}
References errno, ghc::filesystem::detail::make_system_error(), p, and remove().
Referenced by remove(), Dir::remove(), and remove_all().
remove_all()
GHC_INLINE uintmax_t ghc::filesystem::remove_all (const path & p, std::error_code & ec) [noexcept]
Definition at line 4735 of file filesystem.hpp.
{
    ec.clear();
    uintmax_t count = 0;
    if (p == "/") {
        ec = detail::make_error_code(detail::portable_error::not_supported);
        return static_cast<uintmax_t>(-1);
    }
    std::error_code tec;
    auto fs = status(p, tec);
    if (exists(fs) && is_directory(fs)) {
        for (auto iter = directory_iterator(p, ec); iter != directory_iterator(); iter.increment(ec)) {
            if (ec && !detail::is_not_found_error(ec)) {
                break;
            }
            bool is_symlink_result = iter->is_symlink(ec);
            if (ec)
                return static_cast<uintmax_t>(-1);
            if (!is_symlink_result && iter->is_directory(ec)) {
                count += remove_all(iter->path(), ec);
                if (ec) {
                    return static_cast<uintmax_t>(-1);
                }
            }
            else {
                if (!ec) {
                    remove(iter->path(), ec);
                }
                if (ec) {
                    return static_cast<uintmax_t>(-1);
                }
                ++count;
            }
        }
    }
    if (!ec) {
        if (remove(p, ec)) {
            ++count;
        }
    }
    if (ec) {
        return static_cast<uintmax_t>(-1);
    }
    return count;
}
References exists(), is_directory(), ghc::filesystem::detail::is_not_found_error(), ghc::filesystem::detail::make_error_code(), ghc::filesystem::detail::not_supported, p, remove(), remove_all(), and status().
Referenced by remove_all().
rename()
GHC_INLINE void ghc::filesystem::rename (const path & from, const path & to, std::error_code & ec) [noexcept]
Definition at line 4792 of file filesystem.hpp.
{
    ec.clear();
#ifdef GHC_OS_WINDOWS
    if (from != to) {
        if (!MoveFileExW(GHC_NATIVEWP(from), GHC_NATIVEWP(to), (DWORD)MOVEFILE_REPLACE_EXISTING)) {
            ec = detail::make_system_error();
        }
    }
#else
    if (from != to) {
        if (::rename(from.c_str(), to.c_str()) != 0) {
            ec = detail::make_system_error();
        }
    }
#endif
}
References GHC_NATIVEWP, ghc::filesystem::detail::make_system_error(), and rename().
Referenced by rename(), and Dir::rename().
resize_file()
GHC_INLINE void ghc::filesystem::resize_file (const path & p, uintmax_t size, std::error_code & ec) [noexcept]
Definition at line 4821 of file filesystem.hpp.
{
    ec.clear();
#ifdef GHC_OS_WINDOWS
    LARGE_INTEGER lisize;
    lisize.QuadPart = static_cast<LONGLONG>(size);
    if (lisize.QuadPart < 0) {
#ifdef ERROR_FILE_TOO_LARGE
        ec = detail::make_system_error(ERROR_FILE_TOO_LARGE);
#else
        ec = detail::make_system_error(223);
#endif
        return;
    }
    std::shared_ptr<void> file(CreateFileW(GHC_NATIVEWP(p), GENERIC_WRITE, 0, NULL, OPEN_EXISTING, 0, NULL), CloseHandle);
    if (file.get() == INVALID_HANDLE_VALUE) {
        ec = detail::make_system_error();
    }
    else if (SetFilePointerEx(file.get(), lisize, NULL, FILE_BEGIN) == 0 || SetEndOfFile(file.get()) == 0) {
        ec = detail::make_system_error();
    }
#else
    if (::truncate(p.c_str(), static_cast<off_t>(size)) != 0) {
        ec = detail::make_system_error();
    }
#endif
}
References caseconvert::file, GHC_NATIVEWP, ghc::filesystem::detail::make_system_error(), p, and size.
space()
GHC_INLINE space_info ghc::filesystem::space (const path & p, std::error_code & ec) [noexcept]
Definition at line 4861 of file filesystem.hpp.
{
    ec.clear();
#ifdef GHC_OS_WINDOWS
    ULARGE_INTEGER freeBytesAvailableToCaller = {{ 0, 0 }};
    ULARGE_INTEGER totalNumberOfBytes = {{ 0, 0 }};
    ULARGE_INTEGER totalNumberOfFreeBytes = {{ 0, 0 }};
    if (!GetDiskFreeSpaceExW(GHC_NATIVEWP(p), &freeBytesAvailableToCaller, &totalNumberOfBytes, &totalNumberOfFreeBytes)) {
        ec = detail::make_system_error();
        return {static_cast<uintmax_t>(-1), static_cast<uintmax_t>(-1), static_cast<uintmax_t>(-1)};
    }
    return {static_cast<uintmax_t>(totalNumberOfBytes.QuadPart), static_cast<uintmax_t>(totalNumberOfFreeBytes.QuadPart), static_cast<uintmax_t>(freeBytesAvailableToCaller.QuadPart)};
#else
    struct ::statvfs sfs;
    if (::statvfs(p.c_str(), &sfs) != 0) {
        ec = detail::make_system_error();
        return {static_cast<uintmax_t>(-1), static_cast<uintmax_t>(-1), static_cast<uintmax_t>(-1)};
    }
    return {static_cast<uintmax_t>(sfs.f_blocks * sfs.f_frsize), static_cast<uintmax_t>(sfs.f_bfree * sfs.f_frsize), static_cast<uintmax_t>(sfs.f_bavail * sfs.f_frsize)};
#endif
}
References GHC_NATIVEWP, ghc::filesystem::detail::make_system_error(), and p.
status()
GHC_INLINE file_status ghc::filesystem::status (const path & p, std::error_code & ec) [noexcept]
Definition at line 4895 of file filesystem.hpp.
{
    return detail::status_ex(p, ec);
}
References p, and ghc::filesystem::detail::status_ex().
Referenced by copy(), copy_file(), create_directories(), create_directory(), exists(), is_block_file(), is_character_file(), is_directory(), is_empty(), is_fifo(), is_other(), is_regular_file(), is_socket(), FileInfo::isDir(), FileInfo::isExecutable(), FileInfo::isFile(), FileInfo::isReadable(), FileInfo::isSymLink(), FileInfo::isWritable(), remove_all(), ghc::filesystem::directory_entry::status(), ghc::filesystem::directory_entry::status_file_type(), and Portable::system().
status_known()
GHC_INLINE bool ghc::filesystem::status_known (file_status s) [noexcept]
Definition at line 4900 of file filesystem.hpp.
{
    return s.type() != file_type::none;
}
References none, and s.
Referenced by create_directory(), and exists().
swap()
GHC_INLINE void ghc::filesystem::swap (path & lhs, path & rhs) [noexcept]
Definition at line 3365 of file filesystem.hpp.
{
    swap(lhs._path, rhs._path);
}
Referenced by groupClassesWithSameScope(), and ghc::filesystem::path::swap().
symlink_status()
GHC_INLINE file_status ghc::filesystem::symlink_status (const path & p, std::error_code & ec) [noexcept]
Definition at line 4917 of file filesystem.hpp.
{
    return detail::symlink_status_ex(p, ec);
}
References p, and ghc::filesystem::detail::symlink_status_ex().
Referenced by copy(), is_symlink(), ghc::filesystem::directory_entry::is_symlink(), FileInfo::isSymLink(), permissions(), read_symlink(), and ghc::filesystem::directory_entry::symlink_status().
temp_directory_path()
GHC_INLINE path ghc::filesystem::temp_directory_path (std::error_code & ec) [noexcept]
Definition at line 4934 of file filesystem.hpp.
{
    ec.clear();
#ifdef GHC_OS_WINDOWS
    wchar_t buffer[512];
    auto rc = GetTempPathW(511, buffer);
    if (!rc || rc > 511) {
        ec = detail::make_system_error();
        return path();
    }
    return path(std::wstring(buffer));
#else
    static const char* temp_vars[] = {"TMPDIR", "TMP", "TEMP", "TEMPDIR", nullptr};
    const char* temp_path = nullptr;
    for (auto temp_name = temp_vars; *temp_name != nullptr; ++temp_name) {
        temp_path = std::getenv(*temp_name);
        if (temp_path) {
            return path(temp_path);
        }
    }
    return path("/tmp");
#endif
}
References ghc::filesystem::path::clear(), Portable::getenv(), and ghc::filesystem::detail::make_system_error().
u8path() [1/2]
template<class Source , typename = path::path_from_string<Source>>
path ghc::filesystem::u8path (const Source & source) [inline]
Definition at line 1791 of file filesystem.hpp.
{
    return path(source);
}
u8path() [2/2]
template<class InputIterator >
path ghc::filesystem::u8path (InputIterator first, InputIterator last) [inline]
Definition at line 1796 of file filesystem.hpp.
{
    return path(first, last);
}
weakly_canonical()
GHC_INLINE path ghc::filesystem::weakly_canonical (const path & p, std::error_code & ec) [noexcept]
Definition at line 4970 of file filesystem.hpp.
{
    path result;
    ec.clear();
    bool scan = true;
    for (auto pe : p) {
        if (scan) {
            std::error_code tec;
            if (exists(result / pe, tec)) {
                result /= pe;
            }
            else {
                if (ec) {
                    return path();
                }
                scan = false;
                if (!result.empty()) {
                    result = canonical(result, ec) / pe;
                    if (ec) {
                        break;
                    }
                }
                else {
                    result /= pe;
                }
            }
        }
        else {
            result /= pe;
        }
    }
    if (scan) {
        if (!result.empty()) {
            result = canonical(result, ec);
        }
    }
    return ec ? path() : result.lexically_normal();
}
References canonical(), ghc::filesystem::path::clear(), ghc::filesystem::path::empty(), exists(), ghc::filesystem::path::lexically_normal(), and p.
Referenced by proximate(), and relative().