res2cc_cmd Namespace Reference
Classes
class CSSFile
class File
class LumaFile
class LumFile
class SVGFile
class VerbatimFile
Functions
def main ()
Function Documentation
main()
def res2cc_cmd.main (void)
Definition at line 104 of file res2cc_cmd.py.
def main():
    if len(sys.argv)<3:
        sys.exit('Usage: %s directory output_file.cpp' % sys.argv[0])
    directory = sys.argv[1]
    files = []
    for dirName, subdirList, fileList in walk(directory):
        for fname in fileList:
            subdir = dirName[len(directory)+1:] if dirName.startswith(directory) else dirName
            if subdir:
                files.append(File.factory(directory,subdir,fname))
    files.sort(key=lambda f: f.subdir + "/" + f.fileName)
    outputFile = open(sys.argv[2],"w")
    print("#include \"resourcemgr.h\"\n",file=outputFile)
    for f in files:
        f.writeContents(outputFile)
    print("void initResources() { ResourceMgr::instance().registerResources({",file=outputFile)
    for f in files:
        f.writeDirEntry(outputFile)
    print("});}",file=outputFile)
References len, main(), open(), and print().
Referenced by main(), and res2cc_cmd.LumaFile.writeDirEntry().