mymodule Module Reference
Data Types
interface abstractProc
interface externalProc
interface genericproc
interface operator(.cross.)
interface operator(//)
type t1
type t2
type t3
type t4
Functions/Subroutines
subroutine firstproc (i)
short doc
subroutine secondproc (r)
subroutine otherproc (someArg)
pure real function, dimension(3) cross_product (v, w)
integer function secondproc_fun (r)
comment on secondProc_fun
subroutine anotherproc (someArg)
comment on anotherProc
Function/Subroutine Documentation
anotherproc()
subroutine mymodule::anotherproc (character(len=*), intent(in) someArg)
comment on anotherProc
Parameters
 in somearg comment on someArg of anotherProc
Definition at line 23 of file 091_module_with_procs.f90.
    character(len=*), intent(in) :: someArg
cross_product()
pure real function, dimension(3) mymodule::cross_product (real, dimension(3), intent(in) v, real, dimension(3), intent(in) w) [private]
Definition at line 70 of file 090_interfaces.f90.
    real, intent(in) :: v(3), w(3)
    real :: cross_product(3)
    !cross_product = ...
Referenced by mymodule::abstractProc::abstractproc().
firstproc()
subroutine mymodule::firstproc (integer, intent(in) i) [private]
short doc
comment on firstProc
Parameters
 in i integer argument
 in i comment on i of firstProc
Definition at line 58 of file 090_interfaces.f90.
    integer, intent(in) :: i
Referenced by mymodule::externalProc::externalproc().
otherproc()
subroutine mymodule::otherproc (character(len=*), intent(in) someArg) [private]
Definition at line 66 of file 090_interfaces.f90.
    character(len=*), intent(in) :: someArg
Referenced by mymodule::externalProc::externalproc().
secondproc()
subroutine mymodule::secondproc (real, intent(out) r) [private]
Definition at line 62 of file 090_interfaces.f90.
    real, intent(out) :: r
secondproc_fun()
integer function mymodule::secondproc_fun (real, intent(out) r)
comment on secondProc_fun
Parameters
 out r comment on r of secondProc_fun
Returns
comment on result Res of secondProc_fun
Definition at line 17 of file 091_module_with_procs.f90.
    real, intent(out) :: r
    integer :: Res