scan_states Namespace Reference
Functions
def main ()
Function Documentation
main()
def scan_states.main (void)
Definition at line 20 of file scan_states.py.
def main():
    if len(sys.argv)!=2:
        sys.exit('Usage: %s <lex_file>' % sys.argv[0])
    lex_file = sys.argv[1]
    if (os.path.exists(lex_file)):
        #write preamble
        print("static const char *stateToString(int state)")
        print("{")
        print(" switch(state)")
        print(" {")
        print(" case INITIAL: return \"INITIAL\";")
        with open(lex_file) as f:
            for line in f:
                if re.search(r'^%x', line) or re.search(r'^%s', line):
                    state = line.split()[1]
                    print(" case %s: return \"%s\";" % (state,state))
                elif re.search(r'^%%', line):
                    break
                else:
                    pass
            f.close()
        #write post
        print(" }")
        print(" return \"Unknown\";")
        print("}")
References len, main(), open(), and print().
Referenced by main().