dump Namespace Reference
Functions
def parse_compound (inDirName, baseName)
def parse_index (inDirName)
def usage ()
def main ()
Function Documentation
main()
def dump.main (void)
Definition at line 22 of file dump.py.
def main():
    args = sys.argv[1:]
    if len(args)==1:
        parse_index(args[0])
    else:
        usage()
References len, main(), parse_index(), and usage().
Referenced by main().
parse_compound()
def dump.parse_compound (inDirName, baseName)
Definition at line 9 of file dump.py.
def parse_compound(inDirName,baseName):
    doxmlparser.compound.parse(inDirName+"/"+baseName+".xml",False)
# process the index file and export the results to stdout
References doxmlparser.compound.parse().
Referenced by parse_index().
parse_index()
def dump.parse_index (inDirName)
Definition at line 13 of file dump.py.
def parse_index(inDirName):
    rootObj = doxmlparser.index.parse(inDirName+"/index.xml",False)
    for compound in rootObj.get_compound(): # for each compound defined in the index
        parse_compound(inDirName,compound.get_refid())
References doxmlparser.index.parse(), and parse_compound().
Referenced by main().
usage()
def dump.usage ()
Definition at line 18 of file dump.py.
def usage():
    print("Usage {0} <xml_output_dir>".format(sys.argv[0]))
    sys.exit(1)
References print().
Referenced by main().