doxmlparser.index Namespace Reference
Classes
class CompoundKind
class CompoundType
class DoxygenType
class GdsCollector_
class GDSParseError
class GeneratedsSuper
class MemberKind
class MemberSpec_
class MemberType
class MixedContainer
Functions
def parsexml_ (infile, parser=None, **kwargs)
def parsexmlstring_ (instring, parser=None, **kwargs)
def getSubclassFromModule_ (module, class_)
def showIndent (outfile, level, pretty_print=True)
def quote_xml (inStr)
def quote_xml_aux (inStr)
def quote_attrib (inStr)
def quote_python (inStr)
def get_all_text_ (node)
def find_attr_value_ (attr_name, node)
def encode_str_2_3 (instr)
def raise_parse_error (node, msg)
def _cast (typ, value)
def usage ()
def get_root_tag (node)
def get_required_ns_prefix_defs (rootNode)
def parse (inFileName, silence=False, print_warnings=True)
def parseEtree (inFileName, silence=False, print_warnings=True, mapping=None, nsmap=None)
def parseString (inString, silence=False, print_warnings=True)
def parseLiteral (inFileName, silence=False, print_warnings=True)
def main ()
Variables
ModulenotfoundExp_ = ModuleNotFoundError
bool Validate_simpletypes_ = True
bool SaveElementTreeNode = True
BaseStrType_ = basestring
dictionary GenerateDSNamespaceDefs_ = {}
dictionary GenerateDSNamespaceTypePrefixes_ = {}
Enum = object
string ExternalEncoding = ''
bool UseCapturedNS_ = True
dictionary CapturedNsmap_ = {}
Tag_pattern_ = re_.compile(r'({.*})?(.*)')
String_cleanup_pat_ = re_.compile(r`[\n\r\s]+`)
Namespace_extract_pat_ = re_.compile(r'{(.*)}(.*)')
CDATA_pattern_ = re_.compile(r`<!\[CDATA\[.*?\]\]>`, re_.DOTALL)
CurrentSubclassModule_ = None
dictionary GDSClassesMapping
string USAGE_TEXT
dictionary RenameMappings_
dictionary NamespaceToDefMappings_ = {'http://www.w3.org/XML/1998/namespace': []}
list __all__
Function Documentation
_cast()
def doxmlparser.index._cast (typ, value) [private]
Definition at line 962 of file index.py.
def _cast(typ, value):
    if typ is None or value is None:
        return value
    return typ(value)
#
# Data representation classes.
#
Referenced by doxmlparser.index.MemberType.__init__(), doxmlparser.index.CompoundType.__init__(), and doxmlparser.index.DoxygenType.__init__().
encode_str_2_3()
def doxmlparser.index.encode_str_2_3 (instr)
Definition at line 799 of file index.py.
def encode_str_2_3(instr):
    return instr
Referenced by doxmlparser.index.CompoundType.validate_CompoundKind(), and doxmlparser.index.MemberType.validate_MemberKind().
find_attr_value_()
def doxmlparser.index.find_attr_value_ (attr_name, node)
Definition at line 782 of file index.py.
def find_attr_value_(attr_name, node):
    attrs = node.attrib
    attr_parts = attr_name.split(':')
    value = None
    if len(attr_parts) == 1:
        value = attrs.get(attr_name)
    elif len(attr_parts) == 2:
        prefix, name = attr_parts
        if prefix == 'xml':
            namespace = 'http://www.w3.org/XML/1998/namespace'
        else:
            namespace = node.nsmap.get(prefix)
        if namespace is not None:
            value = attrs.get('{%s}%s' % (namespace, name,))
    return value
References len.
Referenced by doxmlparser.index.DoxygenType.buildAttributes(), doxmlparser.index.CompoundType.buildAttributes(), and doxmlparser.index.MemberType.buildAttributes().
get_all_text_()
def doxmlparser.index.get_all_text_ (node)
Definition at line 771 of file index.py.
def get_all_text_(node):
    if node.text is not None:
        text = node.text
    else:
        text = ''
    for child in node:
        if child.tail is not None:
            text += child.tail
    return text
get_required_ns_prefix_defs()
def doxmlparser.index.get_required_ns_prefix_defs (rootNode)
Get all name space prefix definitions required in this XML doc.
Return a dictionary of definitions and a char string of definitions.
Definition at line 1445 of file index.py.
def get_required_ns_prefix_defs(rootNode):
    '''Get all name space prefix definitions required in this XML doc.
    Return a dictionary of definitions and a char string of definitions.
    '''
    nsmap = {
        prefix: uri
        for node in rootNode.iter()
        for (prefix, uri) in node.nsmap.items()
        if prefix is not None
    }
    namespacedefs = ' '.join([
        'xmlns:{}="{}"'.format(prefix, uri)
        for prefix, uri in nsmap.items()
    ])
    return nsmap, namespacedefs
References join().
Referenced by doxmlparser.index.MemberType.buildChildren(), and doxmlparser.index.parse().
get_root_tag()
def doxmlparser.index.get_root_tag (node)
Definition at line 1437 of file index.py.
def get_root_tag(node):
    tag = Tag_pattern_.match(node.tag).groups()[-1]
    rootClass = GDSClassesMapping.get(tag)
    if rootClass is None:
        rootClass = globals().get(tag)
    return tag, rootClass
Referenced by doxmlparser.index.MemberType.buildChildren(), doxmlparser.index.parse(), doxmlparser.index.parseEtree(), doxmlparser.index.parseLiteral(), and doxmlparser.index.parseString().
getSubclassFromModule_()
def doxmlparser.index.getSubclassFromModule_ (module, class_)
Get the subclass of a class from a specific module.
Definition at line 662 of file index.py.
    def getSubclassFromModule_(module, class_):
        '''Get the subclass of a class from a specific module.'''
        name = class_.__name__ + 'Sub'
        if hasattr(module, name):
            return getattr(module, name)
        else:
            return None
#
# If you have installed IPython you can uncomment and use the following.
# IPython is available from http://ipython.scipy.org/.
#
# # from IPython.Shell import IPShellEmbed
# # args = ''
# # ipshell = IPShellEmbed(args,
# # banner = 'Dropping into IPython',
# # exit_msg = 'Leaving Interpreter, back to program.')
# Then use the following line where and when you want to drop into the
# IPython shell:
# ipshell('<some message> -- Entering ipshell.\nHit Ctrl-D to exit')
#
# Globals
#
Referenced by doxmlparser.index.DoxygenType.factory(), doxmlparser.index.CompoundType.factory(), and doxmlparser.index.MemberType.factory().
main()
def doxmlparser.index.main (void)
Definition at line 1597 of file index.py.
def main():
    args = sys.argv[1:]
    if len(args) == 1:
        parse(args[0])
    else:
        usage()
References len, doxmlparser.index.main(), doxmlparser.index.parse(), and doxmlparser.index.usage().
Referenced by doxmlparser.index.MemberType.buildChildren(), and doxmlparser.index.main().
parse()
def doxmlparser.index.parse (inFileName, silence = False, print_warnings = True)
Definition at line 1462 of file index.py.
def parse(inFileName, silence=False, print_warnings=True):
    global CapturedNsmap_
    gds_collector = GdsCollector_()
    parser = None
    doc = parsexml_(inFileName, parser)
    rootNode = doc.getroot()
    rootTag, rootClass = get_root_tag(rootNode)
    if rootClass is None:
        rootTag = 'DoxygenType'
        rootClass = DoxygenType
    rootObj = rootClass.factory()
    rootObj.build(rootNode, gds_collector_=gds_collector)
    CapturedNsmap_, namespacedefs = get_required_ns_prefix_defs(rootNode)
    if not SaveElementTreeNode:
        doc = None
        rootNode = None
    if not silence:
        sys.stdout.write('<?xml version="1.0" ?>\n')
        rootObj.export(
            sys.stdout, 0, name_=rootTag,
            namespacedef_=namespacedefs,
            pretty_print=True)
    if print_warnings and len(gds_collector.get_messages()) > 0:
        separator = ('-' * 50) + '\n'
        sys.stderr.write(separator)
        sys.stderr.write('----- Warnings -- count: {} -----\n'.format(
            len(gds_collector.get_messages()),))
        gds_collector.write_messages(sys.stderr)
        sys.stderr.write(separator)
    return rootObj
References doxmlparser.index.get_required_ns_prefix_defs(), doxmlparser.index.get_root_tag(), len, and doxmlparser.index.parsexml_().
Referenced by doxmlparser.index.MemberType.buildChildren(), doxmlparser.index.main(), dump.parse_index(), metrics.parse_index(), and metrics.Metrics.print().
parseEtree()
def doxmlparser.index.parseEtree (inFileName, silence = False, print_warnings = True, mapping = None, nsmap = None)
Definition at line 1494 of file index.py.
               mapping=None, nsmap=None):
    parser = None
    doc = parsexml_(inFileName, parser)
    gds_collector = GdsCollector_()
    rootNode = doc.getroot()
    rootTag, rootClass = get_root_tag(rootNode)
    if rootClass is None:
        rootTag = 'DoxygenType'
        rootClass = DoxygenType
    rootObj = rootClass.factory()
    rootObj.build(rootNode, gds_collector_=gds_collector)
    # Enable Python to collect the space used by the DOM.
    if mapping is None:
        mapping = {}
    rootElement = rootObj.to_etree(
        None, name_=rootTag, mapping_=mapping, nsmap_=nsmap)
    reverse_mapping = rootObj.gds_reverse_node_mapping(mapping)
    if not SaveElementTreeNode:
        doc = None
        rootNode = None
    if not silence:
        content = etree_.tostring(
            rootElement, pretty_print=True,
            xml_declaration=True, encoding="utf-8")
        sys.stdout.write(str(content))
        sys.stdout.write('\n')
    if print_warnings and len(gds_collector.get_messages()) > 0:
        separator = ('-' * 50) + '\n'
        sys.stderr.write(separator)
        sys.stderr.write('----- Warnings -- count: {} -----\n'.format(
            len(gds_collector.get_messages()),))
        gds_collector.write_messages(sys.stderr)
        sys.stderr.write(separator)
    return rootObj, rootElement, mapping, reverse_mapping
References doxmlparser.index.get_root_tag(), len, and doxmlparser.index.parsexml_().
parseLiteral()
def doxmlparser.index.parseLiteral (inFileName, silence = False, print_warnings = True)
Definition at line 1566 of file index.py.
def parseLiteral(inFileName, silence=False, print_warnings=True):
    parser = None
    doc = parsexml_(inFileName, parser)
    gds_collector = GdsCollector_()
    rootNode = doc.getroot()
    rootTag, rootClass = get_root_tag(rootNode)
    if rootClass is None:
        rootTag = 'DoxygenType'
        rootClass = DoxygenType
    rootObj = rootClass.factory()
    rootObj.build(rootNode, gds_collector_=gds_collector)
    # Enable Python to collect the space used by the DOM.
    if not SaveElementTreeNode:
        doc = None
        rootNode = None
    if not silence:
        sys.stdout.write('#from index import *\n\n')
        sys.stdout.write('import index as model_\n\n')
        sys.stdout.write('rootObj = model_.rootClass(\n')
        rootObj.exportLiteral(sys.stdout, 0, name_=rootTag)
        sys.stdout.write(')\n')
    if print_warnings and len(gds_collector.get_messages()) > 0:
        separator = ('-' * 50) + '\n'
        sys.stderr.write(separator)
        sys.stderr.write('----- Warnings -- count: {} -----\n'.format(
            len(gds_collector.get_messages()),))
        gds_collector.write_messages(sys.stderr)
        sys.stderr.write(separator)
    return rootObj
References doxmlparser.index.get_root_tag(), len, and doxmlparser.index.parsexml_().
parseString()
def doxmlparser.index.parseString (inString, silence = False, print_warnings = True)
Parse a string, create the object tree, and export it.

Arguments:
- inString -- A string.  This XML fragment should not start
  with an XML declaration containing an encoding.
- silence -- A boolean.  If False, export the object.
Returns -- The root object in the tree.
Definition at line 1531 of file index.py.
def parseString(inString, silence=False, print_warnings=True):
    '''Parse a string, create the object tree, and export it.
    Arguments:
    - inString -- A string. This XML fragment should not start
      with an XML declaration containing an encoding.
    - silence -- A boolean. If False, export the object.
    Returns -- The root object in the tree.
    '''
    parser = None
    rootNode= parsexmlstring_(inString, parser)
    gds_collector = GdsCollector_()
    rootTag, rootClass = get_root_tag(rootNode)
    if rootClass is None:
        rootTag = 'DoxygenType'
        rootClass = DoxygenType
    rootObj = rootClass.factory()
    rootObj.build(rootNode, gds_collector_=gds_collector)
    if not SaveElementTreeNode:
        rootNode = None
    if not silence:
        sys.stdout.write('<?xml version="1.0" ?>\n')
        rootObj.export(
            sys.stdout, 0, name_=rootTag,
            namespacedef_='')
    if print_warnings and len(gds_collector.get_messages()) > 0:
        separator = ('-' * 50) + '\n'
        sys.stderr.write(separator)
        sys.stderr.write('----- Warnings -- count: {} -----\n'.format(
            len(gds_collector.get_messages()),))
        gds_collector.write_messages(sys.stderr)
        sys.stderr.write(separator)
    return rootObj
References doxmlparser.index.get_root_tag(), len, and doxmlparser.index.parsexmlstring_().
parsexml_()
def doxmlparser.index.parsexml_ (infile, parser = None, ** kwargs)
Definition at line 49 of file index.py.
def parsexml_(infile, parser=None, **kwargs):
    if parser is None:
        # Use the lxml ElementTree compatible parser so that, e.g.,
        # we ignore comments.
        try:
            parser = etree_.ETCompatXMLParser()
        except AttributeError:
            # fallback to xml.etree
            parser = etree_.XMLParser()
    try:
        if isinstance(infile, os.PathLike):
            infile = os.path.join(infile)
    except AttributeError:
        pass
    doc = etree_.parse(infile, parser=parser, **kwargs)
    return doc
Referenced by doxmlparser.index.MemberType.buildChildren(), doxmlparser.index.parse(), doxmlparser.index.parseEtree(), and doxmlparser.index.parseLiteral().
parsexmlstring_()
def doxmlparser.index.parsexmlstring_ (instring, parser = None, ** kwargs)
Definition at line 66 of file index.py.
def parsexmlstring_(instring, parser=None, **kwargs):
    if parser is None:
        # Use the lxml ElementTree compatible parser so that, e.g.,
        # we ignore comments.
        try:
            parser = etree_.ETCompatXMLParser()
        except AttributeError:
            # fallback to xml.etree
            parser = etree_.XMLParser()
    element = etree_.fromstring(instring, parser=parser, **kwargs)
    return element
#
# Namespace prefix definition table (and other attributes, too)
#
# The module generatedsnamespaces, if it is importable, must contain
# a dictionary named GeneratedsNamespaceDefs. This Python dictionary
# should map element type names (strings) to XML schema namespace prefix
# definitions. The export method for any class for which there is
# a namespace prefix definition, will export that definition in the
# XML representation of that element. See the export method of
# any generated element type class for an example of the use of this
# table.
# A sample table is:
#
# # File: generatedsnamespaces.py
#
# GenerateDSNamespaceDefs = {
# "ElementtypeA": "http://www.xxx.com/namespaceA",
# "ElementtypeB": "http://www.xxx.com/namespaceB",
# }
#
# Additionally, the generatedsnamespaces module can contain a python
# dictionary named GenerateDSNamespaceTypePrefixes that associates element
# types with the namespace prefixes that are to be added to the
# "xsi:type" attribute value. See the exportAttributes method of
# any generated element type and the generation of "xsi:type" for an
# example of the use of this table.
# An example table:
#
# # File: generatedsnamespaces.py
#
# GenerateDSNamespaceTypePrefixes = {
# "ElementtypeC": "aaa:",
# "ElementtypeD": "bbb:",
# }
#
try:
    from generatedsnamespaces import GenerateDSNamespaceDefs as GenerateDSNamespaceDefs_
Referenced by doxmlparser.index.MemberType.buildChildren(), and doxmlparser.index.parseString().
quote_attrib()
def doxmlparser.index.quote_attrib (inStr)
Definition at line 740 of file index.py.
def quote_attrib(inStr):
    s1 = (isinstance(inStr, BaseStrType_) and inStr or '%s' % inStr)
    s1 = s1.replace('&', '&amp;')
    s1 = s1.replace('<', '&lt;')
    s1 = s1.replace('>', '&gt;')
    if '"' in s1:
        if "'" in s1:
            s1 = '"%s"' % s1.replace('"', "&quot;")
        else:
            s1 = "'%s'" % s1
    else:
        s1 = '"%s"' % s1
    return s1
Referenced by doxmlparser.index.CompoundType.exportAttributes(), doxmlparser.index.DoxygenType.exportAttributes(), and doxmlparser.index.MemberType.exportAttributes().
quote_python()
def doxmlparser.index.quote_python (inStr)
Definition at line 755 of file index.py.
def quote_python(inStr):
    s1 = inStr
    if s1.find("'") == -1:
        if s1.find('\n') == -1:
            return "'%s'" % s1
        else:
            return "'''%s'''" % s1
    else:
        if s1.find('"') != -1:
            s1 = s1.replace('"', '\\"')
        if s1.find('\n') == -1:
            return '"%s"' % s1
        else:
            return '"""%s"""' % s1
quote_xml()
def doxmlparser.index.quote_xml (inStr)
Definition at line 715 of file index.py.
def quote_xml(inStr):
    "Escape markup chars, but do not modify CDATA sections."
    if not inStr:
        return ''
    s1 = (isinstance(inStr, BaseStrType_) and inStr or '%s' % inStr)
    s2 = ''
    pos = 0
    matchobjects = CDATA_pattern_.finditer(s1)
    for mo in matchobjects:
        s3 = s1[pos:mo.start()]
        s2 += quote_xml_aux(s3)
        s2 += s1[mo.start():mo.end()]
        pos = mo.end()
    s3 = s1[pos:]
    s2 += quote_xml_aux(s3)
    return s2
References doxmlparser.index.quote_xml_aux().
Referenced by doxmlparser.index.GeneratedsSuper.convert_unicode(), doxmlparser.index.CompoundType.exportChildren(), and doxmlparser.index.MemberType.exportChildren().
quote_xml_aux()
def doxmlparser.index.quote_xml_aux (inStr)
Definition at line 733 of file index.py.
def quote_xml_aux(inStr):
    s1 = inStr.replace('&', '&amp;')
    s1 = s1.replace('<', '&lt;')
    s1 = s1.replace('>', '&gt;')
    return s1
Referenced by doxmlparser.index.quote_xml().
raise_parse_error()
def doxmlparser.index.raise_parse_error (node, msg)
Definition at line 807 of file index.py.
def raise_parse_error(node, msg):
    if node is not None:
        msg = '%s (element %s/line %d)' % (msg, node.tag, node.sourceline,)
    raise GDSParseError(msg)
Referenced by doxmlparser.index.GeneratedsSuper.gds_parse_boolean(), doxmlparser.index.GeneratedsSuper.gds_parse_decimal(), doxmlparser.index.GeneratedsSuper.gds_parse_double(), doxmlparser.index.GeneratedsSuper.gds_parse_float(), doxmlparser.index.GeneratedsSuper.gds_parse_integer(), doxmlparser.index.GeneratedsSuper.gds_validate_boolean(), doxmlparser.index.GeneratedsSuper.gds_validate_boolean_list(), doxmlparser.index.GeneratedsSuper.gds_validate_decimal(), doxmlparser.index.GeneratedsSuper.gds_validate_decimal_list(), doxmlparser.index.GeneratedsSuper.gds_validate_double(), doxmlparser.index.GeneratedsSuper.gds_validate_double_list(), doxmlparser.index.GeneratedsSuper.gds_validate_float(), doxmlparser.index.GeneratedsSuper.gds_validate_float_list(), doxmlparser.index.GeneratedsSuper.gds_validate_integer(), and doxmlparser.index.GeneratedsSuper.gds_validate_integer_list().
showIndent()
def doxmlparser.index.showIndent (outfile, level, pretty_print = True)
Definition at line 709 of file index.py.
def showIndent(outfile, level, pretty_print=True):
    if pretty_print:
        for idx in range(level):
            outfile.write(' ')
Referenced by doxmlparser.index.CompoundType.export(), doxmlparser.index.DoxygenType.export(), doxmlparser.index.MemberType.export(), doxmlparser.index.CompoundType.exportChildren(), doxmlparser.index.MemberType.exportChildren(), and doxmlparser.index.MixedContainer.exportLiteral().
usage()
def doxmlparser.index.usage ()
Definition at line 1432 of file index.py.
def usage():
    print(USAGE_TEXT)
    sys.exit(1)
References print().
Referenced by doxmlparser.index.MemberType.buildChildren(), and doxmlparser.index.main().
Variable Documentation
__all__
list doxmlparser.index.__all__ [private]
Initial value:
= [
    "CompoundType",
    "DoxygenType",
    "MemberType"
]
Definition at line 1618 of file index.py.
BaseStrType_
doxmlparser.index.BaseStrType_ = basestring
Definition at line 44 of file index.py.
CapturedNsmap_
dictionary doxmlparser.index.CapturedNsmap_ = {}
Definition at line 694 of file index.py.
CDATA_pattern_
doxmlparser.index.CDATA_pattern_ = re_.compile(r`<!\[CDATA\[.*?\]\]>`, re_.DOTALL)
Definition at line 698 of file index.py.
CurrentSubclassModule_
doxmlparser.index.CurrentSubclassModule_ = None
Definition at line 702 of file index.py.
Enum
doxmlparser.index.Enum = object
Definition at line 166 of file index.py.
Referenced by doxmlparser.index.MemberSpec_.get_optional().
ExternalEncoding
string doxmlparser.index.ExternalEncoding = ''
Definition at line 690 of file index.py.
GDSClassesMapping
dictionary doxmlparser.index.GDSClassesMapping
Initial value:
= {
    'doxygenindex': DoxygenType,
}
Definition at line 1422 of file index.py.
GenerateDSNamespaceDefs_
dictionary doxmlparser.index.GenerateDSNamespaceDefs_ = {}
Definition at line 117 of file index.py.
GenerateDSNamespaceTypePrefixes_
dictionary doxmlparser.index.GenerateDSNamespaceTypePrefixes_ = {}
Definition at line 121 of file index.py.
ModulenotfoundExp_
doxmlparser.index.ModulenotfoundExp_ = ModuleNotFoundError
Definition at line 26 of file index.py.
Namespace_extract_pat_
doxmlparser.index.Namespace_extract_pat_ = re_.compile(r'{(.*)}(.*)')
Definition at line 697 of file index.py.
NamespaceToDefMappings_
dictionary doxmlparser.index.NamespaceToDefMappings_ = {'http://www.w3.org/XML/1998/namespace': []}
Definition at line 1616 of file index.py.
RenameMappings_
dictionary doxmlparser.index.RenameMappings_
Initial value:
= {
}
Definition at line 1609 of file index.py.
SaveElementTreeNode
bool doxmlparser.index.SaveElementTreeNode = True
Definition at line 42 of file index.py.
String_cleanup_pat_
doxmlparser.index.String_cleanup_pat_ = re_.compile(r`[\n\r\s]+`)
Definition at line 696 of file index.py.
Tag_pattern_
doxmlparser.index.Tag_pattern_ = re_.compile(r'({.*})?(.*)')
Definition at line 695 of file index.py.
USAGE_TEXT
string doxmlparser.index.USAGE_TEXT
Initial value:
= """
Usage: python <Parser>.py [ -s ] <in_xml_file>
"""
Definition at line 1427 of file index.py.
UseCapturedNS_
bool doxmlparser.index.UseCapturedNS_ = True
Definition at line 693 of file index.py.
Validate_simpletypes_
bool doxmlparser.index.Validate_simpletypes_ = True
Definition at line 41 of file index.py.