doxygen/src/qhp.cpp File Reference
#include <algorithm>
#include <fstream>
#include <memory>
#include <string.h>
#include <vector>
#include <cassert>
#include `config.h`
#include `debug.h`
#include `doxygen.h`
#include `groupdef.h`
#include `memberdef.h`
#include `message.h`
#include `qhp.h`
#include `textstream.h`
#include `util.h`
Classes
class QhpSectionTree
struct QhpSectionTree::Node
class Qhp::Private
Functions
static void writeIndent (TextStream &t, int indent)
static QCString getFullProjectName ()
static QCString makeFileName (const QCString &withoutExtension)
static QCString makeRef (const QCString &withoutExtension, const QCString &anchor)
Function Documentation
getFullProjectName()
static QCString getFullProjectName () [static]
Definition at line 155 of file qhp.cpp.
{
  QCString projectName = Config_getString(PROJECT_NAME);
  QCString versionText = Config_getString(PROJECT_NUMBER);
  if (projectName.isEmpty()) projectName="Root";
  if (!versionText.isEmpty()) projectName+=" "+versionText;
  return projectName;
}
References Config_getString, and QCString::isEmpty().
makeFileName()
static QCString makeFileName (const QCString & withoutExtension) [static]
Definition at line 164 of file qhp.cpp.
{
  QCString result=withoutExtension;
  if (!result.isEmpty())
  {
    if (result.at(0)=='!') // relative URL -> strip marker
    {
      result=result.mid(1);
    }
    else // add specified HTML extension
    {
      result = addHtmlExtensionIfMissing(result);
    }
  }
  return result;
}
References addHtmlExtensionIfMissing(), QCString::at(), QCString::isEmpty(), and QCString::mid().
Referenced by makeRef().
makeRef()
static QCString makeRef (const QCString & withoutExtension, const QCString & anchor) [static]
Definition at line 181 of file qhp.cpp.
{
  //printf("QHP::makeRef(%s,%s)\n",withoutExtension,anchor);
  if (withoutExtension.isEmpty()) return QCString();
  QCString result = makeFileName(withoutExtension);
  if (anchor.isEmpty()) return result;
  return result+"#"+anchor;
}
References QCString::isEmpty(), and makeFileName().
writeIndent()
static void writeIndent (TextStream & t, int indent) [inline], [static]
Definition at line 31 of file qhp.cpp.
{
  if (Debug::isFlagSet(Debug::Qhp))
  {
    for (int i=0;i<indent;i++) t << " ";
  }
}
References Debug::isFlagSet(), and Debug::Qhp.
Referenced by QhpSectionTree::traverse(), and QhpSectionTree::writeToc().