doxygen/src/vhdldocgen.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <string.h>
#include <map>
#include <algorithm>
#include `qcstring.h`
#include `vhdldocgen.h`
#include `message.h`
#include `config.h`
#include `doxygen.h`
#include `util.h`
#include `language.h`
#include `commentscan.h`
#include `definition.h`
#include `searchindex.h`
#include `outputlist.h`
#include `parserintf.h`
#include `layout.h`
#include `arguments.h`
#include `portable.h`
#include `memberlist.h`
#include `memberdef.h`
#include `groupdef.h`
#include `classlist.h`
#include `namespacedef.h`
#include `filename.h`
#include `membergroup.h`
#include `membername.h`
#include `plantuml.h`
#include `vhdljjparser.h`
#include `VhdlParser.h`
#include `regex.h`
#include `textstream.h`
Macros
#define theTranslator_vhdlType theTranslator->trVhdlType
#define STARTL
#define DECLN
#define STARTFIN (FlowChart::START_NO | FlowChart::END_NO)
#define LOOP
#define ENDCL (FlowChart::END_CASE | FlowChart::END_LOOP)
#define EEND (FlowChart::ENDIF_NO | FlowChart::ELSE_NO)
#define IFF (FlowChart::ELSIF_NO | FlowChart::IF_NO)
#define EXITNEXT (FlowChart::EXIT_NO | FlowChart::NEXT_NO)
#define EMPTY (EEND | FlowChart::ELSIF_NO)
#define EE (FlowChart::ELSE_NO | FlowChart::ELSIF_NO)
#define EMPTNODE (ENDCL | EEND | FlowChart::ELSIF_NO)
#define FLOWLEN (flowList.size()-1)
Functions
static void initUCF (Entry *root, const QCString &type, QCString &qcs, int line, const QCString &fileName, QCString &brief)
static void writeUCFLink (const MemberDef *mdef, OutputList &ol)
static void addInstance (ClassDefMutable *entity, ClassDefMutable *arch, ClassDefMutable *inst, const std::shared_ptr< Entry > &cur)
static void createSVG ()
static void startDot (TextStream &t)
static void startTable (TextStream &t, const QCString &className)
static std::vector< const MemberDef * > getPorts (const ClassDef *cd)
static void writeVhdlEntityToolTip (TextStream &t, ClassDef *cd)
static void endDot (TextStream &t)
static void writeTable (const std::vector< const MemberDef * > &portList, TextStream &t)
static void endTable (TextStream &t)
static void writeClassToDot (TextStream &t, ClassDef *cd)
static void writeVhdlDotLink (TextStream &t, const QCString &a, const QCString &b, const QCString &style)
static void codify (TextStream &t, const QCString &str)
static void writeLink (const MemberDef *mdef, OutputList &ol)
static void startFonts (const QCString &q, const char *keyword, OutputList &ol)
static QCString splitString (QCString &str, char c)
static int compareString (const QCString &s1, const QCString &s2)
static QCString formatBriefNote (const QCString &brief, ClassDef *cd)
static void writeColumn (TextStream &t, const MemberDef *md, bool start)
static bool membersHaveSpecificType (const MemberList *ml, uint64 type)
static const MemberDef * findMemFlow (const MemberDef *mdef)
void alignText (QCString &q)
Variables
static const MemberDef * flowMember =0
static const std::set< std::string > g_vhdlKeyWordSet0
static const std::set< std::string > g_vhdlKeyWordSet1
static const std::set< std::string > g_vhdlKeyWordSet2
static const std::set< std::string > g_vhdlKeyWordSet3
static std::map< std::string, const MemberDef * > g_varMap
static std::vector< ClassDef * > g_classList
static std::map< ClassDef *, std::vector< ClassDef * > > g_packages
static int recordCounter =0
static std::vector< const MemberDef * > mdList
static int ifcounter =0
static int nodeCounter =0
xx xx xx xx xx xx xx xx xx
struct {
 const char * textNodeLink
 const char * yesNodeLink
 const char * noNodeLink
 const char * comment
 const char * decisionNode
 const char * varNode
 const char * startEndNode
 const char * textNode
} flowCol
std::vector< FlowChart > flowList
Macro Definition Documentation
DECLN
#define DECLN
Value:
                  (FlowChart::WHEN_NO | \
                  FlowChart::ELSIF_NO | FlowChart::IF_NO | \
                  FlowChart::FOR_NO | FlowChart::WHILE_NO | \
                  FlowChart::CASE_NO | FlowChart::LOOP_NO)
Definition at line 2845 of file vhdldocgen.cpp.
EE
#define EE (FlowChart::ELSE_NO | FlowChart::ELSIF_NO)
Definition at line 2857 of file vhdldocgen.cpp.
EEND
#define EEND (FlowChart::ENDIF_NO | FlowChart::ELSE_NO)
Definition at line 2853 of file vhdldocgen.cpp.
EMPTNODE
#define EMPTNODE (ENDCL | EEND | FlowChart::ELSIF_NO)
Definition at line 2858 of file vhdldocgen.cpp.
EMPTY
#define EMPTY (EEND | FlowChart::ELSIF_NO)
Definition at line 2856 of file vhdldocgen.cpp.
ENDCL
#define ENDCL (FlowChart::END_CASE | FlowChart::END_LOOP)
Definition at line 2852 of file vhdldocgen.cpp.
EXITNEXT
#define EXITNEXT (FlowChart::EXIT_NO | FlowChart::NEXT_NO)
Definition at line 2855 of file vhdldocgen.cpp.
FLOWLEN
#define FLOWLEN (flowList.size()-1)
Definition at line 2859 of file vhdldocgen.cpp.
IFF
#define IFF (FlowChart::ELSIF_NO | FlowChart::IF_NO)
Definition at line 2854 of file vhdldocgen.cpp.
LOOP
#define LOOP
Value:
                  (FlowChart::FOR_NO | FlowChart::WHILE_NO | \
                  FlowChart::LOOP_NO)
Definition at line 2850 of file vhdldocgen.cpp.
STARTFIN
#define STARTFIN (FlowChart::START_NO | FlowChart::END_NO)
Definition at line 2849 of file vhdldocgen.cpp.
STARTL
#define STARTL
Value:
                  (FlowChart::WHILE_NO | FlowChart::IF_NO | \
                  FlowChart::FOR_NO | FlowChart::CASE_NO | \
                  FlowChart::LOOP_NO | WHEN_NO)
Definition at line 2842 of file vhdldocgen.cpp.
theTranslator_vhdlType
#define theTranslator_vhdlType theTranslator->trVhdlType
Definition at line 65 of file vhdldocgen.cpp.
Function Documentation
addInstance()
static void addInstance (ClassDefMutable * entity, ClassDefMutable * arch, ClassDefMutable * inst, const std::shared_ptr< Entry > & cur) [static]
Definition at line 2540 of file vhdldocgen.cpp.
{
  QCString bName,n1;
  if (ar==0) return;
  if (classEntity==0)
  {
    //add component inst
    n1=cur->type;
    goto ferr;
  }
  if (classEntity==cd) return;
  bName=classEntity->name();
  // fprintf(stderr,"\naddInstance %s to %s %s %s\n",qPrint(classEntity->name()),qPrint(cd->name()),qPrint(ar->name()),cur->name);
  n1=classEntity->name();
  if (!cd->isBaseClass(classEntity, true))
  {
    cd->insertBaseClass(classEntity,n1,Public,Normal,QCString());
  }
  else
  {
    VhdlDocGen::addBaseClass(cd,classEntity);
  }
  if (!VhdlDocGen::isSubClass(classEntity,cd,true,0))
  {
    classEntity->insertSubClass(cd,Public,Normal,QCString());
    classEntity->setLanguage(SrcLangExt_VHDL);
  }
ferr:
  QCString uu=cur->name;
  std::unique_ptr<MemberDefMutable> md { createMemberDef(
      ar->getDefFileName(), cur->startLine,cur->startColumn,
      n1,uu,uu, QCString(),
      Public, Normal, cur->stat,Member,
      MemberType_Variable,
      ArgumentList(),
      ArgumentList(),
      "") };
  if (!ar->getOutputFileBase().isEmpty())
  {
    TagInfo tg;
    tg.anchor = 0;
    tg.fileName = ar->getOutputFileBase();
    tg.tagName = 0;
    md->setTagInfo(&tg);
  }
  //fprintf(stderr,"\n%s%s%s\n",qPrint(md->name()),qPrint(cur->brief),qPrint(cur->doc));
  md->setLanguage(SrcLangExt_VHDL);
  md->setMemberSpecifiers(VhdlDocGen::INSTANTIATION);
  md->setBriefDescription(cur->brief,cur->briefFile,cur->briefLine);
  md->setBodySegment(cur->startLine,cur->startLine,-1) ;
  md->setDocumentation(cur->doc,cur->docFile,cur->docLine);
  FileDef *fd=ar->getFileDef();
  md->setBodyDef(fd);
  ar->insertMember(md.get());
  MemberName *mn = Doxygen::functionNameLinkedMap->add(uu);
  mn->push_back(std::move(md));
}
References LinkedMap< T, Hash, KeyEqual, Map >::add(), VhdlDocGen::addBaseClass(), TagInfo::anchor, createMemberDef(), TagInfo::fileName, Doxygen::functionNameLinkedMap, Definition::getDefFileName(), ClassDef::getFileDef(), ClassDef::getOutputFileBase(), ClassDefMutable::insertBaseClass(), ClassDefMutable::insertMember(), ClassDefMutable::insertSubClass(), VhdlDocGen::INSTANTIATION, ClassDef::isBaseClass(), QCString::isEmpty(), VhdlDocGen::isSubClass(), Member, MemberType_Variable, Definition::name(), Normal, Public, MemberName::push_back(), DefinitionMutable::setBodyDef(), DefinitionMutable::setBodySegment(), MemberDefMutable::setBriefDescription(), MemberDefMutable::setDocumentation(), DefinitionMutable::setLanguage(), MemberDefMutable::setMemberSpecifiers(), MemberDefMutable::setTagInfo(), SrcLangExt_VHDL, and TagInfo::tagName.
alignText()
void alignText (QCString & q)
Definition at line 2894 of file vhdldocgen.cpp.
{
  if (q.length()<=80) return;
  if (q.length()>200)
  {
    q.resize(200);
  }
  q.append(" ...");
  QCString str(q);
  QCString temp;
  while (str.length()>80)
  {
    int j=std::max(str.findRev(' ',80),str.findRev('|',80));
    if (j<=0)
    {
      temp+=str;
      q=temp;
      return;
    }
    else
    {
      QCString qcs=str.left(j);
      temp+=qcs+"\\";
      temp+="n";
      str.remove(0,j);
    }
  }//while
 q=temp+str;
// #endif
}
References QCString::append(), QCString::findRev(), QCString::left(), QCString::length(), QCString::remove(), and QCString::resize().
codify()
static void codify (TextStream & t, const QCString & str) [static]
Definition at line 99 of file vhdldocgen.cpp.
{
  if (!str.isEmpty())
  {
    const char *p=str.data();
    char c;
    while (*p)
    {
      c=*p++;
      switch(c)
      {
        case '<': t << "&lt;";
                   break;
        case '>': t << "&gt;";
                   break;
        case '&': t << "&amp;";
                   break;
        case '\'': t << "&#39;";
                   break;
        case '"': t << "&quot;";
                   break;
        default: t << c;
                   break;
      }
    }
  }
}
References c, QCString::data(), QCString::isEmpty(), and p.
Referenced by writeColumn().
compareString()
static int compareString (const QCString & s1, const QCString & s2) [static]
Definition at line 154 of file vhdldocgen.cpp.
{
  return qstricmp(s1.stripWhiteSpace(),s2.stripWhiteSpace());
}
References qstricmp(), and QCString::stripWhiteSpace().
createSVG()
static void createSVG () [static]
Definition at line 159 of file vhdldocgen.cpp.
{
    QCString ov =Config_getString(HTML_OUTPUT);
    QCString dir="-o \""+ov+"/vhdl_design_overview.html\"";
    ov+="/vhdl_design.dot";
    QCString vlargs="-Tsvg \""+ov+"\" "+dir ;
    if (Portable::system(Doxygen::verifiedDotPath,vlargs)!=0)
    {
      err("could not create dot file");
    }
}
References Config_getString, err(), Portable::system(), and Doxygen::verifiedDotPath.
endDot()
static void endDot (TextStream & t) [static]
Definition at line 250 of file vhdldocgen.cpp.
{
  t <<" } \n";
}
endTable()
static void endTable (TextStream & t) [static]
Definition at line 395 of file vhdldocgen.cpp.
{
  t << "</TABLE>>\n";
  t << "] \n";
}
findMemFlow()
static const MemberDef * findMemFlow (const MemberDef * mdef) [static]
Definition at line 2732 of file vhdldocgen.cpp.
{
  for (const auto &md : mdList)
  {
    if (md->name()==mdef->name() && md->getStartBodyLine()==mdef->getStartBodyLine())
    {
      return md;
    }
  }
  return 0;
}
References Definition::getStartBodyLine(), mdList, and Definition::name().
formatBriefNote()
static QCString formatBriefNote (const QCString & brief, ClassDef * cd) [static]
Definition at line 273 of file vhdldocgen.cpp.
{
  QCString vForm;
  QCString repl("<BR ALIGN=\"LEFT\"/>");
  QCString file=cd->getDefFileName();
  int k=cd->briefLine();
  auto qsl=split(brief.str(),"\n");
  for(const auto &line : qsl)
  {
    vForm+=parseCommentAsText(cd,NULL,line.c_str(),file,k);
    k++;
    vForm+=repl;
  }
  return vForm;
}
References Definition::briefLine(), caseconvert::file, Definition::getDefFileName(), parseCommentAsText(), split(), and QCString::str().
Referenced by writeVhdlEntityToolTip().
getPorts()
static std::vector< const MemberDef * > getPorts (const ClassDef * cd) [static]
Definition at line 415 of file vhdldocgen.cpp.
{
  MemberList *ml = cd->getMemberList(MemberListType_variableMembers);
  std::vector<const MemberDef *> portList;
  if (ml==0)
  {
    return portList;
  }
  for (const auto &md : *ml)
  {
    if (md->getMemberSpecifiers()==VhdlDocGen::PORT)
    {
      portList.push_back(md);
    }
  }
  return portList;
}
References ClassDef::getMemberList(), MemberListType_variableMembers, VhdlDocGen::PORT, and MemberVector::push_back().
initUCF()
static void initUCF (Entry * root, const QCString & type, QCString & qcs, int line, const QCString & fileName, QCString & brief) [static]
Definition at line 2322 of file vhdldocgen.cpp.
{
  if (qcs.isEmpty())return;
  QCString n;
  VhdlDocGen::deleteAllChars(qcs,';');
  qcs=qcs.stripWhiteSpace();
  static const reg::Ex reg(R"([\s=])");
  int i = findIndex(qcs.str(),reg);
  if (i<0) return;
  if (i==0)
  {
    n=type;
    VhdlDocGen::deleteAllChars(n,'#');
  }
  else
  {
    n=qcs.left(i);
  }
  qcs=qcs.remove(0,i+1);
  // qcs.prepend("|");
  qcs.stripPrefix("=");
  std::shared_ptr<Entry> current = std::make_shared<Entry>();
  current->spec=VhdlDocGen::UCF_CONST;
  current->section=Entry::VARIABLE_SEC;
  current->bodyLine=line;
  current->fileName=fileName;
  current->type="ucf_const";
  current->args+=qcs;
  current->lang= SrcLangExt_VHDL ;
  // adding dummy name for constraints like VOLTAGE=5,TEMPERATURE=20 C
  if (n.isEmpty())
  {
    n="dummy";
    n+=VhdlDocGen::getRecordNumber();
  }
  current->name= n+"_";
  current->name.append(VhdlDocGen::getRecordNumber());
  if (!brief.isEmpty())
  {
    current->brief=brief;
    current->briefLine=line;
    current->briefFile=fileName;
    brief.resize(0);
  }
  root->moveToSubEntryAndKeep(current);
}
References VhdlDocGen::deleteAllChars(), findIndex(), VhdlDocGen::getRecordNumber(), QCString::isEmpty(), QCString::left(), Entry::moveToSubEntryAndKeep(), n, QCString::remove(), QCString::resize(), SrcLangExt_VHDL, QCString::str(), QCString::stripPrefix(), QCString::stripWhiteSpace(), VhdlDocGen::UCF_CONST, and Entry::VARIABLE_SEC.
membersHaveSpecificType()
static bool membersHaveSpecificType (const MemberList * ml, uint64 type) [static]
Definition at line 2077 of file vhdldocgen.cpp.
{
  if (ml==0) return FALSE;
  for (const auto &mdd : *ml)
  {
    if (mdd->getMemberSpecifiers()==type) //is type in class
    {
      return TRUE;
    }
  }
  for (const auto &mg : ml->getMemberGroupList())
  {
    if (!mg->members().empty())
    {
      if (membersHaveSpecificType(&mg->members(),type)) return TRUE;
    }
  }
  return FALSE;
}
References FALSE, MemberList::getMemberGroupList(), membersHaveSpecificType(), and TRUE.
Referenced by membersHaveSpecificType().
splitString()
static QCString splitString (QCString & str, char c) [static]
Definition at line 142 of file vhdldocgen.cpp.
{
  QCString n=str;
  int i=str.find(c);
  if (i>0)
  {
    n=str.left(i);
    str=str.remove(0,i+1);
  }
  return n;
}
References c, QCString::find(), QCString::left(), n, and QCString::remove().
Referenced by writeUCFLink().
startDot()
static void startDot (TextStream & t) [static]
Definition at line 242 of file vhdldocgen.cpp.
{
  t << " digraph G { \n";
  t << "rankdir=LR \n";
  t << "concentrate=TRUE\n";
  t << "stylesheet=\"doxygen.css\"\n";
}
startFonts()
static void startFonts (const QCString & q, const char * keyword, OutputList & ol) [static]
Definition at line 135 of file vhdldocgen.cpp.
{
  ol.startFontClass(keyword);
  ol.docify(q);
  ol.endFontClass();
}
References OutputList::docify(), OutputList::endFontClass(), and OutputList::startFontClass().
startTable()
static void startTable (TextStream & t, const QCString & className) [static]
Definition at line 255 of file vhdldocgen.cpp.
{
  t << className <<" [ shape=none , fontname=\"arial\", fontcolor=\"blue\" , \n";
  t << "label=<<TABLE BORDER=\"0\" CELLBORDER=\"1\" CELLSPACING=\"0\">\n";
}
writeClassToDot()
static void writeClassToDot (TextStream & t, ClassDef * cd) [static]
Definition at line 401 of file vhdldocgen.cpp.
{
  t << "<TR><TD COLSPAN=\"2\" BGCOLOR=\"yellow\" ";
  t << "PORT=\"";
  t << cd->name();
  t << "\" ";
  t << "href=\"";
  t << addHtmlExtensionIfMissing(cd->getOutputFileBase());
  t << "\" ";
  t << ">";
  t << cd->name();
  t << " </TD></TR>\n";
}
References addHtmlExtensionIfMissing(), ClassDef::getOutputFileBase(), and Definition::name().
writeColumn()
static void writeColumn (TextStream & t, const MemberDef * md, bool start) [static]
Definition at line 312 of file vhdldocgen.cpp.
{
  QCString toolTip;
  bool bidir=(md!=0 &&(qstricmp(md->typeString(),"inout")==0));
  if (md)
  {
    toolTip=md->briefDescriptionAsTooltip();
    if (!toolTip.isEmpty())
    {
      QCString largs = md->argsString();
      toolTip+=" [";
      toolTip+=substitute(largs,"%"," ");
      toolTip+="]";
    }
  }
  if (start)
  {
    t <<"<TR>\n";
  }
  t << "<TD ALIGN=\"LEFT\" ";
  if (md)
  {
    t << "href=\"";
    t << addHtmlExtensionIfMissing(md->getOutputFileBase());
    t << "#" << md->anchor();
    t<<"\" ";
    t<<" TOOLTIP=\"";
    if (!toolTip.isEmpty())
    {
      codify(t,toolTip);
    }
    else
    {
      QCString largs = md->argsString();
      if (!largs.isEmpty())
      {
        largs=substitute(largs,"%"," ");
        codify(t,largs);
      }
    }
    t << "\" ";
    t << " PORT=\"";
    t << md->name();
    t << "\" ";
  }
  if (!toolTip.isEmpty())
  {
    // if (!toolTip.isEmpty())
    if (bidir)
      t << "BGCOLOR=\"orange\">";
    else
      t << "BGCOLOR=\"azure\">";
  }
  else if (bidir)
  {
    t << "BGCOLOR=\"pink\">";
  }
  else
  {
    t << "BGCOLOR=\"lightgrey\">";
  }
  if (md)
  {
    t << md->name();
  }
  else
  {
    t << " \n";
  }
  t << "</TD>\n";
  if (!start)
  {
    t << "</TR>\n";
  }
}
References addHtmlExtensionIfMissing(), MemberDef::anchor(), MemberDef::argsString(), Definition::briefDescriptionAsTooltip(), codify(), MemberDef::getOutputFileBase(), QCString::isEmpty(), Definition::name(), qstricmp(), substitute(), and MemberDef::typeString().
Referenced by writeTable().
writeLink()
static void writeLink (const MemberDef * mdef, OutputList & ol) [static]
Definition at line 127 of file vhdldocgen.cpp.
{
  ol.writeObjectLink(mdef->getReference(),
      mdef->getOutputFileBase(),
      mdef->anchor(),
      mdef->name());
}
References MemberDef::anchor(), MemberDef::getOutputFileBase(), MemberDef::getReference(), Definition::name(), and OutputList::writeObjectLink().
Referenced by writeUCFLink().
writeTable()
static void writeTable (const std::vector< const MemberDef * > & portList, TextStream & t) [static]
Definition at line 437 of file vhdldocgen.cpp.
{
  std::vector<const MemberDef *> inPorts;
  std::vector<const MemberDef *> outPorts;
  for (const auto &md : portList)
  {
    QCString qc=md->typeString();
    if (qc=="in")
    {
      inPorts.push_back(md);
    }
    else
    {
      outPorts.push_back(md);
    }
  }
  size_t inp = inPorts.size();
  size_t outp = outPorts.size();
  size_t maxLen;
  if (inp>=outp)
  {
    maxLen=inp;
  }
  else
  {
    maxLen=outp;
  }
  size_t i;
  for (i=0;i<maxLen;i++)
  {
    //write inports
    if (i<inp)
    {
      auto md = inPorts[i];
      writeColumn(t,md,TRUE);
    }
    else
    {
      writeColumn(t,NULL,TRUE);
    }
    if (i<outp)
    {
      auto md = outPorts[i];
      writeColumn(t,md,FALSE);
    }
    else
    {
      writeColumn(t,NULL,FALSE);
    }
  }
}
References FALSE, QCString::size(), TRUE, and writeColumn().
writeUCFLink()
static void writeUCFLink (const MemberDef * mdef, OutputList & ol) [static]
Definition at line 2379 of file vhdldocgen.cpp.
{
  QCString largs(mdef->argsString());
  QCString n= splitString(largs, '#');
  // VhdlDocGen::adjustRecordMember(mdef);
  bool equ=(n.length()==largs.length());
  if (!equ)
  {
    ol.writeString(n);
    ol.docify(" ");
    ol.insertMemberAlign();
  }
  if (mdef->name().contains("dummy")==0)
  {
    writeLink(mdef,ol);
  }
  if (equ)
  {
    ol.insertMemberAlign();
  }
  ol.docify(" ");
  VhdlDocGen::formatString(largs,ol,mdef);
}
References MemberDef::argsString(), QCString::contains(), OutputList::docify(), VhdlDocGen::formatString(), OutputList::insertMemberAlign(), QCString::length(), n, Definition::name(), splitString(), writeLink(), and OutputList::writeString().
writeVhdlDotLink()
static void writeVhdlDotLink (TextStream & t, const QCString & a, const QCString & b, const QCString & style) [static]
Definition at line 261 of file vhdldocgen.cpp.
{
  t << a << "->" << b;
  if (!style.isEmpty())
  {
    t << "[style=" << style << "];\n";
  }
  t << "\n";
}
References a, b, and style.
Referenced by writeVhdlEntityToolTip().
writeVhdlEntityToolTip()
static void writeVhdlEntityToolTip (TextStream & t, ClassDef * cd) [static]
Definition at line 291 of file vhdldocgen.cpp.
{
  QCString brief=cd->briefDescription();
  if (brief.isEmpty()) return;
  brief=formatBriefNote(brief,cd);
  QCString node="node";
  node+=VhdlDocGen::getRecordNumber();
  t << node <<"[shape=none margin=0.1, label=<\n";
  t << "<TABLE BORDER=\"0\" CELLBORDER=\"1\" CELLSPACING=\"0\" CELLPADDING=\"2\" >\n ";
  t << "<TR><TD BGCOLOR=\"lightcyan\"> ";
  t << brief;
  t << " </TD></TR></TABLE>>];";
  QCString dotn=cd->name()+":";
  dotn+=cd->name();
  writeVhdlDotLink(t,dotn,node,"dotted");
}
References Definition::briefDescription(), formatBriefNote(), VhdlDocGen::getRecordNumber(), QCString::isEmpty(), Definition::name(), and writeVhdlDotLink().
Variable Documentation
comment
const char* comment
Definition at line 2872 of file vhdldocgen.cpp.
decisionNode
const char* decisionNode
Definition at line 2873 of file vhdldocgen.cpp.
struct { ... } flowCol [static]
Initial value:
=
{ "green",
  "red",
  "black",
  "khaki",
  "0.7 0.3 1.0",
  "lightyellow",
  "white",
  "lightcyan"
}
flowList
std::vector<FlowChart> flowList
Definition at line 2888 of file vhdldocgen.cpp.
flowMember
const MemberDef* flowMember =0 [static]
Definition at line 84 of file vhdldocgen.cpp.
g_classList
std::vector<ClassDef*> g_classList [static]
Definition at line 594 of file vhdldocgen.cpp.
g_packages
std::map<ClassDef*,std::vector<ClassDef*> > g_packages [static]
Definition at line 595 of file vhdldocgen.cpp.
g_varMap
std::map<std::string,const MemberDef*> g_varMap [static]
Definition at line 593 of file vhdldocgen.cpp.
g_vhdlKeyWordSet0
const std::set< std::string > g_vhdlKeyWordSet0 [static]
Initial value:
=
{
  "abs","access","after","alias","all","and","architecture","array","assert","assume","assume_guarantee","attribute",
  "begin","block","body","buffer","bus",
  "case","component","configuration","constant","context","cover",
  "default","disconnect","downto",
  "else","elsif","end","entity","exit",
  "fairness","file","for","force","function",
  "generate","generic","group","guarded",
  "if","impure","in","inertial","inout","is",
  "label","library","linkage","literal","loop",
  "map","mod",
  "nand","new","next","nor","not","null",
  "of","on","open","or","others","out",
  "package","parameter","port","postponed","procedure","process","property","protected","pure",
  "range","record","register","reject","release","restrict","restrict_guarantee","rem","report","rol","ror","return",
  "select","sequence","severity","signal","shared","sla","sll","sra","srl","strong","subtype",
  "then","to","transport","type",
  "unaffected","units","until","use",
  "variable","vmode","vprop","vunit",
  "wait","when","while","with",
  "xor","xnor"
}
Definition at line 506 of file vhdldocgen.cpp.
g_vhdlKeyWordSet1
const std::set< std::string> g_vhdlKeyWordSet1 [static]
Initial value:
=
{
  "natural","unsigned","signed","string","boolean", "bit","bit_vector","character",
  "std_ulogic","std_ulogic_vector","std_logic","std_logic_vector","integer",
  "real","float","ufixed","sfixed","time","positive"
}
Definition at line 532 of file vhdldocgen.cpp.
g_vhdlKeyWordSet2
const std::set< std::string > g_vhdlKeyWordSet2 [static]
Initial value:
=
{
  "abs","and","or","not","mod","xor","rem","xnor","ror","rol","sla","sll"
}
Definition at line 540 of file vhdldocgen.cpp.
g_vhdlKeyWordSet3
const std::set< std::string > g_vhdlKeyWordSet3 [static]
Initial value:
=
{
  "base","left","right","high","low","ascending",
  "image","value","pos","val","succ","pred","leftof","rightof","left","right","high","low",
  "range","reverse_range","length","ascending","delayed","stable","quiet","transaction","event",
  "active","last_event","last_active","last_value","driving","driving_value","simple_name","instance_name","path_name"
}
Definition at line 546 of file vhdldocgen.cpp.
ifcounter
int ifcounter =0 [static]
Definition at line 2861 of file vhdldocgen.cpp.
mdList
std::vector<const MemberDef*> mdList [static]
Definition at line 2730 of file vhdldocgen.cpp.
Referenced by findMemFlow().
nodeCounter
int nodeCounter =0 [static]
Definition at line 2862 of file vhdldocgen.cpp.
noNodeLink
const char* noNodeLink
Definition at line 2869 of file vhdldocgen.cpp.
recordCounter
int recordCounter =0 [static]
Definition at line 1096 of file vhdldocgen.cpp.
startEndNode
const char* startEndNode
Definition at line 2875 of file vhdldocgen.cpp.
textNode
const char* textNode
Definition at line 2876 of file vhdldocgen.cpp.
textNodeLink
const char* textNodeLink
Definition at line 2867 of file vhdldocgen.cpp.
varNode
const char* varNode
Definition at line 2874 of file vhdldocgen.cpp.
yesNodeLink
const char* yesNodeLink
Definition at line 2868 of file vhdldocgen.cpp.