doxygen/src/perlmodgen.h File Reference
Functions
void setPerlModDoxyfile (const QCString &)
void generatePerlMod ()
Function Documentation
generatePerlMod()
void generatePerlMod ()
Definition at line 2854 of file perlmodgen.cpp.
{
  PerlModGenerator pmg(Config_getBool(PERLMOD_PRETTY));
  pmg.generate();
}
References Config_getBool, and PerlModGenerator::generate().
Referenced by generateOutput().
setPerlModDoxyfile()
void setPerlModDoxyfile (const QCString & qs)
Definition at line 1403 of file perlmodgen.cpp.
{
  pathDoxyfile = qs;
  pathDoxyExec = Dir::currentDirPath();
}
References Dir::currentDirPath(), pathDoxyExec, and pathDoxyfile.
Referenced by readConfiguration().