doxygen/src/dotnode.cpp File Reference
#include `dotnode.h`
#include `classdef.h`
#include `config.h`
#include `memberlist.h`
#include `membergroup.h`
#include `language.h`
#include `doxygen.h`
#include `util.h`
#include `textstream.h`
Classes
struct EdgeProperties
Macros
#define DEBUG_RENUMBERING 0
Functions
QCString escapeTooltip (const QCString &tooltip)
static void writeBoxMemberList (TextStream &t, char prot, const MemberList *ml, const ClassDef *scope, bool isStatic=FALSE, const StringUnorderedSet *skipNames=nullptr)
static QCString stripProtectionPrefix (const QCString &s)
Variables
static const char * normalEdgeColorMap []
static const char * normalArrowStyleMap []
static const char * normalEdgeStyleMap []
static const char * umlEdgeColorMap []
static const char * umlArrowStyleMap []
static const char * umlEdgeStyleMap []
static EdgeProperties normalEdgeProps
static EdgeProperties umlEdgeProps
Macro Definition Documentation
DEBUG_RENUMBERING
#define DEBUG_RENUMBERING 0
Definition at line 842 of file dotnode.cpp.
Function Documentation
escapeTooltip()
QCString escapeTooltip (const QCString & tooltip)
Definition at line 99 of file dotnode.cpp.
{
  if (tooltip.isEmpty()) return tooltip;
  QCString result;
  const char *p=tooltip.data();
  char c;
  while ((c=*p++))
  {
    switch(c)
    {
    case '"': result+="\\\""; break;
    case '\\': result+="\\\\"; break;
    default: result+=c; break;
    }
  }
  return result;
}
References c, QCString::data(), QCString::isEmpty(), and p.
stripProtectionPrefix()
static QCString stripProtectionPrefix (const QCString & s) [static]
Definition at line 254 of file dotnode.cpp.
{
  if (!s.isEmpty() && (s[0]=='-' || s[0]=='+' || s[0]=='~' || s[0]=='#'))
  {
    return s.mid(1);
  }
  else
  {
    return s;
  }
}
References s.
writeBoxMemberList()
static void writeBoxMemberList (TextStream & t, char prot, const MemberList * ml, const ClassDef * scope, bool isStatic = FALSE, const StringUnorderedSet * skipNames = nullptr) [static]
Definition at line 117 of file dotnode.cpp.
{
  if (ml)
  {
    int totalCount=0;
    for (const auto &mma : *ml)
    {
      if (mma->getClassDef()==scope &&
        (skipNames==nullptr || skipNames->find(mma->name().str())==std::end(*skipNames)))
      {
        totalCount++;
      }
    }
    int count=0;
    auto dotUmlDetails = Config_getEnum(DOT_UML_DETAILS);
    for (const auto &mma : *ml)
    {
      if (mma->getClassDef() == scope &&
        (skipNames==nullptr || skipNames->find(mma->name().str())==std::end(*skipNames)))
      {
        int numFields = Config_getInt(UML_LIMIT_NUM_FIELDS);
        if (numFields>0 && (totalCount>numFields*3/2 && count>=numFields))
        {
          t << theTranslator->trAndMore(QCString().sprintf("%d",totalCount-count)) << "\\l";
          break;
        }
        else
        {
          t << prot << " ";
          QCString label;
          if (dotUmlDetails==DOT_UML_DETAILS_t::YES)
          {
            label+=mma->typeString();
            label+=" ";
          }
          label+=mma->name();
          if (!mma->isObjCMethod() && (mma->isFunction() || mma->isSlot() || mma->isSignal()))
          {
            if (dotUmlDetails==DOT_UML_DETAILS_t::YES)
            {
              label+=mma->argsString();
            }
            else
            {
              label+="()";
            }
          }
          t << DotNode::convertLabel(label);
          t << "\\l";
          count++;
        }
      }
    }
    // write member groups within the memberlist
    for (const auto &mg : ml->getMemberGroupList())
    {
      if (!mg->members().empty())
      {
        writeBoxMemberList(t,prot,&mg->members(),scope,isStatic,skipNames);
      }
    }
  }
}
References Config_getEnum, Config_getInt, DotNode::convertLabel(), ghc::filesystem::end(), theTranslator, Translator::trAndMore(), and writeBoxMemberList().
Referenced by writeBoxMemberList().
Variable Documentation
normalArrowStyleMap
const char* normalArrowStyleMap[] [static]
Initial value:
=
{
  "empty",
  "empty",
  "empty",
  "open",
  0,
  0
}
Definition at line 46 of file dotnode.cpp.
normalEdgeColorMap
const char* normalEdgeColorMap[] [static]
Initial value:
=
{
  "steelblue1",
  "darkgreen",
  "firebrick4",
  "darkorchid3",
  "grey75",
  "orange",
  "orange"
}
mapping from protection levels to color names
Definition at line 35 of file dotnode.cpp.
normalEdgeProps
EdgeProperties normalEdgeProps [static]
Initial value:
=
{
  normalEdgeColorMap, normalArrowStyleMap, normalEdgeStyleMap
}
Definition at line 89 of file dotnode.cpp.
normalEdgeStyleMap
const char* normalEdgeStyleMap[] [static]
Initial value:
=
{
  "solid",
  "dashed"
}
Definition at line 56 of file dotnode.cpp.
umlArrowStyleMap
const char* umlArrowStyleMap[] [static]
Initial value:
=
{
  "onormal",
  "onormal",
  "onormal",
  "odiamond",
  0,
  0
}
Definition at line 73 of file dotnode.cpp.
umlEdgeColorMap
const char* umlEdgeColorMap[] [static]
Initial value:
=
{
  "steelblue1",
  "darkgreen",
  "firebrick4",
  "grey25",
  "grey75",
  "orange",
  "orange"
}
Definition at line 62 of file dotnode.cpp.
umlEdgeProps
EdgeProperties umlEdgeProps [static]
Initial value:
=
{
  umlEdgeColorMap, umlArrowStyleMap, umlEdgeStyleMap
}
Definition at line 94 of file dotnode.cpp.
umlEdgeStyleMap
const char* umlEdgeStyleMap[] [static]
Initial value:
=
{
  "solid",
  "solid"
}
Definition at line 83 of file dotnode.cpp.