doxygen/src/msc.h File Reference
Enumerations
enum MscOutputFormat {
MSC_BITMAP
, MSC_EPS
, MSC_SVG
, MSC_BITMAP
,
MSC_EPS
, MSC_SVG
 }
Functions
void writeMscGraphFromFile (const QCString &inFile, const QCString &outDir, const QCString &outFile, MscOutputFormat format, const QCString &srcFile, int srcLine)
QCString getMscImageMapFromFile (const QCString &inFile, const QCString &outDir, const QCString &relPath, const QCString &context, const QCString &srcFile, int srcLine)
void writeMscImageMapFromFile (TextStream &t, const QCString &inFile, const QCString &outDir, const QCString &relPath, const QCString &baseName, const QCString &context, MscOutputFormat format, const QCString &srcFile, int srcLine)
Enumeration Type Documentation
MscOutputFormat
enum MscOutputFormat
Enumerator
MSC_BITMAP
MSC_EPS
MSC_SVG
MSC_BITMAP
MSC_EPS
MSC_SVG
Definition at line 22 of file msc.h.
{ MSC_BITMAP , MSC_EPS, MSC_SVG };
Function Documentation
getMscImageMapFromFile()
QCString getMscImageMapFromFile (const QCString & inFile, const QCString & outDir, const QCString & relPath, const QCString & context, const QCString & srcFile, int srcLine)
writeMscGraphFromFile()
void writeMscGraphFromFile (const QCString & inFile, const QCString & outDir, const QCString & outFile, MscOutputFormat format, const QCString & srcFile, int srcLine)
Definition at line 95 of file msc.cpp.
{
  QCString absOutFile = outDir;
  absOutFile+=Portable::pathSeparator();
  absOutFile+=outFile;
  mscgen_format_t msc_format;
  QCString imgName = absOutFile;
  switch (format)
  {
    case MSC_BITMAP:
      msc_format = mscgen_format_png;
      imgName+=".png";
      break;
    case MSC_EPS:
      msc_format = mscgen_format_eps;
      imgName+=".eps";
      break;
    case MSC_SVG:
      msc_format = mscgen_format_svg;
      imgName+=".svg";
      break;
    default:
      return;
  }
  int code;
  if ((code=mscgen_generate(inFile.data(),imgName.data(),msc_format))!=0)
  {
    err_full(srcFile,srcLine,"Problems generating msc output (error=%s). Look for typos in you msc file %s\n",
        mscgen_error2str(code),qPrint(inFile));
    return;
  }
  if ((format==MSC_EPS) && (Config_getBool(USE_PDFLATEX)))
  {
    QCString epstopdfArgs(maxCmdLine);
    epstopdfArgs.sprintf("\"%s.eps\" --outfile=\"%s.pdf\"",
                         qPrint(absOutFile),qPrint(absOutFile));
    Portable::sysTimerStart();
    if (Portable::system("epstopdf",epstopdfArgs)!=0)
    {
      err_full(srcFile,srcLine,"Problems running epstopdf when processing '%s.eps'. Check your TeX installation!\n",
          qPrint(absOutFile));
    }
    Portable::sysTimerStop();
  }
  Doxygen::indexList->addImageFile(imgName);
}
References IndexList::addImageFile(), Config_getBool, QCString::data(), err_full(), Doxygen::indexList, maxCmdLine, MSC_BITMAP, MSC_EPS, MSC_SVG, mscgen_error2str(), mscgen_format_eps, mscgen_format_png, mscgen_format_svg, mscgen_generate(), outFile, Portable::pathSeparator(), qPrint(), QCString::sprintf(), Portable::system(), Portable::sysTimerStart(), and Portable::sysTimerStop().
Referenced by DocbookDocVisitor::startMscFile(), LatexDocVisitor::startMscFile(), RTFDocVisitor::writeMscFile(), DocbookDocVisitor::writeMscFile(), LatexDocVisitor::writeMscFile(), and HtmlDocVisitor::writeMscFile().
writeMscImageMapFromFile()
void writeMscImageMapFromFile (TextStream & t, const QCString & inFile, const QCString & outDir, const QCString & relPath, const QCString & baseName, const QCString & context, MscOutputFormat format, const QCString & srcFile, int srcLine)
Definition at line 172 of file msc.cpp.
{
  QCString mapName = baseName+".map";
  t << "<img src=\"" << relPath << baseName << ".";
  switch (format)
  {
    case MSC_BITMAP:
      t << "png";
      break;
    case MSC_EPS:
      t << "eps";
      break;
    case MSC_SVG:
      t << "svg";
      break;
    default:
      t << "unknown";
  }
  QCString imap = getMscImageMapFromFile(inFile,outDir,relPath,context,format==MSC_SVG,srcFile,srcLine);
  if (!imap.isEmpty())
  {
    t << "\" alt=\""
      << baseName << "\" border=\"0\" usemap=\"#" << mapName << "\"/>\n";
    t << "<map name=\"" << mapName << "\" id=\"" << mapName << "\">" << imap << "</map>\n";
  }
  else
  {
    t << "\" alt=\"" << baseName << "\" border=\"0\"/>\n";
  }
}
References getMscImageMapFromFile(), QCString::isEmpty(), MSC_BITMAP, MSC_EPS, and MSC_SVG.
Referenced by HtmlDocVisitor::writeMscFile().