doxygen/src/latexdocvisitor.cpp File Reference
#include <algorithm>
#include `htmlattrib.h`
#include `latexdocvisitor.h`
#include `latexgen.h`
#include `docparser.h`
#include `language.h`
#include `doxygen.h`
#include `outputgen.h`
#include `dot.h`
#include `util.h`
#include `message.h`
#include `parserintf.h`
#include `msc.h`
#include `dia.h`
#include `cite.h`
#include `filedef.h`
#include `config.h`
#include `htmlentity.h`
#include `emoji.h`
#include `plantuml.h`
#include `fileinfo.h`
#include `regex.h`
Functions
static const char * getSectionName (int level)
static void insertDimension (TextStream &t, QCString dimension, const char *orientationString)
static void visitPreStart (TextStream &t, bool hasCaption, QCString name, QCString width, QCString height, bool inlineImage=FALSE)
static void visitPostEnd (TextStream &t, bool hasCaption, bool inlineImage=FALSE)
static bool classEqualsReflist (const DocHtmlDescList &dl)
static bool listIsNested (const DocHtmlDescList &dl)
static bool tableIsNested (const DocNodeVariant *n)
static void writeStartTableCommand (TextStream &t, const DocNodeVariant *n, size_t cols)
static void writeEndTableCommand (TextStream &t, const DocNodeVariant *n)
Variables
const int maxLevels =5
static const char * secLabels [maxLevels]
Function Documentation
classEqualsReflist()
static bool classEqualsReflist (const DocHtmlDescList & dl) [static]
Definition at line 1040 of file latexdocvisitor.cpp.
{
  HtmlAttribList attrs = dl.attribs();
  auto it = std::find_if(attrs.begin(),attrs.end(),
                      [](const auto &att) { return att.name=="class"; });
  if (it!=attrs.end() && it->value == "reflist") return true;
  return false;
}
References DocHtmlDescList::attribs().
Referenced by listIsNested().
getSectionName()
static const char * getSectionName (int level) [static]
Definition at line 47 of file latexdocvisitor.cpp.
{
  bool compactLatex = Config_getBool(COMPACT_LATEX);
  int l = level;
  if (compactLatex) l++;
  if (Doxygen::insideMainPage) l--;
  return secLabels[std::min(maxLevels-1,l)];
}
References Config_getBool, Doxygen::insideMainPage, level, maxLevels, and secLabels.
insertDimension()
static void insertDimension (TextStream & t, QCString dimension, const char * orientationString) [static]
Definition at line 56 of file latexdocvisitor.cpp.
{
  // dimensions for latex images can be a percentage, in this case they need some extra
  // handling as the % symbol is used for comments
  static const reg::Ex re(R"((\d+)%)");
  std::string s = dimension.str();
  reg::Match match;
  if (reg::search(s,match,re))
  {
    bool ok;
    double percent = QCString(match[1].str()).toInt(&ok);
    if (ok)
    {
      t << percent/100.0 << "\\text" << orientationString;
      return;
    }
  }
  t << dimension;
}
References reg::match(), s, reg::search(), QCString::str(), string, and QCString::toInt().
Referenced by visitPreStart().
listIsNested()
static bool listIsNested (const DocHtmlDescList & dl) [static]
Definition at line 1049 of file latexdocvisitor.cpp.
{
  bool isNested=false;
  const DocNodeVariant *n = dl.parent();
  while (n && !isNested)
  {
    if (std::get_if<DocHtmlDescList>(n))
    {
      isNested = !classEqualsReflist(std::get<DocHtmlDescList>(*n));
    }
    n = ::parent(n);
  }
  return isNested;
}
References classEqualsReflist(), n, DocNode::parent(), and parent().
tableIsNested()
static bool tableIsNested (const DocNodeVariant * n) [static]
Definition at line 1105 of file latexdocvisitor.cpp.
{
  bool isNested=FALSE;
  while (n && !isNested)
  {
    isNested = holds_one_of_alternatives<DocHtmlTable,DocParamSect>(*n);
    n = ::parent(n);
  }
  return isNested;
}
References FALSE, n, and parent().
Referenced by writeEndTableCommand(), and writeStartTableCommand().
visitPostEnd()
static void visitPostEnd (TextStream & t, bool hasCaption, bool inlineImage = FALSE) [static]
Definition at line 148 of file latexdocvisitor.cpp.
{
    if (inlineImage)
    {
      t << "\n\\end{DoxyInlineImage}\n";
    }
    else
    {
      t << "}\n"; // end mbox or caption
      if (hasCaption)
      {
        t << "\\end{DoxyImage}\n";
      }
      else
      {
        t << "\\end{DoxyImageNoCaption}\n";
      }
    }
}
visitPreStart()
static void visitPreStart (TextStream & t, bool hasCaption, QCString name, QCString width, QCString height, bool inlineImage = FALSE) [static]
Definition at line 76 of file latexdocvisitor.cpp.
{
    if (inlineImage)
    {
      t << "\n\\begin{DoxyInlineImage}\n";
    }
    else
    {
      if (hasCaption)
      {
        t << "\n\\begin{DoxyImage}\n";
      }
      else
      {
        t << "\n\\begin{DoxyImageNoCaption}\n"
               " \\mbox{";
      }
    }
    t << "\\includegraphics";
    if (!width.isEmpty() || !height.isEmpty())
    {
      t << "[";
    }
    if (!width.isEmpty())
    {
      t << "width=";
      insertDimension(t, width, "width");
    }
    if (!width.isEmpty() && !height.isEmpty())
    {
      t << ",";
    }
    if (!height.isEmpty())
    {
      t << "height=";
      insertDimension(t, height, "height");
    }
    if (width.isEmpty() && height.isEmpty())
    {
      /* default setting */
      if (inlineImage)
      {
        t << "[height=\\baselineskip,keepaspectratio=true]";
      }
      else
      {
        t << "[width=\\textwidth,height=\\textheight/2,keepaspectratio=true]";
      }
    }
    else
    {
      t << "]";
    }
    t << "{" << name << "}";
    if (hasCaption)
    {
      if (!inlineImage)
      {
        t << "\n\\doxyfigcaption{";
      }
      else
      {
        t << "%"; // to catch the caption
      }
    }
}
References insertDimension(), QCString::isEmpty(), and setup::name.
writeEndTableCommand()
static void writeEndTableCommand (TextStream & t, const DocNodeVariant * n) [static]
Definition at line 1129 of file latexdocvisitor.cpp.
{
  if (tableIsNested(n))
  {
    t << "\\end{tabularx}}\n";
  }
  else
  {
    t << "\\end{longtabu}\n";
  }
  //return isNested ? "TabularNC" : "TabularC";
}
References n, and tableIsNested().
writeStartTableCommand()
static void writeStartTableCommand (TextStream & t, const DocNodeVariant * n, size_t cols) [static]
Definition at line 1116 of file latexdocvisitor.cpp.
{
  if (tableIsNested(n))
  {
    t << "{\\begin{tabularx}{\\linewidth}{|*{" << cols << "}{>{\\raggedright\\arraybackslash}X|}}";
  }
  else
  {
    t << "\\tabulinesep=1mm\n\\begin{longtabu}spread 0pt [c]{*{" << cols << "}{|X[-1]}|}\n";
  }
  //return isNested ? "TabularNC" : "TabularC";
}
References n, and tableIsNested().
Variable Documentation
maxLevels
const int maxLevels =5
Definition at line 43 of file latexdocvisitor.cpp.
secLabels
const char* secLabels[maxLevels] [static]
Initial value:
=
   { "doxysection","doxysubsection","doxysubsubsection","doxyparagraph","doxysubparagraph" }
Definition at line 44 of file latexdocvisitor.cpp.
Referenced by getSectionName().