doxygen/src/rtfgen.cpp File Reference
#include <stdlib.h>
#include `rtfgen.h`
#include `config.h`
#include `message.h`
#include `doxygen.h`
#include `util.h`
#include `diagram.h`
#include `language.h`
#include `dot.h`
#include `dotcallgraph.h`
#include `dotclassgraph.h`
#include `dotdirdeps.h`
#include `dotincldepgraph.h`
#include `version.h`
#include `pagedef.h`
#include `rtfstyle.h`
#include `rtfdocvisitor.h`
#include `docparser.h`
#include `dirdef.h`
#include `vhdldocgen.h`
#include `portable.h`
#include `groupdef.h`
#include `classlist.h`
#include `filename.h`
#include `namespacedef.h`
#include `dir.h`
#include `utf8.h`
#include `debug.h`
#include `datetime.h`
Macros
#define DBG_RTF(x)
Functions
static QCString dateToRTFDateString ()
static QCString makeIndexName (const QCString &s, int i)
bool isLeadBytes (int c)
static void encodeForOutput (TextStream &t, const QCString &s)
static bool preProcessFile (Dir &d, const QCString &infName, TextStream &t, bool bIncludeHeader=TRUE)
void testRTFOutput (const QCString &name)
Macro Definition Documentation
DBG_RTF
#define DBG_RTF(x)
Definition at line 52 of file rtfgen.cpp.
Function Documentation
dateToRTFDateString()
static QCString dateToRTFDateString () [static]
Definition at line 54 of file rtfgen.cpp.
{
  auto tm = getCurrentDateTime();
  QCString result;
  result.sprintf("\\yr%d\\mo%d\\dy%d\\hr%d\\min%d\\sec%d",
      tm.tm_year+1900, tm.tm_mon+1, tm.tm_mday,
      tm.tm_hour, tm.tm_min, tm.tm_sec);
  return result;
}
References getCurrentDateTime(), and QCString::sprintf().
encodeForOutput()
static void encodeForOutput (TextStream & t, const QCString & s) [static]
Definition at line 1986 of file rtfgen.cpp.
{
  if (s==0) return;
  QCString encoding;
  bool converted=FALSE;
  size_t l = s.length();
  static std::vector<char> enc;
  if (l*4>enc.size()) enc.resize(l*4); // worst case
  encoding.sprintf("CP%s",qPrint(theTranslator->trRTFansicp()));
  if (!encoding.isEmpty())
  {
    // convert from UTF-8 back to the output encoding
    void *cd = portable_iconv_open(encoding.data(),"UTF-8");
    if (cd!=reinterpret_cast<void *>(-1))
    {
      size_t iLeft=l;
      size_t oLeft=enc.size();
      const char *inputPtr = s.data();
      char *outputPtr = &enc[0];
      if (!portable_iconv(cd, &inputPtr, &iLeft, &outputPtr, &oLeft))
      {
        enc.resize(enc.size()-oLeft);
        converted=TRUE;
      }
      portable_iconv_close(cd);
    }
  }
  if (!converted) // if we did not convert anything, copy as is.
  {
    memcpy(enc.data(),s.data(),l);
    enc.resize(l);
  }
  bool multiByte = FALSE;
  for (size_t i=0;i<enc.size();i++)
  {
    uchar c = static_cast<uchar>(enc.at(i));
    if (c>=0x80 || multiByte)
    {
      char esc[10];
      sprintf(esc,"\\'%X",c); // escape sequence for SBCS and DBCS(1st&2nd bytes).
      t << esc;
      if (!multiByte)
      {
        multiByte = isLeadBytes(c); // It may be DBCS Codepages.
      }
      else
      {
        multiByte = FALSE; // end of Double Bytes Character.
      }
    }
    else
    {
      t << c;
    }
  }
}
isLeadBytes()
bool isLeadBytes (int c)
Definition at line 1954 of file rtfgen.cpp.
{
  bool result;
  QCString codePage = theTranslator->trRTFansicp();
  if (codePage == "932") // cp932 (Japanese Shift-JIS)
  {
    result = (0x81<=c && c<=0x9f) || (0xe0<=c && c<=0xfc);
  }
  else if (codePage == "936") // cp936 (Simplified Chinese GBK)
  {
    result = 0x81<=c && c<=0xFE;
  }
  else if (codePage == "949") // cp949 (Korean)
  {
    result = 0x81<=c && c<=0xFE;
  }
  else if (codePage == "950") // cp950 (Traditional Chinese Big5)
  {
    result = 0x81<=c && c<=0xFE;
  }
  else // for SBCS Codepages (cp1252,1251 etc...)
  {
    result = false;
  }
  return result;
}
makeIndexName()
static QCString makeIndexName (const QCString & s, int i) [static]
Definition at line 213 of file rtfgen.cpp.
{
  QCString result=s;
  result+=static_cast<char>(i+'0');
  return result;
}
References s.
preProcessFile()
static bool preProcessFile (Dir & d, const QCString & infName, TextStream & t, bool bIncludeHeader = TRUE) [static]
VERY brittle routine inline RTF's included by other RTF's. it is recursive and ugly.
Definition at line 2050 of file rtfgen.cpp.
{
  static bool rtfDebug = Debug::isFlagSet(Debug::Rtf);
  std::ifstream f(infName.str(),std::ifstream::in);
  if (!f.is_open())
  {
    err("problems opening rtf file '%s' for reading\n",infName.data());
    return false;
  }
  const int maxLineLength = 10240;
  static QCString lineBuf(maxLineLength);
  // scan until find end of header
  // this is EXTREEEEEEEMLY brittle. It works on OUR rtf
  // files because the first line before the body
  // ALWAYS contains "{\comment begin body}"
  std::string line;
  while (getline(f,line))
  {
    line+='\n';
    if (line.find("\\comment begin body")!=std::string::npos) break;
    if (bIncludeHeader) encodeForOutput(t,line.c_str());
  }
  std::string prevLine;
  bool first=true;
  while (getline(f,line))
  {
    line+='\n';
    size_t pos;
    if ((pos=prevLine.find("INCLUDETEXT \""))!=std::string::npos)
    {
      size_t startNamePos = prevLine.find('"',pos)+1;
      size_t endNamePos = prevLine.find('"',startNamePos);
      std::string fileName = prevLine.substr(startNamePos,endNamePos-startNamePos);
      DBG_RTF(m_t << "{\\comment begin include " << fileName << "}\n")
      if (!preProcessFile(d,fileName.c_str(),t,FALSE)) return FALSE;
      DBG_RTF(m_t << "{\\comment end include " << fileName << "}\n")
    }
    else if (!first) // no INCLUDETEXT on this line
    {
      encodeForOutput(t,prevLine.c_str());
    }
    prevLine = line;
    first=false;
  }
  if (!bIncludeHeader) // skip final '}' in case we don't include headers
  {
    size_t pos = line.rfind('}');
    if (pos==std::string::npos)
    {
      err("Strange, the last char was not a '}'\n");
      pos = line.length();
    }
    encodeForOutput(t,line.substr(0,pos).c_str());
  }
  else
  {
    encodeForOutput(t,line.c_str());
  }
  f.close();
  // remove temporary file
  if (!rtfDebug) d.remove(infName.str());
  return TRUE;
}
testRTFOutput()
void testRTFOutput (const QCString & name)
Tests the integrity of the result by counting brackets.
Definition at line 2218 of file rtfgen.cpp.
{
  int bcount=0;
  int line=1;
  int c;
  std::ifstream f(name.data(),std::ifstream::in);
  if (f.is_open())
  {
    while ((c=f.get())!=-1)
    {
      if (c=='\\') // escape char
      {
        c=f.get();
        if (c==-1) break;
      }
      else if (c=='{') // open bracket
      {
        bcount++;
      }
      else if (c=='}') // close bracket
      {
        bcount--;
        if (bcount<0)
        {
          goto err;
          break;
        }
      }
      else if (c=='\n') // newline
      {
        line++;
      }
    }
  }
  if (bcount==0) return; // file is OK.
err:
  err("RTF integrity test failed at line %d of %s due to a bracket mismatch.\n"
      " Please try to create a small code example that produces this error \n"
      " and send that to doxygen@gmail.com.\n",line,qPrint(name));
}
References c, err(), f, setup::name, and qPrint().