doxygen/src/dia.cpp File Reference
#include `dia.h`
#include `portable.h`
#include `config.h`
#include `message.h`
#include `util.h`
#include `dir.h`
Functions
void writeDiaGraphFromFile (const QCString &inFile, const QCString &outDir, const QCString &outFile, DiaOutputFormat format, const QCString &srcFile, int srcLine)
Variables
static const int maxCmdLine = 40960
Function Documentation
writeDiaGraphFromFile()
void writeDiaGraphFromFile (const QCString & inFile, const QCString & outDir, const QCString & outFile, DiaOutputFormat format, const QCString & srcFile, int srcLine)
Definition at line 26 of file dia.cpp.
{
  QCString absOutFile = outDir;
  absOutFile+=Portable::pathSeparator();
  absOutFile+=outFile;
  // chdir to the output dir, so dot can find the font file.
  std::string oldDir = Dir::currentDirPath();
  // go to the html output directory (i.e. path)
  Dir::setCurrent(outDir.str());
  //printf("Going to dir %s\n",Dir::currentDirPath().c_str());
  QCString diaExe = Config_getString(DIA_PATH)+"dia"+Portable::commandExtension();
  QCString diaArgs;
  QCString extension;
  diaArgs+="-n ";
  if (format==DIA_BITMAP)
  {
    diaArgs+="-t png-libart";
    extension=".png";
  }
  else if (format==DIA_EPS)
  {
    diaArgs+="-t eps";
    extension=".eps";
  }
  diaArgs+=" -e \"";
  diaArgs+=outFile;
  diaArgs+=extension+"\"";
  diaArgs+=" \"";
  diaArgs+=inFile;
  diaArgs+="\"";
  //printf("*** running: %s %s outDir:%s %s\n",qPrint(diaExe),qPrint(diaArgs),outDir,outFile);
  Portable::sysTimerStart();
  if (Portable::system(diaExe,diaArgs,FALSE)!=0)
  {
    err_full(srcFile,srcLine,"Problems running %s. Check your installation or look typos in you dia file %s\n",
        qPrint(diaExe),qPrint(inFile));
    Portable::sysTimerStop();
    goto error;
  }
  Portable::sysTimerStop();
  if ((format==DIA_EPS) && (Config_getBool(USE_PDFLATEX)))
  {
    QCString epstopdfArgs(maxCmdLine);
    epstopdfArgs.sprintf("\"%s.eps\" --outfile=\"%s.pdf\"",
                         qPrint(outFile),qPrint(outFile));
    Portable::sysTimerStart();
    if (Portable::system("epstopdf",epstopdfArgs)!=0)
    {
      err("Problems running epstopdf. Check your TeX installation!\n");
    }
    Portable::sysTimerStop();
  }
error:
  Dir::setCurrent(oldDir);
}
References Portable::commandExtension(), Config_getBool, Config_getString, Dir::currentDirPath(), DIA_BITMAP, DIA_EPS, err(), err_full(), FALSE, maxCmdLine, outFile, Portable::pathSeparator(), qPrint(), Dir::setCurrent(), QCString::sprintf(), QCString::str(), string, Portable::system(), Portable::sysTimerStart(), and Portable::sysTimerStop().
Variable Documentation
maxCmdLine
const int maxCmdLine = 40960 [static]
Definition at line 24 of file dia.cpp.
Referenced by writeDiaGraphFromFile().