doxygen/src/rtfstyle.cpp File Reference
#include <string>
#include <fstream>
#include `rtfstyle.h`
#include `message.h`
#include `regex.h`
Macros
#define RTF_LatexToc(lvl, nest, nxt, pos, twps)
#define RTF_ListBullet(lvl, nest, nxt, pos, lvl2)
#define RTF_ListEnum(lvl, nest, nxt, pos)
#define RTF_CodeExample(lvl, nest, nxt, pos)
#define RTF_ListContinue(lvl, nest, nxt, pos)
#define RTF_DescContinue(lvl, nest, nxt, pos)
Functions
void loadStylesheet (const QCString &name, StyleDataMap &map)
void loadExtensions (const QCString &name)
Variables
QCString rtf_title
QCString rtf_subject
QCString rtf_comments
QCString rtf_company
QCString rtf_logoFilename
QCString rtf_author
QCString rtf_manager
QCString rtf_documentType
QCString rtf_documentId
QCString rtf_keywords
static std::map< std::string, QCString & > g_styleMap
char rtf_Style_Reset [] = `\\pard\\plain `
Rtf_Style_Default rtf_Style_Default []
static const reg::Ex s_clause (R`(\\s(\d+)\s*)`)
StyleDataMap rtf_Style
Macro Definition Documentation
RTF_CodeExample
#define RTF_CodeExample(lvl, nest, nxt, pos)
Value:
  { "CodeExample"#lvl, \
    "\\s"#nest"\\li"#pos"\\widctlpar\\adjustright \\shading1000\\cbpat8 \\f2\\fs16\\cgrid ", \
    "\\sbasedon0 \\snext"#nxt" Code Example "#lvl \
  }
Definition at line 70 of file rtfstyle.cpp.
RTF_DescContinue
#define RTF_DescContinue(lvl, nest, nxt, pos)
Value:
  { "DescContinue"#lvl, \
    "\\s"#nest"\\li"#pos"\\widctlpar\\ql\\adjustright \\fs20\\cgrid ", \
    "\\sbasedon0 \\snext"#nxt" DescContinue "#lvl \
  }
Definition at line 82 of file rtfstyle.cpp.
RTF_LatexToc
#define RTF_LatexToc(lvl, nest, nxt, pos, twps)
Value:
                                                                                                            \
  { "LatexTOC"#lvl, \
    "\\s"#nest"\\li"#pos"\\sa"#twps"\\sb"#twps"\\widctlpar\\tqr\\tldot\\tx8640\\adjustright \\fs20\\cgrid ",\
    "\\sbasedon0 \\snext"#nxt" LatexTOC "#lvl \
  }
Definition at line 51 of file rtfstyle.cpp.
RTF_ListBullet
#define RTF_ListBullet(lvl, nest, nxt, pos, lvl2)
Value:
  { "ListBullet"#lvl, \
    "\\s"#nest"\\fi-360\\li"#pos"\\widctlpar\\jclisttab\\tx"#pos"{\\*\\pn \\pnlvlbody\\ilvl0\\ls"#lvl2"\\pnrnot0\\pndec }\\ls1\\adjustright \\fs20\\cgrid ", \
    "\\sbasedon0 \\snext"#nxt" \\sautoupd List Bullet "#lvl \
  }
Definition at line 58 of file rtfstyle.cpp.
RTF_ListContinue
#define RTF_ListContinue(lvl, nest, nxt, pos)
Value:
  { "ListContinue"#lvl, \
    "\\s"#nest"\\li"#pos"\\sa60\\sb30\\qj\\widctlpar\\qj\\adjustright \\fs20\\cgrid ", \
    "\\sbasedon0 \\snext"#nxt" List Continue "#lvl \
  }
Definition at line 76 of file rtfstyle.cpp.
RTF_ListEnum
#define RTF_ListEnum(lvl, nest, nxt, pos)
Value:
  { "ListEnum"#lvl, \
    "\\s"#nest"\\fi-360\\li"#pos"\\widctlpar\\fs20\\cgrid ", \
    "\\sbasedon0 \\snext"#nxt" \\sautoupd List Enum "#lvl \
  }
Definition at line 64 of file rtfstyle.cpp.
Function Documentation
loadExtensions()
void loadExtensions (const QCString & name)
Definition at line 315 of file rtfstyle.cpp.
{
  std::ifstream file(name.str());
  if (!file.is_open())
  {
    err("Can't open RTF extensions file %s. Using defaults.",qPrint(name));
    return;
  }
  msg("Loading RTF extensions %s...\n",qPrint(name));
  uint lineNr=1;
  for (std::string line ; getline(file,line) ;) // for each line
  {
    if (line.empty() || line[0]=='#') continue; // skip blanks & comments
    static const reg::Ex assignment_splitter(R"(\s*=\s*)");
    reg::Match match;
    if (reg::search(line,match,assignment_splitter))
    {
      std::string key = match.prefix().str();
      std::string value = match.suffix().str();
      auto it = g_styleMap.find(key);
      if (it!=g_styleMap.end())
      {
        it->second = value;
      }
      else
      {
        warn(name,lineNr,"Ignoring unknown extension key '%s'...",key.c_str());
      }
    }
    else
    {
      warn(name,lineNr,"Assignment of style sheet name expected!");
    }
    lineNr++;
  }
}
References err(), caseconvert::file, g_styleMap, reg::match(), msg(), setup::name, qPrint(), reg::search(), string, and warn().
loadStylesheet()
void loadStylesheet (const QCString & name, StyleDataMap & map)
Definition at line 273 of file rtfstyle.cpp.
{
  std::ifstream file(name.str());
  if (!file.is_open())
  {
    err("Can't open RTF style sheet file %s. Using defaults.",qPrint(name));
    return;
  }
  msg("Loading RTF style sheet %s...\n",qPrint(name));
  uint lineNr=1;
  for (std::string line ; getline(file,line) ;) // for each line
  {
    if (line.empty() || line[0]=='#') continue; // skip blanks & comments
    static const reg::Ex assignment_splitter(R"(\s*=\s*)");
    reg::Match match;
    if (reg::search(line,match,assignment_splitter))
    {
      std::string key = match.prefix().str();
      std::string value = match.suffix().str();
      auto it = map.find(key);
      if (it!=map.end())
      {
        StyleData& styleData = it->second;
        styleData.setStyle(value,key);
      }
      else
      {
        warn(name,lineNr,"Unknown style sheet name %s ignored.",key.data());
      }
    }
    else
    {
      warn(name,lineNr,"Assignment of style sheet name expected line='%s'!",line.c_str());
    }
    lineNr++;
  }
}
References err(), caseconvert::file, reg::match(), msg(), setup::name, qPrint(), reg::search(), StyleData::setStyle(), string, and warn().
Variable Documentation
g_styleMap
std::map<std::string,QCString &> g_styleMap [static]
Initial value:
=
{
  { "Title", rtf_title },
  { "Subject", rtf_subject },
  { "Comments", rtf_comments },
  { "Company", rtf_company },
  { "LogoFilename", rtf_logoFilename },
  { "Author", rtf_author },
  { "Manager", rtf_manager },
  { "DocumentType", rtf_documentType },
  { "DocumentId", rtf_documentId },
  { "Keywords", rtf_keywords }
}
Definition at line 34 of file rtfstyle.cpp.
Referenced by loadExtensions().
rtf_author
QCString rtf_author
Definition at line 28 of file rtfstyle.cpp.
rtf_comments
QCString rtf_comments
Definition at line 25 of file rtfstyle.cpp.
rtf_company
QCString rtf_company
Definition at line 26 of file rtfstyle.cpp.
rtf_documentId
QCString rtf_documentId
Definition at line 31 of file rtfstyle.cpp.
rtf_documentType
QCString rtf_documentType
Definition at line 30 of file rtfstyle.cpp.
rtf_keywords
QCString rtf_keywords
Definition at line 32 of file rtfstyle.cpp.
rtf_logoFilename
QCString rtf_logoFilename
Definition at line 27 of file rtfstyle.cpp.
rtf_manager
QCString rtf_manager
Definition at line 29 of file rtfstyle.cpp.
rtf_Style
StyleDataMap rtf_Style
Definition at line 313 of file rtfstyle.cpp.
rtf_Style_Default
Rtf_Style_Default rtf_Style_Default[]
Definition at line 88 of file rtfstyle.cpp.
rtf_Style_Reset
char rtf_Style_Reset[] = `\\pard\\plain `
Definition at line 49 of file rtfstyle.cpp.
rtf_subject
QCString rtf_subject
Definition at line 24 of file rtfstyle.cpp.
rtf_title
QCString rtf_title
Definition at line 23 of file rtfstyle.cpp.
s_clause
const reg::Ex s_clause(R`(\\s(\d+)\s*)`) (R`(\\s(\d+)\s*)`) [static]