doxygen/src/ftvhelp.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <algorithm>
#include `ftvhelp.h`
#include `config.h`
#include `message.h`
#include `doxygen.h`
#include `language.h`
#include `htmlgen.h`
#include `layout.h`
#include `pagedef.h`
#include `docparser.h`
#include `htmldocvisitor.h`
#include `filedef.h`
#include `classdef.h`
#include `util.h`
#include `resourcemgr.h`
Classes
struct FTVNode
struct FTVHelp::Private
struct NavIndexEntry
class NavIndexEntryList
Typedefs
using FTVNodePtr = std::shared_ptr< FTVNode >
using FTVNodeWeakPtr = std::weak_ptr< FTVNode >
using FTVNodes = std::vector< FTVNodePtr >
Functions
static QCString node2URL (const FTVNodePtr &n, bool overruleFile=FALSE, bool srcLink=FALSE)
static QCString generateIndentLabel (const FTVNodePtr &n, int level)
static void generateIndent (TextStream &t, const FTVNodePtr &n, bool opened)
static void generateBriefDoc (TextStream &t, const Definition *def)
static char compoundIcon (const ClassDef *cd)
static QCString pathToNode (const FTVNodePtr &leaf, const FTVNodePtr &n)
static bool dupOfParent (const FTVNodePtr &n)
static void generateJSLink (TextStream &t, const FTVNodePtr &n)
static QCString convertFileId2Var (const QCString &fileId)
static bool generateJSTree (NavIndexEntryList &navIndex, TextStream &t, const FTVNodes &nl, int level, bool &first)
static void generateJSNavTree (const FTVNodes &nodeList)
Variables
static int folderId =1
const char * JAVASCRIPT_LICENSE_TEXT
Typedef Documentation
FTVNodePtr
using FTVNodePtr = std::shared_ptr<FTVNode>
Definition at line 69 of file ftvhelp.cpp.
FTVNodes
using FTVNodes = std::vector<FTVNodePtr>
Definition at line 71 of file ftvhelp.cpp.
FTVNodeWeakPtr
using FTVNodeWeakPtr = std::weak_ptr<FTVNode>
Definition at line 70 of file ftvhelp.cpp.
Function Documentation
compoundIcon()
static char compoundIcon (const ClassDef * cd) [static]
Definition at line 368 of file ftvhelp.cpp.
{
  char icon='C';
  if (cd->getLanguage() == SrcLangExt_Slice)
  {
    if (cd->compoundType()==ClassDef::Interface)
    {
      icon='I';
    }
    else if (cd->compoundType()==ClassDef::Struct)
    {
      icon='S';
    }
    else if (cd->compoundType()==ClassDef::Exception)
    {
      icon='E';
    }
  }
  return icon;
}
References ClassDef::compoundType(), ClassDef::Exception, Definition::getLanguage(), ClassDef::Interface, SrcLangExt_Slice, and ClassDef::Struct.
convertFileId2Var()
static QCString convertFileId2Var (const QCString & fileId) [static]
Definition at line 562 of file ftvhelp.cpp.
{
  QCString varId = fileId;
  int i=varId.findRev('/');
  if (i>=0) varId = varId.mid(i+1);
  return substitute(varId,"-","_");
}
References QCString::findRev(), QCString::mid(), and substitute().
Referenced by generateJSTree().
dupOfParent()
static bool dupOfParent (const FTVNodePtr & n) [static]
Definition at line 539 of file ftvhelp.cpp.
{
  auto parent = n->parent.lock();
  if (!parent) return FALSE;
  if (n->file==parent->file) return TRUE;
  return FALSE;
}
References FALSE, n, parent(), and TRUE.
Referenced by generateJSTree().
generateBriefDoc()
static void generateBriefDoc (TextStream & t, const Definition * def) [static]
Definition at line 346 of file ftvhelp.cpp.
{
  QCString brief = def->briefDescription(TRUE);
  //printf("*** %p: generateBriefDoc(%s)='%s'\n",def,qPrint(def->name()),qPrint(brief));
  if (!brief.isEmpty())
  {
    auto parser { createDocParser() };
    auto ast { validatingParseDoc(*parser.get(),
                                     def->briefFile(),def->briefLine(),
                                     def,0,brief,FALSE,FALSE,
                                     QCString(),TRUE,TRUE,Config_getBool(MARKDOWN_SUPPORT)) };
    const DocNodeAST *astImpl = dynamic_cast<const DocNodeAST*>(ast.get());
    if (astImpl)
    {
      QCString relPath = relativePathToRoot(def->getOutputFileBase());
      HtmlCodeGenerator htmlGen(t,relPath);
      HtmlDocVisitor visitor(t,htmlGen,def);
      std::visit(visitor,astImpl->root);
    }
  }
}
References Definition::briefDescription(), Definition::briefFile(), Definition::briefLine(), Config_getBool, createDocParser(), FALSE, Definition::getOutputFileBase(), QCString::isEmpty(), relativePathToRoot(), DocNodeAST::root, TRUE, and validatingParseDoc().
generateIndent()
static void generateIndent (TextStream & t, const FTVNodePtr & n, bool opened) [static]
Definition at line 281 of file ftvhelp.cpp.
{
  int indent=0;
  auto parent = n->parent.lock();
  while (parent) { indent++; parent=parent->parent.lock(); }
  if (n->isDir)
  {
    QCString dir = opened ? "&#9660;" : "&#9658;";
    t << "<span style=\"width:" << (indent*16) << "px;display:inline-block;\">&#160;</span>"
      << "<span id=\"arr_" << generateIndentLabel(n,0) << "\" class=\"arrow\" ";
    t << "onclick=\"toggleFolder('" << generateIndentLabel(n,0) << "')\"";
    t << ">" << dir
      << "</span>";
  }
  else
  {
    t << "<span style=\"width:" << ((indent+1)*16) << "px;display:inline-block;\">&#160;</span>";
  }
}
References generateIndentLabel(), n, and parent().
generateIndentLabel()
static QCString generateIndentLabel (const FTVNodePtr & n, int level) [static]
Definition at line 269 of file ftvhelp.cpp.
{
  QCString result;
  auto parent = n->parent.lock();
  if (parent)
  {
    result=generateIndentLabel(parent,level+1);
  }
  result+=QCString().setNum(n->index)+"_";
  return result;
}
References generateIndentLabel(), level, n, parent(), and QCString::setNum().
Referenced by generateIndent(), and generateIndentLabel().
generateJSLink()
static void generateJSLink (TextStream & t, const FTVNodePtr & n) [static]
Definition at line 547 of file ftvhelp.cpp.
{
  if (n->file.isEmpty()) // no link
  {
    t << "\"" << convertToJSString(n->name) << "\", null, ";
  }
  else // link into other page
  {
    t << "\"" << convertToJSString(n->name) << "\", \"";
    t << externalRef("",n->ref,TRUE);
    t << node2URL(n);
    t << "\", ";
  }
}
References convertToJSString(), externalRef(), n, node2URL(), and TRUE.
Referenced by generateJSTree().
generateJSNavTree()
static void generateJSNavTree (const FTVNodes & nodeList) [static]
Definition at line 661 of file ftvhelp.cpp.
{
  QCString htmlOutput = Config_getString(HTML_OUTPUT);
  std::ofstream f(htmlOutput.str()+"/navtreedata.js",std::ofstream::out | std::ofstream::binary);
  NavIndexEntryList navIndex;
  if (f.is_open())
  {
    TextStream t(&f);
    //TextStream tidx(&fidx);
    //tidx << "var NAVTREEINDEX =\n";
    //tidx << "{\n";
    t << JAVASCRIPT_LICENSE_TEXT;
    t << "var NAVTREE =\n";
    t << "[\n";
    t << " [ ";
    QCString projName = Config_getString(PROJECT_NAME);
    if (projName.isEmpty())
    {
      if (mainPageHasTitle()) // Use title of main page as root
      {
        t << "\"" << convertToJSString(Doxygen::mainPage->title()) << "\", ";
      }
      else // Use default section title as root
      {
        LayoutNavEntry *lne = LayoutDocManager::instance().rootNavEntry()->find(LayoutNavEntry::MainPage);
        t << "\"" << convertToJSString(lne->title()) << "\", ";
      }
    }
    else // use PROJECT_NAME as root tree element
    {
      t << "\"" << convertToJSString(projName) << "\", ";
    }
    t << "\"index" << Doxygen::htmlFileExtension << "\", ";
    // add special entry for index page
    navIndex.emplace_back("index"+Doxygen::htmlFileExtension,"");
    // related page index is written as a child of index.html, so add this as well
    navIndex.emplace_back("pages"+Doxygen::htmlFileExtension,"");
    bool first=TRUE;
    generateJSTree(navIndex,t,nodeList,1,first);
    if (first)
      t << "]\n";
    else
      t << "\n ] ]\n";
    t << "];\n\n";
    // write the navigation index (and sub-indices)
    std::sort(navIndex.begin(),navIndex.end(),[](const auto &n1,const auto &n2)
        { return !n1.url.isEmpty() && (n2.url.isEmpty() || (n1.url<n2.url)); });
    int subIndex=0;
    int elemCount=0;
    const int maxElemCount=250;
    std::ofstream tsidx(htmlOutput.str()+"/navtreeindex0.js",std::ofstream::out | std::ofstream::binary);
    if (tsidx.is_open())
    {
      t << "var NAVTREEINDEX =\n";
      t << "[\n";
      tsidx << "var NAVTREEINDEX" << subIndex << " =\n";
      tsidx << "{\n";
      first=TRUE;
      auto it = navIndex.begin();
      while (it!=navIndex.end())
      {
        const NavIndexEntry &e = *it;
        if (elemCount==0)
        {
          if (!first)
          {
            t << ",\n";
          }
          else
          {
            first=FALSE;
          }
          t << "\"" << e.url << "\"";
        }
        tsidx << "\"" << e.url << "\":[" << e.path << "]";
        ++it;
        if (it!=navIndex.end() && elemCount<maxElemCount-1) tsidx << ","; // not last entry
        tsidx << "\n";
        elemCount++;
        if (it!=navIndex.end() && elemCount>=maxElemCount) // switch to new sub-index
        {
          tsidx << "};\n";
          elemCount=0;
          tsidx.close();
          subIndex++;
          QCString fileName = htmlOutput+"/navtreeindex"+QCString().setNum(subIndex)+".js";
          tsidx.open(fileName.str(),std::ofstream::out | std::ofstream::binary);
          if (!tsidx.is_open()) break;
          tsidx << "var NAVTREEINDEX" << subIndex << " =\n";
          tsidx << "{\n";
        }
      }
      tsidx << "};\n";
      t << "\n];\n";
    }
    t << "\nvar SYNCONMSG = '" << theTranslator->trPanelSynchronisationTooltip(FALSE) << "';";
    t << "\nvar SYNCOFFMSG = '" << theTranslator->trPanelSynchronisationTooltip(TRUE) << "';";
  }
  ResourceMgr::instance().copyResource("navtree.js",htmlOutput);
}
References Config_getString, convertToJSString(), ResourceMgr::copyResource(), e, f, FALSE, LayoutNavEntry::find(), generateJSTree(), Doxygen::htmlFileExtension, LayoutDocManager::instance(), ResourceMgr::instance(), QCString::isEmpty(), JAVASCRIPT_LICENSE_TEXT, Doxygen::mainPage, LayoutNavEntry::MainPage, mainPageHasTitle(), out, LayoutDocManager::rootNavEntry(), QCString::setNum(), QCString::str(), theTranslator, LayoutNavEntry::title(), Translator::trPanelSynchronisationTooltip(), and TRUE.
generateJSTree()
static bool generateJSTree (NavIndexEntryList & navIndex, TextStream & t, const FTVNodes & nl, int level, bool & first) [static]
Definition at line 570 of file ftvhelp.cpp.
{
  QCString htmlOutput = Config_getString(HTML_OUTPUT);
  QCString indentStr;
  indentStr.fill(' ',level*2);
  bool found=FALSE;
  for (const auto &n : nl)
  {
    // terminate previous entry
    if (!first) t << ",\n";
    first=FALSE;
    // start entry
    if (!found)
    {
      t << "[\n";
    }
    found=TRUE;
    if (n->addToNavIndex) // add entry to the navigation index
    {
      if (n->def && n->def->definitionType()==Definition::TypeFile)
      {
        const FileDef *fd = toFileDef(n->def);
        bool doc,src;
        doc = fileVisibleInIndex(fd,src);
        if (doc)
        {
          navIndex.emplace_back(node2URL(n,TRUE,FALSE),pathToNode(n,n));
        }
        if (src)
        {
          navIndex.emplace_back(node2URL(n,TRUE,TRUE),pathToNode(n,n));
        }
      }
      else
      {
        navIndex.emplace_back(node2URL(n),pathToNode(n,n));
      }
    }
    if (n->separateIndex) // store items in a separate file for dynamic loading
    {
      bool firstChild=TRUE;
      t << indentStr << " [ ";
      generateJSLink(t,n);
      if (!n->children.empty()) // write children to separate file for dynamic loading
      {
        QCString fileId = n->file;
        if (!n->anchor.isEmpty())
        {
          fileId+="_"+n->anchor;
        }
        if (dupOfParent(n))
        {
          fileId+="_dup";
        }
        QCString fileName = htmlOutput+"/"+fileId+".js";
        std::ofstream f(fileName.str(),std::ofstream::out | std::ofstream::binary);
        if (f.is_open())
        {
          TextStream tt(&f);
          tt << "var " << convertFileId2Var(fileId) << " =\n";
          generateJSTree(navIndex,tt,n->children,1,firstChild);
          tt << "\n];";
        }
        f.close();
        t << "\"" << fileId << "\" ]";
      }
      else // no children
      {
        t << "null ]";
      }
    }
    else // show items in this file
    {
      bool firstChild=TRUE;
      t << indentStr << " [ ";
      generateJSLink(t,n);
      bool emptySection = !generateJSTree(navIndex,t,n->children,level+1,firstChild);
      if (emptySection)
        t << "null ]";
      else
        t << "\n" << indentStr << " ] ]";
    }
  }
  return found;
}
References Config_getString, convertFileId2Var(), dupOfParent(), f, FALSE, fileVisibleInIndex(), QCString::fill(), found, generateJSLink(), generateJSTree(), level, n, node2URL(), out, pathToNode(), src, QCString::str(), toFileDef(), TRUE, and Definition::TypeFile.
Referenced by generateJSNavTree(), and generateJSTree().
node2URL()
static QCString node2URL (const FTVNodePtr & n, bool overruleFile = FALSE, bool srcLink = FALSE) [static]
Definition at line 237 of file ftvhelp.cpp.
{
  QCString url = n->file;
  if (!url.isEmpty() && url.at(0)=='!') // relative URL
  {
    // remove leading !
    url = url.mid(1);
  }
  else if (!url.isEmpty() && url.at(0)=='^') // absolute URL
  {
    // skip, keep ^ in the output
  }
  else // local file (with optional anchor)
  {
    if (overruleFile && n->def && n->def->definitionType()==Definition::TypeFile)
    {
      const FileDef *fd = toFileDef(n->def);
      if (srcLink)
      {
        url = fd->getSourceFileBase();
      }
      else
      {
        url = fd->getOutputFileBase();
      }
    }
    url = addHtmlExtensionIfMissing(url);
    if (!n->anchor.isEmpty()) url+="#"+n->anchor;
  }
  return url;
}
References addHtmlExtensionIfMissing(), FileDef::getOutputFileBase(), FileDef::getSourceFileBase(), n, toFileDef(), Definition::TypeFile, and setup::url.
Referenced by generateJSLink(), and generateJSTree().
pathToNode()
static QCString pathToNode (const FTVNodePtr & leaf, const FTVNodePtr & n) [static]
Definition at line 526 of file ftvhelp.cpp.
{
  QCString result;
  auto parent = n->parent.lock();
  if (parent)
  {
    result+=pathToNode(leaf,parent);
  }
  result+=QCString().setNum(n->index);
  if (leaf!=n) result+=",";
  return result;
}
References n, parent(), pathToNode(), and QCString::setNum().
Referenced by generateJSTree(), and pathToNode().
Variable Documentation
folderId
int folderId =1 [static]
Definition at line 40 of file ftvhelp.cpp.
JAVASCRIPT_LICENSE_TEXT
const char* JAVASCRIPT_LICENSE_TEXT
Initial value:
= R"LIC(/*
 @licstart The following is the entire license notice for the JavaScript code in this file.
 The MIT License (MIT)
 Copyright (C) 1997-2020 by Dimitri van Heesch
 Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 and associated documentation files (the "Software"), to deal in the Software without restriction,
 including without limitation the rights to use, copy, modify, merge, publish, distribute,
 sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:
 The above copyright notice and this permission notice shall be included in all copies or
 substantial portions of the Software.
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
 BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 @licend The above is the entire license notice for the JavaScript code in this file
*/
)LIC"
Definition at line 42 of file ftvhelp.cpp.