doxygen/src/commentscan.l File Reference
#include <stdint.h>
#include <map>
#include <stack>
#include <string>
#include <mutex>
#include <functional>
#include <unordered_map>
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <ctype.h>
#include `qcstring.h`
#include `fileinfo.h`
#include `cite.h`
#include `commentscan.h`
#include `condparser.h`
#include `config.h`
#include `debug.h`
#include `docgroup.h`
#include `doxygen.h`
#include `entry.h`
#include `formula.h`
#include `language.h`
#include `message.h`
#include `parserintf.h`
#include `reflist.h`
#include `section.h`
#include `util.h`
#include `doxygen_lex.h`
Classes
struct DocCmdMap
class GuardedSection
struct commentscanYY_state
struct CommentScanner::Private
Macros
#define YY_TYPEDEF_YY_SCANNER_T
#define USE_STATE2STRING 0
#define YY_NO_INPUT 1
#define YY_NO_UNISTD_H 1
#define YY_NEVER_INTERACTIVE 1
#define unput_string(yytext, yyleng) do { for (int i=(int)yyleng-1;i>=0;i--) unput(yytext[i]); } while(0)
#define YY_INPUT(buf, result, max_size) result=yyread(yyscanner,buf,max_size);
Typedefs
typedef yyguts_t * yyscan_t
typedef bool(* DocCmdFunc) (yyscan_t yyscanner, const QCString &name, const StringVector &optList)
Enumerations
enum CommandSpacing {
Invisible
, Inline
, Block
, XRef
,
Invisible
, Inline
, Block
, XRef
 }
enum XRefKind {
XRef_Item
, XRef_Todo
, XRef_Test
, XRef_Bug
,
XRef_Deprecated
, XRef_None
, XRef_Item
, XRef_Todo
,
XRef_Test
, XRef_Bug
, XRef_Deprecated
, XRef_None
 }
enum OutputContext {
OutputDoc
, OutputBrief
, OutputXRef
, OutputInbody
,
OutputDoc
, OutputBrief
, OutputXRef
, OutputInbody
 }
enum GuardType {
Guard_If
, Guard_IfNot
, Guard_Skip
, Guard_If
,
Guard_IfNot
, Guard_Skip
 }
Functions
static bool handleBrief (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleFn (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleDef (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleOverload (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleEnum (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleDefGroup (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleAddToGroup (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleWeakGroup (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleNamespace (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handlePackage (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleConcept (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleClass (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleHeaderFile (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleProtocol (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleCategory (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleUnion (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleStruct (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleInterface (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleIdlException (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handlePage (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleMainpage (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleFile (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleDir (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleExample (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleDetails (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleRaiseWarning (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleNoop (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleName (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleTodo (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleTest (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleBug (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleSubpage (yyscan_t yyscanner, const QCString &s, const StringVector &)
static bool handleDeprecated (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleXRefItem (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleRelated (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleRelatedAlso (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleMemberOf (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleRefItem (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleSection (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleAnchor (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleImage (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleCite (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleFormatBlock (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleAddIndex (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleIf (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleIfNot (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleElseIf (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleElse (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleEndIf (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleIngroup (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleNoSubGrouping (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleShowInitializer (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleHideInitializer (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleCallgraph (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleHideCallgraph (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleCallergraph (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleHideCallergraph (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleReferencedByRelation (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleHideReferencedByRelation (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleReferencesRelation (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleHideReferencesRelation (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleInternal (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleStatic (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handlePure (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handlePrivate (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handlePrivateSection (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleProtected (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleProtectedSection (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handlePublic (yyscan_t yyscanner, const QCString &s, const StringVector &)
static bool handlePublicSection (yyscan_t yyscanner, const QCString &s, const StringVector &)
static bool handleToc (yyscan_t yyscanner, const QCString &s, const StringVector &)
static bool handleInherit (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleExtends (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleCopyDoc (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleCopyBrief (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleCopyDetails (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleParBlock (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleEndParBlock (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleParam (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleRetval (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleFileInfo (yyscan_t yyscanner, const QCString &, const StringVector &)
static bool handleLineInfo (yyscan_t yyscanner, const QCString &, const StringVector &)
static QCString stripQuotes (const char *s)
static bool getDocSectionName (int s)
static SectionType sectionLevelToType (int level)
static void stripTrailingWhiteSpace (QCString &s)
static void initParser (yyscan_t yyscanner)
static bool makeStructuralIndicator (yyscan_t yyscanner, Entry::Sections s)
static void lineCount (yyscan_t yyscanner)
static void addXRefItem (yyscan_t yyscanner, const QCString &listName, const QCString &itemTitle, const QCString &listTitle, bool append)
static QCString addFormula (yyscan_t yyscanner)
static void checkFormula (yyscan_t yyscanner)
static void addSection (yyscan_t yyscanner)
static void setOutput (yyscan_t yyscanner, OutputContext ctx)
static void addAnchor (yyscan_t yyscanner, const QCString &anchor)
static void addOutput (yyscan_t yyscanner, const char *s)
static void addOutput (yyscan_t yyscanner, const QCString &s)
static void addOutput (yyscan_t yyscanner, char c)
static void endBrief (yyscan_t yyscanner, bool addToOutput=TRUE)
static void handleGuard (yyscan_t yyscanner, const QCString &expr)
static int yyread (yyscan_t yyscanner, char *buf, int max_size)
static void addCite (yyscan_t yyscanner)
static void addIline (yyscan_t yyscanner, int lineNr)
static void addIlineBreak (yyscan_t yyscanner, int lineNr)
static const char * getLexerFILE ()
int yylex (yyscan_t yyscanner)
Variables
static const std::map< std::string, DocCmdMap > docCmdMap
static std::mutex g_sectionMutex
static std::mutex g_formulaMutex
static std::mutex g_citeMutex
Macro Definition Documentation
unput_string
#define unput_string(yytext, yyleng) do { for (int i=(int)yyleng-1;i>=0;i--) unput(yytext[i]); } while(0)
Definition at line 469 of file commentscan.l.
USE_STATE2STRING
#define USE_STATE2STRING 0
Definition at line 65 of file commentscan.l.
YY_INPUT
#define YY_INPUT(buf, result, max_size) result=yyread(yyscanner,buf,max_size);
Definition at line 474 of file commentscan.l.
YY_NEVER_INTERACTIVE
#define YY_NEVER_INTERACTIVE 1
Definition at line 326 of file commentscan.l.
YY_NO_INPUT
#define YY_NO_INPUT 1
Definition at line 324 of file commentscan.l.
YY_NO_UNISTD_H
#define YY_NO_UNISTD_H 1
Definition at line 325 of file commentscan.l.
YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
Definition at line 23 of file commentscan.l.
Typedef Documentation
DocCmdFunc
typedef bool(* DocCmdFunc) (yyscan_t yyscanner, const QCString &name, const StringVector &optList)
Definition at line 155 of file commentscan.l.
yyscan_t
typedef yyguts_t* yyscan_t
Definition at line 25 of file commentscan.l.
Enumeration Type Documentation
CommandSpacing
enum CommandSpacing [strong]
Enumerator
Invisible
Inline
Block
XRef
Invisible
Inline
Block
XRef
Definition at line 157 of file commentscan.l.
{
  Invisible, // command sets some property but does not appear in the output.
  Inline, // command appears inline in the output which can be a brief description.
  Block, // command starts a new paragraphs / ends a brief description.
  XRef // command is a cross reference (todo, bug, test, xrefitem).
};
GuardType
enum GuardType
Enumerator
Guard_If
Guard_IfNot
Guard_Skip
Guard_If
Guard_IfNot
Guard_Skip
Definition at line 347 of file commentscan.l.
{
  Guard_If,
  Guard_IfNot,
  Guard_Skip
};
OutputContext
enum OutputContext
Enumerator
OutputDoc
OutputBrief
OutputXRef
OutputInbody
OutputDoc
OutputBrief
OutputXRef
OutputInbody
Definition at line 339 of file commentscan.l.
{
  OutputDoc,
  OutputBrief,
  OutputXRef,
  OutputInbody
};
XRefKind
enum XRefKind
Enumerator
XRef_Item
XRef_Todo
XRef_Test
XRef_Bug
XRef_Deprecated
XRef_None
XRef_Item
XRef_Todo
XRef_Test
XRef_Bug
XRef_Deprecated
XRef_None
Definition at line 329 of file commentscan.l.
{
  XRef_Item,
  XRef_Todo,
  XRef_Test,
  XRef_Bug,
  XRef_Deprecated,
  XRef_None
};
Function Documentation
addAnchor()
static void addAnchor (yyscan_t yyscanner, const QCString & anchor) [static]
Definition at line 3521 of file commentscan.l.
{
  std::unique_lock<std::mutex> lock(g_sectionMutex);
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  SectionManager &sm = SectionManager::instance();
  const SectionInfo *si = sm.find(anchor);
  if (si)
  {
    if (!si->ref().isEmpty()) // we are from a tag file
    {
      si = sm.replace(anchor,yyextra->fileName,yyextra->lineNr,QCString(),SectionType::Anchor,0);
      yyextra->current->anchors.push_back(si);
    }
    else if (si->lineNr() != -1)
    {
      warn(yyextra->fileName,yyextra->lineNr,
          "multiple use of section label '%s' while adding anchor, (first occurrence: %s, line %d)",
          qPrint(anchor),qPrint(si->fileName()),si->lineNr());
    }
    else
    {
      warn(yyextra->fileName,yyextra->lineNr,"multiple use of section label '%s' while adding anchor, (first occurrence: %s)",
          qPrint(anchor),qPrint(si->fileName()));
    }
  }
  else
  {
    si = sm.add(anchor,yyextra->fileName,yyextra->lineNr,QCString(),SectionType::Anchor,0);
    yyextra->current->anchors.push_back(si);
  }
}
References SectionManager::add(), Anchor, SectionInfo::fileName(), LinkedMap< T, Hash, KeyEqual, Map >::find(), g_sectionMutex, SectionManager::instance(), QCString::isEmpty(), SectionInfo::lineNr(), qPrint(), SectionInfo::ref(), SectionManager::replace(), and warn().
Referenced by handleImage().
addCite()
static void addCite (yyscan_t yyscanner) [static]
Definition at line 3351 of file commentscan.l.
{
  std::unique_lock<std::mutex> lock(g_citeMutex);
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  QCString name(yytext);
  if (yytext[0] =='"')
  {
    name=yytext+1;
    name=name.left((int)yyleng-2);
  }
  CitationManager::instance().insert(name);
}
References g_citeMutex, CitationManager::insert(), CitationManager::instance(), and setup::name.
addFormula()
static QCString addFormula (yyscan_t yyscanner) [static]
Definition at line 3285 of file commentscan.l.
{
  std::unique_lock<std::mutex> lock(g_formulaMutex);
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  QCString formLabel;
  int id = FormulaManager::instance().addFormula(yyextra->formulaText.str());
  formLabel.sprintf("\\_form#%d",id);
  for (int i=0;i<yyextra->formulaNewLines;i++) formLabel+="@_fakenl"; // add fake newlines to
                                                         // keep the warnings
                                                         // correctly aligned.
  return formLabel;
}
References FormulaManager::addFormula(), g_formulaMutex, FormulaManager::instance(), and QCString::sprintf().
addIline()
static void addIline (yyscan_t yyscanner, int lineNr) [static]
Definition at line 3576 of file commentscan.l.
{
  char cmd[20];
  sprintf(cmd,"\\iline %d ",lineNr);
  addOutput(yyscanner, cmd);
}
References addOutput().
Referenced by endBrief().
addIlineBreak()
static void addIlineBreak (yyscan_t yyscanner, int lineNr) [static]
Definition at line 3583 of file commentscan.l.
{
  char cmd[30];
  sprintf(cmd,"\\iline %d \\ilinebr ",lineNr);
  addOutput(yyscanner, cmd);
}
References addOutput().
addOutput() [1/3]
static void addOutput (yyscan_t yyscanner, char c) [inline], [static]
Definition at line 3570 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  *yyextra->pOutputString+=c;
}
References c.
addOutput() [2/3]
static void addOutput (yyscan_t yyscanner, const char * s) [inline], [static]
Definition at line 3554 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  //printf("addOutput(yyscanner,%s)\n",s);
  *yyextra->pOutputString+=s;
}
References s.
Referenced by addIline(), addIlineBreak(), endBrief(), handleAddIndex(), handleAnchor(), handleCite(), handleCopyBrief(), handleCopyDetails(), handleCopyDoc(), handleDetails(), handleEndIf(), handleEndParBlock(), handleFileInfo(), handleFormatBlock(), handleImage(), handleInternal(), handleLineInfo(), handleParam(), handleParBlock(), handleRefItem(), handleRetval(), handleSection(), and handleSubpage().
addOutput() [3/3]
static void addOutput (yyscan_t yyscanner, const QCString & s) [inline], [static]
Definition at line 3562 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  //printf("addOutput(yyscanner,%s)\n",s);
  *yyextra->pOutputString+=s;
}
References s.
addSection()
static void addSection (yyscan_t yyscanner) [static]
Definition at line 3306 of file commentscan.l.
{
  std::unique_lock<std::mutex> lock(g_sectionMutex);
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  SectionManager &sm = SectionManager::instance();
  const SectionInfo *si = sm.find(yyextra->sectionLabel);
  if (si)
  {
    if (!si->ref().isEmpty()) // we are from a tag file
    {
      // create a new section element
      yyextra->sectionTitle+=yytext;
      yyextra->sectionTitle=yyextra->sectionTitle.stripWhiteSpace();
      si = sm.replace(yyextra->sectionLabel,yyextra->fileName,yyextra->lineNr,
                      yyextra->sectionTitle,sectionLevelToType(yyextra->sectionLevel),
                      yyextra->sectionLevel);
      // add section to this entry
      yyextra->current->anchors.push_back(si);
    }
    else if (si->lineNr() != -1)
    {
      warn(yyextra->fileName,yyextra->lineNr,"multiple use of section label '%s' while adding section, (first occurrence: %s, line %d)",qPrint(yyextra->sectionLabel),qPrint(si->fileName()),si->lineNr());
    }
    else
    {
      warn(yyextra->fileName,yyextra->lineNr,"multiple use of section label '%s' while adding section, (first occurrence: %s)",qPrint(yyextra->sectionLabel),qPrint(si->fileName()));
    }
  }
  else
  {
    // create a new section element
    yyextra->sectionTitle+=yytext;
    yyextra->sectionTitle=yyextra->sectionTitle.stripWhiteSpace();
    si = sm.add(yyextra->sectionLabel,yyextra->fileName,yyextra->lineNr,
                yyextra->sectionTitle,sectionLevelToType(yyextra->sectionLevel),
                yyextra->sectionLevel);
    // add section to this entry
    yyextra->current->anchors.push_back(si);
  }
}
References SectionManager::add(), SectionInfo::fileName(), LinkedMap< T, Hash, KeyEqual, Map >::find(), g_sectionMutex, SectionManager::instance(), QCString::isEmpty(), SectionInfo::lineNr(), qPrint(), SectionInfo::ref(), SectionManager::replace(), sectionLevelToType(), and warn().
addXRefItem()
static void addXRefItem (yyscan_t yyscanner, const QCString & listName, const QCString & itemTitle, const QCString & listTitle, bool append) [static]
Definition at line 3197 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  if (listName.isEmpty()) return;
  //printf("addXRefItem(%s,%s,%s,%d)\n",listName,itemTitle,listTitle,append);
  std::unique_lock<std::mutex> lock(g_sectionMutex);
  RefList *refList = RefListManager::instance().add(listName,listTitle,itemTitle);
  RefItem *item = 0;
  for (auto it = yyextra->current->sli.rbegin(); it != yyextra->current->sli.rend(); ++it)
  {
    RefItem *i = *it;
    if (i && i->list()->listName()==listName)
    {
      //printf("found %s lii->type=%s\n",listName,qPrint(i->list()->listName()));
      item = i;
      break;
    }
  }
  if (item && append) // already found item of same type just before this one
  {
    //printf("listName=%s item id = %d existing\n",listName,item->id());
    item->setText(item->text() + " <p>" + yyextra->outputXRef);
    //printf("%s: text +=%s\n",listName,qPrint(item->text));
  }
  else // new item
  {
    // if we have already an item from the same list type (e.g. a second @todo)
    // in the same Entry (i.e. lii!=0) then we reuse its link anchor.
    item = refList->add();
    //printf("listName=%s item id = %d new yyextra->current=%p\n",listName,item->id(),yyextra->current);
    QCString anchorLabel;
    anchorLabel.sprintf("_%s%06d",listName.data(),item->id());
    item->setText(yyextra->outputXRef);
    item->setAnchor(anchorLabel);
    yyextra->current->sli.push_back(item);
    QCString cmdString;
    cmdString.sprintf(" \\xrefitem %s %d.",qPrint(listName),item->id());
    if (yyextra->inBody)
    {
      yyextra->current->inbodyDocs += cmdString;
    }
    else
    {
      yyextra->current->doc += cmdString;
    }
    {
      SectionManager &sm = SectionManager::instance();
      const SectionInfo *si = sm.find(anchorLabel);
      if (si)
      {
        if (!si->ref().isEmpty()) // we are from a tag file
        {
          si = sm.replace(anchorLabel,listName,yyextra->lineNr,
              yyextra->sectionTitle,SectionType::Anchor,
              yyextra->sectionLevel);
          yyextra->current->anchors.push_back(si);
        }
        else if (si->lineNr() != -1)
        {
          warn(listName,yyextra->lineNr,"multiple use of section label '%s', (first occurrence: %s, line %d)",qPrint(anchorLabel),qPrint(si->fileName()),si->lineNr());
        }
        else
        {
          warn(listName,yyextra->lineNr,"multiple use of section label '%s', (first occurrence: %s)",qPrint(anchorLabel),qPrint(si->fileName()));
        }
      }
      else
      {
        si = sm.add(anchorLabel,listName,yyextra->lineNr,
            yyextra->sectionTitle,SectionType::Anchor,
            yyextra->sectionLevel);
        yyextra->current->anchors.push_back(si);
      }
    }
  }
  yyextra->outputXRef.resize(0);
}
References RefList::add(), LinkedMap< T, Hash, KeyEqual, Map >::add(), SectionManager::add(), Anchor, QCString::data(), SectionInfo::fileName(), LinkedMap< T, Hash, KeyEqual, Map >::find(), g_sectionMutex, RefItem::id(), RefListManager::instance(), SectionManager::instance(), QCString::isEmpty(), SectionInfo::lineNr(), RefItem::list(), RefList::listName(), qPrint(), SectionInfo::ref(), SectionManager::replace(), RefItem::setAnchor(), RefItem::setText(), QCString::sprintf(), RefItem::text(), and warn().
Referenced by setOutput().
checkFormula()
static void checkFormula (yyscan_t yyscanner) [static]
Definition at line 3626 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  if (YY_START==ReadFormulaShort || YY_START==ReadFormulaRound || YY_START==ReadFormulaLong)
  {
    warn(yyextra->fileName,yyextra->lineNr,"End of comment block while inside formula.");
  }
}
References warn().
endBrief()
static void endBrief (yyscan_t yyscanner, bool addToOutput = TRUE) [static]
Definition at line 3590 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  if (!yyextra->current->brief.stripWhiteSpace().isEmpty())
  { // only go to the detailed description if we have
    // found some brief description and not just whitespace
    yyextra->briefEndsAtDot=FALSE;
    setOutput(yyscanner,OutputDoc);
    addIline(yyscanner,yyextra->lineNr);
    if (addToOutput) addOutput(yyscanner,yytext);
  }
  else
  {
    int saveLineNr = yyextra->lineNr;
    lineCount(yyscanner);
    yyextra->current->briefLine = yyextra->lineNr;
    yyextra->lineNr = saveLineNr;
  }
}
References addIline(), addOutput(), FALSE, lineCount(), OutputDoc, and setOutput().
getDocSectionName()
static bool getDocSectionName (int s) [static]
Definition at line 3120 of file commentscan.l.
{
  switch(s)
  {
    case Entry::CLASSDOC_SEC:
    case Entry::STRUCTDOC_SEC:
    case Entry::UNIONDOC_SEC:
    case Entry::EXCEPTIONDOC_SEC:
    case Entry::NAMESPACEDOC_SEC:
    case Entry::PROTOCOLDOC_SEC:
    case Entry::CATEGORYDOC_SEC:
    case Entry::ENUMDOC_SEC:
    case Entry::PAGEDOC_SEC:
    case Entry::VARIABLEDOC_SEC:
    case Entry::MEMBERDOC_SEC:
    case Entry::OVERLOADDOC_SEC:
    case Entry::FILEDOC_SEC:
    case Entry::DEFINEDOC_SEC:
    case Entry::GROUPDOC_SEC:
    case Entry::MAINPAGEDOC_SEC:
    case Entry::PACKAGEDOC_SEC:
    case Entry::DIRDOC_SEC:
    case Entry::EXAMPLE_SEC:
    case Entry::MEMBERGRP_SEC:
    case Entry::CONCEPTDOC_SEC:
      return TRUE;
    default:
      return FALSE;
  }
}
References Entry::CATEGORYDOC_SEC, Entry::CLASSDOC_SEC, Entry::CONCEPTDOC_SEC, Entry::DEFINEDOC_SEC, Entry::DIRDOC_SEC, Entry::ENUMDOC_SEC, Entry::EXAMPLE_SEC, Entry::EXCEPTIONDOC_SEC, FALSE, Entry::FILEDOC_SEC, Entry::GROUPDOC_SEC, Entry::MAINPAGEDOC_SEC, Entry::MEMBERDOC_SEC, Entry::MEMBERGRP_SEC, Entry::NAMESPACEDOC_SEC, Entry::OVERLOADDOC_SEC, Entry::PACKAGEDOC_SEC, Entry::PAGEDOC_SEC, Entry::PROTOCOLDOC_SEC, s, Entry::STRUCTDOC_SEC, TRUE, Entry::UNIONDOC_SEC, and Entry::VARIABLEDOC_SEC.
Referenced by makeStructuralIndicator().
getLexerFILE()
static const char * getLexerFILE () [inline], [static]
Definition at line 477 of file commentscan.l.
{return __FILE__;}
handleAddIndex()
static bool handleAddIndex (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2664 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  addOutput(yyscanner,"@addindex ");
  BEGIN(LineParam);
  return FALSE;
}
References addOutput(), and FALSE.
handleAddToGroup()
static bool handleAddToGroup (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2197 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  bool stop=makeStructuralIndicator(yyscanner,Entry::GROUPDOC_SEC);
  yyextra->current->groupDocType = Entry::GROUPDOC_ADD;
  BEGIN(GroupDocArg1);
  return stop;
}
References Entry::GROUPDOC_ADD, Entry::GROUPDOC_SEC, and makeStructuralIndicator().
handleAnchor()
static bool handleAnchor (yyscan_t yyscanner, const QCString & s, const StringVector &) [static]
Definition at line 2595 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  addOutput(yyscanner,"@"+s+" ");
  BEGIN(AnchorLabel);
  return FALSE;
}
References addOutput(), FALSE, and s.
handleBrief()
static bool handleBrief (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2146 of file commentscan.l.
{
  //printf("handleBrief\n");
  setOutput(yyscanner,OutputBrief);
  return FALSE;
}
References FALSE, OutputBrief, and setOutput().
handleBug()
static bool handleBug (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2453 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->newXRefKind = XRef_Bug;
  setOutput(yyscanner,OutputXRef);
  yyextra->xrefKind = XRef_Bug;
  return FALSE;
}
References FALSE, OutputXRef, setOutput(), and XRef_Bug.
handleCallergraph()
static bool handleCallergraph (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2860 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->current->callerGraph = TRUE; // ON
  return FALSE;
}
References FALSE, and TRUE.
handleCallgraph()
static bool handleCallgraph (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2846 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->current->callGraph = TRUE; // ON
  return FALSE;
}
References FALSE, and TRUE.
handleCategory()
static bool handleCategory (yyscan_t yyscanner, const QCString & cmd, const StringVector &) [static]
Definition at line 2265 of file commentscan.l.
{ // Obj-C category
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  bool stop=makeStructuralIndicator(yyscanner,Entry::CATEGORYDOC_SEC);
  yyextra->currentCmd = cmd;
  BEGIN(CategoryDocArg1);
  return stop;
}
References Entry::CATEGORYDOC_SEC, and makeStructuralIndicator().
handleCite()
static bool handleCite (yyscan_t yyscanner, const QCString & s, const StringVector &) [static]
Definition at line 2628 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  if (!yyextra->spaceBeforeCmd.isEmpty())
  {
    addOutput(yyscanner,yyextra->spaceBeforeCmd);
    yyextra->spaceBeforeCmd.resize(0);
  }
  addOutput(yyscanner,"@"+s+" ");
  BEGIN(CiteLabel);
  return FALSE;
}
References addOutput(), FALSE, and s.
handleClass()
static bool handleClass (yyscan_t yyscanner, const QCString & cmd, const StringVector &) [static]
Definition at line 2231 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  bool stop=makeStructuralIndicator(yyscanner,Entry::CLASSDOC_SEC);
  yyextra->currentCmd = cmd;
  BEGIN(ClassDocArg1);
  return stop;
}
References Entry::CLASSDOC_SEC, and makeStructuralIndicator().
handleConcept()
static bool handleConcept (yyscan_t yyscanner, const QCString & cmd, const StringVector &) [static]
Definition at line 2240 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  bool stop=makeStructuralIndicator(yyscanner,Entry::CONCEPTDOC_SEC);
  yyextra->currentCmd = cmd;
  BEGIN(ConceptDocArg1);
  return stop;
}
References Entry::CONCEPTDOC_SEC, and makeStructuralIndicator().
handleCopyBrief()
static bool handleCopyBrief (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 3056 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  if (yyextra->current->brief.isEmpty() && yyextra->current->doc.isEmpty())
  { // if we don't have a brief or detailed description yet,
    // then the @copybrief should end up in the brief description.
    // otherwise it will be copied inline (see bug691315 & bug700788)
    setOutput(yyscanner,OutputBrief);
  }
  if (!yyextra->spaceBeforeCmd.isEmpty())
  {
    addOutput(yyscanner,yyextra->spaceBeforeCmd);
    yyextra->spaceBeforeCmd.resize(0);
  }
  addOutput(yyscanner,"\\copybrief ");
  return FALSE;
}
References addOutput(), FALSE, OutputBrief, and setOutput().
handleCopyDetails()
static bool handleCopyDetails (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 3074 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  setOutput(yyscanner,OutputDoc);
  if (!yyextra->spaceBeforeCmd.isEmpty())
  {
    addOutput(yyscanner,yyextra->spaceBeforeCmd);
    yyextra->spaceBeforeCmd.resize(0);
  }
  addOutput(yyscanner,"\\copydetails ");
  return FALSE;
}
References addOutput(), FALSE, OutputDoc, and setOutput().
handleCopyDoc()
static bool handleCopyDoc (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 3087 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  if (yyextra->current->brief.isEmpty() && yyextra->current->doc.isEmpty())
  { // if we don't have a brief or detailed description yet,
    // then the @copybrief should end up in the brief description.
    // otherwise it will be copied inline (see bug691315 & bug700788)
    setOutput(yyscanner,OutputBrief);
  }
  if (!yyextra->spaceBeforeCmd.isEmpty())
  {
    addOutput(yyscanner,yyextra->spaceBeforeCmd);
    yyextra->spaceBeforeCmd.resize(0);
  }
  addOutput(yyscanner,"\\copybrief ");
  yyextra->copyDocArg.resize(0);
  yyextra->braceCount = 0;
  BEGIN(CopyDoc);
  return FALSE;
}
References addOutput(), FALSE, OutputBrief, and setOutput().
handleDef()
static bool handleDef (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2163 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  bool stop=makeStructuralIndicator(yyscanner,Entry::DEFINEDOC_SEC);
  yyextra->functionProto.resize(0);
  BEGIN(FnParam);
  return stop;
}
References Entry::DEFINEDOC_SEC, and makeStructuralIndicator().
handleDefGroup()
static bool handleDefGroup (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2188 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  bool stop=makeStructuralIndicator(yyscanner,Entry::GROUPDOC_SEC);
  yyextra->current->groupDocType = Entry::GROUPDOC_NORMAL;
  BEGIN(GroupDocArg1);
  return stop;
}
References Entry::GROUPDOC_NORMAL, Entry::GROUPDOC_SEC, and makeStructuralIndicator().
handleDeprecated()
static bool handleDeprecated (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2462 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->newXRefKind = XRef_Deprecated;
  setOutput(yyscanner,OutputXRef);
  yyextra->xrefKind = XRef_Deprecated;
  return FALSE;
}
References FALSE, OutputXRef, setOutput(), and XRef_Deprecated.
handleDetails()
static bool handleDetails (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2392 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  if (yyextra->inContext!=OutputBrief)
  {
    addOutput(yyscanner,"\\ilinebr\\ilinebr "); // treat @details outside brief description
                                                // as a new paragraph
  }
  setOutput(yyscanner,OutputDoc);
  return FALSE;
}
References addOutput(), FALSE, OutputBrief, OutputDoc, and setOutput().
handleDir()
static bool handleDir (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2361 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  bool stop=makeStructuralIndicator(yyscanner,Entry::DIRDOC_SEC);
  if (!stop) yyextra->current->name = yyextra->fileName;
  BEGIN(FileDocArg1);
  return stop;
}
References Entry::DIRDOC_SEC, and makeStructuralIndicator().
handleElse()
static bool handleElse (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2779 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  if (yyextra->guards.empty())
  {
    warn(yyextra->fileName,yyextra->lineNr,
        "found \\else without matching start command");
  }
  else
  {
    yyextra->spaceBeforeIf = yyextra->spaceBeforeCmd;
    BEGIN(SkipGuardedSection);
  }
  return FALSE;
}
References FALSE, and warn().
handleElseIf()
static bool handleElseIf (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2762 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  if (yyextra->guards.empty())
  {
    warn(yyextra->fileName,yyextra->lineNr,
        "found \\else without matching start command");
  }
  else
  {
    yyextra->guardType = yyextra->enabledSectionFound ? Guard_Skip : Guard_If;
    yyextra->spaceBeforeIf = yyextra->spaceBeforeCmd;
    BEGIN(GuardParam);
  }
  return FALSE;
}
References FALSE, Guard_If, Guard_Skip, and warn().
handleEndIf()
static bool handleEndIf (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2795 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  if (yyextra->guards.empty())
  {
    warn(yyextra->fileName,yyextra->lineNr,
        "found \\endif without matching start command");
  }
  else
  {
    yyextra->guards.pop();
  }
  yyextra->enabledSectionFound=FALSE;
  if (!yyextra->spaceBeforeCmd.isEmpty())
  {
    addOutput(yyscanner,yyextra->spaceBeforeCmd);
    yyextra->spaceBeforeCmd.resize(0);
  }
  BEGIN(GuardParamEnd);
  return FALSE;
}
References addOutput(), FALSE, and warn().
handleEndParBlock()
static bool handleEndParBlock (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2497 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  if (!yyextra->insideParBlock)
  {
    warn(yyextra->fileName,yyextra->lineNr,
        "found \\endparblock command without matching \\parblock!");
  }
  addOutput(yyscanner,"@endparblock");
  setOutput(yyscanner,OutputDoc); // to end a parblock inside a xrefitem like context
  yyextra->insideParBlock = FALSE;
  return FALSE;
}
References addOutput(), FALSE, OutputDoc, setOutput(), and warn().
handleEnum()
static bool handleEnum (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2180 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  bool stop=makeStructuralIndicator(yyscanner,Entry::ENUMDOC_SEC);
  BEGIN(EnumDocArg1);
  return stop;
}
References Entry::ENUMDOC_SEC, and makeStructuralIndicator().
handleExample()
static bool handleExample (yyscan_t yyscanner, const QCString & cmd, const StringVector & optList) [static]
Definition at line 2370 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  Entry::Sections section=Entry::EXAMPLE_SEC;
  for (const auto &opt : optList)
  {
    if (opt=="lineno")
    {
      section=Entry::EXAMPLE_LINENO_SEC;
    }
    else
    {
      warn(yyextra->fileName,yyextra->lineNr,
          "unsupported option '%s' for command '\\%s'",opt.c_str(),qPrint(cmd));
    }
  }
  bool stop=makeStructuralIndicator(yyscanner,section);
  if (!stop) yyextra->current->name = yyextra->fileName;
  BEGIN(FileDocArg1);
  return stop;
}
References Entry::EXAMPLE_LINENO_SEC, Entry::EXAMPLE_SEC, makeStructuralIndicator(), qPrint(), and warn().
handleExtends()
static bool handleExtends (yyscan_t yyscanner, const QCString & cmd, const StringVector &) [static]
Definition at line 3048 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->currentCmd = cmd;
  BEGIN(ExtendsParam);
  return FALSE;
}
References FALSE.
handleFile()
static bool handleFile (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2331 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  bool stop=makeStructuralIndicator(yyscanner,Entry::FILEDOC_SEC);
  if (!stop)
  {
    yyextra->current->name = yyextra->fileName;
  }
  BEGIN(FileDocArg1);
  return stop;
}
References Entry::FILEDOC_SEC, and makeStructuralIndicator().
handleFileInfo()
static bool handleFileInfo (yyscan_t yyscanner, const QCString & , const StringVector & optList) [static]
Definition at line 2672 of file commentscan.l.
{
  using OutputWriter = std::function<void(yyscan_t,FileInfo &)>;
  static std::unordered_map<std::string,OutputWriter> options =
  { // name, writer
    { "name", [](yyscan_t s,FileInfo &fi) { addOutput(s,fi.baseName()); } },
    { "extension", [](yyscan_t s,FileInfo &fi) { addOutput(s,fi.extension(true)); } },
    { "filename", [](yyscan_t s,FileInfo &fi) { addOutput(s,fi.fileName()); } },
    { "directory", [](yyscan_t s,FileInfo &fi) { addOutput(s,fi.dirPath()); } },
    { "full", [](yyscan_t s,FileInfo &fi) { addOutput(s,fi.absFilePath()); } },
  };
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  if (!yyextra->spaceBeforeCmd.isEmpty())
  {
    addOutput(yyscanner,yyextra->spaceBeforeCmd);
    yyextra->spaceBeforeCmd.resize(0);
  }
  bool first = true;
  FileInfo fi(yyextra->fileName.str());
  for (const auto &opt_ : optList)
  {
    QCString optStripped = QCString(opt_).stripWhiteSpace();
    std::string opt = optStripped.lower().str();
    auto it = options.find(opt);
    if (it != options.end())
    {
      if (!first)
      {
        warn(yyextra->fileName,yyextra->lineNr,"Multiple options specified with \\fileinfo, discarding '%s'", qPrint(optStripped));
      }
      else
      {
        it->second(yyscanner,fi);
      }
      first = false;
    }
    else
    {
      warn(yyextra->fileName,yyextra->lineNr,"Unknown option specified with \\fileinfo: '%s'", qPrint(optStripped));
    }
  }
  if (first) // no options specified
  {
    if (Config_getBool(FULL_PATH_NAMES))
    {
      addOutput(yyscanner,stripFromPath(yyextra->fileName));
    }
    else
    {
      addOutput(yyscanner,yyextra->fileName);
    }
  }
  addOutput(yyscanner," ");
  return FALSE;
}
References addOutput(), Config_getBool, FALSE, function(), QCString::lower(), qPrint(), s, QCString::str(), string, stripFromPath(), QCString::stripWhiteSpace(), and warn().
handleFn()
static bool handleFn (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2153 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  bool stop=makeStructuralIndicator(yyscanner,Entry::MEMBERDOC_SEC);
  yyextra->functionProto.resize(0);
  yyextra->braceCount=0;
  BEGIN(FnParam);
  return stop;
}
References makeStructuralIndicator(), and Entry::MEMBERDOC_SEC.
handleFormatBlock()
static bool handleFormatBlock (yyscan_t yyscanner, const QCString & s, const StringVector & optList) [static]
Definition at line 2641 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  if (!yyextra->spaceBeforeCmd.isEmpty())
  {
    addOutput(yyscanner,yyextra->spaceBeforeCmd);
    yyextra->spaceBeforeCmd.resize(0);
  }
  if (optList.empty())
  {
    addOutput(yyscanner,"@"+s+" ");
  }
  else
  {
    addOutput(yyscanner,"@"+s+"{"+QCString(join(optList,","))+"} ");
  }
  //printf("handleFormatBlock(%s) with option(%s)\n",qPrint(s),qPrint(opt));
  yyextra->blockName=s;
  yyextra->commentCount=0;
  BEGIN(FormatBlock);
  return FALSE;
}
References addOutput(), FALSE, join(), and s.
handleGuard()
static void handleGuard (yyscan_t yyscanner, const QCString & expr) [static]
Definition at line 3781 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  CondParser prs;
  bool sectionEnabled=prs.parse(yyextra->fileName,yyextra->lineNr,expr.stripWhiteSpace());
  bool parentEnabled = TRUE;
  if (!yyextra->guards.empty()) parentEnabled = yyextra->guards.top().isEnabled();
  if (parentEnabled)
  {
    if (
        (sectionEnabled && yyextra->guardType==Guard_If) ||
        (!sectionEnabled && yyextra->guardType==Guard_IfNot)
       ) // section is visible
    {
      yyextra->guards.push(GuardedSection(TRUE,TRUE));
      yyextra->enabledSectionFound=TRUE;
      BEGIN(GuardParamEnd);
    }
    else // section is invisible
    {
      if (yyextra->guardType!=Guard_Skip)
      {
        yyextra->guards.push(GuardedSection(FALSE,TRUE));
      }
      BEGIN(SkipGuardedSection);
    }
  }
  else // invisible because of parent
  {
    yyextra->guards.push(GuardedSection(FALSE,FALSE));
    BEGIN(SkipGuardedSection);
  }
}
References FALSE, Guard_If, Guard_IfNot, Guard_Skip, CondParser::parse(), QCString::stripWhiteSpace(), and TRUE.
handleHeaderFile()
static bool handleHeaderFile (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2249 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  BEGIN(ClassDocArg2);
  return FALSE;
}
References FALSE.
handleHideCallergraph()
static bool handleHideCallergraph (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2867 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->current->callerGraph = FALSE; // OFF
  return FALSE;
}
References FALSE.
handleHideCallgraph()
static bool handleHideCallgraph (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2853 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->current->callGraph = FALSE; // OFF
  return FALSE;
}
References FALSE.
handleHideInitializer()
static bool handleHideInitializer (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2839 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->current->initLines = 0; // OFF
  return FALSE;
}
References FALSE.
handleHideReferencedByRelation()
static bool handleHideReferencedByRelation (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2881 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->current->referencedByRelation = FALSE; // OFF
  return FALSE;
}
References FALSE.
handleHideReferencesRelation()
static bool handleHideReferencesRelation (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2895 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->current->referencesRelation = FALSE; // OFF
  return FALSE;
}
References FALSE.
handleIdlException()
static bool handleIdlException (yyscan_t yyscanner, const QCString & cmd, const StringVector &) [static]
Definition at line 2301 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  bool stop=makeStructuralIndicator(yyscanner,Entry::EXCEPTIONDOC_SEC);
  yyextra->currentCmd = cmd;
  BEGIN(ClassDocArg1);
  return stop;
}
References Entry::EXCEPTIONDOC_SEC, and makeStructuralIndicator().
handleIf()
static bool handleIf (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2742 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->enabledSectionFound=FALSE;
  yyextra->guardType = Guard_If;
  yyextra->spaceBeforeIf = yyextra->spaceBeforeCmd;
  BEGIN(GuardParam);
  return FALSE;
}
References FALSE, and Guard_If.
handleIfNot()
static bool handleIfNot (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2752 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->enabledSectionFound=FALSE;
  yyextra->guardType = Guard_IfNot;
  yyextra->spaceBeforeIf = yyextra->spaceBeforeCmd;
  BEGIN(GuardParam);
  return FALSE;
}
References FALSE, and Guard_IfNot.
handleImage()
static bool handleImage (yyscan_t yyscanner, const QCString & s, const StringVector & optList) [static]
Definition at line 2603 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  for (const auto &opt : optList)
  {
    QCString locOpt(opt);
    locOpt = locOpt.stripWhiteSpace();
    if (locOpt.lower().startsWith("anchor:"))
    {
      addAnchor(yyscanner,locOpt.mid(7));
      break; // real option handling will be done later on
    }
  }
  if (optList.empty())
  {
    addOutput(yyscanner,"@"+s+" ");
  }
  else
  {
    addOutput(yyscanner,"@"+s+"{"+QCString(join(optList,","))+"} ");
  }
  BEGIN(Comment);
  return FALSE;
}
References addAnchor(), addOutput(), FALSE, join(), QCString::lower(), QCString::mid(), s, QCString::startsWith(), and QCString::stripWhiteSpace().
handleIngroup()
static bool handleIngroup (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2817 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->inGroupParamFound=FALSE;
  BEGIN(InGroupParam);
  return FALSE;
}
References FALSE.
handleInherit()
static bool handleInherit (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 3041 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  BEGIN(InheritParam);
  return FALSE;
}
References FALSE.
handleInterface()
static bool handleInterface (yyscan_t yyscanner, const QCString & cmd, const StringVector &) [static]
Definition at line 2292 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  bool stop=makeStructuralIndicator(yyscanner,Entry::INTERFACEDOC_SEC);
  yyextra->currentCmd = cmd;
  BEGIN(ClassDocArg1);
  return stop;
}
References Entry::INTERFACEDOC_SEC, and makeStructuralIndicator().
handleInternal()
static bool handleInternal (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2902 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  if (!Config_getBool(INTERNAL_DOCS))
  {
    // make sure some whitespace before a \internal command
    // is not treated as "documentation"
    if (yyextra->current->doc.stripWhiteSpace().isEmpty())
    {
      yyextra->current->doc.resize(0);
    }
    yyextra->condCount=0;
    BEGIN(SkipInternal);
  }
  else
  {
    // re-enabled for bug640828
    addOutput(yyscanner," \\internal ");
    yyextra->inInternalDocs = TRUE;
  }
  return FALSE;
}
References addOutput(), Config_getBool, FALSE, and TRUE.
handleLineInfo()
static bool handleLineInfo (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2729 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  if (!yyextra->spaceBeforeCmd.isEmpty())
  {
    addOutput(yyscanner,yyextra->spaceBeforeCmd);
    yyextra->spaceBeforeCmd.resize(0);
  }
  addOutput(yyscanner,QCString().setNum(yyextra->lineNr));
  addOutput(yyscanner," ");
  return FALSE;
}
References addOutput(), and FALSE.
handleMainpage()
static bool handleMainpage (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2318 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  bool stop=makeStructuralIndicator(yyscanner,Entry::MAINPAGEDOC_SEC);
  if (!stop)
  {
    yyextra->current->name = "mainpage";
  }
  setOutput(yyscanner,OutputDoc);
  BEGIN(PageDocArg2);
  return stop;
}
References Entry::MAINPAGEDOC_SEC, makeStructuralIndicator(), OutputDoc, and setOutput().
handleMemberOf()
static bool handleMemberOf (yyscan_t yyscanner, const QCString & cmd, const StringVector &) [static]
Definition at line 2539 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  if (!yyextra->current->relates.isEmpty())
  {
    warn(yyextra->fileName,yyextra->lineNr,
        "found multiple \\relates, \\relatesalso or \\memberof commands in a comment block, using last definition");
  }
  yyextra->current->relatesType = MemberOf;
  yyextra->currentCmd = cmd;
  BEGIN(RelatesParam1);
  return FALSE;
}
References FALSE, MemberOf, and warn().
handleName()
static bool handleName (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2419 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  bool stop=makeStructuralIndicator(yyscanner,Entry::MEMBERGRP_SEC);
  if (!stop)
  {
    yyextra->docGroup.clearHeader();
    BEGIN(NameParam);
    if (!yyextra->docGroup.isEmpty()) // end of previous member group
    {
      yyextra->docGroup.close(yyextra->current,yyextra->fileName,yyextra->lineNr,TRUE,true);
    }
  }
  return stop;
}
References makeStructuralIndicator(), Entry::MEMBERGRP_SEC, and TRUE.
handleNamespace()
static bool handleNamespace (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2215 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  bool stop=makeStructuralIndicator(yyscanner,Entry::NAMESPACEDOC_SEC);
  BEGIN(NameSpaceDocArg1);
  return stop;
}
References makeStructuralIndicator(), and Entry::NAMESPACEDOC_SEC.
handleNoop()
static bool handleNoop (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2412 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  BEGIN(Noop);
  return FALSE;
}
References FALSE.
handleNoSubGrouping()
static bool handleNoSubGrouping (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2825 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->current->subGrouping = FALSE;
  return FALSE;
}
References FALSE.
handleOverload()
static bool handleOverload (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2172 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->functionProto.resize(0);
  BEGIN(OverloadParam);
  return FALSE;
}
References FALSE.
handlePackage()
static bool handlePackage (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2223 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  bool stop=makeStructuralIndicator(yyscanner,Entry::PACKAGEDOC_SEC);
  BEGIN(PackageDocArg1);
  return stop;
}
References makeStructuralIndicator(), and Entry::PACKAGEDOC_SEC.
handlePage()
static bool handlePage (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2310 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  bool stop=makeStructuralIndicator(yyscanner,Entry::PAGEDOC_SEC);
  BEGIN(PageDocArg1);
  return stop;
}
References makeStructuralIndicator(), and Entry::PAGEDOC_SEC.
handleParam()
static bool handleParam (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2343 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  // we need process param and retval arguments to escape leading underscores in case of
  // markdown processing, see bug775493
  addOutput(yyscanner,"@param ");
  BEGIN(ParamArg1);
  return FALSE;
}
References addOutput(), and FALSE.
handleParBlock()
static bool handleParBlock (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2479 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  if (yyextra->insideParBlock)
  {
    warn(yyextra->fileName,yyextra->lineNr,
        "found \\parblock command while already in a parblock!");
  }
  if (!yyextra->spaceBeforeCmd.isEmpty())
  {
    addOutput(yyscanner,yyextra->spaceBeforeCmd);
    yyextra->spaceBeforeCmd.resize(0);
  }
  addOutput(yyscanner,"@parblock ");
  yyextra->insideParBlock = TRUE;
  return FALSE;
}
References addOutput(), FALSE, TRUE, and warn().
handlePrivate()
static bool handlePrivate (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2939 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->current->protection = Private;
  return FALSE;
}
References FALSE, and Private.
handlePrivateSection()
static bool handlePrivateSection (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2946 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->current->protection = yyextra->protection = Private;
  return FALSE;
}
References FALSE, and Private.
handleProtected()
static bool handleProtected (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2953 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->current->protection = Protected;
  return FALSE;
}
References FALSE, and Protected.
handleProtectedSection()
static bool handleProtectedSection (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2960 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->current->protection = yyextra->protection = Protected ;
  return FALSE;
}
References FALSE, and Protected.
handleProtocol()
static bool handleProtocol (yyscan_t yyscanner, const QCString & cmd, const StringVector &) [static]
Definition at line 2256 of file commentscan.l.
{ // Obj-C protocol
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  bool stop=makeStructuralIndicator(yyscanner,Entry::PROTOCOLDOC_SEC);
  yyextra->currentCmd = cmd;
  BEGIN(ClassDocArg1);
  return stop;
}
References makeStructuralIndicator(), and Entry::PROTOCOLDOC_SEC.
handlePublic()
static bool handlePublic (yyscan_t yyscanner, const QCString & s, const StringVector &) [static]
Definition at line 2967 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->current->protection = Public;
  return FALSE;
}
References FALSE, and Public.
handlePublicSection()
static bool handlePublicSection (yyscan_t yyscanner, const QCString & s, const StringVector &) [static]
Definition at line 2974 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->current->protection = yyextra->protection = Public;
  return FALSE;
}
References FALSE, and Public.
handlePure()
static bool handlePure (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2932 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->current->virt = Pure;
  return FALSE;
}
References FALSE, and Pure.
handleRaiseWarning()
static bool handleRaiseWarning (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2404 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->raiseWarning = "";
  BEGIN(RaiseWarning);
  return FALSE;
}
References FALSE.
handleReferencedByRelation()
static bool handleReferencedByRelation (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2874 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->current->referencedByRelation = TRUE; // ON
  return FALSE;
}
References FALSE, and TRUE.
handleReferencesRelation()
static bool handleReferencesRelation (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2888 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->current->referencesRelation = TRUE; // ON
  return FALSE;
}
References FALSE, and TRUE.
handleRefItem()
static bool handleRefItem (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2553 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  addOutput(yyscanner,"@refitem ");
  BEGIN(LineParam);
  return FALSE;
}
References addOutput(), and FALSE.
handleRelated()
static bool handleRelated (yyscan_t yyscanner, const QCString & cmd, const StringVector &) [static]
Definition at line 2511 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  if (!yyextra->current->relates.isEmpty())
  {
    warn(yyextra->fileName,yyextra->lineNr,
        "found multiple \\relates, \\relatesalso or \\memberof commands in a comment block, using last definition");
  }
  yyextra->current->relatesType = Simple;
  yyextra->currentCmd = cmd;
  BEGIN(RelatesParam1);
  return FALSE;
}
References FALSE, Simple, and warn().
handleRelatedAlso()
static bool handleRelatedAlso (yyscan_t yyscanner, const QCString & cmd, const StringVector &) [static]
Definition at line 2525 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  if (!yyextra->current->relates.isEmpty())
  {
    warn(yyextra->fileName,yyextra->lineNr,
        "found multiple \\relates, \\relatesalso or \\memberof commands in a comment block, using last definition");
  }
  yyextra->current->relatesType = Duplicate;
  yyextra->currentCmd = cmd;
  BEGIN(RelatesParam1);
  return FALSE;
}
References Duplicate, FALSE, and warn().
handleRetval()
static bool handleRetval (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2353 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  addOutput(yyscanner,"@retval ");
  BEGIN(ParamArg1);
  return FALSE;
}
References addOutput(), and FALSE.
handleSection()
static bool handleSection (yyscan_t yyscanner, const QCString & s, const StringVector &) [static]
Definition at line 2561 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  setOutput(yyscanner,OutputDoc);
  addOutput(yyscanner,"@"+s+" ");
  BEGIN(SectionLabel);
  if (s=="section") yyextra->sectionLevel=1;
  else if (s=="subsection") yyextra->sectionLevel=2;
  else if (s=="subsubsection") yyextra->sectionLevel=3;
  else if (s=="paragraph") yyextra->sectionLevel=4;
  return FALSE;
}
References addOutput(), FALSE, OutputDoc, s, and setOutput().
handleShowInitializer()
static bool handleShowInitializer (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2832 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->current->initLines = 100000; // ON
  return FALSE;
}
References FALSE.
handleStatic()
static bool handleStatic (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2925 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->current->stat = TRUE;
  return FALSE;
}
References FALSE, and TRUE.
handleStruct()
static bool handleStruct (yyscan_t yyscanner, const QCString & cmd, const StringVector &) [static]
Definition at line 2283 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  bool stop=makeStructuralIndicator(yyscanner,Entry::STRUCTDOC_SEC);
  yyextra->currentCmd = cmd;
  BEGIN(ClassDocArg1);
  return stop;
}
References makeStructuralIndicator(), and Entry::STRUCTDOC_SEC.
handleSubpage()
static bool handleSubpage (yyscan_t yyscanner, const QCString & s, const StringVector &) [static]
Definition at line 2574 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  if (yyextra->current->section!=Entry::EMPTY_SEC &&
      yyextra->current->section!=Entry::PAGEDOC_SEC &&
      yyextra->current->section!=Entry::MAINPAGEDOC_SEC
     )
  {
    warn(yyextra->fileName,yyextra->lineNr,
        "found \\subpage command in a comment block that is not marked as a page!");
  }
  if (!yyextra->spaceBeforeCmd.isEmpty())
  {
    addOutput(yyscanner,yyextra->spaceBeforeCmd);
    yyextra->spaceBeforeCmd.resize(0);
  }
  addOutput(yyscanner,"@"+s+" ");
  BEGIN(SubpageLabel);
  return FALSE;
}
References addOutput(), Entry::EMPTY_SEC, FALSE, Entry::MAINPAGEDOC_SEC, Entry::PAGEDOC_SEC, s, and warn().
handleTest()
static bool handleTest (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2444 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->newXRefKind = XRef_Test;
  setOutput(yyscanner,OutputXRef);
  yyextra->xrefKind = XRef_Test;
  return FALSE;
}
References FALSE, OutputXRef, setOutput(), and XRef_Test.
handleToc()
static bool handleToc (yyscan_t yyscanner, const QCString & s, const StringVector & optList) [static]
Definition at line 2981 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  if (yyextra->current->section==Entry::PAGEDOC_SEC ||
      yyextra->current->section==Entry::MAINPAGEDOC_SEC)
  {
    for (const auto &opt_ : optList)
    {
      QCString opt = QCString(opt_).stripWhiteSpace().lower();
      char dum;
      int level = 5;
      int i = opt.find(':');
      if (i>0) // found ':' but not on position 0 what would mean just a level
      {
        if (sscanf(opt.right(opt.length() - i - 1).data(),"%d%c",&level,&dum) != 1)
        {
          warn(yyextra->fileName,yyextra->lineNr,"Unknown option:level specified with \\tableofcontents: '%s'", qPrint(QCString(opt_).stripWhiteSpace()));
          opt = "";
        }
        else
        {
          level = (level > 5 ? 5 : level);
          level = (level <= 0 ? 5 : level);
          opt = opt.left(i).stripWhiteSpace();
        }
      }
      if (!opt.isEmpty())
      {
        if (opt == "html")
        {
          yyextra->current->localToc.enableHtml(level);
        }
        else if (opt == "latex")
        {
          yyextra->current->localToc.enableLatex(level);
        }
        else if (opt == "xml")
        {
          yyextra->current->localToc.enableXml(level);
        }
        else if (opt == "docbook")
        {
          yyextra->current->localToc.enableDocbook(level);
        }
        else
        {
          warn(yyextra->fileName,yyextra->lineNr,"Unknown option specified with \\tableofcontents: '%s'", qPrint(QCString(opt_).stripWhiteSpace()));
        }
      }
    }
    if (yyextra->current->localToc.nothingEnabled())
    {
      // for backward compatibility
      yyextra->current->localToc.enableHtml(5);
      yyextra->current->localToc.enableXml(5);
    }
  }
  return FALSE;
}
References QCString::data(), FALSE, QCString::find(), QCString::isEmpty(), QCString::left(), QCString::length(), level, QCString::lower(), Entry::MAINPAGEDOC_SEC, Entry::PAGEDOC_SEC, qPrint(), QCString::right(), QCString::stripWhiteSpace(), and warn().
handleTodo()
static bool handleTodo (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2435 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->newXRefKind = XRef_Todo;
  setOutput(yyscanner,OutputXRef);
  yyextra->xrefKind = XRef_Todo;
  return FALSE;
}
References FALSE, OutputXRef, setOutput(), and XRef_Todo.
handleUnion()
static bool handleUnion (yyscan_t yyscanner, const QCString & cmd, const StringVector &) [static]
Definition at line 2274 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  bool stop=makeStructuralIndicator(yyscanner,Entry::UNIONDOC_SEC);
  yyextra->currentCmd = cmd;
  BEGIN(ClassDocArg1);
  return stop;
}
References makeStructuralIndicator(), and Entry::UNIONDOC_SEC.
handleWeakGroup()
static bool handleWeakGroup (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2206 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  bool stop=makeStructuralIndicator(yyscanner,Entry::GROUPDOC_SEC);
  yyextra->current->groupDocType = Entry::GROUPDOC_WEAK;
  BEGIN(GroupDocArg1);
  return stop;
}
References Entry::GROUPDOC_SEC, Entry::GROUPDOC_WEAK, and makeStructuralIndicator().
handleXRefItem()
static bool handleXRefItem (yyscan_t yyscanner, const QCString & , const StringVector &) [static]
Definition at line 2471 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->newXRefKind = XRef_Item;
  BEGIN(XRefItemParam1);
  return FALSE;
}
References FALSE, and XRef_Item.
initParser()
static void initParser (yyscan_t yyscanner) [static]
Definition at line 3110 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->sectionLabel.resize(0);
  yyextra->sectionTitle.resize(0);
  yyextra->docGroup.clearHeader();
  yyextra->insideParBlock = FALSE;
}
References FALSE.
lineCount()
static void lineCount (yyscan_t yyscanner) [static]
Definition at line 3174 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  for(const char* c = yytext ; *c ; ++c)
    yyextra->lineNr += (*c == '\n') ;
}
References c.
Referenced by endBrief().
makeStructuralIndicator()
static bool makeStructuralIndicator (yyscan_t yyscanner, Entry::Sections s) [static]
Definition at line 3153 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  //printf("yyextra->current->section=%x\n",yyextra->current->section);
  if (getDocSectionName(yyextra->current->section))
  {
    return TRUE;
  }
  else
  {
    yyextra->needNewEntry = TRUE;
    yyextra->current->section = s;
    yyextra->current->fileName = yyextra->fileName;
    yyextra->current->startLine = yyextra->lineNr;
    yyextra->current->docLine = yyextra->lineNr;
    return FALSE;
  }
}
References FALSE, getDocSectionName(), s, and TRUE.
Referenced by handleAddToGroup(), handleCategory(), handleClass(), handleConcept(), handleDef(), handleDefGroup(), handleDir(), handleEnum(), handleExample(), handleFile(), handleFn(), handleIdlException(), handleInterface(), handleMainpage(), handleName(), handleNamespace(), handlePackage(), handlePage(), handleProtocol(), handleStruct(), handleUnion(), and handleWeakGroup().
sectionLevelToType()
static SectionType sectionLevelToType (int level) [static]
Definition at line 3300 of file commentscan.l.
{
  if (level>=0 && level<5) return (SectionType)level;
  return SectionType::Anchor;
}
References Anchor, and level.
Referenced by addSection().
setOutput()
static void setOutput (yyscan_t yyscanner, OutputContext ctx) [inline], [static]
Definition at line 3396 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  bool xrefAppendToPrev = yyextra->xrefAppendFlag;
  // determine append flag for the next item (i.e. the end of this item)
  yyextra->xrefAppendFlag = !yyextra->inBody &&
                   yyextra->inContext==OutputXRef && ctx==OutputXRef && // two consecutive xref items
                   yyextra->newXRefKind==yyextra->xrefKind && // of the same kind
                   (yyextra->xrefKind!=XRef_Item ||
                    yyextra->newXRefItemKey==yyextra->xrefItemKey); // with the same key if \xrefitem
  //printf("%d && %d && %d && (%d || %d)\n",
  // yyextra->inContext==OutputXRef,
  // ctx==OutputXRef,
  // yyextra->newXRefKind==yyextra->xrefKind,
  // yyextra->xrefKind!=XRef_Item,
  // yyextra->newXRefItemKey==yyextra->xrefItemKey);
  //printf("refKind=%d yyextra->newXRefKind=%d xrefAppendToPrev=%d yyextra->xrefAppendFlag=%d\n",
  // yyextra->xrefKind,yyextra->newXRefKind,xrefAppendToPrev,yyextra->xrefAppendFlag);
  //printf("setOutput(yyscanner,yyextra->inContext=%d ctx=%d)\n",yyextra->inContext,ctx);
  if (yyextra->inContext==OutputXRef) // end of XRef section => add the item
  {
    // See if we can append this new xref item to the previous one.
    // We know this at the start of the next item of the same
    // type and need to remember this until the end of that item.
    switch(yyextra->xrefKind)
    {
      case XRef_Todo:
        addXRefItem(yyscanner,QCString("todo"),
            theTranslator->trTodo(),
            theTranslator->trTodoList(),
            xrefAppendToPrev
            );
        break;
      case XRef_Test:
        addXRefItem(yyscanner,QCString("test"),
            theTranslator->trTest(),
            theTranslator->trTestList(),
            xrefAppendToPrev
            );
        break;
      case XRef_Bug:
        addXRefItem(yyscanner,QCString("bug"),
            theTranslator->trBug(),
            theTranslator->trBugList(),
            xrefAppendToPrev
            );
        break;
      case XRef_Deprecated:
        addXRefItem(yyscanner,QCString("deprecated"),
            theTranslator->trDeprecated(),
            theTranslator->trDeprecatedList(),
            xrefAppendToPrev
            );
        break;
      case XRef_Item: // user defined list
        addXRefItem(yyscanner,yyextra->xrefItemKey,
            yyextra->xrefItemTitle,
            yyextra->xrefListTitle,
            xrefAppendToPrev
            );
        break;
      case XRef_None:
        ASSERT(0);
        break;
    }
  }
  yyextra->xrefItemKey = yyextra->newXRefItemKey;
  int oldContext = yyextra->inContext;
  yyextra->inContext = ctx;
  if (yyextra->inContext!=OutputXRef && yyextra->inBody) yyextra->inContext=OutputInbody;
  switch(yyextra->inContext)
  {
    case OutputDoc:
      if (oldContext!=yyextra->inContext)
      {
        stripTrailingWhiteSpace(yyextra->current->doc);
        if (yyextra->current->doc.isEmpty()) yyextra->current->docLine = yyextra->lineNr;
        if (yyextra->current->docFile.isEmpty())
        {
          yyextra->current->docFile = yyextra->fileName;
          yyextra->current->docLine = yyextra->lineNr;
        }
      }
      yyextra->pOutputString = &yyextra->current->doc;
      break;
    case OutputBrief:
      if (oldContext!=yyextra->inContext)
      {
        if (yyextra->current->brief.isEmpty()) yyextra->current->briefLine = yyextra->lineNr;
        if (yyextra->current->briefFile.isEmpty())
        {
          yyextra->current->briefFile = yyextra->fileName;
          yyextra->current->briefLine = yyextra->lineNr;
        }
      }
      if (yyextra->current->brief.stripWhiteSpace().isEmpty()) // we only want one brief
        // description even if multiple
        // are given...
      {
        yyextra->pOutputString = &yyextra->current->brief;
      }
      else
      {
        if (!yyextra->current->doc.isEmpty()) // when appending parts add a new line
        {
          yyextra->current->doc += "\n";
        }
        yyextra->pOutputString = &yyextra->current->doc;
        yyextra->inContext = OutputDoc; // need to switch to detailed docs, see bug 631380
      }
      break;
    case OutputXRef:
      yyextra->pOutputString = &yyextra->outputXRef;
      // first item found, so can't append to previous
      //yyextra->xrefAppendFlag = FALSE;
      break;
    case OutputInbody:
      yyextra->pOutputString = &yyextra->current->inbodyDocs;
      break;
  }
}
References addXRefItem(), ASSERT, OutputBrief, OutputDoc, OutputInbody, OutputXRef, stripTrailingWhiteSpace(), theTranslator, Translator::trBug(), Translator::trBugList(), Translator::trDeprecated(), Translator::trDeprecatedList(), Translator::trTest(), Translator::trTestList(), Translator::trTodo(), Translator::trTodoList(), XRef_Bug, XRef_Deprecated, XRef_Item, XRef_None, XRef_Test, and XRef_Todo.
Referenced by endBrief(), handleBrief(), handleBug(), handleCopyBrief(), handleCopyDetails(), handleCopyDoc(), handleDeprecated(), handleDetails(), handleEndParBlock(), handleMainpage(), handleSection(), handleTest(), and handleTodo().
stripQuotes()
static QCString stripQuotes (const char * s) [static]
Definition at line 3183 of file commentscan.l.
{
  QCString name;
  if (s==0 || *s==0) return name;
  name=s;
  if (name.at(0)=='"' && name.at(name.length()-1)=='"')
  {
    name=name.mid(1,name.length()-2);
  }
  return name;
}
References setup::name, and s.
stripTrailingWhiteSpace()
static void stripTrailingWhiteSpace (QCString & s) [static]
Definition at line 3367 of file commentscan.l.
{
  uint len = s.length();
  int i = (int)len-1;
  char c;
  while (i>=0)
  {
    c = s.at(i);
    if (c==' ' || c=='\t' || c=='\r') // normal whitespace
    {
      i--;
    }
    else if (c=='r' && i>=7 && qstrncmp("\\ilinebr",s.data()+i-7,8)==0) // special line break marker
    {
      i-=8;
    }
    else // non-whitespace
    {
      break;
    }
  }
  //printf("stripTrailingWhitespace(%s) i=%d len=%d\n",qPrint(s),i,len);
  if (i!=(int)len-1)
  {
    s.resize(i+2); // string up to and including char at pos i and \0 terminator
  }
}
References c, gdFont::data, len, qstrncmp(), and s.
Referenced by setOutput().
yylex()
int yylex (yyscan_t yyscanner)
Definition at line 592 of file commentscan.l.
         {CMD}{CMD}[a-z_A-Z]+{B}* { // escaped command
                                          addOutput(yyscanner,yytext);
                                        }
<Comment>{CMD}{CMD}"~"[a-z_A-Z]* { // escaped command
                                          addOutput(yyscanner,yytext);
                                        }
<Comment>{MAILADDR} { // mail address
                                          addOutput(yyscanner,yytext);
                                        }
<Comment>"\""[^"\n]*"\"" { // quoted text
                                          addOutput(yyscanner,yytext);
                                        }
<Comment>("\\"[a-z_A-Z]+)+"\\" { // directory (or chain of commands!)
                                          addOutput(yyscanner,yytext);
                                        }
<Comment>"<"{DETAILEDHTML}{ATTR}">" { // HTML command that ends a brief description
                                          setOutput(yyscanner,OutputDoc);
                                          // continue with the same input
                                          REJECT;
                                        }
<Comment>"<"{DETAILEDHTMLOPT}{ATTR}">" { // HTML command that ends a brief description
                                          if (yyextra->current->lang==SrcLangExt_CSharp)
                                          {
                                            setOutput(yyscanner,OutputDoc);
                                          }
                                          // continue with the same input
                                          REJECT;
                                        }
<Comment>"<"{DETAILS}{ATTR}">" { // start of a HTML style details description
                                          yyextra->HTMLDetailsSummary.push_back(0);
                                          setOutput(yyscanner,OutputDoc);
                                          addOutput(yyscanner,yytext);
                                        }
<Comment>"</"{DETAILS}">" { // end of a HTML style details description
                                          if (!yyextra->HTMLDetailsSummary.empty())
                                          {
                                            yyextra->HTMLDetailsSummary.pop_back();
                                          }
                                          addOutput(yyscanner,yytext);
                                        }
<Comment>"<"{AHTML} { // potential start of HTML anchor, see issue 9200
                                          yyextra->htmlAnchorStr = yytext;
                                          yyextra->htmlAnchor = false;
                                          BEGIN(HtmlA);
                                        }
<HtmlA>{ANCHTML} { // only labels that can be converted to doxygen anchor
                                          yyextra->htmlAnchorStr += yytext;
                                          QCString tag(yytext);
                                          int s=tag.find("=");
                                          char c=tag[s+1];
                                          QCString id;
                                          if (c=='\'' || c=='"') // valid start
                                          {
                                            int e=tag.find(c,s+2);
                                            if (e!=-1) // found matching end
                                            {
                                              id=tag.mid(s+2,e-s-2); // extract id
                                              addAnchor(yyscanner,id);
                                            }
                                          }
                                          else
                                          {
                                            id=tag.mid(s+1);
                                            addAnchor(yyscanner,id);
                                          }
                                          if (!id.isEmpty() && !yyextra->htmlAnchor)
                                          {
                                            // only use first analogous to what is in docparser
                                            addOutput(yyscanner,"@anchor ");
                                            addOutput(yyscanner,id.data());
                                            addOutput(yyscanner," ");
                                            yyextra->htmlAnchor = true;
                                          }
                                        }
<HtmlA>("\""[^\n\"]*"\""|"'"[^\n']*"'") {
                                          yyextra->htmlAnchorStr += yytext;
                                        }
<HtmlA>">"|"/>" {
                                          if (!yyextra->htmlAnchor)
                                          {
                                            addOutput(yyscanner,yyextra->htmlAnchorStr);
                                            addOutput(yyscanner,yytext);
                                          }
                                          else
                                          {
                                            if (yyleng == 1) // to keep <a></a> pairs, otherwise single </a> present
                                            {
                                              addOutput(yyscanner,"<a>");
                                            }
                                          }
                                          BEGIN(Comment);
                                        }
<HtmlA>{DOCNL} { // newline
                                          yyextra->htmlAnchorStr += yytext;
                                          if (*yytext == '\n') yyextra->lineNr++;
                                        }
<HtmlA>. { // catch-all for anything else
                                          yyextra->htmlAnchorStr += yytext;
                                        }
<Comment>"<"{SUMMARY}">" { // start of a .NET XML style brief description
                                          if (yyextra->HTMLDetailsSummary.empty())
                                          {
                                            setOutput(yyscanner,OutputBrief);
                                          }
                                          else // HTML5 style <summary> as part of <details> section.
                                          {
                                            addOutput(yyscanner,yytext);
                                          }
                                        }
<Comment>"<"{REMARKS}">" { // start of a .NET XML style detailed description
                                          setOutput(yyscanner,OutputDoc);
                                          addOutput(yyscanner,yytext);
                                        }
<Comment>"</"{SUMMARY}">" { // start of a .NET XML style detailed description
                                          if (!yyextra->HTMLDetailsSummary.empty())
                                          {
                                            addOutput(yyscanner,yytext);
                                          }
                                          else
                                          {
                                            setOutput(yyscanner,OutputDoc);
                                          }
                                        }
<Comment>"</"{REMARKS}">" { // end of a brief or detailed description
                                          setOutput(yyscanner,OutputDoc);
                                          addOutput(yyscanner,yytext);
                                        }
<Comment>"<"{CAPTION}{ATTR}">" {
                                          QCString tag(yytext);
                                          int s=tag.find("id=");
                                          if (s!=-1) // command has id attribute
                                          {
                                            char c=tag[s+3];
                                            if (c=='\'' || c=='"') // valid start
                                            {
                                              int e=tag.find(c,s+4);
                                              if (e!=-1) // found matching end
                                              {
                                                QCString id=tag.mid(s+4,e-s-4); // extract id
                                                addAnchor(yyscanner,id);
                                              }
                                            }
                                          }
                                          addOutput(yyscanner,yytext);
                                        }
<Comment>"<"{PRE}{ATTR}">" {
                                          yyextra->insidePre=TRUE;
                                          addOutput(yyscanner,yytext);
                                        }
<Comment>"</"{PRE}">" {
                                          yyextra->insidePre=FALSE;
                                          addOutput(yyscanner,yytext);
                                        }
<Comment>{RCSTAG} { // RCS tag which end a brief description
                                          setOutput(yyscanner,OutputDoc);
                                          REJECT;
                                        }
<Comment>"<!--" {
                                          BEGIN(HtmlComment);
                                        }
<Comment>"<!\[CDATA\[" {
                                          BEGIN(CdataSection);
                                        }
<Comment>{B}*{CMD}"endinternal"{B}* {
                                          addOutput(yyscanner," \\endinternal ");
                                          if (!yyextra->inInternalDocs)
                                              warn(yyextra->fileName,yyextra->lineNr,
                                               "found \\endinternal without matching \\internal"
                                              );
                                          yyextra->inInternalDocs = FALSE;
                                        }
<Comment>{B}*"\\ilinebr"{B}* { // preserve spacing around \\ilinebr
                                          addOutput(yyscanner,yytext);
                                        }
<Comment>{B}*{CMD}[a-z_A-Z]+"{"[a-zA-Z_,:0-9\. ]*"}"{B}* |
<Comment>{B}*{CMD}[a-z_A-Z]+{B}* { // potentially interesting command
                                          // the {B}* in the front was added for bug620924
                                          QCString fullMatch = QCString(yytext);
                                          int idx = fullMatch.find('{');
                                          /* handle `\f{` and `@f{` as special cases */
                                          if ((idx > 1) && (yytext[idx-1] == 'f') && (yytext[idx-2] == '\\' || yytext[idx-2] =='@')) REJECT;
                                          int idxEnd = fullMatch.find("}",idx+1);
                                          QCString cmdName;
                                          StringVector optList;
                                          if (idx == -1) // no options
                                          {
                                            cmdName = QCString(yytext).stripWhiteSpace().mid(1); // to remove {CMD}
                                          }
                                          else // options present
                                          {
                                            cmdName = fullMatch.left(idx).stripWhiteSpace().mid(1); // to remove {CMD}
                                            QCString optStr = fullMatch.mid(idx+1,idxEnd-idx-1).stripWhiteSpace();
                                            optList = split(optStr.str(),",");
                                          }
                                          auto it = docCmdMap.find(cmdName.str());
                                          //printf("lookup command '%s' found=%d\n",qPrint(cmdName),it!=docCmdMap.end());
                                          if (it!=docCmdMap.end()) // special action is required
                                          {
                                            int i=0;
                                            while (yytext[i]==' ' || yytext[i]=='\t') i++;
                                            yyextra->spaceBeforeCmd = QCString(yytext).left(i);
                                            CommandSpacing spacing = it->second.spacing;
                                            if ((spacing==CommandSpacing::Block || spacing==CommandSpacing::XRef) &&
                                                !(yyextra->inContext==OutputXRef && cmdName=="parblock"))
                                            {
                                              yyextra->briefEndsAtDot=FALSE;
                                              bool insideXRef = yyextra->inContext==OutputXRef && spacing==CommandSpacing::XRef;
                                              // this command forces the end of brief description
                                              setOutput(yyscanner,insideXRef ? OutputXRef : OutputDoc);
                                            }
                                            //if (i>0) addOutput(yyscanner,QCString(yytext).left(i)); // removed for bug 689341
                                            if (it->second.handler && it->second.handler(yyscanner, cmdName, optList))
                                            {
                                              // implicit split of the comment block into two
                                              // entries. Restart the next block at the start
                                              // of this command.
                                              yyextra->parseMore=TRUE;
                                              // yuk, this is probably not very portable across lex implementations,
                                              // but we need to know the position in the input buffer where this
                                              // rule matched.
                                              // for flex 2.5.33+ we should use YY_CURRENT_BUFFER_LVALUE
#if YY_FLEX_MAJOR_VERSION>=2 && (YY_FLEX_MINOR_VERSION>5 || (YY_FLEX_MINOR_VERSION==5 && YY_FLEX_SUBMINOR_VERSION>=33))
                                              yyextra->inputPosition=yyextra->prevPosition + (int)(yy_bp - YY_CURRENT_BUFFER_LVALUE->yy_ch_buf);
#else
                                              yyextra->inputPosition=yyextra->prevPosition + (int)(yy_bp - yy_current_buffer->yy_ch_buf);
#endif
                                              yyterminate();
                                            }
                                            else if (it->second.handler==0)
                                            {
                                              // command without handler, to be processed
                                              // later by parsedoc.cpp
                                              addOutput(yyscanner,yytext);
                                            }
                                          }
                                          else // command not relevant
                                          {
                                            addOutput(yyscanner,yytext);
                                          }
                                        }
<Comment>{B}*({CMD}{CMD})"f"[$\[{] { // escaped formula command
                                          addOutput(yyscanner,yytext);
                                        }
<Comment>{B}*{CMD}"~"[a-z_A-Z-]* { // language switch command
                                          QCString langId = QCString(yytext).stripWhiteSpace().mid(2);
                                          if (!langId.isEmpty() &&
                                              qstricmp(Config_getEnumAsString(OUTPUT_LANGUAGE),langId)!=0)
                                          { // enable language specific section
                                            if (!Config_isAvailableEnum(OUTPUT_LANGUAGE,langId))
                                            {
                                               warn(yyextra->fileName,yyextra->lineNr,
                                               "non supported language '%s' specified in '%s'",langId.data(),QCString(yytext).stripWhiteSpace().data());
                                            }
                                            BEGIN(SkipLang);
                                          }
                                        }
<Comment>{B}*{CMD}"f{"[^}\n]+"}"("{"?) { // start of a formula with custom environment
                                          setOutput(yyscanner,OutputDoc);
                                          yyextra->formulaText="\\begin";
                                          yyextra->formulaEnv=QCString(yytext).stripWhiteSpace().mid(2);
                                          if (yyextra->formulaEnv.at(yyextra->formulaEnv.length()-1)=='{')
                                          {
                                            // remove trailing open brace
                                            yyextra->formulaEnv=yyextra->formulaEnv.left(yyextra->formulaEnv.length()-1);
                                          }
                                          yyextra->formulaText+=yyextra->formulaEnv;
                                          yyextra->formulaNewLines=0;
                                          BEGIN(ReadFormulaLong);
                                        }
<Comment>{B}*{CMD}"f$" { // start of a inline formula
                                          yyextra->formulaText="$";
                                          yyextra->formulaNewLines=0;
                                          BEGIN(ReadFormulaShort);
                                        }
<Comment>{B}*{CMD}"f(" { // start of a inline formula
                                          yyextra->formulaText="";
                                          yyextra->formulaNewLines=0;
                                          BEGIN(ReadFormulaRound);
                                        }
<Comment>{B}*{CMD}"f[" { // start of a block formula
                                          setOutput(yyscanner,OutputDoc);
                                          yyextra->formulaText="\\[";
                                          yyextra->formulaNewLines=0;
                                          BEGIN(ReadFormulaLong);
                                        }
<Comment>{B}*{CMD}"{" { // begin of a group
                                          //yyextra->langParser->handleGroupStartCommand(yyextra->memberGroupHeader);
                                          yyextra->docGroup.open(yyextra->current,yyextra->fileName,yyextra->lineNr);
                                        }
<Comment>{B}*{CMD}"}" { // end of a group
                                          //yyextra->langParser->handleGroupEndCommand();
                                          yyextra->docGroup.close(yyextra->current,yyextra->fileName,yyextra->lineNr,TRUE);
                                          yyextra->docGroup.clearHeader();
                                          yyextra->parseMore=TRUE;
                                          yyextra->needNewEntry = TRUE;
#if YY_FLEX_MAJOR_VERSION>=2 && (YY_FLEX_MINOR_VERSION>5 || (YY_FLEX_MINOR_VERSION==5 && YY_FLEX_SUBMINOR_VERSION>=33))
                                          yyextra->inputPosition=yyextra->prevPosition + (int)(yy_bp - YY_CURRENT_BUFFER_LVALUE->yy_ch_buf) + (int)strlen(yytext);
#else
                                          yyextra->inputPosition=yyextra->prevPosition + (int)(yy_bp - yy_current_buffer->yy_ch_buf) + (int)strlen(yytext);
#endif
                                          yyterminate();
                                        }
<Comment>{B}*{CMD}[$@\\&~<>#%] { // escaped character
                                          addOutput(yyscanner,yytext);
                                        }
<Comment>[a-z_A-Z]+ { // normal word
                                          addOutput(yyscanner,yytext);
                                        }
<Comment>^{B}*"."{Bopt}/\n { // explicit end autolist: e.g " ."
                                            addOutput(yyscanner,yytext);
                                        }
<Comment>^{B}*[1-9][0-9]*"."{B}+ |
<Comment>^{B}*[*+]{B}+ { // start of autolist
                                          if (!yyextra->markdownSupport)
                                          {
                                            REJECT;
                                          }
                                          else
                                          {
                                            if (yyextra->inContext!=OutputXRef)
                                            {
                                              yyextra->briefEndsAtDot=FALSE;
                                              setOutput(yyscanner,OutputDoc);
                                            }
                                            addOutput(yyscanner,yytext);
                                          }
                                          }
<Comment>^{B}*"-"{B}+ { // start of autolist
                                          if (yyextra->inContext!=OutputXRef)
                                          {
                                            yyextra->briefEndsAtDot=FALSE;
                                            setOutput(yyscanner,OutputDoc);
                                          }
                                          addOutput(yyscanner,yytext);
                                        }
<Comment>^{B}*([\-:|]{B}*)*("--"|"---")({B}*[\-:|])*{Bopt}/\n { // horizontal line (dashed)
                                            addOutput(yyscanner,yytext);
                                        }
<Comment>{CMD}"---" { // escaped mdash
                                          addOutput(yyscanner,yytext);
                                        }
<Comment>{CMD}"--" { // escaped mdash
                                          addOutput(yyscanner,yytext);
                                        }
<Comment>"---" { // mdash
                                          addOutput(yyscanner,yyextra->insidePre || yyextra->markdownSupport ? yytext : "&mdash;");
                                        }
<Comment>"--" { // ndash
                                          addOutput(yyscanner,yyextra->insidePre || yyextra->markdownSupport ? yytext : "&ndash;");
                                        }
<Comment>"-#"{B}+ { // numbered item
                                          if (yyextra->inContext!=OutputXRef)
                                          {
                                            yyextra->briefEndsAtDot=FALSE;
                                            setOutput(yyscanner,OutputDoc);
                                          }
                                          addOutput(yyscanner,yytext);
                                        }
<Comment>("."+)[a-z_A-Z0-9\)] { // . at start or in the middle of a word, or ellipsis
                                          addOutput(yyscanner,yytext);
                                        }
<Comment>".\\"[ \t] { // . with escaped space.
                                          addOutput(yyscanner,yytext[0]);
                                          addOutput(yyscanner,yytext[2]);
                                        }
<Comment>"."[,:;] { // . with some puntuations such as "e.g.," or "e.g.:"
                                          addOutput(yyscanner,yytext);
                                        }
<Comment>"...\\"[ \t] { // ellipsis with escaped space.
                                          addOutput(yyscanner,"... ");
                                        }
<Comment>"..."/[^\.] { // ellipsis
                                          addOutput(yyscanner,"...");
                                        }
<Comment>".."[\.]?/[^ \t\n] { // internal ellipsis
                                          addOutput(yyscanner,yytext);
                                        }
<Comment>(\n|\\ilinebr)({B}*(\n|\\ilinebr))+ { // at least one blank line (or blank line command)
                                          if (yyextra->inContext==OutputXRef)
                                          {
                                            // see bug 613024, we need to put the newlines after ending the XRef section.
                                            if (!yyextra->insideParBlock) setOutput(yyscanner,OutputDoc);
                                            yy_size_t i;
                                            for (i=0;i<(yy_size_t)yyleng;)
                                            {
                                              if (yytext[i]=='\n') addOutput(yyscanner,'\n'),i++;
                                              else if (strcmp(yytext+i,"\\ilinebr")==0) addOutput(yyscanner,"\\ilinebr"),i+=8;
                                              else i++;
                                            }
                                          }
                                          else if (yyextra->inContext!=OutputBrief)
                                          {
                                            yy_size_t i;
                                            for (i=0;i<(yy_size_t)yyleng;)
                                            {
                                              if (yytext[i]=='\n') addOutput(yyscanner,'\n'),i++;
                                              else if (strcmp(yytext+i,"\\ilinebr")==0) addOutput(yyscanner,"\\ilinebr"),i+=8;
                                              else i++;
                                            }
                                            setOutput(yyscanner,OutputDoc);
                                          }
                                          else // yyextra->inContext==OutputBrief
                                          { // only go to the detailed description if we have
                                            // found some brief description and not just whitespace
                                            endBrief(yyscanner,TRUE);
                                          }
                                          lineCount(yyscanner);
                                        }
<Comment>"." { // potential end of a JavaDoc style comment
                                          addOutput(yyscanner,*yytext);
                                          if (yyextra->briefEndsAtDot)
                                          {
                                            setOutput(yyscanner,OutputDoc);
                                            yyextra->briefEndsAtDot=FALSE;
                                          }
                                        }
<Comment>{DOCNL} { // newline
                                          addOutput(yyscanner,yytext);
                                          if (*yytext == '\n') yyextra->lineNr++;
                                        }
<Comment>. { // catch-all for anything else
                                          addOutput(yyscanner,*yytext);
                                        }
 /* -------------- Rules for handling HTML comments ----------- */
<HtmlComment>"--"[!]?">"{B}* { BEGIN(Comment); }
<HtmlComment>{DOCNL} {
                                          if (*yytext=='\n')
                                          {
                                            addOutput(yyscanner,*yytext);
                                            yyextra->lineNr++;
                                          }
                                        }
<HtmlComment>[^\\\n\-]+ { // ignore unimportant characters
                                        }
<HtmlComment>. { // ignore every else
                                        }
<CdataSection>"\]\]>" {
                                          BEGIN(Comment);
                                        }
<CdataSection>{DOCNL} {
                                          addOutput(yyscanner,'\n');
                                          if (*yytext=='\n') yyextra->lineNr++;
                                        }
<CdataSection>[<>&] { // the special XML characters for iwhich the CDATA section is especially used
                                          addOutput(yyscanner,'\\');
                                          addOutput(yyscanner,*yytext);
                                        }
<CdataSection>[^\\\n\]<>&]+ {
                                          addOutput(yyscanner,yytext);
                                        }
<CdataSection>. {
                                          addOutput(yyscanner,*yytext);
                                        }
 /* -------------- Rules for handling formulas ---------------- */
<ReadFormulaShort>{CMD}"f$" { // end of inline formula
                                          yyextra->formulaText+="$";
                                          addOutput(yyscanner," "+addFormula(yyscanner));
                                          BEGIN(Comment);
                                        }
<ReadFormulaRound>{CMD}"f)" { // end of inline formula
                                          addOutput(yyscanner," "+addFormula(yyscanner));
                                          BEGIN(Comment);
                                        }
<ReadFormulaLong>{CMD}"f]" { // end of block formula
                                          yyextra->formulaText+="\\]";
                                          addOutput(yyscanner," "+addFormula(yyscanner));
                                          BEGIN(Comment);
                                        }
<ReadFormulaLong>{CMD}"f}" { // end of custom env formula
                                          yyextra->formulaText+="\\end";
                                          yyextra->formulaText+=yyextra->formulaEnv;
                                          addOutput(yyscanner," "+addFormula(yyscanner));
                                          BEGIN(Comment);
                                        }
<ReadFormulaLong,ReadFormulaShort,ReadFormulaRound>[^\\@\n]+ { // any non-special character
                                          yyextra->formulaText+=yytext;
                                        }
<ReadFormulaLong,ReadFormulaShort,ReadFormulaRound>\n { // new line
                                          yyextra->formulaNewLines++;
                                          yyextra->formulaText+=*yytext;
                                          yyextra->lineNr++;
                                          addIline(yyscanner,yyextra->lineNr);
                                        }
<ReadFormulaLong,ReadFormulaShort,ReadFormulaRound>. { // any other character
                                          yyextra->formulaText+=*yytext;
                                        }
  /* ------------ handle argument of enum command --------------- */
<EnumDocArg1>{SCOPEID} { // handle argument
                                          yyextra->current->name = yytext;
                                          BEGIN(Comment);
                                        }
<EnumDocArg1>{LC} { // line continuation
                                          yyextra->lineNr++;
                                          addOutput(yyscanner,'\n');
                                        }
<EnumDocArg1>{DOCNL} { // missing argument
                                          warn(yyextra->fileName,yyextra->lineNr,
                                               "missing argument after \\enum."
                                              );
                                          unput_string(yytext,yyleng);
                                          //addOutput(yyscanner,'\n');
                                          //if (*yytext=='\n') yyextra->lineNr++;
                                          BEGIN(Comment);
                                        }
<EnumDocArg1>. { // ignore other stuff
                                        }
  /* ------------ handle argument of namespace command --------------- */
<NameSpaceDocArg1>{SCOPENAME} { // handle argument
                                          lineCount(yyscanner);
                                          yyextra->current->name = substitute(removeRedundantWhiteSpace(QCString(yytext)),QCString("."),QCString("::"));
                                          BEGIN(Comment);
                                        }
<NameSpaceDocArg1>{LC} { // line continuation
                                          yyextra->lineNr++;
                                          addOutput(yyscanner,'\n');
                                        }
<NameSpaceDocArg1>{DOCNL} { // missing argument
                                          warn(yyextra->fileName,yyextra->lineNr,
                                               "missing argument after "
                                               "\\namespace."
                                              );
                                          unput_string(yytext,yyleng);
                                          //addOutput(yyscanner,'\n');
                                          //if (*yytext=='\n') yyextra->lineNr++;
                                          BEGIN(Comment);
                                        }
<NameSpaceDocArg1>. { // ignore other stuff
                                        }
  /* ------------ handle argument of package command --------------- */
<PackageDocArg1>{ID}("."{ID})* { // handle argument
                                          yyextra->current->name = yytext;
                                          BEGIN(Comment);
                                        }
<PackageDocArg1>{LC} { // line continuation
                                          yyextra->lineNr++;
                                          addOutput(yyscanner,'\n');
                                        }
<PackageDocArg1>{DOCNL} { // missing argument
                                          warn(yyextra->fileName,yyextra->lineNr,
                                               "missing argument after "
                                               "\\package."
                                              );
                                          unput_string(yytext,yyleng);
                                          //addOutput(yyscanner,'\n');
                                          //if (*yytext=='\n') yyextra->lineNr++;
                                          BEGIN(Comment);
                                        }
<PackageDocArg1>. { // ignore other stuff
                                        }
  /* ------------ handle argument of concept command --------------- */
<ConceptDocArg1>{SCOPEID} { // handle argument
                                          yyextra->current->name = yytext;
                                          BEGIN(Comment);
                                        }
<ConceptDocArg1>{LC} { // line continuation
                                          yyextra->lineNr++;
                                          addOutput(yyscanner,'\n');
                                        }
<ConceptDocArg1>{DOCNL} { // missing argument
                                          warn(yyextra->fileName,yyextra->lineNr,
                                               "missing argument after "
                                               "\\concept."
                                              );
                                          unput_string(yytext,yyleng);
                                          BEGIN(Comment);
                                        }
<ConceptDocArg1>. { // ignore other stuff
                                        }
  /* ------ handle argument of class/struct/union command --------------- */
<ClassDocArg1>{SCOPENAME}{TMPLSPEC} {
                                          lineCount(yyscanner);
                                          yyextra->current->name = substitute(removeRedundantWhiteSpace(QCString(yytext)),".","::");
                                          BEGIN(ClassDocArg2);
                                        }
<ClassDocArg1>{SCOPENAME} { // first argument
                                          lineCount(yyscanner);
                                          yyextra->current->name = substitute(QCString(yytext),".","::");
                                          if (yyextra->current->section==Entry::PROTOCOLDOC_SEC)
                                          {
                                            yyextra->current->name+="-p";
                                          }
                                          // prepend outer scope name
                                          BEGIN(ClassDocArg2);
                                        }
<CategoryDocArg1>{SCOPENAME}{B}*"("[^\)]+")" {
                                          lineCount(yyscanner);
                                          yyextra->current->name = substitute(QCString(yytext),".","::");
                                          BEGIN(ClassDocArg2);
                                        }
<ClassDocArg1,CategoryDocArg1>{LC} { // line continuation
                                          yyextra->lineNr++;
                                          addOutput(yyscanner,'\n');
                                        }
<ClassDocArg1,CategoryDocArg1>{DOCNL} {
                                          warn(yyextra->fileName,yyextra->lineNr,
                                               "missing argument after "
                                               "'\\%s'.",qPrint(yyextra->currentCmd)
                                              );
                                          //addOutput(yyscanner,'\n');
                                          //if (*yytext=='\n') yyextra->lineNr++;
                                          unput_string(yytext,yyleng);
                                          BEGIN(Comment);
                                        }
<ClassDocArg1,CategoryDocArg1>. { // ignore other stuff
                                        }
<ClassDocArg2>{DOCNL} {
                                          //addOutput(yyscanner,'\n');
                                          //if (*yytext=='\n') yyextra->lineNr++;
                                          unput_string(yytext,yyleng);
                                          BEGIN(Comment);
                                        }
<ClassDocArg2>{FILE}|"<>" { // second argument; include file
                                          yyextra->current->includeFile = yytext;
                                          BEGIN(ClassDocArg3);
                                        }
<ClassDocArg2>{LC} { // line continuation
                                          yyextra->lineNr++;
                                          addOutput(yyscanner,'\n');
                                        }
<ClassDocArg2>. { // ignore other stuff
                                        }
<ClassDocArg3>[<"]?{FILE}?[">]? { // third argument; include file name
                                          yyextra->current->includeName = yytext;
                                          BEGIN(Comment);
                                        }
<ClassDocArg3>{LC} { // line continuation
                                          yyextra->lineNr++;
                                          addOutput(yyscanner,'\n');
                                        }
<ClassDocArg3>{DOCNL} {
                                          //if (*yytext=='\n') yyextra->lineNr++;
                                          unput_string(yytext,yyleng);
                                          BEGIN(Comment);
                                        }
<ClassDocArg3>. { // ignore other stuff
                                        }
  /* --------- handle arguments of {def,add,weak}group commands --------- */
<GroupDocArg1>{LABELID}(".html"?) { // group name
                                           yyextra->current->name = yytext;
                                          //lastDefGroup.groupname = yytext;
                                          //lastDefGroup.pri = yyextra->current->groupingPri();
                                          // the .html stuff is for Qt compatibility
                                          if (yyextra->current->name.endsWith(".html"))
                                          {
                                            yyextra->current->name=yyextra->current->name.left(yyextra->current->name.length()-5);
                                          }
                                          yyextra->current->type.resize(0);
                                          BEGIN(GroupDocArg2);
                                        }
<GroupDocArg1>"\\"{B}*"\n" { // line continuation
                                          yyextra->lineNr++;
                                          addOutput(yyscanner,'\n');
                                        }
<GroupDocArg1>{DOCNL} { // missing argument!
                                          warn(yyextra->fileName,yyextra->lineNr,
                                               "missing group name after %s",
                                               yyextra->current->groupDocCmd()
                                              );
                                          //addOutput(yyscanner,'\n');
                                          //if (*yytext=='\n') yyextra->lineNr++;
                                          unput_string(yytext,yyleng);
                                          BEGIN(Comment);
                                        }
<GroupDocArg1>. { // ignore other stuff
                                        }
<GroupDocArg2>"\\"{B}*"\n" { // line continuation
                                          yyextra->lineNr++;
                                          addOutput(yyscanner,'\n');
                                        }
<GroupDocArg2>[^\n\\]+ { // title (stored in type)
                                          yyextra->current->type += yytext;
                                          yyextra->current->type = yyextra->current->type.stripWhiteSpace();
                                        }
<GroupDocArg2>{DOCNL} {
                                          if (yyextra->current->groupDocType==Entry::GROUPDOC_NORMAL &&
                                               yyextra->current->type.isEmpty()
                                             ) // defgroup requires second argument
                                          {
                                              warn(yyextra->fileName,yyextra->lineNr,
                                                 "missing title after "
                                                 "\\defgroup %s", qPrint(yyextra->current->name)
                                                );
                                          }
                                          unput_string(yytext,yyleng);
                                          //if (*yytext=='\n') yyextra->lineNr++;
                                          //addOutput(yyscanner,'\n');
                                          BEGIN(Comment);
                                        }
<GroupDocArg2>. { // title (stored in type)
                                          yyextra->current->type += yytext;
                                          yyextra->current->type = yyextra->current->type.stripWhiteSpace();
                                        }
  /* --------- handle arguments of page/mainpage command ------------------- */
<PageDocArg1>{FILE} { // first argument; page name
                                          yyextra->current->name = stripQuotes(yytext);
                                          yyextra->current->args = "";
                                          BEGIN(PageDocArg2);
                                        }
<PageDocArg1>{LC} { yyextra->lineNr++;
                                          addOutput(yyscanner,'\n');
                                        }
<PageDocArg1>{DOCNL} {
                                            warn(yyextra->fileName,yyextra->lineNr,
                                               "missing argument after "
                                               "\\page."
                                              );
                                          unput_string(yytext,yyleng);
                                          //if (*yytext=='\n') yyextra->lineNr++;
                                          //addOutput(yyscanner,'\n');
                                          BEGIN(Comment);
                                        }
<PageDocArg1>. { // ignore other stuff
                                        }
<PageDocArg2>{DOCNL} { // second argument; page title
                                          unput_string(yytext,yyleng);
                                          //if (*yytext=='\n') yyextra->lineNr++;
                                          //addOutput(yyscanner,'\n');
                                          BEGIN(Comment);
                                        }
<PageDocArg2>{CMD}[<>] {
                                          // bug 748927
                                          QCString tmp(yytext);
                                          tmp = substitute(substitute(tmp,"@<","&lt;"),"@>","&gt;");
                                          tmp = substitute(substitute(tmp,"\\<","&lt;"),"\\>","&gt;");
                                          yyextra->current->args += tmp;
                                        }
<PageDocArg2>. {
                                          yyextra->current->args += yytext;
                                        }
  /* --------- handle arguments of the param command ------------ */
<ParamArg1>{ID}/{B}*"," {
                                          addOutput(yyscanner,yytext);
                                        }
<ParamArg1>"," {
                                          addOutput(yyscanner," , ");
                                        }
<ParamArg1>{DOCNL} {
                                          if (*yytext=='\n') yyextra->lineNr++;
                                          addOutput(yyscanner," ");
                                        }
<ParamArg1>{ID} {
                                          addOutput(yyscanner,yytext);
                                          BEGIN(Comment);
                                        }
<ParamArg1>. {
                                          unput(yytext[0]);
                                          BEGIN(Comment);
                                        }
  /* --------- handle arguments of the file/dir/example command ------------ */
<FileDocArg1>{DOCNL} { // no file name specified
                                          unput_string(yytext,yyleng);
                                          //if (*yytext=='\n') yyextra->lineNr++;
                                          //addOutput(yyscanner,'\n');
                                          BEGIN(Comment);
                                        }
<FileDocArg1>{FILE} { // first argument; name
                                          yyextra->current->name = stripQuotes(yytext);
                                          BEGIN(Comment);
                                        }
<FileDocArg1>{LC} { yyextra->lineNr++;
                                          addOutput(yyscanner,'\n');
                                        }
<FileDocArg1>. { // ignore other stuff
                                        }
  /* --------- handle arguments of the xrefitem command ------------ */
<XRefItemParam1>{LABELID} { // first argument
                                          yyextra->newXRefItemKey=yytext;
                                          setOutput(yyscanner,OutputXRef);
                                          BEGIN(XRefItemParam2);
                                        }
<XRefItemParam1>{LC} { // line continuation
                                          yyextra->lineNr++;
                                          addOutput(yyscanner,'\n');
                                        }
<XRefItemParam1>{DOCNL} { // missing arguments
                                          warn(yyextra->fileName,yyextra->lineNr,
                                               "Missing first argument of \\xrefitem"
                                              );
                                          if (*yytext=='\n') yyextra->lineNr++;
                                          addOutput(yyscanner,'\n');
                                          yyextra->inContext = OutputDoc;
                                          BEGIN(Comment);
                                        }
<XRefItemParam1>. { // ignore other stuff
                                        }
<XRefItemParam2>"\""[^\n\"]*"\"" { // second argument
                                          yyextra->xrefItemTitle = stripQuotes(yytext);
                                          BEGIN(XRefItemParam3);
                                        }
<XRefItemParam2>{LC} { // line continuation
                                          yyextra->lineNr++;
                                          addOutput(yyscanner,'\n');
                                        }
<XRefItemParam2>{DOCNL} { // missing argument
                                          warn(yyextra->fileName,yyextra->lineNr,
                                              "Missing second argument of \\xrefitem"
                                              );
                                          if (*yytext=='\n') yyextra->lineNr++;
                                          addOutput(yyscanner,'\n');
                                          yyextra->inContext = OutputDoc;
                                          BEGIN(Comment);
                                        }
<XRefItemParam2>. { // ignore other stuff
                                        }
<XRefItemParam3>"\""[^\n\"]*"\"" { // third argument
                                          yyextra->xrefListTitle = stripQuotes(yytext);
                                          yyextra->xrefKind = XRef_Item;
                                          BEGIN(Comment);
                                        }
<XRefItemParam2,XRefItemParam3>{LC} { // line continuation
                                          yyextra->lineNr++;
                                          addOutput(yyscanner,'\n');
                                        }
<XRefItemParam3>{DOCNL} { // missing argument
                                          warn(yyextra->fileName,yyextra->lineNr,
                                              "Missing third argument of \\xrefitem"
                                              );
                                          if (*yytext=='\n') yyextra->lineNr++;
                                          addOutput(yyscanner,'\n');
                                          yyextra->inContext = OutputDoc;
                                          BEGIN(Comment);
                                        }
<XRefItemParam3>. { // ignore other stuff
                                        }
  /* ----- handle arguments of the relates(also)/memberof command ------- */
<RelatesParam1>({ID}("::"|"."))*{ID} { // argument
                                          yyextra->current->relates = yytext;
                                          //if (yyextra->current->mGrpId!=DOX_NOGROUP)
                                          //{
                                          // memberGroupRelates = yytext;
                                          //}
                                          BEGIN(Comment);
                                        }
<RelatesParam1>{LC} { // line continuation
                                          yyextra->lineNr++;
                                          addOutput(yyscanner,'\n');
                                        }
<RelatesParam1>{DOCNL} { // missing argument
                                          warn(yyextra->fileName,yyextra->lineNr,
                                              "Missing argument of '\\%s' command",qPrint(yyextra->currentCmd)
                                              );
                                          unput_string(yytext,yyleng);
                                          //if (*yytext=='\n') yyextra->lineNr++;
                                          //addOutput(yyscanner,'\n');
                                          BEGIN(Comment);
                                        }
<RelatesParam1>. { // ignore other stuff
                                        }
  /* ----- handle arguments of the relates(also)/addindex commands ----- */
<LineParam>{CMD}{CMD} { // escaped command
                                          addOutput(yyscanner,yytext);
                                        }
<LineParam>{DOCNL} { // end of argument
                                          //if (*yytext=='\n') yyextra->lineNr++;
                                          //addOutput(yyscanner,'\n');
                                          unput_string(yytext,yyleng);
                                          BEGIN(Comment);
                                        }
<LineParam>{LC} { // line continuation
                                          yyextra->lineNr++;
                                          addOutput(yyscanner,'\n');
                                        }
<LineParam>. { // ignore other stuff
                                          addOutput(yyscanner,*yytext);
                                        }
  /* ----- handle arguments of the section/subsection/.. commands ------- */
<SectionLabel>{LABELID} { // first argument
                                          yyextra->sectionLabel=yytext;
                                          addOutput(yyscanner,yytext);
                                          yyextra->sectionTitle.resize(0);
                                          BEGIN(SectionTitle);
                                        }
<SectionLabel>{DOCNL} { // missing argument
                                          warn(yyextra->fileName,yyextra->lineNr,
                                              "\\section command has no label"
                                              );
                                          if (*yytext=='\n') yyextra->lineNr++;
                                          addOutput(yyscanner,'\n');
                                          BEGIN(Comment);
                                        }
<SectionLabel>. { // invalid character for section label
                                          warn(yyextra->fileName,yyextra->lineNr,
                                              "Invalid or missing section label"
                                              );
                                          BEGIN(Comment);
                                        }
<SectionTitle>{STAopt}/"\n" { // end of section title
                                          addSection(yyscanner);
                                          addOutput(yyscanner,yytext);
                                          BEGIN(Comment);
                                        }
<SectionTitle>{STopt}/"\\ilinebr" { // end of section title
                                          addSection(yyscanner);
                                          addOutput(yyscanner,yytext);
                                          BEGIN(Comment);
                                        }
<SectionTitle>{LC} { // line continuation
                                          yyextra->lineNr++;
                                          addOutput(yyscanner,'\n');
                                        }
<SectionTitle>[^\n@\\]* { // any character without special meaning
                                          yyextra->sectionTitle+=yytext;
                                          addOutput(yyscanner,yytext);
                                        }
<SectionTitle>({CMD}{CMD}){ID} { // unescape escaped command
                                          yyextra->sectionTitle+=&yytext[1];
                                          addOutput(yyscanner,yytext);
                                        }
<SectionTitle>{CMD}[$@\\&~<>#%] { // unescape escaped character
                                          yyextra->sectionTitle+=yytext[1];
                                          addOutput(yyscanner,yytext);
                                        }
<SectionTitle>. { // anything else
                                          yyextra->sectionTitle+=yytext;
                                          addOutput(yyscanner,*yytext);
                                        }
  /* ----- handle arguments of the subpage command ------- */
<SubpageLabel>{LABELID} { // first argument
                                          addOutput(yyscanner,yytext);
                                          // we add subpage labels as a kind of "inheritance" relation to prevent
                                          // needing to add another list to the Entry class.
                                          yyextra->current->extends.push_back(BaseInfo(QCString(yytext),Public,Normal));
                                          BEGIN(SubpageTitle);
                                        }
<SubpageLabel>{DOCNL} { // missing argument
                                          warn(yyextra->fileName,yyextra->lineNr,
                                              "\\subpage command has no label"
                                              );
                                          if (*yytext=='\n') yyextra->lineNr++;
                                          addOutput(yyscanner,'\n');
                                          BEGIN(Comment);
                                        }
<SubpageLabel>. {
                                          unput(yytext[0]);
                                          BEGIN(Comment);
                                        }
<SubpageTitle>{DOCNL} { // no title, end command
                                          addOutput(yyscanner,yytext);
                                          BEGIN(Comment);
                                        }
<SubpageTitle>[ \t]*"\""[^\"\n]*"\"" { // add title, end of command
                                          addOutput(yyscanner,yytext);
                                          BEGIN(Comment);
                                        }
<SubpageTitle>. { // no title, end of command
                                          unput(*yytext);
                                          BEGIN(Comment);
                                        }
  /* ----- handle arguments of the anchor command ------- */
<AnchorLabel>{LABELID} { // found argument
                                          addAnchor(yyscanner,QCString(yytext));
                                          addOutput(yyscanner,yytext);
                                          BEGIN(Comment);
                                        }
<AnchorLabel>{DOCNL} { // missing argument
                                          warn(yyextra->fileName,yyextra->lineNr,
                                              "\\anchor command has no label"
                                              );
                                          if (*yytext=='\n') yyextra->lineNr++;
                                          addOutput(yyscanner,'\n');
                                          BEGIN(Comment);
                                        }
<AnchorLabel>. { // invalid character for anchor label
                                          warn(yyextra->fileName,yyextra->lineNr,
                                              "Invalid or missing anchor label"
                                              );
                                          BEGIN(Comment);
                                        }
  /* ----- handle arguments of the preformatted block commands ------- */
<FormatBlock>{CMD}("endverbatim"|"endiverbatim"|"endiliteral"|"endlatexonly"|"endhtmlonly"|"endxmlonly"|"enddocbookonly"|"endrtfonly"|"endmanonly"|"enddot"|"endcode"|"endicode"|"endmsc")/{NW} { // possible ends
                                          addOutput(yyscanner,yytext);
                                          if (&yytext[4]==yyextra->blockName) // found end of the block
                                          {
                                              BEGIN(Comment);
                                          }
                                        }
<FormatBlock>{CMD}"enduml" {
                                          addOutput(yyscanner,yytext);
                                          if (yyextra->blockName=="startuml") // found end of the block
                                          {
                                              BEGIN(Comment);
                                          }
                                        }
<FormatBlock>[^ \@\*\/\\\n]* { // some word
                                          addOutput(yyscanner,yytext);
                                        }
<FormatBlock>{DOCNL} { // new line
                                          if (*yytext=='\n') yyextra->lineNr++;
                                          addOutput(yyscanner,'\n');
                                        }
<FormatBlock>{CCS} { // start of a C-comment
                                          if (!(yyextra->blockName=="code" || yyextra->blockName=="verbatim" ||
                                                yyextra->blockName=="icode" || yyextra->blockName=="iverbatim"||
                                                yyextra->blockName=="iliteral"
                                               )
                                             ) yyextra->commentCount++;
                                          addOutput(yyscanner,yytext);
                                        }
<FormatBlock>{CCE} { // end of a C-comment
                                          addOutput(yyscanner,yytext);
                                          if (!(yyextra->blockName=="code" || yyextra->blockName=="verbatim" ||
                                                yyextra->blockName=="icode" || yyextra->blockName=="iverbatim"||
                                                yyextra->blockName=="iliteral"
                                               )
                                             )
                                          {
                                            yyextra->commentCount--;
                                            if (yyextra->commentCount<0)
                                            {
                                              QCString endTag = "end"+yyextra->blockName;
                                              if (yyextra->blockName=="startuml") endTag="enduml";
                                              warn(yyextra->fileName,yyextra->lineNr,
                                                 "found */ without matching /* while inside a \\%s block! Perhaps a missing \\%s?\n",qPrint(yyextra->blockName),qPrint(endTag));
                                            }
                                          }
                                        }
<FormatBlock>. {
                                          addOutput(yyscanner,*yytext);
                                        }
<FormatBlock><<EOF>> {
                                          QCString endTag = "end"+yyextra->blockName;
                                          if (yyextra->blockName=="startuml") endTag="enduml";
                                          warn(yyextra->fileName,yyextra->lineNr,
                                            "reached end of comment while inside a \\%s block; check for missing \\%s tag!",
                                            qPrint(yyextra->blockName),qPrint(endTag)
                                          );
                                          yyterminate();
                                        }
  /* ----- handle arguments of if/ifnot commands ------- */
<GuardParam>{B}*"(" {
                                          yyextra->guardExpr=yytext;
                                          yyextra->roundCount=1;
                                          BEGIN(GuardExpr);
                                        }
<GuardExpr>[^()]* {
                                          yyextra->guardExpr+=yytext;
                                          lineCount(yyscanner);
                                        }
<GuardExpr>"(" {
                                          yyextra->guardExpr+=yytext;
                                          yyextra->roundCount++;
                                        }
<GuardExpr>")" {
                                          yyextra->guardExpr+=yytext;
                                          yyextra->roundCount--;
                                          if (yyextra->roundCount==0)
                                          {
                                            handleGuard(yyscanner,yyextra->guardExpr);
                                          }
                                        }
<GuardExpr>\n {
                                          warn(yyextra->fileName,yyextra->lineNr,
                                                "invalid expression '%s' for yyextra->guards",qPrint(yyextra->guardExpr));
                                          unput(*yytext);
                                          BEGIN(GuardParam);
                                        }
<GuardParam>{B}*[a-z_A-Z0-9.\-]+ { // parameter of if/ifnot yyextra->guards
                                          handleGuard(yyscanner,QCString(yytext));
                                        }
<GuardParam>{DOCNL} { // end of argument
                                          if (*yytext=='\n') yyextra->lineNr++;
                                          //next line is commented out due to bug620924
                                          //addOutput(yyscanner,'\n');
                                          addIlineBreak(yyscanner,yyextra->lineNr);
                                          BEGIN(Comment);
                                        }
<GuardParam>{LC} { // line continuation
                                          yyextra->lineNr++;
                                          addOutput(yyscanner,'\n');
                                        }
<GuardParam>. { // ignore other stuff
                                          addOutput(yyscanner,*yytext);
                                        }
<GuardParamEnd>{B}*{DOCNL} {
                                          lineCount(yyscanner);
                                          yyextra->spaceBeforeIf.resize(0);
                                          addIlineBreak(yyscanner,yyextra->lineNr);
                                          BEGIN(Comment);
                                        }
<GuardParamEnd>{B}* {
                                          if (!yyextra->spaceBeforeIf.isEmpty()) // needed for 665313 in combination with bug620924
                                          {
                                            addOutput(yyscanner,yyextra->spaceBeforeIf);
                                          }
                                          yyextra->spaceBeforeIf.resize(0);
                                          addIlineBreak(yyscanner,yyextra->lineNr);
                                          BEGIN(Comment);
                                        }
<GuardParamEnd>. {
                                          unput(*yytext);
                                          addIlineBreak(yyscanner,yyextra->lineNr);
                                          BEGIN(Comment);
                                        }
  /* ----- handle skipping of conditional sections ------- */
<SkipGuardedSection>{CMD}"ifnot"/{NW} {
                                          yyextra->guardType = Guard_IfNot;
                                          BEGIN(GuardParam);
                                        }
<SkipGuardedSection>{CMD}"if"/{NW} {
                                          yyextra->guardType = Guard_If;
                                          BEGIN(GuardParam);
                                        }
<SkipGuardedSection>{CMD}"endif"/{NW} {
                                          if (yyextra->guards.empty())
                                          {
                                            warn(yyextra->fileName,yyextra->lineNr,
                                                "found \\endif without matching start command");
                                          }
                                          else
                                          {
                                            GuardedSection s = yyextra->guards.top();
                                            yyextra->guards.pop();
                                            bool parentVisible = s.parentVisible();
                                            if (parentVisible)
                                            {
                                              yyextra->enabledSectionFound=TRUE;
                                              BEGIN(GuardParamEnd);
                                            }
                                          }
                                        }
<SkipGuardedSection>{CMD}"else"/{NW} {
                                          if (yyextra->guards.empty())
                                          {
                                            warn(yyextra->fileName,yyextra->lineNr,
                                                "found \\else without matching start command");
                                          }
                                          else
                                          {
                                            if (!yyextra->enabledSectionFound && yyextra->guards.top().parentVisible())
                                            {
                                              yyextra->guards.pop();
                                              yyextra->guards.push(GuardedSection(TRUE,TRUE));
                                              yyextra->enabledSectionFound=TRUE;
                                              BEGIN(GuardParamEnd);
                                            }
                                          }
                                        }
<SkipGuardedSection>{CMD}"elseif"/{NW} {
                                          if (yyextra->guards.empty())
                                          {
                                            warn(yyextra->fileName,yyextra->lineNr,
                                                "found \\elseif without matching start command");
                                          }
                                          else
                                          {
                                            if (!yyextra->enabledSectionFound && yyextra->guards.top().parentVisible())
                                            {
                                              yyextra->guardType=Guard_If;
                                              yyextra->guards.pop();
                                              BEGIN(GuardParam);
                                            }
                                          }
                                        }
<SkipGuardedSection>{DOCNL} { // skip line
                                          if (*yytext=='\n') yyextra->lineNr++;
                                          //addOutput(yyscanner,'\n');
                                        }
<SkipGuardedSection>[^ \\@\n]+ { // skip non-special characters
                                        }
<SkipGuardedSection>. { // any other character
                                        }
  /* ----- handle skipping of internal section ------- */
<SkipInternal>{DOCNL} { // skip line
                                          if (*yytext=='\n') yyextra->lineNr++;
                                          addOutput(yyscanner,'\n');
                                        }
<SkipInternal>[@\\]"if"/[ \t] {
                                          yyextra->condCount++;
                                          }
<SkipInternal>[@\\]"ifnot"/[ \t] {
                                          yyextra->condCount++;
                                        }
<SkipInternal>[@\\]/"endif" {
                                          yyextra->condCount--;
                                          if (yyextra->condCount<0) // handle conditional section around of \internal, see bug607743
                                          {
                                            unput('\\');
                                            BEGIN(Comment);
                                          }
                                        }
<SkipInternal>[@\\]/"section"[ \t] {
                                          if (yyextra->sectionLevel>0)
                                          {
                                            unput('\\');
                                            BEGIN(Comment);
                                          }
                                        }
<SkipInternal>[@\\]/"subsection"[ \t] {
                                          if (yyextra->sectionLevel>1)
                                          {
                                            unput('\\');
                                            BEGIN(Comment);
                                          }
                                        }
<SkipInternal>[@\\]/"subsubsection"[ \t] {
                                          if (yyextra->sectionLevel>2)
                                          {
                                            unput('\\');
                                            BEGIN(Comment);
                                          }
                                        }
<SkipInternal>[@\\]/"paragraph"[ \t] {
                                          if (yyextra->sectionLevel>3)
                                          {
                                            unput('\\');
                                            BEGIN(Comment);
                                          }
                                        }
<SkipInternal>[@\\]"endinternal"[ \t]* {
                                          BEGIN(Comment);
                                        }
<SkipInternal>[^ \\@\n]+ { // skip non-special characters
                                        }
<SkipInternal>. { // any other character
                                        }
  /* ----- handle argument of name command ------- */
<NameParam>{DOCNL} { // end of argument
                                          //if (*yytext=='\n') yyextra->lineNr++;
                                          //addOutput(yyscanner,'\n');
                                          unput_string(yytext,yyleng);
                                          BEGIN(Comment);
                                        }
<NameParam>{LC} { // line continuation
                                          yyextra->lineNr++;
                                          addOutput(yyscanner,'\n');
                                          yyextra->docGroup.appendHeader(' ');
                                        }
<NameParam>. { // ignore other stuff
                                          yyextra->docGroup.appendHeader(*yytext);
                                          yyextra->current->name+=*yytext;
                                        }
  /* ----- handle argument of noop command ------- */
<Noop>{DOCNL} { // end of argument
                                          if (*yytext=='\n')
                                          {
                                            yyextra->lineNr++;
                                            addOutput(yyscanner,'\n');
                                          }
                                          BEGIN(Comment);
                                        }
<Noop>. { // ignore other stuff
                                        }
  /* ----- handle argument of raisewarning command ------- */
<RaiseWarning>{DOCNL} { // end of argument
                                          warn_doc_error(yyextra->fileName,yyextra->lineNr,
                                                         "%s",qPrint(yyextra->raiseWarning));
                                          yyextra->raiseWarning = "";
                                          if (*yytext=='\n') yyextra->lineNr++;
                                          addOutput(yyscanner,'\n');
                                          BEGIN(Comment);
                                        }
<RaiseWarning>. { // ignore other stuff
                                          yyextra->raiseWarning += yytext;
                                        }
  /* ----- handle argument of ingroup command ------- */
<InGroupParam>{LABELID} { // group id
                                          yyextra->current->groups.push_back(
                                             Grouping(QCString(yytext), Grouping::GROUPING_INGROUP)
                                          );
                                          yyextra->inGroupParamFound=TRUE;
                                        }
<InGroupParam>{DOCNL} { // missing argument
                                          if (!yyextra->inGroupParamFound)
                                          {
                                             warn(yyextra->fileName,yyextra->lineNr,
                                                "Missing group name for \\ingroup command"
                                                );
                                          }
                                          //if (*yytext=='\n') yyextra->lineNr++;
                                          //addOutput(yyscanner,'\n');
                                          unput_string(yytext,yyleng);
                                          BEGIN(Comment);
                                        }
<InGroupParam>{LC} { // line continuation
                                          yyextra->lineNr++;
                                          addOutput(yyscanner,'\n');
                                        }
<InGroupParam>. { // ignore other stuff
                                          addOutput(yyscanner,*yytext);
                                        }
  /* ----- handle argument of fn command ------- */
<FnParam>{DOCNL} { // end of argument
                                          if (yyextra->braceCount==0)
                                          {
                                            //if (*yytext=='\n') yyextra->lineNr++;
                                            //addOutput(yyscanner,'\n');
                                            unput_string(yytext,yyleng);
                                            yyextra->langParser->parsePrototype(yyextra->functionProto);
                                            BEGIN(Comment);
                                          }
                                        }
<FnParam>{LC} { // line continuation
                                          yyextra->lineNr++;
                                          yyextra->functionProto+=' ';
                                        }
<FnParam>[^@\\\n()]+ { // non-special characters
                                          yyextra->functionProto+=yytext;
                                        }
<FnParam>"(" {
                                          yyextra->functionProto+=yytext;
                                          yyextra->braceCount++;
                                        }
<FnParam>")" {
                                          yyextra->functionProto+=yytext;
                                          yyextra->braceCount--;
                                        }
<FnParam>. { // add other stuff
                                          yyextra->functionProto+=*yytext;
                                        }
  /* ----- handle argument of overload command ------- */
<OverloadParam>{DOCNL} { // end of argument
                                          if (*yytext=='\n') yyextra->lineNr++;
                                          if (yyextra->functionProto.stripWhiteSpace().isEmpty())
                                          { // plain overload command
                                            addOutput(yyscanner,getOverloadDocs());
                                            addOutput(yyscanner,'\n');
                                          }
                                          else // overload declaration
                                          {
                                            makeStructuralIndicator(yyscanner,Entry::OVERLOADDOC_SEC);
                                            yyextra->langParser->parsePrototype(yyextra->functionProto);
                                          }
                                          BEGIN(Comment);
                                        }
<OverloadParam>{LC} { // line continuation
                                          yyextra->lineNr++;
                                          yyextra->functionProto+=' ';
                                        }
<OverloadParam>. { // add other stuff
                                          yyextra->functionProto+=*yytext;
                                        }
  /* ----- handle argument of inherit command ------- */
<InheritParam>({ID}("::"|"."))*{ID} { // found argument
                                          yyextra->current->extends.push_back(
                                            BaseInfo(removeRedundantWhiteSpace(QCString(yytext)),Public,Normal)
                                          );
                                          BEGIN(Comment);
                                        }
<InheritParam>{DOCNL} { // missing argument
                                          warn(yyextra->fileName,yyextra->lineNr,
                                              "\\inherit command has no argument"
                                              );
                                          if (*yytext=='\n') yyextra->lineNr++;
                                          addOutput(yyscanner,'\n');
                                          BEGIN(Comment);
                                        }
<InheritParam>. { // invalid character for anchor label
                                          warn(yyextra->fileName,yyextra->lineNr,
                                              "Invalid or missing name for \\inherit command"
                                              );
                                          BEGIN(Comment);
                                        }
  /* ----- handle argument of extends and implements commands ------- */
<ExtendsParam>({ID}("::"|"."))*{ID} { // found argument
                                          yyextra->current->extends.push_back(
                                            BaseInfo(removeRedundantWhiteSpace(QCString(yytext)),Public,Normal)
                                          );
                                          BEGIN(Comment);
                                        }
<ExtendsParam>{DOCNL} { // missing argument
                                          warn(yyextra->fileName,yyextra->lineNr,
                                              "'\\%s' command has no argument",qPrint(yyextra->currentCmd)
                                              );
                                          //if (*yytext=='\n') yyextra->lineNr++;
                                          //addOutput(yyscanner,'\n');
                                          unput_string(yytext,yyleng);
                                          BEGIN(Comment);
                                        }
<ExtendsParam>. { // ignore other stuff
                                        }
  /* ----- handle language specific sections ------- */
<SkipLang>[\\@]"~"[a-zA-Z-]* { /* language switch */
                                          QCString langId(&yytext[2]);
                                          if (!langId.isEmpty() && !Config_isAvailableEnum(OUTPUT_LANGUAGE,langId))
                                          {
                                             warn(yyextra->fileName,yyextra->lineNr,
                                             "non supported language '%s' specified in '%s'",langId.data(),QCString(yytext).stripWhiteSpace().data());
                                          }
                                          else if (langId.isEmpty() ||
                                              qstricmp(Config_getEnumAsString(OUTPUT_LANGUAGE),langId)==0)
                                          { // enable language specific section
                                            BEGIN(Comment);
                                          }
                                        }
<SkipLang>[^*@\\\n]* { /* any character not a *, @, backslash or new line */
                                        }
<SkipLang>{DOCNL} { /* new line in verbatim block */
                                          if (*yytext=='\n') yyextra->lineNr++;
                                        }
<SkipLang>. { /* any other character */
                                        }
  /* ----- handle arguments of the cite command ------- */
<CiteLabel>{CITEID} { // found argument
                                          addCite(yyscanner);
                                          addOutput(yyscanner,yytext);
                                          BEGIN(Comment);
                                        }
<CiteLabel>{DOCNL} { // missing argument
                                          warn(yyextra->fileName,yyextra->lineNr,
                                              "\\cite command has no label"
                                              );
                                          //if (*yytext=='\n') yyextra->lineNr++;
                                          //addOutput(yyscanner,'\n');
                                          unput_string(yytext,yyleng);
                                          BEGIN(Comment);
                                        }
<CiteLabel>. { // invalid character for cite label
                                           warn(yyextra->fileName,yyextra->lineNr,
                                              "Invalid or missing cite label"
                                              );
                                          BEGIN(Comment);
                                        }
  /* ----- handle argument of the copydoc command ------- */
<CopyDoc><<EOF>> {
                                          setOutput(yyscanner,OutputDoc);
                                          addOutput(yyscanner," \\ilinebr\\ilinebr\\copydetails ");
                                          addOutput(yyscanner,yyextra->copyDocArg);
                                          addOutput(yyscanner,"\n");
                                          BEGIN(Comment);
                                        }
<CopyDoc>{DOCNL} {
                                          if (*yytext=='\n') yyextra->lineNr++;
                                          if (yyextra->braceCount==0)
                                          {
                                            setOutput(yyscanner,OutputDoc);
                                            addOutput(yyscanner," \\ilinebr\\ilinebr\\copydetails ");
                                            addOutput(yyscanner,yyextra->copyDocArg);
                                            addOutput(yyscanner,"\n");
                                            BEGIN(Comment);
                                          }
                                        }
<CopyDoc>{LC} { // line continuation
                                          yyextra->lineNr++;
                                        }
<CopyDoc>[^@\\\n()]+ { // non-special characters
                                          yyextra->copyDocArg+=yytext;
                                          addOutput(yyscanner,yytext);
                                        }
<CopyDoc>"(" {
                                          yyextra->copyDocArg+=yytext;
                                          addOutput(yyscanner,yytext);
                                          yyextra->braceCount++;
                                        }
<CopyDoc>")" {
                                          yyextra->copyDocArg+=yytext;
                                          addOutput(yyscanner,yytext);
                                          yyextra->braceCount--;
                                        }
<CopyDoc>. {
                                          yyextra->copyDocArg+=yytext;
                                          addOutput(yyscanner,yytext);
                                        }
 /*
<*>. { fprintf(stderr,"Lex scanner %s %sdefault rule for state %s: #%s#\n", __FILE__,!yyextra->fileName.isEmpty() ? ("(" + yyextra->fileName +") ").data(): "",stateToString(YY_START),yytext);}
<*>\n { fprintf(stderr,"Lex scanner %s %sdefault rule newline for state %s.\n", __FILE__, !yyextra->fileName.isEmpty() ? ("(" + yyextra->fileName +") ").data(): "",stateToString(YY_START));}
 */
%%
yyread()
static int yyread (yyscan_t yyscanner, char * buf, int max_size) [static]
Definition at line 3610 of file commentscan.l.
{
  struct yyguts_t *yyg = (struct yyguts_t*)yyscanner;
  yyextra->prevPosition=yyextra->inputPosition;
  int c=0;
  while(c < max_size && yyextra->inputString[yyextra->inputPosition])
  {
    *buf = yyextra->inputString[yyextra->inputPosition++] ;
    //printf("%d (%c)\n",*buf,*buf);
    c++; buf++;
  }
  return c;
}
References c.
Variable Documentation
docCmdMap
const std::map< std::string, DocCmdMap > docCmdMap [static]
Definition at line 173 of file commentscan.l.
g_citeMutex
std::mutex g_citeMutex [static]
Definition at line 439 of file commentscan.l.
Referenced by addCite().
g_formulaMutex
std::mutex g_formulaMutex [static]
Definition at line 438 of file commentscan.l.
Referenced by addFormula().
g_sectionMutex
std::mutex g_sectionMutex [static]
Definition at line 437 of file commentscan.l.
Referenced by addAnchor(), addSection(), and addXRefItem().