doxygen/src/portable_c.c File Reference
#include <iconv.h>
Functions
void * portable_iconv_open (const char *tocode, const char *fromcode)
size_t portable_iconv (void *cd, const char **inbuf, size_t *inbytesleft, char **outbuf, size_t *outbytesleft)
int portable_iconv_close (void *cd)
Function Documentation
portable_iconv()
size_t portable_iconv (void * cd, const char ** inbuf, size_t * inbytesleft, char ** outbuf, size_t * outbytesleft)
Definition at line 24 of file portable_c.c.
{
  return iconv((iconv_t)cd,(char**)inbuf,inbytesleft,outbuf,outbytesleft);
}
References iconv.
Referenced by configStringRecode(), encodeForOutput(), HtmlHelpRecoder::recode(), TemplateContextImpl::recode(), Portable::recodeUtf8StringToW(), transcodeCharacterBuffer(), and transcodeCharacterStringToUTF8().
portable_iconv_close()
int portable_iconv_close (void * cd)
Definition at line 30 of file portable_c.c.
{
  return iconv_close((iconv_t)cd);
}
References iconv_close.
Referenced by adjustConfiguration(), configStringRecode(), encodeForOutput(), HtmlHelpRecoder::finalize(), Portable::recodeUtf8StringToW(), TemplateContextImpl::setEncoding(), transcodeCharacterBuffer(), and transcodeCharacterStringToUTF8().
portable_iconv_open()
void * portable_iconv_open (const char * tocode, const char * fromcode)
Definition at line 19 of file portable_c.c.
{
  return iconv_open(tocode,fromcode);
}
References iconv_open.
Referenced by adjustConfiguration(), configStringRecode(), encodeForOutput(), HtmlHelpRecoder::initialize(), Portable::recodeUtf8StringToW(), TemplateContextImpl::setEncoding(), transcodeCharacterBuffer(), and transcodeCharacterStringToUTF8().