doxygen/src/diagram.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <fstream>
#include <algorithm>
#include `diagram.h`
#include `image.h`
#include `classdef.h`
#include `config.h`
#include `message.h`
#include `util.h`
#include `doxygen.h`
#include `portable.h`
#include `indexlist.h`
#include `classlist.h`
#include `textstream.h`
Classes
class DiagramItem
class DiagramRow
class TreeDiagram
class DualDirIterator< C, I >
helper class representing an iterator that can iterate forwards or backwards
struct ClassDiagram::Private
Macros
#define IMAGE_EXT `.png`
Typedefs
using DiagramItemList = std::vector< DiagramItem * >
Functions
static uint protToMask (Protection p)
static uchar protToColor (Protection p)
static QCString protToString (Protection p)
static uint virtToMask (Specifier p)
static Protection getMinProtectionLevel (const DiagramItemList &dil)
static void writeBitmapBox (DiagramItem *di, Image *image, uint x, uint y, uint w, uint h, bool firstRow, bool hasDocs, bool children=FALSE)
static void writeVectorBox (TextStream &t, DiagramItem *di, float x, float y, bool children=FALSE)
static void writeMapArea (TextStream &t, const ClassDef *cd, QCString relPath, uint x, uint y, uint w, uint h)
Variables
const uint maxTreeWidth = 8
const uint gridWidth = 100
const uint gridHeight = 100
const uint labelHorSpacing = 10
const uint labelVertSpacing = 32
const uint labelHorMargin = 6
const uint fontHeight = 12
Macro Definition Documentation
IMAGE_EXT
#define IMAGE_EXT `.png`
Typedef Documentation
DiagramItemList
using DiagramItemList = std::vector<DiagramItem*>
Definition at line 37 of file diagram.cpp.
Function Documentation
getMinProtectionLevel()
static Protection getMinProtectionLevel (const DiagramItemList & dil) [static]
Definition at line 197 of file diagram.cpp.
{
  auto it = dil.begin();
  Protection result = Private;
  if (it!=dil.end())
  {
    result=(*it)->protection();
    for (++it;it!=dil.end();++it)
    {
      Protection p=(*it)->protection();
      if (p!=result)
      {
        if (result==Protected && p==Public) result=p;
        else if (result==Private) result=p;
      }
    }
  }
  return result;
}
References p, Private, Protected, and Public.
protToColor()
static uchar protToColor (Protection p) [static]
Definition at line 161 of file diagram.cpp.
{
  switch(p)
  {
    case Public: return 6;
    case Package: // package is not possible!
    case Protected: return 5;
    case Private: return 4;
  }
  return 0;
}
References p, Package, Private, Protected, and Public.
protToMask()
static uint protToMask (Protection p) [static]
Definition at line 149 of file diagram.cpp.
{
  switch(p)
  {
    case Public: return 0xffffffff;
    case Package: // package is not possible!
    case Protected: return 0xcccccccc;
    case Private: return 0xaaaaaaaa;
  }
  return 0;
}
References p, Package, Private, Protected, and Public.
protToString()
static QCString protToString (Protection p) [static]
Definition at line 173 of file diagram.cpp.
{
  switch(p)
  {
    case Public: return "solid";
    case Package: // package is not possible!
    case Protected: return "dashed";
    case Private: return "dotted";
  }
  return QCString();
}
References p, Package, Private, Protected, and Public.
virtToMask()
static uint virtToMask (Specifier p) [static]
Definition at line 185 of file diagram.cpp.
{
  switch(p)
  {
    case Normal: return 0xffffffff;
    case Virtual: return 0xf0f0f0f0;
    default: break;
  }
  return 0;
}
References Normal, p, and Virtual.
Referenced by writeBitmapBox().
writeBitmapBox()
static void writeBitmapBox (DiagramItem * di, Image * image, uint x, uint y, uint w, uint h, bool firstRow, bool hasDocs, bool children = FALSE) [static]
Definition at line 217 of file diagram.cpp.
{
  uchar colFill = hasDocs ? (firstRow ? 8 : 2) : 7;
  uchar colBorder = (firstRow || !hasDocs) ? 1 : 3;
  uint l = Image::stringLength(di->label());
  uint mask=virtToMask(di->virtualness());
  image->fillRect(x+1,y+1,w-2,h-2,colFill,mask);
  image->drawRect(x,y,w,h,colBorder,mask);
  image->writeString(x+(w-l)/2, y+(h-fontHeight)/2, di->label(),1);
  if (children)
  {
    uint i;
    for (i=0;i<5;i++)
    {
      image->drawHorzLine(y+h+i-6,x+w-2-i,x+w-2,firstRow?1:3,0xffffffff);
    }
  }
}
References Image::drawHorzLine(), Image::drawRect(), Image::fillRect(), fontHeight, h, DiagramItem::label(), Image::stringLength, virtToMask(), DiagramItem::virtualness(), w, Image::writeString(), x, and y.
writeMapArea()
static void writeMapArea (TextStream & t, const ClassDef * cd, QCString relPath, uint x, uint y, uint w, uint h) [static]
Definition at line 247 of file diagram.cpp.
{
  if (cd->isLinkable())
  {
    QCString ref=cd->getReference();
    t << "<area ";
    if (!ref.isEmpty())
    {
      t << externalLinkTarget(true);
    }
    t << "href=\"";
    t << externalRef(relPath,ref,TRUE);
    t << addHtmlExtensionIfMissing(cd->getOutputFileBase());
    if (!cd->anchor().isEmpty())
    {
      t << "#" << cd->anchor();
    }
    t << "\" ";
    QCString tooltip = cd->briefDescriptionAsTooltip();
    if (!tooltip.isEmpty())
    {
      t << "title=\"" << convertToHtml(tooltip) << "\" ";
    }
    t << "alt=\"" << convertToXML(cd->displayName());
    t << "\" shape=\"rect\" coords=\"" << x << "," << y << ",";
    t << (x+w) << "," << (y+h) << "\"/>\n";
  }
}
References addHtmlExtensionIfMissing(), ClassDef::anchor(), Definition::briefDescriptionAsTooltip(), convertToHtml(), convertToXML(), ClassDef::displayName(), externalLinkTarget(), externalRef(), ClassDef::getOutputFileBase(), ClassDef::getReference(), h, QCString::isEmpty(), ClassDef::isLinkable(), TRUE, w, x, and y.
writeVectorBox()
static void writeVectorBox (TextStream & t, DiagramItem * di, float x, float y, bool children = FALSE) [static]
Definition at line 238 of file diagram.cpp.
{
  if (di->virtualness()==Virtual) t << "dashed\n";
  t << " (" << convertToPSString(di->label()) << ") " << x << " " << y << " box\n";
  if (children) t << x << " " << y << " mark\n";
  if (di->virtualness()==Virtual) t << "solid\n";
}
References convertToPSString(), DiagramItem::label(), Virtual, DiagramItem::virtualness(), x, and y.
Variable Documentation
fontHeight
const uint fontHeight = 12
Definition at line 147 of file diagram.cpp.
gridHeight
const uint gridHeight = 100
Definition at line 142 of file diagram.cpp.
gridWidth
const uint gridWidth = 100
Definition at line 141 of file diagram.cpp.
labelHorMargin
const uint labelHorMargin = 6
Definition at line 146 of file diagram.cpp.
labelHorSpacing
const uint labelHorSpacing = 10
Definition at line 144 of file diagram.cpp.
labelVertSpacing
const uint labelVertSpacing = 32
Definition at line 145 of file diagram.cpp.
maxTreeWidth
const uint maxTreeWidth = 8
Definition at line 140 of file diagram.cpp.