doxygen/src/filedef.h File Reference
#include <set>
#include `definition.h`
#include `memberlist.h`
#include `containers.h`
Classes
struct IncludeInfo
class IncludeInfoList
class FileDef
class FileList
struct FilesInDir
Typedefs
using FileDefSet = std::set< const FileDef * >
Functions
bool compareFileDefs (const FileDef *fd1, const FileDef *fd2)
FileDef * createFileDef (const QCString &p, const QCString &n, const QCString &ref=QCString(), const QCString &dn=QCString())
FileDef * toFileDef (Definition *d)
const FileDef * toFileDef (const Definition *d)
Typedef Documentation
FileDefSet
using FileDefSet = std::set<const FileDef*>
Definition at line 44 of file filedef.h.
Function Documentation
compareFileDefs()
bool compareFileDefs (const FileDef * fd1, const FileDef * fd2)
Definition at line 1750 of file filedef.cpp.
{
  return qstricmp(fd1->name(),fd2->name()) < 0;
}
References FileDef::name(), and qstricmp().
Referenced by DirDefImpl::sort(), and writeFileIndex().
createFileDef()
FileDef * createFileDef (const QCString & p, const QCString & n, const QCString & ref = QCString(), const QCString & dn = QCString())
Definition at line 192 of file filedef.cpp.
{
  return new FileDefImpl(p,n,ref,dn);
}
References n, and p.
Referenced by DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), CCodeParser::parseCode(), FortranCodeParser::parseCode(), PythonCodeParser::parseCode(), VHDLCodeParser::parseCode(), LexCodeParser::parseCode(), SQLCodeParser::parseCode(), XMLCodeParser::parseCode(), readDir(), readFileOrDirectory(), and writeGraphInfo().
toFileDef() [1/2]
const FileDef * toFileDef (const Definition * d)
Definition at line 1770 of file filedef.cpp.
{
  if (d==0) return 0;
  if (d && typeid(*d)==typeid(FileDefImpl))
  {
    return static_cast<const FileDef*>(d);
  }
  else
  {
    return 0;
  }
}
toFileDef() [2/2]
FileDef * toFileDef (Definition * d)
Definition at line 1757 of file filedef.cpp.
{
  if (d==0) return 0;
  if (d && typeid(*d)==typeid(FileDefImpl))
  {
    return static_cast<FileDef*>(d);
  }
  else
  {
    return 0;
  }
}
Referenced by DocSets::addIndexItem(), NestingNodeContext::Private::addMembers(), NestingNodeContext::Private::createFile(), DefinitionContext< T >::createNavigationPath(), DocLink::DocLink(), DocRef::DocRef(), DefinitionContext< T >::fillPath(), SymbolResolver::Private::followPath(), generateJSTree(), FTVHelp::Private::generateTree(), DocParser::handleLinkedWord(), NamespaceDefImpl::insertMember(), MemberDefImpl::moveTo(), DefinitionImpl::navigationPathAsString(), node2URL(), SearchIndex::setCurrentDoc(), and SearchIndexExternal::setCurrentDoc().