doxygen/src/dotfilepatcher.cpp File Reference
#include <sstream>
#include `dotfilepatcher.h`
#include `dotrunner.h`
#include `config.h`
#include `message.h`
#include `docparser.h`
#include `docnode.h`
#include `doxygen.h`
#include `util.h`
#include `dot.h`
#include `dir.h`
Functions
static QCString replaceRef (const QCString &buf, const QCString &relPath, bool urlOnly, const QCString &context, const QCString &target=QCString())
static bool readSVGSize (const QCString &fileName, int *width, int *height)
static void writeSVGNotSupported (TextStream &out)
Variables
static const char svgZoomHeader []
static const char svgZoomFooter []
Function Documentation
readSVGSize()
static bool readSVGSize (const QCString & fileName, int * width, int * height) [static]
Definition at line 508 of file dotfilepatcher.cpp.
{
  bool found=FALSE;
  std::ifstream f(fileName.str(),std::ifstream::in);
  if (!f.is_open())
  {
    return false;
  }
  std::string line;
  while (getline(f,line) && !found)
  {
    if (qstrncmp(line.c_str(),"<!--zoomable ",13)==0)
    {
      *width=-1;
      *height=-1;
      sscanf(line.c_str(),"<!--zoomable %d",height);
      found=true;
    }
    else if (sscanf(line.c_str(),"<svg width=\"%dpt\" height=\"%dpt\"",width,height)==2)
    {
      found=true;
    }
  }
  return true;
}
References f, FALSE, found, qstrncmp(), QCString::str(), and string.
replaceRef()
static QCString replaceRef (const QCString & buf, const QCString & relPath, bool urlOnly, const QCString & context, const QCString & target = QCString()) [static]
Definition at line 127 of file dotfilepatcher.cpp.
{
  // search for href="...", store ... part in link
  QCString href = "href";
  //bool isXLink=FALSE;
  int len = 6;
  int indexS = buf.find("href=\""), indexE;
  bool targetAlreadySet = buf.find("target=")!=-1;
  if (indexS>5 && buf.find("xlink:href=\"")!=-1) // XLink href (for SVG)
  {
    indexS-=6;
    len+=6;
    href.prepend("xlink:");
    //isXLink=TRUE;
  }
  if (indexS>=0 && (indexE=buf.find('"',indexS+len))!=-1)
  {
    QCString link = buf.mid(indexS+len,indexE-indexS-len);
    QCString result;
    if (urlOnly) // for user defined dot graphs
    {
      if (link.startsWith("\\ref ") || link.startsWith("@ref ")) // \ref url
      {
        result=href+"=\"";
        // fake ref node to resolve the url
        auto parser { createDocParser() };
        auto dfAst { createRef(*parser.get(), link.mid(5), context) };
        auto dfAstImpl = dynamic_cast<const DocNodeAST*>(dfAst.get());
        const DocRef *df = std::get_if<DocRef>(&dfAstImpl->root);
        result+=externalRef(relPath,df->ref(),TRUE);
        if (!df->file().isEmpty())
          result += addHtmlExtensionIfMissing(df->file());
        if (!df->anchor().isEmpty())
          result += "#" + df->anchor();
        result += "\"";
      }
      else
      {
        result = href+"=\"" + link + "\"";
      }
    }
    else // ref$url (external ref via tag file), or $url (local ref)
    {
      int marker = link.find('$');
      if (marker!=-1)
      {
        QCString ref = link.left(marker);
        QCString url = link.mid(marker+1);
        if (!ref.isEmpty())
        {
          result = externalLinkTarget(true);
          if (!result.isEmpty())targetAlreadySet=true;
        }
        result+= href+"=\"";
        result+=externalRef(relPath,ref,TRUE);
        result+= url + "\"";
      }
      else // should not happen, but handle properly anyway
      {
        result = href+"=\"" + link + "\"";
      }
    }
    if (!target.isEmpty() && !targetAlreadySet)
    {
      result+=" target=\""+target+"\"";
    }
    QCString leftPart = buf.left(indexS);
    QCString rightPart = buf.mid(indexE+1);
    //printf("replaceRef(\n'%s'\n)->\n'%s+%s+%s'\n",
    // qPrint(buf),qPrint(leftPart),qPrint(result),qPrint(rightPart));
    return leftPart + result + rightPart;
  }
  else
  {
    return buf;
  }
}
References addHtmlExtensionIfMissing(), DocRef::anchor(), createDocParser(), createRef(), externalLinkTarget(), externalRef(), DocRef::file(), QCString::find(), QCString::isEmpty(), QCString::left(), len, QCString::mid(), QCString::prepend(), DocRef::ref(), QCString::startsWith(), TRUE, and setup::url.
writeSVGNotSupported()
static void writeSVGNotSupported (TextStream & out) [static]
Definition at line 534 of file dotfilepatcher.cpp.
{
  out << "<p><b>This browser is not able to show SVG: try Firefox, Chrome, Safari, or Opera instead.</b></p>";
}
References out.
Variable Documentation
svgZoomFooter
const char svgZoomFooter[] [static]
Definition at line 73 of file dotfilepatcher.cpp.
svgZoomHeader
const char svgZoomHeader[] [static]
Definition at line 29 of file dotfilepatcher.cpp.