doxygen/src/docnode.h File Reference
#include <stdio.h>
#include <vector>
#include <memory>
#include <variant>
#include `qcstring.h`
#include `docvisitor.h`
#include `docparser.h`
#include `htmlattrib.h`
#include `htmlentity.h`
#include `growvector.h`
Classes
class DocNode
struct DocNodeList
class DocCompoundNode
class DocWord
class DocLinkedWord
class DocURL
class DocLineBreak
class DocHorRuler
class DocAnchor
class DocCite
class DocStyleChange
class DocSymbol
class DocEmoji
class DocWhiteSpace
class DocSeparator
class DocVerbatim
struct DocVerbatim::Private
class DocInclude
class DocIncOperator
class DocFormula
class DocIndexEntry
class DocAutoList
class DocAutoListItem
class DocTitle
class DocXRefItem
class DocImage
struct DocImage::Private
class DocDiagramFileBase
struct DocDiagramFileBase::Private
class DocDotFile
class DocMscFile
class DocDiaFile
class DocVhdlFlow
class DocLink
class DocRef
class DocInternalRef
class DocHRef
class DocHtmlSummary
class DocHtmlDetails
class DocHtmlHeader
class DocHtmlDescTitle
class DocHtmlDescList
class DocSection
class DocSecRefItem
class DocSecRefList
class DocInternal
class DocParBlock
class DocSimpleList
class DocHtmlList
class DocSimpleSect
class DocSimpleSectSep
class DocParamSect
class DocPara
class DocParamList
class DocSimpleListItem
class DocHtmlListItem
class DocHtmlDescData
class DocHtmlCell
class DocHtmlCaption
class DocHtmlRow
class DocHtmlTable
class DocHtmlBlockQuote
class DocText
class DocRoot
struct details::Impl< T, Ts >
struct details::Impl< T >
class DocNodeAST
Namespaces
namespace details
Macros
#define DOC_NODES
#define DN(x) class x;
#define DN_SEP
#define DN(x) x
#define DN_SEP ,
#define DN(x) constexpr const char *docNodeName(const x &n) { return #x; }
#define DN_SEP
#define DN(x) #x
#define DN_SEP ,
#define DN(x) #x
#define DN_SEP ,
#define DN(x) sizeof(x)
#define DN_SEP ,
Typedefs
using DocNodeVariant = std::variant< DOC_NODES >
Functions
constexpr DocNodeVariant * parent (DocNodeVariant *n)
returns the parent node of a given node n or 0 if the node has no parent.
constexpr const DocNodeVariant * parent (const DocNodeVariant *n)
returns the parent node of a given node n or 0 if the node has no parent.
template<class... Ts>
constexpr bool holds_one_of_alternatives (const DocNodeVariant &v)
returns true iff v holds one of types passed as template parameters
const char * docNodeName (const DocNodeVariant &v)
void dumpDocNodeSizes ()
void dumpDocNodeList (const DocNodeList &children)
Macro Definition Documentation
DN [1/6]
#define DN(x) class x;
Definition at line 1350 of file docnode.h.
DN [2/6]
#define DN(x) x
Definition at line 1350 of file docnode.h.
DN [3/6]
#define DN(x) constexpr const char *docNodeName(const x &n) { return #x; }
Definition at line 1350 of file docnode.h.
DN [4/6]
#define DN(x) #x
Definition at line 1350 of file docnode.h.
DN [5/6]
#define DN(x) #x
Definition at line 1350 of file docnode.h.
DN [6/6]
#define DN(x) sizeof(x)
Definition at line 1350 of file docnode.h.
DN_SEP [1/6]
#define DN_SEP
Definition at line 1351 of file docnode.h.
DN_SEP [2/6]
#define DN_SEP ,
Definition at line 1351 of file docnode.h.
DN_SEP [3/6]
#define DN_SEP
Definition at line 1351 of file docnode.h.
DN_SEP [4/6]
#define DN_SEP ,
Definition at line 1351 of file docnode.h.
DN_SEP [5/6]
#define DN_SEP ,
Definition at line 1351 of file docnode.h.
DN_SEP [6/6]
#define DN_SEP ,
Definition at line 1351 of file docnode.h.
DOC_NODES
#define DOC_NODES
Value:
/* 0 */ DN(DocWord) DN_SEP DN(DocLinkedWord) DN_SEP DN(DocURL) DN_SEP DN(DocLineBreak) DN_SEP DN(DocHorRuler) DN_SEP \
/* 5 */ DN(DocAnchor) DN_SEP DN(DocCite) DN_SEP DN(DocStyleChange) DN_SEP DN(DocSymbol) DN_SEP DN(DocEmoji) DN_SEP \
/* 10 */ DN(DocWhiteSpace) DN_SEP DN(DocSeparator) DN_SEP DN(DocVerbatim) DN_SEP DN(DocInclude) DN_SEP DN(DocIncOperator) DN_SEP \
/* 15 */ DN(DocFormula) DN_SEP DN(DocIndexEntry) DN_SEP DN(DocAutoList) DN_SEP DN(DocAutoListItem) DN_SEP DN(DocTitle) DN_SEP \
/* 20 */ DN(DocXRefItem) DN_SEP DN(DocImage) DN_SEP DN(DocDotFile) DN_SEP DN(DocMscFile) DN_SEP DN(DocDiaFile) DN_SEP \
/* 25 */ DN(DocVhdlFlow) DN_SEP DN(DocLink) DN_SEP DN(DocRef) DN_SEP DN(DocInternalRef) DN_SEP DN(DocHRef) DN_SEP \
/* 30 */ DN(DocHtmlHeader) DN_SEP DN(DocHtmlDescTitle) DN_SEP DN(DocHtmlDescList) DN_SEP DN(DocSection) DN_SEP DN(DocSecRefItem) DN_SEP \
/* 35 */ DN(DocSecRefList) DN_SEP DN(DocInternal) DN_SEP DN(DocParBlock) DN_SEP DN(DocSimpleList) DN_SEP DN(DocHtmlList) DN_SEP \
/* 40 */ DN(DocSimpleSect) DN_SEP DN(DocSimpleSectSep) DN_SEP DN(DocParamSect) DN_SEP DN(DocPara) DN_SEP DN(DocParamList) DN_SEP \
/* 45 */ DN(DocSimpleListItem) DN_SEP DN(DocHtmlListItem) DN_SEP DN(DocHtmlDescData) DN_SEP DN(DocHtmlCell) DN_SEP DN(DocHtmlCaption) DN_SEP \
/* 50 */ DN(DocHtmlRow) DN_SEP DN(DocHtmlTable) DN_SEP DN(DocHtmlBlockQuote) DN_SEP DN(DocText) DN_SEP DN(DocRoot) DN_SEP \
/* 55 */ DN(DocHtmlDetails) DN_SEP DN(DocHtmlSummary) \
Definition at line 37 of file docnode.h.
Typedef Documentation
DocNodeVariant
using DocNodeVariant = std::variant< DOC_NODES >
Definition at line 61 of file docnode.h.
Function Documentation
docNodeName()
const char * docNodeName (const DocNodeVariant & v) [inline]
Definition at line 1352 of file docnode.h.
{
  static const char *table[] = { DOC_NODES };
  return table[v.index()];
}
References DOC_NODES.
dumpDocNodeList()
void dumpDocNodeList (const DocNodeList & children) [inline]
Definition at line 1384 of file docnode.h.
{
  printf("children=[\n");
  for (const auto &child : children)
  {
    const DocWord *w = std::get_if<DocWord>(&child);
    printf(" %s (%p) %s\n",docNodeName(child),(void*)&child,qPrint(w?w->word():""));
  }
  printf("]\n");
}
References docNodeName(), qPrint(), and w.
dumpDocNodeSizes()
void dumpDocNodeSizes () [inline]
Definition at line 1360 of file docnode.h.
{
#define DN(x) #x
#define DN_SEP ,
  static const char *tableWithNames[] = { DOC_NODES };
#undef DN
#undef DN_SEP
#define DN(x) sizeof(x)
#define DN_SEP ,
  static size_t tableWithSizes[] = { DOC_NODES };
#undef DN
#undef DN_SEP
  size_t maxSize=0;
  printf("DocNodeVariant(\n");
  for (size_t i=0;i<sizeof(tableWithNames)/sizeof(tableWithNames[0]);i++)
  {
    printf(" /* %2zu */ sizeof(%s)=%zu\n",i,tableWithNames[i],tableWithSizes[i]);
    if (tableWithSizes[i]>maxSize) maxSize = tableWithSizes[i];
  }
  printf(")=%zu\n",maxSize);
}
References DOC_NODES.
holds_one_of_alternatives()
template<class... Ts>
constexpr bool holds_one_of_alternatives (const DocNodeVariant & v) [constexpr]
returns true iff v holds one of types passed as template parameters
Definition at line 1319 of file docnode.h.
{
  return details::Impl<Ts...>::holds_one_of_alternatives(v);
}
References details::Impl< T, Ts >::holds_one_of_alternatives().
parent() [1/2]
constexpr const DocNodeVariant * parent (const DocNodeVariant * n) [constexpr]
returns the parent node of a given node n or 0 if the node has no parent.
Definition at line 1289 of file docnode.h.
{
  return n ? std::visit([](auto &&x)->decltype(auto) { return x.parent(); }, *n) : nullptr;
}
References n, and x.
parent() [2/2]
constexpr DocNodeVariant * parent (DocNodeVariant * n) [constexpr]
returns the parent node of a given node n or 0 if the node has no parent.
Definition at line 1283 of file docnode.h.
{
  return n ? std::visit([](auto &&x)->decltype(auto) { return x.parent(); }, *n) : nullptr;
}
References n, and x.