doxygen/src/tagreader.cpp File Reference
#include `tagreader.h`
#include <map>
#include <functional>
#include <utility>
#include <algorithm>
#include <variant>
#include <assert.h>
#include <stdio.h>
#include <stdarg.h>
#include `xml.h`
#include `entry.h`
#include `doxygen.h`
#include `util.h`
#include `message.h`
#include `defargs.h`
#include `arguments.h`
#include `filedef.h`
#include `filename.h`
#include `section.h`
#include `containers.h`
#include `debug.h`
Classes
class anonymous_namespace{tagreader.cpp}::TagAnchorInfo
class anonymous_namespace{tagreader.cpp}::TagEnumValueInfo
class anonymous_namespace{tagreader.cpp}::TagIncludeInfo
class anonymous_namespace{tagreader.cpp}::TagMemberInfo
struct anonymous_namespace{tagreader.cpp}::TagCompoundInfo
struct anonymous_namespace{tagreader.cpp}::TagClassInfo
struct anonymous_namespace{tagreader.cpp}::TagConceptInfo
struct anonymous_namespace{tagreader.cpp}::TagNamespaceInfo
struct anonymous_namespace{tagreader.cpp}::TagPackageInfo
struct anonymous_namespace{tagreader.cpp}::TagFileInfo
struct anonymous_namespace{tagreader.cpp}::TagGroupInfo
struct anonymous_namespace{tagreader.cpp}::TagPageInfo
struct anonymous_namespace{tagreader.cpp}::TagDirInfo
class anonymous_namespace{tagreader.cpp}::TagCompoundVariant
class anonymous_namespace{tagreader.cpp}::TagFileParser
struct anonymous_namespace{tagreader.cpp}::ElementCallbacks
struct anonymous_namespace{tagreader.cpp}::CompoundFactory
Namespaces
namespace anonymous_namespace{tagreader.cpp}
Functions
ElementCallbacks::StartCallback anonymous_namespace{tagreader.cpp}::startCb (void(TagFileParser::*fn)(const XMLHandlers::Attributes &))
ElementCallbacks::EndCallback anonymous_namespace{tagreader.cpp}::endCb (void(TagFileParser::*fn)())
void parseTagFile (const std::shared_ptr< Entry > &root, const char *fullName)
Variables
static const std::map< std::string, ElementCallbacks > anonymous_namespace{tagreader.cpp}::g_elementHandlers
static const std::map< std::string, CompoundFactory > anonymous_namespace{tagreader.cpp}::g_compoundFactory
Function Documentation
parseTagFile()
void parseTagFile (const std::shared_ptr< Entry > & root, const char * fullName)
Definition at line 1689 of file tagreader.cpp.
{
  TagFileParser tagFileParser(fullName);
  QCString inputStr = fileToString(fullName);
  XMLHandlers handlers;
  // connect the generic events handlers of the XML parser to the specific handlers of the tagFileParser object
  handlers.startDocument = [&tagFileParser]() { tagFileParser.startDocument(); };
  handlers.startElement = [&tagFileParser](const std::string &name,const XMLHandlers::Attributes &attrs) { tagFileParser.startElement(QCString(name),attrs); };
  handlers.endElement = [&tagFileParser](const std::string &name) { tagFileParser.endElement(QCString(name)); };
  handlers.characters = [&tagFileParser](const std::string &chars) { tagFileParser.characters(QCString(chars)); };
  handlers.error = [&tagFileParser](const std::string &fileName,int lineNr,const std::string &msg) { tagFileParser.error(QCString(fileName),lineNr,QCString(msg)); };
  XMLParser parser(handlers);
  tagFileParser.setDocumentLocator(&parser);
  parser.parse(fullName,inputStr.data(),Debug::isFlagSet(Debug::Lex));
  tagFileParser.buildLists(root);
  tagFileParser.addIncludes();
  if (Debug::isFlagSet(Debug::Tag))
  {
    tagFileParser.dump();
  }
}
References XMLHandlers::characters, QCString::data(), XMLHandlers::endElement, XMLHandlers::error, fileToString(), Debug::isFlagSet(), Debug::Lex, msg(), setup::name, XMLParser::parse(), XMLHandlers::startDocument, XMLHandlers::startElement, string, and Debug::Tag.