doxygen/src/message.cpp File Reference
#include <stdio.h>
#include `config.h`
#include `debug.h`
#include `portable.h`
#include `message.h`
#include `doxygen.h`
#include <mutex>
#include <atomic>
Functions
void initWarningFormat ()
void msg (const char *fmt,...)
static void format_warn (const QCString &file, int line, const QCString &text)
static void handle_warn_as_error ()
static void do_warn (bool enabled, const QCString &file, int line, const char *prefix, const char *fmt, va_list args)
QCString warn_line (const QCString &file, int line)
void warn (const QCString &file, int line, const char *fmt,...)
void va_warn (const QCString &file, int line, const char *fmt, va_list args)
void warn_simple (const QCString &file, int line, const char *text)
void warn_undoc (const QCString &file, int line, const char *fmt,...)
void warn_incomplete_doc (const QCString &file, int line, const char *fmt,...)
void warn_doc_error (const QCString &file, int line, const char *fmt,...)
void warn_uncond (const char *fmt,...)
void err (const char *fmt,...)
void err_full (const QCString &file, int line, const char *fmt,...)
void term (const char *fmt,...)
void warn_flush ()
void printlex (int dbg, bool enter, const char *lexName, const char *fileName)
void finishWarnExit ()
Variables
static QCString g_warnFormat
static QCString g_warnLineFormat
static const char * g_warningStr = `warning: `
static const char * g_errorStr = `error: `
static FILE * g_warnFile = stderr
static WARN_AS_ERROR_t g_warnBehavior = WARN_AS_ERROR_t::NO
static std::atomic_bool g_warnStat = false
static std::mutex g_mutex
Function Documentation
do_warn()
static void do_warn (bool enabled, const QCString & file, int line, const char * prefix, const char * fmt, va_list args) [static]
Definition at line 138 of file message.cpp.
{
  if (!enabled) return; // warning type disabled
  va_list argsCopy;
  va_copy(argsCopy, args);
  size_t l=0;
  if (prefix)
  {
    l=strlen(prefix);
  }
  // determine needed buffersize based on:
  // format + arguments
  // prefix
  // 1 position for `\0`
  size_t bufSize = vsnprintf(NULL, 0, fmt, args) + l + 1;
  QCString text(bufSize);
  if (prefix)
  {
    qstrncpy(text.rawData(),prefix,bufSize);
  }
  vsnprintf(text.rawData()+l, bufSize-l, fmt, argsCopy);
  text[static_cast<int>(bufSize)-1]='\0';
  format_warn(file,line,text);
  va_end(argsCopy);
}
References caseconvert::file, fmt, format_warn(), qstrncpy(), and QCString::rawData().
Referenced by err_full(), va_warn(), warn(), warn_doc_error(), warn_incomplete_doc(), and warn_undoc().
err()
void err (const char * fmt, ...)
Definition at line 231 of file message.cpp.
{
  va_list args;
  va_start(args, fmt);
  vfprintf(g_warnFile, (QCString(g_errorStr) + fmt).data(), args);
  va_end(args);
  handle_warn_as_error();
}
References data, fmt, g_errorStr, g_warnFile, and handle_warn_as_error().
err_full()
void err_full (const QCString & file, int line, const char * fmt, ...)
Definition at line 240 of file message.cpp.
{
  va_list args;
  va_start(args, fmt);
  do_warn(TRUE, file, line, g_errorStr, fmt, args);
  va_end(args);
}
References do_warn(), caseconvert::file, fmt, g_errorStr, and TRUE.
finishWarnExit()
void finishWarnExit ()
Definition at line 301 of file message.cpp.
{
  if (g_warnStat && g_warnBehavior == WARN_AS_ERROR_t::FAIL_ON_WARNINGS)
  {
    Doxygen::terminating=true;
    exit(1);
  }
}
References g_warnBehavior, g_warnStat, and Doxygen::terminating.
format_warn()
static void format_warn (const QCString & file, int line, const QCString & text) [static]
Definition at line 83 of file message.cpp.
{
  QCString fileSubst = file.isEmpty() ? "<unknown>" : file;
  QCString lineSubst; lineSubst.setNum(line);
  QCString textSubst = text;
  QCString versionSubst;
  // substitute markers by actual values
  QCString msgText =
      substitute(
        substitute(
          substitute(
            substitute(
              g_warnFormat,
              "$file",fileSubst
            ),
            "$line",lineSubst
          ),
          "$version",versionSubst
        ),
        "$text",textSubst
      );
  if (g_warnBehavior == WARN_AS_ERROR_t::YES)
  {
    msgText += " (warning treated as error, aborting now)";
  }
  msgText += '\n';
  {
    std::unique_lock<std::mutex> lock(g_mutex);
    // print resulting message
    fwrite(msgText.data(),1,msgText.length(),g_warnFile);
  }
  if (g_warnBehavior == WARN_AS_ERROR_t::YES)
  {
    Doxygen::terminating=true;
    exit(1);
  }
  g_warnStat = true;
}
References QCString::data(), caseconvert::file, g_mutex, g_warnBehavior, g_warnFile, g_warnFormat, g_warnStat, QCString::length(), QCString::setNum(), substitute(), and Doxygen::terminating.
Referenced by do_warn(), and warn_simple().
handle_warn_as_error()
static void handle_warn_as_error () [static]
Definition at line 123 of file message.cpp.
{
  if (g_warnBehavior == WARN_AS_ERROR_t::YES)
  {
    {
      std::unique_lock<std::mutex> lock(g_mutex);
      QCString msgText = " (warning treated as error, aborting now)\n";
      fwrite(msgText.data(),1,msgText.length(),g_warnFile);
    }
    Doxygen::terminating=true;
    exit(1);
  }
  g_warnStat = true;
}
References QCString::data(), g_mutex, g_warnBehavior, g_warnFile, g_warnStat, QCString::length(), and Doxygen::terminating.
Referenced by err(), and warn_uncond().
initWarningFormat()
void initWarningFormat ()
Definition at line 36 of file message.cpp.
{
  g_warnFormat = Config_getString(WARN_FORMAT);
  g_warnLineFormat = Config_getString(WARN_LINE_FORMAT);
  QCString logFile = Config_getString(WARN_LOGFILE);
  if (!logFile.isEmpty())
  {
    if (logFile == "-")
    {
      g_warnFile = stdout;
    }
    else if (!(g_warnFile = Portable::fopen(logFile,"w")))
    {
      // point it to something valid, because warn() relies on it
      g_warnFile = stderr;
      err("Cannot open '%s' for writing, redirecting 'WARN_LOGFILE' output to 'stderr'\n",logFile.data());
    }
  }
  else
  {
    g_warnFile = stderr;
  }
  g_warnBehavior = Config_getEnum(WARN_AS_ERROR);
  if (g_warnBehavior != WARN_AS_ERROR_t::NO)
  {
    g_warningStr = g_errorStr;
  }
}
References Config_getEnum, Config_getString, QCString::data(), err(), Portable::fopen(), g_errorStr, g_warnBehavior, g_warnFile, g_warnFormat, g_warningStr, g_warnLineFormat, and QCString::isEmpty().
msg()
void msg (const char * fmt, ...)
Definition at line 67 of file message.cpp.
{
  if (!Config_getBool(QUIET))
  {
    std::unique_lock<std::mutex> lock(g_mutex);
    if (Debug::isFlagSet(Debug::Time))
    {
      printf("%.3f sec: ",(static_cast<double>(Debug::elapsedTime())));
    }
    va_list args;
    va_start(args, fmt);
    vfprintf(stdout, fmt, args);
    va_end(args);
  }
}
References Config_getBool, Debug::elapsedTime(), fmt, g_mutex, Debug::isFlagSet(), and Debug::Time.
printlex()
void printlex (int dbg, bool enter, const char * lexName, const char * fileName)
Definition at line 273 of file message.cpp.
{
  const char *enter_txt = "entering";
  const char *enter_txt_uc = "Entering";
  if (!enter)
  {
    enter_txt = "finished";
    enter_txt_uc = "Finished";
  }
  std::unique_lock<std::mutex> lock(g_mutex);
  if (dbg)
  {
    if (fileName)
      fprintf(stderr,"--%s lexical analyzer: %s (for: %s)\n",enter_txt, qPrint(lexName), qPrint(fileName));
    else
      fprintf(stderr,"--%s lexical analyzer: %s\n",enter_txt, qPrint(lexName));
  }
  else
  {
    if (fileName)
      Debug::print(Debug::Lex,0,"%s lexical analyzer: %s (for: %s)\n",enter_txt_uc, qPrint(lexName), qPrint(fileName));
    else
      Debug::print(Debug::Lex,0,"%s lexical analyzer: %s\n",enter_txt_uc, qPrint(lexName));
  }
}
References g_mutex, Debug::Lex, Debug::print(), and qPrint().
term()
void term (const char * fmt, ...)
Definition at line 248 of file message.cpp.
{
  {
    std::unique_lock<std::mutex> lock(g_mutex);
    va_list args;
    va_start(args, fmt);
    vfprintf(g_warnFile, (QCString(g_errorStr) + fmt).data(), args);
    va_end(args);
    if (g_warnFile != stderr)
    {
      size_t l = strlen(g_errorStr);
      for (size_t i=0; i<l; i++) fprintf(g_warnFile, " ");
      fprintf(g_warnFile, "%s\n", "Exiting...");
    }
  }
  Doxygen::terminating=true;
  exit(1);
}
References data, fmt, g_errorStr, g_mutex, g_warnFile, and Doxygen::terminating.
va_warn()
void va_warn (const QCString & file, int line, const char * fmt, va_list args)
Definition at line 187 of file message.cpp.
{
  do_warn(Config_getBool(WARNINGS), file, line, g_warningStr, fmt, args);
}
References Config_getBool, do_warn(), caseconvert::file, fmt, and g_warningStr.
warn()
void warn (const QCString & file, int line, const char * fmt, ...)
Definition at line 179 of file message.cpp.
{
  va_list args;
  va_start(args, fmt);
  do_warn(Config_getBool(WARNINGS), file, line, g_warningStr, fmt, args);
  va_end(args);
}
References Config_getBool, do_warn(), caseconvert::file, fmt, and g_warningStr.
warn_doc_error()
void warn_doc_error (const QCString & file, int line, const char * fmt, ...)
Definition at line 214 of file message.cpp.
{
  va_list args;
  va_start(args, fmt);
  do_warn(Config_getBool(WARN_IF_DOC_ERROR), file, line, g_warningStr, fmt, args);
  va_end(args);
}
References Config_getBool, do_warn(), caseconvert::file, fmt, and g_warningStr.
warn_flush()
void warn_flush ()
Definition at line 267 of file message.cpp.
{
  fflush(g_warnFile);
}
References g_warnFile.
warn_incomplete_doc()
void warn_incomplete_doc (const QCString & file, int line, const char * fmt, ...)
Definition at line 206 of file message.cpp.
{
  va_list args;
  va_start(args, fmt);
  do_warn(Config_getBool(WARN_IF_INCOMPLETE_DOC), file, line, g_warningStr, fmt, args);
  va_end(args);
}
References Config_getBool, do_warn(), caseconvert::file, fmt, and g_warningStr.
warn_line()
QCString warn_line (const QCString & file, int line)
Definition at line 167 of file message.cpp.
{
  QCString fileSubst = file.isEmpty() ? "<unknown>" : file;
  QCString lineSubst; lineSubst.setNum(line);
  return substitute(
            substitute(
              g_warnLineFormat,
              "$file",fileSubst
            ),
            "$line",lineSubst
          );
}
References caseconvert::file, g_warnLineFormat, QCString::setNum(), and substitute().
warn_simple()
void warn_simple (const QCString & file, int line, const char * text)
Definition at line 192 of file message.cpp.
{
  if (!Config_getBool(WARNINGS)) return; // warning type disabled
  format_warn(file,line,QCString(g_warningStr) + text);
}
References Config_getBool, caseconvert::file, format_warn(), and g_warningStr.
warn_uncond()
void warn_uncond (const char * fmt, ...)
Definition at line 222 of file message.cpp.
{
  va_list args;
  va_start(args, fmt);
  vfprintf(g_warnFile, (QCString(g_warningStr) + fmt).data(), args);
  va_end(args);
  handle_warn_as_error();
}
References data, fmt, g_warnFile, g_warningStr, and handle_warn_as_error().
warn_undoc()
void warn_undoc (const QCString & file, int line, const char * fmt, ...)
Definition at line 198 of file message.cpp.
{
  va_list args;
  va_start(args, fmt);
  do_warn(Config_getBool(WARN_IF_UNDOCUMENTED), file, line, g_warningStr, fmt, args);
  va_end(args);
}
References Config_getBool, do_warn(), caseconvert::file, fmt, and g_warningStr.
Variable Documentation
g_errorStr
const char* g_errorStr = `error: ` [static]
Definition at line 30 of file message.cpp.
Referenced by err(), err_full(), initWarningFormat(), and term().
g_mutex
std::mutex g_mutex [static]
Definition at line 34 of file message.cpp.
Referenced by format_warn(), handle_warn_as_error(), msg(), printlex(), and term().
g_warnBehavior
WARN_AS_ERROR_t g_warnBehavior = WARN_AS_ERROR_t::NO [static]
Definition at line 32 of file message.cpp.
Referenced by finishWarnExit(), format_warn(), handle_warn_as_error(), and initWarningFormat().
g_warnFile
FILE* g_warnFile = stderr [static]
Definition at line 31 of file message.cpp.
Referenced by err(), format_warn(), handle_warn_as_error(), initWarningFormat(), term(), warn_flush(), and warn_uncond().
g_warnFormat
QCString g_warnFormat [static]
Definition at line 27 of file message.cpp.
Referenced by format_warn(), and initWarningFormat().
g_warningStr
const char* g_warningStr = `warning: ` [static]
Definition at line 29 of file message.cpp.
Referenced by initWarningFormat(), va_warn(), warn(), warn_doc_error(), warn_incomplete_doc(), warn_simple(), warn_uncond(), and warn_undoc().
g_warnLineFormat
QCString g_warnLineFormat [static]
Definition at line 28 of file message.cpp.
Referenced by initWarningFormat(), and warn_line().
g_warnStat
std::atomic_bool g_warnStat = false [static]
Definition at line 33 of file message.cpp.
Referenced by finishWarnExit(), format_warn(), and handle_warn_as_error().