doxygen/src/layout.h File Reference
#include <memory>
#include <vector>
#include `types.h`
Classes
struct LayoutDocEntry
Base class representing a piece of a documentation page.
struct LayoutDocEntrySimple
Represents of a piece of a documentation page without configurable parts.
struct LayoutDocEntrySection
struct LayoutDocEntryMemberDecl
Represents of a member declaration list with configurable title and subtitle.
struct LayoutDocEntryMemberDef
Represents of a member definition list with configurable title.
struct LayoutNavEntry
Base class for the layout of a navigation item at the top of the HTML pages.
class LayoutDocManager
Singleton providing access to the (user configurable) layout of the documentation.
Typedefs
using LayoutNavEntryList = std::vector< std::unique_ptr< LayoutNavEntry > >
using LayoutDocEntryList = std::vector< std::unique_ptr< LayoutDocEntry > >
Functions
void writeDefaultLayoutFile (const QCString &fileName)
Typedef Documentation
LayoutDocEntryList
using LayoutDocEntryList = std::vector< std::unique_ptr<LayoutDocEntry> >
Definition at line 194 of file layout.h.
LayoutNavEntryList
using LayoutNavEntryList = std::vector< std::unique_ptr<LayoutNavEntry> >
Definition at line 122 of file layout.h.
Function Documentation
writeDefaultLayoutFile()
void writeDefaultLayoutFile (const QCString & fileName)
Definition at line 1623 of file layout.cpp.
{
  std::ofstream f;
  if (openOutputFile(fileName,f))
  {
    TextStream t(&f);
    QCString layout_default = ResourceMgr::instance().getAsString("layout_default.xml");
    t << substitute(layout_default,"$doxygenversion",getDoxygenVersion());
  }
  else
  {
    err("Failed to open file %s for writing!\n",qPrint(fileName));
    return;
  }
  f.close();
}
References err(), f, ResourceMgr::getAsString(), getDoxygenVersion(), ResourceMgr::instance(), openOutputFile(), qPrint(), and substitute().
Referenced by readConfiguration().