doxygen/src/mangen.cpp File Reference
#include <stdlib.h>
#include `message.h`
#include `mangen.h`
#include `config.h`
#include `util.h`
#include `doxygen.h`
#include <string.h>
#include `docparser.h`
#include `mandocvisitor.h`
#include `language.h`
#include `dir.h`
#include `utf8.h`
Functions
static QCString getExtension ()
static QCString getSubdir ()
static QCString buildFileName (const QCString &name)
Function Documentation
buildFileName()
static QCString buildFileName (const QCString & name) [static]
Definition at line 125 of file mangen.cpp.
{
  QCString fileName;
  if (name.isEmpty()) return "noname";
  const char *p=name.data();
  char c;
  while ((c=*p++))
  {
    switch (c)
    {
      case ':':
        fileName+="_";
        if (*p==':') p++;
        break;
      case '<':
      case '>':
      case '&':
      case '*':
      case '!':
      case '^':
      case '~':
      case '%':
      case '+':
      case '/':
        fileName+="_";
        break;
      default:
        fileName+=c;
    }
  }
  QCString manExtension = "." + getExtension();
  if (fileName.right(manExtension.length())!=manExtension)
  {
    fileName+=manExtension;
  }
  return fileName;
}
References c, getExtension(), QCString::length(), setup::name, p, and QCString::right().
getExtension()
static QCString getExtension () [static]
Definition at line 35 of file mangen.cpp.
{
  /*
   * [.][number][rest]
   * in case of . missing, just ignore it
   * in case number missing, just place a 3 in front of it
   */
  QCString ext = Config_getString(MAN_EXTENSION);
  if (ext.isEmpty())
  {
    ext = "3";
  }
  else
  {
    if (ext.at(0)=='.')
    {
      if (ext.length()==1)
      {
        ext = "3";
      }
      else // strip .
      {
        ext = ext.mid(1);
      }
    }
    if (ext.at(0)<'0' || ext.at(0)>'9')
    {
      ext.prepend("3");
    }
  }
  return ext;
}
References QCString::at(), Config_getString, QCString::isEmpty(), QCString::length(), QCString::mid(), and QCString::prepend().
Referenced by buildFileName(), and getSubdir().
getSubdir()
static QCString getSubdir () [static]
Definition at line 68 of file mangen.cpp.
{
  QCString dir = Config_getString(MAN_SUBDIR);
  if (dir.isEmpty())
  {
    dir = "man" + getExtension();
  }
  return dir;
}
References Config_getString, getExtension(), and QCString::isEmpty().