doxygen/src/dotnode.h File Reference
#include <vector>
#include <map>
#include <deque>
#include <iostream>
#include `dotgraph.h`
Classes
class EdgeInfo
class DotNode
class DotNodeMap
class DotNodeDeque
Typedefs
using DotNodeRefVector = std::vector< DotNode * >
using EdgeInfoVector = std::vector< EdgeInfo >
Functions
QCString escapeTooltip (const QCString &tooltip)
Typedef Documentation
DotNodeRefVector
using DotNodeRefVector = std::vector<DotNode*>
Definition at line 52 of file dotnode.h.
EdgeInfoVector
using EdgeInfoVector = std::vector<EdgeInfo>
Definition at line 53 of file dotnode.h.
Function Documentation
escapeTooltip()
QCString escapeTooltip (const QCString & tooltip)
Definition at line 99 of file dotnode.cpp.
{
  if (tooltip.isEmpty()) return tooltip;
  QCString result;
  const char *p=tooltip.data();
  char c;
  while ((c=*p++))
  {
    switch(c)
    {
    case '"': result+="\\\""; break;
    case '\\': result+="\\\\"; break;
    default: result+=c; break;
    }
  }
  return result;
}
References c, QCString::data(), QCString::isEmpty(), and p.
Referenced by common_attributes(), and DotNode::writeBox().