DotGroupCollaboration::Edge Struct Reference
Public Member Functions
Edge (DotNode *start, DotNode *end, EdgeType type)
void write (TextStream &t) const
Edge (DotNode *start, DotNode *end, EdgeType type)
void write (TextStream &t) const
Public Attributes
DotNode * pNStart
DotNode * pNEnd
EdgeType eType
std::vector< Link > links
Detailed Description
Definition at line 62 of file dotgroupcollaboration.h.
Constructor & Destructor Documentation
Edge() [1/2]
DotGroupCollaboration::Edge::Edge (DotNode * start, DotNode * end, EdgeType type) [inline]
Definition at line 64 of file dotgroupcollaboration.h.
        : pNStart(start), pNEnd(end), eType(type) {}
Edge() [2/2]
DotGroupCollaboration::Edge::Edge (DotNode * start, DotNode * end, EdgeType type) [inline]
Definition at line 64 of file dotgroupcollaboration.h.
        : pNStart(start), pNEnd(end), eType(type) {}
Member Function Documentation
write() [1/2]
void DotGroupCollaboration::Edge::write (TextStream & t) const
Definition at line 252 of file dotgroupcollaboration.cpp.
{
  const char* linkTypeColor[] = {
    "darkorchid3"
    ,"orange"
    ,"blueviolet"
    ,"darkgreen"
    ,"firebrick4"
    ,"grey75"
    ,"midnightblue"
  };
  QCString arrowStyle = "dir=\"none\", style=\"dashed\"";
  t << " Node" << pNStart->number();
  t << "->";
  t << "Node" << pNEnd->number();
  t << " [shape=plaintext";
  if (!links.empty()) // there are links
  {
    t << ", ";
    // HTML-like edge labels crash on my Mac with Graphviz 2.0! and
    // are not supported by older version of dot.
    //
    //t << label=<<TABLE BORDER=\"0\" CELLBORDER=\"0\">";
    //for (const auto &link : links)
    //{
    // t << "<TR><TD";
    // if (!link.url.isEmpty())
    // t << " HREF=\"" << link.url << "\"";
    // t << ">" << DotNode::convertLabel(link->label) << "</TD></TR>";
    //}
    //t << "</TABLE>>";
    t << "label=\"";
    bool first=TRUE;
    int count=0;
    const int maxLabels = 10;
    for (const auto &link : links)
    {
      if (first) first=FALSE; else t << "\\n";
      t << DotNode::convertLabel(link.label);
      count++;
    }
    if (count==maxLabels) t << "\\n...";
    t << "\"";
  }
  switch(eType)
  {
    case thierarchy:
      arrowStyle = "dir=\"back\", style=\"solid\"";
      break;
    default:
      t << ", color=\"" << linkTypeColor[static_cast<int>(eType)] << "\"";
      break;
  }
  t << ", " << arrowStyle;
  t << "];\n";
}
References DotNode::convertLabel(), eType, FALSE, links, DotNode::number(), pNEnd, pNStart, DotGroupCollaboration::thierarchy, and TRUE.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_write(), doxmlparser.compound.memberdefType::hasContent_(), and doxmlparser.compound.memberdefType::set_write().
write() [2/2]
void DotGroupCollaboration::Edge::write (TextStream & t) const
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_write(), doxmlparser.compound.memberdefType::hasContent_(), and doxmlparser.compound.memberdefType::set_write().
Member Data Documentation
eType
EdgeType DotGroupCollaboration::Edge::eType
Definition at line 69 of file dotgroupcollaboration.h.
Referenced by write().
links
std::vector< Link > DotGroupCollaboration::Edge::links
Definition at line 71 of file dotgroupcollaboration.h.
Referenced by write().
pNEnd
DotNode * DotGroupCollaboration::Edge::pNEnd
Definition at line 68 of file dotgroupcollaboration.h.
Referenced by write().
pNStart
DotNode * DotGroupCollaboration::Edge::pNStart
Definition at line 67 of file dotgroupcollaboration.h.
Referenced by write().
The documentation for this struct was generated from the following files:
doxygen/build/doxygen/src/dotgroupcollaboration.h
doxygen/src/dotgroupcollaboration.h
doxygen/build/doxygen/src/dotgroupcollaboration.cpp
doxygen/src/dotgroupcollaboration.cpp