details::Impl< T, Ts > Struct Template Reference
#include <docnode.h>
Static Public Member Functions
static constexpr bool holds_one_of_alternatives (const DocNodeVariant &v)
static constexpr bool holds_one_of_alternatives (const DocNodeVariant &v)
Detailed Description
template<class T, class... Ts>
struct details::Impl< T, Ts >
Definition at line 1298 of file docnode.h.
Member Function Documentation
holds_one_of_alternatives() [1/2]
template<class T , class... Ts>
static constexpr bool details::Impl< T, Ts >::holds_one_of_alternatives (const DocNodeVariant & v) [inline], [static], [constexpr]
Definition at line 1300 of file docnode.h.
  {
    return std::holds_alternative<T>(v) || Impl<Ts...>::holds_one_of_alternatives(v);
  }
References details::Impl< T, Ts >::holds_one_of_alternatives().
Referenced by details::Impl< T, Ts >::holds_one_of_alternatives(), and holds_one_of_alternatives().
holds_one_of_alternatives() [2/2]
template<class T , class... Ts>
static constexpr bool details::Impl< T, Ts >::holds_one_of_alternatives (const DocNodeVariant & v) [inline], [static], [constexpr]
Definition at line 1300 of file docnode.h.
  {
    return std::holds_alternative<T>(v) || Impl<Ts...>::holds_one_of_alternatives(v);
  }
References details::Impl< T, Ts >::holds_one_of_alternatives().
The documentation for this struct was generated from the following files:
doxygen/build/doxygen/src/docnode.h
doxygen/src/docnode.h