CiteInfo Struct Reference
Citation-related data.
#include <cite.h>
Public Member Functions
virtual ~CiteInfo ()=default
virtual QCString label () const =0
virtual QCString text () const =0
virtual ~CiteInfo ()=default
virtual QCString label () const =0
virtual QCString text () const =0
Detailed Description
Citation-related data.
Definition at line 25 of file cite.h.
Constructor & Destructor Documentation
 CiteInfo() [1/2]
virtual CiteInfo::~CiteInfo () [virtual], [default]
 CiteInfo() [2/2]
virtual CiteInfo::~CiteInfo () [virtual], [default]
Member Function Documentation
label() [1/2]
virtual QCString CiteInfo::label () const [pure virtual]
Implemented in CiteInfoImpl, and CiteInfoImpl.
Referenced by doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.nodeType::buildChildren(), DocCite::DocCite(), doxmlparser.compound.nodeType::exportChildren(), doxmlparser.compound.nodeType::get_label(), doxmlparser.compound.nodeType::hasContent_(), and doxmlparser.compound.nodeType::set_label().
label() [2/2]
virtual QCString CiteInfo::label () const [pure virtual]
Implemented in CiteInfoImpl, and CiteInfoImpl.
Referenced by doxmlparser.compound.nodeType::__init__(), doxmlparser.compound.nodeType::buildChildren(), doxmlparser.compound.nodeType::exportChildren(), doxmlparser.compound.nodeType::get_label(), doxmlparser.compound.nodeType::hasContent_(), and doxmlparser.compound.nodeType::set_label().
text() [1/2]
virtual QCString CiteInfo::text () const [pure virtual]
Implemented in CiteInfoImpl, and CiteInfoImpl.
Referenced by DocCite::DocCite().
text() [2/2]
virtual QCString CiteInfo::text () const [pure virtual]
Implemented in CiteInfoImpl, and CiteInfoImpl.
The documentation for this struct was generated from the following files:
doxygen/build/doxygen/src/cite.h
doxygen/src/cite.h