VHDLOutlineParser::Private Struct Reference
Public Member Functions
void parseVhdlfile (const QCString &fileName, const char *inputBuffer, bool inLine)
void parseVhdlfile (const QCString &fileName, const char *inputBuffer, bool inLine)
Public Attributes
VHDLOutlineParser * thisParser = 0
VhdlParser * vhdlParser = 0
CommentScanner commentScanner
QCString yyFileName
int yyLineNr = 1
IntVector lineParse
int iDocLine = -1
QCString inputString
Entry * gBlock = 0
Entry * previous = 0
Entry * oldEntry = 0
bool varr = FALSE
QCString varName
EntryList libUse
EntryList lineEntry
QCString strComment
int iCodeLen
VHDLDocInfo str_doc
VhdlParser::SharedState shared
QCString forL
int code = 0
Detailed Description
Definition at line 57 of file vhdljjparser.cpp.
Member Function Documentation
parseVhdlfile() [1/2]
void VHDLOutlineParser::Private::parseVhdlfile (const QCString & fileName, const char * inputBuffer, bool inLine)
Definition at line 88 of file vhdljjparser.cpp.
{
  JAVACC_STRING_TYPE s =inputBuffer;
  CharStream *stream = new CharStream(s.c_str(), (int)s.size(), 1, 1);
  VhdlParserTokenManager *tokenManager = new VhdlParserTokenManager(stream);
  VhdlTokenManagerErrorHandler *tokErrHandler=new VhdlTokenManagerErrorHandler(fileName.data());
  vhdlParser=new VhdlParser(tokenManager);
  vhdlParser->setOutlineParser(thisParser);
  vhdlParser->setSharedState(&shared);
  tokenManager->setLexParser(vhdlParser);
  tokenManager->ReInit(stream,0);
  tokenManager->setErrorHandler(tokErrHandler);
  VhdlErrorHandler *parserErrHandler=new VhdlErrorHandler(fileName.data());
  vhdlParser->setErrorHandler(parserErrHandler);
  try
  {
    if(inLine)
    {
      vhdlParser->parseInline();
    }
    else
    {
      vhdlParser->design_file();
    }
  }
  catch(std::exception &){ /* fprintf(stderr,"\n[%s]",e.what()); */ }
  // fprintf(stderr,"\n\nparsed lines: %d\n",yyLineNr);
  // fprintf(stderr,"\n\nerrors : %d\n\n",myErr->getErrorCount());
  //
  delete vhdlParser;
  delete tokenManager;
  delete stream;
}
References QCString::data(), vhdl::parser::VhdlParser::design_file(), JAVACC_STRING_TYPE, vhdl::parser::VhdlParser::parseInline(), vhdl::parser::VhdlParserTokenManager::ReInit(), s, vhdl::parser::VhdlParser::setErrorHandler(), vhdl::parser::VhdlParserTokenManager::setErrorHandler(), vhdl::parser::TokenParser::setLexParser(), vhdl::parser::VhdlParser::setOutlineParser(), vhdl::parser::VhdlParser::setSharedState(), shared, thisParser, and vhdlParser.
parseVhdlfile() [2/2]
void VHDLOutlineParser::Private::parseVhdlfile (const QCString & fileName, const char * inputBuffer, bool inLine)
Member Data Documentation
code
int VHDLOutlineParser::Private::code = 0
Definition at line 84 of file vhdljjparser.cpp.
commentScanner
CommentScanner VHDLOutlineParser::Private::commentScanner
Definition at line 63 of file vhdljjparser.cpp.
forL
QCString VHDLOutlineParser::Private::forL
Definition at line 83 of file vhdljjparser.cpp.
gBlock
Entry * VHDLOutlineParser::Private::gBlock = 0
Definition at line 70 of file vhdljjparser.cpp.
iCodeLen
int VHDLOutlineParser::Private::iCodeLen
Definition at line 80 of file vhdljjparser.cpp.
iDocLine
int VHDLOutlineParser::Private::iDocLine = -1
Definition at line 68 of file vhdljjparser.cpp.
inputString
QCString VHDLOutlineParser::Private::inputString
Definition at line 69 of file vhdljjparser.cpp.
libUse
EntryList VHDLOutlineParser::Private::libUse
Definition at line 77 of file vhdljjparser.cpp.
lineEntry
EntryList VHDLOutlineParser::Private::lineEntry
Definition at line 78 of file vhdljjparser.cpp.
lineParse
IntVector VHDLOutlineParser::Private::lineParse
Definition at line 67 of file vhdljjparser.cpp.
oldEntry
Entry * VHDLOutlineParser::Private::oldEntry = 0
Definition at line 74 of file vhdljjparser.cpp.
previous
Entry * VHDLOutlineParser::Private::previous = 0
Definition at line 71 of file vhdljjparser.cpp.
shared
VhdlParser::SharedState VHDLOutlineParser::Private::shared
Definition at line 82 of file vhdljjparser.cpp.
Referenced by parseVhdlfile().
str_doc
VHDLDocInfo VHDLOutlineParser::Private::str_doc
Definition at line 81 of file vhdljjparser.cpp.
strComment
QCString VHDLOutlineParser::Private::strComment
Definition at line 79 of file vhdljjparser.cpp.
thisParser
VHDLOutlineParser * VHDLOutlineParser::Private::thisParser = 0
Definition at line 61 of file vhdljjparser.cpp.
Referenced by parseVhdlfile().
varName
QCString VHDLOutlineParser::Private::varName
Definition at line 76 of file vhdljjparser.cpp.
varr
bool VHDLOutlineParser::Private::varr = FALSE
Definition at line 75 of file vhdljjparser.cpp.
vhdlParser
VhdlParser * VHDLOutlineParser::Private::vhdlParser = 0
Definition at line 62 of file vhdljjparser.cpp.
Referenced by parseVhdlfile().
yyFileName
QCString VHDLOutlineParser::Private::yyFileName
Definition at line 65 of file vhdljjparser.cpp.
yyLineNr
int VHDLOutlineParser::Private::yyLineNr = 1
Definition at line 66 of file vhdljjparser.cpp.
The documentation for this struct was generated from the following files:
doxygen/build/doxygen/src/vhdljjparser.cpp
doxygen/src/vhdljjparser.cpp