Htags Struct Reference
#include <htags.h>
Static Public Member Functions
static bool loadFilemap (const QCString &htmldir)
static QCString path2URL (const QCString &path)
static bool execute (const QCString &htmldir)
static bool loadFilemap (const QCString &htmldir)
static QCString path2URL (const QCString &path)
static bool execute (const QCString &htmldir)
Static Public Attributes
static bool useHtags = FALSE
Detailed Description
This class is a namespace for HTAGS related functions
Definition at line 21 of file htags.h.
Member Function Documentation
execute() [1/2]
bool Htags::execute (const QCString & htmldir) [static]
constructs command line of htags(1) and executes it.
Return values
TRUE success
FALSE an error has occurred.
Definition at line 38 of file htags.cpp.
{
  const StringVector &inputSource = Config_getList(INPUT);
  bool quiet = Config_getBool(QUIET);
  bool warnings = Config_getBool(WARNINGS);
  QCString htagsOptions = ""; //Config_getString(HTAGS_OPTIONS);
  QCString projectName = Config_getString(PROJECT_NAME);
  QCString projectNumber = Config_getString(PROJECT_NUMBER);
  if (inputSource.empty())
  {
    g_inputDir.setPath(Dir::currentDirPath());
  }
  else if (inputSource.size()==1)
  {
    g_inputDir.setPath(inputSource.back());
    if (!g_inputDir.exists())
      err("Cannot find directory %s. "
          "Check the value of the INPUT tag in the configuration file.\n",
          inputSource.back().c_str()
         );
  }
  else
  {
    err("If you use USE_HTAGS then INPUT should specify a single directory.\n");
    return FALSE;
  }
  /*
   * Construct command line for htags(1).
   */
  QCString commandLine = " -g -s -a -n ";
  if (!quiet) commandLine += "-v ";
  if (warnings) commandLine += "-w ";
  if (!htagsOptions.isEmpty())
  {
    commandLine += ' ';
    commandLine += htagsOptions;
  }
  if (!projectName.isEmpty())
  {
    commandLine += "-t \"";
    commandLine += projectName;
    if (!projectNumber.isEmpty())
    {
      commandLine += '-';
      commandLine += projectNumber;
    }
    commandLine += "\" ";
  }
  commandLine += " \"" + htmldir + "\"";
  std::string oldDir = Dir::currentDirPath();
  Dir::setCurrent(g_inputDir.absPath());
  //printf("CommandLine=[%s]\n",qPrint(commandLine));
  Portable::sysTimerStart();
  bool result=Portable::system("htags",commandLine,FALSE)==0;
  if (!result)
  {
    err("Problems running %s. Check your installation\n", "htags");
  }
  Portable::sysTimerStop();
  Dir::setCurrent(oldDir);
  return result;
}
References Dir::absPath(), Config_getBool, Config_getList, Config_getString, Dir::currentDirPath(), err(), Dir::exists(), FALSE, g_inputDir, QCString::isEmpty(), Dir::setCurrent(), Dir::setPath(), string, Portable::system(), Portable::sysTimerStart(), and Portable::sysTimerStop().
Referenced by generateOutput().
execute() [2/2]
static bool Htags::execute (const QCString & htmldir) [static]
loadFilemap() [1/2]
bool Htags::loadFilemap (const QCString & htmlDir) [static]
load filemap and make index.
Parameters
htmlDir of HTML directory generated by htags(1).
Return values
TRUE success
FALSE error
Definition at line 109 of file htags.cpp.
{
  QCString fileMapName = htmlDir+"/HTML/FILEMAP";
  FileInfo fi(fileMapName.str());
  /*
   * Construct FILEMAP dictionary.
   *
   * In FILEMAP, URL includes 'html' suffix but we cut it off according
   * to the method of FileDef class.
   *
   * FILEMAP format:
   * <NAME>\t<HREF>.html\n
   * QDICT:
   * dict[<NAME>] = <HREF>
   */
  if (fi.exists() && fi.isReadable())
  {
    std::ifstream f(fileMapName.str(),std::ifstream::in);
    if (f.is_open())
    {
      std::string lineStr;
      while (getline(f,lineStr))
      {
        QCString line(lineStr);
        //printf("Read line: %s",qPrint(line));
        int sep = line.find('\t');
        if (sep!=-1)
        {
          QCString key = line.left(sep).stripWhiteSpace();
          QCString value = line.mid(sep+1).stripWhiteSpace();
          int ext=value.findRev('.');
          if (ext!=-1) value=value.left(ext); // strip extension
          g_symbolMap.insert(std::make_pair(key.str(),value.str()));
          //printf("Key/Value=(%s,%s)\n",qPrint(key),qPrint(value));
        }
      }
      return true;
    }
    else
    {
      err("file %s cannot be opened\n",qPrint(fileMapName));
    }
  }
  return false;
}
References err(), FileInfo::exists(), f, QCString::find(), QCString::findRev(), g_symbolMap, FileInfo::isReadable(), QCString::left(), QCString::mid(), qPrint(), QCString::str(), string, and QCString::stripWhiteSpace().
Referenced by generateOutput().
loadFilemap() [2/2]
static bool Htags::loadFilemap (const QCString & htmldir) [static]
path2URL() [1/2]
QCString Htags::path2URL (const QCString & path) [static]
convert path name into the url in the hypertext generated by htags.
Parameters
path path name
Returns
URL NULL: not found.
Definition at line 159 of file htags.cpp.
{
  QCString url,symName=path;
  QCString dir = g_inputDir.absPath();
  size_t dl=dir.length();
  if (symName.length()>dl+1)
  {
    symName = symName.mid(dl+1);
  }
  if (!symName.isEmpty())
  {
    auto it = g_symbolMap.find(symName.str());
    //printf("path2URL=%s symName=%s result=%p\n",qPrint(path),qPrint(symName),result);
    if (it!=g_symbolMap.end())
    {
      url = QCString("HTML/"+it->second);
    }
  }
  return url;
}
References Dir::absPath(), g_inputDir, g_symbolMap, QCString::isEmpty(), QCString::length(), QCString::mid(), QCString::str(), and setup::url.
Referenced by FileDefImpl::getSourceFileBase().
path2URL() [2/2]
static QCString Htags::path2URL (const QCString & path) [static]
Member Data Documentation
useHtags
static bool Htags::useHtags = FALSE [static]
Definition at line 23 of file htags.h.
Referenced by generateFileSources(), generateOutput(), DefinitionImpl::getSourceAnchor(), and FileDefImpl::getSourceFileBase().
The documentation for this struct was generated from the following files:
doxygen/build/doxygen/src/htags.h
doxygen/src/htags.h
doxygen/build/doxygen/src/htags.cpp
doxygen/src/htags.cpp