StyleData Struct Reference
#include <rtfstyle.h>
Public Member Functions
StyleData ()=default
StyleData (const std::string &reference, const std::string &definition)
bool setStyle (const std::string &command, const std::string &styleName)
const char * reference () const
const char * definition () const
uint index () const
StyleData ()=default
StyleData (const std::string &reference, const std::string &definition)
bool setStyle (const std::string &command, const std::string &styleName)
const char * reference () const
const char * definition () const
uint index () const
Private Attributes
uint m_index = 0
std::string m_reference
std::string m_definition
Detailed Description
Definition at line 48 of file rtfstyle.h.
Constructor & Destructor Documentation
StyleData() [1/4]
StyleData::StyleData () [default]
StyleData() [2/4]
StyleData::StyleData (const std::string & reference, const std::string & definition)
Definition at line 237 of file rtfstyle.cpp.
{
  reg::Match match;
  if (reg::search(reference,match,s_clause))
  {
    m_index = static_cast<int>(std::stoul(match[1].str()));
  }
  else // error
  {
    m_index = 0;
  }
  m_reference = reference;
  m_definition = definition;
}
References definition(), m_definition, m_index, m_reference, reg::match(), reference(), s_clause, and reg::search().
StyleData() [3/4]
StyleData::StyleData () [default]
StyleData() [4/4]
StyleData::StyleData (const std::string & reference, const std::string & definition)
Member Function Documentation
definition() [1/2]
const char * StyleData::definition () const [inline]
Definition at line 60 of file rtfstyle.h.
{ return m_definition.c_str(); }
References m_definition.
Referenced by doxmlparser.compound.memberdefType::__init__(), RTFGenerator::beginRTFDocument(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_definition(), doxmlparser.compound.memberdefType::hasContent_(), doxmlparser.compound.memberdefType::set_definition(), and StyleData().
definition() [2/2]
const char * StyleData::definition () const [inline]
Definition at line 60 of file rtfstyle.h.
{ return m_definition.c_str(); }
References m_definition.
Referenced by doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.memberdefType::buildChildren(), doxmlparser.compound.memberdefType::exportChildren(), doxmlparser.compound.memberdefType::get_definition(), doxmlparser.compound.memberdefType::hasContent_(), and doxmlparser.compound.memberdefType::set_definition().
index() [1/2]
uint StyleData::index () const [inline]
Definition at line 61 of file rtfstyle.h.
{ return m_index; }
References m_index.
Referenced by setStyle().
index() [2/2]
uint StyleData::index () const [inline]
Definition at line 61 of file rtfstyle.h.
{ return m_index; }
References m_index.
reference() [1/2]
const char * StyleData::reference () const [inline]
Definition at line 59 of file rtfstyle.h.
{ return m_reference.c_str(); }
References m_reference.
Referenced by doxmlparser.compound.tableofcontentsKindType::__init__(), RTFGenerator::beginRTFDocument(), doxmlparser.compound.tableofcontentsKindType::get_reference(), RTFDocVisitor::getStyle(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), doxmlparser.compound.tableofcontentsKindType::set_reference(), and StyleData().
reference() [2/2]
const char * StyleData::reference () const [inline]
Definition at line 59 of file rtfstyle.h.
{ return m_reference.c_str(); }
References m_reference.
Referenced by doxmlparser.compound.tableofcontentsKindType::__init__(), doxmlparser.compound.tableofcontentsKindType::get_reference(), doxmlparser.compound.tableofcontentsKindType::hasContent_(), and doxmlparser.compound.tableofcontentsKindType::set_reference().
setStyle() [1/2]
bool StyleData::setStyle (const std::string & command, const std::string & styleName)
Definition at line 252 of file rtfstyle.cpp.
{
  reg::Match match;
  if (!reg::search(command,match,s_clause))
  {
    err("Style sheet '%s' contains no '\\s' clause.\n{%s}", styleName.c_str(), command.c_str());
    return false;
  }
  m_index = static_cast<int>(std::stoul(match[1].str()));
  size_t index = command.find("\\sbasedon");
  if (index!=std::string::npos)
  {
    m_reference = command.substr(0,index);
    m_definition = command.substr(index);
  }
  return true;
}
References err(), index(), m_definition, m_index, m_reference, reg::match(), s_clause, and reg::search().
Referenced by loadStylesheet().
setStyle() [2/2]
bool StyleData::setStyle (const std::string & command, const std::string & styleName)
Member Data Documentation
m_definition
std::string StyleData::m_definition [private]
Definition at line 66 of file rtfstyle.h.
Referenced by definition(), setStyle(), and StyleData().
m_index
uint StyleData::m_index = 0 [private]
Definition at line 64 of file rtfstyle.h.
Referenced by index(), setStyle(), and StyleData().
m_reference
std::string StyleData::m_reference [private]
Definition at line 65 of file rtfstyle.h.
Referenced by reference(), setStyle(), and StyleData().
The documentation for this struct was generated from the following files:
doxygen/build/doxygen/src/rtfstyle.h
doxygen/src/rtfstyle.h
doxygen/build/doxygen/src/rtfstyle.cpp
doxygen/src/rtfstyle.cpp