LayoutDocEntry Struct Reference
Base class representing a piece of a documentation page.
#include <layout.h>
Public Types
enum Kind {
MemberGroups
, MemberDeclStart
, MemberDeclEnd
, MemberDecl
,
MemberDefStart
, MemberDefEnd
, MemberDef
, BriefDesc
,
DetailedDesc
, AuthorSection
, ClassIncludes
, ClassInlineClasses
,
ClassInheritanceGraph
, ClassNestedClasses
, ClassCollaborationGraph
, ClassAllMembersLink
,
ClassUsedFiles
, ConceptDefinition
, NamespaceNestedNamespaces
, NamespaceNestedConstantGroups
,
NamespaceClasses
, NamespaceConcepts
, NamespaceInterfaces
, NamespaceStructs
,
NamespaceExceptions
, NamespaceInlineClasses
, FileClasses
, FileConcepts
,
FileInterfaces
, FileStructs
, FileExceptions
, FileConstantGroups
,
FileNamespaces
, FileIncludes
, FileIncludeGraph
, FileIncludedByGraph
,
FileSourceLink
, FileInlineClasses
, GroupClasses
, GroupConcepts
,
GroupInlineClasses
, GroupNamespaces
, GroupDirs
, GroupNestedGroups
,
GroupFiles
, GroupGraph
, GroupPageDocs
, DirSubDirs
,
DirFiles
, DirGraph
, MemberGroups
, MemberDeclStart
,
MemberDeclEnd
, MemberDecl
, MemberDefStart
, MemberDefEnd
,
MemberDef
, BriefDesc
, DetailedDesc
, AuthorSection
,
ClassIncludes
, ClassInlineClasses
, ClassInheritanceGraph
, ClassNestedClasses
,
ClassCollaborationGraph
, ClassAllMembersLink
, ClassUsedFiles
, ConceptDefinition
,
NamespaceNestedNamespaces
, NamespaceNestedConstantGroups
, NamespaceClasses
, NamespaceConcepts
,
NamespaceInterfaces
, NamespaceStructs
, NamespaceExceptions
, NamespaceInlineClasses
,
FileClasses
, FileConcepts
, FileInterfaces
, FileStructs
,
FileExceptions
, FileConstantGroups
, FileNamespaces
, FileIncludes
,
FileIncludeGraph
, FileIncludedByGraph
, FileSourceLink
, FileInlineClasses
,
GroupClasses
, GroupConcepts
, GroupInlineClasses
, GroupNamespaces
,
GroupDirs
, GroupNestedGroups
, GroupFiles
, GroupGraph
,
GroupPageDocs
, DirSubDirs
, DirFiles
, DirGraph
 }
enum Kind {
MemberGroups
, MemberDeclStart
, MemberDeclEnd
, MemberDecl
,
MemberDefStart
, MemberDefEnd
, MemberDef
, BriefDesc
,
DetailedDesc
, AuthorSection
, ClassIncludes
, ClassInlineClasses
,
ClassInheritanceGraph
, ClassNestedClasses
, ClassCollaborationGraph
, ClassAllMembersLink
,
ClassUsedFiles
, ConceptDefinition
, NamespaceNestedNamespaces
, NamespaceNestedConstantGroups
,
NamespaceClasses
, NamespaceConcepts
, NamespaceInterfaces
, NamespaceStructs
,
NamespaceExceptions
, NamespaceInlineClasses
, FileClasses
, FileConcepts
,
FileInterfaces
, FileStructs
, FileExceptions
, FileConstantGroups
,
FileNamespaces
, FileIncludes
, FileIncludeGraph
, FileIncludedByGraph
,
FileSourceLink
, FileInlineClasses
, GroupClasses
, GroupConcepts
,
GroupInlineClasses
, GroupNamespaces
, GroupDirs
, GroupNestedGroups
,
GroupFiles
, GroupGraph
, GroupPageDocs
, DirSubDirs
,
DirFiles
, DirGraph
, MemberGroups
, MemberDeclStart
,
MemberDeclEnd
, MemberDecl
, MemberDefStart
, MemberDefEnd
,
MemberDef
, BriefDesc
, DetailedDesc
, AuthorSection
,
ClassIncludes
, ClassInlineClasses
, ClassInheritanceGraph
, ClassNestedClasses
,
ClassCollaborationGraph
, ClassAllMembersLink
, ClassUsedFiles
, ConceptDefinition
,
NamespaceNestedNamespaces
, NamespaceNestedConstantGroups
, NamespaceClasses
, NamespaceConcepts
,
NamespaceInterfaces
, NamespaceStructs
, NamespaceExceptions
, NamespaceInlineClasses
,
FileClasses
, FileConcepts
, FileInterfaces
, FileStructs
,
FileExceptions
, FileConstantGroups
, FileNamespaces
, FileIncludes
,
FileIncludeGraph
, FileIncludedByGraph
, FileSourceLink
, FileInlineClasses
,
GroupClasses
, GroupConcepts
, GroupInlineClasses
, GroupNamespaces
,
GroupDirs
, GroupNestedGroups
, GroupFiles
, GroupGraph
,
GroupPageDocs
, DirSubDirs
, DirFiles
, DirGraph
 }
Public Member Functions
virtual ~LayoutDocEntry ()=default
virtual Kind kind () const =0
virtual ~LayoutDocEntry ()=default
virtual Kind kind () const =0
Detailed Description
Base class representing a piece of a documentation page.
Definition at line 31 of file layout.h.
Member Enumeration Documentation
Kind [1/2]
enum LayoutDocEntry::Kind
Enumerator
MemberGroups
MemberDeclStart
MemberDeclEnd
MemberDecl
MemberDefStart
MemberDefEnd
MemberDef
BriefDesc
DetailedDesc
AuthorSection
ClassIncludes
ClassInlineClasses
ClassInheritanceGraph
ClassNestedClasses
ClassCollaborationGraph
ClassAllMembersLink
ClassUsedFiles
ConceptDefinition
NamespaceNestedNamespaces
NamespaceNestedConstantGroups
NamespaceClasses
NamespaceConcepts
NamespaceInterfaces
NamespaceStructs
NamespaceExceptions
NamespaceInlineClasses
FileClasses
FileConcepts
FileInterfaces
FileStructs
FileExceptions
FileConstantGroups
FileNamespaces
FileIncludes
FileIncludeGraph
FileIncludedByGraph
FileSourceLink
FileInlineClasses
GroupClasses
GroupConcepts
GroupInlineClasses
GroupNamespaces
GroupDirs
GroupNestedGroups
GroupFiles
GroupGraph
GroupPageDocs
DirSubDirs
DirFiles
DirGraph
MemberGroups
MemberDeclStart
MemberDeclEnd
MemberDecl
MemberDefStart
MemberDefEnd
MemberDef
BriefDesc
DetailedDesc
AuthorSection
ClassIncludes
ClassInlineClasses
ClassInheritanceGraph
ClassNestedClasses
ClassCollaborationGraph
ClassAllMembersLink
ClassUsedFiles
ConceptDefinition
NamespaceNestedNamespaces
NamespaceNestedConstantGroups
NamespaceClasses
NamespaceConcepts
NamespaceInterfaces
NamespaceStructs
NamespaceExceptions
NamespaceInlineClasses
FileClasses
FileConcepts
FileInterfaces
FileStructs
FileExceptions
FileConstantGroups
FileNamespaces
FileIncludes
FileIncludeGraph
FileIncludedByGraph
FileSourceLink
FileInlineClasses
GroupClasses
GroupConcepts
GroupInlineClasses
GroupNamespaces
GroupDirs
GroupNestedGroups
GroupFiles
GroupGraph
GroupPageDocs
DirSubDirs
DirFiles
DirGraph
Definition at line 34 of file layout.h.
            {
              // Generic items for all pages
              MemberGroups,
              MemberDeclStart, MemberDeclEnd, MemberDecl,
              MemberDefStart, MemberDefEnd, MemberDef,
              BriefDesc, DetailedDesc,
              AuthorSection,
              // Class specific items
              ClassIncludes, ClassInlineClasses,
              ClassInheritanceGraph, ClassNestedClasses,
              ClassCollaborationGraph, ClassAllMembersLink,
              ClassUsedFiles,
              // Concept specific items
              ConceptDefinition,
              // Namespace specific items
              NamespaceNestedNamespaces, NamespaceNestedConstantGroups,
              NamespaceClasses, NamespaceConcepts, NamespaceInterfaces, NamespaceStructs, NamespaceExceptions,
              NamespaceInlineClasses,
              // File specific items
              FileClasses, FileConcepts, FileInterfaces, FileStructs, FileExceptions, FileConstantGroups, FileNamespaces,
              FileIncludes, FileIncludeGraph,
              FileIncludedByGraph, FileSourceLink,
              FileInlineClasses,
              // Group specific items
              GroupClasses, GroupConcepts, GroupInlineClasses, GroupNamespaces,
              GroupDirs, GroupNestedGroups, GroupFiles,
              GroupGraph, GroupPageDocs,
              // Directory specific items
              DirSubDirs, DirFiles, DirGraph
            };
Kind [2/2]
enum LayoutDocEntry::Kind
Enumerator
MemberGroups
MemberDeclStart
MemberDeclEnd
MemberDecl
MemberDefStart
MemberDefEnd
MemberDef
BriefDesc
DetailedDesc
AuthorSection
ClassIncludes
ClassInlineClasses
ClassInheritanceGraph
ClassNestedClasses
ClassCollaborationGraph
ClassAllMembersLink
ClassUsedFiles
ConceptDefinition
NamespaceNestedNamespaces
NamespaceNestedConstantGroups
NamespaceClasses
NamespaceConcepts
NamespaceInterfaces
NamespaceStructs
NamespaceExceptions
NamespaceInlineClasses
FileClasses
FileConcepts
FileInterfaces
FileStructs
FileExceptions
FileConstantGroups
FileNamespaces
FileIncludes
FileIncludeGraph
FileIncludedByGraph
FileSourceLink
FileInlineClasses
GroupClasses
GroupConcepts
GroupInlineClasses
GroupNamespaces
GroupDirs
GroupNestedGroups
GroupFiles
GroupGraph
GroupPageDocs
DirSubDirs
DirFiles
DirGraph
MemberGroups
MemberDeclStart
MemberDeclEnd
MemberDecl
MemberDefStart
MemberDefEnd
MemberDef
BriefDesc
DetailedDesc
AuthorSection
ClassIncludes
ClassInlineClasses
ClassInheritanceGraph
ClassNestedClasses
ClassCollaborationGraph
ClassAllMembersLink
ClassUsedFiles
ConceptDefinition
NamespaceNestedNamespaces
NamespaceNestedConstantGroups
NamespaceClasses
NamespaceConcepts
NamespaceInterfaces
NamespaceStructs
NamespaceExceptions
NamespaceInlineClasses
FileClasses
FileConcepts
FileInterfaces
FileStructs
FileExceptions
FileConstantGroups
FileNamespaces
FileIncludes
FileIncludeGraph
FileIncludedByGraph
FileSourceLink
FileInlineClasses
GroupClasses
GroupConcepts
GroupInlineClasses
GroupNamespaces
GroupDirs
GroupNestedGroups
GroupFiles
GroupGraph
GroupPageDocs
DirSubDirs
DirFiles
DirGraph
Definition at line 34 of file layout.h.
            {
              // Generic items for all pages
              MemberGroups,
              MemberDeclStart, MemberDeclEnd, MemberDecl,
              MemberDefStart, MemberDefEnd, MemberDef,
              BriefDesc, DetailedDesc,
              AuthorSection,
              // Class specific items
              ClassIncludes, ClassInlineClasses,
              ClassInheritanceGraph, ClassNestedClasses,
              ClassCollaborationGraph, ClassAllMembersLink,
              ClassUsedFiles,
              // Concept specific items
              ConceptDefinition,
              // Namespace specific items
              NamespaceNestedNamespaces, NamespaceNestedConstantGroups,
              NamespaceClasses, NamespaceConcepts, NamespaceInterfaces, NamespaceStructs, NamespaceExceptions,
              NamespaceInlineClasses,
              // File specific items
              FileClasses, FileConcepts, FileInterfaces, FileStructs, FileExceptions, FileConstantGroups, FileNamespaces,
              FileIncludes, FileIncludeGraph,
              FileIncludedByGraph, FileSourceLink,
              FileInlineClasses,
              // Group specific items
              GroupClasses, GroupConcepts, GroupInlineClasses, GroupNamespaces,
              GroupDirs, GroupNestedGroups, GroupFiles,
              GroupGraph, GroupPageDocs,
              // Directory specific items
              DirSubDirs, DirFiles, DirGraph
            };
Constructor & Destructor Documentation
 LayoutDocEntry() [1/2]
virtual LayoutDocEntry::~LayoutDocEntry () [virtual], [default]
 LayoutDocEntry() [2/2]
virtual LayoutDocEntry::~LayoutDocEntry () [virtual], [default]
Member Function Documentation
kind() [1/2]
virtual Kind LayoutDocEntry::kind () const [pure virtual]
Implemented in LayoutDocEntrySimple, LayoutDocEntryMemberDecl, LayoutDocEntryMemberDef, LayoutDocEntrySimple, LayoutDocEntryMemberDecl, and LayoutDocEntryMemberDef.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.sectiondefType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.docParamListType::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.sectiondefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.docSimpleSectType::buildAttributes(), doxmlparser.compound.docParamListType::buildAttributes(), doxmlparser.index.CompoundType::buildAttributes(), doxmlparser.index.MemberType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.index.CompoundType::exportAttributes(), doxmlparser.compound.docParamListType::exportAttributes(), doxmlparser.compound.docSimpleSectType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.index.MemberType::exportAttributes(), doxmlparser.compound.sectiondefType::exportAttributes(), doxmlparser.compound.compounddefType::get_kind(), doxmlparser.compound.sectiondefType::get_kind(), doxmlparser.compound.memberdefType::get_kind(), doxmlparser.compound.docSimpleSectType::get_kind(), doxmlparser.compound.docParamListType::get_kind(), doxmlparser.index.CompoundType::get_kind(), doxmlparser.index.MemberType::get_kind(), doxmlparser.compound.compounddefType::set_kind(), doxmlparser.compound.sectiondefType::set_kind(), doxmlparser.compound.memberdefType::set_kind(), doxmlparser.compound.docSimpleSectType::set_kind(), doxmlparser.compound.docParamListType::set_kind(), doxmlparser.index.CompoundType::set_kind(), and doxmlparser.index.MemberType::set_kind().
kind() [2/2]
virtual Kind LayoutDocEntry::kind () const [pure virtual]
Implemented in LayoutDocEntrySimple, LayoutDocEntryMemberDecl, LayoutDocEntryMemberDef, LayoutDocEntrySimple, LayoutDocEntryMemberDecl, and LayoutDocEntryMemberDef.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.sectiondefType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.docParamListType::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.sectiondefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.docSimpleSectType::buildAttributes(), doxmlparser.compound.docParamListType::buildAttributes(), doxmlparser.index.CompoundType::buildAttributes(), doxmlparser.index.MemberType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.index.CompoundType::exportAttributes(), doxmlparser.compound.docParamListType::exportAttributes(), doxmlparser.compound.docSimpleSectType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.index.MemberType::exportAttributes(), doxmlparser.compound.sectiondefType::exportAttributes(), doxmlparser.compound.compounddefType::get_kind(), doxmlparser.compound.sectiondefType::get_kind(), doxmlparser.compound.memberdefType::get_kind(), doxmlparser.compound.docSimpleSectType::get_kind(), doxmlparser.compound.docParamListType::get_kind(), doxmlparser.index.CompoundType::get_kind(), doxmlparser.index.MemberType::get_kind(), doxmlparser.compound.compounddefType::set_kind(), doxmlparser.compound.sectiondefType::set_kind(), doxmlparser.compound.memberdefType::set_kind(), doxmlparser.compound.docSimpleSectType::set_kind(), doxmlparser.compound.docParamListType::set_kind(), doxmlparser.index.CompoundType::set_kind(), and doxmlparser.index.MemberType::set_kind().
The documentation for this struct was generated from the following files:
doxygen/build/doxygen/src/layout.h
doxygen/src/layout.h