DocNodeList Struct Reference
#include <docnode.h>
Public Member Functions
template<class T , class... Args>
DocNodeVariant * append (Args &&... args)
void move_append (DocNodeList &l)
template<class T >
T * get_last ()
template<class T , class... Args>
DocNodeVariant * append (Args &&... args)
void move_append (DocNodeList &l)
template<class T >
T * get_last ()
Additional Inherited Members
Detailed Description
Definition at line 111 of file docnode.h.
Member Function Documentation
append() [1/2]
template<class T , class... Args>
DocNodeVariant * DocNodeList::append (Args &&... args) [inline]
Append a new DocNodeVariant to the list by constructing it with type T and parameters Args.
Definition at line 1327 of file docnode.h.
{
  emplace_back(T(std::forward<Args>(args)...));
  return &back();
}
References GrowVector< DocNodeVariant >::back(), and GrowVector< DocNodeVariant >::emplace_back().
Referenced by DocSimpleSect::appendLinkWord(), DocParser::defaultHandleToken(), DocParser::errorHandleDefaultToken(), DocParser::handleAHref(), DocParser::handleAnchor(), DocPara::handleCite(), DocPara::handleCommand(), DocPara::handleEmoji(), DocPara::handleFile(), DocPara::handleHtmlEndTag(), DocPara::handleHtmlHeader(), DocPara::handleHtmlStartTag(), DocParser::handleImage(), DocParser::handleImg(), DocPara::handleInclude(), DocPara::handleIncludeOperator(), DocParser::handleInternalRef(), DocPara::handleLink(), DocParser::handleLinkedWord(), DocParser::handleParameterType(), DocPara::handleParamSection(), DocParser::handlePendingStyleCommands(), DocPara::handleRef(), DocPara::handleShowDate(), DocPara::handleSimpleSection(), DocPara::handleStartCode(), DocParser::handleStyleEnter(), DocParser::handleStyleLeave(), DocPara::handleVhdlFlow(), DocPara::handleXRefItem(), DocParser::internalValidatingParseDoc(), DocAutoList::parse(), DocAutoListItem::parse(), DocHRef::parse(), DocHtmlDetails::parse(), DocHtmlHeader::parse(), DocHtmlDescTitle::parse(), DocHtmlDescList::parse(), DocSection::parse(), DocSecRefList::parse(), DocParBlock::parse(), DocSimpleList::parse(), DocHtmlList::parse(), DocPara::parse(), DocHtmlListItem::parse(), DocHtmlDescData::parse(), DocHtmlCell::parse(), DocHtmlRow::parse(), DocHtmlTable::parse(), DocHtmlBlockQuote::parse(), DocText::parse(), DocRoot::parse(), DocSimpleSect::parse(), DocLink::parse(), DocParamList::parse(), DocParamSect::parse(), DocInternal::parse(), DocTitle::parseFromString(), DocHtmlList::parseXml(), DocSimpleSect::parseXml(), DocHtmlListItem::parseXml(), DocHtmlCell::parseXml(), DocHtmlTable::parseXml(), DocHtmlRow::parseXml(), and DocParamList::parseXml().
append() [2/2]
template<class T , class... Args>
DocNodeVariant * DocNodeList::append (Args &&... args)
Append a new DocNodeVariant to the list by constructing it with type T and parameters Args.
get_last() [1/2]
template<class T >
T * DocNodeList::get_last [inline]
Returns a pointer to the last element in the list if that element exists and holds a T, otherwise nullptr is returned.
Definition at line 1343 of file docnode.h.
{
  return std::get_if<T>(&back());
}
References GrowVector< DocNodeVariant >::back().
Referenced by DocSimpleSect::appendLinkWord(), DocParser::handleAHref(), DocPara::handleCommand(), DocPara::handleFile(), DocPara::handleHtmlHeader(), DocPara::handleHtmlStartTag(), DocParser::handleImage(), DocPara::handleInclude(), DocPara::handleIncludeOperator(), DocParser::handleInternalRef(), DocPara::handleLink(), DocPara::handleParamSection(), DocPara::handleRef(), DocPara::handleSimpleSection(), DocPara::handleVhdlFlow(), DocPara::handleXRefItem(), DocParser::internalValidatingParseDoc(), DocAutoList::parse(), DocAutoListItem::parse(), DocHtmlDetails::parse(), DocHtmlDescTitle::parse(), DocHtmlDescList::parse(), DocSection::parse(), DocSecRefList::parse(), DocParBlock::parse(), DocSimpleList::parse(), DocHtmlList::parse(), DocPara::parse(), DocHtmlListItem::parse(), DocHtmlDescData::parse(), DocHtmlCell::parse(), DocHtmlRow::parse(), DocHtmlTable::parse(), DocHtmlBlockQuote::parse(), DocRoot::parse(), DocSimpleSect::parse(), DocParamList::parse(), DocParamSect::parse(), DocInternal::parse(), DocHtmlList::parseXml(), DocSimpleSect::parseXml(), DocHtmlListItem::parseXml(), DocHtmlCell::parseXml(), DocHtmlTable::parseXml(), DocHtmlRow::parseXml(), and DocParamList::parseXml().
get_last() [2/2]
template<class T >
T * DocNodeList::get_last ()
Returns a pointer to the last element in the list if that element exists and holds a T, otherwise nullptr is returned.
move_append() [1/2]
void DocNodeList::move_append (DocNodeList & l) [inline]
moves the element of list l at the end of this list. List l will become empty.
Definition at line 1333 of file docnode.h.
{
  for (auto &&elem : elements)
  {
    emplace_back(std::move(elem));
  }
  elements.clear();
}
References GrowVector< T >::clear(), and GrowVector< DocNodeVariant >::emplace_back().
Referenced by flattenParagraphs().
move_append() [2/2]
void DocNodeList::move_append (DocNodeList & l)
moves the element of list l at the end of this list. List l will become empty.
The documentation for this struct was generated from the following files:
doxygen/build/doxygen/src/docnode.h
doxygen/src/docnode.h