LayoutNavEntry Struct Reference
Base class for the layout of a navigation item at the top of the HTML pages.
#include <layout.h>
Public Types
enum Kind {
None = -1
, MainPage
, Pages
, Modules
,
Namespaces
, NamespaceList
, NamespaceMembers
, Concepts
,
Classes
, ClassList
, ClassIndex
, ClassHierarchy
,
ClassMembers
, Interfaces
, InterfaceList
, InterfaceIndex
,
InterfaceHierarchy
, Structs
, StructList
, StructIndex
,
Exceptions
, ExceptionList
, ExceptionIndex
, ExceptionHierarchy
,
Files
, FileList
, FileGlobals
, Examples
,
User
, UserGroup
, None = -1
, MainPage
,
Pages
, Modules
, Namespaces
, NamespaceList
,
NamespaceMembers
, Concepts
, Classes
, ClassList
,
ClassIndex
, ClassHierarchy
, ClassMembers
, Interfaces
,
InterfaceList
, InterfaceIndex
, InterfaceHierarchy
, Structs
,
StructList
, StructIndex
, Exceptions
, ExceptionList
,
ExceptionIndex
, ExceptionHierarchy
, Files
, FileList
,
FileGlobals
, Examples
, User
, UserGroup
 }
enum Kind {
None = -1
, MainPage
, Pages
, Modules
,
Namespaces
, NamespaceList
, NamespaceMembers
, Concepts
,
Classes
, ClassList
, ClassIndex
, ClassHierarchy
,
ClassMembers
, Interfaces
, InterfaceList
, InterfaceIndex
,
InterfaceHierarchy
, Structs
, StructList
, StructIndex
,
Exceptions
, ExceptionList
, ExceptionIndex
, ExceptionHierarchy
,
Files
, FileList
, FileGlobals
, Examples
,
User
, UserGroup
, None = -1
, MainPage
,
Pages
, Modules
, Namespaces
, NamespaceList
,
NamespaceMembers
, Concepts
, Classes
, ClassList
,
ClassIndex
, ClassHierarchy
, ClassMembers
, Interfaces
,
InterfaceList
, InterfaceIndex
, InterfaceHierarchy
, Structs
,
StructList
, StructIndex
, Exceptions
, ExceptionList
,
ExceptionIndex
, ExceptionHierarchy
, Files
, FileList
,
FileGlobals
, Examples
, User
, UserGroup
 }
Public Member Functions
LayoutNavEntry (LayoutNavEntry *parent, Kind k, bool vs, const QCString &bf, const QCString &tl, const QCString &intro, bool prepend=false)
LayoutNavEntry * parent () const
Kind kind () const
QCString baseFile () const
QCString title () const
QCString intro () const
QCString url () const
bool visible ()
void clear ()
void addChild (LayoutNavEntry *e)
void prependChild (LayoutNavEntry *e)
const LayoutNavEntryList & children () const
LayoutNavEntry * find (LayoutNavEntry::Kind k, const QCString &file=QCString()) const
LayoutNavEntry (LayoutNavEntry *parent, Kind k, bool vs, const QCString &bf, const QCString &tl, const QCString &intro, bool prepend=false)
LayoutNavEntry * parent () const
Kind kind () const
QCString baseFile () const
QCString title () const
QCString intro () const
QCString url () const
bool visible ()
void clear ()
void addChild (LayoutNavEntry *e)
void prependChild (LayoutNavEntry *e)
const LayoutNavEntryList & children () const
LayoutNavEntry * find (LayoutNavEntry::Kind k, const QCString &file=QCString()) const
Private Member Functions
LayoutNavEntry ()
LayoutNavEntry ()
Private Attributes
LayoutNavEntry * m_parent
Kind m_kind
bool m_visible
QCString m_baseFile
QCString m_title
QCString m_intro
LayoutNavEntryList m_children
Friends
class LayoutDocManager
Detailed Description
Base class for the layout of a navigation item at the top of the HTML pages.
Definition at line 125 of file layout.h.
Member Enumeration Documentation
Kind [1/2]
enum LayoutNavEntry::Kind
Enumerator
None
MainPage
Pages
Modules
Namespaces
NamespaceList
NamespaceMembers
Concepts
Classes
ClassList
ClassIndex
ClassHierarchy
ClassMembers
Interfaces
InterfaceList
InterfaceIndex
InterfaceHierarchy
Structs
StructList
StructIndex
Exceptions
ExceptionList
ExceptionIndex
ExceptionHierarchy
Files
FileList
FileGlobals
Examples
User
UserGroup
None
MainPage
Pages
Modules
Namespaces
NamespaceList
NamespaceMembers
Concepts
Classes
ClassList
ClassIndex
ClassHierarchy
ClassMembers
Interfaces
InterfaceList
InterfaceIndex
InterfaceHierarchy
Structs
StructList
StructIndex
Exceptions
ExceptionList
ExceptionIndex
ExceptionHierarchy
Files
FileList
FileGlobals
Examples
User
UserGroup
Definition at line 128 of file layout.h.
              {
      None = -1,
      MainPage,
      Pages,
      Modules,
      Namespaces,
      NamespaceList,
      NamespaceMembers,
      Concepts,
      Classes,
      ClassList,
      ClassIndex,
      ClassHierarchy,
      ClassMembers,
      Interfaces,
      InterfaceList,
      InterfaceIndex,
      InterfaceHierarchy,
      Structs,
      StructList,
      StructIndex,
      Exceptions,
      ExceptionList,
      ExceptionIndex,
      ExceptionHierarchy,
      Files,
      FileList,
      FileGlobals,
      Examples,
      User,
      UserGroup
    };
Kind [2/2]
enum LayoutNavEntry::Kind
Enumerator
None
MainPage
Pages
Modules
Namespaces
NamespaceList
NamespaceMembers
Concepts
Classes
ClassList
ClassIndex
ClassHierarchy
ClassMembers
Interfaces
InterfaceList
InterfaceIndex
InterfaceHierarchy
Structs
StructList
StructIndex
Exceptions
ExceptionList
ExceptionIndex
ExceptionHierarchy
Files
FileList
FileGlobals
Examples
User
UserGroup
None
MainPage
Pages
Modules
Namespaces
NamespaceList
NamespaceMembers
Concepts
Classes
ClassList
ClassIndex
ClassHierarchy
ClassMembers
Interfaces
InterfaceList
InterfaceIndex
InterfaceHierarchy
Structs
StructList
StructIndex
Exceptions
ExceptionList
ExceptionIndex
ExceptionHierarchy
Files
FileList
FileGlobals
Examples
User
UserGroup
Definition at line 128 of file layout.h.
              {
      None = -1,
      MainPage,
      Pages,
      Modules,
      Namespaces,
      NamespaceList,
      NamespaceMembers,
      Concepts,
      Classes,
      ClassList,
      ClassIndex,
      ClassHierarchy,
      ClassMembers,
      Interfaces,
      InterfaceList,
      InterfaceIndex,
      InterfaceHierarchy,
      Structs,
      StructList,
      StructIndex,
      Exceptions,
      ExceptionList,
      ExceptionIndex,
      ExceptionHierarchy,
      Files,
      FileList,
      FileGlobals,
      Examples,
      User,
      UserGroup
    };
Constructor & Destructor Documentation
LayoutNavEntry() [1/4]
LayoutNavEntry::LayoutNavEntry (LayoutNavEntry * parent, Kind k, bool vs, const QCString & bf, const QCString & tl, const QCString & intro, bool prepend = false) [inline]
Definition at line 160 of file layout.h.
      : m_parent(parent), m_kind(k), m_visible(vs), m_baseFile(bf), m_title(tl), m_intro(intro)
    {
      if (parent)
      {
        if (prepend) parent->prependChild(this); else parent->addChild(this);
      }
    }
References addChild(), parent(), and prependChild().
LayoutNavEntry() [2/4]
LayoutNavEntry::LayoutNavEntry () [inline], [private]
Definition at line 183 of file layout.h.
: m_parent(0), m_kind(None), m_visible(true) {}
LayoutNavEntry() [3/4]
LayoutNavEntry::LayoutNavEntry (LayoutNavEntry * parent, Kind k, bool vs, const QCString & bf, const QCString & tl, const QCString & intro, bool prepend = false) [inline]
Definition at line 160 of file layout.h.
      : m_parent(parent), m_kind(k), m_visible(vs), m_baseFile(bf), m_title(tl), m_intro(intro)
    {
      if (parent)
      {
        if (prepend) parent->prependChild(this); else parent->addChild(this);
      }
    }
References addChild(), parent(), and prependChild().
LayoutNavEntry() [4/4]
LayoutNavEntry::LayoutNavEntry () [inline], [private]
Definition at line 183 of file layout.h.
: m_parent(0), m_kind(None), m_visible(true) {}
Member Function Documentation
addChild() [1/2]
void LayoutNavEntry::addChild (LayoutNavEntry * e) [inline]
Definition at line 177 of file layout.h.
{ m_children.push_back(std::unique_ptr<LayoutNavEntry>(e)); }
References e, and m_children.
Referenced by LayoutNavEntry().
addChild() [2/2]
void LayoutNavEntry::addChild (LayoutNavEntry * e) [inline]
Definition at line 177 of file layout.h.
{ m_children.push_back(std::unique_ptr<LayoutNavEntry>(e)); }
References e, and m_children.
baseFile() [1/2]
QCString LayoutNavEntry::baseFile () const [inline]
Definition at line 171 of file layout.h.
{ return m_baseFile; }
References m_baseFile.
Referenced by url(), and writeUserGroupStubPage().
baseFile() [2/2]
QCString LayoutNavEntry::baseFile () const [inline]
Definition at line 171 of file layout.h.
{ return m_baseFile; }
References m_baseFile.
children() [1/2]
const LayoutNavEntryList & LayoutNavEntry::children () const [inline]
Definition at line 179 of file layout.h.
{ return m_children; }
References m_children.
Referenced by renderQuickLinksAsJs(), renderQuickLinksAsTabs(), renderQuickLinksAsTree(), writeDefaultQuickLinks(), writeIndexHierarchy(), and writeUserGroupStubPage().
children() [2/2]
const LayoutNavEntryList & LayoutNavEntry::children () const [inline]
Definition at line 179 of file layout.h.
{ return m_children; }
References m_children.
clear() [1/2]
void LayoutNavEntry::clear () [inline]
Definition at line 176 of file layout.h.
{ m_children.clear(); }
References m_children.
Referenced by LayoutParser::startNavIndex().
clear() [2/2]
void LayoutNavEntry::clear () [inline]
Definition at line 176 of file layout.h.
{ m_children.clear(); }
References m_children.
find() [1/2]
LayoutNavEntry * LayoutNavEntry::find (LayoutNavEntry::Kind k, const QCString & file = QCString()) const
Definition at line 120 of file layout.cpp.
{
  LayoutNavEntry *result=0;
  for (const auto &entry : m_children)
  {
    // depth first search, needed to find the entry furthest from the
    // root in case an entry is in the tree twice
    result = entry->find(kind,file);
    if (result) return result;
    if (entry->kind()==kind && (file==QCString() || entry->baseFile()==file))
    {
      return entry.get();
    }
  }
  return result;
}
References caseconvert::file, find(), kind(), and m_children.
Referenced by LayoutParser::endNavIndex(), find(), generateJSNavTree(), writeAlphabeticalExceptionIndex(), writeAlphabeticalIndex(), writeAlphabeticalInterfaceIndex(), writeAlphabeticalStructIndex(), writeAnnotatedIndexGeneric(), writeClassMemberIndex(), writeClassMemberIndexFiltered(), writeConceptIndex(), writeDefaultQuickLinks(), writeExampleIndex(), writeFileIndex(), writeFileMemberIndex(), writeFileMemberIndexFiltered(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), writeNamespaceIndex(), writeNamespaceMemberIndex(), writeNamespaceMemberIndexFiltered(), writePageIndex(), and writePages().
find() [2/2]
LayoutNavEntry * LayoutNavEntry::find (LayoutNavEntry::Kind k, const QCString & file = QCString()) const
intro() [1/2]
QCString LayoutNavEntry::intro () const [inline]
Definition at line 173 of file layout.h.
{ return m_intro; }
References m_intro.
Referenced by writeAnnotatedIndexGeneric(), writeClassMemberIndexFiltered(), writeConceptIndex(), writeExampleIndex(), writeFileIndex(), writeFileMemberIndexFiltered(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), writeNamespaceIndex(), writeNamespaceMemberIndexFiltered(), and writePageIndex().
intro() [2/2]
QCString LayoutNavEntry::intro () const [inline]
Definition at line 173 of file layout.h.
{ return m_intro; }
References m_intro.
kind() [1/2]
Kind LayoutNavEntry::kind () const [inline]
Definition at line 170 of file layout.h.
{ return m_kind; }
References m_kind.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.sectiondefType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.docParamListType::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.sectiondefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.docSimpleSectType::buildAttributes(), doxmlparser.compound.docParamListType::buildAttributes(), doxmlparser.index.CompoundType::buildAttributes(), doxmlparser.index.MemberType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.index.CompoundType::exportAttributes(), doxmlparser.compound.docParamListType::exportAttributes(), doxmlparser.compound.docSimpleSectType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.index.MemberType::exportAttributes(), doxmlparser.compound.sectiondefType::exportAttributes(), find(), doxmlparser.compound.compounddefType::get_kind(), doxmlparser.compound.sectiondefType::get_kind(), doxmlparser.compound.memberdefType::get_kind(), doxmlparser.compound.docSimpleSectType::get_kind(), doxmlparser.compound.docParamListType::get_kind(), doxmlparser.index.CompoundType::get_kind(), doxmlparser.index.MemberType::get_kind(), doxmlparser.compound.compounddefType::set_kind(), doxmlparser.compound.sectiondefType::set_kind(), doxmlparser.compound.memberdefType::set_kind(), doxmlparser.compound.docSimpleSectType::set_kind(), doxmlparser.compound.docParamListType::set_kind(), doxmlparser.index.CompoundType::set_kind(), doxmlparser.index.MemberType::set_kind(), and url().
kind() [2/2]
Kind LayoutNavEntry::kind () const [inline]
Definition at line 170 of file layout.h.
{ return m_kind; }
References m_kind.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.sectiondefType::__init__(), doxmlparser.compound.memberdefType::__init__(), doxmlparser.compound.docParamListType::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.index.MemberType::__init__(), doxmlparser.index.CompoundType::__init__(), doxmlparser.compound.compounddefType::buildAttributes(), doxmlparser.compound.sectiondefType::buildAttributes(), doxmlparser.compound.memberdefType::buildAttributes(), doxmlparser.compound.docSimpleSectType::buildAttributes(), doxmlparser.compound.docParamListType::buildAttributes(), doxmlparser.index.CompoundType::buildAttributes(), doxmlparser.index.MemberType::buildAttributes(), doxmlparser.compound.compounddefType::exportAttributes(), doxmlparser.index.CompoundType::exportAttributes(), doxmlparser.compound.docParamListType::exportAttributes(), doxmlparser.compound.docSimpleSectType::exportAttributes(), doxmlparser.compound.memberdefType::exportAttributes(), doxmlparser.index.MemberType::exportAttributes(), doxmlparser.compound.sectiondefType::exportAttributes(), doxmlparser.compound.compounddefType::get_kind(), doxmlparser.compound.sectiondefType::get_kind(), doxmlparser.compound.memberdefType::get_kind(), doxmlparser.compound.docSimpleSectType::get_kind(), doxmlparser.compound.docParamListType::get_kind(), doxmlparser.index.CompoundType::get_kind(), doxmlparser.index.MemberType::get_kind(), doxmlparser.compound.compounddefType::set_kind(), doxmlparser.compound.sectiondefType::set_kind(), doxmlparser.compound.memberdefType::set_kind(), doxmlparser.compound.docSimpleSectType::set_kind(), doxmlparser.compound.docParamListType::set_kind(), doxmlparser.index.CompoundType::set_kind(), and doxmlparser.index.MemberType::set_kind().
parent() [1/2]
LayoutNavEntry * LayoutNavEntry::parent () const [inline]
Definition at line 169 of file layout.h.
{ return m_parent; }
References m_parent.
Referenced by LayoutParser::endNavEntry(), LayoutNavEntry(), and renderQuickLinksAsTabs().
parent() [2/2]
LayoutNavEntry * LayoutNavEntry::parent () const [inline]
Definition at line 169 of file layout.h.
{ return m_parent; }
References m_parent.
prependChild() [1/2]
void LayoutNavEntry::prependChild (LayoutNavEntry * e) [inline]
Definition at line 178 of file layout.h.
{ m_children.insert(m_children.begin(),std::unique_ptr<LayoutNavEntry>(e)); }
References e, and m_children.
Referenced by LayoutNavEntry().
prependChild() [2/2]
void LayoutNavEntry::prependChild (LayoutNavEntry * e) [inline]
Definition at line 178 of file layout.h.
{ m_children.insert(m_children.begin(),std::unique_ptr<LayoutNavEntry>(e)); }
References e, and m_children.
title() [1/2]
QCString LayoutNavEntry::title () const [inline]
Definition at line 172 of file layout.h.
{ return m_title; }
References m_title.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), generateJSNavTree(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), doxmlparser.compound.docSimpleSectType::set_title(), writeAlphabeticalExceptionIndex(), writeAlphabeticalIndex(), writeAlphabeticalInterfaceIndex(), writeAlphabeticalStructIndex(), writeAnnotatedIndexGeneric(), writeClassMemberIndex(), writeClassMemberIndexFiltered(), writeConceptIndex(), writeExampleIndex(), writeFileIndex(), writeFileMemberIndex(), writeFileMemberIndexFiltered(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), writeNamespaceIndex(), writeNamespaceMemberIndex(), writeNamespaceMemberIndexFiltered(), writePageIndex(), and writeUserGroupStubPage().
title() [2/2]
QCString LayoutNavEntry::title () const [inline]
Definition at line 172 of file layout.h.
{ return m_title; }
References m_title.
Referenced by doxmlparser.compound.compounddefType::__init__(), doxmlparser.compound.docSect1Type::__init__(), doxmlparser.compound.docSect4Type::__init__(), doxmlparser.compound.docSect2Type::__init__(), doxmlparser.compound.docSect3Type::__init__(), doxmlparser.compound.docSimpleSectType::__init__(), doxmlparser.compound.descriptionType::__init__(), doxmlparser.compound.docParaType::__init__(), doxmlparser.compound.docMarkupType::__init__(), doxmlparser.compound.docParaType::add_title(), doxmlparser.compound.docMarkupType::add_title(), doxmlparser.compound.compounddefType::buildChildren(), doxmlparser.compound.docSimpleSectType::buildChildren(), doxmlparser.compound.compounddefType::exportChildren(), doxmlparser.compound.docSect1Type::exportChildren(), doxmlparser.compound.docSect2Type::exportChildren(), doxmlparser.compound.docSect3Type::exportChildren(), doxmlparser.compound.docSect4Type::exportChildren(), doxmlparser.compound.docSimpleSectType::exportChildren(), doxmlparser.compound.compounddefType::get_title(), doxmlparser.compound.descriptionType::get_title(), doxmlparser.compound.docSect1Type::get_title(), doxmlparser.compound.docSect2Type::get_title(), doxmlparser.compound.docSect3Type::get_title(), doxmlparser.compound.docSect4Type::get_title(), doxmlparser.compound.docParaType::get_title(), doxmlparser.compound.docMarkupType::get_title(), doxmlparser.compound.docSimpleSectType::get_title(), doxmlparser.compound.compounddefType::hasContent_(), doxmlparser.compound.descriptionType::hasContent_(), doxmlparser.compound.docSect1Type::hasContent_(), doxmlparser.compound.docSect2Type::hasContent_(), doxmlparser.compound.docSect3Type::hasContent_(), doxmlparser.compound.docSect4Type::hasContent_(), doxmlparser.compound.docParaType::hasContent_(), doxmlparser.compound.docMarkupType::hasContent_(), doxmlparser.compound.docSimpleSectType::hasContent_(), doxmlparser.compound.docParaType::insert_title_at(), doxmlparser.compound.docMarkupType::insert_title_at(), doxmlparser.compound.docParaType::replace_title_at(), doxmlparser.compound.docMarkupType::replace_title_at(), doxmlparser.compound.compounddefType::set_title(), doxmlparser.compound.descriptionType::set_title(), doxmlparser.compound.docSect1Type::set_title(), doxmlparser.compound.docSect2Type::set_title(), doxmlparser.compound.docSect3Type::set_title(), doxmlparser.compound.docSect4Type::set_title(), doxmlparser.compound.docParaType::set_title(), doxmlparser.compound.docMarkupType::set_title(), and doxmlparser.compound.docSimpleSectType::set_title().
url() [1/2]
QCString LayoutNavEntry::url () const
Definition at line 138 of file layout.cpp.
{
  QCString url = baseFile().stripWhiteSpace();
  if ((kind()!=LayoutNavEntry::User && kind()!=LayoutNavEntry::UserGroup) ||
      (kind()==LayoutNavEntry::UserGroup && url.startsWith("usergroup")))
  {
    url = addHtmlExtensionIfMissing(url);
  }
  else if (url.startsWith("@ref ") || url.startsWith("\\ref "))
  {
    const Definition *d = 0;
    QCString anchor;
    bool found=FALSE;
    if (resolveLink(QCString(),url.mid(5).stripWhiteSpace(),TRUE,&d,anchor))
    {
      if (d && d->isLinkable())
      {
        url=addHtmlExtensionIfMissing(d->getOutputFileBase());
        if (!anchor.isEmpty())
        {
          url+="#"+anchor;
        }
        found=TRUE;
      }
    }
    if (!found)
    {
      msg("explicit link request to '%s' in layout file '%s' could not be resolved\n",qPrint(url.mid(5)),qPrint(Config_getString(LAYOUT_FILE)));
    }
  }
  //printf("LayoutNavEntry::url()=%s\n",qPrint(url));
  return url;
}
References addHtmlExtensionIfMissing(), baseFile(), Config_getString, FALSE, found, Definition::getOutputFileBase(), QCString::isEmpty(), Definition::isLinkable(), kind(), QCString::mid(), msg(), qPrint(), resolveLink(), QCString::startsWith(), QCString::stripWhiteSpace(), TRUE, url(), User, and UserGroup.
Referenced by doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docURLLink::buildAttributes(), doxmlparser.compound.docURLLink::exportAttributes(), doxmlparser.compound.docURLLink::get_url(), doxmlparser.compound.docURLLink::set_url(), and url().
url() [2/2]
QCString LayoutNavEntry::url () const
Referenced by doxmlparser.compound.docURLLink::__init__(), doxmlparser.compound.docURLLink::buildAttributes(), doxmlparser.compound.docURLLink::exportAttributes(), doxmlparser.compound.docURLLink::get_url(), and doxmlparser.compound.docURLLink::set_url().
visible() [1/2]
bool LayoutNavEntry::visible () [inline]
Definition at line 175 of file layout.h.
{ return m_visible; }
References m_visible.
Referenced by writeAlphabeticalExceptionIndex(), writeAlphabeticalIndex(), writeAlphabeticalInterfaceIndex(), writeAlphabeticalStructIndex(), writeAnnotatedIndexGeneric(), writeClassMemberIndex(), writeClassMemberIndexFiltered(), writeConceptIndex(), writeExampleIndex(), writeFileIndex(), writeFileMemberIndex(), writeFileMemberIndexFiltered(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), writeNamespaceIndex(), writeNamespaceMemberIndex(), writeNamespaceMemberIndexFiltered(), and writePages().
visible() [2/2]
bool LayoutNavEntry::visible () [inline]
Definition at line 175 of file layout.h.
{ return m_visible; }
References m_visible.
Friends And Related Function Documentation
LayoutDocManager
LayoutDocManager [friend]
Definition at line 191 of file layout.h.
Member Data Documentation
m_baseFile
QCString LayoutNavEntry::m_baseFile [private]
Definition at line 187 of file layout.h.
Referenced by baseFile().
m_children
LayoutNavEntryList LayoutNavEntry::m_children [private]
Definition at line 190 of file layout.h.
Referenced by addChild(), children(), clear(), find(), and prependChild().
m_intro
QCString LayoutNavEntry::m_intro [private]
Definition at line 189 of file layout.h.
Referenced by intro().
m_kind
Kind LayoutNavEntry::m_kind [private]
Definition at line 185 of file layout.h.
Referenced by kind().
m_parent
LayoutNavEntry * LayoutNavEntry::m_parent [private]
Definition at line 184 of file layout.h.
Referenced by parent().
m_title
QCString LayoutNavEntry::m_title [private]
Definition at line 188 of file layout.h.
Referenced by title().
m_visible
bool LayoutNavEntry::m_visible [private]
Definition at line 186 of file layout.h.
Referenced by visible().
The documentation for this struct was generated from the following files:
doxygen/build/doxygen/src/layout.h
doxygen/src/layout.h
doxygen/build/doxygen/src/layout.cpp
doxygen/src/layout.cpp